### ISSUE TITLE
Cannot ignore whitespace autocorrection

### ISSUE THREAD

**Issue by flipflop97** [WeblateOrg/weblate#10016]
### Describe the issue

As a translator, I cannot ignore/undo whitespace correction at the start/end of a string. These hard checks/corrections are a nice idea theoretically, but do not always work out in practice. For things like suffixes I sometimes need to use different whitespace than the original string. Please make it possible to undo this change or make it a warning.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Translate a string without whitespace with one with whitespace at the beginning.

### Expected behavior

I should be able to save it as intended

### Screenshots

![Screenshot_2023-09-22-21-55-52-52_3aea4af51f236e4932235fdada7d1643](https://github.com/WeblateOrg/weblate/assets/13943260/e9f64101-b24c-4cca-ae35-f8093f1c986f)
![Screenshot_2023-09-22-21-55-46-54_3aea4af51f236e4932235fdada7d1643](https://github.com/WeblateOrg/weblate/assets/13943260/99889bf4-8d87-44f9-b0df-d138d130c8fa)

### Exception traceback

```pytb
-
```

### How do you run Weblate?

weblate.org service

### Weblate versions

Hosted weblate

### Weblate deploy checks

```shell
-
```

### Additional context

-

**Comment by nijel** [comment]
That's why there is a way to override these in specific cases: https://docs.weblate.org/en/latest/user/checks.html#trailing-and-leading-whitespace-fixer

**Comment by flipflop97** [comment]
> That's why there is a way to override these in specific cases: https://docs.weblate.org/en/latest/user/checks.html#trailing-and-leading-whitespace-fixer

This is about disabling it as a **translator**, not as the project maintainer. As a translator I cannot undo or ignore this correction.

**Comment by nijel** [comment]
That's true, you need to ask project maintainer to do this change.

**Comment by comradekingu** [comment]
The suffix for thousand is "K", or "M".
