### ISSUE TITLE
Adding an automatic error report

### ISSUE THREAD

**Issue by gfghjjk** [WeblateOrg/weblate#10010]
### Describe the problem

I suggest making automatic error reports with automatic sending to the developer's server

### Describe the solution you'd like

if any error occurred, the error report was automatically sent to the developer's server

**Comment by nijel** [comment]
What kind of error do you mean and what you mean by developer's server?

In case the application crashes, Django sends e-mails to configured addresses. Weblate has also Sentry integration to collect more detailed info for such errors.
