### ISSUE TITLE
+ Language button is not working

### ISSUE THREAD

**Issue by BoFFire** [WeblateOrg/weblate#10027]
### Describe the issue

Hi, I noticed that the `+ Language` to add a language  is not working on Hosted Weblate.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Tap on `+ Language` on Dooz project https://hosted.weblate.org/projects/dooz/dooz/ to add a new language
2. Nothing seems to happen.

### Expected behavior

Expected : it will open a page to add anew language to the project.

### How do you run Weblate?

weblate.org service

### Additional context

More context : https://mstdn.fr/@ButterflyOfFire/111125425548237629

**Comment by BoFFire** [comment]
I tried to trick a bit by adding /add-lang/ to the URL but received no permission.
![IMG_20230925_121054](https://github.com/WeblateOrg/weblate/assets/42316180/49d7975d-6d50-4c80-810d-052d45dc1bbb)

**Comment by nijel** [comment]
It is disabled in the component settings (https://hosted.weblate.org/settings/dooz/dooz/#files), the button should not be shown in this case.
