### ISSUE TITLE
<source> and <target> are being translated at the same time and it confuses other XLIFF packages

### ISSUE THREAD

**Issue by FrostKiwi** [WeblateOrg/weblate#10024]
### Describe the issue

I have a Angular 13 + [ng-extract-i18n-merge](https://github.com/daniel-sc/ng-extract-i18n-merge) providing the XLIFF files, that Weblate ingests. The source language is English. The issue is when translators find corrections to be done in the English version as well and correct it, then Weblate changes the Source strings as well. So the Weblate English -> English perform a modification of both `<source></source>` and `<target></target>`. This works fine when deploying, but confuses [ng-extract-i18n-merge](https://github.com/daniel-sc/ng-extract-i18n-merge), which led to issue: https://github.com/daniel-sc/ng-extract-i18n-merge/issues/75

```XLIFF
...
      <trans-unit id="UploadExperimentRecords" datatype="html">
        <source>Upload Experiment Records</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app-routing.module.ts</context>
          <context context-type="linenumber">26</context>
        </context-group>
        <note priority="1" from="description">header</note>
      </trans-unit>
...
```
After correction:
```XLIFF
...
      <trans-unit id="UploadExperimentRecords" datatype="html" xml:space="preserve" approved="no">
        <source>Upload Deposition Records</source>
        <target state="translated">Upload Deposition Records</target>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app-routing.module.ts</context>
          <context context-type="linenumber">26</context>
        </context-group>
        <note priority="1" from="description">header</note>
      </trans-unit>
...
```

Is this something that can be configured or is Weblate always changing both?

The maintainer of [ng-extract-i18n-merge](https://github.com/daniel-sc/ng-extract-i18n-merge) suggested ( https://github.com/daniel-sc/ng-extract-i18n-merge/issues/75#issuecomment-1709819196 ) to create a separate translation file for English, in conjunction with a code modification in [ng-extract-i18n-merge](https://github.com/daniel-sc/ng-extract-i18n-merge).

Can Weblate be instructed to write modify only `<target>` in the English translation file in such a scenario? 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Correct entries in the original source language

### Expected behavior

XLIFF output changes the translation, not both the source and translation

### How do you run Weblate?

weblate.org service

### Weblate versions

<details>

```
weblate list_versions
 * Weblate: 4.18.2
 * Django: 4.2
 * siphashc: 2.1
 * translate-toolkit: 3.9.2
 * lxml: 4.9.2
 * Pillow: 9.5.0
 * nh3: 0.2.14
 * python-dateutil: 2.8.2
 * social-auth-core: 4.4.2
 * social-auth-app-django: 5.2.0
 * django-crispy-forms: 2.0
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.2
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.12.0
 * rapidfuzz: 3.1.1
 * openpyxl: 3.1.2
 * celery: 5.3.1
 * django-celery-beat: 2.5.0
 * kombu: 5.3.1
 * translation-finder: 2.15
 * weblate-language-data: 2023.5
 * html2text: 2020.1.16
 * pycairo: 1.24.0
 * PyGObject: 3.44.1
 * diff-match-patch: 20230430
 * requests: 2.28.2
 * django-redis: 5.3.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.28.0
 * Cython: 0.29.36
 * misaka: 2.1.1
 * GitPython: 3.1.32
 * borgbackup: 1.2.4
 * pyparsing: 3.0.9
 * pyahocorasick: 2.0.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.1.0
 * Python: 3.8.10
 * Git: 2.25.1
 * phply: 1.2.6
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.6.0
 * boto3: 1.26.165
 * zeep: 4.2.1
 * aeidon: 1.12
 * iniparse: 0.5
 * Mercurial: 6.5
 * git-review: 2.3.1
 * Redis server: 5.0.7
 * PostgreSQL server: 12.15
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp-jpn.dmgmori.net
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 5.4.0-150-generic (x86_64)
 ```
</details>

### Weblate deploy checks

<details>

System check identified some issues:

WARNINGS:
?: (security.W018) You should not have DEBUG set to True in deployment.
?: (weblate.W033.Subversion) Failure in loading VCS module for Subversion: git: 'svn' is not a git command. See 'git --help'.

The most similar commands are
        fsck
        mv
        show
 (1)
        HINT: https://docs.weblate.org/en/weblate-4.18.2/vcs.html

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.18.2/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.18.2/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 5.0.2.
        HINT: https://docs.weblate.org/en/weblate-4.18.2/admin/upgrade.html

System check identified 5 issues (1 silenced).
```
</details>


### Additional context

_No response_

**Comment by nijel** [comment]
You are probably using bilingual files as monolingual. In monolingual setup, Weblate updates source if it is present.

**Comment by FrostKiwi** [comment]
> You are probably using bilingual files as monolingual. In monolingual setup, Weblate updates source if it is present.

I think the files are monolingual?
My files setup is like this:
```
messages.de.xlf
messages.en.xlf
messages.ja.xlf
messages.ru.xlf
messages.xlf
```
One source and one target, with `message.xlf` and `messages.en.xlf` being the same to workaround https://github.com/daniel-sc/ng-extract-i18n-merge/issues/75#issuecomment-1709819196.
Is this maybe a case for [the configuration option `English (Developer)`](https://docs.weblate.org/en/weblate-4.18.2/admin/projects.html#source-language)?

**Comment by nijel** [comment]
If the files contain both source and translation, they are bilingual, see also https://docs.weblate.org/en/latest/formats.html#bilingual-and-monolingual-formats

**Comment by emmapeel2** [comment]
I have seen lots of problems generated by the 'edit source strings' and 'manage strings' options. 

I disable them in my repositories, and I stopped running into merge conflicts.

In fact, I think those options should be disabled by default, and cry with a red message if you enable them.

**Comment by FrostKiwi** [comment]
> I have seen lots of problems generated by the 'edit source strings' and 'manage strings' options.
> 
> I disable them in my repositories, and I stopped running into merge conflicts.
> 
> In fact, I think those options should be disabled by default, and cry with a red message if you enable them.

@emmapeel2 
Thx for sharing that experience.
Now I wonder how to handle typos in the source 🤔
Translators wanna translate and correct. I can't tell them "Go look in the program source". Have you tried setting up the solution proposed by @daniel-sc in https://github.com/daniel-sc/ng-extract-i18n-merge/issues/75#issuecomment-1709819196?

Basically: Setup a copy of the original source language `.xlf` to be a separate "English Corrected" translation and treat that as a separate language in Weblate?

Or in general, how would you handle the case when a translator comes with to you with _"Hey, the original source has a grammar mistake that needs fixing."_

**Comment by emmapeel2** [comment]
> > I have seen lots of problems generated by the 'edit source strings' and 'manage strings' options.
> > I disable them in my repositories, and I stopped running into merge conflicts.
> > In fact, I think those options should be disabled by default, and cry with a red message if you enable them.
> 
> @emmapeel2 Thx for sharing that experience. Now I wonder how to handle typos in the source 🤔 Translators wanna translate and correct. I can't tell them "Go look in the program source".

> Or in general, how would you handle the case when a translator comes with to you with _"Hey, the original source has a grammar mistake that needs fixing."_

- As we generate the strings 'on the program source', I encourage translators to start participating on the development process. I add the 'Repository browser' link, so they can access easily the string on the upstream repository. 
- I answer quickly to the comments for the source strings, and show translators where did I change the source (which sometimes takes a while to arrive)
- The documentation websites we translate have an 'Edit this page' link that also brings to the source, so when translators are previewing the translation they click on that button and change the source.
- We have the 'source string bug reporting address' set to the translators mailing list, where we receive the comments done in Weblate.

If I see translators with ideas about the text, I encourage them to participate on the 'upstream' repo instead of weblate. If they have no time, I rather get a comment on the string and I do the merge request for upstream.

**Comment by FrostKiwi** [comment]
> There is also https://docs.weblate.org/en/latest/workflows.html#quality-gateway-for-the-source-strings or https://docs.weblate.org/en/latest/workflows.html#source-strings-reviews which can help you in improving source strings.

Sounds like an excellent feature! We'll explore that one.
