### ISSUE TITLE
weblate user not selectable at gitlab web UI for hosted weblate push

### ISSUE THREAD

**Issue by Danfro** [WeblateOrg/weblate#10032]
### Describe the issue

The [docs](https://docs.weblate.org/en/latest/vcs.html#accessing-repositories-from-hosted-weblate) describe that I need to add a user to my repo to allow pushes by hosted weblate. This user is supposed to have the username "weblate", the name "Weblate push user" and the email "hosted@weblate.org".

When using gitlab there is no weblate user available at all when using the username only. Using the email address does work though. When using github the user can be selected via username, but in both cases it is not named "Weblate push user", only "Weblate" or "Weblate (bot)".

Although with github adding the weblate user works, the documentation is only slightly different. 
When working with gitlab this is not the case. Using an email - when a username is provided - is not common. When using the username a maintainer might even add a wrong user to their repo creating a security issue.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to gitlab repository, select members, select invite members, try to add the user _weblate_
2. Go to github repository, open repo settings, select collaborateurs, press "add members", try to add the user _weblate_

### Screenshots

![grafik](https://github.com/WeblateOrg/weblate/assets/37637312/979fbeb8-9d5d-4085-941b-5e6bf1b270fd)

![grafik](https://github.com/WeblateOrg/weblate/assets/37637312/935f9812-aedf-4262-b3b5-3aa1001f9c7a)

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
The user is there: https://gitlab.com/weblate. Maybe it is alreday added to the project?

**Comment by Danfro** [comment]
@nijel No, the user was not added to the repo before. I did try with one app of mine that never used weblate (since it was not published) and the issue arose with someone else doing that for the first time.

Using the email address did work in the end with Gitlab, so yes, the weblate user is there. It is just not accessible via the username in the Gitlab web UI as far as I can tell.

**Comment by nijel** [comment]
Seems like only few matches are shown based on username and there are too many users containing "weblate" now...

**Comment by nijel** [comment]
Let's clarify the docs to recommend searching by e-mail, see https://github.com/WeblateOrg/weblate/pull/10050

**Comment by Danfro** [comment]
Sounds good to me. Thanks a lot.

--
