### ISSUE TITLE
duplicate translation files error but no duplicate files in repo

### ISSUE THREAD

**Issue by Danfro** [WeblateOrg/weblate#10045]
### Describe the issue

For one of our [hosted weblate apps](https://hosted.weblate.org/projects/ubports/dekko/), we get the following error:

```
The component contains translation file for the source language.

Please consider the following:

    You might be using a monolingual translation file as a bilingual one. If that is the case, please set the monolingual base language file location. 

In case translation to the source language is desired, please change the source language in the component settings.
If the translation file for the source language is not needed, please remove it from the repository.
If the translation file for the source language is needed, but should be ignored by Weblate, please adjust the language filter to exclude it.

The following occurrences were found:
Language	Language codes	File names
English (United Kingdom) 	en_GB, en_GB 	i18n/en_GB.ts, i18n/en_GB.ts
Appeared 4 months ago, last seen 12 days ago

```

But on the repo I can't find a second `en_GB.ts` file.
I also tried resetting the component to match the repo and rescanning the language files. No change.

The app does contain some upstream code. Those contain some files with "en_GB.ts" in the filename like [libimap-en_GB.ts](https://gitlab.com/dekkan/messagingframework/-/blob/5f4aea93675a90e3f3c44369f61ce07838d7412d/plugins/messageservices/imap/libimap-en_GB.ts). Can this be the reason why the duplicate file error is raised?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Not sure how to describe this. It is the automated error check.
"Reset all changes in the Weblate repository " and "Rescan all translation files in the Weblate repository" did not help.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
> The component contains translation file for the source language.

You have en_GB as a source language, *and* you have en_GB file present. Please choose one of the recommended approaches to reconfigure Weblate, or to adjust your repository.

**Comment by Danfro** [comment]
@nijel many thanks for your answer. Unfortunately I did not find time to check this earlier.

I think to remember that there was no en.ts file when I did set up that component and then choose the en_GB.ts as source. But now there is a en.ts file.

I did delete the component and did set it up again with the en.ts as source. Now it works. Thanks a lot for your help.
