### ISSUE TITLE
Consolidate Celery tasks trigger on_commit

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#10049]
### Describe the problem

There are several occurrences of delayed Celery tasks trigger on transaction commit like this one:

https://github.com/WeblateOrg/weblate/blob/e48d8c71a21292fc9b650aef027de407a5341e91/weblate/trans/models/component.py#L3724-L3728

This code should be consolidated and reused instead of doing the same logic in several locations.

### Describe the solution you'd like

Switch to `delay_on_commit` once https://github.com/celery/celery/pull/8491 is released in Celery

**Comment by KristoferSoler** [comment]
Hi, I would like to take this issue once the feature you pointed is ready. 😄

**Comment by nijel** [comment]
That will definitely take some time as the PR is not even merged.

**Comment by KristoferSoler** [comment]
> That will definitely take some time as the PR is not even merged.

Don´t worry. I can wait. Meanwhile, I'll take a look at other issues. :)

**Comment by nijel** [comment]
Celery 5.4 with this is out, so we can follow up :-).
