### ISSUE TITLE
Site-wide add-ons

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#10052]
### Describe the problem

With upcoming external notification add-ons (like https://github.com/WeblateOrg/weblate/issues/7604 or https://github.com/WeblateOrg/fedora_messaging/), it will be useful to install them site-wide.

### Describe the solution you'd like

* Allow null value for `component` and `project` (see https://github.com/WeblateOrg/weblate/issues/10051) fields on the `Addon` model
* Adjust `AddonQuerySet.filter_component` to include add-ons with both being null
* Add site level UI for add-ons at /manage

### Additional context

See discussion at https://github.com/WeblateOrg/weblate/issues/7604 and https://github.com/WeblateOrg/weblate/discussions/9937

**Comment by emmapeel2** [comment]
Yes! I wished for this feature a lot, for example for the 'less commits' add-ons.

With lots of small components, I also miss a place where I can clearly see the add-ons all the components have in one place.

**Comment by Ionys320** [comment]
I agree too. I would like to have a common workflow for all of my projects (automated translation, languages generation, etc), it would be useful to have common plugins then!

**Comment by Ionys320** [comment]
I agree too. I would like to have a common workflow for all of my projects (automated translation, languages generation, etc), it would be useful to have common plugins then!
