### ISSUE TITLE
Project-wide installed add-ons

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#10051]
### Describe the problem

In many cases, it is desired to install add-on on a project level. Especially with a lot of components, it is cumbersome to keep the add-on configuration in sync.

### Describe the solution you'd like

* Add `project` foreign key field to the `Addon` model
* Adjust `AddonQuerySet.filter_component` to filter based on the project
* Change all `project_scope` add-on instances have a valid project reference and make sure that `project_scope` flagged add-ons are installed that way
* Remove `project_scope` from the database model (once existing instances are migrated)
* Add project level UI for add-ons

### Additional context

See discussion at https://github.com/WeblateOrg/weblate/issues/7604 and https://github.com/WeblateOrg/weblate/discussions/9937

**Comment by ParthS007** [comment]
Can you please brief more on this point:

> Change all project_scope add-on instances have a valid project reference and make sure that project_scope flagged add-ons are installed that way

What I understand here is inplace of `project_scope` in `LangaugeConsistencyAddon`, `RemovalAddon`, Remove the `project_scope` variable and use the project fk that is added in Addon.

**Comment by nijel** [comment]
It needs to stay on the add-on classes to indicate that this add-on is always installed at project scope. What needs to be changed is Addon model - instead of `project_scope` field, it will use a foreign key to Project. There needs to be a migration that will adjust the database data accordingly.
