### ISSUE TITLE
User within the "Sources" can't edit source strings

### ISSUE THREAD

**Issue by UncleSamSwiss** [WeblateOrg/weblate#10099]
### Describe the issue

A user X is in the "Sources" group within project Y.
This can be seen at: https://example.com/user/X/#groups
![image](https://github.com/WeblateOrg/weblate/assets/7595126/68330f42-6eed-4dad-83f5-becf58322c64)

But this user is not able to edit the source (English) strings:
![image](https://github.com/WeblateOrg/weblate/assets/7595126/16132b02-a1eb-410d-9f4b-7a1b905bbd1f)

According to the documentation at https://docs.weblate.org/en/latest/admin/access.html#managing-per-project-access-control he 
> Can edit source strings (if allowed in the [project settings](https://docs.weblate.org/en/latest/admin/projects.html#component-manage-units)) and source string info.

The project settings allow to edit the source file (and as an administrator I'm also able to do this):
![image](https://github.com/WeblateOrg/weblate/assets/7595126/da2f459e-c6a0-4af6-9d96-e5deb06a3e43)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Create a user with "Sources" group
2. Try to edit a string in the source language

### Expected behavior

The user can edit the string

### Screenshots

See above

### Exception traceback

```pytb
none
```

### How do you run Weblate?

Docker container

### Weblate versions

Weblate 5.0.1-dev

**Comment by nijel** [comment]
What roles does your "Sources" team have?

**Comment by UncleSamSwiss** [comment]
> What roles does your "Sources" team have?

There is no team "Sources", this is the internal Weblate group that is created by default:
![image](https://github.com/WeblateOrg/weblate/assets/7595126/9bcdbf23-a20e-4774-b15d-c61d520709ee)

It doesn't show up as a team in team management:
![image](https://github.com/WeblateOrg/weblate/assets/7595126/055d7511-6ccf-44e0-80d4-3a04fd53679e)

**Comment by UncleSamSwiss** [comment]
@nijel Do you need any additional information or a way to reproduce/test this?

**Comment by nijel** [comment]
Seems like you did some manual changes to the group — it has selected only some components and is not linked to the project.

Try creating new "Sources" team in the UI, granting it "Edit source" permission.
