### ISSUE TITLE
Exclude Glossary translation from "Translated" and "Strings" values on the Engage page

### ISSUE THREAD

**Issue by buhtz** [WeblateOrg/weblate#10094]
![grafik](https://github.com/WeblateOrg/weblate/assets/11861496/8aa20760-ac42-41d5-8c89-8dab869fb344)

The engage page do show a value indicating the completeness of the current translation. This value is related to the whole project including the Glossary.

IMHO this value is useless. The Glossary is used internally by translators and never released or published with the "project" (a software or a document in most cases). On such a fancy engage page it is IMHO better and more realistic to present the translation completeness of all components but excluding the Glossary.
In [my project](https://translate.codeberg.org/engage/backintime/) it would be 59 instead of 56 %.

The same problem occurs for the "Strings" count. As higher this value is as more it drives potential translators away.

**Comment by tomaszajac-vs** [comment]
Hi, is this issue still available?

**Comment by buhtz** [comment]
What do you mean by "available"? Yes it is open.

**Comment by buhtz** [comment]
Switch of the bot and treat your human contributors as humans please.

What was fixed and how? The referenced commit do not explain it. It would be nice to know.

**Comment by nijel** [comment]
As you can see just above the comment you don't like, it was fixed in https://github.com/WeblateOrg/weblate/commit/ed44a52196048a42e56a945d1586fa370cf01f65. IMHO, the commit message is pretty clear.
