### ISSUE TITLE
504 Gateway Time-out in `/autotranslate` REST API after upgrading Weblate to v5

### ISSUE THREAD

**Issue by matzeeable** [WeblateOrg/weblate#10108]
### Describe the issue

Project / Component / Language:

https://translate.devowl.io/projects/wordpress-real-cookie-banner-wordpressorg-readme/wordpress/de@formal/

Affected REST API:

https://translate.devowl.io/api/translations/wordpress-real-cookie-banner-wordpressorg-readme/wordpress/de@formal/autotranslate/

When I try to autotranslate the component with the following parameters, I get a 504 Gateway Time-out:

![image](https://github.com/WeblateOrg/weblate/assets/1008534/6a1bb7ab-6900-402d-a8aa-8457efedbfa7)

It seems, Weblate has a configured time-out of 5 minutes, but for ~125 strings 5 minutes is too long, and it worked with Weblate v4.16 previously.

When I check the docker logs, I can see the following:

```
gunicorn stderr | [2023-10-05 14:15:49,804: INFO/478] wordpress-real-cookie-banner-wordpressorg-readme/wordpress/de@formal: starting automatic translation None: mt: weblate
gunicorn stderr | INFO:weblate:wordpress-real-cookie-banner-wordpressorg-readme/wordpress/de@formal: starting automatic translation None: mt: weblate
gunicorn stderr | [2023-10-05 14:15:49,804: INFO/478] Acquired Lock('lock:component-update-lock-6713').
gunicorn stderr | INFO:redis_lock.acquire:Acquired Lock('lock:component-update-lock-6713').
celery-celery stderr | [2023-10-05 14:16:00,097: INFO/MainProcess] Task weblate.utils.tasks.heartbeat[b7b9748c-95fb-4d1b-92dc-44b9c0b12940] received
celery-celery stderr | [2023-10-05 14:17:00,172: INFO/MainProcess] Task weblate.utils.tasks.heartbeat[a91e550f-6171-40a0-9fb1-738f0e7407f6] received
celery-celery stderr | [2023-10-05 14:18:00,205: INFO/MainProcess] Task weblate.utils.tasks.heartbeat[8af6fcad-1c38-4c9b-a9f3-0b33bdbbee1e] received
celery-celery stderr | [2023-10-05 14:19:00,234: INFO/MainProcess] Task weblate.utils.tasks.heartbeat[74c3555a-d3f7-49f0-acb8-0ed0a96a1579] received
celery-celery stderr | [2023-10-05 14:20:00,324: INFO/MainProcess] Task weblate.utils.tasks.heartbeat[1e0a37f4-2535-4613-8270-08d92ef04fb4] received
celery-celery stderr | [2023-10-05 14:21:00,357: INFO/MainProcess] Task weblate.utils.tasks.heartbeat[82350d9e-3324-4e64-a148-8291d815c76f] received
celery-celery stderr | [2023-10-05 14:22:00,384: INFO/MainProcess] Task weblate.utils.tasks.heartbeat[3a25da81-6cb0-4ecb-a5fd-90b5583e20bf] received
gunicorn stderr | [2023-10-05 14:22:03,489: INFO/478] wordpress-real-cookie-banner-wordpressorg-readme/wordpress/de@formal: completed automatic translation
gunicorn stderr | INFO:weblate:wordpress-real-cookie-banner-wordpressorg-readme/wordpress/de@formal: completed automatic translation
```

Start-time: 14:15
Autotranslate completed: 14:22
Duration: 7 minutes

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

See above.

### Expected behavior

The REST API for autotranslate mechanism should be faster and not end in a time-out.

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.0.2
 * Django: 4.2.5
 * siphashc: 2.1
 * translate-toolkit: 3.10.1
 * lxml: 4.9.3
 * Pillow: 10.0.0
 * nh3: 0.2.14
 * python-dateutil: 2.8.2
 * social-auth-core: 4.4.2
 * social-auth-app-django: 5.3.0
 * django-crispy-forms: 2.0
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.2
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.12.4
 * rapidfuzz: 3.3.0
 * openpyxl: 3.1.2
 * celery: 5.3.4
 * django-celery-beat: 2.5.0
 * kombu: 5.3.2
 * translation-finder: 2.15
 * weblate-language-data: 2023.5
 * html2text: 2020.1.16
 * pycairo: 1.24.0
 * PyGObject: 3.46.0
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.3.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.31.0
 * Cython: 3.0.2
 * misaka: 2.1.1
 * GitPython: 3.1.36
 * borgbackup: 1.2.6
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.17.1
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.2.0
 * Python: 3.11.5
 * Git: 2.30.2
 * psycopg2: 2.9.7
 * phply: 1.2.6
 * ruamel.yaml: 0.17.32
 * tesserocr: 2.6.1
 * boto3: 1.28.48
 * zeep: 4.2.1
 * aeidon: 1.12
 * iniparse: 0.5
 * mysqlclient: 2.2.0
 * Mercurial: 6.5.2
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * PostgreSQL server: 15.4
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: email-smtp.eu-central-1.amazonaws.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://:WjUonTNhHsgHzp8iM66ofyALIz3u@weblate_redis:6379/1, redis://:WjUonTNhHsgHzp8iM66ofyALIz3u@weblate_redis:6379/1, regular
 * Platform: Linux 5.10.28-scaleway (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

WARNINGS:
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.0.2/admin/install.html#collecting-errors

System check identified 2 issues (1 silenced).
```

**Comment by nijel** [comment]
* Disable debug mode, that will give you some performance.
* There is no 5 minutes timeout in Weblate containers, maybe your reverse proxy does that?
* Running `VACUUM ANALYZE trans_unit` on the database might help in the actual performance. (If you have upgraded PostgreSQL while upgrading to Weblate 5.0, doing ANALYZE on all tables might be needed)

**Comment by matzeeable** [comment]
- Disabled debug mode
- Run `ANALYZE` command
- Run `VACUUM ANALYZE trans_unit` command

Result:

```
gunicorn stderr | [2023-10-05 18:07:50,398: INFO/428] wordpress-real-cookie-banner-wordpressorg-readme/develop/de@formal: starting automatic translation None: mt: weblate
gunicorn stderr | INFO:weblate:wordpress-real-cookie-banner-wordpressorg-readme/develop/de@formal: starting automatic translation None: mt: weblate
gunicorn stderr | [2023-10-05 18:07:50,399: INFO/428] Acquired Lock('lock:component-update-lock-6844').
gunicorn stderr | INFO:redis_lock.acquire:Acquired Lock('lock:component-update-lock-6844').
celery-celery stderr | [2023-10-05 18:07:52,387: INFO/MainProcess] Task weblate.utils.tasks.heartbeat[d7b0ed95-254d-40d8-ae69-b4551fd0cab0] received
gunicorn stderr | [2023-10-05 18:07:54,662: INFO/428] wordpress-real-cookie-banner-wordpressorg-readme/develop/de@formal: completed automatic translation
gunicorn stderr | INFO:weblate:wordpress-real-cookie-banner-wordpressorg-readme/develop/de@formal: completed automatic translation
```

-> 4 seconds. Thanks for your help! 😊
