### ISSUE TITLE
@permission_required decorators ignore GroupACL

### ISSUE THREAD

**Issue by matejcik** [WeblateOrg/weblate#1012]
These are in use for translation upload and for dictionary editing.

We will have to implement a custom version of the decorator, which will catch the `request` object and extract from it the project (and possibly subproject/language) in order to call either `can_edit` or `check_permission` on it.
##

**Comment by nijel** [comment]
In many cases the check is done manually (for example see [auto_translate](https://github.com/nijel/weblate/blob/master/weblate/trans/views/edit.py#L603)), but indeed it might be better to share this logic.

**Comment by nijel** [comment]
Translation upload will longer use the decorator (due to API, which needs the same endpoint as well) - fee1fad5b2d19729e59bca7f56410aee2431bf6a

**Comment by nijel** [comment]
Should be fixed now.
