### ISSUE TITLE
Show disabled save button reason more prominently

### ISSUE THREAD

**Issue by ronaldomasc** [WeblateOrg/weblate#10165]
### Describe the issue

When trying to translate the kunoichi trainer game, the site does not allow me to save the translation.
![Captura de Tela (394)](https://github.com/WeblateOrg/weblate/assets/147671297/dd5e4282-a5de-4b14-91d3-3e133314ffa1)
The error only occurs in the "game" session.

### I already tried

- [ ] I've read and searched [the documentation](https://docs.weblate.org/).
- [ ] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Try translating something into Portuguese in the "game" part

### How do you run Weblate?

weblate.org service

**Comment by ronaldomasc** [comment]
> O problema relatado foi resolvido. Se você não acha que está certo, siga seus rótulos para obter uma pista para outras etapas.
> 
> * Caso você veja um problema semelhante, abra um problema separado.
> * Se você está feliz com o resultado, não hesite em apoiar a Weblate fazendo uma [doação](https://weblate.org/donate/).

**Comment by nijel** [comment]
The button title will give you more info, so place your mouse on top of the disabled button. But we should make this more visible...
