### ISSUE TITLE
Suggest flags to maintainers

### ISSUE THREAD

**Issue by Cwpute** [WeblateOrg/weblate#10185]
### Describe the problem

Sometimes code snippets crawl into the strings to be translated, either because they are an integrate part of the string, to emphasize a word with italics, boldness etc... or because the developers unadvertedly left them in. It's a bit of a flow-breaker as it requires you to type with a totally different syntax than usual.

My specific case here looks like this: `If this doesn’t work, try resending your gift card (<a %(a_instr)s>instructions</a>).`

### Describe the solution you'd like

As a translator, i'd like to be able to signal those little code snippets so that they can't be broken by unattentive translators, and so i can just click on them to copy their content to translated string. I've seen this feature being used for some code snippets but not all of them: in my example, snippets that look like `%(a_instr)s` are always recognized and clickable to copy their content.
Just like the glossary, i'd also like to teach our database to recognize recurring code snippets and highlight them automatically for others to see and interact with.
Also, Weblate would recognize when one of those highlighted snippets is either altered or missing, and warn the translator about it.

### Describe alternatives you've considered

Automatic recognition of those code snippets maybe ?

**Comment by nijel** [comment]
There are a lot checks covering different placeholders, see https://docs.weblate.org/en/latest/user/checks.html. For your particular example https://docs.weblate.org/en/latest/user/checks.html#unsafe-html and https://docs.weblate.org/en/latest/user/checks.html#python-format might work, but there might be other which better match your use-case.

**Comment by Cwpute** [comment]
> There are a lot of checks covering different placeholders, see […]
Thanks for your answer, but if i undergtand those correctly, flags can only be placed by the people setting up the strings to be translated, not the translatwrs themselves.
What i request is a way for translators to place those flags themselves, highlight and string sections as special in some way for all other translators.

**Comment by emmapeel2** [comment]
You can always add a comment to the string suggesting a particular flag.

**Comment by emmapeel2** [comment]
Oh, and did you know that you can also copy the highlighted items with Ctrl+1, Ctrl+2 etc?

**Comment by nijel** [comment]
I think commenting is the correct approach here. There might be a dozen of things you might want to change in the translation configuration and flags are one of them.

**Comment by Cwpute** [comment]
Thanks all for your input.
I guess i was looking for a way to speed up the process between a suggestion and its implementation, but as it was said, commenting might be the best way to adress this issue !
