### ISSUE TITLE
massive lockdown issue happened last night on "hosted weblate"

### ISSUE THREAD

**Issue by yilmazdurmaz** [WeblateOrg/weblate#10191]
### Describe the issue

I don't know how much you noticed this but over last night (between 7-12 hours ago) there happened a massive lockdown on almost all projects that came with the same alert (with different url, of course):

````
fatal: unable to access 'https://github.com/WeblateOrg/hosted.git/': Empty reply from server
````
here is a screenshot from one of the Weblate's own components at https://hosted.weblate.org/projects/weblate/hosted/#alerts

![screenshot-hosted weblate org-2023 10 14-14_23_23](https://github.com/WeblateOrg/weblate/assets/1812105/d49bd266-6b3d-44fc-9fb9-24e5ea000337)

beside the projects I am watching, I checked a few other projects and this occurred in many of them. like a global pandemic.

Now, for the Weblate translations, It is either you noticed, acted fast and unlocked most of them, or maybe there is a settings I am missing.

luckily(!) "hosted" component is still locked now so that you can have an inspection. There are many projects with still-locked components for this same alerted reason.

One thing to note that some component did not experienced this lockdown, for example https://hosted.weblate.org/projects/godot-engine/godot-docs/ . 

as for my request here:
- please tell me if it is an automatic recovery setting or plugin (link?). if so, I can tell admins of other projects I am watching.
- if no auto recovery is present, then please inspect the issue and implement an automatic lockdown recovery when it is just a (possibly) temporary problems
  - that is because that locked-down day might be a translator's only available day they had emptied.

Thanks and Good Luck!

PS: I say "temporary problems" because clearly unlocked projects are working fine now.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

I can't reproduce as it seems to happen between Weblate and GitHub

### Expected behavior

If (and after) this issue occurs, Weblate should check GitHub regularly, like 15-30 minutes, and removes the lockdown automatically.

### Screenshots

I added in the description part

### How do you run Weblate?

weblate.org service

### Weblate versions

whatever "hosted weblate" is

**Comment by nijel** [comment]
Weblate will retry the operation and unlock the component if it succeeds. This is there to prevent accepting contributions for repositories that are no longer existing.

**Comment by yilmazdurmaz** [comment]
> This is there to prevent accepting contributions for repositories that are no longer existing.

Alright, that is an undeniable reason to have the lock.

However, for this specific "Empty reply from server" error, the lockdown reason can be made clearer for us translator by adding, for example, these details:
- why this happened?
  - a message like "can be a temporary host (i.e. GitHub) problem, or the project might be cancelled and deleted"
- when Weblate will retry to auto-resolve this?
  - a message like this: "we will retry in xx minutes to auto-unlock as repo was alive in last 24 hours" or "we ceased trying auto-unlock as we could not reach host over 24 hours (or a week?)"

What is the current retry interval? I am having hard time finding this in documents.

meanwhile, I saw one project unlocked after 13 minutes, another took about 10 and half hours, but the lock on "Weblate/Hosted" was lifted exactly after 24 hours (1 minute offset). I don't know which ones might be resolved by auto-unlock, but the last one suggest there is a 24-hour one.

can you please give a link, or leave breadcrumbs I may follow, about this retry interval?

And I hope, you find time to enhance the lockdown message adding extra info such those I suggested above.

**Comment by nijel** [comment]
There is no period for retry, it will just try it again when the operation is needed. So it mostly depends on how the project is active. But we could indeed give more hints what to do.

**Comment by yilmazdurmaz** [comment]
> There is no period for retry, it will just try it again when the operation is needed. So it mostly depends on how the project is active. But we could indeed give more hints what to do.

I am not sure if this undeterministic retry is good, but seeing you are expanding more on alerts and messages, I will trust the progress. 

Thanks

**Comment by nijel** [comment]
Deterministic retry on a massive failure like this is actually undesired – it would quite likely lead to GitHub rate-limiting Hosted Weblate.
