### ISSUE TITLE
Library labels right-aligned.

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#10196]
### Describe the issue

Somewhat hacktobery,

![image](https://github.com/WeblateOrg/weblate/assets/13802408/6a64a2b0-f66b-4ad2-97a6-494ace3b5800)
![image](https://github.com/WeblateOrg/weblate/assets/13802408/92629159-23a7-4ad0-b30f-88608701d855)
are off to the right.

However, it used to look [like this](https://l10n.elementary.io/about/)
![image](https://github.com/WeblateOrg/weblate/assets/13802408/20e42477-fd2c-4266-9cdb-63078487821d)
The versions just went missing at some point? Maybe when the CSS was changed to accommodate a dark theme?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to https://www.hosted.weblate.org/about
2. Notice the labels are off to the right

### Expected behavior

Names in the middle of labels, accompanied by respective version numbers.

### How do you run Weblate?

weblate.org service

### Additional context

Tested on LibreWolf (FF) and non-desktop view on mobile.

Bonus points for vertical center-alignment :)

**Comment by Geeyun-JY3** [comment]
The version is hidden due to https://github.com/WeblateOrg/weblate/commit/dd716f9a6af53dc3c5c848f67f82229ca43e4d03.
Hiding version information is supported in https://github.com/WeblateOrg/weblate/commit/7509cd0912182d58d49a48bc15776f9a40176274.
