### ISSUE TITLE
Scheduled pull from Github failed, leading to multiple problems and an internal server error

### ISSUE THREAD

**Issue by JacekJagosz** [WeblateOrg/weblate#10208]
### Describe the issue

Why one failed git pull can bring down whole weblate project? Why after a pull has failed it still tries to merge and then push the changes?

We set up a weblate instance on AWS about 4 months ago, using official docker container for Weblate. We had one weblate project for translating from a private Github repository. 
We were using git version control system and we were pulling using ssh, Weblate's public key has been registered in Github.
Weblate has been working flawlessly, until after one of automatic Docker restarts the pull has failed, which then caused multiple other issues, leading to internal server error and inability to access project's settings through the web gui. (logs posted below)

Something similar has happened to us a few months earlier, when we were testing Weblate viability locally, but then we thought it was a one-off. We were able to delete the project, create a new one, and a week later the project would fail in the same way.

Is there any way to recover our weblate project?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Create a new project that uses git integration and pulls from Github using SSH or HTTPS
2. Wait from a few days to multiple weeks for a pull to fail and cause internal server error

### Exception traceback

```pytb
This error has occured 3 times:

Could not update the repository.

Weblate could not fetch upstream changes when updating the repository.

fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 (128)
```
Then this one 3 times:
```
Could not merge the repository.

Weblate could not merge upstream changes while updating the repository.

fatal: bad revision '..origin/translations'
 (128)
```

Then this x3
```
Inexistent files.

This component is set up incorrectly.

Following files are no longer present in the repository:

    locales/translations.pot Template for new translations 
```

```
RepositoryException at /projects/device/device-series/

fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
 (128)

Request Method:	GET
Request URL:	https://translations.biegus.org/projects/device/device-series/
Django Version:	4.2.4
Exception Type:	RepositoryException
Exception Value:	

fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
 (128)

Exception Location:	/usr/local/lib/python3.11/site-packages/weblate/vcs/base.py, line 207, in _popen
Raised during:	weblate.trans.views.basic.show_component
Python Executable:	/usr/local/bin/python
Python Version:	3.11.4
Python Path:	

['/',
 '/usr/local/lib/python3.11/site-packages/git/ext/gitdb',
 '/',
 '/usr/local/bin',
 '/usr/local/lib/python311.zip',
 '/usr/local/lib/python3.11',
 '/usr/local/lib/python3.11/lib-dynload',
 '/usr/local/lib/python3.11/site-packages',
 '/app/data/python']
```

I can post full traceback for this exception, but as it is one down the line not sure if it is helpful:
```
RepositoryException at /projects/device/device-series/

fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
 (128)
```

```
Could not push the repository.

Weblate could not push changes to the upstream repository.

fatal: bad revision 'origin/translations..'
 (128)
```
```


### How do you run Weblate?

Docker container

### Weblate versions

4.18.2

### Weblate deploy checks

_No response_

### Additional context

Plugins used:

- Generate MO files
- Update PO files (msmerge)
- Squash commits on Git

**Comment by nijel** [comment]
It seems like the local repository was removed. Was the Docker volume removed? What does your automatic Docker restart consist of?

**Comment by wiktorciurej** [comment]
> It seems like the local repository was removed. Was the Docker volume removed? What does your automatic Docker restart consist of?

Hey, it's running on ECS with Fargate and the task is occasionally recreated automatically. Volumes aren't persistent with Fargate configuration and I think that's the culprit. I tried to connect EFS volume as /app/data instead of default ephemeral storage but container fails during startup with vague "Exit 1" status code.

**Comment by nijel** [comment]
Weblate requires a persistent storage for the data volume. Check container logs for more details on the error...
