### ISSUE TITLE
Error in parameter q: Could not parse query string: BaseTermExpr.__init__() missing 1 required positional argument: 'tokens

### ISSUE THREAD

**Issue by documate-canada** [WeblateOrg/weblate#10211]
### Describe the issue

When I attempt to search for a string with context I get an error displayed saying:

"Error in parameter q: Could not parse query string: BaseTermExpr.__init__() missing 1 required positional argument: 'tokens' "

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Login into weblate
Navigate to the project
Click on Search
within search select "String with context"
enter search criteria eg. "Preferences.Metadata.lblFirstExpanded"

Notice two errors on top:
1)Invalid search query! 

2)  Error in parameter q: Could not parse query string: BaseTermExpr.__init__() missing 1 required positional argument: 'tokens' 

<img width="1362" alt="Screen Shot 2023-10-16 at 8 04 42 PM" src="https://github.com/WeblateOrg/weblate/assets/136353180/19526a17-0ec1-44da-bee3-bca2e5c84953">

### Expected behavior

Search should return results matching criteria.

### Screenshots

<img width="1362" alt="Screen Shot 2023-10-16 at 8 04 42 PM" src="https://github.com/WeblateOrg/weblate/assets/136353180/5dc1fca7-1dfa-4335-8c27-d003e50afeed">

### How do you run Weblate?

Other

### Weblate versions

[5.0.2](https://github.com/WeblateOrg/weblate/releases/tag/weblate-5.0.2)

### Weblate deploy checks

```shell
bitnami@ip-172-31-10-3:/opt/bitnami/weblate/data/static$ sudo weblate check --deploy
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E009) The Celery tasks queue is too long, either the worker is not running, or is too slow.
	HINT: https://docs.weblate.org/en/weblate-5.0.2/admin/install.html#celery
?: (weblate.E019) The Celery does not process tasks, or is too slow in processing them.
	HINT: https://docs.weblate.org/en/weblate-5.0.2/admin/install.html#celery
?: (weblate.E027) The path /opt/bitnami/weblate/data/backups is owned by a different user, check your DATA_DIR settings.
	HINT: https://docs.weblate.org/en/weblate-5.0.2/admin/install.html#file-permissions
?: (weblate.E027) The path /opt/bitnami/weblate/data/cache is owned by a different user, check your DATA_DIR settings.
	HINT: https://docs.weblate.org/en/weblate-5.0.2/admin/install.html#file-permissions
?: (weblate.E027) The path /opt/bitnami/weblate/data/cache/avatar is owned by a different user, check your DATA_DIR settings.
	HINT: https://docs.weblate.org/en/weblate-5.0.2/admin/install.html#file-permissions
?: (weblate.E027) The path /opt/bitnami/weblate/data/cache/avatar/2894fd080d09146faf781f9122ccd7cf.djcache is owned by a different user, check your DATA_DIR settings.
	HINT: https://docs.weblate.org/en/weblate-5.0.2/admin/install.html#file-permissions
?: (weblate.E027) The path /opt/bitnami/weblate/data/cache/avatar/28d2a70ed1b6b26dcb7937bbd00dd3fa.djcache is owned by a different user, check your DATA_DIR settings.
```

**Comment by nijel** [comment]
It works just fine for me:

![image](https://github.com/WeblateOrg/weblate/assets/212189/dacb123b-3692-47c1-b1f5-ade46907ca52)

What pyparsing version do you have installed?

**Comment by documate-canada** [comment]
I installed this as a package via an AWS Bitnami AMI.  The pyparsing version is 3.1.1.

Here is the list of the versions of other modules:

$ weblate list_versions
 * Weblate: 5.0.2
 * Django: 4.2.5
 * siphashc: 2.1
 * translate-toolkit: 3.10.1
 * lxml: 4.9.3
 * Pillow: 10.0.0
 * nh3: 0.2.14
 * python-dateutil: 2.8.2
 * social-auth-core: 4.4.2
 * social-auth-app-django: 5.3.0
 * django-crispy-forms: 2.0
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.2
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.12.4
 * rapidfuzz: 3.3.0
 * openpyxl: 3.1.2
 * celery: 5.3.4
 * django-celery-beat: 2.5.0
 * kombu: 5.3.2
 * translation-finder: 2.15
 * weblate-language-data: 2023.5
 * html2text: 2020.1.16
 * pycairo: 1.24.0
 * PyGObject: 3.46.0
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.3.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.31.0
 * Cython: 3.0.2
 * misaka: 2.1.1
 * GitPython: 3.1.36
 * borgbackup: 1.2.6
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.17.1
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.2.0
 * Python: 3.11.5
 * Git: 2.30.2
 * psycopg2-binary: 2.9.8
 * phply: 1.2.6
 * ruamel.yaml: 0.17.32
 * tesserocr: 2.6.1
 * boto3: 1.19.0
 * zeep: 4.2.1
 * aeidon: 1.12
 * iniparse: 0.5
 * mysqlclient: 2.2.0
 * PostgreSQL server: 15.3

**Comment by nijel** [comment]
That looks correct. Just to clarify, the full search string causing this is: `has:context Preferences.Metadata.lblFirstExpanded`
