### ISSUE TITLE
Cannot assign a team/group administrator using the REST API

### ISSUE THREAD

**Issue by joubu** [WeblateOrg/weblate#10222]
### Describe the problem

It's not possible to grant administration to a group/team using the REST API

### Describe the solution you'd like

It does not seem easy to implement, but just logging the problem in an issue to report the problem.

**Comment by rawatsushil** [comment]
@joubu  Can you describe the problem please

**Comment by joubu** [comment]
Using the UI you can "Grant administration" or "Revoke administration" on the following view: http://localhost:8888/teams/GROUP_ID/#users
![image](https://github.com/WeblateOrg/weblate/assets/671757/1192a401-749c-4a04-beb3-03a4953d6af2)

I have not found a way to do that using the REST API.

**Comment by nijel** [comment]
Indeed it is not exposed in the API. Adding that should be pretty easy to the existing API endpoints: https://docs.weblate.org/en/latest/api.html#groups

**Comment by nidhi-kala** [comment]
@nijel hey! I would like to work on this.
I'll add a new endpoint to the GroupViewSet in the api. Is there a preference for name of the endpoint?

**Comment by nijel** [comment]
Sorry for missing your question. See how components endpoint works at GroupViewSet, this should be similar.
