### ISSUE TITLE
Error saving plurals in xliff

### ISSUE THREAD

**Issue by mickeprag** [WeblateOrg/weblate#1022]
### Steps to reproduce
1. Add a string with plurals in xliff
2. Try translating it
### Expected behaviour

The strings should be saved
### Actual behaviour

Get this error message: Argument must be bytes or unicode, got 'list'

Backtrace:

```
File "/var/www/weblate/env4/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/var/www/weblate/env4/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/www/weblate/env4/lib/python2.7/site-packages/weblate/trans/views/edit.py" in translate
  525.                 this_unit_url, next_unit_url

File "/var/www/weblate/env4/lib/python2.7/site-packages/weblate/trans/views/edit.py" in handle_translate
  311.         go_next = perform_translation(unit, form, request)

File "/var/www/weblate/env4/lib/python2.7/site-packages/weblate/trans/views/edit.py" in perform_translation
  238.         form.cleaned_data['fuzzy']

File "/var/www/weblate/env4/lib/python2.7/site-packages/weblate/trans/models/unit.py" in translate
  1027.         saved = self.save_backend(request)

File "/var/www/weblate/env4/lib/python2.7/site-packages/weblate/trans/models/unit.py" in save_backend
  569.             (saved, pounit) = self.translation.update_unit(self, request, user)

File "/var/www/weblate/env4/lib/python2.7/site-packages/weblate/trans/models/translation.py" in update_unit
  804.                 pounit.set_target(unit.get_target_plurals())

File "/var/www/weblate/env4/lib/python2.7/site-packages/weblate/trans/formats.py" in set_target
  335.         self.unit.settarget(target)

File "/var/www/weblate/env4/lib/python2.7/site-packages/translate/storage/xliff.py" in settarget
  391.         super(xliffunit, self).settarget(text, lang, append)

File "/var/www/weblate/env4/lib/python2.7/site-packages/translate/storage/lisa.py" in settarget
  165.                 languageNode.text = text
```
### Server configuration
- Weblate 2.5
- Python 2.7.3
- Django 1.9.4
- six 1.10.0
- python-social-auth 0.2.14
- Translate Toolkit 1.14.0-rc1
- Whoosh 2.7.2
- Git 1.7.9.5
- Pillow (PIL) 1.1.7
- dateutil 2.5.0
- lxml 3.5.0
- django-crispy-forms 1.6.0
- compressor 1.6
- Database backends: django.db.backends.mysql
##

**Comment by mickeprag** [comment]
Adding suggestion works but when accepting the suggestion the same error appears.

**Comment by nijel** [comment]
Can you please provide sample for XLIFF file with plurals? I'm afraid this is not supported by translate-toolkit, library we use for manipulating with the files.

**Comment by mickeprag** [comment]
I was using translate-toolkit to figure out the format to use in the xliff files for handling plurals. So it should be supported. And Weblate also shows it correctly in the interface.


    <?xml version='1.0' encoding='UTF-8'?>
    <xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 http://docs.oasis-open.org/xliff/v1.2/os/xliff-core-1.2-strict.xsd">
    	<file source-language="en" datatype="plaintext" target-language="en">
    		<body>
    			<trans-unit xml:space="preserve" id="1" approved="yes" restype="x-gettext-domain-header">
    				<source>Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;</source>
    				<target state="translated">PO-Revision-Date: 2016-03-14 12:36+0000
    Last-Translator: Micke Prag &lt;micke.prag@telldus.se&gt;
    Language: en
    Content-Type: text/plain; charset=UTF-8
    Plural-Forms: nplurals=2; plural=n != 1;
    X-Generator: Weblate 2.5
    Content-Transfer-Encoding: 8bit
    </target>
    			</trans-unit>
    			<group restype="x-gettext-plurals" id="2" approved="yes">
    				<trans-unit id="2[0]" datatype="plaintext">
    					<source>%(n)d question</source>
    				<target>%(n)d question</target></trans-unit>
    				<trans-unit id="2[1]" datatype="plaintext" approved="yes">
    					<source>%(n)d questions</source>
    				<target state="translated">%(n)d questions</target></trans-unit>
    			</group>
    		</body>
    	</file>
    </xliff>

**Comment by nijel** [comment]
Okay, this is not orignal XLIFF, but variant for storing Gettext PO files. I certainly could add it as another format to Weblate.

PS: I wonder why it's better to use Gettext stored in XLIFF instead it's native format...)

**Comment by mickeprag** [comment]
Maybe xliff does not have a native format (in 1.2)? Googeling seems to show that `<group restype="x-gettext-plurals">` is at least a de-facto standard...

**Comment by nijel** [comment]
Switching to poxliff as default is certainly an option as well...

**Comment by nijel** [comment]
The poxliff is already there, I think it makes sense to provide both options, therefore I'm closing this issue.
