### ISSUE TITLE
Align the `Tools` button with the other action buttons

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#10225]
### Describe the problem

After https://github.com/WeblateOrg/weblate/commit/18f9c919ad72c309ccae44e587dd1118e27e4ad0 implemented, the bottom right `Tools` button in the full editor is not aligned.

### Describe the solution you'd like

Align the `Tools` button with the other action buttons.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/49396421/f84d25e6-a21a-4a07-89e4-4e764b03c620)

**Comment by furqanindikar** [comment]
Assign me Please

**Comment by nijel** [comment]
@furqanindikar  You're welcome to work on this issue.
