### ISSUE TITLE
Cannot assign list of languages or projects when creating a group using the REST API

### ISSUE THREAD

**Issue by joubu** [WeblateOrg/weblate#10221]
### Describe the problem

`POST /api/groups` and `PUT /api/groups/{group_id}` does not accept languages and projects.

### Describe the solution you'd like

If you set `project_selection` and/or `language_selection` to 0 ("as defined") you would expect the endpoint to accept the list of projects and languages.

### Additional context

We are moving from pootle and we had granular permissions (allowing only some users to submit translations). Doing it manually will take a lot of time unfortunately.
Is there another alternative?

**Comment by joubu** [comment]
Well the alternative is, I guess, to build the list of SQL queries to create the different groups.

**Comment by rawatsushil** [comment]
I think it does accept languages and projects. Would it be possible for you to show the request you are sending and I can then test on the same.
@joubu

**Comment by joubu** [comment]
This is what I have tried:
`curl \--data-binary '{ "name": "New team", "project_selection": 0, "language_selection": 0, "projects": ["$PROJECT_SLUG"], "languages": "$LANG_CODE" }' -H 'Content-Type: application/json' -H "Authorization: Token wlu_Xanzle9JKBK2R93gLbMGB2ublWESKj0pfZWo" http://localhost:8888/api/groups/`

Response:
`{"id":107,"name":"New team","defining_project":null,"project_selection":0,"language_selection":0,"url":"http://127.0.0.1:8888/api/groups/107/","roles":[],"languages":[],"projects":[],"componentlists":[],"components":[]}%`

And the doc is not listing them in the parameter list: https://docs.weblate.org/en/weblate-5.1/api.html#post--api-groups-

**Comment by nijel** [comment]
There is a separate endpoint for manipulating with languages: https://docs.weblate.org/en/weblate-5.1/api.html#post--api-groups-(int-id)-languages-
