### ISSUE TITLE
When clicking `{}`  pastes `[object Object]` to translation field

### ISSUE THREAD

**Issue by Daviteusz** [WeblateOrg/weblate#10236]
### Describe the issue

The Json file in the source has braces `{}`, which are used for numbers. The file flags are `python-brace-format`
When braces are pressed, a `[object Object]` is pasted into the translation field (see screenshots section).

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Set `{}` in some strings in source json file
2. Set python-brace-format flag
3. Click on braces to copy them into translation field

### Expected behavior

Should paste `{}` instead of `[object Object]`

### Screenshots

https://github.com/WeblateOrg/weblate/assets/11527277/fd43d646-2f94-425a-bd05-a0d46055d356

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.1
 * Django: 4.2.6
 * siphashc: 2.3
 * translate-toolkit: 3.10.1
 * lxml: 4.9.3
 * Pillow: 10.1.0
 * nh3: 0.2.14
 * python-dateutil: 2.8.2
 * social-auth-core: 4.4.2
 * social-auth-app-django: 5.3.0
 * django-crispy-forms: 2.1
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.3
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.12.4
 * rapidfuzz: 3.4.0
 * openpyxl: 3.1.2
 * celery: 5.3.4
 * django-celery-beat: 2.5.0
 * kombu: 5.3.2
 * translation-finder: 2.15
 * weblate-language-data: 2023.5
 * html2text: 2020.1.16
 * pycairo: 1.25.0
 * PyGObject: 3.46.0
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.4.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.31.0
 * Cython: 3.0.3
 * misaka: 2.1.1
 * GitPython: 3.1.37
 * borgbackup: 1.2.6
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.20.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.0
 * Python: 3.11.5
 * Git: 2.39.2
 * psycopg2: 2.9.9
 * phply: 1.2.6
 * ruamel.yaml: 0.17.35
 * tesserocr: 2.6.2
 * boto3: 1.28.63
 * zeep: 4.2.1
 * aeidon: 1.13
 * iniparse: 0.5
 * mysqlclient: 2.2.0
 * Mercurial: 6.5.2
 * git-svn: 2.39.2
 * git-review: 2.3.1
 * PostgreSQL server: 15.4
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: s1.ct8.pl
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 6.5.7-arch1-1 (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.1/admin/backup.html

System check identified 2 issues (1 silenced).
```

**Comment by Rishabh-1126** [comment]
I would like to work on this issue, could you please assign this to me?
