### ISSUE TITLE
Cannot change component URL slug or allow duplicating from local VCS

### ISSUE THREAD

**Issue by tipa** [WeblateOrg/weblate#10289]
### Describe the issue

I must have specified the wrong URL slug when creating a new component. Therefore I want to rename it so I have the same URL slug as my other components of other projects. This makes my script for downloading translations via API easier. Unfortunately there doesn't seem to be a way to rename URL slugs for components or (as a workaround) create a new, duplicate component that copies over the stuff from an existing component.
There is this existing & closed issue which is related: https://github.com/WeblateOrg/weblate/issues/2411

### Steps to reproduce the behavior

1. Create new project + component by uploading translation files
2. Try to rename component URL slug
3. Try to create component using "from existing component"

### Expected behavior

Either
- a way for changing the URL slug or
- a way to create component using "From existing component" (which uses "local VCS")

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/2863198/a9102f34-4a4e-43d6-aed7-dd2a4c51763c)

**Comment by nijel** [comment]
Use Manage / Organize component
