### ISSUE TITLE
Automatic checker to tolerate interrobang swapping (!?/?!)

### ISSUE THREAD

**Issue by yheuhtozr** [WeblateOrg/weblate#10296]
### Describe the problem

Languages have differing preference in the order of symbols representing astonishment. Namely, English tends to use _?!_ ("What?!") while Japanese _!?_ ("Nani!?"). The system checks unmatched punctuation between source and target, but every time the composite punctuation appears in such language pairs, it reports false positive warning.

### Describe the solution you'd like

Do not warn, or make an option that does not warn when `?!` and `!?` are swapped. Also for fullwidth `？！` and `！？`, and possibly for pre-combined `⁈` (U+2048) and `⁉` (U+2049) as well.

**Comment by nijel** [comment]
It should not be difficult to add another check to cover solely `?!` and let EndExclamationCheck and EndQuestionCheck ignore this combination.

**Comment by manuelmcruz** [comment]
Hello I am new to the project could i give a try in solving this issue?

**Comment by nijel** [comment]
Yes, you're welcome!
