### ISSUE TITLE
Zen mode throughout

### ISSUE THREAD

**Issue by yfdyh000** [WeblateOrg/weblate#1029]
### Steps to reproduce
1. I want to always use the Zen mode for translating, it looks more suitable for me compared to the default view.
### Expected behaviour
1. Provide an option in profile, and then automatically open / redirected to Zen view for any translating.
### Actual behaviour
1. Every time I need to open the translation interface for any projects, and then switch it.
### Server configuration

Please paste here output of ./manage.py list_versions
##

**Comment by nijel** [comment]
This was planned from the beginning, but for some reason it's not yet there...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
