### ISSUE TITLE
two-line contrast mode for source changes

### ISSUE THREAD

**Issue by yfdyh000** [WeblateOrg/weblate#1031]
### Steps to reproduce
1. Open the translation interface for strings have action is needed.
### Expected behaviour
1. Easily find out which words or paragraphs need to be updated.
### Actual behaviour
1. Changes are mixed in a line, just color-coded.
### Server configuration

Please paste here output of ./manage.py list_versions
##

**Comment by nijel** [comment]
Can you please add some screenshot? I'm not sure I get your issue...

**Comment by yfdyh000** [comment]
![an example](https://cloud.githubusercontent.com/assets/1769875/13900172/baadfa00-ee3a-11e5-9204-da22b769a139.png)
I want it to be a diff view with two lines, it will be easier to compare or copy.

**Comment by ldmpub** [comment]
#1570 updated.

**Comment by ldmpub** [comment]
This should be fix sooner by #2466.

**Comment by ldmpub** [comment]
Michal redirected me here from #1570 which is now closed without any answer ;-( .
Hoping 2 users requests will be more heard than my voice only.

@yfdyh000 could you please read #1570 and tell me what do you think: do we have the same point of view? I find the "merged / all mixed in one line strings changes" particularly inappropriate in History views.
