### ISSUE TITLE
Allow to edit the specialchar group by user

### ISSUE THREAD

**Issue by yfdyh000** [WeblateOrg/weblate#1036]
### Steps to reproduce
1. I see the special character group in translate interface.
### Expected behaviour

I can adjust and editing it, like editing WYSIWYG or preference in user profile.
### Actual behaviour

It can not seem to change.
##

**Comment by nijel** [comment]
I think this issue was already reported, but I can't find it right now, so it's probably not yet here :-). Anyway this indeed makes sense (and actually was planned since the special chars feature was introduced).
