### ISSUE TITLE
Some Chinese translation haven't been apply to weblate official UI

### ISSUE THREAD

**Issue by LaoshuBaby** [WeblateOrg/weblate#10379]
### Describe the issue

For example, on user profiles account tab: https://hosted.weblate.org/accounts/profile/#account

![图片](https://github.com/WeblateOrg/weblate/assets/42690037/2d698226-1170-46a7-8cbc-8c37c7907467)

All those strings highlighted are translated, but none had been applied on UI, why?

* [`Full name`](https://hosted.weblate.org/translate/weblate/application/zh_Hans/?checksum=1ec24b01c7470333)
* [`Name is also used in version control commits.`](https://hosted.weblate.org/translate/weblate/application/zh_Hans/?checksum=40f22474bf0badfb)

These have indeed not been synchronized for a long time. (Strings that were recently enabled for translation do not appear in the screenshots)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

just visit links above

**Comment by nijel** [comment]
Most of these strings are available for translation since yesterday,  so even if they were translated meanwhile,  these changes are not yet deployed.

**Comment by LaoshuBaby** [comment]
> Most of these strings are available for translation since yesterday

No, most of them were translated 5 months ago。Is it because Weblate hasn't been rebuilt in months?

**Comment by nijel** [comment]
> No, most of them were translated 5 months ago。

Sorry, but 2 out of 7 is definitely not “most of them”.

But indeed there is a bug in handling these two strings, I will fix that.
