### ISSUE TITLE
Android strings plural form is lost for Catalan language

### ISSUE THREAD

**Issue by Ereza** [WeblateOrg/weblate#10398]
### Describe the issue

I am a translator for several projects on Hosted Weblate. I contribute to Tachiyomi's Catalan translation, and during the last months, some strings with plurals have been losing the «other» plural form when a sync occurs with the source repository. Catalan language has one/many/other plural forms.

In the Weblate interface, those strings show the «one» and «many» plural forms translated, and the «other» plural form untranslated, which triggers a «Failing check: Missing plurals». If the translators then translate the missing «other» form, it gets propagated back to the repository, but the «many» form is lost. If you download the strings.xml file from Weblate, it doesn't contain the «many» form either: only the «one» and «other» forms. Somehow the «many» form appears to end up used as «other», and the «other» form is lost.

We tried adding the «many» form manually to the repository code (tachiyomiorg/tachiyomi#10133) hoping that it would fix the issue when the strings were synced to Weblate, but it has not helped in any way.

Catalan plural forms have changed in the past years (initially they were one/other and currently they are one/many/other), but I'm not sure if this is the cause of the issue. Maybe it is related to #9364?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Use Weblate to translate an Android project with a pluralized string into Catalan (it has one/many/other forms).
2. When Weblate commits the file to version control, it is missing the «many» plural form. See example: https://github.com/tachiyomiorg/tachiyomi/pull/10135/commits/55ab1ff7a8f31ede96c0ac98087b51856b247535
3. When the file is changed in the repository or new strings land into Weblate, the «other» plural form becomes missing in Weblate and triggers «Failing check: Missing plurals».

### Expected behavior

The plural form should not be lost.

### How do you run Weblate?

weblate.org service

### Weblate versions

Using Hosted Weblate.

### Weblate deploy checks

```shell
Using Hosted Weblate.
```

**Comment by nijel** [comment]
https://github.com/translate/translate/pull/5115 should address this, thanks for reporting this (Weblate automatically follows CLDR, while translate-toolkit needs to get manual updates).
