### ISSUE TITLE
Offer checkboxes in "Flags" dialog

### ISSUE THREAD

**Issue by buhtz** [WeblateOrg/weblate#10391]
### Describe the problem

The "Flags" dialog offers a free text field only.
The problem is that the user need to know or look into the docu to understand which values are valid in that field.
![image](https://github.com/WeblateOrg/weblate/assets/11861496/cccf3a56-03e5-4862-8666-1d2ffba6a8aa)

### Describe the solution you'd like

The dialog should offer all possible values as a checkbox or dropdown menu.

Additionally the dialog should know the failing checks of the current string and offer the related `ignore-` tags first.

**Comment by nijel** [comment]
The flags can have textual values, so it can't be just checkboxes. And there are far too many of them to show them all at once. Also, there is an existing issue for this open for years: https://github.com/WeblateOrg/weblate/issues/1567
