### ISSUE TITLE
Gettext output customization plugin no wrap option doesn't work consistently

### ISSUE THREAD

**Issue by hhyyrylainen** [WeblateOrg/weblate#10392]
### Describe the issue

I've struggled for years now with Weblate having inconsistent line wrapping in .po files compared to other tools. The thing that I hoped to fix the issue (and has worked sometimes) was to enable the plugin gettext-customization and set it to do no wrapping. Still it refuses to work and sometimes Weblate generates PR that linewrap all translations in a file making the diff really hard to see what's actually changed (and requires me to manually make a commit to fix the mess each time). For example this recent PR: https://github.com/Revolutionary-Games/Thrive/pull/4538/files created by Weblate 5.1.1

The only thing I've found that can fix this is to enable the re-run gettext tool to update translation files. That works but creates multiple extra commits for each PR and even that just works after the problem has happened so it bloats git history with extra data.

It'd be super awesome if this years old bug could finally be fixed in Weblate.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Use gettext translation format
2. Don't use line wrapping as Weblate doesn't wrap consistently with other tools (https://github.com/WeblateOrg/weblate/issues/6350 and https://github.com/WeblateOrg/weblate/issues/3852)
3. Wait for Weblate to generate a PR and sometimes see how it messes up one or more files to re-format all the translations with some line wrapping setting that is *not* selected on Weblate.

### Expected behavior

I expect the Weblate option to not line wrap gettext translations to do what it says, namely to stop the line wrapping.

### Screenshots

Here's the settings I have set with the plugin:

![image](https://github.com/WeblateOrg/weblate/assets/3796411/0d6f8d43-fe17-4ebb-9c4a-727370238fd1)

### How do you run Weblate?

PyPI module

### Weblate versions

 * Weblate: 5.1.1
 * Django: 4.2.3
 * siphashc: 2.1
 * translate-toolkit: 3.10.0
 * lxml: 4.9.3
 * Pillow: 10.1.0
 * nh3: 0.2.14
 * python-dateutil: 2.8.2
 * social-auth-core: 4.4.2
 * social-auth-app-django: 5.2.0
 * django-crispy-forms: 2.0
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.2
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.12.2
 * rapidfuzz: 3.1.2
 * openpyxl: 3.1.2
 * celery: 5.3.1
 * django-celery-beat: 2.5.0
 * kombu: 5.3.1
 * translation-finder: 2.15
 * weblate-language-data: 2023.5
 * html2text: 2020.1.16
 * pycairo: 1.24.0
 * PyGObject: 3.44.1
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.3.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.29.0
 * Cython: 0.29.36
 * misaka: 2.1.1
 * GitPython: 3.1.32
 * borgbackup: 1.2.6
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.17.1
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.2.0
 * Python: 3.11.6
 * Git: 2.41.0
 * phply: 1.2.6
 * ruamel.yaml: 0.17.32
 * tesserocr: 2.6.1
 * boto3: 1.28.72
 * zeep: 4.2.1
 * aeidon: 1.12
 * iniparse: 0.5
 * Mercurial: 6.5
 * git-review: 2.3.1
 * PostgreSQL server: 15.4
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.revolutionarygamesstudio.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 6.5.8-200.fc38.x86_64 (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

WARNINGS:
?: (weblate.W033.Subversion) Failure in loading VCS module for Subversion: git: 'svn' is not a git command. See 'git --help'.

The most similar commands are
	fsck
	mv
	show
 (1)
	HINT: https://docs.weblate.org/en/weblate-5.1.1/vcs.html

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-5.1.1/admin/install.html#collecting-errors

System check identified 2 issues (1 silenced).
```

### Additional context

I'm opening another issue as basically the same as: https://github.com/WeblateOrg/weblate/issues/6688 but now having things installed for 2 years, I'm confident this problem has to be happening after that was enabled.

**Comment by emmapeel2** [comment]
To avoid this problem I only submit updates to the .pot file to weblate, and let weblate do the .po files.

**Comment by nijel** [comment]
There must be something in your environment why it doesn't work there. I've just tried it and it works correctly. It also works in the test suite. Changes coming from Hosted Weblate (for example https://github.com/liberapay/liberapay.com/commit/fea56326805f07de6c1bffb3c70466be4b4b2124#diff-80c53ea40e2c73268cd6cf9fe41bb0dcabb0bfc64da33f2a3a693a140bf7f6c9R4544) are also correctly not wrapped.

Can you try uninstalling the add-on and installing it again? Maybe it is not properly hooked to listen to events. This could also be seen from the logs (at debug level), the add-on processing should be visible there:

```
weblate/weblate/cs: running store_post_load add-on: weblate.gettext.customize
```

**Comment by hhyyrylainen** [comment]
I'm pretty sure I've tried uninstalling / reinstalling it before, but I just tried it again. I guess it would be possible that something like updating Weblate breaks the plugin hooks? Which could explain what's going on. At least so far the latest PR opened by Weblate has not had the issue: https://github.com/Revolutionary-Games/Thrive/pull/4557/files

**Comment by nijel** [comment]
Weblate upgrade should not cause this. As you see it for years now (https://github.com/WeblateOrg/weblate/issues/6688), it was most likely caused by some bug when installing the add-on.

**Comment by hhyyrylainen** [comment]
This just now broke again: https://github.com/Revolutionary-Games/Thrive/pull/4636
I suspect the cause is when there is an open PR from weblate and new text is added, that seems to then corrupt all the modified languages in the open PR.
Should I open a new issue or can this be opened?

**Comment by nijel** [comment]
Thanks for additional explanation, there is indeed a bug in adding new strings in monolingual formats. https://github.com/translate/translate/pull/5133 should address that.

As for the cleanup, you need an add-on for that, it doesn't happen automatically: https://docs.weblate.org/en/latest/admin/addons.html#cleanup-translation-files

**Comment by hhyyrylainen** [comment]
Thank you. I'll look into that cleanup plugin.
