### ISSUE TITLE
Glossary: Ability to delete the term in all languages

### ISSUE THREAD

**Issue by emmapeel2** [WeblateOrg/weblate#10403]
### Describe the issue

I have been tidying up the glossary for our project. Some terms where mistakenly added by me, and using the different options without having much idea.

I started trying to remove duplicates, and adding variants to strings. I also added an explanation only to one variant, so as not to clutter the glossary sidebar.

I had to remove many duplicated terms, and the ones that were marked as terminology were super hard to delete, as there were even empty terms on all the languages.

I had to:
- Unmark the term as terminology
- Check the other languages, and if there were translations, check that the other version of the same term was not empty. if empty, add the current translation to the other.
- select all the empty translations in all languages and delete them. i got kicked out of weblate while doing this, which was adding insult to injury :D:D:D

Usually the english term removes itself afterwards

I think it would be much better if on the menu 'Tools'  of the source language string (https://hosted.weblate.org/translate/tor/glossary/en/?checksum=dbc05217b7af603c)  we could have a 'delete term in all languages' . It would make the maintenance of the glossary much easier.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to a glossary component
2. create a term marked as 'terminology'
3. get rid of it

You will take at least 3 minutes to do that

### Expected behavior

A quick way to remove a term from all languages in the glossaries

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Doesn't it happen when you delete the term in the source language?

**Comment by emmapeel2** [comment]
> Doesn't it happen when you delete the term in the source language?

no

**Comment by nijel** [comment]
It does delete it for me...

**Comment by yvanzo** [comment]
I‘m experiencing the same issue here.
After having deleted a glossary term in the source language, it may reappear after some time with no given reason.
Such fictive/temporary deletion don’t appear in the git export in the meantime either, can be a good hint.

**Comment by nijel** [comment]
Hmm, this might be the root cause for https://github.com/WeblateOrg/weblate/issues/9701
