### ISSUE TITLE
some characters were corrupted, fixed but I am still not able to push changes

### ISSUE THREAD

**Issue by jzahradn** [WeblateOrg/weblate#10414]
### Describe the issue

Hi,
I dont't know why but on certain linked component Hungarian translations were somehow corrupted by changing umlaut characters to Korean ones. On its master component everything is OK.
On Insights > History I can see these changes on hungarian language: á > 찼, ó > 처, ú > 첬, ű > 킥, ő > 흷, É > 횋, é > 챕, Ü > 횥, ü > 체, í > 챠, ö > 철, Á > 횁, Ú > 횣. For example: Párosítáts objektum azonosítót szerint > P찼rost챠t찼s objektum azonost챠t처 szerint.
Such changes were done under user "None" with description "String updated in the repository". It is not about manual string insertion or changes by anyone in the GUI.
I searched for every such character on hungarian language and manually updated the corrupted translations.
However, I am not able to commit the changes because of error: 'cp949' codec can't encode character '\xe1' in position 69: illegal multibyte sequence. The string that could not be encoded/decoded was: mportálása".
I searched Hungarian language again for: mportálása or mport (the original word should be importálása - there is not reason to escape "i" character) and I also searched for all the korean characters but I did not find any corrupted string because I already fixed them.
Then I tried to reset changes on the component to match the upstream repository and the corrupted korean characters are back. By the way the hu.csv on the remote Gitlab repository contains correct strings.
I really don't know how to fix the problem because I cannot find any referred multibyte (korean) character in strings mportálása or importálása or mport or sa". Do you know how can I identify, find and fix the certain corrupted string to make commit/push/pull work again?
Because I don't know:
- why these hungarian characters were transformed to koreans
- why I am still getting commit or push errors when I already fixed all the strings from language history
- why I cannot find strings referred in the push errors
I am reporting this as possible bug.
Thank you
Best Regards
Jan

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. commit or push changes in component
2. error received: 'cp949' codec can't encode character '\xe1' in position 69: illegal multibyte sequence. The string that could not be encoded/decoded was: mportálása".
3. search variants of the string mportálása": mportálása, mport, import, sa"
4. no multibyte sequence characters is found

### Expected behavior

1. commit or push translation changes in certain component
2. error received: 'cp949' codec can't encode character '\xe1' in position 69: illegal multibyte sequence. The string that could not be encoded/decoded was: mportálása".
3. search variants of the string mportálása": mportálása, mport, import, sa"
4. found strings with multibyte / Korean character. 
5. fix the strings
6. commit or push successful again

### Screenshots

<img width="1112" alt="Screenshot 2023-11-15 at 14 46 41" src="https://github.com/WeblateOrg/weblate/assets/55885376/781a0d33-d68e-4bef-9227-5457b9720ac1">

### How do you run Weblate?

Docker container

### Weblate versions

4.18.2

**Comment by nijel** [comment]
Please choose `CSV file (UTF-8)` as a file format if your file is UTF-8, see https://docs.weblate.org/en/latest/formats/csv.html

**Comment by jzahradn** [comment]
In the  component settings > Files, we have selected "Simple CSV file". If I switch it to "CSV file (UTF-8) and click Save, I get the same error: 'cp949' codec can't encode character '\xe1' in position 69: illegal multibyte sequence. The string that could not be encoded/decoded was: mportálása"

**Comment by jzahradn** [comment]
I have tried it on both linked component (where the problem with Korean characters occurred) and on its master component (where the problem with Korean characters did not occurred). I am not able to change the CSV type on both of them. Now both components have diverged branches but update is not possible.

**Comment by nijel** [comment]
If there are pending changes, the only way to recover would be to discard them (reset in repo maintenance). Weblate will attempt to write pending changes on component configuration change, and that is what is failing.

**Comment by jzahradn** [comment]
Thank you for the advise, the problem is resolved.
