### ISSUE TITLE
Language aliases do not work in components with category

### ISSUE THREAD

**Issue by emmapeel2** [WeblateOrg/weblate#10417]
### Describe the issue

When on a component with category, like https://hosted.weblate.org/translate/tor/tor-browser/tb-abouttbupdatedtd the language aliases will not forward to the correct language. But if I am on a component without category it will not work.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to https://hosted.weblate.org/translate/tor/support-portal/zh_TW/?q=state:%3Ctranslated 
2. You will be forwarded to https://hosted.weblate.org/translate/tor/support-portal/zh_Hant/?q=state:%3Ctranslated 
3. Now go to  to https://hosted.weblate.org/translate/tor/tor-browser/tor-browser-user-manual/zh_TW/?q=state:%3Ctranslated
4. It says not found

### Expected behavior

It should take you to https://hosted.weblate.org/translate/tor/tor-browser/tor-browser-user-manual/zh_Hant/?q=state:%3Ctranslated like the other component.

Same happens in zen view.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
It is recommended to actual language links instead of relying on such redirects. The redirect is handled in an error path, where the best effort decisions can be made and there is no aim to handle 100% of error cases there. But yes, this specific case could be handled better.

**Comment by emmapeel2** [comment]
> It is recommended to actual language links instead of relying on such redirects. The redirect is handled in an error path, where the best effort decisions can be made and there is no aim to handle 100% of error cases there. But yes, this specific case could be handled better.

In our project we are constrained by different requirements: for example in this case, Tor Browser and related software follows the language conventions of Firefox adding the country (zh-TW), while translators prefer to call the language Traditional Chinese. So we really need the language aliases to match it all together in weblate.
