### ISSUE TITLE
Stay in the translate view when there are no search results

### ISSUE THREAD

**Issue by pavelhoral** [WeblateOrg/weblate#10430]
### Describe the problem

It is very common usecase to search for various strings in the translation. I want to search for a string, check the results and then search for a different string. However the current implementation takes user to component overview page when there are no strings found which does not have search bar - i.e. user loses his/her context, has to go back and potentially fill search parameters again (advanced filter and sort options).

### Describe the solution you'd like

I would love for Weblate to stay on the translate page with the message "No strings found!". This will probably mean that the view has to be able to display without any translation unit available (i.e. don't show anything other than empty pagination, search bar with the filter and sort options).

### Describe alternatives you've considered

Alternative solution (maybe easier and cleaner to implement) would be to end up on the search page with the "No strings found!" message. The end goal is to **preserve and display** used search parameters.

### Screenshots

About to search for "foobar":

![image](https://github.com/WeblateOrg/weblate/assets/2012726/dddeaa3f-6e59-42aa-b595-ca1b4e2a9253)

No strings and my search parameters are lost (query and sorting):

![image](https://github.com/WeblateOrg/weblate/assets/2012726/26ef9e80-cc1e-4ef9-9744-b58cfc15f423)

If I now want to go search for "barbaz" instead, I have to go back. Much better solution would be to either stay on the translate page or on the search page with prefilled query/sorting that was used:

![image](https://github.com/WeblateOrg/weblate/assets/2012726/95267a16-cd9c-44ea-a255-0e5836e469bb)

**Comment by pavelhoral** [comment]
I have discovered (literally seconds after I submit this feature request) there is a dedicated "No matching strings found." page when the search starts from the Search page:

![image](https://github.com/WeblateOrg/weblate/assets/2012726/fa4d71c3-188f-4619-a55f-feea917e9c1b)

This would be probably the best page to end up when doing the search from translate view as well.

**Comment by pavelhoral** [comment]
I have just discovered (should have checked first) that the search page behaves differently in the sense that it has dedicated results page which can show "empty results". So I am not sure how much valid is my feature request in that sense.

**Comment by nijel** [comment]
The search tab uses editor if available in the scope and falls back to browsing if not. It is inconsistent, but uses the typically used view in a given scope.
