### ISSUE TITLE
Add possibility to digest notification mails

### ISSUE THREAD

**Issue by V-Z** [WeblateOrg/weblate#1046]
### Steps to reproduce
1. Go to account settings, notifications.
2. Check whatever You like.
3. Wait to receive plenty of mails. :-)
### Expected behaviour

I'd appreciate some checkbox to allow digest mode of notification e-mails - not one mail for every change, but one (daily?) digest. Doesn't matter if one overall digest or separate digest for each settings or some combination.
### Actual behaviour

The only possibility is to have separate mail for each event.
### Server configuration

The described situation is according to https://l10n.opensuse.org/
##

**Comment by stanislav-brabec** [comment]
I support this request. I got >4000 Weblate error notification e-mails over weekend during mySQL database provider outage. Only ~10 were unique.

**Comment by nijel** [comment]
@stanislav-brabec I don't think there is reasonable way to make digest mails when the database is not there :-). I believe @V-Z is talking about notifications from Weblate itself, while you are seeing error mails from Django. You can certainly limit what it sends by Django configuration (see https://docs.djangoproject.com/en/stable/topics/logging/) or using external service to log the errors and do not use email reporting at all for these (I'm currently using Rollbar <https://rollbar.com/>, but I've seen good experiences with Sentry <https://www.getsentry.com/> as well).

**Comment by V-Z** [comment]
Yes, I'm talking about notifications from Weblate. Well, I don't know how Weblate is structured internally, but it'd be very nice to be able to send notification mails e.g. daily. :-)

**Comment by stanislav-brabec** [comment]
It is extremely annoying for the "Upload po file as suggestion" feature. If I upload po file with 100 changed strings, people will get 100 mails, one per changed string.

**Comment by V-Z** [comment]
stanislav-brabec is right. It'd be great if operation with PO files would be treated as one operation - sending one e-mail with all changes regarding respective PO file...

**Comment by Naruto0** [comment]
Hi @nijel. Is it possible to grab all changes from DB once a day and make it as a digest?

Regards!

**Comment by nijel** [comment]
You can fetch them from a database: `Change.objects.filter(timestamp__gt=previous_run)` (you will need more filtering there though.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
