### ISSUE TITLE
Glossary support for the DeepL service

### ISSUE THREAD

**Issue by kozi** [WeblateOrg/weblate#10468]
## Glossary support for the DeepL service

The Deepl service supports to use a glossary by providing a `glossary_id`.

![grafik](https://github.com/WeblateOrg/weblate/assets/464029/b7318b10-75b9-4186-a494-17bc4165575d)
https://www.deepl.com/de/docs-api/translate-text/translate-text

Currently it is not possible to add this `glossary_id` to the *API request*.

### Describe the solution you'd like

Provide a settings option at project level to specify the `glossary_id`
that should be used in the *DeepL API requests*.

The perfect solution would of course be if the glossaries at project level
were automatically generated as a DeepL glossary via the DeepL API
and this could then be used in the requests.

**Comment by nijel** [comment]
This is planned for 5.3, see #7086 for generic issue.
