### ISSUE TITLE
User receives also mails to administrate another languages

### ISSUE THREAD

**Issue by V-Z** [WeblateOrg/weblate#1047]
### Steps to reproduce
1. Go to Weblate settings and set some interface language (Czech in my case, I haven't tested another languages).
2. Select your translated language. Do not choose another alternative languages.
3. Go to notification settings and select all projects and all notifications.
   (see also attached screenshots below)

![weblate_jazyky](https://cloud.githubusercontent.com/assets/6032665/14146385/a046cb5a-f697-11e5-9870-133378e0abf6.png)
![weblate_oznamnei](https://cloud.githubusercontent.com/assets/6032665/14146384/a0458af6-f697-11e5-8471-0ef107700acb.png)
### Expected behaviour
- User receives only mails related to selected language, so no administrative requests for another languages.
- If user receives such administrative mail, the mail must directly lead to the task - in the example below, there is no link to go to solve the request.
### Actual behaviour

User (without administrative privileges!) receives also administrative requests for another languages, as on the example below:

```
[openSUSE Weblate] Požadován nový překlad v libgettextdemo/master
Od:     weblate-noreply@...
Komu:   Vojtech.Zeisek@...
Kopie: 
Skrytá kopie: 
Datum:  Dnes 14:19
X-Mailer:       Weblate 2.5

Ahoj,

v překladu libgettextdemo/master na openSUSE Weblate byl požadován nový
jazyk.

Prosím přidejte překladový soubor do VCS. Weblate ho automaticky objeví
při další aktualizaci.

Více informací o přidávání nových překladů je k dispozici v dokumentaci:
http://docs.weblate.org/en/weblate-2.5/devel/translations.html#adding-translation

Požadovaný jazyk:

Dutch (nl)

Uživatel:

Nathan Follens <nthn@unseen.is>

--
    Odesláno překladovým systémem Weblate
    http://l10n.opensuse.org/
    Změňte nastavení upozornění: http://l10n.opensuse.org/accounts/profile/#subscriptions
```

I really do not need such mails. And the are also useless as they do not have any link to solve the issue.
### Server configuration

Described behaviour happens on https://l10n.opensuse.org/
##

**Comment by nijel** [comment]
You've explicitly subscribed for new language requests and you get them, I don't see any issue with that. Weblate has no knowledge who can add new translation as this can be done in the Git repository, so anyone can subscribe to that...

**Comment by V-Z** [comment]
Sorry, but I don't see such option here. Which checkbox in (my case) is responsible for receiving of information mails about not followed languages? I still see as a bug...

**Comment by nijel** [comment]
In Czech it is "Upozornění na požadavky o nový překlad" and this notification is not bound to language...

**Comment by nijel** [comment]
It's same as merge failure notifications, these are also for subscribed project

**Comment by V-Z** [comment]
Yes, but it doesn't say anything about new/other language. As I have selected only Czech, I implicitly suppose it *is* restricted to selected language(s). Maybe this needs some clarification, changes in settings, ...?

**Comment by nijel** [comment]
I assume this has been clarified in #1253.
