### ISSUE TITLE
Translation is empty but it is exist in history

### ISSUE THREAD

**Issue by wirthandras** [WeblateOrg/weblate#10470]
### Describe the issue

We have recently encountered an issue: the translated phrases disappear from the input field but still exist in the history. Several text units exhibit the same behavior. These phrases are missing from the commit.

After restarting Weblate, I can re-add the translations from the history. After that the git commit contains the related changes. However, after updating from the git repository, the changes disappear again from the input field.

What shall we do? I search through earlier issues but didn't found any related to this. 
It seems to me there is no memory and CPU resource issue

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. the translated phrases disappear from the input field but still exist in the history.
2. After restarting Weblate,
3. I can re-add the translations from the history.
4.  After that the git commit contains the related changes. 
5. However, after updating from the git repository, the changes disappear again from the input field.

### Expected behavior

No disappearing text, serialization during commit works as expected.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/12913003/9488cf19-8b7f-4b24-bd43-83ba56264445)

### Exception traceback

```pytb
.
```

### How do you run Weblate?

Docker container

### Weblate versions

Weblate 4.8.1

### Weblate deploy checks

```shell
.
```

### Additional context

.

**Comment by wirthandras** [comment]
I forget to mention an important thing, recently we are switched from manual sync (manually push, the Commit, Push , and Update buttons in weblate web app) and now we are using the same things via Rest API

**Comment by wirthandras** [comment]
Weblate docker container became unhealthy:
![image](https://github.com/WeblateOrg/weblate/assets/12913003/502c01a4-a846-4cd8-8eb4-d95274bea17a)

**Comment by wirthandras** [comment]
I saw the following error in logs, Is that related here?
![image](https://github.com/WeblateOrg/weblate/assets/12913003/1835a502-4779-454f-a1a5-0bf348ab07a9)

`
nginx stderr | 2023/11/23 15:15:13 [error] 232#232: *1 open() "/app/cache/static/vendor/bootstrap/css/bootstrap-datepicker3.css.map" failed (2: No such file or directory), client: x.x.x.x, server: , request: "GET /static/vendor/bootstrap/css/bootstrap-datepicker3.css.map HTTP/1.1", host:
`

**Comment by nijel** [comment]
There was a corner case which could cause such behavior, which has been fixed in 5.2.1. Can you please upgrade?

PS: The missing `css.map` file is not related.

**Comment by wirthandras** [comment]
@nijel we have updated the weblate to version 5.2.1, Thanks!
