### ISSUE TITLE
Add labels support for translations

### ISSUE THREAD

**Issue by achtan** [WeblateOrg/weblate#1049]
can you add labels support for translations, I want to mark some translations... for example: emails, static-pages, category-names, etc...
##

**Comment by nijel** [comment]
Can you be a bit more specific? Many translation files support providing some context, that's what you're looking for?

**Comment by achtan** [comment]
not a context... labels like here in github, you can label issues for example...

**Comment by nijel** [comment]
Ah okay, now I understand that.

**Comment by nijel** [comment]
Currently there is only prioritization for strings, but labels might be added as well in future.

**Comment by nijel** [comment]
Proposed solution:

- [ ] Define labels at project level
- [ ] Possibility to attach labels to source strings
- [ ] Add label searches to translation dashboard
