### ISSUE TITLE
Logging in with Keycloak fails after upgrading from 4.18 to 5.2.

### ISSUE THREAD

**Issue by ScionOfDesign** [WeblateOrg/weblate#10502]
### Describe the issue

I recently upgraded my Weblate server from `4.18.2.2` to `5.2.1.1` (going through `5.0.2.2` as required) but now when I or one of my users tries to sign in through Keycloak we get the following message:
`Could not complete registration. The supplied e-mail address is already in use for another account.`

I tried setting the following environment variable:
`WEBLATE_SOCIAL_AUTH_KEYCLOAK_ID_KEY: preferred_username`

But that did not resolve the issue.
This also happens on `bleeding-2023-11-29-48863d1f4b3ec123e6eec7084a9ff6ba09c43678`.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Spin up a Weblate instance with version `4.18.2.2` with a Keycloak authentication connection as well as:
```
WEBLATE_NO_EMAIL_AUTH: "1"
WEBLATE_REGISTRATION_OPEN: "1"
```
2. Login through Keycloak with a user.
3. Upgrade to `5.0.2.2` and then `5.2.1.1`.
4. Try to login through Keycloak with the same user in step 2.
5. Observe the error.

### Expected behavior

I expected that I would still be able to login.

### Exception traceback

```pytb
There were no exceptions.
```

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.3-48863d1f4b
 * Django: 4.2.7
 * siphashc: 2.3
 * translate-toolkit: 3.11.1
 * lxml: 4.9.3
 * Pillow: 10.1.0
 * nh3: 0.2.14
 * python-dateutil: 2.8.2
 * social-auth-core: 4.5.0
 * social-auth-app-django: 5.4.0
 * django-crispy-forms: 2.1
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.4
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.13.1
 * rapidfuzz: 3.5.2
 * openpyxl: 3.1.2
 * celery: 5.3.6
 * django-celery-beat: 2.5.0
 * kombu: 5.3.4
 * translation-finder: 2.15
 * weblate-language-data: 2023.6
 * html2text: 2020.1.16
 * pycairo: 1.25.1
 * PyGObject: 3.46.0
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.4.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.37.1
 * Cython: 3.0.6
 * misaka: 2.1.1
 * GitPython: 3.1.40
 * borgbackup: 1.2.6
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.20.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * Python: 3.11.5
 * Git: 2.39.2
 * psycopg: 3.1.13
 * psycopg-binary: 3.1.13
 * phply: 1.2.6
 * ruamel.yaml: 0.18.5
 * tesserocr: 2.6.2
 * boto3: 1.33.2
 * zeep: 4.2.1
 * aeidon: 1.13
 * iniparse: 0.5
 * mysqlclient: 2.2.0
 * Mercurial: 6.6
 * git-svn: 2.39.2
 * git-review: 2.3.1
 * PostgreSQL server: 14.4
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.myorg.net
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://:xxxxxxxxxx@weblate-redis-master.weblate.svc.cluster.local:6379/1, redis://:xxxxxxxxxx@weblate-redis-master.weblate.svc.cluster.local:6379/1, regular
 * Platform: Linux 5.4.0-167-generic (x86_64)

### Weblate deploy checks

```shell
weblate@weblate-599875d55f-pdmn7:/$ weblate check --deploy
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)), please check EMAIL_* settings.
        HINT: https://docs.weblate.org/en/latest/admin/install.html#out-mail

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/latest/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/latest/admin/backup.html

System check identified 3 issues (1 silenced).
```

**Comment by nijel** [comment]
Issue in python-social-auth, please see https://github.com/python-social-auth/social-core/issues/854 f

**Comment by nijel** [comment]
Previous reelase of python-social-auth (4.4.2) will work. I want to release a fixed version today.

**Comment by mmospanenko** [comment]
Recently added SAML using Authentik and having the same issue with infinitive loop

"The supplied e-mail address is already in use for another account."
