### ISSUE TITLE
No /statistics REST API for categories

### ISSUE THREAD

**Issue by joubu** [WeblateOrg/weblate#10504]
### Describe the problem

The UI is displaying a nice view to show how much a language is translated for a given category:
/projects/:project/:category/#languages

However the REST API does not provide such route.

### Describe the solution you'd like

I guess we will need a new route GET /categories/:category_id/statistics/

### Describe alternatives you've considered

I am currently web scrapping from the UI.

**Comment by metalglove** [comment]
I'd like to work on this good first issue.

From my initial observation of the code base, I see that the `views.py` provides several components with the statistics endpoint exposed.  Are these statistics you mention the same generic statistics as the other components have?

**Comment by nijel** [comment]
Yes, the missing but is `statistics` endpoint on `CategoryViewSet`.

**Comment by metalglove** [comment]
@nijel could you take a look at my pull request?
