### ISSUE TITLE
Include list of skipped results of component discovery

### ISSUE THREAD

**Issue by lluisoxigen** [WeblateOrg/weblate#10515]
### Describe the issue

New docker weblate installation with version 5.2.1. Add Component works correctly. But on saving Component discovery, it shows "No matching components were found!". In the same path, it should have to discover 30 files more.

The setup is the following:

**Regular expression to match translation files against**
web_areapersonal_companyname/Resources/Views/Empleado/(?P\<component>[^/]\*)\\.(?P\<language>[^/.]*)\\.resx

**File format**
.NET resource file

**Customize the component name**
{{ component }}

**Define the monolingual base filename**
web_areapersonal_companyname/Resources/Views/Empleado/{{ component }}.resx

**Language filter**
^[^.]+$

**File mask** 
web_areapersonal_companyname/Resources/Views/Empleado/EmpleadoBandeja.*.resx

**Monolingual base language file** 
web_areapersonal_companyname/Resources/Views/Empleado/EmpleadoBandeja.ca.resx

**Gitlab repository file examples**
https://<span></span>gitlab.companyname.com/informatica/test_weblate/-/blob/develop/web_areapersonal_companyname/Resources/Views/Empleado/EmpleadoBandeja.ca.resx
https://<span></span>gitlab.companyname.com/informatica/test_weblate/-/blob/develop/web_areapersonal_companyname/Resources/Views/Empleado/EmpleadoPerfil.ca.resx

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

No response

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
> **Define the monolingual base filename** web_areapersonal_companyname/Resources/Views/Empleado/{{ component }}.resx

It is missing `.ca`, I guess the file without a language code doesn't exist.

> **Monolingual base language file** web_areapersonal_companyname/Resources/Views/Empleado/EmpleadoBandeja.ca.resx

**Comment by nijel** [comment]
Thanks for the suggestion, adding a list of skipped entries with a reason would be useful for debugging issues like this. `ComponentDiscovery.check_valid` would return an invalidity reason and `ComponentDiscovery.perform` would return an additional list of skipped entries.
