### ISSUE TITLE
Glossary support for Google Cloud Translation Advanced

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#10526]
### Describe the problem

Add glossaries support to Google Cloud Translation Advanced. Their documentation is at https://cloud.google.com/translate/docs/reference/rest/v3/projects.locations.glossaries, Python API is described at https://cloud.google.com/python/docs/reference/translate/latest/google.cloud.translate_v3.services.translation_service.TranslationServiceClient#google_cloud_translate_v3_services_translation_service_TranslationServiceClient_create_glossary.

### Describe the solution you'd like

Add `GlossaryMachineTranslationMixin` to `GoogleV3Translation`, hook it to `download_translations` and implement missing methods.

### Additional context

* 6efd08c0392e2a107da63e824d0c1b00effb6b57 implemented glossary support for DeepL.
* https://github.com/WeblateOrg/weblate/issues/10527

**Comment by gersona** [comment]
@nijel the glossary feature requires a new `bucket-name` field. Does it have to be a mandatory field ? I mean, if it is not provided, should the automatic suggestion be disabled altogether, or do we allow automatic suggestion to run normally but without the glossary ?

**Comment by nijel** [comment]
I think it should run without a glossary (storing glossaries will probably also lead to additional costs).
