### ISSUE TITLE
Change.DoesNotExist

### ISSUE THREAD

**Issue by dxdx123** [WeblateOrg/weblate#10524]
### Describe the issue

It seems to be a bug, it appears frequently in my local operating environment. Please help confirm.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

in the sentry issues

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/14290268/e19219e7-24ed-456c-b8f5-b74c0704dd4b)
![image](https://github.com/WeblateOrg/weblate/assets/14290268/8ba00bd2-507e-48dd-9327-18eaa84b58d4)
![image](https://github.com/WeblateOrg/weblate/assets/14290268/76b2bde7-0923-487f-ae7a-5f6b1302791a)

### How do you run Weblate?

Docker container

### Weblate versions

5.0.2

### Weblate deploy checks

```shell
docker
```

**Comment by nijel** [comment]
It should be harmless: it happens when a change is deleted before notification for it was processed.
