### ISSUE TITLE
No way to set default notification setting for watched projects

### ISSUE THREAD

**Issue by laoneo** [WeblateOrg/weblate#10533]
### Describe the issue

Thanks for this great project. On the notifications part there is some room for improvements as when you come from transifex, you get a lot of useful notifications which encourage user to finish the translation of a language when stuff changes. Would it be possible to set some defaults for the "New translation component was created" and "New string is available for translation" settings. As IMO for these settings an instant notification should be sent out. Probably some more would be nice too.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Got to /accounts/profile/#notifications__1
2. Check the component and translation notifications

### Expected behavior

Some default settings to adjust, either in the GUI or by configuration variable.

### How do you run Weblate?

Docker container

### Additional context

Kind of related to #5155.

**Comment by nijel** [comment]
"New string is available for translation" can be pretty noisy when triggered for each string, so you want that one to be digest.

Anyway: Where these additional defaults should be set and by who? 

Weblate already has built-in defaults:

https://github.com/WeblateOrg/weblate/blob/47b99981341f925c937153b87613bbf99373526a/weblate/accounts/data.py#L12-L22

Admin presets are covered by https://github.com/WeblateOrg/weblate/issues/5155

**Comment by laoneo** [comment]
Thanks for the answer, as I'm using docker, it is probaly not really possible to set these defaults.

I was playing around a bit more with weblate and when I commit new strings or updated strings, weblate receives them correctly from the Github webhook. But no notifications are going out, should I open a new ticket for that?

**Comment by nijel** [comment]
https://github.com/WeblateOrg/weblate/pull/10659 should address notifications for new strings.

**Comment by laoneo** [comment]
Thanks, and what about updated strings? Is this something you want to address too?

**Comment by nijel** [comment]
Yes, we should cover that as well.

**Comment by laoneo** [comment]
Do you not want to add #10651 to the 5.4 milestone instead of this one? As per your [comment](https://github.com/WeblateOrg/weblate/issues/10533#issuecomment-1847193042) this is already possible, just didn't figure out how in docker.

**Comment by nijel** [comment]
#10651 is already added to that milestone. I'd like to change the defaults in this issue to give users more notifications. I am not sure if we want to make this admin configurable, though.
