### ISSUE TITLE
Addons page

### ISSUE THREAD

**Issue by sudhan77** [WeblateOrg/weblate#10538]
### Describe the issue

 In weblate 5.2.1 I am not able to see any Addons in the site. I discovered this while trying to install a custom addon.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

i was trying to create a custom addon. but i dont recall having seen the addon option on the site earlier. the site is otherwise working fine.

### Expected behavior

i want to see the existing Addon page as given in https://docs.weblate.org/en/weblate-5.2.1/admin/addons.html 

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
There can be several reasons:

* You are looking at the wrong level, add-ons are currently only on component
* You don't have permissions to edit the component and thus to manage add-ons
