### ISSUE TITLE
Project overview page shows unfinished languages, but they are

### ISSUE THREAD

**Issue by laoneo** [WeblateOrg/weblate#10540]
### Describe the issue

On my self hosted weblate instance it shows certain languages as not fully translated, but they are. Repo is fully in sync, there is nothing to commit or update.

I'v searched the documentation and issue, nothing came up with information how to rebuild that statistics. As I'm running it through docker, it is still on version 5.2.1. If the issue has been fixed in the meantime, I do apologize and will close the issue and wait for the docker update.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to https://translate.digital-peak.com/projects/dpcalendar/#languages
2. German language is shown with two missing strings
3. Click on German language (de-DE)
4. No strings to translate are found

### Expected behavior

Overview page shows German language as translated.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/251072/6e4b2f7c-1926-49a9-ba38-190955a09cf4)

![image](https://github.com/WeblateOrg/weblate/assets/251072/17829ec6-469d-44e8-bd6b-7a3775c8f81e)

### How do you run Weblate?

Docker container

### Weblate versions

Running it through docker with the latest version:

 * Weblate: 5.2.1
 * Django: 4.2.7
 * siphashc: 2.3
 * translate-toolkit: 3.11.1
 * lxml: 4.9.3
 * Pillow: 10.1.0
 * nh3: 0.2.14
 * python-dateutil: 2.8.2
 * social-auth-core: 4.5.0
 * social-auth-app-django: 5.4.0
 * django-crispy-forms: 2.1
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.4
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.13.1
 * rapidfuzz: 3.5.2
 * openpyxl: 3.1.2
 * celery: 5.3.6
 * django-celery-beat: 2.5.0
 * kombu: 5.3.4
 * translation-finder: 2.15
 * weblate-language-data: 2023.6
 * html2text: 2020.1.16
 * pycairo: 1.25.1
 * PyGObject: 3.46.0
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.4.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.36.0
 * Cython: 3.0.5
 * misaka: 2.1.1
 * GitPython: 3.1.40
 * borgbackup: 1.2.6
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.20.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * Python: 3.11.5
 * Git: 2.39.2
 * psycopg: 3.1.13
 * psycopg-binary: 3.1.13
 * phply: 1.2.6
 * ruamel.yaml: 0.18.5
 * tesserocr: 2.6.2
 * boto3: 1.29.5
 * zeep: 4.2.1
 * aeidon: 1.13
 * iniparse: 0.5
 * mysqlclient: 2.2.0
 * Mercurial: 6.6
 * git-svn: 2.39.2
 * git-review: 2.3.1
 * PostgreSQL server: 16.1
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.cyon.ch
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://translation-cache:6379/1, redis://translation-cache:6379/1, regular
 * Platform: Linux 5.15.0-89-generic (x86_64)

**Comment by nijel** [comment]
Most likely related to https://github.com/WeblateOrg/weblate/issues/10508. It should be already fixed in the `main` branch for the 5.3 release.

**Comment by laoneo** [comment]
Thanks for the information. Any plan when this will be released? And when the docker images will be rebuilt with that patch?
