### ISSUE TITLE
would like to invite new users to register and log in to Weblate using their Gmail

### ISSUE THREAD

**Issue by dxdx123** [WeblateOrg/weblate#10562]
### Describe the problem

I have configured Google OAuth2 authentication in Weblate, allowing existing users to bind their Gmail accounts and log in using Gmail. 
I would like to inquire if Weblate supports new users logging in directly with their Gmail accounts when registration is not open?

### Describe the solution you'd like

As mentioned above

**Comment by nijel** [comment]
Admin invitations should work even with registration disabled

**Comment by dxdx123** [comment]
> Admin invitations should work even with registration disabled
my version is 5.0.2 running in docker

**Comment by nijel** [comment]
I've just tested it, and it works for me.

- Does the user see it in Weblate after following the link? User should get a registration form with invitation info on the top.
- Does the user get some error after following to Google auth button on the registration page?

**Comment by dxdx123** [comment]
![image](https://github.com/WeblateOrg/weblate/assets/14290268/4bef8988-4733-469c-b83a-22fc6c627bd4)
