### ISSUE TITLE
INI file: strings prefix with 'rem' missing

### ISSUE THREAD

**Issue by TakWolf** [WeblateOrg/weblate#10561]
### Describe the issue

Project is https://hosted.weblate.org/projects/aseprite/aseprite/en/#search

The follow sentences cannot be searched, but they do exist.

https://github.com/aseprite/aseprite/blob/516a927a59d8b6dc65061da39bcbf3434965337a/data/strings/en.ini#L162-L165

https://github.com/aseprite/aseprite/blob/516a927a59d8b6dc65061da39bcbf3434965337a/data/strings/en.ini#L385-L388

```
[color_bar]
remap_palette = Remap Palette
remap_palette_tooltip = Matches old indexes with new indexes
remap_tiles = Remap Tiles
remap_tiles_tooltip = Matches old tiles with new tiles

[commands]
RemoveFrame = Remove Frame
RemoveFrameTag = Remove Tag
RemoveLayer = Remove Layer
RemoveSlice = Remove Slice
```

The statistics count are also incorrect, now is 1606 but actually it should be 1614. (Exactly 8 are missing)

They all use ‘rem’ as a prefix, and I'm not sure if it's related to this.

Raise from: https://github.com/aseprite/aseprite/issues/4208

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Go to https://hosted.weblate.org/projects/aseprite/aseprite/en/#search

<img width="695" alt="image" src="https://github.com/WeblateOrg/weblate/assets/6064962/54d897d7-0516-4ee6-8da9-dbd3993cc0dc">

<img width="681" alt="image" src="https://github.com/WeblateOrg/weblate/assets/6064962/1ed3bf34-6629-4051-8369-f0783fc4b097">

### How do you run Weblate?

weblate.org service

**Comment by dacap** [comment]
Probably related to this "allow_rem" parameter from iniparse API:

https://github.com/candlepin/python-iniparse/blob/dbfd7174ee1e9a8e25cdc1694703d59b4ab109a1/iniparse/ini.py#L188-L194

Probably these lines are being parsed as comments.

**Comment by TakWolf** [comment]
Indeed.  ';' or '#' or 'rem' start line parse as a comment.

https://github.com/candlepin/python-iniparse/blob/dbfd7174ee1e9a8e25cdc1694703d59b4ab109a1/iniparse/ini.py#L198

![image](https://github.com/WeblateOrg/weblate/assets/6064962/03ab6587-f996-47df-86cb-aebbf97f4bdf)
