### ISSUE TITLE
Creating terminology entry crashes if it exists in another language

### ISSUE THREAD

**Issue by TakWolf** [WeblateOrg/weblate#10581]
### Describe the issue

If some glossary string has been create in other language, we can't use Terminology option (String will be part of the glossary in all languages) 

![image](https://github.com/WeblateOrg/weblate/assets/6064962/b3d3498c-2082-4104-bb48-f557db95f386)

Raise from: https://github.com/aseprite/languages/issues/28

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

![image](https://github.com/WeblateOrg/weblate/assets/6064962/3fbb3f52-c618-45ed-b18c-d48e2cbc5ed5)

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
You can mark existing string as a terminology instead of adding new one.
