### ISSUE TITLE
Gerrit integration: configure gitreview.username from ssh://user@gerrit... push-URL / provide way to set username from UI

### ISSUE THREAD

**Issue by cloph** [WeblateOrg/weblate#10596]
### Describe the problem

gerrit integration ignores the username provided in push-URL and instead uses the system user's name, at least in the presence of a .gitreview file specifying host, port, project and branch but omitting a username.

That then obviously fails due to lack of permissions and git-review used by weblate asks for a username to try again (and since it is run non-interactive mode it only gets EOF)

### Describe the solution you'd like

Weblate should set up gitreview.username configuration when setting up a component/new repository. Either by adding a dedicated input field in the VCS settings, or more straightforward reading it from the pushurl if in ssh://user@..... format

### Describe alternatives you've considered

Alternatively it can be solved by telling the user in documentation to manually set the git config in the data/vcs... clone

**Comment by nijel** [comment]
This should be pretty easy to implement by customizing `configure_remote` in the `GitWithGerritRepository` class.

**Comment by harriebird** [comment]
Hi guys, check my PR #11585 for this issue.
