### ISSUE TITLE
Gerrit-integration: suggest using the sqash addon or have a gerrit user with forge author identity permissions

### ISSUE THREAD

**Issue by cloph** [WeblateOrg/weblate#10597]
### Describe the problem

gerrit rejects commits from regular users that don't match one of the email addresses associated with the account. So in the default setup where weblate creates a commit with the translator's committer information, trying to push to gerrit will be rejected since the translator's email is no associated with the gerrit user doing the push.

### Describe the solution you'd like

When using VCS with Gerrit integration show a note that you either need a gerrit-account that has the forge author permissions for the repository/branch or have to use the squash addon.

### Describe alternatives you've considered

This is not a bug, just a documentation/QOL thing and there are no alternatives - either create a bot user that do commits with any identity or rewrite the commits/use the bot account itself as committer & author.

**Comment by nijel** [comment]
What kind of error would you get if not following this? Adding it to the push failure alert analysis would be probably the best approach:

https://github.com/WeblateOrg/weblate/blob/40161dfa2e4fd361d61fd31abc9f1b93aa71c924/weblate/trans/models/alert.py#L203-L272

**Comment by nijel** [comment]
The best approach probably would be to go through https://gerrit-review.googlesource.com/Documentation/error-messages.html and add hints for error messages that indicate Weblate misconfiguration. Somebody knowing Gerrit needs to do that.

**Comment by cloph** [comment]
As for the error message from gerrit: Generated here: https://gerrit.googlesource.com/gerrit/+/refs/tags/v3.9.1/java/com/google/gerrit/server/git/validators/CommitValidators.java#980

There are two variants: committer forging and author forging - for weblate I think only the author one is relevant, so message would be 
"email address <author@email.address> is not registered in your account, and you lack 'forge author' permission."
