### ISSUE TITLE
Could not use Pango: 'could not find foreign type Context'

### ISSUE THREAD

**Issue by FunSkelet** [WeblateOrg/weblate#10590]
### Describe the problem

во время использования команды 
weblate runserver
появляется ошибка `?: (weblate.C024) Could not use Pango: 'could not find foreign type Context'
`

### Describe the solution you'd like

no error

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/68019106/5c3dfa40-78fb-4cc2-af3c-5e5c891ecb0e)

**Comment by nijel** [comment]
You are missing Pango GObject introspection data, please refer to our installation guides for info how to install system requirements: https://docs.weblate.org/en/latest/admin/install.html

**Comment by DormantCat** [comment]
fixed:
`sudo apt install python3-gi-cairo`
