### ISSUE TITLE
WeblateLockTimeoutError

### ISSUE THREAD

**Issue by dxdx123** [WeblateOrg/weblate#10594]
### Describe the issue

When I batch edited lables, the error occurred: WeblateLockTimeoutError
Sorry, I don’t quite understand the true meaning of this error.
Is there any guidance or advice?

To add: When performing machine translation, this problem is more likely to occur.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

/projects/xxxx/xxxxxxxx/zh_Hant/#bulk-edit

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/14290268/60f0fd96-0d93-4c57-b2e7-f1803cb903ec)
![image](https://github.com/WeblateOrg/weblate/assets/14290268/03402f86-d1ad-46ac-8912-26aeafa1638a)

### How do you run Weblate?

Docker container

### Weblate versions

5.0.2

**Comment by nijel** [comment]
Weblate does internally lock the component while updating the repository, performing automatic translation or doing bulk edits. Check Weblate logs whether something like that is running in the background.

Without locking, such bulk operations could have caused consistency issues like described in https://github.com/WeblateOrg/weblate/issues/5686. The question is whether this locking is still needed as there were some other cleanups meanwhile which should avoid them.

**Comment by tipa** [comment]
I also started to get those `WeblateLockTimeoutError` errors after updating to v5.3.
They occur when downloading translations using the API.
I have restarted Weblate & Celery multiple times, but the problem persists.

```
WeblateLockTimeoutError: Lock on lock:repo:11 could not be acquired in 120s
  File "weblate/utils/views.py", line 471, in download_translation_file
    translation.commit_pending("download", None)
  File "contextlib.py", line 81, in inner
    return func(*args, **kwds)
  File "weblate/trans/models/translation.py", line 560, in commit_pending
    return self.component.commit_pending(reason, user, skip_push=skip_push)
  File "weblate/trans/models/component.py", line 192, in on_link_wrapper
    return func(self, *args, **kwargs)
  File "weblate/trans/models/component.py", line 1932, in commit_pending
    with self.repository.lock:
  File "weblate/utils/lock.py", line 86, in __enter__
    self._enter_implementation()
  File "weblate/utils/lock.py", line 70, in _enter_redis
    raise WeblateLockTimeoutError(
```

**Comment by nijel** [comment]
@tipa: That is repository level lock unlike component level lock in the original post. Maybe there is (was) another operation in progress? Check the logs. There was no change in the locking since 5.0.
