### ISSUE TITLE
 translated text status was accidentally overwritten

### ISSUE THREAD

**Issue by dxdx123** [WeblateOrg/weblate#10602]
### Describe the issue

This is a confusion that has existed for several months. While using weblate, we found that the translated text status was accidentally overwritten.

from v4.18~5.0.2

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

As shown in the red number in the screenshot, 
1. The first submission of source string and target string. The status is: translated.
2. The source string of the upstream warehouse has been modified.
3. The status of the source string is automatically changed to needs editing. Modified on December 5th.
4. The status automatically changed to translated without anyone's operation. This is not what we expect. We hope that it will remain needs editing. Modified onDecember 11

### Screenshots

![企业微信截图_17024376408961](https://github.com/WeblateOrg/weblate/assets/14290268/497655b9-7939-4d5c-b51b-2520baf542a3)

### How do you run Weblate?

Docker container

### Weblate versions

5.0.2

**Comment by nijel** [comment]
This could have happened with monolingual translations after editing source strings in some corner cases. It should be fixed in 93c0516db7919b154bbf5beb090702bec0642acb.
