### ISSUE TITLE
Missing check for perl-brace-format

### ISSUE THREAD

**Issue by joubu** [WeblateOrg/weblate#10626]
### Describe the issue

I may be missing something obvious here, but I am seeing the following 2 issues (caught using junitmsgfmt on .po files):

1. Typo in parameter
```
#, perl-brace-format
msgid "Delete CSV profile '{csv_profile_name}'?"
msgstr "CSV-Profil '{csv_provile_name}' löschen?"
```

2. Square brackets instead of curly brackets:
```
#, perl-brace-format
msgid "Modify {servertype} server '{servername}'"
msgstr "Server {servertype]-Server '{servername}'"
```

They are not caught by Weblate's UI, is this expected? Is it related with perl-brace-format?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Have an incorrect msgstr translations, go to the translation and expect a warning.

### How do you run Weblate?

Docker container

**Comment by joubu** [comment]
Is it because Weblate expects `perl-format` instead of `perl-brace-format`?

https://docs.weblate.org/en/latest/user/checks.html#perl-format

**Comment by nijel** [comment]
I guess that is something different, similarly as with Python there are two ways of formatting.
