### ISSUE TITLE
Setting for Language Creation in Component not copied during Auto Component Discovery

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#10637]
### Describe the issue

When setting up multiple components via auto component discovery from upstream repo, the setting for Adding Languages is not copied over correctly.

The "template component" has "Disable" selected.
The discovered components have "Create" selected.

![image](https://github.com/WeblateOrg/weblate/assets/26718215/04f0396b-9380-488e-95a3-76a2764a3c4f)

Weblate **[5.0.2]** (https://github.com/WeblateOrg/weblate/releases/tag/weblate-5.0.2)
File Format **XLIFF 1.2 translation file**

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Setup "template" Component
Select Disable Adding Languages
Setup Auto Discovery
Check settings of new "discovered" components

### Expected behavior

Setting is copied over from template component

### How do you run Weblate?

Docker container

### Weblate versions

5.0.2

**Comment by nijel** [comment]
It works for me as expected - the setting is copied. Maybe the component was changed meanwhile?
