### ISSUE TITLE
graphviz missing from dev (or tests) dependency list

### ISSUE THREAD

**Issue by joubu** [WeblateOrg/weblate#10636]
### Describe the issue

Installing from source to run the test suite and ./ci/run-docs is failing with `WARNING: dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting`
I had to install graphviz.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Run ./ci/run-docs

### How do you run Weblate?

Git checkout

**Comment by nijel** [comment]
It is needed to build schemas in the documentation, so it probably should be documented somewhere.

**Comment by juliogit16** [comment]
que honda se fueron las ratas del barco no te preocupes se los correos de todos los tengo en una libreta me saludas u tu novio el Joubu 
![image](https://github.com/WeblateOrg/weblate/assets/153862119/035e8c03-aea6-438e-a58e-274c3e354ee6)

**Comment by juliogit16** [comment]
tengo 3 meses pidiendote ayuda sal de mi IP es lo unico que te voy a decir y enviame certificados buenos no las basuras esas de 2.0 quiero los legales de mis equipos y pagamelos
