### ISSUE TITLE
Possible bug in Search on TMs in the Automatic Suggestions tab

### ISSUE THREAD

**Issue by valtermura** [WeblateOrg/weblate#10649]
### Describe the issue

While searching through the Search field in the "Automatic suggestions" (tab), Weblate returns a series of empty (blank) correspondences for the columns Translation, Suggested change and Source

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. browse to a string you want to translate (with suggestion or not) and go to the tab "Automatic suggestions"
2. if you are lucky, several suggestions will appear with a percentage of "Similarity", a "Translation", a "Suggested change", its "Source" and its "Origin"
3. but... if you search in the "Translation memory" field for a term and click the "Search" button, Weblate returns a series of empty (blank) correspondences for the columns Translation, Suggested change and Source

### Expected behavior

It should show the correspondences, as when you go to "Automatic suggestions" without using the Search field.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/10959279/8481ad7b-488b-4753-9304-5e913de4322e)
(normal view from Automatic Suggestions tab)

![image](https://github.com/WeblateOrg/weblate/assets/10959279/a7f8f1db-cf35-473e-85c3-90f1d51ad41d)
(view after searching a word in the TM Search field)

### How do you run Weblate?

Other

### Weblate versions

Weblate v. 5.1.1 on https://translations.documentfoundation.org/

**Comment by nijel** [comment]
This should be already fixed by ca8c8c2083049fae0b68419d2ac45139db0d809e.

**Comment by valtermura** [comment]
Not sure it has been fixed. I can still see the same problem (the columns are blank)

**Comment by nijel** [comment]
You're using 5.1.1 and this has been fixed in 5.2...
