### ISSUE TITLE
Hebrew plurals: other got lost after import

### ISSUE THREAD

**Issue by mtotschnig** [WeblateOrg/weblate#10670]
### Describe the issue

On Hosted Weblate: https://hosted.weblate.org/projects/my-expenses/
After applying Android Lint's suggestion to remove the "many" variant from Hebrew plurals strings: https://github.com/mtotschnig/MyExpenses/commit/83c979e1c006d41952eb8724930fdc9506521e44
and updating the project in Weblate's Manage section, the "other" variant is no longer shown in Weblate, and a Missing plurals warning is raised: https://hosted.weblate.org/translate/my-expenses/strings/he/?q=has:check

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

See above

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
It turns out that the definition for `iw` is out of syncs with `he` in translate-toolkit, https://github.com/translate/translate/pull/5147 will fix that.

**Comment by mtotschnig** [comment]
@nijel Thank you very much for addressing this issue so quickly! Once the fix is deployed to Weblate.org, will the missing translations appear again automatically, or do I need to update the project again?

**Comment by nijel** [comment]
It should be fixed now, I've forced reloading the files.
