### ISSUE TITLE
Add link to organize next to name in component/project settings

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#10680]
### Describe the problem

User often do not find the Organize item while looking for it in settings.

### Describe the solution you would like

Add a link to organize next to the name setting.

### Describe alternatives you have considered

Merging the forms would also be an option, but it is intentionally separate to make it less likely somebody will rename accidentally.

**Comment by Maddy0027** [comment]
can you explain me more what are expecting in this

**Comment by nijel** [comment]
The component or project settings allow to change visible name only:

![image](https://github.com/WeblateOrg/weblate/assets/212189/c7bbb94b-1051-406e-b4bf-a9ab7620feb9)

There is a separate view for renaming or moving between projects or categories:

![image](https://github.com/WeblateOrg/weblate/assets/212189/39d22b2e-b815-475b-b229-790e0cc91b04)

The settings view should have a link to organize one so that it can be found directly from the settings.
