### ISSUE TITLE
Add group permissions inheritance

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1069]
While working with the newly introduced Group ACL, it is very incomfortable to make clones of Users group, which is required for each language review group.

It would be nice to introduce clone feature, either on GUI level: Initialize new group with a clone of permissions set of another group, or in a dynamic way: define group as a dynamic clone, and define only permissions that need to be added or removed from its parent.
##

**Comment by nijel** [comment]
Probably adding [save_as](https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.save_as) to the Group admin will be easiest solution...
