### ISSUE TITLE
GroupACL sometimes allows user permissions to apply

### ISSUE THREAD

**Issue by matejcik** [WeblateOrg/weblate#1070]
While testing GroupACLs in the wild, we discovered some problems.

The first clue was that `can_suggest` checks both the GroupACL mechanism and the traditional mechanism -- meaning that even if a GroupACL applies, users can still add suggestions (if they have the permissions from the Users or Guests group). This is desirable in our case :) but goes against how GroupACLs should work -- that is, by locking out permissions from all but the assigned groups.

This seems to be the case for all callers of `check_permission`, which allows both `has_group_perm` and `user.has_perm` calls. (`has_group_perm` calls `user.has_perm` internally when appropriate)

Please take a look at the source, check if this is really a bug the way I think it is a bug, and if so, i'll send a PR to fix it :)
##

**Comment by nijel** [comment]
It seems to make sense, though I'm probably too tired today to fully understand this :-).
