### ISSUE TITLE
Comparison between Weblate/Pontoon/Phrase/Lokalise/Crowdin

### ISSUE THREAD

**Issue by saumil-kapadia-stellantispublic** [WeblateOrg/weblate#10711]
### Describe the problem

It will be really easy to decide on which tool has what features, pros-cons if there are comparison available.

### Describe the solution you would like

Creating blogs of product comparison.

**Comment by nijel** [comment]
It would be nice to have, but there are some gotchas:

* To produce an in-depth comparison, a person should be experienced in using all the compared tools.
* When we as Weblate authors would do it, there would be definitely a bias in features we consider important.
* There are way more platforms which could be included in the comparison (Transifex and Crowdin to name some of them).

In other words, I'd like to see such a review so that we can learn from it, but I don't think we should be the ones performing it.

**Comment by saumil-kapadia-stellantispublic** [comment]
@nijel I feel it is fairly okay to do the comparison from Weblate as the product features your team is building will be in some alignment to the market research done by your business development teams. Also to start with if not in-depth but high level feature to feature comparison can be done. By the way I couldn't also find any one place where we can find all the features of weblate.

**Comment by nijel** [comment]
High level Weblate features overview is at https://weblate.org/features/

**Comment by saumil-kapadia-stellantispublic** [comment]
Thanks for sharing. Does weblate support Machine translations, Over-the-air translation updates to apps/web using SDKs, Figma & Github integration, translation versioning?

**Comment by nijel** [comment]
Machine translations are supported, see https://docs.weblate.org/en/latest/admin/machine.html for list of supported services.

GitHub (and many other code hosting sites) are integrated, see https://docs.weblate.org/en/latest/vcs.html.

There is a third-party Figma plugin, see https://docs.weblate.org/en/latest/devel/thirdparty.html.

For versioning, we rely on Git.

3rd party can download translation for offline usage, see https://docs.weblate.org/en/latest/user/files.html.

**Comment by saumil-kapadia-stellantispublic** [comment]
Great! I think one point is missed out is how translations are downloaded/streamed to mobile and web apps? Are there any sdk for android/ios/flutter which can download the updated translations dynamically without requiring app release in play store? 

Few more doubts:

- How do we achieve translation state from preprod env to prod env? 
- Is there internal/external translator and verifier roles available? 
- Is there user specific permissions management?
- Is there any level of approvals workflow before it goes in production?

**Comment by nijel** [comment]
* There is currently no SDK available.
* Typically this is done using the same approach you use for the code.
* There is no built-in internal/external role, but you can define roles and teams as you wish, see https://docs.weblate.org/en/latest/admin/access.html
* Yes, see https://docs.weblate.org/en/latest/admin/access.html
* Yes, there are several options for configuring the workflow, see https://docs.weblate.org/en/latest/workflows.html
