### ISSUE TITLE
Allow to set dedicated contact email address instead of administrators

### ISSUE THREAD

**Issue by tcitworld** [WeblateOrg/weblate#10716]
### Describe the problem

Administrators are not necessarily the appropriate people to be contacted through the contact form. For instance, system administrators can be interested in errors details but not in people asking for an account.
On the other hand, the contact form submissions can be transmitted to a ticketing system like Request Tracker, but errors shouldn't be.

### Describe the solution you would like

A way to separate contact form recipients and admins.
Admins should receive errors and emails from Weblate itself, whereas contact form recipients should only get contact form submissions.

For instance, we could have two extra parameters for the `CONTACT_FORM` settings:
* `send_to_admins`: Include the admins in the contact form recipients. Defaults to `true`
* `recipients`: a list of recipients to send the contact form to, using the same tuple form as `ADMINS`. Defaults to an empty list.

### Describe alternatives you have considered

Using the reverse proxy to redirect `/contact/` to an external contact form, so that submissions aren't sent to administrators.

**Comment by nijel** [comment]
There already is `ADMINS_CONTACT` setting, but it lacks documentation…

**Comment by tcitworld** [comment]
That works perfectly, thanks for your answer and for adding it to the docs!
