### ISSUE TITLE
Fallback groups for GroupACL

### ISSUE THREAD

**Issue by matejcik** [WeblateOrg/weblate#1071]
I expected this to be necessary, so this issue is mostly for record keeping.

If #1070 gets fixed, we will have no way to allow users _any_ actions on GroupACL-locked objects, unless we add a "fallback group".

That is, change behavior of GroupACL locking from:
1. if you're member of a locked group, you get permissions from the group
2. otherwise, you don't get any permissions whatsoever

to:

1. if you're member of a locked group, you get permissions from the group
2. otherwise, you get permissions from a designated "fallback" group

The expected usecase would be to designate a group -- either use Guests, or pared-down Users (#1069 for copying or inheriting groups) -- with "lower than usual" permissions.

A potential issue is with anonymous/known users distinction. With the fallback mechanism, we would either grant both logged-in and anonymous users the same privileges, or we would lock out anonymous users completely.
Alternately, we could add an "anonymous fallback", which seems excessive. Or, possibly most reasonable, limit anonymous users to those permissions that they get from Guests and that are present on the fallback group at the same time.
(so for example, if Guests `can_suggest` and FallbackGroup also `can_suggest`, anonymous users can post suggestions. However, if Guests can suggest and FallbackGroup can't, anonymous users can't suggest either)
Maybe this behavior should apply to the fallback group in general? Name it "retain group" and consider the group a set of permissions that you retain if you got them from the result of `user.has_perm`.

what do you think?
##

**Comment by matejcik** [comment]
Better solution: instead of specifying a fallback group, listing "restricted permissions" directly on the GroupACL object. This would limit the list of permissions on which the GroupACL logic applies, in addition to on which object these apply.

---

Thinking more about this, maybe GroupACL should morph into "group access policies." Each policy would have associated a set of projects, components and/or languages, possibly specified by a wildcard (this could be combined with component lists, for that matter. an access policy applies to objects covered by a component list)
and a list of restricted permissions that could only be gained through the groups listed in the policy

**Comment by nijel** [comment]
The second suggestion seems better to me. It seems easier to manage than fallback groups.
