### ISSUE TITLE
Missing index on trans_unit.pending

### ISSUE THREAD

**Issue by joubu** [WeblateOrg/weblate#10722]
### Describe the issue

We are experiencing performance issues, bottleneck is at disk level caused by postgres SELECT queries.

For instance the following query takes ~30 seconds:
```
SELECT COUNT(*) AS "__count" FROM "trans_unit"
INNER JOIN "trans_translation" ON ("trans_unit"."translation_id" =
"trans_translation"."id") WHERE ("trans_unit"."pending" AND
"trans_translation"."component_id" = 136)
```

There are ~15M entries in trans_unit.

We have created an index and the query now takes few ms

```
CREATE INDEX CONCURRENTLY trans_unit_pending ON trans_unit(pending)
WHERE pending;
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Have a lot of entries in trans_unit and run the previous query.

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
Index on that field was there, but it generally did not perform that well, so it was changed in aed8cf67cceee210640fbf8ba28520da174c6291 and removed in ab7f2945fc9417a58699ddb6077b7c5ab40062ed. Using condition in WHERE might address the issues we had with the full table index on the field, though.

https://github.com/WeblateOrg/weblate/issues/8770 should also be considered when touching this.
