### ISSUE TITLE
Progress Color for failed Checks missing after Update

### ISSUE THREAD

**Issue by PeterDurrer** [WeblateOrg/weblate#10735]
I Have Update the weblate, Now i miss the old colors for the failed Checks and Marked Captions. I have found that this is changed with https://github.com/WeblateOrg/weblate/pull/9794 but is changed withouth configure option. Our employees are used to the old view and have used the color separation for state tracking.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Open the Overview Dashboard with diffrent projects an captions with failed checks.There are now only green and grey color on progress bar:
![image](https://github.com/WeblateOrg/weblate/assets/116004093/14fc516c-2e5b-4524-b33a-0e2d1ddebb91)

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
The progress bar is still the same, it's only showing a gray color instead of red.

It probably could be added as an option to customize these colors in the appearance settings (which lack documentation, see https://github.com/WeblateOrg/weblate/issues/6037).

**Comment by PeterDurrer** [comment]
> The progress bar is still the same, it's only showing a gray color instead of red.
> 
> It probably could be added as an option to customize these colors in the appearance settings (which lack documentation, see #6037).

Thank you i have not found the other issue.

**Comment by m-aciek** [comment]
For what it's worth the progress bars simplification was released in 4.6 with https://github.com/WeblateOrg/weblate/commit/61e655634e536441c10f673e0abbacc06e7ea703 commit.
