### ISSUE TITLE
An error occurred when using OpenAI for machine translation

### ISSUE THREAD

**Issue by dxdx123** [WeblateOrg/weblate#10749]
### Describe the issue

My Weblate version is 5.3.1. When performing machine translation, it puts all the terms into the request, causing the request to fail. It should actually retrieve terms related to the source text for translation.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Perform automatic translation use openai

### Expected behavior

Match only related terms

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/14290268/02e9d6d2-235a-43fa-8402-2df7b10a196a)

### Exception traceback

```pytb
machinery failed: BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 4097 tokens. However, your messages resulted in 21420 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
```

### How do you run Weblate?

Docker container

### Weblate versions

5.3.1

**Comment by nijel** [comment]
That's a great idea for improvement. Presently, OpenAI shares the glossary code with other machine translation backends which store glossary server-side, and thus we need to push the full glossary there.
