### ISSUE TITLE
NBSP rendering issues in Chrome

### ISSUE THREAD

**Issue by sinnnie** [WeblateOrg/weblate#10767]
### Describe the issue

In editor when rendering a list of lines containing non breaking spaces, extra highlighted blocks or symbols appear at the end of the string.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to Editor
2. Open any string containing nbsp
3. Open any of following tabs: Nearby strings, Similar keys, Automatic suggestions, Other languages

### Expected behavior

Strings rendered as they are in localization files

### Screenshots

![Screenshot 2024-01-12 153419](https://github.com/WeblateOrg/weblate/assets/22768922/b39cdec6-67cc-4b6a-ba80-e423285888d6)

### How do you run Weblate?

Docker container

### Weblate versions

Weblate 5.3.1

**Comment by nijel** [comment]
Can you please be more specific when this happens? I've just randomly found some strings with non-breakable space and they look correctly:

![image](https://github.com/WeblateOrg/weblate/assets/212189/c0692e4a-1a06-4d65-87af-19e8e6e5ccaf)

Screenshot taken from https://hosted.weblate.org/translate/weblate/application/fr/?checksum=93eef59d8956dd52#nearby

**Comment by sinnnie** [comment]
> Can you please be more specific when this happens? I've just randomly found some strings with non-breakable space and they look correctly:
> 
> ![image](https://private-user-images.githubusercontent.com/212189/296275606-c0692e4a-1a06-4d65-87af-19e8e6e5ccaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzI3MjAsIm5iZiI6MTcwNTA3MjQyMCwicGF0aCI6Ii8yMTIxODkvMjk2Mjc1NjA2LWMwNjkyZTRhLTFhMDYtNGQ2NS04N2FmLTE5ZThlNmU1Y2NhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQxNTEzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzBhNzg0NjNiYTJjYzY3NmQ0ZGUwNjIzNDY3ODM1MmI0ODllZDdiNmViMTY2ZWRlYmU3ZThhY2U4ZDM0YWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-j58_UMNyoHZ6WaIxTFvbpCalg7EuVDu1LDUeEvifvc)
> 
> Screenshot taken from https://hosted.weblate.org/translate/weblate/application/fr/?checksum=93eef59d8956dd52#nearby

![image](https://github.com/WeblateOrg/weblate/assets/22768922/47460330-984b-4850-8f1a-0decac97590e)

Opened the linked project in Chrome 120.0.6099.217, Win 10 22H2, same issue and stays after clearing browser cache.

**Comment by nijel** [comment]
ac012171a910e5c5e552fd0196be744ef49fd98b caused this.
