### ISSUE TITLE
issue: Logo of the company/website in the footer not appear completely

### ISSUE THREAD

**Issue by Immortal-codes** [WeblateOrg/weblate#10769]
### Describe the problem

The logo of the website/company in the footer section does not appear properly

you can see the image below:- 

![Logo](https://github.com/WeblateOrg/weblate/assets/82056580/bb990b09-2f82-4a86-bc04-8ab791947b6b)

### Describe the solution you would like

It can be solved by adjusting the element of the Footer.

**Comment by nijel** [comment]
That was intentional part of the design but apparently it annoys a lot of people...

**Comment by Immortal-codes** [comment]
Can anyone help me set locally this project, or give me direction on where I do this, i am confused about the documentation provided is for locally setup or for using weblate

just provide me documentation link so i can read and setup locally.
