### ISSUE TITLE
Gettext line wrapping broken immediately after merging a PR made by weblate

### ISSUE THREAD

**Issue by hhyyrylainen** [WeblateOrg/weblate#10763]
### Describe the issue

I just merged a PR from weblate https://github.com/Revolutionary-Games/Thrive/pull/4778 (I had checked on weblate beforehand that there were 0 pending changes to be committed) and weblate decided to immediately open a new PR that again has broken gettext line changes. This seems kind of a new problem after this other issue I had with the line wrapping was fixed: https://github.com/WeblateOrg/weblate/issues/10392 (or maybe I just didn't notice this before due to that more visible issue). Edit: could this be caused by the translation cleanup plugin, which presumably runs immediately when new remote code hook is detected by weblate?

Edit: forgot to show the PR that weblate immediately opened: https://github.com/Revolutionary-Games/Thrive/pull/4798

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Check on weblate admin UI that all changes of a project are committed (though I didn't cause a new push, the weblate PR was not up to date with master at the time of merging)
2. Merge the PR from weblate
3. Weblate immediately makes a new PR where it messes up 2 of the 3 changed languages line changes

### Expected behavior

As always, I expect the gettext line wrapping customization plugin to always work.

### How do you run Weblate?

PyPI module

### Weblate versions

 * Weblate: 5.3.1
 * Django: 4.2.9
 * siphashc: 2.3
 * translate-toolkit: 3.11.1
 * lxml: 4.9.4
 * Pillow: 10.1.0
 * nh3: 0.2.15
 * python-dateutil: 2.8.2
 * social-auth-core: 4.5.1
 * social-auth-app-django: 5.4.0
 * django-crispy-forms: 2.1
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.5
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.13.1
 * rapidfuzz: 3.5.2
 * openpyxl: 3.1.2
 * celery: 5.3.6
 * django-celery-beat: 2.5.0
 * kombu: 5.3.4
 * translation-finder: 2.16
 * weblate-language-data: 2023.9
 * html2text: 2020.1.16
 * pycairo: 1.25.1
 * PyGObject: 3.46.0
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.4.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.39.1
 * Cython: 3.0.7
 * misaka: 2.1.1
 * GitPython: 3.1.40
 * borgbackup: 1.2.7
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.20.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * Python: 3.12.1
 * Git: 2.43.0
 * psycopg: 3.1.16
 * psycopg-binary: 3.1.16
 * phply: 1.2.6
 * ruamel.yaml: 0.18.5
 * tesserocr: 2.6.2
 * boto3: 1.34.11
 * aeidon: 1.13
 * iniparse: 0.5
 * Mercurial: 6.6.1
 * git-svn: 2.43.0
 * PostgreSQL server: 15.4
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.revolutionarygamesstudio.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 6.6.8-200.fc39.x86_64 (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

WARNINGS:
?: (weblate.W033.Gerrit) Failure in loading VCS module for Gerrit: Traceback (most recent call last):
  File "/home/weblate/weblate-env/bin/git-review", line 5, in <module>
    from git_review.cmd import main
  File "/home/weblate/weblate-env/lib/python3.12/site-packages/git_review/cmd.py", line 34, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
 (1)
        HINT: https://docs.weblate.org/en/weblate-5.3.1/vcs.html

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#collecting-errors

System check identified 2 issues (1 silenced).
```

### Additional context

This might be caused by the gettext cleanup plugin I installed as suggested for the issue I was having with old translations sticking around. I just tried reinstalling the gettext line wrap plugin in case it somehow was again broken (I'll know in about a week if that did anything or not).

**Comment by nijel** [comment]
https://github.com/WeblateOrg/weblate/issues/10392 was fixed in translate-toolkit 3.12 which you don't have installed, can you try upgrading it?

**Comment by hhyyrylainen** [comment]
So Weblate doesn't require the newest translate-toolkit version, but I should be able to upgrade that pip package separately? I'll try that.

**Comment by nijel** [comment]
Yes, that should be safe for 3.12. I've adjusted the milestone of https://github.com/WeblateOrg/weblate/issues/10392 to correctly show where the fix will actually land (we had to shuffle the release schedule a bit and some Weblate was released earlier than translate-toolkit).

PS: Can you please grant me admin permissions on https://translate.revolutionarygamesstudio.com/projects/thrive/ so that I can check (and replicate) project configuration? I'm registered as `nijel` there as well.

**Comment by nijel** [comment]
Is there something else besides Weblate code touching the Weblate repository? For example, there could be some Git repository hooks installed. Looking at the changes, there are ones which I cannot explain by Weblate configuration you have.

An example is location change in the translation files:

![image](https://github.com/WeblateOrg/weblate/assets/212189/fb003c03-a6ad-4864-a01c-f5e83772b7af)

* Weblate doesn't update these automatically.
* The `msgmerge` add-on could do that, but you don't have installed. 
* The other option would be that the cleanup add-on mistakenly removed the string and Weblate added it back, but it would lose the translation during this, what didn't happen.
* User replaced the file via upload, but that should be visible in the history.

So, eventually, I'm pretty sure this comes from `msgmerge` being invoked on the file without `--no-wrap`. The only question is who does that and why we can't see that in the history.

**Comment by hhyyrylainen** [comment]
I mean there shouldn't be anything intentionally running on the server that modifies the weblate local repository. I did try to clean diverged history by deleting and recreating the repository months ago, but I think I maybe undid that as that broke way more things than it fixed (I made a folder backup that I think I restored). 

I haven't done any configuration or anything like that manually on the weblate git repository. I'm not fully sure how to check if there's any hooks or anything like that but I see only `.sample` files in the `/home/weblate/weblate/data/vcs/thrive/thrive-game/.git/hooks` folder so there perhaps aren't any hooks.

**Comment by nijel** [comment]
Okay, I think I located the issues:

1. The logic in generating `msgmerge` arguments is flawed, the configuration will store `77` as a string, and it compares it as an integer. #10765 fixes that.
2. The upload together with the cleanup add-on might cause missed parsing of the upload in Weblate. That's why we don't see it in the history and you didn't see pending changes. #10768 fixes that.

**Comment by hhyyrylainen** [comment]
Thank you for the very fast response to this issue. I'll keep an eye out and update to Weblate 5.4 as soon as it becomes available.
