### ISSUE TITLE
Fixup breaks XML syntax

### ISSUE THREAD

**Issue by roptat** [WeblateOrg/weblate#10779]
### Describe the issue

When translating an XML file to French, and it contains an XML entity, punctuation spacing fixup automatically applies and breaks XML syntax. For instance, adding an "`&nbsp;`" to properly implement spacing (as in "`et voilà&nbsp;: c'est fait`" is automatically "fixed" to "`et voilà&nbsp ;: c'est fait`", and I get the XML formatting error with no possibility to disable this, except on a case-by-case basis, using `ignore-punctuation-spacing` flag.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Translate an XML text with weblate to French
2. Use `&nbsp;` or other entities in your translation
3. Submit it
4. The translation is not valid XML

### Expected behavior

The fixup should not apply to XML entities, or there should be a way to disable fixups globally.

### How do you run Weblate?

PyPI module

### Weblate versions

 * Weblate: 5.3.1
 * Django: 4.2.3
 * siphashc: 2.1
 * translate-toolkit: 3.11.1
 * lxml: 4.9.2
 * Pillow: 10.1.0
 * nh3: 0.2.14
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 2.0
 * oauthlib: 3.2.2
 * django-compressor: 4.3.1
 * djangorestframework: 3.14.0
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.12.2
 * rapidfuzz: 2.13.7
 * openpyxl: 3.1.1
 * celery: 5.3.6
 * django-celery-beat: 2.5.0
 * kombu: 5.3.5
 * translation-finder: 2.15
 * weblate-language-data: 2023.3
 * html2text: 2020.1.16
 * pycairo: 1.23.0
 * PyGObject: 3.42.2
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.2.0
 * hiredis: 2.2.2
 * sentry-sdk: 1.31.0
 * Cython: 0.29.33
 * misaka: 2.1.1
 * GitPython: 3.1.31
 * borgbackup: 1.2.6
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.17.1
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.0.1
 * Python: 3.10.12
 * Git: 2.34.1
 * phply: 1.2.6
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.6.1
 * boto3: 1.26.83
 * zeep: 4.2.1
 * aeidon: 1.12
 * iniparse: 0.5
 * Mercurial: 6.3.3
 * git-svn: 2.34.1
 * git-review: 2.3.1
 * PostgreSQL server: 14.10
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg2
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 5.15.0-1035-oracle (aarch64)

### Weblate deploy checks

```shell
System check identified some issues:

WARNINGS:
?: (weblate.W039.AlibabaTranslation) Error importing module 'weblate.machinery.alibaba' in WEBLATE_MACHINERY: No module named 'aliyunsdkalimt'
	HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/machine.html
?: (weblate.W039.OpenAITranslation) Error importing module 'weblate.machinery.openai' in WEBLATE_MACHINERY: No module named 'openai'
	HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/machine.html

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/backup.html

System check identified 4 issues (1 silenced).
```

**Comment by nijel** [comment]
31040bd26478d8fb9ac1c49a9a1ae2dddc1fe406 should already address this.
