### ISSUE TITLE
Editing a glossary apparently causes spurious contributions to be registered

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#10778]
### Describe the issue

Looking at my user profile on TDF Weblate, I seem to have contributions to glossaries of all kinds of languages I don't understand and have never knowingly contributed to.

Also, the Finnish language on TDF Weblate claims several contributors that to my knowledge have never contributed to the Finnish translations.

My guess as to why this happens is that editing a glossary in some way (adding entries? modifying entries? deleting entries?) causes contributions to be counted for all languages that get updated as part of the edit.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Profile: https://translations.documentfoundation.org/user/tjhietala/contributions/

Language contributors: https://translations.documentfoundation.org/user/?q=translates:fi

### Expected behavior

Only actual contributions are counted in the user profile and language page.

### How do you run Weblate?

Other

### Weblate versions

TDF Weblate 5.1.1

**Comment by nijel** [comment]
This is caused by adding terminology entries which are added to all languages.

**Comment by tjhietala** [comment]
> This is caused by adding terminology entries which are added to all languages.

I don't think it's just that. IIRC I have never checked the "Terminology" box when adding glossary entries, yet I still have "contributions" to lots of glossaries in various languages.

I have deleted entries that someone else added, though. AFAIK deleting them from one language doesn't delete them from other languages, but I guess there's some bug that causes deletions to be counted as contributions, anyway.

**Comment by tjhietala** [comment]
This issue also happens on TDF Weblate 5.3.1

**Comment by nijel** [comment]
Okay, it's not a terminology, but an explicit commit: https://translations.documentfoundation.org/changes/browse/android-viewer/glossary/el/?user=tjhietala
