### ISSUE TITLE
Not recognized placeables if & is used

### ISSUE THREAD

**Issue by strepon** [WeblateOrg/weblate#10781]
### Describe the issue

If there is `&` character in a source string, placeables used in the string (as XML tags) are not recognized and cannot be copied from the source to the translation.

### I already tried

- [x] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

See e.g. this string at The Document Foundation's instance:  https://translations.documentfoundation.org/translate/libo_help-master/textscalcguide/cs/?checksum=4a46884ecf40e776

### Expected behavior

`<emph>` tags should be recognized as placeables.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/9050387/fcaa907b-9d04-4c3c-80af-30e16a9cf20e)

### How do you run Weblate?

Other

### Weblate versions

5.1.1

**Comment by nijel** [comment]
You're right, Weblate doesn't find XML markup in a string which is not a valid XML.
