### ISSUE TITLE
SYSTRAN machine translation

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#10799]
### Describe the problem

Add support for SYSTRAN machine translation service.

### Describe the solution you would like

New machinery backend for SYSTRAN.

### Additional context

See https://docs.systran.net/translateAPI/translation/ for API documentation.

**Comment by fondbcn** [comment]
Hello,
I want to help in this project, but I have trouble with api key.

**Comment by nijel** [comment]
AFAIK you cat get one there for free with some limits on number of translated characters.

**Comment by fondbcn** [comment]
`from .base import MachineTranslation, MachineTranslationError
from .forms import KeyMachineryForm


class SystranTranslation(MachineTranslation):
    """Systran machine translation support."""

    name = "Systran"
    max_score = 90
    settings_form = SystranMachineryForm

    def check_failure(self, response):
        if "code" not in response or response["code"] == 200:
            return
        if "message" in response:
            raise MachineTranslationError(response["message"])
        raise MachineTranslationError("Error: {}".format(response["code"]))

    def download_languages(self):
        """Download list of supported languages from a service."""
        response = self.request(
            "get",
            "/translation/supportedLanguages",
            params={"key": self.settings["key"]},
        )
        payload = response.json()
        self.check_failure(payload)
        return payload["langs"].keys()

    def download_translations(
        self,
        source,
        language,
        text: str,
        unit,
        user,
        threshold: int = 75,
    ):
        """Download list of possible translations from a service."""
        response = self.request(
            "post",
            "/translation/text/translate",
            params={
                "key": self.settings["key"],
                "source": source",
                "target": language,
                "input": text,
            },
        )
        payload = response.json()

        self.check_failure(payload)

        for translation in payload["outputs"]:
            yield {
                "text": translation,
                "quality": self.max_score,
                "service": self.name,
                "source": text,
            }

    def get_error_message(self, exc):
        try:
            return exc.response.json()["message"]
        except Exception:
            return super().get_error_message(exc)`

Sorry about my programming level;
1- I didn't understand how to integrate the api endpoint (I can't find it) ?
2- is this code the right way to add Systran api ?

**Comment by nijel** [comment]
Yes, `download_languages` and `download_translations` is what is needed at least. If there is some specific way to get a better error message, and detect error response, `check_failure` and `get_error_message` are useful as well.

**Comment by fondbcn** [comment]
> Yes, `download_languages` and `download_translations` is what is needed at least. If there is some specific way to get a better error message, and detect error response, `check_failure` and `get_error_message` are useful as well.

I want to test the code but the endpoint is missing here `"post",   "???/translation/text/translate",`

**Comment by nijel** [comment]
It should be `https://api-translate.systran.net/`, see https://docs.systran.net/translateAPI/en/.

**Comment by fondbcn** [comment]
sorry,
I tried for many days to resolve the issue of working with weblate,but it always fails (failed to lock dependencies), so i cant test the code or migrate at least !
note that the problem is with weblate only

**Comment by nijel** [comment]
What kind of error do you get?

**Comment by fondbcn** [comment]
> What kind of error do you get?

It wont install the requirements of weblate (manually  nor with setup) !

**Comment by nijel** [comment]
Yes, you need pkg-config to build some dependencies, and it can be installed on Windows. In https://github.com/WeblateOrg/weblate/discussions/5844#discussioncomment-7750282 somebody suggests using WSL. Please follow up there, or start a separate discussion, as we're getting off-topic in this issue.

**Comment by fondbcn** [comment]
> https://api-translate.systran.net/

sorry for getting out of topic.
using systran api endoint directly doesn't seem the right way, instead they say (on docs video) https://"yourServerGateway":8903/ but I dont know how to do it like that !
https://www.youtube.com/watch?v=QILC9eOCjDw&t=569s

**Comment by nijel** [comment]
You can get an API key from https://translate.systran.net/en/account upon registering. Following then works:

```sh
curl --data input=hello --data source=en --data target=cs  --header 'Authorization: Key YOUR-API-KEY' https://api-translate.systran.net/translation/text/translate
```

**Comment by fondbcn** [comment]
how can I test only the model I added (systran) bcz the test is too long ?

**Comment by nijel** [comment]
You can run only part of the test suite, for example:

```
DJANGO_SETTINGS_MODULE=weblate.settings_test ./manage.py test weblate.machinery
```

See also https://docs.weblate.org/en/latest/contributing/tests.html and https://docs.djangoproject.com/en/5.0/topics/testing/overview/#running-tests
