### ISSUE TITLE
Newline handling from XLIFF

### ISSUE THREAD

**Issue by wirthandras** [WeblateOrg/weblate#10811]
### Describe the issue

The weblate user is created some translations with newline characters (the newline control character was selected in weblate interface)

![image](https://github.com/WeblateOrg/weblate/assets/12913003/addafe73-65f2-496b-8532-c3773c4efe0d)

![image](https://github.com/WeblateOrg/weblate/assets/12913003/f915aa7b-df05-4e9e-a281-ed03d331aace)

This text was serialized into git repository without problems, the newline characters are exist in XLIFF 1.2 files.

But the next weblate syncronization (I mean import a new group of text via rest api by setting the source branch) removed the existing newlines from text:

![image](https://github.com/WeblateOrg/weblate/assets/12913003/48c53acd-f500-45fa-9f90-172525fe42e2)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Single line text added to weblate as source text from XLIFF 1.2 source file from GIT feature branch
The translator give a more detailed text with some newline characters
Localizations are synchronized into git origin with push branch (and merged with master branch)
A new source branch is created from master (including some new texts which are not really relevant here) and set that branch into weblate as source branch via REST API.

### Expected behavior

Keep newlines which inserted by weblate tools

### Screenshots

The automatic feedback in insights related to component:
![image](https://github.com/WeblateOrg/weblate/assets/12913003/b22b9c90-cec9-464e-8478-c0fc9ddca66d)

### How do you run Weblate?

Docker container

### Weblate versions

5.2.1

### Additional context

No django settings modified

**Comment by nijel** [comment]
Can you please share a snippet of your XLIFF file before and after Weblate edit? My guess is that the element didn't have `xml:space="preserve"` and translate-toolkit (library we use for manipulating the files) did not add it when changing the string.

**Comment by wirthandras** [comment]
Yeah, i can confirm there is no xml:space="preserve"

```xml
<trans-unit id="8864d0bd25f99594bbfb59780cb19a091946d8e6" datatype="html">
        <source>Status: You have started the form but it is not completed. Please select the continue button below to resume the form process. Please have the following documents available: • INE (Credencial para votar) o pasaporte, vigentes • Carátula del estado de cuenta bancario personal • Cuenta CLABE Bancaria • Constancia de Situación Fiscal con el Régimen de Sueldos y Salarios e Ingresos Asimilados a Salarios, con una vigencia no mayor a 90 días, completa, en FORMATO PDF</source>
        <target state="translated">Estado actual:
Empezaste el proceso en pero no lo has completado.
Por favor, selecciona el botón “continuar” de abajo para continuar el proceso en.

Por favor, ten a la mano los siguientes documentos para completar el proceso:
• INE (Credencial para votar) o pasaporte, vigentes
• Carátula del estado de cuenta bancario personal
• Cuenta CLABE Bancaria
• Constancia de Situación Fiscal con el Régimen de Sueldos y Salarios e Ingresos Asimilados a Salarios, con una vigencia no mayor a 90 días, completa, en FORMATO PDF</target>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/settings/component/profile/example/example.component.html</context>
          <context context-type="linenumber">3</context>
        </context-group>
        <note priority="1" from="description">settings</note>
      </trans-unit>
```

**Comment by nijel** [comment]
The `xml:space="preserve"` is properly added upon editing the file, I've just added tests for this in https://github.com/translate/translate/pull/5168.

Is there something else changing the XLIFF files? Maybe it is removing it?

**Comment by wirthandras** [comment]
@nijel Hi I have made a test run related to this topic, I have added a ```xml:space="preserve"``` as you mentioned before into the input xliff file:
```xliff
<trans-unit id="3330244922547581181" datatype="html">
        <source  xml:space="preserve">Hello World3 test ride</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">13</context>
        </context-group>
      </trans-unit>
```

after text change in weblate (commit, push) this is the result:
```xliff
<trans-unit id="3330244922547581181" datatype="html">
        <source xml:space="preserve">Hello World3 test ride

bla bla

bla blaline2</source>
        <target state="translated">Hello World3 test ride

bla bla SP

bla blaline2 SP</target>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">13</context>
        </context-group>
      </trans-unit>
```

it seems to me the target tag has not marked with the similar ```xml:space="preserve"``` attribute

This could be an open question, but unfortunatly that does not solve my problem, since we are using Angular and [I18n ] extractor (https://angular.io/cli/extract-i18n) to generate input files for weblate, and it seems to this extractor does not provide this attribute. (i see some reference, but does not work as expected for this situation)

Thanks for help, I need to thinking about other solution
