### ISSUE TITLE
Plus icon disappears from Language - need to add languages to Project 

### ISSUE THREAD

**Issue by isolda488** [WeblateOrg/weblate#10814]
### Describe the issue

![AddLanguage](https://github.com/WeblateOrg/weblate/assets/116044237/f8f66d71-cf7a-4aa4-b1cc-b3e2676c5aa0)
Previously added languages to project with the plus button on the language tab under project.   It's disappeared.  There is no help file to just add language to project.  

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Project - choose project name.   Language tab ------  how to add a language to existing project 

### Expected behavior

The plus button to add language.  Like the one to add components.  

### Screenshots

![AddLanguage](https://github.com/WeblateOrg/weblate/assets/116044237/934f870a-3ecf-4707-a568-e1af9104abc7)

### How do you run Weblate?

weblate.org service

### Weblate versions

5

**Comment by nijel** [comment]
Duplicate of #6094
