### ISSUE TITLE
Not localized text when not logged in

### ISSUE THREAD

**Issue by Blueberryy** [WeblateOrg/weblate#10843]
### Describe the issue

![image](https://github.com/WeblateOrg/weblate/assets/36592509/b40670d2-4bb2-48b5-8067-c6d99338176c)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Unlogin from your Weblate account on Hosted website.
2. Open mail with changed translation and click Edit string.
3. You will see this red text

**Comment by nijel** [comment]
This is recently added text which hasn't been yet translated.
