### ISSUE TITLE
Unclear error message on replacing source language's translation file through API

### ISSUE THREAD

**Issue by exhilaratedguy** [WeblateOrg/weblate#10841]
### Describe the issue

Using Weblate v4.17, I am trying to fully replace the translation file for the source language of my translation component through Weblate's API. This works fine for other languages, but errors out for the source language with the error message "You can not overwrite existing approved translations".

I'm confused as to why this is the case through the API, since uploading a file through the web portal with "Replace existing translation file" works without a hitch.

For reference, here is a code snippet of the request:

```
axios({
    url: `${process.env.REACT_APP_WEBLATE_URL}api/translations/${process.env.REACT_APP_WEBLATE_PATH}${language}/file/`,
    method: "POST",
    data: {
      file: fs.createReadStream(filePath),
      email: "my@email.com",
      author: "Author name",
      conflicts: "replace-approved",
      method: "replace",
    },
    headers: {
      "Content-Type": "multipart/form-data",
      Authorization: `Token ${process.env.REACT_APP_WEBLATE_TOKEN}`,
    },
  })
```

I have searched extensively on the docs, google and the issues on GitHub, but found no mentions about this issue.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Add a new translation component
2. Make a POST request to `/api/translations/(string: project)/(string: component)/(string: language)/file/` for the source language
3. Error - "You can not overwrite existing approved translations"

### Expected behavior

Translation file successfully replace

### How do you run Weblate?

Other

**Comment by nijel** [comment]
Most likely source strings review are not enabled and thus approved state is not applicable. The error message could be definitely more clear in this case.

**Comment by exhilaratedguy** [comment]
@nijel Thanks for the quick reply. Can you point me to the right screen to update the necessary permissions for this?
