### ISSUE TITLE
Define source language file for bilingual translation files

### ISSUE THREAD

**Issue by schfab** [WeblateOrg/weblate#10842]
### Describe the problem

I have a Qt Project which is using bilingual translation files (.ts) from Qt Linguist and I would like to be able to translate English as well.
My setups is that I am using English (Developer) as source language and I am providing a ts file for English as well.
It gives me the following setup in weblate:
![image](https://github.com/WeblateOrg/weblate/assets/29098979/fd415fe4-0fbc-4d41-b5fe-a910a65a24fb)
English (Developer) is read-only and contains the strings from the source code which is correct for me.
English is editable and I can change the English strings used in the source code which is fine.
All other languages are editable as well with English (Developer) as source language.
I already tried to use my English .ts file as editable monolingual base file. If I do so, English (Developer) is the only editable language. All other languages are marked as finished and read-only.

### Describe the solution you would like

The only problem I have is that for every other language English (Developer) is taken as source but I would like to have English as source with the edited English translations.
So, English (Developer) should be the source for English but English should be the source for the other languages.
Is this somehow possible?

**Comment by nijel** [comment]
Bilingual translations always display as a source what is present in the bilingual file, so define that as a source language. So having *English (Developer)* as a source language and then *English* as a translation is the correct approach. Users can configure *English* as a secondary language to see it next to the original string (see https://docs.weblate.org/en/latest/user/profile.html#secondary-languages).

For monolingual translations, Weblate has workflow for review of the source strings, see https://docs.weblate.org/en/latest/workflows.html#quality-gateway-for-the-source-strings

**Comment by schfab** [comment]
I was not aware about defining English as a secondary language and it is indeed a big help. Thank you.
The only issue I have now is that automatic suggestions of deepl are still using English (Developer) as source language instead of English.

**Comment by nijel** [comment]
This can be currently only addressed in monolingual files and https://docs.weblate.org/en/latest/workflows.html#quality-gateway-for-the-source-strings.

For bilingual files, this would be tricky because the strings are not identified by ID (as in monolingual setup), but by the source string.
