### ISSUE TITLE
Incorrect string value

### ISSUE THREAD

**Issue by Justman100** [WeblateOrg/weblate#10879]
### Describe the issue

Get this:

> django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xCA\\xBCin' for column `Weblate`.`lang_language`.`name` at row 1")

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

```
git init
git pull https://github.com/WeblateOrg/weblate
virtualenv .
source bin/activate
# Config edited
weblate migrate
```

### Expected behavior

Bugless migration

### How do you run Weblate?

Git checkout

### Weblate versions

* Weblate: bc2949b0df
* Django: 4.2.9
* siphashc: 2.3
* translate-toolkit: 3.12.1
* lxml: 5.1.0
* pillow: 10.2.0
* nh3: 0.2.15
* python-dateutil: 2.8.2
* social-auth-core: 4.5.1
* social-auth-app-django: 5.4.0
* django-crispy-forms: 2.1
* oauthlib: 3.2.2
* django-compressor: 4.4
* djangorestframework: 3.14.0
* django-filter: 23.5
* django-appconf: 1.0.6
* user-agents: 2.2.0
* filelock: 3.13.1
* rapidfuzz: 3.6.1
* openpyxl: 3.1.2
* celery: 5.3.6
* django-celery-beat: 2.5.0
* kombu: 5.3.5
* translation-finder: 2.16
* weblate-language-data: 2024.1
* html2text: 2020.1.16
* pycairo: 1.25.1
* PyGObject: 3.46.0
* diff-match-patch: 20230430
* requests: 2.31.0
* django-redis: 5.4.0
* hiredis: 2.3.2
* sentry-sdk: 1.39.2
* Cython: 3.0.8
* misaka: 2.1.1
* GitPython: 3.1.41
* borgbackup: 1.2.7
* pyparsing: 3.1.1
* ahocorasick_rs: 0.22.0
* python-redis-lock: 4.0.0
* charset-normalizer: 3.3.2
* Python: 3.11.7
* Git: 2.43.0
* phply: 1.2.6
* ruamel.yaml: 0.18.5
* tesserocr: 2.6.2
* boto3: 1.34.26
* aeidon: 1.13
* iniparse: 0.5
* mysqlclient: 2.2.1
* MariaDB sever: 11.4.0
* Database backends: django.db.backends.mysql
* Cache backends: default:RedisCache, avatar:FileBasedCache
* Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
* OS encoding: filesystem=utf-8, default=utf-8
* Celery: redis://localhost:6379, redis://localhost:6379, regular
* Platform: Linux 5.10.0-14-amd64 (x86_64)

### Weblate deploy checks

```shell
ERRORS:
(weblate.E011) E-mail addresses for site admins is misconfigured
	HINT: https://docs.weblate.org/en/latest/admin/install.html#production-admins[0m

WARNINGS:
(weblate.W033.Gerrit) Failure in loading VCS module for Gerrit: git: 'review' is not a git command. See 'git --help'.
 (1)
	HINT: https://docs.weblate.org/en/latest/vcs.html[0m
(weblate.W033.Mercurial) Failure in loading VCS module for Mercurial: [Errno 2] No such file or directory: 'hg'
	HINT: https://docs.weblate.org/en/latest/vcs.html[0m
(weblate.W033.Subversion) Failure in loading VCS module for Subversion: git: 'svn' is not a git command. See 'git --help'.

The most similar commands are
	fsck
	mv
	show
 (1)
	HINT: https://docs.weblate.org/en/latest/vcs.html[0m
(weblate.W039.AlibabaTranslation) Error importing module 'weblate.machinery.alibaba' in WEBLATE_MACHINERY: No module named 'aliyunsdkalimt'
	HINT: https://docs.weblate.org/en/latest/admin/machine.html[0m
(weblate.W039.GoogleV3Translation) Error importing module 'weblate.machinery.googlev3' in WEBLATE_MACHINERY: No module named 'google'
	HINT: https://docs.weblate.org/en/latest/admin/machine.html[0m

INFOS:
(weblate.E006) Weblate performs best with PostgreSQL, consider migrating to it.
	HINT: https://docs.weblate.org/en/latest/admin/install.html#production-database[0m
(weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/latest/admin/install.html#collecting-errors[0m
(weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/latest/admin/backup.html[0m

System check identified 9 issues (1 silenced).
```

**Comment by nijel** [comment]
What encoding is configured on the database server? Please see the documentation for correct MySQL/MariaDB setup (even if it is discouraged).

**Comment by Justman100** [comment]
Using simply PostgreSQL 😉

**Comment by nijel** [comment]
The initial post states something else:

> Database backends: django.db.backends.mysql

**Comment by Justman100** [comment]
> The initial post states something else:
> 
> > Database backends: django.db.backends.mysql

Yeah... Now uses PostgreSQL 🙂
