### ISSUE TITLE
Posix lowercase is not avaiable for Chinese

### ISSUE THREAD

**Issue by ZiYueCommentary** [WeblateOrg/weblate#10878]
### Describe the issue

As #9377 described, Posix lowercase is the format that Minecraft uses.

According to the source code, this function was implemented by lower the code from `EXPAND_LANGS`. But zh_cn, zh_tw, etc are not included in it, they are included in `LEGACY_CODES`, so they are ignored. For example, Chinese Simplified is `zh_hans` instead of `zh_cn`.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Set Language code style as "POSIX style using underscore as a separator, including country code (lowercase)".
2. Add Chinese Simplified or Chinese Traditional for the component.

### Expected behavior

The file name of Chinese Simplified should be `zh_cn`, Chinese Traditional should be `zh_tw`, and so on.

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
Yes, POSIX uses codes like `zh_Hant`, Linux translates it to `zh_TW`. So, maybe you actually need Linux lowercase?
