### ISSUE TITLE
Weblate refuses to accept self-signed certs for SMTP.

### ISSUE THREAD

**Issue by Jamie-TinyPixel** [WeblateOrg/weblate#10889]
### Describe the issue

I have an SMTP server running on `smtp.<mydomain.com>`, with just a self-signed certificate setup, and I simply want to tell the Weblate docker container to accept the self-signed certificate, and I have placed it inside the docker container, by mounting it as a volume.

The error I keep getting is 
```
Could not send test e-mail: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)
```

`docker-compose.override.yml`
```
version: '3'
services:
  weblate:
    ports:
      - 8081:8080
    environment:
      EMAIL_SSL_CERTFILE: /usr/local/share/ca-certificates/certificate.pem
      EMAIL_USE_SSL: 1
      EMAIL_USE_TLS: 0
      WEBLATE_EMAIL_HOST: smtp.<mydomain.com>
      WEBLATE_EMAIL_PORT: 587
      WEBLATE_EMAIL_HOST_USER: ****
      WEBLATE_EMAIL_HOST_PASSWORD: ****
      WEBLATE_SERVER_EMAIL: no-reply@<mydomain.com>
      WEBLATE_DEFAULT_FROM_EMAIL: no-reply@<mydomain.com>
      WEBLATE_SITE_DOMAIN: weblate.<mydomain.com>
      WEBLATE_ADMIN_PASSWORD: ****
      WEBLATE_ADMIN_EMAIL: ****@<mydomain.com>
    volumes:
      - /usr/local/share/ca-certificates/certificate.pem:/usr/local/share/ca-certificates/certificate.pem
```
Any help is appreciated.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Make sure the cert on your SMTP server is self-signed
2. Attempt to allow Weblate to accept the self-signed cert
3. Attempt to send an email through said SMTP server
4. See issue

### Expected behavior

The Weblate server should have something like a warning telling me that I'm allowing a self-signed certificate, but otherwise contine functioning with it.

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.3.1
 * Django: 4.2.8
 * siphashc: 2.3
 * translate-toolkit: 3.11.1
 * lxml: 4.9.3
 * Pillow: 10.1.0
 * nh3: 0.2.15
 * python-dateutil: 2.8.2
 * social-auth-core: 4.5.1
 * social-auth-app-django: 5.4.0
 * django-crispy-forms: 2.1
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.5
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.13.1
 * rapidfuzz: 3.5.2
 * openpyxl: 3.1.2
 * celery: 5.3.6
 * django-celery-beat: 2.5.0
 * kombu: 5.3.4
 * translation-finder: 2.15
 * weblate-language-data: 2023.9
 * html2text: 2020.1.16
 * pycairo: 1.25.1
 * PyGObject: 3.46.0
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.4.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.39.1
 * Cython: 3.0.6
 * misaka: 2.1.1
 * GitPython: 3.1.40
 * borgbackup: 1.2.7
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.20.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * Python: 3.11.7
 * Git: 2.39.2
 * psycopg: 3.1.16
 * psycopg-binary: 3.1.16
 * phply: 1.2.6
 * ruamel.yaml: 0.18.5
 * tesserocr: 2.6.2
 * boto3: 1.34.3
 * zeep: 4.2.1
 * aeidon: 1.13
 * iniparse: 0.5
 * mysqlclient: 2.2.1
 * Mercurial: 6.6.1
 * git-svn: 2.39.2
 * git-review: 2.3.1
 * PostgreSQL server: 16.1
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.tinypixel.uk
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.15.131-1-pve (x86_64)

### Weblate deploy checks

```shell
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)), please check EMAIL_* settings.
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#out-mail
?: (weblate.E027) The path /app/data/static is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/static/__init__.py is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/static/admin.py is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/static/apps.py is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/static/migrations is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/static/migrations/__init__.py is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/static/models.py is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/static/static is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/static/static/email-logo.png is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/static/static/favicon.ico is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/static/static/icons is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/static/static/icons/weblate.svg is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/static/static/logo-512.png is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/static/tests.py is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/static/views.py is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#file-permissions

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/backup.html

System check identified 21 issues (1 silenced).
```

### Additional context

I am aware of the various errors and warnings provided, I have recently set up this server, and it is nowhere near prod ready

I have also tried both this port with SSL and port 25 with no SSL or TLS.

**Comment by nijel** [comment]
Do not use SSL with a non-trusted certificate, it adds almost no security compared to the plain text. See also https://stackoverflow.com/a/77817326/225718

**Comment by Jamie-TinyPixel** [comment]
Sorry, I've forgotten to mention I have also tried no SSL, using port 25. Again, incredibly sorry for not mentioning that, updating extra context now.

**Comment by nijel** [comment]
Using insecure SSL is not supported by Django (see the link I've posted before) and thus it is not supported by Weblate either. If you insist on insecure setup, allow non-TLS connection on your e-mail server and disable SSL/TLS in Weblate.

**Comment by Jamie-TinyPixel** [comment]
Right, however I have already tried using port 25- and it is enabled- I was simply testing if _for some odd reason_, any other ports would work- be it TLS and/or SSL on. Is there just no hope to use a self-signed CA with Django?

**Comment by nijel** [comment]
It needs patching, see the link I posted before.

**Comment by Jamie-TinyPixel** [comment]
Ahh right- sorry- I completely misunderstood your comment then. Thanks a lot- I'll look into it
