### ISSUE TITLE
'Remove blank strings' addon does not remove plurals in Android files

### ISSUE THREAD

**Issue by emmapeel2** [WeblateOrg/weblate#10887]
### Describe the issue

On our component of type Android string resource https://hosted.weblate.org/projects/onionshare/onionshare-android/ we are having issues with the plurals.

We have the add-on 'Remove blank strings' installed, and it removes the untranslated strings well, except on the plurals.

It seems weblate does not close the xml tag neither

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

You can see how weblate pushed a branch with blank strings  that is also missing the xml close tag at https://github.com/onionshare/onionshare-android/commit/627ce6275f387e4cde40da813923e8ce273c526a#diff-96cbab6d6c22855d341211d7bcbbed33456020f2d8ad707a1fb3905cc35e5dff

### Expected behavior

On the link https://github.com/onionshare/onionshare-android/commit/627ce6275f387e4cde40da813923e8ce273c526a#diff-96cbab6d6c22855d341211d7bcbbed33456020f2d8ad707a1fb3905cc35e5dff , for example for the aymara language, the strings `share_file_list_summary` and `settings_tor_bridges_number` should not appear at all, as they are not translated.

### How do you run Weblate?

weblate.org service

**Comment by grote** [comment]
I guess once 5.4 is out, this fix gets deployed on weblate.org?

**Comment by nijel** [comment]
Yes.
