### ISSUE TITLE
Issues when duplicating a component

### ISSUE THREAD

**Issue by nikclayton** [WeblateOrg/weblate#10896]
### Describe the problem

Creating a component that's a copy of another component feels more difficult than it needs to be.

### Describe the solution you would like

1. It's not obvious that a component can be duplicated. When viewing a component there's no option to duplicate it. You have to create a new component, and choose the option to base the new component on an existing component. This is not discoverable and quite surprising.
2. The new component does not duplicate key settings from the source component. In my testing so far the settings that are not duplicated are at least:
a. The license
b. The contributor agreement text
c. The commit messages

These all have to be manually copied from an existing component to the new component.

I'd make it more obvious that duplication is possible with a copy icon (e.g,. something like https://www.flaticon.com/free-icon/copy_126498?term=copy&page=1&position=2&origin=tag&related_id=126498) next to the existing "browse" icon.

The lack of duplication of the other settings feels like a bug.

**Comment by nijel** [comment]
Indeed, only a few of the settings are currently cloned:

https://github.com/WeblateOrg/weblate/blob/3ce0a3de3269ef72717ba3e7144a22c459d6eb41/weblate/trans/views/create.py#L516-L524

More of them can definitely be added.

**Comment by ParthS007** [comment]
@nijel  I've included the requested information in duplication in #11079. Let me know if there's any other attribute that should be included for duplication.

Regarding the duplication functionality, should we consider showing the duplicate icon from the all components list page of a project? If so, what specific functionalities and attributes should be included in the duplication process?

**Comment by nijel** [comment]
@gersona https://github.com/WeblateOrg/weblate/pull/11079 might be a starting point here.
