### ISSUE TITLE
Key is missing from offline manifest

### ISSUE THREAD

**Issue by Justman100** [WeblateOrg/weblate#10895]
### Describe the issue

Get this

> You have offline compression enabled but key "f266524eae2efc24af5d7ac2262445fc6c499cae4ba49d1ba914a788fdde30b9" is missing from offline manifest. You may need to run "python manage.py compress". Here is the original content:

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

```
git init
git pull
# Edited settings
python manage.py migrate
python manage.py compress
python manage.py compilemessages
python manage.py collectstatic --noinput
python manage.py setuplang
uwsgi --uid 1006 --http :3314 --master --processes 1 --threads 1 --wsgi-file weblate/wsgi.py
```

### How do you run Weblate?

Git checkout

### Weblate versions

* aeidon: 1.13
* ahocorasick_rs: 0.22.0
* borgbackup: 1.2.7
* Cache backends: default:RedisCache, avatar:FileBasedCache
* celery: 5.3.6
* Celery: redis://localhost:6379, redis://localhost:6379, regular
* charset-normalizer: 3.3.2
* Cython: 3.0.8
* Database backends: django.db.backends.postgresql
* diff-match-patch: 20230430
* djangorestframework: 3.14.0
* django-appconf: 1.0.6
* django-celery-beat: 2.5.0
* django-compressor: 4.4
* django-crispy-forms: 2.1
* django-filter: 23.5
* django-redis: 5.4.0
* Django: 4.2.9
* Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
* filelock: 3.13.1
* GitPython: 3.1.41
* Git: 2.43.0
* hiredis: 2.3.2
* html2text: 2020.1.16
* iniparse: 0.5
* kombu: 5.3.5
* lxml: 5.1.0
* misaka: 2.1.1
* nh3: 0.2.15
* oauthlib: 3.2.2
* openpyxl: 3.1.2
* OS encoding: filesystem=utf-8, default=utf-8
* phply: 1.2.6
* pillow: 10.2.0
* Platform: Linux 5.10.0-14-amd64 (x86_64)
* PostgreSQL implementation: psycopg3 (python)
* PostgreSQL server: 16.1
* psycopg: 3.1.17
* pycairo: 1.25.1
* PyGObject: 3.46.0
* pyparsing: 3.1.1
* python-dateutil: 2.8.2
* python-redis-lock: 4.0.0
* Python: 3.11.7
* rapidfuzz: 3.6.1
* requests: 2.31.0
* ruamel.yaml: 0.18.5
* sentry-sdk: 1.39.2
* siphashc: 2.3
* social-auth-app-django: 5.4.0
* social-auth-core: 4.5.2
* tesserocr: 2.6.2
* translate-toolkit: 3.12.1
* translation-finder: 2.16
* user-agents: 2.2.0
* weblate-language-data: 2024.2
* Weblate: ce34b93ff1

### Weblate deploy checks

```shell
SystemCheckError: System check identified some issues:

CRITICALS:
(weblate.E034) The Celery process is outdated or misconfigured. Following items differ: version, mt_services
	HINT: https://docs.weblate.org/en/latest/admin/install.html#celery[0m

ERRORS:
(weblate.E011) E-mail addresses for site admins is misconfigured
	HINT: https://docs.weblate.org/en/latest/admin/install.html#production-admins[0m

WARNINGS:
(security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.[0m
(security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.[0m
(security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.[0m
(weblate.W033.Gerrit) Failure in loading VCS module for Gerrit: git: 'review' is not a git command. See 'git --help'.
 (1)
	HINT: https://docs.weblate.org/en/latest/vcs.html[0m
(weblate.W033.Mercurial) Failure in loading VCS module for Mercurial: [Errno 2] No such file or directory: 'hg'
	HINT: https://docs.weblate.org/en/latest/vcs.html[0m
(weblate.W033.Subversion) Failure in loading VCS module for Subversion: git: 'svn' is not a git command. See 'git --help'.

The most similar commands are
	fsck
	mv
	show
 (1)
	HINT: https://docs.weblate.org/en/latest/vcs.html[0m
(weblate.W039.AWSTranslation) Error importing module 'weblate.machinery.aws' in WEBLATE_MACHINERY: No module named 'boto3'
	HINT: https://docs.weblate.org/en/latest/admin/machine.html[0m
(weblate.W039.AlibabaTranslation) Error importing module 'weblate.machinery.alibaba' in WEBLATE_MACHINERY: No module named 'aliyunsdkalimt'
	HINT: https://docs.weblate.org/en/latest/admin/machine.html[0m
(weblate.W039.GoogleV3Translation) Error importing module 'weblate.machinery.googlev3' in WEBLATE_MACHINERY: No module named 'google'
	HINT: https://docs.weblate.org/en/latest/admin/machine.html[0m
(weblate.W039.OpenAITranslation) Error importing module 'weblate.machinery.openai' in WEBLATE_MACHINERY: No module named 'openai'
	HINT: https://docs.weblate.org/en/latest/admin/machine.html[0m

INFOS:
(weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/latest/admin/install.html#collecting-errors[0m
(weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/latest/admin/backup.html[0m

System check identified 14 issues (1 silenced).
```

**Comment by nijel** [comment]
Does re-running `compress` fix that error?

Turning on COMPRESS_OFFLINE needs correct COMPRESS_OFFLINE_CONTEXT setting as well. How is yours configured?

**Comment by Justman100** [comment]
> Does re-running `compress` fix that error?
> 
> Turning on COMPRESS_OFFLINE needs correct COMPRESS_OFFLINE_CONTEXT setting as well. How is yours configured?

```py
# Django compressor offline mode
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = False
COMPRESS_OFFLINE_CONTEXT = "weblate.utils.compress.offline_context"
COMPRESS_CSS_HASHING_METHOD = "content"
```

**Comment by Justman100** [comment]
> Does re-running `compress` fix that error?
> 
> Turning on COMPRESS_OFFLINE needs correct COMPRESS_OFFLINE_CONTEXT setting as well. How is yours configured?

```py
# Django compressor offline mode
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True
COMPRESS_OFFLINE_CONTEXT = "weblate.utils.compress.offline_context"
COMPRESS_CSS_HASHING_METHOD = "content"
```

**Comment by Justman100** [comment]
@nijel

If I deactivate `COMPRESS_OFFLINE`, it works! But then I get this:

> The resource of "http://<myIP>:3314/static/CACHE/js/output.1ee194e23d1e.js" was blocked due to a MIME type conflict ("text/html") (X-Content-Type-Options: nosniff).
login

> Failed to load <script> with resource "http://<myIP>:3314/static/CACHE/js/output.1ee194e23d1e.js". login:45:61

> The resource of "http://<myIP>:3314/static/CACHE/css/output.ecbf08d50e4e.css" was blocked due to a MIME type conflict ("text/html") (X-Content-Type-Options: nosniff).
login

> The resource of "http://<myIP>:3314/static/CACHE/css/output.b2cdc5489794.css" was blocked due to a MIME type conflict ("text/html") (X-Content-Type-Options: nosniff).
login

> Content-Security-Policy: The settings of the page have blocked the loading of a resource on eval ("script-src"). 3 index.js:21:9

> Content-Security-Policy: The settings of the page have blocked the loading of a resource on eval ("script-src"). 3 index.js:21:9

**Comment by nijel** [comment]
Maybe you didn't restart uwsgi after changing the setting?

**Comment by Justman100** [comment]
> Maybe you didn't restart uwsgi after changing the setting?

The errors occur when `COMPRESS_OFFLINE` is already deactivated!

**Comment by Justman100** [comment]
And I restart after every change

**Comment by Justman100** [comment]
As screen
![grafik](https://github.com/WeblateOrg/weblate/assets/149507651/0d006821-0f09-423a-b24d-6cf11f2c2954)

**Comment by Justman100** [comment]
@nijel

**Comment by nijel** [comment]
Perhaps `/static/` is not served from the correct location by the web server? See https://docs.weblate.org/en/latest/admin/install.html#serving-static-files

**Comment by Justman100** [comment]
> Perhaps /static/ is not served from the correct location by the web server? See https://docs.weblate.org/en/latest/admin/install.html#serving-static-files

I use Caddy... But yes, it's configured
<br>

> PS: No need to ping me, if you are looking for faster support, we have options for you: https://weblate.org/support
With the rip-off prices? Cut all prices by a tenth and we'll get into the realistic range

**Comment by Justman100** [comment]
> Perhaps /static/ is not served from the correct location by the web server? See https://docs.weblate.org/en/latest/admin/install.html#serving-static-files

I use Caddy... But yes, it's configured
<br>

> PS: No need to ping me, if you are looking for faster support, we have options for you: https://weblate.org/support

With the rip-off prices? Cut all prices by a tenth and we'll get into the realistic range

**Comment by Justman100** [comment]
And I run this via [uWSGI itself](https://uwsgi-docs.readthedocs.io/en/latest/WSGIquickstart.html)

**Comment by nijel** [comment]
Is the file present on the filesystem?

**Comment by nijel** [comment]
Any of the ones which cannot be retrieved by the browser in https://github.com/WeblateOrg/weblate/issues/10895#issuecomment-1917259577.

With offline compression disabled, these are generated on the fly, but still saved to the filesystem. I still think they are saved, but your serving of /static is misconfigured.

**Comment by Justman100** [comment]
> Any of the ones which cannot be retrieved by the browser in [#10895 (comment)](https://github.com/WeblateOrg/weblate/issues/10895#issuecomment-1917259577).
> 
> With offline compression disabled, these are generated on the fly, but still saved to the filesystem. I still think they are saved, but your serving of /static is misconfigured.

Wie gesagt, ich lasse das über uWSGI selbst laufen! Mit diesem Befehl:

```bash
uwsgi --ini /home/weblate.ini &
```

`weblate.ini`:

```ini
[uwsgi]
http = :3314
chdir = /home/Weblate
wsgi-file = /home/Weblate/weblate/wsgi.py
callable = application
processes = 4
threads = 2
```

**Comment by nijel** [comment]
Uwsgi does not serve static files, you need a web server in front of it. Please read the documentation...

**Comment by Justman100** [comment]
> Uwsgi does not serve static files, you need a web server in front of it. Please read the documentation...

Got it solved! One must use ` --static-map
