### ISSUE TITLE
Incorrect number of Strings in Component

### ISSUE THREAD

**Issue by labe-zedas** [WeblateOrg/weblate#10899]
### Describe the issue

We have a translation file with 1404 Strings. The counter when browsing those strings shows the correct number, but in
the "Overview" of this component it shows the wrong number of Strings (1405).

The base language file is correctly configured in the components settings. 
We have no idea, where Weblate counts this extra String...
Is this a bug or have we overlooked something?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Set up a component with translation File from VCS with 1404 Strings
2. Go to"Overview" of language in component, see number of total Strings
3. Browse the Strings and see a differing number of total Strings

### Expected behavior

Consistent number of Strings

### Screenshots

<img width="662" alt="asset-basicdata" src="https://github.com/WeblateOrg/weblate/assets/136434810/92509ed0-eae8-48a1-8710-a9edf6818404">
<img width="382" alt="asset-basicdata-detail" src="https://github.com/WeblateOrg/weblate/assets/136434810/230bc793-339f-4355-a856-0a68f21913c8">

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.14.1
 * Django: 4.1.1
 * siphashc: 2.1
 * translate-toolkit: 3.7.3
 * lxml: 4.9.1
 * Pillow: 9.2.0
 * bleach: 5.0.1
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.1
 * django-compressor: 4.1
 * djangorestframework: 3.13.1
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.8.0
 * rapidfuzz: 2.8.0
 * openpyxl: 3.0.10
 * celery: 5.2.7
 * kombu: 5.2.4
 * translation-finder: 2.14
 * weblate-language-data: 2022.7
 * html2text: 2020.1.16
 * pycairo: 1.21.0
 * pygobject: 3.42.2
 * diff-match-patch: 20200713
 * requests: 2.28.1
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.9.8
 * Cython: 0.29.32
 * misaka: 2.1.1
 * GitPython: 3.1.27
 * borgbackup: 1.2.2
 * pyparsing: 3.0.9
 * pyahocorasick: 1.4.4
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.1.1
 * Python: 3.10.7
 * Git: 2.30.2
 * psycopg2: 2.9.3
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * boto3: 1.24.73
 * zeep: 4.1.0
 * aeidon: 1.11
 * iniparse: 0.5
 * mysqlclient: 2.1.1
 * Mercurial: 6.2.2
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 6.2.11
 * PostgreSQL server: 13.10
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mx01.instance.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 6.1.18-200.fc37.x86_64 (x86_64)

**Comment by labe-zedas** [comment]
I've tried to reproduce this with a newer Verison, but as i'm importing the files to a fresh component, the counter is correct.
Is it possible to delete the cache of a component?

**Comment by nijel** [comment]
I think the following should work on your version (this has been heavily rewritten recently, so I might be wrong):

````
weblate shell -c 'from weblate.trans.models import Component; Component.objects.get(project__slug="asset", slug="basic-data").invalidate_cache()'
```

You migth need to adjust slugs to actually match the ones of your componnt.
