### ISSUE TITLE
Provide way to setup ssh keys

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#109]
To access private repos, weblate might need ssh keys. In case key is present, weblate could offer it's public key and in case it is not, it could generate it using ssh-keygen.

This would simplify automatic push setup.

**Comment by truesteps** [comment]
Is there a way to add SSH keys to your account so weblate repositories can be accessed without username/password auth? I wanted to use weblate translation repository as a git submodule

**Comment by nijel** [comment]
@truesteps Please open a separate question on this, it is off-topic here.
