### ISSUE TITLE
Automatic translation returns Index out of range Error

### ISSUE THREAD

**Issue by gzor** [WeblateOrg/weblate#10904]
### Describe the issue

On automatic translation i don't get suggestions, but the server error:
Automatische Übersetzung fehlgeschlagen: IndexError: list index out of range
In english:
Automatic translation failed: IndexError: list index out of range

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Add OpenAi as Machine translation.
2. Go to your component, the language to translate and select Tools => Automatic Translation
3. Configure it to make suggestions, and use OpenAI as Machine translation

### Expected behavior

Recieve Suggestions

### Exception traceback

```pytb
celery-translate stderr | [2024-01-30 15:07:37,599: INFO/ForkPoolWorker-1] HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
celery-translate stderr | [2024-01-30 15:07:37,605: WARNING/476] Machinery error: IndexError: list index out of range
celery-translate stderr | [2024-01-30 15:07:37,605: WARNING/ForkPoolWorker-1] Machinery error: IndexError: list index out of range
2024-01-30T16:07:37.606110505+01:00 celery-translate stderr | [2024-01-30 15:07:37,605: ERROR/476] Could not fetch translations from OpenAI
2024-01-30T16:07:37.606120489+01:00 celery-translate stderr | [2024-01-30 15:07:37,605: ERROR/ForkPoolWorker-1] Could not fetch translations from OpenAI
celery-translate stderr | [2024-01-30 15:07:37,607: ERROR/476] psa/terminalstarctbctb_supporti18ninformctbsupport/en: failed automatic translation: IndexError: list index out of range
celery-translate stderr | [2024-01-30 15:07:37,607: ERROR/ForkPoolWorker-1] psa/terminalstarctbctb_supporti18ninformctbsupport/en: failed automatic translation: IndexError: list index out of range
```

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.3.1

**Comment by nijel** [comment]
07acd5b2d930d5e21a74489e668916ff9c1397cc fixes this.
