### ISSUE TITLE
bad stat values ​​for unfinished strings without suggestions

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#10917]
### Describe the issue

bad stat values ​​for unfinished strings
![Uploading Screenshot_20240131_194434_Edge.jpg…]()

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1 Go to stats

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
The screenshot wasn't uploaded...

**Comment by tomkolp** [comment]
![Screenshot_20240131_194434_Edge](https://github.com/WeblateOrg/weblate/assets/39633242/4ac7b2cd-7f03-4f74-b8a7-b7f87d03c6c8)

**Comment by nijel** [comment]
You mean unfinished strings without suggestions?

**Comment by tomkolp** [comment]
> You mean unfinished strings without suggestions?

Yes
