### ISSUE TITLE
Add local user without registration

### ISSUE THREAD

**Issue by dolgovas** [WeblateOrg/weblate#10954]
### Describe the problem

I can't add user into system without registration. In my company I use open-id authentication for local workers and local authentication for outsource workers, but I can't make this, because /accounts/invitation is 301 redirect to /accounts/registration

### Describe the solution you would like

I want to have possibility to add local users into system without open /accounts/registration/ on my web-server for worldwide

**Comment by nijel** [comment]
* What Weblate version do you use?
* The invitation is supposed to redirect to registration so that the user completes the account that way.
* If you don't want public registration open, disable REGISTRATION_OPEN. The invitations will still work.

**Comment by dolgovas** [comment]
> What Weblate version do you use?

5.3.1 docker-compose version


> If you don't want public registration open, disable REGISTRATION_OPEN. The invitations will still work.

In previous version open-id connect doesn't create new users without REGISTRATION_OPEN... if it works now - that's pretty good. I'll check

**Comment by nijel** [comment]
Since 5.0 inviting works with all authentication backends.

**Comment by dolgovas** [comment]
> If you don't want public registration open, disable REGISTRATION_OPEN. The invitations will still work.

Unfortunately registration still works with disabled REGISTRATION_OPEN via direct link = /accounts/register/

May be it's a bug?

**Comment by nijel** [comment]
Maybe you have also configured `REGISTRATION_ALLOW_BACKENDS`?

Or maybe you've clicked on the invitation before? It is stored in the session, so if the registration page says something about invitation, that might be the reason.

**Comment by dolgovas** [comment]
I'm sorry, my bad. We use SAML instead open-id.
I want to use only SAML and internal user (created wia invitation only!)

May be I made any mistake in my configs?

I have
      `WEBLATE_REGISTRATION_OPEN: 1`
and
```
print(settings.AUTHENTICATION_BACKENDS)
('social_core.backends.email.EmailAuth', 'social_core.backends.saml.SAMLAuth', 'weblate.accounts.auth.WeblateUserBackend', 'social_core.backends.saml.SAMLAuth')
```

**Comment by nijel** [comment]
WEBLATE_REGISTRATION_OPEN should be 0 if you don't want open registrations.

**Comment by dolgovas** [comment]
https://github.com/WeblateOrg/weblate/issues/10954#issuecomment-1935694244

I already told you, that this option doesn't disable registration. It seems that it only hide registration button on main page, but you still make new user via direct link
https://mysite_weblate.test/accounts/register/

**Comment by nijel** [comment]
Okay, I'm lost in this, in https://github.com/WeblateOrg/weblate/issues/10954#issuecomment-1938472856 you have set it to 1 which indeed doesn't disable the registration.

* What is your setting for WEBLATE_REGISTRATION_OPEN and WEBLATE_REGISTRATION_ALLOW_BACKENDS?
* Can you clear your cookies before accessing `/accounts/register/` to make sure it's not a pending invitation? (It would be mentioned on the page, but you've ignored that question from https://github.com/WeblateOrg/weblate/issues/10954#issuecomment-1935902739).
* How did you install Weblate? Using Docker (as the configuration variable would suggest) or Python package?
