### ISSUE TITLE
Please document how to use the PO merge driver *outside* of Weblate

### ISSUE THREAD

**Issue by NightTsarina** [WeblateOrg/weblate#10967]
### Describe the problem

As explained in #1598 and elsewhere, Weblate configures the local Git repository to use a custom merge driver for PO files, which is very helpful in reducing conflicts.

Sadly, this is not available in other clones of the repo, so we encounter all kind of conflicts when trying to merge or rebase branches that touch these PO files (most commonly, because somebody is updating the source strings that are also being translated through Weblate).

Naively, I added a `.gitattributes` file to the repository so everybody could make use of this feature, but that seemed to break Weblate's configuration, and then all kind of superfluous conflicts appear when Weblate tries to rebase the translations branch on top of an updated `main` branch.

### Describe the solution you would like

I would like to see some explanation  or guide on how to use the merge driver outside of Weblate without causing these problems. Some more guidance on how to avoid these conflicts when updating source strings would also be useful.

Thanks!

**Comment by nijel** [comment]
There is no way to install this automatically for everybody. While you can add `.gitattributes` to the repository for everybody, you can't install the merge driver for everybody. So using `.gitattributes` is impractical, see also https://git-scm.com/docs/gitattributes#_defining_a_custom_merge_driver.

The script documentation is indeed confusing, I'll improve it.
