### ISSUE TITLE
Unify the two ways of adding glossary terms

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#10969]
### Describe the problem

Currently Weblate has two UIs for adding glossary terms:
1. From the translation view, by clicking "Add term to glossary"
2. From the glossary overview, by clicking "Add new glossary term"

The UIs that open are similar in terms of content (most of the fields are the same) but not identical. In the first case, there's a text field called "Explanation" and a menu for selecting the glossary to add the term to. In the second case, there's a text field called "Key"(TDF Weblate 5.3.1) or "Context" (current Hosted Weblate) 5. and additionally some buttons for inserting special characters.

It's not clear whether "Explanation" is the same field as "Key"/"Context".

### Describe the solution you would like

It would be better to unify the layouts and terminology as much as possible or even better, remove one of the UI altogether to avoid user confusion and simplify code maintenance.

**Comment by tjhietala** [comment]
Also, in the second UI, there's a checkbox titled "Auto-adjust context when an identical string already exists." which doesn't exist in the first UI and does not seem to be explained in Weblate's documentation.

**Comment by comradekingu** [comment]
In that line of thinking, unifying things into adding glossary terms from the translation field would help?
