### ISSUE TITLE
Highlighting sometimes fails on tags containing the word "variable"

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#10966]
### Describe the issue

When displaying changes in strings, Weblate normally highlights all changed content. However, sometimes tags fail to be highlighted. Also Weblate normally highlights the search terms in search results, but sometimes unneeded highlighting appears for tags. These errors in highlighting seem to happen sometimes (but not always) when the tag contains the word "variable".

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Example 1 (unneeded highlighting of the closing tag): https://translations.documentfoundation.org/search/libo_help-master/-/fi/?q=Matching+all+words&sort_by=-priority%2Cposition&checksum=
3. Example 2 (the closing tag in the History part is missing highlighting): https://translations.documentfoundation.org/translate/libo_help-master/textsharedhelp/fi/?checksum=56c9579e44aa4590#history
4. Example 3 (as above): https://translations.documentfoundation.org/translate/libo_help-master/textsharedhelp/fi/?checksum=77c655a6f82dc572#history

### Expected behavior

Tags are highlighted when, and only when, they're part of the change or search term that is being highlighted.

### How do you run Weblate?

Other

### Weblate versions

TDF Weblate 5.3.1

**Comment by nijel** [comment]
The search highlighting is really naive right now, see https://github.com/WeblateOrg/weblate/issues/42.

For the rest, there seem to be some corner cases when two highlighting overlap, that needs more investigation.
