### ISSUE TITLE
Failed to commit pending changes: 'NoneType' object has no attribute 'set'

### ISSUE THREAD

**Issue by captn-cap** [WeblateOrg/weblate#10963]
### Describe the issue

We download the xliff 1.1, re-upload it and get an error. Weblate worked just fine until a week ago, and we cannot figure out why.
Even without processing the xliff, and just simply downloading it and uploading it instantly we get the error, so nothing to do with our external translation process. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. customize download 2. XLIFF 1.1 3.upload translation 4. Failed to commit pending changes: 'NoneType' object has no attribute 'set'

### Expected behavior

upload the translation and merge

### How do you run Weblate?

Docker container

### Weblate versions

4.14.1

**Comment by nijel** [comment]
Please upgrade, this has been most likely fixed meanwhile. Moreover, including exception traceback (should be visible in server logs) would be helpful.
