### ISSUE TITLE
Crash on units API

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#10978]
[weblate.txt](https://github.com/WeblateOrg/weblate/files/14231346/weblate.txt)
This is exception traceback.
I guessed it might be a problem with the language file. I set up a new project and added the entries, and the api could be used normally.

_Originally posted by @AirJerryWhite in https://github.com/WeblateOrg/weblate/discussions/10932#discussioncomment-8431037_

**Comment by AirJerryWhite** [comment]
The problem has been found. It may be that the previous entries are repeated, causing problems with the project. After fixing the problem of duplicate entries, the API still cannot be called to query unit information. After deleting the project and recreating it with the same language file, it functions normally.
