### ISSUE TITLE
Add a "add comments" role to Weblate permissions

### ISSUE THREAD

**Issue by jonko0493** [WeblateOrg/weblate#10971]
### Describe the problem

It is useful for reviewers to be able to leave comments as part of our translation flow, but we still don't want them to be able to edit strings.

### Describe the solution you would like

It would be nice if there were role that specifically allowed for comments to be added.

### Describe alternatives you have considered

N/A there's really only two answers here either do this or don't haha

### Screenshots

N/A

### Additional context

N/A

**Comment by nijel** [comment]
The permission for adding comments is already there (see https://docs.weblate.org/en/latest/admin/access.html#default-teams-and-roles). Do you have any suggestion how the built-in role for your purpose should be called?

**Comment by jonko0493** [comment]
I feel silly -- I didn't actually realize I could make custom roles! That's my bad. Feel free to close as this solves my use case.

**Comment by comradekingu** [comment]
@jonko0493 You make it an issue of other people if you don't close yourself.
