### ISSUE TITLE
Post announcement on project/language

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#11003]
### Describe the problem

Announcements can already be posted on several scopes, but project/language one is missing.

### Describe the solution you would like

Fill the gap and add the UI to post it and change the `context_filter` method to display it in correct scopes.

**Comment by ivanacha** [comment]
Hi! I'm a newbie contributor and I'd like to takeup this issue.

**Comment by nijel** [comment]
@ivanacha You're welcome.

The Announcements model already has all the fiels to store this relation, so the missing parts are:

* Add announcement form to the project/language view to support adding it there.
* Adjust `context_filter` to include project/language assigned announcements in the matching scopes:
  
  https://github.com/WeblateOrg/weblate/blob/287feb9a1bbe9cb26fa184d5fc649d9df23053d7/weblate/trans/models/announcement.py#L17-L44

**Comment by ivanacha** [comment]
Alright, I'll start working on it.

**Comment by ivanacha** [comment]
@nijel I am unable to find the project/language view in the views folder to add the announcement form. [https://github.com/WeblateOrg/weblate/tree/main/weblate/trans/views](url).

**Comment by nijel** [comment]
It is here: https://github.com/WeblateOrg/weblate/blob/a697f36e902e03c1f28f5427d0d6cb4e8429e8ee/weblate/trans/views/basic.py#L225-L283

**Comment by harriebird** [comment]
Hi guys, check my PR #11561 for this issue.

**Comment by emmapeel2** [comment]
I have tried posting an announcement on Project/Language today, but it appears in all languages and components of my project, not in the particular language where I posted it.

Also I wondered:  If I click on 'Notify translators' will all translators get the message, or only the ones for that language? 

Thanks!

**Comment by nijel** [comment]
There appears to be some inconsistency in filtering such announcements; I will look into fixing that.

The notification works based on project/language user subscriptions and notification settings.

**Comment by nijel** [comment]
https://github.com/WeblateOrg/weblate/pull/19771 is the fix.
