### ISSUE TITLE
Outgoing commits is not 0 after successful push

### ISSUE THREAD

**Issue by bastianbeischer** [WeblateOrg/weblate#11010]
### Describe the issue

We have a component which pulls and pushes from/to different branches.

Example:
Repository branch: "dev"
Push branch: "feat/weblate_translations"

In the same repository.

We have the VC setup as 'Git with force push' and the  Merge style is 'rebase'.

It seems that after pulling the dev branch the commits in weblate are correctly rebased. Going to Repository Maintenance and the manually clicking "Push" works just fine.

But then the number of "outgoing commits" does not return to 0.

It seems that weblate compares the internal state with origin/dev, while it should compre with origin/feat/weblate_translations in order to determine how many commits need to be pushed?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Create a component which uses two different branches as 'repository branch' and 'push branch'
2. Make changes in weblate
3. Make changes in the remote repository on the repository branch
4. Pull those changes into the weblate repository
5. Note that outgoing commits is "1"
6. Click push
7. Outgoing commits is still "1"

### Expected behavior

Number of outgoing commits should return to 0, it should count the number of commits which have not yet been pushed to the push branch

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 5.3.1 (from weblate-docker)

**Comment by nijel** [comment]
Yes, Weblate counts outgoing commits as the number of commits not present in the branch it pulls from. In most cases, this is the interesting info (how many commits are not merged upstream).

It might be useful to add info of commits not present in the push branch for the cases where these are different.
