### ISSUE TITLE
Search text input field on search pages is still vertically resizable

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#11022]
### Describe the issue

The search text input field on search pages is still vertically resizable. It looks weird.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to the search page
2. Drag the resize control vertically

### Expected behavior

Make the search bar more harmonious. 
Maybe the `Custom search` dropdown menu next to the search text input field should scale along with it.
Or just limit vertical resizing?

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/49396421/bed90756-6924-4245-8d4d-66c5d870ea73)

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 5.5-dev

### Additional context

BTW, newline can still be entered into the search text input field by pasting it. Is it intended? Related: #10810

**Comment by nijel** [comment]
Yes, newline can be pasted and searched for if wanted. Resizing should also work, but should look better.
