### ISSUE TITLE
CLDR 42 Hebrew plural form changes

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#11030]
### Describe the issue

CLDR 42 introduced some new changes to the Hebrew plural forms without consulting the initiator of this change resulting in a decrease in the number of plural forms.
Applying this change will result in years' worth of translation work going to waste.
Please refrain from applying this change until we sort things out.
Thank you.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

No steps are required.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
CLDR 42 was released on 2022-10-19, so more than a year ago. Weblate typically follows that quickly for formats that follow CLDR, so it has been already applied more than a year ago. Such a change doesn't affect formats which have their set of rules (like Qt), or embed the plural form information in the translation file (gettext).

**Comment by yarons** [comment]
OK, I'll know what to watch closely from now on.
