### ISSUE TITLE
"Apply to propagated strings" button not funcitonal as intended

### ISSUE THREAD

**Issue by Mwallx** [WeblateOrg/weblate#11037]
### Describe the issue

![image](https://github.com/WeblateOrg/weblate/assets/89969909/78057200-fc7a-4094-a437-0c2865e0ebe9)

When you click this button, it does not apply the translation you selected to all strings with the same source, but would apply your selection to the CURRENT string(which has the same source too ofc). so currently in order to mass replace you have to click this button for every other string, or use the replace feature.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

easy

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Indeed it applies them only to propagated strings, these are labelled as such in the list. See https://docs.weblate.org/en/latest/admin/continuous.html#translation-propagation

This feature definitely needs some redefinition, please see https://github.com/WeblateOrg/weblate/issues/3166 for the discussion.
