### ISSUE TITLE
Support for multiple JSON files in a component

### ISSUE THREAD

**Issue by anuj-scanova** [WeblateOrg/weblate#11060]
### Describe the problem

Trying to develop support for Strapi Translation by fetching each page data (using Strapi API) in an individual JSON file.

The directory structure is like
```
src
 | - locale
      | - en
           | - home.json
           | - about-us.json
           |- support.json
      | - es
          | - home.json
          | - about-us.json
          | - support.json
```
Here `en` will be the default source language and `es` will be the translation language.

Currently, it asks to select only one file 
<img width="795" alt="Screenshot 2024-02-21 at 08 08 07" src="https://github.com/WeblateOrg/weblate/assets/105233146/2fc628d1-f482-46a3-923c-d645142d630a">

### Describe the solution you would like

Possibility to add a directory of files and weblate should fetch strings from each file and also generate translation to that respective file in the specific directory.

**Comment by nijel** [comment]
Once component in Weblate is always for one file. You might want to use https://docs.weblate.org/en/latest/admin/addons.html#component-discovery to automatically create additional components.
