### ISSUE TITLE
Superuser cannot access Restricted component

### ISSUE THREAD

**Issue by dxdx123** [WeblateOrg/weblate#11073]
### Describe the issue

I upgraded from version 5.0.2 to version 5.3.1 and found that users in the built-in Manager group could not see components that were set to Restricted component, and this user was set as a superuser. 
Is this expected?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Superuser cannot access Restricted component

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/14290268/6e180f81-d6e8-4fe7-9627-2bba830aecf7)

### How do you run Weblate?

Docker container

### Weblate versions

5.3.1

**Comment by nijel** [comment]
Probably not expected, but this corner case was not really considered. Restricted component is accessible only to users who have been explicitly granted it, but superuser probably could have an exception.

**Comment by nijel** [comment]
Okay - superuser can access it, but not list it.
