### ISSUE TITLE
Add new language to an existing language - Strings are missing

### ISSUE THREAD

**Issue by Hoschi1982** [WeblateOrg/weblate#11077]
### Describe the issue

I defined the default language and added some strings.

If I add a new language to an existing language with existing strings, then the new language is missing the already defined strings.
That's wrong.

However, if I add a new string after adding the new language, then it will also be present in the new language. 
That's right.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Create new project
2. define default language "german"
3. add strings in language german
4. create new language
5. strings are missing in the new language

### Expected behavior

strings are also present in the new language

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
In case you are using a bilingual format, you need to add strings to all languages.
