### ISSUE TITLE
Create new bilingual component via file upload

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#11085]
### Describe the problem

Right now, the file upload only supports monolingual files, but it would be useful for bilingual as well.

### Describe the solution you would like

Define target language for uploaded file in case it is bilingual.

### Additional context

https://github.com/WeblateOrg/weblate/discussions/10683

**Comment by 19231097LX** [comment]
I would like to work on this if it hasn't been taken! @nijel

**Comment by nijel** [comment]
@longlongagou Yes, you are welcome work on this!

**Comment by gersona** [comment]
@nijel needs some guidance on one point: if the user uploads a `cs.po` file containing the English source with Czech translation, should this file be used as template for new translation, or a `en.po` file should be created as used as template ?
