### ISSUE TITLE
Undocumented requirement for contributing

### ISSUE THREAD

**Issue by metalglove** [WeblateOrg/weblate#11094]
### Describe the issue

I am trying to contribute to the repository by starting on a "good-first-issue". However, upon following the steps for getting started with contributing using docker I run into a missing requirement.

https://docs.weblate.org/en/latest/contributing/start.html#running-weblate-locally-in-docker

When running `./rundev.sh` the build fails as the `jq` command is missing
```
./rundev.sh: line 31: jq: command not found
```

The `jq` command is used here:
https://github.com/WeblateOrg/weblate/blob/213f593ad662767b5bf8ab06419c13f6301d8b7a/rundev.sh#L31C5-L31C129

If I am not mistaken, it is the following tool https://github.com/jqlang/jq

The tool can be installed like this
```md
# linux 
apt-get install jq

# macOS
brew install jq
```

As I am on macOS, I used brew to install the tool and now it works.
Looking through the documentation, I do not see this requirement listed anywhere.
Is this intended? Or have I missed this requirement somewhere?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

`./rundev.sh`

### Expected behavior

I expected to run the dev environment and boot up the docker container.

### Screenshots

<img width="667" alt="image" src="https://github.com/WeblateOrg/weblate/assets/24389604/3fe37203-4cea-4726-9448-28df325c9162">

After installing `jq`, it works.\
<img width="592" alt="image" src="https://github.com/WeblateOrg/weblate/assets/24389604/89ae6fbe-d280-459e-8c3e-cd2cf50ecd67">

### How do you run Weblate?

Docker container

**Comment by comradekingu** [comment]
`jq - lightweight and flexible command-line JSON processor` wasn't installed on pretty default Devuan,
so active installation is at least not specific to macOS.

**Comment by nijel** [comment]
I think that would be good enough.

**Comment by metalglove** [comment]
I have created a pull request for the documentation change.
However, I noticed that your [CONTRIBUTING.md](https://github.com/WeblateOrg/weblate/blob/main/CONTRIBUTING.md) document would then miss this same note.
Should that also be updated?
