### ISSUE TITLE
Missing documentation for Gitea Social Auth

### ISSUE THREAD

**Issue by GamePlayer-8** [WeblateOrg/weblate#11112]
### Describe the problem

I've missed an option for configuring Social auth over Gitea/Forgejo instance(s) at https://docs.weblate.org/en/latest/admin/auth.html

### Describe the solution you would like

I'd like to see an example / environment description(s) for Gitea/Forgejo OAuth2.

**Comment by federicopoi** [comment]
Hi, I am new to open source and I would like to help resolve this issue. I am working on adding documentation for configuring Gitea/Forgejo OAuth2 for social authentication. I will submit a pull request soon. Please let me know if you have any specific requirements or suggestions. Thank you!

**Comment by lotigara** [comment]
There is my PR: #12222

**Comment by nijel** [comment]
Thanks, that one is waiting for @orangesunny to review.

**Comment by orangesunny** [comment]
Reviewed, polished, good to go. Thanks for the contribution, @lotigara!

**Comment by lotigara** [comment]
> Reviewed, polished, good to go. Thanks for the contribution, @lotigara!

My pleasure!
