### ISSUE TITLE
Can't commit pending changes or push outgoing commits

### ISSUE THREAD

**Issue by AlphaStarguide** [WeblateOrg/weblate#11111]
### Describe the issue

After upgrading the docker container to latest version, I found out I can't push my changes into repo.
It says "Could not lock the repository, another operation is in progress."
![image](https://github.com/WeblateOrg/weblate/assets/90250769/f302a958-957d-48d6-a9f5-f5f10f42950f)
I checked the log ,this one should be the error message.
`weblate-docker-weblate-1   | gunicorn stderr | [2024-02-29 04:26:52,299: WARNING/437] Handled exception: WeblateLockTimeoutError: Lock on lock:repo:1 could not be acquired in 120s`

How should I fix this problem?

Update:
I attempted to restart the Docker container and the server, but neither approach resolved the issue.
If more information is required to solve the problem, please let me know.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

May be my personal problem but every time try to commit, it bugs.

### How do you run Weblate?

Docker container

### Weblate versions

5.4.2

**Comment by nijel** [comment]
Maybe there is an operation in the background going on? Check docker logs. In case of a crash, the lock might be stale for one hour and persists in redis, so it won't disappear by restart.
