### ISSUE TITLE
fail to upload translation with file

### ISSUE THREAD

**Issue by gs-xpeng** [WeblateOrg/weblate#11110]
### Describe the issue

We upload a translation file with more than 10000 strings in  " File - Upload translation - Add as translation " , It sometimes failed to upload. and it takes 4+ minutes .    （Weblate : 5.4.2 , We deployed it with docker locally）

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

We upload a translation file with more than 10000 strings in  " File - Upload translation - Add as translation " , It sometimes failed to upload. and it takes 4+ minutes .    （Weblate : 5.4.2 , We deployed it with docker locally）

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
Yes, uploading massive files can take some time to process. What means “failed to upload”?

**Comment by gs-xpeng** [comment]
Like this:
1、Lock on lock:repo:42 could not be acquired in 120s
2、
Exception Type: | ResponseError
MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
---
It's working now when adding more CPUs and memory.  Thanks

**Comment by nijel** [comment]
I think redis was killed due to low memory, but this should be visible in the logs.
