### ISSUE TITLE
Notification on component alerts

### ISSUE THREAD

**Issue by spadgeaki** [WeblateOrg/weblate#1112]
### Steps to reproduce
1. Have a JSON component with en.json as a source file (288 strings).
2. Add few key:values to the source JSON, pull to the weblate repository.
3. There are no new strings showing up in Weblate (should be 292 strings).
4. Try updating repository in administration.
5. There are no new strings showing up in Weblate (should be 292 strings).
6. Try uploading new source file via Files -> Upload translation.
7. Notification "Processed 292 strings from the uploaded files." shows up. But there are no new strings showing up in Weblate.
### Actual behaviour

There are still only 288 strings to translate in updated component.
### Expected behaviour

There should be 292 strings to translate.
##

**Comment by nijel** [comment]
Can you try loading the file from command line and checking the output? Maybe there are duplicate IDs?

```sh
./manage.py loadpo project/component --force
```

**Comment by spadgeaki** [comment]
Thank you very much, the isssue was in the duplicate IDs. We will be more cautious in the future! Would it be possible to notify about such errors?

**Comment by nijel** [comment]
These are currently shown only in the project history, there is no email notification right now.

**Comment by nijel** [comment]
There is still no email notification, but all such errors are now visible as alerts, see https://docs.weblate.org/en/latest/devel/alerts.html

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
