### ISSUE TITLE
Updating comment/note in source template file does not correctly update comment/note in translations

### ISSUE THREAD

**Issue by henry-torproject** [WeblateOrg/weblate#11133]
### Describe the issue

Seen when using Fluent, but I imagine it would effect other formats that use a template.

Whenever the source file changes the comment/note on one of its strings, the translation files do not pick up on this change, and Weblate shows the "string description" as a concatenation of the old and new strings.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Tested with my local weblate instance, but I've seen this for the Tor Project before:

1. Have a Fluent component with a template file "en.ftl" containing a Fluent string with a comment "Original comment.", and translate it to "de.ftl".
2. Change the comment in the locally stored file "en.ftl" to be "New comment.".
3. Force weblate to pick up the new changes.

Weblate will show the en string with the string description: "New comment.". But the de string will have the string description: "New comment. Original Comment.". Moreover, the "de.ftl" file will only contain the old comment: "Original Comment.".

NOTE: The concatenation comes from this line: https://github.com/WeblateOrg/weblate/blob/a808cf013882ae41987921cf93301c0055e3cdcc/weblate/formats/ttkit.py#L106-L110 and seems to be a result of the translated file not picking up on the comment change.

### Expected behavior

If the notes on a template unit changes, then all translation units with the same original note should update their note to match the new value. I.e. the new comment should entirely replace the old comment on Weblate, and in the translated files.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Are actually comments in the translated file desired? Keeping them in sync is an additional effort which would have to be performed on each template file update.

**Comment by nijel** [comment]
I'm not 100% sure how all the formats work, but there is definitely no synchronization in place.

From what I know:

* Some formats discard the comments while adding strings to the translation. This applies to all LISA based formats which store content in XML tree and not in the translate-toolkit Unit (Android, TS2 or XLIFF).
* There are formats which do not support comments at all (plain JSON) or in translate-toolkit (YAML).
* Others which store info on the translate-toolkit unit will probably preserve comments (Properties, Fluent, some JSON variants as WebExtension).

Possible solutions:

* Remove comments completely when adding new strings to translated files. This avoids synchronization issues, but will look weird in some formats (eg. WebExtension JSON).
* Sync comments while translating. This would help in situations where both source and comment change.
* Implement add-on to sync comments on template file update. This is a similar approach to https://docs.weblate.org/en/latest/admin/addons.html#update-po-files-to-match-pot-msgmerge.

**Comment by nijel** [comment]
I think stripping comments while adding translated strings is the best approach. It is also the approach which needs least work ;-).

**Comment by gzm0** [comment]
TY for the quick feedback. I'll take a stab at this.

What I've found out so far RE not propagating comments: It seems the snippet above is from the wrapped ttkit unit. So it's not the one that is in the store.

My plan is to identify the point where a new unit gets created (when a translation is added) and attempt to prevent / remove comment propagation.
