### ISSUE TITLE
json import ignore pattern

### ISSUE THREAD

**Issue by eichiflSICKAG** [WeblateOrg/weblate#11149]
### Describe the problem

we have json files with a structure like 
```
{
  "a": {
    "b": {
      "c": {
        "d": {
          "TEXT": "hello",
          "ID": 1234
        }
      }
    }
  }
}
```

but we want weblate to only import the TEXT "hello" not the ID 1234

### Describe the solution you would like

having a ignore pattern field

**Comment by nijel** [comment]
The only way to achieve this currently in Weblate is implementing native support for such files.
