### ISSUE TITLE
Orphan screenshot warning doesn't disappear after clear all of unused screenshots

### ISSUE THREAD

**Issue by Wohlstand** [WeblateOrg/weblate#11141]
### Describe the issue

Hello!

Recently I found that WebLate doesn't get rid of the "Here is at least one unused screenshot presented" warning after I removed all screenshots that has no assigned string. They appeared because of the recent project-side rework that caused removal of a pile of strings that got been replaced with another one. And once I got that warning, I started to remove these screenshots (as they are now obsolete on my side). However, the warning still not gone after one day since I removed all unused screnshots. And, additionally, there is totally no way to remove it manually...

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Have a pile of strings.
2. Upload a screenshot for each of them.
3. On the project side, remove some number of strings, and add another one.
4. Wait when "Unused screenshots" warning will pops up.
5. Open screenshots list and remove every screenshot marked by red exclamation sign.
6. Wait again, and...
7. It still appears. I checked trice the whole list of screenshots on all 7 pages (on my end), I swear I removed every unused screenshot, and warning still wasn't gone.

### Expected behavior

The warning gets disappear after all unused screenshots got been removed or assigned to anything also.

### Screenshots

![Снимок экрана от 2024-03-05 21-04-08](https://github.com/WeblateOrg/weblate/assets/6751442/bbd36054-e0d2-4bfe-86f9-c9a2b9b58c06)

### How do you run Weblate?

weblate.org service

### Additional context

The project and its component where the problem ocurred: https://hosted.weblate.org/projects/thextech/engine-general/

**Comment by nijel** [comment]
To immediately clear the alert, a m2m_change signal on `Screenshot.units` should trigger `component.update_alerts` method.
