### ISSUE TITLE
Too many git commits in suggestion review process

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1116]
### Steps to reproduce
1. Create 100 suggestions
2. Pass through suggestions: accept one, edit the second, accept third etc.
### Actual behaviour

Each change is committed separately, ignoring age.
https://github.com/openSUSE/libzypp/commit/5bf988c4b93ac2c2d95aee45520ffe5316f5db79 (and click to its parents)
### Expected behaviour

If there are pending strings to review, postpone commit until defined age (or any other time) passes.
### Server configuration

```
Weblate 2.5
Python 2.7.9
Django 1.8.4
six 1.9.0
python-social-auth 0.2.7
Translate Toolkit 1.13.0
Whoosh 2.7.0
Git 1.8.5.6
Pillow (PIL) 1.1.7
dateutil 2.1
lxml 3.2.3
django-crispy-forms 1.5.2
compressor 1.5
pyuca N/A
Database backends: django.db.backends.mysql
```
##

**Comment by nijel** [comment]
It seems that every suggestion is coming from different author, is that right? In such cases the separate commits are needed to keep the authorship...

**Comment by stanislav-brabec** [comment]
No, all came from oné author. But in the review process, some were accepted and some were edited by the reviewer before accepting.

**Comment by nijel** [comment]
Okay, that makes the difference. Currently if suggestion is accepted without change, the commit is authored by suggestion author. If you make additional change, the commit is authored by currently logged in user. In case of heavy editing this leads to lot of commits...

**Comment by stanislav-brabec** [comment]
It could still lead to two commits only: one by the original suggestion author, second by suggestions editor.

Both can be:
-  Delayed until AGE passes without any change or new suggestion.
or
- If no more suggestions exist, commit now.

**Comment by nijel** [comment]
But that would mean reordering the transactions, what is something we currently can not do (all changes are immediately written to the underlaying file).
