### ISSUE TITLE
Remove empty stale glossaries

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#11168]
### Describe the problem

The glossary languages are automatically added when a new translation language is used. There is no logic in place to remove such automatically added glossary languages when they are no longer needed.

### Describe the solution you would like

Cleanup of not needed empty glossaries should happen automatically in `sync_glossary_languages` and when translations are removed.

**Comment by AmanSal1** [comment]
@nijel  Can I give it a shot ?

**Comment by nijel** [comment]
Sure, you're welcome.

**Comment by AmanSal1** [comment]
Is this the right documentation to start ?
https://docs.weblate.org/en/latest/contributing/start.html

**Comment by nijel** [comment]
Weblate will not work on Windows, so using Docker is recommended.

**Comment by AmanSal1** [comment]
@nijel I have created a pull request can you review it ?
