### ISSUE TITLE
Screenshot submission permission as part of the ACL

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#11177]
### Describe the problem

Sometimes I want to let the project translators have the ability to post screenshots on their own without having to centralize the process or permit them to manage things they shouldn't manage.

### Describe the solution you would like

Add an option to let specific users manage the screenshots.

### Describe alternatives you have considered

Setting a screenshot file filter and allowing the contributors to submit images directly to the repository.

### Screenshots

Ironically, unnecessary :)

### Additional context

The other case is that I'm trying to avoid many binary files in my repository so I would likely refrain from hosting a large number of screenshots in my repository (or high-resolution images in general).

**Comment by nijel** [comment]
There is a built-in role *Manage screenshots*, you can create a team with this role and add users you want.

**Comment by yarons** [comment]
Wasn't aware, thanks :)
