### ISSUE TITLE
Wrong Translation using Xliff with placeholder support

### ISSUE THREAD

**Issue by 19Alex81** [WeblateOrg/weblate#11179]
### Describe the issue

I try to automatic translate an Xliff file (articulate rise) using deepl and xliff with placeholder support and some of the translations show a translation from another line. i think this is a chaching issue and i work on the version 5.4.2

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Translate xliff with automatic placeholder support using deepl

### Screenshots

<img width="726" alt="image" src="https://github.com/WeblateOrg/weblate/assets/163110287/303ebfd8-184d-43d2-bc86-6c8a8aa8a6ab">

### How do you run Weblate?

weblate.org service

### Weblate versions

Version 5.4.2

**Comment by nijel** [comment]
Do you see this in *Automatic suggestions* tab while translating also, or only when performing automatic translation on more strings?

**Comment by 19Alex81** [comment]
Hi,
Yes seems to be the sam in automatic suggestions
<img width="698" alt="image" src="https://github.com/WeblateOrg/weblate/assets/163110287/04273936-18b7-45e7-ae2f-b000eb23204a">

**Comment by nijel** [comment]
These are added in batch, what I meant is the *Automatic suggestions* tab in bottom.

**Comment by 19Alex81** [comment]
it does not look like. if i delete the automatic suggestions it appear again after the automatic translation.
is there a way to delet all sugastions from this projekt ?
just to be sure that there are nor relicts from older version

**Comment by 19Alex81** [comment]
Hello,
I tried deleting the translation memory for this component and only using DeepL for automatic translation, and my problem is getting worse.
<img width="701" alt="image" src="https://github.com/WeblateOrg/weblate/assets/163110287/bbd1fecd-0903-4026-898f-c048388e000f">

<img width="704" alt="image" src="https://github.com/WeblateOrg/weblate/assets/163110287/b00063ad-1331-42fd-971a-3194531e6c44">

**Comment by nijel** [comment]
> Hello, I tried deleting the translation memory for this component and only using DeepL for automatic translation, and my problem is getting worse. <img alt="image" width="701" src="https://private-user-images.githubusercontent.com/163110287/312421094-bbd1fecd-0903-4026-898f-c048388e000f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTUwMjIsIm5iZiI6MTcxMzYxNDcyMiwicGF0aCI6Ii8xNjMxMTAyODcvMzEyNDIxMDk0LWJiZDFmZWNkLTA5MDMtNDAyNi04OThmLWMwNDgzODhlMDAwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQxMjA1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTM4NWNlNzQ1NmEzYjZhYzg2N2RjNDFjZDVhYWE0YzQ0YjU3ZDNmZDE2YWY5ZDk1NTMwNjMxM2RiYjAwN2I2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uwTLWInrIlCFUTVOKkifsGc_WStA7Lk63AbJJ6C29HA">

This seems correct - it does suggest to remove the additional markup.

> <img alt="image" width="704" src="https://private-user-images.githubusercontent.com/163110287/312421409-b00063ad-1331-42fd-971a-3194531e6c44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTUwMjIsIm5iZiI6MTcxMzYxNDcyMiwicGF0aCI6Ii8xNjMxMTAyODcvMzEyNDIxNDA5LWIwMDA2M2FkLTEzMzEtNDJmZC05NzFhLTMxOTQ1MzFlNmM0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQxMjA1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzdkYmJkYmU3ZTQxZDlmNDdkMmQ2Yjc2NjQxYzVjMmViOGI5ZGFlNDBmZGE5ZWQ4MGE3NTIzZjI3MWY5Mjg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.887tV_jonfZ5EuEm_a_6xbJq_DEMjWdxIiTLgc9E9IE">

This shows current translations. Please note that the default filter for automatic translation is only to look at strings without a translation, so it won't be applied automatically.

**Comment by nijel** [comment]
Thanks to https://github.com/WeblateOrg/weblate/discussions/8673 I probably discovered the issue here.
