### ISSUE TITLE
Question: what is the recommened way to implement the translation preview on the site?

### ISSUE THREAD

**Issue by generalov** [WeblateOrg/weblate#1117]
What is the recommened way to implement the translation preview on the testing site writen on Django framework?

Translator changes some translation in the Weblate and wants to preview it immediately on the testing site. 

I think this could be implemented as:
- Translator changes the translation on Weblate
- Project owner prerforms git commit to commit the change into the translations branch, git pull (merge), git push to git repository
- git hook watches for pushes and preforms testing site update: 
  - git fetch changes from development and translation branches
  - git merge translation branch into the development branch
  - run manage.py compilemessages
  - uwsgi restart
- Translator refreses the page on the testing site and looks for changes.

It looks lite too complecated and produces a lot of commits to the git repostory.
Is any simple way to implement it?
##

**Comment by nijel** [comment]
I don't see better approach right now. You can automate second step by using API as well (either [directly](https://docs.weblate.org/en/latest/api.html) or via [wlc](https://docs.weblate.org/en/latest/wlc.html).

**Comment by nijel** [comment]
Alternatively you can completely skip the Git for testing site and fetch [translated file directly from Weblate](https://docs.weblate.org/en/latest/api.html#get--api-translations-%28string-project%29-%28string-component%29-%28string-language%29-file-).
