### ISSUE TITLE
"Things to check" block has red header even though with updated rules check is passed

### ISSUE THREAD

**Issue by keunes** [WeblateOrg/weblate#11195]
### Describe the issue

There is an inconsistency between the background colour of the 'things to check' box title and the state of the check. The title header is red while the check is passed.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Upload fonts
2. In your component, set up a `max-size` flag with a very small number.
3. Open a string in a browser tab, and note that it doesn't pass the check.
4. Increase the `max-size` flag to a much larger number.
5. Refresh the string tab, and note that it now does pass the check.

### Expected behavior

a) The header of the 'Things to check' box is not red, OR
b) The text size check details are not displayed in a 'Things to check' box but in a box titled 'Check details' or 'String size'

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/11229646/a623bd22-2ce4-4314-bff1-9f0ad2a8cb2d)

### How do you run Weblate?

weblate.org service

### Additional context

Issue can be seen here: https://hosted.weblate.org/translate/antennapod/app-store-listing/screenshot-titles/nl/

**Comment by nijel** [comment]
The checks should be updated in the background when changing component flags, so it should eventually disappear. But as it is still there, there might be something wrong in the logic.

**Comment by nijel** [comment]
Okay, it is always rendered intentionally when the check enabled, see 4f132257926 and #3448. Apparently, the checkmark icon is not enough to realize this is an informative display only, so the UX needs to be fixed to make this clear.

**Comment by keunes** [comment]
Hello @nijel,
Thanks so much for addressing this. The fact that the rendering is always there is indeed quite helpful.

What I'm wondering: did you change the heading colour also? Because that red colour is the thing that gives the 'warning' feeling. In terms of UI signalling, that colour overshadows the checkbox and would do the same with the explanatory text.

I think that more helpful than having an explanatory text, would be to have a green/red header background depending on the situation or a more neutral colour always (without differentiation).
