### ISSUE TITLE
Translation validation via API call

### ISSUE THREAD

**Issue by rix0rrr** [WeblateOrg/weblate#11191]
### Describe the problem

We run a website where we teach children to program, and we offer this in multiple languages so children don't get overwhelmed by having to learn English in addition to learning programming.

Our examples (including source code) are translated by people who may not be programmers themselves, and when translating they often make mistakes agains the programming language syntax in the examples they are supposed to translate.

This used to break the website all the time. We now have CI checks on code in examples, but now our translation CI grinds to a halt every time some a user makes a mistake in any of the code samples. 

Once the broken change has been committed, there's nothing for us to do except fix it by hand (if we even understand the language in practice... not easy if its Thai or Vietnamese or Arabic or any other language we don't speak), or completely revert the change, dropping the translator's efforts.

It would be much better if we could prevent the bad input from getting into the system in the first place, and show the translator that they've made a mistake.

### Describe the solution you would like

Can Weblate make an API call before a user submits a translation, so we can check it for errors before it gets submitted and saved into the Weblate DB?

That way, we can show users as they're translating that what they're submitting can never work, and we will not accept it.

I understand that having to call out to other services adds uncertainty to the performance and stability of your own backend, and that you might not be too keen to call out to any service that could be down, could take 30s to respond, etc.

I was thinking that a nice middle ground might be to do the validation call in the user's browser. If we can get the frontend to make an XMLHttpRequest POST to a project-configurable endpoint with the proposed translation, and it could respond with a status like `ok`, or some error that gets displayed to the user and the form doesn't get submitted to the Weblate server, then we could get the validation that we need without putting extra strain or requirements on your backend.

### Describe alternatives you have considered

If we had a technically savvy audience we could potentially use a GreaseMonkey script; but our translators are volunteers, don't necessarily read up on our materials, and probably are not capable of installing GreaseMonkey and user scripts.

We'd really need a zero-touch solution from the user's perspective, which means it would need to be a Weblate feature.

Another possible solution might be Weblate having a "draft" status for translations, and us having a way to control that via REST API or some other method: we would revert the change in our CI, but in some way push the invalid translation back to Weblate in a status that requires human revision to try again. This seems like it would require more changes than a validation call before first ingestion.

### Additional context

I'd be willing to help implement this, if that would help get this over the line.

**Comment by nijel** [comment]
Maybe you can utilize one of existing checks in Weblate? See https://docs.weblate.org/en/latest/user/checks.html

You can also [implement your own](https://docs.weblate.org/en/latest/admin/checks.html#writing-own-checks). If this is something suitable for a wider audience than just your project, we are happy to accept it into our code base.

Involving external services in the check is possible, but needs consideration about handling error conditions when service is unavailable.
