### ISSUE TITLE
Do not show icons for unactionable alerts

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#11208]
### Describe the problem

Currently Weblate shows alert icons (white exclamation marks on red background) on components and projects even if the alerts are about something the user can't resolve. This adds to visual clutter and may confuse users.

### Describe the solution you would like

Alert icons should not be shown to logged-in users who lack the privileges to resolve them. (The users who do have the necessary privileges should continue to see them).

Logged-out users are a corner case. Maybe the icons should stay visible for them.

### Additional context

TDF Weblate 5.3.1

**Comment by nijel** [comment]
Alerts indicate that something is wrong with the component, so even if the user cannot do something with that, he might postpone his contribution until the alert is resolved.

**Comment by tjhietala** [comment]
At least there should be no reason to show to translators the alert icon for the whole project if only some of the components have alerts.

Also, not all alerts indicate that something is necessarily wrong, it seems some are more like "admins, you might want to look at this at some point", e.g. https://translations.documentfoundation.org/projects/libo_ui-master/dictionaries/dictionariestr_tr/#alerts

**Comment by nijel** [comment]
This particular alert will reflect repository changes to strings as well since 13937755bd2b6fecd47177089c7c77e7a1c50ede, so it will disappear once TDF upgrades to 5.4. The alerts are intended as an indication that something is wrong with the component.
