### ISSUE TITLE
Reverse user creation to let the admin choose names and user name

### ISSUE THREAD

**Issue by pmamat** [WeblateOrg/weblate#11209]
### Describe the problem

Once upon a time... when creating a new user, the admin was able to enter the user's login and name. 
Now this does not work any more: the admin only enters the e-mail address and the user is free to choose login and name.

Whe are using weblate for different projects with different users from different companies. It would be great to have the company's names in the login, like _bigcompany.firstname.lastname_. Now some users simply register with _firstname_ which is really not practical at all.

Additionally, we can only add a new user to a project after the registration. Thus I need to get feedback from the new users: "now I'm registered, please add me to the project" instead of doing all that at one point in time.

### Describe the solution you would like

I'd like to get the old functionality back.

**Comment by nijel** [comment]
You can invite users directly to a project, just invite them from the project, not in the management interface.

As for the name and username, we had exactly opposite feedback before: admins got only a list of e-mails and didn't want to fill in other details. Apparently, the expectations differ here a lot.

**Comment by pmamat** [comment]
Thanks for your feedback.

I think that both use cases are useful.

Maybe you could implement an option to customize this behaviour?

Kind regards,
 Philipp
