### ISSUE TITLE
Prevent Weblate from creating commits

### ISSUE THREAD

**Issue by rix0rrr** [WeblateOrg/weblate#11268]
### Describe the issue

When continuously localizing, we are experiencing a lot of merge conflicts between Weblate and regular development work happening on the main branch. We have contributors constantly translating whenever it suits them, and they are volunteers so we cannot tell them what to do.

In order to combat merge conflicts, we've now resorted to the following workflow:

- Prevent Weblate from creating commits at whim
- Instead, we run a daily workflow where we use the CLI to run `pull`, `commit` and `push` in order.
- The PR that is created by Weblate gets merged automatically.

This should result in 0 merge conflicts, as the only cause for merge conflicts would be if any PRs are merged in the ~1hr period between Weblate PR creation and automerge, at 7am. 

(There might still be conflicts in the Weblate database, as translated strings are also updated in VCS. It's not clear to me how these conflicts are handled as I don't think I saw this described anywhere in documentation, but at least they should not result in merge conflicts)

It turns out that **Step 1** from our desired workflow, "Prevent Weblate from creating commits", is a hard one. I've tried to achieve it this way:

- Set all components in our project to "Age of changes to commit: 2160" (the highest possible value)

<img width="559" alt="image" src="https://github.com/WeblateOrg/weblate/assets/524162/0de7344e-4185-405d-9d0d-b8bc6303de58">

Since we run a daily `commit` command, no change should ever exceed 2160 hours. And yet, I occasionally see commits like these created:

<img width="514" alt="image" src="https://github.com/WeblateOrg/weblate/assets/524162/e2d907d0-12f2-4668-9c4a-00a8953dec63">

The bottom 2 events are my daily workflow script using the `wlc` command, but the 2 events after that are Weblate creating commits, even though I asked it not to create any.

Why have these commits been created? How can I find out why these commits were created?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Set all components of my project to autocommit after 2160 hours.
2. Run a daily `wlc commit` job
3. Have people contribute translations at arbitrary moments in the day.

Could the cause be that someone adds a new language? Would that always create a new commit, regardless of any other settings? (That would explain why a commit was created for Slovenian, though it wouldn't explain why a commit was created for French)

### Expected behavior

I would like Weblate to only create commits when I tell it to, in a time window that I choose.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/continuous.html#lazy-commits for info when Weblate commits. https://github.com/WeblateOrg/weblate/issues/8770 will make commits happen less often.

**Comment by rix0rrr** [comment]
Can I disable Lazy Commits? I really want full control over when Weblate commits, and there are many events that I do not control:

* Somebody else changes an already changed string.
* A merge from upstream occurs (as far as I can tell, Weblate updates from upstream constantly)
* A file download is requested.

----

Alternatively: I can blow away merge conflicts by calling `wlc reset`. I'm concerned that also blows away database changes that have been made in the mean time. Or will those be written out again to the fresh set of files merged from upstream?

**Comment by nijel** [comment]
Disabling lazy commits would make Weblate immediately commit each change. We had that in the very beginning, and you would rather not use that.

> Somebody else changes an already changed string.

https://github.com/WeblateOrg/weblate/issues/8770 will address this.

> A merge from upstream occurs (as far as I can tell, Weblate updates from upstream constantly)

If you configure a webhook, it does, but you can choose not to configure it and update manually.

> A file download is requested.

This is currently being discussed at https://github.com/WeblateOrg/weblate/issues/11256

> I'm concerned that also blows away database changes that have been made in the mean time. Or will those be written out again to the fresh set of files merged from upstream?

Reset does discard all changes on Weblate side.

**Comment by rix0rrr** [comment]
> Disabling lazy commits would make Weblate immediately commit each change. 

I apologize for using the wrong terminology. I meant to say disable automatic committing altogether.

Let me take a step back: for unclear reasons, Weblate occasionally behaves unreliably. Wrapping settings are not applied, some strings are marked "read-only" in some language for a reason I don't understand, keys in YAML objects are reordered, the order of headers in a gettext file are constantly changed, which was leading to conflicts. We've tried to solve this by heavily relying on scripting to normalize file contents, but this leads to more conflicts when Weblate is creating commits based on an outdated view of the world. 

How would you suggest we best avoid merge conflicts?

**Comment by nijel** [comment]
I think the best approach would be to address the individual issues you encounter:

> Wrapping settings are not applied

This is #11032 or something different?

> some strings are marked "read-only" in some language for a reason I don't understand

Usually happens when source string is marked as needing editing.

> keys in YAML objects are reordered

Weblate should keep existing ordering and add new strings to the end of the file. There is https://github.com/WeblateOrg/weblate/issues/11134 to make it match the ordering in the template for monolingual files.

> the order of headers in a gettext file are constantly changed

The ordering is currently hard-coded in translate-toolkit (library we use for manipulating with the files): https://github.com/translate/translate/blob/4a51a2aa7749b09ff77d74cd55111f8b0307dcc5/translate/storage/poheader.py#L112-L127 It should match what GNU gettext produces. If not, please file an issue there.

**Comment by rix0rrr** [comment]
Bugs will always exist and new ones may be introduced; relying on them all to be fixed to unblock our workflow seems unrealistic. 

But you are saying there is no other way, correct?

**Comment by nijel** [comment]
https://github.com/WeblateOrg/weblate/issues/8770 is the way to go. But it's not an immediate solution, fixing bugs could be faster.
