### ISSUE TITLE
XLIFF file traslation with DEEPL

### ISSUE THREAD

**Issue by emartynov** [WeblateOrg/weblate#11265]
### Describe the issue

Hi people,

I'm trying to translate Hedy.org file via xliff export/import and DeepL.
After exporting, I tried to upload a file, and I got a message in an invalid file format. Unfortunately, DeepL doesn't say anything about the error. I've tried to use the online [xliff file validator](https://dev.maxprograms.com/Validation/) and it showed error `Invalid attribute in <trans-unit>: weblate-flags`.

How can I proceed?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Export xliff file
2. Try to upload to DeepL over API
3. Get error invalid file format

### Expected behavior

File is imported

### Screenshots

<img width="374" alt="Screenshot 2024-03-24 at 14 26 44" src="https://github.com/WeblateOrg/weblate/assets/295424/d65eb0d8-29e5-453c-b984-b80d05b9db83">
<img width="825" alt="Screenshot 2024-03-24 at 14 26 38" src="https://github.com/WeblateOrg/weblate/assets/295424/7362c5b8-b491-4b3f-8e0a-ebcc74d93b25">

### How do you run Weblate?

weblate.org service

**Comment by emartynov** [comment]
Might be false alarm since DeepL expects xliff file format 2.1 and weblate is exporting 1.1 version.

**Comment by emartynov** [comment]
Ok, further investigation found that xliff 2.x is not supported and looks like I should close this issue.

**Comment by nijel** [comment]
The `weblate-flags` attribute is indeed not part of the XLIFF standard, see https://docs.weblate.org/en/latest/formats.html#translation-flags

Why not use DeepL integration in Weblate? See https://docs.weblate.org/en/latest/admin/machine.html#deepl

**Comment by emartynov** [comment]
If I'm correct, DeepL integration is auto suggestion that showed when
someone in UI will try to provide translation for a key.

While I wanted to upload whole file and after correct things and upload all
translations to Weblate in one go.

**Comment by nijel** [comment]
It can also be used to translate everything, see https://docs.weblate.org/en/latest/admin/continuous.html#automatic-translation
