### ISSUE TITLE
Repository update with rebase does nothing

### ISSUE THREAD

**Issue by TobiGr** [WeblateOrg/weblate#11282]
### Describe the issue

Using the option "Update with rebase" on NewPipe's repository does nothing but reloading the page.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to https://hosted.weblate.org/projects/newpipe/#repository (as admin)
2. Commit pending changes
3. Ensure that there are missing commits in Weblate's repository by pushing new changes to the upstream repository. Ensure that there are no conflicts which prevent a rebase / merge
4. Go to update > update with rebase

### Expected behavior

Weblate's repository is rebased on top of the upstream repository and the frontend shows "0 missing commits".

### Screenshots

[simplescreenrecorder-2024-03-26_14.12.56.webm](https://github.com/WeblateOrg/weblate/assets/17365767/5bd0ea89-e259-4c4d-975a-0457f4147c5f)

### How do you run Weblate?

weblate.org service

### Weblate versions

hosted weblate on 26.03.2024

**Comment by nijel** [comment]
It did work fine at https://hosted.weblate.org/projects/newpipe/strings/#repository, but it should work at the project level as well.
