### ISSUE TITLE
Does Weblate support the TypeScript file format?

### ISSUE THREAD

**Issue by eamonzzz** [WeblateOrg/weblate#11298]
### Describe the problem

When I use weblate for translation, weblate does not recognize the content in the TypeScript file, which is formatted as follows: https://github.com/ant-design/ant-design-pro/blob/master/src/locales/en-US/pages.ts

### Describe the solution you would like

I'm stuck with the mi18n lang format file for parsing now, but that way comes with special symbols. Not getting the desired result.

**Comment by nijel** [comment]
No, but Weblate supports several JSON variants, see https://docs.weblate.org/en/latest/formats.html.

I am not convinced that using a programming language for translation files is a good idea because people then tend to use programming language features there, and it ends up breaking something.
