### ISSUE TITLE
Support translation of antifeatures for App store metadata format

### ISSUE THREAD

**Issue by paidforby** [WeblateOrg/weblate#11300]
### Describe the problem

I would like Weblate to be able to translate the F-Droid antifeatures included in my Fastlane metadata files. I've added the antifeature to the [/fastlane/metadata/android/en-US/antifeatures](https://gitlab.com/censorship-no/ceno-browser/-/tree/weblate-integration/fastlane/metadata/android/en-US/antifeatures?ref_type=heads) directory on the branch that is the source for my weblate components. But the txt file is not getting picked up by Weblate.

### Describe the solution you would like

I see that similar issues include, https://github.com/WeblateOrg/weblate/issues/1525 and https://github.com/WeblateOrg/weblate/issues/2725

And based on the [AppStoreParser](https://github.com/WeblateOrg/weblate/blob/main/weblate/formats/txt.py#L110) class, it makes sense that the `antifeatures` directory is not being picked up. Can you please add `('antifeatures/*.txt', 'max-length:500'),`? Maybe there is other F-Droid specific metadata files or directories that should be added? Or maybe there is a general solution that could recursively include any text files in any depth or subdirectory?

### Describe alternatives you have considered

I can manually add our translations of the antifeature since it is a short, single line or text, but it would be nice for anyone to review or translate it into a new language.

### Additional context

Thanks!

**Comment by nijel** [comment]
It can be definitely added. Is there some documentation of files which should be translated?
