### ISSUE TITLE
Got MonolingualTranslation alert when using bilingual translation files

### ISSUE THREAD

**Issue by tonton-kibo** [WeblateOrg/weblate#11315]
### Describe the problem
We are using CSV format bilingual translation files while weblate keep alerting that our components are monolingual.
The error message is "The translation component looks monolingual, but it is not set up to be. Please add a monolingual base language file in the component settings."

After tracing the source code, we found that the code causing this is at line 416~423 of weblate/trans/models/alert.py (checked on revision ae8b4db)

```python
        if translation:
            allunits = translation.unit_set
        else:
            allunits = component.source_translation.unit_set

        source_space = allunits.filter(source__contains=" ")
        target_space = allunits.filter(
            state__gte=STATE_TRANSLATED, target__contains=" "
        )
        return (
            not component.is_glossary
            and not component.template
            and allunits.count() > 3
            and not source_space.exists()
            and target_space.exists()
        )
```
I can't figure out why weblate needs to check `source_space` and `target_space` here to determine if the component is monolingual. 
Our source language uses CJK characters and do not use so-called `spaces`. However, our target language, English, does use spaces. So as a result, there exist `target_space` units and exists no `source_space` units, which leads to the MonolingualTranslation alert. But it doesn't mean the component is  monolingual.

### Describe the solution you would like
We can handle this problem by commenting out this check. We share this issue here in case someone meets the same problem.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Upload bilingual translation file whose source uses CJK characters and target language is English.

**Comment by nijel** [comment]
This indeed assumes that source is using whitespace to separate words, the code needs to be adjusted.
