### ISSUE TITLE
File upload in some languages

### ISSUE THREAD

**Issue by cdKannegiesser** [WeblateOrg/weblate#11338]
### Describe the issue

When using our self-hosted Weblate, we encountered the following problem: In one project we have texts which have the following structure:

- Example 1:
        This is a text example
- Example 2:
        This is a text example
- Example 3:
        This is a text Example

In this project, the texts are imported from a Git instance into the Weblate in XLIFF format. 

We now have users who work with Weblate to translate the texts, they use the file export and export the texts in Excel format, edit them and import them back again.

Now the following problem occurs, in some languages this export works without problems and in some languages the texts cannot be assigned, the following message appears:

![grafik](https://github.com/WeblateOrg/weblate/assets/129770199/c13885f5-37c2-4822-b4e5-45115d9fa229)

It does not matter whether the file has been edited or not. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

The texts of a specific component are exported in French (fr) as a file in Excel format.

If this file is now imported again, regardless of whether the file was previously edited or not, problems occur. The texts are recognized correctly in some languages, but not in others.

We have checked the source data but could not find any irregularities.

### How do you run Weblate?

Docker container

### Weblate versions

5.4.2

**Comment by nijel** [comment]
Might be related to https://github.com/WeblateOrg/weblate/issues/10790. Did you export the files in current Weblate version?
