### ISSUE TITLE
New translation via API should be translated only in default language

### ISSUE THREAD

**Issue by voplakal-lukas** [WeblateOrg/weblate#11342]
### Describe the problem

New translation could be created with `POST /api/translations/(string: project)/(string: component)/(string: language)/units/` endpoint (data bellow). I always use the default language (en) because I don't know the value of `target` for all languages. 

```
{
    "source": [
        "Test string API_1"
    ],
    "target": [
        "Test string API_1"
    ]
}
```
Translations are correctly created, however all languages have a translation filled in from the default language. 
<img width="1708" alt="Screenshot 2024-04-03 at 14 13 46" src="https://github.com/WeblateOrg/weblate/assets/36842017/5c2ef5a2-b9c3-4f82-bd1e-d412b71170e3">

### Describe the solution you would like

I would like to create a translation only for the default language, but leave the translation blank for other languages. Just like it works when you add new translation via UI.

**Comment by nijel** [comment]
What Weblate version do you use? How is your translation configured (especially if it is using monolingual or bilingual files)?

**Comment by voplakal-lukas** [comment]
> What Weblate version do you use? How is your translation configured (especially if it is using monolingual or bilingual files)?

Currently 5.4.2 and translations are in monolingual .po files.

**Comment by nijel** [comment]
Okay, it kind of behaves as expected: when the `target` is present, it is used as target for all strings. The missing bit is however to support not including the target and keeping strings not translated.
