### ISSUE TITLE
`wlc reset` always leads to 'Connection aborted'

### ISSUE THREAD

**Issue by rix0rrr** [WeblateOrg/weblate#11368]
### Describe the issue

In order to minimize the risk of merge conflicts after squash-merging Weblate PRs, our workflow looks like the following:

```
wlc pull
wlc commit
wlc push
wlc reset
```

This seems to mostly work fine (except of course if people translate in the window between where the PR is created and it is merged).

However, the `wlc reset` command structurally fails with:

```
Mon, 08 Apr 2024 06:12:52 GMT   wlc reset
Mon, 08 Apr 2024 06:17:36 GMT   Request failed: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

So this commands takes around 5 minutes to run, after which the TCP connection times out, which makes our workflow fail every day.

I've also noticed that clicking the `Reset` button on the website similarly never properly loads a response page after minutes of waiting, and we need to refresh.

Is this expected?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Run

```
wlc reset
```

On our project with ~12 components in a single ~800MB git repository.

### Expected behavior

`wlc reset` completes successfully

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
The operation is currently synchronous, so it can take considerable time to complete on larger projects.
