### ISSUE TITLE
The state of the string should be reverted too

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#11374]
### Describe the issue

Reverting a change in Weblate does not seem to revert the state of the string.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Revert a change that changes the state of the string in Weblate

### Expected behavior

The state of a string should be reverted too while the previous action changed it.

### Screenshots

Example: https://hosted.weblate.org/translate/aves/app-main/zh_Hans/?checksum=8298f1b6a21f6610
The state of the string should be reverted to Approved here.
![image](https://github.com/WeblateOrg/weblate/assets/49396421/c8867821-d0cd-40cc-b9ae-6673bcf7d114)
I have permission to review strings:
![image](https://github.com/WeblateOrg/weblate/assets/49396421/bf0f28f5-5b39-4db9-ae4b-db6923f2dc3f)

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 5.4.3

**Comment by nijel** [comment]
It does revert needs editing state, but it doesn't revert approved state:

https://github.com/WeblateOrg/weblate/blob/511272a0434249b3d69c56d6cb9e1230153b2262/weblate/trans/views/edit.py#L471

It was not intentional, but it makes sense to have approval as an explicit action.

**Comment by Geeyun-JY3** [comment]
?

**Comment by Geeyun-JY3** [comment]
@nijel Please reopen this issue. It is not fixed.

**Comment by Geeyun-JY3** [comment]
In addition, Weblate does not revert the Needs editing state either: https://hosted.weblate.org/translate/weblate/application/zh_Hans/?checksum=c234cbbcf7f12986#history
![image](https://github.com/WeblateOrg/weblate/assets/49396421/a855cc20-43ab-473d-974b-10fc8dc7f6e9)

**Comment by nijel** [comment]
Reverting brings the string to the state as was *after* the change you are clicking on. So if you revert to change where string was translated, it will be translated.
