### ISSUE TITLE
Cannot revert the approved strings

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#11373]
### Describe the issue

Cannot revert the approved strings even though the user has permission to review strings.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

0. Get permission to review the strings of a project
1. Revert an approved string

### Expected behavior

Able to revert the approved strings while the user has permission to review strings.

### Screenshots

Example: https://hosted.weblate.org/translate/f-droid/website/zh_Hans/?checksum=440af90d7078d5eb#history
![weblate_bug_cannot_revert_approved_string](https://github.com/WeblateOrg/weblate/assets/49396421/118c466f-9381-411d-b27d-15538c10725e)
![image](https://github.com/WeblateOrg/weblate/assets/49396421/9de16795-0c34-4a3f-9ac9-5fdc2d0677f4)

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 5.4.3

**Comment by nijel** [comment]
Reverting does revert to that translation, it does not revert that edit. So if you click on a change which matches the current translation, it does nothing.

I think there was a discussion somewhere how revert should behave, but I can't find it right now.

**Comment by nijel** [comment]
Reverting brings you to the state of the string *after* the change where you've clicked on revert.
