### ISSUE TITLE
XLIFF import does not add translated strings to weblate

### ISSUE THREAD

**Issue by eakkas** [WeblateOrg/weblate#1142]
### Steps to reproduce
1. Download XLIFF 1.2 for offline translation
2. Translate the file and upload it back
   3.
### Actual behaviour

File uploads but strings are not imported. I get this message - https://goo.gl/EKueLC
I experimented with a very simple file, downloaded the XLIFF and inserted some text to the first trans-unit's target node, uploaded it back and still get the same message.
### Expected behaviour

Translated strings should be imported
### Server configuration
- Weblate weblate-2.6
- Python 2.7.3
- Django 1.9
- six 1.10.0
- python-social-auth 0.2.13
- Translate Toolkit 2.0.0b2
- Whoosh 2.7.0
- Git 1.7.9.5
- Pillow (PIL) 1.1.7
- dateutil 2.4.2
- lxml 3.5.0
- django-crispy-forms 1.5.2
- compressor 1.6
- djangorestframework 3.3.3
- pytz 2016.4
- Database backends: django.db.backends.mysql
##

**Comment by nijel** [comment]
It's probably caused by missing approved="yes" in the XLIFF (see https://docs.weblate.org/en/latest/formats.html#xliff).

**Comment by rvanlaak** [comment]
What @eakkas maybe means is that new translation strings are not imported after translating offline. So, even if `approved` is missing they are not imported.

**Comment by Amiller-philips** [comment]
Our professional translator reports the same class of problem:

Description:
* download XLIFF
* translate either in MemoQ or Trados
* reimport
* expectation: 76 strings no change of which one is still untranslated,  2 strings  have new translations

For MemoQ, Weblate displays the following messages on upload, and no strings are changed
   Processed 78 strings from the uploaded files.
   There were no new strings in uploaded file!

Trados complains on Saving, that each trans-unit has no id,
and that the schema verification against urn:oasis:names:tc:xliff:document:1.2K_unit_id has failed.
On upload Weblate displays the following messages, and no strings are changed.
   Processed 78 strings from the uploaded files.
   There were no new strings in uploaded file!

XLIFFChecker reports the following on the XLIFF as downloaded from Weblate

Validating: C:\Users\Amiller\Downloads\citytouch-citytouch_mobileworkflowapp-de.xlf
 - XML file parsed.
 - XLIFF version: 1.1
 * XLIFF namespace not declared.
   > XLIFF namespace declaration added.
   > Document reloaded.
 - Validating against XML Schema.
 * Error while validating:
[Error] 5:55 cvc-complex-type.4: Attribute 'id' must appear on element 'trans-unit'.
Selected file is not valid XLIFF.

The weblate Server is on Ubuntu 16.04:
ubuntu@ip-172-31-10-160:~$ weblate list_versions
* Weblate 2.10
* Python 2.7.12
* Django 1.10.5
* six 1.10.0
* python-social-auth 0.2.21
* Translate Toolkit 2.0.0
* Whoosh 2.7.4
* defusedxml 0.4.1
* Git 2.7.4
* Pillow (PIL) 1.1.7
* dateutil 2.4.2
* lxml 3.5.0
* django-crispy-forms 1.6.1
* compressor 2.1
* djangorestframework 3.5.4
* pytz 2016.10
* pyuca N/A
* pyLibravatar N/A
* PyYAML 3.12
* Mercurial 3.7.3
* Database backends: django.db.backends.postgresql_psycopg2
ubuntu@ip-172-31-10-160:~$

Trados takes a translation unit like

      <trans-unit xml:space="preserve">
        <source>Fault Comments</source>
        <target></target>
      </trans-unit>

and emits 

      <trans-unit xml:space="preserve">
        <source>Fault Comments</source>
        <target state="needs-review-adaptation">Störungskommentare</target>
      </trans-unit>

Manually adding an id atttribute or approved=yes|no makes no difference.

If it makes any difference to the flow in the back end: The XLIFFs are generated from .resx  files from .Net.  Prevous tests with .po as source at least lead to some strings being found in hte XLIFF, thoug Singular Plural groups seem to fail silently

**Comment by nijel** [comment]
The import should work way better since aa4e17dd53925456df8389d295ba7d46dc8ec79e, but there still seem to be some glitches with xliff.
