### ISSUE TITLE
More optimization options

### ISSUE THREAD

**Issue by Blueberryy** [WeblateOrg/weblate#11430]
### Describe the problem

Every time you have to select Component then Language and choose Translate or Overview, it takes time to load stuff...

### Describe the solution you would like

It would be great if you could hide not needed languages and show only languages you need (language you speak and translate from)
Also maybe some Quick translate or Quick overview options so when you click at Component and you get straight to it without need to load stuff.

**Comment by nijel** [comment]
All your translations are shown on the dashboard so that you don't have to navigate to them.

But still, where exactly you see the performance issue and what Weblate version do you use?
