### ISSUE TITLE
Time to use `build` from `setuptools` instead of `distutils`?

### ISSUE THREAD

**Issue by abravalheri** [WeblateOrg/weblate#11460]
### Describe the problem

The following feature in setuptools has been deprecated for almost 2 years and is about to be removed:

https://github.com/pypa/setuptools/blob/1ed759173983656734c3606e9c97a348895e5e0c/setuptools/command/build.py#L13-L27

It might be a good idea to import `build` directly from setuptools for the following code:

https://github.com/WeblateOrg/weblate/blob/47f9f2870c4ed9fd5429eebfacc61d2267a5bb31/setup.py#L9
https://github.com/WeblateOrg/weblate/blob/47f9f2870c4ed9fd5429eebfacc61d2267a5bb31/setup.py#L51-L58

(`build` is available directly from setuptools, starting on version v62.4.0)

### Describe the solution you would like

Whenever possible, it might be a good idea to import from setuptools (and minimise imports to `distutils` to the minimum viable).

**Comment by SanjaySiddharth** [comment]
Hey Team ! I would like to work on this issue !
