### ISSUE TITLE
Had to disable Sentry when upgrading to Weblate 5.5

### ISSUE THREAD

**Issue by ldidry** [WeblateOrg/weblate#11487]
### Describe the issue

When upgrading weblate to 5.5, the `weblate migrate --noinput` command failed with the attached stacktrace.

I had those settings related to Sentry:
```
SENTRY_DSN = "https://user@sentry.example.org/3"
SENTRY_ENVIRONMENT = None
```

After replacing those settings with the following, it worked.
```
SENTRY_DSN = None
SENTRY_ENVIRONMENT = SITE_DOMAIN
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Have Weblate in 5.4 version
2. Use Sentry
3. Update to Weblate 5.5 while keeping the Sentry settings

### Expected behavior

It should not crash and should allow to use Sentry.

### Exception traceback

```pytb
Operations to perform:              
  Apply all migrations: accounts, addons, admin, auth, authtoken, checks, configuration, contenttypes, django_celery_beat, fonts, gitexport, glossary, lang, memory, metrics, screenshots, se
ssions, social_django, trans, utils, vcs, weblate_auth, wladmin
Traceback (most recent call last):                                                            
  File "/var/www/weblate/weblate-env/bin/weblate", line 8, in <module>                    
    sys.exit(main())                                                                          
             ^^^^^^                                                                           
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/weblate/runner.py", line 19, in main
    utility.execute()                         
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)                                                                                                                                  
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 303, in handle
    emit_pre_migrate_signal(
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/django/core/management/sql.py", line 32, in emit_pre_migrate_signal
    models.signals.pre_migrate.send(
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 187, in send
    sync_receivers, async_receivers = self._live_receivers(sender)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/sentry_sdk/integrations/django/signals_handlers.py", line 73, in _sentry_live_receivers
    receivers[idx] = sentry_receiver_wrapper(receiver)
    ~~~~~~~~~^^^^^
TypeError: 'tuple' object does not support item assignment
```

### How do you run Weblate?

PyPI module

### Weblate versions

 * Weblate: 5.5                                                                                                                                                                      [18/848]
 * Django: 5.0.4                      
 * siphashc: 2.3                                                                                                                                                                             
 * translate-toolkit: 3.12.2
 * lxml: 5.1.0                                                                                                                                                                               
 * Pillow: 10.1.0                   
 * nh3: 0.2.14                                                                                                                                                                               
 * python-dateutil: 2.8.2                                                                     
 * social-auth-core: 4.5.3                                                                    
 * social-auth-app-django: 5.4.0                                                                                                                                                             
 * django-crispy-forms: 2.1                                                                   
 * oauthlib: 3.2.2                                                                            
 * django-compressor: 4.4                                                                     
 * djangorestframework: 3.15.1                                                                                                                                                               
 * django-filter: 24.2                                                                        
 * django-appconf: 1.0.5                                                                      
 * user-agents: 2.2.0                                                                                                                                                                        
 * filelock: 3.12.4                       
 * rapidfuzz: 3.4.0                                                                                                                                                                          
 * openpyxl: 3.1.2                                                                            
 * celery: 5.3.5   
 * django-celery-beat: 2.6.0
 * kombu: 5.3.4                             
 * translation-finder: 2.15
 * weblate-language-data: 2024.3                                                              
 * html2text: 2024.2.26     
 * pycairo: 1.25.1                                                                            
 * PyGObject: 3.46.0
 * diff-match-patch: 20230430       
 * requests: 2.31.0                            
 * django-redis: 5.4.0
 * hiredis: 2.2.3                                                                             
 * sentry-sdk: 1.31.0                                                                         
 * Cython: 3.0.4                                                                              
 * misaka: 2.1.1                                                                              
 * GitPython: 3.1.40                           
 * borgbackup: 1.2.6                          
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.20.0                                                                                                                                                                    
 * python-redis-lock: 4.0.0    
 * charset-normalizer: 3.3.1 
 * Python: 3.11.2                     
 * Git: 2.39.2                             
 * psycopg: 3.1.12                                                                            
 * psycopg-binary: 3.1.12                                                                     
 * phply: 1.2.6
 * ruamel.yaml: 0.18.2

 * tesserocr: 2.6.2
 * boto3: 1.28.71
 * zeep: 4.2.1
 * aeidon: 1.13
 * iniparse: 0.5
 * Mercurial: 6.5.2
 * git-svn: 2.39.2
 * git-review: 2.3.1
 * PostgreSQL server: 15.6
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary) 
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8 
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 6.1.0-20-amd64 (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/fr/weblate-5.5/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/fr/weblate-5.5/admin/backup.html

System check identified 2 issues (1 silenced).
```

**Comment by nijel** [comment]
Have you tried upgrading `sentry-sdk`?

**Comment by ldidry** [comment]
I didn’t. I always upgrade Weblate with `pip install -U "Weblate[all]"` and never had to upgrade a dependency on my own.

Upgrading manually with `pip install sentry-sdk==1.45.0` fixed it. Thank you!
