### ISSUE TITLE
Components list stays empty in team creation dialog even after choosing a project

### ISSUE THREAD

**Issue by dleidert** [WeblateOrg/weblate#11536]
### Describe the issue

I am creating a team. That team is supposed to be limited to a specific project, a specific language, and specific components. However, even after successfully choosing a project, the components selection fields stay empty. I assume that the components of the selected projects should appear there, and it should be possible to select the components that users of the team should have access to.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Open the administrator view and go to "Teams" and  there to "Create new team". Now choose a name, the roles, and at least a project with multiple components. The components field will stay empty.

### Expected behavior

The components of the selected project(s) should appear and should be selectable.

### Screenshots

![Bildschirmfoto vom 2024-04-30 13-50-37](https://github.com/WeblateOrg/weblate/assets/14413364/c64de374-58fc-48b4-a39e-048744e22475)

The selected project has multiple components.

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.5.2
 * Django: 5.0.4
 * siphashc: 2.4.1
 * translate-toolkit: 3.13.0
 * lxml: 5.2.1
 * pillow: 10.3.0
 * nh3: 0.2.17
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.1
 * django-crispy-forms: 2.1
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.15.1
 * django-filter: 24.2
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.13.4
 * rapidfuzz: 3.8.1
 * openpyxl: 3.1.2
 * celery: 5.4.0
 * django-celery-beat: 2.6.0
 * kombu: 5.3.7
 * translation-finder: 2.16
 * weblate-language-data: 2024.4
 * html2text: 2024.2.26
 * pycairo: 1.26.0
 * PyGObject: 3.48.2
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.4.0
 * hiredis: 2.3.2
 * sentry-sdk: 1.45.0
 * Cython: 3.0.10
 * misaka: 2.1.1
 * GitPython: 3.1.43
 * borgbackup: 1.2.8
 * pyparsing: 3.1.2
 * ahocorasick_rs: 0.22.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * Python: 3.12.3
 * Git: 2.39.2
 * psycopg: 3.1.18
 * psycopg-binary: 3.1.18
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.6.3
 * boto3: 1.34.93
 * zeep: 4.2.1
 * aeidon: 1.14.1
 * iniparse: 0.5
 * mysqlclient: 2.2.4
 * Mercurial: 6.7.2
 * git-svn: 2.39.2
 * git-review: 2.4.0
 * PostgreSQL server: 16.2
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.office365.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 6.1.0-18-amd64 (x86_64)

### Weblate deploy checks

```shell
System check identified no issues (1 silenced).
```

**Comment by nijel** [comment]
"component lists" is something different than "components", so you most likely have none component lists (see also https://github.com/WeblateOrg/weblate/issues/7181 and related issues).

You can grant individual components access when creating teams within a project, not on the globally created teams.

**Comment by dleidert** [comment]
Thank you very much for your feedback. When I create a team inside a project, I can select the translation components the team members are supposed to have access to. So that is precisely what I was looking for. I have not yet understood the "Component list" feature, to be honest, though. But I gather that this is something very different, which is confusing, given the names of each feature containing "components". Maybe it would help to rephrase the features, or at least the titles in each dialog? If you do not agree, please feel free to close this issue.
