### ISSUE TITLE
Make development easier

### ISSUE THREAD

**Issue by max-wittig** [WeblateOrg/weblate#11547]
### Describe the problem

While trying to setup the development environment to tackle https://github.com/WeblateOrg/weblate/pull/11467, I noticed how difficult it is to setup the environment.

I ran into my dependency problems, as we don't have a dependency manager here so a virtualenv needs to be used with a specified version of Python.

And now I'm stuck on this issue, while running `weblate migrate`. I have no idea why it tries to open an LDAP connection on migrate. I'm familiar with Django setups, but this is a bit different.

```sh
django.db.utils.OperationalError: connection failed: could not initiate GSSAPI security context: Unspecified GSS failure.  Minor code may provide more information: Cannot find KDC for realm "AX001.MYCOMPANY.NET"
connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "weblate" does not exist
```

Then I thought, maybe let's just use the docker-compose setup for a simple fix and there I need to create `docker-compose.override.yml`.

I think this project would benefit from a zero-setup start just to develop it.

### Describe the solution you would like

a zero-config setup development environment

**Comment by nijel** [comment]
Have you tried https://docs.weblate.org/en/latest/contributing/start.html#running-weblate-locally-in-docker ?

**Comment by max-wittig** [comment]
Mhmm also the default `./rundev.sh` fails with `psql: error: connection to server at "database" (172.18.0.3), port 5432 failed: FATAL:  password authentication failed for user "weblate"`. This is not made for use on macOS I'm guessing

**Comment by max-wittig** [comment]
Any ideas?

**Comment by max-wittig** [comment]
I had to manually setup the DB. Ideally the dev setup should be zero config, so we can enable the people

```sql
CREATE USER weblate;
ALTER USER weblate WITH PASSWORD 'weblate';
GRANT USAGE ON SCHEMA public TO weblate;
CREATE DATABASE weblate;
ALTER DATABASE weblate OWNER TO weblate;
```

**Comment by nijel** [comment]
This really should be done by the PostgreSQL container during the initial startup. You can check its logs why it didn't.

It is supposed to be zero config, and we do verify that in CI: https://github.com/WeblateOrg/weblate/blob/main/.github/workflows/rundev.yml
