### ISSUE TITLE
Add component filtering based on key

### ISSUE THREAD

**Issue by LeoColman** [WeblateOrg/weblate#11562]
### Describe the problem

Even though I can

- Set the string to read-only
- Fastlane changelogs are lowest-priority shown to translators

I still have some problems I can't address:

- Read-only strings won't allow translators willing to translate changelogs to do it, reducing overall translatability
- Bundling both in the same component doesn't allow vision of true translation of the app -- Changelogs are not exactly part of the app and shouldn't count to the % translated of the language
- Changelog files (if left write-enabled) taint translation percentage of more-valuable app details

### Describe the solution you would like

I'm not sure what exactly to suggest, but the only thing I can think of is getting this screen:
![image](https://github.com/WeblateOrg/weblate/assets/1577251/8e12eae1-9ae2-496e-8280-f31dff21d1b8)

and adding an exclusion (i.e. "Exclude files matching fastlane/metadata/android/changelogs/*") filter, which would mean filtering depending on key. It should probably behave similarly to how current **Languages** filter work.

### Describe alternatives you have considered

- Using the bulk edit addon

As explained above, this is more of a workaround than a final solution to the problem.

### Additional context

Initially discussed on 
- https://github.com/WeblateOrg/weblate/discussions/7917
- https://github.com/WeblateOrg/weblate/discussions/11523

**Comment by nijel** [comment]
Just found out https://github.com/WeblateOrg/weblate/issues/8084, but closing that in favor of this as the description is way better here.

**Comment by nijel** [comment]
To implement this:

* Add *Key filter` field to the Component model
  * Add validation to force it empty for bilingual files which do not use keys
  * Include it in component creation forms
  * Include it in settings form
  * Include it in the API serialization
  * Add documentation for the field with some examples for the filters
* Implement actual filtering in `Translation.check_sync`
* Add tests to see the filtering is applied
  * Initial creation of a component with a filter should filter out strings
  * Adding a filter to an existing component should remove filtered out strings
  * Removing a filter from existing component should bring back filtered out strings
