### ISSUE TITLE
Translations not propagated on file uploads

### ISSUE THREAD

**Issue by joubu** [WeblateOrg/weblate#11599]
### Describe the issue

I have uploaded a .po file for a given component that is supposed to propagate the changes, but other components didn't get their translations updated.
See below, I have uploaded the file for "main" and I as expecting the other versions to be updated as well.
Is that because the translation was fuzzy before the upload?

![image](https://github.com/WeblateOrg/weblate/assets/671757/2f24c5bb-201f-4d82-bf77-702c90ac37d9)

I found this commit https://github.com/WeblateOrg/weblate/commit/8d7edd7688ee518cd4684ff51befc2c3142ff0af that states that it should work.

Note that comment might need adjustments  `weblate/trans/models/translation.py:964             # We intentionally avoid propagating:`

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Have components configured for translation propagation and upload a file.

### How do you run Weblate?

Docker container

### Weblate versions

5.5.4-dev

**Comment by joubu** [comment]
Update: I actually noticed later that the update didn't work at all when using the UI. It worked (without the propagation) using "wlc upload".

The UI timed out and it seems that the job has never been processed (or enqueued?).

**Comment by nijel** [comment]
It is supposed to propagate. Without further details, it is impossible to tell what happened.

- Maybe the string was updated after that?
- Permission issues? 
- Component was locked?
- CLA not agreed (if in place)?

**Comment by joubu** [comment]
On this link you can see that "main" and "23.11" have been updated (23.11 was not before a second "wlc upload" for this specific version)
https://translate.koha-community.org/translate/koha/main/staff-prog/ar_ARAB/?checksum=8134165b32931905

23.05 and 22.11 are still using the old translation.

"Allow translation propagation" is turned on for all of them.

>     * Maybe the string was updated after that?

Nope.

>     * Permission issues?

No. And wlc uses a correct API key as 23.11 has been updated on the second run.

>     * Component was locked?

No components were locked.

>     * CLA not agreed (if in place)?

Not in place.

The component "staff-prog" is quite big and took hours to finish (at least to display the % progress).

I can eventually enable a debug mode and try again if you think it could be helpful.
I have looked at the docker logs output but haven't found anything useful.
```
 gunicorn stderr | [2024-05-10 07:08:25,313: INFO/2125] koha/23-11/staff-prog/ar_ARAB: committed ['/app/data/vcs/koha/23-11/installer/ar-Arab-staff-prog.po'] as "[hidden name]." <hiden email address]>[
 gunicorn stderr | [2024-05-10 07:08:28,348: INFO/2125] koha/23-11/staff-prog/ar_ARAB: processing ar-Arab-staff-prog.po, content changed, 10925 strings
```

**Comment by nijel** [comment]
I didn't notice the different behavior when using API or UI. The code used for upload is the same for both, so that doesn't explain the behavior. The only reason I can think of is that that component was locked at that point and that made Weblate skip the propagation there.
