### ISSUE TITLE
"Download translations as CSV in a ZIP file" is too slow to time out

### ISSUE THREAD

**Issue by Akemi-Madoka** [WeblateOrg/weblate#11592]
### Describe the issue

I have set up Weblate on a server using Docker and successfully uploaded our project to it. However, when we tried to test the download of the translation results by clicking 'Files' -> 'Download translations as CSV in a ZIP file', it took a considerable amount of time, and the process failed due to a timeout without success.

When we checked the 'Performance report', we noticed that the 'notify' queue in 'Celery queues' was exceptionally large and decreased slowly. Could this be the cause of the issue? Should we just wait for the server to clear it? I will provide some screenshots for your reference.
![C1](https://github.com/WeblateOrg/weblate/assets/38621390/254bfde4-57a3-4dbf-b64f-3b8768606c69)
![C2](https://github.com/WeblateOrg/weblate/assets/38621390/69dc71e6-57fa-46e8-81ea-bbe8a728c089)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1.Upload our project.
2.Wait for all loading prompts under the '/projects/*' path to finish.
3.Click the 'Download translations as CSV in a ZIP file' button.
4.time out

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
Indeed, it can take considerable time as it needs to fetch all the strings from the database and generate CVS file for each translation. Notify queue is unrelated, it's probably caused by many new strings added, Weblate 5.5.3 should make this slightly better.

**Comment by Akemi-Madoka** [comment]
> Indeed, it can take considerable time as it needs to fetch all the strings from the database and generate CVS file for each translation. Notify queue is unrelated, it's probably caused by many new strings added, Weblate 5.5.3 should make this slightly better.

We are currently using Weblate 5.5.3. We eventually extended nginx's request timeout to 300 seconds, which successfully allowed the button to download the correct file. Perhaps in the future, a caching feature could be added to this type of functionality?

**Comment by nijel** [comment]
I find it quite unlikely that cache would have many hits here. The download is not used that often and the translations do change.
