### ISSUE TITLE
MISCONF Redis

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#11614]
### Describe the issue

After this error, celery stops processing jobs. Maybe there is more useful information in sentry.
```

Request Method: | GET
-- | --
https://weblate.eso-spolszczenie.eu/
5.0.5
ResponseError
MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
/app/venv/lib/python3.12/site-packages/redis/connection.py, line 536, in read_response
weblate.trans.views.dashboard.home
/app/venv/bin/python
3.12.3
['/',  '/',  '/app/venv/bin',  '/usr/local/lib/python312.zip',  '/usr/local/lib/python3.12',  '/usr/local/lib/python3.12/lib-dynload',  '/app/venv/lib/python3.12/site-packages',  '/app/data/python']
Fri, 10 May 2024 04:02:03 +0200
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1) Receives error notification via email
2) Celery stops processing jobs.

### How do you run Weblate?

weblate.org service

### Weblate versions

<html>
<body>

5.5.4-dev — 5067ae4cb050c601f6fb2fa396e19832931efd5e
--

</body>
</html>5.5.4-dev — [5067ae4cb050c601f6fb2fa396e19832931efd5e](https://github.com/WeblateOrg/weblate/commits/5067ae4cb050c601f6fb2fa396e19832931efd5e)

### Additional context

docker compose stop and docker compose up temporarily solve the problem

**Comment by nijel** [comment]
Did you check the Redis logs as the error suggests? Maybe the disk is full?

**Comment by tomkolp** [comment]
Where can I find the redis logs in Docker? I have about 5 GB of free space.

**Comment by nijel** [comment]
`docker compose logs cache`

**Comment by tomkolp** [comment]
I will check the phone logs if the problem reoccurs. Currently, I only have logs available after restarting the container.

**Comment by nijel** [comment]
Redis does dump it's content regularly and in that time it needs double disk space, check content of its volume to see how much it uses.

**Comment by tomkolp** [comment]
There was no mistake after the seat was cleared tonight.  I think that was a real problem.
