### ISSUE TITLE
Repository reset will not fix merge conflicts

### ISSUE THREAD

**Issue by DerHerrGammler** [WeblateOrg/weblate#11613]
### Describe the issue

I got some merge conflicts in my project and since i had no changes in weblate I tried a reset of the repository. This did nothing and my projects still has some merge conflicts.

I also tried to add the reporitory again as new component but i also got a merge conflict on that new and freshly initialzed component.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Add new component
2. Press reset
3. voila merge conflict

### Expected behavior

If I completly reset a repository there should not be a merge conflict

### How do you run Weblate?

Docker container

### Weblate versions

weblate@3cd6a17078b4:/$ weblate list_versions
 * Weblate: 5.5.3
 * Django: 5.0.4
 * siphashc: 2.4.1
 * translate-toolkit: 3.13.0
 * lxml: 5.2.1
 * pillow: 10.3.0
 * nh3: 0.2.17
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.1
 * django-crispy-forms: 2.1
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.15.1
 * django-filter: 24.2
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.14.0
 * rapidfuzz: 3.9.0
 * openpyxl: 3.1.2
 * celery: 5.4.0
 * django-celery-beat: 2.6.0
 * kombu: 5.3.7
 * translation-finder: 2.16
 * weblate-language-data: 2024.5
 * html2text: 2024.2.26
 * pycairo: 1.26.0
 * PyGObject: 3.48.2
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.4.0
 * hiredis: 2.3.2
 * sentry-sdk: 1.45.0
 * Cython: 3.0.10
 * misaka: 2.1.1
 * GitPython: 3.1.43
 * borgbackup: 1.2.8
 * pyparsing: 3.1.2
 * ahocorasick_rs: 0.22.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * Python: 3.12.3
 * Git: 2.39.2
 * psycopg: 3.1.18
 * psycopg-binary: 3.1.18
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.7.0
 * boto3: 1.34.97
 * zeep: 4.2.1
 * aeidon: 1.14.1
 * iniparse: 0.5
 * mysqlclient: 2.2.4
 * Mercurial: 6.7.2
 * git-svn: 2.39.2
 * git-review: 2.4.0
 * PostgreSQL server: 15.1
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: canis.herold.solutions
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.10.0-21-amd64 (x86_64)

**Comment by DerHerrGammler** [comment]
It seems to be a problem in the `weblate/weblate:latest` docker image since I just downgraded to `weblate/weblate:5.5.0.1` and there the reset button works just fine

**Comment by nijel** [comment]
I've just tried it, and it works for me.

Did you get any error? Did you check the server logs?

**Comment by DerHerrGammler** [comment]
The only error that I receive in the server logs is

```
gunicorn stderr | [2024-05-10 13:56:54,098: WARNING/447] Could check merge needed: RepositoryError: fatal: bad revision 'origin/weblate-translations..'
gunicorn stderr |  (128)
```
