### ISSUE TITLE
Use git sparse checkout to get only needed files from git repo

### ISSUE THREAD

**Issue by vivpez** [WeblateOrg/weblate#1161]
Hello,
In my company we would like to use weblate to communicate translation tasks to an outside translation company, but we have been faced with a security issue : the weblate server needs to be connected to the outside world, but it keeps the whole contents of our git repositories.
So if somebody hacks the weblate server, he has access to all our sources. 

Have you considered using git sparse-checkout to download only the folders containing the translation files ? it would make the checkout much faster ...

Thanks by advance
##

**Comment by nijel** [comment]
Indeed that sounds like an useful addition.

**Comment by nijel** [comment]
On the other side, this will really not help security - attacker can change sparse checkout to full one. So for security I rather suggest keeping translations in separate repository and use submodule to embed it into the code.

**Comment by nijel** [comment]
I don't think this is worth implementation:

- security wise it really does not provide any benefits as sparse checkout does still have all the data in git database, it's just not in the working copy
- the implementation would be quite complex (would have to properly handle linked components and additional commit files)
- the disk space consumption is probably not an issue these days

I've rather added documentation how to use submodules for additional security: https://docs.weblate.org/en/latest/faq.html#how-can-i-limit-weblate-access-to-translations-only-without-exposing-source-code-to-it
