### ISSUE TITLE
More consistent line breaks in exported po files

### ISSUE THREAD

**Issue by Cerno-b** [WeblateOrg/weblate#11615]
### Describe the problem

When I export a po file in Weblate and edit it using an external editor like poedit, I get inconsistent line breaks, which makes merging and comparing changes from weblate with the exported file nearly impossible. Poedit allows setting different line break values, but no matter which value I use, I can't get it to align with the weblate output.

I am currently working on https://hosted.weblate.org/projects/godot-engine/godot-class-reference/de/

### Describe the solution you would like

I'd like weblate to create po files on export that are identical (down to the line breaks) to the files generated by the most popular po file editors (e.g. poedit).

### Describe alternatives you have considered

A workaround would be to always pass the downloaded files through poedit before attempting a merge, but I was hoping for a more consistent output from weblate directly.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/16470072/d2f1626a-448e-4ae1-a9ae-dce0c6f2c044)

### Additional context

Here are some observations I made, and I can't get a grasp on the logic behind where line breaks occur and where they are prevented:

So generally weblate seems to target a maximum line length of 80, but I have also (very rarely) seen longer lines, like these:

85: `"permission#BIND_NOTIFICATION_LISTENER_SERVICE]BIND_NOTIFICATION_LISTENER_SERVICE[/"`
81: `"print(ts.string_get_word_breaks(\"Test ❤️‍🔥 Test\")) # Prints [1, 2, 3, 4, 5, "`

The first one might not have found any character at which a break is allowed, and the second one might be confused with the unicode emojis.

These corner cases aside, Weblate seems to try to avoid breaking up words, but the rules seem inconsistent:

Here, breaking after the "[" is allowed (top line length: 76):

```
"Konvertiert [param what] in [param type] auf die bestmögliche Weise. Der ["
"param type] verwendet die [enum Variant.Type]-Werte.\n"
```

But here it is not, even though it would still fit into the top line (length: 77):

```
"- Eine von [Object] abgeleitete Klasse, die in [ClassDB] existiert, z. B. "
"[Node].\n"
```

Sometimes I even get a forced break inside a word (here: "erhöht"), even though there is a space before the word that could have been used as the break. Also, the line like this is only 79 characters long, so there would still be space for the "h". Maybe the ö is represented as unicode and weblate is allowed to break after unicode characters?

```
"[code]range(b: int, n: int, s: int)[/code]: Beginnt bei [code]b[/code], erhö"
"ht/verringert sich in Schritten von [code]s[/code] und endet [i]vor[/i] "
```

I could try and provide more example if that helps. 

It would be nice if we could get po files that are more consistent.

**Comment by nijel** [comment]
Indeed the implementation in translate-toolkit and gettext do differ. I think I've posted some summary years ago on some translate-toolkit issue, but I can't find it right now.

**Comment by Cerno-b** [comment]
Thanks, will do.

**Comment by Cerno-b** [comment]
Posted it as an issue here: https://github.com/translate/translate/issues/5251

**Comment by nijel** [comment]
Closing this now as there is nothing to be done in Weblate to fix this.
