### ISSUE TITLE
Is there any plan to support setting labels for units through the API?

### ISSUE THREAD

**Issue by dxdx123** [WeblateOrg/weblate#11621]
### Describe the problem

Is there any plan to support setting labels for units through the API?

### Describe the solution you would like

In my projects, I often need to mark a new batch of sources. This will be very useful for me to track the translation content of the current batch in the subsequent process. Is there any plan to support setting labels for units through the API?

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/14290268/fe9c7b6a-0230-4a89-9fca-a112599e3bcb)

**Comment by nijel** [comment]
It is already there on the unit endpoint: https://docs.weblate.org/en/latest/api.html#patch--api-units-(int-id)- 

Just the documentation is wrong in the direction of the parameter, I will fix it.

**Comment by dxdx123** [comment]
The API needs to pass in the unit id. When accessing from the outside, I only have the unit key.

**Comment by nijel** [comment]
You can use search using `q` parameter (same query strings as in UI): https://docs.weblate.org/en/latest/api.html#get--api-translations-(string-project)-(string-component)-(string-language)-units-
