### ISSUE TITLE
"strings needing action" doesn't actually count all strings needing action

### ISSUE THREAD

**Issue by matejcik** [WeblateOrg/weblate#1163]
Notably, the number does not include strings that are translated but have failing checks.

Also, for our purposes, we need to count strings with suggestions as "for review"; this will probably change if we implement a proper review workflow.

I propose counting strings with failing checks into "strings needing action".

Suggestions (and possibly comments) are trickier: the checklist item doesn't differentiate between untranslated and translated, which makes it impossible to get an exact number and wordcount of "strings needing work" for people who need or want that. OTOH, counting them in "strings needing action" would annoy people who don't care about suggestions on already translated strings.

At this point, i'm thinking of implementing a "Clean strings" checklist item, in addition to "Translated strings", and possibly a corresponding "Dirty strings" which is `total - clean`
##

**Comment by dg0yt** [comment]
Not all strings with failing checks are needing action. Sometimes a particular translation is failing a check and still valid, e.g. 
- unchanged translation: "Magenta" can have a unchanged translation in some langages.
- final punctuation: The source string ends in "!" but the translation is to use "." (maybe with a request to change the source string).

In these cases it would be helpful to add a flag just for particular languages (maybe something like 'ignore-same:de,fr'). But I guess this should be raised as another issue.

**Comment by matejcik** [comment]
isn't there an option to clear the failing checks for such purposes?

**Comment by dg0yt** [comment]
I don't know what you mean by "clear". I know that I can set flags on the source string. These flags apply to all languages which is not always what I want (cf. my previous comment).

**Comment by nijel** [comment]
You can ignore the specific failing check by clicking on the X at the check, there is even keyboard shortcut for that - `Alt+I` and then the shown digit:

![page-shot-2017-5-11 androbd obd data descriptions - german](https://cloud.githubusercontent.com/assets/212189/25958011/e28518be-366f-11e7-84ca-0af8ec77e38f.png)

**Comment by comradekingu** [comment]
Ignored checks is an action needed, with possible further action needed in source.

The "needs editing" checkbox should always be available for source language too, so that the "needs editing" for any component language only tracks the component language browsed.
