### ISSUE TITLE
Ignore translatable=false Android string resources when "Add missing languages" is enabled

### ISSUE THREAD

**Issue by vinaygopinath** [WeblateOrg/weblate#11648]
### Describe the issue

In an Android project with English as the source language and the "Missing languages" add-on enabled, the string resource files of other languages contain string resources such as
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string translatable="false" name="some_untranslatable_string_resource"></string>
    <string translatable="false" name="some_other_untranslatable_string_resource"></string>
</resources>
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Add a new Android string resource with the attribute "translatable" set to `false`

### Expected behavior

Given that the string resource is clearly marked as not translatable, the "Missing languages" add-on should ignore creating string resources in other languages.

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
Why do you have that file in Weblate if it contains only non-translatable strings? Once you have it imported into Weblate, the add-on applies, no matter whether the file is currently empty or not.

**Comment by vinaygopinath** [comment]
The file does not contain only untranslatable strings. It's only a few of them that have the `translatable` attribute.

I'd prefer to define them as string resources even if they're currently not translatable, to leave open the possibility of translating them later.
