### ISSUE TITLE
Unable to select any filter option

### ISSUE THREAD

**Issue by mmospanenko** [WeblateOrg/weblate#11643]
### Describe the issue

Can't choose any option from filter builder - no reaction.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to any project/module page
2. Try to build filters

### Expected behavior

Selected option accepted

### Screenshots

<img width="304" alt="image" src="https://github.com/WeblateOrg/weblate/assets/2766211/5bfdc662-af93-4dcb-b2de-0b07c081720b">
<img width="721" alt="image" src="https://github.com/WeblateOrg/weblate/assets/2766211/227201ec-83ce-4317-a5ce-362237460994">

### How do you run Weblate?

Docker container

### Weblate versions

5.5.5.1

### Weblate deploy checks

```shell
root@srv1-host /s/weblate# docker compose exec --user weblate weblate weblate check --deploy
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.5.5/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.5.5/admin/backup.html

System check identified 5 issues (1 silenced).
```

### Additional context

OS Ubuntu server arm64, Traefik as reverse proxy, no any errors in console. Browser Chrome. Seems UI issue

**Comment by nijel** [comment]
The text is inserted, but it is not visible. Once you type something into the form, it will appear.

**Comment by mmospanenko** [comment]
<img width="338" alt="image" src="https://github.com/WeblateOrg/weblate/assets/2766211/d283cc28-efde-437b-ad64-f2b001818bee">
text in field yes, invisible, tried to copy and it was there) but how abut second select, it was fixed?

**Comment by nijel** [comment]
You need to type text and press enter in those.

**Comment by mmospanenko** [comment]
<img width="327" alt="image" src="https://github.com/WeblateOrg/weblate/assets/2766211/3767b5ba-f8e3-47bd-9a7c-d10a4674fef1">
<img width="506" alt="image" src="https://github.com/WeblateOrg/weblate/assets/2766211/699a2c2e-b977-4a67-9432-e63331c8d13d">

oh, I see. Select without changes (UI issue) but string inserts. Thanks
