### ISSUE TITLE
Generate MO files doesn't include fuzzy translation even with option set

### ISSUE THREAD

**Issue by lukavia** [WeblateOrg/weblate#11656]
### Describe the issue

I've used google translate to translate strings in our installation and marked them as 'needs editing'. 
I've discovered that in the .mo files those strings are missing, where as in the po files are there. 
I've enabled the option in the addon configuration: 'Include strings needing editing' and then tried Synchronize, but the strings are still missing from the mo files. 
If I remove the check 'needs editing' on a string, then it gets included in the mo file, but if I check it again then the string is again removed from the .mo files.

I've discovered the problem with version 5.3.4 and upgraded to 5.5.5 and then repeat all the steps described above, but the result is still the same.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Install Generate mo addon
2. Set 'Include strings needing editing'
3. Translate a string as needed editing. 
4. Check or download the .mo file

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/1588312/453d16a7-c3f8-4d67-956d-6a52ba699db5)
![image](https://github.com/WeblateOrg/weblate/assets/1588312/57a04380-5397-42ed-918b-f4b65aa46d37)
![image](https://github.com/WeblateOrg/weblate/assets/1588312/35e1948b-6864-482d-af70-d494f7bb0866)
![image](https://github.com/WeblateOrg/weblate/assets/1588312/fa566029-5408-4fd6-9578-350108ae510d)

### How do you run Weblate?

Other

### Weblate versions

(weblate-env) weblate@tr:~$ weblate list_versions
 * Weblate: 5.5.5
 * Django: 5.0.6
 * siphashc: 2.4.1
 * translate-toolkit: 3.13.0
 * lxml: 5.2.2
 * pillow: 10.3.0
 * nh3: 0.2.17
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.1
 * django-crispy-forms: 2.1
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.15.1
 * django-filter: 24.2
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.14.0
 * rapidfuzz: 3.9.0
 * openpyxl: 3.1.2
 * celery: 5.4.0
 * django-celery-beat: 2.6.0
 * kombu: 5.3.7
 * translation-finder: 2.16
 * weblate-language-data: 2024.5
 * html2text: 2024.2.26
 * pycairo: 1.26.0
 * PyGObject: 3.48.2
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.4.0
 * hiredis: 2.3.2
 * sentry-sdk: 1.45.0
 * Cython: 3.0.10
 * misaka: 2.1.1
 * GitPython: 3.1.43
 * borgbackup: 1.2.8
 * pyparsing: 3.1.2
 * ahocorasick_rs: 0.22.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * Python: 3.11.2
 * Git: 2.39.2
 * psycopg: 3.1.19
 * psycopg-binary: 3.1.19
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.7.0
 * boto3: 1.34.105
 * aeidon: 1.14.1
 * iniparse: 0.5
 * Mercurial: 6.7.3
 * git-svn: 2.39.2
 * git-review: 2.4.0
 * PostgreSQL server: 13.14
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 6.1.0-21-amd64 (x86_64)

**Comment by nijel** [comment]
That's true, such strings are not included because this is consistent with what `msgfmt` does.

**Comment by lukavia** [comment]
What is the meaning of the setting then? 
One would expect that if there is a setting in weblate called "'Include strings needing editing" changing the setting would include those strings, but it turns out the settings doesn't change anything. 
`msgfmt` has an option ` -f, --use-fuzzy             use fuzzy entries in output` and one would expect it's the same in weblate. 

In addition if you look at the code it would seem that it should work: https://github.com/WeblateOrg/weblate/blob/f2c7a4977c73a470561eafe354879046f80a702f/weblate/addons/gettext.py#L36 
However for some reason it doesn't. I've tried to change the if statement there to be always true and other tricks but is seams that translation parameter just doesn't have those strings loaded in the object. 

My particular scenario is simple. I want to use google translate and release the translation ASAP cause they are good enough most of the time, but still have the team of translators go over them and confirm or fix them as needed. 

Another argument I could think of is that the fuzzy strings are indeed included in the po files, so it is strange to not be able to include them in the mo files. 

To be clear. My bug report is that the setting "Include strings needing editing" that is already in weblate and is documented doesn't do what it seas it would do. Not that I claim that is a new functionality to be added in weblate.

**Comment by nijel** [comment]
You are confusing two things:

* `Generate MO files` add-on saves the file to the repository, and it honors the configuration
* The converted download generates MO file on the fly
