### ISSUE TITLE
Glossary function not working

### ISSUE THREAD

**Issue by javierlinera87** [WeblateOrg/weblate#1168]
### Steps to reproduce
1. Add new word in the glossary
2. Go to translate a string that contains this word
### Actual behaviour

In the glossary tab says "No related strings were found in the glossary"
### Expected behaviour

It should suggest the translation that I previously entered in the glossary
### Server configuration

our Weblate (2.6 Version) is installed on an Ubuntu 16.04 system and that we're using a MySQL (Percona) database
##

**Comment by nijel** [comment]
Do you see that for every target language or only some of them?

**Comment by javierlinera87** [comment]
Hi Nijel. We only tried with Russian and Spanish. Thanks for your help :)

**Comment by nijel** [comment]
Hmm, strange, it works fine on Hosted Weblate: https://hosted.weblate.org/translate/weblate/master/es/?q=hook

Is it with all words or only some of them?

**Comment by javierlinera87** [comment]
I see, it works there. 
In my case it does not work with any word, I already tried with 2 or 3 different examples and none worked. Sometimes with a single word, sometimes with a string of words, but it never worked for me.

**Comment by nijel** [comment]
What version of Whoosh are you using (it's used for tokenizing the string)?

**Comment by javierlinera87** [comment]
We use the standard packaged version of whoosh. That's version 2.7.0. The one that comes with Ubuntu 16.04.

**Comment by javierlinera87** [comment]
If you have more questions, please don´t hesitate to ask. We are looking forward to make use of this glossary function. Many thanks in advance!

**Comment by nijel** [comment]
I really lack idea how to debug this. Looking at the code, single word entries should work just fine. Multiple word ones will be broken in most cases.

**Comment by javierlinera87** [comment]
Thanks! I tried again, and now it works for single word entries. Well, that´s something! :)
I´m pretty sure that it didn´t work before, even with just single word entries.
What do you mean that multiple word ones will be broken in most cases?
Is there some hope for multiple word entries or should we forget about it?

**Comment by nijel** [comment]
It's definitely bug which will be fixed.

**Comment by javierlinera87** [comment]
That´s wonderful, thank you and best regards.

**Comment by mattscott** [comment]
Can I confirm that Glossary entries with multiple words are not identified properly in source text?

**Comment by Fjolnir-Dvorak** [comment]
hmm. Would you open that issue again, please? I can confirm this is not working for multiple words in the base language.
Example:
1. Add "Death Mode" -> "Todesmodus" to the glossary
2. Go to a key with the default text "Death Mode". It will have no glossar entry.

**Comment by burner1024** [comment]
Same problem with multiple words, english-russian transation, weblate 2.12.

**Comment by Fjolnir-Dvorak** [comment]
Thank youi nijel. I will test it soon and report with examples if anything goes wrong.

**Comment by Saturnyn** [comment]
Hi sorry for commenting on an old issue, but I have noticed the same issue on my project: I have "No related strings found in the glossary." on the string "Save in Photos" while I have a "Photos" entry in the glossary.

> Hmm, strange, it works fine on Hosted Weblate: https://hosted.weblate.org/translate/weblate/master/es/?q=hook

I noticed that the example quoted above does not seem to work either. If I understand correctly, the word "hook" should appear in the glossary section, but it doesn't.

Is it possible that the feature is broken in the latest versions ? I am using weblate 4.15.

**Comment by nijel** [comment]
The link has changed meanwhile, the string is now at https://hosted.weblate.org/translate/weblate/application/es/?checksum=258b6d8e048ff4cf. Anyway, if you observe an issue after a few years, it is always a good idea to start with a fresh report.

**Comment by Saturnyn** [comment]
Thanks for the link, it helped me understand the problem I had: the glossary words will only be displayed on translated languages, not on the source language.
So it does work, sorry for the trouble, and I'll make sure to open a new issue next time :)
