### ISSUE TITLE
Cannot reuse e-mail for second account

### ISSUE THREAD

**Issue by Ricky-Tigg** [WeblateOrg/weblate#11711]
### Describe the issue

Current states

- Logged in to my GitHub account
- Authorized OAuth application to said account:  _Hosted Weblate_ owned by _WeblateOrg_ .  permission: _**grant access to user e-mail addresses (read-only)**_.

Messages triggered in https://hosted.weblate.org/accounts/login/
- "Could not complete registration. The supplied e-mail address is already in use for another account."
- "Please check if you have already registered an account. You can also request a new password, if you have lost your credentials."

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

In page https://hosted.weblate.org/accounts/login/?next=/accounts/login/

![Screenshot 2024-05-25 143456](https://github.com/WeblateOrg/weblate/assets/26058215/d50bc364-a12f-498e-ae98-c60bebe4c22e)

Under _Sign in with:_; click account name accordingly, thus _GitHub_.

_Note_: fields for _Username or e-mail_ and _Password_ left empty, thus _Sign in_ not clicked.

### Expected behavior

Sign in to take effect

### How do you run Weblate?

weblate.org service

### Weblate versions

_Weblate not installed_

As already mentionned, interface is  https://hosted.weblate.org/accounts/login/?next=/accounts/login/; I understand that matches the option _weblate.org service_ for _How do you run Weblate?_.

**Comment by nijel** [comment]
The email you have on GitHub is already registered in Weblate, aren't the error messages clear?

**Comment by nijel** [comment]
> Knowing why it was worth going to the trouble of making an account e-mail in use elsewhere a problem, however, is what mattered.

There can be a single account for an e-mail in Weblate. If there is an existing account with the same e-mail, another one cannot be created.
