### ISSUE TITLE
Add option for sorting in case-sensitive order to add-on "Format the Java properties file"

### ISSUE THREAD

**Issue by HaaiHenkie** [WeblateOrg/weblate#11714]
### Describe the problem

In my repository I sort the strings in the Java properties files by their key in a case-sensitive order. I noticed that newly translated strings are appended to the end of the properties file. That is why I tried the add-on "Format the Java properties file" which sorts the strings. However it is doing that in a case-insensitive order. This is giving a lot of difference to process when merging the new translations into my repository. So for the moment I am better of not using the add-on "Format the Java properties file".

### Describe the solution you would like

I would like the add-on "Format the Java properties file" to have a configuration option to sort the entries in a case-sensitive order.

### Describe alternatives you have considered

Maybe the properties files for the translations could stick to the key order of the monolingual base properties file. I think that is more difficult to implement.

### Additional context

Not relevant to me, but you could add other common format options like "Align properties in columns" and "Insert space around key-value delimiter"

**Comment by nijel** [comment]
Indeed, the current implementation is case-insensitive, adding an option to make it case-sensitive should be pretty easy. Related code is here: https://github.com/WeblateOrg/weblate/blob/main/weblate/addons/properties.py

**Comment by harriebird** [comment]
Hi guys, check my PR  #11933 for this issue.
