### ISSUE TITLE
Ability to generate contributor reports for a category

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#11739]
### Discussed in https://github.com/WeblateOrg/weblate/discussions/11734

<div type='discussions-op-text'>

<sup>Originally posted by **emmapeel2** May 28, 2024</sup>
I can generate reports for all my project, or for a component.

But I need to generate them for a category.

I use a category to unify all the little components that are part of Tor Browser, and I want to have a report of the translations for that category only.</div>

**Comment by harriebird** [comment]
Hi guys, check my PR #11947 for this issue.
