### ISSUE TITLE
XLSX issue

### ISSUE THREAD

**Issue by iamshoXy** [WeblateOrg/weblate#11760]
### Describe the issue

The context should be in column A, while there are a number of strings that have been moved to column B for some reason. Now column B contains the context and column C the target, while the source (in my case English) is not present at all.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Download XLSX translation file

### Expected behavior

Column A should have the context
Column B source
Column C target

### How do you run Weblate?

Docker container

**Comment by iamshoXy** [comment]
I think some of the members who uploaded it may have messed up with the columns. Is there a possibility to add some safeguard to it?

**Comment by nijel** [comment]
Are you translating XLSX directly or is this just an export from other format? Does the download match what is show in Weblate?
