### ISSUE TITLE
Clarify the difference between "Explanation" and "Translation explanation" fields

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#11810]
### Describe the problem

It's possible for a glossary entry to have two explanations, "Explanation" (shown on the line above the entry proper) and "Translation explanation" (shown below). It's not clear what's the difference between the two and Weblate's documentation does not seem to explain it either.

Additionally, a URL in the "Explanation" field is converted to a link, but an identical URL in the "Translation explanation" field is not. Also, the "Explanation" field is not editable from the normal glossary view, but evidently it can be edited somewhere...

See: https://translations.documentfoundation.org/translate/libo_ui-master/glossary/fi/?checksum=c9d0fc4f904ef11b

Possibly related to #10969

### Describe the solution you would like

More descriptive terminology is used.

### Additional context

TDF Weblate 5.4.3

**Comment by Geeyun-JY3** [comment]
Related: #8810, #9082

**Comment by nijel** [comment]
After changes already implemented for https://github.com/WeblateOrg/weblate/issues/9082 the explanations are differentiated with a tooltip (see https://hosted.weblate.org/translate/f-droid/website-posts/zh_Hans/?checksum=f5df50c12a059caa).

The source string explanation can be changed on the source string, translation on the translation.
