### ISSUE TITLE
Problems with different sets of source strings

### ISSUE THREAD

**Issue by dg0yt** [WeblateOrg/weblate#1182]
In my project I have .ts translation files with different sets of source strings within one component:
- English has only plurals.
- Some languages have extra strings required for translation of third-party components.

I face two issues:

a) New languages added in weblate seem to be copied from English, inheriting only the plural strings (e.g. https://hosted.weblate.org/projects/openorienteering/mapper/zh_HK/). I would expect to be able to specify which language to use as a template.

b) For the extra strings, I cannot set flags on the source string because weblate claims "No matching source strings found!" (e.g. https://hosted.weblate.org/translate/openorienteering/mapper/nl/?sid=99513fa8-5347-11e6-a1b2-5254000d9bae&offset=0). I would expect this to simply work, just as I can store source comments.
##

**Comment by dg0yt** [comment]
I found that at the moment I cannot edit flags for any source string except those four that I have in English: I get "No matching source strings found!" even when trying to edits the flags I saved a few days ago and which are still displayed. Example: https://hosted.weblate.org/translate/openorienteering/mapper/de/?q=Cyan&search=substring&source=on&target=on&type=all&ignored=False

**Comment by nijel** [comment]
Indeed I've arbitrarily chosen english to use as base for new translations. However number of plurals shown in Weblate is determined by language.

The no "No matching source strings found!" error is strange, for bilingual translation such as yours, the source strings are automatically superset of all strings which appear in the translation files. Also it seems that you were able to edit the flag in the end...

**Comment by dg0yt** [comment]
>Also it seems that you were able to edit the flag in the end...

No, i was able to edit the flag in the beginning, not in the end! This is the primary issue at the moment.

**Comment by dg0yt** [comment]
For the record, also Source strings review shows just four items: https://hosted.weblate.org/projects/openorienteering/mapper/source/

**Comment by dg0yt** [comment]
Just a guess: The set of source strings (as available in the source strings review) depends on the last language created upstream or  on the web. When someone added Chinese (Hong Kong) in my project, there were only the four source strings taken from English. Now I added Chinese (China) upstream, and I see the regular set of ~1200 items in source strings review again. (The "3rd-party" strings are still missing of course, as they are not part of my Chinese template.)

**Comment by dg0yt** [comment]
Another note: The "Engage" widgets seem to be affected, too. They now get back from 4 to 12xx strings to be translated.

**Comment by nijel** [comment]
There are probably several places in Weblate based on assumption that number of strings is same in all languages.

BTW: How do you manage the translation files? I thought that lupdate would keep the translation files consistent.

**Comment by dg0yt** [comment]
How do I manage the translation files? I run lupdate with different options, and I due some post-processing. (With weblate, I do some more postprocessing now, to avoid git noise from the XML formatting variations.)

- For the English version, the option --pluralonly to lupdate is enough to make the difference. I don't want the other strings in my repository or in Weblate for English, and it seems that neither lrelease nor lconvert provide an option to drop non-plurals.
- Note that I have a separate "template" translation file from the time before we used Weblate. This file has all strings, but translations are always dropped. This file wouldn't need to appear on Weblate.
- The extra 3rd-party strings in some languages are a different story.  They used to be separate files before we started using weblate, and they could be a separate component. However, neither can I create components myself on hosted weblate, nor do I want every user to be able to create new langugages for these components. So my naive approach was to merge them in to our core component's translation files. Of course this needs some more pre- and postprocessing to keep lupdate from removing them in the end. So a separate component would be a better approach to these strings.

**Comment by nijel** [comment]
Thanks for clarification, now I finally understand it as you're using quite unique setup ;-).

* I've changed configuration so that template doesn't show up among translations and is used when creating new ones.
* I'm not sure if English translation should be show at all...
* For the third party strings I'd really recommend using separate component for each set of them. This way it will work without problems in Weblate and I think it will be easier to manage for you as well.

**Comment by nijel** [comment]
I think this should now mostly work fine. It can be improved by using separate components for the additional strings, just let me know in case you want to create those.
