### ISSUE TITLE
Improved date range selection for changes

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#11846]
### Describe the problem

Selecting date range while browsing changes could be more comfortable.

### Describe the solution you would like

https://github.com/WeblateOrg/weblate/pull/11826 introduces better date range selection for reports and the same should be used when browsing changes:

https://github.com/WeblateOrg/weblate/blob/4f95e0531ed723c6959dd3ae4d13c3181b76ce14/weblate/trans/forms.py#L2716-L2717

**Comment by harriebird** [comment]
Hi @nijel, I will check this issue. This issue related to what PR #11826 solves.

**Comment by nijel** [comment]
Yes, it's just applying the new range selector on different form.

**Comment by harriebird** [comment]
Hi guys, check my PR #11894 for this issue.
