### ISSUE TITLE
Show string/word numbers on search results

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#11853]
### Discussed in https://github.com/WeblateOrg/weblate/discussions/11770

<div type='discussions-op-text'>

<sup>Originally posted by **emmapeel2** June  3, 2024</sup>
I am still looking for numbers, and generating some stats with the api and gitlabci.

I think it would be great to provide the  number of strings and words on the results of the search interface, for example here:

https://hosted.weblate.org/search/tor/community-portal/?q=+added%3A2024-03-06+AND+language%3Aen

In the top we could show '37 strings / 300 words' 

This will help evaluate changes in a quicker and more organic way than elaborating reports, and will be available for translators without admin rights.
</div>

**Comment by DevanshArora312** [comment]
Hello, I am quite new to Open source and I do want to contribute to this issue. Can you please give some basic ideas to what does a string and word mean in the context of this issue. I get the gist that we need to quantize the results , but what would be the results and inputs still remain a bit confusing.
Thanks!

**Comment by nijel** [comment]
String is the number of results, the number of words is available for each string in the database:

https://github.com/WeblateOrg/weblate/blob/dbbb708f457e94d5753767f8cd1fadd4eb8410ef/weblate/trans/models/unit.py#L367

**Comment by amkarn258** [comment]
Hi @nijel ,

Can you please assign it to me if no one is assigned yet. I would like to work on this.

**Comment by nijel** [comment]
You're welcome to work on this, no need to assign.
