### ISSUE TITLE
would like to invite new users to register and login into Weblate only using their GITHUB 

### ISSUE THREAD

**Issue by spurnasai** [WeblateOrg/weblate#11850]
### Describe the issue

I have to limit my users to only login only via GITHUB credentials . So I want to disable the Register new account from my  UI login page . I have used                                                                                                                                                                                                       WEBLATE_REGISTRATION_OPEN: 0 and 1
WEBLATE_REGISTRATION_ALLOW_BACKENDS: github-oauth2         as my env variables and I have used both 0 and 1 for the WEBLATE_REGISTRATION_OPEN in both the cases it was not allowing the new users to register

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. I have gone through https://docs.weblate.org/en/latest/admin/config.html#std-setting-REGISTRATION_ALLOW_BACKENDS  and https://docs.weblate.org/en/latest/admin/config.html#std-setting-REGISTRATION_OPEN          
2.  If I remove both of those env variables then it is allowing the new users to login through new registration and GITHUB 

### Expected behavior

So my expectation is that I want my users to only login by github authentication I want to disable the new register option from my UI. 

### How do you run Weblate?

Docker container

### Weblate versions

5.5.5

**Comment by spurnasai** [comment]
I have used     # Weblate setup

WEBLATE_REGISTRATION_OPEN=1                                                                                                                                                          WEBLATE_REGISTRATION_ALLOW_BACKENDS: ["social_core.backends.github.GithubOAuth2"]
 WEBLATE_REQUIRE_LOGIN: 1          
![Uploading Screenshot 2024-06-13 234744.png…]()
![Screenshot 2024-06-13 234802](https://github.com/WeblateOrg/weblate/assets/167166915/ddb97a43-63b1-4a6e-a516-9be62beae372)
![Screenshot 2024-06-13 234904
![Screenshot 2024-06-13 234949](https://github.com/WeblateOrg/weblate/assets/167166915/c6f5082e-d8e6-40a2-81cb-9daf686b7686)
](https://github.com/WeblateOrg/weblate/assets/167166915/a41fc3ff-cfbf-4995-87c0-1ec77f040d80)

**Comment by nijel** [comment]
Your value for  WEBLATE_REGISTRATION_ALLOW_BACKENDS is wrong, the [documentation](https://docs.weblate.org/en/latest/admin/config.html#std-setting-REGISTRATION_ALLOW_BACKENDS) says:

> The backend names match names used in the URL for authentication.

So you should use `github` instead of `social_core.backends.github.GithubOAuth2`.

Why posting same question twice? https://github.com/WeblateOrg/weblate/discussions/11849

**Comment by spurnasai** [comment]
Hi @nijel ,
I have replaced "social_core.backends.github.GithubOAuth2"  with "github" and also tried using  "github-oauth2"  but still getting the same problem "New registrations are turned off".

**Comment by nijel** [comment]
Are the settings actually applied? How does your docker-compose.yml look like?

**Comment by spurnasai** [comment]
[settings.py.txt](https://github.com/user-attachments/files/15827365/settings.py.txt)
[docker-compose-https.override.yml.txt](https://github.com/user-attachments/files/15827418/docker-compose-https.override.yml.txt)
[docker-compose-https.yml.txt](https://github.com/user-attachments/files/15827419/docker-compose-https.yml.txt)
These are the files I am using , WEBLATE_REGISTRATION_OPEN: 1 is in environment file

**Comment by nijel** [comment]
As these are not default Docker compose names, you need to pass the override as `-f docker-compose-https.override.yml.txt` on the command line.

**Comment by spurnasai** [comment]
i have run                                                                   
  'docker compose -f docker-compose-https.yml -f docker-compose-https.override.yml build'
'docker compose -f docker-compose-https.yml -f docker-compose-https.override.yml up' in my command line

**Comment by spurnasai** [comment]
[docker-compose-https.override.yml.txt](https://github.com/user-attachments/files/15831768/docker-compose-https.override.yml.txt)
there is any problem with the configuration files or command I have used. This is the  docker-compose-https.override.yml I am using

**Comment by nijel** [comment]
The environment variables are string, so it should be:

```yaml
WEBLATE_REGISTRATION_ALLOW_BACKENDS: "github"
```
