### ISSUE TITLE
The Open AI does not implement proxy parameters!

### ISSUE THREAD

**Issue by Akemi-Madoka** [WeblateOrg/weblate#11868]
### Describe the problem

In the py module of OpenAI, the client implementation does not call the HTTP_PROXY and HTTPS_PROXY environment parameters, resulting in the inability to connect to the OpenAI client from my region, and eventually leading to a Connection error.

### Describe the solution you would like

I hope that when calling the related API, the proxy server can be called through the environment parameters, or a new corresponding proxy server environment parameter can be added for input.

**Comment by nijel** [comment]
I think it is supposed to work because openai uses httpx underneath and that supports it: https://www.python-httpx.org/environment_variables/#proxies

**Comment by Akemi-Madoka** [comment]
Hello! I apologize for wasting your time.
This issue actually stems from a very foolish and basic mistake on my part.
I wrote down this question while rigorously testing that the PROXY was actually running properly, and after you responded to me, I realized that in my docker-compose.override.yml, I had written HTTP_PROXY as HTTP_PORXY...
I am very sorry!
