### ISSUE TITLE
Excel File Translation Upload Error

### ISSUE THREAD

**Issue by dxdx123** [WeblateOrg/weblate#11872]
### Describe the issue

There is an issue with uploading translations in the Excel file. If there are more than 4 entries, the translation cannot be uploaded, and an error message appears stating that the translation content cannot be found. Format:

source:
{"desc_list":[{"title": "基础规则","rows":["活动中，传说角色的单次邂逅出率为2%","在任意邂逅活动中，每邂逅1次，累计1次全局保底计数，全局保底计数达到100次时，&lt;style=yellow&gt;必定随机获得1名当期活动中的传说角色&lt;/style&gt;。获得任意传说角色时，全局保底计数将被重置（当前全局保底：&lt;style=yellow&gt;{count}&lt;/style&gt;次内必得随机传说角色）"]}]}

target:
{"desc_list":[{"title": "基本ルール11","desc":"【常設出会い】では現在実装済みの全てのキャラクターと出会う可能性があります"}]}

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Upload Excel

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/14290268/14592caf-6d9c-4941-836e-538e54cb51c6)

![image](https://github.com/WeblateOrg/weblate/assets/14290268/b2ff8aa5-6a8c-4740-b5c1-adca4415fb9b)

### How do you run Weblate?

Docker container

### Weblate versions

5.3.1, 5.5.5

**Comment by nijel** [comment]
What error do you get exactly? Is some additional info available in Weblate logs?

**Comment by dxdx123** [comment]
When uploading 4 items：Processed 4 strings from the uploaded files (skipped: 4, not found: 0, updated: 0).
![image](https://github.com/WeblateOrg/weblate/assets/14290268/716e5ac3-06cb-4f69-8d18-b30c8272a26c)

When uploading more than 5 items：Processed 23 strings from the uploaded files (skipped: 0, not found: 22, updated: 0).
![image](https://github.com/WeblateOrg/weblate/assets/14290268/682c6e33-52ae-41e3-a5e6-1b2bcba20e87)

After further investigation, it was found that the parsing of the csv file was abnormal and the header of the excel file was not parsed normally.
![image](https://github.com/WeblateOrg/weblate/assets/14290268/244773a2-da53-4579-9558-ab150bd986ee)

![image](https://github.com/WeblateOrg/weblate/assets/14290268/e1a3b5af-ec3c-499b-98e4-bc1e28a94392)
