### ISSUE TITLE
XWiki page based translation are serialized with a white space in front of the ending </xwikidoc>

### ISSUE THREAD

**Issue by tmortagne** [WeblateOrg/weblate#11896]
### Describe the issue

When a new translation is committed, it contains a strange white space in front of the ending `</xwikidoc>`. It's a bit annoying since it cause xar:format to produce unexpected changes when it's executed later on the project.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Start translating a new locale.

### Expected behavior

Not having a white space in front of the ending `</xwikidoc>`.

### Screenshots

https://github.com/xwiki/xwiki-platform/pull/3211/files#diff-f1232b93d79779d15c266e620853c554c767cb58a680f03a14e7c91b61724465R139

### How do you run Weblate?

PyPI module

**Comment by surli** [comment]
Related unit test to fix: https://github.com/WeblateOrg/weblate/blob/main/weblate/trans/tests/data/XWikiPageProperties.xml#L52

**Comment by surli** [comment]
@nijel you can assign that one to me.

**Comment by nijel** [comment]
I guess that fix in https://github.com/translate/translate/pull/5269 is sufficient, closing this issue now. It now needs a translate-toolkit release to be used by Weblate (which will take some time because one release was this week).

**Comment by surli** [comment]
> I guess that fix in https://github.com/translate/translate/pull/5269 is sufficient, closing this issue now. It now needs a translate-toolkit release to be used by Weblate (which will take some time because one release was this week).

To be checked but I think https://github.com/WeblateOrg/weblate/blob/main/weblate/trans/tests/data/XWikiPageProperties.xml#L52 needs to be fixed too: you'll probably get test failures right now.

**Comment by nijel** [comment]
That is used for parsing only (at list this is the case for other formats), so that should be fine.
