### ISSUE TITLE
Add automatic suggestion service for transliteration of Cyrillic script to Latin

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#11923]
### Describe the problem

Several languages can be written in Cyrillic and Latin. As these are just different script for the same language, it should be possible to automatically convert these.

### Describe the solution you would like

There is [cyrtranslit](https://github.com/opendatakosovo/cyrillic-transliteration) module which can do transliteration of Cyrillic script to Latin. It can be used to automatically generate `_Latn` and `_Cyrl` translations.

**Comment by Wells245** [comment]
Hello Nijel. I'd like to take this issue as my first open source contribution but I'm not familiar with Weblate. Could someone give me a quick overview on where in the project it goes and how it's needed to be implemented?

**Comment by nijel** [comment]
The backends live in https://github.com/WeblateOrg/weblate/tree/main/weblate/machinery

An example commit to add a new backend: https://github.com/WeblateOrg/weblate/commit/fa73d221794ec49b417008e2ec50f4827569a29c

It will just not call the remote service, but use the library. List of supported languages probably needs to be hard-coded.

**Comment by gersona** [comment]
@nijel  for the sake of clarity, this issue only concerns Cyrillic to Latin transliteration right ? not in both ways

**Comment by nijel** [comment]
I think both ways make sense. The machinery should support whatever is possible with the library

**Comment by gersona** [comment]
for languages that support both Cyrillic and Latin, is the type of script always informed in the code (like `"sr@cyrillic" or "bs_Cyrl"`)? if so, how to determine current script of code such as `"sr"`, or should I check the actual content of the text to translate ?

**Comment by nijel** [comment]
Check language definitions in https://github.com/WeblateOrg/language-data/. Codes like `sr@Latn` should be used. For languages without a modifier, there usually is an existing practice whether it is Latin or Cyrillic, but I don't think we have this documented somewhere. When I need info like this I usually review translations on Hosted Weblate to see if they agree (in this case, look at https://hosted.weblate.org/languages/sr/).

**Comment by gersona** [comment]
and about the `MachineTranslation.max_score`,  since it's just transcribing from a script to another, is it safe to give it a `100` score ?

**Comment by gersona** [comment]
about the `MachineTranslation.max_score`,  since it's just transcribing from a script to another, is it safe to give it a `100` score ?

**Comment by nijel** [comment]
Yes, makes sense
