### ISSUE TITLE
Component discovery addon suddenly uninstalled, error when reinstalling

### ISSUE THREAD

**Issue by nikclayton** [WeblateOrg/weblate#11939]
### Describe the issue

I configured the "Component discovery" addon about four months ago for the Pachli project. This has been working fine, the list of components at https://hosted.weblate.org/projects/pachli/ was automatically generated and has been updated by this addon as I refactored the code in to different modules.

It's just stopped -- I'm not entirely sure when, but between March 16 and June 17.

On March 16 I committed https://github.com/pachli/pachli-android/commit/e41722e16f9e170f19facea4e001298a98e6f390, and the addon correctly created the "Feature/Lists : Main" component.

On June 17 I committed https://github.com/pachli/pachli-android/commit/3d5c2dd32f72d8075ca7860aa5dbebaf2a971795, and the addon did not create the expected "Feature/Suggestions : Main" component. I've discovered this when one of the translation team asked me earlier today why they couldn't find the strings to translate in the new module.

I've just checked https://hosted.weblate.org/addons/pachli/ and the addon is not showing as installed any more. I **definitely** have not removed it, as I haven't needed to log in to Weblate for many months.

I just tried to install and configure the addon, and after trying to save the new configuration I get an HTML page back that says:

> Server error
>
>  The server had serious problems serving your request, and this error has been recorded as 42bb5a8622224652873f066f6cadfc2a. 

(I just tried again to confirm I can reproduce the problem, same error, the error code is 8919a4b4239c4309b8e9b57f20e5635c).

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

From the Pachli project, install and configure the "Component discovery" addon with the following values:

- Regular expression to match translation files against: `(?P<component>.*)/src/(?P<flavour>.*)/res/values-(?P<language>[^/]*)/strings.xml`
- File format: Android String Resource
- Customize the component name: `{{ component | title }} : {{ flavour | title }}`
- Define the monolingual base filename: `{{ component }}/src/{{ flavour }}/res/values/strings.xml`
- Language filter: `^[^.]+$`
- [x] Clone add-ons from the main component to the newly created ones

Everything else was left blank. Then click "Save".

I know these values used to work, as Firefox had retained them in the form fill history.

### How do you run Weblate?

weblate.org service

### Weblate versions

Don't know, there's no version number I can see on https://hosted.weblate.org/about/

### Additional context

So there's two problems here.

1. Why was the addon uninstalled?
2. What's causing the error when I try and reinstall it?

**Comment by nijel** [comment]
The add-on is still installed on the component: https://hosted.weblate.org/addons/pachli/fastlane-metadata/

It indeed can't be installed at the project level, the question is whether it makes sense as it is really bound to the repository. Especially with the delete option it might do weird things when installed project or site wide.
