### ISSUE TITLE
Changes pagination broken

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#11954]
### Describe the issue

Since https://github.com/WeblateOrg/weblate/pull/11894 the navigation to other pages in changes is broken. It generates links with `period={'start_date'%3A+datetime.datetime(2024%2C+6%2C+11%2C+0%2C+0%2C+tzinfo%3Dzoneinfo.ZoneInfo(key%3D'Europe%2FPrague'))%2C+'end_date'%3A+datetime.datetime(2024%2C+6%2C+27%2C+23%2C+59%2C+59%2C+999999%2C+tzinfo%3Dzoneinfo.ZoneInfo(key%3D'Europe%2FPrague'))}`. 

Apparently, the link serialization for pagination is not working as it should.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to https://hosted.weblate.org/changes/browse/weblate/application/?user=&period=06%2F11%2F2024+-+06%2F29%2F2024
2. Click on button for the next page
3. Ends up on not found

### Expected behavior

Next page should load and the period string in the URL should be kept as on the current page.

### How do you run Weblate?

weblate.org service

**Comment by harriebird** [comment]
Hi guys, check my PR #11967 for this issue.
