### ISSUE TITLE
Internal Server Error on manage/addons/ with git exporter enabled

### ISSUE THREAD

**Issue by mkstephenson** [WeblateOrg/weblate#11976]
### Describe the issue

When I have the "git.exporter" addon enabled and I navigate to the addons management page in the UI, I get an internal server error. The error in the console tells me that "module 'weblate.gitexport' has no attribute 'get_identifier'".

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Start weblate 4.6.1 in docker with `WEBLATE_ADD_ADDONS=weblate.gitexport` as an environment variable.
2. Log in and go to the addons management page (🔧 => Add-ons) and see the "Server Error" page.
3. View the docker logs and see the exception in the console logs

### Expected behavior

I expect to see the list of addons, git exporter addon being shown here is optional but would be nice.

### Exception traceback

```pytb
Traceback (most recent call last):
gunicorn stdout |   File "/app/venv/lib/python3.12/site-packages/django/core/handlers/excepti=
gunicorn stdout | on.py", line 55, in inner
gunicorn stdout |     response =3D get_response(request)
gunicorn stdout |                ^^^^^^^^^^^^^^^^^^^^^
gunicorn stdout |   File "/app/venv/lib/python3.12/site-packages/django/core/handlers/base.py=
gunicorn stdout | ", line 197, in _get_response
gunicorn stdout |     response =3D wrapped_callback(request, *callback_args, **callback_kwarg=
gunicorn stdout | s)
gunicorn stdout |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stdout |   File "/app/venv/lib/python3.12/site-packages/django/views/generic/base.py=
gunicorn stdout | ", line 104, in view
gunicorn stdout |     return self.dispatch(request, *args, **kwargs)
gunicorn stdout |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stdout |   File "/app/venv/lib/python3.12/site-packages/django/views/generic/base.py=
gunicorn stdout | ", line 143, in dispatch
gunicorn stdout |     return handler(request, *args, **kwargs)
gunicorn stdout |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stdout |   File "/app/venv/lib/python3.12/site-packages/django/views/generic/list.py=
gunicorn stdout | ", line 174, in get
gunicorn stdout |     context =3D self.get_context_data()
gunicorn stdout |               ^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stdout |   File "/app/venv/lib/python3.12/site-packages/weblate/addons/views.py", li=
gunicorn stdout | ne 94, in get_context_data
gunicorn stdout |     for x in ADDONS.values()
gunicorn stdout |              ^^^^^^^^^^^^^^^
gunicorn stdout |   File "/app/venv/lib/python3.12/site-packages/weblate/utils/classloader.py=
gunicorn stdout | ", line 90, in values
gunicorn stdout |     return self.data.values()
gunicorn stdout |            ^^^^^^^^^
gunicorn stdout |   File "/app/venv/lib/python3.12/site-packages/django/utils/functional.py",=
gunicorn stdout |  line 47, in __get__
gunicorn stdout |     res =3D instance.__dict__[self.name] =3D self.func(instance)
gunicorn stdout |                                          ^^^^^^^^^^^^^^^^^^^
gunicorn stdout |   File "/app/venv/lib/python3.12/site-packages/weblate/utils/classloader.py=
gunicorn stdout | ", line 72, in data
gunicorn stdout |     return self.load_data()
gunicorn stdout |            ^^^^^^^^^^^^^^^^
gunicorn stdout |   File "/app/venv/lib/python3.12/site-packages/weblate/utils/classloader.py=
gunicorn stdout | ", line 67, in load_data
gunicorn stdout |     result[obj.get_identifier()] =3D obj
gunicorn stdout |            ^^^^^^^^^^^^^^^^^^
gunicorn stdout | 
gunicorn stdout | Exception Type: AttributeError at /manage/addons/
gunicorn stdout | Exception Value: module 'weblate.gitexport' has no attribute 'get_identifie=
gunicorn stdout | r'
gunicorn stdout | Raised during: weblate.addons.views.AddonList
gunicorn stdout | Request information: <redacted>
```

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.6.1
 * Django: 5.0.6
 * siphashc: 2.4.1
 * translate-toolkit: 3.13.1
 * lxml: 5.2.2
 * pillow: 10.3.0
 * nh3: 0.2.17
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.1
 * django-crispy-forms: 2.2
 * oauthlib: 3.2.2
 * django_compressor: 4.5
 * djangorestframework: 3.15.2
 * django-filter: 24.2
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.15.4
 * rapidfuzz: 3.9.3
 * openpyxl: 3.1.4
 * celery: 5.4.0
 * django-celery-beat: 2.6.0
 * kombu: 5.3.7
 * translation-finder: 2.16
 * weblate-language-data: 2024.5
 * html2text: 2024.2.26
 * pycairo: 1.26.1
 * PyGObject: 3.48.2
 * diff-match-patch: 20230430
 * requests: 2.32.3
 * django-redis: 5.4.0
 * hiredis: 2.3.2
 * sentry-sdk: 2.6.0
 * Cython: 3.0.10
 * misaka: 2.1.1
 * GitPython: 3.1.43
 * borgbackup: 1.2.8
 * pyparsing: 3.1.2
 * ahocorasick_rs: 0.22.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * Python: 3.12.4
 * Git: 2.39.2
 * psycopg: 3.1.19
 * psycopg-binary: 3.1.19
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.7.0
 * boto3: 1.34.132
 * zeep: 4.2.1
 * aeidon: 1.15
 * iniparse: 0.5
 * mysqlclient: 2.2.4
 * Mercurial: 6.7.4
 * git-svn: 2.39.2
 * git-review: 2.4.0
 * PostgreSQL server: 16.3
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.console.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 6.5.0-1023-azure (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.6.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.6.1/admin/backup.html

System check identified 2 issues (1 silenced).
```

**Comment by nijel** [comment]
The Git exporter is not an add-on, adding it to WEBLATE_ADD_ADDONS is not supposed to work, please remove it. The Docker container has already turned that on.
