### ISSUE TITLE
Clicking "Tab" twice needed to go to new string in Zen mode

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#11982]
### Describe the issue

Clicking tab once only saves the string.
Have to click twice to move the editing field of the string below.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Click tab.
(Current string is saved)
Try typing
(Nothing happens)
Click tab again

### Expected behavior

It used to be that clicking tab once did the trick

### How do you run Weblate?

weblate.org service

### Additional context

Fairly new issue, so probably introduced with a version deployed yesterday?

I don't understand the benefit of being in between string wrt. the ability to edit anything by typing.

**Comment by nijel** [comment]
The needs editing checkbox is focused between the textareas. See https://github.com/WeblateOrg/weblate/issues/9481 and https://github.com/WeblateOrg/weblate/pull/11952.
