### ISSUE TITLE
Components and languages pagination

### ISSUE THREAD

**Issue by roidelapluie** [WeblateOrg/weblate#1198]
With big projects, it would be useful to paginate the following:
- [x] The list of components of a project
- [ ] The list of components in "your languages"
##

**Comment by codeavenger07** [comment]
Mind if I take a stab at this?

**Comment by devophile** [comment]
Could you list the files to be paginated please?

**Comment by nijel** [comment]
Pagination of components on project page is now there: c687e4b1b656e71b5265a8774dfec1287a036dd8

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
