### ISSUE TITLE
View: Tree view for repository.

### ISSUE THREAD

**Issue by emmapeel2** [WeblateOrg/weblate#1201]
To maintain a big corpus of text that is continuously changing can be challenging.

It would be great to have a view per project, where you can browse the actuall directory tree of the repo.

Components already in weblate could be links
New .po files could have an [add] button to create a new Component
##

**Comment by emmapeel2** [comment]
For the time being I have changed the name of all the components to the filemask and it kind of works...
I did it with the shell:

from weblate.trans.models import *  
todos = SubProject.objects.all()

for i in todos:
    i.name = i.filemask
    i.save()

But only work if you have one component per filemask (it is not possible to have the same components for different branches, needed when preparing the translations for a new release)

**Comment by nijel** [comment]
For some time we have a feature to create component from existing one with discovery of translatable files. There is also [discovery addon](https://docs.weblate.org/en/latest/admin/addons.html#component-discovery) to automate this in case the translatable files follow some rules. I believe this is superior to displaying of content of the repository (what additionally might have privacy implications as not all translators should have access to the repository).
