### ISSUE TITLE
Plural fields missing when adding glossary

### ISSUE THREAD

**Issue by timothyqiu** [WeblateOrg/weblate#12044]
### Describe the issue

#11756 implemented pluralized add new translation string on web UI. But seems not working for glossary.

In this screenshot, I selected "Plural", but nothing changes:

![image](https://github.com/WeblateOrg/weblate/assets/372476/5c7c798d-73a8-4083-95df-75bdb8d521a7)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

* Login Weblate and go to https://hosted.weblate.org/projects/godot-engine/glossary/en/#new
* Select "Plural" and the form does not change

### Expected behavior

Show separate fields for singular and plural version, like the screenshot in #11756.

**Comment by nijel** [comment]
Tbx format used by default for glossaries doesn't support plurals.

**Comment by timothyqiu** [comment]
Should these options be hidden when tbx format is used?

**Comment by nijel** [comment]
Yes, it should. I didn't notice the select is still visible.
