### ISSUE TITLE
Activating INSTALLED_APPS += ("weblate.billing",)  on self hosted gives only "without biling" plan and access control cannot be changed

### ISSUE THREAD

**Issue by weblate-highcanfly** [WeblateOrg/weblate#12052]
### Describe the issue

On my own Kubernetes instance instance deployed with the official Helm chart adding `INSTALLED_APPS += ("weblate.billing",)`  in the `configOverride`  options enables the Billing option in the profile but when adding a new project the only option available is "-- without billing --"

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

on a Kubernetes installation deploy weblate 5.6.2 with helm.  

Create a simple project  

Next update the helm configuration for including :  
```yaml
configOverride: |
         INSTALLED_APPS += ("weblate.billing",)
```
on a kubernetes shell issue:  
```bash
weblate migrate
```
Logged as admin create a new project.  

The only billing plan is "-- without billing--"  

Try to change the first created project access control… Not possible the message is **You do not have permission to change project access control. [Check your billing status](https://weblate.exemple.org/billing/)**

### How do you run Weblate?

Docker container

### Weblate versions

5.6.2

### Weblate deploy checks

```shell
System check identified some issues:

WARNINGS:
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.6.2/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.6.2/admin/backup.html

System check identified 3 issues (1 silenced).
```

**Comment by aeltorio** [comment]
same here using docker image

**Comment by nijel** [comment]
You need to define plans in the admin interface, see https://docs.weblate.org/en/latest/admin/optionals.html#billing

**Comment by weblate-highcanfly** [comment]
@nijel 
thanks a lot for your help and thank you for your amazing work.  
I follow the documentation but there's nothing doable in the admin billing interface:  
<img width="1356" alt="Capture d’écran 2024-07-12 à 16 57 51" src="https://github.com/user-attachments/assets/a9ce8e1f-f9c4-4801-a0d8-a6c669291b04">
<img width="1313" alt="Capture d’écran 2024-07-12 à 17 00 10" src="https://github.com/user-attachments/assets/21475dca-7c12-4bdf-b6ab-e4873cb1094f">
<img width="1324" alt="Capture d’écran 2024-07-12 à 17 00 45" src="https://github.com/user-attachments/assets/9f8c4f28-3f29-4492-81ba-c4289c663cf2">

**Comment by aeltorio** [comment]
@nijel it is perhaps more a documentation since I cannot find how to create the billing plans ?

**Comment by aeltorio** [comment]
@weblate-highcanfly @nijel  , I've tried a clean installation it is exactly the same.  
At least one basic plan must be created during the database initialization.

**Comment by nijel** [comment]
Needs to be done in Django admin (see https://docs.weblate.org/en/latest/admin/admin.html#the-django-admin-interface), probably docs needs clarification on this. Can you please contribute that?

**Comment by aeltorio** [comment]
@nijel I’ll do it soon.

**Comment by aeltorio** [comment]
PR https://github.com/WeblateOrg/weblate/pull/12054 created

**Comment by weblate-highcanfly** [comment]
@aeltorio Thank you following your "billing plan creation" PR worked for me
