### ISSUE TITLE
History for upload

### ISSUE THREAD

**Issue by marcperrin** [WeblateOrg/weblate#1208]
**When I upload translations**, there's a history entry at translation level ('Translation uploaded') but **individual units get no additional history entry**
It looks like a problem to me, as our target should be for offline and online translation to have (almost...) the same effect.

Not yet sure about fix details, but I think some additional Change.objects.create could be made in **check_sync** (probably restricted to change == Change.ACTION_UPLOAD case)
##

**Comment by nijel** [comment]
It is done this way for performance reasons, but that is probably no longer true.

**Comment by marcperrin** [comment]
About the performance: I've tried a **very simple tweak/fix** that looked "natural" to me (cf. below), it works but the **performance hit is terrible** (granted, it's on a lousy test machine, with sqlite, but still... e.g. upload of 175 units takes 5 min instead of more-or-less-instantaneous)

The **Change.objects.create** seems very taxing indeed (and even if my fix isn't perfect I'm not sure there's a way around that unless we try maybe a **bulk_create**... I guess I'll try that...)

```diff
Try a very simple fix for Weblate Issue 1208 (History for Upload)

----------------------- weblate/trans/models/changes.py -----------------------
index 00d17ce..da9482a 100644
@@ -223,10 +223,11 @@ class Change(models.Model):
     ACTIONS_REVERTABLE = set((
         ACTION_ACCEPT,
         ACTION_REVERT,
         ACTION_CHANGE,
         ACTION_NEW,
+        ACTION_UPLOAD,
     ))
 
     ACTIONS_CONTENT = set((
         ACTION_CHANGE,
         ACTION_NEW,

--------------------- weblate/trans/models/translation.py ---------------------
index a5bcb23..17376f3 100644
@@ -471,11 +471,11 @@ class Translation(models.Model, URLMixin, PercentMixin, LoggerMixin):
 
         for unit in self.store.all_units():
             if not unit.is_translatable():
                 continue
 
-            newunit, is_new = Unit.objects.update_from_unit(
+            newunit, is_new, is_modified = Unit.objects.update_from_unit(
                 self, unit, pos
             )
 
             # Check if unit is new and untranslated
             was_new = (
@@ -507,10 +507,28 @@ class Translation(models.Model, URLMixin, PercentMixin, LoggerMixin):
                 )
 
             # Store current unit ID
             created_units.add(newunit.id)
 
+            if change == Change.ACTION_UPLOAD and is_modified:
+
+                # Should we store history of edits?
+                # pylint: disable=R0204
+                if self.subproject.save_history:
+                    history_target = newunit.target
+                else:
+                    history_target = ''
+
+                Change.objects.create(
+                    unit=newunit,
+                    translation=self,
+                    action=change,
+                    user=user,
+                    author=user,
+                    target=history_target
+                )
+
         # Following query can get huge, so we should find better way
         # to delete stale units, probably sort of garbage collection
 
         # We should also do cleanup on source strings tracking objects
 

------------------------- weblate/trans/models/unit.py -------------------------
index 49f7d9d..81dd03e 100644
@@ -102,14 +102,14 @@ class UnitManager(models.Manager):
                 context=ctx
             )
             created = True
 
         # Update all details
-        dbunit.update_from_unit(unit, pos, created)
+        modified = dbunit.update_from_unit(unit, pos, created)
 
         # Return result
-        return dbunit, created
+        return dbunit, created, modified
 
     def filter_checks(self, rqtype, translation, ignored=False):
         """
         Filtering for checks.
         """
@@ -460,11 +460,11 @@ class Unit(models.Model, LoggerMixin):
                 translated == self.translated and
                 comment == self.comment and
                 pos == self.position and
                 contentsum == self.contentsum and
                 previous_source == self.previous_source):
-            return
+            return False
 
         # Ensure we track source string
         source_info, source_created = Source.objects.get_or_create(
             checksum=self.checksum,
             subproject=self.translation.subproject
@@ -500,10 +500,12 @@ class Unit(models.Model, LoggerMixin):
         if contentsum_changed:
             self.update_has_failing_check(recurse=False, update_stats=False)
             self.update_has_comment(update_stats=False)
             self.update_has_suggestion(update_stats=False)
 
+        return True
+
     def is_plural(self):
         """
         Checks whether message is plural.
         """
         return is_plural(self.source) or is_plural(self.target)
```

**Comment by marcperrin** [comment]
Yeah, adding the below fix yields a much better performance:

```diff
Try a slightly more sophisticated fix for Weblate Issue 1208 (History for Upload) (use of django's bulk_create as the simple fix's perf is just too awful)

--------------------- weblate/trans/models/translation.py ---------------------
index 17376f3..161155b 100644
@@ -467,10 +467,12 @@ class Translation(models.Model, URLMixin, PercentMixin, LoggerMixin):
         # Was there change?
         was_new = False
         # Position of current unit
         pos = 1
 
+        history_objs = []
+
         for unit in self.store.all_units():
             if not unit.is_translatable():
                 continue
 
             newunit, is_new, is_modified = Unit.objects.update_from_unit(
@@ -516,18 +518,22 @@ class Translation(models.Model, URLMixin, PercentMixin, LoggerMixin):
                 if self.subproject.save_history:
                     history_target = newunit.target
                 else:
                     history_target = ''
 
-                Change.objects.create(
+                history_objs.append(Change(
                     unit=newunit,
                     translation=self,
+                    subproject=self.subproject, #needed because, per bulk_create's caveats, the model's save() method will not be called
                     action=change,
                     user=user,
                     author=user,
                     target=history_target
-                )
+                ))
+
+        if len(history_objs) > 0:
+            Change.objects.bulk_create(history_objs)
 
         # Following query can get huge, so we should find better way
         # to delete stale units, probably sort of garbage collection
 
         # We should also do cleanup on source strings tracking objects

```

**Comment by marcperrin** [comment]
Hello,

I've got another question about upload (let's forget about "history" issues for now):

I get **very different execution times** for **upload** of a .po file **vs. pull** of the same file - e.g. 15 minutes for upload vs 2 minutes for pull... Ideally I'd want the upload to be as fast or almost...

Looking at the **db queries log** (sqlite - I've yet to make the same benchmark on mysql), I mostly notice this difference:
2017-02-07 16:33:06,234 DEBUG (0.000) **BEGIN**; args=None
happens right before 
2017-02-07 16:33:06,235 DEBUG (0.000) UPDATE "trans_unit" SET (...)
for upload, not for pull.

Looking at the code, I see that **check_sync** is wrapped with a 
**with transaction.atomic():**
in **create_translations** (pull test case)
but not in **merge_store** (upload test case)
Is there a reason the transaction.atomic is not used in merge_store? 
Is that so people aren't blocked while someone uploads? (whereas the pull is more of an admin command, and can use transaction.atomic?)

**Do people use the upload a lot? / has anyone encountered such upload times? / does anyone share my concerns?**
I guess I can tweak the code on my end to have a "Speedy Upload" that uses transaction.atomic but warns about the consequences... 
(I'd _much_ rather have users (owners) be able to perform upload themselves, than being forced (due to unreasonable upload times) to tell them to give me (admin) the file(s), so I'd directly work with the repository files, maybe merge on my side, and then perform a pull...)

Thanks,

Marc

**Comment by nijel** [comment]
Every request is wrapped in transaction, for check sync we do separate transaction per translation, so that when something breaks in importing one of them, all previous ones are already committed in the database. But I'm pretty sure that transactions are not the thing which will make speed difference.

Upload is anyway more complex thing than scanning existing file - it has to merge new file into existing one. You don't want to simply overwrite existing file as users can upload pretty much anything and you can easily end up in completely different file than what you had before (I was using Pootle before and it did handle file uploads this way and this is lesson I've learned there). Also this way we can handle uploads in different file format than the project is using.

**Comment by marcperrin** [comment]
Sure, upload is more complex, but from what I see, the time spent doing complex stuff to get a nicely merged file is not the issue.
The issue is purely with check_sync, which serves the same ("scanning") purpose for pull and upload I think.
I'm pretty sure the transactions explain the time difference (I can send you some log examples) - I have to test on mysql to see if the impact is as important, though.

**Comment by nijel** [comment]
There can certainly be some optimizations.

What happens for file upload right now:

1. The uploaded file is parsed.
2. Content is merged to the translation file.
3. The changed file is parsed.

With per unit approach it would be:

1. The uploaded file is parsed.
2. Every unit is updated, this consists of:
    1. Updating in database.
    2. Updating the translation file.
    3. The changed file is parsed.

As you can see with current code we would be parsing the changed file for every changed unit, what will not perform well. Certainly the code could be adjusted to do this once at the end, but this is how the current code works.

**Comment by marcperrin** [comment]
I don't have a problem with the current 1-2-3 steps that you describe. 
I just find 3 slow because check_sync (called by merge_store - please correct me if I'm wrong) isn't wrapped in "with transaction.atomic()" like it's the case in create_translations for example.
Thanks!

**Comment by nijel** [comment]
Well I have to rewrite related code anyway due to different issue, so the code will be a bit simplified....
