### ISSUE TITLE
Incorrect projects count on hosted weblate homepage for anonymous user

### ISSUE THREAD

**Issue by gersona** [WeblateOrg/weblate#12081]
### Describe the issue

The number of projects displayed at the bottom of the homepage doesn't match the actual number of projects an anonymous user can browse.
Currently, it says there are 1400+ projects , but when we click on the button, the paginator only displays 12 pages available (with a limit of 100 projects per page), which add up only to 1200 projects at most

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1 - Go to https://hosted.weblate.org/ as an anonymous user and click the "Browse all [number] projects"
2 - You will be navigate to the https://hosted.weblate.org/projects/ url, and scroll to the bottom of the page where the paginator is located
3 - notice the discrepancy between the pages available and the initial number of projects

### Expected behavior

The number in the "Browse all [number] projects" should match the actual number of projects a user can browse through

### Screenshots

<img width="318" alt="Capture d’écran 2024-07-18 à 08 51 21" src="https://github.com/user-attachments/assets/6ee2ae6c-33aa-48c0-ae75-1ae99b1121de">
<img width="294" alt="Capture d’écran 2024-07-18 à 08 53 46" src="https://github.com/user-attachments/assets/db621e35-8f78-4c52-b219-d5cd1b43c9e3">

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
There are some not publicly accessible projects.
