### ISSUE TITLE
Database backup is on an older state

### ISSUE THREAD

**Issue by iamshoXy** [WeblateOrg/weblate#12107]
### Describe the issue

After extracting a borg backup and importing it to a new server, I realized that the dump is a month old, even though the backup is from today (07/22).

![Screenshot 2024-07-22 150812](https://github.com/user-attachments/assets/db2df6ee-d651-4f7e-a130-2a4611889f7e)

Running pg_dump (just like weblate does) exported the current data successfully:
![image](https://github.com/user-attachments/assets/a370db55-b590-45d9-a725-c5a354a34e41)

Shouldn't it dump the current state?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Perform backup
2. Extract backup
3. Compare the backup with another manual backup

### Expected behavior

The backups should contain the current state at the time the backup is performed.

### How do you run Weblate?

Docker container

### Weblate versions

Weblate 5.5.5

**Comment by nijel** [comment]
Are there any errors in the log? Didn't you change DATABASE_BACKUP setting?

**Comment by iamshoXy** [comment]
I can't certainly say if there were any errors unfortunately and DATABASE_BACKUP has not been changed.
However, it seems to work on 5.6.2, so it can probably be closed.

**Comment by nijel** [comment]
Good that it works, but Weblate should make it easier to spot that it is not working properly, I've created https://github.com/WeblateOrg/weblate/issues/12136 to track this.
