### ISSUE TITLE
Tracking the quality of each translation

### ISSUE THREAD

**Issue by Changaco** [WeblateOrg/weblate#1212]
It seems like the "fuzzy" flag is currently the only indicator of the quality of a translation. It'd be nice if translations could be grouped by the "skill level" (e.g. native, fluent, intermediate, basic) of the translator. Each translator would set (in their profiles) their level for each language, and that would allow categorizing every translation by the skill level of the last translator. Additionally, a reviewer who is more fluent than the original translator could raise the level of a translation by approving it.

This would mostly be useful for open-source projects, as most of them can't pay professional translators for everything and rely on volunteers who aren't always native or fluent speakers, but I guess it could also be useful to some private projects.
##

**Comment by nijel** [comment]
This approach sounds interesting, though I'm a bit afraid of additional complexity.

**Comment by nijel** [comment]
Honestly I don't think this flag would add anything useful. In my experience the self-assessment really doesn't work well in this case. There are people who provide poor quality translations while they think they are professionals and there are people which would like to get the translation reviewed even when they are producing high quality translations.

What I think will help better is to add separate review flag from fuzzy (see #1314) - the translation would be included in the project, but somebody should review it. This will make it easy to ask for review for people who are not confident with what they have provided (and probably there will be option to enforce review).
