### ISSUE TITLE
Automatic groups assignment does not work with LDAP authentication

### ISSUE THREAD

**Issue by marcperrin** [WeblateOrg/weblate#1213]
Automatic groups assignment does not seem to work properly when the user is created/authenticated through LDAP.
(NB: that's the only non-std authentication backend I've played with, not sure whether the issue is reproducible with other backends)
To reproduce the issue, create a non-trivial automatic groups assignment entry (unlike ^.*$ => Users), have an effective LDAP auth configured and login with a new (for Weblate) user.

Analysis: 
Probably (to be verified) the LDAP attribute mapping is performed after the post_save signal from User sender, so that email is basically unavailable (empty) in create_profile_callback.

A solution that seems to work for me (cf. diff below) is to re-do the Automatic groups assignment work upon another signal, namely populate_user from LDAPBackend.

```
--- a/ecccd210e57d4a9901e92af9832870af9fdf4d64:weblate/accounts/auth.py
+++ b/1690c137014861c66d3d220d41a874be90493df2:weblate/accounts/auth.py
@@ -19,8 +19,9 @@
 #

 import sys
+import re

-from django.contrib.auth.models import User, Permission
+from django.contrib.auth.models import User, Permission, Group
 from django.shortcuts import redirect
 from django.core.urlresolvers import reverse
 from django.db.models.signals import pre_save
@@ -28,12 +29,16 @@ from django.dispatch.dispatcher import receiver
 from django.utils.translation import ugettext as _
 from django.contrib.auth.backends import ModelBackend

+from django_auth_ldap.backend import populate_user
+from django_auth_ldap.backend import LDAPBackend
+
 import social.backends.email
 from social.exceptions import AuthMissingParameter

 from weblate.appsettings import ANONYMOUS_USER_NAME
 from weblate.trans import messages
 from weblate.trans.util import report_error
+from weblate.accounts.models import AutoGroup

 class EmailAuth(social.backends.email.EmailAuth):
@@ -125,3 +130,14 @@ def disable_anon_user_password_save(sender, *_kwargs):
     if (instance.username == ANONYMOUS_USER_NAME and
             instance.has_usable_password()):
         raise ValueError('Anonymous user can not have usable password!')
+
+@receiver(populate_user, sender=LDAPBackend)
+def auto_groups_upon_ldap(sender, *_kwargs):
-    # As the User's post_save django signal is apparently called before
-    # LDAP attribute mapping, it's necessary to perform the automatic groups
-    # assignment here too:
-    user = kwargs['user']
-    # Add user to automatic groups ()
-    for auto in AutoGroup.objects.all():
-        if re.match(auto.match, user.email):
-            user.groups.add(auto.group)
```

**Comment by nijel** [comment]
Your solution is not really acceptable - it would introduce dependency on the django_auth_ldap. 

Anyway the user has to be saved, so maybe just skipping the ```if created:``` condition in the create_profile_callback would help in your case?

**Comment by marcperrin** [comment]
If we're using LDAP auth, we're already importing from django_auth_ldap in settings.py, so while we don't want the dependency, we know django_auth_ldap *could* be there, so maybe wrap the relevant imports in try/except ImportError? (yeah that's not pretty...)

I'm not sure there's a clean solution to the issue that would not make use of this populate_user signal.
Anyway, it's a minor issue and I guess a mention of that signal in the LDAP part of the documentation would be enough.

**Comment by nijel** [comment]
Looking at django_auth_ldap code, it first creates user, populates it and then saves again. This is suboptimal and could be done in just one step, but probably necessary if they are still going to support ancient Django versions (what I doubt makes sense, but they do that). So there is probably no other way around than to hook to their specific signal...

BTW: Can you please provide some example for confinguring django_auth_ldap in Weblate? I believe other users would benefit from it as well.

**Comment by marcperrin** [comment]
Currently my config for LDAP auth basically looks like this (in settings.py):
(just an example, has to be adapted to fit your own LDAP preferences / specificities)

```python
import ldap
from django_auth_ldap.config import LDAPSearch

AUTH_LDAP_SERVER_URI = 'ldap://...'
AUTH_LDAP_BIND_DN = "cn=...,ou=...,ou=...,dc=...,dc=..."
AUTH_LDAP_BIND_PASSWORD = "..."
AUTH_LDAP_USER_SEARCH = LDAPSearch("ou=...,ou=...,dc=...,dc=...", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)")

# List of attributes to import from LDAP on login
# Weblate stores full user name in the first_name attribute
AUTH_LDAP_USER_ATTR_MAP = {
    'first_name': 'name',
    'email': 'mail',
}
```

Plus, as discussed above, I've got this probably-not-too-pretty stuff in weblate\accounts\auth.py to get auto group assignement to work fine with LDAP:

```python
from django_auth_ldap.backend import populate_user
from django_auth_ldap.backend import LDAPBackend
from weblate.accounts.models import AutoGroup

@receiver(populate_user, sender=LDAPBackend)
def auto_groups_upon_ldap(sender, **kwargs):
    # As the User's post_save django signal is apparently called before
    # LDAP attribute mapping, it's necessary to perform the automatic groups
    # assignment here too:
    user = kwargs['user']
    # Add user to automatic groups ()
    for auto in AutoGroup.objects.all():
        if re.match(auto.match, user.email):
            user.groups.add(auto.group)
```

Haven't touched/reread all that in a while but it seems to work fine!
