### ISSUE TITLE
UnicodeEncodeError:  'charmap' codec can't encode char...

### ISSUE THREAD

**Issue by auronen** [WeblateOrg/weblate#12140]
### Describe the issue

After every action (that seems to touch the underlying repositories) I get 
```
UnicodeEncodeError

'charmap' codec can't encode characters in position 139177-139178: character maps to <undefined>
encoding with 'mac_greek' codec failed
```

All of my translation files are in UTF-8 encoding

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Seems to happen with every action that touches the internal repositories
- updating remote repository
- downloading translation files
- applying changes to the internal repositories

### Exception traceback

```pytb
UnicodeEncodeError: 'charmap' codec can't encode characters in position 139177-139178: character maps to <undefined>
  File "django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "django/views/decorators/http.py", line 64, in inner
    return func(request, *args, **kwargs)
  File "weblate/trans/views/git.py", line 47, in update
    return execute_locked(
  File "weblate/trans/views/git.py", line 21, in execute_locked
    result = call(*args, **kwargs)
  File "weblate/trans/models/project.py", line 399, in do_update
    return self.on_repo_components(True, "do_update", request, method=method)
  File "weblate/trans/models/project.py", line 383, in on_repo_components
    return all(list(generator))
  File "weblate/trans/models/project.py", line 378, in <genexpr>
    getattr(component, func)(*args, **kwargs)
  File "weblate/trans/models/component.py", line 199, in on_link_wrapper
    return func(self, *args, **kwargs)
  File "weblate/trans/models/component.py", line 1668, in do_update
    self.commit_pending(
  File "weblate/trans/models/component.py", line 199, in on_link_wrapper
    return func(self, *args, **kwargs)
  File "weblate/trans/models/component.py", line 1990, in commit_pending
    translation._commit_pending(reason, user)
  File "contextlib.py", line 81, in inner
    return func(*args, **kwds)
  File "weblate/trans/models/translation.py", line 607, in _commit_pending
    self.update_units(units, store, author_name, author.id)
  File "weblate/trans/models/translation.py", line 807, in update_units
    store.save()
  File "weblate/formats/ttkit.py", line 328, in save
    self.save_atomic(self.storefile, self.save_content)
  File "weblate/formats/base.py", line 474, in save_atomic
    callback(temp)
  File "weblate/formats/ttkit.py", line 324, in save_content
    self.store.serialize(handle)
  File "translate/storage/csvl10n.py", line 347, in serialize
    out.write(source.encode(self.encoding))
  File "encodings/mac_greek.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
```

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.6.2
 * Django: 5.0.6
 * siphashc: 2.4.1
 * translate-toolkit: 3.13.1
 * lxml: 5.2.2
 * pillow: 10.3.0
 * nh3: 0.2.17
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.1
 * django-crispy-forms: 2.2
 * oauthlib: 3.2.2
 * django_compressor: 4.5
 * djangorestframework: 3.15.2
 * django-filter: 24.2
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.15.4
 * rapidfuzz: 3.9.3
 * openpyxl: 3.1.5
 * celery: 5.4.0
 * django-celery-beat: 2.6.0
 * kombu: 5.3.7
 * translation-finder: 2.16
 * weblate-language-data: 2024.5
 * html2text: 2024.2.26
 * pycairo: 1.26.1
 * PyGObject: 3.48.2
 * diff-match-patch: 20230430
 * requests: 2.32.3
 * django-redis: 5.4.0
 * hiredis: 2.3.2
 * sentry-sdk: 2.7.1
 * Cython: 3.0.10
 * misaka: 2.1.1
 * GitPython: 3.1.43
 * borgbackup: 1.2.8
 * pyparsing: 3.1.2
 * ahocorasick_rs: 0.22.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * Python: 3.12.4
 * Git: 2.39.2
 * psycopg: 3.2.1
 * psycopg-binary: 3.2.1
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.7.0
 * boto3: 1.34.136
 * zeep: 4.2.1
 * aeidon: 1.15
 * iniparse: 0.5
 * mysqlclient: 2.2.4
 * Mercurial: 6.7.4
 * git-svn: 2.39.2
 * git-review: 2.4.0
 * PostgreSQL server: 14.12
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.cokoliv.eu
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.19.0-26-amd64 (x86_64)

**Comment by nijel** [comment]
Use UTF-8 variant of the CSV format instead of automatic detection which might fail in some cases

**Comment by auronen** [comment]
This is a very old weblate project, when it was being made I am pretty sure there wasn't the option `CSV File (UTF-8)` and when I try to change it now, I get the same error and cannot change it.
Could you please give me some pointer to how I can change it in some other way than through the UI?

**Comment by nijel** [comment]
It probably won't work via UI because of the pending changes which can't be written out, only on the shell.

**Comment by auronen** [comment]
Thank you for the suggestion. In the end I managed to solve it by removing the component with the issue, changing the format to `CSV File (UTF-8)` and then readding it.
Thank you for help.
