### ISSUE TITLE
New feature: Component priority

### ISSUE THREAD

**Issue by emmapeel2** [WeblateOrg/weblate#1216]
We have some pages that are important to translate before others.

On the interface I can see a way to edit the string priority, but it is very hard to edit the priority of all the strings of a component.

It would be great to be able to do group edit of strings priority from the component window.
##

**Comment by nijel** [comment]
The string priority affects order how strings within component are provided for translation. I'm not sure how component priority would make difference, as there is no project wide translation interface...

**Comment by emmapeel2** [comment]
Michal Čihař:
> I'm not sure how component priority would
> make difference, as there is no project wide translation
> interface...
> 

I think the component with highest average priority should be presented
first to the translator, maybe affect the ordering at the component
page, where there appear other translations, or be a possible ordering
column on the Dashboard.

This will allow to prioritize the content translation project-wide.
