### ISSUE TITLE
> 1.000 error emails in 3 hours running out of space

### ISSUE THREAD

**Issue by vabene1111** [WeblateOrg/weblate#12175]
### Describe the issue

my server ran out of space (for unrelated reasons). This lead to weblate sending ~1.084 "error" emails within a timeframe of about 3 hours. 

The errors are likely correct and caused by having the server run out of space, what is I think an issue is that there seems to be no limit on emails send.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

since I only have one production server and don't want to impact my services again I have not tested it again but probably the following:

1. have the server run out of space
2. clear some space but don't restart weblate
3. wait for emails

### Expected behavior

In general I think sending emails about errors is a good thing. There is probably some kind of rate limit needed to prevent issues like this (also probably for security reasons so people can't ddos infrastructure by causing errors)

### Screenshots

![image](https://github.com/user-attachments/assets/04d155d6-1660-4ccc-9496-157342f4263b)

First email error message
![image](https://github.com/user-attachments/assets/b91eff86-5a58-49c8-a280-72c70d58a847)
alternating with this message (about two emails every minute
![image](https://github.com/user-attachments/assets/505393b3-3147-4f8c-b513-133f7eacd74e)

after clearing space about 3 emails every minute 
![image](https://github.com/user-attachments/assets/fb7cc43c-13fa-4d8c-b71c-cd8617800268)

![image](https://github.com/user-attachments/assets/a13ed0f4-4f8a-4520-81bf-45078ad91a1b)

### How do you run Weblate?

Docker container

### Weblate versions

weblate 5.6.2
postgres 13

### Weblate deploy checks

```shell
While I should probably resolve those issues, I do not think that this is related to the issue of sending to many emails. 

System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.6.2/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.6.2/admin/backup.html
```

### Additional context

Thanks for the amazing translation platform, I really love it and if you need any help from my side debugging this let me know.

**Comment by nijel** [comment]
There are definitely solutions to rate-limit error mails from Django (see https://djangosnippets.org/snippets/2242/, https://stackoverflow.com/q/2052284 or https://github.com/netbox-community/netbox/issues/5023). The tricky part is that these rely on some storage to store the information about rate-limiting and that was unavailable in your case. So, depending on how it would be implemented, you would end up with no mails (because of rate-limiter not handling not accessible Redis) or all mails (because rate-limiting being skipped due to unreachable Redis).

**Comment by vabene1111** [comment]
Hi, thank you for your suggestions. I will probably opt to disable mails for now or implement one of the workarounds. 

This issue is mainly meant to improve "default configuration instances" for people unaware something like this might happen. Maybe someone has a smart idea how to solve this or if you consider this up to the user please feel free to just close the issue :)

**Comment by nijel** [comment]
There is no smart solution to this - if you have no storage available, there is nowhere to store rate-limiting information.

**Comment by bemoty** [comment]
Hi, I'm having the exact same issue and would like to disable these automated mails completely. I read through the documentation but just could not find any information on how to do so. Can you tell me how you did it? @vabene1111 :sweat_smile:

**Comment by vabene1111** [comment]
sorry, haven't turned it off yet. I would hope that there is a setting in the environment or something to just turn sending error messages off. I will try to remember posting here when I do it, for now its no issue since I freed the space and solved the issue that caused it to fill up.

**Comment by nijel** [comment]
I've just added WEBLATE_ADMIN_NOTIFY_ERROR setting in f86d7aef98ec10fdc04198d378e047a028cc1621.
