### ISSUE TITLE
add gitlab login

### ISSUE THREAD

**Issue by glensc** [WeblateOrg/weblate#1219]
Would be nice to have GitLab login as well:

https://demo.weblate.org/accounts/login/?next=/

maybe it's not just configured in demo, but maybe it needs additional code support to allow login from GitLab.com or any gitlab on premise installation
##

**Comment by glensc** [comment]
i found this blog:
http://widerin.net/blog/weblate-gitlab-oauth-login/

seems [python-social-auth](https://github.com/omab/python-social-auth) doesn't have gitlab:
https://github.com/omab/python-social-auth/tree/v0.2.21/social/backends

and no ticket or PR either there

**Comment by glensc** [comment]
filed ticket there: https://github.com/omab/python-social-auth/issues/1011

**Comment by nijel** [comment]
I can certainly enable it on demo and Hosted Weblate once it's supported in python-social-auth.

**Comment by nijel** [comment]
There seems to be GitLab support in new social-core module:

 https://github.com/python-social-auth/social-core/blob/a1267852252a4b9a7cdb3ed54402be9d93496571/social_core/backends/gitlab.py

So we will get it for free once #1307 is implemented.

**Comment by glensc** [comment]
yeah, sorry i already forgot i created issue here as well

ps the actual PR was https://github.com/python-social-auth/social-core/issues/2

**Comment by nijel** [comment]
Now available on Hosted Weblate.

**Comment by glensc** [comment]
can you add it to demo as well?

https://demo.weblate.org/accounts/login/?next=/

**Comment by nijel** [comment]
Now it's there :-).
