### ISSUE TITLE
User definied translation flags

### ISSUE THREAD

**Issue by buhtz** [WeblateOrg/weblate#12204]
### Describe the problem

I have my own po-file-syntax-checking helper script. Some checks are false positive.
I would like to have translation flags to deactivate some of the checks for specific checks.
But Weblate does not allow user defined (unknown) flags: "Error in parameter extra_flags: Invalid translation flag: "ignore-placeholder-compare"

For example "python-brace-format" is to broad/complex and check to many things at once. Just using "ignore-python-brace-format" would disable some checks I don't want to have disabled.

### Describe the solution you would like

User defined translation flags should be allowed. Maybe in a separate field.

**Comment by nijel** [comment]
Weblate doesn't restrict what flags you store in the PO file. The flags entered in Weblate need to be supported by Weblate. If you want some custom behavior, you're welcome to contribute checks implementing that.

**Comment by buhtz** [comment]
I see. OK, then I would like to have "flags entered in Weblate" could be allowed also for "unsupported" flags.

**Comment by buhtz** [comment]
I think I misunderstand something.

"flags entered in Weblate" seem not to appear in the po file. Am I right or am I doing something wrong?

**Comment by nijel** [comment]
Yes, flags are Weblate specific and can be hardly saved to the files. Most formats actually do not support them. And if the format supports them, it might impose limits. For example, the gettext tools reject any unknown flag (see https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html for a list of supported ones).

**Comment by buhtz** [comment]
How do the gettext tools reject unknown flags? I was able to process my po files without problems.

I also saw that "unknown flags" in the po-files are displayed in Weblate. See: https://translate.codeberg.org/translate/backintime/common/uk/?checksum=668e9454c2bb54eb

**Comment by nijel** [comment]
I know that `msgmerge` silently discards them. Not sure about other tools.

Yes, Weblate parses anything present there.

**Comment by buhtz** [comment]
> I know that `msgmerge` silently discards them. Not sure about other tools.

The other gettext tools don't. I can confirm.

> Yes, Weblate parses anything present there.

It can parse unknown flags and display them, but do not allow them to be added. That is inconsistent behavior.

**Comment by nijel** [comment]
Weblate does not store flags set in Weblate to the translation files, and I don't think this should change.

**Comment by buhtz** [comment]
> Weblate does not store flags set in Weblate to the translation files, and I don't think this should change.

I didn't knew that. This is unexpected from my point of view. OK, then your comments make more sense. But I am assuming that this isn't clear to all users/admins.

**Comment by nijel** [comment]
Weblate doesn't save any additional content it allows to attach to strings (screenshots, comments, suggestions, ...) so it's pretty consistent.
