### ISSUE TITLE
The source string type was misidentified

### ISSUE THREAD

**Issue by yangyangdaji** [WeblateOrg/weblate#12216]
### Describe the issue

Weblate recognized the html syntax as plain text, which made it very difficult to translate.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

https://hosted.weblate.org/translate/jamulus/qos-windows/zh_Hans/?checksum=43295f7f720adde0

### Screenshots

![IMG_20240807_101908](https://github.com/user-attachments/assets/9fcecabe-1d15-4114-9b56-15740f085317)

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 5.6.x  (I can't find version info)

**Comment by nijel** [comment]
Weblate just displays a comment present in the PO file here:

https://github.com/jamulussoftware/jamuluswebsite/blob/628943e60ad9c73d615ac913a101b40744052ce2/_translator-files/po/zh_CN/QOS-Windows.po#L71-L95
