### ISSUE TITLE
Customize download

### ISSUE THREAD

**Issue by chenpindong** [WeblateOrg/weblate#12236]
### Describe the issue

Customize download
After successfully downloading, there is no response when clicking to download again. You need to refresh the interface to download again

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

![image](https://github.com/user-attachments/assets/3bb43b0f-dbd1-428c-af04-425e37ba2878)

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
The button is disabled upon submit to avoid people clicking repeatedly when the download takes some time to build. I am not sure if there is a way to re-enable the button once the download has actually completed.
