### ISSUE TITLE
In Insights menu, the name of the project is not displayed.

### ISSUE THREAD

**Issue by BoFFire** [WeblateOrg/weblate#12247]
### Describe the issue

Hi,

When I go to Insights menu, Recent additions on mobile, I cannot see the name of the project or the component recently added.

Web browser used : Fennec F-Droid.

More here : https://mstdn.fr/@ButterflyOfFire/112942225180483392

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

When I go to Insights menu, Recent additions on mobile, I cannot see the name of the project or the component recently added.

### Screenshots

![IMG_20240811_083138](https://github.com/user-attachments/assets/21f323a5-7d64-4694-81b9-57b0d99e3442)

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
@meel-hd https://github.com/WeblateOrg/weblate/pull/12129 breaks on smaller screens as it hides other content:

[Záznam obrazovky z 2024-08-12 10-35-39.webm](https://github.com/user-attachments/assets/82e400a0-cf93-474c-935a-2a044c5201c9)
