### ISSUE TITLE
Translations gone after git push or git pull

### ISSUE THREAD

**Issue by RogerGodefroy** [WeblateOrg/weblate#1224]
### Steps to reproduce
- Import the project
- Add another language to the component
- Translate some items
- Commit in weblate
- Commit and push to the git branch from developers (outside weblate)
- Pull the changes from remote
### Actual behaviour

After the pull the added language with some translations is totally gone
### Expected behaviour

After the pull the translations should still be available in weblate
### Server configuration

Currently testing on docker image with weblate 2.5
##

**Comment by nijel** [comment]
Weblate is quite old, but that should not matter much.

What Merge style do you have set for translation component? Also how did the file disappear in the git repository, can you see it from logs?

**Comment by RogerGodefroy** [comment]
In git it is still intact... only in weblate the language is completely gone. We use 'merge' as merge style. The file itself is committed to git and readable, but in Weblate I would only see the english base language and not the dutch anymore. We also tried to git pull and git push from the commandline on the docker image and then the projects remains ok. So using the buttons in the project for the git commands are doing some more than only a "git pull" and "git push"?

**Comment by nijel** [comment]
The buttons are pretty much doing same as the commands, just scans for changes afterwards. Maybe there is parse error in the file (not sure how 2.4 would report that)?
