### ISSUE TITLE
Brazilian Portuguese requests 3 types of plurals, only 2 are needed

### ISSUE THREAD

**Issue by lucasmz-dev** [WeblateOrg/weblate#12274]
### Describe the issue

Maybe I'm a bad translator but I have noticed I always have to translate 3 fields, when in English, only 2 are used. I haven't really seen any use for this in Portuguese, maybe I just didn't understand this, but pretty much always, I end up having to copy the last translation into "many". Keeping it empty causes a warning, if this warning is ignored, when it is put into a commit, there's still the 'many' field, but it's empty. (can this cause issues? I'm unsure.)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Translate a plural to PT-BR

### Expected behavior

Only two options to appear, the single and other, which would cover a single item, and everything else.

### Screenshots

![image](https://github.com/user-attachments/assets/cf259f8b-f5c1-4576-b9cc-83082112a87c)
![image](https://github.com/user-attachments/assets/cb169e01-80ec-4d3f-92e7-98a10a817a26)

### How do you run Weblate?

weblate.org service

### Additional context

Example: https://hosted.weblate.org/translate/microg/play-services-core-plurals/pt_BR/?checksum=36957d95a47e8a96&sort_by=-priority,position

Example of commit where this is ignored: https://github.com/z-huang/InnerTune/pull/1360/commits/ea5933040ec7a698f0c79fd4deba37388ff8df42#diff-33eb97878bc1c93d6b6371526b256ce286ecbff23bda6bb385c80bc5104bf1f4R122

**Comment by nijel** [comment]
The Weblate behavior matches CLDR specification: http://www.unicode.org/cldr/charts/44/supplemental/language_plural_rules.html#pt. The *Many* option is used when the number is multiple of 1000000 (Weblate shows this as well).

**Comment by lucasmz-dev** [comment]
Ahhhhhh! Understand it now. Thanks for the explanation. OMW to replace a bunch of strings.
