### ISSUE TITLE
Managing and Optimizing the Handling of Large Volumes of User Notifications in Projects

### ISSUE THREAD

**Issue by dxdx123** [WeblateOrg/weblate#12283]
### Describe the problem

In my project, there are often a large number of user notifications occurring, resulting in the Celery queue having a vast number of notifications to process, sometimes reaching hundreds of thousands. This can cause Weblate to block other tasks, such as machine translation, for an extended period. Is there a way for administrators to cancel such notifications? Or is there a setting that can prevent notifications from being sent?

### Describe the solution you would like

Is there a way for administrators to cancel such notifications? Or is there a setting that can prevent notifications from being sent?

### Screenshots

![image](https://github.com/user-attachments/assets/1fe4af66-b87a-4c20-b2ce-d0b92a5b24ce)

### Additional context
celery-notify stderr | [2024-08-16 16:07:45,439: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[4cf280b7-f639-4bfb-a282-6a2151248e71] received
celery-notify stderr | [2024-08-16 16:07:45,619: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[e2f986d3-eb11-4c6a-9f0b-d006c43493a4] received
celery-notify stderr | [2024-08-16 16:07:46,360: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[91378c2a-a3b1-4c98-838b-f097c61d499e] received
celery-notify stderr | [2024-08-16 16:07:46,574: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[8e7805b6-6270-4c04-9dd3-d0f625d61094] received
celery-notify stderr | [2024-08-16 16:07:46,827: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[6f0abeae-0ee4-4ed5-898d-fc9ef0628e91] received
celery-notify stderr | [2024-08-16 16:07:46,991: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[a04630e0-50b7-4a35-90e5-8f83207a2c6e] received
celery-notify stderr | [2024-08-16 16:07:47,854: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[c022a97b-3fde-4f5d-a224-6e7e8ad97651] received
celery-notify stderr | [2024-08-16 16:07:48,080: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[d1164a4f-984c-468e-bb6a-c1b45a9c98e3] received
celery-notify stderr | [2024-08-16 16:07:48,238: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[98603961-b53e-49e8-9882-9970e6e8f7f8] received
celery-notify stderr | [2024-08-16 16:07:49,208: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[5d3e50ec-8b09-4a27-ad75-ecf2c7b1c49a] received
celery-notify stderr | [2024-08-16 16:07:49,211: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[53c40357-56af-4604-beec-1d538f6233aa] received
celery-notify stderr | [2024-08-16 16:07:49,373: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[2e3b9f80-3192-4696-b92d-f39146e40a35] received
celery-notify stderr | [2024-08-16 16:07:50,650: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[d21918de-45c0-431a-9b9c-759d7a87eca0] received
celery-notify stderr | [2024-08-16 16:07:50,652: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[70125892-4dd5-456b-acf3-053e728c19dd] received
celery-notify stderr | [2024-08-16 16:07:50,872: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[55269927-9682-44f0-adb3-6b4767f9e361] received
celery-notify stderr | [2024-08-16 16:07:51,058: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[d561aa8c-6c18-4e8f-8df3-6f20ad88bce9] received
celery-notify stderr | [2024-08-16 16:07:51,989: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[3b7d2151-ceaa-4c71-a71e-ce43063d133c] received
celery-notify stderr | [2024-08-16 16:07:52,301: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[3a9ea4e1-681f-4a34-84b3-73ff7182e22d] received
celery-notify stderr | [2024-08-16 16:07:52,584: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[98b3ab0f-fd96-45f3-bb5d-d43b77370cc7] received
celery-notify stderr | [2024-08-16 16:07:52,741: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[13809699-190e-4fd6-83b4-6747c0070dae] received
celery-notify stderr | [2024-08-16 16:07:53,370: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[8a54e4d0-3109-469b-b3ff-8e485b83c0fa] received
celery-notify stderr | [2024-08-16 16:07:54,458: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[3c7cd077-6fc4-4557-9a0f-c3584f1581bc] received
celery-notify stderr | [2024-08-16 16:07:54,694: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[1b5f840a-d53b-4c3a-ad30-c7bc2b899b8a] received
celery-notify stderr | [2024-08-16 16:07:55,011: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[b6f0877e-f5a5-425d-a4ac-341cdf02f832] received
celery-notify stderr | [2024-08-16 16:07:55,179: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[526ec62b-d7d5-43f2-98de-7045a2316748] received
celery-notify stderr | [2024-08-16 16:07:55,835: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[3dbafb01-a0b2-4a66-938e-57ed1b5eb6ae] received
celery-notify stderr | [2024-08-16 16:07:55,994: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[3d92bf14-544d-47d3-bf99-797cc1d31198] received
celery-notify stderr | [2024-08-16 16:07:56,617: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[5cccc9f7-5ed7-4ec0-90bc-bdd943f48298] received
celery-notify stderr | [2024-08-16 16:07:56,919: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[845e5b22-eb56-4990-ac59-1a7e2418b6f2] received
celery-notify stderr | [2024-08-16 16:07:57,101: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[fd96800d-44d5-4281-a0f4-da68d652a41f] received
celery-notify stderr | [2024-08-16 16:07:57,676: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[b35543f2-da4d-46d0-91c9-58944b7b859e] received
celery-notify stderr | [2024-08-16 16:07:58,022: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[2e0a1d9b-c7d2-4bfe-baba-040734ca1219] received
celery-notify stderr | [2024-08-16 16:07:58,185: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[ffd2b50a-9926-4350-9498-dc79939ca658] received
celery-notify stderr | [2024-08-16 16:07:58,656: INFO/MainProcess] Task weblate.accounts.tasks.notify_change[59837094-c98d-45c3-94ea-1185f7982ba6] received

_No response_

**Comment by nijel** [comment]
The notifications are in a separate queue and processed by a separate worker, so these do not block anything else.

Furthermore, Weblate 5.6 improved notifications' performance, so if you are on an older version, consider upgrading.
