### ISSUE TITLE
Support <html dir=""> when translating HTML

### ISSUE THREAD

**Issue by nclm** [WeblateOrg/weblate#12325]
### Describe the problem

When translating HTML files, Weblate automatically detects the `lang` attribute in `<html lang="en" dir="ltr">` and offers it to be replaced by the target language code.

However, it does not detects the `dir` attribute, that should be either `ltr` or `rtl` depending on language.

So you can end up with `<html lang="ar" dir="ltr">` by mistake.

### Describe the solution you would like

It would be therefore very good to have either:
- The `dir` attribute detected and offered for translation like `lang` is.
- The `dir` attribute changed automatically depending on the language.

If there is no `dir` attribute in the source HTML, we could even imagine it being added when it’s not the same as the source language.

### Describe alternatives you have considered

For now, `dir="auto"` can be used, and it might work in many cases, but it’s not recommended as it depends on the browser detecting certain characters. Having it set clearly as we know the content language anyway is better.

CSS can also be used to change the direction depending on the language used (something like `html[lang="ar"] { direction: rtl; }`) but it not advised to use CSS rather than HTML for this, and it also require adding all languages manually in the stylesheet.

The best is still to have the `dir` attribute changed by Weblate.

**Edit:** Just for information, I’m using the Weblate hosted at https://translate.codeberg.org

**Comment by nijel** [comment]
Needs to be implemented in translate-toolkit, probably here: https://github.com/translate/translate/blob/47c3819aef6998bde5a1e8c2d142eadad79e3967/translate/storage/html.py#L334-L338

**Comment by nclm** [comment]
Alright thanks! Opened https://github.com/translate/translate/issues/5322

**Comment by nijel** [comment]
Closing in favor of issue in the translate-toolkit.
