### ISSUE TITLE
New Check: This untranslated string was translated once

### ISSUE THREAD

**Issue by emmapeel2** [WeblateOrg/weblate#1232]
Sometimes, in my case because of bad configuration (merge/pull from remote repository) a user translation can be lost.
But the history of the string shows it had a translation once.

t would be great to have a check for "untranslated strings that were translated before" so we don't loose contributions because of a failed merge/reset, or can recover them.

I scratched some queries on the django shell, the basics are:

`if (trans_unit.translated == False)`

and in the trans_unit.change_set.all()

`if (change.action == 5L)`

(if the string is untraslated and in it's history there is an action 5, which I think it is 'translation added')
##

**Comment by nijel** [comment]
We do have [symbolic names for actions](https://github.com/WeblateOrg/weblate/blob/master/weblate/trans/models/change.py#L171) ;-). Anyway you probably want to rather look for all actions in [ACTIONS_CONTENT](https://github.com/WeblateOrg/weblate/blob/master/weblate/trans/models/change.py#L251) as these are the ones where content is set or changed.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by emmapeel2** [comment]
Happy that my naturally annoying pickiness can be put to use!

Thanks for the feature!  	♥
