### ISSUE TITLE
Automatic configuration of Content Security Policy form-action for Social Auth

### ISSUE THREAD

**Issue by michael-smt** [WeblateOrg/weblate#12321]
### Describe the problem

The stricter Content Security Policy since Weblate 5.7 requires careful configuration of the [`CSP_FORM_SRC`](https://docs.weblate.org/en/latest/admin/config.html#std-setting-CSP_FORM_SRC) when using social authentication providers, because [some browsers block redirects after a form submission](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/form-action).

### Describe the solution you would like

It would be nice if enabling a social auth provider would also automatically set the appropriate `form-action` Content Security Policy header values.

For example when `WEBLATE_SOCIAL_AUTH_AUTH0_DOMAIN` is configured it could be automatically added to `WEBLATE_CSP_FORM_SRC`.

### Describe alternatives you have considered

Describe the required setting of `CSP_FORM_SRC` in the [social provider documentation](https://docs.weblate.org/en/latest/admin/auth.html#social-authentication) based on the experience from hosted.weblate.org.

### Additional context

Depending on the provider (Auth0, possibly also others) there might be additional redirects to other authentication providers, these could not be automatically configured.

**Comment by nijel** [comment]
The intention was to handle that automatically, but the code doesn't cover all the cases:

https://github.com/WeblateOrg/weblate/blob/9259f38c138ac0e78f961a90d2b5e817d6306a53/weblate/middleware.py#L336-L347

PS: There is also https://github.com/WeblateOrg/weblate/issues/12302
