### ISSUE TITLE
QR codes are inverted in dark mode

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#12359]
### Describe the issue

https://hosted.weblate.org/accounts/auth/tokens/totp/ with dark mode selected at the top of https://hosted.weblate.org/accounts/profile/#preferences fails to register.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Download https://f-droid.org/en/packages/com.xinto.mauth/
2. Try to scan a code
3. Fail
4. Also try it in Catima
5. Still fail

Doesn't seem to be a thing
https://github.com/bennyguitar/BTCDonationViewController/issues/1

### Expected behavior

Would expect it to be black and white like the regular one is.

### Screenshots

The same top square in:

black

![bilde](https://github.com/user-attachments/assets/c68331a0-19a7-4489-9de9-be1a018c332e)

(the dark gray as opposed to black probably doesn't help)
vs
normal
![bilde](https://github.com/user-attachments/assets/af705e88-cc20-4075-b6c6-8e1df5553950)

### How do you run Weblate?

weblate.org service

### Additional context

Maybe also put the code in the middle of the screen to help with finding focus.

Edit: Can't actually make 2FA work on Weblate at all, but maybe that is just me.

**Comment by nijel** [comment]
Scanning the QR code in dark mode works just fine using [Aegis](https://f-droid.org/packages/com.beemdevelopment.aegis/) where I tested it. But let's make it standard white/black for compatibility reasons.
