### ISSUE TITLE
OIDC and other identity provider buttons not working in version 5.7

### ISSUE THREAD

**Issue by mrpotato3** [WeblateOrg/weblate#12358]
### Describe the issue

Since version 5.7 of Weblate, clicking the OIDC button or any other identity provider buttons does nothing. There is no redirection to the authentication provider, and no visible error is displayed on the interface. Instead, it only returns an HTTP 302 response on the /oidc route. Additionally, no errors are logged on the server side.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Configure OIDC provider
2. Go to login section and click "OIDC" button
3. Result is nothing

### Expected behavior

Redirect to OIDC provider

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
Should be already fixed by https://github.com/WeblateOrg/weblate/pull/12322.
