### ISSUE TITLE
Add Kabyle to Google Machinery

### ISSUE THREAD

**Issue by BoFFire** [WeblateOrg/weblate#12362]
### Describe the problem

Hi,

Google Translate added recently a list if new language amont which we can find `Tamazight`. A lot of people notices that this berber language was trained on a corpus language which is in majority `Kabyle` [I'm Kabyle speaker].

### Describe the solution you would like

This is why I suggest to add mapping `Tamazight` to `Kabyle` on Weblate by setting `ber-Latn` to point towards `kab` in the adequate machinery.

Please check the structure of the URL and if API responds well :
https://translate.google.com/?sl=en&tl=ber-Latn&text=Hello!&op=translate

On LibreTranslate, we use :

https://translate.fedilab.app/?source=en&target=kab&q=Hello%21

**Comment by nijel** [comment]
Isn't this merely a bug on Google's side which will likely be addressed?

**Comment by BoFFire** [comment]
Hi,
I'm working to introduce a PR for this.
