### ISSUE TITLE
Key added to repository but missing in hosted Weblate

### ISSUE THREAD

**Issue by ahus1** [WeblateOrg/weblate#12365]
### Describe the issue

A new key "requiredAction.webauthn-register" was added in our repository: https://github.com/keycloak/keycloak/commit/2a64caf3fd967fae402fc1e606f9b10390342ed3 but it is not present in Weblate.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

The string is not present in Hosted Weblate: https://hosted.weblate.org/projects/keycloak/theme-baselogin/en/?q=%20context:requiredAction.requiredAction.webauthn-register#search

While a different old string from the same file is present: https://hosted.weblate.org/translate/keycloak/theme-baselogin/en/?q=context%3ArequiredAction.webauthn-register-passwordless&sort_by=-priority%2Cposition&checksum=

### Expected behavior

String should be present

### Screenshots

![image](https://github.com/user-attachments/assets/e81d7c31-3dff-40a1-b8d5-4f7ec4340200)

### How do you run Weblate?

weblate.org service

### Additional context

The rebase was triggered using the API after the change was committed to our main repository: 

![image](https://github.com/user-attachments/assets/54c51c4e-6549-496f-8d79-16ef525de87f)

**Comment by x-sheep** [comment]
I'm having problems with new keys not appearing in Hosted Weblate too. `Manage > Repository maintenance > Rescan` is a workaround.

**Comment by ahus1** [comment]
Thank you for letting me know of this workaround! I'll wait for another 1-2 days to allow the people maintaining the hosted Weblate to secure logs and other information they might need.
