### ISSUE TITLE
Notifications are undelivered

### ISSUE THREAD

**Issue by snrnsp** [WeblateOrg/weblate#12384]
### Describe the issue

I'm in charge of translating a project. I adjusted the project to send an email if there were any changes or additions in a language. It was working well, but I accidentally went into the project today and found that new changes were registered. I checked my email because I didn't check the notification, but it didn't come. I didn't touch the settings additionally, and there were no changes, but I decided it was an error for the phenomenon that the notification suddenly didn't come. I also checked the spam in my email box, but I don't have it. Can you solve this?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

I've been keeping the settings, so I can't figure out the cause.

### Expected behavior

I need to be informed of the change of the string by e-mail, or additional information.

### How do you run Weblate?

Other

### Additional context

I understand that the project is powered by a cloud server built by the company, not by a weblate server. Originally, it was used as a weblate server, but due to a serious error, it was changed to run on its own server. Maybe. I don't think this and the notification are related, but I informed you to keep that in mind

**Comment by nijel** [comment]
Check the server logs and celery queues. Upgrading Weblate might also help.
