### ISSUE TITLE
Commonwealth/United Kingdom English 

### ISSUE THREAD

**Issue by Secret-Peter** [WeblateOrg/weblate#12386]
### Describe the problem

I’d like to have Blender in British English.

### Describe the solution you would like

If the en_UK language pack were available, I would devote my time to changing the grammar.

### Describe alternatives you have considered

Or don’t bother. I realise it isn’t a priority task for the team.

### Additional context

I’ve never worked on Weblate, so there may be some mistakes, but I would do my best.

**Comment by nijel** [comment]
Please discuss this at Blender forums. They also have a documentation for adding new language: https://docs.blender.org/manual/en/4.0/contribute/translations/add_language.html
