### ISSUE TITLE
DeepL ICU invalid placeholders position

### ISSUE THREAD

**Issue by junekpavel** [WeblateOrg/weblate#12398]
### Describe the issue

When using DeepL Automatic suggestions for translations with ICU message format, the ICU placeholders is always invalid. It's always placed to the beginning of the translated string, as visible on attached screenshot. 

It works correctly only for English, but for any other languages its broken.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Setup project with `icu-message-format` flags
2. Setup DeepL Automatic suggestions
3. Create new translation in ICU format
4. Show suggestions for different language

### Expected behavior

The ICU placeholder should be placed in a correct position in the translated string.

### Screenshots

![CleanShot 2024-09-02 at 16 36 14](https://github.com/user-attachments/assets/e9b9d10a-6f67-4074-b9a0-634f23536af9)

![CleanShot 2024-09-02 at 16 37 52](https://github.com/user-attachments/assets/67ac70a3-f17a-4b9a-9e64-c04a910e45c3)

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.7
 * Django: 5.0.8
 * siphashc: 2.4.1
 * translate-toolkit: 3.13.3
 * lxml: 5.3.0
 * pillow: 10.4.0
 * nh3: 0.2.18
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.2
 * django-crispy-forms: 2.3
 * oauthlib: 3.2.2
 * django-compressor: 4.5.1
 * djangorestframework: 3.15.2
 * django-filter: 24.3
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.15.4
 * rapidfuzz: 3.9.6
 * openpyxl: 3.1.5
 * celery: 5.4.0
 * django-celery-beat: 2.6.0
 * kombu: 5.4.0
 * translation-finder: 2.16
 * weblate-language-data: 2024.5
 * html2text: 2024.2.26
 * pycairo: 1.26.1
 * PyGObject: 3.48.2
 * diff-match-patch: 20230430
 * requests: 2.32.3
 * django-redis: 5.4.0
 * hiredis: 3.0.0
 * sentry-sdk: 2.13.0
 * Cython: 3.0.11
 * mistletoe: 1.4.0
 * GitPython: 3.1.43
 * borgbackup: 1.4.0
 * pyparsing: 3.1.2
 * ahocorasick_rs: 0.22.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * cyrtranslit: 1.1.1
 * Python: 3.12.5
 * Git: 2.39.2
 * psycopg: 3.2.1
 * psycopg-binary: 3.2.1
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.7.0
 * boto3: 1.34.160
 * zeep: 4.2.1
 * aeidon: 1.15
 * iniparse: 0.5
 * mysqlclient: 2.2.4
 * Mercurial: 6.8.1
 * git-svn: 2.39.2
 * git-review: 2.4.0
 * PostgreSQL server: 16.4
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.eu.mailgun.org
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.15.0-84-generic (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
    HINT: https://docs.weblate.org/en/weblate-5.7/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
    HINT: https://docs.weblate.org/en/weblate-5.7/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 5.7.1.
    HINT: https://docs.weblate.org/en/weblate-5.7/admin/upgrade.html

System check identified 6 issues (2 silenced).
```

**Comment by nijel** [comment]
This seems to be an issue on DeepL side.

It is indeed broken for Czech:

Request:
```json
{
  "text": [
    "Ahoj, <x></x>!"
  ],
  "target_lang": "DE", 
  "source_lang": "CS", 
  "tag_handling": "xml",
  "ignore_tags": ["x"] 
}
```

Response:

```json
{"translations":[{"detected_source_language":"CS","text":"<x></x>Hallo, !"}]}
```

But works for English:

Request:

```json
{
  "text": [
    "Hello, <x></x>!"
  ],
  "target_lang": "DE", 
  "source_lang": "EN", 
  "tag_handling": "xml", 
  "ignore_tags": ["x"] 
}
```

Response

```json
{"translations":[{"detected_source_language":"EN","text":"Hallo, <x></x>!"}]}
```
