### ISSUE TITLE
Unable to disable email

### ISSUE THREAD

**Issue by bartvdbraak** [WeblateOrg/weblate#12390]
### Describe the issue

We run a staging environment of Weblate in which we want to have emails disabled, but seem to be unable to get this working.

We run the `docker-compose-https.yml` with overrides in `docker-compose-https.override.yml`, in which we specified:
```yaml
services:
  weblate:
    environment:
      EMAIL_BACKEND: 'django.core.mail.backends.dummy.EmailBackend'
```

Unfortunately this doesn't seem to work since we are still getting errors about email tasks timing out, e.g.:

```
TimeoutError 
weblate.accounts.tasks.send_mails

New
Level: Error
[Errno 110] Connection timed out

Message
Could not initialize e-mail backend
```

And in `list_versions`:

```
(venv) weblate@fac4d715897e:/$ weblate list_versions
...
 * Email setup: django.core.mail.backends.smtp.EmailBackend: 127.0.0.1
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. **Clone the Weblate repository (or create a similar setup):**
   ```bash
   git clone https://github.com/WeblateOrg/docker-compose.git
   cd docker-compose
   ```

2. **Prepare the Docker Compose files:**

   1. Copy the `docker-compose-https.yml` to use as your base setup:
      ```bash
      cp docker-compose-https.yml docker-compose-https.override.yml
      ```

   2. Edit the `docker-compose-https.override.yml` to disable emails using the dummy backend:
      ```yaml
      services:
        weblate:
          environment:
            EMAIL_BACKEND: 'django.core.mail.backends.dummy.EmailBackend'
      ```

3. **Build and bring up the Docker containers:**
   ```bash
   docker-compose -f docker-compose-https.yml -f docker-compose-https.override.yml up --build -d
   ```

4. **Check the Weblate configuration:**

   - Enter the Weblate container:
     ```bash
     docker-compose exec weblate bash
     ```

   - List the current configuration to see the email backend being used:
     ```bash
     . /app/venv/bin/activate
     weblate list_versions
     ```

   - You may observe that the email backend is still set to `django.core.mail.backends.smtp.EmailBackend` instead of the `dummy.EmailBackend`.

5. **Trigger an email event:**

   - Try to trigger an action that would normally send an email (e.g., creating a new user or sending a test email).
   - Monitor the logs for any timeout errors related to email tasks.

     ```bash
     docker-compose logs -f weblate
     ```

   - If emails are not disabled, you'll see errors like:
     ```
     TimeoutError 
     weblate.accounts.tasks.send_mails

     New
     Level: Error
     [Errno 110] Connection timed out

     Message
     Could not initialize e-mail backend
     ```

### Expected behavior

- Despite setting `EMAIL_BACKEND` to `'django.core.mail.backends.dummy.EmailBackend'` in the override file, Weblate still attempts to use the SMTP backend, leading to connection timeouts.

### How do you run Weblate?

Docker container

### Weblate versions

```
 * Weblate: 5.7.1
 * Django: 5.1
 * siphashc: 2.4.1
 * translate-toolkit: 3.13.3
 * lxml: 5.3.0
 * pillow: 10.4.0
 * nh3: 0.2.18
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.2
 * django-crispy-forms: 2.3
 * oauthlib: 3.2.2
 * django-compressor: 4.5.1
 * djangorestframework: 3.15.2
 * django-filter: 24.3
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.15.4
 * rapidfuzz: 3.9.6
 * openpyxl: 3.1.5
 * celery: 5.4.0
 * django-celery-beat: 2.7.0
 * kombu: 5.4.0
 * translation-finder: 2.16
 * weblate-language-data: 2024.6
 * html2text: 2024.2.26
 * pycairo: 1.26.1
 * PyGObject: 3.48.2
 * diff-match-patch: 20230430
 * requests: 2.32.3
 * django-redis: 5.4.0
 * hiredis: 3.0.0
 * sentry-sdk: 2.13.0
 * Cython: 3.0.11
 * mistletoe: 1.4.0
 * GitPython: 3.1.43
 * borgbackup: 1.4.0
 * pyparsing: 3.1.4
 * ahocorasick_rs: 0.22.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * cyrtranslit: 1.1.1
 * Python: 3.12.5
 * Git: 2.39.2
 * psycopg: 3.2.1
 * psycopg-binary: 3.2.1
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.7.1
 * boto3: 1.35.9
 * zeep: 4.2.1
 * aeidon: 1.15
 * iniparse: 0.5
 * mysqlclient: 2.2.4
 * Mercurial: 6.8.1
 * git-svn: 2.39.2
 * git-review: 2.4.0
 * PostgreSQL server: 16.4
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: 127.0.0.1
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 6.8.0-41-generic (x86_64)
```

### Weblate deploy checks

```shell
(venv) weblate@9b4a815645e6:/$ weblate check --deploy
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail (timed out), please check EMAIL_* settings.
        HINT: https://docs.weblate.org/en/weblate-5.7.1/admin/install.html#out-mail
```

### Additional context

All email related environment variables:
```
(venv) weblate@9b4a815645e6:/$ env
...
WEBLATE_ADMIN_EMAIL=admin@example.org
WEBLATE_EMAIL_HOST=smtp.eu.mailgun.org
EMAIL_BACKEND=django.core.mail.backends.dummy.EmailBackend
WEBLATE_NO_EMAIL_AUTH=0
WEBLATE_EMAIL_HOST_USER=translate@example.org
WEBLATE_SERVER_EMAIL=translate@example.org
WEBLATE_EMAIL_HOST_PASSWORD=none
WEBLATE_DEFAULT_FROM_EMAIL=translate@example.org
```

**Comment by nijel** [comment]
It needs `WEBLATE_` prefix same as other variables, see https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_EMAIL_BACKEND

**Comment by bartvdbraak** [comment]
Ah that's a dumb oversight on my part. Thanks @nijel!
