### ISSUE TITLE
Non-existing progress view for project

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#12413]
### Describe the issue

#11717 introduced redirecting to progress page on repository operations. It uses the same redirect for project/category/component/translation scopes, but the view only supports only component and translation scopes:

https://github.com/WeblateOrg/weblate/blob/bf2a2c46649785703f6e816b6c948df1fc3b5831/weblate/trans/views/settings.py#L348

Thus, when a user performs an operation on project or category scope, it ends up on HTTP 404 Not Found.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to project repository maintenance
2. Click on rescan
3. See HTTP 404

### Expected behavior

The actual progress should be shown

### How do you run Weblate?

weblate.org service

**Comment by mont29** [comment]
Uuuuh indeed...

Not sure what are Groups here?

For Projects, how would you suggest fixing this? Adding a Progress view for projects as well? Not sure what it would mean/represent though. Or redirect to `/projects/my-project/` instead?

**Comment by nijel** [comment]
Sorry, it should have been category, I was writing this rushing.

There can be multiple components in progress for both project and category. I'm not sure whether it's a good idea to include logs for all of them on a single page. But it could probably show a progress bar for each of them, there is existing support for this in the client code using `data-task` attribute.
