### ISSUE TITLE
2.8 - home page for visitors - change back to project list.

### ISSUE THREAD

**Issue by fisharebest** [WeblateOrg/weblate#1241]
After upgrading to 2.8, the home page (dashboard) has changed for visitors (who are not logged in).

Before the upgrade, this was a list of projects.

After the upgrade, this is a list of the components/languages with suggestions.

How do I to change this back?

I tried changing the account profile for user "anonymous", but this makes no difference.
##

**Comment by nijel** [comment]
Just a side note: It's not list of components with suggestions, but list of components suggested for contribution (basically the ones which matching language to current user and with some not translated strings).

**Comment by nijel** [comment]
I don't think listing all projects is good idea for default homepage. This might work for small installations, but definitely does not scale for installations with hundredths of projects.

**Comment by burner1024** [comment]
@nijel you're right, but for those of us who don't have hundreds of projects, could you point out which which file to edit if we wanted to just display all components, not filtering on language or status?

**Comment by nijel** [comment]
If you don't add components too often, you can create [component list](https://docs.weblate.org/en/latest/admin/componentlists.html) with all of them and that will add the list with all to your dashboard.

You will have to adjust the code to make it default though, probably in weblate/trans/views/basic.py, the home function.

**Comment by nijel** [comment]
`Profile.DASHBOARD_COMPONENT_LIST` should be the value you want there.

**Comment by burner1024** [comment]
I couldn't get it to work with component list, and anyway it doesn't have same stats and translate button. So in the end I went with this:
```     # Grab all untranslated translations
     base = Translation.objects.prefetch().filter(
         subproject__project_id__in=project_ids,
-    ).exclude(
-        total=F('translated'),
     ).order_by(
         '-translated'
```

**Comment by nijel** [comment]
The listing should be same, what do you miss in the component lists view?

**Comment by burner1024** [comment]
there are only 3 columns for anonymous user, see screenshot
<img width="1175" alt="screen shot 2017-03-23 at 9 31 29 am" src="https://cloud.githubusercontent.com/assets/1279852/24229372/a4d61832-0fab-11e7-86c3-40219281db02.png">

**Comment by nijel** [comment]
Well it is, because there is no language set for the anonymous user, and we're listing just components here and not individual translations. But this is indeed inconsistent, I'll adjust the code to show translations in both cases.

**Comment by nijel** [comment]
I've just realized that this can be made configurable really simple - there already is profile for anonymous user, so it's just matter of using values stored there.

**Comment by nijel** [comment]
Changes in git which will allow you to achieve this:

* You can now create automatic component list assignment to automatically have all components in component list
* You can edit anonymous user profile to change dashboard shown to unauthenticated users

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
