### ISSUE TITLE
After upgrade to 5.6.2 we have duplicated teams

### ISSUE THREAD

**Issue by eleveoadmin** [WeblateOrg/weblate#12429]
### Describe the issue

Hi,

after upgrade to 5.6.2, do not remember exact original version, we've got in instance duplicated teams which is not possible to delete.

- Users
- Users (2)
- Viewers
- Viewers (2)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Upgrade instance from ~5.0 to 5.6.2 (5.0 -> 5.1 -> 5.2 -> 5.3, etc...)

### How do you run Weblate?

PyPI module

**Comment by nijel** [comment]
The teams were IMHO present before, they just had the same name and migration had changed that.
