### ISSUE TITLE
cannot login with openSUSE id

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#12421]
### Describe the issue

I am unable to login using openSUSE id.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to https://l10n.opensuse.org/
2. Click to Sign in
3. I am redirected to an empty page https://l10n.opensuse.org/accounts/login/opensuse/

### Expected behavior

Redirect to openSUSE login page

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate Hosted 5.7.1

**Comment by nijel** [comment]
This is because https://www.opensuse.org/openid/user/ is unreachable and that is used as OpenID endpoint (see https://github.com/python-social-auth/social-core/blob/d9554fa40e751c85ae60231fe2f5bd5a528c4452/social_core/backends/suse.py#L11). Is that still valid?

**Comment by nijel** [comment]
It's actually the whole www.opensuse.org being down, not just this endpoint: https://www.isitdownrightnow.com/opensuse.org.html

**Comment by nijel** [comment]
But Weblate should not crash in such case and let user know what is wrong...
