### ISSUE TITLE
Changes log CSV is limited to 2000 entries

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1245]
CSV download of changes log is limited to 2000 entries (2001 lines CSV) without any visible support for selecting this value or pagination support.
### Steps to reproduce
1. Go to https://l10n.opensuse.org/changes/?project=yast-autoinst&subproject=master
2. Click to download icon
3. See the file
### Actual behaviour

Only latest 2000 changes are logged
### Expected behaviour

Be able to download all changes
### Server configuration

```
Weblate 2.6
Python 2.7.9
Django 1.8.4
six 1.9.0
python-social-auth 0.2.7
Translate Toolkit 1.14.0-rc1
Whoosh 2.7.0
Git 1.8.5.6
Pillow (PIL) 1.1.7
dateutil 2.4.2
lxml 3.2.3
django-crispy-forms 1.5.2
compressor 1.5
djangorestframework 3.3.3
pytz 2013.9
pyuca N/A
Database backends: django.db.backends.mysql
```
##

**Comment by nijel** [comment]
Indeed this limit is currently hardcoded: https://github.com/nijel/weblate/blob/master/weblate/trans/views/changes.py#L244

**Comment by nijel** [comment]
Not sure if it's worth extending or rather adding changes to the API where we would get pagination for free...

**Comment by stanislav-brabec** [comment]
If it will not be extended, then the comment should not say "Download all changes" but "Download latest 2000 changes".
