### ISSUE TITLE
Plural keys do not get updated on Weblate after xlf import

### ISSUE THREAD

**Issue by gerardgalofre** [WeblateOrg/weblate#12450]
### Describe the issue

Describe the problem

I download an xlf from a weblate project, translate it in a CAT tool, import it back to weblate. All keys get updated with translations except for the keys that are set up as plural keys on Weblate. 

Plural keys appear OK in the xlf, transalted, and no alterations to the metadata were made.

Describe alternatives you have considered

I have tried doing the same with all the formats available to export / import and none of the formats imports the plurals back correctly to weblate. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. go to a component in weblate
2. go to a language
3. go to "files", "customize download" 
4. download xlf 1.1 or any other format
5. transalte downloaded file in a cat tool 
6. upload transaltion (add translation, replace approved translations too)
7. see upload report saying some keys were skipped 
8. check the plural keys

### Expected behavior

all keys to be updated with the xlf content, including plural keys 

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Can you try uploading without the blank `<target/>` element?
