### ISSUE TITLE
OpenAI Automatic suggestions with `==WEBLATE_PART==`

### ISSUE THREAD

**Issue by junekpavel** [WeblateOrg/weblate#12456]
### Describe the issue

When using automatic translations via OpenAI, the translated string is tripled and the `==WEBLATE_PART==` is added to the translations. Only happens when the key is marked as "Approved", for keys marked as "Needs editing", the translations behave correctly.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. setup OpenAI auto suggestion
2. try to auto-translate any approved string

### Expected behavior

The string should be translated correctly.

### Screenshots

![CleanShot 2024-09-10 at 07 33 50](https://github.com/user-attachments/assets/fffc10a3-a2f8-44f6-8ccf-13441f4a00d8)

![CleanShot 2024-09-10 at 07 39 42](https://github.com/user-attachments/assets/1e7e68f1-07d3-48b8-bc7a-04d67b2a3f87)

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.7
 * Django: 5.0.8
 * siphashc: 2.4.1
 * translate-toolkit: 3.13.3
 * lxml: 5.3.0
 * pillow: 10.4.0
 * nh3: 0.2.18
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.2
 * django-crispy-forms: 2.3
 * oauthlib: 3.2.2
 * django-compressor: 4.5.1
 * djangorestframework: 3.15.2
 * django-filter: 24.3
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.15.4
 * rapidfuzz: 3.9.6
 * openpyxl: 3.1.5
 * celery: 5.4.0
 * django-celery-beat: 2.6.0
 * kombu: 5.4.0
 * translation-finder: 2.16
 * weblate-language-data: 2024.5
 * html2text: 2024.2.26
 * pycairo: 1.26.1
 * PyGObject: 3.48.2
 * diff-match-patch: 20230430
 * requests: 2.32.3
 * django-redis: 5.4.0
 * hiredis: 3.0.0
 * sentry-sdk: 2.13.0
 * Cython: 3.0.11
 * mistletoe: 1.4.0
 * GitPython: 3.1.43
 * borgbackup: 1.4.0
 * pyparsing: 3.1.2
 * ahocorasick_rs: 0.22.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * cyrtranslit: 1.1.1
 * Python: 3.12.5
 * Git: 2.39.2
 * psycopg: 3.2.1
 * psycopg-binary: 3.2.1
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.7.0
 * boto3: 1.34.160
 * zeep: 4.2.1
 * aeidon: 1.15
 * iniparse: 0.5
 * mysqlclient: 2.2.4
 * Mercurial: 6.8.1
 * git-svn: 2.39.2
 * git-review: 2.4.0
 * PostgreSQL server: 16.4
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.eu.mailgun.org
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.15.0-84-generic (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
    HINT: https://docs.weblate.org/en/weblate-5.7/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
    HINT: https://docs.weblate.org/en/weblate-5.7/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 5.7.1.
    HINT: https://docs.weblate.org/en/weblate-5.7/admin/upgrade.html

System check identified 6 issues (2 silenced).
```

**Comment by nijel** [comment]
Related to #11806, we should switch to a different approach for multiple strings.
