### ISSUE TITLE
Not receiving digests from Hosted Weblate

### ISSUE THREAD

**Issue by lucasmz-dev** [WeblateOrg/weblate#12467]
### Describe the issue

When notifications are set to be received in digests, no digest is received.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Configure notifications to be received in a daily digest
2. "Wait" for something that'll trigger a notification
3. No e-mail is received, even after waiting for days, leaving users unaware of new strings to translate

### Expected behavior

Notifications for digests should work fine.

### Screenshots

![image](https://github.com/user-attachments/assets/50b8d53b-7c14-47fb-b18f-c8f3a241a53b)
![image](https://github.com/user-attachments/assets/d2544635-ae90-4966-a718-ef82d8164058)
![image](https://github.com/user-attachments/assets/591da6c1-d0e9-43f0-b252-1a3ca6944455)

### How do you run Weblate?

weblate.org service

### Additional context

Receiving instant notifications is spammy, literally just yesterday because of setting up a component again, I got an e-mail for every string added, hence using daily notifications is better, except for some reason I never receive notifications if I have it set to daily digest.

This seems to work fine when I'm using other instances such as toolate.othing.xyz or translate.codeberg.org, just for me Hosted Weblate just doesn't work.

**Comment by nijel** [comment]
Can you please share a screenshot of your notification settings?

**Comment by lucasmz-dev** [comment]
@nijel added in the issue!

**Comment by nijel** [comment]
Do you remember for which project didn't the notification arrive?

**Comment by nijel** [comment]
Okay, let's keep this open for now. But there is no known issue with digest notifications, and there is no reason why it should behave differently between different servers.

**Comment by lucasmz-dev** [comment]
Example: https://hosted.weblate.org/translate/aurora-store/fastlane/pt_BR/?q=state:%3Ctranslated#history
Did not get notified for this
Did not get notified for anything in this meantime at all. If I were to switch to instant notifications, it would work right away, but would also spam me.

**Comment by lucasmz-dev** [comment]
Is there a way to know if a change is live?

**Comment by nijel** [comment]
It was deployed now.
