### ISSUE TITLE
Source comments are rendered too small

### ISSUE THREAD

**Issue by ib** [WeblateOrg/weblate#12479]
### Describe the problem

A source comment is important information for the translator, but it is rendered very small:

```
.source-comment {
...
  font-size: 12px;
}
```

### Describe the solution you would like

`font-size: 14px;` would make the comment more noticeable without distracting from translating.

### Screenshots

12px:
![12px](https://github.com/user-attachments/assets/57aed0ab-669c-4c46-987c-62e23a43849c)
14px:
![14px](https://github.com/user-attachments/assets/43fb03e1-1b91-414a-b757-8c0c80ee3f06)

**Comment by nijel** [comment]
The comment is also rendered full-size in the sidebar. Do you find it useful in both locations?

**Comment by ib** [comment]
> Do you find it useful in both locations?

Yes, it's useful in the string information sidebar, and it looks fine there.

**Comment by nijel** [comment]
The question is whether it makes sense to show it in *both* places.

**Comment by ib** [comment]
> The question is whether it makes sense to show it in _both_ places.

The important place is the label at the source string, because this is where a translator sees it best.

In my opinion it's okay to put it in the sidebar. A msgctxt is also displayed in both places.

**Comment by meel-hd** [comment]
I'll go ahead and increase the font size for now.
