### ISSUE TITLE
Hosted weblate: Translations components scheduled for removal are never removed

### ISSUE THREAD

**Issue by Crismon96** [WeblateOrg/weblate#12477]
### Describe the issue

We are hosting our project over hosted weblate. No matter if I remove existing translation components (I have created them via the API before) via the UI or an API delete request they are never removed, now weeks after.
In the UI I get a success message like "Your component is scheduled for removal"

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to a component hosted on hosted weblate
2. Prompt it for deletion
3. After a success message, nothing really happens

### Expected behavior

The component is removed in a timely manner.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Can you please share which component you tried to remove? Either here, or privately to care@weblate.org.

**Comment by nijel** [comment]
Duplicate of #12627
