### ISSUE TITLE
Hosted weblate: Downtime is too high

### ISSUE THREAD

**Issue by Crismon96** [WeblateOrg/weblate#12478]
### Describe the issue

About every second time I try to request hosted weblate its down. It's good software and a cheap service to host it, dont get me wrong, it's nice to use it. 
Why is the downtime perceived as so high?
Were this recent issues or is the only option to self host everything?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go online 10am CET and weblate is offline for about 1/5 of the time in the recent 2 months.

### Expected behavior

Communicate expected and unexpected downtimes more clearly. Reduce them to a necessary minimum.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Can you please write to care@weblate.org with additional information about the time you observed this and your IP address? We will investigate our logs if you aren't affected by some of our anti-DoS measures.

We're under constant DDoS for the past months, and it might have happened that some measures are too aggressive and blocking legitimate users.
