### ISSUE TITLE
Multiple instances of one language in language selector

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#12481]
### Describe the issue

There are 4 nb_NOs

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to https://hosted.weblate.org/new-lang/flirtual/attributes/
2. Select nb_NO
3. There are more than one

### Expected behavior

Expected there to be just the one

### Screenshots

![Skjermavbildning fra 2024-09-12 22 36 07](https://github.com/user-attachments/assets/c383751a-1030-4be6-835e-2bcb08f328b7)

### How do you run Weblate?

weblate.org service

### Additional context

I requested nb_NO yesterday.

**Comment by nijel** [comment]
Most likely caused by https://github.com/WeblateOrg/weblate/pull/12469, looking into fix.

**Comment by comradekingu** [comment]
@nijel https://hosted.weblate.org/new-lang/flirtual/attributes/ still lists many nb_NOs, and even more of "pl".

**Comment by nijel** [comment]
Yes, the fix was not yet deployed.
