### ISSUE TITLE
Improve biome checker configuration

### ISSUE THREAD

**Issue by meel-hd** [WeblateOrg/weblate#12489]
### Describe the issue

The `pre-commit`  command shows linting issues in files that are not modified by the current commit or branch.

The weird part is it raises this issues only when there is an issue with the files you actually modified. If the issues raised by the changes you made are fixed the `pre-commit`  doesn't show the issues with the other files you didn't modify.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Introduce a dummy and  unused variable (to raise an issue within the file you modified).
2. Stage the changes `git add .`
3. Run `pre-commit run -all` (this will say there is an issue with an unused var we introduced and step 1, plus a ton of other issues in other files'
4.  Remove the unused variable we introduced in step 1 and `git add  .`;
5. Then re run the `pre-commit` command. (now that the issue we introduced is fixed the command no longer shows the other issues in the other files'

### Expected behavior

- Show only the issues with the files that are actually modified.
- The other issues should be fixed separately to avoid this behavior

### Screenshots
I introduced the variable in another file. But it says there is issues with `zen.js` which I didn't modify.
![image](https://github.com/user-attachments/assets/227d3b95-a7bc-47e8-9929-27d89565d796)

### How do you run Weblate?

Other

**Comment by nijel** [comment]
I think it shows warnings, but only it fails on error. That's why you see more issues than changed. Probably biome should be configured better (either to not report warnings or to fail on them and fix underlying issues). https://biomejs.dev/guides/configure-biome/ has the documentation.
