### ISSUE TITLE
git log message is confusing if Weblate internal URL is used

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1248]
If a project has "links" using Weblate internal URL, the git change log is insufficient to identify changes.
### Steps to reproduce
1. Create a project with links using Weblate internal URL
2. Make some edits
3. Watch the changes.
### Actual behaviour

Confusing:

Translated using Weblate (Portuguese (Brazil))
Currently translated at 100.0% (51 of 51 strings)

Translated using Weblate (Portuguese (Brazil))
Currently translated at 100.0% (13 of 13 strings)

https://github.com/yast/yast-translations/commits/master
### Expected behaviour

If the change log contains percentage, it should show name of the project (or directory) relevant to the percentage. Otherwise the percentage in the log makes no sense. For example:

yast-control-center: Translated using Weblate (Portuguese (Brazil))
Currently translated at 100.0% (13 of 13 strings)
### Server configuration

```
Weblate 2.6
Python 2.7.9
Django 1.8.4
six 1.9.0
python-social-auth 0.2.7
Translate Toolkit 1.14.0-rc1
Whoosh 2.7.0
Git 1.8.5.6
Pillow (PIL) 1.1.7
dateutil 2.4.2
lxml 3.2.3
django-crispy-forms 1.5.2
compressor 1.5
djangorestframework 3.3.3
pytz 2013.9
pyuca N/A
Database backends: django.db.backends.mysql
```
##

**Comment by nijel** [comment]
You can already customize commit message per component, see https://docs.weblate.org/en/latest/admin/projects.html#commit-message

The question is whether it makes sense to change the default one to be more verbose.

**Comment by nijel** [comment]
I think it would make sense to extend default commit message:

- Include project and component name
- Include URL of the translation

This way it is clear where the translation did happen and it's easier to fix it there as well.
