### ISSUE TITLE
Github pull request does not work as expected

### ISSUE THREAD

**Issue by antonin-kozak** [WeblateOrg/weblate#12484]
### Describe the issue

Hi, I have reported a bug #12472 which was fixed, but I think the root case is different.
Creating a component with "Github pull request" doesn't work and when I change the "Version control system" of a component from Git to Github pull request after the creation, the above mentioned bug occured.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Save GITHUB_CREDENTIALS in settings.py file
2. Start creating a new component
3. As "Version Control System" select "Git pull request"
- The UI allows to select a file with translations (**JSON nested structure file**), but when the component is created, I can see only the source language and it's empty (no strings)
![obrazek](https://github.com/user-attachments/assets/87bc0610-7f20-4059-9645-ec220ee6dd64)

4. Go to the settings of the component and change Version control system to Git
- The component correctly loads other languages and all the strings.
![obrazek](https://github.com/user-attachments/assets/71254168-9e30-498c-aff4-375c0ba82519)

5. Go to the settings and change it to Github pull requests again
- After a translations change, Weblate creates a pull request correctly
6. Go to the settings and change "Merge style" to "Merge without fast-forward"
- The error page described in #12472 is displayed
- To get rid of the error, change back to "Git" is needed

### How do you run Weblate?

Other

**Comment by nijel** [comment]
Did you restart celery workers? I think the check will happen if them and if not restarted they will not see change in settings and thus will not have enabled GitHub backend.

**Comment by antonin-kozak** [comment]
Thanks, restart helped. Sorry, then no bug it is - although the behaviour when the server haven't been not fully restarted is kind of strange.
