### ISSUE TITLE
VCS: Repository branch selector

### ISSUE THREAD

**Issue by lars3141** [WeblateOrg/weblate#12487]
### Describe the problem

For some features, new string are introduced. These features are developed on separate feature branches, which will also include the newly developed strings. In some cases, we want to edit the new strings already in the feature branch before it is merged. Weblate does currently not have access to these strings because they will not be available in the repository branch.

### Describe the solution you would like

For our purposes, a workflow, which can be triggered by the user, would solve the issue: A repository branch selector, which has the following functionality:
- give a dropdown of all available branches (optional) alternatively a text field
- upon confirmation, the repository branch would be changed and the Weblate repository would be reset
- due to the danger potential of this, the user would be asked to confirm the switch. All not committed changes would need to be committed and pushed.

We understand that this feature heavily alters the way Weblate interacts with repositories. In a way, it makes the local Weblate Repo less relevant. Many issues arise if a bigger number of translators work on the same project. We would therefore to make this feature only accessible via the configuration files.

**Comment by nijel** [comment]
You can already choose "Additional branch" when creating a new component, and it will duplicate the component but for a selected branch. This is definitely a safer approach to dealing with a feature branches than changing the main component as you propose. See also https://docs.weblate.org/en/latest/admin/projects.html#adding-translation-projects-and-components
