### ISSUE TITLE
Stale overview of strings status

### ISSUE THREAD

**Issue by ib** [WeblateOrg/weblate#12502]
### Describe the issue

What steps are required or should be taken to get up-to-date statistics after the fix in #12486?

Here is another example: Two ["Failing check: Unchanged translation"](https://hosted.weblate.org/projects/xarchiver/translations/fr/) which have been dismissed (this time manually) 5 hours ago.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Have an unchanged translation
2. Dismiss it
3. Open overview

### Expected behavior

The overview of the strings status should update after the dismissal.

### How do you run Weblate?

weblate.org service

**Comment by ib** [comment]
After the above mentioned failed checks had disappeared in the meantime (due to automatic change commit?), two already dismissed "Reused translation" checks have now reappeared after an API upload (with replace-approved).

**Comment by nijel** [comment]
The fix was not yet deployed to Hosted Weblate, so this is most likely the same issue as #12486. Did you happen to see this this week as well?

**Comment by ib** [comment]
Due to the attempt to save non-breaking spaces with colons in the French translation, there have been numerous commits in the meantime, so that there are no more open failed checks.

However, two strings that were already approved are waiting for review again after an API upload (with replace-approved).

Whether the overview will be updated remains to be seen after #11237 is fixed (pull request will follow) … hopefully my seemingly unapprovable project will still be accessible then.

**Comment by ib** [comment]
It works now.
