### ISSUE TITLE
Number of contributors is one too high

### ISSUE THREAD

**Issue by ib** [WeblateOrg/weblate#12503]
### Describe the issue

The number of contributors on every info page for [this project](https://hosted.weblate.org/projects/xarchiver/translations/) is one too high. The info page says "n contributors", but when you click on it, it only shows n-1 icons. Who or what is the missing contributor?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Contribute or let contribute
2. See the info page

### Expected behavior

The number of contributors should match the number of icons displayed.

### How do you run Weblate?

weblate.org service

**Comment by ib** [comment]
Now the number seems to be correct, but when clicking on it, **all** contributors of the project are shown.

**Comment by nijel** [comment]
It seems to work just fine for me, can you please create a separate issue for that describing how to reproduce?

**Comment by Geeyun-JY3** [comment]
@nijel It is quite easy to reproduce now.
![image](https://github.com/user-attachments/assets/26fc958a-b0de-4c63-af68-ac2022207539)
![image](https://github.com/user-attachments/assets/5780c4d1-1871-4f88-9a63-730af7a776cd)
