### ISSUE TITLE
Filter notifications only for particular language

### ISSUE THREAD

**Issue by V-Z** [WeblateOrg/weblate#1253]
### Steps to reproduce
1. Go to user settings, notifications
2. Check some notifications
3. Wait
### Actual behaviour

User gets notifications from all languages.
### Expected behaviour

User should be able to select language(s) for notifications. Typically it'll probably be only the translated language.
### Server configuration

https://l10n.opensuse.org/

Similar points were discussed in issue #1047 and others.
##

**Comment by nijel** [comment]
User should get only notifications on languages he has selected (+ some which are project wide such as merge failure).

**Comment by V-Z** [comment]
But I get notifications for _all_ languages. :-(

**Comment by nijel** [comment]
What kind notifications? Also what languages do you have selected in https://l10n.opensuse.org/accounts/profile/#languages ?

**Comment by V-Z** [comment]
I have set only Czech. And I do receive notifications about comments and changes in all other languages.

**Comment by nijel** [comment]
That indeed should not happen...

**Comment by nijel** [comment]
Do you receive notifications about both comments and changes? For comments this might be due to confusing comment scope which is by default set to source string (see https://github.com/WeblateOrg/weblate/issues/1060 and https://github.com/WeblateOrg/weblate/issues/1259) and as such is sent to all translators.

**Comment by V-Z** [comment]
I'm confused about the "source" comments. I receive comments written in English, but they refer to various languages (e.g. .../projects/libzypp/master/it/...), which is weird. Regarding changes, I recently receive mainly new translation projects for also another languages, requests to add new languages, etc. It can be related to #1060.

**Comment by nijel** [comment]
Okay, the comments are indeed confusing, I've changed default scope which should make most people comment in scope of translation rather than project wide.

As for the new language requests, these are currently not filtered by added language, I've clarified the form to indicate that:

![user_profile_ _weblate_-_2016-12-14_17 11 07](https://cloud.githubusercontent.com/assets/212189/21189887/545ed2d2-c220-11e6-8200-bd42549e5115.png)

**Comment by V-Z** [comment]
Great, I think this should solve this problem. Thank You. Just tiny note, in the printscreen above You have "...yourtranslated..." (the space is missing). :-)

**Comment by V-Z** [comment]
Sorry, one more point to clarify. Merge is done on project level, so that merge operation is for all languages in same time, correct?
Czech translation for "Notification on new language request" is confusing, because it says "Upozornění na požadavky o nový překlad". IMHO something like "Upozornění na požadavek na překlad *do nového jazyka*" would be better.

**Comment by nijel** [comment]
@V-Z Space added, Czech translation updated (you could have done it yourself at https://hosted.weblate.org/projects/weblate/master/cs/ ;-).

**Comment by V-Z** [comment]
OK, next time. ;-)

**Comment by V-Z** [comment]
![notifikace](https://cloud.githubusercontent.com/assets/6032665/21424106/e3c2f770-c840-11e6-845f-8df6bea491c3.png)
Sorry, I'm confused. I have above settings of notifications. I thought I'm supposed to receive only comments respective for my translated language. I really don't need Greek comments as in the mail below. ;-)
![screenshot_20161222_122235](https://cloud.githubusercontent.com/assets/6032665/21424194/7b2a8ed4-c841-11e6-97be-666c8bbd8d1c.png)
So, how do I set it to receive only comments for my translated language?

**Comment by nijel** [comment]
By default comment scope was global, so it was handled like comment on the source string, thus sent to all translators. The default value has been changed in https://github.com/WeblateOrg/weblate/commit/e57494c5b23d505d72af59e67733f86225a0de9e.

**Comment by V-Z** [comment]
OK, so that comments are going to be specific per language?

**Comment by nijel** [comment]
By default yes.
