### ISSUE TITLE
Leave the date range selection blank by default

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#12558]
### Describe the problem

(While my current main use case is the **Change period** section of the bottom Search menu on the Changes page, I think it makes sense to apply it to all places where the date range selection is used.)

Currently the data range selection is set as today by default. Therefore, clicking the `Search` button in the bottom Search menu on the Changes page, without doing anything in the bottom Search menu, would by default search today’s changes.

### Describe the solution you would like

Leave the date range selection blank by default.

### Screenshots

![image](https://github.com/user-attachments/assets/f4a167c0-bdb3-4057-8ca4-8156fdec0196)

**Comment by nijel** [comment]
@harriebird The date range should have the same defaults as it used to have before #11894 and #11826. The reports should default to last 30 days, while changes should default to blank (no filtering).

**Comment by harriebird** [comment]
Hi guys, check my PR #12608 for this issue.
