### ISSUE TITLE
Unable to add Apertium APy authomatic suggestions because "en>de" pair is missing

### ISSUE THREAD

**Issue by jmontane** [WeblateOrg/weblate#12579]
### Describe the issue

I use a private Apertium APy instance, without en>de lang pair. If I try to add Apertium APy authomatic suggestions to Weblate I get an error because my Apertium server answers a 400 error (because en>de pair isn't available).

You can reproduce the same effect trying to add Apertium APY authomatic suggestions with official Apertium APy URL: https://apertium.org/apy/, because it lacks en>de pair too.

`Could not fetch translation:: 400 Client Error: Bad Request for url: https://apertium.org/apy/translate?langpair=en%7Cde&q=test&markUnknown=no`

So, Apertium APY is unusable. I guess the issue is in [this line](https://github.com/WeblateOrg/weblate/blob/main/weblate/machinery/base.py#L150), because settings validation has a translation en>de test hardcoded.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Try to add an Apertium authomatic suggestions using an APy URL without en>de language pair support
2. Click on Save settings
3. An error occours

### Expected behavior

I expected a test using an avaliable language pair at APy server were used.
Alternatively, provide a field to indicate a custom language pair for testing and validate settings.

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
The validation args used to be overridable until e6f25dca9eab700eec0c712b6fe52a71850df4a1, but none class needed that, so these were inlined (what makes type checking easier). I guess a more complex logic could be introduced to handle a varying list of supported languages.
