### ISSUE TITLE
Too many nearby strings cause long render time

### ISSUE THREAD

**Issue by HealYouDown** [WeblateOrg/weblate#12594]
### Describe the issue

We have translation keys in the format of `<code>.title`, `<code>.description, ...`. Nearly strings loads all available translations, despite having the `NEARBY_MESSAGES` settings set to a low number.

This causes each new translation page to load for about 15-20s.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Have many keys
2. Click translate
3. Wait a long time :)

### Expected behavior

We expect to see a low number of available strings, not a list of all translation keys and their text.

### Screenshots

![grafik](https://github.com/user-attachments/assets/be944c3a-87cd-4de1-934a-889849d7382a)

### How do you run Weblate?

Docker container

### Weblate versions

5.7.2

### Weblate deploy checks

```shell
* Weblate: 5.7.2
 * Django: 5.1.1
 * siphashc: 2.4.1
 * translate-toolkit: 3.13.3
 * lxml: 5.3.0
 * pillow: 10.4.0
 * nh3: 0.2.18
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.2
 * django-crispy-forms: 2.3
 * oauthlib: 3.2.2
 * django-compressor: 4.5.1
 * djangorestframework: 3.15.2
 * django-filter: 24.3
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.16.1
 * rapidfuzz: 3.9.7
 * openpyxl: 3.1.5
 * celery: 5.4.0
 * django-celery-beat: 2.7.0
 * kombu: 5.4.1
 * translation-finder: 2.16
 * weblate-language-data: 2024.6
 * html2text: 2024.2.26
 * pycairo: 1.27.0
 * PyGObject: 3.50.0
 * diff-match-patch: 20230430
 * requests: 2.32.3
 * django-redis: 5.4.0
 * hiredis: 3.0.0
 * sentry-sdk: 2.14.0
 * Cython: 3.0.11
 * mistletoe: 1.4.0
 * GitPython: 3.1.43
 * borgbackup: 1.4.0
 * pyparsing: 3.1.4
 * ahocorasick_rs: 0.22.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * cyrtranslit: 1.1.1
 * Python: 3.12.6
 * Git: 2.39.5
 * psycopg: 3.2.2
 * psycopg-binary: 3.2.2
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.7.1
 * boto3: 1.35.21
 * zeep: 4.2.1
 * aeidon: 1.15
 * iniparse: 0.5
 * mysqlclient: 2.2.4
 * Mercurial: 6.8.1
 * git-svn: 2.39.5
 * git-review: 2.4.0
 * PostgreSQL server: 16.4
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.dummy.EmailBackend: 127.0.0.1
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://weblate_redis:6379/1, redis://weblate_redis:6379/1, regular
 * Platform: Linux 6.8.0-45-generic (x86_64)
```

**Comment by nijel** [comment]
`NEARBY_MESSAGES` configures just the default value, what is the actual value configured in the user profile?

Another reason might be that the string location is not properly parsed and thus making all strings on a single location. What file format do you use?

**Comment by HealYouDown** [comment]
The config value in the user profile is set to `1`.

We used a nested JSON file in the following format with ~1200 keys:

```json
{
    "key1": {
        "title": "",
        "description": "",
        "mission_1": "",
        ...
    },
    "key2": {
        ...
    },
    "key3": {
        ...
    }
}
```
