### ISSUE TITLE
Changing the comment scope

### ISSUE THREAD

**Issue by dg0yt** [WeblateOrg/weblate#1259]
Sometimes I would like to change the scope of comments from source to translation and vice versa. People make mistakes here. Deleting and re-adding the comment doesn't preserve the original poster.
##

**Comment by nijel** [comment]
The comment scope is not really intuitive (see https://github.com/nijel/weblate/issues/1060). The question is how to make it better...

**Comment by nijel** [comment]
I think that current way it works way better, so I think editing is no longer necessary.
