### ISSUE TITLE
Add pagination also to the top of the Changes page

### ISSUE THREAD

**Issue by ib** [WeblateOrg/weblate#12601]
### Describe the problem

When searching for something on the Changes page, it is inconvenient to always scroll to the bottom of the page to move forward or backward.

### Describe the solution you would like

A second pagination at the top of the page would be helpful.

**Comment by nijel** [comment]
With the current implementation, there can be only one paginator on page, see f8160c48216bbc15f9d8ded95640dc23ce09392c and #6888. @meel-hd can you please look into that? Adding second one to the page is just matter of additional include in the page, but in the current implementation the editing of page does not work on second one:

```diff
diff --git weblate/templates/trans/change_list.html weblate/templates/trans/change_list.html
index 88147fed97..2fc41c67ce 100644
--- weblate/templates/trans/change_list.html
+++ weblate/templates/trans/change_list.html
@@ -35,6 +35,8 @@
 
 {% block content %}
 {% if form.is_valid %}
+  {% include "paginator.html" %}
+
   {% include "last-changes-content.html" with last_changes=object_list %}
 
   {% include "paginator.html" %}
```

**Comment by Het4304** [comment]
Hi i am interested in solving the issue can you assign it to me?? @nijel @ib

**Comment by nijel** [comment]
@Het4304 This issue is already assigned to @meel-hd

**Comment by meel-hd** [comment]
@nijel  I'm on it
