### ISSUE TITLE
\"xxxxx\"  will be convert to "\xxxxx"\   when exporting  Arabic strings

### ISSUE THREAD

**Issue by gs-xpeng** [WeblateOrg/weblate#12626]
### Describe the issue

\"xxxxx\"  will be convert to "\xxxxx"\   when exporting  Arabic strings

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. add a new string for Arabic  with "نعم (إستعمال "\نعم"\ فقط إذا كان الوسيط يدعم الاجابة 484)"
2. export the Arabic  in customize download , the string will be convert to 
![image](https://github.com/user-attachments/assets/fc65c226-ee11-4e37-84ca-88ed1dded0a4)
 "نعم (إستعمال \"نعم\" فقط إذا كان الوسيط يدعم الاجابة 484)"

### Expected behavior

the \" should not be convert to "\

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
What file format do you use? What Weblate and translate-toolkit versions do you use?

**Comment by gs-xpeng** [comment]
> What file format do you use? What Weblate and translate-toolkit versions do you use?
PO format  Weblate 5.6.2   translate-toolkit 3.13.3

**Comment by nijel** [comment]
In PO format, quotes need to be escaped, so adding a backslash in the file is expected. Where exactly do you observe it?
