### ISSUE TITLE
Instead of the specified number of contributors to a language, all contributors are shown

### ISSUE THREAD

**Issue by ib** [WeblateOrg/weblate#12637]
### Describe the issue

The number of contributors shown on the language info page is correct, but clicking on it shows **all** contributors to the project.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Open https://hosted.weblate.org/projects/xarchiver/translations/de/#information
2. 1 contributor is shown
3. Click on it
4. All contributors to the project are shown

(or try https://hosted.weblate.org/projects/xarchiver/translations/fr/#information with 3 contributors)

### Expected behavior

The actual contributors should be shown.

### How do you run Weblate?

weblate.org service

**Comment by ib** [comment]
The bug still exists when selecting Project **→** Languages **→** Language **→** Info, as [here](https://hosted.weblate.org/projects/xarchiver/-/de/#information) for example.

**Comment by nijel** [comment]
#12665 should fix this (as a side effect).
