### ISSUE TITLE
Limit the length of the visual keyboard

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#12687]
### Describe the issue

I have configured 21 special characters where defined in the [User profile](https://hosted.weblate.org/accounts/profile/#preferences). This makes the visual keyboard a bit long and sometimes it overflows the edge of the modal window, the full editor or elsewhere.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to the [`Preferences`](https://hosted.weblate.org/accounts/profile/#preferences) tab of the User profile
2. Configure some special characters
3. Go to the full editor

### Expected behavior

The visual keyboard would not overflow the edge of the modal window, the full editor or elsewhere.

### Screenshots

The full editor in mobile view:
![hosted weblate org_translate_weblate_application_zh_Hans__q=(Pixel 7)](https://github.com/user-attachments/assets/2401aa45-6017-4a16-8c4e-99d58594fb83)

`Add term to glossary` modal window in desktop view:
![image](https://github.com/user-attachments/assets/858c8822-1ac0-4734-ad91-1e083a4a6f9f)

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 5.8-dev

**Comment by meel-hd** [comment]
working on it
