### ISSUE TITLE
"Last author" should not be "None"

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#12696]
### Describe the issue

On a component's Information tab, there's an entry called "Last author", which is not documented but seems to show the name of the user who made the latest translation. However, when Weblate automatically commits translations, the last author will be shown as "None", which is not very useful information.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

e.g. https://hosted.weblate.org/projects/f-droid/f-droid/fi/#information compared to https://hosted.weblate.org/projects/f-droid/f-droid/fi/#history

### How do you run Weblate?

weblate.org service

### Additional context

Hosted Weblate

**Comment by nijel** [comment]
It currently is "user who did last operation on the translation". It used to be "user who did last edit in Weblate" before https://github.com/WeblateOrg/weblate/issues/6548 (what was confusing as well because it did ignore changes coming from the repository).

**Comment by nijel** [comment]
Having a better name would definitely help.

It would be useful to track the last author, but it's currently impossible to track for changes from the repository.

**Comment by tjhietala** [comment]
"Last change made by", perhaps?

**Comment by Fjtg** [comment]
working on
