### ISSUE TITLE
Manually added translations may be duplicated

### ISSUE THREAD

**Issue by voplakal-lukas** [WeblateOrg/weblate#12699]
### Describe the issue

You can add duplicates if you create translation string manually. Especially by using the**Add new translation string** option.
We use monolingual .po files for translation.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to **Component Setting** especially on **Translation** tab and enable **Manage strings** option
2. Go to default language of the component
3. Click on **Tools** then **Add new translation string**
Or you go to URL /projects/<project>/<component>/en/#new
4. Fill **English** with **Test string**
5. Click on Add
6. Repeat second, third and fourth step
7. New sting will be successfully added
8. Search for **Test string**
9. You will find two strings with same name

### Expected behavior

I expect that duplicate strings will not be allowed to be created at component level. This can cause more problems with gettext.

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 5.7.2

**Comment by nijel** [comment]
Are you using context to identify the strings? In that case, Weblate should have generated a unique context for each.

**Comment by voplakal-lukas** [comment]
We don't use context at all. We just want to add translations way before it exists in codebase and try to avoid duplicity. So, this isn't a bug, more like a feature with different description. I didn't know about context and how gettext can handle that. Sorry, my bad.
