### ISSUE TITLE
Incorrect plural information in "CLDR plural with zero"

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#12695]
### Describe the issue

On this page, the information about plural forms is correct, except for "CLDR plural with zero":
https://hosted.weblate.org/languages/fi/#information

The entries in the "One" and "Other" appar to be mixed up: they should be the other way round.

The issue is not limited to Finnish, at least Swedish and English seem to have them mixed up as well:
https://hosted.weblate.org/languages/sv/#information
https://hosted.weblate.org/languages/en/#information

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

See above

### Expected behavior

The CLDR plurals with zero are correct.

### How do you run Weblate?

weblate.org service

### Weblate versions

Hosted Weblate

**Comment by nijel** [comment]
Hmm, this should have been fixed by d6b8c3a38b86e48e559a943a246e0f3c65c725d5, but apparently it doesn't affect already created plural rules.
