### ISSUE TITLE
URL generation error

### ISSUE THREAD

**Issue by vinceh121** [WeblateOrg/weblate#12721]
### Describe the issue

Regression from #12673

Render check image URL because it does not accept negative integers as the unit ID.

Not sure how I let that slide through testing the PR. :confused: 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Create a component with the max-size check
2. Create a unit in the source language and translate it in a target language
3. Add a suggestion to the unit

### How do you run Weblate?

PyPI module

### Weblate versions

5.7.2 with d31f719f18187340083cb13f95c81a70a8045b71 cherry-picked

**Comment by nijel** [comment]
Okay, let's revert #12673 and work on a proper fix in #12723.
