### ISSUE TITLE
Unknown time range picker shown in the footer when logged

### ISSUE THREAD

**Issue by JiDW** [WeblateOrg/weblate#12742]
### Describe the issue

Hello,

Since I upgraded from Weblate 5.0.2 to 5.7.2 (with the docker upgrade), I have this time range picker elements visible in most pages footer.

As I could not find anyone with a similar issue, I'm guessing there must be some kind of CSS cache that got stuck somewhere during the upgrade? I tried to restart weblate multiple times but it did not change anything. I also looked for a potential management command related to a possible cache.
I also disabled my Cloudflare (with "developer mode") to make sure it was not a CDN cache.

It only appears when logged in.

I tried with Chrome and Firefox, browser cache disabled.

Thanks for your help!

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Update from 50.2 to 5.7.2
2. Check the footer area while logged in

### Screenshots

![image](https://github.com/user-attachments/assets/2b00c715-a0f9-46db-ac98-3552431d4e1a)

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.7.2
 * Django: 5.1.1
 * siphashc: 2.4.1
 * translate-toolkit: 3.13.3
 * lxml: 5.3.0
 * pillow: 10.4.0
 * nh3: 0.2.18
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.2
 * django-crispy-forms: 2.3
 * oauthlib: 3.2.2
 * django-compressor: 4.5.1
 * djangorestframework: 3.15.2
 * django-filter: 24.3
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.16.1
 * rapidfuzz: 3.9.7
 * openpyxl: 3.1.5
 * celery: 5.4.0
 * django-celery-beat: 2.7.0
 * kombu: 5.4.1
 * translation-finder: 2.16
 * weblate-language-data: 2024.6
 * html2text: 2024.2.26
 * pycairo: 1.27.0
 * PyGObject: 3.50.0
 * diff-match-patch: 20230430
 * requests: 2.32.3
 * django-redis: 5.4.0
 * hiredis: 3.0.0
 * sentry-sdk: 2.14.0
 * Cython: 3.0.11
 * mistletoe: 1.4.0
 * GitPython: 3.1.43
 * borgbackup: 1.4.0
 * pyparsing: 3.1.4
 * ahocorasick_rs: 0.22.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * cyrtranslit: 1.1.1
 * Python: 3.12.6
 * Git: 2.39.5
 * psycopg: 3.2.2
 * psycopg-binary: 3.2.2
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.7.1
 * boto3: 1.35.21
 * zeep: 4.2.1
 * aeidon: 1.15
 * iniparse: 0.5
 * mysqlclient: 2.2.4
 * Mercurial: 6.8.1
 * git-svn: 2.39.5
 * git-review: 2.4.0
 * PostgreSQL server: 15.3
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: send.smtp.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 6.8.0-45-generic (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

INFOS:
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.7.2/admin/backup.html

System check identified 1 issue (1 silenced).
```

**Comment by meel-hd** [comment]
Working on it

**Comment by nijel** [comment]
@JiDW Can you look into the HTML how does CSS inclusion look like? With `COMPRESS_ENABLED` the styles should be compressed into one or two CSS files and these should be changing on every change. Also, what is your setting for `COMPRESS_CSS_HASHING_METHOD`?
