### ISSUE TITLE
Cross-Project glossary stopped working

### ISSUE THREAD

**Issue by TomKambach** [WeblateOrg/weblate#12756]
### Describe the issue

We have a glossary which is stored for all projects, but is originally located in the project "A".

If, for example, a new glossary term is entered for a translation in the master project (branch master), it is only assigned to the project "A" and no longer appears in the translation for master the next time it is called up. 

Target:
    The overarching glossary must be completely available in all projects, regardless of where terms are added

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

I don't know. The problem has never occurred before.

### Expected behavior

The overarching glossary must be completely available in all projects, regardless of where terms are added

### How do you run Weblate?

Docker container

### Weblate versions

* Weblate: 4.14.1
* Django: 4.1.1
* siphashc: 2.1
* translate-toolkit: 3.7.3
* lxml: 4.9.1
* Pillow: 9.2.0
* bleach: 5.0.1
* python-dateutil: 2.8.2
* social-auth-core: 4.3.0
* social-auth-app-django: 5.0.0
* django-crispy-forms: 1.14.0
* oauthlib: 3.2.1
* django-compressor: 4.1
* djangorestframework: 3.13.1
* django-filter: 22.1
* django-appconf: 1.0.5
* user-agents: 2.2.0
* filelock: 3.8.0
* rapidfuzz: 2.8.0
* openpyxl: 3.0.10
* celery: 5.2.7
* kombu: 5.2.4
* translation-finder: 2.14
* weblate-language-data: 2022.7
* html2text: 2020.1.16
* pycairo: 1.21.0
* pygobject: 3.42.2
* diff-match-patch: 20200713
* requests: 2.28.1
* django-redis: 5.2.0
* hiredis: 2.0.0
* sentry_sdk: 1.9.8
* Cython: 0.29.32
* misaka: 2.1.1
* GitPython: 3.1.27
* borgbackup: 1.2.2
* pyparsing: 3.0.9
* pyahocorasick: 1.4.4
* python-redis-lock: 3.7.0
* charset-normalizer: 2.1.1
* Python: 3.10.7
* Git: 2.30.2
* psycopg2: 2.9.3
* psycopg2-binary: 2.9.3
* phply: 1.2.5
* ruamel.yaml: 0.17.21
* tesserocr: 2.5.2
* boto3: 1.24.73
* zeep: 4.1.0
* aeidon: 1.11
* iniparse: 0.5
* mysqlclient: 2.1.1
* Mercurial: 6.2.2
* git-svn: 2.30.2
* git-review: 2.3.1
* Redis server: 6.2.11
* PostgreSQL server: 13.10
* Database backends: django.db.backends.postgresql
* Cache backends: default:RedisCache, avatar:FileBasedCache
* Email setup: django.core.mail.backends.smtp.EmailBackend: mxs.name.com
* OS encoding: filesystem=utf-8, default=utf-8
* Celery: redis://cache:6379/1, redis://cache:6379/1, regular
* Platform: Linux 6.1.18-200.fc37.x86_64 (x86_64)

**Comment by nijel** [comment]
> Weblate: 4.14.1

You should start with upgrading, the issue has been very likely addressed in the past 2 years.

**Comment by TomKambach** [comment]
As mentioned before, the problem has never occurred before and a few weeks ago for the first time. Before that it always worked with the same Weblate version.
