### ISSUE TITLE
Gitlab merge requests

### ISSUE THREAD

**Issue by crisp2u** [WeblateOrg/weblate#1276]
Guys, what would be the correct approach to implement creation of GitLab Merge Requests when Weblate pushes to GitLab repository ? I'm trying to implement a continous translation flow and I'm not sure how to properly notify developers when translations are pushed from Weblate.

Thanks

**Comment by nijel** [comment]
Assuming that it's pretty much same as GitHub pull requests, you can probably base the code on existing GitHub support - https://github.com/nijel/weblate/blob/master/weblate/trans/vcs.py#L833

**Comment by crisp2u** [comment]
@nijel My python skills are barely at beginner level, but I took a stab using POST_PUSH_SCRIPT written in Python. I got stuck at figuring out the branches that I need for the merge requets, those are not exposed to HOOKS.

Later I might try what you suggested but I need to learn a bit more python and django. I'll post my progress here.

**Comment by bravenoob** [comment]
@crisp2u did you have any success?

Im currently facing a similar problem, creating a pull request for Stash/Bitbucket. Unfortunataly I don't know Python at all :(

**Comment by crisp2u** [comment]
@bravenoob I've managed to write a post_push script that calls GITLAB Rest API, I'll do a cleanup and post it here today. You need to adapt it to the Bitbucket API

**Comment by crisp2u** [comment]
The following script makes A LOT of assumptions:
* it uses GITLAB Rest API v3
* it assumes the target branch is *development*
* assumes that the source branch can be read from WL_BRANCH (an env var that I added in a fork, I'll try to do a PR later) or default to one
* it tries to assign the MR to master based on settings on the project/group

**I post this here as as sample it should not be used as it is by no means. The proper way to do this is how @nijel suggested above!**

```python
#! /usr/bin/env python

import os
import requests
import json
import re

//get repo from env var or default to one
giturl = os.environ.get('WL_REPO','git@gitlab.com:sample_group/sample_repo.git')


user_token = 'XXX'
admin_private_token = 'XXX' // in some cases we need admin access

//get the branch if available otherwise hard code it

branch = os.environ.get('WL_BRANCH','features/translations')
target_branch = 'development'
merge_title = 'Weblate translations'

headers = {'PRIVATE-TOKEN' : user_token}
jenkins_headers = {'PRIVATE-TOKEN' : admin_private_token}


gitre = re.compile('(?P<host>(git@|https://)([\w\.@]+)(/|:))(?P<owner>[\w,\-,\_]+)/(?P<repo>[\w,\-,\_]+)(.git){0,1}((/){0,1})')
url = gitre.match(giturl)
host = url.group(3) 
group_name = url.group(5)
project_name = url.group(6)

print "Searching for project {0} on {1}".format(project_name,host)

r = requests.get("http://{0}/api/v3/projects/search/{1}".format(host,project_name), headers=headers)
project_id = r.json()[0]['id']

//try to assign to a master on project or group
print "Searching for group {0} on {1}".format(group_name,host)
r = requests.get("http://{0}/api/v3/groups?search={1}".format(host,group_name), headers=jenkins_headers)

group_id = r.json()[0]['id']
print "Found group with id:{0}".format(group_id)

membersRequest = requests.get("http://{0}/api/v3/projects/{1}/members/".format(host,project_id), headers=headers)
projectMembers = membersRequest.json()

membersRequest = requests.get("http://{0}/api/v3/groups/{1}/members/".format(host,group_id), headers=headers)
groupMembers = membersRequest.json()
print groupMembers

projectMembers = sorted(projectMembers, key=lambda k: k['access_level'])
groupMembers = sorted(groupMembers, key=lambda k: k['access_level'])

print groupMembers

def master_access(member):
    return member['access_level'] == 40

projectMasters = filter(master_access, projectMembers)
groupMasters = filter(master_access, groupMembers)

assignee = None

if len(projectMasters):
    assignee = projectMasters[0]
elif len(groupMasters):
    assignee = groupMasters[0]

payload = {'source_branch': branch, 'target_branch': target_branch, 'title': merge_title, 'assignee_id': assignee['id']}


print "Create merge request for local branch {0} -> remote branch {1}, assigned to {2}".format(branch,target_branch, assignee['name'])

mr = requests.post("http://{0}/api/v3/projects/{1}/merge_requests".format(host,project_id), data=payload, headers=headers)

print mr.text
```

**Comment by crisp2u** [comment]
@nijel, I created #1302 to add WL_BRANCH env.

**Comment by glensc** [comment]
https://docs.weblate.org/en/latest/vcs.html#pushing-changes-to-github-as-pull-request

re-posting earlier @nijel link to `master` branch as permalink
https://github.com/WeblateOrg/weblate/blob/weblate-2.16/weblate/trans/vcs.py#L756-L830

**Comment by lauripiisang** [comment]
For a very similar set-up compared to the github integration, you could use https://github.com/NARKOZ/gitlab/  for CLI. 
From the docs:
```
 # passing options hash to a command (use YAML)
# see: http://www.rubydoc.info/gems/gitlab/3.4.0/Gitlab/Client/MergeRequests#create_merge_request-instance_method
gitlab create_merge_request 4 "New merge request" "{source_branch: 'new_branch', target_branch: 'master', assignee_id: 42}"
```

**Comment by reshadf** [comment]
Is this ( merge requests for Gitlab ) something that is considered building / adding support for in the near future or is there some work around?

**Comment by nijel** [comment]
It's currently not on the roadmap, but in case somebody contributes the code it will be merged.

**Comment by nijel** [comment]
Implemented by https://github.com/WeblateOrg/weblate/pull/3024, kudos to @maxking
