### ISSUE TITLE
 the previously dismissed error records was cleared

### ISSUE THREAD

**Issue by dxdx123** [WeblateOrg/weblate#12771]
### Describe the problem

After disabling and then re-enabling the glossary checker on Weblate, the previously dismissed error records was cleared?
 Is there any way to recover them?
 
![企业微信截图_17289590486067](https://github.com/user-attachments/assets/9b7115dd-0912-4848-adc1-3f086951e150)

### Describe the solution you would like

sorry , I have no idea

**Comment by nijel** [comment]
If you disable the check, it will get removed from the database including dismissing flag. There is no reason to keep obsolete checks in the database...
