### ISSUE TITLE
Include usernames in translator credits

### ISSUE THREAD

**Issue by dumbmoron** [WeblateOrg/weblate#12800]
### Describe the problem

Currently, the output for translator credits includes the translator's email, name, and change count. 

### Describe the solution you would like

It would be useful for me for automatic translation attribution if the output also included the account username of the translator.

### Describe alternatives you have considered

It would probably be possible to pull out the username through some incantation of API calls, but it's not ideal considering this endpoint already *has* access to this information, and simply omits it.

**Comment by YukeHuang123** [comment]
Hi @nijel  ,Can I take up this issue ?

**Comment by notanshb** [comment]
Hi @nijel would be glad to take this up

**Comment by Humayun-23** [comment]
Hello, I would like to work on this issue.

**Comment by nijel** [comment]
Anybody is welcome to submit a pull request. The credits generating code is here:

https://github.com/WeblateOrg/weblate/blob/c8ecca099f75a110d8b8953356fc1be66c1a315a/weblate/trans/views/reports.py#L52-L92

**Comment by YukeHuang123** [comment]
> account username of the translator.

Hi @nijel,
I’m encountering difficulties with the tests related to author usernames in the `generate_credits` function. The ReportsTest are failing, and I’m unsure why. Specifically, is the `author_username` field being used correctly to retrieve the username?
Here is my implement on this issue:
![image](https://github.com/user-attachments/assets/09fe75b3-9e91-4f5c-8667-7673e8b41f75)

Thank you for your help!

**Comment by harriebird** [comment]
Hi guys, check my PR #12821 for this issue.
