### ISSUE TITLE
Bitbucket PRs missing in the table in the docs

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#12803]
### Describe the issue

Bitbucket PRs are supported in Weblate and should be described and linked in the table at https://docs.weblate.org/en/latest/admin/continuous.html#pushing-changes-from-weblate

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Go to https://docs.weblate.org/en/latest/admin/continuous.html#pushing-changes-from-weblate and miss the description of the configuration of Bitbucket PR

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
@gersona this is documentation missin from https://github.com/WeblateOrg/weblate/pull/12593
