### ISSUE TITLE
Add-on squash commit should work in linked components

### ISSUE THREAD

**Issue by Autherain** [WeblateOrg/weblate#12842]
### Describe the issue

# Issue: Add-on "Squash commits" not working on linked components

## Setup
1. Main component: Created to download Git repository
2. Secondary components: Created through:
   - Classical linking method
   - Component discovery add-on

## Issue Description
The "Squash commits" add-on functions correctly on the main component but fails to work on any linked components, regardless of how they were created (manually linked or discovered).

## Steps to Reproduce
1. Create main component from Git repository
2. Create linked components (either method)
3. Configure "Squash commits" add-on
4. Attempt to commit changes on linked components

## Expected Behavior
Squash commits should work consistently across all components, whether main or linked.

## Actual Behavior
Squash commits only work on the main component.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

## Steps to Reproduce

1. Create main component from Git repository
  - Set repository URL and file mask
  - Enable "Squash commits" add-on

2. Create linked components either:
  - Manually via "Link to existing component" OR
  - Using "Component Discovery" add-on

3. Enable "Squash commits" add-on on linked components

4. Test
  - Make changes in main component -> commits are squashed
  - Make changes in linked components -> commits are NOT squashed

## Environment
- Weblate 5.7.2

### Expected behavior

I expected the add-on to work on linked components

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
I think we fixed this for 5.8, can you upgrade?

**Comment by Autherain** [comment]
Yes i can and Yes it does solve the problem !! Thank you very much  (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧
