### ISSUE TITLE
Can't get machine translation tmserver or Weblate built-in to show anything

### ISSUE THREAD

**Issue by WorldCodeCentral** [WeblateOrg/weblate#1285]
Hi everyone, I'm new to Weblate and can't get tmserver machine translation or the Weblate built-in one to work. See https://docs.weblate.org/en/latest/admin/machine.html#tmserver

BTW I'm also wondering whether there is a public Weblate server where I can try out on of these two machine translation services. So if anyone knows a public server that would be great.

### Steps to reproduce
1. Set up Weblate, enable tmserver and/or Weblate built-in machine translation
2. Add a project and component
3. While translating, press on machine translation tab

### Actual behaviour
Nothig shows up under machine translation tab

### Expected behaviour
Machine translation of string should show up, e.g. for strings that were already translated, shouldn't the present translation show up at least?

### Server configuration
Please paste the output of command `./manage.py list_versions` over here
` Weblate weblate-2.7-97-gf4c443d
* Python 2.7.12
* Django 1.9.8
* six 1.10.0
* python-social-auth 0.2.19
* Translate Toolkit 2.0.0b3
* Whoosh 2.7.4
* defusedxml 0.4.1
* Git 2.7.4
* Pillow (PIL) 1.1.7
* dateutil 2.6.0
* lxml 3.4.4
* django-crispy-forms 1.6.0
* compressor 2.0
* djangorestframework 3.3.2
* pytz 2016.6.1
* pyuca N/A
* Database backends: django.db.backends.sqlite3`

**Comment by nijel** [comment]
Some backends (Weblate built in and few third party ones) are enabled at https://hosted.weblate.org/, the availability always depends on a language.

What problem do you have with tmserver?

**Comment by WorldCodeCentral** [comment]
Hi Nijel, I've looked for a long time on hosted.weblate.org and I've looked again, but I just can't find a language/ project where the "Machine Translation" tab is visible on the translation view. Can you maybe show me one?

My problem with tmserver is that there is never any machine translation in the textfield on the machine translation tab. Neither with Weblate built-in machine translation. How do I know whether there is something wrong with my setup or the machine translation just can't suggest anything, because it hasn't learned enough about the current string? Shouldn't it at least suggest the current translation for already translated strings, since it looks for exact matches? So if I translate Weblate as Weblate (because it's a name), if I go back to that to translate again/ correct it, shouldn't machine translation show me Weblate as a suggestion, because it has learned that?

**Comment by nijel** [comment]
Does the browser do requests for the translations? Each service is requested separately.

Also the built in service might be broken in some cases, see https://github.com/nijel/weblate/issues/1056 and https://github.com/nijel/weblate/issues/800

**Comment by ymmd** [comment]
Hi, I am looking at the issue together with WorldCodeCentral and we tried to track why no search results are being displayed. The browser does 3 requests:
http://localhost:8000/js/mt-services/:
["weblate-similarity", "weblate"]

http://localhost:8000/js/translate/3673/?service=weblate-similarity:
{"lang": "de", "responseDetails": "", "service": "Weblate similarity", "translations": [], "responseStatus": 200, "dir": "ltr"}

http://localhost:8000/js/translate/3673/?service=weblate
{"lang": "de", "responseDetails": "", "service": "Weblate", "translations": [], "responseStatus": 200, "dir": "ltr"}

You can see that each request contains an empty translations array. What can we check in order to see why Whoosh doesn't provide any results? Is there any python file I can include so that we can call Weblate's more_like function with our installation's configuration? We tried to setup the query ourselves, but both being Python noobs we failed :(

**Comment by nijel** [comment]
You can play with it in Django shell:

```
$ ./manage.py shell
Python 2.7.13 (default, Dec 18 2016, 20:19:42) 
[GCC 6.2.1 20161215] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from weblate.trans.search import more_like
>>> from weblate.trans.models import Unit
>>> u = Unit.objects.all()[0]
>>> more_like(u.pk, u.source)
set([])
```

**Comment by michaelarlt** [comment]
is it still open? i saw a hint regarding source language which solved my issue. previously i had source lang to english (United States) in projects. after i changed to en only my issue was gone.

**Comment by WorldCodeCentral** [comment]
Thanks for the reply, I forgot to get back at you. We were able to make it work, my problem was that I didn't have enough strings that were similar enough. I still find it strange though that for an already translated string you don't get your translated string as machine translation output since it should fit 100% (exact match). At least I think this is why it did work later. So, issue can be closed as far as I am concerned. Thanks again.
