### ISSUE TITLE
Support simplification of language code for machine translation services

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1289]
### Steps to reproduce

Aha.  Is the problem with
<URL: https://hosted.weblate.org/translate/debian-handbook/00b_foreword/nb_NO?type=suggestions#machine >
that nb_NO is not supported?

Because
<URL: https://hosted.weblate.org/translate/debian-edu-documentation/audacity/nb/?type=allchecks >
work.

nb_NO should be handled like nb with machine translations, I believe.
Same for nn_NO and nn.  The only reason the debian-handbook project uses
nb_NO is because the build tools they use to build the book did not
understand nb.

### Expected behaviour
The machine translation should work for both nb_NO and nb.

**Comment by petterreinholdtsen** [comment]
This do not seem to work with https://hosted.weblate.org/projects/efn/privacy4kids/nb_NO/ .  Only MyMemory and Weblate similarity show up there.  https://hosted.weblate.org/projects/debian-edu-documentation/audacity/nb/ on the other hand get Microsoft Translator as an extra optoin.

**Comment by nijel** [comment]
Oh, I didn't realize that we additionally have to translate "nb" to "no" for Microsoft Translator and that didn't play well with the simplification code. Fixed now for nb_NO.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
