### ISSUE TITLE
Formatting doesn't work on audit log

### ISSUE THREAD

**Issue by Blueberryy** [WeblateOrg/weblate#12909]
### Describe the problem

So there's a bug which allows you to see ``<Strong> </Strong>`` in audit log.
![image](https://github.com/user-attachments/assets/97163ff2-e64f-4fc8-9561-60998ec3baab)

And will platform names like ``PC``, ``Generic Smartphone`` be translatable?
![image](https://github.com/user-attachments/assets/54583f4e-aae9-4a35-85fa-f41f8befd823)

### Describe the solution you would like

fix and add

**Comment by nijel** [comment]
Where do you see that? What Weblate version do you use?

The user agent info comes from https://github.com/ua-parser/uap-python and there is currently no way to translate these.

**Comment by Blueberryy** [comment]
> Where do you see that? What Weblate version do you use?
On my profile settings of https://hosted.weblate.org
I guess it's latest version because it doesn't say anywhere.

> The user agent info comes from https://github.com/ua-parser/uap-python and there is currently no way to translate these.
Gotcha. Hopefully you will find the way
