### ISSUE TITLE
At login screen it is not possible to use special chars (at least @ sign) in user / password boxes on OSX

### ISSUE THREAD

**Issue by hbto** [WeblateOrg/weblate#1291]
### Steps to reproduce
1. Go to https://demo.weblate.org/accounts/login
2. try to input a username by using email (that leads to write @ sign)
3. try to input a password which have special chars (like @ sign or #) 

### Actual behaviour
Not able to use special chars at user / password boxes in login screen

### Expected behaviour
We should be able to input special chars like @ sign both in user or password boxes.

**Comment by nijel** [comment]
What browser do you use? I have no problems with that...

**Comment by hbto** [comment]
I have tried:
- Chrome 53.0.2785.89 (64-bit)
- Firefox 51.0b5 (64-bit)
- Safari 10.0.1 (12602.2.14.0.7)
- Vivaldi 1.5.658.44 (Stable channel) (64-bit)

All of them on MacOS Sierra.

No tested in any other OS yet.

I will try in a VM on Linux & Windows

Best Regards

**Comment by nijel** [comment]
Hmm strange, I'm not aware of anything which could cause this...

**Comment by hbto** [comment]
I have tested on Linux and It works,

I seems it is a mac related issue.

Regards.

**Comment by nijel** [comment]
That's really strange, can you see it on some other sites as well? The page doesn't really use anything special, just Twitter Bootstrap.

**Comment by nijel** [comment]
Have you figured out something here? I've just tested it using Safari 10 on OSX 10.11 and it works just fine.

**Comment by hbto** [comment]
Hello @nijel 

I have not a clue,

@moylop260 told me he had the same issue on Mac too,

It seems it is a mac-related issue.

I am using macOs 10.12.1 (16B2555)
and the login does not accept @ sign in none of the common browsers.

Thanks for your attention.

**Comment by nijel** [comment]
I don't have real Mac to test, I've tested that on [Sauce Labs](https://saucelabs.com/)...

Is it same on other forms? For example contact form at https://hosted.weblate.org/contact/ ?

It might be caused by [Mousetrap](https://github.com/ccampbell/mousetrap) we use for keyboard shortcuts, but I couldn't find anything related in their issue tracker...

**Comment by hbto** [comment]
@nijel I have tested there at  [Sauce Labs](https://saucelabs.com)...
and my test were unsuccessful.

I am using macOs Sierra 10.12.1 (16B2555)

So There should be a problem,

meantime I will not worry about it,

I will be using Third Party Authentication by Github

So this is a low priority.

There are workarounds like copying & pasting usr / pswd :(

Thanks again.

**Comment by nijel** [comment]
I could really use some help in fixing this, it looks annoying...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
