### ISSUE TITLE
Ampersands are sent to machine translation as html escapes

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#12936]
### Describe the issue

At least DeepL and google translate do not take this well and do not return meaningful suggestions.
I pasted the string as "St&art" and as "St & amp;art" (have to insert spaces here for GitHub) into both web interfaces and the results were nonsense with "St& amp;art".

It also looks like Weblate itself doesn't find the string in its translation memory anymore, even though simlar strings have previously been translated. No suggestions from other projects/components are visible in the attached screenshot. But I'm not 100% sure about this. Since the string is short, the similarity to previous translations may be less than 80%.

This looks like a regression in 5.8.x to me. In 5.7x, ampersands were sent as ampersands and handled well by the translation engines.

Maybe other characters are affected too.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Add a string that contains a keyboard accelerator "&" to the source strings.

### Expected behavior

Send the string as "St&art" to the tanslation engines.

### Screenshots

![grafik](https://github.com/user-attachments/assets/7ac9dba0-757e-4868-bab0-72842a7a2dda)

### How do you run Weblate?

Docker container

### Weblate versions

5.8.2

**Comment by nijel** [comment]
If I read your description correctly, this should be already fixed by 07fe2cdf9853e0706663428f7dc069047cb2b84e.

**Comment by nijel** [comment]
Hmm, actually that commit broke it. https://github.com/WeblateOrg/weblate/pull/12938 should be a real fix (with testcase this time).

**Comment by luebbe** [comment]
> Hmm, actually that commit broke it. #12938 should be a real fix (with testcase this time).

I was about to write the same, since it broke when we upgraded from 5.7.2 to 5.8.2.
Thanks for the fix.

**Comment by nijel** [comment]
The fix was just released: https://github.com/WeblateOrg/weblate/releases/tag/weblate-5.8.3
