### ISSUE TITLE
Custom CSS generation fails

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#12950]
### Describe the issue

```
  File "/home/nijel/weblate/weblate/weblate/trans/context_processors.py", line 179, in weblate_context
    "custom_css_hash": CustomCSSView.get_hash(request),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nijel/weblate/weblate/weblate/configuration/views.py", line 81, in get_hash
    css = cls.get_css(request)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/nijel/weblate/weblate/weblate/configuration/views.py", line 49, in get_css
    "header_color_dark": split_colors(settings.get("header_color"))[1],
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Configure custom colors with Weblate 5.8.2
2. Upgrade to latest git after https://github.com/WeblateOrg/weblate/pull/12794
3. See crash

### Expected behavior

It should work gracefully as it worked before.

### How do you run Weblate?

Git checkout

**Comment by meel-hd** [comment]
@nijel fixes on the way
