### ISSUE TITLE
Contributors to component lists too many users

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#12969]
@nijel It is quite easy to reproduce now.
![image](https://github.com/user-attachments/assets/26fc958a-b0de-4c63-af68-ac2022207539)
![image](https://github.com/user-attachments/assets/5780c4d1-1871-4f88-9a63-730af7a776cd)

_Originally posted by @Geeyun-JY3 in https://github.com/WeblateOrg/weblate/issues/12503#issuecomment-2464802218_

**Comment by nijel** [comment]
The actual component is here: https://hosted.weblate.org/projects/xarchiver/translations/#information

**Comment by Geeyun-JY3** [comment]
BTW, I suggest changing the UI string of the `Quick numbers` panel of the `Info` tab `Contributors` to `Recent contributors`, similar to https://github.com/WeblateOrg/weblate/commit/20a714b81c335305e6c4eb10985718e2b28aadc2.

**Comment by nijel** [comment]
Okay, this is a similar issue as #11808.

* In the user profile we show contributions in the past 90 days.
* In project info, these are for 30 days (and 30 days before).
* In search, this is for 90 days.

This is confusing, as the numbers then don't match.
