### ISSUE TITLE
UI customization not applied to some elements

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#12966]
### Describe the issue

Some elements (at least SVG images in navbar) are wrongly styled after https://github.com/WeblateOrg/weblate/pull/12613

Now:

![obrazek](https://github.com/user-attachments/assets/4a09bd01-cd50-42fd-a1f3-76fbf66d2eff)

Before:

![obrazek](https://github.com/user-attachments/assets/52665ea5-5180-460c-a0e9-66269e183e47)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Have UI customization configured
2. Upgrade

### How do you run Weblate?

Git checkout

**Comment by meel-hd** [comment]
I remember that was intentional. The icons on the right side of the navigation weren't affected by the custom color text settings. Unfortunately that affects the logo too. I'm thinking maybe the logo should always stay in the green brand color. What do you think?

**Comment by nijel** [comment]
It affects navigation icons on the right side as well. Also, the logo is not using brand color, it is using navbar color.
