### ISSUE TITLE
Unable to create account

### ISSUE THREAD

**Issue by BDVGitHub** [WeblateOrg/weblate#12979]
### Describe the issue

I tried to [register](https://weblate.panoramax.xyz/accounts/register/) on Panoramax’s Weblate page but did not receive a confirmation email, even after checking 30 minutes later or in the spam folder.

Then tried to report the problem via [contact page](https://weblate.panoramax.xyz/contact/?t=reg) but get the error “The message could not be sent to the administrator.”

Could someone help me create an account on Panoramax’s Weblate page?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Go to [register](https://weblate.panoramax.xyz/accounts/register/) 
Fill in the fields, wait more than 30 minutes, no conformation mail is received

Fil in [contact page](https://weblate.panoramax.xyz/contact/?t=reg) subject: Registration problems , get the error “The message could not be sent to the administrator.”

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
We don't manage this server and apparently has misconfigured sending e-mails. Please get in touch with server admins.

**Comment by BDVGitHub** [comment]
@nijel how or where can I report this to the server admins?

**Comment by nijel** [comment]
I have no clue, I have no relationship with that server.
