### ISSUE TITLE
Automatic language consistency accross components

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#1298]
### Actual behaviour
We add new language per component.
So project statistics on language translation may be wrong as one language may only be 100% in one component while other may include many components.

### Expected behaviour
We should be able to add new language per project. And have Weblate to help us to handle language consistency across components.

**Comment by nijel** [comment]
The per language stats are counting missing components as not translated, so they give consistent view.

Anyway interface for having same languages in all components is good idea.

**Comment by nijel** [comment]
I think best approach to implement this would be addon, so that's opt in feature.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
