### ISSUE TITLE
Allow more flexibility on the components affected by "Add missing languages" add-on

### ISSUE THREAD

**Issue by keunes** [WeblateOrg/weblate#12987]
### Describe the problem

- Google play only accepts a specific list of languages, many of which with region indications: https://support.google.com/googleplay/android-developer/answer/9844778?visit_id=638668750577796187-2587717613&rd=1#zippy=%2Cview-list-of-available-languages
- Android prefers resources without region indications
- Consequently, we have two different sets of languages we need: one for website & app, one for play store listings (full & short descriptions; screenshots)

Because of the above, we have to manually maintain the languages for all components (website has 4, play store listing 3, and the app itself 1). That's a bit of a pain.

### Describe the solution you would like

Until we moved the play store listing translations from Transifex to Weblate, we had enabled the "Add missing languages" add-on. This would ensure that the languages of the app & website components are in sync. We now cannot use that add-on any-more.

To allow us again to use that add-on, I'm thinking of either of these two solutions:
* allow add-on configuration, to exclude specific components (or component groups)
* allow installing the configuration at component (or component group) level, instead of having to install it project-wide

### Describe alternatives you have considered

An alternative for us would be to keep a single set of languages across the project (including the play store listing components), and do some processing along the way (post Weblate, pre Gradle).
Or a new component-level add-on could be introduced which allows to make a mapping in Weblate, such that language `a` gets saved with language code `b`. But that doesn't sound like a great idea either.

**Comment by nijel** [comment]
If you want some component to use only a subset of languages, [language filter](https://docs.weblate.org/en/latest/admin/projects.html#language-filter) might also be the way to go.

**Comment by keunes** [comment]
Thank you @nijel for the quick reply & the tip. We could apply the language filter on the 3 Google Play text (app description) components to only set the permitted languages. However, that wouldn't prevent those language definitions (e.g. `cs-CZ`) from being used in all our other components, where we want a code without region indication (e.g. `cs`). To address that, we'd need to add the same list (as exclusions) for our five other components. Which is where another solution would come in handy.
But we'll give that a try, thanks for the tip :-)

**Comment by nijel** [comment]
For Weblate cs-cz and cs are the same (unless you manually created it).
