### ISSUE TITLE
Error when Pull git changes - RepositoryException: fatal: There is no merge to abort (MERGE_HEAD missing). (128)

### ISSUE THREAD

**Issue by wellkord** [WeblateOrg/weblate#1299]
Thanks for this great project! I am new to weblate. Have setup a project and 2 components under that project (master and branch). In branch component, when I try to pull changes from remote repository, it always return Internal server error will following log message:

fatal: There is no merge to abort (MERGE_HEAD missing). (128)

Request Method: POST
Request URL: -----
Django Version: 1.10.4
Python Executable: /usr/bin/python
Python Version: 2.7.9
Python Path: ['/usr/local/bin', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
Server time: Sat, 17 Dec 2016 04:00:46 +0000
Installed Applications:
(u'django.contrib.auth',
u'django.contrib.contenttypes',
u'django.contrib.sessions',
u'django.contrib.sites',
u'django.contrib.messages',
u'django.contrib.staticfiles',
u'django.contrib.admin',
u'django.contrib.admindocs',
u'django.contrib.sitemaps',
u'social.apps.django_app.default',
u'crispy_forms',
u'compressor',
u'rest_framework',
u'rest_framework.authtoken',
u'weblate.trans',
u'weblate.lang',
u'weblate.accounts',
u'weblate')
Installed Middleware:
(u'django.contrib.sessions.middleware.SessionMiddleware',
u'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
u'django.middleware.common.CommonMiddleware',
u'django.middleware.locale.LocaleMiddleware',
u'django.middleware.csrf.CsrfViewMiddleware',
u'django.contrib.auth.middleware.AuthenticationMiddleware',
u'django.contrib.messages.middleware.MessageMiddleware',
u'django.middleware.clickjacking.XFrameOptionsMiddleware',
u'social.apps.django_app.middleware.SocialAuthExceptionMiddleware',
u'weblate.accounts.middleware.RequireLoginMiddleware')

Traceback:  

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py" in inner
  39.            response = get_response(request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _legacy_get_response
  249.            response = self._get_response(request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  187.                response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  185.                response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                return view_func(request, *args, **kwargs)

File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py" in inner
  40.            return func(request, *args, **kwargs)

File "/usr/local/lib/python2.7/dist-packages/weblate/trans/views/git.py" in update_subproject
  167.    return perform_update(request, obj)

File "/usr/local/lib/python2.7/dist-packages/weblate/trans/views/git.py" in perform_update
  85.        method=request.GET.get('method', None),

File "/usr/local/lib/python2.7/dist-packages/weblate/trans/views/git.py" in execute_locked
  46.        result = call(*args, **kwargs)

File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/subproject.py" in do_update
  708.            ret = self.update_branch(request, method=method)

File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/subproject.py" in update_branch
  960.                method(abort=True)

File "/usr/local/lib/python2.7/dist-packages/weblate/trans/vcs.py" in merge
  493.            self.execute(['merge', '--abort'])

File "/usr/local/lib/python2.7/dist-packages/weblate/trans/vcs.py" in execute
  200.        self.last_output = self._popen(args, self.path)

File "/usr/local/lib/python2.7/dist-packages/weblate/trans/vcs.py" in _popen
  188.                output.decode('utf-8')

Exception Type: RepositoryException at /update/globonote/1_5-dev/
Exception Value: fatal: There is no merge to abort (MERGE_HEAD missing). (128)

### When run git status, it return the following (omitted huge list of modified files):
```
On branch 1.5-dev
Your branch and 'origin/1.5-dev' have diverged,
and have 9 and 8 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   .gitignore
        .....
        .....
	modified:   web/links.xls

no changes added to commit (use "git add" and/or "git commit -a")
```
----
There are code changes in branch so I need to pull those changes to the branch component. Please help on how to resolve this issue.

### Server configuration
Deploy weblate using docker-compile. Happens on v2.9 and v2.10

Thanks.

**Comment by nijel** [comment]
Hmm, the git status looks like after failed merge, but git complains about missing MERGE_HEAD. Did you do some changes manually to the repository or this happened purely through Weblate?

**Comment by wellkord** [comment]
All happened purely through Weblate. Did not do any manual git action in Weblate's vcs folder.

Not sure if it's related to component's setup.
In master component, I checked "Edit base file", "Locked", "Allow translation propagation", etc. Merge style is Merge.
In branch component, I checked "Edit base file", "Allow translation propagation", etc. Merge style also Merge.

master and branch component both show huge list of modified files when type git status.

In the logs, can also see message failed merge on repo: error: Your local changes to the following files would be overwritten by merge:
... (some java files)

**Comment by nijel** [comment]
These settings really should not matter. Can you check whether it seems like it tried to merge master branch into 1.5-dev?

**Comment by wellkord** [comment]
Does not seem like it's merging master branch. In the logs, the files that are listed with merge issue are the one that have java code changes for 1.5-dev branch.

**Comment by nijel** [comment]
Okay, so it most likely looks like not committed merge, the question is why that did fail.

Not sure how logging is setup on the Docker container, can you get to Weblate logs? The error from merge should be logged there.

**Comment by wellkord** [comment]
Not sure why it has not committed merge. I immediately see huge list of modified files after creating branch component using Weblate 2.9(pip install).

For now, I try to create a new component using Weblate 2.10(pip install), and seems all looks good.
```
On branch 1.5-dev
Your branch is up-to-date with 'origin/1.5-dev'.
nothing to commit, working directory clean
```

Hopefully will not see that error again.

**Comment by nijel** [comment]
If you can not reproduce this with 2.10 then it was most likely some concurrency and locking issue. I've seen similar Git problems with two instances of Weblate doing some changes in the repo at same time. This should be fixed since e466bcb081acb99aa20081fe4791094befe8e4bc.

Anyway if you happen to see this again, it would be great to check what operations were performed at the same time so that we can deeper analyze what went wrong.

**Comment by glamic-ep** [comment]
I'm hitting the same error. I'm on the 2.10 tag of the Git version. The only thing I saw in the logs was:
````
2017-01-04 09:02:44,857 INFO project/compontent: updating repository
2017-01-04 09:02:45,333 INFO project/compontent: update took 0.48 seconds:
````
where project/component is the component I'm trying to add. I have set DEBUG = True and using a file for logging. Should there be more output?

When I set the branch to develop I'm getting `fatal: There is no merge to abort (MERGE_HEAD missing). (128)`. If I leave the branch empty I'm getting `fatal: A branch named 'master' already exists. (128)`.

**Comment by glamic-ep** [comment]
After upgrading to Git 2.11.0 this now works. Do the requirements need updating?

**Comment by nijel** [comment]
I'm not aware anything what would require newer version. Actually the testsuite runs on 1.8.5.6, so pretty close to what you're using...

**Comment by glamic-ep** [comment]
I have not tried other versions, but maybe just this little version step made the difference. :)

**Comment by nijel** [comment]
Looking at the git changelog, the 1.8.5 has fixed some corner case in `git branch --track` which we might be hitting, so it's probably good idea to raise dependency to this version...

**Comment by Jibec** [comment]
hi, can you please update documentation? https://docs.weblate.org/en/latest/admin/install.html#software-requirements

**Comment by nijel** [comment]
Older git versions now works just fine, see https://github.com/WeblateOrg/weblate/issues/1404

**Comment by Jibec** [comment]
Le 18 mars 2017 07:33:16 UTC+01:00, "Michal Čihař" <notifications@github.com> a écrit :
>Older git versions now works just fine, see
>https://github.com/WeblateOrg/weblate/issues/1404

Perfect, I saw this one too and our admin applied the patch yesterday, looks good so far, thank you for your great continous support.
-- 
Jean-Baptiste Holcroft
