### ISSUE TITLE
Weblate adding commits that ad a blank line to the end of .strings files

### ISSUE THREAD

**Issue by RDMurray** [WeblateOrg/weblate#13006]
### Describe the issue

Using hosted Weblate. Weblate has created many commits that only add a blank line to the end of a .strings file. The format is iOS strings (UTF-8).

see https://github.com/soundscape-community/soundscape/pull/124/commits/228b4fbe57d50e7c8b8228a37e648b6abd83b5dc for an example.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Translators make changes to other languages

### Expected behavior

No commits like this.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
https://github.com/translate/translate/pull/5412 should fix this.

**Comment by RDMurray** [comment]
Thanks very much for fixing this so quickly!
