### ISSUE TITLE
Greek Translation.

### ISSUE THREAD

**Issue by VisionR1** [WeblateOrg/weblate#13011]
### Describe the issue

Hi.
I see in my language Greek in the projects, when I go to info and scroll down all it is in Greek, except this: 
Last change made by

A simple Greek translation - Τελευταία αλλαγή από

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Go to info in projects and scroll down in:
Last change made by

### Expected behavior

A simple Greek translation so that everyone who knows Greek can understand.

From English: Last change made by
In Greek: Τελευταία αλλαγή από

### Screenshots

![IMG_20241113_224922](https://github.com/user-attachments/assets/e6d44490-02af-4447-823d-a5f4a89dc0a4)

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
I've made the edit at https://hosted.weblate.org/translate/weblate/application/el/?checksum=d7d83a9d68e6af35, if you have further suggestions you can do that there.

**Comment by yarons** [comment]
Hey @nijel , I don't think this is the problem here, this string is translated to Hebrew and this is what I see in the Fedora Weblate (5.8.2) instance:
![image](https://github.com/user-attachments/assets/003372d7-9d59-4e98-9a02-8ef1bb1e0c5b)
The screen is from: https://translate.fedoraproject.org/projects/setroubleshoot/setroubleshoot/he/#information
The URL of the translated string: https://hosted.weblate.org/translate/weblate/application/he/?checksum=d7d83a9d68e6af35
Unless it was fixed since.

**Comment by VisionR1** [comment]
> Hey @nijel , I don't think this is the problem here, this string is translated to Hebrew and this is what I see in the Fedora Weblate (5.8.2) instance: ![image](https://private-user-images.githubusercontent.com/406826/386102826-003372d7-9d59-4e98-9a02-8ef1bb1e0c5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzkzNDAsIm5iZiI6MTczMTU3OTA0MCwicGF0aCI6Ii80MDY4MjYvMzg2MTAyODI2LTAwMzM3MmQ3LTlkNTktNGU5OC05YTAyLThlZjFiYjFlMGM1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxMDEwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDI4MjA0ZmVlMzMwNGE0ZDY0MmE2NjI4NDY0Y2NjYjk0NjdmZmFjZWFlODgwMTE4Nzk0NjBkMDBkMzc0MWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DpbM8Nhja622Iu0I7LWVGozZSq4a70naz7qS8VtxhGo) The screen is from: https://translate.fedoraproject.org/projects/setroubleshoot/setroubleshoot/he/#information The URL of the translated string: https://hosted.weblate.org/translate/weblate/application/he/?checksum=d7d83a9d68e6af35 Unless it was fixed since.

So, this specific string, is wrong and in other languages.

**Comment by nijel** [comment]
Yes, the string was not translated for the release, the translation will be available in the 5.9 release.
