### ISSUE TITLE
Squash Commits Add-on Stops Working Periodically

### ISSUE THREAD

**Issue by Autherain** [WeblateOrg/weblate#13021]
### Describe the issue

# Squash Commits Add-on Stops Working Periodically

## Issue Description
The "Squash commits" add-on periodically stops functioning across all components, requiring deletion and reinstallation at the project level to restore functionality.

## Steps to Reproduce
1. Enable "Squash commits" add-on at project level
2. Use the add-on normally for some time
3. Eventually, the add-on stops squashing commits
4. Only solution is to delete and reinstall the add-on

## Expected Behavior
The add-on should consistently squash commits without requiring periodic deletion and reinstallation.

## Actual Behavior
- Add-on works initially after installation
- Stops functioning after some time across all components
- Only remedied by deleting and reinstalling at project level
- Issue recurs periodically

## Environment
- Weblate version: 5.8
- Deployment: Docker container

## Verification Steps Completed
- [x] Documentation reviewed and searched
- [x] Similar issues checked in repository

## Additional Context
Current workaround: Delete and reinstall add-on at project level whenever it stops working

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

## Steps to Reproduce
1. Enable "Squash commits" add-on at project level
2. Use the add-on normally for some time
3. Eventually, the add-on stops squashing commits
4. Only solution is to delete and reinstall the add-on

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
This add-on has no state, so reinstalling really doesn't change anything. Maybe the repo could not be squashed for some reason (commit dependencies)? Did you check server logs?

**Comment by Autherain** [comment]
Yes, i did check logs but unfortunately, they were not that helpful. In fact, they were just displaying that the add-on was doing his job as expected( but after deleting it). 

I don't see any problem with the repo inside logs and by thinking about it. 

Really sorry because those are not helpful infos :(

**Comment by nijel** [comment]
I mean server logs, the add-on logs indeed lack any detail right now, this needs to be implemented.
