### ISSUE TITLE
Сan't delete the component

### ISSUE THREAD

**Issue by AlexSquire** [WeblateOrg/weblate#13046]
### Describe the issue

I can't remove the language component

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Open reposit
2. Open mange -> Organize or remove -> Removal conformation ``
3. Press Btn` I understand the consequences, delete this translation`

### Expected behavior

The component should be removed, even after some time. It is not removed even after 24 hours

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Check server logs, most likely the background tasks are not processed.
