### ISSUE TITLE
About username.

### ISSUE THREAD

**Issue by VisionR1** [WeblateOrg/weblate#13049]
### Describe the issue

Hi, I have do some translation in Greek, in GitHub say weblate and Vision committed, but my username does not go to my GitHub profile.

So, my weblate username, must have the same username as GitHub to lead to my profile?
My GitHub username is VisionR1 and my weblate is Vision.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Username

### Expected behavior

To go to my GitHub profile 

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
GitHub matches this by email, so your commiter email configured in Weblate needs to be among emails you have at GitHub.

**Comment by VisionR1** [comment]
> GitHub matches this by email, so your commiter email configured in Weblate needs to be among emails you have at GitHub.

Thanks for info.
Now if I did it right, I have the same email (private) as GitHub in Weblate for the commit.

**Comment by VisionR1** [comment]
Yeah, my issue, had fixed.
All good. 👍
