### ISSUE TITLE
Unable to connect to bitbucket

### ISSUE THREAD

**Issue by christophemassin** [WeblateOrg/weblate#1304]
Hello, 

I m trying to connect to set up a new weblate system, but i can't manage to have it working. My translations doesn't want to be imported. 

I ve set up a key in my bitbucket account and i have added the public in : http://localhost/admin/ssh/ 

i try to connect to one of my private test repo : https://bitbucket.org/Christophe_Massin/newbepark-test . 

When i put in the information as the hosts and the port as 22, then i got an error. 

The page : http://localhost/admin/report/ is a blank page. 

If i just put the bitbucket.org host, it's working but nothing is imported.

Can i get some help please ? 

Thanks a lot !

**Comment by nijel** [comment]
Any error in the syslog or webserver logs?

**Comment by nijel** [comment]
PS: In order to make these URLs work with Git, the both username and password has to be url encoded, for example:
```
 https://user%40example.com:%24password%23@bitbucket.org/...
``
