### ISSUE TITLE
Confirmation Skip action, if a translation was written

### ISSUE THREAD

**Issue by gcb** [WeblateOrg/weblate#13050]
### Describe the problem

User can press Skip instead of save, after writing a long translation. (Also, the dark theme shows a bright green for all buttons *but* sava&continue, which shows dimmer!)

### Describe the solution you would like

Besides fixing button colors (maybe a red/orange for skip), showing a confirmation if user really wants to skip when there's text inputed in the translation field.

### Describe alternatives you have considered

none.

### Screenshots

![image](https://github.com/user-attachments/assets/651147ee-9b3a-43e6-a876-adf64b72761b)
(I click skip 1 out of 10 times. Guaranteed)

### Additional context

I'm a very casual user of weblate.

**Comment by nijel** [comment]
The button colors seem really wrong in the dark theme. @meel-hd can you please:

* [ ] Invert the button colors in the dark theme? Presently, they match light one, but it should be the inverse to highlight the most desired action.
* [ ] Add warning if user presses the “Skip” button after doing some edits?
