### ISSUE TITLE
source string change not highlighted

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1305]
### Steps to reproduce
1. Create a bilingual project with po files.
2. Translate some strings via weblated.
3. Outside of Weblate, alter msgid of a translated string in a po file.
4. Github notifies Weblate by hook, the updated po file is pulled into Weblate.

### Actual behaviour
Changed string is added to "strings needed action", but the change is not highlighted in green and red.

### Expected behaviour
The change should be be highlighted like on screenshot.
<img width="256" alt="screen shot 2016-12-26 at 12 50 01 am" src="https://cloud.githubusercontent.com/assets/1279852/21472292/0c8edc16-cb05-11e6-80a2-99c81b899d4a.png">

### Server configuration
```
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_LOADERS.
 * Weblate weblate-2.9
 * Python 2.7.5
 * Django 1.10.3
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 2.0.0b6
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 1.8.3.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.6.4
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.3
 * pytz 2016.7
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.0
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
For po files you need to invoke msgmerge on them with --previous option (so that the previous string is there).

**Comment by burner1024** [comment]
Sorry, I didn't realise that. Thank you for the answer.
