### ISSUE TITLE
No PR (Translations update from Hosted Weblate) ?

### ISSUE THREAD

**Issue by VisionR1** [WeblateOrg/weblate#13067]
### Describe the issue

I have translate the APatch app before 1 week but I don't see a PR from weblate like the other 
Translations update from Hosted Weblate

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Go to APatch PR.

### Expected behavior

Weblate send a PR with the new translation.

### How do you run Weblate?

weblate.org service

**Comment by marat2509** [comment]
Doesn't apply to this repository. I have no idea where you got the idea that the Hosted Weblate administration decides when to issue Pull Requests for our repository.

**Comment by VisionR1** [comment]
> Doesn't apply to this repository. I have no idea where you got the idea that the Hosted Weblate administration decides when to issue Pull Requests for our repository.

Sorry my mistake. 🙏
