### ISSUE TITLE
Non-breakable space messes up editor formatting

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#13073]
### Describe the issue

When there is a non-breakable space at the end of line in the editor, it is treated as non-breakable in the editor, but not in the highlighting overlay bringing them out of sync.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

I've observed this at https://hosted.weblate.org/translate/weblate/legal/cs/?checksum=c4b4e70d78c401df at certain window width.

### Screenshots

Text editor:

![obrazek](https://github.com/user-attachments/assets/a58ae51e-3ca4-4231-a07c-77712688598b)

When selecting text, it is offset (and differently wrapped text is visible):

![obrazek](https://github.com/user-attachments/assets/ac6aac5d-e7c5-4372-b6a9-c5eb6621c9d3)

### How do you run Weblate?

weblate.org service

**Comment by meel-hd** [comment]
I'm on it.
