### ISSUE TITLE
Tools menu not accessible 

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#13101]
### Describe the issue

Since #12982 the Tools menu while editing is not visible, it is caused by this:

https://github.com/WeblateOrg/weblate/blob/c252a77186abf967c3bf213ed2a682c2a01d5545/weblate/static/styles/main.css#L2262

What was the reason to add this style?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to some string with Tools menu (such as Glossary entry, for example https://hosted.weblate.org/translate/weblate/glossary/cs/?checksum=128393ad2ba520a0&sort_by=source).
2. Click on Tools menu

### Expected behavior

The menu should appear

### How do you run Weblate?

Git checkout

**Comment by meel-hd** [comment]
> What was the reason to add this style?

To hide elements inside the panel with smaller border-raduis from showing outside from the corners.

**Comment by nijel** [comment]
But it hides way more than that. Let's remove it for now because it hides parts of the UI and if you encounter some issues, those should be addressed specifically.

**Comment by nijel** [comment]
As this is already deployed on production, let's just remove the overflow now. If you see a better fix, it can be done later.
