### ISSUE TITLE
Glossary zip file download generates an empty archive

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#13105]
### Describe the issue

The archive downloaded from language is empty when extracted. It has 22bytes sizes, always. There might be other occurrences of this, but, for example, downloading a component that uses PO seems to work OK.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Navigate to a glossary component that uses TBX as file format.
2. Open a language (I opted for source)
3. Click `Files` menu –> `Customize download`
4. Click the button highlighted in the screenshot
5. Get broken ZIP instead of TBX

### Expected behavior

Get correct TBX.

### Screenshots

![no download](https://github.com/user-attachments/assets/b55e94cc-dfcd-41c9-84c0-6eacc8ea41fc)

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Seems to work for me, for example here: https://hosted.weblate.org/projects/weblate/glossary/cs/#download

**Comment by orangesunny** [comment]
It seems to affect the source language only
https://hosted.weblate.org/projects/weblate/glossary/en/#download
