### ISSUE TITLE
ES6 support

### ISSUE THREAD

**Issue by GuillaumeAmat** [WeblateOrg/weblate#1313]
Hi there,

I'm developing an ES6 application and I'm looking for a translation platform. Weblate seems really cool and feature complete but I can't find some informations:

1. Is ES6 supported? Regarding to the extract phase.
2. Does translators have the choice of the format they want to use to translate?

About the second point, I mean that if I choose to use gettext in my final application, can a translator use another format than gettext to do his translation?

Thank you!

**Comment by nijel** [comment]
Weblate doesn't do text extraction, it does just editing and pushing changes.

There is one main format used in the repository where translations are stored, additionally translators can download XLIFF, Gettext PO or CSV. Adding other formats is quite easy, though this should really cover most widely spread localization formats.

**Comment by GuillaumeAmat** [comment]
> additionally translators can download XLIFF, Gettext PO or CSV.

Can they modify and import them or is it just a downloaded file?

Thank you for your quick response anyway ;)

**Comment by nijel** [comment]
Yes, import works for any of the supported formats (see https://docs.weblate.org/en/latest/formats.html).

**Comment by GuillaumeAmat** [comment]
Great! Thank you very much :)
