### ISSUE TITLE
Component synchronization

### ISSUE THREAD

**Issue by AlexSquire** [WeblateOrg/weblate#13148]
### Describe the issue

Please tell me how to disable translation synchronization between components in one project.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Example:
1) I have component **1**, it has English language, which has the key `test` with the value `Home`,
there is component **2**, it has English language, which has the key `test`, with the value `Movie`
2)I change the translation on the client application **(1)** `Home` -> `Home page`. 
3)In WebLite for component **1**, the value of the key `test` changes to `Home page` and
in component **2** in the key `test`   `Movie changes `to `Home page`

### Expected behavior

Translation in component **2** for the `test` key does not change

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/continuous.html#translation-propagation
