### ISSUE TITLE
Sorting Search Result by Last updated not correct

### ISSUE THREAD

**Issue by lars3141** [WeblateOrg/weblate#13144]
### Describe the issue

When I search for texts and filter by last updated, the resulting list is seemingly randomly sorted. I get results which have been updated fairly recently, but there are always texts mixed into the results, which have only been changed days or weeks ago. In these cases, I cannot see any change in the History of any language of the string which was recently made.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to a fairly large Project including multiple different components in different categories.
2. Search for anything
3. Sort by Last Updated, Descending

### Expected behavior

See the newest change on top and the oldest last.
The Last Updated Field is filled with a new value, but nothing has changed in the file text history.

### Screenshots

<img width="1906" alt="image" src="https://github.com/user-attachments/assets/32c97247-0d04-4b13-8032-831ce06e8bfe">
<img width="1918" alt="image" src="https://github.com/user-attachments/assets/298ef72e-981a-4294-bdb7-e08c51dcd8c8">

### How do you run Weblate?

Docker container

### Weblate versions

5.8.1

**Comment by nijel** [comment]
Some changes are not tracked in history but update string timestamp. For example, adding variants or when metadata change in the backend file (like location).
