### ISSUE TITLE
Deleted Entry in Source File Not Reflecting in Git Repository

### ISSUE THREAD

**Issue by dxdx123** [WeblateOrg/weblate#13181]
### Describe the issue

I noticed that when an entry (id="200002") is deleted in the source file (zh_Hans.xliff) and synchronized on the Weblate platform, the number of entries in both the source and translation files decreases accordingly. However, the **en.xliff** file in the git repository does not reflect this deletion, even though the status appears correct on the Weblate platform. Could you help me understand why the deletion is not being submitted to the git repository?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Could you help me confirm if this is a bug?

### How do you run Weblate?

Docker container

### Weblate versions

5.5.5

**Comment by nijel** [comment]
This is intended, please install the cleanup add-on if you want stale strings to be removed, see https://docs.weblate.org/en/latest/devel/integration.html#updating-target-files
