### ISSUE TITLE
Automatic sync with Github not working

### ISSUE THREAD

**Issue by MartynasObdeleven** [WeblateOrg/weblate#13182]
### Describe the issue

We migrated from Bitbucket to Github, and after setting up weblate to work with github, we noticed that automatic sync is gone. Now we must always go into Repository Maintenance and manually push or pull any changes made either in our project source code, or in weblate.

Our weblate is hosted internally, so we can't use github plugins for easier sync.

Our settings look like following

<img width="2261" alt="Screenshot 2024-12-04 at 08 30 11" src="https://github.com/user-attachments/assets/78d24dcf-255c-4bc4-a23a-15e487e876d3">

What could be wrong?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Add new translation string
2. Go to reppository maintenance
3. See that there is 1 pending change

### Expected behavior

1. Add new translation string
2. Go to repository maintenance
3. See that there are no pending changes, as my added translation is automatically synced with our main code repository

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
You need to tell Weblate to update the repo somehow:

* Use GitHub hooks (probably not feasible in your case), see https://docs.weblate.org/en/latest/admin/continuous.html#automatically-receiving-changes-from-github
* Use API, see https://docs.weblate.org/en/latest/api.html#post--api-projects-(string-project)-repository-
* Configure Weblate to automatically update all repos, see https://docs.weblate.org/en/latest/admin/config.html#auto-update
