### ISSUE TITLE
Where is 'source string location' property from XLIFF format?

### ISSUE THREAD

**Issue by shuhari** [WeblateOrg/weblate#1320]
Our previous git repository use .PO file and we can see 'source string location' in source information section. It is useful for our translators, and seemd to be extracted from comments in .PO file. 

Now we are moving to .XLIFF format and make it work, but the 'source string location' is missing from web interface. I have not idea where should we put the location in XLIFF file. I've tried to put it in xml tag 'trans-unit/note', but seemed not work.

Could you tell me where should I put the property in XLIFF file? Or it comes from other sources? Thx for any advice.

**Comment by nijel** [comment]
It should work according to specs: http://docs.oasis-open.org/xliff/v1.2/xliff-profile-po/xliff-profile-po-1.2-cd02.html#s.detailed_mapping.tu.references

```
<trans-unit id="1">
 <source>hello world</source>
 <context-group name="po-reference-1" purpose="location">
 <context context-type="sourcefile">example.c</context>
 <context context-type="linenumber">34</context>
 </context-group>
 <context-group name="po-reference-2" purpose="location">
 <context context-type="sourcefile">otherfile.c</context>
 <context context-type="linenumber">233</context>
 </context-group>
</trans-unit>
```

If it does not, deeper look into translate-toolkit is needed.

**Comment by shuhari** [comment]
Now I add context-group to our source file, but it does not show.

Sample of our translation word:

<trans-unit id='btn_close' help-id='sw:e60b137a-f9b5-4093-ab2b-c55b7580403a^1c5ea4de-c77e-446a-86d9-3c182b67be98' xml:space="preserve">
    <source>Close</source>
    <target>Close</target>
    <context-group name="xliff-reference" purpose="location">
      <context context-type="sourcefile">ResGClose</context>
      <context context-type="linenumber">按钮, 关闭页面</context>
    </context-group>    
  </trans-unit>

I also tried to replace sourcefile/linenumber with other properties, but none of them seemed work.

BTW: I noticted the specs saying in '5.4. Extracted Comments':

> It is possible to map each extracted comment to a <note> element.

So add the note tag to .XLIFF file should take effect? I'd tried it but also could not get result.

**Comment by nijel** [comment]
It should be `po-reference` not `xliff-reference`.

**Comment by shuhari** [comment]
I'd already tried po-reference, it does not work either.

**Comment by nijel** [comment]
Okay, I've just noticed that we use poxliff only for exporting, but not for reading the files, so this indeed can not work right now.
