### ISSUE TITLE
Invalid e-mail address '<username>@users.noreply.translate.codeberg.org': local-part is not dot-atom, quoted-string, or obs-local-part

### ISSUE THREAD

**Issue by Bubu** [WeblateOrg/weblate#13225]
### Describe the issue

This is a follow-up of https://github.com/WeblateOrg/weblate/issues/1206 where the 
result was:

> Seems like that user has an invalid e-mail address. https://github.com/WeblateOrg/weblate/pull/12073 should avoid such an e-mail from being used by Weblate in the future, but you will have to fix it for this user manually.

I'm finally trying to track down why this is still happening for us/how to fix this.

I worked around the problem by temporarily renaming the user, making weblate commit the changes and naming the user to their original name again. It's unclear to me how to avoid this problem (with this user) in the future, if they keep contributing. It seems that weblate itself is still generating a wrong(?) noreply mail address for this user that it then cannot actually use?

Am I missing something here?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Have a weblate user with name `Vasilis_Kos.` (note the trailing dot). This user is registered via oauth from a codeberg.org user, so changing the weblate username is not really an option).
2. The user has opted into using the weblate generated contributor email, which will be `Vasilis_Kos.@users.noreply.translate.codeberg.org`
3. This user translates a project
4. Try to commit the translation change from weblate managepent interface

### Expected behavior

Changes are committed correctly

### Exception traceback

```pytb
ValueError at /commit/btremote/app-strings/
Invalid e-mail address 'Vasilis_Kos.@users.noreply.translate.codeberg.org': local-part is not dot-atom, quoted-string, or obs-local-part
```
```


### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.8.4
 * Django: 5.1.4
 * siphashc: 2.5
 * translate-toolkit: 3.14.1
 * lxml: 5.3.0
 * pillow: 11.0.0
 * nh3: 0.2.19
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.2
 * django-crispy-forms: 2.3
 * oauthlib: 3.2.2
 * django-compressor: 4.5.1
 * djangorestframework: 3.15.2
 * django-filter: 24.3
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.16.1
 * RapidFuzz: 3.10.1
 * openpyxl: 3.1.5
 * celery: 5.4.0
 * django-celery-beat: 2.7.0
 * kombu: 5.4.2
 * translation-finder: 2.19
 * weblate-language-data: 2024.14
 * html2text: 2024.2.26
 * pycairo: 1.27.0
 * PyGObject: 3.50.0
 * diff-match-patch: 20241021
 * requests: 2.32.3
 * django-redis: 5.4.0
 * hiredis: 3.0.0
 * sentry-sdk: 2.19.2
 * Cython: 3.0.11
 * mistletoe: 1.4.0
 * GitPython: 3.1.43
 * borgbackup: 1.4.0
 * pyparsing: 3.2.0
 * ahocorasick_rs: 0.22.1
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.4.0
 * cyrtranslit: 1.1.1
 * drf-spectacular: 0.27.2
 * Python: 3.12.8
 * Git: 2.39.5
 * psycopg: 3.2.3
 * psycopg-binary: 3.2.3
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.7.1
 * boto3: 1.35.76
 * aeidon: 1.15
 * iniparse: 0.5
 * mysqlclient: 2.2.6
 * google-cloud-translate: 3.18.0
 * openai: 1.57.0
 * Mercurial: 6.9
 * git-svn: 2.39.5
 * git-review: 2.4.0
 * PostgreSQL server: 16.6
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.codeberg.org
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 6.1.0-27-amd64 (x86_64)


### Weblate deploy checks

_No response_

### Additional context

_No response_

**Comment by nijel** [comment]
Thanks for analyzing this! https://github.com/WeblateOrg/weblate/pull/13227 should address this issue.
