### ISSUE TITLE
Global Search accross all components

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#1323]
Hi,

Component structures are not always easy to understand for translators and sometime strings are not "logically" stored in these components ;-(.

Is there a way to search a string globally to change its translation? Or even a workaround like downloading locally all strings of a project for a specified language then search in file or whatever.

Regards,

**Comment by nijel** [comment]
There is already sitewide search: https://hosted.weblate.org/#search

**Comment by nijel** [comment]
Project wide search is now there as of b75e2052d49fcde36373bcb05ab87fc664539110.

**Comment by ldmpub** [comment]
Hi Michal,

Perfect! Already used and I can already say: "I no longer can do without it" ;-).

Many thanks for your reactivity and this GREAT piece of software.
