### ISSUE TITLE
About "Unchanged translation" warning

### ISSUE THREAD

**Issue by sevdimali** [WeblateOrg/weblate#1324]
Hello,
Some words are same in source and destination language.
For example "developer"  it is same on Azerbijani and English.

https://hosted.weblate.org/translate/phpmyadmin/4-6/az/?checksum=672caf27f5363dc833bda5099775e891

I recommend if the source words are one word (for example: "developer") we have to allow it to translate without unchanging.
Thanks

**Comment by nijel** [comment]
I don't think that skipping anything what is one word from translation is good approach. So far we maintain list of words which are expected not to be translated.
