### ISSUE TITLE
Can't unmark strings as read-only when using the "Fill read-only strings with source" addon

### ISSUE THREAD

**Issue by RappyTV** [WeblateOrg/weblate#13248]
### Describe the issue

The issue that I'm experiencing is that I am unable to unmark source strings as read-only when using the "Fill read-only strings with source" addon. Even if the source string shows that it's not a read-only string, when trying to translate them it shows that they're read-only. I am using the nested json file format and the issue only started ocurring after installing the mentioned addon.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Mark a string as read-only
2. Install the "Fill read-only strings with source" addon
3. Unmark the string as read-only

It should now show that the source string is not read-only but the strings in the corresponding languages are.

Steps to fix:
1. Delete the mentioned addon
2. Mark the string as read-only again
3. Unmark the string as read-only

### Expected behavior

I need the strings in the languages to not be read-only so me any my translators can edit them.

### Screenshots

This is how the source string looks:
<img width="1043" alt="Screenshot 2024-12-11 at 03 58 04" src="https://github.com/user-attachments/assets/c65ae24e-17f9-4a56-9dc7-f0293a4ae1bc">
And this is the view of the german translation for example:
<img width="1040" alt="Screenshot 2024-12-11 at 03 59 17" src="https://github.com/user-attachments/assets/8d82dd6c-c243-4342-8aee-97a20963f706">

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.8.4
 * Django: 5.1.4
 * siphashc: 2.5
 * translate-toolkit: 3.14.1
 * lxml: 5.3.0
 * pillow: 11.0.0
 * nh3: 0.2.19
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.2
 * django-crispy-forms: 2.3
 * oauthlib: 3.2.2
 * django-compressor: 4.5.1
 * djangorestframework: 3.15.2
 * django-filter: 24.3
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.16.1
 * RapidFuzz: 3.10.1
 * openpyxl: 3.1.5
 * celery: 5.4.0
 * django-celery-beat: 2.7.0
 * kombu: 5.4.2
 * translation-finder: 2.19
 * weblate-language-data: 2024.14
 * html2text: 2024.2.26
 * pycairo: 1.27.0
 * PyGObject: 3.50.0
 * diff-match-patch: 20241021
 * requests: 2.32.3
 * django-redis: 5.4.0
 * hiredis: 3.0.0
 * sentry-sdk: 2.19.0
 * Cython: 3.0.11
 * mistletoe: 1.4.0
 * GitPython: 3.1.43
 * borgbackup: 1.4.0
 * pyparsing: 3.2.0
 * ahocorasick_rs: 0.22.1
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.4.0
 * cyrtranslit: 1.1.1
 * drf-spectacular: 0.27.2
 * Python: 3.12.7
 * Git: 2.39.5
 * psycopg: 3.2.3
 * psycopg-binary: 3.2.3
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.7.1
 * boto3: 1.35.76
 * aeidon: 1.15
 * iniparse: 0.5
 * mysqlclient: 2.2.6
 * google-cloud-translate: 3.18.0
 * openai: 1.56.2
 * Mercurial: 6.9
 * git-svn: 2.39.5
 * git-review: 2.4.0
 * PostgreSQL server: 17.2
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.rappytv.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.4.0-182-generic (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.8.4/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.8.4/admin/backup.html

System check identified 5 issues (12 silenced).
```

**Comment by nijel** [comment]
Thanks for your report, https://github.com/WeblateOrg/weblate/pull/13274 should fix it.

To fix existing strings, either wait for a translation file update when Weblate will parse the files again, or commit current changes and do rescan (both can be done in repository management).
