### ISSUE TITLE
Reusing a file between components

### ISSUE THREAD

**Issue by dxdx123** [WeblateOrg/weblate#13259]
### Describe the issue

There are two components. 
Component 1: game_text_cn, source language: Chinese, translating Chinese to English. 
Component 2: game_text_en, source language: English (en.xliff from Component 1), translating English to other languages.
The source code repository of Component 2 uses the shared repository weblate://dev/game_text_cn.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Reproduction Steps: 
Suppose there are 10 source texts in Component 1. When adding and saving a new translation entry (translated to English) in Component 1, Component 2 continues to show only 10 source texts. This issue persists unless the repository is reset in the management interface.

### Expected behavior

![image](https://github.com/user-attachments/assets/6408d903-1aae-416d-af16-7f2d2882aac9)

### How do you run Weblate?

Docker container

### Weblate versions

weblate 5.5.5 in docker

**Comment by nijel** [comment]
Likely a bug because using the same file in multiple components was not really expected.

You might want to use intermediate language instead and have only one component, see https://docs.weblate.org/en/latest/workflows.html#quality-gateway-for-the-source-strings.

**Comment by dxdx123** [comment]
If I use an intermediate language, do I still need to create two components?

**Comment by nijel** [comment]
No

**Comment by dxdx123** [comment]
May I ask, if it is one component, is it recommended to set the intermediate language file to the corresponding en.xliff for masking, or should a separate intermediate language file be specified?

**Comment by nijel** [comment]
It really depends on you whether you want to use English as an intermediate language directly.

https://github.com/WeblateOrg/weblate/pull/13302 will make Weblate alert on such setup so that it will be clear that something is configured wrongly.
