### ISSUE TITLE
Strings are marked for review but in fact they are not

### ISSUE THREAD

**Issue by daniele-athome** [WeblateOrg/weblate#1326]
> Initially reported at #1314

I got a weird behaviour with version 2.10 today:

* a user modified a source string
* all other languages got marked as review (and that's ok)
* I reverted the source string modification because it was a mistake
* the other languages were not marked as review anymore if I open the single string, however language overview still had "Strings needing review" with "1". If I clicked it, it said no strings needed review (WTH?!?)

Looks like a bug to me (nothing really serious, if I manually mark the string as "need review" and back again, the problem goes away, still I have I to do that manually for 14 languages :-), but I don't know if it's worth opening a new issue.

**Comment by nijel** [comment]
As mentioned in #1314, I think this is caching issue as the number of flagged strings is cached.

**Comment by daniele-athome** [comment]
As a workaround, is there a way to clear those caches?

**Comment by nijel** [comment]
AFAIK `./manage.py loadpo --all` should do that, but I'm not 100% sure (it will definitely do it with `--force`, but that reads all files from the disk as well, so it will take quite long).

**Comment by nijel** [comment]
In my testing it behaves slightly differently than you describe:

- once I change the source string, the translations are marked for review with previous translation set to old string
- once I revert the change, the translations are kept set to review (only not highlighting source change as there is now none)

**Comment by daniele-athome** [comment]
> once I revert the change, the translations are kept set to review (only not highlighting source change as there is now none)

That's it, however I get a report of strings to review from the language overview screen, but when I open the strings in detail the checkbox is not checked.

Oh and did I mention that the source string must be edited from Weblate itself to reproduce the issue? I mean not via a source code commit. Tolding you just to be sure we're on the same page.

**Comment by nijel** [comment]
Well the logic is there two times as it is heavily optimized when doing change in Weblate (we do not have to look at source files in this case). Anyway it should now behave according to your expectations in both cases.

**Comment by daniele-athome** [comment]
Thanks! Looking forward to the next release to try it.
