### ISSUE TITLE
port is already allocated

### ISSUE THREAD

**Issue by linliyuan** [WeblateOrg/weblate#13267]
### Describe the issue

I just want to deploy and use it, but the Docker image keeps getting stuck at "port is already allocated". Is there a quick way to adjust it to use another port? The error occurs directly, which is quite a high barrier for new users.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

https://docs.weblate.org/en/latest/admin/install/docker.html

### Screenshots

![image](https://github.com/user-attachments/assets/1478d474-7f7e-487f-99f1-9aa728568aa2)

### How do you run Weblate?

Docker container

**Comment by linliyuan** [comment]
Is it sufficient to change? But the program defaults to listening on port 80, right? How can I change the web service to listen on a different port?
ports:

80:8080
to
ports:
8080:8080

**Comment by nijel** [comment]
You will need to include the port in https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_SITE_DOMAIN if using a non-standard one.
