### ISSUE TITLE
Rest API PO file download as format zip for PO components different from format zip:po

### ISSUE THREAD

**Issue by philipp-kern** [WeblateOrg/weblate#13273]
### Describe the issue

When using the REST API endpoint [GET /api/components/(string: project)/(string: component)/file/](https://docs.weblate.org/en/latest/api.html#get--api-components-(string-project)-(string-component)-file-) we have encountered the following issue.

We have a component that is configured with "file_format": "po-mono" (gettext PO file (monolingual)).

When using `GET /api/components/<project>/<component>/file/?format=zip`

```
msgid "app.storescreen.barcode.hint.1"
msgstr "Für Informationen zum Produkt Barcode scannen"
```

When using `GET /api/components/<project>/<component>/file/?format=zip:po`

```
msgctxt "app.storescreen.barcode.hint.1"
msgid "Für Informationen zum Produkt Barcode scannen"
msgstr ""
```

Apparently if using the explicit PO conversion, the msgstr is used as msgid and the msgid as msgctxt, leaving msgstr empty.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Create a component with file type gettext PO file (monolingual) from scratch.
2. Add new source strings.
3. Use the mentioned API endpoints above and see the difference.

### Expected behavior

The output is the same, because both are in PO format and an empty msgstr is definitely not what is represented in Weblate.

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 5.8.4
(We use a dedicated cloud instance hosted by weblate.org)

### Additional context

We are reporting this because we are currently using the zip:mo (so not PO) conversion, but fear that this might get broken in an update as well.

**Comment by nijel** [comment]
I've just tried it, and it generates a correct entry for me when the string is translated:

```po
msgctxt "hello"
msgid "Hello, world!\n"
msgstr "Nazdar, světe !\n"
```

For untranslated strings it also looks as I would expect:

```po
msgctxt "thanks"
msgid "Thank you for using Weblate."
msgstr ""
```

**Comment by philipp-kern** [comment]
Thanks for the response.
Ok I see that the non-source language files in the zip:po have the msgstr filled out, with msgid being the source language text. So I am guessing that format=zip:po returns the bilingual format, but format=zip the monolingual format.
Am I understanding that correctly?

**Comment by nijel** [comment]
Yes.
