### ISSUE TITLE
How it's better to update translations with the continuous translation process?

### ISSUE THREAD

**Issue by AlexMost** [WeblateOrg/weblate#1328]
We have just made a local setup of weblate, seems like everything works well. Thank you guys you have made really great project. Saves a ton of time for us. 

The question is how it's better to implement automatic update for translations? We are using gettext .po files and gitlab. So for now I'm not sure where I need to execute gettext extract. There are 3 options:

1. Execute it manually by developers. This is an easiest solution but seems like I can automate this step.
2. Execute extract somewhere on a gitlab ci steps and to make an extra commit with updated translations somewhere on a merge request. Need to investigate more on how I can implement this with gitlab ci, and not sure that it is possible.
3. Make this on POST UPDATE script on a weblate server. With this option I need to install all dependencies that I need for extracting translations.

Maybe someone has already configured this behavior and can point me in a right direction?

**Comment by nijel** [comment]
I personally prefer manual approach as it avoids generating too many commits - developers usually have an idea when something important has changed in the translations.

Any automated approach would IMHO either lead to too many commits or would need some heuristics to decide whether the resulting change is worth committing (note that Gettext PO files include links to source file, which can change quite frequently and few lines change is usually not critical here).

Anyway it's matter of personal preference - if you don't mind additional computational power and commits, doing this in CI is probably good approach. Please note that you will probably need to deal with conflicts at some point as well as the automated commits from CI might conflict with changes done by Weblate or developers.

**Comment by nijel** [comment]
See also [Avoiding merge conflicts](https://docs.weblate.org/en/latest/admin/continuous.html#avoid-merge-conflicts) in our docs.

**Comment by AlexMost** [comment]
@nijel thanks for the quick reply! I have already seen "Avoiding merge conflicts" and thought that actually those locks will help to avoid those conflicts. We have quite a big amount of code base, and manual approach can lead to outdated translations (someone must always remember to execute extract command).
