### ISSUE TITLE
`zh-cn` and `zh-tw` translations of documentation are missing from docs.weblate.org

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#13288]
### Describe the issue

`zh-cn` and `zh-tw` translations of documentation are missing from docs.weblate.org

I am not sure if there are any other translations of documentation that are missing.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to https://docs.weblate.org/zh-cn/latest/ and https://docs.weblate.org/zh-tw/latest/

### Expected behavior

See the `zh-cn` and `zh-tw` translations of the documentation on docs.weblate.org

### Screenshots

- https://docs.weblate.org/zh-cn/latest/
  ![image](https://github.com/user-attachments/assets/d73195e8-d49c-4c10-99d7-3a803034d55a)
- https://docs.weblate.org/zh-tw/latest/
  ![image](https://github.com/user-attachments/assets/20c51a21-d392-4d53-87bd-0ed0e62d25b7)

### How do you run Weblate?

weblate.org service

### Weblate versions

Not related

**Comment by nijel** [comment]
The same applies to https://docs.weblate.org/pt-br/latest/, seems like the language codes with dash have this issue.

**Comment by nijel** [comment]
Now it looks correct: https://docs.weblate.org/zh-cn/latest/ (you might need to reload the page to see the new version).
