### ISSUE TITLE
Can't delete huge component (more that 120 000 lines in .po file)

### ISSUE THREAD

**Issue by AlexMost** [WeblateOrg/weblate#1329]
### Steps to reproduce
1. Add project and component with 120 000 lines in .po file.
2. Try to delete this component.

### Actual behaviour
weblate hangs for a couple of minutes. And component is still in the list.

### Expected behaviour
Component should be deleted.

### Server configuration
```
 * Weblate 2.10
 * Python 3.5.2
 * Django 1.10.5
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 2.0.0rc1
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.2
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.3
 * pytz 2016.10
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.0.1
 * Database backends: django.db.backends.postgresql_psycopg2
```

**Comment by AlexMost** [comment]
is there any ability just to hide component?

**Comment by nijel** [comment]
This should be fixed since 08a32b80d9119cf7433bae0aec6804ddcf6fa829.

As workaround, you can remove the post_delete signal handler as done in the patch.

**Comment by AlexMost** [comment]
awesome!

**Comment by AlexMost** [comment]
so upgrading to 2.10.1 will fix the problem?

**Comment by nijel** [comment]
No, 2.10.1 includes just fix for https://github.com/WeblateOrg/weblate/issues/1317
