### ISSUE TITLE
Unreadable math test on account creation with Firefox

### ISSUE THREAD

**Issue by Insoleet** [WeblateOrg/weblate#1331]
### Steps to reproduce
1. Create an account
![image](https://cloud.githubusercontent.com/assets/1170293/22177599/52d16a00-e021-11e6-9d02-4c57a9eb3612.png)

### Actual behaviour
The maths are unreadable.

### Expected behaviour
The maths should be readable. It works on chromium.

**Comment by nijel** [comment]
Hmm, seems like missing unicode fonts, I thought this is now available pretty much everywhere. What OS is that?

**Comment by Insoleet** [comment]
I use archlinux. Notice that it works with chromium on the same OS.

**Comment by nijel** [comment]
I've changed symbols used there, can you please check if that renders fine for you? The new symbols are from Unicode 6.0 though, so I'm a bit worried about their availability as well. Maybe it will be better to render these as SVG instead...

See https://github.com/WeblateOrg/weblate/commit/be657f41f503c44501ee7641bd864d29dcde3325

**Comment by nijel** [comment]
The change is now live on Hosted Weblate as well, so it would be great if you could provide feedback.

Registration form is here: https://hosted.weblate.org/accounts/register/

**Comment by Insoleet** [comment]
It's all good 👍
