### ISSUE TITLE
Rate Limit Applies Globally to All Users, Including Superusers

### ISSUE THREAD

**Issue by kt315ua** [WeblateOrg/weblate#13325]
### Describe the issue

**Description**:
We have installed Weblate 5.9.1 using Docker containers. Everything works well except for account lockouts due to rate-limiting behavior.

Our setup includes 5 regular user accounts and 2 superuser accounts.

**Steps to Reproduce**:
- Attempt 5-6 logins with an incorrect password using the "admin" superuser account.
- Observe the following error: `Too many authentication attempts from this location. Please try again in 10 minutes.`
- Try to log in using another superuser account with the correct credentials.

**Actual Result**:
The second superuser cannot log in, and the same error is displayed:

- Web error: `Too many authentication attempts from this location. Please try again in 10 minutes.`
- Log string: `translations-weblate     | gunicorn stderr | [2024-12-17 15:48:22,248: INFO/471] rate-limit lockout for ratelimit-ip-login-9db7874c312c839c in login scope from`
- This issue affects both superusers and regular users.
- This behavior does not align with the documentation: [Rate limiting in Weblate documentation](https://docs.weblate.org/en/latest/admin/optionals.html#rate-limit)

**Expected Result**:
The rate limit should only apply to the account that exceeded the login attempts, not all accounts from the same location.

**Feature Proposal**:
Allow authenticated admins to reset lockouts for individual accounts via the Webadmin interface.

**Workaround**:
Currently, we use the following workaround:

- Stop the Weblate service.
- Remove the Redis dump.rdb file.
- Start the Weblate service.

**Additional Notes**:
It appears that the 10-minute lockout timer does not reset when the Weblate service restarts unless the Redis database is cleared.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

- Attempt 5-6 logins with an incorrect password using the "admin" superuser account.
- Observe the following error: `Too many authentication attempts from this location. Please try again in 10 minutes.`
- Try to log in using another superuser account with the correct credentials.

### Expected behavior

The rate limit should only apply to the account that exceeded the login attempts, not all accounts from the same location.

### Screenshots

![Знімок_20241217_152624](https://github.com/user-attachments/assets/349b2667-5681-4bc1-b968-696e54133efa)
![Знімок_20241217_154554](https://github.com/user-attachments/assets/83d76056-4ce3-489e-a47f-926bb9ab1672)
![Знімок_20241217_154618](https://github.com/user-attachments/assets/ab62a40f-8aca-4545-b210-72c7557b3956)
![Знімок_20241217_154734](https://github.com/user-attachments/assets/73ed32a4-06dc-439b-a6c6-d5e2101b2c03)
![Знімок_20241217_154802](https://github.com/user-attachments/assets/1aa32379-aa16-4e36-b1a9-83850ef4d866)
![Знімок_20241217_152339](https://github.com/user-attachments/assets/3d52e577-6e5f-4056-8ccc-b69a96583f81)
![Знімок_20241217_160929](https://github.com/user-attachments/assets/1016efde-b7a8-462d-9a12-431f030d4d7f)
![Знімок_20241217_161222](https://github.com/user-attachments/assets/f4184e14-d651-47ab-9ac7-84b2b7715fae)

### How do you run Weblate?

Docker container

### Weblate versions

5.9.1
5.7.2.2

**Comment by nijel** [comment]
The login rate limiting is based on IP address, so this behavior is expected if all the attempts are from a single address.

The rate-limiting is not applied to signed in superusers, it makes no sense to exclude them from rate-limiting which is targeted at limiting password probing.

I've clarified the documentation in e16934338a.

**Comment by kt315ua** [comment]
@nijel 
Thanks, a lot!

It seems I’ve identified the core of our problem. While investigating and trying to fix my colleague’s account in a second browser (to use a separate, clean session environment), I was also blocked by the rate limit.

After you clarified that the rate limit "no longer applies to signed-in users", things made more sense. Once I signed out, I encountered the lock myself, which confirms that statement.

**Comment by nijel** [comment]
Maybe you are not passing correctly proxy headers to the container, and it sees all requests coming from a single IP address?

**Comment by kt315ua** [comment]
@nijel 
I'm reproduce the problem from different networks and we don't use proxy.
I create `rate-limit lockout` from my side ip 95.x.x.x. But my colleague can't Sign in to his own account from ip 3.x.x.x.
Nginx see that we try to connect from different IP's.
![Знімок_20241218_100524](https://github.com/user-attachments/assets/d5ef4ebb-99ba-46d4-bec1-b1c5efeddbc7)
In redis i don't see IP
![Знімок_20241218_100738](https://github.com/user-attachments/assets/3be0b029-7041-4370-9407-4416d8f84270)

**Comment by kt315ua** [comment]
![Знімок_20241218_170024](https://github.com/user-attachments/assets/02df3105-9241-48a2-b49d-109831336e60)
[test_server.txt (python code for tests)](https://github.com/user-attachments/files/18185738/test_server.txt)
I've check headers by py-script (test_server.txt) that was launched before sending sign in request (weblate was stopped for that moment)
Maybe it will helpful.

Weblate service running on AWS EC2 where public IP are mapped to private IP.
Private IP is assigned to weblate, and as we can see, i can get correct client IP address.

**Comment by nijel** [comment]
How do you terminate HTTPS? Do you have a reverse proxy in front of Weblate? It might need to pass additional headers, see https://docs.weblate.org/en/latest/admin/install/docker.html#docker-container-with-https-support.

**Comment by nijel** [comment]
Adding this to the environment might help:

```
WEBLATE_IP_PROXY_HEADER=HTTP_X_FORWARDED_FOR
```

**Comment by nijel** [comment]
Revising all this, I've made some changes:

* https://github.com/WeblateOrg/docker/pull/2897 will turn this on when using built-in https termination as we have control on the headers here
* https://github.com/WeblateOrg/weblate/pull/13343 improves the documentation and adds an error to the log when the IP address cannot be obtained

**Comment by kt315ua** [comment]
@nijel  thanks for helping me.
I don't use any proxy in front of weblate service.
There was taken that template https://github.com/WeblateOrg/docker-compose/blob/main/docker-compose.yml
And after small investigation, i was found, than nginx inside weblate container doesn't have that sting:
```
proxy_set_header X-Real-IP $remote_addr;
```

**Comment by nijel** [comment]
I doubt that anything inside Weblate stack consumes `X-Real-IP` without an additional configuration (and it would be a bug if it would because Weblate can't rely on upstream headers as these might not be coming from a trusted source). https://github.com/WeblateOrg/docker/pull/2897 should be the fix for you.

**Comment by kt315ua** [comment]
@nijel 
> WEBLATE_IP_PROXY_HEADER=HTTP_X_FORWARDED_FOR

It fix a problem, result:
```
gunicorn stderr | [2024-12-19 11:39:28,742: INFO/463] rate-limit lockout for ratelimit-ip-login-60e8ca10e8a8f86c in login scope from 95.***.***.*
```
