### ISSUE TITLE
Skip check if repository exists

### ISSUE THREAD

**Issue by whedro** [WeblateOrg/weblate#1333]
Hi,

My problem is, that GitLab has internal bug (fixing this bug is not priority) and repository web link finished with HTTP status 406 and Weblate can't create component under project ... 
Git clone for repository and other git funcionality (commit, fetch, push, ... ) working without any problem. ..

My question is, if exists or is possible to add functionality, which skipping check if repository url exists ...

Thanks.
Michal

**Comment by nijel** [comment]
AFAIK Weblate doesn't do anything different that `git clone URL` (or rather `git remote set-url origin URL` and `git fetch origin`, but that should be same), so it is probably Git causing these problems...

What error do you actually get?

**Comment by whedro** [comment]
Hi Nijel, 

sorry, I try it again and working  without problem now so far ...

Michal

**Comment by nijel** [comment]
In case it happens again, please note the error you get, that way we can look at what has actually caused it.

**Comment by whedro** [comment]
Sorry, I know .. :) it was meant like question or consultation .. (next step will be error message) :)
