### ISSUE TITLE
Remove pt-PT language - keep pt and pt-BR [Updated]

### ISSUE THREAD

**Issue by horus68** [WeblateOrg/weblate#13336]
### Describe the problem

There is no need to have 2 "European portuguese" languages for the Weblate project
https://hosted.weblate.org/projects/weblate/
This is causing issues in consistence and extra work!

### Describe the solution you would like

remove the "pt" language . The pt-PT language should be used instead.
https://hosted.weblate.org/projects/weblate/-/pt/

Keep those:
pt_PT (European portuguese)
https://hosted.weblate.org/projects/weblate/-/pt_PT/

pt_BR (Portuguese - Brazil)
https://hosted.weblate.org/projects/weblate/-/pt_BR/

### Additional context

The code "pt" is only used when there is no more portuguese flavours (usually in new projects) and it referes to the Portuguese (European) reference.
A translation project should have 2 portuguese flavours:
the main pt_PT (European portuguese / Portugal) and a pt_BR (Portuguese - Brazil)

**Comment by nijel** [comment]
If we're going to remove something, then it should be `pt_PT`. `pt` is needed as fallback when the user has configured Portuguese in the browser. Presently, `pt_PT` and `pt` differ considerably, so I'm not really in position to remove either of these without knowledge of the language.

Looking at https://en.wikipedia.org/wiki/Portuguese_language#Lusophone_countries, `pt` still covers tens of millions of speakers outside `pt_PT` and `pt_BR`.

**Comment by horus68** [comment]
I'm a `pt-PT` portuguese native translator.
`pt-PT` it's the proper code for Portuguese (European), the origin of the portuguese language, and the default for any portuguese speaking country, except for Brazil (`pt-BR`) that has a quite different language use. All other countries on that "Lusophone countries" list just uses the p`t_PT` version.

"pt" it's only used when a system doesn't have pt-BR translation (from an initial bad setup for sure). Has soon as pt-BR comes along ()

The weblate "`pt`" version has been also translated by translators from Portugal (and some Brazilian users by mistake). 
What have we now? two different versions none of them a perfect one!
Has for now, pt-PT has a better translation in Weblate!

So, for me the `pt-PT` version will be the one I will be involved with, even if I get wrong suggestions form the "pt" version

**Comment by rffontenelle** [comment]
Brazilian Portuguese translator here. I'm used to see `pt` as European Portuguese. Since it is a fallback locale (for pt_BR and any other variant), it will work fine for systems set with `pt-PT` locale.

The current translation differences between `pt` and `pt-PT` should be considered and fixed before dropping the variant. For instance, a Brazilian translation in `pt` (wrong) should be replaced with the translation from `pt-PT` if any. This might take some time and effort, so my suggestion is to do some coordination e.g. checklist, talking with other active Portuguese translators ao that everyone is on the same page, etc

**Comment by horus68** [comment]
@nijel  To keep pt and remove pt-PT, I have reviewed all strings translated in `pt` files that **had been translated differently** in `pt-PT` so that nothing is lost when pt-PT is removed. It is now safe to delete the pt-PT language!

I also changed the title of this issue.

After removing the pt-PT language, I will make translations in the pt language
