### ISSUE TITLE
Broken captcha for registration and password reset in 5.9+

### ISSUE THREAD

**Issue by kt315ua** [WeblateOrg/weblate#13335]
### Describe the issue

On 5.7.2.2 registration and password reset working well. 5.8.4 also seems fine.
On 5.9.1 i can't register new account via superuser administration page, because new user can't pass registration by invitation link.
The same problem with password reset.

Our temporary solution: downgrade to 5.8.4 
Server configuration described here: https://github.com/WeblateOrg/weblate/issues/13325
Possible relevant issue: https://github.com/WeblateOrg/weblate/issues/13322

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. register new account via superuser administration page
2. try pass registration via received invitation link

Log error:
```
gunicorn stderr | [2024-12-18 15:58:43,040: ERROR/453] Invalid altcha solution: (None,)
```

### Expected behavior

New user successfully registered

### Screenshots

![Знімок_20241218_152652](https://github.com/user-attachments/assets/cddfb5db-72b7-4f96-ba3f-ca2e551e80cb)
![Знімок_20241218_152710](https://github.com/user-attachments/assets/c59e55da-fa9f-4657-892e-3127a61f8390)
![Знімок_20241218_152739](https://github.com/user-attachments/assets/81b3c5c2-bcf5-464a-9c27-14047916a0f7)
![Знімок_20241218_152749](https://github.com/user-attachments/assets/45a29ef2-4b2a-4073-a553-f90c8eab787f)
![Знімок_20241218_152800](https://github.com/user-attachments/assets/cadc928d-14a5-426a-8b2c-465f9b7a377b)
<img width="580" alt="image" src="https://github.com/user-attachments/assets/241270a1-0d17-4541-b5a1-e45b6c497c3e" />

### How do you run Weblate?

Docker container

### Weblate versions

5.9.1 - issue exist
5.8.4, 5.7.2.2 - no issue

**Comment by nijel** [comment]
Do you see any errors in the browser console?

**Comment by kt315ua** [comment]
@nijel 
I don't see issues in the browser console (adblock, duck-duck-go are disabled)

**Comment by nijel** [comment]
Okay, there is a bug in our code that rejects any captcha after initial one fails. This one is fixed in https://github.com/WeblateOrg/weblate/pull/13338.

There also seems to be something wrong in altcha itself what makes solutions randomly not pass, I've reported that at https://github.com/altcha-org/altcha-lib-py/issues/10.
