### ISSUE TITLE
Usernames are converted to lower case

### ISSUE THREAD

**Issue by nifgraup** [WeblateOrg/weblate#1335]
### Steps to reproduce
1. Visit /accounts/register/, create an account with capital letters in the username
2. Visit /accounts/login/, try to log with that username

### Actual behaviour
Login doesn't work, only lower case version of username works

### Expected behaviour
Username should work as registered

weblate-2.10

**Comment by nijel** [comment]
Yes, python-social-auth defaults to this behaviour but it is indeed unexpected in this case.

**Comment by nifgraup** [comment]
Nice, that was quick!
