### ISSUE TITLE
Getting VCS info from the API without those permissions

### ISSUE THREAD

**Issue by mikefonted** [WeblateOrg/weblate#1343]
### Steps to reproduce
1. Create a project, a component and enable Group ACLs (it may happen without enabling, but not tested)
2. Create a group with "trans | Project | Can access project foobar" permission (only this)
3. Assign that group to a user
4. Log in with that user and access to foobar project and its components and translations
5. Check you can't see VCS info anywhere (nor in Information section)
6. Request GET /api/components/ via Weblate's Web API

### Actual behaviour
You get "vcs", "repo", "branch", "filemask"... fields and values.

### Expected behaviour
You should not get that info. The information you get from the API should be the same (or less) you get from the web.

### Weblate version
2.10

**Comment by nijel** [comment]
Only filemask is not visible in the web interface and I don't see problem in exposing it in API (you can see all filenames in the web, so figuring out mask is not really tricky).

For example: https://hosted.weblate.org/projects/weblate/master/#information

**Comment by mikefonted** [comment]
Following **Steps to reproduce**...

7. That user goes to Information section of the component and this is all what he sees

![component-information](https://cloud.githubusercontent.com/assets/6642583/22498275/9432c4a6-e857-11e6-8619-a5d937f23d41.png)

**Comment by nijel** [comment]
Okay this hiding is not intentional, that's why it's exposed in the API :-). But you're true this should behave consistently.
