### ISSUE TITLE
pyLibravatar not detected by recent VCS checkouts

### ISSUE THREAD

**Issue by pmattern** [WeblateOrg/weblate#1345]
### Steps to reproduce
* Install recent master checkouts of Weblate on Arch Linux or Debian stretch according to the [Installation instructions](https://docs.weblate.org/en/latest/admin/install.html).
* Check URL `./admin/performance` or output of `python manage.py list_versions`.

### Actual behavior
pyLibravatar is not detected both according to the "Performance Report" (`./admin/performance/`) as well as the output of `python manage.py list_versions`.

### Expected behaviour
pyLibravatar should be detected.

### Server configuration
```
 * Weblate weblate-2.11-33-gc85727227
 * Python 3.5.3
 * Django 1.10.5
 * six 1.10.0
 * social-auth-core 1.1.0
 * social-auth-app-django 1.0.1
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.2
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.3
 * pytz 2016.10
 * pyuca N/A
 * python-bidi 0.4.0
 * PyYAML 3.12
 * git-review 1.25.0
 * Database backends: django.db.backends.sqlite3
```

### Additional notes

Seen running several commits from the last days including c857272.
Same findings on Arch Linux (Python 3.6) and Debian stretch/testing (Python 3.5).
All dependencies installed from the PyPI. Same findings on Arch Linux when using the binary packages provided by the distribution instead.
Setting `ENABLE_AVATARS = True` in `settings.py` doesn't help (for testing only, I'm aware this [shouldn't be needed](https://docs.weblate.org/en/latest/admin/config.html#enable-avatars)).

**Comment by nijel** [comment]
I'm not aware of any related change, also it works fine for me.

Does the libravatar module work for you? Can you try `python -c 'import libravatar'`?

**Comment by pmattern** [comment]
```
# python -c 'import libravatar' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/libravatar.py", line 27, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'
```
Other modules work, e. g.
```
# python -c 'import pyuca' 
# python -c 'import pytz'
# 
```
A dns dependency hadn't been pulled
```
# pip list --format=columns | grep -i dns
# 
```
All findings the same on both systems in question.

**Comment by nijel** [comment]
That explains why it does not work ;-). Install py3dns.

**Comment by pmattern** [comment]
Installing py3dns makes `python -c 'import libravatar'` behave as expected and fixes both findings posted in the initial comment.
Btw. as for the former installing pydns has the same effect with regards to Python 2.

So on the one hand sorry for the noise.

On the other hand I was tricked into thinking Weblate is to blame because pyLibravatar apparently does not pull a crucial dependency.
So isn't this a bug in pyLibravatar? Or is it due to the somewhat special situation that the implementations "pydns" of Python 3 and 2 respectively are maintained by different upstream projects?
Also, wouldn't it make sense to mention py[3]dns in section [Software requirements](https://docs.weblate.org/en/latest/admin/install.html#software-requirements) of the installation instructions?

**Comment by nijel** [comment]
Yes, it's bug in their packaging...

**Comment by pmattern** [comment]
FYI https://bugs.launchpad.net/pylibravatar/+bug/1661218.
