### ISSUE TITLE
CSV import problems

### ISSUE THREAD

**Issue by glamic-ep** [WeblateOrg/weblate#1346]
I have a [CSV file](https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/locale/en_US/Mage_Customer.csv) with Key, Value structure that I'd like to import into Weblate. I use the Simple CSV file format for this. The file contains some stuff like `"Customer will stay on the current page if ""No"" is selected.","Customer will stay on the current page if ""No"" is selected."` (quote escapes).

The file is not imported correctly. I'm seeing keys/values with commatas and quotes in them. I'm not sure if the quote escapes are the reason for this. I tested with a simple Python script like

```
import csv

with open('test.csv', 'r') as csvfile:
	reader = csv.reader(csvfile, delimiter=',', quotechar='"')
	for row in reader:
		print row
```

which gives correct output. I'm not sure if Weblate uses translate-toolkit for parsing CSV files, but it seems like translate-toolkit uses a homegrown CSV parser that might fail for such files. Is this a problem of translate-toolkit or can something be done on Weblate side?

**Comment by nijel** [comment]
It doesn't use own parser, it just builds on top of the standard python one, so it should be possible to support this as well. The problem is how to recognize which dialect to use.

**Comment by nijel** [comment]
However I've added tests based on this and it seems to work just fine.

BTW: The translate-toolkit uses csv.Sniffer on first 1024 bytes to decide format of the CSV file, so most likely this is broken for your case...

**Comment by glamic-ep** [comment]
> BTW: The translate-toolkit uses csv.Sniffer on first 1024 bytes to decide format of the CSV file, so most likely this is broken for your case...

Ah, thanks for the hint, this now breaks. I experimented with it and moved some of the problematic lines down in the file so that the sniffer works correctly.
