### ISSUE TITLE
Simple CSV: empty CSV for one language prevents creating component

### ISSUE THREAD

**Issue by glamic-ep** [WeblateOrg/weblate#1347]
I wanted to add a component with the Simple CSV format. One language CSV is empty. When I add the component I get an error regarding not being able to parse the specific language file (original message in German hence I can't post the exact error message).

Workaround is to have some content in every language file.

**Comment by nijel** [comment]
Currently this is how Weblate checks that the parser isn't broken - if it does serialize to empty string, it's considered broken. This is because some of the translate-toolkit parsers happily consume anything and claim it has no translations afterwards...

**Comment by nijel** [comment]
The problem is that if you're using CSV as bilingual file format, there would be no units shown in this language, so I think rejecting empty file is the right thing here.

**Comment by glamic-ep** [comment]
I can live with that limitation. CSV is not a great format for translations anyway.

**Comment by nijel** [comment]
That's true ;-).
