### ISSUE TITLE
Suppress identical suggestions (by anonymous user)

### ISSUE THREAD

**Issue by local-minimum** [WeblateOrg/weblate#1348]
### Steps to reproduce
While not logged in:

1. Suggest a translation
2. Suggest the exact same translation again

### Actual behaviour
This creates multiple identical suggestions.

### Expected behaviour
Several options available here but I would expect default behaviour to be that the user actually casts an up-vote on the first instance of suggested string.

As a side issue in the same vein, if a suggestion is identical to the actual active translation, it should be refused.

Another side, if for some reason the `same as active translation` is triggered after the suggestion has been made, the suggestion should also be removed. This may not be an issue if multiple identical suggestions are refused or collapsed, but at present there can be zero-change suggestions.

I would assume all of this is an issue for multiple logged in users too and would be expected to behave identical to suggested anonymous behaviour.

If the community don't agree with my view here, I would suggest allowing for a setting to trigger `collapse and up-vote` behaviour.

### Server configuration
Don't know, I'm not maintainer of the installation.

**Comment by nijel** [comment]
There is already logic to remove duplicated suggestions in the `cleanuptrans` management command, however it does not do any voting, it simply removes the duplicate.

As for voting there is another problem - the votes are currently unique per user, what makes it impossible for anonymous users to vote, see https://github.com/WeblateOrg/weblate/issues/988. Actually you really do not want anonymous users to be able to give unlimited number of votes, so there has to be something preventing this.

**Comment by nijel** [comment]
I've adjusted the code to avoid accepting duplicate suggestions. As for anonymous voting let's discuss this in separate issue if you want to push that.

**Comment by Sebioff** [comment]
Disallowing duplicate suggestions is good, but turning them into votes as initially suggested would be preferable. I understand the problem with anonymous users, but would it be possible to do it for logged-in users instead of showing them an error message?

In our case we've asked people repeatedly to check existing suggestions first to vote and put it as a note on the whiteboard, yet we keep getting lots of duplicate suggestions.

**Comment by nijel** [comment]
Okay, created separate issue for that: https://github.com/WeblateOrg/weblate/issues/1375
