### ISSUE TITLE
Notify on pending suggestions on specific language

### ISSUE THREAD

**Issue by local-minimum** [WeblateOrg/weblate#1349]
I'm not responsible for an entire installation of Weblate but I've been given moderation over one language of a rather large and dynamic project (the Itch-app). The last thing I'd want  to do is to subscribe to changes in any of its translations and I can't see any way to be notified when there are suggestions on my language.

I would love the following type of options:

- Once per day at maximum on new suggestions on my language.
- Notification on negative change on coverage of translation on my language.
- Possibly also notifications on discussions on language specific translations for my language.

**Comment by nijel** [comment]
Depends on digest notifications availability, see https://github.com/WeblateOrg/weblate/issues/1046.

**Comment by Naruto0** [comment]
Now the settings panel shows both the component as well as language settings. I should proceed by separating the settings, one panel should be for component, another per selected language only.

**Comment by nijel** [comment]
I think it can stay as it is right now in a single panel. In the long term, there should be way to select notifications for each component instead of globally.

**Comment by Naruto0** [comment]
I tought the aim of this issue is to set up a langueage to be digest on.

**Comment by nijel** [comment]
There is no notification on pending suggestions right now, so it's new notification overall, not something to be changed. In the long term there should be digest option for all notifications...

**Comment by Naruto0** [comment]
What actually are pending suggestions? Non reviewd translation suggestions? So the task is to include pending suggestions in reporting and to add an option to get the suggestions?

Thank you.

**Comment by nijel** [comment]
Any existing Suggestion objects. The task is to send daily notification if there are any suggestions on the translation.

**Comment by Naruto0** [comment]
So why I'm I assigned to closed ticket?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
