### ISSUE TITLE
Translation reminders

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1352]
It might be useful feature to remind users there is something to translate:

- Add additional subscription item for daily or weekly reminders about strings to translate
- Every time send one not translated string to a user

This might motivate contributors to work on translation.

**Comment by emmapeel2** [comment]
As a random translator maybe busy with other thing, I find this forgotten bot email very dissapointing.
On the other hand they don't feel so bad when they are really written by somebody, talking about the current situation of the translation, etc.

Nevertheless it is important to keep in touch with the translators!

I would rather improve the ability of the Project Managers to connect with the translators of the project, maybe a 'share this component with: [translators to Farsi that havent logged in the last 6 months] and then you can add a note.

**Comment by nijel** [comment]
I forgot to mention one important thing: of course this would be opt-in feature.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
