### ISSUE TITLE
Turn hook scripts to addons

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1353]
Currently the hook scripts are more kind of hack for special purposes while in most cases they serve quite common tasks. This should be more integrated to Weblate:

- [x] turn the most used scripts into Python modules
- [x] let them declare dependencies (eg. on file format or vcs)
- [x] allow project owners to enable these in component configuration
- [x] the addons will automatically hook into right place (post commit, post update, ...)
- [x] the addons should be able to adjust component parameters such as additional files to commit

**Comment by nijel** [comment]
Work in progress:

![screenshot-2018-2-2 hello gettext](https://user-images.githubusercontent.com/212189/35722687-99e885fa-07f7-11e8-84c2-d1694d974bb0.png)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by Flohack74** [comment]
I got a lot of translation projects in Weblate, is there a way to batch-add the pot-in-po addon to all of them?

**Comment by nijel** [comment]
Weblate 3.2 will come with [install_addon](https://docs.weblate.org/en/latest/admin/management.html#install-addon) management command for that.
