### ISSUE TITLE
Migration fails while trying altering the 'trans_project.slug' column from NULL to NOT NULL

### ISSUE THREAD

**Issue by nschonni** [WeblateOrg/weblate#1354]
### Steps to reproduce
1. Clone the weblate project (currently 2.12-dev)
2. This is a windows machine so the following packages should be installed before the regular pip
- `pip install lxml==3.6.0`
- `pip install pypiwin32`
- `pip install django-mssql`
3. `pip install -r requirements.txt`
4. Configure the DATABASE section according to the docs http://django-mssql.readthedocs.io/en/latest/settings.html
5. Run `python ./manage.py migrate` from the weblate root/cloned directory

### Actual behaviour
While running the migration from an empty weblate install, the migration fails when altering the trans_project.slug from a nullable column from a non-nullible column because of the for

Full log here https://gist.github.com/nschonni/c68c3a27818e9b243c049bc9009832c6

### Expected behaviour
The migration should drop/reapply the constraint and continue the migration

### Server configuration
Please paste the output of command `./manage.py list_versions` over here
c:\inetpub\wwwroot\weblate>python ./manage.py list_versions
 * Weblate 2.12-dev
 * Python 2.7.13
 * Django 1.10.5
 * six 1.10.0
 * social-auth-core 1.1.0
 * social-auth-app-django 1.0.1
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.10.1.windows.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.6.0
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pyuca N/A
 * git-svn 2.10.1.windows.1
 * Database backends: sqlserver_ado

**Comment by nijel** [comment]
IMHO this is bug in django-mssql as there is no problem with other databases on this migration.

Also the problematic migration does not change whether the field can or can not be null, what it changes is its length.

**Comment by nijel** [comment]
And it's known issue of django-mssql, see https://bitbucket.org/Manfre/django-mssql/issues/77/cannot-change-column-with-index.

**Comment by nschonni** [comment]
Thanks for the link, that does look like the issue. For whatever reason I can't access bitbucket at work so I couldn't check that tracker. I'll try one of the other ODBC drivers to see if it can get past that.
