### ISSUE TITLE
How to get a random set for proof reading?

### ISSUE THREAD

**Issue by aggsol** [WeblateOrg/weblate#1362]
Or a list of string that haven't been read/written for a while?

**Comment by nijel** [comment]
There is nothing like this right now.

**Comment by nijel** [comment]
Where would you expect such thing to be available and what search options would you find useful?

**Comment by aggsol** [comment]
Language -> Overview -> Tools
Something like 25 random strings for proof reading so I can check a set every day. Or the 25 least reviewed or oldest strings are then presented.
