### ISSUE TITLE
Cannot disable automatic checks

### ISSUE THREAD

**Issue by stefk** [WeblateOrg/weblate#1363]
Hello,

My colleagues and I work on monolingual translation files and most of the default quality checks don't make sense in that scenario (lots of false positives). I'd like to disable them altogether but they keep showing up no matter what. I've tried this in *settings.py* without success:

```py
CHECK_LIST = ()
AUTOFIX_LIST = ()
```

Is there anything else I should do? I've deployed the app through docker if it matters.

**Comment by nijel** [comment]
The configuration works just fine for me. What might be confusing though is that removing the checks from configuration will not make them disappear automatically, you need to rerun them (eg. by updatechecks management command).

**Comment by stefk** [comment]
Thanks! I was pretty sure I had disabled them before creating components with `import_json` but I might have done something wrong after all.

`updatechecks` makes indeed disappear the checks for individual translation files, however they still appear in the progress bars of components summary and component lists. For example, in the view below, I keep seeing failing checks for *activity-tool-plugin_description*:

![components](https://cloud.githubusercontent.com/assets/880921/22879797/fb7ce0f6-f1df-11e6-9aa3-db66c1378df2.png)

whereas there's no trace of it when I look at the details of that component (expected behaviour):

![component-details](https://cloud.githubusercontent.com/assets/880921/22879888/4cecc136-f1e0-11e6-9c1a-e058ffb7d508.png)

**Comment by nijel** [comment]
Hmm, looks like some caching issue, are there really none in the agenda-agenda component?

**Comment by stefk** [comment]
You're right, most of the problems are gone now -- btw is there a simple/safe way to invalidate the cache? I didn't find anything in the management command list -- but as you said there're still failing checks in agenda-agenda, and in some other places.

**Comment by nijel** [comment]
The checks update command should do that, but it seems there is bug somewhere in that...

**Comment by nijel** [comment]
The coded didn't count on possibility of complete removal of checks and didn't do the cleanup in this case. Fixed now.

**Comment by stefk** [comment]
Thanks, will try this asap!

**Comment by nijel** [comment]
If you're going to patch this manually, there were consequent fixes as well, you need all three patches:

* f02d09f4b Do not skip cleanup when there are no checks to run
* dce568f50 Remove testing if checks to run is empty
* 9da34411c Correctly return empty list of checks to run

**Comment by stefk** [comment]
I can confirm everything is fine after the upgrade. Thanks!
