### ISSUE TITLE
Add translate buttons on component/language screen

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1365]
### Steps to reproduce
1. Go to component/language screen
2. Search for translate button on translation status.

### Actual behaviour
No button is there. Screenshot is attached.
<img width="612" alt="screen shot 2017-02-14 at 12 20 15 pm" src="https://cloud.githubusercontent.com/assets/1279852/22916276/13127b92-f2b0-11e6-813c-881f6e508f2f.png">

### Expected behaviour
I expect to find the translate button right of the progress bars, consistently with the rest of the interface.
I realize that you can click on items in "Strings to check". But it takes me an hour or two to remember each time I don't use Weblate for a week or so. During that hour, I consistently get stuck on that screen.

I think the interface could benefit from being uniform here, even if it brings some redundancy.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
