### ISSUE TITLE
manage.py should return non-zero exit code when hooks fail (or any other failure)

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1367]
### Steps to reproduce
1. Set up a component with git integration
2. Add a pre-commit script, which does "exit 1"
3. Run "./manage.py commit_pending --all --age=1 --verbosity=1"

### Actual behaviour
manage.py reports an error, but returns 0 exit code:
```
ERROR flt/dquest: failed to run hook script /opt/scripts/weblate-flt-v13-precommit.sh: Command '[u'/opt/scripts/weblate-flt-v13-precommit.sh', u'/mnt/data/html/weblate/weblate/../data/vcs/flt/dquest/po/russian.po']' returned non-zero exit status 1
INFO flt/dquest: updating repository
INFO flt/dquest: update took 1.90 seconds:
DEBUG flt/dquest: update: Fetching origin
INFO flt/dquest: pushing to remote repo
```
### Expected behaviour
manage.py should return non-zero in this case, so the failure can be properly detected.

### Server configuration
```
 * Weblate weblate-2.9
 * Python 2.7.5
 * Django 1.10.3
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 1.8.3.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.6.4
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.3
 * pytz 2016.7
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.0
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
Currently failing hooks do not fail commit, regardless whether it is over cli, API or web. When these were added it was intentional, but I'm now not so sure it was good decision...

**Comment by burner1024** [comment]
Just to be clear, this issue is not about aborting commit if a hook fails. (It's debatable, although I would expect it to do so).
Rather, it's about exit code, for which there's a standard convention in POSIX that 0 means successful execution.

**Comment by nijel** [comment]
Well the commit was successfully executed in this case :-). I think either commit should fail or current behavior is correct.

**Comment by burner1024** [comment]
I disagree about it being correct. Succesful completion means that all program actions were completed succesfully, and that's not the case.
However, if you do implement commit abortion, I think that's even better. A hook supposedly has a function on files, and failing it would mean that either something will be missing from the repo, or on the other hand, some unwanted content would be commited.

**Comment by burner1024** [comment]
Or maybe you could make the behaviour configurable, so that everyone could decide for themselves how hook failure should be treated.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
