### ISSUE TITLE
Check pages nest too much with little information, and that make them cumbersome to review

### ISSUE THREAD

**Issue by emmapeel2** [WeblateOrg/weblate#1368]
### Steps to reproduce
1. Logged in in Weblate, go to a project page, click on Tools/Failing checks  or go to your Dashboard / Checks overview
2. Keep clicking until you get to a list of strings with errors.

### Actual behaviour
You dont actually get to an overview, but you need to check through several pages with only one list on each of them
### Expected behaviour
After the first click, only one page with the information nested on the list itself, maybe in this order:
- Check 
  - Language
  - File

or for better review:
- Language
  - Check
  - File

### Server configuration

 * Weblate weblate-2.10.1

**Comment by nijel** [comment]
I'm not against making the navigation easier to use, but please keep in mind that it has to scale to quite a lot of failing checks, so to get overview, you really need to show the summary. For example see:

* https://hosted.weblate.org/checks/?project=phpmyadmin
* https://hosted.weblate.org/checks/?project=andors-trail

This gives you right now quite good overview, with listing all these we would have to paginate the results and you would have no top level view on the data.

**Comment by emmapeel2** [comment]
What about adding the possibility of browsing them as if they were 'strings with failing checks'[1] of a component, but of all components with failing checks of a language instead.

Being able to go one by one, fixing the failing checks.

[1] https://hosted.weblate.org/translate/debian-reference/translations/zh_CN/?type=allchecks

**Comment by nijel** [comment]
You can already use sitewide search for that. It just makes editing one click away. For direct editing we need translate view to work on other scopes as translation and that's covered by https://github.com/WeblateOrg/weblate/issues/49
