### ISSUE TITLE
Failed to verify SSH host key, please add them in SSH page in the admin interface.

### ISSUE THREAD

**Issue by lighter** [WeblateOrg/weblate#1372]
### Steps to reproduce
1. I clone it from https://github.com/WeblateOrg/docker.git
2. I created the weblate on the docker.
3. I open weblate with admin account
4. gen ssh key
5. past the ssh key on my github page
6. created a new project
7. created a new component. 
8. Source code repository: git@github.com:lighter/temp.git

I tried recreate a lot of times container. I still got the error message

**Comment by nijel** [comment]
What error message do you get? Isn't it "Failed to verify SSH host key, please add them in SSH page in the admin interface."? 

So you probably need to verify host key, see https://docs.weblate.org/en/latest/vcs.html#ssh-repositories

**Comment by lighter** [comment]
I got message 

> Failed to verify SSH host key, please add them in SSH page in the admin interface.

**Comment by lighter** [comment]
The container log

> weblate_1   | [21/Feb/2017 15:09:48] "GET /avatar/32/admin.png HTTP/1.0" 200 695
> weblate_1   | [21/Feb/2017 15:09:49] "GET /admin/ HTTP/1.0" 200 12003
> weblate_1   | [21/Feb/2017 15:09:53] "GET /admin/trans/subproject/ HTTP/1.0" 200 5589
> weblate_1   | [21/Feb/2017 15:09:53] "GET /admin/jsi18n/ HTTP/1.0" 200 3217
> weblate_1   | [21/Feb/2017 15:09:55] "GET /admin/trans/subproject/add/ HTTP/1.0" 200 32121
> weblate_1   | [21/Feb/2017 15:09:55] "GET /admin/jsi18n/ HTTP/1.0" 200 3217
> weblate_1   | INFO ocm-frontend-i18n/common_lang: updating repository
> weblate_1   | ERROR ocm-frontend-i18n/common_lang: failed to update repository: No RSA host key is known for gitlab2.astrocorp.com.tw and you have requested strict checking.
> weblate_1   | Host key verification failed.
> weblate_1   | fatal: Could not read from remote repository.
> weblate_1   |
> weblate_1   | Please make sure you have the correct access rights
> weblate_1   | and the repository exists. (128)

**Comment by nijel** [comment]
Yes, you need to add the **host** key:

![ssh-keys](https://cloud.githubusercontent.com/assets/212189/23158182/78be0c18-f81e-11e6-9289-5890cd147f18.png)

**Comment by lighter** [comment]
God. Thank you so much. I tried a lot of time to fix this problem. Thanks again. Have a good day.

**Comment by burner1024** [comment]
I'm having the same problem after server migration. The keys were copied as well, settings weren't changed, but for some reason Weblate refuses to recognize it. I tried deleting the keys and re-adding them, that changed nothing. Any advice?
<img width="808" alt="captura de pantalla 2017-12-03 a las 12 02 54 am" src="https://user-images.githubusercontent.com/1279852/33517829-94d7a4de-d7bd-11e7-9cb7-81969b9626b9.png">
<img width="621" alt="captura de pantalla 2017-12-03 a las 12 03 01 am" src="https://user-images.githubusercontent.com/1279852/33517830-950ecdd8-d7bd-11e7-9eb9-e9e34bcabc42.png">

**Comment by nijel** [comment]
Indeed the ssh wrapper is not updated as moving the whole thing was not really considered. I've fixed this in fd212604088ba2fba2cf50bb5258df70d562ce9b.

PS: It would be better to report this as separate issue, as it's quite easy to miss it here.
