### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by christophemassin** [WeblateOrg/weblate#1374]
### Steps to reproduce
1. Install on ubuntu 
2. Set up nginx server  
3. try to access server

### Actual behaviour
502 bad gateway

### Expected behaviour
- web page should be displayed 
- I can't find the log information related to weblate log. I ve follow the step of the install. I ve check in nginx log, but the error throw is : 
2017/02/20 15:14:08 [error] 8780#8780: *16 connect() failed (111: Connection refused) while connecting to upstream  
[20/Feb/2017:15:14:08 +0000] "GET /admin/ HTTP/1.1" 502 584 "-" 
I would like to have error, from the application but i can't find the best way 
- What is the best place to install weblate ? I ve set it up into /var/www, however the install doc speak about /usr/share/weblate and /var/lib/weblate ( if needed, i can scratch current install ) 
- What is the proper right / user to set ? 

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

**Comment by christophemassin** [comment]
i forgot the uwsdi , but even with it 

2017/02/20 16:26:50 [error] 9616#9616: *2 connect() failed (111: Connection refused) while connecting to upstream, client: X.X.X.X, server: weblate, request: "GET /admin/ HTTP/1.1", upstream: "uwsgi://127.0.0.1:8080", host: "weblate"

**Comment by nijel** [comment]
Is the uwsgi running?

**Comment by christophemassin** [comment]
/var/www/weblate$ service uwsgi status 
● uwsgi.service - LSB: Start/stop uWSGI server instance(s)
   Loaded: loaded (/etc/init.d/uwsgi; bad; vendor preset: enabled)
   Active: active (exited) since Mon 2017-02-20 16:26:43 UTC; 8min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 9656 ExecStop=/etc/init.d/uwsgi stop (code=exited, status=0/SUCCESS)
  Process: 9680 ExecStart=/etc/init.d/uwsgi start (code=exited, status=0/SUCCESS)

Feb 20 16:26:43  systemd[1]: Stopped LSB: Start/stop uWSGI server instance(s).
Feb 20 16:26:43  systemd[1]: Starting LSB: Start/stop uWSGI server instance(s)...
Feb 20 16:26:43  uwsgi[9680]:  * Starting app server(s) uwsgi
Feb 20 16:26:43  uwsgi[9680]:    ...done.
Feb 20 16:26:43  systemd[1]: Started LSB: Start/stop uWSGI server instance(s).

But still a 502 gateway.

**Comment by christophemassin** [comment]
i have install and configure it the proper way i think, but the issue was there previously

**Comment by nijel** [comment]
> Active: active (exited)

That doesn't sound good as it's not running. Did you enable the weblate app in uwsgi?

**Comment by christophemassin** [comment]
● uwsgi.service - LSB: Start/stop uWSGI server instance(s)
   Loaded: loaded (/etc/init.d/uwsgi; bad; vendor preset: enabled)
   Active: active (running) since Mon 2017-02-20 16:51:10 UTC; 22s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 9803 ExecStop=/etc/init.d/uwsgi stop (code=exited, status=0/SUCCESS)
  Process: 9845 ExecStart=/etc/init.d/uwsgi start (code=exited, status=0/SUCCESS)
    Tasks: 3
   Memory: 1.5M
      CPU: 117ms
   CGroup: /system.slice/uwsgi.service
           ├─9976 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/weblate.uwsgi.ini --daemonize /var/log/uwsgi/app/weblate.uwsgi.log
           ├─9977 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/weblate.uwsgi.ini --daemonize /var/log/uwsgi/app/weblate.uwsgi.log
           └─9978 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/weblate.uwsgi.ini --daemonize /var/log/uwsgi/app/weblate.uwsgi.log

**Comment by christophemassin** [comment]
log of uswgi : 

Mon Feb 20 16:56:54 2017 - *** Starting uWSGI 2.0.12-debian (64bit) on [Mon Feb 20 16:56:54 2017] ***
Mon Feb 20 16:56:54 2017 - compiled with version: 5.3.1 20160412 on 13 April 2016 08:36:06
Mon Feb 20 16:56:54 2017 - nodename: 
Mon Feb 20 16:56:54 2017 - machine: x86_64
Mon Feb 20 16:56:54 2017 - clock source: unix
Mon Feb 20 16:56:54 2017 - pcre jit disabled
Mon Feb 20 16:56:54 2017 - detected number of CPU cores: 1
Mon Feb 20 16:56:54 2017 - current working directory: /
Mon Feb 20 16:56:54 2017 - writing pidfile to /run/uwsgi/app/weblate.uwsgi/pid
Mon Feb 20 16:56:54 2017 - detected binary path: /usr/bin/uwsgi-core
Mon Feb 20 16:56:54 2017 - setgid() to 33
Mon Feb 20 16:56:54 2017 - setuid() to 33
Mon Feb 20 16:56:54 2017 - your processes number limit is 3891
Mon Feb 20 16:56:54 2017 - your memory page size is 4096 bytes
Mon Feb 20 16:56:54 2017 - detected max file descriptor number: 1024
Mon Feb 20 16:56:54 2017 - lock engine: pthread robust mutexes
Mon Feb 20 16:56:54 2017 - thunder lock: disabled (you can enable it with --thunder-lock)
Mon Feb 20 16:56:54 2017 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/weblate.uwsgi/socket fd 3
Mon Feb 20 16:56:54 2017 - uwsgi socket 1 bound to TCP address 127.0.0.1:8080 fd 5
Mon Feb 20 16:56:54 2017 - your server socket listen backlog is limited to 100 connections
Mon Feb 20 16:56:54 2017 - your mercy for graceful operations on workers is 60 seconds
Mon Feb 20 16:56:54 2017 - mapped 230592 bytes (225 KB) for 2 cores
Mon Feb 20 16:56:54 2017 - *** Operational MODE: preforking ***
Mon Feb 20 16:56:54 2017 - *** no app loaded. going in full dynamic mode ***
Mon Feb 20 16:56:54 2017 - *** uWSGI is running in multiple interpreter mode ***
Mon Feb 20 16:56:54 2017 - !!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!
Mon Feb 20 16:56:54 2017 - no request plugin is loaded, you will not be able to manage requests.
Mon Feb 20 16:56:54 2017 - you may need to install the package for your language of choice, or simply load it with --plugin.
Mon Feb 20 16:56:54 2017 - !!!!!!!!!!! END OF WARNING !!!!!!!!!!
Mon Feb 20 16:56:54 2017 - spawned uWSGI master process (pid: 10239)
Mon Feb 20 16:56:54 2017 - spawned uWSGI worker 1 (pid: 10240, cores: 1)
Mon Feb 20 16:56:54 2017 - spawned uWSGI worker 2 (pid: 10241, cores: 1)

**Comment by nijel** [comment]
The uwsgi is listening on /run/uwsgi/app/weblate.uwsgi/socket while nginx tries to connect to 127.0.0.1:8080.

Adjust nginx configuration to match uwsgi one:

```
uwsgi_pass unix:///run/uwsgi/app/weblate.uwsgi/socket;
```

**Comment by christophemassin** [comment]
I make the change in /etc/nginx/sites-available ( symlink to enable) : 

server {
    listen 80;
    server_name weblate;
    root /usr/share/weblate;

    location /favicon.ico {
        # DATA_DIR/static/favicon.ico
        alias /var/lib/weblate/static/favicon.ico;
        expires 30d;
    }

    location /robots.txt {
        # DATA_DIR/static/robots.txt
        alias /var/lib/weblate/static/robots.txt;
        expires 30d;
    }

    location /static {
        # DATA_DIR/static/
        alias /var/lib/weblate/static/;
        expires 30d;
    }

    location /media {
        # DATA_DIR/media/
        alias /var/lib/weblate/media/;
        expires 30d;
    }

    location / {
        include uwsgi_params;
        # Needed for long running operations in admin interface
        uwsgi_read_timeout 3600;
        uwsgi_pass unix:///run/uwsgi/app/weblate.uwsgi/socket;
    }
}

i ve restart nginx and uwsgi service 

but still in the log 

nginx
2017/02/21 11:04:29 [error] 11990#11990: *1 upstream prematurely closed connection while reading response header from upstream, client: X.X.X.X, server: weblate, request: "GET /admin/ HTTP/1.1", upstream: "uwsgi://unix:///run/uwsgi/app/weblate.uwsgi/socket:", host: "weblate"

uwsgi
Tue Feb 21 11:04:21 2017 - SIGINT/SIGQUIT received...killing workers...
Tue Feb 21 11:04:22 2017 - worker 1 buried after 1 seconds
Tue Feb 21 11:04:22 2017 - worker 2 buried after 1 seconds
Tue Feb 21 11:04:22 2017 - goodbye to uWSGI.
Tue Feb 21 11:04:22 2017 - *** Starting uWSGI 2.0.12-debian (64bit) on [Tue Feb 21 11:04:22 2017] ***
Tue Feb 21 11:04:22 2017 - compiled with version: 5.3.1 20160412 on 13 April 2016 08:36:06
Tue Feb 21 11:04:22 2017 - os: Linux-4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017
Tue Feb 21 11:04:22 2017 - nodename: ip-10-0-3-40
Tue Feb 21 11:04:22 2017 - machine: x86_64
Tue Feb 21 11:04:22 2017 - clock source: unix
Tue Feb 21 11:04:22 2017 - pcre jit disabled
Tue Feb 21 11:04:22 2017 - detected number of CPU cores: 1
Tue Feb 21 11:04:22 2017 - current working directory: /
Tue Feb 21 11:04:22 2017 - writing pidfile to /run/uwsgi/app/weblate.uwsgi/pid
Tue Feb 21 11:04:22 2017 - detected binary path: /usr/bin/uwsgi-core
Tue Feb 21 11:04:22 2017 - setgid() to 33
Tue Feb 21 11:04:22 2017 - setuid() to 33
Tue Feb 21 11:04:22 2017 - your processes number limit is 3891
Tue Feb 21 11:04:22 2017 - your memory page size is 4096 bytes
Tue Feb 21 11:04:22 2017 - detected max file descriptor number: 1024
Tue Feb 21 11:04:22 2017 - lock engine: pthread robust mutexes
Tue Feb 21 11:04:22 2017 - thunder lock: disabled (you can enable it with --thunder-lock)
Tue Feb 21 11:04:22 2017 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/weblate.uwsgi/socket fd 3
Tue Feb 21 11:04:22 2017 - uwsgi socket 1 bound to TCP address 127.0.0.1:8080 fd 5
Tue Feb 21 11:04:22 2017 - your server socket listen backlog is limited to 100 connections
Tue Feb 21 11:04:22 2017 - your mercy for graceful operations on workers is 60 seconds
Tue Feb 21 11:04:22 2017 - mapped 230592 bytes (225 KB) for 2 cores
Tue Feb 21 11:04:22 2017 - *** Operational MODE: preforking ***
Tue Feb 21 11:04:22 2017 - *** no app loaded. going in full dynamic mode ***
Tue Feb 21 11:04:22 2017 - *** uWSGI is running in multiple interpreter mode ***
Tue Feb 21 11:04:22 2017 - !!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!
Tue Feb 21 11:04:22 2017 - no request plugin is loaded, you will not be able to manage requests.
Tue Feb 21 11:04:22 2017 - you may need to install the package for your language of choice, or simply load it with --plugin.
Tue Feb 21 11:04:22 2017 - !!!!!!!!!!! END OF WARNING !!!!!!!!!!
Tue Feb 21 11:04:22 2017 - spawned uWSGI master process (pid: 12175)
Tue Feb 21 11:04:22 2017 - spawned uWSGI worker 1 (pid: 12177, cores: 1)
Tue Feb 21 11:04:22 2017 - spawned uWSGI worker 2 (pid: 12178, cores: 1)
Tue Feb 21 11:04:26 2017 - -- unavailable modifier requested: 0 --
Tue Feb 21 11:04:28 2017 - -- unavailable modifier requested: 0 --
Tue Feb 21 11:04:28 2017 - -- unavailable modifier requested: 0 --
Tue Feb 21 11:04:28 2017 - -- unavailable modifier requested: 0 --
Tue Feb 21 11:04:29 2017 - -- unavailable modifier requested: 0 --
Tue Feb 21 11:04:29 2017 - -- unavailable modifier requested: 0 --

and 502 gateway

**Comment by nijel** [comment]
Maybe you're missing `uwsgi-plugin-python` package?

**Comment by christophemassin** [comment]
Hello. It solved the issue thanks! Now i got a "simple" internal server error. Digging into it before opening another issue.

**Comment by sourcelocation** [comment]
For future visitors of this thread, in my case I simply forgot to set SECRET_KEY in settings.py

**Comment by Owned67** [comment]
Hello im getting same problem... SECRET_KEY is defined...

all package are installed.

debian 11

service uwsgi status
```
● uwsgi.service - LSB: Start/stop uWSGI server instance(s)
     Loaded: loaded (/etc/init.d/uwsgi; generated)
     Active: active (running) since Tue 2023-10-10 09:33:41 CEST; 4min 32s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 1037475 ExecStart=/etc/init.d/uwsgi start (code=exited, status=0/SUCCESS)
      Tasks: 9 (limit: 4692)
     Memory: 112.1M
        CPU: 8.439s
     CGroup: /system.slice/uwsgi.service
             ├─1037573 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/weblate.uwsgi.ini --daemonize /var/log/uwsgi/app/weblate.uwsgi.log
             ├─1037627 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/weblate.uwsgi.ini --daemonize /var/log/uwsgi/app/weblate.uwsgi.log
             ├─1037628 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/weblate.uwsgi.ini --daemonize /var/log/uwsgi/app/weblate.uwsgi.log
             ├─1037629 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/weblate.uwsgi.ini --daemonize /var/log/uwsgi/app/weblate.uwsgi.log
             ├─1037630 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/weblate.uwsgi.ini --daemonize /var/log/uwsgi/app/weblate.uwsgi.log
             ├─1037632 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/weblate.uwsgi.ini --daemonize /var/log/uwsgi/app/weblate.uwsgi.log
             ├─1037633 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/weblate.uwsgi.ini --daemonize /var/log/uwsgi/app/weblate.uwsgi.log
             ├─1037634 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/weblate.uwsgi.ini --daemonize /var/log/uwsgi/app/weblate.uwsgi.log
             └─1037635 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/weblate.uwsgi.ini --daemonize /var/log/uwsgi/app/weblate.uwsgi.log
```

uwsgi log:
`Tue Oct 10 09:32:47 2023 - *** Starting uWSGI 2.0.19.1-debian (64bit) on [Tue Oct 10 09:32:47 2023] ***
Tue Oct 10 09:32:47 2023 - compiled with version: 10.2.1 20210110 on 11 June 2021 09:08:33
Tue Oct 10 09:32:47 2023 - os: Linux-5.10.0-23-cloud-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12)
Tue Oct 10 09:32:47 2023 - nodename: myvps
Tue Oct 10 09:32:47 2023 - machine: x86_64
Tue Oct 10 09:32:47 2023 - clock source: unix
Tue Oct 10 09:32:47 2023 - pcre jit disabled
Tue Oct 10 09:32:47 2023 - detected number of CPU cores: 2
Tue Oct 10 09:32:47 2023 - current working directory: /
Tue Oct 10 09:32:47 2023 - writing pidfile to /run/uwsgi/app/weblate.uwsgi/pid
Tue Oct 10 09:32:47 2023 - detected binary path: /usr/bin/uwsgi-core
Tue Oct 10 09:32:47 2023 - your processes number limit is 15641
Tue Oct 10 09:32:47 2023 - your memory page size is 4096 bytes
Tue Oct 10 09:32:47 2023 - detected max file descriptor number: 1024
Tue Oct 10 09:32:47 2023 - lock engine: pthread robust mutexes
Tue Oct 10 09:32:47 2023 - thunder lock: disabled (you can enable it with --thunder-lock)
Tue Oct 10 09:32:47 2023 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/weblate.uwsgi/socket fd 3
Tue Oct 10 09:32:47 2023 - bind(): No such file or directory [core/socket.c line 230]
Tue Oct 10 09:33:29 2023 - *** Starting uWSGI 2.0.19.1-debian (64bit) on [Tue Oct 10 09:33:28 2023] ***
Tue Oct 10 09:33:29 2023 - compiled with version: 10.2.1 20210110 on 11 June 2021 09:08:33
Tue Oct 10 09:33:29 2023 - os: Linux-5.10.0-23-cloud-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12)
Tue Oct 10 09:33:29 2023 - nodename: myvps
Tue Oct 10 09:33:29 2023 - machine: x86_64
Tue Oct 10 09:33:29 2023 - clock source: unix
Tue Oct 10 09:33:29 2023 - pcre jit disabled
Tue Oct 10 09:33:29 2023 - detected number of CPU cores: 2
Tue Oct 10 09:33:29 2023 - current working directory: /
Tue Oct 10 09:33:29 2023 - writing pidfile to /run/uwsgi/app/weblate.uwsgi/pid
Tue Oct 10 09:33:29 2023 - detected binary path: /usr/bin/uwsgi-core
Tue Oct 10 09:33:29 2023 - your processes number limit is 15641
Tue Oct 10 09:33:29 2023 - your memory page size is 4096 bytes
Tue Oct 10 09:33:29 2023 - detected max file descriptor number: 1024
Tue Oct 10 09:33:29 2023 - lock engine: pthread robust mutexes
Tue Oct 10 09:33:29 2023 - thunder lock: disabled (you can enable it with --thunder-lock)
Tue Oct 10 09:33:29 2023 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/weblate.uwsgi/socket fd 3
Tue Oct 10 09:33:29 2023 - bind(): No such file or directory [core/socket.c line 230]
Tue Oct 10 09:33:41 2023 - *** Starting uWSGI 2.0.19.1-debian (64bit) on [Tue Oct 10 09:33:41 2023] ***
Tue Oct 10 09:33:41 2023 - compiled with version: 10.2.1 20210110 on 11 June 2021 09:08:33
Tue Oct 10 09:33:41 2023 - os: Linux-5.10.0-23-cloud-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12)
Tue Oct 10 09:33:41 2023 - nodename: myvps
Tue Oct 10 09:33:41 2023 - machine: x86_64
Tue Oct 10 09:33:41 2023 - clock source: unix
Tue Oct 10 09:33:41 2023 - pcre jit disabled
Tue Oct 10 09:33:41 2023 - detected number of CPU cores: 2
Tue Oct 10 09:33:41 2023 - current working directory: /
Tue Oct 10 09:33:41 2023 - writing pidfile to /run/uwsgi/app/weblate.uwsgi/pid
Tue Oct 10 09:33:41 2023 - detected binary path: /usr/bin/uwsgi-core
Tue Oct 10 09:33:41 2023 - your processes number limit is 15641
Tue Oct 10 09:33:41 2023 - your memory page size is 4096 bytes
Tue Oct 10 09:33:41 2023 - detected max file descriptor number: 1024
Tue Oct 10 09:33:41 2023 - lock engine: pthread robust mutexes
Tue Oct 10 09:33:41 2023 - thunder lock: disabled (you can enable it with --thunder-lock)
Tue Oct 10 09:33:41 2023 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/weblate.uwsgi/socket fd 3
Tue Oct 10 09:33:41 2023 - uwsgi socket 1 bound to TCP address 127.0.0.1:8080 fd 5
Tue Oct 10 09:33:41 2023 - setgid() to 1006
Tue Oct 10 09:33:41 2023 - set additional group 0 (root)
Tue Oct 10 09:33:41 2023 - set additional group 5 (tty)
Tue Oct 10 09:33:41 2023 - setuid() to 1005
Tue Oct 10 09:33:41 2023 - Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
Tue Oct 10 09:33:41 2023 - PEP 405 virtualenv detected: /home/weblate/weblate-env
Tue Oct 10 09:33:41 2023 - Set PythonHome to /home/weblate/weblate-env
Tue Oct 10 09:33:41 2023 - Python main interpreter initialized at 0x560867a343a0
Tue Oct 10 09:33:41 2023 - python threads support enabled
Tue Oct 10 09:33:41 2023 - your server socket listen backlog is limited to 100 connections
Tue Oct 10 09:33:41 2023 - your mercy for graceful operations on workers is 60 seconds
Tue Oct 10 09:33:41 2023 - mapped 693288 bytes (677 KB) for 8 cores
Tue Oct 10 09:33:41 2023 - *** Operational MODE: preforking ***
Tue Oct 10 07:33:50 2023 - WSGI app 0 (mountpoint='') ready in 9 seconds on interpreter 0x560867a343a0 pid: 1037573 (default app)
Tue Oct 10 07:33:50 2023 - *** uWSGI is running in multiple interpreter mode ***
Tue Oct 10 07:33:50 2023 - spawned uWSGI master process (pid: 1037573)
Tue Oct 10 07:33:50 2023 - spawned uWSGI worker 1 (pid: 1037627, cores: 1)
Tue Oct 10 07:33:50 2023 - spawned uWSGI worker 2 (pid: 1037628, cores: 1)
Tue Oct 10 07:33:50 2023 - spawned uWSGI worker 3 (pid: 1037629, cores: 1)
Tue Oct 10 07:33:50 2023 - spawned uWSGI worker 4 (pid: 1037630, cores: 1)
Tue Oct 10 07:33:50 2023 - spawned uWSGI worker 5 (pid: 1037632, cores: 1)
Tue Oct 10 07:33:50 2023 - spawned uWSGI worker 6 (pid: 1037633, cores: 1)
Tue Oct 10 07:33:50 2023 - spawned uWSGI worker 7 (pid: 1037634, cores: 1)
Tue Oct 10 07:33:50 2023 - spawned uWSGI worker 8 (pid: 1037635, cores: 1)
`

nginx config: /etc/nginx/sites-enabled/weblate

`
server {
    listen 80;
    listen 443 ssl;
    http2 on;
    server_name translation.mydomain.eu;

    ssl_certificate /etc/letsencrypt/live/translation.mydomain.eu/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/translation.mydomain.eu/privkey.pem;

    # Not used
    root /var/www/html;

    location ~ ^/favicon.ico$ {
        # DATA_DIR/static/favicon.ico
        alias /home/weblate/data/cache/static/favicon.ico;
        expires 30d;
    }

    location /static/ {
        # DATA_DIR/static/
        alias /home/weblate/data/cache/static/;
        expires 30d;
    }

    location /media/ {
        # DATA_DIR/media/
        alias /home/weblate/data/media/;
        expires 30d;
    }

    location / {
        include uwsgi_params;
        # Needed for long running operations in admin interface
        uwsgi_read_timeout 3600;
        # Adjust based to uwsgi configuration:
        uwsgi_pass unix:///run/uwsgi/app/weblate/socket;
        #uwsgi_pass 127.0.0.1:8080;
    }
}
`

nginx return a 502 gateway and error:
`2023/10/10 09:37:50 [notice] 1038567#1038567: using the "epoll" event method
2023/10/10 09:37:50 [notice] 1038567#1038567: nginx/1.25.2
2023/10/10 09:37:50 [notice] 1038567#1038567: built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
2023/10/10 09:37:50 [notice] 1038567#1038567: OS: Linux 5.10.0-23-cloud-amd64
2023/10/10 09:37:50 [notice] 1038568#1038568: start worker processes
2023/10/10 09:37:50 [notice] 1038568#1038568: start worker process 1038569
2023/10/10 09:37:50 [notice] 1038568#1038568: start worker process 1038570
2023/10/10 09:37:50 [notice] 1038570#1038570: sched_setaffinity(): using cpu #1
2023/10/10 09:37:50 [notice] 1038569#1038569: sched_setaffinity(): using cpu #0
2023/10/10 09:43:15 [crit] 1038570#1038570: *2 connect() to unix:///run/uwsgi/app/weblate/socket failed (2: No such file or directory) while connecting to upstream, client: XX.XX.XX.XXX, [serve>](server: translation.mydomain.eu, request: "GET / HTTP/2.0", upstream: "uwsgi://unix:///run/uwsgi/app/weblate/socket:", host: "translation.mydomain.eu")
2023/10/10 09:43:16 [crit] 1038570#1038570: *2 connect() to unix:///run/uwsgi/app/weblate/socket failed (2: No such file or directory) while connecting to upstream, client: XX.XX.XX.XXX, [serve>](server: translation.mydomain.eu, request: "GET / HTTP/2.0", upstream: "uwsgi://unix:///run/uwsgi/app/weblate/socket:", host: "translation.mydomain.eu")
`
