### ISSUE TITLE
Add support for WebExtension json [$100]

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1380]
There is *yet another* JSON variant widely used for translating WebExtensions, see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization

It would be great to support it, ideally the support should be first included in the [translate-toolkit](https://github.com/translate/translate/).

**Comment by alexander255** [comment]
*Note*: The format (just like about everything else in wext) is identical to that of Chrome:
https://developer.chrome.com/extensions/i18n (also issue #650).

So the underlying issue that needs to be fixed is with translate toolkit: #775 (as you said after that some extra integration may be required through).

**Comment by nijel** [comment]
Yes, the preferred approach is to fist support this format in translate-toolkit and then add integration to Weblate (which would most likely consist just from registering the format).

It's also possible to implement this purely in Weblate, but that would be first format with Weblate only support and it's better to have these in generic library.

**Comment by nijel** [comment]
Translate-toolkit support is here: https://github.com/translate/translate/pull/3665

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by danielnaber** [comment]
Great, thanks! When will this be on https://hosted.weblate.org?

**Comment by nijel** [comment]
It really depends on the review of pull request on translate-toolkit, I don't want to run code which might get rejected for some reasons later. The Weblate side of this will be certainly deployed in next days.
