### ISSUE TITLE
Error uploading PO file

### ISSUE THREAD

**Issue by phw** [WeblateOrg/weblate#1381]
### Steps to reproduce
See https://github.com/gnunn1/terminix/issues/795
1. Upload the PO file included in [terminix.zip](https://github.com/WeblateOrg/weblate/files/796628/terminix.zip) via files > upload translation on https://hosted.weblate.org/projects/terminix/translations/pl/#upload

### Actual behaviour
When I tried it showed me an "Internal server error" page, @psokol reported the error "get() returned more than one Unit -- it returned 2!". I first assumed there were maybe duplicate messages in the file, but checked with msguniq

### Expected behaviour
The file gets importet, or if there is an actual problem with the file a better error message is shown

### Server configuration
Hosted Weblate

**Comment by phw** [comment]
Some more details: I can reproduce the issue with the German translation, uploading gives:

    File content merge failed: get() returned more than one Unit -- it returned 2!

My suspicion is that we maybe had duplicates in the POT files, I vaguely remember having cleaned out some duplicate strings. Currently there are none, but maybe they still stick around on Weblate?

**Comment by nijel** [comment]
Also tracked as https://github.com/WeblateOrg/weblate/issues/1385

**Comment by nijel** [comment]
Fix has been deployed right now.

**Comment by phw** [comment]
Thanks a lot, it's working now. Can you say a bit about the cause? The patch still looks a bit like its is really duplicate source strings as I assumed. But currently we don't have such in our translations.

**Comment by nijel** [comment]
The "problem" was caused by having same translation with and without context and the code didn't handle this properly. I've realized the problem just after pushing original fix and I've rewritten it in 5afd1ecac8e18ff678027ed42687c7e86866d666 what should work correctly in such case.
