### ISSUE TITLE
Project information widget is empty on one project

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1383]
### Steps to reproduce
It happens on one project, and not others, so not sure about the steps. Possibly started after moving components between projects.
I checked uwsgi logs, and can't find anything related. I also tried restarting uwsgi and flushing redis cache, to no avail.
<img width="586" alt="screen shot 2017-02-25 at 11 05 13 am" src="https://cloud.githubusercontent.com/assets/1279852/23327982/8d3ef3cc-fb49-11e6-8fef-647836ea27c4.png">
### Actual behaviour
Project Information doesn't display project site, license, repo info, etc. See screenshot.

### Expected behaviour
Project info (site, license, repo) should be displayed in the widget.

### Server configuration
```
 * Weblate weblate-2.9
 * Python 2.7.5
 * Django 1.10.3
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 1.8.3.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.6.4
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.3
 * pytz 2016.7
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.0
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
Is the information filled in for the project?

**Comment by nijel** [comment]
Anyway I can not reproduce this with current version, so upgrading might solve this as well.

**Comment by burner1024** [comment]
Upgrade was a little bumpy, but it seems to have cleaned the issue. Thanks!
