### ISSUE TITLE
List pending suggestions of specific user (to review easily)

### ISSUE THREAD

**Issue by emmapeel2** [WeblateOrg/weblate#1395]
### Steps to reproduce
1. Open contributor page

### Actual behaviour
You can see how many suggestions usr has done, but **there is no way of seeing if this user has suggestions pending for review**.

### Expected behaviour
It should be easy to access a list of the pending suggestions of this contributor.
This will make the workflow swifter as you can assess a whole working session at the same time.

**Comment by emmapeel2** [comment]
maybe it can be addressed along with #1349

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
