### ISSUE TITLE
Other translations: 2.12 regression?

### ISSUE THREAD

**Issue by marcperrin** [WeblateOrg/weblate#1396]
Hello,

Looks like "Other translations" always features the **current unit** (tagged as **"This translation"**)

I feel this is a **2.12 regression** (well, kind of by design - cf. 88663cf524d82c0b9a50e2fb571e031ddb2f5951)

Looking a bit more into this commit, I feel we should just hide the output when the only returned item is the current translation - the current on-screen behaviour is a bit unsettling...

(When there are indeed items with same source & context in other components, then I agree it's useful to see the current unit right along the other ones i.e. you have a direct consistency check view) 

Also, gotta make sure that `others_count` works as expected.

On a separate note, do you think it might be useful to see (somewhere...) the "Other translations" but with same source and not necessarily same context - i.e. both intra-component and across components... ?

Thanks,

Marc

**Comment by nijel** [comment]
Showing only current translation is not intentional outcome, it should be shown only if there are others.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
