### ISSUE TITLE
Fails to install siphashc3 using requirements.txt when upgrading Weblate to version 2.12

### ISSUE THREAD

**Issue by magnuskenneth** [WeblateOrg/weblate#1397]
### Steps to reproduce
1. When upgrading to version 2.12, run: `pip install -r requirements.txt`

### Actual behaviour
`pip install -r requirements.txt` gives the following error:
```
Downloading/unpacking siphashc3 (from -r requirements.txt (line 2))
  Could not find a version that satisfies the requirement siphashc3 (from -r requirements.txt (line 2)) (from versions: 3, 2, 1)
Cleaning up...
No distributions matching the version for siphashc3 (from -r requirements.txt (line 2))
```

### Expected behaviour
It should install siphashc3.

I solved this by installing siphashc3 separately and pointing out version 3 explicitly:
`pip install siphashc3==3`

I guess the solution is to update the requirements.txt to point to version 3 (`siphashc3==3` or `siphashc3>=3`)

I´m using Python 2.7.5.

**Comment by nijel** [comment]
What pip version do you have? It works just fine for me...

**Comment by magnuskenneth** [comment]
I´m using pip version 1.4.1. I tested upgrading pip to version 9.0.1 and then it worked just fine. You can close this issue.

Thank you!

**Comment by nijel** [comment]
Strange, I'm not sure why it does not work there. The oldest I can find on my systems is pip 1.5.6 and it works just fine there....

**Comment by ruslanfedoseenko** [comment]
Have same issue with pip 1.5.4

**Comment by nijel** [comment]
Maybe the library versioning is the problem (it's a bit unusual). Anyway we might look for other implementation to use...

**Comment by nijel** [comment]
Apparently it's time to forward this to upstream: https://github.com/carlopires/siphashc3/issues/1
