### ISSUE TITLE
Installation failded on OpenShift 

### ISSUE THREAD

**Issue by padicao2010** [WeblateOrg/weblate#1399]
### Steps to reproduce
1. rhc -aweblate app create -t python-2.7 --from-code https://github.com/WeblateOrg/weblate.git --no-git

I've also tried 2.12, but it shows up the same error.

### Actual behaviour

```
Executing 'python /var/lib/openshift/.../app-root/runtime/repo//openshift/manage.py loaddata /var/lib/openshift/.../app-root/runtime/repo//weblate/fixtures/site_data'
  CommandError: No fixture named 'site_data' found.
```

Installation failed!

Besides, it failed to install py3dns

```
Executing 'pip install --no-cache-dir --disable-pip-version-check py3dns; python_version >= '3.0''
  Collecting py3dns
    Downloading py3dns-3.1.0.tar.gz
      Complete output from command python setup.py egg_info:
      Traceback (most recent call last):
        File "<string>", line 20, in <module>
        File "/tmp/pip-build-Tvajrm/py3dns/setup.py", line 7, in <module>
          import DNS
        File "/tmp/pip-build-Tvajrm/py3dns/DNS/__init__.py", line 21, in <module>
          raise Exception("py3dns 3.1 requires either ipaddress (python3.3) or ipaddr, see CHANGES for 3.1.0")
      Exception: py3dns 3.1 requires either ipaddress (python3.3) or ipaddr, see CHANGES for 3.1.0
```

**Comment by nijel** [comment]
The pip installation failure seems to be intentional (at least the comment suggests so), I really don't know enough about OpenShift to look into that. I've fixed the original error you've reported as it's leftover from some other changes.

Also it would be great if somebody experienced with OpenShift would contribute automated tests for it, so that we can figure out immediately when something breaks...

**Comment by padicao2010** [comment]
Great, it works.

However, there is a small bug in _openshift/install.sh_: line 67

```
sh "pip install --no-cache-dir --disable-pip-version-check $line" || true
```

For those requirements containing '<' or '>', it just checks the package, but it hasn't checked the version, because it treats '<' or '>' as I/O redirection. 

So, $line is supposed to be surrounded with single quotes.

**Comment by nijel** [comment]
Fixed in a296f713e030604f4f4fc35d9abc33c3aa976798, thanks for pointing out (not that I understand  this file).

**Comment by padicao2010** [comment]
Me again.

Because some optional requirements already have single quotes, like "py3dns; python_version >= '3.0'" and "Mercurial>=2.8; python_version < '3.0'", a296f71 brings out more problems. 

So, use "\\"", or remove all single quotes in _requirements-optional.txt_.

**Comment by nijel** [comment]
Hopefully fixed now. This really lacks testing...
