### ISSUE TITLE
Source language gets failing check that source and translated strings are same

### ISSUE THREAD

**Issue by magnuskenneth** [WeblateOrg/weblate#1401]
### Steps to reproduce
1. In the admin interface, add a component (subproject) and set a source language (Monolingual base language file).
2. In the Weblate interface, go to the source language of that component.

### Actual behaviour
Almost all strings have the failing check: Source and translated strings are same.

### Expected behaviour
That warning should not be there on the source language since it is always same.

### Server configuration
* Weblate weblate-2.11
 * Python 2.7.5
 * Django 1.10.6
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.0
 * defusedxml 0.5.0
 * Git 1.9.3
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.4.4
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.4
 * pytz 2015.2
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.4
 * Database backends: django.db.backends.mysql

**Comment by magnuskenneth** [comment]
This happens on a component where the source language is Swedish and file format is OSX strings (utf-8). I have not the same problem on other projects where the source language is English.

**Comment by nijel** [comment]
Do you have set source language in that project to Swedish? This is really supposed to work correctly since ad20f88b1f.

**Comment by magnuskenneth** [comment]
I selected the Swedish file for the subprojects but the project was set to English.
However, setting source language to Swedish for the project did not remove the warnings.

**Comment by nijel** [comment]
Changing the language will not remove them automatically, the checks are not fired again.

You can fire the checks by `./manage.py updatechecks project/component`.

**Comment by magnuskenneth** [comment]
I tried running `./manage.py updatechecks project/component` on both project/component and just project. It completed but the warnings are still there.

**Comment by nijel** [comment]
Can you please share both project and component configuration?

**Comment by magnuskenneth** [comment]
These are the settings I have set a value for. If it is a checkbox it means it is checked.

**Project**
- Project name
- URL slug
- Project website
- Set Translatoin-Team header
- Enable hooks
- Source language (Swedish)


**Component**
- Component name
- URL slug
- Project
- Version contrit system (Git)
- Source code repository
- Repository push URL
- Repository branch
- File mask
- Monolingual base language file
- Edit base file
- File format (OS X Strings (UTF-8)
- Allow translation propagation
- Save translation history
- Enable suggestions
- Autoaccept translations (0)
- Quality check flags: ignore-end-question,ignore-end-exclamation,ignore-end-colon,ignore-end-stop
- New translation (use contact form)
- Merge style (Merge)
- Commit message when translating
- Commit message when adding translation
- Commit message when removing translation
- Committer name
- Committer email
- Language filter
- Priority

**Comment by nijel** [comment]
What are values for file masks? (File mask, Monolingual base language file)

**Comment by magnuskenneth** [comment]
**File mask:**
`Configurations/Languages/*.lproj/Localizable.strings`

**Monolingual base language file:**
`Configurations/Languages/sv.lproj/Localizable.strings`

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. There is really no need to execute translation checks on translation templates at all.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by magnuskenneth** [comment]
Thank you! :)
