### ISSUE TITLE
404/403 errors with screenshot context feature

### ISSUE THREAD

**Issue by stefk** [WeblateOrg/weblate#1402]
Hi,

I have two related issues regarding screenshots. I'm not sure if it's a bug or a configuration problem or both, but the behaviour I'm experencing is quite problematic.

### Steps to reproduce

1. Upload a screenshot in the *source strings / review* page (through *Screenshot context*)
2. Click on save

### Actual behaviour

The file is uploaded and seems to be correctly associated with the source string, however no caption is available (404 error on the image) and any attempt to remove the screenshot or even modify the source string ends up with a 403 error related to CSRF protection:

![](https://files.gitter.im/claroline/Translation/RNqE/error-403.png)

### Expected behaviour

The uploaded screenshot is visible and other source strings features are still available.

### Server configuration

```
Postgres is up
 * Weblate 2.11
 * Python 2.7.9
 * Django 1.10.5
 * six 1.10.0
 * social-auth-core 1.1.0
 * social-auth-app-django 1.0.1
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.2
 * lxml 3.4.0
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.4
 * pytz 2016.10
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 3.9.1
 * hub 2.2.9
 * Database backends: django.db.backends.postgresql_psycopg2
```

**Comment by nijel** [comment]
Screenshot management has been completely rewritten for 2.12, so most likely this got fixed on the way as wel...

**Comment by nijel** [comment]
However the not found error on screenshot is caused by bug in our Docker container (are you using that right?). I've just fixed it (and will tag it stable after tests complete).

**Comment by stefk** [comment]
Ok, thanks. I will upgrade ASAP and report back (I was waiting for the 2.12 tag also regarding a previous issue).

**Comment by stefk** [comment]
:+1: Both errors are gone after the upgrade.Thanks a lot!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
