### ISSUE TITLE
Git error on creating a component

### ISSUE THREAD

**Issue by yeriomin** [WeblateOrg/weblate#1404]
### Steps to reproduce
1. On a free OpenShift (not nextgen) account create a weblate host with the following command:
`rhc -aweblate app create -t python-2.7 --from-code https://github.com/WeblateOrg/weblate.git`
2. Get the login credentials with
`rhc -aweblate ssh credentials`
3. Log in and create a project with a random name.
4. Try to create a component for this project. Fill in all the required fields and input any github repo (tried `git://github.com/nijel/weblate-web.git` too) into the "Source code repository:" field.

### Actual behaviour
Component is not created, the following notice is shown:
At the top of the form: `Please correct the errors below.`
Near the "Source code repository:" field: `Failed to update repository: fatal: There is no merge to abort (MERGE_HEAD missing). (128)`

### Expected behaviour
A component should be created.

### Server configuration
 * Weblate 2.13-dev
 * Python 2.7.8
 * Django 1.10.6
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 1.8.2.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.4.4
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.2
 * pytz 2016.10
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.1.1
 * Database backends: django.db.backends.sqlite3

Log:

    [Sat Mar 11 00:36:16 2017] [error] INFO aaaa/bbb: updating repository
    [Sat Mar 11 00:36:19 2017] [error] INFO aaaa/bbb: update took 2.97 seconds:
    [Sat Mar 11 00:36:19 2017] [error] ERROR aaaa/bbb: failed merge on repo: fatal: ambiguous argument '@': unknown revision or path not in the working tree.
    [Sat Mar 11 00:36:19 2017] [error] Use '--' to separate paths from revisions, like this:
    [Sat Mar 11 00:36:19 2017] [error] 'git <command> [<revision>...] -- [<file>...]' (128)
    [Sat Mar 11 00:36:19 2017] [error] INFO sending notification merge_failure on aaaa/bbb to ADMINS

This is quite similar to #1299, but it happens on a clean installation. Anyone is free to try it [here](http://weblate-yeriomin.rhcloud.com/admin/trans/subproject/add/). The admin password is 1xijOXJ0u4tNQ.

Am I missing something obvious?

**Comment by nijel** [comment]
This seem to happen with certain git versions. I probably should install it and give it try...

**Comment by nijel** [comment]
The good thing is that I'm able to reproduce the issue with this git version. Let's see if I can fix it as well :-).

**Comment by nijel** [comment]
The root cause being Git does not understand `@` revision:

```
fatal: ambiguous argument '@': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
