### ISSUE TITLE
Missing translation update when updating weblate

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#1406]
### Steps to reproduce
1. we migrated from 2.8 to 2.12 and followed step-by-step
2. go in your instance

### Actual behaviour
Content is not fully translated french

### Expected behaviour
As I translated it upstream, I expect it to be 100%: https://hosted.weblate.org/languages/fr/weblate/

### Solution
We used .mo files from https://dl.cihar.com/weblate/Weblate-2.12.tar.xz
We think that either the mo files should be included in git either the migrate script should build .mo files for each languages.

### Server configuration
 * Weblate weblate-2.12
 * Python 2.7.3
 * Django 1.10.1
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0b5
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 1.7.10.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.6.4
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.4.6
 * pyuca N/A
 * pyLibravatar N/A
 * hub 2.2.2
 * Database backends: django.db.backends.postgresql_psycopg2

thanks for your help

**Comment by nijel** [comment]
The mo files are there:

```
$ tar tvJf ../Weblate-2.12.tar.xz  | grep locale/fr
drwxr-xr-x root/root         0 2017-03-03 11:18 Weblate-2.12/weblate/locale/fr/
drwxr-xr-x root/root         0 2017-03-03 11:18 Weblate-2.12/weblate/locale/fr/LC_MESSAGES/
-rw-r--r-- root/root      8233 2017-03-02 15:43 Weblate-2.12/weblate/locale/fr/LC_MESSAGES/djangojs.po
-rw-r--r-- root/root    140356 2017-03-03 11:18 Weblate-2.12/weblate/locale/fr/LC_MESSAGES/django.mo
-rw-r--r-- root/root    245048 2017-03-02 15:43 Weblate-2.12/weblate/locale/fr/LC_MESSAGES/django.po
-rw-r--r-- root/root      4097 2017-03-03 11:18 Weblate-2.12/weblate/locale/fr/LC_MESSAGES/djangojs.mo
```

What is your settings for LOCALE_PATHS?

**Comment by nijel** [comment]
And actually all of them are fully translated:

```
$ pocount Weblate-2.12/weblate/locale/fr/LC_MESSAGES/*
Processing file : Weblate-2.12/weblate/locale/fr/LC_MESSAGES/djangojs.mo
Type               Strings      Words (source)    Words (translation)
Translated:      62 (100%)        108 (100%)             113
Fuzzy:            0 (  0%)          0 (  0%)             n/a
Untranslated:     0 (  0%)          0 (  0%)             n/a
Total:           62               108                    113

Unreviewed:      62 (100%)        108 (100%)             113

Processing file : Weblate-2.12/weblate/locale/fr/LC_MESSAGES/djangojs.po
Type               Strings      Words (source)    Words (translation)
Translated:      62 (100%)        108 (100%)             113
Fuzzy:            0 (  0%)          0 (  0%)             n/a
Untranslated:     0 (  0%)          0 (  0%)             n/a
Total:           62               108                    113

Unreviewed:      62 (100%)        108 (100%)             113

Processing file : Weblate-2.12/weblate/locale/fr/LC_MESSAGES/django.mo
Type               Strings      Words (source)    Words (translation)
Translated:    1496 (100%)       6823 (100%)            8245
Fuzzy:            0 (  0%)          0 (  0%)             n/a
Untranslated:     0 (  0%)          0 (  0%)             n/a
Total:         1496              6823                   8245

Unreviewed:    1496 (100%)       6823 (100%)            8245

Processing file : Weblate-2.12/weblate/locale/fr/LC_MESSAGES/django.po
Type               Strings      Words (source)    Words (translation)
Translated:    1496 (100%)       6823 (100%)            8245
Fuzzy:            0 (  0%)          0 (  0%)             n/a
Untranslated:     0 (  0%)          0 (  0%)             n/a
Total:         1496              6823                   8245

Unreviewed:    1496 (100%)       6823 (100%)            8245

Processing file : TOTAL:
Type               Strings      Words (source)    Words (translation)
Translated:    3116 (100%)      13862 (100%)           16716
Fuzzy:            0 (  0%)          0 (  0%)             n/a
Untranslated:     0 (  0%)          0 (  0%)             n/a
Total:         3116             13862                  16716

File count:       4
```

**Comment by nijel** [comment]
Ah, sorry, I misread your question.

Anyway this is [documented]}(https://docs.weblate.org/en/latest/admin/install.html#filling-up-the-database):

![page-shot-2017-3-14 installation instructions weblate 2 13 documentation](https://cloud.githubusercontent.com/assets/212189/23888578/028676d6-0889-11e7-9443-e3ae230b7f15.png)

Thou probably not on the best place.

**Comment by Jibec** [comment]
great, this is what we were looking for!

I suggest either to include it in migration script, either to add an explicit note in https://docs.weblate.org/en/latest/admin/upgrade.html so it makes it easier to find :)

**Comment by nijel** [comment]
Doing that in migration would be tricky, I'd rather avoid that.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
