### ISSUE TITLE
'ascii' codec can't encode character u'\u0103' in position 17: ordinal not in range(128)

### ISSUE THREAD

**Issue by michaelarlt** [WeblateOrg/weblate#1408]
### Steps to reproduce
1. login into weblate
2. save `Interval de alertă (min): %s` into any string

### Actual behaviour
Server Error
The server had serious problems while serving your request
Im getting the following inside an errormail:

Internal Server Error: /translate/ienbot/language/ro/

UnicodeEncodeError at /translate/ienbot/language/ro/
'ascii' codec can't encode character u'\u0103' in position 17: ordinal not in range(128)

Request Method: POST
Request URL: http://_servername.tld_/translate/_projectname_/language/ro/?sid=5573eebe-0979-11e7-a90b-f74dfcf760e7&offset=2
Django Version: 1.10.6
Python Executable: /usr/bin/python
Python Version: 2.7.6
Python Path: ['/opt/weblate', '/usr/local/lib/python2.7/dist-packages/Weblate-2.12-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/django_appconf-1.0.2-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/defusedxml-0.5.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/django_compressor-2.1.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/oauthlib-2.0.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/django_crispy_forms-1.6.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/python_dateutil-2.6.0-py2.7.egg', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
Server time: Wed, 15 Mar 2017 13:18:27 +0100
Installed Applications:
(u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.sessions',
 u'django.contrib.sites',
 u'django.contrib.messages',
 u'django.contrib.staticfiles',
 u'django.contrib.admin',
 u'django.contrib.admindocs',
 u'django.contrib.sitemaps',
 u'social_django',
 u'crispy_forms',
 u'compressor',
 u'rest_framework',
 u'rest_framework.authtoken',
 u'weblate.trans',
 u'weblate.lang',
 u'weblate.screenshots',
 u'weblate.accounts',
 u'weblate.utils',
 u'weblate')
Installed Middleware:
(u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.locale.LocaleMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'weblate.accounts.middleware.AuthenticationMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'django.middleware.clickjacking.XFrameOptionsMiddleware',
 u'social_django.middleware.SocialAuthExceptionMiddleware',
 u'weblate.accounts.middleware.RequireLoginMiddleware')

### Expected behaviour
should be fine by unicode

### Server configuration
`mysql --version`
mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper
Type of weblate DB Tables: InnoDB
Collation of Weblate DB and its Tables: utf8mb4_general_ci

`./manage.py list_versions`
 * Weblate weblate-2.12-64-g4602f5c
 * Python 2.7.6
 * Django 1.10.6
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.3
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.2
 * pytz 2016.10
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.1.1
 * Database backends: django.db.backends.mysql

also installed by pip2.7 the package PyMySQL-0.7.10

`dpkg -l | grep python2 |awk '{print $2}'`
libpython2.7:amd64
libpython2.7-dev:amd64
libpython2.7-minimal:amd64
libpython2.7-stdlib:amd64
python2.7
python2.7-dev
python2.7-minimal

`dpkg -l | grep pip |awk '{print $2}'`
libpipeline1:amd64
python-pip
python-pip-whl
python3-pip

- OS Version                = "Ubuntu 14.04.3 LTS"
- Platform Data             = 3.13.0-042stab111.12 x86_64 x86_64 GNU/Linux

`locale`
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

using latest git version of Weblate 2.13-dev

**Comment by nijel** [comment]
Can you please include traceback as well?
