### ISSUE TITLE
Source strings messed up for Tilix project

### ISSUE THREAD

**Issue by phw** [WeblateOrg/weblate#1409]
For Tilix (former Terminix) on hosted weblate the source POT seems to have been incompletely imported.

### Steps to reproduce
1. Search for source string "Tilix version" (https://hosted.weblate.org/search/tilix/?q=Tilix+version&search=substring&source=on&target=on&type=all&ignored=False)
2. Click on one of the translations, e.g. https://hosted.weblate.org/translate/tilix/translations/ja/?checksum=9b2d67b134435511
3. Click on source information / edit source string settings

### Actual behaviour
A "No matching source strings found!" message is displayed. Indeed the source string search for "Tilix version" should show all languages, but for some reason it is only available for Italian and Japanese. But the search for "Terminix version" (which is not in the POT file anymore) does give results for all other version, and this source string is editable.

### Expected behaviour
There is no "Terminix version" source string, and only "Tilix version" for all strings.

This affects other source strings, too. Indeed the German translation does seem to have gotten none of the recent POT file changes. Looks like updating / merging the translation file changes went wrong.

### Server configuration
Hosted weblate. Repository maintanance claims to be up to date (commit  199fbef as I am writing, which matches upstream commit).

**Comment by nijel** [comment]
Sorry, I've messed it up when renaming. Fixing that right now.

**Comment by phw** [comment]
Thanks a lot, looking good now :)
