### ISSUE TITLE
Duplicate translations from XLIFF are not applied to RESX based translations

### ISSUE THREAD

**Issue by Amiller-philips** [WeblateOrg/weblate#1410]
### Steps to reproduce
Here is just one example, Our translator reported 2 cases of this error after a small test, I can see more candidates in the same components.

1. The application has a .resx file which has  fragments like the following: 
Near the top of the .resx file
```
  <data name="Common_Save_Button" xml:space="preserve">
    <value>Save</value>
  </data>
  <data name="Common_Cancel_Button" xml:space="preserve">
    <value>Cancel</value>
  </data>
```
Further down
```
  <data name="Action_Save" xml:space="preserve">
          <value>Save</value>
  </data>
  <data name="Action_Cancel" xml:space="preserve">
          <value>Cancel</value>
  </data>
```
i.e. Several resources with the same value, (and likely the same translation) but different names.

The git repo, containing this source , and the other translatable .lang.resx files is imported as a component in weblate. 
2. The professional translator downloads an XLIFF to translate into German, and perfoms translations, including a translation of Cancel, but not of Save. The traslation is uploaded to Weblate.
3. Inspection of the XLIFF file uploaded shows that MemoQ has indeed translated Cancel correctly twice

### Actual behaviour
The translation for Cancel is neither visible in the WebUI, nor in a new XLIFF that is downloaded after the translation. Both locations where Cancel is present are still untranslated.  The same behaviour was noted for Save in a retest. It seems that either weblate or the underlying translation library is not coping with 2 Texts in the .resx files having the same Source, and therefore the same Translation even though the Resorce names are differen.

### Expected behaviour
The translation should be visible at both locations in the WebUI and remain translated in the XLIFF

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

 * Weblate 2.12
 * Python 2.7.12
 * Django 1.10.6
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.5.0
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.4
 * pytz 2016.10
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 3.7.3
 * git-svn 2.7.4
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Just to make it clear (as the related code has been completely rewritten for 2.12): Did the upload already happen with 2.12?

Also can you please show the snippet from XLIFF with the translation?

**Comment by Amiller-philips** [comment]
Upload and Download were both with 2.12

Here are the corresponding XLIFF snippets, with more context and Cancel translated to Abbrechen,
Save has still not been translated for this XLIFF file.

  ```
    <trans-unit xml:space="preserve">
        <source>Uploaded Photos</source>
        <target></target>
      </trans-unit>
      <trans-unit xml:space="preserve">
        <source>Save</source>
        <target></target>
      </trans-unit>
      <trans-unit xml:space="preserve">
        <source>Cancel</source>
        <target>Abbrechen</target>
      </trans-unit>
      <trans-unit xml:space="preserve">
        <source>Properties</source>
        <target>Eigenschaften</target>
      </trans-unit>
```
and
```
      <trans-unit xml:space="preserve">
        <source>Pull to refresh...</source>
        <target></target>
      </trans-unit>
      <trans-unit xml:space="preserve">
        <source>Save</source>
        <target></target>
      </trans-unit>
      <trans-unit xml:space="preserve">
        <source>Cancel</source>
        <target>Abbrechen</target>
      </trans-unit>
      <trans-unit xml:space="preserve">
        <source>Comment by</source>
        <target>Kommentar von:</target>
      </trans-unit>
```
Thankyou for your quick response!

**Comment by nijel** [comment]
The problem is that the XLIFF snippets you've posted don't mark the strings as translated (it lacks `approved="yes"` attribute). By default Weblate doesn't import strings marked for review. This can be changed while importing, just select *Import as translated* under *Processing of strings needing review*.

See also https://docs.weblate.org/en/latest/formats.html#xliff

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by Amiller-philips** [comment]
If I understand the fix correctly, the following should hold.

if the xlif file contains translation units which are duplicated and not tagged with 'approved="yes"', then the setting of the skip-review-flag in the component is needed toggether with the usage of selecting "import as translated" for "processing of strings needing review" in the upload dialog.  The upload process should then find the duplicates as normal traslations and incorporate them into the translations database correctly.

To test, an xlif containing the 2 duplicates from the original report above and two other unique translations was constructed and uploaded. The 2 uniqe translations were found and handled correctly, the duplicates were "not found"
ie Skipped 0, Not found 4, Found 2, rather than 0,0,6

I then took the liberty of setting approved=yes in the translation unit and trying again. This made no difference. 

adding state="translated" to the target also made no difference.

Interestingly converting xlif to po and back using the xliff2po and po2xliff tools causes the duplicates to dissapear in the resulting xliff. Uploading that xlif also does not result in the duplicates being found, 

I **guess** that the weblate xlif ingestion might be parsing the xlif with the required level of laxity, but something further down the stack is still being strict.

Here are the versions installed

`weblate@ip-172-31-14-176:/app/data/vcs/testweblate$ weblate list_versions
 * Weblate 2.13
 * Python 2.7.12
 * Django 1.11
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.1.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.5.0
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.4
 * pytz 2017.2
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 3.7.3
 * Database backends: django.db.backends.postgresql_psycopg2
weblate@ip-172-31-14-176:/app/data/vcs/testweblate$`
