### ISSUE TITLE
Bitbucket hook crash on Pull Request merge

### ISSUE THREAD

**Issue by Belphemur** [WeblateOrg/weblate#1411]
### Steps to reproduce
1. Have an open pull request on a repository linked to weblate. Doesn't need to target the branch weblate follow.
2. Merge the pull request in the bitbucket interface
3. Enjoy the Crash mail

### Actual behaviour
Weblate can't process the hook and crash saying it can get the name of the branch:

[crash_log.txt](https://github.com/WeblateOrg/weblate/files/847775/crash_log.txt)

```
File "/var/lib/weblate/weblate/weblate/trans/views/api.py" in vcs_service_hook
  166.         service_data = hook_helper(data)

File "/var/lib/weblate/weblate/weblate/trans/views/api.py" in bitbucket_hook_helper
  241.         return bitbucket_webhook_helper(data)

File "/var/lib/weblate/weblate/weblate/trans/views/api.py" in bitbucket_webhook_helper
  231.         'branch': data['push']['changes'][-1]['new']['name']
```

### Expected behaviour
Should recognize the branch

### Server configuration
```
 * Weblate weblate-2.12-44-g2e2e826
 * Python 2.7.12
 * Django 1.10.6
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.3
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.2
 * pytz 2016.10
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 3.7.3
 * Database backends: django.db.backends.postgresql_psycopg2
```

**Comment by nijel** [comment]
Can you please provide the payload that bitbucket has delivered? It can be obtained from the Bitbucket webhook administration.

According to [their docs](https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-Push) the changes attribute should be there and filled in on all push events, but apparently it's missing here.

**Comment by Belphemur** [comment]
Here is the full payload
[payload.json.txt](https://github.com/WeblateOrg/weblate/files/847998/payload.json.txt)

The change is present, but no *new* key into it.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
