### ISSUE TITLE
Incorrect progress for languages with missing components

### ISSUE THREAD

**Issue by rob006** [WeblateOrg/weblate#1413]
### Steps to reproduce
1. Create  two components: A and B.
2. Add two translations (en and pl) for component A and one (en) to component B.
3. Translate everything.

### Actual behaviour
Language pl shows 50% in translation progress even if everything is translated and project progress is 100%.

### Expected behaviour
pl language should have 100%, because there is nothing more to translate. I don't need translate all components to all languages.

### Server configuration

```
 * Weblate weblate-2.12
 * Python 2.7.12
 * Django 1.10.6
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.3
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.4
 * pytz 2016.10
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.1.3
 * Mercurial 3.7.3
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
It was intentionally implemented this way. I'm not sure which way is better as people will have different expectations here (also see https://github.com/WeblateOrg/weblate/issues/1298).

**Comment by rob006** [comment]
Current implementation looks really inconsistent to me. You could have project translated in 100%, but specific language could show only 50% progress. So basically you have fully translated project with missing translations and without the ability to complete them. 

If someone wants to count non-existent component in language statistics, he could always just add it (or we could add option to do it automatically). But there is no easy workaround in opposite case - to fix my stats I need add unused translations and force people to create useless translations.

**Comment by rob006** [comment]
My temporary patch to fix this:

```diff
diff --git a/weblate/trans/stats.py b/weblate/trans/stats.py
index b7ba2bd..3660b90 100644
--- a/weblate/trans/stats.py
+++ b/weblate/trans/stats.py
@@ -41,8 +41,8 @@ def get_per_language_stats(project):
     }
 
     # Calculates total strings in project
-    total = project.get_total()
-    total_words = project.get_source_words()
+    #total = project.get_total()
+    #total_words = project.get_source_words()
 
     # Translated strings in language
     data = Translation.objects.filter(
@@ -53,11 +53,15 @@ def get_per_language_stats(project):
     ).annotate(
         Sum('translated'),
         Sum('translated_words'),
+        Sum('total'),
+        Sum('total_words'),
     ).order_by()
     for item in data:
         language = languages[item['language']]
         translated = item['translated__sum']
         translated_words = item['translated_words__sum']
+        total = item['total__sum']
+        total_words = item['total_words__sum']
 
         # Insert sort
         pos = None
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
