### ISSUE TITLE
`manage.py loaddata` fails on post_save receivers

### ISSUE THREAD

**Issue by matejcik** [WeblateOrg/weblate#1414]
When importing data to a new database through the `manage.py dumpdata` -- `manage.py loaddata` cycle, things fail because `post_save` receivers are refering to records that don't exist in the database yet.

django doc:

> When fixture files are processed, the data is saved to the database as is. Model defined `save()` methods are not called, and any `pre_save` or `post_save` signals will be called with __`raw=True`__ since the instance only contains attributes that are local to the model. You may, for example, want to disable handlers that access related fields that aren’t present during fixture loading and would otherwise raise an exception:

The `post_save` receivers in Weblate don't respect this. Using the example `@disable_for_loaddata` decorator from the [Django doc](https://docs.djangoproject.com/en/1.10/ref/django-admin/#what-s-a-fixture) seems to fix the problem.

(tangentially related, when using multiple database configurations and specifying `loaddata --database=something`, `auto_assign_group` still somehow manages to query the default database for groups, which then fails to create the proper foreign key relationship :) No idea how this happens, but properly blocking the `create_profile_callback` receiver prevents this problem too.)

**Comment by nijel** [comment]
Indeed firing the signal handlers for fixtures does not make much sense.

As for the database connection problem, I've never played with that, but I'd expect signal handlers to automatically use same database as callers...
