### ISSUE TITLE
DataError at /admin/trans/subproject/add/

### ISSUE THREAD

**Issue by lawmaestro** [WeblateOrg/weblate#1421]
When trying to add a new component to an existing project I get the following error:

DataError at /admin/trans/subproject/add/
value too long for type character varying(20)

I've tried different source formats; po, xlif and the result is the same.

The log is as follows:

value too long for type character varying(20)
Request Method:	POST
Request URL:	http://weblate.mycompany.global.corp:8000/admin/trans/subproject/add/
Django Version:	1.10.5
Exception Type:	DataError
Exception Value:	
value too long for type character varying(20)
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py in execute, line 64
Python Executable:	/usr/bin/python
Python Version:	2.7.12
Python Path:	
['/home/ubuntu/Weblate-2.12',
 '/usr/local/lib/python2.7/dist-packages/Weblate-2.10-py2.7.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/home/ubuntu/.local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
Server time:	Wed, 22 Mar 2017 08:35:21 +0000
Traceback Switch to copy-and-paste view

/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py in inner
            response = get_response(request) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in _legacy_get_response
            response = self._get_response(request) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in _get_response
                response = self.process_exception_by_middleware(e, request) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py in wrapper
                return self.admin_site.admin_view(view)(*args, **kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py in _wrapped_view
                    response = view_func(request, *args, **kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py in _wrapped_view_func
        response = view_func(request, *args, **kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py in inner
            return view(request, *args, **kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py in add_view
        return self.changeform_view(request, None, form_url, extra_context) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py in _wrapper
            return bound_func(*args, **kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py in _wrapped_view
                    response = view_func(request, *args, **kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py in bound_func
                return func.__get__(self, type(self))(*args2, **kwargs2) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py in inner
                    return func(*args, **kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py in changeform_view
                self.save_model(request, new_object, form, not add) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py in save_model
        obj.save() ...
▶ Local vars
/home/ubuntu/Weblate-2.12/weblate/trans/models/subproject.py in save
            self.create_translations() ...
▶ Local vars
/home/ubuntu/Weblate-2.12/weblate/trans/models/subproject.py in create_translations
                    self, lang, code, path, force, request=request ...
▶ Local vars
/home/ubuntu/Weblate-2.12/weblate/trans/models/translation.py in check_sync
        translation.check_sync(force, request=request) ...
▶ Local vars
/home/ubuntu/Weblate-2.12/weblate/trans/models/translation.py in check_sync
                self, unit, pos ...
▶ Local vars
/home/ubuntu/Weblate-2.12/weblate/trans/models/unit.py in update_from_unit
        dbunit.update_from_unit(unit, pos, created) ...
▶ Local vars
/home/ubuntu/Weblate-2.12/weblate/trans/models/unit.py in update_from_unit
            same_state=same_state ...
▶ Local vars
/home/ubuntu/Weblate-2.12/weblate/trans/models/unit.py in save
            self.run_checks(same_state, same_content, force_insert) ...
▶ Local vars
/home/ubuntu/Weblate-2.12/weblate/trans/models/unit.py in run_checks
                        for_unit=self.pk ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py in manager_method
                return getattr(self.get_queryset(), name)(*args, **kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/query.py in create
        obj.save(force_insert=True, using=self.db) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/base.py in save
                       force_update=force_update, update_fields=update_fields) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/base.py in save_base
            updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/base.py in _save_table
            result = self._do_insert(cls._base_manager, using, fields, update_pk, raw) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/base.py in _do_insert
                               using=using, raw=raw) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py in manager_method
                return getattr(self.get_queryset(), name)(*args, **kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/query.py in _insert
        return query.get_compiler(using=using).execute_sql(return_id) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py in execute_sql
                cursor.execute(sql, params) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py in execute
            return super(CursorDebugWrapper, self).execute(sql, params) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py in execute
                return self.cursor.execute(sql, params) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/utils.py in __exit__
                six.reraise(dj_exc_type, dj_exc_value, traceback) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py in execute
                return self.cursor.execute(sql, params) ...
▶ Local vars

Does anyone have any ideas? Thanks

**Comment by lawmaestro** [comment]
I've just tried saving the component again having created a new project and the result is still the same

**Comment by nijel** [comment]
Most likely the language code is too long. What is your filemask and what files does it match?

**Comment by lawmaestro** [comment]
The file mask is: .projectDocs/response-locales/plural-*.po

**Comment by lawmaestro** [comment]
I've just edited the subproject.py and added your hotfix. I then restarted weblate along with postgres but I'm still seeing the error. Looking at the fix I'd guessed that would be the case but I thought the output might now indicate that it's something to do with the file mask, is that not the case?

**Comment by nijel** [comment]
What files does it match? Also do you have some customization of Weblate setup?

**Comment by lawmaestro** [comment]
Currently, that just matches the file: "plural-en-GB.po"

I have a custom check which is a check to enforce source and translation are the same. I'm using this for certain strings I want to enforce are NOT translated. Nothing else custom in the setup I can think of. Do I need to run migrate or anything after making edits to core python files?

**Comment by nijel** [comment]
Ah okay, then it is probably by the check, there is currently 20 chars limit on check name...

**Comment by lawmaestro** [comment]
Oh, I see! The class is called "EnforceDifferentCheck" and the check_id is "enforce-different-check". I'm assuming it's the check_id which has the limit?

**Comment by nijel** [comment]
Yes, this certainly needs documentation.

**Comment by lawmaestro** [comment]
I've reduced both to under 20 chars and that has indeed fixed the problem. Thanks so much!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by lawmaestro** [comment]
I've just donated a small token of my appreciation. Thanks again Nijel :)
