### ISSUE TITLE
Broken links to Chineze translation

### ISSUE THREAD

**Issue by annasoloviova** [WeblateOrg/weblate#1422]
### Steps to reproduce
1. Visit https://hosted.weblate.org/projects/osmand/main/ and click 'Chinese (zh_RCN)' or 'Chinese (zh_RTW)'.

### Actual behaviour
'Page Not Found'

### Expected behaviour
The actual broken links are: 
            https://hosted.weblate.org/projects/osmand/main/zh_Hant/
            https://hosted.weblate.org/projects/osmand/main/zh_Hans/

**Comment by nijel** [comment]
Fixed, thanks for spotting.

**Comment by annasoloviova** [comment]
Thanks!
