### ISSUE TITLE
Adding a glossary entry in the translation page erases unsaved translations

### ISSUE THREAD

**Issue by waldyrious** [WeblateOrg/weblate#1427]
### Steps to reproduce
1. Go to the translation page
2. Enter some text in the translation box
2. Use the glossary form on the right to add a new term

### Actual behaviour
The text that had been entered disappears

### Expected behaviour
The translation should remain in the text box

### Server configuration
N/A (using a hosted instance, at https://l10n.elementary.io)

**Comment by nijel** [comment]
Indeed it does, the dictionary management really should use AJAX here.
