### ISSUE TITLE
Undetected same string content in json file

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#1429]
### Steps to reproduce
We have json file with two strings having the same english content.

### Actual behaviour
Weblate don't suggest "Other translation", nor suggest "Automated translation"
You can search "Is it a public SPIP site ?" on https://translate.yunohost.org/translate/yunohost/apps/ or follow those links:
https://translate.yunohost.org/translate/yunohost/apps/fr/?sid=92212658-1976-11e7-a839-00224da69287&offset=1#machine
https://translate.yunohost.org/translate/yunohost/apps/fr/?sid=a9d44c6c-1976-11e7-a010-00224da69287&offset=2

### Expected behaviour
I assume there should be three answer.

1. Automatically complete the translation (same behaviour than same string in multiple component)
2. Suggest the current translation in "Other translation"
3. Suggest the current translation in "Automatic translation"

### Server configuration
I can't get this information from administration panel and don't have more accesses on the server.

Please note we can't fix this error by preventing the duplicate source string because we merge content from multiple sources to have only one component in Weblate (then we split it again).

thanks for this great software and your help!

**Comment by nijel** [comment]
Only strings with same ID are matched in this way. The reason is that different ID is usually used in different scope and can lead to different translation...

**Comment by Jibec** [comment]
Le 5 avril 2017 08:15:07 UTC+02:00, "Michal Čihař" <notifications@github.com> a écrit :
>Only strings with same ID are matched in this way. The reason is that
>different ID is usually used in different scope and can lead to
>different translation...

OK, that makes sense and may exclude automatic replacement. I indeed remember to ask for such duplicates in a project, while it is hard to tell what proportion of language benefits such feature.

Is the lack of suggestions a bug to you too?
-- 
Jean-Baptiste Holcroft

**Comment by nijel** [comment]
I'm not really sure. So far I was assuming that if there are different IDs for same string, it's on purpose, so people actually expect those to be translated differently.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
