### ISSUE TITLE
Quality checks compare wrong things?

### ISSUE THREAD

**Issue by Frexuz** [WeblateOrg/weblate#1436]
### Steps to reproduce
1. Adding Ruby YAML files via a Github component
2. Select english as secondary language 
3. Select a language (other than english) and translate any string

### Actual behaviour
The "source" shows the YAML key, rather than its value. This mismatch would trigger failing checks, like "trailing full stop". See screenshot.

`%{sign_up_link} oder %{log_in_link}, um deinen eigenen anzusehen.`
is compared to
`calendar / show / signup_login_html`

### Expected behaviour

`%{sign_up_link} oder %{log_in_link}, um deinen eigenen anzusehen.`
should be compared with
`%{sign_up_link} or %{log_in_link} to view your own.`

![image](https://cloud.githubusercontent.com/assets/49692/24858786/f8c36312-1e17-11e7-82b9-71744e6ecc1a.png)

**Comment by nijel** [comment]
You should set your translation as monolingual, it indeed can't work as expected if you have monolingual translation set up as bilingual, see https://docs.weblate.org/en/latest/admin/projects.html#monolingual-components

**Comment by Frexuz** [comment]
Works! Thanks for the quick solution :)
