### ISSUE TITLE
Add Trailing Semicolon Check

### ISSUE THREAD

**Issue by danrabbit** [WeblateOrg/weblate#1437]
This is incredibly useful for ensuring things like .desktop files remain valid after translation

**Comment by btkostner** [comment]
Going to drop this here for later: https://github.com/WeblateOrg/weblate/blob/master/weblate/trans/checks/chars.py#L284

**Comment by nijel** [comment]
Probably you can rather base on the newline check, the language variants probably won't be needed here: https://github.com/WeblateOrg/weblate/blob/master/weblate/trans/checks/chars.py#L45

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by danrabbit** [comment]
Thanks for addressing this so quickly!
