### ISSUE TITLE
Sometimes the interface is rendered in Belarusian language

### ISSUE THREAD

**Issue by marcperrin** [WeblateOrg/weblate#1438]
I don't really have steps to reproduce, but it happens to me from time to time: the interface language suddenly becomes Russian (at least something cyrillic!) (instead of English in my case), no idea why - F5 fixes back to English...
Will try to check whether the whole page is in Russian in that case, or if the rendering can be mixed...

**Comment by nijel** [comment]
Maybe some caching issue? I remember seeing this sometimes in the past, but I don't recall the reason.

**Comment by nijel** [comment]
Also might be caused by not properly setting the language and it stays set from other request. I'm not aware of any change in 2.13 which could lead to this, but still I can't be sure... Are you seeing this from logged in user? Does he have set language in the profile?

**Comment by marcperrin** [comment]
- it's Belarusian most probably, as it's on the top of the list of available interface languages... 
- not 2.13-related, I've seen it before in 2.12 for example. 
- yes, it happens for a logged in user, who has English as interface language
- someone also reported me seeing this language as the default proposed interface language for a new user... 
I'll try to have a closer look.

**Comment by nijel** [comment]
The default really should be based on browser preferences, so unless the browser reports Belarusian it should not be selected...

**Comment by marcperrin** [comment]
NB: just adding some screenshots, for reference (yes, it's crazy) (has anyone encountered that with other django applications??)

![image](https://cloud.githubusercontent.com/assets/20423991/25399038/5b3cb98a-29ee-11e7-948b-ca512df48065.png)

![image](https://cloud.githubusercontent.com/assets/20423991/25399057/6d572056-29ee-11e7-9f12-ade7f27a9940.png)

**Comment by nijel** [comment]
Can you try it with enabled LocaleMiddleware? I'm not sure if something is not relying on that. To have interface just in English, remove all other languages from LANGUAGES setting.

**Comment by marcperrin** [comment]
Will try, thanks!

**Comment by nijel** [comment]
Any luck with further testing?

**Comment by marcperrin** [comment]
I did what you suggested (in settings.py, I've reactivated LocaleMiddleware in MIDDLEWARE_CLASSES, but I've commented out all but English in LANGUAGES) and I don't have issues anymore, thanks!
