### ISSUE TITLE
403 vs. 404 for inaccessible vs. inexistent projects

### ISSUE THREAD

**Issue by marcperrin** [WeblateOrg/weblate#1439]
NB: kind of similar to #1317, but about projects rather than accounts.

### Steps to reproduce
Be logged in as user X who has access to projects A & B (and there are no other projects on the instance)

### Actual behaviour
In the /projects page, only A is listed; similarly, only A is listed as available to watch, etc. 
This is good.
But /projects/B yields a 403 page that quite explicitly says this project exists, while /projects/ZZZZ yields a 404 that quite explicitly says this project does not exist.

### Expected behaviour
I feel we're revealing too much information here.
I feel we should get a 404 in both cases, that does not explicitly tell whether the project exists or not. 
(just imagine Valve is using Weblate and translates Half-Life 3 on the same Weblate instance as Steam ;-)
Sure, that's why project codenames are used, but still...)

**Comment by marcperrin** [comment]
The 404 messages are still different in the two cases: "Access denied" vs. "No Project matches the given query".

They could both be replaced by a single, neutral message. 
(same thing at show_subproject level ("Access denied" vs. "No SubProject matches the given query"), show_translation level...)

Also, red messages "You are not allowed to access project X" seem to stack and get displayed if e.g. you go to a valid+allowed project after those 404 (which also gives you the project name behind your tentative project slug...)

**Comment by nijel** [comment]
13. dubna 2017 10:39:47 SELČ, marcperrin <notifications@github.com> napsal:
>The 404 messages are still different in the two cases: "Access denied"
>vs. "No Project matches the given query".
>
>They could both be replaced by a single, neutral message. 
>(same thing at show_subproject level ("Access denied" vs. "No
>SubProject matches the given query"), show_translation level...)
>
>Also, red messages "You are not allowed to access project X" seem to
>stack and get displayed if e.g. you go to a valid+allowed project after
>those 404 (which also gives you the project name behind your tentative
>project slug...)

The message should be shown only in the debug mode, that's anyway not suitable for production...

**Comment by marcperrin** [comment]
Yes sorry I've edited my comment by testing with Debug = False - cf. my prev comment
