### ISSUE TITLE
--verbose=0 flag of commit_pending appears to be non-functional

### ISSUE THREAD

**Issue by BhaaLseN** [WeblateOrg/weblate#1441]
### Steps to reproduce
1. Configure Cron-Job for `commit_pending` as mentioned in [the documentation](https://docs.weblate.org/en/latest/admin/install.html#running-maintenance-tasks). Note: I use `--age=0` and a Project configuration using "Push on commit" to avoid the potential for conflicts (because translate-toolkit is fairly noisy with ResX files)
2. Make some changes to actually have it do something
3. Wait until the Cron-Job triggers and `commit_pending` is run.

### Actual behaviour
The web server user receives a mail that contains a lot of `INFO` messages (like, committing, pushing etc.)
It appears `--verbose=0` is either ignored or does not work as I'd expect it. Also, redirecting stdout to `/dev/null` still sends the mail, so apparently this is all written to `stderr`.

### Expected behaviour
No mails should be generated, _unless_ errors happen (which I'd expect to be written to stderr).
Successful commits/pushes are nothing that I need to be notified of, this is only necessary when something goes wrong and a human needs to fix it.

### Server configuration
```
 * Weblate weblate-2.10
 * Python 2.7.9
 * Django 1.10.4
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 1.14.0-rc1
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.2
 * lxml 3.6.4
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.3
 * pyuca N/A
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
The output currently depends on logging configuration and not on the verbose flag, this should be fixed.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
