### ISSUE TITLE
view/anchor by context or location

### ISSUE THREAD

**Issue by lnussel** [WeblateOrg/weblate#1442]
In openSUSE we use weblate to also translate desktop files. There are hundreds of desktop files from different packages. We don't want to put each desktop file into a separate po file as that would clutter the weblate UI. So we put basically all desktop file translations in one big po file and add context resp location headers to allow splitting later again.
In order for package maintainers to check the translation state of their package it would be nice to have some view in weblate that only shows strings with a specific location or context. The search feature only works per language AFAICT so that's unsuitable for this purpose.

https://l10n.opensuse.org/projects/desktop-file-translations/

**Comment by nijel** [comment]
Search works in any context (project/component/project-language), but I'm not sure if that's suitable view for this purpose.
