### ISSUE TITLE
Error at logout from admin page

### ISSUE THREAD

**Issue by marcperrin** [WeblateOrg/weblate#1444]
From 2.13: seems that logging out from the admin part of the site yields an error - I don't think it used to happen in 2.12.

TypeError at /admin/logout/

int() argument must be a string or a number, not 'AnonymousUser'

**Comment by nijel** [comment]
Indeed, the Django standard logout action sets request.user to Django AnonymousUser, which is not database backed and the Project.objects.all_acl then fails.
