### ISSUE TITLE
2.13 & Project ACL / Group ACL

### ISSUE THREAD

**Issue by marcperrin** [WeblateOrg/weblate#1445]
With 2.13, the per-project permissions handling has changed (harmonized with Group ACL I guess) and thus looks... quite more complicated ;-)
 
I guess Group ACL could use some enhancements and maybe more doc.

My main two gripes:
- when adding a new group ACL I never know whether I must I select all permissions or can I just leave this box alone... (it's the former, I think)
- the possibilities to review an existent group ACL definition are slim: basically you have to delete / recreate...

**Comment by nijel** [comment]
You need to select permissions which you want to filter by the GroupACL, if you select no permissions, the GroupACL will have no effect.
