### ISSUE TITLE
Set a deadline per project

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#1448]
I've spent some time using Pontoon and the "Deadline" feature is very useful for platform/community management and information!

I would love to have something similar per project in Weblate!
Ideally, I think it should be in main dashboard and be available in history + rss feed so we can get notices.

**Comment by nijel** [comment]
Can you be please a bit more specific about this feature? What should the deadline control?

**Comment by Jibec** [comment]
I'm not sure it should "control" anything. It's just an information to tell translator when is the next deadline.

I think it should give the same information than when you write the "Call for translation": http://lists.cihar.com/pipermail/weblate/2017-May/000302.html
It only inform.

If you want to go deeper, it may send a message to contributors.

**Comment by yarons** [comment]
Pontoon implemented this feature for their products roadmap, this way you can make sure the translators will be more involved in the product because they'll now what is the version their work will appear in and maybe will even test it. 

This is the direct correlation between translation work and development.

**Comment by Jibec** [comment]
I just had a great example of this feature request (it's the [gephi](http://gephi.org) project):

![capture du 2017-08-23 06-56-58](https://user-images.githubusercontent.com/474883/29598231-4ba8c23a-87d0-11e7-8915-4ad5e1597d18.png)

**Comment by nijel** [comment]
There is something similar in Weblate now - the whiteboard messages can do announcements and also can disappear after some date, so that kind of does what you wanted.

**Comment by Jibec** [comment]
That's true, you're welcome to close this ticket, thank you for your work!
