### ISSUE TITLE
A more clear strtuctured requirements list

### ISSUE THREAD

**Issue by Fjolnir-Dvorak** [WeblateOrg/weblate#1449]
###Documentation

It would be kind to list the required software without the python requirements which are installable with pip. An Idea would be to group them in python-pip stuff like django and other stuff like python-dev or databases.

source: [https://docs.weblate.org/en/latest/admin/install.html#requirements](https://docs.weblate.org/en/latest/admin/install.html#requirements)

**Comment by nijel** [comment]
Can you please provide some example what would would you expect?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
