### ISSUE TITLE
broken requirements.txt

### ISSUE THREAD

**Issue by Fjolnir-Dvorak** [WeblateOrg/weblate#1451]
**requirements.txt** does not work with `$pip install -r requirements.txt`
tested by this project supported python versions:
- 3.4.6
- 3.6.1

Followed guide out of the documentation:
```
Requirements using pip installer
Most requirements can be also installed using pip installer:

pip install -r requirements.txt
```
[https://docs.weblate.org/en/latest/admin/install.html](https://docs.weblate.org/en/latest/admin/install.html)

Error:
```
Collecting Django>=1.10 (from -r requirements.txt (line 1))
  Using cached Django-1.11-py2.py3-none-any.whl
Collecting siphashc3 (from -r requirements.txt (line 2))
  Using cached siphashc3-3.tar.gz
Collecting Whoosh>=2.7.0 (from -r requirements.txt (line 3))
  Using cached Whoosh-2.7.4-py2.py3-none-any.whl
Collecting translate-toolkit>=2.0.0 (from -r requirements.txt (line 4))
  Could not find a version that satisfies the requirement translate-toolkit>=2.0.0 (from -r requirements.txt (line 4)) (from versions: 1.9.0)
No matching distribution found for translate-toolkit>=2.0.0 (from -r requirements.txt (line 4))
```

**Comment by Fjolnir-Dvorak** [comment]
`$pip install weblate` isn't working, too

**Comment by nijel** [comment]
It works just fine on 3.5.2:

https://travis-ci.org/WeblateOrg/weblate/jobs/222113911#L275

On what platform are you doing that?

**Comment by Fjolnir-Dvorak** [comment]
System: Linux (Ubuntu) on Windows 10
translate-toolkit is not installed via apt-get
setup using pew (virtual env with dedicated python binaries): 
1. $pip install pew
2. $pew install 3.4.6
3. $pew new weblate-3.4-6 --python$(pew locate_python 3.4.6)
4. $pip install -r requirements.txt

I am testing further what could be the issue with translate-toolkit

**Comment by Fjolnir-Dvorak** [comment]
I compiled python without having libbz2-dev installed, so bz2 in pip did not work.

**Comment by nijel** [comment]
I've reported this to https://github.com/translate/translate/issues/3612, maybe it's worth switching to gz as that's what most projects use...

**Comment by nijel** [comment]
BTW: Why not using Weblate natively on Windows? Adding emulation layer can bring additional troubles...

**Comment by Fjolnir-Dvorak** [comment]
I found a weird behaviour  with the glossary where multiple-words-long keys worked sometime and sometimes not. So I wanted to create an isolated test-environment to eliminate all potential requirement-version issues caused by other local python installations.
