### ISSUE TITLE
Google Machine Translation - update to latest API endpoint

### ISSUE THREAD

**Issue by tswast** [WeblateOrg/weblate#1453]
I see at the [Google Cloud Translation API docs](https://cloud.google.com/translate/docs/reference/rest) that the API endpoint is

    https://translation.googleapis.com/language/translate/v2

Whereas Weblate is [using www.googleapis.com](https://github.com/WeblateOrg/weblate/blob/78b3828094fc2ae6db0592ed29191012de3ab23a/weblate/trans/machine/google.py#L62).

You may wish to start using the [new Python client library for Translate](https://googlecloudplatform.github.io/google-cloud-python/stable/translate-usage.html) as well.

**Comment by tswast** [comment]
One reason for using the Python client libraries is that it will use Google Application Default credentials, which automatically authenticates code deployed on Google Compute Engine, for example.

**Comment by nijel** [comment]
I'm not sure if it's worth the additional dependency, but indeed it would be useful for running on GCE.
