### ISSUE TITLE
HTML source string starting with DOCTYPE does not trigger XML checks

### ISSUE THREAD

**Issue by andygoossens** [WeblateOrg/weblate#1454]
### Steps to reproduce
1. Have a source string that contains HTML content starting with a DOCTYPE declaration
2. Enter translation for that source string that contains broken XML/HTML
3. Save

### Actual behaviour
XMLValidityCheck did not detect the mistake

### Expected behaviour
The XML check should have noticed that the translation was invalid.

### Server configuration
 * Weblate weblate-2.10
 * Python 2.7.12+
 * Django 1.10.5
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 2.0.0rc2
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.9.3
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.2
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.3
 * pytz 2016.10
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.0.2
 * Database backends: django.db.backends.postgresql_psycopg2

### Personal analysis
Weblate first checks whether the source string is valid XML. If it isn't, it is not even going to try validating the translation. Checking whether something is valid XML is done by surrounding the text with `<weblate></weblate>` tags.

This fails when the text starts with a DOCTYPE declaration. The SyntaxError that gets thrown, says something like this:
```
XML declaration allowed only at the start of the document, line 1, column 15 (line 1)
```
As Weblate did not consider the source string XML, then it won't even check the translation for valid XML.

Suggestion: Improve the parse_xml method in the BaseXMLCheck class. Somehow detect the DOCTYPE and maybe... strip it, or don't surround it with `<weblate></weblate>`?

I assume there might be a similar issue when XML starts with
```
<?xml version="1.0" encoding="UTF-8"?>
```

**Comment by nijel** [comment]
Indeed the check is built on assumption that it will never get full XML, just portion of it.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
