### ISSUE TITLE
Provide recent changes method for sorting/filter changes [$25]

### ISSUE THREAD

**Issue by leonardo-lemos** [WeblateOrg/weblate#1455]
Weblate should provide sorting/filtering recent changes per change type.

**Comment by AzureByte** [comment]
I would like to have a go at this.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
