### ISSUE TITLE
Updating POT file in source repository doesn't show new strings in already translated languages.

### ISSUE THREAD

**Issue by pauldotknopf** [WeblateOrg/weblate#1456]
I currently have "English" 100% translated (po file).

While developing, I regenerate my POT file, and commit my change.

When going back to weblate, I expect to see English NOT have "100% translated", due to the new string.

I can't see a way to get weblate to support translating my new string in already translated languages.

**Comment by pauldotknopf** [comment]
Ok, I read the FAQ.

> **Why does Weblate still shows old translation strings when I’ve updated the template?**
> Weblate does not try to manipulate with the translation files in any other way than allowing translators to translate. So it also does not update the translatable files when the template or source code has been changed. You simply have to do this manually and push changes to the repository, Weblate will then pick up the changes automatically.

It mentions that developers should run ```msgmerge``` manually, or use ```POST_UPDATE_SCRIPTS```.

How do I use ```POST_UPDATES_SCRIPTS``` to perform this, automatically? I want my developers to only have to update the POT file, otherwise, human error may happen.

**Comment by gilbsgilbs** [comment]
Hi,
I'm also struggling on this, actually. I find a bit confusing that Weblate does not merge `.pot` keys in `.po` by default, as stated in the documentation. From my non-expert point of view, merge is expected 99.99% of the time. I did not find any precise example on how to do this in the documentation, although it seems to be a pretty common use-case. The documentation only states Weblate won't do the merge and if you want to automate it, you have to use post update script.

To declare post update scripts, you must:
- [write a shell script](https://docs.weblate.org/en/latest/admin/continuous.html#processing-repository-with-scripts) that does the msgmerge (knowning that the first argument passed to the script is the current `.po` file being processed)
- Append the path to the script in `POST_UPDATE_SCRIPTS` list in your `settings.py`
- Reload Weblate.

Unfortunately, I did not find a way to retrieve the `.pot` base file from the script as an environment variable, which means (from my understanding) that you have to write one post update script per component… 😕 

I would say that a good way to fix this situation would be to allow custom environment variables on components. This would open the way to much more usable post update scripts. Any chance a contribution in this direction would make it? Unless I missed an easy way to do the merge.

Thanks,
Gilbs

**Comment by nijel** [comment]
I've added the new_base (which should hold path to the .pot) to the environment in 95a5ae0872713b580ad5df1f343a36660d3378cc. 

Having this as an option in Weblate will be possible once https://github.com/WeblateOrg/weblate/issues/1353 is implemented.

**Comment by gilbsgilbs** [comment]
Thanks @nijel. That will be really helpful. Cheers.
