### ISSUE TITLE
Greek question mark character

### ISSUE THREAD

**Issue by Frexuz** [WeblateOrg/weblate#1457]
### Steps to reproduce
1. Translate an English sentence ending in a question mark, into Greek.

Greek question mark (;)
http://questionmark.guide/greek-question-mark/

Would be great to implement this rule, like some of the other rules. For example, French have a space before a question mark.

### Actual behaviour
"Trailing question"-check

### Expected behaviour
Should not get the check

**Comment by nijel** [comment]
The support is there since 4df4c5a0a1, can you please specify when it's not working as expected?

**Comment by Frexuz** [comment]
![image](https://cloud.githubusercontent.com/assets/49692/25936666/4f6fb070-365b-11e7-85b9-8e77ca15cc4f.png)

**Comment by nijel** [comment]
I see - the problem is that [the site](https://translate.frexity.com/projects/episodecalendar/web/gr/) is using non standard code for Greek (it should be `el` while it is using `gr`, see https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes). Actually it is using country codes instead of language ones...

**Comment by Frexuz** [comment]
Ah correct! Unfortunately my website URLs and language files use country codes :( Any way around it, or should we just ignore/remove the checks in Greek?

**Comment by nijel** [comment]
You can path the [check](https://github.com/WeblateOrg/weblate/blob/master/weblate/trans/checks/chars.py#L259) to accept gr code as well:

```patch
diff --git a/weblate/trans/checks/chars.py b/weblate/trans/checks/chars.py
index 2cf06df77..219859fa3 100644
--- a/weblate/trans/checks/chars.py
+++ b/weblate/trans/checks/chars.py
@@ -256,7 +256,7 @@ class EndQuestionCheck(TargetCheck):
             return self._check_fr(source, target)
         if self.is_language(unit, ('hy', )):
             return self._check_hy(source, target)
-        if self.is_language(unit, ('el', )):
+        if self.is_language(unit, ('el', 'gr')):
             return self._check_el(source, target)
 
         return self.check_chars(
```

Still using country codes to identify languages is wrong, there are quite some countries in the world using more than one language...
