### ISSUE TITLE
Add support for additional captcha implementation

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1462]
Current captcha is quite simple and prevents from random bots filling in registration page, but does not provide defense against targeted attack.

Therefore it might be good idea to have option to choose captcha implementation and to provide stronger protection.

Probably we could allow plugging [existing captcha implementations for Django](https://djangopackages.org/grids/g/captcha/)

**Comment by pafcu** [comment]
The current captcha implementation is also not accessible for visually impaired users.

**Comment by nijel** [comment]
True, that's valid point as well.

**Comment by nijel** [comment]
I just learned about https://www.hcaptcha.com/ which claims to be privacy friendlier than reCAPTCHA, see for example https://blog.cloudflare.com/moving-from-recaptcha-to-hcaptcha/

**Comment by nijel** [comment]
https://altcha.org/ might be a viable privacy respecting approach.

**Comment by nijel** [comment]
Okay, I've almost completed the implementation of Altcha in https://github.com/WeblateOrg/weblate/pull/12995. But once I started to working on tests, I've realized that this is really a poor implementation of captcha:

* The `check_expires` parameter is useless because it uses expiry from the client, which can provide any expiry there.
* The Python implementation uses `os.random` instead of using the `secrets` module.
* Generally the code quality is poor (for example, `verify_solution` sometimes returns a tuple with two elements and sometimes with three, at the same time it doesn't give detailed reasoning for several error states).

**Comment by nijel** [comment]
In the end, I think we need to clarify what kind of captcha we want:

* Local only captcha requiring user interaction. This has zero privacy impact but is always limited in terms of catching the bots.
* Local PoW captcha, which doesn't require user interaction, but might take too long to solve on slower devices.
* Third-party captcha service. This has a privacy impact and can take additional aspects to prove there is a human (fingerpriting, problematic IP address ranges, ...).

**Comment by nijel** [comment]
Down the rabbit hole there seems to be no great solutions. PoW seems to be the solution chosen by Codeberg in https://codeberg.org/Codeberg/Community/issues/479 (even though it takes them years to implement). I've decided to give PoW a try and include it in addition to existing math captcha in https://github.com/WeblateOrg/weblate/pull/12995. Still I'm not conviced that altcha is the best solution, but unline mCaptcha it doesn't require external service.
