### ISSUE TITLE
Static sites needed to fulfill local laws

### ISSUE THREAD

**Issue by Fjolnir-Dvorak** [WeblateOrg/weblate#1464]
Pages like Terms of Use, Privacy Policy, are missing and can not easily be added. Also there is no documented option on how to opt-in for cookies. Pages like "Impressum" (Contact for law-stuff), "Datenschutz" (Privacy policy) are required by law. Also required by law is a cookie notification.

It could be solved by enabeling rendering of static pages located in a directory like custom_static written in markdown.

**Comment by nijel** [comment]
Indeed these are missing right now. Patches are welcome :-). However some things are not necessary worldwide (eg. the cookie notification).

**Comment by Fjolnir-Dvorak** [comment]
Thank you.
And sorry for not doing it myself creating a merge request.
Currently working on trying to get more elan on working with python and type-unsafety. Hope I will participate with merge requests, soon, seeing that this project is alive and you are caring about it.
