### ISSUE TITLE
Character-sets of MySQL-like databases

### ISSUE THREAD

**Issue by Fjolnir-Dvorak** [WeblateOrg/weblate#1465]
The encoding of the database/tables/columns in the database is set wrong after installing weblate. It need to be changed by hand to utf8 or to utf8-4b to work proberly. The installation is not setting the character-sets it requires to work itself. It is also not well documented that the encoding has to be repaired by hand in both MySQL and in MariaDB.

**Comment by nijel** [comment]
What exactly is missing in the docs? https://docs.weblate.org/en/latest/admin/install.html#mysql-or-mariadb

I know MySQL is really messy about charsets  and even more fun coming with MySQL 8.0 and charsets like utf8mb4_0900_ai_ci.

**Comment by Fjolnir-Dvorak** [comment]
as far as I know it should be solved by specifying the encoding for the database or for the tables in the installation SQL-Query. The default-encoding is latin-1. If you could guide me to the installation-query I could work on creating a fix.

**Comment by nijel** [comment]
I've adusted the docs a bit to have all the creation things at one place.

I think this really should be solved at Django level, but it's probably not going to happen anytime soon, see https://code.djangoproject.com/ticket/18392.

**Comment by Fjolnir-Dvorak** [comment]
I do not know if that is the issue (well, at least a part of it). The database columns are not even encoded in UTF8mb3 which, as far as I understand Django, should be supported.

**Comment by nijel** [comment]
Django (unfortunately) does not set encoding for the columns, that is determined from the database settings, so it really depends on how you have created the database...

**Comment by Fjolnir-Dvorak** [comment]
[http://mechanics.flite.com/blog/2014/07/29/using-innodb-large-prefix-to-avoid-error-1071/](http://mechanics.flite.com/blog/2014/07/29/using-innodb-large-prefix-to-avoid-error-1071/)

Could you add something like that or a link to that page into the wiki/doku? It made weblate work again.

**Comment by nijel** [comment]
Can you please contribute that? Apparently you know what had to be changed, so you are in way better position to write the docs than me :-).

**Comment by nijel** [comment]
I've added the link to the docs, but still more detailed description of the problem and solution is welcome.
