### ISSUE TITLE
Provide example hooks in pip installations

### ISSUE THREAD

**Issue by gilbsgilbs** [WeblateOrg/weblate#1468]
### Steps to reproduce
1. `pip install Weblate`
2. `ls path/to/site-packages/weblate`

### Actual behaviour
Example hooks are missing. We have to download the examples manually and copy them where we want on the server.

### Expected behaviour
Example hooks should be in site-packages, packaged as data inside Weblate package. This would allow to use examples, even when Weblate is installed using pip.

**Comment by nijel** [comment]
True, we have workaround for this in the Docker (see https://github.com/WeblateOrg/docker/issues/18), but handling this at packaging level is better approach. Patches are welcome :-).

**Comment by gilbsgilbs** [comment]
Thanks @nijel for your fast answer. The point is that it probably shouldn't break existing installations that rely on the fact that examples are located in the project root. Maybe we could symlink `weblate/examples/` to `examples/`?
