### ISSUE TITLE
MySQL unique key error after setting utf8mb4 and migrate

### ISSUE THREAD

**Issue by guoyunhe** [WeblateOrg/weblate#1469]
### Steps to reproduce
1. Create a new MySQL database with utf8mb4
2. Make a new Weblate installation
3. Migrate

### Actual behaviour
Migration failed, with error:
```
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
```

### Expected behaviour
Unique keys should be limited length <= 191, not 255
See this topic http://stackoverflow.com/a/31474509/4699409

### Server configuration
Please paste the output of command `./manage.py list_versions` over here
```
 * Weblate 2.13.1
 * Python 2.7.12
 * Django 1.10.7
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.1.0
 * Whoosh 2.7.0
 * defusedxml 0.5.0
 * Git 2.12.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.7.3
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.2
 * pytz 2017.2
 * pyuca N/A
 * PyYAML 3.12
 * Mercurial 3.8.3
 * git-svn 2.12.0
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
There is workaround for this, see https://github.com/WeblateOrg/weblate/issues/1465#issuecomment-299343915, this should be transformed into our documentation, help is welcome.

Unfortunately Django devs are not really interested in fixing this, see https://code.djangoproject.com/ticket/18392
