### ISSUE TITLE
Domain is example.com instead of actual domain name

### ISSUE THREAD

**Issue by guoyunhe** [WeblateOrg/weblate#1470]
### Steps to reproduce
1. Fresh install a Weblate
2. Check API url on preference page
3. Check email send by Weblate

### Actual behaviour
Activation URL and API url all use example.com as domain not the actual domain.

![spectacle q11650](https://cloud.githubusercontent.com/assets/5836790/25751412/9648e108-31bd-11e7-86a5-393b6d4c3c58.png)

### Expected behaviour
The domain should use URL_PREFIX value in settings.py

### Server configuration

 * Weblate 2.13.1
 * Python 2.7.12
 * Django 1.10.7
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.1.0
 * Whoosh 2.7.0
 * defusedxml 0.5.0
 * Git 2.12.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.7.3
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.2
 * pytz 2017.2
 * pyuca N/A
 * PyYAML 3.12
 * Mercurial 3.8.3
 * git-svn 2.12.0
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
Please read our [documentation](https://docs.weblate.org/en/latest/faq.html#why-does-links-contain-example-com-as-domain).
