### ISSUE TITLE
Avoid double button clicking

### ISSUE THREAD

**Issue by Frexuz** [WeblateOrg/weblate#1474]
### Steps to reproduce
1. Hit accept on many suggestions in a row

### Actual behaviour
Sometimes after clicking accept, there is an error message saying "Invalid suggestion", however the suggestion seems to have been saved as the translated string correctly.

Sometimes this happens after 20-30 suggestions, but I've experienced it 3 in a row even!

Video showing it live:
https://vid.me/ml44

### Expected behaviour
There shouldn't be any error message

### Server configuration
 * Weblate weblate-2.13.1-353-gab0d7a5
 * Python 2.7.12
 * Django 1.10.5
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.1.0
 * Whoosh 2.7.0
 * defusedxml 0.4.1
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.5.0
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2014.10
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.11
 * Mercurial 3.7.3
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Couldn't it happen that you've clicked twice on the button?

**Comment by Frexuz** [comment]
Hm, you mean that it does two POST requests? Possible I guess, but I'll try to look out for it the next time. Will let you know :) Don't have any suggestions to approve atm.

**Comment by Frexuz** [comment]
Tried just now, clicking twice on purpose and I'm getting the error. So it seems you're right :) Thanks again!

**Comment by nijel** [comment]
Still this is something we should try to avoid on the client side (probably by disabling the button once clicked).

**Comment by Frexuz** [comment]
Seems I can still hit Accept more than once. I'm on latest master (1c7cd65)

**Comment by nijel** [comment]
You can do that, but it shouldn't submit form more times (the button can't be disabled because disabled buttons are not submitted to server, so the logic would have to be more complex).

**Comment by Frexuz** [comment]
Ah I see.. I'll let you know if this comes up again :)
