### ISSUE TITLE
Broken site after git pull

### ISSUE THREAD

**Issue by Frexuz** [WeblateOrg/weblate#1475]
### Steps to reproduce
1. `git pull` 
2. `./manage.py migrate`
3. `./manage.py collectstatic`
4. `./scripts/generate-locales`
5. restart uwsgi server

### Actual behaviour
1. Registration is broken
```
AttributeError at /accounts/register/
'EmailAuth' object has no attribute 'partial_token'
Request Method:	POST
Request URL:	https://translate.frexity.com/accounts/register/
Django Version:	1.10.5
Exception Type:	AttributeError
Exception Value:	
'EmailAuth' object has no attribute 'partial_token'
Exception Location:	/home/frexuz/weblate/weblate/accounts/pipeline.py in send_validation, line 162
Python Executable:	/usr/bin/uwsgi-core
Python Version:	2.7.12
````

2. Users that aren't Superuser get an **access denied** when accessing any language from the dashboard

### Server configuration

 * Weblate weblate-2.13.1-353-gab0d7a5
 * Python 2.7.12
 * Django 1.10.5
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.1.0
 * Whoosh 2.7.0
 * defusedxml 0.4.1
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.5.0
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2014.10
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.11
 * Mercurial 3.7.3
 * Database backends: django.db.backends.postgresql_psycopg2

Migrations ran:

```
Operations to perform:
  Apply all migrations: accounts, admin, auth, authtoken, contenttypes, lang, permissions, screenshots, sessions, sites, social_django, trans
Running migrations:
  Applying accounts.0028_auto_20170323_0838... OK
  Applying accounts.0029_auto_20170503_1257... OK
  Applying accounts.0030_auditlog... OK
  Applying accounts.0031_auto_20170503_1414... OK
  Applying trans.0078_auto_20170322_1112... OK
  Applying trans.0079_autocomponentlist... OK
  Applying trans.0080_auto_20170323_0838... OK
  Applying trans.0081_auto_20170323_0953... OK
  Applying trans.0082_change_old... OK
  Applying trans.0083_auto_20170404_1633... OK
  Applying permissions.0005_groupacl_permissions... OK
  Applying permissions.0006_auto_20170404_1637... OK
  Applying trans.0084_auto_20170406_0858... OK
  Applying trans.0085_auto_20170406_0904... OK
  Applying trans.0086_remove_project_owners... OK
```

**Comment by nijel** [comment]
For the first error, you need to upgrade your settings.py as the authenticatoin pipeline has been changed (see https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-2-13-to-2-14).

As there is new permission, you will probably have to run `./manage.py setupgroups`. In case you did some customization to permissions, this will reset the default groups to default state. Alternatively adding `Can access project` permission to `Users` and `Guests` groups should fix this. This should happen already on upgrade to 2.13, I wonder why it did not work correctly for you...

**Comment by Frexuz** [comment]
`./manage.py setupgroups` seems to work :)
Fast support! <3

**Comment by nijel** [comment]
I've adjusted upgrading docs to cover this in 33dbbfc.
