### ISSUE TITLE
Add timestamp on suggestions

### ISSUE THREAD

**Issue by Frexuz** [WeblateOrg/weblate#1478]
Knowing how old an suggestion is would help alot! :)

Something like this:
![screenshot 2](https://cloud.githubusercontent.com/assets/49692/25884639/510c4ef0-3586-11e7-9be7-0d445bbac53f.png)

Or possibly, only do relative time, like the suggestion in #173

**Comment by nijel** [comment]
We currently do not store suggestion timestamp, but certainly it makes sense to do that.

**Comment by Frexuz** [comment]
So fast again :D Updated and it works nicely!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
