### ISSUE TITLE
Git Export not working after update from 2.10 to 2.13.1 (from Git)

### ISSUE THREAD

**Issue by BhaaLseN** [WeblateOrg/weblate#1479]
### Steps to reproduce
1. Install 2.10 from git (by checking out the tag `weblate-2.10`)
2. Enable `weblate.gitexport` by adding it to `INSTALLED_APPS` (so we can fix conflicts if necessary)
3. Test the installation for a few months until you see fixes that look interresting
4. Update to 2.13.1 by fetching and checking out the tag `weblate-2.13.1`.
5. Install/Update prerequisites using pip, run Migrations as described in the docs

### Actual behaviour
Weblate is up and working, but Git Export appears non-functional (so we cannot fetch to resolve conflicts). With 2.10, selecting a project, then component and then language showed a side-panel that had the URL used for cloning. 2.13.1 does not have the panel anymore; the only place where the URL shows up is under "Repository Maintenance".
Attempting to fetch from that Remote yields `fatal: repository 'http://weblate/git/Proj/Comp/' not found` despite being the exact URL as shown on "Repository Maintenance" (and also under Administration > Component "Exported repository URL")
Opening the URL in a Web Browser redirects to http://weblate/project/Proj/Comp/ instead.

Repositories under `weblate/data/vcs/Proj/Comp` do not have a `git-daemon-export-ok` file, as `git-http-backend` would require; not sure if that is related. Creating one does not change the fact though.

### Expected behaviour
Git Export works as it did with 2.10 before the upgrade.

### Server configuration
```
 * Weblate weblate-2.13.1
 * Python 2.7.9
 * Django 1.11
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.3
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.2
 * pytz 2017.2
 * pyuca N/A
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
Upgrading instructions really did not cover new permissions which are needed for git export access, I've just updated them:

https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-2-12-to-2-13

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by BhaaLseN** [comment]
Hm, I'm not sure if I made any mistakes while upgrading, but I did run `./manage.py setupgroups` back then. Just ran it again, didn't change anything.

I didn't notice until I read your changes that pointed me to [Git Exporter - Usage](https://docs.weblate.org/en/latest/admin/optionals.html#usage) - we don't use per-project ACLs; they are disabled. And it clearly states that repositories should be accessible that way.

Regardless, I checked permissions for the "Users", "Guests" and "Proj@Administration" groups - they all have `trans | Component | Can access VCS repository` assigned.
I also checked my own user and "anonymous" (which I assume is used when per-project ACL is disabled) - added `trans | Component | Can access VCS repository` just to make sure.
Then I used http://myuser:myapikey@server/git/Proj/Comp/ instead; same error.

Then I tried to enable ACLs on that project, and got this one:
```
ERROR Internal Server Error: /admin/trans/project/1/change/#012Traceback (most recent call last):#012  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner#012    response = get_response(request)#012  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response#012    response = self._get_response(request)#012  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response#012    response = self.process_exception_by_middleware(e, request)#012  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response#012    response = wrapped_callback(request, *callback_args, **callback_kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 551, in wrapper#012    return self.admin_site.admin_view(view)(*args, **kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view#012    response = view_func(request, *args, **kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func#012    response = view_func(request, *args, **kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 224, in inner#012    return view(request, *args, **kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1511, in change_view#012    return self.changeform_view(request, object_id, form_url, extra_context)#012  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 67, in _wrapper#012    return bound_func(*args, **kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view#012    response = view_func(request, *args, **kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 63, in bound_func#012    return func.__get__(self, type(self))(*args2, **kwargs2)#012  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1408, in changeform_view#012    return self._changeform_view(request, object_id, form_url, extra_context)#012  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1448, in _changeform_view#012    self.save_model(request, new_object, form, not add)#012  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 979, in save_model#012    obj.save()#012  File "/home/weblate/weblate/weblate/trans/models/project.py", line 271, in save#012    super(Project, self).save(*args, **kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 806, in save#012    force_update=force_update, update_fields=update_fields)#012  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 846, in save_base#012    update_fields=update_fields, raw=raw, using=using,#012  File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 193, in send#012    for receiver in self._live_receivers(sender)#012  File "/home/weblate/weblate/weblate/utils/decorators.py", line 30, in wrapper#012    signal_handler(*args, **kwargs)#012  File "/home/weblate/weblate/weblate/trans/models/__init__.py", line 249, in setup_group_acl#012    group_acl = GroupACL.objects.get_or_create(project=instance)[0]#012  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method#012    return getattr(self.get_queryset(), name)(*args, **kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 463, in get_or_create#012    return self.get(**lookup), False#012  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 383, in get#012    (self.model._meta.object_name, num)#012MultipleObjectsReturned: get() returned more than one GroupACL -- it returned 4!
```
In the end, I couldn't enable ACLs for that project at all.

Anything else I could try to enable/disable/assign, anywhere around the Django admin section, settings.py, the Apache config etc?

My current workaround is using the weblate user and fetching over ssh, straight from `weblate/data/vcs/Proj/Comp/.git`. Not pretty, but works for the time being.

**Comment by nijel** [comment]
Did you define GroupACLs on your own or this is result of some failed upgrade? You probably have some defined for translation or component level, don't these filter the VCS access permission?

The query was certainly not strict enough, I've fixed that in 1c7cd65bfcb73ccd87a25224133921baf141c964, I think it should fix your problem with enabling ACL.

**Comment by BhaaLseN** [comment]
Not that I know of. The only remotely permission-related action that I took was assigning users to groups (such as "Admin of Project X" or "Translator"); and that was done through the Project configuration...well, and my attempts of fixing them by adding new ACLs to get the functionality back.
That system is in a locked down network where only permitted users have access, so I don't really have to bother with permissions; nor do we need them (devs work on pretty much all projects, and so do our translators).

Just checked the database, and I'm not sure if that is the issue here:
```
MariaDB [weblate]> select * from permissions_groupacl;
+----+-------------+------------+---------------+
| id | language_id | project_id | subproject_id |
+----+-------------+------------+---------------+
|  1 |        NULL |          1 |          NULL |
|  5 |        NULL |          1 |          NULL |
|  6 |        NULL |          1 |          NULL |
|  7 |        NULL |          1 |          NULL |
|  4 |        NULL |          2 |          NULL |
|  2 |        NULL |          3 |          NULL |
|  3 |        NULL |          4 |          NULL |
+----+-------------+------------+---------------+
7 rows in set (0.02 sec)
```

Project 1 is the one I tried; ACL Id 1 is the default "Proj@Administration" group, 5 is the "@Translate" group (not sure if that one is supposed to have its name like that", 6 is the "@Administration" group (again, not sure if the name is intended) and 7 is "Guests".

Would it help if I just go and clear those tables (or rather, remove all entries on the "Group ACL" admin page)?

At the end of the day, I still can't see how this breaks Git Exporter when no project ACLs are enabled (at least from what the Admin page tells me) and it is intended to be used without authentication.

**Comment by nijel** [comment]
Hmm, that's strange, there should be database level restriction to avoid GroupACL with same language/project/subproject.

How does the table look in your case? You can display it by `SHOW CREATE TABLE permissions_groupacl;` in MySQL shell.

**Comment by nijel** [comment]
Also it would be interesting to see groups assignment for those GroupACL, can you please also execute:

```mysql
select * from permissions_groupacl 
join permissions_groupacl_groups 
on permissions_groupacl.id=permissions_groupacl_groups.groupacl_id 
join auth_group 
on permissions_groupacl_groups.group_id=auth_group.id;
```

**Comment by BhaaLseN** [comment]
Table definition:
```
CREATE TABLE `permissions_groupacl` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `language_id` int(11) DEFAULT NULL,
  `project_id` int(11) DEFAULT NULL,
  `subproject_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `permissions_groupacl_project_id_subproject_id_8458bb98_uniq` (`project_id`,`subproject_id`,`language_id`),
  KEY `permissions_groupacl_language_id_a7b853ce_fk_lang_language_id` (`language_id`),
  KEY `permissions_groupacl_subproject_id_751fca8a_fk_trans_sub` (`subproject_id`),
  CONSTRAINT `permissions_groupacl_language_id_a7b853ce_fk_lang_language_id` FOREIGN KEY (`language_id`) REFERENCES `lang_language` (`id`),
  CONSTRAINT `permissions_groupacl_project_id_bea117ba_fk_trans_project_id` FOREIGN KEY (`project_id`) REFERENCES `trans_project` (`id`),
  CONSTRAINT `permissions_groupacl_subproject_id_751fca8a_fk_trans_sub` FOREIGN KEY (`subproject_id`) REFERENCES `trans_subproject` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8
```

And the GroupACL assignment:
```
+----+-------------+------------+---------------+----+-------------+----------+----+----------------------+
| id | language_id | project_id | subproject_id | id | groupacl_id | group_id |id  | name                 |
+----+-------------+------------+---------------+----+-------------+----------+----+----------------------+
|  1 |        NULL |          1 |          NULL |  1 |           1 |       10 | 10 | Proj@Administration  |
|  5 |        NULL |          1 |          NULL |  5 |           5 |        6 |  6 | @Translate           |
|  6 |        NULL |          1 |          NULL |  6 |           6 |        9 |  9 | @Administration      |
|  7 |        NULL |          1 |          NULL |  7 |           7 |        1 |  1 | Guests               |
|  4 |        NULL |          2 |          NULL |  4 |           4 |       13 | 13 | Test1@Administration |
|  2 |        NULL |          3 |          NULL |  2 |           2 |       11 | 11 | Test2@Administration |
|  3 |        NULL |          4 |          NULL |  3 |           3 |       12 | 12 | Test3@Administration |
+----+-------------+------------+---------------+----+-------------+----------+----+----------------------+
```

And for good measure, the DBMS info:
```
MariaDB [weblate]> status
--------------
mysql  Ver 15.1 Distrib 10.0.28-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Connection id:          34757
Current database:       weblate
Current user:           weblate@localhost
SSL:                    Not in use
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server:                 MariaDB
Server version:         10.0.28-MariaDB-0+deb8u1 (Debian)
Protocol version:       10
Connection:             Localhost via UNIX socket
Server characterset:    latin1
Db     characterset:    utf8
Client characterset:    utf8
Conn.  characterset:    utf8
UNIX socket:            /var/run/mysqld/mysqld.sock
Uptime:                 35 days 6 hours 23 min 27 sec
```

**Comment by nijel** [comment]
Okay, it seems that my expectations on UNIQUE are not matching reality - "a UNIQUE index permits multiple NULL values for columns that can contain NULL". I certainly have to look at better way handling this.

Anyway those groupacls - 5, 6, 7 look bogus, removing that should make the situation better.

**Comment by BhaaLseN** [comment]
Yeah, I just found that too; apparently this is "correct" and "by design" on mysql.

Removed the ACLs, and now I can successfully enable project ACLs. Doesn't change anything, both trying to fetch/clone/ls-remote on either the unauthenticated or the user/apikey authenticated URL return a HTTP 400 error.
Apache access log shows 
```
weblate:80 ::1 - - [10/May/2017:20:11:45 +0200] "GET /git/IS/DC/info/refs?service=git-upload-pack HTTP/1.1" 400 268 "-" "git/2.1.4"
```
Nothing in syslog, so I don't know where it gets stuck...

**Comment by nijel** [comment]
I think that Weblate won't return HTTP 400 on it's own, so it's probably coming from git-http-server. Do you see any error in Weblate logs? Also the response probably contains error message, try using `curl http://weblate/git/Proj/Comp/info/refs?service=git-upload-pack` to see that.

**Comment by BhaaLseN** [comment]
Using `curl -i` returns this:
```
HTTP/1.1 400 Bad Request
Date: Wed, 10 May 2017 18:43:28 GMT
Server: Apache/2.4.10 (Debian)
Vary: Accept-Language,Cookie
X-Frame-Options: SAMEORIGIN
Content-Language: en
Content-Length: 26
Connection: close
Content-Type: text/html

<h1>Bad Request (400)</h1>
```

I didn't touch Git or Apache; the upgrade was done only using pip and git checkout so I'd be surprised if one of those is causing this...

The only log location i know of is `/var/log/syslog`, and it has nothing on this. Temporarily enabling a log file at `/var/log/weblate/weblate.log` writes nothing. Both are at their default level of DEBUG, so at least something should've been there...
`/var/log/messages` has some periodic update messages, but nothing related to Git Export.

**Comment by nijel** [comment]
Maybe your [ALLOWED_HOSTS](https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-ALLOWED_HOSTS) settings does not match what you use in git/curl?

**Comment by BhaaLseN** [comment]
Duh, right. I was running this from the server itself using localhost; which I didn't add to `ALLOWED_HOSTS` (assuming I'd never need it anyways). With the correct Host header, I get a 403 by weblate.

But, now the interresting part:
I tried enabling ACLs, just to see if I could get rid of that 403 (which was at least some progress), and suddenly got "repository not found".
So I disabled them again - and now it works.

I have no idea what happened, but currently project ACLs are disabled, and Git Exporter is working for all projects.

Thanks for spending your time to help me figure this out, even though I don't really know why it worked in the end.
Is there anything I could look at to get some clues (logs appear to be empty or unrelated/useless), or do you want to close this issue now that this seems to be resolved?

**Comment by nijel** [comment]
It looks like the owners migration to GroupACL didn't work correctly, I will look deeper at the code tomorrow, but it seems that the additional GroupACLs have actually caused this....

**Comment by nijel** [comment]
I've failed to figure out how these GroupACLs were created - apparently they were created after the migration (based on their ID), but there is no such code which would do that. Didn't you create those manually in the end?

The other thing is that apparently the original GroupACL did filter too many permissions. Do you happen to know when did you apply the permissions.0006_auto_20170404_1637 migration? If that was before f65eaf084a4b773d6b9ca79373eac89bdea7f2c1, this might be the outcome...

Still there is https://github.com/WeblateOrg/weblate/issues/1480 to solve.

**Comment by BhaaLseN** [comment]
I specifically checked out the tag `weblate-2.13.1`, so it should be _after_ that commit...unless you moved that tag later on, it should've been included. I'll check again tomorrow, it should still be in the scrollback of my screen session (unless I cleared it during my testing frenzy the other day).
