### ISSUE TITLE
POST/PUT screenshots via API

### ISSUE THREAD

**Issue by saily** [WeblateOrg/weblate#1482]
## Given

- We run selenium and protractor to generate screenshots of our testscases.
- We embrace all translated strings in those screenshots with a red box, identification is done using the translation-key as an identifier in html code. 

After running our CI pipeline i have a build artifact containing all screenshots. 

## Idea

So this is a feature request about uploading build artifacts zip-file or each screenshot separately to Weblate using the REST API.

**Comment by nijel** [comment]
I have (read only) API almost ready, I should polish it and publish, so that somebody can implement upload on top of that...

**Comment by saily** [comment]
cool, i'm happy to contribute some stuff here. When are you going to merge the readonly API?

**Comment by nijel** [comment]
In few minutes ;-)

**Comment by nijel** [comment]
It's now there: https://docs.weblate.org/en/latest/api.html#screeenshots

**Comment by saily** [comment]
@nijel i looked into that and adding Update is pretty simple. I was wondering how to add new screenshots, but the current `ScreenshotSerializer` does not support this. Any reason why you skipped `ModelSerializer` of `django_restframework` and implemented your own ones?

If i'm gonna to refactor this, it would be a pretty heavy change, but i'd suggest to discuss it before you introduce the Screenshot API in a release. Are you available on IRC?

**Comment by nijel** [comment]
AFAIR it's all based on ModelSerializer, it's just the viewsets are read only (mostly because I don't want to expose editing of project/component stuff over API right now).

PS: I didn't look at the code right now, so I might be wrong.
