### ISSUE TITLE
Command `weblate cleanuptrans` show error `no moduled named permissions`

### ISSUE THREAD

**Issue by JesusZapata** [WeblateOrg/weblate#1486]
### Steps to reproduce
1. Create project 
2. Rename slug of the project
3. Try `weblate cleanuptrans`

### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/1387970/26036526/419305d4-38ad-11e7-8f0b-7647d2464fbb.png)

### Expected behaviour
Run whitout error

### Server configuration
![image](https://cloud.githubusercontent.com/assets/1387970/26063352/cfc4e440-395b-11e7-866f-069196772a14.png)

**Comment by nijel** [comment]
What weblate version are you actually using? It seems you run 2.12 code on 2.13 settings.py...

**Comment by JesusZapata** [comment]
@nijel 
I fixed the version

**Comment by nijel** [comment]
Please use settings from the version you're using - the permissions app has been added in 2.13. There is settings_example.py shipped with Weblate which you can use.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
