### ISSUE TITLE
Clarify becoming a translator

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1487]
### Steps to reproduce
1. Find component with no translation activity in Weblate.
2. Suggest a translation there.

### Actual behaviour

Following message is shown:

"There is currently no active translator for this translation, please consider becoming a translator as your suggestion might otherwise remain unreviewed."

However it seems to be confusing to new users:

> The interface tells me I should become a translator, since there isn't one appointed and my suggestions won't be otherwise reviewed. I do I do that?

### Expected behaviour

The description should be clear on what to do, probably with link to documentation to figure out more.

**Comment by kishan3** [comment]
Newbie here. Hi @nijel How do i set up the project in my local after doing git clone ? Is database dump required ? Thanks.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
