### ISSUE TITLE
Suggestion to enhance FAQ How to fix merge conflicts in translations?

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1493]
The FAQ *How to fix merge conflicts in translations?* documents generic git conflict merge. In case of Gettext po files, "edit" is not a smart way to do it. gettext-tools can do it better.

In addition to the generic merge, it would be nice to document Gettext po specific way to merge conflicts:

1. Clone the whole set of commands in the frame.

2. Add text:

*In case of Gettext po files, there is a way to merge conflict in a semi-automatic way:*

*Get and keep local clone of the Weblate git repository. Also get a second fresh local clone of the upstream git repository (i. e. you need two copies of the upstream git repository: intact and working copy).*

3. And it the Gettext po specific frame, change:

```shell
# Add remote
git remote add weblate https://hosted.weblate.org/git/weblate/master/
```

change to

```shell
# Add remote
git remote add weblate /path/to/weblate/snapshot/
```

```shell
# Resolve conflicts
edit ....
git add ...
```

```shell
# Resolve conflicts
for PO in space separated list of conflicting po files ; do
	msgcat --use-first /path/to/weblate/snapshot/$PO\
			   /path/to/upstream/snapshot/$PO -o $PO.merge
	msgmerge --previous --lang=${PO%.po} $PO.merge domain.pot -o $PO
	rm $PO.merge
	git add $PO
done
```

**Comment by nijel** [comment]
Sounds useful, can you please prepare patch for that? Thanks.

**Comment by stanislav-brabec** [comment]
Thinking more about it, I can even imagine automatic conflict solver, either embedded into Weblate, external, or even embedded into git. Tool would need a database of all po/pot relations inside the repository.

**Comment by nijel** [comment]
Certainly that would be possible as well, see #98 and #55.

**Comment by stanislav-brabec** [comment]
Thanks for referring them. I will document this way of merge, but implement #55 to our projects.

**Comment by nijel** [comment]
Having this in Weblate would be great as well, I've documented current state (and problems) in https://github.com/WeblateOrg/weblate/issues/55#issuecomment-302694083.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
