### ISSUE TITLE
Source changes are not propagated on monolingual base files

### ISSUE THREAD

**Issue by timonreinhard** [WeblateOrg/weblate#1495]
### Steps to reproduce
1. Enable translation propagation for all components
2. Use monolingual translation files, allow editing base file
3. Have identical context ids across the whole project
4. Change the source string for a specific context in component A 

### Actual behaviour
The source string for component B is not changed

### Expected behaviour
The source string for component B is changed to the string of component A (as the context/msgid matches exactly)

### Server configuration
```
 * Weblate weblate-2.12
 * Python 2.7.6
 * Django 1.10
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0b7
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.6.0
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.2
 * pytz 2017.2
 * pyuca N/A
 * pyLibravatar N/A
 * tesserocr 2.1.3
 * Mercurial 2.8.2
 * Database backends: django.db.backends.mysql
```

**Comment by timonreinhard** [comment]
Awesome! Thank you a lot!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
Yes, that is intended to limit risk of changing message with different meaning which happen to have some source string (let's say you would have two strings "Sun" - one would be short name for Sunday and second the star, they would most likely have different context and you don't want to edit them both).

I thought there is issue for listing units with different context in "other translations", but apparently it was only mentoined in https://github.com/WeblateOrg/weblate/issues/1396#issue-212402016, maybe it's time to have separate issue for that as it certainly makes sense to show them there.

**Comment by timonreinhard** [comment]
Thanks for clarifying. I just opened #1503 as a feature request that is meant to address this limitation. It's however not exactly about [#1396 (comment)](https://github.com/WeblateOrg/weblate/issues/1396#issue-212402016) but more the other way around: When using the _same_ context identifier across multiple components, they should show up in "other translations" even though the source translations may differ (e.g because the source strings have been refined by translators in between new feature branches where created).
