### ISSUE TITLE
Docs: graphviz chart won't render

### ISSUE THREAD

**Issue by egor83** [WeblateOrg/weblate#1497]
### Steps to reproduce
1. Go to https://docs.weblate.org/en/latest/admin/continuous.html

### Actual behaviour
I see a text dump:
`digraph translations { "Developers" [shape=box, fillcolor=lightgreen, <...>`

### Expected behaviour
I expected to see a chart (workflow scheme).

### Additional information:
In console:

    continuous.html#update-vcs:1 Access to Font at 'https://media.readthedocs.org/
    fonts/fontawesome-webfont.woff2?v=4.6.3' from origin 'https://docs.weblate.org' 
    has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is 
    present on the requested resource. Origin 'https://docs.weblate.org' is 
    therefore not allowed access. The response had HTTP status code 404.

    continuous.html#update-vcs:1 Refused to display 'https://docs.weblate.org/en/
    latest/_images/graphviz-bad30ad0666528b8faaa6382fe0d637c11dfe5e5.svg' in a 
    frame because it set 'X-Frame-Options' to 'deny'.

    /en/latest/_images/graphviz-bad30ad0666528b8faaa6382fe0d637c11dfe5e5.svg Failed 
    to load resource: net::ERR_BLOCKED_BY_RESPONSE

### Server configuration
N/A - it's a problem with documentation hosted on Github

**Comment by nijel** [comment]
Thanks for spotting, there are actually two issues here:

* Font issue, which is problem on readthedocs.org which we use for the docs, see https://github.com/rtfd/readthedocs.org/issues/2781
* The frame option for SVG, that was too strict setup of our server, I've just fixed that.

**Comment by egor83** [comment]
Confirming it works - thanks for the quick fix, and for the project in general!
