### ISSUE TITLE
glossary doesn't seem to find words in source that contain a dash (-)

### ISSUE THREAD

**Issue by WorldCodeCentral** [WeblateOrg/weblate#1500]
### Steps to reproduce
1. upload a text, e.g. german, containing a dash like Nordrhein-Westfalen
2. add a glossary term for that word, e.g. Nordrhein-Westfalen <-> Northrhine Westfalia
3. glossary won't show/ suggest Nordrhein-Westfalen <-> Northrhine Westfalia. This only seems to occure for terms containing a dash

### Actual behaviour
glossary won't show/ suggest Nordrhein-Westfalen <-> Northrhine Westfalia.

### Expected behaviour
glossary should show/ suggest Nordrhein-Westfalen <-> Northrhine Westfalia.

### Server configuration
can't check this right now, will post when requested

**Comment by nijel** [comment]
Having at least Weblate version would be useful. There were several fixes for glossary in 2.13 and 2.14, see #1168.

**Comment by WorldCodeCentral** [comment]
I'm using some stale 2.14 dev version. Thanks, should have thought of updating myself... I will post on the other issue if the problem persists after updating. Awesomely fast reply btw :-)

**Comment by nijel** [comment]
I've just tested it on master and it doesn't work there either....
