### ISSUE TITLE
Show other translations that share the same context

### ISSUE THREAD

**Issue by timonreinhard** [WeblateOrg/weblate#1503]
As stated in [#1495](https://github.com/WeblateOrg/weblate/issues/1495#issuecomment-303632050) related translations are only shown in the "Other translations" tab if they share both, the context id _and_ source translation.

(Optionally) weakening that restriction so that only a match on the context id is required for showing it in "other translations" would massively improve the handling of projects that use monolingual base files with same context ids shared across a large number of components.

**Comment by nijel** [comment]
Related to https://github.com/WeblateOrg/weblate/issues/1429 as well

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
