### ISSUE TITLE
Filter by translator

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#1504]
Dear @nijel!
I was thinking about a feature to filter translations by contributor, this way, translators can review each other's work in case of style differences or fixing cases of different translated terms for the same source.

(Already implemented in Transifex BTW)

Kind regards,
Yaron.

**Comment by nijel** [comment]
There is already review option to show you contributors from others:

https://hosted.weblate.org/translate/weblate/master/de/?date=2017-05-01&type=review

Maybe it should be more visible though...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
