### ISSUE TITLE
commit & push only translation files

### ISSUE THREAD

**Issue by serdyuk-alex** [WeblateOrg/weblate#1505]
Currently all files are committed & pushed, e.g. if I choose different push repo url I'll get just a copy of my repository but with translations. Is it possible to commit only translation files?

**Comment by nijel** [comment]
The repository is same as you add to Weblate. You can use git submodules to split translations from the code, see our FAQ: https://docs.weblate.org/en/latest/faq.html#how-can-i-limit-weblate-access-to-translations-only-without-exposing-source-code-to-it
