### ISSUE TITLE
Switch to a different language of the currently shown string

### ISSUE THREAD

**Issue by BhaaLseN** [WeblateOrg/weblate#1509]
This might be very similar to #197, but given its complexity this could be an alternative for shorter term consideration.

Right now if someone edits a non-source language (lets say "fr-FR" for french), the source string is shown regardless and has a little pencil for "Edit source string" next to it. Clicking that one navigates to the source language (lets say "en-GB" for english).
However, once we switched to the source string, the original context from fr-FR is gone, and only a Browser back gets us there. Regardless of where we are, we don't have the option of going to "de-AT" (for german) or any other language.

It would be nice if there were a dropdown somewhere that lets the user pick one of the languages currently present in the project/component, so they can switch from en-GB to fr-FR to de-AT to whatever other language they'd like to look at.
Main reason I'd like to see a feature like that is because the URL is not interchangable (which looks like `/translate/Proj/Comp/en-GB/?sid=<guid>`); I cannot simply replace "en-GB" with "fr-FR" in the URL and end up in the other language (but the same resource key).

And as a scaled down version of that, alternatively, we could use secondary languages (which right now are shown as read-only) and put a small pencil next to them as well (with the same functionality as "Edit source string", except they go to the given language instead).
I imagine this to be easier, because the "Edit source string" URL looks different and _is_ interchangable (which looks like `/translate/Proj/Comp/en-GB/?checksum=<hash>`) between languages.

**Comment by nijel** [comment]
Having edit link on the secondary languages certainly makes sense, I'm a bit worried about more complex solution as it won't be much used and probably will just pollute the UI....

**Comment by BhaaLseN** [comment]
I totally understand that. But there have been quite a few cases where I thought "hmm, what do the other translations look like?" and the only way to get there was backing out, picking the other language and then finding the right key again (until I noticed the URL on "Edit source string").

I can live with a simple edit link on secondary languages, it gets the job done just as much as any other (except you might want to look at a language other than the configured secondary languages, ex. to review its trailing period, leading/trailing space etc. configuration)

**Comment by nijel** [comment]
I've added other translations tab to bottom context pane, I think it's good addition there.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
