### ISSUE TITLE
Newly added glossary terms are not shown in the glossary section (but are saved to the glossary)

### ISSUE THREAD

**Issue by bamstam** [WeblateOrg/weblate#1510]
### Steps to reproduce
1. switch to translation mode
2. enter new glossary term in glossary section and click add
3. SOMETIMES glossary terms are not shown immediately in the glossary section (but are saved to the glossary and can be looked up there)
4. it is not apparent, on which occasions new terms are not shown properly in the glossary section, therefore difficult to reproduce
5. hypothesis: one-word entries are processed without problems, entries with separated words or sentences are not shown properly (hypothesis also not reproducable in all cases)

version: Weblate 2.13.1

### Actual behaviour
Tell us what happens instead

### Expected behaviour
Tell us what should happen

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

**Comment by nijel** [comment]
The section shows only matching words, so if you add word which is not present in current string, it's not shown. That's indeed a bit confusing...

**Comment by bamstam** [comment]
Many thanks, now it's reproducable :-) enhancement would be great

**Comment by bamstam** [comment]
Additional findings:

exact string (e.g. "gamma delta") is not shown in the glossary section when the following conditions apply:
1) exact string is preceded by other words: alpha beta gamma delta
2) brackets are included: alpha beta (gamma delta)
3) colon at the end: alpha beta gamma delta:
4) hyphen is included: alpha beta gamma-delta

Will try to reproduce these cases
