### ISSUE TITLE
The default png status badge is unreadable

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1511]
### Steps to reproduce
1. https://hosted.weblate.org/widgets/osmand/el/status-badge.png
2. https://hosted.weblate.org/widgets/osmand/?lang=el

### Actual behaviour
Text runs out of frame.
Description lacks images.

### Expected behaviour
Nice badge.

### Server configuration
N/A

**Comment by nijel** [comment]
The default badge is SVG exactly for this reason:

![SVG badge](https://hosted.weblate.org/widgets/osmand/el/svg-badge.svg)

But the PNG one certainly could be improved to handle long texts better.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
