### ISSUE TITLE
After deleting glossary item on glossary page n, glossary jumps back to page 1

### ISSUE THREAD

**Issue by bamstam** [WeblateOrg/weblate#1512]
After deleting glossary item on glossary page n, glossary jumps back to glossary page 1

### Expected behaviour
Glossary should stay on the same page in case more strings have to be deleted on this page

tested on version 2.13.1 and 2.14.1

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
