### ISSUE TITLE
Missing source langauge 

### ISSUE THREAD

**Issue by MirabelaBiciin** [WeblateOrg/weblate#1513]
### Steps to reproduce
1.Administration
2.Components
3.Open a component configuration
4. Monolingual base language file: folder/en_US.properties

![screenshot from 2017-06-07 13-52-33](https://user-images.githubusercontent.com/23188941/26875096-f67a6b0c-4b88-11e7-9a49-686dc997e1e0.png)

### Actual behaviour
When I access  Weblate->component, the source language doesn't appear in the list of all languages containing translations for current component.

### Expected behaviour
The source language should appear like all the other languages do. Before changing the file name to use posix style language tag, the source file was named en-US.properties and it worked.

**Comment by nijel** [comment]
Just check "Edit base file" and it will be listed :-).

**Comment by MirabelaBiciin** [comment]
If we check this box, users will be able to edit the source file. How can prevent this? Can we give access just to some users to do it?

**Comment by nijel** [comment]
There is special permission for that (save_template), you can remove that from Users group.

**Comment by MirabelaBiciin** [comment]
Great! Thank you very much. You were really helpful with this issue. I'll make the changes like you said. 
Have a nice day!
