### ISSUE TITLE
Display a warning when trying to manage languages and projects

### ISSUE THREAD

**Issue by GuillaumeAmat** [WeblateOrg/weblate#1515]
Because today, Weblate refuses to submit the followed languages/projects when the user didn't set its firstname and lastname.

The user should be notified in place to do that, it's not obvious.

**Comment by nijel** [comment]
What you mean by managing? In the admin interface? What error do you get?

**Comment by GuillaumeAmat** [comment]
1. You create a user
2. The user logs in
3. He clicks on the *Manage your languages* or the *Manage watched projects* button
4. He modifies its languages or watched projects
5. He clicks on the save button
6. Nothing happens, no apparent submit, no reload of the page, no warning

I figured out that the reason is the user didn't set its first and last names. When set, he can manage languages and watched projects without any trouble.

Weblate displays a warning alert on the dashboard to notify the user that its first and last names are not set, but it's not clear that it blocks some actions. IMHO Weblate should notify the user when he wants to do some actions that are blocked for some reasons.

**Comment by GuillaumeAmat** [comment]
Thanks

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
