### ISSUE TITLE
bad web error if user is not allowed to view project

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1516]
### Steps to reproduce
1. Disallow user to view a project.
2. View a project.

### Actual behaviour
Web page which shows:
Page Not Found
You are not allowed to access project yast-security.
The page you are looking for was not found.

However the following translation projects are available on this server:

### Expected behaviour
Do not show "Page Not Found" if page exists and you are just not allowed to see it.

### Server configuration
 * Weblate 2.13.1
 * Python 2.7.12
 * Django 1.10.5
 * six 1.9.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.0
 * defusedxml 0.4.1
 * Git 2.12.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.6.1
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2015.2
 * pyuca N/A
 * PyYAML 3.11
 * Mercurial 3.8.3
 * git-svn 2.12.0
 * git-review 1.25.0
 * Database backends: django.db.backends.postgresql_psycopg2, django.db.backends.mysql

**Comment by nijel** [comment]
This is intentional to avoid information leaks. The message "You are not allowed to access project yast-security." was removed later as well. See https://github.com/WeblateOrg/weblate/issues/1439
