### ISSUE TITLE
Languages summary does not show languages summary

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1526]
Numbers in the languages summarty don't show summary of a particular language but an overall summary.

### Steps to reproduce
1. https://l10n.opensuse.org/languages/cs/
2. Click to say icewm

### Actual behaviour
You see 76.9%, but after clicking to it you see 86.9%, which is a number from https://l10n.opensuse.org/projects/icewm/ and not https://l10n.opensuse.org/projects/icewm/icewm-1-3-branch/cs/

### Expected behaviour
The summary page should show percentage from the selecte language.

### Server configuration
 * Weblate 2.13.1
 * Python 2.7.13
 * Django 1.10.5
 * six 1.9.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.0
 * defusedxml 0.4.1
 * Git 2.12.3
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.6.1
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2015.2
 * PyYAML 3.11
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Confirmed on current git.
