### ISSUE TITLE
List "other translations" with no changes compared to each other

### ISSUE THREAD

**Issue by petterreinholdtsen** [WeblateOrg/weblate#1527]
The list of 'other translations' some times seem to indicate that different translations for a string exist, but when I have a look at the existing translations, they appear to be identical.
An example can be seen by visiting https://hosted.weblate.org/translate/debian-handbook/05_packaging-system/nb_NO/?checksum=&offset=&q=%3Cprimary%3Epackage&search=substring&source=on&target=on&type=all&ignored=False .

Is there some hidden whitespace that make weblate believe the seemingly identical strings are different?

**Comment by nijel** [comment]
There is no difference, just the diff is shown even if there is none...

**Comment by petterreinholdtsen** [comment]
Perhaps an idea to change weblate to now show 'other translations' when all of them are identical, and not indicate that there is a diff if there is none?  It is very confusing as it is today.

**Comment by nijel** [comment]
I think it's still useful information to see that the same string is used in more locations...
