### ISSUE TITLE
Any local storage?

### ISSUE THREAD

**Issue by marcperrin** [WeblateOrg/weblate#1529]
Let's say you're a user who frequently does searches on context (only).

Correct me if I'm wrong, but it seems you have to repeatedly untick "Search in source strings" / "Search in target strings", and tick "Search in context strings".

Do you think using html local storage to persist last search config would be a good solution to this issue?
We could also add other buttons in addition to the one Search button, for different search flavors (e.g. "Search in context only"), but that could escalate quickly...

And the local storage question would stay on the table anyway, as I guess preferences persistence (so, purely on client side) could be nice on other pages of the site.

What do you think?

Thanks!

**Comment by marcperrin** [comment]
NB: I've got a changelist if you want to have a look (nothing complicated, just localStorage handling) that focuses only on the "search" forms (but all of them).

The difficult part is choosing between a site-wide storage (too blunt), per pathname storage (too micro) or maybe a more sophisticated approach (?).

**Comment by marcperrin** [comment]
NB: incidentally, some issues I've seen on Search:
- If I look for a query string _only_ in Context strings, it will still be highlighted in Source / Target in the result list (and Context isn't featured in the result list) (same issue with Location or Comment) (I can enter a separate issue for this)
- (Big pagination bug, but from what I understand it could be fixed in 2.15)

**Comment by nijel** [comment]
Indeed the highlighting is global, doesn't affect where the string was matched. Maybe it's worth opening separate issue. Some pagination error was fixed in 2.14.1, if you still see it, please report separate issue as well.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
