### ISSUE TITLE
Sorting of glossary terms

### ISSUE THREAD

**Issue by bamstam** [WeblateOrg/weblate#1531]
Weblate 2.14.1

Sorting of glossary terms is currently done in the following order:

1) sorting capitalized glossary terms alphabetically, then
2) sorting lowercased glossary terms alphabetically

Example:
A
B
C
D
a
b
c
d

Recommendation: sorting all terms (capitalized and lowercased) alphabetically to make it easier to find similar terms

### Steps to reproduce
1.
2.
3.

### Actual behaviour
Tell us what happens instead

### Expected behaviour
Tell us what should happen

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

**Comment by bamstam** [comment]
ps: seems to be fixed in 2.15-dev

**Comment by nijel** [comment]
I don't think it's fixed. It probably depends on the database backend (MySQL does by default case insensitive sorting).
