### ISSUE TITLE
Cannot use Ubuntu One SSO for registration despite following documentation

### ISSUE THREAD

**Issue by Flohack74** [WeblateOrg/weblate#1532]
### Steps to reproduce
1. Go to https://ubpweblate.tnvcomp.com
2. Try to log in with Ubuntu One account
3. Authorize account details on Ubuntu One page and press OK

### Actual behaviour
Error message about " CSRF token missing or incorrect."

### Expected behaviour
User gets registered

I already had to add

`CSRF_TRUSTED_ORIGINS = ['login.ubuntu.com']`

somewhere in the config which is missing from the documentation. Also switched on https for the site, did not help.

### Server configuration
 * Weblate 2.14.1
 * Python 2.7.12
 * Django 1.11.2
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.3
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.8.0
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.3
 * pytz 2017.2
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Database backends: django.db.backends.mysql

**Comment by Flohack74** [comment]
Nice, thx! I installed with the virtualenv method, can I somehow just checkout the latest git over it?

**Comment by nijel** [comment]
Weblate 2.15 will be out tomorrow, so it's probably easier to wait ;-).

**Comment by Flohack74** [comment]
Thanks! Yes will do =)

**Comment by nijel** [comment]
Just released it :-)

**Comment by Flohack74** [comment]
Works like a charm. Question, is there a chance to get the twitter social auth also working?

**Comment by nijel** [comment]
That should work without problems, see https://python-social-auth.readthedocs.io/en/latest/backends/twitter.html
