### ISSUE TITLE
Cannot add directionality characters in "Special Characters" list

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#1533]
### Steps to reproduce
1. Add RLM or LRM to the list of Special Characters list in the Preferences
2. Go back to translation mode
3. The toolbar will look like this (I've added both LRM and RLM):
<img width="423" alt="screen shot 2017-06-27 at 10 06 40" src="https://user-images.githubusercontent.com/406826/27574785-5be0083e-5b20-11e7-9968-e4b7896a6a07.png">
(I have some additional characters because there are some characters I can't type with Mac)

### Actual behaviour
There is an additional short button which combines the RLM and LRM characters

### Expected behaviour
In Pootle for example, all the non-printable characters appear as gray [RLM] or [LRM] (I'm not sure but it might be a picture), this allows using non-printable characters more easily.

**Comment by nijel** [comment]
Indeed they have hardcoded these chars for RTL languages: https://github.com/translate/pootle/blob/master/pootle/apps/pootle_store/views.py#L368

Probably we should have something similar.

**Comment by yarons** [comment]
You're awesome! Thank you so much!
Is there a way I can choose which characters do I want to see because I don't need all of them (ZWNJ and ZWJ are not used in Hebrew, mostly in Persian/Arabic and maybe several others).

**Comment by nijel** [comment]
Currently this is not configurable (I've modelled it in similar way as Pootle does it).

**Comment by yarons** [comment]
@nijel do you want me to open another issue for that?

**Comment by nijel** [comment]
Honestly I'm not sure what's best approach, if we can't make the RTL toolbar generally usable, then it's probably better to not provide it at all....

**Comment by yarons** [comment]
Why not making it configurable? We can just add a list to select from these characters. 

Another option would be to parse the special characters field and add these buttons accordingly.

**Comment by nijel** [comment]
Those chars now work fine in special chars setting.

The problem with configuration is that most people won't do that, so we really need good working defaults.

Do you think it's possible to have those controls defined per language? Or is it more translators preference?

**Comment by yarons** [comment]
I'm thinking about adding another option for directionality characters near the custom characters field (First a checkbox for directionality, then when the checkbox is ticked a list will appear allowing the user to select just like when you select languages in the other dialogs allowing Ctrl for multiple selection).

It will be enabled by default for Hebrew, Arabic, Persian, Urdu, Divehi, N'Ko, Syriac etc. but the user will be able to select the desired characters.

Seems legit?

**Comment by nijel** [comment]
Note that user might be translating to more languages, only some of them being RTL (we have such users).

Also I'm always worried of having too much choices..

**Comment by yarons** [comment]
Hmm, so maybe the current way is fine, I'm just thinking about using a smaller font and maybe changing the color to gray. 
This way it won't take so much space. 

Thanks.

**Comment by nijel** [comment]
I've just changed code to place them both on one line, but I think that introducing another button size would make the UI just look worse...
