### ISSUE TITLE
Some keyboard shortcuts are assigned to commands instead of characters

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#1534]
### Steps to reproduce
1. Sometimes I need to add some special type of quotation marks („“), on Mac OS they are produced by typing Shift+D and Alt+C accordingly.
2. While Shift+D works flawlessly I can't type Alt+C because that's the shortcut for the comments section
3. The comments section is focused

### Actual behaviour
The comments section is focused.

### Expected behaviour
The ending quotation should be added to the text.

**Comment by nijel** [comment]
Finding keyboard shortcuts not to collide with system ones is a bit tricky. Do you have any suggestion what to use instead?

**Comment by yarons** [comment]
If the toolbar had non-printable characters support that wouldn't be a problem 😄.

**Comment by nijel** [comment]
Okay, closing as #1533 was fixed.
