### ISSUE TITLE
max-length Quality Check Does Not Affect Allowed Length for TextArea in Template

### ISSUE THREAD

**Issue by pschneider** [WeblateOrg/weblate#1536]
Hi!

### Steps to reproduce
1. Add a max-length:25000 quality check to your component
2. Try to add a translation with more than 10k chars 

### Actual behaviour
- String gets truncated at 10k when pasting in the translation field
- There seems to be no way to add a translation for strings greater than 10k as there is no way to affect the rendered HTML:

```
<textarea class="translation-editor form-control" cols="40" dir="ltr" id="id_7d737f382f698ff3_0" lang="de_AT" maxlength="10000" name="target_0" rows="3" tabindex="100" style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 2454px;">
```

### Expected behaviour

I know this is a rare occurrence and may affect performance but we translate our Terms of Service in Weblate and this is a about 22k char long string. Currently there seems to be no way to affect the allowed `maxlength` attribute for the translation `textarea`.

Maybe it would be good to update the allowed `maxlength` based on the `max-length` quality check (if its greater than 10k) or is there any database limitation because of the used data types?

Related issue where the check was added: #936 

### Server configuration

 * Weblate weblate-2.8
 * Python 2.7.6
 * Django 1.10.6
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0b6
 * Whoosh 2.7.2
 * defusedxml 0.4.1
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.3.3
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.0
 * pytz 2016.3
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 2.8.2
 * Database backends: django.db.backends.mysql

Greetings!

**Comment by nijel** [comment]
Indeed the textarea length limit is currently fixed.

**Comment by pschneider** [comment]
Thank you, @nijel, for confirming this. We separate the string in multiple strings to bypass this restriction for now. :)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
