### ISSUE TITLE
UI improvement proposal: make string to translate more visible

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1537]
Our user has a suggestion:

Is it possible to show text at „Source string comments“ fields in smaller font than at „Source string“ fields in both editing modes (in Zen editing mode, in default mode)? Or at least set some gray color for comments? 
https://lists.opensuse.org/opensuse-translation/2017-06/msg00036.html

I agree with that. On the first look, it is not apparent, which fields are editable, which are important, which are just for translation comfort.

Maybe even extend the idea: also strings in other languages should be smaller, or the string source and string translation emphasized as a most important information.

 * Weblate 2.13.1
 * Python 2.7.13
 * Django 1.10.5
 * six 1.9.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.0
 * defusedxml 0.4.1
 * Git 2.12.3
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.6.1
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2015.2
 * PyYAML 3.11
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
