### ISSUE TITLE
Configuration for GH protected branches?

### ISSUE THREAD

**Issue by Flohack74** [WeblateOrg/weblate#1538]
Hi this is more like a question/discussion item...

my organization wants to use Github´s branch protection, only to prevent accidental merging of PRs by clicking on the shiny green button. But maybe in the future we want to go to using minimum approvals etc.

So I saw that basically there is a possibility to use it with the Hub tool to send the pushes to a separate branch and then create a PR, but this did not work out for me. I still get

```
ERROR ubports/telegram-app: failed to push on repo: remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least one approved review is required by reviewers with write access.
To git@github.com:ubports/telegram-app.git
 ! [remote rejected] master -> master (protected branch hook declined)

```
despite having set the GITHUB_USERNAME and verified that hub works (cloned a repo, had issues with the ssh key but finally resolved it)

How can a debug if the right mode is being used, and just to be curious, does it then create a temporary branch, shall I be able to see that locally?

**Comment by nijel** [comment]
You need to choose GitHub as VCS in the component setup to use hub.

**Comment by Flohack74** [comment]
Hmm I only got Git there *shame* did I overlook this in settings.py?

**Comment by nijel** [comment]
Maybe weblate can not find the hub tool....

**Comment by Flohack74** [comment]
Hmm which path it should be in?

**Comment by Flohack74** [comment]
Forgot to restart, now its there...

**Comment by Flohack74** [comment]
Just to add: in this special case, can I reconfigure to GitHub in the db? Because I want to avoid having to re-create all 4 projects that are already there...

**Comment by nijel** [comment]
It's not possible in the UI, but you can do that from the shell:

```console
$ ./manage.py shell
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from weblate.trans.models import SubProject
>>> sp = SubProject.objects.get(slug='android', project__slug='hello')
>>> sp.vcs = 'github'
>>> sp.save()
```

**Comment by Flohack74** [comment]
Nijel,

I tried this but the behaviour does not change, it still wants to push to master directly. Can it be that it is now confused as the local git repo is already existing, and was not forked properly on the beginning?

Thx BR

**Comment by nijel** [comment]
It really should handle this (I've done this several times and it worked fine). Do you see the GitHub vcs chosen in the admin interface?

**Comment by Flohack74** [comment]
Yes GitHub is show, Is my crontab entry OK for this workflow?

`0 0 * * * . /opt/weblate/bin/activate &&  DJANGO_SETTINGS_MODULE=weblate.settings weblate commit_pending --all && DJANGO_SETTINGS_MODULE=weblate.settings weblate pushgit --all
`

**Comment by nijel** [comment]
That sounds correct (if push on commit is enabled on the project, the second command is not needed).
