### ISSUE TITLE
Password reset prevented on private installations

### ISSUE THREAD

**Issue by timonreinhard** [WeblateOrg/weblate#1540]
### Steps to reproduce
1. Configure `REGISTRATION_OPEN` to be `false`
2. Issue a password reset at `accounts/reset/`

### Actual behaviour
An error message is shown telling the user that new registrations are disabled.

### Expected behaviour
A password reset email is sent.

### Server configuration
 * Weblate weblate-2.15
 * Python 2.7.6
 * Django 1.10
 * six 1.10.0
 * social-auth-core 1.3.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0b7
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.6.0
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.2
 * pytz 2017.2
 * pyuca N/A
 * pyLibravatar N/A
 * tesserocr 2.1.3
 * Mercurial 2.8.2
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
Well, the `REGISTRATION_OPEN = False` was intended for cases where authentication is fully handled externally. You want no registration, but still have password reset, right?

**Comment by timonreinhard** [comment]
Exactly, it's basically an "invite only" system. The password reset worked under this configuration before one of the latest upgrades, that's why I figured this this is a bug.
