### ISSUE TITLE
Status widgets for components

### ISSUE THREAD

**Issue by sikmir** [WeblateOrg/weblate#1541]
For now status widgets are available only for whole project. But if more than one component in the project, it's getting a bit inconvenient. So it would be great to have separate widgets for components within project.

**Comment by nijel** [comment]
Duplicate of #558

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed (see #558). 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
