### ISSUE TITLE
LDAP auth & 2.14 password-related changes

### ISSUE THREAD

**Issue by marcperrin** [WeblateOrg/weblate#1542]
With a LDAP-authenticated user, after update to 2.15 (from 2.13), I've got this message:

"You have not enabled password authentication, please set the password.
You will be still able to authenticate using third party services.
The password is used to verify important changes on your account."

Is that intended? 

It looks like the user can: 
- ignore this message forever 
- or (using blank as current password!) set a new password (from that point, I guess the user goes through regular Weblate auth or LDAP auth depending on the password he uses...) 

Could we just disable the warning in case of third party auth? Or is it really intended to "move users to regular auth"?

**Comment by marcperrin** [comment]
While we're talking about auth/login: I've encountered problems with ENABLE_HTTPS = True & the new example settings about CSRF.

For now I've set CSRF_COOKIE_SECURE = False (instead of = ENABLE_HTTPS) (same thing for SESSION_COOKIE_SECURE) to stop having all logins fail with 403 / CSRF cookie not set...

**Comment by nijel** [comment]
The original intention is to have set password for users using third party auth to allow additional authentication in case of some important action with the account. However this check really should be disabled in case the email auth is not enabled.

**Comment by nijel** [comment]
Hmm, it is actually already done this way. What is your setting for AUTHENTICATION_BACKENDS?

**Comment by marcperrin** [comment]
AUTHENTICATION_BACKENDS = (
    'social_core.backends.email.EmailAuth',
    'django_auth_ldap.backend.LDAPBackend',
    'weblate.accounts.auth.WeblateUserBackend',
)

(I guess I could remove the first line)

**Comment by nijel** [comment]
No, you don't need the EmailAuth at all for this, WeblateUserBackend is good enough for this. EmailAuth is needed for sending email verification and so on. Removing it will make disappear the warning about not set password.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by marcperrin** [comment]
OK great, thx
