### ISSUE TITLE
Display issue on "Other translations" tab

### ISSUE THREAD

**Issue by timonreinhard** [WeblateOrg/weblate#1543]
### Steps to reproduce
1. Enable translation propagation for a project
2. Have same context ids accross components of that project

### Actual behaviour
Oddly distributed UI elements on the "other translations" tab, likely due to a non-consistent use of a `rowspan="2"` attribute.

![Screenshot of the "other translations" tab](http://i.imgur.com/Abq4UPw.png)

### Expected behaviour
Have the items in order as shown in the first two rows.

### Server configuration
 * Weblate weblate-2.15
 * Python 2.7.6
 * Django 1.10
 * six 1.10.0
 * social-auth-core 1.3.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0b7
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.6.0
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.2
 * pytz 2017.2
 * pyuca N/A
 * pyLibravatar N/A
 * tesserocr 2.1.3
 * Mercurial 2.8.2
 * Database backends: django.db.backends.mysql

**Comment by marcperrin** [comment]
NB: on a separate note, we can see a label issue on this screenshot: 

The widgets / zones for: 
1) the other units having the same source (and maybe a different context) 
2) the translations of the current unit in other languages 
are both labeled as "Other translations". 

Even though 2 has a great tooltip, maybe "Other occurrences" would be better for 1 (tooltip could be "Units with the same source")

**Comment by nijel** [comment]
Already fixed in https://github.com/WeblateOrg/weblate/commit/60ad474eefda0b50e428f85876351adae688680f

@marcperrin can you please open separate issues for those?
