### ISSUE TITLE
Deleted strings are not deleted in weblate for Qt *.ts files

### ISSUE THREAD

**Issue by ruslanfedoseenko** [WeblateOrg/weblate#1544]
### Steps to reproduce
1. Upload initial translation
2. Delete a string from translation
3. Pull changes to weblate

### Actual behaviour
Deleted string remains in weblate

### Expected behaviour
Deleted string should be deleted in weblate

### Server configuration
 * Weblate 2.14.1
 * Python 2.7.13
 * Django 1.11.2
 * six 1.10.0
 * social-auth-core 1.3.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.3
 * pytz 2017.2
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.1.3
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Where did you delete the string? What file format are you using?

Maybe our [FAQ](https://docs.weblate.org/en/latest/faq.html#why-does-weblate-still-shows-old-translation-strings-when-i-ve-updated-the-template) does apply?

**Comment by ruslanfedoseenko** [comment]
File format:  Qt *.ts
Seems like i need to change Merge setting for a component. 
Missed this part of docs. Thx for hint.
