### ISSUE TITLE
2 quite different widgets labeled "Other translations"

### ISSUE THREAD

**Issue by marcperrin** [WeblateOrg/weblate#1545]
On the translation page, the widgets / zones for:

1. the other units having the same source (and maybe a different context)
2. the translations of the current unit in other languages
are both labeled as "Other translations" (cf. screenshot on #1543 for example)

Even though 2 has a great tooltip, maybe "Other occurrences" would be better for 1? (tooltip could be "Units with the same source")

**Comment by nijel** [comment]
Indeed the UI is confusing in this case, should be improved.
