### ISSUE TITLE
Login failing with ENABLE_HTTPS & CSRF

### ISSUE THREAD

**Issue by marcperrin** [WeblateOrg/weblate#1546]
I've encountered problems with ENABLE_HTTPS = True & the new example settings about CSRF.

For now I've set CSRF_COOKIE_SECURE = False (instead of = ENABLE_HTTPS) (same thing for SESSION_COOKIE_SECURE) to stop having all logins fail with 403 / "CSRF cookie not set"...

**Comment by nijel** [comment]
Do you have mixed setup allowing both http and https?

**Comment by nijel** [comment]
This *might* be fixed by b3ef507972edfe36c5efd4b79dfc05295b9960c7, can you try adding ``SOCIAL_AUTH_REDIRECT_IS_HTTPS = True`` to your settings?

**Comment by nijel** [comment]
I believe it's same problem as was addressed in b3ef507.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
