### ISSUE TITLE
Consider switching to license AGPL (because GPL doesn't require code to be shared back if run on a server)

### ISSUE THREAD

**Issue by WorldCodeCentral** [WeblateOrg/weblate#1548]
### Steps to reproduce
1. Take a look at the license.
2. Assume the GPL was chosen so code is shared.
3. Wonder how that is supposed to work when the GPL only requires people to share the code with people who run the software locally on their computer. A server doesn't do that. (Exception: Javascript code) GNU.org says this here: https://www.gnu.org/licenses/gpl-faq.html#UnreleasedMods

### Actual behaviour
The GPL doesn't protect against nonlibre forks of Weblate even if run on a public server.

### Expected behaviour
Any fork of this software should only allow public distribution (e.g. a running instance on a server) if the code is shared back to the community.

Hi all,
when thinking about when exactly and how developers are required per the license of this project to share the code when run on a public server, I noticed developers are not actually required by the GPL to share their code. As I understand the GPL it only requires developers to share the code with people they give the software to. Since Weblate usually runs on a server though, no one actually runs the software locally (except Javascript code), so no one is required to share the code. Isn't that why the GPL was chosen for this project though? If you do actually want developers to be required to share their code when they run it on a public server, for that case there is the AGPL: https://www.gnu.org/licenses/why-affero-gpl.html

Please reply if I misunderstood anything. If not, please consider the AGPL so public server providers/ developers are required to share the code.

As always, thanks for this project and the time put into it by everyone who contributed.

**Comment by nijel** [comment]
I was considering AGPL when starting Weblate and I've decided to choose GPL in the end. I've always found AGPL a bit annoying to implement and didn't want to spent time on that.

Relicensing should be AFAIK possible if really needed.

**Comment by WorldCodeCentral** [comment]
Thanks for the reply!

What do you mean by relicensing? You'd be OK with changing the license of the code you have written (which seems to be pretty much all of it) if someone has a convincing reason for using the AGPL instead?

What do you mean by "implementing a license"? Isn't the only thing to do writing down the name of the license somewhere and that's it? Or do you mean it's hard to understand or the terms are more complicated?

I still think Weblate would benefit a lot from the AGPL and it would be frustrating to me if someone ran Weblate on their server but wouldn't share the code back to you! However of course it's your code so feel free to close this issue if you don't want to use the AGPL.

**Comment by nijel** [comment]
AGPL requires the application has to include way to download it's sources. There is [django-agpl](https://chris-lamb.co.uk/projects/django-agpl) which would probably work for us, but I really didn't look at it at all.

GPLv3 we're using is AFAIK compatible with AGPLv3, so it's fine to use GPLv3 code from others while relicensing the code I've written to AGPLv3. 

Still I would need good reason for that. There is always problem with possible patched libraries which this doesn't cover (eg. [Hosted Weblate](https://hosted.weblate.org/) runs patched translate-toolkit and python-social-auth), so the in app download still would be problematic to run elsewhere if it depends on them.

Honestly I think that for everybody running Weblate in the long term is better to give patches back to avoid adjusting them for every release. If somebody wants to keep their patches private, I'm certainly fine with that. If you look at [Weblate forks on GitHub](https://github.com/WeblateOrg/weblate/network) you can see that there are quite a lot of third party forks with patches not submitted upstream...

**Comment by WorldCodeCentral** [comment]
Hello nijel,

django-agpl looks like a useful tool, thanks, but can't the source code be linked to a repository that has the same version in it as well? I read on GNU.org that it's okay to do with GPL'ed programs. So link to the source code of version 14 Weblate for example and translate-toolkit x and python-social-auth y and every requirement is met. However I do see that this can be a hassle to update the link to the sources as well if that's what you mean.

From what I've read I also understood that it's possible to make additions to GPL'ed code and publicise this code under the AGPL. Even new GPL'ed code can be used in already AGPL'ed code, is that correct? "Relicensing" code does not mean the license of the original code changes, only that the new combined work of your code and the additions is available only under that license, right? So in conclusion that means anyone can build upon your work and release it under the AGPL.

Hmm but if it's easier to give patches back to avoid adjusting them for every release, why are there so many forks of Weblate with patches not submitted to upstream?

Thanks again for your time and support!

**Comment by nijel** [comment]
How would you ensure the repository has same version? You can have some local changes and *those* have to be published. Have you actually read the license? See at least [section 13](https://www.gnu.org/licenses/agpl.html#section13).

Honestly I'm not lawyer and I don't want to spend time on discussing what all has to be included in the AGPL source code.

**Comment by WofWca** [comment]
But GPLv3 already requires us to offer the source code for JavaScript. And I would say this requirement is met. I'd say it's fine just linking the repository and stating which version is used (see [section 6(d)](https://www.gnu.org/licenses/agpl-3.0.html#section6) and [FAQ](https://www.gnu.org/licenses/gpl-faq.html#AnonFTPAndSendSources)). Using AGPL would simply add this requirement for the server code as well.

> eg. [Hosted Weblate](https://hosted.weblate.org/) runs patched translate-toolkit and python-social-auth

Or are you saying that those versions' source code is private cannot be made public? Otherwise I don't see a problem.

**Comment by nijel** [comment]
These changes are public, but they were scattered over several pull requests back then.

AGPL compliance would be additional effort for us, and I don't see the real benefits here. Having the source code available doesn't make it magically land in our code base. There are already enough forks on GitHub with unmerged changes.

**Comment by WofWca** [comment]
> These changes are public, but they were scattered over several pull requests back then.

Sorry, but is not specified in `requirements.txt`? If specifying versions as a range is the concern, could `pip freeze` help? I think as long as users can rebuild the same version that is used on the server it's all good. Is this not the case?

> Having the source code available doesn't make it magically land in our code base.

But it allows us to merge them if we find them good. It's what GPL is about.

**Comment by nijel** [comment]
> Sorry, but is not specified in requirements.txt? If specifying versions as a range is the concern, could pip freeze help? I think as long as users can rebuild the same version that is used on the server it's all good. Is this not the case?

Some libraries were installed from a git checkout on our servers, and it has a local branch merging all changes we need. It's definitely not a good practice, but it was done this way. We still occasionally use this for some hotfixes.

> But it allows us to merge them if we find them good. It's what GPL is about.

Still, somebody has to do the work. These changes typically can't be merged as they are (for example, they lack tests and documentation). You typically need author cooperation to merge such changes, and AGPL is not going to persuade people to cooperate more than GPL does.
