### ISSUE TITLE
value to long for type character varying(80)

### ISSUE THREAD

**Issue by JesusZapata** [WeblateOrg/weblate#1549]
### Steps to reproduce
1. I have a repository with long name https://github.com/Vauxoo/runbot_branch_remote_name_grp_feature2/tree/fast-travis-oca
2. I create the project manually using the follow command 

```
django-admin shell -c "import weblate.trans.models.project as project; project.Project(name='github.com:vauxoo-dev/runbot_branch_remote_name_grp_feature2 (fast-travis-oca)', slug='github_com_vauxoo-dev_runbot_runbot_branch_remote_name_grp_feature2_fast-travis-oca', web='github.com/vauxoo-dev/runbot_branch_remote_name_grp_feature2').save()"
```
3. The project was created well bud the console show the follow messages
![image](https://user-images.githubusercontent.com/1387970/27971035-339e656c-631f-11e7-9909-a6fa3631836b.png)

### Actual behaviour
Error when the name of the project has more of 80 character

### Expected behaviour
Support name of project long I think what 160 character is enough

### Server configuration
Please paste the output of command `./manage.py list_versions` over here
![image](https://user-images.githubusercontent.com/1387970/27973541-56a5d08c-6328-11e7-8fb1-aefa7dce97a1.png)

**Comment by JesusZapata** [comment]
@nijel 
Could do you help me with this issue? 
Maybe could you show me in which file is created that field in order to create the pull request

**Comment by nijel** [comment]
The maximal length for name has been 100 since beginning (a6e27df223). But it seems to be caused by permissions code, where the [group name length is indeed limited to 80](https://github.com/django/django/blob/master/django/contrib/auth/models.py#L111).

**Comment by nijel** [comment]
Can't you just use something more reasonable as project name?

In any case either Weblate should allow this or reject it when creating project. As I currently do not see any easy workaround of the Group name limitation, we will probably impose limits on project name...

**Comment by JesusZapata** [comment]
Ok, thanks
I'll make the name more short to my project

**Comment by nijel** [comment]
I'll keep this open as we at least should fix discrepancy between project and group length limits.
