### ISSUE TITLE
Clone repository using user:TOKEN

### ISSUE THREAD

**Issue by JesusZapata** [WeblateOrg/weblate#1552]
### Steps to reproduce
1. Delete permission of access to VCS repository to the user anonymus
2. Create another `cloner` used and add permission to access to VCS repository
3. Try to clone the repository using the another user `cloner` and using the token of this user

### Actual behaviour
`git clone 'http://cloner:TOKEN@example.com:2424/git/project/sub_project/'`

Pay attention to the host has a port number

When the request is made the user found is `WeblateAnonymousUser: anonymous`
![image](https://user-images.githubusercontent.com/1387970/28074631-0dc0091c-6627-11e7-81f0-b2faedc034df.png)

### Expected behaviour
Run the clone using the user permission cloner

### Server configuration
 * Weblate 2.14.1
 * Python 2.7.13
 * Django 1.11.2
 * six 1.10.0
 * social-auth-core 1.3.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.3
 * pytz 2017.2
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.1.3
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by JesusZapata** [comment]
@nijel 
Could do you help me whith this issue ?

**Comment by nijel** [comment]
Apparently some of the recent hardening went too far...

**Comment by JesusZapata** [comment]
@nijel 
Thanks for you fixes

I apply this [patch](https://github.com/WeblateOrg/weblate/commit/69fb0527e5b418e476fb0594d61e011e31181d53) over my weblate code, but this not fixes my trouble.
I need apply another patch ?

**Comment by nijel** [comment]
Are you using the Django built in server or some web server in front? If you're using web server, you might have to configure it to pass headers (eg. WSGIPassAuthorization for Apache WSGI).
