### ISSUE TITLE
hook-merge-pot-in-po does not work

### ISSUE THREAD

**Issue by gilbsgilbs** [WeblateOrg/weblate#1553]
Yeah, I know, I've written [this](https://github.com/WeblateOrg/weblate/blob/weblate-2.15/examples/hook-merge-pot-in-po) a few months ago, but it cannot work since it expects to be called multiple times with the `.po` file as argument. This is [not going to happen](https://github.com/WeblateOrg/weblate/blob/701d8f420ed356ab65a36ab6ed3da8871c9bee3f/weblate/trans/scripts.py#L32) in `post_update` scripts.

I don't know what to do exactly. Correct me if I'm wrong, but I don't think we can handle the general in a `post_update` scripts currently, unfortunately. We may want to remove this hook, but lacking from such a script out of the box obviously makes things a lot more complicated.

**Comment by gilbsgilbs** [comment]
One other possibility would be something like this (I think it will work in my case):
```bash
#!/bin/sh
# Post-update hook to merge POT translations into PO.
# Requires gettext.

[ -z "${WL_NEW_BASE}" -o -z "${WL_FILEMASK} ] && exit 0
find . -path "*/${WL_FILEMASK}" -exec msgmerge -U "{}" "${WL_NEW_BASE}" \;
exit $?
```

What do you think?

**Comment by nijel** [comment]
For the long term the solution will be addons doing such things properly in Weblate (see https://github.com/WeblateOrg/weblate/issues/1353).

As for suggested change, IMHO the * in the find is not necessary, this should work:

```
find . -path "${WL_FILEMASK}" -exec msgmerge -U "{}" "${WL_NEW_BASE}" \;
```

**Comment by gilbsgilbs** [comment]
@nijel Yep. Definitely can't wait for #1353 which will greatly enhance Weblate continuous translation possibilities.

I've always used `-path` with `*/` prefix without wondering, and after a quick test on my machine, it doesn't work when it's missing. It seems to match the path as returned by `find` command which seems always prefixed by `./` when base path is `.`. We might replace `*/` with `./` though 🤔 . `*/` prefix is really common, but I'm unsure whether it's a best practice or not.

**Comment by nijel** [comment]
Good point with ./, it's indeed needed. Will you please submit PR with the fix?

**Comment by gilbsgilbs** [comment]
@nijel I can submit the PR, but keep I won't be able to test it before monday. So be sure it works :) .
