### ISSUE TITLE
Weird Plural Forms behaviour

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#1554]
In Hosted Weblate I came across the following behaviour (Take a closer look at the plural equation):
<img width="971" alt="screen shot 2017-07-13 at 13 43 13" src="https://user-images.githubusercontent.com/406826/28162883-759b921c-67d1-11e7-8f2f-93c99f18b42e.png">

But in the Nearby Messages list I can see a different setting (As if there are more Plural Forms):
<img width="966" alt="screen shot 2017-07-13 at 13 43 25" src="https://user-images.githubusercontent.com/406826/28162921-a6b5c70a-67d1-11e7-949e-a57ece173fbc.png">

This is the link to the exact location of this string:
https://hosted.weblate.org/translate/f-droid/f-droid/he/?checksum=92b5ad4ed87c9305

It happens with several other strings with Plural Forms.

Kind regards,
Yaron Shahrabani.

**Comment by nijel** [comment]
Probably this is different incarnation of https://github.com/WeblateOrg/weblate/issues/1550 (in the other direction).

**Comment by yarons** [comment]
Possibly… Is there a way I can help debug that?
