### ISSUE TITLE
Feature request: Custom Plural forms

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#1555]
I'll start by presenting the lingual necessity and move on to the technical details:

# Lingual
In Hebrew there are special cases where more than 2 plural forms are needed, mostly when the terms are time related, first we'll see the regular form and then the expanded plural form requirement -

- One **house** - **בית** אחד (**Bait** Ekhad)
- Two **houses** - שני **בתים** (Shney **Batim**)
- Three **houses** - שלושה **בתים** (Shlosha **Batim**)

Here we can see a change in position between the singular and plural and also a change in the plural definition of House, the words in bold are all nouns.

Let's look at a similar example but this time with years -

- One **year** - **שנה** אחת (**Shana** Akhat)
- Two **years** - שנתיים (Shnatayim)
- Three **years** - שלוש **שנים** (Shalosh Shania)

As you can see in this example the 2nd line is an exception, the dual form is incorporated within the word year while affecting the word itself.

# Technical
In order to predefine an exception we need to have a method to uniquely identify strings so we can keep the special Plural Forms formula for this string specifically.
This is where the Portable Object (PO) by GNU is lacking, there is no way to uniquely identify strings this we have to declare a default for the document and we must follow this formula throughout the entire document regardless of the noun or lingual necessity.

Few of the formats that allow us to break the Plural Forms rules are: Android Strings XML, XLIFF and L20n by Mozilla.

Part of this change was not only to change the Plural Forms on the file but also to create a method to specifically assign a gender to a string, this is especially important for platforms such as Facebook which incorporated Gender and Quantity definition for several cases:

- {name} got {number} new cats

So we ask the translator question about the different possible variations of the string, we have some general questions such as:

- Does the gender matter according to the Subject?
    - If the subject I'm talking about might differ in terms of gender.
    - Example: Added by you.
       - Subject is male - Nosaf Al Yadekha
       - Subject is female - Nosfa Al Yadekha
- Does it matter who this message is aimed at?
    - Who is reading the string? Should it change accordingly?
    - Example: Welcome
       - To a Male - Barukh Haba!
       - To a Female - Brukha Haba'a!

Now we can ask the translator about the variations according to the arguments:
- {name}: will the form of the sentence change if it's a male? female? gender neutral?
- {number}: will the quantity affect the form of the sentence?

In Facebook there's a very simple interface allowing you to break the string into conditional destination strings according to a unique specification based on the identification of the source string.

The only problem I can think of is that if we'll need to save the file to PO than the structure will flatten or all the simple Plural Forms will expand and cause a major headache for the translator, another option could be that if the translator has expanded the Plural Forms there will be no option to export to PO.

Hoping that was clear enough.

Thanks.

**Comment by nijel** [comment]
I think this is (again) pretty much same issue as https://github.com/WeblateOrg/weblate/issues/1550...

**Comment by yarons** [comment]
Looks similar, in XLIFF there's also gender fields so it's a little different after all.

**Comment by nijel** [comment]
L20n has quite complex expression language and I don't think we will ever support this completely. For XLIFF the gender choice AFAIK has to be defined in the file, so it's nothing you could add afterwards. The same applies for plurals - you can use whatever is supported by the format (eg, stick with CLDR for Android Strings, or what matches the plural formula as defined in Gettext PO), AFAIK none of them allows to specify this per string. I really don't see need to provide more fine grained support in Weblate as there is probably the only file format which can utilize this (L20n) and that is currently not supported by Weblate anyway (and nobody requested that so far).

**Comment by yarons** [comment]
IIRC in XLIFF you can define the gender and plural form on a string basis.

**Comment by nijel** [comment]
Can you point to some reference about that? All XLIFF files I've seen so far defined no plural rules at all and Googling really doesn't show anything useful on this topic...

**Comment by nschonni** [comment]
http://docs.oasis-open.org/xliff/v1.2/xliff-profile-po/xliff-profile-po-1.2-cd02.html#s.detailed_mapping.tu.plural

**Comment by nijel** [comment]
The XLIFF 1.2 relies on Gettext, so uses plural form defined in x-gettext-domain-header, so it's per file not per string.

The XLIFF 2.0 thing is state: under-evaluation and doesn't (yet) have a specification...
