### ISSUE TITLE
"Source string location" doesn't handle long strings well.

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1557]
### Steps to reproduce
1. Set up a component where files have long pathnames.
2. Browse to translate window.

### Actual behaviour
Strings don't fit, looks pretty ugly. Screenshot attached.

### Expected behaviour
Should look prettier. Break lines? Horizontal scroll? Or maybe hide a part of the line that doesn't fit, and show full path as tooltip on hover?

### Server configuration
```
 * Weblate weblate-2.15
 * Python 2.7.5
 * Django 1.10.3
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.13.2
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.6.4
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2016.7
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.0
 * Database backends: django.db.backends.mysql
```
<img width="452" alt="screen shot 2017-07-16 at 1 51 50 pm" src="https://user-images.githubusercontent.com/1279852/28245356-cf602dd0-6a2e-11e7-910a-3e9bf2cb78c0.png">

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
