### ISSUE TITLE
"ignore-same" not applied retroactively

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1560]
### Steps to reproduce
1. Import a component which has some strings equal to to translations
2. Set "ignore-same" flag in component settings.

### Actual behaviour
"Source and translated strings are same" string are still displayed as failing checks in component window.
Also, see attached screenshot for an example.

### Expected behaviour
Once the flag is set, the corresponding check should be disabled and corresponding strings not listed as failing checks.

### Server configuration
```
 * Weblate weblate-2.15
 * Python 2.7.5
 * Django 1.10.3
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.13.2
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.6.4
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2016.7
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.0
 * Database backends: django.db.backends.mysql
```

<img width="1172" alt="screen shot 2017-07-18 at 3 15 26 am" src="https://user-images.githubusercontent.com/1279852/28287881-6ecd81cc-6b67-11e7-9082-c8bbdb8ba7b1.png">

**Comment by nijel** [comment]
Actually none of the per component flags are not recalculated when changing component settings.

**Comment by burner1024** [comment]
Actually, I just found there's an "Update quality checks" action in components windows.
I have tried it, and it seems to work... somewhat.

I use Redis for cache. After doing "Update quality checks", nothing seemingly changed. Then I flushed Redis, and number of "Source and translated strings are same" reduced **but did not become zero**. As I flush and refresh page again, it reduces again. Hopefully this is fixed with #1561.

Arguably, if there's a possibility to update quality checks after all, this issue might be considered not a bug. Still, I'm not sure if the current way it works makes much sense.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by jnavila** [comment]
Hi,

Is the "Update quality checks" action available on open source hosted WebLate website? We're using a script to automatically copy untranslatable strings and mark them `ignore-same`, but this is not reflected in WebLate.

**Comment by nijel** [comment]
@jnavila The is no manual action for that, it should be updated automatically on flag change. Can you please point me to the string where it did not work? Please do that in separate issue though as this one was about changing the flags component level, while you apparently do that per unit or source string.
