### ISSUE TITLE
support XLIFF's maxwidth parameter

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#1562]
The XLIFF format allows char limits to be set per-string.  It would be very helpful if Weblate automatically used these (i.e. converted them to `max-length:80` checks).  Here's an example from
https://hosted.weblate.org/projects/f-droid/fdroiddata/

```xml
      <trans-unit id="com.google.zxing.client.android-summary" maxwidth="80" size-unit="char">
        <note from="developer">This is limited by Google to 80 characters</note>
        <source>Scan barcodes on products, or barcodes containing URLs, contact info, and so on</source>
        <target>Scan barcodes on products, or barcodes containing URLs, contact info, and so on</target>
      </trans-unit>
```

**Comment by nijel** [comment]
Just revisiting this and maxwidth in [xliff specification](http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#maxwidth) is by default in *pixels*. As Weblate supports this as well, the parser will be adjusted to follow xliff specification.
