### ISSUE TITLE
Unnecessary precision

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#1564]
The "Untranslated" column has many decimal places after the dot, I think 1 is enough, correct me if I'm wrong: 
<img width="773" alt="screen shot 2017-07-18 at 19 35 07" src="https://user-images.githubusercontent.com/406826/28328819-68253926-6bf0-11e7-8516-30786a7211b0.png">

**Comment by nijel** [comment]
This is really not intentional, where is it shown?

**Comment by yarons** [comment]
elementary OS' weblate instance.

**Comment by yarons** [comment]
Thanks a lot! I'll ask them to upgrade.

**Comment by nijel** [comment]
Apparently running Weblate on Python 3 has some minor glitches which nobody reported so far.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
