### ISSUE TITLE
Special characters has some additional characters

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#1565]
I was clicking on some sort of Quotation mark in the special characters toolbar and instead of getting the character I wanted („) I got: b'„'

Discovered in the [elementary OS instance](https://l10n.elementary.io/), doesn't happen in Hosted Weblate.

**Comment by nijel** [comment]
Might be caused by Python 3 they are using...

**Comment by yarons** [comment]
You're awesome, thank you!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
