### ISSUE TITLE
gettext monolingual files are all marked as "to check", multilingual are right, but are generated in multiline

### ISSUE THREAD

**Issue by anj4u** [WeblateOrg/weblate#1566]
### Steps to reproduce

1.  Use po file with this format:

`# Header information line x`
`# Header information line x`
`# Header information line x`
`# Header information line x`
`msgid ""`
`msgstr ""`
`"Project-Id-Version: my project\n"`
`"Report-Msgid-Bugs-To: developer@project.de\n"`
`"POT-Creation-Date: 2009-11-12 16:00+0100\n"`
`"PO-Revision-Date: 2009-11-12 17:00+0100\n"`
`"Last-Translator: User <info@project.de>\n"`
`"Language-Team: Team\n"`
`"MIME-Version: 1.0\n"`
`"Content-Type: text/plain; charset=UTF-8\n"`
`"Content-Transfer-Encoding: 8bit\n"`
`"X-Poedit-SourceCharset: utf-8\n"`

`#: /path/to/file.php`
`msgid "globals.Action.error.sort"`
`msgstr "Fehler beim Sortieren."`

2. Set the component as gettext monolingual, using github, 
3. No statistics are shown in language overview (all keys are to review) and the origin key is shown wrong in root language.
4. Export (generation of file) is single line -> THATS WANTED!

### Actual behaviour
Actually I have 2 ways I try:

1) No statistics are shown in language overview (all keys are to review) for monolingual gettext, BUT the export of the .po file is RIGHT for me (single line)

2) Statistics are shown in language overview (all is right) for gettext (multilingual) gettext, BUT the export of the .po file is WRON for me (multi line).

In our development we use only single line translations. So is there any option to force single line in multilingual gettext, or is our format of the file wrong?

### Expected behaviour
Normal statistics for the languages, export in single line of .po files.

### Server configuration
* Weblate weblate-2.15-118-gdcf9c7d
 * Python 2.7.5
 * Django 1.11.3
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.3
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 1.8.3.1
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.2.1
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.3
 * pytz 2017.2
 * PyYAML 3.10
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
What is your component settings? Especially monolingual base language file. Does it contain English strings?

**Comment by anj4u** [comment]
Hi nijel,

the monolingual base language setting is: "lang/po/de_DE.po" and has as msgid always a generic string like "globals.admin.XXX" or "models.User.xxx" and the msgstr is in german, because our development sets as initial language these keys.

**Comment by nijel** [comment]
Well then it looks pretty much as expected. Maybe I'm missing what is actually a problem here...
