### ISSUE TITLE
Suggestions of a user are not always shown

### ISSUE THREAD

**Issue by tuxayo** [WeblateOrg/weblate#1568]
### Steps to reproduce
1. Go to https://hosted.weblate.org/user/tuxayo/
2. See that there should be 2 suggestions (if no one has accepted them in the mean time)
3. Go https://hosted.weblate.org/user/tuxayo/
4. See that the list is empty

I'm not sure if that should have been reported in the instance contact page instead of here.

### Actual behaviour
4: The list is empty

### Expected behaviour
4: The list should has a shown a number of item matching what has been seem in step 2

**Comment by nijel** [comment]
I guess the second URL should be https://hosted.weblate.org/user/tuxayo/suggestions/, rigtht?

**Comment by tuxayo** [comment]
> I guess the second URL should be https://hosted.weblate.org/user/tuxayo/suggestions/, right?

Yes indeed, I've fixed the link.

> Anyway it's just the UI a bit confusing - it's number of suggestions ever made, but the next page shows only pending ones...

Oh, that's why now there is one!

**Comment by tuxayo** [comment]
By the way, when I see the timeline for

- this bug report 21:46 CEST

- your commit 22:01 CEST

- the translation in french by @ldmpub 22:16 CEST

I'm just amazed by both of you :-D

**Comment by ldmpub** [comment]
It's just because Weblate notification system is sooo powerfull and the Weblate webapplication interface is perfectly clean that translations can be quickly and efficient done ;-).
