### ISSUE TITLE
Add source string to history page (somewhere)

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#1569]
Hi,

As an experienced weblate translator, I have 3 little improvements requests on the History page, here is the first one:
Add the "source string" to check quickly if the translation done is aligned or not (it can be a new column or a tooltip on the first column).

![weblate current history page](https://user-images.githubusercontent.com/1452146/28389521-c0e996d8-6cd6-11e7-967b-2c102aeb59dc.png)

Best regards,

**Comment by ldmpub** [comment]
Hi,

Thanks for this improvement.

I'm not sure to understand it correctly because it looks like now "Source string changes are displayed in translation history if string was already translated".

My initial request was to have the "full source string" displayed in the history to perform a quick check if the translation is aligned with the source string meaning.
Yet I see only 2 ways to have this info (and none is nice): access to the details of the strings (with "+" symbol) or subscribe to the translation and monitor my mails where both source and translated strings are available.

Hope its clear, waiting for your explainations,

**Comment by nijel** [comment]
Okay, I probably misunderstood the issue or confused it with another one.

**Comment by ldmpub** [comment]
Thanks Michal, the new history layout is exactly what I need.

**Comment by ce-4** [comment]
Hi Weblate devs,

I was about to file a bugreport for a similar request and just found this commit.
My feature request is however a bit different, it involves direct jumping in the browser history:
--------------
I often use the Browser's long-press/back-button to quickly navigate back between page history and would welcome if this could be used to quickly spot a specific string to streamline to identical style (e.g. in OsmAnd there's a number of petrol quality types 89/90/92/98 Octane). If you long-press Firefox' back button you can immediately jump back/forth between the 15 last visited pages.

It would be nice to see the actual source tag context in the page title so one could quickly pick the right string to edit (if this is feasible).
--------------

Would this be a meaningful addition?

Thanks & best regards,
Christian

**Comment by nijel** [comment]
Please file a separate issue for that.
