### ISSUE TITLE
Better display of changes

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#1570]
After request #1569:

Still in the history page, new translation strings are quite hard to check/read (changed introduced maybe 6 months ago): merge of colors (red for removed characters ...) and font style (strikes for removed characters ...).

I suggest to add an option to switch between 2 display styles for the new translations, depending on user preferences.

Proposed named for this option: "Display mode for the translated strings" (in history page and / or email notifications).
Values could be "Highlight changes" or "Raw display (no change highlighted)".
Maybe the same should apply in the mail notifications.

This option can be set globally in the user profil.

Thanks,

**Comment by nijel** [comment]
There is also https://github.com/WeblateOrg/weblate/issues/1031 to add another view of changes...

**Comment by ldmpub** [comment]
Hi, I'm back on this issue because a newcomer has made a lot of changes in french translation of WebLate yesterday and, with the current history view, it's hard to judge each change (is it an improvement or the new translation is worst?).

Here are some inputs:

- I agree with #1031 that current system to mix old string value and new string value in the same line with color and font highlights is not that easy to "read"
- I confirm that mail content is far better with 2 lines. 1st line: new value for the string, 2d line: mix of the old an new value.

Questions:
Can we add this "2 line display" by default in the History page? Should the display be customizable at user level? If so, where this option should be "toggled" (in Profile or in the history view itself)?

Waiting for your feedback,

**Comment by ldmpub** [comment]
Hi,

Happy new year to all.

Is there anything planned to improve this display and make the new translated sentences more easy to read? (option to get ride of the changes highlights).

**Comment by nijel** [comment]
Currently this is not scheduled for next milestone.

**Comment by ldmpub** [comment]
Hi, any update on this request or on #1031?

It would be really great if translators can easily read / check the "full final translated string" in the History view. Yet I need to open the string in a new tab to check its last value ;-().

**Comment by ldmpub** [comment]
This request was not very important when strings were translated for the first time. But when translators are improving existing translations both in notification emails and in the web interface, it's very hard to check / read the "real" string which will be displayed to user in the final translated app. See for instance https://hosted.weblate.org/projects/weblate/master/fr/#history or more precisely https://hosted.weblate.org/translate/weblate/master/fr/?checksum=180be3aa20b3d107

A short suggestion to solve this issue in the Web interface: add a pop-up and display the "natural" string when pointing mouse on the current "unreadable difference string" mixing red / green and strike through text ;-).

I hope this request is now strongly motivated and my "little" proposal is clear enough to catch your attention.

**Comment by ldmpub** [comment]
Hi,

This improvement becomes more and more important because we are several translators and it's very very hard to understand changes done. See an other example: https://hosted.weblate.org/translate/weblate/master/fr/?checksum=8d36677a0ae5c9bd
Change can have be done because source string has changed or because translators have different approaches ... but the issue / question remains the same: **how to read the sentence history in "clear" text?**

Hope to have been heard at last ;-)

**Comment by nijel** [comment]
Hopefully this will be addressed by https://github.com/WeblateOrg/weblate/pull/2466, feedback welcome.

**Comment by nijel** [comment]
You can try the diff rendering here: https://neil.fraser.name/software/diff_match_patch/demos/diff.html It uses same engine and default settings match what I've done in #2466. Most likely it will be on Hosted Weblate this week...

**Comment by ldmpub** [comment]
It looks a little bit more "readable" but still far from my initial request: **to be able to view the true current translations (a kind of "raw" mode to display the real strings without any changes highlighted)**.
It's particularly important in pages like this one (history for a random language):  https://hosted.weblate.org/projects/osmand/main/be/#history to quickly check the "final" translations strings.

Waiting for you arguments,

**Comment by nijel** [comment]
So what you actually want is more like https://github.com/WeblateOrg/weblate/issues/1031

**Comment by ldmpub** [comment]
I'm really surprised: how can you close a 1 year 1/2 issue which is yet my only concern with Weblate this way ;-( ?

I will try to give my point of view / ideas on the issue you point me to #1031 (issue I already knew and where I've made a link to this one).

**Comment by nijel** [comment]
I understood this issue is about showing changes in more readable way, what the change does. If it's about showing original and diff, then there is already another issue on that topic (#1031) and I don't see point in having two issues for one feature.

**Comment by ldmpub** [comment]
Let me correct you: the issue is not about showing changes, but is 100% **about showing the new / last value of the translated string** => ie displaying strings like they will be shown to an "end user" when he will use the translated app / website ... Is it more clear?

Let's see what your improvement will add and maybe a 2 lines display like suggested in the old #1031 could do the job?

**Comment by nijel** [comment]
This issue is about showing changes, because you are looking at the changes. Still main reason for this view is to be able to show the changes in the translations. It might be shown in two line mode as described in #1031 at some point. Right now I've focused on improving the diff rendering so that it better handles bigger changes in the strings - the original code was really bad in that.

Maybe what you actually want is the review search to look at current value of recently changed strings (see e.g. https://hosted.weblate.org/projects/osmand/main/be/#search).

**Comment by nijel** [comment]
I've made separate issue for that as this is quite different from what was originally described here. See https://github.com/WeblateOrg/weblate/issues/2468
