### ISSUE TITLE
Adjust history layout to better indicate individual entries

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#1571]
Following requests #1569 and #1570, here is my last remark to improve the history page...

Yet the History page layout is a merge of table and paragraph. It's not clear which"History line" (for instance: "X minutes ago") goes with which translation: the above translation or the below translation?

Maybe this very little issue could be addressed by removing lines breaks or by adding a little graphical outline (square around linked elements, alternative background colors for lines which are going "together", ...).

What do you think?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by ldmpub** [comment]
Thanks for the quick improvement!

It's better but it's not perfect because the changes made to the translation strings are always displayed within a "big" and white background ... which breaks the alternate backgrounds layout you have introduced => the History page is still quite hard to read.

Grouping date + changes with little height line breaks and separate one change with an other with bigger line breaks can be a solution or change rectangle around entries or removing the white background for translations (the existing one described above).

Regards,

PS: my donation to Weblate project is giving my time and energy to translate this tools in french for free ;-). It's really a great great tool (far far better than Transifex, Crowdin, getLocalization ...)!

**Comment by nijel** [comment]
I've just removed the background (in Git, it will get deployed later today).

**Comment by ldmpub** [comment]
Checked and now the history display is much easy to read. Thanks!

The last disturbing point is the fact that some events are made of 2 lines and other events are made only of 1 line => the History display is "irregular" but yet this could be an harder job to refactor events logs ;-(.

For now (and for me) the display is not perfect but is far better.

**Comment by nijel** [comment]
I don't think this is going to change - there are events with no additional data to show in the second line...
