### ISSUE TITLE
Weblate crashes when deleting a component

### ISSUE THREAD

**Issue by aidik** [WeblateOrg/weblate#1575]
### Steps to reproduce
1. Delete component using Django administration page

### Actual behaviour
Traceback 

Environment:

Request Method: GET
Request URL: http://weblate.trueos.org/admin/trans/subproject/87/delete/

Django Version: 1.10.1
Python Version: 2.7.12
Installed Applications:
(u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.sessions',
 u'django.contrib.sites',
 u'django.contrib.messages',
 u'django.contrib.staticfiles',
 u'django.contrib.admin',
 u'django.contrib.admindocs',
 u'django.contrib.sitemaps',
 u'social_django',
 u'crispy_forms',
 u'compressor',
 u'rest_framework',
 u'rest_framework.authtoken',
 u'weblate.trans',
 u'weblate.lang',
 u'weblate.permissions',
 u'weblate.screenshots',
 u'weblate.accounts',
 u'weblate.utils',
 u'weblate')
Installed Middleware:
(u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.locale.LocaleMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'weblate.accounts.middleware.AuthenticationMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'django.middleware.clickjacking.XFrameOptionsMiddleware',
 u'social_django.middleware.SocialAuthExceptionMiddleware',
 u'weblate.accounts.middleware.RequireLoginMiddleware')

Traceback:

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/contrib/admin/options.py" in wrapper
  544.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/contrib/admin/sites.py" in inner
  211.             return view(request, *args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/contrib/admin/options.py" in delete_view
  1709.             [obj], opts, request.user, self.admin_site, using)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/contrib/admin/utils.py" in get_deleted_objects
  128.     collector.collect(objs)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/contrib/admin/utils.py" in collect
  193.             return super(NestedObjects, self).collect(objs, source_attr=source_attr, **kwargs)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/db/models/deletion.py" in collect
  222.                     elif sub_objs:

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/db/models/query.py" in __nonzero__
  264.         return type(self).__bool__(self)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/db/models/query.py" in __bool__
  260.         self._fetch_all()

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/db/models/query.py" in _fetch_all
  1087.             self._result_cache = list(self.iterator())

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/db/models/query.py" in __iter__
  54.         results = compiler.execute_sql()

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/db/models/sql/compiler.py" in execute_sql
  835.             cursor.execute(sql, params)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/db/backends/utils.py" in execute
  79.             return super(CursorDebugWrapper, self).execute(sql, params)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/db/utils.py" in __exit__
  94.                 six.reraise(dj_exc_type, dj_exc_value, traceback)

File "/usr/local/lib/python2.7/site-packages/Django-1.10.1-py2.7.egg/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /admin/trans/subproject/87/delete/
Exception Value: relation "trans_groupacl" does not exist
LINE 1: ...nguage_regex", "trans_subproject"."priority" FROM "trans_gro...
                                                             ^

### Expected behavior
Remove component.

### Server configuration
 * Weblate weblate-2.13
 * Python 2.7.12
 * Django 1.10.1
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0
 * Translate Toolkit 2.0.0b7
 * Whoosh 2.7.0
 * defusedxml 0.4.1
 * Git 2.9.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.0
 * lxml 3.6.0
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.4.0
 * pytz 2016.4
 * Database backends: django.db.backends.postgresql_psycopg2

accounts
 [X] 0001_initial
 [X] 0002_auto_20140923_1543
 [X] 0003_auto_20141104_1159
 [X] 0004_auto_20150108_1424
 [X] 0005_auto_20150330_1358
 [X] 0006_profile_hide_completed
 [X] 0007_auto_20150427_1505
 [X] 0008_profile_hide_source_secondary
 [X] 0009_auto_20150630_1213
 [X] 0010_auto_20150819_1457
 [X] 0011_auto_20150916_0952
 [X] 0012_auto_20151112_0738
 [X] 0013_auto_20151222_1006
 [X] 0014_auto_20160302_1025
 [X] 0015_auto_20160304_1418
 [X] 0016_add-api-keys
 [X] 0017_anonymous_profile
 [X] 0018_autogroup_users
 [X] 0019_auto_20160520_1358
 [X] 0020_remove_projects_dashboard
 [X] 0021_auto_20160520_1401
 [X] 0022_auto_20160520_1434
 [X] 0023_auto_20161021_1502
 [X] 0024_auto_20161024_0902
 [X] 0025_auto_20170211_1609
 [X] 0026_profile_special_chars
 [X] 0027_auto_20170317_1441
 [X] 0028_auto_20170323_0838
admin
 [X] 0001_initial
 [X] 0002_logentry_remove_auto_add
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
authtoken
 [X] 0001_initial
 [X] 0002_auto_20160226_1747
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
lang
 [X] 0001_initial
 [X] 0002_auto_20150630_1208
 [X] 0003_auto_20160721_0849
 [X] 0004_auto_20161222_1459
permissions
 [X] 0001_initial
 [X] 0002_auto_20170317_1123
 [X] 0003_autogroup
 [X] 0004_auto_20170317_1430
 [X] 0005_groupacl_permissions
 [X] 0006_auto_20170404_1637
screenshots
 [X] 0001_initial
 [X] 0002_auto_20170215_0849
 [X] 0003_auto_20170215_1633
sessions
 [X] 0001_initial
sites
 [X] 0001_initial
 [X] 0002_alter_domain_unique
social_django
 [X] 0001_initial (2 squashed migrations)
 [X] 0002_add_related_name (2 squashed migrations)
 [X] 0003_alter_email_max_length (2 squashed migrations)
 [X] 0004_auto_20160423_0400 (2 squashed migrations)
 [X] 0005_auto_20160727_2333 (1 squashed migrations)
 [X] 0006_partial
trans
 [X] 0001_initial
 [X] 0002_auto_20141021_1347
 [X] 0003_auto_20141021_1348
 [X] 0004_auto_20141021_1550
 [X] 0005_auto_20141021_1550
 [X] 0006_auto_20141021_1609
 [X] 0007_auto_20141022_1159
 [X] 0008_auto_20141104_1200
 [X] 0009_auto_20141110_1501
 [X] 0010_source_check_flags
 [X] 0011_auto_20141114_1008
 [X] 0012_translation_have_comment
 [X] 0013_auto_20141124_1036
 [X] 0014_auto_20141202_1101
 [X] 0015_auto_20141203_1345
 [X] 0016_auto_20141208_1029
 [X] 0017_auto_20150108_1424
 [X] 0018_auto_20150213_1447
 [X] 0019_auto_20150220_1354
 [X] 0020_auto_20150220_1356
 [X] 0021_auto_20150306_1605
 [X] 0022_auto_20150309_0932
 [X] 0023_project_owner
 [X] 0024_subproject_edit_template
 [X] 0025_subproject_post_update_script
 [X] 0026_auto_20150401_1029
 [X] 0027_auto_20150401_1030
 [X] 0028_auto_20150402_1430
 [X] 0029_auto_20150415_1318
 [X] 0030_change_subproject
 [X] 0031_auto_20150415_1339
 [X] 0032_subproject_agreement
 [X] 0033_auto_20150618_1138
 [X] 0034_auto_20150618_1140
 [X] 0035_auto_20150630_1208
 [X] 0036_auto_20150709_1005
 [X] 0037_auto_20150810_1348
 [X] 0038_auto_20150810_1354
 [X] 0039_remove_project_owner
 [X] 0040_auto_20150818_1643
 [X] 0041_auto_20150819_1457
 [X] 0042_auto_20150910_0854
 [X] 0043_auto_20150910_0909
 [X] 0044_auto_20150916_0952
 [X] 0045_auto_20150916_1007
 [X] 0046_auto_20151111_1456
 [X] 0047_project_source_language
 [X] 0048_auto_20151120_1306
 [X] 0049_auto_20151222_0949
 [X] 0050_auto_20151222_1006
 [X] 0051_auto_20151222_1059
 [X] 0052_install_group_acl
 [X] 0053_auto_20160202_1145
 [X] 0054_auto_20160202_1219
 [X] 0055_auto_20160202_1221
 [X] 0056_auto_20160202_1224
 [X] 0057_indexupdate_language_code
 [X] 0058_componentlist
 [X] 0059_auto_20160303_0934
 [X] 0060_auto_20160310_0950
 [X] 0061_auto_20160404_1841
 [X] 0062_auto_20160419_1429
 [X] 0063_whiteboardmessage_category
 [X] 0064_auto_20160428_1813
 [X] 0065_auto_20160722_0923
 [X] 0066_auto_20160816_1031
 [X] 0067_auto_20161024_0922
 [X] 0068_auto_20161025_1632
 [X] 0069_source_screenshot
 [X] 0070_auto_20161103_1412
 [X] 0071_auto_20170124_1345
 [X] 0072_auto_20170209_1234
 [X] 0073_auto_20170209_1359
 [X] 0074_auto_20170209_1412
 [X] 0075_auto_20170215_1750
 [X] 0076_auto_20170317_1239
 [X] 0077_auto_20170317_1514
 [X] 0078_auto_20170322_1112
 [X] 0079_autocomponentlist
 [X] 0080_auto_20170323_0838
 [X] 0081_auto_20170323_0953
 [X] 0082_change_old
 [X] 0083_auto_20170404_1633
 [X] 0084_auto_20170406_0858
 [X] 0085_auto_20170406_0904
 [X] 0086_remove_project_owners
utils
 (no migrations)

**Comment by nijel** [comment]
Have you recently upgraded? It seems you're running 2.12 code with 2.13 database...

**Comment by aidik** [comment]
Yes, I recently upgraded and I believe that I'm running version 2.13  -- at least according to the website footer "Powered by Weblate 2.13". Is there a way to make sure? Thank you

**Comment by nijel** [comment]
Is the error still happening? Try restarting the uwsgi server (or whatever are you using),

**Comment by mclei-asw** [comment]
Upgraded today to master branch and have the same problem.

**Comment by nijel** [comment]
Maybe there are some stale ``*.pyc`` files causing this, can you try cleaning them up by running::

```
find . -name '*.pyc' -delete
```

**Comment by nijel** [comment]
Did the suggestion fix your problem?
