### ISSUE TITLE
Homepage for new users displays all projects in all languages

### ISSUE THREAD

**Issue by matejcik** [WeblateOrg/weblate#1578]
in `trans/views/basic.py`, function `get_user_translations` for unauthenticated users filters list of translation by session language. Unless that language is english.

This means that browsers that prefer english will load all translations for all languages.

Unfortunately, this query is the base for all the homepage queries. In conjunction with component list feature, this can mean that unauthenticated user is loading a page listing potentially _all languages for all components_ that are in some component list -- initially hidden from view behind the component list switches.

On l10n.opensuse.org, this results in a 23MB homepage that actually times out on the outbound proxy.

A quick fix we're using is removing the `and session_lang != "en"` part of the filter.
Part of the proper solution would be on-demand loading of component lists. Another part would be reviewing the `get_user_translations` function and its usages for sanity, because the logic it uses now is a little weird ;) and not appropriate as a base query for the other queries in `home()`.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
