### ISSUE TITLE
List my languages on top of language list

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#1579]
When I click on languages on the top menu bar I can see the list of languages the app is translated to, although it might be statistically very interesting to scroll and see all the other languages I think that in most cases the language I'm really after is the one I'm translating or if I'm translating to several languages that might also be very helpful to put all of them alphabetically on top.

Right after my langauges I think that the Secondary languages should appear and only then all the others alphabetically.

Do you agree?
Thanks!

**Comment by nijel** [comment]
This kind of makes sense, though it will be a bit tricky to implement.

**Comment by yarons** [comment]
Why? If I selected some languages in the options they will appear on top in the list (Alphabetically), it requires breaking the list in a way but it's more beneficial if I'm moving between several resources.

**Comment by nijel** [comment]
Because the sorting currently doesn't have access to user profile to know your preference :-).

**Comment by yaron-tracxpoint** [comment]
LOL, I understand, do you think it's a necessary feature?

**Comment by yarons** [comment]
LOL, I see, do you think that feature is necessary?

**Comment by nijel** [comment]
I'm not really sure this is good approach as it would break UI consistency. Maybe showing user translations separately and then list of all would be better (so that you find the translation if you end up looking alphabetically)...

**Comment by yarons** [comment]
So you're suggesting 2 list one on top of the other?

The reason I suggested the priority sorting was to avoid that but if you don't think that duplication is a problem in that case so we're good :smile:
