### ISSUE TITLE
Deleting component is slow and resource-hogging

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1580]
### Steps to reproduce
1. Create some large component (po ~ 7Mb in my case)
2. Do some translations
3. Try to delete the component from admin interface

### Actual behaviour
Weblate eats all available memory (~ 4Gb), then uwsgi is killed by the OS. The component is not deleted.

### Expected behaviour
1. Painless and quick component deletion. Maybe leave db cleanup to cron tasks, and just remove it from WebUI?
2. Not using so much memory (and consequently not dying midway)
3. Maybe add a manage.py command for that?
4. Once "Delete" button is pressed, the component should not be available to translators, so that they don't waste time on it.

### Server configuration
```
 * Weblate weblate-2.15
 * Python 2.7.5
 * Django 1.10.3
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.13.2
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.6.4
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2016.7
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.0
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
You can delete faster when deleting from the edit page, if you do the selection in the list, it is indeed slow right now, I'm looking into fix...

**Comment by burner1024** [comment]
I'm actually deleting from edit page.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by burner1024** [comment]
Will this work if I apply it on 2.15?

**Comment by nijel** [comment]
I think it could apply (6fab6b54116a4b9be3b989ea04647fee1ea5c2fc and 33d81216f19bcad245e5a775d77c34ea3c42a303), but I've not tested...

**Comment by burner1024** [comment]
I've deleted the entire project using [your tip](https://stackoverflow.com/questions/43629249/manually-delete-project-in-weblate) on SO. That went surprisingly quick. Does that mean that there's a hanging component somewhere in the db, or all's clean?

**Comment by nijel** [comment]
All is clean after that.

The difference is that Django admin interface first shows confirmation with number of objects to delete. Original version also listed all objects to delete, what above patches remove.

**Comment by burner1024** [comment]
OK, thanks you very much for your help.
