### ISSUE TITLE
Google Machine Translation API not accepting Norwegian Bokmål (nb)

### ISSUE THREAD

**Issue by Zaelot** [WeblateOrg/weblate#1583]
Google MT is looking for `no` even though that's the old one, and currently should either be the `nb` (Bokmål) or `nn` (Nynorsk).
https://cloud.google.com/translate/docs/languages

  

It also seems that what Google is actually translating is "Norwegian, Bokmål" 
https://www.quora.com/How-does-Google-Translate-do-with-Norwegian-language-as-Norwegian-has-two-official-forms

  

..so while Google is looking just for the old code, a hack could be added to send specifically that code to Google MT API (while supplying the correct one to other services).

**Comment by nijel** [comment]
Thanks for spotting. Actually this is not first language affected by Google using old codes, so it's easy to fix...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
