### ISSUE TITLE
RTL Navigation icons are reversed

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#1584]
<img width="370" alt="screen shot 2017-07-31 at 22 42 07" src="https://user-images.githubusercontent.com/406826/28795190-9d44dbb0-7641-11e7-82f2-4439581d3ca1.png">

**Comment by nijel** [comment]
Should only the icons be switched or the links they are pointing to as well?

**Comment by nijel** [comment]
@yarons can you please help me what is expected in RTL langs? Which one of these:

Buttons | ``│<`` | ``<<`` | `` x / y `` | ``>>`` | ``>│``
--------|-------|--------|-------------|--------|-------
Action 1 | first | prev   |             | next   | last
Action 2 | last  | next   |             | prev   | first

**Comment by yarons** [comment]
Hey, I will reach a computer in a week from now, I'll try to ask some friends to help in the meanwhile.

**Comment by yarons** [comment]
This wasn't fixed yet:
<img width="539" alt="screen shot 2018-11-17 at 9 05 07" src="https://user-images.githubusercontent.com/406826/48658261-88976180-ea47-11e8-9a67-5151a81157c5.png">

Action 2 is the desired way of handling these.

**Comment by yarons** [comment]
Yes, it's good now.
![image](https://user-images.githubusercontent.com/406826/50424633-f10c0680-086f-11e9-84c6-c381e6ca19b9.png)
