### ISSUE TITLE
Ability to mark translation string as not needed

### ISSUE THREAD

**Issue by KamilSowa** [WeblateOrg/weblate#1585]
The issue we currently experience is inability to tell Weblate to not require a translation in one of the supported languages.

Image we have two features (F1 and F2) in the application and two countries (C1 with language L1 and C2 with language L2). If feature F2 is only applicable to C1, then translating it to L2 does not make sense, right? Is there a way in Weblate to enable such behaviour? Otherwise all translations from F2 will be marked in L2 as untranslated (they are in fact not needed).

I would greatly appreciate if there's some sort of support for such a scenario.

**Comment by nijel** [comment]
You can split the translation into several files (which would end up as separate components in Weblate). Each can be then translated into different languages. 

4. srpna 2017 13:33:52 GMT+01:00, Kamil Sowa <notifications@github.com> napsal:
>The issue we currently experience is inability to tell Weblate to not
>require a translation in one of the supported languages.
>
>Image we have two features (F1 and F2) in the application and two
>countries (C1 with language L1 and C2 with language L2). If feature F2
>is only applicable to C1, then translating it to L2 does not make
>sense, right? Is there a way in Weblate to enable such behaviour?
>Otherwise all translations from F2 will be marked in L2 as untranslated
>(they are in fact not needed).
>
>I would greatly appreciate if there's some sort of support for such a
>scenario.
