### ISSUE TITLE
Troubleshooting performance for large components

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1586]
### Steps to reproduce
1. Create one small and one large component in Weblate.
2. Translate a few strings in both.

### Actual behaviour
Saving strings for the large component is much slower than for the small one. Time to save is about the same as hosted.weblate.org when working on a small component:
```generated 0 bytes in 940 msecs (HTTP/1.1 302) 5 headers in 217 bytes (1 switches on core 0)```

For the large one (~50k strings, 500k words), it's regularly 4-6 seconds:
```generated 0 bytes in 5774 msecs (HTTP/1.1 302) 5 headers in 208 bytes (1 switches on core 0)```
I couldn't find a large enough project on hosted.weblate.org to compare the timings.

This is way too slow for comfortable working. How can I troubleshoot this? What options are there to speed it up? I already have redis cache, and mysql is tuned.

### Expected behaviour
Time to save a string should be the same (and low).

### Server configuration
```
 * Weblate weblate-2.15
 * Python 2.7.5
 * Django 1.10.3
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.13.3
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.6.4
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2016.7
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.0
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
Can you retry with 66a7391e7bba9bc9ed22a9340fe673e888ecb804 applied? It was bug in 2.15 (maybe present in 2.14 as well) which made Weblate rescan the file on every change as it didn't properly store checksum of updated file. Note that the first change in every translation will still be slow after applying the patch, it will affect only next saves...

**Comment by burner1024** [comment]
I already have that applied.

**Comment by nijel** [comment]
I've realized that just after sending comment ;-). Can you share the file with me? It might be just that the immediate update of the stored file takes too long for the big file...

**Comment by burner1024** [comment]
You mean po file? [Here](https://tra.bgforge.net/projects/fallout2/up-male/es/).

**Comment by nijel** [comment]
I'm afraid that with current approach of applying changes immediately to the file it can't be much faster. On my laptop only the parsing of this file takes 3 seconds, so 4-6 seconds for the request here seems to be close to what we can achieve.

Yes, Weblate does currently save to a file with every single file. I know it's not optimal and I want to get rid of this in the long term. Actually basic optimization should be quite simple as we have all the checkpoints and barriers to commit things to file just when needed for a VCS commit. However it turned out that for most use cases it's really not a big deal - if you have few thousands strings, it still works reasonably fast and that is actually what most people use...

**Comment by burner1024** [comment]
I understand. Is there a simple hack that would restrict saving to on commit or on lock release, or I just have to wait?

**Comment by nijel** [comment]
There is no simple hack to do that - we have to flag dirty units and adjust checks for pending changes (they are currently based on VCS, they would have to turned into database driven ones).

**Comment by burner1024** [comment]
I'm not sure if moving it all to the database is a good idea, file operations must be much quicker. Maybe flushing when lock is released is a better compromise?

**Comment by nijel** [comment]
It really doesn't matter when you flush, still you need to mark dirty units in the database and take that in account when checking need for commit (eg. if repository should be updated while somebody is translating).

**Comment by burner1024** [comment]
OK, I trust you know better.

**Comment by nijel** [comment]
I find this really interesting performance improvement so I will try to prototype this while flying back to Europe this weekend, let's see how far I can get.

**Comment by nijel** [comment]
It turned out to be not that hard, so the files will now be updated on commit. The performance gain is quite visible even on smaller files.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by burner1024** [comment]
Thanks, I will try it as soon as 2.17 is out!
