### ISSUE TITLE
Performance issues on many components in git

### ISSUE THREAD

**Issue by ieugen** [WeblateOrg/weblate#1590]
### Steps to reproduce

We have been using Weblate for some time and decided to change from a 2 project with ~ 30 components to 5 projects with ~ 200+ components. 

All of the data for the components live in a single git repo because they related.

Now, whenever we push changes to our git repo, Weblate pull in those changes and does a re-import of all components in the repository. 

### Actual behaviour

This results in many problems:
- very high load on the system - 150 - the system is doing a lot of I/O - even with SSD and the application is not that responsive
- Weblate does many updates in parallel and runs out of memory and I believe those processes are not retried so the imports are "lost"

````
xception in thread Thread-776:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/var/www/weblate/weblate/trans/models/subproject.py", line 111, in wrapper
    return func(self, *args, **kwargs)
  File "/var/www/weblate/weblate/trans/models/subproject.py", line 698, in do_update
    if not self.update_remote_branch():
  File "/var/www/weblate/weblate/trans/models/subproject.py", line 111, in wrapper
    return func(self, *args, **kwargs)
  File "/var/www/weblate/weblate/trans/models/subproject.py", line 649, in update_remote_branch
    self.repository.update_remote()
  File "/var/www/weblate/weblate/trans/vcs.py", line 226, in update_remote
    self.execute(self._cmd_update_remote)
  File "/var/www/weblate/weblate/trans/vcs.py", line 190, in execute
    self.last_output = self._popen(args, self.path)
  File "/var/www/weblate/weblate/trans/vcs.py", line 166, in _popen
    stdin=subprocess.PIPE,
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
````
![screenshot from 2017-08-08 12-14-32](https://user-images.githubusercontent.com/1050920/29065657-77ac2ef4-7c35-11e7-9328-7719f75b21be.png)

### Expected behaviour

Weblate should behave nicely with respect to changes.

Some suggested solutions:

- Weblate should check for changes before trying to re-importing. I believe file hashing can be used to detect changes on file level. 
- Weblate should use a fixed (configurable maybe) number of spawned import processes and use a producer/consumer pattern to load balance translation updates. 

### Server configuration

We are using a deployment like the one belllow, and planning to switch to a docker based deployment soon. But we need a solution for our update problem. 

I'm thinking that one current workaround to this issue is to create multiple git repositories but that kind sucks. 

````
* Weblate weblate-2.13.1-342-g3867c47
 * Python 2.7.9
 * Django 1.10.5
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.2
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2012c
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.11
 * Mercurial 3.1.2
 * Database backends: django.db.backends.postgresql_psycopg2
````

**Comment by nijel** [comment]
Are you using shared repos (see https://docs.weblate.org/en/latest/vcs.html#weblate-internal-urls) or every component has separate clone? Using shared repos certainly should help in this case.

**Comment by ieugen** [comment]
We are not using shared repos . It does make sense to have better performance. Thank you for this insight. I totally missed that line in the documentation. Will try and come back with feedback.

Thanks,

**Comment by ieugen** [comment]
We updated the components to use shared repo and it works. 

We renamed all the components via sql script and via Weblate UI push & pull and reset. 
Did a new import and things worked much better. Load got up until 9 instead of 150 and the app finished quite fast. 

@nijel : Does Weblate provide a way to clean the un-used repositories (older projects and components that have been migrated to shared repo)?  If not how should we handle removing them - they keep a lot of space and also it's hard to do manual updates when needed? 

````
UPDATE trans_subproject
SET repo = 'weblate://project1/component-slug-with-real-git-repo-url'
, push = ''
, git_export = ''
WHERE id in (SELECT id from trans_subproject
  where project_id in (
  SELECT id
  FROM trans_project
  WHERE slug in ('project1', 'project2')
)
and slug != 'component-slug-with-real-git-repo-url' )
````

**Comment by nijel** [comment]
There is currently no cleanup for this, but you can use following to list paths which are being used and remove others:

```console
$ ./manage.py shell
Python 2.7.13+ (default, Jul 19 2017, 18:15:03) 
[GCC 6.4.0 20170704] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from weblate.trans.models import SubProject
>>> paths = set([x.get_path() for x in SubProject.objects.all()])
>>> print '\n'.join(paths)
```

**Comment by ieugen** [comment]
Thank you for your support. We fixed the performance issues by moving to the hared repository.
The code you provided also helped us clean the old remaining repositories. 

I've added a PR to update the docs and recommend the use of shared repository for performance reasons.
