### ISSUE TITLE
Keyboard shortcuts and Copy and Save doesn't work since version 2.14

### ISSUE THREAD

**Issue by romanr** [WeblateOrg/weblate#1596]
### Steps to reproduce
1. Keyboard shortcut for Ctrl-Save does not work. 
2. On Machine translation tab, pressing copy and save only copies the string . but does not save.

Reported by multiple users, Chrome browser, Windows and Mac. Was working before upgrading to 2.14

### Server configuration

```
./manage.py list_versions
 * Weblate weblate-2.16
 * Python 2.7.3
 * Django 1.11.3
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.4
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.0
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2017.2
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.10
 * Mercurial 3.2.2
 * Database backends: django.db.backends.postgresql_psycopg2

```

**Comment by nijel** [comment]
It seems to work fine for me on Firefox. Do you mean clicking on the "Copy and save" button?

**Comment by romanr** [comment]
- Copy and Save only copies but not saves
- Ctrl-Save does nothing (stays on same page)
- No JS errors in console. 
- Reported by multiple users on different browsers.

These two problems points to that page is not able to save and advance to next page. Save button is present and can be clicked. 

Probably because of some condition? Maybe it's some connection between ACL/permissions and Javascript that's not working?

 Is there a way to diagnose this problem?

Thank you.

**Comment by nijel** [comment]
BTW: Did you run collectstatic after upgrading Weblate? Maybe your installation is just stuck with older javascript files....

**Comment by romanr** [comment]
Thank you. that solved it.

**Comment by nijel** [comment]
Great, I've clarified upgrading instructions a bit on this:

https://docs.weblate.org/en/latest/admin/upgrade.html

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
