### ISSUE TITLE
git-merge-gettext-po documentation

### ISSUE THREAD

**Issue by glensc** [WeblateOrg/weblate#1598]
https://docs.weblate.org/en/latest/admin/continuous.html#updating-repositories

says: 
> Changed in version 2.9: This merge driver is automatically installed in case Weblate finds it (this currently works only for Git checkout as distutils package does not include examples).

however, (at least) with 1.11.3 seems the examples are also present when installed with pip:

```
bash-4.4# weblate --version
1.11.3
bash-4.4# find /usr/ -name git-merge-gettext-po
/usr/local/share/weblate/examples/git-merge-gettext-po
bash-4.4#
```

not sure if the [tool is picked up](https://github.com/WeblateOrg/weblate/blob/weblate-2.16/weblate/trans/vcs.py#L348-L363), as i don't know how to test the scenario.

my suggestion is to:
1. make it work with pip installs too
2. update/remove documentation accordingly

**Comment by glensc** [comment]
scratch test about paths:

```
$ docker run --rm -it python:2 bash -l
root@6a9e09f3b441:/# pip install Weblate==2.16
[truncated]
root@6a9e09f3b441:/# find /usr/ -name git-merge-gettext-po
/usr/local/share/weblate/examples/git-merge-gettext-po
root@6a9e09f3b441:/#

```

**Comment by nijel** [comment]
True, we do install examples recently, but this hasn't been updated...

**Comment by nijel** [comment]
Also related to https://github.com/WeblateOrg/weblate/issues/55

**Comment by glensc** [comment]
what is the scenario to trigger writing `.git/config` and `~/.gitconfig`?

i created the examples dir as symlink and saved project settings and repository tools -> push, pull.

**Comment by nijel** [comment]
The path to merge driver is obtained using Repository.get_merge_driver, see https://github.com/WeblateOrg/weblate/blob/master/weblate/trans/vcs.py#L349, the individual VCS wrappers then implement configure_merge which configures that.

**Comment by glensc** [comment]
i mean what action i need to do to make configure_merge being called.

ps: you again pasted link to master branch, use permalinks (`y` hotkey in github web)

**Comment by glensc** [comment]
without code fixes, made the path working in my docker image:

```

bash-4.4# ln -s /usr/local/share/weblate/examples /usr/local/lib64/python2.7/site-packages/examples
bash-4.4# python -c 'import weblate.trans.vcs as v; print v.Repository.get_merge_driver("po")'
/usr/local/lib64/python2.7/site-packages/examples/git-merge-gettext-po
bash-4.4#
```

**Comment by nijel** [comment]
It's automatically called on every merge/rebase (but you've probably already figured that out).

PS: I've changed the link to permalink.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by glensc** [comment]
https://github.com/WeblateOrg/weblate/issues/1598#issuecomment-322782740

...still not sure this actuall works

so, according to code, i should be seeing `~/.gitconfig` being set?
https://github.com/WeblateOrg/weblate/blob/weblate-3.0.1/weblate/vcs/git.py#L343

but the file doesn't seem to exist:
```
# docker-compose  exec --user=weblate weblate bash -l
weblate@c975793c9c2b:/$ cat ~/.gitconfig
cat: /home/weblate/.gitconfig: No such file or directory
weblate@c975793c9c2b:/$
```

and according to doc:
https://docs.weblate.org/en/weblate-3.0.1/admin/continuous.html#updating-repositories

neither `.git/info/attributes` exist in any repository:

```
# docker-compose  exec --user=weblate weblate bash -l
weblate@c975793c9c2b:/$ find /app/data/vcs/ -name attributes | wc -l
0
```

**Comment by nijel** [comment]
It's being set in /app/data/home, Weblate does not use system home dir at all.
