### ISSUE TITLE
User is unable to delete comment

### ISSUE THREAD

**Issue by Henk8** [WeblateOrg/weblate#1599]
### Steps to reproduce
1. I have added a single user with the following rights

- User can add comment
- User can change comment
- User can delete comment

2.
3.

### Actual behaviour
The user can add a comment, but is unable to delete the comment.
Only the admin has the red delete button.

### Expected behaviour
The user is able to delete the comment. 

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
