### ISSUE TITLE
links from admin to documentation

### ISSUE THREAD

**Issue by glensc** [WeblateOrg/weblate#1601]
In few places i've noticed such sentences:

> [ ] Enable ACL
> Whether to enable ACL for this project, please check documentation before enabling this.

would be a lot more useful if there's actually direct link to the documentaion in question!

**Comment by nijel** [comment]
This is not really possible to do while using Django admin interface. The long term is not to use it at all and move settings to Weblate itself.

This particular setting will however be addressed for next release, see https://github.com/WeblateOrg/weblate/issues/1434
