### ISSUE TITLE
Mobile app for Android (F-Droid)

### ISSUE THREAD

**Issue by Symbian9** [WeblateOrg/weblate#1602]
### Actual behaviour
Currently Weblate could be used only through webbrowser on Android devices.

### Expected behaviour
Make an app for much more friendly translating process for Android users. There is app on F-Droid, that partly interact with repos on Github, that include sources for Android-related apps, and help make locales. But for other projects, non-related to Android, it not yet usable.

### REFERENCE
https://f-droid.org/wiki/page/io.github.lonamiwebs.stringlate

**Comment by nijel** [comment]
Having native app is currently not on a roadmap. However we're happy to extend API to make writing such app possible.

See also https://github.com/WeblateOrg/weblate/issues/1066
