### ISSUE TITLE
Reviewing suggestions: Pass to next suggestion after voting for one.

### ISSUE THREAD

**Issue by emmapeel2** [WeblateOrg/weblate#1603]
A little/low priority usability bug:

### Steps to reproduce
1. Open component
2. Select 'Strings with suggestions'
3. Vote for one suggestion

### Actual behaviour
The vote gets computed, and the string is re-rendered.

### Expected behaviour
Next string with suggestions should appear, as when you click 'Accept suggestion' or 'Suggest'. 
This problem only occurs when voting for the suggestion.

**Comment by nijel** [comment]
There really should be separate view for reviewing/voting suggestions, see https://github.com/WeblateOrg/weblate/issues/671.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
