### ISSUE TITLE
Suggestion: comments: keep the newlines

### ISSUE THREAD

**Issue by tuxayo** [WeblateOrg/weblate#1605]
Example of current behavior:
```
1. falas doesnt' really signifas incurs

2. Find a translation for fee
```
↓
```
1. falas doesnt' really signifas incurs 2. Find a translation for fee
```

Sometime it really messes the meaning. And as the comments are not editable it can create few issues.

```
kotizo != fee
anyway ~= ĉiuokaze
```
↓

```
kotizo != fee anyway ~= ĉiuokaze
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by tuxayo** [comment]
> Thank you for your report, the issue you have reported has just been fixed.

Wow, that's awesome!

> If you are happy with the outcome, consider supporting Weblate by donating.

I'm very happy with the outcome and was happy with Weblate before. In fact I discovered Weblate when translating Liberapay. And insta-donated when saw that Weblate was on Liberapay :-D
https://liberapay.com/Weblate/

These are two projects to support other projects. So having them supporting each other is wonderful.
