### ISSUE TITLE
Custom source check get saved to DB

### ISSUE THREAD

**Issue by jmaxxz** [WeblateOrg/weblate#1612]
### Steps to reproduce
1.  Create a source check
```
# -*- coding: utf-8 -*-
"""Quality check looks for non-production strings."""
from __future__ import unicode_literals
from weblate.trans.checks.base import SourceCheck
from django.utils.translation import ugettext_lazy as _

class SourceContainsHeartCheck(SourceCheck):
    # Used as identifier for check, should be unique
    # Has to be shorter than 50 chars
    check_id = 'SourceContainsHeart'

    # Short name used to display failing check
    name = _('Contains ♥')

    # Description for failing check
    description = _('Likely not a production quality string.')

    severity = 'danger'

    def check_source(self, source, unit):
           # Not the actually check I am using, but the simplest check which produces the issue.
           return true;
```
2. Restart weblate
3. Run `./manage.py updatechecks `<project>`

### Actual behavior
Only a subset of the source strings in `<project>` have a failing check.

### Expected behaviour
All source strings in `<project>` should have a failing check.

### Server configuration

 * Weblate weblate-2.8-3558-g42a9039
 * Python 2.7.12
 * Django 1.11.4
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.4
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.1
 * lxml 3.8.0
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.6.4
 * pytz 2017.2
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 3.9.1
 * hub 2.3.0-pre9
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
Apparently there is not documented expectation of using lowercase in check_id, then everything works as expected. I'll look deeper why this is actually there...

**Comment by nijel** [comment]
Sorry it's not caused by using uppercase, but that changed ordering in my test setup so that the issue was no longer visible. It's bug in stale checks cleanup code.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by jmaxxz** [comment]
Thanks so much, works great!
