### ISSUE TITLE
ord() expected a character, but string of length 0 found

### ISSUE THREAD

**Issue by dachary** [WeblateOrg/weblate#1613]
### Steps to reproduce

1. With weblate 2.14.1 create the Chinese traditional translation
2. Copy paste 登录失败 and click Save

### Actual behaviour

An error page shows with the following:

<pre>

Request Method: | POST
-- | --
http://weblate.securedrop.club/translate/securedrop/securedrop/zh_Hant/?type=todo&offset=0
1.11.3
TypeError
ord() expected a character, but string of length 0 found
/usr/local/lib/python2.7/dist-packages/whoosh/util/varints.py in read_varint, line 102
/usr/bin/python
2.7.13
['/usr/local/bin',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages']
Mon, 28 Aug 2017 07:26:39 +0000

Environment:

Request Method: POST
Request URL: http://weblate.securedrop.club/translate/securedrop/securedrop/zh_Hant/?type=todo&offset=0

Django Version: 1.11.3
Python Version: 2.7.13
Installed Applications:
(u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.sessions',
 u'django.contrib.sites',
 u'django.contrib.messages',
 u'django.contrib.staticfiles',
 u'django.contrib.admin.apps.SimpleAdminConfig',
 u'django.contrib.admindocs',
 u'django.contrib.sitemaps',
 u'social_django',
 u'crispy_forms',
 u'compressor',
 u'rest_framework',
 u'rest_framework.authtoken',
 u'weblate.trans',
 u'weblate.lang',
 u'weblate.permissions',
 u'weblate.screenshots',
 u'weblate.accounts',
 u'weblate.utils',
 u'weblate.gitexport',
 u'weblate')
Installed Middleware:
(u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.locale.LocaleMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'weblate.accounts.middleware.AuthenticationMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'django.middleware.clickjacking.XFrameOptionsMiddleware',
 u'social_django.middleware.SocialAuthExceptionMiddleware',
 u'weblate.accounts.middleware.RequireLoginMiddleware',
 u'weblate.middleware.SecurityMiddleware')

Traceback:

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python2.7/dist-packages/weblate/trans/views/edit.py" in translate
  473.                 this_unit_url, next_unit_url

File "/usr/local/lib/python2.7/dist-packages/weblate/trans/views/edit.py" in handle_translate
  277.         go_next = perform_translation(unit, form, request)

File "/usr/local/lib/python2.7/dist-packages/weblate/trans/views/edit.py" in perform_translation
  203.         form.cleaned_data['fuzzy']

File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/unit.py" in translate
  1046.             propagate=propagate

File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/unit.py" in save_backend
  649.         self.save(backend=True)

File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/unit.py" in save
  798.             update_index_unit(self, force_insert)

File "/usr/local/lib/python2.7/dist-packages/weblate/trans/search.py" in update_index_unit
  219.         index = get_target_index(unit.translation.language.code)

File "/usr/local/lib/python2.7/dist-packages/weblate/trans/search.py" in get_target_index
  125.         exists = STORAGE.index_exists(name)

File "/usr/local/lib/python2.7/dist-packages/whoosh/filedb/filestore.py" in index_exists
  189.             ix = self.open_index(indexname)

File "/usr/local/lib/python2.7/dist-packages/whoosh/filedb/filestore.py" in open_index
  176.         return indexclass(self, schema=schema, indexname=indexname)

File "/usr/local/lib/python2.7/dist-packages/whoosh/index.py" in __init__
  421.         TOC.read(self.storage, self.indexname, schema=self._schema)

File "/usr/local/lib/python2.7/dist-packages/whoosh/index.py" in read
  632.         check_size("int", _INT_SIZE)

File "/usr/local/lib/python2.7/dist-packages/whoosh/index.py" in check_size
  626.             sz = stream.read_varint()

File "/usr/local/lib/python2.7/dist-packages/whoosh/filedb/structfile.py" in read_varint
  191.         return read_varint(self.read)

File "/usr/local/lib/python2.7/dist-packages/whoosh/util/varints.py" in read_varint
  102.     b = ord(readfn(1))

Exception Type: TypeError at /translate/securedrop/securedrop/zh_Hant/
Exception Value: ord() expected a character, but string of length 0 found
</pre>

The translations is properly saved.

### Expected behaviour

The translation is properly saved and no error page is displayed.

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

 * Weblate 2.14.1
 * Python 2.7.13
 * Django 1.11.3
 * six 1.10.0
 * social-auth-core 1.3.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.3
 * pytz 2017.2
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.1.3
 * Mercurial 4.0
 * git-svn 2.11.0

**Comment by nijel** [comment]
It seems that the fulltext index for this language is corrupt, you would probably get same error regardless what the translation is. The question is how this did happen - did you have any hardware problems or sudden reboots of the system recently?

**Comment by dachary** [comment]
I just tried to modify a french translation and did not get the error. The machine did not reboot in 20 days.
<pre>
weblate:~$ uptime
 13:39:31 up 20 days, 17:14,  1 user,  load average: 0.03, 0.07, 0.08
</pre>
but I started / stoped the weblate docker container 4 days ago.

**Comment by nijel** [comment]
Yes, probably just the zh_Hant index is corrupt. What I've meant is that it doesn't depend on the text of the translation.

The fulltext is not in PostgreSQL, but rather in file, honestly I have no clue how to debug this, try asking at https://bitbucket.org/mchaput/whoosh (what is fulltext engine we use).

Anyway to recover, you can rebuild the index:

```
docker-compose run <container> weblate rebuild_index --all --clean
```

**Comment by dachary** [comment]
That worked, thanks for the tip ! I don't feel motivated to report / debug the problem higher up in the upstream chain right now. But if it comes back I will and report the progress here.

As always, thanks a lot for the quick an helpful assistance :-)
