### ISSUE TITLE
Xliff - multiline source context displayed as one line

### ISSUE THREAD

**Issue by romanr** [WeblateOrg/weblate#1614]
### Steps to reproduce
1. Create Xliff file with multi-line string
2. Import in weblate
3. in Translate UI  context source it is displayed as one line

With other format - Android XML resource, the source is displayed properly formatted with newlines.
Both Android and Xliff are xmml formats. I tried with \n and plain newlines, it's ignored with Xliff.

Is Android XML the only format that can be used for multiline strings? (I know Gettext kind of supports it but splits lines into separate strings and requires git hooks to make it work.)

Thank you.

**Comment by nijel** [comment]
In case you want to preserve whitespace (including newlines), the node needs to have ``xml:space="preserve"`` attribute.

Also there is no problem in storing newline in Gettext, it's stored as `\n`:

https://github.com/WeblateOrg/weblate/blob/60251e081a09bd809604e40482363c45f2aed0c5/weblate/locale/cs/LC_MESSAGES/django.po#L7869-L7877

**Comment by romanr** [comment]
Thank you! `xml:space="preserve"` worked for Xliff. Even `\n` is not needed!
I spent so much time on this. This will be very helpful if you add it to https://docs.weblate.org/en/latest/formats.html#xliff

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
