### ISSUE TITLE
reviewing translations: ability to lock a single string

### ISSUE THREAD

**Issue by dachary** [WeblateOrg/weblate#1616]
There currently is no convenient [review workflow](https://docs.weblate.org/en/latest/faq.html#how-do-i-review-others-translations) in weblate allowing reviewers to verify the quality of translated strings. There are suggested workflow that mostly rely on discipline on behalf of the reviewer and the translator. They are error prone and inconvenient.

A reviewer proposed that the ability for a reviewer to lock a translated string (not the whole set of strings, just one) would be an easy way for a reviewer to express the fact that the translation is good and final. If the translated string is locked, the **Save** button is disabled and translators can no longer change the translation. The checkbox allowing the reviewer to lock/unlock a string could be next to the **Need review** checkbox. The search box could be extended to look for all strings that are not in the **Locked** state so the reviewer can focus on them.

Was this idea discussed before ? Does it sound like a convenient review workflow ?

[<img ng-src="https://api.bountysource.com/badge/issue?issue_id=48794537" src="https://api.bountysource.com/badge/issue?issue_id=48794537">](https://www.bountysource.com/issues/48794537-reviewing-translations-ability-to-lock-a-single-string)

**Comment by nijel** [comment]
There is https://github.com/WeblateOrg/weblate/issues/1073 for generic review workflow discussions, but something like this was not really opened there.

I unfortunately do not have experience with good working review process, so I certainly welcome suggestions how to implement such thing.

**Comment by dachary** [comment]
ah, thanks for pointing to the right issue :-) and sorry for the duplicate

**Comment by dachary** [comment]
Actually, I'm reopening this because it is a proposed workflow that is different from what is described in #1073 and, IMHO, simpler and more effective. 

I discussed today with a coordinator from https://www.localizationlab.org/ who described how he usually works. And he was quite clear about the fact that the ability for a reviewer to forbid modifications on a string she/he think final and correct is the most important feature to enable a translation workflow involving two roles : translators and reviewers. If a translator disagrees on a given translation, she/he can make suggestions for improvements, the dialog is still open.

@nijel does that sound like a reasonable feature to add ?

**Comment by nijel** [comment]
Yes, this sounds reasonable and quite simple as well.

It would also work for some other workflows (see https://github.com/WeblateOrg/weblate/issues/868#issuecomment-147403832 from @stanislav-brabec).

**Comment by dachary** [comment]
@nijel cool ! Would you be so kind as to open a bounty on this enhancement ?

**Comment by nijel** [comment]
Apparently the BountySource integration somehow doesn't work, but you can always paste the issue URL there and add bounty. For this issue it's https://www.bountysource.com/issues/48794537-reviewing-translations-ability-to-lock-a-single-string

**Comment by dachary** [comment]
@nijel is it possible to estimate the target of the bounty ? I suppose it would help with fund raising ;-)

**Comment by nijel** [comment]
Generally I try to prioritize all issues with bounties as that shows that somebody is really interested in having that feature :-).

**Comment by burner1024** [comment]
I think having separate roles for reviewers and translators as mentioned in #1073 would be a better (less cumbersome and less work) approach.

**Comment by dachary** [comment]
@burner1024 My understanding is that this would indeed be a specific permission. We could then have one "Reviewer" group with the ability to lock strings. And another group (the currenty User group) that is the default without the ability to lock strings. Is that what you mean by "Role" ? Or do you have something else in mind ?

**Comment by burner1024** [comment]
My issue is there's already a flag that literally says "Needs review", and I think that adding another flag that doesn't say "needs review", but actually means "(doesn't) need review" will lead to confusion.
If it doesn't need review, then "normal" translators don't need access to changing the string in the first place.

(The problem with that approach, though, is that currently "needs review" = fuzzy in PO file, and that will have to be tackled with somehow, maybe moving fuzzy to suggestions?)

**Comment by dachary** [comment]
> but actually means "(doesn't) need review" will lead

It would make sense to me if a locked string was signaled to the translator with:

* No **Save** button
* A warning, on the same line as the **Need review** that reads **This translation has been verified to be correct and can no longer be modified**

And the user with permission to lock/unlock a string would also have a checkbox allowing her/him to **Lock / Unlock** a translation.

Would that be ok ? 

The **Need review** flag semantic is indeed somewhat misleading / confusing but it's a problem that does not block the resolution of this issue, IMHO.

**Comment by burner1024** [comment]
Yes, I agree in general about roles/permissions.
(Not sure about locked checkbox, as a reviewer I'd rather have a button like "Approve/Disapprove" - that's 1 action instead of 2: ticking checkbox and clicking save. But that's implementation details.)

Still, I think that semantics are important, and in my (humble) opinion it will be less confusing to rename current "needs review" to, say, "needs update". And the new "locked/unlocked" would become "needs review", which is its real meaning.

Well, that's just my thoughts on the matter.

**Comment by dachary** [comment]
> it will be less confusing to rename current "needs review" to, say, "needs update"

👍 

> And the new "locked/unlocked" would become "needs review", which is its real meaning.

Not really. A string that is unlocked may have been reviewed a few times and there may have been long discussions about it. When it is locked it means a consensus has been reached or someone with the proper authority made an executive decision for a definitive translation. 

@burner1024 I understand we have different opinions on the matter and this debate will hopefully help @nijel figure out something that makes sense ;-)

**Comment by stanislav-brabec** [comment]
@burner1024 comment 13: No, fuzzy string not equals to suggestion:

Fuzzy string = translation of similar string => string needs edit nearly for sure

Suggestion = a result of human activity; somebody with insufficient privileges or insufficient self-confidence suggested a translation change/addition => string is very probably OK

It also implies that "Needs review" is a bad interpretation of fuzzy flag. In reality, it is "Needs edit".

**Comment by burner1024** [comment]
@stanislav-brabec I agree, it was just a suggestion off the top of my head.

**Comment by nijel** [comment]
For the fuzzy/need review also see https://github.com/WeblateOrg/weblate/issues/1314. So yes, we need two separate flags for this.

**Comment by dachary** [comment]
@nijel Is there anything I could do to help the implementation of this feature ?

**Comment by nijel** [comment]
As you can see from the milestone, it's now scheduled for next release, which is currently expected to be ready by end of November.

**Comment by kushaldas** [comment]
@dachary 👍

**Comment by nijel** [comment]
What do you think about this interface for review?

![screenshot-2017-11-24 acl limited - czech](https://user-images.githubusercontent.com/212189/33220984-b34ea650-d14c-11e7-9298-cd1eaccf0f52.png)

**Comment by nijel** [comment]
The code is already in master branch, but it yet doesn't prevent units from being edited.

**Comment by stanislav-brabec** [comment]
However this UI will be functional, It would need 2 clicks per approval.

I would prefer a different UI:

UI for reviewers:

☐ Needs editing
Review state: Review
Save and approve | Save | Approve | Suggest | Skip

UI for strings that need editing:

☑ Needs editing
Review state: Untranslated
(Save and approve) | Save | (Approve) | Suggest | Skip
(Save and approve) and (Approve) are greyed out and inactive to prevent unwanted approval of fuzzy string (or at least inactive and reporting: First edit the string).

UI for users without review privilege or UI for strings that need editing:

☐ Needs editing
Review state: Review
Save | Suggest | Skip


Fuzzy/Needs editing:

I am not sure about a way to present Needs editing. The flag should be IMHO auto-unset once editing is performed and Save is pressed. And it will be very rarely needed to set it manually. This is mostly done by automatic tools like msgmerge. Manual Needs editing set is only needed if a breaking translation is found by a non-native speaker.

**Comment by dachary** [comment]
@nijel the intereface looks good :-) I'll read the code to understand the change in logic. Very excited about this !

**Comment by nijel** [comment]
I was thinking abut buttons as well, but to me it seemed that would be confusing - should approve button save the change as well? You've addressed this by adding yet another button. Also with radio it's clear that it either needs edit or is approved, with buttons it needs additional logic and is not obvious to user...

Anyway one click approval is there in zen mode.

**Comment by dachary** [comment]
So the idea is that only **reviewers** have the right to **approve** a string or not. And when a string is in the state **approved**, translators can no longer modify it. Also, if the source string changes the **approved** state is removed. Did I understand correctly ?

**Comment by stanislav-brabec** [comment]
Well, actually, Save and Suggest makes no sense until edit is made. (This illogical think already exists in Weblate.)

Approval without save makes no sense at all. (Edit, but don't save, but approve.) So discrimination between Approve and Save and approve makes no sense. Approve | Save | Suggest | Next should be sufficient.

Approval status could be also provided by a background color tone:
Red=untranslated or needs edit
orange or yellow=needs review
green=approved

**Comment by stanislav-brabec** [comment]
@dachary I can imagine two ways to work:
Approved string is locked. Only reviewers can edit, all other users can only suggest a change.
Approved string can be edited by anybody with edit privilege, but loses approved status.

I can even imagine that the work-flow can be switched on the fly on per-component basis:
development of product: Anybody can edit approved string.
beta and RC phase: Only reviewers can edit approved strings.

It has a simple rationale: Reviewers can be hired just for the beta/RC phase. In the rest of the development cycle, there could be nobody to approve suggestions of locked approved strings.

**Comment by dachary** [comment]
> Approved string is locked. Only reviewers can edit, all other users can only suggest a change.

This is going to be less tedious for reviewers, IMHO. If translators disagree, they can always comment.

**Comment by stanislav-brabec** [comment]
@dachary Both make sense.

For community driven enterprise projects, project is running 80% of the time in a community mode. Users are allowed to make packages and translations without strict limitations and without deep review. Nobody is hired for trusted review.

The model "Lock after review":
+ Approved strings are guaranteed to be present.
– Requires trusted reviewers working 100% of the time, otherwise suggestions will be pending.

The model "Invalidate approval":
+ String fixes pass to product even without reviewer interaction.
– Number of approved strings can decrease.
Note: Thinking about this model a bit deeper, this model would probably need storing of last approved version, for both review process (to answer, which change was done in an approved string) and for possibility to revert to last approved version.

**Comment by burner1024** [comment]
A third option for community driven projects could be "two pair of eyes" rule. Meaning that users can both translate and review, but they can't review their own translations. So at least 2 people should agree on each string.

**Comment by nijel** [comment]
@burner1024 This can be already achieved with current code without need for reviewer role, see https://docs.weblate.org/en/latest/workflows.html#peer-review

The review process will work pretty much as described by @stanislav-brabec:

* Users can translate not approved strings
* Reviewers can approve string
* Approved strings can no longer be edited (but users can give suggestions)
* Not approved translations are still stored in the file as translations (unlike suggestions)
* Once the source string changes, the approved flag is gone
* There is additional search for approved strings with suggestions, which reviewers should take care of

The community/review switch can be easily done by removing approved flag from all translations once the string freeze is over.

UI wise, I'm still not 100% sure - the one presented above has advantage of being same in zen and classic mode, having button in classic mode is indeed easier to use.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been implemented, you might want to check the [documentation for translation workflows](https://docs.weblate.org/en/latest/workflows.html). 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
To test this, you can use review/review account our our [Demo server](https://demo.weblate.org/).

**Comment by dachary** [comment]
> To test this, you can use review/review account our our Demo server.

Unless I'm mistaken the users of the Demo server do not have permission to **Approve**. Or did I miss something ?

**Comment by nijel** [comment]
No only the "review" account has.

**Comment by dachary** [comment]
Ah, thanks: I was able to login as user **review** password **review**

**Comment by dachary** [comment]
@nijel would you mind letting us know how much time you estimate you spent on resolving this particular issue, discussions included? My impression is that it is around eight hours over a period of weeks.

**Comment by nijel** [comment]
Honestly I have no clue right now. Quickly looking at the commits referencing this issue, it looks around 10 hours were spent on writing the code.
