### ISSUE TITLE
Inserting non-breakable spaces

### ISSUE THREAD

**Issue by dachary** [WeblateOrg/weblate#1618]
### Steps to reproduce
1. Go to a string translation
2. Add a non-breakable space (copy/pasting or Compose-space)

### Actual behaviour

See the non-breakable space is replaced by a regular space

### Expected behaviour

The non-breakable space is preserved

### Server configuration
Please paste the output of command `./manage.py list_versions` over here
<pre>
$ sudo docker-compose run -e VIRTUAL_HOST=none -e LETSENCRYPT_HOST=none --rm weblate list_versions
Starting weblatedocker_database_1 ...
Starting weblatedocker_cache_1 ...
^[[1BPostgres is up
 * Weblate 2.14.1
 * Python 2.7.13
 * Django 1.11.3
 * six 1.10.0
 * social-auth-core 1.3.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.3
 * pytz 2017.2
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.1.3
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2
</pre>

**Comment by nijel** [comment]
Hmm, isn't your browser doing that? I'm not aware of anything in Weblate what could do this...

**Comment by dachary** [comment]
I honestly have no clue. I suppose it could be the same kind of problem that justifies the present of special buttons to add a tab and other special characters ? It would be great if you could confirm that you are able to add a non breakable space with a given browser version. From this I'll be able to figure out why it does not work for me.

Thanks !
