### ISSUE TITLE
narrow non breakable space (U+202F) not considered space

### ISSUE THREAD

**Issue by dachary** [WeblateOrg/weblate#1619]
### Steps to reproduce
1. translate a string ending with an exclamation mark in French
2. add a [**small** non breaking space](https://en.wikipedia.org/wiki/Non-breaking_space#Width_variation) code U+202F before the exclamation mark in the French translation

### Actual behaviour

The exclamation mark check fails despite of the narrow non breakable space.

![qscjz3](https://user-images.githubusercontent.com/433594/29989267-30398e54-8f72-11e7-8b48-686c1ba9c4c7.jpg)

### Expected behaviour

The exclamation mark check succeeds

### Server configuration
Please paste the output of command `./manage.py list_versions` over here
 * Weblate 2.14.1
 * Python 2.7.13
 * Django 1.11.3
 * six 1.10.0
 * social-auth-core 1.3.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.3
 * pytz 2017.2
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.1.3
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Are you sure it was really this char? I was able to enter it there without firing the check: https://weblate.securedrop.club/translate/securedrop/securedrop/fr/?checksum=c7182775b99f61e7

Also the code does explicitly allow this:

https://github.com/WeblateOrg/weblate/blob/64fc012fce8af0df20c5faf72ee187df6fc303d4/weblate/trans/checks/chars.py#L278-L283

**Comment by dachary** [comment]
@nijel I can't reproduce the problem either... Let's close this for now and reopen if it surfaces. We've done multiple tests with spacing and my bug report is incorrect: not sure how I managed that. Sorry for the noise.
