### ISSUE TITLE
Context preview does not preserve formatting of newlines

### ISSUE THREAD

**Issue by romanr** [WeblateOrg/weblate#1622]
### Steps to reproduce
1.Xliff file:
```
</target></trans-unit>
   <trans-unit xml:space="preserve" id="2" approved="yes" resname="description">
      <source xml:space="preserve" xml:lang="en">
Line 1
Line 2
</source>
```

### Actual behaviour
In translation UI, when translating a string, in Translate window `Context:` displays context without formatting:
```
Line 1Line 2
```

On the right side of screen, source information/Context Displayed *correctly* as
```
Line 1
Line 2
```

### Expected behaviour
In translation UI, when translating a string, in Translate window `Context:` displays 
```
Line 1
Line 2
```

**Comment by nijel** [comment]
I'm a bit curious what are you doing differently here than in https://github.com/WeblateOrg/weblate/issues/1623?

**Comment by romanr** [comment]
This is about "Context" string. #1623 is about source string. Source is different from the source if I Am not mistaken.

**Comment by nijel** [comment]
But you're showing markup for `<source>` in both cases...
