### ISSUE TITLE
Xliff source string appears with \n escaping that is not present in source string

### ISSUE THREAD

**Issue by romanr** [WeblateOrg/weblate#1623]
### Steps to reproduce
1.Xliff file:
```
</target></trans-unit>
   <trans-unit xml:space="preserve" id="2" approved="yes" resname="description">
      <source xml:space="preserve" xml:lang="en">
Line 1
Line 2
</source>
```

### Actual behaviour
In translation UI, when translating a string, in Translate window `Source:` has unnecessary `\n`
```
Line 1\n↩️
Line 2
```

### Expected behaviour
In translation UI, in Translate window `Source:` displays 
```
Line 1↩️
Line 2
```

**Comment by nijel** [comment]
This really looks more like a translate-toolkit bug, but needs deeper look.

**Comment by nijel** [comment]
This seems to work fine now. So either it was fixed in Weblate or in the translate-toolkit. Please reopen if you can still reproduce this with clear instructions.
