### ISSUE TITLE
Download XLIFF 1.2 option setting 1.1 version info in file

### ISSUE THREAD

**Issue by nschonni** [WeblateOrg/weblate#1625]
### Steps to reproduce
1. Navigate to a component language translation (EX: https://hosted.weblate.org/projects/airsonic/develop/fr/)
2. From the Files menu, select "Download translatoin as XLIFF 1.2" 
3. Open the downloaded file, and verify its second line in a text editor

### Actual behaviour
The header of the downloaded file has the 1.1 version and schema
```xml
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.1" version="1.1">
```

### Expected behaviour
The header of the downloaded file has the 1.2 version and schema
```xml
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
```

### Server configuration
 * Weblate 2.16
 * Python 2.7.13
 * Django 1.11.2
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.3
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.13.0.windows.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.8.0
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.3
 * pytz 2017.2
 * git-svn 2.13.0.windows.1
 * Database backends: django.db.backends.sqlite3
Also confirmed on the hosted version for the repro steps

**Comment by nijel** [comment]
Apparently the label is wrong here, translate-toolkit generates Xlifff 1.1.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nschonni** [comment]
Yeah, looks like it's hardcoded https://github.com/translate/translate/blob/master/translate/storage/xliff.py#L92
Might make more sense to just drop the second `XLIFF` download option if they're both outputing 1.1 format files

**Comment by nijel** [comment]
The other one is with poxliff extensions, probably could use better description as well.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by pepapolach** [comment]
I just navigate to download translation files and found the same bug in Weblate 4.1.7.  In download section there are two options **XLIFF** and **XLIFF 1.1**
When I click on XLIFF the top two lines are:
`<?xml version='1.0' encoding='utf-8'?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.1" version="1.1">`

If I select XLIFF 1.1 top two lines are:
`<?xml version='1.0' encoding='UTF-8'?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.1" version="1.1">`

Is the version of **XLIFF** version 1.2 or 1.1? This is really confising.

**Comment by nijel** [comment]
There is "XLIFF with gettext extensions" and "XLIFF 1.1". The first one is also XLIFF 1.1 based.
