### ISSUE TITLE
Cannot page Glossary when filtering by letter

### ISSUE THREAD

**Issue by nschonni** [WeblateOrg/weblate#1626]
### Steps to reproduce
1. Navigate to a glossary of a particular language where on letter has more than one page of terms
2. Change the letter filter in the top right to any letter that has more than one page of terms
3. Click the next or last button

### Actual behaviour
The `?letter=FILTER_LETTER` query parameter is dropped, and you're taken to the unfiltered next or last page
Manually adding back the `letter` along with the `page` query parameter does have the correct result.

### Expected behaviour
The `letter` query paramater is retained, and the user is paged to the next filtered glossary page

### Server configuration

- Weblate 2.16
- Python 2.7.13
- Django 1.11.2
- six 1.10.0
- social-auth-core 1.4.0
- social-auth-app-django 1.2.0
- django-appconf 1.0.2
- Translate Toolkit 2.2.3
- Whoosh 2.7.4
- defusedxml 0.5.0
- Git 2.13.0.windows.1
- Pillow (PIL) 1.1.7
- dateutil 2.6.0
- lxml 3.8.0
- django-crispy-forms 1.6.1
- compressor 2.1.1
- djangorestframework 3.6.3
- pytz 2017.2
- git-svn 2.13.0.windows.1
- Database backends: django.db.backends.sqlite3

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
