### ISSUE TITLE
Any plans to support ModernMT?

### ISSUE THREAD

**Issue by mzeidhassan** [WeblateOrg/weblate#1627]
Hi Weblate team,

This is just a question and a suggestion.

With the current development in Neural Machine Translation Systems provided by Google Tensflow or Harvard OpenNMT, do you plan to provide MT connectors in Weblate?

There are some great projects being developed.

1. ModernMT: https://github.com/ModernMT/MMT; this is a great MT system that will be neural soon. 
2. OpenNMT: https://github.com/ModernMT/MMT

Thanks,
mzeid

**Comment by nijel** [comment]
We do already support several MT systems, see https://docs.weblate.org/en/latest/admin/machine.html

Writing connector is usually pretty easy, see current implementations in https://github.com/WeblateOrg/weblate/tree/master/weblate/trans/machine

**Comment by mzeidhassan** [comment]
Thanks Michal for your reply. I will give it a try with ModernMT and see when I have time. Wish you all the best with your great project.

**Comment by mzeidhassan** [comment]
Hi @nijel ,

This is great. I assume MMT would work with a local instance that doesn't use an API key. Am I right?

Thanks

**Comment by nijel** [comment]
You have to specify the key right now, but any value will work in case the server doesn't check it.

**Comment by mzeidhassan** [comment]
Thank you so much @nijel !
