### ISSUE TITLE
Differentiate name of strings file in iOS

### ISSUE THREAD

**Issue by reshadf** [WeblateOrg/weblate#1628]
### Steps to reproduce
1. in iOS I add localization to different xib files. 
2. The xib files create localization files calles [xibname-here].strings
3. I also have a Localizable.strings for strings used in code. ( which works fine ) 

My mask is
`Resources/*.lproj/Localizable.strings`

### Actual behaviour
Only gets the strings in Localizable.string

### Expected behaviour
Get all strings in all the files. 

I tried using an asterix * like so: `Resources/*.lproj/*.strings` but Weblate throws an error saying the name is too long. So how can I loop over all the files and not just with a specific name?

**Comment by nijel** [comment]
Weblate needs one translation component per file. If you want to import more files at once, please see https://docs.weblate.org/en/latest/admin/projects.html#automatic-creation-of-components
