### ISSUE TITLE
See difference between empty translated string and non translated string.

### ISSUE THREAD

**Issue by tuxayo** [WeblateOrg/weblate#1630]
Two examples at this date

https://hosted.weblate.org/translate/liberapay/core/zh/?checksum=4216a1c8957acaec
From another language, when looking in the `other languages` tab, I see that the status is "translated".
So it should be flagged as "Needs review" right? 

https://hosted.weblate.org/translate/liberapay/core/hu/?checksum=4216a1c8957acaec
From another language, when looking in the `other languages` tab, I see that the status is "not translated
So nothing should be done.

The question is: how can I check that a string has been translated as empty (to flag it when it's an obvious mistake) without going to another language and then go to the `other languages` tab to find the status.
Did I miss a status indicator in the main view of a string?

**Comment by nijel** [comment]
Most of supported file formats (if not all) are not able to differentiate between empty translation and not translated string, that's why Weblate doesn't differentiate it as well - simply the empty string is not translated.

**Comment by tuxayo** [comment]
Where does the Status in the other languages tab comes from? Does this mean that the format allow to know this information?

**Comment by nijel** [comment]
Maybe the needs review flag is not what you expect, see https://github.com/WeblateOrg/weblate/issues/1314
