### ISSUE TITLE
cleanuptrans taking long time

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1632]
### Steps to reproduce
1. run  ./manage.py cleanuptrans
2. wait until it finishes

### Actual behaviour
Right now it takes about 40-60 minutes to finish, even if run 2 times in row.
There's not much activity in the Weblate instance, so I'm not sure what's it munching for so long.

### Expected behaviour
Should work faster? There's only a handful of projects now, but I'm afraid if we start adding more, it might run for half a day, or longer.

### Server configuration
```
 * Weblate weblate-2.15
 * Python 2.7.5
 * Django 1.10.3
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.14.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.6.4
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2016.7
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.0
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
It's pretty much garbage collecting, so it is kind of expected to take long, but probably some optimization should be possible.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed (the command still takes quite long, but it is no longer needed to be executed, all cleanups happen automatically in the background).

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
