### ISSUE TITLE
Deleting characters from translation string does not remove "fuzzy" flag

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1633]
### Steps to reproduce
1. Find a fuzzy string
2. Delete some characters

### Actual behaviour
"Fuzzy" is still checked. When some characters are added, it's unchecked automatically.
It makes no sense when the only change in source string was deleting a part of it.

### Expected behaviour
"Fuzzy" unchecked automatically when deleting characters.
(Probably, it should also be unchecked when "Copy and save" from automatic translation is used).

### Server configuration
```
 * Weblate weblate-2.15
 * Python 2.7.5
 * Django 1.10.3
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.14.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.6.4
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2016.7
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.0
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
We're handling keypress event, so that should be covered as well:

https://github.com/WeblateOrg/weblate/blob/4b28ce23b16bd205b63ac904535c04095c138218/weblate/static/loader-bootstrap.js#L754-L755

**Comment by burner1024** [comment]
just fyi, ctrl-v also doesn't clear it.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
