### ISSUE TITLE
After adding an item to glossary, ctrl-enter doesn't save the string

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1634]
### Steps to reproduce
1. Go to translation window
2. Type translation
3. Add a term to glossary
4. Press ctrl-enter

### Actual behaviour
The same term is added to glossary again. (Because the focus is still on glossary "add" button).

### Expected behaviour
Translation string is saved.

### Server configuration
```
 * Weblate weblate-2.15
 * Python 2.7.5
 * Django 1.10.3
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.14.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.6.4
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2016.7
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.0
 * Database backends: django.db.backends.mysql
```

**Comment by burner1024** [comment]
Also, the glossary "add" field is not cleared after the term is added, see screnshot
<img width="285" alt="captura de pantalla 2017-09-28 a las 5 55 55 am" src="https://user-images.githubusercontent.com/1279852/30941875-cfc427a0-a411-11e7-800e-c60fd5eeb981.png">

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
