### ISSUE TITLE
File mask with multiple wildcards

### ISSUE THREAD

**Issue by Lozik** [WeblateOrg/weblate#1635]
### Steps to reproduce
1. Navigate to the "Add Component" page
2. Add a file mask that uses more than one wildcard (*). (i.e. `translations/*/*.php`)
3. Complete the necessary other fields
4. Click on "Save"

### Actual behaviour
An error message is shown:

> There are more files for single language (help), please adjust the mask and use components for translating different resources.

### Expected behaviour
The files should either correctly be imported or there should be a notice that * does not mean 'language code' but 'wildcard' and that every file that matches the pattern will be used.
I prefer the first version since it enables to have a structure like this:

- languages
  - en
    - en.php
    - invoice.php
    - system.php

(where each file is a translation file)

### Server configuration
 * Weblate weblate-2.16-390-gc92e065
 * Python 2.7.9
 * Django 1.11.5
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.2
 * lxml 3.4.0
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.6.4
 * pytz 2012c
 * pyLibravatar N/A
 * PyYAML 3.11
 * Mercurial 3.1.2
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
Weblate needs one translation component per file. If you want to import more files at once, please see https://docs.weblate.org/en/latest/admin/projects.html#automatic-creation-of-components

**Comment by Lozik** [comment]
Yes. In my situation, there is only one file (per language). But it contains 2 times the language code: /languages/en/en.php
In that case, it should either import the file correctly or there should be a notice that the * is a wildcard, not a language code placeholder.

**Comment by nijel** [comment]
Well `translations/*/*.php` would work AFAIK in that case if there were no other files in that directory.

Yes, it's a wildcard which is used a language code. You can use pretty much anything as language code, so it's not really distinguishable.

**Comment by nijel** [comment]
@stokito Use [Component discovery add-on](https://docs.weblate.org/en/latest/admin/addons.html#component-discovery) to import more components automatically.
