### ISSUE TITLE
Running Weblate on Docker

### ISSUE THREAD

**Issue by arvalaan** [WeblateOrg/weblate#1636]
### Steps to reproduce
1. Setup Weblate/Weblate Docker Container
2. Launch Container
3. Use HAProxy to forward

### Actual behaviour
Internal Server Error (500) on "/"

> 15/09/2017 17:22:362017-09-15 15:22:36,036 DEBG 'uwsgi' stderr output:
> 15/09/2017 17:22:36Internal Server Error: /
> 15/09/2017 17:22:36Traceback (most recent call last):
> 15/09/2017 17:22:36  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 131, in get_response
> 15/09/2017 17:22:36    response = middleware_method(request, response)
> 15/09/2017 17:22:36  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/middleware.py", line 58, in process_response
> 15/09/2017 17:22:36    request.session.save()
> 15/09/2017 17:22:36  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/cache.py", line 57, in save
> 15/09/2017 17:22:36    return self.create()
> 15/09/2017 17:22:36  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/cache.py", line 52, in create
> 15/09/2017 17:22:36    "Unable to create a new session key. "
> 15/09/2017 17:22:36RuntimeError: Unable to create a new session key. It is likely that the cache is unavailable.
> 15/09/2017 17:22:36
> 15/09/2017 17:22:362017-09-15 15:22:36,134 DEBG 'uwsgi' stderr output:
> 15/09/2017 17:22:36[pid: 104|app: 0|req: 2/3] 10.42.157.73 () {54 vars in 1763 bytes} [Fri Sep 15 15:22:32 2017] GET / => generated 90104 bytes in 4036 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)

### Expected behaviour
Page should be rendered

### Docker Environment Variables
WEBLATE_EMAIL_HOST=		smtp	
WEBLATE_EMAIL_HOST_USER=		
WEBLATE_EMAIL_HOST_PASSWORD=			
WEBLATE_ALLOWED_HOSTS=		example.domain.com	
WEBLATE_ADMIN_PASSWORD=		admin	
WEBLATE_ADMIN_NAME=		John Doe
WEBLATE_ADMIN_EMAIL=		example@domain.com	
POSTGRES_PASSWORD=		p4ssw0rd
POSTGRES_USER=			postgres	
POSTGRES_DATABASE=		weblate
WEBLATE_SERVER_EMAIL=		example@domain.com
WEBLATE_DEFAULT_FROM_EMAIL=	example@domain.com
WEBLATE_ENABLE_HTTPS=		1

**Comment by nijel** [comment]
The docker container uses memcache based sessions and that is not found in your setup. Generally it is recommended to base on docker-compose we provide, but you're right this should be documented.

Anyway this is the cache container:

https://github.com/WeblateOrg/docker/blob/7498fc2e5ae0dc6de04785cf30637fdead3fb9f3/docker-compose.yml#L25-L27

**Comment by nijel** [comment]
Also this can now be configured, see https://github.com/WeblateOrg/docker/pull/62
