### ISSUE TITLE
Missing line breaks in translation field after pulling translation files

### ISSUE THREAD

**Issue by saschagordner** [WeblateOrg/weblate#1637]
### Steps to reproduce
1. Export translations (in my case using Xcode)
2. Push them to Git.
3. Pull the Git changes via Weblate.

### Actual behaviour
Translation fields does not show line breaks, although there are line breaks existing in the .xlf file (regular line breaks, not `\n`).

### Expected behaviour
The translation field should utilize line breaks as they occur in the source (.xlf) file.

### Server configuration
```
* Weblate weblate-2.16
 * Python 2.7.6
 * Django 1.10.6
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0b6
 * Whoosh 2.7.2
 * defusedxml 0.4.1
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.3.3
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.0
 * pytz 2016.3
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 2.8.2
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
Maybe our documentation will help: https://docs.weblate.org/en/latest/formats.html#whitespace-and-newlines-in-xliff

**Comment by saschagordner** [comment]
Hey nijel,

thanks for the quick answer. 
I will try to figure out how I can append the `xml:space` attribute to the target (and maybe the source ) tags, because unfortunately Xcode does not support it.
