### ISSUE TITLE
Progress: no good/checks/fuzzy breakdown everywhere?

### ISSUE THREAD

**Issue by marcperrin** [WeblateOrg/weblate#1644]
I just realized that, when looking at a project:
- in #components, string-based progress is broken down between good/checks/fuzzy (great), but words-based progress isn't
- no breakdown at all in #languages 

Everything looks good at translation, subproject, or project x language level though - so is it just not implemented yet? Or is there a design issue I'm missing here?

(in code: generic_progress vs. translation_progress or words_progress)

Thanks

**Comment by nijel** [comment]
It's just not implemented. Actually words stats were added later to component view, that's why it's different at project and component view.

Anyway there is no technical reason for this and should not be hard to implement (the caches at translation level are already there, so it's just matter of aggregating them in one query).

**Comment by Ginger90** [comment]
@nijel I would love to take the task as a first timer. Thanks

**Comment by nijel** [comment]
Feel free to look into this, just ask me if you have any questions... 

30. září 2017 19:53:28 SELČ, Ginger90 <notifications@github.com> napsal:
>@nijel I would love to take the task as a first timer. Thanks

**Comment by ejuniorasas** [comment]
Hello can I contribute with some task? I am learning python and Django. 
Thanks!

**Comment by nijel** [comment]
@ejuniorasas You're surely welcome :-). 

Every Translation objects does have these counts, so it's just matter of aggregating them when showing those pages.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
