### ISSUE TITLE
Single-click immutable deployment

### ISSUE THREAD

**Issue by sedubois** [WeblateOrg/weblate#1645]
I just discovered your project, which looks promising :-)

I come from the context of being both a developer and someone in need of a translation infrastructure, and I don't know anything about this project besides reading the landing page a bit, but I am eager to try Weblate with my own data.

So the first thing I'd like to do is to run a new instance of the project to see how it all works with my own data, however it doesn't seem trivial at all. I don't know anything about Docker and such technologies.

Nowadays, the preferable method I know of consists in deploying any repo with a single click, e.g. using [Zeit Now](https://zeit.co/now). Zeit Now can deploy any project containing a `package.json`, a `Dockerfile`, or a set of static web content in an immutable way, so in that case Weblate should make use of an external database.

Would it be possible for this repo to be deployed in an immutable fashion and to have a `Dockerfile` configuration file, to allow anyone to easily test their own instance by running the [single command](https://zeit.co/blog/github) `now weblateorg/weblate`? That would be hugely helpful for someone like me who wants to give a try to your project.

Just sharing this thought as general feedback, feel free to close if it seems too far-fetched. Thank you very much.

**Comment by nschonni** [comment]
The docker repo is here https://github.com/WeblateOrg/docker

**Comment by nijel** [comment]
And we even have detailed docs for this: https://docs.weblate.org/en/latest/admin/deployments.html#docker

**Comment by sedubois** [comment]
Thank you. There is no mention of docker in the [quick setup guide](https://docs.weblate.org/en/latest/admin/quick.html), so it gives the impression that openshift is the recommended deployment (but currently doesn't work).

I was also trying to share the feedback that such a docker setup, simple though it may seem for someone familiar with the project, is actually still a bit complicated. I don't even know where the `docker-compose` command comes from, etc etc.

This isn't a complaint but just wanted to share where the friction can come from, for an external person discovering the project.

**Comment by nijel** [comment]
I've just added Docker instructions to quick start guide, thanks for mentioning that!

The docker-compose is AFAIK standard part of docker, I've never used docker without it ;-).

**Comment by sedubois** [comment]
Thanks. I just never used docker-compose. I still don't know how to start, i.e. which commands should I type, where should I go to learn more, should it be installed with homebrew or something else, etc? And why do I need to create a configuration file just to get started? Just sharing some thoughts. 

<img width="1680" alt="screen shot 2017-10-12 at 15 52 39" src="https://user-images.githubusercontent.com/4217871/31496882-cc7eb9d4-af65-11e7-9c37-01f61191f1eb.png">

**Comment by nijel** [comment]
No you don't have to create configuration initially, see https://docs.weblate.org/en/latest/admin/quick.html#installing-using-docker (but you will have to configure some things in the end, eg. for sending out emails).
