### ISSUE TITLE
Generate job, custom buttons, plugins

### ISSUE THREAD

**Issue by SamanthaAdrichem** [WeblateOrg/weblate#1647]
Is there a feature which will allow you to add a custom menu item to weblate?
Or even better, add a plugin?

Why am I asking this? Well...
In our system we're translating using weblate, however. These translations need to be generated.
At the moment the developer generates these before each upload using a bitbucket pipeline, this used to be a jenkins job.

What whould be nice is to add a custom plugin, that does the following:
Merge current translation changes (to prevent conflicts)
Lock translations
Start 'generate' job (pipeline, jenkins, whatever)
On success: update translations
Always unlock translations

But that might be a bit excessive, so the option to just add a custom menu item 'which calls' generate
would be nice too. 
Then we could just add api calls to our weblate instance to merge current translations and lock them.

Is there such a feature available or on planning? I don't mind if it's just like Jira, adding a custom 'external' menu which just links to other pages.

**Comment by nijel** [comment]
There is plan to have addons, which could probably cover this. In the original scope there was no plan for UI support, but that can be added later.

See https://github.com/WeblateOrg/weblate/issues/1353

**Comment by nijel** [comment]
The basics of addon system is there: https://docs.weblate.org/en/latest/admin/addons.html

It however doesn't provide any UI for addons (besides configuration) and allows them to subscribe only to few events. To extend it further I'd like to clarify what would fit your needs.

Would be enough to be able to add menu item and action to be triggered?
