### ISSUE TITLE
Add support for Microsoft Terminology Service API

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1653]
It would be great to have [Microsoft Terminology Service API][1] as an machine translation service in Weblate.

It doesn't provide full phrase translation, but extracts terminology, so it should be probably shown below full translations (thus reported with lower quality rank).

There is a Python client implementation in Pontoon:

https://github.com/mozilla/pontoon/blob/8a9b9fd465225e5c40c6ce95b9eb6e4dadb97a36/pontoon/machinery/views.py#L116-L164

[1]:https://www.microsoft.com/en-us/language/Microsoft-Terminology-API

**Comment by Brunux** [comment]
Hi @nijel I can work on this

**Comment by nijel** [comment]
Sure, you're welcome :-)

**Comment by nijel** [comment]
Implemented via https://github.com/WeblateOrg/weblate/pull/1673
