### ISSUE TITLE
Duplicate entries /api/units/

### ISSUE THREAD

**Issue by andonigonzalez** [WeblateOrg/weblate#1656]
### Steps to reproduce
1. Make a request to /api/units/?page1
2. Make a request to /api/units/?page2
3. Compare results

### Actual behaviour
If I search a resource from a specific project, component and language in the first page and I search the same resource in the second page, some resources appears duplicated

### Expected behaviour
Obviously, it does not have to return any duplicate entry

### Server configuration
* Weblate 2.16
 * Python 2.7.13
 * Django 1.11.5
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.4
 * pytz 2017.2
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Well `page1` and `page2` should not make difference, are you really using that? It should be `page=1`...

Anyway I can't reproduce that (with correct URLs).
