### ISSUE TITLE
search by date functionality

### ISSUE THREAD

**Issue by dachary** [WeblateOrg/weblate#1657]
It would be nice to have a search function that shows strings which have been translated before / after a certain date or source strings that have been modified before / after a cetain date. Here is how it looks, for instance, in transifex:

![4da2e8](https://user-images.githubusercontent.com/433594/31391068-d0452c42-add5-11e7-8ac2-8c2b97f89522.jpg)

**Comment by nijel** [comment]
There is already search for strings changed after given timestamp:

![screenshot-2017-10-10 weblate application - czech](https://user-images.githubusercontent.com/212189/31392254-11ab9e70-add9-11e7-8f52-31d2cd9bb569.png)

**Comment by dachary** [comment]
Hum, I'm running 2.14.1 and I don't see this. Looking at https://docs.weblate.org/en/latest/changes.html it does not look like this was a functionality added in 2.15 or 2.16. Am I missing something ?

**Comment by nijel** [comment]
It is new in 2.17. See c5f758824c9de7c23bc0dc3f376bba88e455d0dc and #1504.

**Comment by dachary** [comment]
oh ! Nice :-) Let's close this then.
