### ISSUE TITLE
Automatic translation using machine translation

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1658]
Currently there is automatic translation tool which allows to use translations from other components. It might be useful to have this for machine translation services as well (probably only for those which can translate anything like Google, Microsoft or Yandex, not using Weblate TM).

**Comment by nijel** [comment]
Currently there is automatic translation available, but only based on translations in other Weblate components. It would be useful to have this available based on the machine translation as well.

* User would choose machine translation service (contrary to original post, Weblate TM should be available as well)
* Threshold for quality could be specified

**Comment by mlaggner** [comment]
I will try to provide a PR for this feature

**Comment by nijel** [comment]
Thanks, that was fast :-) ... It's at https://github.com/WeblateOrg/weblate/pull/1840

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
