### ISSUE TITLE
Suggestion rejection reason: possibility of explaining why you reject a suggestion

### ISSUE THREAD

**Issue by emmapeel2** [WeblateOrg/weblate#1661]
### Steps to reproduce
1. Review Suggestions from other users
2. Vote agaisnt or delete suggestion

### Expected behaviour
It would be nice to have a text area to add a reason for the downvote-deletion, for the new translators to learn from the reviewers and get better with time.

**Comment by nijel** [comment]
How is this different from https://github.com/WeblateOrg/weblate/issues/1604? :-)

**Comment by emmapeel2** [comment]
Well, I see #1604 only for a comment, not an action. Just comments on the suggestion until the translators decide something.
This one is a reason for an action.

**Comment by comradekingu** [comment]
If the suggestion is made without a username, I think the comment on the suggestion should time out, so as not to pollute the fields with old stuff, possibly marketing spam.

**Comment by nijel** [comment]
The cleanup be toggled per project by installing [Remove old suggestions](https://docs.weblate.org/en/latest/admin/addons.html#remove-old-suggestions) or globally by [SUGGESTION_CLEANUP_DAYS](https://docs.weblate.org/en/latest/admin/config.html#suggestion-cleanup-days). But that's a bit offtopic here.

**Comment by emmapeel2** [comment]
Another thing that I wanted to add is that I want to correct the new contributor in private, for example if they copy an IMG tag without translating the alt attribute, I want to delete the suggestion, adding a reason.
So the new translator will see a message that says: 

your suggestion :
> here some diff of the suggestion, link, etc.
has been deleted because: 
> 'you need to translate the alt attribute as well' (the reason i gave during deletion)

without shaming the new translator forever in public with a comment on the string.

a bit like it is done in the mailman interface when you can give a reason for discarding or rejecting an email.
