### ISSUE TITLE
Strange word in Profil > Audit log

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#1668]
### Steps to reproduce
Connect to Profil > Audit log (see: https://hosted.weblate.org/accounts/profile/#audit)

### Actual behaviour
Activity column contains the word **Password** before the account name, see screen shot below.

### Expected behaviour
Where does this word is coming from (I didn't find it in the phrases to translate)?

![weblate - strange content](https://user-images.githubusercontent.com/1452146/32022765-ae77bc7a-b9d7-11e7-8487-f9ed9a0dc107.png)

**Comment by ldmpub** [comment]
I've found the translation and slitly changed it in french (see https://hosted.weblate.org/translate/weblate/master/fr/?checksum=486d46619c2a9375 ) but this message will still look quite strange => Audit page should inspire confidence, it's not the case yet.

**Comment by nijel** [comment]
It's name of the authentication, it can contain third party auth as well (eg. Facebook or GitHub).

However this one probably should be changed to be translatable:

https://github.com/WeblateOrg/weblate/blob/9626b914889fb92c4911605f9db694267ab94cb0/weblate/accounts/forms.py#L578

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by ldmpub** [comment]
I have checked =>correction is ok for me.
Thanks.
