### ISSUE TITLE
Setting notification when string for translation changes

### ISSUE THREAD

**Issue by necik** [WeblateOrg/weblate#1675]
### Steps to reproduce
In account settings of Weblate I have set up notifications when new string for translate is added. My interface is in Czech, the option is called "Upozornění na nové řetězce k překladu".

### Actual behaviour
When a new string for translation is added, I receive an email notification about this. But when some string for translation is just changed, I don't receive anything.

### Expected behaviour
I want to be notified also when original string for translation is changed by project owner, not only when a new is added. I didn't find an option in settings for this.

### Server configuration
I'm translating at https://translate.kontalk.org.

**Comment by nijel** [comment]
Apparently this has been already implemented without actually closing the issue, the notification is triggered on both newly added strings and strings which were translated before and now they are not, what typically happens after source string change:

https://github.com/WeblateOrg/weblate/blob/f9b13bfea13f19b8a2b66b2f06a4b19a494cd108/weblate/trans/models/translation.py#L321-L331

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
