### ISSUE TITLE
unable to login with a single auth method (openSUSE)

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1676]
If only one login method is configured, login is impossible.

### Steps to reproduce
1. Enable only 'social_core.backends.suse.OpenSUSEOpenId' and 'weblate.accounts.auth.WeblateUserBackend' in settings.py
2. Try to login
3. Enable also 'social_core.backends.google.GoogleOAuth2'

### Actual behaviour
If only 'social_core.backends.suse.OpenSUSEOpenId' is enabled, login is impossible. Login button on the home page redirects to https://<server>/accounts/login/opensuse/ and it fails.

If I also enable 'social_core.backends.google.GoogleOAuth2', Login button redirects to https://<server>/accounts/login/?next=/. Here openSUSE button is available. Clicking to that succeeds and displays https://<server>/accounts/login/opensuse/?next=/ with an only button Continue. It redirects to openSUSE server and succeeds.

Note that even https://<server>/accounts/login/opensuse/?next=/ fails with a single login method configured.

curl -i --insecure https://$server/accounts/login/opensuse/
HTTP/1.1 405 Method Not Allowed
Server: nginx/1.13.1
Date: Wed, 01 Nov 2017 16:50:53 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
X-XSS-Protection: 1; mode=block
Content-Language: en
Content-Security-Policy: default-src 'self'; style-src 'unsafe-inline' 'self'; img-src 'self'; script-src 'self'; connect-src 'self'; object-src 'none'; font-src 'self';child-src 'none'; frame-ancestors 'none';
Vary: Accept-Language, Cookie
Allow: POST
X-Frame-Options: SAMEORIGIN

### Expected behaviour
Single login menthod should work.

### Server configuration
 * Weblate 2.17.1
 * Python 2.7.13
 * Django 1.10.5
 * six 1.9.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.1.0
 * Whoosh 2.7.0
 * defusedxml 0.5.0
 * Git 2.13.6
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.6.1
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2016.10
 * pyuca N/A
 * PyYAML 3.12
 * Mercurial 4.2.3
 * git-svn 2.13.6
 * git-review 1.25.0
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Indeed that URL now needs POST method...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by macrojames** [comment]
I think I am still running in that issue.
I am using Docker version weblate/weblate:2.18-3

I only configured WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY + _SECRET.
When I click the Google Login button, I am running in 405 Method not allowed from URL
https://domain/accounts/login/google-oauth2/?next=/

**Comment by nijel** [comment]
2.18 should already have javascript based redirect which does post here....

**Comment by macrojames** [comment]
That's why I posted in this issue.

```
pip show weblate
Name: Weblate
Version: 2.18
```
![wb218](https://user-images.githubusercontent.com/482151/36419901-8d09ef00-1633-11e8-88ab-80d5190805dd.PNG)

```
<a class="btn btn-link link-post" href="/accounts/login/google-oauth2/?next=/">  | <i class="fa fa-lg fa-4x fa-wl-social fa-google"></i></a>
```
I get a javascript stacktrace on loading the page, maybe that is related?
![wb-jsstack](https://user-images.githubusercontent.com/482151/36420237-a6b92424-1634-11e8-99c0-8fbce3959788.PNG)

**Comment by nijel** [comment]
Does javascript work at all on your installation? It seems that your server is serving static files with wrong mime type. Anyway that is most likely not related to this issue - it's generic server configuration problem.

**Comment by macrojames** [comment]
It does. But /js/i18n/ gets a 302 Redirect to login page, that's html and of course not allowed.
I can solve that by setting WEBLATE_REQUIRE_LOGIN=0. 
But the other 2 lines remain. 

But you were right, that problem is not directly related. I could fix this problem by downgrading the http connection to 1.1. http2 multiplexing did deliver the dependencies in a different order.

**Comment by nijel** [comment]
@macrojames I'd like to get this sorted out for http2 as well, it should really work out of the box. Can we please move this topic to https://github.com/WeblateOrg/weblate/issues/1864?
