### ISSUE TITLE
Whiteboard message for one component shown in another components

### ISSUE THREAD

**Issue by lomaster1** [WeblateOrg/weblate#1677]
### Steps to reproduce
Create whiteboard message for one component
[Screenshot](http://prntscr.com/h548i3)

### Actual behaviour
Message shown in another components.
[Screenshot](http://prntscr.com/h5486s)

Also the same with languages.

### Expected behaviour
Message are show only in one component.

### Server configuration
Weblate in Docker
 * Weblate 2.17.1
 * Python 2.7.13
 * Django 1.11.6
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.7.0
 * pytz 2017.2
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
I think it's because you've specified project as well, it's then shown for the project (though I didn't look at the code).

**Comment by lomaster1** [comment]
I tried leave project empty, select only component, but after save project is full. 
Later I trying programatilly (in shell) add whiteboard message without project param.

**Comment by nijel** [comment]
I was really not sure, I was just guessing. I haven't used this feature yet :-). But indeed there seems to be a bug in this...

**Comment by lomaster1** [comment]
Programatilly (in shell) add whiteboard message without project param works.
Thx for fix, but the same with languages.

Messages for one component shown in all components and languages.

Screenshots:
http://prntscr.com/h5pkma
http://prntscr.com/h5pkw5
http://prntscr.com/h5pldu

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by burner1024** [comment]
@lomaster1 how do you add this programmatically?
I realize it's been fixed, but it may be a while until we manage to upgrade.
