### ISSUE TITLE
Error template language(source) does not match project source language(en_US)

### ISSUE THREAD

**Issue by MirabelaBiciin** [WeblateOrg/weblate#1678]
Hi,

We try to change the monolingual base language file for the components of our project.  We use json format. Our source file for all the components is named en_US.json but we need to change it with a  file named source.json. When we try to do this we get the error : Error template language(source) does not match project source language(en_US). How we can pass over it? We need to change the source language of the project? For now we use en_US. If you could help me with some answers it would be great.

Have a nice day!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
