### ISSUE TITLE
unable to configure self "url"

### ISSUE THREAD

**Issue by glensc** [WeblateOrg/weblate#1682]
### Steps to reproduce
1. open `https://weblate.example.org/admin/trans/subproject/4/change/`
2. change **Exported repository URL**: `http://example.com/git/group/project/` -> `https://weblate.example.org/git/group/project/`
3. save and reopen the page

### Actual behaviour

The change is not persisted, `example.com` is back

### Expected behaviour

I want the `example.com` (literally) be changed to `weblate.example.org`. my actual problem is that `example.com` is also included to commit messages what weblate makes.

in fact, the same docker image (custom built) is working on other instance, it's able to detect self-url, but place where it's broken the setup includes haproxy in front: haproxy -> nginx.

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

```
root@ygg /srv/weblate# docker-compose exec weblate bash -l
bash-4.4$ weblate list_versions
 * Weblate 2.16
 * Python 2.7.13
 * Django 1.11.4
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.4
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.14.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.6.0
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.3
 * pytz 2016.7
 * pyuca N/A
 * pyLibravatar N/A
 * tesserocr 2.1.3
 * Mercurial 3.7.3
 * git-svn 2.14.1
 * Database backends: django.db.backends.postgresql_psycopg2
bash-4.4$ 
```

**Comment by nijel** [comment]
See our FAQ: https://docs.weblate.org/en/latest/faq.html#why-do-links-contain-example-com-as-the-domain

**Comment by glensc** [comment]
sorry, wasn't around, but when i've switched to use official docker image, and the `http://example.com/` got changed to `http://*/`. weird neh.

**Comment by glensc** [comment]
btw, is there way to set value for initial installation? is there any docker-env variable used for that?

**Comment by glensc** [comment]
also: fixing site url was not sufficient, needed to re-save all projects (subcomponents)

**Comment by glensc** [comment]
also, how to handle protocol? it detected `http://` not `https://` ...

**Comment by nijel** [comment]
Saving again the components when using git exporter is indeed needed, this isn't detected automatically.

**Comment by glensc** [comment]
btw, unable to have that "git export url" readonly, is django-admin limitation again? as it's kind of confusing to have editable field, but it's not really editable because always value forced by application.

**Comment by glensc** [comment]
i've updated now to official docker image (2.17.1), but i'm unable to get rid of `http://*/` thing. i've configured site to be `hostname.example.lan:82`, but editing project (and project view itself) shows:

> Repository with Weblate translations: `http://*/git/project/translations/`

**Comment by nijel** [comment]
The field is editable because it is filled in automatically only if [gitexported module](https://docs.weblate.org/en/latest/admin/optionals.html#git-exporter) is installed. Even in that case it has to be editable because it doesn't work for Mercurial repos.

Anyway did the ENABLE_HTTPS setting work for you? It has to be set as [WEBLATE_ENABLE_HTTPS](https://docs.weblate.org/en/latest/admin/deployments.html#envvar-WEBLATE_ENABLE_HTTPS) in Docker environment.

PS: I've also improved the performance report page to show full URL as Weblate sees it in 3c8040334.

**Comment by glensc** [comment]
just updating the status:

- must set WEBLATE_ENABLE_HTTPS
- must save each project (component) for new url to appear
