### ISSUE TITLE
Support for Report Exporting/Importing

### ISSUE THREAD

**Issue by frankenfine** [WeblateOrg/weblate#1683]
Suggestion:
Allow for a data export which shows only untranslated strings and strings needing action (or other items besides well translated).

These could be used for offline translation and would give translators a good sense of what needs attention. 

Maybe allow these reports to get translated and uploaded as well. However, I think a good summary, by language, of what needs to be looked at is a good start.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
