### ISSUE TITLE
Add/Change group ACL - can't select multiple projects and subprojects

### ISSUE THREAD

**Issue by MirabelaBiciin** [WeblateOrg/weblate#1684]
Hi,

### Steps to reproduce
1. We created groups in Weblate Administration->Groups to limit the access of the translators to some languages. 
2. Group ACL's >Add group ACL:
-Groups( select group)
-Project( select project)
-Subproject( select subproject)

3.
### Actual behavior
When we create an ACL group or edit it, we have the possibility to select just one project and one subproject of the selected project. 

### Expected behavior
We need to have the possibility to select multiple/all project and subprojects  same as there is the possibility to select multiple filtered permissions. 
For example, the translators who translate French need to have access to all the projects and all the components of the projects, but just to translate French, nothing else. They should see the other translations and make suggestions, but not modify or add translations for the languages they don't have access. This is possible for source files, because we took off the permission "Can save template" for the groups from Groups. To limit the access to other languages, we can use ACL groups. There is a way to do it: creating an ACL group for each project and language, but there will be too many groups to manage and number of users will increase in time. Do you have other suggestions? Thanks a lot for helping us. 

Have a nice day!

**Comment by nijel** [comment]
You can create multiple Group ACL objects referencing same group.
