### ISSUE TITLE
Supporting Line Breaks in Android Strings Files

### ISSUE THREAD

**Issue by pschneider** [WeblateOrg/weblate#1686]
Hey,

we're facing issues with handling new lines in our translations. It seems that there's currently no way of adding new lines to a translation via Weblate.

As mentioned in #3606 exporting back to android strings would add an `\n` together with a real newline.
This doesn't seem to be the case because the `\n` which are stripped after importing von vcs are not added again when exporting.

An Android string like
`<string name="test_string">Test1\nTest2\nTest3</string>`
is imported as
```
Test1
Test2
Test3
```

after exporting it becomes an Android string

```
<string name="test_string">Test1
Test2
Test3</string>
```

which android treats as `Test1 Test2 Test3`

Expected behavior would be to get either

```
<string name="test_string">Test1\nTest2\nTest3</string>
```

or as mentioned

```
<string name="test_string">Test1\n
Test2\n
Test3</string>
```

Adding `\n` to a translation escapes the the backslash to `\\n` which, of course, does not work.

### Expected behaviour

I think if we're stripping out `\n` and show the strings with real new lines in Weblate it should support adding them on save. I don't think it's a good solution to expect the translators to add `\n` for each line break. Instead I think Weblate should handle that, as a string like 
`Test1\nTest2\nTest3` is barley readable.

Is there anything we can do to support the new lines? We tested with different Android SDKs (currently working with SDK 26.0.2) but none works with:
```
<string name="test_string">Test1
Test2
Test3</string>
```

Thanks in advance!

### Server configuration

```
 * Weblate weblate-2.16
 * Python 2.7.6
 * Django 1.10.6
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0b6
 * Whoosh 2.7.2
 * defusedxml 0.4.1
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 4.0.0
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.0
 * pytz 2016.3
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 2.8.2
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
Please upgrade translate-toolkit to at least 2.2.0 get fixes mentioned in https://github.com/WeblateOrg/weblate/issues/1418 and https://github.com/translate/translate/pull/3606.
