### ISSUE TITLE
How to set maxwidth parameter for android resource strings?

### ISSUE THREAD

**Issue by Bringoff** [WeblateOrg/weblate#1689]
It's more like a question I wasn't able to find out using documentation.
I use Weblate for an Android app translation. And I want to set length limit for some of the strings to prevent translators from creating too long translations. I know how to do it in xliff's xml files, but I use standard android string resources. Is it possible to add such parameters to android resources?

**Comment by nijel** [comment]
You can set this in Weblate, the Andoid format does not support this directly.

* Click on edit (pencil) icon next to flags on the string.
* Enter max-length:LENGTH as check flag.

See also https://docs.weblate.org/en/latest/admin/translating.html#additional-information-on-source-strings
