### ISSUE TITLE
Trailing semicolon warning for Greek question mark

### ISSUE THREAD

**Issue by gtsiam** [WeblateOrg/weblate#1692]
I'm working on [hosted.weblate.org](https://hosted.weblate.org/projects/godot-engine/godot/el/) (Currently running Weblate 2.18-dev), on a translation to Greek. When translating a sentence that ends with a question mark (which in Greek is the English semicolon), I get a trailing semicolon warning:

![Screenshot](https://user-images.githubusercontent.com/7459196/33100323-a1cb014e-cf1c-11e7-8e00-0f8e3ca84a43.png)

**Comment by nijel** [comment]
This should be fixed as of 7f17171de2f2d090e7aa5732cdb96c734ac0b2bf. I've just triggered checks rescan to update them.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
