### ISSUE TITLE
Flags "Other translation available" and "Translation not consistent" are badly raised and give extra and useless work to translators

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#1694]
### Actual behavior
On the Dashboard, false warnings "Other translation available" and "Translation not consistent" are displayed regularly when translation in an other sub-project for the same source string and key are empty ;-( => see screenshot attached.

Here is the scenario
- Translation in french for Android is OK
- Maybe an update of the resource is done
- Weblate raises "errors to check" on translator dashboard
- In fact errors are false positive => the translator has nothing to check nor to do (errors are raised because of comparison with empty strings). Extra useless work for translator ends by removing the false positive warnings to clear his dashboard.

### Expected behavior
No warning when translation is empty.
![other translation is empty](https://user-images.githubusercontent.com/1452146/33231767-2b8ae378-d1fb-11e7-9dc6-45e0abc7f020.png)

**Comment by nijel** [comment]
There is actually something to do - using the translation in other component.

**Comment by ldmpub** [comment]
What do you mean exactly: translators have something to do in this particular case? or weblate dev team has something to correct on weblate engine side?

**Comment by nijel** [comment]
Translators can click on the "Use this translation" button to bring them in sync. Or use autotranslate if there is more of them.

**Comment by ldmpub** [comment]
Ok, I will check the behavior next time this case will occur in one of my translations.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
