### ISSUE TITLE
weblate 2.17.1 migration rules are incomplete

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1695]
Set of migration rules provided in weblate-2.17.1 is reported as incomplete. And indeed, makemigrations generated two new rules. I am using weblate-2.17.1 with e7e9596 (Make single authentication backend setup work again).

### Steps to reproduce
1. Upgrade from Weblate 2.13.1 to 2.17.1
2. run ./manage.py makemigrations

### Actual behaviour
I got a message:
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

Migrations for 'trans':
  weblate/trans/migrations/0103_auto_20171128_1916.py:
    - Alter field committer_email on subproject
    - Alter field committer_name on subproject
    - Alter field file_format on subproject
    - Alter field vcs on subproject
Migrations for 'accounts':
  weblate/accounts/migrations/0033_auto_20171128_1916.py:
    - Alter field activity on auditlog

And one of generated migrations contains:
    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='committer_email',
            field=models.EmailField(default='weblate-noreply@opensuse.org', max_length=254, verbose_name='Committer email'),
        ),

So I am not sure, whether this warning was real, or whether it was triggered by the configuration file.

### Expected behaviour
No problems

### Server configuration
 * Weblate 2.17.1
 * Python 2.7.13
 * Django 1.10.5
 * six 1.9.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.1.0
 * Whoosh 2.7.0
 * defusedxml 0.5.0
 * Git 2.13.6
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.6.1
 * django-crispy-forms 1.7.0
 * compressor 2.1.1
 * djangorestframework 3.6.3
 * pytz 2016.10
 * PyYAML 3.12
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by stanislav-brabec** [comment]
The report was just updated. Unrelated error messages were deleted.

**Comment by nijel** [comment]
These errors should be harmless, but some probably could be fixed.

See also our FAQ: https://docs.weblate.org/en/latest/faq.html#why-do-i-get-a-warning-about-not-reflected-changes-on-database-migration
