### ISSUE TITLE
lots of errors while loading /widgets/foo/

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1696]
While loading widgets page, I am getting lots of error reports. I am using weblate-2.17.1 with e7e9596 (Make single authentication backend setup work again).

### Steps to reproduce
1. Go to https://l10n.opensuse.org/widgets/yast-cio/
2. wait for server error e-mails

### Actual behaviour
14 errror e-mails

Here is a short summary:
weblate-noreply@opensuse.org[weblate-admin] [openSUSE Weblate] ERROR (EXTERNAL IP): Internal Server Error: /widgets/yast-cio/-/svg-badge.svg
Internal Server Error: /widgets/yast-cio/-/svg-badge.svg IOError at /widgets/yast-cio/-/svg-badge.svg cannot open resource Request Method: GET Request URL: https://l10n.opensuse.org/widgets/yast-cio/-/svg-badge.svg Django Version: 1.10.5 Python Executable: /usr/sbin/uwsgi Python Version: 2.7.13 P…
weblate-noreply@opensuse.org[weblate-admin] [openSUSE Weblate] ERROR (EXTERNAL IP): Internal Server Error: /widgets/yast-cio/-/287x66-white.png
Internal Server Error: /widgets/yast-cio/-/287x66-white.png IOError at /widgets/yast-cio/-/287x66-white.png cannot open resource Request Method: GET Request URL: https://l10n.opensuse.org/widgets/yast-cio/-/287x66-white.png Django Version: 1.10.5 Python Executable: /usr/sbin/uwsgi Python Version:…
weblate-noreply@opensuse.org[weblate-admin] [openSUSE Weblate] ERROR (EXTERNAL IP): Internal Server Error: /widgets/yast-cio/-/287x66-grey.png
Internal Server Error: /widgets/yast-cio/-/287x66-grey.png IOError at /widgets/yast-cio/-/287x66-grey.png cannot open resource Request Method: GET Request URL: https://l10n.opensuse.org/widgets/yast-cio/-/287x66-grey.png Django Version: 1.10.5 Python Executable: /usr/sbin/uwsgi Python Version: 2.…
weblate-noreply@opensuse.org[weblate-admin] [openSUSE Weblate] ERROR (EXTERNAL IP): Internal Server Error: /widgets/yast-cio/-/287x66-grey.png
Internal Server Error: /widgets/yast-cio/-/287x66-grey.png IOError at /widgets/yast-cio/-/287x66-grey.png cannot open resource Request Method: GET Request URL: https://l10n.opensuse.org/widgets/yast-cio/-/287x66-grey.png Django Version: 1.10.5 Python Executable: /usr/sbin/uwsgi Python Version: 2.…
weblate-noreply@opensuse.org[weblate-admin] [openSUSE Weblate] ERROR (EXTERNAL IP): Internal Server Error: /widgets/yast-cio/-/88x31-white.png
Internal Server Error: /widgets/yast-cio/-/88x31-white.png IOError at /widgets/yast-cio/-/88x31-white.png cannot open resource Request Method: GET Request URL: https://l10n.opensuse.org/widgets/yast-cio/-/88x31-white.png Django Version: 1.10.5 Python Executable: /usr/sbin/uwsgi Python Version: 2.…
weblate-noreply@opensuse.org[weblate-admin] [openSUSE Weblate] ERROR (EXTERNAL IP): Internal Server Error: /widgets/yast-cio/-/287x66-white.png
Internal Server Error: /widgets/yast-cio/-/287x66-white.png IOError at /widgets/yast-cio/-/287x66-white.png cannot open resource Request Method: GET Request URL: https://l10n.opensuse.org/widgets/yast-cio/-/287x66-white.png Django Version: 1.10.5 Python Executable: /usr/sbin/uwsgi Python Version:…
weblate-noreply@opensuse.org[weblate-admin] [openSUSE Weblate] ERROR (EXTERNAL IP): Internal Server Error: /widgets/yast-cio/-/svg-badge.svg
Internal Server Error: /widgets/yast-cio/-/svg-badge.svg IOError at /widgets/yast-cio/-/svg-badge.svg cannot open resource Request Method: GET Request URL: https://l10n.opensuse.org/widgets/yast-cio/-/svg-badge.svg Django Version: 1.10.5 Python Executable: /usr/sbin/uwsgi Python Version: 2.7.13 P…
weblate-noreply@opensuse.org[weblate-admin] [openSUSE Weblate] ERROR (EXTERNAL IP): Internal Server Error: /widgets/yast-cio/-/287x66-black.png
Internal Server Error: /widgets/yast-cio/-/287x66-black.png IOError at /widgets/yast-cio/-/287x66-black.png cannot open resource Request Method: GET Request URL: https://l10n.opensuse.org/widgets/yast-cio/-/287x66-black.png Django Version: 1.10.5 Python Executable: /usr/sbin/uwsgi Python Version:…
weblate-noreply@opensuse.org[weblate-admin] [openSUSE Weblate] ERROR (EXTERNAL IP): Internal Server Error: /widgets/yast-cio/-/88x31-black.png
Internal Server Error: /widgets/yast-cio/-/88x31-black.png IOError at /widgets/yast-cio/-/88x31-black.png cannot open resource Request Method: GET Request URL: https://l10n.opensuse.org/widgets/yast-cio/-/88x31-black.png Django Version: 1.10.5 Python Executable: /usr/sbin/uwsgi Python Version: 2.…
weblate-noreply@opensuse.org[weblate-admin] [openSUSE Weblate] ERROR (EXTERNAL IP): Internal Server Error: /widgets/yast-cio/-/287x66-black.png
Internal Server Error: /widgets/yast-cio/-/287x66-black.png IOError at /widgets/yast-cio/-/287x66-black.png cannot open resource Request Method: GET Request URL: https://l10n.opensuse.org/widgets/yast-cio/-/287x66-black.png Django Version: 1.10.5 Python Executable: /usr/sbin/uwsgi Python Version:…
weblate-noreply@opensuse.org[weblate-admin] [openSUSE Weblate] ERROR (EXTERNAL IP): Internal Server Error: /widgets/yast-cio/-/88x31-grey.png
Internal Server Error: /widgets/yast-cio/-/88x31-grey.png IOError at /widgets/yast-cio/-/88x31-grey.png cannot open resource Request Method: GET Request URL: https://l10n.opensuse.org/widgets/yast-cio/-/88x31-grey.png Django Version: 1.10.5 Python Executable: /usr/sbin/uwsgi Python Version: 2.7.1…
weblate-noreply@opensuse.org[weblate-admin] [openSUSE Weblate] ERROR (EXTERNAL IP): Internal Server Error: /widgets/yast-cio/-/88x31-grey.png
Internal Server Error: /widgets/yast-cio/-/88x31-grey.png IOError at /widgets/yast-cio/-/88x31-grey.png cannot open resource Request Method: GET Request URL: https://l10n.opensuse.org/widgets/yast-cio/-/88x31-grey.png Django Version: 1.10.5 Python Executable: /usr/sbin/uwsgi Python Version: 2.7.1…
weblate-noreply@opensuse.org[weblate-admin] [openSUSE Weblate] ERROR (EXTERNAL IP): Internal Server Error: /widgets/yast-cio/-/88x31-black.png
Internal Server Error: /widgets/yast-cio/-/88x31-black.png IOError at /widgets/yast-cio/-/88x31-black.png cannot open resource Request Method: GET Request URL: https://l10n.opensuse.org/widgets/yast-cio/-/88x31-black.png Django Version: 1.10.5 Python Executable: /usr/sbin/uwsgi Python Version: 2.…
weblate-noreply@opensuse.org[weblate-admin] [openSUSE Weblate] ERROR (EXTERNAL IP): Internal Server Error: /widgets/yast-cio/-/88x31-white.png
Internal Server Error: /widgets/yast-cio/-/88x31-white.png IOError at /widgets/yast-cio/-/88x31-white.png cannot open resource Request Method: GET Request URL: https://l10n.opensuse.org/widgets/yast-cio/-/88x31-white.png Django Version: 1.10.5 Python Executable: /usr/sbin/uwsgi Python Version: 2.…

### Expected behaviour
No error messages.

### Server configuration
 * Weblate 2.17.1
 * Python 2.7.13
 * Django 1.10.5
 * six 1.9.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.1.0
 * Whoosh 2.7.0
 * defusedxml 0.5.0
 * Git 2.13.6
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.6.1
 * django-crispy-forms 1.7.0
 * compressor 2.1.1
 * djangorestframework 3.6.3
 * pytz 2016.10
 * PyYAML 3.12
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
How did you install? It seems that it fails to load fonts used for rendering those. Maybe just your [TTF_PATH](https://docs.weblate.org/en/latest/admin/config.html#std:setting-TTF_PATH) setting is wrong?

**Comment by stanislav-brabec** [comment]
TTF_PATH is not set in settings.py nor system environment.

Following fonts are installed:
/usr/share/weblate/weblate/static/font-awesome/fonts/fontawesome-webfont.ttf
/usr/share/weblate/weblate/static/font-linux/font-linux.ttf
/usr/share/weblate/weblate/ttf
/usr/share/weblate/weblate/ttf/DejaVuSans-Bold.ttf
/usr/share/weblate/weblate/ttf/DejaVuSans.ttf
/usr/share/weblate/weblate/ttf/DroidSans-Bold.ttf
/usr/share/weblate/weblate/ttf/DroidSans.ttf
/usr/share/weblate/weblate/ttf/DroidSansFallback.ttf
/usr/share/weblate/weblate/ttf/LICENSE
/usr/share/weblate/weblate/ttf/README.txt

**Comment by nijel** [comment]
It should point to  /usr/share/weblate/weblate/ttf. Maybe there is wrong setting for BASE_DIR? See https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-2-16-to-2-17

**Comment by stanislav-brabec** [comment]
BASE_DIR = "/usr/share/weblate/weblate"

I am always using the up-to-date default configuration file as a base for my customizations. Only few variables are set differently. Nothing of them is related to font loading.

**Comment by nijel** [comment]
IMHO it really should be BASE_DIR = "/usr/share/weblate", this has been changed in 2.17 (to be consistent with default Django configuration).

**Comment by stanislav-brabec** [comment]
In that case it is wrong out of the box:
BASE_DIR = "/usr/share/weblate/weblate" can be found in Weblate-2.17.1/weblate/settings.py after calling make.

Confirming that change to "/usr/share/weblate" fixes the problem.

**Comment by nijel** [comment]
After calling make? There is no Makefile in our sources...

The example config calcualtes this:

https://github.com/WeblateOrg/weblate/blob/adfcedc9729cd07184215e17bd70f5c314b98283/weblate/settings_example.py#L60

Our spec file hardcodes it to /usr/share/weblate at build:

https://github.com/WeblateOrg/weblate/blob/adfcedc9729cd07184215e17bd70f5c314b98283/weblate.spec#L94

However [your spec file](https://build.opensuse.org/package/view_file/M17N:l10n.opensuse.org/weblate/weblate.spec?expand=1#L110) has it wrong:

```
sed -i 's@^BASE_DIR = .*@BASE_DIR = "%{WLDIR}/weblate"@g' weblate/settings.py
```

**Comment by stanislav-brabec** [comment]
Thanks for pointing to that.

It was based on your https://build.opensuse.org/package/view_file/home:Nijel:weblate/weblate/weblate.spec?expand=1. It is now out of date.

I will update spec file using your one.

**Comment by nijel** [comment]
Hmm, I probably should drop that repo. I really don't have time to maintain that...
