### ISSUE TITLE
feature request: duplicate component

### ISSUE THREAD

**Issue by azachar** [WeblateOrg/weblate#1697]
Hello, 

I would like to cover a simple scenario when I want to translate multi branches of the project.

So I created a master component, now I want to translate also the staging branch but it requires to fill up all the details in the component add form again with the only difference, the branch name.

Would it be possible to duplicate branch, or somehow simplify this use case. Or am I doing something wrong here?

Thanks - Díky!

Best regards,
Andrej

**Comment by nijel** [comment]
There is currently no way to make this easier.

**Comment by nijel** [comment]
Currently being implemented here: https://github.com/WeblateOrg/weblate/pull/2820

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
