### ISSUE TITLE
searching source strings sometime fail in Arabic

### ISSUE THREAD

**Issue by dachary** [WeblateOrg/weblate#1699]
### Steps to reproduce

1. https://weblate.securedrop.club/projects/securedrop/securedrop/ar/#search
2. search Because

### Actual behaviour

Nothing is found.

### Expected behaviour

https://weblate.securedrop.club/translate/securedrop/securedrop/ar/?type=all&offset=162 is found

### Server configuration

<pre>
$ sudo docker-compose run weblate list_versions
WARNING: Found orphan containers (weblate_https-portal_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting weblate_cache_1 ... 
Starting weblate_database_1 ... done
Postgres is up
 * Weblate 2.17.1
 * Python 2.7.13
 * Django 1.11.6
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.7.0
 * pytz 2017.2
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2
</pre>

Note that looking for the same string in French finds two source strings

https://weblate.securedrop.club/translate/securedrop/securedrop/fr/?checksum=&offset=&q=Because&search=ftx&source=on&target=on&type=all&ignored=False&date=&only_user=&exclude_user=

The index was rebuilt with
<pre>
$ sudo docker-compose run weblate rebuild_index --all --clean
WARNING: Found orphan containers (weblate_https-portal_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting weblate_cache_1 ... 
Starting weblate_database_1 ... done
Postgres is up
Processing 0.0%
Processing 25.6%
Processing 51.2%
Processing 76.8%
Operation completed
</pre>
just to rule out index corruption.

**Comment by nijel** [comment]
The search seems to be working now. Did you something to fix that?

**Comment by dachary** [comment]
I did not do anything. That's a miracle 🐰 ! I'll close it since there is no longer a reproducer, sorry for the noise.

**Comment by nijel** [comment]
I guess the index rebuild did fix that, the workers might have opened the old one for some time still...

**Comment by dachary** [comment]
>  the workers might have opened the old one for some time still...
Oh... that would explain it. Thanks for the hint :-)
