### ISSUE TITLE
Missing documention version

### ISSUE THREAD

**Issue by azachar** [WeblateOrg/weblate#1700]
Hello, 
the doc version is not available at https://docs.weblate.org/en/weblate-2.17.1/user/translating.html

But is available at https://docs.weblate.org/en/weblate-2.17/user/translating.html
Cheers,
Andrej

**Comment by nijel** [comment]
Apparently this is part of the release process I always forget. Build triggered now, should appear online soon.

**Comment by azachar** [comment]
Wow, that is a blazing speed! Thanks a lot!
