### ISSUE TITLE
Search button should be accessible from Translation Panel

### ISSUE THREAD

**Issue by Cahir5** [WeblateOrg/weblate#1709]
### Steps to reproduce
1. Enter one of your projects.
2. Go to Translation Panel
3. Try to Search some phrases from there

### Actual behaviour
Search button is accessible from the Project Overview panel. This is somewhat cumberstone, because I use Search option often and currently I need to switch to Project Overview everytime I want to search some phrases.

### Expected behaviour
Search button should be also accessible from the Translation Panel, so I don't need to switch to Project Overview panel when I need to search some phrases.

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

**Comment by nijel** [comment]
There *is* search at translation level: https://hosted.weblate.org/projects/weblate/master/cs/#search

**Comment by ALIENQuake** [comment]
@nijel He is talking about this wiew https://tra.bgforge.net/translate/baldurs-gate/ascension/pl/?type=nottranslated

**Comment by nijel** [comment]
Okay, then just click on the current filter and you can search:

![screenshot-2017-12-4 baldur s gate ascension - polstina](https://user-images.githubusercontent.com/212189/33571361-11c36546-d930-11e7-910a-f3fae9367d1b.png)

**Comment by Cahir5** [comment]
Hi Michal,

 

Of course there is an option to Search from there, silly me. Sorry, but I’m new in using this tool and only started to explore it. Should been more inquisitive in this case.

 

Anyway, thanks for fast reply!

 

Regards,

Cahir

**Comment by ALIENQuake** [comment]
@nijel Good to know, but it's a design issue. Until you add "Search" bar/button or other indicator of such feature, it's not existing for end-user. Thanks anyway.

**Comment by nijel** [comment]
Well any suggestion how to improve the UI is welcome. Where do you think the "Search" button should be located?

**Comment by nijel** [comment]
Also the search was located in bottom of the page, what also was not well received either, see https://github.com/WeblateOrg/weblate/issues/1061

**Comment by nijel** [comment]
I've added the search icon to the button, hopefully that makes it easier to spot.

Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
