### ISSUE TITLE
There should be possible to access all files from specific repository

### ISSUE THREAD

**Issue by Cahir5** [WeblateOrg/weblate#1710]
### Steps to reproduce
1. Go to Project overview
2. Try to access one specific file from repository
3.

### Actual behaviour
Currently the only way to access translated strings is by opening one of the following categories:
* All strings
* Translated strings
* Strings needing action
* Not translated strings
* Random strings for review

### Expected behaviour
There should be also an option to access translated lines in one specific file from repository. For example I want to translate files one by one and want to open first file, translate all lines there, and then go to another file. Currently it's not possible (I think).

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

**Comment by nijel** [comment]
Have you tried the *Files* menu?

![screenshot-2017-12-4 weblate application - czech](https://user-images.githubusercontent.com/212189/33571214-a80bce4a-d92f-11e7-9f6f-f2cb2758e607.png)

**Comment by Cahir5** [comment]
Yes, I know the _Files_ menu. But it can be used only to download translation in different formats. What I had in mind is the possibility to enter specific file (without downloading it) and translate it from there.

**Comment by nijel** [comment]
Only files configured by admin can be translated, that's intentional.
