### ISSUE TITLE
Missing Other Translation tab for some translated units

### ISSUE THREAD

**Issue by pleonex** [WeblateOrg/weblate#1711]
### Steps to reproduce
For some po files, some untranslated units shows a matched *similar translation* in another file (as expected). But if we go into that file, it doesn't show the *Other translation* tab with the previous matched untranslated similar translation. It's like an asymmetrical behavior.

### Actual behaviour
Large file with the untranslated unit shows *Other translations* tab with the matched similar unit in other file.
![image](https://user-images.githubusercontent.com/3107481/33582092-c84c71d6-d953-11e7-8d0d-6333a0bfbb70.png)

But if we go into that file with the translation, we don't see the *Other translations* tab with the previous file that have the untranslated unit
![image](https://user-images.githubusercontent.com/3107481/33582127-f92e7c90-d953-11e7-985b-0ab204a6dedb.png)

### Expected behaviour
The *Other translation* tab should appear in both cases so it's easy to find similar untranslated texts. This doesn't happen for all files, in most cases it works as expected, but there are like some corner cases that it doesn't. Could it be related to the number of units?

### Server configuration
```
 * Weblate 2.17.1
 * Python 2.7.13
 * Django 1.11.7
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.7.3
 * pytz 2017.3
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2
```

**Comment by nijel** [comment]
AFAIK it's not shown because the string is not translated.

**Comment by pleonex** [comment]
Ok, then I understand that the expected behavior is that if string is already translated it doesn't show "*Other translations*" that are not yet translated since you can't take use its translations. It makes sense.

In our case, I would find useful to show all the similar translations, even the untranslated ones. So we can go to all the similar cases and translate them at the same time. Thanks!

**Comment by nijel** [comment]
Honestly I'm not really sure what is best behavior in this case. This feature has been changed so many times, that current behavior is result of many iterative changes rather than original design decisions.

**Comment by pleonex** [comment]
I see, well I was able to make it work (I think) by removing this [line](https://github.com/WeblateOrg/weblate/blob/37d7ac93e70a37f96ad75b9cf39cfbd671e6e9b0/weblate/trans/views/edit.py#L78). Having this local change is ok for me, so we can close the issue.
