### ISSUE TITLE
add /git to LOGIN_REQUIRED_URLS_EXCEPTIONS

### ISSUE THREAD

**Issue by derikson** [WeblateOrg/weblate#1712]
When logins are required, attempting to clone a git repository redirects the git client to the login page instead of asking for basic auth. The `/git` path should be added to the `LOGIN_REQUIRED_URLS_EXCEPTIONS` of `settings_example.py`, to the docker configuration, or otherwise documented.

Unless I'm mistaken about the problem. This is what fixed it for me.

### Steps to reproduce
1. Enable the example `LOGIN_REQUIRED_URLS`
2. Attempt to clone the git repository using the documented URL

### Actual behaviour
Git displays the error: `fatal: unable to update url base from redirection:` …

### Expected behaviour
The repository should be cloned.

### Server configuration
* Weblate 2.14.1
 * Python 2.7.13
 * Django 1.11.6
 * six 1.10.0
 * social-auth-core 1.5.0
 * social-auth-app-django 2.0.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.1
 * pytz 2017.2
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
This is not be necessary as of 8308eacf1bbc03f8f40a40c349f4ef76a10e4990 and 6786e58e303d8ebd5e31d395d360ab45532ea1f3.
