### ISSUE TITLE
'pip install weblate' installs Django 2.0

### ISSUE THREAD

**Issue by muranamihdk** [WeblateOrg/weblate#1714]
Django 2.0 released December 2, 2017. ‘pip install weblate’ installs Django 2.0 now. The Weblate doesn’t run with Django 2.0 because of some errors.
Django version must be ‘Django>=1.11,<2.0’ until Weblate adopts Django 2.0.

**Comment by nschonni** [comment]
Duplicate of #1707

**Comment by muranamihdk** [comment]
Thanks. I’m sorry for my being careless.
