### ISSUE TITLE
Valid HTML content triggers "Invalid XML" error

### ISSUE THREAD

**Issue by nightpool** [WeblateOrg/weblate#1715]
### Steps to reproduce
1. create a source string like `This is<br>valid HTML`
2. translate that string into at least 1 other language

### Actual behaviour
The translation is failing the check "invalid XML"

### Expected behaviour
There is no failing check. (Probably this should be behind a check option, something like `xml-as-html`)

**Comment by nijel** [comment]
The XML check should fire only if the source is valid XML, what in this case is not. Are you sure this is exact source string where your can reproduce this?

**Comment by nightpool** [comment]
Here's the exact source string:

`Introductory paragraph on the frontpage and in meta tags. <br> You can use HTML tags, in particular <code> 1&lt; 2a&gt; 3</code> 4 and <code> 5&lt; 6em&gt; 7</code> 8.`

this is valid HTML, but not valid XML. It would be very useful if we could check for valid HTML in some way, and matching HTML tags, to make sure translations don't have any possible errors that would affect the display of text.

**Comment by nightpool** [comment]
(The main difference between html and xml in this case is that HTML allows for a variety of "self-closing" tags to omit their end tag depending on type and context)

**Comment by nijel** [comment]
What Weblate version do you use? I'm not able to reproduce this behavior (I've just added this to our testsuite).
