### ISSUE TITLE
Importing Joomla! INI files adds surrounding "_QQ_" on every string

### ISSUE THREAD

**Issue by nikosdion** [WeblateOrg/weblate#1716]
### Steps to reproduce
1. Create a language in the Joomla! INI format
2. Import an INI file

Sample:
```
COM_EXAMPLE_FOO="This is a test"
```

### Actual behaviour
The string is imported as
```
COM_EXAMPLE_FOO=""_QQ_"This is a test"_QQ_""
```

### Expected behaviour
The string should have been imported as
```
COM_EXAMPLE_FOO="This is a test"
```

### Server configuration
Output of `./manage.py list_versions`

```
 * Weblate 2.17
 * Python 2.7.12
 * Django 1.11.6
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.0
 * defusedxml 0.4.1
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.5.0
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.1
 * pytz 2014.10
 * pyuca N/A
 * python-bidi 0.4.0
 * PyYAML 3.11
 * Mercurial 3.7.3
 * Database backends: django.db.backends.mysql
```

### Further notes

I think this happens because the import treats the surrounding double quotes as part of the string proper instead of file format markup. Unfortunately I don't speak enough Python to debug this.

I do speak plenty of PHP and have been a long time contributor to Joomla! itself, though. In that capacity I can tell you that Joomla! no longer uses `"_QQ_"` since around 2014. Instead, double quotes in strings are supposed to be escaped with a backslash i.e. `\"`. Example:
```
COM_EXAMPLE_TEST="This is a \"special\" string."
```
As a result the generated Joomla! INI strings should not use `"_QQ_"` but `\"`. If you need me to file another issue for this let me know.

Dĕkuji :)

**Comment by nijel** [comment]
It seems that `"_QQ_"` is way Joomla decided to escape quotes, see https://docs.joomla.org/Specification_of_language_files. However it seems that the surrounding quotes are left as part of the string, am I right?

**Comment by nikosdion** [comment]
You're actually correct. It looks like nobody bothered to update Joomla's language file specification. Therefore you have to still use `"_QQ_"` to escape double quotes. I guess I have to file a bug report with Joomla! about this.

Also correct, the problem with the surrounding quotes (markup) becoming part of the string on import does exist. This is what needs fixing in Weblate.

Thank you!

**Comment by fede91it** [comment]
Hello!

I agree with the resolution of the problem, can we put a fix?

**Comment by fede91it** [comment]
@nijel please create a component from git@github.com:fede91it/weblate-joomla-quotes-test.git and create a new translation, than export the created file.

### Original File

```ini
MOD_TEST_FOOBAR="Lorem ipsum dolor sit amet"
```

### Actual Exported File

```ini
MOD_TEST_FOOBAR=""_QQ_"Lorem ipsum"_QQ_""
```

### Expected Exported File

```ini
MOD_TEST_FOOBAR="Lorem ipsum"
```

The actual behavior is totally wrong beacause it wraps each string in double quotes.

I had a lot of year of experience in Joomla development and I never saw that "_QQ_" syntax

**Comment by nikosdion** [comment]
If you want a REAL file which gets imported wrong every single time, here you go:

```INI
LOGINGUARD="Akeeba LoginGuard"
COM_LOGINGUARD="Akeeba LoginGuard"
COM_LOGINGUARD_HEAD_TFA_PAGE="Tvåstegsverifiering"
COM_LOGINGUARD_HEAD_WELCOME="Välkommen!"
COM_LOGINGUARD_STATUS_NOTREADY="INTE KLAR"
COM_LOGINGUARD_STATUS_NOTREADY_INFO="Akeeba LoginGuard kommer inte att fungera korrekt förrän du åtgärdat problemen nedan."
COM_LOGINGUARD_STATUS_ALMOSTREADY="NÄSTAN KLAR"
```

It was last imported as:

```INI
LOGINGUARD=""_QQ_"Akeeba LoginGuard"_QQ_""
COM_LOGINGUARD=""_QQ_"Akeeba LoginGuard"_QQ_""
COM_LOGINGUARD_HEAD_TFA_PAGE=""_QQ_"Tvåstegsverifiering"_QQ_""
COM_LOGINGUARD_HEAD_WELCOME=""_QQ_"Välkommen!"_QQ_""
COM_LOGINGUARD_STATUS_NOTREADY=""_QQ_"INTE KLAR"_QQ_""
COM_LOGINGUARD_STATUS_NOTREADY_INFO=""_QQ_"Akeeba LoginGuard kommer inte att fungera korrekt förrän du åtgärdat problemen nedan."_QQ_""
COM_LOGINGUARD_STATUS_ALMOSTREADY=""_QQ_"NÄSTAN KLAR"_QQ_""
```

This happened three days ago with Weblate 2.19.1 using the upload file feature. Sorry for the delayed response, it was the first of May which is a public holiday here.

What I _suspect_ is going on is below. Feel free to ignore this bit as purely speculative :)

The `"_QQ_"` syntax is a leftover from Joomla! 1.6 and the need to support PHP versions 5.3.0 to 5.3.3 inclusive on hosts which disabled parsing an entire INI file but did allow you to parse INI _strings_. The difference in behavior meant that double quotes inside an INI string could not be escaped with a backslash (`\"`) but had to be escaped using PHP define interpolation. Therefore Joomla! defines `_QQ_` to be equal to `"` and due to the PHP performing constant interpolation the `"_QQ_"` string is interpreted as a double quote when the INI file is read.

But, that's mostly historic and irrelevant. The actual bug in Weblate is that it considers the double quotes surrounding the string in the INI file as part of the translation string instead of what it is, markup. The INI string `FOO_BAR=""` should be understood as key FOO_BAR and empty content. Likewise, it should be exported as `FOO_BAR=""`.

Right now it seems that when _importing_ and INI file the `FOO_BAR=""` is interpreted as key FOO_BAR and content `""` which is wrong. On export it escapes the double quotes thus exporting the content `"_QQ_""_QQ_"` which it then encloses in double quotes since the exporter DOES know that the right hand of the equal signs requires enclosing in double quote markup.

So the problem is a disparity between import and export. Import is unaware of the double quote as markup to the right hand side of the equal sign where export is. This is what creates the problem when we import properly formatted translation files.

**Comment by fede91it** [comment]
Great analysis thank you

**Comment by nijel** [comment]
Great, now I was able to reproduce this in translate-toolkit, will submit a PR with fix there.

**Comment by nijel** [comment]
PR is here: https://github.com/translate/translate/pull/3808

**Comment by fede91it** [comment]
How do I update Weblate using PIP?

Thank you

**Comment by nijel** [comment]
To get this fix, you need to update translate-toolkit. As it hasn't been yet released use git for that (not tested):

```
pip install git+https://github.com/translate/translate.git
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed in translate-toolkit (though it has not yet been released). 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
