### ISSUE TITLE
glossaries do not have a search box.

### ISSUE THREAD

**Issue by fastestnoob** [WeblateOrg/weblate#1717]
### Steps to reproduce
1. you have a large glossary
2. you need to check an entry if there is or not. 
3. you don't have a simple search box for entries.

### Expected behaviour
Put a searh box on every glossary page.

**Comment by nijel** [comment]
Good idea, probably nobody considered so far need for search in glossaries.

**Comment by nijel** [comment]
Good idea, probably nobody considered so far need for search in glossaries.

**Comment by ldmpub** [comment]
+1 same need for me.

**Comment by Naruto0** [comment]
Hi @nijel, i was thinking about this and there should be an attribute in this class for search term and the result should be filtered there:

https://github.com/WeblateOrg/weblate/blob/9b04dbd50b7c72ed9d47d15652177df4c41c96e0/weblate/trans/views/dictionary.py#L284-L348

Then some form should be made in template to reference the search term.

What do you think?

**Comment by Naruto0** [comment]
Another thought:
If there is search field in `Glossary`, what is the justification for Letter form filtering?

Regards, F.

**Comment by nijel** [comment]
It should work similar to the `LetterForm`, just remember to update `query_string` as well, so that the filtering is kept over deleting and other actions.

**Comment by Naruto0** [comment]
What exactly does `query_string` represents?

**Comment by nijel** [comment]
Query string in a URL, check how it's used in the template.

**Comment by Naruto0** [comment]
Hi @nijel. I do not see it at the template nor do i se any reference to it elswhere. While commenting out the `query_string` completely, the `letter` search still works, but not the word search.
Can you please review the code on my fork regarding this issue?
Thank you very much in advance!

**Comment by nijel** [comment]
It was merged after 3.2.1 release, it will be part of 3.3.

**Comment by ldmpub** [comment]
Perfect. I'm eager to use this new glossary functionality.
