### ISSUE TITLE
glossary entries should have comment sections. 

### ISSUE THREAD

**Issue by fastestnoob** [WeblateOrg/weblate#1718]
### Steps to reproduce
1. All the translations do have their own comment section. Also a translator can add a commit message for further clarification. 
2. Glossary entries don't have this feature. Some languages and/or some entries need further clarification. Give translators some space to discuss the glossary entries. 

Every translator follows glossary entries as a main translation source. these entires have the capability of changing the meaning of entire translation process.  

### Expected behaviour
Every glossary entry should have its own comment section.

**Comment by comradekingu** [comment]
Sounds a lot like translation to me.
Would a glossary project with a component for each language in a by side-by-side Zen mode with the ability to add words work? Or could the current glossaries be opened that way?
