### ISSUE TITLE
Honour singular strings, if declared 

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#1719]
Expected "module", got module(s)

Currently this string is listed with (s) on the singular https://hosted.weblate.org/translate/pext/translations/nb_NO/?checksum=d7f002c56c81ab0

It is here https://github.com/Pext/Pext/blob/8a4e864ff90ad105365a53a1f4b8c4058ddce6a6/pext/qml/main.qml#L696
And the plurals are here https://github.com/Pext/Pext/blob/8a4e864ff90ad105365a53a1f4b8c4058ddce6a6/pext/i18n/pext_en.ts#L440

Usually only the plural string is added, but if there is a singular one, it should be preferred for translation.

**Comment by nijel** [comment]
What might be doable approach is to store only the original text in the database and add flag (eg. `interpolate-plural`) to enabled interpolation when rendering. This way we're able to find the unit in the storage (as we have the original text), while the rendered text can be properly interpolated.
