### ISSUE TITLE
Assign screenshots by context

### ISSUE THREAD

**Issue by dg0yt** [WeblateOrg/weblate#1721]
### Steps to reproduce
1. Go to a screenshot page, e.g. https://hosted.weblate.org/screenshot/75/
2. At the bottom of the "Assign source strings", search for the common **context** used by (most) source strings in the screenshot, e.g. QColorDialog.

### Actual behaviour
"No new matching source strings found.", i.e. no matches

### Expected behaviour
All source strings having "QColorDialog" in the context property should be listed.

### Remarks
- At least in Qt based translation projects, the context usually the name of the dialog or widget class, thus providing a good hook to assign a shared screenshot.
- In that sense, matches in "Assign source strings" need to be listed with context. It is not possible to click the "Assign to screenshot" button without verifying the context.
- Given that I uploaded in the screenshot for a source string having this context, the system might even propose to use this context for searching strings.

### Server configuration
hosted.weblate.org

**Comment by nijel** [comment]
Looks like useful addition.

**Comment by mathroule** [comment]
It would be a nice feature. Indeed for the same translation I've got several context, so it's difficult to match the right one.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
