### ISSUE TITLE
Option for adding new language missing

### ISSUE THREAD

**Issue by Sebioff** [WeblateOrg/weblate#1722]
Hello,

on our old Weblate 2.5 installation it was possible to add new languages from the "Languages" tab of the project, but since updating to 2.17.1 that option isn't available anymore. The Languages tab only lists the existing languages.
The project settings haven't changed in the update and after checking the documentation all the required settings seem to be set, so I'm not sure what might be missing.

What I've checked:

- "Base file for new translations" in Components settings is set to the proper file
- "File format" in Components settings is set to "Gettext PO file"
- "New translation" in Components settings is set to "Automatically add language file"
- User has all available permissions

**Comment by nijel** [comment]
There should be "Start new translation" button below the languages list, it should be also available from the Tools menu. The settings you mention seem to be correct...

**Comment by Sebioff** [comment]
Was just a caching problem somewhere :|
After restarting the server the button is there. Thanks!

**Comment by Sebioff** [comment]
I spoke to soon. Suddenly it's gone again... tried it in private mode, clearing the browser cache and a browser I've never used for opening this side to make sure it's not some browser cache issue.
![weblate1](https://user-images.githubusercontent.com/3110063/33908115-9f58fcce-df87-11e7-9f70-98c5210b036c.png)

![weblate2](https://user-images.githubusercontent.com/3110063/33908120-a19ce5b8-df87-11e7-9eba-bd2d3b409fe5.png)

**Comment by nijel** [comment]
This has to be some issue on the server side. Maybe templates caching could cause this. Can you try removing the `django.template.loaders.cached.Loader` template loader?

See also https://docs.weblate.org/en/latest/admin/install.html#template-loading
