### ISSUE TITLE
add default for default git repository URI

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1751]
Read-only exporting of the internal git repository is surely an useful thing for solving of conflicts. Weblate supports information about the repository URI. Currently, this URI has to be filled separately for each component, which is not very comfortable.

It would be nice to support configuration variables for pre-filling of this (e. g. DEFAULT_GIT_EXPORT_URI). Even better would be a smart heuristic, as projects using internal Weblate links have to use iinked Git repository as well.

**Comment by nijel** [comment]
Well there already is an addon to completely automate the Git export, see https://docs.weblate.org/en/latest/admin/optionals.html#git-exporter

PS: The linked repos, should use the export URL from linked component, if not then it's a bug.

**Comment by stanislav-brabec** [comment]
This module works perfectly, supports linked components, but it provides a https:// based URL. As some modules in openSUSE weblate are pretty large, I installed anonymous Git server, and now I only need to report "Repository with Weblate translations" as "git://l10n.opensuse.org/project/branch/" instead of "https://" (or report both alternatives).

**Comment by nijel** [comment]
Why do you prefer git: over https:? Lack of encryption?

**Comment by stanislav-brabec** [comment]
According to the documentation, git protocol is traffic optimized, especially in case of incremental pull. Full checkout of https://l10n.opensuse.org/projects/yast-base/master/ git repository has >700MB and it contains >7000 po files. Speed really matters, as we currently have ~1000 commits per day. It means, that the maintainer has about one minute to pull upstream Git, pull Weblate Git, perform the merge, fix conflicts and push.

https://github.com/yast/yast-translations/commits/master

**Comment by nijel** [comment]
Well it used to be the case years ago, but since introduction the smart HTTP protocol (in Git 1.6.6) there should be no performance difference in those two. See https://git-scm.com/blog/2010/03/04/smart-http.html or https://git-scm.com/book/gr/v2/Git-on-the-Server-Smart-HTTP for more details.

On the other side the git protocol doesn't use encryption making it open to the man in the middle attacks, so https is generally preferred these days.

**Comment by stanislav-brabec** [comment]
Thanks for clarification. If the weblate.gitexport has the same parformance like git://, it makes no sense to run git-daemon in anonymous mode.

**Comment by nijel** [comment]
It's using [git-http-backend](https://git-scm.com/docs/git-http-backend) underneath, so yes, performance should match the native git protocol.
