### ISSUE TITLE
Strings without suggestions

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1753]
Currently we can view strings with suggestions, which is useful for a reviewer, but there's no way to view strings without suggestions. To get to the strings that don't have a suggestion yet, I need to guess offsets, search manually, etc.
Maybe it's worth to add a separate "strings without suggestions" link?

**Comment by nijel** [comment]
Certainly it's easy to add and probably it makes sense.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by burner1024** [comment]
Just tried this... not exactly what I had in mind, probably should've worded it better. It actually displays all strings without suggestions, while I meant "not translated" (without translation + need revision) strings without suggestions. Current implementation is probably not very useful.

**Comment by nijel** [comment]
Indeed that would be probably more useful, reopening.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
