### ISSUE TITLE
[question] how to add a new language code

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1754]
Say, I want Weblate to detect "tchinese.po" as traditional Chinese. Would it be enough to add it to weblate/lang/data.py like this
```
@@ -1172,6 +1172,8 @@ LOCALE_ALIASES = {
     'braz_por': 'pt_BR',
     'chinese_chs': 'zh_Hans',
     'chinese_zh': 'zh_Hant',
+    'tchinese': 'zh_Hant',
     'dutch_be': 'nl_BE',
     'english': 'en',
     'english-uk': 'en_GB',
```
or there something else involved?

**Comment by nijel** [comment]
Yes, that's all what is needed, feel free to submit PR with this.

**Comment by nijel** [comment]
Fixed by https://github.com/WeblateOrg/weblate/pull/1755.
