### ISSUE TITLE
Failure of weblate.trans.tests.test_formats.RESXFormatTest

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1756]
Due to spaces difference, weblate.trans.tests.test_formats.RESXFormatTest fails.

Simple patch fixes it in my build instance: https://build.opensuse.org/package/view_file/M17N:l10n.opensuse.org:testing/weblate/weblate-test_formats.patch?expand=1

### Server configuration
Weblate 2.18
Python 2.7.13
Django 1.11.8
six 1.9.0
social-auth-core 1.4.0
social-auth-app-django 1.2.0
django-appconf 1.0.1
Translate Toolkit 2.1.0
Whoosh 2.7.0
defusedxml 0.5.0
Git 2.13.6
Pillow (PIL) 1.1.7
dateutil 2.4.2
lxml 3.6.1
django-crispy-forms 1.7.0
compressor 2.1.1
djangorestframework 3.7.3
pytz 2016.10
PyYAML 3.12
Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Probably it's caused by translate-toolkit version, but we should make the test more robust to deal with this...

**Comment by nijel** [comment]
You anyway want to upgrade to at least 2.2.0 to get fix for possible security vulnerability in resolving XML entities, see https://github.com/translate/translate/pull/3632, so I will address this by raising the required version (the test works fine since 2.2.0).

**Comment by stanislav-brabec** [comment]
Confirming that the space change is caused by a different translate-toolkit version. After upgrade to 2.2.4, no patch is required.
