### ISSUE TITLE
Change the shortcut for next and previous strings

### ISSUE THREAD

**Issue by tuxayo** [WeblateOrg/weblate#1758]
I finally understand why strange things were happening ^^

### Steps to reproduce
1. Use Weblate with Firefox
2. Got to a string
3. Use Ctrl + PageUp or Ctrl + PageDown to switch tabs
4. Then you also went to next or previous string in Weblate

### Details
OS: Linux
Firefox version: 52.5.2 ESR (64-bit)

**Comment by nijel** [comment]
Honestly we're fighting a bit with the keyboard shortcuts to find the ones not colliding with browser ones here...

**Comment by tuxayo** [comment]
Indeed, multiple browsers x OSes = chaos ^^"

It there a way to at least disable a shortcut? I'm currently unlearning the use Ctrl + PageUp/Down which I use a lot due to this conflict with Webate.

**Comment by tuxayo** [comment]
Thanks a lot! <3
