### ISSUE TITLE
img/switch.png ressource returns a 404

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#1760]
### Steps to reproduce
1. Install Weblate 2.18
2. Check every url

### Actual behaviour
img/switch.png gives a 404

### Expected behaviour
every single file should be included in release
I think the issue is here: https://github.com/WeblateOrg/weblate/blob/34b3d5b046aed4af36ebbfcee8ce8851252a0806/weblate/static/multi-select.css#L2
https://github.com/WeblateOrg/weblate/issues

### Server configuration
Non relevant, or look at https://github.com/YunoHost-Apps/weblate_ynh/blob/master/conf/settings_history/settings.2.18.py

**Comment by nijel** [comment]
That file indeed does not exist, however that CSS is overridden so the browser should not try to load it at all:

https://github.com/WeblateOrg/weblate/blob/8b7fb4bcfc536b7e6933b0488249be9f0b479206/weblate/static/style-bootstrap.css#L242-L245

**Comment by nijel** [comment]
Closing as I believe there is no problem in missing this file.

**Comment by Jibec** [comment]
thanks :)
