### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by np-8** [WeblateOrg/weblate#1761]
### Steps to reproduce
1. Go to http://127.0.0.1:8000/admin/trans/subproject/add/
2. Add Component  & Press Save

### Actual behaviour
Error is thrown:
```
TypeError at /admin/trans/subproject/add/
a bytes-like object is required, not 'str'
```
with following (partial) traceback

```
File "C:\Users\Niko\Miniconda3\lib\subprocess.py" in __init__
  947.                                 restore_signals, start_new_session)

File "C:\Users\Niko\Miniconda3\lib\subprocess.py" in _execute_child
  1198.                 args = list2cmdline(args)

File "C:\Users\Niko\Miniconda3\lib\subprocess.py" in list2cmdline
  751.         needquote = (" " in arg) or ("\t" in arg) or not arg

Exception Type: TypeError at /admin/trans/subproject/add/
Exception Value: a bytes-like object is required, not 'str'
```
### Expected behaviour
A component should be added 

### Server configuration
```
c:\ohjelmia\weblate\weblate\lib\site-packages\data
 * Weblate 2.18
 * Python 3.5.2
 * Django 1.11
 * six 1.11.0
 * social-auth-core 1.5.0
 * social-auth-app-django 2.0.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0.windows.3
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.1
 * lxml 4.1.1
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.3
 * pytz 2017.3
 * git-svn 2.11.0.windows.3
 * Database backends: django.db.backends.sqlite3
```
### Additional info.

I can see that when crashing, the arguments to `subprocess.Popen()` at `weblate\trans\vsc.py:Repository._popen` are
```
In [1]: args
Out[1]: ['git', 'config', 'push.default', b'current']
```

**Comment by nijel** [comment]
It's encoded to utf-8 since d731e21361, AFAIR it was needed on Linux...

**Comment by np-8** [comment]
I'm working on Windows machine. Good to hear it was fixed. Just duck-taped it with a `args = [x.decode('utf-8') if type(x) != str else x for x in args]`.

**Comment by nijel** [comment]
It has not been (yet) fixed, the code apparently behaves differently on Linux and on Windows.

**Comment by nijel** [comment]
I've fixed this particular issue, but there might be other bugs on Windows anyway. Most importantly the translate-toolkit, library we're using to parse translation files, has some bugs on Windows see https://github.com/translate/translate/issues/3751 or https://github.com/translate/translate/pull/3569
