### ISSUE TITLE
Disabled Commit button still submits the form

### ISSUE THREAD

**Issue by cconrad** [WeblateOrg/weblate#1762]
### Steps to reproduce
1. Go to the page "Manage" > "Repository maintenance" when there are no changes to commit
2. In the section "Repository tools", click the disabled Commit button

### Actual behaviour
The page is reloaded with the message "All pending translations were committed." displayed at the top

### Expected behaviour
Nothing should happen

### Server configuration
 * Weblate 2.18
 * Python 3.5.2
 * Django 2.0
 * six 1.11.0
 * social-auth-core 1.5.0
 * social-auth-app-django 2.0.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.1
 * lxml 4.1.1
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.3
 * pytz 2017.3
 * pyuca N/A
 * python-bidi 0.4.0
 * PyYAML 3.12
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
If you have permission to do commit, it indeed still works. It's disabled when there are no changes to commit, so it in fact did nothing (all pending changes were actually none changes).

But indeed ui-wise it's not expected behavior.

**Comment by nijel** [comment]
The problem is that the submit handler does not look at the disabled state:

https://github.com/WeblateOrg/weblate/blob/998da461f8dc8efe05fa18c18d3763cddd34e8b1/weblate/static/loader-bootstrap.js#L1122-L1127
