### ISSUE TITLE
Bug in SSH URL parsing

### ISSUE THREAD

**Issue by mclei-asw** [WeblateOrg/weblate#1763]
### Steps to reproduce
1. Use SSH URL for git repository with relative path like gogs@repo.example.com:test/repo.git

### Actual behaviour
Resolver error for "repo.example.com:test" is returned.

Only absolute URLs are working right.

### Expected behaviour
Only "repo.example.com" should be used as hostname.

**Comment by nijel** [comment]
I don't think Weblate is trying to parse the URL at all, it just passes it to Git. Are you sure the URL you're trying is working with git (especially with version that your Weblate uses)?

**Comment by mclei-asw** [comment]
Yes, it works perfectly in git clone when run locally on the same machine.

**Comment by nijel** [comment]
I've just tried it with `git@github.com:WeblateOrg/hello.git` and it worked fine.

What is exact error message you get?

**Comment by mclei-asw** [comment]
Failed to fetch repository: ssh: Could not resolve hostname repo.example.com:test: Name or service not known fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. (128)

(replaced the real address with fake one, but the structure is the same)

**Comment by mclei-asw** [comment]
Tested again and the problem was the URL:
ssh://gogs@repo.example.com:test/repo.git - DOES NOT WORK
gogs@repo.example.com:test/repo.git - WORKS
ssh://gogs@repo.example.com:/test/repo.git - WORKS

**Comment by nijel** [comment]
And are you sure the first one works in Git? AFAIK it won't as the URL is `ssh://SERVER:PORT/PATH`, so unless you want to specify port there should be no : used there. See https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols#_the_ssh_protocol

**Comment by mclei-asw** [comment]
Ok I understand now.
I did not try the first directly in git, but the last one WORKS in Weblate.
