### ISSUE TITLE
Global contributor stats

### ISSUE THREAD

**Issue by wichert** [WeblateOrg/weblate#1764]
We hire translators who can work on multiple projects. In order to figure out how much work they have done I currently need to generate the Contributor Stats for each component, and add them all up manually. That process works (and I can probably script it through the API), but it is a bit tedious. Would it be possible to have that kind of report at the project and global level as well?

**Comment by wichert** [comment]
A related issue which may or may not warrant its own ticket depending on how you want to tackle this: it would be nice if translators can see their own word counts per time period as well.

**Comment by wichert** [comment]
I tried to do this through the API, but I am not sure it is possible. I can crawl over the `/api/changes` endpoint, but that only returns a numeric id for the translator, with no way to turn that into a name. Trying to write a script to do that also very quickly made me hit a throttling bottleneck which locks me out for 24 hours.

**Comment by wichert** [comment]
The best I can come up with at the moment is this SQL query directly against the weblate database:

```sql
WITH
	changes AS (
		SELECT 
			date_trunc('month', trans_change.timestamp) AS ts, 
			trans_change.author_id,
			trans_translation.language_code,
			array_length(regexp_split_to_array(target, '\s+'), 1) AS words
		FROM trans_change
			JOIN trans_translation ON trans_change.translation_id = trans_translation.id
		WHERE ACTION IN (2, 5)
	)		
SELECT
	ts,
	(auth_user.first_name || ' ' || auth_user.last_name) AS translator,
	language_code AS lang,
	COUNT(*) AS message_count,
	SUM(words) AS word_count
FROM changes
	JOIN auth_user ON changes.author_id = auth_user.id
GROUP BY ts, translator, lang
ORDER BY ts DESC
```

This could be improved by performing a word-diff over `old` and `target` columns to see how many words were added / remove / moved: right now a small typo fix in a large message would count all the words in the message.

**Comment by fdosanjuan** [comment]
I too would like to access each translator's contributions per period of time through the Web API. Do you know if anyone is working on this? Thanks!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by wichert** [comment]
Thanks!
