### ISSUE TITLE
Xliff ID handling

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1765]
According to xliff specification the trans-unit IDs are unique per file section, while Weblate currently needs them globally unique in the xliff file.

> The required id attribute is used to uniquely identify the `<trans-unit>` within all `<trans-unit>` and `<bin-unit>` elements within the same `<file>`.

**Comment by nijel** [comment]
It looks like I was wrong - we're using full ID in bilingual setup, but we completely ignore it in monolingual, what is probably wrong.

**Comment by RobnIrene** [comment]
HCked
