### ISSUE TITLE
All errors at same time

### ISSUE THREAD

**Issue by yashk0thari** [WeblateOrg/weblate#1768]
### Steps to reproduce
1. go to your profile
2. go to authentication
3. wrong fields filled, all errors occur

### Actual behaviour
if any one of the fields is inputted wrongly then all errors are outputted hence difficult to find which field is inputted wrongly...

### Expected behaviour
The field inputted wrongly should output the error designated for the field and no other fields...

**Comment by nijel** [comment]
I can't reproduce this, can you please provide screenshot showing this error? Also what Weblate version do you use?
