### ISSUE TITLE
PHP strings translations are not propagated to VCS

### ISSUE THREAD

**Issue by jekkos** [WeblateOrg/weblate#1769]
### Steps to reproduce
1. Setup a project using php strings (using docker-compose)
2. Patch translate-toolkit with custom dependency found in [PR]( https://github.com/WeblateOrg/weblate/commit/00ea18a1063709d68beebbf3c73bc0fc4613379f)
3. Add a new language and start translating

### Actual behaviour
Tell us what happens instead
PHP strings format didn't seem wel supported at first. Before upgrading to the pull request a couple of users did a translation of a new language, from which I see it is present in weblate. However changes are not propagated to the actual PHP strings file.

### Expected behaviour
When starting new translations with this patched versions, this does seem to work, so changes are staged correctly in the git repository.
When going through previous translated components, I would expect those changes to become eventually visible in the repo, which is not the case. I need to find a way to rescue those otherwise we'll need to start over again.

When I dowload a CSV file for a component, all translations are there. When I download the php strings file, it's just empty (in this case containing the key names, but no translations)

Is there a way to force write the weblate content to the vcs (through admin command or so?)
### Server configuration
Please paste the output of command `./manage.py list_versions` over here
 * Weblate 2.17.1
 * Python 2.7.13
 * Django 1.11.7
 * six 1.11.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.7.3
 * pytz 2017.3
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Just to clarify: You are using patched translate-toolkit with changes in https://github.com/translate/translate/pull/3697? What phply version did you install? I remember some older versions being incompatible with the patch...

There is commit button in the repository maintenance page, Manage menu on each translation/component/project contains it as well or you can use can use [API call do to that](https://docs.weblate.org/en/latest/api.html#post--api-translations-(string-project)-(string-component)-(string-language)-repository-), alternatively through [wlc utility](https://docs.weblate.org/en/latest/wlc.html#cmdoption-wlc-arg-commit).

**Comment by jekkos** [comment]
Currently it's the phply (1.2.1) that I'm using. Normally commit button does indeed propagate the changes, but in this case it does not, which makes me think this is a bug in weblate's php support (as the changes are there when downloading CSV files for example). Any idea if this is a good version?

**Comment by nijel** [comment]
It might be units which were not written when you've used not patched translate-toolkit. This could indeed lead to inconsistency like this. There is currently no UI or API to address this as it should not happen. 

You can force their resync by marking them as pending in the database, eg. using management console:

```
$ ./manage.py shell
Python 2.7.14+ (default, Dec  5 2017, 15:17:02) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from weblate.trans.models.unit import Unit, STATE_TRANSLATED
>>> Unit.objects.filter(translation__subproject__project__slug='your-project-slug', state=STATE_TRANSLATED).update(pending=True)
```

**Comment by nijel** [comment]
@jekkos Did the suggestion above help you?

**Comment by jekkos** [comment]
I seem to have an older version of the source. I adapted the code to this

```
from weblate.trans.models.unit import Unit, STATE_TRANSLATED
Unit.objects.filter(translation__subproject__project__slug='common', translated=True).update(pending=True)
```

I don't directly know what the project-slug should be filled in with, I tried a couple of names linked to my project to no avail. Result of the command always gave 0. When I removed it I did see a number (which probably indicates that all translations are pending?)

Then I committed pending changes but found no real diff with was there before. However the files seem to be in sync now (when I download and compare with what is in git)

**Comment by jekkos** [comment]
Maybe a little off topic, but how should I update the docker-compose image in this case? I see that the 'edge' tag has more recent push date then the default 'latest' in the compose file.

**Comment by nijel** [comment]
Both of them have same Weblate version, just some minor differences in other dependencies which really should not matter here.

**Comment by jekkos** [comment]
@nijel I know have following output . Anything else I have to do after this? It does not seem to sync the entries I see in weblate to the git repo

![schermafdruk van 2018-02-15 23-35-13](https://user-images.githubusercontent.com/576234/36284694-edd735d8-12a8-11e8-895e-09d11084b922.png)

**Comment by nijel** [comment]
Run commitgit management command, that should do it.
