### ISSUE TITLE
Optimize work with repositories

### ISSUE THREAD

**Issue by lomaster1** [WeblateOrg/weblate#1770]
### Steps to reproduce
Import many components (50+) with same repository
Also the same if working with vcs in project on site.

### Actual behaviour
Git update run for all components.

### Expected behaviour
After import git update will be run one time.

### Server configuration
Weblate 2.18

**Comment by nijel** [comment]
Can you please share in more details how to trigger this? Are you using [shared repo](https://docs.weblate.org/en/latest/vcs.html#internal-urls) which is there exactly for this use case?
