### ISSUE TITLE
Upload Translation merge method - suggestion only

### ISSUE THREAD

**Issue by janbednar** [WeblateOrg/weblate#1777]
### Steps to reproduce
1. Login as user with superuser status (i have also added all possible permissions to this user)
2. Open component in project
3. Select language
4. Files -> Upload translation

### Actual behaviour
Merge method shows only one option: `Add as suggestion`

### Expected behaviour
According to https://docs.weblate.org/en/latest/user/files.html#import-methods there should be 2 more methods to upload the translation as.

There is probably a wrong setting in our custom hosted Weblate, but I could not find more info about it in documentation. I know this is possible as other users had some problems with that but managed to access the other options to `add as translation` etc. 

Thank you for any help

### Server configuration
```
* Weblate weblate-2.18
 * Python 2.7.5
 * Django 1.11.5
 * six 1.9.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.2
 * defusedxml 0.5.0
 * Git 1.8.3.1
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.2.1
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.7.7
 * pytz 2017.2
 * pyuca N/A
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
The list of available options depends on your permissions, so you apparently lack permission to translate. Is your translation component configured to use only suggestion voting?

**Comment by janbednar** [comment]
Neither of these are ticked in the component:

* [ ] Locked
* [ ] Allow Translation Propagation
* [ ] Save Translation History
* [ ] Enable Suggestion
* [ ] Suggestion voting
* Autoaccept suggestions: 0
* Quality check flags are empty
* New translation: Automatically add language file
* Merge stlye: Merge

The project where this component is located is set:

* [x] Set Translation-Team header
* Project access: Public (*Přístup k projektu - forgot to localize yet?*)
* [x] Enable review
* [x] Enable hooks
* Source language: English

I have tried using my account with super user status, I have tried creating normal user account with all permissions.

The user I am using has:

* [x] Active 
* [x] Staff status
* [x] Superuser status
* Groups: Managers, Owners, Users, testProject@Administration, ..@Review, ..@Translate
* User permissions: all

**Comment by nijel** [comment]
For some reason the user doesn't have translate permission, that's when these options are removed from the form:

https://github.com/WeblateOrg/weblate/blob/5cd37f4bcedc42a31b30ec31218e6e1a3281c0a0/weblate/trans/forms.py#L613-L615

What can be reasons for this (besides not having the permission, what can not happen for superuser):

* Locked component
* User without configured e-mail

**Comment by janbednar** [comment]
Might there be any other issue with configuration of the custom hosted Weblate? I have tried this on many components, neither of them are locked and the email address is set up for all users:

<img width="270" alt="screen shot 2018-01-09 at 12 58 06" src="https://user-images.githubusercontent.com/22516731/34719896-f2695c72-f53c-11e7-928f-0bcbdfb21c9d.png">

**Comment by nijel** [comment]
Have you installed 2.18 or upgraded from some older version? It it was upgrade, did you run setupgroups management command? (It should not matter, but I'm just curious). Have you somehow customized group permissions?

**Comment by Pitel** [comment]
It was upgraded, and `setupgroups` was run.

@janbednar AFAIK the groups and permissions were customized by @martinpucik.

**Comment by janbednar** [comment]
@Pitel I have tried to use Weblate original groups on test user and I also tried to add all permissions, so there should not be problem. (hopefully)

**Comment by nijel** [comment]
I don't think it's permission problem if this fails for superuser as in this case most permission checks are short circuited.

This option is removed if user does not have translate permission:

https://github.com/WeblateOrg/weblate/blob/8f6bd773cd35abe543ba17448816faed07fed628/weblate/trans/forms.py#L613-L615

That checks expands to simple can_edit call if translation is given:

https://github.com/WeblateOrg/weblate/blob/8f6bd773cd35abe543ba17448816faed07fed628/weblate/permissions/helpers.py#L152-L161

That one is more complex:

https://github.com/WeblateOrg/weblate/blob/8f6bd773cd35abe543ba17448816faed07fed628/weblate/permissions/helpers.py#L121-L136

* You've said the project is not locked
* User is authenticated and has email set
* The has_group_perm just returns True for superuser
* If the translation would be template, then still has_group_perm just returns True for superuser
* Suggestion voting is not enabled for your project
* So it should return True

Apparently something there is not working as expected :-). Can you put some debugging statements to this function (or just insert `return True` and figure out where it starts to work).

**Comment by Pitel** [comment]
The `can_edit` method IS returning `True`.

But I noticed another thing. I've added logs to `get_upload_form`:
```python
def get_upload_form(user, translation, *args):
    """Return correct upload form based on user permissions."""
    project = translation.subproject.project
    if can_author_translation(user, project):
        form = ExtraUploadForm
    elif can_overwrite_translation(user, project):
        form = UploadForm
    else:
        form = SimpleUploadForm
    result = form(*args)
    LOGGER.debug(str(result.fields['method'].choices))
    if not can_translate(user, translation=translation):
        result.remove_translation_choice('translate')
        result.remove_translation_choice('fuzzy')
    if not can_suggest(user, translation):
        result.remove_translation_choice('suggest')
    LOGGER.debug(str(result.fields['method'].choices))
    return result
```

and also `remove_translation_choice`
```python
def remove_translation_choice(self, value):
        """Remove add as translation choice."""
        LOGGER.debug(value)
        choices = self.fields['method'].choices
        self.fields['method'].choices = [
            choice for choice in choices if choice[0] == value
        ]
```

And in log, I see this:
```
2018-01-12 12:58:42,905 DEBUG [(u'translate', u'P\u0159idat jako p\u0159eklad'), (u'suggest', u'P\u0159idat jako n\xe1vrh'), (u'fuzzy', u'P\u0159idat jako p\u0159eklad vy\u017eaduj\xedc\xed \xfapravu')]
2018-01-12 12:58:42,905 DEBUG suggest
2018-01-12 12:58:42,907 DEBUG [(u'suggest', u'P\u0159idat jako n\xe1vrh')]
```

So it seems the `remove_translation_choice` method is NOT removing the given method, but setting it as the only one. Which is a bit WTF, and probably bug. :)

**Comment by nijel** [comment]
Thanks for diagnosing this, it is indeed bug.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
