### ISSUE TITLE
Search gives no results on new language

### ISSUE THREAD

**Issue by jelv** [WeblateOrg/weblate#1780]
### Steps to reproduce
1. Add new language
2. Open search with fulltext search
3. Search

I have this problem on the hosted weblate with the [Frisan](https://hosted.weblate.org/projects/liberapay/core/fy/#search) translation for Liberapay. There are no transation at this moment. Search does work on other languages like French and Dutch.

### Actual behaviour
On any search it gives "No string matched your search!"

### Expected behaviour
Search results for query.

### Server configuration
Hosted Weblate.

**Comment by nijel** [comment]
The fulltext index is updated in background so it might take some time till it's updated (depending on the queue length). Now ti seems to work just fine...

**Comment by jelv** [comment]
I can confirm that it works now again. 

Maybe add an message so that user know that the search is unavailable until the index is updated?

**Comment by nijel** [comment]
Good point, probably useful to add.
