### ISSUE TITLE
CLDR usage or suggestions

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#1781]
In Weblate interface there are many language names to translate (in the following file: https://github.com/WeblateOrg/weblate/blob/master/weblate/lang/languages.py).

Is there a way to pull suggestions from CLDR instead of translating this whenever a new language is added? (Suggestions would be fine as well).

Thanks!

**Comment by nijel** [comment]
Good idea, I'll look into it (working with CLDR anyway these days to bring Weblate language database in sync with it).

**Comment by yarons** [comment]
Thanks, you're awesome, as always 👍

**Comment by nijel** [comment]
The CLDR names are automatically there as of c97fc1e45b798cdaa6ceffb8710555521e4e01eb.

**Comment by nijel** [comment]
Also in case somebody needs this for other projects - there are po files with language names translations available in https://github.com/WeblateOrg/language-data/tree/master/languages-po

**Comment by yarons** [comment]
@nijel according to your link, I looked at the diff for Hebrew and it seems like there was nothing changed there besides the last change date.

So it didn't work for Hebrew in that case.

**Comment by nijel** [comment]
It doesn't override existing translations, it just fills in the empty ones. If you want this, just grab [he.po](https://github.com/WeblateOrg/language-data/blob/master/languages-po/he.po) and upload it to Weblate as suggestions. I'm not going to do this automatically for all languages.

**Comment by nijel** [comment]
When speaking about Hebrew language - do you have clue which plural rules work best for it?

Weblate currenthly has: ['he', 'Hebrew', '2', 'n != 1']
While CLDR: ['he', 'Hebrew', '4', '(n == 1) ? 0 : ((n == 2) ? 1 : ((n > 10 && n % 10 == 0) ? 2 : 3))']

**Comment by yarons** [comment]
I'm already at 100% but I'll try doing it the next time more languages are added.

These are both not 100% practical but from former discussions we agreed on
nplurals=3; plural=n==1 ? 0 : n==2 ? 2 : 1;

This is because Hebrew has special cases in with time related terms (hours, months, days, years, etc.) where 2 days, for example, has a special word for it (Sha'ataim, while 3 hours becomes 3 Sha'ot).

The extended 4 plural forms does not serve us right because the fourth case is not as common and used in very rare cases which are usually irrelevant for software localization.

If there was a way to break the formula for specific strings (as in L20n) it would be great, but since both XLIFF and Gettext PO doesn't allow that we're in trouble.

I think Android strings XML allows setting a special case for two where needed, I ran into that when I tried to correct the official Android translation.

**Comment by nijel** [comment]
Thanks @yarons, I've just adjusted Weblate to understand all of these and changed Weblate translation to use this form in b8de2b2bf662fe508711f59903ad9ce61f092aa9.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by yarons** [comment]
@nijel although correct in some cases the fourth form is usually unnecessary, the third is mostly used in time related terms, so basically whenever possible we should be able to choose, otherwise the 3rd and 4th forms should be the same as the 2nd one.

I see 4 plural forms although the formula at the top shows 3 (according to the formula I posted above).

**Comment by nijel** [comment]
I've probably messed up updating Weblate here, so it picked up the 4 plural form instead. Should I revert it or it's okay as it is now?

**Comment by yarons** [comment]
The 4th form is redundant, yet that's the standard, so in 99% of the cases this form will be identical to the "few" form I don't see the point of having that one.

The "two" form is already used, now Weblate looks much more elegant to Hebrew users.
