### ISSUE TITLE
Users can't see/access any projects

### ISSUE THREAD

**Issue by frankenfine** [WeblateOrg/weblate#1782]
Users log on and go to watched projects (or any other mechanism) to see a component
They receive a Page Not Found error. 

All of our projects are set to Public. Only admins can access projects, everyone else (members of Users group) have lost access. Yesterday they could see some, now they can't see any of them.

We were at 2.17-dev and are now at 2.19-dev.

Any ideas for troubleshooting?

**Comment by nijel** [comment]
The users are probably missing permission to access the projects, you can fix the default groups by running `./manage.py setupgroups`.

See [docs](https://docs.weblate.org/en/latest/admin/access.html#extra-privs) for more information on privileges in Weblate.

**Comment by frankenfine** [comment]
That doesn't seem to have fixed it. We've also re-toggled every project as public just to make sure, but nothing so far.  Of note, this happened before we updated to 2.19 and hoped the update would help, but unfortunately that is not the case.

**Comment by jmaxxz** [comment]
Have a similar issue with public projects not showing up for users. As a work around I've had to make a bunch of users super users.

I've tried adding users to all groups, giving them all permissions, nothing works. Except marking them super users.

**Comment by nijel** [comment]
This is probably result of overly complex design of current permissions (see https://github.com/WeblateOrg/weblate/issues/1798).

Anyway to debug this:

* Did you create any GroupACL manually? If so deleting them might fix that.
* What do you see (as superuser) on project access management (available weblate.example.com/access/projectname/)? (Access control on bottom and user permissions on top)

**Comment by frankenfine** [comment]
Users is empty, projects all set to Public.
As for GroupACL, I don't have any manual adds, but every project has an " @Administration " group which I imagine is automatically created. Should there be other GroupACLs for Translate or Users?

**Comment by jmaxxz** [comment]
@nijel I see nothing when I look at `/access/<project>` it says the projects are public with reviews disabled, and there is no users in the users list.

**Comment by nijel** [comment]
If all projects are public, then there should be just the `@Administration` group for each and each having GroupACL filtering just administrative privileges.

I'm really curious what's going on there, so it would be great if you could trace it there as well. Honestly I start to hate this piece of code...

**Comment by jmaxxz** [comment]
Returns here: https://github.com/WeblateOrg/weblate/blob/master/weblate/permissions/helpers.py#L89

**Comment by nijel** [comment]
Is the user member of standard Users group? Can you list automatic group assignments?

**Comment by jmaxxz** [comment]
@nijel my test user is part of `@Review`, `@Screenshots`, `@Translate`, and `Users`

**Comment by nijel** [comment]
That sounds correct (the @ groups are not needed, but should not harm). What's your seting for MIDDLEWARE and AUTHENTICATION_BACKENDS in `settings.py`? Does it match `settings_example.py`?

**Comment by jmaxxz** [comment]
Well I feel like an idiot. My middleware did not match. It now matches with the exception of 'weblate.wladmin.middleware.ConfigurationErrorsMiddleware' because when I add it crashes. 

Thank you for your help. Sent a small tip for your help.

**Comment by frankenfine** [comment]
Good catch. Same solution here, must have missed the changes in that section last time I updated.

**Comment by nijel** [comment]
@jmaxxz What error do you get with ConfigurationErrorsMiddleware? (It has been added recently to git, so it's not there if you're not using latest git)
