### ISSUE TITLE
Visualize the machine translation quality feedback

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1785]
The machine translation services return quality indication of the translation. It's integer in range 0 - 100. This is currently used to sort the results, but it might be good to indicate this to user as well.

Related code is here:

https://github.com/WeblateOrg/weblate/blob/8f6bd773cd35abe543ba17448816faed07fed628/weblate/static/loader-bootstrap.js#L253-L282

The value is already there, so it's just matter of adding column to the results table and choose way to visually indicate this.

**Comment by nijel** [comment]
Note that many of the services do not report this and their score is hardcoded to 100.

**Comment by mlaggner** [comment]
this is kinda complicated to solve. we could do

- report them as -1, but then these results get ordered to the end of the list and as seen in #1791 there would be many weblate internal results before..
- report them as 75 (or 50) to mix it rather at the front of the list
- let it as is and report it as 100

but having 100 here for translations which are not reported as _perfect_ this could have a negative influence to #1784
