### ISSUE TITLE
AttributeError when updating plural key in source file

### ISSUE THREAD

**Issue by tgwozdzik** [WeblateOrg/weblate#1786]
### Steps to reproduce
First of all I changed polish language definition - number of plurals to 4 (one/few/many/others).
Next i follow those steps:

Suppose we have file structure defined like this:

```
pl
  dashboard.json (source) 
```

I've created new component with such options:
- File mask: */dashboard.json
- Monolingual base language file: pl/dashboard.json
- Edit base file: True
- Base file for new translations: pl/dashboard.json
- File format: i18next JSON file

dashboard.json file contains:
```
"uread_news": {
  "message_0": "{{newsCount}} nieprzeczytana wiadomość",
  "message_1": "{{newsCount}} nieprzeczytane wiadomości",
  "message_2": "{{newsCount}} nieprzeczytanych wiadomości",
  "message_3": "{{newsCount}} nieprzeczytanych wiadomości",
  "description": " 
}
```

Now, I create new translation in that component for English language. This is what I get:
```
"uread_marketing_news": {
  "message": "",
  "description": ""
}
```
I can translate every key I want in this new translation. I can then save changes and everything is correct. Problem occurs when I make changes in base (`pl/dashboard.json`) file, more precisely, when I modify any of plural keys.

### Actual behaviour
Error when I want to list component translations or I click on English translation:
```
Exception Value: 'str' object has no attribute 'get_plural_name'
Exception Location: /usr/local/lib/python2.7/dist-packages/weblate/trans/templatetags/translations.py in format_translation, line 198
```
### Expected behaviour
Ability to update translations in other languages.

P.S. Please let me know if I'm doing something wrong here.

**Comment by nijel** [comment]
What version do you use? Can you please share full traceback?

**Comment by tgwozdzik** [comment]
Version: weblate-docker 2.18-1
Traceback: http://dpaste.com/0G8A8FH

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
