### ISSUE TITLE
locking race: unable to create git lock

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1787]
Locking error appears sometimes during translators' work.

Under a mediocre load of https://l10n.opensuse.org/, locking errors appear several times a day. Under a heavy load, the locking error appears every few minutes.

The most common source of problems are yast translations: yast-base refers to GitHub repository, and all other >100 projects use link projects to link to yast base. In total, yast-base GitHub repository contains >7000 po files.

### Steps to reproduce
The problem happened e. g. when:
1. yast-base got a web hook callback from GitHub
2. user edited another component
3. another user reviewed suggestions (each edit during suggestion review generates 2 push requests, see issue #1116)

This problem was seen in version 2.17.1 as well.

### Actual behaviour
```
RepositoryException at /translate/yast-dhcp-server/master/pl/

fatal: Unable to create '/var/lib/weblate/vcs/yast-base/master/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue. (128)

Exception Location: | /usr/share/weblate/weblate/trans/vcs.py in _popen, line 183
-- | --
/usr/sbin/uwsgi
2.7.13
['/usr/share/weblate/',  '.',  '',  '/usr/lib/python27.zip',  '/usr/lib64/python2.7',  '/usr/lib64/python2.7/plat-linux2',  '/usr/lib64/python2.7/lib-tk',  '/usr/lib64/python2.7/lib-old',  '/usr/lib64/python2.7/lib-dynload',  '/usr/lib64/python2.7/site-packages',  '/usr/lib64/python2.7/site-packages/PIL',  '/usr/local/lib64/python2.7/site-packages',  '/usr/local/lib/python2.7/site-packages',  '/usr/lib/python2.7/site-packages']
Thu, 11 Jan 2018 10:00:41 +0000

(I can send a full error message by mail.)
```
### Expected behaviour
No error.

### Server configuration
Please paste the output of command `./manage.py list_versions` over here
 * Weblate 2.18
 * Python 2.7.13
 * Django 1.11.8
 * six 1.9.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.2.4
 * Whoosh 2.7.0
 * defusedxml 0.5.0
 * Git 2.13.6
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.6.1
 * django-crispy-forms 1.7.0
 * compressor 2.1.1
 * djangorestframework 3.7.3
 * pytz 2016.10
 * PyYAML 3.12
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Can you please post full backtrace (preferrably the text version)?

There is locking at Weblate level to avoid this, but apparently it was not applied in this case for some reason...

**Comment by stanislav-brabec** [comment]
Full backtraces of several cases were sent by e-mail.

**Comment by stanislav-brabec** [comment]
The error message indicates reverse problem than you commit attempts to fix:

Another task is holding lock (too long) and translation save fails. Instead of waiting for completion or postponing the change, it causes error, and translators' work is lost.

As the error disappears in a short time (one minute or so), I suppose it is just a race, not a stale lock.

**Comment by nijel** [comment]
Well that's true for the FileLockException, but the RepositoryException errors should not happen at all - the repository should not be touched without Weblate holding it's own lock.

**Comment by stanislav-brabec** [comment]
When more people work on translations, the error happens much more often, e. g. 100 times a day. Each time it occurs, translators experience an error.

**Comment by nijel** [comment]
Okay, I think I know where the problem is - there is race condition in the locking code. It happens to be same as in py-lockfile (https://github.com/benediktschmitt/py-filelock/issues/31) and as [described on StackOverflow](https://stackoverflow.com/q/17708885/225718).

To fix that, you can remove file unlinking in the lock code:

```patch
--- a/weblate/utils/filelock.py
+++ b/weblate/utils/filelock.py
@@ -128,10 +128,6 @@ class FileLockBase(object):
         if self.is_locked and self.depth == 0:
             self.unlock(self.handle)
             self._close()
-            try:
-                os.unlink(self.lockfile)
-            except OSError:
-                pass
             self.is_locked = False
 
     def __enter__(self):
```

As a proper fix I will rather start using referenced locking library as it seems to now have all features we need and is apparently better tested.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
