### ISSUE TITLE
MyMemory gives error as translation for traditional chinese

### ISSUE THREAD

**Issue by wichert** [WeblateOrg/weblate#179]
When trying the MyMemory automatic translation I get this translation:

  'ZH_TW' IS AN INVALID TARGET LANGUAGE . EXAMPLE: LANGPAIR=EN|IT USING 2 LETTER ISO OR RFC3066 LIKE ZH-CN. ALMOST ALL LANGUAGES SUPPORTED BUT SOME MAY HAVE NO CONTENT

This is possible a combination of two bugs:
1. a MyMemory error should be shown as an error, not inserted as translation.
2. this error should not happen at all.

**Comment by 26e45ee** [comment]
How can resolve this problem (mafa )'MF-MA' IS AN INVALID TARGET LANGUAGE . EXAMPLE: LANGPAIR=EN|IT USING 2 LETTER ISO OR RFC3066 LIKE ZH-CN (China). ALMOST ALL LANGUAGES SUPPORTED BUT SOME MAY HAVE NO CONTENT
