### ISSUE TITLE
suggestion: per-language comment

### ISSUE THREAD

**Issue by dachary** [WeblateOrg/weblate#1790]
It would be nice to be able to comment on a translation and not on the source string. As it stands, when a comment is added for a unit, it is visible in the comment section of the unit for all languages. It would be useful to be able to mark comments that relate to the translation only so that are not shared with other languages.

Maybe this idea was discussed before already ?

**Comment by nijel** [comment]
You can choose scope of the comment when adding it...

**Comment by dachary** [comment]
Damn, I made a fool of myself on this one... Sorry for the noise.
