### ISSUE TITLE
Achieve better results with WeblateTranslation and WeblateSimilarTranslation

### ISSUE THREAD

**Issue by mlaggner** [WeblateOrg/weblate#1791]
When using the machine translation engines by Weblate, I've discovered some minor things with the following example:

Source string: Abfuhrschein

Results:

| Translation | Source string | Engine | Quality index |
|---|---|---|---|
|Should the advice note be saved before?|Soll der Abfuhrschein vorher gesichert werden?|Weblate (SAP/SAP-EFO) | 100|
|Change documents for advice note &1. | Änderungsbelege zu Abfuhrschein &1 | Weblate (SAP/SAP-EFO) | 100|
|Advice note | Abfuhrschein | Weblate (SAP/SAP-EFO) | 100|
|Advice note | Abfuhrschein | Weblate (SAP/SAP-EFO) | 100|
|Advice note | Abfuhrschein | Weblate (SAP/SAP-EFO) | 100|
|EFO advice note | [OBSOLETE!] EFO Abfuhrschein | Weblate (SAP/SAP-EFO) | 100|
|Change documents for delivery note & | Änderungsbelege zu Abfuhrschein & | Weblate (SAP/SAP-EFO) | 100|

two points could be improved here:

- create some sort of string distance (Levensthein?) for the _source string_ to compare it to the desired result rather than give it 100% (or 50% via WeblateSimilarTranslation)
- remove duplicates

what do you think?

**Comment by mlaggner** [comment]
what about using the Dice Coefficient algorithm here?
https://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Dice%27s_coefficient#Python

have been using this algorithm for string scoring in another project and has been returned rather good results

**Comment by nijel** [comment]
I've addressed this partly in 1ca5c60fae58e7fa6bf3d8ae789ee144f229c34d - now WeblateTranslation behaves are originally designed (to find only exact matches).

I guess the duplicates are coming from strings using different IDs but same source, right?

**Comment by mlaggner** [comment]
yes, that's one nature of SAP-internal translations..
we have strings in different lengths to display (5 different texts for one dictionary element) and sometimes the text is rather short that there is the same in 5 different IDs

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
