### ISSUE TITLE
Wrong history shown on git merge

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1797]
### Steps to reproduce
1. Let Weblate create merge commit.
2. Look at it on GitHub (or other tool which shows diff for merge commit)

### Actual behaviour

The diff in upstream changes is shown, for example:
https://github.com/WeblateOrg/weblate/commit/4e50b8ce278989d85b5a2560e13c8d3ea691e36b

### Expected behaviour

The diff with Weblate changes should be shown.

### The problem

All tools seem to use the second parent as branch to show diff, so Weblate should create the merge commit in reverse order. However there seems to be no way to tell git to do this.

As a workaround Weblate could do following:

```
# Create local branch for upstream
git branch tmp origin/master
# Checkout upstream branch
git checkout tmp
# Merge current Weblate changes, this can lead to conflict
git merge master
# Checkout branch with Weblate changes
git checkout master
# Merge temporary branch (this is fast forward so does not create merge commit)
git merge tmp
# Delete temporary branch
git branch -d tmp
```
As this involves quite a lot of manipulations with the repository, it can lead to performance issues. Also this really looks too complex for simple thing we want to achieve.

PS: Asked this question on [StackOverflow](https://stackoverflow.com/q/48302475/225718).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by MikhailTymchukDX** [comment]
Cool!
Is it live on https://hosted.weblate.org/?

**Comment by nijel** [comment]
Not yet, it's only in git so far. Will be probably deployed next week.

**Comment by MikhailTymchukDX** [comment]
Is it live? If not, how can I be notified about it?

**Comment by nijel** [comment]
Yes, it's live, here is example of such merge commit: https://github.com/WeblateOrg/weblate/commit/942dda2f73f7419596f51e3365ec6dbd7fe8673f
