### ISSUE TITLE
 error "Incorrect padding" when using OpenID

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#1799]
### Steps to reproduce
1. Install YunoHost (on Debian 8)
2. Install Weblate (testing is 2.18)
3. Try to register with oauth (current install enables Fedora/Ubuntu/OpenSuse)

### Actual behaviour
It crashes with "Incorrect padding"
Full paste: https://paste.fedoraproject.org/paste/DgpYVI7-w8~AizEbNT5Yrw

### Expected behaviour
Should be able to register and connect.

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

> (venv)weblate@jb:~$ DJANGO_SETTINGS_MODULE="weblate.settings" weblate list_versions
>  * Weblate 2.18
>  * Python 3.4.2
>  * Django 2.0.1
>  * six 1.11.0
>  * social-auth-core 1.6.0
>  * social-auth-app-django 2.1.0
>  * django-appconf 1.0.2
>  * Translate Toolkit 2.2.5
>  * Whoosh 2.7.4
>  * defusedxml 0.5.0
>  * Git 2.1.4
>  * Pillow (PIL) 1.1.7
>  * dateutil 2.6.1
>  * lxml 4.1.1
>  * django-crispy-forms 1.7.0
>  * compressor 2.2
>  * djangorestframework 3.7.7
>  * pytz 2017.3
>  * pyuca N/A
>  * python-bidi 0.4.0
>  * pyLibravatar N/A
>  * PyYAML 3.12
>  * hub 2.3.0-pre10
>  * Database backends: django.db.backends.postgresql_psycopg2

I tried with or without SMTP authentification, no change.
Here is the setting file: https://github.com/YunoHost-Apps/weblate_ynh/blob/testing/conf/settings_history/settings.2.18.py

Thanks for your help!

**Comment by nijel** [comment]
Looks like some issue in ptyhon-social-auth. Can you check what's value of s in the exception (expand the "Local vars" in last traceback item)?

**Comment by Jibec** [comment]
here it is:

Variable | Value
-- | --
s | b"b'vKbH/q146X08aO7/l16C3/mcwrM=\\n'"

**Comment by nijel** [comment]
Okay, it's twice encoded as binary string. IMHO bug in social_core or openid library are you using latest in both cases?

**Comment by Jibec** [comment]
I have no idea, I used pip to install dependencies. And the install itself is from yesterday.

**Comment by Jibec** [comment]
Here is the result of pip freeze:

> (venv)weblate@jb:~$ pip freeze
> Babel==2.5.3
> certifi==2017.11.5
> chardet==3.0.4
> defusedxml==0.5.0
> diff-match-patch==20121119
> Django==2.0.1
> django-appconf==1.0.2
> django-compressor==2.2
> django-crispy-forms==1.7.0
> django-sendmail-backend==0.1.2
> djangorestframework==3.7.7
> idna==2.6
> lxml==4.1.1
> oauthlib==2.0.6
> Pillow==5.0.0
> psycopg2==2.7.3.2
> py3dns==3.1.0
> PyJWT==1.5.3
> pyLibravatar==1.7
> python-bidi==0.4.0
> python-dateutil==2.6.1
> python-memcached==1.59
> python3-openid==3.1.0
> pytz==2017.3
> pyuca==1.2
> PyYAML==3.12
> rcssmin==1.0.6
> requests==2.18.4
> requests-oauthlib==0.8.0
> rjsmin==1.0.12
> siphashc==1.0
> six==1.11.0
> social-auth-app-django==2.1.0
> social-auth-core==1.6.0
> translate-toolkit==2.2.5
> urllib3==1.22
> Weblate==2.18
> Whoosh==2.7.4

python3-openid==3.1.0
which is consistent with: https://github.com/necaris/python3-openid/tags (but there is no formal release for the last two tags)

social-auth-app-django==2.1.0
which is consistent with: https://github.com/python-social-auth/social-app-django/releases

> social-auth-core==1.6.0
which is consistent with: https://github.com/python-social-auth/social-core/releases

**Comment by Jibec** [comment]
Btw, I'm using Python 3.4 (Debian Stretch)

**Comment by nijel** [comment]
Right the issue might as well be Python 3 related. Anyway I'd suggest reporting this against social-core, as this is what handles OpenID authentication an Weblate should not influence this at all...

**Comment by Jibec** [comment]
Please leave this open for now, I'll try with 2.19 and Debian 9, and come back here for an update.
-- 
Jean-Baptiste Holcroft

**Comment by Jibec** [comment]
I spent some time on this, and decided to revert my python3 migration and to say with python 2.7...

**Comment by nijel** [comment]
JFYI: I've included patch from https://github.com/python-social-auth/social-app-django/pull/136 in our docker container to address this, see https://github.com/WeblateOrg/docker/commit/8a8eb2e2923c46b51c28f1ebeab82d457511f9ff

**Comment by Jibec** [comment]
oh, interesting thank you! This means I can install with pip and then patch the installed code :)

**Comment by nijel** [comment]
Yes, it's ugly, but works.

**Comment by Jibec** [comment]
hi, I'm again hitting this bug with weblate 3.5.1; any help would be much appreciated


```Environment:
Request Method: POST
Request URL: https://translate.domain.tld/accounts/login/fedora/?next=/

Django Version: 2.1.2
Python Version: 3.5.3
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin.apps.SimpleAdminConfig',
 'django.contrib.admindocs',
 'django.contrib.sitemaps',
 'social_django',
 'crispy_forms',
 'compressor',
 'rest_framework',
 'rest_framework.authtoken',
 'weblate.addons',
 'weblate.auth',
 'weblate.checks',
 'weblate.formats',
 'weblate.machinery',
 'weblate.trans',
 'weblate.lang',
 'weblate.langdata',
 'weblate.memory',
 'weblate.screenshots',
 'weblate.accounts',
 'weblate.utils',
 'weblate.vcs',
 'weblate.wladmin',
 'weblate')
Installed Middleware:
['weblate.middleware.ProxyMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'weblate.accounts.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'weblate.accounts.middleware.RequireLoginMiddleware',
 'weblate.middleware.SecurityMiddleware']



Traceback:

File "/var/www/weblate/venv/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/var/www/weblate/venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)

File "/var/www/weblate/venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/www/weblate/venv/lib/python3.5/site-packages/django/views/decorators/http.py" in inner
  40.             return func(request, *args, **kwargs)

File "/var/www/weblate/venv/lib/python3.5/site-packages/weblate/accounts/views.py" in demo_wrap
  199.         return function(request, *args, **kwargs)

File "/var/www/weblate/venv/lib/python3.5/site-packages/weblate/accounts/views.py" in social_auth
  865.     return auth(request, backend)

File "/var/www/weblate/venv/lib/python3.5/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)

File "/var/www/weblate/venv/lib/python3.5/site-packages/social_django/utils.py" in wrapper
  49.             return func(request, backend, *args, **kwargs)

File "/var/www/weblate/venv/lib/python3.5/site-packages/social_django/views.py" in auth
  23.     return do_auth(request.backend, redirect_name=REDIRECT_FIELD_NAME)

File "/var/www/weblate/venv/lib/python3.5/site-packages/social_core/actions.py" in do_auth
  27.     return backend.start()

File "/var/www/weblate/venv/lib/python3.5/site-packages/social_core/backends/base.py" in start
  34.         if self.uses_redirect():

File "/var/www/weblate/venv/lib/python3.5/site-packages/social_core/backends/open_id.py" in uses_redirect
  242.         return self.openid_request().shouldSendRedirect()

File "/var/www/weblate/venv/lib/python3.5/site-packages/social_core/backends/open_id.py" in openid_request
  248.                                          params))

File "/var/www/weblate/venv/lib/python3.5/site-packages/openid/consumer/consumer.py" in begin
  359.             return self.beginWithoutDiscovery(service, anonymous)

File "/var/www/weblate/venv/lib/python3.5/site-packages/openid/consumer/consumer.py" in beginWithoutDiscovery
  382.         auth_req = self.consumer.begin(service)

File "/var/www/weblate/venv/lib/python3.5/site-packages/openid/consumer/consumer.py" in begin
  610.             assoc = self._getAssociation(service_endpoint)

File "/var/www/weblate/venv/lib/python3.5/site-packages/openid/consumer/consumer.py" in _getAssociation
  1178.         assoc = self.store.getAssociation(endpoint.server_url)

File "/var/www/weblate/venv/lib/python3.5/site-packages/social_core/store.py" in getAssociation
  43.         for assoc_id, association in self.assoc.oids(server_url, handle):

File "/var/www/weblate/venv/lib/python3.5/site-packages/social_core/storage.py" in oids
  227.             for assoc in cls.get(**kwargs)

File "/var/www/weblate/venv/lib/python3.5/site-packages/social_core/storage.py" in <listcomp>
  227.             for assoc in cls.get(**kwargs)

File "/var/www/weblate/venv/lib/python3.5/site-packages/social_core/storage.py" in openid_association
  235.         return OpenIdAssociation(assoc.handle, base64.decodestring(secret),

File "/var/www/weblate/venv/lib/python3.5/base64.py" in decodestring
  560.     return decodebytes(s)

File "/var/www/weblate/venv/lib/python3.5/base64.py" in decodebytes
  553.     return binascii.a2b_base64(s)

Exception Type: Error at /accounts/login/fedora/
Exception Value: Incorrect padding
```

And here is the result of pip freeze
```
$ pip freeze
amqp==2.3.2
Babel==2.6.0
billiard==3.5.0.4
celery==4.2.1
celery-batches==0.2
certifi==2018.10.15
chardet==3.0.4
defusedxml==0.5.0
diff-match-patch==20121119
Django==2.1.2
django-appconf==1.0.2
django-compressor==2.2
django-crispy-forms==1.7.2
django-redis==4.9.0
django-sendmail-backend==0.1.2
djangorestframework==3.9.0
et-xmlfile==1.0.1
filelock==3.0.9
hiredis==0.2.0
idna==2.7
jdcal==1.4
jellyfish==0.6.1
kombu==4.2.1
lxml==4.2.5
oauthlib==3.0.1
openpyxl==2.5.9
phply==1.2.5
Pillow==5.3.0
pkg-resources==0.0.0
ply==3.11
psycopg2-binary==2.7.5
py3dns==3.2.0
PyJWT==1.6.4
pyLibravatar==1.7
python-bidi==0.4.0
python-dateutil==2.7.5
python3-openid==3.1.0
pytz==2018.6
pyuca==1.2
PyYAML==3.13
rcssmin==1.0.6
redis==2.10.6
requests==2.20.0
requests-oauthlib==1.0.0
rjsmin==1.0.12
siphashc==1.2
six==1.11.0
social-auth-app-django==3.1.0
social-auth-core==3.1.0
translate-toolkit==2.3.1
translation-finder==1.0
ua-parser==0.8.0
urllib3==1.24
user-agents==1.1.0
vine==1.1.4
Weblate==3.5.1
Whoosh==2.7.4
```

**Comment by nijel** [comment]
Is it for new authentication? It's possible that the corrupted values are stored from older broken versions?

**Comment by Jibec** [comment]
thanks, it looks like coming from older values indeed, I totally removed weblate and reinstalled it and it now works, but ho can I fix it for users upgrading from older weblate version?

**Comment by nijel** [comment]
I think the corrupted values look like `b'string'` and you need to strip the extra chars to make it just `string`. AFAIR this was happening only inside the `social_auth_association` table.
