### ISSUE TITLE
Translate Andtoid project

### ISSUE THREAD

**Issue by hram** [WeblateOrg/weblate#1800]
Hi all
I am rtying to configure translation for android project.  I read all docs but do not do crete component.  Where can I found example for configyrstion? Or how can I get help for that? 
Maybe some video or tutorial?

**Comment by nijel** [comment]
I've just added the example to the documentation:

https://docs.weblate.org/en/latest/formats.html#android-string-resources

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
