### ISSUE TITLE
Status of YAML support

### ISSUE THREAD

**Issue by frodrigo** [WeblateOrg/weblate#1805]
The doc indicate that the YAML support is done under a specific branch of `translate`: https://docs.weblate.org/en/latest/formats.html#yaml-files

Now this code is merged into the lasts translate-toolkit.

Nevertheless, I just update my weblate instance from 2.13 to the 2.18. Before I was using the a specific branch of translate-toolkit. Now it should work without hack. But there is no "yaml' in the setting for file format.

**Comment by nijel** [comment]
You need to install PyYAML for yaml support, I've clarified this in the docs.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
