### ISSUE TITLE
Double notification about new language request

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1806]
### Steps to reproduce
1. Set up a component with PO
2. Configure admin profile to a non-english language (Spanish in my case)
3. Receive a new language request

### Actual behaviour
Two notifications arrive: one in English, one in Spanish.

### Expected behaviour
Only one notification arrives, in interface profile language.

### Server configuration
```
 * Weblate weblate-2.17
 * Python 2.7.12
 * Django 1.11.7
 * six 1.11.0
 * social-auth-core 1.5.0
 * social-auth-app-django 2.0.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.1
 * lxml 4.1.1
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.3
 * pytz 2017.3
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.4.1
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
English one is sent to configured ADMINS, there is currently no way to disable this.

**Comment by burner1024** [comment]
So this is intended behavior? All right.
It's a minor thing, I just thought that you should know.

**Comment by nijel** [comment]
It's intentional, currently ADMINS get:

* New language request
* Parse error
* Merge error

The latter two should IMHO stay, new language request is indeed questionable...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
