### ISSUE TITLE
HTML in whiteboard? [$50]

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1807]
It seems whiteboard only supports plain text, or am I missing something? I mean, a link become a link, but you can't change anchor.
Weblate 2.17

**Comment by nijel** [comment]
AFAIR it's like you describe, the string is passed just though [urlize](https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#urlize).

**Comment by burner1024** [comment]
It would probably be nice to have at least anchors

**Comment by nijel** [comment]
Maybe having option to have it as html. The default probably should stay like it is now to avoid problems when user writes there invalid html....

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
