### ISSUE TITLE
Timeout on commit_pending (FileLock), zombie git

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1811]
### Steps to reproduce
Not really sure... Active translation?

### Actual behaviour
```
File "/mnt/weblate_html/weblate/trans/filelock.py", line 102, in acquire
  raise FileLockException("Timeout occured.")
  weblate.trans.filelock.FileLockException: Timeout occured.
```
This is due to a zombie git process:
```
weblate  25794  0.0  0.0      0     0 ?        Z    11:57   0:00 [git] <defunct>
```
There are no errors in uwsgi log. After uwsgi restart, commit works properly.

### Expected behaviour
No timeout.

### Server configuration
```
 * Weblate weblate-2.17
 * Python 2.7.12
 * Django 1.11.7
 * six 1.11.0
 * social-auth-core 1.5.0
 * social-auth-app-django 2.0.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.1
 * lxml 4.1.1
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.3
 * pytz 2017.3
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.4.1
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
The question is why there is zombie from the git process, Weblate is holding the lock until git terminates, so rest is kind of expected. I don't have much clue how to debug this...

**Comment by burner1024** [comment]
Zombie doesn't do anything, it's completed the task and only waits until parent process (uwsgi) reads its status. So I don't think git at fault.
I'll update if any details surface.

**Comment by nijel** [comment]
The code used to start processes is quite straightforward:

https://github.com/WeblateOrg/weblate/blob/55d6736c48a5f5de3cd16072b757a7332e106390/weblate/trans/vcs.py#L164-L173

The [communicate](https://docs.python.org/2/library/subprocess.html#subprocess.Popen.communicate) method waits for process to terminate, so the only way I can imagine it to crash is when subprocess outputs too much to fit into memory...

**Comment by nijel** [comment]
@burner1024 did you manage to discover why this happens?

**Comment by burner1024** [comment]
No. I've seen it one more time, but I'm not sure how to debug.
The activity is very low at the moment, so I'm not sure when to expect it again.
