### ISSUE TITLE
Disable "Strings waiting for review"

### ISSUE THREAD

**Issue by hram** [WeblateOrg/weblate#1813]
Can I disable yelow block "Strings waiting for review"?
I have no reviewers and do not want that my translators see this warning block.
Even after 100% translation I see this frightening block.

**Comment by nijel** [comment]
Just disable "Enable reviews" for your project (either in admin interface or in Access control in Weblate).

**Comment by hram** [comment]
I checked project settings and "Enable reviews" is unchecked

**Comment by hram** [comment]
Powered by Weblate 2.18

**Comment by nijel** [comment]
Sorry, the displaying of this was removed after 2.18 release in e0401821e9.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by hram** [comment]
@nijel this is now tagged as "bug" but steel in state "close"
you may forget about this bug
