### ISSUE TITLE
Uploaded strings lose flags

### ISSUE THREAD

**Issue by frankenfine** [WeblateOrg/weblate#1814]
### Steps to reproduce
1. Upload translations into project
2. Merge Method: Add as translation needing edit
3. Processing of strings needing edit: Import as string needing edit
4. Click Upload

### Actual behaviour
After upload I see message: x number of strings needing edit, but after a few hours or more that disappears and no strings are marked for edit anymore.

### Expected behaviour
After upload I expect to see message: x number of strings needing edit until reviewer/editor comes through and individual checks each one

### Server configuration
This happened after updating to Weblate 2.19-dev
Is there something I have to reconfigure to keep those flags from being reset?

**Comment by nijel** [comment]
What file format is used for that translation? It seems that it's one of these not supporting this flag natively and persistence in Weblate has failed. Also do you have any of `skip-review-flag` or `skip-source-review` flags enabled for the translation component?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. It would be great if you can confirm the fix as your exact setup was not known me when fixing this issue.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by frankenfine** [comment]
The files are .properties files and .json files.
Neither of those flags are set on either components. Coincidentally, I did an upload on one language before 2.19 and the rest of my languages after. The one before has all that set to review still, the rest lost it.

**Comment by nijel** [comment]
2.19 is not yet released, I guess you mean 2.18?

**Comment by frankenfine** [comment]
bottom says 2-19 dev.
Updated via Git and so far changes seem to be sticking

**Comment by nijel** [comment]
Great, please report back if you spot any problems.
