### ISSUE TITLE
Question: API requests number before 429 error

### ISSUE THREAD

**Issue by Cussa** [WeblateOrg/weblate#1815]
Here on the company we have to generate some files on a specific format to be send to some translators.
I create a app that connects to Weblate Api (the installation is on our server) and get the strings that need to be translated.
But after sometime, I'm starting to receiving a 429 error. Even that I saw something about this error on the documentation, I didn't find any kind of information that says how many requests I can do before starting receive this error.

Is this information write somewhere or can someone help me?

**Comment by nijel** [comment]
You can configure API throttling in the settings:

https://github.com/WeblateOrg/weblate/blob/f790f4800504f7abbf1ab3a1195871a4ad9c13ac/weblate/settings_example.py#L700-L703
