### ISSUE TITLE
Supporting checking out branches in git svn

### ISSUE THREAD

**Issue by davidnorthetal** [WeblateOrg/weblate#1817]
Hey,

currently checking out an svn-branch via git-svn is not supported in my case, because weblate calls `['svn', 'init', '-s', '--prefix=origin/', pull_url, self.path]` on a checkout.

Is `-s` required? - with `-s` I get a "Using higher level of URL: ... => ..." which ends up checking out a base that is not `--stdlayout` compatible and thus doesn't check out anything.

This might be a misconfiguration on my SVN setup, but removing `-s` and just setting the `Source code repository` to the branch directly seems to work.

Would it be possible to omit `-s` without further issues?

@nijel would love your opinion on that

Thanks for any input!

**Comment by nijel** [comment]
The big problem I see with omitting `-s` now is that it would break existing setups.

It was probably not wise choice to use it from beginning, but I don't see easy way to migrate from it now...

**Comment by davidnorthetal** [comment]
actually, it seems to work with `-s` now, where it didnt before, I'm setting the `Source code repository` to the root and `Repository branch` to the branch name of the svn-branch and it succeeds to add - and normal operations seem to go through fine.

It actually is standard-layout, however I could swear it didn't work before doing the same thing.

I'm going to do this a lot in the near future so I'll see if this was just a fluke right now.

Thanks for your effort yet again!

**Comment by nijel** [comment]
Well I got email request from another user where stdlayout was causing troubles, that's why I tend to think it was probably bad decision in the beginning. Anyway I'm not a Subversion user, so it's hard to guess for me what is expected behavior here ;-).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
