### ISSUE TITLE
Support for relative locations in Qt TS files

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1819]
### Steps to reproduce
1. Import translation using Qt TS files

### Actual behaviour
The source string location is not shown.

### Expected behaviour
The source string location should be shown when it is present in the file.

### The problem

The location is stored as offsets in Qt TS files, so to know location of message, one has to process previous locations as well, for example:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="cs_CZ">
<context>
    <name>AboutDialog</name>
    <message>
        <location filename="../src/tiled/aboutdialog.ui" line="+14"/>
        <source>About Tiled</source>
        <translation>O Tiled</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Donate</source>
        <translation>Přispět na vývoj</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>OK</source>
        <translation>OK</translation>
    </message>
</context>
<context>
    <name>AddPropertyDialog</name>
    <message>
        <location filename="../src/tiled/addpropertydialog.ui" line="+14"/>
        <source>Add Property</source>
        <translation>Přidání vlastnosti</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Property name</source>
        <translation type="unfinished"></translation>
    </message>
</context>
```

Weblate currently simply discards those as it can not reasonably construct location links from these partial information:

https://github.com/WeblateOrg/weblate/blob/61e68183ae8ed3c7d2c736342bcbb1fd47604bdd/weblate/formats/ttkit.py#L138-L145

The major problem being that you can not construct location without knowing previous locations. Solution might be to cache units locations while parsing.

**Comment by nijel** [comment]
Util Weblate supports this, it is recommended to generate Qt TS files with absolute locations (`lupdate -locations absolute ...`), what is also default.

**Comment by bjorn** [comment]
Hey @nijel, thanks for opening an issue about this.

Now that I know this is the problem, I could of course switch to absolute locations. But the reason for relative locations is to keep down the diffs when updating translation files, since otherwise a single line added somewhere would end up changing the location of many strings.

I would have guessed that deriving the absolute locations while parsing the file should be trivial, but I am surprised by the ad-hoc parsing of XML in various places which does indeed make this into a rather involved change...

**Comment by nijel** [comment]
The problem is that so far there was no need to share context when parsing units - each can be decoded separately without knowing anything about the file. With relative locations, you need to store context (last file, last offset in each file) while parsing translation units.

It's not something hard to solve, just nobody did invest time into that so far.

**Comment by Naruto0** [comment]
Hi @nijel 
Can you please suggest some translation contiaining relative paths so i can import it and fiddle?
Thanks.

**Comment by nijel** [comment]
The example is in the inital comment :-)
