### ISSUE TITLE
Restructure code

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1820]
Historically we have most of the code in the `weblate.trans` module, while some of the things would deserve to be separate top level modules under `weblate`:

* [x] checks
* [x] machine translations
* [x] file formats
* [x] version control
* [x] rename subproject to component to avoid using historical name

There might be more of these and associated tests should moved as well.

**Comment by BhaaLseN** [comment]
Those file formats are a pain point for me as well at this time. I got a new format hacked in until I can get around to clean it up and properly submit it to translate-toolkit; and even then it needs an addition in there.
Right now I have to make sure to reapply my customizations on every update, with the chance of conflicts.

I did start a local branch to seperate out the individual file formats into their own file, but kinda got stuck on how to sensibly load all formats in that module without having to update a file/variable all the time as well (like the `__all__` variable in the `__init__.py` file).
My eventual goal with this was to simply drop my custom format (hacky or not) in there and it-just-works™ (at least until the point where some API changes).

If you have thoughts and ideas on how to go about this, please share them; depending on your 3.0 schedule you may see a PR from me (once i got the tt store sorted out).

**Comment by nijel** [comment]
The alternative approach to registration might be listing them in settings similarly as we do with addons, checks and so on...

**Comment by BhaaLseN** [comment]
Sounds like a sensible choice, and would get of the registration code too (which was one of the issues I had...since I didn't want to split everything up just to see it not work, I started with one format and ended up in an include loop for those functions).
Plus it would clean up the drop down a little; right now we got like 20 or 30 formats in there and use effectively 3.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
