### ISSUE TITLE
Using groups from social auth token to Weblate groups

### ISSUE THREAD

**Issue by ieugen** [WeblateOrg/weblate#1821]
Hello, 

Does Weblate support using group info from JWT token from social auth?

We have setup integration with Azure Ad via social auth (weblate + django python social auth) . 
However that does not seem to use the groups from Azure AD. We have updated the manifest to include "groupMembershipClaims": "All" as in [1]. (Did not check the token yet, will do soon)

I've included some information about the tokens and Azure AD. 

[1] https://www.red-gate.com/simple-talk/cloud/security-and-compliance/azure-active-directory-part-4-group-claims/
[2] https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-application-manifest

### Steps to reproduce

1. Setup social auth with Azure AD Free.
2. Create some security groups and assign users to them
3. Login to weblate with oauth azure.
4. Check Users page, the groups column: expect the groups created in Azure AD and assigned to the user to be there.

### Actual behaviour
Groups are not created/assign in weblate as with LDAP integration. 

### Expected behaviour
Groups should be created or at least assigned to users in weblate. 

### Server configuration

Weblate 2.18.

**Comment by nijel** [comment]
AFAIK there is currently no support for assigning groups in python-social-auth.

**Comment by ieugen** [comment]
Don't know the code but to me it seems like weblate responsability. 

Python social auth handles everything up until you get a token.

What you do with the token and the information within is app specific. In this case Weblate.

I presume that once a token is received with group information Weblate could/should check the groups do the mapping. Of course if this is desired via configuration. Like in LDAP case. 

Does that seem ok with you?

**Comment by nijel** [comment]
In LDAP case it's handled by django-auth-ldap, not by Weblate :-).

**Comment by ieugen** [comment]
It means that it's django the app here. Thanks. I don't know if we can do much about this right now.

**Comment by ShadowXVII** [comment]
@ieugen , sorry to hijack your issue, but wondering if you could provide some insight on how to configured Social Auth for Azure AD? Having some issue on 3.4, discussed in #2497 .
