### ISSUE TITLE
add support for source string review

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1822]
Weblate 2.18 brings a nice new feature: translation review. But English may need review as well.

It would be nice to add review flag to source strings as well.

It could work similar (or even merged with) to English (or other source language) translation, but it would process differently: 

- Empty strings would not be considered as untranslated.

- Review flag can work in the same way, but translators can be notified about translation of unapproved English string.

 Needs edit/suggestion will issue a message to the developer or it will create a bugfix-po file, and maybe adds a message to translators: The source string needs edit.

### Steps to reproduce
N/A

### Actual behaviour
N/A

### Expected behaviour
N/A

### Server configuration
N/A

**Comment by mfrasca** [comment]
I am having the same problem/perplexity.  as non native writer, I tend to put Latin constructions into English, which no grammar checker would sanction as incorrect, but any native speaker would find curious to say the least.  I understand editing the original can work with Android resource files, but what do we do with Python or sphinx collected `po` files?

**Comment by nijel** [comment]
In case source strings review is enabled, it would behave this way:

* Once new source string is imported, it's marked as needs review, at this point all translations of this string will be read only
* At approval the state changes and translations are opened up for editing
* New interface to request review of source string (see https://github.com/WeblateOrg/weblate/issues/2772 and https://github.com/WeblateOrg/weblate/issues/756)

There can be also extended workflow with intermediate translation as described in https://github.com/WeblateOrg/weblate/issues/3257
