### ISSUE TITLE
Language filter resets when paging search results.

### ISSUE THREAD

**Issue by Datanizze** [WeblateOrg/weblate#1823]
### Steps to reproduce
1. go to search
2. select a language in the dropdown
3. search for something common that results in paging
4. go to next page

### Actual behaviour
Language filter is no longer active

### Expected behaviour
Language should persist when paging.

### Server configuration
 * Weblate weblate-2.11
 * Python 2.7.5
 * Django 1.10.6
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.0
 * defusedxml 0.5.0
 * Git 1.9.3
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.4.4
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.4
 * pytz 2015.2
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.4
 * Database backends: django.db.backends.mysql

### Other
`lang` query param is not present in paging links.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported should be already fixed as of 170b9ba135.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
