### ISSUE TITLE
Search multiple languages at once

### ISSUE THREAD

**Issue by Datanizze** [WeblateOrg/weblate#1824]
You can chose either *all* languages or *one* language when searching, would be nice to be able to select a subset of languages.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
