### ISSUE TITLE
Clickable links to secondary languages in translate view

### ISSUE THREAD

**Issue by Datanizze** [WeblateOrg/weblate#1825]
When translating a string you can see a list of translations in your  [secondary languages](https://docs.weblate.org/en/latest/user/profile.html#secondary-languages) if they've been translated.

Would be nice to have a clickable link to quickly go to the translation for a secondary language.

**Comment by nijel** [comment]
The link is there (if user has permission to edit that language):

![screenshot-2018-2-2 weblate application - czech](https://user-images.githubusercontent.com/212189/35735496-4eff2408-0825-11e8-9270-053d2f47e9c9.png)

See also #1509.

**Comment by Datanizze** [comment]
Ah, Thanks!

We're running on an older release, should've checked the changelog more carefully.
