### ISSUE TITLE
Open source string location links in new tab

### ISSUE THREAD

**Issue by fxbenard** [WeblateOrg/weblate#1828]
### Steps to reproduce
1. In the translation UI
2. Source information
3. Source string location

### Actual behaviour
Links open in same tab

### Expected behaviour
Links open in new tab

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
