### ISSUE TITLE
"relation "weblate_addon" does not exist" Exception

### ISSUE THREAD

**Issue by Cussa** [WeblateOrg/weblate#1833]
Hello,

I'm having an exception on WebLate. Not following the common procedure because it's happening when my translators are working on the tool.

Here is the e-mail that I'm getting when the exception happens:

Request Method: | POST
-- | --
Request URL: | http://localhost:8000/translate/XXXX/YYYYYYYY/cs/?type=todo&offset=39
Django Version: | 1.11.6
Exception Type: | ProgrammingError
Exception Value: | relation "weblate_addon" does not existLINE 1: ...on"."configuration", "weblate_addon"."state" FROM "weblate_a...                                                             ^
Exception Location: | /usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py   in execute_sql, line 894
Python Executable: | /usr/bin/python
Python Version: | 2.7.12
Python Path: | ['/var/www/weblate', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']

exc | ProgrammingError('relation "weblate_addon" does not exist\nLINE 1: ...on"."configuration", "weblate_addon"."state" FROM "weblate_a...\n                                                             ^\n',)
-- | --
get_response | <bound method WSGIHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f920fdac410>>
request | <WSGIRequest: POST '/translate/XXXX/YYYYYYYY/cs/?type=todo&offset=39'>

===
Just to inform: even with the error, the translations seems that are been saved without problems.

### Server configuration
* Weblate weblate-2.18-1058-ge634800
 * Python 2.7.12
 * Django 1.11.6
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.0
 * defusedxml 0.4.1
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.5.0
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.1
 * user-agents 1.1.0
 * pytz 2014.10
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.11
 * Mercurial 3.7.3
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Please read the [upgrading instructions](https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-2-18-to-2-19).

**Comment by Cussa** [comment]
The system administrator forgot some steps. Working without problem.
