### ISSUE TITLE
merge failure sometimes causes repository exception

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1835]
When repositories diverge, I get a mail "failed push on repo". But sometimes it does not happen, and I get an internal server error instead.

It is possibly related with issue #1787 or #1834, as these errors often appear together.

### Steps to reproduce
1. Edit resources.
Not easy to reproduce.

### Actual behaviour

Request Method: | POST
-- | --
https://l10n.opensuse.org/translate/yast-update/master/es/?type=suggestions&offset=0
1.11.8
RepositoryException
On branch master Your branch and 'origin/master' have diverged, and have 76 and 52 different commits each, respectively.   (use "git pull" to merge the remote branch into yours) nothing to commit, working tree clean (1)
/usr/share/weblate/weblate/trans/vcs.py in _popen, line 183
/usr/sbin/uwsgi
2.7.13
['/usr/share/weblate/',  '.',  '',  '/usr/lib/python27.zip',  '/usr/lib64/python2.7',  '/usr/lib64/python2.7/plat-linux2',  '/usr/lib64/python2.7/lib-tk',  '/usr/lib64/python2.7/lib-old',  '/usr/lib64/python2.7/lib-dynload',  '/usr/lib64/python2.7/site-packages',  '/usr/lib64/python2.7/site-packages/PIL',  '/usr/local/lib64/python2.7/site-packages',  '/usr/local/lib/python2.7/site-packages',  '/usr/lib/python2.7/site-packages']
Wed, 7 Feb 2018 13:09:14 +0000

### Expected behaviour
Send a "failed push on repo" message, not cause internal server error.

### Server configuration
 * Weblate 2.18
 * Python 2.7.13
 * Django 1.11.8
 * six 1.9.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.2.4
 * Whoosh 2.7.0
 * defusedxml 0.5.0
 * Git 2.13.6
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.6.1
 * django-crispy-forms 1.7.0
 * compressor 2.1.1
 * djangorestframework 3.7.3
 * pytz 2016.10
 * PyYAML 3.12
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by stanislav-brabec** [comment]
Full backtrace was sent by e-mail.

**Comment by nijel** [comment]
The important thing is "nothing to commit, working tree clean" - so Weblate tries to create empty commit here...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. Though I'm not sure if the fix is complete, there might be other corner cases when this can happen which I did not discover.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
