### ISSUE TITLE
Check for " in translated strings

### ISSUE THREAD

**Issue by scootergrisen** [WeblateOrg/weblate#1836]
### Steps to reproduce
1. I had edited this string https://github.com/WeblateOrg/weblate/blob/master/weblate/templates/translate.html#L82 during danish translation by adding some **"**.
2. String was **Ctrl+Skift+Enter - fravælg "behøver gennemgang"-flag og gem**
3. Go translate a string in Weblate and notice the keyboard shortcut icon area.

### Actual behaviour
Text in keyboard shortcut area is messed up because of trouble with " in the data-title attribute.
Its partly visible even when not hovering the cursor on the keyboard icon.
Also the source string is pushed to the left so it look like there are newline for longs strings even though there are not.

### Expected behaviour
Check for " in translations and escape them or something.

```
<i class="fa fa-keyboard-o html-tooltip" data-toggle="tooltip" data-placement="bottom"
    data-title="Tilgængelige tastaturgenveje:<br />
    CTRL + Enter - Gem<br />
    Ctrl+Skift+Enter - fravælg "behøver gennemgang"-flag og gem<br />
...
    "></i>
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
