### ISSUE TITLE
One says "strings", other says "messages"

### ISSUE THREAD

**Issue by scootergrisen** [WeblateOrg/weblate#1837]
One say "messages", the other says "strings".
https://github.com/WeblateOrg/weblate/blob/master/weblate/templates/translate.html#L210
https://github.com/WeblateOrg/weblate/blob/master/weblate/templates/translate.html#L87
I think they should both say the same. Either messages or strings.

> Nearby messages
> Ctrl+J - Shows nearby strings tab

**Comment by nijel** [comment]
Indeed this is confusing. In some places probably "units" is used as well.

**Comment by scootergrisen** [comment]
Which ever is used we could use placeholders for such things as button names so they are always the same.

> Ctrl+J - Shows %s tab
Or
> Ctrl+J - Shows "%s" tab

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
