### ISSUE TITLE
InconsistentMigrationHistory when trying to upgrade from 2.18 to 2.19-git

### ISSUE THREAD

**Issue by mlaggner** [WeblateOrg/weblate#1838]
### Steps to reproduce
1. create a setup with weblate 2.18
2. try to upgrade to the latest version from git

### Actual behaviour
get the following exceptions on startup:

```
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration trans.0085_auto_20170406_0904 is applied before its dependency lang.0010_auto_20180129_1443 on database 'default'.
```

and 

```
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration permissions.0006_auto_20170404_1637 is applied before its dependency lang.0010_auto_20180129_1443 on database 'default'.
```

### Expected behaviour
migration should work

### Server configuration
the docker instance does not even start

reverting the first two changes of https://github.com/WeblateOrg/weblate/commit/ed22b1d60c3a6083e11a81f73de717362af77d98 seems to do the trick for me

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
