### ISSUE TITLE
Github: Squash merging of PR not detected

### ISSUE THREAD

**Issue by Flohack74** [WeblateOrg/weblate#1847]
### Steps to reproduce
1. Create a Weblate project with github type, install hub tool for PR style workflow
2. Create local changes, commit and push them in Weblate´s web interface
3. Weblate creates PR on Github
4. Merge the PR on the Github webpage
5. Pull in Weblate´s web interface

### Actual behaviour
Weblate pulls and wants to push local changes again, as it does not see it´s changes being merged on remote head

### Expected behaviour
Weblate pulls, should see squash merge and continue normally to commit on remote head

### Server configuration
 * Weblate 2.15
 * Python 2.7.12
 * Django 1.11.2
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.3
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.8.0
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.3
 * pytz 2017.2
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * hub 2.2.9
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
If you're doing this, choosing rebase instead of merge on Weblate side might be more desirable (and Git would detect the squashed changes automatically).

**Comment by Flohack74** [comment]
Ok. The problem is, we have a long list of projects, and a bunch of responsible people. Some of them will press Merge, some of them might squash. I will find out how we can get that consistent... thx for the lead

**Comment by nijel** [comment]
Using rebase on weblate side is safe in most cases, the only time it can cause problem is when somebody clones repository from Weblate and it the rebases. That's why it's not default. But if you're not having merge conflicts and do squash or rebase commits in GitHub, then I'd say rebase better choice than merge.

**Comment by Flohack74** [comment]
Ok will try that!

**Comment by Flohack74** [comment]
Nijel,

I got the following cronjobs in place to run every weekend:

```
0 0 * * 0 . /opt/weblate/bin/activate && DJANGO_SETTINGS_MODULE=weblate.settings weblate commit_pending --all
0 1 * * 0 . /opt/weblate/bin/activate && DJANGO_SETTINGS_MODULE=weblate.settings weblate pushgit --all
0 2 * * 0 . /opt/weblate/bin/activate && DJANGO_SETTINGS_MODULE=weblate.settings weblate updategit --all
0 3 * * 0 . /opt/weblate/bin/activate && DJANGO_SETTINGS_MODULE=weblate.settings weblate loadpo --all

```
How can I tell Weblate in this case to rebase the pull step instead of merge? How will it be if we enable automatic updates with the Github API webhook?

Thx

**Comment by nijel** [comment]
You can configure this by `Merge style` in [Component configuration](https://docs.weblate.org/en/latest/admin/projects.html#component-configuration). It will apply to all actions in Weblate (with exception of explicit merge/rebase in repository maintenance).

Also:

* pushgit is not needed if you have push on commit enabled (what is default)
* loadpo is generally not needed

**Comment by Flohack74** [comment]
Hmm when I try to change this on an existing component I get:

![grafik](https://user-images.githubusercontent.com/16186470/36072583-19d5bb80-0f22-11e8-803b-67cc33b2669b.png)

pushgit is added because I dont want to push every day, sometimes ppl translate only 1 word and leave again. Push on commit is off everywhere.
loadpo was added since we got issues with reacting on updates from upstream sometimes. Maybe it could be removed now, did not see this for some time.

**Comment by Flohack74** [comment]
Also interesting, I got a lot of changes that are not being committed automatically:

![grafik](https://user-images.githubusercontent.com/16186470/36072800-a445baaa-0f26-11e8-9efb-605e823e4086.png)

When I press the commit button, nothing happens...

**Comment by nijel** [comment]
It looks weird. Can you inspect the repository manually what has been changed?

**Comment by Flohack74** [comment]
Yes, I had this before, the manual git status output is the same. The changes were actually those: https://github.com/ubports/weather-app/commit/6ac35ddc12eaae5fcc1564282c275031392ef8d4 - So it apparently just changed a few non-important metadata and stuff.

I use the po regenerate hook as described in the docs... maybe its from there, but then Weblate does not think the file might have changed? But still commit butt on should commit those too ;)

**Comment by Flohack74** [comment]
After committing manually, and merging one more time, change to rebase + squash commit seems to work.

**Comment by Flohack74** [comment]
Have to add some sentences here after some time of experience with it:

So basically it turned out that we are indeed getting a lot of merge conflicts with squash and rebase workflow. The reason for that is:

- On Monday, Translator A makes changes - Commit A
- On Tuesday, Translator B makes also changes - Commit B
- Weblate pushes this once a week to Github and opens a PR
- The PR is merged on Github with squash - this leads to a new Commit AB
- Weblate get notified by the Github hook about new commits and pulls the log
- Weblate tries to rebase onto the upstream, but will fail here since it sees a conflict between the changes in Commit AB and Commit A (when it tries to sequentially rebase the diffs)

this creates too much manual work. It only works in the case when there is only 1 Commit during the whole week - So that all changes land in the same patch set.

Any ideas for that? I am currently considering to move back to the old way of not squashing and not rebasing, but this will eventually clutter our git logs quite much.

**Comment by nijel** [comment]
If git fails to see that these changes are already applied (presumably because touching one file and changing same or closely located content), then there is really no simple solution. I see two options to make it easier:

* Let Weblate commit all changes prior to merging and reset it after merging to upstream, this can be easily scripted (`wlc commit`, perform merge and `wlc reset`)
* Perform the squashing on Weblate side, see https://github.com/WeblateOrg/weblate/issues/2102
