### ISSUE TITLE
"The fulltext search might ..." shows in english

### ISSUE THREAD

**Issue by scootergrisen** [WeblateOrg/weblate#1852]
### Steps to reproduce
1. Go to search page like https://hosted.weblate.org/projects/weblate/master/da/#search

### Actual behaviour
At least sometimes it says "The fulltext search might not work properly as the fulltext index for this translation is not yet up to date." in english text.

### Expected behaviour
Text should be in the correct language. Danish (da) in this case.

**Comment by scootergrisen** [comment]
Also sometimes i get this string:

**Comment by scootergrisen** [comment]
If i search for a string and no string is found i get the english text "No matching strings found." in stead of the string from the language i am using.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
