### ISSUE TITLE
Make shortcut tooltip easier to read

### ISSUE THREAD

**Issue by scootergrisen** [WeblateOrg/weblate#1855]
### Steps to reproduce
1. Hover the keyboard icon (top right of editor) to see the keyboard short cuts.

### Actual behaviour
A tooltip div element is created but the text inside is centered and long lines are wrapped so its not very easy to read.
![tooltip](https://user-images.githubusercontent.com/1836590/36121790-8e5eadf6-1047-11e8-9063-fa0b1134533a.jpg)

### Expected behaviour
Suggest to put the shortcuts and text in a table element or something or at least dont center the text so its easier to read.

**Comment by DRD161** [comment]
@scootergrisen Id like to tackle this issue. I have downloaded and registered with Weblate but I cannot find where you see that keyboard icon. How are you getting to the editor to be able to see the keyboard icon?

**Comment by scootergrisen** [comment]
When you edit a string.
Like on https://hosted.weblate.org/translate/weblate/javascript/da/?type=all

**Comment by DRD161** [comment]
It seems to display fine on my screen, has this issue already been solved? I see no problem with text overlap in English. Which language has been giving you this error?

**Comment by scootergrisen** [comment]
There is no text overlap or error.
I just think its not so easy to ready the tooptip text.
If the text was not centeret but left it would be a little easier to read.
If the text was put into a table element it would be better.

Something like this.
![table](https://user-images.githubusercontent.com/1836590/36399835-fe8b1d9a-15cd-11e8-8b8f-abb1e6806421.jpg)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
