### ISSUE TITLE
Is "commit_pending" broken in 2.18?

### ISSUE THREAD

**Issue by BhaaLseN** [WeblateOrg/weblate#1857]
### Steps to reproduce
1. Configure a Component to do "Push on commit"
2. Leave "Age of changes to commit" as default; or change it to 0 or 1 (doesn't seem to matter in my case; especially since I want to use a cronjob with an explicit age of 0 to commit everything at the hour)
3. Make a change and verify that Manage > Repository Maintenance reads "There are some uncommitted changes!"
4. Wait for the hourly cronjob to run `../bin/python ./manage.py commit_pending --all --age=0 --verbosity=0` in the weblate directory; or run the command by hand as `www-data`

### Actual behaviour
Nothing happens. No entry in syslog, nothing printed on command line; not even with `--verbosity=3`.
Using Repository Maintenence > Commit works as expected though.

### Expected behaviour
Any change is committed and then pushed to the remote Git repository.

### Server configuration
Weblate 2.18 from Git (checked out the tag `weblate-2.18`) running on Debian 9.3 with a Python 3 virtualenv (hence the prefixing of `../bin/python` above/below to use the virtualenv executable instead of the global one)
```
$ ../bin/python ./manage.py list_versions
 * Weblate weblate-2.18
 * Python 3.5.3
 * Django 2.0.2
 * six 1.11.0
 * social-auth-core 1.6.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.1
 * lxml 4.1.1
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.7
 * pytz 2018.3
 * pyuca N/A
 * python-bidi 0.4.0
 * PyYAML 3.12
 * Database backends: django.db.backends.mysql
```

That database was migrated from an old system (to be retired) which ran 2.15 under Python 2 by transferring a DB dump over, then migrating it. DATA_DIR was copied over as-is (except for `whoosh`, which was regenerated by running `update_index`/ `rebuild_index`), everything seems to be correct there.

Other cronjobs (such as 5-minute `update_index` and hourly `updategit`) run correctly. The only thing that Commits the changes at this point is using Repository Maintenence.

I don't see anything in the logs, so I have no idea on how to debug this issue.

PS: I just noticed the `commitgit` command in the docs; I didn't try this one (yet) - but since the maintenance tasks section still uses `commit_pending` I didn't assume I should be using anything else here.

**Comment by nijel** [comment]
Do you get some error? It might be #1810

**Comment by BhaaLseN** [comment]
I don't get anything on console or syslog. Let me configure a logger and see if it writes anything there.

**Comment by nijel** [comment]
The error would be probably printed anyway...

**Comment by BhaaLseN** [comment]
I just added a [debug message next to the `repo_needs_commit` check](https://github.com/WeblateOrg/weblate/blob/master/weblate/trans/management/commands/commit_pending.py#L52-L53) - it returns `False` and skips everything (even though it should not).

**Comment by nijel** [comment]
Are there pernding changes in the database or in VCS?

**Comment by BhaaLseN** [comment]
Database only, VCS is clean.

**Comment by nijel** [comment]
Hmm, I don't see how it could go wrong, the code is pretty straightforward:

https://github.com/WeblateOrg/weblate/blob/8029b47f5f4948f1f101338afcb8a04fc424242c/weblate/trans/models/translation.py#L492-L497

Yes, recent versions batch updates to the filesystem for performance reasons.

Also note that --age=0 probably does something different than you expect (it uses default value), I've changed this just now to actually use the 0 in 5ad69eb66.

**Comment by BhaaLseN** [comment]
Thanks for the `--age=0` change!

Could it be that `unit_set` is not up2date, or returning something unexpected instead?

**Comment by nijel** [comment]
No it can't be outdated as it's not cached so it just does query the database (unless you're using django-cache-machine or something similar, what is definitely not supported).

**Comment by BhaaLseN** [comment]
Not that I know of.

`select count(*) from trans_unit where pending = 1;` returns the number of changes if I make any translation changes; but `translation.unit_set.filter(pending=True).count()` is 0 when i extend my debug message in `commit_pending.py`.
Anything else I could/should look at?

**Comment by nijel** [comment]
But these are pending changes for the single translation, not generally in the database. The equivalent SQL query would be `select count(*) from trans_unit where pending = 1 and translation_id= X;`.

**Comment by nijel** [comment]
As you can see there is loop over all matched translations:

https://github.com/WeblateOrg/weblate/blob/6c95f809c93b096b704da824a54cd139d5a84c5b/weblate/trans/management/commands/commit_pending.py#L51-L53

**Comment by BhaaLseN** [comment]
Well, appears it was the unexpected behavior of `--age=0` defaulting to the component. I had the default value there, so it wouldn't look at anything newer than a day.
I just cherry-picked 5ad69eb66f2f7b23e4d4c7b71946a849b29734e7 and it works as it should be. I'll be upgrading later to get the rest of the changes too. Thanks!
