### ISSUE TITLE
Does NewlineCountingCheck work?

### ISSUE THREAD

**Issue by mikefonted** [WeblateOrg/weblate#1858]
### Steps to reproduce
1. 
docker-compose stop

2.
Edit settings.py
CHECK_LIST = (
'weblate.trans.checks.chars.NewlineCountingCheck',
 )

3.
docker-compose start

4.
docker-compose exec weblate-container weblate updatechecks --all

### Actual behaviour
It does not detect the quality-check after 'updatechecks' nor even saving a new translation.
File formats: Android String Resource and OS X Strings (UTF-8).
![image](https://user-images.githubusercontent.com/6642583/36256448-3dca3e92-1253-11e8-8f88-c22306960da9.png)

### Expected behaviour
NewlineCountingCheck quality-check warning after 'updatechecks' and after saving a new translation.

### Server configuration
Weblate 2.8
Python 2.7.9
Django 1.10.8
six 1.11.0
python-social-auth 0.2.21
Translate Toolkit 2.2.0
Whoosh 2.7.4
defusedxml 0.4.1
Git 2.11.0
Pillow (PIL) 1.1.7
dateutil 2.2
lxml 3.4.0
django-crispy-forms 1.6.0
compressor 2.1
djangorestframework 3.4.7
pytz 2018.3
pyuca N/A
pyLibravatar N/A
Mercurial 3.9.1
git-svn 2.11.0
Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
It does work, though it checks different thing than you expect ;-). It checks for `\n` string not for actual newline.

**Comment by mikefonted** [comment]
Oh, understood. What a pity...

**Comment by nijel** [comment]
It's trivial to implement the check you want, there is generic base class and you just need to fill in the char to check and name:

https://github.com/WeblateOrg/weblate/blob/6c95f809c93b096b704da824a54cd139d5a84c5b/weblate/trans/checks/chars.py#L327-L333

**Comment by mikefonted** [comment]
Great! I did not remember the "Writing own checks" section of the docs. Thanks!
