### ISSUE TITLE
AttributeError ['unicode' object has no attribute 'read']

### ISSUE THREAD

**Issue by Cussa** [WeblateOrg/weblate#1859]
### Steps to reproduce
1. Download the CSV file
2. Change some translation
3. Import the file via API (using the option overwrite=true on the form)

### Actual behaviour
Request Method: | POST
-- | --
Request URL: | http://localhost:8000/api/translations/project/component/language/file/
Django Version: | 1.11.6
Exception Type: | AttributeError
Exception Value: | 'unicode' object has no attribute 'read'
Exception Location: | /var/www/weblate/weblate/trans/models/translation.py   in merge_upload, line 889
Python Executable: | /usr/bin/python
Python Version: | 2.7.12
Python Path: | ['/var/www/weblate', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
Server time: | Thu, 15 Feb 2018 16:17:32 +0000

### Expected behaviour
Server responds OK code and translations are imported.

### Server configuration
* Weblate weblate-2.19
 * Python 2.7.12
 * Django 1.11.6
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.0
 * defusedxml 0.4.1
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.5.0
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.1
 * user-agents 1.1.0
 * pytz 2014.10
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.11
 * Mercurial 3.7.3
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by Cussa** [comment]
@nijel one question: there is any idea when the 2.20 will be released? Because some of the translators are using files (instead of the WebLate) and, depending on the day that this will be fixed, I'll have to manually import more than 100 files.

**Comment by nijel** [comment]
How do you upload the file content?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
Weblate 2.19.1 is out with this fix.

**Comment by Cussa** [comment]
Thank's. It seems that even that I send that as a byte array, django understand that as string, not a file exactly. I change part of my code and now it's working.
