### ISSUE TITLE
The WIP list of improvements, suggestions and features. 

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#1862]
Have been writing things down for a while now. Some are probably already reported.
Respond with numbers, and I will take them out or make detailed bug-reports.

1 Logos for all projects, easier to navigate visually this way.
2 Better ways of sharing contact info for project owner, responsible person, project, IRC
3 Mark as needing upstream work
4 Mark as not sure
5 New fuzzy colour for strings that are changed upstream. Right now i think marking as issue is also red.
6 Condense vertical view/focal area to fit more strings. Natural field of view is precious.
7 When searching for untranslated, always use permanent canonical links, never offset  maybe / content ?
8 Better error reporting in Zen mode. live?
9 Ability to click away errors in Zen mode
10 Sharing translation memory, between all projects
11 See all translations in one document or being able to do searches across projects. At-least various branches in same resource.
12 Ability to make custom language checks.
13 Ability to mark terms as Wikipedia entries
14 Rewrite documentation of upstream links to strings /"translation browser" section
(I can do this, just haven't gotten around to it)
15 E-mails about new nontranslated strings don't take you directly to =nottranslated
16 Timeline of what happened today, updates, string changes. Click OK means reviewed.
17 Project announcements
18 Fields for string freeze, translation deadline, version launch.
19 When i click a link with a changed comment from an e-mail,
i get the interface in the language the comment was made in i want nb_NO (my local language)
20 Having to click to search, it should be a open field like in Pootle, for language overview and branch
21 Categories. Android category, security category, Linux program category, AGPL category, etc.
22 ~~In Zen mode, when there are multiple suggested languages, the source language is up top, should be bottom.~~
23 ~~Ability to start new language branch from language overview, not just clicking onto the different resources~~
Still not possible from 
https://hosted.weblate.org/projects/weblate/#languages
and
https://hosted.weblate.org/languages/nb/weblate/
24 ~~Different colour for source comments~~
25 Ability to delete own translations, useful when you paste by accident or make dumb suggestions.
26 Can't comment without losing string, Pootle does a new window to avoid it.
27 ~~The visual double dot on double whitespace from Pootle is very useful in preventing doublespaces, in source strings,~~ and also translations  #1930
and serves as a marker for starting space.
"*this is a string that starts with a space, double spaces**are marked."
28 Overview over what types of failings checks there are in regular view, not just amount.
29 Language checks for source strings
30 Sort by length in Zen-mode. Makes it easier to get all the small strings out of the way.
31 Can't click untranslated strings and go one string back to see what the previous untranslated one was
32 Can't search for single character padded by spaces " — " because it is too short.
33 ~~[Links to all other instances using Weblate](https://github.com/WeblateOrg/weblate/wiki/References), I know of a few. elementaryOS, SecureDrop, etc~~
34 ~~OpenSuse Ubuntu and Fedora logins like on https://translate.ubports.com/~~
35 Answering in comments with @username or Username:
36 Ability to change source strings from the editor. If only just as a comment that is saved locally. See 3
37 Shortest deadline shown first in suggested translation projects, see 18

38 contact dev upstream
39 Ability to see the whole thread in the e-mail when there is a new comment
40 Ability to mark a string as always matched, so no other possible interpretations for TM
41  - " **1**{placeholder1}</b> **2**{placeholder2} **3**{placeholder3} **4**{placeholder4} 5{placeholder5}Last opened Last modified{}"
If the string says that when copied, would be nice to move the numbers out of copyable text, and even inline view so that it doesn't appear to be the actual placeholder. If you copy it manually, or even just write it in.
42 Dictionary for a whole language, where entries can be valid for multiple languages.
Easy way to keep track of what sort of words were picked for each project.
43 ability search for something that isn't the selected section, for example searching in all strings when viewing untranslated strings
44 If you search for something, I'm pretty sure it also returns hits for source string URLs. Possible bug/feature?
45 Ability to get all untranslated strings across all projects of a language. Translatewiki has this. You just log in and you get strings in your editor right away, from many different things.
Would be a nice thing for reviews. (!)
46 All new strings for a language stack up for review in the same editor, no need to click individual projects. Click OK when done.
47 Individual Reviewed tags. I want to know if _I_ have reviewed something.
48 ~~Align Source and translation string markers in emails #1932~~
49 Having to click "Save" when following projects. A nice semi-solution would be to outline the "save" button once a change is made, so it is apparent that it has to be clicked.
50 Project timeline. New contributors, String freezes. Translation Deadlines.
51 When there are new strings in a project and the e-mail is sent out, make it ?date=aftercurrentdate to focus in on those strings, rather than everything that is untranslated.
52 ~~Page not found. Clicking sub-resource in project only works with "?type=untranslated." #1939~~
53 Ability to make Zen-mode the default viewer/editor.
54 Upstream linkable Android files
55 Being able to sort by "comments suggesting changes to source strings" (not just comments)
56 ~~Whitespaces in placeholders should be removed #1952~~
57 Emails/notifications about new subbranches in watched project #1956
58 ~~Commenting a multi-line string scrolls the string translation field #1963~~
59 Suggestions could be in between source and editor field to keep track of all three at the same time
60 Searching for something provides two or more hits if what you are searching for is found multiple times within a string. https://hosted.weblate.org/search/?page=5&lang=nb_NO&lang=nb&q=server&search=substring&target=1&type=translated
61 A way to @ reply in the comment section
62 Use discourse instead of comment section, projects could use their own forum.
63 ~~Distinguish which language is being translated #2031~~
64 Field scrolls outside of box when zooming webpage #2041 
65 "Link" and "Repository for this component is linked to" not translatable #2042
66 nb_NO incorrectly avoided, when it is correct, and nb should be avoided.  #2051
67 Add source code links for Android strings #2052
68 Visually focus the part of the image that contains the string in question. (OneSky has this)
69 A field in each project description that clarifies "Tone:" (OneSky has this)
70 Link to active PR, if string in question has a pending change upstream.
71 Graphs for total words/translated /available for all views. (Transifex has this)
72 ~~Clicking search does not go back to search #2088~~
73 ~~Wrong URL for nb_NO projects #2180~~
74 ~~Uploaded pictures added to statistics #2057 ~~
75 Editing source strings in Weblate logs out user doing it #2208
76 Tetris editing, show additional field below currently edited one #2209
77 ~~E-mail about new strings for translation brans all needing work as non-translated #2236~~

**Comment by nijel** [comment]
This long list will be hard to maintain :-). Anyway just quick response to some points:

7 - What if you want to share search results? I do use this quite often to send link to set of problematic strings.
10 - Is sort of there hidden behind Weblate machine translation.
22 - Done in 2aebd163d
23 - See https://github.com/WeblateOrg/weblate/issues/1369 and https://github.com/WeblateOrg/weblate/issues/1298
24 - Done in aeefaaf08
26 - See https://github.com/WeblateOrg/weblate/issues/1606
27 - Can you please followup in separate issue showing the feature? Weblate is also highlighting double whitespaces...
31 - This should work, if not there is a bug, but I can't reproduce.
33 - Maintained in https://github.com/WeblateOrg/weblate/wiki/References, feel free to add missing ones.
34 - Probably makes sense to add these, these were probably not present when I initially configured the service

**Comment by Kyuuu** [comment]
+1 for "16 Timeline of what happened today, updates, string changes"!
Mantis style would be nice!
![timeline](https://user-images.githubusercontent.com/33127074/63142346-bff06a00-bfe9-11e9-8fc8-9c223612fa05.png)

**Comment by nijel** [comment]
That's shown in the history, isn't it? https://hosted.weblate.org/projects/weblate/#history

**Comment by nijel** [comment]
@comradekingu is this issue still useful? It contains some useful features, but also contains lot of things which were already implemented and managing it this way doesn't seem to work well...
