### ISSUE TITLE
Javascript not working on login page

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1864]
See https://github.com/WeblateOrg/weblate/issues/1676#issuecomment-366940508:

![wb-jsstack](https://user-images.githubusercontent.com/482151/36420237-a6b92424-1634-11e8-99c0-8fbce3959788.PNG)

**Comment by nijel** [comment]
@macrojames it would be great if you could test if changes outlined in 61df59012040ad2a8e9b8b82b68bd6810cafee16 will fix it for you (adding /js/i18n/ to exceptions from required authentication), you need to adjust your settings with this change.

**Comment by macrojames** [comment]
It does fix the MIME-type error.
Still failing is the multiselect because the script Is running before the required dependency is loaded:
The line in question:
https://github.com/WeblateOrg/weblate/blob/cf467bf2d4e3085081b37b0917ef1d75e1b5e68c/weblate/static/loader-bootstrap.js#L1054

It should be somehow deferred after the jquery multiselect is really loaded?

Btw: my test environment here is simple a docker instance, http1.1 is direct access, http2 is cloudflare proxy access in free tier with http2 enabled.

**Comment by nijel** [comment]
That's weird. I assume you're running in debug mode (DEBUG = True) as otherwise all these would be compiled by compressor to one request. Does cloudflare any html rewriting (eg. Rocket Loader enabled)? Because the browser should execute the scripts in order as they are specified (we're not using async here), but that apparently doesn't work in your case.

Can you please post the `<script>` parts of rendered html page as seen by browser?

**Comment by nijel** [comment]
If it really is Rocket Loader enabled, it should be fixed by 6c86ed3f2.

**Comment by macrojames** [comment]
Rocket Loader is not enabled.
But with `Debug=False` the problem does not occur and login works.

**Comment by macrojames** [comment]
Maybe a `<script defer>` would be enough.

[w3 - script defer](https://www.w3schools.com/tags/att_script_defer.asp)

**Comment by nijel** [comment]
The scripts should be executed in order (if not marked async), so that should not make difference. Can you please post how the `<script>` tags look in your rendered page (with DEBUG=False)? Also what browser do you use?

**Comment by macrojames** [comment]
Chrome 64.0.3282.140 on Windows 10, just updated to 64.0.3282.167

```
  <script src="/js/i18n/" type="text/javascript"></script><style></style>


  <script src="/static/js/jquery.js" type="text/javascript"></script>
  <script src="/static/js/js.cookie.js" type="text/javascript"></script>
  <script src="/static/js/autosize.js" type="text/javascript"></script>
  <script src="/static/js/jquery.sortElements.js" type="text/javascript"></script>
  <script src="/static/js/jquery.multi-select.js" type="text/javascript"></script>
  <script src="/static/js/mousetrap.js" type="text/javascript"></script>
  <script src="/static/js/mousetrap-global-bind.js" type="text/javascript"></script>
  <script src="/static/js/chartist.js" type="text/javascript"></script>
  <script src="/static/js/clipboard.js" type="text/javascript"></script>
  <script src="/static/bootstrap/js/bootstrap.js" type="text/javascript"></script>
  <script src="/static/loader-bootstrap.js" type="text/javascript"></script>
  <script src="/static/bootstrap/js/bootstrap-datepicker.js" type="text/javascript"></script>
```
is that what you meant?

**Comment by nijel** [comment]
Yes, thanks. It looks correct (I was just wondering if CloudFlare doesn't do any changes there).

I think it should behave correctly, but adding defer is probably good workaround here to ensure correct execution order.

**Comment by macrojames** [comment]
Defer didn't help.
But I think I got it now and i am embarrassed. Sorry for bothering you.
The multi.js file is not contained in the python package but my loader-bootstrap.js already links to the newer version. That brought another cache layer to my attention. The cloudflare proxy already had the 2.19 version cached. After force-clearing the CDN cache the error is gone.

A solution to prevent different cached versions:
```
<script src="/static/loader-bootstrap.js?v=2.18-3" type="text/javascript"></script>
```
But that is totally your decision.

**Comment by nijel** [comment]
If would be great if you can verify that it works (I can't reproduce it even with same browser, though I didn't setup CloudFlare).

**Comment by nijel** [comment]
Well for production (DEBUG = False) this is handled by merging scripts server side. For development mode, this would probably have to rather include git revision to make sense.

Also multi.js was first present in 2.19, this file was not present in older releases (different js module was used before for this).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed by including current revision in the URLs for JavaScript and CSS files.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
