### ISSUE TITLE
Commit message with failing checks numbers

### ISSUE THREAD

**Issue by Cussa** [WeblateOrg/weblate#1865]
Hello,

I'm setting up the weblate on the company. Sometimes, some translators are saying that they finish the translation, but without verify all the strings. So, I'm using the information on commit to be easier to us. The point is that the commit can only have the information about how many strings was translated and how many need review. Is there any way to put how many has failing checks?

== EXAMPLE == 
Translated using Weblate (%(language_name)s)

Currently translated at %(translated_percent)s%% (%(translated)s of %(total)s strings)
Strings needing review: %(fuzzy_percent)s%% (%(fuzzy)s of %(total)s)
**_Strings with failing checks: %(failing_percent)s%% (%(faling)s of %(total)s)_**

Translation: %(project)s/%(component)s
Translate-URL: %(url)s

**Comment by nijel** [comment]
Currently this is not supported, but can be easily added.

**Comment by nijel** [comment]
Also thinking about this, we already have at least two rendering engines for similar things - one used in commit messages and the other one in generate addon. The latter one is more powerful (it already supports what you want) and probably should be used instead here as well...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
