### ISSUE TITLE
Post translation file via API with more parameters [$15]

### ISSUE THREAD

**Issue by Cussa** [WeblateOrg/weblate#1866]
Here on the company, we have to sometimes export and import CSV files for translations. (Some of the translators and external companies are not using weblate **yet**). So, I create my own application that export the CSV on the format that they need and import it back, based on the Weblate file.

Today the only parameter that I can inform is if I want to overwrite. Is there a possibility to put the other parameters on the post method? (Especially Author Name and Email)

**Comment by nijel** [comment]
Yes, it should be pretty easy to add.

It needs to be in the serializer to parse the request:

https://github.com/WeblateOrg/weblate/blob/61df59012040ad2a8e9b8b82b68bd6810cafee16/weblate/api/serializers.py#L342-L344

And then permission check and passing to `merge_upload` method:

https://github.com/WeblateOrg/weblate/blob/61df59012040ad2a8e9b8b82b68bd6810cafee16/weblate/api/views.py#L447-L455

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
