### ISSUE TITLE
WEBLATE_DEFAULT_FROM_EMAIL missing in Docker setup docs

### ISSUE THREAD

**Issue by Frexuz** [WeblateOrg/weblate#1868]
### Steps to reproduce
1. Copy settings from the docs to `docker-compose-https.override.yml`
2. Register accounts in Weblate

### Actual behaviour
Activation emails aren't received. But the server log says it was sent just fine.

### Expected behaviour
Warning about not being set?

.. Took a while to (google) figure out why we didn't get any emails. Found (https://github.com/WeblateOrg/weblate/issues/96)

**Comment by Frexuz** [comment]
Awesome :)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
