### ISSUE TITLE
Internal server error on https://hosted.weblate.org

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#1869]
Title says it all, errors occurs while saving a translation.

Good luck to the "monkeys" behind ;-).

Note: for instance on https://hosted.weblate.org/translate/osmand/main/fr/

**Comment by ldmpub** [comment]
Hi,

Seems to be back again.

Sorry for the annoyance.

**Comment by ldmpub** [comment]
Confirmed => issue can be closed.

**Comment by nijel** [comment]
It was temporary error on the server...
