### ISSUE TITLE
"UnicodeEncodeError: 'ascii' codec can't encode character" error using manage.py list_translators

### ISSUE THREAD

**Issue by nikosdion** [WeblateOrg/weblate#1870]
### Steps to reproduce
1. Have a translator with a Unicode character in their name, e.g. `Διονυσόπουλος` or `Cámara`, which does not translate to ASCII
2. Run `manage.py list_translators --all`

### Actual behaviour

Bombs out:

```
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/MY_PATH_TO_WEBLATE/weblate/trans/management/commands/__init__.py", line 42, in execute
    super(WeblateCommand, self).execute(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/MY_PATH_TO_WEBLATE/weblate/trans/management/commands/list_translators.py", line 55, in handle
    self.stdout.write('{1} <{0}>\n'.format(*translator))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 8: ordinal not in range(128)
```

### Expected behaviour

It should print out the list of translators in UTF-8 encoding

### Server configuration

```
 * Weblate 2.18
 * Python 2.7.12
 * Django 1.11.6
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.0
 * defusedxml 0.4.1
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.5.0
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.7.0
 * pytz 2018.3
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.11
 * Mercurial 3.7.3
 * Database backends: django.db.backends.mysql
```

The locale is correctly set to en-US.UTF-8.

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

### Proposed fix

**Disclaimer: I am not a Python developer**. I solved this on my installation by putting `from __future__ import unicode_literals` at the top of the imports. That solved the problem for me since it assumes all string literals are Unicode. I would assume that the other acceptable solution would be converting both the name and the translator tuple's values into Unicode but, frankly, it sounded like overkill to me, especially since I _expect_ that the language name, the domain of the email address and the translator's name might contain non-ASCII characters.

I'd appreciate this getting fixed. Right now it's yet another thing I have to manually patch whenever I update Weblate.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
