### ISSUE TITLE
SAP Translation Hub broken with 2.19.1

### ISSUE THREAD

**Issue by mlaggner** [WeblateOrg/weblate#1873]
see my comment in https://github.com/WeblateOrg/weblate/commit/516ddd488d2f22e4454a41457e579a4f6ff1e1f8#diff-4ed48d0180c946cbce367130efd1608e

the combination of python & SAP translation hub is rather tricky - you must also encode the url into UTF-8 -> otherwise there are problems with the python implementation of urllib

**Comment by nijel** [comment]
Fixed by following commits:

* 3bdbd0f1a Make the code compatible with Python 3
* aa64067db Add test for handling unicode strings in machine translation
* 89a7ad5e3 Bring back enconding to utf-8

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
