### ISSUE TITLE
include 'orig' language

### ISSUE THREAD

**Issue by mfrasca** [WeblateOrg/weblate#1874]
I think @nijel and I already discussed it on the mail and we dismissed it, but I now read issues that are closely related to our discussion, so I'm opening it here again.

I was suggesting introducing an 'orig' language, where we let people write strings in their own language, whatever it is, then our translated software needs to show in 'xx' ('en', 'es', 'it', 'uk', ...), it would either copy the string from 'orig' verbatim (when orig==xx, there would be no translation into xx), or use a provided translation.

You do not need this for Android projects, because their resource files are already organized this way, where 'orig' is the resource name, but if we do this for sphinx or Python projects (using collected source strings, and `po` files), then we would bring that same flexibility into these projects, too.

So, myself would write stuff into 'orig' using Italian, preferably with an 'en' translation using my cumbersome English, my Southern American contributors would also produce documentation in Spanish, writing it into 'orig' and give their English version in 'en', then the native English speaker would correct the 'en' translation, if they understand what we mean.

This would "cut the head of the bull" for issue #1822 because you always leave the door open to the software translating 'orig' into xx, whatever xx.

**Comment by nijel** [comment]
Nothing prevents you from adding custom `orig` language. I don't think you actually need any support from Weblate here. In any case the orig language will be a mess and hard to maintain because you would have no indication what language is used there for individual strings.
