### ISSUE TITLE
Bad performance with WeblateTranslation service

### ISSUE THREAD

**Issue by mlaggner** [WeblateOrg/weblate#1878]
### Steps to reproduce
1. create a weblate instance with the default dockerfile (from your docker repository)
2. fill up the weblate instance with about 100k units from several different projects
3. open up the translation mask for an untranslated unit and switch over to the machine translation tab

### Actual behaviour
you can see that the WeblateSimilar service is returning its result rather fast whereas the Weblate service needs some time (~1-2 secs at my testbed)
even worse is the runtime of the automatic translation tool (the exisiting one and the new one from my pull request too)

I could drill that down to some selects which are long running on the postresql server. 
I've traced one select:

```
SELECT "trans_unit"."id", "trans_unit"."translation_id", "trans_unit"."id_hash", "trans_unit"."content_hash", "trans_unit"."location", "trans_unit"."context", "trans_unit"."comment", "trans_unit"."flags", "trans_unit"."source", "trans_unit"."previous_source", "trans_unit"."target", "trans_unit"."state", "trans_unit"."position", "trans_unit"."has_suggestion", "trans_unit"."has_comment", "trans_unit"."has_failing_check", "trans_unit"."num_words", "trans_unit"."priority", "trans_unit"."pending" FROM "trans_unit" INNER JOIN "trans_translation" ON ("trans_unit"."translation_id" = "trans_translation"."id") INNER JOIN "trans_subproject" ON ("trans_translation"."subproject_id" = "trans_subproject"."id") WHERE ("trans_subproject"."project_id" IN (SELECT U0."id" AS Col1 FROM "trans_project" U0) AND (UPPER("trans_unit"."source"::text) = UPPER('Product Name') OR UPPER("trans_unit"."source"::text) LIKE UPPER('Product Name%')) AND "trans_translation"."language_id" = 147 AND "trans_unit"."state" >= 20 AND NOT ("trans_unit"."id" = 243443)) ORDER BY "trans_unit"."priority" ASC, "trans_unit"."position" ASC
```

and according to the postgresql server the analysis is:

```
Sort  (cost=4869.98..4870.14 rows=66 width=143) (actual time=1237.459..1237.459 rows=0 loops=1)
  Sort Key: trans_unit.priority, trans_unit."position"
  Sort Method: quicksort  Memory: 25kB
  ->  Nested Loop  (cost=5.35..4867.98 rows=66 width=143) (actual time=1237.445..1237.445 rows=0 loops=1)
        Join Filter: (trans_translation.subproject_id = trans_subproject.id)
        ->  Nested Loop  (cost=0.12..19.04 rows=1 width=4) (actual time=0.034..0.123 rows=7 loops=1)
              Join Filter: (trans_subproject.project_id = u0.id)
              Rows Removed by Join Filter: 14
              ->  Index Scan using trans_subproject_pkey on trans_subproject  (cost=0.12..8.14 rows=1 width=8) (actual time=0.019..0.038 rows=7 loops=1)
              ->  Seq Scan on trans_project u0  (cost=0.00..10.40 rows=40 width=4) (actual time=0.003..0.004 rows=3 loops=7)
        ->  Hash Join  (cost=5.22..4848.12 rows=66 width=147) (actual time=176.758..176.758 rows=0 loops=7)
              Hash Cond: (trans_unit.translation_id = trans_translation.id)
              ->  Seq Scan on trans_unit  (cost=0.00..4839.77 rows=655 width=143) (actual time=176.756..176.756 rows=0 loops=7)
                    Filter: ((state >= 20) AND (id <> 243443) AND ((upper(source) = 'PRODUCT NAME'::text) OR (upper(source) ~~ 'PRODUCT NAME%'::text)))
                    Rows Removed by Filter: 97311
              ->  Hash  (cost=5.11..5.11 rows=9 width=8) (never executed)
                    ->  Seq Scan on trans_translation  (cost=0.00..5.11 rows=9 width=8) (never executed)
                          Filter: (language_id = 147)
Planning time: 0.818 ms
Execution time: 1237.562 ms
```

you can put the data from https://pastebin.com/jxFs10Dh into http://tatiyants.com/pev/#/plans to see it visually

### Expected behaviour
the automatic translation should not take that long. I think it should be possible to tune the db access

### Server configuration
 * Weblate 2.19
 * Python 2.7.13
 * Django 1.11.10
 * six 1.10.0
 * social-auth-core 1.5.0
 * social-auth-app-django 2.0.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.7
 * user-agents 1.1.0
 * pytz 2018.3
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by mlaggner** [comment]
just to have an overview of the testbed size:

| | |
|-|-|
| Translatable strings | 11872 |
| Translatable units | 97311 |
| Translatable words | 33247 |
| Used languages | 27 |

**Comment by nijel** [comment]
It seems that PostgreSQL is performing way worse on this particular query than MySQL (which I'm currently using in production). This is probably due to different handling of case insensitive lookups.

Any suggestions how to improve the query are welcome:

https://github.com/WeblateOrg/weblate/blob/00f317f3f557748b6836a719a5fa26a07a4b3356/weblate/trans/models/unit.py#L291-L302

Alternative option might be to merge these two Weblate services. The original reasoning for split no longer applies. These were split  because the fulltext search was not reliable (what has been fixed meanwhile) and it was used to return different scoring (there is now proper scoring for the fulltext matches).

**Comment by mlaggner** [comment]
just tried to remove the exclude part of `def more_like_this` to see exact matches in the WeblateSimilar service and the results where the same as in the Weblate service.
I also tested this change with automatic translation and the performance was awesome (compared to the Weblate service).

Integrate both into the same service would need a refactor of the automatic translation tool - what do you think?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
