### ISSUE TITLE
WeblateSimilar maachine translation scoring

### ISSUE THREAD

**Issue by mlaggner** [WeblateOrg/weblate#1880]
In a training yesterday I found a little _problem_ in the WeblateSimilar machine translation scoring:

I have the source string `Yard-Management: &1` (where the &1 is a placeholder for dynamic texts) and the WeblateSimilar engine found the string `Yard-Management` (without `: &1`) with a score of 100/100 - which is too high since the two strings are not identical.

Furthermore, if we think to combine the Weblate and WeblateSimilar engines (#1878) we should achieve a better scoring here. 

Maybe this could be a reason to re-think about score calculation here? (as already discussed in #1791 or basically done in #1793)

**Comment by nijel** [comment]
Good point, the fulltext index ignores such things, and thtat's why they won't appear in scoring.

Anyway instead of implementing scoring algorithm in Weblate, I'd prefer to use something existing. For example `difflib.SequenceMatcher` can do the scoring:

```python
import difflib
difflib.SequenceMatcher(None, 'hello world', 'hello').ratio()
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
