### ISSUE TITLE
Sorting JSON files

### ISSUE THREAD

**Issue by frankenfine** [WeblateOrg/weblate#1881]
I have  python script that a team wants to use to sort a flat JSON file instead of having new translations appended to the end of the file. This is pretty common in that teams would rather the target files look like the source rather than have them looking differently. 

I can run it locally and it seems to work, but I can't seem to get it to work via Weblate on the pre-commit or post-add or post-update.

Am I doing something wrong or am I misunderstanding how these work?

**Comment by frankenfine** [comment]
I believe this is a permissions issue at this point, running it down

**Comment by frankenfine** [comment]
It was script encoding in the end. I feel like an idiot.

**Comment by nijel** [comment]
This seems like quite useful generic addition to JSON storage.

I've already submitted PR for translate-toolkit to allow this: https://github.com/translate/translate/pull/3772

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by freefri** [comment]
Hi, maybe this is not totally related with this issue, but I've seen the new option "Sort JSON keys" in the "Customize JSON output" addon which was introduced with https://github.com/WeblateOrg/weblate/commit/b39d832bf26e14ae5213a0fb6ef6551745ca0a5d

I'm not sure how this is working, with this name I was expecting that if it is not check, Weblate wont change the order of my json objects.

For example I have the object:
```
{
    "LANG_URL": "en",
    "INTRO": {
        "TITLE": "First steps",
        "PICTURES": "Choose your profile and banner pictures.",
        "PRICES": "Choose the price.",
        "TEXT": "Complete your data in order to start.",
        "BUTTON": "start creating"
    }
}
```

Which Weblate converts to:
```
{
    "LANG_URL": "en",
    "INTRO": {
        "BUTTON": "start creating",
        "PICTURES": "Choose your profile and banner pictures.",
        "TEXT": "Complete your data in order to start.",
        "TITLE": "First steps",
        "PRICES": "Choose the price."
    }
}
```

I've tested it with a 1300 lines JSON file and if I don't check the option "Sort JSON keys" only the first level order is kept but nested objects are getting randomized. In the other way, if I check the option "Sort JSON keys", all first level and nested objects are getting sorted alphabetically.

Is this a bug?

**Comment by nijel** [comment]
It's bug in the translate-toolkit, PR with proposed fix is here: https://github.com/translate/translate/pull/3817

**Comment by freefri** [comment]
Hi @nijel, thx for your job in the PR. Let us know when this fix is ready in a production ready version of weblate.

**Comment by nijel** [comment]
The PR is merged, you can already install translate-toolkit from git if you run own instance. With Hosted Weblate I wait for a release for now (see https://github.com/translate/translate/issues/3815), but I might need other fixes there in two weeks, so I might upgrade it there as well.
