### ISSUE TITLE
Unwanted size limitation for translation string (nb of madewithcc)

### ISSUE THREAD

**Issue by petterreinholdtsen** [WeblateOrg/weblate#1882]
### Steps to reproduce
1. visit https://hosted.weblate.org/translate/madewithcc/translation/nb/?type=all&offset=15
2. try to fill in complete sentence as the translated string
3. observe that there is a very short size limit in place

The string is a placeholder to add translation information to the colophon page.  For some reason the web interface reject more than a few characters.  Is there a way to get rid of this size limitation?

**Comment by nijel** [comment]
Well it's there because source string is empty, so the question is what are you actually translating there and why it's not in the source?

**Comment by petterreinholdtsen** [comment]
[Michal Čihař] <notifications@github.com> writes:
> Well it's there because source string is empty, so the question is
> what are you actually translating there and why it's not in the
> source?

The string is not empty, it contain a non-breaking space.  :)

The string is in the source to have a place to insert information about
the translation in the translated colophon page of the book.  I set
aside one paragraph for this, but am unable to insert the text I want
using weblate. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by nijel** [comment]
The default maximal length limit is ten times length of source string:

https://github.com/WeblateOrg/weblate/blob/45e404a0689c2139ce1e3cce127d6bd1bfbd26f2/weblate/trans/models/unit.py#L1132

You can override this by providing actual desired maximal length by adding `max-length:1000` tag to the string. I've just done that for this particular string.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
