### ISSUE TITLE
How to setup custom auth backend?

### ISSUE THREAD

**Issue by Skybladev2** [WeblateOrg/weblate#1883]
Can we setup custom authentication provider (backend) other than listed in [this section](https://docs.weblate.org/en/latest/admin/auth.html)?
If yes, how?

**Comment by nijel** [comment]
Just follow its instructions. Generally any Django authentication should work, just add it to `AUTHENTICATION_BACKENDS` (always keep `'weblate.accounts.auth.WeblateUserBackend'` there as well) and configure it. Similarly as with [LDAP](https://docs.weblate.org/en/latest/admin/auth.html#ldap-authentication) or [CAS](https://docs.weblate.org/en/latest/admin/auth.html#cas-authentication).

**Comment by Skybladev2** [comment]
Ok, thanks, I got it.

**Comment by nijel** [comment]
Probably it's worth documenting this...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by tm1000** [comment]
No custom auth backends work in 3.0 this because there is a custom User and Group object now.
