### ISSUE TITLE
gettext's --no-wrap format still wraps the header

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#1884]
### Steps to reproduce
1. Our source files are merged with:
```console
$ msgcat --no-wrap --add-location=file -o ${OUT_POT_FILE} ${DIR_BUILD_PO}/*.pot
$ VERSION_CONTROL=none msgmerge --no-wrap --add-location=file -U ${I18N_PO} ${POT}
```
2. Then update a translation file in https://hosted.weblate.org/projects/f-droid/website-docs
3. then merge them back into the main source repo, and there are diffs like:

```diff
 msgid ""
-msgstr "Project-Id-Version: PACKAGE VERSION\nReport-Msgid-Bugs-To: team@f-droid.org\nPOT-Creation-Date: 2018-02-23 10:04+0100\nPO-Revision-Date: 2018-03-01 16:35+0000\nLast-Tra
nslator: ezjerry liao <ezjerry@gmail.com>\nLanguage-Team: Chinese (Traditional <https://hosted.weblate.org/projects/f-droid/website-docs/zh_Hant/>\nLanguage: zh_Hant\nMIME-Vers
ion: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\nPlural-Forms: nplurals=1; plural=0;\nX-Generator: Weblate 2.20-dev\n"
+msgstr ""
+"Project-Id-Version: PACKAGE VERSION\n"
+"Report-Msgid-Bugs-To: team@f-droid.org\n"
+"POT-Creation-Date: 2018-03-01 11:22+0100\n"
+"PO-Revision-Date: 2018-03-01 16:35+0000\n"
+"Last-Translator: ezjerry liao <ezjerry@gmail.com>\n"
+"Language-Team: Chinese (Traditional) <https://hosted.weblate.org/projects/f-droid/website-docs/zh_Hant/>\n"
+"Language: zh_Hant\n"
+"MIME-Version: 1.0\n"
+"Content-Type: text/plain; charset=UTF-8\n"
+"Content-Transfer-Encoding: 8bit\n"
+"Plural-Forms: nplurals=1; plural=0;\n"
+"X-Generator: Weblate 2.20-dev\n"
```

### Actual behaviour

The _msgstr_ for the PO header is unwrapped into one line.

### Expected behaviour

The PO header should have the same format as the _gettext_ utilities produce when used with `--no-wrap`.  This seems to be one quirk with the _gettext_ unwrapped format that #365 did not include.  It looks like it should be easy to handle since the header is `msgid ""`.  Right now, this is ~95% of the merge conflicts I'm having with https://hosted.weblate.org/projects/f-droid/website-docs

**Comment by nijel** [comment]
It was designed to behave this way, so it's intentional (I have users who rely on this behavior and they specifically asked for not wrapping headers).

Why don't you just wrap everything on msgmerge and use normal Gettext support in Weblate?

**Comment by eighthave** [comment]
Switching to _po-unwrapped_ has greatly reduced the number of merge conflicts and diffs that we have between _gettext_ and _Weblate_, they have subltely different wrapping rules.  I experimented a lot and found no wrapped format that did not have regular wrapping diffs.

This current _po-unwrapped_ setup is creating a conflicting format to _gettext_'s `--no-wrap` format.  Why introduce yet another PO variant?  Seems to me that _po-unwrapped_ should aim to follow _gettext_'s `--no-wrap` since PO is basically defined by _gettext_ as far as I know. I have yet to find a _gettext_ option to make it wrap the header.

**Comment by eighthave** [comment]
Also, its related to this https://github.com/translate/translate/issues/3765

**Comment by nijel** [comment]
Yes, gettext does wrap on `\n` while this doesn't and it was intentional. The translate-toolkit can be configured to do both and Weblate probably could expose this as well, but currently it doesn't.

Actually we need better way to customize file format behavior than adding more and more formats with minor differences (see also #1881).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
Now deployed on Hosted Weblate, you can configure desired behavior in the addons configuration.
