### ISSUE TITLE
Android Studio formats XML differently than Weblate

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#1886]
### Steps to reproduce
1. use Android Studio's Ctrl-Alt-L code formatter on _strings.xml_ 
2. add translations in Weblate
3. see whitespace merge conflicts

### Actual behaviour

The whitespace formatting rules of _strings.xml_ is different between Android Studio and Weblate, leading to frequent merge conflicts due to whitespace differences.  For example:

```diff
diff --cc app/src/main/res/values-ko/strings.xml
index a38c481,f931128..0000000
--- a/app/src/main/res/values-ko/strings.xml
+++ b/app/src/main/res/values-ko/strings.xml
@@@ -477,4 -477,18 +477,22 @@@
      <string name="panic_hide_title">%s 숨기기</string>
      <string name="panic_hide_summary">앱 자체가 숨을 것입니다</string>
  
++<<<<<<< aa78049d6976f31d45e7ae589ac04ce3cdac2aaa
 +</resources>
++=======
+     <string name="sort_search">검색 정렬</string>
+ 
+     <string name="menu_liberapay">Liberapay</string>
+ 
+     <string name="panic_hide_warning_title">복원 방법을 기억하기</string>
+     <string name="panic_hide_warning_message">패닉 이벤트에서, 이 동작은 %1$s을(를) 런처에서 제거할 것입니다. \"%2$d\"을(를) 입력하는 것만이 가짜 %3$s 앱을 그것으로 복원할 수 있습니다.</string>
+ 
+     <string name="hiding_calculator">계산기</string>
+     <string name="hiding_dialog_title">이제 %s 숨기기</string>
+     <string name="hiding_dialog_message">런처에서 %1$s을(를) 제거하기를 원합니까? \"%2$d\"을(를) 입력하는 것만이 가짜 %3$s 앱을 그것으로 복원할 수 있습니다.</string>
+     <string name="hiding_dialog_warning">경고: 홈 화면의 어떠한 앱 바로 가기도 또한 제거될 것이므로 수동으로 다시 추가할 필요가 있습니다.</string>
+     <string name="hide_on_long_search_press_title">검색 버튼으로 숨기기</string>
+     <string name="hide_on_long_search_press_summary">검색 버튼을 길게 누르면 앱을 숨길 것입니다</string>
+ 
+     </resources>
++>>>>>>> Translated using Weblate (Korean)
```

### Expected behaviour

Weblate should use the same whitespace formatting rules as Android Studio.  The most basic rule:

* 4 space indents, never any tabs
* indent based on XML level (`<resources>` should never be indented, `<string>` and `<plurals>` should always be indented one level, `<item>` should be indented two levels.)
* no newline at the end of the file 
* 120 char line length limit (the least important)

Here is a before/after result of a _strings.xml_ from Weblate, then formatted by Android Studio Ctrl-Alt-L:  
[before-after.zip](https://github.com/WeblateOrg/weblate/files/1785777/before-after.zip)

### Server configuration
weblate.org hosted.

**Comment by eighthave** [comment]
I forgot one format rule: blank lines should not have any whitespace.

**Comment by eighthave** [comment]
Here's another clear example.  I just cleaned up the whitespace stuff yesterday, here's a commit from Weblate:

```diff
-------------------- app/src/main/res/values-is/strings.xml --------------------
index 83aa1aa..e7caf32 100644
@@ -582,9 +582,10 @@
     <string name="hiding_dialog_title">Fela %s núna</string>
     <string name="hiding_dialog_message">Ertu viss um að þú viljir fjarlægja %1$s úr ræsinum? Aðeins með því að skrifa \"%2$d\" í falska %3$s forritið er hægt að endurheimta það.</string>
     <string name="hiding_dialog_warning">Aðvörun: Allar flýtileiðir á forrit á heimaskjánum verða einnig fjarlægðar og verður að bæta þeim aftur inn handvirkt.</string>
     <string name="hide_on_long_search_press_title">Fela með leitarhnappi</string>
     <string name="hide_on_long_search_press_summary">Ef ýtt er lengi mun leitarhnappurinn fela forritið</string>
     <string name="sort_search">Raða leit</string>
     <string name="menu_liberapay">Liberapay</string>
 
-</resources>
+<string name="warning_scaning_qr_code">Það lítur út eins og myndavélin þín sé ekki með sjálfvirkan fókus. Það gæti orðið vandkvæðum bundið að skanna kóðann.</string>
+    </resources>
```

**Comment by nijel** [comment]
Most of the issues should be addressed by https://github.com/translate/translate/pull/3840, feedback welcome.

**Comment by nijel** [comment]
I've just merged that, still looking for feedback if it doesn't behave well in some cases.

**Comment by nijel** [comment]
Have you seen any problems with new code? It should behave way better, but I'm not sure I've fixed all cases...

**Comment by nijel** [comment]
I've gone a bit further to make the XML formatting more consistent in https://github.com/translate/translate/pull/3871, feedback welcome.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed by https://github.com/translate/translate/pull/3871.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
