### ISSUE TITLE
Contributor agreement seems to have no effect

### ISSUE THREAD

**Issue by raphaelm** [WeblateOrg/weblate#1887]
### Steps to reproduce
1. Create a component
2. Set the field "Contributor agreement" which has the description "Agreement which needs to be approved before user can translate this component."

### Actual behaviour
Nothing happens.

### Expected behaviour
I'd expect that each user needs to acknowledge this before starting to translate the component.

It looks like this has just never been implemented. We might be willing to sponsor a near-term implementation if that helps.

### Server configuration
 * Weblate 2.19.1
 * Python 2.7.13
 * Django 1.11.10
 * six 1.10.0
 * social-auth-core 1.6.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.7
 * user-agents 1.1.0
 * pytz 2018.3
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * hub 2.2.9
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
This has been never fully implemented, see https://github.com/WeblateOrg/weblate/issues/516

**Comment by raphaelm** [comment]
Ah, sorry, I didn't know for what word to search! DCO wasn't known to me as a term.
