### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by raphaelm** [WeblateOrg/weblate#1890]
### Steps to reproduce
1. Go to any weblate installation using the current stable version, e.g. https://translate.pretix.eu/
2. Click on "Documentation" in the top navigation bar

### Actual behaviour
https://docs.weblate.org/en/weblate-2.19.1/index.html opens which renders an error 404.

### Expected behaviour
* Either https://docs.weblate.org/en/weblate-2.19.1/index.html should exist, i.e. the readthedocs.org configuration should be build this tag as well
* Or the link should go to https://docs.weblate.org/en/weblate-2.19/index.html which exists

### Server configuration
 * Weblate 2.19.1
 * Python 2.7.13
 * Django 1.11.10
 * six 1.10.0
 * social-auth-core 1.6.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.7
 * user-agents 1.1.0
 * pytz 2018.3
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * hub 2.2.9
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Oops, forgot to build it. I've just triggered the build, should be online soon.
