### ISSUE TITLE
Android - Weblate exports empty string after start new translation

### ISSUE THREAD

**Issue by Khang-NT** [WeblateOrg/weblate#1893]
### Steps to reproduce
1. Go to: http://translate.ymusicapp.com/projects/media-converter/strings/
2. Start new translation
3. Select language -> start new translation

### Actual behaviour
Weblate push new file to Github, contains all keys with empty strings.
https://github.com/Khang-NT/Android-Media-Converter/commit/4cdf436be3015362893801ddd6c2f54185102284

### Expected behaviour
It should create empty resource file.
```xml
<?xml version='1.0' encoding='UTF-8'?>
<resources>

</resources>
```

### Server configuration
```
* Weblate 2.19.1
 * Python 2.7.13
 * Django 1.11.10
 * six 1.10.0
 * social-auth-core 1.6.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.7
 * user-agents 1.1.0
 * pytz 2018.3
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * hub 2.2.9
 * Database backends: django.db.backends.postgresql_psycopg2
```

**Comment by Khang-NT** [comment]
In component setting, I set `Base file for new translations:` to empty, then it works as I expected.

**Comment by StefanBrand** [comment]
Would that be the `Template for new translations` in Weblate 4.5.2?

**Comment by nijel** [comment]
Yes, this behavior is documented here: https://docs.weblate.org/en/latest/admin/projects.html#template-for-new-translations
