### ISSUE TITLE
Machine Translation for main language

### ISSUE THREAD

**Issue by derN3rd** [WeblateOrg/weblate#1894]
If you use "Machine Translation" it always translates the "Source". But in our case we do use nested JSON and it looks like "user.login.username" and the translation does not try to translate the English string but the "user.login.username".

In our case we have English as source languages. Is there a way to always translate the English string to the needed language?

Thanks in advance

**Comment by nijel** [comment]
You should configure the translation as monolingual in this case, see https://docs.weblate.org/en/latest/admin/projects.html#monolingual-components

**Comment by derN3rd** [comment]
Ah thanks! Didn't see this option. Works like is should!
