### ISSUE TITLE
Weblate doesn't see translations after a repository reset

### ISSUE THREAD

**Issue by Changaco** [WeblateOrg/weblate#1895]
### Steps to reproduce

1. Fetch Git commits from Weblate and modify them locally
2. Reset the Weblate repository (click the "Reset" button in the "Repository tools" box)
3. Push the modified commits (to GitHub, which sends a notification to Weblate)

### Actual behaviour

Some translations are empty in the Weblate UI even though they exist in the translation files, e.g. https://hosted.weblate.org/languages/ms/liberapay/ shows 0% translated.

### Expected behaviour

All translations that exist in the `.po` files should appear in Weblate, e.g. https://hosted.weblate.org/languages/ms/liberapay/ should show 69% translated.

### Server configuration

Hosted Weblate

**Comment by Changaco** [comment]
Extra note: the Weblate repository is in sync with GitHub, their `HEAD` is the same, so the problem doesn't come from a missed webhook or another similar issue.

**Comment by nijel** [comment]
I've forced rescan of the files now, so the problem will disappear. However the question is how that happened...

To me it seems that you've hit the window I've restarted the server, but still it should either update the translations or not store the updated hash of the file and process the changes later.

**Comment by iGormilhit** [comment]
> To me it seems that you've hit the window I've restarted the server

@nijel Are maintenance annonced on status.weblate.org? I'm asking because [we][1] spottet two times issues that looked like this one, so I'm looking for a way to avoid manipulating our translation branch in peculiar moments. :slightly_smiling_face: 

[1]: https://hosted.weblate.org/projects/rero_plus/

**Comment by nijel** [comment]
You should not notice regular maintenance. Sometimes things go wrong, ant there is obviously no announcement before such events. Please share more details about what happened to you in a separate issues so that we can take a look.
