### ISSUE TITLE
lg is Luganda, not Ganda

### ISSUE THREAD

**Issue by dachary** [WeblateOrg/weblate#1896]
### Steps to reproduce
1.login as an admin
2.go to /new-lang/securedrop/securedrop/
3.look for Ganda

### Actual behaviour
* Ganda (lg)

### Expected behaviour
* Luganda (lg)

See https://en.wikipedia.org/wiki/Luganda for more information

### Server configuration

<pre>
$ sudo docker-compose run --rm weblate list_versions
WARNING: Found orphan containers (weblate_https-portal_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting weblate_cache_1 ... 
Starting weblate_database_1 ... done
Postgres is up
</pre>

 * Weblate 2.17.1
 * Python 2.7.13
 * Django 1.11.6
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.7.0
 * pytz 2017.2
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
The name is coming from the [CLDR standard](http://www.unicode.org/cldr/charts/29/supplemental/language_plural_rules.html#lg) and [ISO language name](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes) is Ganda as well. However if some native speaker can confirm Luganda is better here, it can be certainly changed.

**Comment by nijel** [comment]
After a bit more research, Luganda indeed seems as more suited for language name, so I've changed that.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
