### ISSUE TITLE
allow for localized screenshot [$100]

### ISSUE THREAD

**Issue by ghost** [WeblateOrg/weblate#1899]
It would be convenient to display a localized screenshot next to the screenshot associated to a string. A script could then:

* watch the repository in which the translations are pushed by Weblate
* create a screenshot of the updated translated string
* upload the screenshot to the corresponding Weblate translation context using the API

It would be specially useful to the reviewer in charge of clicking **Approve** on each translation, to verify they look good.

For instance, in the case of SecureDrop, the script would re-use the existing integration tests which [produce screenshots for documentation updates](https://docs.securedrop.org/en/latest/development/documentation_guidelines.html#updating-screenshots).

**Comment by dachary** [comment]
@nijel I see you added the **undecided** tag and I'm willing to help clarify whatever uncertainty is left. What concern should be investigated first? Is it a matter of usability? Or maybe there is the question of figuring out if localizers really want that kind of feature?

**Comment by comradekingu** [comment]
It would be interesting to have this in review-mode.

**Comment by dachary** [comment]
For the record, a $25 was added to the bounty today by [the SecureDrop Community fund](https://forum.securedrop.club/t/expense-proposal-allow-for-localized-screenshot-25/582).

**Comment by comradekingu** [comment]
@dachary I was able to upload a screenshot for a project i administrate on Weblate 3.0-dev
https://hosted.weblate.org/screenshot/132/

Go to a component, for example /Trebleshot/strings
Administrate ↓
                    Administrate screenshots

Looks like it is possible to add it to strings.

**Comment by dachary** [comment]
@comradekingu can you have a screenshot for the translated string, or just the source string?

**Comment by comradekingu** [comment]
@dachary Source strings only.
