### ISSUE TITLE
Strings removed from source are not removed from translation

### ISSUE THREAD

**Issue by Cussa** [WeblateOrg/weblate#1901]
### Steps to reproduce
1. Create a project working with a csv file for translation
2. Source (english, for example) has 60 strings
3. Create a new translation (czech, for example). The file will have 60 strings
4. Go on the source code of the project and remove 40 strings from the source.
5. The source file contains now only 20 strings.

### Actual behaviour
6. The UI shows only 20 strings for translate, but the file still keeps the 60 strings.

### Expected behaviour
6. The UI show only 20 strings for translate and remove the 40 strings that were removed from source.

### Server configuration
 * Weblate weblate-2.19.1
 * Python 2.7.12
 * Django 1.11.6
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.0
 * defusedxml 0.4.1
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.5.0
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.1
 * user-agents 1.1.0
 * pytz 2014.10
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.11
 * Mercurial 3.7.3
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
The automated cleanup is not there by default to avoid removing things by mistake. If you still want cleanup to happen automatically, you can use [cleanup addon](https://docs.weblate.org/en/latest/admin/addons.html#cleanup-translation-files) to achieve this.
