### ISSUE TITLE
Shortcut for "Toggles edit needed flag." uses unviable shortcut CTRL+T

### ISSUE THREAD

**Issue by Braintelligence** [WeblateOrg/weblate#1904]
### Steps to reproduce
1. Use CTRL+T for toggling "edit needed flag" in weblate as described here: https://docs.weblate.org/en/latest/user/translating.html#keyboard-shortcuts
2. Realize that you open a new tab and otherwise nothing happens
3.

### Actual behaviour
You open a new tab

### Expected behaviour
You toggle the "edit needed flag"

### Server configuration
Latest docker version.

EDIT: Firefox, Chrome, Edge and Internet Explorer (and possible other browsers) all use CTRL+T for "open new tab". I don't understand how "Changed in version 2.18: The keyboard shortcuts have been changed in 2.18 to less likely collide with browser or system ones." led to CTRL+T as a viable shortcut.

**Comment by nijel** [comment]
Apparently we need something better here...

**Comment by nijel** [comment]
Any suggestions for good shortcut?

**Comment by Braintelligence** [comment]
From the top of my head: Is CTRL+Q used anywhere?

**Comment by nijel** [comment]
Quit Firefox? Doesn't sound like a good option...

**Comment by Braintelligence** [comment]
I use Firefox on a German Windows 10 Pro. CTRL+Q doesn't do anything for me. Is it language-specific?

**Comment by Braintelligence** [comment]
The German Firefox documentation says CTRL+SHIFT+Q is close Firefox...

**Comment by Braintelligence** [comment]
Same for the English docs:
![grafik](https://user-images.githubusercontent.com/6761196/37477716-acb94de4-2878-11e8-92a5-52741c9210f6.png)

**Comment by nijel** [comment]
On Linux the default is Ctrl+Q.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by Braintelligence** [comment]
@nijel Thanks for fixing this. Is it possible to donate via crypto and get a receipt for the donation?

**Comment by nijel** [comment]
Sorry, I currently can't issue receipts for crypto donations.
