### ISSUE TITLE
Site name changes back to * after docker instance restart

### ISSUE THREAD

**Issue by mlaggner** [WeblateOrg/weblate#1905]
### Steps to reproduce
1. Go to the admin area and change the site 1 (default) to something else than * (weblate.mydomain.com e.g.)
2. restart the docker instance containing weblate
3. the domain name of site 1 changed back to *

### Expected behaviour
the site name should stay at the set value

### Server configuration
 * Weblate 2.20-dev
 * Python 2.7.13
 * Django 1.11.11
 * six 1.10.0
 * social-auth-core 1.5.0
 * social-auth-app-django 2.0.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.7
 * user-agents 1.1.0
 * pytz 2018.3
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2

this affects (at least) version 2.19 and 2.20

**Comment by nijel** [comment]
What is your setting for WEBLATE_ALLOWED_HOSTS?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by mlaggner** [comment]
thanks, is working now as expected
