### ISSUE TITLE
'on_delete' field is required when defining relationships in Django >=2.0

### ISSUE THREAD

**Issue by waitxd** [WeblateOrg/weblate#1913]
I'm getting the following error when I'm trying to migrate with ```./manage.py migrate --noinput```:
`  File "<...>/weblate/weblate/memory/models.py", line 96, in Memory
    related_name='memory_source',
TypeError: __init__() missing 1 required positional argument: 'on_delete'
`

https://github.com/WeblateOrg/weblate/blob/cb2baf8638b47774a7153d490c90deccee64ebb5/weblate/memory/models.py#L94-L101

According to: https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.ForeignKey

> Requires two positional arguments: the class to which the model is related and the on_delete option. (on_delete isn’t actually required, but not providing it gives a deprecation warning. It will be required in Django 2.0.)

Consider using ```on_delete=models.DO_NOTHING```

Truncated ```./manage.py list_versions``` output:
 * Weblate weblate-2.19.1-230-gcb2baf863
 * Python 3.6.4
 * Django 2.0.1

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
