### ISSUE TITLE
Progress lost after change in remote GIT repository

### ISSUE THREAD

**Issue by flokixplore** [WeblateOrg/weblate#1914]
### Steps to reproduce
1. Setup project with component and connect with GIT repository (Bitbucket)
2. Set File mask: translations/app.*.xlf
Monolingual base language file: translations/app.cs.xlf
Base file for new translations: translations/app.cs.xlf
Edit base file; yes
3. Change files in git repository and pull in Weblate

### Actual behaviour
When I edit app.cs.xlf or app.de.xlf in remote GIT repository, than I pull it in Weblate (or automatically by hook) than all progress is suddenly zero for all files edited on remote git repository.

### Expected behaviour
Progress should persist after modifications in remote repository.

### Version
Weblate 2.19.1

Here are files that I use for monolingual translations (from translation key with source language cs)

app.cs.xlf
```
<?xml
 version='1.0' encoding='UTF-8'?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
    <file source-language="cs" datatype="plaintext" original="app" target-language="cs">
        <body> 
            <trans-unit id="howDoesItWork" approved="yes"> 
                <source>howDoesItWork</source>
                <target state="translated">Jak to funguje?</target>
            </trans-unit> 
            <trans-unit id="pages.home.title" approved="yes"> 
                <source>pages.home.title</source>
                <target state="translated">Domů</target> 
            </trans-unit> 
            <trans-unit id="pages.merchandising.title" approved="yes"> 
                <source>pages.merchandising.title</source>
                <target state="translated">Merchandising</target> 
            </trans-unit> 
            <trans-unit id="pages.aboutUs.title" approved="yes">
                <source>pages.aboutUs.title</source>
                <target state="translated">O nás</target> 
            </trans-unit> 
        </body>
    </file>
</xliff>
```

app.de.xlf
```
<?xml version="1.0" encoding="utf-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
    <file source-language="de" datatype="plaintext" original="app" target-language="de">
        <body> 
            <trans-unit id="howDoesItWork" approved="yes"> 
                <source>howDoesItWork</source>
                <target state="translated">Wie funktioniert es?</target>
            </trans-unit> 
            <trans-unit id="pages.home.title" approved="yes"> 
                <source>pages.home.title</source>
                <target state="translated">Einführung</target>
            </trans-unit> 
            <trans-unit id="pages.merchandising.title" approved="yes"> 
                <source>pages.merchandising.title</source>
                <target state="translated">Merchandising</target>
            </trans-unit>
            <trans-unit id="pages.aboutUs.title" approved="yes">
                <source>pages.aboutUs.title</source>
                <target state="translated">Über uns</target>
            </trans-unit>
        </body>
    </file>
</xliff>
```

Thank you very much for your help.

**Comment by nijel** [comment]
I have few questions to clarify what is going on:

* How do you trigger update of git repository in Weblate?
* If you hit commit in the repository management page in Weblate, are changes written to the file?

**Comment by miloshavlicek** [comment]
@nijel:
- I manually click to commit in Weblate to push changes and in Bitbucket I have hook to pull to Weblate: https://weblate.udanax.cz/hooks/bitbucket/ It works ok in both ways, changes are written to the file and appears in repository.

**Comment by nijel** [comment]
That should work, it's also covered by our tests, but there might be some slight difference in xliff files breaking this (the translate-toolkit is quite picky in some cases). I'll try to test files you've posted above (though I can't give you timeline for that).
