### ISSUE TITLE
Can Glossary support words with space?

### ISSUE THREAD

**Issue by wastee** [WeblateOrg/weblate#1918]
### Steps to reproduce
1. Write a word list in csv file without header. 
    A column is words. 
    B column is the meaning of A column value.
2. Upload csv file in Glossary page. (Overwrite mode)

### Actual behaviour
Some value like "special words" in column A miss in Glossary page after uploaded.
But when i download csv in Glossary page. 
I can see this value still in csv, but it will be splitted into 2 parts by space.
A column value is "special". B column value is "words".

### Expected behaviour
I want word like "special words" keeps it's value after upload and shows in Glossary page.
```
# Before upload
special words,
# After download
special,words
# What i want
special words,
```

### Server configuration
 * Weblate 2.19.1
 * Python 2.7.13
 * Django 1.11.11
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.7.7
 * user-agents 1.1.0
 * pytz 2018.3
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * hub 2.2.9
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Can you please post here the file you're uploading?

**Comment by wastee** [comment]
Thanks for your reply.
This issue was happend when other administrators of the project add new csvs.
I download these words, and list systematically. Then empty all words in glossary.
I re-upload csv. And problem solved, everything seems be find.

~~I am not quite sure why this happened. I guess there is a possibility that the format used by other administrators who uploaded csv is inconsistent with what I use?~~

After I contacted him, I knew that the sep of csv file he used is space, not a comma. I think this is the reason cause the problem.

I will check my issue more carefully next time.
Thanks for your time!
