### ISSUE TITLE
Caching machine translation [$15]

### ISSUE THREAD

**Issue by mipapo** [WeblateOrg/weblate#1923]
I couldn't find an answer for this questions: 
I've enabled some machine translation sources, but does weblate cache them or request that translation everytime a user hits the "machine translation" tab? 

(I'm asking because you've added deepl as a machine translation source and as they charge for the service it would be great to save the already requested translations) 
(Thanks for deepl integration - donation incoming ;) )

https://www.bountysource.com/issues/56311421-caching-machine-translation

**Comment by nijel** [comment]
There is currently no caching, but it's probably good idea to implement it.

**Comment by mipapo** [comment]
Added a 15$ bounty: https://www.bountysource.com/issues/56311421-caching-machine-translation

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
