### ISSUE TITLE
Download more translations in zip [$57]

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1924]
It should be possible to download more translations in a zip file. 

At least following makes sense:

- all in one component list
- all in the project
- all in language for project

Ideally it would be accompanied with upload which would accept zip in same structure.

**Comment by LemonAndroid** [comment]
Hey,

Is someone already working on this issue?

**Comment by nijel** [comment]
AFAIK nobody is working here so far.

**Comment by LemonAndroid** [comment]
Hey, I will start work on this now.

**Comment by nijel** [comment]
It will be new feature. So far export is only for one file, so zipping it was not really necessary.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
