### ISSUE TITLE
Translation memory scoring

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1925]
Currently we use Levenstein based scoring in translation memory (and Weblate machine translation service). It performs way better than difflib which we've used before, but it seems to be too optimistic in some cases. This seems to be the case also in the following tests: https://stackoverflow.com/a/31236578/225718

Maybe we should look for some better approach for scoring. To have some test data, I'd like to collect strings where the current scoring works bad so that we can actually measure the differences between the scoring methods.

Libraries which we might consider:

- [fuzzywuzzy](https://github.com/seatgeek/fuzzywuzzy)
- [jellyfish](https://github.com/jamesturk/jellyfish)
- [distance](https://github.com/doukremt/distance)
- [difflib](https://docs.python.org/3/library/difflib.html)

**Comment by mlaggner** [comment]
I could offer you to do some research in java. I know there is the lib https://github.com/tdebatty/java-string-similarity which offers some different algorithms just for a comparison of the results..
Do you have a pool of texts to compare?

**Comment by nijel** [comment]
I don't really have a good test data, I was only testing on some random strings in my projects. One of the outcome of this issue should be to have reasonable test data set showing some usual strings which would show both close matches or non matches.

**Comment by nijel** [comment]
Just for the reference the current scoring implementation:

https://github.com/WeblateOrg/weblate/blob/a065f372a3e1160aba1621803c0bd660f86c3b6b/weblate/utils/search.py#L23-L34

It can be replaced by anything else, it just needs to provide the `Comparer` class with `similarity` method accepting two string parameters.

**Comment by pleonex** [comment]
I would like to recommend [Damerau-Levensthein](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance). It's an improvement to the regular Levensthein to check also the transposition of characters. This is the algorithm that some CAT tools like [Trados](https://community.sdl.com/product-groups/translationproductivity/w/customer-experience/3190.post-edit-compare) uses so I think it's a good fit.

**Comment by nijel** [comment]
Good point, sticking with what other CAT tools use is good idea.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
