### ISSUE TITLE
Add support for Fluent (l20n)

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1926]
Having l20n support could be useful. The problem is that this file format is quite complex and really doesn't fit into what translate-toolkit and Weblate expects from it. This is quite deeply covered in the translate-toolkit documentation: http://docs.translatehouse.org/projects/translate-toolkit/en/latest/formats/l20n.html

There is some preliminary implementation in translate-toolkit, but I think it's far from being used on real translations. See also https://github.com/translate/translate/issues/3389

**Comment by nijel** [comment]
...and now there is Fluent as well, see https://www.yetanothertechblog.com/2018/04/05/why-fluent-matters-for-localization/

**Comment by silwol** [comment]
Probably also interesting in this regard: https://github.com/projectfluent/fluent/wiki/Fluent-and-L20n

**Comment by nijel** [comment]
It's just separated file format syntax from the library, making it easier to use the file format elsewhere than in L20n.js. But there is now https://github.com/projectfluent/python-fluent, which might be used to get support for this.

**Comment by eighthave** [comment]
I'm just reading up about this, they announced 1.0:
https://hacks.mozilla.org/2019/04/fluent-1-0-a-localization-system-for-natural-sounding-translations/

This will fall under the Linguine funding effort, since Mozilla is moving Firefox to only Fluent strings.

**Comment by Jibec** [comment]
Le 2019-06-19 10:39, Hans-Christoph Steiner a écrit :
> This will fall under the Linguine funding effort, since Mozilla is
> moving Firefox to only Fluent strings.

What is the Linguine funding effort?

**Comment by eighthave** [comment]
Linguine is the project name for working on translations for group of related project, including Tor Project, Tails, Guardian Project, F-Droid, etc.

**Comment by Erudition** [comment]
There is still nothing as advanced and natural sounding as Fluent - I can't use Weblate until it's supported!

**Comment by Doldge** [comment]
Hi,

Is someone able to outline the steps required to get Fluent support into Weblate? (I'm currently stuck using Pontoon but it's absolutely hopeless). Both Pontoon and Weblate are django apps though, so I'm hopeful that if someone is able to outline the requirements I may be able to assist with implementing them based on how Pontoon handles it.

It sounds like the current requirements are:
- get prism.js syntax highlighting?
- something about changing / improving the editor? (might already be done?)
- add file format handling?
- good to go?

Thanks.

**Comment by Jibec** [comment]
as far as i know, Weblate extensively use the translate toolkit to interact with translation files.

first step would be to add support into this library https://github.com/translate/translate

Then adding features in Weblate UI for Fluent specifics may then be possible. But for this, Michal guidance is required.
--
Jean-Baptiste

**Comment by nijel** [comment]
Having support in translate-toolkit is preferred approach and will make integration in Weblate easy.

1. Implement https://github.com/translate/translate/issues/3389
2. Add integration in Weblate, this is typically just defining a wrapper class
3. (optional) Syntax highlighting for Fluent
4. (optional) Check for Fluent syntax
