### ISSUE TITLE
Visual aide of  doublespace in edited string

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#1930]
Above the blue line.
![spacecreated](https://user-images.githubusercontent.com/13802408/37826323-32ddf878-2e93-11e8-8bc9-eb4786d0354b.png)
If you make a triplespace, there are three dots.
Regular spaces have no dots.
Makes it visually apparent that there is a doublespace afoot.

**Comment by nijel** [comment]
This can be easily done in the the strings we display, there is no support for this in the editor as we use just simple textarea so far...

**Comment by nijel** [comment]
I've just implemented it for rendering strings, for the editor it's still open until we use something more complex for entering text.

**Comment by nijel** [comment]
From #3417 by @iriman: 

**Is your feature request related to a problem? Please describe.**
Some characters are invisible and could have unwanted effects on the final translation. like directional characters such as LRE, RLE, etc.

**Describe the solution you'd like**
Making them visible, e.g. by name: `<LRE>`, `<RLE>`, etc.

**Additional context**
I'm specially speacking about these highlighted characters that sometimes need to be inserted in translations:
![image](https://user-images.githubusercontent.com/8467903/73009428-d1099680-3e25-11ea-973e-e067dd63c09e.png)

**Comment by yarons** [comment]
Well if I understand correctly in Pootle it's done via Webfonts and ignoring the directionality charaters altogether leading to a left aligned and reversed text with some black symbols that represent the directionality characters which are non existent characters with a symbol representation of the matching function.

This is how it looks like:
(The editor with the interpreted string)
<img width="754" alt="Screen Shot 2020-02-08 at 13 59 13" src="https://user-images.githubusercontent.com/406826/74084824-9174b880-4a7b-11ea-8c0a-4a0aceef5ad7.png">

(The "raw" version of the same string)
<img width="753" alt="Screen Shot 2020-02-08 at 14 00 04" src="https://user-images.githubusercontent.com/406826/74084834-a6514c00-4a7b-11ea-9978-aec13a92b3ce.png">

**Comment by nijel** [comment]
My intention is rather to go for some rich editor (for example CodeMirror) and highlight whitespace and special chars there. But frontend is not really my cup of tea....

**Comment by yarons** [comment]
Well, there's this project by a friend of mine (@tomer) called Pilcrow:
https://tomer.github.io/pilcrow/
This is the source code:
https://github.com/tomer/pilcrow

It could probably be fitted for our needs pretty easily.

**Comment by nijel** [comment]
What we need in textarea formatting, while this seems to format non-editable text. Anyway we're now using CodeMirror for some other features, so this should be possible using it as well, it just needs to be implemented ;-).
