### ISSUE TITLE
Align Source and translation string markers in emails

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#1932]
How it is on long strings:
![stringviewmail](https://user-images.githubusercontent.com/13802408/37827152-a53aaa44-2e96-11e8-92d4-e17698aaefce.png)

Ideal:
![stringviewmailideal](https://user-images.githubusercontent.com/13802408/37827167-ae7de562-2e96-11e8-8d3f-daf620e12388.png)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
