### ISSUE TITLE
Untranslated ASCII sign from Google Translation API

### ISSUE THREAD

**Issue by miloshavlicek** [WeblateOrg/weblate#1933]
### Steps to reproduce
1. Enable Google Translate API
2. Enter source string (cs): Statistiky je možné rovněž zobrazit po přihlášení k účtu pořadatele akce
3. See it in machine translation

### Actual behaviour
Result is: `Statistics can also be viewed after logging in to the organizer&#39;s account`
The same issue is with sign `"` resulting in `&quot;` etc.

### Expected behaviour
Result should be: `Statistics can also be viewed after logging in to the organizer's account`

I tried to manually enter the string to Google Translate and it is ok, so problem it is probably a bug in encoding. &#39; is equal to apostrof, but char should be represented by '

**Comment by nijel** [comment]
Thanks for spotting, apparently Weblate is not the only place where this is messed up: https://stackoverflow.com/a/26946392/225718

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
