### ISSUE TITLE
List of projects on root page and link in menu

### ISSUE THREAD

**Issue by miloshavlicek** [WeblateOrg/weblate#1934]
It would be more user friendly to:
- see list of all projects on homepage (root page) - in way as on page: domain.tld/projects/.
- have link "Projects" in top menu, because it is hard to users to find how they can go to Project list - the maybe easist way for user (workaround) at this time is to manually chage URL to /projects/

**Comment by nijel** [comment]
We certainly need more dashboard views and listing projects is definitely on of the missing ones. Current dashboard is focused on translators which have chosen their language to show them their translations, but doesn't work well for many other use cases.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
