### ISSUE TITLE
Cleaner theme

### ISSUE THREAD

**Issue by miloshavlicek** [WeblateOrg/weblate#1935]
It would be sexy to use some lighter and cleaner Bootswatch theme e.g.:
- https://bootswatch.com/flatly/ (I prefer)
- https://bootswatch.com/litera/
or some another (in top menu choose Themes and choose one)

It is very easy to implement.

**Comment by nijel** [comment]
These are for Bootstrap 4, while Weblate is still using 3, so it's not just switching theme. Switching to Bootstrap 4 should not be hard though and pull requests are welcome :-).

Out of these , I prefer Flatly.

**Comment by miloshavlicek** [comment]
@nijel Bootstrap 3 version is here: https://bootswatch.com/3/flatly/

**Comment by nijel** [comment]
Great, still we should switch to Bootstrap 4 anyway :-).

**Comment by comradekingu** [comment]
Sounds like going bootstrap 4 ducks problems concerning new bootstrap 3 theming.
Flatly looks great.

**Comment by nijel** [comment]
The problem with Bootstrap 4 seems to be (again) lack of support for RTL languages. There seem to be some third party mods, but it seems to be even bigger mess than with Bootstrap 3...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
