### ISSUE TITLE
Private repository for publicly accessable translation site.

### ISSUE THREAD

**Issue by flokixplore** [WeblateOrg/weblate#1936]
### Steps to reproduce
1. Create a public project with component
2. Access GIT repository via URL - see: https://docs.weblate.org/en/weblate-2.19.1/faq.html#how-to-fix-merge-conflicts-in-translations

### Actual behaviour
If a project is public than repository is publicly accessable via URL and GIT client without credentials on: https://hosted.weblate.org/git/weblate/website/

### Expected behaviour
There should be option to set whether the repository is publicly accessable or not to be able to set private repo for public Weblate project.

**Comment by nijel** [comment]
This depends on project setup and on user permissions. User needs *Can access VCS repository* permission on given project. The default setup is that all users in *Users* group (which is where all users are automatically assigned) and *Guests* (this is for unauthenticated user) have this permission. Therefore anybody can access VCS on public projects.  For private or protected projects only members of VCS group or admins can access VCS.

All this can be tweaked by users or group permissions and by group ACL to restrict the access. You might rather choose Custom access control in case you will be changing those as Weblate might revert some of your changes on the groups/group ACLs it uses. 

Still if you want your VCS to be private, choosing private or protected access for project might be better choice.

**Comment by miloshavlicek** [comment]
Thank you for explanation. I have revoked VCS permissions for Guest and Users and it seems ok.
