### ISSUE TITLE
Caching with Debug=False does not work

### ISSUE THREAD

**Issue by derN3rd** [WeblateOrg/weblate#1937]
### Steps to reproduce
1. Turn off Debug
2. Load a weblate page
3. /static/CACHE/js/*.js is not generated and therefore can't be found by nginx

### Actual behaviour
If I disable Debug mode, the server starts caching. This does not work properly. the css files are generated, but the js files not.
So I get a 404 on `https://myweblatedomain/static/CACHE/js/f5eca4a0bf75.js`

### Expected behaviour
The cache files should be generated and accessible.

### Server configuration
I am using weblate in a virtualenv installed to /home/ubuntu/weblateenv, nginx with uwsgi
weblate list_versions output:
```
 * Weblate 2.19.1
 * Python 2.7.12
 * Django 1.11.11
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.7.1
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.7.7
 * user-agents 1.1.0
 * pytz 2018.3
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Database backends: django.db.backends.mysql
```
nginx.conf:
```
server {
    listen 80;
    server_name **removed**;
    root /home/ubuntu/weblatenv/lib/python2.7/site-packages/weblate;

    location ~ ^/favicon.ico$ {
        # DATA_DIR/static/favicon.ico
        alias /home/ubuntu/data/static/favicon.ico;
        expires 30d;
    }

    location ~ ^/robots.txt$ {
        # DATA_DIR/static/robots.txt
        alias /home/ubuntu/data/static/robots.txt;
        expires 30d;
    }

    location /static/ {
        # DATA_DIR/static/
        alias /home/ubuntu/data/static/;
        expires 30d;
    }

    location /media/ {
        # DATA_DIR/media/
        alias /home/ubuntu/data/media/;
        expires 30d;
    }

    location / {
        include uwsgi_params;
        # Needed for long running operations in admin interface
        uwsgi_read_timeout 3600;
        # Adjust based to uwsgi configuration:
        uwsgi_pass unix:///run/uwsgi/app/weblate/socket;
        # uwsgi_pass 127.0.0.1:8080;
    }
}
```

uwsgi.ini:
```
[uwsgi]
plugins       = python
master        = true
protocol      = uwsgi
socket        = 127.0.0.1:8080
wsgi-file     = /home/ubuntu/weblateenv/lib/python2.7/site-packages/weblate/wsgi.py
python-path   = /home/ubuntu/weblateenv/lib/python2.7/site-packages/weblate
# In case you're using virtualenv uncomment this:
virtualenv = /home/ubuntu/weblateenv
# Needed for OAuth/OpenID
buffer-size   = 8192
# Increase number of workers for heavily loaded sites
#workers       = 6
# Needed for background processing
enable-threads = true
# Child processes do not need file descriptors
close-on-exec = true
# Avoid default 0000 umask
umask = 0022
```

**Comment by nijel** [comment]
Most likely the cache directory is not writable by the server running the uwsgi. With debug disabled, it doesn't have to write there as the compressed files are not used in this case...

**Comment by derN3rd** [comment]
I already tried setting the whole data/static/CACHE folder to 0777, but it results in the same error.
I can't see an error in the logs.

I got another error which sounds like a problem with permissions too.
```
IOError: [Errno 13] Permission denied: '/home/ubuntu/data/avatar-cache/5b2396248f487761de1557062f7f3623.djcache'
```

I did the installation like it should be. Am I missing something?

**Comment by derN3rd** [comment]
I think I got it to work now.

I changed to ownership of the data folder to www-data with `sudo chown www-data:www-data -R ~/data` and restarted the uwsgi application. Now it works like it should.

**Comment by erciccione** [comment]
Was this actually fixed or it's necessary to use the workaround pointed out by @derN3rd?

I'm having the same issue with weblate 1.8

**Comment by nijel** [comment]
The directory needs to be writable, see https://docs.weblate.org/en/latest/admin/config.html#data-dir
