### ISSUE TITLE
Changed language code

### ISSUE THREAD

**Issue by janbednar** [WeblateOrg/weblate#1938]
### Steps to reproduce
1. Open project and component
2. Click start new translation
3. Select for example Chinese (Traditional)

### Actual behaviour
Chinese (Traditional) language is created in subfolder named `zh_Hant`

### Expected behaviour
Previously, language code was `zh-Hant`

This is the same for all other language codes.

### Server configuration
* Weblate weblate-2.19.1
 * Python 2.7.5
 * Django 1.11.5
 * six 1.11.0
 * social-auth-core 1.6.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.2
 * defusedxml 0.5.0
 * Git 1.8.3.1
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.2.1
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.7.7
 * user-agents 1.1.0
 * pytz 2017.2
 * pyuca N/A
 * PyYAML 3.12
 * Database backends: django.db.backends.mysql

**Comment by Pitel** [comment]
This worked in WebLate 2.18, and it breaks iOS XCode projects.

**Comment by nijel** [comment]
Are you sure it was really ever created as `zh-Hant`? The language code in the database was always `zh_Hant` and there is no language codes transformation for anything else than Android.

Weblate will load both variants, but for creating it sticks to what is stored in the database.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
