### ISSUE TITLE
List of machine translations shows HTTP Error 404 when using tmserver

### ISSUE THREAD

**Issue by drebs** [WeblateOrg/weblate#1940]
### Steps to reproduce
1. Setup a local tmserver using [translate-toolkit](https://pypi.python.org/pypi/translate-toolkit/2.3.0) 2.3.0 (i.e. `tmserver -d /path/to/some/db.tmdb -p 8080`).
2. Install Weblate 2.19.1, and configure:
   1. `MT_TMSERVER` to point to the local tmserver (i.e. `'http://127.0.0.1:8080/tmserver/'`).
   2. Add `'weblate.trans.machine.tmserver.TMServerTranslation'` to `MACHINE_TRANSLATION_SERVICES`
3. Import some components into Weblate.
4. Log in into Weblate.
5. Go to a component translation page.
6. Click "Machine Translation" (maybe it's already selected).

### Actual behaviour

The list of machine translations shows:

```
The request for machine translation using tmserver has failed: HTTPError: HTTP Error 404: Not Found
```

### Expected behaviour

It should show a (possibly empty) list of proposed translations.

I think it has to do with Weblate's tmserver client implementation [attempting to get a list of supported languages](https://github.com/WeblateOrg/weblate/blob/weblate-2.19.1/weblate/trans/machine/tmserver.py#L54) from a `/languages` endpoint that doesn't exist in [translate-toolkit's tmserver implementation](https://github.com/translate/translate/blob/2.3.0/translate/services/tmserver.py).

### Server configuration
Please paste the output of command `./manage.py list_versions` over here
```
 * Weblate weblate-2.19.1
 * Python 3.5.3
 * Django 2.0.3
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.0
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.7.7
 * user-agents 1.1.0
 * pytz 2018.3
 * pyuca N/A
 * PyYAML 3.12
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
Ah, the problem is that the code was updated for amagama and tmserver doesn't support this.

Anyway for upcoming 2.20, you might prefer to use [built-in translation memory in Weblate](https://docs.weblate.org/en/latest/admin/memory.html) instead external tmserver.

**Comment by nijel** [comment]
Also this should work just fine unless you have DEBUG = True, is it the case for you?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
