### ISSUE TITLE
Inconsistencies in browsing checks

### ISSUE THREAD

**Issue by BhaaLseN** [WeblateOrg/weblate#1943]
Currently, checks can be accessed on some levels (but not all of them):
1. **Dashboard** (showing recent and managed projects): Tools > Checks overview (which then lets you pick a check, project, component, language)
2. **Project** (showing all components for a project): Tools > Failing checks or Tools > Ignored checks (again; pick a check, component, language)
3. **Component** (showing all languages for the component): ❌ No Checks here!
4. **Language** (showing the summary page for this language): Checks are listed directly.

For consistency, Components should also let you pick checks; either through the Tools submenu (like the Dashboard and Project view) or list a summary of all checks across all languages (which might not be possible/feasible at this point).
It could simply redirect to `/checks/$check/$project/$component/` to present the language selection for the Tools submenu variant.

**Comment by kika115** [comment]
I would like to help you with this issue, please assign it to me.

**Comment by nijel** [comment]
@kika115  you're welcome to work on this

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
