### ISSUE TITLE
Is it possible to have separated projects for every user?

### ISSUE THREAD

**Issue by Skybladev2** [WeblateOrg/weblate#1944]
I would like to know, is it possible to setup Weblate to handle separate project for every user?

Now translation looks like this:
![1](https://user-images.githubusercontent.com/548735/38166672-7468e9da-3530-11e8-9122-a8c70aee3de2.png)

While I need this configuration:
![2](https://user-images.githubusercontent.com/548735/38166673-7f6564a8-3530-11e8-8099-2d4f615862f3.png)

**Comment by nijel** [comment]
Well there is no technical limitation why every user could not have own project, but you need some automation to make it behave way you want.

**Comment by Skybladev2** [comment]
Ok, thanks.
I don't see any explicit info on this in the docs. Could you point me out what do I need to tweak?
