### ISSUE TITLE
How to change branche for component

### ISSUE THREAD

**Issue by hram** [WeblateOrg/weblate#1945]
### Steps to reproduce
1. Edit existing  component
2. Change Repository branch to "release/v1.14"
3. Press "Save"

### Actual behaviour
Failed to update repository: fatal: A branch named 'release/v1.14' already exists. (128)

### Expected behaviour
Branche succesfuly changed

**Comment by nijel** [comment]
It seems you were already using this branch at some point in past, right?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
