### ISSUE TITLE
Suggestion for additional translation check - po files

### ISSUE THREAD

**Issue by shanewims** [WeblateOrg/weblate#1946]
Translating SLE po files we came accross the following issue:

the msgid contains a variable %i
The translator mistook this for %1, and %1 was entered in the msgstr.

There is no translation check to make sure that these variables are consistent. 
The po file in the build caused a crash because of the inconsistent variables.

Request that there is a translation check for “Inconsistent C/C++ variable (%s, %d, etc) count”

**Comment by nijel** [comment]
The check is there, see https://docs.weblate.org/en/latest/user/checks.html#format-strings

It has few prerequisites: 

* The check has to be enabled in Weblate (what is default)
* The unit has to be properly flagged as format string (`c-format`, xgettext does that by default if properly configured)
