### ISSUE TITLE
Show "Start new translation" even when not logged in

### ISSUE THREAD

**Issue by TheLastProject** [WeblateOrg/weblate#1950]
So far, every single time I've referred a new translator to the Pext page on Hosted Weblate, they ask "can you add <language name> so I can start translating"? The new button is great, but unfortunately only shown when logged in, so many new users who haven't used Weblate before don't see it and get confused :(

**Comment by nijel** [comment]
Just to clarify: you don't want unauthenticated users to start new translations, just to be able to see the button, right?

**Comment by TheLastProject** [comment]
Yeah, exactly

**Comment by comradekingu** [comment]
The  grayed out "start new translation"-button and the "Log in" could be outlined in the same way, so as to draw a connection between their function.

**Comment by piyushmittal25** [comment]
Hello team:)
Can I take care of this issue and its going to be my first open source contribution.

**Comment by comradekingu** [comment]
@piyushmittal25 That is a different issue. You have to click your way into one of the resources to open up a new translation.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
