### ISSUE TITLE
Whitespace in placeholder

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#1952]
What it looks like

![supposed2](https://user-images.githubusercontent.com/13802408/38480560-7d296e4a-3bc6-11e8-9e79-430c39d5f612.png)

What it actually is

![actual](https://user-images.githubusercontent.com/13802408/38480568-88647408-3bc6-11e8-94de-762789307bd6.png)

Whitespace after the placeholder

![after](https://user-images.githubusercontent.com/13802408/38480574-8fe63360-3bc6-11e8-8fc1-226f3809c28d.png)

Actual content

![actual2](https://user-images.githubusercontent.com/13802408/38480651-00321f9e-3bc7-11e8-9d0d-4deba125537b.png)

A lot of people get this wrong. Would be nice if there were no whitespaces before and after the placeholder numbering.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
