### ISSUE TITLE
Weblate's italian translation

### ISSUE THREAD

**Issue by f-liva** [WeblateOrg/weblate#1954]
Hello

Italian translations for Weblate platform is missing a lot of strings and there are some typos I would fix them.

How I do that?

**Comment by nijel** [comment]
You can fix in using Weblate: https://hosted.weblate.org/projects/weblate/master/it/

**Comment by comradekingu** [comment]
@fede91it Other italian resources here https://hosted.weblate.org/languages/it/weblate/

**Comment by fede91it** [comment]
thanks
