### ISSUE TITLE
Balance typo?

### ISSUE THREAD

**Issue by ovari** [WeblateOrg/weblate#1955]
https://github.com/WeblateOrg/weblate/blob/weblate-2.20/docs/user/checks.rst

Should 'ballance' be 'balance'? Only one 'l'?

Thank you

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
