### ISSUE TITLE
Notifications about new components in watched project

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#1956]
Right now it is possible to watch a project, where a new subbranch can be added, without triggering any notifications.
For example AndroidOS/Lipstick 
It is new, and there seems to be no other way of finding out than clicking into each resource to see if there are any resources without ones translated language(s).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
