### ISSUE TITLE
searching comments always yields 0 results

### ISSUE THREAD

**Issue by elarzee** [WeblateOrg/weblate#1957]
### Steps to reproduce
1. search (tick - also or only - "Search in comment strings")
2. for string (that definitely is there in several comments)
2. on all levels (project-, component-, language-level)

### Actual behaviour
result: "No string matched your search!"

### Expected behaviour
should yield results (concrete case: at least eleven)
(we're using comments containing the word "outdated" to mark obsoleted strings not to be bothered with by translators)

### Server configuration
 * Weblate 2.17.1
 * Python 3.5.3
 * Django 1.11.6
 * six 1.11.0
 * social-auth-core 1.5.0
 * social-auth-app-django 2.0.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.1
 * lxml 4.1.0
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.1
 * pytz 2017.3
 * PyYAML 3.12
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
This is indeed confusing - it searches only in comments from the translation files, not in the comments in Weblate.

Can't you just remove the obsolete strings from the translation files instead? There is also https://github.com/WeblateOrg/weblate/issues/743 to do similar thing on Weblate side, but it's nowhere near implementation right now.

**Comment by elarzee** [comment]
i see. removing them from the source is the cleanest solution, anyway. thanks!
