### ISSUE TITLE
Wrong ouput for PHP strings translation

### ISSUE THREAD

**Issue by fede91it** [WeblateOrg/weblate#1959]
### Steps to reproduce
1. Connect a new component to git@github.com:fede91it/weblate-laravel-lang-files.git
2. Set file mask to `resources/lang/*/app.php`
3. Set monolingual base language file to `resources/lang/en/app.php`
4. Set file format to `PHP strings`
5. Start a new translation from frontend and translate, than commit
6. See produced file output for new language

### Actual behaviour
```php
<?php
'fruits' = array(
    'peach' => 'pesca',
);
'vegetables' = array(
    'legumes' => array(
        'beans' => 'fagioli',
    ),
);
```

The produced PHP file is NOT valid.

### Expected behaviour
```php
<?php

return [
	'fruits' => [
		'peach' => 'pesca',
	],
	'vegetables' => [
		'legumes' => [
			'beans' => 'fagioli',
		],
	],
];
```

The produced PHP file reflects the base language unamed PHP array structure.

### Server configuration
 * Weblate 2.20
 * Python 2.7.12
 * Django 1.11.12
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.7.2
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.1
 * user-agents 1.1.0
 * pytz 2018.3
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
This is issue in translate-toolkit, I've submitted pull request with fix here: https://github.com/translate/translate/pull/3801

**Comment by fede91it** [comment]
Thank you very much for your prompt action!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed in the translate-toolkit.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by fede91it** [comment]
Thanks!

I'm in virtualenv, how I update translate toolkit?

**Comment by nijel** [comment]
As it's not yet released, you have to install from git, following should work, though I haven't tested it:

```
pip install https://github.com/translate/translate/archive/branch.zip
```

**Comment by fede91it** [comment]
I have updated translate-tookit and checked the PHP files generated by the new translations. There is still a problem, an equal is added before the brackets of the return, still resulting in invalid file.

```php
<?php
return = [
    'fruits' => [
        'peach' => 'pêche',
    ],
    'vegetables' => [
        'legumes' => [
            'beans' => 'fèves',
        ],
    ],
];
```

**Comment by nijel** [comment]
You're right, I've not really fixed the `return []` case, only `return array()`. Here is another fix: https://github.com/translate/translate/pull/3802
