### ISSUE TITLE
ParseError saving a translation

### ISSUE THREAD

**Issue by f-liva** [WeblateOrg/weblate#1960]
### Steps to reproduce
1. An Italian string (source language) is translated into Portuguese

![screencapture-translate-marisdea-translate-vivi-city-applicazione-pt-2018-04-12-10_07_30](https://user-images.githubusercontent.com/346224/38664515-27e65fc6-3e3a-11e8-95a3-0a37aaeea701.png)

2. The translation is saved

![screencapture-translate-marisdea-translate-vivi-city-applicazione-pt-2018-04-12-10_08_19](https://user-images.githubusercontent.com/346224/38664591-5fb13908-3e3a-11e8-8bc1-84148849d5b6.png)

### Actual behaviour
The translation is saved correctly.

### Expected behaviour
Saving the translation creates a ParseError.

### Server configuration
 * Weblate 2.20
 * Python 2.7.12
 * Django 1.11.12
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.7.2
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.1
 * user-agents 1.1.0
 * pytz 2018.3
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
Are this same PHP files as in #1959? It might be same or similar issue in handling PHP files...

**Comment by nijel** [comment]
Yes, I think it's related to that.

**Comment by fede91it** [comment]
OK thanks

**Comment by fede91it** [comment]
Fixed
