### ISSUE TITLE
Qt linguist files source/context mix

### ISSUE THREAD

**Issue by mzanetti** [WeblateOrg/weblate#1962]
We're using weblate with Qt Linguist .ts files. It mostly works great, except it seems to mix up source strings and context. Here's a screenshot:

![image](https://user-images.githubusercontent.com/102573/38679532-49df2728-3e64-11e8-834a-6d4221fa15af.png)

The actual installation is public and can be found here:
https://translate.nymea.io/translate/nymea/nymead/de/?type=all

Or reviewing just source strings, it has only empty strings:
https://translate.guh.io/projects/nymea-plugins/datetime/source/review/?type=all

Our code is open source and the source .ts files can be found here:
https://github.com/guh/nymea/tree/master/translations

Thanks

**Comment by nijel** [comment]
You probably should use the files as monolingual when they do not contain source strings, see https://docs.weblate.org/en/latest/admin/projects.html#monolingual-components

**Comment by nijel** [comment]
I've just extended docs to cover this example as well: https://docs.weblate.org/en/latest/formats.html#qt-linguist-ts
