### ISSUE TITLE
Commenting a multi-line string scrolls the string translation field

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#1963]
![scrolling](https://user-images.githubusercontent.com/13802408/38709886-cc956dea-3ebd-11e8-9010-cd800bfd95d4.png)

1. Input multi line translation
2. Input source comment
3. Send source comment
4. Multi line translation is now single line.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
