### ISSUE TITLE
Weblate and GDPR

### ISSUE THREAD

**Issue by nikosdion** [WeblateOrg/weblate#1968]
The European Union's General Data Protection Regulation (GDPR) is coming into effect on May 25th. Per the GDPR we need the user's explicit (and revokable) consent before collecting and using any personally identifiable information (PII).

During the account creation on a Weblate installation we ask our users for their name and email address and possibly to link a social account. All of these are considered PII under the GDPR since they can be used to identify the natural person.

When the GDPR goes into effect this would be a violation which carries hefty fines. The only way I can think to fix that is have Weblate provide a mandatory checkbox on user registration "I agree to the Privacy Policy of this site" where "Privacy Policy" is a link to a static page on the site (which means that you need a documented way to provide it). If they don't check that box they can't create an account. The last date, time and IP address when consent was given (or not given) must be recorded.

If they are using a social login they have obviously not gone through this process and they have not given consent. Or maybe in a later time they revoked that consent. In both cases, when explicit consent is not given they should be directed to their user profile page upon login and be unable to visit any other page, even if they type the URL themselves, unless they provide their consent.

Is this something which is going to be implemented by Weblate before May 25th or should I be looking at shutting down the volunteer translation site of my software?

Thank you in advance for your clarification on this matter!

**Comment by nijel** [comment]
It's already implemented in Weblate, you just need to configure it: https://docs.weblate.org/en/latest/admin/optionals.html#legal

**Comment by comradekingu** [comment]
I am an earlier user, so I haven't explicitly accepted the one i saw.
I think an option to obfuscate usernames, but still identify all work attached to any of its doing is interesting.
Adding a libravatar could be a user-click away. Libravatar has a user-policy in place.

**Comment by nijel** [comment]
It's not yet enforced on Hosted Weblate, it's currently only done on new registrations, but the plan is to enforce it soon (the code is already there, it just needs to be enabled).

I don't see reason to obfuscate usernames, it really doesn't bring much benefits...

**Comment by nijel** [comment]
JFYI: Accepting of ToS should be now enforced on Hosted Weblate.
