### ISSUE TITLE
403 doc link for 2.17

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1969]
### Steps to reproduce
1. Follow the documentation link in admin/trans/whiteboardmessage/add/
2. See permission denied at https://docs.weblate.org/en/weblate-2.17/admin/whiteboard.html

### Actual behaviour
404 error

### Expected behaviour
Proper doc is displayed.
I'm not sure if it's a good idea to host the doc centrally anyway, it's a spof. Won't work in closed network, too. Maybe optionally bundle it?

### Server configuration
Weblate 2.17.

**Comment by nijel** [comment]
Apparently something has changed on the RTD service, these were accessible before. I've just changed the settings there and it again works.

The documentation source is shipped, but there is currently no way to change the URL Weblate is using here. Doing so would be trivial in case somebody finds need to do so in the `get_doc_url` function:

https://github.com/WeblateOrg/weblate/blob/e336c8cd228122f6c58e5a78cf3d318404ac1a48/weblate/__init__.py#L55-L68

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by burner1024** [comment]
thank you
