### ISSUE TITLE
XLIFF indents lead to merge conflicts

### ISSUE THREAD

**Issue by mlaggner** [WeblateOrg/weblate#1970]
### Steps to reproduce
1. import a well formatted XLIFF file into weblate (with existing translations)
2. change a translation of an unit of this XLIFF file
3. commit changes and compare source and comitted XLIFF files

### Actual behaviour
the XML structure of the XLIFF file changes which leads to merge conflicts (because the source file had been re-exported too).
Source part of the XLIFF file (existing file in the git repo)

```
   <trans-unit size-unit="char" approved="no" maxwidth="60" id="DDTEXT    00001" resname="DTEL//ZEWR_ZOTYP//DDTEXT    00001">
    <source>Typ des Zielorts</source>
    <target state="needs-review-translation">Typ des Zielorts</target>
   </trans-unit>
```

the same part after changing the translation

```
   <trans-unit size-unit="char" approved="no" maxwidth="60" id="DDTEXT    00001" resname="DTEL//ZEWR_ZOTYP//DDTEXT    00001">
    <source>Typ des Zielorts</source>
   <target state="translated">Tip destinatie</target></trans-unit>
```

### Expected behaviour
the structure of the XLIFF file should not change

### Server configuration
Weblate 2.19
Python 2.7.13
Django 1.11.10
six 1.10.0
social-auth-core 1.5.0
social-auth-app-django 2.0.0
django-appconf 1.0.2
Translate Toolkit 2.2.5
Whoosh 2.7.4
defusedxml 0.5.0
Git 2.11.0
Pillow (PIL) 1.1.7
dateutil 2.5.3
lxml 3.7.1
django-crispy-forms 1.7.0
compressor 2.2
djangorestframework 3.7.7
user-agents 1.1.0
pytz 2018.3
pyuca N/A
pyLibravatar N/A
PyYAML 3.12
tesserocr 2.2.2
Mercurial 4.0
git-svn 2.11.0
Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
I though translate-toolkit is not changing the XML structure, but I might be wrong. Anyway this is something to be addressed at translate-toolkit, maybe https://github.com/translate/translate/issues/3424 is related.

**Comment by eighthave** [comment]
Roundtrip through Weblate does change the XML code format.  It does what's documented in  translate/translate#3424.  I have a Python script that converts between plain text and XLIFF, and it does this after every Weblate import:

```diff
@@@ -519,18 -426,17 +548,29 @@@ v1.0.70: eblo kaŝi ag-breton Material 
        <trans-unit id="org.fdroid.fdroid.privileged.ota-description-3" maxwidth="4000" size-unit="char" approved="yes">
          <note from="developer">All description strings combined cannot exceed 4000 characters</note>
          <target state="translated">Jen kelkaj avantaĝoj:</target>
 -        <source>This has several advantages:</source> </trans-unit>
 +        <source>This has several advantages:</source>
 +      </trans-unit>
        <trans-unit id="org.fdroid.fdroid.privileged.ota-description-4" maxwidth="4000" size-unit="char" approved="no">
          <note from="developer">All description strings combined cannot exceed 4000 characters</note>
```

So I use this:
```bash
sed -i \
    -e 's,</target>\s*<source>,</target>\n        <source>,g' \
    -e 's,</source>\s*<target>,</source>\n        <target>,g' \
    localizations/*.xliff
```

Seems like there is a chance we could find some XML code format that works in common across many tools.  Unfortunately, there does not seem to be one standard XLIFF or XML code format.

**Comment by nijel** [comment]
Proposed fix: https://github.com/translate/translate/pull/3871

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed by https://github.com/translate/translate/pull/3871.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by eighthave** [comment]
Could you add this to Linguine so its easy for us to track it?

**Comment by nijel** [comment]
Done
