### ISSUE TITLE
Suggest an arrow in the opposite direction

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#1972]
Sometimes I'm running into strings that contains text like this:
To change this behavior go to  'Settings' →  'Navigation'.

In Hebrew, due to the opposite reading direction I will need a suggestion for an opposite arrow.
Now when I'm running into this kind of situation I just search for that arrow in Google, go to Wikipedia to show all alternative arrows, copying the opposite one and then pasting it into the editor.

The translation in our case will be this:
<div dir="rtl">
כדי לשנות את ההתנהגות הזאת עליך לגשת אל ‚הגדרות’ ← ‚ניווט’.
</div>

Thank you!

**Comment by comradekingu** [comment]
You can add it to the user-selected characters.
Can you link to a string that has an arrow so it is easier to make a suggestion?
A default added char for just those strings in the opposite direction might be good, i don't think it is present for left to right-languages, but there it could be copied.

**Comment by comradekingu** [comment]
@yarons 
The opposite of "→" is ""←. For every instance of "→" in a source, a "←" could be available in translation, pertaining to the opposite use of pointing rightwards, as is the convetion in RTL languages.

**Comment by yarons** [comment]
@comradekingu Well, it's just one case, there are various kinds of them:
http://xahlee.info/comp/unicode_arrows.html

It will be relatively easy to prepare a list from this webpage but this is the way to go as I see it (Adding optional opposite error to the special characters or so).
Adding each and every one of them to the special characters will create a really long list and will make the interface and the process less comfortable.

**Comment by yarons** [comment]
@comradekingu there are several thousands of projects and even more strings than that, is it feasible to add comments on each and every one of them?

I'm suggesting a simple feature for a dynamic counter facing arrow in the special characters list, solving the case for an arrow or two is not really a useful solution here.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by yarons** [comment]
You are incredible! When will you allow me to invite you to a beer?

**Comment by nijel** [comment]
Whenever you are in Prague ;-).
