### ISSUE TITLE
Slow/Unresponsive Requests

### ISSUE THREAD

**Issue by sbhigham** [WeblateOrg/weblate#1973]
### Steps to reproduce
1. Select a project
2. Select a translation

### Actual behaviour
No response from webpage, or very slow response. ERR_CONNECTION_TIMED_OUT

### Expected behaviour
Webpage should respond and display. 

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

**Comment by nijel** [comment]
What version do you use? Can you see anything in the application logs while the requests take so long?
