### ISSUE TITLE
Weblate Translation Memory/Machine Translation fails when used with language(s) that contain spaces/parenthesis in the name

### ISSUE THREAD

**Issue by rpardini** [WeblateOrg/weblate#1975]
### Steps to reproduce
1. Create a project and component, use languages with spaces and/or parenthesis in the name (eg: "Portuguese (Brazil)" (pt_BR) or "English (United States)" (en_US)
2. Go to translate screen, click on "Machine Translation"
3. Get the error below.

### Actual behaviour
`The request for machine translation using Weblate Translation Memory has failed: MemcachedKeyCharacterError: Control/space characters not allowed (key=':1:mt:weblate-translation-memory:Portuguese (Brazil):English (United States):2e99d97e4af9c97a')`

### Expected behaviour
Well, it should behave the same as when used with languages with names with no spaces and parenthesis...

### Server configuration
 * Weblate 2.20
 * Python 2.7.12
 * Django 1.11.12
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.7.2
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2018.4
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 3.7.3
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
It's really preferred the language code to be really the language code, otherwise integration with machine translation will not really work. Anyway this is bug in translations caching which should be fixed.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
