### ISSUE TITLE
Deleted anonymous account, broke Weblate

### ISSUE THREAD

**Issue by vektor330** [WeblateOrg/weblate#1977]
Hello there, today I removed the anonymous user (the system default one) when cleaning up user accounts. This broke our installation: only already logged in users can continue using it, no one can log in and webhooks are dead as well.

The anonymous user is deleted, not just disabled. How do I recreate this account?

**Comment by vektor330** [comment]
Tried fixing it using the following DB change
`insert into "public"."auth_user" ( "password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") values ( ' ', '2018-04-01 00:00:00+00', 'f', 'anonymous', ' ', ' ', ' ', 'f', 't', '2018-04-01 00:00:00+00') RETURNING *;`

Am I forgetting something or should this suffice?

**Comment by nijel** [comment]
That should be good enough. Alternatively you can use following command to create the user:

```
./manage.py setupgroups --no-privs-update --no-projects-update
```
