### ISSUE TITLE
Automatic translation: Do not translate or heal XML tags

### ISSUE THREAD

**Issue by SantosSi** [WeblateOrg/weblate#1980]
### Steps to reproduce
1. With a source string containing XML tags, click automatic translation.

### Actual behaviour
Sometimes XML tags are wrongly recognized as translatable text and are translated.

### Expected behaviour
Leave the XML tags alone:
- Either exclude the tags from being sent to the automatic translator.
- Or configure the machine translator to not translate XML-looking text (which I doubt, as this seems to be out of Weblate's control).
- Or compare the source tags and recreate them when receiving/copying from the machine translator.

### Server configuration
Hosted version

**Comment by nijel** [comment]
The current approach does not work well, but I don't see any good approach:

- Excluding tags is certainly possible, but there is no way to figure out where they should be placed, so they will be gone.
- Most of the MT services do not allow any configuration, I haven't seen any allowing to tweak this.
- How would you know how to insert them back to the translated string?

**Comment by nijel** [comment]
From #2374:

The same is true for all machine translation services, they have no knowledge of the markup.

For DeepL, the only supported markup is xml (see https://www.deepl.com/api.html), so there is possibility of converting the text to xml with xml placeholders and converting it back after translation. Maybe similar approach would work for other services as well.

**Comment by eighthave** [comment]
Based on my experience with _po4a_ and _Weblate_, I think that it is impossible or really heard to solve this programmatically.  One good approach is in the original source code, ensuring that the strings are only human language.  That's not always possible, and in those cases, it is possible to write syntax checkers that make sure the machine language bits are intact, in the right order, etc.  For example, Weblate already has a bunch of format string checkers.
