### ISSUE TITLE
Automatic translation: Do not translate text between <literal> XML tags

### ISSUE THREAD

**Issue by SantosSi** [WeblateOrg/weblate#1981]
### Steps to reproduce
1. With a string containing text between <literal></literal> XML tags, click automatic translation (see Debian handbook)

### Actual behaviour
The text is translated by the machine translator

### Expected behaviour
Everything between the literal openinng and closing tags should be left alone.

### Server configuration
Hosted version

**Comment by nijel** [comment]
This is pretty much same as with #1980. It doesn't matter whether you exclude one XML tag or tag with content, the problem is same.
