### ISSUE TITLE
Add support for Windows .rc files

### ISSUE THREAD

**Issue by SantosSi** [WeblateOrg/weblate#1982]
Windows .rc files are not supported by Weblate, but they are part of open source projects like [ReactOS](https://github.com/reactos/reactos).
Obvious issues would be:
- to identify translatable strings
- to retain the source path although not important for the translation itself
- for the output to recreate the .rc file with the original surrounding

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
I've just added basic support for this in Weblate. There will be probably some fixes needed for the translate-toolkit (which we're using for parsing the files) as the current parser there seems to have some limitations. The first thing I've noticed is currently hardcoded windows-1252 encoding, but there are more problems, see https://github.com/translate/translate/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+rc

**Comment by SantosSi** [comment]
How unfortunate: the main purpose I asked this file format for is to translate ReactOS'es .rc file, but the [translation page requests UTF-8](https://www.reactos.org/wiki/Translation_Introduction) and the oldest issue there is 9 years old...

**Comment by SantosSi** [comment]
Deat @nijel, I am afraid the rc2po development is inactive: see https://github.com/translate/translate/issues/3199#issuecomment-384318974.
If nobody steps in, do you have other means of supporting this format instead, like making weblate parse .rc files without dependencies or debugging rc2po yourself?

**Comment by nijel** [comment]
I'd prefer to fix the parser in translate-toolkit rather than implementing parser inside Weblate. This has already happened with other parsers as well (eg. I've rewritten PHP parser in https://github.com/translate/translate/pull/3697 or contributed YAML support in https://github.com/translate/translate/pull/3500).
