### ISSUE TITLE
Do not allow removing anonymous user

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1984]
Currently when anonymous user is removed many things fail to work (see https://github.com/WeblateOrg/weblate/issues/1977), the admin interface should not allow to delete this user.

**Comment by freefri** [comment]
Same problem when removing anonymous profile

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
