### ISSUE TITLE
Strings in .PO are not showing in web interface

### ISSUE THREAD

**Issue by jasonabergel** [WeblateOrg/weblate#1986]
### Steps to reproduce
1. Go to Project
2. Click Search
3. Search for string in question

### Actual behaviour
No string matched your search!

### Expected behaviour
String found

### Server configuration
 * Weblate 2.19.1
 * Python 2.7.5
 * Django 1.11.2
 * six 1.10.0
 * social-auth-core 1.3.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 1.8.3.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.3
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.7.7
 * user-agents 1.1.0
 * pytz 2017.2
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.2.2
 * Database backends: django.db.backends.postgresql_psycopg2

### Comments
1 - If we open the PO file manually with POEdit, the strings exist and we are able to search them. However, in the web interface of Weblate, we retreive now results.

2 - The string count in the Interface is missing is missing about 2600 strings (only showing 360)

3 - We have performed a full re-index multiple times which did not work.

4 - We deleted the components and re-added it with a new name and that did not work either.

5 - We are seeing this same issue in our Staging environment but NOT in a our DEV instance. Comparing configs all looks good. Copying the .PO file from tghe working DEV instance to the failing Staging instance also did not work.

Any help with this would be great.

Thanks,

Jay

**Comment by jasonabergel** [comment]
Are you referring to Indexing Offloading, if so no. If not, I do not see background indexing in the performance report.

**Comment by jasonabergel** [comment]
I have just enabled Indexing Offloading in our dev instance, this did not resolve the issue. The string count still does not match what is in the .po file.

**Comment by jasonabergel** [comment]
For some reason there is a mixmatch yes. PRD which is NOT working is running 2.3.0 of the toolkit while DEV which IS working is running 2.2.0. Can that be the problem and how do you recommend I go about resolving that if this is indeed the issue?

**Comment by nijel** [comment]
There were some changes in parsing po files, but it should make it more fault tolerant, not stricter. Anyway can you please share that problematic file?

**Comment by jasonabergel** [comment]
Hi @nijel I was able to get Production to work now after downgrading the Translation Toolbox to be the same version deployed in DEV (2.2.5). However, although it is working, we still have 1 outstanding issue where when we refresh the page, the string count, bounces from the correct number to the incorrect number upon clicking F5. This appears to be an issue with reporting as searching for strings seems to work perfectly fine now. Any thoughts?
[en_CA.zip](https://github.com/WeblateOrg/weblate/files/1975629/en_CA.zip)

**Comment by nijel** [comment]
Okay the file is a bit weird - each filename is terminated by `\x0d`, what can be interpreted as newline in some cases.

**Comment by nijel** [comment]
This should be fixed by following PR on translate-toolkit: https://github.com/translate/translate/pull/3809

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed in the translate-toolkit. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by jasonabergel** [comment]
Hi,

I am looking to upgrade to the latest version of Weblate but the site appears to be down. Can you please take a look.

Jason Abergel
Devops Analyst | Technology – Canada | Wolters Kluwer Tax & Accounting
300 - 90 Sheppard Avenue East |Toronto, ON M2N 6X1 | Local: 416·224-2224 x6311
[WKCCH.jpg]

.

**Comment by nijel** [comment]
@jasonabergel There was server misconfiguraton affecting some Chrome and Safari versions, it's been already fixed...
