### ISSUE TITLE
Add browser client checks

### ISSUE THREAD

**Issue by SantosSi** [WeblateOrg/weblate#1989]
### Steps to reproduce
1. Copy source string
2. Save, then wait
3. The server complains about the translatoin being identical

### Actual behaviour
The server complains about the translatoin being identical.

### Expected behaviour
Instead of putting the load on the server and make the user wait for the complaint, make the browser check the strings client-side. This concept might be useful for other checks, like the ending punctuation checks.
If the string is intentionally copied and approved so by the user, please also implement a solution to avoid the server complain anyway.

### Server configuration
Hosted

**Comment by yarons** [comment]
This is a very cool feature, I ran into the following project:
https://github.com/betonimig/grunt-gettext-msgfmt

The feature we're talking about here is having a selective msgfmt per string while typing and without bloating the memory.
Maybe implementing this will solve all the overhead part of actually developing such feature and relying on it for future implementation and expansion?

@nijel you are the best! thank you so much!

**Comment by nijel** [comment]
Sorry but I don't see how that is related to checking the translations - all it does is execute msgfmt program in a grunt task. This will certainly not work within a browser and definitely will not be fast enough to run as you type.

**Comment by yarons** [comment]
So it's not an implementation of msgfmt for JS, sorry for that.

**Comment by nijel** [comment]
Considering more this I don't think it currently makes sense. Even if we would be able automatically able to generate code for the client side checks from server side ones, it will still not cover all checks done as quite some of the checks can't be performed without hitting the database and more such checks will be probably added more in the future. Even quite simple checks as translation being same as source rely on [big blacklist](https://github.com/WeblateOrg/weblate/blob/master/weblate/checks/data.py) which we probably don't want to send to client.

I understand that it might be be more user friendly in some cases, but with more complex checks in the pipeline (see https://github.com/WeblateOrg/weblate/issues/1911, https://github.com/WeblateOrg/weblate/issues/1297 or https://github.com/WeblateOrg/weblate/issues/1252), this will never cover all of the checks. 

If somebody comes up with automated way to generate code for client side checks from server side code, I'm open to bring this feature for checks where it makes sense. But implementing client side checks manually is not an option from maintenance perspective.
