### ISSUE TITLE
Howto switch branches properly?

### ISSUE THREAD

**Issue by Flohack74** [WeblateOrg/weblate#1992]
Hi, I would like to switch the Weblate subproject to a new branch in our RCS. Currently we are working in such a style that translations are not made in master but in a release branch. When a new major release is being set, we therefore would need to switch all subprojects to the new "active" branch.

**Comment by nijel** [comment]
Changing the branch in the admin interface should work just fine.

**Comment by Flohack74** [comment]
Ok I will try thx ;)
