### ISSUE TITLE
Recreate po files from Db?

### ISSUE THREAD

**Issue by Flohack74** [WeblateOrg/weblate#1999]
Hello,

made a stupid error and then panicked, resulting in accidently merging a wrong branch into the local git repo of the Weblate project. Now I am pretty sure that I messed up the po files with actually older translations. Is there a way to lets say revert in Git to an older commit, but then let Weblate just recreate the po files from its Db?

Thanks BR

**Comment by Flohack74** [comment]
Oh cool thx very much. I appreciate that there i always a way to fix things manually ;) - Can I add a filter for a specific component on this call?

**Comment by nijel** [comment]
Hmm, the above would work on recent versions, I don't think it's that easy on 2.15...

**Comment by Flohack74** [comment]
Hmm what a pity. Seems I have to manually try to roll back that stuff.... thx anyway

**Comment by Flohack74** [comment]
@nijel Finally had time to upgrade to Weblate 2.17 which introduced the pending feature, marked all of them, pressed commit or so and immediately the changes were there. Good job, thx so much!
