### ISSUE TITLE
The history event added when changing the review state look like a noop

### ISSUE THREAD

**Issue by ghost** [WeblateOrg/weblate#2000]
### Steps to reproduce
1. Translate a string
2. Click on Save
3. Go back to the string
4. Click on Approve

### Actual behaviour
An event is added to the history that claims **Translation changed** but does not hint how and displays the same string as the previous translation (as it should because it did not change) which looks like a bug.

![a](https://user-images.githubusercontent.com/433594/39694893-181f592c-51e9-11e8-9bed-b6e25a3ba55b.png)

### Expected behaviour

The history should show the old and new review state.

### Server configuration

<pre>
$ sudo docker-compose -f docker-compose-securedrop-club.yml run weblate list_versions
Starting weblate_cache_1 ... 
Starting weblate_database_1 ... done
Postgres is up
 * Weblate 2.20
 * Python 2.7.13
 * Django 1.11.12
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.1
 * user-agents 1.1.0
 * pytz 2018.3
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2
</pre>

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
