### ISSUE TITLE
/api/translations/ - listing duplicities & missing translations

### ISSUE THREAD

**Issue by zjarkov** [WeblateOrg/weblate#2003]
Hi, we experienced a bug in `/api/translations/` API method. The method shows correct results number for all projects/components but there are actually duplicities in the overall results array and at the same time some translations are missing.
When I list translations for particular components the result seems to 0K.

We are currently running 2.20 version but this happened in previous versions as well as I found (at least since 2.11 - the first version we installed).

**Comment by nijel** [comment]
I can't reproduce this right now, are you sure there are really duplicates there?

**Comment by zjarkov** [comment]
For sure. We have set of components with 17 languages and EN as main among them. We are exporting them for our partner => should be 17 files per component. But actually there is less than 17 files in the export though listing always contains 17 items per component (manually checked).
The strange thing is while on 2.11 version we had Bulgarian listed twice for one of the components, after upgrading to 2.20 there is 3xNL instead. The listing itself seems always the same while settled on certain version.

**Comment by nijel** [comment]
Thanks, I've just quickly looked into that and I have some additional questions:

* Was the list generated directly from the API or using wlc?
* Does the total count of returned translations match actual count in the database?
* If using API directly, did you get the result though pagination?

**Comment by zjarkov** [comment]
Hi, obtained directly from API with HTTP requests via pagination, count matches. I got the same result with wlc.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
