### ISSUE TITLE
Migrating project from GitHub to GitLab, how to handle that on Weblate?

### ISSUE THREAD

**Issue by elboulangero** [WeblateOrg/weblate#2007]
Hi, this is just a simple question.

I'm moving one of my project from GitHub to GitLab, and this project is translated on `hosted.weblate.org`. I can't find any place to update the url accordingly in Weblate. Is it supported? Or should I delete the project on Weblate, and re-create a new one with the new GitLab url?

Cheers,
  Arnaud

**Comment by nijel** [comment]
Just let me know and I will adjust the repository location, currently it's not editable by users.

**Comment by elboulangero** [comment]
The repository was https://github.com/elboulangero/goodvibes, moving to https://gitlab.com/goodvibes/goodvibes.

On WebLate, the project is at https://hosted.weblate.org/projects/goodvibes

**Comment by nijel** [comment]
I've just made the change.

Please check that everything looks correct. If you want Weblate to automatically follow and push to your repository, please follow instructions on https://weblate.org/en/hosting/, namely:

To notify Weblate about changes in your repository please add Weblate Service to your project:

https://docs.weblate.org/en/latest/admin/continuous.html#gitlab-setup

If you want Weblate to push changes directly to your repository, please add weblate user to the repository:

https://docs.weblate.org/en/latest/admin/continuous.html#hosted-push

The free hosting still costs us some money, so if you're in position to do that, you are welcome to support us in providing this service for free:

https://weblate.org/donate/

**Comment by elboulangero** [comment]
@nijel Thanks a lot for your support!

FYI I found one setting in the configuration that was still pointing to the old GitHub url, the *Repository Browser* setting. I updated it to GitLab, that was easy.

I added the Weblate user to my repo on GitLab, I changed a translation on Weblate, however I seem to be unable to push yet. The *commit* and *push* actions are greyed out. Am I missing something? Or maybe it's not supposed to be done that way (I'm not a translator so it's  the first time I actually try to translate something with Weblate).

![screenshot from 2018-05-22 14-45-21](https://user-images.githubusercontent.com/1942580/40348911-34c77b4e-5dcf-11e8-925e-801e5e61ac42.png)

**Comment by nijel** [comment]
It has to be configured by me, it's now done.

**Comment by elboulangero** [comment]
Almost there, apparently the Weblate user on GitLab needs to accept the new Terms of Service.

![screenshot from 2018-05-24 14-29-32](https://user-images.githubusercontent.com/1942580/40470939-38bd5ea8-5f5f-11e8-92a3-6987631d1d7c.png)

Let me open a new issue for that

**Comment by elboulangero** [comment]
Just opened #2040 to track this issue, hopefully it's just about accepting the new TOS of gitlab.com

**Comment by elboulangero** [comment]
Alright it's all good now, thanks!
