### ISSUE TITLE
Personal translation memory

### ISSUE THREAD

**Issue by ghost** [WeblateOrg/weblate#2008]
Hi,
I would like to have an option to add my own TMX/TBX instead of a simple glossary to Weblate or Weblate instance and a choice in my own profile to insert, for example, my own DeepL or personal OpenMNT API key.
As a translator, I will have the choice to share/not my own TMX/TBX publically to help other localizers.
TMX/TBX either could be uploaded to one Weblate instance or imported/linked via a link.
Suggestions appears to the translators, under the field to translate, in the automatic translation tab. Can this be possible ?
Thank you,

**Comment by nijel** [comment]
The per user translation memory is planned and is technically possible with current memory backend, but it's currently not yet on a roadmap.

**Comment by nijel** [comment]
I've created separate issue for the machine translation: https://github.com/WeblateOrg/weblate/issues/2062
