### ISSUE TITLE
Make save buttons floating

### ISSUE THREAD

**Issue by dotZoki** [WeblateOrg/weblate#2009]
It would be very useful if save buttons could be floating. This way when you fix error on a form you don't have to scroll down to bottom of a long form.

![image](https://user-images.githubusercontent.com/247270/39813109-6d3e72a6-538f-11e8-944b-0f03ba73b241.png)

**Comment by nijel** [comment]
The screenshot looks like it's from the Django interface, so you should better report it there. As for Weblate UI we rather try not to make so long forms...

**Comment by dotZoki** [comment]
OK, I didn't know it's from Django. The form (e.g. creating component) is quite long - IMHO.

**Comment by nijel** [comment]
Yes, the long term plan is to move this completely to the Weblate UI and make the creation simpler, we're just not yet there :-)
