### ISSUE TITLE
xliff tags not deleted on pull

### ISSUE THREAD

**Issue by licaon-kter** [WeblateOrg/weblate#2011]
### Steps to reproduce
1. Edit translation by removing the tags: https://hosted.weblate.org/languages/ro/kiss/#history (not limited to this language!)
2. Pull that in the repo

### Actual behaviour
The repo should have the new strings, no xliff tags

### Expected behaviour
Repo was updated with the new strings BUT the xliff tags stayed in place: https://github.com/Neamar/KISS/commit/96ac14cee920f8aebbd51b3a29c25a30ef61d9cc

### Server configuration
https://hosted.weblate.org

**Comment by nijel** [comment]
The xliff placeholders should now be fully supported, see https://github.com/WeblateOrg/weblate/pull/2364
