### ISSUE TITLE
Create funcion to copy source and intentionally leave as is

### ISSUE THREAD

**Issue by SantosSi** [WeblateOrg/weblate#2014]
### Steps to reproduce
1. Click copy
2. Don't change translated string. This is intentional for related cases, e.g. for e-mail addresses
3. Click Save
4. The unstranslated error appears
5. Confirm unstranslated
6. Click next

### Expected behaviour
The new function should allow for copying the source text and intentionally saving unchanged without further confirmation.

### Server configuration
Hosted

**Comment by nijel** [comment]
I think the current approach is good. Adding UI (button / checkbox) for this corner case would pollute the interface for not so frequently used case.
