### ISSUE TITLE
Timeout uploading PO files

### ISSUE THREAD

**Issue by DarrenV79** [WeblateOrg/weblate#2017]
### Steps to reproduce
1.  Upload a PO file
2.  Wait
3.  Timesout

### Actual behaviour
Uploading times out.

So the setup appears to be fine and weblate is running against our project.  Exporting the translations (we use PO files) is fine but uploading just sits and eventually time outs (approx 7minutes) with:

File content merge failed: [Errno 110] Connection timed out

In a red bar at the top.

My biggest issue is that I cannot find any information on where to find the logs or how to configure such with the docker set up to provide addtional info or see why this happens myself.

### Expected behaviour
It should upload.

### Server configuration
Ubuntu 16:04 with docker with Weblate 2.20 backed by PG SQL.
Docker compose file has been modified slightly to remove the Postgres and connects directly to AWS RDS instance instead.  
This was a version 2.19 originally that was upgraded to 2.20 (updated because Weblate claimed it couldnt read the PO file even though it was the same one exported)
Upload fails when client uses both Chrome and Edge.

**Comment by DarrenV79** [comment]
Addtional:

I completely obliterated the DB and set Weblate up from scratch.  Imports work fine again.

**Comment by nijel** [comment]
Having remote database will certainly have performance consequences.

The Docker container currently logs to files, what is probably not the best setup, see https://github.com/WeblateOrg/docker/issues/79

**Comment by DarrenV79** [comment]
Understood, DB isn't a huge problem.  Never goes above 2% use after initial setup.  

I think the timeout is caused by bad PO file formats.  I tried some of the old files that failed in 2.19 again in 2.20 and the error is now Invalid format.  The files from our translator is UTF8-BOM which has a header in front of it.  As I don't have the 2.19 server I cannot confirm this.  Changing the format works and uploads work fine.

**Comment by nijel** [comment]
There were some changes in translate-toolkit (which we use for parsing po files) recently which might explain this (also see https://github.com/WeblateOrg/weblate/issues/1986).
