### ISSUE TITLE
xliff <trans-unit> ID for translation import

### ISSUE THREAD

**Issue by zjarkov** [WeblateOrg/weblate#2021]
Are <trans-unit> IDs taken into consideration during translation import of monolingual component? It seems that mathing with source is fuzzy-only what leads to the need to have unique strings in the source.

**Comment by nijel** [comment]
You mean on file upload? The IDs are taken into consideration, but it was not really working well for XLIFF before 1cb37a7bb41a45124a406f4bddd836a0fd1d9b6c.

**Comment by zjarkov** [comment]
Yes, on file upload. I am asking because I have faked some test data and made all the source strings the same. Since then uploaded translation stopped to import anything => thought it could be the bug.
Also in other test data set (more real one) I have a situation where I am uploading exactly the same xliff files just with different `target-language` attribute. For some languages it matches all the strings and for others nothing.

**Comment by zjarkov** [comment]
It took a little bit longer to test due to overload but I can confirm the issue is fixed.

**Comment by nijel** [comment]
Thank you for your report, marking issue you have reported as fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
