### ISSUE TITLE
Configurable zen mode

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2022]
Currently zen mode is a bit hidden and doesn't work well for some users. What might be useful:

* option to make zen mode default
* option to display source and translation next to each other, not top bottom

**Comment by comradekingu** [comment]
I think unless it can be kept one line, spanning horizontally is quite useless.

Wrapping lines that cant be, could be a good middleground, though there is no obvious place to put secondary translations.

Putting in two short strings that each span vertically might be a better use of space.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
