### ISSUE TITLE
Search for not translated AND not suggested strings; skip own suggestions

### ISSUE THREAD

**Issue by SantosSi** [WeblateOrg/weblate#2023]
### Steps to reproduce
1. In a project configured to accept translations only when a suggestion was accepted >1 time click Strings needing an action

### Actual behaviour
Strings with my own suggestion are returned

### Expected behaviour
- My own suggestions should not be listed to me, since I cannot confirm them. Purpose: to confirm other user's suggestions.
- Create search categories to list untranslated strings without suggestions. Purpose: to create new translation suggestions without the need to skip the untranslated strings, but suggested by myself.

### Server configuration
Hosted

**Comment by emmapeel2** [comment]
maybe related to  #1203

**Comment by nijel** [comment]
Also related to #1163

**Comment by nijel** [comment]
Such search is now possible, for changing the default view there is https://github.com/WeblateOrg/weblate/issues/1163.
