### ISSUE TITLE
Improve translation of multiple gettext domains

### ISSUE THREAD

**Issue by ziima** [WeblateOrg/weblate#2026]
We have been using weblate for some time now, but the major obstacle we have to get over is the support of projects with multiple gettext domains. With about 20 Django applications, most of them having JS translations, makes weblate quite cumbersome to use.

We have set up our applications as single project with ~30 components some of which contain JS translations. Performing translations in this setup ends up in significant amount of manual labor to line up the commits from "django" and "djangojs" domains.

I would be very helpful if the weblate could be made aware of multiple domains in a single application and could perform the task on a single Git repository.

**Comment by nijel** [comment]
It can work on single repository:

* You can use `weblate:` URLs to share the cloned repository on Weblate side, see https://docs.weblate.org/en/latest/vcs.html#weblate-internal-urls
* On 3.0, you can automate this by [Component discovery](https://docs.weblate.org/en/latest/admin/addons.html#component-discovery)
* On older versions multiple components can be imported using [import_project](https://docs.weblate.org/en/latest/admin/management.html#import-project) management command

**Comment by ziima** [comment]
Didn't found those. Is it possible to provide a section in docs that would sum up a weblate usage with multiple gettext domains. Looks like there are currently bits and pieces here and there.

**Comment by nijel** [comment]
Indeed the documentation always can be improved, patches are welcome :-). The basic is [already there](https://docs.weblate.org/en/latest/admin/projects.html#automatic-creation-of-components) (though it doesn't specifically mention multiple gettext domains as it's just one of the use cases).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed by improving docs in https://github.com/WeblateOrg/weblate/commit/e975d628e644c5342b926393c27b95e8d5f43afc.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
