### ISSUE TITLE
Source language file api

### ISSUE THREAD

**Issue by GeorgeBekh** [WeblateOrg/weblate#2028]
### Steps to reproduce
1. Go to your component settings 
2. Ensure that "Edit base file" is **not** checked
3. `curl -X GET http://{hostname}/api/translations/{project}/{component}/{your source language}/file`

### Actual behaviour
Returns: `{"detail":"Not found."}`
Even though i'm not trying to edit it, i cannot get it.

### Expected behaviour
Returns file with translation for that language
Request expected to work like with any other language 

### Server configuration
Installed from https://github.com/WeblateOrg/docker.git

**Comment by GeorgeBekh** [comment]
I'm not sure, this component's project has setting `Access control: Public`, and the point is that when the `Edit base file` in component is **checked** getting the source language file is working just fine.

Also i observed that this affects not only files but also global list of languages 

`/api/languages/` response with `Edit base file` checked:
```
{
  "count": 2,
  "next": null,
  "previous": null,
  "results": [
    {
      "code": "en",
      "name": "English",
      "direction": "ltr",
      "web_url": "http://example.com/languages/en/",
      "url": "http://.../api/languages/en/"
    },
    {
      "code": "ru",
      "name": "Russian",
      "direction": "ltr",
      "web_url": "http://example.com/languages/ru/",
      "url": "http://.../api/languages/ru/"
    }
  ]
}
```
Without:
```
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "code": "en",
      "name": "English",
      "direction": "ltr",
      "web_url": "http://example.com/languages/en/",
      "url": "http://.../api/languages/en/"
    }
  ]
}
```

**Comment by nijel** [comment]
Your base language is Russian? In that case it's expected - when editing base file is disabled, it's not imported into Weblate, so the language is not used and you can not access it's files.

**Comment by GeorgeBekh** [comment]
Ok i kind of understand that behaviour, but how can i do monolingual translation properly then?
I want to get translations from weblate by keys (id) not by their source language value

so if i have
en.yaml
```
test: "Test"
```
ru.yaml
```
test: "Тест"
```
I cannot get the value for Russian language

I can get it via PO though but it looks like a hack to me
```
msgctxt "test"
msgid "Тест"
msgstr "Test"
```
(using msgctxt as id and msgid as value)
```

**Comment by nijel** [comment]
The API works only for translations which are stored in Weblate, if you disable base file editing, then this translation is not imported, though the strings from it are used. If you want to have it inside Weblate and do not allow editing in the UI, you can remove permissions to do that for all users.

**Comment by GeorgeBekh** [comment]
Ok, thanks for the solution!

Can we then agree on that naming option 'Edit base file'  is a bit misleading. May be consider renaming and changing description?
