### ISSUE TITLE
Distinguish which language is being translated

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2031]
![translation](https://user-images.githubusercontent.com/13802408/40356286-e007da88-5db8-11e8-9b70-801938ac1dc7.png)

Clicking comments from e-mail takes you to the respective language of what the comment was made in. However, this poses a risk that the user just starts translating thinking it is a different language.

Instead it could say "translation" in the respective language, or just say "French translation" in a local language. Or have a flag next to it.

**Comment by comradekingu** [comment]
@nijel The closest emoji for those? Maybe there already is a set that uses symbols for those that don't have a flag?

**Comment by nijel** [comment]
How do you define closest? See eg. http://www.flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/ 

I can name several other examples where country flag does not make much sense and usually is a good way to upset people by showing them something what they believe is wrong. This is very typical for Asia or Africa, where languages are not really bound to country boundaries. Also many languages are widely used in several countries, but are not major language anywhere (eg. Tamil).

**Comment by comradekingu** [comment]
All those are solved by applying them to the correct locale.

English en_UK
American english en_US
Australian english en_AU

Spanish es_ES
Mexican spanish es_MX

I suppose I'm not winning this argument, because there are corner-cases. However, this is only a cue to make you look up at the top of the screen, where it says the full name.

The mind is drawn to colours, which is the reason to use flags.

**Comment by nijel** [comment]
Yes that's doable, but most translations do not have full locale code. Actually it's for reason, in many cases the language is same regardless country, so there is no reason to differentiate and create duplicate translations.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
