### ISSUE TITLE
Change the pull request title

### ISSUE THREAD

**Issue by atallahade** [WeblateOrg/weblate#2035]
Is it possible to create pull requests with some other title than "Update from Weblate."?

**Comment by nijel** [comment]
Right now it is not possible, it's hardcoded:

https://github.com/WeblateOrg/weblate/blob/30b4c118e7c5b9b0e77ce8093129c7c807af3b6f/weblate/vcs/git.py#L550

**Comment by nijel** [comment]
I think there could be setting for this:

* Add setting default value to `weblate/trans/models/conf.py`
* Add documentation to `docs/admin/config.rst`
* Use it in the vcs (currently `weblate/vcs/git.py`)

**Comment by atallahade** [comment]
Thanks @Naruto0 !

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
