### ISSUE TITLE
Glossary field scrolls outside of box when zooming webpage

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2041]
110%
![skjermbilde pa 2018-05-24 22-20-15](https://user-images.githubusercontent.com/13802408/40511768-0b356114-5fa1-11e8-9091-1e3bd05328ad.png)

120%
![skjermbilde pa 2018-05-24 22-20-37](https://user-images.githubusercontent.com/13802408/40511790-2063326e-5fa1-11e8-9628-90c9d24433c2.png)

130%
![skjermbilde pa 2018-05-24 22-20-53](https://user-images.githubusercontent.com/13802408/40511793-23499dc4-5fa1-11e8-8b00-f621a0c9cb95.png)

**Comment by nijel** [comment]
Apparently the add form should be wrapped if it does not fit.

**Comment by DLotero** [comment]
Is this issue still available to be taken? if so, I'd love to help :)

**Comment by comradekingu** [comment]
@Dlotero Yes, have a go :)

**Comment by nijel** [comment]
The problem here is with styling and maybe also markup for the glossary pane. If either of form or displayed words are too wide, the table and/or form is drawn outside of the pane.

**Comment by nijel** [comment]
HTML markup :-)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
