### ISSUE TITLE
"Link" and "Repository for this component is linked to" not translatable

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2042]
Click https://hosted.weblate.org/projects/trebleshot/ and hover the "link" field.

![linkexport](https://user-images.githubusercontent.com/13802408/40512375-ed486294-5fa2-11e8-8e46-1b71efe14d40.png)

**Comment by nijel** [comment]
It is translatable: https://hosted.weblate.org/translate/weblate/master/cs/?checksum=2e76b2e9d8528dd1
