### ISSUE TITLE
GitHub Services are being deprecated

### ISSUE THREAD

**Issue by rugk** [WeblateOrg/weblate#2044]
This is deprecated as it seems: https://docs.weblate.org/en/latest/admin/continuous.html#github-setup

>  Note: GitHub Services are being deprecated. Please contact your integrator for more information on how to migrate or replace a service with webhooks or GitHub Apps.

As you list the webhook version below, maybe it is just time to remove the outdated docs. :smile: 
And maybe send customers using the old version a notification that they should change. :smile:

**Comment by rugk** [comment]
As for webhooks you may also want to explain what format to select. GitHub supports www-form-urlencoded or JSON. Additionally you also have to select what you actually want to push there…

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
