### ISSUE TITLE
"Add new translation" does nothing

### ISSUE THREAD

**Issue by rugk** [WeblateOrg/weblate#2046]
### Steps to reproduce
![button](https://user-images.githubusercontent.com/11966684/40515393-e7aca840-5fac-11e8-8aa2-bf96f7d93636.gif)

### Actual behaviour
see above

### Expected behaviour
Should do something or at least show an error – if there is a reason it is not permitted/possible.

### Server configuration
On https://hosted.weblate.org/ with Firefox 60

**Comment by nijel** [comment]
Can you please post list of network requests done in this as well? I can't reproduce this issue.

**Comment by rugk** [comment]
So it is on https://hosted.weblate.org/projects/offline-qr-code-generator/translations/en/#new and I see no network request being triggered, so it seems to be some JS issue or so.

**Comment by nijel** [comment]
Ah, it's not supported in this format and the UI still shows the menu item. Probably the conditions should be consistent, or better move the logic to the permission check:

https://github.com/WeblateOrg/weblate/blob/2e7bb66df33ef1798e1cd749e3a036ddca1f992c/weblate/templates/translation.html#L63-L65

https://github.com/WeblateOrg/weblate/blob/2e7bb66df33ef1798e1cd749e3a036ddca1f992c/weblate/templates/translation.html#L259-L275

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
