### ISSUE TITLE
How I can add new address? - ALLOWED_HOSTS

### ISSUE THREAD

**Issue by emresaracoglu** [WeblateOrg/weblate#2048]
Hello,

I installed with Docker with my local IP and I want to access the domain name at now but I getting this error:

> DisallowedHost at /
> Invalid HTTP_HOST header: 'sub.domain.com'. You may need to add u'sub.domain.com' to ALLOWED_HOSTS.

How do I add this domain name?
Thank you.

**Comment by nijel** [comment]
Follow the [documentation](https://docs.weblate.org/en/latest/admin/deployments.html#deployment) and 
set it in the [Docker environment](https://docs.weblate.org/en/latest/admin/deployments.html#envvar-WEBLATE_ALLOWED_HOSTS)
