### ISSUE TITLE
nb_NO incorrectly avoided, when it is correct, and nb should be avoided.

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2051]
"nb_NO" is the correct and longest standing locale for Norwegian Bokmål. Can't start any new translations now, since only "nb" is available.

Related:

https://github.com/WeblateOrg/weblate/commit/c63271dc3fcb4377dd593a39b7dcb91dbdb463d3

https://github.com/WeblateOrg/weblate/issues/1939

**Comment by nijel** [comment]
I'm a bit confused here - this change was done on request from some projects. What is wrong with using just `nb`?

**Comment by comradekingu** [comment]
@nijel It isn't as backward compatible.

**Comment by nijel** [comment]
I always thought these two are same...

**Comment by comradekingu** [comment]
nb_NO is older than the other, and that is the one we use, we being the norwegian free software folks, and the locale info. Goes back to sysV stuff.

There are also communities that speak Norwegian in other parts of the world, USA and so on, so it makes some sense.

**Comment by nijel** [comment]
> nb_NO is older than the other, and that is the one we use, we being the norwegian free software folks, and the locale info. Goes back to sysV stuff.

The problem is that there are other groups which prefer just `nb`. It's really hard for me to judge which one is better, but using just `nb` is consistent with how other locales behave. Also Weblate will have no problems loading `nb_NO` files, they will be just presented as `nb` in the UI.

> There are also communities that speak Norwegian in other parts of the world, USA and so on, so it makes some sense.

That holds true for pretty much any language ;-).

**Comment by comradekingu** [comment]
Let them prefer nb if the like, it can be grayed out with a warning, nb_NO is the default.

**Comment by comradekingu** [comment]
http://i18n.skolelinux.no/localekoder.txt is the reference.

**Comment by comradekingu** [comment]
This means I cant search for things in nb_NO, which is nearly every project in Norwegian Bokmål on Weblate.

**Comment by comradekingu** [comment]
@nijel Could I try to convince the people that asked for nb incorrectly that this is an alias? Don't know what more to bring here.

**Comment by comradekingu** [comment]
http://www.open-std.org/JTC1/SC22/WG20/docs/n854-Bokmal.htm says it is the POSIX standard https://bugzilla.redhat.com/show_bug.cgi?id=532487 says glibc uses nb_NO

nb is an alias.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by asmecher** [comment]
At the risk of re-opening an old issue -- can I ask a little more context on why `nb_NO` is preferred rather than `nb`, other than "it's always been that way"? Recently my project is standardizing locale codes according to IETF language codes, and we are generally replacing `xx_YY` locale codes with `xx` for cases where the country code doesn't add useful information.

This is following the recommendation on e.g. https://www.w3.org/International/articles/language-tags/:

> **The golden rule when creating language tags is to keep the tag as short as possible.** Avoid region, script or other subtags except where they add useful distinguishing information. For instance, use `ja` for Japanese and not `ja-JP`, unless there is a particular reason that you need to say that this is Japanese as spoken in Japan, rather than elsewhere.

This is in service of [BCP47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt), which obsoletes RFCs 4646, 3066, and 1766.

One of the motivations for this, I think, is to allow the [RFC 4647 extended filtering algorithm](https://www.rfc-editor.org/rfc/rfc4647.html#section-3.3.2) to work better. If a user's browser says it prefers `nb_SJ` (Norwegian Bokmål, Svalbard & Jan Mayen) but the software broadly supports [`nb`](https://www.localeplanet.com/icu/nb/index.html), the filtering algorithm will successfully provide the user with what they probably expect. However, if the browser says [`nb_SJ`](https://www.localeplanet.com/icu/nb-SJ/index.html) and the software supports only [`nb_NO`](https://www.localeplanet.com/icu/nb-NO/index.html), then there will be no match.

**Comment by comradekingu** [comment]
@asmecher
It _has_ always been that way, and we like to keep things open wrt. reestablishing Greater Scandinavia.

There are some Norwegian speakers in the US, and more norsemen than here, which I guess could be part of the plan,

nb_SJ isn't ever used, as it doesn't signify any dialect/language. (Only norsemen there.)
nb_NO, and nn_NO otoh. are languages of their own.

no_NO, is a nono, and shouldn't be used for anything other than maybe setting up dubious fallbacks/when unsure
which one it is/combining the two for some reason.
Web browsers support a long list of locales, _or_ (don't even think about changing it) nb_NO. :)

There are also a bunch of sami languages, like this one https://www.localeplanet.com/icu/se-NO/index.html that also falls into the *_NO paradigm.
Those are also official languages, and some of those I think are spoken in *_SE variants.

**Comment by asmecher** [comment]
@comradekingu, thanks for the details; I'm sympathetic to the pain in changing locale codes -- we recently renamed a *lot* of them -- but I think `nb_NO` is objectively the wrong choice according to BCP 47 / W3C.

I'm aware that I'm stepping into this as an outsider, and if it's a more complicated/controversial subject than I know, I apologize for my ignorance about it.

From [Internationalization Best Practices: Specifying Language in XHTML & HTML Content](https://www.w3.org/International/geo/html-tech/tech-lang.html#ri20030112.224717800) (W3C) Best Practice 12:

> Use the shortest possible language tag values.
>
> How to: The golden rule when creating language tags is to keep the tag as short as possible. Avoid region, script or other subtags except where they add useful distinguishing information. For instance, use `ja` for Japanese and not `ja-JP`, unless there is a particular reason that you need to say that this is Japanese as spoken specifically in Japan.

Then, in [Language tags in HTML and XML](https://www.w3.org/International/articles/language-tags/#region):
> Once again, you should only use region subtags if they are necessary to make a distinction you need. Unless you specifically need to highlight that you are talking about Italian as spoken in Italy you should use `it` for Italian, and not `it-IT`. The same goes for any other possible combination.

The `_NO` subtag does not add anything useful -- it's assumed that Norwegian will be as spoken/written in Norway, no? Would there ever need to be another `nb` variant? I don't think there would.

`nb_NO` also very unusual among the languages in the [Weblate languages list](https://github.com/WeblateOrg/language-data/blob/main/languages.csv). Just about all of them prefer two-language codes, unless there are multiple meaningful candidates: Portuguese; Arabic; French; Bengali; etc.

I suspect systems are going to start to want to use `nb` in place of `nb_NO` for good (standardization) reasons, despite the legacy. If "it's always been that way" was enough of an argument, this Canadian project would be forever stuck with `en_US` :)

**Comment by michael-smt** [comment]
I agree with the arguments of @asmecher above and would also like Norwegian Bokmål in Weblate to be changed to have `nb` as the primary language code. 

Weblate should **not** create a `nb-NO` file when e.g. _BCP style using hyphen as a separator_ language code style is set in a component. It should default to the shortest possible language tag value.

@comradekingu's arguments seem to boil down to:

> http://www.open-std.org/JTC1/SC22/WG20/docs/n854-Bokmal.htm says it is the POSIX standard https://bugzilla.redhat.com/show_bug.cgi?id=532487 says glibc uses nb_NO

Solved by using the language code style settings _POSIX style using hyphen as a separator, including country code_

>  It has always been that way, [...]

As far as I'm aware in such systems make **all** languages include a region, Norwegian Bokmål is not a special case. Making it consistent is what the correct language code style setting in Weblate is for.

> [...] and we like to keep things open wrt. reestablishing Greater Scandinavia.

Not sure what exactly is meant here, but having the language without any country code seems more open to me 😀
