### ISSUE TITLE
Indicate monolingual status and template editing to users

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2052]
Doesn't have to be the exact string, app/res/values/strings.xml would do just fine.
Just a way to manually point to it helps out a lot.

Even if a string is changed its markup, and its position relative in the file to the translation, the markup will correspond to the string, so it should be possible with some trouble to link directly

[Source](https://github.com/osmandapp/Osmand/blob/bd1d5d100af111420f95ead2eaf026f07e52a9e1/OsmAnd/res/values/strings.xml#L92)`
 <string name="use_two_digits_longitude">Use double digit longitude</string>`
[Translation](https://github.com/osmandapp/Osmand/blob/bd1d5d100af111420f95ead2eaf026f07e52a9e1/OsmAnd/res/values-nb/strings.xml#L2817)`
<string name="use_two_digits_longitude">Bruk tosifret lengdegrad</string>`

**Comment by nijel** [comment]
What use case are you trying to follow here? Does the XML provide something more than Weblate UI?

**Comment by comradekingu** [comment]
@nijel I am seeing a source string that is wrong, I want the quickest route to get to it so that it can be changed.

**Comment by nijel** [comment]
The quickest route should be to click on edit icon next to the source string and edit it in Weblate.

**Comment by comradekingu** [comment]
@nijel I am not disagreeing, that would be even better. Both seem nice.

I think editing a nice feature would be to have strings editable, clicking or not, but not having to open it in a different editor.

Usually it is just the one string the user wants to edit, and having a tab open in a language the user forgot was different from the usual is asking for trouble. An issue plaguing many platforms, which I have fallen victim to many times.

**Comment by nijel** [comment]
You already can edit source strings for monolingual translations (such as Android) if it's enabled for the project (what is default setting). The OsmAnd maintainers have disabled this feature.

**Comment by comradekingu** [comment]
@nijel You cornered a use-case for having links that take you to the source-code.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
