### ISSUE TITLE
Add filter to see only observed translations with work to be done

### ISSUE THREAD

**Issue by SantosSi** [WeblateOrg/weblate#2053]
### Steps to reproduce
1. Click observed translations 

### Actual behaviour
All translations are displayed, including those with 100% completion.

### Expected behaviour
Especially with a large number of observerd traslations, those without required activities clutter the display and distract from those work is needed to be done.

### Server configuration
Hosted

**Comment by comradekingu** [comment]
@SantosSi 
Click account
> Settings
Hide finished translations on dashboard [x]

**Comment by SantosSi** [comment]
I was thinking of a way of toggling to hide finised translations next to the list, not in the settings.

**Comment by nijel** [comment]
Having the settings configurable on the page which they affects is something I want to have, though it's not yet on the roadmap.

**Comment by nijel** [comment]
There is now a direct link to the settings on the dashboard.
