### ISSUE TITLE
[Question] Is there a way to automatically discove/create components?

### ISSUE THREAD

**Issue by ieugen** [WeblateOrg/weblate#2055]
Hi, 

I'm working on a project and we are migrating to use a CMS system where people can create Pages. 
These pages can contain lot's of texts and these texts need to be translated. 
I'm mostly thinking of: Terms of use, privacy policy pages etc.  The idea is that an Author can create a new page that needs to be translated. 

My question is: can I automate the process of creating components inside Weblate for each page that is created? Either this feature exists or I can find a way to script it. 

The workflow I think should be like this:

1. User creates the new page/pages that are marked somehow for translation.
2. We have a process that runs from time to time to scan for pages needing translations and exports the translations to a simple structure like: project_name/page_name ( page_path / page_id ?! ) . 
3. Weblate discovers the new page and creates the component for us. Alternatively we make an API / script call to create the component for the page.
 
Thanks,

**Comment by ieugen** [comment]
Awesome @nijel , thank you. 

Weblate should potentially have to manage hundreds or thousands of components per project. Have you done any benchmarks around this? 

What we discovered while working with clients is that not all content is equal when it comes to translating. Some pages are more important then others.

**Comment by nijel** [comment]
You can set priority on components, that makes the high priority one to show on the top.

I don't have any benchmarks, hundreds of components are certainly okay performance wise.

**Comment by ieugen** [comment]
Thank you. I will need to find some time to upgrade weblate version to use that feature.

**Comment by nijel** [comment]
The addon is first available in upcoming 3.0 and the upgrade to 3.0 is more tricky than usual.

**Comment by ieugen** [comment]
Thanks for the heads-up. I've noticed a lot of changes there. We might do a manual migration:

- we have all the translations in git and we might use the import_project and component discovery addon to automate some parts
- we use azure_oauth2 for authentication and we can take care of users easily like that
- we do need to be able to migrate groups and roles to make sure that translators for FR can write/see only French translations . I know this area has seen some improvements lately but not sure how it all works out.

**Comment by nijel** [comment]
Yes, things like French translators should work nicely in 3.0. The plan is to make final release this week (most likely Friday).
