### ISSUE TITLE
Uploaded pictures added to statistics

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2057]
There is a whole field of unused space in the statistics, could be used to keep count of uploaded images. Would be a nice way for the user to find all their uploaded images.

![statistics](https://user-images.githubusercontent.com/13802408/40626727-ade39cc0-62ba-11e8-84e7-aa37be621d87.png)

**Comment by nijel** [comment]
We currently do not track information who has uploaded the screenshot...

**Comment by comradekingu** [comment]
@nijel I think it should be tracked, and available per default, with an option to restrict it to only cleared users.
Tagging images with program version number is an added benefit that makes it less chaotic.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
