### ISSUE TITLE
Page reload returns different checks/statistics for the same component/language

### ISSUE THREAD

**Issue by BhaaLseN** [WeblateOrg/weblate#2061]
### Steps to reproduce
1. Open a language for a component of a project.
2. Look at the list of strings that requires editing.
3. Reload the page and repeat from 2.

### Actual behaviour
Between reloads, the total number of words/translations and their status switches around from edits required to everything fine:
![image](https://user-images.githubusercontent.com/826052/40780803-fd87b894-64d9-11e8-9e13-6f0e4e931836.png)
(Reload)
![image](https://user-images.githubusercontent.com/826052/40780820-0acd7d36-64da-11e8-9b1d-87cac6e23adf.png)
(Reload)

Sorry for the german screenshot, but I guess the issue is still visible. The Screenshots are just a few seconds apart; about the amount of time needed to reload the page, fire up Snipping Tool and take a screenshot.
For that particular component (or even project?) the problem is reproducible on every other reload; even with caching disabled in the browser.

Hitting the check to see the strings comes up with a "no results" page, so I guess the state showing strings that require editing is bogus.

I already ran `./manage.py updatechecks --all` and `./manage.py rebuild_index --clean --optimize` but didn't really see any changes in behavior.
Any hints on what else I could try (or look at) would be appreciated.

### Expected behaviour
Status stays consistent on every reload.

### Server configuration
```
$ ./manage.py list_versions
 * Weblate weblate-2.20-6-g447d51f77
 * Python 3.5.3
 * Django 2.0.4
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.7.2
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2018.3
 * pyuca N/A
 * python-bidi 0.4.0
 * PyYAML 3.12
 * Database backends: django.db.backends.mysql
```
(Note that I'm running 447d51f7782c2501c097b92a0bcc7c4bdfdc5527 for the insta-commit issue reported in #1917; which is barely past the 2.20 release)

**Comment by nijel** [comment]
What cache backend do you use?

**Comment by BhaaLseN** [comment]
Uhm. None? Or whatever is configured as default. It's not really a big installation so I don't really pay much attention to that.

**Comment by nijel** [comment]
Okay, this is the problem - the default cache is in memory per process and thus it depends which process does serve your request. We should really make this more important error than it is right now.

Anyway see docs for configuring the cache: https://docs.weblate.org/en/latest/admin/install.html#enable-caching

**Comment by BhaaLseN** [comment]
Interresting, I didn't expect multiple workers being spawned...then again, I _think_ I did set some number for the WSGI stuff, so that might be it.
This might as well explain some of the random "a check triggers but the search finds nothing" problems we noticed at times.

Any thoughts on simply enabling a default cache that works good enough instead of leaving it to the Django defaults of in-memory caching per-process? Like, file-system cache inside the `DATA_DIR`. I'll probably go down that road instead of redis/memcached since it feels like overkill for this.

**Comment by nijel** [comment]
Anything shared among processes will work fine. The default per process just doesn't work as the other processes do not recalculate cache on change thus see some older snapshot of the stats.

Redis will be probably required in the future, in 3.x most likely only for optional features, in 4.0 for core as well.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed (Weblate will compain visibly about such setup).

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
