### ISSUE TITLE
Per user machine translation

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2062]
Split of https://github.com/WeblateOrg/weblate/issues/2008:

It might be useful to allow translator to configure own machine translation services by providing appropriate API keys. This could be useful feature for shared instances.

**Comment by adrmzz** [comment]
It can be useful to allow users to connect to their own Moses-based engines: http://blogs.uab.cat/tradumatica/2018/01/28/tradumatica-sponsors-a-moses-mt-connector-for-omegat-by-aaron-madlon-kay/

**Comment by nijel** [comment]
This didn't get much attention over two years, so I don't think this is worth of the effort.
