### ISSUE TITLE
Where to find the git remote for a project

### ISSUE THREAD

**Issue by fede91it** [WeblateOrg/weblate#2063]
I have a merge conflict on my project https://translate.acme.com/projects/foobar/

I read https://docs.weblate.org/en/weblate-2.20/faq.html#how-to-fix-merge-conflicts-in-translations and I see that I have to add the remote, but I cannot find the right remote URL, this doesn't work:

https://translate.acme.com/git/foobar/

**Comment by nijel** [comment]
The repositories are not exported by default, this can be done by installing [git exporter](https://docs.weblate.org/en/latest/admin/optionals.html#git-exporter).

**Comment by fede91it** [comment]
There is another way to fix merge conflict?

**Comment by nijel** [comment]
Without access to the repository, you can only reset it in Weblate UI, but that way you loose changes done in Weblate.
