### ISSUE TITLE
[Translation] Not translatable string?

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#2069]
### Steps to reproduce
1. Go to page http://xxx/contact/?t=account (from mail received when a suspicious activity is detected on an account)
=> see screen shot attached.
![not translatable string](https://user-images.githubusercontent.com/1452146/40839967-fe9b7d44-65a4-11e8-8a20-72d0c1a4975e.png)

### Actual behaviour
In the form, topic is filled in english and I was not able to find any translation string for it (checked in: https://hosted.weblate.org/projects/weblate/master/fr/ ).

### Server configuration
Original server : https://l10n.xwiki.org

**Comment by nijel** [comment]
That's expected - this is subject of sent mail and the preferred language there is currently English...

**Comment by ldmpub** [comment]
Okay, maybe this field should be in read only or even hidden to the user?

(Weblate is a translation tool, everything I saw until this issue was perfectly managed in several languages. That's the reason why I raised this question / issue).

**Comment by comradekingu** [comment]
I think it would be better to translate the fields, and then have
"preferably in English, or Romanian" in gray font in the message field, to be overwritten once you start typing.

**Comment by ldmpub** [comment]
New suggestion based on @comradekingu reply above:
1. have a "type" of request / hidden to user in the form / translated in weblate app / added to the beginning of the mail's subject received by weblate admin
2. have an "open" subject / displayed to user in the form / editable / added to the end of the mail's subject received by weblate admin.
3. Final mail subject will be composed of "1+ 2".

For instance weblate admin **will receive a mail with subject like "[Suspicious activity report] blabla**" where:
- **[Suspicious activity report]** : is the type of request (see 1 above), displayed in admin language (string to add to weblate translation resources)
- **blabla**: is the value user entered in the custom subject field of the web form ;-).

What do you think of my proposal?

**Comment by comradekingu** [comment]
The current way to do it is https://github.com/nijel/weblate/blob/b16006fffab4260b746f4b5aaeaa7371676657a7/weblate/accounts/forms.py#L322

"Please contact us in English, otherwise we might be unable to understand your request."
Which is preferable.

**Comment by comradekingu** [comment]
As this is not for the actual text field, for which a graytext explanation could be used, this string could be made translatable to solve the issue.
