### ISSUE TITLE
UI refinement

### ISSUE THREAD

**Issue by agaida** [WeblateOrg/weblate#2070]
### Steps to reproduce
1. Open weblate in Browser
### Actual behaviour
![](https://i.imgur.com/gsKfqZ8.png)
* One of the documentation links is superfluous
* Contact link is hard to find

### Expected behaviour
* Remove Documentation form top bar
* Place the Contact link in the top bar instead

### Server configuration
Please paste the output of command `./manage.py list_versions` over here
```
 * Weblate 3.0
 * Python 2.7.13
 * Django 1.11.13
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.7.3
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2018.4
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.0
 * hub 2.3.0-pre10-136-g1e5bb95
 * Database backends: django.db.backends.postgresql_psycopg2
 * Cache backends: default:MemcachedCache, avatar:FileBasedCache
```

**Comment by comradekingu** [comment]
I would put both in the footer. It is where I would expect to find them, and it de-clutters a bit.

**Comment by agaida** [comment]
PS: there is a second aspect - i know that Weblate need donations, so i would like to leave the footer untouched. But that means that i would like to have the top bar for the needed downstream things.

**Comment by nijel** [comment]
Also the footer can contain more things than you see on the default install, both of them are downstream and I don't think it makes sense to place them to the top bar:

* Legal (see https://docs.weblate.org/en/latest/admin/optionals.html#legal)
* Status page link (see https://docs.weblate.org/en/latest/admin/config.html#status-url)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
