### ISSUE TITLE
Possibly duplicated locales

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2072]
Might be I'm wrong, but

Tibetan **bo_BT** and **bo**
Tartar **tt** and **tt@iqtelif**
Serbian **sr_Cs** and **sr**
Moldavian **mo** and **ro_MD**
Chinese traditional **zh**, **zh_hant** and **ZH_CMN_HANT**
Catalan **ca**, **ca@valencia** and **ca_ES@valencia**
(the Valencian variant of Catalan is a bit different, might be warranted)

If some of these are aliases, i think that should be evident.

**Comment by nijel** [comment]
No aliases are shown, so these are indeed separate languages. Most likely this comes from merging various data sources for language definitions and some of them using different language codes.

**Comment by nijel** [comment]
The tt and tt@iqtelif use diferent alphabet, so these should be kept.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
