### ISSUE TITLE
Choose/Select consistency in strings

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2079]
This has been brought up here: https://hosted.weblate.org/translate/weblate/master/fr/?checksum=3205fc07a8b7d090#comments

> We have 14 occurrences of Choose and 5 Select. IMO, to ensure consistency, we should use the same term for the same concept.

**Comment by comradekingu** [comment]
In my head "choose" implies the choice could be none.
"Select" selects from a selection.

**Comment by ldmpub** [comment]
I agree with @comradekingu: selection is among a restricted number of choices.

**Comment by comradekingu** [comment]
@nijel This is fixed :)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
