### ISSUE TITLE
No replacement for examples/hook-json_restore_hierarchy in 3.0

### ISSUE THREAD

**Issue by BhaaLseN** [WeblateOrg/weblate#2080]
I know this is technically a translate-toolkit thing, but this has been possible before using pre-commit scripts; so I'm reporting this anyways as it blocks upgrades.

### Steps to reproduce
1. Install Weblate 2.x and configure a hierarchical Json format using `examples/hook-json_restory_hierarchy` in `PRE_COMMIT_SCRIPTS`.
2. Upgrade to Weblate 3.0
3. Find out that the Json Addon replacement does not support hierarchy restore.

### Actual behaviour
Previously hierarchical Json file is now flattened.

### Expected behaviour
Json hierarchy is being restored by the addon.

### Server configuration
```
$ ./manage.py list_versions
 * Weblate weblate-3.0
 * Python 3.5.3
 * Django 2.0.6
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.7.3
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2018.4
 * pyuca N/A
 * python-bidi 0.4.0
 * PyYAML 3.12
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache
```

**Comment by nijel** [comment]
The solution is to use nested json file format that does preserve the hierarchy. You should have been migrated to this automatically if you were using the hook. The [addons.0003_install_addons migration](https://github.com/WeblateOrg/weblate/blob/master/weblate/addons/migrations/0003_install_addons.py) is responsible for this. This migration was already present in 2.19, the 3.0 release didn't change anything here...

**Comment by nijel** [comment]
PS: You're right that if you've configured this after 2.19, then the migration would not have happened...

**Comment by BhaaLseN** [comment]
Oh, thats probably because I had a customized one with different indent width. 
Plus, I actually missed the nested JSON format in my `WEBLATE_FORMATS`, so I couldn't possibly select it.

Thanks for clarifying!
