### ISSUE TITLE
Docs: Redis connection using TCP vs. Unix Socket

### ISSUE THREAD

**Issue by BhaaLseN** [WeblateOrg/weblate#2081]
Not sure if [Installation: Enable Caching](https://docs.weblate.org/en/latest/admin/install.html#enable-caching) is slightly outdated or not, but I couldn't get Redis to run with just the instructions there.

Some things I had to search first before it would work (Note that this is on Debian 9.4; not sure if others have different requirements):
1. The instructions list `redis-server` as prerequisite for caching, but never mention the `django-redis` and `hiredis` (plus `redis` as dependency) packages. They're not in `requirements.txt` or `requirements-optional.txt` either.
2. The sample configuration uses a Unix Socket at `unix:///var/run/redis/redis.sock?db=0`, but the default installation of Redis uses TCP at `redis://127.0.0.1:6379/1` (or similar; at least thats the one that worked for me)

**Comment by nijel** [comment]
Good point, we're slowly moving towards redis and the docs is not really consistent here.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
