### ISSUE TITLE
Misaligned Source information box when using long translation file paths

### ISSUE THREAD

**Issue by darthginger** [WeblateOrg/weblate#2083]
### Steps to reproduce
1. Add Project with long translation file path
2. Open translate page

### Actual behaviour
See misaligned Source information box

### Expected behaviour
Nicely aligned Source information box

### Server configuration
* Weblate weblate-3.0
 * Python 3.6.5
 * Django 2.0.6
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.7.3
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2018.4
 * pyuca N/A
 * Database backends: django.db.backends.mysql
 * Cache backends: default:MemcachedCache, avatar:FileBasedCache

See attached file, tested on Chrome 67, Edge 42 and IE 11.
![weblatebug](https://user-images.githubusercontent.com/8257956/41194265-02c2f472-6c19-11e8-931e-37a897c3f187.JPG)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
