### ISSUE TITLE
No other translations yet error appears

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#2085]
This is from Weblate 2.18 (elementary OS instance):
![image](https://user-images.githubusercontent.com/406826/41358818-d856f67c-6f31-11e8-8559-ca143df6358d.png)

Even though these 2 strings are completely identical I'm seeing this error no mater what I try.

**Comment by nijel** [comment]
Can you please post link to the string as well?

**Comment by yarons** [comment]
Sure, sorry.

https://l10n.elementary.io/translate/desktop/granite/he/?type=allchecks

**Comment by comradekingu** [comment]
@yarons From what I remember, that was a feature of 2.18 elsewhere too.
You can disregard the check, at-least I did for elementary.

**Comment by nijel** [comment]
Ah, that is still on 2.18. I this this has been addressed meanwhile, but I couldn't find related issue right now.

**Comment by yarons** [comment]
If you claim it was fixed I trust you and there's no need to provide evidence.

Thank you :smile:
