### ISSUE TITLE
Wrong calculation of Strings needing action

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#2086]
![image](https://user-images.githubusercontent.com/406826/41399275-89c72270-6fc2-11e8-913f-411b71ba3fda.png)
https://hosted.weblate.org/projects/osmand/main/he/

I've seen the update message in my mailbox, shouldn't the first 3 (Stings needing edit) be actually 36?

**Comment by nijel** [comment]
It should, however it seems to be translated now, so no longer reproducible. It seems to sum up properly elsewhere (eg https://hosted.weblate.org/projects/gammu/gammu-docs/cs/).

**Comment by yarons** [comment]
I should have left one untranslated, I'll wait to see if it happens again in the next import.
