### ISSUE TITLE
Clicking search does not go back to search

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2088]
("Søk" means "search")

![skjermbilde pa 2018-06-14 23-01-47](https://user-images.githubusercontent.com/13802408/41438278-0ce7871c-7027-11e8-850b-54bce56ac403.png)

It tries to go to 

https://hosted.weblate.org/search/

I would expect it to go back to the search for the language in question

https://hosted.weblate.org/languages/en_GB/weblate/#search

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
