### ISSUE TITLE
403 Error on `git pull` from Weblate remote

### ISSUE THREAD

**Issue by aardvarkk** [WeblateOrg/weblate#2091]
### Steps to reproduce
1. Deploy Weblate (I'm using a Docker deployment)
2. Add the remote repository with `git remote add weblate http://myrepo`
3. Run `git pull`

### Actual behaviour
A 403 error is returned: 
`fatal: unable to access 'http://myrepo': The requested URL returned error: 403`

### Expected behaviour
The repository is pulled

### Server configuration
Would paste the output of `list_versions` here, but I'm not entirely clear on how to run this command on a Docker deployment.

### Possibly Relevant
- It's a Docker deployment
- It's version 2.20 of Weblate
- There's no domain name for the repo -- I'm using an IP address directly

**Comment by nijel** [comment]
If the project is not public, you need to authenticate for git as well.

To figure out more what is going on, please run `GIT_CURL_VERBOSE=1 git remote update weblate`

**Comment by nijel** [comment]
Also maybe your [ALLOWED_HOSTS](https://docs.djangoproject.com/en/latest/ref/settings/#std:setting-ALLOWED_HOSTS) settings does not match what you use in git?

**Comment by aardvarkk** [comment]
Here's the output from the update request (with IP filtered out):

```
Fetching weblate
* Couldn't find host xxx.xxx.xxx.xxx in the .netrc file; using defaults
*   Trying xxx.xxx.xxx.xxx...
* TCP_NODELAY set
* Connected to xxx.xxx.xxx.xxx (xxx.xxx.xxx.xxx) port 80 (#0)
> GET /git/repo/repo-web/info/refs?service=git-upload-pack HTTP/1.1
Host: xxx.xxx.xxx.xxx
User-Agent: git/2.15.1
Accept: */*
Accept-Encoding: gzip
Pragma: no-cache

< HTTP/1.1 403 Forbidden
< Server: nginx/1.10.3
< Date: Wed, 20 Jun 2018 21:11:05 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Language, Cookie
< X-Frame-Options: SAMEORIGIN
< Content-Language: en
< Set-Cookie: sessionid=p0e72lm2gry9z35eoyg7fotplr0h7nay; expires=Wed, 04-Jul-2018 21:11:05 GMT; httponly; Max-Age=1209600; Path=/
< Content-Encoding: gzip
<
* Connection #0 to host xxx.xxx.xxx.xxx left intact
fatal: unable to access 'http://xxx.xxx.xxx.xxx/git/repo/repo-web/': The requested URL returned error: 403
error: Could not fetch weblate
```

**Comment by aardvarkk** [comment]
I like your `ALLOWED_HOSTS` idea -- I'm going to try setting that to see if it fixes the issue

**Comment by aardvarkk** [comment]
I've also added:

`      - WEBLATE_INSTALLED_APPS+=('weblate.gitexport',)`

to the Docker Compose override file, then run `docker-compose run weblate migrate` (as suggested here: https://docs.weblate.org/en/latest/admin/optionals.html#git-exporter), but I'm still getting the 403 error.

**Comment by aardvarkk** [comment]
I've also tried changing the remote repository URL to include Weblate credentials (i.e. `git remote set-url weblate http://weblateuser:weblatepassword@mydomain/git/project/component`), but still getting the 403.

**Comment by aardvarkk** [comment]
The problem is definitely related to project access. I had set the project access to Private. When I switch to Public, everything works as expected. It looks like, when specifying a username and password, only `https` is supported. But that's not explicitly stated anywhere -- just my guess. And to support HTTPS, a whole reverse proxy setup (and apparently some other complexities?) are involved. So for now I just opened up the project publicly, even though I don't really want to!

**Comment by nijel** [comment]
There is definitely no https limit on Weblate site, though maybe Git refuses to pass authentication on insecure http...

**Comment by nijel** [comment]
Also if you want to have your project private and public VCS (what kind of does not make sense to me), you can add permission to access VCS to the anonymous user in Weblate.

**Comment by utapyngo** [comment]
@aardvarkk have you solved the problem?

I am experiencing a similar problem with docker deployment of weblate 2.1.7. 
I can pull but can't push, even if I set access control to Public.
The error message is

> fatal: unable to access 'https://username:key@weblate-server-fqdn/git/project/component/': The requested URL returned error: 403

**Comment by aardvarkk** [comment]
To be honest I can't recall exactly what I did to gain access. I think, though, it was a Weblate setting I needed to change. I think I ended up opening up permissions and then it worked. I may have switched also from the username/password auth to a secured protocol. To be honest, though, I think it was the Public access control I needed to fix, so I'm not sure what to tell you if that's not working for you.

**Comment by rishubil** [comment]
I had a similar problem with this issue.

By using the `GIT_CURL_VERBOSE` option, I found that git was not sending the AUTHORIZATION header properly.

This is a temporary solution, but I was able to solve the problem by forcibly adding the AUTHORIZATION header using the extraheader.

You can add extraheader like this:
```
git \
    -c "http.https://<HOST>/git/.extraheader=AUTHORIZATION: basic <TOKEN>" \
    fetch weblate
```

Change `<HOST>` to your host, `<TOKEN>` to encoded `username:api_key` as base64

**Comment by nijel** [comment]
@rishubil You're probably hitting different issue. HTTP 403 response is returned after authentication, but Git doesn't seem to send one in your case.

This is how it is supposed to work (for non-public projects):

1. Git issues unauthenticated request
2. Server responds with HTTP 401 and `WWW-Authenticate` header
3. Git issues authenticated request
4. Now the server response varies:
   * HTTP 404 for non-existing components or not supported repository (eg. trying to access Mercurial repo with Git)
   * HTTP 403 for permission denied (user doesn't have permission to access the Git repo)
   * When all above checks pass, handling is passed to Git to serve the actual payload and status code

In your case, there seems to be issue with passing response in step 2 from Weblate. Maybe some reverse proxy is filtering that.
