### ISSUE TITLE
Regular expression search

### ISSUE THREAD

**Issue by jorgesumle** [WeblateOrg/weblate#2092]
### Steps to reproduce

We were trying to search words that contain upper-case letters at the beginning of a word except at the start of the string (see https://github.com/liberapay/salon/issues/125#issuecomment-398013861), but I didn't know how to do that within Weblate, and so I had to search it locally using GNU grep. I also searched in the documentation but I didn't find any instance of "regular expression". Is there a way to search using a regular expression? I think that feature would be useful.

### Actual behaviour
We don't know how to search using regular expressions

### Expected behaviour
There should be an advanced option for regular expressions, visible.

### Server configuration
Using weblate.org

**Comment by nijel** [comment]
It's currently not there. It needs to be evaluated for performance reasons, but I think it should be okay to provide this.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
