### ISSUE TITLE
"New strings to translate" Notification received ... but nothing to do

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#2093]
### Actual behaviour
Automatic mail received "New strings to translate" but:
- in the mail body: counts indicate no string to translate => see screen shot
- confirmed when accessing the project on the website ... still nothing to do on any string.

### Expected behaviour
Please don't send this useless mail.

### Server configuration
https://hosted.weblate.org/projects/weblate/website/fr/
![notification received with nothing to do](https://user-images.githubusercontent.com/1452146/41708300-862241a8-7540-11e8-8707-ea1f3e87ca16.png)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
