### ISSUE TITLE
[little mail improvment] Please remove Trailing slashes in URLs

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#2094]
### Steps to reproduce
Receive an automatic mail, look at signature.

### Expected behaviour
Remove useless "/" caracter at the end of URLs
See screen shot
![trailing slash](https://user-images.githubusercontent.com/1452146/41708913-33484642-7542-11e8-93ed-e7fbdf3913fd.png)

**Comment by nijel** [comment]
Well this is how the URLs actually look like :-).

**Comment by ldmpub** [comment]
/ at the end of url are both useless and not nice in emails ;-).

For instance accessing URL https://hosted.weblate.org is working perfectly well (it refers to last arrow in above screenshot).
I would prefer to remove this ending character than managing 1 href / html attribut + 1 displayed translation label, at least for the 2 examples above.
