### ISSUE TITLE
Adding new language - no plural option

### ISSUE THREAD

**Issue by scippio** [WeblateOrg/weblate#2100]
A don't have plural option when I want add new language:
![image](https://user-images.githubusercontent.com/672903/41840475-2101f70e-7866-11e8-90bb-73201ff79310.png)

(I want add `no` Norwegian macrolanguage)

I'm using weblate/weblate:3.0.1-1 image from hub.docker.com.

```
weblate list_v 
 * Weblate 3.0.1
 * Python 3.5.3
 * Django 2.0.6
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2018.4
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2
 * Cache backends: default:RedisCache, avatar:FileBasedCache
```

**Comment by nijel** [comment]
Do you have javascript enabled? Do you see some javascript errors? This really should look like:

![screenshot-2018-6-25 add language weblate administration](https://user-images.githubusercontent.com/212189/41849733-4497b228-7882-11e8-9588-dd99f78b39a3.png)

**Comment by scippio** [comment]
I see many errors... :thinking: 

![image](https://user-images.githubusercontent.com/672903/41850178-ebd94ff0-7883-11e8-8046-10ff28484dcf.png)

**Comment by scippio** [comment]
I added
```
add_header 'Content-Security-Policy'            "script-src 'unsafe-inline';";
```
in my nginx proxy... but still have this error... :thinking:

**Comment by nijel** [comment]
Aren't you using some antivirus with transparent proxy? It might be causing this kind of errors, see https://docs.phpmyadmin.net/en/latest/faq.html#i-get-errors-about-violating-content-security-policy

**Comment by scippio** [comment]
No... I'm not using antivirus... but I'm using nginx... and this helps me:
```
        proxy_hide_header 'Content-Security-Policy';
```

**Comment by scippio** [comment]
But there is another problem... The plural definition not saved. Should I create new issue?

**Comment by nijel** [comment]
The javascript code probably detects changes (it's built in in Django), so if you don't to any changes it won't be saved. (I haven't checked this, I'm just guessing).

**Comment by scippio** [comment]
You guessing right ... I added a plural form and change plural number to 3 and it was saved! ... So I changed this back to 2 and it's finally done. ... thank you.
