### ISSUE TITLE
Asynchronous tasks

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2103]
Weblate really needs some standard way to perform tasks asynchronously in background.

Use cases:

- Fulltext index updates, currently done by queuing updates in the database and executing by cron
- Processing update hooks, currently done by forking thread to do the update
- Translation memory updates, see https://github.com/WeblateOrg/weblate/issues/1919
- Email sending, see https://github.com/WeblateOrg/weblate/issues/492 and https://github.com/WeblateOrg/weblate/issues/1046

Ideal solution would have:

- Django integration
- Rollbar integration (alternatively we might switch to self hosted Sentry)
- Scheduled tasks to perform maintenance and send digest mails
- Batch tasks to allow effective updates of Whoosh indexes (translation memory and fulltext search)
- Redis is preferred backend (database doesn't work for us as IndexUpdate table has locking issues right now)

Possible candidates:

- [TaskTiger](https://github.com/closeio/tasktiger) - lacks Django integration
- [RQ](http://python-rq.org/) and [Django RQ](https://github.com/ui/django-rq) - lacks Rollbar integration and batch updates
- [Celery](http://www.celeryproject.org/) - supports Django, lacks batch tasks, there is way to [integrate with Rollbar](https://www.mattlayman.com/blog/2017/django-celery-rollbar/)

Other suggestions welcome!

**Comment by wichert** [comment]
FWIW I use [celery](http://celeryproject.org) with redis for these kinds of things.

**Comment by nijel** [comment]
Redis will be definitely preferred backend, I'm still wondering whether to stick with Celery (and don't have batched tasks) or use TaskTiger and integrate it with Django ourselves.

**Comment by nijel** [comment]
There used to be celery.contrib.batches, but it was removed in Celery 4, see https://github.com/celery/celery/issues/3376. It now seems to be maintained at https://github.com/percipient/celery-batches

In the end I tend to prefer Celery as it's most widely used thing. It also doesn't come with limitations others have - RQ does support only platforms with fork (so Windows are not supported) and for TaskTiger we would have to implement Django integration.

**Comment by nijel** [comment]
Currently being implemented in https://github.com/WeblateOrg/weblate/pull/2187

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
