### ISSUE TITLE
msgmerge addon not merging keys

### ISSUE THREAD

**Issue by gilbsgilbs** [WeblateOrg/weblate#2107]
### Steps to reproduce
1. Create a new project with PO / POT translations from git
2. Enable `Update po files to match pot (msgmerge)` addon
3. Push new keys in the POT

### Actual behaviour
New keys don't appear in weblate interface.

### Expected behaviour
New keys should appear in the project and be ready to translate.

### Server configuration
```
 * Weblate 2.20
 * Python 3.5.2
 * Django 2.0.4
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.7.2
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2018.4
 * pyuca N/A
 * python-bidi 0.4.0
 * PyYAML 3.12
 * Database backends: django.db.backends.postgresql_psycopg2
```

I'm not sure at the moment if the keys are truly not merged at all in the PO file, of if it's just weblate that doesn't see PO files updates.

**Comment by nijel** [comment]
It seems it just doesn't show in Weblate. Use `./manage.py loadpo --all` to bring it back to sync.

**Comment by gilbsgilbs** [comment]
Thanks for taking time to reproduce.

**Comment by nijel** [comment]
Can you please check if the command I've posted helps? I'm not sure you're hitting same issue as I do (I'm testing that on current git version and something else might be broken there).

**Comment by gilbsgilbs** [comment]
Mmh, not able to reproduce this morning anymore :thinking: . Let's close until I'm able to find a way to reproduce this consistently. Sorry for the inconvenience.

**Comment by sbidoul** [comment]
Hi, I'm seeing something similar with the msgmerge addon not working.

I could observe the following with Weblate 3.3:

* msgmerge addon installed on a component
* github webhook triggered following an update of the .pot file
* git repository correctly pulled on weblate side
* msgmerge did not run
* manually running `post_update(component, None)` on the `MsgmergeAddon` updates the .po files and pushes them back to GitHub
* at this stage, translations are out of sync, running `webload loadpo` brings them back in sync

So AFAICT the msgmerge addon works but did not trigger.

I'm happy to dig into this, but I'm not sure where to look next.

**Comment by nijel** [comment]
Can you check your Celery logs if they contain some errors? Most likely there is some error in handling update and that leads to addons not being triggered. Recommended setup includes [error collection](https://docs.weblate.org/en/latest/admin/install.html#collecting-errors) to catch this.

**Comment by sbidoul** [comment]
@nijel thanks for the hint. We do have Sentry collecting errors.

The only suspicious one I see is `IntegrityError: duplicate key value violates unique constraint "trans_unit_translation_id_id_hash_ab945589_uniq"
DETAIL:  Key (translation_id, id_hash)=(58903, 4070057283307414519) already exists.`

I still need to diagnose that but it seems unrelated because when I run post_update + loadpo manually, everything gets back to normal.

**Comment by nijel** [comment]
That's not really related, I'd expect something like `Task weblate.trans.tasks.do_update[1240d20a-f929-41cb-a641-5e8ba904800c] raised unexpected: Exception(u'bug',)`
