### ISSUE TITLE
Libravatar will be shutting down on 2018-09-01

### ISSUE THREAD

**Issue by renpe** [WeblateOrg/weblate#2109]
### Expected behaviour
use gravatar as default for the avatar image

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
