### ISSUE TITLE
What file format is best for multiline translation units?

### ISSUE THREAD

**Issue by romanr** [WeblateOrg/weblate#2110]
We have Help text files (markdown format) that need to provide for translation via Weblate.
Each translation unit is a multi-line block of text formatted preserving spaces and newlines.  

What format to choose to work with these in Weblate? So far from my experience with Weblate I know know what XLIFF with `xml:space="preserve"` will work with multi-line.

Is there simpler format that will support multiline text?  

My requirements:

* No special quirks like need to add `xml:space="preserve"` for each unit
* no git pre/post commit hooks to glue lines together
* preserving spaces and newlines

Thank you.

**Comment by nijel** [comment]
I'd suggest using [po4a](https://github.com/mquinson/po4a) and gettext PO files.

**Comment by nijel** [comment]
Yes, the `\n` are treated as newlines by all tools parsing PO files.
