### ISSUE TITLE
Question: how do I prevent 100% translated when key=value ?

### ISSUE THREAD

**Issue by working-name** [WeblateOrg/weblate#2111]
I'm sorry, I did my due diligence, I searched everywhere, I googled, I can't find this anywhere. I don't know why but Weblate seems to think something is 100% "translated" when you have both key and value regardless of the failing check of them being one and the same. Yes, it does do the yellow banded bar thing but it still says 100%. Any way to match the percentage to the green portion of the bar? You know, the percentage passing all checks?

Thanks

**Comment by nijel** [comment]
Well it's 100% translated, the quality checks are just additional indicator what might worth looking at.

**Comment by working-name** [comment]
Nothing wrong with thinking that way, I just wanted to know if there's a way to customize that through the software. In my use case having all key=value means 0% translated. Only when key!=value do you actually have a translation going on. A blank value is one of your supported settings (which I can't find again to save my life), but that also means a blank site once the particular translation is selected. Hope this makes sense.

I'm currently looking into templates but python is my enemy so far. For example why is the variable `approved` only available to `progress.html` template and not `list-translations.html` which seems to call the former?

**Comment by nijel** [comment]
In most contexts there is stats object which contans all the info (eg. ``trans.stats.approved`` in ``list-translations.html``).

The problem with value == source value is that it's valid in some cases and we can't unconditionally treat these as not translated.

**Comment by working-name** [comment]
I understand that, I'm not asking you to reconsider your ways, it would be a wasted effort. I'm just using weblate for one project alone.

And `trans.stats.approved` is unfortunately incorrectly set to `0` in `list-translations.html`. It doesn't get the same value as it does in `progress.html`.

Anyway, it sounds like I have a lot of fiddling to do and this is not an option in the UI. Thanks so much for your time.

**Comment by nijel** [comment]
Well approved is most likely 0 there as well unless you've enabled review process, that's opt in feature.

**Comment by working-name** [comment]
I see, that makes sense. So what I ended up doing is moving the `<td class="percent">{{ translated }}%</td>` out of `list-translations.html` and into `progress.html` which has access to `good` and made it output the `<td class="percent">` instead. 

Thank you again.

**Comment by nijel** [comment]
True, that's value calculated in the template tag:

https://github.com/WeblateOrg/weblate/blob/253a3d8fd36ef93c510f5092995827333308969f/weblate/trans/templatetags/translations.py#L481

Anyway I think that workflow customization can be easily achieved using addon, so I'm reopening this for implementing it.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
