### ISSUE TITLE
Feature Request: Additional Row "Comments" in Overview

### ISSUE THREAD

**Issue by agaida** [WeblateOrg/weblate#2113]
###  Actual behaviour

![](http://i.imgur.com/SZns4Jf.png)

Comments are important for reviews - and should be displayed

**Comment by nijel** [comment]
Template rendering this page: https://github.com/WeblateOrg/weblate/blob/master/weblate/templates/list-translations.html

It will be probably needed to adjust the column hiding code as well:

https://github.com/WeblateOrg/weblate/blob/a51fe72de9eed74a5d150e9237482d8328c608dc/weblate/static/loader-bootstrap.js#L897-L930

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
