### ISSUE TITLE
doc: unable to understand how to use addons

### ISSUE THREAD

**Issue by glensc** [WeblateOrg/weblate#2120]
https://docs.weblate.org/en/weblate-3.0/admin/addons.html

this just shows screenshot, and then list of built in translations.

but where can i find that "addons view" in my installation? do i need to enable something first?

i'm using docker:3.0.1-4

**Comment by nijel** [comment]
It's in the Manage menu for each translation component.

**Comment by glensc** [comment]
i've cross linked the original problem: none enabled in docker version: https://github.com/WeblateOrg/docker/pull/88

**Comment by nijel** [comment]
The manage menu is there always regardless number of addons available (though its visibility depends on user permissions).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
