### ISSUE TITLE
Add verbosity to update_index

### ISSUE THREAD

**Issue by tm1000** [WeblateOrg/weblate#2130]
I'm probably being nit-picky here but due to me messing up the crontab in the docker before @nijel added crons directly into the docker made it so that none of the crons were ever running and I had index offloading enabled. So after about 6 months I had an Indexing offloading queue of 70282. 

I updated the docker image to 3.0.1 and now the crons function but I've got this huge queue to go through. I've disabled crons temporarily because update_index runs every 5 minutes and the crons are all crashing on top of each other with:

```
CommandError: Failed to acquire lock on the fulltext index, probably some other update is already running.
```

Anyways it'd be nice if
```
. /etc/profile.d/weblate.sh; /usr/local/bin/weblate update_index -v 3
```

Actually outputted some progress.. like I said. I am being nit-picky here. If I set --limit 100 then I can see it's actually decreasing the "Indexing offloading queue" from the GUI but if I let it run without that then it just sits there and I have to assume it's just going to take a while to finish..

**Comment by nijel** [comment]
Not if this is worth implementing as we're going to change way how fulltext is updated in the background, see https://github.com/WeblateOrg/weblate/issues/2103

**Comment by nijel** [comment]
The update_index command is gone as of 3f87809927941edab6f65186b0cd242cd8b68a2f.
