### ISSUE TITLE
QA check "multiple translations" triggers but none are shown

### ISSUE THREAD

**Issue by Flohack74** [WeblateOrg/weblate#2135]
### Actual behaviour
Weblate shows no further alternative translations for some of the strings, or shows the same translation across multiple projects

### Expected behaviour
Quality check should only trigger if there are really mor than one translations for the same source.

### Server configuration
Weblate 2.17

I dont know if this is because of the older version. We are now gradually updating to the latest stable. But this happens quite often, like here:

![grafik](https://user-images.githubusercontent.com/16186470/43044705-f4528240-8dab-11e8-8315-c04c088f74d4.png)

You can see the inconsistent warning, but no alternatives listed. So I cannot get rid of it at all. Also when there are 5 projects with the same translation, it will show them all, you can pick one to be used, but nothing happens.

**Comment by nijel** [comment]
I vaguely remember fixing something like this, but I can't quickly find any details right now. Anyway I believe this no longer happens in 3.0 and I've seen this in past, so I'm closing this issue as fixed in recent versions. If you happen to reproduce this again, please ask for reopening this.
