### ISSUE TITLE
Demo server reviewer account in Czech, cannot be changed

### ISSUE THREAD

**Issue by Moini** [WeblateOrg/weblate#2139]
### Steps to reproduce
1. Visit https://demo.weblate.org/
2. login as reviewer
3. Try to change interface language via user settings
4. Delete all cookies, try again

### Actual behaviour
2 -> Get interface in Czech
3 -> User settings say that the demo account cannot be edited when trying to save
4 -> Even after deleting all cookies, I still get Czech, and it even carries over to the interface after I logged out.

### Expected behaviour
Get interface in German (the weblate.org page detects my language correctly) or at least, in English.
Be able to change interface language, without that being a fixed setting of the user.
At least keep language setting confined to logged-in users.

**Comment by nijel** [comment]
The user was indeed created with Czech language, I've just changed it to rely on autodetection.

**Comment by Moini** [comment]
Děkuji :)

**Comment by Moini** [comment]
Now it's in traditional Chinese... Only deleting the cookie after logging out allows me to return to German. As soon as I log in as reviewer, I get zh-hant again.

**Comment by Moini** [comment]
@nijel I guess you don't want a new report for this ...

**Comment by nijel** [comment]
Ah, the problem is that unsetting language for user kicks in automatic setting based on user preference in browser, what is really not suitable for demo:

https://github.com/WeblateOrg/weblate/blob/567ce88f3eafcfc638c53fe390f7cf81aa973fa6/weblate/accounts/views.py#L233-L235

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by Moini** [comment]
Mmh, my browser's preference is definitely not Chinese... or did I misunderstand? It's set to German, then English. 

Anyway, when I log in now as user 'review' I get German, which is correct. Thank you! 

(Although, tbh., I prefer a selection dropdown. Then one gets exactly what one needs and doesn't have to rely on any auto-detection - especially if translations are bad. Usually, for things like these, I prefer English, so I can see what people really meant, and not some translator's interpretation of it.).

**Comment by nijel** [comment]
Somebody who has entered the user preferences had set Chinese and that was saved as a preferred language.

You can select your language when you register your own user, with demo the language selection was disabled exactly for reasons shown in this issue.

**Comment by Moini** [comment]
That hadn't worked for me with the old version - I had edited and saved the user preferences (hoping that the first dropdown is indeed the interface language preference - maybe not?)  - but saving didn't make a difference. I like to be able to switch the interface language when I see it's badly or incompletely translated. Good to know I can (somehow) do this, on a more 'real world' installation. I don't remember having any problems with that on my local install. Btw. if you can spare some time at some point, would you be able to give some info on my mailing list questions?

**Comment by nijel** [comment]
Well you are not allowed to change settings of the demo user, you should have gotten error message about that:

![screenshot_2018-08-24 user profile](https://user-images.githubusercontent.com/212189/44579010-5a321f00-a795-11e8-8970-746df2a66d06.png)

Just create your own account and it will work properly ;-).

**Comment by Moini** [comment]
Lol - yes, there was some Chinese on a yellow background... Should have made me suspicious that it was *yellow* (and not green) ;-)
