### ISSUE TITLE
Documentation: add virtualenv install as an option in Quick Install

### ISSUE THREAD

**Issue by Moini** [WeblateOrg/weblate#2140]
It would be nice to add a set of instructions for installation in virtualenv to the Quick start part. It's really just a series of quick commands, and people can do a quick local testing without messing with anything outside the virtualenv.

The reason why I'm using the virtualenv-with-pip way is because:
- I don't want to install the whole docker machinery
- I don't want to install all the dependencies system-wide, as they might interfere with other projects
- I don't want to try the development version
- I don't want to mess with my apache settings
- I just want to quickly test locally what kind of admin options are offered, as that isn't possible in the demo instance.

### Steps to reproduce

1. Follow the steps 1 to 5 in https://docs.weblate.org/en/latest/admin/install.html#installing-in-virtualenv , for reasons mentioned above
2. read step 7 - now what?

I did:
- copy /tmp/weblate/lib/python2.7/site-packages/weblate/settings-example.py to /tmp/weblate/lib/python2.7/site-packages/weblate/settings.py
- adjust a couple of values there in settings.py
- run `python /tmp/weblate/lib/python2.7/site-packages/weblate/wsgi.py`, get `django.db.utils.OperationalError: no such table: wladmin_configurationerror` (logically, as I haven't set up the database yet)
- not understand "Don’t forget to set Python search path to your virtualenv as well (for example using virtualenv = /tmp/weblate in uwsgi)." - please could you just put the command there or which file to edit, at least if it's relevant for testing? I think this isn't relevant when I'm just doing a test run, but not sure.
- run `weblate migrate`, and got `django.core.exceptions.ImproperlyConfigured: Requested setting GITHUB_USERNAME, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.`
- finally figured out the correct order of commands, fortunately I already had a bit of django experience.

### Actual behaviour

- instructions for virtualenv are not suitable for a quick start, but a virtualenv would be the perfect candidate for it.

### Expected behaviour

Quick start Instructions say something along these lines (after explaining the virtualenv setup as in https://docs.weblate.org/en/latest/admin/install.html#installing-in-virtualenv):
________________

If you just want to do a quick local test setup, to see if Weblate is for you, then:

(Insert steps 1 to 4 from above instructions)

5. Copy the file /tmp/weblate/lib/python2.7/site-packages/weblate/settings-example.py to /tmp/weblate/lib/python2.7/site-packages/weblate/settings.py
6. Adjust a couple of values in the new settings.py (are there any that are absolutely necessary? Or would it work with defaults?)
7. Run `export DJANGO_SETTINGS_MODULE=weblate.settings`
8. Run `weblate migrate`
9. Run `weblate createadmin`
10. Run `weblate runserver`
10. Open a webbrowser, go to http://localhost:8000/accounts/login/ and login with name and pw as was output by above command

### Server configuration and status

Version is 3.0.1., installed via pip in virtualenv

**Comment by nijel** [comment]
Yes it would be useful, are you willing to contribute this docs? That would be awesome.
