### ISSUE TITLE
The Hiri license is not free, nor legal

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2141]
https://feedback.hiri.com/downloads/license.txt

> Terms of Use ("Terms")
> 
> Last updated: April 15, 2015
> 
> Please read these Terms of Use ("Terms", "Terms of Use") carefully before using the Hiri  application (the "Service") operated by Whittl Media Ltd ("us", "we", or "our").
> 
> Your access to and use of the Service is conditioned on your acceptance of and compliance  with these Terms. These Terms apply to all visitors, users and others who access or use the Service.
> 
> By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.
> 
> Intellectual Property
> 
> The Service and its original content, features and functionality are and will remain the exclusive property of Whittl Media Ltd and its licensors. The Service is protected by copyright, trademark, and other laws of both the Ireland and foreign countries. Our trademarks and trade  dress may not be used in connection with any product or service without the prior written consent of Whittl Media Ltd.
> 
> Termination
> 
> We may terminate or suspend your access immediately, without prior notice or liability, for any  reason whatsoever, including without limitation if you breach the Terms.
> 
> Upon termination, your right to use the Service will immediately cease.
> 
> Limitation Of Liability
> 
> In no event shall Whittl Media Ltd, nor its directors, employees, partners, agents, suppliers, or  affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the ServiceÍ¾ (ii) any  conduct or content of any third party on the ServiceÍ¾ (iii) any content obtained from the  ServiceÍ¾ and (iv) unauthorized access, use or alteration of your transmissions or content,  whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a  remedy set forth herein is found to have failed of its essential purpose.
> 
> Disclaimer
> 
> Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express  or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, nonÂ­infringement or course of performance.
> 
> Whittl Media Ltd its subsidiaries, affiliates, and its licensors do not warrant that a) the Service  will function uninterrupted, secure or available at any particular time or locationÍ¾ b) any errors  or defects will be correctedÍ¾ c) the Service is free of viruses or other harmful componentsÍ¾ or d) the results of using the Service will meet your requirements.    
> 
> Governing Law
> 
> These Terms shall be governed and construed in accordance with the laws of Ireland, without  regard to its conflict of law provisions.
> 
> Our failure to enforce any right or provision of these Terms will not be considered a waiver of  those rights. If any provision of these Terms is held to be invalid or unenforceable by a court,  the remaining provisions of these Terms will remain in effect. These Terms constitute the  entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.
> 
> Changes
> 
> We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a  revision is material we will try to provide at least 30 days notice prior to any new terms taking  effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our Service after those revisions become effective, you agree  to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.
> 
> Contact Us
> 
> If you have any questions about these Terms, please contact us.
> 

Hiri reserves for itself copyright to original content, without CLA, and also to change the terms at any time. That is illegal, CLAs are not valid in all jurisdictions, which btw. are not governed by Irish law, as said. Specifically the license can be terminated by license at any time. There is a implied consent given here, without agreeing to anything. That is not legal with someone elses content.

The whole thing undermines all the free software on hosted Weblate.

**Comment by nijel** [comment]
Hiri is indeed not a free software (they are paying for the service) and they should specify a license properly, I will get in touch with them.

**Comment by comradekingu** [comment]
@nijel That invalidates every current translation. It also makes it impossible to advertise hosted weblate as a libre software platform.

I am not here to complain. Tell me how much they pay you and I will send you the money so that this cancer can be dropped.
The reason I use hosted Weblate and recommend it to people is because it doesn't do things like this.
Will pay per IBAN transfer.

**Comment by nijel** [comment]
The price list is publicly available: https://weblate.org/hosting/ It's not hidden anywhere - Hosted Weblate is used for both free and commercial software. Customers like this allow me to run the service, though most of them do not operate their translations publicly so it's harder to notice that they exist :-).

**Comment by comradekingu** [comment]
I have no problem with proprietary software being hidden and paying for the service.
Translation is the service, driven by translators.
Lumping in proprietary software with all libre software, without any mention, takes away my will to help build and contribute to Weblate.

Those prices are a unfunny joke compared to what commercial translation agencies pay to have things translated. I am more than happy to foot the bill to not have the good name of Weblate tarnished by illegal and cancerous practices. That goes for this and any other project.

Hoping I haven't inadvertently helped any such effort.

**Comment by nijel** [comment]
I've never advertised Hosted Weblate service as hosting for libre software only. It started for my projects only and gradually evolved into hosting platform with free tier for libre software (well not only software).

These prices are not for translating, but for hosting, usually commercial projects come with their translators who actually do the translating job. Weblate is just a service which helps them to manage the translations and push them back.

The translators should always check if the translated project license matches their preference. Everybody will draw the line somewhere else what he finds acceptable. The missing license information on Hiri was indeed an unfortunate omission, but I've already fixed that.

It might make sense to highlight OSI or FSF approved licenses, though I'm not really sure this would be good indication of anything. For example [Beerware](https://spdx.org/licenses/Beerware) license is neither of these while it is extremely permissive (yes there is project on Hosted Weblate licensed under this license).

**Comment by comradekingu** [comment]
That it has been a platform for only libre software, is a benefit in contrast to the incentive to bring on proprietary additions for profit. The libre software translation community is one more closely knit than even professional agencies. With the tools improving and additional growth, there is no reason Weblate should not be the natural platform. If it fails to make the distinction, it adopts one of the worst qualities of just about every other platform. As a translator I don't want to constantly check licenses.
It is enough for me that I am contributing towards the Weblate database corpus, helping root out errors as I go. This is predecated on all licenses being libre.
Beerware is FSF approved. ISC is too, Whereas "WTFPL" v1 I can't find info about, v2 is at-least GPL-compatible https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses
The idea of having one proprietary project branded as "commercial", is misleading. The GPL license is just as commercial, and some of the GPLv3+ projects on hosted Weblate are commercial.
However, regardless of name, doing freelance voluntary work _does not_ sign away copyright. Because that is not how copyright works in any jurisdiction I am aware of. It doesn't even work with CLA from Norwegian territory. Selling the notion that it isn't, is not a sound business plan.

To bring in more money, take my solely charitable offer, and possibly offer donation status to projects that donate towards Weblate. I have put effort towards goodwill of the sort, and am happy to keep doing so.

**Comment by nijel** [comment]
You're right that commercial name was wrong there, I've just changed it to proprietary.

As for the money, I don't think donations will work good enough. I currently spent about half-time job developing and maintaining Weblate and I need to live from something. The commercial hosting is currently the way to pay the bills for me. The current income from donations (on [BountySource](https://salt.bountysource.com/teams/weblate) and [Libeapay](https://liberapay.com/Weblate/)) is nowhere near to that.

Anyway as most of the commercially hosted projects are private they don't seem to be problematic in this regard. On the other side increasing translators community on Hosted Weblate might motivate more companies to take this approach, so it should be addressed somehow.

**Comment by nijel** [comment]
I think we should figure out some reasonable way to indicate license information in the UI to avoid such confusion. As there is more such information which might be worth displaying I've created separate issue for that, see https://github.com/WeblateOrg/weblate/issues/2194

**Comment by comradekingu** [comment]
I want a checkbox, that is enabled by default, hiding all proprietary projects.
Don't want them in the subscription list, don't want the suggestions, etc.

**Comment by nijel** [comment]
I've created separate issue for that: https://github.com/WeblateOrg/weblate/issues/2263
