### ISSUE TITLE
Source strings corruption on monolingual translations

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2144]
### Steps to reproduce

So far this has happened once on Hosted Weblate, no clear steps to reproduce. What were the steps

1. Translation was imported with English as source language
2. Turkish translation was added
3. Turkish translation was changed
4. Source string for Norwegian translation is Turkish string from 2, though probably it was changed earlier

### Actual behaviour

The source strings for one unit of monolingual translation was used from one particular version of Turkish translation.

### Expected behaviour

The source strings for all same units should match.

**Comment by comradekingu** [comment]
@nijel 
I faintly remember something like that.
Did I maybe make a comment in the English source, someone got the e-mail and started editing English thinking it was Turkish?

**Comment by nijel** [comment]
This was seen on private project once, it has never happened there again. Having other occurrence might help to track down the issue.

13. září 2018 17:11:36 SELČ, "Allan Nordhøy" <notifications@github.com> napsal:
>@nijel 
>I faintly remember something like that. What project was it?
>
>Did I maybe make a comment in the English source, someone got the
>e-mail and started editing English thinking it was Turkish?

**Comment by nijel** [comment]
Another occurence from https://github.com/WeblateOrg/hosted/issues/10:

https://hosted.weblate.org/translate/your-local-weather/strings/nb_NO/?checksum=c8fa1237ef890b5c

I am seeing 
"schwere Regenschauer", but when clicking to edit the source string, it says
"light rainshower"

Edit: When clicking [nearby strings](https://hosted.weblate.org/translate/your-local-weather/strings/nb_NO/?type=nottranslated#nearby), they are presented in English, but once clicked, seen overwritten in Norwegian Bokmål.

This suggests the source history gets overwritten when editing translated languages, as that is what happened most recently.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
@sm4rk0  The source seems correct there (it reads "Abbrev N↓, NE↙, …")
