### ISSUE TITLE
Translations Disappear

### ISSUE THREAD

**Issue by frankenfine** [WeblateOrg/weblate#2146]
Users (in the User role) will translate strings. History shows translations, however viewing the translation it remains unchanged, though the history of the string shows it as changed. Reverting from history causes the translation to stay.

This only seems to impact some languages and irregularly. Not sure how to troubleshoot.

Running version: 3.1-dev

**Comment by nijel** [comment]
There might have been change in the vcs as wel, that one is not shown in the history. Does Weblate match what is saved in the file?

**Comment by frankenfine** [comment]
Currently all disappeared translations were reverted and are now good. I'll have to wait until this happens again and check for differences.

**Comment by nijel** [comment]
I'd be really curious how this could happen as I haven't seen this so far even on quite big servers.

**Comment by frankenfine** [comment]
So the issue never popped up again. Interesting as it was a repeat issue on my end, but since reporting it, zero repeats. If it ever comes back I'll give an update
