### ISSUE TITLE
Document capabilities supported for each file format

### ISSUE THREAD

**Issue by wichert** [WeblateOrg/weblate#2148]
Not every supported file format has the same capabilities. It would be handy if the documentation indicates what features each format supports. Something like this:

| Format | Linguality | Comments | Context | Location |
| ---- | --- | --- | --- | --- |
| gettext | bi | yes | yes | yes |
| monolingual gettext | mono | yes | yes | yes |
| JSON | mono | no | no | no |
| CSV | bi | no | no | no |
| YAML | mono | ? | no | no |

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
