### ISSUE TITLE
No module named 'weblate.trans.machine'

### ISSUE THREAD

**Issue by esejuli94** [WeblateOrg/weblate#2152]
Hello, I'm getting this error when I try to access to a component. I'm using docker and the component is created for nested JSON files.

```
Request Method: | GET
-- | --
http://translate.cryptominingroup.com:8000/translate/crypto-mining-group/home/es/?type=allchecks
2.0.7
ImproperlyConfigured
Error importing module weblate.trans.machine.weblatetm in MT_SERVICES: "No module named 'weblate.trans.machine'"
/usr/local/lib/python3.5/dist-packages/weblate/utils/classloader.py in load_class, line 43
/usr/bin/uwsgi-core
3.5.3
['/usr/local/lib/python3.5/dist-packages/',  '.',  '',  '/usr/lib/python35.zip',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/usr/lib/python3.5/lib-dynload',  '/usr/local/lib/python3.5/dist-packages',  '/usr/lib/python3/dist-packages']
Mié, 1 Ago 2018 23:26:06 +0000
```

What could be the problem? Thanks in advance.

**Comment by nijel** [comment]
This should be already fixed in 3.1.1-3 version of the image (current `latest`), can you try to upgrade.

See https://github.com/WeblateOrg/docker/pull/94 and https://github.com/WeblateOrg/docker/issues/93 for more information.

**Comment by esejuli94** [comment]
I'm already using version 3.1.1. I also tried to update by using these commands:
```
docker-compose stop
docker-compose pull
docker-compose up
```
but there is no updates. So, what could I do? Thanks in advance,

**Comment by esejuli94** [comment]
These are containers I've installed.
![images](https://user-images.githubusercontent.com/1363023/43589309-b512d8e8-966e-11e8-95a7-a0775a742d3e.PNG)

**Comment by nijel** [comment]
Hmm, for some reason the latest tag on Docker Hub was not updated. As a workaround you can manually use 3.1.1-3. I will look into why that has happened later.

**Comment by nijel** [comment]
Okay, I've pushed no change 3.1.1-4 now and the latest will rebuild based on that, it should be ready in 10-20 minutes.

**Comment by leungitc12** [comment]
Thanks, it works now.

**Comment by esejuli94** [comment]
Thank you very much. It works like a charm!
