### ISSUE TITLE
Whiteboard message for specific language is shown for all languages

### ISSUE THREAD

**Issue by sotathan** [WeblateOrg/weblate#2153]
### Steps to reproduce

1. Create a whiteboard message for specific component and language.

### Actual behaviour

Message is shown in all languages of the component.

### Expected behaviour

Message is shown only at the specific language of the component.

### Server configuration and status

docker-compose run --rm weblate list_versions:
 * Weblate 3.1.1
 * Python 3.5.3
 * Django 2.0.7
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 4.0.0
 * python-dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.3.0
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Platform: Linux 4.9.93-boot2docker (x86_64)

**Comment by nijel** [comment]
The per language whiteboard indeed works only when component is not set. Should be fixed.

**Comment by nijel** [comment]
Related code is here:

https://github.com/WeblateOrg/weblate/blob/4c4ff10271b9589cbfe48781463989f884cebebf/weblate/trans/models/whiteboard.py#L32-L60

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
