### ISSUE TITLE
Sometimes Need editing flag not ON when source updated 

### ISSUE THREAD

**Issue by leungitc12** [WeblateOrg/weblate#2154]
### Steps to reproduce

1. Get contents translated and approved it
2. Source string updated but status not updated from approved to Need editing
3. Diffs not showing sometimes

### Actual behaviour

1. Source updated but component status still equal to Approved
2. Diffs not showing always

### Expected behaviour
1. Component status changed to Need Editing for all languages excepted source
2. Diffs showing every source update

**Comment by nijel** [comment]
What file format do you use?

**Comment by leungitc12** [comment]
I am using Ruby YMAL file as the source file
i.e.
```en_US: {context_10027: "This is a testing"}```

**Comment by nijel** [comment]
Just be patient, this is not 24x7 support. If you want paid support for Weblate, [there is an option](https://weblate.org/en/hosting/#self).

It looks like a bug, the approved strings are not properly marked as needing edit, only translated ones are.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by leungitc12** [comment]
Thanks for getting this fixed. I tried to upgrade it using docker-compose pull
```docker-compose pull
Pulling cache    ... done
Pulling database ... done
Pulling weblate  ... done
```
I can't see it upgraded to 3.2.

**Comment by nijel** [comment]
Weblate 3.2 is not yet released, it is scheduled to end of September, see https://github.com/WeblateOrg/weblate/milestone/36
