### ISSUE TITLE
Revive Libravatar support

### ISSUE THREAD

**Issue by ryonakano** [WeblateOrg/weblate#2155]
They [announced](https://blog.libravatar.org/posts/Libravatar.org_is_not_going_away/) that Libravatar will no longer be shutting down in September as announced before. So I suppose we can revive the support for Libravatar that have been dropped in dfa45646e4af72c8f09e3ce12e7f1ad8f3439c94.

**Comment by nijel** [comment]
Honestly I don't see much benefit in adding libravatar service as was originally supported - the federated avatar idea never really worked and most people who originally set it up forgot and it did lead to invalid URLs (I've seen lot of them even with quite small user base we have on Hosted Weblate).

Supporting Libravatar server is just mater of changing AVATAR_URL_PREFIX and there is no need for  special support for this.

**Comment by nijel** [comment]
But at least AVATAR_URL_PREFIX should be documented, what it currently is not.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
Please see https://github.com/WeblateOrg/weblate/issues/3564#issuecomment-595649477 for proposed solution
