### ISSUE TITLE
Search works for some time, then it breaks and tells me "Invalid search query" for any given query

### ISSUE THREAD

**Issue by dburner** [WeblateOrg/weblate#2160]
### Steps to reproduce

1. Search for any query in the main search (`http://weblate/#search`) for example `query`
2. The search will work and show some results
3. Wait some time (5-10mins)
4. Search again for the same thing

### Actual behavior
Search will show the message: 
```
Invalid search query!
```

### Expected behavior

Search will show the same results

### Extra details:
1. I have migrated from 2.19 to 3.0 then to latest 3.1
2. deleted /app/data/whoosh
3. ran `runuser -l  weblate -c 'weblate rebuild_index --all --clean'`
4. used docker-compose restart
5. for some time the search will work after some time it will be broken

EDIT: After some time it will work again but after a few page refreshes it will be broken again.

### Server configuration and status

Using docker-compose:

```
weblate list_versions

 * Weblate 3.1.1
 * Python 3.5.3
 * Django 2.0.8
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 4.0.0
 * python-dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.3.0
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:MemcachedCache, avatar:FileBasedCache
 * Platform: Linux 4.15.0-1018-azure (x86_64)

weblate check --deploy


SystemCheckError: System check identified some issues:

ERRORS:
?: (weblate.E003) Can not send email ([Errno -2] Name or service not known), please check EMAIL_* settings.
        HINT: https://docs.weblate.org/en/weblate-3.1.1/admin/install.html#out-mail
```

**Comment by nijel** [comment]
You should also get another error message indicating what went wrong:

![screenshot_2018-08-07 hosted weblate](https://user-images.githubusercontent.com/212189/43804075-12af30d4-9a9b-11e8-8b63-75a335fd6cd1.png)

**Comment by dburner** [comment]
No, that does not show up.

**Comment by dburner** [comment]
From what I've read from the code, I think this might be the problem.

https://github.com/WeblateOrg/weblate/commit/a15d8f6ef2c772a8f55dbc9cc821a66116c6222a#diff-30ba9e2e256bba10b6f8ef2a2d682b37

Search has a rate limit of `settings.AUTH_MAX_ATTEMPTS`, which I think it's wrong. That value is 5 so I am limited to 5 searches per 10 minutes?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
