### ISSUE TITLE
docs.weblate.org gives a bad domain error

### ISSUE THREAD

**Issue by kejiro** [WeblateOrg/weblate#2161]
It seems that readthedocs has changed to HSTS, so it might be a good idea to change all the links to point to the documentation under https://weblate.readthedocs.io instead,  or alternatively change docs.weblate.org to redirect to the readthedocs domain. 

### Steps to reproduce

go to https://docs.weblate.org

### Actual behaviour
Receiving the error message: 

> The owner of docs.weblate.org has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.
> 
> This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.
> 
> docs.weblate.org uses an invalid security certificate.
> 
> The certificate is only valid for the following names:
> ssl905239.cloudflaressl.com, *.readthedocs.io, readthedocs.io
> 
> Error code: SSL_ERROR_BAD_CERT_DOMAIN
> 

### Expected behaviour

Access the documentation.

**Comment by nijel** [comment]
Known issue, see https://github.com/rtfd/readthedocs.org/issues/2652#issuecomment-411206711. I wanted to switch to readthedocs provided SSL instead of proxying it on my servers, but the switch didn't really work. I've just reverted to the original setup.
