### ISSUE TITLE
Component Discovery addon is very slow

### ISSUE THREAD

**Issue by pvsune** [WeblateOrg/weblate#2163]
### Steps to reproduce

1. Enable component discovery addon.
2. Push a lot of translation files in Github.
3. See the component creation takes a lot of time; creation of components ~3500 translation files is still not finished after a day.

### Actual behaviour

I have a translation repository which contains translation yaml files. It contains ~3500 yaml files. After pushing it to Github, Weblate is successfully creating the components via Discovery Addon but is very slow.

### Expected behaviour

Component creation is likely a database bulk update but it seems doing a lot of things.

### Server configuration and status

```
 * Weblate 3.0.1
 * Python 3.5.3
 * Django 2.0.8
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2018.5
 * pyuca N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2
 * Cache backends: default:RedisCache, avatar:FileBasedCache
```

**Comment by nijel** [comment]
It does import all the translations. This should be done in background in future, but currently we don't have infrastructure for that.

**Comment by KixPanganiban** [comment]
@nijel Would it be simple enough to delegate these discovery processes to something like Celery? Can you point us in the right direction to get started should we want to do it ourselves?

**Comment by nijel** [comment]
Yes, something like Celery will be used for that, see https://github.com/WeblateOrg/weblate/issues/2103 for related discussion.

**Comment by pvsune** [comment]
@nijel I'm wondering what step in the import is taking too long though. If this is done by a background job, the HTTP request will just finish early isn't it? Thanks for your response.

**Comment by nijel** [comment]
It's currently not done by background job, so that's why it takes so long. It *should* be done by background job *in future*.

**Comment by pvsune** [comment]
@nijel I found that `weblate.trans.models.translation.invalidate_cache()` is what causing the creation of components to be slow (at least in my use case). I set `DEFAULT_TRANSLATION_PROPAGATION` setting to `False` and component creation via discovery addon is faster.

**Comment by nijel** [comment]
Good point, that should be done just once. I've tried to address this in https://github.com/WeblateOrg/weblate/pull/2172, but it's completely untested right now.

**Comment by nijel** [comment]
It would be great if you could test behavior with current master on your setup. There were several improvements to this and I'd like to hear how that helped in your case.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
