### ISSUE TITLE
Possible incorrect URL encoding when using auto-translate with tmserver

### ISSUE THREAD

**Issue by fdosanjuan** [WeblateOrg/weblate#2177]
I am trying to auto-translate a component by using a custom tmserver engine. Said component has a text including a slash ("/"), e.g.:

"male/female"

Whenever I click the "Process" button in the Automatic Translation form, I would get a 404 Error because the following URL does not exist:

"http://<MY_TM_SERVER>/tmserver/en/fr/unit/**male/female**"

I guess the previous URL should instead be:

"http://<MY_TM_SERVER>/tmserver/en/fr/unit/**male%2Ffemale**"

With the slash encoded.

I'm guessing it could be fixed by changing the way the url is created in /usr/local/lib/python3.5/dist-packages/weblate/machinery/tmserver.py (method: download_translations), but I'm not really sure since I'm quite new to Python.

Thank you!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
