### ISSUE TITLE
ImportError: No module named phply.phpparse

### ISSUE THREAD

**Issue by Lozik** [WeblateOrg/weblate#2178]
### Steps to reproduce

1. Install Weblate 3.0.1
2. Add a translation where Weblate needs to parse a php file

### Actual behaviour

PHP file parsing does not work and there is an error message in the "Performance overview":
Traceback (most recent call last):

>   File "/var/www/translator.belo.lu/lib/python2.7/site-packages/weblate/formats/models.py", line 50, in load_data
>     fileformat.get_class()
>   File "/var/www/translator.belo.lu/lib/python2.7/site-packages/weblate/formats/base.py", line 336, in get_class
>     module = importlib.import_module(module_name)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/var/www/translator.belo.lu/lib/python2.7/site-packages/translate/storage/php.py", line 63, in <module>
>     from phply.phpparse import make_parser
> ImportError: No module named phply.phpparse

### Expected behaviour

There should be no error message and php files should correctly be parsed.

### Server configuration and status

* Weblate 3.0.1
 * Python 2.7.13
 * Django 1.11.14
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.7.3
 * lxml 4.2.3
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2018.5
 * pyuca N/A
 * python-bidi 0.4.0
 * PyYAML 3.13
 * Mercurial 4.0
 * Database backends: django.db.backends.mysql
 * Cache backends: default:LocMemCache

**Comment by nijel** [comment]
Just install it: `pip install phply`, it's optional dependency for PHP support.

**Comment by Lozik** [comment]
Thanks for your quick answer. Unfortunately, it is already installed. As I run the command you indicated, it gives me the output "requirement already satisfied" (phply 1.2.4 and ply 3.11).

**Comment by nijel** [comment]
It is installed in the environment used by the server? Does `python -c 'import phply.phpparse'` work fine for you?

**Comment by Lozik** [comment]
I'm so sorry to have wasted your time. Effectively, this worked and the issue displayed in the "performance overview" was an old one that was not cleared. So phply was proprely installed but I thought the issue would be current, because php parsing did not work.

Now, I found out why the parsing itself did not work: the new php parser does not support array_merge() anymore. As that's the way my files were constructed (Joomla used the same system in the old days if I remember correctly). Sorry again and thanks for your assistance.

**Comment by nijel** [comment]
The old did work with array_merge? That was probably more a coincidence that intention as there was nothing for handling this. Feel free to open issue on https://github.com/translate/translate/ with more details to get that supported if there is some reasonable use case.

Anyway I'm reopening this as the errors should be removed if they are no longer valid to avoid such confusion.

**Comment by Lozik** [comment]
Yes, the old one did. The idea was to set the php array variable only if it is not yet defined. And then the new language keys would be added to the existing array. That way, you could use more than one language file having different keys and using a simple `include()`.
Okay, will do that with the issue in the translate toolkit issue tracker. I should be able to get around it but you are right, if someone needs it, it would be an idea to consider.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
Just for the record, the issue on translate-toolkit is https://github.com/translate/translate/issues/3821
