### ISSUE TITLE
utf8mb4 issue

### ISSUE THREAD

**Issue by Lozik** [WeblateOrg/weblate#2179]
As far as I can tell, the utf8mb4 issue is not yet resolved. The issue has first been documented here:
https://github.com/WeblateOrg/weblate/issues/938 and here: https://github.com/omab/python-social-auth/issues/777

A few weeks ago, I tried to install Weblate (3.0.1) again.
During installation, I got the issue that the "Specified key was too long". A long time ago, I had the same issue (Weblate 2.x.x) and used the fix using "UID_LENGTH" and "SOCIAL_AUTH_UID_LENGTH" (191 instead of 255). This time, I tried the same thing but the issue was not gone (but it had changed): "Specified index was too long".

I fixed the issue by first migrating using utf8mb4, then I stopped at the error messages, deleted the social tables manually, set the format to utf8, ran the migrations up to the point after the social plugin, rechanged the format to utf8mb4 and ran the missing migrations. However this is not an optimal way and I don't even know if everything works at this moment.

This bug needs some fixes as utf8 is not the standard for mysql and mariadb anymore. IMHO, I'd rather have a weblate without social plugins than a weblate without utf8mb4...

Here is my configuration:

 * Weblate 3.0.1
 * Python 2.7.13
 * Django 1.11.14
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.7.3
 * lxml 4.2.3
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2018.5
 * pyuca N/A
 * python-bidi 0.4.0
 * PyYAML 3.13
 * Mercurial 4.0
 * Database backends: django.db.backends.mysql
 * Cache backends: default:LocMemCache

Thanks a lot.

**Comment by nijel** [comment]
This is indeeed problem with MySQL. Their way of storing utf-8 is strange. 

To address that just set `SOCIAL_AUTH_UID_LENGTH = 191` before migrating social-auth.

**Comment by Lozik** [comment]
Unfortunately, this won't work anymore. Some versions ago, this worked but, as I stated, at this point, this won't fix the issue anymore. It changes the error message from "specified key too long" to "specified index too long", though. (At least that's what I found out) It would be nice if one could change the charset for the social plugin separately but I feel like this is not possible in the django ecosystem...

**Comment by nijel** [comment]
I've just tried that and it worked fine for me. The index there is uid + provider, where both are varchars and it works fine in my test. What was the exact error you got? What MySQL server do you use?

**Comment by Lozik** [comment]
I'm using MariaDB 10.1.26 with innodb_large_prefix ON, innodb_file_per_table ON and innodb_file_format Barracuda.
I think the issue is somewhat that the row format is not set to dynamic (or compressed).
The issue was:

> django.db.utils.OperationalError: (1709, 'Index column size too large. The maximum column size is 767 bytes.')

I can retry to reproduce the error if you want me to...

**Comment by nijel** [comment]
That really looks like there is some other column causing this or the SOCIAL_AUTH_UID_LENGTH setting was not applied.

**Comment by Lozik** [comment]
I just installed a new instance on the same server (so same MariaDB version) in virtualenv using the latest weblate version and setting SOCIAL_AUTH_UID_LENGTH to 191. I still get the same issue. All migrations are made up to the `social_django.0001_initial`:
`django.db.utils.OperationalError: (1709, 'Index column size too large. The maximum column size is 767 bytes.')`
IMHO it would be a behaviour change of mysql and mariadb when it comes to that row format.

**Comment by nijel** [comment]
Looking again at the migration, you should also set:

```python
SOCIAL_AUTH_ASSOCIATION_SERVER_URL_LENGTH = 191
```

**Comment by Lozik** [comment]
Still the same error. Unless the new config is not loaded, but using `weblate migrate` having set `DJANGO_SETTINGS_MODULE`, the new config should be automatically loaded, right?

**Comment by nijel** [comment]
Sorry, I've missed that there are two `server_url` fields in the migration and only one having index on it, so the correct variable name is `SOCIAL_AUTH_NONCE_SERVER_URL_LENGTH`.

**Comment by Lozik** [comment]
Well, migrations for `social_django.0001_initial` worked now, but there are now issues for `social_django.0003_alter_email_max_length`. (same error message)

**Comment by nijel** [comment]
That should be `SOCIAL_AUTH_EMAIL_LENGTH`.
