### ISSUE TITLE
Wrong URL for nb_NO projects

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2180]
Go to https://hosted.weblate.org/projects/andors-trail/game-content/ click Norwegian Bokmål, which is correctly added as "nb_NO", link now takes the user to not existent "nb".

Possibly related to https://github.com/WeblateOrg/weblate/issues/2051

**Comment by nijel** [comment]
Sorry, I've messed up web server setup, fixed now.
