### ISSUE TITLE
Stop listing removed projects in list of suggested projects?

### ISSUE THREAD

**Issue by petterreinholdtsen** [WeblateOrg/weblate#2188]
### Steps to reproduce

I just saw this strange behavior:

1. Visit https://hosted.weblate.org/#suggestions
2. Click on top proposal
3. Get a message stating "the project you were looking for has been removed"

### Expected behaviour

It would be better if the list of suggestions did not contain projects that has been removed.

**Comment by nijel** [comment]
The problem is that Airsonic should have been deleted, but apparenly I forgot to do that. Removing it now.
