### ISSUE TITLE
rebase fails because *~ backup files present

### ISSUE THREAD

**Issue by glensc** [WeblateOrg/weblate#2192]
### Steps to reproduce

1. `touch po/blah.po~`
2. `Manage` -> `Repository maintenance` -> `Rebase`

`Repository details` shows:

```
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	po/en_LT.po~
	po/en_LV.po~
	po/et.po~
	po/lt.po~
	po/lv.po~
	po/pl_LT.po~
	po/ru_EE.po~
	po/ru_LT.po~
	po/ru_LV.po~
	po/ru_UA.po~

nothing added to commit but untracked files present (use "git add" to track)
```

i think older weblate (2.17?) created backup files each time it edit files, and those now cause rebase to fail?

here's exception logged during error: https://ptpb.pw/7MYy

## version

`weblate/weblate:3.0.1-6` docker image

```
# docker-compose exec weblate weblate list_versions
 * Weblate 3.0.1
 * Python 3.5.3
 * Django 2.0.7
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2018.5
 * pyuca N/A
 * PyYAML 3.12
 * tesserocr 2.3.0
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache

# docker-compose exec weblate weblate check --deploy
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W018) You should not have DEBUG set to True in deployment.

System check identified 2 issues (0 silenced).
```

**Comment by glensc** [comment]
removing the `*~` from vcs directory and hitting `rebase` solved the issue.

btw, i hit `Reset` button, but that did nothing to untracked backup files

**Comment by nijel** [comment]
Do you have some addons installed? I think msgmerge could lead to this. Weblate itself definitely does not create backup files.

Repository maintenance should certainly cover this.

**Comment by glensc** [comment]
yes. `msgmerge` is enabled

**Comment by glensc** [comment]
i checked my backup, and indeed, the `*~` files were not present in 2.17 where i upgraded from. so they were created with actions made with 3.0.1

**Comment by nijel** [comment]
Okay, so it's most likely coming from msgmerge, it should be fixed in 4d15468e3a. Still there should be way to recover from this in Weblate UI.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by glensc** [comment]
in my local dev, i `git stash` before `git rebase` and later `git stash pop`

**Comment by nijel** [comment]
We don't want untracked files in the repository at all. There is no point in having them as user has no access to them.
