### ISSUE TITLE
Indicate project state to contributors

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2194]
It might be useful to indicate project state to contributors on Hosted Weblate (this probably makes no sense for private installs). This might help people to choose actively maintained projects to contribute.

* Does the project have push enabled? Without it it might take longer until translations appear upstream.
* Are there any extra commits in the Weblate repository? Extra commits might indicate nobody is taking care of merging changes.
* Project license, maybe highlighting OSI or FSF approved licenses (see #2141)
* Is the project using shared translation memory

This might be just tersely shown output from component warnings, see https://github.com/WeblateOrg/weblate/issues/2176

**Comment by burner1024** [comment]
Note that actual project license and translation license don't have to be the same, at all.

**Comment by nijel** [comment]
That's true, what we're supposed to have in Weblate is translation license (and it's called like that).

**Comment by comradekingu** [comment]
Would be nice if visually the source project was its own bar, with all the "suggested changes comments" and whatever failing upstream checks there are.
Failing to actually put in a link to the source repo or similar should also be a failing check.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
