### ISSUE TITLE
Search for short strings (including blanks)

### ISSUE THREAD

**Issue by agaida** [WeblateOrg/weblate#2196]
### Steps to reproduce

1. Notice something like "$foo :" 
2. try to search for " :"
3. merge it unchanged and use grep - search for the translations and search again in weblate :P

### Actual behaviour

Maybe i overseen something, but i'm not able to search for these things in Weblate

### Expected behaviour

I wan't to be able to search for

### Server configuration and status

current pip - all thing fine.

**Comment by nijel** [comment]
I *think* it should work with substring search (without quotes), but I'm not sure.

**Comment by agaida** [comment]
substring search seems to strip blanks - and fails if the searchstring is to small (< 3 chars)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by agaida** [comment]
Confirmed to work fine now, thanks.
