### ISSUE TITLE
regression: weblate-3.1.1 became incompatible with npn https

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#2203]
Up to weblate-3.0.1, weblate worked perfectly with npn https (proxy encrypted https; port 443 provides http that is encrypted on the proxy server). Starting with weblate-3.1.1, it gets infinite redirect only.

As a side effect, it also makes impossible to use `./manage.py runserver`.

### Steps to reproduce

1. Configure haproxy to use npn https (optional; not needed to reproduce)
2. Configure nginx to provide npn https (remove ssl keywords from port 443 records, i. e. use http on port 443)
3. Run uwsgi and weblate.

### Actual behaviour
Infinite redirect.

```
curl -i http://dhcp114:8000/
HTTP/1.1 301 Moved Permanently
Date: Tue, 28 Aug 2018 11:33:27 GMT
Server: WSGIServer/0.2 CPython/3.6.5
Content-Type: text/html; charset=utf-8
Location: https://dhcp114:8000/
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
```

### Expected behaviour
Working weblate.

### Server configuration and status
 * Weblate 3.1.1
 * Python 3.6.5
 * Django 2.0.8
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.16.4
 * Pillow 5.0.0
 * python-dateutil 2.6.1
 * lxml 4.0.0
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2017.3
 * pyuca 1.2
 * python-bidi 0.4.0
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.5.2
 * git-svn 2.16.4
 * git-review 1.25.0
 * Database backends: django.db.backends.postgresql_psycopg2
 * Cache backends: default:LocMemCache
 * Platform: Linux 4.12.14-lp150.12.16-default (x86_64)

**Comment by stanislav-brabec** [comment]
Recommended npn https setup uses http for communication between the server and npn proxy, and the server itself does not have access to the certificate. Switching the internal link to https makes no benefit.

Is it possible to recognize make SECURE_SSL_REDIRECT port based, i. e. return redirect on port 80 but not on port 443 on 8000/8080?

Alternative clean solution would be turning off SECURE_SSL_REDIRECT in weblate and configuring haproxy to implement HSTS on its side.

**Comment by nijel** [comment]
It's not about switching internal link to https, it's just about telling uwsgi that the site is being served by https.

**Comment by stanislav-brabec** [comment]
Is there a way to configure uwsgi to serve http on port 443, and backend plugins will see that as https?

**Comment by nijel** [comment]
Just use the nginx setting I've posted in https://github.com/WeblateOrg/weblate/issues/2203#issuecomment-416582792. No need to do any magic with ports.

Full example (taken from https://hosted.weblate.org/):

```nginx
        location / {
                include uwsgi_params;
                uwsgi_param UWSGI_SCHEME https;
                uwsgi_read_timeout 3600;
                uwsgi_pass unix:///run/uwsgi/app/weblate_hosted/socket;
        }
```
