### ISSUE TITLE
extreme slowdown of rebuild_index and update_index

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#2205]
After incremental upgrade of testing weblate instance from 2.18 to 3.1.1, I encountered that rebuild_index and update_index runs slower by several magnitudes.

### Steps to reproduce

1. Run rebuild_index and update_index

### Actual behaviour

In weblate 2.18 on python2:
rebuild_index: several hours
update_index: several seconds

In weblate 2.20 on python3:
rebuild_index: still several hours

In weblate 3.1.1 on python3:
rebuild_index: guessing 2 to 3 weeks
update_index: 40 minutes (it should run in cron every 15 minutes)

### Expected behaviour

No slowdown.

### Server configuration and status
    Weblate 3.1.1
    Python 3.6.5
    Django 2.0.8
    six 1.11.0
    social-auth-core 1.7.0
    social-auth-app-django 2.1.0
    django-appconf 1.0.2
    translate-toolkit 2.3.0
    Whoosh 2.7.4
    defusedxml 0.5.0
    Git 2.16.4
    Pillow 5.0.0
    python-dateutil 2.6.1
    lxml 4.0.0
    django-crispy-forms 1.7.2
    django_compressor 2.2
    djangorestframework 3.8.2
    user-agents 1.1.0
    jellyfish 0.6.1
    pytz 2017.3
    pyuca 1.2
    python-bidi 0.4.0
    PyYAML 3.12
    tesserocr 2.2.2
    Mercurial 4.5.2
    git-svn 2.16.4
    git-review 1.25.0
    Database backends: django.db.backends.postgresql_psycopg2
    Cache backends: default:LocMemCache
    Platform: Linux 4.12.14-lp150.12.16-default (x86_64)

**Comment by nijel** [comment]
There should be no change in this, but the code has been refactored in ba664080d3bbcacf83bc05208652057e32d099fe, so it's possible that some regression is there. On the other side I've recently done rebuild_index on Hosted Weblate and it took several hours, what matches your experience with older versions. I'm still on Python 2 there though.

**Comment by nijel** [comment]
I've gone through the code and I can't find any functional difference between the versions. Just to clarify: are you sure that the 2.20 tests were done on Python 3?

PS: I see you are using LocMemCache as cache backend, that is certainly not recommended for production setup, though it has no effect on index updating.

**Comment by burner1024** [comment]
Try deleting whoosh directory before rebuilding. Speeds it up by orders of magnitude.

**Comment by nijel** [comment]
`rebuild_index --clean` does exactly that :-):

https://github.com/WeblateOrg/weblate/blob/664dcdad17fc3f4bb9f8eb05af6882cf06c723aa/weblate/utils/index.py#L39-L43

Anyway running `rebuild_index --all` without `--clean` probably doesn't make much sense.
