### ISSUE TITLE
InconsistentMigrationHistory: Migration trans.0085_auto_20170406_0904 is applied before its dependency permissions.0006_auto_20170404_1637 on database 'default'.

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#2207]
### Steps to reproduce

1. install Weblate on Yunohost https://github.com/YunoHost-Apps/weblate_ynh
2. upgrade on same version

### Actual behaviour

Tell us what happens instead

```
Upgrade failed. (61)
11717 ^MExtraction des modèles depuis les paquets : 93%^MExtraction des modèles depuis les paquets : 100%
28111 Synchronizing state of postgresql.service with SysV service script with /lib/systemd/systemd-sysv-install.
28111 Executing: /lib/systemd/systemd-sysv-install enable postgresql
34244 Created symlink /etc/systemd/system/multi-user.target.wants/uwsgi-app@weblate.service → /etc/systemd/system/uwsgi-app@.service.
63157 Failed to get status information via dbus for service uwsgi-app@weblate.service, systemctl didn't recognize this service ('NoSuchUnit').
123976 WARNING:root:Python-Levenshtein not found. Continuing with built-in (slower) fuzzy matching.
124779 WARNING:root:Python-Levenshtein not found. Continuing with built-in (slower) fuzzy matching.
124779 Traceback (most recent call last):
124779   File "/var/www/weblate/venv/bin/weblate", line 11, in <module>
124779     sys.exit(main())
124779   File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/runner.py", line 33, in main
124779     execute_from_command_line(argv)
124779   File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
124780     utility.execute()
124780   File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
124780     self.fetch_command(subcommand).run_from_argv(self.argv)
124780   File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
124780     self.execute(*args, **cmd_options)
124780   File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
124780     output = self.handle(*args, **options)
124780   File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 86, in handle
124780     executor.loader.check_consistent_history(connection)
124781   File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 298, in check_consistent_history
124781     connection.alias,
124781 django.db.migrations.exceptions.InconsistentMigrationHistory: Migration trans.0085_auto_20170406_0904 is applied before its dependency permissions.0006_auto_20170404_1637 on database 'default'.
124781 !!
124781   weblate's script has encountered an error. Its execution was cancelled.
124781 !!
```
### Expected behaviour

The migration step works (whatever if it does something or not)

### Server configuration and status

Here is the code used for upgrade: https://github.com/YunoHost-Apps/weblate_ynh/blob/master/scripts/upgrade#L279

The same kind of upgrade worked fine with 3.0.1 and 2.x releases.

We enable upgrade on same version to clean up an app. If for any reason a user or system modification impacted the current installation, you can rerun upgrade to try to fix it (user rights or missing dependency).

Thanks for your help :)

**Comment by nijel** [comment]
Duplicate of #2204

**Comment by Jibec** [comment]
Thanks for quick feedback, I'm unsure to understand how to test the 3.1.1-5, will it go through pip?

**Comment by nijel** [comment]
No, it's docker only issue. So in the end this might not be the duplicate. In any case that means that you are running 3.0 code after database has been migrated to 3.1.

**Comment by Jibec** [comment]
Indeed, I'm not using docker and execute the code after an upgrade (or installation) on 3.1.1

**Comment by nijel** [comment]
Maybe there are old .pyc files kept in the migrations dir?

**Comment by Jibec** [comment]
I confirm that running the following command prior the migration doesn't change anything:

`find . -regex '.*\(__pycache__\|\.py[co]\)' -delete`

**Comment by nijel** [comment]
Can you grep your sources for the permissions.0006_auto_20170404_1637 migration (or rather just 0006_auto_20170404_1637 string)? The dependency is not there in 3.1 release, so it has to come from somewhere.

**Comment by Jibec** [comment]
Oh, I think I forgot "--upgrade" in this line: 
https://github.com/YunoHost-Apps/weblate_ynh/blob/master/scripts/upgrade#L217

Do you think it may be related?

**Comment by nijel** [comment]
I'm not really sure, what's difference when missing `--upgrade`. Anyway what is content of `weblate/trans/migrations/` directory?

**Comment by Jibec** [comment]
I think this bug is only existing in our Continous integration system, I'll wait for 3.2 to test if it happens again. I can't reproduce it out of our LXC tools (and I won't fix bugs that doesn't impact our users ;)).

**Comment by nijel** [comment]
If you reuse the checkout, I recommend doing `find weblate -name '*.pyc' -delete` after doing git pull. Some files might have been removed and the pyc files would be used instead then.
