### ISSUE TITLE
Editing source strings in Weblate logs out user doing it

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2208]
https://hosted.weblate.org/languages/en/your-local-weather/ allows editing source strings.
However, when clicking in the editor to edit a string in English (source) it logs me out, and directs to the login, complaining about too many attempts made at logging in.

**Comment by nijel** [comment]
There is rate limiting to allow 6 edits in 60 seconds, so it doesn't really matter what you edit. However it was wrongly applied even in case when user hit skip button as well.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by Ablu** [comment]
I just got logged out for the same reason twice in the past few minutes. I simply did normal translations of really simple strings which partly were 1:1 copy from source and mostly single words. So it seems to be still be a bit over aggressive maybe?

**Comment by PhiLhoSoft** [comment]
6 edits in 60 seconds?
What is the reason to slow down the workflow so much?
When all you do is to fix typos, mistakes, approximations, etc. of existing translations, it is easy to reach this limit, and this harsh logout is really disruptive, particularly if you don't remember at which translation number you were.
As said above, I can accept a modal "wait" screen (with an explicit message), but being thrown out of the app without explanations is rude and disturbing.

**Comment by nijel** [comment]
This definitely should not affect normal usage, this is just a last resort to block spamming users (we had such in last few days). So I was probably too aggressive in setting the limits here, sorry. I was thinking that 10 seconds for one string is reasonable, but apparently it's too strict.

**Comment by PhiLhoSoft** [comment]
OK, I understand now, but still it could be a bit more user friendly... :smile: 
5 s per edit seems more reasonable, and when we are aware of the limit, we can slow down.
Thanks.

**Comment by nijel** [comment]
The motivation is not to slow down regular users, they should never hit this limit :-). But apparently my assumption about 10s was wrong. If you hit this again with regular work, please let me know, I will adjust it again.

**Comment by Ablu** [comment]
thank you for the fast reaction :)

**Comment by joshuaboniface** [comment]
I'm running into this same issue with a self-hosted Weblate 3.4 under UWSGI. When I try to approve "too many" translations, I get booted out with no errors to speak of in the logs.

**Comment by nijel** [comment]
It's not available in environment variables, but you can customize anything using custom config: https://docs.weblate.org/en/latest/admin/deployments.html#further-configuration-customization

**Comment by uNitrous** [comment]
Does that happen when start new language translation in multiple projects within short period time? I also had tap skip button often to get and translate small amount of words contain strings first
Recently i added and was translation few projects to new language and now when i click to add new language in other projects then quickly log me out. it's better to display slow down mode in UI instead log out as in telegram groups

eg: |Slow down mode| You have to wait x time to perform x action
