### ISSUE TITLE
Tetris editing, show additional field below currently edited one in zen mode

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2209]
To achieve greater efficiency, it would be great if the edited field wasn't the bottommost one.
For anyone that has ever played Tetris, you get to plan ahead, because the next piece is announced, allowing one to strategize accordingly.

In Weblate, sometimes it makes sense to copy the content of the translated field to the clipboard, for use in the next field, adding minor additions. The problem becomes knowing when to.

I think two empty fields below, given enough screen-estate brings about as much benefit that can be had.

In any event editing in the middle of the screen is good for ergonomics.

**Comment by nijel** [comment]
There is enough screen-estate on full HD display, but not that much on smaller screens. Maybe this could be shown only on larger screens. Anyway you can get that in "Nearby strings" right now...

**Comment by comradekingu** [comment]
@nijel Forgot to mention this concerns the Zen-editor.
A lot of space could be saved vertically in it, but that is another matter.

**Comment by nijel** [comment]
Indeed zen mode needs some improvements, see https://github.com/WeblateOrg/weblate/issues/2022 or https://github.com/WeblateOrg/weblate/issues/2033.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
