### ISSUE TITLE
Non-git based components

### ISSUE THREAD

**Issue by wichert** [WeblateOrg/weblate#2210]
We have translatable content that is not tied to code, for example CMS-style content and email campaign content. Since weblate is a really good tool to handle translations, and are translators have experience with it we would like to use weblate to handle translations instead of trying to replicate parts of it. Currently we are doing that by automatically managing a git repository with a copy of our content, essentially doing a data-export on every change, and re-importing when we receive a webhook from github/bitbucket. I am wondering if it is possible to take out the git part of this? For example use a weblate API to directly push texts to weblate, along with a webhook from weblate so we can automatically receive updated translations or mark content as unusable if a translators flags text as needing review.

**Comment by nijel** [comment]
The biggest problem here is missing API to do all this. Implementing simple backend with not VCS integration would be quite easy.

**Comment by wichert** [comment]
The celery work you are doing would certainly be very useful for webhook delivery.

**Comment by dragosv** [comment]
@nijel What are the missing API?

**Comment by nijel** [comment]
Not yet working, but I'd like to have it for 3.3. There needs to be way to upload new files to translate, that should be exposed in the API. The current upload interface *merges* content of uploaded file into current translation.

**Comment by dragosv** [comment]
@nijel What about a File based repository instead of Source Control (Git, Hg, Svn) ? Just pushing files into a folder then running wlc push and pull? As adding a Source Control is not needed. Not sure how should this options be named.

**Comment by dragosv** [comment]
@nijel This is same concept in Pootle
http://docs.translatehouse.org/projects/pootle/en/stable-2.8.x/features/pootle_fs.html

```
What is a filesystem
A filesystem is actually itself a Pootle FS plugin. Currently two exist:

localfs - allowing synchronization with the filesystem on which Pootle is running
git - synchronization with a Git repository
You can write a plugin for any version control system, Pootle FS will ensure that the same commands and operations are used to ensure Pootle and your filesystem stay synchronized.
```

**Comment by nijel** [comment]
The wlc push and pull does push and pull from remote repository. There is no such thing for local one :-). That is really the missing part here - to implement support for replacing files by the ones uploaded (it doesn't matter whether by web or API).

I will look into this for the 3.6 release, the vcs requirement is really a blocker for some users.

**Comment by dragosv** [comment]
So why not go for a pootle like approach? I mean instead of pushing to git, put the files onto the local filesystem. Same for git pull. I am missing something?

**Comment by nijel** [comment]
There is no problem with such approach, it just needs to be implemented.

The major missing parts:

- [ ] Extend upload interface to allow to completely replace files
- [ ] Extend component creation to allow zip upload with the initial files
- [ ] Writing local vcs layer (to make implementation easier, it might be based on git internally, just not configure remotes and ignore pulls and pushes)

**Comment by nijel** [comment]
Work in progress code for this feature is in https://github.com/WeblateOrg/weblate/pull/2907

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
