### ISSUE TITLE
Hosted Weblate bug - incorrect word count for "strings with suggestions"

### ISSUE THREAD

**Issue by franconian** [WeblateOrg/weblate#2211]
### Steps to reproduce

1. Open some //hosted.weblate.org/projects/[project name]/[project component]/[language] page that contains "strings with suggestions"

### Actual behaviour

Hosted weblate doesn't show the correct number of words for "strings with suggestions". Number of words is always equal to number of strings

### Expected behaviour

The numbers should differ in almost any case like they do in other categories

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
