### ISSUE TITLE
How is id used to differentiate trans-units with same source in xlf?

### ISSUE THREAD

**Issue by wheresmehat** [WeblateOrg/weblate#2212]
In the xlf translation file there are two trans-units that have the same source for translation and need to be translated to different words in my language (grammatical gender related).
However, they have unique ids, and I was hoping Weblate would distinguish between them based on that. 
But when I use the file in Weblate I can translate only one of this trans-units, the other doesn't even appear among the strings.
So it seems that Weblate doesn't use the id attribute in the trans-unit. Is there any other way to tell trans-units with the same source apart.

The "NewUnit.FormNewUnit.Active" translation needs to be
`<target state="translated">Aktivna</target>`

The "NewDevice.FormNewDev.Active" translation needs to be
`<target state="translated">Aktivan</target>`

hr.xlf (foreign language file)
```
<trans-unit id="NewUnit.FormNewUnit.Active" approved="no">
        <note>Status menu item, active, in newUnit</note>
        <source>Active</source>
        <target state="needs-translation"></target>
</trans-unit>

<trans-unit id="NewDevice.FormNewDev.Active" approved="no">
        <note>Status menu item, active, in newDevice</note>
        <source>Active</source>
        <target state="needs-translation"></target>
</trans-unit>
```

en.xlf (source language file)
```
<trans-unit id="NewUnit.FormNewUnit.Active" approved="yes">
        <note>Status menu item, active, in newUnit</note>
        <source>Active</source>
        <target state="translated">Active</target>
</trans-unit>

<trans-unit id="NewDevice.FormNewDev.Active" approved="yes">
        <note>Status menu item, active, in newDevice</note>
        <source>Active</source>
        <target state="translated">Active</target>
</trans-unit>
```

**Comment by nijel** [comment]
Weblate should use ID properly and it works fine in my tests. What Weblate version do you use? What is your translation component setup?

**Comment by wheresmehat** [comment]
This is my xlf file setup:

```
<?xml version='1.0' encoding='utf-8'?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.1" version="1.1">
  <file original="NoName" source-language="en" datatype="plaintext" target-language="hr">
    <body>
    </body>
  </file>
</xliff>
```
The body contains all the trans-units.

en.xlf is set as Monolingual base language file and Base file for new translations.

On the translations page I have English set as source language.

**Comment by nijel** [comment]
As you have the source in both files, there is no reason to use monolingual files. That's probably reason why it doesn't work as handling of monolingual translations in xliff is a bit different (what is results of some bug reports, but those might have been wrong, but that's different topic).

**Comment by wheresmehat** [comment]
Cool! After removing the monolingual base language Weblate recognizes both trans-units. 

But now it seems that context is set wrong. NoName///FleetAdmin.NewUnit.FormNewUnit.Active instead of FleetAdmin.NewUnit.FormNewUnit.Active. 
When trying to save the translation the error is: Message not found in backend storage, it is probably corrupted.

Maybe upgrading to 2.6 will fix it. As in #1099, #939 and #1021

**Comment by nijel** [comment]
I indeed think this has been fixed in some more recent release.
