### ISSUE TITLE
Output \n as new line character in Weblate source/ target

### ISSUE THREAD

**Issue by forceunwrap** [WeblateOrg/weblate#2213]
Hey there.

We are using the `xcodebuild` CLI tool in order to export our strings into `xliff` format. Since Xcode 9.3 Apple changed something which results in having new lines as `\n` instead of new line characters and I couldn't find a way to adjust that behavior.

So the example string "Test1\nTest2" resulted in a xliff format like this:

```
      <trans-unit id="Test">
        <source>Test1
Test2</source>
      </trans-unit>
```

... and now like this:

```
      <trans-unit id="Test">
        <source>Test1\nTest2</source>
      </trans-unit>
```

Weblate *does* show new line characters for the first example, but only shows `\n` for the second.

We don't want our translators to have to take care of adding `\n` for new lines, we just want them to hit enter for new lines, just like before.

Is there a way to have `\n` in the .xliff files while showing new line characters in Weblate? Also, new target translations done using the enter key also have to be saved as `\n` behind the scenes then.

I guess this is regarding translate-toolkit, right?

Thanks

**Comment by nijel** [comment]
There are already several established ways to write newlines in the xliff files, but Apple had to invent yet another one. This is currently not supported by the [translate-toolkit](https://github.com/translate/translate) we use for parsing translation files and has to be implemented there.

**Comment by nijel** [comment]
Alternatively it could be patched on Weblate side as well, but the more I think about this, it really deserves separate file format - storing newlines as `\n` would break the file for anything else than Xcode.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by forceunwrap** [comment]
So here’s a update on this:

I’ve came up with the idea to check how the upcoming Xcode 10 (which is currently still in beta) will handle this.
Line breaks in the xliff are „real“ line breaks again, so they switched back without mentioning it again. This solves the problem as soon as Xcode 10 is being released.

**Comment by forceunwrap** [comment]
Oh you’ve just closed the issue as I was typing lol. Thanks a lot for your quick fix!

I think it might still make sense to keep the new format, as we never know when they decide to change it again. What do you think?

**Comment by nijel** [comment]
I think if they decided to abandon it, then it's for good reason (which I've mentioned in https://github.com/WeblateOrg/weblate/issues/2213#issuecomment-418375123), so I'd probably remove the format to avoid confusion.

**Comment by forceunwrap** [comment]
Alright then. Again, thanks for your quick support.
