### ISSUE TITLE
Error trying to navigate search results with an excluded user

### ISSUE THREAD

**Issue by Daniel-Tr** [WeblateOrg/weblate#2216]
Repro:
* Search a component and define a value for "Exclude changes by user". Note that this field expects the username. 
Example from the demo: https://demo.weblate.org/translate/gitlab/ce/de/?checksum=&offset=&q=&search=ftx&source=on&target=on&type=all&ignored=False&date=&only_user=&exclude_user=demo
* Clickt Next/Last/Previous/First. 
Example from the demo: https://demo.weblate.org/translate/gitlab/ce/de/?exclude_user=Weblate+Demo&type=all&offset=2 
=> Error in parameter exclude_user: No matching user found.

The url indicates that the full name of the user is appended to the exclude_user parameter, instead of the user name.

Best regards,
Daniel

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by Daniel-Tr** [comment]
That was fast, thank you very much!
