### ISSUE TITLE
Remove Dash in status legend

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#2231]
To improve readability I suggest to remove dashes in the legend for translation status => see screenshot below.
Just need to add extra space as separator.

Note: I first though these "-" were in translations themselves ... but I didn't find them.

![remove dash](https://user-images.githubusercontent.com/1452146/45324132-8a2b4180-b54d-11e8-9dc2-98310809af51.jpg)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by ldmpub** [comment]
Thanks!

Waiting to check readability of the new legend.

**Comment by ldmpub** [comment]
Hi,

Like I was "fearing", the new legend is not easy to read: please add space at the end of / after each label (colored square and label should be as near as possible).
![weblate misses some space](https://user-images.githubusercontent.com/1452146/45557375-bd1b5100-b83d-11e8-99ac-66f59e00a63b.jpg)

**Comment by nijel** [comment]
I've tried to make it better now.

**Comment by ldmpub** [comment]
Thanks a lot, display is now perfect according to me ... you can close this issue.
