### ISSUE TITLE
Add format checker for javascript ES6 template string variable

### ISSUE THREAD

**Issue by miroslavrehor** [WeblateOrg/weblate#2234]
**Is your feature request related to a problem? Please describe.**
 I am using ES6 template string syntax in javascript: `Beginning of string ${variableX} end of string`. I would like Weblate to recognize this variable-syntax.

**Describe the solution you'd like**
Extend class JavascriptFormatCheck to use a regexp matching the ES6 template string (not only standard %s etc.).

**Additional context**
If I wrote the new regexp would you please add it to the next version? Thank you.

**Comment by nijel** [comment]
Extending the check is certainly possible. If you submit the PR (preferably with tests) it will be accepted.

**Comment by nijel** [comment]
Example of adding such check can be found in https://github.com/WeblateOrg/weblate/commit/963dcc5d8460943a03ae8d1b4a58b8cd836fb0cb (landed by https://github.com/WeblateOrg/weblate/pull/2290). The most important thing is to write an regexp to extract the format strings, rest is quite easy.
