### ISSUE TITLE
Documentation doesn't include how to activate your addons

### ISSUE THREAD

**Issue by bornxbackwards** [WeblateOrg/weblate#2235]
**Describe the bug**

In the documentation, there seem to have all the steps for activating existing addons and writing new addons, however there is no mention on how make available in the web interface our own written addons.

Given the scripts are no longer working, not knowing how to replace them with custom addons just break our flow and force us to either never upgrade or change tool. We would very much like to just be able to create our own addons, however there is a hole in the documentation on how to activate our own addons.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
