### ISSUE TITLE
E-mail about new strings for translation brans all needing work as non-translated

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2236]
E-mails about new strings don't actually say how many new untranslated strings there are, and if there are many, there is no link to the actually new ones.

From the e-mail (translated from Norwegian Bokmål):
----------------
Strengs, total: | 1268
-- | --
Translated strings: | 1202 (94,7%)
Non-translated strings: | 66 (5,2%)
Strings marked for review: | 64 (5,0%)
-----------------

Actually there are 2 untranslated strings.
~~This might be an error in translation too.~~
Edit: No it isn't, this is the string https://hosted.weblate.org/translate/weblate/master/nb/?checksum=110d2f4357178c4d

https://hosted.weblate.org/translate/weblate/master/nb/?checksum=37b1bf47e4257ced is the same, without the colon.

https://hosted.weblate.org/translate/weblate/master/nb/?checksum=e542b8d7913465d8
is thematically the same.

**Comment by nijel** [comment]
We currently do not store the information about new strings, it's just flag when processing the file and there is no way to filter such strings later.

**Comment by comradekingu** [comment]
@nijel New untranslated might be a dream, however.
I flag as "Needing work" usually to keep track of upstream changes needing to happen, I don't want those to inaccurately reflect how many strings are actually "not translated", because they are.

Even if flagged because one is unsure of the spelling in ones own language, it isn't untranslated.

**Comment by nijel** [comment]
On similar topic there is also https://github.com/WeblateOrg/weblate/issues/1163. Anyway I've made the labels consistent and now the footer includes both todo and untranslated strings. 

Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
