### ISSUE TITLE
Plurals support in xlf files

### ISSUE THREAD

**Issue by wheresmehat** [WeblateOrg/weblate#2237]
How would one add plural forms to this file:

```
<?xml version='1.0' encoding='utf-8'?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.1" version="1.1">
  <file source-language="en" datatype="plaintext" target-language="en">
    <body>
      <trans-unit id="FleetAdmin.Devices.SubHeader.Devices" xml:space="preserve" approved="yes">
        <note>Text for breadcrumbs</note>
        <source>Devices</source>
        <target state="translated">Devices</target>
      </trans-unit>
    </body>
  </file>
</xliff>
```

I tried using the group tag: 

```
<group restype="x-gettext-plurals" id="2" approved="yes">
  <trans-unit id="3" datatype="plaintext">
    <source>Device</source>
    <target>Uređaj</target>
  </trans-unit>
  <trans-unit id="4" datatype="plaintext" approved="yes">
    <source>Devices</source>
    <target state="translated">Uređaji</target>
  </trans-unit>
</group>
```
But this is using the gettetxt attribute and I'm working with xlf files. 

Is there a way to use plurals in xlf so that Weblate can use the inbuilt language definitions and the translator can work on one word in all of its forms (one, two, few, many)?

**Comment by nijel** [comment]
I think if you would use *XLIFF Translation File with PO extensions*, there is standard way to store plurals. I haven't used it though...

It should look like:

```xml
<group restype="x-gettext-plurals" id="apples">
   <trans-unit id="apples[0]">
       <source>I have no apples</source>
   </trans-unit>

   <trans-unit id="apples[1]">
       <source>I have one apple</source>
   </trans-unit>

   <trans-unit id="apples[n]">
       <source>I have <g id="1">count</g> apples</source>
   </trans-unit>
</group>
```

**Comment by wheresmehat** [comment]
Ok, I added the `<group restype...` to my file. 
Weblate doesn't recognize that the trans-units are in the group, it just shows them as separate translations. I never get the fine grained control of plurals as in [https://docs.weblate.org/en/latest/user/checks.html](url).

What does _XLIFF Translation File with PO extensions_ actually mean? Do I need to change the File format in the Django admin panel for the component. Or is this still a XLIFF Translation file but I have to format it differently for this to work?

**Comment by nijel** [comment]
Yes, that needs to be selected in the admin panel.
