### ISSUE TITLE
User name was changed to Full name.

### ISSUE THREAD

**Issue by kyotarozzz** [WeblateOrg/weblate#2238]
Repro:

Example from the demo: https://demo.weblate.org/translate/gitlab/ce/en/?type=suggestions#history
Luca is full name. User name is Idx.
Luca Profile : https://demo.weblate.org/user/ldx/

Same problems : Suggestions, Comments, History

Best regards,
Kyotaro

**Comment by nijel** [comment]
Maybe I'm still sleeping in the morning, but I fail to see what is wrong, can you please clarify?

**Comment by nijel** [comment]
Username is used for login and in URLs, full name was always the thing which should be displayed.

**Comment by kyotaro-iijima** [comment]
Oh I see.

Best Regards
Kyotaro
