### ISSUE TITLE
Search who translates the same language

### ISSUE THREAD

**Issue by kyotarozzz** [WeblateOrg/weblate#2241]
Reason :
1. I want to know how many people translate the same language.
    And who is it?
   
2. I also want to specify the range of the period.

Solution :
1. Display the number of translators in the same language in "Translation status".
    And, click on the number of translators to display a list of translators of the same language.
    Next to the name of a person, how many translations were made.

2. Add start and end of period to search function.

Best Regards
Kyotaro

**Comment by comradekingu** [comment]
Sounds like this could build some community.

Is this potentially a GDPR issue though? Right now you can effectively work it out by amalgamating [the history](https://hosted.weblate.org/changes/) which goes back (at present) 5 years.
To the contrary, the [language specific history](https://hosted.weblate.org/languages/nb_NO/#history) only goes back a month.

Would be nice with the statistics and info-page the whole platform has for every language. For Norwegian Bokmål we have an IRC-channel, and a dictionary.

**Comment by comradekingu** [comment]
Sounds like this could build some community.

Is this potentially a GDPR issue though? Right now you can effectively work it out by amalgamating [the history](https://hosted.weblate.org/changes/) which goes back (at present) 5 years.
It is also possible to search for [language specific history](https://hosted.weblate.org/languages/nb_NO/#history)

Would be nice with the statistics and info-page the whole platform has for every language. For Norwegian Bokmål we have an IRC-channel, and a dictionary.

**Comment by nijel** [comment]
Tthe history for nb_NO is short because of changing the language codes (see https://github.com/WeblateOrg/weblate/issues/2051), you will find rest of the history under nb. We currently do no history pruning.

**Comment by kyotaro-iijima** [comment]
Okay, I understand.

Best Regards
Kyotaro

**Comment by nijel** [comment]
You can use history to look for these: https://hosted.weblate.org/changes/?project=weblate&lang=cs&action=2

We probably could add language filtering to user listing (https://hosted.weblate.org/user/), but that will certainly not have the period.
