### ISSUE TITLE
Repository branch is too short

### ISSUE THREAD

**Issue by tibormarchynzoom** [WeblateOrg/weblate#2243]
Hi,

"Repository branch" field accept just 50 chars, please increased to at least 256 chars. We are using longer branch names than 50 chars and are unable to use branches.

Thanks

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
