### ISSUE TITLE
Invite email for admin generated user accounts

### ISSUE THREAD

**Issue by tibormarchynzoom** [WeblateOrg/weblate#2246]
**Is your feature request related to a problem? Please describe.**
When open registration are disabled and admin is creating user accounts, even mail server is configured, no invite email is sent. 

**Describe the solution you'd like**
As an admin I would like to have option that people will receive invite email and will be able to generate their own password or temporary password is delivered and they will be forced to change it after first login.

**Describe alternatives you've considered**
Alternative 1 - user will have just password reset link in email and they will create password their-self
Alternative 2 - user will have temporary password in email and is forced to changed it upon first login.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
