### ISSUE TITLE
In cs_CZ language plurals are badly handled

### ISSUE THREAD

**Issue by tibormarchynzoom** [WeblateOrg/weblate#2247]
**Describe the bug**
When importing PO files from GIT with SIMPLIFY_LANGUAGES as disabled, string is badly handled and causing plural exception.
Exception message: "unexpected token in plural form: ("

**To Reproduce**
1. Import PO file which contains following string

#: str_calls_type
msgid "Media type (file name)"
msgstr "Typ média (souboru)"

2. Weblate badly handling translation as it thinks its plural, but it's not "(s"
3. When translated string is fixed to "Typ média \\(souboru)" then it's imported correctly.

**Expected behavior**
Weblate shouldn't consider "(s" as plural as there are not finished brackets

**Server configuration and status**
_**weblate list_versions**_
 * Weblate 3.1.1
 * Python 3.4.9
 * Django 2.0.8
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.9.5
 * Pillow 5.2.0
 * python-dateutil 2.7.3
 * lxml 4.2.4
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * pyuca 1.2
 * python-bidi 0.4.0
 * PyYAML 3.13
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Platform: Linux 3.10.0-862.el7.x86_64 (x86_64)

_**weblate check --deploy**_
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.

System check identified 1 issue (0 silenced).

**Comment by nijel** [comment]
This is really not the plural form, are you sure this is the problematic part of the po file?

**Comment by nijel** [comment]
I've reproduced this when `Plural-Forms` header contained invalid expression.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
