### ISSUE TITLE
Handle integer values

### ISSUE THREAD

**Issue by diesl** [WeblateOrg/weblate#2252]
**Is your feature request related to a problem? Please describe.**
I have a Rails Project where a translation value is of type integer. Weblate does only seem to support values of type string. This leads to errors in the whole component.

**Describe the solution you'd like**
It would be nice if Weblate could handle values of type integer (or in general, type "number")

**Describe alternatives you've considered**
Of course, a solution is to make the value a string and cast it later in code, but in some cases the program expects an integer and can't be changed. My particular problem is the value of [number.format.precision](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/locale/en.yml#L46) in Rails' Active Support

**Additional context**
Error message
> We don't handle these values:
> Type: <class 'int'>
> Data: 2
> Previous: number->currency->format->precision

**Comment by nijel** [comment]
Are these really translatable and do you expect translators to change these? This particular value looks more like application/user settings than something localization should address.

Anyway since 6c5e37569aa5d23d030ec294ed92f7f481dfc5ad Weblate will load and save such values as strings.

**Comment by diesl** [comment]
Thank you for your quick response 👍 

Well, you are of course right that it is more an application setting and not that important to appear in the translation process. But it is part of of the locales nonetheless, got added as part of the component discovery and therefore it would be nice if weblate can handle it.

I am not sure if it is the best idea to change the type as part of the translation process, I would try to preserve the type when saving. A string would not help in my case, but at least the file could translated without an error then.

**Comment by nijel** [comment]
The problem is that inside Weblate we do not have any idea of value type - everything is considered a string. So the idea was to be able at least parse such files, while saving will have some side effects.

**Comment by nijel** [comment]
The other reason for this behavior was that yaml happily interprets yes/no/true/false as boolean and people tend to write these into yaml translations without quotes. Turning these into strings will make things work as expected. So my preference would be to keep it as it is right now without complicating the code for this special case.
