### ISSUE TITLE
https://hosted.weblate.org/legal/privacy/ not translatable

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2253]
Would be nice to have this localized.
It can still link to the English source as the authoritative version.

**Comment by nijel** [comment]
I've intentionally kept the legal documents not translatable. I'm not sure if it makes sense to crowdsource translation of legal documents - it can easily happen that there will be mistake and that would be confusing for users. Especially with strict regulation like GDPR...

**Comment by comradekingu** [comment]
I think not confusing users tips the scale towards translation into a language the users can understand _especially_ since it is technical language.
Doing so helps root out mistakes in the source, which I don't assume to be free of mistakes.

Legally speaking, if you say one version is authoritative, the translated one is just for reference.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed, the documents are now open for translation at https://hosted.weblate.org/projects/weblate/hosted/.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
