### ISSUE TITLE
Include language codes in discovery preview

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2258]
**Is your feature request related to a problem? Please describe.**
It is easy to create discovery rule which wrongly matches language.

**Describe the solution you'd like**
The preview should list language codes next to matched files.

**Comment by comradekingu** [comment]
Sounds like this could build some community.

Is this potentially a GDPR issue though? Right now you can effectively work it out by amalgamating [the history](https://hosted.weblate.org/changes/) which goes back (at present) 5 years.
To the contrary, the [language specific history](https://hosted.weblate.org/languages/nb_NO/#history) only goes back a month.

Would be nice with the statistics and info-page the whole platform has for every language. For Norwegian Bokmål we have an IRC-channel, and a dictionary.

**Comment by nijel** [comment]
It seems you wanted to comment on something different? Anyway the history for nb_NO is only month because of changing the language codes, you will find rest of the history under nb. We currently do no history pruning.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
