### ISSUE TITLE
Add number of uploaded screenshots statistic in user profile

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2265]
https://hosted.weblate.org/user/kingu/ does not have uploaded screenshots, or number of translation memory entries.
No count for uploaded strings, or uploaded translation memory, but i suspect those just count towards the total.

**Comment by Naruto0** [comment]
Hi @nijel, screenshots are bond to Project or User model?

Thanks in advance!

**Comment by nijel** [comment]
Number of uploaded screenshots is attribute of user profile:

https://github.com/WeblateOrg/weblate/blob/63c8db307e5a4ec66601dd5adbf91f5c9588637b/weblate/accounts/models.py#L309

**Comment by Naruto0** [comment]
Should I also make translation_memory an attribute to profile, or should i just compute it in views.py and hardcode there? 

Thank you in advance!

**Comment by nijel** [comment]
IMHO it's better to display current amount of strings in the memory for the user. Still I'm not sure this is useful thing to display here. Anyway the code for this is already there in the translation memory storage and is used in the user translation memory view...

**Comment by Naruto0** [comment]
I assume user is different from profile.. at least regarding current view

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
