### ISSUE TITLE
Windows compatibility and tests

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2267]
Weblate should work pretty much fine on Windows. It would be great to have this covered by tests. There are currently tests running on AppVeyor, but there are some test failures which should be addressed. These might be both problems with AppVeyor setup or code issue. Best way to figure out is probably to reproduce the issues in local Windows build.

Besides others, there is some problem with parsing po files:

```
weblate.formats.ParseError: Invalid file format <translate.storage.pypo.pofile object at 0x081AC110>
```

See https://ci.appveyor.com/project/nijel/weblate for current build status.

**Comment by Naruto0** [comment]
Hi @nijel 

It seems that windows cannot handle symbolic link, which in this case is `xx.po`. I am in the middle of solving another issue, which is dependent on this.
Do you have any idea, how to resolve this?

**Comment by nijel** [comment]
We might just skip this particular test, it doesn't make sense to test behavior the platform does not support.

**Comment by nijel** [comment]
One important thing to note here is that Celery no longer officially supports Windows, see https://docs.celeryproject.org/en/stable/faq.html#windows. We should probably make similar statement.

**Comment by nijel** [comment]
I don't see enough interest in making Weblate work on Windows. Patches for it are always welcome, but I'm not going to invest any time into that besides reviewing pull requests. This is properly documented since 399dd5c.
