### ISSUE TITLE
Source strings only show common strings between all locales, cannot attach screenshots to strings not present in all locales

### ISSUE THREAD

**Issue by wjdp** [WeblateOrg/weblate#2272]
**Describe the bug**
Using gettext bilinguial if you have several locales with a variable number of source strings (i.e. 3 locales with 900 strings and 9 with 200) only the common 200 show in the "source strings review" section.

In addition the 700 strings not present cannot have screenshots attached. Clicking the pencil on a string not in "source strings" shows the message "No matching source strings found.". When searching for strings to add to a screenshot these strings cannot be found in the "Assign source strings" panel.

You also cannot set context, flags or string priority on these strings.

**To Reproduce**
1. Add gettext translations with variable number of source strings
2. Find that not all strings are present in "Source strings review"

**Expected behavior**
All source strings should be able to have screenshots attached.

**Screenshots**
![image](https://user-images.githubusercontent.com/1690934/46032233-f3d15100-c0f2-11e8-8c9f-ec3c30edad49.png)

![image](https://user-images.githubusercontent.com/1690934/46032431-84a82c80-c0f3-11e8-8a0b-e8b403ecb5dc.png)

**Server configuration and status**
```
docker-compose exec weblate weblate list_versions

 * Weblate 3.1.1
 * Python 3.5.3
 * Django 2.0.8
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 4.0.0
 * python-dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.3.1
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Platform: Linux 4.15.0-1019-aws (x86_64)
```

**Comment by nijel** [comment]
You're right, the code is built with assumption that all translations have same strings. It picks one of the translations to search for a string and if that doesn't contain it it fails. This should be improved.

**Comment by wjdp** [comment]
As a workaround is it possible to select which translation it picks? If I can do this it would solve the issue for me.

**Comment by wjdp** [comment]
The uploading of the images isn't the problem.

What I need to do is tell Weblate to look at the English PO file to find the complete list of source strings. What does this logic look like in the code, does it just find the language with the lowest ID in the database?

**Comment by wjdp** [comment]
@nijel Sorry to bother, but could you point me in the right direction? I'm hoping there's an easy workaround for this. If not could you indicate where in the code I should start looking. Cheers! :smile:

**Comment by nijel** [comment]
The problematic code is in several places, it picks up first translation and lookups units in that only. Quickly I was able to find following locations, but the list doesn't have to be complete:

https://github.com/WeblateOrg/weblate/blob/cac31c4df7931a5db8ebe712274df3a16fce4227/weblate/screenshots/views.py#L214-L217

https://github.com/WeblateOrg/weblate/blob/cac31c4df7931a5db8ebe712274df3a16fce4227/weblate/trans/views/source.py#L227

https://github.com/WeblateOrg/weblate/blob/cac31c4df7931a5db8ebe712274df3a16fce4227/weblate/trans/views/source.py#L243

https://github.com/WeblateOrg/weblate/blob/cac31c4df7931a5db8ebe712274df3a16fce4227/weblate/trans/views/source.py#L49-L52

What it should do instead is join over `Source` models where we already track all source strings within a component.

**Comment by Kingdutch** [comment]
It feels like we're running into this same problem. We extract translations into a en.pot file and then translate them to a nl.po file. However any strings that we add to the en.pot file don't show up in Weblate (probably because they're not in the nl.po file). We would expect Weblate to automatically keep the .po file up to date with these new source strings.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
