### ISSUE TITLE
Some machine translation services fail silently when project source language is set to "English (United Kingdom)"

### ISSUE THREAD

**Issue by wjdp** [WeblateOrg/weblate#2273]
**Describe the bug**
Some machine translation services fail silently when project source language is set to "English (United Kingdom)". I've tried Google Translation API and MyMemory. Nothing is printed in the stdout console and the ajax calls on the machine translation tabs return empty with 200 status codes.

**To Reproduce**
1. Create a project with en_GB set as language
2. Add google translate API
3. Note nothing happens on the 'Machine Translation' tab

**Expected behavior**
en_GB should co-erce to whatever English the translation services require perhaps with an error or warning.

**Screenshots**
With en_GB the machine translation section looks like this:
![image](https://user-images.githubusercontent.com/1690934/46092580-12941e00-c1ad-11e8-956e-4f6dbb0b7ad0.png)

**Server configuration and status**

```
docker-compose exec weblate weblate list_versions

 * Weblate 3.1.1
 * Python 3.5.3
 * Django 2.0.8
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 4.0.0
 * python-dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.3.1
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Platform: Linux 4.15.0-1019-aws (x86_64)
```

**Comment by nijel** [comment]
Probably none of the services supports en_GB, we should probably fall back to en in that case...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
