### ISSUE TITLE
Add Apertium's engine to Weblate

### ISSUE THREAD

**Issue by asereze** [WeblateOrg/weblate#2279]
**Is your feature request related to a problem? Please describe.**
Sometimes having machine translation for the strings could be useful, even if just as a reference.

**Describe the solution you'd like**
It would be nice to have Apertium's engine added to Weblate, like it seems like it is on OmegaT for some supported languages (for ex. Sardinian, the one I translate to). Unfortunately I don't really know how that works or if it's really possible.

**Comment by nijel** [comment]
It's already supported, see https://docs.weblate.org/en/latest/admin/machine.html#apertium

**Comment by asereze** [comment]
Oh, so it's up to the project administrators to enable them? Ok, I didn't know, thank you very much for the information!

**Comment by nijel** [comment]
Yes, it's just matter of configuration (and running Apertium APY in this case).
