### ISSUE TITLE
Possibility to import the translation memory in formats different from TMX and JSON

### ISSUE THREAD

**Issue by asereze** [WeblateOrg/weblate#2280]
**Is your feature request related to a problem? Please describe.**
I have some translation files in .po format that I don't know how to convert in tmx or json (every time I tried it seems like it didn't work, for some reason I don't know) and I would like to import them in the translation memory.

**Describe the solution you'd like**
It would be great to have the possibility to import files into the translation memory in formats different from TMX and JSON, and also to be able to export in other formats, like Xliff and xml, like it's possible to do for single translations.

**Comment by nijel** [comment]
TMX is standard file for translation memories, JSON is Weblate specific format. The translation memory will most likely have more than one language and thus it's not really possible to store in translation file formats which typically support only one translation.

For importing it should be possible, though you would have to specify languages which the file uses as it's in most cases not stored in it.

**Comment by gersona** [comment]
@nijel What additional formats should be supported for memory imports ? It makes sense to only allow files with bilingual format, but should they all be included ?

**Comment by nijel** [comment]
I think using `weblate.formats.auto.try_load` could be the way to handle all Weblate-supported bilingual formats. I'd prefer to avoid having a format-specific code here.
