### ISSUE TITLE
Possibility to get suggestions from other projects in github

### ISSUE THREAD

**Issue by asereze** [WeblateOrg/weblate#2281]
**Describe the solution you'd like**
Launchpad seems to have a way to suggest translations using a TM generated automatically from strings in various github projects. For example, when translating Ubuntu programs I get suggestions from Exaile, a media player that I translated in Sardinian some time ago using not Launchpad but Weblate. I don’t know how they got those strings automatically in their translation memory. Adding something like that (if it's even possible, maybe they just got the translation files some other way) to Weblate would be a great thing, since it would allow us to get a lot more useful suggestions.

**Comment by nijel** [comment]
Doing this automatically is problematic license wise, there would have to be per license TM. There is now opt in shared translation memory in Weblate, so it will work like that for future translations.

**Comment by comradekingu** [comment]
@asereze [Until 2014](https://launchpad.net/exaile/+announcement/12937), Exaile used Launchpad, so it might have handled translations there too? Nontheless an interesting idea.

**Comment by comradekingu** [comment]
Maybe tag this for a future milstone?

**Comment by nijel** [comment]
I don't see any easy way to address licensing issues here. Also my time is pretty much booked for next release.

**Comment by nijel** [comment]
The only way to get around licensing is getting an explicit consent. And in that case, I believe that something like https://github.com/WeblateOrg/weblate/issues/3561 or https://github.com/WeblateOrg/weblate/issues/3749 would be a better solution than ad-hoc suggestions from other GitHub projects.
