### ISSUE TITLE
Selecting string from navigation bar breaks filtering

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#2282]
**Describe the bug**
Selecting a number of string switches to all strings mode

**To Reproduce**
1. Go to 'Translation component'
2. Click on 'Strings needing action'
3. At the top bar select the navigation scale (Numbers)
4. After selecting a string number and clicking OK all the strings appear without filtering

**Expected behavior**
I would expect the filtering to remain the same unless I asked for something else.

**Additional context**
When showing all strings it doesn't matter.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by yarons** [comment]
Wow, that's insane, thank you so much.
