### ISSUE TITLE
Invalid XLIFF conversion (missing id in trans-unit)

### ISSUE THREAD

**Issue by acalvo** [WeblateOrg/weblate#2283]
**Describe the bug**
When you download a translation in XLIFF (converted from another format), the generated file does not comply with the specification, as `trans-unit`s do not have the mandatory `id` attribute.

**To Reproduce**
1. Go to the official demo: https://demo.weblate.org/projects/gitlab/ce/es/
2. Click on Files -> Download translation file as XLIFF... (either of them)
3. Check that the downloaded file doesn't comply with [XLIFF 1.1 specification](http://www.oasis-open.org/committees/xliff/documents/xliff-specification.htm)

**Expected behavior**
Every `trans-unit` in the downloaded XLIFF file should have an `id` attribute filled with a unique value.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
