### ISSUE TITLE
SPAM by suggestion

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2284]
https://hosted.weblate.org/translate/debian-edu-documentation/audacity/nb/?checksum=cc3a3b8aeba83df4

Maybe putting these behind a CAPTCHA would solve matters?

I think it comes down to the invidiual mod to delete it, which isn't about to work out.

**Comment by nijel** [comment]
We're using [Akismet](https://akismet.com/) to filter anonymous suggestions. It doesn't filter 100% of spam, but it isn't that annoying as Captcha. I've just gone through all anonymous suggestions done in last two weeks and these two seem the only ones spammy, so I'd say it still maintains quite good rate of rejecting spam. There seems to be increased amount of spam coming in - the Akismet service did block quite a lot of suggestions in pas weeks (yesterday 30% of tested suggestions were spam).

PS: I've just deleted these the two suggestions.

**Comment by comradekingu** [comment]
https://hosted.weblate.org/translate/debian-edu-documentation/audacity/nb/?checksum=cc3a3b8aeba83df4#suggestions

**Comment by comradekingu** [comment]
https://hosted.weblate.org/translate/debian-edu-documentation/audacity/nb/?checksum=cc3a3b8aeba83df4
https://hosted.weblate.org/translate/debian-edu-documentation/audacity/nb/?checksum=cc3a3b8aeba83df4

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed (Weblate now supports reporting spam back to Akismet, what should make the repeated spam as seen here harder to pass through again).

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
