### ISSUE TITLE
Base file should allow value even if not used

### ISSUE THREAD

**Issue by netniV** [WeblateOrg/weblate#2285]
When creating/saving a component based on PO/POT files, you can set the Base file only if you are allowing weblate to add new translations.  There may be a reason to not initially allow this but configure the base file for use later so that it is as simple as turning the flag on.

**To Reproduce**
1. Add a component
2. Set PO based info (file mask, base file, etc)
3. Set New Translation to `No adding of language` (which should probably read Do not add new langauges)
4. See `Base file for new translations is not used because of component settings. You probably want to enable automatic adding of new translations.` reported twice (once at base file and once at new translation)

**Expected behavior**
This should maybe be a warning (once) but it should allow the preset of the field

**Screenshots**
![image](https://user-images.githubusercontent.com/9052188/46335901-f7983280-c620-11e8-8c6a-7699ff644672.png)

![image](https://user-images.githubusercontent.com/9052188/46335910-041c8b00-c621-11e8-9597-3d1a64d3994c.png)

**Comment by nijel** [comment]
The reason for this error is that it often lead to mistake that people forgot to enable adding of new languages. But since adding new languages is default, it might make sense to remove this check...

**Comment by netniV** [comment]
Yeah, like I said, better a warning than an error.  If I had saved it with No add without the base set (which I was going to), later when I changed it back, I would have been surprised so then the warning would be useful.  But in this case, I was setting it as I knew it, and it stopped me continuing just because I hadn't set add automatically.  That didn't seem right so I reported it.

**Comment by nijel** [comment]
This error probably should be turned into a warning as described in #2176.

**Comment by nijel** [comment]
Downgrading this certainly makes sense, once we have the warnings code in, I'll convert it.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
