### ISSUE TITLE
Disable punctuation checks for Lojban

### ISSUE THREAD

**Issue by giqtaqisi** [WeblateOrg/weblate#2286]
Lojban (ISO 639-3 code `jbo`) does not use the punctuation marks `!`, `?`, `:`, or `…`. It does use the character `.`, but not to indicate the end of a sentence. For this reason, the following checks should be disabled for Lojban:

- `EndStopCheck`
- `EndColonCheck`
- `EndQuestionCheck`
- `EndExclamationCheck`
- `EndEllipsisCheck`

**Comment by nijel** [comment]
It's easy to add per language exceptions, there are already some:

https://github.com/WeblateOrg/weblate/blob/0b2a4d7b737b9f213e0a6b111d8a493f7df6d181/weblate/checks/chars.py#L128-L130

**Comment by gchan1** [comment]
Hey! I would like to try to take this issue :)

**Comment by nijel** [comment]
You're welcome, feel free to ask if you have any questions :-)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
