### ISSUE TITLE
Move post_migrate signals to AppConfig.ready

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2288]
Currenly we register post_migrate signals in models and that makes it impossible to receive signal only from one app (as there is no app instance available in the models.py). This leads to code where first line is always if checking which app has been migrated:

https://github.com/WeblateOrg/weblate/blob/03392f7b087edd03287e0eabc538bb7ce6686844/weblate/lang/models.py#L336-L341

The desired registration could look like:

```python
class MyAppConfig(AppConfig):

    def ready(self):
        post_migrate.connect(signal_handler, sender=self)
```

**Comment by Brunux** [comment]
Hi @nijel I think I can refactor this will PR when ready

**Comment by nijel** [comment]
You're welcome to contribute!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
