### ISSUE TITLE
What is the best method of installation for production?

### ISSUE THREAD

**Issue by romanr** [WeblateOrg/weblate#2292]
In documentation it is not really clear - is virtualenv  method of installing Weblate recommended in general or  only for those who want to play around with it temporarily?   

> This is recommended method if you don’t want to dig into details.

So "don't dig into details" - means you want to have it "guaranteed to just work" or "get it running no matter what, quickly" ?  
Confusing that documentation suggests installing into /tmp/weblate which looks like not a good idea for something non-temporary.   

I've been using Weblate for some years under Debian with pip, however if you stop upgrading Debian to next major release, after some time python libraries drift in version comparing to what's required by Weblate. and you no longer able to upgrade Weblate. Maybe some OS is better suited, is it Debian or CentOS?  

What is the best case environment for Weblate?

**Comment by nijel** [comment]
The install documentation really should get some updates, patches are welcome :-).

What I think:

* If you don't need to customize the code, the first recommendation would be to use Docker.
* Using virtualenv is otherwise preferred as that way you can easily upgrade libraries needed by Weblate without interfering with rest of the system.
* The path for virtualenv in the examples should be really moved from `/tmp/`.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by romanr** [comment]
I have some follow-up questions for documentation:

### 1

```
virtualenv ~/weblate-env
. ~/weblate-env/bin/activate
```
Is this supposed to be run by root user, will virtualenv require privileged permissions?  Or it's recommended to create `weblate` user?

### 2

```
# Debian/Ubuntu:
apt install libxml2-dev libxslt-dev libfreetype6-dev libjpeg-dev libz-dev libyaml-dev python-dev

....

pip install Weblate
# Optional deps
pip install pytz python-bidi PyYAML pyuca
```

In commands there's no Mysql or Postgres -specific packages.
Is it installed in `apt-get` stage or `pip install` stage? and which package required for Postgres and Mysql?

in "Installing with Pip" chapter there is an example of that:

```
# For PostgreSQL
apt-get install python-psycopg2
# For MySQL on Ubuntu (if using the Ubuntu package for Django)
apt-get install python-pymysql
```

is this valid for virtualenv method?

**Comment by nijel** [comment]
I've added pip instructions to the docs. You can create virtualenv under user as well.
