### ISSUE TITLE
Wrong percentage in translated progress bar

### ISSUE THREAD

**Issue by padorg** [WeblateOrg/weblate#2298]
**Describe the bug**
The start of a new translation for a language without a "basefile for new translations" sets the progress bar to 100% green. 
After saving a translations for a string, the progress bar shows the correct progress.

Same behavior if a basefile is specified.

**To Reproduce**
1. Add a new translation
2. Check the progress bar
3. Translate one string and save
4. Check the progress bar

**Expected behavior**
After adding the language the progressbar should show the correct progress.

**Screenshots**
Language: 
![image](https://user-images.githubusercontent.com/43959391/46610516-46573800-cb0b-11e8-9ce3-748fa7b1509d.png)
Details:
![image](https://user-images.githubusercontent.com/43959391/46610559-5f5fe900-cb0b-11e8-84f5-a37252bcc87a.png)
Missing string:
![image](https://user-images.githubusercontent.com/43959391/46610587-756da980-cb0b-11e8-9b9c-72d216851765.png)
Add a string and save:
![image](https://user-images.githubusercontent.com/43959391/46610616-85858900-cb0b-11e8-8b62-eef61a0430c0.png)
Correct progressbar:
![image](https://user-images.githubusercontent.com/43959391/46610630-8f0ef100-cb0b-11e8-82cf-0f67216f4dea.png)

The same if a base file is specified: 
![image](https://user-images.githubusercontent.com/43959391/46611182-53752680-cb0d-11e8-95a5-14149c03f96d.png)
After editing and saving a string: 
![image](https://user-images.githubusercontent.com/43959391/46611202-6851ba00-cb0d-11e8-94da-19e9ce4a0015.png)

Progress bar also doesn't update correct if a string is added to the base file. Red color isn't displayed correct. The progress bar shows free space instead of the color.
![image](https://user-images.githubusercontent.com/43959391/46611879-5c66f780-cb0f-11e8-9fec-5d151cd590fe.png)

**Server configuration and status**

Using docker-compose:

```
docker-compose exec weblate weblate list_versions:
 * Weblate 3.2
 * Python 3.5.3
 * Django 2.1.2
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 4.0.0
 * python-dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.3.1
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postg
 * Cache backends: avatar:FileBasedCache, defa
 * Platform: Linux 4.9.116-1.ph2-esx (x86_64)

docker-compose exec weblate weblate check --deploy:
System check identified no issues (0 silenced).

**Comment by nijel** [comment]
Actually the progress without red part is correct, it's just named a bit confusingly, see https://github.com/WeblateOrg/weblate/issues/2240

**Comment by padorg** [comment]
Thanks for your fast reply. 
The second case occurs when a developer adds a string to the language base file, so if the unit is added in the vcs.
Is the fix already available in the current Docker image?

**Comment by nijel** [comment]
Not yet, there will be soon 3.2.1 release including this fix.
