### ISSUE TITLE
Option "Base file for new translations" should be required filed

### ISSUE THREAD

**Issue by alesrosina** [WeblateOrg/weblate#2302]
**Describe the bug**
When creating component with translations, you can also enable adding new languages. If you leave "Base file for new translations" filed empty, you can add new languages, but will always be "greeted" with "No string matched your search!" when trying to translate for that language. Also indicator for that language is not correct, since it shows status "Approved", where it should show "0% translated".

**To Reproduce**
Steps to reproduce the behaviour:
1. Create/use git repo with available translations
2. Create new component in admin UI, filling only required fields and leaving default fields as is
3. Go to application and to newly created component - click "Start new translation", select a new language and confirm selection
4. Click on "Translate" for that language
5. Detail page for this language is shown with a message "No string matched your search!"

**Expected behavior**
 Field "Base file for new translations" should be required when creating component.

**Server configuration and status**

```
* Weblate 3.2
 * Python 3.5.3
 * Django 2.1.2
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 4.0.0
 * python-dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.3.1
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Platform: Linux 4.9.93-linuxkit-aufs (x86_64)
```
```
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Can not send email ([Errno -2] Name or service not known), please check EMAIL_* settings.
	HINT: https://docs.weblate.org/en/weblate-3.2/admin/install.html#out-mail

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.

System check identified 5 issues (0 silenced).
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa22341dea0>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa22341dea0>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```

**Additional context**
I'm running it in debug mode, since this is not production build. Also error regarding SSL and email - I am aware of it and for current test setup is this something I do not need, therefore ignored.

**Comment by nijel** [comment]
What file format do you use? In many formats it's valid to create empty translation files what Weblate does in this case (eg. Android strings resources).

**Comment by alesrosina** [comment]
For this demo I tried `.po` files and structured json files
```
{
"CATEGORY": {
  "SUB_THING": "Translation for this."
  }
}
```
Both with same result. 
And yes, when I checked commits, empty file was created, but I cannot add new translations.

Maybe this is actually intended behaviour?

**Comment by nijel** [comment]
This is default behavior for monolingual translations (what is what you seem to be using). The translations will be added once the string is translated.

Anyway this topic is covered by our docs: https://docs.weblate.org/en/latest/formats.html#adding-new-translations

**Comment by alesrosina** [comment]
Thanks for the answer! As it seems, it is only me not understanding the workflow :)

So what would be a use case for adding a language, but not able to translate one?

**Comment by nijel** [comment]
You should be able to translate in the UI, it's just the file is empty as many tools do not expect to get non translated keys.

**Comment by alesrosina** [comment]
But how can I translate? That's the thing I wrote in initial bug report - I got a message "No string matched your search!" when trying to translate.

Or is this something wrong with my setup? I'm using `weblate-docker` for running it locally.

**Comment by nijel** [comment]
That certainly looks wrong. What is setup of your translation component?

**Comment by alesrosina** [comment]
All default values, except git source url and a file mask.

Can you reproduce the steps, if you follow the steps I've initially posted?

**Comment by nijel** [comment]
Okay, if you're using monolingual transaltions and not having template file, then it will probably not behave as expected, but the validation should reject empty base for new langs with adding languages enabled.

**Comment by alesrosina** [comment]
Yes, exactly. But the validation does not kick in for that filed, so that was my initial report of a bug.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
Anyway what you want in your case is to set `Monolingual base language file`.

**Comment by alesrosina** [comment]
Perfect, thank you very much!

I think this was one of the fastest fixes of reported bug I have encounter! 🎉 

And yes, you are correct, `monolingual base language file` is actually what I need.

Again, thanks for this fast response!
