### ISSUE TITLE
Max length for sources no translated is 0. I cannot add a string so I cannot translate it.

### ISSUE THREAD

**Issue by dabit1gamma** [WeblateOrg/weblate#2303]
**Describe the bug**
Using monolingual translations, imagine that a developer add a new key in the code `home.greetings`. Then this key should be translated from the translator using weblate to its real string, for instance `Hello user!`. But this is not possible due when he goes to weblate the `maxlength` attribute from the textarea is 0.

**To Reproduce**
1. Add a new key to the POT file (base file for new translations)
2. Go to weblate and translate this key in the source language
3. You will realise that you cannot since maxlength is 0

**Expected behavior**
No attribute maxlength for source translations

**Additional context**
Weblate 3.1.1

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has been already fixed for the 3.2 release by 373847c010b3bb958d828cde86a788ae15fc0ac8.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
