### ISSUE TITLE
Commit message on merge, can't I edit it?

### ISSUE THREAD

**Issue by dabit1gamma** [WeblateOrg/weblate#2304]
When I press the button `manage > commit` it generates the next commit message: `Merge branch 'origin/master' into Weblate`. The thing is that I need to control the commit messages in order to say to TravisCI that it does not have to execute many tasks that are not necessary like tests. In component settings I can edit some commit messages but I don't know how to control that message.

Is it possible? Or is something that weblate should add as a feature?

Thanks,
David

**Comment by nijel** [comment]
In older versions this commit message is generated by Git, in recent versions it's done by Weblate because of merge ordering (see #1797):

https://github.com/WeblateOrg/weblate/blob/0327a99dc358a51c7e7bae21588d689cdb2989cf/weblate/vcs/git.py#L142-L146

It probably could be customized though.

**Comment by dabit1gamma** [comment]
@nijel don't you think would be better if it could be customized from Admin panel? For CI systems is really necessary to be able to control commit messages. In my case I need it in order to add "[no checks]" in every commit from weblate to say to TravisCI that it shouldnt trigger tests since it is not necessary when we just translated some strings. Also editing this source file I think is not a good idea.

**Comment by nijel** [comment]
I think it makes sense to make it configurable in a similar way as other messages - configurable per component with installation wide defaults.

**Comment by dabit1gamma** [comment]
@nijel nice, I'm not a python developer otherwise I would create this feature :(

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
