### ISSUE TITLE
URL to documentation in API is wrong and html tags are displayed

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#2311]
Hi,

when logged as admin on https://translate.holcroft.fr/api/projects/fedora-docs-homepage/repository/

I see:
`See <a href="https://docs.weblate.org/en/weblate-3.1.1/apiprojects.html">the Weblate's Web API documentation</a> for detailed description of the API`.

The correct link should be: https://docs.weblate.org/en/weblate-3.1.1/formats.html

The link should work, here, the html is displayed as text.

Screenshot:
https://screenshots.firefox.com/eONlb2YOIDZQ9CO8/translate.holcroft.fr

Thanks for your help!

**Comment by nijel** [comment]
The not rendered link is caused by old django-rest-framework, recent version render it properly.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by Jibec** [comment]
Thank you :)

After reading again the link, I think it should be corrected too.

I think it should point to api.html instead of apiprojects.html
-- 
Jean-Baptiste Holcroft

**Comment by nijel** [comment]
It should link to api.html#projects, that's what I've fixed in  e94bb89

**Comment by Jibec** [comment]
Perfect, thanks
