### ISSUE TITLE
Configurable language names when creating translations

### ISSUE THREAD

**Issue by ieugen** [WeblateOrg/weblate#2313]
This is mostly a question, to clarify some details regarding language tags. Languages on disk are saved with the posix language format like  `en_US` instead of the language tag format used in web and all new modern tools `en-us`. 

Can we switch to this format. This is also to establish a common format since new added languages are added with the language tag. 
Example: 

We have some translations that cover a specific region of the world like: Eastern Africa. 
According to the language tag specification [1], I can define a language specific to that region like `ar-014` [2].  

I've defined such a language and it seem to work after I put in the proper plurals (manually copied from arabic).

[1] https://www.w3.org/International/articles/language-tags/ 
[2] https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

```
Type: region
Subtag: 014
Description: Eastern Africa
Added: 2005-10-16
```

**Comment by nijel** [comment]
You can save the files in any format, Weblate will recognize that just fine (both `en_US` and `en-us` will be treated same). For creating, currently POSIX format is used for most file formats (AFAIK the only exception is Android where different scheme is used).

The regional codes are currently not defined in Weblate, but still should work fine.

**Comment by ieugen** [comment]
Thank you. Any hints on how to upgrade Weblate to use language tags by default? Both database and files. Would a rename + sql upgrade to the trick?

**Comment by ieugen** [comment]
Thank you, I'll do that but it does make management harder, since starting new translations will use the POSIX format for translations. This makes automating the import impossible/difficult. 

A workaraound would be to have a script that renames all `_` to `-` via script and run that as part of weblate or as part of a cron job, but it would be a pain.

**Comment by nijel** [comment]
There is already method for reformating language codes in such case:

https://github.com/WeblateOrg/weblate/blob/760018c452cc01489f00e4c784486e6778a4d934/weblate/formats/base.py#L557-L560

It is already used by several formats where there are clear platform requirements on the language code (Android, OSX, Windows RC files). There is just no generic configuration for this.

The plurals are copied when the language is created automatically (when Weblate first imports such translation), but not in the admin interface.

**Comment by ieugen** [comment]
Thanks. I don't see how we can apply this (code patch) and still do upgrades via docker. It's going to be a maintenance burden. 

I can think of some alternatives, but all fail short on maintainability.
1. Build docker image locally and copy a patched `ttkit.py` file over.

I think an hourly cron job that renames the files is better for this.

**Comment by nijel** [comment]
I think it should be made configurable in some way per component.

**Comment by nijel** [comment]
> Feature proposal: It might be nice to copy the plurals from the base language when creating new languages since plurals don't change IMO.

Implemented in d7217eec22ce8a792eaea0850329e40ec1ea3b28, this is clearly better approach than the one chosen in #2242.

**Comment by ieugen** [comment]
Hello,

It seems Weblate does not support he language tag format when working with files. 

i've renamed all of them with this script and the components dissapeared. (Weblate 3.2.2). 

The workaround is to update our code to work with the `xx_YY` format when we import. 

```
#!/bin/bash

DIR=$(pwd)
echo "Rename directory $DIR"

for i in $( ls -d ./*/ ); do
  echo "Renaming files in $i"
  cd $i
  rename 's/\-/\_/' *
  cd ..
done
```

**Comment by nijel** [comment]
If the components disappeared, it's most likely caused by no longer matching discovery rules. Weblate does not delete components otherwise. So check the discovery addon setup, maybe the regexp there is too strict and no longer matches after this change.

**Comment by ieugen** [comment]
I agree. However, we decided not to go against weblate on this and updated our apps to use the underscore version for locale. Let's home we don't run into exotic languages pretty soon :).
