### ISSUE TITLE
Increased Character limit in language list field for project

### ISSUE THREAD

**Issue by lo-gun** [WeblateOrg/weblate#2314]
**Is your feature request related to a problem? Please describe.**
This feature is required when someone needs to pass the language list of more than 200 characters. where the regex takes space of up to 4 characters.

**Describe the solution you'd like**
Increase the input size of the language list field which can support more languages to be added for translation in a particular project.

**Comment by nijel** [comment]
You mean for language regexp? There is no reason to use that unless you want to restrict languages imported into Weblate, what doesn't seem to be the case with 200 languages...

**Comment by lo-gun** [comment]
Yes the languages has to be restricted to 65 languages on project and that has to be taken from the repo itself, where the po files for the languages are already defined with some already translated terms.

And it is 200 char length of the field and not 200 languages.

**Comment by nijel** [comment]
Right, but still listing 65 languages is far from optimal and hard to maintain. What is reason for not importing all of them?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
