### ISSUE TITLE
Adding Arabic Tatweel and related Tatweel check

### ISSUE THREAD

**Issue by BoFFire** [WeblateOrg/weblate#2315]
Hi,
Arabic Tatweel U+0640 and related tatweel letters are decorative letters and usually does not pass spell checking and are useless in a translation and pollute TMs. Can we add a *check* for them to inform users to avoid using them ?

http://graphemica.com/%D9%80
Something like in : https://hosted.weblate.org/checks/
Regards,

**Comment by nijel** [comment]
So this char should not be used at all? Can you please post some reference on that?

I've just quickly checked translations on Hosted Weblate service and it's used in 314 translations right now.

**Comment by nijel** [comment]
Thanks for adding more detailed information! I think such check certainly makes sense, it should be easy implement, there is similar check for zero width space which could be used as a inspiration:

https://github.com/WeblateOrg/weblate/blob/de272e64cf5ab4bfe80c02df0fca9e4d238581e4/weblate/checks/chars.py#L336-L346

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by mhmdanas** [comment]
I was about to open an issue, but then I found this.

Anyway, I believe the check is too aggressive. There are occasions where Kashida is useful, such as when a preposition that is supposed to be linked with a word is followed by a colon (meaning the preposition applies to all the items that follow); it looks very awkward without one.

> I think that this section of the RFC should be applied in all translation plateforms. 

I don't see why restrictions on Arabic letters in domain names should apply to typical prose and translation strings.

**Comment by nijel** [comment]
It could be definitely improved, somebody with language knowledge should describe how it should behave. Preferably in a separate issue.
