### ISSUE TITLE
Add all ar_xx as RTL languages

### ISSUE THREAD

**Issue by BoFFire** [WeblateOrg/weblate#2316]
Hi,
The actual list for RTL languages in Weblate includes :

`# List of RTL languages
RTL_LANGS = set((
    'ar',
    'arc',
    'ckb',
    'dv',
    'fa',
    'ha',
    'he',
    'ks',
    'ps',
    'ug',
    'ur',
    'yi',
))`
We can include all regional ar_DZ, ar_MA, ar_xx (generic) as RTL, they are RTL :)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by BoFFire** [comment]
Thank you :)
