### ISSUE TITLE
XLSX import causing errors

### ISSUE THREAD

**Issue by mlaggner** [WeblateOrg/weblate#2317]
**Describe the bug**
If you download the translations as XLSX, edit it in Excel and try to upload it again, the upload ends in the error
`File content merge failed: could not convert string to float: 'location'`

**To Reproduce**
1. Go to a language inside one of your translation component
2. Click on 'Files' -> 'Download translation file as Excel Open XML'
3. Excel: Edit an existing translation in Excel into another value
4. Weblate: Click on 'Files' -> 'Upload translation'

**Expected behavior**
The changed translation should be uploaded

**Server configuration and status**
list_versions:
* Weblate 3.2.1
 * Python 3.5.3
 * Django 2.1.2
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 4.0.0
 * python-dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * pyuca 1.2
 * PyYAML 3.12
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Platform: Linux 4.4.114-94.11-default (x86_64)

check --deploy:
WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

**Comment by nijel** [comment]
I can not reproduce this on 3.3, it seems to work just fine for me.

**Comment by mlaggner** [comment]
would it help if I send you (confidential) XLSX where the error occurs on 3.2?

**Comment by nijel** [comment]
That might help, please send it to michal@cihar.com, thanks!

**Comment by nijel** [comment]
Thanks for providing that. I figured out that this happens only on Python 2 due to different CSV module being used there.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by mlaggner** [comment]
can confirm that the commit works on 3.3 via patching the installation!
Thanks
:+1:
