### ISSUE TITLE
Send e-mail about new resources in subscribed projects

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2323]
I am subscribed to gnumdk, who puts projects into this "metagroup" of his.
I never knew about the recent addition of "[Passbook](https://hosted.weblate.org/projects/gnumdk/passbook/#information)" till I clicked around and found it that way.

For other projects, new components could go unnoticed I imagine.

**Comment by nijel** [comment]
I guess this is duplicate of #1956...

**Comment by comradekingu** [comment]
@nijel No I'm pretty sure this is a mental problem on my part. Closing.
