### ISSUE TITLE
Rights management is missing flexibility

### ISSUE THREAD

**Issue by Flohack74** [WeblateOrg/weblate#2325]
**Is your feature request related to a problem? Please describe.**
Currently it is unclear, at least to me, how to easily manage user rights assignment based on multiple roles, e.g.:
* Our project does not have qualified coordinators/reviewers for each language
* Therefore, new users joining are in the group of Users, and are allowed to translate on all languages.
* As soon as we got enough QA guys ready (we have this now for Spanish and French e.g.), I want to add a group "Spanish Translators", with those people inside
* The translators group gets Translate, Review, and Add suggestion roles for all projects and all Spanish language flavors
* Now comes the tricky part, how to remove Translate rights from all normal users for all Spanish flavors only? I cannot configure this in the group editor. It is also kinda impractical to add all remaining users manually into a new group
* Suppose the new group is there (Suggestion rights only for Spanish flavors), will it override the old Translate rights (means does the most strict rights assignment win)

As I currently see it I cannot add multiple rules/rights to a group or user, like be translator here, but suggestor only here.

**Describe the solution you'd like**
I see kinda "reduced ACL" technique here. A real ACL would allow positive and negative statements, with negative ones probably overruling positive ones. Plus the m:n relationships are not fully configurable as such, it would probably need ACL on the objects (languages, projects, components) rather than having this only on groups and users

**Describe alternatives you've considered**
Bear with me if this was implemented after 3.01 in a similar way that I can use. We are continously upgrading our Weblate in production and will eventually arrive at the latest stable :)

The alternative to a full blown ACL system would be to at least be able to assign multiple positive and negative roles (forbidden rights) to a group, so that I can lockdown Spanish globally without having to touch all users somehow.

**Comment by nijel** [comment]
The negative permissions were intentionally not included as that has caused serious problems and inconsistencies in previous implementation (see https://github.com/WeblateOrg/weblate/issues/1798 for discussion).

What you can do right now is remove "All languages" selection from the `Users` group and remove languages you want to manage manually from it. Then it will no longer interfere with per language groups you create. The only drawback is that you have to add new languages once they appear (though this should be quite rare as Weblate comes with definitions for most of the languages).

**Comment by Flohack74** [comment]
Ok so you mean this:
![grafik](https://user-images.githubusercontent.com/16186470/47041273-acd1fb00-d188-11e8-8f6b-d7a9427053b3.png)
So that means that "Users" group has now "Power user" rights for all project and languages except Spanish. But how to give them "Add suggestion" now for only Spanish? This I dont get....

**Comment by nijel** [comment]
You need to create separate group for that.

**Comment by Flohack74** [comment]
Ok and then add all users via SQL to the new group? Because via interface its not really possible...

**Comment by nijel** [comment]
Just define automatic assignment rule same as for Users group.
