### ISSUE TITLE
Nelson is CLA-ware, without any disclaimer or waiver.

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2326]
https://cla-assistant.io/Nelson-numerical-software/nelson.

Also, this has no legal bearing if signed on Norwegian territory.

**Comment by Nelson-numerical-software** [comment]
Hi,

Nelson is a long term project. I (as main developper) need to have the possibility to  re-licensing easily (GPL3 or LGPL3) without to ask to others contributors.

Do not hesitate to contact me directly if you need more informations.

Thanks for your interest about Nelson

**Comment by comradekingu** [comment]
@Nelson-numerical-software Long running projects like the Linux kernel seem to do just fine without. https://news.slashdot.org/story/14/01/20/2158221/linus-torvalds-any-cla-is-fundamentally-broken
The FSF, of which license you employ, are against it. CLAs garner about as much positive feedback as CoCs do, which I regrettably see you also have. My thoughts on that particular one, [here](https://github.com/WeblateOrg/weblate/pull/2257).

The good news is you can in fact license it GPLv3 all you like, without any CLA.
https://github.com/Nelson-numerical-software/nelson/blob/92355155e38d7b00ce4d9c79a83742d231ae42c2/.gitignore#L8

If you just additionally want to make it LGPL, you can dual license it GPLv* and LGPL, though you need to trust the legality and the coverage of the CLA, and prepare for the inevitable backlash. You can then do away with the CLA.
Contributing anything to a project that holds the door open to proprietary relicensing isn't welcoming. Thank you for your consideration.
