### ISSUE TITLE
Always show language selection for search

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2328]
Going through Tools>Search on https://hosted.weblate.org/languages/nb/weblate/
you get language specific choices right away.

Through https://hosted.weblate.org/projects/weblate/master/nb/#search no language specific choices. If the search has no hits, the user is back here: https://hosted.weblate.org/projects/weblate/master/nb saying there are no hits.

Only _after_ having searched for something from https://hosted.weblate.org/projects/weblate/#search
the user is presented with language specific choices:
↓
![skjermbilde pa 2018-10-17 05-35-58](https://user-images.githubusercontent.com/13802408/47060602-8cc52a80-d1ce-11e8-9ed1-228ac57c8a30.png)

I would prefer that the language specific choices were always available.
Additionally it would be great if making a search always results in the same behaviour, but that might be a separate issue.

**Comment by nijel** [comment]
The language selection should be there if it makes sense - if you are searching from scope which already has defined language, it doesn't make sense to show it as it's already defined. Apparently it's not the case as it's shown in https://hosted.weblate.org/languages/nb/weblate/#search, where anyway the results are only from one language.

**Comment by comradekingu** [comment]
@nijel I think it makes sense to always show language options, because then it is apparent what is going on. Also it allows for the choice of (always) selecting different languages. This way search always behaves the same, and the user need not be mindful of where the search was started from.

Additionally, sometimes a search that returns nothing lands you back at the string overview, sometimes it takes you right back to the search.

**Comment by mohit741** [comment]
Hello @comradekingu I want to try. Can you please give me pointers on how should I proceed? 
p.s - First timer

**Comment by comradekingu** [comment]
@mohit741 I would imagine finding and comparing one to the other, then send a PR with the change.

I don't know if we agreed on the scope, but I would argue it doesn't matter where the user is, but rather what the user wants to do. I.e. not waste resources for both user and server on a search known to be fruitless.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
