### ISSUE TITLE
Note: GitHub Services are being deprecated. Please contact your integrator for more information on how to migrate or replace a service with webhooks or GitHub Apps.

### ISSUE THREAD

**Issue by arpinarula** [WeblateOrg/weblate#2330]
**Describe the bug**
Getting the error "Note: GitHub Services are being deprecated. Please contact your integrator for more information on how to migrate or replace a service with webhooks or GitHub Apps." under services

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to "https://github.com/TeamMavericks/Happinessrepo/settings/installations"
2. Click on "Integrations and services"
3. Scroll down to Services

**Expected behavior**
"Add service " button should be present

**Screenshots**

**Server configuration and status**
Please paste the output of `list_versions` and `check --deploy` commands over
here. Depending on installation these can be executed in different way, please
consult https://docs.weblate.org/en/latest/admin/management.html for more
details.

On Git checkout:

```
./manage.py list_versions
./manage.py check --deploy
```

Using docker-compose:

```
docker-compose exec weblate weblate list_versions
docker-compose exec weblate weblate check --deploy
```

**Additional context**

**Comment by nijel** [comment]
The documentation already covers using webhooks:

https://docs.weblate.org/en/latest/admin/continuous.html#github-setup

There is also GitHub App, which you can use instead. It should work fine for notifications, it is still not used for pushing the changes though. See https://github.com/WeblateOrg/weblate/issues/1688 for more details.
