### ISSUE TITLE
 <?xml version='1.0' encoding='UTF-8'?> should use " not ' for quotes

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#2333]
**Describe the bug**

Weblate converts the XML header  `<?xml version="1.0" encoding="UTF-8"?>` to ` <?xml version='1.0' encoding='UTF-8'?>`, i.e. it changes `"` double quotes which are standard in XML to single quotes `'`, which are not standard.

**To Reproduce**
See the source file:
* https://gitlab.com/fdroid/fdroidclient/blob/master/app/src/main/res/values/strings.xml

Versus all the translation files:
* https://gitlab.com/fdroid/fdroidclient/blob/master/app/src/main/res/values-sk/strings.xml

**Expected behavior**

The XML header should just be copied, not modified.

**Server configuration and status**

On _hosted.weblate.org_.

**Comment by nijel** [comment]
Closely related to https://github.com/WeblateOrg/weblate/issues/1886

**Comment by nijel** [comment]
Sure done, just ping me when something else should be included in the list.

**Comment by nijel** [comment]
This is hardcoded in the xml library:

https://github.com/lxml/lxml/blob/d5c69a40df483ed60e75ebcb27e493c51e10873d/src/lxml/serializer.pxi#L271-L285

So probably the only way to workaround that is to avoid using output from the library like in https://stackoverflow.com/a/47132033/225718

**Comment by nijel** [comment]
Addressed in https://github.com/translate/translate/pull/3840

**Comment by eighthave** [comment]
what do you think about doing a pull request to lxml to fix that?

**Comment by eighthave** [comment]
it seems that both ' and " are valid in XML, but by convention, " is the
standard:

* https://en.wikipedia.org/wiki/XHTML#XML_declaration
* https://xmlwriter.net/xml_guide/xml_declaration.shtml
* https://www.tutorialspoint.com/xml/xml_declaration.htm
* https://developer.mozilla.org/en-US/docs/XML_introduction
* https://msdn.microsoft.com/en-us/library/ms256048(v=vs.110).aspx
* https://stackoverflow.com/questions/6800467/quotes-in-xml-single-or-double

**Comment by nijel** [comment]
Certainly its possible to attempt to fix it there, but I felt more comfortable to address it in the translate-toolkit. My expectation that changing behavior which library has for ages would not be easy to push.

**Comment by eighthave** [comment]
I did one: https://github.com/lxml/lxml/pull/277

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
