### ISSUE TITLE
runtests.py missing from PyPi

### ISSUE THREAD

**Issue by jtojnar** [WeblateOrg/weblate#2334]
I am trying to package weblate for NixOS but cannot run tests because the PyPI package lacks them.

See also the Debian thread about the issue:
https://lists.debian.org/debian-python/2016/04/msg00074.html

```
runtests (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: runtests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: runtests
Traceback (most recent call last):
  File "/nix/store/s3nl02c26303mfjvaaxnc19f8ks9hc8c-python3-3.6.6/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'runtests'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>

```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
