### ISSUE TITLE
Billing and uwsgi hanging out for Gitlab auth

### ISSUE THREAD

**Issue by BoFFire** [WeblateOrg/weblate#2336]
Hi,
I tried to activate billing and adequate roles for a group of users. Everything was fine, a community user can create projects and components depending on the FOSS Plan assigned.

Until I tried to add by mistake a component based on a private Gitlab repo. In the background, uwsgi displays a `prompt for authentication`, which is normal but seems that this blocked all Weblate.

Is there any workaround to tell this `simple translator` that this is a **private repo** and process to `timeout uwsgi` to allow other users to continue translation ?
Regards,

**Comment by nijel** [comment]
The git process is executed with own stdin, it really should not use uwsgi stdin. Also I've done this several times and it never waited for the prompt. Anything custom in your setup what could lead to this?

**Comment by BoFFire** [comment]
I'll try to reproduce the issue tonight.

**Comment by nijel** [comment]
This probably depends on Git version, I've seen this recently as well.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
