### ISSUE TITLE
URL_PREFIX is not used when commit_pending is invoked by cron task

### ISSUE THREAD

**Issue by SlavekB** [WeblateOrg/weblate#2338]
**Describe the bug**
We have a Weblate instance installed on our server for our project and we use `URL_PREFIX`. At the web interface, everything works as expected.

When sending a commit is invoked by cron task or manually in the CLI, the URL specified in the commit log and the URL listed in the PO file header does not contain `URL_PREFIX` and are therefore invalid.

**To Reproduce**
1. Have a Weblate instance that uses `URL_PREFIX`.
2. Make some translations.
3. Invoke the cron task for commit_pending.
4. Notice that the translation team's URL is bad both in the commit log and in the PO file header - do not contain `URL_PREFIX`.

**Expected behavior**
I expect that `URL_PREFIX` will be used in all outputs so that the URLs will be valid.

**Server configuration and status**
Weblate is installed in virtualenv using pip.

$ weblate list_versions
 * Weblate 3.2
 * Python 2.7.13
 * Django 1.11.15
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 5.2.0
 * python-dateutil 2.7.3
 * lxml 4.2.5
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * pyuca 1.1.2
 * PyYAML 3.12
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Platform: Linux 3.16.6-042stab127.46 (x86_64)

$ weblate check --deploy
System check identified no issues (0 silenced).

**Additional context**
Currently, we use a small hack in utils/site.py to resolve the issue - slightly modified function get_site_url:
```
def get_site_url(url=''):
    """Return root url of current site with domain."""
    return '{0}://{1}{2}{3}'.format(
        'https' if settings.ENABLE_HTTPS else 'http',
        get_site_domain(),
        '' if url.startswith(settings.URL_PREFIX) else settings.URL_PREFIX,
        url
    )
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by SlavekB** [comment]
Tested, works great!
