### ISSUE TITLE
URL_PREFIX is not used in the View site link in the administration interface header

### ISSUE THREAD

**Issue by SlavekB** [WeblateOrg/weblate#2339]
**Describe the bug**
I've applied commit 3aec503 on Weblate 3.2.2. I've modified the Apache configuration as shown in the example. On the web interface, all links seem to be ok, except for the View site link in the administration interface header.

**Expected behavior**
View site link will point to the Weblate start page.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by SlavekB** [comment]
Tested, works great!
