### ISSUE TITLE
[Weblate LXQt] ERROR (EXTERNAL IP): Internal Server Error: /projects/lxqt/lxqt-about/fr/

### ISSUE THREAD

**Issue by agaida** [WeblateOrg/weblate#2342]
**Describe the bug**
Get sometimes mails with the Title above - Body
```
OperationalError at /projects/lxqt/lxqt-about/fr/

FATAL:  remaining connection slots are reserved for non-replication superuser connections

Request Method: 	GET
Request URL: 	https://weblate.lxqt.org/projects/lxqt/lxqt-about/fr/
Django Version: 	2.1
Exception Type: 	OperationalError
Exception Value: 	

FATAL:  remaining connection slots are reserved for non-replication superuser connections

Exception Location: 	/home/weblate/weblate.env/lib/python3.5/site-packages/psycopg2/__init__.py in connect, line 130
Python Executable: 	/usr/bin/uwsgi-core
Python Version: 	3.5.3
Python Path: 	....
```

**To Reproduce**
1. No Clue

**Expected behavior**
I don't want to be out of connection slots. Maybe it would help to set some limits higher.

**Server configuration and status**
pip installation, nothing special - and this phenomenom isn't related to the current version, encountered it with former versions too, but forget to file it. Please ping me for a full  backtrace or additional informations.

**Comment by BoFFire** [comment]
@agaida How many uwsgi processes and buffersize are you running/allowing ?

**Comment by agaida** [comment]
thanks for the pointers - it was 5 processes, 5 threads , 5 workers
