### ISSUE TITLE
Typos in the documentation

### ISSUE THREAD

**Issue by muranamihdk** [WeblateOrg/weblate#2343]
When I found the typos in the documentation, what should I do?
1. We can publish the issues based on the line number of the source code, but we can't do that for the documentation (it is just a rendered document or raw document). Do I have only to publish the issue with the document url and headers and passages (like the following)?
2. Each time I find the typo, can I publish the issue?

Weblate basics
==============
Project structure
------------------
Internally, each project has translations to common strings ~~propangated~~ __propagated__ across other components within it by default.
https://github.com/WeblateOrg/weblate/blob/master/docs/user/basic.rst

Translation projects
====================
Adding translation projects and components
------------------------------------------
...
Based on your permissions, you can be able to create new translation projects
and ~~componets~~ __components__ in Weblate.
...
The project creation can be ~~intiated~~ __initiated__ from there or using menu in navigation
bar.
https://github.com/WeblateOrg/weblate/blob/master/docs/admin/projects.rst

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

For the nextreports, the best approach would be if you could directly submit pull request with desired fix - just click on the edit icon (pen) and propose changes as a pull request. Thanks :-)
