### ISSUE TITLE
Pull requests for BitBucket Cloud

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2344]
**Is your feature request related to a problem? Please describe.**
Weblate currently supports pull requests only for GitHub, it might be useful to have it for BitBucket as well.

**Describe the solution you'd like**
Similarly like with GitHub, Weblate would open pull request on BitBucket instead of directly pushing the code.

**Additional context**
See also https://github.com/WeblateOrg/weblate/issues/1276

**Comment by msteiger** [comment]
I would be greatly interested in this as well.

**Comment by nijel** [comment]
Since https://github.com/WeblateOrg/weblate/pull/4224 we have generic layer for implementing pull requests support. So all what is needed is to trigger few API calls on the BitBucket to for a repo and create a pull request. The most tricky part in this is usually error handling (deal existing forks and pull requests).

For example, code for GitHub is here:

https://github.com/WeblateOrg/weblate/blob/b317c87a5b0397d4ed00845c9bba3a8c0066be15/weblate/vcs/git.py#L687-L772

**Comment by afridlund85** [comment]
I started working on this.
However it's my first open source contribution ever and also first time trying Python, so please be humble when a PR arrives, hopefully within the next couple of weeks.

**Comment by nijel** [comment]
Great! You're welcome to submit draft PR to receive feedback or ask questions about further development.

Many things have changed in the code since https://github.com/WeblateOrg/weblate/issues/2344#issuecomment-692687189, the VCS merge request logic is now more generic and robust, depending on the BitBucket API, you might need to implement only `create_fork` and `create_pull_request` methods (see Pagure and Gitea implementations).

**Comment by afridlund85** [comment]
I noticed that and I have a working solution now I think. It was fairly easy to add by looking at the other implementations even though Bitbucket Server API is very different.
On another note, this solution is only for Bitbucket Server. There's also a Bitbucket Cloud, but this API is different and frankly not something I have time to fix right now. Hopefully this will make it easier for someone (or my self in the future) to add.

**Comment by nijel** [comment]
I see no problem with that, just name and document it so that it's clear which variant it does support.

**Comment by lars3141** [comment]
We are also interested in an implementation of Pull Requests for Bitbucket Cloud analogue to the existing implementations for GitLab, Bitbucket Server etc.
We would like to also have the option of choosing between a Fork and a dedicated Branch as source of the pull request. Is the dedicated Branch the Push Branch? Is the repository branch always the target of the PR?

Thank you!

**Comment by nijel** [comment]
Whether to create a fork or push from a branch is indeed configured by the *Push branch*, see https://docs.weblate.org/en/latest/admin/continuous.html#pushing-changes-from-weblate.

**Comment by lars3141** [comment]
Thank you for the reply @nijel! 

Since the push branch has a fixed name, I do have a follow-up questions:
Our current process includes rather small PRs for text changes. This leads to frequent PRs. The previous PR might not be merged before the next one is opened.
How would the current set-up handle this situation?

I am also in contact with Benjamin about this feature request [Ticket#2010019].

**Comment by nijel** [comment]
Weblate maintains just a single pull request as long as it is not merged.
