### ISSUE TITLE
Right way of configuration for POT files as base file for translation.

### ISSUE THREAD

**Issue by lo-gun** [WeblateOrg/weblate#2349]
**Describe the bug**
The bug is regarding the "file mask" where the base file to be considered is pot file located in the same location as "po" file (as configured in the attached image)

And if the language filter is not added then the pot is read and a blank component is added.

**To Reproduce**
Make configurations as per screen shoots. 
 
**Expected behavior**
To read message strings from pot file and add the translation languages as per language filter and create the component. 

**Screenshots**
1. Configurations for file mask and base file for translation. 
Error remains same for New Translation option selected as 
  1. No adding of language. 
  2. Automatically add  language file. 
![screenshot-178 128 78 9-8000-2018 10 25-12-17-25](https://user-images.githubusercontent.com/34648772/47481040-0b197080-d850-11e8-8cb0-6b527967009b.png)

2. Setup for New Translation for be added.
![screenshot-178 128 78 9-8000-2018 10 25-12-19-31](https://user-images.githubusercontent.com/34648772/47481113-4320b380-d850-11e8-82d8-f6da8f2c607c.png)

3. Configuration example taken from : https://docs.weblate.org/en/latest/formats.html
![screenshot-docs weblate org-2018 10 25-12-20-38](https://user-images.githubusercontent.com/34648772/47481196-75caac00-d850-11e8-98b1-91bd2c477142.png)

**Server configuration and status**
 * Weblate weblate-3.2.2-220-g9780b30
 * Python 2.7.12
 * Django 1.11.16
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.1
 * translate-toolkit 2.3.1
 * Whoosh 2.7.0
 * defusedxml 0.4.1
 * Git 2.7.4
 * Pillow 3.1.2
 * python-dateutil 2.4.2
 * lxml 3.5.0
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * pyuca 1.2
 * python-bidi 0.4.0
 * PyYAML 3.11
 * Mercurial 3.7.3
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:LocMemCache
 * Platform: Linux 4.4.0-137-generic (x86_64)

**Additional context**
What should be the exact configuration for file mask and new translation option in the component configuration page?

**Comment by nijel** [comment]
Maybe removing initial `/` will help.

**Comment by lo-gun** [comment]
**NO**. That's not and issue with the **"/"** as the error remains same.

But the error only occurs when **File Format** option is selected as **Gettext PO.**
And when **File Format** is selected as **Automatic Detection** the component is created but the pot is not read and all the languages are skipped and blank string component is added to project.

And while adding the component languages server gets stuck on 
```
INFO flectra/sale: skipping language en_GB [addons/sale/i18n/en_GB.po]
INFO flectra/sale: checking addons/sale/i18n/af.po (af) [1/64]
INFO flectra/sale/af: processing addons/sale/i18n/af.po, revision has changed
```
It remains stuck on **revision changed** error from then.

**Comment by nijel** [comment]
There should be real path to pot file, not a mask. Anyway the problem on screenshot is with the file mask, which didn't match any files.

As for the stuck on import, if the file is huge, the processing can take some time.

**Comment by lo-gun** [comment]
But if the **PO** files are skipped and only **POT** is added as base file for translation. 
But yet strings from pot are not added for new translation.

And the file contains **11443** lines.

**Comment by nijel** [comment]
Is the repository publicly available so that I can take a look?

If not, can you try installing translation-finder and run in on checked out repository? That should give you hints how to configure the translation projects (this is code still early beta, but it is being improved and will be used by next Weblate release):

```sh
pip install translation-finder
weblate-discovery /path/to/git/repo
```

**Comment by lo-gun** [comment]
Yes here is the repo : https://github.com/lo-gun/check-odoo

**Comment by lo-gun** [comment]
Tried with the latest beta test which you suggested:
`weblate-discover data/vcs/flectra/ac2`
Which resulted :
```

== Match 1 ==
file_format    : po
filemask       : addons/account/i18n/*.po

== Match 2 ==
file_format    : po
filemask       : addons/sale/i18n/*.po
```

Have checked the configuration and i see that the file mask are provided correctly. But it stills remain stuck on revision changed issue.

**Comment by lo-gun** [comment]
For me It is always stuck here:
```
./manage.py loadpo --all
INFO check/sale: checking addons/sale/i18n/af.po (af) [1/66]
INFO check/sale/af: processing addons/sale/i18n/af.po, revision has changed
INFO check/sale: checking addons/sale/i18n/am.po (am) [2/66]
INFO check/sale/am: processing addons/sale/i18n/am.po, revision has changed
INFO check/sale: checking addons/sale/i18n/ar.po (ar) [3/66]

```

**Comment by lo-gun** [comment]
Hello @nijel 

I can see the repo working with the latest pull yesterday where head is at :  
> b5e54664dc8a5307ee3f64b9c632b9a85c229c23

but not the exact commit which made it working.

Where the **"PO"** files are read properly per module and the **"POT"** is also stored and referred as base file translation for any other new translation. 

The console **[INFO]** for revision has changed still persists but the files are added to the component.

Thanks.

**Comment by nijel** [comment]
There were quite some performance improvements, that might make difference in your case.

The revision changed logs are expected as this is first time time Weblate sees the file, but they are indeed a bit confusing...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed - I've improved the message when loggin.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
