### ISSUE TITLE
Copy from glossary doesn't work for new words

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2359]
**Describe the bug**
Copy from glossary doesn't work for newly added words.

**To Reproduce**
1. Go to translate page
2. Add new word to glossary
3. Click on that to copy it into translation

**Expected behavior**
The translation should copy to translation

**Comment by Naruto0** [comment]
Is it hard to solve? The thing is i do not how to do that..

**Comment by Amanbhandula** [comment]
We can introduce word embedding in this case.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
