### ISSUE TITLE
as is, the "celery-weblate.service" of documentation can't work

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#2362]
When following the installation procedure, it took me hours, but I finally understood that using `ExecStart=/bin/sh -c` in systemd script just doesn't work.

My solution was to directly use the path to the celery binary (in my case, in the bin folder of my venv).

I'm using Debian 9.

A friend told me it is normal, because bash won't tell system where is the PID file (I'm unsure to correctly explain this).

**Comment by nijel** [comment]
The example in Weblate is pretty much taken from Celery (see http://docs.celeryproject.org/en/latest/userguide/daemonizing.html#usage-systemd) and it works just fine for me (Debian 9 as well). So I'd be really curious why it doesn't work well for you.
