### ISSUE TITLE
Export / Import project(s) configuration

### ISSUE THREAD

**Issue by meglio** [WeblateOrg/weblate#2367]
Is there any way to export all project(s) configuration? I couldn't find any.

**Comment by nijel** [comment]
You can get most of it using API, eg. https://hosted.weblate.org/api/projects/

**Comment by meglio** [comment]
No ways to do it through GUI for non-tech-savvy translation admins at the moment? If not, is it in any of the todo lists?

**Comment by nijel** [comment]
No GUI for that, sorry. It's not really planned right now, what would be use case for this?

**Comment by meglio** [comment]
I include Weblate through Docker Compose as part of a bigger web
application, and ship it to my customer for testing / configuring locally
before it is deployed. While testing, they're going to setup multiple
projects/components. When it is time to go live, they would like to export
complete local configuration and import it into the live Weblate version.
One-time task though, not a repetitive one.
