### ISSUE TITLE
Undefined name '_ALIASES' in weblate/trans/forms.py

### ISSUE THREAD

**Issue by cclauss** [WeblateOrg/weblate#2377]
flake8 testing of https://github.com/WeblateOrg/weblate on Python 3.7.1
```
15.35s$ time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
./weblate/trans/forms.py:1175:25: F821 undefined name '_ALIASES'
                        _ALIASES[code]
                        ^
1     F821 undefined name '_ALIASES'
1
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
