### ISSUE TITLE
Checks performed when saving translation should be performed when saving suggestions too

### ISSUE THREAD

**Issue by emmapeel2** [WeblateOrg/weblate#2383]
**Describe the bug**
When I accept other translators suggestions, the checks about 'trailing newline', 'trailing space', 'invalid XML' etc start to appear. This tests should be performed before the user adds the suggestion, and prevent the saving of said suggestion instead.
This will save reviewing time, and also will help translators to learn not to make the mistakes.

**To Reproduce**
1. Add a translation that will provoke and error (depending on the tests you have selected)
2. Click on Save
3. A message appears saying there is an error
4. Click on Suggest

The suggestion gets saved without problem

**Expected behavior**
The error message should appear again and prevent the suggestion to be saved (or have an error flag but that will be really complicated I think)

**Server configuration and status**

 * Weblate weblate-3.2.2
 * Python 2.7.15
 * Django 1.11.16

**Comment by nijel** [comment]
Just to clarify - the translation is saved as well, it's just the message is shown and you stay on same string. But indeed the suggestions should behave similarly.

**Comment by emmapeel2** [comment]
yeah the problem is that when i accept suggestions i dont have this information neither. It would be nice if the suggestions were flagged somehow as not passing a check.
otherwise, each time I go through the pending suggestions, i get a lot of error messages _aftwerwards_, not when I am looking at the suggestions.

and happy birthday to the ticket!
