### ISSUE TITLE
Increase components pagination limit

### ISSUE THREAD

**Issue by priverop** [WeblateOrg/weblate#2386]
**Is your feature request related to a problem? Please describe.**
Right now the pagination limit of a project components are just 200, and I feel like it's quite limited. I feel it would be useful to better script automation (web scrappers), and to watch the entire project at a glance.

**Describe the solution you'd like**
Increase it or let the admin decide that limit.

**Comment by priverop** [comment]
With the API it's not that easy for users to see how the project is going at a glance, that's the good thing about the UI in my opinion. Plus there isn't any way to modify that limit without changing the URL right?

By the way I would like to do the pull request myself if possible, as it's a small enhancement, to avoid you spending your time on this.

**Comment by nijel** [comment]
In first comment you've mentioned web scraping, I really don't feel motivated making life easier for these when we do have an API. If you miss something from the API, please open up issue for that.

On the other side, I don't see strong reason for this limit, so it's probably safe to increase it.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
