### ISSUE TITLE
Additional context from imported files

### ISSUE THREAD

**Issue by miikalo** [WeblateOrg/weblate#2390]
Hi,

We defined our translations files as such:

en.json (base file)

{
  "ERR_ERROR_IN_SOMETHING":"Something failed.",
  "ERR_ANOTHER_ERROR":"Another error happened."
}

The code will look for a translation for ERR_ERROR_IN_SOMETHING in the json file of the selected locale (en.json, de.json, fr.json...)

This works well with Weblate. We can create new translation files when the english file is configured as the base file, and those files will then have the "ERR_ERROR_IN_SOMETHING" as the context for the translation. This is often not enough though, since we wanted to keep the tokens short and provided additional context in form of json comments in the json base file, manually at first. The "Additional context" on the right side of a translation in Weblate would be perfect for showing this information, or any other clearly visible field in Weblate.

Since I was aware that these comments would be ignored by Weblate, I tried parsing the comments from the base file into corresponding comment fields in a CSV file downloaded from Weblate. When uploading the file though, these comments are nowhere to be seen.

I tried some other formats, but could not figure a way to download the translations, edit the translation file to include the extra context (or as comments), and upload it back to Weblate to include the extra information.

Any way to achieve this?

**Comment by nijel** [comment]
You can use some more complex format which supports this. If you want to stick with JSON, there is [WebExtension JSON](https://docs.weblate.org/en/latest/formats.html#webextension-json).

Alternatively you can include additional context directly in Weblate, see https://docs.weblate.org/en/latest/admin/translating.html?highlight=screenshot#additional-information-on-source-strings
