### ISSUE TITLE
Wording issue "hundredths" ?

### ISSUE THREAD

**Issue by trebmuh** [WeblateOrg/weblate#2392]
I've translated in French a new string on weblate today. This string is: 
> Browse hundredths of projects on Hosted Weblate

But looking at it, I'm wondering if it's not an error and the meaning should be:
> Browse **hundreds** of projects on Hosted Weblate

Note that I've check in the repo and [this file](https://github.com/WeblateOrg/weblate/blob/master/docs/admin/install.rst) seems to suffer the same issue with:
> For hundredths of translation components at least 4 GB of memory is recommended.

Hope that helps.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by trebmuh** [comment]
:+1:
