### ISSUE TITLE
"Remove translation", complement to "Start new translation"

### ISSUE THREAD

**Issue by ieugen** [WeblateOrg/weblate#2397]
Hi, 

Is there a complement to "Start new translation"? I'm looking for "Remove translation" that will remove the translation for one language from weblate but leave the VCS files intact.

This is a way to RESET translations. Sometimes translations get 0 strings when created.
Now I have to go to VCS, remove translation file, push.
Go to weblate, pull, start new translation.

Having Remove will allow Non Developers (people without git access) to perform these maintenance operations.

Regards,

**Comment by nijel** [comment]
Depending on which version you are, it's either located in the translation repository maintenance (anything released so far) or directly in the "Manage" menu for the translation (in current master and upcoming 3.3 release).
