### ISSUE TITLE
History not retained for local source string edits

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2398]
If someone clicks source and starts editing as if it was a translation, the string can not be reverted easily.
https://hosted.weblate.org/translate/your-local-weather/strings/nb_NO/?checksum=f955d7cd4b15540f

Edit: I would expect the history of edits under "history"

Edit2: For some strings history is retained: 
https://hosted.weblate.org/translate/your-local-weather/strings/en/?checksum=c6c2740180a8e857

**Comment by nijel** [comment]
The history is always kept on the source language: https://hosted.weblate.org/translate/your-local-weather/strings/en/?checksum=f955d7cd4b15540f#history
