### ISSUE TITLE
Enclosing apostrophes makes element unclickable in Zen mode

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2401]
https://hosted.weblate.org/translate/f-droid/fdroidserver/nb_NO/?checksum=78e84d0f080e8aee

Expected clicking '{path}' to copy it to editable field.
Works in the regular editor.

**Comment by nijel** [comment]
It works for first statically loaded units, but not for rest of dynamically loaded ones.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
