### ISSUE TITLE
xlsx Read error

### ISSUE THREAD

**Issue by berubou** [WeblateOrg/weblate#2402]
**Describe the bug**
when add a 'Monolingual base language file' in a component,
it occurred an error with can't analysis. as pic below

![image](https://user-images.githubusercontent.com/14237234/48933315-c3633300-ef3a-11e8-89dc-5e0aa7ea167a.png)

and I follow the [docs ](https://docs.weblate.org/en/latest/formats.html#xlsx) 
does not work either

- the xlsx file i write 
    ![os 09nu d 9iv xd 78h9](https://user-images.githubusercontent.com/14237234/48933401-19d07180-ef3b-11e8-8243-8b05b7f19959.png)

- or the xlsx file i downloaded before
    ![v_4ti05 ys e 8c3tl0 l](https://user-images.githubusercontent.com/14237234/48933417-2b197e00-ef3b-11e8-804e-bb8e589dd7de.png)

**Server configuration and status**
- list_versions
``` 
* Weblate 3.2.2
 * Python 3.5.3
 * Django 2.1.2
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 4.0.0
 * python-dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.3.1
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Platform: Linux 4.4.0-132-generic (x86_64) 
```
- check --deploy
```
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

System check identified 3 issues (0 silenced).
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
