### ISSUE TITLE
Logging in with OAuth2 fails if e-mail is in used

### ISSUE THREAD

**Issue by Kingdutch** [WeblateOrg/weblate#2407]
**Describe the bug**
When trying to authenticate using Google OAuth2 with an e-mail address that is already a normal user you keep being routed to the login screen and the log shows `ERROR Handled exception AuthMissingParameter: b'Missing needed parameter disabled'`

**To Reproduce**
1. Create a user with e-mail somemail@gmail.com
2. Configure your site for OAuth2 authentication using Google
3. Go to https://develop-sr3snxi-i3x5x6gs2mxic.eu-2.platformsh.site/accounts/login/
4. Click to Sign-in with Google
5. Try to authenticate with somemail@gmail.com
6. Find yourself back on the login screen without warning

**Expected behavior**
Feedback to the user that they should login with username/password and link their accounts.

**Screenshots**
n.a.

**Server configuration and status**
```
$ weblate list_versions
 * Weblate 3.2.2
 * Python 3.7.0
 * Django 2.1.3
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 2.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 5.3.0
 * python-dateutil 2.7.5
 * lxml 4.2.5
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.7
 * Mercurial 4.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Platform: Linux 4.18.10-pl1 (x86_64)

$ weblate check --deploy
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.

System check identified 1 issue (0 silenced).
```

**Additional context**
Nope

**Comment by nijel** [comment]
What is your setting for REGISTRATION_OPEN?

**Comment by Kingdutch** [comment]
--- Before @nijel 's comment but forgot to press "Comment" ---
So I asked someone else to try this but they also had the same behaviour when they didn't yet have an account which might mean that the title of this issue is incorrect.

It seems to logging in with a username/password and then linking will allow it to work however.

--- After his comment ---
The REGISTRATION_OPEN was indeed set to False which could explain this. From a UX perspective I'd expect an error message saying "New registrations are turned off on this platform. Contact an administrator for help" to acknowledge that nothing is broken but nothing will happen either.

I'm having some trouble redeploying the environment with the changed setting so I'll update this issue with results once that's fixed :)

If REGISTRATION_OPEN then I have another question beside the user feedback: Could it be possible to allow new accounts through Single-Sign-On but no new accounts through normal login? The scenario where this could work is a protected SSO application limited to a domain that ensures only users within that domain can register but also having to provide access to some external users that are not in that domain by creating an account manually for them (without opening up translations to the world).

**Comment by nijel** [comment]
To disable normal registration, just remove `social_core.backends.email.EmailAuth` from `AUTHENTICATION_BACKENDS`.

The user should get reasonable message:

https://github.com/WeblateOrg/weblate/blob/8c99f097e982dd0d2bc3206c5d048be9e4c5db21/weblate/accounts/views.py#L905-L909

If it was not displayed, then it's some bug in the error handling.

**Comment by Kingdutch** [comment]
> To disable normal registration, just remove social_core.backends.email.EmailAuth from AUTHENTICATION_BACKENDS.

I was under the impression that this would disable normal user login also which is not what we want (though I admit I haven't tried it yet).

That auth_fail didn't work (with a user facing message) but gave the error that I mentioned in the opening issue in the logs.

**Comment by nijel** [comment]
I've just tested it on current master and it behaves as expected with `REGISTRATION_OPEN = False`:

* Creating new account is rejected with `New registrations are disabled!`
* Same happens when trying to login with new method for existing email
* Adding authentication method from settings still works

**Comment by TafkaMax** [comment]
I am getting the same error with OIDC.

https://github.com/WeblateOrg/weblate/issues/8217
