### ISSUE TITLE
Version in filename

### ISSUE THREAD

**Issue by Kingdutch** [WeblateOrg/weblate#2409]
We want to use Weblate with a project that has quite a few extensions in separate repositories. We would like to keep our translations outside of the repositories of the various components and instead group them in a single translations repository.

From what I've found in the documentation so far, most of the versioning is based around git tags. Is it possible to configure Weblate to put the version in the translation file name instead?

e.g. a translations repository with

- english/component-one-1.1.po
- english/component-one-1.2.po
- english/component-two-2.1.po
- spanish/component-one-1.2.po

**Comment by nijel** [comment]
Weblate doesn't deal with Git tags at all. Also there is no reason why mentioned files would not work, just use `*/component-one-1.1.po` or `*/component-two-2.1.po` as a filemask.

**Comment by Kingdutch** [comment]
I confused my picture of the workflow (create translations then tag version for project together with translations) with how Weblate worked, sorry : )

However, if I use the filemasks you suggested then there is no way within Weblate to distinguish between translations made for the 1.1 version of component-one and the 1.2 version of component-one. Or is there?

**Comment by Kingdutch** [comment]
We're not using versioning for individual components at the moment but my question of how to track multiple versions of a translation for multiple components within a single repository still stands :)

**Comment by nijel** [comment]
The easiest approach is to use separate branch for each version.

**Comment by Kingdutch** [comment]
Then we'd have to create a component per branch I think right or am I missing a feature?

**Comment by nijel** [comment]
Yes, that's true - you need separate component for each source. You can use translation propagation feature (enabled by default) to keep translations in sync within one project.
