### ISSUE TITLE
Automatic translation: TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by SantosSi** [WeblateOrg/weblate#2419]
On hosted.weblate.org all external translation engines (Baidu, Yandex, Apertium APy, Microsoft Translator and DeepL) return:
TypeError: argument of type 'NoneType' is not iterable
Internal suggestions from the Weblate Translation Memory still work fine.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by SantosSi** [comment]
Has it been deployed to hosted.weblate.org yet? It is still not changed.

**Comment by SantosSi** [comment]
OK now.

**Comment by nijel** [comment]
I was deploying it now with other fixes...
