### ISSUE TITLE
Terminology for a project

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#243]
There should be possible to define terminology for a project, which would be then used in all of it's dictionaries. This should not prevent translators from adding own words for just given language, but project maintainer should be able to define list of words, which should be included in all glossaries (and see how much of them is actually translated).
##

**Comment by algazarra** [comment]
+1
I was going to open a new issue called "unified glossary". If I add a glossary word in any language, that item should be added to every other language glossary.

Maybe auto start with glossary when creating a new translation.

**Comment by nijel** [comment]
Scope of this feature:

* Add new category to glossary view to define terminology, allowing adding of new words and see words status
* The per language view should list missing words
* When adding new term to glossary, it should be possible to mark it as terminology

Terminology model: 

* Term.terminology references Terminology, on delete set NULL
* Term.terminology is automatically set when source string matches
* Terminology object is not editable to avoid need to adjust the foreign keys
