### ISSUE TITLE
Translator name in updated string e-mail.

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2430]
It would be nice if the username of whoever changed a string was in the e-mail detailing the change. It currently lists the project, the language, and the instance of Weblate.
My usecase is trusting a particular username, so I don't need to check all the changes, or am atleast not rushing to do so. Bonus for putting the username in the subject field :)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
