### ISSUE TITLE
Task-equivalent for "updategit"?

### ISSUE THREAD

**Issue by BhaaLseN** [WeblateOrg/weblate#2433]
**Is your feature request related to a problem? Please describe.**
Until now I've used a bunch of cronjobs (as per the old documentation) to perform both `commitgit` (or `commit_pending`) and `updategit` on an hourly basis to minimize the potential for conflicts.
With 3.2 and the introduction of Celery background tasks, there are many new built-in tasks that do exactly that (in the case of `commitgit` for example).
However, there is no equivalent to `updategit`, the task https://github.com/WeblateOrg/weblate/blob/302326604c2d65931749b1084f498c18f8ba7092/weblate/trans/tasks.py#L249-L251 only does a fetch, but no merge.

**Describe the solution you'd like**
I'd really like to replace _all_ cronjobs with the (seemingly now) preferred way of specifying a Celery task instead. But there is no task to do a fetch _and_ merge/rebase (as per Component configuration)

**Describe alternatives you've considered**
For now, I'll keep using the cronjob with `updategit`, but I was able to retire the others (`update_index`, `cleanuptrans` and `commit_pending`/`commitgit`) since they have task equivalents (not only that, but also with an hourly configuration so I don't even have to change anything)

**Comment by nijel** [comment]
The `update_remotes` task can do merge as well, you just need to enable it using [AUTO_UPDATE](https://docs.weblate.org/en/latest/admin/config.html#auto-update) setting.

**Comment by BhaaLseN** [comment]
It should probably be mentioned in `settings_example.py` then ;)

Thanks!

**Comment by nijel** [comment]
The example config was always meant to include the most important options, not all of them :-).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed by extending the docs, the example settings were not changed.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
