### ISSUE TITLE
zeep is mandatory for test suite

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#2435]
**Describe the bug**
According to the documentation, zeep is an optional dependency.

But witout zeep, testsuite fails.

**To Reproduce**
1. Have a system without zeep.
2. `python3 ./manage.py test --settings=weblate.settings_test -v 2`

```test_update_remote (weblate.vcs.tests.test_vcs.VCSSubversionTest) ... ok

======================================================================
ERROR: weblate.machinery.tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: weblate.machinery.tests
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/abuild/rpmbuild/BUILD/Weblate-3.2.2/weblate/machinery/tests.py", line 46, in <module>
    from weblate.machinery.microsoftterminology import MicrosoftTerminologyService
  File "/home/abuild/rpmbuild/BUILD/Weblate-3.2.2/weblate/machinery/microsoftterminology.py", line 24, in <module>
    from zeep import Client
ModuleNotFoundError: No module named 'zeep'


----------------------------------------------------------------------
Ran 2097 tests in 713.932s

FAILED (errors=1, skipped=63)
 OK
```

**Expected behavior**
Pass.

**Screenshots**
N/A

**Server configuration and status**
N/A

**Comment by nijel** [comment]
The same applies to most of the optional deps (at least boto3 for sure).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
