### ISSUE TITLE
SSH access keys for repo publicly visible for everyone

### ISSUE THREAD

**Issue by epkjoja** [WeblateOrg/weblate#2436]
**Describe the bug**
I have a private Git repo containing all my code and the translations. To let Weblate easily access the translations I am using an SSH key that is added to Weblate and to my private repo. This is the same setup as described here: https://docs.weblate.org/en/weblate-3.3/vcs.html?#ssh-repositories
I am using Weblate version 3.3

My Weblate configuration allows anonymous users to view the translations but they must login to translate. My projects are protected. I have also removed the "Access repository" role from the "Guests" group.

When I access Weblate without logging in and go to "About Weblate" -> "Keys", the SSH key to my private repo is fully visible there! That can't be the intended behavior?

**To Reproduce**
1. Go to https://demo.weblate.org/keys/ No need to login.

There you can see the placeholder for the keys. If there where any keys installed on the demo site, they would have be seen there just as they are on my site.

**Expected behavior**
An SSH access key to a private repo should not be publicly visible.

**Screenshots**
![weblate](https://user-images.githubusercontent.com/5808522/49475066-8e968c00-f816-11e8-84ff-30ac99bc20d3.jpg)

**Comment by nijel** [comment]
This is a *public* key, it doesn't allow you to access anything. It allows you to configure something in a way to be accessible by Weblate.

**Comment by nijel** [comment]
Thank you for your report, I've improved the description to avoid such confusion.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
