### ISSUE TITLE
Improve auto locking

### ISSUE THREAD

**Issue by xmorave2** [WeblateOrg/weblate#245]
It would be great (if it is possible) to have auto locking function working more sophisticated.

My idea is, to lock only each one string, which is currently translated.

It means, that when somebody opens the string for translation, this string is being locked and, if somebody else is going to translate, this locked string is automatically skipped.

If somebody tries to open currently locked string, the message will display and "Save" button will be inactive, as it is now for whole sub-project.
##

**Comment by marcperrin** [comment]
Hi nijel,

Before thinking about a more ambitious chunk-based lock, do you think there is value in making a simple feature that lets (based on settings) the auto lock work at unit level instead of translation level? Or do you think we would be better off just deactivating the auto lock? 

(got some user feedback about not being able to collaborate on a single translation)

Thanks,

Marc

**Comment by nijel** [comment]
The chunk based locking would in the end be implemented on unit level anyway, so it's pretty much same approach.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by marcperrin** [comment]
Échec de la remise pour ces destinataires ou groupes :

marcperrin (marc.perrin@dont-nod.com)<mailto:marc.perrin@dont-nod.com>
L'adresse de messagerie que vous avez entrée est introuvable. Vérifiez l'adresse de messagerie du destinataire et essayez de renvoyer le message. Si le problème persiste, contactez le support technique.







Informations de diagnostic pour les administrateurs :

Génération du serveur : dont-nod.com

marc.perrin@dont-nod.com
#550 5.1.1 RESOLVER.ADR.RecipNotFound; not found ##

En-têtes de message d'origine :

Received: from SRV (192.168.1.5) by SRV.dont-nod.lan (192.168.1.5) with
 Microsoft SMTP Server id 14.3.361.1; Tue, 5 Dec 2017 14:50:19 +0100
Return-Path: <noreply@github.com>
Received: from github-smtp2b-ext-cp1-prd.iad.github.net ([192.30.252.194]) by
 mx.kundenserver.de (mxeue012 [212.227.15.41]) with ESMTPS (Nemesis) id
 1MUGFH-1eUmTg1Jo3-00RKyr for <marc.perrin@dont-nod.com>; Tue, 05 Dec 2017
 14:49:55 +0100
Date: Tue, 5 Dec 2017 05:49:54 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
        s=pf2014; t=1512481794;
        bh=TeQZQKREK6TnB4WiWhKG9PfGpW1t3I47ElFpyl91cJk=;
        h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
         List-Archive:List-Post:List-Unsubscribe:From;
        b=kbqkshm+NLJmooWkUVUz8S0RMCzi4qSGM3Vb3E1ZOIGiYfE9D8FpxLeycffB8ODjG
         J2ruHT+H7nB70zheNaMFZAemzMha4flt12eCyZ9+ZrCCTAQHdr0Zq5bDGPfl5L+ZP9
         /bUoz7v8MSWoVt1QWxsDr2c0ldClAvgGzr51Aa+s=
