### ISSUE TITLE
Custom addon does not run (after upgrade from 3.1 to 3.3)

### ISSUE THREAD

**Issue by miroslavrehor** [WeblateOrg/weblate#2451]
I have created my own addon. In 3.1 it worked correctly. Now I updated to 3.3 - and the addon will not start. I can see it in the admin interface, it is installed, but does not run. No error, nothing.

Addon is correctly added in settings.py in variable WEBLATE_ADDONS.

Do I have install the addon in any other way? I could not find anything new in the documentation.

**Comment by nijel** [comment]
I'm not aware of any change in the addons code since their introduction, you should get at least error if it doesn't work.

**Comment by nijel** [comment]
Did you figure out something? Is the addon listed as installed on the addons page?

**Comment by miroslavrehor** [comment]
Unfortunately, no progress. My addon is listed:
![image](https://user-images.githubusercontent.com/1447944/50058529-069b7500-017a-11e9-8d8f-3925e658fd3f.png)

There is no error in the log. Just nothing happens... :-/

**Comment by nijel** [comment]
If there is no error, then most likely something is wrong in with the addon registration to events:

* Does it properly define `events` attribute?
* Does it have unique `name` attribute?
* Does it implement handler method matching the received events?

You can also check if addons is correctly registered in Django shell:

```console
$ ./manage.py shell
from webPython 2.7.15+ (default, Nov 28 2018, 16:27:22) 
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from weblate.addons.models import Addon
>>> addon = Addon.objects.filter(name='your.addon.name')[0]
>>> addon
<Addon: Generate MO files: ACL/Limited>
>>> addon.event_set.all()
<QuerySet [<Event: Generate MO files: ACL/Limited: pre commit>]>
```

**Comment by miroslavrehor** [comment]
I use docker image based on your image https://github.com/WeblateOrg/docker and I add my addon into this image.
I run this in docker container:
```bash
root@4b58953cfd14:/# /usr/local/bin/weblate shell
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from weblate.addons.models import Addon
>>> addon = Addon.objects.filter(name='weblate.addons.kmat_addon.KmatPotGeneratorAddon')
>>> addon
<AddonQuerySet [<Addon: Kmat Pot Generator Addon: Kalhotkomat/kalhotkomat>]>
```
There is no error.

There is addon class:
```python
class KmatPotGeneratorAddon(BaseAddon, LoggerMixin):
	events = (EVENT_POST_UPDATE,)
	name = 'weblate.addons.kmat_addon.KmatPotGeneratorAddon'
	verbose = _('Kmat Pot Generator Addon')
	description = _(
		'Automaticky vygeneruje POT pri pushnuti.'
	)

	def post_update(self, component, previous_head):
		self.log_info("Updating pot and po files")
```

When I used base docker image for weblate 3.1.1, everything was ok.
The message `Updating pot and po files` was logged.

Now I have upgraded to new docker image for weblate 3.3 and **no addon action occurs**, no message, no error...

I even tried to uninstall and newly install the addon - but nothing changed. Just silence.

**Comment by nijel** [comment]
Can you please print `addon.event_set.all()` as well? That would show if addon is correctly registered for the update event.

**Comment by nijel** [comment]
One thing which comes to my mind is that there was change in the Python version used in the Docker container between 3.1 and 3.3.

**Comment by miroslavrehor** [comment]
It seems to be registered well:
```
>>> addon = Addon.objects.filter(name='weblate.addons.kmat_addon.KmatPotGeneratorAddon')[0]
>>> addon.event_set.all()
<QuerySet [<Event: Kmat Pot Generator Addon: Kalhotkomat/kalhotkomat: post update>]>
```
I've have changed the addon path  in dockerfile for python3.6 as well.

**Comment by nijel** [comment]
Okay, Django doesn't catch the exception in way Weblate invokes signals, so that is not the problem here. But I still think that something on the way catches the error happening in your addon...

**Comment by miroslavrehor** [comment]
> There is no `log_info` method on the addon class, you probably want to use `component.log_info` instead...

My addon is inherited from` BaseAddon` and `LoggerMixin` which has method `log_info`

```python
class KmatPotGeneratorAddon(BaseAddon, LoggerMixin):
    ...
```
Do you have any suggestions what I should try?

**Comment by nijel** [comment]
LoggerMixin will not work unless you define slug property, it is built for models having that out of the box.

**Comment by miroslavrehor** [comment]
I see now. Problem is this commit https://github.com/WeblateOrg/weblate/commit/007e9134eeefffb1819669ca43a4dc35c4a4e4e8.

Before It was ok to use LoggerMixin, but now it fails on it.
Strange is that there is no error on exception.

**Comment by nijel** [comment]
Okay, now I probably get it - the addon is executed in Celery task and that way the error probably appears only in the Celery logs. The recommended approach is to use Sentry or Rollbar to collect these, see https://docs.weblate.org/en/latest/admin/install.html#collecting-errors.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed - I've clarified intended use for mixins and added deploy check when error collection is missing. There is now also test whether exceptions are properly passed from addons.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
