### ISSUE TITLE
OperationalError REGEXP_LIKE does not exist'

### ISSUE THREAD

**Issue by mipapo** [WeblateOrg/weblate#2452]
**Describe the bug**
I'm getting a OperationalError  when clicking e.g. on "String needed action" (only if not null)

**To Reproduce**
- Go to proejct
- go to component
- click on translated strings
- https://translate.runalyze.com/translate/runalyze/runalyze-master-po/ca/?type=todo

(Debug currently enabled)

For me it does not seems to be a duplicate with #2378

**Expected behavior**
Get the missing translations 

**Screenshots**
![bildschirmfoto vom 2018-12-09 19-12-33](https://user-images.githubusercontent.com/2135076/49700988-6a57f800-fbe6-11e8-8477-59b617f06d6f.png)

**Server configuration and status**
MariaDB 10.3

 * Weblate weblate-3.3
 * Python 3.5.2
 * Django 2.0.7
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 2.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow 5.2.0
 * python-dateutil 2.7.3
 * lxml 4.2.3
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * pyuca 1.2
 * python-bidi 0.4.0
 * PyYAML 3.13
 * tesserocr 2.3.0
 * Mercurial 3.7.3
 * Database backends: django.db.backends.mysql
 * Cache backends: default:MemcachedCache
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.4.0-138-generic (x86_64)

On Git checkout:
HEAD detached at weblate-3.3

Do you have any idea?

**Comment by nijel** [comment]
This is bug in Django 2.0.7, it was fixed in 2.0.8, please upgrade. See https://docs.djangoproject.com/en/2.0/releases/2.0.8/

**Comment by mipapo** [comment]
Thanks! It works!
