### ISSUE TITLE
Zen-mode shows wrong translation after editing source string

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2453]
First I clicked the marked for edit nb_NO strings, opened the regular editor, switched to source there, then edited source strings.

Then in the marked for edit strings, I corrected/updated and unmarked edits for the nb_NO strings in the Zen mode.

I noticed one of the strings had an erroneous translation, clicked it for opening in the regular editor, and all was fine there. Then i F5-ed the Zen editor, and this string was fixed, but the erroneous translation had moved somewhere else.

Wrong here (zen):
![skjermbilde pa 2018-12-10 08-39-56](https://user-images.githubusercontent.com/13802408/49717515-98295500-fc57-11e8-929e-e5497ca9d268.png)

Correct here (regular):
![skjermbilde pa 2018-12-10 08-40-25](https://user-images.githubusercontent.com/13802408/49717513-9790be80-fc57-11e8-9a8a-300bd1d0412a.png)

I think it has to do with the offset when switching between modes, and keeping the same Zen-view.

**Comment by nijel** [comment]
I guess that's how most browsers handle page reload - they will keep the current form content and inject it into reloaded page. In case some of the strings disappeared from the search meanwhile, the ordering would be changed...
