### ISSUE TITLE
JSON keys are removed when pushing changes

### ISSUE THREAD

**Issue by leonekmi** [WeblateOrg/weblate#2457]
**Describe the bug**
When you use placeholders in `messages.json` files from WebExtensions, they dissapear when you push changes.

**To Reproduce**
1. Create a project and a component based on WebExtension
2. Make some changes
3. Push these changes
4. `placeholders` keys are removed

**Expected behavior**
It should keep these keys to avoid compatibility issues with the extensions code

**Screenshots**
https://github.com/leonekmi/scrobbly/commit/58ce6284e7bca987f594dfd347d9ac6745282612
![image](https://user-images.githubusercontent.com/20224422/49821054-c901ab00-fd79-11e8-9875-7c58247ea28b.png)

**Server configuration and status**

```
weblate@hifumin:/srv/weblate$ ./manage.py list_versions
 * Weblate 3.3
 * Python 2.7.13
 * Django 1.11.17
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.10.0
 * social-auth-core 2.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.1
 * translate-toolkit 2.3.1
 * Whoosh 2.7.0
 * defusedxml 0.4.1
 * Git 2.11.0
 * Pillow 4.0.0
 * python-dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.6.1
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2016.7
 * pyuca 1.2
 * python-bidi 0.4.0
 * PyYAML 3.12
 * tesserocr 2.4.0
 * Mercurial 4.0
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.9.0-7-amd64 (x86_64)
weblate@hifumin:/srv/weblate$ ./manage.py check --deploy
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.

System check identified 1 issue (0 silenced).
```

**Comment by nijel** [comment]
Bug in the translate-toolkit, proposed fix is here: https://github.com/translate/translate/pull/3844

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
