### ISSUE TITLE
Plurals other than "one/other" in YML files seem to be ignored

### ISSUE THREAD

**Issue by renatolond** [WeblateOrg/weblate#2458]
**Describe the bug**
In version 3.1.1 running on joinmastodon.org, it seems that  "zero", "two" and other similar plurals are not shown by weblate interface. Those plurals are not present in the source file, because the source file is in english, and therefore only uses one/other.

See https://github.com/tootsuite/mastodon/blob/master/config/locales/ar.yml#L38-L39 / https://weblate.joinmastodon.org/translate/mastodon/backend/ar/?checksum=b64520f969b267e2

**To Reproduce**
1. Create a source locale with plural translations containing one/other
2. Create another locale, such as AR that supports two/many/few/zero
3. No option to translate two/many/few/zero is available

**Expected behavior**
I'd expect to be able to translate those plurals

**Additional context**
I have no access directly to the weblate installation to give more details about configuration, but I can try to spin up a docker installation to test if needed.

**Comment by nijel** [comment]
Plurals in the Ruby YAML files are not yet supported by our backend library, see https://github.com/translate/translate/issues/3615

**Comment by nijel** [comment]
I've just proposed PR implementing this: https://github.com/translate/translate/pull/3846

**Comment by renatolond** [comment]
Thank you! :+1:

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
