### ISSUE TITLE
Dates fields are not aligned

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#2461]
**Describe the bug**
Date are not aligned in the field.

**To Reproduce**
Perform a search

**Screenshots**
![dates are not aligned](https://user-images.githubusercontent.com/1452146/50043463-eafa7680-0074-11e9-8be9-7c7b78613c2f.jpg)

**Versions & Context**
Weblate 3.4-dev
Discovered under Firefox (note: this aligned problem is not visible under Chromium).

**Comment by nijel** [comment]
Probably related to native date selection introduction to Firefox. The popup part was fixed in https://github.com/WeblateOrg/weblate/issues/2045.

**Comment by nijel** [comment]
Related bootstrap CSS:

https://github.com/twbs/bootstrap/blob/3e519c37267b44fd0fedfd86df4b0e67468046ac/less/forms.less#L186-L214

**Comment by nijel** [comment]
Related Mozilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1503427

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by ldmpub** [comment]
Thanks, it works fine ;-).
