### ISSUE TITLE
Validate GitHub emails

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2463]
It seems that there are some users from GitHub using email `username@users.noreply.github.com`. Apparently that is not working email address and should not be used by Weblate.

Maybe these are just historical accounts from prior https://github.com/WeblateOrg/weblate/issues/648, but it still needs to be checked.

**Comment by ccppoo** [comment]
Maybe something needs to be added like :
-------------------------------
import re
check  =re.complie('^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$')
for email in emails:
    p.match(email)
-------------------------------
To get what you are looking for ; like someone@google.com

will be changes on :  https://github.com/WeblateOrg/weblate/blob/56c75d30629b1b6f2f206dc138adc79becada910/weblate/utils/validators.py#L37
and some other things that imports this module

**Comment by nijel** [comment]
The emails are syntactically valid, they just are not working. The regexp validation is already there (from Django validator).

**Comment by ccppoo** [comment]
Thanks just wanted to help

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
