### ISSUE TITLE
documentation: cron rules in weblate >= 3.3

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#2464]
**Describe the bug**
Weblate documentation contains references to cron in many places. But starting with version 3.3, no reference for recommended rules is present.

Please either describe rule of the cron in weblate >= 3.3 functionality, or remove references to cron.

In past, 3 rules were recommended for cron:
1. update_index four times a hour
2. cleanuptrans every day
3. commit_pending every hour with maximal age set to 96 hours

If I understand correctly, all these tasks were moved to celery. First two are part of the default behavior, rule 3. was moved to the optional CELERY_BEAT_SCHEDULE.

But 3. is unclean. The old cron rule recommended to commit pending changes every 96 hours, the new CELERY_BEAT_SCHEDULE recommends commit every 120 seconds! Is it really intended as replacement with 2880 times more frequent commits?

**Comment by nijel** [comment]
The docs is probably not clear on that, but the CELERY_BEAT_SCHEDULE is a way to make more frequent commits, the pending changes are now commited hourly, but only if they are older than age defined at component level.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by stanislav-brabec** [comment]
This is not yet fully clean. There are still 5 references to cron and no example of commands that should be added. According to these last two commits, it seems that cron is not needed any more.

**Comment by nijel** [comment]
Yes, cron should not be needed in most cases. I've clarified some other parts of the docs.
