### ISSUE TITLE
Feature Request: Search for suggestions

### ISSUE THREAD

**Issue by diplozoon** [WeblateOrg/weblate#2472]
**Is your feature request related to a problem? Please describe.**

I want to search for my suggestions, but cannot do.

**Describe the solution you'd like**

Add the feature to search for one's suggestions, or  see those on dashboard.

**Comment by nijel** [comment]
You already can browse user suggestions (eg. https://hosted.weblate.org/user/anonymous/suggestions/)

**Comment by diplozoon** [comment]
Oops! Sorry!
Thank you for the information.
