### ISSUE TITLE
Possibility to export project data in xml ldml format

### ISSUE THREAD

**Issue by asereze** [WeblateOrg/weblate#2473]
**Describe the solution you'd like**
We already have the possibility to export the translation files of the projects in many formats (CSV, MO, PO, TBX, TMX, XLIFF and XLSX), but since there are some projects with data that could be imported in the Unicode CLDR survey tool (for example, all the ISO locale data for Debian), it would be really useful to translators that already worked on those to be able to download the files in the LDML XML format that Unicode uses ( http://unicode.org/reports/tr35/ ).

**Comment by nijel** [comment]
I'm not really sure this would be useful for anything else besides iso-codes project - it's format for defining locale rather than translations. The translations are there just for defined topics, so it's not really generically applicable format.

**Comment by asereze** [comment]
Ah, ok. Too bad. Thank you anyway.
