### ISSUE TITLE
Weblate 3.3: API user requests are rate limited as anon

### ISSUE THREAD

**Issue by alexminton** [WeblateOrg/weblate#2474]
**Describe the bug**
After update of openSUSE Weblate instance to 3.3 it was noticed that rate limit for anon API requests is applied to authorized requests as well.
I have a helper script in Python to list and download all translations (I use it for single language) and it was working fine for quite some months - but now I can get only a hundred responses which results in 87 files downloaded only out of almost 250 files (I think that projects pagination eats up first 13 requests).

**To Reproduce**
1. Download and unpack the script attached [wl_get_public.zip](https://github.com/WeblateOrg/weblate/files/2723316/wl_get_public.zip)
2. Set the path for downloaded files and valid API key (lines 56-57)
3. Run it and see that 87 files get downloaded until error 429 kicks in.

**Expected behavior**
Configured rate limits for anon and user requests should be applied respectively.

**Server configuration and status**
 * Weblate 3.3
 * Python 3.6.5
 * Django 2.0.8
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 2.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.16.4
 * Pillow 5.0.0
 * python-dateutil 2.6.1
 * lxml 4.0.0
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2017.3
 * pyuca 1.2
 * PyYAML 3.12
 * Database backends: django.db.backends.postgresql_psycopg2
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.12.14-lp150.12.28-default (x86_64)

**Additional context**
openSUSE instance admin Stanislav Brabec assured me that default limits of 100/day for anon and 1000/day for user requests were not changed, so everything should still work but doesn't — therefore we suspect a regression happenning here.

**Comment by nijel** [comment]
There is no customization for throttling in Weblate, so Django REST Framework rules should apply: https://www.django-rest-framework.org/api-guide/throttling/

I've just tested that on Hosted Weblate service and the throttling seems to correctly kick in after approximately 1000 requests for authenticated user. Are you sure you're not using the API elsewhere as well?

**Comment by alexminton** [comment]
The script I've attached is my only way of API interaction. Throttling itself was not a problem until the update: as I mentioned, I've used this script successfully during 2018 (it's weblate 2.18 times) — but noticed different results some time after upgrade.

**Comment by nijel** [comment]
I've just tested that on https://l10n.opensuse.org/ and I was able to perform 1000 requests as well, so it really looks something is consuming your rate limit as well.

**Comment by stanislav-brabec** [comment]
I just added following lines to settings.py on https://l10n.opensuse.org/ and restarted uwsgi:

```
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '300/day',
        'user': '1000/day'
    }
}
```

Please test whether things had changed.

**Comment by alexminton** [comment]
Things had changed drastically, but not in a good way:
Traceback (most recent call last):
  File "wl_get.py", line 58, in <module>
    for trans_item in get_components():
  File "wl_get.py", line 26, in get_components
    wl_response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://l10n.opensuse.org/api/components/

Something is still not up and running, I guess.

**Comment by stanislav-brabec** [comment]
OK, reverted. Interesting that the change did not affect the web. I was able to login without problems.

**Comment by stanislav-brabec** [comment]
> Something else influences this situation: after reverting only the error has changed, now I have error 429 at the very beginning.

You probably already exhausted the daily limit. The Weblate admin GUI does not allow to reset daily limit, and the Django documentation also does not contain easy way to reset it.

**Comment by alexminton** [comment]
> You probably already exhausted the daily limit. 
Looks plausible to me. When does daily reset happen — UTC midnight or some other timepoint?

**Comment by stanislav-brabec** [comment]
I made some tests on my weblate testing instance and finally found the problem.

There is a typo in your script: `Autorization` should be `Authorization`. That is why anonymous access limit applies.

**Comment by alexminton** [comment]
Well, it means that those limits were not properly applied in previous versions — and all this was just a strange way to find out that now everything works like it should. I am deeply sorry for wasting your time on this, thank you very much for your support. God bless you!

**Comment by stanislav-brabec** [comment]
You are welcome. It could happen. Maybe the behavior change was a side effect of:

weblate 3.2
* Allow more fine grained ratelimit settings.

**Comment by nijel** [comment]
Just to answer questions: I was testing using [wlc](https://github.com/WeblateOrg/wlc), you might want to use it's API as well to make things easier to implement.

The change in 3.2 applied to user facing pages (like contact, login or search), not the API. I don't recall any change in that. Still we rely purely on Django REST Framework here, so it might be some fix there as well. Looking at their [release notes](https://www.django-rest-framework.org/community/release-notes/) I don't see anything obvious.
