### ISSUE TITLE
Make Weblate compliant with Google API Policy

### ISSUE THREAD

**Issue by skvalex** [WeblateOrg/weblate#2475]
Since November 2018, all apps need to get approval by Google of the OAuth consent screen. So trying to comply with this policy, I have installed Legal module, wrote a simple Privacy Policy. But Google has rejected my request with the following message:

> 1. Privacy Policy
> 
> [Google API Service:User Data Policy](https://developers.google.com/terms/api-services-user-data-policy) requires the following:
> 
> Your Privacy policy must be visible to users, hosted within the domain of your website, and linked to the OAuth consent screen on [Google API Console](https://console.developers.google.com/).
> 
> Your privacy policy and in-product privacy notifications must thoroughly disclose the manner in which your application accesses, uses, stores, or shares Google user data. Your use of Google user data must be limited to the practices explicitly disclosed in your published privacy policy.
> 
> 2. Google Sign-In Branding
> 
> The Google sign-in button on your project's homepage URL is not compliant with the Google sign-in branding guidelines. Please update the Google sign-in button on your website according to [Google sign-in branding guidelines](https://developers.google.com/identity/branding-guidelines#top_of_page).

As I understand from this message, link to Privacy Policy should be direct. Currently, it's not visible unless you click Legal.

Here are my thoughts what's needed to be done:
1. Make Legal module installed by default.
2. Write a template Privacy Policy with the explanation how Weblate uses Google user data.
3. Add direct link to Privacy Policy in the footer.
4. Make Google Sign In button compliant with their branding guidelines.

**Comment by nijel** [comment]
Having legal installed by default doesn't make sense - you need to write sensible legal documents to match your use case. This heavily depends on local law and I doubt anything generic can be provided. Also not everybody needs Google authentication, so it doesn't make sense to describe in generic policy how Weblate uses data from Google.

If I understand the branding policy, we should be mostly okay once we replace the current one color G with actual logo (You can use the word "Google" by itself in the button if it is accompanied by adjacent text that makes it clear what the action is). The other part is using Roboto font for "Google" text, but this really looks insane to increase page load size just for this.

Apparently I've registered it for Hosted Weblate too long ago, when the approval was not that strict (or maybe even the rules were not that strict).

**Comment by skvalex** [comment]
> Having legal installed by default doesn't make sense - you need to write sensible legal documents to match your use case. This heavily depends on local law and I doubt anything generic can be provided. Also not everybody needs Google authentication, so it doesn't make sense to describe in generic policy how Weblate uses data from Google.

To write the Privacy Policy, I need to know how Weblate works and what Weblate does to User data. But I can't know it for sure, I may only guess. And writing Privacy Policy based on guesses is not good idea I think.

> Apparently I've registered it for Hosted Weblate too long ago, when the approval was not that strict (or maybe even the rules were not that strict).

It doesn't matter when you registered, approval needed for any public app. Without the approval, Google will show "[Unverified](https://support.google.com/cloud/answer/7454865)" screen, but will keep working. Check your developer console: https://console.developers.google.com/apis/credentials/consent

**Comment by nijel** [comment]
There is [a privacy policy for Hosted Weblate service](https://hosted.weblate.org/legal/privacy/) which describes it, the source is [in the hosted repository](https://github.com/WeblateOrg/hosted/blob/master/wlhosted/legal/templates/legal/documents/privacy.html). It can be probably used as a template in case you are EU based as it heavily references to GDPR.

The Unverified screen is not shown for Hosted Weblate, so apparently there was some approval in the past, but the rules were not that strict. Anyway I've already updated consent settings to include link to privacy policy and now I have to pass the verification as well.

**Comment by nijel** [comment]
I've changed to display official logo in https://github.com/WeblateOrg/weblate/commit/0f5d99357e81c0ed03606da8c1879696dec99c18, so Weblate should be closer to the branding guidelines. Let's see if the font really needs to be used.

**Comment by nijel** [comment]
It has been successfully verified for [Hosted Weblate](https://hosted.weblate.org/) now, so hopefully it will work well for anybody else.

- the privacy policy and terms of service need to be specified and linked from the consent screen
- I've changed the logo to use official one in 0f5d993

I believe the issue has been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by skvalex** [comment]
I just got the approval as well.

Thank you for your support, sent you a small donation.
