### ISSUE TITLE
Openshift3 deployment does not fully work

### ISSUE THREAD

**Issue by alesrosina** [WeblateOrg/weblate#2476]
For Weblate to fully work on openshift, there are still two things that needs to be fixed:
- [x] add redis cache
- [x] fix `Failed to generate key: b'No user exists for uid 1000140000\r\n'`error (*)

(*) This error is due to openshift nature of handling users (so `git clone` command will fail) and it is documented [here](https://docs.openshift.com/enterprise/3.1/creating_images/guidelines.html) and we need to use [nss wrapper](https://cwrap.org/nss_wrapper.html). 

Currently Weblate can be deployed to OpenShift, but it is not usable due to second issue, so this needs to be resolved.

**Comment by alesrosina** [comment]
@nijel you can assign this to me, will try to solve it as soon as possible.

**Comment by nijel** [comment]
Thanks! The current OpenShift3 integration is not updated for recent changes and probably had some missing bits even at time of merging see https://github.com/WeblateOrg/weblate/issues/1523 (but you've already found that).

**Comment by nijel** [comment]
Should be now fixed by https://github.com/WeblateOrg/weblate/pull/2477, right?

**Comment by alesrosina** [comment]
Yes, correct. Thanks!
