### ISSUE TITLE
Weblate is unable to deal with private-use subtags

### ISSUE THREAD

**Issue by sschueller** [WeblateOrg/weblate#2478]
**Describe the bug**
Per RFC 4646 and RFC 4647 now collectively BCP 47 (https://www.w3.org/International/articles/language-tags/ , http://www.rfc-editor.org/rfc/bcp/bcp47.txt) private-use subtags are valid language codes. For example `en-US-x-twain` or `de-x-a123` is valid. In our case we use this to translate customer specific strings in our application where `twain` or `a123` is the customer. We would like to manage this in weblate however if we import xliff files with such tags weblate will incorrectly recognise the language code.

**To Reproduce**
1. Create a language in weblate `de-x-a123`
2. Add component with xliff file called comp.de-x-a123.xlf (source-language="de" target-language="de-x-a123")
3. Weblate will auto-create new a language withe code `de_X-G` instead of `de-x-a123`

**Expected behavior**
Languages such as `de-x-a123` are correctly detected

**Server configuration and status**

```
 * Weblate 3.3
 * Python 2.7.13
 * Django 1.11.17
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 2.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 5.3.0
 * python-dateutil 2.7.5
 * lxml 4.2.5
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.7
 * Database backends: django.db.backends.mysql
 * Cache backends: default:LocMemCache
 * Celery: memory://, N/A, eager
 * Platform: Linux 4.9.0-8-amd64 (x86_64)
```

**Comment by nijel** [comment]
This is supposed to be working if the language is created manually. If it would not, some changes might happen if [SIMPLIFY_LANGUAGES](https://docs.weblate.org/en/latest/admin/config.html#simplify-languages) is enabled.

**Comment by nijel** [comment]
Hmm, apparently we're stripping digits to handle some messed up file names since 933fd1a3e71...

**Comment by sschueller** [comment]
I have `SIMPLIFY_LANGUAGES = False`

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
