### ISSUE TITLE
Add Translator Certificate of Origin

### ISSUE THREAD

**Issue by jnavila** [WeblateOrg/weblate#2483]
When talking about integrating the translations into an upstream project, there was a question as to whether the translated content was following the original license. Presently, the licensing is preserved by the DCO (Developer Certificate of Origin) and the `signed-off-by:` lines. As of now, the commits generated by Weblate are not compliant with the requirements.

Would it be possible to have the `signed-off-by:` line added automatically to the commits generated by Weblate for each hunk of each user? 

Otherwise, what is the proposed or existing solutions?

**Comment by nijel** [comment]
You can edit commit messages Weblate creates, it's easy to add this there, just include `Signed-off-by: {{ author }}`. You might want to enforce *Contributor agreement* on component level as well for that.

**Comment by jnavila** [comment]
Excuse-me, but is this option available at hosted.weblate.org? If it is in default administrative privileges, I don't have access at them for git manpages.

Thank you.

**Comment by nijel** [comment]
If you can manage the project, you can find this in component settings:

![screenshot_2019-01-10 phpmyadmin development](https://user-images.githubusercontent.com/212189/50951935-2f7c0500-14af-11e9-9457-516a9f5b1acf.png)

**Comment by jnavila** [comment]
I cannot manage the project git-manpages on https://hosted.weblate.org/projects/git-manpages.

So I guess this option is not available on hosted Weblate.

**Comment by nijel** [comment]
It is, you just need proper permissions. Apparently @Naruto0 who created this project forgot to add you. Sorry about that, I've just added you.

You should now be able to edit the commit messages: https://hosted.weblate.org/settings/git-manpages/translations/#messages

**Comment by jnavila** [comment]
Thanks a lot! :tada:

**Comment by Naruto0** [comment]
Hi @jnavila I asked you to add license file first before i would make you project manager. I was waiting for your response and i got none.

However i see you added the license.
https://github.com/jnavila/git-manpages-l10n/commits/master/LICENSE.txt

So to clear the confusion, i did not made you manager by design. Not by mistake.

**Comment by jnavila** [comment]
Ah, my bad. I thought that the detection of the license file was automatic and I was not aware of the range of privileges granted to open-source projects.

Thanks anyway for letting this project start on WebLate.
