### ISSUE TITLE
Return a Last-Modified header for translation downloads

### ISSUE THREAD

**Issue by Kingdutch** [WeblateOrg/weblate#2484]
**Is your feature request related to a problem? Please describe.**
We're using Drupal to automatically download translations from Weblate as PO files. In order to minimise file downloads Drupal first performs a HEAD request for the PO file and will only actually download the file when a Last-Modified header is present that gives a date that is newer than the last download time.

**Describe the solution you'd like**
The `/download/[project]/[component]/[language]` URL should provide the Last-Modified header with a timestamp that is set to the value of the last change made to the component for that language (similar to what is displayed in the user interface).

**Describe alternatives you've considered**
Hardcoding this header to a value far in the future on the server level. This has some obvious drawbacks as it may break in a few hundred years, however, it's also wasteful in having to download the translations during each check.

**Additional context**

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
