### ISSUE TITLE
Possibility of deleting own history entry

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2486]
https://hosted.weblate.org/translate/gamehub/translations/nb_NO/?type=nottranslated&offset=8#history

Accidentally pasted a YouTube link in history, would like to delete it. 

Edit: This is a really easy mistake to do in Zen-mode. Paste, hit tab, and there it is.

**Comment by nijel** [comment]
I can't find that now, maybe the related strings was removed upstream?

**Comment by comradekingu** [comment]
@nijel
For example I did this, https://hosted.weblate.org/translate/weblate/master/zh_Hans/?type=nottranslated&offset=1#history in the wrong language. Further proving my ability to make mistakes goes beyond the ability to delete them.
