### ISSUE TITLE
Broken translation upload using API

### ISSUE THREAD

**Issue by alexminton** [WeblateOrg/weblate#2487]
To say that I am a Python newbie would be an offence to Python newbies everywhere, but I still try to write a helper for using Weblate's web API (still on openSUSE instance, continuation of #2474 ). I've written a small test for translation POST request and it **almost** works, but changed translations are only accepted as suggestions due to my failure of sending overwrite parameter correctly (or, less likely, Weblate ignorance)
Example code is like this 

```python
import requests

def send_translation(filename):
    """
    send a specified translation file to Weblate
    """
    target_name = '/'.join([TARGET_PATH,
                            filename])
    with open(target_name, 'rb') as file_to_send:
        parse_data = filename.split(sep='.')
        target_url = '/'.join([API_URL+'translations',
                               parse_data[0],
                               parse_data[1],
                               parse_data[2],
                               'file/'])
        wl_response = requests.post(target_url,
                                    headers=API_HEADERS,
                                    data={'overwrite':True},
                                    files={'file': file_to_send})
        wl_response.encoding = 'utf-8'
        print(str(wl_response.status_code) + ": " + filename)
        print(wl_response.json())

API_URL = "https://l10n.opensuse.org/api/"
API_KEY = "here_goes_my_API_key"
API_HEADERS = {'Accept': 'application/json, text/javascript',
               'Authorization': ('Token '+API_KEY)}
TARGET_PATH = '/home/minton/Translations/opensuse-i18n/weblate/ru'

send_translation("yast-services-manager.master.ru.po")
```

File in question has one new translation and response code is 200, but still no overwriting happens.
I have no ability to look at this request on the server side and see what's going wrong there, so maybe I should summon @stanislav-brabec here. Or maybe you just know how to properly push files to requests.post data parameter :)

**Comment by nijel** [comment]
You can look at [how wlc does that](https://github.com/WeblateOrg/wlc/blob/449d6060cb4d47170dfc9dd570102cebdbd35fbb/wlc/__init__.py#L95)

Anyway why not just use wlc for that?

```python
from wlc import Weblate
weblate = Weblate('KEY', 'https://l10n.opensuse.org/api/')
translation = weblate.get_translation('opensuse-i18n/weblate/ru')
with open(target_name, 'rb') as file_to_send:
    translation.upload(file_to_send)
```

(Code not tested, but I think it should work)

**Comment by alexminton** [comment]
I've tried wlc some (long) time ago and it had no upload ability, so that was exactly the cause for pure python attempt.
I've tested your snippet and at first try it failed with exception:
`  File "/usr/lib/python3.6/site-packages/wlc/__init__.py", line 230, in __getattr__
    raise AttributeError(name)
AttributeError: upload`
but after updating from wlc 0.8 to wlc 0.10 the error message was gone, everything exited gracefully and the file was uploaded succesfully, but still only as suggestions, i.e. overwrite still doesn't happen even your way.
I had a look in wlc code (thanks for the pointer!) and everything seems similar to my attempt: form encoded parameters are passed using "data" and file is passed using "files", hence I would be surprised if it worked differently.
So maybe you have any other insight on how to do this properly?

**Comment by nijel** [comment]
The problem (at least in my tests) is that the strings are added as a suggestion instead of translation when using the API...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by stanislav-brabec** [comment]
The fix was backported and deployed into https://l10n.opensuse.org/.
