### ISSUE TITLE
Creating new language with plural in Frontend

### ISSUE THREAD

**Issue by sschueller** [WeblateOrg/weblate#2491]
**Is your feature request related to a problem? Please describe.**
It does not appear to be currently possible to create a new language in the front end. Only in the django administration. We have users that should be able to create new languages but should not be able to log into the django administration. Previously it was possible to limit permissions in the django administration but that is no longer possible since weblate has its own permissions table `weblate_auth_user` now.

**Describe the solution you'd like**
Under Langauges `/languages/` add a button to create/edit new language and add ACL for those features.

**Describe alternatives you've considered**
Add back possibity to give permissions to weblate users to access only parts of the django administration.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
