### ISSUE TITLE
Limit allowed domains when using Google Oauth2

### ISSUE THREAD

**Issue by SeveFP** [WeblateOrg/weblate#2492]
Hi!

First of all thank you very much for such an awesome project!

I've come across a problem that I can't really find out anywhere. 
I'm using https://docs.weblate.org/en/latest/admin/auth.html#google-oauth-2 and I would like to limit registrations for just a certain domain. 

Is that possible somehow? 

Thank you in advance! :)

**Comment by nijel** [comment]
I have no clue, sorry. But the python social auth doesn't mention anything like this: https://python-social-auth.readthedocs.io/en/latest/backends/google.html#google-oauth2

**Comment by SeveFP** [comment]
Hey @nijel !

Thank you for your fast reply.

I will come back if I happen to find out how to answer this question :+1: 

Thank you again :)

**Comment by nijel** [comment]
Looking at the social-auth code for different reason now and I've noticed [SOCIAL_AUTH_WHITELISTED_DOMAINS](https://python-social-auth-docs.readthedocs.io/en/latest/configuration/settings.html#whitelists), that should do the trick for you.

**Comment by drzraf** [comment]
It does exists (https://github.com/python-social-auth/social-app-django/issues/180) and is documented [here](https://python-social-auth.readthedocs.io/en/latest/configuration/settings.html#whitelists) (and would be **very** useful if supported by Weblate)

**Comment by drzraf** [comment]
In the docker setup I tried `WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS=['myGSuiteDomain.com']` but I can still register using a plain @gmail.com email address.

**Comment by nijel** [comment]
There is no need for special support in Weblate, just put that line into `settings.py`. Patches to cover this in the Weblate documentation are welcome.

**Comment by drzraf** [comment]
1. There is no `settings.py` in the Docker version (and not explanation why so. Is that taking everything from the environment?)
2. I used the above-mentioned variable (**with** the `WEBLATE_` prefix, without success). Any documentation about prefixing (or not prefixing) here?

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/install/docker.html#further-configuration-customization

**Comment by drzraf** [comment]
`SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS=['myGSuiteDomain.com']`
(inside `docker exec -ti weblate_weblate_1 cat /app/data/settings-override.py`) seems to have done it

Thank you
