### ISSUE TITLE
Return "Edit user" privilege back in a better way

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#2493]
If I remember correctly, it was possible to assign Edit user privilege in old Weblate versions. In Weblate-3.3 I found no way to accomplish it. Except a Superuser status.

It would be nice to return this feature. Or actually a better feature:

1. (The most important.) Assign a new privilege: Group administrator(s): user(s) who can add users to the particular group without superuser privileges. Example: member of "Approved Czech Translators@Administration" could add users to group "Approved Czech Translators".

2. (Less important.) Make a limited possibility to add new groups by a non-superuser. Example: approved user can add group e. g. "Approved Hindi Translators" and assign its administrator. The limitation could be based on transitivity: Approved user can assign only privileges owned by that user.

**Comment by nijel** [comment]
This is certainly planned, see https://github.com/WeblateOrg/weblate/issues/2127 and https://github.com/WeblateOrg/weblate/issues/2363.

**Comment by nijel** [comment]
I'm closing this as I don't see what would be missing.

* https://github.com/WeblateOrg/weblate/issues/2127 is already implemented for some time. 
* Project-wide admins can create additional teams.
* Site-wide there is `user.edit` permission which can be used to create teams.
