### ISSUE TITLE
Approved property is off in exported xliff for translated units

### ISSUE THREAD

**Issue by mclei-asw** [WeblateOrg/weblate#2494]
**Describe the bug**
I am using XLIFF files. Originally the imported units do not have approved flags when they are not translated. After translating in Weblate with reviews switched off, the exported XLIFF contains approved="no" for these units.

**To Reproduce**
1. Disable reviews
2. Import XLIFF with units without translation and without approved flags
3. Translate units in Weblate
4. Export XLIFF

**Expected behavior**
approved property in XLIFF for translated units should be "yes"

**Server configuration and status**
- Weblate 3.3 installed through pip
- "Enable reviews" should be off

**Comment by nijel** [comment]
Why do you think approved property should be set to yes with reviews disabled? There was no approval process, so there is no reason to set it to yes.

Looking at the [XLIFF specs](http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#approved) the default value for the `approved` attribute is `no` so IMHO Weblate behaves according to the specification here.

**Comment by mclei-asw** [comment]
You a right. It was my misconception to automatically set approved, when reviewing is disabled. But then it should be enough when state is translated.
