### ISSUE TITLE
Markdown syntax check

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2495]
**Is your feature request related to a problem? Please describe.**
Many projects use Weblate to edit text files using markdown (and extracted through po4a).

**Describe the solution you'd like**
Weblate should provide quality check for markdown markup.

**Additional context**
Example project can be seen at https://hosted.weblate.org/projects/f-droid/website-posts/

Example po file: https://gitlab.com/fdroid/fdroid-website/blob/master/po/_posts.cs.po

**Comment by emmapeel2** [comment]
someone mentioned https://github.com/MihaZupan/MarkdownValidator

**Comment by eighthave** [comment]
I have a very basic script that check links in Markdown.  I could probably port those to Weblate checks pretty easily.  But a more complete solution would be nicer.  Here is my script:
* https://gitlab.com/fdroid/fdroid-website/blob/1.72/tools/check-page-links.py

@matrixcoffee FYI

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. I've implemented checks which I think make sense (links, link references and inline markup).

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by sajolida** [comment]
Hi @nijel, I'm really happy to see this implemented!

I'm not really good at reading Python, so can you clarify if these checks cover, for example, missing or extra `*` for bold and italic?

For example:

* Good Markdown: `This is **bold** and this is *italic*.`
* Bad Markdown: `This **bold* is broken.`

**Comment by nijel** [comment]
So far it does check if markup in translation is same as in source.

**Comment by sajolida** [comment]
Of course! This sounds like an excellent approach :)

**Comment by eighthave** [comment]
One thing I see __a lot__ in translations is a space between `]` and `(` that breaks the Markdown link syntax, e.g. `'[Použij Weblate] (https://weblate.org/)`.  That would be a good test case to have for this.

**Comment by nijel** [comment]
It does catch this (just to be sure, I've just added this to the testsuite).

**Comment by eighthave** [comment]
The other one that I see quite commonly is that translators translate the strings in the URL portion of the Markdown link.  That of course breaks the link.  That's also in https://gitlab.com/fdroid/fdroid-website/blob/1.72/tools/check-page-links.py  Basically, I store all links that are in the source string, then for each link found in the translation string, I check to make sure it is in the list of source string links.

**Comment by eighthave** [comment]
The hard part with that check is that some sites might want to change all links to force the page to use the localized version, but I haven't seen that case in the stuff I've worked out.

**Comment by nijel** [comment]
Currently it doesn't trigger on changed URL, exactly for reason that it might be valid to change them to locale specific in some cases.

**Comment by eighthave** [comment]
On our site, we almost always use relative links for internal links, then the locale is inherited from the page, and doesn't need to be in the actual link itself.  I think this is a relatively common setup for localized websites.  And so far, no one has found a localized link for any of the external links that are included.

**Comment by emmapeel2** [comment]
With ikiwiki most of the links are locale-agnostic, but the inlines need to be changed (add the locale at the end as .es with Spanish)

**Comment by nijel** [comment]
Okay, maybe it makes sense to check relative links for being same.

**Comment by marcbria** [comment]
Sorry @nijel is this included in last weblate relase?
In other words, is weblate markdown ready?

**Comment by nijel** [comment]
What do you mean by "markdown ready"? It can validate markdown syntax in the strings, it can not parse markdown files, see https://github.com/WeblateOrg/weblate/issues/3106

**Comment by marcbria** [comment]
I was asking if is able to work with ".md" files, so you answered my question.
Thanks a lot.
