### ISSUE TITLE
Broken sync of plural strings

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2496]
**Describe the bug**
The pending plural strings are not properly saved, Weblate reports disappeared string:

```
weblate/master/fr: message Weblate/Application - French, string 1795 disappeared!
```

**To Reproduce**
1. Edit string with plurals
2. Force commit

**Expected behavior**
Updated unit appear in the file.

**Additional context**
This is broken since 139f484df92806a262e4177b38a69c7658e4f38f.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has been fixed by 18d084dcdffff99a6434236aae1e710ca0868299.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
@stanislav-brabec you might want to apply this fix on your installation.

**Comment by stanislav-brabec** [comment]
The fix was backported and deployed into https://l10n.opensuse.org/.
