### ISSUE TITLE
Hide/show locked projects

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2498]
https://hosted.weblate.org/accounts/profile/#preferences
has a setting for hiding finished translations, an option to hide locked ones right next to it would be nice. From my point of view it should be checked by default.
Projects like https://hosted.weblate.org/projects/bauble/ are only there for the translation memory, and will never be opened. (It is the project Ghini is forked from (?))

**Comment by nijel** [comment]
I'm not really sure how useful it will be. In most cases locking is used to temporary restrict editing (eg. when updating the translation files in the repository) and I don't think it makes sense to hide projects for this short period.

The constantly locked projects on the other side should be probably removed, they really just consume resources without being useful.

**Comment by nijel** [comment]
I'm just going through locked projects. Most of them really should have been deleted and the reason they are locked is that there was no UI to delete project in Weblate. Some were apparently forgotten in the locked state and I've unlocked those. So we're now down to single locked component :-).

**Comment by comradekingu** [comment]
This is great, thank you.
