### ISSUE TITLE
Can STARTTLS be configured in the email setup ?

### ISSUE THREAD

**Issue by erionsina** [WeblateOrg/weblate#2502]
Hi guys,
thank you for this platform. I'm having some issues during the configuration of the email
Can STARTTLS be configured in the email setup ?
Thanks

**Comment by ShadowXVII** [comment]
I get ```Can not send email (SMTP AUTH extension not supported by server.), please check EMAIL_* settings```

But I'm not sure if it's related -- I had thought email_use_tls might not have been working.

Using Office 365 @erionsina ?

**Comment by erionsina** [comment]
> Yes, just use [EMAIL_USE_TLS](https://docs.djangoproject.com/en/2.1/ref/settings/#email-use-tls).

Thank you, it worked.

**Comment by erionsina** [comment]
> I get `Can not send email (SMTP AUTH extension not supported by server.), please check EMAIL_* settings`
> 
> But I'm not sure if it's related -- I had thought email_use_tls might not have been working.
> 
> Using Office 365 @erionsina ?

I'm using private mail server for this not Office365

**Comment by hhyyrylainen** [comment]
It would be really handy if this was mentioned in the documentation that weblate links to when you get an email send error: https://docs.weblate.org/en/weblate-4.3.2/admin/install.html#out-mail

**Comment by nijel** [comment]
@hhyyrylainen patches to improve the documentation are always welcome ;-)

**Comment by ilkarataev** [comment]
I am using last docker-compose and have the same issu but EMAIL_USE_TLS=TRUE didn't help me

`weblate_1   | check stderr | CRITICALS:
weblate_1   | check stderr | ?: (weblate.E003) Cannot send e-mail (SMTP AUTH extension not supported by server.), please check EMAIL_* settings.
weblate_1   | check stderr | 	HINT: https://docs.weblate.org/en/weblate-4.3.2/admin/install.html#out-mail`

**Comment by BasicPro** [comment]
Hey guys, I get this error too, I've tried everything in this posts and others with no success. I'm using Docker. Everything else is working perfectly. 

These are some of my email settings:
 ```
 environment:
      - WEBLATE_ENABLE_HTTPS=1
      - WEBLATE_EMAIL_HOST=mail.masteringbox.com
      - WEBLATE_EMAIL_HOST_USER=weblate
      - WEBLATE_EMAIL_HOST_PASSWORD=<password>
      - WEBLATE_EMAIL_HOST_PORT=587
      - WEBLATE_EMAIL_USE_TLS=1
      - WEBLATE_IP_BEHIND_REVERSE_PROXY=1
      - WEBLATE_SECURE_SSL_REDIRECT=1
```

The error:
```
weblate_1   | check stderr | CRITICALS:
weblate_1   | check stderr | ?: (weblate.E003) Cannot send e-mail (STARTTLS extension not supported by server.), please check EMAIL_* settings.
weblate_1   | check stderr | 	HINT: https://docs.weblate.org/en/weblate-4.4.2/admin/install.html#out-mail
```

This is the mail log in the smtp server
```
Feb  6 13:47:02 mail postfix/smtpd[17060]: connect from sandbox.masteringbox.com[136.243.71.4]
Feb  6 13:47:02 mail postfix/smtpd[17060]: lost connection after EHLO from sandbox.masteringbox.com[136.243.71.4]
Feb  6 13:47:02 mail postfix/smtpd[17060]: disconnect from sandbox.masteringbox.com[136.243.71.4] ehlo=1 commands=1
```

**Comment by nijel** [comment]
> STARTTLS extension not supported by server

Why do you enable `WEBLATE_EMAIL_USE_TLS` when your server does not support it?

**Comment by BasicPro** [comment]
Yeah, that is true. I was getting this error which I get with TLS deactivated:

```
(weblate.E003) Cannot send e-mail (SMTP AUTH extension not supported by server.), please check EMAIL_* settings.
weblate_1   | check stderr | 	HINT: https://docs.weblate.org/en/weblate-4.4.2/admin/install.html#out-mail
```

And that url said: 
"In case you get error about not supported authentication (for example SMTP AUTH extension not supported by server), it is most likely caused by using insecure connection and server refuses to authenticate this way. Try enabling EMAIL_USE_TLS in such case." 

Which is why I tried activating it and then tried other things and didn't put it back to 0.

My mailserver uses STARTTLS in port 587 which is working fine.

**Comment by nijel** [comment]
Most of the servers refuse authentication without SSL, so that's kind of expected.

Going through your configuration, there is no WEBLATE_EMAIL_HOST_PORT, it should be [WEBLATE_EMAIL_PORT](https://docs.weblate.org/en/weblate-4.4.2/admin/install/docker.html#envvar-WEBLATE_EMAIL_PORT).

**Comment by BasicPro** [comment]
Thanks @nijel ! That was the problem. However, I had to turn back on WEBLATE_EMAIL_USE_TLS=1 

environment:
     - WEBLATE_ENABLE_HTTPS=1
     - WEBLATE_EMAIL_HOST=mail.masteringbox.com
     - WEBLATE_EMAIL_HOST_USER=weblate
     - WEBLATE_EMAIL_HOST_PASSWORD=<password>
     - WEBLATE_EMAIL_PORT=587
     - WEBLATE_EMAIL_USE_TLS=1

That worked in the end.

Regards
