### ISSUE TITLE
Gerrit integration

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2504]
Jami has merging errors, and are using Gerrit.
There is no mention of Gerrit on https://docs.weblate.org/en/latest/vcs.html
Can the generic Git one be used, and if so, is there still a write-up possible for how to do it?

**Comment by nijel** [comment]
There is specific Gerrit backend, the docs is indeed missing.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
