### ISSUE TITLE
Show authoritative Terms of Service

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#2506]
**Is your feature request related to a problem? Please describe.**
The Terms of Service new users need to accept when signing in to Weblate.org are partially localised, partially in English. The page says "The Terms of Service document is authoritative in English, translations are provided for your convenience.". However, there appears to be no way to view the untranslated, authoritative version.

**Describe the solution you'd like**
Either disable translations for Terms of Service (and other pieces of legalese in Weblate, if any) or offer a way to show them in their authoritative form.

**Comment by nijel** [comment]
You can find English version here: https://weblate.org/en/terms/

But you're right that in Weblate it's not really easy to see English version, that should be addressed.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
