### ISSUE TITLE
Better handling of BCP 47 language tags

### ISSUE THREAD

**Issue by apgrucza** [WeblateOrg/weblate#2509]
The translation files in my repository use BCP 47 language tags (e.g. `en-AU`). If I use the **Start New Translation** feature and pick one of the standard languages, the translation is added using the POSIX format (e.g. `en_AU`) as per the language definition in Weblate, which is not suitable for my repository.

I have tried using the administration interface to modify the language definitions to use BCP 47 instead. Although this fixes the problem, when Weblate restarts it automatically creates the standard language definitions in POSIX format, effectively duplicating the BCP 47 ones. (I am running Weblate in Docker.) I do not want these POSIX ones to be available when using the **Start New Translation** feature.

The best solution that I can think of would be to add a setting that tells Weblate to set up the standard languages using the BCP 47 format.

I've considered changing my repository to use POSIX format, but it uses private use subtags (e.g. `en-AU-x-test`) and there does not seem to be a standard way to represent these in POSIX format.

**Comment by nijel** [comment]
What file format and what Weblate version do you use?

This issue was recently addressed in 353703a884219473f2beb573bb38c14da022f70c, df9f2298a01acc4375b68c240903295fc32e2c48 and e78de11db7b2beefb169d876a2b2034ceec52e21. See also #2478 and #2480.

**Comment by apgrucza** [comment]
I am using gettext PO format and the Docker image with tag 'edge'.

I saw #2478 but it’s about how Weblate behaves when pulling translation files from the repo. Pulling works fine for me, even when there are private use subtags. The problem is I end up with duplicate language definitions (e.g. en_AU and en-AU) so the user might pick the wrong one when starting a new translation.

I understand that the PO format is probably not commonly used with BCP 47 language tags. Because I use this format, #2480 does not help as it relates to XLIFF format. Switching to XLIFF format might be possible but would be a big change for me.

**Comment by nijel** [comment]
Right, for Gettext Weblate uses POSIX locales (what makes sense in most cases). Making this configurable could be an option.

**Comment by apgrucza** [comment]
Yes, I was thinking the same thing. Could be either in `settings.py` or a new field on the component (next to **file mask**). Perhaps something like this?

Language code format:
- Automatic, based on file format (default)
- Underscore separator
- Hyphen separator

**Comment by nijel** [comment]
Proposed implementation is in https://github.com/WeblateOrg/weblate/pull/2626

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
