### ISSUE TITLE
Deepl machine translation not working

### ISSUE THREAD

**Issue by qcad** [WeblateOrg/weblate#2510]
**Describe the bug**
Deepl machine translation does not work here.

**To Reproduce**
Enable Deepl machine translation module and configure API key. No translations are offered under Machine Translation tab.

**Expected behavior**
Translations offered from Deepl under Machine Translation tab.

**Server configuration and status**
$ weblate list_versions
 * Weblate 3.3
 * Python 2.7.15rc1
 * Django 1.11.18
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.4.1
 * python-dateutil 2.7.5
 * lxml 4.3.0
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.9
 * pyuca 1.2
 * python-bidi 0.4.0
 * PyYAML 3.13
 * Database backends: django.db.backends.mysql
 * Cache backends: default:MemcachedCache, avatar:FileBasedCache
 * Celery: memory://, cache+memcached://127.0.0.1:11211/, eager
 * Platform: Linux 4.15.0-42-generic (x86_64)

$ weblate check --deploy
SystemCheckError: System check identified some issues:

ERRORS:
?: (weblate.E005) Celery is configured in the eager mode
	HINT: https://docs.weblate.org/en/weblate-3.3/admin/install.html#celery

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

System check identified 4 issues (0 silenced).

**Additional context**
Our DeepL subscription is of type "Advanced" which is supposed to be for "Use within your CAT tool without limits". Deepl API v2 works fine from within out console tools, using REST API. I've noticed that Weblate is using Deepl v1.
Google Translate API works fine in the same Weblate installation but would prefer to integrate Deepl.

**Comment by nijel** [comment]
Ah, they have introduced new API version (without any changes) and changed pricing from last time I looked. Still Weblate as a CAT tool is probably supposed to use API v1 ("version 2 of the DeepL API isn't supported for CAT tools and DeepL plans for CAT tool users").

Does the v1 API work with your API key? It's same as v2, just replace v2 with v1 in the URL. Anyway Weblate should report any errors it gets from DeepL, so you shoul see those in Weblate as well. 

PS: Are you translating between languages DeepL supports (English, German, French, Spanish, Portuguese, Dutch, Italian, Polish, and Russian)?

**Comment by qcad** [comment]
Thanks for your reply.

Yes, API v1 works with our key:
curl -s -X GET "https://api.deepl.com/v1/translate?auth_key=xxx&text=Hello&source_lang=EN&target_lang=FR

And for some reason, Deepl integration in Weblate now also works perfectly fine. Looks like it was a temporary issue or a mistake on my part. Sorry for the noise.

**Comment by ecxod** [comment]
since i also came across the error, i want to draw your attention to the following;
the URL of the API is :

> https://api-free.deepl.com/v2/

and not 

> ~https://api-free.deepl.com/v2/translate~

as in the example on the deepl.com page [https://www.deepl.com/docs-api](https://www.deepl.com/docs-api#headlessui-listbox-label-5)

**Comment by nijel** [comment]
That's how we document it: https://docs.weblate.org/en/latest/admin/machine.html#deepl
