### ISSUE TITLE
Import user permission/privileges from pootle

### ISSUE THREAD

**Issue by devers89** [WeblateOrg/weblate#2516]
Hello,
first of all thank you for weblate. It's a great platform. As our intention is migrating from Pootle to Weblate we have successfully imported users accounts from the prior platform using dumped csv files and formating them for Weblate so far so good. My question is if it is possible to import user privileges/permissions ?

Thanks in advance,
Gerard

**Comment by nijel** [comment]
No, that's not currently possible. Actually nobody asked for that so far :-). Technically it should be possible to implement for most cases, but it would not be easy to implement because of the differences in the access control on both sides.

**Comment by samtuke** [comment]
This is also a major issue for our migration. There are 421 users on our Pootle installation, most of them has edit rights to one or more languages. Manually mapping these in weblate would be a time consuming project. The ability to migrate user permissions automatically, or even semi-automatically, would be very useful.

**Comment by nijel** [comment]
I'm not really sure it's possible to do something like this generic. The permission models are really different on both sides, so there is no simple 1:1 mapping (Pootle grants based on most specific match, while Weblate grants on any match). So my recommended approach would be to solve this migration by some scripting which addresses your particular use case. If you don't have capacity to handle this on your own you can hire me to do this.

**Comment by nijel** [comment]
I don't think there is a generic solution to this problem as the permission system is really different in both apps. As mentioned before, we can help you with this, see https://weblate.org/support/
