### ISSUE TITLE
Introduce a simple "send test email" function to validate SMTP settings

### ISSUE THREAD

**Issue by ShadowXVII** [WeblateOrg/weblate#2517]
**Is your feature request related to a problem? Please describe.**
I find it tricky to test SMTP settings as there's no dedicated "send test email" function in Weblate.

**Describe the solution you'd like**
An admin function would be useful to more easily trigger a notification email to send to the admin's email address. This in turn would validate the SMTP setup.

**Describe alternatives you've considered**
Trying to get other users to submit dummy changes to translations.

**Comment by nijel** [comment]
The `./manage.py check --deploy` does test the SMTP connection and reports if it's broken, but it doesn't try to send actual email.

**Comment by ShadowXVII** [comment]
Cool, good to know.

I'm having trouble with the "from" address and restrictions on the SMTP server side. The sending of an actual email would be a good end to end test.

**Comment by UncleSamSwiss** [comment]
@ShadowXVII: second that! It would be great to have this feature.
@nijel: can you explain how to execute .manage.py inside the docker-compose? Also, the documentation says, one should use `django-admin sendtestemail`, but that doesn't work "as is" in the weblate Docker container (I get an error from python).

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/management.html#invoking-management-commands for docs on executing inside docker.

Good point on [sendtestemail](https://docs.djangoproject.com/en/2.1/ref/django-admin/#sendtestemail), you can certainly use it with Weblate as well.

**Comment by ShadowXVII** [comment]
Tried sentestemail, got the same error as above. A weblate specific test would be nice to make sure it's using accurate "from" addresses, etc.

**Comment by nijel** [comment]
If you're using docker, you need to exec it as `docker-compose exec weblate weblate sendtestemail test@example.com`.

**Comment by ShadowXVII** [comment]
Ohh, I was using django-admin in place of the second weblate. That worked and the test email came through. Some documentation on this should be an adequate fix then.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
