### ISSUE TITLE
mixed CRLF / LF po files confuse weblate

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#2519]
**Describe the bug**
If the imported po file does not consistently use CRLF or LF, then if totally confuses weblate.

**To Reproduce**
1. Import https://github.com/yast/yast-translations/blob/79a5212c449c76f60495731bb439e8fcc3acac28/po/fcoe-client/pl.po
2. 1 string is detected instead of 123.

**Expected behavior**
Parse properly.

**Screenshots**

**Server configuration and status**
 * Weblate 3.3
 * Python 3.6.5
 * Django 2.0.8
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 2.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.16.4
 * Pillow 5.0.0
 * python-dateutil 2.6.1
 * lxml 4.0.0
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2017.3
 * pyuca 1.2
 * PyYAML 3.12
 * Database backends: django.db.backends.postgresql_psycopg2
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.12.14-lp150.12.45-default (x86_64)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
