### ISSUE TITLE
Button for force commit and fix auto commit

### ISSUE THREAD

**Issue by glixx** [WeblateOrg/weblate#2520]
**Is your feature request related to a problem? Please describe.**
Automatic commit does not work good. Sometimes it commits nothing, sometimes not finished translation, but it does not commit when it will be finished.

**Describe the solution you'd like**
Add button to commit force, what is available for translator.

**Describe alternatives you've considered**
Fix auto commit.

**Additional context**
There are files in attachment: upstream_* are from github, weblate_* are from weblate.

[upstream_pianobooster_cs.txt](https://github.com/WeblateOrg/weblate/files/2793791/upstream_pianobooster_cs.txt)
[upstream_pianobooster_ru.txt](https://github.com/WeblateOrg/weblate/files/2793792/upstream_pianobooster_ru.txt)
[weblate_pianobooster_cs.txt](https://github.com/WeblateOrg/weblate/files/2793793/weblate_pianobooster_cs.txt)
[weblate_pianobooster_ru.txt](https://github.com/WeblateOrg/weblate/files/2793794/weblate_pianobooster_ru.txt)

**Comment by glixx** [comment]
Czech and Russian translations were commited today automatically with delay around 1-2 days.

**Comment by nijel** [comment]
Yes, it intentionally takes some time, see https://docs.weblate.org/en/latest/admin/continuous.html#lazy-commits
