### ISSUE TITLE
[XLIFF] Editing source monolingual file with only Source should only update Source

### ISSUE THREAD

**Issue by ShadowXVII** [WeblateOrg/weblate#2521]
**Describe the bug**
Weblate lets you edit the source translation file. When editing a XLIFF that only uses Source strings in the base file, they're not updated correctly. In a monolingual XLIFF file, the `<target>` is redundant.

This is related to #2481.

For example:

```
<?xml version='1.0' encoding='UTF-8'?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" source-language="en-US" target-language="en-US" original="Translation">
    <body>
      <group id="body">
        <trans-unit id="123456789" size-unit="char" translate="yes" xml:space="preserve" approved="yes">
          <source>Original String</source>
          <target>Original String</target>
        </trans-unit>
      </group>
    </body>
  </file>
</xliff>
```

**To Reproduce**
Use the following file as a "base" file, then edit or approve the translation:

```
<?xml version='1.0' encoding='UTF-8'?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" source-language="en-US" target-language="en-US" original="Translation">
    <body>
      <group id="body">
        <trans-unit id="123456789" size-unit="char" translate="yes" xml:space="preserve">
          <source>Original String</source>
        </trans-unit>
      </group>
    </body>
  </file>
</xliff>
```

**Expected behavior**
- If the translation is edited, then the `<source>` element should be updated, instead a `<target>` element is created.
- If the translation is the same as the `<source>`, then no `<target>` element should be created. Source can remain as-is and it can be marked as Done,

**Additional context**
Interestingly, the "Group" element is maintained which is awesome. I assume this is because Weblate isn't regenerating the entire file but just making changes. This means no fix for "base" file edits will be required in #2482 (still required for translations though).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
