### ISSUE TITLE
Adding multiple language files

### ISSUE THREAD

**Issue by ripern** [WeblateOrg/weblate#2523]
I've been trying to configure Weblate to pull in my existing PO files (3 of them) from repo. File mask field says: "Path of files to translate relative to repository root, use * instead of language code, for example: po/*.po or locale/*/LC_MESSAGES/django.po."

so I wrote
`src/locales/*/*.po`

but then I got:
![image](https://user-images.githubusercontent.com/515357/51745062-04460800-20a2-11e9-8abb-adb0cd5b92b3.png)

Then I found someone saying I have to create one component per language. That doesn't sound right?
After many tries I just put the path to my English file
`src/locales/en/*.po`
which worked.

How do I add my other language files now? I would like them listed next to the English one like I've seen in other projects so I doubt creating a new component would solve that.
I see it as

* 1 Project (has N Components)
   * myApp -> N languages
   * myOtherApp -> N languages

Also, the English one got named  "messages (generated)". Is it possible to rename that to "English"?

The top of my locales/en/messages.po looks like:
```
msgid ""
msgstr ""
"POT-Creation-Date: 2018-11-14 18:04+0100\n"
"Mime-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: @lingui/cli\n"
"Language: en\n"
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"PO-Revision-Date: \n"
"Last-Translator: \n"
"Language-Team: \n"
"Plural-Forms: \n"

#: src/views/AddContactView.jsx:67
msgid "addContact.title"
msgstr "Importing contact from"
```

Cheers

**Comment by nijel** [comment]
From the error it seems that you should use `src/locales/*/messages.po`. You can add other translation files later (either manually using `weblate://` URL to share the repo) or using discovery.

Anyway using new in app interface for adding components should be able to suggest you correct settings: https://docs.weblate.org/en/latest/admin/projects.html#adding-translation-projects-and-components

**Comment by ripern** [comment]
Starting over and using the new interface for adding components ("Add translation component" in the project view) worked great! Now I see English (source), Finnish, Korean under languages.
Thanks!

I read about discovery at https://docs.weblate.org/en/latest/admin/addons.html#component-discovery. If instead manually using weblate url, where do I do that?

**Comment by nijel** [comment]
On component it's in the manage/addons menu.

**Comment by ripern** [comment]
Right, but regarding the manual way using weblate url?

**Comment by nijel** [comment]
Just add another component and instead of actual repository URL enter `weblate://project/component`, see https://docs.weblate.org/en/latest/vcs.html#weblate-internal-urls

**Comment by ripern** [comment]
Just to make things clear: When I just the new app interface for adding components and I added one which imported my 3 translation files (3 x messages.po for en, fi, ko languages). Is that seen as 1 component or 3 components from your perspective? I see it as 1 (the UI seem to show it as 1 from what I can see).

**Comment by nijel** [comment]
You need to have one component per file. Use star in the mask to identify language. For example `src/locales/*/messages.po`. If there is other file, then add another component with `weblate://project/messages-component` as repository URL (so that repository is shared) and use mask for other file, eg. `src/locales/*/other.po`.

**Comment by ripern** [comment]
I might misunderstand again, but do you mean one component per filename then?  All my language files are called messages.po, hence the file mask matching that. 
Eg.
src/locales/en/messages.po
src/locales/fi/messages.po
src/locales/ko/messages.po
etc.

and as seen below it shows up as 1 component (called Home) with 3 languages
![image](https://user-images.githubusercontent.com/515357/52127444-5e127900-2632-11e9-8473-3c24c1a7713a.png)

**Comment by ripern** [comment]
Great, so given that I add a language locally, eg. src/locales/fr/messages.po
Should it be enough to do a git pull in Weblate for it to show up as a language in the UI?

**Comment by nijel** [comment]
Yes.
