### ISSUE TITLE
Microsoft Translator never returns a translation

### ISSUE THREAD

**Issue by ccMatrix** [WeblateOrg/weblate#2524]
**Describe the bug**
I have setup machine translation using cognitive services for Microsoft Translator. There is a request to the backend at /js/translate/microsoft-translator/12340/ to get the translation. But the response is always the same: no translations. The responseStatus of the call is always 200.

**To Reproduce**
1. Open any translation component
2. navigate to a translation text
3. select machine translation tab
4. tab remains empty

**Expected behavior**
I expected the translations array to contain the correct translations.

**Screenshots**
![2019-01-25_17h05_05](https://user-images.githubusercontent.com/96917/51757360-71b66080-20c3-11e9-86f5-9dfc6d2c5b58.png)

**Server configuration and status**
```
./manage.py list_versions
 * Weblate weblate-3.4
 * Python 2.7.12
 * Django 1.11.16
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 2.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.7.4
 * Pillow 5.3.0
 * python-dateutil 2.7.5
 * lxml 4.2.5
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * diff-match-patch 20121119
 * pytz 2018.7
 * pyuca 1.2
 * python-bidi 0.4.0
 * PyYAML 3.11
 * Mercurial 3.7.3
 * Database backends: django.db.backends.postgresql_psycopg2
 * Cache backends: default:RedisCache
 * Celery: memory://, N/A, eager
 * Platform: Linux 4.15.0-1036-azure (x86_64)


./manage.py check --deploy
SystemCheckError: System check identified some issues:

ERRORS:
?: (weblate.E005) Celery is configured in the eager mode
        HINT: https://docs.weblate.org/en/weblate-3.4/admin/install.html#celery

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.4/admin/install.html#collecting-errors

System check identified 3 issues (0 silenced).
```

**Additional context**
application is hosted on azure vm and is running behind an nginx webserver.

**Comment by nijel** [comment]
At first look it seems they have changed the API without keeping compatibility for the previous one:

https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-translate?tabs=curl

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by ccMatrix** [comment]
Just wanted to confirm, that the fix is working. Thank you very much and have a nice day!
