### ISSUE TITLE
Is there a way to get rid of new line header changes in PO file?

### ISSUE THREAD

**Issue by ripern** [WeblateOrg/weblate#2527]
I'm using gettext monolingual PO files and the library [Lingui](https://lingui.js.org/tutorials/react.html). When I add a string and run lingui extract to extract it to messages.po it updates a header property (as seen in picture below) which is shown on one line, but then when translating a string in Weblate it puts that header property on two lines, probably because it exceeds 80 characters? Is it possible to tell Weblate to increase this limit? It's just annoying getting unnecessary changes.

![image](https://user-images.githubusercontent.com/515357/51905783-7d0ad400-23c2-11e9-9e60-7c5de84bcd05.png)

Cheers

**Comment by nijel** [comment]
I was already trying to address this by https://github.com/translate/translate/pull/3773, but apparently it's still not working in some cases.

**Comment by nijel** [comment]
Can you please specify what Weblate and translate-toolkit versions do you use?

**Comment by ripern** [comment]
Weblate 3.4. What does translate-toolkit refer to? I'm using lingui 2.7.2 in my react web app. When I add a new language using it locally it doesn't add any Language-Team header but when translating strings in Weblate the Language-Team header is added. Another solution would be to configure that so Language-Team isn't added at all, if possible.

**Comment by nijel** [comment]
You can disable updating Language-Team header in the project settings.

**Comment by ripern** [comment]
The only one I can find in settings is
![image](https://user-images.githubusercontent.com/515357/54754313-7e4ac700-4be3-11e9-9afb-0b4aea27374c.png)
and that's **Translation-Team** header. Did you mix them up or is there a way to disable **Language-Team** also?

Cheers

**Comment by nijel** [comment]
Ah, the description is wrong then, it actually disables the `Language-Team` header.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by ripern** [comment]
Do you mean that only the description was wrong (or something in the weblate code as well)? Because I have Weblate 3.4 and that setting unchecked, but still it updates the Language-Team header in my translation files. Was it perhaps fixed in a later version of Weblate?

**Comment by nijel** [comment]
Yes, just the description, the code was always optional:

https://github.com/WeblateOrg/weblate/blob/e75b1a2e2f2e8b617a0268da197a6fd5035d1302/weblate/trans/models/translation.py#L605-L610

**Comment by ripern** [comment]
But isn't it strange then that I have it unchecked, but the Language-Team header is still being updated by Weblate?

**Comment by nijel** [comment]
It's not being updated, it just stays there. There is apparently also some issue with line wrapping...
