### ISSUE TITLE
per segment ignore-same are not applied from upstream

### ISSUE THREAD

**Issue by jnavila** [WeblateOrg/weblate#2529]
**Describe the bug**

We're using a script to automatically copy untranslatable strings and mark them ignore-same, but when merged back into Weblate, this is not reflected on the website.

**To Reproduce**
1. See https://raw.githubusercontent.com/jnavila/git-manpages-l10n/master/po/documentation.fr.po and search for "--[no-]progress"  and check that the flag `ignore-same` is set
2. Go to https://hosted.weblate.org/translate/git-manpages/translations/fr/?type=check:same
3. See status "unchanged translation" for the same entry.

**Expected behavior**

Translations pushed with tag `ignore-same` should not be flagged with defect.

**Server configuration and status**

Viewed on hosted.weblate.org as of 2019-01-30

**Comment by nijel** [comment]
Thanks, this is apparently case which was not considered so far - in most cases the flags editing happens in Weblate and not on the git side....

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
I've also updated checks for this project now.

**Comment by jnavila** [comment]
Sorry, but that does not seem to work correctly. Some new commits where pushed and the entries previously unflagged are now flagged with "same translation".

**Comment by nijel** [comment]
Maybe because it was not yet deployed? :-) I've deployed it about hour ago, not sure when you've pushed the changes...

**Comment by jnavila** [comment]
About an hour ago :clown_face: . Maybe a small race condition then.

**Comment by jnavila** [comment]
I tried again tonight. But no way.

**Comment by nijel** [comment]
Ah, there is also *different* issue when specifying multiple flags this way. I've just fixed that and will deploy that shortly.
