### ISSUE TITLE
Add "Select all" button

### ISSUE THREAD

**Issue by akcansoft** [WeblateOrg/weblate#2537]
Please add "Selact all" button for source strings
and Move "Copy to clipboard" button right to left. 
![addbutton](https://user-images.githubusercontent.com/7031346/52162529-3b419c80-26e6-11e9-9785-c881fffe8931.jpg)

**Comment by nijel** [comment]
Why select all? The copy does copy it all already...

**Comment by akcansoft** [comment]
It is required for right click menu

**Comment by nijel** [comment]
You can already copy the whole text by clicking on the button. And I think that all current browsers will select a paragraph by tripple click, so I really don't see much reason to pollute UI with another button. Not that I'm happy with current placement of the copy button, it could be indeed integrated better.

**Comment by akcansoft** [comment]
![image1](https://user-images.githubusercontent.com/7031346/52178735-2434a480-27e3-11e9-83ca-ec71e7bf9aa8.png)
I use this Chrome extension
[https://chrome.google.com/webstore/detail/one-click-translate/anhjddeakbabimdgmonfbnpbainknbfa](url)

**Comment by nijel** [comment]
Still tripple click will work for that without needing any changes...

**Comment by akcansoft** [comment]
Ok
