### ISSUE TITLE
nested JSON outputs arrays with []

### ISSUE THREAD

**Issue by sr258** [WeblateOrg/weblate#2538]
I want to use Weblate to translate libraries of [the H5P project](https://h5p.org) and they use nested JSON for their language files. This seems to be very similar (or identical?) to how the language files of Chrome Web Extensions work. The files they work on look like this:
![list without key](https://user-images.githubusercontent.com/15268740/52167367-431b3400-271a-11e9-8b7c-e75b837362be.png)

The H5P language files are parsed by Weblate just fine, but the JSON files Weblate produces are structured differently from the original ones because it outputs arrays with array indexes instead just putting in unnamed objects. This is what Weblate outputs (same content as above):
![list with key](https://user-images.githubusercontent.com/15268740/52167415-e66c4900-271a-11e9-9605-9bc6291e14b9.png)

I'm not sure if this is even valid JSON and I certainly don't want to submit files to the H5P maintainers that are structured differently from the originals. 

Is this behaviour a bug or does it work as desired?
Can I somehow configure Weblate to output JSON in the way I want it? 
I've seen that there is an add-on that allows you to change how JSON output is formatted. If there is not way of configuring Weblate in the desired way, would creating a copy of this add-on and adding code that reformats the JSON files be the best way of achieving this? Or is there an easier one?

**Comment by nijel** [comment]
You need this fix on the translate-toolkit: https://github.com/translate/translate/pull/3836, it's not yet part of any release.
