### ISSUE TITLE
Automatic translations/suggestions addon

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2541]
**Is your feature request related to a problem? Please describe.**
We already have quite some sources which could be used to give automated suggestions for translations and those should be utilized.

**Describe the solution you'd like**
For any project having suggestions enabled, there will be regular (eg. daily) job to automatically add suggestions for untranslated strings based on internal sources with 100% matches:

- translation memory
- glossary terms 

**Describe alternatives you've considered**
The suggestions are shown in the machine translation tab, but having them explicit will make them more visible.

**Comment by comradekingu** [comment]
Maybe they can be grayed out, to signify that they are auto-translations?
In Launchpad, it is possible to click an auto-translation and go back to its origin, meaning one can fix erroneous suggestions. It works both ways, less time spent typing, and more time spent fixing translations that are "done".

**Comment by comradekingu** [comment]
I don't think automatic suggestions are a whole lot faster, they would mostly be viable and available for short strings, which take about as much time to go through as manually entering them, especially as suggestions are only available in the non-Zen editor.

How to gauge mostly, and make them viable where it counts?

Adding them as translations "needing work" is what would help matters. It is a shotgun approach, it is easy to do, but it is also a bit messy. Coverage will go up a lot, but so will the amount of erroneous translation.
So how does one avoid confusion and false positives?

"Needing work" should be split into upstream string needs work, and translation needs work.
Autotranslations fall into the latter.

This does however not solve the real issue, differentiating between true positives, (which should be translations) and potential matches (which should be suggestions).

How about making a meta-project component in Weblate that has the * most common strings from all the available strings for translation.
If all the suggestions from machine translation in it are clickable, that would make for an easy way to make a vetted "dictionary" of (for the first however many) single words or terms, and an easy way to sanitize it. Go through the 1000 most common ones, and that is the _1000_ most common strings "done". Or, lets say 500. That is 500 very common strings that will never have anything but a 1:1 relation. One string, one possible translation.

The second step would be to mark all the machine translations of a source string as reviewed in a language, and have any new strings that differ from this raise a warning/error check.

This could be expanded to also encompass mentions of a word.

Using it in English would be a quick way of getting to all instances of "GTK+" (that should now all be just "GTK", following the renaming), without firing off searches at random, that are then "lost".

This amounts to having a language/platform-wide dictionary, and meta-terms could be added even if they are not found in any real component. So they would be in hosted/language/dictionarycomponent.

That needs the functionality of being able to add strings to a component, which I supposed could be solved short term by just having it be 1000 "empty" and editable strings to start with.

The dictionary would gain strength by being reviewed by many people, so review status per translator is needed, a most fitting feature, seeing as only the translators ability is what is primarily trusted in Weblate.

In review mode, which is something the platform should engage as much as being somewhere for translators to translate, one would see the auto-translator user strings first by default, and then ones own selection of users after that, possibly with some preference, or ability to see strings by date. Nothing should be stale, and nothing should be fresh and unchecked. That is the new "language admin" thing to do.

When people get feedback on their changed strings, eventually they learn, or avoid malicious editing of something they hold insight of.

No more component setting pollution by being able to upload strings in many places.

From what I understand the TM already has meta-terms, a class of strings found in the corpus committed to TM by any component.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
