### ISSUE TITLE
Huge memory consumption during search

### ISSUE THREAD

**Issue by SlavekB** [WeblateOrg/weblate#2543]
**Describe the bug**
I tried to use the search by source string to find the component. During the search, I watched the memory consumption of the weblate wsgi process (Apache). The peak was 1.3 GiB.

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Tools / Search'
3. Enter some string as query
4. Scroll down to 'Search' button
5. See memory consumption during search

**Expected behavior**
During search, memory consumption will not reach astronomical heights :)

**Server configuration and status**
```
 * Weblate 3.4
 * Python 2.7.13
 * Django 1.11.15
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 2.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 5.2.0
 * python-dateutil 2.7.3
 * lxml 4.2.5
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * diff-match-patch 20121119
 * pytz 2018.5
 * pyuca 1.1.2
 * PyYAML 3.12
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 3.16.6-042stab134.46 (x86_64)
```
```
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E009) The Celery tasks queue is too long, either the worker is not running or is too slow.
        HINT: https://docs.weblate.org/en/weblate-3.4/admin/install.html#celery

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.4/admin/install.html#collecting-errors

System check identified 2 issues (0 silenced).
```
**Additional context**
I updated to 3.4 shortly to check that the problem on Weblate 3.3 persists also on 3.4. I do not know if the celery queue is long for that reason or for some other. The celery daemon is properly run.

**Comment by nijel** [comment]
Most likely this is related to some issues within Whoosh, the fulltext engine we use, for example see https://github.com/whoosh-community/whoosh/issues/492.

Do you see some errors in the celery logs? Can you post logs from the Celery daemon serving the search queue? It can be occasionally stuck by doing index cleanup, what should in the end improve the performance, so that might be reason why queue is (temporarily) long.

**Comment by SlavekB** [comment]
Note: I have a patch from [whoosh#522](https://github.com/whoosh-community/whoosh/pull/522) already applied.

From yesterday's upgrade to Weblate 3.4, search log is very short and uninteresting:
```
[2019-02-04 18:50:54,660: INFO/MainProcess] Connected to redis://localhost:6379//
[2019-02-04 18:50:54,669: INFO/MainProcess] mingle: searching for neighbors
[2019-02-04 18:50:55,694: INFO/MainProcess] mingle: sync with 1 nodes
[2019-02-04 18:50:55,694: INFO/MainProcess] mingle: sync complete
[2019-02-04 19:46:48,585: INFO/MainProcess] Received task: weblate.trans.tasks.cleanup_fulltext[2683f633-a958-4267-a200-8c1405536c13]
[2019-02-04 19:46:48,588: INFO/MainProcess] Received task: weblate.trans.tasks.optimize_fulltext[b6a5a3b0-1688-41b5-a039-79376a432624]
[2019-02-04 23:58:20,474: INFO/MainProcess] Received task: weblate.trans.tasks.optimize_fulltext[b6a5a3b0-1688-41b5-a039-79376a432624]
[2019-02-05 01:43:44,366: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:30318 exited with 'signal 9 (SIGKILL)'
[2019-02-05 01:43:44,425: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL).',)
Traceback (most recent call last):
  File "/var/lib/weblate/local/lib/python2.7/site-packages/billiard/pool.py", line 1223, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).
```
As I expected, worker was killed by OOM Killer.

**Comment by nijel** [comment]
Okay, so it's the index cleanup (optimize_fulltext) task consuming this memory. It's ironical as it's main goal is to shrink segmented indices to reduce memory usage when searching.

Can you please provide list of index files in DATADIR/whoosh? Probably the source ones are the most interesting (as they are typically the biggest ones), so `ls -lah data/whoosh/*source*` would be interesting to see.

**Comment by SlavekB** [comment]
After restarting the celery daemon I waited until weblate.trans.tasks.optimize_fulltext is completed:
```
-rw-r--r-- 1 www-data www-data 701K Feb  5 17:04 data/whoosh/_source_868.toc
-rw-r--r-- 1 www-data www-data 383K Feb  5 16:54 data/whoosh/source_4xw18uahlk3l3mba.seg
-rw-r--r-- 1 www-data www-data  81K Feb  5 16:54 data/whoosh/source_6hnarnva3i7l5z7u.seg
-rw-r--r-- 1 www-data www-data 316K Feb  5 16:59 data/whoosh/source_89xkrpuwxip0853u.seg
-rwxr-xr-x 1 www-data www-data    0 Nov 24 20:35 data/whoosh/source_WRITELOCK
-rw-r--r-- 1 www-data www-data 1.5G Feb  5 14:17 data/whoosh/source_smlarqgfdqlgijhl.seg
```

**Comment by nijel** [comment]
That's nothing extraordinary and looks in a good shape. The only major difference I see to my deployments (which have bigger indices) is that I run Python 3...

**Comment by SlavekB** [comment]
So do you recommend switching from Python 2.7 to Python 3.5?

**Comment by nijel** [comment]
I'm not sure if that will maky any difference, I just looking at differences between your setup where the problem appears and mine where it works fine while having bigger index size...

Do you see the problem with the optimized index as well? Or it now works well and was only problematic before? In that case you might be updating it more often what could lead to bigger issue with deleted entries in it (any update is in fact deleting old entry and creating new one).

**Comment by SlavekB** [comment]
I tried searching. The wsgi process had at the beginning 192 MiB, gradually increased to 1.3 GiB, at the end returned to 205 MiB. So search is just as awful as it was.

**Comment by nijel** [comment]
Does the search result have lot of matches? Is the search term you're trying somehow special? What search type do you use?

**Comment by SlavekB** [comment]
I was looking for a string that returns two occurrences for each language. There was no difference in whether I had the specified filter on my language only or whether the occurrences for all languages were returned.

**Comment by SlavekB** [comment]
By the way, recently, celery-search was probably updating the index. Upon completion, he consumed over 600 MiB RAM. And since the release did not take place in 24 hours, I did (again) restart the celery.

**Comment by SlavekB** [comment]
Addition: Search was full text in source string only.

**Comment by nijel** [comment]
At least for the Celery workers I've added workaround to restart them once they consume too much memory in https://github.com/WeblateOrg/weblate/commit/0a3d373e2d88d73246d9e8f03334e4a3cde2d9a2.

**Comment by SlavekB** [comment]
Although I backed 0a3d373 into my instance, I observe the process that processes the celery queue, which at times reaches 1.8 GiB RAM. The web interface in such a situation sometimes ends with 504 Gateway Timeout.

**Comment by SlavekB** [comment]
From /var/log/celery/weblate-celery.log:
[2019-02-19 20:39:10,685: ERROR/ForkPoolWorker-3] child process exiting after exceeding memory limit (1974012KiB / 200000KiB)

...and now worker is a zombie process, probably need to restart celery daemons.

**Comment by nijel** [comment]
I haven't seen the zombie issue, what Celery version do you use?

**Comment by SlavekB** [comment]
Celery 4.2.1 – according to information: https://mirror.git.trinitydesktop.org/weblate/about/

**Comment by nijel** [comment]
Hmm, I'm using that one as well and I haven't met this so far. Anyway this is really just a workaround, the proper solution is to figure out what causes the leaks.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
