### ISSUE TITLE
Component strings to translate are always zero even that original source file contains strings

### ISSUE THREAD

**Issue by HyckoM** [WeblateOrg/weblate#2544]
**Describe the bug**
Component strings to translate are always zero even that original source file contains strings

**To Reproduce**

1. Create new component
2. Fill in required informations
3. Map to valid translations files
4. Confirm new component
5. Open this component from project
6. Check number of strings of source language
7. Download original translation file

**Expected behavior**
All strings of original file available on Weblate to be translated

**Current behavior**
Number of string of all languages is zero. Original file downloaded from Project/Component/Source language (File > Download original translation file) contains correct number of strings.
There is nothing in logs
Tried to modify existing component and after save there was same problem

**Comment by nijel** [comment]
Can you please provide your component configuration? This looks like you've either chosen wrong format or wrongly set up monolingual translations.

**Comment by nijel** [comment]
At first sight it looks correct, at least I don't see anything obviously wrong. Is the `values/strings.xml` file valid? The other option would be that the parsing didn't complete for whatever reason, you can try forcing rereading by `./manage.py loadpo --force myq/mobile-android`.

You might also consider getting [support or consultation contract](https://weblate.org/support/) to get this sorted out...

**Comment by nijel** [comment]
Nah, didn't find time to respond until the bot kicked it. Anyway few remarks:

* the original file download is the file as is stored in the VCS, so it tells nothing about how Weblate parsed it
* would you mind sharing the file? it might just use some unsupported feature (eg. `string-array`, see https://docs.weblate.org/en/latest/formats.html#android-string-resources)

**Comment by HyckoM** [comment]
Not a problem , here it is 
[app_src_main_res_values_strings.zip](https://github.com/WeblateOrg/weblate/files/2908961/app_src_main_res_values_strings.zip)

**Comment by nijel** [comment]
All strings in the file are marked as non translatable (`translatable="false"`), so that's quite expected that they are not shown in Weblate for translation :-).

**Comment by HyckoM** [comment]
Thats because english is used in weblate as a source and its not supposed to be translatable, for original file for czech doesnt have this variable and its still not showing in weblate 

[app_src_main_res_values-cs_strings.zip](https://github.com/WeblateOrg/weblate/files/2909182/app_src_main_res_values-cs_strings.zip)

**Comment by nijel** [comment]
For monolingual translations Weblate always considers the base language as source of information. The reason for that is that new units get added there and do not exist in the translated files. If you do want English editing in Weblate, just disable it in Weblate (disable *Edit base file*).

**Comment by HyckoM** [comment]
ok so changing the variable in english to true should fix this? Question is nothing had changed in those files basically master branch and develop are the same except develop has a new string, so why did it worked before with master but now doesnt with develop?

**Comment by nijel** [comment]
I think this was recently fixed in Weblate, so that might make the difference - if the other component was not reloaded after upgrade, it stayed in previous state.

**Comment by HyckoM** [comment]
ok so we change the the string from false to true and its working now. Thank you for your help
