### ISSUE TITLE
Plural forms not saved back to Qt .ts file

### ISSUE THREAD

**Issue by qcad** [WeblateOrg/weblate#2546]
**Describe the bug**
Strings which use plural forms ("%n") in Qt translation sources (.ts) are shown correctly in the browser with multiple inputs for the translation. The also seem to be accepted and stored correctly. However, on commit, the translations do not make it back into the .ts file.

Strings without plural forms are saved back fine.

**To Reproduce**
Create translation source (.ts) with plural form, e.g.:
```
...
    <message numerus="yes">
        <location line="+42"/>
        <source>%n path(s) identified...</source>
        <translation type="unfinished">
            <numerusform></numerusform>
            <numerusform></numerusform>
        </translation>
    </message>
...
```
Attempt to translate in Weblate.

**Expected behavior**
The translations to end up back in the .ts file upon commit. Instead, the numerusform elements in the .ts files remain unchanged. The type attribute of the translation element remains "unfinished".

**Screenshots**
User interface (correct):
<img width="417" alt="schermafbeelding 2019-02-05 om 20 33 33" src="https://user-images.githubusercontent.com/1685085/52302548-757c9980-2985-11e9-9271-2943092a2568.png">

Partial contents of file in the git repository (weblate/env/lib/python2.7/site-packages/data/vcs/...) on the server after saving and committing the translation:
<img width="545" alt="schermafbeelding 2019-02-05 om 20 34 07" src="https://user-images.githubusercontent.com/1685085/52302619-ae1c7300-2985-11e9-8a42-bf5d62fa1d07.png">

**Server configuration and status**
weblate list_versions
 * Weblate 3.3
 * Python 2.7.15rc1
 * Django 1.11.18
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.4.1
 * python-dateutil 2.7.5
 * lxml 4.3.0
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.9
 * pyuca 1.2
 * python-bidi 0.4.0
 * PyYAML 3.13
 * Database backends: django.db.backends.mysql
 * Cache backends: default:MemcachedCache, avatar:FileBasedCache
 * Celery: memory://, cache+memcached://127.0.0.1:11211/, eager
 * Platform: Linux 4.15.0-42-generic (x86_64)

weblate check --deploy
SystemCheckError: System check identified some issues:

ERRORS:
?: (weblate.E005) Celery is configured in the eager mode
	HINT: https://docs.weblate.org/en/weblate-3.3/admin/install.html#celery

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

System check identified 4 issues (0 silenced).

**Comment by nijel** [comment]
Please upgrade to 3.4, it is fixed there

5. února 2019 21:36:44 SEČ, Andrew Mustun <notifications@github.com> napsal:
>**Describe the bug**
>Strings which use plural forms ("%n") in Qt translation sources (.ts)
>are shown correctly in the browser with multiple inputs for the
>translation. The also seem to be accepted and stored correctly.
>However, on commit, the translations do not make it back into the .ts
>file.
>
>Strings without plural forms are saved back fine.
>
>**To Reproduce**
>Create translation source (.ts) with plural form, e.g.:
>...
>    <message numerus="yes">
>        <location line="+42"/>
>        <source>%n house(s)</source>
>        <translation type="unfinished">
>            <numerusform></numerusform>
>            <numerusform></numerusform>
>        </translation>
>    </message>
>...
>Attempt to translate.
>
>**Expected behavior**
>The translations to end up back in the .ts file upon commit. Instead,
>the numerusform elements in the .ts files remain unchanged. The type
>attribute of the translation element remains "unfinished".
>
>**Screenshots**
>User interface (correct):
><img width="417" alt="schermafbeelding 2019-02-05 om 20 33 33"
>src="https://user-images.githubusercontent.com/1685085/52302548-757c9980-2985-11e9-9271-2943092a2568.png">
>
>Partial contents of file in the git repository
>(weblate/env/lib/python2.7/site-packages/data/vcs/...) on the server
>after saving and committing the translation:
><img width="545" alt="schermafbeelding 2019-02-05 om 20 34 07"
>src="https://user-images.githubusercontent.com/1685085/52302619-ae1c7300-2985-11e9-8a42-bf5d62fa1d07.png">
>
>**Server configuration and status**
>weblate list_versions
> * Weblate 3.3
> * Python 2.7.15rc1
> * Django 1.11.18
> * Celery 4.2.1
> * celery-batches 0.2
> * six 1.12.0
> * social-auth-core 3.0.0
> * social-auth-app-django 3.1.0
> * django-appconf 1.0.2
> * translate-toolkit 2.3.1
> * Whoosh 2.7.4
> * defusedxml 0.5.0
> * Git 2.17.1
> * Pillow 5.4.1
> * python-dateutil 2.7.5
> * lxml 4.3.0
> * django-crispy-forms 1.7.2
> * django_compressor 2.2
> * djangorestframework 3.9.0
> * user-agents 1.1.0
> * jellyfish 0.6.1
> * pytz 2018.9
> * pyuca 1.2
> * python-bidi 0.4.0
> * PyYAML 3.13
> * Database backends: django.db.backends.mysql
> * Cache backends: default:MemcachedCache, avatar:FileBasedCache
> * Celery: memory://, cache+memcached://127.0.0.1:11211/, eager
> * Platform: Linux 4.15.0-42-generic (x86_64)
>
>weblate check --deploy
>SystemCheckError: System check identified some issues:
>
>ERRORS:
>?: (weblate.E005) Celery is configured in the eager mode
>	HINT:
>https://docs.weblate.org/en/weblate-3.3/admin/install.html#celery
>
>WARNINGS:
>?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS
>setting. If your entire site is served only over SSL, you may want to
>consider setting a value and enabling HTTP Strict Transport Security.
>Be sure to read the documentation first; enabling HSTS carelessly can
>cause serious, irreversible problems.
>?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True.
>Unless your site should be available over both SSL and non-SSL
>connections, you may want to either set this setting True or configure
>a load balancer or reverse-proxy server to redirect all connections to
>HTTPS.
>?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a
>secure-only session cookie makes it more difficult for network traffic
>sniffers to hijack user sessions.
>
>System check identified 4 issues (0 silenced).

**Comment by qcad** [comment]
Excellent, thanks! I can confirm 3.4 fixes this problem.
