### ISSUE TITLE
After upgrade to Python 3: ASCII decoding issue

### ISSUE THREAD

**Issue by Flohack74** [WeblateOrg/weblate#2548]
**Describe the bug**
Weblate crashes with ascii decoding error on certain API URLs. 

**To Reproduce**
Unclear to me, seems to happen only with such URLs in API: /api/translations/ubports/ciborium/ja/file/

```
File "/opt/weblate3/local/lib/python3.5/site-packages/rest_framework/views.py" in handle_exception
  455.             self.raise_uncaught_exception(exc)

File "/opt/weblate3/local/lib/python3.5/site-packages/rest_framework/views.py" in dispatch
  492.             response = handler(request, *args, **kwargs)

File "/opt/weblate3/local/lib/python3.5/site-packages/weblate/api/views.py" in file
  437.             return download_translation_file(obj, fmt)

File "/opt/weblate3/local/lib/python3.5/site-packages/weblate/trans/views/helper.py" in download_translation_file
  143.             handle.read(),

File "/opt/weblate3/lib/python3.5/encodings/ascii.py" in decode
  26.         return codecs.ascii_decode(input, self.errors)[0]

Exception Type: UnicodeDecodeError at /api/translations/ubports/ciborium/ja/file/
Exception Value: 'ascii' codec can't decode byte 0xe3 in position 971: ordinal not in range(128)
Request information:
```

**Expected behavior**
No error should happen when calling those URLs. I did follow all steps for Python upgrade from 2 to 3, and now cannot locate the missing db or index I did not upgrade properly.

**Server configuration and status**
 * Weblate 3.1.1
 * Python 3.5.2
 * Django 2.1.5
 * six 1.12.0
 * social-auth-core 3.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow 5.4.1
 * python-dateutil 2.7.5
 * lxml 4.3.0
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.1
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * pytz 2018.9
 * pyuca 1.2
 * PyYAML 3.13
 * hub 2.2.9
 * Database backends: django.db.backends.mysql
 * Cache backends: default:MemcachedCache, avatar:FileBasedCache
 * Platform: Linux 4.4.0-142-generic (x86_64)

System check identified some issues:

WARNINGS:
?: (security.W021) You have not set the SECURE_HSTS_PRELOAD setting to True. Without this, your site cannot be submitted to the browser preload list.

System check identified 1 issue (0 silenced).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has been already fixed by b0639ba38f6db2bffc1ae2fa2748d411de4a2882 and the fix is part of the 3.3 release.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
