### ISSUE TITLE
CDATA tags in XLIFF are not correctly handled

### ISSUE THREAD

**Issue by sschueller** [WeblateOrg/weblate#2551]
**Describe the bug**
When editing a CDATA tag that already exists in an XLIFF file it will be "converted" when it it shown in the browser. It will then be saved in this converted state if changed. Creating a new CDATA entry also will result in the data also being encoded.

**To Reproduce**

XLIFF File:
```
<?xml version='1.0' encoding='UTF-8'?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file source-language="de-CH" target-language="de" datatype="plaintext" original="file.ext">
    <header>
      <tool tool-id="symfony" tool-name="Symfony"/>
    </header>
    <body>
      <trans-unit id="90872482424" resname="email.info">
        <source>email.info</source>
        <target><![CDATA[Sie sind mit der E-Mail '%email%' für den Dienst '%service%' angemeldet.<br><a style="text-decoration: underline;" href="%link%">Abmelden</a>]]></target>
      </trans-unit>
    </body>
  </file>
</xliff>
```

1. Import this into weblate and open the string to edit it
2. String will be converted to: ```Sie sind mit der E-Mail '%email%' für den Dienst '%service%' angemeldet.&lt;br&gt;&lt;a style="text-decoration: underline;" href="%link%"&gt;Abmelden&lt;/a&gt;```
3. If I add text, for example change `für den Dienst` to `für den test Dienst` the XLIFF will look like this:
```
<?xml version='1.0' encoding='UTF-8'?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file source-language="de-CH" target-language="de" datatype="plaintext" original="file.ext">
    <header>
      <tool tool-id="symfony" tool-name="Symfony"/>
    </header>
    <body>
      <trans-unit id="90872482424" resname="email.info">
        <source>email.info</source>
        <target>Sie sind mit der E-Mail '%email%' für den test Dienst '%service%' angemeldet.&lt;br&gt;&lt;a style="text-decoration: underline;" href="%link%"&gt;Abmelden&lt;/a&gt;</target>
      </trans-unit>
    </body>
  </file>
</xliff>
```

**Expected behavior**
CDATA correctly stored unencoded, maybe requires a raw button or something like that to enter the CDATA.

**Server configuration and status**
```
 * Weblate 3.4
 * Python 3.6.7
 * Django 2.1.7
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.1.0
 * python-dateutil 2.8.0
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.1
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2018.9
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.4.0
 * Mercurial 4.5.3
 * git-svn 2.17.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.9.125-linuxkit (x86_64)
```
<img width="634" alt="screenshot 2019-02-14 at 13 51 39" src="https://user-images.githubusercontent.com/1180107/52787927-b2205300-305f-11e9-85d1-72300cf3ddf9.png">

Maybe related to https://github.com/WeblateOrg/weblate/issues/737

**Comment by nijel** [comment]
The CDATA is indeed converted to raw XML. The file should still be equivalent in any XML compliant software. Do you have some problem with parsing such files?

**Comment by sschueller** [comment]
In my Symfony application it does not work. However I have setup a test using the latest Symfony version and it appears to work irregardless if the XLIFF is CDATA or raw XML.

Is CDATA support something to do with translation-toolkit anyway and not weblate?

Thanks for your time.

**Comment by nijel** [comment]
Support for saving as CDATA would need support on both sides - translate-toolkit to support generating such XML and Weblate to use such feature. Currently neither of these is there.

**Comment by sschueller** [comment]
I think I know whats going on now.

There is a bit of confusion among translators when working with html. I have determined the following:

- If a user puts html in the translation, it is validated and will through an error (Django XMLSyntaxError) upon commit if open tags are found. For example a `<br>`. This is difficult for a translator to locate and fix.
- If the html is valid the tags will be saved that way without being "encoded". So you end up with `<target>Sie <a style="back..` in the XLIFF. (not sure if that is correct). This will result in Symfony for example not correctly showing the html as a CDATA tag or conversion to RAW would be needed.
- If you edit existing CDATA it will be converted before it is shown to you. When you save that it is then correctly stored in "raw" xml.

So for it to work correctly the user must enter html encoded and not leave any tags open.
