### ISSUE TITLE
Add support for Bitbucket Server webhooks

### ISSUE THREAD

**Issue by apgrucza** [WeblateOrg/weblate#2553]
Weblate supports webhooks for Bitbucket, but not for Bitbucket Server (i.e. self-hosted Bitbucket). This is because the payloads for push events differ between the two:
* [Bitbucket - Push event payload](https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-Push)
* [Bitbucket Server - Push event payload](https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html#Eventpayload-Push)

For example, the Bitbucket Server push payload does not have a field called 'push'.

I'd like Weblate to be able to handle the Bitbucket Server payload. In the meantime I can use the `updategit` management command to update Weblate whenever my repository changes.

**Comment by nijel** [comment]
The problem I see is that it doesn't seem to include any information about the server name, so it's hard to match against the repository URL. Does the payload actually look like described in the docs, or does it include some additional fields which could help with this? Both self-hosted GitLab and GitHub include actual repository URL in this case...

**Comment by apgrucza** [comment]
The actual payload does indeed include some additional fields that identify the server name and repository. Here's an anonymized example:

```json
{
    "eventKey": "repo:refs_changed",
    "date": "2019-02-20T03:28:49+0000",
    "actor": {
        "name": "joe.blogs",
        "emailAddress": "joe.bloggs@example.com",
        "id": 160,
        "displayName": "Joe Bloggs",
        "active": true,
        "slug": "joe.blogs",
        "type": "NORMAL",
        "links": {
            "self": [
                {
                    "href": "https://bitbucket.example.com/users/joe.blogs"
                }
            ]
        }
    },
    "repository": {
        "slug": "my-repo",
        "id": 3944,
        "name": "my-repo",
        "scmId": "git",
        "state": "AVAILABLE",
        "statusMessage": "Available",
        "forkable": true,
        "project": {
            "key": "SANDPIT",
            "id": 205,
            "name": "Sandpit",
            "description": "sandpit project",
            "public": false,
            "type": "NORMAL",
            "links": {
                "self": [
                    {
                        "href": "https://bitbucket.example.com/projects/SANDPIT"
                    }
                ]
            }
        },
        "public": false,
        "links": {
            "clone": [
                {
                    "href": "https://bitbucket.example.com/scm/sandpit/my-repo.git",
                    "name": "http"
                },
                {
                    "href": "ssh://git@bitbucket.example.com:7999/sandpit/my-repo.git",
                    "name": "ssh"
                }
            ],
            "self": [
                {
                    "href": "https://bitbucket.example.com/projects/SANDPIT/repos/my-repo/browse"
                }
            ]
        }
    },
    "changes": [
        {
            "ref": {
                "id": "refs/heads/master",
                "displayId": "master",
                "type": "BRANCH"
            },
            "refId": "refs/heads/master",
            "fromHash": "fdff3f418a8e3d25d6c8cb80776d6ac142bef800",
            "toHash": "7cb42185f7d8eab95f5fac3de2648a16361ecf34",
            "type": "UPDATE"
        }
    ]
}
```

So the data to match against is in the `repository` -> `links` -> `clone` field.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by apgrucza** [comment]
Thanks for fixing so quickly - I have been trying to test it. I expected the docker image with tag 'edge' to include the fix but it does not seem to. The 'About' page still says 3.4 and the /usr/local/lib/python3.6/dist-packages/weblate/trans/views directory inside the container doesn't contain the new hooks.py file. Is there an issue with how the 'edge' image is being built?

**Comment by nijel** [comment]
No, the edge is expected to be on stable Weblate, just edge docker changes (this is also written on https://hub.docker.com/r/weblate/weblate).
