### ISSUE TITLE
Enabling an addon project wide / system wide

### ISSUE THREAD

**Issue by sr258** [WeblateOrg/weblate#2555]
Is it possible to enable addons project wide (or globally for the whole system)? I'm going to import lots of components for a project and want to use "Customize JSON output" for each of them (with JSON indentation set to 2). It would also be fine if I could enable the add-on from the API or some other automatic means.

**Comment by nijel** [comment]
You can install addon to all components using [install_addon](https://docs.weblate.org/en/latest/admin/management.html#install-addon) management command.

**Comment by sr258** [comment]
Fantastic! It's really great how flexible Weblate is!
