### ISSUE TITLE
Having several languages codes as base languages in single project

### ISSUE THREAD

**Issue by sr258** [WeblateOrg/weblate#2556]
The components I want to translate sometimes have base language files for ".en" and sometimes for "en" only. Is there a way of getting them to work in a single project? (I know that I could simply copy from "en" to ".en", but I'm not the maintainer of the component's repositories.)

**Comment by nijel** [comment]
Maybe I'm missing something, but it's just how you define the filemask?

**Comment by sr258** [comment]
I need the "monolingual base language file", as the project uses nested JSON as a file format. In the example below the project source language is set to "English" and I try to add an ".en.json" file as base language file for a specific component:

![bildschirmfoto von 2019-02-17 11-11-45](https://user-images.githubusercontent.com/15268740/52911508-f486a180-32a4-11e9-92c2-a0a895e2c38c.png)

As you can see, Weblate complains about the mismatch between project source language and language the base language file.

**Comment by nijel** [comment]
Do all locales start with .? Or is just English for some reason special that it includes an extra .?

**Comment by sr258** [comment]
No, it's only this one. All others just have the normal language code. The ".en" files are the auto-generated files from the source. You can set the "source language" setting of the project to ".en (generated)" and then it will accept ".en.json" files, but not "en.json" any more. As Weblate offers ".en (generated)" as an option I assumed that this is some kind of standard.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
