### ISSUE TITLE
make user's subscription list api 

### ISSUE THREAD

**Issue by choiks14** [WeblateOrg/weblate#2557]
**Is your feature request related to a problem? Please describe.**
I make a third party app. I can not found api that has not  users' subscription list.
please make user's subscription list.

**Comment by nijel** [comment]
There is plan to rewrite the notification system (see https://github.com/WeblateOrg/weblate/issues/2542), so the API for that should be done after those changes.

**Comment by choiks14** [comment]
👍

**Comment by nijel** [comment]
Please leave that open, that issue doesn't mention api.

**Comment by nijel** [comment]
How it could look like:

* GET /api/users/nijel/notifications/ - list user subscribed events
* PUT /api/users/nijel/notifications/ - create new subscription
* GET /api/users/nijel/notifications/123/ - get individual subscription
* POST/PATCH /api/users/nijel/notifications/123/ - modify
* DELETE /api/users/nijel/notifications/123/ - remove subscription

@choiks14 can you please check that it matches your needs?
