### ISSUE TITLE
Probably wrong locale name for gettext for Chinese Traditional

### ISSUE THREAD

**Issue by onkarshinde** [WeblateOrg/weblate#2559]
**Describe the bug**
I have a project on hosted weblate
https://hosted.weblate.org/projects/gnusim8085/
One of the translators created a Chinese (Traditional) translation recently. This has created a zh_Hant.po file in my source repository. I wanted to test this new translation. So I installed Chinese (Traditional) language package on my Ubuntu desktop. The language selection I get is Chinese (Taiwan) and Chinese (Hong Kong) with codes zh_TW and zh_HK respectively. Doesn't matter which one I choose this new translation does not get loaded.
It looks like zh_Hant may be a language code used in other systems but not on GNU/Linux systems that use glibc/gettext for locale/i18n.

**To Reproduce**
1. Go to any hosted project which is using gettext as translation mechanism
2. Add new language and select Chinese (Traditional)
3. Translate at least one string and save.
4. Check which po file is created.

**Expected behavior**
A file names zh_TW.po should be created (preferably).

**Comment by nijel** [comment]
The "correct" code in this case depends how you use gettext and where. The zh_Hant is modern and preferred variant, see eg. https://www.w3.org/International/articles/bcp47/, but probably doesn't work well on Linux / glibc environments (I haven't tested this).

You can rename the file to legacy name (zh_TW) and Weblate will recognize it just fine.

**Comment by onkarshinde** [comment]
Based on the information in that link shouldn't the file be called zh-Hant.po rather than zh_Hant.po?

**Comment by nijel** [comment]
It really depends whether you prefer Gettext or BCP syntax. Weblate will parse both, but for creation it currently has defaults per file format, so Gettext prefers Gettext syntax. Also see https://github.com/WeblateOrg/weblate/issues/2509
