### ISSUE TITLE
gitlab webhook not matching a component in case of HTTP URI with user+token

### ISSUE THREAD

**Issue by ReneBoehm** [WeblateOrg/weblate#2560]
**Describe the bug**
I'm not exactly sure if this is really a bug or something in the "grey zone" ;)
We have a gitlab running on HTTP and our repos are restricted to private access. Therefore someone will need a user + token in the URI to access the repos via HTTP. When we configure a push webhook in gitlab, Weblast doesn't find any matching component, because the code in api.py only ignores the relevant user+token information in the URI in case of HTTPS but not HTTP.

**To Reproduce**
1. Configure a project + component with HTTP gitlab URL including user + token.
2. Configure a push webhook in gitlab to inform Weblast about a change.
3. Look at the Weblast log
4. See the message ```...0 matching components, 0 to process```

**Expected behavior**
The correct project and component will be matched.

**Screenshots**
if needed

**Server configuration and status**
I'm using the current docker image.

``` * Weblate 3.4
 * Python 3.6.7
 * Django 2.1.7
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.1.0
 * python-dateutil 2.8.0
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.1
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2018.9
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.4.0
 * Mercurial 4.5.3
 * git-svn 2.17.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 3.16.0-4-amd64 (x86_64)
```

**Additional context**
To verify this I've patched the file api.py to replace the HTTPS restriction with HTTP and it works as expected. Since I'm not familiar with Python, I'm not able to produce a final solution at the moment ;)
```
    # We need to match also URLs which include username and password
    for repo in repos:
        if not repo.startswith('http://'):
            continue
        spfilter = spfilter | (
            Q(repo__startswith='http://') &
            Q(repo__endswith='@{0}'.format(repo[8:]))
```

**Comment by nijel** [comment]
And do you know that using http is insecure? :-)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by ReneBoehm** [comment]
> And do you know that using http is insecure? :-)

I know that but it's all company internal no public access. Additionally the functional user has only read access to the git repo.

**Comment by ReneBoehm** [comment]
BTW...how can I convince Weblate that my self signed SSL certificate is fine and can be accepted ? Is there a way to do this ?

**Comment by nijel** [comment]
You need to install it into the system, you can find several howtos for that, eg. https://unix.stackexchange.com/q/90450/47231
