### ISSUE TITLE
possible ways to support developer comments for Android strings.xml

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#2562]
XLIFF and po both have the very nice feature of being able to include comments to the translators right in the source file.  Android's _strings.xml_ does not have this explicitly.  Transifex had a nice idea for how to support this: an XML comment before a string is included as the developer comment:
 https://docs.transifex.com/formats/android-xml Unfortunately, Transifex seems to be the only one supporting that.  Most services don't seem to support a developer comment for Android _strings.xml_ at all. 
* Crowdin uses `<string comment="">` which seems more likely to conflict with tools. https://support.crowdin.com/file-formats/android-xml/
*  Lokalise seems to do this with an attached JSON file: https://docs.lokalise.co/supported-file-formats/android-resources-xml
*  OneSky claims to support "notes to translators" but I can't find any example or documentation

**Comment by nijel** [comment]
Looking at the code, the XML comments should be already parsed by translate-toolkit and thus by Weblate. Have you tested it?

**Comment by nijel** [comment]
I've just verified it works and clarified docs on this.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by eighthave** [comment]
I added a bunch of comments to F-Droid's _string.xml_, but they don't seem to have been picked up by Weblate's web UI yet.

https://gitlab.com/fdroid/fdroidclient/blob/07971080c4bf6aaf0fe7a31d0f84f5153f2c4b30/app/src/main/res/values/strings.xml
```xml
    <!-- as in software updates -->
    <string name="updates">Updates</string>
    <!-- as in software updates -->
    <string name="unstable_updates">Unstable updates</string>
    <!-- as in software updates -->
    <string name="unstable_updates_summary">Suggest updates to unstable versions</string>
```
* https://hosted.weblate.org/translate/f-droid/f-droid/cs/?checksum=1c9cea4df7819f
* https://hosted.weblate.org/translate/f-droid/f-droid/cs/?checksum=f63a574238a0f60e
* https://hosted.weblate.org/translate/f-droid/f-droid/cs/?checksum=722b4f877d7a8f9d

**Comment by nijel** [comment]
It turns out there was a bit mess in the repository due to bug in squash addon together with multi file storage for metadata. I've manually fixed the repo now, updated it and the comments are now there.

**Comment by eighthave** [comment]
Now they are there! :+1:
