### ISSUE TITLE
GDPR compliance - download personal data

### ISSUE THREAD

**Issue by sr258** [WeblateOrg/weblate#2564]
To comply with the GDPR websites have to list what personal data they store, for how long, who can see this and for what purpose. I've seen the documents at https://github.com/WeblateOrg/hosted/tree/master/wlhosted/legal/templates/legal/documents and I think this is a good starting point for my own documentation. Does Weblate offer any functionality with which Chapter 3 of GDPR (Rights of the data subject) can realized? I'm particularly thinking of Article 15 (Right of access by the data subject) and 20 (Right to data portability).

**Comment by nijel** [comment]
There is currently no in app support for data download. In the long term I certainly want to have this built in, but implementing it is not really a priority for now. Given that there is very little personal information we collect, the portability is achieved pretty much by just creating user account elsewhere.

As for the policy, feel free to base on the documents we use on [Hosted Weblate](https://hosted.weblate.org/legal/privacy/) (which source you've already found).

**Comment by nijel** [comment]
PR for user data download is here: https://github.com/WeblateOrg/weblate/pull/2609

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
