### ISSUE TITLE
Markdown links fail checks when the translatable field is changed

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2573]
https://hosted.weblate.org/checks/md-link/

https://hosted.weblate.org/translate/f-droid/website-posts/de/?checksum=5ed8a2a1ff22025c
Source:
[translate]({{ site.baseurl }}/docs/Translation_and_Localization/)
Translation (German):
[übersetzen]({{ site.baseurl }}/docs/Translation_and_Localization/)

Related to #2495

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
