### ISSUE TITLE
Every source strings appears to have a whitespace following it in the Zen and regular editor.

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2574]
Get an e-mail about a new translation.

It says:

--"Kildestreng: | Connect… "
"Oversettelse: Koble til… "
-----"Bruker:"

![skjermbilde pa 2019-02-24 01-02-11](https://user-images.githubusercontent.com/13802408/53293228-2da4a180-37d0-11e9-80e8-69d3bd7e5735.png)

There is a whitespace following the string, which seems as if there is an error,
and if you click to edit the string (in the translation language branch) it is still there.

![skjermbilde pa 2019-02-24 01-03-07](https://user-images.githubusercontent.com/13802408/53293233-3a28fa00-37d0-11e9-9e15-ec0a189e1a69.png)

https://hosted.weblate.org/translate/freeyourgadget/gadgetbridge/nb_NO/?checksum=e281142a1a75f910

But when clicking to edit source, it is gone.
https://hosted.weblate.org/translate/freeyourgadget/gadgetbridge/en/?checksum=e281142a1a75f910

Having to click this many times to review something when it could be visually presented with ""s right away is time wasted.
Also the fields in the e-mail are not aligned, (could be Thunderbird error) and the pipe sign is present when copying it, which is strange.

The User is missing, which in this case is https://hosted.weblate.org/user/HenRy/ who has 0 submissions… Maybe did it with the stats script turned off, and it will correct itself later on?

I would want it to be:

"New source string: Connect…" Click to edit source string
"New translation: Koble til…" Click to edit translation
"New translator: HenRy" Click to get to user account

**Comment by nijel** [comment]
Any extra whitespace is highlighted by Weblate, so if it's not there. The whitespace in HTML is not really good indicator of anything.

The user has 0 suggestions, but 336 translations, where do you exactly see a problem?

PS: It would be great to open one issue pert topic and not mixing up different topics in one...

**Comment by comradekingu** [comment]
I must have missed that, but the username is not in the original e-mail for the notification.
The whitespace is a false positive, even if there is a true positive that is more visible.
Same for every source string. There is a whitespace following the source string in the Zen editor, and in the default one.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
