### ISSUE TITLE
Mentions in comments

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2580]
**Is your feature request related to a problem? Please describe.**
Add option to notify particular user about a comment. This might be related to the translation (what https://github.com/WeblateOrg/weblate/issues/2579 is trying to address), but it might be different concern as well (eg. notifying somebody to review or to fix the source string).

**Describe the solution you'd like**
* Whenever `@username` is used in the comment user is notified.
* This can be configured in the user settings.

**Comment by comradekingu** [comment]
Username is different from handle, so if all handles are unique, it could do both?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
