### ISSUE TITLE
Add support for subtitle formats [$25]

### ISSUE THREAD

**Issue by gorgobacka** [WeblateOrg/weblate#2582]
**Is your feature request related to a problem? Please describe.**
I would like to use weblate for translating subtitles. But currently those format is not natively supported in Weblate.

**Describe the solution you'd like**
Several formats are already supported by tranlate-toolkit (see: https://github.com/translate/translate/blob/master/translate/storage/subtitles.py)
I read in other issues that it's "easy" to add formats, if they are already available in ttkit. I hope it's also the case for those.
My main interest are srt-files. However, sub-, ass- and ssa-files would be nice to have.

**Comment by nijel** [comment]
It's really easy when translate-toolkit implementation follows some standards, what unfortunately is not always the case.

In that case you just need small glue class:

https://github.com/WeblateOrg/weblate/blob/e56d524c02c6291dcca028711c34ff114e02814c/weblate/formats/ttkit.py#L1074-L1090

**Comment by gorgobacka** [comment]
Thanks for your fast answer.

I will set up an development environment and try it out in the coming days.

**Comment by gorgobacka** [comment]
I'm a bit puzzled.

I added the following to ttkit.py:

`class SubRipFormat(TTKitFormat): 
    name = _('SubRip file') 
    format_id = 'srt' 
    loader = ('subtitles', 'SubRipFile') 
    unit_class = MonolingualSimpleUnit 
    autoload = ('.srt',) 
    new_translation = '{}\n' 
  
    @property 
    def mimetype(self): 
        """Return most common mime type for format.""" 
        return 'text/plain' `

But while creating the component in Weblate, it tells me that the mask *.srt does not match any file type.

Do I need to activate it somewhere? Or is the code wrong?

**Comment by nijel** [comment]
You also need to add the class name to the `WEBLATE_FORMATS` setting, the default value is kept here:

https://github.com/WeblateOrg/weblate/blob/d617fbc16ad287b0a48c91201d40ce96d054d8fb/weblate/formats/models.py#L67-L97

**Comment by gorgobacka** [comment]
Thanks a lot that was very helpful.

But now I get an error when I "Start a new translation". It shows a FormatError. And when I look at the newly created (empty) file, it contains only `{}`. This is not an subtitle format and I except therefore the error shows up. It seems that I miss the creation of the new file.

Do I need an additional method to do this in the SubRipFormat class?

**Comment by nijel** [comment]
This is what you've put into `new_translation` attribute :-). If you keep that as `None`, it will allow creating new translations only based on base file. Also see https://docs.weblate.org/en/latest/formats.html#adding-new-translations

**Comment by gorgobacka** [comment]
Thanks. But something still seems not right.

This is my subtitle file:
`
1
00:00:01,000 --> 00:00:04,000
Hello

2
00:00:06,000 --> 00:00:08,000
I am a subtitle file.

3
00:00:12,000 --> 00:00:16,000
Please translate me.
`

But, the source strings are still empty in weblate. See:
![weblate_translate](https://user-images.githubusercontent.com/10488441/54061881-300cef80-4203-11e9-8871-dc36b3596270.png)

Here are my settings:
![weblate_settings](https://user-images.githubusercontent.com/10488441/54061877-2d11ff00-4203-11e9-9b4c-d83ac640d2d6.png)

Do I need to add a `def source(self)` method to the my new class?

Sorry, that I have so many questions.

**Comment by nijel** [comment]
Yes, you will probably need something like:

```python
    @cached_property
    def source(self):
        if self.template is not None:
            return self.template.source
        return self.unit.getid()
```

**Comment by gorgobacka** [comment]
Currently, I don't have time to solve this by myself. Therefore, I posted a bounty for it. Hopefully, it motivates someone to work on it.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by gorgobacka** [comment]
Thanks a lot. I will test it.

**Comment by nijel** [comment]
Thanks, real life testing is always welcome.

**Comment by gorgobacka** [comment]
Tested it today and it works. Thanks a lot!
