### ISSUE TITLE
'component' with Excel Format. will returns 500 error

### ISSUE THREAD

**Issue by berubou** [WeblateOrg/weblate#2584]
**Describe the bug**
Created a 'component' with Excel Format.
when i create new language or push commits, it will returns ' Internal Server Error'

**To Reproduce**

- how the 'compoent' configuration
![image](https://user-images.githubusercontent.com/14237234/53471987-75ae1780-3aa1-11e9-92ec-0937ac4da653.png)

- 'start new translation' returns 500
    1. ![image](https://user-images.githubusercontent.com/14237234/53472167-e6553400-3aa1-11e9-8f75-40a755994126.png)
    2. ![image](https://user-images.githubusercontent.com/14237234/53472181-ed7c4200-3aa1-11e9-8208-d3c286cfc360.png)

- when i want commit something, it also returns 500. and at 'repository maintenance' page, it says `There are some new commits in the local repository`.
   1. ![image](https://user-images.githubusercontent.com/14237234/53472318-4b108e80-3aa2-11e9-900f-7290c1072c39.png)
   2.![image](https://user-images.githubusercontent.com/14237234/53472370-624f7c00-3aa2-11e9-92f8-12a44a16dc7a.png)

**Server configuration and status**
```
* Weblate 3.4
* Python 3.7.2
* Django 2.1.5
* Celery 4.2.1
* celery-batches 0.2
* six 1.12.0
* social-auth-core 3.0.0
* social-auth-app-django 3.1.0
* django-appconf 1.0.2
* translate-toolkit 2.3.1
* translation-finder 1.0
* Whoosh 2.7.4
* defusedxml 0.5.0
* Git 2.19.1
* Pillow 5.4.1
* python-dateutil 2.7.5
* lxml 4.3.0
* django-crispy-forms 1.7.2
* django_compressor 2.2
* djangorestframework 3.9.1
* user-agents 1.1.0
* jellyfish 0.7.1
* diff-match-patch 20121119
* pytz 2018.9
* pyuca 1.2
* python-bidi 0.4.0
* PyYAML 3.13
* Database backends: django.db.backends.mysql
* Cache backends: default:LocMemCache
* Celery: memory://, N/A, eager
* Platform: Linux 4.13.0-36-generic (x86_64)
```

```
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Can not send email ([Errno 111] Connection refused), please check EMAIL_* settings.
	HINT: https://docs.weblate.org/en/weblate-3.4/admin/install.html#out-mail
?: (weblate.E007) The configured cache backend will lead to serious performance or consistency issues.
	HINT: https://docs.weblate.org/en/weblate-3.4/admin/install.html#production-cache
?: (weblate.E014) The cookie secret key has default value
	HINT: https://docs.weblate.org/en/weblate-3.4/admin/install.html#production-secret
?: (weblate.E017) Configure correct site domain
	HINT: https://docs.weblate.org/en/weblate-3.4/admin/install.html#production-site

ERRORS:
?: (weblate.E005) Celery is configured in the eager mode
	HINT: https://docs.weblate.org/en/weblate-3.4/admin/install.html#celery
?: (weblate.E008) Please configure separate avatar caching to reduce pressure on the default cache
	HINT: https://docs.weblate.org/en/weblate-3.4/admin/install.html#production-cache-avatar

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.4/admin/install.html#collecting-errors

System check identified 10 issues (0 silenced).
```

**Additional context**

**Comment by nijel** [comment]
Can you please post the traceback you get in this case? Either configure ADMINS and you should get it by email or enable DEBUG mode to see it in the browser.

**Comment by Pinkuburu** [comment]
sorry，traceback is here http://dpaste.com/0GGKW8D

**Comment by nijel** [comment]
I can see two problems there:

- wrong URL for the repository `git@github.com/Pinkuburu/GF_i18n.git`, probably should be `git@github.com:Pinkuburu/GF_i18n.git`
- you don't have correctly configured sending emails

**Comment by Pinkuburu** [comment]
Oops, I made a mistake. Sorry to bother you.
I have fixed this now，and I will continue testing.

**Comment by Pinkuburu** [comment]
The feauture “Start new translation” can create new language now，but no strings or words inside.

Source strings have 30 strings inside:
![image](https://user-images.githubusercontent.com/4962790/53486192-0e08c400-3ac3-11e9-8fcb-c028ae6a193b.png)

But no strings in other translation:
![image](https://user-images.githubusercontent.com/4962790/53486251-31337380-3ac3-11e9-8202-2d90247d97f7.png)

My excel files:
![image](https://user-images.githubusercontent.com/4962790/53486320-5b853100-3ac3-11e9-911f-45fd32d31a47.png)

**Comment by nijel** [comment]
Is the xlsx file actually created? I'm affraid this is not really implemented for this format right now...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by Pinkuburu** [comment]
> Is the xlsx file actually created? I'm affraid this is not really implemented for this format right now...

the xlsx file actually created,it can open with notepad,content it seems like csv file,just filename extension is ".xlsx"

**Comment by nijel** [comment]
That's what I've figured out. The fix is already in git and will be part of upcoming release.

**Comment by Pinkuburu** [comment]
> That's what I've figured out. The fix is already in git and will be part of upcoming release.

thank you,but also find a new bug.I have not changed any settings except to change the mailbox settings.
When you create an excel component, modify any settings of the component again, you will get this error messsage.
![image](https://user-images.githubusercontent.com/4962790/53541135-67203880-3b53-11e9-8210-be7f1992e7cd.png)

**Comment by nijel** [comment]
That's probably because of the csv files? Can you try removing them?

**Comment by Pinkuburu** [comment]
> That's probably because of the csv files? Can you try removing them?

Yes,I also think because the csv files,because csv no more attribute,just a text files.
I can remove them
