### ISSUE TITLE
User is rate limited when translating

### ISSUE THREAD

**Issue by ionmincu** [WeblateOrg/weblate#2585]
**Describe the bug**
Clicking save too many times on when translating results in user beeing signed out with the following message.

![image](https://user-images.githubusercontent.com/44569445/53552379-e148c100-3b43-11e9-8bf2-2812d33b0905.png)

**To Reproduce**
1. Go to a component
2. Start translating strings
3. Translate a string and click save, repeat

The user is signed out.
From my knowledge the user should not be rate limited doing his work, the only rate limits (according to documentation) are:
```
Registration (REGISTRATION scope)
Sending message to admins (MESSAGE scope)
Password authentication on login (LOGIN scope)
Sitewide search (SEARCH scope)
```

**Expected behavior**
The user should not be rate limited when translating

**Server configuration and status**
```
 * Weblate 3.4
 * Python 3.6.7
 * Django 2.1.5
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.1.0
 * python-dateutil 2.7.5
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.1
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2018.9
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.4.0
 * Mercurial 4.5.3
 * git-svn 2.17.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
```
**Additional context**

**Comment by nijel** [comment]
There always was rate limiting for translating as well, it was just missing from the docs, it's already fixed for upcoming release: https://docs.weblate.org/en/latest/admin/optionals.html#rate-limit The default limits were also increased for next release.

The rate limiting unfortunately has to be there it avoid malicious users messing up too much.

**Comment by ionmincu** [comment]
@nijel thanks, just one more question was 20 attempts default in 3.4, or thats after they were increased?
