### ISSUE TITLE
source string comment does not update until hard refresh

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#2591]
**Describe the bug**

I updated the source string comment in XLIFF files last night.  A translator asked a question that was directly addressed by the new source string comment.  I went to check it in weblate, and saw the old source string comment.  I checked in a few different languages and strings and saw only the old source string comment.  After a little while, I came back to weblate, and it seems that the source string comment had updated.  I'm guessing this is due to the browser caching the old one.  I think when I came back I did a search to find a specific string and then it was updated.  Before I was just browsing through the strings.

Here's the translator's comment:
https://forum.f-droid.org/t/translating-lots-of-app-summaries/1319/19

**Expected behavior**

Pushing updates to the source string should change it in the weblate UI as soon as possible.

**Server configuration and status**

https://hosted.weblate.org/projects/f-droid/fdroiddata/

**Comment by nijel** [comment]
There is no caching of comments, especially not in the browser. Looking at the logs the repository was updated on 23:46:16  and 23:51:48 the updates were fully processed, maybe you looked before the update was completed?

**Comment by eighthave** [comment]
those times match when I pushed the updates to the XLIFF files, but I
saw the old comments today, shortly before I posted this issue.

**Comment by nijel** [comment]
I don't see anything wrong in the project now. The comments seem to match what is in the files. There are still quite some strings where the old comment is stored in the xliff file:

```xml
      <trans-unit id="org.fdroid.fdroid.privileged-summary" maxwidth="80" size-unit="char">
        <note from="developer">This is limited by Google to 80 characters</note>
        <source>Services to allow F-Droid to securely install and update apps</source>
      </trans-unit>
```

**Comment by eighthave** [comment]
Ah, thanks, maybe I was just confused by this, but I'm pretty sure I was checking the same strings and they changed.  I updated all those, my conversion script had a bug.

/close
