### ISSUE TITLE
Android Metadata translations limited to 500 charaters

### ISSUE THREAD

**Issue by ar-** [WeblateOrg/weblate#2594]
**Describe the bug**
I've received a report that metadata for android apps (a beta feature) can't be translated since it is limited to 500 characters. https://gitlab.com/ar-/apple-flinger/issues/78

> In Weblate, the source string changelogs/1005004.txt:1 (for the game's metadata) is written with more than 500 characters, but only 500 characters are available for the translation.
Some other strings need more than what is offered to be properly translated, like changelogs/1005004.txt:1 (still in metadata).
Is it possible to fix that?

**To Reproduce**
1. Go to the metadata translation of 'Apple Flinger'.
2. Translate changelogs/1005004.txt:1
3. See that you can enter only 500 characters

**Expected behavior**
The amount of characters that can be used for the translation should be at least the amount of characters in the source string and not be limited to 500.

**Server configuration and status**
Uses the hosted version of weblate

**Comment by nijel** [comment]
The limit was done based on specification in https://github.com/WeblateOrg/weblate/issues/1525 from F-Droid developers - reportedly the limit for changelog entries is 500 chars. If you have better source for what the limit should be (or if there is none), please share that.

CC @eighthave

**Comment by ar-** [comment]
I wasn't aware of this specification. I know that changelogs are sometimes being chopped off and that might be because of this limit.

Apart from that, such a rule still doesn't make much sense. Even if the original text is 499 characters long, the translation can still be 501 characters long. So this rule naturally enforces wrong translations.

**Comment by nijel** [comment]
From what I understood, they are chopped in the appstore at 500 chars. IMHO it makes no sense to produce longer strings, they would be chopped later. So it's better to let the translator know there is the limit. The actual problem is that the original text is already using all that limit and it makes it challenging to fit the translation into same space...

Anyway I have no knowledge of the limits besides what was written in #1525, if anybody can dig up specification for these, it would be great. But it seems that people agree on this limit in various posts, see https://stackoverflow.com/a/20276565/225718 or https://dgtlmart.com/google-changed-character-limit-for-app-title-in-google-play-store/

**Comment by ar-** [comment]
Yes fair enough. I also don't have a good solution for that, so maybe keep it as it is.

Could a setting be implemented that allows me to turn off the translation for changelogs and have only the app description and the summary translated?

Background: I usually do a release when I have enough features to release. or for continuous deployments I have one release per feature. So I write up the changelogs in the last second and then release it (and the changelog are part of the release). In the past I used my own script to translate these changelogs, since I need them translated right away. For my projects the changelog translation is not useful. So in addition to the problem of the 500 char limit, I would like to prevent the volunteers going through all old changelogs and translate them, since no one will ever see them.

**Comment by eighthave** [comment]
Enforcing strict 500 char limits on changelog entries is 100% correct. That's what Google Play, F-Droid, and other app stores enforce.

* F-Droid, Google Play, Amazon, and iTunes all have 4000 char descriptions
* F-Droid and Google Play allow a 80 char "Short Description"      https://support.google.com/googleplay/android-developer/answer/113469?hl=en
* Amazon allows a 1200 char "Short Description"       https://developer.amazon.com/public/support/submitting-your-app/tech-docs/submitting-your-app#Add Metadata and Image Assets

**Comment by eighthave** [comment]
I think this issue should just be closed.  Here's more discussion from fdroid: https://gitlab.com/fdroid/fdroidserver/merge_requests/55

**Comment by eighthave** [comment]
Here are other character limits for the record:
* Name=30
* Video=256
* WhatsNew=500
  
https://support.google.com/googleplay/android-developer/answer/113469?hl=en
https://stackoverflow.com/a/20276565
