### ISSUE TITLE
Same strings check does not work good

### ISSUE THREAD

**Issue by glixx** [WeblateOrg/weblate#2597]
If original string is same with translated string, then checking works not always.

**Comment by nijel** [comment]
There is blacklist to allow some words to be same: https://github.com/WeblateOrg/weblate/blob/master/weblate/checks/data.py

**Comment by glixx** [comment]
If you use blacklist, then needs to have option to disable blacklist.
But I see some strings, that are not in blacklist, but checking does not see them.

**Comment by nijel** [comment]
Can you please give some specific example? The blacklist is there to avoid producing too many false positives for strings which are same in several languages.

**Comment by glixx** [comment]
Blacklist for all languages is not good. It's better to have button for translator to blacklist what he needs. And to have global blacklist, but for each language.

**Comment by nijel** [comment]
Patches are always welcome ;-). Still, can you please describe actual problem you are facing?

**Comment by glixx** [comment]
At least you must do not use your blacklist for Japanese, Chinese, Russian, Ukrainian, Serbian Cyrillic, .etc, for languages that does not use English alphabet.

**Comment by nijel** [comment]
Based on my experience this is not really true, look at this Chinese string:

https://github.com/WeblateOrg/weblate/blob/dd92092f2f27946902462577092327e31cb1577d/weblate/locale/zh_Hant/LC_MESSAGES/django.po#L188-L190

The very same situation is in Russian:

https://github.com/WeblateOrg/weblate/blob/dd92092f2f27946902462577092327e31cb1577d/weblate/locale/ru/LC_MESSAGES/django.po#L199-L201

Or Arabic:

https://github.com/WeblateOrg/weblate/blob/dd92092f2f27946902462577092327e31cb1577d/weblate/locale/ar/LC_MESSAGES/django.po#L197-L201

So in all these cases it apparently makes sense to ignore some words.

The current implementation is not perfect, but it's been tuned to avoid producing too much of false positives. Having the black list per language would be indeed better, but somebody has to produce that.

Still you haven't described the actual problem you're facing...
