### ISSUE TITLE
Can we use same URL (weblate url) for repository push url?

### ISSUE THREAD

**Issue by ieugen** [WeblateOrg/weblate#2598]
Hello,

Can we use the weblate style url for repository push url so that git push will work?
The idea is to maintain the git url only on one component and reference it in all the rest. It makes moving the translations easier to another git repo.

We have multiple components. They share the same git repository. We use the weblate style url for the `source repository` field: 

Source code repository:  
weblate://project/my-component

My question is related to the `Repository push URL` . Can we use the same type of url so weblate will use the push url from the referenced component?

What if we don't put anything there but have the weblate url + push on commit. Should weblate just use the parent component push url?

Thanks,

**Comment by ieugen** [comment]
I tried to set a push url with a linked repository and I get this error message:
```
Push URL is not used when repository is linked!
URL of a push repository, pushing is disabled if empty.
```

This means that there is probably a bug here.

**Comment by nijel** [comment]
The push url is used only on the target component, so if you define repo URL as  `weblate://project/my-component` it will use push URL configured on project/my-component.
