### ISSUE TITLE
[XLIFF] Translations aren't being saved as Target in bilingual files

### ISSUE THREAD

**Issue by XVII** [WeblateOrg/weblate#2600]
**Describe the bug**
I've noticed my Target translation files (bilinguals) are only getting their Source updated -- not the Target.

Maybe this is a regression introduced from #2521?

I need to test in 3.5 without patches.

**To Reproduce**
1. Using https://github.com/WeblateOrg/weblate/files/2853605/TranslationTest.zip
2. Translate en-NZ "Color" to "Colour"
3. Commit

**Expected behavior**
The en-NZ bilingual file should have the `<Source>Color</Source>` and `<Target>Colour</Target>` but instead my `<Source>` gets updated to "Colour".

**Comment by nijel** [comment]
Before b21089b0310960834e7ba389193dbbef63edb075 only target was updated, after it only source is updated. That was what you've described in #2521 -  "should only update Source".

**Comment by ShadowXVII** [comment]
Yes, but only in the monolingual file (i.e. en-US to en-US) not the bilingual one (en-US to nl-NL). 

The above is a bilingual example.

**Comment by nijel** [comment]
The source is updated only on monolingual translations (when monolingual template is set)...

**Comment by ShadowXVII** [comment]
If that's the case then it shouldn't be affecting my bilingual files. Would a screen share or similar be useful here?

**Comment by nijel** [comment]
Is your translation configured as bilingual? Looking at the zip, I saw the .mono file and assumed you're using the monolingual setup...

**Comment by ShadowXVII** [comment]
### Monolingual
`Translation Test.mono.xlf` is the monolingual base/source file (en-US). 
It shouldn't have `<Target>`, just `<Source>`.

### Bilingual
`Translation Test.en-NZ.xlf` is the bilingual translation file (en-US to en-NZ).
`Translation Test.en-AU.xlf` is the bilingual translation file (en-US to en-AU).
Both of these should have `<Target>` (matching up to the mono file), and`<Source>`.

**Comment by nijel** [comment]
I meant how it's configured in Weblate? Didn't you set monolingual base even for bilingual translation?

**Comment by ShadowXVII** [comment]
This can be closed and moved into #2668
Same issue.
