### ISSUE TITLE
Whitespace in source string can not be edited away.

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2602]
https://hosted.weblate.org/translate/your-local-weather/strings/nb_NO/?checksum=d5b0449c60ca142

Present when copying the translation, gone when clicking edit.

Possibly related to #2574

**Comment by nijel** [comment]
Apparently it can be edited away as you've [done that 12 days ago](https://hosted.weblate.org/translate/your-local-weather/strings/en/?checksum=d5b0449c60ca142#history) :-). But the source for other languages seem not to be updated, what is definitely a bug.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
