### ISSUE TITLE
msgmerge addon - log output of msgmerge command

### ISSUE THREAD

**Issue by ReneBoehm** [WeblateOrg/weblate#2603]
**Is your feature request related to a problem? Please describe.**
Yes and no ;) During a POT file sync the msgmerge addon only reported a non-zero exit status of the msgmerge command but no reason for this was logged, which would be the output of the msgmerge command. In our case it was a duplicate msgid.

**Describe the solution you'd like**
Just log the output of the executed msgmerge command as well. At least in case of a non-zero exit status.

**Describe alternatives you've considered**
To manually execute the logged command line. But that won't be a solution for production.

**Additional context**
nothing yet

**Comment by nijel** [comment]
You should find the output in the component alert, so you don't have to look into logs at all on production :-). But it makes sense to log it as well...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by ReneBoehm** [comment]
> You should find the output in the component alert, so you don't have to look into logs at all on production :-). But it makes sense to log it as well...

Great :) That helps a lot.
