### ISSUE TITLE
Can't add Github host key with Rancher

### ISSUE THREAD

**Issue by z31fbras** [WeblateOrg/weblate#2604]
**Describe the bug**
I have Weblate installed in a Rancher environment and I managed to make it work with my repository hosted on a self-hosted gitlab. Although, I can't manage to make it work since I migrated my repositories on Github.

My Weblate (v3.5) is hosted on Rancher and I can't add github.com host key =s

curl https://github.com works fine though.

**To Reproduce**
Install Weblate on Rancher with the official docker installation 

Set the environment variables for weblate service:

      POSTGRES_DATABASE: database
      POSTGRES_HOST: host.rds.amazonaws.com
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: '60901'
      POSTGRES_USER: user
      REDIS_HOST: cache
      REDIS_PORT: '6379'
      WEBLATE_ADMIN_EMAIL: myaddress@group.com
      WEBLATE_ADMIN_NAME: admin
      WEBLATE_ADMIN_PASSWORD: password
      WEBLATE_ALLOWED_HOSTS: '*'
      WEBLATE_DEBUG: '1'
      WEBLATE_DEFAULT_FROM_EMAIL: noreply@weblate.org
      WEBLATE_EMAIL_HOST: smtp.gmail.com
      WEBLATE_EMAIL_PASSWORD: ''
      WEBLATE_EMAIL_USER: ''
      WEBLATE_LOGLEVEL: DEBUG
      WEBLATE_REGISTRATION_OPEN: '1'
      WEBLATE_SERVER_EMAIL: noreply@weblate.org
      WEBLATE_SITE_TITLE: Nexchange Translate
      HTTP_PROXY: http://proxy-internet-aws-eu.subsidia.org:3128
      HTTPS_PROXY: http://proxy-internet-aws-eu.subsidia.org:3128
      ALL_PROXY: http://myproxy:3128

**Server configuration and status**
 * Weblate 3.5
 * Python 3.6.7
 * Django 2.1.7
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.1.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.1.0
 * python-dateutil 2.8.0
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.2
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2018.9
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.4.0
 * Mercurial 4.5.3
 * git-svn 2.17.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.13.7-1.el7.elrepo.x86_64 (x86_64)

**Additional context**
Without trying to connect to Github.com, it works fine.

**Comment by nijel** [comment]
What is the actual error you get? You can't clone GitHub repo?

**Comment by z31fbras** [comment]
@nijel Thanks for your answer!

I have the following after trying to add github.com as an host.
Here are the data I enter in the form:
Host: github.com
Port: (empty)

I get the following error: failed to fetch public key for a host!

Although, in command line, git clone github.com/myOrganization/myRepo works fine ;)

**Comment by z31fbras** [comment]
@nijel By the way, my service is behind haproxy which is a reverse proxy used for Rancher in my company.

**Comment by nijel** [comment]
The key is for ssh access, but what you describe that works is most likely https, is there some firewall which would block ssh? You can try `git clone git@github.com:myOrganization/myRepo.git`...

Anyway you should not need this in most cases, the new SSH keys should be imported by Weblate on first use.

**Comment by z31fbras** [comment]
@nijel If I try with HTTPS and not SSH it works!
This is due to my company blocking the SSH on our containers ^^'

Thanks a lot for your help, I appreciate it =)
