### ISSUE TITLE
Automatic Source Language Translations

### ISSUE THREAD

**Issue by codebykenny** [WeblateOrg/weblate#2611]
Coming from transifex, we are use to uploading a `.pot` file, and then all languages get updated `.po` files with the new strings and they get translated.

With Weblate we have the flow set up entirely.

We upload a `client.pot`, then with the addon we automatically update all the `.po` files and they all have the updated strings.

However the `source` language `.po` file, also needs to be translated. If the source language is english, shouldn't the translated strings be the same as the source string?

Is there a way to automate this? Right now we have to copy and paste the `context` to the `source` for every new string, just for comparisons sake, transifex automatically has the source language 100% and doesn't require us to translate the `source` language.

![image](https://user-images.githubusercontent.com/6720728/53994512-834a4980-4100-11e9-816c-4b3c8c46ca46.png)

![image](https://user-images.githubusercontent.com/6720728/53994621-cefcf300-4100-11e9-8773-89dcc6ea9dd4.png)

**Comment by nijel** [comment]
You should not be setting monolingual base in this case at all as you're using bilingual translation files. See https://docs.weblate.org/en/latest/formats.html#bilingual-and-monolingual-formats

**Comment by codebykenny** [comment]
Hello @nijel I think you're absolutely right and it should be a bilinqual format. We have changed to this now.

However the issue remains, we are still forced to translate the source language.

Is there a way to automate the source language translations?

All the strings are in `english` so we don't want to have to copy and paste each string for `english` translations. The `source` and `translation` are exactly the same for english.

**Comment by nijel** [comment]
Do you actually need that file? In normal gettext operation, English just uses text strings and there is no need to copy anything. But maybe I'm missing something.

**Comment by maicol07** [comment]
@nijel this issue is alreay in latest version. Could you fix it?

**Comment by nijel** [comment]
There was no response to my question in this issue, that's why it was closed after some time. @maicol07 What exactly is your problem? Maybe it's better to open separate issue for that?

**Comment by nijel** [comment]
Using PO files as well? Can you please describe your workflow?

**Comment by maicol07** [comment]
When I release a new version of my app, I upload to Weblate the PO file of the source language but Weblate doesn't set them automatically as translated.
Schematics:
New release --> PO file generation (source language) --> Source language PO upload (through Weblate UI)

**Comment by nijel** [comment]
But why do you need such source language PO files? Don't get me wrong, I'm just trying to figure out reasons :-).

**Comment by maicol07** [comment]
@nijel because in this way automatic translation don't work...

**Comment by nijel** [comment]
It should not need any extra translations. Can you share your component configuration and sample of the PO file?

**Comment by maicol07** [comment]
@nijel Here is component config:
![immagine](https://user-images.githubusercontent.com/9463142/73302831-93d24980-4215-11ea-928b-5faebbe7edf2.png)

And here is the sample PO (zipped because Github doesn't accepts po files):
[messages.zip](https://github.com/WeblateOrg/weblate/files/4124463/messages.zip)

**Comment by codebykenny** [comment]
> But why do you need such source language PO files? Don't get me wrong, I'm just trying to figure out reasons :-).

Just to give an example of why our company had a source language PO. We came from Transifex. The Transifex system had a source language PO which would always remain translated and we kind of created our system under the assumption that we should have a PO for the source language as well.

I'm not entirely sure if thats normal or not as Transifex was the extent of our experience with localizations.

**Comment by maicol07** [comment]
@codebykenny I've also had some projects on transifex so I know this situation (some files from old projects came from Transifex)

**Comment by maicol07** [comment]
@nijel I know source strings in PO system don't get used but I think this is more for uniformity with other templates

**Comment by nijel** [comment]
The POT upload feature is present in the 4.0 release.
