### ISSUE TITLE
Few issues with Quick setup guide

### ISSUE THREAD

**Issue by benjaminglatzeder** [WeblateOrg/weblate#2614]
**Describe the bug**
Following the [Quick setup guide](https://docs.weblate.org/en/latest/admin/quick.html)

There is a typo
`apt install python3-pip python3-virtualenv virtualevn`
should be
`apt install python3-pip python3-virtualenv virtualenv`

**Describe the bug**
Mysqlclient installation fails. Here's the full log:

```bash
pip install mysqlclient
Collecting mysqlclient
  Downloading https://files.pythonhosted.org/packages/f4/f1/3bb6f64ca7a429729413e6556b7ba5976df06019a5245a43d36032f1061e/mysqlclient-1.4.2.post1.tar.gz (85kB)
    100% |████████████████████████████████| 92kB 2.1MB/s
    Complete output from command python setup.py egg_info:
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-g8svgl5j/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-g8svgl5j/mysqlclient/setup_posix.py", line 51, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-g8svgl5j/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found

    
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-g8svgl5j/mysqlclient/
```

**Expected behavior**
Install mysqlclient successfully.

**Describe the bug**

New folder names for new python version needed and underscore needed instead of hyphen for file `settings-example.py`

```bash
Copy the file ~/weblate-env/lib/python2.7/site-packages/weblate/settings-example.py to ~/weblate-env/lib/python2.7/site-packages/weblate/settings.py
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
