### ISSUE TITLE
Download original translation file with not translated strings

### ISSUE THREAD

**Issue by farkasgzoltan** [WeblateOrg/weblate#2616]
Hello!

would I have 2 suggestions to find out somehow or is it possible?
1.
Download original translation file with Single-language basic language file not translated strings
translated strings and not translated strings mergering in a custom download original translation file...

2. 
Download original translation filename why not match the basic language filename syntax?

Thanks

**Comment by nijel** [comment]
The generated filename is always consistent from Weblate no matter what original filename was. This is to allow saving more files next to other.

And I don't understand your first point, sorry, can you please clarify?

**Comment by farkasgzoltan** [comment]
sorry for the wrong wording... 

Download original translation file syntax

<string name="loading">Betöltés</string>   "translated"
<string name="press_any_key"/>                   "not translated"

what would i need "custom download original translation file"...
automatic addition of not translated with original strings

<string name="loading">Betöltés</string>   "translated"
<string name="press_any_key">Press any key</string>               "automatic addition of not translated"

**Comment by nijel** [comment]
Well then it's not an original file :-). This is issue with the monolingual formats, that's why Weblate offers several downloads in bilingual formats which address this better without messing up with the translations like your proposal (it makes it easy to miss something in that case).

**Comment by farkasgzoltan** [comment]
And if we look at it as a "test file" without more editing?

**Comment by nijel** [comment]
We could add another download option, but I still think bilingual formats like Gettext or XLIFF are just better suited for offline editing in this case.

**Comment by farkasgzoltan** [comment]
There are programs, games whose strings needed to be there to work on the text display if there is no translated...
eg. csv, xml monolingual formats
if there was such a download option that would add to the monolingual format amutomatically... but there is still no editing for this download format. only test format.
