### ISSUE TITLE
Present flag dropdown menu right away when pressed

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2619]
Clicking this (flagg):
![flagg](https://user-images.githubusercontent.com/13802408/54142217-89edff00-4427-11e9-97ea-3d509bb9a83a.png)

---
Takes the user to this (different page):
![dropdown](https://user-images.githubusercontent.com/13802408/54142216-89edff00-4427-11e9-8529-200432e390f0.png)

---

When seeing any string as an admin in non-Zen mode, (for example https://hosted.weblate.org/translate/f-droid/website/nb_NO/?checksum=5a7be9d09152da44 ) it takes a while to change flags, since it is a nested menu.

**Comment by nijel** [comment]
The whole flag editing needs better UI and the UI should be used in all places where flags can be edited. Making it inline in the translation might be an option as well, but it needs to make it clear that it's editing flags for source string and that affects all translations...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
