### ISSUE TITLE
Tag hotkeys confuse users

### ISSUE THREAD

**Issue by TheLastProject** [WeblateOrg/weblate#2620]
**Describe the bug**
Weblate numbers all tags in the string to translate, which confuses users

**To Reproduce**
1. Go to https://hosted.weblate.org/translate/pext/pext-radio-module/hi/?checksum=ab111c2987763da3
2. Notice all the numbers next to the tags
3. Notice how the translator copied the numbers:
![image](https://user-images.githubusercontent.com/1885159/54145022-5910c880-442d-11e9-95ef-24681ac47aa1.png)

**Expected behavior**
No numbers next to the tags

**Server configuration and status**
Hosted Weblate

**Additional context**
I'm sure the numbers have an actual meaning, but this is the third translator just in the Pext project who types over the numbers and thus mistranslates the string. It seems to be more confusing than helpful.

**Comment by nijel** [comment]
The numbers are there for keyboard shortcuts, but indeed it is confusing for some users. The situation should be better since bd8ba3007424f6096358c76b6f6eba71bc8c21c2, since these numbers are no longer selectable for copying into clipboard, but apparently this really doesn't solve the problem...

**Comment by comradekingu** [comment]
You get the numbers if you mouseover, select the text, and copy it.
I think it would happen way less if that wasn't the case.

**Comment by nijel** [comment]
Ah, apparently `user-select` currently only works in some browsers, I've added vendor prefixed version in 18099ff284d1fa85859d669189c529ccd73f6652 which should make it more acceptable, see https://developer.mozilla.org/en-US/docs/Web/CSS/user-select#Browser_compatibility

**Comment by TheLastProject** [comment]
I've talked more with one of the users mistranslating this and apparently they were manually typing it all over. Could it perhaps be possible to hide it until control is pressed, together with the suggestion of comradekingu in edit 2? I think that should eliminate all possible confusion

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
