### ISSUE TITLE
just clicking "Suggest" creates a suggestion with the exact same text as the translation

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#2622]
**Describe the bug**

If someone mistakenly clicks "Suggest" without changing the text, a suggestion is created that has the exact same text as is in the current translation.

**To Reproduce**

https://hosted.weblate.org/translate/f-droid/website/de/?type=all&offset=8#suggestions

1. Go to any fully translated string
2. click "Suggest"
3. see new Suggestion in the Suggestions tab with text matching the current translation

**Expected behavior**

It should use whatever UX pattern that Weblate uses to show that "Suggest" does nothing unless the text is changed.  That could be that the button is disabled/greyed out until the translation text changes, etc. Seems like the Save button should do the same thing but that is less important.

**Server configuration and status**

hosted.weblate.org

**Comment by nijel** [comment]
I *think* there was issue for this and it was fixed, but I can't find that and the code doesn't seem to contain such check, so I'm apparently wrong.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
