### ISSUE TITLE
squash addon stopped squashing in mixed repo

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#2623]
**Describe the bug**

The F-Droid website is a collection of different filetypes (gettext and nested JSON) in a single git repo.  The squash addon has been active on it for a while.   It has been working nicely since I enabled it, until yesterday.  As far as I remember, it has been set to "per-language" the whole time.  I added the "Customize JSON output" addon to the main component yesterday, that might have affected the squashing, but I'm not sure.

In order to try to trigger the squash, I changed a translation of the root project, and pressed Commit.  It still did not squash.

 These are the components in question:

* https://hosted.weblate.org/projects/f-droid/website
* https://hosted.weblate.org/projects/f-droid/website-docs
* https://hosted.weblate.org/projects/f-droid/website-pages
* https://hosted.weblate.org/projects/f-droid/website-posts
* https://hosted.weblate.org/projects/f-droid/website-tutorials

**To Reproduce**

1. see unsquashed commits in https://hosted.weblate.org/projects/f-droid/website
2. commit a translation change
3. see there are still unsquashed commits there

**Expected behavior**

The commits to be squashed per-language like what was happening before.

**Server configuration and status**

hosted.weblate.org

**Comment by nijel** [comment]
The squash addon needs to be able rebase changes on current upstream master, due to merge error that doesn't work and that's why it doesn't do anything.

**Comment by eighthave** [comment]
It seems it is still not doing a full squash, so I think this is a valid bug report after all.  In the current status of this account, all the weblate commits are rebased on upstream's _master_.  But there are two commits on the same file _po/_posts.de.po_.  And there are two commits for the same language, Ukrainian, but different files.

Also, needing to rebase on current upstream master makes sense, but is counter-intuitive if someone is not familiar with git.

**Comment by eighthave** [comment]
There are also two _nb_NO_ commits, with different files.

**Comment by nijel** [comment]
I see that it was there, but when I tried to perform some changes, it did properly squash, but apparently it needs further investigation.

**Comment by eighthave** [comment]
so I did a reset in weblate after I manually merged in the conflicting
commits.  So those commits were just the ones that were automatically
added by weblate after the reset.  I think there was no updates to the
upstream git repo in the mean time, so maybe the issue was that it won't
squash until it rebases on the upstream repo?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
