### ISSUE TITLE
New language requests are missing a link to the project in question

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2629]
It says who requested the language etc,
but there is no link to the project so that it can be added.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
