### ISSUE TITLE
Nested projects or project grouping

### ISSUE THREAD

**Issue by lurdan** [WeblateOrg/weblate#263]
The problem:
Weblate can't(may not) handle large project, including multiple independent documents which consists of multiple po files.
These subprojects can share glossaries, so it had better create as included in one project.

(ex. I want to set up debian documentation project translation project for japanese. https://github.com/lurdan/trans-ddp )
##

**Comment by nijel** [comment]
While implementing related feature I've come to this issue. So there are basically two issues here:

* Adding more structure than just project/component. This can be done using [component lists](https://docs.weblate.org/en/latest/admin/componentlists.html) and can be used both to split up projects or to group components in several projects together.
* Having shared glossaries, this is covered by https://github.com/WeblateOrg/weblate/issues/1158

For the setup you describe, it is probably best to use separate projects for independent documents and group them using component lists. The only missing piece is shared glossary.

**Comment by nijel** [comment]
It might be actually useful to provide tree like a structure within a project. That would not complicate things for smaller projects, but allow complex structure for bigger ones.

**Comment by nijel** [comment]
Typical example which would utilize some kind of nesting is [LibreOffice](https://weblate.documentfoundation.org/).

What would be probably useful to have here is: LibreOffice Help / master / Calc / Guide

**Comment by Justman10000** [comment]
@nijel 

Are you working on it? This damn issue existed for _**9 years**_! Only **_5 years_** later came an answer... I don't know...

**Comment by nijel** [comment]
We have even older issues and we welcome contributions!

I expect we get to this one this year. We're a small team and need to prioritize work.

**Comment by m-aciek** [comment]
Another use case to consider: Python docs are being translated for all stable releases (e.g. 3.10, 3.9, 3.8 and 3.7 currently). Subprojects or "organization" wrapper for projects plus shared glossary and default translation memory propagation (already can be achieved, but not by default AFAIK) would work for them.
