### ISSUE TITLE
"indexing offloading" doesn't exist anymore

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#2630]
**Describe the bug**
The latest docs mention an old optimization feature with a hard link to an older documentation version

**To Reproduce**
1. Go to https://docs.weblate.org/en/latest/admin/projects.html#optimize-configuration
2. See error

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
