### ISSUE TITLE
Fastlane not yet available ?

### ISSUE THREAD

**Issue by PhieF** [WeblateOrg/weblate#2631]
Hi,

I've seen on the documentation that weblate was able to translate fastlane metadata
doc : https://docs.weblate.org/en/latest/formats.html
I'm running weblate 3.5.1 but when setting my fastlane repo I can't find "Market metadata text files" as file format
and setting "Monolingual base language" file to "metadata/en_US" leads to a "Template file not found!" error

any ideas why ?
here is my fastlane repo https://github.com/PhieF/CarnetFdroid
Thanks for weblate, very good tool :))

**Comment by nijel** [comment]
It was renamed to "App store metadata files", but the docs was not updated...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by PhieF** [comment]
OK! thanks

Then I've tried  this one but it still doesn't work, any ideas ? 
I still have this 

> "Monolingual base language" file to "metadata/en_US" leads to a "Template file not found!" error

**Comment by nijel** [comment]
Maybe because it's `metadatada/en-US`? Note dash instead of undescore.

**Comment by PhieF** [comment]
Oh gosh, I miss read this

thank you, I'm sorry for that :)
