### ISSUE TITLE
Exclude users from rate limit

### ISSUE THREAD

**Issue by raphaelm** [WeblateOrg/weblate#2632]
**Is your feature request related to a problem? Please describe.**
I, as the admin user, often need to process lots of translations. For example, we translate into two very similar variants of a language: Once the first one of them is translated, translating the second one can be done real quick with copy+paste. In that step, I regularly get annoyed by the rate limit.

I could turn the rate limit off or tune it to a different value (which would require me to inject custom settings into the docker container), but I think in general it is useful to keep.

**Describe the solution you'd like**
It would be great if I'd be able to whitelist tustworthy users.

**Describe alternatives you've considered**
* Turning off ratelimiting completely.
* Turning off ratelimit for staff/superuser users, but that wouldn't be as flexible.

**Comment by nijel** [comment]
For me the preferred approach would be to find rate limiting which will not limit regular usage, while will block malicious one. Having whitelisting sounds really too complex for this and would be similarly inflexible as filtering superusers.

On what version do you observe the problem? The rate limiting has been tweaked in all most of recent releases to address such issues...

**Comment by raphaelm** [comment]
> For me the preferred approach would be to find rate limiting which will not limit regular usage, while will block malicious one.

Well, sure, that would be best, but the balance is hard to strike. 

>  Having whitelisting sounds really too complex for this

I wouldn't think a whitelist would be that complex, we'd just need a ``ignore_ratelimit`` flag stored in the ``auth.User`` model (or with a role/permission?) and then add a ``if not request.user.ignore_ratelimit:`` here:
https://github.com/WeblateOrg/weblate/blob/0601168583cad90346817138bd38e91c38fe9229/weblate/utils/ratelimit.py#L88-L107

> and would be similarly inflexible as filtering superusers.

Not sure. There's a couple of contributors to our translation who have contributed for years and I'd totally trust them to do as many requests as they want, even if they would want to automate something. However, that doesn't mean I want to make them superusers ;)
On what version do you observe the problem? The rate limiting has been tweaked in all most of recent releases to address such issues...

We're running 3.4 at the moment, I can see if 3.5 makes it easier for us if there were changes to this.

**Comment by raphaelm** [comment]
Just ran into it again on 3.5, even without copy paste :( I was translating week day and month names ("January", "February", …), which I apparently can do to quickly. No I need to reschedule my work for (how much?) later, which is really a bit frustrating :(

**Comment by nijel** [comment]
Today, I've removed no-op edits from the rate limit (in 2314ea9b81f7f2d0b60fe499bbfdeab05c7cab2c), what should make situation better in some cases.  But that will probably not help in your case...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed by increasing the default rate to 30 edits in 60 seconds.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
