### ISSUE TITLE
Ability to configure password expiration policies

### ISSUE THREAD

**Issue by SBSolera** [WeblateOrg/weblate#2633]
**Is your feature request related to a problem? Please describe.**
Some organizations have blanket rules that all systems which store passwords have an expiration of xx days. Even though no sensitive data is stored within Weblate, employees may have to adhere to this policy.

**Describe the solution you'd like**
Setting a password expiration in number of days system wide would be sufficient in the Settings.py file.
Even better would be if you could set password policies on a per group basis (i.e. 60 days for admins and 90 days for all other users)

**Describe alternatives you've considered**
I don't believe there is any good alternative other than manually looking at how old an account is and then forcing them to reset. This is not feasible in most situations

**Additional context**
It appears there are some django middlewares which support this functionality. More info [here](https://django-user-accounts.readthedocs.io/en/latest/usage.html)

**Comment by nijel** [comment]
I'm not sure this is something what should be handled by Weblate. Password expiration is not considered a good idea these days, see [FTC](https://www.ftc.gov/news-events/blogs/techftc/2016/03/time-rethink-mandatory-password-changes) or [NCSC](https://www.ncsc.gov.uk/collection/passwords?curPage=/collection/passwords/updating-your-approach) (to show some official sources, you can definitely find more on this topic).

As you've mentioned there are some third party modules for Django which might achieve this behavior (though it might be tricky to integrate as Weblate already uses custom User model).
