### ISSUE TITLE
Commits from linked components are not pushed

### ISSUE THREAD

**Issue by SlavekB** [WeblateOrg/weblate#2634]
**Describe the bug**
I have a major repository that contains many linked components. Since version 3.4.0, I observe that commits are created for translations in components, but are not pushed.

Option push_on_commit is set to '1' on both - the main component and also on all linked components. Of course, the push address is just on the main component.

When I push from the Weblate web interface manually, there is no problem, commits are pushed to remote git.

**Expected behavior**
The expected behavior is that the changes will not only be committed but also pushed.

**Server configuration and status**
```
 * Weblate 3.5.1
 * Python 2.7.13
 * Django 1.11.15
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 3.1.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 5.2.0
 * python-dateutil 2.7.3
 * lxml 4.2.5
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * diff-match-patch 20121119
 * pytz 2018.5
 * pyuca 1.1.2
 * PyYAML 3.12
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 3.16.6-042stab134.46 (x86_64)
```

```
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.5.1/admin/install.html#collecting-errors

System check identified 1 issue (0 silenced).
```

**Additional context**
Before upgrade to 3.4.0, the problem with the push did not exist. The update to 3.5.1 did not resolve this regression.

**Comment by nijel** [comment]
I don't see any related change between 3.4 and 3.5.1. The push on commit is happening in background using Celery, so maybe your Celery is not operating correctly. Have you restarted it after upgrade? Are there any errors in the Celery logs?

**Comment by SlavekB** [comment]
The change probably occurred between 3.3 and 3.4, as 3.4 did not push commits. Celery now works well – after all, if it didn't work well, no commits would be created :smiley_cat:

**Comment by nijel** [comment]
It can be just the push task failing for some reason. If Celery would not be working at all it would be visible in system checks pasted above. That's why I've asked for errors in the Celery workers logs.

**Comment by SlavekB** [comment]
I watched the log when commit was made – celery successfully created commit, but no other log messages followed - no bugs, no information that there is another celery task.

```
[2019-03-11 10:02:51,359: INFO/ForkPoolWorker-2] Lock 140086441555984 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-11 10:02:51,496: DEBUG/ForkPoolWorker-2] git: exec git status --porcelain -- tde-i18n-cs/messages/tdebase/ksmserver.po [retcode=0]
[2019-03-11 10:02:51,497: INFO/ForkPoolWorker-2] tdebase/ksmserver/cs: committing tde-i18n-cs/messages/tdebase/ksmserver.po as Sl?vek Banko <slavek.banko@axis.cz>
[2019-03-11 10:02:51,757: DEBUG/ForkPoolWorker-2] git: exec git add --force -- tde-i18n-cs/messages/tdebase/ksmserver.po [retcode=0]
[2019-03-11 10:02:53,124: DEBUG/ForkPoolWorker-2] git: exec git commit --message Translated using Weblate (Czech)

Currently translated at 100.0% (58 of 58 strings)

Translation: tdebase/ksmserver
Translate-URL: https://mirror.git.trinitydesktop.org/weblate/projects/tdebase/ksmserver/cs/ --author Sl?vek Banko <slavek.banko@axis.cz> --date 2019-03-10T00:36:24.124040+00:00 [retcode=0]
[2019-03-11 10:02:53,201: INFO/ForkPoolWorker-2] Lock 140086441555984 released on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
```

Note: You can see that in the log the encoding is wrong in the name of the author.

**Comment by nijel** [comment]
Please restart Celery, it seems to be still running code from some older version (it is executing code which was removed in 3.5), while your seem to be running 3.5. That can be also reason for this issue.

**Comment by SlavekB** [comment]
This is strange – since the update to 3.5.1 I have restarted the celery task several times. Now I added the patch 2493871 and restarted again.

**Comment by SlavekB** [comment]
It is possible that the previous log was from 3.4 – shortly before updating to 3.5.1. This should be the same situation with 3.5.1.

```
[2019-03-14 03:31:50,102: INFO/ForkPoolWorker-3] Lock 140353528882896 released on /var/lib/webl
ate/data/vcs/dependencies/tqt3.lock
[2019-03-14 09:02:52,544: INFO/ForkPoolWorker-3] tdebase/twin/cs: committing pending changes (c
ommit_pending)
[2019-03-14 09:02:52,565: INFO/ForkPoolWorker-3] Lock 140353529861968 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-14 09:02:53,013: INFO/ForkPoolWorker-3] Lock 140353529861968 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-14 09:02:53,013: INFO/ForkPoolWorker-3] Lock 140353529861968 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-14 09:02:53,212: INFO/ForkPoolWorker-3] tdebase/twin/cs: committing [u'/var/lib/weblate/data/vcs/tde/tde-i18n/tde-i18n-cs/messages/tdebase/twin.po'] as Sl?vek Banko <slavek.banko@ax
is.cz>
[2019-03-14 09:02:54,121: INFO/ForkPoolWorker-3] Lock 140353529861968 released on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
```

**Comment by nijel** [comment]
Sorry, maybe I was wrong, that code still can be executed in some cases...

**Comment by nijel** [comment]
If push on commit was not enabled on all linked components, then 2493871 should address your problem, but if it was, we should look somewhere else...

**Comment by SlavekB** [comment]
Push on commit should be enabled on all linked components – at least I checked it on the components for which the commits were created but were not pushed.

I added 2493871 on my Weblate instance , so I will try to make some other changes in translations to see if the changes will now be pushed.

**Comment by nijel** [comment]
Can you please also add 2b9937a173? With it it should show information why push was skipped after commit.

**Comment by nijel** [comment]
Thank you for your report, I think the issue you have reported has just been fixed in https://github.com/WeblateOrg/weblate/commit/ecde2019e9601cdbb77e07123317bcacd1f41dc0.

* It would be great if you could verify the fix.
* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by SlavekB** [comment]
I included a commit on my instance and increased the level of celery logging to DEBUG. In about 3 hours, translation should be committed and pushed, so we'll see…

**Comment by SlavekB** [comment]
Great, now I can confirm that the new commit was written and shortly afterwards all the waiting commits were pushed into the remote repository. Thank you for solving the issue!
