### ISSUE TITLE
Possibility of rejecting suggestions

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2635]
There is a [suggestion](https://hosted.weblate.org/translate/osmand/main/nb_NO/?checksum=3778fd0321ee854d) I want to reject.
It, along with the [most recent translation](https://hosted.weblate.org/translate/osmand/main/nb_NO/?checksum=3778fd0321ee854d), was made 2 months ago, so dont't know which is newer.

I want to delete this suggestion, but there is no button to do so.
Effectively I could

- Accept it with edits, and put my version in, 
or 
- Accept it, and click to recover my version
or
- Accept it, and add my version again manually

I suppose it is somewhat interesting to see unaccepted suggestions in the history, so one of those with a button to do it? It is important for someone to know what it was that didn't get accepted. Either everyone else if it is better, or the author if worse.

**Comment by nijel** [comment]
The suggestion removal is there, but currently it's only enabled for superusers, what is apparently wrong. At least project admins definitely should have this permission.

**Comment by nijel** [comment]
Okay, project admins can already do that, so the questions if it really should be open to anybody or not...
