### ISSUE TITLE
Add callback URL for Github in documentation

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#2637]
**Is your feature request related to a problem? Please describe.**
it's not that easy to configure github authentification:
https://docs.weblate.org/en/latest/admin/auth.html?highlight=oauth#github-authentication

**Describe the solution you'd like**
please add the CallBack URL form (/accounts/complete/github) in documentation and in example settings.py as a comment

**Additional context**
Once configured properly, it works really well <3

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
