### ISSUE TITLE
Overnight git process fails to pull, yet repository maintenance pulls without issue

### ISSUE THREAD

**Issue by netniV** [WeblateOrg/weblate#2641]
**Describe the bug**
Our weblate instance is currently constantly throwing up the following error across all repositories when it does an overnight automated self-update of our sources:
```
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists. (128)
```

When you view the repository maintenance section, it shows no entry for that date/time that I can see and works perfectly when I use the `pull` button.

I have also noticed that when forcing a pull, no entry shows in the audit.  I feel this should show that a pull request was made even if nothing was updated especially on a manual pull (automated ones would probably just spam the audit).

**Screenshots**
![image](https://user-images.githubusercontent.com/9052188/54517406-7f68c380-4959-11e9-952e-edfa4ec3bed7.png)

![image](https://user-images.githubusercontent.com/9052188/54517438-9ad3ce80-4959-11e9-93d0-a576a11ac782.png)

**Server configuration and status**
_VERSIONS_
```
$ weblate list_versions
DEBUG git: exec git svn --version [retcode=1]
DEBUG git: exec git --version [retcode=0]
DEBUG git: exec git review --version [retcode=1]
 * Weblate 3.4-dev
 * Python 2.7.5
 * Django 1.11.18
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 2.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 1.8.3.1
 * Pillow 5.4.1
 * python-dateutil 2.7.5
 * lxml 4.3.0
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * diff-match-patch 20121119
 * pytz 2018.9
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 3.10.0-957.1.3.el7.x86_64 (x86_64)
```

_DEPLOY INFO_
```
$ weblate check --deploy
DEBUG git: exec git svn --version [retcode=1]
DEBUG git: exec git --version [retcode=0]
DEBUG git: exec git review --version [retcode=1]
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/latest/admin/install.html#collecting-errors

System check identified 4 issues (0 silenced).
```

**Comment by nijel** [comment]
Maybe the service was not running back then? What repository URL do you have configured?

**Comment by netniV** [comment]
It's a git repository via HTTPS.  I have checked, the service is definitely running as it's been happening overnight for the past few nights.  The command line and web are able to pull without issue, and the service is running under the same account.

**Comment by netniV** [comment]
I would post the status that showed it running but unfortunately I literally just restarted it after making a change as I just changed the email from/names to ones to match our services.

**Comment by netniV** [comment]
```
]$ systemctl status weblate celery-weblate
â weblate.service - weblate
   Loaded: loaded (/etc/systemd/system/weblate.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2019-03-18 04:12:20 CDT; 27min ago
 Main PID: 6904 (weblate-service)
   CGroup: /system.slice/weblate.service
           ââ6904 /bin/bash /app/weblate/venv/lib/python2.7/site-packages/weblate/weblate-service.sh
           ââ6907 /app/weblate/venv/bin/python /app/weblate/venv/bin/weblate runserver 127.0.0.1:8008
           ââ7162 /app/weblate/venv/bin/python /app/weblate/venv/bin/weblate runserver 127.0.0.1:8008

â celery-weblate.service - Celery Service (Weblate)
   Loaded: loaded (/etc/systemd/system/celery-weblate.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2019-03-18 04:12:24 CDT; 27min ago
  Process: 6902 ExecStop=/bin/sh -c ${CELERY_BIN} multi stopwait ${CELERYD_NODES}    --pidfile=${CELERYD_PID_FILE} (code=exited, status=0/SUCCESS)
  Process: 6946 ExecStart=/bin/sh -c ${CELERY_BIN} multi start ${CELERYD_NODES}    -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE}    --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} ${CELERYD_OPTS} (code=exited, status=0/SUCCESS)
  Process: 6943 ExecStartPre=/bin/chown -R weblate /var/log/celery/ (code=exited, status=0/SUCCESS)
  Process: 6940 ExecStartPre=/bin/mkdir -p /var/log/celery (code=exited, status=0/SUCCESS)
  Process: 6937 ExecStartPre=/bin/chown -R weblate /var/run/celery/ (code=exited, status=0/SUCCESS)
  Process: 6935 ExecStartPre=/bin/mkdir -p /var/run/celery (code=exited, status=0/SUCCESS)

**Comment by netniV** [comment]
Another log entry that may help, I just saw this:
```
2019-03-18 10:55:19,870 ERROR cacti/core: failed to update repository: fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists. (128)
```
When I went to the data folder and checked the .git/config it looked fine:
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/Cacti/cacti.git
        fetch = +refs/heads/develop:refs/remotes/origin/develop
        pushurl = https://github.com/Cacti/cacti.git
[branch "develop"]
        remote = origin
        merge = refs/heads/develop
```

and when I attempted the same command:
```
[core]$ git fetch origin
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 12 (delta 8), reused 9 (delta 6), pack-reused 0
Unpacking objects: 100% (12/12), done.
From https://github.com/Cacti/cacti
   805ec48..b7506ce  develop    -> origin/develop
```
This makes me wonder if it is not in the correct directory when it is attempting to do the fetch.

**Comment by netniV** [comment]
Please note, that is a public URL so username/password do not matter.

**Comment by netniV** [comment]
Sorry for the number of posts, but I just spotted something else.  In the $HOME of the user, is a `data` directory which mostly appears out of date apart from the `memory` and `whoosh` folders.

This is not the same location as the one I had to put the .git credentials into to make the git push work properly as whoosh and memory appear to be populated under the original $HOME/data whereas the DATA_DIR/vcs and DATA_DIR/home directories are under site-packages/data

**Comment by netniV** [comment]
I have confirmed that this seems to be the case.  Because the log isn't distinguishing between whether it's the service, website or command line, it can be tricky to work out which is doing what.  So I left everything alone, committed a fix and then checked a git.log file that I started generating which pumps in the home dir, current dir, and command being run:

Non-working:
```
[2019-03-18 14:17:24+00:00] Current Dir: /app/weblate/data/vcs/cacti/core
[2019-03-18 14:17:24+00:00] Home Dir...: /app/weblate/data/home
[2019-03-18 14:17:24+00:00] Command....: /usr/bin/git fetch origin
```

Working:
```
[2019-03-18 14:18:49+00:00] Current Dir: /app/weblate/venv/lib/python2.7/site-packages/data/vcs/cacti/core
[2019-03-18 14:18:49+00:00] Home Dir...: /app/weblate/venv/lib/python2.7/site-packages/data/home
[2019-03-18 14:18:49+00:00] Command....: /usr/bin/git fetch origin
```

The working was done via the website, whereas the non-work was done by the background service, so I am assuming will be the celery launch processes?

**Comment by nijel** [comment]
It seems that your [DATA_DIR](https://docs.weblate.org/en/latest/admin/config.html#data-dir) is set differently in those environments, maybe you forgot to restart one of the services after changing settings?

**Comment by nijel** [comment]
Or maybe you have two installations of Weblate and Celery not using the one in virtual env?

**Comment by netniV** [comment]
I've not had chance to return to it this evening but my gut is pretty sure the celery instances are not using the virtual env.  So, I will just have to figure out what is needed to start that before launching the celery process.

**Comment by netniV** [comment]
So I had another look and tried to use venv/bin/active && venv/bin/celery, which launches but makes zero difference.  

I then had a look at settings.py, which appears to be calculating it's DATA_DIR based of the base directory, which is the location of the file being run dirname(__file__).  

The only way I can make this work is to symlink the $HOME/data to site-packages/data

**Comment by nijel** [comment]
Yes, the example settings calculate DATA_DIR relative to it's location, but that should not change between exection unless you are having two different settings files used, what I think is your case - one defines ``DATA_DIR = '/app/weblate/data/'`` and the other has the default value.

Things which might be different between wsgi and celery execution environment:

* Different Python search path, do you manipulate with PYTHONPATH (in uwsgi config it's AFAIK lowercase)
* Different virtualenv
* Changed settings module, check for DJANGO_SETTINGS_MODULE environment variable
