### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2643]
**Is your feature request related to a problem? Please describe.**
In several situations it might be useful to search for more complex conditions than current search allows. Probably something similar like GitHub has (see https://github.com/search/advanced).

This at least should cover:

* Number of votes
* Last change (see https://github.com/WeblateOrg/weblate/issues/2455)
* Skipping own suggestions (see https://github.com/WeblateOrg/weblate/issues/2023)

**Describe the solution you'd like**
Possibility to specify more search parameters in both UI and text box.

**Describe alternatives you've considered**
Current search forms really don't scale well further.

**Comment by nijel** [comment]
In the end, this might be blocked by #2831, so the question is whether to move all this to 3.10 or prioritize blocking issues for 3.9.

**Comment by nijel** [comment]
The new search is currently used only for screenshots adding (where only substring search was available previously) and is documented here: https://docs.weblate.org/en/latest/user/search.html

Full features and replacement of normal search depends on https://github.com/WeblateOrg/weblate/issues/3007 and https://github.com/WeblateOrg/weblate/issues/2831.

**Comment by nijel** [comment]
Partly addressed by https://github.com/WeblateOrg/weblate/pull/3059, rest will be implemented after #3007 and #2831.

**Comment by ramon-b** [comment]
A dropdown to filter on context (groups) would also be nice. It is already possible to search in context, but translators do not always know the context (group(s)). We are using i18next, whereby we have contexts like .support.form.title. Our translators want to be able to select a group, so that they can search in specific (sub)groups without using regex.
