### ISSUE TITLE
Spaces in name cause git commands to fail

### ISSUE THREAD

**Issue by netniV** [WeblateOrg/weblate#2644]
**Describe the bug**
If you put a space in a name field used by git, the field can fail because the data is not wrapped in quotes, eg, commiter name.

**To Reproduce**
Set a committer name of a component to include a space.

**Expected behavior**
I'm assuming that the strings should be quoted.

**Comment by netniV** [comment]
I actually now think this may be more to trying to use the --replace-all with user.name or that there is a global configuration, and it doesn't like replacing that whilst replacing the local one.

**Comment by nijel** [comment]
I don't think spaces are actual the problem. Can you please provide the actual error you get?

The `--replace-all` was introduced in 9bdd722452a to address https://github.com/WeblateOrg/weblate/issues/2321.

**Comment by netniV** [comment]
I did attempt to copy and paste the command line and it kept giving me warnings when I ran it manually too.  However, I've tried testing this just now and I can't get it to reproduce so I'm going to close it unless I can make it re-occur.  

I'm having some 'issues' with the whole installation were I correct one problem and another appears so it may have been corrected by fixing something else.
