### ISSUE TITLE
Source code links do not include branch despite replacement text containing it

### ISSUE THREAD

**Issue by netniV** [WeblateOrg/weblate#2645]
**Describe the bug**
For a component, set the branch to the default branch of your repo.  Then edit the component and set the source code url to:

```
https://github.com/<user>/<repo>/blob/%(branch)s/%(file)s#L%(line)s
```
Where `<user>` and `<repo>` are the correct github user/repo's.

The actual URL opened is 
```
https://github.com/<user>/<repo>/blob/%(file)s#L%(line)s
```
which results in a 404 error.

Did I get the URL wrong or is this an actual bug?

**Comment by nijel** [comment]
I guess is that it is on linked repository. That issue has been fixed by 530fc89725b. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by netniV** [comment]
No, these are all independent repositories.

**Comment by netniV** [comment]
Thanks for the commit link, that helps me to trace the area I needed to add some debugging without searching like crazy ;-)

I added some log info, and found this:
```
2019-03-19 08:31:25,092 INFO cacti/cycle: repoweb was https://github.com/Cacti/plugin_cycle/blob/%(branch)s/%(file)s#L%(line)s
2019-03-19 08:31:25,093 INFO cacti/cycle: repoweb now https://github.com/Cacti/plugin_cycle/blob/develop/../cycle.php#L47
```

**Comment by netniV** [comment]
So I did some more digging on this because I couldn't see why this wouldn't have been spotted earlier.  To cut through the following details, it was down to the way we generate the pot as we have a script in /locales/ that then searches ../*.php for strings.

At first I tried to adjust the keyed string format but that made zero difference.  So I decided to add various log_info()'s into get_repoweb_link() which resulted in giving me:
```
2019-03-19 08:45:42,735 INFO cacti/cycle: filename was ../cycle.php
2019-03-19 08:45:42,735 INFO cacti/cycle: line    was 47
2019-03-19 08:45:42,736 INFO cacti/cycle: branch  was develop
2019-03-19 08:45:42,736 INFO cacti/cycle: repoweb was https://github.com/Cacti/plugin_cycle/blob/%(branch)s/%(file)s#L%(line)s
2019-03-19 08:45:42,736 INFO cacti/cycle: repoweb now https://github.com/Cacti/plugin_cycle/blob/develop/../cycle.php#L47
```

Since the filename was already coming in with the parent directory, I decided to go up a level to get_location_links() but that also gave me the same filename.  Having seen that, I was about to go off and look at the templating system to see where it pulls things in from, when it suddenly dawned on me that maybe you were getting the filename from our files.  

So I went and checked our cacti.pot file to find:
```
#: ../cycle.php:47
msgid "Graph Display Timespan"
msgstr ""

#: ../cycle.php:58
msgid "Cycle Rotation Refresh Frequency"
msgstr ""
```

This made me realise that we utilise a script in every repo called `/locales/update-pot.sh` and that was using a parent path ../ prefix so that makes EVERY file have that prefix.  Now I will have to go see what happens if we make the script properly go up a level before searching for files to include.

So, not technically a weblate bug, but a corner case that could occur causing people to scratch their heads.

**Comment by nijel** [comment]
You can use %(../file)s to strip first part of the path in the format string, see https://docs.weblate.org/en/latest/admin/projects.html#component-configuration

**Comment by netniV** [comment]
I could have but I'd rather have things correct in the first place 👍 

Thanks as always for pointing me in the right direction.
