### ISSUE TITLE
'Unused base file for new translations' alert if using contact form but have addons using base file

### ISSUE THREAD

**Issue by netniV** [WeblateOrg/weblate#2646]
**Describe the bug**
There is an alert generated if you set the repository to not automatically add files (such as use contact form).  However, if you have populated the new base POT filename, this generates a warning (which I'm sure is something I suggested many moons ago so it's now biting me heh).

![image](https://user-images.githubusercontent.com/9052188/54598404-59fab900-4a30-11e9-9ad9-708828f1c8e8.png)

However, whilst the core isn't using that file now, the addon's such as Generate PO's from POT do, especially when used in conjunction with Consistency.

![image](https://user-images.githubusercontent.com/9052188/54598438-6bdc5c00-4a30-11e9-8ca5-c9b688060343.png)

**Additional context**
Wasn't sure how I could manually suppress this alert from reappearing.

**Comment by nijel** [comment]
The language consistency would not currently work without having enabled adding new translations in Weblate, so this boils down to same question as https://github.com/WeblateOrg/weblate/issues/2648.

**Comment by netniV** [comment]
Ah, now that explains something else I was going to ask.  I set it up that way thinking that it would work but it doesn't.  I wanted to prevent other users adding new languages but have them ask for it (which uses the contact form and works).  But if the consistency is blocked because you can't automatically add languages (should be an option of consistency?) that goes out the window.

We don't really want users just randomly adding languages at this point so is there a better way?

**Comment by nijel** [comment]
Looking at it now, the current behavior doesn't make much sense. It was coming from past when most of formats didn't support adding new translations (now all do) and there was no other way to invoke adding than in the UI (now there is consistency addon and cli). I've changed it in https://github.com/WeblateOrg/weblate/pull/2650 to allow adding when configured even if the users are not allowed to add.

**Comment by netniV** [comment]
Funny thing is I think I originally raised a bug about the base file alert in https://github.com/WeblateOrg/weblate/issues/2285 where we had discussed about it being a warning not a full alert (but it still shows as any alert would)

But I think your update in #2650 will make more sense overall.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
