### ISSUE TITLE
When adding a component, filemask should not prevent adding the repo when it has no files yet

### ISSUE THREAD

**Issue by netniV** [WeblateOrg/weblate#2648]
**Describe the bug**
The filemask feature is quite useful in verifying that the repo has got files that match.  However, this should be a warning not an error especially when you are adding a repo without PO files so that you can use the Consistency/Generate PO plugins to generate the appropriate language files.

**To Reproduce**
1. Create a repo with a POT
2. Create a component in weblate pointing at the repo
3. Set the filemask (eg locales/po/*.po)
4. Try to add, see error

**Expected behavior**
The filemask error should be a warning so that the operate realises there are no matching files.  When a new component is being added that may be by design until the consistency and Generate PO plugins kick in.

**Additional context**
Weblate 3.4 would definitely not allow this or a blank filemask, so I had to create a blank es-ES.po file and commit it.

**Comment by nijel** [comment]
You would not get this error if creating of new translation files is configured for the component. Without that, the setup in Weblate is pretty much useless and that's why it fails.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
