### ISSUE TITLE
Count characters when you are translating a String

### ISSUE THREAD

**Issue by Darkmet98** [WeblateOrg/weblate#2649]
**Is your feature request related to a problem? Please describe.**
When you are translating a file and there's a limit on the line (not the string), you have to count manually the number of characters on the translated string.

**Describe the solution you'd like**
When you are translating a string, show on the bottom or another zone the number of characters on the translated string.

**Comment by comradekingu** [comment]
The even more relevant info would be how many chars there are left, because when it goes negative, that is how many letters and symbols need to be omitted.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
