### ISSUE TITLE
squash-by-language (#2623) is adding wrong info to the commit messages

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#2653]
**Describe the bug**

Git repo with multiple components and squash-by-language (#2102) is adding wrong information to the commit messages.  It looks like it is filling out the right template, but using variables from the wrong language/translator.

**To Reproduce**

In https://hosted.weblate.org/projects/f-droid/f-droid/, see commits for ar, sk, fr, en-US, ca, nl_BE, id, tr, de, it, eo, fa, zu, and zh_CN marked as "Translated using Weblate: Danish (da) by Jesper Hertel".

**Expected behavior**

Each commit message should have content relevant to the language represented in the commit.

**Server configuration and status**

hosted.weblate.org

**Comment by eighthave** [comment]
I saved the current git history here in case it goes away: https://gitlab.com/eighthave/fdroidclient/commits/weblate-issue-2653

**Comment by nijel** [comment]
Looking at the reflog at the server and it was once squashed wrongly - all commits were squashed into one with this commit message. Further (correct per file) squashing lead to spreading this message to all files included in this. I believe this has been addressed by recent changes in the commit handling to make it more robust (1fd6cfeb33f6242106026f9d42d7254d69170d82, ed4fb5001def72d109960a51503e8bacf55f6292, eb7410874a46b318c4baf19c7a0c9ee607fa22c1, b92f6a8e30d6afbf027d71f96bbe1fb52509886d).

**Comment by eighthave** [comment]
ah right, that makes sense.  I'll keep a look out for this going forward.
