### ISSUE TITLE
[Component Discovery] - Claims to create components, but they don't exist

### ISSUE THREAD

**Issue by SBSolera** [WeblateOrg/weblate#2654]
**Describe the bug**
I recently configured the Automatic Component Discovery addon so that it would pull in 8 json files of a specific format.  The regex pulls the 8 files correctly and when I select to confirm adding them if appears fine.
Afterwards, when you look in the project, there aren't any other components.

When I view my weblate log, this is what I see:
```
2019-03-22 15:49:51,995 INFO solera4me-static-content/common: Creating component eligibility
2019-03-22 15:49:52,006 INFO solera4me-static-content/common: Creating component welcomeback
2019-03-22 15:49:52,018 INFO solera4me-static-content/common: Creating component preference
2019-03-22 15:49:52,032 INFO solera4me-static-content/common: Creating component coveredpages
2019-03-22 15:49:52,046 INFO solera4me-static-content/common: Creating component enrollment
2019-03-22 15:49:52,061 INFO solera4me-static-content/common: Creating component assessment
2019-03-22 15:49:52,076 INFO solera4me-static-content/common: Creating component medicarelabresults
2019-03-22 15:49:52,089 INFO solera4me-static-content/common: Creating component classselection
```

**To Reproduce**
1. Go to automatic component discovery
2. Put in regex and other options
3. Save, and confirm the json files which are being brought in

**Expected behavior**
I would expect the project to now have all the components added, but only the original component is there.

**Screenshots**

**Server configuration and status**
Please paste the output of `list_versions` and `check --deploy` commands over
here. Depending on installation these can be executed in different way, please
consult https://docs.weblate.org/en/latest/admin/management.html for more
details.

On Git checkout:

```
* Weblate 3.5.1
 * Python 3.6.7
 * Django 2.1.7
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 3.1.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.4.1
 * python-dateutil 2.8.0
 * lxml 4.3.2
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.2
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2018.3
 * pyuca 1.2
 * PyYAML 3.12
 * Mercurial 4.5.3
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.18.0-1013-azure (x86_64)
```

```
System check identified some issues:

WARNINGS:
?: (security.W021) You have not set the SECURE_HSTS_PRELOAD setting to True. Without this, your site cannot be submitted to the browser preload list.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.5.1/admin/install.html#collecting-errors

System check identified 2 issues (0 silenced).
```

**Additional context**
Do you have any tips on where to look to figure out the problem? From what I can see, there are no errors, but the components don't exist anywhere.

**Comment by nijel** [comment]
The components are created in background (in Celery worker), so it is expected to take some time. If they are still not there, check Celery logs for errors.

**Comment by SBSolera** [comment]
Hi, I have checked the celery logs and found no errors. Also, after waiting the whole weekend I checked and none of the components are showing up.  This is the only thing I could find in celery logs
```
[2019-03-25 18:25:39,689: INFO/MainProcess] Received task: weblate.trans.discovery.create_component[990e0a0e-33af-4d6a-b530-b6dff1ee0e5d]
[2019-03-25 18:25:39,699: INFO/MainProcess] Received task: weblate.trans.discovery.create_component[c3e64699-873e-4f5c-8a7a-31dd6349c066]
[2019-03-25 18:25:39,717: INFO/MainProcess] Received task: weblate.trans.discovery.create_component[46cd5a5f-d4e8-4031-a4b2-8ed06c1673d1]
[2019-03-25 18:25:39,733: INFO/MainProcess] Received task: weblate.trans.discovery.create_component[1bce3db0-4577-435f-8dec-016f2f429bae]
[2019-03-25 18:25:39,748: INFO/MainProcess] Received task: weblate.trans.discovery.create_component[2c563bbe-d2c1-4900-86cc-775a701b3e88]
[2019-03-25 18:25:39,760: INFO/MainProcess] Received task: weblate.trans.discovery.create_component[1e54d485-6920-4ba8-92b6-b1156c1c4760]
[2019-03-25 18:25:39,782: INFO/MainProcess] Received task: weblate.trans.discovery.create_component[3e136d6e-cf6a-45a7-ad45-f576c0c0f28b]
[2019-03-25 18:25:39,795: INFO/MainProcess] Received task: weblate.trans.discovery.create_component[8eedcda0-a386-4952-befc-6d2e8dad993a]
```

Do you have any ideas where the error might be showing in the weblate logs? I can't find any indication why it isn't working

**Comment by SBSolera** [comment]
Here's some additional info that might be helpful:
In my console, the following error shows:
```
Uncaught TypeError: Illegal constructor
    at HTMLDocument.<anonymous> (2e342037c3c1.js:1985)
    at mightThrow (2e342037c3c1.js:229)
    at process (2e342037c3c1.js:231)
```

Also, I now can't even get Celery to run so something must be wrong with the setup. This is the most information I can find from the service logs:
```
● celery.service - Celery Service (Weblate)
   Loaded: loaded (/etc/systemd/system/celery.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-03-25 18:57:09 UTC; 29min ago
  Process: 14490 ExecStop=/bin/sh -c ${CELERY_BIN} multi stopwait ${CELERYD_NODES}    --pidfile=${CELERYD_PID_FILE} (code=exited, status=0/SUCCESS)
  Process: 17383 ExecStart=/bin/sh -c ${CELERY_BIN} multi start ${CELERYD_NODES}    -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE}    --logfile=${CELERYD_LOG_FILE}
  Process: 17382 ExecStartPre=/bin/chown -R weblate /var/log/celery/ (code=exited, status=0/SUCCESS)
  Process: 17381 ExecStartPre=/bin/mkdir -p /var/log/celery (code=exited, status=0/SUCCESS)
  Process: 17374 ExecStartPre=/bin/chown -R weblate /var/run/celery/ (code=exited, status=0/SUCCESS)
  Process: 17367 ExecStartPre=/bin/mkdir -p /var/run/celery (code=exited, status=0/SUCCESS)

Mar 25 18:57:09 SH-WEBLATE sh[17383]: > Starting nodes...
Mar 25 18:57:09 SH-WEBLATE sh[17383]:         > celery@SH-WEBLATE: * Child terminated with exit code 1
Mar 25 18:57:09 SH-WEBLATE sh[17383]: FAILED
Mar 25 18:57:09 SH-WEBLATE sh[17383]:         > search@SH-WEBLATE: * Child terminated with exit code 1
Mar 25 18:57:09 SH-WEBLATE sh[17383]: FAILED
Mar 25 18:57:09 SH-WEBLATE sh[17383]:         > memory@SH-WEBLATE: * Child terminated with exit code 1
Mar 25 18:57:09 SH-WEBLATE sh[17383]: FAILED
Mar 25 18:57:09 SH-WEBLATE systemd[1]: celery.service: Control process exited, code=exited status=1
Mar 25 18:57:09 SH-WEBLATE systemd[1]: celery.service: Failed with result 'exit-code'.
Mar 25 18:57:09 SH-WEBLATE systemd[1]: Failed to start Celery Service (Weblate).
```

**Comment by nijel** [comment]
Check celery logs in `/var/log/celery`....

**Comment by SBSolera** [comment]
I checked all of the celery logs and didn't find anything. The only thing I can find is when I run 
`journalctl -xe`, I get the following stack trace:
```
Mar 27 15:43:45 SH-WEBLATE sh[3796]: Traceback (most recent call last):
Mar 27 15:43:45 SH-WEBLATE sh[3796]:   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
Mar 27 15:43:45 SH-WEBLATE sh[3796]:     "__main__", mod_spec)
Mar 27 15:43:45 SH-WEBLATE sh[3796]:   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
Mar 27 15:43:45 SH-WEBLATE sh[3796]:     exec(code, run_globals)
Mar 27 15:43:45 SH-WEBLATE sh[3796]:   File "/usr/local/lib/python3.6/dist-packages/weblate/celery.py", line 26, in <module>
Mar 27 15:43:45 SH-WEBLATE sh[3796]:     from celery import Celery
Mar 27 15:43:45 SH-WEBLATE sh[3796]:   File "/usr/local/lib/python3.6/dist-packages/weblate/celery.py", line 26, in <module>
Mar 27 15:43:45 SH-WEBLATE sh[3796]:     from celery import Celery
Mar 27 15:43:45 SH-WEBLATE sh[3796]: ImportError: cannot import name 'Celery'
```

Have any idea what could cause this? I'm pretty sure this is the same error we had when we talked a while back... Seems like we thought it was fixed, but once Celery restarted it broke again.

**Comment by nijel** [comment]
Do you have any PYTHONPATH set in Celery settings (`/etc/default/celery-weblate`)? If so, this might be same issue as described in https://github.com/WeblateOrg/weblate/issues/2410, removing PYTHONPATH should fix this.

**Comment by SBSolera** [comment]
No, I don't have that. I found  this issue before and tried to remove it. Do you see any problems with my configuration? Here is my configuration for celery:
```
# Absolute or relative path to the 'celery' command:
CELERY_BIN="/usr/local/bin/celery"

# App instance to use
# comment out this line if you don't use an app
CELERY_APP="weblate"

# Extra command-line arguments to the worker,
# increase concurency if you get weblate.E019
CELERYD_OPTS="--beat:celery --concurrency:celery=4 --queues:celery=celery --prefetch-multiplier:celery=4 --concurrency:search=1 --queues:search=search --prefetch-multiplier:search=2000 --concurrency:memory=1 --queues:memory=memory --prefetch-multiplier:memory=2000"

# Logging configuration
# - %n will be replaced with the first part of the nodename.
# - %I will be replaced with the current child process index
#   and is important when using the prefork pool to avoid race conditions.
CELERYD_PID_FILE="/var/run/celery/weblate-%n.pid"
CELERYD_LOG_FILE="/var/log/celery/weblate-%n%I.log"
CELERYD_LOG_LEVEL="INFO"

# Internal Weblate variable to indicate we're running inside Celery
CELERY_WORKER_RUNNING="1"
```

**Comment by nijel** [comment]
That looks okay. Do you get failure if you run Celery manually? Something like this should work (under weblate user):

```
/usr/local/bin/celery -A weblate worker
```

**Comment by SBSolera** [comment]
Actually , yes that command does work... I think something is wrong with the paths that uwsgi uses or something like that. According to weblate error logs, my python does have the right location to where celery is installed `/usr/local/lib/python3.6/dist-packages`
```
Python Path: ['.', '', ‘/usr/lib/python36.zip’, ‘/usr/lib/python3.6’, ‘/usr/lib/python3.6/lib-dynload’, ‘/usr/local/lib/python3.6/dist-packages’, ‘/usr/lib/python3/dist-packages’, ‘/’] 
```

**Comment by nijel** [comment]
The `'.'` AFAIK should not be there (and it's quite likely causing some problems), the `'/'` at the end looks suspicious as well. The error is coming from starting Celery, it has nothing to do with uwsgi.

**Comment by SBSolera** [comment]
Interesting. Unfortunately, I don't know much about python and how these paths work. I've done a lot of research and cannot figure what it is. Likely a problem caused by clashing versions of Python 2.7 and 3.6.  Would you recommend possibly starting over and using a virtual environment? At this point I feel like starting fresh might be best.  

Really appreciate your help on this one. It is very odd because I can run 
`python`
`import celery`
as the weblate user and it pulls it in correctly.
Something is happening only when I try to start the Celery service that it has problems.

**Comment by nijel** [comment]
The problem is most likely that current directory is in Python search path. I have no clue where it is coming from, but it's certainly not the default setup and can easily cause things to break. You can limit it's impact by adjusting `WorkingDirectory` in systemd service to something else than Python module location.

**Comment by SBSolera** [comment]
Thanks for that idea. I adjusted the working directory to point to something else and all the sudden celery started working.
For some reason, pointing directly to `python3.6/dist-packages/weblate` was causing problems

**Comment by nijel** [comment]
The root cause is having current directory (`.`) in Python search path. It really should not be there as it can lead importing random code from current directory (like in this case where local file was imported instead of Celery module).
