### ISSUE TITLE
Missing icon for two plugin categories

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2655]
https://hosted.weblate.org/addons/trebleshot/strings/

![Skjermbilde på 2019-03-24 08-39-27](https://user-images.githubusercontent.com/13802408/54876453-8d628c80-4e10-11e9-837e-a8bc9b372df9.png)

They are:
Mark new source string as needing edit
Mark new translations as needing edit

**Comment by nijel** [comment]
What browser do you use? All these work fine for me:

![Screenshot_2019-03-24 TrebleShot Strings](https://user-images.githubusercontent.com/212189/54877204-a6bd0600-4e1b-11e9-8e92-44ed4937556b.png)

**Comment by nijel** [comment]
Also does https://fontawesome.com/v4.7.0/icon/search or https://fontawesome.com/v4.7.0/icon/flag work fine in your browser?

**Comment by comradekingu** [comment]
![Skjermbilde på 2019-03-24 18-40-05](https://user-images.githubusercontent.com/13802408/54883256-49997280-4e64-11e9-928e-d965206ba205.png)
![Skjermbilde på 2019-03-24 18-39-42](https://user-images.githubusercontent.com/13802408/54883258-49997280-4e64-11e9-850c-77597f77adfb.png)

**Comment by nijel** [comment]
It probably won't work without javascript, I'm surprised that some do work though...

**Comment by comradekingu** [comment]
Maybe it is UTF-8 support first, and then relies on fetching if that isn't present?

**Comment by nijel** [comment]
Maybe, still more things will be broken in Weblate without javascript...

**Comment by nijel** [comment]
What are you actually blocking? I've tried without javascript and the icons work just fine in that case.
