### ISSUE TITLE
Documentation about custom addons is missing information

### ISSUE THREAD

**Issue by Phontana** [WeblateOrg/weblate#2657]
I want to add a precommit script we had in an older version of Weblate, but we can't get it to work in the newer versions.

I read about custom addons, but I don't understand how custom addons work. The documentation states that you can add a custom addon by adding its classname to `WEBLATE_ADDONS`, but how do I determine what the classname is? Where do I put the code of the actual addon? The documentation doesn't even mention this. By reading the documentation, I get the impression that it should be super simple to add a custom addon, but I can't get it to work. Can anyone point me in the right direction?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
