### ISSUE TITLE
Generate MO files addon not respecting monolingual PO files

### ISSUE THREAD

**Issue by Phontana** [WeblateOrg/weblate#2658]
**Describe the bug**
The 'Generate MO files' addon doesn't generate the correct MO file when using monolingual PO files. The generated file moves the `msgid` from the PO file to `msgctxt` in the MO file, and copies the `msgstr` to `msgid`.

**To Reproduce**
1. Add a component which uses monolingual PO files
2. Add the MO addon
3. Translate some files
4. Commit the changes 
5. Check the generated MO file with a gettext tool, for example `msgunfmt` on the command line. 

**Expected behavior**
The MO file has the same structure as the PO file.

Using weblate 3.5.1

**Comment by Phontana** [comment]
Why is the addon not simply using the `gettext` `msgfmt` command instead of a custom implementation?

**Comment by nijel** [comment]
Because we wanted to avoid external dependency and also for performance reasons. But the original MO generator was written for slightly different use case and doesn't properly handle monolingual files. That should be fixed.

**Comment by nijel** [comment]
While looking into this the another reason to avoid using msgfmt on monolingual files is that it's complaining on things which aren't problem in this case:

```
$ msgfmt /tmp/hello-po-mono-it.po
/tmp/hello-po-mono-it.po:35: 'msgid' and 'msgstr' entries do not both end with '\n'
msgfmt: found 1 fatal error
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
