### ISSUE TITLE
Unable to find mass state changes

### ISSUE THREAD

**Issue by Phontana** [WeblateOrg/weblate#2659]
I can't find the option of mass state changes. Where do I enable this feature?

Using Weblate 3.5.1

**Comment by nijel** [comment]
It's under `Tools` -> `Search and replace`. Maybe having separate menu entry for that would be better...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
