### ISSUE TITLE
Automatic Translation - platformwide

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#2662]
**Is your feature request related to a problem? Please describe.**
Weblate detects same strings inside the components of a project, and propagate the translation automatically one translated.

The same behavior can be done manually, using the auto-translation feature:
https://docs.weblate.org/en/latest/user/translating.html#auto-translation

**Describe the solution you'd like**
I would like to be able to enlarge the scope of this features, on all projects of the Weblate server.

The usecase is as follow: I'm working on Fedora documentation translation, and have one component per page to translate and one project per documentation. Because the content is cut into small pieces, a same source string can have the same content.

**Describe alternatives you've considered**
no idea

**Additional context**
none

thanks a lot for your help

**Comment by nijel** [comment]
There already is [Automatic translation addon](https://docs.weblate.org/en/latest/admin/addons.html#automatic-translation).

**Comment by nijel** [comment]
I think we should have some generic way to define default enabled addons. That would cover automatic translation or any other customization user might want to have on the dedicated instance.
