### ISSUE TITLE
auto-translation: overwrite existing translation

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#2663]
**Is your feature request related to a problem? Please describe.**
Weblate detects same strings inside the components of a project, and propagate the translation automatically one translated.

The same behavior can be done manually, using the auto-translation feature:
https://docs.weblate.org/en/latest/user/translating.html#auto-translation

But this only works if there is no existing translation. When I correct a typo or rephrase, I have to go over all components to have consistency. Which I don't do because of time (there is no hyperlink to go to the other translations).

**Describe the solution you'd like**

Either:

 * at edit: I would like Weblate to ask me if the translation has to overwrite other translations with same source-string
 * in a menu: I would like Weblate to ask list same source strings with different translations and offer to propagate one of the translations

**Describe alternatives you've considered**
no idea

**Additional context**
none

thanks a lot for your help

**Comment by nijel** [comment]
It should go to all components within project if you have translation propagation turned on (what is AFAIK default).

**Comment by Jibec** [comment]
Hello, maybe I misunderstood something, here is an illustration.

Step one, I find a source string existing in three components of the same project.
![Capture d’écran de 2019-04-01 07-56-18](https://user-images.githubusercontent.com/474883/55343326-26e20c00-54ab-11e9-89dc-e3ed374c11d3.png)

Step two, I edit the string.
![Capture d’écran de 2019-04-01 07-56-27](https://user-images.githubusercontent.com/474883/55343345-2cd7ed00-54ab-11e9-8090-e5c367763564.png)

Step three, I go to one of the other source string and see the translation was not propagated.
![Capture d’écran de 2019-04-01 07-57-49](https://user-images.githubusercontent.com/474883/55343358-319ca100-54ab-11e9-9b3b-50510533b5e6.png)

What I expect, when I change the translation in the first component, this translation is propagated to the other component with the same source content.

**Comment by Jibec** [comment]
Note, I did my screenshot using the search feature, but it works the same using internal link.

![Capture d’écran de 2019-04-01 18-29-08](https://user-images.githubusercontent.com/474883/55343804-25651380-54ac-11e9-8348-0db09b276b04.png)

**Comment by nijel** [comment]
The problem is that strings have different context, you can see that in your first screenshot (if I correctly matched the French string).
