### ISSUE TITLE
translation-memory : allow queries

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#2664]
**Is your feature request related to a problem? Please describe.**
We have a translation memory, but we can't use it to search for existing translation of a string.

**Describe the solution you'd like**
As a translator, I would like to search for existing translation of a string and get result sorted by similarity, to be more efficient and consistent in my work.

As a translator, I would like Weblate to automatically search for similar string in translation-memory and display it edition screen to help consistency and save time.

As a translator, I would like Weblate to apply a colored diff when displaying result of translation-memory to make the difference finding easier.

**Describe alternatives you've considered**
No idea

**Additional context**
When I translate in Zanata, I have this translation memory on the
bottom-left of the screen:
https://screenshots.firefox.com/22gCf2khbuD8oGxx/fedora.zanata.org
This screenshot show the search of "deprecated".

I can use the same form to search another string. The usecase is as follow: sometimes the string you search don't have any meaningful result and you may search for the specific word that bothers you or that requires a special level of consistency.

thanks a lot for your help

**Comment by nijel** [comment]
Attaching screenshot locally as it will expire on the original location:

![Screenshot_2019-03-27 Pykickstart (rhel7-branch) to French - Zanata Web Translation](https://user-images.githubusercontent.com/212189/55613950-35bb0e00-578c-11e9-9f69-e83c69d3a93b.png)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
