### ISSUE TITLE
Editing metadata strings directly puts source diff field atop all others in Zen

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2665]
Edited https://hosted.weblate.org/zen/f-droid/f-droid-metadata/nb_NO/?type=todo directly
Expected to see diff source string at the bottom, next to the input field and the source string. Instead it is at the very top of each string listing.

**Comment by nijel** [comment]
The diff is shown above the source string, same as in normal editor.

**Comment by comradekingu** [comment]
@nijel In the regular editor, yes. In the Zen editor it is different.

**Comment by comradekingu** [comment]
![Skjermbilde på 29-03-2019 15-50-31](https://user-images.githubusercontent.com/13802408/55241417-4b37b180-523b-11e9-8464-bbccd01a0cb4.png)

**Comment by nijel** [comment]
Ah, I didn't look into secondary languages, thanks for clarification.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
