### ISSUE TITLE
Integration of the Microsoft Terminology Service API 

### ISSUE THREAD

**Issue by WWWesten** [WeblateOrg/weblate#2667]
**Is your feature request related to a problem? Please describe.**
Microsoft Terminology is most distributed software industry-level standard for terminology in world languages. Integration of the Microsoft Terminology Service API to Weblate will make translators works easier, standardize the use of terminology and will achieve a more professional level of translations..

**Describe the solution you'd like**
Integrate Microsoft Terminology Service API (https://www.microsoft.com/en-us/language/Microsoft-Terminology-API?rtc=1) to Automatic translations (Mashine translation service) subsystem on Weblate.

**Describe alternatives you've considered**
No alternatives

**Additional context**
No

**Comment by nijel** [comment]
It's already [supported](https://docs.weblate.org/en/latest/admin/machine.html#microsoft-terminology-service). The "only" problem is that the API is very unreliable and fails frequently.
