### ISSUE TITLE
test_long segfaults on 32bit platform

### ISSUE THREAD

**Issue by scarabeusiv** [WeblateOrg/weblate#2673]
Really don't know what could be the cause here, maybe I should blame the interpreter itself but the log on i586 system looks as follows:

[weblate.txt](https://github.com/WeblateOrg/weblate/files/3037581/weblate.txt)

Also with the release 3.1 at least it seem to have been working (no test crash).

**Comment by nijel** [comment]
That is invoking [jellyfish](https://pypi.org/project/jellyfish/) library, so it might be issue there. What it invokes in the end is:

```
from jellyfish import damerau_levenshtein_distance
print(damerau_levenshtein_distance('a' * 200000, 'b' * 200000)
```

I don't have 32bit system to test this though...

**Comment by scarabeusiv** [comment]
```python
abuild@bugaboo:~> python3
Python 3.7.2 (default, Dec 30 2018, 16:18:15) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from jellyfish import damerau_levenshtein_distance
>>> print(damerau_levenshtein_distance('a' * 200000, 'b' * 200000))
Segmentation fault (core dumped)
```

Also if I use the C extension instead it reports memory error:
```python
>>> from jellyfish.cjellyfish import damerau_levenshtein_distance
>>> print(damerau_levenshtein_distance('a' * 200000, 'b' * 200000))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError
```

You can use build.opensuse.org to generate the arch containers for you still as you have the acount:

```bash
osc co M17N:l10n.opensuse.org/weblate
cd M17N:l10n.opensuse.org/weblate
osc build i586
osc chroot i586
```

If you set up qemu it will happily oblige even with arms/powers/s390 chroots.

**Comment by nijel** [comment]
I've reported it on jellyfish, as that's where it needs to be addressed: https://github.com/jamesturk/jellyfish/issues/120
