### ISSUE TITLE
Same Plurals 

### ISSUE THREAD

**Issue by ebraminio** [WeblateOrg/weblate#2680]
**Describe the bug**
There is a check in the translator that says "Some checks have failed on your translation: Same plurals", this is actually not true in Persian, in Persian it is possible that "%d file" and "%d files" be translated in the same way, many Iranian languages are like that also, I guess you have to put a list of languages excepted for this check.

**To Reproduce**
1. Go to https://hosted.weblate.org/translate/trebleshot/plurals/fa/?checksum=cac54de94c02f7f
2. Use "%d فایل" on both and click on save
3. See the error

**Expected behavior**
Except the Persian

**Screenshots**
![image](https://user-images.githubusercontent.com/833473/55837876-de27f400-5b37-11e9-945b-19a125d3f6a7.png)

The code is [here](https://github.com/WeblateOrg/weblate/blob/3d3122b3a93de05eec5395f975a457845d84cfc9/weblate/checks/consistency.py#L62).
I like to contribute a patch to this but don't know how to wire the language value to the place.

**Comment by nijel** [comment]
You can always ignore the check for particular string. It still might be good idea to show it to allow translator consider if this is really correct in this case.

**Comment by ebraminio** [comment]
> You can always ignore the check for particular string

I can't see how, it doesn't let me save.

> It still might be good idea to show it to allow translator consider if this is really correct in this case.

Not this case but this language and Kurdish/Sorani as I ased as the check has language assumption.

**Comment by nijel** [comment]
It is already saved. You can ignore the check in the listing on the sidebar (I know the UX of this is poor, see https://github.com/WeblateOrg/weblate/issues/894).

**Comment by ebraminio** [comment]
> It is already saved.

> It still might be good idea to show it to allow translator consider if this is really correct in this case.

Ok, now it makes more sense, thanks. I believe excepting Persian (fa) from the check or giving an informational notice instead warning will be great here but feel free to close that isn't that feasible. Thanks

**Comment by nijel** [comment]
I've improved the error message in bc22ecc71d.
