### ISSUE TITLE
something adding ignore flags to Android Strings

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#2681]
**Describe the bug**
A translation like this one has an invalid trailing space that the source string does not have:
https://hosted.weblate.org/translate/f-droid/f-droid/pt_BR/?checksum=a56442d9b3d00027

Weblate does not flag the issue because a bunch of flags have been added:  ignore-end-space, ignore-end-newline, ignore-begin-newline, ignore-begin-space.  I cannot find where these were added, so I'm assuming they are automatically added based on the Android Resource Strings file format.

**To Reproduce**

Add an Android Strings component and see all the flags on all the strings.

**Expected behavior**

All of those checks are valid so none of the ignore flags should be set.

**Comment by nijel** [comment]
AFAIR it was added because the format ignores leading and trailing whitespace.

**Comment by nijel** [comment]
See #358 and commits f1136dc2f81 190c1b509c2.

**Comment by eighthave** [comment]
Unfortunately it is more complicated than that.  I'll use the case I just saw where the translator added a trailing space to the translation.  For Android _strings.xml_ without the Android string quoting, the leading/trailing whitespace will be ignored:

```xml
<string name="hide_all_notifications">Ocultar todas notificações </string>
```

But if Android string quoting is used, then the leading/trailing whitespace will not be ignored, e.g.:

```xml
<string name="hide_all_notifications">"Ocultar todas notificações "</string>
```

The source string does not have any leading/trailing whitespace:

```xml
<string name="hide_all_notifications">Hide all notifications</string>
```

When the translator added a trailing whitespace, Weblate added the Android string quoting to preserve it, e.g.:

```xml
<string name="hide_all_notifications">"Ocultar todas notificações "</string>
```
 So if Weblate is going to add that quoting to preserve the whitespace, it should not disable the whitespace checks.

**Comment by eighthave** [comment]
I setup a [test project](https://gitlab.com/eighthave/weblate-android-tests) for determining the exact behavior.  Here are some source strings:

```xml
<resources>
    <string name="app_name">Weblate Android Tests</string>
    <string name="trailing_space">trailing space </string>
    <string name="leading_space"> leading space</string>
    <string name="leading_trailing_spaces">  leading trailing spaces  </string>
    <string name="quoted_trailing_space">"quoted trailing space "</string>
    <string name="quoted_leading_space">" quoted leading space"</string>
    <string name="quoted_leading_trailing_spaces">"  quoted leading trailing spaces  "</string>
    <string name="trailing_newline">trailing newline
    </string>
    <string name="leading_newline">
        leading newline</string>
    <string name="leading_trailing_newlines">
        leading trailing newlines
    </string>
    <string name="quoted_trailing_newline">"quoted trailing newline
"</string>
    <string name="quoted_leading_newline">"
quoted leading newline"</string>
    <string name="quoted_leading_trailing_newlines">"
quoted leading trailing newlines
"</string>
</resources>
```

And Android seems them like this:

```
leading_space:                   '''leading space'''
trailing_space:                  '''trailing space'''
leading_trailing_spaces:         '''leading trailing spaces'''
quoted_leading_space:            ''' quoted leading space'''
quoted_trailing_space:           '''quoted trailing space '''
quoted_leading_trailing_spaces:  ''' quoted leading trailing spaces '''
leading_newline:                 '''leading newline'''
trailing_newline:                '''trailing newline'''
leading_trailing_newlines:       '''leading trailing newlines'''
quoted_leading_newline:          ''' quoted leading newline'''
quoted_trailing_newline:         '''quoted trailing newline '''
quoted_leading_trailing_newlines:''' quoted leading trailing newlines '''
```

**Comment by nijel** [comment]
It's possible that whitespace handling was broken in translate-toolkit back then and this was more a workaround. Needs further investigation, but probably it's good idea to remove those flags.

**Comment by nijel** [comment]
Okay, it's no longer necessary in Weblate since https://github.com/translate/translate/pull/3637 was merged in the translate-toolkit.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
