### ISSUE TITLE
I keep receiving emails "No such branch master" 

### ISSUE THREAD

**Issue by z31fbras** [WeblateOrg/weblate#2684]
**Describe the bug**
Hi everyone,

I've installed my own version of Weblate.
Everything was working fine but I've been receiving mails for a few days.
Here are the mail first lines
```
Internal Server Error: /projects/exchange/nexchange-app/

RepositoryException at /projects/exchange/nexchange-app/
fatal: no such branch: 'master' (128)
```

My weblate container logs are showing over and over 
```
10/04/2019 15:24:512019-04-10 13:24:51,564 INFO spawned: 'celery-beat' with pid 5839
10/04/2019 15:24:522019-04-10 13:24:52,564 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
10/04/2019 15:24:53!strcmp(locale, "C"):Error:Assert failed:in file baseapi.cpp, line 209
10/04/2019 15:24:532019-04-10 13:24:53,800 INFO exited: celery-beat (terminated by SIGSEGV; not expected)
```

I've also received this kind of emails: 
```
[Errno 2] No such file or directory: '/app/data/vcs/exchange/admin/app/i18n/en.json'
```

**To Reproduce**
1. Install a 3.5.1 version of Weblate
2. Configure your repo
3. Wait a few days
4. Try to open a component

Thanks a lot for your help

**Comment by nijel** [comment]
It seems that the vcs directory has been removed. Not sure how to track down what has actually removed it.

The segfault looks like https://github.com/WeblateOrg/weblate/issues/2581, but that was supposed to be already addressed...
