### ISSUE TITLE
ModuleNotFoundError: No module named 'weblate.settings'

### ISSUE THREAD

**Issue by massivetim** [WeblateOrg/weblate#2685]
Hi,

I followed the installation guide on an Ubuntu server. I renamed the settings_example.py to settings.py, next step is to call weblate migrate. After that I get the "ImportError: cannot import name 'settings_example'" error. When I rename the file back to settings_example.py I get the "ModuleNotFoundError: No module named 'weblate.settings'" error.

Is this a bug or am I missing something?

Thanks
Tim

**Comment by nijel** [comment]
Don't rename the file, just copy it, that should work fine.
