### ISSUE TITLE
Disabling fuzzy matches possible (gettext) ?

### ISSUE THREAD

**Issue by ReneBoehm** [WeblateOrg/weblate#2690]
Is it possible to disable fuzzy matching when using gettext (with a gitlab hook) ? It's confusing our people ;)

**Comment by nijel** [comment]
Do you mean in the msgmerge addon? It's currently not possible, but it can be easily added.

**Comment by ReneBoehm** [comment]
> 
> 
> Do you mean in the msgmerge addon? It's currently not possible, but it can be easily added.

Yes, I meant that addon. It would be create to add a config option for this.

**Comment by nijel** [comment]
This should be really easy to implement:

You need to create form with the configuration, it can quite simple, similarly like this one:

https://github.com/WeblateOrg/weblate/blob/618830d0a346b409344a8ba9d5163bf7ac4ffd72/weblate/addons/forms.py#L123-L133

And then use it in the msgmerge addon:

Link the form to the addon, like here:

https://github.com/WeblateOrg/weblate/blob/618830d0a346b409344a8ba9d5163bf7ac4ffd72/weblate/addons/gettext.py#L224

And use the configuration (eg. `self.instance.configuration.get('no_fuzzy_matching', False)`) in the addon:

https://github.com/WeblateOrg/weblate/blob/618830d0a346b409344a8ba9d5163bf7ac4ffd72/weblate/addons/gettext.py#L191-L214

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
