### ISSUE TITLE
Simplify addition of libre software projects

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2695]
Clicking the "+" on Hosted Weblate lands the user on https://hosted.weblate.org/create/billing/?upgrade=1 which says nothing about gratis hosting for libre software projects.

From the general Weblate Website, one can get to:
https://hosted.weblate.org/hosting/ In the very least that could be linked to from clicking the +

Would be nicer to have an option for automation, maybe with a silent OK to click for the site admin, and then ask in a nice way for donations once up and running?

**Comment by nijel** [comment]
Duplicate of #2174
