### ISSUE TITLE
Import strings from Transifex with user attribution.

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2698]
I imagine this would require having a Transifex user, as strings can't be seen otherwise, or hooking into the API from the admin account of each respective project.
In any event, it is important for quality.
Issues filed in Transifex could be added as comments too, but that isn't as crucial.

**Comment by comradekingu** [comment]
The PO/POT format doesn't have this. Unless every string is done by the same person, or every import just has one new added contributor. However, a file additional to it could be generated, containing this information. That would greatly increase the interoperability and/or federation between translation platforms. Also it retains the crucial component of authorship for posterity and continued work.

Going with the idea of trust only being functional at the translator level, it is then possible to tier the review process for each individual. Amassing this into visible statistics for each string lets unseen translations appear different. #2699

**Comment by comradekingu** [comment]
If hooking into the Transifex API, it would maybe be possible to freeze translations there, and pick things out one PO-file per translator, as that effectively holds attribution.

**Comment by comradekingu** [comment]
Browsing around I stumbled upon http://okapiframework.org/wiki/index.php/Transifex_Filter

**Comment by comradekingu** [comment]
I think Transifex allows downloading translations as TMX files, could someone download one and see if translator/reviewer details are in there?

**Comment by nijel** [comment]
I don't think this would belong in Weblate. Such migration would be one-time action requiring Transifex credentials and that is easier to perform outside Weblate utilizing the API. For example, there is https://github.com/WeblateOrg/wlc/issues/10 to integrate something like this into wlc.
