### ISSUE TITLE
User changes source string and every(?) translation, possible bug

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2702]
https://hosted.weblate.org/translate/androbd/strings/en/?checksum=94db16a324c41c73#history

Can be seen here: https://hosted.weblate.org/changes/?page=10&limit=20&user=Umeaboy

**Comment by nijel** [comment]
User changed English string and it triggered "Source string changed" on all translation, that's expected. I've just reverted these two edits.

**Comment by comradekingu** [comment]
But then the translations should be blanked?

**Comment by nijel** [comment]
They were flagged as needing editing.
