### ISSUE TITLE
Missing trans/alert/addonscripterror.html template

### ISSUE THREAD

**Issue by UncleSamSwiss** [WeblateOrg/weblate#2703]
**Describe the bug**
When a script add-on fails, instead of the actual error, I get a django error because the following template is missing: ```trans/alert/addonscripterror.html```

**To Reproduce**
1. Create an add-on which executes a pre-commit script
2. Make something wrong (not sure yet why the script or the add-on is failing)
3. Commit a translation

**Expected behavior**
The error of the add-on should be shown and not an error that the error template is missing.

**Screenshots**
![image](https://user-images.githubusercontent.com/7595126/56515735-e40ad580-6538-11e9-8679-ba88216b820f.png)

**Server configuration and status**
```
$ docker-compose exec weblate weblate list_versions
 * Weblate 3.6
 * Python 3.7.3rc1
 * Django 2.2
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.1.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.3.1
 * translation-finder 1.2
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.20.1
 * Pillow 5.4.1
 * python-dateutil 2.8.0
 * lxml 4.3.2
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.2
 * user-agents 2.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2019.1
 * pyuca 1.2
 * PyYAML 3.13
 * tesserocr 2.4.0
 * Mercurial 4.8.2
 * git-svn 2.20.1
 * hub 2.2.9
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.14.111-boot2docker (x86_64)
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
