### ISSUE TITLE
Use Add-Ons when creating a component

### ISSUE THREAD

**Issue by UncleSamSwiss** [WeblateOrg/weblate#2705]
**Is your feature request related to a problem? Please describe.**
We need to convert some JSON files in the repository before they can be used by Weblate.
This conversion is done by a Weblate add-on (post-update script) and generates new JSON files (one per language).
When we add a new translation component (which will happen quite a few times in the future), right now we have to manually run some commands to generate those files, then add and commit it with Git (see below for details).

**Describe the solution you'd like**
If we could choose to enable some add-ons while creating a new translation component using "Add new translation component", we could simply add those translation components as the post-update add-on (which runs a script) would automatically add the required files.

If the files are missing, we have no way to create the component (there will always be an error telling us the translation files are missing). And thus we never get a chance to enable our add-on.

We can't add those files manually to the remote repository as we are using GitHub with pull-requests (the remote repositories are not from us).

Suggested sequence:
1. Click on "Add new translation component"
2. Enter all the required information
3. Expand the new "Add-ons" configuration section or click on "Advanced" button (to be created)
4. Choose our two add-ons (post-update, pre-commit)
5. Click "Continue"
6. Choose the i18n/translation-*.json files
7. Continue as usual (filling out the missing settings on the next page)

**Describe alternatives you've considered**
As mentioned above, we do the following right now:
1. Click on "Add new translation component"
2. Enter all the required information
2. Click "Continue"
3. Open a shell on the server
4. In the shell ```cd /app/data/vcs/<project>/<new-component>```
5. Execute our script which will generate the i18n/translation-*.json files
6. ```git add . && git commit -m "Initial translation"```
7. In the browser reload (F5) the "Create component" page (so it shows us the option to choose the i18n/translation-*.json files)
8. Continue as usual (filling out the missing settings on the next page)

**Comment by nijel** [comment]
Maybe you can use [Component discovery addon](https://docs.weblate.org/en/latest/admin/addons.html#component-discovery) for this?

**Comment by UncleSamSwiss** [comment]
From what I understand, the component discovery addon only works with one repository. We will have a lot of different GitHub repositories (each with exactly one adapter to our application).

The problem we are facing is that the files to be translated are not compatible with Weblate, as all translations are stored in one file. Here is an example:
https://github.com/UncleSamSwiss/ioBroker.loxone/blob/master/admin/words.js

We have a [script](https://github.com/UncleSamSwiss/ioblate/blob/master/index.js) that:
1. converts such a ```words.js``` file into one JSON file for each language on ```EVENT_POST_UPDATE```
2. converts the language specific JSON files back to the ```words.js``` on ```EVENT_PRE_COMMIT```

This script works fine as soon as we have set up the repository as mentioned above; but setting up the repository in such a way is a lot of work when you look at the list of 265 adapters we would like to integrate:
https://github.com/ioBroker/ioBroker.repositories/blob/master/sources-dist.json

**Comment by nijel** [comment]
Maybe stupid question, but I have to ask: Can't you have the translations in pure json? That would remove need for all that complex logic.

**Comment by UncleSamSwiss** [comment]
That's not a stupid question at all. Yes, that would be favorable, but you can imagine that telling about 50 open source developers to modify all their code for 265 projects would be quite difficult...

**Comment by nijel** [comment]
The alternative approach might be to write simple format doing transform on loading/saving instead of storing the files on the disk, for example see https://github.com/WeblateOrg/weblate/issues/2689.
