### ISSUE TITLE
Can not see administrated projects in settings

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2708]
1 Go to Settings
2 Go to Notifications (I think this is where it used to be)
! No administrated projects, all-tough I can still navigate to the respective projects and administrate them.
None of the projects are created by me.
As of Weblate 3.7, might be a Hosted Weblate bug.

**Comment by nijel** [comment]
Yes, it's no longer listed there as it was not that useful and taking quite a lot of space. It might make sense to put this list somewhere though.

**Comment by comradekingu** [comment]
Could colourcode the general list that is on there?
I like the idea of just an "A" before the project.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
