### ISSUE TITLE
CLI command to rebuild vcs folder

### ISSUE THREAD

**Issue by btkostner** [WeblateOrg/weblate#2714]
**Is your feature request related to a problem? Please describe.**
I moved weblate instances but did not keep the `vcs` folder and I can't seem to find a way to recreate it.

**Describe the solution you'd like**
A cli command to resetup the vcs folder.

**Comment by nijel** [comment]
I think `./manage.py updategit --all` could do the trick.

**Comment by btkostner** [comment]
@nijel It seems to make the folders, but does not include any git remotes (so no code).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed and the fix will be part of upcoming 3.6.1 bugfix release.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
