### ISSUE TITLE
Weblate refuses to push to the repository after following conflict resolution procedure

### ISSUE THREAD

**Issue by mareksuscak** [WeblateOrg/weblate#2716]
**Describe the bug**

Weblate refuses to push to the repository after following [the recommended conflict resolution procedure](https://docs.weblate.org/en/latest/faq.html#how-to-fix-merge-conflicts-in-translations)

**To Reproduce**
1. Simulate a merge conflict.
2. Follow the conflict resolution procedure described in [the FAQ section](https://docs.weblate.org/en/latest/faq.html#how-to-fix-merge-conflicts-in-translations).
3. Translate more strings.
4. Pull first (yes, I have done that, also tried Reset and Rebase)
4. Try to push them.

**Expected behavior**
Weblate should push the changes to the remote repository.

**Screenshots**

![image](https://user-images.githubusercontent.com/613647/56804957-c8991680-6827-11e9-86f5-a9edd2c3575c.png)

**Server configuration and status**

We use an official docker image `weblate/weblate:3.6-1`.

**Comment by nijel** [comment]
Do pull and push URLs match in your component configuration? It looks like Weblate is unable to fetch new upstream changes.

**Comment by mareksuscak** [comment]
![image](https://user-images.githubusercontent.com/613647/56805259-c08da680-6828-11e9-83b1-290c9a19a950.png)

Damn it. You're right. 🙈Let's pretend this did not happen. Thanks for helping me out!
