### ISSUE TITLE
Import names of languages directly from ICU?

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#2717]
**Is your feature request related to a problem? Please describe.**
Weblate maintains its own translations of language names. Some of the translations appear contain errors or are incomplete.

**Describe the solution you'd like**
It might make more sense to import the translations of language names directly from an authoritative source such as ICU, unless there's a good reason to maintain Weblate-specific translations.

**Describe alternatives you've considered**
The translations can be fixed manually too, of course, if someone takes the time.

**Additional context**

**Comment by nijel** [comment]
The language translations are currently based on CLDR, but it doesn't contain translations for many languages. AFAIK UCI does just take the language data from CLDR, so that should not be different. But maybe there is something broken, what exactly is missing or wrong?

**Comment by tjhietala** [comment]
Sorry, I mixed up ICU and CLDR. At least the Finnish translations of language names in Weblate do not in some cases match what's found in the latest CLDR.

**Comment by tjhietala** [comment]
For example, [here](https://hosted.weblate.org/translate/weblate/languages/fi/?checksum=&offset=&q=norwegian&search=ftx&source=on&type=all&ignored=False&date=&only_user=&exclude_user=) nb_NO is translated as "kirjanorja" whereas in CLDR it's (IMO more correctly) "norjan bokmål"

**Comment by nijel** [comment]
Okay, that is quite old translation from time before we used CLDR as base see f2f3cbf27b8. Existing translations were not replaced later and I still don't think that would be a good idea.

**Comment by nijel** [comment]
But thanks for bringing this to my attention, it turns out that importing names from CLDR is broken for some time, so new languages didn't get those. I've fixed that in a06f9fbf21b5c8a33a15afb89b293a3576fde7dd and updated locales in b3d7724b608a3797203d55a7b0d70d645c5d1896.

**Comment by tjhietala** [comment]
FWIW, I see no reason not to do at least a one-time re-import of Finnish language name translations from CLDR as CLDR seems to get the names (at least generally) right, while the translations currently in Weblate, in some cases, do not. (Also, names of languages should not normally be capitalised in Finnish, which CLDR gets right.)

**Comment by nijel** [comment]
Okay, I will try to look into that. However the language names should be capitalized in Weblate because those are used as labels.

**Comment by nijel** [comment]
@tjhietala  I finally got to this, can you please review https://github.com/WeblateOrg/weblate/pull/2770 if the changes make sense to you?

**Comment by tjhietala** [comment]
Sorry, I don't know French, my observations were about the Finnish translations.

**Comment by nijel** [comment]
My bad, I've messed this up, sorry... For Finnish it's here: https://github.com/WeblateOrg/weblate/pull/2774

**Comment by tjhietala** [comment]
#2774 looks good to me, thumbs up for merging!
