### ISSUE TITLE
Allowing translate same language (abbreviation like RMS)

### ISSUE THREAD

**Issue by ccppoo** [WeblateOrg/weblate#2719]
**Is your feature request related to a problem? Please describe.**
It's not about problems of feature, but while translating there are words that I can't translate more about it like this
![image](https://user-images.githubusercontent.com/46418312/56911775-c1546000-6ae8-11e9-89a1-90ad73067a42.png)
It's 19 line of Debian Handbook/01_the-debian-project and there's only RMS which is initial of Richard Stallman and there's nothing to say more about because it tells what's RMS means at line 20,21 so while adding something else than only "RMS" will make redundancy of information and it forces to add something not to get RED(needs corrections)

Also for abbreviation of technical words undergoes the same problem.

**Describe the solution you'd like**
For translating a single abbreviation like FED or FBI, please don't give RED(need corrections)
Allowing one word translating like this case.

**Describe alternatives you've considered**
Example I attached above, as you could see I added what's RMS previously with "( ... )". But this makes really awkward to read in translated version.

**Additional context**
Adding something else not to get RED stuff makes me to read whats in front(not saying it's not necessary), and it's really a time of waste thinking of what to add as naturally as possible

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by ccppoo** [comment]
thanks for fast reply :)
