### ISSUE TITLE
weblate loadpo is not executed properly

### ISSUE THREAD

**Issue by Flohack74** [WeblateOrg/weblate#2723]
**Describe the bug**
After calling weblate loadpo on the cmdline nothing happens. We updated in 2 or 3 steps from Weblate 3.1 to 3.6 - With 3.1 this definitely worked without issues. Sometimes its needed, since also msgmerge extension did/does not always work.

**To Reproduce**
1. just execute `weblate loadpo <project>/<component>

**Expected behavior**
Either output that task has been queued or interactive finish message

**Server configuration and status**
``` * Weblate 3.6
 * Python 3.5.2
 * Django 2.1.5
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.1.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * translation-finder 1.4
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow 5.4.1
 * python-dateutil 2.7.5
 * lxml 4.3.0
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.1
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2018.9
 * pyuca 1.2
 * PyYAML 3.13
 * hub 2.2.9
 * Database backends: django.db.backends.mysql
 * Cache backends: default:MemcachedCache, avatar:FileBasedCache
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.4.0-146-generic (x86_64)

SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E009) The Celery tasks queue is too long, either the worker is not running or is too slow.
        HINT: https://docs.weblate.org/en/weblate-3.6/admin/install.html#celery
?: (weblate.E019) The Celery does not process tasks or is too slow in processing them.
        HINT: https://docs.weblate.org/en/weblate-3.6/admin/install.html#celery

WARNINGS:
?: (security.W021) You have not set the SECURE_HSTS_PRELOAD setting to True. Without this, your site cannot be submitted to the browser preload list.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.6/admin/install.html#collecting-errors
```

**Additional context**
Note that despite the Celery errors everything seems to be working, that means, I do get tasks in all queues (periodic and interactive), I can see workers processing them etc.

the output of queue lengths and celery worker status seems innocent.

the only output from the cmdline is:
```2019-05-02 22:22:55,216 DEBUG hub: exec hub --version [retcode=0]
2019-05-02 22:22:55,227 DEBUG git: exec git review --version [retcode=1]
2019-05-02 22:22:55,233 DEBUG git: exec git svn --version [retcode=1]
2019-05-02 22:22:55,237 DEBUG git: exec git --version [retcode=0]
```

**Comment by nijel** [comment]
Your Celery setup seems to broken, the loadpo queues task to it.

You can silent the debug logs by using following logging configuration snippet from the example config:

https://github.com/WeblateOrg/weblate/blob/9f38cbece4a0bf285b25c324693a632f86310236/weblate/settings_example.py#L506-L510

**Comment by Flohack74** [comment]
Hmm actually I would like to have more debug output, like when Weblate is queueing the job. Can I raise that level somewhere? I moved from the one-queue-setup from Weblate 3.2 to 3.4 and then 3.6 to not have too many changes at once :) - but I am pretty sure I applied the celery config files as they should be. I have all 3 queues memory, weblate, search showing as empty.

**Comment by Flohack74** [comment]
For example, if I stop Celery and then trigger an action in Weblate, I might get the following queue in Redis:
```
127.0.0.1:6379> llen search
(integer) 116
127.0.0.1:6379> lindex search 0
"{\"content-encoding\": \"utf-8\", \"content-type\": \"application/json\", \"properties\": {\"correlation_id\": \"78f80322-cb98-471e-8bda-615bbb902873\", \"reply_to\"
```
Also the celery queue gets filled:
```
127.0.0.1:6379> llen celery
(integer) 27091
(weblate3) root@t:/opt/weblate3# weblate loadpo ubports/indicator-datetime
(weblate3) root@t:/opt/weblate3# redis-cli
127.0.0.1:6379> llen celery
(integer) 27092
```
So _after_ my loadpo command the job ends up in the queue, but then it seems to get lost...
Restarting celery now and thats the result:
```
127.0.0.1:6379> llen celery
(integer) 27088
```
And then again after some minutes:
```
127.0.0.1:6379> llen celery
(integer) 27080
```
Why is it taking jobs so slowly? Is there anything I can check on celery side?

**Comment by nijel** [comment]
Check celery logs, maybe there are some errors?

**Comment by Flohack74** [comment]
Ok I purged the whole bunch of stuck jobs, and now it seems to start working. Notable behaviour: celery queue fetched 8 stale tasks every 5 minutes or so. Guess it would take some time for 26k tasks to finish. Also it seems to not know what to do with them, since no action was triggered. But it seems ok now.
