### ISSUE TITLE
App store metadata files missing

### ISSUE THREAD

**Issue by Phontana** [WeblateOrg/weblate#2725]
**Describe the bug**
I added an App Store metadata files component to a project, and it picks up `description.txt` and `keywords.txt` correctly from the metadata folders generated by fastlane. However, those folders contain way more files than those 2 files added by Weblate. See the attached screenshot.

**To Reproduce**
1. Add an App Store metadata files component from an iOS project
2. Check the strings visible in Weblate

**Expected behavior**
All files are picked up by Weblate and added as strings.

**Screenshots**
![missing_files](https://user-images.githubusercontent.com/13638753/57132550-3ac9a800-6da0-11e9-8f69-9918dd730730.png)

**Comment by nijel** [comment]
The original request was to cover limited set of files (see https://github.com/WeblateOrg/weblate/issues/1525). Are really all `*.txt` files supposed to be translatable?

CC @eighthave

**Comment by Phontana** [comment]
@nijel Yes, all these `.txt` files are supposed to be translatable. That's why fastlane puts them in the language folders, and it makes sense since all these values can be different in a different language. For example, the app name can be translated in several languages (the app name can contain a short description as well on the App Store). Marketing URLs can be different for each language to point the user to a localized product page, and so on.

**Comment by eighthave** [comment]
I think it would be relatively safe to assume that _*.txt_ in those folders should be translatable.  Otherwise, you'll need to maintain file name lists for each variant:
* Fastlane Android (_full_description.txt_, _short_description.txt_, _<locale>/changelogs/*.txt_, etc)
* Fastlane iOS (_description.txt_, _subtitle.txt_, _release-notes.txt_, etc)
* Triple-T Android (_full-description.txt_, _short-description.txt_, _, _release-notes/<locale>/*.txt_, etc)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by eighthave** [comment]
Looks like a great fix
