### ISSUE TITLE
Translation error/duplicate

### ISSUE THREAD

**Issue by ppasserini** [WeblateOrg/weblate#2726]
**Describe the bug**

I found 2 strings (Into Application) too much similar, IMO a duplicate:
1) You can receive notifications for watched projects and they are shown on the dashboard by default.
2) You can receive notifications for watched projects and they are shown on dashboard by default.

**To Reproduce**
Just search into the English translation

**Expected behavior**
Either delete one or update the other if the meaning is different

**Comment by nijel** [comment]
Thank you for your spotting, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
