### ISSUE TITLE
use wildcard in Monolingual Base in App Store Metadata format

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#2729]
Now that the App Store Metadata format and squash/rebase addon are working smoothly, I have reached a point I didn't think we'd get to for a long time: considering the [_fdroiddata_](https://gitlab.com/fdroid/fdroiddata/) metadata files as a direct source for Weblate.  That file format is quite closely related to the App Store Metadata file format, the difference is that it can include multiple apps in a single repo:

* _fastlane/android/metadata/[locale]/*_ __vs__ _metadata/[appname]/[locale]*_
* https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots

So if the _Monolingual base language file_ field allowed using a wildcard, then the _fdroiddata_ format would work with the rest of what's there, e.g.:

* _Filemask_: metadata/\*/*
* _Monolingual base language file_: metadata/*/en-US

This might also end up being useful for apps that want to maintain separate sets of files in Fastlane format in the single git repo.  For example, some apps want to have separate descriptions for Google Play vs F-Droid.

**Describe alternatives you've considered**

We currently have a cumbersome sync setup that converts files to XLIFF, manages those in Weblate, then converts back:

https://gitlab.com/fdroid/fdroiddata-localizations

But maybe this is too complicated to be worthwhile...
(this is a Linguine issue)

**Comment by nijel** [comment]
You can already have multiple wildcards in the filemask and all are used as language code, so this would break existing setups (where language code is used multiple times in the path like `help/de/de.po` or `sources/localization/ja/Xenko.Core.Presentation.ja.po`).

I can see two alternatives:

* Use component discovery and have separate component for each app. Looking at the number of apps, that would probably not scale well, but it should work right now.
* Introduce special handler for this to have all the translations in single component.

**Comment by eighthave** [comment]
Using component discovery would be fine by me, if we can setup an
"fdroiddata" project, then each app would be a component.  That seems
annoying for the translators, since most app components would just have
a single string entry called "summary".  But maybe if this worked
smoothly, we'd also handle _title_, _full_description_, _changelogs_,
etc. in the _fdroiddata_ repo.

So I guess for this use case, there would need to be some special wildcard.
