### ISSUE TITLE
Translated yml file has different translations than what I can see in the Weblate UI

### ISSUE THREAD

**Issue by eneaalexandra** [WeblateOrg/weblate#2731]
The translated .yml file shows translations from Google Translate rather than the translations provided by our translators, which are available in Weblate 

**To Reproduce**
1. Upload .yml source file
2. Translate the strings in weblate interface
3. Download the file in original format (.yml)
4. See that translations in the downloaded file are the ones that are recommended by Google Translate rather than the saved translations for the strings. 

**Expected behavior**
Translations provided by human translators should be available in the downloaded file. 

**Screenshots**
Screenshots attached show the different translations for string Explore in the interface and in the translated file. 
<img width="675" alt="Saved translations available in the interface" src="https://user-images.githubusercontent.com/47116314/57390640-85df2300-71c5-11e9-839d-e8f77eda6370.png">
<img width="324" alt="Translation for explore available in the downloaded file" src="https://user-images.githubusercontent.com/47116314/57390652-88da1380-71c5-11e9-85fb-941964a06b52.png">

**Comment by nijel** [comment]
Are there any errors in the Weblate logs?

**Comment by nijel** [comment]
Looking again at the screenshot: It seems you've configured the translation as YAML instead Ruby YAML, that might fix your issue.

**Comment by eneaalexandra** [comment]
I've identified that actually the issue was generated by some manual changes introduced by the dev team some time ago.
