### ISSUE TITLE
Statistics for most frequent comments added.

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2733]
This would be a great way to find the type of people that like questioning and providing feedback.

**Comment by ccppoo** [comment]
I really agree with it.
Unless someone who wants to translate everything by him or herself, there needs to be someone else to cooperate.

Maybe with some sorting methods showing tags like recent added translation project, short(something that could finished fast), nobody engaged, ect. to be promoted.

Can't find anyone working on debian-handbook(KR) lol

**Comment by nijel** [comment]
@ccppoo  Sorry, but I don't really see how your comments is related to the original issue...

If you want to look who is working on certain language and project, it's easy to do so: https://hosted.weblate.org/languages/ko/debian-handbook/#history

@comradekingu You mean something like we do for uploads/translations/suggestions at https://hosted.weblate.org/stats/?

**Comment by comradekingu** [comment]
@nijel yes :)

**Comment by comradekingu** [comment]
Edit: There was a call for per project based statistics too.

Lets say an organizational figure want to reach out to the top translators for any given project. It could be that there are a lot of other translators, that just translate other projects, and have no interest in translating the one project in question.

**Comment by comradekingu** [comment]
![bilde](https://user-images.githubusercontent.com/13802408/57843248-348af100-77ce-11e9-910e-c1cc6d289201.png)
Sorry, that is another matter #2752
I just answered yes here without thinking, took me a while to understand what I meant from reading the headline. Like a top 10 of "top commenters" in pic related. Don't know if source string and translation string comments should be separate categories.
