### ISSUE TITLE
Horizontal Zen has fixed width translations

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2737]
![Skjermbilde på 2019-05-11 19-50-52](https://user-images.githubusercontent.com/13802408/57573338-76124980-7426-11e9-96be-03d41023f65e.png)

I imagined it would be half and half. More than one line in horizontal Zen means more mental line-wraps, and doesn't save space. If anyone like this, or half-and-half with wrap, do tell me what the point of it is.
For truly long strings I will grant looking back and forth spans the actual field of view, but that is imo. a string problem.

Another solution would be to go with horizontal Zen on one-liner strings, and vertical Zen for wrapping ones (given the user resolution present when loaded) in a mode of its own, or make that the current horizontal Zen.

**Comment by nijel** [comment]
Hmm, it was half-half for me when testing, definitely some bug.

I don't think that making some strings horizontal and some vertical will do any good here (though it would be trivial to implement).

**Comment by comradekingu** [comment]
@nijel 
You probably tested single width strings
![Skjermbilde på 2019-05-11 20-28-19](https://user-images.githubusercontent.com/13802408/57573666-6f3a0580-742b-11e9-9093-e5f5699d34b0.png)

**Comment by nijel** [comment]
I had long strings as well, but I also had big display ;-). Now on notebook with small screen I can easily see that it's broken...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
