### ISSUE TITLE
Rename vertical/horizontal Zen

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2738]
The problem is this, 

Is it the alignment of the fields to each-other, as
in the direction of the written text-fields, vertical being the current horizontal as it wraps a lot more? With this logic side-by side (which is now called horizontal) is sometimes vertical, whereas top and bottom (now called vertical) is always horizontal.

or

Is it the line between the respective translation fields?
This seems a bit arbitrary a convention, seeing as wrt. the text that goes in, side-by-side isn't written 90 degrees rotated, but instead always horizontal, regardless of mode, but that could be down to how I see it.

Suggestion:

Side-by-side 

and

Top-
to-
bottom

This is where the fields actually are, and how information flows between them, always.

**Comment by nijel** [comment]
Good point and I like your suggestion.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
