### ISSUE TITLE
Side-by-side Zen should only be half-and-half for the longest possible oneliners

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2739]
![Skjermbilde på 2019-05-11 20-28-19](https://user-images.githubusercontent.com/13802408/57573684-da83d780-742b-11e9-8b86-7ecffb30c0b6.png)

The field of vision isn't infinitely wide, additionally, a modern screen that is plenty wide will easily surpass that of the area in absolute focus.

The extreme case is a one word string, where that word is also short.

Source - Translation

is a lot easier to focus on, compared to

Source---------------------------------------------------------------------------- Translation

This makes a lot of difference for reviewing strings, where I think side-by-side actually works better for some cases.

**Comment by nijel** [comment]
I think the width should be consistent for all strings, changing it between strings make it hard to focus on the right string when the beginning of it moves.

**Comment by comradekingu** [comment]
@nijel Unless sorted by string length. That is a feature in and of itself when it comes to being productive on a mobile screen.

**Comment by nijel** [comment]
I don't think you want to use side by side mode on mobile screen :-).

**Comment by comradekingu** [comment]
Good point, but I would want only small strings, which is where having something to sort them by is good for both desktop, in not skipping around with the translation field, and mobile since one would only want small strings.

**Comment by nijel** [comment]
I really prefer fixed layout here, I've tried aligning by source length and it looks messy.

**Comment by comradekingu** [comment]
Granted, the question is how it works though.
Can you post a screenshot? It could maybe be semi-sorted by length, at 10 possible lengths, and then a divider in between those.

**Comment by comradekingu** [comment]
I'll take functional any day, it could have two side-by sides side by sides if the strings are short enough, and then transition?

The reason it looks untidy might be #2784 and #2766 ?
