### ISSUE TITLE
Clicking placeholder in RTL copies placeholder front to back

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2749]
https://hosted.weblate.org/zen/weblate/master/ar/?type=check%3Apython_format

![Skjermbilde på 2019-05-16 00-05-13](https://user-images.githubusercontent.com/13802408/57812837-7edc8580-776e-11e9-8c89-9d4b947c6931.png)
Possibly related to #1140

**Comment by nijel** [comment]
I *think* it's just a rendering issue and in the end it's correct. But knowledge of RTL is limited.

Maybe somebody else can help? @yarons ?

**Comment by comradekingu** [comment]
It does trigger the Python format error check, hence my involvement. Pretty sure I was able to edit these in the past.

**Comment by nijel** [comment]
It does trigger it because of missing format string in one of plurals. Sometimes gettext is really strict in this and sometimes not, I should check their code when it actually fails in gettext and the check should be adjusted.

**Comment by comradekingu** [comment]
Ah, I keep getting that when i write ~ "one ___" instead of "1 ___"

**Comment by nijel** [comment]
It should be addressed by https://github.com/WeblateOrg/weblate/pull/2753.

**Comment by yarons** [comment]
It's only logical (character order), in practice the app will use it correctly.

In case of doubt just open the resulting translation file in a hex editor and see if there are any special characters in there.

If you see no characters than the gettext/L20n/interpreter/compiler/whatever will probably read it correctly.

In addition to that, adding LRM/RLM to variables might actually break it, It's something like:
%<>s

It's fine that way, just keep it like that, it makes perfect sense in RLE environment.

**Comment by nijel** [comment]
Thanks for clarification! I've meanwhile addressed the issue with format string check.
