### ISSUE TITLE
Links in translation memory results

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2754]
![bilde](https://user-images.githubusercontent.com/13802408/57844820-107cdf00-77d1-11e9-81ba-71f86e609de7.png)

Editing strings directly here would be nice, but a link would do.

For editor with translated string
For editor with source string
To project in question

Launchpad has this, and it is very useful.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
