### ISSUE TITLE
Timeout in get_github_email is 1 second

### ISSUE THREAD

**Issue by dbkr** [WeblateOrg/weblate#2759]
I've just had a lot of errors from our weblate instance where it's timing out whilst reading from the connection in `get_github_email`. The timeout is set to 1 second in https://github.com/WeblateOrg/weblate/blob/master/weblate/accounts/pipeline.py#L59 - is there a reason this is so low? This is for a user logging in with Github auth, so if the request fails then their login fails. It seems like it taking a few tens of seconds to complete would be preferable to the login failing. I'd expect timeouts for this kind of thing to be somewhere between 10 and 30 seconds?

**Comment by nijel** [comment]
It's not limit for the authentication request, it's just an API call to get user emails. One second might be too strict, but it really should no take long, maybe you have some networking issues?

**Comment by dbkr** [comment]
Yep, although it will still throw an exception and fail the authentication if it doesn't make it within the timeout. It shouldn't take long, and probably won't 99% of the time, but GitHub often has its go-slow moments IME. I'd have thought a user would rather wait 10 or 15 seconds than have it fail and have to to back out and try again?

**Comment by nijel** [comment]
It indeed does happen occasionally, on Hosted Weblate there are 12 such errors in last 3 moths.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
