### ISSUE TITLE
Make multiple pages in glossaries more obvious

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#2764]
**Is your feature request related to a problem? Please describe.**
I only recently noticed that glossaries can have multiple pages. The page controls are only on top of the page, where they are easily missed. Most website have them at the bottom or both top and bottom.

**Describe the solution you'd like**
Add page controls to the bottom of the glossary page also.

**Describe alternatives you've considered**
Alternatively, only have a single big page. This would be Ctrl-F friendly.

**Additional context**

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
