### ISSUE TITLE
Translated strings in not translated

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2765]
Clicking https://hosted.weblate.org/zen/f-droid/fdroiddata/nb_NO/?type=nottranslated  in https://hosted.weblate.org/projects/f-droid/fdroiddata/nb_NO/
I get 225 strings, many of which are actually translated…

On new FF: 67

Seems like #1491

**Comment by nijel** [comment]
It seems to fix when I edit the string, but there are more of such strings in the database, so it needs further investigation.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
I've hopefully fixed all broken strings as well now.

**Comment by comradekingu** [comment]
@nijel Works :) Not seeing any translated strings in untranslated.
