### ISSUE TITLE
Condensed Zen

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2766]
What is now
![image](https://user-images.githubusercontent.com/13802408/58148718-21f63900-7c60-11e9-81b3-5c7692d5c1fb.png)
Could be
![image](https://user-images.githubusercontent.com/13802408/58148749-3fc39e00-7c60-11e9-9786-b10624b77da6.png)
By reducing the nothingness, everything is one.

Which means, twice as many strings seen, or space for more languages.

**Comment by ccppoo** [comment]
reducing blank space could look more compressed and feel more full.
But for me, if this design is adopted, 
for the first 30 minutes there would be no problems reading but after that,
it will make hard to read.

@nijel , if you are considering this, please make it as optional

**Comment by comradekingu** [comment]
@ccppoo 
There is a lot of data on how people read from typhography. Essentially this is a book, in the form of a play. Increasing the line hight does nothing, and the context here is not only comparing one language to another, but getting the full effect of seeing multiple strings at once, which together with the new Tetris-mode in Zen makes it a lot more efficient.
Spending more time doing nothing, scrolling, panning, is what ultimately has to be calculated when comparing. Keeping a lot of strings in mind is taxing enough, and then you effectively have to guess what strings come later if they are unseen.

This is just the bare minimum needed to save on the space that goes unused.
What it does is highlight the use of borders, focus-stealing colours, and the inconsistency of listing the translated language differently from the guide languages.

#2767 is an example of doing a lot more, in a minimal fashion, without looking busy.
It actually does more than Zen does now. Hoping this gets solved at both ends.

**Comment by ccppoo** [comment]
@comradekingu 
If there's a feature like highlighting lines what line I'm working like you said, I would love it.
But most of the case, strings for translate are breaked small enough to see in a screen without scrolling.

anyway what I want to say is not a complete 'no', but there are other people who likes not-dense

**Comment by comradekingu** [comment]
@ccppoo 
If I could see every string in a translation I would want that, with all the other languages in tow. The more the merrier.
The blinking cursor is where editing happens. There isn't a huge point in highlighting with colour, because writing or moving with the arrowkeys shifts focus. Also the editing field is always in the same place. Compare it to GitHub, or any non-suite editor. Less noise works.

**Comment by ccppoo** [comment]
@comradekingu 
I checked Pootle, Translate wiki, and Launchpad Translations and I got what you were trying to say.
Weblate is my first translation tool, so I really didn't got the point you said first. sorry!

**Comment by nijel** [comment]
I've changed padding a bit in ba30bcbc5b4d1f13439aa742d404bdeb7de3ca61, but the way you did it looks too much to me.

**Comment by comradekingu** [comment]
I don't remember if I edited it to not be like that in the firstpost, but the language codes are now below each field, which uses a lot of space if there are many:
![Skjermbilde på 2019-05-30 13-33-35](https://user-images.githubusercontent.com/13802408/58630901-1f8b8300-82e1-11e9-9dd7-05681517f3df.png)

**Comment by nijel** [comment]
Good idea to move that to left column, done in 7e8498a9be67662a55347352448f0494227fab0f.

**Comment by comradekingu** [comment]
@nijel Great, that is huge :)
