### ISSUE TITLE
Translation license status

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2769]
https://hosted.weblate.org/accounts/profile/#licenses
There are a lot of ways to write GPLv3+, it would be better to have just one.
What is worse, if a license states "GPLv3", it isn't clear to me if this is GPLv3 only, meaning no, or any later version (+).

It would be great to get this cleared up, and only allow a dropdown list of licenses.
Otherwise it will turn into chaos with dual-licensing, combinations thereof, and the TM.

**Comment by nijel** [comment]
I plan to consolidate licensing information for quite some time, I just never got to it so far...

**Comment by comradekingu** [comment]
I did it for the projects I administrate.

**Comment by nijel** [comment]
Thanks, what we need in the long term is generic solution. Maybe using SPDX for that might be good choice: https://spdx.org/licenses/ and https://github.com/spdx/license-list-data/blob/master/json/licenses.json
