### ISSUE TITLE
Link in fuzzy Zen leads to wrong strin 

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2771]
https://hosted.weblate.org/zen/fluffychat/translations/nb_NO/?type=fuzzy

Clicking any of these for editing opens up another string in the regular editor.
Works in other projects.

Got many tabs open of the same thing.
Clicking Tab also sent me to some other string than the next one.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by comradekingu** [comment]
@nijel Still happens in Metrodroid.
Clicked link saying there were new strings
Translated one
Clicked edit on one string to fix the source
Got a different string

Came from
https://hosted.weblate.org/translate/metrodroid/strings/nb_NO/?type=nottranslated&offset=3 
Onto
https://hosted.weblate.org/zen/metrodroid/strings/nb_NO/?type=nottranslated

It seems the offset is not keeping up.

When pressing F5, the translation I made (for the first of 5 strings) is now in the wrong field.

![image](https://user-images.githubusercontent.com/13802408/58372777-040c2b00-7f23-11e9-845a-2eca56bebfa7.png)

(means system info)

**Comment by nijel** [comment]
That's expected for now, the fix was not yet deployed.

**Comment by nijel** [comment]
Fix is now finally deployed.
