### ISSUE TITLE
Needs editing-box for source strings

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2772]
![image](https://user-images.githubusercontent.com/13802408/58303281-b5aa3f80-7def-11e9-9328-bf13ad110753.png)

Right now I use "needs editing" to (also) mark source strings that need to be improved.
Only because clicking into the source string to mark it there takes longer to do.

**Comment by nijel** [comment]
Related to https://github.com/WeblateOrg/weblate/issues/756
