### ISSUE TITLE
Adding instructions for each projects

### ISSUE THREAD

**Issue by LongHyukLee** [WeblateOrg/weblate#2775]
I think some translations in some projects need some kind of notice board
to tell how the project was worked, something more than History and Activity of that project

I'm not talking about responsibility or director.
 
Huge projects that are worked not by as team,
it's hard to keep the same style how it's going to be translated.
Such as literal style, colloquial style(spoken language), ... etc.

In my case, Korean there are honorific(respect form) and familiar(plain form) speech
(not about hierarchy)

**So** adding "README" just as every repository in git projects would be helpful

![tempsnip](https://user-images.githubusercontent.com/35549913/58365313-69e5bc00-7efd-11e9-9a74-5019d0090acb.png)

I know there's feature that could leave comment for every string, or Glossary
but it's not like a announcement so other translator who works on it later would not notice it

I think this would help for later maintenance(update of script) and keep consistency of translation style

**Comment by nijel** [comment]
There is already project information available, it's just not shown on the language view: https://hosted.weblate.org/projects/debian-handbook/#information

**Comment by LongHyukLee** [comment]
Most of the projects don't have their own domain or guide lines for translation.
What I mean is, there needs some kind of bulletin board where translators could share or announce
what or how works are done.
Debian is just a lucky case that could contact with other contributors

I know this would spend another large amount of data for every projects and language just for few lines of texts.

Really appreciate if you add it

**Comment by nijel** [comment]
Related: https://github.com/WeblateOrg/weblate/issues/2239 (and to some extend https://github.com/WeblateOrg/weblate/issues/2241)

**Comment by LongHyukLee** [comment]
I should have searched previous issues what I tried to said :(
Thank you!

**Comment by comradekingu** [comment]
@LongHyukLee Sometimes proper/causual forms are dealt with by using lang_code@Rude.
What would you put in the announcement tag? If there isn't a lot of back and forth, you could ask the admin to make an announcement, or just use comment field of the first string. Does that cover your problem?

**Comment by nijel** [comment]
For announcements there are whiteboard messages, see https://docs.weblate.org/en/latest/admin/whiteboard.html

**Comment by nijel** [comment]
I think current translator instructions URL should be replaced by markdown field which could be used for both URL and giving more detailed instructions.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
