### ISSUE TITLE
about "things to check",is there a quick way to edit them at one time?

### ISSUE THREAD

**Issue by shinji-ikari** [WeblateOrg/weblate#2776]
**Is your feature request related to a problem? Please describe.**
i have join a project, and it shows thousands of "things to check", they are not wrong, in fact, it's the way it should be, but since it show up like i need check it  and click the "X", it seems i can't find a way to edit ten of it or all of it in one time. 
i have to click the X in "things to check" one by one , each time it need to load for at lest 2 seconds to wait. it does wasting the time...

i had tried zen mode, but it doesn't found anything about "things to check"

**Describe the solution you'd like**
can zen mode solve this problem, by showing the "things to check" in zen mode and edit them at one time?

sorry for my bad english and poor Search ability，if i  miss something about "things to check" or there is already a solution to solve this problem. please point me out.

thanks guys.

**Comment by ccppoo** [comment]
adding screen-shots where you had problems with a link of it would help somebody to understand

**Comment by comradekingu** [comment]
@shinji-ikari 
Your best bet is to go to the regular editor, see what kinds of problems there are, and then open each respective one in the Zen editor.
Checks like "unchanged string" will have to be unclicked manually, which is why many people just leave them.

**Comment by shinji-ikari** [comment]
[http://i.imgur.com/igT7zrV.jpg](url)
sorry for so late to check the issues ,didn't get the mail of notifications, almost forget i had asked this for help. I mean the red one in picture .
[http://i.imgur.com/KEMARL2.jpg](url)
almost all is like this, I have to click the "X"  one by one, is there a way finish  them in one time or by one single click?

**Comment by nijel** [comment]
This is no longer called "Strings to check" since 35343b2891f as the label was indeed confusing.
