### ISSUE TITLE
Wrong string count in engage page and widget

### ISSUE THREAD

**Issue by t2d** [WeblateOrg/weblate#2779]
**Describe the bug**
Engage page and widget counts translations of just one component, not all.

**To Reproduce**
1. Go to https://hosted.weblate.org/engage/userli/
2. It shows:
> The translation project for userli currently contains 17 strings for translation and is being translated into 4 languages. Overall, these translations are 75.0% complete.

These are the statistics of the components `validators` not all components as you can see in [the project dashboard](https://hosted.weblate.org/projects/userli/).

**Expected behavior**
Weblate should summarize all components and show statistics about them.

**Server configuration and status**
hosted.weblate.org with Weblate 3.7-dev

**Additional context**
This affects also the widget. See
* https://hosted.weblate.org/widgets/userli/?lang=&component=messages
* https://hosted.weblate.org/widgets/userli/?lang=&component=validators
* https://hosted.weblate.org/widgets/userli/

Thank you for this great software.

**Comment by nijel** [comment]
The messages component is currently empty because of the bug in YAML file, @orangesunny AFAIK wrote you about that.

**Comment by t2d** [comment]
You are correct. Sorry for not looking more careful. Weblate had read 0 strings from `messages.en.yml`, because of broken markup. How can I trigger a re-read of the fixed file? I already did a rebase. But there are still no strings.

**Comment by nijel** [comment]
The file format was wrongly configured on import, I've just fixed that and the file is properly imported now.
