### ISSUE TITLE
Add no-cache to widgets

### ISSUE THREAD

**Issue by Otiel** [WeblateOrg/weblate#2783]
(_Not sure if I should open this issue in https://github.com/WeblateOrg/weblate instead?_)

Hosted Weblate offers widgets (for [instance](https://hosted.weblate.org/widgets/bandcampdownloader/?component=bandcampdownloader)) to promote a translation project. When adding this widget to a repository README file on GitHub, the image is cached by GitHub and thus never updated. The progress (percentage, number of languages...) displayed on the widget quickly becomes not up-to-date, making the widget irrelevant.

GitHub has [stated](https://github.com/github/markup/issues/224#issuecomment-48532178) that:
>Make sure the image has the `Cache-Control: no-cache` header, and either `Expires`, `Last-Modified` or `Etag`

I don't see the `Cache-Control` header when downloading a widget, for instance:
```
$ curl -v https://hosted.weblate.org/widgets/bandcampdownloader/-/287x66-white.png -o a.png

> GET /widgets/bandcampdownloader/-/287x66-white.png HTTP/1.1
> Host: hosted.weblate.org
> User-Agent: curl/7.55.1
> Accept: */*
>

< HTTP/1.1 200 OK
< Server: nginx
< Date: Wed, 29 May 2019 13:12:29 GMT
< Content-Type: image/png
< Content-Length: 3768
< Connection: keep-alive
< Content-Language: en
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Vary: Accept-Language, Cookie
< X-Frame-Options: DENY
< Content-Security-Policy: default-src 'self'; style-src s.weblate.org 'unsafe-inline' 'self'; img-src stats.cihar.com s.weblate.org data: 'self'; script-src stats.cihar.com 'unsafe-inline' sentry.io s.weblate.org cdn.ravenjs.com 'self'; connect-src stats.cihar.com sentry.io 'self'; object-src 'none'; font-src s.weblate.org 'self';frame-src 'none'; frame-ancestors 'none';
< Set-Cookie: sessionid=xxx; expires=Wed, 29 May 2019 13:49:09 GMT; HttpOnly; Max-Age=2200; Path=/; SameSite=Lax; Secure
```

Could it be added?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed (the fix will be deployed in next days). 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by Otiel** [comment]
Thanks, all good now!

**Comment by Otiel** [comment]
I've noticed since several days that the widget is not up-to-date anymore.

See for instance [this README](https://github.com/Otiel/BandcampDownloader#contributing): it shows "118 strings into 4 languages":

![image](https://user-images.githubusercontent.com/3851902/59582134-85487f00-90d7-11e9-80dd-352e03e6e5c9.png)

While the [Engage](https://hosted.weblate.org/engage/bandcampdownloader/) page shows "124 strings | 9 languages":

![image](https://user-images.githubusercontent.com/3851902/59582178-ad37e280-90d7-11e9-980d-03084714c238.png)

**Comment by nijel** [comment]
It's in sync now. As the widget can be cached for one hour, it might be caused by this delay? I'm not sure how caching works on GitHub side - if they cache it for one hour and send it to clients with one hour cache header it makes the delay effectively two hours.

**Comment by Otiel** [comment]
What's weird is that I've seen the widget "go back in time", while the number of languages on the Weblate project never decreased (no language has been deleted):
* First it displayed "4 languages".
* Then (at the time of [my previous comment 15 days ago](https://github.com/WeblateOrg/weblate/issues/2783#issuecomment-498050506)) I've seen it display "6 languages".
* Now it's back to "4 languages".

Could it be an issue from GitHub's side?

**Comment by nijel** [comment]
I the same information on the widget as on the engage page - 124 strings and 9 languages.

**Comment by Otiel** [comment]
Sorry, I didn't understand that you meant that when you wrote:

> It's in sync now.

I still see only "4 languages", so it looks like it is actually an issue from my side! Will look into that. Thanks for your quick answers. 👍
