### ISSUE TITLE
Side-by-side Zen should line up the translation field with the source string

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2784]
![Skjermbilde på 2019-05-30 13-33-35](https://user-images.githubusercontent.com/13802408/58630462-c1aa6b80-82df-11e9-88b2-7ad88f7fc89e.png)

The translation field is top right, when using multiple guide-languages it is misaligned with the source.

Would want it to be bottom right

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
