### ISSUE TITLE
Performance issue when a project as many components (172 components)

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#2785]
**Describe the bug**
The more component there is, the slower is the save

**To Reproduce**
0. Fresh weblate 3.6.1 installation using yunohost, in a VM on a machine with 8 cores and 16GB of RAM
1. configure a project ***fedora-release-notes***, see: Project config-Screenshot_2019-05-30 Modification de Projet Administration Weblate.png (I chosed https://pagure.io/fedora-l10n/fedora-release-notes)
2. configure a first component ***f29nav***, see Component config-Screenshot_2019-05-30 Modification de Composant Administration Weblate.png
    1. note: this component only has one string to translate
3. ***TEST 1***, open the component ***f29nav***, select french
    1. repeat this operation three time: open all string, translate, save, it will come back to component's homepage for this language
4. ***TEST 2***, open the component ***f29nav***, add the autodiscovery component, which will add 171 new components
    1. come back to the component, select french
    2. repeat this operation three time: open all string, translate, save, it will come back to component's homepage for this language
4. ***TEST 3***, open the component ***f29nav***,
    1. remove component autodiscovery,
    2. delete all the previously created 171 components (using the admin interface)
    3. come back to the component, select french
    4. repeat this operation three time: open all string, translate, save, it will come back to component's homepage for this language
4. create a new project ***badges***,
2. configure a new ***nav*** on project ***badges***,
    1. note: this component only has one string to translate
5. ***TEST 4***, open the component ***nav***, select french
    1. repeat this operation three time: open all string, translate, save, it will come back to component's homepage for this language
6. ***TEST 5a***, open the component ***f29nav***, add the autodiscovery component, which will add 171 new components
    1. come back to the component ***f29nav***, select french
    2. repeat this operation three time: open all string, translate, save, it will come back to component's homepage for this language
7. ***TEST 5b***, open the component ***nav***, select french
    1. repeat this operation three time: open all string, translate, save, it will come back to component's homepage for this language
8. ***TEST 6a*** open the component ***nav***, add the autodiscovery component, which will add 4 new components
    1. come back to the component ***f29nav***, select french
    2. repeat this operation three time: open all string, translate, save, it will come back to component's homepage for this language
9. ***TEST 6b*** open the component ***nav***, select french
    2. repeat this operation three time: open all string, translate, save, it will come back to component's homepage for this language

**Results**

*** TEST 1***
[Test1-one project-onecomponent-Archive 19-05-30 14-12-47.zip](https://github.com/WeblateOrg/weblate/files/3237212/Test1-one.project-onecomponent-Archive.19-05-30.14-12-47.zip)

Test1, action | POST | Last file received | elapsed time :
-- | -- | -- | --
1 | 12:09:52.391 | 12:09:53.125 | 00:00:00.734
2 | 12:09:58.143 | 12:09:58.715 | 00:00:00.572
3 | 12:10:02.864 | 12:10:03.362 | 00:00:00.498
4 | 12:10:07.890 | 12:10:08.527 | 00:00:00.637
Mean |   |   | 00:00:00.610

It's fast, everything is fine.

*** TEST 2***
[Test2-one project-with autodiscovery-Archive 19-05-30 14-20-51.zip](https://github.com/WeblateOrg/weblate/files/3237213/Test2-one.project-with.autodiscovery-Archive.19-05-30.14-20-51.zip)

Test2, action | POST | Last file received | elapsed time :
-- | -- | -- | --
1 | 12:20:10.466 | 12:20:15.050 | 00:00:04.584
2 | 12:20:28.087 | 12:20:32.740 | 00:00:04.653
3 | 12:20:37.820 | 12:20:42.539 | 00:00:04.719
Mean |   |   | 00:00:04.652

It's too slow, it destroys user experience.

*** TEST 3***
[Test3-one project-onecomponent after removing all-Archive 19-05-30 14-25-56.zip](https://github.com/WeblateOrg/weblate/files/3237214/Test3-one.project-onecomponent.after.removing.all-Archive.19-05-30.14-25-56.zip)

Test3, action | POST | Last file received | elapsed time :
-- | -- | -- | --
1 | 12:25:42.607 | 12:25:43.487 | 00:00:00.880
2 | 12:25:47.225 | 12:25:48.310 | 00:00:01.085
3 | 12:25:51.797 | 12:25:52.802 | 00:00:01.005
Mean |   |   | 00:00:00.990

It's almost back to normal, it's weird it's 30% slower than before removing the component, but not a big deal.

*** TEST 4***
[Test4-two project-onecomponent-Archive 19-05-30 14-29-02.zip](https://github.com/WeblateOrg/weblate/files/3237215/Test4-two.project-onecomponent-Archive.19-05-30.14-29-02.zip)

Test4, action | POST | Last file received | elapsed time :
-- | -- | -- | --
1 | 12:28:45.335 | 12:28:46.052 | 00:00:00.717
2 | 12:28:49.387 | 12:28:50.015 | 00:00:00.628
3 | 12:28:52.949 | 12:28:53.635 | 00:00:00.686
Mean |   |   | 00:00:00.677

It's fast, everything is fine.

*** TEST 5a***
[Test5a-two project-one with autodiscovery-same as test 2-Archive 19-05-30 14-32-51.zip](https://github.com/WeblateOrg/weblate/files/3237216/Test5a-two.project-one.with.autodiscovery-same.as.test.2-Archive.19-05-30.14-32-51.zip)

Test5a, action | POST | Last file received | elapsed time :
-- | -- | -- | --
1 | 12:32:19.102 | 12:32:24.240 | 00:00:05.138
2 | 12:32:29.721 | 12:32:34.598 | 00:00:04.877
3 | 12:32:42.620 | 12:32:47.374 | 00:00:04.754
Mean |   |   | 00:00:04.923

Same as Test 2, no impact from having a second project, no surprises, it's too slow, it destroys user experience.

*** TEST 5b***
[Test5b-two project-one with autodiscovery-test impact on second project-Archive 19-05-30 14-34-05.zip](https://github.com/WeblateOrg/weblate/files/3237217/Test5b-two.project-one.with.autodiscovery-test.impact.on.second.project-Archive.19-05-30.14-34-05.zip)

Test5b, action | POST | Last file received | elapsed time :
-- | -- | -- | --
1 | 12:33:45.582 | 12:33:46.310 | 00:00:00.728
2 | 12:33:49.394 | 12:33:50.246 | 00:00:00.852
3 | 12:33:53.624 | 12:33:54.232 | 00:00:00.608
Mean |   |   | 00:00:00.729

Still fast, so it's not the server which is overwhelm.

*** TEST 6a***
[Test6a-two projects-both with autodiscovery-test on first project-Archive 19-05-30 14-38-00.zip](https://github.com/WeblateOrg/weblate/files/3237218/Test6a-two.projects-both.with.autodiscovery-test.on.first.project-Archive.19-05-30.14-38-00.zip)

Test6a, action | POST | Last file received | elapsed time :
-- | -- | -- | --
1 | 12:37:37.142 | 12:37:41.739 | 00:00:04.597
2 | 12:37:44.978 | 12:37:49.688 | 00:00:04.710
3 | 12:37:53.911 | 12:37:58.506 | 00:00:04.595
Mean |   |   | 00:00:04.634

Same as test 2 and 5a, it's too slow.

*** TEST 6b***
[Test6b-two projects-both with autodiscovery-test on second project-Archive 19-05-30 14-36-47.zip](https://github.com/WeblateOrg/weblate/files/3237219/Test6b-two.projects-both.with.autodiscovery-test.on.second.project-Archive.19-05-30.14-36-47.zip)

Test6b, action | POST | Last file received | elapsed time :
-- | -- | -- | --
1 | 12:36:33.844 | 12:36:34.783 | 00:00:00.939
2 | 12:36:37.565 | 12:36:38.496 | 00:00:00.931
3 | 12:36:41.820 | 12:36:42.626 | 00:00:00.806
Mean |   |   | 00:00:00.892

It's a little bit slower, but it's still acceptable for user experience.

**Expected behavior**
No impact on save time whatever we have one or many components one the same project.

**Screenshots**

Project config-Screenshot_2019-05-30
![Project config-Screenshot_2019-05-30 Modification de Projet Administration Weblate](https://user-images.githubusercontent.com/474883/58635977-86b03400-82ef-11e9-9e82-f7c4491a22ba.png)

Component config-Screenshot_2019-05-30
![Component config-Screenshot_2019-05-30 Modification de Composant Administration Weblate](https://user-images.githubusercontent.com/474883/58636005-99c30400-82ef-11e9-9337-b87de753772a.png)

Autodiscover config-Screenshot_2019-05-30
![Autodiscover config-Screenshot_2019-05-30 fedora-l10n fedora-release-notes f29 nav](https://user-images.githubusercontent.com/474883/58636043-ac3d3d80-82ef-11e9-8db6-6beb157ad734.png)

**Server configuration and status**
```
weblate@jb9:~$ ./venv/bin/weblate list_versions
 * Weblate 3.6.1
 * Python 3.5.3
 * Django 2.2.1
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.3.1
 * translation-finder 1.5
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.11.0
 * Pillow 6.0.0
 * python-dateutil 2.8.0
 * lxml 4.3.3
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.4
 * user-agents 2.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2019.1
 * pyuca 1.2
 * python-bidi 0.4.0
 * PyYAML 5.1
 * hub 2.3.0-pre10
 * Database backends: django.db.backends.postgresql_psycopg2
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Celery: redis://127.0.0.1:6379/3, redis://127.0.0.1:6379/3, regular
 * Platform: Linux 4.9.0-9-amd64 (x86_64)
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f0db6159950>
Traceback (most recent call last):
  File "/var/www/weblate/venv/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f0db6159950>
Traceback (most recent call last):
  File "/var/www/weblate/venv/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```

```
weblate@jb9:~$ ./venv/bin/weblate check --deploy
SystemCheckError: System check identified some issues:

ERRORS:
?: (weblate.E011) The site admins seem to be wrongly configured
	HINT: https://docs.weblate.org/en/weblate-3.6.1/admin/install.html#production-admins

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.6.1/admin/install.html#collecting-errors

System check identified 4 issues (1 silenced)
```

**Additional context**

**Comment by nijel** [comment]
I've made quite some improvements which should make it perform way better. I'm not sure if you're able to test those to measure performance impact in your setup.

Anyway the bigger improvement might come with https://github.com/WeblateOrg/weblate/issues/2786

**Comment by Jibec** [comment]
thanks for these commits, I installed it via `pip install git+git://github.com/WeblateOrg/weblate.git@181a82490c618f3408d9f424534ff06f90f9fc1b` but it was challenging to understand the new dependencies to install ;)

Result is really positive! Bravo! See:

After corrections Test2, action | POST | Last file received | elapsed time :
-- | -- | -- | --
1 | 20:21:07.747 | 20:21:09.206 | 00:00:01.459
2 | 20:21:12.137 | 20:21:13.867 | 00:00:01.730
3 | 20:21:17.346 | 20:21:18.846 | 00:00:01.500
Mean |   |   | 00:00:01.563

Would it be difficult to backport this in a minor release?

**Comment by nijel** [comment]
While it should be pretty easy to backport these individual commits, I don't want to spend time on this as there are other fixes which might look important for other users and doing point release would end up being major work. The next release  will be out in two weeks, what I believe is not that long ;-).

**Comment by Jibec** [comment]
Cool. If you give me commit numbers, I can get an archive of it from github and install from it with yunohost without changing much in the package.

**Comment by Jibec** [comment]
I understand

**Comment by nijel** [comment]
Now Weblate 3.7 with all the changes is out, so it should be easy to test in your environment :-).

**Comment by nijel** [comment]
Closing for now. In case problems reappear, they will be most likely different cause and should be addressed in separate issue.
