### ISSUE TITLE
Doublespace check

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2787]
Right now adding a doublespace is not an active check, but it is one of the most common errors.
https://hosted.weblate.org/checks/

Wrong:
```
"This is an  example"
```
Correct:
```
"This is an example"
```

Triggering it on doublespaces within first to last char would avoid false checks for spaces used as indentation, or line-endings. (For which there are already other checks)

**Comment by MetalDent** [comment]
Hi, anyone working on this?

**Comment by jschmidtlein** [comment]
I was planning to take a look, but hadn't actually started yet!

**Comment by nijel** [comment]
Addressed by https://github.com/WeblateOrg/weblate/pull/3115

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
