### ISSUE TITLE
Redesign notification mails

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2790]
**Is your feature request related to a problem? Please describe.**
Currently notification mails look quite simple and not formatted. This should be changed to make them look more professional. It should probably also include some branding.

**Comment by comradekingu** [comment]
Other than repeating the word "string" a lot, I think they are fine.
"Analytical error" one does not link anywhere though.
just says
"Error message
erroneous file

src/i18n/nl.json 
"

**Comment by comradekingu** [comment]
@nijel The whiteboard messages don't link to the respective project.
So I now know that "Weblate 3.7 release is currently scheduled on 16th June, all translations completed by then will be included." but can't click my way there from the e-mail.

It could be @nijel says: New whiteboard message added:
Actual message.

Now it says "New whiteboard message added.
**Message**: Actual message"

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
