### ISSUE TITLE
Side-by-side Zen editing field is not as tall as the source field

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2791]
If the source field has more than one line, it looks like this, misaligning the fields
![Skjermbilde på 2019-06-02 01-38-34](https://user-images.githubusercontent.com/13802408/58754771-e1a47f80-84d7-11e9-8f52-67b000fb590e.png)
The top line of the editing field is taken up by the translation info and buttons
![Skjermbilde på 2019-06-02 01-48-40](https://user-images.githubusercontent.com/13802408/58754819-9f2f7280-84d8-11e9-8f4b-eefa31c96c0e.png)
Expanding the gray part of the source field starts a line too early, because of the "needs editing" line
![Skjermbilde på 2019-06-02 01-50-04](https://user-images.githubusercontent.com/13802408/58754836-d56cf200-84d8-11e9-855c-466d6063f9eb.png)
![Skjermbilde på 2019-06-02 01-40-32](https://user-images.githubusercontent.com/13802408/58754773-e1a47f80-84d7-11e9-9c58-31b1e240694f.png)
![Skjermbilde på 2019-06-02 01-40-57](https://user-images.githubusercontent.com/13802408/58754774-e1a47f80-84d7-11e9-935b-13ff89fc6984.png)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
