### ISSUE TITLE
removal of checks does not depend on language rights

### ISSUE THREAD

**Issue by ali-avci** [WeblateOrg/weblate#2793]
It looks like a bug; 

We want that a user is able to edit only specific language(s). We have achieved that the user is able to save the translation where he has the rights to. But the user is able to clean ckecks defined in languages where he has no rights to save the translation.  Either the list of languages might be limited to the languages he is able to edit, or the clean check needs to check the edit rights defined for the specific language. 

By the way, thanks for the nice tool.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
