### ISSUE TITLE
Translation error/duplicate

### ISSUE THREAD

**Issue by ppasserini** [WeblateOrg/weblate#2796]
**Describe the bug**
I found 2 duplicated string  "Needs editing"  inside Weblate/Application.

**To Reproduce**
Just search into the English translation

**Expected behavior**
Delete one of them or change the meaning

**Comment by nijel** [comment]
It was intentionally introduced (each has different context), but probably is not needed anymore these days.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
