### ISSUE TITLE
Pagination button moves between views

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2800]
- [x] **Pagination buttons**
At the bottom, the pagination is not in the same place,
but it is a visual disturbance to have it there, with the active blue colour, when there is just one page to pick from. 
![bilde](https://user-images.githubusercontent.com/13802408/59002091-847b3780-8811-11e9-8a36-6d30d5e96ffa.png)

[One way](https://hosted.weblate.org/languages/nb_NO/guardianproject/#overview)
vs
[The other](https://hosted.weblate.org/projects/guardianproject/)

**Comment by nijel** [comment]
The placement has been addressed in 17a70a4532315bc20cffd36802dd590881e082ca, it's probably reasonable to hide pagination when there are no pages...

**Comment by comradekingu** [comment]
@nijel OK, added as feature request #2804
