### ISSUE TITLE
Buttons move around between views

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2801]
"Info search history" is "Info language search history", meaning search and history is not where it is expected.
I would much prefer if the buttons didn't move.
![bilde](https://user-images.githubusercontent.com/13802408/59001649-be4b3e80-880f-11e9-8c8c-325ee7937ce7.png)
becomes

![bilde](https://user-images.githubusercontent.com/13802408/59001605-8217de00-880f-11e9-88f6-1a87a760bbfb.png)
instead of moving buttons around
![bilde](https://user-images.githubusercontent.com/13802408/59001684-e175ee00-880f-11e9-82d5-84cce5faa1bb.png)

The common buttons could maybe be placed on the left, to avoid any gaps?

[One way](https://hosted.weblate.org/languages/nb_NO/guardianproject/#overview)
vs
[The other](https://hosted.weblate.org/projects/guardianproject/)

**Comment by nijel** [comment]
Currently the buttons are ordered by (perceived) importance, but it's mostly consistent with exception of buttons which make no use in context (languages when already being on one language).

**Comment by comradekingu** [comment]
@nijel Couldn't "Languages" go back to the landing page project view of languages when clicked from a translated language?

**Comment by nijel** [comment]
I've partly improved this by adding link to glossary and making consistent the insights menu, but I'm not really sure with the languages. It doesn't belong to the navigation here, it's going one level up which is done in breadcrumbs...

**Comment by nijel** [comment]
I don't think we can do more here, the inconsistent ordering has been already fixed.
