### ISSUE TITLE
Different info between views

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2802]
**Different info presented**

![bilde](https://user-images.githubusercontent.com/13802408/59001142-de79fe00-880d-11e9-95c8-171c1620c1b9.png)
https://hosted.weblate.org/languages/nb_NO/guardianproject/#overview
**vs**
![bilde](https://user-images.githubusercontent.com/13802408/59001161-f5205500-880d-11e9-9ecd-36c9355773b6.png)
https://hosted.weblate.org/projects/guardianproject/

[One view](https://hosted.weblate.org/languages/nb_NO/guardianproject/#overview) has
translated bars, and then the stats in numbers, no "linked"
[The other](https://hosted.weblate.org/projects/guardianproject/) has
Translated bars, word coverage bars, and no numbers, and is right-aligned.

[One way](https://hosted.weblate.org/languages/nb_NO/guardianproject/#overview)
vs
[The other](https://hosted.weblate.org/projects/guardianproject/)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
