### ISSUE TITLE
Pagination button steals attention and does nothing with one page

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2804]
![bilde](https://user-images.githubusercontent.com/13802408/59002091-847b3780-8811-11e9-8a36-6d30d5e96ffa.png)

Activly coloured blue, which means it should do something.
That there is only one page, when there is just one page, is not relevant information.
To that effect, I think that would be even more clear, if there were no extra things, like this pagination, so it should be removed.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
