### ISSUE TITLE
Respect default (Visual Studio) resx formatting

### ISSUE THREAD

**Issue by Otiel** [WeblateOrg/weblate#2807]
## Description

Weblate format _resx_ files differently than Visual Studio, namely:
* Line 1: single quotes are used instead of double quotation marks:
    * Default resx: `<?xml version="1.0" encoding="utf-8"?>`
    * Weblate: `<?xml version='1.0' encoding='UTF-8'?>`
* Line 1: encoding is capitalized instead of lower case:
    * Default resx: `<?xml version="1.0" encoding="utf-8"?>`
    * Weblate: `<?xml version='1.0' encoding='UTF-8'?>`
* Node `<xsd:schema ...>`: parameters order is changed:
    * Default resx: `<xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">`
    * Weblate: `<xsd:schema xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" id="root">`
* Self-closing nodes `< />`: the space character before the self-closing tag is removed:
    * Default resx: `<xsd:import namespace="http://www.w3.org/XML/1998/namespace" />`
    * Weblate: `<xsd:import namespace="http://www.w3.org/XML/1998/namespace"/>`
* Last line: a new line is added at the end of file:
    * Default resx: 
        ```
        </root>
        No newline at end of file
        ```
    * Weblate: 
        ```
        </root>
        
        ```

## Steps to reproduce

1. Format resx file through Visual Studio.
2. Translate some strings through Weblate. Commit, Push.
3. Notice the changes in the commit.

## Expected behavior

Weblate should respect the default resx formatting offered by Visual Studio.

## Screenshot

This shows a git diff (inverted compared to the steps above - red = Weblate version, green = VS version):

![image](https://user-images.githubusercontent.com/3851902/59201460-c8b46200-8b9a-11e9-877f-9918d026ff8d.png)

**Comment by nijel** [comment]
This is something to address in the [translate-toolkit](https://github.com/translate/translate).

Few notes:

- the XML header is hardcoded in the library, see https://github.com/lxml/lxml/pull/277 and https://github.com/translate/translate/pull/3840
- trailing newline should be easy to address
- the attribute ordering might depend on Python version, what version do you use?

**Comment by Otiel** [comment]
>the attribute ordering might depend on Python version, what version do you use?

I don't know, the issue is from https://hosted.weblate.org

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has been addressed by https://github.com/translate/translate/pull/3900.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by Otiel** [comment]
Thanks! How can I know if/when it has been deployed to Hosted Weblate?

**Comment by nijel** [comment]
I usually deploy these fixes once they are merge to the translate-toolkit, what usually takes some time.

**Comment by Otiel** [comment]
👌 perfect, I'll watch translate/translate#3900.

**Comment by Otiel** [comment]
It seems this issue has not been fixed:

>* Node `<xsd:schema ...>`: parameters order is changed:  
>    * Default resx: `<xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">`
>    * Weblate: `<xsd:schema xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" id="root">`

See for instance this recent [Weblate commit](https://github.com/Otiel/BandcampDownloader/pull/117/commits/c219062bfe86b1c406913a0d26471307ee99b938):

![image](https://user-images.githubusercontent.com/3851902/62635447-fe29c180-b937-11e9-94a2-5a1c112a1f02.png)

Can this be addressed?

**Comment by nijel** [comment]
Not easily, see https://stackoverflow.com/q/14917943/225718. The issue might be resolved once we upgrade to Python 3.7 as it has ordered dicts, but it needs verification.

**Comment by Otiel** [comment]
Thanks for the reply.

How should we track this in order to not forget it? Should I open a separate issue?

**Comment by nijel** [comment]
Okay, Python 3.7 doesn't change anything on this. Feel free to open issue on translate-toolkit, but I really don't see way to address this right now.
