### ISSUE TITLE
New bars look good, but have no seperation

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2810]
![bilde](https://user-images.githubusercontent.com/13802408/59311318-52eaec00-8ca9-11e9-804b-5824bdf70c82.png)

https://hosted.weblate.org/languages/

There should be some divide in between these, or am I reading it the wrong way?
Also everything is amassed leftwards.

Edit: I think what it is doing is presenting the first bar as the total, at-least in

![bilde](https://user-images.githubusercontent.com/13802408/59311497-0522b380-8caa-11e9-8c01-9dd764cf1412.png)

https://hosted.weblate.org/#your-languages it is (for me anyways).

**Comment by nijel** [comment]
The progress values are same as they used to be, that did not change at all. It looks okay for the ones you've posted - 89,8% translated, out of which 12,2% have failing check and then there are 10,2% which needs editing.

**Comment by comradekingu** [comment]
@nijel Right, but there used to be more bars.
![Skjermbilde på 2019-06-13 11-34-24](https://user-images.githubusercontent.com/13802408/59421721-5d9fa100-8dcf-11e9-98b1-34ae8f63871d.png)
Actually there were 4 of these. Two extra for the of totals.

This gives higher precision on the one graph, but it is less information dense.
To me the new way looks a bit like a clash of information.
I really liked having the of total bars to distinguish between.

**Comment by nijel** [comment]
I never liked the four bars, it really looked weird and in most cases people didn't know what to look for. With just one bar the most important thing is clearly visible while the other are available as numbers in case somebody is looking for more details.

**Comment by nijel** [comment]
PS: Also we're now showing same information at all levels (failing checks, comments and suggestions) what gives less space for the progress bars.

**Comment by comradekingu** [comment]
@nijel I like that, in that line of thinking, how about showing the same info, the same way, for every field too.

![image](https://user-images.githubusercontent.com/13802408/59429773-c2afc280-8de0-11e9-98f9-81f33346e0e1.png)
vs
![image](https://user-images.githubusercontent.com/13802408/59429787-ce9b8480-8de0-11e9-9749-4aa0a507e495.png)

Pixel for pixel, there is a lot to be saved

![image](https://user-images.githubusercontent.com/13802408/59429915-23d79600-8de1-11e9-8a01-a82f35a33556.png)

**Comment by nijel** [comment]
That might be option only for wide screens. For mobile we have to show only one progress bar to keep it readable and even on smaller laptop screens squeezing more than one progress bar would make it hard to read. And I tend to prefer consistent UI across screen resolution here.

**Comment by comradekingu** [comment]
In my view pixel-dense wide screens are more important, as most contributions come from people using them, but here it isn't even a question of having to sacrifice one for the other.

In the current view, on 30" 2160px wide, regular scaling, I have to pan my head left and right to compare the one bar visually. It can start all the way to the left, and end up mostly at the far right. Confusing all the numbers it passes with itself on the way. And I have to go up and down more too, since more vertical space is used with the bar being below the numbers.

The numbers are not aligned either, but that is another matter, but are divided by the bar, so harder to compare numbers for numbers this way.

The most important task is finding bars that are not all full, and then clicking the project in question to fix that. This means looking right at the opposite end of where the project can be clicked.

I would rather some views were minimized or not shown by default than compromise functionality.

The most important info in every view is going to be the first bar, and the first column, so users that can fit less information, could scroll right to get to the rest of it, like they scroll downwards now.

However with more of the first bar in vertical view for everyone, everyone wins?

**Comment by comradekingu** [comment]
![image](https://user-images.githubusercontent.com/13802408/59460186-c3674980-8e1e-11e9-98fd-29015efa95e0.png)
is 1024px wide
That is within every desktop resolution in current use https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide/#monthly-201805-201905-bar
For mobile there are a lot of lower resolutions, but those are not phones people use for Weblate anyhow. The Samsung Galaxy S had 800px, and that is within reason if the bars are smaller, or with some scrolling.

**Comment by nijel** [comment]
This is something what you (or some other experienced users) might enjoy, but that's not that useful for regular users - most people won't know language codes and showing many progress bars is just confusing. Actually the latter point was my motivation to have just one progress bar - people complained about the additional "of total" progress bars.

You can still sort the translations based on any progress, but displayed will be just one.

**Comment by comradekingu** [comment]
Speaking for me, I thought the current system was a bug at first, for reasons it is an unergonomic way to present one bar, as mentioned.
The feature was actually requested by a organization admin that favours non-experienced users over technically minded ones.

I favour it because of the Pareto principle, granting users trying to get a grasp of the total situation better insight. This scales to any level, but most importantly total work done.
For case of argument it also makes it possible to treat languages that have less effort compared to their reach differently to languages that meet inclusion policies otherwise.

What was the complaint other than wording?

**Comment by nijel** [comment]
Looking at the Hosted Weblate stats, there are quite some users from the mobile devices, that's why I think it's important to keep these in mind. Per devices it's 70% desktop and 25% smartphone. That's definitely not "next to none" ;-). The top three resolutions are:

* 24% 1920x1080
* 12% 1366x768
* 10% 360x640

I quite often use 1366x768 on notebook, that's why I might prefer to make things better fit on smaller screens...

**Comment by comradekingu** [comment]
As it is, the two most common resolutions, and above being desktop ones, possibly blocking the statistics more, have less information density. I think it is fair to say that is where most translations come from.

Having one bar stretching across doesn't fit into 360x640, so right now the one bar argument serves what demographic? What is the cut-off for scrolling? I'll try to make a mockup detailing where I think savings are more effective.

**Comment by nijel** [comment]
That's why I've mentioned the desktop/smartphone stats, there are hundredths of resolutions and these categories are better for getting overview. Yes, most of the translations do come from desktop, but 25% is definitely not "next to none".

And it currently fits nicely into 360x640:

![Screen Shot 2019-06-17 at 17 45 39](https://user-images.githubusercontent.com/212189/59618047-be104480-9127-11e9-8831-8de51c854b57.png)

(the displayed columns are changed only on page load)

**Comment by comradekingu** [comment]
So here the extra categories are not shown, I am not saying they absolutely have to be by default. What I am saying is they grant great utility to users of most screens.
In terms of vertical use, doubling the lines would grant something more extensive than A-C
If Strings and Words were inline, another line could be saved

![image](https://user-images.githubusercontent.com/13802408/59621904-8c4fab80-9130-11e9-8900-bad0a211ee23.png)
37.5 fields, vs 13
Considering the amount of languages sits at 310, the amount of scrolling even at 1600 pixels vertically is a greater concern than it looking airy.
