### ISSUE TITLE
Language consistency plugin by default for new projects?

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2811]
With the option to turn it off again in initial setup, or not default for very big projects,
the end-result is that of saving a lot of manual clicking for translators.

**Comment by nijel** [comment]
I don't think that enabling it by default is good idea. It should be rather part of https://github.com/WeblateOrg/weblate/issues/2789.

**Comment by nijel** [comment]
@comradekingu Let's keep this discussion here. Being it installed by default or not it still should be present in the https://github.com/WeblateOrg/weblate/issues/2789.

I see many projects which do not want to translate some leaf components (for example plugins or documentation) until the core components are translated. Automatically adding such translations would be surprising for the admins and that is something I always try to avoid.

**Comment by comradekingu** [comment]
@nijel That I presume is down to laziness or ill derived logic. It should generally be translators who get to decide where their contributions are worthwhile(?) Given the choice, that will be the main component, unless there is a special reason why not.
Naming, notifications and weighting of strings should be used to indicate priority, not barriers.

If it is the default to propagate language resources across components, then no surprise to be had.

What actually happens more often is the main branch translation is done, and then either manual clicking on part of the translator, not seeing that there are additional resources, or waiting around for the project admin to add resources. None of those are good.

If no component is added by default, nor propagation is turned on, the translator could just chose to add secondary resources, which does not change the premise of voluntary addition being cumbersome, and neither conducive to getting one component translated before the other.

It is most often just one translator doing a whole component, so one person adding more resources, only for someone else to see it and start working on the wrong one, is imo. not a greater concern than missing components, if wanting to complete a project, which is the ultimate goal. More people working on components that are available is conducive to such a goal, and it is better to complete a whole component and then check another one translated by someone else.

**Comment by comradekingu** [comment]
There are a lot of projects that do it manually, not knowing the plugin exists presumably.
The option that wastes the least (critical) time is the best.

**Comment by comradekingu** [comment]
I don't understand why it working by default is not to be expected?
Why make it a manual task, when it could be just a green light that it is possible to turn off.

**Comment by nijel** [comment]
Weblate always tries to not be intrusive to the project - make as small edits to the files as possible and avoid surprises and only edit the translation files as they are updated. There are log of addons which some people will think they should be enabled by default and we currently don't do that. I still think that better approach is better visibility to such addons and provide one click install in https://github.com/WeblateOrg/weblate/issues/2789.

The other reason for this particular addon is because I know many projects which will not want this :-).  It really depends on how you use projects and how rest of your infrastructure behaves.

**Comment by comradekingu** [comment]
@nijel Maybe a function to remove empty translation components would mitigate that. Or "Remove currently empty components added by consistency plugin".

**Comment by nijel** [comment]
I don't say it's not possible. It's lot of additional work just to make it reasonable to have it enabled as default and I currently don't see that it's that useful to have it enabled by default to justify the additional work. We have over 200 open issues and *lot* of them are more important than this.

As for grayed-out missing translations see https://github.com/WeblateOrg/weblate/issues/2610

**Comment by nijel** [comment]
I think that https://github.com/WeblateOrg/weblate/issues/4015 explains why it's not a good idea to have it on by default - for big projects it can cause big mess once new language is added.
