### ISSUE TITLE
Language specific comments answering source comments are local

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2812]
https://hosted.weblate.org/translate/manuskript/translations/de/?checksum=1946568260a9a6a2#comments

Will show in German, but not in other languages.

Just as source comments should not only be seen in the source view,
translator comments should be seen in all views.

Rarely is there a need to make it language specific, seen this type of thing more often,
and is more of a loss, so seeing all comments always would be preferable?

**Comment by nijel** [comment]
It used to be default and was changed in e57494c5b23, see https://github.com/WeblateOrg/weblate/issues/1060.

**Comment by nijel** [comment]
This should be finally addressed by https://github.com/WeblateOrg/weblate/issues/2831 - the notification for source string comment will point to source string page where only source string comments will be shown or posted.
