### ISSUE TITLE
Garbled text shown when using Weblate in Finnish

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#2816]
**Describe the bug**
When using Weblate in Finnish, the following text appears in the translation interface above the heading "Käännä" (Translate):

`Alt+PageUp/PageDown/Home/EndTekstien navigointi Ctrl+ESiirry käännösmuokkaimeen Ctrl+QSiirry kommenttimuokkaimeen Ctrl+MNäytä konekäännös -välilehti Ctrl+JNäytä Viereiset tekstit -välilehti Ctrl+SNäytä etsi -välilehti Ctrl+OKopioi lähdetekstin Ctrl+YMuuta Tarkistettava -valinnan tilaa ">`

It does not appear in a few other languages I tried, nor does it appear to be accidental copypaste in the translation strings.

**To Reproduce**
Select Finnish interface in settings at hosted.weblate.org, go to the translation interface, e.g. https://hosted.weblate.org/translate/weblate/master/fi/

**Expected behavior**
The garbled text above is not shown.

**Screenshots**

**Server configuration and status**

**Additional context**

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
