### ISSUE TITLE
Saving vertical space

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2817]
![image](https://user-images.githubusercontent.com/13802408/59617850-5eb23480-9127-11e9-963b-f199a1c52a96.png)
vs
![image](https://user-images.githubusercontent.com/13802408/59617891-6e317d80-9127-11e9-838f-2d1b1f9e2b6f.png)

The most often use content is maximized this way if all the controls don't fit,
and if it does fit, the information density is better.

For mobile use, vertical space is very limited in horizontal view, so this increases amount of seen projects greatly.

**Comment by nijel** [comment]
This would lead to need for hiding items even on 1366x768, so this boils down to same topic as https://github.com/WeblateOrg/weblate/issues/2810. Not everybody has huge screen with lot of horizontal space.

There is some space on lower resolution, but definitely not enough to squeeze both navigation bars into one:

![Screen Shot 2019-06-17 at 18 03 53](https://user-images.githubusercontent.com/212189/59619209-4bed2f00-912a-11e9-850a-176b4fff9a1e.png)

**Comment by comradekingu** [comment]
![image](https://user-images.githubusercontent.com/13802408/59621053-b011f200-912e-11e9-868d-ecb18b7d9786.png)
Is within 1000 px, easily 960.
This is without making the projects, language, insight, tools into pictograms, which would be consistent with the right hand symbols.

**Comment by comradekingu** [comment]
@nijel Challenge accepted
![bilde](https://user-images.githubusercontent.com/13802408/60390775-3ab70180-9ade-11e9-9e1a-424f29d7b6b0.png)
![bilde](https://user-images.githubusercontent.com/13802408/60390832-abaae900-9adf-11e9-9e86-b1614ce1d59c.png)

That saves 173 vertical pixels (!), and then another 50. Not counting the small stars, nor the fact that the line height is not the same between listings. The difference is being able to navigate between components if there are more than one.
Overall exact same information density, no extra pictograms. 

Notice tropdown triangle spacing is equal between all objects. I even added the two needed to have projects and watced projects drop.

I would make "Watched projects" "Watched", and possibly just make it "(eye icon) list)"

**Comment by nijel** [comment]
You can certainly remove all margin/padding and squeeze everything together, but I don't think that will help usability. Getting more blank space on the typical screen will do no good here :-).

Currently the page has logical blocks:

* global navigation
* breadcrumbs
* local navigation
* content

With this user can easily find where he currently is, what your proposal completely hides somewhere to the middle.

Weblate certainly needs UX improvements and it's on my roadmap to get something done about that in near future, but I think we rather first need some general approach for that and then focus on rearranging individual pages.
