### ISSUE TITLE
Best native format?

### ISSUE THREAD

**Issue by marcbria** [WeblateOrg/weblate#2818]
Hi,
I didn't find any forum or community space to make this kind of questions, so sorry in advance if this is not the right place to ask.

I'm working in a free software project (quite extend) and we like to move from our own translation tool to weblate. Our aplication follows it's [own XML native format](https://raw.githubusercontent.com/pkp/ojs/master/locale/en_US/editor.xml) so I suggested moving from those XML files to XLIFF to make the translation workflow easier, but more I dig, more doubts I have about this decision (as far as I can see, only a few projects use XLIFF files internaly).

We don't mind to transform our native XML files to something more standard (could be XLIFF, PO, yml, whatever...) but we are unsure about the best option.

As translation experts and from weblate perspective, what would be today your recommendation?

Thanks in advance for your time,
m.

**Comment by nijel** [comment]
Thank you for your question, it's something what indeed was missing in our docs and I've just added it: https://docs.weblate.org/en/latest/devel/starting.html#choosing-internationalization-framework

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
