### ISSUE TITLE
Support for Qt 5 Linguist TS files

### ISSUE THREAD

**Issue by Wohlstand** [WeblateOrg/weblate#2821]
**Is your feature request related to a problem? Please describe.**
Qt 5 and Qt 4 TS files are similar to each other, however, they have some differences:
* `<message>` tag no more uses `utf8="true"` tag, the codepage is always UTF8 or specified in the header of entire TS file.
* Version of TS is 2.1 on Qt 5 while 2.0 on Qt 4
* Vanished messages are now marking with `type="vanished"` in Qt 5 and `type="obsolete"` in Qt 4. However, Qt 4's "obsolete" is still work on Qt Linguist of Qt 5, but no more coming by default.

In most, Qt 5 translations are working well, except messages are marked as "vanished" are appearing as "alive" when they are must be same as "obsolete".

**Describe the solution you'd like**
For now because of "vanished" tag, obsolete messages are appearing as "alive" when they are must be not shown. The first solution is applying the [patch to the `translate` dependent library directly](https://github.com/translate/translate/pull/3902/commits/fb637f151c8c2ee2f5dc95cf41327901cdc34de6) which resolves this problem without modifying of WebLate itself.

**Describe alternatives you've considered**
However, when using the older `translate` library, the problem will still appear. Therefore it's would be needed to copy the patched implementation of TS file parser into the WebLate directly to support Qt 5 translations independently from the version of `translate` library.

**Additional context**
An example of Qt 5 translation that has vanished messages are marked by the new way: https://github.com/Wohlstand/OPL3BankEditor/blob/master/src/translations/opl3bankeditor_fr_FR.ts

**Comment by nijel** [comment]
This is something what needs to be addressed in the translate-toolkit. We won't ship patched translate-toolkit on our own because that would mean shipping whole library (given that most of recent fixes there are coming from Weblate).
