### ISSUE TITLE
ValueError: Namespace PangoCairo not available

### ISSUE THREAD

**Issue by darthginger** [WeblateOrg/weblate#2822]
**Describe the bug**
When trying to upgrade from 3.6.1 to 3.7 i get this error:
`ERROR Handled exception: ValueError: Namespace PangoCairo not available`
`Traceback (most recent call last):`
`  File "manage.py", line 33, in <module>`
`    main()`
`  File "/home/nouser4u/weblate/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)`
`  File "/home/nouser4u/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line`
`    utility.execute()`
`  File "/home/nouser4u/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute`
`    django.setup()`
`  File "/home/nouser4u/.local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)`
`  File "/home/nouser4u/.local/lib/python3.7/site-packages/django/apps/registry.py", line 112, in populate`
`    app_config.import_models()`
`  File "/home/nouser4u/.local/lib/python3.7/site-packages/django/apps/config.py", line 198, in` `import_models`
`    self.models_module = import_module(models_module_name)`
`  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module`
`    return _bootstrap._gcd_import(name[level:], package, level)`
`  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import`
`  File "<frozen importlib._bootstrap>", line 983, in _find_and_load`
`  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked`
`  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked`
`  File "<frozen importlib._bootstrap_external>", line 728, in exec_module`
`  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed`
`  File "/home/nouser4u/weblate/weblate/addons/models.py", line 47, in <module>`
`    from weblate.trans.models import Component, Unit`
`  File "/home/nouser4u/weblate/weblate/trans/models/__init__.py", line 35, in <module>`
`    from weblate.trans.models.component import Component`
`  File "/home/nouser4u/weblate/weblate/trans/models/component.py", line 46, in <module>`
`    from weblate.checks.flags import Flags`
`  File "/home/nouser4u/weblate/weblate/checks/flags.py", line 27, in <module>`
`    from weblate.fonts.utils import get_font_weight`
`  File "/home/nouser4u/weblate/weblate/fonts/utils.py", line 35, in <module>`
`    gi.require_version("PangoCairo", "1.0")`
`  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version`
`    raise ValueError('Namespace %s not available' % namespace)`
`ValueError: Namespace PangoCairo not available`

**To Reproduce**
1. install/update new python dependencies with python3 -m pip install -r requirements.txt
2. sudo apt install libcairo2-dev pkg-config python3-dev to get step 1 to work
2. manage.py migrate

**Expected behavior**
successful upgrade

**Additional context**
I need help on this one, google couldn't help me.

**Comment by nijel** [comment]
You need to install `gir1.2-pango-1.0` as well. Looks like this was forgotten in the docs...

**Comment by darthginger** [comment]
that fixed it indeed, thanks.

**Comment by nijel** [comment]
Reopening to keep track of updating docs to cover this.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by erictapen** [comment]
For those that are stumbling over this issue in the future, unable to make out how to tell PyGobject where PangoCairo can be found:

Setting `GI_TYPELIB_PATH` to the location of `girepository-1.0` helps. `girepository-1.0` should then contain something like `PangoCairo-1.0.typelib`.
