### ISSUE TITLE
Add Regex Tagger functionality

### ISSUE THREAD

**Issue by Artuvazro** [WeblateOrg/weblate#2827]
All CAT tools have the possibility of locking tags present in the text through regular expressions. I would like to see this feature implemented in Weblate.

Roughly speaking, it should work like this:
I have a segment such as:

`"Hello %s! How are you <color=yellow>doing</color>?"`

Then I should be able of writing two regex rules:
%s
<(?:\/)?color.*=>

This would lock the regex matches in all the segments and turn those tags into non-editable tags that can be inserted with a keyboard shortcut (usually is just one key that adds the first, then it adds the next one if you press it again, etc.).

It would also be pretty useful to throw warnings in the case of missing tags in a segment. This is also common in all CAT tools.

Thank you.

**Comment by nijel** [comment]
This specific case should be already handled by [XML checks](https://docs.weblate.org/en/latest/user/checks.html#invalid-xml-markup), but having something more generic might be indeed useful.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
