### ISSUE TITLE
Add an option to configure fuzzy match range and display % of match alongside every match

### ISSUE THREAD

**Issue by Artuvazro** [WeblateOrg/weblate#2829]
Being able of configuring the % of fuzzy matches would be quite useful. The standard in the industry is 70%-75% but sometimes you want to lower it or make it higher because some projects require it. Could this parameter be configurable on a per project basis?

Also, instead of having to hover your mouse over a "Quality" bar in the segments, it would be better to have the % always displayed over that bar.

![imagen](https://user-images.githubusercontent.com/8776528/59963110-e4026400-94ee-11e9-975a-4674eb94f339.png)

**Comment by comradekingu** [comment]
It seems it could be useful even per string, where some strings are crucially different, or a sentence-altering change was made.

**Comment by nijel** [comment]
In the machine translations (what I believe is topic of original issue) most of third party services have built in threshold which can not be configured, so all we could do is apply additional filter on the results.

**Comment by Artuvazro** [comment]
This is not related to machine translations but to fuzzy matches. I know both of them are called the same in Weblate, but I believe this terminology should be tweaked to adapt it to the current terminology being used by the industry. Machine Translations are the ones that Google or Deepl provide through their engines. Fuzzy Matches are the ones extracted from your Translation Memories.

Furthermore the threshold of acceptable fuzzy matches is configurable on a per project basis in all the CAT tools I've been using until now (MemoQ, SDL Trados, Transit NXT, etc.). Normally is set by default to 70% or 75% and fuzzies that fall under that % are not shown.

**Comment by nijel** [comment]
My comment was mostly aimed at @comradekingu, who I believe is bringing different topic here.

Mixing up translation memory and machine translation services might be indeed problematic, but they are currently grouped together as they share same API. It will probably stay like this for external services (eg. MyMemory), the built in translation memory will get separate interface, see https://github.com/WeblateOrg/weblate/issues/2664.

**Comment by comradekingu** [comment]
@nijel 
What I had in mind was a source that said (erroneously) 
"Do not click here if you want to keep the program open"
if that is changed to 
"Click here if you want to keep the program open"
translations will be within the limit of fuzziness, but none of them should be more than suggestions.
