### ISSUE TITLE
Xliff source lacks rich markup after editing

### ISSUE THREAD

**Issue by reloxx13** [WeblateOrg/weblate#2832]
**Describe the bug**
If creating a new component, it cannot parse the Source if the Source text includes
(as far i tried) `> < &`    
(Invalidates XML)

If finnaly the component creation worked by removing those chars, i could start translation.
By saving a translation string, in Test 9 the <bla bla/> Tag would be completly removed in the source tag of the target translation file, but will be saved in the target tag. And in the GUI ull see the <bla bla/> tag as source.

See my attached example Source file.

**To Reproduce**
Just create a new GIT Project with my example test.xlf   
Add a new component with the test.xlf as source
Hit save

**Examples**
```
<trans-unit id="test_2" datatype="html">
   <source>Test 2 is > Test 1 but < then Test 3 and 2</source>
</trans-unit>
```

```
<trans-unit id="test_8" datatype="html">
   <source>Test 8 Sun & Moon </source>
</trans-unit>
```
   

Source File:   
```
<trans-unit id="test_9" datatype="html">
   <source>Test 9 <bla bla/> said mr. x </source>
</trans-unit>
```   
Translated:   
```
<trans-unit id="test_9" datatype="html">
   <source>Test 9 said mr. x </source>
   <target>Test 9 <bla bla/> sagte Herr. x </target>
</trans-unit>
```

**Expected behavior**
Parse anytext between `<scource></source>` and `<target></target>`.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/14855001/60017780-dd5c2400-9689-11e9-8db3-d8d15d790678.png)

![grafik](https://user-images.githubusercontent.com/14855001/60018210-07621600-968b-11e9-94da-0d348eaa70ea.png)

**Server configuration and status**
```
./manage.py list_versions
 * Weblate weblate-3.7
 * Python 3.5.3
 * Django 2.2.2
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.10.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.3.1
 * translation-finder 1.5
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.11.0
 * Pillow 6.0.0
 * python-dateutil 2.8.0
 * lxml 4.3.4
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.9.4
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20121119
 * pytz 2019.1
 * pyuca 1.2
 * PyYAML 5.1.1
 * tesserocr 2.4.0
 * git-review 1.28.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: SMTP.office365.com
 * Celery: memory://, N/A, eager
 * Platform: Linux 4.9.0-9-amd64 (x86_64)
```

[weblatetest-master.zip](https://github.com/WeblateOrg/weblate/files/3320744/weblatetest-master.zip)

**Comment by nijel** [comment]
As you can see that even your editor highlights those - these are invalid in the XML - you should escape them - `>` becomes `&gt;`, `<` becomes `&lt;` and `&` should be written as `&amp;`.

**Comment by reloxx13** [comment]
Yeah, you are correct, but there are some cases like the <strong> tag which should not be escaped cause it should be shown in strong (html compiled).

Im not sure what is the right/best way to handle this.
This is an extern Project and they used XLIFF.

I mostly use POT&PO, with it i can use any unescaped special chars and the translater tools (Weblate/Poedit) can parse it.   
If i would start with XLIFF now, i would write those chars un-escaped just like with the POT files.

While writing those source strings while developing, its difficult to remember to escape those special chars   
(e.g. in sentences where you would write the & char).
   
It would rather be a nice2have feature to allow unescaped special chars.

**Comment by nijel** [comment]
You can use XML tags, but the content has to be valid XML, what those chars are not. Sorry, but there is not going to be feature to parse XML files which are not valid XML files. Are you creating XLIFF manually?

**Comment by reloxx13** [comment]
In this cases, yes its invalid XML.  
  
But i also got a Source Strings like this:     
(Its AngularJS with TypeScript)   
```
<trans-unit id="updateEvery" datatype="html">
   <source>
      Update every:
       <x id="INTERPOLATION" equiv-text="{{updateControl.value}}" />
       seconds
   </source>
</trans-unit>
```

And in the Translated File its this:
```
<trans-unit id="updateEvery" datatype="html">
   <source>Update every: seconds</source>
   <target>
      Aktualisiere alle: <x id="INTERPOLATION" equiv-text="{{updateControl.value}}"/> Sekunden 
   </target>
</trans-unit>
```

this <x /> tag should be a valid tag.

**Comment by nijel** [comment]
True, but that's completely different issue :-). I'll look into that.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by reloxx13** [comment]
Heya,
we just updated to 3.7.1 today and it still does not work correctly

this is my example:

Source File:
```
<trans-unit id="updateEvery" datatype="html">
   <source>
      Update every: <x id="INTERPOLATION" equiv-text="{{updateControl.value}}" /> seconds
   </source>
 </trans-unit>
```

Translated DE file:
```
<trans-unit id="updateEvery" datatype="html">
   <source>Update every: seconds</source>
   <target>
      Aktualisiere jede: <x id="INTERPOLATION" equiv-text="{{updateControl.value}}"/> Sekunde
   </target>
</trans-unit>
```

The x tag is missing in the translated source tag.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
