### ISSUE TITLE
Vertical administration field

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2834]
![bilde](https://user-images.githubusercontent.com/13802408/60030183-d261bd80-96a2-11e9-820b-b065502c3777.png)

Seen in https://hosted.weblate.org/access/f-droid/

@nijel I imagine you can see it on 
https://hosted.weblate.org/access/weblate/

**Comment by nijel** [comment]
That's intentional:
![project-access](https://user-images.githubusercontent.com/212189/60041408-99821280-96bb-11e9-9bb5-ba44e38426f3.png)
