### ISSUE TITLE
Add search input to navbar

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2835]
![bilde](https://user-images.githubusercontent.com/13802408/60060909-22687080-96f3-11e9-977c-1adf32941496.png)
Can there be a dropdown menu for Projects and Languages? It would be a lot quicker to get to anywhere then.
![bilde](https://user-images.githubusercontent.com/13802408/60060985-76735500-96f3-11e9-972a-7b6666fc1036.png)

**Comment by nijel** [comment]
No, there is too much of them to be useful in the menu. Also see #1235

**Comment by comradekingu** [comment]
@nijel 
That person didn't explain why the dropdown is ugly.
It isn't scrolling any less if you visit the page. Actually a whole lot more, only behind one extra click and waiting for the page to load.
That being said, why not dropdown on the ▼ and the site for people that want to visit it.
I'll take ugly over less functional any day. When the pagination of long pages was introduced, I got less effective. I keep a tab open just to counteract it.

**Comment by nijel** [comment]
It is ugly because there is 300 of them. There is no good reason to have this in menu as the menu will not really help you in navigation. Add projects you're interested in into watched and you will get your subset in the menu.

What might be useful addition though is list of user translated languages, I'll add this.

**Comment by comradekingu** [comment]
@nijel However ugly n number is, hiding it behind a nested menu and making it longer is worse.
Beside that, doing both means there is the same functionality across everything, and not complicating navigation with extra information and time.

**Comment by nijel** [comment]
I still don't think menu listing all of these is a good solution. What we more need is embedding search in navigation, something like GitLab has:

![Screenshot_2019-07-05 Projects · Dashboard](https://user-images.githubusercontent.com/212189/60725459-5df80b80-9f39-11e9-9c85-e2d12a4e25ec.png)

**Comment by comradekingu** [comment]
I like the current system of dropping down translated languages.
I find GitLab relies too much on search, and has little overview. Then again I like deterministic navigation.
Will try to think of where a search could be implemented.

**Comment by comradekingu** [comment]
Nested menus and extra clicks, other than finding out where they are, is the worst part about GitLab.

**Comment by nijel** [comment]
I was more considering search field directly in the navbar (for example like on GitHub). With suggestions on projects or components.

**Comment by nijel** [comment]
I think we really need GitHub like search in top navbar:

* Suggestion as typing for projects and components for direct navigation.
* It can replace search tab and it will make search available consistently in all scopes.

**Comment by tomkolp** [comment]
My project has over 2000 components, will the search work after visiting the project?
