### ISSUE TITLE
XML at end of string not saved when using Zen

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2844]
When using the Zen editor and clicking in XML elements manually, they don't update the string in question, which will be saved without it, and not get saved upon exiting.

I think it has to be the end of translation string for this to happen.

https://hosted.weblate.org/translate/gamehub/translations/nb_NO/?checksum=552d8d48318c4850

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
