### ISSUE TITLE
ARB file support [$15]

### ISSUE THREAD

**Issue by 12people** [WeblateOrg/weblate#2847]
**Is your feature request related to a problem? Please describe.**
I'm developing an app using Flutter and using the [.arb file format](https://github.com/google/app-resource-bundle/wiki/ApplicationResourceBundleSpecification), as per the [official Flutter documentation](https://flutter.dev/docs/development/accessibility-and-localization/internationalization#appendix-using-the-dart-intl-tools). This format is not supported by weblate.

**Describe the solution you'd like**
Support .arb resource files

**Additional context**
ARB is based on JSON and should therefore be relatively simple to implement.

**Comment by nijel** [comment]
Looking at [Sample resource file](https://github.com/google/app-resource-bundle/wiki/ApplicationResourceBundleSpecification#sample-resource-file), it's not JSON at all - it's JavaScript code, what makes it much harder to parse (see also https://github.com/WeblateOrg/weblate/issues/2043), or did I get something wrong?

Anyway the preferred approach for new file formats is to get support into [translate-toolkit](https://github.com/translate/translate) first.

**Comment by 12people** [comment]
@nijel Google's official example is confusing, as it includes code for adding the ARB file to a web app. ARB itself is JSON.

[Here](https://gitlab.com/emparent/emparent/blob/master/lib/l10n/intl_messages.arb)'s the ARB file that Flutter generated for me.

Anyway, I filed a bug report in the translate-toolkit project: https://github.com/translate/translate/issues/3910 . Should I close this one?

**Comment by nijel** [comment]
We need small boilerplate code once the format is supported in translate-toolkit, so it's good to keep this open.

**Comment by nijel** [comment]
PS: I was confused by comments in the sample as well, because that's not valid in JSON.

**Comment by MTRNord** [comment]
Hi any progress on this?

**Comment by nijel** [comment]
I don't think anybody is working on this.
