### ISSUE TITLE
Better visualization of current string in Nearby Strings

### ISSUE THREAD

**Issue by gorgobacka** [WeblateOrg/weblate#2849]
While looking at the "Nearby String" list, it's not clearly visible which one is the current string, although it's in the middle. The user needs to "search" for it, because it's not visually distinguishable.

**Describe the solution you'd like**
My suggesting would be to make the current string in the list more visible. Maybe via a different colour or in bold of the string number or the string itself.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
