### ISSUE TITLE
Performance boost: Component Discovery Addon should not be available to repo links

### ISSUE THREAD

**Issue by fdosanjuan** [WeblateOrg/weblate#2853]
**Describe the bug**
Any time a VCS pull is made on a component, it triggers the component discovery process on the component linked to an actual repository and on all its linked childs, which makes the pull operation terribly slow.

**To Reproduce**
1. Configure a Git repository with a lot of files.
2. Go to Weblate and create a project with one component linked to one of the files in the Git repo (let's name this component "master-component").
3. Install the Component Discovery addon on master-component to match all the other files in the Git repo.
4. It will take a while for Weblate to create all the components, but that's OK. Wait for it to finish.
5. Modify one of the files in the Git repo (e.g., add a new term to translate)
6. Back to Weblate, go to the repository management view of one of the components and perform a Pull operation. This will be very slow.

**Expected behavior**
Once the pull button is pressed, the process to sync the repo should not be that time consuming.

The method Component::update_branch (in file trans/models/component.py) triggers a vcs_post_update on "master-component" and all of its linked childs. This eventually produces a call to post_update on each of the addons installed in the child component. And here lies the problem: since each linked child has the component discovery addon installed, it will be run. 

I understand the need to run the component discovery on the "master-component", but not on its children.

**Easy fix**
I have managed to temporarily fix it by modifying the method DiscoveryAddon::post_update (within file addons/discovery.py):

```
def post_update(self, component, previous_head):
        if not component.is_repo_link: 
                self.perform()
```

However, I am wondering whether a better solution would be to not install the Component Discovery addon automatically on child components (i.e., those created by Weblate as a result of the component discovery itself).

**Notes on performance**
With ~350 child components, the previous fix makes the Pull operation run 7.5 times faster.

**Server configuration and status**

* Weblate 3.7
 * Python 3.7.3
 * Django 2.2.2
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.5
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.20.1
 * Pillow 5.4.1
 * python-dateutil 2.8.0
 * lxml 4.3.2
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.9.4
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20121119
 * pytz 2019.1
 * pyuca 1.2
 * PyYAML 3.13
 * tesserocr 2.4.0
 * Mercurial 4.8.2
 * git-svn 2.20.1
 * Database backends: django.db.backends.mysql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: 192.168.0.140
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.15.0-52-generic (x86_64)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
