### ISSUE TITLE
Documentation about caching is not clear about the prerequisite

### ISSUE THREAD

**Issue by erciccione** [WeblateOrg/weblate#2854]
[The docs](https://docs.weblate.org/en/weblate-3.6.1/admin/install.html#enable-caching) give a configuration for the Redis server, but it's not specified that you need to install `django-redis` and `hiredis`. These two are not mentioned in the installation process but they are required to make weblate and the caching with redis work.

I think would be better to mention in the 'caching' section that those packages need to be installed, or they could be added to the requirement.  
Especially since not having caching set up, is flagged as a critical error by `check --deploy`.

This problem was already mentioned in #2081

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
