### ISSUE TITLE
Flat XML support

### ISSUE THREAD

**Issue by kgronowski** [WeblateOrg/weblate#2857]
**Is your feature request related to a problem? Please describe.**
It would be nice to see support for simple XML files in Weblate.

**Describe the solution you'd like**
It shouldn't be hard to implement since translate-toolkit added support for this format in newest release https://github.com/translate/translate/commit/03c3d9c52194b5a09cbcab20bbd3ba82f761d46f

**Comment by nijel** [comment]
Yes, it should be pretty easy. I've just submitted PR to translate-toolkit to standardize API a bit: https://github.com/translate/translate/pull/3908

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
