### ISSUE TITLE
missing tables after upgrade to 3.7.1

### ISSUE THREAD

**Issue by mvrhov** [WeblateOrg/weblate#2858]
**Describe the bug**
I've upgraded the weblate in virtual env using a pip.. at the end I've run `weblate migrate --noinput`
After clicking the Fontgroups and font in admin I get the report to the email, that the fields/tables do not exist

```
ProgrammingError at /admin/weblate/fontgroup/

relation "weblate_fontgroup" does not exist
LINE 1: ...ct"."id" IN (SELECT DISTINCT U0."project_id" FROM "weblate_f...

ProgrammingError at /admin/weblate/font/

relation "weblate_font" does not exist
LINE 1: ...ct"."id" IN (SELECT DISTINCT U0."project_id" FROM "weblate_f...
```

**Comment by nijel** [comment]
You probably miss `weblate.fonts` in the `INSTALLED_APPS` setting, looks like this was forgotten to be mentioned in the upgrade instructions, I've just added that.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
