### ISSUE TITLE
Login icons not aligned

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2861]
Some icons left-aligned

Ubuntu, openSUSE and Fedora look different from the rest.
The spacing between the icon and the text is a bit different between them, padding maybe?

![Skjermbilde fra 2019-07-07 08 53 28](https://user-images.githubusercontent.com/13802408/60765094-fce54a80-a094-11e9-9002-28b2d0f89bbc.png)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
