### ISSUE TITLE
Navigation to and from dictionary

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2863]
Project > Component > Language
![Skjermdump fra 2019-07-07 22-41-48](https://user-images.githubusercontent.com/13802408/60773916-ce0abb00-a10c-11e9-9546-17ff60fe7536.png)
Clicking dictionaries is a bit unexpected, because the regular navigation changes, with no recourse
Weblate > Dictionaries > Same language
![Skjermdump fra 2019-07-07 22-42-07](https://user-images.githubusercontent.com/13802408/60773918-d5ca5f80-a10c-11e9-9e10-4cd822e3e210.png)

There is no clear way to get back here.
Maybe clicking the language (which does nothing) would at-least get one to
Weblate/language
Or if it was
Weblate > Dictionaries [x]> Same language > (same component grayed out)
One could do away with the dictionary part.
A possible alternative is to just do both the navigations
"Project > Component > Language
Weblate > Dictionaries > Same language"
Possibly like this
"Project > Component > Language[x]
Dictionary[x]"

It would be nice to have a dictionary > language somewhere, which would be a dictionary for the whole language.
Similar problems are present for other types of navigation.

**Comment by nijel** [comment]
The dictionary is currently only per project, see https://github.com/WeblateOrg/weblate/issues/1158.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
