### ISSUE TITLE
Allow setting a project page as the index page for a weblate installation

### ISSUE THREAD

**Issue by samtuke** [WeblateOrg/weblate#2867]
**Is your feature request related to a problem? Please describe.**
When visitors come to our weblate site, they see a mostly empty page with one project listed. Our installation has only one project, with many languages, so naturally all visitors always have to click on that project, and then click on languages (from another mostly empty page), before they can find what they are looking for, which is usually a list of the available languages. By default weblate seems to be configured for multi-project usage, but many use cases are single-project only.

**Describe the solution you'd like**
Allow configuration of weblate to change the index / homepage of an installation, from the project list, to the languages of a specific project. This way our visitors will find what they are looking for on the first page of their visit, not the third. Out of interest, we previously used Pootle in this way.

Great work on the product, by the way. Keep it up!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
