### ISSUE TITLE
Provide signatures for tarballs

### ISSUE THREAD

**Issue by hefee** [WeblateOrg/weblate#2868]
Currently the tarballs, that can be downloaded have no signature. That means there is no way to verify the integrity of the tarballs.

You find a howto create signatures for releases:
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by nijel** [comment]
The tarballs are PGP signed, see https://weblate.org/download/ and https://docs.weblate.org/en/latest/admin/quick.html#verifying-release-signatures

**Comment by nijel** [comment]
What you're probably missing is release being uploaded to GitHub, it would be great to mention that in the post...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
The future releases will be now automatically uploaded there, I've uploaded bunch of past releases as well - https://github.com/WeblateOrg/weblate/releases

**Comment by hefee** [comment]
Thanks for fixing this.
The download page does not mention the existence of .asc files. So it was not obvious, that I should try to download a .asc file from there.

**Comment by nijel** [comment]
Indeed, those were added without much consideration. New website which will be out in week or two addresses this.
