### ISSUE TITLE
Notification redesign redesign

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2870]
![Skjermbilde fra 2019-07-09 13 23 28](https://user-images.githubusercontent.com/13802408/60884397-0d402580-a24d-11e9-81b6-7b89a7ce41e2.png)

Would want it to be
"[New string to translate] in [Weblate] / [Application] - [Norwegian Bokmål]"

All the categories could be links.

"View the translation", at the bottom, past some scrolling, does not make sense in any department.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
