### ISSUE TITLE
Use the word "translation" more consistently

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#2878]
**Is your feature request related to a problem? Please describe.**
The word "translation" appears to be used in Weblate to mean different things: a translation project or component (such as in "Suggested translations") or, more commonly, a translated string. This causes some confusion when translating Weblate, possibly also when translating with Weblate.

**Describe the solution you'd like**
Use the word "translation" to refer to translated strings only. Use "translation project" or "translation project", or just "project" and "component" to refer to projects and components.

**Describe alternatives you've considered**
Always using "translated string" to refer to a translated string would also be possible, but shortening it to "translation" is quite understandable IMO, if the other meanings of "translation" are taken care of.

**Additional context**

**Comment by comradekingu** [comment]
Is the confusion over "translated string" possibly meaning either
state: translated (finished translation)
or
translatable string, where a translation is possible, one of the many strings for translation
?

**Comment by tjhietala** [comment]
Not sure I follow, but what I meant was that in Weblate, "translation" can currently refer to a project, a component, or a string. If it would only refer to a string, it would be more understandable.

There's actually a fourth meaning, too, in "The translation has come to an end." where (as I understand it) it refers to the process of translating.

**Comment by comradekingu** [comment]
@tjhietala Yes, you got that right. I don't think that string is used anymore, I could be wrong.
Are there any offending strings left? If you copy links from Weblate itself it is easier to keep track of the confusing ones.

**Comment by tjhietala** [comment]
@comradekingu There are at least "Watched translations" and "Suggested translations", both of which refer to components. In total there are currently 297 source strings containing the substring "translation" in Weblate/Application, so it would take some time to review them all.

**Comment by comradekingu** [comment]
@tjhietala Nice catch, fixed here https://github.com/WeblateOrg/weblate/pull/3044
Should fix it at the top of
https://hosted.weblate.org/#your-subscriptions
And at the bottom of
https://hosted.weblate.org/accounts/profile/#preferences

Suggested translations are actual string suggestions.
