### ISSUE TITLE
Notification e-mails missing name of commenter

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2879]
Notifications of new comments feature the actual comment, but not whoever made it.
It says the name up top, but the nickname is missing from the comment.

![bilde](https://user-images.githubusercontent.com/13802408/61137485-e50f2b80-a4c5-11e9-927f-7a484cbdd474.png)

**Comment by nijel** [comment]
I've changed it to include username instead of full name, as that is what we show in most of the UI.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
