### ISSUE TITLE
Trailing stop for languages other than (Chinese, Japanese, Devanagari or Urdu)

### ISSUE THREAD

**Issue by proneon267** [WeblateOrg/weblate#2880]
I am translating english language strings into odia language. But I get trailing stop error. But my language doesn't have a full stop. Instead it has `|` as full stop. 
please fix this.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
