### ISSUE TITLE
Weblate digest e-mail has HTML markup in it

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2882]
Is it just my e-mail client that doesn't handle HTML in the middle of an e-mail?

Weblate Digest, Vol 76, Issue 9

Date: Mon, 15 Jul 2019 19:34:41 -0000
From: Name Namerino <noreply@weblate.org>
Subject: [Weblate] [Hosted Weblate] New comment in Weblate/Website
To: weblate@lists.cihar.com
Message-ID: <156321928151.22530.3599586132483195864@django.cihar.com>
Content-Type: multipart/related;
    boundary="===============4067237712760471132=="

--===============4067237712760471132==
Content-Type: multipart/alternative;
 boundary="===============7916508742181093394=="
MIME-Version: 1.0

--===============7916508742181093394==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

IyBDb21tZW50IGFkZGVkCgpbV2VibGF0ZV0oaHR0cHM6Ly9ob3N0ZWQud2VibGF0ZS5vcmcvcHJv
amVjdHMvd2VibGF0ZS8pIC8KW1dlYnNpdGVdKGh0dHBzOi8vaG9zdGVkLndlYmxhdGUub3JnL3By
b2plY3RzL3dlYmxhdGUvd2Vic2l0ZS8pIC8gW1BvcnR1Z3Vlc2UKKEJyYXppbCldKGh0dHBzOi8v
aG9zdGVkLndlYmxhdGUub3JnL3Byb2plY3RzL3dlYmxhdGUvd2Vic2l0ZS9wdF9CUi8pCgpUaGVy
ZSBoYXMgYmVlbiBhIG5ldyBjb21tZW50IG9uIFdlYmxhdGUvV2Vic2l0ZSBhdCBIb3N0ZWQgV2Vi
bGF0ZSBieSByYWZhZWxmZi4KCiMjIFNvdXJjZSBzdHJpbmcKCkRpdmUgaW50byBXZWJsYXRlIGZv
ciBmcmVlLCBvciBjb25uZWN0IHdpdGggb3VyIHRlYW0gb2YgcHJvZmVzc2lvbmFscyBmb3IgYQpt
b3JlIGZvY3VzZWQgYWR2aWNlIG9uIHlvdXIgZXhhY3QgbmVlZHMuIFdlIGhhdmUgZXh0ZW5zaXZl
IHNraWxscyAmIGV4cGVyaWVuY2UKd2l0aCBvdmVyIDE1MCsgbGFuZ3VhZ2VzLgoKIyMgQ29tbWVu
dAoKREVWczogQ29uc2lkZXIgdG8gZGlzYW1iaWd1YXRlICJmcmVlIjogYXMgaW4gZnJlZWRvbSBv
ciBpbiBmcmVlIGJlZXI/CgpbRWRpdCB0aGlzCnN0cmluZ10oaHR0cHM6Ly9ob3N0ZWQud2VibGF0
ZS5vcmcvdHJhbnNsYXRlL3dlYmxhdGUvd2Vic2l0ZS9wdF9CUi8/Y2hlY2tzdW09MWYzZGZlZDNm
ZTM1YTFmZCkKCiMgIFRyYW5zbGF0aW9uIHN1bW1hcnkKCkFsbCBzdHJpbmdzCgo0MzUKClRyYW5z
bGF0ZWQgc3RyaW5ncwoKMzU4ICg4Mi4zJSkKCk5vdCB0cmFuc2xhdGVkIHN0cmluZ3MKCjM0ICg3
LjglKQoKU3RyaW5ncyBuZWVkaW5nIGFjdGlvbgoKNzcgKDE3LjclKQoKU3RyaW5ncyBtYXJrZWQg
Zm9yIGVkaXQKCjQzICg5LjklKQoKW1ZpZXcgdGhlCnRyYW5zbGF0aW9uXShodHRwczovL2hvc3Rl
ZC53ZWJsYXRlLm9yZy9wcm9qZWN0cy93ZWJsYXRlL3dlYnNpdGUvcHRfQlIvKQoKWyAhW10oY2lk
OmVtYWlsLWxvZ29AY2lkLndlYmxhdGUub3JnKSBdKGh0dHBzOi8vd2VibGF0ZS5vcmcvKQoKW1dl
YmxhdGUsIHRoZSBjb250aW51b3VzIGxvY2FsaXphdGlvbiBzeXN0ZW1dKGh0dHBzOi8vd2VibGF0
ZS5vcmcvKQoKPGh0dHBzOi8vaG9zdGVkLndlYmxhdGUub3JnLz4g4oCiIFtDaGFuZ2Ugbm90aWZp
Y2F0aW9uCnNldHRpbmdzXShodHRwczovL2hvc3RlZC53ZWJsYXRlLm9yZy9hY2NvdW50cy9wcm9m
aWxlLyNub3RpZmljYXRpb25zKQoKR2VuZXJhdGVkIG9uIEp1bHkgMTUsIDIwMTksIDk6MzQgcC5t
LgoK

--===============7916508742181093394==
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html>
<html lang=3D"en" dir=3D"ltr">
 <head>
  <meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8">
    <meta name=3D"viewport" content=3D"width=3Ddevice-width, initial-scale=
=3D1.0" />
  <title>New comment in Weblate/Website</title>
  <style>

………………

.</span>
        </div>
    </div>
 </body>
</html>
--===============0204704086512047508==--

--===============4071517335688951387==
Content-Type: image/png
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-ID: <email-logo@cid.weblate.org>
Content-Disposition: inline; filename="weblate.png"

iVBORw0KGgoAAAANSUhEUgAAAJUAAACWCAMAAADg6DrTAAABoVBMVEUUTT8Up54B0uQC0uID0uIE
0eEF0N8G0N4H0d0I0dwJ0doK0dkM0dcM0dYN0dUO0dQafGkYY1ItzKsty6kgn4MjrY4ksZIjro8i
rI0iq4whqoshqYogqIkgpYcWVkcGytYXW0seiXIrxaQsyagVUkMdhnAXZlUXzscYb14VUEIsxqUY
YE8YmosZdGIbhHEaeGUmtZYXaFgpwJ8hpYcVT0EqwqEWU0Qmtpchg20agG0go4YO0NMUTkAWz8kX
bFsbzsIov54ZsqYnuZkrw6IsyKcrxKMB0uMPz9AP0NIZpJQVz8oQz88kspIS0M4kspMsx6YnupsU
z8wezL0fyLcmt5gdzcAYz8cZz8UbuKknu5snu5wfw7Eevqwovp4gx7QfzLsks5MRz84dn4cvY1di
iH9fhn1dhHsZWElRfHI9bGFFc2g3aFwzZVlXgHb////6+/vI1tKGpJzy9fSjubT8/f3X4d6ZsquJ
pp92l49skIdli4HN2tfr8O/h6OaCoZmuwr39/v6Qq6S2yMPd5ePl6+nT3tt8nJXB0M0yZFj2+PgZ
XU0m7GA7AAAJO0lEQVR4AWJgYGBkYmZhYWVjY+fg4OTi4ubm5uHlA7Bilumtw0AUdd4GXp0o5ToO
MzNzmfa/mTLrON8t6K/nk45Hd0j//2859nLDuCLuBxvDNlEHltne2dmJRnd39/b2Dx7W4eHRw/Ke
vsWQyodd4nyi+WjjJdAmmYL90kiVCabKOrCieGDCU9BzsF8OqZ4sU/+IKgSb5JOBrvrorAJaxWHD
IlI9aSeDVCVZVpHiV7XIwkohVfrxUxmpKrBJFY+rfTWro1mDJNEkqievVpCqLIodrqbVRpd2KAiJ
6kkRJaSq058hlWufhXYZ+s9AqhBSebBHlw4rtCy7HlJVYcc+UQ3yQVTDEezRlmTFwuIgrCKVF0Q1
Jm0mOS9Yy5OpykjlB1FREs2rh40KIr4zQapiENXUUV3QA8uZSlX/HtWcMjFSURVfkGFTpnK/Q+XK
oVUjwx0wzARSxVSqDFJRut1mql/7avr3vor+nopi0NfVruoq973MMCYqOQ0tf02l53Y9Oa6EzCDk
dqkO5iPiYR3EN3Id7AT2DBn9YvSrFnuG0SOv3F8txOo8kdOtQarv9aI4TKwdsZPJfasXrct9O3dz
ntizgibyO0z1rRmHT7O71j208/UZ51vzIN9MT9NfYaTPg9+anXPiNLESo8LpB8/O+jsDR/yOVsWN
/M7w7I8SUaHcl9I4kWaXktiJyoye0wtSzalDkYKrqfYW7jZRveB7x0R14oHHFS+M2mhVBFkhVf/l
a4yoTrfUIIwqslqOSFZE9ZptQ0h1pvZ9yQ5kNaHn87aR6jX4S0iVzdsjVVuQTE0VexmpzKtT60h1
WnbErN2ESUioggap3vBHMaQ6U2qOdYVssurgBQLVuy9CSHXubX5BwKIzWoTFAWeLqfz3EEWqi4oq
rO6HqrQSZTVqIpUZvTuTqeYbMxb3DSYZ0R656pdI1f9gEkKqK1vv5fBmvReXBcJqwP8x1cdCUWIq
u8lKJTe/2Jo1UUFpdq+RavAxHflMdTXhV8jAY/3GErHqdjQz1Wcph5hqLr4jh1fPwjGN9jJxYwl+
NrJcdclUn/XXZypbWfnlBmWlurN223IWRaC5RirzGd+LMdU8L0Zh+Omye7cPzrKwIr7V1V4y1deO
IMRUVyWo0LjuabHrJUedIIDjnf9/ApVJrtYIE4UFYkik4nKu6y73/g9xYY4cxUBP9L4vsJ/tnmAT
nV2ERgk7zMZerg8QFc9vIKofMv4ZKGFNaj3cIf7ARz8nqyjwpRBVbIcSopqV2X83ie1w5MQuoIiq
AXwdRPWD36HeRFgjhR2ZCb/DEkRT3tSTVQRi9XKI6qOEvi1w2ewXZI2iw8p7EMkhdUSlQbwOpuoP
IFLRxVgUGGsSshIe62kdUREHkoaFqD6eGeKnLH5Zct0NVacKN+kWptIgqQ6m6p9Hf4jeFFOlJfDz
SMiiHOoCU4Wj4oaFqSpnZexdh1PNAkQjExx414v8idIEVWmQ3ABVVS4jR95pYar0jDiBi0zT/LeR
IpmgKtoDpBSquro2dQjTcFUhayztjTaNrMU4mqCqIwOw1Byqurq+GUCYjasK83YPEnJKFxNcVQI8
U6AaDk019H9DVYvqVtylHXz/jqu6HuD1UiLV5bk56IUHHld9O81KkT+jSJnbW5GqAaKMnEA1PDs/
vzE7Dd33Z4Sq07xr04GqAxQNjdp3ozuhqgTiOiLV5fn5/f3Dg8l2OBer8vP5dOq6brP5+Pg4EqtI
EVaUEqsYi517K70v1aEMq1JyAlUwrLECi+i+VBaszvghUJ2FOwQnsx9VCdZp8C+q8of1tFA9dGCR
N9mHiuiwVlWB6nmh8lllduLd3VVdBdbMxFVnwbBeVFgkz3dVdVVYOxNXLYd1zH7N5eluKhtBISxU
9YdFHDat6Q4qDIWz3qGqYIcPpMdY7vYqDIXXecVUy2E9UMZS69uqiAIb16gkqxiLqe4YCzx7OxXV
YYvUMa76zWoxFjg0vbkqW4Pt6pmvyarnJ7bDu7tWcF/VmpuqujJsXWOMqYIdtoKLoGJvpirpsENF
82OSKhxW66AMLG2yvsouw46pZj+uCk7Wnc96kYCl0+l6qgML9pCciqnCYX1fsJa/cI+6q1VZSYf9
JJvnMRVjjfxhfQ2vhl67LlYRS4f9pUupM07l7/DRHxapeRAm0xGmOqAG7DtHM8fnTBUO6/GAWgrw
GW27yauypKbCX6pnWFXz54fxy8vxiVm1yh5gKY0aJcS2D2xCae1Xe+W3myoTxdH9Or0nfaFRUawL
KgjYolC0WvvUn9OZMKnngIarLzmzLszO/PnNYmcnDhz8Z/B4PB6Px+PxeDweNZlMAtFMJzPRBNeV
sNuzzMWwmGim0fJJHNcVJbdEbtVcc7yYxZVbUbeXgZ9TCvjZXEL8LJoZHYkYXrGsU5eUwUpu2QC5
WArAUboTlrn8Joxhpost8KaLKbzLXSuo1JDVEmAXjLGye3u5kgKpfTjtrOK9YeusNlEUTeoG6iGr
PSQQiSHSGTnwoYtF93Jr45XckNr4A3DQRQ2lsxKHsbJty+E4ZPXJcQofIo4FoH734yQ9lPBpxiqh
UeZwdN9qBdWA1QvUYcZhrFUE8ZPIG2xhIvIck4X3rUo4D1jtYSvvsBhpFWawFEk5fkGu77KRu1ZR
RTMfsHrXfS+gGGNlN6f6t5VK+0ygdlbN7ofCWVHV9fkA1Zv0W6lGj0UEm2GrysSH8gc1FDrmVc72
A0/OypI6K8vldTlgdUIPerCG5ZCVxa7eJtRaYC6FTq915Xq1/iH/3as6OUJcBL1WiQmpYT9odTHx
338d908piEOZQyEbmvD+XAWzNZR9Vqqh2V9p4XPkXIUNl6DV18OYNriwk3tWtsVJn1WJ42uEld39
qsh146m+oH3IagVVn1WC4zTSqoat+Q/MdcXrQ1Yl7HqsVEYTvWhySEZanSAx56e6YvWI1fIIdY9V
2Y1TBI0aZzUHONopBZSzIkstYWe1K8uyaGOIF86qNady0Zy7P8CggnLAKrHp07+OO/a7D0Alzsrh
rCxcZuKsDObudwxzNx3JgJWFD/mTA9gvSoHzI1bZ4UNJj9UW1k+6MHWmxlmp61yaV8Nr5S6GL47g
15KykgZ3Spk4l/Fsorv66eZZy7d4PB6Px+PxeDwej8fzf+M/d5oPasmfhysAAAAASUVORK5CYII=

--===============4071517335688951387==--

MIDDLEPARTWITHLOTSOFHTML

Subject: Digest Footer

**Comment by nijel** [comment]
This is mailing list digest, right? In that case mailman is responsible for that. There are some issues it has with creating digests, see for example https://gitlab.com/mailman/mailman/issues/473.
