### ISSUE TITLE
Search for source strings only

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2884]
https://hosted.weblate.org/projects/weblate/#search

Search for "good" in source strings, partial matches

https://hosted.weblate.org/search/weblate/?checksum=&offset=&q=good&search=substring&source=on&type=all&ignored=False&date=&only_user=&exclude_user=

This returns "good" in English, from every target language. That has some utility, don't know if it also includes "good" in the target, when it isn't found in the source?

However, I would expect to only get "good" from source strings.

Searching with English as selected target language when doing source string searches is the easiest and ugliest hack I could think of.

**Comment by nijel** [comment]
It does search only in source string, just the highlighting is wrongly done on all content.

**Comment by nijel** [comment]
Also related to https://github.com/WeblateOrg/weblate/issues/42

**Comment by comradekingu** [comment]
@nijel My issue is I sometimes want to find out if a string is used upstream, without paging through all the ir/relevant hits from other languages. (Not really sure when one needs hits from all languages)

How about if:

- Source strings
- Target strings

was

- Source strings with results for every language
- Target strings
- Source strings only

**Comment by nijel** [comment]
In 3.10 you will be able to search in source language only thanks to https://github.com/WeblateOrg/weblate/issues/2831

**Comment by nijel** [comment]
Searching is there for 3.10, let's deal with the highlighting in #42
