### ISSUE TITLE
Search scrolls, with search buttom at the bottom

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2885]
This is possibly the least smooth part of the workflow. Usually I don't want/use all the options, yet having to get to the bottom is bad for users that don't press return to search.

![Skjermbilde fra 2019-07-17 16 55 59](https://user-images.githubusercontent.com/13802408/61386018-c8069e00-a8b3-11e9-8162-a46b3fe5d93b.png)

Duplicating the "Search" buttom (at the bottom) to also be present at the top is the quickest fix.

**Comment by nijel** [comment]
You can still press enter after typing the search string :-). But I agree that UX wise this is bad.

**Comment by svora198** [comment]
how can I fix this?

**Comment by nijel** [comment]
@svora198 thanks for interest in fixing this. The problem here is that search form is too long and for many cases user doesn't need all the options. One of the solutions might be to collapse the advanced options (changed filter and languages).

**Comment by comradekingu** [comment]
@svora198 Either put another Search at the top, possibly more compact listings.
![bilde](https://user-images.githubusercontent.com/13802408/61532729-0a9eb680-aa2b-11e9-86e7-9a4da6bdc3ee.png)

**Comment by nijel** [comment]
To achieve this it should be enough to [adjust form settings](https://django-crispy-forms.readthedocs.io/en/latest/crispy_tag_forms.html#bootstrap3-horizontal-forms). I'm not sure if `{% crispy %}` is used for this particular form, so it might need more tweaking than just the single line.

**Comment by svora198** [comment]
Alright I will take a look and create a PR asap.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
