### ISSUE TITLE
WebExtension JSON: support placeholders

### ISSUE THREAD

**Issue by ariasuni** [WeblateOrg/weblate#2886]
**Describe the bug**
Weblate doesn’t warn a user when e.g. a source string contain a placeholder (e.g. `$VAR$`) and not the translation.

**To Reproduce**
1. Add a WebExtension JSON file with a string containing a variable.
2. Translate this string but without the placeholder, or with a missing `$`
3. Save and see that there is no warning.

**Expected behavior**
Weblate should warn about inconsistent number of placeholders between source and translation.

**Additional context**
[MDN documentation about placeholders](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization#Retrieving_message_strings_from_JavaScript).

I’m using an instance of Weblate 3.7.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
