### ISSUE TITLE
fix: i18next json schema version unclear

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#2887]
**Describe the bug**
In relation to #2855 and as recommended by @nijel , I started exploring i18next. Since this framework already has different [json-format versions](https://www.i18next.com/misc/json-format) , it is not obvious which version (currently v1, v2 or v3) is supported in weblate.

**Proposal**
Indicate in component creation dialoge -> file format drop-down : which i18next json format version is supported, e.g. **i18next JSON file v3**

![image](https://user-images.githubusercontent.com/8058166/61436703-a5b86300-a93b-11e9-8b78-0fec3303b407.png)

**Remark**
- Currently, by parsing the file, especially when base language (source) is `en`, it can be hardly identified what schema version is used. Therefore, I requested at i18next upstream to [declear schema version in json](https://github.com/i18next/i18next/issues/1284) directly.
- weblate documentation doesn't specify schema version either.

**Comment by nijel** [comment]
Thanks for pointing this out, I was not aware that there are more versions of the format.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by rhofer** [comment]
Many thanks for documenting.
Just a remark, discussion is ongoing in https://github.com/i18next/i18next/issues/1284 , appearingly v3 indication is not sufficient, there are allowed sub-variants as to strictly use index `_0`, `_1`, etc, what then applies to languages with simple plurals as `en` has, means `_plural` is allowed to be replaced with it's according index.
