### ISSUE TITLE
Update OpenShift documentation

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2889]
**Is your feature request related to a problem? Please describe.**
Currently we have only docs covering [OpenShift 2](https://github.com/WeblateOrg/weblate/blob/master/docs/admin/install/openshift2.rst) but no docs for OpenShift 3.

**Describe the solution you'd like**
Add documentation for OpenShift 3, possibly dropping OpenShift 2 one (if it's no longer useful).

**Additional context**
https://github.com/WeblateOrg/docker/issues/298, https://github.com/WeblateOrg/docker/issues/292, https://github.com/WeblateOrg/weblate/pull/2977

**Comment by alesrosina** [comment]
Yeah, let's write it down when docker is fixed, since this would bring also a bit of changes to actual openshift deployment.

But agree, this needs to be added.

**Comment by nijel** [comment]
I've added stub article here: https://github.com/WeblateOrg/weblate/blob/master/docs/admin/install/openshift.rst

**Comment by GrahamDumpleton** [comment]
Latest is actually OpenShift 4.2, but new documentation would work for for 3.X and 4.X at this point. Note that 4.2+ support is blocked by https://github.com/WeblateOrg/weblate/issues/3199
