### ISSUE TITLE
Languages are not sorted in search form

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#2894]
**Describe the bug**
Languages are not sorted in the search form ( at least in french ;-) ) ... it's not easy to find / select the wanted language.

**To Reproduce**
See: https://hosted.weblate.org/projects/weblate/master/#search

**Screenshots**
Attached ...
![Languages are not sorted in search](https://user-images.githubusercontent.com/1452146/61558515-933b4800-aa67-11e9-95ca-1471457b50e9.jpg)

Please sort alphabeticaly this list based on the displayed language.

**Comment by nijel** [comment]
To find language, there is a search interface :-). But true, those should be sorted.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by ldmpub** [comment]
> To find language, there is a search interface :-). But true, those should be sorted.

I agree with you it was not a major bug ... thanks for the easy / quick fix!
