### ISSUE TITLE
Too much "with spaces / line breaks" in new emails

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#2896]
The new notification emails automaticaly received by translators are nicer but they contain too much "with spaces / line breaks" => user is forced to scroll down to find relevant info.

For instance,  in the "New strings are needing translation" email, user needs to scroll down to have access to the link which opens the translation.

Simply open a weblate notification in Gmail, it will convice you that there is "room" ;-) for improvment in the new mail presentation layout.

Waiting to get other opinions,

**Comment by nijel** [comment]
It certainly needs more polishing. Especially on small (mobile) screens it often wraps wrongly.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by ldmpub** [comment]
Thanks new mail layout is still nice, readable and more compact.
