### ISSUE TITLE
Ability to search for parsed text

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2897]
If a string is 
"`Click <strong>here</strong>`"
the intuitive functionality is to search for "Click here" expecting to get the relevant result.

**Comment by nijel** [comment]
It should work on the fulltext search. It can't work for substring or exact match.

**Comment by comradekingu** [comment]
Will report back the next time it happens.

**Comment by comradekingu** [comment]
It could if there was a database of parsed text to search from(?)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
