### ISSUE TITLE
Include context in "new comment in" e-mails

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2899]
Sometimes people ask questions, that are answerable by looking at the context, but this requires
looking at the actual string. Would be easier if one could consider the context.

This is also useful when double-checking that advice given by other translators about the source string is correct.

Source string
→Context←
Comment

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
