### ISSUE TITLE
Build of introspection fails on openSUSE in 3.7+

### ISSUE THREAD

**Issue by scarabeusiv** [WeblateOrg/weblate#2901]
When testing the package on openSUSE I get following error:

```
[  111s] ?: (weblate.C024) Failed to use Pango: Pango.Layout.set_markup() takes exactly 3 arguments (2 given)
[  111s] 	HINT: https://docs.weblate.org/en/weblate-3.7.1/admin/install.html#pangocairo
```

Can I make it somehow more verobse to see more trace to find out what to blame?

The full diff between 3.6.1 and 3.7.1 https://build.opensuse.org/package/rdiff/M17N:l10n.opensuse.org/weblate?linkrev=base&rev=30

Full build log attached: [weblatelog.txt](https://github.com/WeblateOrg/weblate/files/3421697/weblatelog.txt)

**Comment by nijel** [comment]
Looks like incompatible gir or Pango version. Any patches on your side? 

It seems that https://github.com/GNOME/pygobject/commit/116d3712251b1b8aa2d4f4a9e40e22f5b9fcbe4f is missing but its *years* old and present in any recent release. The latest master still has the default value there: https://github.com/GNOME/pygobject/blob/7c4674f37efdc827d16d24bad7ff7e2704bd83ca/gi/overrides/Pango.py#L50

**Comment by nijel** [comment]
Actually what you need is `python3-gobject-Gdk`, it's just a bit strange SUSE packaging of pygobject...

**Comment by scarabeusiv** [comment]
Ah, okay, will test it out, it will take a bit to build...

**Comment by scarabeusiv** [comment]
Works now, so indeed the missing dep was the culprit.
Closing as it was my screwup :)
