### ISSUE TITLE
Allow to increase the limit of 200 characters length for components filemask/template

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#2902]
**Is your feature request related to a problem? Please describe.**
We use Weblate in the project [XWiki](https://github.com/xwiki/xwiki-platform) with some custom scripts to be able to manage various kind of resource files that exists in Maven submodules.
The problem is that 200 characters is to limited for the hierarchy of submodules we now have, for example I recently tried to add the following filemask: 
`.translation/xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-ui/src/main/resources/XWiki/Authentication/Translations_*.properties` which is 203 characters long.

This limitation also apply on the template path, see:
`.translation/xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-ui/src/main/resources/XWiki/Authentication/Translations_en.properties`. 

**Describe the solution you'd like**
We already patched the database to increase the size of filemask/template columns, but the maxlength put in the Django model (https://github.com/WeblateOrg/weblate/blob/master/weblate/trans/models/component.py#L238) still prevents to call `import_json` with such paths.
It would be nice to have a way to configure this limitation. 

**Describe alternatives you've considered**
As said we already patched the DB. I also edited the linked component.py file in my own instance to put 400 instead of 200 as maxlength. So far I didn't notice any issue with doing that, but I guess I'll need to do it at each upgrade which is not nice.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by surli** [comment]
Great! Thanks for the very quick fix :) :+1:
