### ISSUE TITLE
Allow to hide addon alerts for normal and anonymous users

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#2905]
**Is your feature request related to a problem? Please describe.**
We use some custom addons in our Weblate instance and it just happened that I had a bug with one of them. I discovered when reaching the instance that the alert about this issue was available by an anonymous user and was leaking some information about the system. (cf screenshot)

**Describe the solution you'd like**
I don't think in my case it could be used for an attack, but for safety I think it would be better that those alerts to be only displayed to the admins. Or at least to give the possibility to hide them for regular/anonymous users.

**Describe alternatives you've considered**
Just hiding the alerts for anonymous users could be a first start I guess.

**Additional context**
![Capture d’écran_2019-07-24_16-02-26](https://user-images.githubusercontent.com/1478232/61800628-a7979000-ae2d-11e9-88f3-6deac664f004.png)

**Comment by nijel** [comment]
Hiding from anonymous users sounds okay. I'm not so sure with hiding from regular users - the alerts typically indicate that something is wrong with the setup and that might be interesting to know to translators.

**Comment by surli** [comment]
ok to change it only for anonymous users then.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
