### ISSUE TITLE
Copying source in Zen mode does not save translated string

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2906]
Find a string in Zen mode
Click copy
Click anywhere else, or tab.
String is not saved.

Not sure if this only happens if it is the last string in a translation, but I am pretty sure it happens anyway.

Getting into regular mode copying, clearing dulication errors and clicking save there works.

An alternative way in Zen mode is saving the string as something else, and then saving it as the duplicated text.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
