### ISSUE TITLE
Show component alerts on project level

### ISSUE THREAD

**Issue by BhaaLseN** [WeblateOrg/weblate#2908]
**Is your feature request related to a problem? Please describe.**
Alerts are a nice way to see when things go wrong, such as a merge conflict that happens in one of the components of a project (due to non-automated changes by developers conflicting with the automated changes as result of a translation).
However, those only show up on the component; looking at the project list everything seems fine.

**Describe the solution you'd like**
I'd like to see the alert symbol pushed up (and aggregated, if necessary) to the project list as well - that means any project that has at least one alert in one of its components should show the alert symbol as well.
That way, we can just look at the project list and identify projects that need to be looked at (rather than clicking through all projects in the hopes of finding a component that has an alert).

**Describe alternatives you've considered**
Particularly for the mentioned merge issues, there is the "Repository Status" list in the administration section. However, not all users (or rather, people responsible for certain projects) are Weblate administrators; so they cannot immediately use that as indication.

**Additional context**
This alert on the component:
![image](https://user-images.githubusercontent.com/826052/61876268-c577fa00-aeec-11e9-8ddc-b278a3b08490.png)
...isn't visible in the project list:
![image](https://user-images.githubusercontent.com/826052/61876410-17208480-aeed-11e9-8f69-a8b099a4cd62.png)

**Comment by nijel** [comment]
Good point, they are not there as those are per component, but we could indeed aggregate this.

**Comment by nijel** [comment]
In case somebody wants to dig into this (what should be quite easy):

The logic is here:

https://github.com/WeblateOrg/weblate/blob/e2d60e8b7dd828fa1a86b635bde8ececb4781003/weblate/trans/templatetags/translations.py#L778-L791

And the template

https://github.com/WeblateOrg/weblate/blob/e2d60e8b7dd828fa1a86b635bde8ececb4781003/weblate/templates/trans/embed-alert.html#L1-L21

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
