### ISSUE TITLE
%-encapsuled placeholders followed by % split into two

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2910]
https://hosted.weblate.org/translate/weblate/website/nb_NO/?checksum=42cade7105073ee2

Says Save %(percent)s%%
And the string is "Save *%"

What happens is there are actually two placeholders
"%(percent)s" and "%%"
when there should be only one
"%(percent)s%"

**Comment by nijel** [comment]
This:

```python
>>> "%(percent)s%" % {'percent': 99}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: incomplete format
```

Also see https://docs.python.org/2.7/library/stdtypes.html#string-formatting
