### ISSUE TITLE
Question: source string replacement

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#2911]
Hello,

the same way we have statistics to tell the amount of word translated per day for translators, do we have a way to get similar information for source string replacement and addition over time?

I would like to have an idea of the percentage of changes in source string. I feel like it's about 10 percent of the string that changes every year, but that's a wild guess.

This isn't a feature request, just a request for personal research purposes.

Thanks a lot for your help!

**Comment by nijel** [comment]
You probably could dig this up from the `Change` objects, not sure if this worth exposing as reporting.

Something like this should give you idea:

```
Change.objects.filter(action=Change.ACTION_NEW_SOURCE, component__project__slug='project', component__slug='component', timestamp__gt=datetime(2019, 1, 1))
```

**Comment by Jibec** [comment]
Le 2019-07-29 15:38, Michal Čihař a écrit :
> You probably could dig this up from the Change objects, not sure if
> this worth exposing as reporting.

Thank you really much Michal, but I was wondering what is the result on 
hosted.weblate.org ?

**Comment by nijel** [comment]
Sorry, I currently do not have time to produce meaningful stats (it needs to exclude initial strings import and do this per component based on it's creation date).
