### ISSUE TITLE
Cannot manage repository from UI with "0 error" message

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#2915]
**Describe the bug**
Trying to manage the repository of a specific component, and get the following message in the UI, without any option for managing the repository:
> Error while loading page: 0 error

**To Reproduce**
I don't know how to reproduce it.

**Expected behavior**
I should be able to get access to the manage repository interface.

**Screenshots**
![weblate-error](https://user-images.githubusercontent.com/1478232/62042679-f31bb680-b1fe-11e9-9240-b3d27180512c.png)

**Server configuration and status**
```
 * Weblate 3.7.1
 * Python 2.7.9
 * Django 1.11.13
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.4.0
 * translation-finder 1.6
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 5.1.0
 * python-dateutil 2.7.2
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * diff-match-patch 20121119
 * pytz 2018.4
 * pyuca 1.2
 * ruamel.yaml 0.15.100
 * hub 2.3.0-pre10-136-g1e5bb95
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.9.0-9-amd64 (x86_64)
```

Check deploy:
```
SystemCheckError: System check identified some issues:

ERRORS:
?: (weblate.W023) Please upgrade your installation to Python 3. Python 2 support will be dropped in Weblate 4.0 currently sheduled on April 2020.
	HINT: https://docs.weblate.org/en/weblate-3.7.1/admin/updare.html#py3

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (weblate.W025.ass) Failure in loading handler for ass file format: gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-3.7.1/admin/install.html#optional-deps
?: (weblate.W025.srt) Failure in loading handler for srt file format: gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-3.7.1/admin/install.html#optional-deps
?: (weblate.W025.ssa) Failure in loading handler for ssa file format: gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-3.7.1/admin/install.html#optional-deps
?: (weblate.W025.sub) Failure in loading handler for sub file format: gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-3.7.1/admin/install.html#optional-deps

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.7.1/admin/install.html#collecting-errors
```

**Additional context**

I was checking this particular component because I received a notification for a new language and I didn't noticed a pull request for the translation. I  checked on the server and the commit was correctly performed, and the repository looks ok, so I don't think it could be a configuration problem. 
I tried to restart weblate job to see if it could internally reset some wrong state but it didn't change anything.
I also checked my other components and they looked ok.
Moreover I usually get an email in case of python error, and I checked the different logs (celery, redis, weblate) and I don't find anything weird related to that component.
I'm a bit stuck here and the error is not really explicit... 
[EDIT: Apparently we finally got the pull request with the changes, after the restart of weblate, so it might have been useful, but I still got the same issue when I try to get access to the Repository UI of this component]

**Comment by nijel** [comment]
Can you please open browser developer tools (F12 in most browsers) and check the request this does (it's request to `/js/git/PROJECT/COMPONENT/`). Does it return any content? Does it fail with some error?

**Comment by surli** [comment]
So I just checked with a clear cache refresh (ctrl+shift+r) and for this component apparently it never make the request to `/js/git/xwiki-contrib/piwik-application`.
![Capture d’écran_2019-07-29_14-54-24](https://user-images.githubusercontent.com/1478232/62050173-16e7f800-b211-11e9-94ce-8377352e912f.png)

If I got to a manually crafter URL to `/js/git/xwiki-contrib/piwik-application` I got the right content: no error to get the request.

I also checked with another component, and I see the request being performed:
![Capture d’écran_2019-07-29_14-58-04](https://user-images.githubusercontent.com/1478232/62050301-4ac31d80-b211-11e9-83e6-09dc55de2ea0.png)

**Comment by nijel** [comment]
Any errors in the console? It looks like the request was aborted for some reason by browser.

**Comment by surli** [comment]
I haven't noticed before, but there is indeed a console error: 
> Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). piwik-application:1:1

![Capture d’écran_2019-07-29_15-37-47](https://user-images.githubusercontent.com/1478232/62052941-dee3b380-b216-11e9-8fb0-e60c46dde7a5.png)

**Comment by surli** [comment]
Update: apparently I got the error only on Firefox (68.0.1). I just checked on Chromium and I don't get any error.

**Comment by nijel** [comment]
If you can apply https://github.com/WeblateOrg/weblate/commit/623f44c8995b4286e495801db42c142622279600, it should give better error message.

**Comment by surli** [comment]
> If you can apply 623f44c, it should give better error message.

so I just gave it a try. First I got the following error when I applying https://github.com/WeblateOrg/weblate/commit/623f44c8995b4286e495801db42c142622279600
> ReferenceError: responseText is not defined

so I changed a bit the code to use `xhr.responseText` instead of `responseText` and then I got:
> Error while loading page: error (0): undefined

On another side, I investigated a bit on the error and apparently the console error is a Firefox warning related to the Content-Security-Policy. Somehow the content is blocked on firefox and not on chrome.

**Comment by nijel** [comment]
Oops, it should be only `response`.

The CSP error seems to be related to Piwik. Are you using our [Piwik integration](https://docs.weblate.org/en/latest/admin/config.html#piwik-site-id) or you did that manually? With patching the files, you will have to patch CSP headers as well. But I don't think it's related to this issue (that's why I didn't comment it above).

**Comment by surli** [comment]
> The CSP error seems to be related to Piwik. 

ahahah thanks! I forgot about that, so for the story it's not at all related to your Piwik integration, we actually have a XWiki module ourselves for Piwik integration inside XWiki, and it's the component for translating this module. However, and here it becomes funny I'm using uBlock origin in Firefox and it blocks requests from Piwik... actually here it just parsed the request and saw "piwik" in the name and it was enough to block it... I just disabled it and everything's fine... 

I really hate those kind of bug. Anyway, sorry for the time lost here, and thanks a lot for helping!
