### ISSUE TITLE
GIF format screenshots

### ISSUE THREAD

**Issue by Kyuuu** [WeblateOrg/weblate#2924]
**Is your feature request related to a problem? Please describe.**
I wanted to add an animated game description's thumbnails to translate by translators but... I can't.

**Describe the solution you'd like**
Possibility to attach GIF pictures as screenshots.

**Describe alternatives you've considered**
//

**Additional context**
//

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
