### ISSUE TITLE
Could not parse translation base .Net resource file if there is no strings in it

### ISSUE THREAD

**Issue by mvodnev** [WeblateOrg/weblate#2927]
**Describe the bug**
Unable to save linked components' settings if in resource file that is specified as "Monolingual base language file" there is no strings. File type is ".Net resource file" and it has no errors in its structure (it's valid RESX-file).

**To Reproduce**
1. Have linked component (I don't know if this problem is actual for direct components) which base file doesn't contain any strings.
2. Open components' settings and click "Save" button. After this there will be an error message in "Files" tab and components' settings isn't saved.

**Expected behavior**
Components' settings is saved without any errors.

**Server configuration and status**
 * Weblate 3.7.1
 * Python 3.7.3
 * Django 2.2.3
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.6
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.20.1
 * Pillow 5.4.1
 * python-dateutil 2.8.0
 * lxml 4.3.2
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.9.4
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20121119
 * pytz 2019.1
 * pyuca 1.2
 * ruamel.yaml 0.15.99
 * tesserocr 2.4.0
 * Mercurial 4.8.2
 * git-svn 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.gmail.com
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.15.0-54-generic (x86_64)

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.7.1/admin/install.html#collecting-errors

**Additional context**

**Comment by nijel** [comment]
Weblate indeed does reject empty files. The reason is that library we use for parsing the files is not really checking file syntax in several formats and it parses completely invalid files as empty.

This check probably should be done only on file formats known to be broken and this should be fixed upstream to remove need for such checks in future.

**Comment by nijel** [comment]
Fix for Gettext PO parser is here: https://github.com/translate/translate/pull/3912

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
