### ISSUE TITLE
Install addons"Cleanup translation files". It will throw FileNotFoundError

### ISSUE THREAD

**Issue by Pinkuburu** [WeblateOrg/weblate#2929]
**Describe the bug**
When I install addons"Cleanup translation files". It will throw **FileNotFoundError**

**To Reproduce**
1. Go to Component 'g_t_t'
2. Click on "Manage"-----"Addons"-------Install "Cleanup translation files"
3. See error

Not every component that installs the plug-in will report an error; only this one will. This file exists in my VCS.
![image](https://user-images.githubusercontent.com/4962790/62363478-06f25000-b552-11e9-839d-aff2da5ac0aa.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/4962790/62363058-f2618800-b550-11e9-89be-5dd7a84d1ab3.png)

**Server configuration and status**
 * Weblate 3.6.1
 * Python 3.7.3rc1
 * Django 2.2.1
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.3.1
 * translation-finder 1.5
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.20.1
 * Pillow 5.4.1
 * python-dateutil 2.8.0
 * lxml 4.3.2
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.9.4
 * user-agents 2.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2019.1
 * pyuca 1.2
 * PyYAML 3.13
 * tesserocr 2.4.0
 * Mercurial 4.8.2
 * git-svn 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.4.0-132-generic (x86_64)

System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.6.1/admin/install.html#collecting-errors

**Additional context**
Traceback 
Environment:

Request Method: POST
Request URL: https://example.com:8081/addons/GTable/g_t_t/

Django Version: 2.2.1
Python Version: 3.7.3
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin.apps.SimpleAdminConfig',
 'django.contrib.admindocs',
 'django.contrib.sitemaps',
 'social_django',
 'crispy_forms',
 'compressor',
 'rest_framework',
 'rest_framework.authtoken',
 'weblate.addons',
 'weblate.auth',
 'weblate.checks',
 'weblate.formats',
 'weblate.machinery',
 'weblate.trans',
 'weblate.lang',
 'weblate.langdata',
 'weblate.memory',
 'weblate.screenshots',
 'weblate.accounts',
 'weblate.utils',
 'weblate.vcs',
 'weblate.wladmin',
 'weblate',
 'weblate.gitexport']
Installed Middleware:
['weblate.middleware.ProxyMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'weblate.accounts.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'weblate.accounts.middleware.RequireLoginMiddleware',
 'weblate.middleware.SecurityMiddleware']

Traceback:

File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.7/dist-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)

File "/usr/local/lib/python3.7/dist-packages/django/views/generic/base.py" in dispatch
  97.         return handler(request, *args, **kwargs)

File "/usr/local/lib/python3.7/dist-packages/weblate/addons/views.py" in post
  90.             addon.create(component)

File "/usr/local/lib/python3.7/dist-packages/weblate/addons/base.py" in create
  81.         result.post_configure()

File "/usr/local/lib/python3.7/dist-packages/weblate/addons/base.py" in post_configure
  126.                 self.post_update(component, '')

File "/usr/local/lib/python3.7/dist-packages/weblate/addons/base.py" in post_update
  247.         self.update_translations(component, previous_head)

File "/usr/local/lib/python3.7/dist-packages/weblate/addons/cleanup.py" in update_translations
  182.                 self.update_units(index, translation, translation.store.store)

File "/usr/local/lib/python3.7/dist-packages/weblate/addons/cleanup.py" in update_units
  86.             storage.save()

File "/usr/local/lib/python3.7/dist-packages/translate/storage/base.py" in save
  876.                 fileobj = open(self.filename, 'wb')

Exception Type: FileNotFoundError at /addons/GFTable/gun_tag_type/
Exception Value: [Errno 2] No such file or directory: ''

**Comment by Pinkuburu** [comment]
When I refresh the page, it will show that the addons have been installed, but I don't know f it works.
 
![image](https://user-images.githubusercontent.com/4962790/62363658-5c2e6180-b552-11e9-8d4d-24b09af94859.png)

**Comment by nijel** [comment]
No the addon will not work, it will probably crash every time. Can you please provide more info on the failing components? What file format are they using? Anything else specific on those?

**Comment by Pinkuburu** [comment]
[Files.zip](https://github.com/WeblateOrg/weblate/files/3460981/Files.zip)
The file is csv,utf-8

**Comment by Pinkuburu** [comment]
please download the files.zip, thank you

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
