### ISSUE TITLE
Question: Possibility of comparing 2 files with translations

### ISSUE THREAD

**Issue by eugenfriedrich** [WeblateOrg/weblate#2930]
Hey, i'll try to describe my issue. 
The company I am working for delivers its products in german and in english language. For that, we are using 2 files where all language-keys are listed. The devs don't have to translate anything. They just add the language-key in the source code. 
Now we don't want to look for the right key by hand. 
Is there any possibility to upload both files in weblate and then let weblate compare those files. 
It would be nice if weblate would tell me, if there are any keys that are not yet translated. Or maybe german keys that are not available in english. 

Thanks for your help

**Comment by nijel** [comment]
Maybe I'm missing something, but Weblate does this automatically when the translation is configured as monolingual. See docs for more info: https://docs.weblate.org/en/latest/formats.html#bimono
