### ISSUE TITLE
Possibility to see non-translated source characters and words amount

### ISSUE THREAD

**Issue by Kyuuu** [WeblateOrg/weblate#2931]
**Is your feature request related to a problem? Please describe.**
I need to know how many source characters and words are non-translated in full project/selected components for the chosen language. (I have to use another program for it atm)

//In Poland most of the translators check characters amount instead of words. In Asia words amount.

**Describe the solution you'd like**
Possibility to see/export amount of non-translated characters and words of the source language in project/selected components.

**Describe alternatives you've considered**
//

**Additional context**
It would be nice if could also do this with other languages, used as sources, since someone might be translating English/Spanish for example.

**Comment by nijel** [comment]
You can already get strings and words stats from Insights / Download statistics, the chars stats are currently not there, but should be easy to add.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by Kyuuu** [comment]
Has it stopped working?
![image](https://user-images.githubusercontent.com/33127074/77158666-105e0780-6aa4-11ea-956a-29a8a8c54919.png)

**Comment by nijel** [comment]
@Kyuuu No, you are just looking somewhere else. It was added to the info tab, not sure where you are looking, but definitely elsewhere. Please open separate issue for that.

**Comment by Kyuuu** [comment]
Okay, I will!

However I do not see it in info tab
![image](https://user-images.githubusercontent.com/33127074/77160523-c2e39980-6aa7-11ea-8c2c-da99319b5d65.png)

(I looked for it last time ~2 months ago but now I cannot find it anywhere. Shouldn't it be here? http://translation.frozendistrict.com/weblate/languages/en_GB/house-flipper-1/#information)

**Comment by nijel** [comment]
It's here: http://translation.frozendistrict.com/weblate/projects/house-flipper-1/achievements/en_GB/#stats
