### ISSUE TITLE
Priority flag

### ISSUE THREAD

**Issue by jnavila** [WeblateOrg/weblate#2940]
**Is your feature request related to a problem? Please describe.**
We are using po files to translate a series of manpages. I'd like to help translator translate most viewed text by directing them to the translation of selected source files. Now, the translation is managed in the order of the po file which is alphabetical only.

**Describe the solution you'd like**
It would be great if we could provide a drop-down list of source files names, and when selecting one name, only have the strings from this file available for further processing (untranslated, fuzzy...).

I think it would also be useful for software translations too where the most viewed strings in the sofware could be translated in priority. This is a good way to provide positive feed-back to translators, when their work is quickly visible, even if not complete.

**Describe alternatives you've considered**
Another choice would be to split the files into multiple po files, but that would have a few drawbacks, firstly because the script would require to merge back things when generating the output, with chances of conflicts.

There might be some simpler solutions, but I'm not aware of them.

**Additional context**

This is a special context of documentation translation.

**Comment by nijel** [comment]
Related to https://github.com/WeblateOrg/weblate/issues/2455 (though the prioritization is different there).

What you can do right now is adjust string priorities and high priority strings will be shown first. If it's few strings it's doable, but it won't scale for hundredths of strings.

**Comment by jnavila** [comment]
I wasn't aware of priority. Can this priority index be injected in the po file before-hand? If yes, then, I can already do it by script.

**Comment by jnavila** [comment]
Replying to myself, the [flags are mostly used for checks](https://docs.weblate.org/en/latest/admin/checks.html) .

**Comment by nijel** [comment]
No, but that's actually good idea to use flags for that. It would make it behave consistent with other features.

**Comment by nijel** [comment]
Thank you for your report, I've just implemented feature to parse priority from the flags.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
