### ISSUE TITLE
Missing dependency for setuptools >= 40.8.0

### ISSUE THREAD

**Issue by Flohack74** [WeblateOrg/weblate#2953]
Hi there,

just upgraded to Weblate 3.7.1 - A small blocker was various errors during compilation of dependencies, and it turned out that setuptools must be 40.8.0 in order to have it working. Can this be included in the dependencies file?

**Comment by nijel** [comment]
What exactly did break? I don't think Weblate itself is using anything specific from that version, so it's more likely missing in some of the deps....
