### ISSUE TITLE
Repeatedly adding extra rows with empty string

### ISSUE THREAD

**Issue by SlavekB** [WeblateOrg/weblate#2954]
**Describe the bug**
When generating a new PO file for pushing into the git repository, for unknown reasons, rows with empty strings are added again and again.

**To Reproduce**
There is no particular procedure for reproduction, as this is not a problem caused by user steps.

**Expected behavior**
The expected result is that unnecessary empty string rows will not be added.

**Screenshots**
https://mirror.git.trinitydesktop.org/gitea/TDE/tde-i18n/commit/322f9ed46a
https://mirror.git.trinitydesktop.org/gitea/TDE/tde-i18n/commit/87550fcf19
https://mirror.git.trinitydesktop.org/gitea/TDE/tde-i18n/commit/a9539ab86d
https://mirror.git.trinitydesktop.org/gitea/TDE/tde-i18n/commit/a952042487
https://mirror.git.trinitydesktop.org/gitea/TDE/tde-i18n/commit/c2aa37fb9a

**Server configuration and status**
The difference from official 3.7.1 is that I have backported patches related to Issue #2813.
```
 * Weblate 3.7.1
 * Python 3.5.3
 * Django 1.11.20
 * Celery 4.2.2
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.1.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.1
 * translate-toolkit 2.4.0
 * translation-finder 1.6
 * Whoosh 2.7.0
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 4.0.0
 * python-dateutil 2.5.3
 * lxml 4.2.5
 * django-crispy-forms 1.6.1
 * django_compressor 2.2
 * djangorestframework 3.9.2
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2016.7
 * pyuca 1.1.2
 * ruamel.yaml 0.15.97
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django_sendmail_backend.backends.EmailBackend: localhost
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 3.16.6-042stab138.42 (x86_64)
```
```
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.7.1/admin/install.html#collecting-errors

System check identified 1 issue (0 silenced).
```

**Comment by nijel** [comment]
Bug in the translate-toolkit, it seems to do this on msgid comments.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has proposed fix here: https://github.com/translate/translate/pull/3916

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by SlavekB** [comment]
Commit from the related project I have backported, celery daemons restarted, but pushing today's changes has caused the same problem again. See
https://mirror.git.trinitydesktop.org/gitea/TDE/tde-i18n/commit/2cbf3d3c9f

**Comment by nijel** [comment]
Are you sure you patched it correctly? In my testing it does work even in your case.

**Comment by SlavekB** [comment]
Oh, my fault. I cloned upstream and therefore the git show couldn't give me the right patch. The second attempt hopefully will be more successful :smiley_cat:

Thank you!

**Comment by SlavekB** [comment]
I can confirm that with the correct commit, extra rows with empty strings have been nicely removed.

https://mirror.git.trinitydesktop.org/gitea/TDE/tde-i18n/commit/7bfa3b216b

Thank you!
