### ISSUE TITLE
change LANGUAGE_CODE in settings.py

### ISSUE THREAD

**Issue by bfdxyou** [WeblateOrg/weblate#2955]
when i change LANGUAGE_CODE = 'zh-hans' , restart the weblate host, the host still in english

Request URL: http://localhost:8000/js/i18n/

Content-Language: en

**Comment by bfdxyou** [comment]
weblate 3.7.1
python 3.5.2
Django 1.11

**Comment by nijel** [comment]
The language is set in the session, so you need to clear cookies or logout. Also there is language preference in the profile, which overrides this.

**Comment by bfdxyou** [comment]
Thank you for your reply. It's overrides in language preference,thank you.
