### ISSUE TITLE
Commit with another user

### ISSUE THREAD

**Issue by lusu007** [WeblateOrg/weblate#2957]
**Is your feature request related to a problem? Please describe.**
I want to push my translations to GitLab via another user and not the user im logged in with.

**Additional context**
We are using Weblate in our project for translating our messages. We want to push changes on Weblate immediatly to our Repository on GitLab. Is there a way to change the user wich commits and pushes Weblate changes?

**Comment by nijel** [comment]
You can change your name and email in Weblate to whatever you want. You can set committer name in [component configuration](https://docs.weblate.org/en/latest/admin/projects.html#component-configuration). If you don't care about authorship information at all, you can [squash all commits](https://docs.weblate.org/en/latest/admin/addons.html#squash-git-commits).

**Comment by lusu007** [comment]
Where can I set the commiter name and email adress?
I can't find it in my translation component settings.

**Comment by nijel** [comment]
It's currently only in the admin interface because there is no verification of used email addresses.

**Comment by lusu007** [comment]
Oh okay. I found it. Thank you 😄
