### ISSUE TITLE
Comment mention autosuggestion

### ISSUE THREAD

**Issue by Kyuuu** [WeblateOrg/weblate#2964]
**Is your feature request related to a problem? Please describe.**
When mentioning someone in the comments section it would be helpful to be able to type and select them using a handle, similar to the system used in Discord.

**Describe the solution you'd like**
![mention](https://user-images.githubusercontent.com/33127074/63140163-35a40800-bfe1-11e9-8295-056385f8b696.png)

**Describe alternatives you've considered**
//

**Additional context**
//

**Comment by JanStevcik** [comment]
Hi, can I do this issue?

**Comment by nijel** [comment]
Yes, you're welcome to do that.

**Comment by rhofer** [comment]
> When mentioning someone in the comments section it would be helpful to be able to type and select them using a handle, similar to the system used in Discord.

... or similar to github or gitlab when mentioning somebody in e.g. this issue here.

Especially, when social authentication is activated (e.g. via auth0), and e.g. two users are registering with the same first name, this results into:
- USERNAME 1: `Martin`
- USERNAME 2: `Martina31bb7cecc0b442c`

In the second case, there is no chance to remember the user name, hence autosuggestion is kind of a must.

**Comment by nijel** [comment]
@SaptakS When touching the editor, please keep in mind that we want more features there in future. 

Related issues I've remembered now: 

* https://github.com/WeblateOrg/weblate/issues/3504 - placeables support
* https://github.com/WeblateOrg/weblate/issues/1930 - whitespace highlighting
* https://github.com/WeblateOrg/weblate/issues/2856#issuecomment-513137804 - ICU messageformat editor, something similar will be needed for Fluent as well (https://github.com/WeblateOrg/weblate/issues/1926)

**Comment by nijel** [comment]
This could probably use the /api/users/.  It should be exteded to support this use case. The django_filters can be added to add filtering and add support for making the API call by non superusers by filtering the available fields to them (probably just username and full_name should be exposed in this case).
