### ISSUE TITLE
Automatic translation with source Machine translation "Weblate" runs in server time-out

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#2965]
**Describe the bug**
Having a component and applying *Automatic translation* with source *Machine translation - Weblate* (weblate internal machine), fuzzy match (Score threshold) set to 75, runs into server time out *504 Gateway Time-out -- Ther server didn't respond in time.*
- Target component has about 550 strings for a specific language
- Weblate machine has a pool of about 30'000 strings for this language, provided from other components

**Cross check**
Reducing Target component to about 10 strings, rest remains same as above, works properly.

**To Reproduce**
1. Go to component, select target language (e.g. `fr`)
2. Click on 'Tools -> Automatic translation'
3. Settings: 
  - `Search filter : Not translated strings`
  - `Automatic translation source : Machine translation`
  - `Machine translation engines : Weblate`
  - `Score threshold : 75`
4. Click on `Process`
5. See error

**Expected behavior**
No server time-out happens.

**Solution Idea**
On click `Process`, the UI switches to a `In Progress` dialogue in context of the current language, e.g. with progress bar and/or busy indicator, whilst machine translation happens asynchronously in the background. Maybe, during this happens, the current language is locked for editing.

Might be similar to #372 , but in context of `Automatic translation`

**Comment by nijel** [comment]
Indeed this operation can take some time. What timeout do you have set for wsgi? In example configuration we recommend quite high values to avoid this:

https://github.com/WeblateOrg/weblate/blob/dd38563a95b2de023ff1d807773b10cadcc0c237/weblate/examples/weblate.nginx.conf#L33

**Comment by nijel** [comment]
Related to #2541

**Comment by rhofer** [comment]
Tested with docker image 3.9.1-1. This is working fine. @nijel many thanks for the fix.

**Comment by rhofer** [comment]
@nijel question: when starting automatic translation, the UI returns to component view showing the progress bar. Appearingly, when navigating off the component and then back to it, the progress bar isn't there anymore. Does this mean that the automatic translation procedure is stopped / aborted?
Is it then required to simply stay in the component view and not changing anything?

**Comment by nijel** [comment]
No it runs regardless the progressbar, no need to stay on the page.
