### ISSUE TITLE
Customization in an easy way via the admin website

### ISSUE THREAD

**Issue by Kyuuu** [WeblateOrg/weblate#2968]
**Is your feature request related to a problem? Please describe.**
I wanted to change my Weblate page to a Frozen themed one. I'd quite like it and it would suit my projects more.

**Describe the solution you'd like**
I would like to be able to change it in an easy way via the admin website. There should be a category for customizations like that:
![customization](https://user-images.githubusercontent.com/33127074/63412217-8cea1400-c3f7-11e9-92a0-693c93ab42f9.png)

Selecting a color theme similar to Blogger:
![theme](https://user-images.githubusercontent.com/33127074/63412248-9f644d80-c3f7-11e9-869b-64006a6686e1.png)

**Describe alternatives you've considered**
//

**Additional context**
Color theme changing could possibly be a bonus option for subscribers/donators.

**Comment by PunchyRascal** [comment]
It would also be nice to be able to upload a custom CSS altogether maybe?

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/customize.html for some info on customizing (though it's not an UI approach).

**Comment by PunchyRascal** [comment]
Thanks, I noticed that. I was however looking for a more light-weight option as I don't have the installation under complete control - just registering my voice for this feature request I guess..
