### ISSUE TITLE
Weblate: command not found

### ISSUE THREAD

**Issue by maicol07** [WeblateOrg/weblate#2970]
**Describe the bug**
I'm trying to install Weblate using pip (following the docs) but when I do `weblate migrate` it shows:
```
$ weblate migrate
weblate: command not found 
```

**To Reproduce**
1. Follow the [docs](https://docs.weblate.org/en/latest/admin/install/venv-debian.html)

**Expected behavior**
Command works as expected by the docs

**Comment by nijel** [comment]
You probably need to add `~/.local/bin` to `PATH` see https://github.com/pypa/pip/issues/3813.

**Comment by nijel** [comment]
Hmm, but when using virtualenv it should be already there, you need to activate it. I will clarify docs.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
