### ISSUE TITLE
Import translation without "Needs editing"

### ISSUE THREAD

**Issue by pokoli** [WeblateOrg/weblate#2973]
My issue is a feature request related to translation import. 

Currently when importing a po file the only options available are: 

* Import as needs review
* Import as sugest
* Import as needs editing

If the user has rights is a administrator for the language it should be possible to import all the file translations as definite translation and import them into weblate. 

For now the only solution is import as "Needs editing" and then manually uncheck the "Needs editing" of every translation which is unsable when the number of imported translation is quite big.

**Comment by nijel** [comment]
"Import as needs review" is what you actually want, it's just wrongly named.

**Comment by pokoli** [comment]
Wow, thanks for your fast reply!

I think changing the wording will fix it.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
