### ISSUE TITLE
Project / Language info improvement

### ISSUE THREAD

**Issue by Kyuuu** [WeblateOrg/weblate#2974]
**Is your feature request related to a problem? Please describe.**
It would be nice to improve this tab.

**Describe the solution you'd like**
In case I am in **/projects/projectName/#information**
![project-info](https://user-images.githubusercontent.com/33127074/63637911-612e8e80-c682-11e9-8527-86cee92a5b77.png)
- _Number of languages_ should go under _Translation license_
- Under _Number of words_ there should be _Number of chars_
- Under _Number of source words_ there should be _Number of source chars_

In case I am in **/languages/code/projectName/#information**
![language-info](https://user-images.githubusercontent.com/33127074/63638063-17df3e80-c684-11e9-8654-158e2d6ecbc2.png)
- There is no need to show _Number of languages_ here
- Useful information here would be:
-- _Number of translated strings_
-- _Number of translated words_
-- _Number of translated chars_
-- _Number of source strings_
-- _Number of source words_
-- _Number of source chars_
- If the user has selected a secondary language (more secondary languages = more records)
-- _Number of secondary language strings (languageName)_
-- _Number of secondary language words (languageName)_
-- _Number of secondary language chars (languageName)_

**Describe alternatives you've considered**
//

**Additional context**
Why do I need to see "secondary language" stats? Some translators may want to translate strings from a different language other than the source one.
Why do I need to see "(XYZ is not translated)"?  I need to send the number of source words/chars to translators (who then tell me how much it will cost me).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
