### ISSUE TITLE
How to increase translation limit?

### ISSUE THREAD

**Issue by desmax** [WeblateOrg/weblate#2975]
I see limit in 400 characters for translation field now, how could I increase that?

**Comment by nijel** [comment]
Thank you for your report, this is really missing in our documentation. I've just fixed that: https://docs.weblate.org/en/latest/user/translating.html#translated-string-length

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
