### ISSUE TITLE
Default automatic group assignments get restored, despite of deletion

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#2976]
As default gorup assignments, weblate provides:
- Users: regex `^.*$`
- Viewers: regex `^.*$`

For my special requirements, I deleted the auto assignment form Users and Viewers and created only one for my case, assigning to a group with a specific permission model in behind:
- SpecialUsersGroup: regex `Something specific and more complicated`

**Observation**
After a certain while, suddenly the auto assignment for Users and Viewers is back there (magically re-created). The assignment for SpecialUsersGoup remains unchanged (luckily).

**Expected behaviour**
Deleted auto assignments stay removed.

Weblate version 3.7 running on openshift

**Comment by rhofer** [comment]
Currently, it's hard to say when exactly this happens. I usually observe it, when a new user registers, that suddenly they are auto assigned to Users and Viewers, what has been deleted once.

**Comment by nijel** [comment]
This is documented behavior, in case you want to disable it, change the regex to not match anything.

26. srpna 2019 11:30:19 SELČ, Remy Hofer <notifications@github.com> napsal:
>As default gorup assignments, weblate provides:
>- Users: regex `^.*$`
>- Viewers: regex `^.*$`
>
>For my special requirements, I deleted the auto assignment form Users
>and Viewers and created only one for my case, assigning to a group with
>a specific permission model in behind:
>- SpecialUsersGroup: regex `Something specific and more complicated`
>
>**Observation**
>After a certain while, suddenly the auto assignment for Users and
>Viewers is back there (magically re-created). The assignment for
>SpecialUsersGoup remains unchanged (luckily).
>
>**Expected behaviour**
>Deleted auto assignments stay removed.
>
>Weblate version 3.7 running on openshift

**Comment by rhofer** [comment]
Yes, thanks, wasn't aware of this: `(?!.*)` solved my problem:

https://stackoverflow.com/questions/2930182/regex-to-not-match-any-characters

**Comment by nijel** [comment]
The recommended approach in our docs is to set it to match empty string `^$`, see https://docs.weblate.org/en/latest/admin/access.html#automatic-group-assignments. But anything like that will do the job.

**Comment by rhofer** [comment]
@nijel this would mean, that a user can never register without an email address entered. Is this enforced?

**Comment by nijel** [comment]
Yes, in on application logic and in database the email field is unique field.
