### ISSUE TITLE
Google Translate API v3

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2979]
**Is your feature request related to a problem? Please describe.**
There is new version of Google Translate API - [version 3](https://cloud.google.com/translate/docs/intro-to-v3).

The API itself is almost same, the biggest difference is that it does not support API keys:

> Cloud Translation v3 does not currently support API keys. We recommend that you create a service account for Cloud Translation v3beta1 requests. For information on creating a service account, see Creating and managing service accounts. Your service account must be added to one of the IAM roles added for Cloud Translation v3.

**Describe the solution you'd like**
Add support for this new authentication. Most likely by using [existing Python binding](https://pypi.org/project/google-cloud-translate/).

**Additional context**
The v3 API supports for customization of used MT model, what might be useful feature for many use cases.

**Comment by MetalDent** [comment]
Hi, is anyone working on this issue?

**Comment by msriv** [comment]
I can try to solve this issue...

**Comment by MetalDent** [comment]
This new version should go in the requirements or do we have a separate file for that?

**Comment by nijel** [comment]
Probably to requirements-optional.txt as that will needed only when the service will be enabled.

**Comment by Naruto0** [comment]
Should the version 3 api exist next to the former or should it replace it?

Regards

**Comment by nijel** [comment]
Both services have different credentials and billing, so probably v3 should be added as new service.
