### ISSUE TITLE
Provide data languages scheme based on programming languages

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#2980]
**Is your feature request related to a problem? Please describe.**
We are using Weblate for a Java project that is using the standard Java locales. However the language code defined in Weblate is not mapping the language codes defined in Java locales: for example, for the Chinese support, we have this for Java (extracted from https://www.oracle.com/technetwork/java/javase/java8locales-2095355.html):

```
Chinese (zh) | China (CN) |   | (Hans) | zh-CN |  
Chinese (zh) | Singapore (SG) |   | (Hans) | zh-SG(*) |  
Chinese (zh) | Hong Kong (HK) |   | (Hant) | zh-HK |  
Chinese (zh) | Taiwan (TW) |   | (Hant) | zh-TW
```

where Weblate have the following:
```
# Translators: Language name, ISO code: za
    ('za', _('Zhuang'), 2, 'n != 1'),
    # Translators: Language name, ISO code: zh_Hans
    ('zh_Hans', _('Chinese (Simplified)'), 1, '0'),
    # Translators: Language name, ISO code: zh_Hant
    ('zh_Hant', _('Chinese (Traditional)'), 1, '0'),
    # Translators: Language name, ISO code: zh_Hant_HK
    ('zh_Hant_HK', _('Chinese (Hong Kong)'), 1, '0'),
```

**Describe the solution you'd like**
It could be really useful to provide different schemes of languages, depending on the programming language and their own standard language code mapping.

**Describe alternatives you've considered**
For now we'll amend manually our list of languages from the admin, but it's a bit tedious.

**Comment by surli** [comment]
Moreover, it seems that we cannot edit an existing language from the admin: so we need to delete the wrong ones, and create new ones with the right codes. Which I guess also mean that we need to backup the plural rules associated to the languages to link them to the new Weblate language we'll add.

**Comment by nijel** [comment]
The Weblate internal language code doesn't have to match the ones used in the translated software. Weblate already maps that depending on platform. The only case where it might be problematic is when starting new translations within Weblate - we do support some platforms here, but this could certainly be extended, see https://docs.weblate.org/en/latest/formats.html#adding-new-translations

The admin interface should allow editing and I've just tested that it works fine for me. Do you get some error? Also if you're on 3.8 or newer, you can edit languages directly from Weblate.

**Comment by surli** [comment]
> The only case where it might be problematic is when starting new translations within Weblate

OK it was the case here. Actually we might have indeed seen a problem too fast, since we received an email for a new translation started for `zh_Hans` and when checking we discovered that this code wasn't supported... 

> Weblate already maps that depending on platform.

Where is this mapping available? I did not find it in the source. 

> The admin interface should allow editing and I've just tested that it works fine for me. Do you get some error? Also if you're on 3.8 or newer, you can edit languages directly from Weblate.

My bad, I wrongly checked the actions select from the admin interface, instead of clicking on the language...

**Comment by nijel** [comment]
Most of the logic is generic:

https://github.com/WeblateOrg/weblate/blob/a4fe11bddb65ed3dcbeb947269102cdb677aa025/weblate/lang/models.py#L166-L226

There is also hardcoded list of aliases:

https://github.com/WeblateOrg/weblate/blob/a4fe11bddb65ed3dcbeb947269102cdb677aa025/weblate/langdata/languages.py#L770-L1050

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed - I've added support for creating new languages in Java compatible way.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
