### ISSUE TITLE
django_auth_ldap,When a user logs in and prompts the account is inactive

### ISSUE THREAD

**Issue by bfdxyou** [WeblateOrg/weblate#2981]
LDAP user has email attribute, in settings.py when i don't include AUTH_LDAP_USER_FLAGS_BY_GROUP ,the LDAP user can log in 

user : cn=you,cn=PosixTest1,dc=example,dc=com

in settings.py 
AUTH_LDAP_BIND_DN="cn=admin,dc=example,dc=com"
AUTH_LDAP_BIND_PASSWORD="123456"
AUTH_LDAP_USER_SEARCH=LDAPSearchUnion(
LDAPSearch(" dc=example,dc=com", ldap.SCOPE_SUBTREE, "(cn=%(user)s%)"),
)

AUTH_LDAP_Group_SEARCH=LDAPSearchUnion(
LDAPSearch("cn=AdminGroup, dc=example,dc=com", ldap.SCOPE_SUBTREE, "(objectClass=groupOfNames)"),
LDAPSearch("cn=PosixTest, dc=example,dc=com", ldap.SCOPE_SUBTREE, "(objectClass=groupOfNames)"),
)

AUTH_LDAP_GROUP_TYPE=GroupOfNamesType(name_attr="cn")

AUTH_LDAP_USER_FLAGS_BY_GROUP={
"is_staff" : "cn=test, cn=PosixTest1, dc=example, dc=com",
"is_active": "cn=hong, cn=PosixTest1, dc=example, dc=com",
"is_superuser": "cn=adminCom1, cn=PosixTest1, dc=example, dc=com",
}

AUTH_LDAP_ALWAYS_UPDATE_USER=True
AUTH_LDAP_FIND_GROUP_PERMS=True

**Comment by bfdxyou** [comment]
when i use the user  in AUTH_LDAP_USER_FLAGS_BY_GROUP ,weblate/accounts/login/  prompts  this accounts is inactive.  i check the use name and password ,is correct.

**Comment by nijel** [comment]
The [AUTH_LDAP_USER_FLAGS_BY_GROUP](https://django-auth-ldap.readthedocs.io/en/latest/reference.html#auth-ldap-user-flags-by-group) tries to find all user attributes in LDAP. So in case the `is_active` is not present, it's set to False and user is considered inactive.

**Comment by bfdxyou** [comment]
change the user "test" is active, and not include AUTH_LDAP_USER_FLAGS_BY_GROUP, the user can log in.
if i change "is_active" ,i use the user"test" ,is always inactive.
AUTH_LDAP_USER_FLAGS_BY_GROUP={
"is_active" : (LDAPGroupQuery("cn=test, cn=PosixTest1, dc=example, dc=com")
                  |LDAPGroupQuery("cn=adminCom1, cn=AdminGroup, dc=example, dc=com")),
"is_staff" : "cn=test, cn=PosixTest1, dc=example, dc=com",
"is_superuser" : "cn=adminCom1, cn=AdminGroup, dc=example, dc=com",
}
