### ISSUE TITLE
Shared translation memory: separate usage and contribution permission

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#2983]
Weblate allows in project settings to *share translation memory* across projects:
![SharedTransMemory](https://user-images.githubusercontent.com/8058166/63944424-c662f500-ca71-11e9-8980-9d0fcaa9a792.PNG)

By using one Weblate instance, separation of concern can be achieved by separate projects. This may requires
- Project A allowed to contribute to cross TM only
- Project B allowed to use cross TM only
- Project C allowed to contribute to and use cross TM

**Request**
Separate combined setting into two separate settings
- [ ] Use shared translation memory between projects
- [ ] Contribute to shared translation memory between projects

**Comment by comradekingu** [comment]
@rhofer
Interesting. How and when is only being able to use the TM a legitimate concern?
AFAIK there is a special license in the Weblate EULA for TM, which means it is different from the project license, effectively dual-licensing everything.

**Comment by nijel** [comment]
This is (probably) not useful for Hosted Weblate, but for private instances it does have a use case.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by rhofer** [comment]
@nijel should this already be visible, e.g. when testing the current docker image weblate/weblate:edge ?

**Comment by nijel** [comment]
No, it's part of the 3.9 release (see the milestone set on this issue). It will be out next week.

**Comment by rhofer** [comment]
Tested with weblate 3.9.1-1 from hub.docker.com: (my) status: **Failed**

## Steps to reproduce

1. Created `Project 1` with settings
   - [x] Use shared translation memory
   - [x] Contribute to shared translation memory
1. Created `Project 2` with settings
   - [x] Use shared translation memory
   - [ ] Contribute to shared translation memory
1. Added `Component 1` to `Project 1`
1. Added `Component 2` to `Project 2`
1. Created `User 1`, assigned to `Group 1` with permission `Project selection: As defined > Projects: Project 1 (only)`
1. Created `User 2`, assigned to `Group 2` with permission `Project selection: As defined > Projects: Project 2 (only)`
1. Logged in with `User 1` and translate `Dog` to German `Hund 1`
1. Log-out and log-in with `User 2`, checking in `Component 2` > `German` for source `Dog`. Result: Tab `Machine translation` as well as tab `Translation memory` show proposal `Hund 1`. Works as expeced, status **Passed**
1. With `User 2` translate `Dog` to German `Hund 2`
1. Log-out and log-in with `User 1`, checking in `Component 1` > `German` for source `Dog`. Result: Tab `Machine translation` as well as tab `Translation memory` show proposal `Hund 2`. Expected: `Hund 2` does never appear as proposal as per current user's permissions and according project settings from `Project 2` to NOT contribute to shared TM. Status **Failed**

@nijel could you pleae re-open this issue and cross check (test) from your side and apply appropriate fix. (or did I miss something ?)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by rhofer** [comment]
Re-tested with weblate 3.9.1-3. Works as expected.
