### ISSUE TITLE
Package django-simple-open-graph missing in requirements.txt

### ISSUE THREAD

**Issue by BhaaLseN** [WeblateOrg/weblate#2989]
**Describe the bug**
After upgrading from 3.7.1 to 3.8, I've been getting 500 errors and associated log entries in my Apache log regarding 
```
django.urls.exceptions.NoReverseMatch: Reverse for 'og-image' not found. 'og-image' is not a valid view function or pattern name.
```

**To Reproduce**
1. Install Weblate 3.8 from Git
2. Run `pip install -r requirements.txt` as indicated by the docs.
3. Load any page that is intended to have an OpenGraph reference

**Expected behavior**
Everything should just work

**Server configuration and status**
```
$ ./manage.py list_versions
 * Weblate weblate-3.8
 * Python 3.7.3
 * Django 2.2.4
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.6
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.20.1
 * Pillow 6.1.0
 * python-dateutil 2.8.0
 * lxml 4.4.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.10.2
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20181111
 * ruamel.yaml 0.15.97
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache
 * Email setup: django.core.mail.backends.dummy.EmailBackend:
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.19.0-5-amd64 (x86_64)

$ ./manage.py check --deploy
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.8/admin/install.html#collecting-errors

System check identified 2 issues (1 silenced).
```
(note this is _after_ installing `django-simple-open-graph`; in case it matters the silenced check is `admin.E408`)

**Additional context**
To fix this, simply install the package `django-simple-open-graph`:
```
$ pip install django-simple-open-graph
```
This should probably be in `requirements.txt` so it is installed automatically.

**Comment by nijel** [comment]
`django-simple-open-graph` is certainly not needed. Maybe you just forgot to restart uwsgi after upgrade and the site was running new templates but old code?

**Comment by BhaaLseN** [comment]
Good question. It worked afterwards, so it is a bit hard to tell.

I just removed the package again and it still seems to work; so it might've been that.
(and it probably also explains why it was still showing 3.7.1 in the page footer; which I assumed to be a cache issue - now it certainly shows 3.8 though.)
