### ISSUE TITLE
Langauge Aliases apprear to be case sensitive

### ISSUE THREAD

**Issue by Blendify** [WeblateOrg/weblate#2990]
**Describe the bug**
In our repository our naming scheme for our Chinese po-files are `zh_CN.po` and `zh_TW.po` however weblate does not use these files when choosing `Chinese (Simplified)` or `Chinese (Traditional)` in the language drop down.

Having a look at https://github.com/WeblateOrg/weblate/blob/master/weblate/langdata/languages.py#L828-L831 I see correct aliases for this use case which makes me suspect that the aliases are case sensitive. 

**To Reproduce**
1. Import a repository containing `zh_CN.po` and `zh_TW.po` files
2. In the projects components attempt to add a new language 
3. Select either  `Chinese (Simplified)` or `Chinese (Traditional)` in the language drop down.

**Expected behavior**
Choosing  `Chinese (Simplified)` or `Chinese (Traditional)` in the language drop down. Should correctly use the `zh_CN.po` and `zh_TW.po` files.

**Comment by Blendify** [comment]
https://github.com/Blendify/bf-translations can be used as a test repository.

**Comment by nijel** [comment]
The lookup in aliases is case sensitive, it converts the string to lowercase first:

https://github.com/WeblateOrg/weblate/blob/4bf67e22b34788a87aec6cc5717c35de8e640259/weblate/lang/models.py#L149-L164

In case the translation file is there, it should be imported without need for adding it. If you add new language in Weblate, it's naming depends on format and setting, see https://docs.weblate.org/en/latest/formats.html#adding-new-translations

**Comment by Blendify** [comment]
It would appear that the languages are not being imported and instead weblate tries to create new files

**Comment by nijel** [comment]
Did you happen to disable [SIMPLIFY_LANGUAGES](https://docs.weblate.org/en/latest/admin/config.html#simplify-languages)?
