### ISSUE TITLE
No matching checks found!

### ISSUE THREAD

**Issue by leela52452** [WeblateOrg/weblate#2993]
link shows 89 for ellipsis on https://hosted.weblate.org/checks/?project=freeplane

however, when i click https://hosted.weblate.org/checks/ellipsis/?project=freeplane, it shows error "No matching checks found! "

**Comment by nijel** [comment]
Looks like some missing cleanup, I've just scheduled extra maintenance, it should fix it...

**Comment by nijel** [comment]
Seems fixed now. The cleanup was not done properly in past, what was fixed in ded3eebf0a0f0ecece54e437361e106e501d2df5.
