### ISSUE TITLE
Two copy buttons in the same interface do different things

### ISSUE THREAD

**Issue by fitojb** [WeblateOrg/weblate#2994]
In the translation interface, there are two Copy buttons, with a similar icon, but they do different things.

If I click the rightmost icon, which is green, the original string is copied to the clipboard. This is expected.

But if I click on the Copy button that is next to the special character buttons, then the original string is _transferred_ to the editable Translation field. This is a functionality that I appreciate a lot but it should be labelled better (“Fill with source”, maybe?), and with a clearer, more distinctive icon, perhaps including an arrow pointing down.

![image](https://user-images.githubusercontent.com/554953/64236553-3df4b200-cec0-11e9-908a-9d6f529fdd8a.png)
For the sake of comparison, here are Crowdin’s, Translatewiki’s and Pootle’s equivalent buttons:

* Crowdin’s “Copy Source” button: 
![image](https://user-images.githubusercontent.com/554953/64236999-181bdd00-cec1-11e9-9ab0-4d046067947b.png)
* Translatewiki’s “Paste source text” button:
![image](https://user-images.githubusercontent.com/554953/64237390-e35c5580-cec1-11e9-8e08-6222f2c75f5e.png)
* Pootle’s “Copy to translation” button:
![image](https://user-images.githubusercontent.com/554953/64237167-6fba4880-cec1-11e9-8ddf-fd8e70940cfe.png)

Both Lokalize and Transifex use a very similar icon to that of Weblate’s current 
![image](https://user-images.githubusercontent.com/554953/64237930-020f1c00-cec3-11e9-8dcb-0ba639a8d621.png) icon, but as they don’t offer any clipboard-copy functionality, the issue is non-existent.

**Comment by nijel** [comment]
I was worried about the confusion when adding the copy to clipboard feature, but in the end no differentiation was done. Suggestion on choosing icon from https://fontawesome.com/v4.7.0/icons/ are welcome.

**Comment by fitojb** [comment]
Thanks for your attention to this issue!

Oh, I see that the current icon is called `clone` by Font Awesome. It is a great name for this functionality but it’s a shame that they were so lazy as not to think of any different metaphor to disambiguate this action from `copy`. Oh well… 

That said, what about `angle-double-down`? I also thought of `paper-plane-o` and `arrow-circle-down`, but the former is too similar to Telegram’s logo and the latter is heavier and its lighter variant looks like it represents a download. Of course, `angle-double-down` will stop working if the UI is rearranged, but seems like it could best convey the idea of “transferring”, even if it looks a bit like a guillemet.

Even if the icon doesn’t end up changed, this bug could also be fixed by changing the label of the button: after seeing the Font Awesome name, I liked “Clone source”. WDYT?

**Comment by nijel** [comment]
I've changed the text in 2b60a0fcc4, not sure about the icon, I don't find others much better than the current one.

**Comment by fitojb** [comment]
Yeah, none seem to be a good fit :/

Thanks for the change!! :)
