### ISSUE TITLE
"gettext PO" shown twice in file download selection

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2997]
https://hosted.weblate.org/widgets/osmand/?lang=nb_NO&component=main
https://hosted.weblate.org/projects/osmand/main/sv/#download (etc)

![bilde](https://user-images.githubusercontent.com/13802408/64387534-951f9180-d03c-11e9-811a-20aaf52b89bf.png)

Edit: The bottom one links to `&type=all&format=mo` which isn't there. (https://www.gnu.org/software/gettext/manual/html_node/MO-Files.html)

**Comment by nijel** [comment]
The reason is that you have made wrong translation, see https://github.com/WeblateOrg/weblate/commit/0ac77228c8df1cd3f92575e3af4abda065998ae7#diff-97ad75089a236672c5f6920645fa47a4L1795

**Comment by nijel** [comment]
I've fixed the translation now: https://hosted.weblate.org/translate/weblate/master/nb_NO/?checksum=40166b5c7a6c4079
