### ISSUE TITLE
How to set custom logo and favicon with docker deployment?

### ISSUE THREAD

**Issue by romanr** [WeblateOrg/weblate#3000]
Where to place files to make them copied into container? Anythis has to be added to docker-compose file?

Thank you!

**Comment by nijel** [comment]
This is described in https://github.com/WeblateOrg/docker/issues/97 and https://docs.weblate.org/en/latest/admin/customize.html

**Comment by romanr** [comment]
Thank you. I looked at documentation and example https://github.com/WeblateOrg/customize-example
Unfortunately it does not apply to Docker - based Weblate installation as-is, there are some missing parts that I can't figure out: Created the weblate_customization module but have no idea how to apply what's in documentation to docker-based instance.

**1.** adding INSTALLED_APPS

in docker-compose.override iml format it's not possible to add INSTALLED_APPS = (...)

```yml
ersion: '3'
services:
  weblate:
    environment:
            INSTALLED_APPS: (
              'weblate_customization',
            )
``` 

How to properly add it and make it work?

**2.**  how to execute `./manage.py collectstatic --noinput`

If we run it on host it will not have ./manage.py. How to run that inside Weblate container, or even better, make it run every time it's started or docker-compose is built?

**3.** folder structure
Documentation says:

```
Overall your module structure should look like:

weblate_customization
├── setup.py
└── weblate_customization
    ├── __init__.py
    ├── addons.py
    └── checks.py
```

How would it look in relation to docker-based installation? is it weblate_customization in same folder as docker-compose files?

**Comment by nijel** [comment]
The docker integration options are described in https://github.com/WeblateOrg/docker/issues/97, it's not yet covered by docs or automation.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
