### ISSUE TITLE
Some translations are not automatically committed

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3005]
It is possible to reopen this issue? I spoke too fast last time: apparently it looks like it did work just after restarting weblate and celery after the upgrade, but now it's again not committing automatically the translations.

I checked celery logs and apparently the translations are found as "pending commits" but they are never committed. I also tried again to run manually `weblate commit_pending --all` in that case I see the components that needs to be committed, but they are not. OTOH when I do `weblate commitgit --all` everything is properly committed.

Here the problem is about linked components, I don't know if it happens for other ones.

All my components are configured with push on commits and 1 hour for commit_pending.

_Originally posted by @surli in https://github.com/WeblateOrg/weblate/issues/2923#issuecomment-529528575_

**Comment by nijel** [comment]
What is output of `weblate commit_pending --all -v2`? Does it list components which are not committed?

**Comment by surli** [comment]
> Does it list components which are not committed?

yes it does, but apparently there's no commit done.

**Comment by nijel** [comment]
Is it on linked component (the one with weblate:// URL) or on main one (with real Git URL)?

**Comment by surli** [comment]
> Is it on linked component

AFAIR, on both: on the linked components but also on the main one the components are linked too. I have some independent components, I'm not quite sure if it's the same. I just added some translations to test, but I need to wait 1 hour for my tests...

**Comment by nijel** [comment]
Also can you please check if you see `committing pending changes` log for the translation where things are not committed?

Anyway the only important difference between `commitgit` and `commit_pending` is that the latter first check if the changes are older than configured age, but once it is it prints the name and after this point both behave same (the only difference is that pending offloads the committing to the Celery worker).

**Comment by surli** [comment]
> if you see committing pending changes log for the translation where things are not committed?

where should I check for those logs? 

>  (the only difference is that pending offloads the committing to the Celery worker)

I suspect a problem with celery: we started to lose the automatic commits when migrating to Weblate 3.x I think which introduced the usage of celery.

**Comment by nijel** [comment]
Then please check it's logs for errors. Also you need to restart it on every Weblate upgrade.

**Comment by surli** [comment]
Ok, looks like I didn't check the right logs for celery, I found the following error: 
```
[2019-09-10 14:10:36,367: INFO/ForkPoolWorker-2] xwiki-platform/xwiki-core-resources/fr: committing pending changes (commit_pending)
[2019-09-10 14:10:36,368: ERROR/ForkPoolWorker-2] Failure while executing task: KeyError: u'github'
[2019-09-10 14:10:36,368: ERROR/ForkPoolWorker-2] Failure while executing task
Traceback (most recent call last):
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/weblate/trans/tasks.py", line 78, in perform_commit
    component.commit_pending(*args)
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/weblate/trans/models/component.py", line 124, in on_link_wrapper
    *args, **kwargs
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/weblate/trans/models/component.py", line 126, in on_link_wrapper
    return func(self, *args, **kwargs)
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/weblate/trans/models/component.py", line 1063, in commit_pending
    reason, request, skip_push=True, force=True
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/weblate/trans/models/translation.py", line 442, in commit_pending
    with self.component.repository.lock, transaction.atomic():
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/weblate/trans/models/component.py", line 682, in repository
    repository = VCS_REGISTRY[self.vcs](
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/weblate/utils/classloader.py", line 78, in __getitem__
    return self.data.__getitem__(key)
KeyError: u'github'
```

From what I can see in the DB the VCS value is indeed "github" for my components. I just tried to update it from the interface, but the value in DB remains the same apparently.

**Comment by nijel** [comment]
You probably had `hub` tool installed before and it's now removed, that's why Weblate doesn't include the github support.

**Comment by surli** [comment]
> that's why Weblate doesn't include the github support.

I don't get it. We indeed have `hub` installed and use weblate with Github pull requests as documented in https://docs.weblate.org/en/latest/vcs.html#hub-setup: it all works properly when I use the command from the UI.

Apparently it just does not work anymore from Celery.

**Comment by nijel** [comment]
Maybe Celery worker is executed with different `PATH` than Weblate itself? Where is `hub` installed?

**Comment by surli** [comment]
`hub` is installed in `/home/weblate/bin` and the Celery service is running by user weblate. The path is added in `/home/weblate/.bashrc`.

**Comment by nijel** [comment]
I don't think that Celery worker invokes .bashrc, so that might be the problem.

**Comment by surli** [comment]
hmmm right, checking how to give the right path to the service then

**Comment by nijel** [comment]
In case you're using provided examples, you can include it in `/etc/default/celery-weblate`

**Comment by surli** [comment]
Ok so I just did that but apparently it's not enough, I keep getting the same error log.

**Comment by nijel** [comment]
Maybe `systemctl daemon-reload` is needed afterwards, I'm not sure whether it's automatically applied.

**Comment by surli** [comment]
I tried with it.

**Comment by surli** [comment]
So, looks like it was indeed related to hub: I created a symlink on `/bin/hub` and apparently it fixes all my issue. I don't really understand why putting the path in `/etc/default/celery-weblate` didn't work properly, but at least I managed to make it work. Thanks for the help.
