### ISSUE TITLE
Use of soft hyphen for better automatic line break control in translations

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#3006]
Is there a good way to deal with soft hyphen in weblate? (Or any other recommendation?)

**Comment by nijel** [comment]
The only related thing Weblate does right now is to check for existence of [zero width space](https://docs.weblate.org/en/latest/user/checks.html#zero-width-space).

Can you please clarify what are you looking for?

**Comment by rhofer** [comment]
It's about resulting visualization of a translation in application's UI. E.g.
- English: Display Settings
- German: Anzeigeeinstellungen

Per it's nature, English is not dealing with very long words, constructed and concatenated as it is possible in german. Therfore in some places the according visualization widget needs to break the text into two lines. What works well for english above, since there two words are separated with white space, resulting in line 1: Display, line 2: Settings.

Whereas for german, the out of box result would be something like: line 1: Anzeigeinstel, line 2: lungen. Without a hyphen, just arbitrarily wrapped. 

With soft hyphen this could be controlled better.
- HTML style: `Anzeige&shy;einstellungen`
- Result: 
  - line 1: Anzeige-
  - line 2: einstellungen

Question is whether from weblate point of view there is a way to deal with this.
Drawback is, soft hyphen is technology specific (html5, xml, ...)

**Comment by rhofer** [comment]
The problem starts with editing, how a soft hyphen could be entered. There is a unicode character for this: U+00AD, see also https://de.wikipedia.org/wiki/Weiches_Trennzeichen

In windows you can "write" this sign by press+hold : ALT + 0173. The following is an example where after each word a soft hyphen is entered:

This­Is­A­Very­Long­Sentence­Where­After­Each­Word­A­Soft­Hyphen­Is­Entered­So­That­By­Exceeding­A­Line­It­Automatically­Breaks­At­The­Desired­Position­And­Renders­A­Hyphen­Accordingly.

Drawback is that this is a non-displayable character unless we come to a line end where at the position of a soft hyphen the line breaks, and only then this character becomes visible as a hyphen.

For editing in weblate it could be helpful to treat soft hyphen specially, as:

![shy-editor](https://user-images.githubusercontent.com/8058166/64759698-3d02f680-d538-11e9-9a4c-30c021aee2e8.png)

So that we have besides the special char buttons an additional one for soft hyphen (shy). When pressing this button and only the unicode char is injected this still is invisible. So may to enrich the input field with a special visualization for the soft hyphen char.

Textually, this is sufficient. What I don't know is whether soft hyphen needs to be treated differently, depending on destination technology (to handle accordingly in importer/exporter) as for e.g. json, html, xml, xliff, resx, ...

**Comment by rhofer** [comment]
Again, this is to start a discussion. I'm not fully clear whether this is really needed.

**Comment by fitojb** [comment]
Pootle uses a web font called “Raw” to make invisible Unicode formatting marks, like SHY and NBSP, explicit in the editor.

**Comment by nijel** [comment]
Related to https://github.com/WeblateOrg/weblate/issues/1930

Custom font should be quite easy to implement, but probably would not help with double space and more complex issues. The good thing is that we could the [Pootle Raw font](https://github.com/translate/pootle/tree/master/pootle/static/fonts).

I was always considering bringing in more complex editor which would handle highlighting such things and possibly also help with editing format strings and markup.

**Comment by nijel** [comment]
https://github.com/WeblateOrg/weblate/pull/10441 addressed most of this, but there is still rendering issue:

Adding soft hyphen shows nothing:

![image](https://github.com/WeblateOrg/weblate/assets/212189/b57f78a3-7672-41f2-82be-4636219c6dc6)

But when I extend the text, it appears:

![image](https://github.com/WeblateOrg/weblate/assets/212189/3675a079-b930-48a7-a4f0-3b9dc228e573)

This seems to affect only some browsers, see https://github.com/WeblateOrg/weblate/pull/10441.
