### ISSUE TITLE
Revert translation doesn't seem to work

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#3008]
**Describe the bug**

I just tried to hit the button "revert" on a translation and apparently nothing happened.

**To Reproduce**
1. Go to a translation
2. Look on the history
3. Revert a translation
4. See nothing happens

**Expected behavior**
I expect the previous translation to be automatically applied back and saved.

**Screenshots**
![weblate-try-revert](https://user-images.githubusercontent.com/1478232/64674973-53467f00-d472-11e9-9574-e54dee87c44c.gif)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by surli** [comment]
Thanks for the quick fix! :+1:

**Comment by nijel** [comment]
It was really a forgotten half of migration. It should have been done year ago :-). See b7f6308f6d3 and #1274.
