### ISSUE TITLE
Differentiate anymous user from bot

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3009]
**Is your feature request related to a problem? Please describe.**
Several operations performed by addons or command line currently default to be accounted to the anonymous user. This can be confusing as same user is used for unauthenticated web users.

**Describe the solution you'd like**
Create bot account which will be used for such events or more bots for different events (eg. autotranslate).

**Comment by comradekingu** [comment]
I am seeing https://hosted.weblate.org/translate/weblate/website/nb_NO/?checksum=3b654bf44e53462c and wonder where it came from.

Problem 1, lets say an autotranslation is just plain wrong, which means the source is wrong too. I think it is extremely valuable to be able to trace back a translation. Launchpad has this, where it lists the project name a string came from. That way one can correct errors at its root. The user could be Autotranslation-originalusername. That way it is possible to gauge urgency of review later on. I want to

Problem 2, who did what.
The problem with just doing "autotranslation" from unknown origin is that bad ideas propagate too, and it makes it easier to hide malice.

**Comment by strk** [comment]
We're having the same problem, commits by an "Anonymous" user started being pushed and we were left wondering. It would be nice to know they came from the automatic translator. Weblate does know about it, as it's shown in the UI: https://weblate.osgeo.org/translate/postgis/postgis-manual/es/?checksum=0043a14816a4ddbe&q=Identifier+of+the+edge&sort_by=-priority%2Cposition#history

**Comment by nijel** [comment]
MT authorship is addressed in https://github.com/WeblateOrg/weblate/pull/10096
