### ISSUE TITLE
Can't recover older translation entries, if

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3010]
I opened a KeePass comment e-mail, I think it must have mistakenly been a local/language comment, because it opened the German translation of the project.
All good so far, but I opened todays batch of new string e-mails, and mistakenly translated a string in KeePass into Norwegian, whereas it should have been German.

This is the string that was opened (in Zen)
https://hosted.weblate.org/zen/keepass-dx/strings/de/?type=nottranslated
I also had https://hosted.weblate.org/translate/keepass-dx/strings/de/?type=all&offset=35 open

I think the kicker is I edited the string back into English, (and I wrote in the string manually, rather than recover) since someone had translated it into its own context yesterday. 

The end result is https://hosted.weblate.org/translate/keepass-dx/strings/de/?checksum=7e7692ab360d74c5 where I can only recover my own mistake, but not the earlier translation, which I guess was "lost" when changing the source string.

---

Should users be sent to the language translation branch in question for comments?
I think the comment fields should be split up, one for the source, and one for the translation.
(Right now I think it is only possible to really comment source if the source can be edited, marked needs work, and commented directly)

I think if source comments are always source comments, and a warning is issued for the first string edited, translators will do no wrong, and admins can look at only relevant string comments?

**Comment by nijel** [comment]
There is indeed bug in revert, it's fixed in git, but not yet deployed, see https://github.com/WeblateOrg/weblate/issues/3008. 

The links for source comments will change after https://github.com/WeblateOrg/weblate/issues/2831 is implemented.
