### ISSUE TITLE
Minor: The big percentage stat in the “Engage” page isn’t localized

### ISSUE THREAD

**Issue by fitojb** [WeblateOrg/weblate#3013]
The big percentage in the Engage page is not localized, meaning that they don’t change according to each language’s punctuation rules. For instance, in Spanish and French, the “%” sign should be separated from the number with a no-break space, and in Basque and Turkish, the sign goes before, not after, the number.

This feature already works in the status badges.

* Spanish/French (number, no-break space, percentage symbol):
![Spanish](https://user-images.githubusercontent.com/554953/64766041-f77c0480-d50a-11e9-9180-62673b628110.png)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
