### ISSUE TITLE
./weblate setuplang should inform about the changes performed

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#3014]
**Is your feature request related to a problem? Please describe.**
We decided to only support `zh` and `zh_TW` locale for chinese on our platform, and so we deleted the other `zh_*` locale languages for Weblate.
But we just noticed that the former languages (such as `zh_Hans` or `zh_Hant`) appeared back on the interface. 
It looks like it's related to last upgrade during which we called `./weblate setuplang`. 

**Describe the solution you'd like**
The documentation could be improved about the impact of the command `setuplang` right now the only information we have is that is heavily recommended, that's why we performed it. 

Best solution would be to not create back the languages deleted on purpose, or ask for creating them back. But I can imagine it's not that easy to do.

IMO the bare minimum would be to at least display the changes performed when calling `setuplang`: right now, it doesn't display any info about the changes made.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
