### ISSUE TITLE
Very high memory consumption after delete of languages with pending commits

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#3015]
**Describe the bug**
Yesterday a new user started to translate using `zh_Hans` which is an unsupported language in our platform (in favor of `zh`). We decided to delete the language from the django admin, hoping that it would also perform a deletion of the translations. 

Starting there we got apparently several issues, a new `zh_HANS` appeared in the admin, and at that moment `celery-weblate` service was down. So we decided to start it again, and to delete also `zh_HANS`. Then we experienced a global decrease of performance on weblate: apparently it performed a global check over the components.

Now after the check it seems that `zh_HANS` appeared again, but also that our memory consumption is now very very high: we managed until then to run weblate on a machine with 3Go of RAM, but apparently we now got our services OOM killed, even after increasing it to 4Go of RAM.

Note that we still have a pull request opened with 25 commits, and that this VCS is linked by 75 components. I guess deleted the languages before fixing the commits led to a weird state in Weblate, which caused the memory issue, but not sure what we should have done in such condition.

**Comment by nijel** [comment]
Deleting the language in the Django admin interface will lead to collecting all related objects in memory, what can lead to huge memory consumption. That's one of reasons why we're going to stop using it (see https://github.com/WeblateOrg/weblate/issues/2363). I don't think that Python will ever release once allocated memory back to the system.
