### ISSUE TITLE
Grouping alert notifications

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#3017]
**Is your feature request related to a problem? Please describe.**
Our current installation of weblate contains 3 projets and one of them actually has 76 components which are linked to the same VCS: so basically 1 component is linked to the VCS and 75 others are linked to the root component. 

As an admin, I received all emails, and I just received 76 emails containing the following message:
```
The VCS repository has many changes compared to the upstream. Please merge the changes manually or set up push to automate this.
```

I don't know if those emails are sent only to the administrator or not: if it's the case, I'm not sure they should be send for each linked component, sending them only for the root component should be enough.

Now if the email can be sent also on people watching some components, then I guess they should be at least grouped: the warning triggers an email, and only one mail is sent with all concerned components.

**Comment by nijel** [comment]
The emails are sent to whoever has configured to receive notifications for alerts, by default admins receive this. You can also change subscription to digest mode.

**Comment by surli** [comment]
> You can also change subscription to digest mode.

Yes, but the digest mode are timeframed: here I'd like to continue receiving instant notifications in case of errors, but not to receive 1 mail for each component associated to the problematic VCS. 

> The emails are sent to whoever has configured to receive notifications for alerts

from what I can see, the configuration is done at project scale, not at component scale (e.g. I can chose only some projects to watch) so it might make sense here to only send 1 mail for the entire project in case of problem no?

**Comment by nijel** [comment]
Currently it's not easily possible - the alert trigger on each component is separate event, but you're right that in case of linked components, the notification should be sent out just once for the main repo.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
