### ISSUE TITLE
Performance impact from in_progress

### ISSUE THREAD

**Issue by mlaggner** [WeblateOrg/weblate#3018]
**Describe the bug**
After upgrading to 3.7.1 I noticed a performance issue (really slow loading pages) in my environment. After hours of debugging and performance tracing, I've noticed that the code in `/weblate/trans/models/component.py` causes a ~3 sec delay for every component shown:

https://github.com/WeblateOrg/weblate/blob/efaadf581912010eff3bc3b9da005f78f3cd5f7e/weblate/trans/models/component.py#L582-L587

tracing it down has shown that the access to the celery workers is causing the delay. At the moment there are no more active workers, but I've had some failed workers (out of memory) for these components - maybe there is a old worker state in the DB?

after commenting the check in `in_progress` (always return false), weblate responds as fast as it should

**To Reproduce**
1. create a project with several components
2. install pyinstrument (https://github.com/joerick/pyinstrument)
3. create the profile.

**Expected behavior**
The progress indicator should not slow down the responses

**Screenshots**
an export of the profile is available

[4,164s - __call__ - pyinstrument.zip](https://github.com/WeblateOrg/weblate/files/3605568/4.164s.-.__call__.-.pyinstrument.zip)

**Server configuration and status**
```
* Weblate 3.7.1
 * Python 3.7.3
 * Django 2.2.3
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.6
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.20.1
 * Pillow 5.4.1
 * python-dateutil 2.8.0
 * lxml 4.3.2
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.9.4
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20121119
 * pytz 2019.1
 * pyuca 1.2
 * ruamel.yaml 0.15.99
 * tesserocr 2.4.0
 * Mercurial 4.8.2
 * git-svn 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.4.114-94.11-default (x86_64)
```

```
WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.7.1/admin/install.html#collecting-errors

System check identified 586 issues (1 silenced).
```

**Additional context**
used your docker image without modifications

**Comment by nijel** [comment]
It just checks task state, what should be fast. Is celery running? In case it's not it can probably lead to some timeouts...

**Comment by mlaggner** [comment]
yes, celery is running (at least if your default docker instance is set up correctly, but all other tasks in celery works well)..

could it be that the component looks for a celery job which has been aborted due to memory issues?
I saw in the logs, that some celery jobs has been aborted because I've added a rather huge component and the default 200mb per celery job was not enough.

**Comment by nijel** [comment]
The 200mb limit should be checked after task execution, so that should not be an issue.

Anyway now I finally looked into your profile and the problem is in collecting child tasks, probably there is way too many of them and that's why it takes so long.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
