### ISSUE TITLE
Not sure how to reset branches after merge conflicts

### ISSUE THREAD

**Issue by hicksjacobp** [WeblateOrg/weblate#3021]
**Describe the bug**
We found out that our Weblate repository had issues pushing for awhile. It looked like it auto-created a `weblate-merge-tmp` branch to continue making commits while the `master` branch stayed at the last point in history it could push.

I believe I have resolved all conflicts by manually merging and pushing to the upstream repository such that the latest commit on the current branch is the same as the latest commit on the upstream branch. On the Repository maintenance screen, it shows a status indicating this:
```
On branch weblate-merge-tmp
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

**To Reproduce**
I'm not exactly sure how the `weblate-merge-tmp` branch got created. Once it is and used as the current branch while `master` is behind the latest in `upstream/master`, then the following steps can be used to show conflicts.

1. Change a translation (save it).
2. Navigate to the Repository maintenance screen. It should indicate that there are uncommitted changes.
3. Click on 'Commit'
4. The push fails (see screenshot).

**Expected behavior**
I would expect a push command to succeed, and/or that Weblate automatically switches back and resets the `master` branch when the current branch is finally up to date the latest from upstream.

I would guess that by having server access that the current git branch could just be changed to `master` and reset to `upstream/master` via the command line. Additionally the `weblate-merge-tmp` could be deleted? I'm not sure if these are the expected steps however.

**Screenshots**

![image](https://user-images.githubusercontent.com/832739/64894425-5773c780-d63f-11e9-82df-e72aebd32c15.png)

**Server configuration and status**
I don't have server access, I'm a user. Our support staff is limited in Weblate knowledge and this scenario doesn't appear documented. I don't believe I have methods to provide the requested configuration and status, but I can provide information that is available through the UI.

![image](https://user-images.githubusercontent.com/832739/64894161-99503e00-d63e-11e9-91fb-6e0067f86728.png)

**Additional context**
None.

**Comment by nijel** [comment]
The `weblate-merge-tmp` branch is temporary branch used to merge upstream changes in order to have expected order in the merge commit (see https://github.com/WeblateOrg/weblate/issues/1797 for more info on that).

Probably there is (was) some bug in merge failure handling left to state where the branch stayed in the repo, while it is expected to be there only in time of merging. I remember fixing one of similar things in  59886a62392ec529d59f5d3d3cd81fb38bff2f22, but there were more fixes in the related logic since 3.1.1 which you are using.

My best advice would be to upgrade to current version, it should be able to recover better from this.

**Comment by hicksjacobp** [comment]
@nijel I can put in a request to upgrade the version, but I'm guessing it won't be resolved immediately. Until that can happen, we have translations on-going but they won't be merged to our upstream unless we manually merge them due to this issue that Weblate's git working directory is not switching back to `master` to put new translation commits on.

Do you think it would be sufficient to change the current branch in Weblate's git working directory from `weblate-merge-tmp` to `master`, and reset `master` to the same commit as `upstream/master`?

**Comment by nijel** [comment]
Doing `git checkout master && git branch -D weblate-merge-tmp` should be safe. However the same issue might still appear again.

**Comment by hicksjacobp** [comment]
We have other projects/components that appear to be working fine, so I'm hoping that with manually fixing this one will be back to normal operation. I'll post an update once we give it a shot.

**Comment by hicksjacobp** [comment]
> We have other projects/components that appear to be working fine, so I'm hoping that with manually fixing this one will be back to normal operation. I'll post an update once we give it a shot.

Apologies for the delay, but these actions have allowed us to clean up our Weblate instance, with the additional action of resetting the `master` branch to the latest commit available in `upstream`.
