### ISSUE TITLE
/healthz causing crash when Sentry is enabled.

### ISSUE THREAD

**Issue by mcfedr** [WeblateOrg/weblate#3026]
**Describe the bug**

I'm using the docker container to run weblate, and when I added the envvar `SENTRY_DSN` weblate crashes (reporting the crash to sentry, which i guess is a positive) on the /healthz url, not sure if it crashes on all urls, as I wasnt able to check.

This a link to the crash, https://sentry.io/share/issue/6b576552ae434e7fa1cb0d637b6d124b/ - unfortunately it doesnt show you the full info so I've attached a screenshot:
![Screenshot 2019-09-16 at 12 17 28 pm](https://user-images.githubusercontent.com/704356/64946676-10bee100-d87c-11e9-998f-bd49883b0aa1.png)

**Server configuration and status**

```
weblate@weblate-0:/app/bin$ /usr/local/bin/weblate list_versions
 * Weblate 3.8
 * Python 3.7.3
 * Django 2.2.5
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.6
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.20.1
 * Pillow 5.4.1
 * python-dateutil 2.8.0
 * lxml 4.3.2
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.10.3
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20181111
 * ruamel.yaml 0.16.5
 * tesserocr 2.4.1
 * Mercurial 4.8.2
 * git-svn 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: email-smtp.eu-west-1.amazonaws.com
 * Celery: redis://weblate-redis:6379/1, redis://weblate-redis:6379/1, regular
 * Platform: Linux 4.14.127+ (x86_64)
```

**Additional context**

**Comment by nijel** [comment]
Looks like the code doesn't well handle if `SENTRY_PUBLIC_DSN` is not set, so setting it should fix it.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by mcfedr** [comment]
Thank, adding SENTRY_PUBLIC_DSN has fixed the issue. Its really unclear in the docs that you need both.

**Comment by nijel** [comment]
You should not need both, I've fixed that.
