### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by ersvltan** [WeblateOrg/weblate#3028]
**Is your feature request related to a problem? Please describe.**
I am sending a request for a Weblate, and the response does not have `Access-Control-Allow-Origin` headers, and therefore the browser rejects responses from the server with the error `Access to XMLHttpRequest at * from origin 'http://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request`.
Can Weblate provide any solution for setting Access-Control-Allow-Origin headers?

**Describe the solution you'd like**
Currently I am adding a corsheaders library to `settings.py`. But it would be easier in the future to have CORS headers support built-in.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
No context

**Comment by nijel** [comment]
This is intentional setup, can you please clarify what is your use case for this

**Comment by ersvltan** [comment]
> This is intentional setup, can you please clarify what is your use case for this

updated description.

**Comment by nijel** [comment]
I don't think it's reasonable to set it on whole Weblate, it might be better just on selected endpoints you are using?

**Comment by ersvltan** [comment]
> I don't think it's reasonable to set it on whole Weblate, it might be better just on selected endpoints you are using?

What do you mean by selected endpoints ?

**Comment by nijel** [comment]
Selected URLs. Can you please describe what is your use case? Why do you need to do CORS against Weblate?

**Comment by nijel** [comment]
Reopening based on https://github.com/WeblateOrg/weblate/discussions/6665 and https://github.com/WeblateOrg/docker/pull/1694
