### ISSUE TITLE
Rework e-mail subject field/headline to state number of respective alerts

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3030]
E-mails about suggestions don't actually feature the number of strings that have suggestions, whereas having that would make sense to gauge the required workload for whoever gets the e-mail.

Seems all alerts share the same layout, and suggestions is left out?

![image](https://user-images.githubusercontent.com/13802408/65007577-e0705480-d906-11e9-8046-a37786e018c3.png)

The actual topic field of the e-mail doesn't have it either, but that is similarly an issue with all alert strings.

**Comment by nijel** [comment]
It does include the number in the first sentence....

**Comment by comradekingu** [comment]
Oh boy, quality bugreport right there! ;)

![image](https://user-images.githubusercontent.com/13802408/65272045-a4afd780-db1e-11e9-8e08-711ce56f8033.png)

I for some reason don't look at that text, as every other time, the relevant info can be found in the fields below, and it is a bit redundant to the headline.
