### ISSUE TITLE
Add notification settings for all projects

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3036]
(To my understanding the new component alert only works for followed components.)

However, it would be nice to be alerted of new projects, and additionally, the components in them, instead of looking through the list of watched projects now and then.

Not sure if this should be on by default, maybe?

**Comment by nijel** [comment]
Such thing certainly can not be on by default, most people are not interested in this :-).

But certainly there could be notification setting for *all* projects in addition to *watched* ones.

**Comment by comradekingu** [comment]
Maybe not on Hosted they aren't, but for other instances I imagine people would be? It seems to me it would provide better results, if annoying maybe some. A middle-ground of the admin being able to set it for all users could be good? Don't know what the EU-GDPR legality of it is, but you get the idea. For another day.

The "All projects" is exactly it :) I think if setting those, the corresponding and subordinate "watched" cateogries should  be grayed out for the user.

**Comment by nijel** [comment]
Another reason to have notification settings for all projects is to enable mention notifications on these by default. Currently it works only on watched projects, what is a bit confusing.
