### ISSUE TITLE
Suggetion notifications have two buttons, new translations just one

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3037]
**New suggestion**:
![image](https://user-images.githubusercontent.com/13802408/65272504-81d1f300-db1f-11e9-937b-eb8ede4f340b.png)

---

**New string:**

![image](https://user-images.githubusercontent.com/13802408/65272579-9b733a80-db1f-11e9-8e1d-42d67842b03c.png)

---

I think just the one button, up top, is better. What is shown is more-so related to the first explanation, not the translator info.

**Comment by MetalDent** [comment]
Hi, anyone working on this?

**Comment by 2132000** [comment]
ADD CONTIBUTING.md

from functools import wraps

LIST_OF_ADMINS = [12345678, 87654321]

def restricted(func):
    @wraps(func)
    def wrapped(update, context, *args, **kwargs):
        user_id = update.effective_user.id
        if user_id not in LIST_OF_ADMINS:
            print("Unauthorized access denied for {}.".format(user_id))
            return
        return func(update, context, *args, **kwargs)
    return  #wrapped``

**Comment by nijel** [comment]
It's not new translations, but new string to translate. The problem with that one, is that it's not about one particular string, but about state of the translation - there appeared at least one new string to translate.

Related to #3332
