### ISSUE TITLE
Make translator info fields in alerts into links

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3038]
![image](https://user-images.githubusercontent.com/13802408/65272921-4f74c580-db20-11e9-94a2-bae768f0e58b.png)

All strings, untranslated etc. could be links. More direct navigation, less clicking about in the UI. :)

**Comment by nijel** [comment]
Adding the links to the template should be easy:

https://github.com/WeblateOrg/weblate/blob/51195ff7f6919313b7cf165dbeb4938102b71b1d/weblate/templates/mail/base.html#L215-L243

**Comment by MetalDent** [comment]
Hi, is anyone working on this?

**Comment by apitulea** [comment]
Could I work on this as well?

**Comment by comradekingu** [comment]
@Don't think so.
@apitulea Yes.
