### ISSUE TITLE
Provide way to deal with abusing users

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3040]
**Is your feature request related to a problem? Please describe.**

There can be users intentionally putting bad translations. Often this happens when some of the security hackers do not follow our [HackerOne policy](https://hackerone.com/weblate).

There should be way to deal with such users easily.

**Describe the solution you'd like**

* Blocking user
* Reverting all his changes

**Describe alternatives you've considered**

Currently reverting has to be done manually, what can be tricky in case of lot of changes.

**Additional context**
https://hosted.weblate.org/user/dicks/

**Comment by comradekingu** [comment]
Other than changes, it is a bit cumbersome to "revert" suggestions now. If it was easier, it would also serve its purpose more easily, as one could all governed projects at 0 pending suggestions.

One would have to find malice first, but who knows who is looking at what?
I know I am not watching Andors' Trail, nor Thai, but I don't really know if something has slipped past me for the things that I do check.

Review per translator #2699 and per component threshold for admission would help. (Similar to what can be done with reviewed now). One helps direct eyeballs and effort, the other prevents potential malice from going live.

**Comment by comradekingu** [comment]
https://hosted.weblate.org/translate/dreamchess/dreamchess/nb_NO/?checksum=520d5d45b8778762 is still shown in history.

**Comment by nijel** [comment]
The history will stay there forever.

**Comment by rubenwardy** [comment]
It would be good to have a way of banning users which submit malicious translations

We've had a user create 100s of languages and spam of all us, obviously the best fix for this would be rollbackings

**Comment by nijel** [comment]
@rubenwardy We've added rate limiting to adding new translations, so that should reduce the scope of the problem next time.

Right now, it might be easier to revert unwanted changes in Git than doing that in Weblate, but in the long term Weblate should provide an easy way to do that.

**Comment by rubenwardy** [comment]
I meant ratelimiting, I must have read rollback in another window whilst typing

**Comment by nijel** [comment]
It's already there for this case: https://github.com/WeblateOrg/weblate/commit/0f97e134ebb3f213a1b4f58d3e6907426acb95b2

**Comment by rubenwardy** [comment]
We have a user who is putting in inappropriate sex-related translations in Chinese

https://forum.minetest.net/viewtopic.php?f=6&t=26303

**Comment by orangesunny** [comment]
> We have a user who is putting in inappropriate sex-related translations in Chinese
> 
> https://forum.minetest.net/viewtopic.php?f=6&t=26303

We received a report from the Minetest community to our support. The user is suspended for now.

**Comment by rubenwardy** [comment]
Thanks :)

**Comment by kevinpapst** [comment]
It would be great to have a way to block certain users completely from a project.
While I get more translations with Weblate (which is great!) I am now chased by some users who keep adding empty languages and changing translation which I have to revert over and over again. 

A collaboration platform should be able to deal with both sides of contributions (even in free plans), the good ones and the bad ones, while putting the least possible effort on administrators. 

Having a "block this user from my projects" button on the user profile could be enough for the beginning. An overview of blocked users would be nice, but for the start having a button that simply toggles from "block this user" to "user is blocked - unblock" should be enough.

**Comment by kevinpapst** [comment]
Thank you @nijel for adding user blocking!
