### ISSUE TITLE
XLIFF 2.0 support

### ISSUE THREAD

**Issue by marcbria** [WeblateOrg/weblate#3041]
I'm working for a free software project.
We like to offer a weblate server to our translation community, but we need to work over XLIFF 2.0.

Any plan in weblate to support XLIFF 2.0?

Thanks for your great work,
m.

**Comment by nijel** [comment]
Duplicate of #972

**Comment by marcbria** [comment]
thanks! Sorry for the annoyance.

**Comment by nijel** [comment]
No problem, it's one of major formats we're missing. Unfortunately it's quite different to XLIFF 1.2, so the implementation is not that easy.

**Comment by marcbria** [comment]
We full understand. In our community we have a similar situation.
Looot of people is using it, but only a few can code (or like to contrib).
Thanks for this wonderful tool. You are making the free software ecosystem stronger.
