### ISSUE TITLE
Show source language on components when using a POT file

### ISSUE THREAD

**Issue by maicol07** [WeblateOrg/weblate#3043]
**Is your feature request related to a problem? Please describe.**
At the moment, when you set PO gettext as file format in a component, it will not show the source language in the components languages

**Describe the solution you'd like**
When you set in components options, Weblate should show that source language is 100% translated and mark it as source

**Describe alternatives you've considered**
Nothing...

**Additional context**
![immagine](https://user-images.githubusercontent.com/9463142/65387340-bd9ad180-dd46-11e9-957b-128ea70073f5.png)
In this case, Italian is the source language. I've added it manually and it shows 0% translated and it's not marked as source.

**Comment by nijel** [comment]
This should be addressed by https://github.com/WeblateOrg/weblate/issues/2831

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
