### ISSUE TITLE
Split RESX synchronization from "Cleanup translation files" addon

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3052]
**Describe the bug**
The "Edit base file" setting and "Cleanup translation files" addon interfere with each other

**To Reproduce**
So I have a repository with .Net resource file and already with some translated strings. But the files are different, the most complete file is, obviously, source language file (Russian). Other languages (English and German) are missing some lines completely (each one a different set of them). 
- I create a component with "Edit base file" check on from these files. On the language list of this component Russian translation is 100% complete, English is 98.8% and German is 92.2%.
- Then I go to Manage>Addons and install "Cleanup translation files" addon.
- Then I go to Manage>Settings>Files and remove the "Edit base file" check.

Now when I go to the list of languages Russian is gone (obviously), but English translation is 100% complete and German is 99.8%.
The reason for this is because the missing strings have been added to the English and German translation with the targets (translations) in Russian.

The same thing happens with different sequence
- At the component creation I uncheck the "Edit base file"
- Install "Cleanup translation files" addon
- At the Manage>Settings>Files enable "Edit base file" check

If I don't install the "Cleanup translation files" addon switching base language editing on and off does not affect other languages.

**Expected behavior**
Installing "Cleanup translation files" addon should not interfere with enabling or disabling base language editing.

**Server configuration and status**
```
 * Weblate 3.9-dev
 * Python 3.5.3
 * Django 2.2.5
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.6
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.11.0
 * Pillow 6.1.0
 * python-dateutil 2.8.0
 * lxml 4.4.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.10.3
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20181111
 * ruamel.yaml 0.16.5
 * Mercurial 4.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * Celery: memory://, N/A, eager
 * Platform: Linux 4.9.0-3-amd64 (x86_64)
```

**Comment by nijel** [comment]
It has nothing to do with "Edit base file", it's just the addon doing this. AFAIR this was intended behavior and it behaves like this for years (see 64a21aee2c4251d5742bff3d5f45b16cae3bc86f). I'm however no expert on resx, so it might be actually wrong.

**Comment by nijel** [comment]
I've looked up the original request for this feature and it was requested to behave this way:

> We have it before in transifex. So when we add new string in the source file, the other languages will also be added with the english text by default. We need it because, when the string is not there for certain language it could crash the app. Returning the english value is better than not having any.

**Comment by tariver** [comment]
I see, thank you.
Our application has a different fallback mechamism and won't crash if there is no string.

**Comment by nijel** [comment]
Probably it makes sense to split cleanup and adding of new strings into separate addons.

**Comment by tariver** [comment]
> Probably it makes sense to split cleanup and adding of new strings into separate addons.
That would be great.
Meanwhile it would be nice to update addon description so that it tells about adding new line.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
