### ISSUE TITLE
merge failures after  BFG Repo-Cleaner

### ISSUE THREAD

**Issue by juha-h** [WeblateOrg/weblate#3053]
I used BFG Repo-Cleaner to permanently get rid of some old large binary files from my GitHub repository.  After that, Weblate started to send me email warnings:

"Weblate could not merge upstream changes while updating the repository."

I tried to follow  given "Typical workflow for fixing merge conflicts" instructions, but it looked like the files that I just got rid off appeared again in my repository.

Is there some way to update Weblate's version of my repository (and not the other way around) so that those permanently deleted files would also disappear from Weblate?

**Comment by nijel** [comment]
Yes, reset the repository in the repository maintenance.

**Comment by juha-h** [comment]
Thanks.
