### ISSUE TITLE
Only send merge failure emails to admins

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#3054]
**Is your feature request related to a problem? Please describe.**
Currently email alerts about merge failures in a component are apparently sent to all users watching the component (on hosted.weblate.org at least). I don't think translators without administrator privileges can do anything to fix the failures, though.

**Describe the solution you'd like**
Don't send merge failure alerts to users who can't solve the issue.

**Describe alternatives you've considered**

**Additional context**

**Comment by nijel** [comment]
The default notification settings send this only to admins, users only get notifications on comments and posted announcement messages:

https://github.com/WeblateOrg/weblate/blob/42aa142aeb1e8203a3e3b0e88a77e8ee05ce2d1d/weblate/accounts/data.py#L25-L35

What makes you think that all watching users get it?

**Comment by tjhietala** [comment]
At least I get them, and I don't think I'm an admin :)

**Comment by tjhietala** [comment]
I checked in the profile and indeed they seem to be enabled. I don't remember enabling them, though. If it hasn't ever been the default, I suppose I may have enabled them accidentally.

**Comment by cnavagr** [comment]
Is there any option where we can change duration of this mails?
It is coming after every 10 minutes and inbox is getting full.

**Comment by nijel** [comment]
The email is sent for every even in case you have configured immediate sending for this notification in your profile, you can switch to digest mails to get one per day or even less frequent.
