### ISSUE TITLE
Make all search fields searchable

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3057]
![bilde](https://user-images.githubusercontent.com/13802408/65722269-3c2ba200-e0ac-11e9-9284-53679d529a48.png)

Scenario: I want to make sure every translation of a word avoids a mistake I am aware of. What I would do is fill out 
Source string: Dog
Target: (backtranslation) Cat

instead of going to every dog string, or every translation that happens to be (backtranslation) cat.

So a "Search in" field would have to be added.

**Comment by nijel** [comment]
This is already in progress, see https://github.com/WeblateOrg/weblate/issues/2643 and https://docs.weblate.org/en/latest/user/search.html

**Comment by comradekingu** [comment]
@nijel Fantastic :)
