### ISSUE TITLE
&amp; flagged as punctuation error in French

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3065]
Possibly the smallest issue :)

https://hosted.weblate.org/translate/madewithcc/translation/fr/?checksum=22cffe173f228769

`Par Paul Stacey &amp; Sarah Hinchliff Pearson`

Don't know if the best idea is to never have bugs in copied placeholders, or add something to the specific rule.

Edit: Also strange, "% of" turns into a "% o" placeholder
https://hosted.weblate.org/translate/skolab-groupware/webadmin/pt/?checksum=c98ad3c704990253

**Comment by nijel** [comment]
The punctuation spacing is certainly wrong, it should ignore html markup.

As for the format string, it's legit - the string is flagged as `php-format` and `% o` is valid format string. So I'd say it's bug in extracting the strings or in the code.

```console
php > printf('% o', 493);
755
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
