### ISSUE TITLE
Access to internal git repository for previews

### ISSUE THREAD

**Issue by sr258** [WeblateOrg/weblate#3068]
Is it possible to access the internal git repository that Weblate uses to manage translations from outside, e.g. using http? What I want to do is have an external service do previews on translations in a demo instance of the real application and it needs to get the current translation files (unpushed) from the Weblate service for this.

**Comment by nijel** [comment]
Yes, see https://docs.weblate.org/en/latest/admin/optionals.html#git-exporter

**Comment by sr258** [comment]
Excellent! Thanks! Weblate is really a great tool!
