### ISSUE TITLE
Folder after branch name in source linking

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3069]
Clicking around in https://hosted.weblate.org/settings/ghini/documentation-10/#vcs I can't seem to add a folder after the branch name for the source linking?

I tried
https://hosted.weblate.org/settings/ghini/documentation-10/#vcs https://github.com/ghini/ghini.desktop/blob/{{branch}}/doc/{{filename}}#L{{line}}

to get to https://github.com/Ghini/ghini.desktop/tree/ghini-3.1-dev/doc

for example https://github.com/Ghini/ghini.desktop/blob/ghini-3.1-dev/doc/administration.rst like in https://hosted.weblate.org/translate/ghini/documentation-10/nb_NO/?checksum=94de33f24875fc24

Currently using https://github.com/ghini/ghini.desktop/blob/{{branch}}/doc/{{filename}}#L{{line}}

**Comment by nijel** [comment]
Probably the filename includes `../`. In that case you want to use `{{filename|parentdir}}` to strip that. See https://docs.weblate.org/en/latest/admin/projects.html#markup
