### ISSUE TITLE
Leftclicking dictionary in components does nothing

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3070]
https://hosted.weblate.org/projects/f-droid
`<a href="/dictionaries/f-droid/">Ordlister</a>
`
vs. (the non-working new-thing-bad)

https://hosted.weblate.org/projects/f-droid/f-droid/
`<a href="/dictionaries/f-droid/" data-toggle="tab">Ordlister</a>`
(middleclick and leftclick→ open in new tab works)

Why not just target="_blank"?

Tried in FF, Falcon, Otter, and Tor-Browser

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
