### ISSUE TITLE
Forced punctuation spacing for colon in glossary lookup

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3071]
https://hosted.weblate.org/dictionaries/weblate/en_GB has a forced space preceding the colon " :", which is not modifiable in https://hosted.weblate.org/translate/weblate/master/nb_NO/?checksum=f8c11999783a1311

![bilde](https://user-images.githubusercontent.com/13802408/65831644-3f957800-e2bc-11e9-86f3-dc120ac82d92.png)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
