### ISSUE TITLE
Indentation spaces adds one whitespace to link

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3073]
https://hosted.weblate.org/translate/freedombox/plinth/nb_NO/?checksum=9a01418f36fd54a1

Copying source here adds an extra whitespace before "discussion forum" that is not in https://salsa.debian.org/freedombox-team/plinth/blob/master/plinth/modules/help/templates/help_feedback.html#L33

**Comment by nijel** [comment]
It's there - there is newline between `<a>` tag and the text. See https://salsa.debian.org/freedombox-team/plinth/blob/master/plinth/locale/nb/LC_MESSAGES/django.po#L1794
