### ISSUE TITLE
Glossary access by language

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3080]
I've created a group called "English translators", gave them roles "Translate" and "Manage glossary". Also I limited their language to English
![image](https://user-images.githubusercontent.com/36223356/65944519-8dd08580-e43a-11e9-84be-658a23273243.png)

Now when I log in as this user I can't save or even suggest in other languages other than English, but I still can add new words to the glossary of this languages. Is there a way to provide glossary access on per language level?

**Comment by nijel** [comment]
The dictionary permissions are currently not checking the language scope at all. Support for that could be definitely added.
