### ISSUE TITLE
&amp; in XLIFF does not get unescaped

### ISSUE THREAD

**Issue by mlaggner** [WeblateOrg/weblate#3081]
**Describe the bug**
If you have `&amp;` in your XLIFF files, it does not get unescaped to `&`.

Example:

orginal: `Sicht "&" Eintrag kopieren als: Zieleintrag`

XLIFF;

```
<?xml version="1.0" encoding="utf-8"?><xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
 <file datatype="plaintext" original="OBJECT" source-language="de-DE" target-language="fr-FR" date="2019-09-11T07:25:52Z" category="..">
  <body>
   <trans-unit size-unit="char" approved="no" maxwidth="60" id="A_TITLE" resname="A_TITLE">
    <source>Sicht "&amp;" Eintrag kopieren als: Zieleintrag</source>
    <target state="needs-review-translation">Copier entrée vue "&amp;" : entrée cible</target>
   </trans-unit>
  </body>
 </file>
</xliff>
```

and in weblate, exactly this string is represented as:
![image](https://user-images.githubusercontent.com/1523778/65946792-34b32280-e437-11e9-9067-362f262abf06.png)

**To Reproduce**
1. Create an XLIFF Export having a source string with an escaped `&`
2. Import this into weblate
3. View the string in weblate

**Expected behavior**
The `&amp;` should be unscaped for translation (and re-escaped on commit)

**Screenshots**
see above

**Server configuration and status**
```
* Weblate 3.7.1
 * Python 3.7.3
 * Django 2.2.3
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.6
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.20.1
 * Pillow 5.4.1
 * python-dateutil 2.8.0
 * lxml 4.3.2
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.9.4
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20121119
 * pytz 2019.1
 * pyuca 1.2
 * ruamel.yaml 0.15.99
 * tesserocr 2.4.0
 * Mercurial 4.8.2
 * git-svn 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.4.114-94.11-default (x86_64)
```

```
WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.7.1/admin/install.html#collecting-errors

System check identified 586 issues (1 silenced).
```

**Comment by mlaggner** [comment]
update: looks like xliff files imported with a previous version did not have these problems; only components I've created with weblate 3.7.1

**Comment by nijel** [comment]
The XML markup is handled differently for some time, see https://github.com/WeblateOrg/weblate/issues/490 and related issues.

**Comment by mlaggner** [comment]
as far as I can read out of the issue (and PR), the XLIFF content is now handles as rich source, where no more _conversion/escaping_ is done?

But if I remember correctly, there is a need to escape some characters in a XML file (like the ampersand).

How could we solve that?

**Comment by nijel** [comment]
It should escape the strings when necessary (AFAIR it's when it's not valid XML).

**Comment by mlaggner** [comment]
But if you take the example from above and create a new test component in a weblate 3.7.1 instance, you will recognize that the ampersand is not unescaped..

tbh I do not have any clue where to look for a solution

**Comment by nijel** [comment]
With current code, it's expected to be unescaped. We can either interpret the XML and strip tags or include the tags and leave the XML as is including tags and escaped entities.

**Comment by mlaggner** [comment]
Would it be possible to include a setting in the component to choose the behavior?

**Comment by nijel** [comment]
Probably not in the settings, but separate file format would do that.

**Comment by al-65** [comment]
Hi there, 
also hit this, but actually it would already help if the checking against maxwidth tag considered escaped characters like &amp; as just one character :)

**Comment by nijel** [comment]
@al-65 It should be the case since 15841ba07a6e2a36f380f61b700d6efcb2103292, see #6645

**Comment by al-65** [comment]
hm, my &amp; is still counted as 5 chars. have tried to place the xml-text flag in both header and translation unit, like:

<trans-unit id="ID_qwertyS16" xml-text="1" size-unit="char" maxwidth="1">
<source>&amp;</source>
</trans-unit>

**Comment by al-65** [comment]
oops xml doesn't survive inputting here :( 
here is an image:
![image](https://user-images.githubusercontent.com/54986767/151341552-9a2dd6cb-6899-46b0-9aad-6f24f75e68b2.png)

**Comment by nijel** [comment]
The flag needs to be set in Weblate, but it should be set automatically for XLIFF. You might need to use `loadpo --force` to enforce re-reading the file by Weblate.

**Comment by nijel** [comment]
What would be the preferred solution here?

* Are we looking for string granularity to handle XML differently?
* Would file format option to escape/not escape XML be sufficient?

In case the second option wins, implementing it is pretty straightforward - it's just a matter of adding another XLIFF file format support to Weblate which will skip current XML handling logic.

**Comment by al-65** [comment]
Hi there, 
for me, option 2 would be absolutely fine. Translators would just see "&" instead of its esc sequence, and a "&" character would ideally be counted as one character (same for the other few escaped chars). The xliff files would still have to hold the escaped version to be valid xml.
Best regards,
Andre

**Comment by nijel** [comment]
Okay, in that case, we can go for two file formats - *XLIFF (raw XML)* (current one) / *XLIFF (escaped XML)* (to be developed).

Looking at Transifex, they escape only parts of the strings, but that sounds too fragile to me (and that won't cover the HTML use case mentioned in https://github.com/WeblateOrg/weblate/issues/7224): https://docs.transifex.com/formats/xliff#escaping-characters

**Comment by ScionOfDesign** [comment]
I just ran into this issue, hot having escaped XML Xliff formats is _horribly_ painful to work with for us. We do not have the option to use .csv because the format Unity exports from are not compatible with the format Weblate uses.
Our use case is that we use XLIFF files exported from Unity's localization package. In Unity, strings use Rich Text to determine if they are bold or italic or whatnot. We also use XML tags to insert variables and character names.

This leads to a lot of confusing-looking characters in the text. Furthermore, the french translation check thinks that there should be a space in front of the ; used for escaping like so:
![image](https://user-images.githubusercontent.com/8867456/162782054-73ae3561-d640-4f71-ad4f-485d0e53acfd.png)

Having this escaped XML format would be amazing. Also having the ability to edit in rich-text would be even _more_ amazing.

**Comment by ScionOfDesign** [comment]
Thank you so much for thise! I was able to pull from `bleeding` and it works great for us!
