### ISSUE TITLE
Allow use translation ID as case insensitive

### ISSUE THREAD

**Issue by jzahradn** [WeblateOrg/weblate#3082]
Hi,

Observation: packageExists ID is different in both file camel-case in [en] and lowercase in [ko].
Weblate Version: 3.7.1

Please take a look at csv files:
https://drive.google.com/open?id=1o_XsGOMI-47m24V-PVJLgGPM007bMbX8

The mqps-webapp-ko.csv file is imported via http using the access token and the translations get duplicates because the ID doesn't match in Weblate.

There is no steps to reproduce because it is not issue with the UI, it is issue with the engine.

Best regards,
Jan

**Comment by nijel** [comment]
Yes, identifiers are currently case sensitive as that is how most localization framework deal with them.
