### ISSUE TITLE
Flag translations as "need editing" when source translation is committed

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#3088]
**Is your feature request related to a problem? Please describe.**
When a source message is modified through a commit, it seems that the translations are not flagged automatically as "need editing". It looks like it's done only when editing the source through the platform. 

**Describe the solution you'd like**
To flag the translations as "need editing" when a commit is done on an existing translation key. 

**Describe alternatives you've considered**
Pushing the contributors to not commit changes on existing source message, but not easy :) 

**Context**

Example of such commit which are not flagging the translations as "need editing": https://github.com/xwiki/xwiki-platform/commit/051cf02ae2e9d9b281284aa42e8afb9b8d6ac277#diff-fffbf37334c4d7a178b13f4ccc313f86

**Comment by nijel** [comment]
It should happen this way for mononolingual translations. How is your translation component configured?
