### ISSUE TITLE
Installation requirements on Fedora

### ISSUE THREAD

**Issue by bkmgit** [WeblateOrg/weblate#3093]
**Describe the bug**

Install requirements on Fedora/Rhel/CentOS need update, the dependency typelib-1_0-Pango-1_0 is not in recent repositories

**To Reproduce**
see [here](https://github.com/WeblateOrg/weblate/blob/5c59ef89df53941a291f5b33434ff6758c8e16cb/docs/admin/install/venv-redhat.rst)

**Expected behavior**

**Screenshots**

Not applicable

**Server configuration and status**

Fedora 30, Cent OS 8 + Epel

**Additional context**

typelib-1_0-Pango-1_0 is available for [
typelib-1_0-Pango-1_0](https://software.opensuse.org/package/typelib-1_0-Pango-1_0) and for Debian, the replacement is [gir1.2-pango-1.0](https://packages.debian.org/stretch/gir1.2-pango-1.0)

**Comment by nijel** [comment]
Fixed by https://github.com/WeblateOrg/weblate/pull/3094
