### ISSUE TITLE
Searching for context in Weblate

### ISSUE THREAD

**Issue by kees538** [WeblateOrg/weblate#3098]
I tried searching for context in Weblate.
I searched for the reference E6L2o.
In Pootle I got a match after about 10 seconds
In Weblate it took several minutes and it found no match.
I did the following in weblate:
In the main window I went to Tools > Find (don’t know the exact English
words, because I see them in Dutch)
I fill in the searched item in the box Find.
I tick all the boxes.
I leave the rest unchanged.
I chose my language. (it will be useful if my language is default)

**Describe the solution you'd like**
To make it possible to search for context
Make my language the default language to search in.

**Comment by nijel** [comment]
Search is currently being rewritten and that should address this. Part of that is already in master ready for the 3.9 release, second part will land for the 3.10, see https://github.com/WeblateOrg/weblate/issues/2643 for more details.

**Comment by kees538** [comment]
Thanks Michal. I didn't notice this change.
Any idea when this is going to be live?
I hope it will be live before we migrate to Weblate.

Kind regards, Kees

Thanks Mi
Michal Čihař schreef op 09.10.2019 09:13:

**Comment by nijel** [comment]
Live where? Most of that is already in our repository.
