### ISSUE TITLE
Notification about commits and pushes

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3102]
**Is your feature request related to a problem? Please describe.**
It would be nice to have notification options for commits and pushes as this information can be useful for other project participants and automating it will remove the human factor.

**Describe the solution you'd like**
To have in your profile notification settings two more options - "On commit" and "On push"

**Describe alternatives you've considered**
Alternative would be to manually notify interested parties via e-mail/messengers, but that removes automation from the process.
Also Gitlab, for example, have notification mechanism but it will work only for push, not for commit.
I also tried to write a script and to call it using an [addon](https://docs.weblate.org/en/latest/admin/addons.html#executing-scripts-from-addon), but unfortunately it is not very flexible, you cannot pass data to the script like component name, who did the commit/push etc.

**Comment by nijel** [comment]
Adding new notifications should be easy, you just need to add new notification class for each:

https://github.com/WeblateOrg/weblate/blob/6857de6088d49bd80d8bbd2808590cdbb5c29a36/weblate/accounts/notifications.py#L356-L360

And add corresponding templates: https://github.com/WeblateOrg/weblate/tree/master/weblate/templates/mail

PS: You can write addons in Python and process anything there, the environment for scripts is indeed limited, but it can be easily extended.

**Comment by ptisserand** [comment]
Hi, does this issue still need some work ?

**Comment by nijel** [comment]
Yes, the notification is not yet implemented.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
