### ISSUE TITLE
Option to resolve comments

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#3103]
**Is your feature request related to a problem? Please describe.**
Some translators are using comments to ask questions, right now it's not that easy to be able to answer to questions and to find new ones. 
So here I see two problems:
  1. being able to answer to people by quoting them, or by being able to reply to a specific comment
  2. being able to see specifically new questions/comments: so to be able to mark a comment as "read" for example to not see it in the future when filtering the translations by comments

**Describe the solution you'd like**
I guess it would need two different solutions. 

For problem 1, the easiest solution would be to allow markdown in the comments, I know we can use `@` to mention users, but apparently you cannot quote someone for example, which could be really useful. 

For problem 2, I'm not quite sure: maybe being able to mark a comment as read, and add new filters to "read/unread/all" comments would be enough?

**Describe alternatives you've considered**
Another solution could be to add a new feature specifically for questions, but I guess it would be redundant with comments, so not so good I think.

**Comment by nijel** [comment]
Thanks for your issue, but it's always better to post one topic per issue, it's hard to track when there are multiple ones :-). I've created separate one for markdown in comments: https://github.com/WeblateOrg/weblate/issues/3104

Back to problem 2 - having way to resolve conversation and not show these by default makes certainly sense. Filtering such things will become easier once https://github.com/WeblateOrg/weblate/issues/3007 is implemented.
