### ISSUE TITLE
Flag unchanged translations as "Needs editing" addon also flags the source language

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3108]
**Describe the bug**
If you install "Flag unchanged translations as "Needs editing" addon and also have "Edit base file" check on when a new string added to source language it is marked as "Needs editing"

**To Reproduce**

1. Enable editing of base file ("Edit base file" in component settings is on)
2. Install "Flag unchanged translations as "Needs editing" addon
3. Add a new string to base file in VCS
3. After Weblate updates (via Gitlab webhook in my case) the newly added string is marked as "Needs editing"

**Expected behavior**
I think this addon shouldn't have effect on source language.

Note: My source language is Russian

**Server configuration and status**
 * Weblate 3.9-dev
 * Python 3.5.3
 * Django 2.2.5
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.6
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.11.0
 * Pillow 6.1.0
 * python-dateutil 2.8.0
 * lxml 4.4.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.10.3
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20181111
 * ruamel.yaml 0.16.5
 * Mercurial 4.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * Celery: memory://, N/A, eager
 * Platform: Linux 4.9.0-3-amd64 (x86_64)

**Comment by nijel** [comment]
The addon skips source language units (it's called template in the sources):

https://github.com/WeblateOrg/weblate/blob/78bb83405e04c0ce7c364da2b79c8275941dbe4c/weblate/addons/flags.py#L71

Maybe you have also installed Flag new source strings as "Needs editing" addon?

**Comment by tariver** [comment]
I recreated this behaviour from scratch - created a new project and then a component from a repository that isn't used anywhere else, installed only this addon and then added a new string via Gitlab web-interface.

**Comment by nijel** [comment]
Okay, I was looking at different addon, this one indeed behaves wrongly in this case.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
