### ISSUE TITLE
Language consistency addon not working

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3111]
Sorry to ask, but the documentation doesn't elaborate much about this addon. How it is supposed to work? My guess is that you need machine translation for language detection so I enabled two of them - Yandex and Microsoft Terminology Service. They work (I see suggestions from both services in "Machine translation" tab) but after I installed "Language consistency" nothing changed in my component translations (almost, I'll write about it below) although I certainly have some English translations in my German file.
Or do you need Google Translate enabled to make this addon work?

The only thing that actually changed is that new languages were added to components. As I mentioned before (#3086 ) one of my components has "English (United States)" and the others have just "English" language. After installing "Language consistency" addon "English" was added to the first one and "English (United States)" to all others. These new languages had no string translated.

I removed these languages by going to Manage>Repository Maintenance and hitting "Cleanup" and "Reset" buttons, but static at the project are still showing as if there is still one completely untranslated language. For example this component has 100% translation to three languages, but at the top right it shows 75%, as if there are four languages one of which is not translated.
![Screenshot from 2019-10-15 11-45-45](https://user-images.githubusercontent.com/36223356/66815847-ad3ed680-ef41-11e9-912c-7e9859e84884.png)

It's the same on component list on project level:
![Screenshot from 2019-10-15 11-48-42](https://user-images.githubusercontent.com/36223356/66815977-f42ccc00-ef41-11e9-95db-eff0775c6aeb.png)

**Comment by nijel** [comment]
[Language consistency](https://docs.weblate.org/en/latest/admin/addons.html#language-consistency) ensures that same languages are present in all components. I think you are actually looking for [Automatic translation](https://docs.weblate.org/en/latest/admin/addons.html#automatic-translation).

**Comment by tariver** [comment]
Sorry, I misunderstood what this addon does, I thought it looks at strings inside component and marks those that are not in proper language. Thanks for clearing it out.

But is there any way to update statistics of components now, so it doesn't count fourth language?

**Comment by nijel** [comment]
You can remove the language (after removing the consistency addon).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed by improving the documentation.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
