### ISSUE TITLE
Update with pip

### ISSUE THREAD

**Issue by maicol07** [WeblateOrg/weblate#3114]
Hi,
is it possible to update Weblate using PIP (for example from 3.8 to 3.9)? If yes, how?
I've already tried the command `pip install --upgrade weblate` without success
Thanks

**Comment by nijel** [comment]
What didn't work on that? You will need to follow [ugprading instructions](https://docs.weblate.org/en/latest/admin/upgrade.html) then.

**Comment by maicol07** [comment]
Do I have to download the zip and extract it in weblate folder?

**Comment by nijel** [comment]
Probably your mirror is outdated and doesn't yet see 3.9 released few hours ago. Try using pypi.org directly...

**Comment by maicol07** [comment]
I've edited default mirror in `~/.pip/pip.conf` to:
```
[global]
index-url = https://pypi.python.org/simple

[install]
trusted-host = pypi.python.org
```
and it works with `pip install --upgrade Weblate`
Thank you @nijel
