### ISSUE TITLE
Daily Digest not working for 'Strings needing action'

### ISSUE THREAD

**Issue by sanecito** [WeblateOrg/weblate#3120]
**Describe the bug**
Despite having Daily Digest set for various triggers, of the two type I've received, 'New string', and 'Strings needing action', 'Strings needing action' isn't being condensed down to a digest on hosted.weblate.org:

![image](https://user-images.githubusercontent.com/3056597/67023602-e8fbac80-f0b7-11e9-8702-431d01b44bad.png)

**To Reproduce**
1. Add a project that has components w/ strings needing action on 2+ components to your watch list on hosted.weblate.org
2. Configure your 'Strings needing action' notifications to be Daily Digest:

![image](https://user-images.githubusercontent.com/3056597/67023968-7d660f00-f0b8-11e9-859a-722a1bee13e6.png)

**Expected behavior**
I get a single, Daily email about strings needing action similar to new strings

**Screenshots**
See above ones

**Server configuration and status**
It's hosted.weblate.org

**Additional context**
N/A

**Comment by nijel** [comment]
Looking at the code, you should get one notification for each of translations, is that correct?

It probably would make more sense if it would send just one mail listing translations having such strings...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
