### ISSUE TITLE
language consistency creates files with different language code

### ISSUE THREAD

**Issue by aparcar** [WeblateOrg/weblate#3126]
**Describe the bug**
Using the language consistency created new files in the zn_Han{s,t} format while other existing translations use zh_{cn,tw}. This results in a mix of PO files. This is likely as zh_{cn,tw} is aliased to the other format, however the existing format is required to work with browser detection.

**Expected behavior**
Ideally (hosted.)weblate would ask which format is desired before creating new languages.

**Server configuration and status**
Hosted

**Additional context**
From my (short) research I understand that browsers still use zh_{cn,tw} as accepted language headers, therefore these steps. If I'm wrong about that I could move all language files to zh_Han{s,t}.

**Comment by nijel** [comment]
Using same language codes is not always desired. For example translating iOS and Android application you want to use language codes used by the platform. That's why this is [configurable per component](https://docs.weblate.org/en/latest/formats.html#adding-new-translations).

**Comment by aparcar** [comment]
Thank you that should fix the issue.
