### ISSUE TITLE
Curl and WLC

### ISSUE THREAD

**Issue by ersvltan** [WeblateOrg/weblate#3134]
Hello,

I have a question, but I don't know where to ask. So I opened an issue.

Can you describe when to use CURL and when to use WLC CLI. As far as I know WLC uses the same API, and there shouldn't be any difference, except WLC launches on the client side. Are there any difference? Or I misunderstood?

Thanks.

**Comment by nijel** [comment]
Just use whatever you want :-). wlc just wraps the API to make it easier to use.

**Comment by ersvltan** [comment]
> Just use whatever you want :-). wlc just wraps the API to make it easier to use.

Thanks for the quick answer. Now I have another quite connected to this topic. So I want to use Weblate API in my workflow. I saw the minimum hardware requirements of Weblate. What is the recommended hardware to be able to proccess many requests at the same time. Let's say I have 100 000 of users, and they will send the same request(for instance api/translation/project/component/en/file) at the same time, how many resources I need to accomplish this task? Thanks.
