### ISSUE TITLE
Placeholders for rendered size check [$50]

### ISSUE THREAD

**Issue by IlDucci** [WeblateOrg/weblate#3140]
Good evening. I would like to request certain upgrades and additions to the string length rendering checks:

**Is your feature request related to a problem? Please describe.**
I find two problems when it comes to check the renderings:
 - I'm using the tool to translate the dialogues of a game. Imagine you're using control codes within your dialogues. Just as they can be marked for references, can certain string combos/control codes be marked to have specific widths, from zero (In the case of, for example, color control codes) to a fixed width (For example, variables that draw names).
- ~~Call me micromanager, but sometimes I'd like to see the actual sample of the rendered dialogue. Maybe I have a word that's too long and that's going over the limit because of that reason, but I won't be able to know it's the problem unless I actually see the rendered sample. Or maybe I'd like to do the line breaks manually to improve the text flow. Is there a way to display the sample renders to the user?~~

**Describe the solution you'd like**
 - Add support for a table of custom lengths for specific control codes or words/partial words. Those lengths could be zero, a specific value, or a value measured in characters, perhaps (For example, I could use a sample name/temp name as a way to calculate the widths).
 - ~~Display the font rendering samples as graphics during the translation/revision process.~~

**Describe alternatives you've considered**
 - About lengths, there's the chance that the same project has more than one string length values. Maybe the values could be targeted per component or maybe there could be a single, "default" value and then specific values for the minority components that have different string length parameters.
 - ~~About the font rendering, probably the best way to avoid a server overload is to make the graphic display on-demand, by the touch of a button, for example. Having a lot of images rendered and displayed could cause havoc in Zen mode. But if the actual TTF can be used as a web font, maybe the system could use it to display on-the-fly modifications, which could even work in Zen mode.~~

**Additional context**
There's not much else I can think of right now.

**Comment by nijel** [comment]
Can you please keep it one feature per issue? I've separated https://github.com/WeblateOrg/weblate/issues/3143

**Comment by IlDucci** [comment]
Sorry about that.

**Comment by nijel** [comment]
Can you please clarify how the control codes look like? To me it looks like string replacement would be better fit for this than manually specifying width. That way it will also look better with #3143.

**Comment by IlDucci** [comment]
Right now we have a few, so let me write some similar examples (I'm a translator, so I cannot speak about the naming decisions here)...

<COLOR_RED> as an example for coloring, <PORTRAIT_NAME_NUMBER> for displaying portraits and <PROTAGONIST_FULL_NAME> for displaying a name and a surname. The first and second cases should count as zero, and the second one, well... I personally was thinking of adding the equal value to the max amount of chars available in memory (For example, 8 chars for the name + the space of the space character + 8 chars for the surname).

**Comment by nijel** [comment]
Effectively, https://github.com/WeblateOrg/weblate/issues/3546 is prerequisite here to support space and other special chars in the strings.

**Comment by IlDucci** [comment]
I've found an error: it is not possible to add more than one empty entries in the replacements string.

#, replacements:{COLOR-GREY}:""

Makes any elements called {COLOR-GREY} dissappear. This is a behavior I would like to keep.

Writing this:
#, replacements:{COLOR-GREY}:"":{COLOR-GARNET}:"":{VARIABLE-01}:99

Causes a server error when pulling the new changes, and the server considers it is up-to-date.

**Comment by nijel** [comment]
Can you please open separate issue for that? Preferably including the traceback. Most likely it's a bug in the parser introduced by https://github.com/WeblateOrg/weblate/issues/3546

**Comment by IlDucci** [comment]
> Can you please open separate issue for that? Preferably including the traceback. Most likely it's a bug in the parser introduced by #3546

Done. Check #4136.
