### ISSUE TITLE
Show rendered text from size check [$25]

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3143]
Split from https://github.com/WeblateOrg/weblate/issues/3140 by @IlDucci

Good evening. I would like to request certain upgrades and additions to the string length rendering checks:

**Is your feature request related to a problem? Please describe.**
I find two problems when it comes to check the renderings:
 - Call me micromanager, but sometimes I'd like to see the actual sample of the rendered dialogue. Maybe I have a word that's too long and that's going over the limit because of that reason, but I won't be able to know it's the problem unless I actually see the rendered sample. Or maybe I'd like to do the line breaks manually to improve the text flow. Is there a way to display the sample renders to the user?

**Describe the solution you'd like**
 - Display the font rendering samples as graphics during the translation/revision process.

**Describe alternatives you've considered**
 - About the font rendering, probably the best way to avoid a server overload is to make the graphic display on-demand, by the touch of a button, for example. Having a lot of images rendered and displayed could cause havoc in Zen mode. But if the actual TTF can be used as a web font, maybe the system could use it to display on-the-fly modifications, which could even work in Zen mode.

**Additional context**
There's not much else I can think of right now.

**Comment by IlDucci** [comment]
I haven't been able to test this on an environment, so I'm going to ask things based on what I'm figuring out via reading the code:
 - Is it possible to have access to the preview at all times, not only when the limits are reached?

**Comment by nijel** [comment]
We currently don't have UI for this. All we do is to show failed checks and this now includes the rendered images.

**Comment by IlDucci** [comment]
A friend of mine made a temp server and I've seen the current status (master from 3.11-dev, taken yesterday). I was unable to get the proper font-family being read out, all the samples were still displaying SourceSansPro. Window size and font size were read properly.

He also had this error:  [error] 158#158: *538 open() "/app/data/static/font-source/WOFF2/TTF/SourceCodePro-Semibold.ttf.woff2" failed (2: No such file or directory), client: 81.38.99.139, server: , request: "GET /static/font-source/WOFF2/TTF/SourceCodePro-Semibold.ttf.woff2 HTTP/1.1", host: "91.134.243.113:9000", referrer: "http://91.134.243.113:9000/static/font-source/source-code-pro.css?v=3.11-dev"

Though I do have seen how does it look like. Maybe making it a permanent toggeable window, like Glossary and Source information, would be nice in the future (though I'd be worried if this was implemented in Zen, even if that would be much nicer for the translator, it could increase the server load).

**Comment by nijel** [comment]
Hmm, I've just tested it and it seems to work properly for me. I've recently fixed possible issue with using bold font faces, but you should still end up with correct family.

**Comment by IlDucci** [comment]
I tried two different fonts: A custom one I made, which is my target font and should be marked as Regular, and a copy of Stencil from my Windows Fonts folder just to be sure I wasn't breaking anything with the font. Both fonts did not appear in the render.

**Comment by IlDucci** [comment]
I just went to the sample server again and my custom font worked now, maybe there was a caching problem of some sorts. So now I'm seeing the previews whenever the check fails.

The current system works with the checks, but I'd be interested on seeing this window at all times. That's what's making me doubt over if I should accept or reject the changes for the bounty.

**Comment by nijel** [comment]
Can you please open separate issue for that?
