### ISSUE TITLE
Difference between "Edit source string" and "Edit source strings"

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3148]
I understand that some permission names are self-explanatory, but some make you wonder and [documentation](https://docs.weblate.org/en/latest/admin/access.html#list-of-privileges) doesn't elaborate much.

What is the difference between "Edit source string" and "Edit source string**s**" permissions?
By experimenting I found out that "string" enables adding additional context and translation flags, but adding the "string**s**" options seem not to change anything.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. The permission description has been simplified too much in 187e50e3c54.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
The source strings permission allow to edit actual source string for monolingual translations. This should be further improved with https://github.com/WeblateOrg/weblate/issues/2831
