### ISSUE TITLE
Updating .po files in the git repository does not update "needs editing" count

### ISSUE THREAD

**Issue by rimrul** [WeblateOrg/weblate#3151]
**Describe the bug**
I've updated a bunch of strings in the [Git Manpages translation (German)](https://github.com/jnavila/git-manpages-l10n/pull/35) that where previously marked fuzzy, but aren't anymore. I expected the count of ["Strings that need editing" on Weblate](https://hosted.weblate.org/projects/git-manpages/translations/de/) to go from ~820 to ~520, but it didn't. 

**To Reproduce**
1. Take a weblate project based on po files and a git repository
2. Update some fuzzy strings via git to not be marked fuzzy anymore
3. Look at the number of fuzzy strings on weblate

**Expected behavior**
Significant drop of "Strings that need editing".

**Server configuration and status**
Hosted Weblate

**Comment by rimrul** [comment]
I've just found that Weblate doesn't update the count **everywhere**. It updates the count here:

https://hosted.weblate.org/translate/git-manpages/translations/de/?type=fuzzy

but doesn't update the one here:

https://hosted.weblate.org/projects/git-manpages/translations/de/

or the one here:

https://hosted.weblate.org/projects/git-manpages/translations/

**Comment by nijel** [comment]
Looks like caching issue, we really need better approach here to gather summary stats. The current one is quite slow and prone to race conditions.
