### ISSUE TITLE
Status widget for language progress across all components and projects

### ISSUE THREAD

**Issue by romanr** [WeblateOrg/weblate#3153]
**Is your feature request related to a problem? Please describe.** 

Status Widget that will show "global" language completion across all projects/components in entire Weblate installation.  
We have one product split into projects and components. Want to show progress across each language in whole product as percentage.

**Describe the solution you'd like**   

Currently you can put `-` in place of language to see the all languages:
` /widgets/project/-/svg-badge.svg`

So for "global" languages it could be like:
`/widgets/-/pl/svg-badge.svg`

**Comment by nijel** [comment]
The only per site widget is currently open graph image: https://hosted.weblate.org/exports/og.png
