### ISSUE TITLE
Continuous localization for Mercurial

### ISSUE THREAD

**Issue by m-schieder** [WeblateOrg/weblate#3156]
Hello,

I want to write a program for a Mercurial repository that will automatically find translatable text when a "PUSH" is executed and saves these texts in .po files and uploads them to Weplate.
When the texts have been translated, they should be automatically downloaded and committed to the repository. It should not matter where the remote repository is located (on a server or on any hosting site).

I wanted to ask if there is a possibility for a demo system with which I can develop it or if I have to set one up myself?

**Comment by nijel** [comment]
You can use [Hosted Weblate](https://weblate.org/hosting/) for that. We offer gratis plans for libre software. Also, check [our docs](https://docs.weblate.org/en/latest/admin/continuous.html) to see how to integrate Weblate.
