### ISSUE TITLE
Add external links to string

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3161]
**Is your feature request related to a problem? Please describe.**
It many cases it might be useful to include link to provide additional context to a string. The most obvious use case is link to web application where the string is used.

**Describe the solution you'd like**
Allow to add a URL to the string and present it together with other additional context.

**Comment by comradekingu** [comment]
I find Wikipedia is great for this, seeing as it often has good translations and alternative when switching language.
Maybe that is something for machine translation?

**Comment by yarons** [comment]
It's super relevant when we have explanation about the UI, for example:
Click File -> Print -> Number of pages.

If I don't have the context I can translate this freely without knowin how was the UI actually translated (if it wasn't me or I forgot what I translated, searching is also an option but it's less convenient).
