### ISSUE TITLE
API Screen, code blocks RTL instead of LTR

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#3171]
**Describe the bug**

**To Reproduce**
1. Switch to Hebrew
2. Go to Profile
3. Click on API Access
4. Look at the screen

**Expected behavior**
The code blocks should be LTR, it looks weird on RTL and I cannot understand the order of arguments.

**Screenshots**
![weblate_api_bug](https://user-images.githubusercontent.com/406826/68118278-44c39380-ff08-11e9-9378-3a55f6c71299.png)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
