### ISSUE TITLE
Follow menu is exceeding screen area in RTL

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#3172]
**Describe the bug**
When clicking the "Follow" menu (appears on the right in RTL interface) the menu is popping up but expands to the left and exceeds the screen area showing only part of the menu.

**To Reproduce**
1. Switch to RTL
2. Go to a translation project
3. Click the follow button
4. Look at the menu that expands

**Expected behavior**
Should be kept inside the screen area so all options will appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/406826/68126389-5a42b880-ff1c-11e9-8ae4-859a0120435e.png)

**Server configuration and status**
It's 3.9.1.

**Comment by yarons** [comment]
Tried changing the rules for `.pull-right > .dropdown-menu` in inspector, switched between left and right and it's now `left:0` and `right: auto`, the menu now aligns correctly, is there an RTL override CSS? I can try and add this myself.

**Comment by nijel** [comment]
You can use `.dir-rtl` in the CSS:

https://github.com/WeblateOrg/weblate/blob/ab4ebe34441db841c8ef87ec3ba6af5df30ac0de/weblate/static/style-bootstrap.css#L70-L72
