### ISSUE TITLE
Extra lineshifts in zen translation fields

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3175]
New with 3.10, if not after that.
![image](https://user-images.githubusercontent.com/13802408/68179698-bf33f800-ff88-11e9-8968-b346fa289f99.png)
https://hosted.weblate.org/translate/orisa/bot/nb_NO/?checksum=5f167730969d175

https://hosted.weblate.org/translate/selfoss/translations/ca/?checksum=964fdd647ffda3d2
for one line.

**Comment by nijel** [comment]
Confirmed, sizing of plural editor is wrong after 0196629.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
