### ISSUE TITLE
Multiple repositories with different file formats

### ISSUE THREAD

**Issue by amiuhle** [WeblateOrg/weblate#3176]
**Describe the solution you'd like**
We have two projects that share translations. In this case it's an Android and an iOS app, but it could also be backend and frontend of some kind. The projects are located in two different repositories and the file formats are different.

This could be solved by having a 1:n relationship between components and version control systems, and a 1:1 relationship between version control and file configuration.

**Describe alternatives you've considered**
A valid workaround is to only have one repository and import the translation files as a download with a different format from the second project via some task runner.

**Comment by nijel** [comment]
You can share repositories inside Weblate, see https://docs.weblate.org/en/latest/vcs.html#weblate-internal-urls (in fact Weblate does this automatically in case you add existing repo again).

**Comment by amiuhle** [comment]
@nijel I want the opposite: Multiple repositories per component.

Edit: I want to share translations between repositories, not the other way round.

**Comment by nijel** [comment]
One component is always for one file, so that will never work. You can have any number of components within one project.

**Comment by nijel** [comment]
Maybe https://docs.weblate.org/en/latest/faq.html#how-to-translate-multi-platform-projects would be helpful to you as well.

**Comment by ochorocho** [comment]
@nijel just tried to set this up for @amiuhle
Is translation propagation supposed to update all ocurrences of the given key?

I get only a suggestion
![Bildschirmfoto 2019-11-06 um 16 41 19](https://user-images.githubusercontent.com/4623070/68313853-90677000-00b5-11ea-8a60-17fe5ab39cc2.png)

**Comment by nijel** [comment]
It works only on translating, I've recently explained it here: https://github.com/WeblateOrg/weblate/issues/3166#issuecomment-551064246

Probably time to put this into the docs :-)

**Comment by ochorocho** [comment]
Thanks for your response. :-)
