### ISSUE TITLE
Clicking edit source in zen mode does not work

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3179]
https://hosted.weblate.org/zen/your-local-weather/strings/nb_NO/?type=nottranslated
also happens in
https://hosted.weblate.org/zen/mastodon-twitter-crossposter/translations/nb_NO/?type=fuzzy

![image](https://user-images.githubusercontent.com/13802408/68270110-32567080-0054-11ea-84f3-dcc27f9a8386.png)

The checksum is missing in the URL

checksum=
vs
checksum=saio1uia1iuj12781812 (for languages other than source)

Edit:
Going to the regular editor by clicking "Edit" on any string presents the checksum when clicking to edit the source string from there

![image](https://user-images.githubusercontent.com/13802408/68270332-dc35fd00-0054-11ea-8e16-b74e632ad2ac.png)

https://hosted.weblate.org/translate/your-local-weather/strings/nb_NO/?checksum=6d6dae946af114f1 for example.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
