### ISSUE TITLE
documentation: Missing dogslow information

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#3182]
I'm currently preparing an upgrade of Weblate and I'm reviewing the changes on the settings.py, and I discovered some references to dogslow in it, but there's very info in the documentation about it.
Only mention I found is in https://docs.weblate.org/en/latest/debugging.html#performance-issues (with a broken link btw :)), and it seems to say that it's optional? 
However the [settings-sample](https://docs.weblate.org/en/latest/admin/sample.html#sample-configuration) shows that there is a middleware for Dogslow: 

```
MIDDLEWARE = [
    "weblate.middleware.ProxyMiddleware",
    "dogslow.WatchdogMiddleware",
```

A log handler for it too:
```
"dogslow": {
            "level": "WARNING",
            "class": "sentry_sdk.integrations.logging.EventHandler",
        },
[...]
"dogslow": {"level": "WARNING", "handlers": ["dogslow"]},
```

and some variable that are not documented in  https://docs.weblate.org/en/latest/admin/config.html
```
# Logging slow requests
DOGSLOW_LOG_TO_SENTRY = bool(SENTRY_DSN)
DOGSLOW_LOGGER = "dogslow"
DOGSLOW_TIMER = 60
```

Could be nice to improve a bit the doc about it.
And since I'm not using sentry, I guess I won't be able to use dogslow: should I comment out the middleware / remove the log handlers, etc?

**Comment by nijel** [comment]
It's still optional, it's just enabled in example configuration. Without Sentry, it still logs slow request, so it is useful even without it. But you're right that the docs on this is missing.

**Comment by surli** [comment]
Ok, thanks for the info!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
