### ISSUE TITLE
display context key on nearby strings and other occurences

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#3183]
**Is your feature request related to a problem? Please describe.**
If the same source is used in two translations keys, in the same components (which should not happen, but that's another discussion :)), it's very difficult to understand the UI from nearby strings and other occurences, since they are displaying exactly the same info. See the gif below.

**Describe the solution you'd like**
The context key should be available somewhere in the UI in nearby strings / other occurences, either by a tooltip or directly on the tables.

**Describe alternatives you've considered**
Right now the only way I've found is by clicking on the links and checking the UI on the page.

**Additional context**
![Peek 06-11-2019 13-25](https://user-images.githubusercontent.com/1478232/68298432-a404dd80-0099-11ea-893d-e55c0b0ec4dc.gif)

**Comment by comradekingu** [comment]
@surli So you want to be able to expand any string that is duplicated?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
