### ISSUE TITLE
Mercurial rebase and collapse merge style

### ISSUE THREAD

**Issue by Wohlstand** [WeblateOrg/weblate#3190]
It's known that here is the Git Squash feature exists to help to avoid thousands of mini-commits and make one big commit instead. However, Mercurial lacks it. Natively, Mercurial has the "--collapse" option to rebase with the squashing of commits into one giga-commit.

**Describe the solution you'd like**
Make a similar extension to Git Squash, but for Mercurial over `hg rebase --collapse ...` option or similar other.

**Comment by nijel** [comment]
It's certainly possible. The [Git squash addon](https://docs.weblate.org/en/latest/admin/addons.html#squash-git-commits) has more options how to squash commits, though there is no need to match all features in Mercurial.

**Comment by nijel** [comment]
Given decreasing Mercurial adoption over the years, I don't see likely we would ever implement this. Pull requests would still be accepted, though!
