### ISSUE TITLE
Replace Zeep by suds-community

### ISSUE THREAD

**Issue by scarabeusiv** [WeblateOrg/weblate#3192]
As a zeep is an optional runtime dependency and mandatory dependency for testing it is borked with new Tornado (5.x+) releases that work with python 3.8.

Looking on the github there is not much activity upstream in that directon to get the issues fixed. As such it is technically quite challenging to get the weblate running just using the newest python stack. Could some other library be used to provide the functionality?

**Comment by nijel** [comment]
Any soap client would work as replacement. At time of writing this code, zeep seemed like best option, that's why it was chosen back then.

Related issue on zeep: https://github.com/mvantellingen/python-zeep/issues/990

**Comment by nijel** [comment]
Possible options to address this

* Make zeep work with Python 3.8, see https://github.com/mvantellingen/python-zeep/issues/990 or https://github.com/mvantellingen/python-zeep/pull/1006
* Replace zeep with something else, [suds-community](https://pypi.org/project/suds-community/) might be an option (most likely it is the only option)

**Comment by nijel** [comment]
Hmm, there are no issues with Zeep on Python 3.8 (see https://github.com/mvantellingen/python-zeep/issues/1055#issuecomment-585948741 and https://github.com/mvantellingen/python-zeep/pull/1034) and the Tornado is optional dependency not needed by Weblate.

Still, the question is which of zeep and suds-community is less dead project :-).

**Comment by nijel** [comment]
Closing for now as there doesn't seem to be good solution now. The zeep library seems like best one, but it currently lacks maintenance. The suds community fork has some maintenance, but also not very much moving forward.
