### ISSUE TITLE
No translation stored, marked Has been translated, but history shows new translation

### ISSUE THREAD

**Issue by SantosSi** [WeblateOrg/weblate#3194]
**Describe the bug**
Sometimes, when there is a long pause (hours) between starting to enter translations and resuming and finishing it, the translations are marked Has been translated.

**To Reproduce**
1. Start translating and leave the form open
2. Stop translating for hours
3. Resume translating
4. Complete translating: it shows 100%
5. Next day: check the set, it became incomplete

**Expected behavior**
When history lists an existing translation, add it to the translated field, instead of marking it uselessly to be reviewed.

**Comment by comradekingu** [comment]
@SantosSi Zen or regular, and what browser?

**Comment by SantosSi** [comment]
Regular on Firefox 70 on Debian Linux

**Comment by nijel** [comment]
As you see the previous edits in the history, it seems that the content was not properly written to the file. Do you see some logs about disappeared strings? What file format do you use?

**Comment by SantosSi** [comment]
It's weird to see the translation in the history, but the translated string is empty. As this combination is paradox, it could be identified and sanitized automatically by filling the last string from the history.
No logs, no file format, all online on the web interface.

**Comment by nijel** [comment]
I mean server logs. This can happen when Weblate fails to save the changed string to the backend file. This would be visible there and that's why I ask what file format do you use for storing the translations.

**Comment by SantosSi** [comment]
I am not sure: did not see logs anywhere in the process and because the translations were done online there is no file format I was in touch with.

**Comment by SantosSi** [comment]
Example: https://hosted.weblate.org/translate/osmand/main/pt/?checksum=b4b6967a73e7e163

**Comment by nijel** [comment]
Thanks, finally we have something to diagnose. It seems that the problem here is source string change - the check doesn't see this event and assumes that it's same string that has been translated.
