### ISSUE TITLE
Configurable SQL backups

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#3200]
**Is your feature request related to a problem? Please describe.**
We used to perform automatically backups of our database using pg_dump and gzip. Now Weblate perform backups automatically but they're not gzipped. It might be on purpose since Borg is doing diffs when saving, but when no Borg instance is configured it's a bit annoying. 

See the difference:
```
$ du -sh /var/weblate/backup/weblate_20191112.sql.gz 
2.3G	/var/weblate/backup/weblate_20191112.sql.gz
$ du -sh /var/weblate/data/backups/database.sql 
6.9G	/var/weblate/data/backups/database.sql
```

**Describe the solution you'd like**
When no borg instance is configured, at least the database backup should be compressed.

**Describe alternatives you've considered**
For now I'll disable the backups from Weblate and keep my old script to perform backups.

**Comment by nijel** [comment]
The file is uncompressed to be easier to do incremental backups. With compressed files, it won't work regardless whether you use borg or some other tool.

**Comment by mayeulk** [comment]
In my use case, I'd prefer to have compressed files than incremental backups.
If some users prefer the later, maybe letting them choose would be great.

**Comment by nijel** [comment]
Patches are welcome to make that configurable, related code is here:

https://github.com/WeblateOrg/weblate/blob/88c30780f06b900dd55a73d37c6f47f950773cdf/weblate/utils/tasks.py#L66-L86

**Comment by nijel** [comment]
Based on https://github.com/WeblateOrg/weblate/issues/3255, there should be probably three options:

* uncompressed backups (default)
* compressed backups
* none backups
