### ISSUE TITLE
Too strict requirements to allow in-distribution updates

### ISSUE THREAD

**Issue by scarabeusiv** [WeblateOrg/weblate#3206]
If you take look on openSUSE packages in obs I have to now convert == to >= to allow version updates we deliver sometimes faster than the bot:

(note the diff-match-patch is unrelated to workaround something in the translation-toolkit deps)
```
# do not pull in the diff match patch
sed -i -e '/diff-match-patch/d' requirements.txt
# do not hardcode versions
sed -e 's:==:>=:g' \
    -i requirements.txt \
    -i setup.py
```

Even now the weblate 3.9.1 is unresolvable for openSUSE because new 2.6 Pillow caused some regressions:
  https://build.opensuse.org/package/show/M17N:l10n.opensuse.org/weblate

And if you look on the release product if I would like to base the weblate there I would have to update quite few python packages.

Would it be possible to have pinned deps by depandbot and alternatively a list of least possible versions next to it we could use instead? We run the testsuite so we would see if something borked with the older versions in depgraph...

**Comment by nijel** [comment]
Honestly, I'm not sure what is the best approach for the dependencies. We used to have quite loose dependencies, but then it often happened that new version changed something and that broke Weblate. That's why I've switched to tightly controlled dependencies for many libraries. This also has nice benefit that whenever new library is released it's automatically tested by CI and we notice most of the breakages immediately.

**Comment by scarabeusiv** [comment]
I agree that the development with pinned latest versions is pretty good. But it is honestly pain in the butt to track in distributions as we can't overall update that many packages in the python stack.

Thats why I think it might be good idea to have set of two. One hardcoded with latest and other with some more flexible oldest possible version)...

**Comment by nijel** [comment]
Do you have some example of project that does this?

**Comment by scarabeusiv** [comment]
I've seen some that have `requirements.txt` used by their travis run and hand written dependencies in `setup.py`, where they even have them without version tbh, but it is probably just an ommision on their side :).

ATM you use the `requirements.txt` in https://github.com/WeblateOrg/weblate/blob/master/tox.ini and `requirements-travis.txt` in .travis.yml I guess this should both use same requirements, be it the ones with all the latest hardcoded versions, while there would be another requirements the distributors could use.

Now if you want to test the lowest possible requirements that would be stored for the distributors you would have to define another enviroment for the travis and or for the tox to run it too...

**Comment by nijel** [comment]
The `requirements-travis.txt` currently lists additional requirements for the CI environment, but it probably could be extended to cover more.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by scarabeusiv** [comment]
I don't think this will really help. It gets resolved on the rolling release distro, but it won't work on anything semi-stable. If you look on the Leap you can see it is having ~30 unresolvable packages and we are providing them, but with slightly older versions.

FWIW I can really just sed the requirements to not have any version part in the fields, but I wonder if is the best solution...

https://build.opensuse.org/package/show/M17N:l10n.opensuse.org/weblate

**Comment by nijel** [comment]
As long as you run the tests, it should be mostly safe to ignore the version constrains. There are exceptions though as broken kombu versions.
