### ISSUE TITLE
Auth0 registration fails when new user has same first name as already registered user

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#3230]
# Situation

1. Register a first user in weblate via auth0.
   - email: `jhon.first@example.com`
   - First Name: `Jhon`; last name: `First`
1. Upon this weblate automatically creates this user with:
   - email: `jhon.first@example.com`
   - username: `Jhon`
1. Login with a second user (first registration) via auth0 with:
   - email: `jhon.second@example.com`
   - First Name: `Jhon`; last name: `Second`
1. weblate also tries to create this user with:
   - email: `jhon.second@example.com`
   - username: `Jhon`
1. Despite of having different email addresses, it tries to create the same username a second time what results into registration error, something like "Registration not possible. Username and/or email and/or ... already taken."

# Solution variants

Considering in case registration and later authentication via social auth, specially auth0:

1. Weblate could stick to first name taken but check whether email is different, if yes just add something (e.g. counter) to this username, as `Jhon-1`.
1. Weblate to may set username==email for uniqueness
1. Fully drop the "username" pattern and only use "email" + "Full Name"

Potentially for data consistency reasons, approach 2. would be preferred.

May to expose it's control as env var (settings_docker.py), similar to `WEBLATE_SOCIAL_AUTH_USERNAME_EQUAL_EMAIL = true` (default `false`)

# Remark:

If this already can be solved with proper configuration, please consider as a question.

**Comment by nijel** [comment]
The social-auth should handle this gracefully, so the question rather is why the pipeline doesn't behave properly in such case.

Related code:

https://github.com/python-social-auth/social-core/blob/c8d172e3fe5129fe9c7814157684c2d83d7809e9/social_core/pipeline/user.py#L51-L58

**Comment by nijel** [comment]
Can you figure out what uid is Auth0 returning for such users? It is visible in Weblate in profile Account tab.

**Comment by nijel** [comment]
BTW: The email = username patter is not good fit for Weblate as we use usernames in URLs and comments, what would expose emails in such case.

**Comment by rhofer** [comment]
The UID returned from my auth0 instance in use are from the following kind:
- Person 1: oauth2|main-tenant-oidc|samlp|xxxxxx|A0002WNY
- Person 2: oauth2|main-tenant-oidc|samlp|xxxxxx|A0032M2P

(Retrieved from Django admin interface Home > Python Social Auth > User social auths, column UID)

**Comment by rhofer** [comment]
Meanwhile I tried with a 3rd user with same first name. Same error occurred.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by rhofer** [comment]
@nijel will this fix also end up in something like 3.9.1-3 as docker image on hub.docker.com? Asking, b'cause it's quite urgent to me since I was forced to stop translator onboarding on my production deployment.

**Comment by nijel** [comment]
It should be soon available in the `edge` tag and will be part of next release.

**Comment by rhofer** [comment]
@nijel just tested with `edge` . It works now as expected:

- First person: John
- Second person: Johna31bb7cecc0b442c

Thanks for the quick fix.
