### ISSUE TITLE
Solved: docker loaddata Import groups

### ISSUE THREAD

**Issue by michaelarlt** [WeblateOrg/weblate#3232]
I have exported groups in json file within my old weblate version 2.20
`./manage.py dumpdata auth.Group > /tmp/weblate_group`
i want to import them into the dockerized weblate latest version. I Habe moved the file to the data/backups/ Filder where weblate has access
`mv weblate_group groups.json`
`docker exec weblate weblate loaddata /app/data/backups/groups.json`
`Installed 32 object(s) from 1 fixture(s)`
so far it looks like a success but the groups arent there. Just de defoult ones are shown
Im not sure how exactly the django loaddata works but if someone can help, i would be happy

**Comment by nijel** [comment]
In 3.0 we switched to own user management from the one built into Django. So your groups were imported to the no longer used code. When upgrading the groups were migrated between those two, so the easiest approach would be to import to pre 3.0 container, upgrade it to 3.0.1 and then to current version. 

Alternatively you can try to run migrations code manually on current version, the related migrations are [here](https://github.com/WeblateOrg/weblate/blob/weblate-3.0.1/weblate/auth/migrations/0004_auto_20180508_1032.py) and [here](https://github.com/WeblateOrg/weblate/blob/weblate-3.0.1/weblate/auth/migrations/0005_groups.py).

**Comment by michaelarlt** [comment]
Thanks for the Answer. I got the Upgrade to latest 3.9.1 working and now i would like to migrate the mysql data into postgresql
i have tried to call `./manage.py dumpdata --all --output weblate.json` and then to `./manage.py loaddata weblate.json --database=postgresql` but im getting the error:
django.db.utils.IntegrityError: Problem installing fixture '/opt/weblate/weblate.json': Could not load contenttypes.ContentType(pk=1): duplicate key value violates unique constraint "django_content_type_app_labe
l_model_76bd3d3b_uniq"                                                                                                                                                                                             
DETAIL:  Key (app_label, model)=(auth, permission) already exists.

i also tried to dump without auth.permission but then it complains about the relationships which is logical
django.db.utils.ProgrammingError: Problem installing fixture '/opt/weblate/weblate.json': Could not load weblate_auth.Permission(pk=1): relation "weblate_auth_permission" does not exist                          
LINE 1: UPDATE "weblate_auth_permission" SET "codename" = 'billing.v...

so is there any way for example to migrate whole mysql data into a clean postgresql schema?

**Comment by nijel** [comment]
You probably forgot to flush the newly created table, see https://docs.weblate.org/en/latest/admin/upgrade.html#create-empty-tables-in-the-postgresql

**Comment by michaelarlt** [comment]
This issue/question can be marked as solved. I managed to migrate. Ill add some more explaination later, how i made it. Thanks a lot @nijel
