### ISSUE TITLE
Unable to push to Gitlab via Merge Request

### ISSUE THREAD

**Issue by maxking** [WeblateOrg/weblate#3237]
This happens because `master` branch is a protected branch by default and we try to force push to the Gitlab fork of Weblate when trying to create a Merge Request:

```
remote: GitLab: You are not allowed to force push code to a protected branch on this project.        
To gitlab.com:weblate/hyperkitty.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@gitlab.com:weblate/hyperkitty.git'
 (1)
```

This is the error message that is seen in the project, like https://hosted.weblate.org/projects/gnu-mailman/hyperkitty/#alerts for Hyperkitty.

This can potentially be fixed by choosing a non-master branch to push to on the Fork and use that to create a Merge Request.

Although, I am not sure if we necessarily need to do a force-push all the time. We do that for GitHub I guess, and the same code got copied over to Gitlab's commands.

**Comment by nijel** [comment]
The reason for force push is that we can rewrite history on Weblate side — if rebase is used or with squash add-on. In that case force push is needed to update the pull request.

I think the right approach to fix this is to avoid having protected branches on Weblate fork.

**Comment by nijel** [comment]
PS: You apparently need force push as well - otherwise GitLab would not complain. The force push option AFAIK does nothing if the push is fast forward.

**Comment by nijel** [comment]
Looking at it, it would make sense to disable several features on the GitLab forks. It doesn't make sense to have issue tracking, wiki, snippets...

This is quite different compared to GitHub - it does create fork with none of these features enabled by default, compare:

* https://github.com/weblate/warehouse
* https://gitlab.com/weblate/hyperkitty/

**Comment by maxking** [comment]
I can work on figuring out what would be a good way to get these forks to not have all the options enabled by default and perhaps find an easy way to disable protected branches.

**Comment by maxking** [comment]
I haven't yet been able to find anything that would work for us. Although, Gitlab does support this concept of custom group/issue templates, we don't yet have a way get that on a free plan.

https://docs.gitlab.com/ee/gitlab-basics/create-project.html#custom-project-templates-premium

Gitlab does provide free premium to open source project, instructions on how to apply: https://gitlab.com/gitlab-com/marketing/community-relations/gitlab-oss/tree/master

**Comment by nijel** [comment]
Workaround could be not using squash and rebase on Weblate side. It should avoid need for force pushes.

**Comment by maxking** [comment]
Although, there might be situations for repository repair when it could require force push IMO, which would fail.

It shouldn’t be hard to push to a non-master branch, I usually use `weblate-master` in the scripts that I have to create pull requests. It works pretty well for  me.

**Comment by nijel** [comment]
Remembering that we do something like this made me look again look into the code.

We do create branch name based on current component:

https://github.com/WeblateOrg/weblate/blob/60ee6c4596b1b8ace296d0e8b5b73fbab7be2f75/weblate/vcs/git.py#L551-L556

But we push both branches to the fork:

https://github.com/WeblateOrg/weblate/blob/60ee6c4596b1b8ace296d0e8b5b73fbab7be2f75/weblate/vcs/git.py#L557-L558

The GitHub integration picks the named branch:

https://github.com/WeblateOrg/weblate/blob/60ee6c4596b1b8ace296d0e8b5b73fbab7be2f75/weblate/vcs/git.py#L595-L609

While GitLab one uses the original branch:

https://github.com/WeblateOrg/weblate/blob/60ee6c4596b1b8ace296d0e8b5b73fbab7be2f75/weblate/vcs/git.py#L717-L737

I think that we should avoid pushing to the original branch and fix GitLab integration to correctly create MR.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. Actually the GitLab integration seems to do the correct thing, so the only problematic part is pushing to both branches.

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
