### ISSUE TITLE
Configurable number of strings in nearby strings

### ISSUE THREAD

**Issue by narayaan** [WeblateOrg/weblate#3243]
When translating, only 10 strings are shown per page around a certain position.

I'd like to have the ability to see more strings at once, so that I'm able to quickly scan for certain mistakes.

**Comment by nijel** [comment]
This is currently configurable only in [settings](https://docs.weblate.org/en/latest/admin/config.html#nearby-messages).

**Comment by comradekingu** [comment]
@nijel Would it be costly to set it to a higher number at Hosted Weblate?
![bilde](https://user-images.githubusercontent.com/13802408/77453731-88536700-6def-11ea-8087-6ed6e9a5bf99.png)
Here 60 entries fit
![bilde](https://user-images.githubusercontent.com/13802408/77452178-8d171b80-6ded-11ea-9ecd-cd4dae4d934c.png)
Maybe set it to 66, as it starts out at just 6 and gets to 11 at string 6?
