### ISSUE TITLE
Language code style with expanded language codes

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3246]
**Describe the bug**
When adding new language to component, Weblate names new file in `xx.resx` format, rather than in `xx-XX.resx` format, regardless if "Language code style" is set to "Default based on the file format" or "BCP style using hyphen as a seperator"

**To Reproduce**
1. I have a component with localization files of a Windows desktop application that are named in `xx-XX.resx` format. Currently there are three languages - `ru-RU.resx`, `en-US.resx`, `de-DE.resx`
2. I add a new language (Kazakh), but the new file is named `kk.resx`
This behaviour is the same, regardless if "Language code style" is set to "Default based on the file format" or "BCP style using hyphen as a seperator"

**Expected behavior**
I would like the new file named `kk-KZ.resx`

**Server configuration and status**
```
 * Weblate 3.9-dev
 * Python 3.5.3
 * Django 2.2.5
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.6
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.11.0
 * Pillow 6.1.0
 * python-dateutil 2.8.0
 * lxml 4.4.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.10.3
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20181111
 * ruamel.yaml 0.16.5
 * Mercurial 4.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.9.0-3-amd64 (x86_64)
```

**Comment by tariver** [comment]
I just realized now that file name should be kk-KZ.resx
I created a language called "Kazakh" too with code kk_KZ, but that brings up the same issue as in #3086

I used underscore because variants of English, Spanish and German already preset in the system use underscore.

And yet again the "Language code style" doesn't seem to affect the file name of this new language, it's kk_KZ.resx

**Comment by nijel** [comment]
There is currently no option to expand language codes to full ones, but it could be easily implemented.

**Comment by nijel** [comment]
The language code logic is here:

https://github.com/WeblateOrg/weblate/blob/d5b9d80189e6e5972c443e4d76cba8318dc25cc3/weblate/formats/base.py#L340-L378

The codes are available here: https://github.com/WeblateOrg/weblate/blob/master/weblate/langdata/countries.py
