### ISSUE TITLE
Ability to add language at once to all components created with "Component discovery" addon

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3247]
**Is your feature request related to a problem? Please describe.**
In my project I have a Java web-application that keeps it's localizable strings in several files located in directory which name equals to language code i.e. all files for English are in `en` directory, for Russian in `ru` directory and for German in `de` directory
So what I did is I created a component for `xx/default.properties` file and added other files using "Component discovery" addon, so there are few components linked to the `default.properties` one.
Now I need to add another language but adding it just to `default.properties` component doesn't replicate to other components linked to it.

**Describe the solution you'd like**
It would be nice to have a setting in "Component discovery" addon that allowed language consistency between main and linked components.

**Describe alternatives you've considered**
An alternative would be:
1. Adding new language to each component manually, which is a bit cumbersome task because there might be quite many of them (about 40 in my case).
2. Deleting all the linked components and recreating them, which is again a bit cumbersome and probably might have some undesired side effects like deleted translation memory etc.
3. Using "Language consistency" addon. But that will have effect on all components in the project, not just linked to this particular one, which might be undesirable to some people (because of #3086 in my case)

**Comment by nijel** [comment]
There is [Language consistency addon](https://docs.weblate.org/en/latest/admin/addons.html#language-consistency) to achieve this.

**Comment by tariver** [comment]
That's one of alternatives, but sometimes it is not desirable that every component in a project has the same set of languages.

**Comment by nijel** [comment]
I don't think this belongs to the discovery addons. You can also create linked components manually and might want to use this. In the end I still think the language consistency addon is the right tool in this case. In case you want to have consistency only in some of the components, maybe that's good reason to split them into separate project. Anyway https://github.com/WeblateOrg/weblate/issues/3086 should be addressed somehow to make it work properly in such case.
