### ISSUE TITLE
Register EXPORTERS in settings.py

### ISSUE THREAD

**Issue by fdosanjuan** [WeblateOrg/weblate#3248]
I think it would be useful to be able to select which exporters to have available.

I propose to have a similar solution to the one used for machine translation services, i.e., register in settings.py the list of EXPORTERS as it is done with MT_SERVICES.

What do you think?

Thank you!!

**Comment by nijel** [comment]
It makes sense to configure it for some deployments, patches are welcome :-)

**Comment by 55abhilash** [comment]
I would like to work on this. Shall I send a pull request with changes?

**Comment by nijel** [comment]
Yes, you are welcome to do that.

**Comment by nijel** [comment]
Weblate uses https://pypi.org/project/django-appconf/ to define default values for settings, it's then defined here:

https://github.com/WeblateOrg/weblate/blob/93d569739c3a3d700d57e719b55f9fb17265bd3f/weblate/formats/models.py#L57-L99

Defined with WEBLATE prefix, so the setting is in the end called WEBLATE_FORMATS, unforntunately there is not much consistence in naming settings so far.

**Comment by 55abhilash** [comment]
#4091
