### ISSUE TITLE
Replace Chartist by own svg chart renderer

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3249]
**Is your feature request related to a problem? Please describe.**
The current activity charts do not look nice are not aligned with rest of the charts. It should have similar look as status widgets:

![](https://hosted.weblate.org/widgets/weblate/-/horizontal-auto.svg)

**Describe the solution you'd like**
Render SVG directly instead of rendering JSON and then doing client side transform into SVG.

**Describe alternatives you've considered**
Tuning Chartist to produce nicer charts is also option, but I think for the minimal feature set we need it's not needed.

**Comment by apitulea** [comment]
Hi, could I work on this?

**Comment by nijel** [comment]
@apitulea Thanks, I've assigned you this issue.
