### ISSUE TITLE
Android translatable field ignored

### ISSUE THREAD

**Issue by Marlinc** [WeblateOrg/weblate#325]
Strings in a Android application can have the `translatable="false"` in the tag which means that the string is not translatable. So these should not be marked as 'Untranslated strings'

**Comment by hram** [comment]
It would be great if I can mark string as translatable="false" from weblate

**Comment by nijel** [comment]
@hram that's pretty unrelated here, please avoid posting to many issues (you've also posted this to https://github.com/WeblateOrg/weblate/issues/743, which is actually the feature requests you want)

**Comment by hram** [comment]
@nijel #743 and this one issue is different
if they have some common words it does not mean that it is the same

**Comment by nijel** [comment]
#743 is about marking strings non translatable and you want to mark strings non translatable, it looks pretty similar to me. While this one was about importing android files...
