### ISSUE TITLE
Disable dump data backups

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#3255]
**Is your feature request related to a problem? Please describe.**
We have a server with automated backups setup through a CRON and postgresql dumps. Since an upgrade to Weblate 3.9 some database dumps are also automatically performed, but they are redundant with our existing scripts. We'd like to disable them completely from Weblate.

**Describe the solution you'd like**
A documented way to switch off the backup dumps from Weblate.

**Describe alternatives you've considered**
I tried to remove the specific queue for backups from Celery, but AFAIU it only remove a priority queue for backups, they are still running on the main queue. I don't know well Celery but maybe there's an easy way to configure it for stopping the running of backups?

**Comment by nijel** [comment]
Do you want to compress them (https://github.com/WeblateOrg/weblate/issues/3200) or disable them? :-)

**Comment by surli** [comment]
I want choice about them :)
I'd be personally fine with a compress only but my sysadmin wants to keep his own backup/restore scripts for now.

**Comment by nijel** [comment]
Okay, closing in favor of https://github.com/WeblateOrg/weblate/issues/3200, this really should be done at once.
