### ISSUE TITLE
Introduce dependencies on "Translation states"

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#3256]
## Pre-Requisites

`Project1` is configured, including

- [x] Enable reviews

`ComponentA` in `Project1` is configured, including

- Monolingual base language file: `en` (Source)
- [x] Edit base file (allowed)

## Expected dependencies and behavior

- If string in `en` has "Translation state" `Needs editing` or `Waiting for review` this means it is not yet approved hence should not yet be translated into further languages. For a translator being on e.g. `it` in `ComponentA`, the effect shall be, that he cannot translate due to source's state.
  - Option 1: Disable `Save` button when being on this string, but still showing it.
  - Option 2 (preferred): Don't show/provide string at all for translation.
- Furthermore, if `Needs editing` or `Waiting for review` is set, it shall also not appear in Machine Translation and Translation Memory

**Comment by rhofer** [comment]
@nijel Assuming the project has "review enabled", what are the current rules for a string that it arrives in the translation memory? Is it depending on Translation Status? Is there a difference for personal, project and shared TM?

**Comment by nijel** [comment]
Once string is translated in Weblate, it lands in the translation memory. It end ups in all three TMs by default.

**Comment by rhofer** [comment]
Does it end up in TM's independent of Translation state? (needs editing, waiting for review and approved)

**Comment by nijel** [comment]
Just waiting for review and approved, needs editing doesn't end up in TM.
