### ISSUE TITLE
Provide a secondary source language in case "Monolingual base language file" is marked as editable

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#3257]
## Situation

For translation we run a three step approach:

1. **Developer** to create and provide SWEnglish / Developer-English. We call it `template`
1. **Harmonize** `template` into a proper and polished `en`
1. **Translator** to go for further translations based on `en` released from Harmonize step

In our weblate configuration we created an artificial language called `template`, what represents this English from developer perspective

This means for Harmonize:
- Source: `template`
- Target: `en`

This means for Translator:
- Source: `en`
- Target: any other language

## Expected behavior

- In in Harmonize step, when user is editing `en`, present `en` as "Translation **English**" and `template` as "Source"
  - Also in this case the secondary base language `template` provides the comprehensive list of contexts (keys/msgid's)
- When string has changed in `template`, show in the `Component`/`en` overview tab that `Strings marked for edit` due to secondary source has changed

Remark:
- In Translator step, `en` shall be the source language, as it already is today
- Also `en` then provides the list of context (keys/msgid's), as it already is today

## Expected configuration

In `Component` configuration dialogue (e.g. Django Admin Interface), when:
- [x] Edit base file (allowed) ... is ticked, provide an additional drop-down underneath to `Select secondary source language`
- In this case `template` should be picked then.

### Cleanup translation files

If secondary source language is set, enhance for a two step approach:

1. Cleanup `en` against `template`
1. Cleanup all other languages against `en`

(Any other Addon which would need enhancement due to two step approach?)

## Expected behavior of `Project`/`Component`/`Language` > Tools > Automatic translation

- If *Automatic translation* is started from `Project`/`Component`/`en` and secondary source language is set as `template`, then take `template` as source for match making.
- If *Automatic translation* is started from `Project`/`Component`/`Any other than en`, then take primary source language `en` as base for match making.

This shall apply to both, component based automatic translation and to machine based automatic translation with fuzzy match making.

**Comment by nijel** [comment]
Related to https://github.com/WeblateOrg/weblate/issues/1822

**Comment by Bachstelze** [comment]
Do you need to keep the template? I understand the issue as a source string review.
Anyways, it could be helpful to provide multiple source sentences if there are already reviewed translations. This would increase the accessible informations for the human and automatic translation.
