### ISSUE TITLE
Add API for adding new monolingual strings

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3261]
Currently, this is UI only feature and might be useful in the API as well.

It calls `Translation.new_unit` under the hood.

_Originally posted by @jornvl90 in https://github.com/WeblateOrg/weblate/issues/1145#issuecomment-555039651_

**Comment by grebulon** [comment]
@nijel [moved the comment from 1145]
We also need this. In out project we can't connect our git to the weblate platform, and must use the API.
However, I don't understand why do this only for monolingual strings and not as a general way of adding terms. This seems like a very basic thing to do.

**Comment by nijel** [comment]
The reason is that with monolingual files, it's clear that the monolingual base file is the one to add it. With bilingual the strings are typically extracted from somewhere else (from source code, other documents, ...), so adding them manually doesn't make much sense. It might be eventually supported, but it needs an use case and I currently do not see one. Also, it might get tricky as the bilingual translation files do not have to be in sync - there is no requirement on all of them having same strings and it happens in some cases that they do not.
