### ISSUE TITLE
YAML output customization

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3266]
**Is your feature request related to a problem? Please describe.**
Currently YAML format uses whatever defaults are hardcoded in the ruamel-yaml. This should be made configurable in way similar to JSON.

What we want to customize:

* width to avoid line wrapping if desired

**Describe the solution you'd like**
YAML customize addon.

**Additional context**
On the translate-toolkit side this is supported since https://github.com/translate/translate/pull/3926

**Comment by ilocit** [comment]
Thanks for adding this to the feature list.
The option / AddOn should allow to set a length or disable line breaking all together.
