### ISSUE TITLE
VCS using Subversion,when I create componet,it said server ssl certificate verification failed

### ISSUE THREAD

**Issue by bfdxyou** [WeblateOrg/weblate#3276]
Could not update repository: svn: E170013: Unable to connect to a repository at URL 'https://svn.com/svn/BFPLIBS/trunk' svn: E230001: Server SSL certificate verification failed: issuer is not trusted (1)

I already use : HOME=${DATA_DIR}/home svn co https://svn.com/svn/BFPLIBS/trunk.
I see #1231,but the problem still hasn't been solved.
git version:2.24.0
weblate: 3.9

Must I have to use an SSH key? But the host not have a SSH key.

**Comment by nijel** [comment]
The correct solution is to install your CA certificate into the system certificates, so that it will be trusted.

**Comment by bfdxyou** [comment]
Thank you for your reply.
I run the command：sudo dpkg-reconfigure ca-certificates
you@ubuntu16:/usr/share/ca-certificates$ sudo dpkg-reconfigure ca-certificates
Processing triggers for ca-certificates (20170717~16.04.1) ...
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.

And then, recreate a new compent, but also say Server ssl certificate is not trusted.

**Comment by nijel** [comment]
How do you use SVN outside Weblate? Do you configure it to ignore SSL errors?

**Comment by bfdxyou** [comment]
you@ubuntu16:~$ svn ls https://svn.com/svn/BFPLIBS/trunk
Common/
Cryptography/
Cryptography_v2/
IO/
PO.UIText/
TcpUdpCommunication/
Windows.Forms/
Weblate/
you@ubuntu16:~$ sudo chown -R www-data:www-data .subversion

Finally, I changed the owner to www-data. Must the owner be changed to www-data?
Problems still exist.

**Comment by nijel** [comment]
Yes, the files have to be owned by user running Weblate. Looking at `/manage/performance` will tell you about such issues.

So interactively svn asks for accepting the cert and stores that into `~/.subversion`? Or stores it into checked out repository?

**Comment by bfdxyou** [comment]
In DATA_DIR path, "~ /weblate/lib/python3.5/site-packages/data"   and  "~ /weblate/lib/python3.5/site-packages/data/vcs" ,  I run "sudo svn ls https://svn.com/svn/BFPLIBS/trunk", also Can be verified. Do you mean that?

**Comment by nijel** [comment]
Yes, those are unrelated.

What I meant is where does subversion store information about trusting the certificate. Let's assume it's in home. In that case running `sudo -u www-data HOME=/path/to/data svn ls https://svn.com/svn/BFPLIBS/trunk` should make it store in correct location to be used by Weblate.

**Comment by bfdxyou** [comment]
Thank you very much. The problem has been solved. Import CA certificate and  use "sudo -u www-data HOME=/path/to/data svn ls https://svn.com/svn/BFPLIBS/trunk", then Svn can be accessed smoothly.
