### ISSUE TITLE
Lots of backlog causes "Copy from source" to lag in zen mode

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3280]
Could be that it is when copy from source is used a lot in the same session, but it seems to only happen when there are a lot of translation units in the scrollback.

**Comment by nijel** [comment]
Probably the `parents` lookup is taking too long with many elements. We definitely do not need to go through all parents here:

https://github.com/WeblateOrg/weblate/blob/c7992547849c5e3b20d546952617ca2657c74996/weblate/static/loader-bootstrap.js#L243-L245
