### ISSUE TITLE
Text for translation missing in arabic with many cases

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3281]
https://hosted.weblate.org/translate/remmina/remmina/ar/?checksum=5a93e36c2cd293e

**Comment by nijel** [comment]
I can see it there:

![Screenshot_2019-12-06 Remmina remmina - Arabic](https://user-images.githubusercontent.com/212189/70304937-55b33d80-1803-11ea-8e90-b2257db612f1.png)

**Comment by comradekingu** [comment]
@nijel Ah yes, that is acutally the same for everyone. Just confusing when there are many.
How about instead of

- **Source 1**
- **Source 2**
- Translations …

it was

- **Source 1**
- Translation 1 _______
- **Source many**
- Translation many _______
- Translation other1_______
- Translation other2_______
- Translation other3_______

Maybe that would be less confusing?

**Comment by comradekingu** [comment]
So from my understanding the extra forms for Arabic are autogenerated by the gettext config in Weblate?
How about duplicating the english plural string for everything 2 and above?

**Comment by nijel** [comment]
Arabic has 6 plural forms, see http://www.unicode.org/cldr/charts/32/supplemental/language_plural_rules.html#ar

The question mark has tooltip with help for plurals.
