### ISSUE TITLE
Weblate hangs on string processing

### ISSUE THREAD

**Issue by vorgusa** [WeblateOrg/weblate#3282]
**Describe the bug**
When weblate runs its celary tasks to process po files into strings, it ends up getting stuck with no error message.  If I delete and recreate the component all strings are then processed and everything works fine.  If I do a loadpo on it, it works, and then eventually it stops working and returns to getting stuck.  Unfortunately, I can not even find a log or anything in order to point to a problem, what is the best way for me to continue troubleshooting?

**To Reproduce**
Can't reproduce from scratch.
1. weblate loadpo --force project/component1
2. Check logs and validate it stopped at 1/98

**Expected behavior**
Weblate/celery to process all po files

**Screenshots**
```
Dec  5 15:03:49 weblateserver weblate[9261]: INFO project/component1: updating repository
Dec  5 15:03:50 weblateserver weblate[9261]: INFO project/component1: update took 0.56 seconds
Dec  5 15:03:50 weblateserver weblate[9261]: INFO project/component1: pushing to remote repo
Dec  5 15:03:51 weblateserver weblate[1533]: INFO project/component1: updating repository
Dec  5 15:03:52 weblateserver weblate[1533]: INFO project/component1: update took 0.93 seconds
Dec  5 15:04:40 weblateserver weblate[26014]: INFO project/component1: checking src/resources/po/ar.po (ar) [1/98]
Dec  5 15:04:40 weblateserver weblate[26014]: INFO project/component1/ar: processing src/resources/po/ar.po, content changed
Dec  5 15:13:29 weblateserver weblate[26014]: INFO project/component1: updating repository
Dec  5 15:13:30 weblateserver weblate[26014]: INFO project/component1: update took 0.76 seconds
Dec  5 15:16:21 weblateserver weblate[26014]: INFO project/component1: updating repository
Dec  5 15:16:22 weblateserver weblate[26014]: INFO project/component1: update took 0.56 seconds
```
**Server configuration and status**
Please paste the output of `list_versions` and `check --deploy` commands over
here. Depending on installation these can be executed in different way, please
consult https://docs.weblate.org/en/latest/admin/management.html for more
details.

On Git checkout:

```
(weblate-3.6.1) -bash-4.2$ weblate list_versions
 * Weblate 3.6.1
 * Python 3.6.8
 * Django 2.2.7
 * Celery 4.4.0rc4
 * celery-batches 0.2
 * six 1.13.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.7
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 1.8.3.1
 * Pillow 6.2.1
 * python-dateutil 2.8.1
 * lxml 4.4.2
 * django-crispy-forms 1.8.1
 * django_compressor 2.3
 * djangorestframework 3.10.3
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20121119
 * pytz 2019.3
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache
 * Celery: redis://127.0.0.1:6379, redis://127.0.0.1:6379, regular
 * Platform: Linux 3.10.0-1062.4.3.el7.x86_64 (x86_64)

(weblate-3.6.1) -bash-4.2$ weblate check --deploy
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.6.1/admin/install.html#collecting-errors

System check identified 1 issue (2 silenced).
```

Using docker-compose:

Not using docker

**Comment by comradekingu** [comment]
I managed to hang in pushing to upstream repo (something that was already pushed)
https://hosted.weblate.org/progress/remmina/remmina/?info=1
Possibly related to trying to cancel it midway.

**Comment by nijel** [comment]
Most likely it crashed for some reason. The version you are using didn't log errors in background jobs in some cases, this was fixed in 3.8. Configuring Sentry or Rollbar will collect the error even in such cases.

**Comment by vorgusa** [comment]
I will try to upgrade and see what happens.   Thanks!

**Comment by vorgusa** [comment]
There are lots more errors showing now.  I will take that as a good and bad thing :)  Thanks for your help
