### ISSUE TITLE
Yandex machine translation for Kazakh is missing

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3283]
**Describe the bug**
After adding Kazakh language to component, Yandex machine translation doesn't show up in "Machine Translation" tab.
Yandex machine translation for other languages (English and German) is shown.
Microsoft Terminology translation for Kazakh also shows up.

**To Reproduce**
1. Have a project with source language Russian and target languages - English, German and Kazakh.
2. Configure Yandex and Microsoft Terminology machine translation
2. Go to any string to translate it to English or German. Both Yandex and Microsoft Terminology translations show up
3. Go to any string to translate it to Kazakh. Microsoft Terminology translation shows up, but no Yandex translation

**Expected behavior**
Yandex machine translation should also show up for Kazakh

**Server configuration and status**
```
 * Weblate 3.9-dev
 * Python 3.5.3
 * Django 2.2.5
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.6
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.11.0
 * Pillow 6.1.0
 * python-dateutil 2.8.0
 * lxml 4.4.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.10.3
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20181111
 * ruamel.yaml 0.16.5
 * Mercurial 4.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.9.0-3-amd64 (x86_64)
```

**Additional context**
Yandex has two options when translating to Kazakh - Kazakh and Kazakh (Latin). It would be nice if both of these would show up.

**Comment by nijel** [comment]
~~Sorry, but Kazakh language is not available in Yandex Translate API. Once it will be available, it will be used by Weblate.~~

Okay, it turns out they have changed way in reporting supported languages and the original way is deprecated, but still works and returns outdated list of supported languages:

> Due to changes in the service, the dirs field has been deprecated. Supported languages are listed in the langs field.

**Comment by tariver** [comment]
> Yandex has two options when translating to Kazakh - Kazakh and Kazakh (Latin). It would be nice if both of these would show up.
I just updated and there is only one Kazakh translation in Cyrillic. Is there a possibility to also add Kazakh translation in Latin script?

**Comment by nijel** [comment]
It doesn't seem to be present in the API, there is just `kk | "Kazakh"`
