### ISSUE TITLE
Add secondary languages glossary to translation screen

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3284]
**Is your feature request related to a problem? Please describe.**
It would be nice if not just translation on secondary languages chosen by the user but also glossary for those languages would be shown on translation screen

**Describe the solution you'd like**
To display secondary languages glossary entries below target language glossary entry.

**Comment by nijel** [comment]
Can you please clarify why additional glossary entries would be useful?

**Comment by tariver** [comment]
> Can you please clarify why additional glossary entries would be useful?

As far as I understand, the "[Secondary languages](https://docs.weblate.org/en/latest/user/profile.html#secondary-languages)" options is there so that translators could have more context and also could see how this string was translated to other languages that they know or/and closely related language.

So IMHO adding display of glossaries in these secondary languages will enhance and expand the purpose of the "Secondary language" feature - to give translators more context.

**Comment by nijel** [comment]
While it is easy to implement, the current glossary can already take considerable screen space, and I don't see how we can make it work for an additional language.
