### ISSUE TITLE
Add support for react-intl

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3286]
**Is your feature request related to a problem? Please describe.**
Add support for [react-intl](https://github.com/formatjs/react-intl).

**Describe the solution you'd like**
Native support for their format.

**Describe alternatives you've considered**
Maybe current JSON backends are good enough, it just needs proper documentation and handling of extensions.

**Additional context**

See also https://github.com/WeblateOrg/weblate/issues/2967

**Comment by fnune** [comment]
I'm almost done with an E2E implementation (get translation files from repo, translate on Weblate, push back to repo as PR) for apps that use `react-intl` and we've only needed to use JSON. There's nothing in there specific to `react-intl`.

**Comment by nijel** [comment]
Good to know, so probably the only missing bit is MessageFormat support, https://github.com/WeblateOrg/weblate/issues/2967

**Comment by nijel** [comment]
Closing, the reaming bit is covered by #2967
