### ISSUE TITLE
Setting WEBLATE_ENABLE_HTTPS to 1 leads to HTTP 301

### ISSUE THREAD

**Issue by sr258** [WeblateOrg/weblate#3288]
My Weblate installation is in a docker-compose setup that includes a reverse proxy. HTTP is done by the reverse proxy (NGINX). It relays all traffic to the weblate server inside the docker network (http://weblate:8080).

So far I've not set WEBLATE_ENABLE_HTTPS, and the installation works. Now I want to have the correct URLs with https:// when generating badges. If I set WEBLATE_ENABLE_HTTPS to 1, Weblate can't be accessed anymore and I receive a 301 HTTP answer redirecting to https://weblate:8080. As the browser can't access this address, there is a failure.

The sitename is set correctly to my domain. I suspected that the cause might be that WEBLATE_ALLOWED_HOSTS is set to localhost and weblate as well (besides my domain name), but removing it breaks Weblate. (There is a bad request message in the UI and the log shows ```ERROR Handled exception: DisallowedHost: Invalid HTTP_HOST header: 'weblate:8080'. You may need to add 'weblate' to ALLOWED_HOSTS.```)

What might cause the redirect to https://weblate:8080? How can I redirect to the correct domain?

app.conf (NGINX):
```
server {
    listen 80;
    server_name deutsche-h5p-uebersetzungscommunity.tk;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}
server {
    listen 443 ssl;
    client_max_body_size 100M;
    server_name deutsche-h5p-uebersetzungscommunity.tk;
    ssl_certificate /etc/letsencrypt/live/deutsche-h5p-uebersetzungscommunity.tk/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/deutsche-h5p-uebersetzungscommunity.tk/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://weblate:8080;
        proxy_read_timeout 360s;
    }

    location /scorm-h5p/ {
        proxy_pass http://scorm-h5p/;
    }
}
```

relevant environment variables in docker-compose:
```
      - WEBLATE_ALLOWED_HOSTS=deutsche-h5p-uebersetzungscommunity.tk,localhost,weblate
      - WEBLATE_ENABLE_HTTPS=1
```

**Comment by nijel** [comment]
It is most likely coming from the `Host` header, adding `proxy_set_header Host $host;` should address it.

**Comment by sr258** [comment]
I've fixed it, but there was one more step. Thank you @nijel! For future readers: I've also set 
```
proxy_set_header HOST $host;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host $server_name;
```

in the NGINX config. In particular the `X-Forwarded-Proto` is important for Weblate to not redirect all the time.
