### ISSUE TITLE
Logo resource

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3290]
New logo doesn't have a page to download it (that I could find)
This makes https://github.com/ForkAwesome/Fork-Awesome/issues/218 hard to satisfy
I think a black and white official set in PNG/SVG would do nicely
https://github.com/ForkAwesome/Fork-Awesome/issues/189#issuecomment-530311920

Edit: Found https://github.com/WeblateOrg/graphics/tree/ec7c6e94bdb2abaa2d330b2e7560674bf97767c1

**Comment by nijel** [comment]
Yes, graphics is the right location, but it should be documented somewhere.

The black logo is here: https://github.com/WeblateOrg/graphics/blob/master/logo/weblate-black.svg
