### ISSUE TITLE
Comments in Android string resources

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3295]
**Is your feature request related to a problem? Please describe.**
Not sure if it's a bug or works as intended, but comments in Android string files and Java properties files work differently.
In Java properties if you leave a blank line between the comment line and string line the comment is not shown in Weblate. As an example, here is a Java properties file:
```
string1=String 1
# This comment will NOT be shown

string2=String 2

#This comment will be shown
string3= String 3
```
And how it is shown in Weblate:
![image](https://user-images.githubusercontent.com/36223356/70701471-784ec600-1cdd-11ea-821c-9382be613427.png)
![image](https://user-images.githubusercontent.com/36223356/70701508-843a8800-1cdd-11ea-90c1-661ee04c5545.png)

But this trick doesn't work with Android string files
```
    <string name="string1">String 1</string>
    <!-- This comment should NOT be shown -->

    <string name="string2">String 2</string>
    <!-- This comment should be shown -->
    <string name="string3">String 3</string>
```
![image](https://user-images.githubusercontent.com/36223356/70701966-51dd5a80-1cde-11ea-8f6a-2795cadd6ce5.png)
![image](https://user-images.githubusercontent.com/36223356/70701985-5a359580-1cde-11ea-9c62-bab7691fd04a.png)

**Describe the solution you'd like**
It would be nice if comments in Android string files would be parsed the same way as in Java properties files, so that developers would have an option to choose which comments are shown to translators and which should be kept hidden.

**Comment by nijel** [comment]
This is something to address in https://github.com/translate/translate/, I've filed https://github.com/translate/translate/issues/3928.
