### ISSUE TITLE
Support for translation file headers

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#3296]
**Is your feature request related to a problem? Please describe.**
We use java properties for our translation, and all our files contains an header with the license of our project. Right now when a translation is added in a new language, the created file does not have the original headers. 

**Describe the solution you'd like**
A new addon to support headers in generated file.
I guess it should be enough for us to be able to configure this addon to specify which header to add. In our case we'd certainly need to be able to configure this header by component: I don't know if such configurable addon is supported right now.

A better solution is most certainly to directly retrieve the header from the original source file: not sure how it would be supported depending on the file format.

**Additional context**
Here's an example of such header: https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/src/main/resources/ApplicationResources.properties#L1-L50

**Comment by nijel** [comment]
You can already define template for creating new translations. Have you tried that?

**Comment by surli** [comment]
Hmmm indeed I haven't study this option, I will give it a try :)

**Comment by surli** [comment]
OK that indeed completely covers my header issue. Now from an UI point of view, I find it a bit weird that when adding a new language when using a template, Weblate shows that all is already translated with unchanged translation.
I understand that it's because the source file is copied, but it feels a bit wrong for UX.

**Comment by surli** [comment]
I'm going to close the issue anyway, since it solves my problem, thanks a lot!

**Comment by surli** [comment]
Actually reopening the issue: I tried to specify my base source file as template, but as I mentioned the result is that when adding a new language, it copies entirely my base source file for the new language.
So in the end, if not all keys are translated, I end up with a translation file containing values in my source language, and some other translated: I don't have any way outside Weblate to know which is translated and which is not. We currently don't want to have such files.

So, ideally I'd like to specify a common templates for all my components, which would only contain my license and maybe some comments. Problem is that apparently I cannot specify an URL for the template, and in my case the template is not necessarily a file from the same repository.

**Comment by nijel** [comment]
The template currently has to be in the repository. It should be completely untranslated when adding new language.
