### ISSUE TITLE
Update to Django 3

### ISSUE THREAD

**Issue by Bachstelze** [WeblateOrg/weblate#3301]
**Is your feature request related to a problem? Please describe.**
With a well-structured plan, we could make a neat [upgrade](https://docs.djangoproject.com/en/3.0/releases/3.0/) and benefit in the development from [new features](https://docs.djangoproject.com/en/3.0/releases/3.0/#whats-new-3-0) like exclusion constraints on PostgreSQL and filter expressions.

**Describe the solution you'd like**
Follow the [upgrade documentation](https://docs.djangoproject.com/en/3.0/howto/upgrade-version/) and cut it into smaller parts to distribute them.

**Describe alternatives you've considered**
Wait till the next  LTS release (3.2).

**Additional context**
[Deprecation which are removed in 3.0](https://docs.djangoproject.com/en/3.0/internals/deprecation/#deprecation-removed-in-3-0)

**Comment by nijel** [comment]
Our code should be ready, we're blocked by https://github.com/django-compressor/django-compressor/issues/963, see https://github.com/WeblateOrg/weblate/pull/3264

**Comment by Bachstelze** [comment]
@diox asked for tests. It could help to install django-compressor from source and weblate without the pip version of django-compressor. Are all cases covered by only testing with python 3?

**Comment by nijel** [comment]
You mean with Django 3? Yes, our testsuite is quite comprehensive, so it should cover everything.

**Comment by nijel** [comment]
I've created branch for that: https://github.com/WeblateOrg/weblate/pull/3313

**Comment by nijel** [comment]
...and all tests pass there, so we're ready.

**Comment by Bachstelze** [comment]
Nice test!

> You mean with Django 3? Yes, our testsuite is quite comprehensive, so it should cover everything.

I was thinking about the backward-compatibility of django-comprossor with python2 and django 1.11, but either way I don't know if that matters in the future.

**Comment by nijel** [comment]
Even the Python 2 tests passed, so that should be safe as well.

**Comment by Bachstelze** [comment]
The extended build tests were cancelled: https://github.com/WeblateOrg/weblate/pull/3313/checks?check_run_id=352423758
Where can I find the passed Python 2 tests?

**Comment by nijel** [comment]
Because setup tests fail on hacked requirement for django_compressor. All tests were executed on drone: https://cloud.drone.io/WeblateOrg/weblate/1324

**Comment by nijel** [comment]
https://github.com/WeblateOrg/weblate/pull/3264 was just merged.
