### ISSUE TITLE
"Translated" translation

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3303]
**Describe the bug**
This string should be divided. The one displayed on https://github.com/WeblateOrg/weblate/blob/master/weblate/templates/snippets/list-objects.html#L13 should be a different string. In Catalan (and other languages, like Spanish, for example), "Translated" can be translated in several ways, depending on the genre and amount of elements (strings are feminine, while projects are masculine, for example). In the case of the "Translated" string shown on the dashboard, it should be "Traduïdes" because it refers to strings (feminine and plural). In other places (like the widgets, for example) it should be "Traduït" because it refers to a project (masculine and singular).

**Additional context**
https://hosted.weblate.org/translate/weblate/master/en/?checksum=45db08850818d4b1#comments

**Comment by ldmpub** [comment]
I confirm this is regularly an issue for translators in Weblate (not only to translate Weblate app but to translate projects using Weblate tool!).

Personally in french, when I have no context or only one string (without the noun) =>I always prefer to translate in singular and in male forms. I apply this rule for verbs, nouns, adjectives when they are alone in a string.

To correctly translate, translators always need either:
1. genre and number contexts for this kind of string
or
2. a "full sentence" 
Examples "String translated" / "Strings translated" to know if it's singular / plural or "String translated" or "Project translated" to know if it's female / male form ... 
In french "String translated" / "Strings translated" = Chaine traduite / Chaines traduites ; "String translated" or "Project translated" = Chaine traduie / Projet traduit.

Strings like "translated" alone and/or without context should be avoided ... to get good translation quality.

From my point of view this is a general improvement to perform to Weblate tool (clarify theses contexts by adding the noun for instance) and not only a strings to change in the app itself like reported here ;-).

**Comment by nijel** [comment]
I notice most of such problems myself when translating to Czech. However, there are very few places where it won't be different in Czech and I'm glad when somebody tells me.
