### ISSUE TITLE
None too many open spaces

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3304]
Liking the new stuff :) This I don't understand:
![bilde](https://user-images.githubusercontent.com/13802408/70863758-c79a2e00-1f4b-11ea-9c2b-0c97674268ed.png)
vs
![bilde](https://user-images.githubusercontent.com/13802408/70863765-d385f000-1f4b-11ea-8114-6f8c5444924a.png)
Though I am not sure, I would contest that all the "None" does no other thing than present extra visual clue, to which there is no logical continuation or effort to be made(?)

The percentage translated could be colourcoded in a gradient similar to the green completion colour, arriving at a "thumbs up" sign (for 100%)
👍 of 100% is a lot easier to digest than
"Done" of 100%  None None None None None(?)
It all gets a bit strange with the completion of empty projects, like https://hosted.weblate.org/projects/darkwallet/darkwallet/nb_NO/ but that is another matter I think.

**Comment by nijel** [comment]
You could say the same for "Done", but you've kept those :-).  I'd stay consistent here and either keep both strings or remove both. But I don't have a strong opinion here.

**Comment by comradekingu** [comment]
@nijel
With neither
![bilde](https://user-images.githubusercontent.com/13802408/70875872-c0106e80-1fb7-11ea-8ed0-498f11bbd9d6.png)

With OK
![bilde](https://user-images.githubusercontent.com/13802408/70876169-dbc84480-1fb8-11ea-8d67-f85d3b740725.png)

With thumbs up
![bilde](https://user-images.githubusercontent.com/13802408/70876250-277aee00-1fb9-11ea-95eb-cbd09559a64e.png)

For me it is OK/neither, thumbs up, Done only, with Both being the worst.
Symbol giving a mental boost, and none making it easier to focus. With none the work to do stands out more, so I think that is best.

**Comment by nijel** [comment]
I'm not sure that making completed translations more visible is good approach. Actually it's something translator should not focus on...

**Comment by bovirus** [comment]
For me about status is more clear

100% - for full translated
0 - Instead None

**Comment by vitavalka** [comment]
Thank you @comradekingu for the ideas and comments. I like the thinking.

I am the designer behind the new UI. What do you think about even better simplification → green tick icon for done (instead of thumbs up) so it would be a little more subtle while it would clearly say that this piece is fully completed.

As for removing None, I agree. If there is no information transfered keeping it there, then cleaning things up is always a good thing ;-)

Here's a sketch of such screen:
![Overview](https://user-images.githubusercontent.com/2325142/71007751-d0276b80-20e7-11ea-8e5e-70965e84ec4e.png)

**Comment by comradekingu** [comment]
@vitavalka And what a great design it is. Having used the new system, I am partial to the "Neither" option. If it is unclear if the project is finished, I think colouring the project name is the step to take, or similar.

I really like the info presented to all be relevant, this is my thinking:
If "None" can be removed to the effect of "nothing to be done", then "Done" can go too?
You found a screen without "of total". It is a fixed bug.  #3311 (same with the licenses and admin status not shown)
One assumption, "words" can't be anything other than 100% if strings are 100%.
Therefore 100% words are redundant if strings are 100%

There were some people confused about the "of total" amount, (which means percentage of available strings added for translation), so maybe having that be the only remaining percentage makes things clear.

To draw on the earlier rationale, there are percentages and numbers everywhere to detail something needs doing and how much of it needs doing. Once that is done, only the ultimate percentage (of total) is left, because it is the only thing that matters beyond finishing "everything", and then people can know or decide if that is relevant for them by adding more components need to be added in their language. (which would bring back Strings, words, etc.

**Comment by vitavalka** [comment]
@comradekingu Thank you. The screen chosen was my design, where I just removed the "None" words and added the green tick. So other bits are not relevant.

True, we can clean it up to a point, where we either have some percentages for items requiring action, or we have clean green line.

And for the button, we could have filled (dark) ones for items needing action. And outlined (dimmed) ones for items completely finished (with green line). That way the dark buttons will call for action more than the dimmed ones. What do you think @nijel ?

**Comment by comradekingu** [comment]
From
![bilde](https://user-images.githubusercontent.com/13802408/71071466-f6e3b180-217c-11ea-9af4-fe0a7290df8f.png)
to
![bilde](https://user-images.githubusercontent.com/13802408/71071313-a9ffdb00-217c-11ea-9f98-eefa56070db9.png)
No borders, buttons or whitespace up top.

The "Of total" is now completion. Before it could be 47% 47%, this way that would be 47% ----
One can argue making line length represent the same thing does away with the completion/of total category altogether.

![bilde](https://user-images.githubusercontent.com/13802408/71072227-4f677e80-217e-11ea-92f4-7c6717dbcac9.png)

(unadded part of bar is either invisible (activity tracker) or coloured in black (airsonic))

**Comment by nijel** [comment]
I've made some changes now, what is left to discuss:

* checkmark / empty space for 100%, I'm not really sure what is better here
* different button colors (needs some additional CSS)
* of total clarification, please let's discuss that in https://github.com/WeblateOrg/weblate/issues/2866 where the discussion on this topic has started

**Comment by comradekingu** [comment]
Are those "Translate" buttons even needed?
The contrasting white/bar only vs the numbers is a call to action similar to that of making the "translate" button a different colour, if the "100%" is also removed.
How about a "_remove everything thought to be superflous_" and see if someone complains?

- Removing the gray borders.
I am on a yes please for this, as borders have been my pet peeve for the best part of 20 years.
Saw the Netfilx design just recently, and they seem to get away with having no borders, with a lot of users.

Sorry about bringing in more things, but it is difficult for me not to consider everything. That is my style of argument and design ;)

**Comment by nijel** [comment]
The button is IMHO needed, it brings you directly to translating without need to go through intemediate screen with translation details.

**Comment by comradekingu** [comment]
Ah, never knew that was a thing. How about just clicking the untranslated % sign?
Is there something wrong with clicking the actual bar, for its different sections?
