### ISSUE TITLE
Declarative progress bars

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3305]
![bilde](https://user-images.githubusercontent.com/13802408/70864847-dcc88a00-1f56-11ea-9f12-54489bf21fa4.png)

First concern is I never understood what the difference between yellow and red is.
There is some meta-category of "needing work" that is lost here, (one more click to get to regular editor)
Marked as needing edit should not be in either of those categories though.

What I really wish for is a fuzzy/string changed upstream category.

It may be a bit nondiscript that words are (of untranslated) here.

Suggested is the same colour as the reviewed? Might need a category for reviewed.

I would prefer the shorter bar and having the ending black dot be signified as total percentage, however I've failed that before, and the consensus was it needed to be longer.

**Comment by nijel** [comment]
Red is failing check, yellow needs edit. Needing action definitely needs some clarification, see https://github.com/WeblateOrg/weblate/issues/1163 . The same for needs edit/fuzzy/whatever, see https://github.com/WeblateOrg/weblate/issues/2240
