### ISSUE TITLE
Glossaries should have project navigation

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3307]
**Is your feature request related to a problem? Please describe.**
When you navigate to glossaries, the project navigation is gone.

1. https://hosted.weblate.org/projects/weblate/
2. Click on Glossaries
3. https://hosted.weblate.org/dictionaries/weblate/
4. Tabs are gone.

**Describe the solution you'd like**
The project tabs would be present here.

**Comment by Burzo** [comment]
Working on this one currently.
