### ISSUE TITLE
Inline editing of position and query

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3308]
**Is your feature request related to a problem? Please describe.**
With improved search based on query string instead of big forms, it seems better to allow editing the query string and position inline instead of poping up a dialog.

**Describe the solution you'd like**
Click on search term or position and input box appears in the position, enter submits it, escape cancels the edit.

**Describe alternatives you've considered**
At least proper popup placement would be great.

**Additional context**
<img width="442" alt="pozice" src="https://user-images.githubusercontent.com/212189/70911919-25457d80-2013-11ea-863b-9b61fd6aa420.png">

**Comment by SaptakS** [comment]
@nijel I was trying to work on this. I still get a huge form dropdown on clicking in the query part. 
![image](https://user-images.githubusercontent.com/9530293/77858789-45e0be80-7223-11ea-93b9-e403c11615ed.png)

Should I remove the dropdown and replace it with inline editing completely? Because as in this the above screenshot, that area is showing `Strings needing action`. 

The position thing completely makes sense and I see that the dropdown is completely misplaced and I think inline editing totally makes sense there

**Comment by nijel** [comment]
@SaptakS wrote on #3645:

> For making it inline editing, I think we need to make some design decisions. For example after clicking on the query field, do we show the applied filter (such as all queries) also or just replace that part by an input field? If we show the filter, I guess it needs to expand horizontally. Similarly for position, do we show an input field for the page number while still showing the total (I would prefer this)? or just an input box, with a max and min limit.
>
> I also think it will advantageous to move to bootstrap 4 because that gives us the scope to use flexbox directly. Flexbox really helps in designing grid-based UI.

**Comment by nijel** [comment]
Switching to Bootstrap 4 is certainly an option, there were some issues with RTL support last time I looked, see https://github.com/WeblateOrg/weblate/issues/2916.

For the search field, I'd really like to make it more flexible to allow building more complex queries easily. I've mentioned some examples (GitLab and Sentry) in https://github.com/WeblateOrg/weblate/issues/3063#issuecomment-594458085 and https://github.com/WeblateOrg/weblate/issues/3063#issuecomment-606029363

**Comment by SaptakS** [comment]
@nijel Great! In that case, won't it make more sense to separate the search field from the pagination group of buttons on the right sounds? And we can just keep the tab in pagination to switch between different filters of `All queries` and `Queries needing attention`, etc. I think UX wise that makes more sense since that tab doesn't really hint on opening an input query box. And I did look into #3063 and I feel a separate search field would be more flexible and give more options.

**Comment by nijel** [comment]
Yes that makes sense. UX wise still many of parts are results of myself not being comfortable in CSS and JS to do it way it would look best, so it ended up using default components present in bootstrap.

**Comment by nijel** [comment]
See also https://github.com/WeblateOrg/weblate/issues/3742

**Comment by SaptakS** [comment]
I was proposing something similar.

**Comment by nijel** [comment]
I think we could use something GitLab like as described in https://github.com/WeblateOrg/weblate/issues/3063#issuecomment-594458085. Example:

https://gitlab.com/fdroid/fdroid-website/-/issues?scope=all&utf8=%E2%9C%93&state=opened&author_username=uniqx

1. Dropdown of recent/bookmarked/frequent queries.
2. Editable query box with autocomplete.
3. Sorting selection.

**Comment by SaptakS** [comment]
> 
>     1. Dropdown of recent/bookmarked/frequent queries.
> 
>     2. Editable query box with autocomplete.
> 
>     3. Sorting selection.

Agree with this. I feel first we should go with separting this 3 parts like in gitlab and then iteratively focus on adding multiple elements (or query terms) in the query box like gitlab allows.

**Comment by nijel** [comment]
Thinking more about this, the final state should be following (I'm not saying we should reach it in single step, but just to define the direction we're heading):

* Sorting selection, which would autosubmit and keep current search term
* Dropdown with predefined queries, if current query will match one, it will show it's name, otherwise "Custom Search" (this logic already exists and is used to display query name right now)
* Text input with current search query
  * On focus dropdown would popup showing some help and recent queries
  * On typing it would offer autocompletion
  * This is heavily inspired by Sentry, so check out how it works here
* Action buttons in side of search query
  * Clear the query
  * Pin the query (make it default for current translation/component)
  * Add to saved searches (see #3060)
  * Open more detailed query builder (see #3063)
* Navigation

The basic look should be following (it lacks the navigation):

![image](https://user-images.githubusercontent.com/212189/79848651-a77aef80-83c1-11ea-84bc-08a845bb30a0.png)

Screenshots from Sentry to show how it behaves:

Recent queries shown on focus to text edit:

![image](https://user-images.githubusercontent.com/212189/79849687-16a51380-83c3-11ea-837e-9949c7f3956b.png)

Autocompletion on tag:

![image](https://user-images.githubusercontent.com/212189/79849787-3d634a00-83c3-11ea-9817-50bb77f0be8d.png)

Autocompletion on value:

![image](https://user-images.githubusercontent.com/212189/79849878-5d930900-83c3-11ea-9c93-3e7b85fcd2fc.png)

**Comment by SaptakS** [comment]
@nijel sounds great to me. I am gonna proceed with it iteratively building first the UI and then improving on the different features.

**Comment by nijel** [comment]
Query editing landed in https://github.com/WeblateOrg/weblate/pull/3766, the position needs to be done.
