### ISSUE TITLE
contribution onboarding: debugging Weblate with PyCharm

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#3309]
Sorry again to bother you with setup, but hard to work without the proper tools :-/ 

I'm working with PyCharm, and I'm apparently unable to properly use the debugger with it. The issue is that PyCharm keeps showing me an error because of celery.py doing an import on celery: 
> ImportError: cannot import name 'Celery' from partially initialized module 'celery' (most likely due to a circular import) (/home/urli/Github/weblate/weblate/celery.py)

I only get the error in the IDE if I specify `weblate/weblate` as source directory. 

If I don't specify the source directory, I don't get any error in the IDE and I can run the unit tests. But I cannot run the server and use the debugger: it looks like the debugger is not inspecting the breakpoints: whatever breakpoint I put, each time I start the debugger they are not triggered. (I used https://blog.jetbrains.com/pycharm/2017/08/develop-django-under-the-debugger/ to check)

So maybe I'm doing it all wrong, but it would be really useful for me if I could have a live debugger when performing operation on the server, to better understand how it currently works :)

**Comment by nijel** [comment]
Specify just `weblate` as source directory, it should do it. At least I hope, I have exactly zero knowledge of PyCharm. However it would be great if you could document it once it works for you as it's probably good way to start with developing Weblate.

**Comment by surli** [comment]
> Specify just weblate as source directory, it should do it. 

apparently it does not :-(

>  However it would be great if you could document it once it works for you as it's probably good way to start with developing Weblate.

I'd be glad to, as soon as I manage to make it work :)

**Comment by nijel** [comment]
What doesn't work with `weblate` as source dir?

**Comment by surli** [comment]
So just to clarify, I tried using both `weblate` (the cloned repository) and `weblate/weblate` (the weblate directory from the repo) as source directory.
In both cases I got the same issue with cyclic celery import: 
> ImportError: cannot import name 'Celery' from partially initialized module 'celery' (most likely due to a circular import) (/home/urli/Github/weblate/weblate/celery.py)

The only way I manage to make the IDE works is by not setting the source directory.

**Comment by nijel** [comment]
The cloned directory is what should work as source. When you will use weblate directory inside that, you will get error you describe.

Does PyCharm somehow set Python path as well? Is there some separate setting for that?

**Comment by surli** [comment]
> Is there some separate setting for that?

Yes it is: I actually specified my virtualenv config for the path, and I double checked that the paths included the libs coming from the venv.
Now maybe my error is that I created my virtualenv directly in the cloned dir? Basically I got `weblate/bin`, `weblate/lib` etc, so those libs are shown in my working dir.

**Comment by nijel** [comment]
Maybe that caused some mess, usually it's better to create virtualenv in a subdir (I usually use `.venv`).

**Comment by surli** [comment]
So for info, I just tried to clean everything (basically I completely remove the directory and cloned it again), to create back the virtualenv in a  `.venv` subdirectory, but I keep getting the same issue on PyCharm. I guess I'll open an issue to them :)

**Comment by surli** [comment]
In the meantime if you have any hint for live debugging on any other IDE, I take it :)

**Comment by nijel** [comment]
It must be something wrong with setting Python path. Apparently it tries to import celery module from weblate subdir, so it has to be in the path. Or something in PyCharm is ignoring absolute imports in `weblate/celery.py`.

**Comment by nijel** [comment]
You can try this suggestion: https://stackoverflow.com/a/35352735

**Comment by surli** [comment]
Thanks for the help, I finally manage to make it work. So the solution was to indeed to import the main directory as source directory AND to deactive the autoreload in the server configuration in PyCharm (cf screenshot).

![Capture d’écran_2019-12-19_08-39-35](https://user-images.githubusercontent.com/1478232/71154130-1ccf8b80-223b-11ea-86cb-3ff0457d6461.png)

I can try to provide some doc about setuping the project under PyCharm if you like, under contribution I guess?

**Comment by nijel** [comment]
Yes, having that documented would be great.

**Comment by nijel** [comment]
@surli Can you please write short documentation on using PyCharm with Weblate for our docs? Having this documented would be great.

**Comment by surli** [comment]
Yes it's still planned, I mainly need to spend a bit of time to redo the setup, takes screenshots and write steps at the same time. Shouldn't take too much time.

**Comment by nijel** [comment]
Great, thanks!
