### ISSUE TITLE
All project categories should be clickable

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3310]
1. https://hosted.weblate.org/projects/weblate/javascript/nb_NO/ and https://hosted.weblate.org/projects/weblate/master/
2. Click on categories, works
3. https://hosted.weblate.org/languages/nb_NO/ and https://hosted.weblate.org/projects/weblate/
4. Categories are not clickable.

![bilde](https://user-images.githubusercontent.com/13802408/70968092-967b4400-2098-11ea-8958-d65413190991.png)
For projects that only have one component in language view, and components in project view, it seems links could be added without extra functionality.

It would be great to have it work for "meta categories" of two components by loading one project after the other in the editor too. Then the different checks on https://hosted.weblate.org/checks/ wouldn't have to break into per project per language.

**Comment by nijel** [comment]
We don't have view for that, so there is no target for such link. See https://github.com/WeblateOrg/weblate/issues/49
