### ISSUE TITLE
Skewed "of total" percentage

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3312]
https://hosted.weblate.org/projects/night-clock/#languages

Norwegian Bokmål is fully translated, with all components added. Sits at "Of 55%" Only Ukrainian is of 100%, the difference being it is checked, to the tune if ~ 45%.

https://hosted.weblate.org/projects/onionshare/translations/ is of 98% in https://hosted.weblate.org/languages/nb_NO/ …

https://hosted.weblate.org/languages/nb_NO/debian-member-portfolio-service/ is also 98% in the language overview, and it has a comment.

So blue status category strings skews the "Of total"?

**Comment by nijel** [comment]
The problem is that Ukraninian has 76 strings, while others only 42. That's certainly some bug in loading the files...

**Comment by nijel** [comment]
Okay, found it - it's caused by recent added support for non translatable strings. Those were not loaded for existing translations, only for Ukranianian which was added recently.
