### ISSUE TITLE
Installing from source

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3317]
**Describe the bug**
I'm tryng to update to latest from source and run into some trouble. To be honest I don't have much experience with pip so maybe I'm just missing something basic.
So I'm following [this](https://docs.weblate.org/en/latest/admin/install/source.html#quick-source) instruction which says to follow the [installation instructions](https://docs.weblate.org/en/latest/admin/install/venv-debian.html) for my system first, which is Debian 9.

**To Reproduce**
1. All the necessary packages are already installed I'm creating virtualenv for Weblate
`virtualenv --python=python3 weblate-env-3.10`
Output is the following:
```
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /var/www/weblate-env-3.10/bin/python3
Also creating executable in /var/www/weblate-env-3.10/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
```
2. Then I activate the environment `. weblate-env-3.10/bin/activate`
3. `pip install Weblate` The output is [here](https://pastebin.com/ZigzmJan)
4. `pip install psycopg2-binary`
5. Now if i go to `weblate-env-3.10/lib/python3.5/site-packages` there is a directory called `weblate`
6. `git clone https://github.com/WeblateOrg/weblate.git /root/weblate-src`
7. Now I run `pip install -e /root/weblate-src` [Output of the command](https://pastebin.com/ZhzRcpdN)
8. But now if I go to `weblate-env-3.10/lib/python3.5/site-packages` there is no more directory called `weblate`

I guess at this point I'm supposed to manually copy `weblate` folder from `weblate-src`, am I?
If so it would be nice to mention it in the documentation, just for clarity.

**Comment by nijel** [comment]
No, `pip install -e` creates there `weblate.egg-link` link with location to the actual source.

**Comment by tariver** [comment]
Thanks for clearing it out, didn't notice it.

Does it mean that in the future to update I just need to pull changes from repository to update?
Off course with performing database migrations etc.

**Comment by nijel** [comment]
Yes, pulling to update the source, but you need to do other needed steps, for example install updated dependencies.
