### ISSUE TITLE
Shortcut tooltip is empty

### ISSUE THREAD

**Issue by reloxx13** [WeblateOrg/weblate#3319]
**Describe the bug**
Since a few versions the shortcut tooltip is broken :(
The link icon tooltip and others work fine.

Currently Weblate 3.9.1, tested in firefox and chrome.

**To Reproduce**
Just start translating and hover the keyboard icon.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/14855001/71068320-c39e2400-2176-11ea-9300-c4d9cb89f1e6.png)

**Server configuration and status**

**Comment by nijel** [comment]
It has been completely removed for the 3.10 release.

**Comment by reloxx13** [comment]
why =O ?

it was always helpful for new translators.

**Comment by nijel** [comment]
One of the reasons is https://github.com/WeblateOrg/weblate/issues/2034, we first need to make the shortcuts work reliably on all platforms and then can advertise them more visibly. The other reason is that it really doesn't belong in this place. The same keyboard shortcuts work in zen mode and should be visible there as well. Once we have sorted out them on all platforms, we need to find new place to advertise them.
