### ISSUE TITLE
Component discovery: sticky addons

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#3326]
**Is your feature request related to a problem? Please describe.**
When you configure component auto discovery and have many components, adding a new addon on each component takes a lot of time.

**Describe the solution you'd like**
Add an option to ask all components to use the same set of addons: the one of main component.

**Describe alternatives you've considered**
We may delete existing components and generate again, but I think we'll loose change history

**Comment by nijel** [comment]
There is checkbox for that - clone addons from main component. Also see https://docs.weblate.org/en/latest/admin/addons.html#component-discovery

**Comment by Jibec** [comment]
Yes, but this features only exists on component creation.
If you want to add a new addon, you'll have to add it to each components 
(the main one and the automated ones)

**Comment by nijel** [comment]
I think the project- and site- wide add-ons address this better than handling this in the discovery.

**Comment by Jibec** [comment]
It does. Thank you.
Jean-Baptiste
