### ISSUE TITLE
Chaging source string doesn't mark translations as "Needs editing"

### ISSUE THREAD

**Issue by Bubu** [WeblateOrg/weblate#3330]
**Describe the bug**
For fdroiddata I just pushed some updates in the english translation sources. I'd expect all translations of the changed source strings to be marked as "needs editing". None of them are marked this way though.

**To Reproduce**
1. Push updates to the source repo
2. Go to translation and search for the changed string
4. See that needs editing is not checked.

See for example here: 
https://hosted.weblate.org/translate/f-droid/fdroiddata/pt/?q=Chaos&checksum=&offset=

**Screenshots**
![image](https://user-images.githubusercontent.com/105185/71280422-7333eb80-235b-11ea-8eeb-46d0fc463fab.png)

**Comment by nijel** [comment]
Weblate doesn't do any such detection for bilingual formats. The reason behind that is that in most of bilingual formats, the source string is actually the identifier, so there is no way to detect it has been changed.

With xliff it's a bit different - the strings are identified by IDs, so people tend to expect Weblate to do this kind of thing, but it behaves same as with other formats. The easy fix for this is to configure the translation as monolingual, it will then work as expected.

**Comment by eighthave** [comment]
I set the "Monolingual base language file" to _localizations/en-US.xliff_, I think it took effect, but it doesn't seem to be retroactive.

**Comment by eighthave** [comment]
Oops, but now the original link in the issue description is giving an Internal Server Error.  And after resetting "Monolingual base language", I'm still getting:

```
Server Error

The server had serious problems serving your request. Trained monkeys are en-route fixing the issue.

If you need assistance, you may reference this error as 782a82bd6dc14d2b966d3687e8cd5936.
```

**Comment by nijel** [comment]
Yes, it will only affect newly changed strings. The related bug is https://github.com/WeblateOrg/weblate/issues/3331, I'm looking into that.
