### ISSUE TITLE
[English Translation] Source string should be plural

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#3332]
The following source string is displayed in notification emails and should be in plural form according to me. I already performed the change for french.

String:
https://hosted.weblate.org/translate/weblate/master/en/?checksum=165b713e6838d138

Usage of this string
![Weblate Mail](https://user-images.githubusercontent.com/1452146/71309254-193c3000-2406-11ea-87c9-258baec883df.jpg)

Alternative (particularly if this string is used elsewhere in Weblate) => to have 2 strings (and in the code use one or the other):
- 1 singular string
- 1 plural string

Thanks,

**Comment by nijel** [comment]
Hmm, we don't count the strings, so it actually means "at least one new string to translate". I will take a look if we can actually count them and use proper plurals here.
