### ISSUE TITLE
azure Social Auth question

### ISSUE THREAD

**Issue by PokerLi** [WeblateOrg/weblate#3333]
I used “WEBLATE_SOCIAL_AUTH_AZUREAD_OAUTH2_KEY” and WEBLATE_SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET ““WEBLATE_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_TENANT_ID”
when i login it ，the redirect_uri always https://example.com/accounts/complete/azuread-oauth2
；
How do i set redirect_uri in weblate config
![image](https://user-images.githubusercontent.com/32827584/71334861-db144d00-257a-11ea-8f5e-672fc1bf26ec.png)

**Comment by PokerLi** [comment]
The doc only have five config about azure，I can't get more information，so please help me

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/faq.html#why-do-links-contain-example-com-as-the-domain

**Comment by PokerLi** [comment]
thans very much，it‘s working
