### ISSUE TITLE
RTL Source information box

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#3334]
While editing a string I've noticed that the location of the file is RTLed while usually filenames are in English, they should remain ltr and also the arrow should be in the right place (to the right).

Current:
<img width="324" alt="Screen Shot 2019-12-23 at 13 48 54" src="https://user-images.githubusercontent.com/406826/71357151-51ba4600-258d-11ea-958e-f1747e48a4ae.png">

Correct:
<img width="321" alt="Screen Shot 2019-12-23 at 14 02 21" src="https://user-images.githubusercontent.com/406826/71357131-3bac8580-258d-11ea-8a8e-4aa4853dacc1.png">

(I know it's the old design but it's relevant to the new one as well)

**Comment by nijel** [comment]
Actually it's not valid in current design, as those icons are gone.

**Comment by yarons** [comment]
But it's not only about the icons, the text is RTL instead of LTR.

**Comment by nijel** [comment]
You're right, I've noticed that just after posting and fixed that in https://github.com/WeblateOrg/weblate/commit/1c479378af47b31fe5aa045cdb8b9637024128b6
