### ISSUE TITLE
Implement a way to discover newly added projects

### ISSUE THREAD

**Issue by Ereza** [WeblateOrg/weblate#3335]
**Is your feature request related to a problem? Please describe.**
I translate several projects on Hosted Weblate into Catalan (including Weblate itself), and I think it would be really cool to be able to discover newly added projects (in order to decide if I'm interested in translating them too). Currently the list of projects can not be sorted by creation date or any similar option.

**Describe the solution you'd like**
Either a way to sort the list of projects by creation date, or a specific page or dashboard tab with the newest projects.

**Describe alternatives you've considered**
Right now my only alternative is to remember the list of projects (or copy/paste them into a file), and later check for differences manually.

**Additional context**
Maybe this could be reworked somehow into the "Suggested translations" tab on the dashboard? Maybe it could suggest the newest projects first.

**Comment by nijel** [comment]
Related to https://github.com/WeblateOrg/weblate/issues/3036

**Comment by nijel** [comment]
You can already browse recent additions here: https://hosted.weblate.org/changes/?action=51&action=50
