### ISSUE TITLE
Check for number of lines

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3339]
**Is your feature request related to a problem? Please describe.**
There is resx with a following key
```
  <data name="ErrorServerVersionNotSupportedMessage" xml:space="preserve">
    <value>Для работы необходима версия ProgramName не ниже {0}!
Обратитесь к администратору.</value>
  </data>
```
Note that it has two lines.
If the translator enters the translation just in one line as
```
Sie benötigen eine ProgramName Version {0} or höher! Wenden Sie sich an den Administrator.
```
Weblate accepts it without question.
Here how it looks in Weblate:
![image](https://user-images.githubusercontent.com/36223356/71509790-9c91d180-289d-11ea-8e80-acecfa8677a5.png)

**Describe the solution you'd like**
It would be nice to have a check for number of lines or number of end of paragraph characters, so that translators would be warned that they need to make the translation in more than one line.

**Comment by nijel** [comment]
In case somebody is looking into implementing this, similar check was added in https://github.com/WeblateOrg/weblate/pull/3115, so you can base code on these changes.

**Comment by savornicesei** [comment]
@nijel  There already exists BeginNewlineCheck and EndNewLineCheck but they do not check for Windows end of line (\n\r) just for the *nix end of line (\n).

As a side note,
when installing git on Windows you can choose to push changes with *nix EOL or leave the files as they are (with Windows EOL)

Best,
Simo

**Comment by nijel** [comment]
That's true as browsers to submit just \n as a newline. In case you see a problem with that, please open separate issue.

**Comment by Naruto0** [comment]
Does this check only work for escaped newlines? https://github.com/WeblateOrg/weblate/blob/4548d84cc312d9c10e5e53f7665754bb7394c562/weblate/checks/chars.py#L320-L327

**Comment by nijel** [comment]
There is currently only check for escaped newlines, the one for actual new lines is not yet there.
