### ISSUE TITLE
Changed source string and guide for translations different

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3340]
https://hosted.weblate.org/translate/pext/pext_module_pass/nb_NO/?checksum=8849f9294dea9b14
Changed this string without the guide for translations updating.
Either it isn't changed, or it should update?

**Comment by nijel** [comment]
Actually, it should not be possible to change source for bilingual translation files. In this case it's possible, because there is a PO file for source language, but such corner case should be handled by Weblate gracefully.
