### ISSUE TITLE
Translating documentation

### ISSUE THREAD

**Issue by Lyttym** [WeblateOrg/weblate#3344]
Weblate documentation is available in English only. Why not provide the opportunity to translate documentation into other languages ?

**Comment by nijel** [comment]
That's something I wanted to do after doing some cleanup and improvements in the docs, but this is something what always gets postponed.

**Comment by comradekingu** [comment]
I think having it available for translation is a good way to get fixes in. I'll make sure to stay on it if that is the case. Just reading through something and editing it, is not a whole lot easier than translating it simultaneously.

**Comment by nijel** [comment]
As more people asked about this, it's now there (well it's in progress, but all languages will appear shortly): https://hosted.weblate.org/projects/weblate/documentation/

I will add documentation builds once the language will get reasonable coverage.

Happy translating.

**Comment by nijel** [comment]
@rffontenelle seems to be the fastest one to start working on this, here comes first localized version: https://docs.weblate.org/pt_BR/latest/
