### ISSUE TITLE
Missing docs for zen editor

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3345]
The [user documentation](https://docs.weblate.org/en/latest/user/translating.html) lacks any mention of zen editor and documenting its behavior.

**Comment by thePlebDev** [comment]
is this still up for open??

**Comment by orangesunny** [comment]
Yes, if you are open to write it, please do it! The whole community will be happier 😄

**Comment by thePlebDev** [comment]
you got it boss

**Comment by thePlebDev** [comment]
where do I find the zen editor?

**Comment by orangesunny** [comment]
To answer the deleted post if you are still interested: 

There is a ⚡️ `ZEN` button in top-right corner when you are translating. Or just click on, e.g. https://hosted.weblate.org/zen/weblate/application/fr/? 😃
