### ISSUE TITLE
Pull request for Pagure hosted projects

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#3346]
Maintainers don't like to provide direct commit rights to Weblate.
Seeing a pull request is something what maintainers prefer to have.

Could you please add pull request support for Pagure?

Pagure URL: https://pagure.io/pagure
Pagure API: https://pagure.io/api/0/#pull-requests

I created a weblatebot on Pagure, let me know if you wish to take control of it.
Thanks a lot for your help.

**Comment by nijel** [comment]
@Jibec Is there some CLI utility to interact with Pagure? We're using [hub](https://github.com/github/hub) and [lab](https://github.com/zaquestion/lab) to interact with GitHub and GitLab. Having something similar would make implementation easier than dealing with the API directly.

**Comment by Jibec** [comment]
you should put this request on hold, because of this: https://communityblog.fedoraproject.org/git-forge-requirements/

**Comment by nijel** [comment]
@Jibec Did I get it correctly, that Fedora is moving towards GitLab and thus Pagure integration is no longer important?

We're now starting to work on https://github.com/WeblateOrg/weblate/issues/3493 and I'd like to clarify if we're going to include Pagure in the list as well.

**Comment by Jibec** [comment]
I'm unsure what to say here.

As far as I know, Pagure will remain an active project, but the platform won't be used for some key Fedora infrastructure I think.
We'll still have projects hosted on https://pagure.io

It still really makes the feature nice to have, and not mandatory.

**Comment by nijel** [comment]
Thanks for clarification!

**Comment by nijel** [comment]
Since https://github.com/WeblateOrg/weblate/pull/4224 we have generic layer for implementing pull requests support. So all what is needed is to trigger few API calls on the Pagure to for a repo and create a pull request. The most tricky part in this is usually error handling (deal existing forks and pull requests).

For example, code for GitHub is here:

https://github.com/WeblateOrg/weblate/blob/b317c87a5b0397d4ed00845c9bba3a8c0066be15/weblate/vcs/git.py#L687-L772

**Comment by nijel** [comment]
@Jibec I've just implemented this. I expect there will be some rough edges because the API is not that well documented. In case you want to try it out on Fedora Weblate, please write to support@weblate.org with token or credentials for the bot user you want to use there.
