### ISSUE TITLE
ImportError: cannot import name 'Celery'

### ISSUE THREAD

**Issue by sowinski** [WeblateOrg/weblate#3347]
**Describe the bug**
Please find bellow the link to the problem.

https://stackoverflow.com/questions/59561039/fresh-weblate-installation-importerror-cannot-import-name-celery

**To Reproduce**
I tried the installation on different systems and I get always the same problem.

**Comment by nijel** [comment]
Most likely `PYTHONPATH` for gunicorn contains `/var/www/ws5weblate/priv/weblate-env/lib/python3.5/site-packages/weblate` which it should not include.
