### ISSUE TITLE
allow to store only po files in upstream repository

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#3349]
Some upstream repository don't want to store pot file.
Theses upstream repository won't let Weblate commit in their repository or open pull requests.

**Describe the solution you'd like**
What they wish to have:
* wlc upload project.pot => expected result: weblate updates all po files and allows to add new languages
* wlc download => all po files are downloaded

**Describe alternatives you've considered**
Libvirt did a hack with monolingual gettext file: https://www.redhat.com/archives/libvir-list/2019-December/msg01014.html and https://bugzilla.redhat.com/show_bug.cgi?id=1783579
Cockpit project probably will create a dedicated repository: https://github.com/cockpit-project/cockpit-podman/issues/267

**Additional context**
The reasons why projects don't want pull requests and localization commits in their repositories:

* The file size: https://www.berrange.com/posts/2018/11/29/improved-translation-po-file-handling-by-ditching-gettext-autotools-integration/
* The way Weblate let us control when it tries to push changes to upstream repo. As far as I know, we can't set a push branch for a component and only trigger the push manually.

**Comment by marusak** [comment]
> The reasons why projects don't want pull requests and localization commits in their repositories:

I would also add that it is a lot of work to keep `.pot` file up to date. Or then having old `.pot` file in upstream and update it from time to time. (Each commit which touches strings in any way would also have to update `<project>.pot` file)

**Comment by nijel** [comment]
There is no need for pot file until you want Weblate to be able to create new translations.

The upload for pot is already covered by https://github.com/WeblateOrg/weblate/issues/3263.
