### ISSUE TITLE
Query "state:<translated" not showing expected results

### ISSUE THREAD

**Issue by reloxx13** [WeblateOrg/weblate#3353]
**Describe the bug**
Using the query` state:<translated` or `state:empty` shows all strings.
For some projects the number of strings needing action/not translated strings wont show up under "String status".
The bug accured after the update to 3.10.
I followed the generic upgrade instructions, updated my settings.py, restarted redis/celery/uwsgi, updated with pip(requierements/-optional) and added the translate queue to celery-weblate.

 

**Expected behavior**
Showing the first string that needs editing after clicking on "String status"->"Strings needing action" and only showing 1/108 not 1/3065.

 

 

**Screenshots**
On the first screenshot you can see that german has 62 untranslated strings. 
![languagelist](https://user-images.githubusercontent.com/14855001/71896737-dcd23900-3154-11ea-8044-81a1d13b8528.PNG)

On the second screenshot under "String status" not translated strings wont show up.

 
![germanstringstatus](https://user-images.githubusercontent.com/14855001/71896770-ee1b4580-3154-11ea-8639-ef514e669b3f.PNG)

On the next two screenshots you can see that the english language shows all the strings needing action/not translated strings. If you choose to click on one of them you'll get all strings instead of only the ones needing action

![englishstringstatus](https://user-images.githubusercontent.com/14855001/71896798-fc696180-3154-11ea-9524-9d31e83451f9.PNG)

![stringsneedingactionquery](https://user-images.githubusercontent.com/14855001/71896807-00957f00-3155-11ea-8a68-512d209b8aed.PNG)

 

 

 

**Server configuration and status**

 * Weblate: weblate-3.10
 * Django: 2.2.9
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.4.0
 * lxml: 4.4.2
 * Pillow: 6.2.2
 * bleach: 3.1.0
 * six: 1.13.0
 * python-dateutil: 2.8.1
 * social-auth-core: 3.2.0
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.8.1
 * oauthlib: 3.1.0
 * django-compressor: 2.3
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.3
 * user-agents: 2.0
 * filelock: 3.0.12
 * setuptools: 44.0.0
 * jellyfish: 0.7.2
 * openpyxl: 2.6.4
 * celery: 4.4.0
 * kombu: 4.6.7
 * celery-batches: 0.2
 * translation-finder: 1.7
 * html2text: 2019.9.26
 * pycairo: 1.18.2
 * pygobject: 3.34.0
 * diff-match-patch: 20181111
 * requests: 2.22.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.13.5
 * Cython: 0.29.14
 * misaka: 2.1.1
 * GitPython: 3.0.5
 * borgbackup: 1.1.10
 * Python: 3.5.3
 * Git: 2.11.0
 * psycopg2: 2.8.3
 * psycopg2-binary: 2.8.3
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.5
 * tesserocr: 2.5.0
 * akismet: 1.0.1
 * boto3: 1.10.47
 * zeep: 3.4.0
 * aeidon: 1.6.0
 * git-review: 1.28.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: SMTP.office365.com
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.9.0-9-amd64 (x86_64)

 

System check identified some issues:

 

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.

 

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.10/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.10/admin/backup.html

 

System check identified 3 issues (1 silenced).
 

 

**Additional context**
Clicking on Failed Checks/Strings with any failing checks works.

**Comment by nijel** [comment]
Currently, the logical operator has to be upper case: `state:<translated OR state:empty`. The way you used it is searching for "or" string in all source/translation/context, what makes many hits.

```pycon
>>> from weblate.utils.search import parse_query
>>> parse_query('state:<translated or state:empty')
<Q: (AND: ('state__lt', 20), (OR: ('source__icontains', 'or'), ('target__icontains', 'or'), ('context__icontains', 'or')), ('state', 0))>
>>> parse_query('state:<translated OR state:empty')
<Q: (OR: ('state__lt', 20), ('state', 0))>
```

We probably need something better to parse the queries, see https://github.com/WeblateOrg/weblate/issues/3229

**Comment by reloxx13** [comment]
Heya,

there is no "or" in the query.

**Comment by nijel** [comment]
Sorry for misreading that. Seems there are more issues here. 

What file format and component configuration do you use? Bilingual or monolingual?

Do you happen to use bilingual translation format and have existing translation file for source language? In that case you are probably hitting https://github.com/WeblateOrg/weblate/issues/3340 

Stale stats cache on the source language showing wrong numbers in the overview, it probably should have been cleared on the migration.

You can try running `./manage.py loadpo --force internetortnung-web/app` if that fixes some of the issues?

**Comment by reloxx13** [comment]
I made a new installation and imported the old database and setting files and now the queries are working.

**Comment by reloxx13** [comment]
Heya,

we managed to find the issue now.

On live server we had set 
```
# Language code for this installation. All choices can be found here:
# http://www.i18nguy.com/unicode/language-identifiers.html
LANGUAGE_CODE = "de"
```
in the settings.py.

If i click on a filter (image below) the following URL is generated and the query/filter is not working, showing all translation strings:
`https://weblate.live/translate/projectname/app/en_GB/?q=state:%3Ctranslated`

If i change the query to `q=state:<übersetzt`, the query filter is working again.
`https://weblate.live/translate/projectname/app/en_GB/?q=state:%3C%C3%BCbersetzt`

When we switch back the LANGUAGE_CODE to ´en-us´, the queries with ´translated´ are working again.

This only applies after executing ´compilemessages´.

![grafik](https://user-images.githubusercontent.com/14855001/72327374-3f758880-36b1-11ea-939b-22b93262d1fa.png)



Suggestion: 
- Dont use the translated query names in the filtering (backend)
- Translate the generated query in URLs from the links/buttons
- Add a hint to NOT change the language code, cause it does nothing (?)

**Comment by reloxx13** [comment]
👍 👍 👍
