### ISSUE TITLE
WebHook StatusCode 200 return even on failure

### ISSUE THREAD

**Issue by aparcar** [WeblateOrg/weblate#3354]
**Describe the bug**

GitHub WebHook return statuscode 200 even if repositories are missing.

**To Reproduce**
This is currently happening to `openwrt/luci`, I have no additional Weblate instance to test it.

**Expected behavior**
The Weblate instance should a) find the repository (as it actually exists) and b) update it.

**Screenshots**
![image](https://user-images.githubusercontent.com/16000931/71920110-2d806c80-312a-11ea-96cf-f6d2f7634a65.png)

**Comment by nijel** [comment]
Did you change something on the `openwrt/luci` project as I see it's now matching.

The response code is always 200 as in past some of the services (I don't recall if that was GitHub, GitLab or Bitbucket) disabled the webhook after some amount of errors. On projects using feature branches there is lot of events for branches which Weblate doesn't know. Maybe using 202 might be better approach in such cases, that seems to be currently recommended by GitHub, see https://developer.github.com/v3/guides/best-practices-for-integrators/#use-appropriate-http-status-codes-when-responding-to-github

**Comment by aparcar** [comment]
Sorry for the delay, yes I fixed the LuCI repository by removing the leading slash.
