### ISSUE TITLE
LDAP Auth fails with KeyError

### ISSUE THREAD

**Issue by tholu** [WeblateOrg/weblate#3359]
**Describe the bug**
LDAP Auth fails after upgrading from 3.8 to 3.10

**To Reproduce**
1. Go to 'Homepage'
2. Try to Login with LDAP credentials
3. See error

```
Exception Type:	KeyError
Exception Value:	
'username'
Exception Location:	/usr/local/lib/python3.7/dist-packages/django_auth_ldap/backend.py in _construct_simple_user_dn, line 527
```

**Expected behavior**
Login succeeds

**Server configuration and status**
Please paste the output of `list_versions` and `check --deploy` commands over
here. Depending on installation these can be executed in different way, please
consult https://docs.weblate.org/en/latest/admin/management.html for more
details.

```
* Weblate: 3.10
 * Django: 2.2.8
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.4.0
 * lxml: 4.3.2
 * Pillow: 6.2.1
 * bleach: 3.1.0
 * six: 1.13.0
 * python-dateutil: 2.8.1
 * social-auth-core: 3.2.0
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.8.1
 * oauthlib: 3.1.0
 * django-compressor: 2.3
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.3
 * user-agents: 2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.1
 * celery: 4.3.0
 * kombu: 4.6.3
 * celery-batches: 0.2
 * translation-finder: 1.7
 * html2text: 2019.9.26
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.22.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.13.5
 * Cython: 0.29.14
 * misaka: 2.1.1
 * GitPython: 3.0.5
 * borgbackup: 1.1.10
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.7.7
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.5
 * tesserocr: 2.5.0
 * akismet: 1.0.1
 * boto3: 1.10.44
 * zeep: 3.4.0
 * aeidon: 1.6.0
 * Mercurial: 4.8.2
 * git-svn: 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.elasticemail.com
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.9.0-8-amd64 (x86_64)
```

```
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.10/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.10/admin/backup.html
```

**Additional context**
Deployed via docker-compose. LDAP Login worked fine in 3.8. New logins failed after upgrading to 3.10.

**Comment by nijel** [comment]
Probably your [WEBLATE_AUTH_LDAP_USER_DN_TEMPLATE](https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_AUTH_LDAP_USER_DN_TEMPLATE) contains `%(username)s` instead of `%(user)s`?

**Comment by tholu** [comment]
@nijel You're right, I changed that (did that change in 3.10?), but login still fails now (without the error) with:

> This username/password combination was not found. Please try again.

What's the actual content of `user`?

**Comment by nijel** [comment]
Whatever you enter as a username. I don't think this has changed, the format of this is still the same - it's done by [django-auth-ldap](https://github.com/django-auth-ldap/django-auth-ldap/blob/99090772cd7275d2ff6bbb27816894aa89cdba49/django_auth_ldap/backend.py#L524-L527) and the code didn't seem to get any substantial change in last years.

**Comment by nijel** [comment]
What has changed, is that errors from LDAP authentication are logged, so maybe it was never working for you?

**Comment by tholu** [comment]
@nijel I'm currently also doubting that it ever worked 🤔  Will double-check and let you know!

**Comment by tholu** [comment]
@nijel Closed in favor of: https://github.com/WeblateOrg/docker-compose/issues/15
