### ISSUE TITLE
AADSTS900144: The request body must contain the following parameter: 'client_id'. when trying to authenticate with azuread-tenant-oauth2

### ISSUE THREAD

**Issue by zsotesz81** [WeblateOrg/weblate#3360]
Hi 

I am trying to authenticate with azuread-tenant-oauth2 . I added the client id, client secret and tenant id to the environment file. But when I try to authenticate I am receiving the following error:
AADSTS900144: The request body must contain the following parameter: 'client_id'
This is the whole url: https://login.microsoftonline.com/eb36d020-2c35-44de-bc7a-554cc979b26d/oauth2/authorize?client_id=&redirect_uri=https://myweblate.com/accounts/complete/azuread-tenant-oauth2/&state=IhwvUlDyWEhTr8nAPrKjjuw1JOJDvgQd&response_type=code&scope=openid+profile+user_impersonation
The client id is missing from the link.

**Comment by nijel** [comment]
Are you setting correct variables? Please note that these are different for tenant and normal setup, see https://docs.weblate.org/en/latest/admin/install/docker.html#azure-active-directory-with-tenant-support

**Comment by zsotesz81** [comment]
I believe yes, i configured the following values:
WEBLATE_SOCIAL_AUTH_AZUREAD_OAUTH2_KEY=
WEBLATE_SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET=
WEBLATE_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_TENANT_ID=
And I added social_core.backends.azuread_tenant.AzureADTenantOAuth2 as authentication backend to settings-override.py

**Comment by nijel** [comment]
The KEY and SECRET variables are *different* for tenant auth.

**Comment by zsotesz81** [comment]
Oh, shoot, i missed that part, thank you for the help.
