### ISSUE TITLE
How to add a new language to a component?

### ISSUE THREAD

**Issue by pbaeumel** [WeblateOrg/weblate#3367]
Dear all,

I just installed weblate through docker on a VPS.
Then I created a project and two components.

Now I try - for nearly the whole day - to add a new language to the component.
Unfortunately it did not work out so far.

If I click the button "Start new translation", then select "German" for example, then click on "Request new translation", then the message "A request for a new translation has been sent to the project's maintainers." confirms my action.

Question is:
How should the process look like after this steps? Where does the maintainer add the requested language? (I haven`t found any section in the gui, there is no message poping up in the GUI, I didn`t receive an E-Mail with a confirmation link?)

Best regards,
Patrick

**Comment by nijel** [comment]
What happens depends on how you configured *New translation* component setting. Weblate can automatically add new translations if configured so, see https://docs.weblate.org/en/latest/formats.html#adding-new-translations. In case you don't let Weblate add new languages, you have to add them in the VCS repository.

**Comment by MacGyver2018** [comment]
@nijel 
I have an en_EN.po base-file available. By setting up the component I uploaded that one .po-file inside a ZIP-File through the Web-GUI.

I do not use any foreign VCS for this translation project at all; I therefore assume that Weblate itself is generating and using a local VCS.

Unfortunately I have not been able to use the "automatically add new translation" setting as the system always shows me an error that it can not find the template file (even if I included a .pot file in my first ZIP-Upload).

So I ended in setting "inform maintainer about languge request". 

How do I add the new language to the internal VCS of weblate; must there be any conditions met (specific filename of .po-file withe new language / specific sub-folder / specific content of .po file)?

Additionally one question remains:
How is the maintainer / admin of Weblate notified about any request for a new language (if the manual setting ist used); I didn`t geht any email or other notification.

Best regards,
Patrick

**Comment by nijel** [comment]
You should be able to set path to the POT file in the component setting, it should then work. When you created the translation from ZIP, there is currently no way to update it, it will be addressed in https://github.com/WeblateOrg/weblate/issues/3263.

**Comment by MacGyver2018** [comment]
@nijel 
The ZIP-uploaded en.po file contains only the english base strings.
For me it sounds okay that this special file could not be updated.

I will now start over again (after I checked if a new language will show up after uploading a de.po file - again this has not worked.

Will it be possible to shortly direct me step-by-step after I have add the project?

Best regards,
Patrick

**Comment by nijel** [comment]
You need to configure template for new languages. If you uploaded the POT file with PO files, you should be able to set it in the settings.
