### ISSUE TITLE
Make Java MessageFormat check about an apostrophe more clear

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3371]
**Is your feature request related to a problem? Please describe.**
When a single apostrophe is used with a variable a check is triggered (see [this stackoverflow question](https://stackoverflow.com/questions/4449639/apostrophe-doesnt-get-translated-properly-when-placed-in-a-resource-bundle))
Example of a java properties file
```
key = {0}'s brush is {1} centimeters tall
```
Check message is "Following format strings are wrong: {'}" which, in my opinion is not very clear and descriptive.
![image](https://user-images.githubusercontent.com/36223356/72331554-7061b780-36c9-11ea-94a7-e474ccf11d87.png)

**Describe the solution you'd like**
It would be nice to change the description to something more straight, for example "You need to screen an apostrophe with another one" and maybe add an option for fixing it with "Fix string" button.

**Comment by comradekingu** [comment]
@tariver I don't really understand the "to screen" part. How does "to screen" mean whatever the action to be done, and what is that action?
See https://hosted.weblate.org/translate/weblate/master/en/?&offset=102#comments

**Comment by fitojb** [comment]
Yeah, the correct verb to use here is “mirror” or easier, “pair”, but not “screen” @nijel

**Comment by nijel** [comment]
I've changed it to "pair up" in 5454c0a5139442a3303f3269101bfd3f28362234, thanks for feedback.
