### ISSUE TITLE
Weblate & large .NET project

### ISSUE THREAD

**Issue by savornicesei** [WeblateOrg/weblate#3372]
Hi all,

We have a large .NET project: ~250+ visual studio projects (.csproj) organized in 7+ visual studio solutions (.sln) for which we want to use weblate as translation tool.
Currently translation is handled by some custom XLIFF tools and Redpin's Babylon.NET and already translated terms are kept in a custom sql database. The xliff tools generate xliff files that are send over to translators and then merged into the Babylon.NET that recreates the resx files.

Given the current state of Weblate and the poor support for resx of translation kit:

1. creating one weblate component for a resx file is a no-go for us (given the size of the project)
    1. what would work: define a regex for selecting resx files to be included in the component

2. we handle resx <-> xliff (pushing xliff files in a separate git repo) and weblate does the rest but:
    1. most of the translation tools support xliff 2.0; translation kit does not
    2. weblate supports xliff 1.2 but translations can only be downloaded as xliff 1.1
    3. when creating a new component in weblate > "Start from scratch" I cannot select xliff as file format (it does not appear in the list)
    4. will weblate preserve the imported xliff file (term ids, skl tags, notes)? Having .skl files would be great for us to recreate the resx files but does weblate differentiate between the term id from skl and the id from memory translation?
    5. can weblate also export the term id and context?
    6. can we import the existing translated terms, including context into weblate MT? How? I've been looking for the needed json schema but it's not documented.
    7. how should we handle translations for project releases? I looked over the openSUSE weblate instance - at [yast-slide-show project](https://l10n.opensuse.org/projects/yast-slide-show/). There each release is a translation component. But in our scenario - if we have the resx files in /release/1.0 and push them as xliff files in /l10n/release/1.0 - how should we configure them in weblate?
I think I would like to be able to organize components into modules.

Please throw in your thoughts on how .NET big projects should integrate with weblate.

Thanks,
Simo

**Comment by nijel** [comment]
There is always one file per component. You can define [component discovery](https://docs.weblate.org/en/latest/admin/addons.html#component-discovery) to create components automatically.

For xliff 2 support see https://github.com/WeblateOrg/weblate/issues/972.

To import translation memory, TMX is recommended as a standard format. JSON schema is indeed not documented right now, I've created https://github.com/WeblateOrg/weblate/issues/3373 for that.

"Start from scratch" is not really recommended approach if you already have dozens of translation files, it's way more effective to let Weblate connect to your VCS repository and handle translations directly.
