### ISSUE TITLE
Document JSON schema for translation memory

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3373]
**Is your feature request related to a problem? Please describe.**
Weblate does import/export translation memory in JSON format, but its schema is not documented.

The example file is here:

https://github.com/WeblateOrg/weblate/blob/24a460e52787008cb8947ec4c25d96ce5c41e3f3/weblate/trans/tests/data/memory.json#L1-L10

**Describe the solution you'd like**
Publish [JSON schema](https://json-schema.org/) for this format.

**Describe alternatives you've considered**
It could be also described in the docs.

**Additional context**
Originally mentioned in https://github.com/WeblateOrg/weblate/issues/3372 by @savornicesei

**Comment by Burzo** [comment]
Working on this one :)

**Comment by nijel** [comment]
Thanks! In case you need any help just ask me :-).

**Comment by Burzo** [comment]
@nijel Well its already finished actually, but since I'm still learning the Git flow I'm having versioning / branching troubles :( I accidentally commited to master in the past and rebasing didn't help at all now. Should I just delete my fork and fork the repo again?

**Comment by nijel** [comment]
I've drafted https://github.com/WeblateOrg/weblate_schemas to contain such schemas based on schema provided in https://github.com/WeblateOrg/weblate/pull/3380. There is still quite some work to make it usable:

* Make the schema actually describe the content, see https://github.com/WeblateOrg/weblate/pull/3380#discussion_r378111146
* Release the package to PyPI
* Use the schema validation from this package inside Weblate, similarly as in https://github.com/WeblateOrg/weblate/pull/3380/files#diff-8f636c5fbc21f80a1c18869a41a0baef

**Comment by nijel** [comment]
The package is now released on PyPI: https://pypi.org/project/weblate-schemas/
