### ISSUE TITLE
shoud auto-translation count as an anonymous contribution?

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#3374]
the auto-translation project is a really interesting feature: https://docs.weblate.org/en/latest/user/translating.html#auto-translation

I enable it by default on every component of the Fedora project translation platform.

But auto-translation suggestions aren't identified in statistics: https://translate.stg.fedoraproject.org/stats/

The bigger the platform will be, the more efficient the feature will be, and the more suggestions will be submitted by the machine.

shouldn't these auto-translation contribution be identified by a dedicated user?

**Comment by nijel** [comment]
It should be, see https://github.com/WeblateOrg/weblate/issues/3009
