### ISSUE TITLE
Automatic translation not working (endless requests)

### ISSUE THREAD

**Issue by goraccio** [WeblateOrg/weblate#3375]
**Describe the bug**
When you try to use automatic translation for any language on any amount of lines with the help of machine translation (tried weblate, weblate translation memory, google translation) you see the progression bar and nothing happens except xhr requests for "weblate/js/task" that always return {"completed": false, "progress": 0, "result": null}. Also no requests goes to google, when you try to use automatic translation. Google defenitly works, because when you try use machine translation in each line - it show results from google translation

**To Reproduce**
1. Go to any language in project
2. Click on tools > automatic translation
3. select any settings and "Automatic translation source" to "Machine translation"
4. Click "Apply" and see endless progress bar. 

**Expected behavior**
Automatic translation should work

**Server configuration and status**
list_versions:
 * Weblate: 3.10.1
 * Django: 3.0.2
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.4.0
 * lxml: 4.3.2
 * Pillow: 7.0.0
 * bleach: 3.1.0
 * six: 1.13.0
 * python-dateutil: 2.8.1
 * social-auth-core: 3.2.0
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.8.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.3
 * user-agents: 2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.1
 * celery: 4.4.0
 * kombu: 4.6.7
 * celery-batches: 0.2
 * translation-finder: 1.7
 * html2text: 2019.9.26
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.22.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.0
 * Cython: 0.29.14
 * misaka: 2.1.1
 * GitPython: 3.0.5
 * borgbackup: 1.1.10
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.7.7
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.5
 * tesserocr: 2.5.0
 * akismet: 1.0.1
 * boto3: 1.10.50
 * zeep: 3.4.0
 * aeidon: 1.6.0
 * Mercurial: 4.8.2
 * git-svn: 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: 127.0.0.1
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.15.0-72-generic (x86_64)

check --deploy:
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Can not send email ([Errno 111] Connection refused), please check EMAIL_* settings.
	HINT: https://docs.weblate.org/en/weblate-3.10.1/admin/install.html#out-mail

ERRORS:
?: (weblate.E016) Configure cached template loader for better performance
	HINT: https://docs.weblate.org/en/weblate-3.10.1/admin/install.html#production-templates

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.
?: (security.W022) You have not set the SECURE_REFERRER_POLICY setting. Without this, your site will not send a Referrer-Policy header. You should consider enabling this header to protect user privacy.

INFOS:
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.10.1/admin/backup.html

System check identified 8 issues (1 silenced).

**Comment by nijel** [comment]
Using Docker? If so please update, it has been fixed in https://github.com/WeblateOrg/docker/commit/a4b74a3f038055a2a8dc0add42d35c7fc23d64ff

In case you manually installed, please check celery worker configuration to execute the translate queue, also see https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-3-9-to-3-10

**Comment by goraccio** [comment]
Thank you for fast answer. I'm using docker-compose and it seems it doesn't have that fix

**Comment by nijel** [comment]
Just update the images by `docker-compose pull`. The fix is part of both `latest` and `edge` tags.

**Comment by goraccio** [comment]
> Just update the images by `docker-compose pull`. The fix is part of both `latest` and `edge` tags.

Thank you for your help, now everything is working like a charm
