### ISSUE TITLE
Weblate UI need to edit PO header

### ISSUE THREAD

**Issue by fujiwarat** [WeblateOrg/weblate#3376]
**Is your feature request related to a problem? Please describe.**
Whenever I get the pull request in GitHub from Weblate, I need to check the PO header is right.

E.g. If the current PO file inlcludes:
```
# Japanese translation of ibus.
# Copyright (C) 2015-2019 Takao Fujiwara <takao.fujiwara1@gmail.com>
# This file is distributed under the same license as the ibus package.
#
# Translators:
# Takao Fujiwara <takao.fujiwara1@gmail.com>, 2012
```
Problem 1. Weblate deletes the null line:
```
# Japanese translation of ibus.
# Copyright (C) 2015-2019 Takao Fujiwara <takao.fujiwara1@gmail.com>
# This file is distributed under the same license as the ibus package.
# Translators:
# Takao Fujiwara <takao.fujiwara1@gmail.com>, 2012
```

I don't expect to delete the null line `#` so I revert the Weblate change forcibly.

Problem 2. Weblate keeps the copyright header "# Copyright (C) 2015-2019 Takao Fujiwara" but I expect the pull request changes the copyright header to "# Copyright (C) 2015-2020 Takao Fujiwara" with the current year so I modify the pull request forcibly.
I don't want to separate the commits of PO files. One commit could update translations and copyright header.

E.g. if the POT file includes:
```
# Source translation of ibus.
# Copyright (C) 2015-2019 Takao Fujiwara <takao.fujiwara1@gmail.com>
# This file is distributed under the same license as the ibus package.
#
```

When a Weblate user tries to add a language, Weblate copy the POT file to a PO file with the language and creates a pull request.

Problem 3. I don't want any pull requests if the PO does not include any translations and I'd consolidate the pull request of adding a PO file and the update translations.
So even if I receive some pull requests of some new languages, I ignore the pull requests if any translations are not added and I consolidate the two pull requests of adding a PO file and updating translations of the PO file to one pull request by language
.
Problem 4. Weblate copy the header of POT file but I update "# Source translation of ibus." to "# Japanese translation of ibus." in the pull request in case the copied PO file is ja.po and I also update "# Copyright (C) 2015-2019 Takao Fujiwara" to "# Copyright (C) 2015-2020 Takao Fujiwara" in the pull request. Of course I revert the null lines of "#" in the pull requests.

After I consolidate my modifications and pull requests from Weblate, I commit a patch by language.
And go to Weblate GUI "Manage" -> "Commit" and click "Reset" button and Weblate pull the consolidated changes of my changes and the original pull requests. One commit could include adding a PO, modifying the header and updating thet translation by language.

**Describe the solution you'd like**
If users could push a PO file with the updated PO header into Weblate or Weblate GUI provides the editor of PO headers and Weblate could merge the header modification and translation updates to one commit by language, it could resolve my problems.

**Describe alternatives you've considered**
I use the "Reset" button.

**Additional context**

**Comment by fujiwarat** [comment]
I forgot problem 5.

When I received a pull request from Weblate, I add the pull request ID in the commit log with "BUG=".

E.g.
```
Author: Takao Fujiwara <takao.fujiwara1@gmail.com>
Date:   Mon Jan 6 20:26:44 2020 +0900

    Translated using Weblate (Ukrainian)
    
    Currently translated at 100.0% (544 of 544 strings)
    
    Translation: ibus/ibus
    Translate-URL: https://translate.stg.fedoraproject.org/projects/ibus/ibus/uk/
    BUG=https://github.com/ibus/ibus/pull/2169
```

**Comment by nijel** [comment]
I don't see good use for free form header editing. In case you're using usual list of authors in PO file header, you can update that using the [Contributors in comments](https://docs.weblate.org/en/latest/admin/addons.html#contributors-in-comment) add-on.

The copyright comment is not updated by this add-on as that's not something what could be done automatically. Actually the way you are expecting it is wrong - the contributions are copyrighted by appropriate authors unless they have signed some kind of contributor agreement with you which would transfer the copyright, what doesn't seem to be the case for ibus.

**Comment by fujiwarat** [comment]
I think this issue is a kind of the introduction how I use Weblate and why I need to modify the patches from Weblate.

Seems the Contributors in comments add-on would not be useful for me unless it could revert the null comments (#). 
Actually I don't think translator contributors could update the copyright but myself want and I won't accept Weblate pull requests unless I modify the patches.
I think it might be good to have two kinds of the editors of PO files in Weblate. One is for translators and another is for the package owners and it would be great if Weblate could squash the commits.

Since there are several problems as I listed up, I just wish "Reset" button continue to work in Weblate so that I can override the Weblate git with upstream git.
It would be great if some of the RFEs could be enhanced by new add-ons or updated UIs.

**Comment by nijel** [comment]
Weblate [can squash Git commits](https://docs.weblate.org/en/latest/admin/addons.html#squash-git-commits.

**Comment by nijel** [comment]
The empty line removal should be addressed by https://github.com/translate/translate/pull/3936

If some other issue persists, please open separate issue, so that it's easier to track individual problems.
