### ISSUE TITLE
Yandex Cloud Translate API

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3378]
This is more of a "for your information" post.

I recently noticed that machine translation by YT given through API in Weblate and on [YT's web-interface](https://translate.yandex.com) differ, sometimes significantly and the one given via web-interface is better.

So I wrote to tech support and they confirmed that indeed, they differ because translation given through web-interface is done used "neuro translation + statistical phrasal translation" and that given via API just "statistical phrasal translation".
To get the same translation as on web-interface via API you have to use paid version of YT's API on Yandex.Cloud platform. More info can be found here:
https://cloud.yandex.com/services/translate

Here is the original answer in Russian:
> Да, вы правы, есть различие в переводах на сервисе и через API. Оно существует потому, что на сервисе используется гибридный перевод (нейроперевод + статистический фразовый), а в API — только статистический фразовый.
> В платной версии API Яндекс.Переводчика на платформе Яндекс.Облако используется такой же перевод, как и на сервисе. Подробнее об этом можно почитать тут: https://cloud.yandex.ru/services/translate

**Comment by nijel** [comment]
Adding support for their another service is certainly possible. Actually, many of the machine translation services we support require payment.

**Comment by nijel** [comment]
It should replace the existing implementation as the existing service is now dead:

> We no longer issue free keys for the Yandex.Translate API. For all existing free keys, there will be a limit of 50,000 symbols as of July 31st and these keys will stop working on August 15th.

**Comment by nijel** [comment]
...or actually should not. The paid version of the old API stays available.

**Comment by kykint** [comment]
Actually the old API is finally dead. There is the new (v2) API: https://cloud.yandex.com/en-ru/docs/translate/api-ref/Translation/translate
It would be very great if it is possible to add support of it instead of old one.
