### ISSUE TITLE
searching for strings in specific languages query 

### ISSUE THREAD

**Issue by andrei-stoian** [WeblateOrg/weblate#3385]
**Describe the bug**
Using Weblate 3.10.1
I am trying to search for strings in just a number of the available languages translated. eg. Output AND language:en,ja, but it returns string not found. 

**To Reproduce**
1. Go to 'Search'
2. input "output AND language:en,ja"

**Expected behavior**
Should be able to see only the strings containing "output" for en and ja files, except all other langages.

**Additional context**
I have noticed that with the latest update, the "exact match" option is gone from the Search function, when using quotes for a one line string, it will display all strings where that word is used, opposed to only the strings where the word is alone.

**Comment by ionmincu** [comment]
Also `lanaguage:r".*"` dose not seem to produce any results.

**Comment by nijel** [comment]
What should work is: `output AND ( language:en OR language:ja )`

I don't think that it parses the values, so it looks for language code "en,ja" which does not exist.

**Comment by nijel** [comment]
The regex lookup is indeed broken here, I will fix that.
