### ISSUE TITLE
SINGLE_PROJECT setting

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3388]
Sorry to ask, but [documentation](https://docs.weblate.org/en/weblate-3.10/admin/config.html#single-project) doesn't elaborate much on it. I wonder how does the `SINGLE_PROJECT` setting work. I tried `SINGLE_PROJECT = True` and `SINGLE_PROJECT = 'project-name'` but the dashboard is still shown. Or for this setting to work there should be only one project in Weblate?

**Comment by nijel** [comment]
Yes, this setting works only in case there is actually one project and it changes dashboard view in that case.
