### ISSUE TITLE
i18next format not take in account interpolation and HTML key words

### ISSUE THREAD

**Issue by Heziode** [WeblateOrg/weblate#3389]
**Describe the bug**

The current implement of i18next file format support does not take in acconut interpolation variables and HTML tag.

According to the [i18next doc](https://www.i18next.com/translation-function/interpolation#all-interpolation-options), a string can contains interpolation key with `{{myInterpolation, number}}` and nested interpolation `$t("someKey", { option1: 42 })`.

**To Reproduce**

Have an i18next project imported into Weblate with some strings that contains interpolation variables like this:

```
Hello {{username}}, <b>you</b> are $t("compliment.awesome")!
```

Currently, we have:

![image](https://user-images.githubusercontent.com/16735076/72603631-b1500b00-3919-11ea-8a85-824b1b2908dc.png)

**Expected behavior**

Interpolation key and HTML tag shall be matched, like this (hand making, by modifying the HTML ^^):
![image](https://user-images.githubusercontent.com/16735076/72603321-17885e00-3919-11ea-98af-0a2320b73e37.png)

---

Found on **Weblate 3.9.1**.

**Comment by Heziode** [comment]
@nijel this seems to be more a [Translate Toolkit](https://github.com/translate/translate/issues) issue than an Weblate, isn'it ?

I have just take a look at you code, if I undestand well, the parsing is done by **Translate Toolkit** ?
*PS: I do not know Python programming language*

**Comment by nijel** [comment]
Currently, we handle placeholders independently in most cases. But having support for this in the translate-toolkit will allow us to use that.

**Comment by nijel** [comment]
For example in Web Extension JSON we use information parsed from the file:

https://github.com/WeblateOrg/weblate/blob/f1bba6a9890f70ede3bcbae72aa5eeb5c3567218/weblate/formats/ttkit.py#L642-L650

But we can have custom code dealing with this as well.

**Comment by Heziode** [comment]
@nijel,

How can I manage placeholders that contains comma ?
Example: `You clicked $t(value, { count: 2 })!`, here **$t(value, { count: 2 })** is a valid i18next placeholder.

I can't add it manualy (I get an error message).

**Comment by nijel** [comment]
That's currently not supported.

**Comment by nijel** [comment]
I've created separate issue for that: https://github.com/WeblateOrg/weblate/issues/3546

**Comment by Heziode** [comment]
@nijel,

Indeed, I think it should be a first step to the "complete" support of i18next.

**Comment by nijel** [comment]
That is not a requirement for that - it is limitation only for manually specified placeholders.
