### ISSUE TITLE
Choose a project to display instead of a dashboard

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3390]
**Is your feature request related to a problem? Please describe.**
Currently I have one main public project in Weblate used by translators and a couple of private ones, used for testing purposes by me.
Since there is only one project available for translators it would be good to disable the dashboard for them and directly show this main project as is done by by `SINGLE_PROJECT` setting. But this option works only if there is one project in Weblate, which is not true in this case.

**Describe the solution you'd like**
It would be nice to be able to have a setting to enable one project as if it's the only one in "Weblate", maybe something like `MAIN_PROJECT = 'project_name'`

**Comment by nijel** [comment]
You can partly already do this with component lists - create component list including all components from the project and let users choose this as a default view.

Setting main project (or let SINGLE_PROJECT accept project slug) is probably better in this case.
