### ISSUE TITLE
Upload without overwriting approved strings

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3392]
**Is your feature request related to a problem? Please describe.**
When uploading a file, all translations including approved are overwritten (given user has permissions to do that).

**Describe the solution you'd like**
Add an option to skip replacing approved strings.

**Describe alternatives you've considered**

**Additional context**
Maybe there would be more options how to handle upload instead of existing replace option:

* Update only non translated
* Update also translated
* Update also approved

**Comment by reloxx13** [comment]
heya, 

currently the import is bugged somehow:
- got a xlxs custom download/export.
- translated 5/5 strings in it.
- reupload says 4/5 not found.

will provide feedback if i got some time to investigate.
BR and have a nice day

**Comment by nijel** [comment]
Please open separate issue for that, thanks.
