### ISSUE TITLE
Reset ignored checks

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3396]
**Is your feature request related to a problem? Please describe.**
Sometimes it is desired to reset all the ignored checks either in a project or in a specific component. 

**Describe the solution you'd like**
It would be great to have a management command similar in syntax to [updatechecks](https://docs.weblate.org/en/latest/admin/management.html)

**Comment by nijel** [comment]
Can you please clarify use case for this?

**Comment by tariver** [comment]
> Can you please clarify use case for this?

A translator unresponsibly clicked "Dismiss" on all checks, I would like to undo this. 
Also sometimes an option to unignore and  review all the checks would be useful.
For these purposes it would be nice to be able to unignore all or some selected checks.

I understand that it can be accessed in Tools>Ignored checks menu, but bringing it to the main screen will be more visually representative.

**Comment by nijel** [comment]
Maybe we could display them greyed out and with less detail...
