### ISSUE TITLE
Unclickable links in e-mail about new components

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3401]
Webmail
![bilde](https://user-images.githubusercontent.com/13802408/72672335-b36cb380-3a58-11ea-864e-5f4d3449d31b.png)

Mailpile (non-HTML mode)
![bilde](https://user-images.githubusercontent.com/13802408/72672358-ee6ee700-3a58-11ea-9f79-077294922420.png)

Neomutt
![bilde](https://user-images.githubusercontent.com/13802408/72672372-1cecc200-3a59-11ea-9255-5a544b124271.png)
Links with linespans are also problematic here.

Solution
1: No HTML e-mails. I think hard spaces could maintain the formatting of the table.
2: Optional HTML or non-HTML in the settings.
3: Add clickable full one-liner links to HTML e-mails, preferably up top.

**Comment by nijel** [comment]
Currently, the plain text mail is rendered by [html2text](https://pypi.org/project/html2text/). There used to be dedicated templates for them, but after several issues with them I replaced them with automatically generated from HTML. Probably the conversion can be tweaked to be more useful.

**Comment by nijel** [comment]
The other problem is that [`<base href="">` doesn't work in most web based clients](https://stackoverflow.com/a/14726118).

**Comment by comradekingu** [comment]
@nijel This also happens with "new alert" and "parse error" e-mails.

![bilde](https://user-images.githubusercontent.com/13802408/112238204-10a35c80-8c3c-11eb-8038-1f127c7b3443.png)
