### ISSUE TITLE
Changing source language doesn't change source

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3406]
https://hosted.weblate.org/translate/turris/foris-js/en/?checksum=a8d33459c7e7cf4f
Clicking to edit this string "Settings saved successfully", from https://hosted.weblate.org/zen/turris/foris-js/nb_NO/?q=state:empty it was an empty input field.

So now it is "Settings saved", but just for "English", which seems to be a different English to the source, but the user isn't informed of this.

**Comment by nijel** [comment]
This is same situation as https://github.com/WeblateOrg/weblate/issues/3340, the English translation should be read only...

**Comment by comradekingu** [comment]
I don't know what happened in GASdottoNG, but in Zen Italian strings are shown as source, and when one clicks to edit, they are in English.
https://hosted.weblate.org/translate/gasdottong/translations/nb_NO/?checksum=d7dbd93f40b72cc0 https://hosted.weblate.org/translate/gasdottong/translations/en/?checksum=d7dbd93f40b72cc0

**Comment by nijel** [comment]
It seems that the project has [actually using Italian as source in the PO files](https://github.com/madbob/GASdottoNG/blob/master/code/resources/lang/i18n/de_DE/LC_MESSAGES/messages.po).

**Comment by nijel** [comment]
I've fixed the project configuration now.
