### ISSUE TITLE
100%+ and <100% of translated component

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3413]
![bilde](https://user-images.githubusercontent.com/13802408/72947635-f2fe0d00-3d82-11ea-9d4f-408b703a287e.png)

Translated 90% (214 of 236)
and 
Strings of total (214 of 2)

https://hosted.weblate.org/languages/nb_NO/tremotesf/#information says it has 1418 strings (when it really has 236)

**Comment by nijel** [comment]
The stats are now correct, maybe it was just some temporary glitch. The information tab is confusing though - it shows stats for whole project, while it should show the per language ones.
