### ISSUE TITLE
Create project in api missing source language

### ISSUE THREAD

**Issue by ilkarataev** [WeblateOrg/weblate#3416]
Hi i want to create project from component and i need to set up source_language.
I read the document and saw that i need only free field name,slug and web.
When i created project is saw weblate response for me that source_language en and checked it on the web interface.
I tryied to send "source_language" in the reqest i created project but had the same result.

```
curl -H 'Content-Type: application/json' -H "Authorization: Token ${api_token}" --data-binary "{\"name\":\"${job_name}\", \"slug\":\"${job_name}\",\"web\":\"https://exaple.com\","source_language\":{\"code\":\"ru\",\"name\":\"Russian\",\"direction\":\"ltr\",\"web_url\":\"http://weblate.exaple.com/languages/ru/\",\"url\":\"http://weblate.exaple.com/api/languages/ru/\"}}" https://weblate.exaple.com/api/projects/`
```

```
{
  "name": "master_locales",
  "slug": "master_locales",
  "web": "https://example.site",
  "source_language": {
    "code": "en",
    "name": "English",
    "direction": "ltr",
    "web_url": "http:/example.site/languages/en/",
    "url": "http://example.site/api/languages/en/"
  },
  "web_url": "http://example.site/projects/master_locales/",
  "url": "http://example.site/api/projects/master_locales/",
  "components_list_url": "http://example.site/api/projects/master_locales/components/",
  "repository_url": "http://example.site/api/projects/master_locales/repository/",
  "statistics_url": "http://example.site/api/projects/master_locales/statistics/",
  "changes_list_url": "http://example.site/api/projects/master_locales/changes/",
  "languages_url": "http://example.site/api/projects/master_locales/languages/"
}
```
One more problem when i creater component, the File_format: JSON nested structure file didn't install in the property.
In our workflow we need to use all api featuries.

**Comment by nijel** [comment]
Configuring source language is currently missing from the API.

I didn't get what was your problem with nested JSON, can you please open separate issue describing that? Mixing unrelated topics in single issue makes it hard to properly track then.

**Comment by ilkarataev** [comment]
about Configuring source language,will you fix it?
About json_nested it's my mistake it's working, sorry.

**Comment by nijel** [comment]
It will get eventually fixed, currently it's not on the roadmap.
