### ISSUE TITLE
Unspecified license tag icons

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3419]
![bilde](https://user-images.githubusercontent.com/13802408/73023464-e1247480-3e2b-11ea-9106-cb17d750c3fe.png)

Should be GPLv2+, GPLv3, AGPLv3+ GPLv3-only etc.
There is also a lot of difference between BSD variants. 2 clause. 3 clause etc.

**Comment by nijel** [comment]
The intention was to make this *short* indication of the license. We can't put full details here. We might a well just show OSI approved flag instead, but I thought this would be more useful.

**Comment by comradekingu** [comment]
@nijel It is more useful, but it has to be specific to be meaningful. I made a list of all the licenses in use on Hosted. (- signifies only).

Apache2.0

LGPLv2-
LGPLv2+
LGPLv2.1-
LGPLv2.1+

LGPLv3-
LGPLv3+

GPLv2-
GPLv2+
GPLv3-
GPLv3+

AGPLv2-
AGPLv2+
AGPLv3-
AGPLv3+

GFDLv1.3+

MPL2.0

BSD2c
BSD3c

ISC

MIT

Beerware

zlib

LaTeXv1.3c

CCZ1.0U
CCBY4.0I
CCBYSA4.0I
CCBYND4.0I
WTFPL
Unfree

It would be a lot easier to navigate the list on https://hosted.weblate.org/accounts/profile/#licenses with these shorter names too.

**Comment by nijel** [comment]
I don't feel like reinventing license naming. We currently rely on [SPDX](https://spdx.org/licenses/) for that. The simplified license currently is whatever is there up to fist dash:

https://github.com/WeblateOrg/weblate/blob/ef0508456ada99794e678f8b667ccdd0f5e6388e/weblate/trans/models/component.py#L2030-L2032

In other places, full license name is shown.

**Comment by comradekingu** [comment]
@nijel 
Dropping the dashes and replacing "or later" with plus and "only" with - doesn't reinvent the license name, whereas cutting the name short at the first dash does.

The + for "or later" is common practice, could even do "only" instead of minus, as not a whole lot of projects even use that.

The CC licenses have nothing meaninful in common, and there are a lot of differences between the numbers and designations of other licenses.
