### ISSUE TITLE
Distinguish component license differing from project license

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3420]
I think doing Project:license - component:license when they differ makes sense.

![](https://user-images.githubusercontent.com/13802408/54481867-ada3b180-483a-11e9-8b0e-85353d4bd507.png)

**Comment by nijel** [comment]
License can be defined for each component. We might be aggregating it for display somehow (we're already doing that in project view (which just got improved by 8b3dfd621c9779ef0ba4ab1724086b11383752be), the question is whether multiple licenses on line will make it easier to use than current approach.
