### ISSUE TITLE
 Error creating accounts

### ISSUE THREAD

**Issue by Pierre277** [WeblateOrg/weblate#3421]
When creating an account and filling in all the data you will see that even if you answer the math account correctly the site understands that the answer will always be incorrect.

1. Go to 'https://translate.beamng.com/'
2. Click on 'registry'
3. Fill in the data and answer the math account and click on "register" the website will reload and indicate that the math account will be incorrect "even if you answer it correctly". '
4. If the answer is incorrect, you will not create the account.

**Screenshots**

![Sem título 2](https://user-images.githubusercontent.com/60247638/73043170-cc071000-3e42-11ea-8ee0-8fcb86776445.png)
![error](https://user-images.githubusercontent.com/60247638/73043171-cc071000-3e42-11ea-9d66-d1e8c38e6ba1.png)
![Sem título](https://user-images.githubusercontent.com/60247638/73043173-cc071000-3e42-11ea-827c-e1c915b04080.png)
![2](https://user-images.githubusercontent.com/60247638/73043174-cc9fa680-3e42-11ea-8a9d-0611603ff580.png)

**Comment by nijel** [comment]
Is that your site?

I've just tried that and I've passed captcha on first attempt without any problems. Can you still reproduce it?

Not sure if that's related, but the static files on the site seem outdated. Check [upgrading instructions](https://docs.weblate.org/en/latest/admin/upgrade.html) or pull latest Docker image to fix that.
