### ISSUE TITLE
"Strings waiting for review" not working correctly

### ISSUE THREAD

**Issue by sowinski** [WeblateOrg/weblate#3423]
**Describe the bug**
"Strings waiting for review" not working correctly
Please find attached a few screenshots. I am using webalte 3.10

![weblate_2](https://user-images.githubusercontent.com/1528746/73055359-e7970880-3e8c-11ea-9c2b-b84afa4b7707.png)
![weblate_1](https://user-images.githubusercontent.com/1528746/73055360-e7970880-3e8c-11ea-9a32-490f7438292c.png)

On the first screenshot you can see "Strings waiting for review - 36 Words" but after clicking on that "link" I get 279 strings to review?

I guess this is a bug?

Thank you

**Comment by comradekingu** [comment]
@sowinski
Post a link :)
Possibly related to #3413
