### ISSUE TITLE
Error on Automated translations

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#3424]
When "navigating" from one string to an other I receive a lot for errors linked to Automated translations ... the number of "Red error lines" is random, see screen shot on OmsAnd project / French translation.

Error on Automated translations
![Error When on Automated Translation](https://user-images.githubusercontent.com/1452146/73078987-ae2dbf80-3ec3-11ea-9ab5-1e23fb79a439.jpg)

**Comment by ldmpub** [comment]
It looks like the number of errors raised is directly linked to the speed of the string navigation change: the more you wait before your go to next string the less errors you get.

**Comment by nijel** [comment]
Such errors should be indeed ignored if the request was terminated because user navigated away.

**Comment by ldmpub** [comment]
Thanks for this fix ... it will improve (my) user experience ;-).
