### ISSUE TITLE
Select specific languages that may be translated by user on access page

### ISSUE THREAD

**Issue by Kyuuu** [WeblateOrg/weblate#3426]
**Is your feature request related to a problem? Please describe.**
Users' management by /admin page is pretty confusing. There are too many groups and too many default groups I can't delete and I am just lost in all these things (would be easier if there will be 4 default groups - administrators, translators, users and guests and you can add more only if you want to). However, cause of this issue, I decided to start giving permissions by /access/project-name page. But I miss one option that seems to be really must-have. It would be great to select a language or languages the translator can edit. There was a situation that one guy who translated language X knows also language Y translated by another guy. He started to change Y language cause he thought he knows better and did it voluntarily. It would be great to select languages that can be translated by a specific user on /access/project-name page. Or you may put in order group management and make it easier and cleaner - but it can probably take a while.

**Describe the solution you'd like**
Possibility to select languages that may be translated by a specific user on /access/project-name page (with option "All" of course).

**Describe alternatives you've considered**
//

**Additional context**
Something like that:
![image](https://user-images.githubusercontent.com/33127074/73124145-3087b380-3f98-11ea-9c4f-8b25b720c563.png)

**Comment by comradekingu** [comment]
> There was a situation that one guy who translated language X knows also language Y translated by another guy. He started to change Y language cause he thought he knows better and did it voluntarily
Good or bad? Restricting projects to users on a general basis does not work (Transifex), and being open to edits does (Wikipedia, Weblate). Review status not shared between all, and multi-level selection of quality. (Now there is only the binary "needs work", would do better IMO.
What is the actual issue? Can you screenshot the confusing UI?

Something like editing source strings could be restricted to only some users, but then again one should always be able to make suggestions. Suggestions should be easier to implement.

**Comment by nijel** [comment]
Technically it's possible to define per language groups and assign users, but this currently can be done only in the admin interface, not in the app directly. We want to make this option available in the app easily as well, it's just not a priority for now.

**Comment by derkoe** [comment]
We would also like this implemented - additionally I would suggest:
- The languages in the list should only include the languages used in the current project
- The current translators should still have the role Translate with the "All" option after the new feature is introduced

**Comment by nijel** [comment]
What, I think, makes more sense is to allow defining custom groups (maybe call that teams), and allowing them access to individual languages. This will be easier to manage in larger scale than setting individual permissions to every user.
