### ISSUE TITLE
User may translate all components except master one

### ISSUE THREAD

**Issue by Kyuuu** [WeblateOrg/weblate#3427]
**Describe the bug**
If I add permissions for a user on the access page - these permissions work on all components except master one.

**To Reproduce**
1. Open project ( /projects/project-name ) with a few components that are linked to another one.
2. Click on 'Manage' and select 'User'
3. Add normal, new user (without any rights except default ones)
4. Add "Glossary" and "Translate" permissions
![image](https://user-images.githubusercontent.com/33127074/73125957-2d4af280-3fad-11ea-92c0-a1e423881eb9.png)
5. Try to translate by this user account anything in linked components and in the master one.
6. See results
![image](https://user-images.githubusercontent.com/33127074/73125998-9c284b80-3fad-11ea-9631-ff378fb20bf1.png)

**Expected behavior**
//

**Screenshots**
//

**Server configuration and status**
//

On Git checkout:
//

**Additional context**
Tested on 2 git projects with PO files.

**Comment by comradekingu** [comment]
You want the created user to be able to translate everything or no?

**Comment by Kyuuu** [comment]
The issue here is a bug. I selected user access to the project and it works for all components except the first (not linked) one.

Please check the steps above.

**Comment by nijel** [comment]
Maybe it's locked down for some other reasons? Review process? Locked? What kind of error does the user get?

**Comment by Kyuuu** [comment]
@nijel there is no error. The user is not able to translate this component and sees only the "suggest" option.

The component is not locked. It has exactly the same settings as others.

I tested it on two projects - just check it by steps I wrote.

**Comment by nijel** [comment]
I've just tried to recreate it and I failed, the user has access to all components in this case.

Maybe you have suggestion voting enabled?

**Comment by Kyuuu** [comment]
@nijel wow, right! That was a problem!

If I enabled suggestion voting on the component - people with translation access on project/access page have no permissions for translating this component anymore.

Without voting - translation work for them.

Thank you for help. I got a bit misguided.
