### ISSUE TITLE
Status widget for a specific commit

### ISSUE THREAD

**Issue by rixx** [WeblateOrg/weblate#3438]
I'm a big fan of the status widgets – but I'd love to be able to refer to the translation status in a specific commit, instead of just the current one. My project uses weblate, and occasionally I will release a new version – I'd like to offer a language selection screen that shows the actual translation coverage, but that would have to be stable for the specific release.

So ideally, I'd like a URL scheme where I could drop in a git reference (a tag, a commit hash, a branch), with the default remaining the main branch of the component or project.

I'm not sure how feasible this suggestion is (does weblate retain the translation percentage at past commits?)

Do you know of another way to approach this? For example, can I hack weblate into adding the current translation percentage to a file on commit, instead of just the commit message?

**Comment by nijel** [comment]
No, we don't store past data. Also the translation status is not really bound to commit, but rather a time - given upstream commit, there can be lot of (not yet commited) changes in Weblate, which already account as translated.

See https://hosted.weblate.org/widgets/weblate/?lang=&component=master for example what can be configured as widget params.
