### ISSUE TITLE
problems with creating components via api

### ISSUE THREAD

**Issue by jzahradn** [WeblateOrg/weblate#3441]
Hi,
I don't know whether it is an issue or I am just doing something wrong.

All I need is to copy components via api from Python IDE, using POST method described here:
https://docs.weblate.org/en/latest/api.html#post--api-projects-(string-project)-components-
The text says:
POST /api/projects/(string:project)/components/
Creates translation components in the given project.
Parameters:	
project (string) – Project URL slug

Steps to reproduce:
1. I run 'requests.get' on this url: 'https://translate.mydomain.cz/api/projects/tests/components/'
2. I extract a json object that contains information about four components in the project Tests: [{copmonent1},{component2},{component3},{component4}] 
3. I replace keys: name, slug and branch with unique values. I do not touch the rest keys. I save the result to variable data that is list of dictionaries
4. I run requests.post(url, data=json.dumps(data), headers=head).

I am unable to insert list of components, because Fiddler Web Debugger says:
{"non_field_errors":["Invalid data. Expected a dictionary, but got list."]}

5. OK, so I have tried to insert only one component in a dict:

data = {'name':'TestJava_v2','slug':'testjava_v2','vcs':'git','repo':'git@git.mydomain.cz:EMB/test-vocab.git','git_export':'http://translate.mydomain.cz/git/tests/testjava/','branch':'develop_v2','filemask':'bundle_*.properties','template':'bundle.properties','new_base':'bundle.properties','file_format':'properties','license':'','license_url':None,'web_url':'http://translate.mydomain.cz/projects/tests/testjava/','url':'https://translate.mydomain.cz/api/components/tests/testjava/','repository_url':'https://translate.mydomain.cz/api/components/tests/testjava/repository/','translations_url':'https://translate.mydomain.cz/api/components/tests/testjava/translations/','statistics_url':'https://translate.mydomain.cz/api/components/tests/testjava/statistics/','lock_url':'https://translate.mydomain.cz/api/components/tests/testjava/lock/','changes_list_url':'https://translate.mydomain.cz/api/components/tests/testjava/changes/','new_lang':'add'}

>requests.post(url, data=json.dumps(data), headers=head)
><Response [201]>

However, Fiddler Web Debugger claims the real posted data was:

{"name":"TestJava_v2","slug":"testjava_v2","project":{"name":"Tests","slug":"tests","web":"http://tests.mydomain.cz","source_language":{"code":"en","name":"English","direction":"ltr","web_url":"http://translate.mydomain.cz/languages/en/","url":"https://translate.mydomain.cz/api/languages/en/"},"web_url":"http://translate.mydomain.cz/projects/tests/","url":"https://translate.mydomain.cz/api/projects/tests/","components_list_url":"https://translate.mydomain.cz/api/projects/tests/components/","repository_url":"https://translate.mydomain.cz/api/projects/tests/repository/","statistics_url":"https://translate.mydomain.cz/api/projects/tests/statistics/","changes_list_url":"https://translate.mydomain.cz/api/projects/tests/changes/","languages_url":"https://translate.mydomain.cz/api/projects/tests/languages/"},"vcs":"git","repo":"git@git.mydomain.cz:EMB/test-vocab.git","git_export":"http://translate.mydomain.cz/git/tests/testjava_v2/","branch":"develop_v2","filemask":"bundle_*.properties","template":"bundle.properties","new_base":"bundle.properties","file_format":"properties","license":"","license_url":null,"web_url":"http://translate.mydomain.cz/projects/tests/testjava_v2/","url":"https://translate.mydomain.cz/api/components/tests/testjava_v2/","repository_url":"https://translate.mydomain.cz/api/components/tests/testjava_v2/repository/","translations_url":"https://translate.mydomain.cz/api/components/tests/testjava_v2/translations/","statistics_url":"https://translate.mydomain.cz/api/components/tests/testjava_v2/statistics/","lock_url":"https://translate.mydomain.cz/api/components/tests/testjava_v2/lock/","changes_list_url":"https://translate.mydomain.cz/api/components/tests/testjava_v2/changes/","new_lang":"add"}

This component's structure is different from component's structure I received via requests.get (step 1) and from structure I have posted in the command (step 5)!

The new component was created in GUI after executing the command. But it is bad, with error: The server had serious problems serving your request. Trained monkeys are en-route fixing the issue.

My Questions:
1. Is it possible to bulk insert hundreds of components in one command? How if I cannot use the list?
2. Why I am getting the server error on component's url after executing the post command? Is it because the inserted json structure was changed? Why it was changed?
3. Can I easily delete from GUI defected components that was created by the post command? When I try this url: https://translate.mydomain.cz/projects/tests/testjava_v2/#delete I am still getting the error

Thank you
Regards
Jan

**Comment by nijel** [comment]
Try removing "project" from the request, it's taken from the URL and maybe it can't be parsed properly.

**Comment by jzahradn** [comment]
1. What project from the request do you mean? There is no project in variable data = {'...'} that I use for POST command
When I execute GET command on https://translate.mydomain.cz/api/projects/tests/components/ the project TestJava_v2 is displayed correctly but it is still inaccessible from GUI.

API:
{
"name":"TestJava_v2",
"slug":"testjava_v2",
"vcs":"git",
"repo":"git@git.mydomain.cz:EMB/test-vocab.git",
"git_export":"http://translate.mydomain.cz/git/tests/testjava_v2/",
"branch":"develop_v2",
"filemask":"bundle_*.properties",
"template":"bundle.properties",
"new_base":"bundle.properties",
"file_format":"properties",
"license":"",
"license_url":null,
"web_url":"http://translate.mydomain.cz/projects/tests/testjava_v2/",
"url":"https://translate.mydomain.cz/api/components/tests/testjava_v2/",
"repository_url":"https://translate.mydomain.cz/api/components/tests/testjava_v2/repository/",
"translations_url":"https://translate.mydomain.cz/api/components/tests/testjava_v2/translations/",
"statistics_url":"https://translate.mydomain.cz/api/components/tests/testjava_v2/statistics/",
"lock_url":"https://translate.mydomain.cz/api/components/tests/testjava_v2/lock/",
"changes_list_url":"https://translate.mydomain.cz/api/components/tests/testjava_v2/changes/",
"new_lang":"add"
}

GUI:
Server Error. The server had serious problems serving your request. Trained monkeys are en-route fixing the issue.


2. I am unable to delete a component from Weblate using the guide: DELETE /api/components/(string:project)/(string:component)

Auth token is good, it can be verified using GET command:
C:\WINDOWS\system32>curl -i -L -k -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization:token Changed5O9N699upsEvEu8MV6ZxYCCBdQZvQ4wh7a" -X GET https://translate.mydomain.cz/api/projects/tests/components/
OK - a long json is returned

The project name and component are correct, however:
C:\WINDOWS\system32>curl -i -L -k -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization:token Changed5O9N699upsEvEu8MV6ZxYCCBdQZvQ4wh7a" -X DELETE https://translate.mydomain.cz/api/components/tests/TestJava_v2/
{"detail":"Not found."}

How can I delete it? The project details is displayed above in this comment


3. I swear I saw a button like "copy component" in component's details last week. But not today. Today, there is nothing like that in the main menu: Translations, Info, Search, Glossaries, Insights, Files, Tools, Manage, Share
I don't know why. Do you know why? How can I manually copy a component?

Thank you
Regards
Jan

**Comment by jzahradn** [comment]
Regarding the delete (point 2 in my previous post), I was able to delete the component, its name in the curl command must be in lowercase (even if in Weblate contains both lowercase and uppercase letters). I would like to copy component manually from GUI, then take a look at its parameters in json, then compare parameters of both components (source component and newly copied component) in json. Finally, based on that, compose own component's json to post via API. But I still don't see the 'copy component' option in Weblate's Gui.

**Comment by nijel** [comment]
>  Server Error. The server had serious problems serving your request. Trained monkeys are en-route fixing the issue.

Can you please check server logs for the actual error?

> Regarding the delete (point 2 in my previous post), I was able to delete the component, its name in the curl command must be in lowercase (even if in Weblate contains both lowercase and uppercase letters).

Yes, you have to use slug in the API URLs.

> How can I manually copy a component?

You can choose existing component when creating new one, either to choose different filename or branch.

**Comment by jzahradn** [comment]
Now I am able to create a component via api. The reason I was not able to do it before is because there are more json keys that needs to be unique within existing components when executing the POST command. I said in my first comment in this ticket description: "I replace keys: name, slug and branch with unique values. I do not touch the rest keys. I save the result to variable data that is list of dictionaries".
This is the mistake. If only these three keys are renamed, the component will be created with errors. It is necessary to rename also at least *url* keys.
Wa can close this ticket, thank you
