### ISSUE TITLE
Search / filter for strings with status "waiting for review" does not work anymore due to pre-filled keyword typo in search query

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#3445]
**Describe the bug**
When navigating to a translation component > language as an example given, the string status are shown as following:

![image](https://user-images.githubusercontent.com/8058166/73736819-bc8c9e80-4741-11ea-9b49-d620ccf378d5.png)

When clicking now on *Strings waiting for reveiw* it is expected that it shows the 19 strings only as it was in previous version of weblate. But unfortunately it does not filter and shows all strings:

![image](https://user-images.githubusercontent.com/8058166/73736944-f78ed200-4741-11ea-8007-04611376b6b9.png)

When clicking now on the "strings waiting for review" drop down in aboves view, the actual search query is revealed:

![image](https://user-images.githubusercontent.com/8058166/73737153-5ce2c300-4742-11ea-8674-9e79f419c0cd.png)

Appearingly the query has a typo. When changing now "state:trans`al`ted" to "state:trans`la`ted" manually, the query works and the view is reduced to the 19 elements, as expected.

**Server configuration and status**

Weblate version 3.10.3-1 from hub.docker.com (weblate/weblate:3.10.3-1)

**Comment by rhofer** [comment]
@nijel is this related to https://github.com/WeblateOrg/weblate/pull/1829 ?

**Comment by rhofer** [comment]
I guess I found it in https://github.com/WeblateOrg/weblate/commit/bbb3ffe485cb2029f1854db1c108ba415e9a35fc 

@nijel if this resolves this issue we can close it.

**Comment by rhofer** [comment]
Duplicate of #3423 . Hence, closing.

**Comment by nijel** [comment]
Yes, that's it.
