### ISSUE TITLE
Baidu translates to Slovenian instead of Slovak

### ISSUE THREAD

**Issue by andrewshadura** [WeblateOrg/weblate#3450]
**Describe the bug**
![image](https://user-images.githubusercontent.com/309253/73943675-724a1f80-48f1-11ea-9cca-38b2f1af8060.png)

‘nuff said.

**To Reproduce**
1. Enable machine translation
2. Translate to Slovak
3. Observe Baidu being the only translation service to erroneously suggest Slovenian translations

**Expected behavior**
Either no translation to Slovenian from Baidu or translation to Slovak.

**Comment by nijel** [comment]
Hmm, they use "slo" language code, but the label for it seems to be Slovenian...
