### ISSUE TITLE
Active Directory LDAP Authentication doesn't work properly

### ISSUE THREAD

**Issue by bbolyasov** [WeblateOrg/weblate#3452]
**Describe the bug**

**To Reproduce**
1. Go to 'docker-compose.override.yml'
2. Add lines 
' WEBLATE_AUTH_LDAP_BIND_DN: CN=ldap,CN=Users,DC=example,DC=com
  WEBLATE_AUTH_LDAP_BIND_PASSWORD: password
  WEBLATE_AUTH_LDAP_SERVER_URI: ldap://ldap.example.org
  WEBLATE_AUTH_LDAP_USER_ATTR_MAP: full_name:name,email:mail
  WEBLATE_AUTH_LDAP_USER_SEARCH: **CN**=Weblate_Users,OU=Users,DC=example,DC=com
  WEBLATE_AUTH_LDAP_USER_SEARCH_FILTER: (sAMAccountName=%(user)s)'

**Expected behavior**
Users form group "Weblate_Users" can login to Weblate service

**Screenshots**
![image](https://user-images.githubusercontent.com/54394143/74026690-bf90c480-49b7-11ea-9c42-3fb8da15d412.png)

DEBUG search_s('CN=Weblate_Users,OU=Users,DC=example,DC=com', 2, '(sAMAccountName=%(user)s)') returned 0 objects:
weblate_1   | DEBUG Authentication failed for bbolyasov: failed to map the username to a DN.

**Server configuration and status**
 * Weblate: 3.10.3
 * Django: 3.0.2
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.0
 * lxml: 4.3.2
 * Pillow: 7.0.0
 * bleach: 3.1.0
 * six: 1.14.0
 * python-dateutil: 2.8.1
 * social-auth-core: 3.2.0
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.8.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.3
 * user-agents: 2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.1
 * celery: 4.4.0
 * kombu: 4.6.7
 * celery-batches: 0.2
 * translation-finder: 1.7
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.22.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.0
 * Cython: 0.29.14
 * misaka: 2.1.1
 * GitPython: 3.0.5
 * borgbackup: 1.1.10
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.7.7
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.5
 * tesserocr: 2.5.0
 * akismet: 1.0.1
 * boto3: 1.11.5
 * zeep: 3.4.0
 * aeidon: 1.6.0
 * Mercurial: 4.8.2
 * git-svn: 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: ******.com
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.3.0-28-generic (x86_64)

SystemCheckError: System check identified some issues:

ERRORS:
?: (weblate.E016) Configure cached template loader for better performance
        HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#production-templates

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/backup.html

**Comment by nijel** [comment]
Are you sure that `WEBLATE_AUTH_LDAP_USER_SEARCH` is correct? In `WEBLATE_AUTH_LDAP_BIND_DN` you have `CN=Users`, but in search you use `OU=Users`...

**Comment by bbolyasov** [comment]
Yes, I'm sure.  It's just example. I tried to mansion that if we use CN (Common Name) in  "WEBLATE_AUTH_LDAP_USER_SEARCH:" then users can't be pulled from specified group, only if I use OU instead of Group it gets work, but I have a lot of OU with users in my domain and don't want to give access to "weblate" for all of them.

If you need my real config:
      WEBLATE_AUTH_LDAP_BIND_DN: "CN=ldapguest,OU=Service Accounts,OU=Moscow,OU=EMEA,OU=ORG,DC=TOPCON,DC=com"
      WEBLATE_AUTH_LDAP_BIND_PASSWORD: *******
      WEBLATE_AUTH_LDAP_SERVER_URI: ldap://*********
      WEBLATE_AUTH_LDAP_USER_ATTR_MAP: full_name:name,email:mail
      WEBLATE_AUTH_LDAP_USER_SEARCH: CN=Weblate_Users,OU=Global Security Groups,OU=ORG,DC=TOPCON,DC=com
      WEBLATE_AUTH_LDAP_USER_SEARCH_FILTER: (sAMAccountName=%(user)s)'

**Comment by nijel** [comment]
The search returns no matches, so there is apparently something wrong there. You can try using `ldapsearch` from the command line to test the search parameters.

**Comment by bbolyasov** [comment]
Fixed by creating filter like
(&(memberOf=CN=Weblate_Users,OU=Global Security Groups,OU=ORG,DC=TOPCON,DC=com) (sAMAccountname=%(user)s))

**Comment by Egarone** [comment]
This post help me today!!!
thx a lot guys

**Comment by nijel** [comment]
Is this something to put into documentation? Contributions are welcome!

The documentation is here: https://github.com/WeblateOrg/weblate/blob/main/docs/admin/auth.rst#ldap-authentication
