### ISSUE TITLE
add Document Foundation identity provider

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#3455]
Hello,

the document foundation also have a SSO: https://wiki.documentfoundation.org/Infra/SingleSignOn
To show friendship of our communities, I would love to enable this provider it in our Weblate, the same way we have Fedora, Ubuntu and OpenSuse.

Thanks for your help

**Comment by nijel** [comment]
Unfortunately the wiki doesn't mention how to connect to it. Actually, the service might not be open to third party at all. Do you have some insights on that?

Anyway we need working Django integration to make it usable for Weblate. For most services we rely on [python-social-auth](https://github.com/python-social-auth/social-core/tree/master/social_core/backends.

**Comment by nijel** [comment]
They are using https://lemonldap-ng.org/, so it should be pretty easy to add support for it to python-social-auth. However, the authentication service doesn't seem to be open to third-party apps.

**Comment by Jibec** [comment]
Maybe the configuration could require an authentication key we would ask to the documentation foundation to be able to interact with their infra?

**Comment by fitojb** [comment]
cc @cloph

**Comment by nijel** [comment]
If somebody wants to implement this, starting at [python-social-auth](https://github.com/python-social-auth/social-core/tree/master/social_core/backends). is the way to go. Weblate can then use it directly.

But I find little value for Weblate as even them are not using it at https://translations.documentfoundation.org/.
