### ISSUE TITLE
Development server registration email doesn't work

### ISSUE THREAD

**Issue by Garfius** [WeblateOrg/weblate#3469]
Hello, i am evaluating weblate for a production environment, so i must chech multi-user capablities.

But i canno register any user other than admin user.

Email  system works, already checked ./weblate sendtestemail
And received: 'If you're reading this, it was successful.'

Also i can use the 'Report an issue with registration' option, and received:
Subject: [Weblate] Registration problems

But the register user button doesn't work, simply doesn't send emails.

Need a fix?

**Comment by Garfius** [comment]
Managed to do it using django interface

**Comment by nijel** [comment]
Probably they are sitting in a Celery queue. Check `./manage.py celery_queues` and your Celery configuration (maybe worker for notifications is not running?).

**Comment by Garfius** [comment]
It was the WSL listening ports binding. Works slightly different, 127.0.0.1 better not be used by apps.

Just changed to rabbitmq 0.0.0.0, now celery connects fine.

And ubuntu mail config, better use ssmtp package.
