### ISSUE TITLE
Is It possible to use Repository push URL parameter in POST command via API?

### ISSUE THREAD

**Issue by jzahradn** [WeblateOrg/weblate#3474]
Hi,

I need to create bulk components via API. I am able to do it, but parameter "Repository push URL" is always empty after creation and needs to be added manually.

Steps to reproduce:
1. cURL GET to some component: .../api/[project name]/[component name] > json is received
2. modify parameters in the json like name, branch, url, etc...
3. cURL POST the new json
4. check: [new component] > Settings > Version Control > Repository push URL is empty

After creation, parameter "Repository push URL" is empty. Obviously this is because the parameter is missing in the json posted by cURL.
I would like to add this parameter to the json before posting it.

My Question: Is it possible to create a component via API with this parameter? If yes, what is the name of the parameter in API?

Thank you
Best regards
Jan

**Comment by nijel** [comment]
Yes, it is possible since https://github.com/WeblateOrg/weblate/pull/3432. It will be part of the 3.11 release.
