### ISSUE TITLE
Cython is not a dependcy for python2. Breaks group roles editing

### ISSUE THREAD

**Issue by tsipizic** [WeblateOrg/weblate#3479]
**Describe the bug**
Cython is needed for Group roles editing page but it is not a dependency for python2 installations. If added manually throws error
TypeError: has_add_permission() takes exactly 3 arguments (2 given)

Running latest weblate 3.10.3 on Ubuntu 18.04 Python2.7

**Comment by nijel** [comment]
This is not related to Cython at all. This Python 2 crash was already fixed by 84d5cc019ee60f0b816574b4d4411d5b4b008e3e and will be part of upcoming 3.11 release.
