### ISSUE TITLE
weblate is unusable without javascript

### ISSUE THREAD

**Issue by alex-tee** [WeblateOrg/weblate#3482]
**Describe the bug**
Please make weblate usable without javascript, at least part of it for administration. Maybe it's too much effort for the translation stuff, but I don't see any logical reason why one would require javascript to do basic administration. 

The site used to be a bit more usable before with javascript turned off, but with the new design it seems that nothing at all works without javascript.

**To Reproduce**
1. Go to https://hosted.weblate.org/projects/zrythm/ using GNU IceCat
2. Click on "Insights"
3. Nothing happens

**Expected behavior**
My click does something.

**Screenshots**

**Server configuration and status**
Using hosted weblate

**Additional context**

**Comment by nijel** [comment]
The "Insights" is a menu which requires JavaScript. We don't have manpower to develop and maintain usability without JavaScript, sorry.
