### ISSUE TITLE
Adding safe-html flag not clearing suggestion to do so

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3483]
Clicked on localization guide. Saw safe-html not added, proceeded to do so yesterday.
https://hosted.weblate.org/guide/remmina/remmina
Still red triangle rather than green check-mark.

**Comment by nijel** [comment]
I don't see it being set:

![image](https://user-images.githubusercontent.com/212189/74605182-ea6cce00-50c5-11ea-8c94-46d5a93a2d7b.png)

**Comment by comradekingu** [comment]
![bilde](https://user-images.githubusercontent.com/13802408/74605598-d9be5700-50c9-11ea-9285-839c49a450cf.png)

I see it here (from the image posted). That should add "safe-html" to all strings(?)

**Comment by comradekingu** [comment]
Ah, I should have added it to the "Translation flags", not "Enforced checks"
