### ISSUE TITLE
Not possible to set string labels

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3485]
https://docs.weblate.org/en/latest/devel/translations.html#labels

https://hosted.weblate.org/translate/remmina/remmina/nb_NO/?q=check:same#

![bilde](https://user-images.githubusercontent.com/13802408/74605437-7122aa80-50c8-11ea-9ec3-2ec1e47026b9.png)

**Comment by nijel** [comment]
Labels are defined at project level, but it would deserve link here...
