### ISSUE TITLE
Missing documentation for adding a new project for novice users

### ISSUE THREAD

**Issue by HappyMiner** [WeblateOrg/weblate#3487]
**Describe the bugs**

1. Unable to use Weblate, since the documentation on how to create a new local translation  project (no GIT) with different languages is missing.
2. After blindly going through the different masks to create a new project, I finally manage to get to the "component update" screen, but nothing happens after that. In the console of the webserver I just see:

```
INFO test-manual/english-source: rebase remote into repo 20563c3bda67c23a421f42b03014f2146df1e3ae..20563c3bda67c23a421f42b03014f2146df1e3ae
[16/Feb/2020 13:02:28] "POST /create/component/zip/ HTTP/1.1" 302 0
[16/Feb/2020 13:02:28] "GET /progress/test-manual/english-source/ HTTP/1.1" 200 14484

[...] many more lines like the above.
```
The above seems to loop forever.

**To Reproduce**
1. I have created a test document in OpenOffice that contains some demo text, shapes and formatting (1 page and English only).
2. This .odt document was then converted to .xlf and finally to .po and .pot with the help of the [translate toolkit](http://docs.translatehouse.org/projects/translate-toolkit/en/latest/)
3. Since it is not quite clear what the use of GIT would be in this context and how to use it, I decided not go down the rabbit hole of configuring a separate local GIT server just to test Weblate. I found evidence in the documentation that [GIT was indeed not necessary](https://docs.weblate.org/en/latest/vcs.html) and that Weblate could manage this:
```
Weblate can also operate without a remote VCS. The initial translations are imported by uploading them. Later you can replace individual files by file upload, or add translation strings directly from Weblate (currently available only for monolingual translations).

In the background Weblate creates a Git repository for you and all changes are tracked in. In case you later decide to use a VCS to store the translations, you already have a repo within Weblate can base your integration on.
```
(The documentation does not explain what the differences or benefits are or how things work with this "repo within Weblate")
4. I then proceeded to manually upload my .pot.zip file and another .po file (it is not clear how they work and how they are supposed to be used here. Please see the screenshots in the .pdf on how I tried to use them.)
5. Attached screenshots show my entries to the system which are accepted (it took a lot of trial and error to finally get there, since nothing is really explained in the documentation!)
6. I finally get to the screen saying "Component is being updated...". This basically runs forever and nothing happens. What is this screen supposed to show?
7. In the console where I launched the webserver I can see that something happens in the background (see loop mentioned in "describe the bugs".

**Expected behavior**
Since a new user can't magically know what the different fields in the new project sections mean and what content exactly is required and in which format, more details are required for this part of the documentation. Alternatively the related fields could get some specific examples on what input is expected. What is the expected content of the .po and .pot files? Maybe I did something wrong there already, I have no way of knowing, since the documentation does not explain this at all.
The documentation should show at least one use case of exactly how one is supposed to create / configure a new translation.

**Screenshots**
Please find attached screenshots in the sequence until I reached the "Component is being updated..." screen plus the looping console output.

**Server configuration and status**
**`list_versions`**
```
theuser@TestDrive:~/weblate-env/bin$ ./weblate list_versions
System check identified some issues:

WARNINGS:
?: (weblate.W025.ass) Failure in loading handler for ass file format: aeidon or gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#optional-deps
?: (weblate.W025.php) Failure in loading handler for php file format: No module named 'phply'
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#optional-deps
?: (weblate.W025.srt) Failure in loading handler for srt file format: aeidon or gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#optional-deps
?: (weblate.W025.ssa) Failure in loading handler for ssa file format: aeidon or gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#optional-deps
?: (weblate.W025.sub) Failure in loading handler for sub file format: aeidon or gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#optional-deps
 * Weblate: 3.10.3
 * Django: 2.2.10
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.0
 * lxml: 4.5.0
 * Pillow: 7.0.0
 * bleach: 3.1.0
 * six: 1.14.0
 * python-dateutil: 2.8.1
 * social-auth-core: 3.2.0
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.8.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.3
 * user-agents: 2.0
 * filelock: 3.0.12
 * setuptools: 45.2.0
 * jellyfish: 0.7.2
 * openpyxl: 2.6.4
 * celery: 4.4.0
 * kombu: 4.6.7
 * celery-batches: 0.3
 * translation-finder: 1.7
 * html2text: 2020.1.16
 * pycairo: 1.19.0
 * pygobject: 3.34.0
 * diff-match-patch: 20181111
 * requests: 2.22.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.1
 * Cython: 0.29.14
 * misaka: 2.1.1
 * GitPython: 3.0.7
 * borgbackup: 1.1.10
 * Python: 3.5.2
 * Git: 2.7.4
 * psycopg2-binary: 2.8.4
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.15.0-76-generic (x86_64)
theuser@TestDrive:~/weblate-env/bin$ 

```

**`check --deploy`** 
```
theuser@TestDrive:~/weblate-env/bin$ ./weblate check --deploy
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.C030) The Celery beats scheduler is not executing periodic tasks in a timely manner.
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#celery
?: (weblate.E012) The server email has default value
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#production-email
?: (weblate.E013) The default from email has default value
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#production-email
?: (weblate.E014) The cookie secret key has default value
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#production-secret
?: (weblate.E017) Configure correct site domain
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#production-site
?: (weblate.E018) Failed to download avatar: <urlopen error _ssl.c:629: The handshake operation timed out>
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/optionals.html#avatars
?: (weblate.E019) The Celery does not process tasks or is too slow in processing them.
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#celery

ERRORS:
?: (weblate.E011) The site admins seem to be wrongly configured
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#production-admins
?: (weblate.E016) Configure cached template loader for better performance
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#production-templates

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.
?: (weblate.W025.ass) Failure in loading handler for ass file format: aeidon or gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#optional-deps
?: (weblate.W025.php) Failure in loading handler for php file format: No module named 'phply'
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#optional-deps
?: (weblate.W025.srt) Failure in loading handler for srt file format: aeidon or gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#optional-deps
?: (weblate.W025.ssa) Failure in loading handler for ssa file format: aeidon or gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#optional-deps
?: (weblate.W025.sub) Failure in loading handler for sub file format: aeidon or gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#optional-deps

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.10.3/admin/backup.html

System check identified 20 issues (1 silenced).
theuser@TestDrive:~/weblate-env/bin$
```

On Git checkout:
Not applicable.

Using docker-compose:
Not applicable.

**Additional context**
Not applicable.
[Weblate.pdf](https://github.com/WeblateOrg/weblate/files/4209804/Weblate.pdf)

**Comment by nijel** [comment]
Is Celery running on your installation? Can you please include output of `weblate check --deploy` and `weblate list_versions`?

**Comment by HappyMiner** [comment]
Updated the initial ticket with requested outputs. My mistake was to run them with `python check --deploy` instead of `./weblate check --deploy`. Missed that in the documentation. No idea why I have to use `./weblate` instead of just `weblate`...

**Comment by HappyMiner** [comment]
Ok, starting Celery got me further. Here the command I used in order to run this: `**(weblate-env) theuser@TestDrive:~/weblate-env/lib/python3.5/site-packages/weblate/examples$ ./celery start**
celery multi v4.4.0 (cliffs)
> Starting nodes...
	> search@TestDrive: OK
	> notify@TestDrive: OK
	> celery@TestDrive: OK
	> memory@TestDrive: OK
	> backup@TestDrive: OK
	> translate@TestDrive: OK
(weblate-env) theuser@TestDrive:~/weblate-env/lib/python3.5/site-packages/weblate/examples$`

But now one big problem remains: How do I actually start the translation of my English file? I could not find anything in the documentation, seems one has to be born with this knowledge?

I tried to "start a new translation", then added my target language and then got a file not found error. After I went back and tried to submit again, I was told that "the translation file already exists". Please see document attached.

Also all the languages I just added, show 100% complete. How can that be? What do I need to do next?

[weblate2.pdf](https://github.com/WeblateOrg/weblate/files/4211757/weblate2.pdf)

**Comment by nijel** [comment]
Can you please share the zip file you used for upload?

**Comment by HappyMiner** [comment]
Please find attached the .pot files I used. Original and zip in case something went wrong during zipping.
[Files.zip](https://github.com/WeblateOrg/weblate/files/4214267/Files.zip)

**Comment by nijel** [comment]
Hmm, I don't see any problem in there.

Looking again at your original PDF, I think I found problem - the path should be relative to the repository, so it should be only `testENGLISH.po`. There is probably bug in the validation that let it go.
