### ISSUE TITLE
Cannot delete language added with an emoji name

### ISSUE THREAD

**Issue by samhocevar** [WeblateOrg/weblate#3497]
**Describe the bug**
Someone added language “😃” to my project on hosted.weblate.org and the confirmation dialog is preventing me from deleting it. There may be encoding issues at stake.

**To Reproduce**
1. Go to https://hosted.weblate.org/projects/wincompose/master/%F0%9F%98%83/
2. Click on Manage → Removal
3. Type in “😃” (also tried with “%F0%9F%98%83”)
4. See error: “The translation name does not match the one marked for deletion!”

**Expected behavior**
I would like to delete the translation

**Comment by nijel** [comment]
I've just removed it without problem, copy paste from the text above the confirmation box...

**Comment by samhocevar** [comment]
Ah, I understand, thanks. I tried again and realised I had to type “wincompose/master/😃” instead of just “😃”. Sorry, this wasn’t obvious to me as I never used that specific feature.
