### ISSUE TITLE
Translating and priorizing Glossary

### ISSUE THREAD

**Issue by rvalle** [WeblateOrg/weblate#3503]
**Is your feature request related to a problem? Please describe.**

In our service there are some key terms for which we need translation consistency. We use the glossary for that. Think of the term "synchronise" for a service like dropbox, or the term "invite" for a service like facebook. You need consistent translations for that and the start and the glossary seems like a good tool.

Our current process is to invite "experts users" to weblate first, then follow up so that they translate the glossary first, so that it will help the rest of the contributors. (we export/import glossaries to help).

It frustrates us that there is no way to translate the glossary from the source language. You need to re-write the glossary from scratch and cannot use aid from machine translation.

It is also frustrating that some contributors will join and start translating before key terms in the glossary have been translated.

We also think that the Glossary is hidden on the right hand, contributors don't realize their existence if we don't alert them, or until they have gained a lot of experience.

**Describe the solution you'd like**

There should be an option to mark in project or components called "translate glossary first", and the glossary terms to be offered in the normal translation workflow as terms to start translation with. 

If the option is not selected empty glossaries should offer: do you want to translate from source language? 

It could also be possible to limit the glossary translation to distinguished terms that could be ticked in the source language's glossary as "key terms". 

To boost glossary usability, an alert should be made around the input field when a source string includes terms in the glossary. this could be implemented as an icon (!) include glossary terms. 

**Describe alternatives you've considered**

As an alternative we onboard contributors in parallel. Or course It could be possible to onboard users in an automated way.

**Comment by nijel** [comment]
Related to https://github.com/WeblateOrg/weblate/issues/243

**Comment by nijel** [comment]
Glossaries now will be standard components. You can adjust the component priority to list it first and you can use all Weblate features in that like machine translation.
