### ISSUE TITLE
Highlighting variables and tags in the target section

### ISSUE THREAD

**Issue by elMui** [WeblateOrg/weblate#3504]
Highlighting would be very helpful to see the strings which need translation at a glance 

![image](https://user-images.githubusercontent.com/61275914/74929983-f36ae180-53dc-11ea-9252-80603ff42da4.png)

**Comment by nijel** [comment]
That needs some rich editor, we currently use plain textarea. See also https://github.com/WeblateOrg/weblate/issues/1930
