### ISSUE TITLE
Clicking placeholder in Zen scrolls view to top of string

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3507]
If there are lots of secondary languages and the string is sufficiently long, and the resolution/scaling isn't there to cover it all, editing field focus is lost.

![bilde](https://user-images.githubusercontent.com/13802408/75032204-46f63180-54a8-11ea-9705-bef590c7b1cf.png)

https://hosted.weblate.org/translate/remmina/remmina/sv/?checksum=a40059ac9985ca75

Write up a whole string, click </big>, view skips, click </tt> view skips again.

**Comment by comradekingu** [comment]
@nijel 
This loss of editing field also happens (on 4.15) when just clicking the editing field, or clicking tab from the previous string.

The expected behaviour is to have the editing field visible at the bottom of the screen, and then lose out on the topmost alternative translations. (Instead of starting at the top alternative translation and then running out of screen-estate somewhere before the editing field is shown.)

**Comment by meel-hd** [comment]
Given #12981 has been merged, this issue is fixed now.
