### ISSUE TITLE
Wrong fill-rate for word completion bar

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3508]
![bilde](https://user-images.githubusercontent.com/13802408/75033395-19f74e00-54ab-11ea-9bf5-337266828453.png)
https://hosted.weblate.org/projects/remmina/remmina/sv/

I never understood which ones of the colours are subsets of others.
However the words "ord" bar only has yellow in it, when it should be almost full of something.

The 293 translated green ones would present more strings than that small green bit of strings "strenger" too I should think…?

**Comment by nijel** [comment]
The problem here is that number of source words is wrong. I already have fix for this ready in f8a0218e9051401126aba5d551e516b3be47e227
