### ISSUE TITLE
question about failing checks in api

### ISSUE THREAD

**Issue by jzahradn** [WeblateOrg/weblate#3509]
Hello,
in the API, I can find information about failing check:

{...
"failing_checks":3,
"failing_checks_words":6,
"failing_checks_percent":13.6,
...}

In the GUI, failing checks consists of yellow colored, blue colored and red colored warnings.

I would like to distinguish these levels in the API too. Is it possible to do this in API?

Thank you

Regards
Jan

**Comment by nijel** [comment]
The indication in GUI is gone for now and it's unclear whether it will be back, see https://github.com/WeblateOrg/weblate/issues/3265. Exposing this in stats is currently not planned, you better look for individual failing checks and determine severity in your case.
