### ISSUE TITLE
Ability to 'watch' a Component

### ISSUE THREAD

**Issue by smackattacka** [WeblateOrg/weblate#3510]
**Is your feature request related to a problem? Please describe.**
The ability to 'watch' at the component level would be beneficial in instances where there are several components within a project, in which the Weblate user is only interested in one or more specific components within that project.

**Describe the solution you'd like**
Add the ability to 'watch' a component, rather than only a project.

**Describe alternatives you've considered**
We have considering splitting each component into a separate project, but this is not our current internal standard.

**Additional context**
We have translators who are only responsible for certain components in Weblate, but they do not have the ability to only display these specific components in their custom Dashboard display.

**Comment by nijel** [comment]
It's already possible, though there is no direct UI for this.

1. Watch project
2. Go to the component, choose "Customize notifications for ..." from "Watching" menu
3. Configure notifications you want for given component
4. Unwatch project
