### ISSUE TITLE
Option to disable emails

### ISSUE THREAD

**Issue by majklovec** [WeblateOrg/weblate#3511]
**Is your feature request related to a problem? Please describe.**
When installed, checks stops application at start. Because EMAIL_* variables are not properly setup.

**Describe the solution you'd like**
`EMAIL_DISABLE=1` to disable emailing at all.

**Describe alternatives you've considered**
`EMAIL_HOST=''`

**Additional context**
Thanks a lot for the great piece of software, you rock!

Michal

**Comment by nijel** [comment]
Have you tried adding the failing check to `SILENCED_SYSTEM_CHECKS`?

**Comment by nijel** [comment]
I think that there is no need to have separate setting for this. Following should work:

```python
EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'
```

So the only missing thing is to document this and what consequences it has (for example no option to reset password).

**Comment by Akronae** [comment]
`SILENCED_SYSTEM_CHECKS` / `EMAIL_BACKEND` do not change anything.
We could not use Weblate as we do not want to bother with email for something as simple as locales..
