### ISSUE TITLE
Integrate Authentication with Slack

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#3512]
Integrate a oauth2 authentication via Slack, like with e.g. GitHub, Google and Facebook.
I think this would be a great addition.
The python component already exists.
https://dev.auth0.com/authenticate/python/slack/

**Comment by nijel** [comment]
It's already supported: https://python-social-auth.readthedocs.io/en/latest/backends/slack.html

I guess you want Docker integration for that ;-)

**Comment by ilocit** [comment]
You are of course right. Thanks!

Matthias Caesar
iLocIT

________________________________

**Comment by nijel** [comment]
This will be part of 3.11.3, you can see it in https://docs.weblate.org/en/latest/changes.html#weblate-3-11-3
