### ISSUE TITLE
E-mail notification digest has misaligened html when displayed on gmail WebUI

### ISSUE THREAD

**Issue by Fat-Zer** [WeblateOrg/weblate#3520]
**Describe the bug**
There are several problems with HTML alignment in E-mail notification digests (see screenshots):

 * The timestamp (like `5 часов назад` or `5 hours ago`) is shifted a bit bellow the box its supposed to be in
 * The first notification reason is separated from others
 * An author for each notification is shifted (note that last notification is missing the author entry)

**To Reproduce**
1. Go to https://hosted.weblate.org/accounts/profile/#notifications
2. Set notifications to be reported in digests (`Daily digest`, `Weekly digest` etc).
3. Make a change to a repository.
4. Receive e-mails with misaligned HTML.

**Expected behavior**
Receive a well-formatted HTML.

**Screenshots**
![scr12](https://user-images.githubusercontent.com/1060057/75124656-c3179180-56c1-11ea-8a60-f7fce947e535.png)
![scr13](https://user-images.githubusercontent.com/1060057/75124750-35887180-56c2-11ea-82f8-4e39379b6a5a.png)

**Server configuration and status**
Hosted weblate.

**Additional context**
I haven't tested if this applies only to gmail or if it is a general failure.

**Comment by nijel** [comment]
Seems like Gmail is removing part of the CSS applied to mails.
