### ISSUE TITLE
translations are not complete after manual post of component

### ISSUE THREAD

**Issue by jzahradn** [WeblateOrg/weblate#3527]
Hello,

in Weblate 3.11 I have problem with creation of a component by manual post method. If I create it, only English translation is displayed. Other languages are missing. Detail information is attached in txt file. 

[weblate_3.11_post_problem_EN.txt](https://github.com/WeblateOrg/weblate/files/4255566/weblate_3.11_post_problem_EN.txt)

Best Regards
Jan

**Comment by nijel** [comment]
Can you please check server logs for the update? Maybe it failed with some error? (Though this should be visible in component alerts.)

**Comment by jzahradn** [comment]
I have created 'testbranch7' in a new branch in gitlab and repeated the test, now everything is fine. We can close this issue.
