### ISSUE TITLE
Installation instructions for macos

### ISSUE THREAD

**Issue by abtinmo** [WeblateOrg/weblate#3528]
**Is your feature request related to a problem? Please describe.**
I was going to install weblate and give a look to it, but i noticed there is no macos installation instruction in docs 

**Describe the solution you'd like**
There is a docker installation, but it would be great to install it on system for development.

**Comment by nijel** [comment]
My guess is that it won't be much different from [Linux installs](https://docs.weblate.org/en/latest/admin/install/venv-debian.html), just using `brew` to install dependencies.

Contributions to our documentation are definitely welcome :-).

**Comment by abtinmo** [comment]
> My guess is that it won't be much different from [Linux installs](https://docs.weblate.org/en/latest/admin/install/venv-debian.html), just using `brew` to install dependencies.
> 
> Contributions to our documentation are definitely welcome :-).

i tried but some packages have different names and some of them like: gir1.2-pango-1.0 libgirepository1.0-dev libacl1-dev python3-gdbm doesn't exist in brew.

**Comment by nijel** [comment]
* You can ignore the gdbm one, it's probably separated from Python only on Debian. 
* libacl is probably not needed on mac (guessing that it's not mentioned in https://borgbackup.readthedocs.io/en/stable/installation.html#mac-os-x)
* brew probably doesn't have the packages split into several ones, so install pango and cairo

**Comment by nijel** [comment]
Any luck with installing Weblate? In case it did work, can you please document it so that others can benefit from your experience?

**Comment by nijel** [comment]
I've added basic docs in c00a362cb37115f222ba4e16fac8f053d8c863a9. It's not tested at all, so correctiosn are welcome.
