### ISSUE TITLE
Problem with locale LC_ALL after migration the weblate to a new server

### ISSUE THREAD

**Issue by zmartyz** [WeblateOrg/weblate#3534]
Hello,

i'am having a trouble with one project that shows this alert message:

 sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
remote: 
remote: ========================================================================
remote: 
remote: The project you were looking for could not be found.
remote: 
remote: ========================================================================
remote: 
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists. (128)

This problem is only with one project, and the alert is shown only in a few components of the particular project. Weblate was migrated to a new server (centos8) from centos7. I installed all possible locales to the system but problem persists. 

locale command from cli shows this output: 
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

So its look like the LC_ALL is not set, i tried to export this variable globaly (in bashrc file) but problem persists. Also, the locale in Centos is  C.utf8 and not C.UTF8. Also, on the old server, this output looks same, with no LC_ALL set, but there is no alert messages.

Please, do you have any suggestions, how to solve this problem/bug?

Thank you very much
Martin

**Comment by nijel** [comment]
The most important thing is "The project you were looking for could not be found.", so most likely the Git URL is wrong. 

You probably can safely ignore the locales warning (in the end it's just a warning).

**Comment by nijel** [comment]
The locales warning should be gone with 7a1a376f17c20682e279303c13a232aded3f30b9.

**Comment by zmartyz** [comment]
I checked the repository URL in weblate administration/components, and the URL is exactly the same as on the old server, also if i try to save changes here, almost same error appears. 
Weired think is, that on the old server this works with the same URL.

**Comment by nijel** [comment]
Maybe authentication issue? For private repos, most services return not found if user doesn't have permissions to see it.

**Comment by nijel** [comment]
It can be also wrong repository URL. I've just seen this on a project using gitlab.com instead of github.com.

**Comment by zmartyz** [comment]
Ok, thank you for your suggestions!
