### ISSUE TITLE
PayPal donation link

### ISSUE THREAD

**Issue by user8446** [WeblateOrg/weblate#3540]
Is there a donation link through PayPal? I did not see one on the website

**Comment by nijel** [comment]
Thanks for interest in donating to Weblate. We've replaced PayPal in favor of accepting credit cards directly, see https://weblate.org/donate/. This was mostly due to high fees and horrible exchange rates.

As an option you can use PayPal on https://liberapay.com/Weblate/

**Comment by user8446** [comment]
Great, thank you

**Comment by comradekingu** [comment]
@nijel Liberapay recently started accepting IBAN transfers to € accounts, hoping that is set up :)

**Comment by nijel** [comment]
@comradekingu IBAN on Liberapay goes through Stripe, which is still not supported in Czechia (they seem to have launched closed beta this year, so it will eventually be an option).

IBAN is also directly supported on our website :-).
