### ISSUE TITLE
Placeholders with comma, space or colon

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3546]
How can I manage placeholders that contains comma or colons ?
Example: `You clicked $t(value, { count: 2 })!`, here **$t(value, { count: 2 })** is a valid i18next placeholder.

I can't add it manualy (I get an error message).

_Originally posted by @Heziode in https://github.com/WeblateOrg/weblate/issues/3389#issuecomment-584646789_

**Comment by nijel** [comment]
The flags should be expanded to use proper parser to support quoting of values:

```
placeholders:"$t(value, { count: 2 })":{other}
```

The parser should be probably based on same library as new search parser (see https://github.com/WeblateOrg/weblate/issues/3229) to share the knowledge and dependency.

**Comment by Heziode** [comment]
Also, remember to use an escape char to allow users to use double quote in the placeholders.

Example:
```
placeholders:"$t(value, { count: 2, name: \"John\" })":{other}
```
