### ISSUE TITLE
Improve date selection for reports [$32]

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3558]
**Is your feature request related to a problem? Please describe.**

Current reporting period selection is not user-friendly:

![image](https://user-images.githubusercontent.com/212189/75873029-7d6c6e80-5e0f-11ea-84e4-18cd280ab98f.png)

**Describe the solution you'd like**

I'd like to see something like this:

![image](https://user-images.githubusercontent.com/212189/75872958-60d03680-5e0f-11ea-8722-c12b09e86f4c.png)

**Comment by msanden** [comment]
Can I claim this issue?

**Comment by nijel** [comment]
Sure, you're welcome.

**Comment by rajat641** [comment]
Hi @nijel , Can I work on this. There is no update on this for a long time.

**Comment by nijel** [comment]
You're welcome! Yes, there are about two hundredths of issues without an update for a long time ;-)

**Comment by rajat641** [comment]
Hi @nijel ,
Today I explored on how to implement the above change and managed to find an already written JS component implementing the above feature. Here is the reference link [http://www.daterangepicker.com/#config](). 
It looked somehow like this on my local machine-
![image](https://user-images.githubusercontent.com/8374949/83105715-03473100-a070-11ea-8cd2-3bde010cf558.png)
Please ignore the styling details as it's just done for demonstration/clarification purposes to you.
It doesn't have a **This Year** and **Next Year** option(as given in the requirements image attached above) and I tried adding it but I did work out as its predefined. 

I'm not sure If I can change styling or not as its already predefined. I haven't worked on UX before so please let me know if I'm following the right path or I have to write everything from scratch or maybe learn something else. I thought of using some Bootstrap/JQuery Plugin but I am not very confident about my approach.

**Comment by nijel** [comment]
Writing from scratch is certainly not needed, this one seems like a good choice (it has compatible license and it seems to be using Bootstrap, so hopefully it will not require much of additional styling).

We use yarn to manage the deps, see https://docs.weblate.org/en/latest/contributing/frontend.html for more info on that and other frontend development hints (I've just pushed some improvements to that, it will take few minutes to be fully up to date).

**Comment by WofWca** [comment]
Is it _that_ not user-friendly? Nowadays browsers have pretty solid date pickers built in.

**Comment by nijel** [comment]
The date selection itself is okay, but seeing directly chosen date range would be definitely nicer than current drop-down and two inputs...

**Comment by akhilsahuji** [comment]
is this feature is still needed ?

can i work on it ?

**Comment by nijel** [comment]
Yes, nobody has contributed this so far.

**Comment by akhilsahuji** [comment]
@nijel could you guide me on reproducing the report section mentioned above? I have set up the demo project, but I am unable to locate the specific report section shown in the screenshot.

**Comment by akhilsahuji** [comment]
@nijel never mind i am guessing that we are talking about Translation progress reporting.

**Comment by nijel** [comment]
Yes, *Insights* / *Translation reports* in the menu. Currently, there is a dropdown for range selection and two date inputs. Instead, there should be just two date inputs sent to the backend and client-side selection of the ranges. It should probably also include time to make it explicit (this is a frequent question we get).

Here are some additional examples of how it could look:

![image](https://github.com/WeblateOrg/weblate/assets/212189/460343e6-19c8-4d43-9bb3-1d0f6f2cd54f)

![image](https://github.com/WeblateOrg/weblate/assets/212189/b3d9403c-1db5-4bb2-89d4-14947e038122)

**Comment by harriebird** [comment]
Hi guys, check my PR #11826 for this issue.

**Comment by nijel** [comment]
Implemented by https://github.com/WeblateOrg/weblate/pull/11826
