### ISSUE TITLE
Hosted Weblate is unable to commit translations to Weblate master branch

### ISSUE THREAD

**Issue by rffontenelle** [WeblateOrg/weblate#3565]
**Describe the bug**
I set to be notified of Weblate's string changes in Hosted Weblate, and for the last 3 days I have received over 40 notification e-mails of failed commits for the "Weblate/Application" resource. According to the [Weblate/Application's Alerts](https://hosted.weblate.org/projects/weblate/master/#alerts) page, the error message is:

```
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: This branch must not contain merge commits.        
To github.com:WeblateOrg/weblate.git
 ! [remote rejected]       master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:WeblateOrg/weblate.git'
 (1)
```
I assume a protection rule was added to its master branch.

**To Reproduce**
1. Go to https://hosted.weblate.org/projects/weblate/
2. Click on "watch" next to the eye icon, on the top-right of the window
3. Receive notification e-mail of each failed attempt to commit translations to the target source code repository ("WeblateOrg/weblate", in this case)

**Expected behavior**
To stop these notifications, and have translations merged.

**Screenshots**
Not needed, I guess. Let me know.

**Server configuration and status**
n/a

On pip installed Weblate:
n/a

On Git checkout:
n/a

Using docker-compose:
n/a

**Additional context**
n/a

**Comment by nijel** [comment]
Fixed.

Apparently, I need to better tweak notifications for myself to spot such things and avoid missing them among warnings from other projects.

If you don't want to get such notifications so frequently, you can set them to daily or weekly digest.

**Comment by rffontenelle** [comment]
@nijel I didn't notice this option. Thanks for the suggestion and for fixing it!
