### ISSUE TITLE
Blocking certain changes of translated strings

### ISSUE THREAD

**Issue by Kyuuu** [WeblateOrg/weblate#3566]
**Is your feature request related to a problem? Please describe.**
I sent translations in Spanish for certification for consoles. The translation successfully went through the certification, therefore I wouldn’t want anyone to change that specific string in my absence.

**Describe the solution you'd like**
I’d like for here to be a button called “block translation”, with which a certain string can be blocked.
(Ex. Only block changes for the string in position 12 in Italian.)

This option should only be available for the administrator of the project.

**Describe alternatives you've considered**
//

**Additional context**
//

**Comment by nijel** [comment]
[Enable reviews](https://docs.weblate.org/en/latest/workflows.html#enabling-reviews) and mark strings as reviewed. Regular translators will no longer be able to edit them.
