### ISSUE TITLE
max-length char count wrong

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#3567]
**Describe the bug**
When your string contains special chars which are transcribed in XML, like `&` to `&amp;` the target char count is off. The count is not the actual length of the target string in the app, but the total number of chars in the "string" in the Target Language edit field in Weblate.

**To Reproduce**
1. Component has strings like this: `Cross-plant orders are forbidden for EDI! Plants: &amp; and &amp;` (Originally. `Cross-plant orders are forbidden for EDI! Plants: & and &`)
2. When you translate this string with max-length parameter (set to e.g. 73), the correct target language string which would also fit into the application (Werksübergreifende Bestellung für EDI nicht erlaubt! Werke: & und &) is displayed as `Werksübergreifende Bestellung für EDI nicht erlaubt! Werke: &amp; und &amp;`
3. The reported char count for this string is 75, thus too long. Whereas the actual length is only 67.

**Expected behavior**
chars like `&amp;` should only count as **one** char against the `max-length` count.

**Screenshots**
Example:
![image](https://user-images.githubusercontent.com/26718215/75986609-b3345480-5eee-11ea-9201-2239069872b0.png)

**Server configuration and status**
Weblate Docker v3.11.2

**Comment by nijel** [comment]
Currently, the max length is defined as length of the string without any transformations. In the end Weblate doesn't really have the knowledge what will happen with the string.

This particular case looks easy, but this is really a gray area of similar cases. What about HTML markup? Or placeholders?

**Comment by ilocit** [comment]
Sure, there are many more things that could be considered. But this one, XML related should be considered, I think. It is pretty common I should think. But this is of course for you and the whole community to discuss and decide then.

**Comment by nijel** [comment]
Kind of similar request is https://github.com/WeblateOrg/weblate/issues/3140
