### ISSUE TITLE
Disable normal registration when using Azure Active Directory [$15]

### ISSUE THREAD

**Issue by jan-nsn** [WeblateOrg/weblate#3575]
We are using Weblate on Kubernetes and our problem with weblate is that when we are using Azure Active Directory and have new registrations disabled, it is not possible for new Azure AD users to login into Weblate.
Currently our settings for Weblate are:
- WEBLATE_REQUIRE_LOGIN: 1
- WEBLATE_REGISTRATION_OPEN: 0
- WEBLATE_SOCIAL_AUTH_AZUREAD_OAUTH2_KEY: xxx
- WEBLATE_SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET: xxx 
Also we want to use the normal E-Mail Authentification, for users that we created in Weblate.
We tried using the WEBLATE_NO_EMAIL_AUTH setting but this shuts off E-Mail login completely.

The best possible solution would be that only E-Mail registrations can be turned off, but still possible for new Azure AD users to register in Weblate and Weblate users with E-Mail authentification to login.

**Comment by nijel** [comment]
If you want to disable registration only, do that using [WEBLATE_REGISTRATION_OPEN](https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_REGISTRATION_OPEN).

**Comment by jan-nsn** [comment]
When setting WEBLATE_REGISTRATION_OPEN to 0, we are still unable to login new users via Azure AD.
![Unbenannt](https://user-images.githubusercontent.com/37983983/76083542-2d77de00-5fae-11ea-9ad1-10638187615d.png)

**Comment by nijel** [comment]
Ah, I didn't realize, it blocks *all* new registrations.

**Comment by nijel** [comment]
I think it would make sense to introduce something like `REGISTRATION_ALLOW_METHOD` which would take list of methods allowed for new registration even with `REGISTRATION_OPEN` set.

**Comment by jan-nsn** [comment]
Yeah, it would be great to have a list to allow methods for new registrations.
When do you think this feature is available for us?

**Comment by nijel** [comment]
Currently, it's not on a roadmap. It should be straightforward to implement, so patches are welcome. You can also fund the development either by raising bounty via Bountysource (and hoping the bounty will attract some developer) or directly, see https://weblate.org/support/.
