### ISSUE TITLE
latest celery fails performance/ page

### ISSUE THREAD

**Issue by minusf** [WeblateOrg/weblate#3579]
**Describe the bug**
This bug is affecting a clean install of Weblate: https://github.com/celery/celery/issues/5990

Until it's fixed the version should be pinned for 4.4.0

**To Reproduce**
1. Install Weblate 3.11.2
2. Click on 'Performance Report'
3. See error

**Comment by nijel** [comment]
It fails more things, root cause is https://github.com/celery/celery/commit/3b564c7c2ffbc8e215ca46e5606023d56785c2a0

**Comment by minusf** [comment]
I was wondering would it be possible to have a release plz that includes this fix?

**Comment by nijel** [comment]
Yes, it's planned soon (most likely today afternoon).

**Comment by nijel** [comment]
You can however fix this particullar issue by installing older version of celery: `pip install Celery==4.4.0`.
