### ISSUE TITLE
Added string with failing checks is removed from editing field

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3580]
https://hosted.weblate.org/translate/remmina/remmina/ar/?checksum=eabec522b18da3f6

![bilde](https://user-images.githubusercontent.com/13802408/76136693-c3eee280-6034-11ea-8f8e-39337f5b3d95.png)
("Testing testing" removed afterwards).
Not sure if this only happens in Arabic, will have to see.

Edit: Didn't happen for
"The translation has been saved, however there are some newly failing checks: Mismatching line breaks" at
https://hosted.weblate.org/translate/remmina/remmina/nb_NO/?checksum=3dd07397d0fb58dd

**Comment by nijel** [comment]
I can't reproduce this, it seems to work fine for me. Maybe some browser issue which prevented displaying the string?
