### ISSUE TITLE
Swapping username and full_name in the stats page

### ISSUE THREAD

**Issue by minusf** [WeblateOrg/weblate#3597]
**Is your feature request related to a problem? Please describe.**
Because of our custom SSO where the username is a `UUID`, the stats page is a see of UUIDs... 

**Describe the solution you'd like**
It would be nice to have `full_name` as the anchor text and `username` as the `title`. Basically swapping the current behaviour.  I think this change would be beneficial to all users of Weblate, `full_name` is supposed to be more human friendly after all. Fallback to `username` in case `full_name` evaluates to empty string is already there.

**Comment by nijel** [comment]
We used to display full names in past, switched to using usernames some time ago to be consistent with discussions, where we use usernames to be able to utilizee mentions easily.

**Comment by minusf** [comment]
ok, i'll just make a custom tag solution.
