### ISSUE TITLE
Import translation memory run into timeout

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#3600]
**Describe the bug**
Importing TM (e.g. tmx file) in Weblate renders 504 Gateway Time-out

**To Reproduce**
Prepare a tmx with a reasonnable size (my case: File size 8MB, Strings: roughly 18'000)

1. Go to 'myweblate-instance/memory/'
2. Click on 'Select File' under 'Import translation memory', select file and click 'Upload'
3. Wait for server to return, ends up in '504 Gateway Time-out

**Expected behavior**
Independent, whether tmx processing takes a while, Weblate should return to a proper view (may indicating that process happens in background, similar to asynchronity introduced with "Automatic translation" --> Progress bar)

Remark: After manually refreshing 'myweblate-instance/memory/', it shows that the 18'000 strings are properly imported.

**Comment by nijel** [comment]
This should perform way better with upcoming 4.0 release, where performance of built in memory is much increased. I'll close this as fixed for 4.0, but feel free to reopen in case you reproduce it there.

**Comment by rhofer** [comment]
@nijel Just tested this with my self hosted instance (weblate/weblate:4.0.2-1) AND with the test project on hosted.weblate.org

- Self hosted: still run into timeout 504 when uploading (maybe after 10 to 15 sec). Waiting a while and then refreshing the Translation memory view also properly shows the TM is updated.
- hosted.weblate.org: no timeout happens. Need to wait roughly 1-2 minutes, whilst the busyindicator on the browser tab is spinning, but it properly refreshes the page and results in updated personal TM

My gut-feeling is that we have different server timeout settings for the webserver in the docker image and the webserver behind hosted.weblate.org .. (?) ... or asked differently: What is the difference between the docker image and hosted.weblate.org in this regard?

**Comment by nijel** [comment]
Maybe you have some additional proxy in front of Weblate? The nginx and uwsgi in Docker container have intentionally very high timeouts. You might need to do the same for the proxy. For example here is how we do it with ssl proxy: https://github.com/WeblateOrg/docker-compose/blob/aa99e9f22bc5e154ed8df15c9e9edba478ec65a3/docker-compose-https.yml#L37-L38

**Comment by rhofer** [comment]
Thanks for the hints. Yes, the additional proxy is it. I changed the timeout to something reasonable high and it works now.
