### ISSUE TITLE
Importing the same TM (e.g. tmx file) n times seems to add the strings n times

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#3601]
**Describe the bug**
When importing a TM, available as e.g. tmx file, several times it seems to add the strings several times as well, despite of having them imported already.

**To Reproduce**
Prepare a tmx with e.g. 10 entries.

1. Go to 'myweblate-instance/memory/'
2. Click on 'Select File' under 'Import translation memory', select tmx file and click 'Upload'
3. First import result shows "Number of your entries" = 10
4. Click on 'Select File' under 'Import translation memory', select same tmx file again and click 'Upload'
5. Second import result shows "Number of your entries" = 20
6. and so on ...

Observed together with #3600 

**Expected behavior**
Multiple import of same translation should only add once to the TM.

**Remark**
I don't see a reason why this import should add to TM when repeating on the same strings. In case there is reason why it is supposed to behave as-is, please comment and consider this bug report as obsolete.

Maybe a better way could be to implement #3561 instead of fixing this one.

**Comment by nijel** [comment]
This one is fixed for sure in 4.0, by a091b10c873011ae279903ac9bb896c7f515d259.

**Comment by rhofer** [comment]
@nijel Many thanks for the fix. Successfully tested with weblate/weblate:4.0.2-1. Works now as expected.
