### ISSUE TITLE
API for users and groups

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3607]
**Is your feature request related to a problem? Please describe.**
In many cases it would be useful to have an API to manage users, their group membership and permissions.

**Describe the solution you'd like**
Extend API with user management.

**Comment by valeriocos** [comment]
Hi @nijel , is it possible that this issue is related to https://github.com/WeblateOrg/weblate/issues/3659 ?

**Comment by nijel** [comment]
Yes, as there is no API for users it can't point to it.

**Comment by valeriocos** [comment]
Thank you for the quick reply @nijel
