### ISSUE TITLE
Different source and target branch

### ISSUE THREAD

**Issue by ochorocho** [WeblateOrg/weblate#3610]
I want to be able to use a branch as source (`master`) and push changes to another branch (e.g. `weblate-translation`). So reviewers can check the translation before merging.

**Describe alternatives you've considered**
Using a fork and merge it whenever it changed. But it needs to be updated all the time.

Would be great if Weblate could support such workflow.

Thank you.

**Comment by nijel** [comment]
You can use pull requests (GitHub and GitLab are currently supported) to achieve this, see https://docs.weblate.org/en/latest/vcs.html#github and https://docs.weblate.org/en/latest/vcs.html#gitlab

But having support for different push branch makes sense anyway.

**Comment by fnune** [comment]
Slightly related: while trying to achieve the same (pushing to a specific branch) my first attempt was to append `#branch-name` to my push URL, but the `#branch-name` part was ignored.

**Comment by ochorocho** [comment]
Thank you @nijel
