### ISSUE TITLE
Possibility to get chars stats from Insights / Download statistics

### ISSUE THREAD

**Issue by Kyuuu** [WeblateOrg/weblate#3612]
**Is your feature request related to a problem? Please describe.**
//

**Describe the solution you'd like**
Seeing also chars stats in Insights / Download statistics:
![image](https://user-images.githubusercontent.com/33127074/77160911-b3b11b80-6aa8-11ea-8a9c-fe400275ad37.png)

**Describe alternatives you've considered**
//

**Additional context**
//

**Comment by comradekingu** [comment]
From what I remember Transifex only has stats for the number of translated words.
Some translation houses pay for each translated word, so useful to have without having to calculate it manually.

**Comment by Kyuuu** [comment]
Yup. In Poland and probably Russia (or they just do that for Polish folks) we have "pages system" - I will not ask for implement that cause it is easy to calculate it if I have full chars amount for the project.

//If somebody is interested how this system works:
Translator count their work by X złoty for 1 page
1 page = 1800 chars

So if translator want 20 złoty per page and I send him 3900 chars to translate: 3900/1800= 2,17
Up to full page we have 3 pages.
so 3 pages * 20 złoty = 60 złoty to pay for his job (and translator want to know it before he starts translation).
