### ISSUE TITLE
Users page and easy user search

### ISSUE THREAD

**Issue by Kyuuu** [WeblateOrg/weblate#3615]
**Is your feature request related to a problem? Please describe.**
Whenever I don't remember someone's nickname I have to search for it via /admin/weblate_auth/user/ page.

**Describe the solution you'd like**
User page with query field. You should be able to sort users alphabetically, by date created, by project access... also you should be able to open profile settings via this page.

**Describe alternatives you've considered**
//

**Additional context**
Something in this style:
![image](https://user-images.githubusercontent.com/33127074/77183146-2f718f00-6ace-11ea-8173-6e07735f61da.png)
![image](https://user-images.githubusercontent.com/33127074/77183165-37313380-6ace-11ea-85d2-bb99e15308b5.png)

/weblate/stats/ page would also be nice if linked here. Now this page is a bit hidden and it doesn't make sense a bit that best translators stats are part of "About Weblate".
![image](https://user-images.githubusercontent.com/33127074/77181728-0a7c1c80-6acc-11ea-96a5-16a977644bed.png)

**Comment by nijel** [comment]
Related to #3223.
