### ISSUE TITLE
Translator access limited to component or not limited by anything

### ISSUE THREAD

**Issue by Kyuuu** [WeblateOrg/weblate#3616]
**Is your feature request related to a problem? Please describe.**
//

**Describe the solution you'd like**
In User settings we should be able to select access by:
- Global Access (to translate all components)
- Project/s Access (to translate everything in the selected project)
- Component/s Access (to translate only selected component)
(and also chose to which one language this person may contribute in these components)

**Describe alternatives you've considered**
//

**Additional context**
In the same way we should choose access to adding new languages.

**Comment by comradekingu** [comment]
When would it be useful?

**Comment by Kyuuu** [comment]
For me right now it would be useful.
I have 7 projects already. Some of them are private, some are protected.

I am a casual user type. Groups and roles on admin site are too messy for me in many ways - so I just resigned from it and started using _Manage users_ page to add translators to projects.

So if there will be a translator that has to translate one of the projects - I just add him there.
If there will be a translator that has to translate 3 projects - I have to enter every single project and add him there.
If there will be a translator that has to translate all projects - I have to enter 7 projects one by one and add him.

If there would be a separate page with users where I can add all projects or components I want and select permissions for this user in these projects or components.
Or (as manager) I would have the possibility to do that in the user profile - it would be much easier.

Also it would be easy to check what permissions to which ones projects the user has. And if I want to delete him from these projects or some projects - it would be easy and possible to do. And everything from the one page.

**Comment by nijel** [comment]
* The global and per project access is there.
* Per component access will be added, see #3267.
* The user management should be moved from Django admin interface, see #2363, #2493, #2126 and #2127.
