### ISSUE TITLE
Glossary entries not appearing because of special characters

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#3618]
**Describe the bug**
Glossary entries do not always appear in the translation interface as they should, if they have special characters immediately before or after them.

**To Reproduce**
Two examples from The Document Foundation's Weblate instance: [first](https://translations.documentfoundation.org/translate/libo_ui-master/officecfgregistrydataorgopenofficeofficeui/fi/?checksum=8f0b490e8dd25e75
) [second](https://translations.documentfoundation.org/translate/libo_ui-master/filtermessages/fi/?checksum=6711a2940ed0b776)

The glossary entry for "accessibility" does not appear, even though it's in the [glossary](https://translations.documentfoundation.org/dictionaries/libo_ui-master/fi/).

**Expected behavior**
The relevant glossary entry should appear in the translation view.

**Screenshots**

**Server configuration and status**

**Additional context**
The TDF Weblate instance has some customisations IIRC, but nothing related to glossaries as far as I'm aware.

**Comment by comradekingu** [comment]
Looks like detection is thwarted by it being:
~Accessibility
and
accessibility-

I get ~, but - changes the nature of the word. Maybe that could be a second rate suggestion?

**Comment by tjhietala** [comment]
The dash sometimes changes the meaning, sometimes not. In English at least, the conventions seem quite fluid, e.g. "test driven" and "test-driven" have the same meaning. If there are no exact matches in the glossary, in this example it would be still useful to show the entry for "test", if one exists.

**Comment by nijel** [comment]
There are some changes in handling glossaries for 4.0 (see 7fdc0378b8d64b3190d4eacb943850da07948767), but I'm not sure it's going to address this.

In the end this is similar to #2183. Currently, the glossary search is far from being perfect and definitely needs some improvements.

**Comment by vernzimm** [comment]
I copied this from StackExchange question with additions for relevancy... 

I am working on a translation project with Japanese as the source language, using Weblate 4.0. Owner was previously using 3.3, and the same issue was happening. After adding a term into the glossary, it often fails to show up when the source string has a match. It will show up if there is a single phrase exactly matching the glossary, but Japanese does not use spaces between words, so normally it will fail. Do I need to use regex in the glossary? Seems like a lot of hassle to enter every word and phrase with regex to get a match?

Possibly there could be language dependent rules... a generic set for a given language, such as match all substring, and then the ability to customize regex matching per entry? Could you use the existing "Search" interface in some way, like the glossary entries would actually be customized search entries, even to the extent of then selecting the relevant strings and deselecting improper matches vis-a-vis search and replace interface? Maybe a downvote for incorrect glossary match on the string page could also "unselect" that "replace" match.

**Comment by nijel** [comment]
There are already some language depending rules, but apparently they do not work well in your case. Can you please share some example of glossary entry and string where it should be shown?

**Comment by vernzimm** [comment]
Hi nijel,

The translation I am working on is located at [nussygame](http://translate.nussygame.com/projects/edrpg/). You should be able to browse without login.

[English Dictionary](http://translate.nussygame.com/dictionaries/edrpg/en/) (note entry for **魔王** translated to **Satan**).

I do a [search](http://translate.nussygame.com/languages/en/edrpg/search/?q=source%3Ar%22%E9%AD%94%E7%8E%8B%22&checksum=&offset=) in English section using search string **source:r"魔王"**. Without **r"_"** we get no results(?) and with **=** we get a single [result](http://translate.nussygame.com/translate/edrpg/edrpg-origin/en/?checksum=13ed91a4cf65a348).

Glossary does not provide a match for any of the results, even the single exact match result. Is this possibly a configuration issue? I am not in charge of the server, and, not surprisingly, it is difficult to communicate with owner due to language barrier :(.

**Comment by nijel** [comment]
@vernzimm The string search should get better in 4.0.2 and later, please recommend him to upgrade. The glossary search also works well for me on current version. 

PS: In case you're curious, this is related change: 5ed60d3a49c32373883f4d59e6671351e85e1bda

**Comment by vernzimm** [comment]
Sadly I think I am stuck with 4.0 for a while. I think he does not like "point" updates... went from 3.0 to 4.0, never 3.x or 4.x... when do you plan to release 5.0? 😆  

Maybe someone else can confirm the function for Japanese, sorry. If I have a lot of free time, maybe I will download docker 4.0.2 for myself to test.

**Comment by comradekingu** [comment]
@vernzimm Added the instance to https://github.com/WeblateOrg/weblate/wiki/References :)

**Comment by nijel** [comment]
@vernzimm  5.0 will be out in few years. We're on bi-monthly schedule for 4.x releases and there is plan when they will turn 5.0. Anyway this is getting off-topic here.
