### ISSUE TITLE
Ability to add new string to an existing component

### ISSUE THREAD

**Issue by dragosv** [WeblateOrg/weblate#3624]
My workflow would be to add a new string in the xliff file, upload the new file, translate it and download it back. Also do not see a way to add it from the interface. For monolingual files would probably mean that it is added in the template file or source language.

**Comment by nijel** [comment]
Adding for monolingual files is already there, for bilingual it's not (because these are in most cases extracted from the source code automatically, so adding doesn't make much sense in this case).

**Comment by dragosv** [comment]
In order to integrate with Serge I need to be able to have the following workflow working
- Developer adds new string into 
- Serge generates additional property in the xliff or po file
- wlc uploads the file with the new string
- Weblate shows the new string
- New string is translated in Weblate
- wlc downloads the file with the translated string
- Serge parse the new string translation and generates the according translation file (mono or bilingual)
- Developer sees the new string as translated

**Comment by dragosv** [comment]
`      <trans-unit id="a0ab9284a353f3610e815eff63031843" resname="header.three">
        <source xml:lang="en">Three</source>
        <target xml:lang="fr-FR" state="new"></target>
      </trans-unit>	`

**Comment by dragosv** [comment]
By looking at the code I can see that the logic is to merge translations based on the store ones, so no new keys are added

**Comment by dragosv** [comment]
See https://github.com/WeblateOrg/weblate/blob/master/weblate/trans/models/translation.py#L730

**Comment by nijel** [comment]
I see no problem with what you've described in https://github.com/WeblateOrg/weblate/issues/3624#issuecomment-603892095. You just have to use ``--method=replace`` for upload in step 3. Just make sure you've downloaded the existing translations prior that, because they are replaced with content of the file.

**Comment by dragosv** [comment]
I looked at the replace method and indeed it preserves the new string between download and upload, however the new string is not available on the interface. In my scenario the component is stored locally, not on a git repository.

**Comment by nijel** [comment]
The new strings should appear there. In case you are using monolingual setup, the new strings have to be uploaded the monolingual template as well.

**Comment by dragosv** [comment]
They do not show up (the number of strings and words is the same after the upload).

**Comment by dragosv** [comment]
By looking at handle_replace I can see that create_translations and check_sync are only executed if the component is a vcs component, this not being the case for a locally stored component

**Comment by dragosv** [comment]
On another note added support for  Serge <-> Weblate integration https://github.com/dragosv/serge-plugins

**Comment by nijel** [comment]
There is no condition for that:

https://github.com/WeblateOrg/weblate/blob/5fa9961c30e13bb5667a13d3bc8bced6730c384f/weblate/trans/models/translation.py#L836-L852

There is always a VCS repository underneath even if you do not use remote. The code only checks whether there was any change in the file and in that case it does the processing.

**Comment by dragosv** [comment]
However it did not worked for me. I've created the component by uploading the translation files (xliff).

**Comment by nijel** [comment]
Can you please check server logs what happens when uploading the file?

**Comment by dragosv** [comment]
@nijel What is the location of the server logs for Weblate?

**Comment by nijel** [comment]
It depends on your logging configuration. The example one logs to syslog, you will will find them in `/var/log/messages` or `/var/log/syslog`. With Docker it logs to container output.

**Comment by nijel** [comment]
I've also added more detailed explanation to docs: https://docs.weblate.org/en/latest/debugging.html#weblate-logs

**Comment by dragosv** [comment]
Unfortunately I am using bitnami and none applies (I've mounted /opt/bitnami)

**Comment by nijel** [comment]
Sorry, I have no clue about that. Check Weblate `settings.py` how LOGGING is configured there.
