### ISSUE TITLE
User Interface Locale

### ISSUE THREAD

**Issue by ronniebrito** [WeblateOrg/weblate#3625]
hi, 

we just installed Weblate and are trying to chenge user interface locale to pt-BR.
We changed the option at seeting.py (LANGUAGE_CODE = "pt-BR" ) and also at user settings "Interface Language" option. 

But  just minor parts of the interface language were changed to pt_BR. 

Am I missign something?

regards

version is  Weblate 4.0-dev

**Comment by nijel** [comment]
You probably didn't compile the po files, see last step in https://docs.weblate.org/en/latest/admin/install/source.html#quick-source

**Comment by ronniebrito** [comment]
that was exactly the case
thank you very much!!!!!!!
