### ISSUE TITLE
Need an option to strip locations from PO files when submitting a pull request from weblate

### ISSUE THREAD

**Issue by abbra** [WeblateOrg/weblate#3627]
FreeIPA project is moving to use Fedora weblate instance. We use Pagure as primary git storage but use Github pull requests workflow to provide contributors a way to easily submit changes.

For translations we store PO files that have location stripped with the following command:
```
msgattrib --translated --no-fuzzy --no-location -s $file > $output
```

However, Weblate submits pull requests with non-stripped translation files. Github then refuses to show content of the pull request, making it effectively non-reviewable.

We would like to see an option in Weblate to strip PO files before sending them as a pull request.

**Comment by abbra** [comment]
Ideally, we want to have a mechanism that allows us to run a sequence of operations before providing a commit that would be submitted by the weblate. In freeipa we have 'make strip-po' target that prepares PO files for the commit.

**Comment by nijel** [comment]
Either you have po files with locaiton or not, Weblate doesn't do any changes in this. If the location is present in the po file, removing it in Weblate pull requests doesn't make much sense because it would be added later by whatever you use to update them on source change. Or am I missing something?

**Comment by abbra** [comment]
No, our po files don't have location, we strip them before committing to upstream git repo. POT file has them. Weblate creates a pull request that has full set of locations in PO files. Here is an example that actually has two bugs: https://github.com/freeipa/freeipa/pull/4446/files

- one is LINGUAS modification that makes LINGUAS unusable to gettext Makefile
- another one is these enormous size PO files that github refuses to show for review

**Comment by abbra** [comment]
Another issue is that sort order seem to be different which could be partially attributed as a reason for these huge diffs. There seems to be no way to control the order to be the same as in gettext tools.

**Comment by nijel** [comment]
Okay, finally I understand what you use. It would be great to mention your setup in the beginning: 

* The POT files are in the repository.
* Weblate updates PO files by [msgmerge addon](https://docs.weblate.org/en/latest/admin/addons.html#update-po-files-to-match-pot-msgmerge).
* The LINGUAS is update by [addon](https://docs.weblate.org/en/latest/admin/addons.html#update-linguas-file).

Have you considered generating POT files with ``--no-location`` to get rid of location in case you don't want to have them in the PO file? That seems to be the most straightforward approach.

I've created separate issue for LINGUAS update bug, see https://github.com/WeblateOrg/weblate/issues/3633
