### ISSUE TITLE
how to debug social auth / azure ad logins

### ISSUE THREAD

**Issue by Mandraenke** [WeblateOrg/weblate#3632]
**Describe the bug**
I tried to setup AzureAD to provide login data. But I only get "Authentication cancelled." after entering password and getting redirected to weblate. 

**To Reproduce**
1. Click on login with Azure / register with Azyre
2. Provide correct credentials
3. Login page shows error "Authentication cancelled."

**Expected behavior**
Setting up a new AD app I don't expect to work at first try. But the logs don't show anyting useful what could cause this error. What can I do to debug this?

**Server configuration and status**
~/weblate-docker# docker-compose exec weblate weblate list_versions
ERROR: The Compose file is invalid because:
Service https-portal has neither an image nor a build context specified. At least one must be provided.
~/weblate-docker# docker-compose exec weblate weblate list_versions
ERROR: The Compose file is invalid because:
Service https-portal has neither an image nor a build context specified. At least one must be provided.
~/weblate-docker#

**Additional context**

**Comment by nijel** [comment]
Enable debug mode and the logs will show more details from authentication.

**Comment by Mandraenke** [comment]
I did set "WEBLATE_DEBUG: 1" in my docker compose override and restartet. Watching with docker logs I only got this lines:

`nginx stdout | 172.27.0.2 - - [26/Mar/2020:08:39:14 +0000] "GET /accounts/login/ HTTP/1.0" 200 12608 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
uwsgi stderr | [pid: 313|app: 0|req: 1/1] 172.27.0.2 () {58 vars in 1164 bytes} [Thu Mar 26 08:39:14 2020] GET /accounts/login/ => generated 12608 bytes in 997 msecs (HTTP/1.0 200) 11 headers in 516 bytes (1 switches on core 0)
nginx stdout | 172.27.0.2 - - [26/Mar/2020:08:39:16 +0000] "GET /js/i18n/ HTTP/1.0" 200 3223 "https://weblate.foo.bar/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
uwsgi stderr | [pid: 314|app: 0|req: 1/2] 172.27.0.2 () {54 vars in 1030 bytes} [Thu Mar 26 08:39:15 2020] GET /js/i18n/ => generated 3223 bytes in 522 msecs (HTTP/1.0 200) 10 headers in 330 bytes (1 switches on core 0)
nginx stdout | 172.27.0.2 - - [26/Mar/2020:08:39:18 +0000] "GET /site.webmanifest HTTP/1.0" 200 433 "https://weblate.foo.bar/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
uwsgi stderr | [pid: 314|app: 0|req: 2/3] 172.27.0.2 () {52 vars in 843 bytes} [Thu Mar 26 08:39:18 2020] GET /site.webmanifest => generated 433 bytes in 128 msecs (HTTP/1.0 200) 9 headers in 394 bytes (1 switches on core 0)
nginx stdout | 172.27.0.2 - - [26/Mar/2020:08:39:30 +0000] "POST /accounts/login/azuread-tenant-oauth2/ HTTP/1.0" 302 0 "https://weblate.foo.bar/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
uwsgi stderr | [pid: 314|app: 0|req: 3/4] 172.27.0.2 () {66 vars in 1460 bytes} [Thu Mar 26 08:39:30 2020] POST /accounts/login/azuread-tenant-oauth2/ => generated 0 bytes in 166 msecs (HTTP/1.0 302) 12 headers in 811 bytes (1 switches on core 0)
nginx stdout | 172.27.0.2 - - [26/Mar/2020:08:40:04 +0000] "GET /accounts/complete/azuread-tenant-oauth2/?code=Q001AQABAAAAAAAm-06blBE1TpVMil8KPQ41VSYMZs2cboQfJBCe0Otonm-G4eUdKPu3xUvUSh96t44pLYeouUKy-3L5kKhngtNHzatewoXnPidHH-XBkKPM4MNXBz9DSPC0eZPYeNdIrsPyNL0T_3sTZPzNJlVEPMJl8ujXGo2VXTk9R9DhHakegDq08au9XKPM3b859zhcRZjP3hHZ--ljd5MQkqYJzZ6fw4vStrKrPxULdUNMG6OKjD82ITt8aSZAsqoXvIaqVA6j2yjmUhd8REe-0YJJJysGxeOqZlXLC_bImDFfHNL9tHIS1vc2Sdj3X08Cze53hda8s9kPA_tpRnsq0czmYsjPGg-JcHzODCWxhKEdzWo5jTz9z6CtPvgTalqe6l9ofWWh9EnahFDTj5Rna5OWk8DzSOsN2LmuVHOXnzkzcZLvBxNEjchVPhn7cqmf9vfWizXAKMH5A4UbBSveOod34hnZdBaoguMYkq6e0rEDRc2bcRC-3Zr5_0ocQ9XXY8QBfkoUCGVEew7i-HDu8ee6M6fyAC3Pb1xVYITs8mG5eT6nV0MQnoCA2IuO0t0LFAFNQZARTQNxjOsZvS6q8dYElwxAwrgCjXda7p_Ub_gmNZFeKBSPZ1JjDB4N6FHcRWL-_W0HgdR1btYQGZIvg6D9xxS7Sbaz8Ups4odKH46ccqUa1_hT54om7DMd-Q1a4-iKnH0xye5hbI9852KhvLPHp9JvL9HLrUJbU-Dz2cmZUcEh8EXllZprUjp0u0d35h_JqWPsig5ZjpH8EhjZ4nEtiWboaSW-0vbgiynTfpwkoNMmKsRtB2fxtPW7bic47W-oKrb2orqV8LqbpyfUY2Gi9cwQ6J2P5jTNulO_YXaCo66PALDLV7TeuvXo1d1wYnuUmNtgWH5-VqjPBexrj0vETD4yIAA&state=V3V1AjevTBVkOCoTAtvSlz3H0UTjsaW6 HTTP/1.0" 302 0 "https://login.microsoftonline.de/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"`

Maybe I am missing something obvious?

**Comment by nijel** [comment]
Most likely something is wrong on Azure setup. Is your tenant configuration correct? Is authenticated user allowed to use it?

**Comment by ilocit** [comment]
Is SSL properly configured on your docker installation? Otherwise the URI with HTTPS will not work.
