### ISSUE TITLE
Error Amagama translations

### ISSUE THREAD

**Issue by maicol07** [WeblateOrg/weblate#3636]
**Describe the bug**
Amagama translations can't be used:
 `URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>`

**To Reproduce**
Try to translate a string with Amagama enabled. In the translation UI it throws this error

**Expected behavior**
No error. Amagama should work

**Comment by nijel** [comment]
The third-party service is not well maintained for some time, see https://github.com/translate/amagama/issues/3214

The only thing we can do is to remove it from our code base, but I prefer to keep it around in case it will be revived.
