### ISSUE TITLE
Search in translation memory doesn't work as expected

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3637]
**Describe the bug**
With 4.0 changes to translation memory, it provides better phrase-based matches, but the search is no longer working as expected.

**To Reproduce**
1. Go to translate page.
2. Click on 'Translation memory'
3. Try searching some terms.
4. See no results

**Expected behavior**
Single phrase queries should return reasonable number of results.

**Comment by nijel** [comment]
It might be just due to quality threshold, which should not be applied in this case.

**Comment by comradekingu** [comment]
I tried adding labels in bulk and got nothing. The same string search worked as expected.

**Comment by nijel** [comment]
@comradekingu Please file separate issue for that, it doesn't seem to be related to translation memory search...
