### ISSUE TITLE
Editing Xliff base monolingual base file doesn't change "target" 

### ISSUE THREAD

**Issue by est42** [WeblateOrg/weblate#3641]
**Describe the bug**
Changing the source language in the weblate monolingual base XLIFF file doesn't change the target language in the same base file, therefore the changes are discarded when the translation file is imported to Xcode, since Xcode is only importing the target of the base file.

**To Reproduce**
1. Edit source XLIFF base file translation
3. Commit to git repo
4. import XLIFF file to Xcode

**Expected behavior**
In case of editing source of the monolingual base XLIFF file, the target should be changed as well to the same value.

**Server configuration and status**
Weblate 3.11.3

**Comment by nijel** [comment]
Just to clarif: Both source and target should be changed on such edit?

**Comment by est42** [comment]
yes, only when it is the source of the monolingual file, edit to the source should change also the target, since it's basically the same language. Xcode would discard the source once imported and keep the target so in this case any edit of the source over Weblate UI wouldn't make a difference.
