### ISSUE TITLE
Move Search field in Glossaries to the top of the page

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#3642]
When browsing Glossaries, the search field is displayed at the end of the list on each page.

It would be better UX if this Search field was at the top, since this is where you land by default when navigating to or within the Glossary.

![image](https://user-images.githubusercontent.com/26718215/77911352-fa64f980-7290-11ea-85ff-53263e6bfe2b.png)

And/or make the the navigation control at the top act like in Translation (for Search and Jumping to a certain page in the list of Glossary entry pages.

![image](https://user-images.githubusercontent.com/26718215/77911602-5cbdfa00-7291-11ea-8cdb-b3d65f82f36f.png)

**Comment by nijel** [comment]
Sure, you're welcome.
