### ISSUE TITLE
String Status reset to "Needs Editing" is not being persisted in the db.

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#3643]
When a string was previously translated and then reset to "`Needs Editing`", this is change is reverted to `Translated `after some time, maybe related to a "`commit`" that happens after the reset of the string status....
This behavior makes it impossible to set strings back to `Needs Editing` so that the translator is urged to review the string again. Status change should be permanent until changed back again by a user, not the system.
![image](https://user-images.githubusercontent.com/26718215/77912140-4e241280-7292-11ea-89a2-31834c4e0134.png)

This happend regardless of weather "`Review`" is enabled, like in the scenario on the screenshot, or not.

System is `v3.11.3` running as a `Docker container`.

**Comment by nijel** [comment]
For xliff the state is supposed to be saved into the file and persisted there. Can you check `state` attribute of the unit in the file?

**Comment by ilocit** [comment]
Sure, but until it is committed and pushed to the actual file in the git repo, the state is only available within Weblate. And there it is lost.
That is the problem I wanted to outline.

**Comment by nijel** [comment]
You've mentioned commit in the initial comment. On commit the state is supposed to be synced to the XLIFF file. If that fails, it will be reset in Weblate as well.
