### ISSUE TITLE
Permissions on a component and component list level

### ISSUE THREAD

**Issue by kamilgrymuza** [WeblateOrg/weblate#3646]
**Is your feature request related to a problem? Please describe.**
Right now when a project is set to private it is possible to grant access to that project to certain users (according to the [documentation on Per project Access Control](https://docs.weblate.org/en/latest/admin/access.html#per-project-access-control)) but not on a component or component list level, which is desirable for larger projects.

**Describe the solution you'd like**
It should be possible to grant access only to a particular component or a component list (once https://github.com/WeblateOrg/weblate/issues/3291 is implemented) so that the user isn't able to view other components/component lists within the same project.

**Comment by nijel** [comment]
Related to https://github.com/WeblateOrg/weblate/issues/3267, but that one is about *restricting* and this one about *granting* per component.
