### ISSUE TITLE
"markdown-text" as standardized flag name for "md-text"

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#3648]
**Is your feature request related to a problem? Please describe.**

The [standard gettext flags](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html#PO-Files) all use full names without abbreviations.  For example `python-format` rather than `py-format`.  We would like to make _po4a_ automatically add a Markdown flag to the PO files, so that Weblate will automatically add the relevant checks.

Would it be possible to support the name "markdown-text" as a name for this flag?

**Describe the solution you'd like**

Anyway that makes it so that "markdown-text" can be used as a PO flag and do what Weblate's "md-text" currently does.  Even better, Weblate would also use the name "markdown-text".

**Describe alternatives you've considered**

We've considered just using "md-text", but that would make it the only standard PO flag that uses an abbreviation.  And "md" is not clear in many contexts.

**Additional context**

This is something that @uniqx and I could implement if you agree it makes sense. 
 If so, please add this issue to the Linguine project.

**Comment by nijel** [comment]
I think it's hard to bring consistency into this. We also have `rst-text`, do you want to rename it to `restructuredtext-text`?

Introducing aliases might be way to address this. Such would be easy to implement in the flags parsing code:

https://github.com/WeblateOrg/weblate/blob/05b3b2f50273a12c2e2b6ba234f1fbfe504bf1b2/weblate/checks/flags.py#L96-L103

**Comment by eighthave** [comment]
aliases would be fine by me.  I can understand migrating away from `md-text` would be a lot of work.

**Comment by nijel** [comment]
It can be stored in translation files for anybody using Weblate, so breaking existing flags is not really an option.

**Comment by eighthave** [comment]
How about a merge request that implements aliases and adds the "markdown-text" alias?

**Comment by nijel** [comment]
Sounds good.

**Comment by uniqx** [comment]
@nijel what would be the correct way to implement this alias?

I've read through all involved Check classes several times, but I couldn't find a clean way or any hint's on how to implement aliases for flags.

([weblate/checks/base.py](https://github.com/WeblateOrg/weblate/blob/weblate-3.11.3/weblate/checks/base.py), [weblate/checks/markup.py](https://github.com/WeblateOrg/weblate/blob/weblate-3.11.3/weblate/checks/markup.py))

**Comment by nijel** [comment]
IMHO it would belong to weblate/checks/flags.py to the `parse` method. It is already used to skip `fuzzy` flag and it can be extended to handle aliases as well. Rest of the code should not care about it then.
