### ISSUE TITLE
add check and fixup for most common broken Markdown links

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#3649]
**Is your feature request related to a problem? Please describe.**

By far the most common Markdown syntax error that I've seen in translation is broken Markdown links where the translation has space between the `]` and the `(`, for example:
```markdown
[My Home Page] (http://example.com)
```
I think this is related to the machine translation messing up the Markdown syntax.

**Describe the solution you'd like**

This seems like a clear case for a specific check with its own fixup.

**Describe alternatives you've considered**

Another possibility is automatically sanitizing the data when it comes back from the machine translation, but then that won't cover the cases where the translator messes up the Markdown syntax.

**Additional context**

This is something that @uniqx and I will implement if you agree it makes sense.
If so, please add this issue to the Linguine project.

**Comment by nijel** [comment]
The missing links should be already covered by:

https://github.com/WeblateOrg/weblate/blob/05b3b2f50273a12c2e2b6ba234f1fbfe504bf1b2/weblate/checks/markup.py#L244-L265

It might need extension to be more generic and to support fixup.
