### ISSUE TITLE
Do not wrap long lines?

### ISSUE THREAD

**Issue by fisharebest** [WeblateOrg/weblate#365]
PO files generated by weblate wrap long lines.  e.g.

```
#: trans/admin_views.py:267
#, python-format
msgid ""
"Added host key for %(host)s with fingerprint %(fingerprint)s, please verify "
"that it is correct."
msgstr ""
"Clé de l'hôte ajoutée pour %(host)s avec l'empreinte %(fingerprint)s, "
"veuillez vérifier qu'elle est correcte."
```

Is it possible to disable this, e.g. like

```
msgmerge --no-wrap
```

The word-wrap makes it difficult to search for messages when using a text editor.  In this example, you cannot search for "verify that".

Also you cannot do things like this, to search for en_US spellings in en_GB files:

```
grep "^msgstr.*ize" en_GB.po
```

or this, to quickly fix typos in the source code

```
sed -i '^msgid "This is a tpyo/msgid "This is a typo' *.po
```

**Comment by nijel** [comment]
As there still seems to be demand to support this natively, I've just submitted PR to translate-toolkit implementing this: https://github.com/translate/translate/pull/3702

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
