### ISSUE TITLE
optional check/fixup for ensuring URLs in source match URLs in translation

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#3651]
**Is your feature request related to a problem? Please describe.**

On the f-droid.org and guardianproject.info websites, we are localizing the content, but the URLs are the same for all languages.  I have some hack link checkers to make sure that the sorted list of URLs in the source matches the sorted list of links in the translation.  This is obviously not applicable to websites that translate the paths in the URLs.

**Describe the solution you'd like**

An optional check called something like _markdown-untranslated-links_ with a potential fix up that uses a similarity check for the URLs in the translation versus the links in the source.

**Describe alternatives you've considered**

Custom script on our end, but we're close to upstreaming all of our custom checkers to Weblate.

**Additional context**

This is something that @uniqx and I will implement if you agree it makes sense.
If so, please add this issue to the Linguine project.

**Comment by nijel** [comment]
Right now, the remote URLs are not checked because these might be localized:

https://github.com/WeblateOrg/weblate/blob/4c08ec868b5a4484003056563f74dbaa8eed86dc/weblate/checks/markup.py#L259-L265

**Comment by eighthave** [comment]
So @uniqx and I just dug into the existing code.  It looks quite close, the only issue is that this check will mark a string as bad if source and translation have the same link collections, but they are in a different order.  Since the translator might need to reorder the words that are linked in order to write correctly, we propose that this comparison should compare the sorted lists, i.e.:
```python
 return sorted(tgt_anchors) != sorted(src_anchors) 
```
