### ISSUE TITLE
Inconsistency checks raised "false positive"

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#3652]
Hi,,

The inconsistency check feature is nice (it checks translations of the same string across all translations within a project to help me keep the translation consistent, see https://docs.weblate.org/en/latest/user/checks.html#check-inconsistent ).

But I have noticed several times where this feature raised "failed checks" when it shouldn't.

For instance when the same string is available elsewhere but not yet translated:
![Weblate inconsistency checks](https://user-images.githubusercontent.com/1452146/78031199-85162900-7363-11ea-9655-422024e6d44c.jpg)

See other examples here (I won't correct them for the next couple of days):
https://hosted.weblate.org/translate/osmand/main/fr/?q=has:check

Note 1: it looks like there are other issues reported and open on the "inconsistency checks" feature but I'm not sure they are pointing the same bug I'm reporting here.
Note 2: I already reported this bug some years ago #1694 but it may have reappeared ;-(.

**Comment by ldmpub** [comment]
If the following  behavior is the one you want: **raised erros to ask translator to change translation in all components** (even in the one he don't care about, for me iOs) ; please change the button label "use this translation / utiliser cette traduction" with other label already available in weblate "Use this translation for all components / Utiliser cette traduction dans tous les composants"

See these 2 labels yet in Weblate:
https://hosted.weblate.org/search/weblate/?q=+target%3A%22utiliser+cette+traduction%22&checksum=&offset=#

**Comment by ldmpub** [comment]
It looks like the button I suggest to change the label is there:
https://github.com/WeblateOrg/weblate/blob/4596180fec914a50dea478d6b8b488b10d769c68/weblate/templates/trans/other-row.html#L17

`title="{% trans "Use this translation for all components" %}">{% trans "Use this translation" %}</a>`

Maybe the button label is so short that I misunderstood its usage, the toolitp / title is more relevant to understand that by clicking translator will apply this translation to all components.

**Comment by nijel** [comment]
The inconsistency check intentionally fires in case when the string is translated in one component and not translated in other.

UI wise it should be made clear what to do in this case, I'm not sure that changing the button text to longer one will really help.

**Comment by ldmpub** [comment]
Thanks Michal for your quick answer.

I have made some translation improvements in french for strings used in this particular context but I agree with you: "not sure that changing the button text to longer one will really help.".

I don't see yet how to improve this screen layout nor how to add "tips" to guide translators without overloading the screen ;-(.

What I suggest yet is to explain the usage of this button in the following help page: 
https://docs.weblate.org/en/latest/user/checks.html#inconsistent (and indicate that the check is raised even for empty strings => it's a quick way to translate them).

**Comment by ldmpub** [comment]
Hi,

I confirm there is an issue on theses checks (false positive), see for instance https://hosted.weblate.org/translate/weblate/master/fr/?q=check:inconsistent 

Despite all translation strings are the same among components, an inconsistent error is still raised ;-(.

![Weblate inconsistency checks  2jpg](https://user-images.githubusercontent.com/1452146/78243064-5de66580-74e3-11ea-8ced-dcabee9c18f3.jpg)

**Comment by nijel** [comment]
Probably related to automatic translation which did the change: https://hosted.weblate.org/translate/weblate/website/fr/?checksum=1877b22f8fdbbe4d#history

**Comment by ldmpub** [comment]
Thanks for the fix and for the documentation update ;-).
I will report new issue if I noticed some other strange behaviors around these "wrong raised string checks" (like done here and in the past).

Thanks again for the global quality of Weblate project and app!
