### ISSUE TITLE
Missing user/author URL in translation change

### ISSUE THREAD

**Issue by valeriocos** [WeblateOrg/weblate#3659]
**Describe the bug**
When fetching data from https://translations.documentfoundation.org/api/projects/libo_help-6-3/changes/, the user and author attributes don't contain the URLs of the related object (as stated in the documentation https://docs.weblate.org/en/latest/api.html#get--api-changes-(int-pk)-). The main limitation is that it isn't possible to navigate from a change to the corresponding profile information.

**To Reproduce**
1. Go to https://translations.documentfoundation.org/api/projects/libo_help-6-3/changes/
2. All entries have numeric or null user/author attributes (I don't know if the other null values are correct or not)

```
{
            "unit": null,
            "component": null,
            "translation": null,
            "dictionary": null,
            "user": 2, <----------------------------
            "author": 2, <-------------------
            "timestamp": "2019-12-12T07:01:18.078407Z",
            "action": 50,
            "target": "",
            "id": 429911,
            "action_name": "Created project",
            "url": "https://translations.documentfoundation.org/api/changes/429911/"
        },
```

**Expected behavior**
User and author attributes should be URLs pointing to the user/author profile

**Comment by nijel** [comment]
@SaptakS this probably makes sense to implement together with https://github.com/WeblateOrg/weblate/issues/3607

**Comment by SaptakS** [comment]
@nijel exactly. I was planning to do the same.
