### ISSUE TITLE
Make character limit less restrictive

### ISSUE THREAD

**Issue by Fat-Zer** [WeblateOrg/weblate#3662]
Currently if a translated message is hitting character limit in the text input, weblate prevents new character from being input. It's quite inconvenient if some restrictive string length is defined and you are trying to fit translation into into it. Basically, you just have to copy the translated text to external text editor or a comment field, because you need extra space to shuffle words around or rephrase the translation.

I suggest (instead of forbidding input of extra characters) to mark the word indicator with red (and may be bold) if the translation length is exceeded and refuse to save it until the length fits.

**Comment by nijel** [comment]
Having something more fancy requires using some better editor, there are already several issues related to this, see https://github.com/WeblateOrg/weblate/issues/2964#issuecomment-607756032

**Comment by comradekingu** [comment]
I think there should be hard and soft limits.
When the source is 168 of 150 chars, it makes no sense to hard-limit the translation to 150.
Was possible to copy source to get 168 to play with, but all in all frustrating to work with.

**Comment by comradekingu** [comment]
I often see it being more than 500. Does that mean it is cut off at 500?

**Comment by Fat-Zer** [comment]
AFAIK, yep... Google Play and F-droid just chop off the rest of the string. But I haven't found any related docs, so I'm not really sure... If it's crucial, I would rather double check...

**Comment by nijel** [comment]
See https://github.com/WeblateOrg/weblate/issues/1525 for discussion on Google Play limits.
