### ISSUE TITLE
Target state of translation being ignored

### ISSUE THREAD

**Issue by paulIVRE** [WeblateOrg/weblate#3663]
I push an xliff file with translations marked with state "needs-translation". Yet in weblate bu translations are marked as 100% complete and none marked as needs editing or anything.

**To Reproduce**
1. Add entry like this to xliff file:
`      <trans-unit id="SETTINGS">
        <source>Settings</source>
        <target state="needs-translation">Einstellungen</target>
        <note from="description">Can you make this about 8 characters long so fits on button?</note>
      </trans-unit>
`
Observe that Weblate thinks all translations are done. I think the problem may be in when something was translated and then is marked as needs translation again.

**Expected behavior**
If I push an xliff file with something marked as "need-translation" should be shown as needs editing in weblate.

**Comment by nijel** [comment]
It is indeed supposed to work this way. What Weblate version do you use?
