### ISSUE TITLE
Add a question when removing users from the project

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#3667]
**Is your feature request related to a problem? Please describe.**
With big number of users on the translation project, it’s quite tricky to hit the right *red bin* button.

**Describe the solution you'd like**
Ask a question *Do you want to remove `username` from this project?* With yes/no

**Comment by GriffinMeltzer** [comment]
I'd like to work on this too.

**Comment by nijel** [comment]
@GriffinMeltzer I've assigned you, thanks.

**Comment by GriffinMeltzer** [comment]
Any ideas on where to find this in the code base?

**Comment by nijel** [comment]
The HTML code is here: https://github.com/WeblateOrg/weblate/blob/master/weblate/templates/manage-access.html

**Comment by Anubhav652** [comment]
I'd like to work on this.

**Comment by nijel** [comment]
@Anubhav652 You're welcome, I've just assigned you the issue.

**Comment by comradekingu** [comment]
@nijel That appears to be a spamtoberfest account.

**Comment by Anubhav652** [comment]
> 
> 
> @nijel That appears to be a spamtoberfest account.

It's not

**Comment by comradekingu** [comment]
I clicked around enough to notice, but then I had lost the thread. Sorry for implying it was.

**Comment by Anubhav652** [comment]
I should implement this something along the lines of templates/trans/delete-form.html right?

**Comment by nijel** [comment]
I don't thing typing the username is needed here, simple modal dialog would be okay here. Something similar is there when deleting translation memory entries:

https://github.com/WeblateOrg/weblate/blob/700594508f17e5c80474c0b71b1d343db3471f44/weblate/templates/memory/index.html#L74-L89
