### ISSUE TITLE
URLs are case sensitive, causing 404

### ISSUE THREAD

**Issue by TobiGr** [WeblateOrg/weblate#3668]
**Describe the bug**
URLs in the latest Weblate-4.0dev hosted version are case sensitive causing 404 responses.
I did not figure out if this applies to project names only or if all parts of a URL are affected.

**To Reproduce**
1. Go to https://hosted.weblate.org/engage/newpipe/  :arrow_right:  works
2. Go to https://hosted.weblate.org/engage/NewPipe/ :arrow_right: 404

**Expected behavior**
URLs should be case insensitive

**Server configuration and status**
Hosted weblate version (weblate-4.0dev as of 03/04/2020)

**Comment by nijel** [comment]
The URLs probably were not case-sensitive before just because of using MySQL, which is case-insensitive by default.
