### ISSUE TITLE
Translation progress bars not filled in completely

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3669]
![bilde](https://user-images.githubusercontent.com/13802408/78423763-38c73380-7658-11ea-9fc9-e74dd902647d.png)

![bilde](https://user-images.githubusercontent.com/13802408/78423835-ac694080-7658-11ea-9d84-ad43c6a4e0e4.png)

https://hosted.weblate.org/languages/nb_NO/givemelyrics/
"Extra" has the problem
"Translations" does not

**Comment by nijel** [comment]
The last part of the progress bar are not translated strings, so that's expected for not completed translations.

**Comment by comradekingu** [comment]
Yes, but there aren't any untranslated strings in them.
This is my problem trying to keep an overview of which projects are finished and which ones aren't.

**Comment by nijel** [comment]
Okay, I thought you are talking about XBackBone. Looks like rounding issue - the widths are integers.

**Comment by nijel** [comment]
This might be related to https://github.com/WeblateOrg/weblate/issues/3730, but it's more likely it is a different issue here.

**Comment by nijel** [comment]
Seems like this is no longer happening. Besides fixes in #3730 there was also 3e6f4860a56b144963c4c32db3dd337bc1714470 addressing related issues.
