### ISSUE TITLE
Only some translation progress bars are rounded

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3670]
https://hosted.weblate.org/projects/givemelyrics/extra/nb_NO/

![bilde](https://user-images.githubusercontent.com/13802408/78423941-87290200-7659-11ea-8586-4169b61c9249.png)
vs
![bilde](https://user-images.githubusercontent.com/13802408/78423943-91e39700-7659-11ea-82ad-ca72cfb167ae.png)

Intentional?

**Comment by nijel** [comment]
Yes, it's intentional. Rounding on the small bar didn't look well.
