### ISSUE TITLE
Default GitHub repo configuration doesn’t create PR

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#3671]
**Describe the bug**
Default GitHub repository configuration of translation project in not creating pull requests

**To Reproduce**
1. Set up a translation profile
2. In its VCS configuration, left `Repository push URL` empty
3. Try to push changes to the remote repository.

**Expected behavior**
The Default GitHub repository configuration of translation project is creating PR in the remote repo when `Repository push URL` field on https://hosted.weblate.org/settings/<project>/<component>/#vcs is empty.

The `Push` button on https://hosted.weblate.org/settings/<project>/<component>/#repository works when no push URL is set up.

**Comment by nijel** [comment]
Setting of push URL is currently required even though it won't be used in this particular case.

The logic for enabling push is currently pretty simple:

https://github.com/WeblateOrg/weblate/blob/b19d4bd0834411ec5963a0f835f48730238466e1/weblate/trans/models/component.py#L685-L688

It should also consider configured VCS backend and query it whether it is okay to push even with empty push URL.
