### ISSUE TITLE
Linked GitHub repo is not pushing

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#3672]
connected to https://github.com/WeblateOrg/weblate/issues/3671

**Describe the bug**
When *Component Discovery* is set up, linked repo/component changes are not pushing to the remote repo. New files are created, but updated are not pushed.

**To Reproduce**
1. Try push changes made in https://hosted.weblate.org/projects/jitsi/languages/cs/ to https://github.com/jitsi/jitsi-meet/pull/5664

**Expected behavior**
When `Push` to the remote repo, all the changed and new files are included in the created PR.

**Comment by nijel** [comment]
The mentioned pull request contains changes in both lang/languages-*.json and  lang/main-*.json, so it seems to have worked as expected. In case some particular changes were not present, they might not yet been committed. Weblate does delay committing to avoid excessive amount of commits, see https://docs.weblate.org/en/latest/admin/continuous.html#lazy-commits

The good practice when merging pull request is to force committing all pending on Weblate side first. To avoid potential conflicts, it is also good idea to lock the repository while doing this.

On command line using [wlc](https://docs.weblate.org/en/latest/wlc.html), it might look as :

```sh
# Lock from translations
wlc lock 
# Commit and push pending changes
wlc push
# Merge pull request
hub merge ....
# Push changes to upstream repo
hub push
# Unlock the component
wlc unlock
```
