### ISSUE TITLE
Search / Criteria"Exact" overwrites 'Add" button

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#3675]
The search is a great feature (quick to fill, powerfull  - with advanced criterias - and results are fast and reliable) but I have noticed an issue in the layout : "Exact" (which seems to be an untranslatable string yet) overwrite the "Add" button (at least in french, the full french label is "Ajouter"); see:  ![Search](https://user-images.githubusercontent.com/1452146/78504660-e0368a00-776e-11ea-9ede-ce77263e4107.jpg)

page https://hosted.weblate.org/projects/weblate/master/#search

**Comment by nijel** [comment]
@SaptakS Can you please take a look at this?

**Comment by nijel** [comment]
It's not translatable only because strings were not yet extracted, but it's properly marked for translation. But I've added context to the string in 5fa8327280.

**Comment by SaptakS** [comment]
@nijel on it.

**Comment by ldmpub** [comment]
Fix is OK. Thanks.
