### ISSUE TITLE
Femine and neuter forms

### ISSUE THREAD

**Issue by Kyuuu** [WeblateOrg/weblate#3676]
**Is your feature request related to a problem? Please describe.**
If you have a game in which you give the possibility to select player's gender - in some languages you need to create separate keys for males' and females' sentences.

**Describe the solution you'd like**
In some languages like Polish or German(?), verbs, adjectives, and pronouns are written differently if sentences are about women and differently about men. It would be useful if we will be able to use the same solution as plurals have.

The translator should have the possibility to add feminine form every time he needs to (it is sometimes possible to create a sentence that sounds natural and does not indicate gender).

**Describe alternatives you've considered**
//

**Additional context**
![image](https://user-images.githubusercontent.com/33127074/78525069-60dca100-77d6-11ea-8290-0512644cbd10.png)
![image](https://user-images.githubusercontent.com/33127074/78525079-676b1880-77d6-11ea-9cea-d1fe1238d2aa.png)
![image](https://user-images.githubusercontent.com/33127074/78525092-6b973600-77d6-11ea-8b5d-078c67672ddd.png)

**Comment by nijel** [comment]
This needs to be addressed at program and translation file format level first - the program has to somehow include the gender when handling the translations, and they have to be somehow stored in the file.

I do not know any format supporting it the way you describe. In most cases, it is handled by separate strings for each form and these can be grouped in Weblate using [Shapings](https://docs.weblate.org/en/latest/devel/translations.html#shapings) (which will be probably renamed for the next release, see https://github.com/WeblateOrg/weblate/issues/3484).

Such translations can be for example natively handled by [Fluent](https://projectfluent.org/) (currently not supported by Weblate, see https://github.com/WeblateOrg/weblate/issues/1926), but it is done using expressions inside the string.

**Comment by comradekingu** [comment]
Would need to be worded differently to prevent non-language.
