### ISSUE TITLE
Subversion svn+ssh protocol doesn't use ssh key

### ISSUE THREAD

**Issue by rattkin** [WeblateOrg/weblate#3678]
Subversion protocol svn+shh doesn't try the publickey method

I've tried to use the url like we use it in other svn clients, eg:
svn+ssh://username@svnserver.example.com/repository/

Weblate connects to the svn server via ssh, but doesn't try to use the ssh key (publickey method):
```
debug1: Client protocol version 2.0; client software version OpenSSH_7.9p1 Debian-10+deb10u2
debug1: match: OpenSSH_7.9p1 Debian-10+deb10u2 pat OpenSSH* compat 0x04000000
debug1: Local version string SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u1
debug1: permanently_set_uid: 106/65534 [preauth]
debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
debug1: SSH2_MSG_KEXINIT sent [preauth]
debug1: SSH2_MSG_KEXINIT received [preauth]
debug1: kex: algorithm: curve25519-sha256 [preauth]
debug1: kex: host key algorithm: ecdsa-sha2-nistp256 [preauth]
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
debug1: rekey after 134217728 blocks [preauth]
debug1: SSH2_MSG_NEWKEYS sent [preauth]
debug1: expecting SSH2_MSG_NEWKEYS [preauth]
debug1: SSH2_MSG_NEWKEYS received [preauth]
debug1: rekey after 134217728 blocks [preauth]
debug1: KEX done [preauth]
debug1: userauth-request for user username service ssh-connection method none [preauth]
debug1: attempt 0 failures 0 [preauth]
debug1: PAM: initializing for "username"
debug1: PAM: setting PAM_RHOST to "10.10.50.121"
debug1: PAM: setting PAM_TTY to "ssh"
debug1: userauth-request for user username service ssh-connection method password [preauth]
debug1: attempt 1 failures 0 [preauth]
Failed none for username from 10.10.50.121 port 44768 ssh2
debug1: userauth-request for user username service ssh-connection method password [preauth]
```
This is only when I set the Version control System as "Subversion" in the "Add new translation component" dialog. When I set i to "Git", the ssh connection proceeds with publickey method.
`debug1: userauth-request for user progwart service ssh-connection method publickey [preauth]`

What am I setting wrong? Seems like a bug to me, but I'm not sure.

**Comment by nijel** [comment]
I think it should be addressed by https://github.com/WeblateOrg/weblate/pull/3679, it would be great if you could test it.

**Comment by rattkin** [comment]
I installed vim in the docker
I edited the file vim /usr/local/lib/python3.7/dist-packages/weblate/vcs/git.py
(please let me know if there's an easier way)
I added the lines in your commit https://github.com/WeblateOrg/weblate/pull/3679/commits/c89309aaf5888f3218cb28cd3c3031e75aa96d43

I did not see any change. Do I need to restart something?

**Comment by nijel** [comment]
Yes, you need to restart uwsgi and celery, both running under supervisor inside docker.

**Comment by rattkin** [comment]
Thank You. I tried restarting those processes. No change. I even restarted the docker stack. no change.

**Comment by nijel** [comment]
With container restart your edits will be gone.

Anyway I've found simpler way to do this and changed the pull request now.

**Comment by rattkin** [comment]
Thank you. It uses the ssh key now and communicates with svn.
I get another error:
![image](https://user-images.githubusercontent.com/910080/78643560-b8e9d500-78b4-11ea-9208-d2a65d0cabb7.png)
my repository layout seems standard.

**Comment by nijel** [comment]
Try using just myorg-test as branch name.
