### ISSUE TITLE
All accented characters being removed

### ISSUE THREAD

**Issue by di** [WeblateOrg/weblate#3683]
**Describe the bug**
Automated updates from Weblate are stripping all accented characters from translations

**To Reproduce**
For example, https://hosted.weblate.org/translate/pypa/warehouse/pt_BR/?&offset=3 shows no additional edits, but the originally submitted translation differs from the "current" translation, which has no accented characters.

This is happening for all languages in our repository with updates from weblate in the last ~24 hours: https://github.com/pypa/warehouse/pull/7742/commits/4d829ce66583845c1a46f2898b593f2f6191eaaa

**Expected behavior**
Translated strings contain special characters.

**Comment by nijel** [comment]
The commit you reference is from msgmerge and it (mostly) seems to remove plurals, which looks okay as they were removed from the POT file as well. I don't see anything related to accents removal there.

The actual broken commit seems to be https://github.com/pypa/warehouse/pull/7742/commits/f54f1d11fd0cb9b6e8698377d87599de5f266ec1#diff-b7afcece84d574e5f7f3231dcf12b6fa

Problem might be related to https://github.com/pypa/warehouse/commit/d203010211e8a4daed273c7c655ff2bba03ecf37 which removed headers from the PO files, I'm not sure how msgmerge behaves in this case, but it definitely should fail and not silently corrupt the files.

**Comment by di** [comment]
Got it, makes sense. It sort of begs the question, why does `pybabel update` take an `--omit-header` flag if it's going to produce `.po` files that are unusable by msgmerge? But that's probably off-topic for this repo.

Thanks for the fast reply!

**Comment by nijel** [comment]
I can not reproduce the corruption with msgmerge, but maybe I'm doing something wrong. It doesn't fail with error, but it emits tons of warnings like:

```
warehouse/locale/pt_BR/LC_MESSAGES/messages.po:5353: warning: The following msgid contains non-ASCII characters.
                                                              This will cause problems to translators who use a character encoding
                                                              different from yours. Consider using a pure ASCII msgid instead.
                                                              If you have skills in Python, ElasticSearch, HTML, SCSS, JavaScript, or SQLAlchemy then skim our <a href="%(getting_started_href)s" title="%(title)s" target="_blank" rel="noopener">"Getting started" guide</a>, then take a look at the <a href="%(issue_tracker_href)s" title="%(title)s" target="_blank" rel="noopener">issue tracker</a>. We've created a <a href="%(good_first_issue_href)s" title="%(title)s" target="_blank" rel="noopener">'Good first issue'</a> label – we recommend you start here.
warehouse/locale/pt_BR/LC_MESSAGES/messages.po:5353: invalid multibyte sequence
warehouse/locale/pt_BR/LC_MESSAGES/messages.po:5353: invalid multibyte sequence
warehouse/locale/pt_BR/LC_MESSAGES/messages.po:5353: invalid multibyte sequence
warehouse/locale/pt_BR/LC_MESSAGES/messages.po:5353: invalid multibyte sequence
warehouse/locale/pt_BR/LC_MESSAGES/messages.po:5353: invalid multibyte sequence
warehouse/locale/pt_BR/LC_MESSAGES/messages.po:5353: invalid multibyte sequence
```

I've found exactly this in the log as well, maybe it would be worth checking msgmerge output for warnings...

**Comment by nijel** [comment]
I think Weblate should reject the update once there is any warning.
