### ISSUE TITLE
Add ``has:context`` search type

### ISSUE THREAD

**Issue by Mingun** [WeblateOrg/weblate#3684]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to see all messages with context no matter which context really are.

**Describe the solution you'd like**
Add search type ``has:context`` similar to existing ``has:plural`` or ``has:comment``. Search with this type should find all messages which have settled context (has ``msgctxt`` field in po-file).

**Comment by nijel** [comment]
The has lookup is defined here:

https://github.com/WeblateOrg/weblate/blob/2c412409550d26b231423b752d8dca45f674b7bc/weblate/utils/search.py#L251-L269
