### ISSUE TITLE
Subversion Could not update repository: fatal: 'origin/repository' is not a commit and a branch 'branch' cannot be created from it (128)

### ISSUE THREAD

**Issue by rattkin** [WeblateOrg/weblate#3689]
I can't create a Subversion backed component:
![image](https://user-images.githubusercontent.com/910080/78654491-db83ea00-78c4-11ea-8b25-d0d74bee36fc.png)

I get this error message: Could not update repository: fatal: 'origin/myorg-test' is not a commit and a branch 'myorg-test' cannot be created from it (128)

Does the 'Repository branch' refer to an existing branch with code to translate? That would make sense to me, but that that branch can not be created since it already exist, why is it trying to create the branch?

Or is it new branch to be created? How do I then specify there is the translatable file?
Didn't find anything in the manual about it, sorry. I tried to read https://docs.weblate.org/en/latest/vcs.html several times.

This is our repository layout:
![image](https://user-images.githubusercontent.com/910080/78654336-ab3c4b80-78c4-11ea-9e5e-008549ede7d3.png)
(the url @svn / @svn.example.com is different because some clients use tortoiseSVN)

I tried specifying existing branch as well as new branch but I can't get it working.

**Comment by nijel** [comment]
As your repo is not really using "standard layout" (see https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-svn.html#_commands), it won't work with specifying branch. Try including the branch name in the repository URL and leaving branch empty.

**Comment by rattkin** [comment]
Thank You this is it!
I don't know git.

**Comment by nijel** [comment]
This is not really a Git behavior, but more a Weblate one. To have the setup simple, we do not expose the stdlayout flag and try to detect it automatically, what can lead to some confusion.
