### ISSUE TITLE
change from linked component to master component failed

### ISSUE THREAD

**Issue by jzahradn** [WeblateOrg/weblate#3696]
Hi,
We have master components and also linked components in certain project. I need to change these linked components, remove the links and save them with configuration of their master components.
In most cases, it can be done without errors. But some components cannot be saved. After approximately one minute error appear:
The server had serious problems serving your request. Trained monkeys are en-route fixing the issue.

What I exactly do:
1. look at linked component to see to which master component it is linked
2. open the master component, and copy parameters 'Source code repository','Repository branch' and 'Repository push URL'.
3. open linked component, change current link to master component in parameter 'Source code repository' to git repository from step two, add 'Repository branch' and 'Repository push URL' values from step two. Now the configuration of both components equals in these three fields.
4. I save the settings and sometimes get the error.
Do you know why this happens?

I have tried to look at the log, but in /var/log/weblate/ the last records are from January, maybe we have problems with logging too.

Thank you
Regards
Jan

**Comment by nijel** [comment]
On the error, whoever is configured in ADMINS will get a notification with a traceback. It will be shown in the logs as well. Without that, it's nearly impossible to diagnose what went wrong.

**Comment by jzahradn** [comment]
OK, I decreased logging level from CRITICAL to ERROR and I received the email. I will attach it here.
[weblate_error.txt](https://github.com/WeblateOrg/weblate/files/4455259/weblate_error.txt)

**Comment by nijel** [comment]
Seems like locking issue - is there another operation on the component? Like repository update?

**Comment by jzahradn** [comment]
I don't think so. I tried it many times in various date and time and the result is always the same. And regarding the error message: "The file lock '/var/www/weblate/data/vcs/xy/easy-config-user-interface.lock' could not be acquired.": I took a look at the server and the lock file looks like it does not differs from another lock files - see the console screenshot.
In these certain components: 'Easy Config - Common Library' (the linked component) and 'Easy Config - User Interface' (the master component to which the Common Library is linked), I remember the error message was initially different. Both components, the linked one and the target/master one had the same values in field 'Translation flags': add-source-review,add-review. Again, the linked component has this value and the master component has this value too. I kept this values untouched in both components. However when I changed values 'Source code repository', 'Repository branch' and 'Repository push URL' in the linked component with values of the master component I got the error: Invalid translation flag: "add-source-review" - see the screenshot. Since that time, I am getting the timeout/lock errors.

**Comment by jzahradn** [comment]
![IMG_20200414_212322](https://user-images.githubusercontent.com/55885376/79330049-2337f080-7f19-11ea-863d-1dc439c399db.jpg)
![wbl_transl_flags](https://user-images.githubusercontent.com/55885376/79330055-2501b400-7f19-11ea-9bf8-6ad18c650f11.png)

**Comment by nijel** [comment]
These flags do not exist anymore, they were replaced by addons in 56960fb11591d982382ccce5f40d365c1a968024 (more than two years ago, released in Weblate 2.19). There was migrating taking care of this on upgrade, so I wonder how it's possible that they stayed here. Anyway they are no longer supported, so removing them will address this.

**Comment by jzahradn** [comment]
When I removed the flags and changed the repository settings at once, I received the same error. So I decided to remove the flags first. All components was saved successfully without flags. However, since this edit, new icon "updating translation component" appeared on the seven components that was changed. After one hour elapsed, nothing was changed on them, the 'update icons' are still here on the components. Should I:
- wait until the evening to complete the update on the components?
- abort the updates?
- restart Weblate?

Other words, if the icons won't disappear until this evening, I will restart the Weblate. Would it be better to abort the update berofe the restart? I am not sure in what states are currently the components. I think the updates should be already finished and something is going wrong.

**Comment by nijel** [comment]
Is Celery running? Can you check it's logs for errors?

**Comment by jzahradn** [comment]
I was waiting until this morning and updating icons disappeared. So the components were updating, but it takes many hours to complete. I did not expect that. I have checked translation flags of the components and the field was empty. So I restarted Weblate including server and then I have tried to do the component repository change. It returned the same timeout error like before.
Last week I upgraded Weblate from version 3.11. to 3.11.3 - just executed the upgrade commands without changing anything in the configuration (there were no version specific upgrade notes between these versions). The upgrade was successful. However, probably there is something wrong with the Celery since the upgrade, in performance report I have found:
weblate.E009	The Celery tasks queue is too long, either the worker is not running or is too slow.
weblate.E019	The Celery does not process tasks or is too slow in processing them.
I am not very familiar with Celery, please how can I start it?

**Comment by jzahradn** [comment]
It seems there is some problem with celery service indeed:
![weblate_celery](https://user-images.githubusercontent.com/55885376/79467552-28bb3680-7ffe-11ea-8927-9c650d8bf58e.png)

**Comment by jzahradn** [comment]
Our disk is probably full. I will let you know when I solve this.

INFO master-server-7-3/wsf-framework-contents-ui73: updating repository
ERROR Could not update the repository: RepositoryException: fatal: write error: No space left on device
fatal: index-pack failed (128)
ERROR Could not update the repository: RepositoryException: fatal: write error: No space left on device
fatal: index-pack failed (128)

**Comment by jzahradn** [comment]
I have resolved the disk problem. Celery service is working without any errors. However I still cannot remove the link on the component and save it as master component. Again - timeout error. The referred lock file exists with standard permissions like other lock files. More detail in new attachments

**Comment by jzahradn** [comment]
[20200417_email1.docx](https://github.com/WeblateOrg/weblate/files/4492818/20200417_email1.docx)
[20200417_email1.txt](https://github.com/WeblateOrg/weblate/files/4492819/20200417_email1.txt)
[20200417_celery.txt](https://github.com/WeblateOrg/weblate/files/4492820/20200417_celery.txt)
