### ISSUE TITLE
string that cannot be translated/keeps reappearing

### ISSUE THREAD

**Issue by ce-4** [WeblateOrg/weblate#3699]
The osmand project has a string that cannot be translated

It gets re-fixed every couple days and seemingly contains a wrong snippet of the source xml again shortly after:
https://hosted.weblate.org/translate/osmand/main/de/?checksum=7bbdb188d99bc29e

Reproduction is easy: just fix the above to one of the recent fixed strings and see.

Expected: Strings gets translated and stays translated correctly.

Original english string:
`<u>Online OSM</u> map classification with images.`

Wrong german text that keeps reappearing, note the surrounding xml fragments from the osmand source xml. Looks like a parser error:
`string name="route_descr_current_location">Aktueller Standort</string`

Correct german string:
`<u>Online OSM</u> Kartenklassifizierung mit Bildern`

**Comment by nijel** [comment]
Seems like https://github.com/translate/translate/pull/3951 ... I will deploy that fix.

**Comment by ce-4** [comment]
Thanks for the quick fix!
