### ISSUE TITLE
Source string tracking

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#370]
It seems that we should track source strings as well to be able to associate some metadata with them:
- issue #123 - string priorities
- issue #241 - first string occurence
- issue #250 - providing more context to translators
- review of source strings (proofreading English)
- better view of source string checks

**Comment by yarons** [comment]
Where is it and how can I use this feature?
I like what you did with WebLate, good job!

**Comment by nijel** [comment]
You can browse source strings:

https://hosted.weblate.org/projects/weblate/master/source/review/?type=all

All information is also available while translating in source information box:

https://hosted.weblate.org/projects/weblate/master/cs/translate/?checksum=0ebe3484b6d6806e25a78d4f4cb85f21
