### ISSUE TITLE
Repetition check

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3702]
Some platforms/tools have checks for repetition, which is the error that happens most often.

When something is very complex, it is easy to stop, think, and then carry on from the word already put down onwards. It can also happen when rewriting a sentence, ending up with two parts that share a repeated word in its midst.

For example this this is an example of a repeated word.

Example and example, fine. "This this" etc. is almost always an error.
If not an outright error, it is often best avoided, so quality would improve a lot overall with a check that (in most languages) has very few false positives.

**Comment by nijel** [comment]
Should be easy to implement, for example using https://www.oreilly.com/library/view/regular-expressions-cookbook/9780596802837/ch05s08.html

**Comment by flosincapite** [comment]
Hi, I'd be interested in taking this on. Where should this check live? What are the input and output? For example, should this check simply report that there is a (probably unintentional) repetition, or should it attempt to rectify the repetition?

**Comment by nijel** [comment]
It should live in weblate.checks, see ecbace66a021dafaf8c15d73b63a688762129036 for example of adding a new check code.

**Comment by flosincapite** [comment]
I'm implementing the regex check, but I'd like to raise the relevant linguistic issues below so I understand the use case better.

~

Reduplication is common in a fair number of languages. For example, in Persian, one way to say "very big" is by saying "big" twice [1]:

بزرگ بزرگ

So we might think that we can enable this check only for content words, or only in certain languages. But in English, I can say "very very" (a reduplicated function word) as an intensifier. So, while "this this" is almost certainly an error, it's difficult to develop a heuristic (e.g. "no reduplicated function words") that applies across the board.

[1] There is actually a pronounced morpheme between these two (it's "bozorg-e bozorg"), but, orthographically, it's just a repeated token.

**Comment by flosincapite** [comment]
My in-progress PR is here [1].

Can someone indicate what the preferred way to test a module that relies on labile data would be? I tried to dependency-inject the relevant data when testing but DeepSource doesn't seem to like me messing with function signatures in that way.

[1] https://github.com/WeblateOrg/weblate/pull/3797

**Comment by flosincapite** [comment]
It also looks like my change decreases coverage in some unrelated (?) files. I'll try to figure out what's going on there, but any guidance will be appreciated :).

**Comment by flosincapite** [comment]
A couple of questions.

I'm seeing failures in the Distribution/ tests related to Selenium's webdriver. How can I run these tests locally to see whether that failure occurs at HEAD?

**Comment by nijel** [comment]
@flosincapite The coverage is collected during the builds, so it might take some time until it's fully calculated. Once that is done, there should not be any changes in the unrelated code. The test failure was discussed and resolved in https://github.com/WeblateOrg/weblate/issues/3812. Next time please discuss such things at the pull request, because it really doesn't belong here, thanks :-).
