### ISSUE TITLE
Testresults for new feature "harmonize" quality gate

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#3705]
This issue has been started to collect test results for "harmonize" quality gate #3270 

## Configuration

- Test sources: https://gitlab.com/rhofer/translation-test
- Test Project: https://hosted.weblate.org/projects/test-harmonize/
- `template.json` is configured as intermediate language
- `en.json` is the base language, editable
- `de.json` is a test-translation

## Tests

**Sort order of strings (Nearby strings)**
- [ ] (improve): English is sorted according occurrence in template, but German is sorted according occurrence in English. This makes it hard to compare, where `en` term might be at position 1 but `de` term to be found at pos 237, especially when plug-in is sorting alphabetically. Please sort any language only according one file (key-order donator):
  - If intermediate language is configured, sort according this for any language
  - If intermediate language is not configured, sort according base language set for any further language

**Review states / Q-gates**
- If source (`en`) has never been "translated" yet from intermediate language (`template`), then the target (`de`) dialogue for this string shows:
  - [x] (ok) String is locked, cannot be translated in `de`
  - [ ] (improve) **Source is shown as "English" but provides the string from `template`**. This is puzzling since translator wonders why translation is locked but source is provided and Developer English should not be exposed. Please **strictly show source strings from source file only** ( in this case `en.json`). If source isn't translated yet, then show empty string. (if source is empty, then it is immediately clear why it can't be translated).
- Source (`en`) has been translated:
  - [x] (ok) If string status is set back to Needs editing or string is simply deleted, then also translation in target language is locked again. As information (read-only) it shows, how it previously has been translated

**Machine Translation and Translation Memory**
When intermediate language is specified (Developer English), then the actual English is becoming a translation itself. For the further translations, English is the source, yes, but technically in context of `template` , `en` is a translation. I see the following needs for "look-up support" on source language:
- Are there strings from intermediate language which are similar/ same as the current in focus,  either coming from this component or another component? >> look-up for string in intermediate language
  - Assuming that developer picked the string "About", the look-up may provides that it occurs several times, some times it becomes "About" in `en`, sometimes it becomes "Information". On one hand, this allows to better decide whether "About" or "Information" is the better fit, on the other hand this may gives hints that even across all `en` the terms are not well harmonized.
- If I intend to use a string for the proper English, did I already use it some where else as proper English, is it in this component or another? >> look-up for string in English within and accross components
  - Given the example above, having "About" as input from developer, I'd like to go for "Information" as proper English. Before doing so, I quickly want to look-up, where "Information" is in use within this component or across others on the source language "English"

These are efficiency use-cases, I'd expect the translator working in "harmonize" step is receiving support by the tool. The first point might be simply provided by current Machine Translation Tab, to allow look-up on intermediate language. The second point is more of a search as we have in the Translation Memory Tab, where it is intended to enter a string to seek for on the source language (here not the intermediate language) and to provide results for the source from the source. This might become an enhancement in the MT Tab to provide an alternative input box as source for MT look-up (instead of automatically taking the source string provided).

Translation Memory should not be used in context of intermediate language. This would mean, that TM is enriched with DeveloperEnglish to English pairs, what is not meaningful.

- automatic translation support in harmonize?

**Comment by nijel** [comment]
I've just fixed issue in cleanup addon you've hit, see 1ff9eae. The fix will be deployed tonight.

**Comment by rhofer** [comment]
testing still in progress...

Upfront, I tried to provide some feedback, what was quickly obvious to me and/or where I see major short comings.

With #3270 there is on bullet point in the Requirements sections:

> - Template based creation of `en` shall be supported by built in MT

I tried to depict more what majorly is expected with the feedback under **Machine Translation and Translation Memory**

**Comment by nijel** [comment]
> Source is shown as "English" but provides the string from template. This is puzzling since translator wonders why translation is locked but source is provided and Developer English should not be exposed. Please strictly show source strings from source file only ( in this case en.json). If source isn't translated yet, then show empty string. (if source is empty, then it is immediately clear why it can't be translated).

I was considering this as well, but I thought this is the least confusing option in the end:

* Not showing the string at all
    * Would produce confusing overall state as there would be fewer strings in translations than in source
    * Would lead to performance penalty when "translating" the English string - it would have to be added to all languages.
    * It would behave differently when there is a new source string and when there is changed source string - in first case the string would not be present, in second it would be preset as read only
* Showing with empty source string
    * People would think this is bug in Weblate as empty source string doesn't make much sense to display
* Showing intermediate source string
    * It might not be the final source string
    * The string is read only and not being translated, so it should not matter much

Maybe better explanation why the string is read only would help?

**Comment by rhofer** [comment]
@nijel Many thanks for this explanation. Yes, you're right, showing the intermediate string might be the best case then. Besides the `read-only` flag an additional remark could help:
- negative formulation: *source not yet approved*
- positive formulation: *source in review*

Would you also think about something like this?

**Comment by nijel** [comment]
Yes, added in ea9f05c424d5ac780589e8c394655490a97e626f.

**Comment by nijel** [comment]
Strings ordering fixed in https://github.com/WeblateOrg/weblate/commit/ec70c1ef530250adcf841d66566e894ea3407a93

**Comment by rhofer** [comment]
@nijel Many thanks for the fixes. As you closed this issue, how/where can we follow up on the "look-up support" mentioned above and outlined in the *Machine Translation* section?

**Comment by nijel** [comment]
Just file new one, preferably one problem per issue, so that it can be easily tracked.

I've addressed some of the suggestions on the machine translation in  a052743, but I think more changes will be neeed.

**Comment by rhofer** [comment]
Just saw it on hosted.weblate.org and I definitely agree to keep one request per issue 👍 .
I'd propose to take it as is for the moment, collect some experience and give feedback on another issue, e.g. with #3626 .

Many thanks again.
