### ISSUE TITLE
Ability to set "parent message" for commit via "Squash Git commits" addon

### ISSUE THREAD

**Issue by di** [WeblateOrg/weblate#3709]
**Is your feature request related to a problem? Please describe.**
We are currently usinge the "Squash Git commits" addon.

We'd like to retain authorship information in the squashed commit by using `Co-authored-by: {{ author }}`, however with multiple authors this ends up producing a commit message like:

```
Translated using Weblate

Translation: pypa/warehouse
Translate-URL: https://hosted.weblate.org/projects/pypa/warehouse/es/

Co-authored-by: Contributor 1 <email@example.com>

Translated using Weblate

Translation: pypa/warehouse
Translate-URL: https://hosted.weblate.org/projects/pypa/warehouse/de/

Co-authored-by: Contributor 2 <email@example.com>
```

**Describe the solution you'd like**
Ideally, we could produce a single commit with a commit message like:
```
Translated using Weblate


Co-authored-by: Contributor 1 <email@example.com>
Co-authored-by: Contributor 2 <email@example.com>
```
I think it would be possible to do this if were possible to configure the "Squash Git commits" to have a "parent commit message" which the squashed commit messages are appended to. 

**Describe alternatives you've considered**
Setting the commit message to just:

```
Co-authored-by: {{ author }}
```
doesn't work, as the first line is interpreted by git as the commit message title, not part of the body.

**Comment by nijel** [comment]
We do no processing of commit messages in the squash addon. But adding `Co-authored-by` certainly makes sense. The messages are simply retrieved by `git log` right now:

https://github.com/WeblateOrg/weblate/blob/3c2c3143b1e246ab49abbd0034ad5836f13dd361/weblate/addons/git.py#L47

**Comment by di** [comment]
@nijel I'd be interested in trying to implement this if you'd like.

**Comment by nijel** [comment]
Sure, patches are always welcome ;-).
