### ISSUE TITLE
Customizable string ordering

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#3710]
**Describe the bug**
Something very strange is going on with string numbering in MyPaint on hosted.weblate.org

**To Reproduce**
Go to https://hosted.weblate.org/projects/mypaint/mypaint/fi/ and click All strings. You'll be directed to https://hosted.weblate.org/translate/mypaint/mypaint/fi/?q= which says it's string 1 out of 1272, yet there appear to be neighbouring strings above it. If you click on the one immediately above, Weblate says it's string 1086 out of 1272.

Likewise if you click the "last string" button, you'll be directed to https://hosted.weblate.org/translate/mypaint/mypaint/fi/?&offset=1272 where you can see neighbouring strings below it. If you click on the one immediately below, Weblate says it's string 1232 out of 1272.

**Expected behavior**
The first string should actually be the first and the last string should actually be the last, with no unexpected jumps in the numbering.

**Screenshots**

**Server configuration and status**
Whatever configuration is on hosted.weblate.org

**Additional context**

**Comment by tjhietala** [comment]
I see. Is there any way for the translator to switch to location-based numbering?

**Comment by nijel** [comment]
Not yet. I thought there is existing issue for this, but I cannot find it right now...

**Comment by comradekingu** [comment]
@tjhietala They are sorted by context.
First Context: Menu (labels),then nothing, then "Menu→File (labels), Accel Editor (labels)"

**Comment by nijel** [comment]
What sorting options do you find useful?

* Priority and position (currently hardcoded)
* Position
* Context
* Source

**Comment by comradekingu** [comment]
Length of string?

**Comment by nijel** [comment]
I also sometimes do translate short strings first, but I'm not sure it's a good practice... But it probably makes sense to include it.

**Comment by tjhietala** [comment]
For me, position is important in keeping mental orientation on where I am in the component, because the context strings alone often don't provide enough context. If the ordering stays stable, it's possible to build a kind of mental map of the component over time. It's hard to say how useful other sorting options would be without trying them.

**Comment by comradekingu** [comment]
Whatever makes the most sense should be selectable, no?

**Similarity**, same concept as length, but with additional benefit of keeping more topical
**Number of comments**, helps with keeping up with discussion
**New commends**, same as above
**Number of open issues**, helps people fix issues
**Number of failing checks**, same as above
**Age of string**, lets people get into the swing of things, and review what hasn't already been
**Label**, keeps it topical. Would be nice to open special language strings in a new tab where all those are.
**Number of reviews**, where the amount of reviews hopefully gets to be more than one some day.
**Number of screenshots/descriptions/source comments/labels**, helps the process of getting the context in shape

**Comment by nijel** [comment]
Some basic ordering options landed in https://github.com/WeblateOrg/weblate/pull/3766, more to be added.
