### ISSUE TITLE
Announcements improvements

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3713]
**Is your feature request related to a problem? Please describe.**
Announcements are a good way to communicate with the translators, but they could be more useful.

**Describe the solution you'd like**

* [x] Include author in related change entry, so that it is clear who posted that.
* [x] Use markdown rendering for them to allow rich content. Use that in the history as well.
* [x] Add recent announcements to project/component pages.
* [x] Add option to exclude announcement from e-mail notifications. This might be especially useful for site-wide ones.
* [x] Add management UI for site-wide announcements (currently this can be done only in the admin).

**Comment by comradekingu** [comment]
If the poster was there in gray when writing it and line-shifts made it in, it would solve all my issues.
