### ISSUE TITLE
Handling inconsistency accross translations of the same string

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#3715]
During translation, when strings are fired as inconsistent, yet it's hard to understand for a translator how to fixed it and to propagate good translation.

I have made some documentation improvement (see #3711), but I consider now Weblate Application "buggy".

The string "Change compared to this translation:" ("Modification par rapport à cette traduction :" in the french screenshot below) and the computed difference displayed below should be corrected as follow:
- **Label should be something like: "Change you could apply to this existing / remote string" or "future changes on this string if you erase the translation"**
- **Computed difference should be in reverse order : source = current translation in the "remote" component and target should be the value of proposed new translation. My idea; the computed difference should reflect what the string will look like if translator applies its change through "use this string button".**
- Maybe an other way to solve this is not to have several "Use this string button" on the same screen at once because the don't do all the same work despite having the same name but rather working on a kind of "assistant" with several steps selecting what translation to apply and where (on which strings) to apply it.

Thanks for your feedback (I'm opened to discussion).

![Handling inconsistency accross translations of the same string](https://user-images.githubusercontent.com/1452146/79041111-7a725400-7bed-11ea-8ddb-2f8b38d08d2d.jpg)

**Comment by comradekingu** [comment]
"Use this string" doesn't make it clear what actually happens.
Something like "Change all occurrences to this"?

**Comment by ldmpub** [comment]
Thanks for your inputs ;-).

> "[Use this string](https://hosted.weblate.org/translate/weblate/master/fr/?checksum=e70746c5c31b4d0e)" doesn't make it clear what actually happens.
> Something like "Change all occurrences to this"?

=> that's exactly what I have done in the french translation (adding "all" in the button label ; "partout" means everywhere ; the french button means "Apply this string to all translations").

> In the plain listing of duplicated strings, I don't understand why the first occurrence has to be there. There is the string in question, clearly visible in the editor, and then there is a "Other occurrences" in a tab.
The string in the editor isn't another occurrence to itself, so it stands to reason it shouldn't be listed (?)

=> I agree, in "other occurrences" tab, the first translation line should be removed ... BUT the current "Use this string" button should moved elsewhere to propagate this translation!

Maybe my suggestion to have a wizard is complexe and can be handled with multiple buttons but it won't be easy to understand/use by translators. For instance on each line:
- button "Ignore warning" = Keep the current translation
- button "Inherit translation" = Copy and save the above translation (overwrite).
And there is still a question about the "Computed difference syntax": what to display, where to put it?

I will have a look to the "context" issue you've created #3716.
