### ISSUE TITLE
Differentiate "Context" from "Source context"

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3716]
https://hosted.weblate.org/translate/weblate/website/en/?checksum=967407b9f176397c

"Context" in this regard means "text description of string", whereas all of the context is called "Source context", that is confusing, as one is interchangeable for the other.

"Context" is also in nearby strings.

**Comment by nijel** [comment]
To add the confusion, the context field is also used for key in monolingual translations.

**Comment by comradekingu** [comment]
Is that something translatetoolkit or someone else decided?
How about 
"Contextual description" for "context"
and 
"String info" for "Source context"?

"String info" could maybe be better, but it would be better to have a name that could also be used for something that would also describe the translation, if "context" is added there, like a localized screenshot when that functionality makes it in some day.

Sorry about one feature-request leading to the next, but #3718 is something I thought of.

**Comment by nijel** [comment]
The name is based on gettext (https://www.gnu.org/software/gettext/manual/html_node/Contexts.html). The existing field got later reused for keys in monolingual translations.

**Comment by comradekingu** [comment]
Maybe "Explanation" is better than "string info", to differentiate it from "label"

**Comment by nijel** [comment]
I think the biggest confusion comes from usage of the of "context" for (at least) three different things:

* `msgctxt` from gettext PO files
* keys fro monolingual files
* manually defined additional context

I think the latter two should use different words.

Additionally, there is source string comment, which is comment extracted from the translation files (which in turn might be extracted from the source code for example by xgettext).
