### ISSUE TITLE
Alerts or no alert? (bug in new alert feature)

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#3719]
Hi,

On the "language dashboard" there is a new info raised if inconsistencies are detected:
![Weblate - Main - Alerts](https://user-images.githubusercontent.com/1452146/79063047-87e81680-7c9f-11ea-8942-4300e16c81b2.jpg)

but when clicking on the component, there is no alert:
![Weblate - Details - No Alert](https://user-images.githubusercontent.com/1452146/79063044-861e5300-7c9f-11ea-9c68-2c738fda06b8.jpg)

Starting point is: https://hosted.weblate.org/languages/fr/weblate/

... there is inconsistency in the consistency check (depending on the level) ;-).

**Comment by ldmpub** [comment]
Other point: clicking on the red alert "!" with tolltip "Fix this component to clear its alerts" leads to an error page https://hosted.weblate.org/projects/weblate/master/#alerts (it may be a bug or just an incorrect setup for this particular project ...).

**Comment by nijel** [comment]
It does show the alerts for me. As anonymous user the page says it requires sign in.

**Comment by ldmpub** [comment]
I confirm what you say: as anonymous user the page https://hosted.weblate.org/projects/weblate/master/#alerts says it requires sign in => OK.

For me clicking on the red alert icon "!" with tooltip "Fix this component to clear its alerts" produces a kind of **blinking pages**:
1. a screen displaying alerts during less than 0.5 seconds => see below screenshot
![Webmate - Short Display](https://user-images.githubusercontent.com/1452146/79070937-0319ee80-7cd9-11ea-929b-3480249510cc.jpg)
This page seems to be https://hosted.weblate.org/projects/weblate/master/#translations
2. then there is immediately a redirect to the alerts page which displays "bad project config" => see below screenshot
![Weblate - Bad project config](https://user-images.githubusercontent.com/1452146/79070961-3492ba00-7cd9-11ea-9632-44f8ff1e4a33.jpg)

So there are several subjects for me:
- clicking on the "!": what should occur? (the behavior with fast redirect is strange according to me). Should we change the "!" tooltip to something more like "View list of alerts to correct them" (because correction can not be done in one click despite the text "Fix this component to clear its alerts" which means more or less clicking will fix all alerts).
- is there a particular pb or not with /weblate/master project config?

**Comment by nijel** [comment]
The problem is caused by GitHub rate limiting requests to its web interface. I've reduced the amount of links we check in bf5f31a8ad77a25519fdedc099d517d4d5029dde and I will see tonight if that helps when the site wide check is performed.
