### ISSUE TITLE
Show user languages as ghost translations

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3726]
Considering #3725 it would help in and of itself to put the "Add new translation" to the top, rather than at the bottom of all available languages.

**Comment by nijel** [comment]
Having it in bottom seems more natural to me - in case user doesn't find the language he is looking for, he is at the bottom of the page. Also, this is not really the most frequent action to have prominent placement on top of the page...

**Comment by comradekingu** [comment]
They are sorted alphabetically, so unless someone is looking for "Zulu", or similar, how are they getting to the bottom of the list?

**Comment by nijel** [comment]
I think this could use similar approach as in https://github.com/WeblateOrg/weblate/issues/2610 - show the missing translations with easy option to add them.
