### ISSUE TITLE
Translation memory enhancements or bugs?

### ISSUE THREAD

**Issue by ionmincu** [WeblateOrg/weblate#3729]
**Is your feature request related to a problem? Please describe.**

Not really sure if it's a bug, but when going `https://weblate.internal/manage/memory/` My shared translations are half of total translations, and also when I press the download button a very small file is created with only 4 strings in the memory instead of all.

![image](https://user-images.githubusercontent.com/44569445/79193242-e691c980-7e32-11ea-95c6-77e499a47ced.png)

**Describe the solution you'd like**

I would like a feature like `weblate dump_memory` that downloads all the translation memory into a single file (TMX preferably) but from the web interface.

**Describe alternatives you've considered**

I've tried to use `weblate dump_memory` but it seems it gets stuck sometimes and takes a lot of time to generate.

**Comment by nijel** [comment]
The descriptions are confusing and should be improved. What you are downloading here are only global entries, which is 0 in your case.

The backend for translation memory is rewritten for upcoming 4.0 release and the performance issues with dumping should be gone there.
