### ISSUE TITLE
Weblate changed i18next source string to be ".package.opencollective"

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#3731]
**Describe the bug**

Weblate changed a source string to a strange value.  As far as I can tell, it is not anything to do with i18next syntax:

*_data/strings.json*:
```diff
         "gpg_signature": "PGP Signature",
         "issue_tracker": "Issue Tracker",
         "liberapay": "Liberapay",
         "license": "License",
         "minimum_android_version": "This version requires Android {{ android_version }} or newer.",
         "new_in_version": "New in version {{ latest_version }}",
-        "opencollective": "Open Collective",
+        "opencollective": ".package.opencollective",
         "packages": "Packages",
         "permissions": "Permissions",
         "signed_by_developer": "It is built and signed by the original developer.",

```

**To Reproduce**

I don't know what triggered it.  It is visible here:

* be5653ce95e439a7288d3e7b4eb29909d74963b0 in https://hosted.weblate.org/translate/f-droid/website
* for example https://hosted.weblate.org/translate/f-droid/website/de/?q=opencollective&checksum=&offset=

**Expected behavior**

Should not have changed the source string.

**Server configuration and status**

hosted.weblate.org

**Additional context**

We recently changed the source string format from "nested JSON" to i18next in order to get syntax checking of the format strings.  We left the JSON files as they are since the basic structure should be compatible between the two formats.  We only changed the format strings to use i18next syntax `{{ android_version }}` instead of our custom syntax `[android_version]`.

@uniqx FYI

**Comment by nijel** [comment]
It was edited this way by someone, see https://hosted.weblate.org/translate/f-droid/website/en/?checksum=c646e7b0a8d8c605#history

**Comment by eighthave** [comment]
Oops, strange, yeah, sorry for the noise.
