### ISSUE TITLE
Hide Repository info on Information screen for regular users

### ISSUE THREAD

**Issue by gorgobacka** [WeblateOrg/weblate#3743]
**Is your feature request related to a problem? Please describe.**
Currently all users see detailed information of the repository that store the language files. Regular users that only need to translate something, do not need to see that (Repository, Filemask, ...). In my use case, I don't want to show this information to everyone.

**Describe the solution you'd like**
I propose an option to hide this information and only show it to admins.

Is this possible?

**Comment by nijel** [comment]
Yes, there is permission for that: "View upstream repository location"

**Comment by gorgobacka** [comment]
Thanks, I will try that.
