### ISSUE TITLE
Project changes by user

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3744]
https://hosted.weblate.org/changes/?project=kiss&component=strings&lang=nb_NO
can not be divided by users.
Neither can https://hosted.weblate.org/user/kingu/

So I have to resort to the search to find strings by a user for a project.
I find issues in string view, go to history, and want to make sure a user hasn't made any more errors in the project.

Some word/string count on the user page, along with links to those would do it.

**Comment by nijel** [comment]
It can, there just no UI for that: https://hosted.weblate.org/changes/?project=kiss&component=strings&lang=nb_NO&user=kingu
