### ISSUE TITLE
Allow Language code style placeholders in Filemask of file in a Component

### ISSUE THREAD

**Issue by vanous** [WeblateOrg/weblate#3746]
Thank you for all your work. I contribute translations to FLOSS projects regularly using PRs, Weblate, Crowdin... now it's time to move some of my own pet projects to Weblate :)

**Is your feature request related to a problem? Please describe.**

Yes. Some of my projects (Publican with Docbook) use lc-CC (cs-CZ), some other projects use CC (CZ) in file paths (lc → language code, CC → Country Code). When importing from git, existing languages are correctly recognized in most cases, but i cannot start new translation with correct path/language code (for example cs_CZ as Weblate always uses cs (or custom created cz) there. I cannot modify language definitions, because each project uses different style.

**Describe the solution you'd like**

I would like to see the possibility to use placeholders, like can be seen in other projects:

%language% | Language name (e.g. Ukrainian)
%two_letters_code% | Language code ISO 639-1 (i.e. uk)
%three_letters_code% | Language code ISO 639-2/T (i.e. ukr)
%locale% | Locale (like uk-UA)
%locale_with_underscore% | Locale (i.e. uk_UA)
...

I picked this example as a small portion of what is possible in Crowdin.

**Describe alternatives you've considered**
I can have the translators to start new translation, then pull back to my repo, rename directory from e.g. cs to CZ or to cs-CZ and push back. Obviously sub-optimal as it requires constant watch over what is happening. I have also tried using other `Language code style` from the selection box, but this didn't work (maybe because of this:

```
Weblate recognizes any of these when parsing translation files, the above settings only influences how new files are created.
```

**Additional context**
Maybe i missed something and would be grateful for a hint.

**Comment by nijel** [comment]
There is already setting for this: https://docs.weblate.org/en/latest/formats.html#adding-new-translations

**Comment by vanous** [comment]
Hi @nijel ,

thank you for getting back. This is why i reported it, as per my original description... it does not work:

Master component (repository) settings:

![2020-04-18_20-15](https://user-images.githubusercontent.com/3680926/79651607-b9864380-81b1-11ea-8566-af3596e11887.png)

Linked component settings:

![2020-04-18_20-16](https://user-images.githubusercontent.com/3680926/79651978-d589e500-81b1-11ea-8813-d51a28aac801.png)

Start new translations → Czech (cs) , Info:

![2020-04-18_20-17](https://user-images.githubusercontent.com/3680926/79652348-f05c5980-81b1-11ea-9c09-989c652b5023.png)

But it should have been cs-CZ. Am i doing something wrong?

Is it perhaps related to https://github.com/WeblateOrg/weblate/issues/3246 ?
Thank you
Petr

**Comment by nijel** [comment]
Ah, I didn't notice you want the full language code in all cases, then it's really #3246

**Comment by vanous** [comment]
One more idea - how far does `SIMPLIFY_LANGUAGES` affect this and is it perhaps clashing with the settings per project/module? At this point, i have not set it to False yet, but will try.

**Comment by nijel** [comment]
`SIMPLIFY_LANGUAGES` affects only parsing, not creating new files.
