### ISSUE TITLE
Better utilize XLIFF states

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3750]
This might be true for some other formats as well, but definitely for XLIFF. It has way more states than Weblate and Weblate should at least utilize those to make sense for it.

Right now it's:

* Needs editing is mapped to `needs-translation`
* Translated/Waiting for review is mapped to `translated`
* Approved is mapped to `final` (+ approved flag if used)

In case the review process is enabled, the right state probably should be `needs-review-translation`.

**Comment by djbe** [comment]
Would this fix the current loss of "state" when importing? We've noticed that whenever Weblate triggers an import (on push for example), it loses the "needs editing" state. Reading through https://github.com/WeblateOrg/weblate/pull/2372#issuecomment-436157111 and this issue, makes me think that's the cause for it.

**Comment by nijel** [comment]
The needs editing state should be saved right now - it should appear as "needs-translation" state.
