### ISSUE TITLE
Unable to correct a string / "zero-width-space" check raised

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#3763]
Hi,

On one string there is a "zero-width-space" check raised. I have retyped the entire sentence so I'm quite sure that this is a false positive (except if you can find where this "invisible caracter" is).

The erroneous string I can not correct yet is https://hosted.weblate.org/translate/osmand/main/fr/?checksum=5c1df88f6b9cf99b

**Comment by ldmpub** [comment]
Plus: clicking on 'Correct string' button has no effect.

**Comment by comradekingu** [comment]
I tried copying it into something without support for rich text, I think that has used in the past.
