### ISSUE TITLE
Updating settings.py does not update settings

### ISSUE THREAD

**Issue by buck-E** [WeblateOrg/weblate#3772]
**Describe the bug**
After addressing "System checks" at `/manage/performance/` by editing settings.py, and restarting weblate, the "System checks" are still present

**To Reproduce**
1. Go to `/manage/performance/`
2. Read "System checks"
3. Change value in `./weblate-env/lib/python3.8/site-packages/weblate/settings.py`
4. Restart weblate 
5. See "System checks" error is still present

**Expected behavior**
After addressing the system check, the issue should disappear.

**Additional context**
Documentation about specific issues is not available.  Example: https://docs.weblate.org/en/weblate-4.0.1/admin/install.html#production-ssl  (See https://github.com/WeblateOrg/weblate/issues/3769)

**Comment by nijel** [comment]
The system checks section is generated on each request, so either you did not fix it or did not restarted wsgi.

**Comment by buck-E** [comment]
@nijel 

wsgi?

4 above should have been more clear:

4. Restarted weblate with:
a. CTRL-C
b. `weblate runserver`

wsgi is a root-level change right?  Does the systems administrator need to restart apache2/nginx?
