### ISSUE TITLE
SITE_DOMAIN documentation does not exist

### ISSUE THREAD

**Issue by buck-E** [WeblateOrg/weblate#3773]
**Describe the bug**
/manage/performance/ shows an error that the docs do not address

**To Reproduce**
1. Go to `/manage/performance/`
2. See error: `weblate.E017 | Configure correct site domain`
3. Visit https://docs.weblate.org/
4. Search for "SITE_DOMAIN" and "SITE DOMAIN"
5. No doc exists: /en/latest/search.html?q=SITE+DOMAIN&check_keywords=yes&area=default

**Expected behavior**
A doc should exist to address any error message found in the site.

**Comment by nijel** [comment]
It links to the docs: https://docs.weblate.org/en/latest/admin/install.html#production-site

**Comment by buck-E** [comment]
@nijel

> It links to the docs:

What is "It" here?  The "weblate.E017" text does not link to that URL, nor anything else on this line.

But that URL is very helpful/necessary.  Thank you.

**Comment by buck-E** [comment]
@nijel

Ah!  I am seeing the error under "Configuration errors" and this has no links.  But the links under "System checks" now work after you fixed https://github.com/WeblateOrg/weblate/issues/3769

However in this example, the "Configuration errors" section shows "weblate.E017" but this error does not appear under "System checks"

**Comment by Patelrahul4884** [comment]
I am still getting this error
![image](https://user-images.githubusercontent.com/26384517/184990000-654b0a61-8985-4406-9a5e-030004a04819.png)
