### ISSUE TITLE
DEBUG = True causes CSS failure

### ISSUE THREAD

**Issue by buck-E** [WeblateOrg/weblate#3774]
**Describe the bug**
After setting DEBUG = True in settings.py, webUI styles are not available

**To Reproduce**
Following: https://docs.weblate.org/en/weblate-4.0.1/admin/install.html#production-debug
1. Set `DEBUG = True` in `settings.py`
2. Refresh website
3. See that styling information is lost

**Expected behavior**
Either:

1 - The styles would not be lost
2 - The doc at https://docs.weblate.org/en/weblate-4.0.1/admin/install.html#production-debug would explain what else should happen to prevent this.

**Additional context**
Are there other settings that `DEBUG` depends on?  Does apache2/nginx need to be restarted?  Etc.  Maybe this should go in the doc at https://docs.weblate.org/en/weblate-4.0.1/admin/install.html#production-debug

**Comment by nijel** [comment]
I can't reproduce this. How do you serve static files? Any customization in settings?

**Comment by buck-E** [comment]
@nijel 

> How do you serve static files? Any customization in settings? What error do you get?

It's an unusual config.  Running weblate using "weblate runserver" in a `screen` session as non-priv `weblate` user.

Then nginx proxy to port 8000

Also, now we are using a local user-level systemd service instead of running inside a `screen` session.

There is no error message.  But the CSS styles are not available.  So you see all of the text, but no formatting.  Example is attached.  This page looked normal a moment ago before I changed "DEBUG = True" to "DEBUG = False"
![Screenshot_2020-04-24 GNU Taler Weblate Translations](https://user-images.githubusercontent.com/64185129/80177052-07ec7580-85ea-11ea-9025-45d97f73963d.png)

**Comment by buck-E** [comment]
@nijel

> Okay, so it's exactly opposite than what you've described in the initial post.

Oh, yes.  I changed the initial post,  The error comes from setting `DEBUG = False`, not to `True` which is the default.

> With DEBUG = True it's up to you to configure serving of the static files. See https://docs.weblate.org/en/latest/admin/install.html#serving-static-files

Okay I looked at that doc and it is not clear.  It gives one vague recommendation but doesn't tell me what is actually happening well enough to figure out a fix that works for our system.  We are running the built-in web server, but reverse proxying nginx to it. 

Do you think perhaps that `DEBUG = True` is perhaps less dangerous, with nginx as the front-end?

If not then is there a way to have `DEBUG = False` but still have the build-in webserver serve the static files?  Some manual config option I can change?

If both of these fail, I will config nginx manually.  But that page does not make it clear what needs to be served.  What I mean is, where exactly are the `/static/` and `/media/` folders?  I don't see `media` anywhere in the `weblate-env` directory, and I see many `static` folders.

**Comment by nijel** [comment]
The `runserver` is really intended for development only. You can probably hack urls.py to do what you want, but I don't think it makes sense. Just do a proper wsgi setup, see https://docs.weblate.org/en/latest/admin/install.html#running-server. In case you're struggling with this, we're happy to help by our professional support service at support@weblate.org (please note, this a paid service, see https://weblate.org/support/).

**Comment by buck-E** [comment]
@nijel 

How dangerous is DEBUG = True if filtered through an nginx reverse proxy?  We have other reasons for running it this way.

**Comment by nijel** [comment]
For sure running with DEBUG = True will leak a lot of information about your environment in case of internal server error. It will probably also lead to memory leaks (at least that what Celery warns about). See https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-DEBUG for detailed explanation of what it does.

**Comment by buck-E** [comment]
@nijel 

Okay, moving to a full install.  Styling is still an issue and it might be resolved with this:  in a virtualenv running as a non-priv user, /usr/share/weblate does not exist.  What is the correct nginx setting for:

```
    listen 80;
    server_name weblate;
    root /usr/share/weblate;
```

**Comment by buck-E** [comment]
Okay please confirm or correct:

/var/lib/weblate = weblate-env/lib/python3.8/site-packages/data/
/usr/share/weblate = weblate-env/lib/python3.8/site-packages/weblate

?

**Comment by nijel** [comment]
I've clarified and consolidated the examples in 1267882c3b65585dc4ca54f3427777ae283b701d.

**Comment by buck-E** [comment]
@nijel That is useful but it doesn't directly answer my question.  I want to map those values onto a pip install.  So can you  please confirm or correct:

```
/var/lib/weblate = weblate-env/lib/python3.8/site-packages/data/
/usr/share/weblate = weblate-env/lib/python3.8/site-packages/weblate

?
```

**Comment by nijel** [comment]
`/usr/share/weblate` should not be needed at all. `/var/lib/weblate` should be replaced to where your `DATA_DIR` is set. The default value will look like you describe.
