### ISSUE TITLE
client language

### ISSUE THREAD

**Issue by jzahradn** [WeblateOrg/weblate#3775]
Hi,
I created many components via API and then I noticed that new language "Client (generated)" was created too.
Now I need to delete this language on every component I have created.
- What is purpose of this language?
- Can I delete it safely without impact to primary language? (it seems to use the same file)
- Is it possible to bulk delete it (without need to browse every single component in GUI)?
- How can I avoid creating this language during further components creation?

Thank you
Regards
Jan

**Comment by nijel** [comment]
It was created by Weblate because it has matched file mask in one of the components, see https://docs.weblate.org/en/latest/admin/languages.html#parsing-language-codes

**Comment by jzahradn** [comment]
If I understand it correctly, I can delete all these "Client (generated)" languages safely without risking any impacts. Right?

**Comment by jzahradn** [comment]
I want to delete the client languages in new components, I expect it won't have impact to another languages.
When I try to delete it, I must write its name. I have tried: client, client (generated), client (generated) client, but Weblate always returned: "The translation name does not match the one marked for deletion!" and the language was not deleted.
How can I delete it? Can I delete just csv file client.csv on file system?

**Comment by nijel** [comment]
You can also delete the file from the VCS. You have to type full path, so something like `project/component/client`.

**Comment by jzahradn** [comment]
I confirm I can delete a language if slug is included in the language name. We can close this issue.
