### ISSUE TITLE
Protected project is not visible on hosted.weblate.org

### ISSUE THREAD

**Issue by tpokorra** [WeblateOrg/weblate#3777]
According to https://docs.weblate.org/en/latest/admin/access.html#acl

When I set a project on hosted.weblate.org to public, it is accessible. That works fine.
But when I set the project to "protected", then other users get something like: this project does not exist, or is not publicly available.

I would expect it still to be publicly visible. But that does not seem to be the case.

**Comment by nijel** [comment]
For me, it is shown for authenticated users. It was not shown to anonymous user due to too strict and I've just fixed that.

**Comment by tpokorra** [comment]
Yes, I only tried with my own user (owner of the project) and as an anonymous user.
Thanks for fixing it!
