### ISSUE TITLE
Links to new strings missing in history view

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#3779]
**Describe the bug**
In the History view, for modified strings, the View details button (the magnifying glass icon) links to the exact location of the string. This is not true for new strings, though. In new strings there's only a link to the component.

**To Reproduce**
Reproducible on e.g. https://hosted.weblate.org/projects/weblate/master/fi/#history

**Expected behavior**
Clicking the button should always take the user to the exact location of the string.

**Screenshots**

**Server configuration and status**
hosted.weblate.org

**Additional context**

**Comment by nijel** [comment]
Seems that this event is confusing - it actually means "at least one new string to translate was found". See also https://github.com/WeblateOrg/weblate/issues/3332

**Comment by ldmpub** [comment]
As far as I understand the new link (behind the magnifier glass) will allow to "browse" the new strings to translate => it fine for me.
