### ISSUE TITLE
Back-end docs fail on docutils but python3-docutils is installed

### ISSUE THREAD

**Issue by buck-E** [WeblateOrg/weblate#3781]
**Describe the bug**
"Weblate administration" errors on docutils but python3-docutils is installed

**To Reproduce**
1. Go to 'admin/doc/'
2. See this error:
```
The admin documentation system requires Python's docutils library.
Please ask your administrators to install docutils.
```
3. Note that `python3-docutils` is installed on system, scratch head.

**Expected behavior**
Either the docs would be available, or the error should relate to a package that does not exist on the server?

**Server configuration and status**

Debian stretch; python3-docutils installed

**Additional context**
Is this more of a Django error?

**Comment by nijel** [comment]
In case you are using virtualenv, the package needs to be installed in it, it doesn't use system packages.

**Comment by buck-E** [comment]
Confirmed.  After `pip install docutils` and restarting weblate, `admin/doc` showd the docs.

I recommend adding `docutils` to the optional packages where you say:

```
5. Install wanted optional dependencies depending on features you intend to use...
```

**Comment by nijel** [comment]
True docutils might be mentioned there, but I don't find `admin/doc` much useful for Weblate user. Can you please share your use case?

PS: Django admin interface should not be used in future, see https://github.com/WeblateOrg/weblate/issues/2363

**Comment by buck-E** [comment]
> True docutils might be mentioned there, but I don't find admin/doc much useful for Weblate user. Can you please share your use case?

Use case:  

- have a new system
- click all the things
- get error

> PS: Django admin interface should not be used in future, see #2363

That would preempt this then.  Good.
