### ISSUE TITLE
Configuration errors still visible after System checks resolved

### ISSUE THREAD

**Issue by buck-E** [WeblateOrg/weblate#3782]
**Describe the bug**
After default email and server email are fixed and no longer visible in "System checks" they still appear in "Configuration errors"

Screenshot is probably clearest.  A moment before, the errors we see in "Configuration errors" were also in "System checks" but even after fixing settings.py, they still exist in the top:

![Screenshot_2020-04-24 GNU Taler Weblate Translations(2)](https://user-images.githubusercontent.com/64185129/80180141-9c0e0b00-85f1-11ea-8fc9-8d1a8a3d0159.png)

**Comment by nijel** [comment]
Already addressed by 88a54ad8617d4d061783b49fea73f0d3a6c56c2f.

**Comment by buck-E** [comment]
@nijel No this is unrelated to the earlier bug report (which was fixed byhttps://github.com/WeblateOrg/weblate/commit/88a54ad8617d4d061783b49fea73f0d3a6c56c2f)

This error persists on `manage/performance/` after upgrading with `pip install Weblate --upgrade`

**Comment by nijel** [comment]
Yes. It will persist for now because 4.0.2 which will include this fix was not yet released...
