### ISSUE TITLE
security.W012 issue with inconsistent messaging

### ISSUE THREAD

**Issue by buck-E** [WeblateOrg/weblate#3783]
**Describe the bug**
The error message for security.WO12 conflicts with settings.py and https://docs.weblate.org/en/weblate-4.0.1/admin/install.html#production-ssl

**To Reproduce**
1. Go to `/manage/performance`
2. See message:
`security.W012 | SESSION_COOKIE_SECURE is not set to True. Using a secure-only  session cookie makes it more difficult for network traffic sniffers to  hijack user sessions.`
3. Visit https://docs.weblate.org/en/weblate-4.0.1/admin/install.html#production-ssl
4. See `you should set ENABLE_HTTPS in the settings`
5. Verify `settings.py` says `SESSION_COOKIE_SECURE = ENABLE_HTTPS`

**Expected behavior**
security.WO12 should not be shown to me

**Additional context**

Is it possible that an older version of weblate used "True" instead of "ENABLE_HTTPS" and the scanner for security.WO12 is expecting the earlier parameter?

UPDATE:  Also true for security.W008

**Comment by nijel** [comment]
I don't get what is wrong. In case you are using https, you should enable `ENABLE_HTTPS` and that will automatically enable `SESSION_COOKIE_SECURE`. Enabling `SESSION_COOKIE_SECURE` without using https will make some browsers ingore the cookies, because they are set as https only from site not using https.

All the security.* checks come from Django, see https://docs.djangoproject.com/en/3.0/ref/checks/#security

**Comment by buck-E** [comment]
@nijel

> In case you are using https, you should enable ENABLE_HTTPS and that will automatically enable SESSION_COOKIE_SECURE

This doesn't make a lot of sense to me.  What do I do to "enable ENABLE_HTTPS?"

The `SESSION_COOKIE_SECURE` option takes `ENABLE_HTTPS` as a parameter.  They are not different things.  In `settings.py`, `SESSION_COOKIE_SECURE = ENABLE_HTTPS` is already set as the default.

The nginx webserver is forwarding to port 8000, and nginx does have HTTPS.  So I assume I need these set, but there is no `True` parameter.  The parameter is `ENABLE_HTTPS`.

> All the security.* checks come from Django

So these are really Django errors?  If so, I understand if you want to close this Issue here.

**Comment by nijel** [comment]
>  What do I do to "enable ENABLE_HTTPS?"

```python
ENABLE_HTTPS = True
```

I've clarified the docs in 913a0f8eccec34ef95d5c7f7208f1de0eaa75829.
