### ISSUE TITLE
security.W004 documentation not available

### ISSUE THREAD

**Issue by buck-E** [WeblateOrg/weblate#3784]
**Describe the bug**
security.W004 points user to https://docs.weblate.org/en/weblate-4.0.1/admin/install.html#production-ssl, which does not explain `SECURE_HSTS_SECONDS`

**To Reproduce**
1. Go to '/manage/performance'
2. See:
```
security.W004 | You have not set a value for the SECURE_HSTS_SECONDS setting.  If your entire site is served only over SSL, you may want to consider  setting a value and enabling HTTP Strict Transport Security. Be sure to  read the documentation first; enabling HSTS carelessly can cause  serious, irreversible problems.
```

3. Visit link at https://docs.weblate.org/en/weblate-4.0.1/admin/install.html#production-ssl
4. Fail to find information on `SECURE_HSTS_SECONDS`, and live in fear of these "serious, irreversible problems"

**Expected behavior**
The link should explain the item in the same line

**Comment by rajat641** [comment]
Hi @nijel , I can start of on this bug.

**Comment by nijel** [comment]
Go ahead, it's mostly about adding documentation and links to Django docs.

**Comment by rajat641** [comment]
Thanks @nijel . I'm on it .

**Comment by rajat641** [comment]
Hi @nijel , This is my first ever code contribution on any open-source software. Please let me know if the code changes are fine or I have made some improvements. It took me some time to do the code set up and run sphinx.
