### ISSUE TITLE
Make suggestions available in read-only mode

### ISSUE THREAD

**Issue by Kyuuu** [WeblateOrg/weblate#3785]
**Is your feature request related to a problem? Please describe.**
I use the read-only flag to block the possibility to change strings while I do not notice.
However, some translators reported that these strings have syntax errors not connected with terms I care about. It will be great for people with translate permissions to make suggestions in read-only mode also.

**Describe the solution you'd like**
Possibility for translators to suggest changes even with a read-only flag.

Whatever is admin should be able to accept these suggestions just like that or has to delete the read-only flag before.

**Describe alternatives you've considered**
(Yeah, I heard about proofreaders option? Or something. But I totally do not get how it works and permissions on the admin page are a bit complicated and there are too many of them that I do not use it at all. Just the option to make a normal suggestion with this flag would be perfect!).

**Additional context**
![image](https://user-images.githubusercontent.com/33127074/80191559-28cac000-8616-11ea-8e55-e5d1df1fa785.png)

**Comment by nijel** [comment]
Using review workflow seems better fit for your use case, see https://docs.weblate.org/en/latest/workflows.html#dedicated-reviewers

The read only strings are intended for string that are not supposed to be changed (some file formats support this natively, for other you can add flag in Weblate).

**Comment by Kyuuu** [comment]
Hm. If I just left translation that _I do not care about_ with "Waiting for review" option - would it work just like I even do not turn on review option?

Also, do I have to approve every string if I want it to be sent to the repository? Or "waiting for review" strings are just sent normally?

And is there a way to mark all languages as "Approved" in the selected string? Or do I have to open every single language and mark it separately?

**Comment by nijel** [comment]
Yes, for people with only translate permission it will behave exactly like now. With review permission, there will be additional state to select.

Currently, all strings are committed, this might be configurable in future, see https://github.com/WeblateOrg/weblate/issues/3745

You can use bulk edit to change state of more strings.

**Comment by Kyuuu** [comment]
"You can use bulk edit to change state of more strings."

Hm, then I think that the "needs-approval" flag would be great or another similar thing to mark all string's actual translations and these ones that will be added in the future as something that may be suggested only cause it is important to check.

**Comment by nijel** [comment]
I see no need for additional flag. In case you want to check the string before approval, flag them manually. If you want to freeze current state, use bulk edit with `state:translated` search and set all strings to approved.
