### ISSUE TITLE
Weblate Digest e-mails in broken HTML

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3786]
I seem to remember this working in Mutt, but now Thunderbird has other ideas.
Could the e-mails be sent in plain text so that everyone gets along?
---
To: "weblate@lists.cihar.com" <weblate@lists.cihar.com>
Message-ID:  <VI1PR10MB21285FFB439DE289E51B865BC2D00@VI1PR10MB2128.EUR
	PRD10.PROD.OUTLOOK.COM>
Content-Type: multipart/alternative;    boundary="_000_VI1PR10MB21285F
	FB439DE289E51B865BC2D00VI1PR10MB2128EURP_"

--_000_VI1PR10MB21285FFB439DE289E51B865BC2D00VI1PR10MB2128EURP_
Content-Type: text/plain; charset="iso-8859-9"
Content-Transfer-Encoding: quoted-printable

>The message part

<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Diso-8859-=
9">
<style type=3D"text/css" style=3D"display:none;"> P {margin-top:0;margin-bo=
ttom:0;} </style>
</head>
<body dir=3D"ltr">
<div style=3D"font-family: Calibri, Helvetica, sans-serif; font-size: 12pt;=
 color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">
Hi,</div>
<div style=3D"font-family: Calibri, Helvetica, sans-serif; font-size: 12pt;=
 color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">
<br>
</div>
<div style=3D"font-family: Calibri, Helvetica, sans-serif; font-size: 12pt;=
 color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">
The following string is not working as translation in all languages. It is =
always in English on &quot;Add new translation project&quot; page.<br>
</div>
<div style=3D"font-family: Calibri, Helvetica, sans-serif; font-size: 12pt;=
 color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">
&quot;You can use Markdown and mention users by @username.&quot;<br>
</div>
<div style=3D"font-family: Calibri, Helvetica, sans-serif; font-size: 12pt;=
 color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">
<br>
</div>
<div style=3D"font-family: Calibri, Helvetica, sans-serif; font-size: 12pt;=
 color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">
Regards,</div>
<div style=3D"font-family: Calibri, Helvetica, sans-serif; font-size: 12pt;=
 color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">
Burak</div>
</body>
</html>

--_000_VI1PR10MB21285FFB439DE289E51B865BC2D00VI1PR10MB2128EURP_--

--
>Reply

Date: Fri, 24 Apr 2020 14:47:18 +0200
From: Michal Čihař <michal@
Subject: [Weblate] Re: Not working translation string
To: weblate@
Message-ID: <9d2fa7cb8f1b628da84fb679eccd1dc1b778e654.camel@cihar.com>
Content-Type: multipart/alternative; boundary="=-TPqbflotH0KBMp/9Egj8"

--=-TPqbflotH0KBMp/9Egj8
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

**Comment by nijel** [comment]
I don't think we can enforce this on the mailing list...
