### ISSUE TITLE
RTL Regression in 4.0.1

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#3788]
**Describe the bug**
The string navigation arrows on top have switched places

**To Reproduce**
Switch to the RTL interface and edit a string

**Expected behavior**
It was fixed before in #1584 but now I've spotted it once again on Fedora's instance

**Screenshots**
<img width="1398" alt="Screen Shot 2020-04-26 at 10 55 06" src="https://user-images.githubusercontent.com/406826/80301479-1cc53680-87ad-11ea-8216-011024d95106.png">

**Server configuration and status**
Fedora's instance, not sure.

**Additional context**
Should be quite trivial because the former fix was exactly the same.

**Comment by nijel** [comment]
Broken by https://github.com/WeblateOrg/weblate/pull/3645, working on a fix.

**Comment by yarons** [comment]
Thanks again man!
