### ISSUE TITLE
HAML and erb file formats

### ISSUE THREAD

**Issue by 0xtrzy** [WeblateOrg/weblate#3793]
Please add haml and erb format of file.
typical multiline web source

**Comment by nijel** [comment]
The issue you've reported needs to be addressed in the [translate-toolkit](https://github.com/translate/translate/). Please file the issue there and do not forget to include links to any relevant specifications about the formats (if applicable).

**Comment by nijel** [comment]
Looking at these formats, I don't think Weblate is the place to handle localization in this case. You should use standard rails localization, see for example: https://stackoverflow.com/questions/10948333/how-to-use-rails-i18n-with-haml . The Ruby YAML files are already supported by Weblate.
