### ISSUE TITLE
XLIFF file with PO extensions does not show plural forms

### ISSUE THREAD

**Issue by jammmet** [WeblateOrg/weblate#3794]
**Describe the bug**
xliff file with PO extensions does not import plurals

**To Reproduce**
Import the following into weblate as _XLIFF translation file with PO extensions_

```<?xml version="1.0"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file source-language="en" target-language="sw" datatype="plaintext">
    <body>
      <group restype="x-gettext-plurals" id="test">
        <trans-unit id="test[0]">
          <source>There are six spots altogether.</source>
        </trans-unit>
        <trans-unit id="test[1]">
          <source>The/re are s/ix sp/ots altogether.</source>
        </trans-unit>
      </group>
    </body>
  </file>
</xliff>
````

No plural forms are shown

**Expected behavior**
Two plural forms should be shown

**Screenshots**

**Server configuration and status**

 * Weblate: 4.0.1
 * Django: 3.0.5
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.0
 * lxml: 4.3.2
 * Pillow: 7.1.1
 * bleach: 3.1.4
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.9.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.1
 * celery: 4.4.2
 * kombu: 4.6.8
 * translation-finder: 2.0
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.23.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.3
 * Cython: 0.29.16
 * misaka: 2.1.1
 * GitPython: 3.1.1
 * borgbackup: 1.1.11
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.7.7
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.12.39
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * Mercurial: 4.8.2
 * git-svn: 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.gmail.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.15.0-96-generic (x86_64)

**Comment by nijel** [comment]
Currently, the ID of plural units has to be numeric only. The [specification](https://docs.oasis-open.org/xliff/v1.2/xliff-profile-po/xliff-profile-po-1.2-cd02.html) lists only numeric ids as example, but it doesn't clearly state that it has be numeric.

See related code: https://github.com/translate/translate/blob/988b7096142a0043f4f43a577f0f4b38410595ab/translate/storage/poxliff.py#L368-L374

**Comment by nijel** [comment]
Should be addressed by https://github.com/translate/translate/pull/3998
