### ISSUE TITLE
Text in widgets

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3807]
Right now the widgets use text as images. This is not good for blind people, and the info isn't in the alt tag. It also makes it hard to search and highlight one language, especially when multiple widgets are present. It also makes it a few clicks more difficult to get to the translation in question.
![bilde](https://user-images.githubusercontent.com/13802408/80778027-92872480-8b56-11ea-9a68-63405b9b9957.png)
Example from https://gitlab.com/fdroid/fdroid-website

**Comment by nijel** [comment]
The widgets are SVGs and it contains text, but it's probably not good accessibility wise. On the other side, images are suitable for embedding in other sites, including textual content might be more problematic. Do you know if GitLab/GitHub support iframes or javascript?

**Comment by comradekingu** [comment]
That sounds bad. The <text> element in SVG would do.(?)

**Comment by nijel** [comment]
The `<text>` element is already used in those.
