### ISSUE TITLE
"Go To Position" for Zen mode

### ISSUE THREAD

**Issue by vernzimm** [WeblateOrg/weblate#3811]
I feel like I must be missing something massive here. Weblate 4.0 project with >5k strings in one set. Editing string 2000, and notice a whole group of strings that need small changes. Click Zen to start banging out little changes... Zen starts from string 1(???)... no "Go To Position" like in standard view... scroll 20 at a time until Chrome is dying from lack of memory because it's holding 2k zen entries open simultaneously. Hit back button by accident. Palm->Face++ and call it a day :)

**Comment by comradekingu** [comment]
Fairly sure Pootle has this.

**Comment by vernzimm** [comment]
I like the scrollbar idea, but use string number instead/beside and add a "view so many" dropdown to limit memory use. Maybe use relative scale i.e. from current string 2000:

0 - 500 - 1000 - 1500 - 1750 - 1850 - 1950 - 1975 -(2000)- 2025 - 2050 - 2150 - 2250 - 2500 - 3000...



One other small note, the existing "Go To Position" pane in non-zen is very finicky. I often close it when trying to click the number to change. A click on the left empty section of the pane causes it to close (as though clicking off pane), but click to the right does not. Same is true for the new (to me) string search pane.

**Comment by comradekingu** [comment]
You can add "/?&offset=123" to the URL in Zen mode as a stopgap measure.

**Comment by vernzimm** [comment]
@comradekingu thanks, that works! Nice work.
