### ISSUE TITLE
Sitewide search improvements

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3815]
**Is your feature request related to a problem? Please describe.**
The sitewide search currently looks quite ugly. There is lot of space for improvements:

- [x] Move search query input to the top and remove full query builder, it doesn't seem to be needed here
- [x] Improve listing of the strings

**Describe the solution you'd like**
The basic UI concepts should be same as on translate or zen pages.

**Comment by 12people** [comment]
I'm not sure what Translate or Zen Pages do, but I quite like the search sidebar in Mozilla's Pontoon:

<img width="1440" alt="Screen Shot 2020-05-08 at 16 17 00" src="https://user-images.githubusercontent.com/7361228/81414656-9b27be00-9147-11ea-8110-b168b08ce483.png">

Do you mean something like that?
