### ISSUE TITLE
Autofill uploaded screenshot name with filename

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3818]
It is tedious having to name all screenshots when the files are already named.

**Comment by flosincapite** [comment]
I would be happy to take this one. @comradekingu , can you provide more context?

**Comment by comradekingu** [comment]
@flosincapite Hold on, I'll get some screenshots

**Comment by flosincapite** [comment]
Thank you! Yes, please make me an admin. I'm flosincapite on Weblate.

**Comment by flosincapite** [comment]
Quick question: is there a way to run only the frontend locally? Maybe some undocumented option in rundev.sh?

Alternatively, is there a way I can pre-populate the local DBs with a few projects and languages?

**Comment by comradekingu** [comment]
@floscapite How are you getting on? Anything I can help with?

**Comment by flosincapite** [comment]
Doing alright! Apologies, had a busy week. I am getting back to this today.
How are you?

**Comment by Harshad-droid** [comment]
Hi, I want to work on this issue. Can I take this up?

**Comment by comradekingu** [comment]
@Harshad-droid I imagine so. Perhaps better to check in with @flosincapite first :)

**Comment by flosincapite** [comment]
Hi, all, I am sorry for the delay. Was camping this week. Let me hold the
lock through Wednesday--I should have something by then, and if I fail, I
will surrender this issue!

**Comment by flosincapite** [comment]
Hey, all, I don't think I'll realistically have time to get to this anytime soon. @Harshad-droid or anybody else, feel free to take it :)
