### ISSUE TITLE
Repository push URL is mandatory when using the API

### ISSUE THREAD

**Issue by mudrd8mz** [WeblateOrg/weblate#3819]
The [documentation](https://docs.weblate.org/en/weblate-4.0.3/admin/projects.html#repository-push-url) reads:

> Repository URL used for pushing. This is completely optional and push support is turned off when this is empty.

Yet when creating a new component via an API call, the "push" parameter is mandatory and can be neither null nor empty.

**To Reproduce**
Attempt to create a new component via CURL POST request with no "pull" parameter provided. You get an HTTP 400 error response like
```
{
    "push": [
        "This field may not be blank."
    ]
}
```

**Expected behavior**
Null, empty or absent "push" value should be allowed to match the API call with the manually editing form.

**Server configuration and status**
Weblate: 4.0.3

**Comment by dakur** [comment]
@nijel I've got v4.0.4 installed but still it is happening in my case.

![image](https://user-images.githubusercontent.com/9862581/84379524-406e0000-abe6-11ea-889b-c1e0236e2bc6.png)

Response: `{"push":["This field may not be blank."]}`

If I omit the `push` property completely, it return e500.

![image](https://user-images.githubusercontent.com/9862581/84379638-78754300-abe6-11ea-8758-78468fd3438a.png)

**Comment by nijel** [comment]
Both work for me, but testing on current master. Can you check the exception traceback for the server error? Maybe better do that in a separate issue...

**Comment by dakur** [comment]
@nijel Where should I search for logs in docker container? I can not find a mention in the docs.

**Comment by nijel** [comment]
Use `docker-compose logs`, see https://docs.weblate.org/en/latest/contributing/debugging.html#weblate-logs

**Comment by dakur** [comment]
@nijel Chm, now it works. We were upgrading from 3.9 to 4.0 yesterday so maybe it was cached somehow? I do not know. But after running `docker-compose logs` it started to work. Thanks for replies.
