### ISSUE TITLE
Alert for lost or changed screenshot context link

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3821]
If a string changes, naturally the static screenshot linked to it will have to, so it needs to be updated.
The same goes for a string that is lost. It may be less of an issue, but the screenshot will in any event not represent reality any longer.
Bonus for having a way to find strings that aren't screenshotted. Something for (another feature request, and) the admin workload list.

**Comment by nijel** [comment]
I've added search `has:screenshot`. Alert for screenshots without a string certainly makes sense.
