### ISSUE TITLE
More detailed credits

### ISSUE THREAD

**Issue by Kyuuu** [WeblateOrg/weblate#3830]
**Is your feature request related to a problem? Please describe.**
I wanted to create game credits this way where the size of the translator name depends on contribution.
![image](https://user-images.githubusercontent.com/33127074/81265110-c96fa580-9042-11ea-89f7-3a7804c18f99.png)
(name lightness based on contribution would be nice also if somebody wants to create credits this way)

**Describe the solution you'd like**
It would be useful to see more details in credits you can export in the translation reports tab. Except the name, e-mail, and translated language, you should find there translated chars/words amount or percent of contribution in the translation of this language. Maybe years also cause I saw few credits (especially on webpages) where to names somebody added years of contribution.

**Describe alternatives you've considered**
//

**Additional context**
//

**Comment by nijel** [comment]
Credits list just names, there is also contributors stats which give you all the details, see https://docs.weblate.org/en/latest/devel/reporting.html#contributor-stats

**Comment by Kyuuu** [comment]
Yeah, you can mix translation stats and credits data to do that if there is only one language for every translator. But if somebody translates a few languages - you don't know the percentage of translations for each language.
