### ISSUE TITLE
User interface language is not restored

### ISSUE THREAD

**Issue by Badiboy** [WeblateOrg/weblate#3833]
**Describe the bug**
When open the Weblate,  the interface always have the ?system? language, in spite of the profile settings.
If you open the profile - the language setting have the correct value. If you save "as is" - interface will change according to the selected settings.

**Screenshots**
1. Open the weblate.
![image](https://user-images.githubusercontent.com/5613421/81330820-564d4a00-90a9-11ea-9f1f-94f8441620d0.png)
2. Open user settings
![image](https://user-images.githubusercontent.com/5613421/81330932-7d0b8080-90a9-11ea-94cf-92c72385f98c.png)
3. Save "as is"
![image](https://user-images.githubusercontent.com/5613421/81330993-9280aa80-90a9-11ea-9156-2da49384e360.png)

**Server configuration and status**
Weblate 4.0.3 from pip on Ubuntu.
In DEBUG mode.

**Comment by nijel** [comment]
It seems to work correctly for me. Do you have `django_language` cookie set in your browser?

**Comment by Badiboy** [comment]
When I open the weblate after open the browser - I have not.
![image](https://user-images.githubusercontent.com/5613421/81335951-168a6080-90b1-11ea-8727-666fd724c33c.png)

Then when I go to settings and save them - It appears with "Session" expiration period.
![image](https://user-images.githubusercontent.com/5613421/81336017-36ba1f80-90b1-11ea-815d-abbbcde61534.png)

**Comment by nijel** [comment]
It should appear on the login. Did you have existing session or login freshly?

**Comment by Badiboy** [comment]
I do not login. I logged in long ago and weblate remebers me. 

Existing session - may be yes, I do not know where/how this "logged in" is stored.

I can try to re-login, may be it wll help...
