### ISSUE TITLE
Direct navigation from screenshot context to screenshot editing

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3836]
Finding a screenshot among many is difficult, because only viewing the screenshot in question or navigating to all of them is possible. Instead it should be possible to go directly to the screenshot in question.

One use-case is making sure other text objects in the same screenshot are mapped.

**Comment by nijel** [comment]
Can you please clarify to what screenshot directly? Identified by name, string, or something else?

**Comment by comradekingu** [comment]
If I am browsing a string, regular editor, the attached screenshot(s) can be found right there on the side.
How do I get to a specific one? If I click the image, I get a bigger version. If I click elsewhere, I get to all of the screenshots, and I have to sort through many screenshots to locate it.
