### ISSUE TITLE
Plurals problem in Chinese language

### ISSUE THREAD

**Issue by Lyaiya** [WeblateOrg/weblate#3837]
In Weblate 4.0.3, plurals should not have **singular** and **plural** in chinese language(such as Chinese (Simplified) and Chinese (Traditional)), it should have only **plural**(such as Korean).

Some examples:
[Plurals in Chinese (Simplified)](https://hosted.weblate.org/translate/tachiyomi/strings/zh_Hans/?q=notification_chapters_multiple_and_more)
[Plurals in Chinese (Traditional)](https://hosted.weblate.org/translate/tachiyomi/strings/zh_Hant/?q=notification_chapters_multiple_and_more)
[Plurals in Korean](https://hosted.weblate.org/translate/tachiyomi/strings/ko/?q=notification_chapters_multiple_and_more)

**Comment by nijel** [comment]
Thanks for pointing this out. I'm not sure how it has happened as we have correct definition in our data. But anyway it's now fixed.

**Comment by Lyaiya** [comment]
It still have some problems in Android strings, look at [Tachiyomi/#2714](https://github.com/inorichi/tachiyomi/issues/2714).

**Comment by nijel** [comment]
Newly saved translations should be correct.

**Comment by Lyaiya** [comment]
> Newly saved translations should be correct.

I already saved translations, when I download translation file in Weblate, it still have the same problem.

**Comment by Lyaiya** [comment]
In a github [commit](https://github.com/inorichi/tachiyomi/pull/3125/commits/08be755bc2ac908a871898f685ad3fa88388f708#diff-722c6062dd4e87d29cdedf7307d50973), the context of `<item quantity="other">` forced move to `<item quantity="one">` in `app/src/main/res/values-zh-rCN/strings.xml`
