### ISSUE TITLE
List the screenshots added to each screenshot

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3841]
When adding elements to a screenshot, is is hard to remember which ones have already been added (onto earlier screenshots).

Currently adding all possible strings to each ones, and then going to "show" each one, finally deleting the connection for the ones that already have something similar.

**Comment by nijel** [comment]
The already added strings should not be shown in the search results, so there should be no need to remember anything.

**Comment by comradekingu** [comment]
Not if trying upload a new image (?)
