### ISSUE TITLE
cleanuptrans broken in 4.0.4 - cannot import name 'cleanup_fulltext'

### ISSUE THREAD

**Issue by ccaputo** [WeblateOrg/weblate#3847]
Am running into an issue where a 100% translated language is not accepting any updates to the source strings.  Is there something special about 100% translated languages that I need to unfreeze?

Trying "weblate cleanuptrans" fails with:

```
    from weblate.trans.tasks import (
ImportError: cannot import name 'cleanup_fulltext'
```

Looks like cleanup_fulltext was removed in fabe5a3cf72a5995db693dbbefc119849f491cf5.

list_versions:

```
 * Weblate: 4.0.4
 * Django: 3.0.6
 * siphashc: 1.2
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.1
 * lxml: 4.2.6
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.9.0
 * oauthlib: 3.0.1
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.10
 * setuptools: 46.2.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.3
 * celery: 4.4.2
 * kombu: 4.6.8
 * translation-finder: 2.0
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.36.1
 * diff-match-patch: 20181111
 * requests: 2.21.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.3
 * Cython: 0.29.17
 * misaka: 2.1.1
 * GitPython: 3.1.2
 * borgbackup: 1.1.11
 * Python: 3.6.8
 * Git: 2.17.2
 * psycopg2-binary: 2.7.6.1
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * aeidon: 1.7.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.14.123-111.109.amzn2.x86_64 (x86_64)
```

**Comment by nijel** [comment]
You really shouldn't need to invoke `cleanuptrans` manually. All necessary cleanups should happen automatically in the background in recent versions.

As for not accepting updates - how do you update it? Are there any errors in the logs?

**Comment by ccaputo** [comment]
> You really shouldn't need to invoke `cleanuptrans` manually.

Should it be removed from the code & docs?

> All necessary cleanups should happen automatically in the background in recent versions.
> 
> As for not accepting updates - how do you update it? Are there any errors in the logs?

Our normal update procedure uses the steps from the script example at https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts but I am finding that for our Korean translation it is not updating.

In the below screenshot, "rout servers" was changed to "route servers".  All languages except Korean and English (the source language) show the change to "route servers".  The Korean language appears wedged and English is showing both the old and the new versions of the string, which also seems odd.  Further, new strings are not showing up in Korean, while they are in other languages.

I've wondered if the cause is because Korean hit 100% translation and somehow that resulted in it becoming frozen in some way?

I have also tried `weblate loadpo --foreground --all` and that has not helped.

The syslog and celery logs are not showing errors.

<img width="838" alt="Screen Shot 2020-05-12 at 9 10 52 AM" src="https://user-images.githubusercontent.com/1417833/81718420-93f6fd80-9430-11ea-8453-d87beb5f8fa3.png">

A check of the git tree (below) shows that "locale/ko/LC_MESSAGES/django.po" has the updated string "route servers".  A "Pull" in "Repository maintenance" does not help.

<img width="838" alt="Screen Shot 2020-05-12 at 9 19 45 AM" src="https://user-images.githubusercontent.com/1417833/81719359-d2d98300-9431-11ea-9c29-d967e739fbaf.png">

**Comment by nijel** [comment]
I've created separate issue for the updates issue - https://github.com/WeblateOrg/weblate/issues/3853

> Should it be removed from the code & docs?

It might be still useful in some corner cases, but in normal operation the cleanups are triggered automatically on regular basis and it's documented that way: https://docs.weblate.org/en/latest/admin/install.html#production-cron and https://docs.weblate.org/en/latest/admin/management.html#django-admin-cleanuptrans

**Comment by ccaputo** [comment]
> I've created separate issue for the updates issue - #3853
> 
> > Should it be removed from the code & docs?
> 
> It might be still useful in some corner cases, but in normal operation the cleanups are triggered automatically on regular basis and it's documented that way: https://docs.weblate.org/en/latest/admin/install.html#production-cron and https://docs.weblate.org/en/latest/admin/management.html#django-admin-cleanuptrans

But trying "weblate cleanuptrans", as mentioned on those pages, fails with:

```
    from weblate.trans.tasks import (
ImportError: cannot import name 'cleanup_fulltext'
```

so a heads-up that it is currently broken with 4.0.4.

**Comment by nijel** [comment]
True, that has been fixed in https://github.com/WeblateOrg/weblate/commit/2fb869b864de446f9d7b2fe84c37246e75465b3d
