### ISSUE TITLE
PO files line wrapping discrepancy between gettext and translate-toolkit

### ISSUE THREAD

**Issue by SlavekB** [WeblateOrg/weblate#3852]
**Describe the bug**
Weblate pushed commit to save new translations. This was followed by the commit for the same language for the same component in response to the msgmerge addon.

The commit for translation made some changes to the page-width wrap, and a subsequent commit for the msgmerge addon reverted those changes.

**Expected behavior**
It is expected that all modules will consider the same page width and will not make any changes that are immediately rolled back.

**Screenshots**
[Commit with translation and changes to the page-width wrap](https://mirror.git.trinitydesktop.org/gitea/TDE/tde-i18n/commit/8fa8cd6244b36f394aa33b686be6f3ec8c209728)
[Commit from msgmerge addon](https://mirror.git.trinitydesktop.org/gitea/TDE/tde-i18n/commit/0add6ab8425b32999e6e6048d7e9b53e8dbeac88)

**Server configuration and status**
```
 * Weblate: 4.0.4
 * Django: 3.0.6
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.1
 * lxml: 4.5.0
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.9.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 46.1.3
 * jellyfish: 0.7.2
 * openpyxl: 3.0.3
 * celery: 4.4.2
 * kombu: 4.6.8
 * translation-finder: 2.0
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.36.1
 * diff-match-patch: 20181111
 * requests: 2.23.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.3
 * Cython: 0.29.17
 * misaka: 2.1.1
 * GitPython: 3.1.2
 * borgbackup: 1.1.11
 * Python: 3.7.3
 * Git: 2.11.0
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * aeidon: 1.7.0
 * Mercurial: 4.8.2
 * git-svn: 2.11.0
 * git-review: 1.25.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django_sendmail_backend.backends.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 3.16.6-042stab141.42 (x86_64)
```
```
System check identified no issues (3 silenced).
```

**Comment by nijel** [comment]
There is some difference in how gettext and translate-toolkit do wrapping and this is the result. But it would be good to bring these two in sync.

**Comment by SlavekB** [comment]
Yes, it would be good if it is consistent, because it looks weird when one commit from Weblate is then immediately overwritten by another commit from the same Weblate :smile_cat:
