### ISSUE TITLE
One translation not being updated

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3853]
> All necessary cleanups should happen automatically in the background in recent versions.
> 
> As for not accepting updates - how do you update it? Are there any errors in the logs?

Our normal update procedure uses the steps from the script example at https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts but I am finding that for our Korean translation it is not updating.

In the below screenshot, "rout servers" was changed to "route servers".  All languages except Korean and English (the source language) show the change to "route servers".  The Korean language appears wedged and English is showing both the old and the new versions of the string, which also seems odd.  Further, new strings are not showing up in Korean, while they are in other languages.

I've wondered if the cause is because Korean hit 100% translation and somehow that resulted in it becoming frozen in some way?

I have also tried `weblate loadpo --foreground --all` and that has not helped.

The syslog and celery logs are not showing errors.

<img width="838" alt="Screen Shot 2020-05-12 at 9 10 52 AM" src="https://user-images.githubusercontent.com/1417833/81718420-93f6fd80-9430-11ea-8453-d87beb5f8fa3.png">

A check of the git tree (below) shows that "locale/ko/LC_MESSAGES/django.po" has the updated string "route servers".  A "Pull" in "Repository maintenance" does not help.

<img width="838" alt="Screen Shot 2020-05-12 at 9 19 45 AM" src="https://user-images.githubusercontent.com/1417833/81719359-d2d98300-9431-11ea-9c29-d967e739fbaf.png">

_Originally posted by @ccaputo in https://github.com/WeblateOrg/weblate/issues/3847#issuecomment-627451043_

**Comment by nijel** [comment]
English showing both strings is expected in this case - it shows strings present in all translations.

Why Korean is not updated is not clear to me. Can you try running `loadpo` with `--force` if that will help?

**Comment by ccaputo** [comment]
`--force` fixed the issue.  Thank you!

This server had gone from 3.3 to 3.6.1 to 4.0.4.  I suspect there was an issue with the upgrade process from 3.3 to 3.6.1 in which we did not complete the migrations.  I first discovered the wedged Korean translation while under 3.6.1.  Upgrading to 4.0.4 didn't help, even with completing the migrations ala `weblate migrate`, but that may have been due to an earlier failure to upgrade properly to 3.6.1.

**Comment by nijel** [comment]
I remember there was bug causing missing some updates, but I though you got this after 4.0 upgrade and not before...

**Comment by ccaputo** [comment]
> I remember there was bug causing missing some updates, but I thought you got this after the 4.0 upgrade and not before...

The failure to show new translations happened under 3.6.1, so I upgraded to 4.0.4 to see if that would fix it.  Apologies for not thinking to mention that in the original post.
