### ISSUE TITLE
Browser's native Cmd/Ctrl+<N> is blocked everywhere

### ISSUE THREAD

**Issue by julen** [WeblateOrg/weblate#3875]
**Describe the bug**
In any Weblate page, pressing Cmd/Ctrl+\<N\> (N being a tab number), will prevent browser's default behavior, which is to change switch to a specific tab.

**To Reproduce**
1. Go to any Weblate page
2. Press Cmd/Ctrl+\<N\> (where N != current tab number)

**Expected behavior**
I understand this is desired behavior for translate pages to enhance the translating experience, however it shouldn't be the case for any other page. Altering/hijacking browser native functionality is usually bad practice, and it interrupts visitors and their expectations.

**Comment by julen** [comment]
One of the source problems here is that code which is meant to be for translate pages is included everywhere, and a natural thing to do would be to split that code apart. I'm happy to provide a fix for this if we can agree on the way forward.

**Comment by nijel** [comment]
I'm not really sure what is best approach to keyboard shortucs, see also https://github.com/WeblateOrg/weblate/issues/2034

**Comment by nijel** [comment]
But it certainly makes sense to bind these only when needed.

**Comment by julen** [comment]
So are you ok with the approach to take the editor code apart? Also, feel free to assign the issue to me.

**Comment by nijel** [comment]
Yes, that sounds good.
