### ISSUE TITLE
MultipleFailingCheck does not respect dismissal of individual checks

### ISSUE THREAD

**Issue by kkotenko** [WeblateOrg/weblate#3878]
**Describe the bug**
The message "The translations in several languages have failing checks" appears even if all of the failing checks have been individually dismissed. The only way to get rid of this (as a translator) is manually checking that there are, in fact, no undismissed failing checks across all translations, and then dismissing the MultipleFailingCheck warning manually in the source language.

**To Reproduce**
1. Create a source language and two translations. 
2. Introduce a string to be translated, without a period at the end (e.g. "example source string")
3. Put a period at the end of both translations (e.g. "example source string transl.")
4. Observe that this has triggered the "period mismatch" warning.
5. Dismiss both of the period mismatch warnings.
6. Observe that the "example source string" still has the MultipleFailingCheck warning despite you dismissing the individual checks.
7. Also observe that this counts as a failing check towards the "Strings with any failing checks" and the "Failed check: multiple failing checks" counter of the source language.

**Expected behavior**
* Dismissed checks are not counted towards the checks aggregated by MultipleFailingCheck.
* The MultipleFailingCheck is not triggered.
* This situation is not counted towards the "Strings with any failing checks" or the "Failed check: multiple failing checks" counter.

**Server configuration and status**
Unfortunately, I don't have direct access to the server, but the version running is Weblate 3.11.3.

**Comment by nijel** [comment]
AFAIR it was intentional that it behaves this way. The intention behind this is that this should indicate potential problems in the source string and dismissed checks on the translations might be indication of that. They can also mean that the check doesn't work well. The question is which of these cases is more likely.

**Comment by kkotenko** [comment]
> AFAIR it was intentional that it behaves this way. The intention behind this is that this should indicate potential problems in the source string and dismissed checks on the translations might be indication of that. They can also mean that the check doesn't work well. The question is which of these cases is more likely.

I can see that being relevant for some checks, but for others, it's downright annoying.

For example, some of our strings trigger the "translation equals source" check, if we are "translating" a common technical term like "Internet". 
Let's say we are translating our project into Spanish, Italian, and Russian. Spanish and Italian would trigger the warning, whereas Russian would not, because it would become "интернет". This is an instance where I want to ignore the fact that Spanish and Italian match the original, but at the same time, I don't want to set the flag "dismiss for all languages" on that string, because I want to be aware if someone accidentally pastes the English string into the Russian field. 

So if I want to stay semantically "clean", I would dismiss the the warning for Spanish and Italian and leave the check stand for Russian. This is a case where I emphatically know what I am doing.

Still, I get that annoying warning about "multiple checks failing". It doesn't even tell me what languages are affected, or what kinds of checks are triggering the warning.

I would also be happy with the following changes instead:

* make this a component-wide or project-wide setting
* display what kinds of checks on what language are triggering the warning, for example:

> The translations in several languages have failing checks:
> - Spanish: period mismatch
> - Italian: double space

**Comment by nijel** [comment]
The unchanged translation check has blacklist to avoid the most common terms which are not translated, so that might use some extending to make it work better.

I've just made changes to better indicate string states in the unit listing, so you can figure out which checks are failing from the other languages tab.
