### ISSUE TITLE
Dismiss or ignore for checks?

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3880]
Currently, the action to hide false positive check is "dismiss", but the check is called "ignored" in many cases. This should be consistent to use only one of the words.

Feedback is welcome which of them sounds better, especially from @comradekingu and @orangesunny ;-).

**Comment by comradekingu** [comment]
As an active choice "dismissal" is the gerund. "ignoring" can be passive, so it doesn't fit as well.

**Comment by nijel** [comment]
That's my impression as well, WIP changes are in https://github.com/WeblateOrg/weblate/pull/3887
