### ISSUE TITLE
The ability to disassociate components from a component-list via the API

### ISSUE THREAD

**Issue by superDross** [WeblateOrg/weblate#3885]
**Is your feature request related to a problem? Please describe.**

I am able to associate component(s) with a component list via the API but not disassociate.

**Describe the solution you'd like**

DELETE method available at `/api/component-lists/<list-name>/components/<component-id>/`

This action should disassociate the component with the component-list.

**Describe alternatives you've considered**

I have checked the REST API docs and there does not seem to be a valid way to do this.

**Comment by kamilgrymuza** [comment]
FYI - this is related to https://github.com/WeblateOrg/weblate/issues/3291
