### ISSUE TITLE
'Stale suggestion removal' addon not removing suggestions that exceed set threshold

### ISSUE THREAD

**Issue by erciccione** [WeblateOrg/weblate#3886]
**Describe the bug**
The `Voting threshold` option of the addon `Stale suggestion removal` doesn't seem to work. I set it to `-1`, but suggestions with -1 or even -2 votes are not removed.

**To Reproduce**
1. Activate the addon and set the threshold to `-1`
2. Downvote a suggestion until you reach or surpass the threshold
3. The suggestion is not removed

**Expected behavior**
Translations exceding or matching the threshold should get removed by the addon.

I'm on Weblate `3.11.3`.

**Comment by nijel** [comment]
There is also age threshold which has to match as well.

**Comment by erciccione** [comment]
Ok, then i misunderstood the point of the addon. I thought it was possible to set `Days to keep` *or*  `Voting threshold`, not that both fields must be true to have a string removed. I see now, thanks.
