### ISSUE TITLE
Check uniqueness of strings with underscores and ampersands for inconsistency

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3888]
Right now (19:10:57)
https://hosted.weblate.org/translate/remmina/remmina/pl/?checksum=7878d7647bc1ea3d#history is   "_Informacje"
But https://hosted.weblate.org/translate/remmina/remmina/pl/?checksum=8a48b7b41568a4d  is
"O programie"

With no check triggered. I think the same might be true for &strings, and maybe neither will show up in searches if the _ or & is in the middle of the word. Treating it all as one word would trigger false positives in URLs. So maybe all without "http"?

**Comment by nijel** [comment]
I'm not sure this makes sense in all cases - one string can be action and second title leading to different translations.
