### ISSUE TITLE
Create a new user via the REST API.

### ISSUE THREAD

**Issue by superDross** [WeblateOrg/weblate#3890]
**Is your feature request related to a problem? Please describe.**

I would like to be able to create an user via the REST API

**Describe the solution you'd like**

Allow `POST` requests at the `/api/users/` endpoint.

**Describe alternatives you've considered**

I have checked the REST API docs and there does not seem to be a valid way to do this.

**Comment by nijel** [comment]
The POST should work there, but the documentation for it seems missing.

@SaptakS can you please add it?

**Comment by superDross** [comment]
You are right. Just tested and it works fine. Thanks :)

**Comment by SaptakS** [comment]
Sure. I am on it.
