### ISSUE TITLE
The ability to add & revoke access to an existing component via the API

### ISSUE THREAD

**Issue by superDross** [WeblateOrg/weblate#3892]
**Is your feature request related to a problem? Please describe.**

I would like to be able to restrict specific component access to some users. 

**Describe the solution you'd like**

The ability to compose and apply a blacklist of components a user cannot access. 

**Describe alternatives you've considered**

I have considered creating specific permissions that would allow me to implement this behavior but, as far as I know, we cannot create our own permissions.

**Comment by superDross** [comment]
I think I may have misunderstood how access control is handled in Weblate

**Comment by nijel** [comment]
See also #3267
