### ISSUE TITLE
Uploaded a replacement `.po` file does not take immediate effect

### ISSUE THREAD

**Issue by blackfedora** [WeblateOrg/weblate#3896]
**Describe the bug**
When using the `api/translations/<proj>/<comp>/<lang>/file` to upload a file the changes are not applied to the relevant units/translations/components.

**To Reproduce**
1. Make a POST request to the `api/translations/<proj>/<comp>/<lang>/file/` endpoint with `method: "replace"` and `overwrite: true`. Your request should also include a bilingual po file. It should change at least one existing source-translation pairing and also introduce at least one pairing for a previously undefined source. 
2. The request should come back with a 400 response. However, if you then go to `/projects/<proj>/#repository` in the admin, you'll see that you're now 1 commit ahead of master. Repeating your request should return a 200 response as normal. 
3. Now visit `/translate/<proj>/<comp>/<lang>/?q=` in the weblate admin and you'll see that none of the changes in the new .po file are present. You can also verify this by GETing `api/translations/<proj>/<comp>/<lang>/units/`.
4. Now push your changes through the weblate admin/api (e.g. `POST /api/translations/test-project/comp/nl/repository/` with `operation: "push"`). 
5. Visit your upstream repository to verify that your new .po file has been updated there. If you repeat step 3 at this point you will not see the new changes applied. 
6. Now reset all local changes through the weblate admin/api (e.g. `POST /api/translations/test-project/comp/nl/repository/` with `operation: "reset"`). 
7. Repeat step 3 and see that your changes are now reflected in the weblate data. 

Note: An alternative to pushing/resetting through the vcs operations is to go to `/settings/<proj>/<comp>/#files` and change the "Edit Base File" setting. It doesn't matter whether you turn the setting on or off, just that you change it. This is especially weird as that setting relates to monolingual .po files and we're working with bilingual .po files here. 

**Expected behavior**
I would expect the changes in the uploaded file to immediately be applied to the weblate data (the units/translations/components)

**Server configuration and status**
``` 
* Weblate: 4.0.4
 * Django: 3.0.6
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.1
 * lxml: 4.3.2
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.9.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.1
 * celery: 4.4.2
 * kombu: 4.6.8
 * translation-finder: 2.0
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.23.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.3
 * Cython: 0.29.17
 * misaka: 2.1.1
 * GitPython: 3.1.2
 * borgbackup: 1.1.11
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.7.7
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.13.4
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * Mercurial: 5.4
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * hub: 2.13.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.example.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.5.13-arch2-1 (x86_64)
```

```
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail ([Errno -2] Name or service not known), please check EMAIL_* settings.
	HINT: https://docs.weblate.org/en/weblate-4.0.4/admin/install.html#out-mail

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.0.4/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.0.4/admin/backup.html

System check identified 7 issues (1 silenced).
```

**Additional context**
Example .po file:
```
msgctxt "Dialog title"
msgid "Log in"
msgstr "Sign in"

msgid "foo!"
msgstr "bar!"
```
Note: The "Log in" source string exists but previously mapped to "Log in". Meanwhile, "foo!" does not yet exist as a source string.

**Comment by nijel** [comment]
The upload is supposed to parse the file as well. The http 400 indicates that there was some error in processing the request. Can you check server logs and the response payload to see what went wrong?

**Comment by blackfedora** [comment]
The body of the 400 is:
'{"result":false,"detail":"Unit matching query does not exist."}'

Even with `WEBLATE_DEBUG: 1` in my docker-compose.override.yml I'm not seeing a log entry for this request (this is just using `docker-compose logs`, let me know if there's somewhere else you'd like me to look.

**Comment by nijel** [comment]
It turns out that the error is silently ignored here, I've already fixed that in master. But I think I now know where the problem is...
