### ISSUE TITLE
Create a new group via the REST API

### ISSUE THREAD

**Issue by superDross** [WeblateOrg/weblate#3898]
**Is your feature request related to a problem? Please describe.**

I would like to be able to create an new permission group via the REST API

**Describe the solution you'd like**

Allow POST requests at the `/api/groups/` endpoint.

**Describe alternatives you've considered**

I have checked the REST API docs and there does not seem to be a valid way to do this.

**Comment by nijel** [comment]
Again, it's only docs what is missing. It's on the way in https://github.com/WeblateOrg/weblate/pull/3894
