### ISSUE TITLE
Unlabeled string status

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3900]
Going through all strings in a project forces an admin to comment as "unlabeled" for every skipped string, whereas having "unlabeled" would solve this.

**Comment by nijel** [comment]
You can already search strings without a label: `NOT has:label`

**Comment by comradekingu** [comment]
Thank you, I will stop annoying people with comments.
Can't tell if I would expect to see it at the top or bottom. Top maybe?
![image](https://user-images.githubusercontent.com/13802408/82319391-0469c580-99c1-11ea-9d35-c9b1b3c25c19.png)
