### ISSUE TITLE
The ability to add multiple component-lists to a permissions group.

### ISSUE THREAD

**Issue by superDross** [WeblateOrg/weblate#3905]
**Is your feature request related to a problem? Please describe.**

Currently we can only add one component-list to a permission group and I would like to be able to add multiple. 

**Describe the solution you'd like**

Be able to POST multiple component lists to `/api/groups/(int: id)/componentlists/`.

**Comment by kamilgrymuza** [comment]
FYI - this issue is related to https://github.com/WeblateOrg/weblate/issues/3647 and https://github.com/WeblateOrg/weblate/issues/3646
