### ISSUE TITLE
[Documentation] Clarify "Consecutive duplicated tokens" check

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#3906]
Hi,

A new validation check is done on translations in last Weblate version, see documentation:
https://docs.weblate.org/en/latest/user/checks.html#check-duplicate

Can you please clarify by adding a sample or by defining what a "token" is in this context?
Because this check has been raised on some strings but I didn't understand why and "ignored" it.

Thanks,

**Comment by nijel** [comment]
It seems that the name could have been chosen better, see https://github.com/WeblateOrg/weblate/issues/3702 and https://github.com/WeblateOrg/weblate/pull/3797

**Comment by nijel** [comment]
CC @flosincapite
