### ISSUE TITLE
Nope

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3908]
Right now it is 3 - 2 - 1 and 1 - 2 - 3 (which is the most natural order of adding things).
![image](https://user-images.githubusercontent.com/13802408/82320125-49dac280-99c2-11ea-93a2-090f0bf76115.png)
I would want it to be 1 - 2 - 3 and 1 - 2 - 3 That way it is the same order, and the visual scrolling distance is kept to a minimum when I want to know what I added last.
Bonus: Manual sorting would be great, for example if I added "remove", it should be nr 3 / 4.
Maybe @flosincapite wants to have a look :)

**Comment by flosincapite** [comment]
Sure, can do after the current issue.

**Comment by flosincapite** [comment]
Er, never mind, haha.
