### ISSUE TITLE
Ctrl/Cmd+Y doesn't toggle fuzzy flag when textarea has focus

### ISSUE THREAD

**Issue by julen** [WeblateOrg/weblate#3910]
**Describe the bug**
Pressing Cmd+Y for toggling the "Needs editing" flag doesn't work when the editing textarea has focus. When focus is somewhere else, toggling works fine.

I tried this in Mac, but I suspect the behavior is the same in other platforms when using the Ctrl+Y shortcut, because I see [`testChangeHandler`](https://github.com/WeblateOrg/weblate/blob/2353916da58f5626c1b5ccd63ebbe6f925bdb974/weblate/static/loader-bootstrap.js#L290-L295) will be invoked for every keypress, including keyboard shortcuts.

**To Reproduce**
1. Open editor and focus editing textarea
2. Press Ctrl/Cmd+Y

**Expected behavior**
"Needs editing" flag is toggled.

**Comment by nijel** [comment]
Confirmed on Linux.
