### ISSUE TITLE
Cmd+M doesn't switch to Machine Translation tab

### ISSUE THREAD

**Issue by julen** [WeblateOrg/weblate#3911]
**Describe the bug**
In Mac, pressing Cmd+M doesn't switch Weblate to the Machine Translation tab. Instead, it triggers the native Mac behavior of minimizing the current window.

Other platforms to be confirmed.

**To Reproduce**
1. Open the editor
2. Press Cmd+M

**Expected behavior**
Machine Translation tab is opened.

**Comment by nijel** [comment]
It seems to sometimes work in Firefox on Linux. For most of the time the default browser action is executed.

**Comment by julen** [comment]
Ok, that sounds racy. The default must be prevented the same way we did for Ctrl/Cmd+I in #3891; I verified that works fine in Mac.

Nonetheless let me get back to these shortcut issues once I split the editor code as suggested in #3875.
