### ISSUE TITLE
Consecutive duplicated tokens

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#3926]
**Describe the bug**
I don't understand the warning in this string: https://hosted.weblate.org/translate/po4a/po4a-doc/fr/?checksum=97fc5f04e7c1628e

English content is:  This chapter gives you a brief overview of the po4a internals, so that you may feel more confident to help us maintaining and improving it. It may also help you understanding why it does not do what you expected, and how to solve your problems.

Translation is: Cette section vous donne un bref aperçu des rouages internes de po4a afin que vous vous sentiez plus à même de nous aider à le maintenir et l’améliorer. Elle peut également vous permettre de comprendre pourquoi cela ne fait pas ce que vous souhaitez et corriger vos problèmes par vous-même.

**To Reproduce**
1. Go to https://hosted.weblate.org/translate/po4a/po4a-doc/fr/?checksum=97fc5f04e7c1628e

**Expected behavior**
No warning.

**Additional context**

If it is related to the double "vous", it is correct in french: https://www.linguee.fr/francais-anglais/search?source=auto&query=vous+vous+en+occupez

**Comment by nijel** [comment]
Seems like we will need a blacklist for some languages in the end. I wanted to avoid that, see https://github.com/WeblateOrg/weblate/pull/3797

**Comment by Jibec** [comment]
Maybe we need to measure false positives versus real issues. I don't know if it worth the effort.

Can you do this with the current database model?

What ever the solution, just highlight or quote the repetition would make my life easier.
I searched a few minutes to find it 😅

**Comment by nijel** [comment]
The problem will be indicated nicely since 401eb8bdb2d628c7ffecc83dc67ebaca3e94de9a

**Comment by nijel** [comment]
In the most cases the trigger seems legit. I've fixed some corner cases now (it was catching digits as well).

What indeed seems to be problematic is French ;-). The "vous" and "nous" seems to be the most frequent ones.

**Comment by Jibec** [comment]
Thank you
