### ISSUE TITLE
Weblate not uploading vendor translations files for some components 

### ISSUE THREAD

**Issue by jmanaks1** [WeblateOrg/weblate#3931]
I recently received translated files back from our translation vendor, and only some of the strings we received are being updated within Weblate.  I've attached some of the files that haven't worked (but only from one language of each component...there are 17 language translations for each component), and here are the links to the components that aren't working:

https://fsmisc3.cg.na.jci.com/admin/trans/component/173/change/
https://fsmisc3.cg.na.jci.com/admin/trans/component/174/change/
https://fsmisc3.cg.na.jci.com/admin/trans/component/175/change/

For reference, the components that do work are:

https://fsmisc3.cg.na.jci.com/admin/trans/component/187/change/
https://fsmisc3.cg.na.jci.com/admin/trans/component/176/change/
https://fsmisc3.cg.na.jci.com/admin/trans/component/188/change/

The main interface for these translations in Weblate can be found here: 

https://fsmisc3.cg.na.jci.com/projects/metasys/

**Comment by nijel** [comment]
* fsmisc3.cg.na.jci.com doesn't seem to resolve, probably it is your private on site installation?
* No files are attached, so nothing to look at.
* Do you get some errors while doing that?
* What Weblate version do you use?

**Comment by KatieHolterman** [comment]
The comment above was actually my request, and my colleague was kind enough to locate this forum for me.

Upon further investigation, I think I found the problem.  It seems that the developers removed/moved some of the source strings.  Is there a way to remove unused strings from Weblate that are no longer in the source files?  That would help prevent us from spending money on translations that are no longer necessary.

Thanks for all the help.

**Comment by nijel** [comment]
For monolingual formats, just remove them from the base file. For bilingual ones, all files have to be updated. With Gettext you can utlize https://docs.weblate.org/en/latest/admin/addons.html#addon-weblate-gettext-msgmerge
