### ISSUE TITLE
Is a "context" a valid name?

### ISSUE THREAD

**Issue by Kyuuu** [WeblateOrg/weblate#3934]
I wondered about name "context". "Context" is something that should describe key (explain what is it used for or why you should be carefully translating it).

So context (and additional context) is really "context" (green arrow).

However "context" that is marked with blue arrow is just application/game translation key and it may be something not useful in translation like ItemName_00023 - just something for programmers that translator do not have to care about.

![image](https://user-images.githubusercontent.com/33127074/82753490-5007df00-9dc6-11ea-95a7-9c19e8b34826.png)

So wouldn't this way of naming be better?
![image](https://user-images.githubusercontent.com/33127074/82753639-4df25000-9dc7-11ea-93ba-6a901fbd83ca.png)

Also I am not sure how it is in other languages but in Polish "kontekst" means only "meaning" so it is a bit bad translation for key.

**Comment by nijel** [comment]
See https://github.com/WeblateOrg/weblate/issues/3716#issuecomment-612404919 and https://github.com/WeblateOrg/weblate/issues/3716#issuecomment-612609520, even after split of "explanation", the "context" is used for two things, depending on file format:

* `msgctxt` from gettext PO files
* keys from monolingual files
