### ISSUE TITLE
Some SVG Icons are not visible

### ISSUE THREAD

**Issue by maka1000** [WeblateOrg/weblate#3937]
In my Dashboard of Weblate 4.0.4 are not all icons visible (See screenshot). When I copy the picture adress and check it in a new tab it show this:

`<svg width="14" height="14" version="1.1" viewBox="0 0 14 14" xmlns="http://www.w3.org/2000/svg"><path d="m0 1 3.5 5 3.5-6 3.5 6 3.5-5-1 9h-12zm13 12c0 0.6-0.4 1-1 1h-10c-0.6 0-1-0.4-1-1v-1h12z" fill="#2a3744"/></svg>`

![screenshot](https://user-images.githubusercontent.com/19875641/82767878-1ddc9880-9e2b-11ea-85ab-c7854ebdd96f.jpg)

**Comment by nijel** [comment]
Do you see any error in the browser console?  What browser do you use?

**Comment by maka1000** [comment]
I use the latest Chrome Version 83.0.4103.61 (Offizieller Build) (64-Bit). I tried also the inkognito tab.
Just checked in firefox, there it is working well.

Chrome Console:
```
Resource interpreted as Stylesheet but transferred with MIME type text/plain: "<URL>".
loader-bootstrap.js?v=4.0.4:1573 Stop!
loader-bootstrap.js?v=4.0.4:1574 This is a console for developers. If someone has asked you to open this window, they are likely trying to compromise your Weblate account.
loader-bootstrap.js?v=4.0.4:1578 Please close this window now.
DevTools failed to load SourceMap: Could not load content for https://weblate.xxx.com/static/bootstrap/css/bootstrap-datepicker3.css.map: HTTP error: status code 502, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://weblate.xxx.com/static/chartist.css.map: HTTP error: status code 502, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by nijel** [comment]
I've just tested with same Chrome build and it works just fine for me. Any extensions in the browser which might be causing this?

**Comment by nijel** [comment]
Also, does the rendering break on our instance as well? For example, try looking at https://hosted.weblate.org/projects/minetest/
