### ISSUE TITLE
Add API for addons

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3948]
There is current ly no API for addons, it should allow:

* Listing enabled addons
* Adding new addon (with configuration)
* Changing configuration of existing addons
* Removing addons

> The addon looks promising. I think this would still need manual intervention to enable the addon on each translation component. I am trying to reduce the manual process related to setting up of a translation component to none or minimum. 
Could we enable and configure this addon via APIs? That would help even more since we wouldn't have to trigger the auto-translation everytime a string is added.

_Originally posted by @jojurajan in https://github.com/WeblateOrg/weblate/issues/3930#issuecomment-633831015_

**Comment by nijel** [comment]
Related to https://github.com/WeblateOrg/weblate/issues/3930

**Comment by prateekj117** [comment]
@nijel I can have a look at it.

**Comment by nijel** [comment]
@prateekj117 You're welcome.
