### ISSUE TITLE
Java properties not parsed from subversion

### ISSUE THREAD

**Issue by Glandos** [WeblateOrg/weblate#3949]
**Describe the bug**
A project stored in subversion is not parsed after import. The project is stored in subversion, using standard `svn://path/to/project/{branches,trunk/tags}` schema, and a classical Java hierarchy `src/com/example/project/resources/messages_*.properties`

**To Reproduce**
1. Add a component in a project
2. Fill out the form, with everything as expected
3. Autodiscovery works well: it finds all my properties and fill out forms automatically
4. After summary, click on save
5. The "progress" page is skipped instantly, without reading files
6. Component page is empty, only showing the base language with 0 string.

**Expected behavior**
I should see the progress page, and the component page should list all my languages and strings.

**Server configuration and status**
```sh
(weblate-env) weblate@translate:~$ weblate list_versions
 * Weblate: 4.0.4
 * Django: 3.0.6
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.1
 * lxml: 4.5.1
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.9.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 46.4.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.3
 * celery: 4.4.2
 * kombu: 4.6.8
 * translation-finder: 2.0
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.36.1
 * diff-match-patch: 20181111
 * requests: 2.23.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.4
 * Cython: 0.29.19
 * misaka: 2.1.1
 * GitPython: 3.1.2
 * borgbackup: 1.1.11
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * aeidon: 1.7.0
 * git-svn: 2.20.1
 * git-review: 1.27.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: domino01.nst.gls-germany.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.19.0-9-amd64 (x86_64)
(weblate-env) weblate@translate:~$ weblate check --deploy
System check identified no issues (5 silenced).
```

**Additional context**
I tried with and without branch with svn: same result.
I tried to copy all files into a local folder, initialize a git repository in it, and then load it with `git` as VCS: I have the expected result, so it works.

It seems that the workflow with `git-svn` is broken, but I don't know where to start debugging.

**Comment by nijel** [comment]
How do you specify repository URL? It might be tricky in some cases, see https://docs.weblate.org/en/latest/vcs.html#subversion

**Comment by Glandos** [comment]
I forgot to say that since it's an internal repository, anonymous checkout is available. So I just wrote `svn://server/path/to/project` with `trunk` as branch.
As I stated in the reproduction step, the project is checked out, and the finder finds my translation, so I *think* that my URL is correct.

**Comment by nijel** [comment]
If it finds the translation, there should be no problem in loading. What error do you get?

**Comment by Glandos** [comment]
That's the point: I get exactly no error from weblate. Just that translations are not loaded from property files.

**Comment by nijel** [comment]
So the component is created, it just shows no translations? Or empty translations? The parsing itself happens in background, it might be caused by Celery worker not running. Do you get any errors from `weblate check --deploy`?

Another reason might be that the chosen format is wrong? Look at encoding of these files and choose matching format.

**Comment by Glandos** [comment]
Here is a more detailed use case:
- Add a component in a newly created project, with SVN
- Go to the filesystem, copy project to temporary with `cp -r $DATA_DIR/vcs/project/component /tmp/test_project`
- Init git in it `git init /tmp/test_project`
- Add all files and commit `git add .; git commit -m 'First commit'`
- Add a 2nd component in the same project, with Git and `/tmp/test_project`

With SVN, I just have a component with the source language (English) with no strings.

With Git, I have a component with all languages with all strings.

As a strange behavior, after updating some settings (e.g. the name) in the SVN component, I have an alert on the VCS:
```
16 | 2020-05-27 10:36:13.726568+02 | UnsupportedConfiguration | {"vcs": true, "file_format": false} |           14
```
It is rendered with:

![Screenshot_2020-05-27 Unitronics RUDA010 (SVN)](https://user-images.githubusercontent.com/297578/82999797-d52f0600-a009-11ea-8514-4bbd61a149c8.png)

However, I think I have all the dependencies needed: subversion and git-svn. Am I missing something?

**Comment by nijel** [comment]
Maybe Celery process was started prior to installing subversion? That could probably explain the weird behavior.

**Comment by Glandos** [comment]
> Maybe Celery process was started prior to installing subversion? That could probably explain the weird behavior.

Hooray!
Yes, that was it. And indeed, I started celery early in the process, and missed `subversion` package (on Debian, `git-svn` doesn't fetch `subversion`, but it is required by Weblate for support). Of course, I forgot about celery then.

I don't know if it's easy to add some consistency check between celery and the main WSGI script. Or use systemd logic to depends on each other, but it's rather complicated, and maybe obtrusive.

**Comment by nijel** [comment]
> I don't know if it's easy to add some consistency check between celery and the main WSGI script. Or use systemd logic to depends on each other, but it's rather complicated, and maybe obtrusive.

That's good idea, it should not be that hard to add some basic check for this.
