### ISSUE TITLE
Per-component visibility controls

### ISSUE THREAD

**Issue by blackfedora** [WeblateOrg/weblate#3950]
**Is your feature request related to a problem? Please describe.**
From the documentation:

> Checking access to a project
> A user has to be a member of a group linked to the project or **any** component inside it. Only membership is enough, no specific permissions are needed to access a project (this is used in the default Viewers group, see Default groups and roles).

I would like the ability to grant a group access to a single component without also making every component in the project visible to them. Some of our users represent competitors within the same industry, so having access to each other's translations files would constitute a data breach. 

**Describe the solution you'd like**
Assume we have private project P with components C1, C2, C3, and group G which does not have access to P, but does have access to C1 and C2. When viewing P in weblate group members would only see C1 and C2. C3 would remain inaccessible to them.

**Comment by kamilgrymuza** [comment]
FYI - this issue is related to https://github.com/WeblateOrg/weblate/issues/3646

**Comment by kamilgrymuza** [comment]
Would it be possible to expose the `restricted` attribute of a component via the API? It seems that currently there's no way to control this behaviour through the RESTful API :/

**Comment by nijel** [comment]
Yes, added in 77bd8f2c40

**Comment by kamilgrymuza** [comment]
Awesome, thank you @nijel 👍 

Would it be possible to include that in some kind of a hotfix release, next time you guys are releasing something (especially within the docker container)?

**Comment by nijel** [comment]
Yes, there will be 4.1.1, most likely tomorrow or on Monday.

**Comment by kamilgrymuza** [comment]
That is great! Thanks again @nijel :)
