### ISSUE TITLE
“Search and replace” tool unavailable at project level with a language specified

### ISSUE THREAD

**Issue by fitojb** [WeblateOrg/weblate#3954]
The **Tools > Search and replace** option is available both in individual project components:
* e.g. https://translations.documentfoundation.org/projects/libo_help-master/auxiliary/es/
... and at the project level:
* e.g. https://translations.documentfoundation.org/projects/libo_help-master/
... but not if I choose a language from that project:
* e.g. https://translations.documentfoundation.org/languages/es/libo_help-master/ ← here, clicking Tools doesn’t give you the Search and replace function.

**Comment by nijel** [comment]
Related to #3701

You can limit the scope on project level by adding language constraint: `something AND language:es`

See https://docs.weblate.org/en/latest/user/search.html for query language documentation.

**Comment by jmontane** [comment]
My use case is when you want to make a change-all terminology term. Or you want to review all same-structured sentences "Are you sure...". 

I expected something similar to "filter" feature, and then be able to edit strings. Searching works great, but it's a nightmare to edit all matching strings. And "search and replace" is very dangerous. I want to edit filtered/matching strings easily.

**Comment by fitojb** [comment]
> You can limit the scope on project level by adding language constraint: something AND language:es

This doesn’t seem to work in the Search and replace form, only in the Search tool.

An alternative solution could be to provide a language drop-down.
