### ISSUE TITLE
unable to add new language - plain English (en) is missing 

### ISSUE THREAD

**Issue by ReneBoehm** [WeblateOrg/weblate#3963]
Currently we are using Weblate 3.9.1 (docker image) and got a project with a plain English (en) translation which was created a while ago with an old version of weblate. Now we want to add another project, also with a plain English (en) translation but it doesn't exist anymore. Only other "specialized" english locale can be selected. I've tried to add it in the admin portal but no section "Weblate Languages" (as written in the documentation) exists.

How can I add a plain English (en) translation for a project ?

**Comment by nijel** [comment]
Probably English is set as your source language, please change it to match your expectations, see https://docs.weblate.org/en/latest/admin/projects.html#project-source-language

**Comment by ReneBoehm** [comment]
You are right, the source language is English. But my description was slightly wrong. I'm not trying to add a new translation to an existing component. The project has 4 components at the moment and 2 of them have plain English translations (beside German). But I'm not able to add the plain English translation to the other 2 components.
Sorry for the confusion.

**Comment by nijel** [comment]
So you want to edit source strings? That's available with monolingual translations. In more recent versions, you will always get source language present because we need it for additional features.

**Comment by ReneBoehm** [comment]
No, the primary goal is to translate english patterns to German but sometimes it's neccessary to translate "technical" patterns to English, i.e. replace placeholders with a full text.

**Comment by ReneBoehm** [comment]
Ah, it seems when I add an en.po file (we are using gettext) in the source repo, the language is automatically assigned :) That solves my issue.

**Comment by nijel** [comment]
Great, however with this you will probably hit https://docs.weblate.org/en/latest/faq.html#faq-duplicate-files after upgrade
