### ISSUE TITLE
Error during login with Azure AD Guest User

### ISSUE THREAD

**Issue by sthomae01** [WeblateOrg/weblate#3968]
We are using Weblate on a Kubernetes Cluster of Microsoft Azure. For login we are using an Active Directory with the setting "WEBLATE_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_TENANT_ID". When a guest user of this Directory tries to login, this error occurs: "No E-mail-address received by a third-party athentication service. Please register by E-mail instead" 

**To Reproduce**
1. Having a Guest account in Azure AD
2. Go to Sing-In screen of Weblate
3. Click on Sign-In

**Expected behavior**
A successful login.

**Screenshots**
![image](https://user-images.githubusercontent.com/66111968/83238735-26b8cb80-a197-11ea-971b-4b036e2e2d2b.png)

**Server configuration and status**
list_versions:
* Weblate: 4.0.4
 * Django: 3.0.6
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.1
 * lxml: 4.3.2
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1  
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.9.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.1
 * celery: 4.4.2
 * kombu: 4.6.8
 * translation-finder: 2.0
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.23.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.4
 * Cython: 0.29.19
 * misaka: 2.1.1
 * GitPython: 3.1.2
 * borgbackup: 1.1.11
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.7.7
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.13.16
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * Mercurial: 5.4
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.tegos.eu
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://:mjEW4Q$PTknvQfPx@redis-svc:6379/2, redis://:mjEW4Q$PTknvQfPx@redis-svc:6379/2, regular
 * Platform: Linux 4.15.0-1069-azure (x86_64)

check --deploy
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.0.4/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.0.4/admin/backup.html

System check identified 4 issues (1 silenced).

**Comment by nijel** [comment]
Can't you set email for the guest user? Weblate currently relies on that being present.

**Comment by sthomae01** [comment]
They have an e-mail-address in the directory. It's just that they need to be guests because their e-mail-address is different from our company-address. To me it seems like Weblate does not read the e-mail address because of the guest-user state.

**Comment by nijel** [comment]
This is what it does to get it: https://github.com/python-social-auth/social-core/blob/417b607fe4fa0e4cb2f490938d9902c7a889e427/social_core/backends/azuread.py#L73

**Comment by sthomae01** [comment]
Okay, I'll open up a new [issue](https://github.com/python-social-auth/social-core/issues/467) in the social core github

**Comment by jwo-qa** [comment]
I have exactly the same issue with Weblate 4.5.2-1. AzureAD Tenant is not working for guest users. 
Python Social Auth does not seem to be maintained anymore (sthomae01's [issue](https://github.com/python-social-auth/social-core/issues/467) was never answered). 
Are there any ideas how to resolve this issue?

**Comment by nijel** [comment]
https://github.com/python-social-auth/social-core/pull/594 might address this, can you test that?
