### ISSUE TITLE
Creating fake base language for monolingual website?

### ISSUE THREAD

**Issue by okainov** [WeblateOrg/weblate#3973]
I'm trying to integrate i18n into my website. What I had is PHP arrays with numeric indexes like `$TRANSLATION[123]` and several different files depending on the language defining this global variable. The main language of the website is not English. I've decided to go with `gettext` approach.

From what I understood from the docs, monolingual scheme should fit here with the `123` and others as `msgid` and the corresponding text as "translation". However I do not understand how can I make the website translatable to all languages, keeping this pseudo-ID-language as a base.

What I was thinking to do is following `locale` folder:
```
│
├───be
│   └───C
│       └───LC_MESSAGES
│               messages.mo
│               messages.po
│
├───dev
│   └───C
│       └───LC_MESSAGES
│               messages.mo
│               messages.po
│
├───en
│   └───C
│       └───LC_MESSAGES
│               messages.mo
│               messages.po
│
├───ru
│   └───C
│       └───LC_MESSAGES
│               messages.mo
│               messages.po
│
└───ua
    └───C
        └───LC_MESSAGES
                messages.mo
                messages.po
```

Where English is empty translation for now (like `msgid "123" msgstr ""`), `dev` is the "internal" autogenerated translation  (like `msgid "123" msgstr "123"`) and the other languages containing the normal translations (like `msgid "123" msgstr "Тестовая строка"` for russian, for example).

The point is that I'd like to be flexible in the "main" language, eventually it can be either Russian or English, in the same way I do not want to restrict translators to use one source language - someone can use Russian to complete Ukrainian translation and the other guy might use English to complete French translation. As a developer I can either add ID and then provide the proper text in one or more languages or I can just enter the text i.e. in English (in long-term perspective I might want to replace all IDs to English strings, but it's for sure not for now).

The problem with Weblate I have is that it doesn't like my `dev` language complaining `Error template language(dev) does not match project language en`. But I haven't set up any "project language" and actually, as mentioned above, I don't even want to have a single "project language" really. If I change `.po` file for `dev` translation to have `en` as a language, then Weblate will complain for two files for the same language...

Could you please advise, how should I structure monolingual project? Example from the [documentation](https://docs.weblate.org/en/latest/formats.html#monolingual-gettext) assumes there is a base language, but there is none...
Can it be that the whole example in documentation is wrong and one should NOT use monolingual case when having IDs as gettext identifiers?

**Comment by nijel** [comment]
The monolingual base should be the file which has the initial string to translate, according to your description it seems to be English file.

* The source language is configured at project level, see https://docs.weblate.org/en/latest/admin/projects.html#source-language
* Users can configure languages they understand, and they are shown to them regardless what is actual source language, see https://docs.weblate.org/en/latest/user/profile.html#secondary-languages
* You can exclude languages you do not want to translate (dev) by language filter, see https://docs.weblate.org/en/latest/admin/projects.html#language-filter

**Comment by okainov** [comment]
>which has the initial string to translate, according to your description it seems to be English file.

Not really true, initial strings are IDs in general and they don't belong to any language really. Eventually in long-term it might change and become English, that's true.

>The source language is configured at project level, see

Yeah, I think that was the part I was missing, it was not intuitive to find where to configure source language, I ended up changing this from Django Admin.

So currently I made en_devel as my project's main language (which btw is not really true for me, I'd prefer to have it named just "devel" or something similar), so it enabled translations to all Russian, English and other languages. I think I'm quite fine with this now. 

As for more actionable feedback items, I think it would make sense to:
- Show source language selector during project creation. Default is English, it's fine, but it's not really obvious where to change it even from the documentation (I was looking at my project settings, to the documentation in circles trying to find out where is this option)
-- No really proposal here, but maybe consider better organization of the projects without "source" language. It's a bit confusing when the tool asks me to select "source" language at all, when I have none.
- Mention/highlight in the documentation the way of setting main monolingual file to "fake" "en_devel" language which would definitely help people like me to get started with similar type of projects/translation (using IDs)

**Comment by nijel** [comment]
> Show source language selector during project creation. 

Already done in da65137dc14d29c8b2b931ff1cf0b745bf86402c

> It's a bit confusing when the tool asks me to select "source" language at all, when I have none.

Yes, but there has to be initial strings to have something to translate. Translator has no other means to figure out what id "123" means. Whatever developer provides is the source string. Weblate needs to know what language it is to be able to use machine translation or translation memory. With monolingual files, it's possible to edit the source strings within Weblate, so you can fix the mistakes developers did in the language. If you want more control over that and separate what developers and translators care about, you can use https://docs.weblate.org/en/latest/workflows.html#source-quality-gateway
