### ISSUE TITLE
Status widget text is cut off

### ISSUE THREAD

**Issue by jepler** [WeblateOrg/weblate#3974]
**Describe the bug**
The horizontal and vertical multi language status widgets cut off a language with a very long name

**To Reproduce**
1. Go to https://hosted.weblate.org/widgets/circuitpython/?lang=&component=master#multi
2. Scroll down to 'color variants'
3. Look at the text on the image
4. The text of the long translation name "Chinese (Simplified) (zh_LATN@pinyin)" is truncated

**Expected behavior**
The whole name of the translations is visible

**Screenshots**

**Server configuration and status**
On hosted.weblate.org

**Additional context**
We can probably rename this translation language in the source tree (zh_Latn_pinyin.po) if it will resolve the problem.  However, the "correct" naming is not clear to me, and there is no easy way to experiment.

Browser is Firefox 76.0.1

**Comment by jepler** [comment]
![image](https://user-images.githubusercontent.com/1517291/83368830-d8b2ec00-a37f-11ea-922a-9e3a9f4d7fa2.png)

**Comment by jepler** [comment]
How long will it take for this change to be live on hosted.weblate.org?  I checked just now and my icon is still served with width=400
```$ curl -s https://hosted.weblate.org/widgets/circuitpython/-/master/multi-red.svg | head

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="400" height="225" xml:lang="en">
```

**Comment by nijel** [comment]
It will be there during this week.
