### ISSUE TITLE
Cloning source string simply moves to next string

### ISSUE THREAD

**Issue by rffontenelle** [WeblateOrg/weblate#3979]
**Describe the bug**
Pressing the "Clone source" button in the normal editor makes it go to next translation string, without actually cloning the text.

**To Reproduce**
1. Enter normal editor to translate some string
2. Press "Clone source" button
3. Weblate window is updated if other source string
4. Go back to previous string to see nothing was applied

**Expected behavior**
Once the "Clone source" button is pressed, expected to have the source string copied to the translated text.

**Screenshots**

**Server configuration and status**
Hosted Weblate

**Additional context**
This doesn't happen in Zen editor, which, once clicked, it successfully clones the source string, marks as ✅ and moves to the next string.

**Comment by julen** [comment]
Hey @rffontenelle what's the environment you are in (browser / OS)? FWIW I cannot reproduce this myself neither in hosted Weblate nor in my local dev server.

**Comment by rffontenelle** [comment]
Firefox 77.0 in Arch Linux 64-bit

I don't know how, but I've solved it somehow, after some local testing that involved downgrading, add-on disabling, cleaning browsing data, private browsing.

Closing since it doesn't happen anymore. Thanks for the attention and sorry for the noise.
