### ISSUE TITLE
Translators can not save - button is disabled

### ISSUE THREAD

**Issue by PawelSpoon** [WeblateOrg/weblate#3988]
**Describe the bug**
Users marked as translators only can modify the string but not push save button, as button is disabled.

**To Reproduce**
Project is set to protected, review is enabled
Login in as user having translator rights

1. Go to component
2. Click on translate
3. Try to translate an string (even non approved)
4. See error - button is disabled

**Expected behavior**
It should be possible to save

**Screenshots**

**Server configuration and status**
Weblate 3.11.3

![image](https://user-images.githubusercontent.com/11692361/83731407-c3251700-a64a-11ea-8d8c-a58120bac526.png)

Please paste the output of `list_versions` and `check --deploy` commands over
here. Depending on installation these can be executed in different way, please
consult https://docs.weblate.org/en/latest/admin/management.html for more
details.

On pip installed Weblate:

```
weblate list_versions
weblate check --deploy
```

On Git checkout:

```
./manage.py list_versions
./manage.py check --deploy
```

Using docker-compose:

```
docker-compose exec weblate weblate list_versions
docker-compose exec --user weblate weblate weblate check --deploy
```

**Additional context**

**Comment by nijel** [comment]
The button tooltip should give you indication why it's disabled...

**Comment by PawelSpoon** [comment]
yes it did: user has to rights to .. or was it privileges ?
the user was marked as translator, the project as protected.
i can not add screenshots now as the whole thing is connected with ldap and i need a second user :)
will do that tomorrow

**Comment by nijel** [comment]
There can be several reasons for that, but all of them should be visible on the page. The tooltip might not be accurate in some cases, I've just improved that.

**Comment by PawelSpoon** [comment]
![image](https://user-images.githubusercontent.com/11692361/83850785-b7e8ee80-a711-11ea-880a-cd1b8de58d9c.png)

it is actually possible to enable the button when adding also rights on template, not only translate

**Comment by nijel** [comment]
That's expected when editing the template language...

**Comment by comradekingu** [comment]
@PawelSpoon If you are just trying to edit the source language and it isn't allowed, updating to a newer version of Weblate will have that field grayed out.

**Comment by PawelSpoon** [comment]
We thought that template checkbox is about pot files.


but we are running mono lingual gettext.

there the source is english po file and thus was confusing that we need to enable that for our devs.

however we can close it

**Comment by PawelSpoon** [comment]
seems in that mode pit files are only used when adding a new translation / language

**Comment by comradekingu** [comment]
@PawelSpoon What are you using Weblate for? :)

**Comment by PawelSpoon** [comment]
for what its meant for: translating software. translation with approval, using msgid's

**Comment by comradekingu** [comment]
@PawelSpoon I meant what project. Was thinking I could help translate.
