### ISSUE TITLE
Cannot detect encoding for given string

### ISSUE THREAD

**Issue by Capspam** [WeblateOrg/weblate#3993]
**Describe the bug**
I am trying to create a component with a iOS project. But I got an error in **Create Component** section in **Monolingual base language file**. 

**To Reproduce**
1. Go to Create Component
2. Add repo url with git
3. Add **Resources/en.lproj/InfoPlist.strings** in Monolingual base language file.
4. Try to save and see the error : _Could not parse translation base file: Cannot detect encoding for given string._

**Expected behavior**
It should create the component

**Screenshots**
<img width="1089" alt="Screenshot 2020-06-04 at 8 28 51 PM" src="https://user-images.githubusercontent.com/66252730/83773459-2aba8100-a6a2-11ea-8aee-f69acdefe76b.png">

**Comment by nijel** [comment]
Try choosing "iOS strings (UTF-8)" as file format instead.

**Comment by DRSchlaubi** [comment]
I have the same problem when using Java Properties UTF-8

The file on GitHub is definitively using UTF-8
