### ISSUE TITLE
Single entry dropdown for tools in language view

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4004]
In language view, there is a dropdown that only has one entry.

![bilde](https://user-images.githubusercontent.com/13802408/84091655-9a9f7300-a9e4-11ea-8b9d-ee2f8a11dddb.png)

Could it be made into a button instead?

Edit: It could be argued it is inconsistent with menu entries available elsewhere.
That point would be made better if position was always the same.

https://hosted.weblate.org/dictionaries/freeplane/ has a "Share" item, and that for example is not available.

**Comment by nijel** [comment]
The long-term plan is to make more features available at the language level, so flattening the menu is not an option. Even right now if you have proper permissions, there are options to delete and edit the language in this menu.
