### ISSUE TITLE
The Celery tasks queue is too long, either the worker is not running or is too slow

### ISSUE THREAD

**Issue by hon97tan** [WeblateOrg/weblate#4005]
Hi All,

I recently setup the automatic translation add-on in the Weblate and I have encounter the an performance issue as following, please advice how to configure the Celery to support this.

weblate.E009 | The Celery tasks queue is too long, either the worker is not running or is too slow.

P/s: I'm using docker compose deployment.

-Tan

**Comment by nijel** [comment]
You can check status of the Celery queues at /manage/performance/ page.

**Comment by hon97tan** [comment]
The status: The Celery tasks queue is too long, either the worker is not running or is too slow. 

It did not provide detail on which celery tasks cause the issue.

**Comment by nijel** [comment]
On the bottom of the page there is status of individual queues.

**Comment by hon97tan** [comment]
This is what I see, :(

![image](https://user-images.githubusercontent.com/13308896/84130603-10075400-aa76-11ea-853d-1d9360d5449d.png)

**Comment by nijel** [comment]
If you don't see stats for individual queues under this, then you should start with upgrading ;-).

**Comment by hon97tan** [comment]
I'm using 3.11 at the moment and which version I need to upgrade ?

**Comment by nijel** [comment]
I think the queue stats were introduced in 4.0. It also drastically improves performance of translation memory, so that can make difference in the processing speed as well.

**Comment by hon97tan** [comment]
Thanks for the information. 

=============================
$ docker exec weblate-docker_weblate_1 weblate celery_queues
System check identified some issues:

INFOS:
?: (weblate.I031) New Weblate version is available, please upgrade to 4.0.4.
        HINT: https://docs.weblate.org/en/weblate-3.11.2/admin/upgrade.html
backup: 0
celery: 0
memory: 0
notify: 0
search: 0
translate: 25682

==================

At the moment, I have 25682 queue in the celery and I will kill the background automation translation process for now and disable the add-on until upgrade to 4.0.

The command should be:
docker exec weblate-docker_weblate_1 weblate cleanup_celery

or 

docker exec weblate-docker_weblate_1 celery purge -f

Please advice and many thanks for your feedback.

**Comment by nijel** [comment]
The first one does something different, the second one will need an app to work, adding `-A weblate.utils` should do it, but I've not tested that.

**Comment by nijel** [comment]
Also it might also help just to restart the container. The Whoosh based translation memory was sometimes stuck and restarting did help.

**Comment by hon97tan** [comment]
Thanks for the information.
