### ISSUE TITLE
The language code is too long, please check the filemask

### ISSUE THREAD

**Issue by kissu** [WeblateOrg/weblate#4014]
Hi ! :wave: 
Basically, I do import some JSONs from a git repo.
The path is usually `initial-locales/web` but can be `initial-locales/mobile` too.
Following that kind of pattern `initial-locales/${platform}`.

And inside of that directory, I'm using some computed JSON that can look from `en.json` to `en-cool-nested-locale.json` to `en_GB-more-specific-locale.json`.

But when I do import it, it throws me the following error
![image](https://user-images.githubusercontent.com/5133074/84357643-5075e780-abc6-11ea-89ec-d50c0721c5c3.png)

#### Stuff I tried
- I kinda imported it with the following settings:
  - filemask: `initial-locales/web/*.json`
  - language filter: `^[^.json]+$`
  - Monolingual base language file: empty
  - **result**: I do only get the basic JSONs like `fr.json` and `en.json` (not the longer hyphenated ones).
- Even tho I tried to create a new locale in the Weblate administration back-office:
  - language code: `en-cool-nested-locale`
  - language name: `en-cool-nested-locale`
- I've tried with the following filemask: `[A-Za-z-_]*.json$` but it wasn't working neither...
- It's not working with a manual `.zip` import neither (same error of language code being too long).

#### My setup
Oh and I'm using Weblate `4.0.4` on a self-hosted Docker. Not sure if it may help anyhow.
The `docker-compose` is basic with nothing fancy, basic credentials and a port.

I've looked into the docs/GH issues but did not find any clue on how to either make my regex work or how to bypass that threshold. :crying_cat_face:

**Comment by nijel** [comment]
There is currently hardcoded limit of 20 characters on the language name here.
