### ISSUE TITLE
Removing a translation doesn't update the Weblate bot Pull Requests

### ISSUE THREAD

**Issue by aparcar** [WeblateOrg/weblate#4016]
**Describe the bug**
Somebody added a new translation (language) resulting in a pull request with more than 90.000 lines of PO files. We removed the language afterwards and it disappeared from the Weblate language/translation overview, however the Weblate bot still opens a pull request including all lines. 

**To Reproduce**
see above

**Expected behavior**
Once removing the translation the PR should be upated and removed languages should be removed as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/16000931/84365506-9075a400-ab9f-11ea-9c53-502dcf9f52f8.png)

**Server configuration and status**
hosted Weblate

**Additional context**
The pull request is [here](https://github.com/openwrt/luci/pull/4156)

**Comment by nijel** [comment]
I think you've removed it only on one component, but thanks to "Language consistency" addon it was added to all components. I'm not sure if you really want to have this addon installed on this big project.

**Comment by aparcar** [comment]
I disabled the Addon. Looks like I have to remove the two languages for each component individually. There is however a overview for the specific language, it would be great to have a "remove" button there as well, removing it from **all** components at once.

https://hosted.weblate.org/languages/cadstar/openwrt/

![image](https://user-images.githubusercontent.com/16000931/84439453-ef551080-abd3-11ea-95ea-1e10a773ffd9.png)

**Comment by nijel** [comment]
There is currently no interface for this. You can script this using API though, see https://docs.weblate.org/en/latest/api.html#delete--api-translations-(string-project)-(string-component)-(string-language)-
