### ISSUE TITLE
Strings are skipped on saving

### ISSUE THREAD

**Issue by Mingun** [WeblateOrg/weblate#4019]
**Describe the bug**
If filter set in translation editor and string after saving no longer satisfies the filter condition, after clicking “Save” button next string skipped.

**To Reproduce**
1. Choose any project on https://hosted.weblate.org with >= 3 untranslated strings.
2. Select in filter “Untranslated strings”. Strings counter for example show 1/3.
3. Translate string and click “Save” button. After translation string no longer satisfies the filter “Untranslated strings”, so total counter of untranslated string decreased by one.
4. Editor loads third initially untranslated string, not second! Second string was skipped. Strings counter now shows 2/2.

**Expected behavior**
String should not be skipped, even after previous string no longer satisfies the filter condition.

That is, if the previous string has ceased to satisfy the filter, the total number of string matching the filter decreases by one, and then the offset to the current string should not increase by one. Now it is increasing in any case.

**Additional context**
As mentioned in footer, hosted.weblate.org works on Weblate 4.1-dev.

**Comment by nijel** [comment]
The list is supposed to be cached, probably something got broken due to recent search changes.
