### ISSUE TITLE
Comments on source strings are not shown in translations

### ISSUE THREAD

**Issue by Mingun** [WeblateOrg/weblate#4020]
**Describe the bug**
Filter `has:comment` in translation not select strings with comments on source strings. Previously it worked as expected.

**To Reproduce**
For example, [here](https://hosted.weblate.org/translate/andors-trail/game-content/ru/?q=has:comment) shows only one comment. But in fact there [five more comments](https://hosted.weblate.org/translate/andors-trail/game-content/en/?q=has:comment) to source strings.

It is useful for translators to see these comments, because they directly relate to translation: in particular, in the above example, clarifying questions are asked, the answers to which are useful for all translations, and not just for translation into Russian.

**Expected behavior**
Filter `has:comment` should shown all comments. Or, at least, one more filter is needed to show all translation strings with comments on the source strings.

**Additional context**
As mentioned in footer, hosted.weblate.org works on Weblate 4.1-dev.

**Comment by nijel** [comment]
The pretty much same applies to other source string metadata (for example `has:screenshot`). It definitely makes sense to make these work on translations as well.
