### ISSUE TITLE
Consecutive duplicated words is triggered when translating repetitions

### ISSUE THREAD

**Issue by Mingun** [WeblateOrg/weblate#4023]
**Describe the bug**
The “Consecutive duplicated words” check is triggered even if the repeat is a translation of repeated words in the source string. This is false positive and I expect not triggered check in that case.

**To Reproduce**
1. Go to https://hosted.weblate.org/translate/andors-trail/game-content/ru/?checksum=e794e9c184b2be2f

**Expected behavior**
No warning.

I think it should also count the number of repetitions in the source string and trigger warning only if the number of repetitions in the translation is different. For example:
```po
# :Source string:     two word groups with two and three repetitions
# :Translated string: two word groups with two and three repetitions
# :Result:            no warning
msgid "HAH HAH! HEH HEH HEH!"
msgstr "ХАХ ХАХ! ХЕ ХЕ ХЕ!"

# :Source string:     two word groups with two and three repetitions
# :Translated string: two word groups with two and two (less than source) repetitions
# :Result:            warning
msgid "HAH HAH! HEH HEH HEH!"
msgstr "ХАХ ХАХ! ХЕ ХЕ!"

# :Source string:     two word groups with two and three repetitions
# :Translated string: two word groups with three (more than source) and two repetitions
# :Result:            warning
msgid "HAH HAH! HEH HEH HEH!"
msgstr "ХАХ ХАХ ХАХ! ХЕ ХЕ ХЕ!"

# :Source string:     two word groups with two and three repetitions
# :Translated string: one (less than source) word group with two repetitions
# :Result:            warning
msgid "HAH HAH! HEH HEH HEH!"
msgstr "ХАХ ХАХ!"

# :Source string:     two word groups with two and three repetitions
# :Translated string: three (more than source) word groups with two, 
#                     three and two repetitions
# :Result:            warning
msgid "HAH HAH! HEH HEH HEH!"
msgstr "ХАХ ХАХ! ХЕ ХЕ ХЕ! ХИ ХИ!"
```

**Additional context**
As mentioned in footer, hosted.weblate.org works on Weblate 4.1-dev.

**Comment by 55abhilash** [comment]
I am doing changes for this. Please assign.

**Comment by 55abhilash** [comment]
@Mingun I think your suggestion will apply to only cases when there is a one to one mapping of the words in the string. There might be cases when a word is repeated in English twice, but it is translated to just one word in some language.
I suggest following solution:
If there is a repeated word in original string, never throw the duplicate check warning.
If there is no repeated word in original string, but there are repeated words in translated string, throw the warning.

**Comment by Mingun** [comment]
Yeah, your suggestion looks reasonable.

**Comment by nijel** [comment]
@55abhilash Any progress on this? Do you need help?
