### ISSUE TITLE
Javascript localization library

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#4024]
**Is your feature request related to a problem? Please describe.**
Sometimes it would be useful to translate static HTML content. Typical use case could be our static error page.

**Describe the solution you'd like**

* Javascript library to load the translations and inject them into the page
  * The initial implementation can only support strings manually marked in the HTML for translation
  * Might be based on Django gettext library later to support usage from the javascript
* Strings export addon for Weblate to push localized strings to JSON
  * Should be served externally to make it available when Hosted Weblate is down

**Describe alternatives you've considered**
Right now, the error page is not localized, what is not nice and people tend to complain about that.

**Additional context**
https://github.com/WeblateOrg/hosted/issues/35

**Comment by nijel** [comment]
Played a bit with this, the basic text extraction and replacement could be:

```
document.querySelectorAll('*').forEach(function(node) {
    if (node.children.length === 0 && node.textContent) {
        console.log(node.textContent); 
        node.textContent='x';
    }
});
```

**Comment by julen** [comment]
Why not generate language-specific HTML files and serve them by default based on `Accept-Language` headers? Seems like a simpler solution to me.

**Comment by nijel** [comment]
It would work in this use case, but the intention is to support localization of static pages in general. GitHub pages might be another example of things which could be localized by it.

**Comment by julen** [comment]
If it's for static pages I honestly think HTML is the way to go — I might miss some context, but in principle there's no strong technical reason to err on using JS there. JS localization should be left for SPAs and interactive components.

**Comment by nijel** [comment]
I'm not expert in that, but we got several questions on that topic. AFAIK GitHub doesn't support serving localized page depending on `Accept-Language` and generally localization of static or statically generated pages seem tricky for many users, while including JavaScript which does that seems easy.

**Comment by nijel** [comment]
Friend just pointed me to https://weglot.com/ which is basically built around this idea with some additional features (plugins for various CMS, server side proxying, ...).
