### ISSUE TITLE
Wrong offset in new search leads to prematurely search terminate

### ISSUE THREAD

**Issue by Mingun** [WeblateOrg/weblate#4027]
**Describe the bug**
After fixing issue #4019 search behavior was broken. It remember string offset withing previous search and applied it to new search. In result, if total search results less than that offset, search terminates prematurely with message “The translation has come to an end.”

**To Reproduce**
1. Go to https://hosted.weblate.org/translate/andors-trail/game-content/ru/?offset=2
2. Then trying to find an unique term, that should return only one string. For example, [search “Ring of venom”](https://hosted.weblate.org/translate/andors-trail/game-content/ru/?offset=2&q=Ring+of+venom&sort_by=-priority%2Cposition&checksum=).
3. It should return [one result](https://hosted.weblate.org/translate/andors-trail/game-content/ru/?q=Ring+of+venom). But instead search jumps to page to dashboard with message “The translation has come to an end.”

**Expected behavior**
Every new search should reset offset value.

**Additional context**
As mentioned in footer, hosted.weblate.org works on Weblate 4.1-dev.

**Comment by nijel** [comment]
That's unrelated to #4019, but caused by other changes
