### ISSUE TITLE
Can Not Merge/Rebase

### ISSUE THREAD

**Issue by buck-E** [WeblateOrg/weblate#4030]
**Describe the bug**

Under the `/#repository` page, I see the error:

The remote repository needs to be merged!
There are some new commits in the local repository.

But when I Rebase with the button on the right, I see "Could not rebase local branch onto remote branch" with no other information.

**Expected behavior**
I expect the rebase to fix the problem, or to be given details about why it is not working.  Specifically, what is the correct way to do this:

```
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>
```

If I used the command line, it's easy.  But using the weblate interface?

**Server configuration and status**
Please paste the output of `list_versions` and `check --deploy` commands over
here. Depending on installation these can be executed in different way, please
consult https://docs.weblate.org/en/latest/admin/management.html for more
details.

On pip installed Weblate:

```
$ weblate list_versions
 * Weblate: 4.0.4
 * Django: 3.0.5
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.0
 * lxml: 4.5.0
 * Pillow: 7.1.1
 * bleach: 3.1.4
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.9.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 44.0.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.3
 * celery: 4.4.2
 * kombu: 4.6.8
 * translation-finder: 2.0
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.36.0
 * diff-match-patch: 20181111
 * requests: 2.23.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.3
 * Cython: 0.29.16
 * misaka: 2.1.1
 * GitPython: 3.1.1
 * borgbackup: 1.1.11
 * Python: 3.8.3
 * Git: 2.26.2
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * aeidon: 1.7.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.9.0-8-amd64 (x86_64)

weblate check --deploy
$ weblate check --deploy
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.0.4/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.0.4/admin/backup.html


```

**Additional context**
```
Rebasing (1/4)
Rebasing (2/4)
Rebasing (3/4)
error: could not apply 3c997e3... Translated using Weblate (French)
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 3c997e3... Translated using Weblate (French)
Auto-merging locale/fr/LC_MESSAGES/messages.po
CONFLICT (content): Merge conflict in locale/fr/LC_MESSAGES/messages.po
 (1)
```

I do not know how to start troubleshooting.  Is there a way to `git stash`?

**Comment by nijel** [comment]
In case there is a merge conflict, you need to resolve it outside Weblate, see https://docs.weblate.org/en/latest/faq.html#how-to-fix-merge-conflicts-in-translations

**Comment by buck-E** [comment]
Thank you.  What user should I run those commands as?  The weblate user that runs pip?

**Comment by buck-E** [comment]
And what is `wlc commit`?  This is not in the weblate path.

**Comment by nijel** [comment]
You can run these on your system. The wlc steps are optional and can be done in the Weblate UI as well, see docs.weblate.org/en/latest/wlc.html for more info on wlc.

**Comment by buck-E** [comment]
I installed wlc with pip3 and `wlc ls` gives lots of errors:

```
wlc ls
Traceback (most recent call last):
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/wlc/main.py", line 454, in run
    obj = self.get_object()
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/wlc/main.py", line 272, in get_object
    raise CommandError("No object passed on command line!")
wlc.main.CommandError: No object passed on command line!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
.
.
.
```

I am still confused how the instructions (https://docs.weblate.org/en/latest/faq.html#how-to-fix-merge-conflicts-in-translations) help with this, or where to run them.  Are the docs saying I should take a fresh localhost, create a new directory for the code, run `git remote add weblate https://hosted.weblate.org/git/project/component/` etc. and then manually fix them?  I can do this if that is what you are saying.  But it's not clear.

**Comment by buck-E** [comment]
Running `git remote add weblate https://hosted.weblate.org/git/project/component/` (with the correct info in the URL) produces:

```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

This is what I would expect.  So I do not understand what the docs are saying.

**Comment by buck-E** [comment]
Oh I am starting to see this.  It is extremely complicated for fixing a git problem.  But I see it now.  Wow, okay.  Nothing quicker than all of this export, API key stuff?

**Comment by buck-E** [comment]
In the account where I install weblate with pip, I ran step 2 of this page: https://docs.weblate.org/en/latest/admin/optionals.html#git-exporter.  (`weblate.gitexport` was already in `INSTALLED_APPS` by default in `settings.py`.):

```
$ weblate migrate
Operations to perform:
  Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, fonts, gitexport, lang, memory, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
Running migrations:
  No migrations to apply.
```

Should I run `weblate migrate gitexport` instead?  Should the docs say that here: https://docs.weblate.org/en/latest/admin/optionals.html#git-exporter

**Comment by buck-E** [comment]
On https://docs.weblate.org/en/latest/wlc.html#getting-started:

Does this page imple that .config/weblate will be automatically generated with "pip3 install wlc"?  It is not.

Or should I manually create this file, and choose any API key of any format/length I wish?

**Comment by nijel** [comment]
You need to create configuration matching your server URL and API key, it can't be generated automatically. But as mentioned before, you don't have to use wlc, you can trigger the same operations from the web interface (or skip most of them if the project is not much alive).

**Comment by buck-E** [comment]
I don't know what you're saying.  I read the docs you pointed me to and asked the questions that it brings up.  At this time we just did a "skip" so I will close the issue but it should not be considered resolved as there is now no path to resolving this type of problem that is clear in the docs.
