### ISSUE TITLE
Evaluate usage of django-compressor

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#4034]
Back then it was clearly beneficial to introduce it as number of HTTP requests was real concern. Maybe it's not the case these days with HTTP/2.

Things to consider:

* Current setup does add overhead to each request (~25 redis requests to check freshness of the cache)
* Are multiple requests still concern with HTTP/2? Maybe it would be more beneficial to utilize per script caching and serve them individually

Possible outcomes:

* Current approach is good
* Reconfigure django-compressor to better fit our use case
* Drop django-compressor usage

**Comment by nijel** [comment]
Typical overhead caused by django-compressor, in total it accounts to 11ms: 

![image](https://user-images.githubusercontent.com/212189/84656064-60693080-af12-11ea-9cbe-d1bad608c763.png)

**Comment by julen** [comment]
[Is HTTP/2 even an option](https://caniuse.com/#search=http2) if Weblate is meant to work in [browsers supported by Bootstrap 3.4](https://getbootstrap.com/docs/3.4/getting-started/#support-browsers)? Refs. https://github.com/WeblateOrg/weblate/pull/3965#discussion_r432321138

**Comment by nijel** [comment]
The reality is that most of the users use browsers which do support it (on Hosted Weblate it is more than 99%), so I think it's okay to have slightly degraded performance for the rest. 

The browser support is something what has never been really evaluated and maybe it's time to change that :-).

**Comment by julen** [comment]
> The browser support is something what has never been really evaluated and maybe it's time to change that :-).

That'd be cool for some frontend code improvements! 👍

**Comment by nijel** [comment]
I'm really open to suggestions in that. I'm not really a frontend guy...

**Comment by nijel** [comment]
Anyway to give some starting point, I'd like to move to Bootstrap 4 at some point (see https://github.com/WeblateOrg/weblate/issues/2916), so we might target at [Bootstrap 4 browser requirements](https://getbootstrap.com/docs/4.1/getting-started/browsers-devices/).

**Comment by julen** [comment]
A common approach is to support latest 2 stable versions of browsers (e.g. [StackExchange does this](https://meta.stackexchange.com/a/71208)). Nonetheless, it'd be good (also for the web) to drop IE support as it's a browser stuck in the past. You should evaluate your userbase's browser usage data, though — it's your business after all.

**Comment by nijel** [comment]
It seems to be time to finally do that. Checking the stats, there seem to be only few users on that. Also, the current code is not really tested that it works in older browsers, so it's probably time to stop pretending we support them...

**Comment by julen** [comment]
Cool, can we then [start using](https://kangax.github.io/compat-table/es6/) arrow functions, restructuring assignment, classes, etc. without transpilation of any sorts?

**Comment by nijel** [comment]
Let's try it in small scope first and see if we will get some (negative) feedback on that. I can check Weblate instances we manage, but that's only a small fraction of what people run.

**Comment by nijel** [comment]
@julen Can you please prepare some small change introducing one of the features soon? I'd include it in the 4.1.1 release to gather feedback soon.

**Comment by julen** [comment]
You mean to rewrite some part using ES6+ features? If so I'd start with arrow functions — I can do that after #4035 has been merged.

**Comment by nijel** [comment]
Yes, starting with something tiny so that there is not much wasted effort in case we will have to revert that.

**Comment by julen** [comment]
> Anyway to give some starting point, I'd like to move to Bootstrap 4 at some point (see #2916), so we might target at [Bootstrap 4 browser requirements](https://getbootstrap.com/docs/4.1/getting-started/browsers-devices/).

Btw, I just came across Bootstrap 5 alpha, which on the JS side gets rid of jQuery and also updates its [set of supported browsers](https://v5.getbootstrap.com/docs/5.0/getting-started/browsers-devices/#supported-browsers).

**Comment by nijel** [comment]
Sounds great, they are even planning RTL support there, so I think this is the way to go once it is released, I've updated https://github.com/WeblateOrg/weblate/issues/2916#issuecomment-645205569 accordingly.

**Comment by nijel** [comment]
After some research I think keeping the compressor still brings some benefits, however it is better to operate it in the offline mode. This will be default for Docker images, for manual installs it will have to enabled as additional step is needed to compress the files on each deploy.
