### ISSUE TITLE
Weblate error starting 4.1

### ISSUE THREAD

**Issue by Badiboy** [WeblateOrg/weblate#4036]
**Describe the bug**
Error while starting weblate.
> ERRORS:
> trans.Change.glossary_term: (fields.E300) Field defines a relation with model 'glossary.Term', which is either not installed, or is abstract.
> trans.Change.glossary_term: (fields.E307) The field trans.Change.glossary_term was declared with a lazy reference to 'glossary.term', but app 'glossary' isn't installed.

**To Reproduce**
1. Upgrade according to manual
2. Run (weblate runserver)

**Additional context**
Ubuntu 18.04, Python 3.6

**Comment by nijel** [comment]
Please read https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-4-0-to-4-1 and adjust your settings accordingly.

**Comment by Badiboy** [comment]
I'm very sorry. I always checked upgrade notes... Except this time. 
Thank you once again.
