### ISSUE TITLE
Changing Port on pip install

### ISSUE THREAD

**Issue by buck-E** [WeblateOrg/weblate#4038]
**Is your feature request related to a problem? Please describe.**

Problem #1 is in the case of a port conflict between weblate's default port and another service on the server.  

Problem #2: Also to help troubleshooting.  At this time after upgrading to 4.1, nginx reverse proxy does not find weblate and I want to do testing to find out why.  

Question: what is the default weblate port for a pip install of version 4.1?

**Describe the solution you'd like**
In settings.py, it would be useful to have a setting to change the default weblate port

**Describe alternatives you've considered**

**Additional context**
Could not find existing method in docs.  Searching for "port" reveals docker, redis, etc. config options, not for web service of a pip install.

**Comment by nijel** [comment]
There is no port defined anywhere in Weblate, that's why you can't configure it. See https://docs.weblate.org/en/latest/admin/install.html#running-server

**Comment by buck-E** [comment]
I know.  That's why this is a request. :)  But we have a working setup and it is not some emergency.  Just a backlog feature request.

**Comment by nijel** [comment]
But there is nothing to configure in Weblate side, the actual setup depends on how you run the server and the port is configured at the server (nginx, Apache, or built in Django server).

**Comment by buck-E** [comment]
Oh crap you're right.  I'm sorry, I was thinking of another system I have on this server, not weblate.
