### ISSUE TITLE
Remove TM matches for MT

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#4041]
**Is your feature request related to a problem? Please describe.**
The machine translation UI currently contains translation memory matches as well. This is mostly a historical relict from times when there was no dedicated UI for translation memory.

**Describe the solution you'd like**
Remove translation memory matches from the machine translation tab. 

I'm not sure what is the best approach for third-party services which do provide translation memory. Especially in case they do provide translation memory, but fallback to machine translation such as MyMemory.

Additionally, there is "Weblate" service which behaves like translation memory, but scans existing translations only. Maybe it's time to remove it favoring translation memory.

**Describe alternatives you've considered**
Current setup works, but is confusing.

**Additional context**
See https://github.com/WeblateOrg/weblate/pull/4035#discussion_r440349261

**Comment by julen** [comment]
I believe MyMemory offers a way to tell if a result originates from MT via the `reference` field ([example](https://api.mymemory.translated.net/get?q=This%20was%20Machine%20Translated&langpair=en|eu)).

Nonetheless, another option is to keep everything under a single tab (like e.g. Pontoon does), and changing the label of the tab, which is misleading right now. Visually telling what comes from where, emphasizing important parts translators should immediately focus on, and maybe putting TM results over MT matches should help in that case, too.

**Comment by nijel** [comment]
Yes, MyMemory tells that (and I think Weblate includes that info). What I wanted to point out is that it sometimes can not be determined at service level.

Having one tab is option as well, the reason for separating it was that we don't want to allow free text entry for machine translation, but only for translation memory. But that can be probably addressed in single tab UI as well.

**Comment by julen** [comment]
I can have a look at integrating both in a single tab.

I also think the initial request for `MT_BACKENDS` can be skipped either by inlining the list in the DOM or by delegating this to the backend — the endpoint should already know which services are configured and hence what to query. I ignore what was the reason to keep services in separate endpoints — worry about latency perhaps?

**Comment by nijel** [comment]
We definitely want to query each service in a separate request as some might just take long, timeout, or fail.

**Comment by julen** [comment]
Understood. Please feel free to assign the ticket to me.

**Comment by julen** [comment]
@nijel do you have any suggestions on how to proceed with `machinery.view` and `memory.view` permissions? Should they still be kept separate?

**Comment by nijel** [comment]
I think it's okay to have just `machinery.view`. I don't think anybody uses that fine grained permissions anyway.
