### ISSUE TITLE
Free plan for open source project is impossible

### ISSUE THREAD

**Issue by Kwaskoff** [WeblateOrg/weblate#4042]
Hello everybody, we develop open source project and send request for free plane halve year ago!
If you know this request is just letter, no ticket system, no site system request like for profit plans.
It need to be changed! 

Great thx!!

**Comment by nijel** [comment]
There is a ticket system behind the requests. We just have huge backlog in processing these...

**Comment by orangesunny** [comment]
Hi @Kwaskoff, thanks for the head’s up! The mistake was mine.

You are right, the waiting is long. We are working on two things to change that:
1. New support/customer care system. Soon.
2. Letting libre project maintainers set up the project by themselves. That is a long term plan.

Thank you for your support. I wish you a happy libre translating. And let us know via e-mail in case of any questions. We are getting faster there :)
