### ISSUE TITLE
Cannot import all translations with dashes and underscores

### ISSUE THREAD

**Issue by kissu** [WeblateOrg/weblate#4043]
Hi ! :wave: 
First off, I'm not sure if it's done on purpose but the link to `translation-finder issue tracker` is actually broken on the main repo. :information_source: 
![image](https://user-images.githubusercontent.com/5133074/84765789-06c73b80-afd0-11ea-9430-fbaa581df3b9.png)

Now, my issue.
I really cannot find a way to import all my `.json` properly.
The auto-detect sees them but nothing more.
I've tried all the possible `filemask` I've thought about. The filemask is not really working like a regex so I'm kinda lost of what it should look like here.
![image](https://user-images.githubusercontent.com/5133074/84766188-aedd0480-afd0-11ea-9fd8-dcffad99d690.png)

For some reason, my translations are skipped when I do choose the middle option (`initial-locales/web/*.json`). :confused:
![image](https://user-images.githubusercontent.com/5133074/84766714-94eff180-afd1-11ea-90b4-16d379660e95.png)

I do need, `initial-locales/web/en.json` as my `Monolingual base language file`.
And I do have a lot of JSONs in `initial-locales/web` that do include that kind of format:
- `fr`
- `fr-politique-larem`
- `en_GB`
- `en_GB-ong-vert`

**Comment by nijel** [comment]
What is youir setting for [Language filter](https://docs.weblate.org/en/latest/admin/projects.html#language-filter)? That is most likely cause of skipping those.

**Comment by kissu** [comment]
I've tried several on Rubular but `^[A-Za-z_-]*$` is not catching them all.
https://rubular.com/r/9DOq7xmHoMwKZg

![image](https://user-images.githubusercontent.com/5133074/84774650-6af0fc00-afde-11ea-8082-c86e0f570eac.png)

**Comment by nijel** [comment]
I don't see why the default one should not work, it just excludes dot from the match and the language codes you use doesn't seem to contain it. The log seems okay now, it's processing the files...

**Comment by kissu** [comment]
Ok, the configuration was great, it was an issue on my part: my backend dev did not do the migration of the database after bumping to 4.1 (so it kept the limit of `20` chars for a json name).

Sorry for the bother !
