### ISSUE TITLE
Button in Repo Maintanence for git reset --hard origin/master

### ISSUE THREAD

**Issue by SethiPandi** [WeblateOrg/weblate#4050]
**Is your feature request related to a problem? Please describe.**
There are times when one will want to do the equivalent of `git reset --hard origin/master`.
In my case, I had accidentally committed sensitive information into a repository and didn't discover this until after it was already pushed remotely. As a result I had to use `git filter-repo` to alter the history and do a `git push --force` to overwrite the history of the repository to exclude this.

However, in doing, so I found no way in the Weblate UI force a reset, the reset button didn't appear to do the job and most other commands caused errors such as unable to rebase.

After such a scenario it's necessary to rebase or reset to the origin's repository.

**Describe the solution you'd like**
Could a button be provided in the UI that simulates `git reset --hard origin/master` to forcefully replace the entire repository and history with the origin repository?

**Comment by nijel** [comment]
This is exactly what reset button is supposed to do, what failed on that?

**Comment by SethiPandi** [comment]
Interesting, I didn't realize. :thinking: 
It didn't "fail" (as in error message), it was "successful" but did visibly nothing. Other commands still didn't work (ie error regarding rebase) and I'd still get error emails from Weblate when committing to the repository.

Unfortunately I ended up removing the project and components and recreated them from scratch, to address my issue and get things working again quickly; so I may have jeopardized my ability to provide more information.

I've been trying to dig through the logs to find anything useful:
I believe this portion covers where I attempted to rebase, which failed, then tried to reset, which visibly succeeded.

However, later when I perform a commit, it's still unable to merge them.  

https://gist.github.com/SethiPandi/b7309c6e16164fd892f7800b3e824d94

Please let me know if this isn't helpful.

**Comment by nijel** [comment]
> Killed
>
> git encountered an error while preparing the patches to replay

That seems like the git process was killed during merging. Maybe you're hitting memory limits and it was killed by OOM?

**Comment by SethiPandi** [comment]
Ahh, I see. Yeah, that's quite likely.
I'm deployed on a budget GCP Compute Engine instance via [docker-compose](https://github.com/WeblateOrg/docker-compose). 

```
MiB Mem :   1996.6 total,    121.7 free,   1572.8 used,    302.1 buff/cache
``` 

Sorry about that, this is probably a fault on my end in that case.

**Comment by nijel** [comment]
2GB should be enough, can you check what is consuming most of the memory?

**Comment by SethiPandi** [comment]
I restarted the server and waited a few minutes, then performed `top -o %MEM`.

https://gist.github.com/SethiPandi/0ed70cd735cafd3c37d23229c475498e

Unfortunately I just learned GCP by default doesn't store metrics on memory for some reason, so I don't have historic data of my memory usage, but I hope this helps.

**Comment by nijel** [comment]
The number of processes seems too big for the 2G system. The problem is that it currently cannot be configured in the docker container, see https://github.com/WeblateOrg/docker/issues/683 . That would probably address your problem.
