### ISSUE TITLE
Translation repository stuck on "There are some new commits in the local repository" state

### ISSUE THREAD

**Issue by jtiai** [WeblateOrg/weblate#4051]
**Describe the bug**
After pulling, merging and pushing Weblate reports "There are some new commits in the local repository" even there are none.

I did checked actual local repositories and they're up-to date and there are no outstanding commits  nor unpushed changeset in local repository.

Repository backend is mercurial.

**To Reproduce**
Unfortunately I don't know how to reproduce the error.

**Expected behavior**
After described procedure I expected repository state to be clean

**Server configuration and status**

 * Weblate: 4.1
 * Django: 3.0.7
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0
 * lxml: 4.5.1
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.4.0
 * django-crispy-forms: 1.9.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.1
 * celery: 4.4.5
 * kombu: 4.6.10
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.23.0
 * django-redis: 4.12.1
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.4
 * Cython: 0.29.20
 * misaka: 2.1.1
 * GitPython: 3.1.3
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.14.3
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * Mercurial: 5.4.1
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * Redis server: 4.0.14
 * PostgreSQL server: 11.8
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.keypro.fi
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 3.10.0-1062.12.1.el7.x86_64 (x86_64)

System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.1/admin/backup.html

**Additional context**

Regarding to system check I'm fully aware what they do mean.

**Comment by nijel** [comment]
Weblate does `hg outgoing()` on the repo to detect this. I have no clue why it might be reporting something in your case.

**Comment by jtiai** [comment]
If I only knew where to start debugging I could do that.

**Comment by nijel** [comment]
Check system available memory (`free`), kernel logs (`dmesg`) will show whether OOM killer was invoked.

**Comment by nijel** [comment]
Go to the Weblate repo (DATADIR/vcs/project/component) and execute `hg outgoing()` and check how it matches your expectation.

**Comment by jtiai** [comment]
Progress when I enabled our sentry to track exceptions:

Because weblate docker container uses C-locale (which doesn't work well with Rhodecode) It thinks remote warnings as an errors.

```
RepositoryException: remote: bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
remote: /bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
remote: /opt/rhodecode/store/arwnrdxkhff4hzkpygd58shxy15zgm7j-bash-4.4-p12/bin/bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
remote: sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
remote: /bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
remote: _findLib_gcc: warning: setlocale: LC_ALL: cannot change local...
  File "weblate/trans/models/component.py", line 1260, in do_reset
    self.repository.reset()
  File "weblate/vcs/mercurial.py", line 113, in reset
    self.execute(["strip", "roots(outgoing())"])
  File "weblate/vcs/base.py", line 190, in execute
    args, self.path, fullcmd=fullcmd, local=self.local, merge_err=merge_err
  File "weblate/vcs/base.py", line 177, in _popen
    raise RepositoryException(retcode, output)
```

**Comment by nijel** [comment]
Hmm, it should not set locale on the remote connection. We're trying to disable that, but that doesn't seem to work, see https://superuser.com/q/485569
