### ISSUE TITLE
Project alert for "Broken project website URL" does not go away (and has no apparent way to ignore it)

### ISSUE THREAD

**Issue by BhaaLseN** [WeblateOrg/weblate#4055]
Not sure if this is an actual bug or anything; so I'm filing this as a question for now.

We use exlusively URLs on internal servers which are running HTTPS with domain-signed certificates (from our active directory certificate authority, ADCA), and at least for the "Project website URL" we now have "Broken project website URL" alerts, one for every project.

This makes working with the overviews a bit difficult since we cannot tell if one of them has _actual_ issues or whether it is just the URL.

The detailed message is 
```
This project is set up incorrectly.

The project website URL points to a non-existing location:
* http://company.domain.tld/browse/PRJ (HTTPSConnectionPool(host='company.domain.tld', port=443): Max retries exceeded with url: /browse/PRJ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)'))))
-------
a month ago
```
(and yes, it was generated a month ago; and doesn't appear to update even if I change the URL. The alert message _does_ change if I change the URL though.)

We _know_ that we're using self signed certificates there, and we also made sure to make this certificate trusted on the machine (which is Debian 10 "buster") using `update-ca-certificates` (after moving our domain root certificate into `/usr/local/share/ca-certificates/domain-root.crt`). Local testing with `curl` shows that this works correctly.

On to the actual questions:
1. Why does the project website URL trigger this alert, despite being correctly (at least as far as I can tell?)
In case this is indeed a configuration issue (because Python doesn't use the system certificate store): How can I fix that?
2. Why is the project website URL the only one to trigger this alert? The repository URL as well as the repository browser URL are using HTTPS as well (using a similarly self-signed certificate).
3. Is there any way to disable/ignore certain alerts globally (using `settings.py`)?

In case it matters: This is still on Weblate 4.0.1; but according to the release notes I don't see anything that would affect this on 4.1.1

**Comment by nijel** [comment]
The difference probably comes in way firing those requests - the web URL is checked by requests (most likely installed by pip), while the repository URLs are handled by git (installed on system, thus using system certificates). You can tell requests to use system certs by environment, see https://stackoverflow.com/a/42982144/225718 (note you will have to do set this for both wsgi and celery).

**Comment by nijel** [comment]
Actually, it might be good enough to add following to `settings.py` (not tested):

```python
import os
os.environ["REQUESTS_CA_BUNDLE"] = "/etc/ssl/certs/ca-certificates.crt"
```

**Comment by BhaaLseN** [comment]
This appears to be working, thanks a lot!

Do you want to leave this open, as reminder to add it as documentation/add some built-in variables/something else?
