### ISSUE TITLE
Component status from API

### ISSUE THREAD

**Issue by iniel** [WeblateOrg/weblate#4063]
Hi.

I am trying to create component with translations and upload file with rest api .

So I use
"POST /api/projects/(string:project)/components/" to create a component
"POST /api/components/(string:project)/(string:component)/translations/" to create new translation in the component
"POST /api/translations/(string:project)/(string:component)/(string:language)/file/" to upload file with keys

But I couldn't call this in sequence, because when the first response has received the process of creating a component is still in progress. So I need to check the status of this process with api, but there is no such information in there.

I am not sure which one of endpoints should return this information, but it would be great to be able to get this from api somehow.

**Comment by nijel** [comment]
The background project creation was recently introduced and it's not yet covered by the API.
