### ISSUE TITLE
Is it necessary to disable translation propagation feature for project or whole site?

### ISSUE THREAD

**Issue by zslucky** [WeblateOrg/weblate#4065]
**Is your feature request related to a problem? Please describe.**
Yes, translation propagation give me some unexpected changes.

**Describe the solution you'd like**
Maybe we can provide a setting for project or whole site to disable this feature?

**Describe alternatives you've considered**
Now I need to disable this feature component-by-component. There are so many components for me now, and I don't know when user will add new component in the future, it's hard to make changes in real-time.

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/config.html#default-translation-propagation

**Comment by zslucky** [comment]
@nijel Thank you so much, but I'm not sure how to set this value in dcoker container... `docker-compose.override.yml` looks like doesn't suport `Boolean` value, how to add it?

**Comment by nijel** [comment]
You can always add custom configuration file, see https://docs.weblate.org/en/latest/admin/install/docker.html#custom-configuration-files

I've exposed this particular setting to environment in f254c3bf1049690cb1512eaffcbe664fa93066c8 for upcoming 4.1.1 release.

**Comment by zslucky** [comment]
@nijel good job 👍
