### ISSUE TITLE
ParseException  found 'é' 

### ISSUE THREAD

**Issue by solymi** [WeblateOrg/weblate#4066]
We got this error after update from 4.0.4 to 4.1

Request Method: | POST
-- | --
http://weblate.prod.exc.hu/translate/282-2020/specifcation-names/hr/?q=has%3Acheck&offset=1
3.0.7
ParseException
Expected end of text, found 'é'  (at char 6), (line:1, col:7)
/usr/local/lib/python3.7/dist-packages/pyparsing.py in parseImpl, line 3814
/usr/bin/uwsgi-core
3.7.3
['/usr/local/lib/python3.7/dist-packages/git/ext/gitdb',  '/',  '/usr/local/lib/python3.7/dist-packages/',  '.',  '',  '/usr/lib/python37.zip',  '/usr/lib/python3.7',  '/usr/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/dist-packages',  '/app/data/python',  '/usr/lib/python3/dist-packages',  '/usr/local/lib/python3.7/dist-packages/gitdb/ext/smmap']

**Additional context**
**EXAMPLE PO FILE**
#: specification_template_translation:7
msgid "Akkumulátor töltő"
msgstr "Puunjač za baterije"
#: specification_template_translation:24
msgid "Hálókártya"
msgstr "Mrežna kartica"
#: specification_template_translation:31
msgid "Egér"
msgstr "Miš"
#: specification_template_translation:33
msgid "Billentyűzet"
msgstr "Tipkovnica"
#: specification_template_translation:43
msgid "Rendszerhűtő"
msgstr "Hladnjak"
#: specification_template_translation:44
msgid "Memóriamodul"
msgstr "Memorijski modul"
#: specification_template_translation:45
msgid "Tápegység"
msgstr "Napajanje"

**Comment by nijel** [comment]
The parser is invoked on type flags in the PO file, can you please look for the lines starting with `#,` there and post them here?

**Comment by nijel** [comment]
Any reason for using flags non-conforming with Gettext? Still Weblate should not crash on that...
