### ISSUE TITLE
Make some alerts dismissible

### ISSUE THREAD

**Issue by sthomae01** [WeblateOrg/weblate#4067]
**Describe the bug**
We are using Weblate with Kubernetes with a proxy for the ssl encryption. Since we updated to the new Weblate version 4.1 we have the error on every project that the project URL is not right because it can not be found, although it is correct. Of course this is not important for weblate to work but it still would be nice not having this error.

**To Reproduce**
1. Go to 'Projects/Browse All Projects'
2. Click on 'Fix this component to clear its alerts'
3. See error

**Expected behavior**
The error should not be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/66111968/85027922-c2c46a00-b17a-11ea-8994-240bf6ce51be.png)

**Server configuration and status**
list_versions:
 * Weblate: 4.1 
 * Django: 3.0.7
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0     
 * lxml: 4.5.1
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1       
 * social-auth-core: 3.3.3      
 * social-auth-app-django: 3.4.0
 * django-crispy-forms: 1.9.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.1
 * celery: 4.4.5
 * kombu: 4.6.10
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.23.0
 * django-redis: 4.12.1
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.4
 * Cython: 0.29.20
 * misaka: 2.1.1
 * GitPython: 3.1.3
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.14.3
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * Mercurial: 5.4.1
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * Redis server: 5.0.4
 * PostgreSQL server: 11.6
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.tegos.eu
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://:mjEW4Q$PTknvQfPx@redis-svc:6379/2, redis://:mjEW4Q$PTknvQfPx@redis-svc:6379/2, regular
 * Platform: Linux 4.15.0-1069-azure (x86_64)

check --deploy:
System check identified some issues:

WARNINGS:
?: (security.W005) You have not set the SECURE_HSTS_INCLUDE_SUBDOMAINS setting to True. Without this, your site is potentially vulnerable to attack via an insecure connection to a subdomain. Only set this to True if you are certain that all subdomains of your domain should be served exclusively via SSL.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.1/admin/backup.html

System check identified 4 issues (1 silenced).

**Comment by sthomae01** [comment]
Yes, if i click on the link it directs me to the project site. We had a project URL that did not work earlier but now the URL is correct.

**Comment by nijel** [comment]
Weblate does nothing special here. So most likely  the site actually returns HTTP 404 for it (based on user agent or whatever).

Can you please try running `curl -v URL` to check the response?

**Comment by sthomae01** [comment]
Our problem was that we tried to use the site of a project that was set on private so it returned 'Access Denied'. It seems like we don't really get what the project website is used for but we can fix it now. Thanks.

**Comment by nijel** [comment]
Hmm, in case of login requiring links it probably makes sense to provide option to dismiss such alert.
