### ISSUE TITLE
Improve check dismiss UI

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#4068]
Make the "all languages" option a checkbox instead of additional button.

Current look:

![dialog-checks](https://user-images.githubusercontent.com/212189/85120230-40dc4b80-b223-11ea-898d-51d37ab26326.png)

Desired look:

![image](https://user-images.githubusercontent.com/212189/85120302-58b3cf80-b223-11ea-83b5-a92331dc8753.png)

**Comment by omaratta212** [comment]
I would like to work on that

**Comment by nijel** [comment]
Great, I've assigned it to you. Thanks

**Comment by Anubhav652** [comment]
I'd like to work on this

**Comment by nijel** [comment]
You're welcome, reassigned.

**Comment by Anubhav652** [comment]
I plan to implement it by converting the a href links into a form. I will merge ignore_check and ignore_check_source functions in trans/views/js.py and handle accordingly if the checkbox was ticked or not. Is this fine?

**Comment by nijel** [comment]
Sounds good. Just make sure the permission checks are kept - the source dismiss needs different permission.

**Comment by Anubhav652** [comment]
Okay. How do I undismiss a check?

**Comment by nijel** [comment]
That's already implemented in trans/views/js.py

**Comment by Anubhav652** [comment]
@nijel Not for implementation purposes. Like, from the UI how'd I reverse my ignore check later on, so I can test more easily

**Comment by nijel** [comment]
Once the check is dismissed, it looks like:

![image](https://user-images.githubusercontent.com/212189/96713788-6e87fb80-13a1-11eb-87ac-7d9c91f3de34.png)
