### ISSUE TITLE
RTL support in comments

### ISSUE THREAD

**Issue by jwtiyar** [WeblateOrg/weblate#4070]
Hey
I have a problem while commenting in transaltion of mozilla, when i type in Central Kurdish which is (RTL), The sentence will be miss-ordered when english letters is inside it.

**Comment by nijel** [comment]
Can you please provide screenshot of wrong behavior and what is expected?

**Comment by jwtiyar** [comment]
Thanks for replay
When i type the comment everything is good it detects the language direction like this:
[Right Direction](https://ibb.co/PW5xVVp)
But when the comment goes live become like this:
[Wrong Direction](https://ibb.co/ggvJkx9)

**Comment by nijel** [comment]
Neither of that seems to be screenshotted from Weblate...

**Comment by jwtiyar** [comment]
What you mean? i don't nderstand.
Currently iam wokring on LibreOffice Translation, this two picture from comments below strings.

**Comment by jwtiyar** [comment]
Really Sorry dear nijel
Its another project, I thought iam writing in correct place, because iam working on LibreOffice i was confused between Weblate and Pontoon. I didn't realize that iam on weblate not pontoon repository.
Sorry again.
