### ISSUE TITLE
Localization guide naming and placement

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#4075]
Several people complained that [Localization guide](https://docs.weblate.org/en/latest/devel/community.html#localization-guide) is hard to find and not clearly named. Let's figure out something better.

It is supposed to be a guideline how to make the localization process smoother. It doesn't indicate an error (we have [alerts](https://docs.weblate.org/en/latest/devel/alerts.html) for this)

**Comment by nijel** [comment]
Got also few suggestions:

- "Community Setup Tips"
- "Setup Tips"
- "Configuration Tips"
- "Optimization Tips"
- "Community Setup Suggestions"
- "Setup Suggestions"

**Comment by fitojb** [comment]
To me, this page is a _checklist_, not a _guide_ per se.
