### ISSUE TITLE
Are google language codes compatible with Weblate?

### ISSUE THREAD

**Issue by ssuess** [WeblateOrg/weblate#4078]
**Describe the bug**
We are using MT with Google Translate services, and it seems that google is always returning simplified Chinese (`zh_Hans`), whether or not we have chosen to translate Traditional Chinese (`zh_Hant`). And when I look at google's page for codes, it seems the ones they are using (`zh-CN` for simplified and `zh-TW` for traditional) are different than the ones weblate uses. And there is no way that I can find to add Google's codes to weblate.

**To Reproduce**
1. Click on  'Start new translation' button and add 'Chinese (Traditional) (zh_Hant)'
2. Go into 'Chinese (Traditional)' translation and then perform an  'Automatic Translation' using Google Translate 

**Expected behavior**
Traditional Chinese translation

**Actual Result**
Simplified Chinese translation

**Additional context**
Here is the page for Google's language codes: [https://developers.google.com/recaptcha/docs/language](https://developers.google.com/recaptcha/docs/language)

**Comment by nijel** [comment]
The machine translation engine should convert the Weblate language codes automatically, but that doesn't seem to be happening for Chinese right now in Google Translate.

PS: The Google translate language codes are here: https://cloud.google.com/translate/docs/languages
