### ISSUE TITLE
MS Azure Authentication AD auth - Could not authenticate due to invalid session state.

### ISSUE THREAD

**Issue by tregin** [WeblateOrg/weblate#4079]
**Describe the bug**

Hello I'm currently implementing Weblate with MS Azure Authentication AD.
Weblate is running on Openshift OKD cluster and has a route link setup to  "https://external-OKD-link-to-weblate.me"... obviously we wanted to to make this link "pretty" we created a separate DNS name which point to this link.
DNS works but when I try to authenicate via MS Azure AD I get following error:

Could not authenticate due to invalid session state.

The callback URL have been specified the:
https://newDNSentry/accounts/complete/azuread-tenant-oauth2/

**Comment by nijel** [comment]
Check Weblate logs for more detailed errors.

**Comment by tregin** [comment]
The exact error is:
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 

The call back url when azure is returning the authentication callback URL is still pointing to the old URL yet the old URL does not exists on Azure AppRegistration anymore... 

Could it be some sort of cache on Azure side?

**Comment by nijel** [comment]
Check that callback URL domain matches what is configured as domain in Weblate, see https://docs.weblate.org/en/latest/admin/install.html#production-site

**Comment by tregin** [comment]
Amazing @nijel!! That did the trick... 
Now the question is is there a variable for either Docker Compose or Openshift template (which I'm using) through which I could setup such domain name during the deployment?
Something like: WEBLATE_DOMAIN_NAME ? 

Thanks very much!

**Comment by nijel** [comment]
Yes, first from [https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_ALLOWED_HOSTS](WEBLATE_ALLOWED_HOSTS) is used for that.
