### ISSUE TITLE
Translation text too long error

### ISSUE THREAD

**Issue by okainov** [WeblateOrg/weblate#4081]
**Describe the bug**

Kind of the same as #2380

I do have monoligual set up with keys being msgid. As mentioned in #3973, I do have "en_devel" set as "source language" which I don't really care about.

After generating my .po files from the code, my `en_devel` file looks like
```
#, php-format
msgid "email_coauthor_new_note"
msgstr ""

msgid "1665"
msgstr ""
```

And my `ru` file contains actual texts of those messages.

When I go to my Weblate instance, I see:
1. "`ru`" strings marked as "need edit" and I cannot save them due to "translation too long"... While they are (1) not translations but original texts and (2) the only actual translations present in the file
2. `en_devel` strings are empty and `email_coauthor_new_note` is shown only as context, not as the text itself.

While I somehow understand why Weblate gives this error, I see no way what I can do to avoid it. I don't see options for `msgmerge`/`xgettext` to copy `msgid` to `msgstr` for one given language. As I'm using monoligual setup with string Ids==keys, Weblate shouldn't check the "source" at all, I should be allowed to put whatever string I want.

**Comment by okainov** [comment]
And it's also reproducible not only for empty strings, but for the keys-strings as well

ID `coauthor_new_find`
Translation item:
`Item ¤<a href="https://mydomain.com/?pn=101&cid=%2$s&utm_source=notification&utm_medium=email&utm_campaign=coown_find">%1$s</a>¤, соавтором которого Вы являетесь, отмечен как найденный игроком <b>%3$s</b>.`

Not accepted, "too long"

**Comment by nijel** [comment]
If you are using monolingual files, configure Weblate that way and set [Monolingual base language file](https://docs.weblate.org/en/latest/admin/projects.html#monolingual-base-language-file).

**Comment by okainov** [comment]
>If you are using monolingual files, configure Weblate that way and set Monolingual base language file.


I did. That's what I said, that I have it set up as monolingual

**Comment by nijel** [comment]
Okay, then you need some translations in en_DEVEL so that users can translate the strings.

> And my ru file contains actual texts of those messages.

Maybe it should be then the base file as it contains the actual texts? How is translators supposed to translate if he doesn't see the source string?

**Comment by okainov** [comment]
> Okay, then you need some translations in en_DEVEL so that users can translate the strings.

There are none, there are ids, like `new_note_title`. I really feel absolutely the same as in #3973. I'd like to have the better examples and the usage models of Weblate, maybe I'm just not getting what you mean. I did set it up in some way it works okay for us now, but if that was not the "right" way - I'm open for suggestions. But I don't have "single" source of the strings in general case.

>Maybe it should be then the base file as it contains the actual texts? How is translators supposed to translate if he doesn't see the source string?

Might be, but the idea is that there is not necessarily ru text added by the developers, some developers add id (en_devel) AND "ru" as part of their contribution, other developers add id  (en_devel) AND "en". The only single common point is ID, but there is no single "base" language. So for the translators to the third language we don't know whether there will be ru or en string available: maybe both, maybe just one of them.

**Comment by nijel** [comment]
Somebody has to provide the initial strings. In most cases, it's done by developers who add these IDs as they know what they mean. How is translator supposed to figure out meaning of the string when he has just ID? 

Having adding random languages and translating from those will be typically bad for translation quality. You can use intermediate translation to consolidate whatever you get from developers into single language and translate it then, see https://docs.weblate.org/en/latest/workflows.html#quality-gateway-for-the-source-strings

**Comment by okainov** [comment]
>Somebody has to provide the initial strings. 

That's what I said. Developer provides them. But in no fixed language, EITHER Russian OR English.  No single source language. I think I'm repeating myself for the third time or not more, is my case so special so you don't seem to understand what I mean?

**Comment by nijel** [comment]
Weblate needs to know the source string for many features. Several features in Weblate rely on source strings being available. The quality checks look at the source string and check target string based on the source string content. You can disable all checks if you don't have single source language, but other things will probably break as well.
