### ISSUE TITLE
PHP "%s" is treated as "wrong format"

### ISSUE THREAD

**Issue by okainov** [WeblateOrg/weblate#4082]
**Describe the bug**
`%s` is raising PHP format error

```
 PHP format
Following format strings are wrong: %s
```

**To Reproduce**
1. Create any source string having `%s` like `Hi, %s` 
2. Check Weblate for this string
3. Make sure PHP warning appears

**Expected behavior**
This is perfectly valid PHP format string and shouldn't create any warnings

**Comment by nijel** [comment]
It indicates which format strings are missing in the translation, see https://hosted.weblate.org/translate/phpmyadmin/4-9/hr/?checksum=a7046ce920750295 for example - the transaltion uses `%s` while the source has `%1$s` and `%2$s`.

**Comment by okainov** [comment]
Ahm, then maybe it's related to #4081

I have source language `en_devel` which has IDs as strings

```
msgid: email_own_cache_new_note
translation: В интернет-блокнот Вашего тайника ¤%s¤ внесена новая запись.
```

Obviously ID don't have these placeholders.

**Comment by nijel** [comment]
Okay, first configure Weblate to see the actual source strings and many issues will sort out then.

**Comment by okainov** [comment]
@nijel what is the "proper configuration" then? I was asking this question in #3973 and the best approach I could use is to have fake `en_devel` as a source and then different languages in there

**Comment by nijel** [comment]
Proper configuration is anything what will Weblate know what is the source string. The quality checks need to know what is present in the source string to properly evaluate whether translation is correct.
