### ISSUE TITLE
Cannot translate string: "Source in review"

### ISSUE THREAD

**Issue by okainov** [WeblateOrg/weblate#4083]
**Describe the bug**
I have no idea why, but some of my strings have mark "Source in review" and I (admin) cannot do anything with them. When I click save, I'm getting error `Error in parameter review: Select a valid choice. 100 is not one of the available choices.`.

![image](https://user-images.githubusercontent.com/918446/85457718-a708fb80-b5a0-11ea-9d0d-6c5a29f99cc1.png)

**To Reproduce**
No idea really...

**Expected behavior**
Admin should be able to edit all strings regardless of anything.

There should be proper indication, what exactly is wrong

**Comment by nijel** [comment]
The source string is not translated, probably the root cause being same as in https://github.com/WeblateOrg/weblate/issues/4081#issuecomment-648658355
