### ISSUE TITLE
Color distribution is not following the real proportion

### ISSUE THREAD

**Issue by okainov** [WeblateOrg/weblate#4085]
Screenshot describes it better than anything else, hope it's clear enough

![image](https://user-images.githubusercontent.com/918446/85459153-29de8600-b5a2-11ea-96b4-500569efac36.png)

**Comment by nijel** [comment]
These categories do overlap, so the mapping can never be really accurate. But it could be done better.

**Comment by okainov** [comment]
I don't even see a theoretical possibilities from the screenshot what can "overlap" in this case. I have just one blue string and 1900 strings in total.  1 could be part of the orange, then blue part should be 0 (which would be also strange, but at least understandable). 1 can be 0.05% of the whole bar which would be understandable. But 1 cannot ever be equal to 30% of 1900 ;)

**Comment by nijel** [comment]
There can be approved string with failing check. It's shown as approved in the progress bar, but it will be listed in both categories in detailed listing.
