### ISSUE TITLE
Confusing Error: The component contains several translation files mapped to a single language in Weblate.

### ISSUE THREAD

**Issue by buck-E** [WeblateOrg/weblate#4088]
```
The component contains several translation files mapped to a single language in Weblate. Please fix this by removing one of the translation files.

Please consider the following:

In case the translation to the source language is desired, please change the source language in the project settings. 
In case the translation file for the source language is not needed, please remove it from the repository.
In case the translation file for the source language is needed, but shoud be ignored by Weblate, please adjust the language filter to exclude it. 
The following occurrences were found:

Language | Language codes
-- | --
English | en, en

```

What does this error mean?  Especially:

`The component contains several translation files mapped to a single language in Weblate. Please fix this by removing one of the translation files.`

I should remove one of the other languages that maps to the single language in Weblate?  Where do I see this mapping?  What should I remove?

I only see one `messages.po` file under `/en/LC_MESSAGES`.

**Comment by nijel** [comment]
Please consider the following:

* In case the translation to the source language is desired, please change the source language in the project settings. 
* In case the translation file for the source language is not needed, please remove it from the repository.
* In case the translation file for the source language is needed, but shoud be ignored by Weblate, please adjust the language filter to exclude it.
