### ISSUE TITLE
Status widgets for Component Lists

### ISSUE THREAD

**Issue by rob006** [WeblateOrg/weblate#4089]
I have one big project with over a hundred components. I tried to divide them into smaller groups using component lists, but it does not help that much without status widget for each group - separate groups may have different priorities, it would be useful to have quick insight if particular group requires some action. Having status widgets for components list similar to [project status widgets](https://hosted.weblate.org/widgets/weblate/) would be great.

**Comment by nijel** [comment]
Recently introduced categories better serve such purpose than component lists and those come with a status widget.
