### ISSUE TITLE
Language view for Component Lists

### ISSUE THREAD

**Issue by rob006** [WeblateOrg/weblate#4090]
There is a separate view with list of project components for specified language: https://hosted.weblate.org/languages/pl/weblate/
It would be great to have the same for component list (something like `https://hosted.weblate.org/component-list/component-list-slug/pl/`). Right now if I'm interested only in one language, component list does not give any valuable info, since it mixes all languages, so it is impossible to guess which components may require some action from me. 

related: #4089

**Comment by nijel** [comment]
Recently introduced categories better serve such purpose than component lists and those come with a language views.
