### ISSUE TITLE
improve notifications

### ISSUE THREAD

**Issue by jzahradn** [WeblateOrg/weblate#4092]
Hi,
we have Weblate 3.11.3 connected to Gitlab. During last Weblate server and Gitlab server maintenance, Weblate sent 103 alerts 'fatal: Could not read from remote repository' to our internal users and also to our partners. I need to avoid this spamming in the future. I know I can use a workaround, which is about disabling emails in Weblate, then restart Weblate, do Gitlab maintenance, enable emails in Weblate and restart Weblate again. However, it is quite complicated. I think such fatal notifications describing connection to remote server error should be sent to administrators only. Is it possible to set it somewhere in the settings?
Thank you
Regards
Jan

**Comment by nijel** [comment]
By default, it is sent to users who can manage given component. It can be configured in the profile.

**Comment by jzahradn** [comment]
I know. But I cannot say all the users to disable notifications in their profiles during maintenance tasks. So tip for improvement is to add some checkbox to admin area to disable all notifications in given project with immediate effect (not required restart). From time to time it could be very useful during servers maintenance and outages.

**Comment by nijel** [comment]
I'm not sure such toggle would address your issue - the problem was GitLab maintenance, not Weblate maintenance. In case Weblate would not be running, it would not trigger the errors. And will you always remember to toggle something on Weblate when you do GitLab maintenance?

**Comment by jzahradn** [comment]
It is useful not only for maintenance tasks. For example when I created approx. 60 components via scripts using API, our users and partners also received 60 notifications. After complaints I needed to disable sending emails at all in settings.py. And because 'service emperor.uwsgi restart' did not apply the change, I had to restart the server. This is the second example where disabling emails on a button would be a good feature.

**Comment by nijel** [comment]
The notifications are sent in background by Celery, so to apply the setting it has to be restarted.

Reviewing the default enabled notifications now and I think that the new component and translation ones really should be opt in than opt out, so I've removed these for default set in 0cb5bff87280b9f18e135a37f8389338f7cb3665.
