### ISSUE TITLE
Incremental fetching of changes doesn't seem to work

### ISSUE THREAD

**Issue by valeriocos** [WeblateOrg/weblate#4095]
**Describe the bug**

I tried to fetch changes from a given date without success. 

- Side comment 1: the `next` url returned by the response contain the param `timestamp_after` (see image below). I understand that this param should be used only to get the first page, the next pages shouldn't include it.

![captura_500](https://user-images.githubusercontent.com/6515067/85739760-5ceb5b80-b701-11ea-95b8-b1159feee0f7.png)

- Side comment 2: by looking at the [documentation](https://docs.weblate.org/en/latest/api.html#get--api-changes-) I see that this has been implemented only for the endpoint `api/changes`. However, the feature request at https://github.com/WeblateOrg/weblate/issues/3658 was about to support the incremental fetching for a given project (e.g., https://translations.documentfoundation.org/api/projects/libo_help-6-3/changes/?timestamp_after=2020-01-01T00%3A00%3A00%2B00%3A00). I don't know if this decision is a misunderstanding or not.

**To Reproduce**

1. Go to https://translations.documentfoundation.org/api/changes/?timestamp_after=2020-01-01T00%3A00%3A00%2B00%3A00
2. Check that the results returned contain a date prior to 2020-01-01

**Expected behavior**

Only the changes after a given date should be returned

**Screenshots**

![captura_499](https://user-images.githubusercontent.com/6515067/85738206-2234f380-b700-11ea-921a-09d989515221.png)

**Comment by nijel** [comment]
https://github.com/WeblateOrg/weblate/issues/3658 was implemented in Weblate 4.1, but https://translations.documentfoundation.org/ runs Weblate 3.10.3, so it's expected that it ignores this parameter.

**Comment by valeriocos** [comment]
thank you for the quick reply @nijel

**Comment by nijel** [comment]
On the other side, you seem to be correct that it won't work on the project changes endpoint...

**Comment by nijel** [comment]
https://hosted.weblate.org/ now has deployed fixed API
