### ISSUE TITLE
Question about Rate Limit

### ISSUE THREAD

**Issue by valeriocos** [WeblateOrg/weblate#4097]
I'm checking the headers about rate limit info. I would like to know the unit of time of the values returned in `X-RateLimit-Reset` (see example below). I'm not able to find this info on https://docs.weblate.org/en/latest/api.html#rate-limiting.

![captura_502](https://user-images.githubusercontent.com/6515067/85860058-6edf0400-b7be-11ea-92ae-064ff559d7b5.png)

**Comment by nijel** [comment]
I think it should be seconds, but I need to check the code and document it properly.
