### ISSUE TITLE
Broken project website URL alert only occurred on for some components

### ISSUE THREAD

**Issue by zslucky** [WeblateOrg/weblate#4099]
**Describe the bug**

I have a project, it have many components which sharing one git repo, only a few of them show this alert.

Broken project website URL
```bash
This project is set up incorrectly.

The project website URL points to a non-existing location:

https://www.xxxxxxx.com (('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
```
I'm not sure how does it worked, this setting looks like configured for project, do you think it should passed or blocked at the same time? 

Or if they checked 1-by-1, it may blocked by our network policy? If that, is it necessary to disable this check?

**To Reproduce**

1. Create a project and configure a https url.
2. Create many components in it.
3. wait for url check

**Server configuration and status**

```bash
* Weblate: 4.1.1
* Django: 3.0.7
* siphashc: 1.3
* Whoosh: 2.7.4
* translate-toolkit: 3.0.0
* lxml: 4.5.1
* Pillow: 7.1.2
* bleach: 3.1.5
* python-dateutil: 2.8.1
* social-auth-core: 3.3.3
* social-auth-app-django: 3.4.0
* django-crispy-forms: 1.9.1
* oauthlib: 3.1.0
* django-compressor: 2.4
* djangorestframework: 3.11.0
* django-filter: 2.3.0
* django-appconf: 1.0.4
* user-agents: 2.1
* filelock: 3.0.12
* setuptools: 40.8.0
* jellyfish: 0.8.2
* openpyxl: 3.0.1
* celery: 4.4.5
* kombu: 4.6.10
* translation-finder: 2.1
* html2text: 2020.1.16
* pycairo: 1.16.2
* pygobject: 3.30.4
* diff-match-patch: 20181111
* requests: 2.24.0
* django-redis: 4.12.1
* hiredis: 1.0.1
* sentry_sdk: 0.15.1
* Cython: 0.29.20
* misaka: 2.1.1
* GitPython: 3.1.3
* borgbackup: 1.1.13
* pyparsing: 2.4.7
* Python: 3.7.3
* Git: 2.20.1
* psycopg2: 2.8.5
* psycopg2-binary: 2.8.5
* phply: 1.2.5
* chardet: 3.0.4
* ruamel.yaml: 0.16.10
* tesserocr: 2.5.1
* akismet: 1.1
* boto3: 1.14.6
* zeep: 3.4.0
* aeidon: 1.7.0
* iniparse: 0.5
* mysqlclient: 1.4.6
* Mercurial: 5.4.1
* git-svn: 2.20.1
* git-review: 1.28.0
* hub: 2.13.0
* lab: 0.16
* Redis server: 4.0.14
* PostgreSQL server: 11.8
* Database backends: django.db.backends.postgresql
* Cache backends: default:RedisCache, avatar:FileBasedCache
* Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.gmail.com
* OS encoding: filesystem=utf-8, default=utf-8
* Celery: redis://cache:6379/1, redis://cache:6379/1, regular
* Platform: Linux 4.14.143-118.123.amzn2.x86_64 (x86_64)
```

**Comment by nijel** [comment]
Connection reset by peer - seems like a temporary error, it's quite likely that it failed only for part of the probes. Also, the positive probing result is cached to avoid doing too many requests, so it seems that some of the first probes failed.

**Comment by zslucky** [comment]
thanks @nijel , is it necessary to disable this checking?

And these days I also get an error `The Celery does not process tasks, or is too slow in processing them.`.
According to docs, Celery will run background tasks, but I'm not sure does it matter? 

I also setup my Sentry server with Weblate correctly, but no any error message from Celery, what I missed?

**Comment by nijel** [comment]
> thanks @nijel , is it necessary to disable this checking?

There is currently no way to disable this check, see https://github.com/WeblateOrg/weblate/issues/4067

> The Celery does not process tasks, or is too slow in processing them.

Check lengths of the Celery queues on bottom of /manage/performance/ page. Is Celery running?

**Comment by zslucky** [comment]
@nijel , yes sure, Celery is running, but queue is large enough, celery ran slowly, the length decreased slowly, and in creased quickly... 

I found many SMTP related errors in Sentry, this may due to wrong admin email address, so I update this address to a correct address, then restart service, now everything goes well.

**Comment by zslucky** [comment]
For broken project website URL issue, how often it checked? does it checked every time I changed?

**Comment by nijel** [comment]
It is checked nightly and on change.

**Comment by zslucky** [comment]
@nijel looks like not checked when I changed it...

**Comment by nijel** [comment]
The check happens in background using Celery task, so it is not immediate. Is Celery working fine in your setup?

**Comment by zslucky** [comment]
Sure, working fine. no task delay, but project url check not happened anymore...

**Comment by nijel** [comment]
Can you component_alerts task in Celery logs after changing project URL?

**Comment by zslucky** [comment]
![image](https://user-images.githubusercontent.com/15725589/86886382-66c18580-c129-11ea-8f44-02b416702671.png)

@nijel looks like task received, but I'm not sure why it use standard error output...

I'm using docker-compose

**Comment by nijel** [comment]
The logging goes to stderr AFAIK, so that's expected. In case it's not followed by an error message, it should trigger the update.

**Comment by zslucky** [comment]
But still shows alert, and still on those components, the alert shows it checked 8 days ago...

![image](https://user-images.githubusercontent.com/15725589/86988339-95436d00-c1ca-11ea-8a6d-b2cfca5522fc.png)

**Comment by nijel** [comment]
It shows when the alert occurred for the first time, not when it was last checked.

**Comment by zslucky** [comment]
OK I see, no idea now...

**Comment by nijel** [comment]
I've made some improvements for the 4.2 release: 43d45d5f6558e3ba974b2dc8c54bf01604c2b8b8 will log the URL check results, so that it's easier to debug and 47803b8f756c0caadeaa75a0b11f18dad9bd988c will show last hit timestamp as well.

**Comment by zslucky** [comment]
Thanks so much, I will upgrade and provide latest log later. 👍

**Comment by zslucky** [comment]
@nijel hello could you pls upgrade latest docker image? 😄

**Comment by nijel** [comment]
Use `bleeding` tag for testing latest git snapshot.

**Comment by zslucky** [comment]
Thanks @nijel , after I use `bleeding` tag image, I confirmed weblate version is up to date, I tried again, but still only show the `component_alerts`, no more other logs...

![image](https://user-images.githubusercontent.com/15725589/87372242-a53bc200-c5b9-11ea-91b3-3fca9a80f5e8.png)

**Comment by nijel** [comment]
AFAIR it is shown by default in debug mode only, not sure if you have enabled that.

**Comment by zslucky** [comment]
Yeah, I checked my `environment` file just now, it's in debug mode.

**Comment by nijel** [comment]
What version does Weblate report? Maybe the Docker tag was not properly updated...

**Comment by zslucky** [comment]
weblate 4.2-dev

**Comment by nijel** [comment]
Do you have WEBLATE_LOGLEVEL set?

**Comment by zslucky** [comment]
Thanks, after I set `WEBLATE_LOGLEVEL=DEBUG`, I can see the debug log. This time I used another new website link, and this time I saw all components `cache success`, and alerts disappeared. After I changed website link back to old link, no additional logs and alerts doesn't showed again.

Looks like this cache doesn't refreshed anymore, or every link share the cache?

**Comment by nijel** [comment]
The first one should report `tested success`, only next ones should get `cached success`. The successful result is cached per URL and for one hour.

**Comment by zslucky** [comment]
OK, thanks so much! 👍
