### ISSUE TITLE
“Expected end of text” error when searching for ASCII quotes in translations

### ISSUE THREAD

**Issue by fitojb** [WeblateOrg/weblate#4101]
**Describe the bug**

Using the search form to look for the characters `'` and `"` no longer works.

This is a regression. The current version at hosted.weblate.org (4.2-dev) exposes this behavior, while e.g. 3.10.3 works as expected.

**To Reproduce**

1. Go to https://hosted.weblate.org/projects/weblate/application/ca/#search
2. In the “Custom Search” box, query for either `'` or `"`
3. Press Enter

**Expected behavior**

The strings containing that character are listed.

My use case is: in Spanish and Catalan we use guillemets `« »` as quotation marks, so I query for those in combination with `target:` to find any translated string that doesn’t use guillemets.

**Comment by nijel** [comment]
The quotes have been syntax chars in the search for several releases, but with rewriting of the parser it got a bit too strict. Anyway you can always put the string into quotes to avoid such problems: `"'"` or `'"'`

See also https://docs.weblate.org/en/latest/user/search.html#simple-search
