### ISSUE TITLE
The component contains several translation files mapped to a single language in Weblate.

### ISSUE THREAD

**Issue by buck-E** [WeblateOrg/weblate#4104]
I have this alert on every translation in a Component.  Source language is set to `English (Developer)`.  The UI is missing the info icon to click on for more information, or detailed instructions.

```
The component contains several translation files mapped to a single language in Weblate. Please fix this by removing one of the translation files.

The following occurrences were found:

Language	Language codes
English	en, en
```

**Comment by nijel** [comment]
What files are present in the repository?
