### ISSUE TITLE
Live preview of search queries

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#4106]
**Is your feature request related to a problem? Please describe.**
When typing search queries in places like bulk edit or custom download, it would be useful to get a preview of matching strings.

**Describe the solution you'd like**
* Show number of matching string next to the search input. Should be live updated as typing, possibly with some delay to reduce server-side load.
* Add link to search showing matched strings.

**Comment by GG-Sheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by meel-hd** [comment]
@nijel I started working on this.  first by working on `Search and Replace`. I will make the handler of the Post request of this tool check if a certain header is available indicating preview then it will return only the search result as JSON for the preview without performing the `Replace`. then consume the response and show it in a `popover` while the user is typing with a _certain interval._

**Comment by nijel** [comment]
I think you can use API to perform the search server-side (see https://docs.weblate.org/en/latest/api.html#units). It might need additional predicate to support filtering by URL path to make things easier to implement.

**Comment by meel-hd** [comment]
I have implemented it in [73a50ef](https://github.com/meel-hd/weblate/commit/73a50eff8e42379be16c522af64d16a335e125f1) for `Search and Replace` but not sure about the correctness of the results. meaning if the api returns the `units` related to the current project we are trying to edit, etc.
![image](https://github.com/user-attachments/assets/e5145613-7bc2-40a8-a26f-15de04217c10)

**Comment by meel-hd** [comment]
@nijel from reading the docs about `api/search` I am not sure what is exactly needed to implement the search preview in `Tools`. I wonder what is missing to add, so this endpoint is complete for the search preview. I might jump on it and them!

**Comment by nijel** [comment]
https://github.com/WeblateOrg/weblate/pull/12460 implements the missing filtering for the search queries.

**Comment by nijel** [comment]
Ah, and the preview should be applied to the filter field above, this one is only a string to replace.
