### ISSUE TITLE
'NoneType' object has no attribute 'mode'

### ISSUE THREAD

**Issue by TheLastProject** [WeblateOrg/weblate#4114]
**Describe the bug**

I get an email saying `'NoneType' object has no attribute 'mode'` every few hours

**To Reproduce**

No clue, it just started happening today

**Expected behavior**

No exceptions in my email

**Screenshots**

![Screenshot_20200630_200628](https://user-images.githubusercontent.com/1885159/86161202-31a3aa80-bb0d-11ea-8153-5743a15c6dbd.png)

**Server configuration and status**

Hosted Weblate

**Additional context**

This seems to happen on the https://hosted.weblate.org/projects/pext/pext/ component.

**Comment by nijel** [comment]
Should be fixed now, seems like a migration issue.
