### ISSUE TITLE
Error: app 'glossary' isn't installed

### ISSUE THREAD

**Issue by minusf** [WeblateOrg/weblate#4116]
**Describe the bug**

After upgrading from 3.11.1 to 4.1.1 I get the following error:

```
SystemCheckError: System check identified some issues:

ERRORS:
trans.Change.glossary_term: (fields.E300) Field defines a relation with model 'glossary.Term', which is either not installed, or is abstract.
trans.Change.glossary_term: (fields.E307) The field trans.Change.glossary_term was declared with a lazy reference to 'glossary.term', but app 'glossary' isn't installed.
```

**To Reproduce**

1. Upgrade to 4.1.1
2. Start weblate
3. See error

**Expected behavior**

Running Weblate

**Server configuration and status**

```
 * Weblate: 85c68b7
 * Django: 3.0.8
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0
 * lxml: 4.5.1
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.4.0
 * django-crispy-forms: 1.9.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 41.2.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.4
 * celery: 4.4.6
 * kombu: 4.6.11
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.36.1
 * diff-match-patch: 20181111
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.0.1
 * sentry_sdk: 0.15.1
 * Cython: 0.29.20
 * misaka: 2.1.1
 * GitPython: 3.1.3
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.7
 * Git: 2.24.2
 * psycopg2-binary: 2.8.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * Redis server: 6.0.5
 * PostgreSQL server: 12.3
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.console.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://127.0.0.1:6379, redis://127.0.0.1:6379, regular
 * Platform: Darwin 19.5.0 (x86_64)
```

**Comment by nijel** [comment]
Please follow upgrading instructions: https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-4-0-to-4-1

**Comment by minusf** [comment]
will pay more attention to upgrade instructions, sorry. thank you.

**Comment by reloxx13** [comment]
changes in INSTALLED_APPS is "mentioned" but not what to do...

**Comment by nijel** [comment]
Contributions to improve the docs are always welcome.

**Comment by minusf** [comment]
weblate is a big project with many moving parts...  i think that the upgrade manual has very good pointers:

> There are several changes in settings_example.py, most notable middleware changes, please adjust your settings accordingly.

and the Generic update instructions start with that right away:

> Once all requirements are installed or updated, please adjust your settings.py to match changes in the configuration (consult settings_example.py for correct values).

instead of listing every single change, i find `diff`ing the settings file quicker both for the authors and the administrators, esp for someone with django experience.

**Comment by reloxx13** [comment]
yep, it was just my note or my exp with the update as a non/unexperience python/django user.

i dont get why this is in settings for "users". imho there should be a system settings and an extending user settings. 

but its done now :D


PostgreSQL extension also made me struggle :p

**Comment by nijel** [comment]
> i dont get why this is in settings for "users". imho there should be a system settings and an extending user settings.

Because we use normal Django settings, having that split from user settings would be useful for most use cases, see https://github.com/WeblateOrg/weblate/issues/4017

If you struggle with that, we offer several paid options to take care of your Weblate instance ;-). See https://weblate.org/support/ and https://weblate.org/hosting/

**Comment by minusf** [comment]
as a developer i like the status quo :D   i think hiding the settings adds complexity and dependencies for questionable returns.  hosting weblate will never be like hosting a wordpress instance but it's very well documented.

**Comment by jjlakis** [comment]
Could anyone actually point what to do with this error? I went through the docs and still have no idea what is wrong. Thanks.

**Comment by nijel** [comment]
@jjlakis Add `weblate.glossary` into `INSTALLED_APPS`.
