### ISSUE TITLE
Weblate changes the JSON structure when full stop appears in translation key

### ISSUE THREAD

**Issue by gorskim** [WeblateOrg/weblate#4117]
**Describe the issue**

I've got typical solution for JSON files and translations (i18n). Whenever there is a full stop in a key, Weblate breaks the original structure of the file and the result is nested JSON - which of course cannot be read properly in the application. Is there a way to keep the original structure?
It seems strange to me because all these strings are seen properly in the Weblate itself (there is no division of one key into two separate ones). 
This is issue is the exact opposite of mine: https://github.com/WeblateOrg/weblate/issues/775
The original file:

```json
{
  "foo. bar": "baz"
}
```

is restructured into:

```json
{
  "foo": {
    "bar": "baz"
  }
}
```

**Comment by nijel** [comment]
Known issue, see https://github.com/translate/translate/issues/3819 and https://github.com/translate/translate/issues/3819

In case you do not need nesting at all, use "JSON file" instead of "JSON nested structure file".
