### ISSUE TITLE
Extending documentation for HTTPS support

### ISSUE THREAD

**Issue by radeklat** [WeblateOrg/weblate#4119]
**Is your feature request related to a problem? Please describe.**

I followed the instruction for setting up Weblate in [Docker container with HTTPS support](https://docs.weblate.org/en/latest/admin/install/docker.html#docker-container-with-https-support), [using own SSL certificates](https://docs.weblate.org/en/latest/admin/install/docker.html#using-own-ssl-certificates). I encountered couple of issues that were not mentioned in the documentation and were quite difficult to diagnose as Weblate itself did not complain either. I arrived to the solution in two days of trial and errors. So I think it would be beneficial to include them for others.

**Describe the solution you'd like**

Include the following in the installation instructions:

1. `ssl/fullchain.pem` and `ssl/privkey.pem` need to be owned by the same user as the one starting the docker container. Additionally, they need to have a `600` access rights mask (can be set by `chmod -R 600 <SSL FOLDER>`).
2. I hit the issue and solution described in #3288, namely I needed the following Nginx setup:
    ```nginx
    server {
            listen 443;
            listen [::]:443;

            server_name <SITE_URL>;
            ssl_certificate /etc/letsencrypt/live/<SITE>/fullchain.pem;
            ssl_certificate_key /etc/letsencrypt/live/<SITE>/privkey.pem;

            location / {
                    proxy_set_header HOST $host;
                    proxy_set_header X-Forwarded-Proto https;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Host $server_name;
                    proxy_pass https://127.0.0.1:<DOCKER_EXPOSED_PORT>; 
            }
    }
    ```
    The `proxy_set_header` values were the things missing for me. These instructions are specific to using own Nginx and Let's Encrypt.

I would be more than happy to do a PR if there is an appetite.

**Describe alternatives you've considered**

Keeping it to myself and let other fail.

**Additional context**

None...

**Comment by nijel** [comment]
Patches are always welcome, please go ahead :-).
