### ISSUE TITLE
Erroneous sentence

### ISSUE THREAD

**Issue by KovalevArtem** [WeblateOrg/weblate#4121]
**Describe the bug**

The proposed change is identical to the original translation.

**To Reproduce**

https://hosted.weblate.org/translate/openwrt/luciapplicationsunbound/ru/?q=check:inconsistent#suggestions

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/36500228/86301722-40728600-bc0f-11ea-82a2-9092658cbdb1.png)

Weblate 4.2-dev

**Comment by nijel** [comment]
Most likely the suggestion was there and the string was changed afterwards. There is regular cleanup job to remove these, see https://hosted.weblate.org/translate/openwrt/luciapplicationsunbound/ru/?checksum=734c7e2c05319b22#history
