### ISSUE TITLE
Change the interface language on the fly

### ISSUE THREAD

**Issue by KovalevArtem** [WeblateOrg/weblate#4122]
**Is your feature request related to a problem? Please describe.**
Fast and convenient switching of the site interface to the desired language.

I created a [issue](https://github.com/WeblateOrg/weblate/issues/4121). I needed to attach a screenshot. I wanted to change the interface of the site to English, so that it was more convenient and understandable for everyone. But I did not understand how to change the site interface to another language.
I am sure that a quick change of interface language will also be useful when testing translations of the Weblate platform itself.

**Comment by nijel** [comment]
It's in the user settings, the very first thing there:

![image](https://user-images.githubusercontent.com/212189/86318145-77f22a00-bc31-11ea-8b7e-069259b14f39.png)

**Comment by KovalevArtem** [comment]
And if the user is not authorized on the site?

**Comment by nijel** [comment]
Then whatever is configured as preferred language in the browser is used. One of the reasons is that we don't have user consent to store optional cookies at that point.
