### ISSUE TITLE
The inconsistency checker reports two identical translations as inconsistent

### ISSUE THREAD

**Issue by petterreinholdtsen** [WeblateOrg/weblate#4129]
This is similar to issue #3494, where you asked similar issues to be reported as a new issue.

The inconsistency checker report two identical strings in the Norwegian Bokmål translation available from
<URL: https://hosted.weblate.org/checks/inconsistent/debian-handbook/?lang=nb_NO > as inconsistent, even though both strings are identical.  The translations in question are both "&lt;primary>kvote&lt;/primary>" (HTML escaped to keep github happy).

**Comment by nijel** [comment]
Possibly related to not properly highlighting whitespace changes, see https://github.com/WeblateOrg/weblate/issues/4132

**Comment by petterreinholdtsen** [comment]
[Michal Čihař]
> Possibly related to not properly highlighting whitespace changes, see
> https://github.com/WeblateOrg/weblate/issues/4132

Perhaps, but no matter which translation I use with the 'Use this
translation' button, I still get the inconsistency warning, so if so
there is something else going on here too.  I am starting to suspect
some strange caching going on, not discovering that the translations are
now identicial.

-- 
Happy hacking
Petter Reinholdtsen
