### ISSUE TITLE
Missing instructions for muting DisallowedHost warning

### ISSUE THREAD

**Issue by JulianGro** [WeblateOrg/weblate#4148]
In a production setup you get spammed with messages like `Invalid HTTP_HOST header: '0'. You may need to add '0' to ALLOWED_HOSTS.` in sentry and via email.
While there is apparently options to disable this in Django, there do not appear to be any docs on this topic.
Documentation on how to add configuration to Django and/or just on this specific issue would make a lot of sense.

Seems to be the same as this issue https://github.com/readthedocs/readthedocs.org/issues/4791
I realize that you can just mute the warning in sentry, but weblate would still send me an email.

**Comment by nijel** [comment]
The docs was already there, I've slightly improved it: https://docs.weblate.org/en/latest/admin/install.html#production-hosts

**Comment by JulianGro** [comment]
@nijel while this does tell you how to configure which hosts are allowed, it does not tell you how to mute the warning. Of course you can just allow any host, but according to the Django documentation this is a security risk.

My problem is that I get an email and a sentry notification every time someone searches for a security hole using a disallowed host. Which happens quite a lot. Currently we are on 41 events of this happening, after just 8 days.

**Comment by nijel** [comment]
Either configure web server to pass only certain hosts to Weblate wsgi or configure Weblate to accept any hosts. I don't see need for describing other option. In case you really want it, solution from https://github.com/readthedocs/readthedocs.org/pull/4879 will probably work...

**Comment by JulianGro** [comment]
@nijel the problem is that the webserver comes with the weblate docker container. There doesn't appear to be any documentation about where that webserver is, how to give configuration parameters to it, or even what webserver it is.
I feel like for something that should be done in every production setup like this there should be a documentation entry.

**Comment by nijel** [comment]
Okay, in this case it probably should be rather fixed in the Docker container, I've created https://github.com/WeblateOrg/docker/issues/733 to track this.

**Comment by zymotik** [comment]
In my case, on a server that only hosts weblate, I used this method to return a 403 when using anything but the configured domain/sub-domain name:

Generate an ssl cert to hide the domain of the server in use:

`openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/ssl-cert/no-domain.com/privkey.pem -out /etc/ssl-cert/no-domain.com/fullchain.pem -subj "/CN=no-domain.com"`

Edited the `nginx` default site config (/etc/nginx/sites-available/default) and added at the end:

```
# block unknown
server {
    listen 80 default_server;
    listen 443 ssl default_server;
    server_name _;

    ssl_certificate /etc/ssl-cert/no-domain.com/fullchain.pem;
    ssl_certificate_key /etc/ssl-cert/no-domain.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 403;
}
```

Notice I am using certbot/LetsEncrypt for my config, so I copied that. It may not be necessary in your case.
