### ISSUE TITLE
Adding translation strings for iOS in Weblate fails for the 1st commit

### ISSUE THREAD

**Issue by AJOCHAM** [WeblateOrg/weblate#4151]
Everytime we add a new translation string in Weblate via Web-GUI the iOS string is without quotes.

`drawer_collect_enroll_i=Select what you want`
**but it should be**
`"drawer_collect_enroll_i"="Select what you want"`

If I edit the string and commit again, everything is fine

**To Reproduce**

1. Add a new string via WebGui for an iOS String component
2. Commit & push
3. the resulting file is wrong

**Weblate list_versions**

 * Weblate: 4.0.3
 * Django: 3.0.5
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.1
 * lxml: 4.3.2
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.9.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.1
 * celery: 4.4.2
 * kombu: 4.6.8
 * translation-finder: 2.0
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.23.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.3
 * Cython: 0.29.17
 * misaka: 2.1.1
 * GitPython: 3.1.1
 * borgbackup: 1.1.11
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.7.7
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.13.1
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * Mercurial: 5.4
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: webmail.loyaltypartner.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.15.0-45-generic (x86_64)

**Comment by AJOCHAM** [comment]
i applied this changes to my ttkit-py in Weblate: 4.0.3 and it looks good.
Thx a lot for your fast solution

**Comment by asiboro** [comment]
I am using version 4.3.2 and it still happens. I uploaded translation files as Zip.

**Comment by nijel** [comment]
@asiboro Maybe https://github.com/WeblateOrg/weblate/issues/5144?

**Comment by asiboro** [comment]
> @asiboro Maybe #5144?

@nijel Thanks. I think you are right. I googled and was brought to this one.
