### ISSUE TITLE
Support creating local VCS components using API

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#4156]
**Is your feature request related to a problem? Please describe.**
The component creation API right now supports only creating components from remote VCS. It should also support no remote VCS setup where initial file is either created by Weblate or provided by upload.

In other words, it should support following workflows supported in the UI:

* [ ] Upload translations files - upload more files in a ZIP
* [ ] Translate document - upload main file
* [ ] Start from scratch - no file provided, starts with blank one

**Describe the solution you'd like**
Extend https://docs.weblate.org/en/latest/api.html#post--api-projects-(string-project)-components- to support local vcs.

**Describe alternatives you've considered**
Right now, this is not supported over API, but I don't think it's a viable approach.

**Additional context**
The related code is currently placed in the view, but should be shared for the API, not sure if it makes sense to move it to the models.

For example, creating component from scratch si here:

https://github.com/WeblateOrg/weblate/blob/93991891060a6eb02d8961edaf3f5aea853c7cc6/weblate/trans/views/create.py#L54-L72

**Comment by nijel** [comment]
I've just implemented basics start from scratch in d9bfab2e0dfaef9fe62cd4c5ffb852558c6c8dd2

**Comment by EpocDotFr** [comment]
Thank you!
