### ISSUE TITLE
JSON  Serialization problems

### ISSUE THREAD

**Issue by abbudao** [WeblateOrg/weblate#4159]
**Describe the bug**
JSON serialization breaks arrays containing objects. I've seen some JSON serialization issues, but I have not seen any reporting this particular case. 

Source file:
```json
{
    "values": [
        {
            "heading": " ",
            "description": " ",
            "icon": " "
        },
        {
            "heading": " ",
            "description":  " ",
            "icon": " "
        },
 ]
}
```

Weblate is serializing (either I18next  or JSON nested):
```json
{
 "values": [
        {
            "heading": " "
        },
        {
            "description": " "
        },
        {
            "icon": " "
        },
        {
            "heading": " "
        },
        {
            "description": "  "
        },
        {
            "icon": " "
        }
    ]
}
```

**To Reproduce**

1. Create a component with i18next as source
2. Upload a file with the above example
3. Commit any changes 
4. Push to repository

**Expected behavior**
I expected Weblate to keep the same file structure after and before changes. 

**Additional context**
Let me know if I can be of any help. I am not familiar with Weblate codebase but if there is something that is blocking this and needs to be done ([as there is a PR from 2018](https://github.com/translate/translate/pull/3835)), I can help, if some guidance is given.

**Comment by nijel** [comment]
This particular issue has been fixed by https://github.com/translate/translate/pull/4071, it's not yet released in the translate-toolkit.

**Comment by abbudao** [comment]
Hey @nijel, thank you for your reply!
I'm not familiar with how translate-toolkit relates to Weblate. Can I do anything to help see this fix merged on Master?

**Comment by nijel** [comment]
The fix is merged on translate-toolkit master branch, it is just not released. You can install it using `pip install https://github.com/translate/translate/archive/master.zip`
