### ISSUE TITLE
Document translation

### ISSUE THREAD

**Issue by howiezhao** [WeblateOrg/weblate#4163]
**Is your feature request related to a problem? Please describe.**
This document is comprehensive. Are there plans to translate it into other languages? I can help translate it into Chinese.

**Describe the solution you'd like**
It seems that it can be done using `sphinx-intl`.

**Describe alternatives you've considered**
No.

**Additional context**
https://www.sphinx-doc.org/en/master/usage/advanced/intl.html

**Comment by nijel** [comment]
Duplicate of #3344
