### ISSUE TITLE
Broken link to Weblate Docs' source string location

### ISSUE THREAD

**Issue by rffontenelle** [WeblateOrg/weblate#4164]
**Describe the bug**

The source string location of Weblate Docs gives broken link, leading to GitHub's 404 Not Found page.  It looks like "blobs/master/docs" are missing from the URL.

**To Reproduce**

1. Go to a string in [Weblate/Documentation](https://hosted.weblate.org/translate/weblate/documentation/en/)
2. Click on source link; e.g. "[../../admin/access.rst:4](https://github.com/WeblateOrg/weblate/admin/access.rst#L4)"
3. You will be directed to https://github.com/WeblateOrg/weblate/admin/access.rst#L4
4. See 404 Not Found page
5. Now browse the link https://github.com/WeblateOrg/weblate/blob/master/docs/admin/access.rst#L4

**Expected behavior**

A working link.

**Screenshots**

Not needed ?

**Server configuration and status**

Hosted Weblate, looking good

**Weblate deploy checks**

not applicable

**Exception traceback**

not applicable

**Additional context**

**Comment by nijel** [comment]
Thanks for pointing out, I forgot to configure this.
