### ISSUE TITLE
Android translatable field ignored

### ISSUE THREAD

**Issue by arkon** [WeblateOrg/weblate#4171]
**Describe the bug**

Duplicate of #325, which we're still seeing.

**To Reproduce**

We're seeing this in the [Tachiyomi project](https://hosted.weblate.org/projects/tachiyomi), particularly with [this string](https://github.com/inorichi/tachiyomi/blob/dev/app/src/main/res/values/strings.xml#L372).

**Expected behavior**

Any string marked with `translatable="false"` should not be translatable in Weblate.

**Screenshots**

N/A

**Server configuration and status**

N/A, using hosted Weblate.

**Weblate deploy checks**

N/A, using hosted Weblate.

**Exception traceback**

N/A

**Additional context**

N/A

**Comment by nijel** [comment]
I believe it should be fixed by https://github.com/WeblateOrg/weblate/commit/26118c454a293b41e358fa5f92094566e36effde and https://github.com/WeblateOrg/weblate/commit/badbeed69f5dcdd491a9d8487f672dae465e9686. I've just forced reloading the translations on Weblate side and it indeed did fix this.
