### ISSUE TITLE
Table view

### ISSUE THREAD

**Issue by AJOCHAM** [WeblateOrg/weblate#4175]
For the management of our strings we used a google spreadsheet, where a tool created all the needed filed for our Android and iOS APP.
Now with Weblate we benefit from a lot of new features to improve the string quality. 

But our PO´s still like the overview about a group of strings in all languages. 
So is the a option so show all strings per project/component in a table view (editing possible)

i.e.

Key | Language1 | Language2 | Language3 | Language4 | Languagex
------------ | ------------- | ------------ | ------------ | ------------ | ------------
myKey1 | string1.1 | string1.2 | string1.3 | string1.4 | string1.x
myKey2 | string2.1 | string2.2 | string2.3 | string2.4 | string2.x

**Comment by nijel** [comment]
There already is matrix view: https://hosted.weblate.org/matrix/weblate/application/?lang=cs&lang=de
