### ISSUE TITLE
Backup error - weblate.C029 - Failed to create/acquire the lock /app/data/home/.cache/borg/***/lock.exclusive (timeout).

### ISSUE THREAD

**Issue by Koubek** [WeblateOrg/weblate#4176]
**Describe the bug**

Problems with backups against the borg backup endpoint hosted by weblate.org. Backup always terminates with the following error message:
```
Failed to create/acquire the lock /app/data/home/.cache/borg/1a5a60ea6b525416828ef87554c313290c200d200e972d1fb154b6aa64ec7dbb/lock.exclusive (timeout).
```

**To Reproduce**

I don't know how to repro the bug as the backups had been running correctly since we got and applied the token (maybe two weeks ago) until the day 13th of July. This was the first day we registered the issue and it continues since then.

It happens during both, automated backups but also during the backup triggered manually.

**Expected behavior**

Successful backup :)

**Server configuration and status**

We run weblate as a Docker Stack (Docker Swarm).

```
 * Weblate: 4.1.1
 * Django: 3.0.8
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0
 * lxml: 4.5.1
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.4.0
 * django-crispy-forms: 1.9.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.1
 * celery: 4.4.6
 * kombu: 4.6.11
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.0.1
 * sentry_sdk: 0.15.1
 * Cython: 0.29.20
 * misaka: 2.1.1
 * GitPython: 3.1.3
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.5
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.14.14
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 1.4.6
 * Mercurial: 5.4.2
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * hub: 2.13.0
 * lab: 0.16
 * Redis server: 5.0.9
 * PostgreSQL server: 11.8
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.0.0-1029-azure (x86_64)
```

**Weblate deploy checks**

```
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.C029) There was error while performing backups: Failed to create/acquire the lock /app/data/home/.cache/borg/1a5a60ea6b525416828ef87554c313290c200d200e972d1fb154b6aa64ec7dbb/lock.exclusive (timeout).

        HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/backup.html
```

**Comment by nijel** [comment]
Maybe there is some backup process stuck running? Can you check running processes if there is any borg process left? (It should not be there as backups should be executed from single process in normal configuration)

**Comment by Koubek** [comment]
OK, I will but I restarted completely the entire weblate stack once I saw the error message. The restart didn't help.

**Comment by Koubek** [comment]
Confirmed, there is no running borg process. I can understand (maybe incorrectly - sorry, I am not a linux guy), the backup is being triggered as a celery task.

**Comment by Koubek** [comment]
Please, could I provide any additional info that is currently missing? I am a bit afraid that we are without daily backups (despite the fact we currently don't provide any changes to the translation db). Or should I instead of the paid service start using our own solution?

**Comment by nijel** [comment]
This should not be reason for the paid service, but you are always welcome to use hosted solution or commercial support for your installation :-).

Can you try looking which process holds the lock? `fuser -v  /app/data/home/.cache/borg/1a5a60ea6b525416828ef87554c313290c200d200e972d1fb154b6aa64ec7dbb/lock.exclusive` should tell that.

**Comment by nijel** [comment]
And one more question: What filesystem is used on `/app/data`? Maybe it has some issues with locking...

**Comment by Koubek** [comment]
```
Cannot stat file /proc/1/fd/0: Permission denied
Cannot stat file /proc/1/fd/1: Permission denied
Cannot stat file /proc/1/fd/2: Permission denied
Cannot stat file /proc/1/fd/3: Permission denied
Cannot stat file /proc/1/fd/4: Permission denied
Cannot stat file /proc/1/fd/6: Permission denied
Cannot stat file /proc/1/fd/7: Permission denied
Cannot stat file /proc/1/fd/8: Permission denied
Cannot stat file /proc/1/fd/9: Permission denied
Cannot stat file /proc/1/fd/10: Permission denied
Cannot stat file /proc/1/fd/11: Permission denied
Cannot stat file /proc/1/fd/12: Permission denied
Cannot stat file /proc/1/fd/13: Permission denied
Cannot stat file /proc/1/fd/14: Permission denied
Cannot stat file /proc/1/fd/15: Permission denied
Cannot stat file /proc/1/fd/16: Permission denied
Cannot stat file /proc/1/fd/17: Permission denied
Cannot stat file /proc/1/fd/18: Permission denied
Cannot stat file /proc/1/fd/19: Permission denied
Cannot stat file /proc/1/fd/20: Permission denied
Cannot stat file /proc/1/fd/21: Permission denied
Cannot stat file /proc/1/fd/22: Permission denied
Cannot stat file /proc/1/fd/23: Permission denied
Cannot stat file /proc/1/fd/24: Permission denied
Cannot stat file /proc/1/fd/25: Permission denied
Cannot stat file /proc/1/fd/26: Permission denied
Cannot stat file /proc/1/fd/27: Permission denied
Cannot stat file /proc/1/fd/28: Permission denied
Cannot stat file /proc/1/fd/29: Permission denied
Cannot stat file /proc/1/fd/30: Permission denied
Cannot stat file /proc/1/fd/31: Permission denied
Cannot stat file /proc/1/fd/32: Permission denied
Cannot stat file /proc/1/fd/33: Permission denied
Cannot stat file /proc/1/fd/34: Permission denied
Cannot stat file /proc/1/fd/35: Permission denied
Cannot stat file /proc/1/fd/36: Permission denied
Cannot stat file /proc/1/fd/37: Permission denied
Cannot stat file /proc/1/fd/39: Permission denied
Cannot stat file /proc/1/fd/41: Permission denied
Cannot stat file /proc/1/fd/42: Permission denied
Cannot stat file /proc/1/fd/43: Permission denied
Cannot stat file /proc/1/fd/45: Permission denied
Cannot stat file /proc/1/fd/48: Permission denied
Cannot stat file /proc/1/fd/49: Permission denied
Cannot stat file /proc/1/fd/50: Permission denied
Cannot stat file /proc/1/fd/51: Permission denied
Cannot stat file /proc/1/fd/52: Permission denied
Cannot stat file /proc/1/fd/54: Permission denied
Cannot stat file /proc/1/fd/56: Permission denied
Cannot stat file /proc/1/fd/57: Permission denied
```

```/app/data``` is a mounted volume. It uses **ext4** file system.

**Comment by Koubek** [comment]
Btw, I have restarted the entire host (docker swarm node) and without any positive effect.

**Comment by nijel** [comment]
Reading https://github.com/borgbackup/borg/issues/3191 and related issues, it seems that this can happen in some situations when borg can not reliably detect it can safely remove the stale lock.

What might help is:

```
HOME=/app/data/home borg break-lock path_to_your_backup_repo
````

See also https://borgbackup.readthedocs.io/en/stable/usage/lock.html#borg-break-lock

**Comment by Koubek** [comment]
Thanks a lot, I will try it. Actually, I saw it when I hit the problem and I was considering this might really help. But as I really don't have very strong experience with Borg backup I decided to rais my hand here and ask.

I believe ```path_to_your_backup_repo``` is the remote URI I can see in Weblate and starting with ```Backup service: ssh:```.

**Comment by nijel** [comment]
Yes, that's it.

**Comment by Koubek** [comment]
Hello @nijel, sorry for coming so late but I was away for a week. I have tried the trick you recommended but I am always ending up with the following:
```
***@***.your-storagebox.de's password: Remote: Permission denied, please try again.
***@***.your-storagebox.de's password: Remote: Permission denied, please try again.
Remote: ***@***.your-storagebox.de: Permission denied (publickey,password).
```

I am using the passphrase seen in the backup panel.

**Comment by nijel** [comment]
Are you executing it with HOME as written in https://github.com/WeblateOrg/weblate/issues/4176#issuecomment-660493811. It is not supposed to ask for as password, it should use keys to authenticate.

**Comment by Koubek** [comment]
Sorry, I have spent next time with this but no success. I removed everything (accidentally the volume with the local data too) and I need to figure out how to proceed with full data recovery and get everything back.

**Comment by nijel** [comment]
The basic instructions for that are in the docs: https://docs.weblate.org/en/latest/admin/backup.html#restoring-from-borgbackup

**Comment by Koubek** [comment]
But is it safe (and possible at all) to enable again backups for a brand new installation using the same activation token? What I am the most afraid of it will be possible but it will overwrite backups with new (empty) installation (almost empty db).

Btw, I have been trying to connect to the remote repo (borg list REMOTEREPO) from another host (that had borg installed on) and I wasn't successful. Probably I do something wrong with the private key but I am not sure.

**Comment by Koubek** [comment]
I have advanced a bit but now getting:
```Load key "/[some_path]/id_rsa": invalid format```

This is the key I downloaded after the backup system was activated using the activation token. The file was stored on a secure placed and now uploaded and used. The file hasn't been altered.

**Comment by Koubek** [comment]
OK, I think I am able to see the remote repo and the files now. My mistake I uploaded the key in the wrong way before.

**Comment by Koubek** [comment]
OK, I have recovered the backup but now struggling with 5) and maybe also 4) from:
https://docs.weblate.org/en/latest/admin/backup.html#restoring-from-borgbackup

**Comment by Koubek** [comment]
I believe I have been able to recover now the db and set the entire stack again (I did have the stack definition - I am just pointing now to a new database). And weblate is back and running. I am curious to see if the backup is running now properly or not.

**Comment by nijel** [comment]
> But is it safe (and possible at all) to enable again backups for a brand new installation using the same activation token? 

Yes, the backups are incremental and some of the old ones are being pruned (it keeps 7 daily, 4 weekly and 6 monthly).

I've now clarified the docs to cover this and be more detailed in restoring docs.

**Comment by Koubek** [comment]
Closing this issue as we move to another problem and this isn't required anymore. Thanks for your help.
