### ISSUE TITLE
Autotranslate addon: remove the undocumented "run only once a week" condition

### ISSUE THREAD

**Issue by mbarta** [WeblateOrg/weblate#4179]
**Describe the bug**

The autotranslate addon is only triggered at a random day in a week per component, even though the job seems to be intended to be run "on push" and "daily" judging by the code structure of the addon.

The documentation or settings of the addon don't mention this limitation anywhere, so it's quite impossible to find out why the autotranslation isn't triggered without studying the [source code](https://github.com/WeblateOrg/weblate/blob/master/weblate/addons/autotranslate.py).

**To Reproduce**

1. Set up Autotranslate addon for your project
2. Push changes to repository (on one of the six random days)
3. Check the status of translations
4. See the autotranslator addon didn't start

**Expected behavior**

The addon should start upon the push event and/or daily. A configuration option for changing the behaviour might be useful too.

**Screenshots**

N/A

**Server configuration and status**

```
 * Weblate: 4.1.1
 * Django: 3.0.8
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0
 * lxml: 4.5.1
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.4.0
 * django-crispy-forms: 1.9.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.1
 * celery: 4.4.6
 * kombu: 4.6.11
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.0.1
 * sentry_sdk: 0.15.1
 * Cython: 0.29.20
 * misaka: 2.1.1
 * GitPython: 3.1.3
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.5
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.14.14
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 1.4.6
 * Mercurial: 5.4.2
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * hub: 2.13.0
 * lab: 0.16
 * Redis server: 5.0.9
 * PostgreSQL server: 11.8
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.gmail.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.4.0-40-generic (x86_64)
```

**Weblate deploy checks**

```
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/backup.html

System check identified 2 issues (1 silenced).
```

**Comment by nijel** [comment]
Yes, the addon is currently executed once a week for every component:

https://github.com/WeblateOrg/weblate/blob/9356e06f5be702d5922bd2d73ebf56a37533a121/weblate/addons/autotranslate.py#L47-L49

The problem is that on installations with thousands of components it is not practical to run it on all components every day and this distributes the load. It might be configurable though as this is not a concern for most users.

**Comment by nijel** [comment]
Similar logic is applied on background checks update, but that is triggered once in a month:

https://github.com/WeblateOrg/weblate/blob/9356e06f5be702d5922bd2d73ebf56a37533a121/weblate/trans/tasks.py#L391-L394
