### ISSUE TITLE
Possibility to disable "Long untranslated" check

### ISSUE THREAD

**Issue by Kyuuu** [WeblateOrg/weblate#4181]
**Is your feature request related to a problem? Please describe.**
https://docs.weblate.org/en/weblate-4.1.1/user/checks.html#check-long-untranslated
This check has no use and is only annoying, cause for what is for? Some strings just were translated/added a long time ago and everything is fine with them.

**Describe the solution you'd like**
Possibility to disable this test at all (somewhere in options or wherever). I cannot clean my checks' list from it and it's triggering 😢

**Describe alternatives you've considered**
//

**Additional context**
//

**Comment by nijel** [comment]
You can disable it on component level using `ignore-long-untranslated` flag or you can remove it from [CHECK_LIST](https://docs.weblate.org/en/weblate-4.1.1/admin/config.html#std-setting-CHECK_LIST) to disable int completely.

**Comment by nijel** [comment]
Oops, it turns out there is a bug in the check making it fire pretty much on all old strings, not only on those translated beyond component average...
