### ISSUE TITLE
Internal Server Error when changing project source language 

### ISSUE THREAD

**Issue by p3kj** [WeblateOrg/weblate#4184]
Internal Server Error when changing project source language from English to English(developer).

We have constant alert in Weblate, that we have Duplicated translation, so we want to switch English to English (developer) to avoid the alert. We use English translation to fix minor typos.

Project have several components, one is bound to ssh git repo, others are using shared weblate repo.

Weblate version: 4.1.1 (docker)
Recently updated from 3.11 -> 4.0.4 -> 4.1.1

Email Trace log attached.

[[Weblate] ERROR (EXTERNAL IP) Internal Server Error _admin_trans_project_1_change_.zip](https://github.com/WeblateOrg/weblate/files/4924682/Weblate.ERROR.EXTERNAL.IP.Internal.Server.Error._admin_trans_project_1_change_.zip)

**Comment by nijel** [comment]
Already fixed by 78f2b90d70172576f7e4592400ffa5ca4c577938 (and further improved by 66c24b09bb780d4acc55fed1d91346d2aa9cfb36).
