### ISSUE TITLE
Widgets fot translation status

### ISSUE THREAD

**Issue by milotype** [WeblateOrg/weblate#4187]
**Describe the bug**
The description for _vertical_ and _horizontal_ widgets are quite confusing IMO. The strings in question are:

- `Vertical multi language status widget` (weblate/locale/hr/LC_MESSAGES/django.po, string 2223)
- `Horizontal multi language status widget` (weblate/locale/hr/LC_MESSAGES/django.po, string 2224)

**To Reproduce**
Please take a look at the attached screenshots.

**Expected behavior**
I would expect it to be the other way around at least. I do understand the logic behind it, but _visually_ it makes no sense.

**Screenshots**

- **VERTICAL WIDGET**
![vertical](https://user-images.githubusercontent.com/43657314/87582529-cfd16c00-c6da-11ea-8842-e3c146671b97.png)

- **HORIZONTAL WIDGET**
![horizontal](https://user-images.githubusercontent.com/43657314/87582567-d8c23d80-c6da-11ea-81cd-ff12c87e5546.png)

**Solution**
My suggestion is actually to drop the `Horizontal multi language status widget` altogether. I don't see a need/advantage in that kind of presentation – especially as it does not take into account scripts, that may be written vertically or RTL.

**Comment by milotype** [comment]
@nijel Thank you. Yes, I'm aware that the names indicate the direction of listing. I just find the wording _horizontal/vertical_ confusing. Maybe the following could be used:

- `Multi language status widget, rows`
- `Multi language status widget, columns`

Anyway, it's just a thought. If you don't like it, that's fine.

**Comment by nijel** [comment]
I'd love to see better names for those, but dropping one of them is definitely not an option.

Maybe @comradekingu or @orangesunny will have some though on naming of these widgets?

**Comment by comradekingu** [comment]
Vertical translation status widget
Horizontal translation status widget

or

Vertical language bar chart
Horizontal language bar chart

https://en.wikipedia.org/wiki/Bar_chart

Vertical/horizontal is correct. The need for the latter arises when you have amount of entries scaling beyond the length of text.

**Comment by milotype** [comment]
**bar chart** sound good – better than widget, because the others are widgets as well. So there would be three sorts of widgets: badge, bar chart and image

**Comment by comradekingu** [comment]
"Image" isn't very descriptive. How about "panel"?

**Comment by nijel** [comment]
Technically, it's an image suitable as Open Graph image, but panel might be better name here.

**Comment by milotype** [comment]
Yes, the technical usage is clear ... **Panel** is (IMO) definitely better!

**Comment by orangesunny** [comment]
Giving one more 👍  for `panel`
