### ISSUE TITLE
weblate.C023 - System encoding is not UTF-8

### ISSUE THREAD

**Issue by zmartyz** [WeblateOrg/weblate#4195]
Good evening,

After upgrade Weblate 3.9.1 to 4.1.1, weblate still showing this error: "System encoding is not UTF-8, processing non-ASCII"

It is running from Centos8.2 and the system locale is set to en_US.utf8. I tried different *.utf8 langpacks, but nothing seems to work. 
![weblate-utf8-02](https://user-images.githubusercontent.com/61587582/87858162-36999400-c92c-11ea-89fb-eb69669c5db8.png)
![weblate-utf8-01](https://user-images.githubusercontent.com/61587582/87858163-37322a80-c92c-11ea-8ede-1dbc4fb88f9c.png)

Do you have any suggestions ?

Thank you

**Comment by nijel** [comment]
Maybe your wsgi environment is different? How do you run that?
