### ISSUE TITLE
translations/.../file api does not allow "method"="source" (403 resp) despite test user having all possible permissions.

### ISSUE THREAD

**Issue by iBurnette** [WeblateOrg/weblate#4199]
**I see that my weblate is out of date, so I will download and give it another shot tomorrow. I'm not convinced that this is a bug though, so I'm going to post this anyways in the meantime. **

**Describe the issue**

I have created a user with every default role/group as well as a custom group with every possible permission, but when I try to add a source string by uploading a bilingual po file through the API I get a 403 permissions error.

**To Reproduce**

1. Create a new project, component, and translation as well as a user with all permissions
2. Post a bilingual po file to [the translation/.../file endpoint](https://docs.weblate.org/en/weblate-4.1/api.html#get--api-translations-(string-project)-(string-component)-(string-language)-file-) with "method"="source". Make sure to use the api key for the appropriate user.
3. Receive a 403 error.
4. Changing the method to "replace" will cause the po file to be applied to the translation, but it will also overwrite any existing source strings.

**Expected behavior**

You will receive a 403 HTTP response with the payload `'{"detail":"You do not have permission to perform this action."}'`

**Screenshots**

**Server configuration and status**
```

System check identified some issues:

INFOS:
?: (weblate.I031) New Weblate version is available, please upgrade to 4.1.1.
	HINT: https://docs.weblate.org/en/weblate-4.0.4/admin/upgrade.html
 * Weblate: 4.0.4
 * Django: 3.0.6
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.1
 * lxml: 4.3.2
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.9.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.1
 * celery: 4.4.2
 * kombu: 4.6.8
 * translation-finder: 2.0
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.23.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.3
 * Cython: 0.29.17
 * misaka: 2.1.1
 * GitPython: 3.1.2
 * borgbackup: 1.1.11
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.7.7
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.13.4
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * Mercurial: 5.4
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * hub: 2.13.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.example.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.6.15-arch1-1 (x86_64)

```
**Weblate deploy checks**

```
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail ([Errno -2] Name or service not known), please check EMAIL_* settings.
	HINT: https://docs.weblate.org/en/weblate-4.0.4/admin/install.html#out-mail

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.0.4/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.0.4/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 4.1.1.
	HINT: https://docs.weblate.org/en/weblate-4.0.4/admin/upgrade.html
```

**Comment by nijel** [comment]
The method source was added in 4.1, see #3263. Also it supports only bilingual translations, on monolingual `replace` should work just fine in this case.

**Comment by blackfedora** [comment]
Hi @nijel,
I've updated weblate to 4.1.1 and added literally every permission to the power-user. I've double checked that the admin user I'm using to post things to the api is in the User group and that the User group has the power-user role (this is all just local for testing, I understand how bad an idea this authentication set up would be).

The component is configured to use the gettext PO file format (NOT the monolingual option). The translation has been created. 

I'm still getting a 403 response when I try to update the translation using method=source. 

This is the po file I'm using:

```
#: string_a
msgid "String A"
msgstr "This is string 'A'"
```
Would weblate interpret that as a monolingual file even though the component is configured to use bilingual gettext?

**Comment by nijel** [comment]
The upload has to happen on the source language as well, maybe that's the problem?

**Comment by blackfedora** [comment]
@nijel Ok that was the problem, changing the target language to english caused the upload to go through.

I noticed that all of the existing source strings were replaced-- is "source" equivalent to "replace" but it's restricted to the source language?

Is there any documentation for the "method" attribute options I could read? 

We have a collection of bilingual po files that we want to migrate to weblate. Some languages have multiple po files, which is why I can't just use a single method="replace" for each translation. Furthermore, not all of the source strings are present in each po file, so it's very important that migrating a single translation won't remove any source strings which have been migrated into weblate.

**Comment by nijel** [comment]
The documentation is here: https://docs.weblate.org/en/latest/user/files.html#import-methods (it is missing names used in the API, I will add that)

**Comment by blackfedora** [comment]
Thanks for the help so far @nijel!

Unfortunately, I still haven't been able to accomplish what we're trying to do. 

Say you have these two bilingual po files:

numbers_nl.po
```
#: 1
msgid "one"
msgstr "een"
```

greetings_nl.po
```
#: hello
msgid "hello"
msgstr "hoi"
```

When trying to upload these files into weblate I have not found a way such that both strings are present in the final translation. If I upload them using any method other than "replace" the strings are detected, but ignored because the source strings are not present. However, if I use replace obviously only one of the strings is present after the upload as the new translation overrides the old one.

I also tried to upload these files as english sources (using method=source targeting english). Unfortunately this caused the same issues as using replace-- uploading a new source file completely deletes existing translations if a source string isn't contained in the new file.

**Comment by nijel** [comment]
There is currently no way to achieve that, you need to merge the files before the update and then use replace (for single translation update) or source upload (to update all translations, but you probably want to have msgstr empty in this case).

**Comment by lokha** [comment]
@blackfedora 
hi i have the same problem  
how did you solve this problem?

i also want to update original strings via api but replace method replaces whole language file

and if you send all strings for updates, then this will cause their bulk processing and weblate will experience the load

**Comment by blackfedora** [comment]
@lokha 
For bulk uploads, we're using the workflow described above (downloading and merging the two files ourselves).

For single translations we add the source string via [this endpoint](https://docs.weblate.org/en/latest/api.html#post--api-translations-(string-project)-(string-component)-(string-language)-units-), and then patching the translation units through the [units endpoint](https://docs.weblate.org/en/latest/api.html#patch--api-units-(int-id)-).
