### ISSUE TITLE
Machine translation question

### ISSUE THREAD

**Issue by FransMeerhoff** [WeblateOrg/weblate#4204]
**Describe the issue**

Dear Support,

Built-in support for several machine translation services and can be turned on by the administrator using MT_SERVICES for each one.

Is this possible for all type of licenses?
If so, how and where can you you set the MT_SERVICES configuration setting?

Kind regards 
Frans Meerhoff

**Comment by nijel** [comment]
That's done in the settings.py, see https://docs.weblate.org/en/latest/admin/config.html#mt-services and https://docs.weblate.org/en/latest/admin/install.html#adjusting-configuration
