### ISSUE TITLE
Improved activity

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#4206]
Weblate display activity stats in #activity tabs.
it exists for:

- a project: https://translate.fedoraproject.org/projects/languages-in-floss/#activity
- a language: https://translate.fedoraproject.org/languages/fr/#activity
- a platform: https://translate.fedoraproject.org/#activity

The issues I see is that isn't informative enough and no navigation is made possible from one level to another (project/language/platform).

To make it more informative:

- Restore the numbering on left hand-side (lost in 4.2 ?)
- Restore the value on mouse over (lost in 3.x ?)
- Use calendar months instead of weeks
- Display the action displayed and allow to select one or many actions, the same way we can select one or many actions in https://translate.fedoraproject.org/changes/

To allow interaction:

- When clicking on a bar, I would like to be able to see: the same KPI distributed per project (top 10) and per language (top 10). Hyperlinks allowing to jump to the project or language that interests me.

Now that I wrote this, I feel like I would like to have the same ability to interact with history stats that the one I have with #history.

thanks a lot for this great tool

**Comment by nijel** [comment]
The activity charts were simplified for 4.2 release, see https://hosted.weblate.org/projects/weblate/#activity

It was never meant to be a detailed reporting tool, but rather a quick overview of project activity. It might be extended in the future, but I don't see this as a priority.
