### ISSUE TITLE
How to approve 300 reviews with one click?

### ISSUE THREAD

**Issue by Littlegolden** [WeblateOrg/weblate#4209]
There are more than three hundred reviews, but I didn't find any one-click button from the pannel, does this feature exist?

Now I have to click "approved" 300 times to complete all reviews.

![image](https://user-images.githubusercontent.com/35162802/88272453-51448200-cd0b-11ea-896d-ffc41f67b813.png)

**Comment by nijel** [comment]
You can use Bulk edit for that.

**Comment by Littlegolden** [comment]
Thanks for the prompt reply. But I don’t see any button for Bulk edit under Zen mode. By the way, I'm usding Weblate 3.9.1.

**Comment by Littlegolden** [comment]
Thank you so much!
