### ISSUE TITLE
Unify the usage of decimal/thousands separators

### ISSUE THREAD

**Issue by milotype** [WeblateOrg/weblate#4212]
**Describe the bug**

- Decimal/thousands separators are not used uniformly on the pages mentioned below.
- In most other cases (website/Hosted Weblapte pages), the separators seem to be used appropriately

**To Reproduce**
1. Go to https://weblate.org/en/ (or check 1st screenshot)
2. Go to https://hosted.weblate.org/create/billing/?upgrade=1 (or check 2nd screenshot)

**Expected behavior**
All instances of numbers should be handled equaly, with decimal/thousands spearator

**Screenshots**

- ![DecimalSeparator](https://user-images.githubusercontent.com/43657314/88302568-49361380-cd06-11ea-9d66-e3d3e6e36087.png)
---
- ![BillingPlans](https://user-images.githubusercontent.com/43657314/88304931-2eb16980-cd09-11ea-9190-99b19da600f1.png)

**Comment by nijel** [comment]
Thanks for pointing out! Originally, this has not been used at all. It was introduced recently to most of the website, but we've apparently missed few places...
