### ISSUE TITLE
Celery queue `celery` looks like always stop work after few days...

### ISSUE THREAD

**Issue by zslucky** [WeblateOrg/weblate#4214]
**Describe the bug**

Celery queue `celery` looks like always stop working after few days... every time I restart the service, it can run for some days.

weblate will show alert, `Celery looks like too slow`, after `celery` collect many tasks, it also alert me `Celery looks like stop work`

**To Reproduce**

Hard to describe the reproduce steps, just I have some projects and many components.

**Expected behavior**

Celery should work correctly.

**Server configuration and status**
* Weblate: 4.2-dev
 * Django: 3.0.8
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0
 * lxml: 4.5.2
 * Pillow: 7.2.0
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.1
 * celery: 4.4.6
 * kombu: 4.6.11
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.0.1
 * sentry_sdk: 0.16.1
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.3
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.5
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.14.20
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.1
 * Mercurial: 5.4.2
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * hub: 2.13.0
 * lab: 0.16
 * Redis server: 4.0.14
 * PostgreSQL server: 11.8
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.gmail.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.14.143-118.123.amzn2.x86_64 (x86_64)

**Weblate deploy checks**

Only a piece of backup configuration info.

**Additional context**

I'm using docker-compose, I'm not sure is it related to celery configuration, I want to increase celery concurrency number, but looks like no documents let to configure celery in docker-compose file?

**Comment by nijel** [comment]
Do you get any errors in the logs? Is it still receiving tasks?

> I want to increase celery concurrency number, but looks like no documents let to configure celery in docker-compose file?

Recently, a pull request implementing this has been merged, see https://github.com/WeblateOrg/docker/pull/745

**Comment by zslucky** [comment]
I will provide all the relation logs later
