### ISSUE TITLE
Add syntax highlight and quick actions for reStructuredText markup constructs

### ISSUE THREAD

**Issue by Mingun** [WeblateOrg/weblate#4218]
At least it should highlight roles and the ability to insert these parts unchanged by `Alt+<number>` (like is it done for XML or HTML tags or format placeholders).

In the simplest case reStructuredText role looks like this:
```rst
:role_name:`role text`
or
`role text`:role_name:
```
Also special cases:
```rst
*emphasis*, **strong emphasis**, `interpreted text` or ``inline literal``
`hyperlink reference`_ or `anonymus hyperlink reference`__, also with `alias <aliased>`_
[#footnote]_, also [#]_, or [*]_, or [2]_, or [CITATION]_
```
Also it is good to support roles from Sphinx, many of which look like this:
```rst
:ref:`Optional title <some_identifier>`
:py:class:`ClassName`
:py:meth:`~Queue.Queue.get`
```
Ideally, this markup should also not change with machine translation, but I don't know if this is possible in principle.

**Additional info:**

- [reStructuredText Markup Specification](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html).
- [reStructuredText Interpreted Text Roles](https://docutils.sourceforge.io/docs/ref/rst/roles.html).
- [Standard Sphinx roles](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html).

**Comment by nijel** [comment]
The check (and thus placeables) could be implemented for existing`rst-text` flag.

Once we switch main editor to CodeMirror, it should be easy to add syntax highligting based on that as well.
