### ISSUE TITLE
Limit the number of "Other components" displayed

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#4220]
**Is your feature request related to a problem? Please describe.**
In projects with many components, listing them all on a component page is excessive, making the page many times longer than it needs to be. For example: https://translations.documentfoundation.org/projects/libo_ui-master/cuimessages/fi/

**Describe the solution you'd like**
Is it necessary to display "Other components" on the component page at all? If it is, the list should at least be collapsed by default, if the number of components exceeds (say) 10.

**Describe alternatives you've considered**
Including simply a link to the page that shows the components.

**Additional context**

**Comment by nijel** [comment]
It was introduced to give bigger visibility to related translations, see https://github.com/WeblateOrg/weblate/issues/559, but it certainly makes sense to limit the listing to a few of them (preferring not translated ones) and include link to full list (https://translations.documentfoundation.org/languages/fi/libo_ui-master/ in your case).

**Comment by comradekingu** [comment]
@tjhietala I think the current limit elsewhere is how many items you can reasonably fit on a UHD-display on its side. That is 60 or so. On https://translations.documentfoundation.org/languages/fi/libo_ui-master/ is something like 90.
I would expect to find all components in "components". What are "other components" in that regard?

**Comment by nijel** [comment]
@comradekingu Just click on link in first post to see that ;-)

**Comment by krishnmohan19** [comment]
Hii @nijel  i am new to open source  so can i work on this. ?

**Comment by nijel** [comment]
@krishnmohan19 You are welcome.

The related code is here (note the logic for adding ghost translations):

https://github.com/WeblateOrg/weblate/blob/138d10ad14e8ef3962670fa3faea7ac2dbe1bc2c/weblate/trans/views/basic.py#L299-L316

And template is here:

https://github.com/WeblateOrg/weblate/blob/138d10ad14e8ef3962670fa3faea7ac2dbe1bc2c/weblate/templates/translation.html#L184-L191
