### ISSUE TITLE
Wrong alert when creating component through api

### ISSUE THREAD

**Issue by franta** [WeblateOrg/weblate#4228]
**Describe the bug**
Alerts:

Could not push the repository.

Weblate could not push changes to the upstream repository.

fatal: bad revision 'origin/mybranch..'
 (128)

But in fact everything is ok.

**To Reproduce**

1. Create components through API, vcs is gitlab
2. About 80% components show this message
3. After some changes (eg. new translation) commit is working and alert message on changed component disappear

**Server configuration and status**

Weblate 4.1.1 installed by helm

**Comment by nijel** [comment]
Did you get any errors in the logs while creating? Seems like the remote repository is not properly set up.

**Comment by franta** [comment]
No error in response, it's valid json with component data. If this not happens in general, I will ask support after my company order support. Ordering should be in progress. This issue is not blocker everything is working, only wrong message in ui.

May be one information, I am creating about 50 components from about 10 repositories in short time (most components reference repo by weblate:// syntax.

My request body for dummy component referencing real git repo:
```
{"branch":"[branchname]","file_format":"properties", "filemask":"invalid*", "git_export":"","license":"", "license_url":"","name":"[componentname]","slug":"[componentname]","repo":"[git@gitlab.ourcompany:path/project.git]","template":"","new_base":"","vcs":"gitlab","push":"[git@gitlab.ourcompany:path/project.git]"}
```

And real component creation referencing repo from dummy component:

```
{"branch":"","file_format":"[format]","filemask":"[path/filename_*.extension]","git_export":"","license":"","license_url":"","name":"[componentname-filename]","slug":"[componentname-filename]","repo":"weblate://[projectname]/[componentname]", "template":"[path/filename.extension]","new_base":"","vcs":"gitlab","push":"weblate://[projectname]/[componentname]"}
```

**Comment by nijel** [comment]
My guess is that the problem is in the invalid mask, it won§t fully create the component. But it should be caught by validation before creating it...

**Comment by franta** [comment]
You are right, gui don't allow this settings, closing because definitely don't want fix for validation because don't want dummy file in every repo.
