### ISSUE TITLE
Microsoft Translator Https ConnectionError (Docker only?)

### ISSUE THREAD

**Issue by Kyuuu** [WeblateOrg/weblate#4229]
**Describe the bug**

With the newest update via Docker (Weblate 4.1.1) in every language this popup appears:

> Żądanie tłumaczenia maszynowego przy użyciu Microsoft Translator nie powiodło się: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='westeurope.https', port=443): Max retries exceeded with url: //link.cognitiveservices.azure.com//sts/v1.0/issueToken?Subscription-Key=token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff1926c5048>: Failed to establish a new connection: [Errno -2] Name or service not known'))"))

**Additional context**
Google translate works fine:

![image](https://user-images.githubusercontent.com/33127074/88595263-ee345180-d062-11ea-990b-d71a2202d2dd.png)

**Comment by nijel** [comment]
> host='westeurope.https'

Looks wrong, maybe wrong setting for [MT_MICROSOFT_ENDPOINT_URL](https://docs.weblate.org/en/latest/admin/config.html#mt-microsoft-endpoint-url). You probably don't need this one unless you are in China.

**Comment by Kyuuu** [comment]
Our MT_MICROSOFT_ENDPOINT_URL starts with "https://" which is missing in the error message (it starts with //), which would result in "[Errno -2] Name or service not known" as the protocol is missing from URL.
Since it began with the latest docker update (and was working fine before) it seems that something changed in regard to reading that setting from settings-override.py

**Comment by nijel** [comment]
`MT_MICROSOFT_ENDPOINT_URL` should be just domain name.

This setting did not exist prior to 4.1, so maybe that's why it didn't cause anything. It was introduced by f95b8a57aa9
