### ISSUE TITLE
Broken search with long search text

### ISSUE THREAD

**Issue by Mingun** [WeblateOrg/weblate#4231]
**Describe the bug**

Periodically long strings are not searched, instead the search ends with the message “No string matched your search!”

**To Reproduce**

For example search string “[The percent placeholders](https://hosted.weblate.org/translate/weblate/application/ru/?q=The+percent+placeholders)” found one result. But if we search full text from that result “[The percent placeholders do not match source](https://hosted.weblate.org/translate/weblate/application/ru/?q=The+percent+placeholders+do+not+match+source)”, search ends with the message “No string matched your search!”

**Expected behavior**

Search should always find relevant results.

**Additional context**

Hosted Weblate 4.2-dev

**Comment by nijel** [comment]
When searching for long string, better to quote it. This way `not` is used as logical expression looking for strings where `match` word is not present and all other words are present.

See https://docs.weblate.org/en/latest/user/search.html

**Comment by Mingun** [comment]
OK, that looks reasonable.
