### ISSUE TITLE
More files in one repository

### ISSUE THREAD

**Issue by franta** [WeblateOrg/weblate#4233]
**Is your feature request related to a problem? Please describe.**
I want localize more files from one repository and don't want download this repository more times to weblate. Files may be added or removed - don't want depends on one randomly selected file with git repository reference.

**Describe the solution you'd like**
Allow component without valid file - only for reference git repository.

**Describe alternatives you've considered**
Prepare special "component" type called eg. repository for reference git repository. Put this repository between project and components with 1..N relationship.

Don't add git repository directly to project - I need more git repositories inside one project.

**Comment by nijel** [comment]
This is already there, you can use internal reference as repository URL, see https://docs.weblate.org/en/latest/vcs.html#weblate-internal-urls.

It is used automatically in the web UI when creating component that matches your existing repo. You can alsso choose to create "From existing component" (see https://docs.weblate.org/en/latest/admin/projects.html#adding-translation-projects-and-components) to do it explicitely or use Component discovery addon to automate this, see https://docs.weblate.org/en/latest/admin/addons.html#component-discovery.
