### ISSUE TITLE
How can i change the component which was fork from the existing component to a independent git repo or branch ?

### ISSUE THREAD

**Issue by deboyblog** [WeblateOrg/weblate#4236]
**Describe the issue**

There is a component that already exists name `a-component`
then i create a new component form that existing component name `b-component`
when b-component have some original words update and new key-value added, and i don't want to sync to the a-component git repo.
but when i clone the a-component repo, it's always the lastest update on b-component.
Q1: how can i create the different branch to contain b-component in a-component git repo?
Q2: when i using [this api](https://docs.weblate.org/en/weblate-4.1.1/api.html#components)  to get the component info, b-component without `git_export`, there is noway to clone b-component repo, and there is no field to told me b-component is connect to a-component

**Comment by nijel** [comment]
Maybe I'm missing something, but in case you have different branches, the components won't share the repository. How exactly did you create the b-component? "From existing component" chooses different files from the same component, sharing the underlying repo, there is also "Additional branch" where you can choose different branch from the repo (but it has to already exist). See also https://docs.weblate.org/en/latest/admin/projects.html#adding-translation-projects-and-components

**Comment by deboyblog** [comment]
My wablate version is 4.1.1.
I didn't see  "Additional branch" option when I create a new component, which step can I see this option?
![image](https://user-images.githubusercontent.com/11410323/89101706-f6123e00-d434-11ea-971a-309a945bb04e.png)

**Comment by nijel** [comment]
The option will be there only if there is a repository which has more branches.

**Comment by deboyblog** [comment]
> The option will be there only if there is a repository which has more branches.

how can I cretae more branch if I use the wablate default repository?  
I found that I couldn't push it after I cloned my weblate component repo with username and password like `git clone https://username:password@translate.xxx.com`

**Comment by nijel** [comment]
In case you did not used remote repository, just create again new component from scratch. Playing with branches doesn't bring any benefits in this case.

**Comment by deboyblog** [comment]
I changed to use the remote repository by connect to gitlab, it's solved my problem.
Thank you for your patient reply.
