### ISSUE TITLE
Uploading translation files using the translate or fuzzy method are not working as expected

### ISSUE THREAD

**Issue by superDross** [WeblateOrg/weblate#4249]
**Describe the bug**

As per the title everytime I use the fuzzy or translate method via the UI when uploading translation files (monolingual PO gettext format), I receive the below error:

```
Processed 2 strings from the uploaded files (skipped: 0, not found: 2, updated: 0). 
```

The only way I can upload a PO file and have the contents updated is using the `replace` method.

**To Reproduce**

Create a monolingual component referring to a git repo with these files:

Monolingual base file:
```
#: weblate/media/js/bootstrap-datepicker.js:1421
msgid "day-monday"
msgstr "Monday"

msgid "day-wednseday"
msgstr "Wednseday"
```

Monolingual template file:
```
#: weblate/media/js/bootstrap-datepicker.js:1421
msgid "day-monday"
msgstr ""

msgid "day-wednseday"
msgstr ""
```

Once the component has been created, create a new translation and upload a translation file that looks like this:
```
#: weblate/media/js/bootstrap-datepicker.js:1421
msgid "day-monday"
msgstr "test"

msgid "day-wednseday"
msgstr ""
```

With the options:
![op](https://user-images.githubusercontent.com/16519378/89205909-61cce600-d5b0-11ea-9c3c-7006b2546e79.png)

**Expected behavior**

For Monday translation to be test for the translated string and for this to be represented in the UI and in the resulting PO file stored in Weblate.

The expected message:
```
Processed 2 strings from the uploaded files (skipped: 0, not found: 0, updated: 1). 
```

**Server configuration and status**

    Weblate: 4.1.1
    Django: 3.0.8
    siphashc: 1.3
    Whoosh: 2.7.4
    translate-toolkit: 3.0.0
    lxml: 4.5.1
    Pillow: 7.1.2
    bleach: 3.1.5
    python-dateutil: 2.8.1
    social-auth-core: 3.3.3
    social-auth-app-django: 3.4.0
    django-crispy-forms: 1.9.1
    oauthlib: 3.1.0
    django-compressor: 2.4
    djangorestframework: 3.11.0
    django-filter: 2.3.0
    django-appconf: 1.0.4
    user-agents: 2.1
    filelock: 3.0.12
    setuptools: 40.8.0
    jellyfish: 0.8.2
    openpyxl: 3.0.1
    celery: 4.4.6
    kombu: 4.6.11
    translation-finder: 2.1
    html2text: 2020.1.16
    pycairo: 1.16.2
    pygobject: 3.30.4
    diff-match-patch: 20181111
    requests: 2.24.0
    django-redis: 4.12.1
    hiredis: 1.0.1
    sentry_sdk: 0.15.1
    Cython: 0.29.20
    misaka: 2.1.1
    GitPython: 3.1.3
    borgbackup: 1.1.13
    pyparsing: 2.4.7
    Python: 3.7.3
    Git: 2.20.1
    psycopg2: 2.8.5
    psycopg2-binary: 2.8.5
    phply: 1.2.5
    chardet: 3.0.4
    ruamel.yaml: 0.16.10
    tesserocr: 2.5.1
    akismet: 1.1
    boto3: 1.14.14
    zeep: 3.4.0
    aeidon: 1.7.0
    iniparse: 0.5
    mysqlclient: 1.4.6
    Mercurial: 5.4.2
    git-svn: 2.20.1
    git-review: 1.28.0
    hub: 2.13.0
    lab: 0.16
    Redis server: 5.0.9
    PostgreSQL server: 11.8
    Database backends: django.db.backends.postgresql
    Cache backends: default:RedisCache, avatar:FileBasedCache
    Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.mailtrap.io
    OS encoding: filesystem=utf-8, default=utf-8
    Celery: redis://cache:6379/1, redis://cache:6379/1, regular
    Platform: Linux 5.4.52-1-MANJARO (x86_64)

**Comment by nijel** [comment]
Probably related to monolingual PO format, maybe it uses it as bilingual instead.

**Comment by superDross** [comment]
So, I just checked, and these methods (`fuzzy`, `translate` and eve `approve`) work fine via the UI when the component is a bilingual format. This makes me think it is a bug specifically for monolingual components.
