### ISSUE TITLE
Adding Translation Units behaves differently based on order of invocations.

### ISSUE THREAD

**Issue by jojurajan** [WeblateOrg/weblate#4277]
**Describe the bug**

Adding a translation unit with same key for different languages in a component behaves differently based on order

**To Reproduce**

If we have a project with _en_ as source language,

Scenario 1:
* Post a new translation unit to en. **_{"key": "string A", value: "This is string A in en"}_**
* Post same translation unit to de. **_{"key": "string A", value: "This is string A in de"}_**

We get an error _Translation with this key seem to already exist!_

Scenario 2:
* Post a new translation unit to de. **_{"key": "string B", value: "This is string B in de"}_**
* Post same translation unit to en. **_{"key": "string B", value: "This is string B in en"}_**

The translated string is visible under German language for the component.

**Expected behavior**

The translated string is visible in German, irrespective of the order of execution of translation Unit APIs

**Comment by nijel** [comment]
How exactly do you add units? In Weblate should be possible to add only units to source language.

What Weblate version do you use?

**Comment by jojurajan** [comment]
Adding the versions output
```
$ ./manage.py list_versions
 * Weblate: weblate-4.1.1-702-gc7564737db
 * Django: 3.0.8
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0
 * lxml: 4.5.2
 * Pillow: 7.2.0
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-filter: 2.3.0
 * django-appconf: 1.0.3
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.6.2
 * jellyfish: 0.8.2
 * openpyxl: 3.0.4
 * celery: 4.4.6
 * kombu: 4.6.11
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.36.1
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.16.1
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.7
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.6.8
 * Git: 2.27.0
 * psycopg2-binary: 2.8.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * git-svn: 2.27.0
 * Redis server: 6.0.5
 * PostgreSQL server: 9.6.18
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Platform: Darwin 18.7.0 (x86_64)
```

**Comment by jojurajan** [comment]
I used this script to add the units. Just changed the `language` and `value` parameters as required.

```
import requests

def check_unit_upload():
    SETTINGS = {
        "base_url": "http://localhost:8000/api",
        "api_key": "<add_key>"
    }
    base_url = SETTINGS["base_url"]
    api_key = SETTINGS["api_key"]
    project = "mono-trans-project"
    comp = "sample-1k-mono-new"
    langauge = "en"
    data = {
        "key": "String F",
        "value" : "This is string F in en"
    }
    resp = requests.post(
        f"{base_url}/translations/{project}/{comp}/{langauge}/units/",
        headers={"Authorization": f"Token {api_key}"},
        data=data
    )
    print(resp._content)
```

**Comment by nijel** [comment]
When I try it, I (correctly) get HTTP 403 when trying to add unit to non source language:

```
<Response [403]>
'{"detail":"Can not add unit"}'
```

On source language it works just fine and returns the newly added unit and fails on second execution when unit is already added.

**Comment by jojurajan** [comment]
@nijel Thank you for the quick response. I had a look after your reply. I had forgotten to remove an update which was bypassing the checks due to which this weird scenario was possible. After reverting back, I can confirm that it works as you have said.

I'm extremely sorry for the trouble that I caused you.
