### ISSUE TITLE
Zen editing does not save "needs editing" flag, because "has been translated" 

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4286]
This turned out "has been translated"
https://hosted.weblate.org/translate/xwords/android/nb_NO/?checksum=6186f2a953e1a08

What happens otherwise is the translation saved, but the "needs editing" checkbox not.
If that happens it says "Translation exists" or somesuch.

Could be these are two different issues?

Will have to see if it also hapens when not translating source strings with multiple tabs open in Zen and regular mode.

**Comment by nijel** [comment]
I see it now saved as needs editing. Did you save it again? In case of failing check the string is saved, but the failing check is shonw.

**Comment by comradekingu** [comment]
Yes. I went into the regular editor and did that.

Just now I opened an e-mail by clicking the "not translated strings" link
https://hosted.weblate.org/translate/openrefine/database/nb_NO/?q=state:empty

This string opened in the regular editor
https://hosted.weblate.org/translate/openrefine/database/nb_NO/?checksum=a736aceb92aeebaf
Then I changed to Zen
Edited the string and clicked "needs editing"
it says
> Translation of string has changed meanwhile: Please review your changes

"Needs editing" is not saved, but the string is.

**Comment by nijel** [comment]
Seems like a race condition, but I'm unable to trigger it. The edited string is saved ansynchronously once the textarea looses focus. The response updates string version in the browser. However before this happens, the string is submitted again with changed state and outdated version.
