### ISSUE TITLE
"Failing checks" doesn't tell what is wrong

### ISSUE THREAD

**Issue by aha999** [WeblateOrg/weblate#4293]
**Is your feature request related to a problem? Please describe.**
When doing Failed Checks, and i don't know what is wrong, the Weblate doesn't say why the check failed... or why is the problem there...

**Describe the solution you'd like**
Text under every string translation explaining what went wrong/why did it fail checking

**Comment by nijel** [comment]
There is always a description, for some checks there is even detailed description what is wrong:

![obrazek](https://user-images.githubusercontent.com/212189/89796673-36a34300-db2a-11ea-82d6-de4918d210d5.png)

**Comment by aha999** [comment]
well, this was not seen anywhere on the checks it failed where i was translating... now i found out i didn't include one enter space, but it didn't say anywhere why the checks failed...

**Comment by nijel** [comment]
The failing check is always displayed in the right sidebar...
