### ISSUE TITLE
Receive Notification When Component is Completely Translated

### ISSUE THREAD

**Issue by superDross** [WeblateOrg/weblate#4294]
**Is your feature request related to a problem? Please describe.**
I want to receive a notification when all translations have been completed in a component.

**Describe the solution you'd like**
[Component wide notifications options ](https://docs.weblate.org/en/latest/user/profile.html?highlight=notifications#notifications) have a drop down box for `Completely Translated Component`.

**Comment by funktionierbar** [comment]
I would also be nice to be notified when a single translation is at 100%, at least for a project that I manage.
