### ISSUE TITLE
Receive Notifications from Watched Components

### ISSUE THREAD

**Issue by superDross** [WeblateOrg/weblate#4295]
**Is your feature request related to a problem? Please describe.**
Currently there is only a way to receive notifications from watched projects. It would be useful to also useful to have this feature available at the component level too.

**Describe the solution you'd like**
[Within the notification options](https://docs.weblate.org/en/latest/user/profile.html?highlight=notifications#notifications), have a box allowing one to select components to watch and to have the `component wide notification` settings available for a individually watched component.

**Comment by nijel** [comment]
Duplicate of #3510
