### ISSUE TITLE
Chinese plurals using incorrect quantifier

### ISSUE THREAD

**Issue by arkon** [WeblateOrg/weblate#4296]
**Describe the bug**

We're seeing this happen for Chinese (`zh-rCN`) translations in the Tachiyomi (Android) project.

Expected:

```xml
<plurals name="num_trackers">
  <item quantity="other">%d 个同步源</item>
</plurals>
```

What we're actually getting from Weblate:

```xml
<plurals name="num_trackers">
  <item quantity="one">%d 个同步源</item>
  <item quantity="other"/>
</plurals>
```

**To Reproduce**

We have an automated process to update Weblate with the strings from https://github.com/inorichi/tachiyomi. If you need more details, I can ask someone who's more familiar with it.

**Expected behavior**

See earlier section.

**Screenshots**

N/A

**Server configuration and status**

N/A, using hosted Weblate.

**Weblate deploy checks**

N/A, using hosted Weblate.

**Exception traceback**

N/A

**Additional context**

Related earlier issues:
- https://github.com/WeblateOrg/weblate/issues/3837
- https://github.com/inorichi/tachiyomi/issues/2714

Most recent instance of seeing this issue: 
- https://github.com/inorichi/tachiyomi/pull/3580

**Comment by comradekingu** [comment]
Isn't that halfway what is supposed to happen? The source string isn't pluralized?

https://hosted.weblate.org/languages/zh_Hans/#information
vs
https://hosted.weblate.org/languages/zh_Hant/#information
the latter has an additional blue line.

http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html
https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals  

And then this bugreport https://code.djangoproject.com/ticket/765

**Comment by arkon** [comment]
> Isn't that halfway what is supposed to happen?

I guess? It's at least recognizing that there should only be one form, but it's putting it in `one` instead of `other`, and then adding an empty `other`. We've been manually moving the value from `one` to `other` in the generated XML files.

> The source string isn't pluralized?

This is the source string:

```
<plurals name="num_trackers">
    <item quantity="one">1 tracker</item>
    <item quantity="other">%d trackers</item>
</plurals>
```

There isn't a concept of plural quantifiers in Chinese (traditional nor simplified), like that Django bug report mentioned.
