### ISSUE TITLE
Zen mode: Option to show source string comment field

### ISSUE THREAD

**Issue by RobbyZ** [WeblateOrg/weblate#4299]
**Is your feature request related to a problem? Please describe.**
Some of our translators are really excited about Zen mode, but I'm a bit worried since using that hides the comment field and they may miss some important note.

**Describe the solution you'd like**
Maybe there could be an option to show the comment field above or below the source translation?

**Describe alternatives you've considered**
A hover icon with the comment could also work, but that wouldn't be quite as efficient of a workflow since then translators would have to mouse over it (and might not bother if it seems like an obvious translation).

**Additional context**
In our case, we have many multiline comments, so supporting multiple lines here would be ideal.

**Comment by nijel** [comment]
It should be there, it was probably mistakenly not ported at some point.

**Comment by RobbyZ** [comment]
Thank you very much!
