### ISSUE TITLE
Creating components with large file sizes fails

### ISSUE THREAD

**Issue by jan-nsn** [WeblateOrg/weblate#4311]
**Describe the bug**

We have a component with about 26000 strings. Now we want to create a release component that has an older translation version. When I put the file(s) into a ZIP (The zip archive contains the base file and another language file) and upload it via "upload translation files", the component shows that the base file contains 0 strings. However, the strings are displayed in the language.

![2020-08-12_10h27_18](https://user-images.githubusercontent.com/37983983/89993063-767f3d00-dc86-11ea-96e2-0a0bafd728d6.png)
Core: Contains ~26000 strings and one additional language
Core Release 15.2: Should also contain 26000 strings and another language, but nothing is displayed 
Test: Smaller component with 160 strings and one additional language
Test2: Same component as Test, but with 155 strings and one additional language

This only happened with larger files. With small files the correct effect was obtained.

**To Reproduce**

1. Go to a project
2. Create a new component and upload file(s) with about 26000 strings via "upload translation files"
3. Create another new component and upload the same file(s) via "upload translation files"
4. See components

**Expected behavior**

"Core Release 15.2" should also have the base file and a language.

**Server configuration and status**

 * Weblate: 4.1.1
 * Django: 3.0.8 
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0     
 * lxml: 4.5.1
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1       
 * social-auth-core: 3.3.3      
 * social-auth-app-django: 3.4.0
 * django-crispy-forms: 1.9.1   
 * oauthlib: 3.1.0
 * django-compressor: 2.4       
 * djangorestframework: 3.11.0
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.1
 * celery: 4.4.6
 * kombu: 4.6.11
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.0.1
 * sentry_sdk: 0.15.1
 * Cython: 0.29.20
 * misaka: 2.1.1
 * GitPython: 3.1.3
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.5
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.14.14
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 1.4.6
 * Mercurial: 5.4.2
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * hub: 2.13.0
 * lab: 0.16
 * Redis server: 5.0.4
 * PostgreSQL server: 11.6
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.tegos.eu
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://:mjEW4Q$PTknvQfPx@redis-svc:6379/2, redis://:mjEW4Q$PTknvQfPx@redis-svc:6379/2, regular
 * Platform: Linux 4.15.0-1069-azure (x86_64)

 **Weblate deploy checks**

System check identified some issues:

WARNINGS:
?: (security.W005) You have not set the SECURE_HSTS_INCLUDE_SUBDOMAINS setting to True. Without this, your site is potentially vulnerable to attack via an insecure connection to a subdomain. Only set this to True if you are certain that all subdomains of your domain should be served exclusively via SSL.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/backup.html

System check identified 4 issues (1 silenced).

**Comment by jan-nsn** [comment]
I just tried to upload only the base file in a ZIP archive and it worked fine. Only if I add another language to the ZIP archive it does not work.

**Comment by nijel** [comment]
Do you get any errors in the logs? Maybe the processing just takes too long and the strings will eventually appear...

**Comment by jan-nsn** [comment]
No errors were shown in the logs. We also tried to leave the components alone overnight, but the next day nothing changed, nothing in the logs and no new language was created.

**Comment by nijel** [comment]
Did you correctly configure the file format during the import? 

Can you try running manual loading of the existing file? `weblate loadpo --foreground --force test/core-release-15.2` should do it, but I'm guessing the component name.

**Comment by jan-nsn** [comment]
Since we use the XLIFF format, I don't know if we can import this via the CLI.
A work around has been, however, if we upload only the base translation file into a ZIP archive and then later create the languages manually and insert translations.

**Comment by nijel** [comment]
Don't worry about `loadpo` name, it loads whatever is configured right now.

**Comment by jan-nsn** [comment]
When I run the command, I get the following message:

weblate@weblate-945745fc5-sm46f:/$ weblate loadpo --foreground --force test/core-release-15-2
INFO test/core-release-15-2: checking enwis.Core.g.xlf (g) [1/2]
INFO test/core-release-15-2/g: processing enwis.Core.g.xlf, check forced
INFO test/core-release-15-2: checking enwis.Core.de-DE.xlf (de-DE) [2/2]
INFO test/core-release-15-2/de-DE: processing enwis.Core.de-DE.xlf, new file
Killed

Additionally, the component remained unchanged.

**Comment by nijel** [comment]
Okay, that explains why it's not completed :-). It seems like it was killed by OOM. How much memory does the server have?

**Comment by jan-nsn** [comment]
Currently the server runs with 4GB.

**Comment by nijel** [comment]
Anything else consuming lots of memory there? Is Weblate running in DEBUG mode? Check kernel log why the process has been killed...

**Comment by jan-nsn** [comment]
We use weblate in a container environment and have therefore allocated at least 3.5 gb to the server. This means that working memory should not be a problem. Furthermore, there were no signs/events that would have shown that there is not enough memory.
Also the debug mode is off.

**Comment by jan-nsn** [comment]
Ok the kernel log showed that there is not enough memory. 
[14833320.741932] Memory cgroup out of memory: Kill process 28529 (weblate) score 885 or sacrifice child

But why does it need more memory, if there is already a component with the same size as without?

**Comment by nijel** [comment]
I have no clue, it might be some issue in parsing. How much memory did it consume (it should be visible in the kernel log).

**Comment by jan-nsn** [comment]
Since we had to restart the container, I do not have the logs anymore. However, I remember that the logs said that the server had used the full 4gb.
