### ISSUE TITLE
Cannot Add new translation component

### ISSUE THREAD

**Issue by FransMeerhoff** [WeblateOrg/weblate#4312]
**Describe the issue**

Dear Support,

We encounter the following configuration problem:

In the additional information below you can see that JASP is an open source project
and we know that Weblate supports open source projects. We filled in this information form 
as you can check below. (We understood that for such projects you can activate the Libre plan for free. 
It has same limits as Advanced plan, but only allows public projects.)

But now we want to add a new translation component in our project.
And the response is:
“ You do not have permission to create components in any projects.
This might be caused by missing subscription or some of your billings are past due date or over limits. “

We do not know how to solve this and what exactly the status of our account is at the moment..

I hope you can help us out with this.

Kind regards 
Frans Meerhoff (JASP developer)

**To Reproduce**
On the Dashboard :
Press the Add button
Choose 'Add new translation component

**Expected behavior**
Translation component should be added.

**Comment by nijel** [comment]
This should be now addressed, the project is at https://hosted.weblate.org/projects/jasp/
