### ISSUE TITLE
Show some message when setting up component

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#4327]
**Is your feature request related to a problem? Please describe.**
When creating a component in a project, there is no progress or message about scanning and cloning the remote repo.

**Describe the solution you'd like**
Show message _Weblate is scanning the chosen repository for translation files. It will be done in a few moments._

**Describe alternatives you've considered**
Wait and be a bit guessed if something is happening and for how long.

**Comment by nijel** [comment]
When creating component, the progress is shown:

![image](https://user-images.githubusercontent.com/212189/92212357-23b63100-ee92-11ea-984f-88de5a93e823.png)

When somebody opens the component at the same time, the ongoing update is indicated by an icon (which can be clicked to get detailed progress):

![image](https://user-images.githubusercontent.com/212189/92212435-3fb9d280-ee92-11ea-99c5-a4476bdfdf88.png)

Maybe I'm missing the point where the progress should be shown?
