### ISSUE TITLE
I am trying to register to the website - but a confirmation is never received

### ISSUE THREAD

**Issue by OrenYul** [WeblateOrg/weblate#4328]
Hi,
I am trying to assist in translation of a web site and an app.
http://translation.timesheet.io/projects/timesheet/ios/

When I register I am not getting the activation email

I use the following email: timesheet.io@yulevitch.com
It is a good email.
Nothing gets in to the SPAM.

I tried Chrome, EDGE, explorer... Nothing works.

I only get to the following text:
Registration User registration
Registration almost complete
Thank you for registering. You will very soon receive an email with a confirmation link. Please follow this link in order to complete your registration.

Please note that the confirmation link has limited validity. In case it does not work, please register again.

If you don't receive it shortly, please check your spam folder or retry the registration. If the problem persists, please contact us.

Powered by Weblate 2.17.1timesheet.io

**Expected behavior**

Receive an activation email

Any help would be appreciated.

Oren

**Comment by nijel** [comment]
We do not operate that server, try reaching its admins, for example using http://translation.timesheet.io/contact/
