### ISSUE TITLE
Support for multiple GitLab instances

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#4332]
**Is your feature request related to a problem? Please describe.**
Weblate currently supports only single GitLab instance for pull requests. This can be limiting for some open source hostings as there can be multiple instances of GitLab which we want to talk to.

**Describe the solution you'd like**
Extend GITLAB_USERNAME / GITLAB_TOKEN configuration to support multiple GitLab instances.

**Additional context**
See https://github.com/WeblateOrg/weblate/pull/4224

**Comment by StefanBrand** [comment]
For reference: Docs are here: https://docs.weblate.org/en/latest/admin/config.html#gitlab-credentials
