### ISSUE TITLE
Weblate allowed_hosts multiple domains

### ISSUE THREAD

**Issue by tregin** [WeblateOrg/weblate#4335]
Hey 
I'm currently deploying weblate using OPENSHIFT TEMPLATE and would like to add two domain names to the WEBLATE_ALLOWED_HOSTS parameters but when I do it in a format like this:

```
- name: WEBLATE_ALLOWED_HOSTS
  value: "['domain1.com', 'domain2.com']"
```

I have tried several formats like: 
```
- value: "['domain1.com', 'domain2.com']"
- value: "[domain1.com, domain2.com]"
- value: '["domain1.com", "domain2.com"]'
```
 but always unsuccessful

this doesn't work and I'm getting error when I try to access weblate
"
Bad request
We’re sorry but something appears to be wrong with the request you made.
"

when I have the parameter set only for one domain it works;
```
            - name: WEBLATE_ALLOWED_HOSTS
              value: "domain1"

```
Can you please share the correct syntax.

**Comment by nijel** [comment]
See example in the docs: https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_ALLOWED_HOSTS

**Comment by tregin** [comment]
yes I did that and even tried with settting:
```
            - name: WEBLATE_ALLOWED_HOSTS
              value: "example.com, example-2.com"
```

the result is the first domain "example.com" works... but the second doesn't.
I have even tried adding the second domain to the Sites under admin area but no luck...

**Comment by nijel** [comment]
I think the space should not be there.

**Comment by tregin** [comment]
thanks that did the trick! :)
