### ISSUE TITLE
Add search utilities dropdown on while-translate view

### ISSUE THREAD

**Issue by Porrumentzio** [WeblateOrg/weblate#4346]
**Is your feature request related to a problem? Please describe.**
When using Weblate sites and wanting to use the search to filter the strings (untranslated, with suggestions...) while translating I never know the correct syntax. Ex. `state:<translated`
![irudia](https://user-images.githubusercontent.com/61913683/90753820-60522c00-e2d9-11ea-8ad4-ae2279f4344a.png)

**Describe the solution you'd like**
The solution would be to display a dropdown menu with all the options, even maybe with non-syntactic form, but more human-legible.

**Describe alternatives you've considered**
An alternative could be to work as on mobile view, where the syntax are suggested when writing the initial letter. Ex `i` > `is:...`

**Comment by nijel** [comment]
Please upgrade, we already have this:

![image](https://user-images.githubusercontent.com/212189/90759131-4e27bc00-e2e0-11ea-887b-8436260c61bb.png)

See https://docs.weblate.org/en/latest/user/search.html#predefined-queries
