### ISSUE TITLE
Is it possible to disable certain types of email sending?

### ISSUE THREAD

**Issue by exzhawk** [WeblateOrg/weblate#4350]
**Describe the issue**

Is it possible to disable certain types of email sending? For example, disable new string/changed string email notification for all users; only send parse error to project admins; leaving resetting password by email for everyone.

**Additional context**

I'm hosting Weblate on my own server, using a mail service. I found that too many users are watching projects and prefer instant notification on a new string, changed string, and many others. The project is pretty large and changing often. Whenever there is a change, weblate send them emails. But the quantity of emails is too large, making my email service very stressful. And actually, many users do not really need email notifications. I can't disable the email completely, because resetting password needs sending email.

**Comment by nijel** [comment]
There is no way to globally disable some kind of notifications. You can however change the user subscriptions by API: https://docs.weblate.org/en/latest/api.html#get--api-users-(str-username)-notifications-

**Comment by exzhawk** [comment]
API works well. Thank you!
