### ISSUE TITLE
Upgrade 4.1.1 to 4.2

### ISSUE THREAD

**Issue by Badiboy** [WeblateOrg/weblate#4351]
_Yes, it's new upgrade and me again. :(_

**Describe the issue**

> WARNING Handled exception: OperationalError: (1054, "Unknown column 'trans_project.language_aliases' in 'field list'")

**language_aliases** field does not appear during upgrade (full exception below).
I found it in 0094_project_language_aliases.py, but seems that migration procedure does not run it.
How to force this script execution?

**Additional context**

> WARNING Handled exception: OperationalError: (1054, "Unknown column 'trans_project.language_aliases' in 'field list'")
> Traceback (most recent call last):
>   File "/drive/weblate-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
>     return self.cursor.execute(sql, params)
>   File "/drive/weblate-env/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 74, in execute
>     return self.cursor.execute(query, args)
>   File "/drive/weblate-env/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
>     res = self._query(query)
>   File "/drive/weblate-env/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
>     db.query(q)
>   File "/drive/weblate-env/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
>     _mysql.connection.query(self, query)
> MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'trans_project.language_aliases' in 'field list'")
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/drive/weblate-env/bin/weblate", line 8, in <module>
>     sys.exit(main())
>   File "/drive/weblate-env/lib/python3.8/site-packages/weblate/runner.py", line 32, in main
>     execute_from_command_line(argv)
>   File "/drive/weblate-env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "/drive/weblate-env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/drive/weblate-env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/drive/weblate-env/lib/python3.8/site-packages/weblate/utils/management/base.py", line 42, in execute
>     return super().execute(*args, **options)
>   File "/drive/weblate-env/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
>     output = self.handle(*args, **options)
>   File "/drive/weblate-env/lib/python3.8/site-packages/weblate/auth/management/commands/setupgroups.py", line 49, in handle
>     create_groups(options["update"])
>   File "/drive/weblate-env/lib/python3.8/site-packages/weblate/auth/models.py", line 614, in create_groups
>     migrate_groups(Group, Role, update)
>   File "/drive/weblate-env/lib/python3.8/site-packages/weblate/auth/utils.py", line 83, in migrate_groups
>     instance.save()
>   File "/drive/weblate-env/lib/python3.8/site-packages/weblate/auth/models.py", line 165, in save
>     self.projects.set(
>   File "/drive/weblate-env/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 986, in set
>     objs = tuple(objs)
>   File "/drive/weblate-env/lib/python3.8/site-packages/django/db/models/query.py", line 276, in __iter__
>     self._fetch_all()
>   File "/drive/weblate-env/lib/python3.8/site-packages/django/db/models/query.py", line 1261, in _fetch_all
>     self._result_cache = list(self._iterable_class(self))
>   File "/drive/weblate-env/lib/python3.8/site-packages/django/db/models/query.py", line 57, in __iter__
>     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
>   File "/drive/weblate-env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1152, in execute_sql
>     cursor.execute(sql, params)
>   File "/drive/weblate-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
>     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
>   File "/drive/weblate-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
>     return executor(sql, params, many, context)
>   File "/drive/weblate-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
>     return self.cursor.execute(sql, params)
>   File "/drive/weblate-env/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/drive/weblate-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
>     return self.cursor.execute(sql, params)
>   File "/drive/weblate-env/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 74, in execute
>     return self.cursor.execute(query, args)
>   File "/drive/weblate-env/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
>     res = self._query(query)
>   File "/drive/weblate-env/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
>     db.query(q)
>   File "/drive/weblate-env/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
>     _mysql.connection.query(self, query)
> django.db.utils.OperationalError: (1054, "Unknown column 'trans_project.language_aliases' in 'field list'")
> 
>

**Comment by nijel** [comment]
Did you run the migrations? See https://docs.weblate.org/en/latest/admin/upgrade.html#generic-upgrade-instructions

You can also check current status by `weblate showmigrations`.
