### ISSUE TITLE
Add "delete user from group" into api

### ISSUE THREAD

**Issue by franta** [WeblateOrg/weblate#4353]
**Is your feature request related to a problem? Please describe.**
It's possible to add user to group by API, but not remove it (or it's missing in documentation).

**Comment by krishnan2098** [comment]
Hi @nijel , I would like to work on this Issue.

**Comment by nijel** [comment]
@krishnan2098 you're welcome, I've just assigned this issue to you.

**Comment by alvinchen977** [comment]
@nijel Has this feature request been added? If not, I would like to work on it

**Comment by nijel** [comment]
It has not been added yet, you are welcome to implement it.

**Comment by ParthS007** [comment]
@nijel what about a `PATCH` API for updating the group members, I think of adding in [Group's API](https://github.com/WeblateOrg/weblate/blob/main/weblate/api/views.py#L426). Please let me know what do you think.

**Comment by nijel** [comment]
The groups API doesn't currently expose users. The users API does expose groups, that's why I was thinking about placing it there.

**Comment by ParthS007** [comment]
okay, Understood, Then I will go for this: `DELETE /api/users/(str: username)/groups/(int: group_id)/`
