### ISSUE TITLE
Improved presentation of differences in machine translations

### ISSUE THREAD

**Issue by goeranu** [WeblateOrg/weblate#4368]
**Is your feature request related to a problem? Please describe.**
When Weblate gives me suggestions for machine translations there is an indication on how similar the source string is to the one I'm translating. Unless the string is short, it can require a close read to discover exactly what the differences are.

**Describe the solution you'd like**
If the differences were highlighted, for example similarly to how a message that has been changed is marked with red and green sections, it would be immediately obvious what the differences were. Then I could more quickly make the necessary adjustments to the translated string.

**Comment by m-aciek** [comment]
<img width="1272" alt="Zrzut ekranu 2022-07-21 o 00 22 02" src="https://user-images.githubusercontent.com/9288014/180092618-9c4d400e-d5cf-45bc-8452-84d9b555fa6f.png">
@goeranu isn't it done already?

**Comment by goeranu** [comment]
In the particular case when the suggested translation is prefilled, I do indeed get markers of the changes nowadays. But not when there is separate suggestion, like here for example.
![Screenshot_20220721_093852](https://user-images.githubusercontent.com/1842587/180157970-9ffea457-1988-4ea3-8692-84c1c8f06765.png)

Similarly, there are no indication what is changed if you select “automatic suggestions” (approximate name, I'm not running in English.) You get an indication there is a 91% similarity, but you are not told what 9% differs.
![Screenshot_20220721_094601](https://user-images.githubusercontent.com/1842587/180158906-f7b79aa0-b6f6-4ee2-998b-0dd7989f4a41.png)

Do you want separate reports for each of these cases?

**Comment by Geeyun-JY3** [comment]
I guess OP wants what Crowdin provides like:
![image](https://user-images.githubusercontent.com/49396421/181191089-daf80895-a456-4f80-b9f9-38a9d4ac64d5.png)

**Comment by strepon** [comment]
I checked this new feature in Weblate 4.18.2 and I am confused - is it supposed to work in this way?

I get the highlights between "translation" and "suggested change" (where there is no change) while I would expect to see changes between the source and source of the suggestions (i.e. to correspond with the "similarity" column).

![obrazek](https://github.com/WeblateOrg/weblate/assets/9050387/b1f88500-6347-4b5f-919f-6fe0d4a59391)

**Comment by goeranu** [comment]
I can't say what the intention of the implementor was, but as the original reporter, I can say it is not what I had hoped for. The current highlighting doesn't give very useful information, as you note @strepon. What I did hope for was exactly what you express, the difference between the source of the suggestion and the source to be translated.

I haven't tried to reopen, but if we are more that would like this feature, maybe we should.

**Comment by nijel** [comment]
You're right, I misread the original report. The difference compared to the current string is useful during review – to see how the current translation compares to machine translation. But for the translation memory services, having source diff is important as well. I've just added it in 1460d8405a8c17030a88b87f8bb1c78377d1b828.

**Comment by strepon** [comment]
That was quick, thanks a lot!

**Comment by goeranu** [comment]
Returning now to Weblate after translating elsewhere for some time I see the markers I hoped for are indeed there. Thanks!
