### ISSUE TITLE
issue of Change history

### ISSUE THREAD

**Issue by baffclan** [WeblateOrg/weblate#4369]
**Describe the bug**

issue of Change history

**To Reproduce**

1. Open application language page
   e,g,. https://hosted.weblate.org/projects/weblate/application/ja/
2. Click Insight -> history
3. Goto page bottom, and click "Browse all translation changes"
4. Edit position is "1/246"
5. Click [>], Change to "2/246"
6. Click "edit position", edit to "200/246" and Enter

Actual Results
Edit position is "200/238636" with all languages

  
**Expected behavior**

Edit position is "200/246" with Japanese languages

**Additional context**

Reproduce with Weblate 4.2.1-dev

**Comment by nijel** [comment]
Seems like at least the lang URL parameter is missing from the form.

**Comment by BElluu** [comment]
I can look at this :)

**Comment by baffclan** [comment]
Reproduce with today's hosted.weblate.org.
> Weblate weblate-4.2.2-1279-g6e7254fdde

**Comment by nijel** [comment]
That's expected, the fix was not yet deployed.

**Comment by baffclan** [comment]
Cannot reproduce this.
Thanks for fixing this!
