### ISSUE TITLE
git error

### ISSUE THREAD

**Issue by remyahalza** [WeblateOrg/weblate#4382]
i got keyerror Git

Error during template rendering
In template /home/site/wwwroot/weblate/templates/snippets/git-info.html, error at line 24

git

**Comment by nijel** [comment]
Can you please include some useful information in the report? What Weblate version do you use? What was the actual error? What was the exception traceback?

**Comment by remyahalza** [comment]
I use 3.3 version. Now i upgraded to 4.1.1. when i click components in my project i got key error "git", only after signin to any user, without sign in no error


Exception Type: | KeyError
-- | --
'git'
/home/site/wwwroot/weblate/utils/classloader.py in __getitem__, line 78
/home/site/wwwroot/myenv/bin/python3.8
3.8.3

**Comment by nijel** [comment]
Have you changed configuration of VCS_BACKENDS? The Git backend has to stay there...

**Comment by remyahalza** [comment]
No. i didn't changed the configuration of VCS_BACKENDS, Can you please help me to configure this

**Comment by nijel** [comment]
Can you please provide full traceback?

**Comment by remyahalza** [comment]
Request Method: | GET
-- | --
http://halzaweblatenew.azurewebsites.net/manage/repos/
3.0.9
KeyError
'git'
/home/site/wwwroot/weblate/utils/classloader.py in __getitem__, line 78
/home/site/wwwroot/myenv/bin/python3.8
3.8.3
['/home/site/wwwroot/myenv/lib/python3.8/site-packages/git/ext/gitdb',  '/home/site/wwwroot',  '/home/site/wwwroot',  '/home/site/wwwroot/myenv/bin',  '/opt/python/3.8.3/lib/python38.zip',  '/opt/python/3.8.3/lib/python3.8',  '/opt/python/3.8.3/lib/python3.8/lib-dynload',  '/home/site/wwwroot/myenv/lib/python3.8/site-packages',  '/home/site/wwwroot/myenv/lib/python3.8/site-packages/gitdb/ext/smmap']

**Comment by remyahalza** [comment]
i got an error like ,


All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\26099\AppData\Local\Programs\Python\Python36\lib\site-packages\git\__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception



so I do
  export GIT_PYTHON_REFRESH=quiet


I think the key error due to this,


Can you please give me a solution for this

**Comment by nijel** [comment]
> All git commands will error until this is rectified.

Weblate can not find the git command. Maybe it's not installed in the PATH?

> File "C:\Users\26099\AppData\Local\Programs\Python\Python36\lib\site-packages\git_init_.py", line 85, in 

You apparently run Weblate on Windows, which is not supported, some things might be broken, see https://docs.weblate.org/en/latest/admin/install.html#operating-system

**Comment by remyahalza** [comment]
How to install git  in the path in linux

**Comment by remyahalza** [comment]
when i go to weblate, select a project and select a component, its working,
but I login to any user and do the same like above it shows git keyerror like above

**Comment by remyahalza** [comment]
When i try to create component, in version control option there is no git, can you please help me why this happened

**Comment by nijel** [comment]
When not authenticated, it doesn't show VCS information, so the related code path is not invoked. Anyway the root cause is that Weblate can not find `git` command. Are you running Windows or Linux? How did you install Git?

**Comment by remyahalza** [comment]
I am running in Azure Webapp service linux application, in its startup file i add like this, 

#!/bin/bash
apt-get update
apt-get install libssl-dev  --yes 
apt-get install  libxml2-dev   --yes 
apt-get install  libxslt-dev   --yes 
apt-get install  libfreetype6-dev   --yes 
apt-get install  libjpeg-dev   --yes 
apt-get install  libz-dev  --yes 
apt-get install libyaml-dev --yes
apt-get install libcairo-dev   --yes 
apt-get install gir1.2-pango-1.0 --yes   
apt-get install libgirepository1.0-dev --yes   
apt-get install libacl1-dev   --yes 
apt-get install libssl-dev   --yes 
apt-get install  build-essential --yes 
apt-get install python3-gdbm  --yes 
apt-get install python3-dev --yes 
apt-get install virtualenv   --yes 
apt-get install git   --yes 
apt-get install gcc --yes 
apt-get install libcairo2-dev --yes


cd /home/site/wwwroot

#export GIT_PYTHON_REFRESH=quiet
#export GIT_PYTHON_GIT_EXECUTABLE=\usr\local\bin

pip install Weblate==4.1.1
pip install django-redi
pip install mysqlclient
pip install whitenoise
gunicorn --bind=0.0.0.0 --workers=4 --timeout 3600 weblate.wsgi

**Comment by nijel** [comment]
Maybe you're mixing native Windows Python with Linux container? You don't seem to install pip in the container, so it probably sticks to using system one which then cannot find the Git binary installed in the container? Try installing `python3-pip` and then installing Weblate using it. You can also install optional deps in single command:

```
pip3 install Weblate[MySQL]==4.2.1
```
