### ISSUE TITLE
Automatic Translation in UI crashing

### ISSUE THREAD

**Issue by tsoslow** [WeblateOrg/weblate#4383]
**Describe the bug**

We get a failure when running Automatic Translation in the Weblate UI. The slider bar does not continue and, as the admin user, I get hundreds of error emails. 

This worked in version 4.1.1 and earlier. Upgrading to 4.2.1 has caused the error on our server. We are running the latest docker tag.

**To Reproduce**

1. Go to the language page of a component
2. Click on Tools -> Automatic Translation
3. We use:
 * Automatic translation mode: Add as translation
 * Search filter: Strings needing action
 * Automatic translation source: Machine translation
 * Machine translation engines: Weblate, Weblate Translation Memory, and Google Translate
 * Score threshold: 80
4. Click Apply
5. Slider bar does not move and errors stream into my email

**Expected behavior**

The progress bar should begin to move and strings should be translated.

**Server configuration and status**

DEBUG git: exec git --version [retcode=0]
DEBUG git: exec git --version [retcode=0]
DEBUG git: exec git review --version [retcode=0]
DEBUG git: exec git review --version [retcode=0]
DEBUG git: exec git svn --version [retcode=0]
DEBUG git: exec git svn --version [retcode=0]
DEBUG hub: exec hub --version [retcode=0]
DEBUG hub: exec hub --version [retcode=0]
DEBUG lab: exec lab --version [retcode=1]
DEBUG lab: exec lab --version [retcode=1]
DEBUG hg: exec hg version -q [retcode=0]
DEBUG hg: exec hg version -q [retcode=0]
DEBUG git: exec git config --global merge.weblate-merge-gettext-po.name Weblate merge driver for Gettext PO files [retcode=0]
DEBUG git: exec git config --global merge.weblate-merge-gettext-po.name Weblate merge driver for Gettext PO files [retcode=0]
DEBUG git: exec git config --global merge.weblate-merge-gettext-po.driver /usr/local/lib/python3.7/dist-packages/weblate/examples/git-merge-gettext-po %O %A %B [retcode=0]
DEBUG git: exec git config --global merge.weblate-merge-gettext-po.driver /usr/local/lib/python3.7/dist-packages/weblate/examples/git-merge-gettext-po %O %A %B [retcode=0]
DEBUG git: exec git config --global user.email noreply@weblate.org [retcode=0]
DEBUG git: exec git config --global user.email noreply@weblate.org [retcode=0]
DEBUG git: exec git config --global user.name Weblate [retcode=0]
DEBUG git: exec git config --global user.name Weblate [retcode=0]
 * Weblate: 4.2.1
 * Django: 3.1
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0
 * lxml: 4.5.2
 * Pillow: 7.2.0
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.1
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.4
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.16.5
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.7
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.5
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.14.47
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.1
 * Mercurial: 5.5
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * hub: 2.13.0
 * lab: 0.16
 * Redis server: 4.0.14
 * PostgreSQL server: 9.6.19
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: email-smtp.us-east-1.amazonaws.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.15.0-112-generic (x86_64)

**Weblate deploy checks**

DEBUG git: exec git --version [retcode=0]
DEBUG git: exec git --version [retcode=0]
DEBUG git: exec git review --version [retcode=0]
DEBUG git: exec git review --version [retcode=0]
DEBUG git: exec git svn --version [retcode=0]
DEBUG git: exec git svn --version [retcode=0]
DEBUG hub: exec hub --version [retcode=0]
DEBUG hub: exec hub --version [retcode=0]
DEBUG lab: exec lab --version [retcode=1]
DEBUG lab: exec lab --version [retcode=1]
DEBUG hg: exec hg version -q [retcode=0]
DEBUG hg: exec hg version -q [retcode=0]
DEBUG git: exec git config --global merge.weblate-merge-gettext-po.name Weblate merge driver for Gettext PO files [retcode=0]
DEBUG git: exec git config --global merge.weblate-merge-gettext-po.name Weblate merge driver for Gettext PO files [retcode=0]
DEBUG git: exec git config --global merge.weblate-merge-gettext-po.driver /usr/local/lib/python3.7/dist-packages/weblate/examples/git-merge-gettext-po %O %A %B [retcode=0]
DEBUG git: exec git config --global merge.weblate-merge-gettext-po.driver /usr/local/lib/python3.7/dist-packages/weblate/examples/git-merge-gettext-po %O %A %B [retcode=0]
DEBUG git: exec git config --global user.email noreply@weblate.org [retcode=0]
DEBUG git: exec git config --global user.email noreply@weblate.org [retcode=0]
DEBUG git: exec git config --global user.name Weblate [retcode=0]
DEBUG git: exec git config --global user.name Weblate [retcode=0]
System check identified some issues:

WARNINGS:
?: (weblate.W025.xwiki-fullpage) Failure in loading handler for xwiki-fullpage file format: module 'translate.storage.properties' has no attribute 'XWikiFullPage'
	HINT: https://docs.weblate.org/en/weblate-4.2.1/admin/install.html#optional-deps
?: (weblate.W025.xwiki-java-properties) Failure in loading handler for xwiki-java-properties file format: module 'translate.storage.properties' has no attribute 'xwikifile'
	HINT: https://docs.weblate.org/en/weblate-4.2.1/admin/install.html#optional-deps
?: (weblate.W025.xwiki-page-properties) Failure in loading handler for xwiki-page-properties file format: module 'translate.storage.properties' has no attribute 'XWikiPageProperties'
	HINT: https://docs.weblate.org/en/weblate-4.2.1/admin/install.html#optional-deps

INFOS:
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.2.1/admin/backup.html

System check identified 4 issues (1 silenced).

**Exception traceback**

Internal Server Error: /js/task/9748cb64-96eb-428b-90ad-3780591e2314/

TypeError at /js/task/9748cb64-96eb-428b-90ad-3780591e2314/
sequence item 1: expected a bytes-like object, UUID found

Request Method: GET
Request URL: https://weblate.OURDOMAIN.net/js/task/9748cb64-96eb-428b-90ad-3780591e2314/
Django Version: 3.1
Python Executable: /usr/bin/uwsgi-core
Python Version: 3.7.3
Python Path: ['/usr/local/lib/python3.7/dist-packages/git/ext/gitdb', '/', '/usr/local/lib/python3.7/dist-packages/', '.', '', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/app/data/python', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/gitdb/ext/smmap']
Server time: Tue, 25 Aug 2020 15:06:40 +0000
Installed Applications:
['customize',
'weblate.addons',
'weblate.auth',
'weblate.checks',
'weblate.formats',
'weblate.glossary',
'weblate.machinery',
'weblate.trans',
'weblate.lang',
'weblate.langdata',
'weblate.memory',
'weblate.screenshots',
'weblate.fonts',
'weblate.accounts',
'weblate.utils',
'weblate.vcs',
'weblate.wladmin',
'weblate',
'weblate.gitexport',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'django.contrib.admin.apps.SimpleAdminConfig',
'django.contrib.admindocs',
'django.contrib.sitemaps',
'django.contrib.humanize',
'social_django',
'crispy_forms',
'compressor',
'rest_framework',
'rest_framework.authtoken',
'django_filters']
Installed Middleware:
['weblate.middleware.RedirectMiddleware',
'weblate.middleware.ProxyMiddleware',
'django.middleware.security.SecurityMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'weblate.accounts.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
'social_django.middleware.SocialAuthExceptionMiddleware',
'weblate.accounts.middleware.RequireLoginMiddleware',
'weblate.api.middleware.ThrottlingMiddleware',
'weblate.middleware.SecurityMiddleware']

Traceback (most recent call last):
 File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
   response = get_response(request)
 File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 179, in _get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/integrations/django/views.py", line 52, in callback
   return old_callback(*args, **kwargs)
 File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
   return view_func(request, *args, **kwargs)
 File "/usr/local/lib/python3.7/dist-packages/weblate/trans/views/js.py", line 242, in task_progress
   result = task.result
 File "/usr/local/lib/python3.7/dist-packages/celery/result.py", line 447, in result
   return self._get_task_meta()['result']
 File "/usr/local/lib/python3.7/dist-packages/celery/result.py", line 423, in _get_task_meta
   return self._maybe_set_cache(self.backend.get_task_meta(self.id))
 File "/usr/local/lib/python3.7/dist-packages/celery/backends/base.py", line 523, in get_task_meta
   meta = self._get_task_meta_for(task_id)
 File "/usr/local/lib/python3.7/dist-packages/celery/backends/base.py", line 878, in _get_task_meta_for
   meta = self.get(self.get_key_for_task(task_id))
 File "/usr/local/lib/python3.7/dist-packages/celery/backends/base.py", line 761, in get_key_for_task
   self.task_keyprefix, key_t(task_id), key_t(key),

Exception Type: TypeError at /js/task/9748cb64-96eb-428b-90ad-3780591e2314/
Exception Value: sequence item 1: expected a bytes-like object, UUID found

**Additional context**

We're using the latest docker build. This is the first time that I've noticed all of the debug messaging. It's also the first time we've had warnings for xwiki. I'm wondering if there was a bad build for docker.

**Comment by nijel** [comment]
This is bug in Celery, see https://github.com/celery/celery/issues/6164. I'm seeing it time to time as well, but I'm not able to reproduce it reliably...

**Comment by Koubek** [comment]
We are facing the same problem. We are not able to access translation UI and I can see the same errors (didn't see before):

```
weblate.W025.xwiki-java-properties | Failure in loading handler for xwiki-java-properties file format: module 'translate.storage.properties' has no attribute 'xwikifile'

weblate.W025.xwiki-page-properties | Failure in loading handler for xwiki-page-properties file format: module 'translate.storage.properties' has no attribute 'XWikiPageProperties'

weblate.W025.xwiki-fullpage | Failure in loading handler for xwiki-fullpage file format: module 'translate.storage.properties' has no attribute 'XWikiFullPage'
```

```
 * Weblate: 4.2.1
 * Django: 3.1
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0
 * lxml: 4.5.2
 * Pillow: 7.2.0
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.1
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.4
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.16.5
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.7
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.5
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.14.47
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.1
 * Mercurial: 5.5
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * hub: 2.13.0
 * lab: 0.16
 * Redis server: 5.0.9
 * PostgreSQL server: 11.9
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.3.0-1032-azure (x86_64)
```

**Comment by Koubek** [comment]
And we also use machine translations (automatic translations) with a similar setup, but instead of Google Translator we use Azure Translation services.

What I notice today by checking changes in the repo, the files are a bit weird now (those auto-translated).

A file that wasn't auto-translated (only the trailing part in the end of the document):
```
        <trans-unit id="XmlPort 947373062 - Property 2879900210" size-unit="char" translate="yes" xml:space="preserve">
          <source>Get Loyalty Receipt List</source>
          <target>Obtenir la liste des reçus de fidélité</target>
          <note from="Developer" annotates="general" priority="2"/>
          <note from="Xliff Generator" annotates="general" priority="3">XmlPort MM Get Loyalty Receipt List - Property Caption</note>
        </trans-unit>
        <trans-unit id="XmlPort 966973832 - Property 2879900210" size-unit="char" translate="yes" xml:space="preserve">
          <source>Reset Account Password</source>
          <target>Réinitialiser mot de passe de compte</target>
          <note from="Developer" annotates="general" priority="2"/>
          <note from="Xliff Generator" annotates="general" priority="3">XmlPort M2 Reset Account Password - Property Caption</note>
        </trans-unit>
      </group>
    </body>
  </file>
</xliff>
```

For a translated (auto-translated) file it's different, the tag ```<group />``` ends somewhere in the middle of the document and the new translation units are added after that element:
```
        <trans-unit id="XmlPort 966973832 - Property 2879900210" size-unit="char" translate="yes" xml:space="preserve">
          <source>Reset Account Password</source>
          <target>Wachtwoord opnieuw instellen</target>
          <note from="Developer" annotates="general" priority="2"/>
          <note from="Xliff Generator" annotates="general" priority="3">XmlPort M2 Reset Account Password - Property Caption</note>
        </trans-unit>
      </group>
      <trans-unit id="Codeunit 1100175395 - NamedType 2008153173" size-unit="char" translate="yes" xml:space="preserve">
          <source>No input Node found.</source>
        <target>Er is geen inputknooppunt gevonden.</target>
        <note from="Developer" annotates="general" priority="2"/>
        <note from="Xliff Generator" annotates="general" priority="3">Codeunit CS Rfid Shipping List - NamedType Text006</note>
      </trans-unit>
      <trans-unit id="Codeunit 1100175395 - NamedType 2476940767" size-unit="char" translate="yes" xml:space="preserve">
          <source>Function not Found.</source>
        <target>Functie is niet gevonden.</target>
        <note from="Developer" annotates="general" priority="2"/>
        <note from="Xliff Generator" annotates="general" priority="3">Codeunit CS Rfid Shipping List - NamedType Text000</note>
      </trans-unit>
```

And this is how this document looks like at the end of the document:
```
      <trans-unit id="Table 3649642816 - Field 2961552353 - Property 2879900210" size-unit="char" translate="yes" xml:space="preserve">
          <source>Name</source>
        <target>Naam</target>
        <note from="Developer" annotates="general" priority="2"/>
        <note from="Xliff Generator" annotates="general" priority="3">Table NpRv Sales Line - Field Name - Property Caption</note>
      </trans-unit>
      <trans-unit id="Table 54082414 - Field 145988851 - Property 2879900210" size-unit="char" translate="yes" xml:space="preserve">
          <source>Ticket Full Description</source>
        <target>Ticket objectbeschrijving</target>
        <note from="Developer" annotates="general" priority="2"/>
        <note from="Xliff Generator" annotates="general" priority="3">Table TM Ticket Setup - Field Ticket Full Description - Property Caption</note>
      </trans-unit>
    </body>
  </file>
</xliff>                  
```

Not sure if this is related somehow with the problems we are facing now but the issues started basically shortly after auto-translation was executed.

**Comment by nijel** [comment]
@Koubek You seem to be mixing different issues here. For XLIFF groups, please see https://github.com/WeblateOrg/weblate/issues/2482
