### ISSUE TITLE
Component error

### ISSUE THREAD

**Issue by remyahalza** [WeblateOrg/weblate#4387]
When i upload a component, i got like this.

Instead of these link i need values
http://weblate.halza.com/translate/halzadotcom/halza-faq/en/?type=all&offset=4

**Comment by nijel** [comment]
The site seems misconfigured, it's using old CSS files with current code and that looks ugly. Please see https://docs.weblate.org/en/latest/admin/upgrade.html for upgrading instructions.

You seem to be using xliff and Weblate just displays whatever is in the xliff file....
