### ISSUE TITLE
One language of a component is not updated

### ISSUE THREAD

**Issue by iGormilhit** [WeblateOrg/weblate#4389]
**Describe the issue**

We're using a free plan on hosted.weblate.org. Inside [one project](https://hosted.weblate.org/projects/rero_plus/), we have many component, corresponding to the backend, frontend, a shared library between two of our web applications that we're developing. We're still looking for the workflow that fits our need.

Our (main) issue, is in one of our components ([rero-ils](https://hosted.weblate.org/projects/rero_plus/rero-ils/)). As I set up the component, I choosed the `dev` branch as a repository branch ([GitHub project](https://github.com/rero/rero-ils), and tried the continuous translation workflow, which worked nearly as expected, exept that sometimes we've lost translations. After a lot of searching and thinking, I decided to deactivate the continuous workflow and to create a dedicated branch on GitHub for translations.

So I created this branch from the `dev` on, extracted new messages and updated the translations files (catalogs), committed the changes, pushed it on the remote repository (GitHub). Then, on weblate, in the component repository settings, I've changed the repository branch from `dev` to `translations`. The component went through the updating process. I actually noticed that, on the web interface, no logs where displayed about this process. So I did nothing until the next morning.

The next morning, the updating process seemed finished, and I looked for the new strings to be translated. To my surprise, I could find them in any languages but the French. And I can't understand why. The strings are in the translations files, either in the GitHub branch or in the weblate git repository, as seen on my local machine.

Two examples:

- `performer` (a contributor role when describing a bibliographic document): [on GitHub, French translation file](https://github.com/rero/rero-ils/blob/translations/rero_ils/translations/fr/LC_MESSAGES/messages.po#L4930), the [search for this string on weblate](https://hosted.weblate.org/search/rero_plus/rero-ils/?offset=1&q=source%3Aperformer&sort_by=-priority%2Cposition&checksum=). As you can see, the string is on GitHub, and in weblate in each language, but not in French.
- `new_acquisition`: [on GitHub, French translation file](https://github.com/rero/rero-ils/blob/translations/rero_ils/translations/fr/LC_MESSAGES/messages.po#L72), the [search for this string on weblate](https://hosted.weblate.org/search/rero_plus/rero-ils/?offset=1&q=source%3Anew_acquisition&sort_by=-priority%2Cposition&checksum=).

And this is the case for all the strings that have been extracted after the creation of the dedicated `translations` branch. What strikes me is that they are missing only in French.

I suspect that I did something wrong, but can't find out what, and moreover I don't know how to fix this. Of course, I will glady share further information, if needed.

**To Reproduce**

I don't know how to reproduce my situation.

**Expected behavior**

I expected all languages to be in the same state.

**Additional information**

The git log of the weblate repository, cloned locally and updated:

```
* d7555c8 (HEAD -> translations, origin/translations) translations: translate (French)
* 996236a translations: extract strings & update catalogs
* 25b12f3 circulation: fix validate request return type
* 985921a (origin/dev, origin/HEAD, dev) help: update the public help menu entry url
* 9d54c6c acquisition: update item/doc for new acquisition
* 3ec0b3b permission: refactoring the loan permission factory
```
As you can see, it exactly the same as the `translations` branch history on GitHub: https://github.com/rero/rero-ils/commits/translations

**Comment by nijel** [comment]
There seem to be some issue in background translation parsing during the last week. The issue should be now fixed and the string is properly listed there.
