### ISSUE TITLE
Add all CRUD REST API operations at the units endpoint

### ISSUE THREAD

**Issue by superDross** [WeblateOrg/weblate#4394]
**Is your feature request related to a problem? Please describe.**

I would like to be able to create update & delete a translation unit via a REST API request.

**Describe the solution you'd like**
PUT, POST, PATCH & DELETE operations available at `/api/units/(int: id)/`

**Describe alternatives you've considered**

For updating translation units I tried:

GET request `api/translations/<project>/<component>/<language>/file/`, modify entry of interest, and POST to `api/translations/<project>/<component>/<language>/file/` to overwrite the file.

This works but there are potential race conditions to consider with this approach if another person is adding/editing a translation present in that language. 

One way to get around this is to lock the component, but that could be very disruptive.

**Comment by nijel** [comment]
The delete part depends on https://github.com/WeblateOrg/weblate/issues/1974
