### ISSUE TITLE
Update unit using API

### ISSUE THREAD

**Issue by KadAnna** [WeblateOrg/weblate#4396]
**Is your feature request related to a problem? Please describe.**
I am migrating current localization to Weblate - I want to transfer also the metadata to strings plus I need to do some adjustments as the weblate set-up is different.

**Describe the solution you'd like**
via API, I need to be able to:
- tick off "needs editing" at a string
- set flag "read-only" at the string in source list
- set a commnent in "explanation"

**Describe alternatives you've considered**

**Additional context**

**Comment by nijel** [comment]
Should be done after https://github.com/WeblateOrg/weblate/issues/4020 which will probably change way we link to the source strings.
