### ISSUE TITLE
Adding new language results in error and untracked file

### ISSUE THREAD

**Issue by metanerd** [WeblateOrg/weblate#4408]
I am trying to add a new language to an existing component in a project. I already did so with 2 other components in the same project and it worked just fine. 

**To Reproduce**

1. Go to https://translate.mattermost.com/new-lang/mattermost/mattermost-mobile_master/
2. Select any language
3. Click save
5. See untracked language file in repository maintenance settings

**Expected behavior**

Language gets added

**Screenshots**

**Server configuration and status**

**Weblate deploy checks**

**Exception traceback**

**Additional context**

**Comment by nijel** [comment]
This is caused bug in data migration in the 4.2 release. It wrongly migrated IDs for the strings JSON files and Weblate now can not find matching source strings.
