### ISSUE TITLE
Dockerized dev version won't run if env var WEBLATE_SITE_DOMAIN is not set 

### ISSUE THREAD

**Issue by vladox** [WeblateOrg/weblate#4413]
**Describe the bug**

Dockerized dev version won't run if env var WEBLATE_SITE_DOMAIN is not set 

**To Reproduce**

1. Run `./rundev.sh` on project root
2. Wait for docker-compose to build & run dockerized setup'
3. See error `dev-docker_weblate_1 exited with code 1`

**Expected behavior**

docker-compose runs and site is available on `http://127.0.0.1:8080/`

error on docker-compose log:

`weblate_1   | Missing WEBLATE_SITE_DOMAIN, please configure it`

**Comment by nijel** [comment]
IMHO fixed by #4412
