### ISSUE TITLE
Add plain text file format support [$200]

### ISSUE THREAD

**Issue by KazamaSion** [WeblateOrg/weblate#4429]
**Is your feature request related to a problem? Please describe.**
Currently, I can use "Simple CSV file" instead, but the file downloaded is ended with ".csv" instead of ".txt".  
Transifex has been supporting plain text format for years.  
![image](https://user-images.githubusercontent.com/13185633/92027516-3e56b000-ed95-11ea-9484-9e6c66a72194.png)

**Describe the solution you'd like**
Add a new file format.  

**Additional context**
TXT file format is simple: 1 line = 1 string  

Example:  
```
This is the text for submitting app descriptions into Google Play.

# One of the best rated messaging apps on Play Store #
# More than 20 million downloads #

The features we have are:
- xxxx
- xxxx
```

![image](https://user-images.githubusercontent.com/13185633/92028225-45ca8900-ed96-11ea-9d6e-07bef0a0ca2b.png)

**Comment by brymut** [comment]
Hi @nijel, is this available for anyone to try out?

**Comment by nijel** [comment]
I don't know that anybody would be working on this.

**Comment by bl00mber** [comment]
@nijel can you please confirm the shape of the test.

```py
# cs.txt
Hello, world!
Ahoj světe!
Thank you for using Weblate.
Děkujeme za použití Weblate.

class TXTFormatTest(AutoFormatTest):
    FORMAT = TXTFormat
    FILE = TEST_TXT
    BASE = TEST_TXT
    MIME = "text/plain"
    COUNT = 2
    EXT = "txt"
    MASK = "txt/*.txt"
    EXPECTED_PATH = "txt/cs_CZ.txt"
    MATCH = "Hello, world!\n"
    FIND = "Thank you for using Weblate."
    FIND_MATCH = "Děkujeme za použití Weblate."
    NEW_UNIT_MATCH = b'\nSource string\n'
    EXPECTED_FLAGS = ""
```

**Comment by nijel** [comment]
It looks good, you will probably have to introduce line numbers as context in order to be able to serialize correctly and FIND_CONTEXT will be needed then as well.
