### ISSUE TITLE
Migration fails from Weblate 3.11 to 4.2

### ISSUE THREAD

**Issue by Ereza** [WeblateOrg/weblate#4436]
**Describe the bug**

I had a Weblate 3.11 installation and tried upgrading it to 4.2. However, the described migration error occurred. 
I then removed all Docker containers, images and volumes and did a clean install of Weblate 4.2, then restored a database backup from Weblate 3.11 (the backup was done before attempting the upgrade), expecting that it would run all the needed migrations. However, the exact same error happens. Also, the error indicates that I should upgrade to 3.0.1-7 first, which is wrong, because I am on 3.11.

**To Reproduce**

1. Have an install of Weblate 3.11
2. Upgrade to Weblate 4.2 (docker-composer pull)
3. See error

Alternately:
1. Have a clean install of Weblate 4.2
2. Restore a database from Weblate 3.11
3. See error

**Expected behavior**

There should be no migration error.

**Server configuration and status**

 * Weblate: 4.2.2
 * Django: 3.1.1
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0
 * lxml: 4.5.2
 * Pillow: 7.2.0
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.1
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.16.5
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.7
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.5
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.14.53
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.1
 * Mercurial: 5.5.1
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * hub: 2.13.0
 * lab: 0.16
 * Redis server: 6.0.7
 * PostgreSQL server: 12.4
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.gmail.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.19.0-10-amd64 (x86_64)

**Weblate deploy checks**

Cannot provide it, container does not start.

**Exception traceback**
```
weblate_1   | System check identified some issues:
weblate_1   | 
weblate_1   | WARNINGS:
weblate_1   | ?: (weblate.W025.xwiki-fullpage) Failure in loading handler for xwiki-fullpage file format: module 'translate.storage.properties' has no attribute 'XWikiFullPage'
weblate_1   | 	HINT: https://docs.weblate.org/en/weblate-4.2.2/admin/install.html#optional-deps
weblate_1   | ?: (weblate.W025.xwiki-java-properties) Failure in loading handler for xwiki-java-properties file format: module 'translate.storage.properties' has no attribute 'xwikifile'
weblate_1   | 	HINT: https://docs.weblate.org/en/weblate-4.2.2/admin/install.html#optional-deps
weblate_1   | ?: (weblate.W025.xwiki-page-properties) Failure in loading handler for xwiki-page-properties file format: module 'translate.storage.properties' has no attribute 'XWikiPageProperties'
weblate_1   | 	HINT: https://docs.weblate.org/en/weblate-4.2.2/admin/install.html#optional-deps
weblate_1   | WARNING Handled exception: NodeNotFoundError: Migration weblate_auth.0008_auto_20200611_1232 depends on nonexistent node ('weblate_auth', '0007_group_components'). Django tried to replace migration weblate_auth.0007_group_components with any of [weblate_auth.0002_auto_20180507_1540_squashed_0011_auto_20180509_0739_squashed_0007_group_components] but wasn't able to because some of the replaced migrations are already applied.
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/loader.py", line 255, in build_graph
weblate_1   |     self.graph.validate_consistency()
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/graph.py", line 195, in validate_consistency
weblate_1   |     [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/graph.py", line 195, in <listcomp>
weblate_1   |     [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/graph.py", line 58, in raise_error
weblate_1   |     raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
weblate_1   | django.db.migrations.exceptions.NodeNotFoundError: Migration weblate_auth.0008_auto_20200611_1232 dependencies reference nonexistent parent node ('weblate_auth', '0007_group_components')
weblate_1   | 
weblate_1   | The above exception was the direct cause of the following exception:
weblate_1   | 
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/bin/weblate", line 8, in <module>
weblate_1   |     sys.exit(main())
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/runner.py", line 32, in main
weblate_1   |     execute_from_command_line(argv)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
weblate_1   |     utility.execute()
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 395, in execute
weblate_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 330, in run_from_argv
weblate_1   |     self.execute(*args, **cmd_options)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 371, in execute
weblate_1   |     output = self.handle(*args, **options)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/showmigrations.py", line 50, in handle
weblate_1   |     return self.show_plan(connection, options['app_label'])
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/showmigrations.py", line 111, in show_plan
weblate_1   |     loader = MigrationLoader(connection)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/loader.py", line 53, in __init__
weblate_1   |     self.build_graph()
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/loader.py", line 280, in build_graph
weblate_1   |     ) from exc
weblate_1   | django.db.migrations.exceptions.NodeNotFoundError: Migration weblate_auth.0008_auto_20200611_1232 depends on nonexistent node ('weblate_auth', '0007_group_components'). Django tried to replace migration weblate_auth.0007_group_components with any of [weblate_auth.0002_auto_20180507_1540_squashed_0011_auto_20180509_0739_squashed_0007_group_components] but wasn't able to because some of the replaced migrations are already applied.
weblate_1   | 
weblate_1   | Migration from this version is not supported!
weblate_1   | Please upgrade to 3.0.1-7 first.
weblate_weblate_1 exited with code 1
```

**Additional context**

Weblate run with Docker. However, I am not that familiar with Docker nor any of Weblate's internal components, so it's possible I did something wrong at some moment.

**Comment by nijel** [comment]
You need to upgrade to 4.0 or 4.1 first, see https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-3-x

I've just adjusted the error message to give correct hint in this case.

**Comment by Ereza** [comment]
You are absolutely right! Upgrading from 3.11 to 4.0.4 and then to 4.2 completely fixed the problem.

Thanks a lot and sorry for taking some of your time, my bad! I'll close the issue now.
