### ISSUE TITLE
Language Custom is not working in bulk-edit.

### ISSUE THREAD

**Issue by aoisensi** [WeblateOrg/weblate#4441]
**Describe the bug**

Language Custom is not working in bulk-edit.
You cannot filter with `language:` parameter.

**To Reproduce**

I tried to add the "read-only" flag with "Bulk-edit" to one language.

Before:
![image](https://user-images.githubusercontent.com/1350990/92271665-2ca31300-ef23-11ea-95d8-2f7d18e09deb.png)

Edit:
![image](https://user-images.githubusercontent.com/1350990/92271708-404e7980-ef23-11ea-9220-ba84f3af3b03.png)

After:
![image](https://user-images.githubusercontent.com/1350990/92271760-55c3a380-ef23-11ea-898e-f1be90a4f467.png)

**Server configuration and status**

```
 * Weblate: 4.2.2
 * Django: 3.1.1
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0
 * lxml: 4.5.2
 * Pillow: 7.2.0
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.1
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.16.5
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.7
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.5
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.14.53
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.1
 * Mercurial: 5.5.1
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * hub: 2.13.0
 * lab: 0.16
 * Redis server: 6.0.7
 * PostgreSQL server: 12.4
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.mailgun.org
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.7.4-arch1-1 (x86_64)
```

**Comment by nijel** [comment]
The flags are always set on the source, not on the translations, see https://docs.weblate.org/en/latest/admin/checks.html#customizing-behavior

**Comment by aoisensi** [comment]
Thank you for response.
However, the official Weblate translation project is read-only in English only.
How are you doing?

**Comment by nijel** [comment]
The source language can be read only. In case of bilingual translations (what Weblate use), there is no other way as the source strings are extracted from the source code and cannot be edited in Weblate. For monolingual translations there is option to disable that - https://docs.weblate.org/en/latest/admin/projects.html#edit-base-file.

If you don't want some languages to be translated in Weblate, you can use language filter, see https://docs.weblate.org/en/latest/admin/projects.html#language-filter

**Comment by aoisensi** [comment]
Thank you!
I was able to do what I wanted to do!
