### ISSUE TITLE
Allow registered users to create new translation projects without admin involvement

### ISSUE THREAD

**Issue by Bubu** [WeblateOrg/weblate#4450]
**Describe the issue**
My usecase/goal is to run a weblate instance for multiple foss android apps. This involves users signing up for the instance and creating and managing their own projects but not other projects they don't own. So far I've not found a good way to do that.

I've ended up enabling the billing component and create an empty billing plan and then an empty billing for every user on the instance. At that point they were able to create translation projects. Unfortunately those projects then weren't associated to the billing and the user couldn't set the project as public without me fixing that from the admin interface.

Is there some other way than the billing module to achieve what I need?

(Using weblate version 4.2.2)

**Comment by nijel** [comment]
When billing is enabled and user has billing the created project should be associated with it automatically - the project creation form should automatically select the billing in case user has only one (that's what we use at Hosted Weblate).

But you don't need billing when you don't want to enforce some limits on the user created projects. All you need is to grant users "Add new projects" permission.

**Comment by Bubu** [comment]
> But you don't need billing when you don't want to enforce some limits on the user created projects. All you need is to grant users "Add new projects" permission.

I think I got this working now instead. Thanks a lot for the pointer, the docs only mentioned the billing module for non-admin users being able to create new projects.

**Comment by nijel** [comment]
I've clarified the docs in abdd6b727886d80b40cdcc5264362c4bfba7d08a
