### ISSUE TITLE
issue of user list sorting

### ISSUE THREAD

**Issue by baffclan** [WeblateOrg/weblate#4452]
**Describe the bug**
issue of user list sorting

**To Reproduce**

1. Open Weblate user page
     https://hosted.weblate.org/user/
2. Cange Date_Join Old->New
     https://hosted.weblate.org/user/?q=&sort_by=date_joined
   Topest user is @nijel
3. Goto Page bottom, and click [>|]
   list number is 472/472
   Last user is @nijel
   url is https://hosted.weblate.org/user/?page=472&limit=50
  lost a "sort_by=date_joined"

**Expected behavior**
Opens 
https://hosted.weblate.org/user/?page=472&limit=50&sort_by=date_joined

**Additional context**
Reproduce with Weblate 4.3-dev
Similar to 4369.

**Comment by prashant-tholia** [comment]
Hi, I'd like to work on this issue.

**Comment by nijel** [comment]
@prashant-tholia you're welcome, I've just assigned this issue to you.

**Comment by prashant-tholia** [comment]
@nijel Thanks.

**Comment by baffclan** [comment]
Cannot reproduce this problem.
Thanks for fixing this!

Er, another one.
Editing a position counter will cause a sort option to be lost.
See #4369


BElluu said:
 I can look at this :)

**Comment by nijel** [comment]
Fixed in 2b00a24dcf, thanks for pointing out.
