### ISSUE TITLE
Search, filter or group by source string location

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#4457]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to detect all string sources in order to know whether I should translate them or not.
In Hebrew it's better to leave CLI strings untranslated because the different terminals are having a hard time displaying the characters or diplaying it in the right direction so finding all the strings for a certain file can really save me time and make sure I'm not mistaken.

**Describe the solution you'd like**
I would like a feature to either group all the strings which are related to a certain file or the ability to filter/search by source string location.

**Describe alternatives you've considered**
I can look at the source file and search these manually but I think it's too tedious.

**Additional context**
It can also help with screenshot context in the future.

**Comment by nijel** [comment]
`location:xxx` search should do that, see https://docs.weblate.org/en/latest/user/search.html

**Comment by yarons** [comment]
Yup, sorry, thanks.

**Comment by WofWca** [comment]
What about sorting / grouping? I know a string can have several locations, but sorting should be possible anyway, I think?

**Comment by nijel** [comment]
Added in 02a2eb3bad6318cf081e7d32cae4833046d5ab1d
