### ISSUE TITLE
IDML Translation & InDesign XML Tags

### ISSUE THREAD

**Issue by draganstudios** [WeblateOrg/weblate#4468]
Hi there,

We are doing some testing with Weblate 4.2.1 and using the Adobe InDesign Markup Language (IDML) files.  We understand IDML support was recently added and it's still in beta. 

While we are still learning and discovering Weblate, we were able to successfully import the IDML file, translate it, and download the translated version. Works great!

My question is about the InDesign XML tags that are visible in the textarea for translators. Is this the expected behavior? 

`<x id="22" xid="idPkg:Story[0]/{}Story[0]/{}ParagraphStyleRange[1]/{}CharacterStyleRange[4]/{}Br[0]"/><x id="23" xid="idPkg:Story[0]/{}Story[0]/{}ParagraphStyleRange[1]/{}CharacterStyleRange[4]/{}Br[1]"/></g>`

(Ignore the encoding issues, we are looking into that, assuming that's on us to configure properly.)
![idml-translation](https://user-images.githubusercontent.com/1308229/92510506-f5aa5700-f1d9-11ea-9b48-744022353eac.png)

Is there a way to manage these InDesign XML tags? We understand that some tags are needed, e.g. a tag to indicate bold or italic in the middle of a string, but we are concerned that the translator might accidentally delete a tag and break it.

![idml-xml-error](https://user-images.githubusercontent.com/1308229/92510560-0955bd80-f1da-11ea-9a02-8d33ffe313f3.png)

Unfortunately I was not able to find much documentation about IDML support, or how to properly configure them, so this could be totally on our side. If you can point me to the right direction, that would be much appreciated.

If there is a way to improve it, we are open to help and contribute back to the project.

Thank you for your help,
D.

**Comment by nijel** [comment]
I think the code just takes the inner XML and presents it to the translator. However, I have no knowledge of IDML format either... The code for it is in https://github.com/translate/translate/blob/master/translate/storage/idml.py and https://github.com/translate/translate/blob/master/translate/storage/xml_extract/extract.py.

Weblate [XML markup check](https://docs.weblate.org/en/latest/user/checks.html#xml-markup) should be able to catch this and report properly to the translator. You can configure it as [enforcing check](https://docs.weblate.org/en/latest/admin/checks.html#enforcing-checks) to mark such strings as needing review, but that still won't prevent Weblate from saving it. This might be addressed by https://github.com/WeblateOrg/weblate/issues/3745, but it's currently not on our roadmap.

**Comment by draganstudios** [comment]
Hi @nijel ,

Thank you for your reply! We'll take a look at the code and see what we can do.

We are still looking into the encoding issue with IDML files. We have tried JSON files with no issues, the files are encoded perfectly, but with IDML we're still experiencing issues. We'll keep looking...

Thanks again and have a great day,
D.
