### ISSUE TITLE
Condensed Zen mode redux

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4476]
I think this could improve quality
![bilde](https://user-images.githubusercontent.com/13802408/92668388-f8f32f00-f30e-11ea-9c65-d6976fe086f8.png)
vs
![bilde](https://user-images.githubusercontent.com/13802408/92668373-ee389a00-f30e-11ea-9681-e2108e94ef47.png)

The longest language codes are probably something like Klingon, but it stands to reason the user knows these languages, and see them often enough not to need the full name. Removing it removes entropy, and it increases the dataflow in the focal point of view. Additionally it allows more strings to be on screen above and below the string in question.

Right now on small screens it is a hard tradeoff between the amount of other languages, and the amount of nearby strings in view.

Edit: Seems more involved, but to have everything consistent
![bilde](https://user-images.githubusercontent.com/13802408/92669095-deba5080-f310-11ea-85ae-365eaebc2c08.png)

A bit cramped, but the Zen mode is the get it done mode. Distance between the source and translation is the most important thing to have. Sizes of icons are the same as the "needs editing" checkbox.

Could be people start translating in the wrong language more if this is implemented (?)

Problem to solve in similar vein to https://github.com/WeblateOrg/weblate/issues/2817
Edit2: I found the one I thought I had made https://github.com/WeblateOrg/weblate/issues/2766
where the problem was seemingly fixed, but only by adjusting margins.

**Comment by nijel** [comment]
The language names in left column were present since 7e8498a9be67662a55347352448f0494227fab0f, but it was reverted later in 356eac5111d0ed70021645af98af1ab84e106f3e because it breaks for longer language names. Using language codes as you propose here would address this, but the question is whether users are familiar with these.

**Comment by comradekingu** [comment]
Language codes is (partly) how languages are added to the component already
![bilde](https://user-images.githubusercontent.com/13802408/92938694-2e059b80-f44d-11ea-8efc-c9a44975dab6.png)

However they are not present when adding secondary languages
![bilde](https://user-images.githubusercontent.com/13802408/92938682-29d97e00-f44d-11ea-9bd6-651cd195c0b1.png)

However the language names themselves are right there in the regular editor, which is visited regularly
![bilde](https://user-images.githubusercontent.com/13802408/92939171-bc7a1d00-f44d-11ea-8b43-af77e0dbafbb.png)

I don't actually look at the language names much, as it is evident from looking at the strings what languages they are, and they are always in the same order. Try visually scanning all languages in the two first pictures of the first-post.

In terms of typography, 400-600% line-spacing is far off anything. Books and dictionaries all use about the same arrangement at ~140%, and it is a marked readability improvement to get it just right. (Second image is something like 170%)
https://practicaltypography.com/line-spacing.html
https://www.justinmind.com/blog/best-ux-practices-for-line-spacing/
(The Matrix mode is at about 250%)

The strong point of the Zen mode is to have a continuous flow of translations wrt. regular mode.
The Tetris-view helps a lot, and doing condensed Zen would mean more people get to benefit. This only concerns people that have added secondary languages, and of those mainly the ones with many. 280px to be saved for me, for every string.
The vertical space to unlock and readability to gain is just the bigger concern, so it is a question of how to best do it. The trade-off is a bit of difficulty learning the language codes, for languages the user added. If anything it teaches people the language codes (?)

There could be a mouseover for what the full format language name is?

**Comment by comradekingu** [comment]
POeditor hides the "string key" entirely, and it is only available on mouseover

![bilde](https://user-images.githubusercontent.com/13802408/98274129-f584c880-1f8a-11eb-9fa0-6b31ff788ac0.png)
I think that makes sense, as only rarely are string keys in question. They serve some purpose being always available, but I think
the additional space far outweighs that ability.

The buttons are also shown inline, though at the wrong side wrt. functionality.

I think it is possible to get away with some arrangement of:
![bilde](https://user-images.githubusercontent.com/13802408/98274740-b5721580-1f8b-11eb-949e-a96ac33ce860.png)
