### ISSUE TITLE
Add support of regex in placeholders

### ISSUE THREAD

**Issue by Heziode** [WeblateOrg/weblate#4483]
**Is your feature request related to a problem? Please describe.**
Sometimes, we can have many placeholders that have a similar structure.
Example:

> Hello `{name}`, you hare a `{gender}`, living in `{location}`. It is `{time}`…

**Describe the solution you'd like**

Instead of adding every similar placeholders, it can be useful to use a regex: `placeholders:r"(\{[^\}]+\})"`

**Describe alternatives you've considered**
Manually add every placeholders, that can be time consuming.

**Additional context**
This can be see as an addition of placeholders already supported by a specific format.

**Comment by nijel** [comment]
Maybe it's good idea to support most common ones directly instead of forcing users to invent an regexp for this. For example there already is https://docs.weblate.org/en/latest/user/checks.html#percent-placeholders

**Comment by Heziode** [comment]
For example, my use case:

I use GetText format to get support of an l10n platform (Weblate). However, I use the syntax of [vue-i18n](https://kazupon.github.io/vue-i18n/), because I use it. And in my tool chain, after getting translation from weblate, I convert it to vue-i18n json format.

I think it's a good idea to let the user to add custom regex to manage special cases, instead of adding all l10n format of the world.

**Comment by nijel** [comment]
I don't say we should support all formats, but the most common ones. For most users it's way easier to add flag enabling specific format instead of crafting regex to do so. In the end the built-in checkers are basically just a class wrapping regex:

https://github.com/WeblateOrg/weblate/blob/41a81b6c61269a1c2b4ba9f9cd6726923704836b/weblate/checks/format.py#L532-L536

**Comment by nijel** [comment]
I've just added Vue I18n formatting check in d4fc3ba88075af8fd9682eb70042e85cba1bf708.

**Comment by Heziode** [comment]
@nijel, you have forgot [Linked locale messages](https://kazupon.github.io/vue-i18n/guide/messages.html#linked-locale-messages).

**Comment by Heziode** [comment]
> flag enabling specific format

Have you a link to the doc ? I haven't seen this part.

**Comment by nijel** [comment]
> you have forgot Linked locale messages.

Because it's not covered by the [formatting docs](https://kazupon.github.io/vue-i18n/guide/formatting.html)...

> Have you a link to the doc ? I haven't seen this part.

See https://docs.weblate.org/en/latest/user/checks.html#formatted-strings
