### ISSUE TITLE
Plural count and formula not saved on reboot for built-in locales

### ISSUE THREAD

**Issue by TruffeCendree** [WeblateOrg/weblate#4487]
**Describe the bug**

Plural count and formula not saved on reboot for built-in locales.

**To Reproduce**

- Edit a locale (eg. French) with the following settings : plural count: 3, plural formula: `(n == 0) ? 0 : (n == 1 ? 1 : 2)`
- Restart the weblate instance (ex. docker-compose restart weblate)
- French plural count and formula are restored to defaults.

Please note that I created a new locale (fr_US). For this locale, count and formula are persisted after reboot.

**Screenshots**

![image](https://user-images.githubusercontent.com/4479304/92878502-75b80300-f40c-11ea-8294-10fbbc915bca.png)

**Server configuration and status**

 * Weblate: 4.2.2
 * Django: 3.1.1
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0
 * lxml: 4.5.2
 * Pillow: 7.2.0
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.1
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.16.5
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.7
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.5
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.14.53
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.1
 * Mercurial: 5.5.1
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * hub: 2.13.0
 * lab: 0.16
 * Redis server: 4.0.14
 * PostgreSQL server: 11.9
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: 127.0.0.1
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.3.0-1035-aws (x86_64)

**Comment by nijel** [comment]
The shipped language definitions are always synced on container startup using [setuplang](https://docs.weblate.org/en/latest/admin/management.html#setuplang).

The language and plurals definitions are built on expectation that either file format includes the plural definition and if not, it sticks to CLDR.

**Comment by dada-amater** [comment]
Our plugin uses eval() for plural formula. It is written in PHP. We need to put brackets to the formula manually. Every time we reboot the service, we need to change it again. Is it possible to skip `setuplang` on reboot?

**Comment by nijel** [comment]
@dada-amater  patches are welcome to make it configurable. Asking same question on several places is not that welcome.

> Our plugin uses eval() for plural formula. It is written in PHP. 

Your plugin is broken if it needs changing plural formula from Gettext. Use something that handles it correctly. For example, https://github.com/phpmyadmin/motranslator does it properly and safely (without using eval).

**Comment by nijel** [comment]
Revising this again and I think found the issue. There is implicit setuplang invocation on database migration which is supposed to add newly defined languages and not updating existing ones. This flag is however not honored for plurals, so these are updated always...
