### ISSUE TITLE
Download translation file as CSV - extra single quotes

### ISSUE THREAD

**Issue by ss-gxp** [WeblateOrg/weblate#4488]
Version: 4.2.2 (docker image weblate/weblate)

Everything is fine in the web interface:

![weblate-2](https://user-images.githubusercontent.com/26460289/92890361-ba996500-f41f-11ea-903e-f2d7bf0c06a3.png)

But extra quotes appear when downloading CSV:

![weblate-3](https://user-images.githubusercontent.com/26460289/92890366-bc632880-f41f-11ea-9aff-fe4615af5302.png)

**Comment by nijel** [comment]
Unfortunately, this is intentional. Without the additional quote, Excel interprets the string as formula. See 1216f65655ca4b3f32b9d59605eb4446d503bdbf and https://hackerone.com/reports/223344.

**Comment by ss-gxp** [comment]
Clear.
But when loading back, the quotes were not stripped.

![weblate-5](https://user-images.githubusercontent.com/26460289/92896287-ea973700-f424-11ea-86dd-e91722426ec5.png)

**Comment by ss-gxp** [comment]
An api parameter would solve the problem.

Thanks for the clarification.

**Comment by nijel** [comment]
>  But when loading back, the quotes were not stripped.

Good point, I've fixed this in 747730847a
