### ISSUE TITLE
The past date of translation is not in my country's time.

### ISSUE THREAD

**Issue by kyotaro** [WeblateOrg/weblate#4500]
**Is your feature request related to a problem? Please describe.**

The calculation across dates does not fit the reality because the past date of translation is not in my country's time.
It shows how long ago the translation was done, but not my locale time.

**Describe the solution you'd like**

A pull-down menu for the translator's locale is available in the settings screen of the profile.

**Describe alternatives you've considered**

The number of days is calculated based on the translator's locale.

**Comment by nijel** [comment]
The number of days works regardless timezone. If something was 11 hours ago, it is still 11 hours ago no matter what timezone you are in. The absolute timestamps show in the tooltip are in the server timezone.
