### ISSUE TITLE
Login via Steam OpenID

### ISSUE THREAD

**Issue by aoisensi** [WeblateOrg/weblate#4504]
I want to add Login via Steam OpenID so I added ["social_core.backends.steam.SteamOpenId"](https://python-social-auth.readthedocs.io/en/latest/backends/steam.html) to `settings_override.py`.
I can login with Steam from registered with email address.
But, new user got error like Weblate cannot get email address.
Because Steam's OpenID is not provide account email address.
Can I add Steam Login without validate email address?
(I don't need user's email address.)

I tried `SOCIAL_AUTH_STEAM_FORCE_EMAIL_VALIDATION = False`.
(I don't know it is correct because my English level is low...)

Or Weblate need user's email address?

**Comment by nijel** [comment]
Weblate needs e-mail address as it includes it in the VCS commits.

**Comment by aoisensi** [comment]
I give up registration with Steam.
Thank you for quick response.
