### ISSUE TITLE
All changes for me are not shown

### ISSUE THREAD

**Issue by shima-office** [WeblateOrg/weblate#4516]
**Describe the bug**

I can't see all changes that I had done.

**To Reproduce**

1. Go to 'https://hosted.weblate.org/user/T.Shimazaki/#changes'
2. Click on 'Browse all changes for user'
3. See error  https://hosted.weblate.org/changes/?user=T.Shimazaki

**Expected behavior**

I expected to see all changes for me.

**Comment by shima-office** [comment]
The problem is not fixed yet.  

See error https://hosted.weblate.org/changes/?user=T.Shimazaki

**Comment by comradekingu** [comment]
@shima-office https://hosted.weblate.org/user/T.Shimazaki/#changes :)
