### ISSUE TITLE
REGISTRATION_ALLOW_BACKENDS not working

### ISSUE THREAD

**Issue by UncleSamSwiss** [WeblateOrg/weblate#4518]
**Describe the bug**

We configured a Docker Weblate instance using the following relevant environment variables:
```
WEBLATE_REGISTRATION_OPEN: 0
WEBLATE_REGISTRATION_ALLOW_BACKENDS: "github"
WEBLATE_SOCIAL_AUTH_GITHUB_KEY: "xxx.xxxxxxxxxxxxxxxx"
WEBLATE_SOCIAL_AUTH_GITHUB_SECRET: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
WEBLATE_ADD_LOGIN_REQUIRED_URLS_EXCEPTIONS: "/engage/(.*)$$"
```

According to the [documentation](https://docs.weblate.org/en/latest/admin/config.html#registration-allow-backends) (specifically for [Docker](https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_REGISTRATION_ALLOW_BACKENDS)), this should allow us to register through GitHub only.

Unfortunately, the registration page `/accounts/register/` only shows "Sorry, new registrations are turned off on this site."

We want the  user to be able to register from the "engage" page. There the "Register" button is available but leads to the aforementioned register page with the error message.

On the Sign-In page the GitHub button is shown, but this doesn't allow for a new user to register using a GitHub account.

**To Reproduce**

1. Set the environment variables as mentioned above (or without "WEBLATE_" when not in Docker)
2. Navigate to `/accounts/register/`
3. See the error message mentioned above

**Expected behavior**

According to the documentation, this should allow the user to register using GitHub.

**Screenshots**

Message when navigating to the `/accounts/register/` page:
![image](https://user-images.githubusercontent.com/7595126/93172168-a2308f80-f72a-11ea-892b-b871da097a43.png)
Login dialog:
![image](https://user-images.githubusercontent.com/7595126/93172239-c12f2180-f72a-11ea-9c71-c7af378a988b.png)

**Server configuration and status**

I'm not the server administrator, thus I can only provide the Weblate version: 4.2.2

**Comment by nijel** [comment]
WEBLATE_REGISTRATION_OPEN should be enabled.

**Comment by nijel** [comment]
Hmm, it doesn't seem to work that way either...
