### ISSUE TITLE
No automatic fix-ups on suggestions (or suggestion accept)

### ISSUE THREAD

**Issue by drdokk** [WeblateOrg/weblate#4522]
**Describe the issue**

Automatic fix-ups are only applied when saving translation (by clicking on "Save" button) and are not triggered when suggesting or accepting suggestions, is there any particular reason for that or is it a simple choice ?

**Server configuration and status**
Weblate 4.1.1

Thank you for your attention to my question!

**Comment by nijel** [comment]
I don't think there is a good reason for that.

**Comment by drdokk** [comment]
I think that most users will expect auto fixes to be applied on suggestions too, at least I did and I was a little bit surprised.
