### ISSUE TITLE
Zen mode no longer saves translations

### ISSUE THREAD

**Issue by fvbommel** [WeblateOrg/weblate#4536]
**Describe the bug**

I translated some strings for [Tasks on hosted.weblate.org](https://hosted.weblate.org/projects/tasks/android/nl/) yesterday, in Zen mode.
This morning I got a notification that there were untranslated strings, and they turned out to be the same ones.
This time I paid more attention, and the green check mark that usually shows up in Zen mode... didn't appear.
I had to copy-paste the translated strings to normal mode to get them to save.

**To Reproduce**

1. Translate some strings in Zen mode on https://hosted.weblate.org.
2. Check whether they've been saved.

**Expected behavior**

The strings are saved.

**Server configuration and status**

Whatever hosted.weblate.org uses.

**Additional context**

This used to work perfectly.

**Comment by nijel** [comment]
It works for me. What kind of error did you get? Can you please check browser console to see what might have gone wrong?

**Comment by fvbommel** [comment]
Weird, I just tried to reproduce it in Weblate/Documentation and it worked. It also worked when I edited existing translations in Tasker. And because it now worked neither way produced any errors in the console, obviously.

Unfortunately, I didn't leave any untranslated strings in Tasker to be able to test it that way.

Maybe it was a temporary issue or something? (even though it somehow happened twice on two different days...)

**Comment by fvbommel** [comment]
I think I'll close this unless (and until) I run into it again, hopefully with the console open.

**Comment by nijel** [comment]
In case the string is not saved, the Zen mode is supposed to show an error message to avoid silently losing data, but that apparently didn't work well in your case. In case you run into this again, try to collect more information from the browser (javascript errors and log of network requests) so that we can analyze what have gone wrong.
