### ISSUE TITLE
The visual regexp

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4541]
GitLab grants a good overview of what terms are available, and the options for them.

![bilde](https://user-images.githubusercontent.com/13802408/93610848-decfe580-f9cd-11ea-9d3d-fd9eade0f9b3.png)
![bilde](https://user-images.githubusercontent.com/13802408/93611001-0757df80-f9ce-11ea-8c00-33bbbcd50c70.png)

I would use it more on Hosted Weblate if I didn't those forget between using them.

**Comment by nijel** [comment]
Duplicate of #3063
