### ISSUE TITLE
Search page needs modification

### ISSUE THREAD

**Issue by baffclan** [WeblateOrg/weblate#4552]
**Describe the bug**
Search page needs modification.

**To Reproduce**
1. Open document page
   https://docs.weblate.org/en/latest/index.html
2. Goto page bottom
3. Click "Search Page" link
4. Opened Search page
   https://docs.weblate.org/en/latest/search.html

**Expected behavior**
Need a same search text box as a search in side panel.

| \<div role="search">
|  \<form id="rtd-search-form" class="wy-form" action="#" method="get">
|    \<input type="text" name="q" placeholder="Search docs">
|    \<input type="hidden" name="check_keywords" value="yes">
|    \<input type="hidden" name="area" value="default">
|  \</form>
| \</div>

**Comment by nijel** [comment]
Thanks for your report. It seems to be issue in the sphinx_rtd_theme, I've created the issue there: https://github.com/readthedocs/sphinx_rtd_theme/issues/998
