### ISSUE TITLE
I cant see all changes for me.

### ISSUE THREAD

**Issue by shima-office** [WeblateOrg/weblate#4559]
I can't see all changes that I had done.

1. Go to 'https://hosted.weblate.org/user/T.Shimazaki/#changes'
2. Click on 'Browse all changes for user'
3. See error https://hosted.weblate.org/changes/?user=T.Shimazaki

**Comment by shima-office** [comment]
The problem is not solved yet.

**Comment by baffclan** [comment]
@shima-office
稼働している本体への更新は、一日一回なので少し時間が必要です。

**Comment by shima-office** [comment]
1週間前にも、同じ指摘をして、直ったと言われたのですが、何も変わっていないので、再度、指摘をしたのです。
https://github.com/WeblateOrg/weblate/issues/4516

**Comment by baffclan** [comment]
IDに "." dot が使われていると再現するようです。
今回の修正で治るとよいですね。

**Comment by nijel** [comment]
That's expected, the fix was not yet deployed.

**Comment by nijel** [comment]
I've fixed only part of the problem with #4516 , it needed additional fix and that one is not yet deployed on the Hosted Weblate.

**Comment by shima-office** [comment]
Thank you very much.
I understand the situation.

I will wait **patiently**．

**Comment by shima-office** [comment]
I found this problem solved just now.
Thank you very much.
