### ISSUE TITLE
WEBLATE_SITE_DOMAIN doesn't change API URLs

### ISSUE THREAD

**Issue by jirihajek** [WeblateOrg/weblate#4565]
Even though I have WEBLATE_SITE_DOMAIN configured, queries to /api/ return urls like:

"web_url": "http://correct.domain.name.com/languages/en/",
"url": "http://127.0.0.1:8090/api/languages/en/",

I'd expect that "url" should respect the configured WEBLATE_SITE_DOMAIN, at least I haven't found anything stating the opposite in the documentation. Any idea?

**Comment by nijel** [comment]
What Weblate version do you use?

**Comment by jirihajek** [comment]
Sorry, the latest, 4.2.2.
