### ISSUE TITLE
How to unlock all read-only lines and make them normal or how to disable read-only strings completely?

### ISSUE THREAD

**Issue by zarp-dev** [WeblateOrg/weblate#4579]
Hi!
I have a problem with the translations.
Some of the strings in the project are read-only.
![image](https://user-images.githubusercontent.com/65812041/94044235-8be39d00-fdd6-11ea-9360-3df8272af239.png)
But there is no read-only flag in the translation file.
![image](https://user-images.githubusercontent.com/65812041/94044348-ae75b600-fdd6-11ea-91de-132c8df67d6b.png)
How can I turn all read-only strings to normal ones or how can I disable the read-only strings feature in the project completely.
I have administrator rights in it.

**Comment by nijel** [comment]
It seems like an issue with data migration in the past. You had English PO files and these were supposed to be converted to source string, but something went wrong there. I've just forced rescan of the PO files and that should fix this...

PS: It would be useful to include link to the project directly... https://hosted.weblate.org/projects/zrythm/
