### ISSUE TITLE
Suggest empty string for derivative language

### ISSUE THREAD

**Issue by andres53016** [WeblateOrg/weblate#4608]
**Is your feature request related to a problem? Please describe.**
Empty strings cannot be suggested for derived languages, this way it can be confirmed that for that language it is the same as for its derivative

**Describe the solution you'd like**
When an empty string is suggested, confirm that it is the same as in the derived language

**Describe alternatives you've considered**
A checkbox to confirm that it is equal to the derived language

**Comment by nijel** [comment]
What do you call derivative language?

Anyway it might be related to https://github.com/WeblateOrg/weblate/issues/1920

**Comment by andres53016** [comment]
For example es_419 (latin american spanish) is derivate of es (spanish), when it is empty the string in es_419 is the same as it is in Spanish. There should be a way to mark as translated for when it equals your derived language. Because there are many untranslated strings and the only action you can take is to skip

**Comment by nijel** [comment]
This behavior is specific to Gettext (and probably only to it), so it doesn't apply in general. Still it might be useful in general to mark blank string as translated and that's already covered by  #1920.
