### ISSUE TITLE
Restrict languages that can be downloaded for a user/group

### ISSUE THREAD

**Issue by mikefonted** [WeblateOrg/weblate#4611]
**Describe the bug**

A project with Custom access.
A component in that project with multiple languages.
A role with the only permission "Edit strings".
A group with that role, that project, that component and only one language.
A user with that group.

The user still can click on "Download translation files as ZIP file" with all languages.

Related #4519 and #4491

**Expected behavior**

"Download translation files as ZIP file" with only the language the user has permission to edit.

**Server configuration and status**

Docker image tag weblate/weblate:4.2.2-2

**Comment by nijel** [comment]
The user is also able to browse all translations in this case, so the download is consistent with this behavior.
