### ISSUE TITLE
Still fuzzy matches when using PO with deactivated fuzzy matching ?  

### ISSUE THREAD

**Issue by ReneBoehm** [WeblateOrg/weblate#4614]
We are using weblate 3.9.1 (docker image) with PO files (gettext) and deactivated the fuzzy matching. Sometimes (not really seldom) it seems that there are still fuzzy matches that make no sense. Is it a bug in this old version or is it something like a feature of gettext and is not related to actual fuzzy matching becuase it has something to do with the normal merge behaviour of gettext ?

Did someone else experience the same ?

**Comment by nijel** [comment]
You update the PO files using msgmerge addon? Can you try saving the addon configuration if that fixes the behaviour?

**Comment by ReneBoehm** [comment]
Thanks for the suggestion. We will try that.
