### ISSUE TITLE
Inconsistent borders between dashboard and component view

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4618]
Sometimes the borders don't do anything (?)
If a vision impaired user with a magnifying tool is baited to follow the line to see where it ends, there isn't actually anything over there on the right side.
Like current component language view
![bilde](https://user-images.githubusercontent.com/13802408/94591202-452ef080-0277-11eb-9694-7bec08c06ba2.png)

Current dash, 
![bilde](https://user-images.githubusercontent.com/13802408/94586760-288fba00-0271-11eb-8f19-bd6919cd3d0e.png)

This foregoes the gray line operating a "border" function, but since there isn't anywhere to track to,
I think this is more visually consistent
![bilde](https://user-images.githubusercontent.com/13802408/94591430-9d65f280-0277-11eb-8cc9-1269abb63dbd.png)

**Comment by nijel** [comment]
Fixed together with #4619
