### ISSUE TITLE
Borderless menus, or option for no borders?

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4619]
Current, borders
![bilde](https://user-images.githubusercontent.com/13802408/94586760-288fba00-0271-11eb-8f19-bd6919cd3d0e.png)
Borderless
![bilde](https://user-images.githubusercontent.com/13802408/94586794-32192200-0271-11eb-8b50-6bb53ac33e3d.png)

The second row of buttons, "Component" and so on dissapear more, but that highlights a problem of not knowing where the borders are (vertically) in the first place.

![bilde](https://user-images.githubusercontent.com/13802408/94590549-5a574f80-0276-11eb-94e8-1fc26eadecb8.png) has borders surrounding the buttons.

I like the borderless, but it isn't clear from https://www.w3.org/TR/low-vision-needs/#spacing whether borders are good or bad, only that they ideally should be selectable.
Arguably this is already possible, but it could be a user option.
Maybe also high-contrast mode would be something to consider.

What to do with the borders is more of a question, of design and consideration for vision-impaired people.
If anything a gray border doesn't seem optimal.

In the new (much) improved Matrix view, the borders could be said to serve a purpose
![bilde](https://user-images.githubusercontent.com/13802408/94587264-d8fdbe00-0271-11eb-920d-3cd41b3b3bd9.png)

YouTube and Netflix have almost no borders, and I imagine they spent a fair bit on research to get there. In the very least they seem to have all sorts of users (covered?).
As a compromise: Contrast sections, no extra borders, no horizontal lines
![bilde](https://user-images.githubusercontent.com/13802408/94596616-e7e96e00-027b-11eb-9443-2595d4bb3917.png)
instead of
![bilde](https://user-images.githubusercontent.com/13802408/94596663-f46dc680-027b-11eb-966d-9ae99cbe7ada.png)
Related to #4618 and #4620

**Comment by nijel** [comment]
Removing some borders is certainly an option. Actually, 4.3 will already have way fewer borders than 4.2 had because we've removed most borders around source/translation strings.

>  Arguably this is already possible, but it could be a user option.

No, we can't make everything user configurable.

>  Maybe also high-contrast mode would be something to consider.

We might have dark mode in future, see https://github.com/WeblateOrg/weblate/issues/2969
