### ISSUE TITLE
Status and component field colour inconsistency

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4620]
Gray, current
![bilde](https://user-images.githubusercontent.com/13802408/94588583-9ccb5d00-0273-11eb-9aca-6acc3c373588.png)
White, current
![bilde](https://user-images.githubusercontent.com/13802408/94588642-b2d91d80-0273-11eb-94be-bdfdca71055c.png)
New "consistent"
![bilde](https://user-images.githubusercontent.com/13802408/94591992-59272200-0278-11eb-967a-8b8a2d5d02a0.png)

Or, if you will
New dash, gray
![bilde](https://user-images.githubusercontent.com/13802408/94594676-47924a00-0279-11eb-9372-7151b46a977b.png)

**Comment by nijel** [comment]
I think that this does no longer apply after changes in #4619 - the tables no longer have borders...
