### ISSUE TITLE
Deletion of PO files results in inability to pull them down from the source code repository

### ISSUE THREAD

**Issue by superDross** [WeblateOrg/weblate#4625]
**Describe the issue**

We had an issue whereby our persistent volume (used along with a dockerised Weblate) that stores our Weblate translation data (PO files) was deleted by accident.

The translation data was still present and intact on our remote git server so I thought we could simply pull them down into our Weblate instance. 

It seemed that all components translations were present in the UI, despite the po files no longer existing in the volume.  When this occurred we found all components were locked and when trying to unlock and pull via the UI (Repository Maintenance), we could not do so. Either an error occurred with `Fatal: bad revision` or a message suggesting everything is fine with `The local repository is up to date.`.

I tried to jump into the docker container in a bash terminal and going into the individual components  in the `/app/data/vcs/` dir and git pulling there. However, all were gone except the component which was used to share the same repository with all the other components.

I am wondering how we should proceed with file recovery if this occurs again within the future? I imagine there is a simple solution to this that I am not seeing considering all the translation files were still present within the remote source code repository.

**Additional Information**

Our components for this project were set up to a source repository via ssh. All other components were set up to share the same repository as the initial ('main') component e.g. `weblate://project/component`. 

All components were configured as monolingual components.

**Comment by nijel** [comment]
I think that `weblate updategit --all` should recover the repos, see https://docs.weblate.org/en/latest/admin/management.html#updategit for more info.
