### ISSUE TITLE
Add term I am translating to glossary by one click

### ISSUE THREAD

**Issue by KadAnna** [WeblateOrg/weblate#4630]
**Is your feature request related to a problem? Please describe.**
When I am translating a term, I want to add it to a chosen glossary. Now I have to manually copy both the source text, translated ext, then click add term to a glossary, then paste both of the texts.

**Describe the solution you'd like**
in the glossary screen part on the right, I would like to have a button e.g. "Add current term to glossary". The currently translated term (both source and translated text) would then be automatically populated in the popped up dialog on adding a term to glossary.

**Describe alternatives you've considered**
just improve the current Add term to the glossary.

**Additional context**
Similarly, I would like to apply translation suggested from glossary to the translation window by clicking on (currently missing) option "Apply translation" - see in the screenshot
![weblate_addtermtoglossary](https://user-images.githubusercontent.com/70368530/94816473-2a39b900-03fc-11eb-8039-4a9696d0a77f.jpg)
)

**Comment by nijel** [comment]
This is simple for short strings. On the other side, it doesn't make much sense for paragraph like strings (for example https://hosted.weblate.org/translate/weblate/documentation/ru/?checksum=f638e2d112eb48fe). The question is where to draw a line between these two.

**Comment by comradekingu** [comment]
Don't draw a line. See how many hits a translation gets, and see if it is in the master dictionary.
