### ISSUE TITLE
Count words and characters in the target language

### ISSUE THREAD

**Issue by ss-gxp** [WeblateOrg/weblate#4631]
Version: 4.2.2

Apparently, the same numbers are displayed.

![weblate-7](https://user-images.githubusercontent.com/26460289/94844543-13f52280-0427-11eb-9b35-38c6d7c3b734.png)

**Comment by comradekingu** [comment]
@ss-gxp As it should, you are browsing the English branch of a component.
Since it is the source, it will have the same number of strings as the "source amount".
https://hosted.weblate.org/projects/remmina/#information
vs
https://hosted.weblate.org/languages/en/remmina/#information

**Comment by ss-gxp** [comment]
I am sorry not specified that the source is not English.
Take any project on hosting, it's [the same there](https://hosted.weblate.org/languages/eo/weblate/#information).

**Comment by nijel** [comment]
The number of chars/words always refers to source language chars/words, but it's not described that way. In this case having both of them listed doesn't make much sense, it was copied from the [project level stats](https://hosted.weblate.org/projects/weblate/#information).

**Comment by nijel** [comment]
Fixed since 11056c9cf565b0258b1ec82d2790156bb1a9900f.
