### ISSUE TITLE
My word are now in "Has been translated". Why ?

### ISSUE THREAD

**Issue by ar-boschung** [WeblateOrg/weblate#4637]
**Describe the bug**

I've translated a lot of word yesterday. A few hours later, all my translations are deleted, but I have the message "Has been translated". I'm also able to see them in "Translation Memory". 

How can this happend ? 

**Screenshots**
![image](https://user-images.githubusercontent.com/15978870/94909771-f619d300-04a3-11eb-982c-c13c39916377.png)  

**Server configuration and status**
$ weblate list_versions
 * Weblate: 3.10
 * Django: 2.2.8
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.4.0
 * lxml: 4.3.2
 * Pillow: 6.2.1
 * bleach: 3.1.0
 * six: 1.13.0
 * python-dateutil: 2.8.1
 * social-auth-core: 3.2.0
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.8.1
 * oauthlib: 3.1.0
 * django-compressor: 2.3
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.3
 * user-agents: 2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.1
 * celery: 4.3.0
 * kombu: 4.6.3
 * celery-batches: 0.2
 * translation-finder: 1.7
 * html2text: 2019.9.26
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.22.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.13.5
 * Cython: 0.29.14
 * misaka: 2.1.1
 * GitPython: 3.0.5
 * borgbackup: 1.1.10
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.7.7
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.5
 * tesserocr: 2.5.0
 * akismet: 1.0.1
 * boto3: 1.10.44
 * zeep: 3.4.0
 * aeidon: 1.6.0
 * Mercurial: 4.8.2
 * git-svn: 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: vserv1223.swisslink.ch
 * Celery: redis://localhost:6379/1, redis://localhost:6379/1, regular
 * Platform: Linux 4.15.0-47-generic (x86_64)

**Comment by nijel** [comment]
It could be that it was reverted in the repository. Or there could be a bug in saving the string to the file. Check the string and VCS history to figure out what did happen.

> Weblate: 3.10

I see you are running old version, many issues were fixed since then...
