### ISSUE TITLE
Error in weblate instance - "File content merge failed: could not convert string to float: location"

### ISSUE THREAD

**Issue by cnavagr** [WeblateOrg/weblate#4645]
**Describe the bug**

When attempting to upload translations from our vendor to Weblate, first of all, it takes a long time (when attempting an upload of the full file -- more than 70k strings -- it runs for over an hour, then fails completely).

After trimming the file to a smaller size by various methods, the action will still not complete, and Weblate throws this error:

"File content merge failed: could not convert string to float: location"

Checking the history of the project in Weblate, it shows that new strings are still being imported ("Resource update") for individual languages.

This is affecting the Dictionary strings in Weblate

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server configuration and status**

**Weblate deploy checks**

**Exception traceback**

**Additional context**
Weblate instance
https://fsmisc3.cg.na.jci.com/

Please share this issue with "katie.holterman@jci.com"

**Comment by nijel** [comment]
Can you please provide a bit more details? What Weblate version do you use? What file format?

Have you looked at similar issues? See https://github.com/WeblateOrg/weblate/issues/2550 or https://github.com/WeblateOrg/weblate/issues/2317

**Comment by cnavagr** [comment]
Hi,
It is Weblate 3.1.1.

**Comment by nijel** [comment]
Please upgrade, looks like #2550 or #2317.
