### ISSUE TITLE
Expanded language lists

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4656]
Papercut again,

No matter the vertical resolution, you get 5 items to pick from in the settings, in what is a double-scrollbar view.
That is neither where I expect to find a scrollbar, nor is it as easy to get to as the right side.

![bilde](https://user-images.githubusercontent.com/13802408/95260165-cd813880-0817-11eb-92db-69309f7fcfd8.png)
The bottom here isn't even as far down as the next tab "Settings".

These are the alerts
![bilde](https://user-images.githubusercontent.com/13802408/95260285-fe616d80-0817-11eb-9316-45b93c198699.png)
If it was placed on the bottom here, it could just scroll forever. The "Languages" tab would have to have the two lists side-by-side to do this, though the latter (secondary languages) is the more important one (and the one that doublescrolls for me on Hosted)

Something ala this looks more 18:9 21:9 or 16:9 or whatever the new resolutions are

![bilde](https://user-images.githubusercontent.com/13802408/95262208-37e7a800-081b-11eb-9cb6-3f30b7d9fd1f.png)

**Comment by meel-hd** [comment]
@comradekingu @nijel the problem if I am not mistaken is that the scrollable languages view needs to be bigger if the screen have enough space?
**These ones? **
![image](https://github.com/user-attachments/assets/b45cd1b8-d7df-450f-a121-e64400d6440a)

Similarly, in the **Watched Project** in **Notifications** here
![image](https://github.com/user-attachments/assets/13770f03-90a2-4209-a7e6-d15be1a7e08e)
