### ISSUE TITLE
Remove top line

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4659]
Papercut issue,
![bilde](https://user-images.githubusercontent.com/13802408/95299158-c1739600-086c-11eb-8227-85e03f564bc4.png)

The top line is available in the profile, in checks, and various other places.
I don't think it does anything (?) as everything above it is always next to the much more prominent top bar. Following the top bar horizontally is thus easier than the line.

Also, like the screenshot shows, it is out of line with the lines in the dropdown menu. I am not hoping or think this is an issue for most people, but I will fully acknowledge I care more about it than I should. :)

**Comment by nijel** [comment]
> Also, like the screenshot shows, it is out of line with the lines in the dropdown menu.

Yes, the dropdown is not aligned to the navbar, what it should be, fixed in 40461839600eb2e9b30475cb0d8c1d57b57ac728.
