### ISSUE TITLE
504 Gateway Timeouts

### ISSUE THREAD

**Issue by michaelplatt** [WeblateOrg/weblate#4670]
We're suffering 504 Gateway Timeouts when dealing with a larger resource file (28k strings, 115k words).

We get timeouts when pulling or pushing to Git.
We get timeouts when exporting files for translation.

The specific timeout causing the current issue is Files > Download translation as XLIFF 1.1

What options do we have to prevent the timeout and actually be able to export the translation file?

Regards
Mike Platt
Bohemia Interactive Simulations

**Comment by nijel** [comment]
> The specific timeout causing the current issue is Files > Download translation as XLIFF 1.1

This particular issue should be already addressed by1598e418c14ea28e32e78e1ca188bf6593dcb84f for the 4.3 release.

Generally speaking, there are requests which might take long as they are synchronous, so for now, the recommended approach is to increase the timeout.

**Comment by anudeepg** [comment]
@nijel  - can you please provide any documentation on how to increase the server timeout ? 
We are getting same 504 gateway timeout ( server didn't respond in time )

**Comment by ecobnb** [comment]
we solved changing settings in nginx with: 
proxy_connect_timeout 600;
proxy_send_timeout 600;
proxy_read_timeout 600;
send_timeout 600;
