### ISSUE TITLE
Make Inclusion of weblate logs in Sentry configurable

### ISSUE THREAD

**Issue by blackfedora** [WeblateOrg/weblate#4673]
**Is your feature request related to a problem? Please describe.**
We would like to use Sentry to monitor events generated by weblate. It appears that the sentry sdk is currently configured to ignore the `weblate` and `weblate.celery` loggers. As a result, the Sentry data paints and incomplete picture.

**Describe the solution you'd like**
A config variable is introduced which allows users to choose whether or not data from the `weblate` and `weblate.celery` loggers is sent to Sentry.

**Describe alternatives you've considered**
We have considered forwarding log data to Sentry using a separate process, but we have been unable to find the logs in their default locations (However, it is possible that they were configured to appear elsewhere, the developer who configured the pod is out sick today).

**Additional context**
Above the code in question (`weblate/utils/errors.py:93-5`), there is a comment: 

> # Ignore Weblate logging, those should be reported as proper errors

It is not immediately clear why data sent to Sentry could not also be reported as an error. In fact, [your own documentation](https://docs.weblate.org/en/latest/admin/install.html?highlight=sentry#sentry) suggests using Sentry to monitor weblate and celery errors, and yet both of these loggers are explicitly being ignored. What exactly does "built-in support" mean in this context?

**Comment by nijel** [comment]
The reason for this is that errors are sent to Sentry as an exception and logged. The log then needs to be ignored for Sentry to avoid duplication of all such errors.

**Comment by blackfedora** [comment]
@nijel just to make sure I understand you, the current Sentry workflow is this:

1. Some issue is detected, prompting the "weblate" logger to write some data to the logs, and an exception to be raised
1. Eventually, this exception is caught by Django, which returns an appropriate HTTP error response.

Sentry has been set to ignore the "weblate" logger because otherwise both of these steps would produce a Sentry entry, so a single issue would be represented multiple times.

Is my understanding correct?

**Comment by nijel** [comment]
To be more precise let's look at the code:

https://github.com/WeblateOrg/weblate/blob/3ebae56ee162c18a44aee7dcc3dcc9a52b92608f/weblate/utils/errors.py#L59-L72

The exception is sent to Sentry (if configured, lines 59-66) and logged (line 72).

You don't want both to appear in Sentry as that will create two distinct events there. On the other side the error should appear in the log even when using Sentry to make logging consistent with non-Sentry setup and to allow to see things locally on the system.

What could be way to improve it is to use dedicated logger for this kind of logs and ignore only that for Sentry.
