### ISSUE TITLE
Android: translations of new strings in non-master language are removed when pulled from repository

### ISSUE THREAD

**Issue by ubuntudroid** [WeblateOrg/weblate#4679]
**Describe the bug**

Our master language is English. After pulling string data from our Android app repository, weblate has removed all German translations for newly added English strings which we did in the German strings.xml (same commit). We now have to manually add them again via the weblate UI.

**To Reproduce**

1. Add new strings to the master strings.xml
2. Translate them in one non-master language strings.xml
3. Commit and push
4. Sync weblate

**Expected behavior**

Translated new strings in the non-master language should be picked up by weblate (this is how it worked up until today) and not just being removed.

**Screenshots**

I can send a screenshot of weblate's commit as DM upon request (it's a private repository).

**Server configuration and status**

hosted weblate

**Weblate deploy checks**

N/A

**Exception traceback**

N/A
**Additional context**

N/A

**Comment by nijel** [comment]
Weblate should only remove non-matching strings in case the [cleanup addon](https://docs.weblate.org/en/latest/admin/addons.html#cleanup-translation-files) is installed.

Looking at your repo that is indeed what has happened there...
