### ISSUE TITLE
Translation of same string bug different context are automatically merged, causing wrong translations

### ISSUE THREAD

**Issue by hosiet** [WeblateOrg/weblate#4692]
**Describe the bug**

There are translation items with same source strings and different contexts (not exactly the same context). When I translate the string, the translated string is automatically applied to strings of similar context, which is undesired and made the translation of that string with simiar context wrong.

Even the context information are different, on weblate web interface it still says that the strings "share the same source string and same context".

To make things worse, I cannot cut the connection of those strings as a translator. When I change the translation at string A, the translation of string B **always** change and follow the change of string A. The result is that either string A's translation is wrong, or string B's translation is wrong, or both translations are all wrong.
 
**To Reproduce**

The bug example can be found currently on the hosted weblate instance.

To be more concrete, we consider the translation of "Georgia". We all know that it can be a European country named "Georgia" or the name of state "Georgia" in the United States.

The case is about the translation of ISO-3166-1 (country name) and ISO-3166-2 (province-level name).

* `zh_Hans` translation of country Georgia: https://hosted.weblate.org/translate/iso-codes/iso-3166-1/zh_Hans/?checksum=ec037b069edd70a3
* `zh_Hans` translation of state Georgia: https://hosted.weblate.org/translate/iso-codes/iso-3166-2/zh_Hans/?checksum=ec037b069edd70a3

1. Go to https://hosted.weblate.org/translate/iso-codes/iso-3166-1/zh_Hans/?checksum=ec037b069edd70a3 and translate it as name A
2. Click on https://hosted.weblate.org/translate/iso-codes/iso-3166-2/zh_Hans/?checksum=ec037b069edd70a3 and translate it as name B
3. Go to https://hosted.weblate.org/translate/iso-codes/iso-3166-1/zh_Hans/?checksum=ec037b069edd70a3 and you will find that the translation becomes name A, which is the error.

**Expected behavior**

The translation at step 1 and step 2 should be different. Or at least, please disable the automatic translation applying by default.

**Screenshots**

Let me know if you need more screenshot here.

**Server configuration and status**

This is hosted.weblate.org.

**Weblate deploy checks**

This is hosted.weblate.org.

**Exception traceback**

This is hosted.weblate.org.

**Additional context**

The translation is for hosted iso-codes project.

* * *

If possible, may I suggest that we do not merge translation with different source string comment by default? I know that the iso-codes project did not actually add the "context" information at all but use the string comments to differentiate different strings, but this consideration should be reasonable.

(Or at least please provide an option to disable automatic translation applying.)

**Comment by nijel** [comment]
You can already disable it in component settings: https://docs.weblate.org/en/latest/admin/projects.html#allow-translation-propagation.

This should be improved in the future, see https://github.com/WeblateOrg/weblate/issues/3166

**Comment by nijel** [comment]
It's per component setting meanwhile, the issue was not updated. But still, it's something admins can configure.

**Comment by tomkolp** [comment]
The ideal solution to this problem is to bind the string to the context in TM.  

PO file:
#: 3427285-0-8
msgctxt "3427285-0-8"
msgid "IDLE"
msgstr "IDLE1"

#: 3427285-0-10
msgctxt "3427285-0-10"
msgid "IDLE"
msgstr "IDLE2"

TM Smartcat example:
<prop type = "x-context"> 3427285-0-10 </prop>
<tuv xml: lang = "en">
<Seg> IDLE </ seg>
</ Tuv>
<tuv xml: lang = "pl">
<Seg> IDLE2 </ seg>
</ Tuv>
</ Tu>

Is it possible in "Weblate"?

**Comment by nijel** [comment]
In this particular case "context" probably means translation component where the string is used, not actual msgctxt which is not set on these strings.

**Comment by tomkolp** [comment]
Currently my .po files have msgctxt set for each segment. This ensures that Smartcat always writes three things to TM:
ID = msgctxt, source = msgid, target = msgstr. As a result, I can even delete all files, and after reloading the translations always go to the right place, even if source (msgid) is the same and target (msgstr) is different. Would there be such a possibility in Weblate?

**Comment by nijel** [comment]
@tomkolp Can you please stop hijacking unrelated issue? The original issue had no msgctxt and it was not about translation memory at all...

I'm closing this issue as the original question has been most likely answered more than month ago. Given that the original poster didn't come back it probably helped him.
