### ISSUE TITLE
How to increase the rate limit API on a Docker install ?

### ISSUE THREAD

**Issue by doums** [WeblateOrg/weblate#4693]
Hi,

Once again the [doc](https://docs.weblate.org/en/latest/api.html#rate-limiting) is quite vague on this point.
Whit a docker install, what are we suppose to do ?

**Comment by nijel** [comment]
Anything what can't be configured using documented environment variables can be done in custom configuration file, see https://docs.weblate.org/en/latest/admin/install/docker.html#further-configuration-customization
