### ISSUE TITLE
Keep editing buttons consistent and in the same place

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4696]
Papercut move all "open in editor" clickables (pencils) to the left.

![bilde](https://user-images.githubusercontent.com/13802408/96050624-79a2cf00-0e69-11eb-8245-94887ed120d5.png)
**vs**
![bilde](https://user-images.githubusercontent.com/13802408/96050644-80314680-0e69-11eb-97ad-c690d05fac35.png)

Sometimes there is a link top left too, so with this all the clickable stuff is within reach.

**Comment by nijel** [comment]
On the other side, this would ruin alignment of full editor where several non-editable fields are displayed as well:

![image](https://user-images.githubusercontent.com/212189/96090132-1300ce00-0ec8-11eb-9196-61a73f8f2ac7.png)

**Comment by nijel** [comment]
As one of the icons is gone now, it's consistent ;-).
