### ISSUE TITLE
Keep copy to source and clipboard buttons consistent and in the same place

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4697]
Papercut
In the spirit of #4696 all clickable buttons are consistent and left-aligned
![bilde](https://user-images.githubusercontent.com/13802408/96052048-4281ed00-0e6c-11eb-8686-d155026f89ee.png)
**vs**
![bilde](https://user-images.githubusercontent.com/13802408/96052204-9096f080-0e6c-11eb-8d4b-1159ea899d34.png)

It stands to reason if "copy to clipboard"
![bilde](https://user-images.githubusercontent.com/13802408/96052373-f08d9700-0e6c-11eb-93e3-da619f1f7c77.png)
is inline with what is being copied, "copy to source" 
![bilde](https://user-images.githubusercontent.com/13802408/96052342-dd7ac700-0e6c-11eb-932e-080dbc674cbd.png)
should be too.
Adding "copy to source" for all languages makes sense for languages that are very similar. (or more similar than the source language and the translation).

**Comment by nijel** [comment]
This would break consistency with the full editor, where there is no space on the left. Having the clone button for all languages looks useful though...

**Comment by comradekingu** [comment]
Well effectively the already present copy icon is a part of the usable text field that could be anywhere. Losing a bit to the right is the same as losing it on the left, even if it means moving the start of the text field(?)

I worry more about the actual consistency of what the buttons look like, meaning shape, where, and what colour they are.

Does having the clone tool in all languages mean putting the green current button below or above the current other langauges?
That is far from optimal. Neither has any connection to the text, moreso than it does to the language either below or above it.
Yes it is possible to figure it out, but it is all going to be inconsistent with where that button is now for cloning the source language.

If the current clone button just moves to the source language, I would much rather have it to the left of the language name with the pencil. Or if you will, to the right of the language name with the pencil.

**Comment by nijel** [comment]
We've been discussing this and the biggest question is whether we need both actions. The problem with "copy to source" is that it doesn't work well when working on plural string and showing multiple languages. That would either need doing decisions instead of the user (and possibly overwriting his changes) or showing some kind of selection (where do you want to copy this string to).

In the end I tend to prefer having just copy to clipboard action, which is clearly defined, and has generally known icon.
