### ISSUE TITLE
GPLv3+ → AGPLv3+ license

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4705]
GPLv3+ doensn't have the "network protection" clause which renders the function of the license invalid as it it is applied upon "distribution". For reasons that are solved in AGPLv3, software intended to be used as-a-service is then no different from software distributed as packages.

> Notwithstanding any other provision of this License, if you modify the Program, your modified version must prominently offer all users interacting with it remotely through a computer network (if your version supports such interaction) an opportunity to receive the Corresponding Source of your version by providing access to the Corresponding Source from a network server at no charge, through some standard or customary means of facilitating copying of software.

**Comment by nijel** [comment]
I don't see strong reason to do so:

* It requires additional work to ensure compliance with the AGPL (something to download the source code)
* IANAL, but I think it doesn't cover additional modules loaded into Weblate, so users would be still able to extend Weblate without releasing source code
* Publishing the source code doesn't automatically mean it will get merged and improve existing code base
