### ISSUE TITLE
Random 'cursor already closed' error

### ISSUE THREAD

**Issue by jirihajek** [WeblateOrg/weblate#4709]
I got sometimes notified from the server about an error:

InterfaceError at /js/translate/modernmt/102793/
cursor already closed
Request Method: | POST
http://127.0.0.1:8090/js/translate/modernmt/102793/
3.1.1
InterfaceError
cursor already closed
/usr/local/lib/python3.7/dist-packages/django/db/utils.py, line 97, in inner
/usr/bin/uwsgi-core
3.7.3
['/usr/local/lib/python3.7/dist-packages/git/ext/gitdb',  '/',  '/usr/local/lib/python3.7/dist-packages/',  '.',  '',  '/usr/lib/python37.zip',  '/usr/lib/python3.7',  '/usr/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/dist-packages',  '/app/data/python',  '/usr/lib/python3/dist-packages',  '/usr/local/lib/python3.7/dist-packages/gitdb/ext/smmap']

I'm not sure about the exact repro-steps, but if anyone has any suggestion re. what to look for, I can try to get more information. Thanks!

**Comment by nijel** [comment]
I've seen several such reports, but we were unable to reproduce that in another environment, my wild guess is that something is terminating inactive TCP connections as this typically happens after Weblate does some possibly lengthy operation which does not involve database (accessing ModernMT in your case).

It might be a PostgreSQL configuration (which we ruled out in most cases) or something in the Docker networking (where my knowledge is close to zero, so I can't really help).

See https://github.com/WeblateOrg/docker/issues/786, https://github.com/WeblateOrg/weblate/issues/3942, https://github.com/WeblateOrg/weblate/issues/4539

**Comment by humphrey** [comment]
I get the same issue, with a very similar stack trace in my own custom django project (not using weblate).  I do not yet have a solution, but the issue only occurs when I use `uwsgi`.  If I use `manage.py runserver` it does not occur.
