### ISSUE TITLE
Are languages with the `_CARES` suffix spam?

### ISSUE THREAD

**Issue by samfundev** [WeblateOrg/weblate#4715]
I'm new to using Weblate and the user `@pidraiwo` has added the language `de_CARES` to my project on the hosted version of Weblate. I've looked into other projects that got translations with the `_CARES` prefix and it looked like those translations have been deleted. So to me, this looks like spam and I've deleted it. Is this actually spam? And if it is spam, is there something that I (or even Weblate) could do to prevent this in the future?

**Comment by nijel** [comment]
It's a custom language used by some projects. The problematic part is when users are adding it to projects which are not interested in this (in this particular case probably nobody else wants this). 

This is related to https://github.com/WeblateOrg/weblate/issues/3559, we probably need a way to limit users what locales they can select to translate leaving full choice only to admins...
