### ISSUE TITLE
Subtitle file not found

### ISSUE THREAD

**Issue by RobbyZ** [WeblateOrg/weblate#4732]
When trying to add a Advanced Subtitle Station Alpha component, the UI returns "Could not parse translation base file: No such file or directory" for "Monolingual base language file" section

In the apache logs, I see:  ` WARNING Template parse error: FileNotFoundError: [Errno 2] No such file or directory: '/home/weblate/weblate-env/lib/python3.8/site-packages/data/headers/ass'`

Perhaps there is a dependency I have not installed?  I don't have any headers folder.  I have already installed both aeidon and ass into my env.

Thank you

**Server configuration and status**

(weblate-env) www-data@translate:/home/weblate$ weblate list_versions
 * Weblate: 4.1.1
 * Django: 3.0.9
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0
 * lxml: 4.5.2
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.4.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 44.0.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.4
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.36.1
 * diff-match-patch: 20181111
 * requests: 2.22.0
 * django-redis: 4.12.1
 * hiredis: 1.0.1
 * sentry_sdk: 0.15.1
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.7
 * borgbackup: 1.1.13
 * pyparsing: 2.4.6
 * Python: 3.8.5
 * Git: 2.25.1
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.1
 * git-svn: 2.25.1
 * Redis server: 5.0.7
 * MySQL sever: 5.7.31
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.smtp2go.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: memory://, N/A, eager
 * Platform: Linux 5.4.0-52-generic (x86_64)
(weblate-env) www-data@translate:/home/weblate$

**Weblate deploy checks**

(weblate-env) www-data@translate:/home/weblate$ weblate check --deploy
SystemCheckError: System check identified some issues:

ERRORS:
?: (weblate.E005) Celery is configured in the eager mode
        HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/install.html#celery

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.
?: (weblate.W025.laravel) Failure in loading handler for laravel file format: No module named 'phply'
        HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/install.html#optional-deps
?: (weblate.W025.php) Failure in loading handler for php file format: No module named 'phply'
        HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/install.html#optional-deps
?: (weblate.W033.Gerrit) Failure in loading VCS module for Gerrit: git: 'review' is not a git command. See 'git --help'.
 (1)
        HINT: https://docs.weblate.org/en/weblate-4.1.1/vcs.html
?: (weblate.W033.GitHub) Failure in loading VCS module for GitHub: [Errno 2] No such file or directory: 'hub'
        HINT: https://docs.weblate.org/en/weblate-4.1.1/vcs.html
?: (weblate.W033.GitLab) Failure in loading VCS module for GitLab: [Errno 2] No such file or directory: 'lab'
        HINT: https://docs.weblate.org/en/weblate-4.1.1/vcs.html
?: (weblate.W033.Mercurial) Failure in loading VCS module for Mercurial: [Errno 2] No such file or directory: 'hg'
        HINT: https://docs.weblate.org/en/weblate-4.1.1/vcs.html

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 4.3.
        HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/upgrade.html

System check identified 14 issues (1 silenced).

**Comment by nijel** [comment]
What is your translation component configuration?

**Comment by RobbyZ** [comment]
Please find attached two different component configurations I attempted

Attempt 1:

![Screenshot_2020-10-21-a](https://user-images.githubusercontent.com/4694583/96790912-63869880-13ac-11eb-9377-e8a1b475a501.png)

Attempt 2:

![Screenshot_2020-10-21-b](https://user-images.githubusercontent.com/4694583/96790924-671a1f80-13ac-11eb-86d4-911726e007c4.png)

Confirming that it's there:

![Screenshot_2020-10-21-c](https://user-images.githubusercontent.com/4694583/96790939-6da89700-13ac-11eb-8ff0-461f25d57760.PNG)

I use a similar configuration to the first attempt for both .PO's and .XLSX with good results so far.  It is only the .ASS file that seems to give trouble.

**Comment by nijel** [comment]
As you're using SVN, most likely your repo URL might need adjustment to include branch, see https://docs.weblate.org/en/latest/vcs.html#subversion

**Comment by RobbyZ** [comment]
The URL includes the trunk path.  As shown by the third screenshot, SVN is pulling down the file into the directory correctly.

**Comment by nijel** [comment]
Hmm, there seems to be quite some logic in the subtitles parser which involves temporary files, there can possibly go something wrong: https://github.com/translate/translate/blob/1d45f776b51f470ef84e5fd52c2a7086e81f1a4b/translate/storage/subtitles.py#L119-L160

**Comment by RobbyZ** [comment]
Today I tried to manually install translate toolkit on a windows box in a fresh install of python/virtualenv, and got the same error.

```
(ttk) C:\dev\translate-toolkit>sub2po -P "C:\dev\translate-toolkit\DA Launch Trailer.ass" "C:\dev\translate-toolkit\trailer.pot"
processing 1 files...
Failed to read file 'C:\Users\Sim\Envs\ttk\lib\site-packages\data\headers\ass': No such file or directory
sub2po: WARNING: Error processing: input C:\dev\translate-toolkit\DA Launch Trailer.ass, output C:\dev\translate-toolkit\trailer.pot, template None: FileNotFoundError(2, 'No such file or directory')
[###########################################] 100%
```

So I think it is a problem with translate toolkit, not a problem with weblate.  I opened [a new issue](https://github.com/translate/translate/issues/4155) over there and will close this one.
