### ISSUE TITLE
Field for adding source comments is not shown by default

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4734]
Papercut issue
![bilde](https://user-images.githubusercontent.com/13802408/96679280-e256e380-1362-11eb-82a2-c40ca9971eba.png)
When clicking it, it becomes
![bilde](https://user-images.githubusercontent.com/13802408/96679330-fc90c180-1362-11eb-9012-1c1724826f09.png)

Curiously, it is also shown when closing the source string context editor and clicking the button to open it a second time, which makes me think this isn't intentional.

**Comment by nijel** [comment]
Looks like some issue in CodeMirror editor integration.

**Comment by nijel** [comment]
Caused by https://github.com/codemirror/CodeMirror/issues/2469, there is addon which should fix ths.
