### ISSUE TITLE
Provide clear, actionable error message when account creation fails

### ISSUE THREAD

**Issue by eloquence** [WeblateOrg/weblate#4745]
**Is your feature request related to a problem? If so, please describe.**
Imagine that you attempt to log in via Weblate via GitHub, but you actually already have a local account with the same name. The error message you see is as follows, which can be a bit confusing:

> Could not complete registration. The supplied authentication, e-mail address or username is already in use for another account. 

**Describe the solution you'd like**

It would be great if the error message spoke to the _specific_ issue that was encountered (e.g., "There is already a user with this email address") and/or offered tips to resolve (e.g., "Please check if you have already registered an account. You can also request a new password, if you have lost your credentials.")

**Additional context**

See report here: https://github.com/freedomofpress/securedrop/issues/5588 of a user being confused by this error message on our Weblate instance

**Comment by nijel** [comment]
This not supported to happen on username collision, the authentication code should automatically generate username like "nijel137e9574ce04448a" (just tested that). In case it doesn't work on securedrop, check SOCIAL_AUTH_PIPELINE settings. This was broken in the past, but got fixed for 3.1, see abc7993f33418bf59f955b37aa8a9c89939d76e1 and #3230.

Regardless, the error message should be more useful in such case.
