### ISSUE TITLE
Optional flag for markdown parsing of string comments

### ISSUE THREAD

**Issue by tnp0** [WeblateOrg/weblate#4753]
**Is your feature request related to a problem? If so, please describe.**

In commit b13c10cfcbeda9a24a1f90407bed34b2ca35ad20 markdown support was added for string comments, noting expected behaviour. Unfortunately for our use case, we have underscores in our string comments referencing parts of the codebase, which get converted into underlines when parsed, making the comments no longer suitable for our needed purpose.

**Describe the solution you'd like**

Would it be possible to add a flag to change the parsing of string comments? eg, markdown, plaintext, etc.

**Describe alternatives you've considered**

As a quick fix we'll probably use CSS to disable the `<em>` tags within the html, but this isn't really practical.

**Additional context**

![image](https://user-images.githubusercontent.com/49878245/97098393-4126a080-1674-11eb-84ba-7b1b4467fa92.png)

Thanks very much.

**Comment by nijel** [comment]
Hmm, maybe markdown is not the best choice here, let's try something between and only avoid highlighting whitespace.
