### ISSUE TITLE
Comments in history

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4758]
https://hosted.weblate.org/changes/?component=po4a-website&project=po4a

There is no topic for comments, and I can't seem to find a list of commented strings.

**Comment by nijel** [comment]
There is a comment added: https://hosted.weblate.org/changes/?component=po4a-website&project=po4a&lang=&action=3&user=

**Comment by comradekingu** [comment]
Right, but there is no "Action" for it (that I can find anyways)
![bilde](https://user-images.githubusercontent.com/13802408/97214544-2874d280-17bb-11eb-9186-f0b529213cfe.png)

**Comment by nijel** [comment]
It's "Comment added" in English and it's selected on the link I've sent.

**Comment by comradekingu** [comment]
Aha, just erroneously translated in Norwegain Bokmål then. Closing closing closing.
