### ISSUE TITLE
YAML error: We don't handle these values: Type: <class 'ruamel.yaml.comments.TaggedScalar'>

### ISSUE THREAD

**Issue by lokha** [WeblateOrg/weblate#4765]
i add this file with strings:  
[messages.ru.zip](https://github.com/WeblateOrg/weblate/files/5445348/messages.ru.zip)

it has the format according to the documentation:  
https://docs.weblate.org/en/latest/formats.html#yaml

```yaml
weblate:
  hello: ""
  orangutan": ""
  try": ""
  thanks": ""
```

but when loading it throws an error:
```
We don't handle these values: Type: <class 'ruamel.yaml.comments.TaggedScalar'> Data: = Previous: weblate->coding.sign.if_variable_equals
```
![image](https://user-images.githubusercontent.com/32991511/97303585-40079600-1863-11eb-9c45-c53ba772f72d.png)

**Comment by nijel** [comment]
It seems that the equals sign should be quoted for some reason. 

Changing 

```
coding.sign.if_variable_equals: =
```

to

```
coding.sign.if_variable_equals: "="
```

should fix the parsing.

**Comment by nijel** [comment]
The proper fix should be https://github.com/translate/translate/pull/4157

**Comment by lokha** [comment]
Wow thanks

I generated this yaml file using snakeyaml on java
thus it was generated
I didn't think that syntax violations are possible

**Comment by nijel** [comment]
I don't think it's syntax violation, it's rather issue in the parser. That should be fixed in the next translate-toolkit release.
