### ISSUE TITLE
Writes that there are 0 strings, but there are 5.000+

### ISSUE THREAD

**Issue by lokha** [WeblateOrg/weblate#4768]
I added a translation component, source language is Russian (Русский)

and if you open the Russian translation page, you can see that strings 0:  
https://weblate.mineland.net/projects/mineland/test4/ru/  
![image](https://user-images.githubusercontent.com/32991511/97365725-ceedd000-18ae-11eb-9b7e-a8bc63b7575f.png)

but I know that there are indeed 5,000+ strings, and you can verify this by clicking the "Translate" button ("Перевести"):  
https://weblate.mineland.net/translate/mineland/test4/ru/  
![image](https://user-images.githubusercontent.com/32991511/97365864-11afa800-18af-11eb-9b92-77de3487f149.png)

I recorded a video demonstrating the problem: https://youtu.be/Es5tDJuiWa8

as well as you can follow my links to make sure of this

**Comment by lokha** [comment]
most likely the problem is in the weak host, or rather the hdd disk

i tried installing weblate on a powerful host with an NVMe disk and the problem did not reproduce

**Comment by nijel** [comment]
Some things happen in background, so maybe reload would address this as well...
