### ISSUE TITLE
Quotation marks in Hebrew are wrong

### ISSUE THREAD

**Issue by fitojb** [WeblateOrg/weblate#4772]
The special-character virtual keyboard in Hebrew includes the Gershayim character instead of quotation marks. Gershayim is used as an abbreviation mark or to signal numerals or transliterations.

https://github.com/WeblateOrg/weblate/blob/b04e0b1fabd6ce48f9e9c67ca486a9a902aa7c49/weblate/trans/specialchars.py#L267

Here it should be `„`, and in

https://github.com/WeblateOrg/weblate/blob/b04e0b1fabd6ce48f9e9c67ca486a9a902aa7c49/weblate/trans/specialchars.py#L312

Here it should be `”`.

If this comes from CLDR, then it should be corrected there as well.

**Comment by nijel** [comment]
According to #406 it was extracted from CLDR, but it seems no longer present there. There seems to be proposal to reimplement this, see http://cldr.unicode.org/development/development-process/design-proposals/delimiter-quotation-mark-proposal

However, that one lists `“…”` as double quoting for Hebrew while you propose `„…”`.

**Comment by nijel** [comment]
Maybe @yarons can comment on this as well...

**Comment by yarons** [comment]
Yup, @fitojb is right.
These quotation marks are not widely used for everyday speakers but these are the correct way according to the Hebrew Language Academy.

Double
---
Opening: „
Closing: ”

Single:
---
Opening: ‚
Closing: ’

Additional important specialchars for Hebrew (added manually):
---
Maqqaf: ־
Gershayim: ״
Geresh: ׳

This change would save me a lot of screen space :).

**Comment by eyalroz** [comment]
I should mention that, with Weblate as currently installed for the Document Foundation, MAQQAF characters are rendered inappropriately: [screenshot](https://redmine.documentfoundation.org/attachments/3002). It's not that they're missing or replaced with another character, but it looks like the glyph is taken from another font family, as its weight is off and so is its vertical position, slightly.

I'm not sure if this is within the scope of the bug, as opposed to quotation marks.

**Comment by fitojb** [comment]
@eyalroz The Weblate webfont doesn’t include Hebrew characters. What you report is obviously our of topic for this issue and should be reported in another bug, but anyway, webpages are quite malleable. Since I don’t like Source Sans, for example, I have a local stylesheet replacing the font; you could do the same thing.
