### ISSUE TITLE
change the source language: git push vs api?

### ISSUE THREAD

**Issue by lokha** [WeblateOrg/weblate#4773]
I want to update the source language strings periodically.

What is the best and most correct way to do it?
1. Push changes to the git repository by updating the language file
2. Use the upload api call with the `method=replace` parameter?  
https://docs.weblate.org/en/latest/api.html#post--api-translations-(string-project)-(string-component)-(string-language)-file-

Is there a performance difference using these 2 approaches?
And in general, which is more correct?

Personally, I would prefer the api call, since it is more convenient, but I have doubts that I am doing the right thing. And I want to do it right.

**Comment by nijel** [comment]
Performance wise these are pretty much same (the only difference is Git repository manipulation - pull or commit). There is no "right" way to do this, just choose whatever fits your workflow. In case the file is maintained in the Git repo, the obvious way is to push it from it. In case it's maintained externally, using API seems better choice.

**Comment by lokha** [comment]
thanks for the answer
