### ISSUE TITLE
Bad sorting indicator on list pages

### ISSUE THREAD

**Issue by afeurra** [WeblateOrg/weblate#4777]
**Describe the bug**
(This is the most minor of all issues, please don't rush on it)
In all pages that present a list (such as [this](https://hosted.weblate.org/languages/)) when you sort the list by clicking on an header (such as "Translated strings") the list is correctly sorted, but the order is reversed.
You can see that when the arrow on the header is downwards (meaning from bigger to smaller) the list goes from smaller to bigger and viceversa.

**To Reproduce the bug**
1. Go to 'https://hosted.weblate.org/languages/'
2. Click once on 'Translated strings' to sort the list
3. See error: the arrow is downwards but the list goes from smaller to bigger
3. Click once again on 'Translated strings' to sort the list
4. See error: the arrow is upwards but the list goes from bigger to smaller

**Expected behavior**
The list should follow the arrow indicator icon.

**Screenshots**
<img width="1273" alt="Schermata 2020-10-29 alle 10 14 01" src="https://user-images.githubusercontent.com/47101794/97548812-e7094080-19cf-11eb-9c36-22a70467b0b5.png">

**Comment by nijel** [comment]
Seems this is not that easy topic: https://stackoverflow.com/q/338166/225718
