### ISSUE TITLE
Button "Lock" does not change to "Unlock" for locked components

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#4786]
**Describe the bug**

I think in previous versions, the button **Lock** in Repo Mgmnt changed to **Unlock** when a component was locked.

**To Reproduce the bug**

Lock component in "Repo"

**Expected behavior**

Button changes from "**Lock**" to "**Unlock**"

**Screenshots**

If applicable, add screenshots to better explain your problem.
![image](https://user-images.githubusercontent.com/26718215/97703963-cfa28400-1ab1-11eb-983e-50fbc8c5b853.png)

**Server configuration and status**

Weblate 4.3.1

**Comment by ilocit** [comment]
I was in the porject and thus managing all components, whereas only one of the four cmoponents was locked.
User error.
System behavior as before and as it should be!

**Comment by nijel** [comment]
The "Lock" button is there as long as there is single unlocked component in the project. It will turn into "Unlock" once all of the components are locked.

**Comment by ilocit** [comment]
I had closed it already. Since it is not an issue.

**Comment by ilocit** [comment]
Sorry for the mixup, and also for re-opening the issue. Not it should be closed and remain closed 👍
