### ISSUE TITLE
Saves vcs to translated strings empty, and then writes "Has been translated"

### ISSUE THREAD

**Issue by lokha** [WeblateOrg/weblate#4795]
**Describe the bug**

I am translating into Ukrainian, I have already translated 23 messages. But every time git gets only empty lines and writes "Things to check Has been translated"  

https://weblate.mineland.net/translate/mineland/mineland/uk/?q=has:check    

![image](https://user-images.githubusercontent.com/32991511/97797014-dd771700-1c21-11eb-9c18-009f7973ce7b.png)

![image](https://user-images.githubusercontent.com/32991511/97797086-8faede80-1c22-11eb-821e-2f93eca67189.png)

**To Reproduce the bug**

It works on weblate on my host 100% of the time, just try to translate Ukrainian and wait for the commit.

**Server configuration and status**

```
 * Weblate: 4.3.1
 * Django: 3.1.2
 * siphashc: 2.1
 * Whoosh: 2.7.4
 * translate-toolkit: 3.1.1
 * lxml: 4.6.1
 * Pillow: 8.0.1
 * bleach: 3.2.1
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.1
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 50.3.2
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.4
 * weblate-language-data: 2020.10
 * html2text: 2020.1.16
 * pycairo: 1.20.0
 * pygobject: 3.38.0
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.19.1
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.11
 * borgbackup: 1.1.14
 * pyparsing: 2.4.7
 * Python: 3.6.10
 * Git: 2.17.0
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.12
 * mysqlclient: 2.0.1
 * Redis server: 3.2.6
 * MariaDB sever: 10.1.47
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: postfix.mineland.net
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://:%5B7UoPbwRh1%7D7t5%5Ep%2B%25y%5DIw0X%29jPUxnXvZ%3B%5BjMY%2Ap@localhost:6379, redis://:%5B7UoPbwRh1%7D7t5%5Ep%2B%25y%5DIw0X%29jPUxnXvZ%3B%5BjMY%2Ap@localhost:6379, regular
 * Platform: Linux 4.9.0-14-amd64 (x86_64)
```

**Comment by nijel** [comment]
I've tried to import your files and it works fine for me - the YAML files are properly updated.

Do you see any errors in the logs? Was Celery process restarted after last update?

**Comment by lokha** [comment]
I tried again and this time the problem did not appear
the only thing i did was restart weblate and celery

and changed the time zone in settings.py, because I noticed that the time in the logs differs from the system one
I changed the timezone so that they match

Could the problem arise due to a timezone difference?

**Comment by nijel** [comment]
No, timezone shouldn't make the difference. What is more likely is that celery process was not restarted on upgrade and was running different code than web server.

**Comment by lokha** [comment]
no longer reproduced

**Comment by lokha** [comment]
after a while the problem began to appear again  
I notice her in 3 languages  
at the moment it spoils the whole translation process

could the problem be related to the errors I receive in my email?  
example error:  
[Gmail - [Weblate] ERROR (EXTERNAL IP)_ Internal Server Error_ _api_translations_mineland_mineland_en_file_.pdf](https://github.com/WeblateOrg/weblate/files/5539875/Gmail.-.Weblate.ERROR.EXTERNAL.IP._.Internal.Server.Error_._api_translations_mineland_mineland_en_file_.pdf)  
[Gmail - [Weblate] ERROR (EXTERNAL IP)_ Internal Server Error_ _search_mineland_mineland_.pdf](https://github.com/WeblateOrg/weblate/files/5539876/Gmail.-.Weblate.ERROR.EXTERNAL.IP._.Internal.Server.Error_._search_mineland_mineland_.pdf)  

but the error says only about English, because I only download English through api
but maybe this problem and the problem "Has been translated" have a common cause?

I get this error quite often:   
![image](https://user-images.githubusercontent.com/32991511/99133038-0be0f300-2621-11eb-904a-72f9e25199a8.png)


https://weblate.mineland.net/projects/mineland/mineland/  

![image](https://user-images.githubusercontent.com/32991511/99133080-2fa43900-2621-11eb-8470-de3023b66561.png)

![image](https://user-images.githubusercontent.com/32991511/99132729-033bed00-2620-11eb-82cc-a2861a6f7799.png)

**Comment by lokha** [comment]
> I've tried to import your files and it works fine for me - the YAML files are properly updated.

perhaps this way it will not be reproduced via file upload

at the moment it appears if you translate strings through this form:

![image](https://user-images.githubusercontent.com/32991511/99133278-0afc9100-2622-11eb-8f05-4c943950723c.png)

**Comment by nijel** [comment]
I'm not sure whether the error is related, but it certainly indicates something is wrong in your setup. MySQL server seems to close connection when Weblate still expects it to be open. Try adjusting the configuration based on https://matomo.org/faq/troubleshooting/faq_183/ (this is first article I found on the topic, it's general MySQL configuration issue not related to the actual application).

**Comment by lokha** [comment]
> I'm not sure whether the error is related, but it certainly indicates something is wrong in your setup. MySQL server seems to close connection when Weblate still expects it to be open. Try adjusting the configuration based on https://matomo.org/faq/troubleshooting/faq_183/ (this is first article I found on the topic, it's general MySQL configuration issue not related to the actual application).

I am still working on fixing this problem.

Regarding mysql 2006 errors, I tried to specify various settings for my mariadb server, nothing helped me.
However, I still fixed the problem when I moved the weblate to another host. There is now also installed mariadb and everything works well, no errors. Perhaps it was in the version of mariadb.

I will leave here information for those who face the same problem. There will be NO errors if you use this version of mariadb:
```
mysql Ver 15.1 Distrib 10.1.47-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

there will be no errors with these mariadb settings:
```
[mysqld]
wait_timeout = 30000
interactive_timeout = 30000
innodb_log_file_size = 512M
max_allowed_packet      = 16M
```

there will be no errors with these weblate database settings (settings.py):
```
        "OPTIONS": {
            # In case of using an older MySQL server,
            # which has MyISAM as a default storage
            "init_command": "SET storage_engine=INNODB",
            # Uncomment for MySQL older than 5.7:
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            # Set emoji capable charset for MySQL:
            "charset": "utf8mb4",
            # Change connection timeout in case you get MySQL gone away error:
            #"connect_timeout": 28800,
        },
```

about the problem "Has been translated" still studying the problem

**Comment by lokha** [comment]
after solving the error with mysql 2006, the bug with the "Has been translated" is no longer reproduced, so this solved the problem

**Comment by lokha** [comment]
this problem came back again after some time

i was wrong when i thought the problem was in the old host

also the problem was not related to mysql error 2006

the true cause of the problem was misuse of the weblate api. I'm not sure if this is a bug, but with this use of api you can shoot yourself in the foot.  
to reproduce the bug, you need to follow these steps:
1. translate any string so that it is not committed
2. execute the api request. upload file with source strings  
<https://docs.weblate.org/en/latest/api.html#post--api-translations-(string-project)-(string-component)-(string-language)-file->
3. done, the translated string from the first step will be lost and marked with the error "Has been translated"

I solved this problem for myself like this:   
adding another api request between steps 1 and 2, which commits the changes to the repository  
<https://docs.weblate.org/en/latest/api.html#post--api-projects-(string-project)-repository->  
with value `{"operation": "commit"}

if this api behavior is not an error, then close this task, otherwise at your discretion. I'm glad I figured out the source of the problem and shared it`

**Comment by nijel** [comment]
> execute the api request. upload file with source strings

Can you please clarify what method do you use here? `source` or `replace`? I assume it's `replace` as it's the code path where I can see this bug, but it would be good to get a confirmation.

**Comment by lokha** [comment]
@nijel method `replace`
