### ISSUE TITLE
Automatic Translation Endpoint in REST-API not working

### ISSUE THREAD

**Issue by Julian-Schaefer** [WeblateOrg/weblate#4798]
Hello there,

in the Documentation of Weblate's REST-API, there is an Endpoint to trigger the automatic Translation of a Component for a specific language (see [Automatic Translation Endpoint](https://docs.weblate.org/en/latest/api.html#post--api-translations-(string-project)-(string-component)-(string-language)-autotranslate-)).

However, when I try to use the Endpoint, I receive the following Error Message:

Status: _405 Method not allowed_
Response:
_{
    "detail": "Method \"GET\" not allowed."
}_

Screenshot:
![weblate-error](https://user-images.githubusercontent.com/11839572/97858478-821b5680-1cff-11eb-9ca0-7352506a94ef.PNG)

I also made sure to install the **Automatic Translation Add-On** in the specific Component, however it is still not working.
![installedaddon](https://user-images.githubusercontent.com/11839572/97858981-3c12c280-1d00-11eb-8137-6522854f77da.PNG)

Any help on this will be greatly appreciated! Thanks.

Weblate-Version:
4.3.1

**Comment by nijel** [comment]
The docs clearly states that you should use POST, not GET....

**Comment by Julian-Schaefer** [comment]
I did use "POST", that's what makes it even more confusing...

![2020-11-02_14h21_14](https://user-images.githubusercontent.com/11839572/97872710-c82fe480-1d16-11eb-8664-978040e352de.png)

**Comment by nijel** [comment]
It ends up being performed as GET, maybe the URL is missing trailing slash and it gets redirected?

**Comment by Julian-Schaefer** [comment]
Stupid me, that was actually the issue, thank you very much!

**Comment by nijel** [comment]
I've adjusted the middleware to avoid redirects on POST in 41c2bdb as that seems to be quite frequent mistake and properly returning 404 in that case might make it more likely people will look at the URL ;-).
