### ISSUE TITLE
Two shortcuts overlap with f.lux

### ISSUE THREAD

**Issue by kyotaro-iijima** [WeblateOrg/weblate#4802]
Search Back (ALT+PgUp) and Search Next (ALT+PgDN) overlaps the brightness adjustment of f.lux.
Can you change it to like ALT + B and ALT + N?
Or it would be nice if users could change the shortcut settings screen and so on.

**Comment by nijel** [comment]
The keyboard shortcuts will always collide with something. The Alt + letter have proven to be problematic on OS X (see https://github.com/WeblateOrg/weblate/issues/1291 and other issues).

I don't think that having this user configurable is way to go - it's something that would require complex code and probably only very few users would use.

What might make sense is to add keyboard shortcuts compatible with [Transifex](https://docs.transifex.com/translation/tools-in-the-editor/#section-keyboard-shortcuts) - Ctrl/Alt + ↓ / Ctrl/Alt + ↑. Would that work for you?
