### ISSUE TITLE
Indicate when a comment is too long

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4824]
Tried posting a comment that was very long, just got "could not paste comment".

**Comment by nijel** [comment]
There is currently limit of 1000 chars, I'm not sure if that's reasonable. Anyway it should be applied to the CodeMirror editor what doesn't seem to happen...

**Comment by comradekingu** [comment]
Ideally the "send" button would not be operative beyond 1000, because sending that much text into the unknown is not a good experience.

**Comment by nijel** [comment]
Before the editor was changed to CodeMirror, the textarea enforced the length. Now just this limits needs to be properly handled by the CodeMirror...
