### ISSUE TITLE
Cmd+M doesn't switch to Machine Translation tab

### ISSUE THREAD

**Issue by kyotarozzz** [WeblateOrg/weblate#4833]
Describe the bug
In Windows Chrome, pressing Ctrl M doesn't switch Weblate to the Machine Translation tab. Instead, it will bring up Chrome's user profile.
Therefore, Ctrl M+Number doesn't work either.
It was working fine about six months ago.

How about changing to Ctrl m?

**Comment by nijel** [comment]
What version do you use? This was supposed to be fixed in 31a9da0f966d0a84455ea180e9ede04edd4c81e5, see https://github.com/WeblateOrg/weblate/issues/3911

**Comment by kyotarozzz** [comment]
I am using Weblate 4.3.2 because I am translating some libre projects in hosted.weblate.org.
