### ISSUE TITLE
My JSON file is reformatted with 4 spaces indent

### ISSUE THREAD

**Issue by thongnv** [WeblateOrg/weblate#4840]
I have my JSON file formatted with 2 spaces indentation. But weblate reformats the file to 4 spaces for indentation.

Expectation: the indentation should be kept.

**Comment by nijel** [comment]
You can configure JSON indentation using addon, see https://docs.weblate.org/en/latest/admin/addons.html#customize-json-output

**Comment by thongnv** [comment]
Thank you for your answer!

**Comment by hovancik** [comment]
How do I reformat it back? I installed the addon on but PR that gets created is still 4 spaces.

**Comment by nijel** [comment]
The installation itself doesn't change anything, the files are changed when being edited.
