### ISSUE TITLE
Keyboard Shortcuts Report and Issues

### ISSUE THREAD

**Issue by kyotarozzz** [WeblateOrg/weblate#4841]
**All keyboard shortcuts test**

I checked #4833, but it's still non-working.
So, I've tried all the keyboard shortcuts for [Keyboard shortcuts](https://docs.weblate.org/en/latest/user/translating.html#keyboard-shortcuts).
All keyboard shortcuts test of latest Windows 10 and Ubuntu 20.04LTS using chrome and new Edge.
Different OS and browsers, but the result was the same.
The experiment was done in a sandbox project of hosted.weblate.org.
I tried an hour ago.

Non-working shortcut
- Ctrl M  (Shows Automatic suggestions tab)
- Ctrl M 1 to 9  (Copy the machine translation of given number)
- Ctrl I 1 to 9  (Ignore one item in the list of failing checks)

Everything else is fine.

**CTRL key problem**

When the CTRL key is pressed, 'Needs editing' checkbox is deactivated on the translation page.
Also, if you press CTRL+Enter to save a page with the 'Needs editing' checkbox already ON, the page will be saved without 'Needs editing' flag.
Therefore, it cannot be saved with the Needs editing flaged on.
However, once the mouse is clicked in the browser, it works normally.
The click doesn't have to be a form, and the timing doesn't matter.
However, even if you click, if you change the page, it will reset and reproduce the problem.

**To Reproduce the problem**

1. Use the mouse or CTRL+arrows to navigate to the next translation page.
2. Display the translation page.
3. Without clicking your mouse, press CTRL+Y to select 'Needs editing' checkbox.
4. Use CTRL+J (Nearby strings) or CTRL+Enter (Save current translation).
5. Deactivate 'Needs editing' checkbox. Or saved without 'Needs editing' flag.

I'm sorry for requesting a fix for the shortcut keys again and again.
The shortcut keys may be difficult to adjust, so it would be nice if you could fix the CTRL key alone.

**Comment by nijel** [comment]
>  The experiment was done in a sandbox project of hosted.weblate.org.

The fix from https://github.com/WeblateOrg/weblate/issues/4833 was not yet deployed there...

All mentioned Ctrl M / I shortcuts do work for me on Chrome and Firefox in my devel environment.

For Ctrl Y, please see https://github.com/WeblateOrg/weblate/issues/3910

**Comment by kyotarozzz** [comment]
Sorry. I guess I spoke too soon. #3910, OK!  I'm looking forward to update.
