### ISSUE TITLE
Language code style does not seem to be applied

### ISSUE THREAD

**Issue by weeblr** [WeblateOrg/weblate#4847]
**Describe the issue**

On my Weblate instance, I added translation language (say French) with a `fr` language code (the default I think, not sure).
Project 1 is using this and language files are output in 

```
/output-folder/fr/fr.language.json
```

Now for a new project (which uses INI files), I need a different output format:

```
/output-folder/fr-FR/fr-FR.language.ini
```

but Weblate keeps outputting the translation in:

```
/output-folder/fr/fr.language.ini
```

NB: The translation process itself works fine, the content of fr.language.ini is the expected one. Issue is only with path and filename of the translation.

**I already tried**

1. For a single test component, I set "Language code style" to "BCP style using hyphen, including country code". no change
2. I figured Weblate did not know the country code anyway, so I **modified** the language code for the French language to `fr_FR` (underscore seems to be what's needed if I look at other languages)
3. Same: output goes to `/output-folder/fr/fr.language.ini`
4. I modified the language code for French to `fr-FR`: same, `/output-folder/fr/fr.language.ini`

**Expected behavior**

Translation should be output in `/output-folder/fr-FR/fr-FR.language.ini`

**Note that for the first project, using json files, output should still be in `/output-folder/fr/fr.language.json`**

** Screenshots **

This is the list of languages I can see now when going to `Languages -> Browse all languages`:

![image](https://user-images.githubusercontent.com/5846185/98809181-6f023800-241d-11eb-8a66-aa434d80d3b3.png)

`French` is what I used initially to create both projects. `French (fr_FR)` appeared after I manually modified the language code on the language "Information" tab.

**Questions**

What am I missing? do I need to specify the country code in some other way? 

Many thanks

**Comment by weeblr** [comment]
Worth mentioning: the **source** language files follow the same, desired convention:

```
/source-folder/en-GB/en-GB.language.ini
```

**Comment by nijel** [comment]
Just to make sure: The setting only affects creating of the files, in won't rename existing files.

On your list you seem to have *both* fr and fr_FR, is that intentional? Weblate doesn't come with definition of fr_FR and should create fr_FR file for fr in case "including country code" is selected. 

I'm not sure how it will end up if you already have that one. It assumes languages simplification is used and the additional languages are not present...

**Comment by weeblr** [comment]
Hi

> Just to make sure: The setting only affects creating of the files, in won't rename existing files.

So if a translation was created with 'fr' and later I realize I need it to be 'fr-FR', it's too late and I have to delete the translation, then add a new one after changing the language code in the list of languages?

> On your list you seem to have both fr and fr_FR, is that intentional? Weblate doesn't come with definition of fr_FR and should create fr_FR file for fr in case "including country code" is selected.

yes and no. At first, only fr was available. Later on, in my second project, I realized I needed fr-FR (not fr_FR actually), so I added 'fr**_**FR' as a language and then tried to change "Language code style" to fr**-**FR.
From then, both versions of fr and fr_FR are showing in the list.

> I'm not sure how it will end up if you already have that one. It assumes languages simplification is used and the additional languages are not present...

What matters to me most is to be able to achieve the desired output path. I already have a feeling I will have to re-do the setup for both project, as existing files path and names won't be modified, right?

So the question now is, what's the best configuration to use. I'm thinking about:

- exporting and then deleting all translations

- Changing the language codes of the languages to fr_FR, es_SP and ru_RU (which are the current languages, there will be more in the future)

- For components needing a long-form code, /fr-FR/fr-FR.language.ini, set Language code style to "BCP with hyphen separator, using language code"

- For those components needing simple codes (ie javascript in my case), /fr/fr.json, then set "Language code style" to "Default based on file format"? will this work if the language code has been set to fr_FR?

If I do it the other way around, and keep the language codes as simple, fr, es or ru, that will work fine for component that needs simple codes in their ouput files. But then how do I setup "language code style" to add the country code? where is the country code coming from?

Thanks

**Comment by weeblr** [comment]
Sorry, I missed that:

> should create fr_FR file for fr in case "including country code" is selected.

1. It does not but then initially, the code was 'fr' and I changed it to "fr_FR" only later
2. I actually need fr-FR with an Hyphen, will this work as well?

If so, I should just leave the language with their default code, set Language code style, delete the translations and import them back so that weblate re-create them with the correct path/names?

**Comment by weeblr** [comment]
Looks like I'm stuck: I cannot change the language code from fr_FR back to fr, as that language definition already exists.

**Comment by weeblr** [comment]
Is it safe to delete the fr language definition using the Django admin and then, still from Django, change the code for the fr_FR back to fr?
Or just safer to delete everything and start from scratch? Not sure how I got into this in the first place...

**Comment by nijel** [comment]
My suggestion would be:

1. Delete one of the translations (either in Weblate or as files in Git). I suggest you remove "fr" as that is the one you don't want.
2. Move all content under "fr" using `weblate move_language fr_FR fr` (see  https://docs.weblate.org/en/latest/admin/management.html#move-language).
3. Delete (now empty) "fr_FR".

All that is based on assumption that you didn't disable SIMPLIFY_LANGUAGES setting, otherwise it will not work properly.

**Comment by weeblr** [comment]
Hi
Thanks for that. I managed to clean it up in a different way, by deleting the xx_XX translations first, then re-creating the proper one and importing back the data - after setting up the Language code style based on the specific project/component needs.

That worked, I have now the desired output for all components. Took only half a day!

The only tricky part here was that the files are modified when one changes that setting, it's only for the initial creation.

Thanks for your help and information provided!
