### ISSUE TITLE
What does new de_DE@rude locale correspond to?

### ISSUE THREAD

**Issue by akien-mga** [WeblateOrg/weblate#4864]
**Describe the bug**

A translator added a `de_DE@rude` locale to my project on Hosted Weblate: https://hosted.weblate.org/translate/godot-engine/godot/de_DE@rude

(*Edit:* As the handful of `de_DE@rude` strings don't seem much different from the 100% complete `de` translation, I'll be removing `de_DE@rude` to de-duplicate, so the above link will likely 404.)

Apart from another match in the "Emote Collector" project, I don't see any reference on the Internet on what the `@rude` specifier means: https://hosted.weblate.org/languages/de_DE@rude/

Is this a feature or a bug? I couldn't find documentation on "rude" in the Weblate docs: https://docs.weblate.org/en/latest/search.html?q=%40rude&check_keywords=yes&area=default#

If `@rude` means the same as "rude" in English, I'm not sure I want a rude German translation of my project :)

**To Reproduce the bug**

1. Go to any project on Hosted Weblate
2. Click "Start new translation"
3. Search "rude"

**Expected behavior**

I'd expect such locale variant not to be present in the "Start new translation" dialog, or there should be more documentation on what it means and why it's relevant.

**Screenshots**

![Screenshot_20201117_121609](https://user-images.githubusercontent.com/4701338/99383889-dbbe7c00-28ce-11eb-9fcc-2013dfe3a4c4.png)

**Server configuration and status**

Hosted Weblate.

**Comment by nijel** [comment]
These are probably rude variants of the locales. See similar question: https://github.com/WeblateOrg/weblate/issues/4715

**Comment by akien-mga** [comment]
I'd welcome the implementation of something like #3559 then, as it's not the first time we get users adding locales which we definitely don't want to use:
- `de_DE@rude` (the given translations have nothing "rude" in them)
- `ru@CARES`
- ` 😃 (generated) (😃) (😃) ` ...

A related question is where does Weblate source those locales from? I have a hard time finding any reference spec on what `@rude` or `@CARES` are supposed to mean.

**Comment by nijel** [comment]
The definitions are either extracted from the translation files (Gettext PO files) or generated by Weblate based on similar locale when the locale is first seen.

Some kind of filtering is scheduled for upcoming release, if you have suggestions how to approach that, please comment on #3559.

**Comment by comradekingu** [comment]
As opposed to the formal type.

**Comment by akien-mga** [comment]
Yeah it does seem to be a joke locale as seen in the only project now using it: https://hosted.weblate.org/translate/emote-collector/bot/de_DE@rude/?&offset=2

The version of it in Godot was using `Sie` and definitely not rude, and more or less the same as the original `de`, so I just removed it (there was only a handful of translated strings).

I'm fine with closing this as superseded by #3559 which is indeed a good solution which I'd like to see implemented. This issue comes up with joke locales like this one, but also with more relevant situations where users needlessly start regional translations for languages which don't warrant it, and thereby duplicate the work on possibly tens of thousands of strings (e.g. `pt` vs `pt_PT`, or `de` vs `de_DE`, `de_AT`, etc. - those variants *can* make sense, but in most projects it would only make sense to support them as copies of `pt` and `de` once 100% complete, to address local variations in the handful of strings where they're warranted). But again, that's what #3559 is about.
