### ISSUE TITLE
Suggest new contributors to watch project

### ISSUE THREAD

**Issue by OscarBeiro** [WeblateOrg/weblate#4866]
**Is your feature request related to a problem? If so, please describe.**
Contributors make their translations, but when new strings are added, they don't know about them until they return to the site.

**Describe the solution you'd like**
When new strings are available to be translated, users should receive a notification asking them if they want to translate the new strings. 

**Describe alternatives you've considered**
If there is such an option, I cannot find it.

**Additional context**
None

**Comment by nijel** [comment]
The notification is there, contributors have to watch the project, see https://docs.weblate.org/en/latest/user/profile.html#notifications

**Comment by OscarBeiro** [comment]
Hi @nijel,

Thanks for your answer. 
We need to make it easy for a contributor to enabling notifications. 
This is not about me getting them. We are talking about a user who does occasional translations. 
What about a kind reminder that they can get a notification when a new string is available? Then you can point weblate to the notifications area, which they probably don't know about.
Or even better, a check to enable this notification from the reminder itself.

Thanks

**Comment by OscarBeiro** [comment]
By the way, support has pointed us here. We are using your Hosted Weblate already.

**Comment by nijel** [comment]
We definitely want to have the notifications opt-in. Suggesting user to subscribe to the translation after his contribution makes sense.

**Comment by comradekingu** [comment]
Possibly an "unwatched" contributions overview would mitigate the effect of not wanting to get e-mails for something.

**Comment by OscarBeiro** [comment]
Looking forward to test it.
Thanks!
