### ISSUE TITLE
API - Note Field

### ISSUE THREAD

**Issue by bilalcorbacioglu** [WeblateOrg/weblate#4871]
**Describe the bug**

As much as seen in the below, each unit has the "note" field (in the API). Our content managers want to put Note for the Units. How we can do this in the Interface? I didn't see any fields for this.

* I can see "Explanation" field. I try to use this, but it relates just Source Language. But I want to write a special note for each language.

```json
	...
	"location": "",
    "context": "alph_a",
    "note": "",
    "flags": "",
    "state": 0,
    "fuzzy": false,
    "translated": false,
    "approved": false,
    "position": 1,
    "has_suggestion": false,
    "has_comment": false,
    "has_failing_check": false,
    "num_words": 1,
	...
```

**Comment by nijel** [comment]
The note is extracted from the translation files, it's read-only in Weblate. There is explanation which you can set per source string and is shown for all translations or you can post comment to each string.
