### ISSUE TITLE
Someone‘s account can't open project page, will show 504 Gateway Time-out

### ISSUE THREAD

**Issue by Pinkuburu** [WeblateOrg/weblate#4874]
**Describe the bug**

Someone‘s account can't open the project page, will show 504 Gateway Time-out
but he can open another project page ，he is the only one account that can't open the project page 

**To Reproduce the bug**

Description should look similar to this:

1. Login his account
2. open project link
3. wait……
4. Will see “504 Gateway Time-out”

**Docker log out**
weblate_1   | celery-main stderr | [2020-11-19 15:30:08,256: INFO/MainProcess] Received task: weblate.utils.tasks.heartbeat[8bba6e00-861b-45f8-965d-0ae4568f9a7b]
database_1  | LOG:  invalid length of startup packet
weblate_1   | uwsgi stderr | [pid: 409|app: 0|req: 16/45] 172.31.0.1 () {60 vars in 1137 bytes} [Thu Nov 19 15:29:35 2020] GET /projects/Work/ => generated 0 bytes in 73221 msecs (HTTP/1.0 200) 10 headers in 0 bytes (0 switches on core 0)
weblate_1   | uwsgi stderr | Thu Nov 19 15:30:48 2020 - ...The work of process 409 is done. Seeya!
weblate_1   | uwsgi stderr | Thu Nov 19 15:30:49 2020 - worker 3 killed successfully (pid: 409)
weblate_1   | uwsgi stderr | Thu Nov 19 15:30:49 2020 - Respawned uWSGI worker 3 (new pid: 414)
weblate_1   | nginx stdout | 172.31.0.1 - - [19/Nov/2020:15:30:59 +0800] "GET /projects/Work/ HTTP/1.0" 499 0 "https://translate.workwebsite.com:8081/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
weblate_1   | celery-main stderr | [2020-11-19 15:31:08,257: INFO/MainProcess] Received task: weblate.utils.tasks.heartbeat[21c1e626-5f64-460c-b37a-7a43067bbf49]
weblate_1   | uwsgi stderr | [pid: 411|app: 0|req: 9/46] 172.31.0.1 () {60 vars in 1164 bytes} [Thu Nov 19 15:29:59 2020] GET /projects/Work/ => generated 0 bytes in 73313 msecs (HTTP/1.0 200) 10 headers in 0 bytes (0 switches on core 0)
weblate_1   | uwsgi stderr | Thu Nov 19 15:31:12 2020 - ...The work of process 411 is done. Seeya!
weblate_1   | uwsgi stderr | Thu Nov 19 15:31:13 2020 - worker 2 killed successfully (pid: 411)
weblate_1   | uwsgi stderr | Thu Nov 19 15:31:13 2020 - Respawned uWSGI worker 2 (new pid: 416)

**Comment by nijel** [comment]
Can you please clarify your issue?

* What version do you use?
* How do you run it? Any reverse proxy in front of it? 
* The log doesn't show the 504 error, however it shows that client closed connection (HTTP 499).

**Comment by Pinkuburu** [comment]
1、install on Ubuntu 16.04.6 LTS by docker image
weblate list_versions
 * Weblate: 4.3.2
 * Django: 3.1.3
 * siphashc: 2.1
 * Whoosh: 2.7.4
 * translate-toolkit: 3.2.0
 * lxml: 4.6.1
 * Pillow: 8.0.1
 * bleach: 3.2.1
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.1
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.5
 * weblate-language-data: 2020.11
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.19.2
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.11
 * borgbackup: 1.1.14
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.6
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.16.12
 * zeep: 4.0.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.1
 * Mercurial: 5.6
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * Redis server: 4.0.14
 * PostgreSQL server: 9.6.20
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.qq.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.4.0-132-generic (x86_64)
2、docker image ports setting 8082:8080
proxy is nginx, nginx setting here:

server {
    listen 8081 ssl;
    # listen 443 ssl;
    ssl on;
    server_name translate.workwebsite.com;
    ssl_certificate /etc/letsencrypt/live/translate.workwebsite.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/translate.workwebsite.com/privkey.pem;
    location / {
        proxy_pass http://127.0.0.1:8082;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Cookie $http_cookie;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    error_page 497 301 https://$http_host$request_uri;
}

3、I think I found the reason why a common user can't open the project page link because I added an Excel format component yesterday, it's including 13440 rows strings. I try to move this excel component to another project a moment ago, then it will be opened, but the new project 504 again.

**Comment by nijel** [comment]
Okay, so it's your nginx reporting 504. Have you considered increasing proxy read timeout there?

**Comment by Pinkuburu** [comment]
Oh!!!!!!!!!!!!!!!!!!!!!!!thank you!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
I forget that……sorry……

**Comment by Pinkuburu** [comment]
So，which setting variable I need setting……I'm so sorry to ask this question……because I am just a rookie on web server……

**Comment by Pinkuburu** [comment]
Ok, I change the Nginx setting like here, now is better, the common user can open the project link, but very slowly, do you have any plan to improve this question……I think it should not be very slow to open the Project page……

server {
    listen 8081 ssl;
    # listen 443 ssl;
   ssl on;
    server_name translate.micateam.cn;
    ssl_certificate /etc/letsencrypt/live/translate.workwebsite.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/translate.workwebsite.com/privkey.pem;
    location / {
        proxy_pass http://127.0.0.1:8082;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Cookie $http_cookie;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 180;
        proxy_read_timeout 180;
        proxy_send_timeout 180;
	keepalive_timeout 180;
    }
    error_page 497 301 https://$http_host$request_uri;
}

**Comment by nijel** [comment]
The initial project load might be slow due to calculating some stats. Besides that, it should load fast. Some stats will be calculated in the background in next release, see 1eeb82433a91db25a41c9f6c119fe1c0ba0b3831, but it can still happen that the user request triggers that earlier than the background task completes.

**Comment by Pinkuburu** [comment]
Oh, I see, thank you very much!!
