### ISSUE TITLE
"Backend not found" when trying to invite users

### ISSUE THREAD

**Issue by nebulade** [WeblateOrg/weblate#4875]
**Describe the bug**

Trying to invite users results in a a 404 page (When Debug is turned on)
The exact message is:
```

Request Method: POST
https://example.com/manage/users/
weblate.wladmin.views.users

Backend not found
```
The newly invited users email does not exist yet. I can see the new user correctly created in the django interface. Deleting that user will send out an email just fine.

The instance is also using LDAP and the auth backend config looks like this:
```
AUTHENTICATION_BACKENDS = (
    "social_core.backends.email.EmailAuth",
    "weblate.accounts.auth.WeblateUserBackend",
)
```

**Server configuration and status**

Weblate installation: on Cloudron version 4.3.1

Any pointers how to debug this further would already help. Thanks!

**Comment by nijel** [comment]
This really looks like `social_core.backends.email.EmailAuth` is not present in the `AUTHENTICATION_BACKENDS` setting. I think the error page lists current settings, so you should be able to verify it there.

**Comment by nebulade** [comment]
Indeed you were right. Well also the github-actions bot then was correct, this being more of a support issue. The underlying issue was that some other config file actually overwrote the AUTHENTICATION_BACKENDS which I was not aware of.
Thanks for the quick turnaround. I will also build a new Cloudron Weblate package to fix this properly now.
