### ISSUE TITLE
Zen editor not saving strings in top to bottom mode

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4884]
As of yesterday, when using Zen, I press tab to go to the next string like usual.
There is no icon to be seen for any string.
The translated text remains in field, but is not saved.

**Comment by nijel** [comment]
Can you try reloading the page? It might be caused by some parts of javascript being cached (what would be still a bug).

**Comment by nijel** [comment]
Confirmed the bug in top to bottom mode.

**Comment by comradekingu** [comment]
That is the one I am using. :) Reloading and clearing cache, changing browser still doesn't save.

**Comment by comradekingu** [comment]
Works now.

**Comment by nijel** [comment]
Fixed by 017d7a85d42ed8a5479362514782a99a7351cefc
