### ISSUE TITLE
Sorting by position won't stay selected

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#4886]
**Describe the bug**

On hosted.weblate.org running Weblate 4.4-dev, the default sorting order of strings appears to be "Position and priority". When I try to change this to "Position", it won't stay selected, but reverts to "Position and priority" (which I find quite frustrating setting to work with, as I'll be jumping around unpredictably).

**To Reproduce the bug**

Happens at least in Weblate/Application and MyPaint/MyPaint on hosted.weblate.org

**Expected behavior**

The selected sorting order stays selected.

**Comment by nijel** [comment]
Can you please clarify where you see this? I've just tested translating and it stays there.

Also, there should be no different between "Position and priority" and "Priority" on Weblate/Application as there are no string priorities set.

**Comment by tjhietala** [comment]
Yes, for Weblate/Application it doesn't matter, but for MyPaint/MyPaint it does, because the developers there make use of priorities.

Checking again, it seems that "Position" stays set if I use the Next and Previous buttons to move between strings. However, to reduce the clicks needed to skip over strings I usually click on the neighbouring strings, and this is where it resets back to "Position and priority".
