### ISSUE TITLE
Language variations formal/informal

### ISSUE THREAD

**Issue by tttp** [WeblateOrg/weblate#4893]
**Describe the issue**
Hi,
Some of my users want a formal/polite way of addressing ("Vous" in french, "Sie" in german...), some want a more informal one "Tu" and "Du")

Is there a way to have two "formal" and "informal" versions of the same language?

And is there a way to automatically default/auto-translate from the one to the other? (as in 90% of the strings, it's going to be the same)? is there a way to automatically use the default "formal" language  on the more informal version but only "translate" the sentences that differ?

And is there a way to "lock/flag" that language, eg "no need to translate/copy-paste all the strings in informal, by default it will take the one from formal?

**I already tried**

I read various issues, and see they are several versions of a language, eg FR, FR_CARE, FR_SCHUMANN, DE@rude, DE_FORM, DE_1901

Is there a "official/blessed" way of handling it? I *think* I'd prefer a "LL@form" rather than "LL_FORM", but whatever is fine

I've seen an issue as discussed at FOSDEM2020 about having somewhat similar issues with the various NL_be/NL_nl... issues. May be the same solution could be used for both?
https://github.com/WeblateOrg/weblate/issues/4864
https://github.com/WeblateOrg/weblate/issues/4715

X+

**Comment by nijel** [comment]
I think that `LL@form` is more correct when speaking about Gettext, while according to BCP 47 it should be `LL-form` (but there is no defined tag for format/informal, so it should be `LL-x-formal`). See for example https://core.trac.wordpress.org/ticket/28303 for (lengthy) discussion on this topic.

When there is some consensus on this, we can add definitions to https://github.com/WeblateOrg/language-data/ to make it easier to use.

**Comment by tttp** [comment]
What's the process of getting a/some consensus?

I don't think it matters that much as long as weblate recommends one way of doing it (and probably try to tame the number of @form -FORM and recommend to migrate to LL-x-formal)

**Comment by nijel** [comment]
There is no formalized process. Usually it is enough when few people agree here ;-)

**Comment by tttp** [comment]
Is there a way to see how many strings/projects are using a language?
I'm trying to get a sense if there is already some consensus, but when randomly checking, found non used language variants, eg

https://hosted.weblate.org/languages/lt_CARES/
https://hosted.weblate.org/languages/fr_STRAUMANN/

on the _FORM, it's the same, those I checked seems to be clone of the non FORM version

if there is a consensus, it's doesn't seem there is an obvious one when looking at the data ;)

**Comment by nijel** [comment]
The cares/straumann are used by few non-public projects. These really should be hidden for most of the users as they are just confusing. This should be done via https://github.com/WeblateOrg/weblate/issues/3559

**Comment by nijel** [comment]
Also, I think that most of the projects decide whether to use formal or non-formal language and don't add both, that's why it's not widely seen so far. For example, none such locale is found among software shipped by Fedora, see https://github.com/WeblateOrg/language-data/issues/103

**Comment by tttp** [comment]
My use case is a campaigning project, and when a new organisation starts a new petition, some wants a formal or informal style, so we need both ;(

**Comment by nijel** [comment]
Ah, I've also answered this topic on StackOverflow five years ago :-), see https://stackoverflow.com/q/28329453/225718

**Comment by nijel** [comment]
I will add definitions for `de@formal` and `de@informal` to our languages data, that seems to be best choice for now.

**Comment by tttp** [comment]
Awesome, thanks.

Do I need to make requests to create new "languages" de@informal and
fr@informal or that will be handled automatically?

**Comment by nijel** [comment]
They will be created automatically on Hosted Weblate once new language data is installed, but that might take some time. You can create translation files with these codes right now and Weblate will handle that gracefully.

**Comment by tttp** [comment]
Hi @nijel, any chance to get these on hosted weblate soon?

**Comment by nijel** [comment]
It should be already there.

**Comment by tttp** [comment]
aah, it's there for german, but not for french

Could you add it for french too? ("tu" vs. "vous") or can I somehow do it
myself?

**Comment by nijel** [comment]
Added. You can start using any language code without being defined in Weblate, see https://docs.weblate.org/en/latest/admin/languages.html
