### ISSUE TITLE
Tags handling in xliff files

### ISSUE THREAD

**Issue by domeav** [WeblateOrg/weblate#490]
Hello,
I'm experiencing an issue with xliff files containing tags in some of their translation units (weblate 1.9, but the issue persists with a fresh git clone). Here is a real-world example with a en/fr unit:

```
<trans-unit id="1108488165166414712" datatype="html" approved="yes">
    <source><x id="XXX_1"/> / <x id="XXX_2"/> events succesfully imported</source>
    <target state="translated"><x id="XXX_1"/> / <x id="XXX_2"/> événements importés</target>
</trans-unit>
```

Weblate handles source string as "/ events succesfully imported", and target string as "/ événements importés", tags are somehow lost during the import. I've been fiddling around with datatypes but it doesn't seem to help.

Moreover, when editing and saving the translation in weblate (let's say the new French translation for this is "duh"), here is what appears in my xliff file:

```
<trans-unit id="1108488165166414712" datatype="html" approved="yes">
    <source><x id="XXX_1"/> / <x id="XXX_2"/> events succesfully imported</source>
    <target state="translated">duh<x id="XXX_1"/> / <x id="XXX_2"/> événements importés</target>
</trans-unit>
```

The new translation is appended at the beginning of the string instead of replacing it.
Thanks for your help!
##

**Comment by mapx** [comment]
Same issue in weblate 2.6 :)

**Comment by nijel** [comment]
That's expected. nobody has fixed it :-).

**Comment by nijel** [comment]
The best approach to address this is probably overriding `set_source`, `get_source` and `get_target` methods in [XliffUnit](https://github.com/WeblateOrg/weblate/blob/070a0cc65705b43a0979cab0525941c60695f334/weblate/formats/ttkit.py#L63) to use `rich_source`/`rich_target` from translate-toolkit. That way the strings would get into Weblate. To make them behave like placeholders, additional flag would be needed on the unit and implementing corresponding check to check and extract the placeables when displaying.

**Comment by PowerKiKi** [comment]
I started working on this, but I would need a bit more guidance. I didn't write Python for years, and I really don't have a good understanding of how data flow.

So far I overrode the method as suggested, and completed `XliffUnit.get_flags`. So, given the following XLIFF unit:

```xml
<trans-unit id="id-1">
    <source xml:space="preserve">source "<x id="INTERPOLATION" equiv-text="{{ angularExpression }}"/>", source.</source>
    <target xml:space="preserve">target "<x id="INTERPOLATION" equiv-text="{{ angularExpression }}"/>", target.</target>
</trans-unit>
```

I ended up the following content in DB:

![image](https://user-images.githubusercontent.com/72603/47705508-dd329280-dc7a-11e8-9436-2aa5370ee080.png)

Is serializing `StringElem` that way a good idea ? What part should I edit to be able to unserialize properly ? would it be the role of a check ?

Is there any documentation describing how the app internals work for developer to help me understand it ?

Also @nijel would you prefer if I created a work-in-progress PR to talk about this ?

**Comment by nijel** [comment]
The easiest approach is probably to serialize it back to xml in `get_source`. Perfect solution would be to store rich structure in the database and have some editor for that, but I'd suggest to stay with simple approach - store the XML in the database and let user edit it with proper checking.

As for docs there is https://docs.weblate.org/en/latest/contributing.html and https://docs.weblate.org/en/latest/internals.html, but these are far from being complete, sorry :-(.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by ramyakrishnapandian** [comment]
> The easiest approach is probably to serialize it back to xml in get_source. Perfect solution would be to store rich structure in the database and have some editor for that, but I'd suggest to stay with simple approach - store the XML in the database and let user edit it with proper checking.
> As for docs there is https://docs.weblate.org/en/latest/contributing.html and https://docs.weblate.org/en/latest/internals.html, but these are far from being complete, sorry :-(.

Hi Nijel,
Could you please help to translate a business central Xliff file using Weblate??

Thanks in Advance

Ramya

**Comment by nijel** [comment]
@ramyakrishnapandian This issue should be fixed, in case you see some similar issue, please open a separate issue. For business inquiries, please ask on sales@weblate.org (see https://weblate.org/support/).

**Comment by sntxerror** [comment]
So, does any XML tag may be inside <source> and <target> nodes? Or XLIFF placeholders <x> tags only?

**Comment by sntxerror** [comment]
@nijel So, for now, does any XML tag inside source/target nodes supported? Or XLIFF placeholders x tags only?

I mean, we are using XLIFF and we have strings like "Plaint text part <someTag attr1="value" /> other plaintext part". Should we add data-type attribute to trans-unit? Or change some config?

Now we have to escape xml  brackets with &lt; and &gt; which annoys our editors and translators...

**Comment by nijel** [comment]
Maybe you're hitting https://github.com/WeblateOrg/weblate/issues/3081?

**Comment by sntxerror** [comment]
> 
> 
> Maybe you're hitting #3081?

no, our goal is to push strings with XML via XLIFF. For example, our source text is:

```xml
Plaint text part <someTag attr1="value" /> other plain text part

<table>
  <tbody
    <tr>
      <td>Cell2 text<td>
      <td>Cell2 text<td>
    </tr>  
  </tbody>
</table>
```
We parse and prepare it and our XLIFF going to be:

```xml
<?xml version="1.0"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="ru"  original="/path/to/source" datatype="plaintext">
    <body>
      <trans-unit id="0">
          <source>Plaint text part <someTag attr1="value" /> other plain text part</source>
      </trans-unit>
      <trans-unit id="1">
          <source>
            <table>
              <tbody
                <tr>
                  <td>Cell2 text<td>
                  <td>Cell2 text<td>
                </tr>  
              </tbody>
            </table>
          </source>
      </trans-unit>
    </body>
  </file>
</xliff>

```

But instead, because Weblate needs escaping for XML in XLIFF we have to send text like this:


```xml
<?xml version="1.0"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="ru"  original="/path/to/source" datatype="plaintext">
    <body>
      <trans-unit id="0">
          <source>Plaint text part &lt;someTag attr1="value" /&gt; other plain text part</source>
      </trans-unit>
      <trans-unit id="1">
          <source>
            &lt;table&gt;
              &lt;tbody&gt;
                &lt;tr&gt;
                  &lt;td&gt;Cell2 text&lt;td&gt;
                  &lt;td&gt;Cell2 text&lt;td&gt;
                &lt;/tr&gt;  
              &lt;/tbody&gt;
            &lt;/table&gt;
          </source>
      </trans-unit>
    </body>
  </file>
</xliff>
```

And the question is, is it possible to use XML content inside XLIFF trans-units without escaping and how to do it properly?

**Comment by sntxerror** [comment]
Other example of our source is `Some text&#160;<i18n:param>date</i18n:param>`, where he use namespaces in tags.

FYI we use monolinguial XLIFF setup and Weblate 4.4 (updating to 4.8 right now)
