### ISSUE TITLE
Logging out of weblate does not log out Keycloak

### ISSUE THREAD

**Issue by thongnv** [WeblateOrg/weblate#4913]
**Describe the bug**

When using Keycloak for authentication, user is logged out of weblate but not logged out of Keycloak

**To Reproduce the bug**

1. Turn off password authentication: `WEBLATE_NO_EMAIL_AUTH: true`
2. Login with Keycloak
3. Click on Log out
4. User is redirected to Keycloak then login again automatically. So basically I cannot log out.

**Expected behavior**

User is redirected to Keycloak login page.

Weblate version: 4.3.1

**Comment by nijel** [comment]
All third-party authentication backends work this way. I don't even think that python-social-auth has support for this. The assumption probably being that you might still use the third-party service for other things than Weblate. 

For example, if you authenticate to Weblate using GitHub, logging out of GitHub is not what I would expect when logging out of Weblate.
