### ISSUE TITLE
Weblate writes generated SSH keys to users home directory

### ISSUE THREAD

**Issue by mgla** [WeblateOrg/weblate#493]
Hello,

In the admin backoffice `/admin/ssh/`, the "Generate" button generates a SSH key pair in `/var/www` (webserver users homedir). In the bitnami stack installation, the directory for  the key creation is `/usr/sbin`.

This causes some issues:
- The web server directory is not writable to the web server user for good reasons. 
- Strange error messages in installations.

SSH key management ist very important for git interaction. It would be very nice to be able to store an existing key in the configuration dialogue (or more than one), or to be able to change the location.

**Comment by Rvanlaak** [comment]
@nijel this also is a bit unclear while using the `import_project` command

**Comment by nijel** [comment]
Can you please file this separately? I doubt it's related here... (most likely you're running import_project as different user than the one running web interface)
