### ISSUE TITLE
CC BY 3.0 license is incorrectly reported as not fulfilling the libre license criterion

### ISSUE THREAD

**Issue by akien-mga** [WeblateOrg/weblate#4932]
**Describe the issue**

I'm being notified that my `godot-engine/godot-docs` component on Hosted Weblate (https://hosted.weblate.org/projects/godot-engine/godot-docs/) using Creative Commons Attribution 3.0 Unported license (CC BY 3.0), matching the original documentation that is being translated, is not using a libre license.

What are the criteria used to define what licenses are libre? IMO CC-BY is a well established libre license for non-software content.

- Fedora guidelines on documentation licensing: https://fedoraproject.org/wiki/Licensing:Main#Documentation_Licenses
- Debian Free Software Guidelines: https://wiki.debian.org/DFSGLicenses#Creative_Commons_Attribution_unported_.28CC-BY.29_v3.0

**I already tried**

There's nothing I can do, the license has been used for both the source content and the translations for many years, I can't change it without consent for *all* contributors as we don't use a CLA.
I also don't see a reason to change it (if I could I'd bump the version to "CC BY 4.0 International", but that's about it).

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce**

1. Go to https://hosted.weblate.org/guide/godot-engine/godot-docs/
2. See warning on unmet conditions to fit into libre software hosting conditions: "Make your translations available under a libre license."
3. The configured license is CC BY 3.0 Unported, like the source strings: https://github.com/godotengine/godot-docs/blob/master/LICENSE.txt

**Expected behavior**

CC BY 3.0 Unported (and other CC BY, CC BY-SA, and CC0 versions) should be considered libre.

**Screenshots**

![Screenshot_20201128_124921](https://user-images.githubusercontent.com/4701338/100514833-24e8b880-3178-11eb-8776-73919005104b.png)
![Screenshot_20201128_124935](https://user-images.githubusercontent.com/4701338/100514837-2e722080-3178-11eb-9040-6ed39fde4d34.png)

**Server configuration and status**

On Hosted Weblate.

**Comment by nijel** [comment]
We currently rely on [SPDX](https://spdx.org/licenses/) on this and only  CC-BY-4.0 is marked there as FSF Free/Libre.

>  Fedora guidelines on documentation licensing

It mentions only version 4.0. On the other side, Debian has 3.0...

**Comment by akien-mga** [comment]
Hm, that's a bummer. I'll see with our legal counsel if there's anyway we can easily upgrade to CC BY 4.0.

SPDX bases its assessment on the FSF's, which doesn't mention anything about earlier versions: https://www.gnu.org/licenses/license-list.en.html#OtherLicenses
They only mention CC-BY-4.0 as there's indeed no reason to use an earlier version, but there's no argumentation on why CC-BY-3.0 or earlier would actually be nonfree.

**Comment by akien-mga** [comment]
Generally speaking though I don't think that SPDX's listing is the most reliable on to assess the license of content which can be licensed like documentation instead of like software. While the FSF does talk about documentation and other non-software work, this is a very late addition to their guidelines (2015) and they've historically had an ambiguous relationship to non-software licensing terms.

The other source that SPDX relies on, the OSI-approved licenses, is also focused solely on software and doesn't include any Creative Commons license.

**Comment by nijel** [comment]
There are more licenses which status is questionable in SPDX - for example [Beerware](https://fedoraproject.org/wiki/Licensing/Beerware) is also not marked as libre. We used to check licenses manually in the past, but that doesn't scale and the only useable source for this I found was SPDX. We might need to add some exceptions...

**Comment by akien-mga** [comment]
Thanks @nijel!
