### ISSUE TITLE
xliff : bad weblate key from `xliff/file//trans-unit/@resname` (same resname in two file tag)

### ISSUE THREAD

**Issue by apourche** [WeblateOrg/weblate#4937]
**Describe the bug**

Importing an xliff file results in the determination of `Key`s by Weblate, associated with each `<trans-unit>` tag.
This determination seems to be based on `trans-unit /@resname` if it exists, **without taking into account** the current tag `<file>` context.
The xliff standard does not specify this rule or global uniqueness of `@resname`. On the other hand, she clearly speaks of the uniqueness of `@id` **in the context of a `<file>` tag** (http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#trans-unit).

So, for `@resname`, it would make sense to only enforce their uniqueness in the context of a `<file> `tag.

The determination of `Key`s by Weblate would become:
```
key = {file/@original} / {trans-unit/@resname}
```

**To Reproduce the bug**

1. Import _Initial XLIFF file_ (see below) as 'translate document' component
2. Problem : Only one `Source string` is created for the two `<trans-unit>` with same `@resname` in two different `<file>` tag
Confirmation of the problem (bad check) : `The component contains several duplicated translation strings.`
![image](https://user-images.githubusercontent.com/25720810/100542651-9180b780-324b-11eb-9657-cb74700c4b67.png)
![image](https://user-images.githubusercontent.com/25720810/100542661-a8270e80-324b-11eb-80d2-cbe311d1c80d.png)

3. Consequences of this problem: translation and export in another language produces an incomplete file, not processing the strings considered as duplicated (wrongly) :
![image](https://user-images.githubusercontent.com/25720810/100542698-ef150400-324b-11eb-8a69-435c11f26904.png)

**Expected behavior**

The determination of `Key`s by Weblate would become:
```
key = {file/@original} / {trans-unit/@resname}
```
...or schould be configurable

**Screenshots**

Initial XLIFF file  :
```xml
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2" xmlns:scxlf="extXliff">
    <file original="/rep1/myFile1.xml"  source-language="fr" datatype="plaintext">
        <body>
            <trans-unit id="1" resname="str1">
                <source xml:space="preserve">str1</source>
            </trans-unit>
            <trans-unit id="2" resname="strA">
                <source xml:space="preserve">strA</source>
            </trans-unit>
        </body>
    </file>
    <file original="/rep1/myFile2.xml"  source-language="fr" datatype="plaintext">
        <body>
            <trans-unit id="1" resname="str1">
                <source xml:space="preserve">str1</source>
            </trans-unit>
            <trans-unit id="2" resname="strB">
                <source xml:space="preserve">strB</source>
            </trans-unit>
        </body>
    </file>
</xliff>
```

**Server configuration and status**

 * Weblate: 4.3.2
 * Django: 3.1.3
 * siphashc: 2.1
 * Whoosh: 2.7.4
 * translate-toolkit: 3.2.0
 * lxml: 4.6.1
 * Pillow: 8.0.1
 * bleach: 3.2.1
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.1
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.5
 * weblate-language-data: 2020.11
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.19.2
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.11
 * borgbackup: 1.1.14
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.6
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.16.12
 * zeep: 4.0.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.1
 * Mercurial: 5.6
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * Redis server: 6.0.9
 * PostgreSQL server: 13.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: relay-01.kelis.fr
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.4.0-54-generic (x86_64)

Thank you for your answer

**Comment by nijel** [comment]
It was introduced by 6190db4ce64568b7ae03486bb46bdd82095c20b1, see #2218 and #2380. The Xliff specification does not define its uniqueness at all and Weblate currently assumes it's unique in the whole Xliff file. And nobody complained so far :-).

In case we would strictly follow the specification, there are no requirements on resname being unique, so it should not be used at all...

**Comment by apourche** [comment]
Thank you for your reply @nijel. The limit of standardization, and their interpretation ... :)

http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#resname :
```
Resource name - Resource name or identifier of a item. For example: the key in the key/value pair in a Java properties file, the ID of a string in a Windows string table, the index value of an entry in a database table, etc.
```
Without considering the uniqueness of `@rename` in the <file>, all of these examples are wrong : it becomes impossible to have a single xliff dealing with 10 different java properties file (with potential redundancy of sring).

Hopefully xliff2.0 will be more explicit on this topic :)

We will therefore modify our xliff files to make them compatible with this weblate rule...

Cordially.

ps: I very recently discovered weblate, and did not take long to choose it compared to Pootle. Great job!
We will use weblate for the translation of the different components of our tool (libre software) : https://scenari.software/

**Comment by nijel** [comment]
> Without considering the uniqueness of @rename in the <file>, all of these examples are wrong : it becomes impossible to have a single xliff dealing with 10 different java properties file (with potential redundancy of sring).

That's valid point. On the other side the existing implementation is there for two years and changing the behaviour would be a breaking change for existing users. 

> Hopefully xliff2.0 will be more explicit on this topic :)

It doesn't see to be the case - the attribute name has changed, but the description is pretty much same: http://docs.oasis-open.org/xliff/xliff-core/v2.1/os/xliff-core-v2.1-os.html#name

**Comment by nijel** [comment]
I don't see big enough reason to change the behaviour now, but this should be at least documented.
