### ISSUE TITLE
"ignore-same" not work

### ISSUE THREAD

**Issue by noxmoe** [WeblateOrg/weblate#4941]
weblate version: Weblate 4.3.2

I use api (PUT /api/units/(int:id)/) with "extra_flags":"ignore-same" to update enties. But weblate still mention "Unchanged translation".

**Comment by nijel** [comment]
Did the PUT succeed? Looking at the code it seems to correctly trigger checks update on flags change.

**Comment by noxmoe** [comment]
Yes, It returns 200 and target has been update.

**Comment by nijel** [comment]
The extra_flags can be changed only on source units, see https://docs.weblate.org/en/latest/api.html#patch--api-units-(int-id)-

It seems to be silently ignored when changing translation units though...
