### ISSUE TITLE
What does the statistics at the glossary mean?

### ISSUE THREAD

**Issue by KadAnna** [WeblateOrg/weblate#4942]
![glossary-statistics](https://user-images.githubusercontent.com/70368530/100616267-20a7d100-3319-11eb-9f3a-b4daae1923a1.jpg)
**Describe the issue**
the number / statistic info at a glossary shows "mysterious" value - there is about 140 entries in the glossary - the number shows 1152.

I imagine it would shouw number of entries / words.

**Comment by nijel** [comment]
It seems to be wrongly calculated...
