### ISSUE TITLE
Exported XLIFF has incorrect <file ... target-language=*> property 

### ISSUE THREAD

**Issue by bryceco** [WeblateOrg/weblate#4945]
I'm exclusively using XLIFF files, not strings files. When a translator creates a new language based on my "en" XLIFF the new language-specific XLIFF doesn't contain correct "target-language" properties in \<file\> tags. The first is correct, but all others remain "en".

**To Reproduce the bug**

My app is hosted here: https://hosted.weblate.org/projects/go-map/app/
Select "Start a new translation"
Push the XLIFF to the upstream repository.
grep "target-language" *.xliff and you'll see many instances of target-language="en"

**Expected behavior**

target-language should match the target language instead of "en"

**Comment by nijel** [comment]
Hopeffully, this should be fixed by https://github.com/translate/translate/pull/4184
