### ISSUE TITLE
Could not find source unit

### ISSUE THREAD

**Issue by TheYunus** [WeblateOrg/weblate#4950]
I installed weblate server on my local machine and configured a new project successfully. The project uses resx files. When I click "Start new translation". I get the following error message. The error occurs at the location of Monolingual base language file. There are two files.

1) Index.cs.resx
2) Index.en.resx

Request Method: | POST
-- | --
http://127.0.0.1:8000/new-lang/e_receipt-web-portal/all-languages/
3.1.1
DoesNotExist
Could not find source unit
/home/weblate/weblate-env/lib/python3.7/site-packages/weblate/trans/models/component.py, line 905, in get_source
/home/weblate/weblate-env/bin/python3
3.7.3
['/home/weblate/weblate-env/lib/python3.7/site-packages/git/ext/gitdb',  '/home/weblate',  '/home/weblate/weblate-env/bin',  '/home/weblate/weblate-env/lib/python37.zip',  '/home/weblate/weblate-env/lib/python3.7',  '/home/weblate/weblate-env/lib/python3.7/lib-dynload',  '/usr/lib/python3.7',  '/home/weblate/weblate-env/lib/python3.7/site-packages',  '/home/weblate/weblate-env/lib/python3.7/site-packages/gitdb/ext/smmap']
Tue, 01 Dec 2020 10:09:25 +0100

Variable | Value
-- | --
Unit | <class 'weblate.trans.models.unit.Unit'>
create | {'content_hash': 4037590963198313610,  'context': 'Access by Bank card',  'flags': '',  'location': '',  'note': '',  'position': 1,  'source': 'Přístup prostřednictvím bankovní karty',  'target': 'Přístup prostřednictvím bankovní karty'}
id_hash | -2656145529178347471
self | <Component: E_Receipt Web Portal/All Languages>
source_units | <django.db.models.fields.related_descriptors.create_reverse_many_to_one_manager.<locals>.RelatedManager object at 0x7f6622286cf8>

**Comment by nijel** [comment]
Please upgrade. This code had bugs in previous releases and has been rewritten for 4.3.

**Comment by TheYunus** [comment]
thank you, it worked after upgrade
