### ISSUE TITLE
Support for Burmese in automatic suggestions

### ISSUE THREAD

**Issue by brockfanning** [WeblateOrg/weblate#4952]
I'm not sure if this is a Weblate issue, or a hosted.weblate.org issue, or a problem with third-party services, or just expected behavior. So feel free to close this if appropriate!

**Is your feature request related to a problem? If so, please describe.**

On hosted.weblate.org it appears that Burmese (my) is not supported in the "automatic suggestions" feature. None of the web services return any suggestions - only the Weblate translation memory.

**Describe the solution you'd like**

If possible it would be great to get Burmese support there. I was expecting to at least see a Google Translate result, since I can get translations from Burmese on Google Translate directly.

**Describe alternatives you've considered**

We can always go directly to Google Translate, but this feature would add convenience.

**Comment by nijel** [comment]
It does work for me:

![image](https://user-images.githubusercontent.com/212189/100756089-2b339a80-33ed-11eb-98e8-248a302403fb.png)

**Comment by brockfanning** [comment]
Thank you for the quick response @nijel! It is working for me as well. Sorry for the noise - I'll close this.
