### ISSUE TITLE
Bulk removing of addons in lots of components

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#4959]
**Describe the issue**

I have some addons installed in all my components that I want to remove everywhere after an upgrade.

**I already tried**

We are already using `weblate install_addon` command internally and I was expecting to have a similar `weblate remove_addon` command: in my case it would be enough to use since I already have a list of components for some scripts. 
I also found that there's apparently a `WEBLATE_REMOVE_ADDONS` variable (https://docs.weblate.org/en/latest/admin/install/docker.html?highlight=addons#envvar-WEBLATE_REMOVE_ADDONS) but it would be only for docker? And there's no much info about using that one.

**Comment by nijel** [comment]
`WEBLATE_REMOVE_ADDONS` removes them from [WEBLATE_ADDONS](https://docs.weblate.org/en/latest/admin/config.html#weblate-addons), you can do the same in your configuration.

The proper solution would be API for addons, which is planned, see https://github.com/WeblateOrg/weblate/issues/3948

**Comment by surli** [comment]
>  you can do the same in your configuration.

OK so it just manipulates the `WEBLATE_ADDONS` array. We agree that removing an addons from this array does not uninstall it, right? I commented out one of the addons and I got an error when trying to get access to the Addons Management UI on one of the component where this addon was installed: I guess it's expected?

> The proper solution would be API for addons, which is planned, see #3948

Sounds great :+1:

**Comment by nijel** [comment]
I was expecting that it would cause failures, that's why I haven't suggested it as a solution...

**Comment by surli** [comment]
> I was expecting that it would cause failures, that's why I haven't suggested it as a solution...

ok thanks for the confirmation. Closing the issue then since it's a duplicate of #3948.
