### ISSUE TITLE
Missing documentation: How to manually update .pot file?

### ISSUE THREAD

**Issue by mikkorantalainen** [WeblateOrg/weblate#4962]
**Describe the issue**

I'm trying to use Weblate without trusting it to access the real git repository I'm using (neither push nor pull). I was able to submit existing messages.pot and partial localization .po files using the zip package upload while adding a component.

However, the method to update the messages.pot without using git repository connection is non-existant or the UI is hidden so well that I cannot find it.

**I already tried**

- [X] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
- Note that I'm looking for a way to update the .pot file only, I don't need msgmerge which is an existing add-on.
- I would have expected to see option to upload new .pot file in component view "Files" dropdown menu. Currently it seems to only contain option "Download translation files as ZIP file". Another option would be "Manage" dropdown menu or "Manage" -> "Settings" -> "Files" view.
- Documentation at https://docs.weblate.org/en/weblate-4.3.2/user/files.html#upload-method describes a feature called "Update source strings" which is not available (maybe because I have selected "File format" "gettext PO file" in component Manage->Settings->Files view). My source strings (msgid) are "developer english" and there's en.po for proper English localization, too.

**To Reproduce**

1. Create component with option "Upload translation files" and upload file all.zip containing messages.pot and collection of .po files.
2. Select "Version control system" option "No remote repository"

There appears no way to upload a new messages.pot file when I add new base strings. **If the only supported method is to always create new component without version control connection this should be documented.**

My intent is to submit new messages.pot into weblate and collect modified translations using "Download translation files as ZIP file" from the component view.

**Server configuration and status**

$ lsb_release -d
Description: Ubuntu 20.04.1 LTS

$ pip show weblate
Name: Weblate
Version: 4.3.2
Summary: A web-based continuous localization system with tight version control integration
Home-page: https://weblate.org/

**Comment by nijel** [comment]
In case you want to replace single file, use "Replace existing translation file" on upload. For monolingual translation, it will automatically update it. For bilingual you want to use msgmerge to update the translation files.

**Comment by mikkorantalainen** [comment]
I have gettext bilingual setup with 7 translated languages (.po files) + one "messages.pot" file. The `msgid` values are in English but may contain typos or not-so-fluent text and we have en.po to fix those issues so it's arguable that this is actually monolingual project instead.

When the source code is updated and I run xgettext to include new 'msgid' strings into messages.pot, how I'm supposed to get all languages to have empty translations for the new strings? Is the expected way to really use `msgmerge` add-on and just update any random language in Weblate UI with a file that contains the new `msgid` without translation?

If this is indeed the expected workflow, it would deserve a paragraph or two in the official documentation.

I would have expected some UI where I can drop the new messages.pot file. Preferably at the component level, not on a single language level because the template file is shared by all languages.

**Comment by nijel** [comment]
Yes, with traditional Gettext workflow, you are supposed to run msgmerge. See https://docs.weblate.org/en/latest/devel/gettext.html or https://www.gnu.org/software/gettext/manual/html_node/Overview.html

**Comment by mikkorantalainen** [comment]
Do you understand that in my opinion the weblate UI should have different UI for sending the template (shared between all languages) and another UI for sending the translation for a single language?

Creating a new component does already work but updating existing component to use new messages.pot file has usability problems in the Weblate UI in my opinion.

**Comment by nijel** [comment]
The interface is there on the source language. I've just noticed that there is a bug that it doesn't show the "Update source strings" in some situations: 42bc1bc2a1161f48b65be4aed2873f239dcf8591

**Comment by nijel** [comment]
Just go to the source language and you can upload it there.

**Comment by IceflowRE** [comment]
This was closed as stale. Was a way added to update pot files manually with the web interface?

**Comment by gpatel-fr** [comment]
@IceflowRE 
I don't know but i just stumbled on the same issue and it worked with the Python interface by specifiying the 'en' language explicitly, like this:
```
wlc upload --method source  -i /mylocalproject/locale/mylocalproject.pot myweblateproject/myweblocateprojectcomponent/en
```
note that in my local project files, I don't have a 'en' subdirectory under /mylocalproject/locale, there are only subdirectories for the localized versions, de_DE, fr_FR, it_IT, en_GB, und so weiter. The 'en' suffix is only needed by weblate, and uploading to it triggers an update of the localized versions on Weblate. This is not true if you upload a localized language, the 'master' version is updated automatically but not the other localized versions. In the Python wlc utility there is no way to upload to the component itself, it is denied. But uploading to the 'en' pseudo language works as intended. This is a bit complicated to grasp, yes, and the documentation could be more explicit on this detail.

I think that it would be worth a try to upload to the 'en' language in the Web UI. I'd give it a 90% chance for it to work.
Good luck.
