### ISSUE TITLE
Add number for Needs editiong and For review in overview page

### ISSUE THREAD

**Issue by KadAnna** [WeblateOrg/weblate#4965]
**Is your feature request related to a problem? If so, please describe.**
As a translator, I would like to see at first glance how much work is needed - how many strings need my attention.

**Describe the solution you'd like**
On the language / component overview bar, I would like to see a number for number of strings that need editing and for strings waiting for review.

![addstattobar](https://user-images.githubusercontent.com/70368530/100996690-a74af100-3559-11eb-9774-5ba3be35392f.jpg)

**Comment by nijel** [comment]
It's there, the example you've posted is fully translated, so there is nothing to show:

![image](https://user-images.githubusercontent.com/212189/100999734-61902780-355d-11eb-8549-43f3ad3f6028.png)

**Comment by comradekingu** [comment]
@KadAnna The top option ~"Hide completed entries" https://hosted.weblate.org/accounts/profile/#preferences will hide those, so you can focus on the ones needing edits. :)
