### ISSUE TITLE
Incorrect language being assigned during translation creation

### ISSUE THREAD

**Issue by jojurajan** [WeblateOrg/weblate#4966]
**Describe the bug**

If we have two languages which vary by case, it leads to an incorrect language being returned back.

**To Reproduce the bug**

Description should look similar to this:

1. Create three custom languages, say `xx-AA`, `xx-aa` and `xx_AA`.
2. Now try creating a new translation for a component using either `xx-AA` or `xx-aa`.
3. You should see `xx_AA` being used for translation.

**Expected behavior**

The translation should use the language specified during creation.

**Screenshots**

-N-A

**Server configuration and status**

Weblate installation: weblate.org service / Docker / PyPI / other

```
 * Weblate: 4.3.2
 * Django: 3.1.3
 * siphashc: 2.1
 * Whoosh: 2.7.4
 * translate-toolkit: 3.2.0
 * lxml: 4.6.1
 * Pillow: 8.0.1
 * bleach: 3.2.1
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.1
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.5
 * weblate-language-data: 2020.11
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.19.2
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.11
 * borgbackup: 1.1.14
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.6
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.16.12
 * zeep: 4.0.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.1
 * Mercurial: 5.6
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * Redis server: 6.0.6
 * PostgreSQL server: 9.6.18
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: amqp://<user>:<password>@host.docker.internal:5672, redis://host.docker.internal:6379/1, regular
 * Platform: Linux 5.4.39-linuxkit (x86_64)
```

**Weblate deploy checks**

```
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail ([Errno 99] Cannot assign requested address), please check EMAIL_* settings.
	HINT: https://docs.weblate.org/en/weblate-4.3.2/admin/install.html#out-mail
?: (weblate.E019) The Celery does not process tasks, or is too slow in processing them.
	HINT: https://docs.weblate.org/en/weblate-4.3.2/admin/install.html#celery

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.
?: (security.W019) You have 'django.middleware.clickjacking.XFrameOptionsMiddleware' in your MIDDLEWARE, but X_FRAME_OPTIONS is not set to 'DENY'. Unless there is a good reason for your site to serve other parts of itself in a frame, you should change it to 'DENY'.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.3.2/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.3.2/admin/backup.html
```

**Exception traceback**

**Additional context**

The issue arises from the fact that we don't check for an exact case-sensitive match of the provided code.

**Comment by nijel** [comment]
I'm not sure that introducing support for case-sensitive language names is a good approach. It will definitely not work with MySQL, which has all lookups case-insensitive anyway. I'm not aware of any other code that would rely on language codes being case-insensitive, but that doesn't mean there is none.

What is wrong on having just a single language defined in Weblate instead of three of them? Is there some translation where you will want to have more of these?

**Comment by jojurajan** [comment]
A single language defined in Weblate would have been the best approach in this case, but we need to support these case-sensitive locales for backward compatibility during the transition period from our in-house solution to Weblate.

The only reason we want to even add these variations is for backward compatibility with existing APIs.

I understand that MySQL might not natively support this unless we use a binary collation for the column. In our case, the data is stored in PostgreSQL which supports this natively.

Is there some other way to support this functionality without adding the case sensitive query change in https://github.com/WeblateOrg/weblate/pull/4967 ?

**Comment by nijel** [comment]
The file names can contain any of `xx-AA`, `xx-aa` or `xx_AA`, Weblate would map that to a single language on it's side. The only tricky party is creating new translations in Weblate, but since 4.4 you will be able to customize this as well using https://docs.weblate.org/en/latest/admin/projects.html#project-language-aliases

**Comment by jojurajan** [comment]
If we could use the code provided in the translation creation request, instead of trying to parse it from the generated filename, I think we could sidestep this issue in the first place. 

But I suppose, there might be forced updates which would revert the translation to use the language code generated by the filename.

I think that was the main issue behind https://github.com/WeblateOrg/weblate/issues/4861, the difference between the translation create API specified language and the language generated from parsing the filename created by that API.
Because we have different file naming conventions for the various formats, it might not be feasible to get the actual language code, unless we put limitations on possible custom language codes.

**Comment by nijel** [comment]
Okay. I still think that having the language defined just once and handling differences for file creation by [language aliases](https://docs.weblate.org/en/latest/admin/projects.html#project-language-aliases) is a cleaner approach. On the other side your proposed change is not really problematic, so if you prefer it this way, let's merge it.
