### ISSUE TITLE
Weblate does not read language strings from INI/JSON file

### ISSUE THREAD

**Issue by kenygamer** [WeblateOrg/weblate#4970]
**Describe the issue**

I have just finished installing Weblate. I've created a new project, as my intention is to link Weblate a my GitHub repository (one of the VCS that you support).
The goal is to let users freely translate strings and push these back live to GitHub. My production branch is stable and my dev branch is "dev". At the moment, the language file resides on both branches, with that said my stable branch is always even or behind dev.
To accomplish that it seems that I'll be needing to use continuous localization (I'm still new), so I've created a new branch where I'll just have the language files for Weblate to pull and push. However when I confiugure a branch and add the file, it first:

1) Weblate not detect my PHP ini file, and did not show it in the dropdown either.
2) When I chose JSON, it found it, but did not detect any strings. I also tried uploading the JSON myself in the project panel and it didn't add any new strings.

I appreciate you helping me with this.

**I already tried**

I've searched all the docs, there's not enough information.

**Server configuration and status**
 * Weblate: 4.3.2
 * Django: 3.1.3
 * siphashc: 2.1
 * Whoosh: 2.7.4
 * translate-toolkit: 3.2.0
 * lxml: 4.6.1
 * Pillow: 8.0.1
 * bleach: 3.2.1
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.2
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 50.3.2
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * Platform: Linux 4.15.0-123-generic (x86_64)

**Comment by kenygamer** [comment]
i'm non-profit, sorry,

**Comment by nijel** [comment]
> Weblate not detect my PHP ini file, and did not show it in the dropdown either.

You can still configure it manually, see https://docs.weblate.org/en/latest/formats.html#ini-translations

Generally, it's impossible to give you any advice without knowing more information about your repository - naming of the files and  their actual content.

> I also tried uploading the JSON myself in the project panel and it didn't add any new strings.

Most upload methods do not add new strings, see https://docs.weblate.org/en/latest/user/files.html#import-methods

> i'm non-profit, sorry,

We do have discounts for non-profits and gratis plan for libre projects, see https://weblate.org/hosting/#libre

**Comment by kenygamer** [comment]
@nijel

1) I have a simple JSON file, with about 3,000 `key => value` pairs. The key is the ID like POT is `msgid’ and the value is the string that needs to be translated like `msgstr` in POT.

The INI file is the same, just with comments somewhere.

When I go to files, "load new translation" and add one pf the files, it gives me this error:

```
No strings were imported from the uploaded file.
```

2) I want to make a branch for Weblate specifically and let Weblate pull and push the translation files itself. How do I do this?

3) I'd also like to add admin approval for every string translated by a normal user. How do I do this?

**Comment by nijel** [comment]
1. Please read https://docs.weblate.org/en/latest/user/files.html#import-methods, apparently you are choosing something different than what you want.

3. Choose whatever workflow you prefer and enable it as described in the docs: https://docs.weblate.org/en/latest/workflows.html

**Comment by kenygamer** [comment]
@nijel In conclusion, INI files cannot be loaded by Weblate. I had to use JSON (worked for repo as well as for manual upload). It is not a type of upload allowed nor is it detected in the repository. I'll have to port everything to JSON...

**Comment by kenygamer** [comment]
2. When I edit a string from Weblate, then push to GitHub, the string line is removed from the file it was in (`.json` not Weblate). Do you know why this happens?

**Comment by nijel** [comment]
Generally, INI files work just fine, see https://docs.weblate.org/en/latest/formats.html#ini-translations. If you have some specific issues with some specific INI files, it's good idea to describe these with reasonable amount of detail (what error you get) and sample of such format.

**Comment by kenygamer** [comment]
@nijel If you mind, I've listed all my questions.

```
# timeonline-*
timeonline = "You have been online {% 0} in the specified time."
timeonline-other = "{% 0} has been online {% 1} in the specified time."
listuperms-none = "{% 0} does not have any player permissions."
listuperms-list = "List of all player permissions from {% 0} ({% 1} / {% 2})"
```

 I moved all strings to the GitHub root folder. It now worked.

1) It comes to my attention that I edit a string it edits in all the languages, I only want to edit the string of my specific language.

2) I also want so when I add a string I want it to add automatically in all the other languages so users can edit it.

3) When I edit a string and push to GitHub, the line of the string is removed.


4) Are translated strings just a reference? When I edit a string, it says "translation ended". Since all other languages ​​aren't translated I need to change everything to not translated. How can I do that?

**Comment by nijel** [comment]
That doesn't look like a INI file - it lacks section header.

**Comment by kenygamer** [comment]
@nijel INI files don't need a section header.  I use my INI file without any sections perfectly. Do you have the answer to the other four questions?

**Comment by nijel** [comment]
In translate-toolkit/Weblate they need to have sections. In case you don't have them, you can use [Java properties](https://docs.weblate.org/en/latest/formats.html#java-properties) or [Joomla translations](https://docs.weblate.org/en/latest/formats.html#joomla) formats instead of full features INI.

**Comment by kenygamer** [comment]
> In translate-toolkit/Weblate they need to have sections. In case you don't have them, you can use [Java properties](https://docs.weblate.org/en/latest/formats.html#java-properties) or [Joomla translations](https://docs.weblate.org/en/latest/formats.html#joomla) formats instead of full features INI.

@nijel I am going to try with that. 

1. It comes to my attention that I edit a string it edits in all the languages, I only want to edit the string of my specific language.

2. I also want so when I add a string I want it to add automatically in all the other languages so users can edit it.

3. When I edit a string and push to GitHub, the line of the string is removed.

4. Are translated strings just a reference? When I edit a string, it says "translation ended". Since all other languages ​​aren't translated I need to change everything to not translated. How can I do that?

**Comment by kenygamer** [comment]
> In translate-toolkit/Weblate they need to have sections. In case you don't have them, you can use [Java properties](https://docs.weblate.org/en/latest/formats.html#java-properties) or [Joomla translations](https://docs.weblate.org/en/latest/formats.html#joomla) formats instead of full features INI.

@nijel I am going to try with that. 

1. It comes to my attention that I edit a string it edits in all the languages, I only want to edit the string of my specific language.

2. I also want so when I add a string I want it to add automatically in all the other languages so users can edit it.

3. When I edit a string and push to GitHub, the line of the string is removed.

4. Are translated strings just a reference? When I edit a string, it says "translation ended". Since all other languages ​​aren't translated I need to change everything to not translated. How can I do that?

**Comment by nijel** [comment]
It edits the file for the selected language. There is no option to edit all languages besides search and replace.

**Comment by kenygamer** [comment]
> It edits the file for the selected language. There is no option to edit all languages besides search and replace.

Do you know why when I edit a string the line is removed?

**Comment by kenygamer** [comment]
@nijel Thanks for your help but none of the solutions you propose work for this issue. I've switched over all files from ini to JSON, and used Joomla parsing instead.

And I've created an `en.ini` file with a `[Language]` section, it still doesn't parse the INI file. The error message is "it is not supported".

I also have a third question what it is, how long does it take to be removed? Why does it take so much ? I tried deleting my old component and it's still "deleting" after one hour.

**Comment by nijel** [comment]
> I tried deleting my old component and it's still "deleting" after one hour.

It is removed by Celery worker, which is apparently not working for you (see #4983). I'm not sure how much of your issues is actually caused by this, but first fix that and then look at other things. The file parsing also happens in the background, so in case your translations appeared empty, it's related as well.

**Comment by kenygamer** [comment]
@nijel Are you sure about that? For some reason, my JSON files parsed without the celery worker. Now they don't. I don't understand this randomness, I think this should be logged.

**Comment by nijel** [comment]
Yes, in most cases it happens in the background.

**Comment by kenygamer** [comment]
@nijel However you can't know when it is sent to Celery worker? Is there a way to disable Celery because it has made Weblate unusable for several weeks now. 

I want to insist with INI files. They are not loading, they are simply not being detected. I tried adding the section you told me and Weblate "cannot detect it" in the Project Maintenance page.

Also, can you advise me any way to optimize Weblate? My web server is lightning, but Weblate takes at least 10s to load every page.

**Comment by nijel** [comment]
There is no reason every page should take 10 seconds. It has to be something misconfigured on your side and it's up to you to figure out what is messed up.

If you want to get rid of Celery process, you can enable CELERY_TASK_ALWAYS_EAGER, but Weblate will then perform worse.

**Comment by kenygamer** [comment]
> There is no reason every page should take 10 seconds. It has to be something misconfigured on your side and it's up to you to figure out what is messed up.
> 
> If you want to get rid of Celery process, you can enable CELERY_TASK_ALWAYS_EAGER, but Weblate will then perform worse.

@nijel That is what I did, the page load is still slow. However we leave the central topic, my INI/JSON strings are not parsed yet.

**Comment by kenygamer** [comment]
@nijel I appreciate your attention.

**Comment by nijel** [comment]
@kenygamer Sorry, but this is not a guaranteed support service, if you are looking for that, you can purchase it on our website. You might have noticed that it has been Christmastime when most people spend time with their families...

Anyway I'm completely lost in your problems. Are you using JSON or INI files now? What is the actual bug that happens? How is your translation component configured? Did you sort out other issues you had with the installation that might be causing problems?

**Comment by kenygamer** [comment]
@nijel I am non-profit, but not established, so if there are requirements I could not fill them. And yes I understand, but I've been needing this for 2 months and having an entire company on standby for that, so I appreciate your prompt attention. as I said, None of my JSON/ INI strings are being parsed.

My translation project shows in the Repository maintenance section that it is linked to the repository yet, it does not load any of the strings and is completely unusable. I have 8 INI files in my repository and none are detected with or without INI sections, the same applies for JSON fil.

Also, I commented in another issue that I have problems with Redis.  
I emptied the password, set an empty password, used a 128-character password. I can login with `redis-cli` -> `AUTH <password>` perfectly but Weblate can't:

```
Authentication required
```

**Comment by nijel** [comment]
I understand you have no funding, but you have to understand that I do this in my free time and there can be periods where I have no free time to spend here...

INI: Where they are not detected? Parsing of the files fails with an error? Weblate lists them empty?

Redis: I have no clue which issue you are talking about. https://github.com/WeblateOrg/weblate/issues/4978#issuecomment-753640945 doesn't mention anything like that. Probably the password is not specified there if it tells that. Please note that redis is used in two places - for cache and Celery. Maybe one of these is missing the password? I guess reading the full error exception instead of just the error message would reveal which one of these is that.

Each of your question lacks details that would allow to diagnose it. This is really wasting time for both of us. I suggest you start with a new issue (for each of the problems) and fill in all the parts in the issue template (including steps to reproduce).
