### ISSUE TITLE
Add project API tokens

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#4974]
**Is your feature request related to a problem? If so, please describe.**

Add support for generating API tokens at project level and granting them access to certain features.

**Describe the solution you'd like**

* API tokens management at project level
* In background it generates bot users and adds them to the project
* These bot users will have NULL email and will be blocked from authenticating
* They will be shown in a user management to adjust permissions
* The username would be generated, something like project_{id}_bot{optional_unique_suffix}

**Describe alternatives you've considered**
Creating real users is an option as well, but that sucks in team management.

**Additional context**
See https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html for documentation how GitLab does it.

Also see #1066

**Comment by JochenDiekenbrock** [comment]
I'm currently evaluating weblate for working with our existing private Gitlab.

For security reasons, we do not want to have *one* weblate user that has access to all repositories. Ideally the weblate user would exist in gitlab as well and weblate would push the translations with the gitlab user. If I didn't miss something, that's not possible in weblate.

Is my understanding correct, that this issue implements managing Gitlab access tokens on the project or even component level? And the generated username would be the user pushing changes to Gitlab?

Any idea, when this feature would be available?

**Comment by nijel** [comment]
No, this issue is about having project wide access tokens for Weblate API. Right now the API token is for users only.

For accessing remote repos the proper solution is to have native connection to the service, ask for repository access and store these tokens. For GitHub, this is requested in https://github.com/WeblateOrg/weblate/issues/1688.

**Comment by JochenDiekenbrock** [comment]
Ah ok, thank you Michal!

**Comment by derkoe** [comment]
I have created a draft implementation that works so far: https://github.com/WeblateOrg/weblate/compare/main...derkoe:project-tokens

What is still open is the UI to create/delete the tokens.

**Comment by nijel** [comment]
@derkoe Looks good so far. Please submit a pull request once you are ready for feedback (it doesn't have to be finished).
