### ISSUE TITLE
Make SOCIAL_AUTH_REDIRECT_IS_HTTPS configurable by env. variable in settings_docker.py

### ISSUE THREAD

**Issue by petrformanek** [WeblateOrg/weblate#4975]
**Weblate in docker using Azure AD with https offloading by proxy**
In my case https is offloaded by proxy and weblate docker image runs just with http. I need to be able to have Azure AD redirect url with https protocol instead of http protocol.

**Describe the solution you'd like**
I want to be able to set `SOCIAL_AUTH_REDIRECT_IS_HTTPS` independently on `WEBLATE_ENABLE_HTTPS` environment variable.
The setting should be available via `docker-compose.override.yml` via `WEBLATE_SOCIAL_AUTH_REDIRECT_IS_HTTPS` env. variable.

**Describe alternatives you've considered**
After some time of investigation I changed the setting via `settings-override.py`. I consider it as workaround and I'd rather be able to configure it via env. variables.

Thank you for considering this request.

**Comment by nijel** [comment]
It should be easy to implement in https://github.com/WeblateOrg/weblate/blob/master/weblate/settings_docker.py

**Comment by nijel** [comment]
Anyway I think the correct approach here is to set WEBLATE_ENABLE_HTTPS. I see no reason why Weblate should be generating http links and social auth https.

**Comment by petrformanek** [comment]
> Anyway I think the correct approach here is to set [WEBLATE_ENABLE_HTTPS](https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_ENABLE_HTTPS). I see no reason why Weblate should be generating http links and social auth https.

WEBLATE_ENABLE_HTTPS does more thinks than I need. I could not make it run in my environment. I have a proxy which off loads https and weblate docker runs just in http. Only issue I have that Active Directory (AD) integration requires https so I have to somehow tell weblate to use https protocol to call AD.

**Comment by nijel** [comment]
The ENABLE_HTTPS setting makes Weblate produce links with https, what is what you want in your setup. It also toggles some other Django settings by default, what is typically desired in such setup as well (making cookies ssl only or enabling HSTS).

The only problematic thing it toggles might be SECURE_SSL_REDIRECT. In case it redirects infinitely, you might want to set [WEBLATE_SECURE_PROXY_SSL_HEADER](https://docs.weblate.org/en/latest/admin/install/docker.html?highlight=SECURE_PROXY_SSL_HEADER%20#envvar-WEBLATE_SECURE_PROXY_SSL_HEADER).

**Comment by petrformanek** [comment]
I understand your points.
Currently I'm running weblate in docker on my machine and I'm just happy with http. I tried to integrate to AD, so I needed just https for AD endpoint calls.
When is WEBLATE_ENABLE_HTTPS true I'm ending with infinite loop of forwarding.
Sometimes I also make weblate available for colleague to evaluate via [localtunnel](https://www.npmjs.com/package/localtunnel) which provides publicly available https endpoint.

**Comment by nijel** [comment]
Setting WEBLATE_SECURE_PROXY_SSL_HEADER to match your reverse proxy headers should fix the forwarding loop.
