### ISSUE TITLE
Add an option to disable sharing

### ISSUE THREAD

**Issue by nblock** [WeblateOrg/weblate#498]
Is there a way to disable the 'Share' tab on a Weblate installation? I could not find a configuration switch for it. Disabling the 'Share' tab is interesting for in-house installations where sharing is not desirable or in cases where the generated links/widgets are are not reachable from the outside. What do you think about it?

**Comment by zymotik** [comment]
Found it, don't worry @nijel.

**ENABLE_SHARING**
Turn on/off the Share menu so users can share translation progress on social networks.
[Weblate Configuration - Enable sharing](https://docs.weblate.org/en/latest/admin/config.html#enable-sharing)
