### ISSUE TITLE
Statistics based on the number of words or characters.

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#4981]
Is it possible to calculate statistics based on the number of words or characters?  Current string calculations are not very reliable in some situations.
![Screenshot_1](https://user-images.githubusercontent.com/39633242/101323428-f39f7500-3868-11eb-993b-131db10df05c.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/39633242/101323430-f4380b80-3868-11eb-981a-dae92c3a8675.jpg)

**Comment by nijel** [comment]
You can already see there number of untranslated words. I know it works better for some use cases and that's why it's included.

**Comment by tomkolp** [comment]
Can you add a method to calculate the statistics displayed on the widget?  
1) count statistics based on strings 
2) count statistics based on words
 In some cases this would improve the reliability of the statistics.
The current method of calculating statistics suggests that my project is 61% complete.  It really is only 33%.

**Comment by nijel** [comment]
The detailed stats are now available on the info tab:

![image](https://user-images.githubusercontent.com/212189/113298070-b4a39c80-92fb-11eb-8ff3-a29abdaa4a5f.png)
