### ISSUE TITLE
manage.py file is unusuable

### ISSUE THREAD

**Issue by kenygamer** [WeblateOrg/weblate#4982]
**Describe the bug**

First, the `manage.py` files gives an error:
```
Non-ASCII character \xc2 in file .manage.py on line 3 but no encoding declared.
```
Possibly grapheme in @nijel 's name?

Secondly, the `manage.py` file says:
```
No module named weblate.runner
```

When you try to execute the file with `./manage.py` I have activated the virtual environment and placed the `manage.py` in the `/weblate-env/bin` folder for consideration.

**To Reproduce the bug**

1. Go to the weblate venv folder.
2. Place the `manage.py` from the repository.
2. Run the `./manage.py` command.
3. See errors.

**Expected behavior**

These errors should not show.

```
 Weblate: 4.3.2
 * Django: 3.1.3
 * siphashc: 2.1
 * Whoosh: 2.7.4
 * translate-toolkit: 3.2.0
 * lxml: 4.6.1
 * Pillow: 8.0.1
 * bleach: 3.2.1
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.2
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 50.3.2
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.5
 * weblate-language-data: 2020.11
 * html2text: 2020.1.16
 * pycairo: 1.20.0
 * pygobject: 3.38.0
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.19.3
 * Cython: 0.29.21
 * misaka: 2.1.1
 * Platform: Linux 4.15.0-126-generic (x86_64)
```

**Comment by nijel** [comment]
> Non-ASCII character \xc2 in file .manage.py on line 3 but no encoding declared.

Weblate requires Python 3.
