### ISSUE TITLE
Pending changes do not commit to Weblate repository

### ISSUE THREAD

**Issue by kenygamer** [WeblateOrg/weblate#4983]
**Describe the bug**

I am using Weblate for my project.  I need to be able to get all the strings that are uploaded in GitHub and let users edit them in my Weblate website.  However, when changes are made on Weblate side, they are never committed to Weblate

I'd like to know how is it possible to make all changes (not suggestions) automatically commit to Weblate every 5 minutes.  As of now I am using the manual way in the Repository Maintenance page, and when I goot he maintenance page underneath Repositroy status it says:

```
2 pending changes not yet committed to the weblate repository.
```

There is also a strange use of terminology.  I don't know if this is the source code repository that is mentioned earlier (most likely, since no change I make or commit I try to make is sent out with the Commit button), or if this is for the local repository.  However, I need to make all changes send to the remote repository.  This number stays the same.

In addition, Commit and Push buttons aren't doing anything, just returning a success message.

I have been checking the bug tracker in case this issue was reported before, but I can't seem to find it.  

**To Reproduce the bug**

1. Go to the Weblate website.
2. Login as admin.
3. Click on the Weblate project.
4. Go to the "Repository Maintenance" section.
5. Try to Commit or Push.

**Expected behavior**
Commits should reflect in the remote repository.

**Server configuration and status**
```
Weblate: 4.3.2
 * Django: 3.1.3
 * siphashc: 2.1
 * Whoosh: 2.7.4
 * translate-toolkit: 3.2.0
 * lxml: 4.6.1
 * Pillow: 8.0.1
 * bleach: 3.2.1
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.2
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 50.3.2
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.5
 * weblate-language-data: 2020.11
 * html2text: 2020.1.16
 * pycairo: 1.20.0
 * pygobject: 3.38.0
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.19.3
 * Cython: 0.29.21
 * misaka: 2.1.1
 * Platform: Linux 4.15.0-126-generic (x86_64)
```

**Comment by jojurajan** [comment]
You could try to set the `COMMIT_PENDING_HOURS` to 0 for immediate commits on local repo and the consequent pushes to remote repo or maybe set it to `0.083` for committing every 5 mins.
The UI settings can be found under `settings/<project>/<component>/#vcs`.
https://docs.weblate.org/en/latest/admin/projects.html#component-commit-pending-age

**Comment by nijel** [comment]
@kenygamer Seriously, you should spend some time by looking into the documentation. See https://docs.weblate.org/en/latest/admin/continuous.html#lazy-commits which exactly describes when changes are committed and how you can adjust that.

**Comment by kenygamer** [comment]
@jojurajan I added the `COMMIT_PENDING_HOURS = 0.038 `configuration entry and it's still not making any commits nor lazy/ commits.  I'd like to do this the proper way with a celery task, however Celery doesn't even work to begin with.  

The logs are:

```
 /etc/systemd/system/celery-weblate.service:19: Executable path is not absolute: ${CELERY_BIN} multi start $CELERYD_NODE
```

The contents of the unit file:

```
[Unit]
Description=Celery Service (Weblate)
After=network.target

[Service]
Type=forking
User=root
Group=root
EnvironmentFile=/etc/default/celery-weblate
WorkingDirectory=/home/weblate-env
PermissionsStartOnly=true
ExecStartPre=/bin/mkdir -p /var/run/celery
ExecStartPre=/bin/chown -R weblate /var/run/celery/
ExecStartPre=/bin/mkdir -p /var/log/celery
ExecStartPre=/bin/chown -R weblate /var/log/celery/

# please note surrounding environment variables with braces has a specific meaning.
# When surrounded by braces, variable content is not split around spaces.
ExecStart=${CELERY_BIN} multi start $CELERYD_NODES \
  -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} \
  --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} $CELERYD_OPTS
ExecStop=${CELERY_BIN} multi stopwait $CELERYD_NODES \
  --pidfile=${CELERYD_PID_FILE}'
ExecReload=${CELERY_BIN} multi restart $CELERYD_NODES \
  -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} \
  --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} $CELERYD_OPTS

[Install]
WantedBy=multi-user.target
```

**Comment by nijel** [comment]
The executed command cannot be variable in systemd. Do you have reason for not using examples coming with Weblate? See https://docs.weblate.org/en/latest/admin/install.html#running-celery-as-system-service

**Comment by kenygamer** [comment]
> The executed command cannot be variable in systemd. Do you have reason for not using examples coming with Weblate? See https://docs.weblate.org/en/latest/admin/install.html#running-celery-as-system-service

I do. If you see `ExecPreStart', it creates a missing `celery` directory. If I use your example, I get this (very!) descriptive error:
```
Starting Celery Service (Weblate)...
Dec 22 01:00:02 ubuntu systemd[1]: celery-weblate.service: Control process exited, code=exited status=217
Dec 22 01:00:02 ubuntu systemd[1]: celery-weblate.service: Failed with result 'exit-code'.
Dec 22 01:00:02 ubuntu systemd[1]: Failed to start Celery Service (Weblate).
```

**Comment by nijel** [comment]
The `RuntimeDirectory=celery` and `LogsDirectory=celery` statements should handle creation of these directories. What OS and systemd version are you using?

Anyway, that's not reason for changing the `ExecStart` statement to something what cannot work.

**Comment by nijel** [comment]
PS: aef8e9d48587f7921dc1d6c01c232644a099e138 will most likely fix the original service startup (I'm just guessing based on symptoms you've described).

**Comment by kenygamer** [comment]
Thanks for the advice.  Your commit has not resolved my issue.  Celery still can't start, using your suggested unit file and environment file. 

Affix: I noticed the `EnvironmentFile is pointing` to `celery-weblate` when the example filename has a `.conf` ending.

```
● celery-weblate.service - Celery Service (Weblate)
   Loaded: error (Reason: Exec format error)
   Active: failed (Result: exit-code) since Tue 2020-12-22 16:19:50 UTC; 19s ago
Dec 22 16:19:50 ubuntu systemd[1]: Starting Celery Service (Weblate)...
Dec 22 16:19:50 ubuntu systemd[1]: celery-weblate.service: Control process exited, code=exited status=217
Dec 22 16:19:50 ubuntu systemd[1]: celery-weblate.service: Failed with result 'exit-code'.
Dec 22 16:19:50 ubuntu systemd[1]: Failed to start Celery Service (Weblate).
Dec 22 16:19:59 ubuntu systemd[1]: /etc/systemd/system/celery-weblate.service:19: Executable path is not absolute: ${CELERY_BIN} multi start $
~
``'

**Comment by nijel** [comment]
You're still using wrong `ExecStart` command. It seems like we're running in circles here, please go back to https://github.com/WeblateOrg/weblate/issues/4983#issuecomment-749152163

**Comment by kenygamer** [comment]
@nijel For some reason my SSH client didn't send the changes. I'm still getting errors though.
```
● celery-weblate.service - Celery Service (Weblate)
   Loaded: loaded (/etc/systemd/system/celery-weblate.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-12-23 02:27:07 UTC; 4s ago
  Process: 27973 ExecStart=/bin/sh -c ${CELERY_BIN} multi start ${CELERYD_NODES}    -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE}    --logfile=${CELERYD_LOG_FILE} --logl
Dec 23 02:27:07 ubuntu systemd[1]: Starting Celery Service (Weblate)...
Dec 23 02:27:07 ubuntu systemd[1]: celery-weblate.service: Control process exited, code=exited status=217
Dec 23 02:27:07 ubuntu systemd[1]: celery-weblate.service: Failed with result 'exit-code'.
Dec 23 02:27:07 ubuntu systemd[1]: Failed to start Celery Service (Weblate).
```

The same error we started with.

**Comment by nijel** [comment]
Can you please try some debugging yourself? For example [entering the error in Google](https://www.google.com/search?client=firefox-b-d&q=Control+process+exited%2C+code%3Dexited+status%3D217).

**Comment by kenygamer** [comment]
@nijel I am trying to do this methodically. If the user did not exist, for example, why should I create it if it is in the example? Shouldn't this be pointed out in the guide? I'm going to try to create the user, but believe me I googled everything else.

**Comment by nijel** [comment]
I have no clue under which user you run weblate. I also don't think you have read the documentation, so it really doesn't matter what is written there. The celery instructions explicitly describe that the celery process should use same user as wsgi. Did you follow that?

**Comment by kenygamer** [comment]
@nijel Done. I've fixed the user. The directory also apparently didn't exist, so the first time I used the unit it did work. I confused the user error with the error I had before with that previously unexisting `/var/run/celery` directory.

Celery starts well and is running as a service. However, Weblate is still as slow as before (4s to 10s), and the project is "scheduled for removal", but never actually removed. Language strings are occasionally added, and strings that are modified continue to be removed from the GitHub repository. I don't see any differences.

**Comment by kenygamer** [comment]
@nijel am also having a little issue with Redis support, whenever I try to go to the Weblate page after configuring my Redis server, I get the error "Authentication required.". I have this config entry:

`CELERY_BROKER_URL = "redis://hidden_password@localhost:6379/1"`

And the permissions are correct. What is wrong here?

**Comment by nijel** [comment]
Where do you get "Authentication required."? You apparently have something misconfigured and examining where does that error come from might help you to figure out source of the problem.

**Comment by kenygamer** [comment]
> Where do you get "Authentication required."? You apparently have something misconfigured and examining where does that error come from might help you to figure out source of the problem.

I checked now and it got fixed. It seems to be some cache. I just tried configuring Redis because on some page it warned me to use and, And I also remembered that I skipped the step of configuring Redis in my setup. However, all the other issues continue.
