### ISSUE TITLE
Colouring of string statuses

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4985]
![image](https://user-images.githubusercontent.com/13802408/101287787-6f0e1180-37ea-11eb-8e4a-c1f7fe7ad1a2.png)

The lighter teal (confirmed string) colour doesn't follow from green (translated).

**1.** It makes sense to me that the confirmed good string should be a darker colour of good/unproblematic.

However, write-protected is currently dark green. I thought it was just confirmed strings were in the wrong place, so

![image](https://user-images.githubusercontent.com/13802408/101287892-f491c180-37ea-11eb-85d2-b6c70c9efe4b.png)
This is the colour for confirmed strings, but it is the same colour as translated ones.

**2**. The icon for confirmed good should be the same darker green as in 1.

**3.** Write-protected should have the teal colour.

Similarly, I think "marked for edit" should also be a darker red than just "untranslated", and that it should be possible to distinguish fuzzied strings from those, but that is a bit further along.

Untranslated strings are transparent/gray in the main bar, which makes sense, but then red
![image](https://user-images.githubusercontent.com/13802408/101288045-26575800-37ec-11eb-8106-2f22c13c8643.png)
in the categories…I think it should be the same gray/transparent everywhere, so

**4.** Untranslated category should have the transparent/gray colour from the main bar section.

Right now, "All strings" is gray/transparent. I think it makes sense if

**5.** "All strings" category should have no colour at all (?).

![image](https://user-images.githubusercontent.com/13802408/101288025-045dd580-37ec-11eb-953a-1f396df21704.png)
should be 

![image](https://user-images.githubusercontent.com/13802408/101288220-476c7880-37ed-11eb-8fa1-4a83a045cc92.png)

---

In the main bar, the yellow field preceedes the red one, whereas in the category, red comes first.

**6.** Make the yellow category come before red in the main bar, or change the order in the categories?

It makes sense that "marked for edit" is more towards the "untranslated" side of the main bar, so I am thinking ordering the categories differently is better.

With that in mind.

**7.** Put the "all strings" category at the bottom. This way they all sum up (from top to bottom) to what is the final tally.

The "confirmed" strings are above translated ones in the categories, but then the various types of red strings are all below the red category, like "all strings" is above everything.

**8.** Does it make sense to move the confirmed strings to the right of translated strings on the main bar to have ultimate consistency, or like 6/7 to change the categories instead?
I sort of like how it is two passes of left to right, and that confirmed doesn't push against the translated bar.

I got a bit confused by the seemingly shared categories being a double-indentation that doesn't hold true for the above.

![image](https://user-images.githubusercontent.com/13802408/101289493-b8635e80-37f4-11eb-845f-82f2b77aa761.png)

**Comment by nijel** [comment]
I'm not sure it's a good idea to switch colours when people are get used to them. Another important thing is that the progress bar shrinks multidimensional metric into one dimension. The strings with failing check can be any of read only/approved/needing edit/not translated, the same applies to suggestions (which are currently not represented in the progress bar).

**Comment by comradekingu** [comment]
Therein lies the crux. Are people used to them? I haven't understood most of them yet, but mileage may vary.

The option is to go for something other than teal for "read-only", and a slightly different green for "confirmed".
Or go with something that works for colour-blind people entirely.

**4.** Seems to be uncontroversial?

**Comment by comradekingu** [comment]
@nijel Bar colours changed, and I didn't notice. Nor did I remember what the old ones were, so that seems good.
Boy does it look better than my suggestion.

https://hosted.weblate.org/projects/kinovea/root/nb_NO/
![bilde](https://user-images.githubusercontent.com/13802408/114827303-ca6b9400-9dc8-11eb-9f44-41286ebdce45.png)

I don't understand why "Strings needing action without suggestions" 41 is gray though.

What is it, and why is it gray?

**Comment by nijel** [comment]
Fixed in 3bcf4b65ae

**Comment by comradekingu** [comment]
![bilde](https://user-images.githubusercontent.com/13802408/114832978-64ced600-9dcf-11eb-8320-aa29be88f193.png)

- "Has been translated" 5 moved up underneath failing checks 11
- All "missing control:" removed in favour of a : on the category they are in above
- Marked for edit is a checkmark, it could be a checkmark on red both places to make the connection even better.\
Right now it is 
![bilde](https://user-images.githubusercontent.com/13802408/114832426-c0e52a80-9dce-11eb-8c10-5675a2b5725a.png) which is, not red…

**Comment by comradekingu** [comment]
This indentation is a little less awful. Don't think removing the colour for all strings did any good though.
![bilde](https://user-images.githubusercontent.com/13802408/114837064-9649a080-9dd3-11eb-8d5a-23b6424564cf.png)

**Comment by nijel** [comment]
The coloring change was necessary to have consistent color in the navigation and progress bar. Also, it now indicates whether there is something to be done on the string. The additional colors were problematic - people didn't understand them (and they were not well-defined).

As for the indentation, it might be added later, but I don't see it as a priority now and it is out of topic here.
