### ISSUE TITLE
Import Git Repo but Existing Languages not Detected

### ISSUE THREAD

**Issue by TheWitness** [WeblateOrg/weblate#4987]
**Describe the issue**

Simple question.  I was using Weblate 3.4, and i've installed 4.3 as I was really unable to easily upgrade.  So, I added a project back into Weblate.  In the past, it would detect all of our existing PO files, and load them into Weblate.  But now in this latest release, it says that there are no languages except English.  What did I do wrong.

This is a RHEL7 install with git 2.22 instead of git 1.8 which is no longer supported.

**Comment by nijel** [comment]
Where it doesn't find the files?

* When creating the component and offers the list of possible configuration? In that case, please file issue at https://github.com/WeblateOrg/translation-finder/ with listing of the files. We're constantly tweaking the finder to improve accuracy, but it's possible there is some bug in that.
* After creating the component, only English language is shown? The most likely cause is that the Celery process is not running correctly (or was not restarted after reinstallation in your case). The parsing of the files happens in the background. See https://docs.weblate.org/en/latest/admin/install.html#celery for more info.

**Comment by TheWitness** [comment]
Took some days off for the holiday.  See if I can trace today

**Comment by TheWitness** [comment]
Ope, different issue.  I'm okay closing.  Basically, there is another case that should be backgrounded.  Let's say I add a component, and it includes a number of po files, but for some reason they are not processed, if I then go to upload them from the files ment, the page hangs.  You can tell from the backend it's processing the files, but the gui is hung.  Eventually cloudflare times out the page.  The process continues of course and finishes.  The larger the translation to be processed, the longer it stalls if course.
