### ISSUE TITLE
GitHub private email address

### ISSUE THREAD

**Issue by namazso** [WeblateOrg/weblate#4988]
GitHub provides a "cloak" noreply email address when enabling e-mail privacy, with which you can commit in normal git repos and it will get attributed correctly. E-mails sent to this address will be lost, this is an intended feature:

![image](https://user-images.githubusercontent.com/8676443/101301774-24b48100-383a-11eb-9014-d0c3ac6d1220.png)

 Because of it throwing away all mails, you cannot add that email address on Weblate. Would it be possible to automatically add that email to the user whenever someone uses GitHub login?

**Comment by nijel** [comment]
Not right now because Weblate requires working e-mail address for account recovery. We might add the option to configure e-mail address for Git commits and it will certainly make sense there.

**Comment by comradekingu** [comment]
@namazso How is this a good idea?

**Comment by namazso** [comment]
@comradekingu what do you mean?

Some people prefer not having their email on a public git, especially if they just came to translate some random project. 
Sure, you could just say "well, just make another email, verify it on github (for attribution as contributor) & weblate (so that it commits as that email) and make it just delete everything", but github has this feature out of the box with much less hassle.
