### ISSUE TITLE
MT: Norwegian not translating

### ISSUE THREAD

**Issue by reloxx13** [WeblateOrg/weblate#4997]
**Describe the bug**
Heya,
i tested machine translations and found out that translating norwegian (both codes) does not work.
For testing i used google translator api.

Im low at time right now, ill try to add more infomrations later :(

**To Reproduce the bug**
Add both norwegian laguages (nn and nb_NO) and try to trigger google machine translations.
It will not get translated.

**Expected behavior**

**Screenshots**
![grafik](https://user-images.githubusercontent.com/14855001/101477551-a8ac5d00-394f-11eb-8311-b7e4cfd3af59.png)

**Server configuration and status**

Weblate installation: pip
 Weblate 4.3.2

**Weblate deploy checks**

**Exception traceback**

**Additional context**

**Comment by comradekingu** [comment]
@reloxx13 What project is that? Hoping to avoid auto-translations making it in.

**Comment by WilliamHingston** [comment]
When will this fix be released? Still not working in 4.5

**Comment by nijel** [comment]
The fix was part of the 4.4 release (you can see from the issue milestone). And it works just fine:

![obrazek](https://user-images.githubusercontent.com/212189/108605731-61faca80-73b6-11eb-95e9-02cb76c710f0.png)

**Comment by reloxx13** [comment]
I can confirm it works

**Comment by comradekingu** [comment]
@reloxx13 What are you machine-translating? Sounds almost like a feature :)
Can I help rectify the situation?
