### ISSUE TITLE
TM matches don't show correct similarity match value

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#4999]
I was updating a project today and noticed that there are strings which are 100% identical but are not pulled from the TM.
When I checked them individually, I noticed that the match value weblate calculated for those is not 100 but 90.

Example:
![image](https://user-images.githubusercontent.com/26718215/101480241-b663e180-3953-11eb-8afe-e466fdc5729d.png)

Any idea?

**Comment by nijel** [comment]
There are two issues here.

First, the auto translate addon was not correctly fired in some cases, I've just fixed that in e9c4a04c161d385e404e48c84b3f530ddc21db6f.

Then there is a UI issue - the display logic looks for the same translation and adds another backend listing to it, but doesn't update the similarity. So, what probably happened in your case is that the Microsoft Translator results were received first, it was added to the table with its score (which is capped at 90). Later Weblate translation memory match was received, the entry origin was updated, but not the score.

Code causing this:

https://github.com/WeblateOrg/weblate/blob/facca58953d9f55417b24f224d18e4dc558cfa3e/weblate/static/editor/full.js#L534-L539

**Comment by ilocit** [comment]
Super cool. You are so super fast!!!
Thanks a lot, Michal.
Have a great day.

**Comment by ilocit** [comment]
Sorry, I accidentially closed this issue. But you / your team is still working on it. Since you say "help wanted"...

**Comment by nijel** [comment]
Yes, there is still the UI issue which needs to be addressed.
