### ISSUE TITLE
"Adding new translation" option missing from component settings

### ISSUE THREAD

**Issue by figure002** [WeblateOrg/weblate#5024]
**Describe the issue**

On my hosted.weblate.org hosted project, translators are not able/allowed to request a new language.

**I already tried**

The documentation states that it should be possible configure this at the component settings:

https://docs.weblate.org/en/latest/admin/projects.html#adding-new-translation

So I went to the component settings and selected the "Translation" tab, but there is no "Adding new translation" option anywhere. 

**To Reproduce**

1. Login as project maintainer.
2. Go to the translation component settings at https://hosted.weblate.org/settings/getgnulinux/getgnulinux-pot/#translation
3. There is no "Adding new translation" option anywhere.

**Expected behavior**

I would expect to find a "Adding new translation" option at the component settings, as described in the documentation.

I also expect translators to be able to request new languages, but they are not able to.

**Comment by comradekingu** [comment]
I think you have selected
~ Point to URL for translator instructions
in Adding new translation
https://hosted.weblate.org/projects/getgnulinux/getgnulinux-pot/#files

**Comment by figure002** [comment]
Wow I can't believe I missed that. I was looking under the wrong tab; "Translation" instead of "Files".
