### ISSUE TITLE
Java Format check fails for out of order parameters

### ISSUE THREAD

**Issue by Ch4t4r** [WeblateOrg/weblate#5033]
**Describe the bug**

I use Weblate to translate my Android app.
In texts with positional arguments (%1s, %2s, ...) the `Java Format` check fails when the order in which they appear is not the same as in the source string.
An example source is `The quick brown %1s jumps over the lazy %2s with %3s`, an example (and valid) target could be `Der träge %2s wird vom %1s mit einem %3s übersprungen`. It would result in the following error:

```
Java format
Following format strings are missing: %1s, %2s
Following format strings are extra: %1s, %2s
```

**Expected behavior**

I'm not exactly sure whether this is worth fixing or not. In some cases the check would help catch formatted strings which are unintentionally out of order, however there are some languages where they are always going to be out of order.
I'll leave that up to you to decide. I can simply dismiss the error where applicable.

**Server configuration and status**

Weblate installation: Docker, version 4.3.2

**Comment by nijel** [comment]
Your format strings are wrong - these do not allow reordering, the number defines minimal width of the string. You should be using `%1$s` instead of `%1s`. See https://medium.com/better-programming/formatting-strings-with-java-2281d40accce

**Comment by Ch4t4r** [comment]
TIL what the $ is for. Never ran into that in the past haha
Thanks!

I'm going to close this then. Just a small side question, is it possible for the error message to be a bit more precise in this case (missing format args=extra format args)?
