### ISSUE TITLE
performance: Saving component settings when linked to many others take ages

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#5034]
**Describe the bug**

On https://l10n.xwiki.org/projects/xwiki-platform/ we have a specific scheme consisting in many (85 at last count) components, all linked to a central one. The reason of that scheme is because we have a big Maven multi-module project on https://github.com/xwiki/xwiki-platform/tree/master/xwiki-platform-core and each of the module can contain translations. 
So basically: one component with the repository settings and 85 components corresponding to the various Maven sub-modules with translations.

The problem is that when we need to change settings on the central component: apparently those specific settings are taking very long to save. I measured around 2 min for saving a new setting in this component. And it won't decrease since we keep adding new modules and so possibly new translations in this repository.

**To Reproduce the bug**

1. Create several Weblate components linked to a single one 
2. Try to save settings in the components containing CVS informations
3. Check the duration for saving the component

**Expected behavior**

The component save shouldn't take more time than saving a linked component.

**Comment by nijel** [comment]
I think this should be better with the upcoming 4.4 release. I recall debugging similar issue for Fedora, but can't find the exact commit right now.

**Comment by surli** [comment]
> I think this should be better with the upcoming 4.4 release.

Ok, I'll try to come back to you when I'll be able to test with 4.4 to see if it improves performance.

**Comment by nijel** [comment]
Great, 4.4 will be released in upcoming hours, I'd really like to hear the feedback once it is out.

**Comment by surli** [comment]
@nijel could you remove the wontfix label? It's not right here, it's probably fixed it's just that I haven't been able to check yet since I'm waiting the other fixes. You can just close it, I'll comment it once I'll be able to test.

**Comment by nijel** [comment]
Assuming this has been fixed, please comment in case it does not.

**Comment by surli** [comment]
Sorry I completely forgot about that one, I didn't see the issue anymore indeed.
