### ISSUE TITLE
I Created SSH Keys for New Install, but Weblate Previously was using .ssh/config file directives and now pushing is broken

### ISSUE THREAD

**Issue by TheWitness** [WeblateOrg/weblate#5035]
**Describe the issue**

I migrated a server from machine to machine.  They had previously used the .ssh/config directive to setup key use for github.com.  I would like to use that keypair in the Weblate GUI under the "SSH Keys" section, but I don't know where the Weblate keys are stored.  Is there a way for me to manualy enter the keys, or to move the existing keys into the Weblate configuration?

**I already tried**

grep -r "ssh-rsa" *

**Comment by TheWitness** [comment]
I found the location by searching the documentation.  Look like they are under DATA_DIR/ssh.  Replaced the files, now waiting to see if the push starts working.

**Comment by TheWitness** [comment]
Okay, confirmed that it took the new keys.  Thanks for your great tool.

What help do you need in being able to support MariaDB backup services.  Would you accept a pull request?

**Comment by nijel** [comment]
> What help do you need in being able to support MariaDB backup services. Would you accept a pull request?

Yes, pull requests (with tests) are always welcome. The PostgreSQL code is here:

https://github.com/WeblateOrg/weblate/blob/52949f7f8bccfcf6d45a7faa2a1d8eac40947faf/weblate/utils/tasks.py#L88-L112

**Comment by TheWitness** [comment]
So, I've made the changes, but I'm not seeing the database.sql in the backup service file list or floating about the file system.  Did I miss something?  How should I log, just turn on DEBUG?

**Comment by nijel** [comment]
The database backup is triggered daily, so it's not expected to appear immediatelly.

**Comment by TheWitness** [comment]
Cool.  I'll look for it tomorrow. Work is done.  Wondering how you set the password though.
