### ISSUE TITLE
XWiki translation format are marked as missing when adding a new language

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#5040]
**Describe the bug**

In Weblate 4.3.2, when using XWiki Page Properties format, translations are not properly handled when adding a new language. The files are committed with the translations marked as missing, even if they have been translated already. See for example: https://github.com/xwiki-contrib/application-discussions/pull/1

**To Reproduce the bug**

1. Create a component with XWiki Java Properties format
2. Add a new language to the component created and perform some translations
3. Commit the changes
4. Translations are not committed: keys are marked as missing 

**Expected behavior**

Translations should have been committed.

**Comment by surli** [comment]
@nijel creating the issue for me: I'll investigate to fix it.

**Comment by nijel** [comment]
Should be fixed by #5050.
