### ISSUE TITLE
please change ANONYMOUS_USER_NAME

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#5046]
**Describe the issue**

After changing the permissions of the user anonymous, weblate does not start.

**Server configuration and status**

 * Weblate: 4.3.2
 * Django: 3.1.3
 * siphashc: 2.1
 * Whoosh: 2.7.4
 * translate-toolkit: 3.2.0
 * lxml: 4.6.1
 * Pillow: 8.0.1
 * bleach: 3.2.1
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.1
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.5
 * weblate-language-data: 2020.11
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.19.2
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.11
 * borgbackup: 1.1.14
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.6
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.16.12
 * zeep: 4.0.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.1
 * Mercurial: 5.6
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * Redis server: 6.0.9
 * PostgreSQL server: 13.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.laptopy.srodaslaska.eu
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.4.0-58-generic (x86_64)

**Exception traceback**

Running migrations:
weblate_1       |   No migrations to apply.
weblate_1       | [2020-12-15 08:14:46,771: WARNING/62] Handled exception: ValueError: Anonymous user (anonymous) already exists and enabled, please change ANONYMOUS_USER_NAME setting.
weblate_1       | Traceback (most recent call last):
weblate_1       |   File "/usr/local/bin/weblate", line 8, in <module>
weblate_1       |     sys.exit(main())
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/weblate/runner.py", line 32, in main
weblate_1       |     execute_from_command_line(argv)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
weblate_1       |     utility.execute()
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 395, in execute
weblate_1       |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 330, in run_from_argv
weblate_1       |     self.execute(*args, **cmd_options)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 371, in execute
weblate_1       |     output = self.handle(*args, **options)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 85, in wrapped
weblate_1       |     res = handle_func(*args, **kwargs)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/migrate.py", line 268, in handle
weblate_1       |     self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/sql.py", line 54, in emit_post_migrate_signal
weblate_1       |     **kwargs
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django/dispatch/dispatcher.py", line 179, in send
weblate_1       |     for receiver in self._live_receivers(sender)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django/dispatch/dispatcher.py", line 179, in <listcomp>
weblate_1       |     for receiver in self._live_receivers(sender)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/weblate/auth/models.py", line 654, in sync_create_groups
weblate_1       |     create_groups(False)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/weblate/auth/models.py", line 636, in create_groups
weblate_1       |     create_anonymous(User, Group, update)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/weblate/auth/utils.py", line 100, in create_anonymous
weblate_1       |     settings.ANONYMOUS_USER_NAME
weblate_1       | ValueError: Anonymous user (anonymous) already exists and enabled, please change ANONYMOUS_USER_NAME setting.

**Comment by nijel** [comment]
> After changing the permissions of the user anonymous

No you were not changing its permissions, you have changed the is active flag. The anonymous user cannot have enabled sign in.

**Comment by tomkolp** [comment]
> > After changing the permissions of the user anonymous
> 
> No you were not changing its permissions, you have changed the is active flag. The anonymous user cannot have enabled sign in.

Can I change this flag from database bash? If so, what command? Unfortunately, my snapshot from the previous week already has this bug.

**Comment by nijel** [comment]
I've blocked such edits for upcoming releases in 8a15555c1c. That way it will be harder to mess up the installation this way.
