### ISSUE TITLE
Prevent translators to go to next string after saving current

### ISSUE THREAD

**Issue by zslucky** [WeblateOrg/weblate#5047]
**Describe the issue**

How to prevent translators go to next string after saving current...

Is there a setting to disable it? As some users told me they always need to go back then they can go to another language and update it, it's waste of time.

**Comment by nijel** [comment]
It's currently not possible. Can you please clarify the use case a bit? Are they translating into more languages simultaneously?

**Comment by zslucky** [comment]
Yes sure, some guys can translate 2 or 3 languages, and some guys just move external resources into weblate.

**Comment by zslucky** [comment]
Or sometimes the content are the same, just need to copy and rewrite to every language.

**Comment by comradekingu** [comment]
Would be really nice if users could midclick the "Save" in the regular editor.
I open all the strings for other languages in different tabs to do it.

**Comment by zslucky** [comment]
This can be a workaround. 👍

**Comment by nijel** [comment]
I don't think it's possible to do a POST request while opening a new browser window.

Having another button to save and stay on current unit is probably best approach here.

**Comment by zslucky** [comment]
I agreed have another button 👍

**Comment by comradekingu** [comment]
How bad of an idea is it to save what is in the field when the tab closes (provided no other changes of the string happened meanwhile)?

**Comment by NicolasLeboeuf** [comment]
Hello. I'd just like to upvote this request, it would be immensely useful for us.

**Comment by gabrielboucher** [comment]
👍
