### ISSUE TITLE
New translation from a bilingual PHP file does not keep escaping in translation keys

### ISSUE THREAD

**Issue by sbocahu** [WeblateOrg/weblate#5048]
We're using PHP chains format for translations, where keys are whole french sentences (mostly).
Using a reference file containing 'my sentence as a key' => '' as model for new translations is broken when our keys contain escaped quotes, which are unescaped in the new language file, resulting in a PHP Syntax error.

Ex:

```
<?php
return array(
'mon exemple avec \' ' => '',
);
```
should give, for new translation, let's say duch "nl":

```
<?php
return array(
'mon exemple avec \' ' => '',
);
```

but what's commited to git is:

```
<?php
return array(
'mon exemple avec ' ' => '',
);
```
and weblate shows "0 strings" in the component for the new language.

How to keep escaping characters such as \ before quotes ?

**Comment by nijel** [comment]
This seems to be a bug in the translate-toolkit code which is used for serializing.

On the other side, bilingual PHP files are not really supported by Weblate, see https://github.com/WeblateOrg/weblate/issues/2547

**Comment by nijel** [comment]
Closing in favor of https://github.com/translate/translate/issues/5348 and https://github.com/translate/translate/pull/5350 should address this.
