### ISSUE TITLE
Clicked markup not saved in Zen

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5049]
https://hosted.weblate.org/zen/gnucash/gnucash/nb_NO/?q=check:xml-invalid

Click the end or opening bold's and tab to the next string.
If the only change, or the last change is editing in the markup by clicking, it doesn't save.

Typing in <-/-b->-tab works.

**Comment by comradekingu** [comment]
@nijel This happens when the markup placeholder is at the end of the string now

**Comment by comradekingu** [comment]
Now it throws the error in the dropdown, but it is saved.

**Comment by nijel** [comment]
What kind of error?
