### ISSUE TITLE
Please add Docu link to "Basic Settings"

### ISSUE THREAD

**Issue by htgoebel** [WeblateOrg/weblate#5055]
On "Settings →Basics" I'm missing a link to the documentation.

I'd like to have a small info-icon for each of the sections on this page linking to the respective part of the documentation.

Many thanks

**Comment by nijel** [comment]
There already is a documentation link for each form field:

![image](https://user-images.githubusercontent.com/212189/102373128-29a6cc80-3fc0-11eb-8513-56b0ec09dfc7.png)

**Comment by htgoebel** [comment]
I meant the *project* settings.

Sorry for being unprecise, I'm a bit confused by where which setting is done.
