### ISSUE TITLE
"other occurrences" slow loading

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#5056]
**Is your feature request related to a problem? If so, please describe.**
Strings with many "other occurrences" take a long time to load. With 2000+, it even takes about one minute.

**Describe the solution you'd like**
Not all "other instances" need to load forever. You can load a certain amount, and the rest only after pressing the appropriate button.

**Additional context**
Weblate 4.4
weblate_1       | uwsgi stderr | [pid: 410|app: 0|req: 12/34] 172.21.0.3 () {60 vars in 1264 bytes} [Wed Dec 16 14:19:07 2020] GET /translate/xxxxxxxxx/xxxxxxxxxxxxxxxx/pl/?q=has:check => generated 1805963 bytes in 58677 msecs (HTTP/1.0 200) 9 headers in 630 bytes (10 switches on core 0)
![image](https://user-images.githubusercontent.com/39633242/102355290-f4907f00-3fab-11eb-97ab-23fa2ab45dac.png)

**Comment by nijel** [comment]
Do you really have that may of strings with same source? Or it's a bug that there are 3853 strings there?

**Comment by tomkolp** [comment]
> Do you really have that may of strings with same source? Or it's a bug that there are 3853 strings there?

It's not a bug, the project is gigantic.  We translate The Elder Scrolls online into Polish.  Our current translation platform (Smartcat) unexpectedly introduced fees, which is why we are moving to weblate.
![Screenshot_20201216-164735](https://user-images.githubusercontent.com/39633242/102372006-12b3aa80-3fbf-11eb-8f1f-eaa5cba1275c.png)

**Comment by nijel** [comment]
So there are actually 3853 with source `Talk to <<1>>`? In that case it's not really useful to show them all...
