### ISSUE TITLE
Things to check panels not dismissable

### ISSUE THREAD

**Issue by minusf** [WeblateOrg/weblate#5057]
**Describe the bug**

The "Things to check" panel shows notes like "Long untranslated", etc.  The "Dismiss" and "Dismiss for all languages" buttons result in `405 Method not Allowed` errors and can't be dismissed.

The issue seems to be that `ignore_check` is marked `@require_POST`: https://github.com/WeblateOrg/weblate/blob/master/weblate/trans/views/js.py#L116 while `templates/translate.html` has no `POST` forms for the check ignores.

This bug was noticed on an older installation of `4.1.1` but it seems to be the case for `master` still as well.

**To Reproduce the bug**

1. Try to dismiss a "Things to check" panel.

**Comment by nijel** [comment]
This is supposed to happen in JavaScript, the link has `check-dismiss` class and that is handled here:

https://github.com/WeblateOrg/weblate/blob/aeede8d3f8f4060ab77e9a4be91f8784922b8af9/weblate/static/editor/full.js#L303-L322

Do you have JavaScript enabled? Did you run `collectstatic` on [upgrade](https://docs.weblate.org/en/latest/admin/upgrade.html)?

**Comment by minusf** [comment]
yes, the file is present on the server under `data/static/editor/full.js` but it doesnt seem to be included in `output.XXX.js` by django compressor.

**Comment by minusf** [comment]
i turned of `COMPRESS_ENABLED` and the js files are still not loaded from `translate.html` template.

```
  <script defer data-cfasync="false" src="/static/js/slugify.js?v=4.1.1" type="text/javascript"></script>
  <script defer data-cfasync="false" src="/static/loader-bootstrap.js?v=4.1.1" type="text/javascript"></script>
---> this is where they should show up
  <link rel="image_src" type="image/png" href="/static/weblate-128.png"/>
```

very strange

**Comment by minusf** [comment]
i found the issue, it was an out of date locally modified `base.html`.  I apologize for the noise and thanks for the clues.
