### ISSUE TITLE
Press "?" for available keyboard shortcuts (as on GitHub)

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#5064]
I think it would be a nice feature for translators if they could simply press `'?'` and be presented with a pop-up with all available keyboard shortcuts. Like on GitHub.
![image](https://user-images.githubusercontent.com/26718215/102606520-237f3000-4127-11eb-9aa9-16b7ec12f3f9.png)
What do you think?

**Comment by debottamKundu** [comment]
If this issue has not been assigned yet, is it okay if I pick it up?

**Comment by nijel** [comment]
Yes, you're welcome to work on this!

**Comment by ilocit** [comment]
Thanks for picking this up!

Matthias Caesar
iLocIT!

________________________________

**Comment by Oymate** [comment]
"?" Is a bit too general. Maybe"Ctrl+?" Or "Shift+?" :-)

**Comment by ilocit** [comment]
`CTRL ?` is fine, sure. 
(Or `F1`, since this is usually the key for Help on Windows; if this is possbile and not already used by the Browser itself to launch the Browser help).
Thanks a mil!

**Comment by hasecilu** [comment]
What do you think in showing the keyboard shortcut in a small label when hovering over a button, something like this (taken from GitHub open tag):
![image](https://github.com/WeblateOrg/weblate/assets/53124818/2af3b75a-bf35-454c-a4f0-140a90f4293d)
