### ISSUE TITLE
User can lock himself by restricting component

### ISSUE THREAD

**Issue by marusak** [WeblateOrg/weblate#5068]
**Describe the bug**

This is very similar to https://github.com/WeblateOrg/weblate/issues/3652 just that there is special case, when this happens.

**To Reproduce the bug**

For this we need to have two components that share same strings. Then we need to lock one of them so we cannot edit it.
Then in the unlocked one we will translate some string. It will fail on consistency, as in the locked component the string does not get translated (it is locked, no surprise there). This is very confusing and there is literally nothing I can do about it.

**Expected behavior**

Do not show inconsistent translation against locked component when the string in locked component is empty. (I would suggest not showing inconsistent translation if one of them is not translated but I've read some comments about it. I feel like just the non-translated component should offer suggestion and not have inconsistent translation)

**Screenshots**

(cockpit/rhel-8.2 is locked and I cannot edit or access it)
![locked](https://user-images.githubusercontent.com/12330670/102683279-f044ab80-41cf-11eb-85dd-33630e89ebb8.png)

**Server configuration and status**

This happens on https://translate.fedoraproject.org instance, but it really feels like upstream bug. If this is misconfiguration  or you need more info about the deployment, I am happy to provide that.

**Note**
It might be of some interest, that I have locked the component, but now I cannot see it. When I visit https://translate.fedoraproject.org/translate/cockpit/rhel-8-2/ where I should see it, I am greeted with `The page you are looking for was not found. The project you are looking for does not exist or is not publicly available. `. I am admin for `cockpit` project in https://translate.fedoraproject.org so I find it a bit weird that I cannot access it and I shot myself into leg with locking it from other users. I'll contact admin of this instance if they can unlock it for me.

**Comment by nijel** [comment]
I think it works as intended. In case you want to disable some component here, disable translation propagation on these.

> It might be of some interest, that I have locked the component, but now I cannot see it.

It seems to be removed now. But you're right, that you might have permission to toggle "Restricted component" status and you will lose access to that component because you lack explicit privileges for it...
