### ISSUE TITLE
Option to make weblate not update POT creation date

### ISSUE THREAD

**Issue by hhyyrylainen** [WeblateOrg/weblate#5071]
**Is your feature request related to a problem? If so, please describe.**
For some reason my weblate instance always wants to update both `POT-Creation-Date` and `PO-Revision-Date`. I'd like to have an option to *only* update `PO-Revision-Date` because `POT-Creation-Date` causes merge conflicts if a programmer has locally ran translation extraction, which causes the  `POT-Creation-Date` to be updated. This is very logical as programmers add new strings to be localized etc. However, what I don't get is why weblate also wants to update that timestamp, even though it doesn't actually have anyway to run our scripts for regenerating the .pot file.

I tried the addon `Update PO files to match POT (msgmerge)` but that made things just worse by ignoring line wrapping, and still leaving `POT-Creation-Date` values updated.

This is the kind of diff PRs from weblate contain:
```diff
--- a/locale/bg.po
+++ b/locale/bg.po
@@ -7,8 +7,8 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PROJECT VERSION\n"
 "Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
-"POT-Creation-Date: 2020-12-17 20:40+0200\n"
-"PO-Revision-Date: 2020-12-16 02:36+0000\n"
+"POT-Creation-Date: 2020-12-17 10:38+0200\n"
+"PO-Revision-Date: 2020-12-17 20:28+0000\n"
 "Last-Translator: ...\n"
 "Language-Team: Bulgarian <https://translate.revolutionarygamesstudio.com/"
 "projects/thrive/thrive-game/bg/>\n"
```
Example PR: https://github.com/Revolutionary-Games/Thrive/pull/1939/files

**Describe the solution you'd like**
I'd like some kind of option, or maybe even a default value, for weblate to **not** touch the line with `POT-Creation-Date` at all in .po files.

Sorry if I missed some bit of documentation about this or a configuration option that already does this, or if this is a duplicate request. I didn't find anything about this when searching.

**Describe alternatives you've considered**
I tried that addon I mentioned before, but it didn't solve my issue, and caused new problems.

**Additional context**
Self hosted weblate at: https://translate.revolutionarygamesstudio.com
With source repository at: https://github.com/Revolutionary-Games/Thrive
Updates are configured to be sent as separate PRs (see example above) because I didn't want weblate directly pushing to master and I thought that pushing to a branch in the main repository wouldn't give any benefits over making PRs from a fork.

**Comment by nijel** [comment]
Weblate doesn't update `POT-Creation-Date` (unless you instruct it to invoke msgmerge). But you seem to be using that (https://github.com/Revolutionary-Games/Thrive/commit/64145274cdbecb49214daae6858fb41eb4e29718). So the solution is simple - just uninstall the msgmerge addon in case you don't want it to happen.

**Comment by hhyyrylainen** [comment]
I had that addon just for 5 minutes, to see if it would fix the POT update changes, then uninstalled it.
This is what the addons page looks like to me:
![Kuvakaappaus - 2020-12-20 20-54-36](https://user-images.githubusercontent.com/3796411/102721785-a362f100-4305-11eb-88d8-6d58c844b311.png)

Here's a PR that was opened by weblate, after I had uninstalled the addon: https://github.com/Revolutionary-Games/Thrive/pull/1955/files
And in it 2 out of the 3 updated translation files have a change in the `POT-Creation-Date`. At least I'm pretty sure that the msgmerge addon shouldn't have done anything to that PR, because I removed the msgmerge addon before I merged the previous PR. So that PR should have only gotten opened by weblate after the addon was disabled.

**Comment by nijel** [comment]
Hmm, that might be the outcome of Git merge driver we're using and reverted changes from the msgmerge you've done in https://github.com/Revolutionary-Games/Thrive/commit/6af788e7ba57d0144f52c88aaaafde34e9506612. Is your component configured to use rebase?

**Comment by hhyyrylainen** [comment]
I haven't manually went in and tried to make it do rebases. But as far as I can tell, it's always done rebases whenever a new commit gets added to master. But that doesn't seem to correlate with when the POT timestamp gets changed.
I just looked through all the weblate PRs and it doesn't seem that having force pushes in them cause the POT timestamp to change. Here's a PR with force pushes in it, which I assume are from rebases, but no POT timestamp update: https://github.com/Revolutionary-Games/Thrive/pull/1832
This is the first PR where the POT timestamp is changing: https://github.com/Revolutionary-Games/Thrive/pull/1939

It's much more recent than I initially thought. I seem to recall that I had to fix merge conflicts already twice with the POT timestamps weeks ago... but apparently those weren't from the weblate opened PRs.
That first PR with the POT timestamp change, might actually correspond with when I enabled the "Squash Git commits" addon, because I wanted to reduce the amount of translation commits going into master. 
So maybe that squash addon is causing this?

**Comment by nijel** [comment]
The squash addon only operates at git level, it doesn't change content of the files, it just reorganizes commits. When both squash and msgmerge addons are installed that will most likely (depending on squash addon configuration) lead to changes of msgmerge being incorporated into the translation commits.

Anyway do you still get POT timestamp updates after removing the msgmerge addon and merging or resetting all pending changes on the Weblate side?

**Comment by hhyyrylainen** [comment]
I just merged the currently open PR from weblate and made a few small changes to get weblate to open a new PR. This time `POT-Creation-Date` was not updated. So I still don't know what caused the POT timestmap to change *before* I enabled that msgmerge addon... I suppose I'll close this issue until / if I can get the incorrect POT timestamp update to happen again.

**Comment by nijel** [comment]
Weblate is not supposed to update the POT timestamp and I found no code which would do that, so in case you hit this again, it would be good to collect as much details as possible before further changes stack up on that.

**Comment by eytienne** [comment]
Looks like the headers are updated in any case: https://github.com/WeblateOrg/weblate/blob/main/weblate/trans/models/translation.py#L779-L800
It would be nice to have an option `set_revision_headers` to drop both `last_translator` and `PO_Revision_Date` because they are causes of unnecessary conflicts in our project. I could make the PR.

**Comment by nijel** [comment]
@eytienne This issue was about `POT-Creation-Date`, which is correctly *not* being updated. If you want to discuss other headers, please open a separate issue. But there definitely are projects which want to see this updated.
