### ISSUE TITLE
UTF-8 Java Properties upload broken

### ISSUE THREAD

**Issue by Nick-kel** [WeblateOrg/weblate#5083]
If I upload something to a language in Weblate, the source language works very well in UTF-8 (e.g. a § is displayed correctly). But if I upload a translation to a "normal" language, it isn't in UTF-8 and in front of a § there's a weird character:
![image](https://user-images.githubusercontent.com/42046014/102817734-96f79a80-43d0-11eb-8304-9050678c9aaf.png)

I'm using the newest version of Weblate

**Comment by nijel** [comment]
Maybe the existing file is iso-8859-1 encoded? What file format do you use? How do you upload?

**Comment by Nick-kel** [comment]
The existing file is UTF-8 encoded and I'm using a Java Properties (UTF-8) format. I'm uploading the translation using the "Files" button in a language.

**Comment by nijel** [comment]
I mean which [upload method](https://docs.weblate.org/en/latest/user/files.html#upload-method) do you use...

**Comment by Nick-kel** [comment]
The upload method is "add as translation"

**Comment by nijel** [comment]
Can you please share the uploaded file? It seems that it's detected as iso-8859-1 instead of UTF-8. Maybe it has encoding error or there is something wrong with the detection.

**Comment by Nick-kel** [comment]
@nijel https://www.file-upload.net/download-14404874/test.properties.html

**Comment by nijel** [comment]
There is no unicode char in there which could break...

**Comment by Nick-kel** [comment]
@nijel ah sorry: https://www.file-upload.net/download-14405120/en_US.properties.html

**Comment by nijel** [comment]
That one works fine in my tests. The content looks like something (mis-)detectcs it as iso-8859-1. It might be a bug in [chardet](https://github.com/chardet/chardet) on the specific file you are using.

**Comment by Nick-kel** [comment]
![image](https://user-images.githubusercontent.com/42046014/103038287-5f265980-456e-11eb-9937-a7c2da2a085f.png)
@nijel how to fix this?

**Comment by nijel** [comment]
How to reproduce that?

**Comment by GoneTone** [comment]
I also encountered the same problem. When uploading a new Chinese translation, it will be garbled.

![image](https://user-images.githubusercontent.com/10025956/103137318-e86e9500-4702-11eb-9645-c69c103ed3ae.png)

**Comment by Nick-kel** [comment]
@nijel I don't know ... I only uploaded the translations, these are my settings:
![image](https://user-images.githubusercontent.com/42046014/103137942-d0305300-46cd-11eb-9de2-ae1ec889b4af.png)
In the source language there's no problem with the encoding, only in other languages

**Comment by nijel** [comment]
The most likely suspect is still chardet here as the detection is always in place. Unfortunately, the file in https://github.com/WeblateOrg/weblate/issues/5083#issuecomment-749754980 doesn't show it. Can reproduce it with that file? Having the actual uploaded file to reproduce this would help...

**Comment by GoneTone** [comment]
@nijel Here contains the demo video and translation files:
https://drive.google.com/drive/folders/1pY2AEZgkvsgW-DOVRN9tN5u4Z_fd99Vn?usp=sharing

**Comment by nijel** [comment]
@GoneTone I can reproduce this if the file format is configured to ISO-8859-1, and it's expected in this case - the replace upload method does no processing of the file. When I switch file format in Weblate to UTF-8, it is shown correctly and the replace upload works fine. What still seems to be broken is regular upload though, what probably matches behavior @Nick-kel was describing initially.
