### ISSUE TITLE
ODF-file string extraction fails

### ISSUE THREAD

**Issue by funktionierbar** [WeblateOrg/weblate#5095]
**Describe the bug**

When I upload an odf/odt/ods file as a component, it gets recognized, the creation-mask is filled out correctly, the component gets successfully created, but it contains no strings. 

**To Reproduce the bug**

1. In an existing Document, click on "Add new translation component" -> "Translate Document"
2. Upload a odf-file (or ods) and select the original language, in my case German
3. Select "File format OpenDocument file, Filemask testodf/*.odt" and "Continue"
4. Scroll down, click "save" and then "return to the component", then on the origin language
5. It contains 0 strings.

If I then click on "File"-> "Download original translation file", the file is the same as I uploaded, but, if I download it as any other format, it comes up empty. 

**Expected behavior**

I expect the strings to be extracted from the odf file into the component. 

**Server configuration and status**

Weblate installation: self-hosted

On pip installed Weblate:

weblate list_versions

` * Weblate: 4.3.2
 * Django: 3.1.3
 * siphashc: 2.1
 * Whoosh: 2.7.4
 * translate-toolkit: 3.2.0
 * lxml: 4.6.1
 * Pillow: 8.0.1
 * bleach: 3.2.1
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.2
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 50.3.2
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.5
 * weblate-language-data: 2020.11
 * html2text: 2020.1.16
 * pycairo: 1.20.0
 * pygobject: 3.38.0
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.19.3
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.11
 * borgbackup: 1.1.14
 * pyparsing: 2.4.7
 * Python: 3.6.9
 * Git: 2.17.1
 * psycopg2-binary: 2.8.6
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.12
 * mysqlclient: 2.0.1
 * Redis server: 4.0.9
 * MySQL sever: 5.7.32
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 3.10.0-1127.18.2.vz7.163.46 (x86_64)
`

**Comment by nijel** [comment]
Is your celery worker running fine? In most cases parsing of the file happens in the background and in case the worker is not running, it won't happen.

In case it does, it might be an issue with the particular file you are trying to translate.

**Comment by funktionierbar** [comment]
Thank you for your answer. I think I am getting closer to the source of the problem. In my syslog I discovered a 

> ERROR Failure while executing task: PermissionError: [Errno 13] Permission denied: '/home/weblate/weblate/data/vcs/testproject/test.lock'

that appears when I create a new component. So it seems to be connected to the permissions. I have had some difficulties, with file system ownership, the wsgi-process and apache2 process, but I thought I had resolved that, because I could create components using pot-files without any problems.
So I am serving the files with apache2 and mod_wsgi. The thing was, that while apache2 is run under the www-data user, and the wsgi processes are also run under the www-data user, I didnt want to have the weblate files owned by www-data for security reasons, so I had them owned by a user called weblate and forced the wsgi process to be ran from the same user "weblate". I then had the weblate/data folder owned by www-data user but weblate group, so the wsgi process could access them. I thought that worked fine. 
Anyways, now I tried to have everything owned by www-data:www-data and the wsgi process running as default www-data, then the perfomance report shows no errors, but when I run weblate check --deploy, it shows all those warnings that files are owned by a different user. And I cant start the celery process again.... 

Well, I will continue to try things, but I would be thankful for pointers, the documentation is not very elaborate on this issue.

**Comment by nijel** [comment]
> Well, I will continue to try things, but I would be thankful for pointers, the documentation is not very elaborate on this issue.

Documentation improvements are always welcome, please add the bits you find missing there.

**Comment by funktionierbar** [comment]
I managed to solve my problem, it was a permissions problem. 

I solved the problem by having all files and folders (including the data folger) owned by weblate:weblate, the user I used to set up the virtual environment and the pip installation.
I then changed the virtualhost file so that the mod_wsgi process was running not as user www-data, as is default with apache2 but under the same user used to set up the virtualenv.
This can be done by appending the WSGIDaemonProcess statement with a user=weblate argument.

[https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html](https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html)

I am not really sure if I should add that to the Documentation, because I am not really sure what these changes mean for server security.

```
#
# VirtualHost for Weblate
#
# This example assumes Weblate is installed in virtualenv in /home/weblate/weblate-env
# and DATA_DIR is set to /home/weblate/data, please adjust paths to match your setup.
#
<VirtualHost *:80>
    ServerAdmin admin@weblate.example.org
    ServerName weblate.example.org

    # DATA_DIR/static/favicon.ico
    Alias /favicon.ico /home/weblate/data/static/favicon.ico

    # DATA_DIR/static/
    Alias /static/ /home/weblate/data/static/
    <Directory /home/weblate/data/static/>
        Require all granted
    </Directory>

    # DATA_DIR/media/
    Alias /media/ /home/weblate/data/media/
    <Directory /home/weblate/data/media/>
        Require all granted
    </Directory>

    # Path to your Weblate virtualenv
    WSGIDaemonProcess weblate python-home=/home/weblate/weblate-env user=weblate
    WSGIProcessGroup weblate
    WSGIApplicationGroup %{GLOBAL}

    WSGIScriptAlias / /home/weblate/weblate-env/lib/python3.7/site-packages/weblate/wsgi.py process-group=weblate request-timeout=600
    WSGIPassAuthorization On

    <Directory /home/weblate/weblate-env/lib/python3.7/site-packages/weblate/>
        <Files wsgi.py>
        Require all granted
        </Files>
    </Directory>

</VirtualHost>

```

**Comment by nijel** [comment]
The requirement for correct permissions and same user running both processes is described in several places in the docs, for example https://docs.weblate.org/en/latest/admin/install.html#filesystem-permissions. If you have idea how to make it easier to discover, suggestions or patches are definitely welcome.

**Comment by nijel** [comment]
i've made some improvements in 734c16267a431cf2bd19e83feecda98409def09c, but suggestions are still welcome.
