### ISSUE TITLE
Problem creating .mo files with plural strings

### ISSUE THREAD

**Issue by MocioF** [WeblateOrg/weblate#5098]
The .mo file generated by weblate doesn't include some strings with plurals.
The strings are fine included in the .po file but the .mo doesn't store some of them.

I have seen the issue with these strings:
https://hosted.weblate.org/translate/gnucash/gnucash/it/?checksum=eb14c2b63810bd3f
https://hosted.weblate.org/translate/gnucash/gnucash/it/?checksum=e5b91ebb2952c05d

The .mo file can be downloaded from:
https://hosted.weblate.org/download/gnucash/gnucash/it/?format=mo

This could be a gettext version problem.

If I download the Italian .po file (https://hosted.weblate.org/download/gnucash/gnucash/it/?format=po) and then save it as a .mo file with poedit on a Linux system with gettext-0.21 the resulting .mo file stores the strings.

**To Reproduce the bug**

1. Go to 'https://hosted.weblate.org/projects/gnucash/gnucash/it/'
2. Click on 'File' and the download the (gettext MO)
3. replace your gnucash.mo (in my installation /usr/share/locale/it/LC_MESSAGES/gnucash.mo for Italian translation), with the downloaded file

**Expected behavior**

The file downloaded from https://hosted.weblate.org/download/gnucash/gnucash/it/?format=mo should store all strings.

**Comment by nijel** [comment]
There indeed seems to be something wrong with the generated file:

> msgunfmt: file "/tmp/gnucash-gnucash-it.mo" is not in GNU .mo format: Some messages are at a wrong index in the hash table.

**Comment by nijel** [comment]
I've done some investigation and it seems that there is some issue in generating hash tables in the translate-toolkit. In some cases it produces a table which cannot be parsed with gettext. The tricky part is there is [no specification for the hash table](https://www.gnu.org/software/gettext/manual/html_node/MO-Files.html):

> The precise hashing algorithm used is fairly dependent on GNU gettext code, and is not documented here.

**Comment by nijel** [comment]
https://github.com/translate/translate/pull/4218 should most likely address this
