### ISSUE TITLE
Translation files download size reduction 

### ISSUE THREAD

**Issue by Heychsea** [WeblateOrg/weblate#5111]
**Is your feature request related to a problem? If so, please describe.**
I am using Weblate as a translation file source for a project but I find it wasteful to send those files only with human readable formatting as it can use space and bandwidth for files that won't be accessed by users.

**Describe the solution you'd like**
Would it be possible to send these files without unnecessary whitespaces and possibly, compressed? 

**Describe alternatives you've considered**
I considered using the VCS but it does not offer this kind of feature.

**Additional context**

**Comment by nijel** [comment]
The web server should compress the content in case the client accepts compressed content. Removing the human formatting will have  minimal impact on the size of the compressed payload.

**Comment by Heychsea** [comment]
That's probably true for the formatting. As for the compression, it unfortunately does not work as far as my tests says. My client accepts gzip and deflate but there is no 'Content-Encoding' header set in the response.

**Comment by nijel** [comment]
You're right, I was testing it wrongly...
