### ISSUE TITLE
Loss of focus for editing when using a symbol from the toolbar

### ISSUE THREAD

**Issue by SlavekB** [WeblateOrg/weblate#5114]
**Describe the bug**

I often use toolbar symbols to write quotation marks to match our language habits („ … “).

Before upgrading to 4.4, it worked well. After updating to 4.4, by clicking on a symbol in the toolbar, the focus is moved to the toolbar, which is very impractical because it is not possible to continue typing smoothly – this requires mouse movements and clicking back to the appropriate place in the edit field.

**To Reproduce the bug**

1. Open a translation of any component for editing.
2. Write some text.
3. Click the symbol from the toolbar.
4. Try to continue writing more text.
5. You will see that this is not possible, because the focus has moved to the toolbar.

**Expected behavior**

I expect it to work as in the << 4.4 versions, where the toolbar did not steal the focus of the edit field and therefore it was possible to continue writing text smoothly after inserting the symbol.

**Server configuration and status**

Weblate installation: selfhosted installed by pip

```
 * Weblate: 4.4
 * Django: 3.1.4
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.1.1
 * lxml: 4.5.0
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 46.1.3
 * jellyfish: 0.7.2
 * openpyxl: 3.0.3
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.6
 * weblate-language-data: 2020.13
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.36.1
 * diff-match-patch: 20200713
 * requests: 2.23.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.3
 * Cython: 0.29.17
 * misaka: 2.1.1
 * GitPython: 3.1.2
 * borgbackup: 1.1.11
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * boto3: 1.14.7
 * aeidon: 1.7.0
 * iniparse: 0.5
 * Mercurial: 4.8.2
 * git-svn: 2.20.1
 * git-review: 1.27.0
 * Redis server: 5.0.3
 * PostgreSQL server: 11.9
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django_sendmail_backend.backends.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 3.16.6-042stab141.42 (x86_64)
```

**Weblate deploy checks**

```
System check identified no issues (3 silenced).
```

**Comment by nijel** [comment]
Related to changed editor implementation, we will most likely revert it, see https://github.com/WeblateOrg/weblate/issues/5049 and https://github.com/WeblateOrg/weblate/issues/4977
