### ISSUE TITLE
Consistent use of string status bars

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5122]
The string statuses from https://hosted.weblate.org/projects/enrecipes/app-translations/nb_NO/

![image](https://user-images.githubusercontent.com/13802408/103446125-7a831a00-4c7c-11eb-9087-944f33579629.png)

are missing in https://hosted.weblate.org/projects/enrecipes/app-translations/

It would make sense if the totals were listed at the bottom of all views.

I would imagine clicking into a bulk category view would list https://hosted.weblate.org/checks/?project=enrecipes&component=app-translations if more than one language is failing.

**Comment by nijel** [comment]
I'm not sure it's a good idea to add another possibly lengthy listing to the page which can already be quite long when there are many languages (for example https://hosted.weblate.org/projects/weblate/website/).

**Comment by comradekingu** [comment]
@nijel I think mostly it fits, and if it scrolls, it doesn't add scrolling to what is already there.
All user-translated languages are at the top anyway, so there is already a mitigation in place.

I think it is a similar problem to the earlier pagination. Given enough screen, there is more utility, where it doesn't remove it from others.

**Comment by nijel** [comment]
Another reason against this is performance - going to the check level details is way more expensive than calculating basic stats which are needed on the component page right now...

**Comment by comradekingu** [comment]
@nijel It doesn't have to be all calculated.

What I mainly want is a handy link for https://hosted.weblate.org/zen/cyberos/-/nb_NO/?q=state:%3Ctranslated for example.

![bilde](https://user-images.githubusercontent.com/13802408/108582057-223dcf80-7331-11eb-8da5-bdb221190025.png)

Doesn't even have to be translation status (circle)
Just string status (star) would be a major improvement.

I think always listing all status bars is a further UI-consistency fix that means there could be no calculating nothing. Bonus for graying out ones that aren't relevant, but I have a hard time when the position of them change between projects.

**Comment by nijel** [comment]
This will not work well - there is a performance issue with calculating the stats and displaying all ~80 categories without indicating that there is some content will not be useful at all.
