### ISSUE TITLE
Android component discovery example does not match any components

### ISSUE THREAD

**Issue by vinaygopinath** [WeblateOrg/weblate#5143]
**Describe the issue**
The Android example for the [component discovery addon](https://docs.weblate.org/en/latest/admin/addons.html#component-discovery) does not match any components when there are multiple files. I was able to get component discovery working with a workaround, but the generated language translation files are incorrectly named.

The example regular expression is
```
res/values-(?P<language>[^/.]*)/strings-(?P<component>[^/]*)\.xml
```

I have multiple files that use the format `strings_some_name.xml` (underscore instead of the hyphen after "strings"), so I modified it to
```
res/values-(?P<language>[^/.]*)/strings_(?P<component>[^/]*)\.xml
```

Since I'm just getting started with localization and Weblate, I have files only in the `values` directory (the default fallback language directory in the Android world) and there are no language code directories like `values-es`.

Some file names
```
values/strings_login.xml
values/strings_register.xml
values/strings_home.xml
```
With the regular expression `res/values-(?P<language>[^/.]*)/strings_(?P<component>[^/]*)\.xml` and monolingual base file name `res/values/strings_{{ component }}.xml`, I see the message `No components were matched!`

To get it working, I had to make the following changes:
1. Prefix the regular expression and file name with the relative path from the root of the project. 
```
mymodulename/src/main/res/values-(?P<language>[^/.]*)/strings_(?P<component>[^/]*)\.xml
mymodulename/src/main/res/values/strings_{{ component }}.xml
```
2. Since I don't have any folders that match `values-(?P<language>[^/.]*)`, the regular expression still wouldn't match `values/strings_login.xml`, so I made the hyphen optional, using `values[-]*` instead of `values-`
```
mymodulename/src/main/res/values[-]*(?P<language>[^/.]*)/strings_(?P<component>[^/]*)\.xml
```
3. I changed the language filter to `^(.*)$`

With these changes, I'm able to get component discovery working, but the consequence of making the `values-` hyphen optional is that adding a new translation and translating some strings results in files with the name format `valueses/strings_login.xml` when Android expects `values-es/strings_login.xml` (hyphen between `values` and the language code `es`)

**To Reproduce the issue**

1. Set up an Android project with files like `strings_something.xml` and `strings_something_else.xml` in the `values` folder.
2. Set up a base component with the file mask `mymodule/src/main/res/values-*/strings.xml`, language filter `^[^.]+$` and monolingual base language file `mymodule/src/main/res/values/strings.xml`
3. Attempt to enable component discovery using the Android example in the documentation and in the component discovery screen.
3. Click 'Save'
4. The "No components were matched!" error is displayed

**Expected behavior**
The example should match components, and new translations should generate files that match the Android convention.

**Server configuration and status**
Weblate installation: Docker

 * Weblate: 4.4
 * Django: 3.1.4
 * siphashc: 2.1
 * Whoosh: 2.7.4
 * translate-toolkit: 3.2.0
 * lxml: 4.6.2
 * Pillow: 8.0.1
 * bleach: 3.2.1
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.10.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.2
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 5.0.4
 * kombu: 5.0.2
 * translation-finder: 2.6
 * weblate-language-data: 2020.13
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.25.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.19.5
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.11
 * borgbackup: 1.1.14
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.6
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.16.36
 * zeep: 4.0.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.2
 * Mercurial: 5.6.1
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * Redis server: 6.0.9
 * PostgreSQL server: 13.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp-relay.gmail.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.4.0-1034-aws (x86_64)

**Comment by nijel** [comment]
If the path starts with `mymodule/src/main/` in your repo, the regular expression should as well. These are just examples for some usual setups - the examples cannot cover everything...

**Comment by vinaygopinath** [comment]
Thanks for your response. No Android project would have string resources starting at `res/values/...`, so it might be easier for those getting started with Weblate to update the example to reflect that.

Also, I have yet to find a way to have component discovery working in conjunction with the correct creation of new translation strings. The complicating factor is that Android string resources don't always conform to the format `values-<language-code>` - It's possible to have a default set of string resources in the `values` folder. Changing the regular expression to handle `values` OR `values-es` breaks the folder names for new translations - i.e, adding Italian as a new language results in a `valuesit` folder when the expected name is `values-it`. 

Is there an example repo that demonstrates the use of Weblate in an Android project that uses multiple string files?

**Comment by nijel** [comment]
> No Android project would have string resources starting at res/values/...,

Wrong, there are lots of them. First ones that popped up on Hosted Weblate (order and selection are random as provided by the database):

* https://github.com/ciubex/dscautorename
* https://github.com/otakuhqz/Omega
* https://github.com/Etar-Group/Etar-Calendar

I have no clue whether it's good practice or not, but there is apparently not a single layout that would fit all projects.

Something closer to your setup might be https://github.com/ram-on/SkyTube with following addon configuration:

```python
{'base_file_template': 'app/src/main/res/values/strings_{{ component }}.xml',
 'confirm': True,
 'file_format': 'aresource',
 'language_regex': '^[^.]+$',
 'match': 'app/src/main/res/values-(?P<language>[^/]*)/strings_(?P<component>[^/]*).xml',
 'name_template': '{{ component|title }}',
 'preview': True,
 'remove': False}
```

**Comment by vinaygopinath** [comment]
I stand corrected :)

Thank you for the configuration snippet from SkyTube. That looks similar to the one in the example, but I'll try again.
