### ISSUE TITLE
Cannot parse INI/JSON language files

### ISSUE THREAD

**Issue by kenygamer** [WeblateOrg/weblate#5145]
## Description
Hello I am openign an issue, self-explanatory. INI and JSON file strings are not loading.

The case is that when I try to load INI or JSON files from a repository they list up successfully but none of the strings are added.

I can't recall as I managed to get them to load, however I have already created multiple Weblate projects and none loads the strings successfully.

**Comment by nijel** [comment]
It would be great if you actually followed my advice in https://github.com/WeblateOrg/weblate/issues/4970#issuecomment-754530482 - to fill in the issue template. It's not there to be removed, but to collect useful information.

I can't reproduce this.

**Comment by kenygamer** [comment]
@nijel would like to start from the base, that's to rule out that the Celery is having a problem.

I have filled out my template in each of my issues, the information is the same. I will update now.

**Comment by kenygamer** [comment]
I have officially confirmed that Celery bad setup is the biggest time waster.

**Comment by nijel** [comment]
> I have officially confirmed that Celery bad setup is the biggest time waster.

The biggest time waster is not reading documentation and not filling issue templates. Each issue template suggest you to paste output of `weblate check --deploy` which would have immediately told you that the issue with Celery is there.
