### ISSUE TITLE
Celery is failing to connect to Redis

### ISSUE THREAD

**Issue by kenygamer** [WeblateOrg/weblate#5147]
## Description
In the configuration there is a directive that allows you to enable the cache with Redis.

This directive is indeed necessary, since Weblate complains if Redis is not enabled. It is used by the Celery worker for caching.

After setting up the connection information successfully, and try to perform an action like deleting a project, I get the following error on the screen:

https://ibb.co/F4Dh6xp

**Comment by nijel** [comment]
Your `CELERY_BROKER_URL` lacks authentication, see https://docs.celeryproject.org/en/stable/getting-started/brokers/redis.html for configuring it.

**Comment by kenygamer** [comment]
@nijel Thanks, I solved it, I was using the `CACHES default.options.PASSWORD` field.

It was stated in Django that that field should be used, so I didn't think the `CELERY_BROKER_URL` needed to be changed.
