### ISSUE TITLE
The speed of the site is unacceptable

### ISSUE THREAD

**Issue by eqMFqfFd** [WeblateOrg/weblate#5149]
## Description

The speed of Weblate is unacceptable. The loading of the pages takes between 1s to 30s. I'm very inquiring to find why Weblate takes so long to load. All my other sites load perfectly.

I suspected a confiuration error, but Weblate confiugration is filled.

What can be the issue here?

**Comment by nijel** [comment]
Can you post more details? I can't reproduce.

**Comment by kenygamer** [comment]
@nijel Sometimes the page takes a long time to load:
https://i18n.crowdmc.us.to/

**Comment by nijel** [comment]
Maybe you are hitting same issues as https://github.com/WeblateOrg/weblate/issues/5152?

**Comment by kenygamer** [comment]
I don't really know.

**Comment by kenygamer** [comment]
@nijel How can I update my weblate installation to support your PR? Configuring and setting up everything took ages.

**Comment by nijel** [comment]
You can apply the patch manually or wait for the 4.4.1 release which will include that.
