### ISSUE TITLE
Best practise project/component size

### ISSUE THREAD

**Issue by eschumacher-99** [WeblateOrg/weblate#5152]
Hello, 
I would like to know what's the best size for projects and components on Weblate.
Currently, I have one project with 4 components that each hold 20.000 strings and 27 languages.
Everytime I click on a component, it takes about half an hour for it to parse the xliff file and show up on my screen.
This happens since around version 4.2 or 4.3 I believe.
Is there any way to avoid this or is it better to split it into more and therefore smaller components?
Would that change anything?

<!--
Want your answer quickly and guaranteed? Follow https://weblate.org/support/ to reach our dedicated support team. As a subscriber, you will always have priority and help Weblate growing.

1. Go to a large project
2. Go to a component containing about 20.000 strings
3. Click on the component
4. Wait a long time before the page is loaded and the languages show up.

**Comment by nijel** [comment]
> Everytime I click on a component, it takes about half an hour for it to parse the xliff file and show up on my screen.

There is no file parsing going on when displaying the page, it has to be something else causing this delay.

What can be lengthy is updating stats, but this is cached and should not happen that often.

What version do you currently use?

**Comment by eschumacher-99** [comment]
> What version do you currently use?
I'm using Version 4.3

**Comment by nijel** [comment]
I think there were some slight changes in 4.4, but I don't think it will make a major difference.

When starting with an empty cache, calculating the stats take 4-8 database queries per translation. This should be needed only for changed translations, and it is pre-calculated in the background. If massive changes are going on in all the translations, it will definitely have measurable impact.

In case it happens to you regularly, it would be interesting to figure out why it happens.

**Comment by eschumacher-99** [comment]
Could you also please answer my question on #5151 ? You marked it as duplicate, but I said that I noticed someone already asked this and wanted to know how long you would estimate it takes until it's done and asked for the best file format. 

"I did notice that this enhancement was already added to the todo list, but I would like to ask when to expect the solution?
Also, are there any other file formats that cause less problems concerning the encoding and the state of translation?
As far as I've seen, GNU Gettext format would be best practise, is that correct?"

Thank you very much!!

**Comment by nijel** [comment]
@eschumacher-99 I did answer it there, and I don't see how it is related to this issue...

**Comment by eschumacher-99** [comment]
I looked it up and this is the part that causes the problem. base contains the whole xliff file and this method gets called everytime you click on the project.

```
diff --git a/formats/ttkit.py b/formats/ttkit.py
index 19b0f86..fb09758 100644
--- a/formats/ttkit.py
+++ b/formats/ttkit.py
@@ -369,7 +369,7 @@ class TTKitFormat(TranslationFormat):
         if not base:
             return monolingual and cls.new_translation is not None
         try:
-            cls.parse_store(base)
+            #cls.parse_store(base)
             return True
         except Exception:
             report_error(cause="File parse error")
```

**Comment by nijel** [comment]
It really shouldn't, can you please try whether upgrading addresses it?

**Comment by nijel** [comment]
Hmm, looking at the code it can indeed happen in some situations...

**Comment by nijel** [comment]
https://github.com/WeblateOrg/weblate/pull/5153 should address the issue I've found (it's not yet tested, waiting for CI to run the tests)

**Comment by eschumacher-99** [comment]
> #5153 should address the issue I've found (it's not yet tested, waiting for CI to run the tests)

Thank you very much!
