### ISSUE TITLE
```suggestion

### ISSUE THREAD

**Issue by jace4511** [WeblateOrg/weblate#5156]
```suggestion
Automation is possible by granting the Weblate user (available on various
code hosting sites) push access to your repository and configuring
```

_Originally posted by @nijel in https://github.com/WeblateOrg/weblate/pull/5097#discussion_r552554144_

**Comment by comradekingu** [comment]
I revised the text, and think it is good now. Automation isn't really the topic of importing projects into Weblate though.

**Comment by nijel** [comment]
Thanks for your feedback. It's more practical if you comment inside the pull request instead of opening a separate issue for each suggestion.
