### ISSUE TITLE
Add support for explicit DCO

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#516]
Some project require contributions to be Signed-Off-By with accompanying DCO. Weblate should provide support for this:
- Add UI for accepting DCO
- Properly signoff commits
- Avoid contributions without agreeing to DCO
##

**Comment by raphaelm** [comment]
We would be happy to pay you (or someone, fully or in part, depending on the effort) for the development of this feature. We're also an open source business (pretix.eu) but currently lack the time to contribute this back ourselves. We do not strictly really need Signed-Off-By, it would be sufficient for us if it is ensured that every translator has to confirm the DCO in the web UI, but Signed-Off-By would be nice.

**Comment by nijel** [comment]
I think it would be best to implement after https://github.com/WeblateOrg/weblate/issues/1798 as this would touch the permissions code which is going to be rewritten.

Regular invoice from me is possible, please let me know your possibilities at michal@cihar.com

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
