### ISSUE TITLE
Unable to dismiss "Mismatched full stop" check.

### ISSUE THREAD

**Issue by baranovskiykonstantin** [WeblateOrg/weblate#5166]
The "Things to check" panel has no Dismiss button for the "Mismatched full stop" check.
The hotkey also does not work.

![screenshot](https://user-images.githubusercontent.com/3592925/104049048-ede0da80-51ec-11eb-96f3-bbe026d54cbd.png)

Weblate 4.4.1-dev

**Comment by nijel** [comment]
This check is set as enforced in component configuration (https://hosted.weblate.org/settings/kicad/master-source/#translation), and enforced checks can not be dismissed.
