### ISSUE TITLE
Remove "0 strings changed" strings from "Changed string" digest

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5170]
Verifying strings puts them in the stringlog as "0 strings changed".
In turn actually changed strings drown out in the e-mail digest about changed strings.

I think it is also possible to save a string with no changes to achieve the same (that shouldn't be possible if so).

I wonder if confirming strings removes "needs editing".

**Comment by nijel** [comment]
Can you please share screenshot of the problematic digest? I don't get where you see a problem from the description...

**Comment by comradekingu** [comment]
This is the e-mail (says Digest: Changed string)
![image](https://user-images.githubusercontent.com/13802408/104089092-3390b800-526c-11eb-8a57-93e0ddeb100b.png)

**Comment by nijel** [comment]
I still don't see an issue. The string state has changed there.

**Comment by comradekingu** [comment]
The issue is I am trying to find bad changes and correct them, not keep track of what someone thinks is approved or not.

**Comment by nijel** [comment]
We might add another type of notification. Something like "edited string".

**Comment by nijel** [comment]
There are separate notifications for approval now, so I think this can be closed.
