### ISSUE TITLE
Improve checks listings

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5177]
In for example https://hosted.weblate.org/checks/c_format/venom/translations/?lang=nb_NO I dismissed this check.
It still shows up there without any indication that it is dismissed, it isn't in https://hosted.weblate.org/projects/venom/translations/nb_NO/#history and it isn't in any of the categories in https://hosted.weblate.org/projects/venom/translations/nb_NO/

I think a "dismissed" category showing in all places would be in order. Don't know if it should be for each check.

**Comment by nijel** [comment]
It shows counts, and it is only in the dismissed column. The dismissed checks are useful to know as well - for example to identify problematic strings (for example in this case it indicates issue in string extraction as it's falsely marked as `c-format`).

**Comment by nijel** [comment]
What might be useful here is to reorder columns to show the most important ones (translated, active) first...

**Comment by nijel** [comment]
Implemented in 3689728
