### ISSUE TITLE
Bangla: Error: Warning that it doesn't end with full-stop, but in Bangla sentence ender is ।

### ISSUE THREAD

**Issue by Oymate** [WeblateOrg/weblate#5189]
**Describe the issue**
In Bangla using "।" produces error on trailling stop. This is very time consuming to invidually solve for every single string on thousands of string I have to work with.

**I already tried**
Trying to fix this manually, but this problem affects thousands of string in F-droid and newpipe

Describe the steps you tried to solve the problem yourself.
You could add a special rule for Bangla to not trigger trailling stop if "।" is used.

**To Reproduce the issue**

1. Go to a string ending in full-stop
2. Write some Bangla translation with sentence ender "।"
3. Save
4. Trailling stop error

**Expected behavior**

**Screenshots**

**Exception traceback**

**Server configuration and status**
weblate.org service

**Additional context**

**Comment by nijel** [comment]
Can you please share permalink to one of failed strings? Weblate should already support this, so there has to be some issue with the implementation...

**Comment by eighthave** [comment]
I think any of these: https://hosted.weblate.org/translate/f-droid/website/bn/?q=check:end_stop

**Comment by eighthave** [comment]
Also, FYI, the `permissions.permdesc_*` strings came from Android AOSP 10.0.0+r6, so I imagine they have been reviewed to some degree.  That said the F-Droid translators often find errors in the strings from AOSP.

**Comment by nijel** [comment]
Thanks, now I understand that.

Weblate expects [Unicode Character 'DEVANAGARI DANDA' (U+0964)](https://www.fileformat.info/info/unicode/char/0964/index.htm), but F-Droid translations contain [Unicode Character 'BENGALI CURRENCY NUMERATOR FOUR' (U+09F7)](https://www.fileformat.info/info/unicode/char/09f7/index.htm).

They both look visually same, but I have no clue which one of them is correct to use as full stop in a sentence. [Wikipedia](https://en.wikipedia.org/wiki/Bengali_alphabet#Punctuation_marks) seems to agree with Weblate.

We can certainly add another char to the list if somebody can confirm it's actually a correct choice here.

**Comment by Oymate** [comment]
Both should be supported IMO, cause a popular Bangla writing program uses the numerator four so as not to depend on other script blocks

**Comment by Oymate** [comment]
@nijel  After thinking about it, I think this would be better solved by autofix
