### ISSUE TITLE
There are more files for the single language (id), please adjust the filemask and use components for translating different resources

### ISSUE THREAD

**Issue by nicolabeghin** [WeblateOrg/weblate#5196]
Hi everyone
I'm going crazy because I don't understand the reasoning behind this ([documentation](https://docs.weblate.org/en/latest/faq.html#what-does-mean-there-are-more-files-for-the-single-language-en)), if there's any at this point (:D)

I'm creating a new component through ZIP upload. These files are available in the ZIP:
* `testcomponent/resources/localization/productconfigaddon-locales.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_cs.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_de.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_es.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_fr.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_hi.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_hu.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_id.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_in.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_it.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_ja.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_ko.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_ms.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_pl.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_pt.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_ru.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_tr.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_vi.properties`
* `testcomponent/resources/localization/productconfigaddon-locales_zh.properties`

but it gets blocked like below:
![image](https://user-images.githubusercontent.com/2743637/104382129-e6436d80-552d-11eb-8598-8c192db74c03.png)

As per #3952 I tried with both `testcomponent/resources/localization/productconfigaddon-locales.properties` and `testcomponent/resources/localization/productconfigaddon-locales_en.properties` but no luck with both.

Any hint is welcome!

thanks
nicola

**Comment by nicolabeghin** [comment]
Hint: `in` and `id` lead to the same language (Hindi, I assume), therefore removing one of the two changes the message. Problem is, it gets back to the infamous
> There are more files for the single language (**en**), please adjust the filemask and use components for translating different resources

**Comment by nijel** [comment]
It doesn't matter whether there is `productconfigaddon-locales.properties` or `productconfigaddon-locales_en.properties`, but there should be only one of them (and that one should be configured as monolignual base file).

**Comment by nicolabeghin** [comment]
We tried narrowing down to 4 languages and still not accepted, at this point something else must be the issue. I'm really near to give up, it makes no sense anymore :/

- `productconfigaddon/resources/localization/productconfigaddon-locales_de.properties`
- `productconfigaddon/resources/localization/productconfigaddon-locales.properties`
- `productconfigaddon/resources/localization/productconfigaddon-locales_fr.properties`
- `productconfigaddon/resources/localization/productconfigaddon-locales_it.properties`

![image](https://user-images.githubusercontent.com/2743637/104456205-a2da1500-55a8-11eb-8f38-faa987ba95b9.png)

**Comment by nijel** [comment]
This happens on creating component via ZIP upload? I'm not sure if there is proper cleanup, so maybe there are stale files from previous attempts. Can you try changing the component slug?

**Comment by nicolabeghin** [comment]
THAT MADE THE TRICK!!! so it was caching the previous ZIPs. It literally drove me crazy :D

**Comment by nicolabeghin** [comment]
Thanks a lot @nijel!!!

**Comment by nijel** [comment]
I've just added the cleanup to the file upload path.
