### ISSUE TITLE
issue with plural string (Android) for languages with different plural forms

### ISSUE THREAD

**Issue by ruleant** [WeblateOrg/weblate#520]
I noticed something strange related to plural string, but I'm not sure if it is a Weblate issue, or a TTK issue.

Some Asian languages (I noticed it for Chinese and Korean) don't have the grammatical concept of plural as fe. English (one, other), so Android only expects "other", for these languages.

Weblate displays one field in the interface, but puts its content in the "one" item, while "other" is also present in the [xml file](https://github.com/ruleant/getback_gps/commit/224650870c2ca47959d9aa6ff390f63244ee8b4c), but left empty. 
Android expects a value in "other", the value in "one" is ignored, resulting in an empty string when displaying it.
##

**Comment by nijel** [comment]
Has anybody of you seen this bug recently? As I haven't seen any complains in last year, I'd assume it was fixed (probably on the babel/toolkit side as I'm not aware of anything related in Weblate).

**Comment by eighthave** [comment]
We're hitting this issue a lot right now with F-Droid:
https://hosted.weblate.org/projects/f-droid/f-droid/

Exactly as initially described: languages with no plurals (e.g. zh-CN) have the translation string stuck into `<item quantity="one">` and there is a blank other included: `<item quantity="other"/>`.  The Android docs say pretty clearly that in this case, there should only be `<item quantity="other">` and that's where the translation should go:
https://developer.android.com/guide/topics/resources/string-resource.html#Plurals

**Comment by nijel** [comment]
I finally understood when this happens and why it's not always reproducible - it only happens when adding new units to the translation. When changing existing units, this works without problems.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
