### ISSUE TITLE
"Multiple unnamed variables" for Python format source string with one format

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#5207]
**Describe the issue**

`Command '%s' not recognised.` is being flagged with "Multiple unnamed variables"

**To Reproduce the issue**

https://hosted.weblate.org/translate/f-droid/fdroidserver/en/?checksum=391386acdf263ec

**Expected behavior**

No failing check.

**Comment by nijel** [comment]
It's caused by flagging the string both `c-format` and `python-format`. Weblate should detect in such case that the extracted format string is actually same in both cases.
