### ISSUE TITLE
Allow user without translate permission to upload translation files as suggestions

### ISSUE THREAD

**Issue by exzhawk** [WeblateOrg/weblate#5208]
**Is your feature request related to a problem? If so, please describe.**
It's a feature request. My weblate instance works in peer review workflow. Most users only have "suggest" privilege. All suggestions must be approved by users with "translate" privilege. Some users sometimes download language files and use local editors to perform "magic" operations(regexp, personal dict, local testing, etc.) that are not easy on weblate. After edited language files, users with only "suggest" privilege finds it's impossible to upload the processed file as suggestions. Currently, when a user with only "suggest" privilege want to upload translation, they will send files to a privileged user and ask him to upload the file with their Author name and Author e-mail.

**Describe the solution you'd like**
Allow users with only "suggest" privilege to upload translation files as suggestions. They are able to access the upload interface. Of course "Add as suggestion" is the only available option in File upload mode.

**Describe alternatives you've considered**

**Screenshots**

**Additional context**

**Comment by nijel** [comment]
There is dedicated permission for file uploads. Once user has it, the suggestion only upload should work.

**Comment by exzhawk** [comment]
It works well! Didn't notice that, my bad. Thx!
