### ISSUE TITLE
Clicking "comment solved" scrolls to top of window

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5211]
Papercut issue

https://hosted.weblate.org/translate/remmina/remmina/ar/?checksum=5a93e36c2cd293e

Clicking to solve multiple comments makes it apparent that going back and forth from the top of the page down to the comments to do so is tedious.

Try making a comment, and then click the checkmark to solve it.
No scrolling should be done(?).

It could be argued it would make sense for only the last one, but it isn't often there are more than one comment, so better to have it consistently do no scrolling IMO.

**Comment by kathleenjvaldez** [comment]
Hi, is this issue still open?

**Comment by comradekingu** [comment]
@kathleenjvaldez In the very least it still happens on Weblate 4-8-dev, so yes.
