### ISSUE TITLE
Improve keyboard shortcuts documentation

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#5215]
**Is your feature request related to a problem? If so, please describe.**

Right now the documentation for keyboard shortcuts is confusing for some users, especially the sequenced ones - press `Ctrl` and `I`, then `1`. 

**Describe the solution you'd like**

Improve the docs to be easier to understand.

**Screenshots**

![obrazek](https://user-images.githubusercontent.com/212189/104722696-849e2180-572e-11eb-952c-082a303295f0.png)

**Additional context**

See https://docs.weblate.org/en/latest/user/translating.html#keyboard-shortcuts

CC @orangesunny @comradekingu (as you often contribute to the docs).

**Comment by nijel** [comment]
_Original comment by @Fat-Zer at 41c46cdd10d88178949827b8fe7544ec1684ef7b:_

Looks very weird... without `+` it looks like it suggests to use sequential presses rather than simultaneous... i.e. press `Alt`, release it and only then `Home`... especially it's a bit confusing in case of two non-modifier chars like `Ctrl i` `1` etc... when I saw it my thoughts were like: *should it be `C-i` and then `1` in emacs style? or `Ctrl+i+1`? or may be `Ctrl` `i` `1`? can the last one even be handled?...*

I'd personally prefer the ``:kbd:`Alt`+:kbd:`Home` `` (<kbd>Alt</kbd>+<kbd>Home</kbd>) look i.e. separated by plus with each individual key inside its own `<kbd>` tag. IMHO it looks most eye-candy and least confusing.

PS: Looks like the github guys are not settled yet themselves: they use mess of different approaches.
PPS: I was gonna write «ok, I don't care»-style comment, but I've added a «but» after that and couldn't stop myself... after that it didn't looked like one of those anymore =))) So, for the record: in general I don't really care.

**Comment by Oymate** [comment]
I came to suggest keyboard shortcuts and found this. Please consider marketing the shortcuts as a feature more!

**Comment by Oymate** [comment]
The first keyboard shortcut is duplicate though

**Comment by nijel** [comment]
@Oymate I've already fixed this in fd9a9b77c640dea5b4c619574ca6fc27b91db9b5 :-)

**Comment by Oymate** [comment]
Also `Ctrl+?(/)` would be nice for a cheat sheet shortcut :)

**Comment by nijel** [comment]
@Oymate This issue is about improving documentation, please keep comments on topic. See https://github.com/WeblateOrg/weblate/issues/5064 for your topic.
