### ISSUE TITLE
Long regexp monikers not fully shown

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5220]
Papercut

https://hosted.weblate.org/translate/ejabberd/ejabberd/nb_NO/?q=state%3A%3Ctranslated+AND+NOT+has%3Asuggestion&sort_by=-priority%2Cposition

at 50% scaling on 1600px horizontal res (x2560)
![bilde](https://user-images.githubusercontent.com/13802408/104807627-95a76b00-57e0-11eb-8ada-2104d22fd785.png)

"works" at 70% on 2160px horizontal res (x3840) ![bilde](https://user-images.githubusercontent.com/13802408/104807738-5fb6b680-57e1-11eb-94d8-75a8d1b2d8cc.png)

>state:<translated AND NOT has:suggestion

is not included in full, and more of the combinations fail in other languages.

(same in regular editor)

Would be nice if they spanned to available space.

"Position and priority" could be aligned rightwards to make it appear in an expected place each time.

Showing the full second element is great to familiarize people with the searching-logic, and having the full bar there makes it easy to adapt/do custom searches.

**Comment by nijel** [comment]
Yes, that part needs to be switched to flexbox, with current layout it is probably not possible.
