### ISSUE TITLE
Not "unlock "notification

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#5226]
**Describe the issue**

1. I receive a notification "New strings to translate" after a translation update
2. I click on the link and the translation is in "Lock" state
=> everything is OK

3. I click on the option "Warn me when translation will be unlocked" => see screen shot (in french) ; I get Weblate info "notification updated"
4. I never receive any mail, like if the translation is never unlocked which is wrong...
![Notification when Unlocked](https://user-images.githubusercontent.com/1452146/104920572-4146eb80-5998-11eb-9a65-9abcc9179790.png)

**To Reproduce the issue**

See https://hosted.weblate.org/translate/osmand/main/fr/?q=is:untranslated ; try to activate the "unlock notification" ... you may not receive any mail.

**Expected behavior**

Be warned when translation is unlocked.

**Screenshots**
See above.

**Server configuration**
Hosted Weblate

**Additional context**
This "unlock" notification feature had never worked for me.

**Comment by ldmpub** [comment]
Hi,

First "unlock notification" received => I confirm this issue is closed. Thanks 👍

I wonder if you consider as normal the fact that if you go back top page while Component is locked and you already have request to be automaticaly warned when unlock => the button "Notify me when unlock" is always displayed / available? May I fill a bug or an improvment or nothing for this particular "case"? (I already "pushed the button" but button is still displayed).

**Comment by nijel** [comment]
Yes, the button is always displayed to make the code simpler. Feel free to open a separate issue for that, though.
