### ISSUE TITLE
Removal documentation

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#5235]
Removing language, component, or project is easy thing to do, but some users would like to have a description of it in the docs. Would you be kind @comradekingu and write some lines about it?

**Comment by comradekingu** [comment]
@orangesunny Will do. Bit busy today, but maybe towards the evening.
Should it be after https://docs.weblate.org/en/latest/admin/projects.html#adding-translation-projects-and-components
or its own page?

**Comment by orangesunny** [comment]
Thanks. Don’t hurry, it doesn’t have to be today.

> Should it be after https://docs.weblate.org/en/latest/admin/projects.html#adding-translation-projects-and-components

this seems like a good place.

removing the translation should be a new paragraph probably here: https://docs.weblate.org/en/latest/devel/translations.html?highlight=start#adding-new-translations

Basically, there should be a search hit for *delete* and *remove* for all the levels so the wandering users will find the right docs section.
