### ISSUE TITLE
Consolidate LTR/RTL button to a single button

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#5245]
Having 2 different buttons is redundant since there are only 2 options.
I thought about having a single button, when pushed it will be RTL (default for RTL languages) and LTR in normal mode (or the other way around, have it your way).

Thanks!

**Comment by fitojb** [comment]
I like the current two-state switch design, as it makes it obvious which state is on at one time, and doesn’t create a false hierarchy between both modes (i.e., that RTL is something “extra” that you “turn on” over the “normal” LTR mode. Note the quotation marks)

**Comment by yarons** [comment]
Or maybe it can have a small green icon that will be lit when pushed.

My main problem is screen space as you can see from the screenshot, it's pretty crowded when using a mobile phone for translation.

**Comment by fitojb** [comment]
Maybe this control can be positioned underneath the edit area, so that it doesn’t take additional space from the “virtual keyboard” row of special characters?

**Comment by comradekingu** [comment]
We LTR-ers don't have this, but I am all about saving on the visuals

![bilde](https://user-images.githubusercontent.com/13802408/105647448-0c5dfb80-5ea6-11eb-99ab-be8d52e4f601.png)

is what it looks like.
How about removing both and just clicking the lower left or right corner ala

![bilde](https://user-images.githubusercontent.com/13802408/105647534-b5a4f180-5ea6-11eb-976e-80912e57aed1.png)

**Comment by yarons** [comment]
@comradekingu Too obscure and I also think that this symbol is handled automagically by the browser so you can either show or hide it but nothing further.

**Comment by nijel** [comment]
Yes, the resize handle is rendered by the browser and I don't think you can easily handle events on that. Besides that, nobody would figure out this himself besides when randomly clicking there - it has not indication of being clickable and doing some action.

The current placement was intentionally chosen to be next to the other direction controls, but it could be certainly moved under the textarea in case that makes sense for you.

**Comment by fitojb** [comment]
Yep, I think moving the control below the textarea is a good solution, but I think it should remain as a two-button switch for the reasons I stated above.
