### ISSUE TITLE
Move billing overview into project addition

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5262]
![bilde](https://user-images.githubusercontent.com/13802408/105647744-0537ed00-5ea8-11eb-834e-1811bab696c3.png)

This is ~Billing overview or somesuch,

In my head that belongs with ~Buy new hosting plan over in

![bilde](https://user-images.githubusercontent.com/13802408/105647793-43351100-5ea8-11eb-9993-806efe288e85.png)

no?

**Comment by nijel** [comment]
That's not about adding new billing, but to manage existing ones.

For most users this will just redirect to the only billing they have, for others it displays a list of them without an option to add a new one, so why it should be in the add menu?
