### ISSUE TITLE
Need help to upgrade production weblate instance

### ISSUE THREAD

**Issue by bharathbotla** [WeblateOrg/weblate#5264]
We are currently using weblate 3.1.1 , want to upgrade it  to the latest version and need help throughout the process.
Url :https://fsmisc3.go.johnsoncontrols.com/
It is on-premises instance 
I have gone through documents but not getting step by step process, apart from that i need to create replica of our production instance to test instance to check upgrade on that.

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [ ] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

2. Scroll down to '....'
3. Click on '....'

**Expected behavior**

**Screenshots**

**Exception traceback**

**Server configuration and status**

Weblate installation: weblate.org service / Docker / PyPI / other

**Weblate deploy checks**

**Additional context**

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/upgrade.html

PS: It's not a good practice to write to all channels you can find to ask a question.

**Comment by orangesunny** [comment]
Hello @bharathbotla,

Last week, I offered you assistance, replying to all of your three different gmail.com addresses you wrote to us from with the same question. As you also signed up to GitHub now, to ask the same question, I am pasting my reply here, too:

> 
> The upgrade process is described for both native and Docker installations in the Weblate documentation: https://docs.weblate.org/en/latest/admin/upgrade.html
> 
> Specifics for 3.x versions are noted here: https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-3-x

You replied that you don’t understand the documentation, but you didn’t tell which part. So this was my second reply:

> Bharath,
> I am sorry to hear that. Whatever I would tell you would be the similar things as are in the documentation. It is pretty useful, straight forward, and includes all things needed for the upgrade. If you don’t understand it, it is better to let someone who understands do the upgrade.
> 
> If you want us to do it, we offer paid consultations or a support package that covers the regular updates of the installations we set up for our customers. So if you want us to do the upgrade, please choose the solution at https://weblate.org/support/. Once you buy the support, we only need SSH access to your server to perform the upgrade.

You can tell us which part of the documentation of the migration process seems tricky for you.
