### ISSUE TITLE
Ability to update the source information labels via the API

### ISSUE THREAD

**Issue by lacroixdavid1** [WeblateOrg/weblate#5275]
**Is your feature request related to a problem? If so, please describe.**

We are sharing the same dictionary source for 3 different applications. We would like to easily distinguish in Weblate what application(s) a key appears in. Labels would be perfect but I haven't seen any API documentation regarding them. Am I missing something?

**Describe the solution you'd like**

Have the ability to update the source information labels via the API.

**Comment by lacroixdavid1** [comment]
I'm asking this because we intend to translate only 1 of the 3 UIs our customers have access to. 

Since a lot of keys are shared among the UIs, we decided when designing our i18n to have a single translation component in Weblate to maintain instead of 3. 

I've noticed that the following paths `[PUT|PATCH] api/units/:pk/` supports updating the `explanation` field, but then I can't do anything since both the Bulk Edit addon and the Search feature returns me this errors message when trying to search in the `explanation` field: 

```
Error in parameter q: Failed to parse query string: Unsupported field: explanation
```

@nijel sorry to bother you but, do I absolutely need to split my component into 3 distinct components (one per UI) or there's a workaround to this? 

Thanks in advance, Weblate is an amazing tool.

**Comment by nijel** [comment]
I've added searching for explanation in f4a2d00be2c25f7c427811f319ec2964bd024943.

Please keep the issue single-topic next time, requesting another features inside the existing ticket will make it hard to track in case it would not be implemented immediately.

**Comment by burner1024** [comment]
I second the request for label API.
