### ISSUE TITLE
Sort list of followed projects (and dropdown) by newest first.

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5277]
Papercut

Makes sense with no scrolling too, but

Finding new projects for translation is currently not one of the e-mail alert fields, so the best way to find new projects is to look in the available project list. Since it is quite long, and there are new projects nearly every day, scrolling to the bottom of it (and to the bottom of the project dropdown to find them) is a bit tedious.

![bilde](https://user-images.githubusercontent.com/13802408/105913053-989a2b00-602c-11eb-8246-77fe1f821046.png)

To me it makes sense the most interesting projects having seen the least attention, and thus requiring the most amount of work could rather be sorted to the top.

If the main project is added first, I still think it evens out effort a bit better than giving newer/less important projects less prominent placing.

![bilde](https://user-images.githubusercontent.com/13802408/105913458-26761600-602d-11eb-82bd-9fe26815c9ae.png)
Not really sure what the sorting is based on here. Would prefer if it was the same in both places.

Older projects more likely to be dormant and "finished"?

**Comment by nijel** [comment]
> Finding new projects for translation is currently not one of the e-mail alert fields,

You can subscribe for new components, which is probably more interesting as you do not care about empty projects which do not have any content (yet).

If you want to browse recent projects, you can do it here: https://hosted.weblate.org/changes/?action=50

>  Not really sure what the sorting is based on here. Would prefer if it was the same in both places.

Good point, both locations will be now consistently alphabetically sorted: 1dab162a820234160fc4a3cb715f35c787166f57 and c6af60191d1d2e0e2499fdbb7c42e8d41778a4db
