### ISSUE TITLE
Check for capital letters

### ISSUE THREAD

**Issue by KadAnna** [WeblateOrg/weblate#5281]
**Is your feature request related to a problem? If so, please describe.**

Translators sometimes do not stay consistent with usage of capital letters, e.g. instead of Title Case they use Sentence case. The headings in UI are then inconsistent.

**Describe the solution you'd like**

There is a check, which can recognise if source uses capital letters. There might be a confusion for German which uses capital leters for nouns.

**Comment by nijel** [comment]
The tricky thing here is that this differs per language. In English headings are supposed to use title case, but not in Czech. I'm not sure what is more common approach among other languages.

Quickly looking up French, they have more complicated rules for this, see https://github.com/benoitvallon/titlecase-french

Anyway this needs more linguistic information to implement it properly.

**Comment by comradekingu** [comment]
Double capital letter in a row is more likely to be in error.

**Comment by tjhietala** [comment]
I agree about the double capital, but e.g. function names in LibreOffice are written in ALL CAPS intentionally.

**Comment by comradekingu** [comment]
@tjhietala There is an "ignore-checkname" flag for every other check, so that should be fine.
https://docs.weblate.org/en/latest/admin/checks.html#custom-checks

**Comment by NathanBnm** [comment]
> Quickly looking up French, they have more complicated rules for this

In French title case should be avoided. For example is there is a title "Available Languages" in English, it should be "Langues disponibles" in French. There is an exception for literary works, movie names etc.
