### ISSUE TITLE
Contributor statistics

### ISSUE THREAD

**Issue by wetneb** [WeblateOrg/weblate#5284]
**Is your feature request related to a problem? If so, please describe.**

I would like to reach out to the community of translators of the OpenRefine project. How do I find out who is active in translating the project?

**Describe the solution you'd like**

It would be nice if Weblate could offer some view on who is active in the project, just like GitHub/GitLab show a list of contributors to the project. It could be broken down by language (helping translators get in touch with each other) or global. Contributors could be sorted by number of translations edited, last edit made, length of contribution to the project, or other criteria.
Perhaps that would be a good addition to the "Activity" page:
https://hosted.weblate.org/projects/openrefine/#activity

**Describe alternatives you've considered**

I can try to extract these statistics from the git repository itself but it's a bit harder.

**Additional context**

I want to reach out to the translator community to ask them whether they are interested in translating our new user manual, and if so using which system.

**Comment by nijel** [comment]
Reporting is already there, see https://docs.weblate.org/en/latest/devel/reporting.html, but it's action that has to be triggered manually as it's expensive right now.

For the stats it's already covered by https://github.com/WeblateOrg/weblate/issues/2752

**Comment by wetneb** [comment]
Ah thank you, sorry, I should have found it myself.
