### ISSUE TITLE
Missing translation after completing 100%

### ISSUE THREAD

**Issue by guymass** [WeblateOrg/weblate#5291]
Hello,

We are a group of people who have decided to translate Element messenger to Hebrew for all platforms mainly the mobile app, desktop app and web app. We have completed all translations on Weblate and achieve 100%. Currently we only have seen the mobile being updated with the new translation, however it is missing many translated works and sentences some of which are on main menu. We are sure to have translated those. We do not see the new translation on the other apps but the mobile.

So my questions are:

1. how can we resolve the missing translations for the mobile app?
2. When can we expect to see the new translation for the desktop and web apps?
2. How can we assist to accelerate the process?

Best Regards,

**Comment by guymass** [comment]
Well I asked support and was also asking in the translation Matrix chat group but no real answer so I thought I would ask here as well. Maybe someone knows something. We figured that once we finish the translations it will be updated soon.

**Comment by comradekingu** [comment]
@guymass 
How many strings make it into a release depends on the cutoff date. If it is still a problem by the time next realse maybe it is an issue. Link to the instance in question and I can have a look. I am not an admin for it.

**Comment by guymass** [comment]
These are the URL for the translations we have done:

https://translate.element.io/projects/element-web/element-web/he/

https://translate.element.io/projects/element-android/element-app/he/

https://translate.element.io/projects/element-android/element-store/he/

https://translate.element.io/projects/element-web/matrix-react-sdk/he/

I have now seen this one as well and will also translate it. Can't I simply
copy one translation to another?
https://translate.element.io/projects/element-android/element-sdk/he/

**Comment by guymass** [comment]
Thanks for taking a look this is very confusing. Don't understand why to
use so many files and versions.

**Comment by orangesunny** [comment]
Hi @guymass!

I understand your confusion, but this workflow cannot be changed by the Weblate team here. It‘s all up to the Element folks as they run and manage the instance themselves with no support from us. Please contact them directly (I assume you tried their support already), seems that translation propagation would help here :) https://docs.weblate.org/en/latest/admin/continuous.html?highlight=propagation#translation-propagation
