### ISSUE TITLE
AWS Autotranslate not working for certain languages

### ISSUE THREAD

**Issue by panbanda** [WeblateOrg/weblate#5299]
I have tried to use autotranslate for Hindi, Swahili, Chinese, and Portuguese.  Chinese and Portuguese work great but when I run the autotranslate tool from the UI or from CLI I get successful messages but no translated strings.

The response I get from the UI in the inspector is:

```json
{"completed":true,"progress":100,"result":{"translation":237,"message":"Automatic translation completed, no strings were updated."},"log":"dashboard/general/hi: starting automatic translation f597b716-eea9-45b9-9586-46bee81931a1\ndashboard/general/hi: completed automatic translation"}
```

The response I get in the API is:

```json
{
  "detail": "Failed to process autotranslation data!"
}
```

I used the following for both UI and API requests:

```json
{
	"mode": "fuzzy",
	"filter_type": "nottranslated",
	"auto_source": "mt",
	"engines": "aws",
	"threshold": "80"
}
```

I tried translating the strings in AWS translate and it works fine, even in the API it works fine (with the IAM user weblate is setup to use).  When I run `docker-compose logs` it shows just as seen above in the UI response payload (started, completed).   I have also tried lowering the threshold to `1` to see if it was just ignoring it.

I can't see the "Machine translation recommendation" when looking at translation strings in this language either.

I am running the latest docker-compose version as of January 31st 2021.

Describe the steps you tried to solve the problem yourself.

- [ x ] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

1. Setup english + hindi
2. Set english as the source language
3. Use the autotranslate for AWS translate
4. Run the Tool -> autotranslate with the above configuration

**Expected behavior**

Translates the untranslated strings

 * Weblate: 4.4.2
 * Django: 3.1.5
 * siphashc: 2.1
 * Whoosh: 2.7.4
 * translate-toolkit: 3.3.0
 * lxml: 4.6.2
 * Pillow: 8.1.0
 * bleach: 3.2.1
 * python-dateutil: 2.8.1
 * social-auth-core: 4.0.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.10.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.2
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 5.0.5
 * kombu: 5.0.2
 * translation-finder: 2.7
 * weblate-language-data: 2020.13
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.25.1
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.19.5
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.12
 * borgbackup: 1.1.15
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.6
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.16.54
 * zeep: 4.0.0
 * aeidon: 1.9
 * iniparse: 0.5
 * mysqlclient: 2.0.3
 * Mercurial: 5.6.1
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * Redis server: 6.0.10
 * PostgreSQL server: 11.8
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: email-smtp.us-east-1.amazonaws.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.15.0-1021-aws (x86_64)

**Weblate deploy checks**

WARNINGS:
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.4.2/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.4.2/admin/backup.html

**Comment by panbanda** [comment]
Ah this is great thanks!  Any thoughts on when this will be available in the docker compose version?

**Comment by nijel** [comment]
It will be part of the 4.5 release currently scheduled on mid-February.
