### ISSUE TITLE
"other occurences" need additional improvements

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#5309]
**Is your feature request related to a problem? If so, please describe.**

By limiting the number of displayed results to 20 in the "Other occurrences" tab, strings load quickly, you no longer have to wait a few minutes when there are a lot of results.
Unfortunately, when limited to 20 results, it often fails to display strings with the same source and context. In this case, the button "show strings with the same source and context" would be very useful to trigger a full search.
Prior to being limited to 20 results, the long search had a false impression that Weblate had crashed or lost connection to the server. If the user clicks the "show strings with the same source and context" button, he will be aware that the search operation is in progress.

**Comment by nijel** [comment]
I don't think that introducing an additional button for this is a way to go. Loading strings with matching context and source first should be the way to go.
