### ISSUE TITLE
AttributeError at /admin/weblate_auth/group/73/change/

### ISSUE THREAD

**Issue by tgriepentrogPATH** [WeblateOrg/weblate#5324]
I want to create a authentication group for external translators (e.g. hungarian translation).

The settings are the following:
Roles: Translate
Project Selection: "From component list"
Projects: none selected
Components: none selected
Component lists: My specified component list
Language selection: As defined
Languages: Hungarian

When I hit the "SAVE" Button, the following error appears:
AttributeError at /admin/weblate_auth/group/73/change/
'Group' object has no attribute 'componentlist'
Request Method:	POST
Request URL:	http://OUR_SERVER/admin/weblate_auth/group/73/change/
Django Version:	3.0.6
Exception Type:	AttributeError
Exception Value:	
'Group' object has no attribute 'componentlist'
Exception Location:	/INSTALL_PATH/python3.7/site-packages/weblate/auth/models.py in save, line 177
Python Executable:	/usr/bin/python3
Python Version:	3.7.3
Python Path:	
['/INSTALL_PATH/python3.7/site-packages/git/ext/gitdb',
 '/',
 '/INSTALL_PATH/python37.zip',
 '/INSTALL_PATH/python3.7',
 '/INSTALL_PATH/python3.7/lib-dynload',
 '/usr/lib/python3.7',
 '/INSTALL_PATH/python3.7/site-packages',
 '/INSTALL_PATH/python3.7/site-packages/gitdb/ext/smmap']

Any suggestions how to solve the issue?

**Comment by tgriepentrogPATH** [comment]
Thank you for fixing it.

I updated my local file to your change and now I run into another error. :(

'ManyRelatedManager' object is not iterable
Request Method: POST
Request URL: http://OUR_SERVER/admin/weblate_auth/group/73/change/
Django Version: 3.0.6
Exception Type: TypeError
Exception Value: 'ManyRelatedManager' object is not iterable
Exception Location: /INSTALL_PATH/python3.7/site-packages/django/db/models/fields/related_lookups.py in get_prep_lookup, line 50

Is this the correct place to post it?

**Comment by nijel** [comment]
Sorry, there is another bug in that, should be fixed in 6385ba6ce4a6eaf8d92fa0bccb65f28987096e3e

**Comment by tgriepentrogPATH** [comment]
Thank you.
It's working now.
