### ISSUE TITLE
 create a new translation button is not working

### ISSUE THREAD

**Issue by Stilian-ops** [WeblateOrg/weblate#5329]
I don't know what just happened

**Comment by ianathompson** [comment]
Is it enabled for your user?
Is it enabled for that component?
![image](https://user-images.githubusercontent.com/6380484/106855570-17135e80-66f8-11eb-9c98-2c8b2ca98d96.png)

**Comment by nijel** [comment]
Also see https://docs.weblate.org/en/latest/devel/translations.html#adding-translation
