### ISSUE TITLE
Addon: Squash Git commits - ignores custom commit messages

### ISSUE THREAD

**Issue by spacecowboy** [WeblateOrg/weblate#5337]
**Describe the issue**

When enabling git squashing per author, the squashed commit's title is the default weblate commit message. Full commit is as follows:

```
Translated using Weblate (Russian)

Currently translated at 2.7% (2 of 73 strings)

Updated Russian translation using Weblate

Currently translated at 95.9% (94 of 98 strings)
Co-authored-by: Nikita Epifanov's avatarNikita Epifanov <nikgreens@protonmail.com>
Translate-URL: https://hosted.weblate.org/projects/feeder/android-strings/ru/
Translate-URL: https://hosted.weblate.org/projects/feeder/fastlane/ru/
Translation: Feeder/Android strings
Translation: Feeder/F-Droid and Play Store metadata
```

Note that the title of the commit is

> Translated using Weblate (Russian)

Where as the title of the squashed commit inside the body uses the template that I have configured:

> Updated Russian translation using Weblate

**I already tried**

Describe the steps you tried to solve the problem yourself.

- I've looked in the settings and the Squash Git Commits addon suggests that the commits should simply be squashed
- The addon has a commit message box you can fill in - but it is not at all clear if this message supports template variables.

**To Reproduce the issue**

1. Enable the Squash Git Commits addon
2. Enable per-author
3. Enable append trailers to squashed commits
4. Set a custom commit message for `Commit message when translating` in the project
5. See incorrect title of squashed commit

**Expected behavior**

The commit message should look like this (note first row difference):

```
Updated Russian translation using Weblate

Currently translated at 2.7% (2 of 73 strings)

Updated Russian translation using Weblate

Currently translated at 95.9% (94 of 98 strings)
Co-authored-by: Nikita Epifanov's avatarNikita Epifanov <nikgreens@protonmail.com>
Translate-URL: https://hosted.weblate.org/projects/feeder/android-strings/ru/
Translate-URL: https://hosted.weblate.org/projects/feeder/fastlane/ru/
Translation: Feeder/Android strings
Translation: Feeder/F-Droid and Play Store metadata
```

**Comment by nijel** [comment]
Looking at the code it is indeed ignored with "Append trailers to squashed commit message" turned on.
