### ISSUE TITLE
Translation of items with no string value

### ISSUE THREAD

**Issue by RoosPM65** [WeblateOrg/weblate#5344]
https://translations.documentfoundation.org/translate/libo_ui-master/sfx2messages/af/?q=state:%3Ctranslated  
Hi, there are 6 strings to be translated but they are empty template names. The first two indicates that they would be default templates, so I gave them names numbered 1 and 2. The last 4 (see URL) are simply template names, but they are blank? What should we do?

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

2. Scroll down to '....'
3. Click on '....'

**Expected behavior**

**Screenshots**

**Exception traceback**

**Server configuration and status**

Weblate installation: weblate.org service / Docker / PyPI / other

**Weblate deploy checks**

**Additional context**

**Comment by nijel** [comment]
That Weblate instance is operated by LibreOffice, so better reach them.

Anyway if you click on the "Source string location" in the right sidebar, you can see that this is really defined as an empty string: https://git.libreoffice.org/core/+/master/include/sfx2/strings.hrc#307

**Comment by fitojb** [comment]
That sounds like a bug @HeikoTietze

**Comment by HeikoTietze** [comment]
Reviewers have requested some fine-tuning at https://gerrit.libreoffice.org/c/core/+/110074. Once this is done we get new strings. Might have been a bad idea to split the work into removal and addition, sorry for the noise.
