### ISSUE TITLE
Inconsistency check failed even tough there is no inconsistency

### ISSUE THREAD

**Issue by slsimic** [WeblateOrg/weblate#5351]
Inconsistency check failed even tough there is no inconsistency

Translations are updated by uploading translations file. 47 inconsistencies
As seen on the screenshot both components have same translations and there is nothing under Difference to current string
![inconsistency](https://user-images.githubusercontent.com/12166655/107035883-15f63600-67b9-11eb-82ac-3eab381f36a2.png)

**Comment by nijel** [comment]
Can you please include the link to the affected string so that I don't have to search for it? Thanks :-)

**Comment by slsimic** [comment]
Sorry.
https://hosted.weblate.org/translate/weblate/hosted/sr_Latn/?q=check:inconsistent
and all 46 fail checks are same

My guess is that when I uploaded first file, inconsistency flags are risen because same strings in other component had no translations. But when I uploaded second file, flags are not removed in the first one. Maybe will be later, if some periodical Checks are performed.

**Comment by nijel** [comment]
It should not happen. 

What might be related is I've updated some PO files at the same time and that have triggered an update of the checks as well. As there is no locking for this, things might have gone wrong in unfortunate timing.

**Comment by slsimic** [comment]
Should I just Dismiss them manually? Is there a "bulk" way of doing that?

**Comment by nijel** [comment]
They should eventually disappear, but if you are annoyed by them, you can dismiss them right now.

**Comment by slsimic** [comment]
Let them rest until monday. :-)
