### ISSUE TITLE
if the translation is 100%, the status display is incorrect.

### ISSUE THREAD

**Issue by baffclan** [WeblateOrg/weblate#5363]
**Describe the issue**
if the translation is 100%, the status display is incorrect.

**To Reproduce the issue**

1. Open translation page 
   (e.g. https://hosted.weblate.org/projects/weblate/glossary/ja/)

2. Strings status is
 > 31 All strings — 40 words
 > 31 Translated strings — 40 words
 > 31 Strings needing action without suggestions — 40 words 

3. Click a "Strings needing action without suggestions — 40 words",
 > weblate said: "No string matched your search!".

**Expected behavior**

"Strings needing action without suggestions" is not displayed. 

**Additional context**
Weblate 4.5-dev

**Comment by baffclan** [comment]
This problem is still reproduced.
weblate-4.4.2-1077-gf0ef7419b7 (20210214)

**Comment by nijel** [comment]
It is fixed in the code, but stats are cached for quite long time if there is no change in the translation, so the wrong numbers will stay in some locations for some time.

**Comment by baffclan** [comment]
Thanks for comments.
I check after a while.
