### ISSUE TITLE
A button to edit glossary term doesn't work

### ISSUE THREAD

**Issue by Fat-Zer** [WeblateOrg/weblate#5367]
**Describe the issue**

On the translation page 
A button to edit glossary term introduced by 9aaeacab256334d0fbdc2390321d171b7d555cea doesn't work. When clicked the text of the term is passed to the translation field

**To Reproduce the issue**

1. Go to any translation page which displays some glossary terms
2. Click on the button with the term near the term
3. See that text of the term is passed

**Expected behavior**

A redirection to the glossary page.

**Server configuration and status**

Weblate installation: weblate.org service

**Comment by nijel** [comment]
This is now the glossary page, it just looks nearly the same as a translation page ;-).

**Comment by Fat-Zer** [comment]
nijel commented 19 hours ago

> This is now the glossary page, it just looks nearly the same as a translation page ;-).

???

I'm talking about those buttons with pen icon beside glossary terms:

![scr27](https://user-images.githubusercontent.com/1060057/107317101-0cb3e480-6aab-11eb-8c8b-715e6803a8aa.png)

See the referred commit...

**Comment by nijel** [comment]
Sorry, I didn't properly read the initial comment. I confirm the bug now.
