### ISSUE TITLE
Weblate Docker - how to set LIMIT_TRANSLATION_LENGTH_BY_SOURCE_LENGTH ?

### ISSUE THREAD

**Issue by ReneBoehm** [WeblateOrg/weblate#5374]
We are using the official Weblate 4.4.2 docker container and need to disable this setting. It seems it will be ignored when set in the environment file. With a quick look at https://github.com/WeblateOrg/weblate/blob/master/weblate/settings_docker.py it seems that no environment variable isn't cosidered but it's set to a fixed "true" instead.

Is there a chance to change this setting in den weblate docker environment ?

best regards,
René

**Comment by nijel** [comment]
Yes, it is possible: https://docs.weblate.org/en/latest/admin/install/docker.html#further-configuration-customization

**Comment by ReneBoehm** [comment]
Thank you. That's what I thought about as plan B ;) Mount a custom config file...
