### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getlanguageNode'

### ISSUE THREAD

**Issue by northantech** [WeblateOrg/weblate#5379]
**Describe the issue**

Commit fails and throws AttributeError, 'NoneType' object has no attribute 'getlanguageNode'

**Server configuration and status**

Returned message is:

Request Method: | POST
-- | --
http://website/commit/project/component/en_US/
3.1.4
AttributeError
'NoneType' object has no attribute 'getlanguageNode'
/root/weblate-env/lib/python3.6/site-packages/weblate/formats/ttkit.py, line 537, in xliff_node
/root/weblate-env/bin/python
3.6.8
['/root',  '/root/weblate-env/lib/python3.6/site-packages/git/ext/gitdb',  '/root/weblate-env/bin',  '/usr/lib64/python36.zip',  '/usr/lib64/python3.6',  '/usr/lib64/python3.6/lib-dynload',  '/root/weblate-env/lib64/python3.6/site-packages',  '/root/weblate-env/lib/python3.6/site-packages',  '/root/weblate-env/lib/python3.6/site-packages/gitdb/ext/smmap']

**Comment by nijel** [comment]
I believe this issue has been already fixed because we have seen similar one on our servers.

In case it won't be fixed with the 4.5 release for you, please open new report including full traceback and version information so that we can take a deeper look.
