### ISSUE TITLE
"Commented" action missing

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5380]
I noticed https://hosted.weblate.org/user/66611265/#changes has a lot of comments and translations, but they are nowhere to be found.

There isn't a field for "comment made" or similar in https://hosted.weblate.org/changes/?user=66611265

**Comment by nijel** [comment]
You don't have permission to access the project where he has commented...

**Comment by comradekingu** [comment]
Right, but there is no "has commented" for https://hosted.weblate.org/changes/?user=kingu or https://hosted.weblate.org/changes/?user=nijel either. Am I missing it?

**Comment by nijel** [comment]
Yes, you are missing it: https://hosted.weblate.org/changes/?user=kingu&project=&lang=&action=3&user=kingu

**Comment by comradekingu** [comment]
Was "merknad" instead of "kommentar" in nb_NO for some reason. Turns out I fixed that https://hosted.weblate.org/translate/weblate/application/nb_NO/?checksum=3d4885d7584ec35c

What a user dumb report this turned out to be :)
