### ISSUE TITLE
Email address of Hosted Weblate push user on Bitbucket

### ISSUE THREAD

**Issue by jzskca** [WeblateOrg/weblate#5381]
According to the documentation:

> For Hosted Weblate there is a dedicated push user registered on GitHub, Bitbucket, Codeberg and GitLab (with the username weblate named Weblate push user).

However, on Bitbucket users can only be added by email address. What's the email address of the `weblate` user on Bitbucket?

**Comment by nijel** [comment]
It's `hosted@weblate.org`, it did used to work with username only...
