### ISSUE TITLE
Check deploy taking several hours when a lot of components in place

### ISSUE THREAD

**Issue by adriandiazgar** [WeblateOrg/weblate#5382]
**Describe the issue**

When a new weblate version release happens and there are a lot of components with a lot of translations in place already, weblate takes hours to start.

In https://github.com/WeblateOrg/docker/blob/0de63022d310936d46eeb0aff1596b16b1320b47/etc/supervisor/supervisord.conf#L45
the check command executes some checks before starting up.

Including the conflictive check `check_perm` from https://github.com/WeblateOrg/weblate/blob/3a064cc86dbf3ff0b5600d218791f948f563ad0f/weblate/utils/checks.py#L403

Which will traverse the entire directory tree including `.git` folders.

**To Reproduce the issue**

1. Load webalte with a ton of translations with a lot or projects and components, we have like 15 projects, some of them with 10k+ components inside, where some components have 13k+ units.
6. Execute the check command

**Expected behavior**

Weblate should start in minutes if not seconds.

**Server configuration and status**
```
 * Weblate: 4.3.2
 * Django: 3.1.3
 * siphashc: 2.1
 * Whoosh: 2.7.4
 * translate-toolkit: 3.2.0
 * lxml: 4.6.1
 * Pillow: 8.0.1
 * bleach: 3.2.1
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.1
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.5
 * weblate-language-data: 2020.11
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.19.2
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.11
 * borgbackup: 1.1.14
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.6
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.16.12
 * zeep: 4.0.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.1
 * Mercurial: 5.6
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * Redis server: 3.0.6
 * PostgreSQL server: 11.10
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: REDACTED
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: REDACTED, REDACTED, regular
 * Platform: Linux 4.15.0-123-generic (x86_64)
```

**Weblate deploy checks**

This took several hours

```
weblate@weblate-production-app-7bffffdfcf-2z4bf:/app$ weblate check --deploy
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E034) The Celery process is outdated or misconfigured. Following items differ: vcs
	HINT: https://docs.weblate.org/en/weblate-4.3.2/admin/install.html#celery

WARNINGS:
?: (security.W019) You have 'django.middleware.clickjacking.XFrameOptionsMiddleware' in your MIDDLEWARE, but X_FRAME_OPTIONS is not set to 'DENY'. Unless there is a good reason for your site to serve other parts of itself in a frame, you should change it to 'DENY'.

INFOS:
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.3.2/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 4.4.2.
	HINT: https://docs.weblate.org/en/weblate-4.3.2/admin/upgrade.html

System check identified 4 issues (1 silenced).
```

**Additional context**

Company, YouGov

**Comment by nijel** [comment]
The deploy checks should be executed in parallel to other things, so it's not supposed to block startup.

The motivation behind this is that people often do manual changes on the Weblate data and end up being surprised that something doesn't work then. This check detects it.

The Python implementation seems quite efficient. It should be same as `find $DATA_DIR -not -user weblate`, does that one take hours for you as well?

**Comment by dgarana** [comment]
It's taking 1 hour on the best scenario:
```
    real 71m21.469s
    user 0m20.405s
    sys 0m57.182s
```
