### ISSUE TITLE
Make Language Consistency compatible with new glossary

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#5383]
**Is your feature request related to a problem? If so, please describe.**

Community localization checklist started suggesting *Language Consistency* addon with the new glossary approach introduced in 4.5 to all projects, even to those with only one component (two with Glossary now).

**Describe the solution you'd like**

- [x] investigate the interoperability between the addon and new Glossary features
- [ ] polish the docs if needed https://docs.weblate.org/en/latest/admin/addons.html#language-consistency
- [x] probably don’t suggest the addon to projects with only one component besides Glossary

**Comment by nijel** [comment]
The addon would do no harm to the glossary (the glossary is automatically available in all project languages anyway). It just should not be suggested in this case.
