### ISSUE TITLE
Weblate fails to read monolinguistic base file?

### ISSUE THREAD

**Issue by spacecowboy** [WeblateOrg/weblate#5389]
**Describe the issue**

I've added another component to my project to point a specific Play store metadata file:

https://hosted.weblate.org/projects/feeder/f-droid-and-play-store-short-description/

But it seems like weblate is failing to parse the english base file - and all other languages appear as blank with no strings available.

The base file is this one:

https://gitlab.com/spacecowboy/Feeder/-/blob/master/fastlane/metadata/android/en-US/short_description.txt

I am using the exact same configuration for another metadata component pointing at the `full_description.txt` and that is working fine.

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

1. Create a component pointing at a fastlane android short_description file (being a single line of text with no ending newline)
2. Set filetype as HTML because there is no plaintext option
3. Include several translations
4. Note that weblate fails to parse the english base file

**Expected behavior**

A single string should be detected with regular translation options possible

**Screenshots**

Full component configuration:

![image](https://user-images.githubusercontent.com/223655/107419406-0c9dfe00-6b18-11eb-901b-60156a6f6765.png)

Result where no strings are detected:

![image](https://user-images.githubusercontent.com/223655/107419777-774f3980-6b18-11eb-9241-65f9c0654817.png)

**Additional notes**

I am aware of the option to expose the full fastlane metadata as a single component and I started with that - but I don't want to expose changelogs for translation or the title.

**Comment by nijel** [comment]
I've changed the component configuration to [App store metadata files](https://docs.weblate.org/en/latest/formats.html#app-store-metadata-files), that should do the trick.

**Comment by spacecowboy** [comment]
@nijel incorrect. I do NOT want all files to be exposed as I explained last in my message because 

* I don't want the changelogs `fastlane/metadata/android/*/changelogs/*` to be translateable
* I don't want title `fastlane/metadata/android/*/title.txt` to be translateable

I really only want the specific file to be shown.

**Comment by nijel** [comment]
Sorry, there is no plain text translation support in Weblate right now. You can mark the string you don't want to translate as read-only.

**Comment by spacecowboy** [comment]
Everytime I make a release - a new changelog files is created. That would require me to login and manually mark this as read-only for every release.

Why does the full_description work? That is also a single txt file - however containing actual html

**Comment by spacecowboy** [comment]
FYI - found a workaround it seems. Setting the file-format as YAML allowed it to be parsed

**Comment by nijel** [comment]
> Why does the full_description work? That is also a single txt file - however containing actual html

The HTML format extracts content of the HTML tags, in case there are none it does not extract anything.

> That would require me to login and manually mark this as read-only for every release.

No, that just needs you to configure an addon once to that automatically: https://docs.weblate.org/en/latest/admin/addons.html#bulk-edit

> Setting the file-format as YAML allowed it to be parsed

...until somebody puts quotes or other char which need to be handled specially in YAML.

**Comment by spacecowboy** [comment]
Ah, that sounds pretty much what I'd like to do.

Thanks for your help. I'll go ahead and close this now then.
