### ISSUE TITLE
Clickable fields in search results

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5400]
https://hosted.weblate.org/languages/nb_NO/collabora-online/search/?offset=1&q=connectors&sort_by=-priority%2Cposition&checksum=
![bilde](https://user-images.githubusercontent.com/13802408/107621522-acfa3c80-6c56-11eb-86f0-176e70d24581.png)
so it can be
![bilde](https://user-images.githubusercontent.com/13802408/107621832-28f48480-6c57-11eb-8fd7-60d124386ad3.png)
vs the current
![bilde](https://user-images.githubusercontent.com/13802408/107621882-3c075480-6c57-11eb-9c57-986608be9587.png)

That way it would work like https://hosted.weblate.org/translate/collabora-online/ui/en/?checksum=a3c838a1751a542d

Does anyone know what a connector is btw?

Edit: Even re-iterating the placement every time it easily fits twice

![bilde](https://user-images.githubusercontent.com/13802408/107622575-55f56700-6c58-11eb-9f44-9b4fdc04d972.png)

So I don't think adding lines is the solution, but rather it doesn't do anything other than confusing the UI between views.

**Comment by comradekingu** [comment]
It would maybe be clearer if the mouseover colour highlighted just part of the link.

**Comment by nijel** [comment]
Fixed by 27143a1b14d0025e42f0903c299bc01fd94f813f.
