### ISSUE TITLE
How to change Email notification duration in weblate

### ISSUE THREAD

**Issue by cnavagr** [WeblateOrg/weblate#5401]
Team,

We are receiving email notification as an admin related to 'merge failure' and 'push fail error' after every 10 minutes.
We struggled to find out settings where we can change this duration of receiving mails to after every 2 hours or so.
Can you help us to find out from where I can change that frequency/duration of email notification?

Weblate Version: Weblate 3.1.1

Thank You.

Regards,
Rakesh 

Not found any option in settings.py file also.

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

2. Scroll down to '....'
3. Click on '....'

**Expected behavior**

**Screenshots**

**Exception traceback**

**Server configuration and status**

Weblate installation: weblate.org service / Docker / PyPI / other

**Weblate deploy checks**

**Additional context**

**Comment by cnavagr** [comment]
![Email notification](https://user-images.githubusercontent.com/53469923/107637584-5a3f7580-6c94-11eb-8269-61c78de1b151.JPG)

**Comment by nijel** [comment]
I've already answered in https://github.com/WeblateOrg/weblate/issues/3054#issuecomment-777343830:  The email is sent for every event in case you have configured immediate sending for this notification in your profile, you can switch to digest mails to get one per day or even less frequent.

> Weblate Version: Weblate 3.1.1

You should start with upgrading, digest notifications were introduced in 3.6.

What you can do besides that:

* Unsubscribe from these notifications
* Fix the merge failure
* Avoid the merge failures, see https://docs.weblate.org/en/latest/admin/continuous.html#avoid-merge-conflicts

**Comment by cnavagr** [comment]
Thanks for quick reply.

Okay so from your comment my understanding is we can't change notification duration / frequency with our current weblate version 3.1.1, (Please correct me If I am wrong).

We have recently taken over as Admin for our instance and still struggling to understand our weblate instance structure and so can not upgrade prod instance immediately.

Alternate option you suggested to unsubscribe from notifications
Here the issue is, users who are getting mails are not even subscribed for notifications but they are assigned admin access for that particular projects so receiving these emails.

Do you suggest any option in this condition, like user having admin access but should not receive emails, while others admins are needed to receive emails (Duration can be less).

**Comment by nijel** [comment]
Sorry, I don't know exactly how things behaved in 3.1.1 release. It was released in July 2018 and many things have changed meanwhile.

With the current subscription system, every user can adjust which notifications are sent and how frequently. Also, notifications for linked components are sent just once (guessing from the number of e-mails this might be an issue for you as well).

We can provide you paid support for your Weblate instance or even host it for you to make sure you are always up to date, see https://weblate.org/hosting/ for options.
