### ISSUE TITLE
Automatically watch projects disabled by default

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#5403]
Automatically watch projects should be turned off by default.  In large projects, it degrades performance terribly.  My project has over 1000 components and it takes a few seconds to observe the project to load the dashboard.  Any new user must be notified that this option is to be disabled.  The same slowdown causes more lists of components to appear in the dashboard.

**Comment by nijel** [comment]
We might add configuration for new users, but for many situations opt-out is the best approach, see #4866

**Comment by tomkolp** [comment]
The performance degradation is related to: #5513
