### ISSUE TITLE
New language (Esperanto) just added claims to have 0 strings

### ISSUE THREAD

**Issue by michelesalvador** [WeblateOrg/weblate#5410]
The Esperanto language has just been added by a contributor, but now it's not possible to go on with the translation.
In fact Esperanto appears incorrectly to have zero strings.
https://hosted.weblate.org/projects/family-gem/app/eo/

**Comment by nijel** [comment]
Already fixed by 57e1b429c7a1cf46312ba64dad940dbb638c29fd, I've just triggered rescan of your project.

**Comment by casimir** [comment]
I just encountered the same situation on the same instance. I hope this help: https://hosted.weblate.org/projects/frigoligo/app-store-metadata/eo/

**Comment by casimir** [comment]
Never mind, a rescan fixed it.

**Comment by nijel** [comment]
Fix has been just deployed to Hosted Weblate.
