### ISSUE TITLE
push branch not respected

### ISSUE THREAD

**Issue by michield** [WeblateOrg/weblate#5416]
I set a clear difference between the pull and push branches

![image](https://user-images.githubusercontent.com/569843/107823950-8cc29e80-6d78-11eb-8ff2-78873d43a505.png)

However, it tried to push to master instead

**Comment by nijel** [comment]
What version do you use? Is that on git? For mercurial the push branch is not supported...

**Comment by michield** [comment]
Version Weblate 4.3.1 using Git(hub)

I think the problem was that I used a branch called "weblate" but that already existed, so Weblate got confused.
I've renamed it to "translations" which didn't exist, and I think it's working correctly now.
