### ISSUE TITLE
Adding a new word to Glossary is very slow

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#5418]
**Describe the issue**

When adding a new glossary term ... pop-up stays displayed a looooonnnng time (while an icon is turning in the background near "Glossary")

**I already tried**

With short words => same issue

Second issue linked: several "Save" in the popup create several entries!

**Steps to reproduce the behavior**

Go to https://hosted.weblate.org
Context: viewed in french glossary while working on Weblate translation projetct.

**Expected behavior**

1. More speed (less checks?)
2. No duplicates creation (prevent several saves from the popup).

Priority:
1. High
2. Low

Good luck for debug / troubleshoot 👍

**Comment by nijel** [comment]
It's a limitation of current implementation - it immediately adds strings to the files and that is slow. There are no checks involved in the glossary. There is a plan to rewrite it to split adding of the strings from saving to the files (similarly like we do with changes to existing strings).

**Comment by ldmpub** [comment]
@nijel => Ok thanks for your clear and quick answer,

In the meanwhile I will use this feature (add new term to glossary) with caution 🤝.

**Comment by ldmpub** [comment]
Thanks Michal 👍.
