### ISSUE TITLE
zh and zh_Hans cannot exist at the same time

### ISSUE THREAD

**Issue by pd4d10** [WeblateOrg/weblate#5427]
**Describe the issue**

> The component contains several translation files mapped to a single language in Weblate. Please fix this by removing one of the translation files.

See https://hosted.weblate.org/projects/git-touch/git-touch/#alerts. Is this by design?

The `zh` locale is necessary for [GitTouch](https://github.com/git-touch/git-touch) because Flutter needs this as a fallback of `zh_Hans`

I searched the past issues and found https://github.com/WeblateOrg/weblate/issues/3471 and https://github.com/WeblateOrg/weblate/issues/4088, which are not caused by the same problem.

**Server configuration and status**

Weblate installation: weblate.org service

**Comment by nijel** [comment]
Are they supposed to differ?

**Comment by pd4d10** [comment]
`zh_Hans` and `zh_Hant` are different. I think `zh` may be the same as one of them (as fallback)

An example:

https://github.com/flutter/gallery/blob/master/lib/l10n/intl_zh.arb
https://github.com/flutter/gallery/blob/master/lib/l10n/intl_zh_CN.arb

**Comment by nijel** [comment]
Yes, `zh` usually means `zh_Hans`. That's why Weblate complains when both are present - it's not useful to duplicate translators work when producing two translations which are supposed to be identical.

**Comment by pd4d10** [comment]
OK. Temporarily solved by excluding these by language filter: `^(?!(zh|nb)$).+$`
