### ISSUE TITLE
Per-language translation workflow setting

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#5447]
**Is your feature request related to a problem? If so, please describe.**

As I understand it, currently Weblate allows setting translation workflow only globally (for all languages at once). In large projects, translation teams for different languages can be quite different in size and have different ideas about optimal workflow.

**Describe the solution you'd like**

Allow setting the translation workflow on a per-language basis.

**Describe alternatives you've considered**

**Screenshots**

**Additional context**

**Comment by nijel** [comment]
I think this really needs some clarification:

* What all from workflow should be configurable? Is it expected to cover reviews, suggestions and auto-acceptance?
* What means per-language? Site-wide per-language settings, or within a project?

**Comment by tjhietala** [comment]
As @sveinki explained,  a workflow with a mandatory review step would be very useful for some language teams and unwanted overhead for others. If there are 100+ languages like on TDF Weblate, some with large and some with very small teams of translators, one-size-fits-all is not really optimal. Instead, if e.g. French team wants to enable reviews but Swedish team doesn't want to, it would be better if Weblate admins can enable or disable that on per-language basis based on what each team thinks is best.

**Comment by tjhietala** [comment]
> * What means per-language? Site-wide per-language settings, or within a project?

For the needs of TDF Weblate specifically, site-wide should probably be enough, because the different projects there are just different versions or components of LibreOffice. Each [language team](https://wiki.documentfoundation.org/Language_Teams) works across versions and components.

However, for this feature to be useful more generally, "within a project" would be better. For example, there isn't really a "Finnish language team" in the same sense on Hosted Weblate, because e.g. the people translating F-Droid don't necessarily communicate with people translating, say, GnuCash. In other words, the projects on Hosted Weblate are (mostly) actually separate projects and need separate governance.

So the question becomes: does this feature need to be useful more generally?

**Comment by comradekingu** [comment]
So maybe users can have a setting to request changes?

I favour an open control panel where anyone can leave suggestions, and admins can make changes.

**Comment by nijel** [comment]
> For the needs of TDF Weblate specifically, site-wide should probably be enough

Let me ask differently: do you prefer site-wide configuration or per-project? Site-wide one would be easier to maintain, while per-project gives more granular control.

The site-wide customization definitely does not make sense for instances shared by many projects such as Hosted Weblate. On the other side, the smaller the project is, the less likely it is it wants to customize workflow per language. So the question is whether there are enough projects that use shared Weblate and want to customize workflow per language.

I see the initial post has been :+1: by @TheLastProject, @eighthave and @m-aciek, so maybe they can give here some input as well so that we can cover reasonable use cases.

**Comment by m-aciek** [comment]
For case of Python docs translations language teams are quite independent, and as we are still trying to figure out landing on Hosted Weblate instance, I think being able to enable reviews at a language level **inside a project** would be likely used at some point in the future. Although it isn't a blocker for day-one of the Python docs/Weblate integration launch.

**Comment by tjhietala** [comment]
> Let me ask differently: do you prefer site-wide configuration or per-project? Site-wide one would be easier to maintain, while per-project gives more granular control.

I have no experience developing nor administering Weblate, so I don't know how much dev or admin complexity "per-project" would add compared to "site-wide". From a translator's point of view (who also translates projects on Hosted Weblate every now and then), I would prefer "per-project".

> The site-wide customization definitely does not make sense for instances shared by many projects such as Hosted Weblate. On the other side, the smaller the project is, the less likely it is it wants to customize workflow per language. So the question is whether there are enough projects that use shared Weblate and want to customize workflow per language.

I agree that for very small projects, the choice of workflow probably doesn't matter that much. But while there aren't giants like LibreOffice on Hosted Weblate, I wouldn't say all of the projects there are exactly small either.

**Comment by eighthave** [comment]
We recently rolled out a Project-wide reviewer setup and it seems to be working 
well enough.  One thing that was confusing is that once we started some 
per-language review teams, it seems that translators for the languages without a 
team lost the ability to mark strings as reviewed.  I don't remember the details 
there.

@linsui has been managing our translation workflow setup, maybe they have some 
more input here.

**Comment by ib** [comment]
Maybe I misunderstood something, but the "Enable reviews" setting for individual languages always follows the "Enable reviews" setting for the project, i.e. it is not possible to not use reviews for the project, but for individual languages. An individual language setting is confirmed with "Settings saved", but isn't actually changed.

**Comment by nijel** [comment]
Yes, reviews need to be turned on for project and then can be disabled for individual languages, see https://docs.weblate.org/en/latest/workflows.html#workflow-customization.

**Comment by ib** [comment]
> Yes, reviews need to be turned on for project and then can be disabled for individual languages

Even that's not possible. The "Enable reviews" setting for individual languages always follows the "Enable reviews" setting for the project, i.e. the project setting always overrides the language setting (on hosted Weblate), even though it says "Settings saved" for the language.

But my question actually is, why can't we have no reviews for the project (to encourage translators) and set reviews for individual languages that are already at 100% and quality checked?

**Comment by nijel** [comment]
> > Yes, reviews need to be turned on for project and then can be disabled for individual languages
> 
> Even that's not possible. The "Enable reviews" setting for individual languages always follows the "Enable reviews" setting for the project, i.e. the project setting always overrides the language setting (on hosted Weblate), even though it says "Settings saved" for the language.

If it doesn't work as described in the documentation, please open a separate issue describing where it doesn't behave correctly next time. The setting is correctly saved and used, but the form always displays it to match the project setting. https://github.com/WeblateOrg/weblate/pull/12458 fixes that.

> But my question actually is, why can't we have no reviews for the project (to encourage translators) and set reviews for individual languages that are already at 100% and quality checked?

The reason is that the project level setting enables some features in the project scope as well (like what states you can set in the bulk edit or showing approved strings in stats). This could be calculated from the setting of all the translations, but it was avoided for performance reasons. https://github.com/WeblateOrg/weblate/pull/12458 also adds validation for this.
