### ISSUE TITLE
About Qt TS language format file name 

### ISSUE THREAD

**Issue by rekols** [WeblateOrg/weblate#5466]
Recently we have used weblate as a translation platform, it is very easy to use and powerful, but we also found problems. Most of the translation files of Qt programs under Linux follow the standards of [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) and [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1), but I can’t find these settings in weblate.

This is our weblate homepage: https://hosted.weblate.org/projects/cyberos

CC: @omaemae @probonopd

**Comment by nijel** [comment]
Can you please clarify what is the actual problem? There is no problem in using ISO 639-1 language codes. The Weblate settings actually covers things not defined by ISO 639-1 - how to include country code there, see https://docs.weblate.org/en/latest/admin/languages.html#adding-new-translations.
