### ISSUE TITLE
Version specific documentation help links in admin settings setup broken

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5469]
https://hosted.weblate.org/settings/weblate/application

The (i) links are for https://docs.weblate.org/en/weblate-4.5/admin/projects.html#component-source-language and so on, and that doesn't work.

**Comment by nijel** [comment]
That's a temporary issue - I wanted to release 4.5 yesterday, so the repository was prepared for the release, but there are still some issues to address, and the tag and the release are not yet done.
