### ISSUE TITLE
msgmerge invalid control sequence

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#5473]
How do I find an error in a file?
What are these digits after expanding .po 160227428.po:156:163 ?
![image](https://user-images.githubusercontent.com/39633242/108473677-a0956580-728e-11eb-960c-fd395c8a6469.png)

**Comment by nijel** [comment]
It's line and character in that line.

**Comment by tomkolp** [comment]
Thank you for your answer. How can I tag this character?
![image](https://user-images.githubusercontent.com/39633242/108478999-77c49e80-7295-11eb-8507-b09f3999165a.png)

**Comment by nijel** [comment]
You should probably double the backslash.

**Comment by tomkolp** [comment]
works well
