### ISSUE TITLE
Glossaries added multiple times

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#5478]
Why does my component here has 6 entries for Glossary now?
I would expect only one.
![image](https://user-images.githubusercontent.com/26718215/108533063-d65f3c00-72d8-11eb-86bf-531c2b3b48c3.png)
(They are all named the same, I just had to pixel them, since it gave away the customer name - data protection....)
Thanks!

**Comment by nijel** [comment]
Are these six different glossaries or a single glossary listed six times?

**Comment by ilocit** [comment]
Right, seems to be one listed six times.
