### ISSUE TITLE
Always list all string status bars everywhere

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5479]
This is probably a no-go with phone-clickability in mind.
However it could maybe be done with expandable categories/sections?

These two buttons are very clickable already
![bilde](https://user-images.githubusercontent.com/13802408/108582510-24edf400-7334-11eb-9709-18c861eaca2c.png)

My problem is finding things when the position of them change between projects. Costs vertical space though. Squeeze together to make the compromise?

What is sometimes
![bilde](https://user-images.githubusercontent.com/13802408/108582240-2e765c80-7332-11eb-9b3c-a402300b68fe.png)

is sometimes
![bilde](https://user-images.githubusercontent.com/13802408/108582275-71383480-7332-11eb-8320-4ef4aa5d4593.png)

When it could be something like

![bilde](https://user-images.githubusercontent.com/13802408/108582305-ab093b00-7332-11eb-8567-1af8a9dcfe74.png)

Or even missing ones in between would be fine.

![bilde](https://user-images.githubusercontent.com/13802408/108582339-e73c9b80-7332-11eb-8a7d-0e898744aa02.png)

For example https://hosted.weblate.org/projects/cyberos/audio-recorder/nb_NO/ doesn't have as many items.

**Comment by nijel** [comment]
I don't think this is the way to go, there can be - there are currently 58 checks which could be listed there (+ about 18 non-check categories). Having them grayed out would make it had to find the ones which are actually relevant and having blank space would lead to a *lot* of blank space on the page (which is something you always fight against ;-)).

**Comment by comradekingu** [comment]
I am just exploring my own confusion here. It becomes an issue of screen-estate too.

I think a combination of indentation/desaturation and expandable categories could make it tolerable.

Not always having the main red and yellow categories makes it appear more random. That they are in opposite order to the bar makes it no less strange. It always seemed so random.
In my head the position of red spots on the bar should be positional too. Are the new strings failing, are they old ones? What are the meta categories, which ones are actual strings.

Having expandable categories is an interesting way to find the history of failing checks, or set up alerts for specific fails/show which ones alerts are set up for.
