### ISSUE TITLE
Fuzzy date parsing for search queries

### ISSUE THREAD

**Issue by Fat-Zer** [WeblateOrg/weblate#5483]
It would be nice to have fuzzy date parsing for search queries for `added` and `changed` fields to allow such queries as `changed:>"2 days ago"`.

**Describe the solution you'd like**

Can be pretty easily implemented with a library such as https://github.com/bear/parsedatetime

**Comment by alvinchen977** [comment]
@nijel I'm interested in tackling this, but I'm not really sure which files to take a look at. If you could give me a few pointers, that would be great!

**Comment by nijel** [comment]
The datetime parsing is here:

https://github.com/WeblateOrg/weblate/blob/af24d35e0d3ab51887bc2f18e1629db675b2a544/weblate/utils/search.py#L313-L365

Related tests are here:

https://github.com/WeblateOrg/weblate/blob/af24d35e0d3ab51887bc2f18e1629db675b2a544/weblate/utils/tests/test_search.py#L141-L211

**Comment by nijel** [comment]
Another library I quickly found: https://github.com/scrapinghub/dateparser

There might be something better to use, so the first step would be to find the best library to use (maintained, features, ...).
