### ISSUE TITLE
Glossary in Zen mode

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#5484]
A very useful option would be to highlight the terms from the dictionary in Zen mode, with the function of displaying the translations in a "bubble" on hovering over the mouse, similar to the normal mode.

**Comment by comradekingu** [comment]
In keeping with the Zen of things, do you mouseover the actual word in the source language, (and respective glossary translations in alternative languages)?  How do you know to do that? Is there a hotkey for it?

Do you copy the existing translation to your translation field easily? Do you click it? Is there a hotkey for that? Both?

How does forbidden words get shown? Red under-strike, check failing once translated? Both?

#5126 is my idea of seeing comments, but it might fail if there is a whole thread.
