### ISSUE TITLE
Several issues with new glossary implementation

### ISSUE THREAD

**Issue by Fat-Zer** [WeblateOrg/weblate#5486]
I've noticed several relatively small issues in recent glossary reimplementation and its documentation. I don't feel like each of those  deserves it's own bug report. Although I don't want them to get lost. 

**Describe the issues**

* [x] Marking terms as forbidden are available for users now, but it shows an «insufficient privileges» error (despite actually adds the flag).
* [x] IMHO marking terms as "Not translatable" should be available for users as it should be managed by translators and the set of such words may differ from one language to another. 
* [x] Adding explanations should be available for users and bond to translation.
* [x] It would be nice to have explanations available from the glossary panel (probably in form of a tooltip)/source string tooltip text.
* [x] Glossary documentation messages that you can share a glossary with an another project quite badly: it can be misread as "If you have a shared component, you will share the glossary"
* [x] It would be nice to have a shortcut to browse the glossary on the side panel e.g, an eye-shaped icon besides the pen one.
* [x] It would be nice to have a more clear designation for forbidden translations: may be an icon with an exclamation mark as for the configuration errors between the term and the translation.

**Comment by nijel** [comment]
The explanation should be already available in the glossary panel. I will check rest later...

**Comment by Fat-Zer** [comment]
I'm felling like I'm pushing some keep-feedback-useful limit, adding more and more to the list... Feel free to tell me to stop or if you want it in some other format...

**Comment by tjhietala** [comment]
There's also the small issue that there's nothing to indicate that the user is editing the glossary. It looks just like any other component. Even the glossary pane on the right hand side is displayed! ([example](https://hosted.weblate.org/translate/weblate/glossary/fi/?checksum=ea1ecd8e7ce703f9))

**Comment by tjhietala** [comment]
Correction: Actually it says "Glossary term", but that might be easily missed as evidenced above...

**Comment by nijel** [comment]
It is more visible since 353ff0ecc4fbf855c46c94ccf22f1daa6302fd43.
