### ISSUE TITLE
No "bubble" glossary hints in the mobile version

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#5490]
In the mobile version, the glossary hints are not displayed when you hover over the highlight.

**Comment by nijel** [comment]
There is no "mobile version" it is just one responsive version. The glossary hints are using HTML title attribute, so maybe your mobile browser doesn't show them? And btw: How to you hover on mobile?

**Comment by Fat-Zer** [comment]
I believe the point of the issue, is that you can't ... AFAIK mobile browsers don't display title/alt text even if you attach a mouse to it.

You could replace a `title` with a proper tooltip... besides support for mobile version it will allow to visually separate the useless text like ("Glossary term: ") from it's translation... and better distinguish read-only/forbidden and normal terms....

**Comment by nijel** [comment]
We had several issues with Bootstrap 3.x tooltips, that's why they are no longer used. This might be revisited once we upgrade to Bootstrap 5 (or newer), see https://github.com/WeblateOrg/weblate/issues/2916.
