### ISSUE TITLE
Translators can no longer add glossary entries

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#5493]
With the glossary related changes in v4.5, translators now can no longer add new term unless I give them rights to maintain the glossary. But that would allow them to also modify existing terms.

Translators should only be allowed to add new proposed terms.
Glossary maintainers should then validate them and approve.

Solution: 
* add the permission to add terms to the translator role
* only when the term and translation are set to approved (or at least no longer as "Needs Editing", which should be the default after a new Term was added!) the term should be displayed in the glossary. Or, maybe even better, the status "In Review" / "Approved" should be displayed along with the term in the Glossary area of the string translation page.

**Comment by nijel** [comment]
This should work similar as before - users need permission to add glossary entries and that was the case before as well. The only difference is that it now follows component and language level permission in case you are utilizing that.

**Comment by ilocit** [comment]
OK. If it was like that before....
Maybe this could then be changed to a feature request/suggestion?
I think it is really important that Translators can add Terms to the Glossary but they should not be able to modify (or even delete!) existing terms in an existing glossary.

**Comment by nijel** [comment]
Adding to a glossary always required permission to do so and that one is in all built-in groups tied together with other glossary management commands. If your translators could add terms to a glossary without that, it sounds like a bug that was fixed.

**Comment by Fat-Zer** [comment]
Actually, according to the docs there are (or at least there were) several distinct glossary-related permissions:
* Add glossary entry
* Edit glossary entry
* Delete glossary entry
* Upload glossary entries

By default all of those are assigned to the same groups on each Weblate-provided (public, protected or private) access control modes, but with custom mode (when you compose together your own groups via the Django's admin interface) those actions could be separated.

I don't know if it were working before and I haven't tested whether it works now or not... And I'm not sure if it's relevant to the @ilocit case... But if it doesn't it's probably a bug or a regression...

**Comment by ilocit** [comment]
I think I was able to edit also the standard roles which you ship with Weblate in the past, but maybe I am mistaken. 
Now I can't.

![image](https://user-images.githubusercontent.com/26718215/108966339-57725680-767e-11eb-9c2f-b473006e4e07.png)


Would be nice though, because then I could add the View and Add glossary entry to that standard role. Because I do not want to add the Glossary role to all translators so that they could change existing entries and/or delete them.

Can this be fixed/changed in Django, please.
Thanks!

**Comment by nijel** [comment]
The "Translate" role never had permission to add glossary terms.

It was possible to edit built-in roles, but the changes were reverted on upgrade that's why it's intentionally not possible now to avoid suprpise on upgrade (see #4842). See also https://docs.weblate.org/en/latest/admin/access.html#default-groups-and-roles

**Comment by ilocit** [comment]
Well ok. That is nice, but defining your own roles (I did that previously) is nice but very difficult to maintain.
The default roles are still created/assigned by default for new projects. For instance you can not use the new (don't remember in which version) User UI in the project/component frontend with custom roles, only the default ones.

Is there a tweak I can use to enable changing the default rules? 
Or wouldn't you think that translators should also be able to **add** terms (as proposals), thus you change this in the default role generally?
The approval and flagging as Terminology and translation thereof would then still have to be managed by the role Glossary.
I understand why you have this locked, but that was also before you introduced this much more powerful Glossary feature now in v4.5

So I thing the roles/permissions need to be updated to reflect these new possibilites. No?

**Comment by nijel** [comment]
I don't see much of new possibilities. Unless you enable review workflow, the glossary behaves exactly same as before. For most projects it doesn't make sense to decouple adding and editing - you want users to be able to fix typos or errors in the translations.

**Comment by ilocit** [comment]
But a glossary is something else entirely.
You want to control quality by using glossaries and thus want to define a strickt process for creation, enrichment, validation and approval. 

Anyhow, the easiest would be to allow editing the default translator role or being able to create a new custom default role.

**Comment by nijel** [comment]
Created https://github.com/WeblateOrg/weblate/issues/5560 to track this.
