### ISSUE TITLE
Translators should not be able to add translation languages to a project/component

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#5494]
Maybe I did not notice before, or it is new with v4.5, but translators can now add languages to projects/components.
This messes up the setup of the project, esp. if there are multiple components which have different languages by design...

![image](https://user-images.githubusercontent.com/26718215/108686315-87dab900-74f5-11eb-9b17-0f00ef148dc7.png)

Only project maintainers/admins or (if I understand the role correctly) users with the role **Languages** should be able to add languages!

**Comment by Fat-Zer** [comment]
Have you configured `Adding new translation` in the project's settings correctly, see [doc](https://docs.weblate.org/en/latest/admin/projects.html#adding-new-translation).

**Comment by ilocit** [comment]
There is no such setting. You can do that to some extend on the component level, but not on the project level.
I also had a closer look at this again and it also relates to the new Glossary feature!
The permission to add new languages is automatically set to "Enable" for those newly created "Glossary Components". This should take over the settings from the component/project for which the Glossary was created. I will close this issue here, because it is not an issue related to new or changed permissions, but rather about how the Glossary components are created.
