### ISSUE TITLE
Glossary components - Create New Translations settings are always enabled, even if disabled for "oringial" component

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#5496]
After migrating to v4.5 for each project/component a new Glossary component is/was created.
This component did not inherit the "Adding new translation" setting from the project/component, but was set to "Create new language file". So now the translators can create new translations for those. This is not the desired behavior.
* By default it should be disabled or inherit the setting from the main component/project.

CURRENT:
![image](https://user-images.githubusercontent.com/26718215/108696265-9a5aef80-7501-11eb-8f8c-e9bbbee9baf7.png)

Expected:
![image](https://user-images.githubusercontent.com/26718215/108696312-a777de80-7501-11eb-8cbf-0ab1bc63a91d.png)

**Question:**
Can this be fixed generally, or do we now need to change this for each of the dozens new Glossary components which were created during the migration to v4.5?

**Comment by comradekingu** [comment]
@ilocit You are killing me here. "oringial" should be "original".

---

I think it would depend on whether the components themselves are set as slaves to a master component https://docs.weblate.org/no/weblate-4.5/admin/projects.html#component-repo

Where do you get "Adding new translation" from?

**Comment by nijel** [comment]
Adding is turned on by default for glossaries, but it should not be needed since 16512702eff68703663d10fbea85c64d885eab0d, so it seems better to turn it off by default.
