### ISSUE TITLE
Support scheme-format

### ISSUE THREAD

**Issue by roptat** [WeblateOrg/weblate#5504]
**Is your feature request related to a problem? If so, please describe.**
I've added some translations on a self-hosted weblate instance for a scheme project. The translation uses gettext (po files) and strings have the `scheme-format` comment. While translating, I made a mistake in the format strings and broke the software. Weblate did not warn, even though msgfmt managed to report the error.

**Describe the solution you'd like**

Ideally, a scheme-format check would be implemented, similar to python-format, c-format, php-format and the like that I saw in the documentation.

**Additional context**

In case it can help, here's a sample of scheme-format gettext:

```
msgid: "module ~a not found"

msgid: "  root device: ~[UUID: ~a~;label: ~s~;~a~]~%"
```

where `~a`, `~s`, `~[`, `~;` and `~%` are format specifiers like `%s` or `%d` in C (there are more, including positional arguments). Here is the documentation for the Scheme implementation I'm using: https://www.gnu.org/software/guile/manual/html_node/Formatted-Output.html.

Please tell me if there's any way I can help. If you think this is not too hard as a first contribution, can you guide me through the general steps I need to take to implement that support?

**Comment by nijel** [comment]
Adding new format checkers is easy:

1. Define a regular expression to extract the format.
2. Add it to list of format definitions (you will probably need to define function to decide whether format is position based or not):
    https://github.com/WeblateOrg/weblate/blob/ac4dd72fa6fcf8067b77ee084b9259c0578a3692/weblate/checks/format.py#L214
3. Define a check class (which will most likely not need to override any methods):
   https://github.com/WeblateOrg/weblate/blob/ac4dd72fa6fcf8067b77ee084b9259c0578a3692/weblate/checks/format.py#L434-L439
4. Add it to list of configured checks in few locations (weblate/checks/models.py, weblate/settings_*.py)
5. Add documentation for the check to docs/user/checks.rst
