### ISSUE TITLE
Glossary in v4.5 adding wrong language

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#5505]
We have a project where one of the configured languages is pt-PT (Portuguese - Portugal).
During the upgrade to v4.5 a Glossary for this component was created as expected.
When new terms were added and marked as "Terminology", they were added as to be translated into PT (Portugal).

This means we have two Portuguese in our component now:

![image](https://user-images.githubusercontent.com/26718215/108772443-4c73d500-755d-11eb-82fc-ff976b24dad4.png)

Please fix so that a Glossary entry for the correct language variant is created, depending on the language list of the component.

**Comment by nijel** [comment]
You had them before as well, the migration uses the same language as was used before, it does no conversion of the language at all. It is just way more visible now :-).

**Comment by ilocit** [comment]
Honestly, that particular project did not have PT as a language, it is based on XLFs in a git repo. And there is only a pt-PT.xlf and no pt.xlf. So PT did not exist in the project or the single component which exists. I promise.

![image](https://user-images.githubusercontent.com/26718215/108814656-7a840400-75b3-11eb-86c0-7c1279bbe37e.png)

**Comment by nijel** [comment]
The migration doesn't create any new content, so the glossary had to be present. If you have database backup before the upgrade we can confirm that.

**Comment by ilocit** [comment]
Of course, the glossary existed, but not the language pt-PT. Only PT. Perhaps this is a misunderstanding?

**Comment by nijel** [comment]
The glossary for pt-PT had to exist. The migration cannot create them out of nothing. Maybe they were not used for a long time...

**Comment by comradekingu** [comment]
There is some logic to create new components in the correct locale if memory serves me right. However that is pt-PT, which looks correct to begin with…

From the first-post I can't understand where just "pt" entered the picture…

Had pt-PT (Portuguese - Portugal) language
got pt-PT (Portuguese - Portugal) glossary
filestructure says pt-PT.xlf

why is there a "Portuguese" (presumably "pt") glossary (with two untranslated entries, each of which has one word so that has to be the glossary)?

**Comment by ilocit** [comment]
> The glossary for pt-PT had to exist. The migration cannot create them out of nothing. Maybe they were not used for a long time...

Right of course. I was typing too fast. The pt-PT has to exist. It is the translation language of the project the PT one is / was wrong.
Sorry for the confusion.
I guess the PT one might come from as Glossary which was created in this component before the migration? But how come that a previously existing glossary does not have the correct pt-PT setting when pt-PT is the translation language?

Anyhow, I deleted this additional glossary. No big deal.
But the implementation of the new glossary functionality is "buggy". Probably because it is really a big change.

I will close this issue and create a new one where something is really wrong. I guess it all has to do with org-lang != EN (we work a lot with projects which have e.g. DE as the source).

Thanks a mil!

**Comment by nijel** [comment]
> I guess the PT one might come from as Glossary which was created in this component before the migration? But how come that a previously existing glossary does not have the correct pt-PT setting when pt-PT is the translation language?

Both had to exist before migration. In previous implementation the glossary for any used language was automatically listed and users could add strings. Maybe you did have [SIMPLIFY_LANGUAGES](https://docs.weblate.org/en/latest/admin/config.html#simplify-languages) turned on initially, users added some glossary terms, and it stayed there once you turned it off?

Anyway, I'm confident there is no bug in the migration - it will not introduce glossary languages which did not exist before the migration.
