### ISSUE TITLE
A project with 1000 components is very slow

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#5513]
In a project with a large number of components, individual segments load tragically. My project has about 1000 components, it has a lot to do with speed in all components. For comparison, I have created a new project with the same files and it loads quickly. Unfortunately, I cannot afford many projects because propagation does not work between projects.
For speed comparison, I put the same files in a test project, one is shared from a huge project.
[Link](https://weblate.eso-spolszczenie.eu/projects/101286772-test-propagacji-miedzy-projektami/)

**Comment by nijel** [comment]
We definitely need to re-introduce pagination here to avoid loading all the components in such cases.

**Comment by tomkolp** [comment]
I will test how the new docker image will be available.
