### ISSUE TITLE
Confusing naming of converted downloads

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#5515]
![image](https://user-images.githubusercontent.com/39633242/109129875-6544dc00-7751-11eb-942a-e8cdbd8c363c.png)
![image](https://user-images.githubusercontent.com/39633242/109129939-78f04280-7751-11eb-80ce-03de80ec655a.png)
This can cause a problem when importing.

**Comment by tomkolp** [comment]
Problem with source

**Comment by tomkolp** [comment]
![image](https://user-images.githubusercontent.com/39633242/109141120-aa6f0b00-775d-11eb-9df7-9ca2789fed45.png)
I have created a new component marked as a glossary. I used the file from the screen. The explanation is displayed as a comment.

**Comment by nijel** [comment]
There are two ways of getting files from Weblate:

* The original file as is stored in the repository. This follows as closely as possible original format and does not include any additional metadata. This is the first option in the download menu.
* Converted files for offline usage. These attempt to fit as much information as possible into the file for offline usage. Often this leads to putting content into developer comments as most formats do not support anything like suggestions or different source of comments. These are all the other options in the download menu.

![obrazek](https://user-images.githubusercontent.com/212189/109149005-49e4cb80-7767-11eb-94dd-24fc14a75bb7.png)

When you download the files using the second method and use it in Weblate the different behavior is expected.

What we really need is to set correctly expectations on the converted downloads.

@orangesunny Please can you take a look at this? This is a similar issue to what YouGov has hit...

**Comment by tomkolp** [comment]
If comments and explanations are exported, the import should take them into account.

**Comment by nijel** [comment]
Nearly all things from Weblate are included in the comments and there was no intention to make it machine readable, so in the current form the import is not possible. (I think there is some issue on this)

**Comment by tomkolp** [comment]
After moving from Smartcat to weblate, I have 5 glossaries. They all have 150,000 strings and over 20,000 comments. I would like to import comments as "explanations". Showing explanations in the glossary is really great. Unfortunately at the moment I have to do it manually, so translators use google sheet to find "explanations"
I think this is a big problem for users migrating to Weblate from other translation platforms.

**Comment by nijel** [comment]
The explanation is stored in the Weblate database only, I've just explained this in https://github.com/WeblateOrg/weblate/issues/5517#issuecomment-788729502

**Comment by nijel** [comment]
Let's deal with clarification of the download naming here and cover the glossary explanations in #5519.
