### ISSUE TITLE
Setup New Weblate to latest version 4.5

### ISSUE THREAD

**Issue by jmanaks1** [WeblateOrg/weblate#5518]
Dear Team,

We have recently setup new Weblate version-4.5 with PostgreSQL db.
But after configuration of almost everything landing page layout is still not coming proper.

Please find attached layout coming.
Can you suggest what could be the issue?

Thank You.
Sameer Manake.
![Weblate-UI](https://user-images.githubusercontent.com/36956821/109151636-6ea16900-7790-11eb-8fd5-def11b508f1e.PNG)

**Comment by nijel** [comment]
Most likely your serving of static files is misconfigured, see https://docs.weblate.org/en/latest/admin/install.html#static-files

**Comment by jmanaks1** [comment]
I have tried all static root setting but still same issue....and now getting another error "internal server error".
Please find attached screenshot of error.
![weblate_internal_server_error](https://user-images.githubusercontent.com/36956821/109176693-1331a400-77ad-11eb-9653-135789fafdd3.PNG)

Thank you

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/contributing/debugging.html

**Comment by jmanaks1** [comment]
By keeping "DEBUG = True " in settings.py file, I am able to access UI but with "http://iec-weblate.go.johnsoncontrols.com:8000/admin" (with admin suffix).
If I try to connect with http://iec-weblate.go.johnsoncontrols.com:8000/ only (without admin suffix)...shows following error.

ProgrammingError at /
relation "weblate_metric" does not exist
LINE 1: ...ate_metric"."name", "weblate_metric"."value" FROM "weblate_m...
                                                             ^
Request Method:	GET
Request URL:	http://iec-weblate.go.johnsoncontrols.com:8000/
Django Version:	3.1.6
Exception Type:	ProgrammingError
Exception Value:	
relation "weblate_metric" does not exist
LINE 1: ...ate_metric"."name", "weblate_metric"."value" FROM "weblate_m...
                                                             ^
Exception Location:	/root/weblate-env/lib/python3.8/site-packages/django/db/backends/utils.py, line 84, in _execute
Python Executable:	/root/weblate-env/bin/python
Python Version:	3.8.5
Python Path:	
['/root/weblate-env/lib/python3.8/site-packages/weblate/examples',
 '/root/weblate-env/lib/python3.8/site-packages/git/ext/gitdb',
 '/root/weblate-env/bin',
 '/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '/root/weblate-env/lib/python3.8/site-packages',
 '/root/weblate-env/lib/python3.8/site-packages/gitdb/ext/smmap']
Server time:	Mon, 01 Mar 2021 15:10:23 +0000

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-4-4-to-4-5

**Comment by jmanaks1** [comment]
Thank you for all your support till now, we are able to see proper UI now.

Is there any way to keep weblate server continuously ON, even if we disconnect Shell access?
Currently weblate server getting stopped if I disconnected shell access and to start it again we have to run "weblate runserver" command.

Thank you!

**Comment by nijel** [comment]
Sure, just don't use `runsever` (which is suitable for development only) and choose one of the production setups: https://docs.weblate.org/en/latest/admin/install.html#running-server ... or use a Docker image, which does include all needed parts.
