### ISSUE TITLE
Avoid git merge conflicts if possible

### ISSUE THREAD

**Issue by evfool** [WeblateOrg/weblate#552]
If multiple subprojects are using the same git repository, but different branches, and translation propagation is set, it would be nice to commit the changed translations on one branch and e.g. cherrypick the commit to the other. 
Currently this is not the case, and having subprojects for separate branches with translation propagation, when the branches will get merged, we'll have conflicts in all the changed translations.
##

**Comment by nijel** [comment]
Few years later: I still don't see how cherry picking would make merging branches easier. Either the change is applicable and git merges the branches just fine or it is not and cherry pick won't work as well.
