### ISSUE TITLE
Random 503 errors from Weblate

### ISSUE THREAD

**Issue by jmdem** [WeblateOrg/weblate#5520]
**Describe the issue**
Hi, first thanks for creating this amazing app !
We recently faced a strange issue with our hosted docker version of Weblate. We use Weblate to manage and serve translations, and we noticed that on a ratio of 1/10, some request were returning a 503. The Weblate API is often requested, when our users logs in one of our web apps. As said, most of the time, everything just works. But randomly, the server seems to be unable to serve the data, no matter which route.
Is there anything we're missing here ? Reading the docs, we didn't see anything that can cause this random issue.

Any help is much appreciated, thank you.

**I already tried**
We already tried to stress the Weblate service API, with many concurrent requests, and up to 100 concurrent request, it responds well.
Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

2. Scroll down to '...'
3. Click on '...'

**Expected behavior**

**Screenshots**

**Exception traceback**

**Server configuration and status**

Weblate installation: weblate.org service / Docker / PyPI / other

**Weblate deploy checks**

**Additional context**

**Comment by nijel** [comment]
It can be that all uwsgi workers are busy, you can try increasing that: https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-UWSGI_WORKERS

**Comment by jean-marc-dembele** [comment]
Thanks for the reply, we keep monitoring the issue, if we need to we'll try this solution and see if it improves in someway.
B.R.
