### ISSUE TITLE
Add interface to force sync files

### ISSUE THREAD

**Issue by lunikon** [WeblateOrg/weblate#5521]
**Describe the issue**

I have an otherwise perfectly functional Weblate installation using the Docker image. On it, there are several translation projects for around half a dozen languages. On one of the smaller projects, just 44 strings, the interface shows me that the German language version is fully translated. In fact, I can click through all 44 strings and verify that they are indeed translated. This is what it looks like:

![image](https://user-images.githubusercontent.com/277052/109217778-8d1a5b00-77b6-11eb-934e-73165933ba3c.png)

Yet when I try to download the translation or commit to the repository, the resulting Java Properties file only contains 24 strings.

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.
- [x] When I try to download the translations in another format, like JSON, all 44 strings are included, so it is likely related to the message format. 

**To Reproduce the issue**

unknown

**Expected behavior**

There are two options: 

1. The Java Properties file should include all 44 translated strings.
2. If generating the full file fails for any reason, an error message describing the issue should be printed instead of generating a partial file. Depending on the workflow, just generating a partial file can cause major headaches.  

**Screenshots**

See above.

**Exception traceback**

I see no error messages of any kind when I follow the Docker logs while downloading the file. 

**Server configuration and status**

Weblate installation: Docker

weblate@2b27b855d8ed:/$ weblate list_versions
 * Weblate: 4.5
 * Django: 3.1.6
 * siphashc: 2.1
 * translate-toolkit: 3.3.2
 * lxml: 4.6.2
 * Pillow: 8.1.0
 * bleach: 3.3.0
 * python-dateutil: 2.8.1
 * social-auth-core: 4.0.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.11.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.2
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.6
 * celery: 5.0.5
 * kombu: 5.0.2
 * translation-finder: 2.9
 * weblate-language-data: 2021.2
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.25.1
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.20.3
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.13
 * borgbackup: 1.1.15
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.6
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.17.11
 * zeep: 4.0.0
 * aeidon: 1.9
 * iniparse: 0.5
 * mysqlclient: 2.0.3
 * Mercurial: 5.7
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * Redis server: 6.0.9
 * PostgreSQL server: 13.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.eu.mailgun.org
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.9.0-0.bpo.4-amd64 (x86_64)

**Weblate deploy checks**

weblate@2b27b855d8ed:/$ weblate check --deploy
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.5/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.5/admin/backup.html

System check identified 2 issues (1 silenced).

**Additional context**

none

**Comment by nijel** [comment]
Saving to the file happens in the background, any related error message should be visible in the logs, did you check that? See https://docs.weblate.org/en/latest/contributing/debugging.html

**Comment by lunikon** [comment]
Tailing the Docker logs, I caused a translation change and then went to the Repository maintenance page to trigger an update.  While the repository update did show up in the logs, I didn't see anything hinting at an error, neither when doing the translation change, nor when triggering the update or when the update actually took place.

Does the Docker log contain all output generated by Weblate? Should I enable some additional logging or look into another logfile?

**Comment by nijel** [comment]
Yes, everything is logged there. You might want to enable debug mode to see more messages.

**Comment by lunikon** [comment]
Even with debug mode enabled, there is nothing pointing towards an issue. Whatever writes the properties file just silently swallows half of the strings without causing an error. Unfortunately, I know very little about Python, but if you point me into the general direction of the code that is responsible for generating the files, I might be able to have a look.

**Comment by nijel** [comment]
It is expected to write only changed strings, so unless the strings are changed in Weblate they won't appear there. In case the strings were removed by Weblate at some point, look at the Git commit which removed them. There might be some incompatibility in the original file that caused this.

**Comment by lunikon** [comment]
I started the file in question "from zero" and translated everything essentially in one go. The first commit already had the wrong number of translated strings. Meanwhile, I have tried updating individual strings to trigger updates and I also enabled the "Formats the Java properties file" addon to cause Weblate to resort all strings. The latter worked, but still only with the strings that were previously in the file.

I would understand if the strings in questions wouldn't be written due to some problem detected by Weblate. But as per my screenshot in the OP, everything looks fine.

**Comment by nijel** [comment]
If you change the string which is missing from the file and commit the translation in Weblate, is it added? Can you please share a log for this?

**Comment by lunikon** [comment]
Huh, this actually worked. When I edit a string, it gets added to the properties file. As if there was a flag on a string that it has already been "added" that got out of sync with reality. Is there anyway to "reset" a file so it gets written in its entirety once?

**Comment by nijel** [comment]
There is currently no such option, though it could be done by changing the flag in the database or using Django shell.

The question still is why the strings were not written in the first place. There had to be some error while writing them out, but the code is not supposed to unset the pending flag without writing out the changes to a file...

**Comment by lunikon** [comment]
Thanks you very much for you great support! Installed the latest version today, forced a synchronisation and the problem went away.
