### ISSUE TITLE
New language for App Store Metadata uses unsupported language code

### ISSUE THREAD

**Issue by spacecowboy** [WeblateOrg/weblate#5522]
**Describe the issue**

Having configured a component with `App store metadata files`, when a user added a new Japanese translation the folder `fastlane/metadata/android/ja/` was created but later during a deployment fastlane failed with the following error

```
badRequest: The requested language is not currently supported: ja
```

The correct code would be `ja-JP` as seen in the list on https://www.ibabbleon.com/Google-Play-Store-Language-Codes.html for example

**To Reproduce the issue**

1. Set up a component with type `App store metadata files`
2. Add a japanese translation
3. Note that the folder created has the language code `ja`

**Expected behavior**

The folder should have the language code `ja-JP`. It should not be possible to create the invalid `ja` folder for this type of translation.

**Comment by nijel** [comment]
We apparently need special language codes handling for this case - there is no logic in the used language codes as some include country codes and some do not...

**Comment by ParthS007** [comment]
Hi @nijel, The issue looks interesting to me and I want to work on this one. 

Can you please point me to related source code and any other resource to get started. Thanks :)

**Comment by nijel** [comment]
I'd name the new behavior "appstore" and it probably needs to hardcode the list of language codes (at least I don't see any system in that).

The logic is defined in file format class:

https://github.com/WeblateOrg/weblate/blob/28993930cf44fec4786b72cec159b4981add3d35/weblate/formats/base.py#L417-L428

The list of available choices is here:

https://github.com/WeblateOrg/weblate/blob/28993930cf44fec4786b72cec159b4981add3d35/weblate/trans/models/component.py#L126-L142

And the default for the app store file format is here:

https://github.com/WeblateOrg/weblate/blob/28993930cf44fec4786b72cec159b4981add3d35/weblate/formats/txt.py#L186

**Comment by spacecowboy** [comment]
You should be aware that the Apple play store and Google Play store have different supported locales

so you should differentiate behavior based on if it's `fastlane/metadata/android/<FILE>` or `fastlane/metadata<FILE>`

see https://docs.fastlane.tools/actions/deliver/ for iOS

and https://docs.fastlane.tools/actions/supply/ for Android

**Comment by eighthave** [comment]
I think the simple fix to this is to make Weblate always use BCP47 language tags (e.g. with `-` rather that `_`).  Then people who are actually uploading to Google Play can manually manage the locale tags as needed.  F-Droid will use any valid BCP47 from the fastlane directory.

The Google Play list does seem really arbitrary, and even worse, they have changed it, according to the fastlane ode: https://github.com/fastlane/fastlane/blob/633860a5aae0fa9c0b936797560efb24181b1bf7/fastlane_core/lib/fastlane_core/languages.rb#L14

**Comment by spacecowboy** [comment]
That might be the better choice - and simply mention the huge weirdness of the app stores behavior here in the docs.

I currently have some code in my deployment script which removes translations not supported by google play.

**Comment by nijel** [comment]
> I think the simple fix to this is to make Weblate's fastlane support always use BCP47 language tags (e.g. with - rather that _). 

That's already the case since 64c1c0d8dcd34c46b86ee23ae31a1b1387794163, see #5446.
