### ISSUE TITLE
Bulk Edit addon doesn't run automatically on git updates

### ISSUE THREAD

**Issue by spacecowboy** [WeblateOrg/weblate#5524]
**Describe the issue**

I have setup the `Bulk Edit` addon to set changelogs as read-only and it is not triggered automatically. I have to manually edit and save the config to make it run on each release.

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

0. Configure weblate to monitor your gitlab repo
1. Add bulk edit addon to your app store metadata component
2. Configure it with custom search `key:changelogs`, state `do not change`, and translation flags to add `read-only`
3. Add a changelog to the project, a file such as `fastlane/metadata/android/en-US/changelogs/99.txt`
4. Push the commit to your project
5. Go to weblate and manually click `Update` to ensure it has the commit

**Expected behavior**

When the new commit is pulled, bulk-edit runs, and the new changelog is marked as read-only in all languages.

**What actually happens**

bulk-edit doesn't run - and user is forced to open config and save config to make it run - for every release made to the project.

**Comment by nijel** [comment]
It is supposed to run on translation files update. What version do you use? There were some changes in signals triggering in 4.5, but I'm not sure it could be related.

**Comment by spacecowboy** [comment]
> It is supposed to run on translation files update. What version do you use? There were some changes in signals triggering in 4.5, but I'm not sure it could be related.

Whatever version `hosted.weblate.org` runs.

**Comment by nijel** [comment]
Would you mind sharing the component where it happens so that we can take a look?

**Comment by spacecowboy** [comment]
> Would you mind sharing the component where it happens so that we can take a look?

Sure, it's https://hosted.weblate.org/projects/feeder/f-droid-and-play-store-metadata/
