### ISSUE TITLE
Do not logout user on rate limiting

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#5528]
Does that happen when start new language translation in multiple projects within short period time? I also had tap skip button often to get and translate small amount of words contain strings first
Recently i added and was translating few projects to new language and now when i click to add new language in other projects then quickly log me out. it's better to display slow down mode in UI instead log out as in telegram groups, if user ignored warning few times then good to log out

eg: |Slow down mode| You have to wait x time to perform x action

_Originally posted by @uNitrous in https://github.com/WeblateOrg/weblate/issues/2208#issuecomment-786608052_

**Comment by petrenkonikita112263** [comment]
Hello, will change of [limits](https://docs.weblate.org/uk/weblate-4.15.1/admin/optionals.html#rate-limit) improve situation instead of waiting?
