### ISSUE TITLE
Ability to erase audit log and disable it

### ISSUE THREAD

**Issue by Aikatsui** [WeblateOrg/weblate#5534]
**Is your feature request related to a problem? If so, please describe.**
Some users feel uncomfortable when certain web-app keep log IP addresses, timestamps and localization platform isn't critical instrument for translator as personal mail or IM account, weblate also offer on-premise solution then it's good to offer flexible features

**Describe the solution you'd like**
- Add option to erase audit log
- Add option to disable audit log for own account

**Comment by nijel** [comment]
The audit log retention can be configured already, see https://docs.weblate.org/en/latest/admin/config.html#auditlog-expiry

**Comment by Aikatsui** [comment]
Thank you however it might be good to have user side option for both on-premise and hosted instances. In this case, some are may completely disable it and others will get benefit from it.

**Comment by nijel** [comment]
I don't think it's reasonable to have this a user configurable. In many cases, there is a legal requirement to keep such logs.
