### ISSUE TITLE
Clickable sorting in browse mode

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#5538]
**Is your feature request related to a problem? If so, please describe.**

The browse mode (for example https://hosted.weblate.org/browse/weblate/application/cs/) allows to customize ordering by clicking on a dropdown. It would be more user-friendly to allow sorting by clicking on columns as well. This would support only subset of available options, but still would be useful.

**Describe the solution you'd like**

Sort arrow next to currently applied column ordering (which might be none) and clickable column headers to change ordering.

**Describe alternatives you've considered**

The dropdown works well, but people expect table headings to be clickable to reorder entries.

**Comment by comradekingu** [comment]
I would expect it to allow alphabetical sorting, which isn't in the dropdown.

**Comment by nijel** [comment]
There is "Source string" and "Translated string"...

**Comment by comradekingu** [comment]
@nijel Aha. Would have gotten it if it was "Source A-Z"
