### ISSUE TITLE
Large number of glossary entries slow down the loading of strings

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#5545]
The glossary has 70,000 entries, which means that loading strings takes over 6 seconds. Can the glossary search start after loading the string?![image](https://user-images.githubusercontent.com/39633242/109479677-eb776000-7a7a-11eb-998d-9df26ca07243.png)
When I turned off the glossaries, the time went down 1000 msecs

**Comment by nijel** [comment]
Right now this cannot be separated.

The match expression for glossaries is cached, so it should not take that long in the usual case. When the glossary was changed, building of the matcher might take some time, though. Do you observe this with every request or occasionally?

**Comment by tomkolp** [comment]
It happens all the time, in every component.

**Comment by tomkolp** [comment]
I tested it, it works great.
