### ISSUE TITLE
Translation disappeared after branch changed

### ISSUE THREAD

**Issue by pd4d10** [WeblateOrg/weblate#5549]
**Describe the issue**

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

1. Go to [project VCS settings](https://hosted.weblate.org/settings/bytemd/bytemd/#vcs)
2. Change the Repository branch 
3. The previous translations disappeared

**Expected behavior**

Not sure if it's by design. If not, perhaps this is a bug

**Server configuration and status**

https://hosted.weblate.org/

**Comment by pd4d10** [comment]
And it seems don't send a pull request after committed. The previous project [GitTouch](https://github.com/git-touch/git-touch) works fine. Am I missing something in the settings?

**Comment by nijel** [comment]
The translations should be committed to the previous branch. Weblate does commit pending changes and switch to a new branch.

See https://docs.weblate.org/en/latest/admin/continuous.html#pushing-changes-from-weblate for info on configuring pull requests.

**Comment by pd4d10** [comment]
Found [this doc](https://docs.weblate.org/en/latest/vcs.html#pushing-changes-to-github-as-pull-requests), which says we should configure API credentials to send pull requests automatically.

The wired thing is that I seem don't set anything in [the previous project](https://hosted.weblate.org/projects/git-touch/git-touch/), and it just works.

**Comment by nijel** [comment]
The API keys are configured oh Hosted Weblate, you just need to choose GitHub as VCS, see the link I've sent in the previous comment...

**Comment by pd4d10** [comment]
Sorry. Did not notice the difference between `GitHub` and `Git`

Thank you for your patient answer!
