### ISSUE TITLE
Automatic and unwanted status change?

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#5552]
**Issue with translation status of strings not being preserved.**

We already experienced in the past that when we kept the default setting of 24h to commit and Push after commit, in some cases the translations we had in that project/component were all changed from Needs Editing (or else) to Translated.

I our experience this happened mostly (always?) when we were dealing with bilingual file formats, mostly with XLF.

But now we did use the feature for component creation "Translate document" with a ODT file.

We also set the Push after Commit to "off" and set the auto-commit delay to "9999".
![image](https://user-images.githubusercontent.com/26718215/109643087-0d90e100-7b54-11eb-9cc2-431f1b45f3a5.png)

Nonetheless, this morning all strings for all languages were set to "Translated".

**Note**

1) Review is enabled for this component/project
2) Even when I revert the status to Needs Editing with Bulk Edit for a language, the status is immediately reverted back to Translated, when I launch the Bulk Edit for the next language.

Please let me know if you need further info/detail.

**Comment by ilocit** [comment]
It doesn't have to do with auto-commit, apparently, because the changes are still pending:
![image](https://user-images.githubusercontent.com/26718215/109643586-b63f4080-7b54-11eb-9255-1c23f1210de5.png)

**Comment by nijel** [comment]
Setting the commit age to high value doesn't disable committing changes, it happens on other situations as well, see https://docs.weblate.org/en/latest/admin/continuous.html#lazy-commit

The ODT format cannot store state, so my guess would be that it's related to committing changes and Weblate didn't properly keep the needs editing state while it should.

**Comment by ilocit** [comment]
That might be one of the reasons, but as I wrote, it happend / happens also with XLF and there is a state and an approval flag in the XML structure.
