### ISSUE TITLE
Upgrading to 4.5 breaks the ability to add source strings to components via the REST API

### ISSUE THREAD

**Issue by superDross** [WeblateOrg/weblate#5558]
**Describe the issue**

Upon upgrading our Weblate instance to 4.5 we found that we received a new error when adding source strings to newly created components that utilise monolingual po files via the REST API:

```
b'{"detail":"Can not add unit"}'
```

**To Reproduce the issue**

First create a monolingual component with a template that can be edited:

```py
kwargs = {
    "headers": {
        "Accept": "application/json",
        "Authorization": "Token my-key",
    },
    "files": {"docfile": 'msgid ""\nmsgstr ""\n'},
    "data": {
        "file_format": "po-mono",
        "edit_template": True,
        "filemask": "*.po",
        "name": "test_component",
        "repo": "local:",
        "slug": "test_component",
        "vcs": "local",
        "source_language": "en",
    },
}

requests.post(url="http://weblate:8080/api/projects/dragoman/components/", **kwargs)
```

Then try to add source string to the unit:
```py
kwargs = {
    "headers": {
        "Accept": "application/json",
        "Authorization": "Token my-key",
    },
    "json": {"key": "new_source_string", "value": ["new_source_string"]},
}

requests.post(
    url="http://weblate:8080/api/translations/dragoman/test_component/en/units/",
    **kwargs
)
```

**Solution**

We have to add `manage_units` to our kwargs when creating a component via a POST request to allow us to add source strings with Weblate 4.5:

```
{
  ...
  "data": {
    "manage_units": True,
    ...
  },
}
```

We found that this was due to a change in `check_manage_units` which introduced a new conditional as part of commit `d2577116733`:

```py
if not component.manage_units or (template and not component.edit_template):
    return False
```

This alteration essentially creates a breaking change when using pre-existing API calls. We are under the assumption a breaking change was not intended here and perhaps the above conditionals logic is mistaken?

**Expected behavior**

The alteration in 4.5 does not break existing behaviour; creating a comonent with `edit_template` set to `True` is enough to allow source strings to be edited or added.

**Comment by nijel** [comment]
It was intended to work without a change, but the code doesn't work as expected. Investigating.
