### ISSUE TITLE
Components discovered don't pull changes if main component are not updated

### ISSUE THREAD

**Issue by Shide** [WeblateOrg/weblate#5561]
**Describe the issue**

I've created a component connected to Bitbucket, added the SSH key to the push/pull user, branches and URLs are ok and all the workflow goes well with this single component.

I've installed the *Component Discovery Addon* from a component that I think will never dissapear. This is because I have another 100 components to track. All Component Discovery Addons are linked to the main Component weblate repo.
Component discovery goes well and creates all the other components correctly, but:

Assume we have this structure:
```python
lang_folder / en / component_1.php # This is the main component (source lang = en (monolingual)) */
lang_folder / en / component_2.php # Component created by Component Discovery Addon
lang_folder / fr / component_1.php # new lang of component 1
lang_folder / fr / component_2.php # new lang of component 2
```

When I push a change into `lang_folder / en / component_1.php` (the main component), all goes well. All structure are pulled and all new source strings are created on components.
But, when I push to `lang_folder / en / component_2.php` (component created by Component discovery) nothing happens. 
I think that new components created by Component Discovery are linked to the main component. 
And if this main component is not updated on a git push, this will not trigger the repo pull (repo pull updates other linked components).

**I already tried**

I've tryied to 
- Activate the _Clone addons from the main component to the newly created ones_ option on the Component Discovery
- Batch editing to change Source code repository to set the real repo on all Discovered Components

**To Reproduce the issue**

1. Configure PUSH / PULL automation for Bitbucket.
2. Create component
3. Add Component Discovery Addon and Configure it properly (this will create a discovered_component component)
4. Add new string in discovered_component outside Weblate and push it to GIT
5. Nothing happens

**Expected behavior**

If I push to a folder that is a Discovered Component in Weblate, I expect to see the changes done in the repo as well.
Components discovered should be updated if any changes are pushed to the server and not only when main componet are updated/affected

**Screenshots**

**Exception traceback**

**Server configuration and status**

Weblate installation: Docker

Weblate Version: 4.5

**Weblate deploy checks**

**Additional context**

**Comment by nijel** [comment]
It should update all linked components. Do you see any errors in the Docker log on the update?

In case there was an error in one of the components it might be addressed by 3aa09a9315dc7fdce1c7a6819d467162d31d9912.

**Comment by Shide** [comment]
It seems like in order to discover new components, the component must be placed on the main language folder.
Assuming `lang_folder / en /` is my main language folder, if I add a new file in `lang_folder / fr / new_file.php`, Component Discovery don't see the changes because there is no new file in main language folder.

Is it correct?

**Comment by nijel** [comment]
> Log doesn't show any errors. The process completes as usual.

So it goes through all the components?

> Component Discovery don't see the changes because there is no new file in main language folder.

I have no clue how your discovery is set up, but generally, it should not matter which language it is.

**Comment by Shide** [comment]
Well, my weblate instance is working as I have explained. 
I can deal with this way of working. I will always create the files in source lang folder first.

Thanks Nijel!
