### ISSUE TITLE
How to Import Different Files into one component.

### ISSUE THREAD

**Issue by graebertshiva** [WeblateOrg/weblate#5572]
Hi,

i have 2000 different Files. i want them to import in one translation component. how can i do that?

right now i can able to import only one type of file due to restriction of FileMask.

"Path of files to translate relative to repository root, use * instead of language code, for example: po/*.po or locale/*/LC_MESSAGES/django.po."

**Comment by nijel** [comment]
Use [Component discovery addon](https://docs.weblate.org/en/latest/admin/addons.html#component-discovery) for that.

**Comment by graebertshiva** [comment]
Ops. It has created several other translation component in linked with one Main component.

and Main Component still has same config with one file and showing translation for one file. i have tried to change setting but i can not due to "Monolingual translations".
![Screenshot from 2021-03-04 14-25-00](https://user-images.githubusercontent.com/54701590/109938210-c7738300-7cf5-11eb-84a7-f84f4c4dd29e.png)

**Comment by nijel** [comment]
That's expected - see https://docs.weblate.org/en/latest/user/basic.html

**Comment by comradekingu** [comment]
@graebertshiva I think you can get it done if you make one big component with all the files as for case of argument a separate entity, and then turn on sharing between them?

**Comment by nijel** [comment]
> its allowing me to select only one file.

That's expected - see https://docs.weblate.org/en/latest/user/basic.html
