### ISSUE TITLE
False-positive check for duplicated words

### ISSUE THREAD

**Issue by urbalazs** [WeblateOrg/weblate#5576]
**Describe the issue**

If the translation contains the string \`\`#\`\` (double backticks, hashmark, double backtics), the following check is displayed:

```
Text contains the same word twice in a row: ``
```

**To Reproduce the issue**

1. Create a translatable string like:

   ```
   Remove the comments (``#`` characters) from the beginning of the lines.
   ```
   
2. Add a translation for this string, where the translation contains \`\`#\`\` as is, like.

   ```
   Távolítsa el a megjegyzéseket (a ``#`` karaktereket) a sorok elejéről.
   ```
   
3. See the failing check about duplicated word.

**Expected behavior**

No warnings about failing checks.

**Screenshots**

You can see the issue in production here: https://translate.otrs.com/translate/otrs-7/administration-manual/hu/?checksum=b292f20c38c03b6c

This is Weblate 4.3.2, but I have no possibility to check the issue in newer version. If the issue was fixed in the newer versions, feel free to close this report.

**Comment by urbalazs** [comment]
Hi @nijel, I found a similar issue (or a regression?) in 4.5.2-dev. See this check: https://hosted.weblate.org/translate/po4a/po4a/hu/?q=has:check
Here, the `%s` has marked as duplicated words. However, the quality check is right, the `%s` is duplicated indeed. But this (and `%d`, `%i`, `%u`, etc.) is a common placeholder and can exist in many translation sources. You should consider to use an exception list in this case.

**Comment by nijel** [comment]
Most likely it was triggered before and was not yet updated after the fix has been deployed...
