### ISSUE TITLE
Provide badges per component

### ISSUE THREAD

**Issue by mkochenough** [WeblateOrg/weblate#558]
When e.g. going to https://hosted.weblate.org/projects/phpmyadmin/master/de/ the german translation of phpmyadmin has 100% completion. But in the upper right corner it says 79%.

First I thought this is the completion of all languages cumulated together. But https://hosted.weblate.org/projects/phpmyadmin/master/ says that is currently 47%.
##

**Comment by burner1024** [comment]
Second this. The only way to get translation propagation is to stuff components together into a single project, even if they are not exactly dependent on each other. However, the result is that translation progress tracking is combined.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by burner1024** [comment]
New badges are present and usable from as direct links, but on component page in the upper right corner, it still displays the whole project badge.

**Comment by nijel** [comment]
Thanks for spotting, fixed in 7b42f539d
