### ISSUE TITLE
Comment and explanations when adding to the glossary.

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#5580]
**Is your feature request related to a problem? If so, please describe.**

When adding a new entry to the glossary, it is not possible to add an explanation and comment. 

**Describe the solution you'd like**

A field could be added to enter a comment and explanation.

**Comment by comradekingu** [comment]
This is the one thing Crowdin is good at. Can someone screenshot the UI from there?

**Comment by tjhietala** [comment]
[Transifex also has the part of speech selection](https://docs.transifex.com/glossary/adding-terms), but I don't know what format it uses internally. You can download the glossary as a CSV file, though.

**Comment by nijel** [comment]
We currently don't have any use for part of speech. Without that, it's not useful to collect such information (and users will not be motivated to fill it in correct).
