### ISSUE TITLE
Saving a new Glossary entry takes a long time - like 10 seconds...

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#5584]
When you translate a string and create a new Glossary entry, saving the PopUp with the new terms takes about 10 seconds....
![image](https://user-images.githubusercontent.com/26718215/110097151-014c9400-7d9f-11eb-9495-0fa78d80002d.png)
Perhaps in a later release the performance of this module can be improved?

**Comment by ilocit** [comment]
Plus, I now noticed that you choose "**Zeichenketten**" rather than "**Zeichenfolgen**" in Weblate. So I changed this Term entry accordingly.

**Comment by nijel** [comment]
Duplicate of #5418
