### ISSUE TITLE
Glosbe automatic suggestion failing

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5598]
![bilde](https://user-images.githubusercontent.com/13802408/110200972-0a059e80-7e61-11eb-90f5-534015f5ea54.png)

String in English: https://hosted.weblate.org/translate/weblate/javascript/nb_NO/?checksum=6f3f150333c5bd6c
>The request for machine translation using %s has failed:

Reproduce by opening any string with the auto-translation tab open

https://hosted.weblate.org/translate/weblate/javascript/nb_NO/?checksum=6f3f150333c5bd6c#machinery

**Comment by nijel** [comment]
See https://glosbe.com/help/api:

> Due to the long lasting DDoS attack to the Glosbe API from millions of IPs we have to shut down the service.
>
> It will be closed until further notice. Sorry for the inconvenience.

I'm disabling it on Hosted Weblate.
