### ISSUE TITLE
Pending tasks: Notify responsible translators if source strings modified

### ISSUE THREAD

**Issue by Aikatsui** [WeblateOrg/weblate#5602]
**Is your feature request related to a problem? If so, please describe.**
This isn't frequent use case but has considerable outcome. most small and large projects maintainers do that randomly then old translation remain months, years without change or some projects try to contact translators privately often. So as solution display modified strings list under pending task tab.

![image](https://user-images.githubusercontent.com/63988538/110229799-98038700-7f3e-11eb-8cd7-391a9fe91372.png)
https://crowdin.com/project/gitlab-ee/activity_stream (User interface sample only, not the activity_stream  feature)

**Describe the solution you'd like**
https://github.com/WeblateOrg/weblate/issues/5532 (in user profile)

**Comment by nijel** [comment]
With auto-watch in place (see 3dd0a93dd978d3edb8eb11355027906867b15b95 and #4866), everybody who translated a string will start watching a project and will get notifications on strings to translate.

**Comment by comradekingu** [comment]
@Aujatsui In https://hosted.weblate.org/accounts/profile/#notifications__2 there are specific settings for projects the user in question administrates.
If I understand you correctly you want admins to be notified of string-changes and suggestions automatically.

Not sure what the default settings are, maybe you can screenshot them if you haven't changed anything there?

**Comment by Aikatsui** [comment]
>If I understand you correctly you want admins to be notified of string-changes and suggestions automatically.

No. not it.

This's a example.

- You're the remmina admin and maintain the project
- I'm one of translator and has translated 100 strings for specific language 
(once user started to translate then auto adds to watched projects)
    - meanwhile you modify certain(translated) source string e.g. copy --> copy & delete then as mentioned above i am responsible for the recent translation so i need notification about it
    
In this page https://hosted.weblate.org/accounts/profile/#notifications__1 (watched projects)
Has a setting called "changed string" under translation notification 

I couldn't find more details https://docs.weblate.org/en/weblate-4.5.1/user/profile.html?highlight=watched%20projects#notifications
1. Does it use to notify such modifications?
(If for it, but it's disabled by default then need to be enabled instead and set as permanent without let users to configure)
2. I expect this tracked on web-interface within this component https://github.com/WeblateOrg/weblate/issues/5532 (pending tasks)
(Above provided UI design sample and task details necessary remain until anyone address it) email notification sometimes miss or forget.

**Comment by comradekingu** [comment]
@Aikatsui
If you contribute to a project, it ends up as a watched project now.

As for what settings are the defaults for
[Other projects](https://hosted.weblate.org/accounts/profile/#notifications__0), [Watched projects](https://hosted.weblate.org/accounts/profile/#notifications__1), [Administrated projects](https://hosted.weblate.org/accounts/profile/#notifications__2) it all depends on what the site admin has set up (not me).

The user should always be able to change notifications. If you don't do that you end up with the same problem as sending out too much by default. The e-mails get blocked, and the e-mail account gets blocked because of it.

Since getting immediate notifications and digests per e-mail of string changes already works, I think this can be closed in favour of the "TODO" list on the actual instance https://github.com/WeblateOrg/weblate/issues/5532

**Comment by Aikatsui** [comment]
No. you may misunderstood and this's a separate feature request.

If it exist already as mentioned on (https://github.com/WeblateOrg/weblate/issues/5602#issuecomment-792416029) 1-2 then I mean move(merge) this part as new feature design to,
or add this facility to proposed "pending tasks" #5532 component, when such change happened in any contributed project then it appear on responsible translators profiles as a task next they can start to work on it first

**Comment by nijel** [comment]
0cef5afa747a97a9cb3d0fa633756f2c2739da8e adds the notification flow for source changed event. This will be visible on the UI once pending tasks view (#5532) or notifications on website (#6569) are implemented.
