### ISSUE TITLE
 bad magic number in 'weblate.permissions'

### ISSUE THREAD

**Issue by jmanaks1** [WeblateOrg/weblate#5613]
Hi team,
We encountered an issue while migrating from an old instance of weblate.

 

**Describe issue**
ImportError: bad magic number in 'weblate.permissions': b'\x03\xf3\r\n'

 

**Steps to replicate**
1. Migrate data from old instance to new instance
2. Configure settings.py with our new configuration
3. Merge INSTALLED_APPS from old instance of weblate to new instance of weblate
4. Run:
```python manage.py migrate```
5. Run:
```python manage.py loaddata old_data_base.json```
6. Error occurs here: ImportError: bad magic number in 'weblate

 

The old_data_base.json file was generated by running:
```python manage.py dumpdata --all --natural-foreign --natural-primary --indent=4 > old_data_base.json```

 

Is migration possible from Weblate 3.1.1 to latest version (Weblate version 4.5)?
If yes, could you please redirect us to a resource showing this.

Thank you!

**Comment by nijel** [comment]
Remove stale pyc files (see https://stackoverflow.com/a/49394405/225718) and update the `settings.py`.

AFAIK the JSON dump cannot be imported into a different version, the database structure has to match. See https://docs.weblate.org/en/latest/admin/backup.html for recommendations on backup and server migration.

**Comment by festugreat** [comment]
Hello.
Kindly stop sending me all these emails,effect from now.
Thanks.
