### ISSUE TITLE
New source strings are not showing in Weblate, even though the repository on Weblate is up-to-date

### ISSUE THREAD

**Issue by sct** [WeblateOrg/weblate#5615]
**Describe the issue**

Strings are not updating to the latest source strings. The repository is out of date even though, as far as I can tell, everything in Repository maintenance says we are up to date?

**I already tried**

I have tried rebasing but a server error is thrown. I tried resetting, and a server error is also thrown there. It says in the history the reset worked, but there are still no new strings.

**To Reproduce the issue**

This issue seems specific to our repository: https://hosted.weblate.org/projects/overseerr/overseerr-frontend/

There are strings in the source files that are not present in Weblate.

**Expected behavior**

We should see the new strings being added.

**Exception traceback**

Server Error
The server had serious problems serving your request. Trained monkeys are en-route fixing the issue.

If you need assistance, you may reference this error as 291b434bb6c04f0b9bf310d92f4396e2.

**Server configuration and status**

Weblate installation: weblate.org service

**Additional context**

It's been like this for 3 days. We have added plenty of new strings but none of them want to show up. Not sure what to do.

**Comment by nijel** [comment]
Fixed in 8755b80da290, the fix will be deployed today to the Hosted Weblate.
