### ISSUE TITLE
MINOR: Clicking on <untranslated word link> in Translation Overview for Glossary component links to Browse not Translate 

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#5619]
When you click on the number of untranslated words, this usually takes you to the **Translation** screen, but for **Glossary** components, it opens the **Browse** view.

Click here:
![image](https://user-images.githubusercontent.com/26718215/110504474-7dc3d780-80fd-11eb-9030-e82333c36cac.png)

Takes you to:
![image](https://user-images.githubusercontent.com/26718215/110504497-83212200-80fd-11eb-9e39-d83f08649677.png)

Would expect this:
![image](https://user-images.githubusercontent.com/26718215/110504578-98964c00-80fd-11eb-8a60-d98e85d2589b.png)

**Comment by nijel** [comment]
The glossaries default to browse view as that was more expected outcome. I'm not sure if it's a good idea to use a different target for not translated strings...

**Comment by ilocit** [comment]
Well, but that behavior makes it impossible to translate a bunch of Glossary entries in one go.
You will always be presented the Browse view and when you click on one entry there, it takes you to that exact entry at its position within that string list. The next one without a translation might not be the next one in that set. So you need to go back and start over. 
The same happens when you click on **Not translated strings**. 
![image](https://user-images.githubusercontent.com/26718215/110511003-10677500-8104-11eb-9039-6aef0c081b95.png)

Why would a Glossary component behave different from a regular component in terms of "translatability"?

**Comment by comradekingu** [comment]
I've seen some projects run their one component as a glossary one with all actual strings in it.
Don't know if that is meant to be a thing.

**Comment by nijel** [comment]
> Well, but that behavior makes it impossible to translate a bunch of Glossary entries in one go.

You can click on any string and start translating (the search query will be preserved since 2a850247644af164220aed74d411c37dba76b6f5). It's an additional click, but I believe the browse view is expected in most cases. If you want a different one, you can get it from the overview as well:

![obrazek](https://user-images.githubusercontent.com/212189/111684380-f1b15e80-8826-11eb-8288-90a0a8c972d0.png)

**Comment by ilocit** [comment]
Not on my installation. Also clicking on the links in the overview always takes me to **Browse**, even though there is the **Browse** link to the right, as in other components.
Also the "preserving" does not seem to apply after "browse", since I am always taken to the one sting in the sequence when I click on it in the **Browse** view.

Perhaps we misunderstand each other here? Not sure. Maybe I will do  a screen recording and share it to illustrate what I mean.

**Comment by nijel** [comment]
> Not on my installation.

I think it's not yet released, it will be in 4.5.2.

**Comment by nijel** [comment]
Closing this as fixed for 4.5.2. I don't think that it's a good idea differentiate target here based on the action.
