### ISSUE TITLE
Source files from newly created components are malformed

### ISSUE THREAD

**Issue by superDross** [WeblateOrg/weblate#5620]
**Describe the issue**

The source translation file from new component configured with monolingual po file format seems to be malformed. After downloading it from the UI (or the API via `http://localhost:8080/api/translations/<project>/<comp>/en/file/`) I am presented with a file the looks like this:

```po
msgid ""
msgstr "X-Generator: Weblate\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit"
```

It looks as though the metadata has malformed into a msgstr.

One other thing to note is the `add new translation string` button is also missing from this newly created components source translation page. I am not sure if this is intentional so have not created a separate issue (happy to do so though):

![issue_gh](https://user-images.githubusercontent.com/16519378/110508869-6682eb00-80f9-11eb-9193-0bff5d3ebb72.png)

**I already tried**

Conversely, when downloading the source file by converting to po, we find it looks correct (`http://localhost:8080/api/translations/<project>/<comp>/en/file?format=po`):

```po
msgid ""
msgstr ""
"Project-Id-Version: English (Dragoman)\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-03-09 16:53+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: English <http://weblate:8080/projects/dragoman/a0/en/>\n"
"Language: en\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Generator: Weblate 4.5.1\n"
```

However we are interested in manipulating the original po file.

**To Reproduce the issue**

1. Go to create a new component
2.  Select "from scratch" using monolingual po file format
3. Navigate to the newly created component and click on the source language
4. Click Files -> Download Translation or via the API `http://localhost:8080/api/translations/<project>/<comp>/en/file/`

**Expected behavior**

For the file to not be malformed; contain the metadata outwith the msgstr as expected.

**Comment by nijel** [comment]
I don't see anything malformed. Lines are not wrapped and I guess this is caused by gettext customization addon you are using.

**Comment by superDross** [comment]
Thanks for the quick response. I'll do some digging into this.
