### ISSUE TITLE
Make information drop down in top menu configurable

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#5627]
Weblate has a help/support drop down in the top menu, currently (v4.4.2) looking as following:

![image](https://user-images.githubusercontent.com/8058166/110640611-4ca4df00-81b1-11eb-961c-9862ad394ae7.png)

The lower entries are fine and are Weblate specific as:
- About Weblate
- Documentation
- Contribute to Weblate
- Donate to Weblate

The upper part heavily depends on the installation of Weblate:
- Support
- Contact

Where the default values / links behind those two entries are surely ok for hosted.weblate.org. This might not be suitable for a self-hosted situation.

### Proposal / Solution Approach

Introduce feature toggle and configuration options to be controlled by environment variables as following

```py
WEBLATE_HELPMENU_SUPPORT_ENABLE = True / False # Default is True
WEBLATE_HELPMENU_SUPPORT_LINK = https://myawesomesupportpage.com  # Default is as today https://weblate.org/support/
WEBLATE_HELPMENU_CONTACT_ENABLE = True / False # Default is True
```

(This requires correct mapping in [settings-docker.py](https://github.com/WeblateOrg/weblate/blob/master/weblate/settings_docker.py))

This allows to define a specific support endpoint for the self-hosted case and to switch on/off the contact form.

### Exclusion

The request above is intentionally not asking for a fully flexible configurability, what could allow to add more menu entries or altering the current entries as already given. Reason for this is that the current entries (link names) are nicely translated and any addition / change in a sense of local customization wouldn't.

**Comment by comradekingu** [comment]
Not suitable why?
You want to look for someone to ask questions, there is your local site admin contact field.
If not, there is the paid support.

When is turning that off good? I suppose if there is a support subscription it could replace one or more of those.

**Comment by rhofer** [comment]
In my self-hosted use case "support" means to get connected to people who now why the projects and components are set-up exactly that way and how our internal translation process and workflow works. It is not about infrastructure support, this I'd expect from Weblate as paid service. Therefore, the link behind "support" must be configurable.

This "support" link will lead people from my scope to a specific landing page, where we show, who is responsible for which domain and how to interact. Same for infrastructure matters. Otherwise, my colleagues end up in my self-hosted weblate instance and are wondering where the internal documentation is. My special process settings, rules and guidelines are needed from my point of view, since weblate is not yet "enterprise ready". And yes, there is support subscription what covers tooling and infra support, as supposed.

Therefore, enable/disable support link is not required, but configuring the link, this is.

The contact form I'd like to disable since contact should be created via the configurable support link and I only want to receive email from transactions. (Remark: the way the contact form is sending email, is not working in my set-up > another reason why I want to disable it.)

**Comment by ilocit** [comment]
I support @rhofer on this one. Would like that too. Same reasoning.
Difference between "Support" for Weblate by the Weblate team/community vs. support given to the team working on a specific project / component. External (to us) resources click on Support in order to reach us and get support with a project related matter. You might argue that they should use the comment feature or other ways within the Weblate project/component setup, but they don't always do.
