### ISSUE TITLE
Add gitee for authentication

### ISSUE THREAD

**Issue by Aikatsui** [WeblateOrg/weblate#5629]
**Describe the solution you'd like**

https://gitee.com/api/v5/oauth_doc#/

**Comment by nijel** [comment]
This should be added to python-social-auth, Weblate does not implement authentication methods itself. Please report the issue at https://github.com/python-social-auth/social-core

**Comment by Aikatsui** [comment]
https://github.com/python-social-auth/social-core/issues/574

**Comment by Aikatsui** [comment]
> [python-social-auth/social-core#574](https://github.com/python-social-auth/social-core/issues/574)

@nijel may i know why this issue closed? i asked reason but no response for 9 days

**Comment by nijel** [comment]
Sorry, I have no clue...
