### ISSUE TITLE
Laravel PHP strings adds extra content to source lang keys

### ISSUE THREAD

**Issue by Shide** [WeblateOrg/weblate#5633]
**Describe the issue**

Creating a Component from a Laravel PHP string adds the `return ->` (if php contains `return array(`) or `return[]->` (if php contains `return [`) to the key string.

**I already tried**

I've tryied changing all combinations of selecting:
- Change file format to `PHP strings` or` Laravel PHP strings`
- Edit the file return to `return array(` or `return [`
- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.

**To Reproduce the issue**

1. Go to the [weblate documentation page for laravel strings](https://docs.weblate.org/es/latest/formats.html#laravel-php-strings), copy the example Laravel string, put it on a file and call it `as_wb.php` for example.
2. Create a new component on an existing project selecting `Translate document` option (same issues with git repos, etc), upload your document and choose traslation file suggestion (**File format `Laravel PHP strings`, Filemask `as_wb/*.php`**)
3. Save and continue with default settings and wait weblate import strings.
4. Check source translation (key)

**Expected behavior**

This key should be only **welcome**.

**Screenshots**

![weblate_laravel_import_error](https://user-images.githubusercontent.com/1162050/110773210-c6de6d80-825c-11eb-8977-cf390dac220a.png)

**Exception traceback**

**Server configuration and status**

Weblate installation: Docker + Weblate 4.5

**Weblate deploy checks**

**Additional context**

Original file was `as_wb.php` and contains:
```php
<?php
return [
    'welcome' => 'Welcome to our application',
    'apples' => 'There is one apple|There are many apples',
];
```

Pushing to GIT is ok, works well and builds files correctly.
Plurals also are well imported.

Also, exporting language to other formats (like JSON), changes the source of the strings making impossible migration to other formats (I've selected JSON for the code):
```json
{
    "return[]->'welcome'": "Welcome to our application",
    "return[]->'apples'": "There is one apple"
}
```
![exporting_to_other_file_formats](https://user-images.githubusercontent.com/1162050/110774235-dca06280-825d-11eb-94cd-864108df4a1c.png)

**Comment by nijel** [comment]
The Laravel parser adds only a thin layer on top of the generic PHP parser to support plurals, and it uses generic keys to be able to reconstruct any of the supported PHP syntax (see http://docs.translatehouse.org/projects/translate-toolkit/en/latest/formats/php.html).

Anyway this would have to be addressed in the translate-toolkit.
