### ISSUE TITLE
Use of translated Python Docs pages in translated Weblate Docs

### ISSUE THREAD

**Issue by rffontenelle** [WeblateOrg/weblate#5634]
Python Docs has a translation project and I would like, if possible, to link its translated pages when translating strings in Weblate Docs.  While it would be easy to adjust a URL in the translation string, I can't say the same of a ```:ref:`<name-of-a-link>` ``` RST syntax.  In the latter case, not using the correct link name would generate sphinx warnings or error (if sphinx-build's `-W` flag is used) messages.

For instance, ```Look at similar strings translated in past, see :ref:`memory`.``` in [docs/user/translating.rst in line 269](https://github.com/WeblateOrg/weblate/blob/master/docs/user/translating.rst#L269) which currently links to

https://docs.python.org/3.7/c-api/memory.html#memory

and I would change to

https://docs.python.org/pt-br/3.7/c-api/memory.html#memory

Any idea on how to allow to use translated pages of Python Docs?

**Comment by nijel** [comment]
Hmm, this particular link should point to the Weblate docs, that is fixed in ea77e2231afbe613bb5187ebeddaacede1c882fe. This would ideally be addressed in Sphinx (such reference should fail the docs build), see https://github.com/sphinx-doc/sphinx/issues/2068.

Back to your original question - the only way is to add all localized versions to our interpshinx configuration and then use these in the links. The links to Python docs currently should be done as:

```
:ref:`python:target`
```

**Comment by rffontenelle** [comment]
> Hmm, this particular link should point to the Weblate docs, that is fixed in [ea77e22](https://github.com/WeblateOrg/weblate/commit/ea77e2231afbe613bb5187ebeddaacede1c882fe). This would ideally be addressed in Sphinx (such reference should fail the docs build), see [sphinx-doc/sphinx#2068](https://github.com/sphinx-doc/sphinx/issues/2068).

Sweet.
 
> Back to your original question - the only way is to add all localized versions to our interpshinx configuration and then use these in the links. The links to Python docs currently should be done as:
> 
> ```
> :ref:`python:target`
> ```

Do you mean e.g to add "python-pt-br" to conf.py, so the pt_BR translator use "python-pt-br" instead of python in the `:ref:` ?

**Comment by nijel** [comment]
Yes, that would be needed. The problem is that this would have to be done for every language, so it doesn't really scale well...

**Comment by rffontenelle** [comment]
Nah, It really doesn't. Let's leave as it is.. Thanks!

**Comment by nijel** [comment]
Hmm, it should be possible to change the target based on the documentation language. I've tried to implement this in b95369149409597b74075db8cf56d0b1b3289828, not sure if that will work (it needs to be built on the Read the Docs to see actual result).

**Comment by rffontenelle** [comment]
A little bit late, but just for the record: I've tested and URLs for Python, Django etc. are displayed translated. Thanks!
