### ISSUE TITLE
Consistency check is wrong

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#5645]
I'm seeing some quality checks which inform that there's a consistency problem but when I'm looking at the other occurences and they are all identical.

This is where I've encountered this error:
https://hosted.weblate.org/translate/weblate/website/he/?q=has:check#others

A relevant screenshot in case it'll change:
<img width="1418" alt="Screen Shot 2021-03-13 at 17 33 06" src="https://user-images.githubusercontent.com/406826/111035306-8597ba80-8422-11eb-92ad-cdd5542080c1.png">

**Comment by nijel** [comment]
Might be related to automatic translation, needs more investigation...

**Comment by yarons** [comment]
Indeed, thats in your court though :)
