### ISSUE TITLE
New language notification for adding language as well

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#567]
Currently new language notification is fired only when project does not support automatic adding of translations. However it might be useful just to get notification even if the language can be added automatically.
##

**Comment by ksn0w** [comment]
Hello! I can help to fix this, where can I start to help?

**Comment by nijel** [comment]
Basically the notification has to be hooked into [SubProject.add_new_language](https://github.com/WeblateOrg/weblate/blob/master/weblate/trans/models/subproject.py#L1514)

**Comment by kishan3** [comment]
Hi I am not able to push changes to a new branch any idea why ?

**Comment by nijel** [comment]
On Weblate repo? You should [fork it first](https://help.github.com/articles/fork-a-repo/).

**Comment by Naruto0** [comment]
Hi Michal, the path https://github.com/WeblateOrg/weblate/blob/master/weblate/trans/models/subproject.py#L1514 is not valid anymore.

**Comment by nijel** [comment]
Yes, it's here (this time I'm using permalink): https://github.com/WeblateOrg/weblate/blob/6c5e37569aa5d23d030ec294ed92f7f481dfc5ad/weblate/trans/models/component.py#L1478

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
