### ISSUE TITLE
Security bug: User is able to see language statistics even no role is granted

### ISSUE THREAD

**Issue by tibormarchynzoom** [WeblateOrg/weblate#5673]
**Describe the issue**

When you have user which does not belong to any group, any role and does not have any permission, he is still able to navigate to `Languages -> Browse all languages` and see all currently used languages on Weblate server.

**I already tried**

N/A

**To Reproduce the issue**

1. Create any user
2. Ensure that user does not belong to any group, any role or any project (even not Viewers or Users)
3. Navigate to `Languages -> Browse all languages`
4. languages are listed
 
**Expected behavior**

Languages must not be listed

**Screenshots**

![weblate_user_without_permissions](https://user-images.githubusercontent.com/41163136/111305657-84030800-8657-11eb-91fb-dbe1841bd4ee.png)

**Exception traceback**

N/A

**Server configuration and status**

Weblate 4.5.1

**Weblate deploy checks**

N/A

**Additional context**

N/A

**Comment by nijel** [comment]
This is [documented behaviour](https://docs.weblate.org/en/latest/admin/access.html#project-access-control):

![image](https://user-images.githubusercontent.com/212189/111308194-aba79f80-865a-11eb-88e1-f74f0c4fc147.png)

**Comment by tibormarchynzoom** [comment]
thanks, but don't you think it's wrong to show those data? especially if you really want to keep your environment secure.

**Comment by nijel** [comment]
If you don't want users to have access to any data in Weblate, don't let them register. Registered users will always be able to get some information from the service. The current scope is merely caused by implementation, and is documented.

**Comment by comradekingu** [comment]
@tibormarchynzoom How do you think it is wrong to show that data?
In my view it is a great feature, not a "security bug"…
