### ISSUE TITLE
Different spellcheck dictionaries for target and comment text boxes

### ISSUE THREAD

**Issue by rffontenelle** [WeblateOrg/weblate#5676]
**Is your feature request related to a problem? If so, please describe.**

Firefox allows more than language to be spell-checked with its spellcheck dictionaries (going to use "dict" from now on), but uses the only one selected (not all together) per "context". By "context" (which I'm not sure what is, technically speaking) I mean that I can have English set for Weblate and another language for another website (say, writing in issues text boxes in GitHub); but can't have both languages set simultaneously for Weblate.

When translating in Weblate (in Firefox), I rather use my language dict in the translation ("target") text box, and English dict when writing a comment for the source string.

Currently, the dict used in one box applies to the other. So, I have to switch dict if I want the spellcheck to work properly when e.g. I want to write a comment in Weblate.

**Describe the solution you'd like**

I would like to be able to set a spellcheck dictionary to each of the aforementioned boxes (translation box and comment box), without needing to switch everytime I want to use the spellchecking in them.

**Describe alternatives you've considered**

No alternatives comes to my mind at the moment.

**Screenshots**

Here is a screenshot of the Weblate translation editor, showing the translation box with a text in Brazilian Portuguese, flagged as misspelled by Firefox spellcheck feature with English dictionary set, and the commentary box with text in English, not misspelling flag applied:

![spellcheck-dict](https://user-images.githubusercontent.com/1571783/111323602-cb35cc80-8648-11eb-9eae-0ade3563a35f.png)

**Additional context**

**Comment by nijel** [comment]
I have no clue how to achieve this. The translation textarea has correctly set language, but that seems to do nothing for Firefox spellchecker.

**Comment by rffontenelle** [comment]
@nijel Can you please point me to the file the set the language?

**Comment by nijel** [comment]
It's `lang` attribute on the `textarea`:

https://github.com/WeblateOrg/weblate/blob/693c389b9f0959b7a9b4f5c072108fa2b9a213ae/weblate/trans/forms.py#L299

**Comment by rffontenelle** [comment]
Thanks. Searching for info on firefox+textarea+lang, I found this meta-bag entitled "[meta] Spellchecker fails to honour/remember user's choice of language/dictionary", with some explanation on how Firefox works with lang selecting and some dependency bugs not yet closed: https://bugzilla.mozilla.org/show_bug.cgi?id=1073827#c33

Hope it helps

**Comment by nijel** [comment]
It all seems to relate to site only, not to individual inputs...

**Comment by nijel** [comment]
I don't see anything we could do here - the `lang` attribute on the textarea is set, and it's up to the browser if it will use it or not.
