### ISSUE TITLE
[Hosted Weblate] Parse error in OpenOrienteering/Mapper, due to unexpected new entry

### ISSUE THREAD

**Issue by dg0yt** [WeblateOrg/weblate#5682]
**Describe the issue**

I recceive notifications about a "Parse error in OpenOrienteering/Mapper" (https://hosted.weblate.org/projects/openorienteering/mapper/#history).

I guess this is related to an entry which was added by a Weblate user to the English translation 8 days ago:
https://hosted.weblate.org/translate/openorienteering/mapper/en/?checksum=b091306442f1aef0
This entry is marked as "Translation file: string [pending]"

The project is based on .ts  files (Qt). The English translation is plural-only, and users are not allowed to add source strings. (However there is a separate template file which is en_GB, too).

**I already tried**

With regard to the mentioned entry:
I tried to find an action for removing the entry. 
I tried to find an action to deal with "Translation file: string [pending]" (rejection, acceptance).

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

1. Go to '...' https://hosted.weblate.org/translate/openorienteering/mapper/en/?checksum=b091306442f1aef0

**Expected behavior**

a) UI action to deal with the current state.
b) Prevent users from adding (source) entries to the translation files.

**Server configuration and status**

Weblate installation: weblate.org service

**Comment by dg0yt** [comment]
...and reminders coming every hour since 6:19h today.

**Comment by dg0yt** [comment]
Thanks! :+1:

**Comment by nijel** [comment]
Please note that it has been fixed in the code, the fix will take some time to deploy.
