### ISSUE TITLE
Unreasonable "Inconsistent"

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#5686]
**Describe the issue**

After adding the component and automatic translation, the "Inconsistent" check appeared.
All of the three strings have the status of "approved", and are identical. Automatic translation was over a day ago and the check has not changed. After adding a few components, I have over a hundred such cases.

**Screenshots**
![image](https://user-images.githubusercontent.com/39633242/111520601-8d27ce00-8758-11eb-8b71-9139970b4cf0.png)

**Comment by nijel** [comment]
Do you know what version do you run when the automatic translation did happen? This has been changed recently (in 4cfc99de57130c3f66938b9e43175c120a50427c).

**Comment by tomkolp** [comment]
I already have the version after this change.  Bleeding from this morning.

**Comment by nijel** [comment]
But the question is what version did you run when the automatic translation did happen, you said it was a day ago or something like that.

**Comment by tomkolp** [comment]
It was 100% after the patch, because I immediately noticed a huge increase in the speed of automatic translation.
![Screenshot_20210317-202850](https://user-images.githubusercontent.com/39633242/111527212-f7903c80-875f-11eb-8820-3b54224deb0e.png)

**Comment by nijel** [comment]
Hmm, seems to still happen in some cases: https://hosted.weblate.org/translate/weblate/website/cs/?checksum=8f27538aba795067

**Comment by tomkolp** [comment]
This problem persists with me.  Re-checking in the background takes place after 12-24h and only then it works properly.

**Comment by tomkolp** [comment]
[inconsistency error](https://weblate.eso-spolszczenie.eu/translate/eso-spolszczenie/deshaan-oath-breaker/pl/?q=has%3Acheck&offset=2#others)
15 minutes after the automatic translation, the inconsistency error still occurs.
Docker bleeding version today.
@nijel

**Comment by nijel** [comment]
Any WeblateLockTimeout / ComponentLockTimeout errors in the logs?

**Comment by tomkolp** [comment]
No current errors.
![image](https://user-images.githubusercontent.com/39633242/114550717-ccb3de00-9c62-11eb-9521-787f61c4fa43.png)

**Comment by nijel** [comment]
Ah, I've just discovered yet another race condition in the code, fixed in 75de510915ab0e251b21140df15209470b03478d.
