### ISSUE TITLE
Addon to fill in untranslated strings in a file

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#5692]
By default, all strings in a new translation created by Weblate are empty. The application for which I run a localization site expects untranslated string to be copies of the original English source strings. Is there a way of configuring Weblate to change how it creates new translations?

I also now have a number of translations that contain these empty strings. Can I somehow batch edit those to copy the English source strings for cases in which the translated string is empty?

_Originally posted by @sr258 in https://github.com/WeblateOrg/weblate/discussions/5599_

**Comment by sr258** [comment]
I've looked into the source code to modify the "Remove blank strings" addon for this purpose. As the addon still relies on a specific method in the core, it looks like this feature requires changes in the core. As I'm new to Weblate and also Python, I can't contribute this feature myself.

How much would you ask for developing this addon, @nijel ? You can reach me at serettig@posteo.de

**Comment by nijel** [comment]
I think the better approach would be to start from [Pseudolocale generation add-on](https://docs.weblate.org/en/latest/admin/addons.html#pseudolocale-generation). I've sent you followup to e-mail.

**Comment by nijel** [comment]
Summary provided by @sr258:

- Overall aim: Instead of having empty strings in the files that are pushed to the actual source code repo, the translation files should contain the source strings if there is no translation.
- If the source string is empty (this happens), the translation should also be empty, of course.
- I don't mind if the translations in Weblate appear empty or with a copy of the English source strings. Either is fine.
- Changes in the source string don't need to be propagated to the translations that are created by the addon.
- If possible existing empty translations in components are also filled in when the addon is activated first. There are some partial translations at the moment that have some strings translated and other that aren't. If this is not possible within the timeframe you mention, it is also fine if only new translation files are filled with the empty English strings when they are created.

**Comment by KadAnna** [comment]
Would it be possible for the point "Changes in the source string don't need to be propagated to the translations that are created by the addon." Instead I suggest that it does this:
- If source strings changes, I want the change to also be propagated in the translations that are created by the add-on or alternatively,
- When source string chages, then the translation created by the add-on would be marked as "needs editing"

**Comment by nijel** [comment]
> When source string chages, then the translation created by the add-on would be marked as "needs editing"

This is already the case for all source string edits.
