### ISSUE TITLE
How to view all supported languages?

### ISSUE THREAD

**Issue by neotrak** [WeblateOrg/weblate#5704]
**Describe the issue**

How can i find about all supported languages and writing systems on weblate?

**I already tried**

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.

**Expected behavior**

Details somewhere about all supported languages
eg https://www.transifex.com/explore/languages/

**Comment by neotrak** [comment]
> neotrak added the question label.

this suitable for feature request rather than question

**Comment by nijel** [comment]
The language definitions are at https://github.com/WeblateOrg/language-data/, more info is at https://docs.weblate.org/en/latest/admin/languages.html

The list of currently translated languages is at https://hosted.weblate.org/languages/
