### ISSUE TITLE
Support for INI-Format without section headers

### ISSUE THREAD

**Issue by Somebodyisnobody** [WeblateOrg/weblate#5715]
**Is your feature request related to a problem? If so, please describe.**
I try to import INI-files without containing section headers (e.g. `[foo]`).
Weblate complains about, that no section header was found in the base file. (Screenshots)
I see no need for a header file and as this files are later read in from the target program I cannot just add a section header.
I also tried it with CSV but I cannot enter a custom separator.
**Describe the solution you'd like**

As I fail to see why headers are needed, I suggest to remove the need of headers in ini files. This shouldn't break anything.

**Describe alternatives you've considered**
One alternative would be add a parameter to enter a custom CSV separator.

On my side I've problems to integrate the weblate into the CI-process. As weblate pulls automatically I cannot run a pre-process script, which adds a foo-header nand a post-process script to remove it before pushing.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/35230554/111959408-b8ab0f80-8aee-11eb-8717-3b95b00a9820.png)

**Additional context**
These are the files I want to integrate following files into weblate:
- LanguageDE.txt
- LanguageUS.txt
from https://github.com/legacyclonk/LegacyClonk/tree/master/planet/System.c4g

**Comment by nijel** [comment]
That might work as [Java properties](https://docs.weblate.org/en/latest/formats.html#java-properties) or [Joomla files](https://docs.weblate.org/en/latest/formats.html#joomla).

**Comment by Somebodyisnobody** [comment]
Hmmm okay Java Properties worked but the output filename needs of course to be renamed. I'll see if I can do this via addon.

Nevertheless I still want to suggest to parse ini files without sections. Sections are not needed.

**Comment by nijel** [comment]
The filename is not anyhow linked with the format, whatever you specify will be used.

The section requirement is caused by [iniparse](https://pypi.org/project/iniparse/) library which [translate-toolkit](https://github.com/translate/translate/) uses to parse INI files.
