### ISSUE TITLE
Documentation API status codes

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#5716]
Just a small documentation issue:

The API docs at https://docs.weblate.org/en/latest/api.html?highlight=api#any-- mention only 200 as "OK" status code where at least "201 Created" and "204 No Content" are other 20X "OK-ish" status codes returned by Weblate.

![grafik](https://user-images.githubusercontent.com/3872576/111965439-07a87300-8af6-11eb-8fce-d19bbfff1215.png)

**Comment by nijel** [comment]
Pull requests are welcome to improve the documentation :-). The source file is here: https://github.com/WeblateOrg/weblate/blob/master/docs/api.rst
