### ISSUE TITLE
GitLab fork merge requests pending due to missing pipelines

### ISSUE THREAD

**Issue by remcohaszing** [WeblateOrg/weblate#5718]
**Describe the issue**

We have configured Weblate to create merge requests from a fork. For example, see [appsemble/appsemble!1715](https://gitlab.com/appsemble/appsemble/-/merge_requests/1715). However, the merge requests can’t be merged because the merge request shows a spinner indefinitely. I think [gitlab-org/gitlab#300471](https://gitlab.com/gitlab-org/gitlab/-/issues/300471#note_507981964) is related.

I see 2 possible solutions:
1. Enable pipelines publicly for the fork.
2. Give owners of the original project access to the Weblate fork. This also allows maintainers to further tweak the fork, i.e. change the description / tags / logo. This also allows them to enable pipelines publicly if they desire.

**I already tried**

I tried creating a new account on GitLab, forking the project from that account, and creating a merge request. If I change the merge request visibility to _Everyone With Access_ in the project settings of the fork, I notice the same behaviour as for Weblate merge requests when looking at the merge request as owner of the original project.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

See _**I already tried**_

**Expected behavior**

Weblate forks have pipelines enabled in a way project maintainers of the original project can see it.

**Screenshots**

![image](https://user-images.githubusercontent.com/779047/111983200-2add1d80-8b0a-11eb-820b-ae0491a8bc5f.png)

**Exception traceback**

N/A

**Server configuration and status**

Weblate installation: weblate.org

**Weblate deploy checks**

N/A

**Comment by nijel** [comment]
Do you know which flag needs to be toggled to do this? Is it "builds_access_level"? See https://docs.gitlab.com/ee/api/projects.html#edit-project

**Comment by nijel** [comment]
Also, you can let Weblate push to a different branch in your repository to avoid such problems, see https://docs.weblate.org/en/latest/admin/continuous.html#push-changes

**Comment by remcohaszing** [comment]
Yes, toggling `Pipelines` in the project settings seems to change the `builds_access_level` when I inspect the PUT request made on gitlab.com.

Having Weblate push to a different branch on the main repository has other quirks. I.e. ideally the Weblate branch should be protected from other project members, but then Weblate can’t rebase and force push.

**Comment by remcohaszing** [comment]
That was super fast!

Is there any ETA when this will be available on https://hosted.weblate.org?

**Comment by nijel** [comment]
It should be already there. I'm just not sure if it will update existing forks, feedback on that is welcome.

**Comment by remcohaszing** [comment]
I think existing forks need to be updated. Anyone should be able to access https://gitlab.com/weblate/appsemble/-/pipelines (or the same page for different projects forked by weblate).

**Comment by nijel** [comment]
I think it should be update on creating a new pull request.

**Comment by nijel** [comment]
Ah okay, it does it only when the remote is not yet configured in Weblate... I've changed the repo configuration manually now.

**Comment by remcohaszing** [comment]
Since no pipeline was created yet, I had to close the open merge request and push from the Weblate interface. This created a pipeline for the new merge request (appsemble/appsemble!1731), which can now me merged.

Thanks for your help and fast replies!
