### ISSUE TITLE
Huge input lookup error for large XLF files

### ISSUE THREAD

**Issue by mclei-asw** [WeblateOrg/weblate#5720]
Cannot commit any new translations when XLF file grows to about 32MB.

Tested in versions from 3.10 to 4.5.1

**I already tried**

Searched for the problem and found, that it is a limitation of lxml, which could be bypassed by specifying huge_tree=True when creating the XML parser, but I was not successful.

**To Reproduce the issue**

Steps to reproduce the behavior: Use XLF file larger than 32MB.

**Exception traceback**

In 4.5.1 I get only log lines like:
WARNING Translation parse error: XMLSyntaxError: internal error: Huge input lookup, line 379625, column 1 (<string>, line 379625)
WARNING Failed to parse file on commit: FileParseError: internal error: Huge input lookup, line 379625, column 1 (<string>, line 379625)
ERROR project/xxxxx/cs: skipping commit due to error: internal error: Huge input lookup, line 379625, column 1 (<string>, line 379625)

**Server configuration and status**

Weblate installation: PyPI installed on Debian Buster amd64.

 * Weblate: 4.5.1
 * Django: 3.1.7
 * siphashc: 1.3
 * translate-toolkit: 3.3.3
 * lxml: 4.4.2
 * Pillow: 7.0.0
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 4.1.0
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-filter: 2.4.0
 * django-appconf: 1.0.3
 * user-agents: 2.0
 * filelock: 3.0.12
 * setuptools: 45.1.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.3
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.9
 * weblate-language-data: 2021.3
 * html2text: 2020.1.16
 * pycairo: 1.18.2
 * pygobject: 3.34.0
 * diff-match-patch: 20200713
 * requests: 2.22.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.0
 * Cython: 0.29.14
 * misaka: 2.1.1
 * GitPython: 3.0.5
 * borgbackup: 1.1.10
 * pyparsing: 2.4.7
 * pyahocorasick: 1.4.1
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2-binary: 2.8.4
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.6
 * tesserocr: 2.5.0
 * boto3: 1.11.6
 * zeep: 3.4.0
 * aeidon: 1.6.0
 * git-svn: 2.20.1
 * Redis server: 5.0.3
 * PostgreSQL server: 11.6
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.19.0-6-amd64 (x86_64)

**Comment by nijel** [comment]
Probably the parser in the translate-toolkit needs to be adjusted to include huge_tree=True. Security implications of that should be investigated first, though.

**Comment by mclei-asw** [comment]
Thanks for suggestion. Yes using huge_tree=True in translate toolkit works for me.

**Comment by mclei-asw** [comment]
Reported in translate toolkit: https://github.com/translate/translate/issues/4302
