### ISSUE TITLE
Implement a configuration setting that makes the URL non mandatory

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#5734]
Since Weblate enforces an URL for each project, I specified the URL of the weblate instance itself. This instance runs as https, but uses a self-signed certificate. Weblate then complains that:

`https://weblate.xxxxx.de/projects/ (HTTPSConnectionPool(host='weblate.xxxxx.de', port=443): Max retries exceeded with url: /projects/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)'))))`

Using `google.com` as the project URL satisfies weblate, but doesn't satisfy me. ;)

BTW: The same error message is also thrown by `wlc`, although with a different `_ssl.c` line number.

As far as we could track it, certification checks are done via urllib3 and then via certifi, which brings its own .pem file, which of course doesn't contain our self-signed certificate.

- Why does weblate access this URL at all and tries to validate the certificate? 
- Why is the project URL itself checked for validity?
- Why is the project URL mandatory at all?

Especially for an internal setup, it should be possible to make the URL:

- not mandatory or 
- turn the validation of the URL off or
- turn the certificate validation off

The project URL is for display/info purposes only (correct me, if I'm wrong) and Weblate doesn't need it to function.

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.
- [x] I've searched the issue tracker and did not find the answer there.

**Expected behavior**

no certificate verification error.

Weblate installation: Docker

**Comment by nijel** [comment]
It is mandatory because it is very useful for public instances such as https://hosted.weblate.org/. 

Having non-working URL there indicates that something is wrong. You can still dismiss the alert in case you think it's okay.

**Comment by luebbe** [comment]
There are always two sides to a medal. A public instance benefits from a project URL. A private instance doesn't really need it and the alert gets in the way and may hide other more important alerts. 

The URL is working fine. It's just weblate complaining about the certificate, because it doesn't use the OS's certificate store.
Weblate doesn't even trust itself. I can't use the internal URL of the weblate instance as a workaround. Would https://localhost work? Probably neither.

If it was only a handful of components, I'd dismiss the alert and be done with it. The annoying thing is that the alert has to be dismissed per component, even though there is only one project URL. I don't want to do this manually for 10 components * 10 projects or whatever.

So let's turn this into a feature request: "Implement a configuration setting that makes the URL non mandatory."
