### ISSUE TITLE
Start new translation is shown even though disabled in File settings

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#5735]
It is possible to **Start new translation**, even though this is disabled in the settings.

![image](https://user-images.githubusercontent.com/26718215/112331747-7bdf4400-8cb9-11eb-9431-a29819863648.png)

Disabled in **Settings**:
![image](https://user-images.githubusercontent.com/26718215/112331792-87326f80-8cb9-11eb-803b-fa22264b5f05.png)

(Well, just the button to **Start new translation** is displayed, but when you click on it and add a new language, nothing happens. But still, the button should not be visible when disabled in **Settings**, no?)

**Comment by nijel** [comment]
It is expected for project admins to be able to add translations even if disabled. The check seems to be too loose and it shows the button even if it is not possible to add languages.
