### ISSUE TITLE
Glossary Issue with very specific setup

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#5743]
We have a project which has multiple components. n-1 components have German as the source, among the target languages are both EN and en_US. 1 component has English (US) as a source.

We now have the following situation:

Three glossaries were created during upgrade to v.4.5:
![image](https://user-images.githubusercontent.com/26718215/112447196-5140ca00-8d51-11eb-9f66-ffbfc7fac63b.png)

The additional ones with English and English US are not needed.

When deleting those components, via Manage / Removal, Weblate shows the usual confirmation:
`Translation component was scheduled for removal.`
But nothing happens and the components remain.

**Comment by nijel** [comment]
Do you see any error in the log? The removal should just work same as for any other component.

**Comment by ilocit** [comment]
Interesting, even though the Glossary components were empty and I deleted them like 3 times, now, after almost 2h, they are gone....strange. 

Thanks and sorry for the "wrong" bug report.
