### ISSUE TITLE
Downloaded PO File Does Not Contain All Strings

### ISSUE THREAD

**Issue by superDross** [WeblateOrg/weblate#5758]
**Describe the issue**

When downloading monolingual po files, by navigating to the translation of interest and downloading via `Files` -> `Download translation`, we find only translated strings are present. We would expect source strings without translations to be present too.

**I already tried**

We tried using the customize download. So `File` -> `Customize download`, click `gettext PO` and press Download. The strings without translations are present but the `msgctxt` looks wrong in this version. They look like `msgctxt "<msgctxt>.<msgid>"`, which is not useable for our purpose.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

1. Create a component in the UI by selecting `start from scratch`, then ensure the file format is gettext PO file (monoglingual) and have English as the source language
2. Start new translation (French)
3. Add some source strings to English
4. Add the French translations via the UI
5. Download the source language (via `Files` -> `Download translation`), add some more source strings to the file then upload the file to the source language using the pictured options.
6. Download the French translation file (via `Files` -> `Download translation`) and you will find the newly uploaded source strings are not present in the po file.

![upload_options](https://user-images.githubusercontent.com/16519378/112672582-8e917e80-8e5b-11eb-9a5c-b3b8b7f5a601.png)

**Expected behavior**

For all strings to be present in the downloaded po files, even those without translations.

**Server configuration and status**
```
* Weblate: 4.5.1
 * Django: 3.1.7
 * siphashc: 2.1
 * translate-toolkit: 3.3.3
 * lxml: 4.6.2
 * Pillow: 8.1.1
 * bleach: 3.3.0
 * python-dateutil: 2.8.1
 * social-auth-core: 4.1.0
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.11.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.2
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.6
 * celery: 5.0.5
 * kombu: 5.0.2
 * translation-finder: 2.9
 * weblate-language-data: 2021.3
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.25.1
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 1.0.0
 * Cython: 0.29.22
 * misaka: 2.1.1
 * GitPython: 3.1.14
 * borgbackup: 1.1.15
 * pyparsing: 2.4.7
 * pyahocorasick: 1.4.1
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.6
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.16.13
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.17.21
 * zeep: 4.0.0
 * aeidon: 1.9
 * iniparse: 0.5
 * mysqlclient: 2.0.3
 * Mercurial: 5.7
 * git-svn: 2.20.1
 * git-review: 2.0.0
 * Redis server: 6.2.1
 * PostgreSQL server: 13.2
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.mailtrap.io
 * OS encoding: filesystem=utf-8, default=utf-8
```

**Comment by nijel** [comment]
The monolingual files typically do not contain non-translated strings. Having empty strings there can cause problems when the consumer only checks for the existence of a string, not whether it is non-empty. In case you would like to see original strings, please see https://github.com/WeblateOrg/weblate/issues/5692.

**Comment by superDross** [comment]
I see. Thanks for clarifying the reasoning as well as linking the associated issue.
