### ISSUE TITLE
Automatic Translation Addon not being triggered after pulling the repo, and no commit happens

### ISSUE THREAD

**Issue by benks-io** [WeblateOrg/weblate#5772]
My setup tries translating a Sphinx Repo on Github as automated as possible. Github triggers the Weblate Webhook on every commit. I am using Component discovery and Automatic Translation with deepl and Weblate Memory. "Push on commit" is enabled for the repo.

I configured the Automatic Translation Addon with

- Automatic translation mode: add as translation
- Search filter: Strings needing action
- Score Threshold: 1

There are to steps to be automated that do not work up til now

First: After Weblate pulled the Repo from Github, the changes can be found with the Project search, but the Automatic Translation doesn't seem to run. I guess so, because no translation is set for the new Message.

I only see a Translation to choose from when I open the Message in Translation View. It seems the translation is pulled from deepL api in the moment I open the Message for the first time.

Second:
I'd like to achieve that the automatic translation addon, puts the translations from deepl or Weblate's memory as the accepted translation for all new messages (needing action), and then commits the changes to the local repo, so that Weblate pushes it back upstream.

Weblate Version 4.3.1

**Comment by nijel** [comment]
I'd start with upgrading to current version. There might have been some bug back then (I do recall some related issues, but I have no clue which versions were affected).

**Comment by benks-io** [comment]
@nijel The Update did fix the issue, indeed.
I considered my question a bug report, providing some context to narrow the bug down. Thanks anyway for the quick response.
Commiting the changes, may be another issue for a feature idea.
/close

**Comment by nijel** [comment]
You can configure when Weblate commits, see https://docs.weblate.org/en/latest/admin/continuous.html#lazy-commits
