### ISSUE TITLE
Automatic translation completed, no strings were updated. 

### ISSUE THREAD

**Issue by ohameiri** [WeblateOrg/weblate#5790]
Hi
trying to use AWS auto translate, but getting  "Automatic translation completed, no strings were updated. "
and none of the strings got translated.

Trying to translate from Hebrew to English

**Comment by nijel** [comment]
What Weblate version do you use? Might be related to #5299 or #5669.

**Comment by ohameiri** [comment]
@nijel yes!
thank you

upgraded, problem solved!
