### ISSUE TITLE
Doc: table translation in devel/reporting-examples.rst

### ISSUE THREAD

**Issue by rffontenelle** [WeblateOrg/weblate#5801]
**Describe the issue**

I believe the table in [docs/devel/reporting-example.rst] should not be translated at all, since it shows how a auto-generated table is rendered. The page [docs/devel/reporting.rst] includes [docs/devel/reporting-example.rst] both literal and non-literal. See [published documentation](https://docs.weblate.org/en/latest/devel/reporting.html#contributor-stats) or the screenshot section below.

The table headers and its values are available for translation in [documentation component].

The problem is that the header label "Name" is also used [docs/admin/optionals.rst](https://github.com/WeblateOrg/weblate/blob/main/docs/admin/optionals.rst), so it is not possible at the moment to keep translated for one and not translated for the other.

Currently, the translation for other headers is not used in any other place in the documentation, but surely this could happen at some point. The values (not headers) in the table are used in other places, but they are mostly numbers or proper name, so it is an issue. 

**I already tried**

No ideas

**To Reproduce the issue**

1. Translate "Name" string in [documentation component]
2. See the translation in the table of [docs/devel/reporting.rst]'s corresponding page

**Expected behavior**

Avoid the conflict between the (no-)translations for the table with the translations of any other part of the documentation.

**Screenshots**

| Click in the images to enlarge them.

In English:

<img src="https://user-images.githubusercontent.com/1571783/113568606-460a5b80-95e7-11eb-9bf0-476c9d94451d.png" alt="Screenshot of Contributor Stats section showing a table literal and the its rendered version" width="50%" height="50%">

In Portuguese (Brazil) (see translation "Nome" in the rendered table):

<img src="https://user-images.githubusercontent.com/1571783/113570577-080f3680-95eb-11eb-9dde-cfa4e07442a8.png" alt="Screenshot of translated page of Contributor Stats section showing a table literal and the its rendered version" width="50%" height="50%">

**Exception traceback**

N/A

**Server configuration and status**

N/A

**Weblate deploy checks**

N/A

**Additional context**

N/A

[docs/devel/reporting-example.rst]: https://github.com/WeblateOrg/weblate/blob/main/docs/devel/reporting-example.rst
[docs/devel/reporting.rst]: https://github.com/WeblateOrg/weblate/blob/main/docs/devel/reporting.rst
[documentation component]: https://hosted.weblate.org/projects/weblate/documentation/

**Comment by rffontenelle** [comment]
@comradekingu cc'ing you, as you might be interested in this issue.

**Comment by nijel** [comment]
These indeed should not be translated as these are not translated in the generated files. Unfortunately, I have no clue how to achieve that.

**Comment by comradekingu** [comment]
Bit too tired to read _and_ understand.
Something like https://docs.readthedocs.io/en/stable/guides/embedding-content.html and then don't put the file in POTFILES.in?

That being said, I am a fan of even translating things that appear differently. That way the user has some reference that works for them if they can't read the source language. If the exact checksum of output for scripts isn't important that is.

**Comment by nijel** [comment]
> Bit too tired to read and understand.

Definitely ;-)

> Something like https://docs.readthedocs.io/en/stable/guides/embedding-content.html 

This is for embedding rendered documentation into other documentation projects, this has really no use here.

> and then don't put the file in POTFILES.in?

Unfortunately, there is no list of files to (not) localize in Sphinx, see https://www.sphinx-doc.org/en/master/usage/advanced/intl.html#intl
