### ISSUE TITLE
As admin I receive: "Your request was rejected because you have performed too many operations recently. You have been signed out, please sign in and try again later."

### ISSUE THREAD

**Issue by spartan** [WeblateOrg/weblate#5802]
As "admin" when I try to add a new language to the project I receive the following message:

"Your request was rejected because you have performed too many operations recently. You have been signed out, please sign in and try again later. "

and I get logged out.

I could not find any configuration / documentation on how to fix this.

Thank you.

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/optionals.html#rate-limiting
