### ISSUE TITLE
Implement checks for Object Pascal format() strings

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#5813]
I'd like to add checks for Object Pascal format() strings. `c-format` is pretty close, but doesn't catch all cases, especially not the indexed parameters. See [Gnu Gettext](https://www.gnu.org/software/gettext/manual/html_node/object_002dpascal_002dformat.html#object_002dpascal_002dformat), which links to the [Free Pascal](https://www.freepascal.org/docs-html/rtl/sysutils/format.html) docs.

Currently I'm trying to figure out, at which places functions for a new `object-pascal-format` flag have to be added.

Looking through weblate's code, I found `format.py`, which definitely looks like a place to start. `test_format_checks.py` too. Any other not so obvious places?

One question: are there any rules for the named regex capturing groups in format.py? I see that most regexes use a similar naming scheme, but it's not consistent across all regexes. Can I conclude that there is no rule for the group names?

**Comment by nijel** [comment]
You can take look at https://github.com/WeblateOrg/weblate/pull/5248, it added Lua format.

The named regex groups are AFAIK not used for anything, and I'm not convinced that they follow some consistent naming.

**Comment by luebbe** [comment]
A little status report plus a call for help:

I've made some progress on the issue. So far I managed to get dev-docker up and running (partly, see below) on lubuntu on an old laptop of mine. I could make the desired changes add tests and run them locally in docker. So far so good.

My final test would be to create a translation project in dev-docker which contains `object-pascal-format` strings and here is where I have problems. I can't get Weblate itself to run, only the tests.

When I just `sudo rundev.sh` and wait until all three containers are past their "starting" phase, accessing localhost:8080 results in a "502 bad gateway". 

the output of `docker ps` is:

```
CONTAINER ID   IMAGE                COMMAND                  CREATED         STATUS                   PORTS                      NAMES
49ebe2170068   weblate-dev:latest   "/app/bin/start runs…"   9 minutes ago   Up 9 minutes (healthy)   127.0.0.1:8080->8080/tcp   dev-docker_weblate_1
744a765999cf   postgres:12-alpine   "docker-entrypoint.s…"   9 minutes ago   Up 9 minutes             5432/tcp                   dev-docker_database_1
73cb3a29aa07   redis:6-alpine       "docker-entrypoint.s…"   9 minutes ago   Up 9 minutes             6379/tcp                   dev-docker_cache_1
```

the output of `docker logs 49eb` is:

```
... more check stderr messages before this line ...

check stderr | 
check stderr | System check identified 7 issues (1 silenced).
2021-04-21 12:34:27,042 INFO exited: check (exit status 1; expected)
nginx stderr | 2021/04/21 12:34:52 [crit] 237#237: *3 connect() to unix:///run/uwsgi/app/weblate/socket failed (13: Permission denied) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /healthz/ HTTP/1.1", upstream: "uwsgi://unix:///run/uwsgi/app/weblate/socket:", host: "localhost:8080"
nginx stdout | 127.0.0.1 - - [21/Apr/2021:12:34:52 +0000] "GET /healthz/ HTTP/1.1" 502 166 "-" "curl/7.64.0"
celery-celery stderr | [2021-04-21 12:35:22,312: INFO/MainProcess] Received task: weblate.utils.tasks.heartbeat[2a14c71c-ac56-463a-afd9-e3cc30e923d7]  

... more similar nginx stderr | stdout messages after this line ...

```

Any hint what I can check or have to change?

**Comment by nijel** [comment]
Any uwsgi related log entries?

**Comment by luebbe** [comment]
Yes, the middle line of the log output above. ".../socket failed permission denied ..."

**Comment by nijel** [comment]
> WARNING: you are running uWSGI as root

Can you try whether adding this to the dev container will help?

```patch
diff --git dev-docker/weblate-dev/Dockerfile dev-docker/weblate-dev/Dockerfile
index e83036a3ec..f631cf7675 100644
--- dev-docker/weblate-dev/Dockerfile
+++ dev-docker/weblate-dev/Dockerfile
@@ -50,3 +50,4 @@ COPY requirements.txt /tmp/
 RUN pip3 install -r /tmp/requirements.txt
 # List should match weblate/weblate
 RUN chmod -R 777  /etc/nginx/sites-available/ /var/log/nginx/ /var/lib/nginx /app/data /app/cache /run /home/weblate /etc/localtime /etc/supervisor/conf.d
+USER 1000
```

**Comment by luebbe** [comment]
Unfortunately not. `USER 1000` is run as step 10/10 but the "502 bad gateway" remains, as well as the "permission denied" uwsgi errors in the log.
The startup messages are similar. Still full of "WARNING: you are running uWSGI as root".

By user is in the docker group, so it should not need to run docker commands as sudo. But when I called rundev.sh without sudo, it does't even get past the "starting" phase.

**Comment by luebbe** [comment]
Progress made :)

After merging with main, most problems running dev-docker went away. So I was missing some fixes before.
The only thing I had to do on top of it was to run `sudo chown -R myUID:myGID dev-docker/data` to get rid of a ton of warnings about "... has the wrong owner" on many files.

My tests were successful so the PR is about to come in a few minutes.
