### ISSUE TITLE
Rename "Language consistency" addon

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#5829]
The "Language consistency" does not well describe what it does as it is ambiguous. It can be understood as "ensuring consistent language is being used in translations" instead of "ensures a consistent set of languages is used for all components within a project".

_Originally posted by @luebbe in https://github.com/WeblateOrg/weblate/discussions/5811#discussioncomment-584565_:

> OK, so this means that I shouldn't activate the language consistency add-on. That's a pity.
> Wouldn't it make sense for this add-on to have an operation mode where it "just" checks for consistency across existing translations instead of adding empty translations on its own? 
> Especially when adding new translations is disabled for users. Why should an add on be allowed to override this?

**Comment by nijel** [comment]
Suggestions welcome, CC @Fat-Zer @comradekingu

**Comment by comradekingu** [comment]
Language proliferation, language coverage, auto-addition of all languages in all components.

"All languages in all components" or "All components in all added languages"?

**Comment by fitojb** [comment]
“Language set uniformity”

**Comment by luebbe** [comment]
I think "Consistent set of Languages" is already good. The real problem IMHO is that there is just a "snappy" headline for each add-on.
The German translation "Sprachliche Konsistenz" even points in a wrong direction. It's a literal translation of "Language Consistency", but as a German I'd always interpret it as "ensure consistent language is being used in translations". The correct translation in the sense of the add on would be "Konsistente Sprachen".

A one line explanation below the headline would already help a lot. The link to the online help is good, but even after reading this, I came to the wrong conclusion.

**Comment by nijel** [comment]
Hopefully, this will be easier to understand:

![image](https://user-images.githubusercontent.com/212189/114859227-be90c980-9dea-11eb-8d98-1fcfe10af614.png)

**Comment by luebbe** [comment]
That looks great!
