### ISSUE TITLE
Support for LibreTranslate

### ISSUE THREAD

**Issue by SethFalco** [WeblateOrg/weblate#5830]
**Is your feature request related to a problem? If so, please describe.**

We're thinking about moving to a free and open-source and self-hostable machine translation solution, however it's not supported by Weblate.

**Describe the solution you'd like**

Could an additional machine translation provider be implemented to include support for this?

https://libretranslate.com/
https://github.com/LibreTranslate/LibreTranslate

**Describe alternatives you've considered**

N/A

**Screenshots**

N/A

**Additional context**

N/A

**Comment by nijel** [comment]
Adding that should be easy, the API is similar to what other services use.

Check https://github.com/WeblateOrg/weblate/blob/main/weblate/machinery/deepl.py for similar service implementation.
