### ISSUE TITLE
Error building local Docker for development

### ISSUE THREAD

**Issue by BoGnY** [WeblateOrg/weblate#5841]
**Describe the issue**

During the build:

```shell
Step 9/9 : RUN chmod -R 777 /etc/nginx/sites-available/ /var/log/nginx/ /var/lib/nginx /app/data /run /home /home/weblate /etc/timezone /etc/localtime
 ---> Running in c44aa4548416
+ chmod -R 777 /etc/nginx/sites-available/ /var/log/nginx/ /var/lib/nginx /app/data /run /home /home/weblate /etc/timezone /etc/localtime
chmod: cannot access '/etc/timezone': No such file or directory
The command '/bin/bash -o pipefail -x -c chmod -R 777 /etc/nginx/sites-available/ /var/log/nginx/ /var/lib/nginx /app/data /run /home /home/weblate /etc/timezone /etc/localtime' returned a non-zero code: 1
```

**To Reproduce the issue**

1. Run `git clone https://github.com/WeblateOrg/weblate.git`
2. Run `./rundev.sh`
3. See error

**Expected behavior**

Build Docker succesfully.

**Possible fix**

Problem is caused by [line 52](https://github.com/WeblateOrg/weblate/blob/main/dev-docker/weblate-dev/Dockerfile#L52) of development's Dockerfile.
By removing `/etc/timezone` from line, the build work correctly.

Same deletion is even removed from [production's Docker](https://github.com/WeblateOrg/docker/blob/main/Dockerfile#L170).

**Comment by nijel** [comment]
Indeed it should be removed as the file got removed in the container, see https://github.com/WeblateOrg/docker/commit/2226fdfd7988fa30ef0bc5f98e6e6837750f9370

**Comment by luebbe** [comment]
Thanks for the solution! I just had the same issue.
