### ISSUE TITLE
Shortcut for suggest

### ISSUE THREAD

**Issue by kalimbra** [WeblateOrg/weblate#5842]
It is great there is a shortcut to validate a translation (CTRL + enter) but it is a pity there is none to "suggest" a translation.

We work in double team and the first to translate generally do it as suggest, so the reviewer can just validate the suggestion or correct it.

When you do a lot of suggestion in a row, having to use the mouse is time consuming.

**Comment by nijel** [comment]
Any suggestions what might be a good shortcut for this?

**Comment by kalimbra** [comment]
I think you can remove ALT+ENTER from the save current translation and use it to "save as suggestion"

**Comment by nijel** [comment]
Hmm, I'm not sure changing the existing keyboard shortcut to do something else is a good idea....

**Comment by comradekingu** [comment]
I think taking a cue from what other editors do could be helpful. Making an overview on the wiki would do nicely.
Are the shortcuts documented anywhere?

**Comment by kalimbra** [comment]
yes, here : https://docs.weblate.org/en/latest/user/translating.html#keyboard-shortcuts
