### ISSUE TITLE
question about rate limits

### ISSUE THREAD

**Issue by jzahradn** [WeblateOrg/weblate#5846]
Hi,
my colleague is getting error: Your request was rejected because you have performed too many operations.
He received the error after he added two or three new languages to a component. Then he was logged out, unable to add any other languages.
I already viewed page: https://docs.weblate.org/en/latest/admin/optionals.html#rate-limiting
But it is not clear to me how to set Weblate to solve this problem.
Is it enough to add this line:
RATELIMIT_LANGUAGE_ATTEMPTS = 100
to settings.py?

Thank you
Regards
Jan

**Comment by nijel** [comment]
Yes, that should work. Upcoming 4.6 release will skip this rate limiter for admins.
