### ISSUE TITLE
Full bars for projects with missing translations

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5849]
https://hosted.weblate.org/languages/nb_NO/
![bilde](https://user-images.githubusercontent.com/13802408/114804694-017a7f00-9da2-11eb-9432-42f20f23979d.png)

"Ikke oversatt" - "Not translated" should not be full.

Something seems to be off about the counting of strings

![bilde](https://user-images.githubusercontent.com/13802408/114804819-37b7fe80-9da2-11eb-8b26-9736b6b7d53c.png)

**Comment by nijel** [comment]
There are  now just three colors in the progress bar (approved / translated / needs work), see #4985.
