### ISSUE TITLE
Messaging to contributors

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#585]
In many cases it's useful to be able to send message to the contributors to given translation like  heads up before releasing. Weblate should provide support for this:
- This needs to be allowed only to project managers.
- For ACL projects it should send to all active users who have ACL.
- For open project to all contributors, probably limited by time, so let's say one year.
##

**Comment by Jibec** [comment]
I would love to see this implemented.
But I thought about an option to subscribe to such messages. If users didn't subscribe to project, I do not see the point to send them email (and it keeps your code simple).

About migration, I would love to see this enabled by default if user ask to get notification for new strings to translate.

I would also really love to give project maintainer the possibility to select which components are targeted in the release message. Some project have an android app, an iOS app, a web app, it often have different life cycle.

In addition, add a little helper to suggest project manager to at least give a one week delay so contributors. Sometimes, project maintainer forget we need time to translate and have

**Comment by nijel** [comment]
There is (for ages) possiblity to post whiteboard message. It then appears on top for given scope (project, component or translation). What is missing is sending out these announcements as notifications by email. This should be addressed within new notification system (see eg. https://github.com/WeblateOrg/weblate/issues/1046) as we really need to send such notifications in the background and provide better way to manage subscriptions for users.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
