### ISSUE TITLE
Adding a link to a specific commit

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#5852]
**Describe the solution you'd like**

Now that the docker bleed image indicates commit revisions, you can add a link to that revision.

**Screenshots**

![image](https://user-images.githubusercontent.com/39633242/114842711-67362d80-9dd9-11eb-9f13-91b93c789776.png)

**Comment by nijel** [comment]
It links to project website in all cases, I see no good reason to link to a commit here.

**Comment by tomkolp** [comment]
Maybe it is in a different place? This allowed you to check which changes are already included in a given docker image with one click. I use it a lot, e.g. in ntopng testing.
![image](https://user-images.githubusercontent.com/39633242/114844811-7322ef00-9ddb-11eb-839b-c3a7e75f1e62.png)
