### ISSUE TITLE
Unable to login weblate with gitlab

### ISSUE THREAD

**Issue by lyenliang** [WeblateOrg/weblate#5853]
I want to use my gitlab account to sign in to Weblate.

So I followed the [instructions from GitLab OAuth 2](https://docs.weblate.org/en/latest/admin/auth.html#gitlab-oauth-2), and set `AUTHENTICATION_BACKENDS`, `SOCIAL_AUTH_GITLAB_KEY`, `SOCIAL_AUTH_GITLAB_SECRET`, `SOCIAL_AUTH_GITLAB_SCOPE`, and `SOCIAL_AUTH_GITLAB_API_URL` variables into `environment` file.

I use [docker-compose](https://github.com/WeblateOrg/docker-compose) to setup a self-hosted Weblate service.

I've also created an application at `https://gitlab.my-company.com/oauth/applications/`.

After all the above variables are set. I run `docker-compose down && docker-compose up -d` to restart Weblate service.

But then I cannot find gitlab sign in option at `https://weblate.my-company.com:1443/accounts/login/`

![image](https://user-images.githubusercontent.com/3468329/114849781-acc31c80-9e12-11eb-90e2-aa9a9eeddae0.png)

Is there anything else that I need to configure to make gitlab sign in option appear?

I cannot find any error messages in the logs of the docker container. (I use `docker logs -f <container_id>` to view the logs)

Here's the content I added to the `environment` file:

```
# GitLab lab setup
WEBLATE_GITLAB_USERNAME=weblate_user
WEBLATE_GITLAB_HOST=https://gitlab.my-company.com
WEBLATE_GITLAB_TOKEN=<MY_TOKEN>

# Authentication configuration
AUTHENTICATION_BACKENDS = (
    "social_core.backends.gitlab.GitLabOAuth2",
    "social_core.backends.email.EmailAuth",
    "weblate.accounts.auth.WeblateUserBackend",
)

# Social auth backends setup
SOCIAL_AUTH_GITLAB_KEY = "<MY_GITLAB_KEY>"
SOCIAL_AUTH_GITLAB_SECRET = "<MY_GITLAB_SECRET>"
SOCIAL_AUTH_GITLAB_SCOPE = ["read_user"]

# If you are using your own GitLab
SOCIAL_AUTH_GITLAB_API_URL = 'https://gitlab.my-company.com/'
```

I expect that I should see something like this after a successful configuration.

![image](https://user-images.githubusercontent.com/3468329/114859354-37a91480-9e1d-11eb-913f-68e937cb9bca.png)

**Comment by nijel** [comment]
Putting Python code into Docker environment will not really work. Usually, a good way to start is by looking at the documentation: https://docs.weblate.org/en/latest/admin/install/docker.html#gitlab

**Comment by lyenliang** [comment]
I've also tried putting python code into `/var/lib/docker/volumes/weblate-docker_weblate-data/_data/backups/settings-expanded.py`. But the gitlab sign in option is still missing.

**Comment by lyenliang** [comment]
According [issue #57](https://github.com/WeblateOrg/docker/issues/57), the settings python code should be placed in `/var/lib/docker/volumes/weblate-docker_weblate-data/_data/settings-override.py`

**Comment by nijel** [comment]
In case you would read the documentation I referenced https://github.com/WeblateOrg/weblate/issues/5853#issuecomment-820322817, you could configure it purely in the Docker environment...
