### ISSUE TITLE
Autofix Bangla/Bengali sentence ender to ।

### ISSUE THREAD

**Issue by Oymate** [WeblateOrg/weblate#5854]
**Currently the autofix doesn't transform or sign(|), numerator sign to proper sentence ender**

**Describe the solution you'd like**
Autofix sentence ender to '।' when source has sentence ender[full-stop(.)]

**Describe alternatives you've considered**

**Screenshots**

**Additional context**
https://github.com/WeblateOrg/weblate/issues/5189

**Comment by Nibba2018** [comment]
Hello @Oymate , I would like to work on this issue if it's not already assigned to someone else.

**Comment by Oymate** [comment]
I think this was fixed actually. See exa.: https://hosted.weblate.org/translate/newpipe/strings/bn_BD/?q=।&sort_by=-priority%2Cposition&offset=3

@Nibba2018

**Comment by nijel** [comment]
I don't think there's an autofixer for this...
