### ISSUE TITLE
Header viewing when scrolling

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#5855]
**Is your feature request related to a problem? If so, please describe.**

When viewing projects / component lists with a large number of components the header remains at the top of the page. This makes it difficult to identify the meaning of the numbers.

**Describe the solution you'd like**

Header viewing when scrolling

**Screenshots**

![image](https://user-images.githubusercontent.com/39633242/114857668-d49d8a80-9de8-11eb-9897-45f774831fc1.png)

**Comment by ptse888** [comment]
Is anyone working on this? I would like to implement it!

**Comment by nijel** [comment]
You are welcome to work on this

**Comment by ptse888** [comment]
@nijel would it be possible to point me in the right direction of where the HTML files to modify are? I am having a bit of trouble locating them.

**Comment by nijel** [comment]
The template for objects listing is here: https://github.com/WeblateOrg/weblate/blob/main/weblate/templates/snippets/list-objects.html

**Comment by ptse888** [comment]
@nijel I tried modifying the https://github.com/WeblateOrg/weblate/blob/main/weblate/static/style-bootstrap.css and the https://github.com/WeblateOrg/weblate/blob/main/weblate/static/vendor/bootstrap/css/bootstrap.css files to try to change the header, but none of my changes would show up. I was able to do some inline CSS and was able to see my modifications. Am I looking at the wrong CSS files or am I missing something? Thank you again for the help and quick responses!
