### ISSUE TITLE
Clicking placeholder in Zen removes previously entered text

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5861]
https://hosted.weblate.org/translate/app-manager/main/nb_NO/?checksum=ecc3a29d2a664437

1. Type in ~"Password for alias"
2. Click `<b>`
3. Only left with `<b>`

Only in Zen, regular mode is fine.

**Comment by nijel** [comment]
Sorry, but I can't reproduce this. What browser do you use?

**Comment by comradekingu** [comment]
Now it works in both FF 78.9.0esr (64-bit) and Vivaldi | 3.7.2218.52 (Stable channel) (64-bit) …
I'll close this if I can't trigger it again soon.
