### ISSUE TITLE
Clickable categories in profile overview

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5872]
![bilde](https://user-images.githubusercontent.com/13802408/115136806-7825af80-a022-11eb-99dd-6b146b506f99.png)

This would be the dream now that there is project-wide listings. Top stuff.

**Comment by nijel** [comment]
Can you please clarify? I have no clue what you are talking about...

**Comment by comradekingu** [comment]
@nijel I want to be able to click the "not translated" number for 3Dtris and get to https://hosted.weblate.org/zen/3dstris/-/nb_NO/?q=state:%3Ctranslated

Now I remembered they aren't listed per language, and instead for the whole project.

Clickable numbers for controls and comments might be possible?

**Comment by nijel** [comment]
There is one slight issue: How it should determine desired language? Also, the numbers are for project as a whole, so the link going to language would be confusing...

**Comment by comradekingu** [comment]
It could do one listing per language of configured languages. I have contributed to plenty, but am really only interested in nb_NO. Those are the numbers I want too.

**Comment by nijel** [comment]
The list of projects is already huge for many users. Multiplying it by number of languages will not do anything good. See for example https://hosted.weblate.org/user/Edanas/

**Comment by comradekingu** [comment]
@nijel It could be expanded by language if there is more than one.
Moreover, maybe we should ask someone with as many contributions in what we only presume to be different languages. It would be interesting to find out, which is one use-case.
