### ISSUE TITLE
Plural mismatch becomes inconsistent 

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#5874]
**Describe the issue**

If I translate a plural string in two different components with different plural rules I'm encountering an Inconsistent quality check.

**To Reproduce the issue**

https://hosted.weblate.org/translate/weblate/application/he/?q=has:dismissed-check#others

**Expected behavior**

Allow me to choose the plural form or deduce that there's a problem with the string with less plural forms for the same language.

**Screenshots**

<img width="1057" alt="Screen Shot 2021-04-18 at 12 08 03" src="https://user-images.githubusercontent.com/406826/115140205-c3e65200-a03e-11eb-908b-655778072dd0.png">

It's Weblate localization related so I'm guessing we don't need further investigation to understand the issue.

**Comment by nijel** [comment]
Can you please share a permalink to the string? The check seems to be gone and I have troubles finding it...

**Comment by yarons** [comment]
It was that one:
https://hosted.weblate.org/translate/weblate/application/he/?checksum=613469241a22a197
