### ISSUE TITLE
Improve handling duplicate keys

### ISSUE THREAD

**Issue by KadAnna** [WeblateOrg/weblate#5881]
**Developers sometimes create a duplicate key (with different text value). Weblate takes in just one and ignores the duplicate(s). There is not feedback this happened, just a string is missing.**

I would like to have a (source) check reporting there is duplicate key in the source file, and maybe which one it is.
A clear and concise description of what the new feature should do.I would like to have a (source) check reporting there is duplicate key in the source file, and maybe which one it is.

**Comment by nijel** [comment]
You will get an alert with that information:

![image](https://user-images.githubusercontent.com/212189/115349518-3e84ae00-a1b4-11eb-9b39-70b30069775e.png)
