### ISSUE TITLE
"Untranslated/words" isn't actually untranslated

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5896]
I can't distinguish untranslated strings with the new always-full bars.
This is compounded by not being able to sort for untranslated strings, or number of untranslated words.

https://hosted.weblate.org/languages/nb_NO/
![bilde](https://user-images.githubusercontent.com/13802408/115528897-ba552800-a292-11eb-9c1c-13c116f72563.png)

The third category here is "Not translated strings" or somesuch, but aren't actually _missing_, as that would suggest.

For example: https://hosted.weblate.org/languages/nb_NO/asteroidos/#overview

**Comment by nijel** [comment]
>  This is compounded by not being able to sort for untranslated strings, or number of untranslated words.

You can sort by any column...

**Comment by comradekingu** [comment]
Yes. I am saying what is actually in that column isn't actually untranslated things, but rather translated things with errors, marked for edit. etc.

What I want to get is strings that haven't been translated. Then I want to get fuzzy strings.
Nr1 used to be possible, but now I don't know.

**Comment by comradekingu** [comment]
In summary, the column that says "untranslated" links to q=state:<translated, which is "needs editing", when it should be   q=state:empty "untranslated".

**Comment by nijel** [comment]
> which is "needs editing"

No, it is "needs editing" OR "not translated". We clearly need a better label here.

See also https://github.com/WeblateOrg/weblate/issues/1163

**Comment by comradekingu** [comment]
@nijel 

In https://hosted.weblate.org/languages/nb_NO/

One column is [not translated](https://hosted.weblate.org/translate/weblate/application/en/?checksum=5e8f2651c688b01d) but actually holds untranslated+needs editing.

and the other is [untranslated words](https://hosted.weblate.org/translate/weblate/application/en/?checksum=fb1a24d2d478142a), which is fine for untranslated+needs editing words, but why words?

I never needed the breakdown or comparison of strings to words.
When everything else is also in strings, I would be happy with "untranslated" and "needs work".

"Needs work" next to useless since it covers too much, and what I really want to find is "untranslated", at least for now.

Breaking it down into two solves my problem, but then presents the problem of whether or not to also put "untranslated" words in the "needs work".

Moving the % into the bar removes one column.

Then one or two bars with 
"Unfinished" sorted fuzzy/changed first, then untranslated, and then
"Problematic" for the ones marked (or written, see below), sorted by suggestion first
"Suggestions" moved here as they are closer to problematic, sorted by problematic first.
"Comments" 
"Controls" as now

I argue it should be impossible to just "mark as needing edit" [x]", and this should instead by a type of comment (stating what is wrong), mapped to the actual language it concerns. English, German, etc.

**Comment by comradekingu** [comment]
I am revisitng this because it is the single worst aspect of using Weblate right now.

Not only is it colour-blind unfriendly, I just don't understand the practical use of it.

In order of preference I want to know what

- Changed but is fuzzy
(this is often easy to do something about, and most often actively wrong)

- Isn't translated
(Other than e-mails, this is now obfuscated)

- Is translated, but has a lower confidence intervall
(currently checked as needs work)

- I suggested
(This functionality isn't as good, and not often used. In the interest of presenting less info, I'd settle for these three categories.)

I want this in one Zen-like editor for all the projects I follow, (ala translatewiki) and never look for stuff again.
With some randomization that gives smaller projects a chance too.

If I miss one e-mail in a project that doesn't update often, there is no mitigation other than to go looking for missing stuff.

**Comment by comradekingu** [comment]
If the mixed-strings are sorted status:empty first, it would be possible to use "unfinished" as a label.
