### ISSUE TITLE
Wrong text presentation (with XML tags)

### ISSUE THREAD

**Issue by luminow** [WeblateOrg/weblate#5899]
**A long list of XML tags has the wrong ostent. See more in the attached video.**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

1. Go to 'https://translations.documentfoundation.org/translate/libo_help-master/textsharedoptionen/uk/?checksum=d854ed2a8604bc42'
2. Select a language that differ from English.
3. Copy/paste English variant and try to edit to your language.
4. Select an empty space starting from the end. See error

**Expected behavior**
WYSIWYG

**Screenshots**

**https://drive.google.com/file/d/1MbZ48BjCLm_Kre2V1WMqHct75xthiiG2/view?usp=sharing**

**Server configuration and status**

Weblate installation: weblate.org service / Docker / PyPI / other

**Weblate deploy checks**

**Additional context**

**Comment by nijel** [comment]
I think this issue has been already fixed, please upgrade

**Comment by luminow** [comment]
nijel, right now it still present.

**Comment by nijel** [comment]
The site still runs Weblate 4.4.2. I've just tested the same string in 4.6, and it renders correctly. I think it was fixed by 2aec3ca3b61a3bcf8de32658b06a5c87e0fbf348.

**Comment by nijel** [comment]
I have no clue, we don't maintain that server...
