### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by VadymTkachuk** [WeblateOrg/weblate#5904]
In reply letter for activities in profile. 

Ативність у вашому профілі на Hosted Weblate
should be "Активність"

Надіслано устроєм перекладу Weblate.
устроєм should be пристроєм.

**Comment by comradekingu** [comment]
It has been "Деятельность с вашей учётной записи на %(site_title)s"
in https://hosted.weblate.org/translate/weblate/application/ru/?checksum=1b6cf44fd8657425
for a year. Couldn't find the other one, but you can make changes in https://hosted.weblate.org/languages/ru/weblate/

**Comment by nijel** [comment]
@comradekingu It seems he is talking about Ukrainian, but you've made the change to Russian...

@VadymTkachuk You can do the fixes yourself at https://hosted.weblate.org/languages/uk/weblate/, just find the string and fix it ;-).

**Comment by comradekingu** [comment]
I didn't change anything. Guess that is why I couldn't find it :)
