### ISSUE TITLE
Deleting terms won't commit all languages

### ISSUE THREAD

**Issue by alex-adestech** [WeblateOrg/weblate#5911]
**Context:**
I recently migrated to Weblate, uploaded all translations in json format from my GitLab repository and made some adjustments to them. I saw the changes were committed and everything was going fine. 

**Problem:**
We have a "testing" term in the glossary which we wanted to delete from all translation files. Once we deleted the term, it would be removed from all the translation files, but only the base language (which is English) would be committed.

**Screenshots:**
1. Searching for the term
![Screen Shot 2021-04-23 at 13 32 57](https://user-images.githubusercontent.com/48839733/115915950-b0215e00-a439-11eb-9309-e0afa162647e.png)

2. Deleting the term and searching for it
![Screen Shot 2021-04-23 at 13 35 16](https://user-images.githubusercontent.com/48839733/115916023-d0e9b380-a439-11eb-8f8b-60b71c54aee7.png)

3. Looking at the commits
![Screen Shot 2021-04-23 at 13 35 48](https://user-images.githubusercontent.com/48839733/115916059-dd6e0c00-a439-11eb-820d-ef35ebe1477d.png)

4. Translations files with their last modified status
![Screen Shot 2021-04-23 at 13 36 12](https://user-images.githubusercontent.com/48839733/115916128-fa0a4400-a439-11eb-8232-e91035c3d91a.png)

**Expected behavior:**
When deleting a term from the glossary it should be deleted from all files and then commit all the translation files, not just the base translation file.

I hope I made myself clear enough. If I'm wrong, please let me know how to solve this issue. Thanks!

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/addons.html#cleanup-translation-files
