### ISSUE TITLE
Weblate is a "first-time contributor" everytime, and now it matters

### ISSUE THREAD

**Issue by jepler** [WeblateOrg/weblate#5912]
Hi!

I'm writing on behalf of https://github.com/adafruit/circuitpython, which we use with a paid account on Hosted Weblate.

GitHub recently made a change, so that "[pull requests from first-time contributors will require manual approval from a repository collaborator with write access before any Actions workflows run](https://github.blog/2021-04-22-github-actions-update-helping-maintainers-combat-bad-actors/)".

In adafruit/circuitpython, Weblate consistently is treated as a "first-time contributor".

This leads to us needing to approve each Weblate PR to run Actions, introducing extra undesirable steps.

We would like Weblate to NOT appear as a first-time contributor everytime, or to have some other workaround for this problem so that the Actions will be kicked off automatically.

We've considered adding Weblate as a collaborator on the project, but we aren't sure what the ramifications would be; and Weblate would have to accept the addition as a collaborator (I think) so I'm not sure we can do it unilaterally.

**Screenshots**

Typical pull request: https://github.com/adafruit/circuitpython/pull/4656

![image](https://user-images.githubusercontent.com/1517291/115927195-aacc0f80-a449-11eb-8ad2-be32c6ab13b7.png)

![image](https://user-images.githubusercontent.com/1517291/115927420-05fe0200-a44a-11eb-9af9-da6bc70ff0a9.png)

I don't understand the reasons that weblate is always a first-time contributor (it seems odd to me) and I hope there's some kind of solution that can be found for this problem.

Thank you!

**Comment by comradekingu** [comment]
Did you add the Weblate user to your organization and/or https://docs.weblate.org/no/latest/admin/continuous.html?highlight=webhooks#automatically-receiving-changes-from-github?

**Comment by jepler** [comment]
Under "Integrations", we have "Weblate".

![image](https://user-images.githubusercontent.com/1517291/115993852-4076b480-a59a-11eb-9d2e-7733b79f25e0.png)

**Comment by nijel** [comment]
The integration is currently only used for getting notifications about repo updates, it is not yet used for repository access, that's why we have a dedicated user for that...

**Comment by jepler** [comment]
Thanks to those who have offered help in this issue.

We are going to try with the @weblate user set as an external collaborator to our organization.

If this is the correct solution, it is not obvous to us.  The linked page of documentation does not contain the word "collaborator".  However, about the github integration, weblate's documentation does state

> If you are using Hosted Weblate, the recommended approach is to install the Weblate app, that way you will get the correct setup without having to set much up. It can also be used for pushing changes back.

I hope that someone who is more familiar with the details can offer an improvement to the documentation before this troubles too many weblate users.

I'll monitor our weblate PRs and close this issue up if using the "external collaborator" method fixes github requiring manual approval of Actions.

**Comment by nijel** [comment]
This first time contributor feature on GitHub is quite recent and what I understood it should be enough to confirm each user once (see https://github.blog/2021-04-22-github-actions-update-helping-maintainers-combat-bad-actors/). The @weblate user should not be any different in this.

**Comment by nijel** [comment]
Hmm, after seeing a question about first-time contributor several times on https://github.com/WeblateOrg/docker/pull/1052, I'm not sure the GitHub feature works as I understood it.

Anyway I don't see anything we can do with the way the first-time check behaves, the proper fix is https://github.com/WeblateOrg/weblate/issues/1688

**Comment by jepler** [comment]
Adding weblate manually as a "collaborator" has allowed the CI to start automatically.

As far as I can see we had previously enabled the weblate integration https://github.com/apps/weblate but for whatever reason it was not enough on its own to get past this new check by github.

Thank you as always for Weblate.
