### ISSUE TITLE
Android export - missing string parameters

### ISSUE THREAD

**Issue by fprt77** [WeblateOrg/weblate#5913]
We have weblate project where core file in repo is in iOS (string) format.

We are using string substitutes in translations (%@) and when  we try to export string to Android file, it does not do conversion to Android format neither have the original substite. It simply dissapears.

P.e. the iOS string

`
"login.biometricsSetup.header" = "Enable %@";
`

Is exported to android as  

`
<string name="login.biometricsSetup.header">Enable</string>
`

**Comment by nijel** [comment]
I can't reproduce this, it exports correctly for me:

```xml
<string name="login.biometricsSetup.header">Enable %@</string>
```

What Weblate and translate-toolkit versions do you use?

**Comment by fprt77** [comment]
Weblate 4.6
translate-toolkit 3.3.4

**Comment by nijel** [comment]
Just tried with your versions, and it still works fine for me. Are there any non-printable characters in the iOS string? What exact steps you do to trigger this?

**Comment by fprt77** [comment]
We do not experience this issue anymore. Android strings now contain iOS style parameters.
