### ISSUE TITLE
"Text copied to clipboard" should be "link"?

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5931]
https://github.com/WeblateOrg/weblate/blob/e5cdb746f711aaf4504ba06dbf799bc9c723c55f/weblate/static/loader-bootstrap.js#L827

is used for copying links via 

![image](https://user-images.githubusercontent.com/13802408/116250050-aebfa080-a76d-11eb-8840-4216e38f54b6.png)

https://hosted.weblate.org/translate/weblate/javascript/nb_NO/?checksum=cdadcca2c36828bb

Can it just be made to say "links" without breaking something else?

**Comment by nijel** [comment]
This is a generic message used for copying to clipboard, so "text" is more appropriate here.

**Comment by comradekingu** [comment]
@nijel Yes, when it is used for 
![bilde](https://user-images.githubusercontent.com/13802408/116604942-18d37380-a92f-11eb-9b1f-cbd62c3a06bd.png)
it makes sense, because that _is_ text.

However if I click 
![bilde](https://user-images.githubusercontent.com/13802408/116605150-559f6a80-a92f-11eb-97c5-2ae00466aaa3.png) (to copy the link)
I get the same
![bilde](https://user-images.githubusercontent.com/13802408/116605113-48827b80-a92f-11eb-9045-aaa32b94658f.png)
~"Text copied to clipboard"

The mouseover is correct, but the resulting message could mention "link" for the latter,
to instil some confidence in the action, and possibly doing without having to read the mouseover.

**Comment by nijel** [comment]
It indeed would give a better feedback, I will look into that.
