### ISSUE TITLE
Labeling does not work properly

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#5935]
**Describe the issue**
Labeling with all languages does not work properly.

**To Reproduce the issue**

1. This is what the (Polish) component looks like at the start:
![image](https://user-images.githubusercontent.com/39633242/116375624-c0598480-a80f-11eb-812a-7a6a97ac4a4c.png)

2. We go to all languages. We choose bulk edit with the following parameters:
![image](https://user-images.githubusercontent.com/39633242/116375823-ef6ff600-a80f-11eb-8ea1-fa15bbd60826.png)

All strings are marked with a label.
![image](https://user-images.githubusercontent.com/39633242/116376238-57264100-a810-11eb-9acb-2d6126a81172.png)

**Expected behavior**

Only the translated strings are marked.

**Additional context**

Weblate version | 4.7-dev — [ca6afc412bf7a72665068a0678808ace407211a1](https://github.com/WeblateOrg/weblate/commits/ca6afc412bf7a72665068a0678808ace407211a1)

**Comment by nijel** [comment]
Labels are applied on source string. All source strings are translated. The behaviour you get is expected.

**Comment by tomkolp** [comment]
Ok
