### ISSUE TITLE
Question about document linking "Checks and Fixups"

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#5940]
I don't know much about rst linking, but it looks like the target ids in the links are missing in the page.
https://docs.weblate.org/en/latest/user/checks.html#check-python-format
https://docs.weblate.org/en/latest/user/checks.html#check-php-format

All links are just resolved to: https://docs.weblate.org/en/latest/user/checks.html#formatted-strings

See:
![grafik](https://user-images.githubusercontent.com/3872576/116531428-7213b680-a8df-11eb-951e-4542e58f4da4.png)

Is it possible to fix it?

**Comment by nijel** [comment]
Hmm, that contains generic description of the format checks, but it indeed looks confusing. Probably better to link directly to these...
