### ISSUE TITLE
Deepl API has changed for free version

### ISSUE THREAD

**Issue by Xia0ben** [WeblateOrg/weblate#5952]
**Describe the issue**

Configured DeepL today (2021-05-02) for my own Weblate instance today.
Subscribed to DeepL free plan today too.
Configured the settings.py file with the two appropriate variables.
Got a 403 Forbidden error back from DeepL displayed in red on the Weblate interface.

**I already tried**

Digged around, made a sample request in my Firefox web browser with my API key on URL : https://api.deepl.com/v2/translate .
Got a 403 error message that the free tier should request URL : https://api-free.deepl.com/v2/translate .
Made a request with this new URL in my browser. Success.
Checked Weblate code (file weblate/machinery/deepl.py) --> does not seem to take this variation into account for now.
Manually changed lines 24 and 25 to :

```python3
DEEPL_TRANSLATE = "https://api-free.deepl.com/{}/translate"
DEEPL_LANGUAGES = "https://api-free.deepl.com/{}/languages"
```

Restarted my Weblate instance. Translations Success.

**To Reproduce the issue**

1. Subscribe a DeepL free account.
2. Setup Weblate following docs.
3. Get 403 Error.

**Expected behavior**

Add a new configuration parameter for DeepL in settings.py to differentiate free and paid versions so that "-free" is inserted in the API string the same way "v2"/"v1" is.

**Screenshots**

NA

**Exception traceback**

NA

**Server configuration and status**

Irrelevant to this problem: the current code is likely incompatible with the current API for free accounts for every Weblate version.

**Weblate deploy checks**

NA

**Additional context**

NA

**Comment by nijel** [comment]
Maybe it would be better to have DEEPL_API_URL instead to configure all this...

**Comment by Xia0ben** [comment]
@nijel You are right, this would be even better.

I would suggest adding a small line to the documentation for DeepL configuration, in case this changes again, so thatusers may quickly see if the problem lies in their API key or a new API change. For example, this is the URL I used :

```
https://api-free.deepl.com/v2/translate?text=Hello&target_lang=FR&auth_key=XXX
```
--> Replace XXX by your auth key
--> Expects JSON file with translated text as "Bonjour"

**Comment by Xia0ben** [comment]
And this is just an extra comment to say thank you, this software is already amazing, and I am amazed at the speed of your answer. =)

**Comment by luebbe** [comment]
I will have a go at this issue

**Comment by nijel** [comment]
The best approach would be to drop MT_DEEPL_API_VERSION and introduce MT_DEEPL_API_URL with default `https://api.deepl.com/v2`. Free users will change to `https://api-free.deepl.com/v2` and CAT users to `https://api.deepl.com/v1`.

**Comment by luebbe** [comment]
Already done this way. I'm currently testing with dev-docker.

**Comment by luebbe** [comment]
Basically I'm ready to make the PR. I just need @nijel's decision on whether MT_DEEPL_API_URL in the config should be with or without trailing slash. As I wrote above, I implemented for `MT_DEEPL_API_URL=https://api.deepl.com/v2/`, but I can change it to `MT_DEEPL_API_URL=https://api.deepl.com/v2` in all places.

**Comment by nijel** [comment]
That should be fine. Please include examples how to configure it for each case in the docs.
