### ISSUE TITLE
Add an API endpoint for "download translations as Zip"

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#5957]
**Is your feature request related to a problem? If so, please describe.**

right now it is possible to download a complete set of translations via;

`GET https://<weblate>/download/<project>/<component>/?format=zip`

This doesn't work anymore when `WEBLATE_REQUIRE_LOGIN` is enabled. One could possibly add a matching regex to `WEBLATE_LOGIN_REQUIRED_URLS_EXCEPTIONS`, but this would still allow anybody who can construct the above URL to download the translations without authorization (IIUC).

**Describe the solution you'd like**

There is already an API endpoint to download individual languages, but nothing for the whole component. The idea is to send only one request and get everything in one go.

We have:
`GET /api/translations/(string: project)/(string: component)/(string: language)/file/`

An API endpoint like:
`GET /api/translations/(string: project)/(string: component)/file/(string:format)`
or, if that doesn't make sense:
`GET /api/translations/(string: project)/(string: component)/zip`

where you have to pass in your authorization token and can only download translations when this is ok.

**Comment by Vogel612** [comment]
The endpoint specification as outlined would require sweeping changes to the way the API is created within weblate. A much easier setup is available if the download is exposed on the components API instead.

Attaching the endpoint there sidesteps the issue that all translation API endpoints ***require*** the specification of `project`, `component` and `language` (implemented as the `lookup_fields` that are included into the router registration via the `MultipleFieldsMixin` and the `WeblateRouter`.

I am currently working on a patch that would add this endpoint, expect a PR by the end of this week (and feel free to poke me if I fail on that commitment)
