### ISSUE TITLE
License Names Are Using Wrong Dashes ("-")

### ISSUE THREAD

**Issue by WuzgXY-GitHub** [WeblateOrg/weblate#5964]
https://github.com/WeblateOrg/weblate/blob/0bdeca24e6c72b55da11db233d083688ad665405/weblate/utils/licensedata.py#L715
For example, "CC-BY-NC-SA-4.0" should be "CC BY-NC-SA 4.0".

**Comment by nijel** [comment]
These are names defined by SPDX...
