### ISSUE TITLE
Include missing `i`docs links in the Weblate UI

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#5965]
**Describe the issue**

`i` link to docs is missing in some places. 
--
As they are popular among users, let’s add the missing ones:

**Project**
Access control
- [Invite new user](https://docs.weblate.org/en/latest/admin/access.html#new-user-invitation)

Settings/Workflow
- Shared translation memory
- Enable hooks
- Enable reviews
- Enable source reviews

Rename project

Remove project

**Component:**
Settings/Basic
- [Restricted component](https://docs.weblate.org/en/latest/admin/projects.html#restricted-access)
- [Use as glossary](https://docs.weblate.org/en/latest/admin/projects.html#use-as-a-glossary)

Settings/Translation
- Suggestions or Turn on suggestions
- Translation propagation
- Manage strings

Settings/Version Control:
- [Push on commit](https://docs.weblate.org/en/latest/admin/projects.html#push-on-commit)
- [Lock on error](https://docs.weblate.org/en/latest/admin/projects.html#lock-on-error)

Settings/Files
- Edit base file

**Comment by nijel** [comment]
There is a bug that the links are not shown for a checkbox.

For Rename / Remove forms  I don't see docs where it should go to (I've added the docs for individual form fields, but that's not much helpful).
