### ISSUE TITLE
Using Tabs vs Spaces for the JSON addon

### ISSUE THREAD

**Issue by ahadcove** [WeblateOrg/weblate#5969]
When weblate tries to merge to our branch it merged the file with spaces causing a complete clash with our current setup.
We're already using the JSON addon and specifying the indentation, but there isn't a way to choose tabs or spaces

**Describe the solution you'd like**

Option for tabs vs spaces in the JSON indentation addon please

**Describe alternatives you've considered**

Or even an option for a custom hook before trying to merge where we could run an auto formatter. But the easier route is just adding on to the already existing json addon by selecting tabs

**Comment by nijel** [comment]
It should be possible to specify a custom string for indentation instead of the integer, see https://docs.python.org/3/library/json.html#json.dump. So, it's just a matter for adding configuration in the JSON add-on.

**Comment by ahadcove** [comment]
> It should be possible to specify a custom string for indentation instead of the integer, see https://docs.python.org/3/library/json.html#json.dump. So, it's just a matter for adding configuration in the JSON add-on.

This would be awesome! If you need me to help out with the PR, i can try and dig further

**Comment by nijel** [comment]
The JSON add-on is here (it gets whatever is saved from the form):

https://github.com/WeblateOrg/weblate/blob/69f09794559fe83a51ce9d489725cf09658718e0/weblate/addons/json.py#L45-L48

The form to configure it is defined here:

https://github.com/WeblateOrg/weblate/blob/69f09794559fe83a51ce9d489725cf09658718e0/weblate/addons/forms.py#L184-L188

**Comment by ahadcove** [comment]
Finally had time to make the PR @nijel https://github.com/WeblateOrg/weblate/pull/6088
