### ISSUE TITLE
Plurals are not included in a custom download for various formats (base format is i18next JSON)

### ISSUE THREAD

**Issue by pleunv** [WeblateOrg/weblate#5981]
I have a project of which the base language files are JSON (i18next). Plurals are configured with either a `_plural` or `_{count}` suffix. When attempting to create a custom download, plurals are not included in various formats. Changing the filters does not appear to have an effect. The translation status of the individual strings ("not translated" or "translated") also does not appear to make a difference.
In one case I'm also getting a "Page not found" error (gettext MO).

Plurals **are** included in the following formats:
- gettext PO
- XLIFF with gettext extensions
- Android String Resource

Plurals **are not** included in the following formats:
- XLIFF 1.1
- CSV
- XLSX
- JSON (even if the source is JSON)
- iOS strings

Not applicable:
- TBX
- TMX

Gives a "Page not found":
- gettext MO

**I already tried**

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
- [x] Tried with both translated and untranslated plurals.
- [x] Tried exporting a custom download in the original base language, plurals are also not present here.
- [x] Tried changing the filters.

**To Reproduce the issue**

1. Set up a project with one or more JSON plural strings (`_plural` or `_{count}`).
2. Navigate to an individual component language.
3. Click "Files" -> "Customize download".
4. Select one of the formats outlined above.
5. Open up the downloaded file, search for the expected plural key.

There's an additional minor issue I noticed here: when you want to download multiple formats, the "Download" button stops working after the first download. You have to refresh the page to get it to work again. Happy to open up a new issue for this one.

**Expected behavior**

- I would expect consistent export behavior for all formats, and all strings, including plural forms, to be included by default.

**Screenshots**

- N/A

**Exception traceback**

- N/A

**Server configuration and status**

Weblate installation: Docker (4.6.0)

```
 * Weblate: 4.6
 * Django: 3.2
 * siphashc: 2.1
 * translate-toolkit: 3.3.4
 * lxml: 4.6.3
 * Pillow: 8.2.0
 * bleach: 3.3.0
 * python-dateutil: 2.8.1
 * social-auth-core: 4.1.0
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.11.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4.1
 * djangorestframework: 3.12.4
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.7
 * celery: 5.0.5
 * kombu: 5.0.2
 * translation-finder: 2.9
 * weblate-language-data: 2021.4
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.25.1
 * django-redis: 4.12.1
 * hiredis: 2.0.0
 * sentry_sdk: 1.0.0
 * Cython: 0.29.23
 * misaka: 2.1.1
 * GitPython: 3.1.14
 * borgbackup: 1.1.16
 * pyparsing: 2.4.7
 * pyahocorasick: 1.4.2
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.6
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.17.4
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.17.53
 * zeep: 4.0.0
 * aeidon: 1.9
 * iniparse: 0.5
 * mysqlclient: 2.0.3
 * Mercurial: 5.7.1
 * git-svn: 2.20.1
 * git-review: 2.0.0
 * Redis server: 6.2.1
 * PostgreSQL server: 13.2
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.mandrillapp.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.4.0-1046-azure (x86_64)
```

**Weblate deploy checks**

```
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.6/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.6/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 4.6.2.
	HINT: https://docs.weblate.org/en/weblate-4.6/admin/upgrade.html
```

**Additional context**

- N/A

**Comment by pleunv** [comment]
I suppose this also means that, if we were to manually generate excel files that included the `_plural` keys from the i18next JSON source (outside of weblate), they would not be mapped correctly on upload?

**Comment by nijel** [comment]
> I suppose this also means that, if we were to manually generate excel files that included the _plural keys from the i18next JSON source (outside of weblate), they would not be mapped correctly on upload?

No, it would not work.

**Comment by pleunv** [comment]
Alrighty, thanks for clarifying.
