### ISSUE TITLE
Weblate doesn't compile po files

### ISSUE THREAD

**Issue by AlainLDE** [WeblateOrg/weblate#5988]
Maybe don't compile po files

My web app uses gettext method to generate po files.
I use weblate to let ma translate team add translations string in german
On my weblate web server area, when translators change a translation string and push on our git, then pipeline restart my api server but if po files are changed, i can't see translated strings changed on my web application through api response
-->

**I already tried**

- [ ] I've read and searched [the docs](https://docs.weblate.org/en/latest/index.html) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

2. Scroll down to '...'
3. Click on '...'

**Expected behavior**

**Screenshots**
Here u can see translation string content, not updated with **_TESTAlain_** on the api response
[![Image](https://i.goopics.net/58YQ7.png)](https://goopics.net/i/58YQ7)
[![Image](https://i.goopics.net/Oq01K.png)](https://goopics.net/i/Oq01K)
[![Image](https://i.goopics.net/ZqLKd.png)](https://goopics.net/i/ZqLKd)

**Exception traceback**

**Server configuration and status**

Weblate installation: weblate.org service / Docker / PyPI / other

**Weblate deploy checks**

**Additional context**

**Comment by AlainLDE** [comment]
Translations had worked few days ago. So it's maybe a configuration issue but i can't find how to fix

**Comment by AlainLDE** [comment]
ok i just add addon to get mo files and it's fine.

**Comment by nijel** [comment]
Weblate will now suggest this add-on see b9659613c3.
