### ISSUE TITLE
Issues on Okta + Weblate configuration with SAML2

### ISSUE THREAD

**Issue by M0Rf30** [WeblateOrg/weblate#5989]
I'm trying to figure out how to configure Weblate and Okta using SAML2

As described in official documentation I set the following values in a docker-compose scenario:
```
WEBLATE_SAML_IDP_ENTITY_ID=
WEBLATE_SAML_IDP_URL=
WEBLATE_SAML_IDP_X509CERT=
```
and everything seems to be detected in the right way

On IdP side (Okta), I configure the values retrieved from `https://mydomain.com/accounts/metadata/saml/`

* as SP Entity ID:
  https://mydomain.com/accounts/metadata/saml/

* as ACS:
  https://mydomain.com/accounts/complete/saml/

* as Relay
  blank value

Now if I don't set a value for Relay, weblate complains with this message:
```
web_1       | uwsgi stderr |     return self.auth_complete(*args, **kwargs)
web_1       | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/social_core/backends/saml.py", line 314, in auth_complete
web_1       | uwsgi stderr |     idp = self.get_idp(idp_name)
web_1       | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/social_core/backends/saml.py", line 198, in get_idp
web_1       | uwsgi stderr |     idp_config = self.setting('ENABLED_IDPS')[idp_name]
web_1       | uwsgi stderr | KeyError: ''
```

Putting the "weblate" value as Relay (because docker settings auto-generate an entry named `weblate`)
the above error disappears and another one pops out:
```
web_1       | uwsgi stderr | The response was received at https://mydomain.com:8080/accounts/complete/saml/ instead of https://mydomain.com/accounts/complete/saml/
```
I don't know how to proceed
I also attach my `docker-compose.yaml`
[docker-compose.txt](https://github.com/WeblateOrg/weblate/files/6458594/docker-compose.txt)

Regards

**Comment by nijel** [comment]
It seems that SAML backend does not honour the URL configured for Weblate and tries to auto-discover this...
