### ISSUE TITLE
Indentation on json translation files

### ISSUE THREAD

**Issue by AlainLDE** [WeblateOrg/weblate#5990]
Weblate generate json translation files with 4 spaces indentation

Weblate generate json translation files with an indentation with 4 spaces when my developers of Front translation uses indentation with 2 spaces through vue.i18n

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

2. Scroll down to '...'
3. Click on '...'

**Expected behavior**

I'd like to know if i can't change indentation on weblate json generate
**Screenshots**

[![Image](https://i.goopics.net/QqZxq.png)](https://goopics.net/i/QqZxq)

**Exception traceback**

**Server configuration and status**

Weblate installation: weblate.org service / Docker / PyPI / other

**Weblate deploy checks**

**Additional context**

**Comment by comradekingu** [comment]
https://docs.weblate.org/en/latest/admin/addons.html?highlight=indentation#customize-json-output
