### ISSUE TITLE
Translated string does not match history

### ISSUE THREAD

**Issue by zergu** [WeblateOrg/weblate#6014]
During search for some missing translations we've discovered that is some cases string translation history does not match current translations. Is this a bug or am I missing something?

Translator was sure he translated it like history shows, but there were no changes in our project repo (VSC = GitLab, no pending/outgoing changes).

![image](https://user-images.githubusercontent.com/171167/118285795-18f87500-b4d2-11eb-9ab2-4dd0ba588ad7.png)

**Comment by nijel** [comment]
It could be a bug in Weblate writing out the changes, or it could be a change from the VCS which is not shown in the history (see https://github.com/WeblateOrg/weblate/issues/5726). Looking into Git history would tell you more.
