### ISSUE TITLE
SAML login conflicts with WEBLATE_REGISTRATION_OPEN=0 logic

### ISSUE THREAD

**Issue by M0Rf30** [WeblateOrg/weblate#6015]
If I set `WEBLATE_REGISTRATION_OPEN=0` I will make registration buttons disappear, for a private, on-invitation use, but I'll cause the failing of SSO procedure. The following message is shown:
`New registrations are turned off.`

So is a third state required to say that incoming registrations/login from a SSO are enabled and together removing the registration button?

I don't know if my explaination is clear enough.

**Comment by nijel** [comment]
You need to whitelist saml using https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_REGISTRATION_ALLOW_BACKENDS if you want to allow users register using it.

**Comment by M0Rf30** [comment]
This can be close. Now it works like a charm. Many thanks @nijel
