### ISSUE TITLE
Weblate is not on Github verified localization apps ?

### ISSUE THREAD

**Issue by aha999** [WeblateOrg/weblate#6017]
**Describe the issue**

Weblate does not seem to be verified or even on the list in the Github Localization platforms, while some other known platforms are: 

- https://github.com/marketplace/category/localization

Don't know if it's in your interest to be verified on that list, but i think it might help in Weblate being more recognizable/ more people getting to know about it.

**Comment by nijel** [comment]
The app is not yet complete, that's the major reason, see #1688.
