### ISSUE TITLE
Maintenance/read-only mode

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#6020]
**Is your feature request related to a problem? If so, please describe.**

I'd like to upgrade Weblate, however I'm concerned that users will access it during the upgrade and that'll interfere with upgrade process and/or result in a loss of work in case I need to roll back.

**Describe the solution you'd like**

Single-button lock down of all "write" actions for all users except admins. Display a custom note with some info.

**Describe alternatives you've considered**

I could lock it down by ip on webserver level, but that will not be as transparent, break badges on external sites in the meantime, etc.

**Additional context**

In fact, I'd be interested to know how you do it on https://hosted.weblate.org. Is it documented anywhere?

**Comment by nijel** [comment]
On Hosted Weblate we know what changes are being deployed (it is updated more frequently) and depending on that one of workflows is used:

* In case of non-breaking changes, the app is kept running, upgraded and uwsgi restarted.
* In case of bigger updates, the app is stopped, upgraded and then started.

For the second case we have web server configured in a way to display a maintenance message (which is here: https://github.com/WeblateOrg/wllegal/blob/main/wllegal/templates/weblate_50x.html).

**Comment by nijel** [comment]
The maintenance mode of Weblate would not address this in general - the database schema changes between versions and the old version is not be able to work with the new one.
