### ISSUE TITLE
Automatic translation cannot cover everything completely

### ISSUE THREAD

**Issue by Pinkuburu** [WeblateOrg/weblate#6028]
**Describe the issue**

Some text in the component has already been translated. But when I use automatic translation, the same text can not be completely translated, can only translate a few

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [√] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

find a component 
1. Go to 'Tool->Automatic translation'
2. Adjust the Settings to look like the image below
![image](https://user-images.githubusercontent.com/4962790/118475479-e2736200-b73e-11eb-9aec-a092bd3d3a82.png)
3. Click on 'Apply'
4. Automatic translation finish, but still have some text were not translated

**Expected behavior**
The same text can be translated completely

**Screenshots**

**Exception traceback**

**Server configuration and status**

Weblate installation: Docker

* Weblate: 4.5
 * Django: 3.1.6
 * siphashc: 2.1
 * translate-toolkit: 3.3.2
 * lxml: 4.6.2
 * Pillow: 8.1.0
 * bleach: 3.3.0
 * python-dateutil: 2.8.1
 * social-auth-core: 4.0.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.11.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.2
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.6
 * celery: 5.0.5
 * kombu: 5.0.2
 * translation-finder: 2.9
 * weblate-language-data: 2021.2
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.25.1
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.20.3
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.13
 * borgbackup: 1.1.15
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.6
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.17.11
 * zeep: 4.0.0
 * aeidon: 1.9
 * iniparse: 0.5
 * mysqlclient: 2.0.3
 * Mercurial: 5.7
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * Redis server: 4.0.14
 * PostgreSQL server: 9.6.21
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: 127.0.0.1
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.4.0-132-generic (x86_64)

**Weblate deploy checks**

[2021-05-17 18:42:09,504: DEBUG/13589] git: failure fatal: not a git repository (or any of the parent directories): .git
 (128)
[2021-05-17 18:42:09,504: DEBUG/13589] git: failure fatal: not a git repository (or any of the parent directories): .git
 (128)
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail ([Errno 111] Connection refused), please check EMAIL_* settings.
        HINT: https://docs.weblate.org/en/weblate-4.5/admin/install.html#out-mail

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.5/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.5/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 4.6.2.
        HINT: https://docs.weblate.org/en/weblate-4.5/admin/upgrade.html

System check identified 7 issues (1 silenced).

**Additional context**

**Comment by nijel** [comment]
The translation memory can not translate everything, you need some machine translation service for that...

**Comment by Pinkuburu** [comment]
I get it, because it used to go well with the 3.x version, and I thought it would be all done，thank you

**Comment by nijel** [comment]
The Weblate / Weblate translation memory only operate on translations store/done in Weblate. In case you had matches to existing ones, it could work. In any other case you need a third-party machine translation service.

**Comment by Pinkuburu** [comment]
Ah, I think you might have misunderstood me.
Suppose the current situation is that there are a thousand texts in the component.
Fifteen of these texts are "CAT".They need to be translated as "ねこ"
I translated one of the texts "CAT" as "ねこ"
Then I used automatic translation, and Weblate couldn't complete the translation of the remaining 14 texts
With one automatic translation, maybe translate 3, maybe 5, etc

**Comment by nijel** [comment]
Ah, now I understand. There were several improvements to this code recently, can you please try upgrading?

**Comment by Pinkuburu** [comment]
OK! thank you! I will try it this week!

**Comment by tomkolp** [comment]
In this version I also had this problem, the update should help.
