### ISSUE TITLE
Add labels to components (and projects)

### ISSUE THREAD

**Issue by dsnoeck** [WeblateOrg/weblate#6029]
**Is your feature request related to a problem? If so, please describe.**

I would like to allow users to group components using labels.

**Describe the solution you'd like**

Allow project administrators to add labels to components such as users could filter components based on labels.
On any project page (where we see all related components), we could use those labels to filter the view.

This feature could also be integrated for projects.

**Describe alternatives you've considered**

The **Share in project** feature is similar but less flexible. I dedicated project would need to be created (less easy then just a label). Filters is less flexible

**Comment by nijel** [comment]
There are [component lists](https://docs.weblate.org/en/latest/admin/componentlists.html) which can be defined by admins to group components.

**Comment by dsnoeck** [comment]
Thanks @nijel, exactly what we were looking for.
