### ISSUE TITLE
whitespace and newlines in translation key field

### ISSUE THREAD

**Issue by swurzinger** [WeblateOrg/weblate#6031]
**Describe the issue**

A recent update added some whitespace for the key field (structured json). There is no whitespace in the JSON in the keys. Whitespace seems to be the same for all entries.

**I already tried**

Looked through the issues in GitHub and didn't find any similar one.
I have another translation using Java property files - there I can't spot the error.

**To Reproduce the issue**

browse translations for structured json translation.

**Expected behavior**

single line in key field.

**Screenshots**

![image](https://user-images.githubusercontent.com/6787397/118527344-7d6d3b80-b741-11eb-83d4-74e883ed353f.png)

**Server configuration and status**

Weblate installation: openshift

weblate@weblate-web-11-cb9qt:/$ weblate list_versions
 * Weblate: 4.6.2
 * Django: 3.2.2
 * siphashc: 2.1
 * translate-toolkit: 3.3.6
 * lxml: 4.6.3
 * Pillow: 8.2.0
 * bleach: 3.3.0
 * python-dateutil: 2.8.1
 * social-auth-core: 4.1.0
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.11.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4.1
 * djangorestframework: 3.12.4
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.7
 * celery: 5.0.5
 * kombu: 5.0.2
 * translation-finder: 2.9
 * weblate-language-data: 2021.4
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.25.1
 * django-redis: 4.12.1
 * hiredis: 2.0.0
 * sentry_sdk: 1.1.0
 * Cython: 0.29.23
 * misaka: 2.1.1
 * GitPython: 3.1.14
 * borgbackup: 1.1.16
 * pyparsing: 2.4.7
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.6
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.17.4
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.17.69
 * zeep: 4.0.0
 * aeidon: 1.9
 * iniparse: 0.5
 * mysqlclient: 2.0.3
 * Mercurial: 5.8
 * git-svn: 2.20.1
 * git-review: 2.1.0
 * Redis server: 3.2.13
 * PostgreSQL server: 9.6.10
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://:pJ4mvDTdTjvw4re0@weblate-cache:6379/1, redis://:pJ4mvDTdTjvw4re0@weblate-cache:6379/1, regular
 * Platform: Linux 4.18.0-193.47.1.el8_2.x86_64 (x86_64)

**Comment by nijel** [comment]
It's just a display issue, it has been fixed today in 09c26381affe36cd5bfe1297524bd9585a7849ae.
