### ISSUE TITLE
Document appearance settings

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#6037]
**Describe the issue**

Documentation lacks info about appearance customization.

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**Expected behavior**

A short description about Weblate appearance customization options

**Comment by nijel** [comment]
I've just added a note on this in 4d6c2b6f1ce52d7c88e82e7159e414042bc9cc02, more docs is really needed here.
