### ISSUE TITLE
Edit translation memory. Howto?

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#6050]
This is a follow up to #5905, where "\r\n" escape sequences made it into the translations. I'd like to get rid of these once and for all so they don't turn up in automatic translations anymore.

I have downloaded the translation memory as json and found > 100 occurrences of this escape sequence. What is going to happen when I replace them all with "\n" and upload the translation memory to Weblate again? Will the upload replace the existing TM or will it live happily next to the existing TM? I will create duplicates, because currently the strings exists in a "\r\n" and a "\n" version right now. Will this cause trouble?

**Comment by nijel** [comment]
There is currently no interface for editing entries individually.

You can do that using `weblate shell` though. Something like this could work (the snippet is not tested at all):

```python
from weblate.memory.models import Memory
from django.db.models import Value
from django.db.models.functions import Replace

Memory.objects.filter(target__contains="\r\n").update(target=Replace("target", Value("\r\n"), Value("\n"))
```
