### ISSUE TITLE
Add option to make Weblate merge with --no-ff ("no fast forward") for the cleanest git history

### ISSUE THREAD

**Issue by shasheene** [WeblateOrg/weblate#6095]
I have configured Weblate to prefer a "Merge" style over the default "Rebase" style:

![merge style setting](https://user-images.githubusercontent.com/1414379/119771463-e9e3f980-befc-11eb-9df4-079785cc7c01.png)

From the Weblate user-interface I can create git commits out of the work the translators have done, then push the commits to the configured GitHub repository. Because the git commits on Weblate are building upon a git branch that is up-to-date, by default running `git merge` can and will do a "fast forward" merge, leading to the git history being the following (screenshot is of the `tig` tool):

![git history using tig example showing an ff merge](https://user-images.githubusercontent.com/1414379/119771457-e81a3600-befc-11eb-893d-cf2537212ca6.png)

My problem with the git history shown above combines the history of the software with the translations, which makes the history less useful for me. The git history I really would like to see is the following:

![git history using tig showing no-ff merge](https://user-images.githubusercontent.com/1414379/119771462-e94b6300-befc-11eb-8074-d77ab0d525bc.png)

Indeed, before I added Weblate's continuous localization today, the above screenshot was how I ensured my git history looked. I achieved by running `git fetch weblate` on my local repository followed by `git merge --no-ff weblate/master`, then I push my work to GitHub as usual. From `man git merge`:

```
       --ff
           When the merge resolves as a fast-forward, only update the branch pointer, without creating a merge commit. This is the default behavior.

       --no-ff
           Create a merge commit even when the merge resolves as a fast-forward. This is the default behaviour when merging an annotated (and possibly signed) tag that is not stored in its natural place in refs/tags/ hierarchy.
```

From what I can tell, Weblate is internally run `git merge weblate/master` before pushing the changes to the configured GitHub repository.

My suggestion is to add a checkbox option that is shown when using Weblate's Merge style to enable the "--no-ff" flag so that users can choose if they would prefer to always see a merge commit.

**Comment by rootbid** [comment]
Hey @nijel,
I am interested in working on this.

I was reading through the [components ](https://github.com/WeblateOrg/weblate/blob/bed7e1ab638367730845c7c1bae577015fa65f7e/weblate/trans/models/component.py#L490)and the [vcs/git](https://github.com/WeblateOrg/weblate/blob/bed7e1ab638367730845c7c1bae577015fa65f7e/weblate/vcs/git.py#L182) implementations. And I believe there are multiple ways to achieve this, here is what I think
1. We could enforce the `--no-ff` in the [vcs/git](https://github.com/WeblateOrg/weblate/blob/bed7e1ab638367730845c7c1bae577015fa65f7e/weblate/vcs/git.py#L182) for weblate to always create a merge commit.
2. We could introduce a new merge_style under MERGE_CHOICES that creates a merge commit. And the users can choose any particular merge_style based on preference. This implementation would require working on additional files which I'm unaware of at this moment. 

Please suggest.

**Comment by nijel** [comment]
Another option is to have a separate vcs backend, similarly to force push option. But I think having this in MERGE_CHOICES would be the best approach.

**Comment by nijel** [comment]
WIP pull request: https://github.com/WeblateOrg/weblate/pull/7130
