### ISSUE TITLE
Project can't be accessed when I login

### ISSUE THREAD

**Issue by unbranched** [WeblateOrg/weblate#6103]
As the title says, I can see this project:
https://hosted.weblate.org/projects/taiga/

until I login, then it says "Page not found". I already contacted Taiga support but they don't know why this happens and my nickname is not blacklisted.
I can see without any issues all other projects I contribute to.
If you need my Weblate nickname, I'll pm it.

**Comment by nijel** [comment]
Please write this together with your username on Hosted Weblate to care@weblate.org.

**Comment by nijel** [comment]
Automatic group assignments were not applied for some reason to some users. The fix is being applied right now.
