### ISSUE TITLE
Issue reported when creating component via "Translate Document"

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#6104]
When adding a new component to a project via **Translate Document**, a config error is shown which is not relevant.

Repo Steps:

1. In a project create a new component via **Translate Document**
2. Select the file you want to translate (e.g. demo-translation-file.odt)
3. Select the proposed Open Doc Format and confirm the default settings proposed by Weblate (the only change to the default I make/made is to disable **Edit base file**)
4. After the component is created, the following message is displayed.
![image](https://user-images.githubusercontent.com/26718215/119977387-a6e75c00-bfb8-11eb-87a5-f6aa1f15cdad.png)

Contrary to the message, the component is fully functional and target languages can be added.
The error does  not seem to be an error and should be handled differently, ie. not shown in the UI.

**Comment by ilocit** [comment]
To give this some context:
_I understand where this comes from, the new component obviously does not have any translations yet, because only one (source) document was uploaded. As a techie, this error might not be important and is ignored. But we are using Weblate also as a kind of "self-service" portal for our customers. And they reported this as an issue repeatedly and we have to deal with it ;-)
So it would be nice if this could be captured as a none-relevant error in case a single document is uploaded as a new translation component._

**Comment by nijel** [comment]
The question is what is the correct solution here - there are no translations, so it's pointless to have this in Weblate without them. 

* Should the wording be changed to guide the user more towards creating a translation instead?
* Should this be disabled for document like formats?
* Should the "Translate document" feature force user to select at least one language and create the translation while importing?

**Comment by ilocit** [comment]
I'd say whatever is the easiest to implement.
Maybe the wording is the easiest to adjust? So more like an info than a warning/issue?
Adding that if a monolingual document was uploaded, it is necessary to create at least one language in the Component UI.
If it is easy enough to "catch" this issue message in case of manually uploaded, monolingual documents, then it would be best just to suppress the message.
