### ISSUE TITLE
Some docs say that 4.x only supports Postgresql

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#6109]
**Describe the issue**

Upgrade instructions https://docs.weblate.org/en/weblate-4.0.4/admin/upgrade.html#migrating-from-other-databases-to-postgresql:
> If you are running Weblate on other dabatase than PostgreSQL, you should migrate to PostgreSQL as that will be the only supported database backend in the 4.0 release

So I already started migrating from Mysql to Postgres before noticing that other docs say that Mysql is still supported...

**I already tried**

N/A

**Expected behavior**

Docs being consistent.

Also, could you clarify what's the long term plan here, will Mysql be dropped at some point anyway? And if I'm upgrading from 3.x, at which point it's best/safest to switch to Postgres (on 3.x, 4.1.1, or latest)?

**Comment by nijel** [comment]
PostgreSQL is the recommended database for Weblate. The intention was to drop support for MySQL/MariaDB in the 4.0 release, but I got convinced to keep it (there is an issue for this, but I can't find it right now).

The point of migration from MySQL to PostgreSQL should not matter.
