### ISSUE TITLE
Customize JSON output add-on is not when using Component discovery add-on

### ISSUE THREAD

**Issue by remcohaszing** [WeblateOrg/weblate#6115]
**Describe the issue**

The _Customize JSON output_ add-on is not applied on components discovered using the _Component discovery_ add-on.

Recently someone added a new language to our project. We received a GitLab merge request where the original component has been formatted, but not the newly added languages for the automatically discovered components.

**I already tried**

N/A

**To Reproduce the issue**

See https://gitlab.com/appsemble/appsemble/-/merge_requests/1895/diffs

**Expected behavior**

All translation files should have been formatted using 2 spaces indentation. Instead, only the one for the original component is. This is also te only file that has been modified by the translator.

**Screenshots**

**Exception traceback**

**Server configuration and status**

Weblate installation: weblate.org service

**Weblate deploy checks**

**Additional context**

**Comment by nijel** [comment]
Do you have "Clone addons" enabled in the discovery?

**Comment by remcohaszing** [comment]
> Do you have "Clone addons" enabled in the discovery?

Yes.

Also I can see the _Customize JSON output_ add-on is enabled for all of the discovered components.

**Comment by nijel** [comment]
These are empty files created by Weblate, the add-on does not seem to apply in this case. It will get applied once some translation is made. I will check why it was not applied...

**Comment by remcohaszing** [comment]
Is the fix in production already? Someone just added another language and the files are still not formatted.

https://gitlab.com/appsemble/appsemble/-/merge_requests/1929/diffs

**Comment by nijel** [comment]
The fix is there, but there was a bug in it, and it was fixed in 92bb9ce62737c198159bbb9d69dfe3b9f396ec45
