### ISSUE TITLE
If you change the "Full name", it will look like another contributor.

### ISSUE THREAD

**Issue by baffclan** [WeblateOrg/weblate#6116]
**Describe the issue**
If you change a "Full name" on account/profile, it will look like another contributor in a PO file.

**To Reproduce the issue**

1. Download a tranlation file
   e.g. https://hosted.weblate.org/projects/weblate/languages/ja/
        Files -> Download tranlation
2. Open a tranlation file
  weblate-languages-ja.po
| # baffclan <baffclan_at_yahoo.co.jp>, 2020.
| # 日陰のコスモス <baffclan_at_yahoo.co.jp>, 2020, 2021.

**Expected behavior**

Update to new Full name + email address 
| # 日陰のコスモス <baffclan_at_yahoo.co.jp>, 2020, 2021.

The following is unnecessary: 
| # baffclan <baffclan_at_yahoo.co.jp>, 2020.

**Comment by nijel** [comment]
Right now, name and e-mail have to match to extend existing entries:

https://github.com/translate/translate/blob/5714d6fe0794cbfdbc9d7da216028d9bbf79228e/translate/storage/poheader.py#L397-L451

It could probably do something more clever in case only name changes, but I'm not confident if that is desired in all cases.

**Comment by fitojb** [comment]
Yeah, Transifex messed up my name badly too, and the only thing I could do was manually send PRs to all projects which had my name duplicated in PO files…

**Comment by fitojb** [comment]
This has implications for trans people: Weblate shouldn’t [dead-name](https://en.wikipedia.org/wiki/Deadnaming) them after they transition.

**Comment by nijel** [comment]
Weblate uses whatever name user configures. The past Git commits will contain previous name and rewriting history is not an option.

For changing the name in the file credits, Weblate would have to look into all translations the user has contributed to and change the name and e-mail accordingly. It's doable, but it could be a dangerous operation. It would be fragile and expensive operation,  and it could lead to DoS. So I don't think Weblate should be changing past entries.

**Comment by baffclan** [comment]
It turns out that this can cause some very difficult problems.
I am withdrawing this issue.
