### ISSUE TITLE
msgmerge ignores base language

### ISSUE THREAD

**Issue by PawelSpoon** [WeblateOrg/weblate#6127]
**Describe the issue**

our service team did update to 4.6.2 on 22.5. now a week after team reports that strings added to pot file do not get propagated to po files. we use monolingual gettext, have base language english and set as editable. this setting was agreed upon together with you guys. until recently the installed msgmerge addon would also update the english base file

**I already tried**

i have added a string to a different test component, pulled, checked for updates, changed edit base file flag etc.

**To Reproduce the issue**

1. Go to git, add a key to pot file and commit change (branch linked with weblate)
2. In weblate ui go to component, and execute a pull
3. go to translate and check if new strings are available: no they arent
4. go to git and check if weblate did a commit: yes it did but only for de, not for en po file
5. go to container and checks log (result see above)
6. create a new translation and check: new strings are not available in webui. 
7. go and check git for new translation: it contains all the strings (old and new)

**Expected behavior**

also base file should be updated with new keys as in earlier versions

**Screenshots**

**Exception traceback**
celery-notify stderr | [2021-06-01 12:23:30,527: INFO/MainProcess] Received task: weblate.accounts.tasks.notify_change[ccb16d85-32c1-41ea-9605-89fc46aea213]
6/1/2021 2:23:30 PM uwsgi stderr | [2021-06-01 12:23:30,570: DEBUG/562] tfms-cus/stmd: running post_update addon: weblate.gettext.msgmerge
6/1/2021 2:23:30 PM uwsgi stderr | [2021-06-01 12:23:30,633: INFO/562] tfms-cus/stmd: weblate.gettext.msgmerge addon skipped, new base was not updated

**Server configuration and status**

Weblate installation: weblate.org service / Docker / PyPI / other

**Weblate deploy checks**

**Additional context**

**Comment by nijel** [comment]
Weblate looks at the changes and triggers msgmerge only in case the pot file was changed. It seems like it didn't work as expected here.

From which version did you upgrade? Maybe this would help when searching for the regression...

**Comment by PawelSpoon** [comment]
Hi,
to me it seems like:
- it gets triggered by pot file change
- BUT it skips the base image

and until base image file is not updated weblate does not show the new key in any of the languages..
regarding version: i think it was 4.6.1 but need to wait for answer from the responsible person

**Comment by igorjesih** [comment]
Hello,
Weblate was upgraded from version 4.2.2. (docker tag 4.2.2-3)

**Comment by nijel** [comment]
The log says:

> weblate.gettext.msgmerge addon skipped, new base was not updated

It is not updating any files at this point...

>  Weblate was upgraded from version 4.2.2. (docker tag 4.2.2-3)

Ah, that's big step, that will be hard to look at the changes...

**Comment by PawelSpoon** [comment]
> The log says:
> 
> > weblate.gettext.msgmerge addon skipped, new base was not updated
> 
> It is not updating any files at this point...
> 
> > Weblate was upgraded from version 4.2.2. (docker tag 4.2.2-3)
> 
> Ah, that's big step, that will be hard to look at the changes...

yes it is not updating on purpose.
but if i interpret the commits in git correctly:
- it does react on pot file change
- it skips the en base language file
- it updates the de file

**Comment by nijel** [comment]
The behavior you describe might be caused by 3178f880e2b1b547c8a60226392dda77319df651
