### ISSUE TITLE
English translations created twice in a component when created through API

### ISSUE THREAD

**Issue by dakur** [WeblateOrg/weblate#6139]
# Issue

I use HTTP API to create components in Weblate. Until recently, everything worked fine, but suddenly it started to create two translations for English language.

The problem probably lies in the fact, that we use short language codes (`en`) instead of full ones (`en_GB`). So it creates `en` translations correctly, but also `en_US`, which is not desired.

![image](https://user-images.githubusercontent.com/9862581/120767070-21fdc480-c51b-11eb-86d5-d1211816e340.png)

# Request

The API request looks as follows:

```
POST /api/projects/PROJECT_NAME/components/
Content-Type: application/json

{
	name: 'CampaignEditingTakenOver',
	slug: '1b65293c-0f92-488e-87f0-1766097d5f17',
	vcs: 'git',
	repo: 'weblate://PROJECT_NAME/c19014e5-cd6f-4207-8d27-6b187ab18bbc',
	filemask: 'src/app/.../translations/CampaignEditingTakenOverPresenter+intl-icu.*.po',
	template: 'src/app/.../translations/CampaignEditingTakenOverPresenter+intl-icu.cs.po',
	edit_template: true,
	new_base: 'src/app/.../translations/CampaignEditingTakenOverPresenter+intl-icu.pot',
	file_format: 'po-mono',
	new_lang: 'add',
	source_language: {
		code: 'cs',
	},
}
```

# I already tried

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

# Expected behavior

To create only translations matching existing file names with the asterisk pattern from `filemask`.

# Server configuration and status

Weblate version: 4.6.2

I don't have access to the server, but I can ask for these information if you need it for resolving the issue. Please let me know.

I guess it had to be introduced in 4.6.x branch as I made successful API call on Apr 16.

**Comment by nijel** [comment]
Are both files present in the repository?

You might want to use https://docs.weblate.org/en/latest/admin/projects.html#language-aliases or https://docs.weblate.org/en/latest/admin/projects.html#language-filter

**Comment by dakur** [comment]
@nijel Yes, they are.

I've made a test – I deleted existing component (from GUI) which was already in Weblate (for a longer time) and re-created it with API again. It first created `Czech` correctly and `English` with ghost icon in the same time as well. Then – when the ghost icon from `English` disappeared – `English (United States)` has been created as well.

Also, I've noticed that this `English (United States)` translation was automatically created in all of my 50+ already existent components! So something had to change in Weblate itself. Is it an undocumented breaking change or bug or…?

I've scanned docs and found [language parsing codes](https://docs.weblate.org/en/latest/admin/languages.html#language-parsing-codes) but it didn't answer me on what language code format Weblate actually expects and what is unusual case I should handle with aliases or filters. Are short code formats such `cs`, `en` etc. unexpected?

However thanks for the tip, that should help as a workaround at least if it is a bug.

**Comment by nijel** [comment]
If language was added to all components you are most likely using https://docs.weblate.org/en/latest/admin/addons.html#add-missing-languages

**Comment by dakur** [comment]
Yes, that's true, I have this add-on enabled even though I probably don't need it in my workflow.

Still not pretty sure why that add-on evaluates that exactly `en_US` should be added when there are plenty of languages we don't provide translations for, but I don't want to waste your time on theoretical discussions.

Thank you for the tips. 👍
