### ISSUE TITLE
If some modifiers are included, the processing of each combination will not be processed correctly.

### ISSUE THREAD

**Issue by baffclan** [WeblateOrg/weblate#6146]
**Describe the issue**
If some modifiers(``foo``, ``bar`` or/and `website <https://www.weblate.org/>`_ ) are included, the processing of each combination will not be processed correctly in input box of target strings.

**To Reproduce the issue**

1. Open https://hosted.weblate.org/translate/weblate/documentation/ja/?checksum=9dcfc30675370951

The area surrounded by the modifier changes color, but this unit does not handle it correctly.

**Expected behavior**
Modifiers are processed correctly.

**Screenshots**
![Screenshot_docspo1700](https://user-images.githubusercontent.com/18899730/120915252-b9127a00-c6dd-11eb-8559-6e653b8e5a31.png)

**Server configuration and status**
weblate site:
hosted.weblate.org

weblate list_versions:
Weblate weblate-4.6.2-897-gb23440f4e7

**Additional context**
It is also reproduced in "Other languages".

There seems to be no problem with the documentation.
https://docs.weblate.org/ja/latest/admin/install.html#configuring-weblate-to-use-postgresql

**Comment by nijel** [comment]
This is an issue in PrismJS, I've reported it there: https://github.com/PrismJS/prism/issues/2940
