### ISSUE TITLE
Output css file different on each node (High availability)

### ISSUE THREAD

**Issue by adriandiazgar** [WeblateOrg/weblate#6154]
**Describe the issue**

When running weblate in a HA environment the frontend assets are generated on each pod using https://django-compressor.readthedocs.io/en/stable/ and get stored inside the `cache` folder.

It results on each time a request goes to weblate using a different css file and because the browser requests always the same css it only works when the browser hits the node having the requested css file.

**To Reproduce the issue**

Start a multi-node weblate cluster (using k8s) for example.
Make several requests and see how weblate doesn't work when it goes to the pods without the requested css.

**Expected behavior**

There should be only one group of frontend resources shared across all the nodes.

**Workaround**

Share all the css inside a shared volume, this way there would be one file generated per pod, but when the browser hits a pod, all the css will be available for all the pods.

**Server configuration and status**

Weblate installation: weblate.org service using Kubernetes (3 pods)

**Comment by nijel** [comment]
Are all nodes running same container versions with same configuration? The css file name should depend on the content only and should not change between container startups.

**Comment by nijel** [comment]
Can you please share the differing part of `manifest.json`? For me, the ordering of manifest.json entries varies between runs, but the content stays same.
