### ISSUE TITLE
Missing strings after import/reset for a subset of locales

### ISSUE THREAD

**Issue by akien-mga** [WeblateOrg/weblate#6155]
**Describe the issue**

After my last sync (see additional context) of [Godot Engine/Godot Documentation](https://hosted.weblate.org/projects/godot-engine/godot-docs) on Hosted Weblate, it seems like some source strings haven't been properly accounted for by Weblate for some languages.

This was reported here: https://github.com/godotengine/godot-docs-l10n/issues/13

Namely, the source POT file and the localized PO files should all have 16,342 strings, but for `zh_CN` and `pt_BR`, Weblate only reports and shows 16,060 strings:

![Screenshot_20210608_112241](https://user-images.githubusercontent.com/4701338/121159846-d9f8dd80-c84b-11eb-93c8-ce4ce051d2c7.png)

Yet when checking the Git repo or downloading the PO files from Weblate for those locales, Poedit properly reports 16,342 strings:

![Screenshot_20210608_112142](https://user-images.githubusercontent.com/4701338/121159710-b5046a80-c84b-11eb-9c98-b1c4ca919866.png)

I listed some of those missing strings here: https://github.com/godotengine/godot-docs-l10n/issues/13#issuecomment-856605925
It could be that advanced reST and RTD directives might have triggered a parser bug?

Alternatively, it could have just been a mishap during Reset, see "Additional context".

**I already tried**

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

Nothing so far. I suspect that re-syncing the repo might solve the issue, but before I do that I thought it could be useful to report it as a bug and see if any relevant debugging info can be found to improve Weblate.

**To Reproduce the issue**

1. Go to https://hosted.weblate.org/projects/godot-engine/godot-docs/
2. Compare strings count for https://hosted.weblate.org/projects/godot-engine/godot-docs/en/ and https://hosted.weblate.org/projects/godot-engine/godot-docs/zh_Hans/
3. Download zh_Hans PO and see that actual string count matches source POT/en PO, but not what Weblate shows.

**Expected behavior**

The strings count should be the same for all valid PO files synced from the same POT, if they pass `msgfmt -c` (which they appear to do).

**Screenshots**

See above.

**Exception traceback**

n/a

**Server configuration and status**

Weblate installation: Hosted Weblate, last sync on June 2, 2021: https://github.com/godotengine/godot-docs-l10n/commits/05b30269bce2106d9ed67812f6caf58cb74e310b

**Weblate deploy checks**

n/a

**Additional context**

In case it's relevant, my sync workflow for Godot projects is:

- Commit all from Weblate to the internal repo (it does not auto-commit to the upstream repo, I don't want that).
- Lock the Weblate repo.
- Copy translations manually from the Weblate repo to the upstream repo, commit all as one batch.
- Reset Weblate repo (on Godot Docs, this can take ~30 min and usually ends up with a timeout in the browser, though the Weblate repo does eventually match upstream).
- Unlock the Weblate repo.

So it could be that my issue is just a mishap during the Reset stage and would be solved by another Reset.

**Comment by Bubu** [comment]
I believe we are seeing something similar over at https://weblate.bubu1.eu/projects/schildichat/element-desktop/eu/

There's actually one string to translate but the Status says "All strings - 0 words".

**Comment by nijel** [comment]
It seems that Weblate did not parse the files during some repository update. I've now forced that using `weblate loadpo --force --foreground godot-engine/godot-docs`, and it seems to fixed that. The question is why it has happened...

**Comment by nijel** [comment]
...as for the workflow, why don't use [rebase](https://docs.weblate.org/en/latest/admin/projects.html#merge-style) + [squash](https://docs.weblate.org/en/latest/admin/addons.html#squash-git-commits) on Weblate side? That would create one commit you could directly merge (or going through the GitHub pull request) and it would avoid all the manual actions you do.
