### ISSUE TITLE
An ability to quicky search for labeled strings

### ISSUE THREAD

**Issue by FuriousDuck** [WeblateOrg/weblate#6161]
**Is your feature request related to a problem? If so, please describe.**

Search UI itself seems to be more technical than user-friendly to be honest. And at least query examples lack the one on how to search for strings labeled as 'label-name'

**Describe the solution you'd like**

It would be a great addition to:
1. Add the related example to search UI
2. Maybe add the UI option to select labels for search
3. Make labels clickable in the tranlsation UI to quickly search for strings labeled as 'label-name'

**Comment by nijel** [comment]
1 - The examples cannot cover everything, that is for the documentation:

https://docs.weblate.org/en/latest/user/search.html

2 - See https://github.com/WeblateOrg/weblate/issues/3063

3 - There are links for each label on the translation page:

![image](https://user-images.githubusercontent.com/212189/121380715-66d39200-c945-11eb-87a7-819daf91b678.png)

Where would you like to have them clickable as well?

**Comment by FuriousDuck** [comment]
> Where would you like to have them clickable as well?

Yup. I mean here, when you do translate the exact string, in the 'string information' block 
![image](https://user-images.githubusercontent.com/3840955/121383877-73a9b300-c950-11eb-9ec2-73ec5ff547e7.png)
