### ISSUE TITLE
Adding codeberg.org as auth backend

### ISSUE THREAD

**Issue by Bubu** [WeblateOrg/weblate#6163]
(https://codeberg.org is a free software, community-run git forge).

I've implemented https://github.com/python-social-auth/social-core/pull/595 to add a generic gitea auth backend. I also configured it to work with codeberg for my instance but it still said "gitea" without an icon on the login page.

To get the proper logo and name for this auth backend I patched https://github.com/WeblateOrg/weblate/blob/c531080bce7d5fb0e14a8ef19bfcc2aa65d933d7/weblate/accounts/templatetags/authnames.py#L29 and added the logo file into the weblate install, which is not ideal.

**Describe the solution you'd like**

I'd either like a configuration override for the auth names and icons or just add codeberg.org to that list of hardcoded providers. (I'm unsure how to add a different gitea instance then though)

**Screenshots**
The [result](https://weblate.bubu1.eu/accounts/login/?next=/) :-).

![image](https://user-images.githubusercontent.com/105185/121443864-9955ad00-c98e-11eb-8d3a-65ae53650b4b.png)

**Comment by nijel** [comment]
If you want to authenticate against more Gitea servers then a separate class as a authentication backend is needed.

For changing name and icon for the backend the best approach would be generalizing SOCIAL_AUTH_AUTH0_TITLE / SOCIAL_AUTH_AUTH0_IMAGE / SOCIAL_AUTH_SAML_TITLE / SOCIAL_AUTH_SAML_IMAGE approach to all backends. I've done that in 159ae591e91e7c2065ede9c39f14d743f5ab07e5.

**Comment by Bubu** [comment]
Thanks! That should do it form the weblate side.

> If you want to authenticate against more Gitea servers then a separate class as a authentication backend is needed.

I see, I suspected that much. It's not something I need right now, though.

(Feel free to close this, if this is solved from your side)
