### ISSUE TITLE
Watched translations (no more than 28 lines)

### ISSUE THREAD

**Issue by KovalevArtem** [WeblateOrg/weblate#6168]
**Is your feature request related to a problem? If so, please describe.**
If you start watching a lot of translations, then it turns out that all of them are not displayed in "Watched translations".
In order to see translation projects at the end of the alphabetical list, I have to stop watching any other projects. I find it inconvenient ...

**Describe the solution you'd like**
I suggest adding a setting for the "Watched translations" section with options for choosing the number of lines

- 5
- 10
- 15
- ...
- Everything

**Screenshots**
![image](https://user-images.githubusercontent.com/36500228/121590103-93b89f80-ca40-11eb-883b-ac5333c7e882.png)

**Additional context**

**Comment by nijel** [comment]
The list of watched should show up to 100 entries and is paginated so you can navigate to further entries:

![image](https://user-images.githubusercontent.com/212189/121649133-8a5b2180-ca98-11eb-8de3-b233b1dc7662.png)

**Comment by nijel** [comment]
...ah but the pagination is gone when hide completed is enabled.

**Comment by KovalevArtem** [comment]
![image](https://user-images.githubusercontent.com/36500228/121669409-f481bf80-cab4-11eb-9125-3e6b66228425.png)
Here is a screenshot of the entire page.
There is no page navigation, and it seems it never was (at least for me) ...
