### ISSUE TITLE
Weblate commits aren’t GPG signed

### ISSUE THREAD

**Issue by remcohaszing** [WeblateOrg/weblate#6175]
**Describe the issue**

Our commits from Weblate used to be signed using GPG. However, recent commits aren’t signed anymore.

https://gitlab.com/appsemble/appsemble/-/commits/main?author=weblate

I think this is because at some point we enabled the _**Squash Git commits**_ addon, or because we set _**Merge style**_ to _Rebase_ in project settings.

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

1. Make a contribution to https://hosted.weblate.org/translate/appsemble/appsemble
2. View the merge request created by Weblate on https://gitlab.com/appsemble/appsemble/-/merge_requests
3. Notice the commit is not signed

**Expected behavior**

The commit is signed

**Screenshots**

N/A

**Exception traceback**

N/A

**Server configuration and status**

Weblate installation: weblate.org service

**Weblate deploy checks**

N/A

**Additional context**

**Comment by nijel** [comment]
You might want to change to rebase style when using commit squashing, see https://docs.weblate.org/en/latest/admin/projects.html#merge-style

The bug here is in not signing merge commits with GitHub integration enabled.
