### ISSUE TITLE
Weblate 2.1 missing on PyPI

### ISSUE THREAD

**Issue by wichert** [WeblateOrg/weblate#618]
Can you upload Weblate 2.1 to PyPI?

**Comment by madmuffin1** [comment]
@wichert Hows your experience with the docker setup? We are currently running a weblate instance in a VM but'd like to migrate it into docker at some point.

**Comment by wichert** [comment]
@madmuffin1 I haven't had time to look at this in a while and had forgotten about it completely. I'll try to take another look later this week.

**Comment by wichert** [comment]
It seems there is a [bitnami weblate docker image](https://bitnami.com/stack/weblate), but it is locked behind a login so I have no idea what that looks like.

**Comment by wichert** [comment]
@nijel [wichert/docker-weblate](https://github.com/wichert/docker-weblate) has a working docker setup for weblate 2.2 now.

**Comment by nijel** [comment]
@wichert Can you turn it to pull request, so that required files can be shipped together with Weblate?

**Comment by wichert** [comment]
I can, but keep in mind that I'm not entirely happy with the current images
yet so this is of beta quality at best.

**Comment by nijel** [comment]
Okay, feel free to submit it once you're happy with it :-).
