### ISSUE TITLE
how i can push Weblate repostory back to github repository

### ISSUE THREAD

**Issue by qianqianluo** [WeblateOrg/weblate#6184]
**Is your feature request related to a problem? If so, please describe.**

**Describe the solution you'd like**
I want to  push Weblate repostory back to github repository

**Describe alternatives you've considered**
tried to click push, it is grey, i am not able to click it

**Screenshots**
![image](https://user-images.githubusercontent.com/31708677/122136132-b3601700-cdf6-11eb-89c6-1fbfdeaf1c78.png)

**Additional context**

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/devel/integration.html#fetching-updated-translations-from-weblate
