### ISSUE TITLE
Link between glossary term and source key gets lost

### ISSUE THREAD

**Issue by Rene-Cryptshare** [WeblateOrg/weblate#6193]
**Describe the issue**

When adding a new term to the glossary using the 'Add term to glossary' function in the translation section, the added term does not remain linked to the source key it was added to.

**I already tried**

Different types of glossary configurations, respectively the file type configuration were tried.

**To Reproduce the issue**

1. Open an existing translation component in the project containing some translation strings
2. Start the translation and click on 'Add term to glossary' on any item.
3. Fill in the form fields and add the new term. The glossary component shows the new term now
![image](https://user-images.githubusercontent.com/86038446/122343432-fa105700-cf45-11eb-83cd-4b207f3ae319.png)
4. Now forward to the next translation item and go back again.

**Expected behavior**

The glossary component shows the term as described in Step 3

**Actual behavior**

No term is shown, however the glossary contains the new term. Furthermore the fields do not match together and seem to be inconsistent as can be seen in the screenshot:
![image](https://user-images.githubusercontent.com/86038446/122345770-8459ba80-cf48-11eb-8b78-fd2ae369a8e4.png)

**Comment by Rene-Cryptshare** [comment]
I just realized, the the form for adding a term directly in the glossary component also looks entirely different compared to the ones shown under 'Actual behavior':
![image](https://user-images.githubusercontent.com/86038446/122348992-0c8d8f00-cf4c-11eb-949e-59036245ef88.png)

**Comment by comradekingu** [comment]
Why is it 
"clarify source strings" (plural) and not "clarify the meaning"?

Other suggestions:
"Auto-adjust context when an identical string exists" (What happens?)
"The string will propagate to the glossary in all languages"

**Comment by JohnRDOrazio** [comment]
I have noticed that even with Weblate 4.7.2, when using "Add term to glossary" from the sidebar of a translation component, the term and it's translation are added to the glossary with an empty key. Then when I try to "Add term to glossary" again, it fails, because it is trying to create a new term with an empty key, however an empty key already exists in the glossary. So there is a conflict of "two identical keys" (which are both empty).

Is this the issue that was fixed? Or should I open a new issue?

**Comment by nijel** [comment]
@JohnRDOrazio This should be fixed in 4.8 (and one more fix for glossary adding is in place for 4.8.1.).

**Comment by JohnRDOrazio** [comment]
I just tried in v4.8.1, and I see that the first key defined seems to have an empty key, whereas the next keys defined are numbered starting from 1. I am not getting an error when adding new glossary terms from the sidebar of a translation component.

**Comment by nijel** [comment]
Yes, the source / key combination has to be unique, so if the source already exists, unique key is automatically generated. But we're getting off-topic here...

**Comment by Rene-Cryptshare** [comment]
Ok, so what does that mean? Do you still consider this as closed? Because for me this issue still exists the way it initially was described.

**Comment by nijel** [comment]
The glossary sidebar shows matching terms. If the term is not present in the translated string, it won't be shown. There is no other linking of glossary terms to strings.
