### ISSUE TITLE
How to configure the case of Unicode characters in Java properties files?

### ISSUE THREAD

**Issue by vpyzhyanov** [WeblateOrg/weblate#6195]
**Describe the issue**

How to configure the case of Unicode characters in Java properties files? 
I use ISO-8859-1 encoding with **lowercase** encoding Unicode escape sequences. For example, '**\uabcd**' instead of '\uABCD'. But Weblate changes the case to uppercase for every translation performed.

**I already tried**

- I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.

**Expected behavior**

Setting is needed to change case.

**Comment by nijel** [comment]
This is currently hardcoded: https://github.com/translate/translate/blob/c680009db845ad6e64eee3fb3212e2ab5bd50b4f/translate/misc/quote.py#L359

**Comment by vpyzhyanov** [comment]
Thanks. Is it possible to add such a setting?

**Comment by nijel** [comment]
Everything is possible. It will need quite a lot of code changes, as there is currently no way to pass settings way down to this function.
