### ISSUE TITLE
Extra translateable text for website project on weblate

### ISSUE THREAD

**Issue by Blueberryy** [WeblateOrg/weblate#6226]
https://weblate.org/download/
![yjfzDFLk0e](https://user-images.githubusercontent.com/36592509/123328467-094e6080-d555-11eb-92dc-6522a94cafb8.png)
https://weblate.org/donate/
![opera_zySfu9riSa](https://user-images.githubusercontent.com/36592509/123328506-1408f580-d555-11eb-9ae6-48b77d7b776f.png)

**Comment by nijel** [comment]
Fixed in https://github.com/WeblateOrg/website/commit/8845dcd85bf93376e45adc72b668feaaeb5fd3d7

**Comment by Blueberryy** [comment]
Thank you
