### ISSUE TITLE
Add support for Localized Property List File (OS X >= 10.9 and iOS >= 7)

### ISSUE THREAD

**Issue by AL333Z** [WeblateOrg/weblate#623]
Hi guys,

In the past days i successfully set up weblate for a big iOS project.
Now i'm trying to figuring out how to properly manage plurals and genders using Weblate.

Some time ago [Apple introduced "Localized property list file"](https://developer.apple.com/library/ios/releasenotes/Foundation/RN-Foundation/#//apple_ref/doc/uid/TP30000742-CH2-SW56).

You can find more [here](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html) and another explanations [here](https://github.com/objcio/articles/blob/master/2014-02-10-string-localization.md#plural-and-gender-support).
Some nice guy also set up a test repository [here](https://github.com/ObjectiveToast/LocalizeTesting), demonstrating the usage of the new file (`.stringsdict`).

Any future plan to support this?

Thanks
##

**Comment by nijel** [comment]
Is this really used in the end? It seems that iOS is still either using old properties or XLIFF files...

**Comment by DagAgren** [comment]
.stringsdict is used for plurals.

**Comment by romanr** [comment]
This is a current official best practice for non plurals localization for macOS/iOS: https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html#//apple_ref/doc/uid/10000171i-CH5-SW10

**Comment by nijel** [comment]
See also https://github.com/translate/translate/issues/633

**Comment by reshadf** [comment]
6 years later still hoping this will be implemented someday. We now have to manually translate plurals in iOS because weblate doesn't recognize .stringsdict files.

**Comment by nijel** [comment]
Patches or funding of development is always welcome :-). There are nearly 300 open issues on this project, and we're not able to implement all of them as fast as we would like to.

**Comment by nijel** [comment]
Thanks to @x-sheep support for stringsdict has landed in translate-toolkit: https://github.com/translate/translate/pull/4398
