### ISSUE TITLE
 Zen mode Tab order does not honor sorting

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#6236]
Clicked "translate" to get to https://hosted.weblate.org/zen/tachideskjui/desktop/nb_NO/?q=state:%3Ctranslated

Expected tab to move only to the next field, but it seemingly skips at random.
Different results going back to do it again.

**Comment by nijel** [comment]
The tabindex does not respect ordering. It's always position-based even though the default ordering for glossaries is alphabetical.

**Comment by yarons** [comment]
I found a very lame workaround: Use Shift+Tab.

**Comment by nijel** [comment]
This should have been addressed by https://github.com/WeblateOrg/weblate/pull/11952
