### ISSUE TITLE
Github action fails with The process '/usr/bin/git' failed with exit code 1

### ISSUE THREAD

**Issue by Tbaut** [WeblateOrg/weblate#6240]
**Describe the issue**

We are running Github action for several tasks on the PRs that hosted weblate created on the repo. The problem is that the Github action checkout can't seem to be able to checkout the branch correctly.

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

1. Go to https://github.com/ChainSafe/files-ui/pull/1196
2. Scroll down to the Github action steps
3. Click on the linting job
```
Run actions/checkout@v2
Syncing repository: ChainSafe/files-ui
Getting Git version info
Deleting the contents of '/home/runner/work/files-ui/files-ui'
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/weblate-chainsafe-files-chainsafe-files-user-interface*:refs/remotes/origin/weblate-chainsafe-files-chainsafe-files-user-interface* +refs/tags/weblate-chainsafe-files-chainsafe-files-user-interface*:refs/tags/weblate-chainsafe-files-chainsafe-files-user-interface*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 10 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/weblate-chainsafe-files-chainsafe-files-user-interface*:refs/remotes/origin/weblate-chainsafe-files-chainsafe-files-user-interface* +refs/tags/weblate-chainsafe-files-chainsafe-files-user-interface*:refs/tags/weblate-chainsafe-files-chainsafe-files-user-interface*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 14 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/weblate-chainsafe-files-chainsafe-files-user-interface*:refs/remotes/origin/weblate-chainsafe-files-chainsafe-files-user-interface* +refs/tags/weblate-chainsafe-files-chainsafe-files-user-interface*:refs/tags/weblate-chainsafe-files-chainsafe-files-user-interface*
  Error: The process '/usr/bin/git' failed with exit code 1
```

**Expected behavior**
Checkout successful

**Screenshots**

**Exception traceback**

**Server configuration and status**

Weblate installation: weblate.org service

**Weblate deploy checks**

**Additional context**

**Comment by nijel** [comment]
Your pull request action is broken for pull requests from forks.

Removing the with for checkout action should fix that:  https://github.com/ChainSafe/files-ui/blob/83b333da328c79f7f23686db3dfdcd500b62dd6d/.github/workflows/lint.yml#L8-L10

The `github.event.pull_request.head.ref` is name of the branch in the fork repository, and you are trying to fetch it from the main repository.

**Comment by Tbaut** [comment]
Thank you very much, this works
