### ISSUE TITLE
Weblate seems to not be saving the translations for Portuguese-BR language

### ISSUE THREAD

**Issue by framabr** [WeblateOrg/weblate#6245]
** The Issue**
* Yesterday I worked a quite long time translating about 40 strings saving each of them.
* When I filtered the string to find only the translated one. There was just 1. (very weird) **
* Still weird... weblate showed the PT-BR translation for the string in its correspondent box, (which seemed that weblate saved them), but it simply seems to not count them as translated string when they are searched in the string filter field search.

**I already tried**

1.  I accepted the frustration of having lost all my already done translation.
2.  I went to Firefox browser, since I was working using Tor browser and eventually could be something from Tor that was not saving the translations.
3. I translated a couple of strings again, saving each of them, (but the bug was still there).
4. I opened this issue.

- [ ] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

1. Go to https://weblate.framasoft.org/translate/framadate/framadate/pt_BR/?q=state%3Aempty&sort_by=-priority%2Cposition&offset=2
2. Write several translated string into the Portuguese (Brazil) correspondent field, saving each of them.
3. Go to the seach fielter field and write: state:empty to see no translated stream and see that you will be able to see just one while the text of all the translation you did are still there.

**Expected behavior**
1. After filtering I expected to see the Portuguese (Brazil) field completely empty, not with the text from the already saved translate text.

**Screenshots**

**Exception traceback**

**Server configuration and status**

https://weblate.framasoft.org website.

**P. S. ** Just let you know that I am a 55 self-taught person and this is the first time I created a production Issue inside github.

**Weblate deploy checks**

**Additional context**

**Comment by framabr** [comment]
How can I share this issue with Framasoft?

**Comment by nijel** [comment]
There are now [107 translated strings](https://weblate.framasoft.org/translate/framadate/framadate/pt_BR/?q=state:%3E=translated).

Can you please share a permalink to a string which you've translated, and now it's not? Also, once we have that, it would be useful to have access to Weblate logs, so involving admins of that server will be needed...
