### ISSUE TITLE
C-format check doesn't allow positional values

### ISSUE THREAD

**Issue by sethhillbrand** [WeblateOrg/weblate#6249]
When the C-format check is enabled, positional arguments such as `%1$s` raise an error.

**I already tried**

- [X] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
- [X] The weblate documentation states that this format is supported (https://docs.weblate.org/en/latest/user/checks.html#c-format)

**To Reproduce the issue**

1. Go to 'https://hosted.weblate.org/translate/kicad/master-source/zh_Hans/?checksum=65ad27d657ff921f'
2. Note that the source string uses default position format (%s)
3. When translating to Chinese, the position of the arguments needs to change, so the positional format it used
4. Note that this fails the c-format check

**Expected behavior**

We expect that default order variables can be replaced in translation with positional variables without error

**Screenshots**

![image](https://user-images.githubusercontent.com/914826/124153889-c9eaad00-da49-11eb-997a-2573142970d3.png)

**Server configuration and status**

Observed on Weblate hosted instance

**Comment by nijel** [comment]
The check currently looks for same format strings as in the source. While this is the correct approach in most cases, it is better to use position-based format in the source string as well to make sure it is really supported by the printf engine (there used to be implementations which did not support this).

**Comment by sethhillbrand** [comment]
Thank you for looking into this.

Please note that even on systems where printf does not support this (and so it should not exist in the source string), `libintl.a` provides a replacement function that is activated for translations [1].

[1] https://www.gnu.org/software/gettext/manual/html_node/c_002dformat.html

**Comment by nijel** [comment]
I know it's possible to use libintl, but whether it is being used the translator typically does not know, that's why it's good to be explicit in the source string in this. 

Still, Weblate probably should not complain on this, as most platforms these days will support it.

**Comment by nijel** [comment]
I think this check is valid. The original string should have positional format strings if these are supported. It would also make obvious to translators how to reorder.
