### ISSUE TITLE
hoste.weblate.org - links get mangled

### ISSUE THREAD

**Issue by licaon-kter** [WeblateOrg/weblate#6258]
1. Go to https://hosted.weblate.org/translate/f-droid/website-posts/ro/?checksum=3155de3b1a1a0cde&sort_by=-priority,position#nearby
2. Fix the end link with the proper one from source string
3. Click on approve or for review
4. Save
4. See translated string as `...Weblate F-Droid (<https:>).</https:>`

**Expected behavior**

Translated string should be `...Weblate F-Droid (<https://hosted.weblate.org/languages/ro/f-droid/>).`

**Comment by eighthave** [comment]
We've been getting a lot of these on the Markdown/gettext sections of f-droid.org (f-droid/weblate-page, f-droid/weblate-posts, f-droid/weblate-docs).  I have a utility script to catch them when I merge.  The existing Weblate link checkers do mark these cases.

**Comment by nijel** [comment]
In this case, it is caused by `safe-html` flag - it treats the content as HTML, and performs cleanup on the string:

![obrazek](https://user-images.githubusercontent.com/212189/124755359-8e5d5080-df2b-11eb-829b-bcf98943e38f.png)

Using `safe-html` flag on non-HTML content can cause such issues.

**Comment by licaon-kter** [comment]
@nijel where is that controlled?

**Comment by eighthave** [comment]
I can handle it.

**Comment by eighthave** [comment]
Upon thinking about this, I guess the hard part here is that just about all HTML 
would be valid in Markdown, so _safe-html_ is quite useful for Markdown text. 
But then that does make it harder to write the _safe-html_ plugin.

Here's the official docs on using HTML in Markdown:
https://daringfireball.net/projects/markdown/syntax#html
