### ISSUE TITLE
Make the source of an automatic translation visible

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#6268]
Currently all automatic translation suggestions are by the user "anonymous".

![grafik](https://user-images.githubusercontent.com/3872576/124900990-e6568e80-dfe1-11eb-9389-2c9222e7ed24.png)

It would be nice to see if the machine translation was fetched from Weblate, DeepL or any other machine translation source.
For me it would be helpful, because I would generally prefer a phrase that was already translated in Weblate over a phrase that was translated by an external source.

I've only seen "Anonymous" and "new suggestion" up to now. Is there anything else than "new suggestion"?
Would it be possible to add something like "new suggestion (Weblate)" or "new suggestion (DeepL)" to indicate the translation source?

**Comment by nijel** [comment]
The origin is shown there:

![obrazek](https://user-images.githubusercontent.com/212189/125578551-920dfda3-d06a-49e4-90b3-8c0f937209bb.png)

**Comment by luebbe** [comment]
You're right. Can you guess why I missed this?

![grafik](https://user-images.githubusercontent.com/3872576/125583127-d6206d03-030f-4cea-84a3-96f7e756b350.png)

looking at the UI there are no automatic suggestions...

**Comment by nijel** [comment]
The motivation is to give more visibility to human suggestions - they are something what should be acted on, while the machine suggestions are present everytime.

**Comment by luebbe** [comment]
I thought so and I perfectly understand the reasoning, but it put (at least) me on a wrong path. To me it is an UI inconsistency, because you have "the same thing" split up into two places. Maybe it's not the same under the hood, but suggestions are suggestions, whether they are automatic or human.

How about a sorted list with the human suggestions always on top?

Crude UI mockup:

![grafik](https://user-images.githubusercontent.com/3872576/126946419-4f751802-fde6-434c-a387-32621c7a98e8.png)
