### ISSUE TITLE
Views are taking too much time to process when there are too many components and languages on the project

### ISSUE THREAD

**Issue by dgarana** [WeblateOrg/weblate#6269]
**Describe the issue**

When processing the `show_project` view, the request is taking too much time. This is not because of the rendering itself, this is because the ammount of data the context is requesting to generate before rendering the template.

We've identified that, although we are paginating the components inside a project, we are trying to retrieve all the languages stats for the whole project, which basically iterates over all the components for the specific project that we are requesting and then requests their languages and merges it's stats.

This process is taking too much time to compute (more than 30 minutes to process).

This is only happening, as I mentioned, when the project has too many components and those components are translated into too many different languages.

**I already tried**

Monkey patching the library in order to do not compute the information displayed on the "languages" tab in order to reduce the amount of operations executed against the database, and this has decreased the process down to 5 secs.

**To Reproduce the issue**

Create a Project with 15.000 components. Translate those components into different languages so the total languages for this project is more or less 120 (Components should be translated at least to 10 different languages).

After that, you'll see that when trying to process the `show_project` view, it will take more than 1 minute.

**Expected behavior**

The `show_project` view should be processed and rendered in a matter of seconds.

**Server configuration and status**

Tested on 4.6.1 and 4.7, both versions are facing the same issue.

**Comment by nijel** [comment]
Most of this should be addressed in https://github.com/WeblateOrg/weblate/commit/9262194e8aacffcd93000252ed22fcebaac8b183 - the component level stats were correctly updated, but the language level ones were not.

**Comment by nijel** [comment]
The additional performance improvements will be part of 4.9. For example, 0566fb8a40e2244ec86d6bc5b4286a6bccaf2d90 and 68a566c0b971a752e60a79d9f537368afd670609 should have a positive effect on your setup.
