### ISSUE TITLE
Component Discovery - usage of match groups results in "Undefined variable" error

### ISSUE THREAD

**Issue by wiedsche** [WeblateOrg/weblate#6270]
In older versions of weblate it was possible to use other variables than `{{ component }}` in the fields component name and base translation file in the component discovery extension.

In older versions of weblate it was possible to use named groups of the regular expression in these two fields. I'm not sure if it was supported in version upto 3.x or even upto a lower 4.x - but now in 4.7 it is not working any more.

1. Add extension "component discovery"
2. Set regular expression to: `src/(?P<component>[^/]*)/messages/messages\.(?P<language>[^.]*)\.(?P<customization>[^.]+)\.json`
3. Set component name to: `Messages - component - {{ component }}.{{ customization }}`
4. Set base file name to: `src/{{ component }}/messages/messages.en.{{ customization }}.json`
5. Save extension.
6. Error message at both fields: `Undefined variable: "customization"`

**Expected behavior**
The component discovery works without any issue, as it was working in older versions of weblate.

**Screenshots**

![image](https://user-images.githubusercontent.com/4105235/124904840-b4472b80-dfe5-11eb-954a-767a76c1a1e9.png)

**Server configuration and status**

Weblate installation: weblate.org service / Docker / PyPI / other

docker, weblate 4.7

**Comment by nijel** [comment]
This was never documented, but the discovery still works this way, it's just the form validation that block creating new discovery with such setup.

**Comment by wiedsche** [comment]
Great! Thank you for the quick support 👍 👍 👍
