### ISSUE TITLE
Glossary term explanation cannot be added or edited

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#6283]
**Describe the issue**

I added an abbreviation as glossary term to the source language (English) and tried to add an explanation.

![grafik](https://user-images.githubusercontent.com/3872576/125409006-c6491580-e3bb-11eb-8989-394e7c15348c.png)

Things I have observed:
1. You can enter a text "this is an explanation" into the "explanation" field, but the save button stays disabled
2. You can enter an explanation "this is another explanation" via the "explanation edit" dialog. The value you enter there overwrites the value you have previously entered into the "explanation" field, but the save button still stays disabled. The new explanation is visible twice. 
3. Removing the write protection via the drop-down menu has no effect.

The first screenshot shows the state after steps 1..2, the second one tries to further illustrate my observations.
If you "remove write protection" via the drop down, already entered explanations are lost.
Moving forward or back with the navigation buttons obviously loses the explanation

![grafik](https://user-images.githubusercontent.com/3872576/125408662-6ce0e680-e3bb-11eb-8423-e4c30ef385e1.png)

I would have expected the save button to be active or at least to become active after "remove write protection" was selected
I would have expected all edit functions to be disabled (edit fields, "pen" buttons",...) when the entry is write protected. When I can't edit or save an entry it should be clear from the start. Why should I waste my time entering information that can't be saved.

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.
- [x] I've searched the issue tracker and found no similar issue

**Server configuration and status**

Weblate 4.7.1 on docker

**Comment by nijel** [comment]
What are your component settings for "Manage strings" / "Monolingual base language file" / "Edit base file" on the glossary?

**Comment by luebbe** [comment]
Since I haven't touched anything in the glossary settings knowingly, I'd say "the weblate defaults". This is what I see in the glossary's Settings->Files:

![grafik](https://user-images.githubusercontent.com/3872576/126457743-e7749f96-1c92-4060-8a75-fff9ba155415.png)
