### ISSUE TITLE
Update to Source Sans 3 v. 3.046

### ISSUE THREAD

**Issue by fitojb** [WeblateOrg/weblate#6319]
Weblate currently uses Source Sans _Pro_ [v. 3.6.0](https://github.com/WeblateOrg/weblate/pull/2998), but newer versions of the font are called Source Sans _3_ and [the latest release](https://github.com/adobe-fonts/source-sans/releases/tag/3.046R) has a lower version number, weirdly (@adobe-fonts, you did make a mess here! :/). This will need CSS changes to update the font name.

**Comment by nijel** [comment]
Apparently, we're using https://yarnpkg.com/package/source-sans-pro which has been renamed to https://yarnpkg.com/package/source-sans. That's why we don't follow the updates...
