### ISSUE TITLE
`weblate migrate` terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by Real-Gecko** [WeblateOrg/weblate#6328]
Trying to install Weblate 4.7.2 [following this instruction](https://docs.weblate.org/en/latest/admin/install.html) leads to aforementioned error on `Filling up the database` step.

Tried to clone the repo and run project from there, get the same error with `manage.py migrate`

Describe the steps you tried to solve the problem yourself.

**To Reproduce the issue**

1. clone the repo
2. install dependencies
3. create postgresql db for the project
4. configure `settings.py` accordingly
5. run `python manage.py migrate`

**Expected behavior**

Database structure required for project is created.

**Screenshots**
![image](https://user-images.githubusercontent.com/2231969/126791867-daa39ffb-e381-42a7-9628-ab443c6a8d12.png)

**Exception traceback**

None, see screenshot.

**Server configuration and status**

Weblate installation: local from GitHub source code

./manage.py list_versions

* Weblate: weblate-4.7.2-57-gec27d923ea
 * Django: 3.2.5
 * siphashc: 2.1
 * translate-toolkit: 3.3.6
 * lxml: 4.6.3
 * Pillow: 8.3.1
 * bleach: 3.3.1
 * python-dateutil: 2.8.2
 * social-auth-core: 4.1.0
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.12.0
 * oauthlib: 3.1.1
 * django-compressor: 2.4.1
 * djangorestframework: 3.12.4
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 56.0.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.7
 * celery: 5.1.2
 * kombu: 5.1.0
 * translation-finder: 2.9
 * weblate-language-data: 2021.5
 * html2text: 2020.1.16
 * pycairo: 1.20.1
 * pygobject: 3.40.1
 * diff-match-patch: 20200713
 * requests: 2.26.0
 * django-redis: 5.0.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.3.0
 * Cython: 0.29.24
 * misaka: 2.1.1
 * GitPython: 3.1.19
 * borgbackup: 1.1.17
 * pyparsing: 2.4.7
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * Python: 3.7.11
 * Git: 2.32.0
 * psycopg2-binary: 2.9.1
 * ruamel.yaml: 0.17.10
 * Redis server: 6.2.5
 * PostgreSQL server: 13.3
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 5.13.4-arch1-1 (x86_64)

PC: Arch Linux, Core i7 7700, 32 GB RAM.

**Comment by nijel** [comment]
Seems like something is wrong with your hardware (eg. RAM), Python (maybe compiled for different CPU) or some of the Python modules. I'm not sure what is the best approach to debug this, though...

**Comment by Real-Gecko** [comment]
Any ideas where to dig? Other Django+PostgreSQL projects work flawlessly. My whole job is built around Django.

**Comment by nijel** [comment]
Getting a core dump and looking where it crashes would be a good starting point. See https://wiki.archlinux.org/title/Core_dump
