### ISSUE TITLE
Add string translatin status to history

### ISSUE THREAD

**Issue by KadAnna** [WeblateOrg/weblate#6340]
In the string history, I would like to see included changes of string status - to see who, when, what action made a string "waiting for review", "suggesttion", "approved".

**Comment by nijel** [comment]
It should be already visible there - there are separate history entries for these states:

https://github.com/WeblateOrg/weblate/blob/f73baa4d6e8631ffaf824f97cad3ccb489194eef/weblate/trans/models/change.py#L291-L294
