### ISSUE TITLE
Android parse error - Start tag expected, '<' not found, line 1, column 1 (<string>, line 1)

### ISSUE THREAD

**Issue by rtsisyk** [WeblateOrg/weblate#6345]
Here is a sample file which fails to parse by Weblate:

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Android Strings File -->
<!-- Generated by Twine 1.0.3 -->
<!-- Language: en -->
<resources>
	<!-- SECTION: Strings -->
	<!-- Button text (should be short) -->
	<string name="back">Back</string>
	<!-- Button text (should be short) -->
[REDACTED]
</resources>
```

<img width="719" alt="image" src="https://user-images.githubusercontent.com/1799054/127287686-b519461c-cec0-4662-bb61-5c3948a93727.png">

I guess that this problem is caused by comments. It would be nice to support comments. Comments are needed to know the context.

**Comment by nijel** [comment]
The problem is that you've configured  Intermediate language file to data/strings/strings.txt, what is not a XML file. Weblate wrongly reports where the parse error has happened, I'll fix that.

**Comment by rtsisyk** [comment]
I removed data/strings/strings.txt and it works now. Thanks!
