### ISSUE TITLE
PO file line wrapping discrepancy with gettext in specific case

### ISSUE THREAD

**Issue by alvinhochun** [WeblateOrg/weblate#6350]
**Describe the issue**

Weblate wraps a certain message differently than how gettext would as seen in these commits:

Weblate translation change commit: https://github.com/l10n-tw/krita-translation/commit/f428bc1bb822e3b7d97574285c272290f6433e0a#diff-53a66f86239a754a47aa04c28f7db47912d7f2afe96c16a67f6b3ee955b72f53R32237
msgmerge hook: https://github.com/l10n-tw/krita-translation/commit/029f6bec9c07d4334b1b2433fe341d8662e26a25#diff-53a66f86239a754a47aa04c28f7db47912d7f2afe96c16a67f6b3ee955b72f53R32247

**Expected behavior**

Weblate should produce line wrapping the same way as msgmerge.

**Weblate deploy checks**

I only have access to this list from "About Weblate":

> Weblate 4.7.2 Django 3.2.5 siphashc 2.1 translate-toolkit 3.3.6 lxml 4.6.3 Pillow 8.3.1 bleach 3.3.1 python-dateutil 2.8.2 social-auth-core 4.1.0 social-auth-app-django 4.0.0 django-crispy-forms 1.12.0 oauthlib 3.1.1 django-compressor 2.4.1 djangorestframework 3.12.4 django-filter 2.4.0 django-appconf 1.0.4 user-agents 2.2.0 filelock 3.0.12 setuptools 40.8.0 jellyfish 0.8.2 openpyxl 3.0.7 celery 5.1.2 kombu 5.1.0 translation-finder 2.9 weblate-language-data 2021.5 html2text 2020.1.16 pycairo 1.16.2 pygobject 3.30.4 diff-match-patch 20200713 requests 2.26.0 django-redis 5.0.0 hiredis 2.0.0 sentry_sdk 1.3.0 Cython 0.29.24 misaka 2.1.1 GitPython 3.1.18 borgbackup 1.1.17 pyparsing 2.4.7 pyahocorasick 1.4.2 python-redis-lock 3.7.0 Python 3.7.3 Git 2.20.1 psycopg2 2.9.1 psycopg2-binary 2.9.1 phply 1.2.5 chardet 4.0.0 ruamel.yaml 0.17.10 tesserocr 2.5.2 akismet 1.1 boto3 1.17.112 zeep 4.0.0 aeidon 1.9 iniparse 0.5 mysqlclient 2.0.3 Mercurial 5.8.1 git-svn 2.20.1 git-review 2.1.0 Redis server 6.2.4 PostgreSQL server 13.3 

**Additional context**

I suppose this is similar to https://github.com/WeblateOrg/weblate/issues/3852

**Comment by nijel** [comment]
I've already tried to address most of the differences in https://github.com/translate/translate/pull/3773, but as both wrapper implementations are using different methods, there will probably always be some differences.

**Comment by alvinhochun** [comment]
Is there a way to get Weblate to run msgmerge before commit then?

**Comment by nijel** [comment]
Not right now, the [msgmerge add-on](https://docs.weblate.org/en/latest/admin/addons.html#update-po-files-to-match-pot-msgmerge) is triggered on update, not on commit time.

**Comment by nijel** [comment]
Looking again at the diff, the translate-toolkit wrapping is based on characters, but the gettext one is based on bytes.

**Comment by alvinhochun** [comment]
This is perhaps a clearer example: https://github.com/l10n-tw/krita-translation/commit/2a14a8ea0f4d1a2b7589b39760d31dcead80cf59#diff-53a66f86239a754a47aa04c28f7db47912d7f2afe96c16a67f6b3ee955b72f53R22732
https://github.com/l10n-tw/krita-translation/commit/7692cc1f26accce593de2cd27e9ce48c2b7fe2a1#diff-53a66f86239a754a47aa04c28f7db47912d7f2afe96c16a67f6b3ee955b72f53R22730

> Looking again at the diff, the translate-toolkit wrapping is based on characters, but the gettext one is based on bytes.

I don't think it's really by number of bytes. CJK ideographs in UTF-8 are often 3 bytes long and even those wrapped by gettext has over 80 bytes. I recall there being a fullwidth property in Unicode (probably [East Asian Width](https://unicode.org/reports/tr11/)), maybe gettext is making use of that instead?

**Comment by nijel** [comment]
Yes, that might be it as well. I didn't really look deeper into that, but it seems that the difference is how the string length is measured.
