### ISSUE TITLE
Changing the configuration of the discovery addon deletes the history of the existing linked components

### ISSUE THREAD

**Issue by rsr-cs** [WeblateOrg/weblate#6355]
**Steps to reproduce**

1. Change the configuration of the dicsovery addon: Activate the option _Remove components for inexistant files_ 
2. Save the changes
3.  The complete history of the existing components is deleted

**Expected behavior**

The history of the existing components should be preserved with such changes in the discovery addon. At least there should be a warning that the existing history information will be lost.

**Comment by nijel** [comment]
It is not supposed to remove existing translations - it removes non-matched linked components where files are missing. Also, the removal happens as a last step, so it's unlikely to create blank components, it is more likely that it would just remove them. Maybe the file locations have changed in the repository and that caused recreating the components? Also, what Weblate version do you use?

**Comment by rsr-cs** [comment]
Is it possible that there is a delay after the changes have been saved? Now the history is back :-)

**Comment by nijel** [comment]
There should be no such delay, maybe the page was not fully loaded for some reason?
