### ISSUE TITLE
Mylocal istance not feel when I update the pot file

### ISSUE THREAD

**Issue by matteoopenf** [WeblateOrg/weblate#6358]
**Describe the issue**

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

2. Scroll down to '...'
3. Click on '...'

**Expected behavior**

When I upadate the pot file, my weblate istance not feel new term 

**Screenshots**

**Exception traceback**

**Server configuration and status**

Weblate installation: weblate.org service / Docker 

**Weblate deploy checks**

**Additional context**

**Comment by nijel** [comment]
Maybe https://docs.weblate.org/en/latest/faq.html#why-does-weblate-still-show-old-translation-strings-when-i-ve-updated-the-template?

**Comment by matteoopenf** [comment]
How can i receive help?

Matteo Mircoli
Developer | ***@***.*** 

> Il giorno 14 ago 2021, alle ore 03:48, github-actions[bot] ***@***.***> ha scritto:
> 
> ﻿
> Closed #6358.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 

_
Openforce Srls Unipersonale *| www.openforce.it 
<http://www.openforce.it/> |*__ 02 21119472 | Via Tiziano,32 20145 Milano_

**Comment by nijel** [comment]
Did you look at the documentation link

**Comment by matteoopenf** [comment]
Yeah, but I don’t find how to setup to check New pot file 



Matteo Mircoli
Developer | ***@***.*** 

> Il giorno 15 ago 2021, alle ore 07:02, Michal Čihař ***@***.***> ha scritto:
> 
> ﻿
> Did you look at the documentation link?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 

_
Openforce Srls Unipersonale *| www.openforce.it 
<http://www.openforce.it/> |*__ 02 21119472 | Via Tiziano,32 20145 Milano_

**Comment by nijel** [comment]
I don't know what you've tried and what is your configuration. Most likely you want a msgmerge add-on.

**Comment by matteoopenf** [comment]
> I don't know what you've tried and what is your configuration. Most likely you want a msgmerge add-on.

where can I check in my configuration?
