### ISSUE TITLE
ignore-end-ellipsis check doesn't ignore source language

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#6372]
**Describe the issue**

In order to turn off this quality check I set "ignore-end-ellipsis" at the component level for all components, but they still show up as failed quality checks:

![grafik](https://user-images.githubusercontent.com/3872576/127986005-cb1fdf2a-0723-4cca-9c95-a8047d61735b.png)

Detail for the first warning:

![grafik](https://user-images.githubusercontent.com/3872576/127985938-6d940282-6b2a-4b12-a5bf-2bf12983fec1.png)

**To Reproduce the issue**

The "ignore-end-ellipsis" tag was set yesterday afternoon after the component was created and content was uploaded (a few days ago). So since then more than 12 hours have passed. It is not clear to me, when this triggers. Do I have to wait hours/days/weeks until some housekeeping is done by weblate or is it expected to trigger (read: turn off the check and reflag everything) immediately when the component configuration is saved?

The behaviour was observed for "ignore-end-ellipsis", but maybe other checks are affected too?

**Expected behavior**

No warning for "ignore-end-ellipsis" should be shown.

**Server configuration and status**

Weblate installation: 4.7.2 on Docker

**Comment by nijel** [comment]
You want `ignore-ellipsis` instead. But this should be better documented.

**Comment by luebbe** [comment]
Thank you. I completely missed `ignore-ellipsis `. `ignore-end-ellipsis` was the first one I came across. Since all of them are at the end,  it was the logical choice.
