### ISSUE TITLE
Highlight unusual "space" characters in the editor

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#6377]
Following up to #6360 it would be nice, if the translation editor could highlight unusual space characters, like it does for linebreaks. Right now it is not possible to tell a NBSP from a normal space and a zero width space disappears entirely.

I'm specifically thinking of the space characters listed here: https://www.compart.com/en/unicode/category/Zs plus `U+200B` if that makes sense .

I'm not an expert on this subject, but I think everything apart from the standard space `U+0020` should be highlighted in order to tell the translator that there is an unusual space character, which may need to be preserved in the translation or which may have made it into the source language by accident.

**Comment by nijel** [comment]
It should be good enough to add these to the regular expressions here:

https://github.com/WeblateOrg/weblate/blob/fc8846c6f97207a449d1a42186897d6470046911/weblate/static/loader-bootstrap.js#L385

https://github.com/WeblateOrg/weblate/blob/fc8846c6f97207a449d1a42186897d6470046911/weblate/trans/templatetags/translations.py#L68
