### ISSUE TITLE
add non-breaking space for default french virtual keyboard

### ISSUE THREAD

**Issue by bikepunk** [WeblateOrg/weblate#6379]
**Is your feature request related to a problem? If so, please describe.**
French language needs non-breaking space before all double punctuation (:;!). there is no such key on standard french keyboard and no easy way to type without compose key.

**Describe the solution you'd like**
adding the non-breaking space in the french virtual keyboard.

**Describe alternatives you've considered**

**Screenshots**

**Additional context**

**Comment by nijel** [comment]
It is already included in the default [SPECIAL_CHARS](https://docs.weblate.org/en/latest/admin/config.html#special-chars):

https://github.com/WeblateOrg/weblate/blob/34c731a62009b594df67dfc39e9cd9a61a3087cd/weblate/trans/models/_conf.py#L174-L175

**Comment by bikepunk** [comment]
The instance I was using was not the latest. An upgrade will solve the issue. Many thanks for this software ;-)

**Comment by nijel** [comment]
The default setting was changed in 4.2 about one year ago in https://github.com/WeblateOrg/weblate/commit/bc2d9d20a56084577c8034e4a167260ec8f0a772. You can also change the configuration in your settings.py.
