### ISSUE TITLE
Change token in source PO-file from singular to plural form not shown in the translated languages

### ISSUE THREAD

**Issue by trapero** [WeblateOrg/weblate#6386]
Hi,

After integrate my VCS with Weblate to manage our translations, we experimented some problem updating the token structure. The system is configurated to work pulling PO-files (Gettext) from a branch and push the translation into another VCS which containts the new translated PO-files.

Let me explain it a bit deeper:

- **Source** -> It contents the original language in PO-files. Let's use as _source.po_ for this example.
- **Translation** -> It contents the original language in PO-files. Let's use as _translation.po_ for this example.

### **Start Stage**
The branch from the source repository contents the source file with the following content:

**source.po**
msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\n"
"Language: de\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

msgid "token_id"
msgstr "token_str"

, this is already translated by Weblate so we have the following content in the branch on the translated repository:

**translated.po**
msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\n"
"Language: de\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

msgid "token_id"
msgstr "token_str"

**Problem Stage**
Now  the issue comes when modifying the source token to be plural, let's change as follows:

 **source.po**
msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\n"
"Language: de\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

msgid "token_id"
msgid_plural "token_id"
msgstr[0] "token_singular_str"
msgstr[1] "token_plural_str"

**What are we expecting now?** Weblate should update this change, and after translation, update the **translated.po**

**What is happening?** Weblate updates the change, and show it as new translation for the language, but after translation the **translated.po** file does not change the token structure, it stays always singular:

**translated.po**
msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\n"
"Language: de\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

msgid "token_id"
msgstr "token_str"

**Server configuration and status**

Weblate installation: Docker

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/faq.html#why-does-weblate-still-show-old-translation-strings-when-i-ve-updated-the-template
