### ISSUE TITLE
Some buttons override the "All Strings" list

### ISSUE THREAD

**Issue by eshagh79** [WeblateOrg/weblate#6394]
**Describe the issue**
Character counter and right-to-left and left-to-right buttons are displayed in the "All Strings" list

**To Reproduce the issue**

1. Open the browser (Firefox 90.0.2)
2. Go to the translation page of a project (any project)
3. Click on "All Strings"

**Expected behavior**
I expect the character counter and right-to-left and left-to-right buttons to be hidden and not displayed in the "All Strings" list

**Screenshots**
![2021-08-06_12-1841Friday41](https://user-images.githubusercontent.com/52137191/128477505-e71a56dc-37e4-4fbf-b9d5-32443c5aee07.png)

**Server configuration and status**

Weblate installation: weblate.org

**Comment by nijel** [comment]
Probably z-index needs to be tweaked for these.
