### ISSUE TITLE
PostgreSQL Version in dev container

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#6407]
I'm trying to get my weblate dev docker up and running again in order to work on a feature request.

PostgreSQL doesn't start and keeps repeating the following message:
```
rundev.sh logs | grep database_1

database_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
database_1  | 
database_1  | 2021-08-10 07:04:33.102 UTC [1] FATAL:  database files are incompatible with server
database_1  | 2021-08-10 07:04:33.102 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 13.3.

```
running on lubuntu, apt update && apt upgrade done yesterday.

**I already tried**

I made my first steps with weblate development on 4.5.1 or 4.6, so I'm pretty sure that the database was created with the previous version of weblate. I've seen from the weblate commits that PostgreSQL has been updated to 13.
Where is this database stored?
* I didn't see anything in dev-docker/data 
* I tried to delete all docker containers and images

This is the output after deleting everything I could think of and calling `rundev.sh`.

```
lucky@lubuntubook:~/develop/weblate/dev-docker$ docker image ls
REPOSITORY        TAG         IMAGE ID       CREATED          SIZE
weblate-dev       latest      d91e4305fce7   22 minutes ago   1.14GB
weblate/weblate   bleeding    e26700b6c938   5 hours ago      772MB
redis             6-alpine    814803e951a7   3 days ago       32.3MB
postgres          13-alpine   f0b3bc4eab99   3 days ago       191MB
```
What am I missing? I'm still a total docker noob, so sorry if this is obvious to you.

**Comment by nijel** [comment]
If you don't care about the data, just drop the data volume in the postgres container and start from scratch.

In case you do care about the data, manual migration has to be done - first dump the data using old version and then load it into new PostgreSQL version. I'm sure you will find howtos for that.

**Comment by luebbe** [comment]
Thanks @nijel . I don't care about the data and I thought that I got rid of all containers by deleting all docker images. So I assumed I would start from scratch again. Is there something outside the container which I'm not aware of and that has to be purged manually?

**Comment by nijel** [comment]
You need to delete the Docker volumes as well, that's where Docker keeps persistent data.

**Comment by luebbe** [comment]
Thank you, I knew I missed something
