### ISSUE TITLE
Automatic translation does not update po files

### ISSUE THREAD

**Issue by paulpach** [WeblateOrg/weblate#6415]
I run automatic translation in my repo, and set it to mark entries as needing editing:

![Screen Shot 2021-08-11 at 6 57 19 PM](https://user-images.githubusercontent.com/466007/129118570-38de1eb6-3078-470e-b9bd-8edf855d9e66.png)

It goes through and does the machine translation:

![Screen Shot 2021-08-11 at 7 00 51 PM](https://user-images.githubusercontent.com/466007/129118641-d9f1afaf-ce06-4d51-84d9-142a9ad51e21.png)

I can click on the entries and I see that it successfully translated them and marked them as "needing editing"

![Screen Shot 2021-08-11 at 7 01 43 PM](https://user-images.githubusercontent.com/466007/129118698-4dfad450-e774-4a82-b810-7d5f82496896.png)

I would expect it to add those translations to the po file and mark them as fuzzy,  but it seems it does not modify the po files at all:

![Screen Shot 2021-08-11 at 7 03 19 PM](https://user-images.githubusercontent.com/466007/129118850-0315f35a-3c38-4e27-ad7d-1ee98417f2a0.png)

I could be wrong,  but it looks like the "needs editing" translations are stored in the database but are not saved in the po file.

**I already tried**

I set it to add as translation, and it successfully updates the po files,  but then they are not marked as fuzzy.  This is not great because I would like them to be marked somehow so that I can review them.

**To Reproduce the issue**

1. Add a gettext component from a git repo
2. Configure machine translation with google translate (I would assume other services have the same issue)
3. Open the component in weblate and click on tools -> Automatic translation
4. Select "Add as needing edit" in the automatic translation mode
5. set search filter to "strings needing action"
6. Set automatic translation source to "Machine translation"
7. Add google translate to the engines list
8. click on apply
9. once finished, click on Manage -> Repository Maintenance
10. Notice there are no pending changes or new commits at all.

**Expected behavior**

The translations should be added to the po file and marked as fuzzy.

**Exception traceback**

I don't see any error in the log at all

**Server configuration and status**

Weblate installation: weblate.org service / Docker / PyPI / other
running weblate in docker

```
* Weblate: 4.7.1
 * Django: 3.2.5
 * siphashc: 2.1
 * translate-toolkit: 3.3.6
 * lxml: 4.6.3
 * Pillow: 8.2.0
 * bleach: 3.3.0
 * python-dateutil: 2.8.1
 * social-auth-core: 4.1.0
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.12.0
 * oauthlib: 3.1.1
 * django-compressor: 2.4.1
 * djangorestframework: 3.12.4
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 45.2.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.7
 * celery: 5.1.2
 * kombu: 5.1.0
 * translation-finder: 2.9
 * weblate-language-data: 2021.5
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.36.0
 * diff-match-patch: 20200713
 * requests: 2.25.1
 * django-redis: 5.0.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.1.0
 * Cython: 0.29.24
 * misaka: 2.1.1
 * GitPython: 3.1.18
 * borgbackup: 1.1.17
 * pyparsing: 2.4.7
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * Python: 3.8.10
 * Git: 2.25.1
 * psycopg2: 2.9.1
 * psycopg2-binary: 2.9.1
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.17.10
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.17.111
 * zeep: 4.0.0
 * aeidon: 1.9
 * iniparse: 0.5
 * mysqlclient: 2.0.3
 * Mercurial: 5.8.1
 * git-svn: 2.25.1
 * git-review: 2.1.0
 * Redis server: 4.0.14
 * PostgreSQL server: 10.17
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.sendgrid.net
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.4.109+ (x86_64)
```

**Weblate deploy checks**

```
$ weblate check --deploy
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail (Connection unexpectedly closed), please check EMAIL_* settings.
        HINT: https://docs.weblate.org/en/weblate-4.7.1/admin/install.html#out-mail

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.7.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.7.1/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 4.7.2.
        HINT: https://docs.weblate.org/en/weblate-4.7.1/admin/upgrade.html

System check identified 7 issues (1 silenced).
```

**Additional context**

here is the link to the component I run it on:

http://translate.blockstory.net/projects/block-story/items/ka/#overview

This particular component is gettext, monolingual mode:
![Screen Shot 2021-08-11 at 7 18 57 PM](https://user-images.githubusercontent.com/466007/129119765-f853fabf-fabc-4f47-becf-ef7209da4421.png)

But the problem is the same in bilingual components.

**Comment by nijel** [comment]
Such strings should be in the PO file and marked as fuzzy there. Can you please share the file?

**Comment by paulpach** [comment]
Looks like I made a mistake here.  Sorry.
