### ISSUE TITLE
Normal users can mark approved source strings as needing changes

### ISSUE THREAD

**Issue by hhyyrylainen** [WeblateOrg/weblate#6416]
**Describe the issue**

I'm not 100% sure this is a bug, but reading the documentation it says: "For monolingual formats, the source string review behaves similarly as with Dedicated reviewers - once issue is reported on the source string, it is marked as Needs editing." and in that bit of documentation: "Reviewer can approve / unapprove strings."

So my understanding is that normal users **should not** be able to mark reviewed / approved (sorry I don't know the exact term as my interface language is Finnish) strings. But that's exactly what I see happening. This is the third time I see this happening, that a clueless user goes and marks a source string, that I have manually checked and marked as approved, as needing changes. Luckily I have source text change notification emails on so I notice this within a day and can fix it, but this is certainly annoying when users do that. I would much prefer if normal users (as the documentation says) would not be able to invalidate my approved source strings, instead they should comment / add a suggestion if they have found an actual problem.

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

1. Have a source string that is approved, and have the component wide source string reviews on. Also maybe use the .po format.
2. Mind your own business, happy that you have checked all source strings and have approved them.
3. See an email that a normal user has went and marked a source string as needing changes

**Expected behavior**

I expected that normal users (as the documentation seems to imply) would not be able to unmark (mark as needing changes) source strings being approved.

**Server configuration and status**

Weblate installation: other
(sorry my installation is probably not entire up to date as there isn't automatic update / single click update, I'll update it once I'm done writing this issue)

```
 * Weblate: 4.5.3
 * Django: 3.1.7
 * siphashc: 2.1
 * translate-toolkit: 3.3.4
 * lxml: 4.6.3
 * Pillow: 8.1.2
 * bleach: 3.3.0
 * python-dateutil: 2.8.1
 * social-auth-core: 4.1.0
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.11.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.4
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 49.1.3
 * jellyfish: 0.8.2
 * openpyxl: 3.0.7
 * celery: 5.0.5
 * kombu: 5.0.2
 * translation-finder: 2.9
 * weblate-language-data: 2021.3
 * html2text: 2020.1.16
 * pycairo: 1.20.0
 * pygobject: 3.40.1
 * diff-match-patch: 20200713
 * requests: 2.25.1
 * django-redis: 4.12.1
 * hiredis: 2.0.0
 * sentry_sdk: 1.0.0
 * Cython: 0.29.22
 * misaka: 2.1.1
 * GitPython: 3.1.14
 * borgbackup: 1.1.16
 * pyparsing: 2.4.7
 * pyahocorasick: 1.4.2
 * Python: 3.9.6
 * Git: 2.31.1
 * psycopg2-binary: 2.8.6
 * chardet: 4.0.0
 * ruamel.yaml: 0.17.2
 * boto3: 1.17.44
 * zeep: 4.0.0
 * aeidon: 1.9
 * git-review: 1.28.0
 * Redis server: 6.0.15
 * PostgreSQL server: 12.7
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.revolutionarygamesstudio.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 5.13.4-100.fc33.x86_64 (x86_64)
```

**Weblate deploy checks**

```
System check identified some issues:

WARNINGS:
?: (weblate.W025.ini) Failure in loading handler for ini file format: Missing iniparse library.
	HINT: https://docs.weblate.org/en/weblate-4.5.3/admin/install.html#optional-deps
?: (weblate.W025.islu) Failure in loading handler for islu file format: Missing iniparse library.
	HINT: https://docs.weblate.org/en/weblate-4.5.3/admin/install.html#optional-deps
?: (weblate.W025.laravel) Failure in loading handler for laravel file format: No module named 'phply'
	HINT: https://docs.weblate.org/en/weblate-4.5.3/admin/install.html#optional-deps
?: (weblate.W025.php) Failure in loading handler for php file format: No module named 'phply'
	HINT: https://docs.weblate.org/en/weblate-4.5.3/admin/install.html#optional-deps
?: (weblate.W033.Mercurial) Failure in loading VCS module for Mercurial: [Errno 2] No such file or directory: 'hg'
	HINT: https://docs.weblate.org/en/weblate-4.5.3/vcs.html
?: (weblate.W033.Subversion) Failure in loading VCS module for Subversion: git: 'svn' is not a git command. See 'git --help'.

The most similar commands are
	fsck
	mv
	show
 (1)
	HINT: https://docs.weblate.org/en/weblate-4.5.3/vcs.html

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.5.3/admin/install.html#collecting-errors
?: (weblate.I031) New Weblate version is available, please upgrade to 4.7.2.
	HINT: https://docs.weblate.org/en/weblate-4.5.3/admin/upgrade.html

System check identified 8 issues (1 silenced).
```

**Additional context**

Here's one source string where I just had to do this: https://translate.revolutionarygamesstudio.com/translate/thrive/thrive-game/en/?checksum=d4866890b4a60cbd#history

**Comment by nijel** [comment]
It really depends on whether user has privilege to do that, see https://docs.weblate.org/en/latest/admin/access.html#list-of-privileges

**Comment by hhyyrylainen** [comment]
Which (site wide) privilege I should be looking at? I've only found this part: https://docs.weblate.org/en/latest/admin/access.html#managing-per-project-access-control and added one user as a reviewer in the project as a test. I have not added review permission to any other user.

**Comment by nijel** [comment]
Only roles are kept in sync, you can customize the groups.

**Comment by hhyyrylainen** [comment]
I created a new role like this:
![Kuvakaappaus - 2021-08-19 15-50-25](https://user-images.githubusercontent.com/3796411/130071337-c6a11bf1-6a9a-4075-af64-417b6502a8b8.png)

and then replaced the default role in the users group:
![Kuvakaappaus - 2021-08-19 15-50-43](https://user-images.githubusercontent.com/3796411/130071352-7d2a8f7a-6157-446c-9a14-30350eedfbdf.png)


Is this the right approach? Or did you mean that the roles in a group are kept in sync, in which case this would be undone on an upgrade.

**Comment by nijel** [comment]
This should work fine.

**Comment by comradekingu** [comment]
This only "invalidates" review status because the "needs work" status is shared among more than one user?
