### ISSUE TITLE
Source strings not updated after msgmerge addon

### ISSUE THREAD

**Issue by alvinhochun** [WeblateOrg/weblate#6417]
**Describe the issue**

When I did a repo update from Weblate after updated POT files had been pushed to the repo, Weblate ran msgmerge and updated the translation PO catalogs, the changes visible from the Git history, yet the changed/new strings were not available on Weblate until I then merged the Weblate changes back into the master branch.

The POT updates are pushed to the `master` branch and Weblate is configured to pull from it.

Weblate is configured to push to the `weblate-stage` branch.

This is a bit confusing as I thought it was working normally a few days ago, as in the source string changes are immediately available as soon as I do repo update on Weblate. I am not aware of any changes to the server as Weblate has been staying at 4.7.2. A probable difference is perhaps that, in the past I have been explicitly committing the changes from inside Weblate before doing an update, while on the most recent occasions I only pressed update without first pressing commit (though I can't say for sure if I really did this or not).

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

1. Set up a repo with POT template and one PO catalog for a language
2. Set up a gettext PO component to pull from one branch and push to another
3. Set up the msgmerge addon
4. (may or may not need to?) Change a translation
5. Push updated POT templates with source string changes to the repo
6. Press "Update" from Weblate, then push
7. Verify that the push branch contains the msgmerge'd PO file
8. Check whether the new strings are available for translation from Weblate
9. Merge the push branch into the pull branch manually
10. Press "Update" from Weblate
11. Check whether the new strings are now available for translation from Weblate

**Expected behavior**

The new strings should be available from Weblate on step 8

**Server configuration and status**

```
 Weblate 4.7.2 Django 3.2.5 siphashc 2.1 translate-toolkit 3.3.6 lxml 4.6.3 Pillow 8.3.1 bleach 3.3.1 python-dateutil 2.8.2 social-auth-core 4.1.0 social-auth-app-django 4.0.0 django-crispy-forms 1.12.0 oauthlib 3.1.1 django-compressor 2.4.1 djangorestframework 3.12.4 django-filter 2.4.0 django-appconf 1.0.4 user-agents 2.2.0 filelock 3.0.12 setuptools 40.8.0 jellyfish 0.8.2 openpyxl 3.0.7 celery 5.1.2 kombu 5.1.0 translation-finder 2.9 weblate-language-data 2021.5 html2text 2020.1.16 pycairo 1.16.2 pygobject 3.30.4 diff-match-patch 20200713 requests 2.26.0 django-redis 5.0.0 hiredis 2.0.0 sentry_sdk 1.3.0 Cython 0.29.24 misaka 2.1.1 GitPython 3.1.18 borgbackup 1.1.17 pyparsing 2.4.7 pyahocorasick 1.4.2 python-redis-lock 3.7.0 Python 3.7.3 Git 2.20.1 psycopg2 2.9.1 psycopg2-binary 2.9.1 phply 1.2.5 chardet 4.0.0 ruamel.yaml 0.17.10 tesserocr 2.5.2 akismet 1.1 boto3 1.17.112 zeep 4.0.0 aeidon 1.9 iniparse 0.5 mysqlclient 2.0.3 Mercurial 5.8.1 git-svn 2.20.1 git-review 2.1.0 Redis server 6.2.4 PostgreSQL server 13.3 
```

**Additional context**

You may check our repo and match with the history on Weblate:

```
Repo: github.com/l10n-tw/krita-translation
Weblate history: weblate.slat.org/changes/?component=krita&project=krita
```

**Comment by nijel** [comment]
Are you using squash add-on as well? It might be fixed by https://github.com/WeblateOrg/weblate/commit/eaebcbdf7984632bcff088a459a51cdfcdb0bef3

**Comment by alvinhochun** [comment]
Yeah, I have the squash add-on for the project, so that fix does look relevant. Thanks for looking into this!

(I can't install the change though, so I'll have to wait for the next release and ask the sysadmin to upgrade.)

**Comment by nijel** [comment]
4.8 with this fix should be out this week
