### ISSUE TITLE
Add built-in per-project permission group to allow only "Add Suggestion"

### ISSUE THREAD

**Issue by alvinhochun** [WeblateOrg/weblate#6419]
**Is your feature request related to a problem? If so, please describe.**

I have a project access set to "Protected" and I would like to allow specific users to only add suggestions but not changing the translations directly. I know it is possible to add such custom permission from the Django admin interface, but I only have project adnimistration access right so can't directly change that.

It appears that if I add a custom group named "Project@Suggestion" copying "Project@Translate" but with only the "Add suggestion" role, and also keep the "Internal Weblate group" flag checked, then it becomes visible from the project user access control page and does what I want:

![圖片](https://user-images.githubusercontent.com/2397650/129185909-e9da0995-4b06-4d18-8bd6-88b63f03744b.png)

But I don't think this is the intended way to use that. Since the code of Weblate doesn't really know about this group, I imagine it may cause issues in the future.

**Describe the solution you'd like**

Consider adding a built-in "Add Suggestion" group to Weblate.

**Describe alternatives you've considered**

- I can ask the administrator to manually assign the group to users, but this gets really annoying for everyone involved.
- I can ask the administrator to do what I described above to allow me to assign the permission, risking breakage in the future.

**Comment by nijel** [comment]
Such group will be probably removed on upgrade.

The long term plan is to allow customization of these groups, but we're not yet there. Not sure if there is a issue covering this ...

**Comment by nijel** [comment]
Duplicate of #5560
