### ISSUE TITLE
"Squash Git commits" addon squashes already pushed commits, gets rejected for non-fast-forward

### ISSUE THREAD

**Issue by alvinhochun** [WeblateOrg/weblate#6423]
**Describe the issue**

The "Squash Git commits" addon, when I set it to "per author", squashes new commits with previous commits that had already been pushed to the push branch. Subsequently, when Weblate tries to push the new commits, it does not do force-push and thus fails with being rejected by remote due to non-fast-forward, requiring manual intervention.

**I already tried**

Describe the steps you tried to solve the problem yourself.

- I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
- I tried changing the merge style between "merge" and "rebase" with no observable differences.

**To Reproduce the issue**

1. Create a gettext PO component with different pull and push branches
2. Set up "Squash Git commits" addon to "per author"
3. Change a translation
4. Commit and push
5. Change another translation
6. Commit and push

**Expected behavior**

The push should not be rejected with "non-fast-forward"

**Server configuration and status**

```
 Weblate 4.7.2 Django 3.2.5 siphashc 2.1 translate-toolkit 3.3.6 lxml 4.6.3 Pillow 8.3.1 bleach 3.3.1 python-dateutil 2.8.2 social-auth-core 4.1.0 social-auth-app-django 4.0.0 django-crispy-forms 1.12.0 oauthlib 3.1.1 django-compressor 2.4.1 djangorestframework 3.12.4 django-filter 2.4.0 django-appconf 1.0.4 user-agents 2.2.0 filelock 3.0.12 setuptools 40.8.0 jellyfish 0.8.2 openpyxl 3.0.7 celery 5.1.2 kombu 5.1.0 translation-finder 2.9 weblate-language-data 2021.5 html2text 2020.1.16 pycairo 1.16.2 pygobject 3.30.4 diff-match-patch 20200713 requests 2.26.0 django-redis 5.0.0 hiredis 2.0.0 sentry_sdk 1.3.0 Cython 0.29.24 misaka 2.1.1 GitPython 3.1.18 borgbackup 1.1.17 pyparsing 2.4.7 pyahocorasick 1.4.2 python-redis-lock 3.7.0 Python 3.7.3 Git 2.20.1 psycopg2 2.9.1 psycopg2-binary 2.9.1 phply 1.2.5 chardet 4.0.0 ruamel.yaml 0.17.10 tesserocr 2.5.2 akismet 1.1 boto3 1.17.112 zeep 4.0.0 aeidon 1.9 iniparse 0.5 mysqlclient 2.0.3 Mercurial 5.8.1 git-svn 2.20.1 git-review 2.1.0 Redis server 6.2.4 PostgreSQL server 13.3 
```

**Additional context**

I can think of two possible fixes:

Fix 1: Add an option to the addon to not squash commits already pushed to remote.
Fix 2: Add an option for Weblate to always do force pushes, applicable when the push branch is different than the pull branch.

**Comment by nijel** [comment]
The add-on has no clue how do you handle pushed changes. It does rebase on top of upstream branch, not on top of pushed changes (what would be useless in most cases as commits are pushed immediately).

Use Git with force push if your workflow needs it.

**Comment by alvinhochun** [comment]
Oh sorry, I forgot/missed that there already is a force push option. I guess I completely glossed over that select combo box when hunting for the option. For some reason I was expecting there to be a "force push" checkbox somewhere.
