### ISSUE TITLE
Can add screenshot to language that I do not have permission for

### ISSUE THREAD

**Issue by StefanBrand** [WeblateOrg/weblate#6426]
**Describe the issue**

I have a group with following roles:
- Power user
- Manage Screenshots

 and following languages:
- Hungarian
- Romanian

Still, I can add a screenshot to language English. I cannot delete that screenshot later though.

**To Reproduce the issue**

1. Add a group with `Manage Screenshots` role and language restriction to e.g. Hungarian
2. Add user to group
3. Click "Add Screenshot" on a translation
4. Choose English
5. Screenshot is added
6. Click on "Delete" -> `Permission Denied - Insufficient privileges to display this page.`

**Expected behavior**

It is not possible to add a screenshot to a language that I do not have permission for.

**Server configuration and status**

Weblate installation: HelmRelease

**Comment by nijel** [comment]
The screenshot's permissions are currently mostly component-wide. I'm not sure changing this is a good idea - in most cases screenshots are uploaded to the source language and the typical use is that the person (or a bot) uploading screenshots does not have permission to edit the source language.
