### ISSUE TITLE
Error: module 'social_django.utils' has no attribute 'BACKENDS'

### ISSUE THREAD

**Issue by wjdfx** [WeblateOrg/weblate#6455]
**Describe the issue**
When I completed setup and login on web, I got a rewrite(<domain>/accounts/login/?next=/) and show error:
`
AttributeError at /accounts/login/
module 'social_django.utils' has no attribute 'BACKENDS'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/accounts/login/?next=/
Django Version:	3.2.6
Exception Type:	AttributeError
Exception Value:	
module 'social_django.utils' has no attribute 'BACKENDS'
Exception Location:	/root/weblate-env/lib/python3.6/site-packages/weblate/accounts/views.py, line 156, in get_auth_keys
Python Executable:	/root/weblate-env/bin/python3
Python Version:	3.6.9
Python Path:	
['/root',
 '/root/weblate-env/lib/python3.6/site-packages/git/ext/gitdb',
 '/root/weblate-env/bin',
 '/root/weblate-env/lib/python36.zip',
 '/root/weblate-env/lib/python3.6',
 '/root/weblate-env/lib/python3.6/lib-dynload',
 '/usr/lib/python3.6',
 '/root/weblate-env/lib/python3.6/site-packages',
 '/root/weblate-env/lib/python3.6/site-packages/django_social_auth-0.8.1-py3.6.egg',
 '/root/weblate-env/lib/python3.6/site-packages/python_social_auth-0.3.6-py3.6.egg',
 '/root/weblate-env/lib/python3.6/site-packages/gitdb/ext/smmap']
Server time:	Sat, 21 Aug 2021 11:22:51 +0000
`

**I already tried**

upgrade django-social-auth to 0.8.1

python version : Python 3.6.9

pip3 list | grep auth
django-social-auth     0.8.1
oauthlib               3.1.1
python-social-auth     0.3.6
requests-oauthlib      1.3.0
social-auth-app-django 5.0.0
social-auth-core       4.1.0

- [*] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

1. Go to 'https://translate.bitcat365.com/accounts/login/?next=/'
2. See error

**Comment by nijel** [comment]
* django-social-auth is not used by Weblate (and never was)
* The problem is in  social-auth-app-django 5.0.0
* If you break Weblate dependencies, things might break, Weblate 4.7 needs social-auth-app-django==4.0.0
* If you need social-auth-app-django==5.0.0 install Weblate 4.8

**Comment by wjdfx** [comment]
> * social-auth-app-django

Thanks. I follow this guide and first time excute `pip install Weblate` I got: 3.2.6
I just excute`pip3 install --upgrade weblate` got Welate, it's works now.
