### ISSUE TITLE
Can't dismiss warnings ("Things to check") on projects where I'm the admin

### ISSUE THREAD

**Issue by realpixelcode** [WeblateOrg/weblate#6467]
I'm the creator and admin of the [Sijacom project](https://weblate.bubu1.eu/projects/sijacom/) on Bubu's Weblate server. There are some warnings about some translation strings, for example `unchanged translation` or `The string uses three dots (...) instead of an ellipsis character (…)`. 

Trying to dismiss those warnings fails and I always get the error "Forbidden" in a red popup. This happens regardless of the language.

I have no clue what might be the reason and Bubu (the server admin) has already looked at the logs but didn't find anything.

`unchanged translation` warning:

![Sijacom Weblate forbidden before](https://user-images.githubusercontent.com/52963327/130646966-796631e7-ba67-4ce1-8340-4da69626a41a.png)

`Forbidden` error after clicking on `Dismiss`:

![Sijacom Weblate forbidden after](https://user-images.githubusercontent.com/52963327/130646941-3fa6b53d-12ad-4f4c-a189-b852dd8293c0.png)

**Comment by nijel** [comment]
Is the check actually dismissed? How does it look when you reload the page? Do you get any JavaScript errors in the browser?

**Comment by Bubu** [comment]
It produces a 403 error server side (seen in webserver logs, I can't see anything logged by weblate about this.)

**Comment by nijel** [comment]
You can also try removing cookies for the domain. I've seen some similar weird errors when bot secure and insecure cookies were set in the browser.
