### ISSUE TITLE
Add component missing options

### ISSUE THREAD

**Issue by CaiMiao** [WeblateOrg/weblate#6474]
**Describe the issue**

Missing other options which can be found <https://docs.weblate.org/en/latest/admin/projects.html>

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [X] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

1. Add new translation component

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/4640483/130990328-f28f89a0-425f-44dd-9138-584fadef7809.png)

**Exception traceback**

**Server configuration and status**

Weblate installation: own hosted 

**Weblate deploy checks**

~# weblate list_versions
 * Weblate: 4.8
 * Django: 3.2.6
 * siphashc: 2.1
 * translate-toolkit: 3.4.0
 * lxml: 4.6.3
 * Pillow: 8.3.1
 * bleach: 4.1.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.1.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.12.0
 * oauthlib: 3.1.1
 * django-compressor: 2.4.1
 * djangorestframework: 3.12.4
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 54.1.2
 * jellyfish: 0.8.2
 * openpyxl: 3.0.7
 * celery: 5.1.2
 * kombu: 5.1.0
 * translation-finder: 2.10
 * weblate-language-data: 2021.5
 * html2text: 2020.1.16
 * pycairo: 1.20.1
 * pygobject: 3.40.1
 * diff-match-patch: 20200713
 * requests: 2.26.0
 * django-redis: 5.0.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.3.1
 * Cython: 0.29.24
 * misaka: 2.1.1
 * GitPython: 3.1.18
 * borgbackup: 1.1.17
 * pyparsing: 2.4.7
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * Python: 3.6.8
 * Git: 1.8.3.1
 * psycopg2-binary: 2.9.1
 * ruamel.yaml: 0.17.13
 * Redis server: 4.0.9
 * PostgreSQL server: 10.17
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:36379, redis://localhost:36379, regular
 * Platform: Linux 5.1.9-1.el7.elrepo.x86_64 (x86_64)

**Additional context**

I'm a hobbist and not really good at deploying such things, i just want to trial out the weblate functions... and i stuck here.

**Comment by CaiMiao** [comment]
> Most of the choices depend on local VCS, maybe you have disabled it in https://docs.weblate.org/en/latest/admin/config.html#vcs-backends?

i did follow typical installation of docs but i skipped all optional packages to minimize it, can you please tell me which one i should install if i want to use via manual file upload?

**Comment by nijel** [comment]
Did you customiez VCS_BACKENDS setting? Just commet it out in your settings.py.

**Comment by CaiMiao** [comment]
> Did you customize VCS_BACKENDS setting? Just comment it out in your settings.py.

nope? all `vcs` related line in my `settings.py` as below.

![image](https://user-images.githubusercontent.com/4640483/131294343-7e7b1b57-3cd9-49ac-b50d-43634aa036a7.png)

**Comment by CaiMiao** [comment]
seems my git from centos 7 default repo (1.8.x) is not accepted by weblate, installing a new one fixed this atm.

**Comment by CaiMiao** [comment]
> Yes, git 2.12 is required, but that should be visible in the deploy checks...
was not aware that even flat files need git... but anyway thanks.
