### ISSUE TITLE
safe-html doesn't allow & in string

### ISSUE THREAD

**Issue by Findus23** [WeblateOrg/weblate#6490]
**Describe the issue**

Source string: `User Access Attribute Server & Site List Separator`
Translation: `Benutzerzugriffs Eigenschaft Server- & Seitenlisten-Separator`
The safe-html check complains that "The translation uses unsafe HTML markup"-

Testing this case in bleach shows that this is caused by bleach replacing the & with &amp; which makes the strings different:

```text
extracted tags:
{'tags': {'p'}, 'attributes': defaultdict(<class 'set'>, {'p': set()})}
cleaned:
Benutzerzugriffs Eigenschaft Server- &amp; Seitenlisten-Separator
target:
Benutzerzugriffs Eigenschaft Server- & Seitenlisten-Separator
True
```

<details>
<summary>source code</summary>

```python
from collections import defaultdict

import bleach
from lxml.etree import HTMLParser

IGNORE = {"body", "html"}


class MarkupExtractor:
    def __init__(self):
        self.found_tags = set()
        self.found_attributes = defaultdict(set)

    def start(self, tag, attrs):
        if tag in IGNORE:
            return
        self.found_tags.add(tag)
        self.found_attributes[tag].update(attrs.keys())


def extract_bleach(text):
    """Exctract tags from text in a form suitable for bleach."""
    extractor = MarkupExtractor()
    parser = HTMLParser(collect_ids=False, target=extractor)
    parser.feed(text)
    return {"tags": extractor.found_tags, "attributes": extractor.found_attributes}


def check_single(source, target):
    print("extracted tags:")
    print(extract_bleach(source))
    print("cleaned:")
    print(bleach.clean(target, **extract_bleach(source)))
    print("target:")
    print(target)
    return bleach.clean(target, **extract_bleach(source)) != target


if __name__ == '__main__':
    result = check_single(
        'User Access Attribute Server & Site List Separator',
        'Benutzerzugriffs Eigenschaft Server- & Seitenlisten-Separator'
    )
    print(result)
```

</details>

**I already tried**

Adding the `ignore-safe-html` flag to the string fixes it, but I think it would be better if the check would be adapted to work around this bleach detail, so it can be more generally helpful.

**To Reproduce the issue**

Create a translation string as given above (one containing `<` or `>` also works) and add the `safe-html`

**Expected behavior**

The check should only trigger if the actual HTML differs.

**Server configuration and status**

hosted.weblate.org

**Comment by nijel** [comment]
The check is intended to validate whether the string is valid HTML, what is not the case in the above examples. The question is whether it should try to detect that the source is not a valid HTML either and ignore such string completely.

**Comment by jralls** [comment]
We just encountered this problem translating sources for gettext po files. `safe-html` is flagged on the community localization checklist with a big orange warning symbol. The documentation doesn't say anything about it gratuitously inserting HTML entities into strings that aren't HTML and where they don't belong.

The warning should be removed from the community localization checklist and the documentation for the tag should have a warning that it should be used *****only***** for projects in which *****all***** translatable strings are HTML or XML.

**Comment by nijel** [comment]
Let's deal with the checklist in https://github.com/WeblateOrg/weblate/issues/9497

**Comment by nijel** [comment]
https://github.com/WeblateOrg/weblate/issues/9497 was addressed and I think the `safe-html` flag behaves as expected and therefore closing this issue.
