### ISSUE TITLE
Link to repostitory of Component

### ISSUE THREAD

**Issue by Findus23** [WeblateOrg/weblate#6496]
**Is your feature request related to a problem? If so, please describe.**

This is quite a minor feature, but with a lot of components pointing to a lot of plugins repositories it would sometimes be nice to quickly jump there. 

**Describe the solution you'd like**

So it would be great if a component has a remote repository, there would be a link somewhere (maybe in one of the drop-down menus) that would link to this repository. I'm not entirely sure what the best location for this is.

**Describe alternatives you've considered**

Otherwise, when I have to check the repo of `Plugin SomePlugin` I need to search for `someplugin` in my browser history to quickly find the repo.

**Comment by nijel** [comment]
The link to the repository is on the info tab (if you have privileges to see that), for example see https://hosted.weblate.org/projects/weblate/website/#information.

It's not clickable though, as it is not browsable in many cases.

**Comment by Findus23** [comment]
Thanks, I missed that (I only knew of the box in the repository maintenance).

Maybe one could make it clickable if it is known to be browsable (e.g. if it is a http URL pointing at github or gitlab (and maybe others)), but I get that this is quite specific and low priority.
