### ISSUE TITLE
RepositoryException: fatal: bad object

### ISSUE THREAD

**Issue by differentlocal** [WeblateOrg/weblate#6502]
**Describe the issue**
Hello!
After migrating from 'repository for each component' to 'single repository for all components' model (by changing repository url from ssh://git@... to weblate://maincomponent) on some components I got an exception when trying to open component's page:   
```
RepositoryException at /projects/metainfo/365support/
fatal: bad object c4cf0fcb5e73751b669b567458e439ec76e46a15
 (128)
Request Method:	GET
Request URL:	https://hostname/projects/metainfo/365support/
Django Version:	3.2.6
Exception Type:	RepositoryException
Exception Value:	
fatal: bad object c4cf0fcb5e73751b669b567458e439ec76e46a15
 (128)
Exception Location:	/usr/local/lib/python3.7/dist-packages/weblate/vcs/base.py, line 212, in _popen
Python Executable:	/usr/bin/uwsgi-core
Python Version:	3.7.3
Python Path:	
['/',
 '/usr/local/lib/python3.7/dist-packages/git/ext/gitdb',
 '/usr/local/lib/python3.7/dist-packages/',
 '.',
 '',
 '/usr/lib/python37.zip',
 '/usr/lib/python3.7',
 '/usr/lib/python3.7/lib-dynload',
 '/usr/local/lib/python3.7/dist-packages',
 '/app/data/python',
 '/usr/lib/python3/dist-packages',
 '/usr/local/lib/python3.7/dist-packages/gitdb/ext/smmap']
Server time:	Wed, 01 Sep 2021 13:13:37 +0000
```
**I already tried**

- Update repository of main component
- Force synchronize repository of main component
- Restart weblate

It doesn't help.

**Exception traceback**

Full traceback attached as file to the task.

**Server configuration and status**

Weblate installation: Docker 
Weblate version: 4.8.0
[Weblate exception.log](https://github.com/WeblateOrg/weblate/files/7091386/Weblate.exception.log)

**Comment by differentlocal** [comment]
Thanks you a lot, everything is fine now.

**Comment by petrkr** [comment]
Hello,
what is solution ? I have same issue now, I am using latest pip version. It seems like did remote checkup for latest revision, but does not pull it, thus make error "bad object" because localy it does not exists, but already trying show remote commit

Weblate error:
```
RepositoryException
--
fatal: bad object 980dfff79191ca4f04224202de10bed8e4abdd28  (128)
/var/lib/weblate/venv/lib/python3.9/site-packages/weblate/vcs/base.py, line 211, in _popen
```


Local git:
```
root@ovtranslate:/var/lib/weblate/data/vcs/....# git log
commit 95186fa940394c422674d70a73f1dd74f1dd3629 (grafted, HEAD -> master, origin/master)
Author: Open Vision translation bot <bot@openvision.tech>
Date:   Sun Sep 26 11:22:16 2021 +0000
```

Remote git (after manual git pull):
```
root@ovtranslate:~/enigma2# git log
commit 980dfff79191ca4f04224202de10bed8e4abdd28 (HEAD -> master, origin/master)
Author: Open Vision translation bot <bot@openvision.tech>
Date:   Sun Oct 3 01:57:22 2021 +0000

    Update po files using updateallpo-multiOS.sh using https://github.com/OpenVisionE2/enigma2-openvision

commit 95186fa940394c422674d70a73f1dd74f1dd3629 (grafted)
Author: Open Vision translation bot <bot@openvision.tech>
```

Maybe I am missing something, but does weblate should do git pull itself ?

**Comment by nijel** [comment]
Weblate does `git fetch origin` and then looks for the remote commit in the fetched remote. The original issue was for the linked components, are you using that? Did you do something manually in the repository? What Weblate version do you use?
