### ISSUE TITLE
Rendered font size is bigger than it should be

### ISSUE THREAD

**Issue by RoeelCohen** [WeblateOrg/weblate#6503]
**Describe the issue**

I uploaded the `Segoe UI` font to Weblate, set it in a font group, and added checks for text with the following flags:
`font-size:12, max-size:145, font-family: segoeui`
The rendered text always exceeds the size in the flag even in English (and even with few extra pixels).
The `max-width` actually shows 140 px but the rendered text itself is bigger and breaks the line.

**I already tried**

Just to be certain I doubled checked both the design on figma and my react project, they both are matching.
I also tried to play with different fonts of same family - light, semi bold, etc.

- [x ] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

1. Download [Segoe UI font](https://www.cufonfonts.com/font/segoe-ui-4)
2. upload `Segoe UI.ttf` to weblate and add it as a font family under the name `segoeui`
3. Add a string with flags of `font-size:12, max-size:145, font-family: segoeui`
4. Set the string value in English to: `Upgrade your protection`
5. See that the check is failing.

**Expected behavior**
check should not fail, it should match in 141 px width

**Screenshots**

Check:
<img width="406" alt="Screen Shot 2021-09-01 at 18 00 49" src="https://user-images.githubusercontent.com/18325304/131698833-ec46f5e7-d638-48c5-ba10-05fd3c374709.png">

React:
<img width="332" alt="Screen Shot 2021-09-01 at 18 16 12" src="https://user-images.githubusercontent.com/18325304/131698894-00e9d0b4-bd93-449a-af17-723d41272454.png">

Figma:
<img width="614" alt="Screen Shot 2021-09-01 at 18 24 51" src="https://user-images.githubusercontent.com/18325304/131699108-008138f4-5505-489f-aaf9-b637985952d2.png">

**Server configuration and status**

Weblate installation:  Docker @ version. 4.7.1

**Comment by nijel** [comment]
It seems to be using different font (look at the g letter). Are you sure that the font group name matches what is in the flags? Can you try if removing space from `font-family: segoeui` will make a difference?

**Comment by fitojb** [comment]
@RoeelCohen Also, you should get your Segoe fonts from Microsoft directly (https://aka.ms/segoeuifont), not a random third-party site.

**Comment by RoeelCohen** [comment]
> It seems to be using different font (look at the g letter). Are you sure that the font group name matches what is in the flags? Can you try if removing space from `font-family: segoeui` will make a difference?

Hey, it really seemed as there was an issue there, I fixed it but the result is still the same.
Updated print screens*





> @RoeelCohen Also, you should get your Segoe fonts from Microsoft directly (https://aka.ms/segoeuifont), not a random third-party site.
I tried to download from so many places and also tried to convert to different font types nothing really did the trick
