### ISSUE TITLE
input field "Content" doesn't specify which content is required 

### ISSUE THREAD

**Issue by bokor-rami-io** [WeblateOrg/weblate#6505]
When trying to register an Account at an self-hosted weblate installation, there is an input labeled "Content". The field is required and there is no documentation what this content is supposed to be. Please advise. 

The same field is also in the contact-form. 
![Bildschirmfoto 2021-09-02 um 13 24 16](https://user-images.githubusercontent.com/87018995/131836856-fdb3ec91-876c-4029-8ad3-d29be347cec8.png)

**Comment by nijel** [comment]
Upgrade, this was fixed in ed37cbcbf9d89330c0dfc13e83a43ad2c957c15c.
