### ISSUE TITLE
Allow personal email addresses to be ommitted in commits

### ISSUE THREAD

**Issue by pappasadrian** [WeblateOrg/weblate#6508]
**Is your feature request related to a problem? If so, please describe.**

Email addresses used by translators are included in the commit files, with no option to opt out/turn off. This leads to leaks of personal information publically, by including addresses in public code. This is not respectful towards translators who contribute, and potentially illegal in some jurisdictions (Especially considering that there's no specific consent given. Everyone is opted-in by default, with no option to opt out). 

**Describe the solution you'd like**

Add an option allowing translators's email to not be included in commits.

**Describe alternatives you've considered**
Using a fake email is not an option, as a valid email is required for other features of weblate. 
Using an throwaway/single use email is also not very viable, as it is very cumbersome for users, and not a clear option for people who don't want their personal information leaked. 

**Screenshots**

**Additional context**
 
Relevant issue: https://github.com/WeblateOrg/weblate/issues/4988

**Comment by bjorn3** [comment]
Github gives everyone a email address like `bjorn3@users.noreply.github.com` to be used as commit author. Alternatively giving the option to use one of the secondary email addresses associated with a github account rather than the primary one would be nice. For example zulip asks you which of the email addresses associated with your github account to use. Personally I have my private email address set as primary email on my github account, but a public email address as secondary email.

**Comment by nijel** [comment]
The final solution should look like:

* ~Prefer public address from GitHub~, done in 90e101139ac8c89c7c931e0d7eb3edf1560c701a
* Fetch all verified addresses from GitHub and store them as `VerifiedEmail`
* Add separate selection for email address to use in Git commits

**Comment by phw** [comment]
@nijel Thanks for getting in. Could this also be done independent of a users GitHub profile? Not every users has one. I imagine something similar to how Github does it:

- First have a separate "Commiter e-mail" field the user can set, so the e-mail being used for commits is separate from the main communication e-mail. The user can fill in any value they want to have a different e-mail for committing. If they omit this the primary e-mail address will be used.
- Have an option "Keep my e-mail address private". Activating this will automatically use some e-mail address in the form of "username@weblate_host", let's say for example "phw@hosted.weblate.org"

This is how it looks like in Github:

![grafik](https://user-images.githubusercontent.com/29852/172811374-7257f458-3185-42af-a403-e9edf46876ef.png)

I even think this option should be active by default. It's better users have to activate their real e-mail than to have them discover later that they published their private e-mail address. E.g. Transifex also has an option to keep e-mail private, but it is disabled by default We had some discussion about this on the MusicBrainz forums, where users where badly surprised that Transifex put their e-mail addresses into public translation files.

**Comment by nijel** [comment]
There are many questions related to this:

* Should Weblate allow entering any address as committer e-mail without any verification?
* Keeping the address private on Weblate side will avoid associating commits on GitHub, that will be surprising for many users if that would be a default. On the other side, I understand that privacy wise, there might be good reasons for that.
* Keeping the address private requires some setup to avoid problems with the e-mail addresses (make sure these do not end up in some mailbox) - something we can easily do on Hosted Weblate, but on the other side, something we cannot realistically expect from thousands of other Weblate installations. So, this would have to be an opt-in feature enabled in the configuration, which is used only on few installations.

**Comment by bjorn3** [comment]
> Should Weblate allow entering any address as committer e-mail without any verification?

Probably not.

> Keeping the address private on Weblate side will avoid associating commits on GitHub, that will be surprising for many users if that would be a default. On the other side, I understand that privacy wise, there might be good reasons for that.

An option would be to use the github user specific noreply email as author for the commit and an email address forwarding to the author in the commit message (if you want to introduce any forwarding in the first place).

For me specifically allowing me to pick any of the already email addresses verified by github would be fine.

**Comment by phw** [comment]
@nijel Those are good points. So give the user the ability to specify a separate commit e-mail from their verified e-mail addresses + importing the verified e-mails from github as verified is probably a good first start.

Having the ability to configure a weblate instance to provide custom e-mails (maybe on a specified subdomain) would be a great addition I think, but it really complicates things. E.g. ideally the user would still be able to add this fake e-mail to their github account.

Maybe an easier approach would be to allow anonymous commits, where the commits then get associated with a default user + e-mail provided by the weblate instance (e.g. most setups could use the Github account they use for pushing).

This should be clearly an opt-in from the user, with the note that commits will then not be associated with their own Github user account. Also this option should only be available to users if the instance is configured accordingly. Would this work?

**Comment by ann0see** [comment]
On hosted Weblate probably https://github.com/WeblateOrg/weblate/commit/90e101139ac8c89c7c931e0d7eb3edf1560c701a is already included, I assume. Even if the relevant checkboxes are set on GitHub, it doesn't change anything on Weblate, the E-Mail is still exposed.

![grafik](https://user-images.githubusercontent.com/20726856/186021217-5d26af95-14da-4da8-bcb5-07da2be8f306.png)
I assume it's not possible to get these values from GitHub?

**Comment by nijel** [comment]
That commit just makes Weblate prefer the public e-mail address if you have it configured on GitHub.

**Comment by bjorn3** [comment]
How do you set an e-mail address as public? I can't find any ui for it. The only option I see it to keep everything private or everything public.

**Comment by nijel** [comment]
When editing profile:

![obrazek](https://user-images.githubusercontent.com/212189/186112588-e855b82a-fc3f-4002-adf1-d0ed331bd5d1.png)

**Comment by bjorn3** [comment]
I see, thanks! Unfortunately it isn't compatible with the option to prevent accidentally leaking any other email addresses. Maybe temporarily unchecking that option while creating a weblate account would work?

**Comment by nijel** [comment]
Weblate picks up public or primary mail. You can add and verify any e-mail and use that.

Also, I've improved the GitHub integration in b0cbaa31e0 to fetch all verified e-mails, so that you can choose them without need for additional verification.

**Comment by ann0see** [comment]
Does this allow to set the noreply E-Mail from GitHub now?

I think what's wanted here is to be able to have an invalid E-Mail in the translation files while still being able to receive Mails from Weblate.

**Comment by nijel** [comment]
No, Weblate needs a working e-mail and doesn't allow different e-mail for commit and notifications. That's why this issue is still open. The desired solution has been outlined in https://github.com/WeblateOrg/weblate/issues/6508#issuecomment-1150862268, patches to implement that are welcome.

**Comment by ann0see** [comment]
I don't know Python or the code base well enough, but do you have any pointers on how I could help out?

**Comment by nijel** [comment]
In more detail, what is missing:

* The [VerifiedEmail](https://github.com/WeblateOrg/weblate/blob/072befc09cb5d66cb794343e940e50d6c9636a23/weblate/accounts/models.py#L347-L362) model needs to track information whether e-mail is suitable for e-mail delivery
* Extend [get_all_user_emails](https://github.com/WeblateOrg/weblate/blob/072befc09cb5d66cb794343e940e50d6c9636a23/weblate/accounts/utils.py#L90-L99) to support filtering based on that, defaulting to deliverable e-mails
* Add `commit_email` field to `Profile` and make it configurable in the settings (utilizing `get_all_user_emails`) to get valid selection, this time without the filter for deliverable e-mails
* Adjust [get_github_emails](https://github.com/WeblateOrg/weblate/blob/072befc09cb5d66cb794343e940e50d6c9636a23/weblate/accounts/pipeline.py#L59-L87) to not filter noreply e-mail, but flag it accordingly for storing as `VerifiedEmail`

**Comment by ann0see** [comment]
Thanks. I'll try to look into the code base, but no guarantees ;-)

> The [VerifiedEmail](https://github.com/WeblateOrg/weblate/blob/072befc09cb5d66cb794343e940e50d6c9636a23/weblate/accounts/models.py#L347-L362) model needs to track information whether e-mail is suitable for e-mail delivery

That should be easy with just some field "is_deliverable" added to the place where E-Mails are stored (DB?)

> Extend [get_all_user_emails](https://github.com/WeblateOrg/weblate/blob/072befc09cb5d66cb794343e940e50d6c9636a23/weblate/accounts/utils.py#L90-L99) to support filtering based on that, defaulting to deliverable e-mails

I think we need to look where the method is called and change the behavior based on a parameter


> Add commit_email field to Profile and make it configurable in the settings (utilizing get_all_user_emails) to get valid selection, this time without the filter for deliverable e-mails

I think that's the interesting part. Would we want to add a generic noreply@weblate.org E-Mail here for people not using GitHub but wanting privacy, or would we just disable committing an E-Mail at all (which I doubt is even possible on the git side).

**Comment by ann0see** [comment]
After some thinking, wouldn't the cleanest way be to add another field in the user database containing the commit E-Mail? To me the code I read seems like it was targeted to one E-Mail only - and we need to save a possible commit E-Mail somewhere...

**Comment by nijel** [comment]
> I think that's the interesting part. Would we want to add a generic [noreply@weblate.org](mailto:noreply@weblate.org) E-Mail here for people not using GitHub but wanting privacy, or would we just disable committing an E-Mail at all (which I doubt is even possible on the git side).

There will be currently no option for such users. We definitely do not want to commit all changes without any authorship. And providing such e-mail for every user needs some setup (see https://github.com/WeblateOrg/weblate/issues/6508#issuecomment-1152052663). So let's focus on selecting commit e-mail from those we already have for now.

> After some thinking, wouldn't the cleanest way be to add another field in the user database containing the commit E-Mail? To me the code I read seems like it was targeted to one E-Mail only - and we need to save a possible commit E-Mail somewhere...

The committer e-mail is typically `noreply@weblate.org` (it is configured by https://docs.weblate.org/en/latest/admin/config.html#default-commiter-email), what we want to configure here is author e-mail. That is retrieved here (note that this is currently also used in sending e-mail, so again, this will need to handle correct scope):

https://github.com/WeblateOrg/weblate/blob/1d21471423fe6976ea7f145efc6300452e1f7762/weblate/auth/models.py#L640-L642

**Comment by ann0see** [comment]
Ok thanks. So we'd incorporate a separate "no-reply" committer E-Mail only for GitHub users for now?

**Comment by ann0see** [comment]
Ok. I've now looked at the database, and it seems as if we do in fact only save one E-Mail. So we'd need to add a field to weblate_auth_user named e.g. commit_email. Then we'd set it via GUI (with verification if needed) and use this one for all git/svn operations?

**Comment by ann0see** [comment]
I don't seem to understand how the logic in the social login.

That's what I tried: https://github.com/WeblateOrg/weblate/commit/69a6e9630457d7e8d01076cd84187e02c2cda4fb until now. 

What does VerifiedEmail do? get_all_user_email doesn't seem to use it as I expected:

I'd expect to have some array of E-Mails or VerifiedEmail objects which I can extend with a new field and modify. However, this doesn't seem to be the case: What does
```
        emails = set(VerifiedEmail.objects.filter(**kwargs).values_list("email", flat=True))
```

actually do? Is it a database query? However, how should we get the data from GitHub there?

**Comment by nijel** [comment]
VerifiedEmail is a database model. It's a database query using Django ORM. It fetches "email" field from the matching object and creates a set from that.

The data needs to be fetched from GitHub during authentication and stored in the database (this already happens, it just needs to be extended to cover the deliverability flag). Then n the settings all user verified e-mail are available for selection.

**Comment by ann0see** [comment]
Ok. I think i've made some progress: https://github.com/ann0see/weblate/tree/feature/hideMail

GUI still needs to be done.

**Comment by ann0see** [comment]
Ok. Now I get an error about a missing key after setting the commit E-Mail.

  File "/home/a0/weblate/weblate/accounts/models.py", line 307, in get_message
    message = ACCOUNT_ACTIVITY[activity]
KeyError: 'commit_email'

The database has the key and it is also updated.

**Comment by nijel** [comment]
The ACCOUNT_ACTIVITY defines verbose messages to notify user when attribute has changed. The audit log entries are created in `UserForm.audit`.

**Comment by nijel** [comment]
I've created https://github.com/WeblateOrg/weblate/pull/8268 so that I can easily comment on the code (and sorry for late response, I built a huge backlog on GitHub and I'm now finally processing that).

**Comment by maboroshin** [comment]
Next: https://github.com/WeblateOrg/weblate/issues/8451
