### ISSUE TITLE
what strategy to download all tmx?

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#6512]
Hello,

I would like to create tmx file with all translations in Weblate.

I'll make this for the Fedora translation platform on which I am admin, but in the future, I'll ask for permission to other admins to let me do this.

it means I would like to go through API.

what would be the recommanded approach to do so without creating an heavy load on the server?

thanks for your help!

**Comment by nijel** [comment]
There is currently no API for memory. You can either use /manage/memory/ and download JSON or TMX there or use [dump_memory](https://docs.weblate.org/en/latest/admin/management.html#dump-memory) on the commandline.
