### ISSUE TITLE
File xx.po doesn't exist error when there is no translation

### ISSUE THREAD

**Issue by Aikatsui** [WeblateOrg/weblate#6514]
**Describe the issue**

Past i added a language to several projects and forgot to start translate [freeipa]( https://translate.fedoraproject.org/projects/freeipa/) project.
They have got build error since added the language (#20210817.5 and past)
It no longer occur after added translations (from #20210818.8)

https://github.com/freeipa/freeipa/pull/5976
https://dev.azure.com/freeipa/freeipa/_build?definitionId=3&_a=summary

https://dev.azure.com/freeipa/freeipa/_build/results?buildId=9703&view=results
#20210817.5 (Jobs --> Build --> failed)
https://dev.azure.com/freeipa/freeipa/_build/results?buildId=9716&view=results
#20210818.8 (It shows build success with some errors)

I don't have relationship with fedora or FreeIPA or maintain access to the instance. member informed me about that problem and said, weblate submitting not working PRs and the log ends with: "File si.po does not exist.

**Comment by nijel** [comment]
There is `po/si.po` in the diff - https://github.com/freeipa/freeipa/pull/5976/files#diff-7dd8242da7e604ceaf7afbb3eb0379a6e9c073d11bdeb2a7686895374479bae7, so I don't see an issue on the Weblate side, but more likely something went wrong in the build...

**Comment by Aikatsui** [comment]
> I don't see an issue on the Weblate side, but more likely something went wrong in the build...

@nijel I added new language recently (no translation yet) and noticed that build fail once again. I'll let them know about this issue then if necessary; they can come to discuss 

https://github.com/freeipa/freeipa/pull/5976
https://github.com/freeipa/freeipa/pull/5976/checks?check_run_id=3573987855

Build log "File ko.po does not exist".
[https://dev.azure.com/freeipa/freeipa/_build/results?buildId=9831&view=logs&j=ca395085](https://dev.azure.com/freeipa/freeipa/_build/results?buildId=9831&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=f3c91641-114c-5821-bd1e-444cf5c75ddb&l=3991)

**Comment by nijel** [comment]
There is something broken in the build - the file is present in https://github.com/freeipa/freeipa/pull/5976/files,

Quickly looking at that it seems to remove it:

```
2021-09-11T07:44:06.6126993Z removed './ko.po'
2021-09-11T07:44:06.6131462Z 
2021-09-11T07:44:06.6132133Z Please remove the deleted files from LINGUAS!
```

That is clearly out of scope here.
