### ISSUE TITLE
Search through translated terms

### ISSUE THREAD

**Issue by jtagcat** [WeblateOrg/weblate#6516]
**Is your feature request related to a problem? If so, please describe.**

Translating multiple things, or checking-ensuring consistency across a larger project requires reference.

https://translations.telegram.org/eestikeel

Searching through all terms in both source and translation language would be desired. Ideally, across projects as well.

It's wasted time researching the same translation, that I've already translated earlier. Having translations from quality sources at my fingertips is empowering. Every so often you don't even have any ideas, you know when you see a translation, that's just right.

One can also pick (find a UI element, that has a wonky translation) and change translations quickly as well. This is great for getting new translators involved, as they see the little change themselves.

**Screenshots**

![image](https://user-images.githubusercontent.com/38327267/132119961-e1a74d3d-83df-44b7-beb0-fa53d9ebf42c.png)

![image](https://user-images.githubusercontent.com/38327267/132119971-5c8641e3-651c-42cf-8bb8-edc23cfd8265.png)

**Comment by Findus23** [comment]
Hi,

I think weblate by default searches through both source and translated texts. See this search without any filter or option as an example:

https://hosted.weblate.org/search/matomo/?offset=1&q=Kampagnen+URL+Erzeuger&sort_by=-priority%2Cposition&checksum=

**Comment by nijel** [comment]
@jtagcat That doesn't look like Weblate. You can search for translation text in Weblate, see https://docs.weblate.org/en/latest/user/search.html

**Comment by jtagcat** [comment]
> @jtagcat That doesn't look like Weblate. You can search for translation text in Weblate, see [docs.weblate.org/en/latest/user/search.html](https://docs.weblate.org/en/latest/user/search.html)

That's telegram, where the search is implemented.

**Comment by jtagcat** [comment]
> Hi,
> 
> I think weblate by default searches through both source and translated texts. See this search without any filter or option as an example:
> 
> [hosted.weblate.org/search/matomo/?offset=1&q=Kampagnen+URL+Erzeuger&sort_by=-priority%2Cposition&checksum=](https://hosted.weblate.org/search/matomo/?offset=1&q=Kampagnen+URL+Erzeuger&sort_by=-priority%2Cposition&checksum=)

Huh, didn't see the search button at all.
