### ISSUE TITLE
"Clone to Translation" Keybinding

### ISSUE THREAD

**Issue by aptMattKoe** [WeblateOrg/weblate#6518]
I have a single language file and have also one english to english xfl. file. In this case its often that the source is the translation.

Now I have to click on the "Clone to translation"-Button.  For every translation. It would be faster if there is an Keybinding for this :)

There could also be an setting that this is the default value for the translation?

**Comment by nijel** [comment]
Ctrl+O should already do that, see https://docs.weblate.org/en/latest/user/translating.html#keyboard-shortcuts

**Comment by aptMattKoe** [comment]
Oh sorry, I realy thought this is currently not an feature!
