### ISSUE TITLE
Maintain Syntax in Messages when using deepl machine Translation by using XML handling

### ISSUE THREAD

**Issue by benks-io** [WeblateOrg/weblate#6529]
**Is your feature request related to a problem? If so, please describe.**

Inline syntax within a message will sometimes be broken after machine translation with deepl as e.g. when translating to german ` will be replaced by " in most of the cases. 

Example:
The documentation software Sphinx uses the inline syntax for Links

```
This is a sentence with a `link <https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html?highlight=link#external-links>`_ in Sphinx restructured text syntax.
```
This would be one message in weblate.

**Describe the solution you'd like**

Deepl offers XML handling flags to not translate text in predefined tags.

```
"tag_handling=xml"
"ignore_tags=x"

```
When using the deepl API with weblate it would be helpful to have the opportunity to define some special chars and strings that will be escaped with xml-Tags that will be removed from the result afterwards.

e.g.

```
This is a sentence with a <x>`</x>link <x><</x>https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html?highlight=link#external-links<x>>`_</x> in Sphinx restructured text syntax.
```

**Describe alternatives you've considered**

One approach could be to split the messages up further before sending them to deepl API, but deepl cannot maintain the grammar when sentences are chopped up too far.

**Comment by benks-io** [comment]
Alternative solutions or ideas are very welcome.

**Comment by nijel** [comment]
We're doing generic cleanup before sending the text to machine translation services, see 
https://github.com/WeblateOrg/weblate/blob/cd5d360de52b8963d3bb1bbcc17999ed046b1f09/weblate/machinery/base.py#L235-L254

It could be overridden for DeepL to use the XML specific feature instead.

**Comment by nijel** [comment]
This issue has really two parts:

Switch to using XML syntax for DeepL to escape placeholders (instead of the logic referenced above). This is pretty straightforward to implement.

Add way to define additional strings to escape. This will be definitely more tricky, as manually defining strings/characters to escape will break in many corner cases.

The best approach in this particular case would be to learn Weblate to understand the RST syntax and do this escaping automatically. There already is `rst-text` flag which could toggle this (see https://docs.weblate.org/en/latest/admin/checks.html#customizing-behavior-using-flags).

Also, I think that the URL should be inside the XML markup - this is not something DeepL could translate and having the URL inside the sentence will confuse it.

**Comment by benks-io** [comment]
As an alternative to the complex task of defining RST Syntax and to prevent corner cases, Regular Expressions could be used instead of trivial string/char replacement. With that also URLs could easily be grabbed to be put into xml-tags.
This would also be a handy mechanic for Project Managers to define "none Syntax" Strings or Terms on a semantic Level, to be marked as fix independently from any syntax used in the background.

**Comment by nijel** [comment]
Thinking about this, there are two topics:

1. Use XML syntax with DeepL to mark placeables, that requires changing text processing for DeepL
2. Introduce additional filter for text processing to handle syntax of the strings, for example RST

**Comment by benks-io** [comment]
@nijel thank you!

Ist this feature enabled for rst and deepl by default, or is there something to be configured or escaped?

After updating to 4.10.1 still URL Syntax of rst from sphinx is changed by deepl:
For example in some cases:
``
`My Link Text <https://foo.bar>`_
``
will be translated to german by
``
Mein Linktext <https://foo.bar>`_
``
without the leading Grave accent.

This also happens when there is a leading string before the accent in some cases.

**Comment by nijel** [comment]
You need `rst-text` flag to enable rst processing.

**Comment by benks-io** [comment]
Thanks – that did the trick.

For the record: I added "rst-text" in /settings/MYPROJECT/MYCOMPONENT/#translation for all components as described in https://docs.weblate.org/en/latest/devel/sphinx.html?highlight=%22rst-text%22#id1

**Comment by benks-io** [comment]
@nijel 
With the fix in some cases for some languages there are misplaced or missing spaces within the Syntax for **bold** and for Links.

I've spotted it for Japanese, Spanish and French.

You can see examples of the original Message, the translation and the manual fix here:
https://github.com/Nitrokey/nitrokey-documentation/commit/3fe54fd0d820ff20c60a4a4a69041a748b19c062
https://github.com/Nitrokey/nitrokey-documentation/commit/3d6ab3c83c4d6300c8187fe8e0304031c7ba7681
https://github.com/Nitrokey/nitrokey-documentation/commit/717a60433e8a5395daa3fe20dac07a0086d559ff
https://github.com/Nitrokey/nitrokey-documentation/commit/c6594b0b008f8b49ec700685ecd38d39bee3ed47

**Comment by nijel** [comment]
This is coming from DeepL, I currently don't see a way to hint it to some behavior....

**Comment by benks-io** [comment]
After getting in touch with deepl, they'd like to have the cURL request to get into it. @nijel Is there a way to obtain or log the requests weblate performs?

**Comment by nijel** [comment]
All rst syntax is replaced by blank `<x>` XML elements, so for example https://github.com/Nitrokey/nitrokey-documentation/commit/c6594b0b008f8b49ec700685ecd38d39bee3ed47 becomes: `Open one of the <x id="16"></x>websites that support FIDO U2F <x id="48"></x><x id="77"></x>.`

It is then passed with `tag_handling=xml&ignore_tags=x`.

**Comment by nijel** [comment]
Unfortunately that one was not handled, I've just added it in b90425b44b33f431aeeb2a313bd92e6aa510723
