### ISSUE TITLE
Incorrect component name in commit log (msgmerge addon)

### ISSUE THREAD

**Issue by SlavekB** [WeblateOrg/weblate#6531]
**Describe the issue**

Commit log generated after updating PO files with msgmerge addon for the linked component uses the project and name of the master component. This makes commit log confusing. See example [TDE/tde-i18@dadedeb8](https://mirror.git.trinitydesktop.org/cgit/tde-i18n/commit/?id=dadedeb8) – instead of `tdenetwork/kopete` is used `TDE/tde-i18n`.

**I already tried**

- [x] I checked that the component uses a standard commit log template with
```
Translation: {{Project_Name}} / {{Component_Name}}
Translate-URL: {{ url }}
```
- [x] I verified that before the Weblate 4.7.x commit log was ok – see example [TDE/tde-i18n@5057a7e5](https://mirror.git.trinitydesktop.org/cgit/tde-i18n/commit/?id=5057a7e5).

**To Reproduce the issue**

1. Have a linked components.
2. Use the msgmerge addon.
3. Make a POT file update for some component. 
4. See wrong message in commit log.

**Expected behavior**

The expected behavior is to use information from the linked component, as it was before Weblate 4.7.x.

**Server configuration and status**

Weblate installation: PyPI

```
 * Weblate: 4.8
 * Django: 3.2.4
 * siphashc: 1.3
 * translate-toolkit: 3.4.0
 * lxml: 4.6.3
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 4.1.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.9.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 46.1.3
 * jellyfish: 0.7.2
 * openpyxl: 3.0.3
 * celery: 5.1.1
 * kombu: 5.1.0
 * translation-finder: 2.7
 * weblate-language-data: 2021.5
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.36.1
 * diff-match-patch: 20200713
 * requests: 2.23.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.3
 * Cython: 0.29.17
 * misaka: 2.1.1
 * GitPython: 3.1.2
 * borgbackup: 1.1.11
 * pyparsing: 2.4.7
 * pyahocorasick: 1.4.1
 * python-redis-lock: 3.7.0
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * boto3: 1.14.7
 * aeidon: 1.7.0
 * iniparse: 0.5
 * Mercurial: 4.8.2
 * git-svn: 2.20.1
 * git-review: 1.27.0
 * Redis server: 5.0.3
 * PostgreSQL server: 11.12
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django_sendmail_backend.backends.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 3.16.6-042stab141.42 (x86_64)
```

**Weblate deploy checks**

```
System check identified no issues (3 silenced).
```

**Comment by nijel** [comment]
Caused by dbcf4bd125f.
