### ISSUE TITLE
Some log messages are redundantly displaying twice

### ISSUE THREAD

**Issue by fitojb** [WeblateOrg/weblate#6534]
![Captura de pantalla de 2021-09-09 04-15-40](https://user-images.githubusercontent.com/554953/132658663-78ec92f3-47c5-4b3a-9947-f68e787f07e5.png)

In the above screenshot, the gray label contains the exact same message as the label in the blue background. In these cases, the gray label shouldn’t be displayed.

**Comment by nijel** [comment]
The gray label is name of the event for all actions, so it's good to keep it to have consistency in this. The message provides more details, but we don't have more detailed information for some of the events.

**Comment by fitojb** [comment]
I think consistent display is pointless when you don’t have a consistent set of details to display for all events. The duplication just makes the pages of the log bigger vertically, and you have to scroll more for less information on screen.

**Comment by fitojb** [comment]
Do you have any idea then on how to solve the issue of wasted vertical space?
