### ISSUE TITLE
Keys's translations are no more deleted when Key is deleted from Weblate

### ISSUE THREAD

**Issue by borisBelloc** [WeblateOrg/weblate#6536]
Hello,

**Describe the issue**

We use Weblate to manage X languages.

```
Key : English
Key : French
Key : Spain
```

Since 1-2 months, when we delete a key with it's english translation, the other translations linked to this key are not deleted.

It worked fine before.
I have no idea why it stoped working, is it a new setting ? does a user changed something somewhere ?

In this screenshot, Red cross will be deleted but not the yellow translations linked to the same key "Absence Type".
![image](https://user-images.githubusercontent.com/37147299/132684240-0ff5f729-6dcd-4ff7-9ee5-f05778733ada.png)

When I download the files from weblate, the key is removed from EN.JSON but not from other languages : FR.JSON, ES.JSON...

It mean, in our file we know have orphan translations.

Example : 
In my EN.JSON, the key/translation `weekly sentence is updated` isn't here but in FR.JSON, the key is still here : 
![image](https://user-images.githubusercontent.com/37147299/132685316-7293e34c-a872-4495-8796-1cc90eccc54c.png)

I don't find how to fix it.

Any idea ?
thank you

**To Reproduce the issue**
1. Open English translation
2. Delete key

**Expected behavior**

Delete every translations linked to that key like it did before...

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/devel/integration.html#updating-target-files

**Comment by borisBelloc** [comment]
thanks for the fast answer, I will check it.

is it a new thing ? it worked fine before and I don't think someone removed an addon from _our_ weblate

**Comment by borisBelloc** [comment]
hello,

After installing the addon :
- I remove a key from EN (base lang file)
- 24 hours later, the key is successfully deleted from other language files.

This point seem to works correctly but now there is another big problem :

>Update all translation files to match the monolingual base file.
> For most file formats, **this means removing stale translation keys no longer present in the base file**.

Now we have a lot of missing translation on our files; thoses translations were on the `en.json` (base file) file so they shouldn't have been deleted (file had 1088 lines and now got only 969).

Any way to find why it happened ?

**Comment by nijel** [comment]
Looking into Git repository history will tell what did delete them.
