### ISSUE TITLE
Docs: feature supported by Celery?

### ISSUE THREAD

**Issue by BenderV** [WeblateOrg/weblate#6540]
**Describe the issue**
For deployment reason, I prefer not to add Celery to begin with.

However, I haven't found what I am missing without Celery. In the [FAQ](https://docs.weblate.org/en/latest/admin/install.html#background-tasks-using-celery), it just state "background task" but it's unclear to me what they are.

Would it be possible to add a paragraph to explain what Celery is taking care of, feature wise ?

Thanks

**Comment by nijel** [comment]
TLDR: Don't do that.

For long answer, I will update the docs.
