### ISSUE TITLE
Can't add new translation component

### ISSUE THREAD

**Issue by Tefel** [WeblateOrg/weblate#6543]
I installed my own Weblate following the guide: https://docs.weblate.org/en/latest/admin/install/venv-debian.html
I was able to create an account and the project. There is a **Server Error** when trying to add new component:

**Screenshot**
![image](https://user-images.githubusercontent.com/1677244/132988606-9cff550e-0188-4066-ada1-4928a22e3230.png)

**Plese check my running Weblate here (if you need credentials let me know)**
https://astrocolony1.vps.webdock.io/create/component/

There are some **warnings** when starting the server:
> ?: (weblate.W025.ass) Failure in loading handler for ass file format: aeidon or gaupol package required for Subtitle support
>         HINT: https://docs.weblate.org/en/weblate-4.8/admin/install.html#optional-deps
> ?: (weblate.W025.fluent) Failure in loading handler for fluent file format: No module named 'fluent'
>         HINT: https://docs.weblate.org/en/weblate-4.8/admin/install.html#optional-deps
> ?: (weblate.W025.ini) Failure in loading handler for ini file format: Missing iniparse library.
>         HINT: https://docs.weblate.org/en/weblate-4.8/admin/install.html#optional-deps
> ?: (weblate.W025.islu) Failure in loading handler for islu file format: Missing iniparse library.
>         HINT: https://docs.weblate.org/en/weblate-4.8/admin/install.html#optional-deps
> ?: (weblate.W025.laravel) Failure in loading handler for laravel file format: No module named 'phply'
>         HINT: https://docs.weblate.org/en/weblate-4.8/admin/install.html#optional-deps
> ?: (weblate.W025.php) Failure in loading handler for php file format: No module named 'phply'
>         HINT: https://docs.weblate.org/en/weblate-4.8/admin/install.html#optional-deps
> ?: (weblate.W025.srt) Failure in loading handler for srt file format: aeidon or gaupol package required for Subtitle support
>         HINT: https://docs.weblate.org/en/weblate-4.8/admin/install.html#optional-deps
> ?: (weblate.W025.ssa) Failure in loading handler for ssa file format: aeidon or gaupol package required for Subtitle support
>         HINT: https://docs.weblate.org/en/weblate-4.8/admin/install.html#optional-deps
> ?: (weblate.W025.sub) Failure in loading handler for sub file format: aeidon or gaupol package required for Subtitle support
>         HINT: https://docs.weblate.org/en/weblate-4.8/admin/install.html#optional-deps
> ?: (weblate.W033.Gerrit) Failure in loading VCS module for Gerrit: git: 'review' is not a git command. See 'git --help'.
>  (1)
>         HINT: https://docs.weblate.org/en/weblate-4.8/vcs.html
> ?: (weblate.W033.Mercurial) Failure in loading VCS module for Mercurial: [Errno 2] No such file or directory: 'hg'
>         HINT: https://docs.weblate.org/en/weblate-4.8/vcs.html
> ?: (weblate.W033.Subversion) Failure in loading VCS module for Subversion: git: 'svn' is not a git command. See 'git --help'.
> 
> The most similar commands are
>         fsck
>         mv
>         show
>  (1)
>         HINT: https://docs.weblate.org/en/weblate-4.8/vcs.html
> 
> System check identified 12 issues (1 silenced).
> September 12, 2021 - 08:10:04 AM
> Django version 3.2.7, using settings 'weblate.settings'
> Starting development server at http://127.0.0.1:8080/
> Quit the server with CONTROL-C.

**About my configuration**
Weblate 4.8 Django 3.2.7 siphashc 2.1 translate-toolkit 3.4.0 lxml 4.6.3 Pillow 8.3.2 bleach 4.1.0 python-dateutil 2.8.2 social-auth-core 4.1.0 social-auth-app-django 5.0.0 django-crispy-forms 1.12.0 oauthlib 3.1.1 django-compressor 2.4.1 djangorestframework 3.12.4 django-filter 2.4.0 django-appconf 1.0.4 user-agents 2.2.0 filelock 3.0.12 setuptools 44.0.0 jellyfish 0.8.2 openpyxl 3.0.7 celery 5.1.2 kombu 5.1.0 translation-finder 2.10 weblate-language-data 2021.5 html2text 2020.1.16 pycairo 1.20.1 pygobject 3.40.1 diff-match-patch 20200713 requests 2.26.0 django-redis 5.0.0 hiredis 2.0.0 sentry_sdk 1.3.1 Cython 0.29.24 misaka 2.1.1 GitPython 3.1.18 borgbackup 1.1.17 pyparsing 2.4.7 pyahocorasick 1.4.2 python-redis-lock 3.7.0 Python 3.8.10 Git 2.25.1 psycopg2-binary 2.9.1 ruamel.yaml 0.17.16 mysqlclient 2.0.3 Redis server 5.0.7 MariaDB sever 5.5.5

I have no idea if warnings are related to the issue. I am using Mysql database, maybe encoding utf-8 plays role here?
What about language? Is it a server fault? I am using webdock VPS server. Please help!

**Comment by Tefel** [comment]
What could be the reason why creating components is not possible? It allows me to navigate to every tab and create new project. Using admin to grant access etc. Seems the website, certificates, Mysql database are working.

Is there anything more in addition to the guide: https://docs.weblate.org/en/latest/admin/install/venv-debian.html
which has to be done, before using the service?

**Comment by Tefel** [comment]
Is there anything I can do to track the problem? Is it a server, configuration or Weblate issue? I would like to take a consulting hour, obviously, if this can be resolved! Thanks in advance!

**Comment by nijel** [comment]
> Is there anything I can do to track the problem?

The best thing you can do is to avoid spamming it to more locations. This is being discussed at https://github.com/WeblateOrg/weblate/discussions/6559.
