### ISSUE TITLE
Permission to block certain users (translators) from downloading the source files

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#6547]
We are encountering the issue that some customers of ours do not want to switch to Weblate, since the translators have the ability to download the source files. In some cases confidentiality requires for this to not be possible.

Can a permission "Download Source" be added and only made available to translators for specific projects (default to OFF).

**Comment by nijel** [comment]
There already is a permission for VCS access
 Is that what you want?

**Comment by ilocit** [comment]
No, that is not it. The translators usually never have VCS permission. The thing is that they can download the source files by default. Maybe it would be tolerable to have them download "converted" files like TMX, TBX, XLIFF or such. But not the original source files.
This is not compliant with confidentiality in many of our cases. Let's say, they translate a legal document which is ODT as a source. Translators should not be able to download the ODT file (source file). 
Since such a distinction is more complex to implement, it would be the "easier" fix, perhaps, to have a switch/permission which would disable download for a translator altogether.
That way the only option would be to translate "online". Which should be the preferred option anyhow, so that the progress can be monitored in real-time.
