### ISSUE TITLE
Field last_change date is not updated in some cases

### ISSUE THREAD

**Issue by ZloyChert** [WeblateOrg/weblate#6548]
Field **last_changed** is not updated in following cases with **repro steps**:

_1st case:_
Somebody makes any changes to translations in git and pulls/rebase them in component (or any of maintenance functions), **last_changed** field is not updated. 

_2nd case:_
Somebody createы new component from file in git - **last_changed** is null. After that, somebody adds new translaiton in that component from weblate UI - **last_changed** is still null. 
Please, see attached screenshot for that case (you can see, that **total** field changed, but **last_changed** didn't)
![image](https://user-images.githubusercontent.com/17516013/133085977-6b9c6e1f-49fe-4a5a-ba9d-12fde7af2c7c.png)

I'm using this endpoint: https://docs.weblate.org/en/latest/api.html#get--api-translations-(string-project)-(string-component)-(string-language)-statistics-

**Expected behavior**
**last_changed** property is updated with every change. 
Also, since there is no property created_date, last_changed can be set after creating. 

Weblate version is 4.7.1

**Comment by nijel** [comment]
That field currently indicates last change within Weblate, it does not reflect outside changes.

**Comment by ZloyChert** [comment]
Seems, like there is no reason to expose that field, since it is meaningless for api user and reflects unknown internal processes

**Comment by nijel** [comment]
It indicates when the translation was changed in Weblate. It's not meaningless for everybody if you don't have use for this information.

**Comment by nijel** [comment]
Field is updated exactly as intended - both `last_change` and `last_author` indicate last edit in Weblate. It behaves this way since ever.

See https://github.com/WeblateOrg/weblate/issues/5726 for related issue.
