### ISSUE TITLE
The "commit" button has disappeared

### ISSUE THREAD

**Issue by scaralfred** [WeblateOrg/weblate#6556]
From the tab "Manage", if you check all the items of the dropdown menu, you should get something like this:
1. Repository Maintenance
2. Commit <============== This is missing...
3. Screenshots
4. Translation memory
5. Post announcement
6. Users
Etc....

The number 2 has been missing since a month from my dashboard. How can I reenable it and make it show up there?

Thanks in advance for your help
<img width="1201" alt="Screen Shot 2021-09-15 at 10 44 57" src="https://user-images.githubusercontent.com/25985418/133401457-86661665-a740-40aa-aef8-bb8e2f0abda1.png">

**Comment by nijel** [comment]
Yes, it was removed from the menu - it was the single item in the menu which did directly trigger an action and that turned out to be problematic.
