### ISSUE TITLE
Do not use single quote in the xml `<?xml version="1.0" encoding="UTF-8"?>` header for xliff files

### ISSUE THREAD

**Issue by VincentLanglet** [WeblateOrg/weblate#6563]
The weblate hook is trying to make PR on our project in order to change
```
<?xml version="1.0" encoding="UTF-8"?>
```
to 
```
<?xml version='1.0' encoding='UTF-8'?>
```

This is failing our CI because we're running `xmllint` on every xliff files.

Fact are
- Everywhere else in the file double quote are used
- Linter like http://xmlsoft.org/xmllint.html is requiring double quote
- I never saw the usage of simple quote before in xml files

Would it be possible to change this in the xml generated by weblate in order to use double quote ?

**Comment by nijel** [comment]
This is caused by lxml, see https://github.com/lxml/lxml/pull/277.

For many formats, this is handled in the translate-toolkit (https://github.com/translate/translate/blob/f2e856c15c85f30b6f9897f1f964874511ba4495/translate/storage/lisa.py#L329-L330), so the change should be done there for xliff as well.

**Comment by VincentLanglet** [comment]
> For many formats, this is handled in the translate-toolkit (https://github.com/translate/translate/blob/f2e856c15c85f30b6f9897f1f964874511ba4495/translate/storage/lisa.py#L329-L330), so the change should be done there for xliff as well.

I'm not familiar with this library at all, do you know where/how the change should be made for xliff ?

**Comment by nijel** [comment]
It just needs `XMLdoublequotes = True` in the class declaration. The question is whether it's a good idea to change the behavior this way.

In case it is, it might be better to make this a default at https://github.com/translate/translate/blob/3db0b06582d78fc4b954fc3dc6dbf70da9608696/translate/storage/lisa.py#L264 and optionally override this on other classes.

**Comment by VincentLanglet** [comment]
> The question is whether it's a good idea to change the behavior this way.

Sure. I understand this point.
According to https://github.com/lxml/lxml/pull/277#issue-380757341, I'm not the only one with this issue. And there is a good list of link in favor of `"` over `'`. `lxml` refused to make the change to avoid the BC-break. It might be acceptable for Weblate since the platform might not have a BC-promise about the format of the xliff format.

I'd like to avoid to stop using a linter because I'm using Weblate ; and didn't find one accepting `'` for the first line. I already find a way to configure the indent used, but found nothing for the quote. It can also be considered as weird the fact that the first line is the only one with single quote.

Another solution would be to add an option on the weblate website for the format, but I don't think it worth the pain.

> In case it is, it might be better to make this a default at https://github.com/translate/translate/blob/3db0b06582d78fc4b954fc3dc6dbf70da9608696/translate/storage/lisa.py#L264 and optionally override this on other classes.

I'll open a PR then.

**Comment by nijel** [comment]
Let's deal with this in https://github.com/translate/translate/pull/4440.
