### ISSUE TITLE
DeepL formality does not work as expected

### ISSUE THREAD

**Issue by matzeeable** [WeblateOrg/weblate#6566]
**Describe the issue**

I have created a language "German (informal)" within my component, but the automatic DeepL suggestions still uses formal sentences.

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
- [x] Searched for issues within GitHub repository and did not find a similar ticket

**To Reproduce the issue**

1. Create an English string `Are you sure?`
2. Go to "German (informal)" language
3. Open the automatic translation and DeepL still suggests `Sind Sie sicher?` instead of `Bist du sicher?`

**Expected behavior**

DeepL's suggestion should be `Bist du sicher?`.

I also checked out the API of DeepL, and they provide a field for `formality`: https://www.deepl.com/docs-api/translating-text/response/

> Sets whether the translated text should lean towards formal or informal language. This feature currently only works for target languages "DE" (German), "FR" (French), "IT" (Italian), "ES" (Spanish), "NL" (Dutch), "PL" (Polish), "PT-PT", "PT-BR" (Portuguese) and "RU" (Russian).Possible options are:
> - "default" (default)
> - "more" - for a more formal language
> - "less" - for a more informal language

![image](https://user-images.githubusercontent.com/1008534/133989121-f03fa0f6-6ad6-40c0-b953-f4027745ea84.png)

**Server configuration and status**

Docker, Weblate version 4.8.

```
 * Weblate: 4.8
 * Django: 3.2.6
 * siphashc: 2.1
 * translate-toolkit: 3.4.0
 * lxml: 4.6.3
 * Pillow: 8.3.1
 * bleach: 4.0.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.1.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.12.0
 * oauthlib: 3.1.1
 * django-compressor: 2.4.1
 * djangorestframework: 3.12.4
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.7
 * celery: 5.1.2
 * kombu: 5.1.0
 * translation-finder: 2.10
 * weblate-language-data: 2021.5
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.26.0
 * django-redis: 5.0.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.3.1
 * Cython: 0.29.24
 * misaka: 2.1.1
 * GitPython: 3.1.18
 * borgbackup: 1.1.17
 * pyparsing: 2.4.7
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.9.1
 * psycopg2-binary: 2.9.1
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.17.11
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.18.26
 * zeep: 4.1.0
 * aeidon: 1.9
 * iniparse: 0.5
 * mysqlclient: 2.0.3
 * Mercurial: 5.9
 * git-svn: 2.20.1
 * git-review: 2.1.0
 * Redis server: 6.2.5
 * PostgreSQL server: 13.3
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.mailersend.net
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://:WjUonTNhHsgHzp8iM66ofyALIz3u@weblate_redis:6379/1, redis://:WjUonTNhHsgHzp8iM66ofyALIz3u@weblate_redis:6379/1, regular
 * Platform: Linux 5.10.28-scaleway (x86_64)
```

**Weblate deploy checks**

```
System check identified some issues:

WARNINGS:
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.8/admin/install.html#collecting-errors
?: (weblate.I031) New Weblate version is available, please upgrade to 4.8.1.
        HINT: https://docs.weblate.org/en/weblate-4.8/admin/upgrade.html

System check identified 3 issues (1 silenced).
```

**Additional context**

Nothing.

**Comment by nijel** [comment]
The formality feature of DeepL is currently not utilized by Weblate, so both languages map to default German.
