### ISSUE TITLE
Add option to mark a path as read-only

### ISSUE THREAD

**Issue by ashutoshgngwr** [WeblateOrg/weblate#6594]
**Is your feature request related to a problem? If so, please describe.**

In my project's Fastlane Android metadata, I want to keep all changelogs as read-only. Fastlane Metadata is split across files and all changelogs are stored at the path `fastlane/metadata/android/<locale>/changelogs`. Now whenever a new changelog is added, I have to manually mark it as read-only. I searched the docs, but I didn't find anything to achieve this.

**Describe the solution you'd like**

An option to mark all changelogs (a path or a key pattern in general) as read-only.

**Describe alternatives you've considered**

**Screenshots**

**Additional context**

**Comment by nijel** [comment]
This is documented as example in https://docs.weblate.org/en/latest/admin/addons.html#addon-weblate-flags-bulk (and linked from https://docs.weblate.org/en/latest/formats.html#app-store-metadata-files).

**Comment by ashutoshgngwr** [comment]
@nijel As I understood it, I still have to manually flag each new changelog entry. Is there a way to automate it so that the any future additions will automatically be flagged as read-only?

**Comment by nijel** [comment]
The bulk edit add-on does it automatically based on the configuration.

**Comment by ashutoshgngwr** [comment]
@nijel Right, sorry! I mistook the add-on to be the same as the "bulk edit" feature. Thank you!
