### ISSUE TITLE
The one nav bar

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#6603]
Edit: Currently https://hosted.weblate.org/projects/ is very close to the look of one navigation bar.

In light of #5896 I thought about similarly meeting demands of mobile users and power users alike at the basic "Weblate-like" experience.

So no power-only ways, and no dumb extra functionality. Just what works and that's it.

**The idea is to have just the top row of buttons do everything, instead of the focus shifting between between different views and partly duplicated functionality/naming of the lower set of controls.**

Currently there is

Instance logo | Overview | Projects | Language | Controls
up top

1 Right off the bat I think clicking "Instance logo" and "Overview" does the exact same thing (?), but moreover I don't see why it shouldn't…
If clicking the "user's name" under profile now goes to ones profile, this seems like it could be combined too.
Solution: Remove "Overview" from top navigation.

2. "Projects" and "Languages" are also listed in the secondary menu.
If the user clicks into
"Project/Component/Selected Language, there is no quick way to undo just "component" and be left with
"Project/Selected Language", which is what I want to do almost every time.
I don't really use "other components" much, other than to find ghost-components, and I don't really find it to be reliable.

If the top menu had dropdowns for each selected "project" and "language", the issue is solved by unclicking selected "component" and the lower row of navigation is removed.

3. "Followed projects."
This could be put in the top "projects", and displayed as an eye icon next to the name.
Bonus for adding "administrated"  and ghost icons here instead of having to go to respectively user profile and project view.

4. "Suggested projects"
I don't like this, and I'd much rather have it at be at the very end of the project list, with the buried user profile selection being one of selecting to never see a project.
Especially seeing as there is a situation of "isomorphic" in suggested, which is marked now as "proprietary" on Hosted, it needs no "steering" of the user, which is why FSF doesn't like the DFSG.

5, "Insight > recent additions".
This is a very commonly used power feature and I think it should be at the top of Projects (before it moves to the bottom) for everyone, because it really helps new projects. To get as many projects into the loop as possible is great.

6. "History and search"
This should be in the top bar under a magnifying glass icon. It uses the space saved in 1.
It is possible to put "recent additions" in a submenu here instead of in projects. (as suggested in 5)
Having to go the bottom of project changes/history or search there to go to page two to get the settings for the search is ugly.

7. "Tools > search and replace"
This is the third "search", which should all be in search (see 6)

8. "Statistics and translation reports"
Who cares about statistics other than finding people or what they do? That is the actual value anyway.
I'd say put this in Search (see 6).
Translation reports are pretty useless for users by default. I think that should be in the search, maybe as a subcategory at most.

9. Download / Upload
Could be buttons in the colums next to project view > browse and edit columns, which has a lot of empty spce

10. Project view >
Available button in top Project field (see 2), similar to other icons (see 3)
Could be an expanding horizontal submenu field too, but that is ugly because it is a nested menu

11. Project view > Overview
This is now the default view, so this can be removed.

12, The top "+" button
This should be the same as "add new language" in project view, both of which should be moved to the top(?).
Alternatively there should only be an option when clicking top project (see 2.) and then "add new component" only available from there(?)

13. "+" > Buy new plan
"should be in the add component/project process somewhere.

14. I would really want a top category of "meta tags".
What projects are "SailfishOS", which ones are "iOS", I don't know anymore.
This would be really be a great way of finding projects based on license, or topic.

15. One could imagine future improvements where multiple categories and entries can be selected, with failing controls and other stuff drawing attention if need be.

16. To avoid scrolling on mobile screens in vertical mode, all top categories could be icons(?)

There are many other considerations, but am I onto something here?

**Comment by comradekingu** [comment]
Good idea?

**Comment by nijel** [comment]
No - it mixes up many topics and is based on your opinions instead of what other users actually do. There are some valid points, but having issues covering so many different points makes it hard to read.

> This is a very commonly used power feature

It is used about 5 times a day at Hosted Weblate, that doesn't look like a commonly used thing.

> Who cares about statistics

It is frequently used to see the translation progress. We've received quite some positive feedback on that.

Generally, a user interface is not about squeezing as many things as possible into single row.
