### ISSUE TITLE
Handle files in one directory as one component

### ISSUE THREAD

**Issue by MrManor** [WeblateOrg/weblate#6632]
**Is your feature request related to a problem? If so, please describe.**
I am very new to Weblate so I might have missed something obvious.

But I was hoping to use wl for translating a specific job. Source code is not mine, but I offered to help with translation. Weblate setup was easy using Docker, but on importing I found that I need to fill in a webpage for every file? This project is build with a directory pr langue and has something like 322 php files in each language directory. Some with many lines, but many with only a few lines to translate.

Do I really have to create a component for each file using the web interface?

**Describe the solution you'd like**
Could it be possible make weblate treat all files in a directory as one component?

**Comment by nijel** [comment]
Yes you need a component for each file to translate. But you can automate that using https://docs.weblate.org/en/latest/admin/addons.html#component-discovery

**Comment by MrManor** [comment]
> Yes you need a component for each file to translate. But you can automate ..
Thanks for your fast answer and glad to hear that the process can be automated. Although looking the front end, I fear that potential participants, meeting a list with several hundreds of 'components' might be scared away. So I would say, that handling directories as components, is still on my wish list. Not only to ease administration, but also to be able to get/keep participants committed. I also understand that this is not a simple change to implement and might be out of scope for weblate.

> This issue looks more like a support question than an issue. 
I respectfully disagree, especially now after reading your answer @nijel . But my limited experience with Weblate made me unsure whether I had missed something - and I was trying to let my doubt be in Weblates favor. 

> but [purchasing the support subscription](https://weblate.org/support/) is not only more responsible and faster for your business but also makes Weblate stronger.
That I will certainly consider that, - if I get a business some day. For now I am just a IT guy using my spare time helping out the volunteer based local community theater translating some semi-opensource software they need. 

> In case your question is already answered, [making a donation](https://weblate.org/donate/) is the right way to say thank you!
I case we go further using Weblate I will try to convince the board of the theater to make a donation. Based on my observations above, I unsure if we can use Weblate to engage the local community in translating.
