### ISSUE TITLE
Some small ideas for hosted weblate project

### ISSUE THREAD

**Issue by Blueberryy** [WeblateOrg/weblate#6643]
Widgets panel: 
![Screenshot_20211006-100650_Chrome](https://user-images.githubusercontent.com/36592509/136156222-1964aaa5-3b31-4d7d-9310-ccc032ff6b4f.jpg)
**Use Weblate** & **and _join the community_** should be translateable through the project.

Announcement Messages: 
![Screenshot_20211006-100727_Chrome](https://user-images.githubusercontent.com/36592509/136156509-0b34f685-82b9-43d5-8bc2-a96100ae0168.jpg)
Just in case, let people translate them, maybe there will be some important announcement. Just add it :)

**Comment by nijel** [comment]
Announcements are there https://docs.weblate.org/en/latest/admin/announcements.html

Missing localization of widget is already covered by #4198

**Comment by nijel** [comment]
Duplicate of #4198
