### ISSUE TITLE
Visual character movement different from actual glyph width

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#6700]
**Describe the issue**

There's some gap between the glyph visuals and the glyph logical width.
I'm guessing it happened because of webfonts configuration that was configured in LibreOffice's Weblate instance, specifically for Hebrew.

**I already tried**

When the text is short there's not much difference between the cursor location and the actual location in text but when the text gets longer it's clearer.

**To Reproduce the issue**

1. Switch to Hebrew
2. Translate some term
3. Start writing some text in the textarea
4. The cursor and the logical location of it are different

**Expected behavior**

The cursor should be coordinated with the text.

**Screenshots**

![photo_2021-10-20 22 46 27](https://user-images.githubusercontent.com/406826/138161489-0d036760-96bc-4caf-bbbe-914b4c45cc45.jpeg)
Thanks @ItielMaN !

**Additional context**

LibreOffice's Weblate version is 4.8.1.

**Comment by nijel** [comment]
This font is not used in Weblate, so most likely it was patched by them. Please get in touch with site admins to adjust the patch to cover this as well.

Their custom CSS is:

```css
div[lang="he"], textarea[lang="he"], span[lang="he"] {
      font-family: 'Assistant', 'Source Sans Pro', sans-serif;
}
```

**Comment by yarons** [comment]
It looks better now, they must have fixed it somehow, wouldn't it be easier for them to simply work with web fonts?

**Comment by nijel** [comment]
Sorry, I have no clue how they patched Weblate and what changes they have...

**Comment by yarons** [comment]
OK then, thank you. 😃
