### ISSUE TITLE
Glossary explanation duplidated/missing

### ISSUE THREAD

**Issue by ghost** [WeblateOrg/weblate#6701]
**Describe the issue**

The  glossary explanation gets lost. When adding it via the glossary itself, there are 2 explanation fields afterwards.

**To Reproduce the issue**

1. Open an existing translation component in the project containing some translation strings
2. Start the translation and click on 'Add term to glossary' on any item.
3. Fill in the form fields and add an explanation
4. Go to the glossary and check for the term added in step 2/3

**Expected behavior**
The term shows the explanation that was typed in earlier.

**Actual behavior**
The term doesn't have an explanation. After typing it in a second time, there are 2 explanation fields.

**Screenshots**
<img width="296" alt="2021-10-21_09h41_28" src="https://user-images.githubusercontent.com/86038446/138233639-4352249c-9fca-4f9b-a2ae-5c2e88c711b0.png">
<img width="234" alt="2021-10-21_09h41_59" src="https://user-images.githubusercontent.com/86038446/138233663-0beab304-8981-4ff8-9e6d-1b9152065df5.png">
<img width="143" alt="2021-10-21_09h42_43" src="https://user-images.githubusercontent.com/86038446/138233683-2795f4bc-8e8c-4551-ac02-bfe368f235fa.png">

**Comment by ilocit** [comment]
I was able to verify that the Explanation you enter in the "Create" field is not stored/shown with the entry itself. 
But when I enter an explanation in the Glossary component, it works and only "one entry", not two.

Still, the initial explanation which was provided should be persisted and shown.

**Comment by nijel** [comment]
The tricky part is that the explanation is on both source string and translation. It is indeed confusing in many situations, so we should do something about that... 

Some issues with editing explanation were fixed in https://github.com/WeblateOrg/weblate/issues/6283, what version do you use?

**Comment by Rene-Cryptshare** [comment]
I'm using the latest version: 4.8.1

**Comment by nijel** [comment]
I struggle to reproduce this:

* Whenever I add a glossary entry, it shows the explanation immediately in the side panel. Can you confirm this?
* When I click edit icon on that entry, the explanation is there as well.
