### ISSUE TITLE
Weblate created PR brings back removed gettext comments

### ISSUE THREAD

**Issue by hhyyrylainen** [WeblateOrg/weblate#6702]
**Describe the issue**

Weblate seems to somehow put comments that have been removed into the PRs it creates for .po files.
Here's an example PR (ignore the ton of line wrapping changes, I opened a separate [issue](https://github.com/WeblateOrg/weblate/issues/6688) about that): https://github.com/Revolutionary-Games/Thrive/pull/2662

And specifically one place where it happens: https://github.com/Revolutionary-Games/Thrive/pull/2662/files#diff-c43ee329ecf73e9166b48f65c52c2a6c8e8d41b965c548888072f915208d8e63R415
When I manually ran gettext after merge, it promptly removed all those incorrectly added comments that shouldn't be in the files.

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above. I have not found any existing issue with any of the keywords about this that I thought to use
- [x] I tried to reset the Weblate local translations repo just before that bad PR was opened

**To Reproduce the issue**

1. Have weblate configured to create PRs for gettext translations. Maybe the option to squash merge per author has something to do with this?

**Expected behavior**

I expect Weblate created PRs to not bring back removed comment parts. If this keeps happening whenever anyone runs the text extraction process it bloats PR diffs as they go back and forth removing and adding back the text.

**Server configuration and status**

Weblate installation: PyPI

I included this section info in my other issue I opened recently (I have not updated anything since then, and this issue became visible at the same time as that other one): https://github.com/WeblateOrg/weblate/issues/6688

**Comment by nijel** [comment]
Your translation is configured as monolingual. That means that the strings are defined in the base file - English in your case. So whatever is present in the English file can be translated and will get saved to the translation files. This includes string location comments or strings removed from the translation files. See also https://docs.weblate.org/en/latest/formats.html#bimono

**Comment by hhyyrylainen** [comment]
Looking through the en.po at the time that branch was merged (I assume here that weblate had correctly rebased so that there can be no commits with changes to the en.po file between this commit I'm looking at and what weblate had to work with), I don't see any of those lines in the file: https://github.com/Revolutionary-Games/Thrive/blob/88e230f6f50872f6c5f75f8b000dac874c523db8/locale/en.po

Could it be that weblate had seen a previous version of en.po which then when a new commit was added to master and weblate rebased the PR it did not revert the changes to the comments in different languages?

**Comment by nijel** [comment]
Weblate always takes the version it has in the repository when doing the commit. The commit is done before pulling changes, so if you did changes in Weblate, then updated the en.po and then pulled changes into Weblate, the commit would still use old po file.
