### ISSUE TITLE
[Bug] Cannot login with Google and Github account

### ISSUE THREAD

**Issue by shun2wang** [WeblateOrg/weblate#6730]
**I cannot login weblate when I click the 'Google"or 'Github‘ button, The page cannot be opened for a long time，and chrome says 'ERR_CONNECTION_RESET'** 

I've tried to use proxy or direct connection，but it didn't work. Other web pages can be opened normally.Maybe you can see the error message from the log record in the background of the website，time form this issue open.

1. Go to https://hosted.weblate.org/
2. Click on 'https://hosted.weblate.org/accounts/login/github/'
3. See error

**Comment by nijel** [comment]
This looks more like a networking issue. Are you using some VPN?

**Comment by icekylin** [comment]
In some cases I do use a VPN to guarantee the connection speed, but this kind of problem seems to occur when I don’t use it. Will Weblate refuse VPN connections?

**Comment by nijel** [comment]
Weblate will not refuse that. However, there were issues with some VPN provider blocking access to our services in the past, so I'd like to rule that out...

Back then it was with GlobalProtect, and they modified DNS responses so that it resolved to their server instead of our one:

```
$ dig hosted.weblate.org
; <<>> DiG 9.11.26-RedHat-9.11.26-4.el8_4 <<>> hosted.weblate.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26259
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
 
;; QUESTION SECTION:
;hosted.weblate.org. IN A
 
;; ANSWER SECTION:
hosted.weblate.org. 1 IN CNAME sinkhole.paloaltonetworks.com.
 
;; Query time: 11 msec
;; SERVER: 9.25.147.1#53(9.25.147.1)
;; WHEN: Wed Oct 06 14:37:03 CEST 2021
;; MSG SIZE rcvd: 79
```
