### ISSUE TITLE
Unable to add translate component

### ISSUE THREAD

**Issue by icekylin** [WeblateOrg/weblate#6736]
I’m reporting a problem here, according to [#1482](https://github.com/jasp-stats/jasp-issues/issues/1482)  issue in JASP project.Please help us to see if there is a configuration error.

**Comment by nijel** [comment]
JASP project has exceeded the limits for the Libre plan (it matches the Advanced plan), that's why you cannot add new component. Please write to care@weblate.org to discuss possible solutions.

**Comment by icekylin** [comment]
Thank you for your answer, I will inform the project organizer.
