### ISSUE TITLE
Disable Machine Translation for per-project

### ISSUE THREAD

**Issue by Wouter0100** [WeblateOrg/weblate#6749]
### Describe the issue

I've digged through the documentation and issues, but I can't seem to get an answer on this question: we may consider enabling DeepL in our Weblate instance. Although, we do not want to enable it on all projects right away. 

So, is there any way to disable DeepL and/or Machine Translations for specific projects if we enable it in the system configuration?

Thanks,

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
Duplicate of #6539

**Comment by Wouter0100** [comment]
Right, I didn't search for "MT". Only for "Machine Translations". Thanks!
