### ISSUE TITLE
 Android Studio says "he" should be called "iw"

### ISSUE THREAD

**Issue by tateisu** [WeblateOrg/weblate#6760]
### Describe the issue

https://github.com/tateisu/SubwayTooter/issues/153

About res/values-he/strings.xml, Android Studio's lint check says
> The locale folder `he` should be called `iw` instead; see the `java.util.Locale` documentation

Before switching the country code to `iw`, I want to consider the following implications:
- Weblate can handle it ? Seems they can't customize the country code.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Yes, it will handle it.

**Comment by tateisu** [comment]
thanks!
