### ISSUE TITLE
Whitelist for consecutive words

### ISSUE THREAD

**Issue by Fjoerfoks** [WeblateOrg/weblate#6773]
### Describe the issue

In Frisian we have several strings where we use consecutive words, like ‘jo jo’ and ‘mei mei’.
I would like to add these to some sort of whitelist, but couldn't find it in the docs on https://docs.weblate.org/en/latest/user/checks.html#check-duplicate.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to 'https://translate.element.io/translate/element-android/element-app/fy/?q=check:duplicate'
2. See error

### Expected behavior

Not marked as false.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
The reproducer link requires login, can you please share the text directly?

Adding the words to the list is simple, patches are welcome, the code is here:

https://github.com/WeblateOrg/weblate/blob/371015c92ac216d6d05aff57a3804c9090db2542/weblate/checks/duplicate.py#L33-L39

**Comment by nijel** [comment]
I've added the two words you mention, in case you know more, please share that.
