### ISSUE TITLE
Autotranslated field

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#6774]
### Describe the problem

Autotranslated entries are hard to check, since they are only available in the (non-editable) history.

### Describe the solution you'd like

A section for autotranslations

The problem is similar to reverting/checking translations or edits made by others, so there could be one for
"translated by others", but I think in addition, since autotranslations are particularly worrisome.

### Screenshots

![bilde](https://user-images.githubusercontent.com/13802408/141013639-e8ef8d03-ad3f-4765-b9fa-a5fc1864254b.png)

**Comment by tomkolp** [comment]
Currently, with a new file, I do this:
1) I use automatic translation
2) labeled "automatic translation"
This suggestion seems to be right if you could still associate your label with automatic translations. That would help me save a few hours of work per month.

**Comment by nijel** [comment]
(Optionally) adding label to auto-translated strings might be a viable solution.

**Comment by comradekingu** [comment]
@nijel I think that would work. The problem is it doesn't show up in the bar.
I think one common category and then different ones for
- Imported from project strings
- Imported from instance strings
- Machine-translated

Propagated/imported strings aren't as bad, but machine-translation is the real problem.

**Comment by nijel** [comment]
If it is a problem, it might be better to make these suggestions or set the auto-translated strings as needs editing.

**Comment by comradekingu** [comment]
>auto-translated strings as "suggestions"

This is true from the point of view of importing, but only because there is no differentiation between translated and auto-translated strings now. If they are to enter the stringbase at all, they can't be suggested.

>auto-translated strings as "needs editing"

This weakens the state of uncertainty, (and what is often a problem with the source string since it is easier to do)  by conflating it with something that "needs a lot more editing"

In the widgets, it would be really marketable to show manually translated strings as different from auto-translations.
The same thing goes for the statistics.
