### ISSUE TITLE
API | Support "query filters" for translation files

### ISSUE THREAD

**Issue by ad-boschung** [WeblateOrg/weblate#6797]
### Describe the problem

Context : 

We have multiple translation projects that are shared between multiple development projects in a single source format. This is to avoid to translate the same keys in every projects.

Then, we use a script that import the translation files from different projects in the project required file format.

Weblate : 
- project: my-app, component: main, source lang: EN

Development projects : 
- app-ios : import my-app/main in format: iOS strings
- app-android: import my-app/main in format: Android String Resource

File : EN
```json
{
 "key1": "Hello",
 "key2": "World",
 "key3" : "weblate"
}
```

File : FR (not 100% translated)
```json
{
 "key1": "Hello"
}
```

The script will execute this : 
- app-ios : GET `/api/translations/my-app/main/fr/file/?format=strings`
- app-android : GET `/api/translations/my-app/main/fr/file/?format=aresource`

If we import the FR translations with the GET request, the result looks like this : 
Localizable.strings (iOS format)
```
 "key1": "Hello"
 "key2": "key2"
 "key3" : "key3"
```
Problem : If the key is not translated, it returns a row with the key as value.
That means in iOS it will display in the app the key as value in for this key.

strings.xml (Android format)
```
    <string name="key1">Hello</string>
    <string name="key2"></string>
    <string name="key3"></string>
```
Problem : If the key is not translated, it returns a row an empty value.
That means, in Android it will display in the app an empty text for this key.

The FR translation source file doesn't contains the keys: key2, key3. 

So, the formatted file receive from the request should not add the unexisting/untranslated keys.

### Describe the solution you'd like

If we use the weblate web interface we can do a customizable download and choose the file format and define a filter for the translations.  
We can download the needed file in format iOS and Android with the filter : `state:>=translated`.
It will return me exactly what I want : Only the translated keys in the format requested.

![Screenshot 2021-11-12 at 10 32 24](https://user-images.githubusercontent.com/32476796/141452501-c0687a81-800c-49bb-98af-54afb50669c3.png)

We analysed the request done by the web interface :   
`https://translate.borrma.info/download/{project}/{component}/{lang}/csrfmiddlewaretoken=X&q=state:>=translated&format=strings`

Unfortunately, I cannot use it in my script because of authentication issue ?
We always receive a `404 - Access denied`. By the way, related to HTTP it should be a `403 - Forbidden` I guess.

The API `/api/translations/{project}/{component}/{lang}/file/` endpoint offers the query parameter `format`, but not the `q` parameter like the `download` request.

It would be great if you could implement this query parameter in the `/api/translations/{project}/{component}/{lang}/file/` endpoint too. 
This way we could specify the filters using the API, like we can use this feature on the web interface.

### Additional context

Weblate API : 4.7.2. 

But in the latest version this feature is not present either.

**Comment by nijel** [comment]
>  We always receive a 404 - Access denied. By the way, related to HTTP it should be a 403 - Forbidden I guess.

It's 404 to avoid information leak. But your URL seems wrong anyway (missing `?`).

**Comment by ad-boschung** [comment]
Thanks for the reply and your quick implementation.  
Do you already know when it will be released ?

**Comment by nijel** [comment]
Probably next week.
