### ISSUE TITLE
May I ask for a translate connection function?

### ISSUE THREAD

**Issue by dewcked** [WeblateOrg/weblate#6800]
### Describe the problem

If project manager adds a string that doesn't need to be translated (like fragment of code or keyboard shortcuts), and if we don't translate it, it remains being connected to the original block. But If someone translate it, then the connection is broken.

Later the original string might be changed. Then someone need to fix the translated block.

Leaving a block untranslated is somehow uneasy (because it is counted as untranslated). Is there any function or going to add function to let the block as translated and also being connected to original block?

### Describe the solution you'd like

Add option to connect to a original string.
- If connect is enabled, string is counted as translated. Because it is connected to original. Translation text area is disabled.
- If connect is disabled, Translation text area is enabled.

Add connect option for each string.
- Default value: disabled.
- Only project manager can enable this whenever you want.

Scope
- Adapting this option per-language costs tons of resources, so I don't really expecting it. I just want per-string.

Privilege
- With above scope, only project manager can toggle the option.

**Comment by dewcked** [comment]
I may seem silly, but the strings inserted in the middle of the context are usually registered in the same order on the translation list to avoid damaging the context, and I thought the connection option was needed in the above situation.

**Comment by dewcked** [comment]
Add to this, translated text with special characters same to origin doesn't show any error. Is this bug or?

**Comment by nijel** [comment]
You can mark string read-only, that will avoid translation

**Comment by dewcked** [comment]
> You can mark string read-only, that will avoid translation

Oh.. I haven't managed projects yet, so didn't know that.. I'll ask for that to manager. Appreciate.
