### ISSUE TITLE
Search against pattern containing Scandinavian characters

### ISSUE THREAD

**Issue by Ricky-Tigg** [WeblateOrg/weblate#6826]
### Describe the issue

Searches against patterns containing Scandinavian characters invariably produce null outputs.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. In Finnish section, search against target text _lähitulevaisuudessa_;
2. Inspect the output.

### Expected behavior

_Match found_; the presence of the searched pattern shall be attested by searching against _tulevaisuudessa_.

### How do you run Weblate?

weblate.org service

### Weblate versions

4.9

**Comment by nijel** [comment]
Works for me: https://hosted.weblate.org/search/matomo/plugin-segmenteditor/?q=+target%3Atulevaisuudessa

**Comment by Ricky-Tigg** [comment]
What happened to you? You did test against the expected section! That is a sure indication of overwork. What about [that](https://hosted.weblate.org/search/matomo/plugin-segmenteditor/?q=+target%3Al%C3%A4hitulevaisuudessa) instead?

**Comment by nijel** [comment]
I probably misread the report, sorry. Providing links to broken search and to the string which should have been found would avoid that...

**Comment by nijel** [comment]
> What about that instead?

Well, there is no such string in this translation. Can you please share a link to the string which should be found and is not?

**Comment by Ricky-Tigg** [comment]
That issue demonstrates that the service works as intended randomly since a [target](https://translate.fedoraproject.org/languages/fi/-/search/?offset=1&q=+target%3Al%C3%A4hitulevaisuudessa&sort_by=-priority%2Cposition&checksum=) is at this moment found. Not a glory case. Conclude from it whatever you want.

**Comment by nijel** [comment]
It does not work randomly, did you notice that you are on a different server than before?

**Comment by Ricky-Tigg** [comment]
> It does not work randomly,

No one suggested that we have had at any time cloned environments. It did not come to my mind at the time to check the server mention in Firefox _Developer tools_: for now it is reported as _nginx_ alone. However the view if the console is not pretty.

![firefox](https://user-images.githubusercontent.com/26058215/142879141-936b1bab-c329-403a-a6d7-1dccfa35a257.png)
