### ISSUE TITLE
Q: Is it okay to have few projects in single git repo?

### ISSUE THREAD

**Issue by Belorus** [WeblateOrg/weblate#6836]
### Describe the issue

Subj :) 

I have multiple projects with 3 components each.

Components reflect git branches (dev/release/prod).
Projects sit in same git repo, and structure is simple (same for each branch):
```
/project1/en_US.json
/project1/ja_JP.json
/project2/en_US.json
/project2/ja_JP.json
/project3/en_US.json
/project3/ja_JP.json
```

Branches (components) are merged **dev** -> **release** -> **prod** to follow our app git branching approach.

I have lots issues with git conflicts, and got a feeling that projects in same repo might be a bad idea. Could you please share best practices?

In documentation there is a phrase that same repo can be shared between components, but can it be shared between components AND projects?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

Docker container

### Weblate versions

4.8.1

**Comment by nijel** [comment]
If your translations are done in Weblate into multiple branches, it is recommended to avoid merging translations in git and use a merge strategy that prefers branch translations when merging. See https://docs.weblate.org/en/latest/faq.html#how-do-i-translate-several-branches-at-once (or https://github.com/phpmyadmin/phpmyadmin/wiki/Git#merging-translations).
