### ISSUE TITLE
Status badge widgets have incorrect width

### ISSUE THREAD

**Issue by rob006** [WeblateOrg/weblate#6838]
### Describe the issue

On [this page](https://rob006-software.github.io/flarum-translations/) I have multiple status badges, which should illustrate the issue ([screen](https://user-images.githubusercontent.com/5972388/142764329-4e801761-8f74-4f87-a008-314df842a00b.png)). I can replicate all these issues on https://hosted.weblate.org/:

1. All badges does not have horizontal padding and it feels too cramped - ![](https://hosted.weblate.org/widgets/weblate/en/svg-badge.svg)
2. Some badges are too small and text does not fit - ![](https://hosted.weblate.org/widgets/weblate/th/svg-badge.svg)
3. Some badges are much bigger then they should - ![](https://hosted.weblate.org/widgets/weblate/hi/svg-badge.svg)

This is regression since 4.8.1 - badges were fine there (although I noticed that width of badge randomly changed).

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Git checkout

### Weblate versions

 * Weblate: weblate-4.9.1
 * Django: 3.2.9
 * siphashc: 2.1
 * translate-toolkit: 3.5.1
 * lxml: 4.6.4
 * Pillow: 8.4.0
 * bleach: 4.1.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.1.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.13.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4.1
 * djangorestframework: 3.12.4
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.4.0
 * setuptools: 59.2.0
 * jellyfish: 0.8.9
 * openpyxl: 3.0.9
 * celery: 5.2.1
 * kombu: 5.2.2
 * translation-finder: 2.10
 * weblate-language-data: 2021.6
 * html2text: 2020.1.16
 * pycairo: 1.20.1
 * pygobject: 3.42.0
 * diff-match-patch: 20200713
 * requests: 2.26.0
 * django-redis: 5.0.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.5.0
 * Cython: 0.29.24
 * misaka: 2.1.1
 * GitPython: 3.1.24
 * borgbackup: 1.1.17
 * pyparsing: 3.0.6
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * Python: 3.8.10
 * Git: 2.25.1
 * psycopg2-binary: 2.9.2
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.17.17
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.20.10
 * zeep: 4.1.0
 * aeidon: 1.10.1
 * iniparse: 0.5
 * mysqlclient: 2.1.0
 * Redis server: 5.0.7
 * MySQL sever: 8.0.27
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379/0, redis://localhost:6379/0, regular
 * Platform: Linux 5.4.0-90-generic (x86_64)

### Weblate deploy checks

```shell
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E034) The Celery process is outdated or misconfigured. Following items differ: vcs
	HINT: https://docs.weblate.org/en/weblate-4.9.1/admin/install.html#celery

System check identified 1 issue (7 silenced).
```

**Comment by rob006** [comment]
> 2. Some badges are too small and text does not fit

This is browser specific. On Chrome it is rendered OK, but on Firefox I gave this:

![bd172f9d](https://user-images.githubusercontent.com/5972388/142766244-90fb4f42-172d-41ba-96bf-fe996510c275.png)

It looks fine if I remove `lang` attribute from SVG.

>  3. Some badges are much bigger then they should 

This may be a problem with font. I have tested this phrase on https://www.fontsquirrel.com/fonts/dejavu-sans and it renders a long string of garbage:

![6130d71e](https://user-images.githubusercontent.com/5972388/142766319-69807856-0671-4782-bed1-d53a71bb4cd4.png)

**Comment by nijel** [comment]
There are probably several issues here:

- Hindi text width calculation seems wrong (testing with shields.io, we're not alone in this: https://img.shields.io/badge/%E0%A4%85%E0%A4%A8%E0%A5%81%E0%A4%B5%E0%A4%BE%E0%A4%A6%E0%A4%BF%E0%A4%A4-90-red)
- Wrong widget width generally, this is most likely a side effect of ebc31818eea4e82efa4e588693579d9c60c23dd3
- The XML `lang` attribute pushes some browsers to choosing different font sizes. In this particular case, the problem is that Firefox has default preference of minimal font size for Thai set to 13px. This is the only language having such override in Firefox, what is a bit weird...
