### ISSUE TITLE
Pull request support for GitHub Enterprise Server

### ISSUE THREAD

**Issue by gilfthde** [WeblateOrg/weblate#6853]
### Describe the problem

We would like to use the "[Pushing changes to GitHub as pull requests](https://docs.weblate.org/en/weblate-4.9.1/vcs.html#pushing-changes-to-github-as-pull-requests)" feature with *Github Enterprise Server (GHES)*. Currently this does not work because on GHES the API endpoint is different from GitHub cloud.

The current code derives the API endpoint from the repository URL (extracts the hostname) and only changes it to`api.github.com` if the repo URL points to a repository on GitHub cloud. But for GHES the base API endpoint is `<hostname>/api/v3`.

As a result all requests to create the pull request fail with an authentication error because Weblate tries to access an UI URL instead of the API, which in turn results in a redirect to the user login page.

### Describe the solution you'd like

Change the code to derive the API URL form the repository URL to append the `/api/v3` suffix to the hostname if the repository is not on GitHub cloud. Maybe an additional configuration property is required to control this.

**Comment by nijel** [comment]
The logic would probably fit here:

https://github.com/WeblateOrg/weblate/blob/af562880a48f8a0ebdb7574e4cfe7eaf99f74b07/weblate/vcs/git.py#L821-L824

**Comment by gilfthde** [comment]
Have a look at my draft PR. It implements the support as a new repository backend. I think this is a more clean solution.
