### ISSUE TITLE
Improve Search and Replace feature

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#6854]
### Describe the problem

- It is hard to define the search query
- It’s not possible to search for words, just for strings
- Search term and query parameters are both in one field

### Describe the solution you'd like

- [ ] Separate search term and query parameters into two fields
- [ ] include query builder and examples like in search
- [ ] tell the user "Don’t worry about messing up the strings. This is a two-step process showing a preview of edited strings before the actual change is confirmed." right on the page, not only in the docs
- [x] link the docs via the "**i**" link

### Describe alternatives you've considered

🤔  Include Replace as an option inside the Search feature. Considering Access control changes is needed as managers would like to differ access to S&R from just Search.

**Comment by nijel** [comment]
The documentation link was just added in 9d496c3ace87f92d661bcd52bbd3eab626bce4ae

**Comment by nijel** [comment]
And first point is already covered by https://github.com/WeblateOrg/weblate/issues/4022

**Comment by nijel** [comment]
Also related: https://github.com/WeblateOrg/weblate/issues/4108
