### ISSUE TITLE
Cannot logout when updating to 4.9.1

### ISSUE THREAD

**Issue by gramakri** [WeblateOrg/weblate#6859]
### Describe the issue

Updated Weblate 4.9 to 4.9.1. Logout does not log out the user.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

* Install 4.9
* Login/logout - works fine
* Update to 4.9.1
* Cannot logout. User remains logged in

This is not reproducible on a fresh install on 4.9.1. But always reproducible when updating from 4.9 to 4.9.1

### Expected behavior

User should be logged out.

### Exception traceback

```pytb
No errors in the logs or browser console.
```

### How do you run Weblate?

Other

### Additional context

I am updating the Cloudron package to 4.9.1 when I found this problem.

**Comment by nijel** [comment]
Is there a configuration change? Looks like one of the versions has https enabled and one not

**Comment by gramakri** [comment]
@nijel I found that clearing the statics cache makes it work. But I had to delete this manually, checking if I missed something in the docs about how to clear the cache before/after update.

**Comment by gramakri** [comment]
OK, `weblate collectstatic --noinput --clear --link` makes it work.

For future reference, https://docs.weblate.org/en/latest/admin/install.html#static-files has information on how to customize the statics directory.

**Comment by nijel** [comment]
Thanks for the hint, I've clarified the upgrading docs in 36d23c619858d064eb035e3006a87687d0b9007d.
