### ISSUE TITLE
Request for label change

### ISSUE THREAD

**Issue by kyotaro** [WeblateOrg/weblate#6860]
### Describe the problem

There are now two functions for saving translations. 
This is probably necessary for functionality.
They are 'Save' and 'Save and stay'.
However, the labels are not easy to translate, so could you change them to be functional, simple and easy to understand?

### Describe the solution you'd like

`Save' ⇒ 'Save and Next'
'Save and stay' ⇒ 'Save Only'

**Comment by orangesunny** [comment]
Thank you for this, @kyotaro!

`Save` will stay as it is; it‘s what most translators use and expect from the button.
`Save and stay` could be renamed, it is a pretty new feature. `Save and stay on the string` would be better descriptive, but it is much longer.

**Comment by shima-office** [comment]
The word "save" doesn't mean "save and screen transition" in the first place.
But in weblate, if you push "save" button ,the screen unexpectedly transits to another screen of next source string.
It's misleading and confusing many users.
So the "save" button should not be used to mean "save and screen transition".
The button for saving and screen transition should be labeled clearly as "save and transition to next raw string" or "save and next" or "save and transition".
I appreciate Kyotaro's suggestion above.

**Comment by nijel** [comment]
While it's not an exact name, it's the action most people want to do. Giving it confusing names such as "Save and next" or "Save and transition" will not help anything.

It was called "Save" since ever (a358491a87c) and nobody complained about that until another button was added (see https://github.com/WeblateOrg/weblate/issues/5047). So, it's probably not that bad name :-).

We might change the name, but the new name cannot be confusing. Neither for new users to understand that this is what they most likely want to click, nor for existing users who got used to "Save".

**Comment by comradekingu** [comment]
@kyotaro What if you go with ~"Save and continue"?

**Comment by Geeyun-JY3** [comment]
FYI, there is an option called “Automatically move to next string” in the editor setting of Crowdin:
![image](https://user-images.githubusercontent.com/49396421/143915816-7e65462a-a876-4240-bba0-d848adaba20e.png)

TBH, I prefer the current two button mode in Weblate. Maybe a tooltip can be added for the current “Save” button?

**Comment by kyotaro** [comment]
I understand your opinion well.
I think it depends on the language.

If so, would you be able to do a different translation only here?

Could you at least separate the translation from the label of the 'save' button on the translation editing page?
 I would like to make a different translation only on the translation editing page, but if I make a change, more than 20 are used elsewhere and the effect is too big.

**Comment by comradekingu** [comment]
Maybe "Save, but stay" makes the distinction clear?
