### ISSUE TITLE
Poorly distinguishable colors

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#6868]
### Describe the problem

The colors of the translated and approved string are very similar, this is quite problematic e.g. in search results.

### Describe the solution you'd like

Applying a different color to an approved string or adding a feature to change the color.

### Screenshots

![unknown](https://user-images.githubusercontent.com/39633242/143282850-2fa7cfef-df64-4bad-878e-ef19b5d2795c.png)

**Comment by comradekingu** [comment]
With low blue-sensitivity on part of the user there is no telling those apart. Unfortunately telling red from green also suffers then.
It used to be https://github.com/WeblateOrg/weblate/issues/4985
but now it is worse since there is no yellow in between.
