### ISSUE TITLE
User profile page shows password warning even though password cannot be set

### ISSUE THREAD

**Issue by derkoe** [WeblateOrg/weblate#6871]
### Describe the issue

Even though a server does not allow authentication via e-mail a warning on the user profile is shown that you should configure a password. When you click in "Configure the password" an error is shown: "Cannot reset password, e-mail authentication is turned off."

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Expected behavior

Password warning banner should not be shown when e-mail authentication is turned off.

### Screenshots

![image](https://user-images.githubusercontent.com/123199/143469682-f9aa2f5a-d8c6-40ed-8599-516a417afe4a.png)

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.9
 * Django: 3.2.9
 * siphashc: 2.1
 * translate-toolkit: 3.5.1
 * lxml: 4.6.4
 * Pillow: 8.4.0
 * bleach: 4.1.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.1.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.13.0
 * oauthlib: 3.1.1
 * django-compressor: 2.4.1
 * djangorestframework: 3.12.4
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.3.2
 * setuptools: 58.5.3
 * jellyfish: 0.8.9
 * openpyxl: 3.0.9
 * celery: 5.2.0
 * kombu: 5.2.2
 * translation-finder: 2.10
 * weblate-language-data: 2021.6
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.38.0
 * diff-match-patch: 20200713
 * requests: 2.26.0
 * django-redis: 5.0.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.4.3
 * Cython: 0.29.24
 * misaka: 2.1.1
 * GitPython: 3.1.24
 * borgbackup: 1.1.17
 * pyparsing: 3.0.6
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * Python: 3.9.2
 * Git: 2.30.2
 * psycopg2: 2.9.2
 * psycopg2-binary: 2.9.2
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.17.17
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.20.8
 * zeep: 4.1.0
 * aeidon: 1.10.1
 * iniparse: 0.5
 * mysqlclient: 2.0.3
 * Mercurial: 5.9.3
 * git-svn: 2.30.2
 * git-review: 2.1.0
 * Redis server: 6.2.5
 * PostgreSQL server: 11.13
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mailz.porsche.co.at
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379/1, redis://localhost:6379/1, regular
 * Platform: Linux 3.10.0-1160.25.1.el7.x86_64 (x86_64)

**Comment by math-a3k** [comment]
@derkoe, I cannot reproduce the bug, I have created a test for the logic and seems working: https://github.com/math-a3k/weblate/commit/70487ccc6e38acd1c856930f68ae8473b3f1911e

The logic for this was introduced in https://github.com/WeblateOrg/weblate/commit/a5b76f1fc4d09022e9f4e555d35b10651234d30c, which is included in weblate 4.9 (the version you are using)

I cannot think of a scenario where the email backend is enabled for the profile and disabled for the password change / set, which seems the only way that may lead to show the error and the warning at the profile as your screenshot shows.

The only thing that seems plausible is that for whatever reason your code differs, can you check that your weblate/accounts/views.py contains these conditions?
- https://github.com/WeblateOrg/weblate/blob/main/weblate/accounts/views.py#L387 
- https://github.com/WeblateOrg/weblate/blob/main/weblate/accounts/views.py#L862

**Comment by derkoe** [comment]
We use the Docker image - so, we cannot change the source code.

We have the following settings regarding auth/registration in `settings-override.py`:
```
REGISTRATION_OPEN = False
REGISTRATION_ALLOW_BACKENDS = ["keycloak", "azuread-tenant-oauth2"]
AUTHENTICATION_BACKENDS = (
    "social_core.backends.keycloak.KeycloakOAuth2",
    "social_core.backends.azuread_tenant.AzureADTenantOAuth2",
    "social_core.backends.google.GoogleOAuth2",
    "weblate.accounts.auth.WeblateUserBackend",
)
```

**Comment by derkoe** [comment]
Just checked it again (after a restart of Weblate) and I cannot reproduce the issue now. We had the issue on our staging and live instance before - very strange. 

I'm closing this now - I will re-open when it happens again.

**Comment by math-a3k** [comment]
I'm afraid that due to current hardware limitations I cannot test with the Docker image.

However, according to your settings, setting https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_NO_EMAIL_AUTH should prevent certainly the warning to be shown.

I'm seeing your update while writing this, well, I will leave some pending additional thoughts:
- 'has_usable_password' is meant for checking if the the User has been flagged by 'set_unusable_password', it does not provides any other checks nowadays (like validation or what used to be https://stackoverflow.com/a/17250296/8930660): https://docs.djangoproject.com/en/3.2/ref/contrib/auth/#django.contrib.auth.models.User.set_unusable_password.
It may be better to use something like 'has_password_set(self): return not(self.password is None or self.password == "") for the case.
- @nijel if you want to incorporate the test, let me know and I'll make the PR

**Comment by nijel** [comment]
The only situation I can think of is that the settings have changed and some workers are still using previous settings. Depending on which ends up handing the request the behavior will differ.

@math-a3k The test is useful, PR is welcome.
