### ISSUE TITLE
Consistency improvement

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#6872]
### Describe the problem

The first column in `Translation with contribution` list of user page should be consistent with the first column in component list of dashboard.

### Describe the solution you'd like

Change `Project` to `Component`

### Screenshots

Dashboard
![image](https://user-images.githubusercontent.com/49396421/143409471-95e690aa-a663-476c-8a6c-24f662a013b3.png)

User page
![image](https://user-images.githubusercontent.com/49396421/143409545-5169d419-4dbc-4117-8653-4c58944e8724.png)

**Comment by comradekingu** [comment]
That used to read "Contributions", but someone with write access found it to be in error.
(It isn't, but now it is though.)

In the same vein that "insights" and "Search" doesn't change scope for the different sections,
where it would be ~"Project search" and ~"Component search"
the word "translations"/"project" (where it already isn't ~Platform/Instance insights/ or -search) could be dropped altogether.

>Watched, Suggested, Insight, Search

>Contributions,  Managed, Watched, Activity, Recent

(This would also align with the URLs for the respective sections, like `[#managed](https://hosted.weblate.org/user/username/#managed)`

Moreover "Recent changes" should really be "History" if consistency is a goal? (It is the same functionality.)
