### ISSUE TITLE
Background task gives date value out of range exception

### ISSUE THREAD

**Issue by tcitworld** [WeblateOrg/weblate#6873]
### Describe the issue

The following line from the `weblate.trans.tasks.commit_pending` task:
https://github.com/WeblateOrg/weblate/blob/cf4e7997505a2ec65c3ee8ae5286d09a9def3083/weblate/trans/tasks.py#L146

Outputs
```
OverflowError

date value out of range
```
In Sentry logs.

Sentry says `component` is defined.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

N/A, background task

### Expected behavior

No error

### How do you run Weblate?

PyPI module

### Weblate versions

 * Weblate: 4.9.1
 * Django: 3.2.8
 * siphashc: 1.2
 * translate-toolkit: 3.5.1
 * lxml: 4.6.3
 * Pillow: 6.2.1
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 4.1.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.9.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-filter: 2.4.0
 * django-appconf: 1.0.3
 * user-agents: 2.0
 * filelock: 3.0.12
 * setuptools: 41.2.0
 * jellyfish: 0.7.2
 * openpyxl: 2.6.3
 * celery: 5.1.2
 * kombu: 5.1.0
 * translation-finder: 2.7
 * weblate-language-data: 2021.5
 * html2text: 2019.9.26
 * pycairo: 1.18.1
 * pygobject: 3.34.0
 * diff-match-patch: 20200713
 * requests: 2.22.0
 * django-redis: 4.12.1
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.1
 * Cython: 0.29.14
 * misaka: 2.1.1
 * GitPython: 3.0.7
 * borgbackup: 1.1.10
 * pyparsing: 3.0.6
 * pyahocorasick: 1.4.1
 * python-redis-lock: 3.7.0
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2-binary: 2.8.3
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.5.1
 * boto3: 1.9.226
 * zeep: 3.4.0
 * aeidon: 1.9
 * iniparse: 0.5
 * Redis server: 5.0.14
 * PostgreSQL server: 11.14
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.19.0-18-amd64 (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

WARNINGS:
?: (weblate.W033.Gerrit) Failure in loading VCS module for Gerrit: git: 'review' is not a git command. See 'git --help'.
 (1)
	HINT: https://docs.weblate.org/fr/weblate-4.9.1/vcs.html
?: (weblate.W033.Mercurial) Failure in loading VCS module for Mercurial: [Errno 2] No such file or directory: 'hg': 'hg'
	HINT: https://docs.weblate.org/fr/weblate-4.9.1/vcs.html
?: (weblate.W033.Subversion) Failure in loading VCS module for Subversion: git: 'svn' is not a git command. See 'git --help'.

The most similar command is
	serve
 (1)
	HINT: https://docs.weblate.org/fr/weblate-4.9.1/vcs.html

INFOS:
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/fr/weblate-4.9.1/admin/backup.html

System check identified 4 issues (1 silenced).
```

**Comment by nijel** [comment]
What is commit age configured on the component?

**Comment by tcitworld** [comment]
`240000000` hours. :see_no_evil: 

I'll ask the project maintainer why there's such a value.

**Comment by nijel** [comment]
Okay, there should be a limit on this value...
