### ISSUE TITLE
Pull problem

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#6875]
### Describe the issue

There is an error retrieving changes from the repository. I locked and unlocked the project, it didn't help.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Docker container

### Weblate versions

4.10-dev — 12d53f1e258185121939b3943e6fea8cee63c863

### Additional context

[sentry](https://sentry.io/share/issue/e124b7188f7e43baa538997c0151bf14/)

**Comment by comradekingu** [comment]
Link to instance?

**Comment by tomkolp** [comment]
> Link do instancji?

https://weblate.eso-spolszczenie.eu/projects/eso-spolszczenie/

**Comment by tomkolp** [comment]
Can I manually remove the index.lock file?

**Comment by nijel** [comment]
Hmm, that still doesn't look like a cause - the question is why gunicorn is being aborted.

**Comment by tomkolp** [comment]
Everything is back to normal after some time after deleting index.lock. Push and pull branch and no errors. I mark the problem as solved, the next tests will be on the next download of changes from external repository in a few weeks. If the problem recurs, I will try to analyze it in detail.

**Comment by nijel** [comment]
It could be hitting memory limits. Switching to gunicorn is quite recent (see https://github.com/WeblateOrg/docker/pull/1275), so it might have some issues...

**Comment by tomkolp** [comment]
Increasing the limits didn't help.
4.10-dev — d98e10e1f000a0d5bba5378e7014dca5ea361397
![image](https://user-images.githubusercontent.com/39633242/144295860-31e3c379-0b4a-4325-b7ce-8a6a7a8d7326.png)
[sentry](https://sentry.io/share/issue/6f0a012dbe8f4a63a378959eacad8937/)

**Comment by nijel** [comment]
Is there anthing from the gunicorn in the logs?

**Comment by tomkolp** [comment]
Only this:
![image](https://user-images.githubusercontent.com/39633242/144392841-1f315306-e46c-4876-9ebd-4e2d1e4ba425.png)

**Comment by tomkolp** [comment]
Download now works, check the rest tomorrow.
https://github.com/WeblateOrg/docker/commit/66ddfe7733e85e02620961225c417901384260b5
@nijel
