### ISSUE TITLE
Arabic Tatweel check is too aggressive

### ISSUE THREAD

**Issue by mhmdanas** [WeblateOrg/weblate#6877]
### Describe the issue

First, I apologize if this is the wrong issue template; this didn't really sound like a feature request to me, so I opened it as a bug in the end.

Since https://github.com/WeblateOrg/weblate/issues/2315, if an Arabic translation contains Tatweel a warning is shown. However, there are cases where a Tatweel is useful. An example is when a preposition that is typically linked to a word is followed by a colon (as in <span dir=rtl>`ب:`</span> vs. <span dir=rtl>`بـ:`</span>), meaning it applies to each item following the colon; it looks awkward without the Tatweel.

I'm willing to open a PR.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Just try to add a Tatweel to any Arabic translation
2. See the warning pop up

### Expected behavior

I expect valid usages like the one I mentioned to not be warned on. One option is to hard-code them, as the prepositions that are linked are only a handful: `ب` , `ك` , `ل`

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Adding exceptions to the check makes sense.
