### ISSUE TITLE
Addidional Quality check - consistency across components

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#6882]
### Describe the problem

In Weblate there is already the very helpful "other occurrences" tab in the translation editor, which helps me to spot if the string that I'm looking at right now has been translated differently in other components.
This allows me to find inconsistent translations between components by chance, but I haven't found a way yet to actively search for inconsistent translations.

![grafik](https://user-images.githubusercontent.com/3872576/143845021-c54a8f39-bfff-4b10-b70a-f83f8d856fb6.png)

### Describe the solution you'd like

Add a qualtiy check that picks all strings "The following strings have the same context and the same source" like in the screenshot above and checks the condition "Has different translations" for all components in a project.

So I would like to see the string `Directory "%s" cannot be created.` from the screenshot above fall under the quality check "Has different translations" for the Chinese language.

This would allow to easily find strings that have been translated differently and improve consistency.

**Comment by nijel** [comment]
There already is a [check covering this](https://docs.weblate.org/en/latest/user/checks.html#inconsistent)

**Comment by luebbe** [comment]
Good to know. I turned on translation propagation for all components of the project in question. Does this also trigger the check for all strings in the background or will the check only run, when a string is freshly translated?
Or, asking the other way round: Will the check find strings that already had inconsistent translations before translation propagation was activated?

**Comment by luebbe** [comment]
OK, it looks like it needed a day and a night of housekeeping. Now "inconsistent" quality checks show up.
