### ISSUE TITLE
REST API Create Component allow_translation_propagation and new_base

### ISSUE THREAD

**Issue by sntxerror** [WeblateOrg/weblate#6883]
Hello!

I'm looking for correct request parameters for component creation request via REST API at `https://{{weblate_domain}}/api/projects/{{PROJECT_NAME}}/components/`

I trying to create "fork" component "feature_1" of base component named "dev".

After creation of "feature_1" component I want to upload only the new and updated units via XLIFF. Later, after complete translation of "feature_1" I will upload units with translations back to "dev" component and remove "feature_1".

My params for creation of `feature_1`  looks like this:

```
{
	"file_format": "xliff",
	"filemask": "feature_1/*.xliff",
	"name": "feature_1",
	"slug": "feature_1",
	"repo": "weblate://{{PROJECT_NAME}}/dev",
	"vcs": "local",
	"template": "",
	"license": "MIT",
	"new_base": "dev/{{LANGUAGE_ID}}.xliff"
	"allow_translation_propagation": "true"
}
```

And I'm trying to understand, is `new_base` value here correct for my scenario?

Also, when I'm trying with `"new_base": "feature_1/{{LANGUAGE_ID}}.xliff"` it's obviously not working, because there is no  uploaded translations in `feature_1` yet.

So, please, give me some advise how to implement "fork" components, with new and updated translations units correctly, and is my scenario (fork base -> upload only new/edited units -> translate -> update base) suitable for this task>

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

**Comment by nijel** [comment]
You can not upload new files when creating a component from an existing one. Use ZIP file upload to create a new component from files. In case you have a real VCS connected to Weblate, you can add the files directly there and then create the component in Weblate.
