### ISSUE TITLE
Template for new translations - File does not exist - despite being present in repo

### ISSUE THREAD

**Issue by keunes** [WeblateOrg/weblate#6891]
### Describe the issue

I'm trying to add a new GitHub-based component for the `translation-files` branch in the repo https://github.com/keunes/AP-website-copy. That repo contains the file https://github.com/keunes/AP-website-copy/blob/translation-files/site-contribute.pot

However, Weblate claims that the file does not exist:
![afbeelding](https://user-images.githubusercontent.com/11229646/144143040-e3495fe7-5828-47f0-a60f-17c4c2b1bca1.png)

I just created the file, and I already had added a component in Weblate based on that repo and branch. Would it be possible that Weblate forked/replicated the branch initially, but didn't update when creating this new component and thus isn't aware of this file? Or is something else going on alltogether?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

weblate.org service

### Additional context

This concerns the AntennaPod testing project: https://hosted.weblate.org/projects/antennapod-website/

**Comment by nijel** [comment]
Are you on the same branch? The file is in the `translation-files` branch...

**Comment by keunes** [comment]
I would swear I was. But for some reason I did get it to work now - maybe a repo update in the meantime. Sorry for the noice!

**Comment by nijel** [comment]
The repo should be updated upon changing the configuration (unless it can not be merged).
