### ISSUE TITLE
Automatic link for label is invalid for searching label when the label name is more than one word

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#6897]
### Describe the issue

Automatic link for label is invalid for searching label when the label name is more than one word

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to a string with a label whose name is more than one word
2. Click on the label
3. The “No string matched your search!” alert appears

### Expected behavior

The link is valid for searching that label in the component

### Screenshots

![image](https://user-images.githubusercontent.com/49396421/144422644-67b8be3f-cb54-4299-a6c6-4374b3812b2f.png)

### How do you run Weblate?

weblate.org service

### Additional context

Example: https://hosted.weblate.org/translate/gnucash/website/en/?checksum=e4ec522774aafadf

The automatic link for the `Source needs review` label is `https://hosted.weblate.org/translate/gnucash/website/en/?q=label:Source%20needs%20review`. But this is invalid for seaching this label and you will only get “No string matched your search!” alert after you clicking it. The link should be `https://hosted.weblate.org/translate/gnucash/website/en/?q=label:"Source%20needs%20review"`.

**Comment by Al-0** [comment]
I will look into this issue.

**Comment by nijel** [comment]
@Al-0 You're welcome!

**Comment by nijel** [comment]
@Al-0 As we're close to the milestone where this is supposed to be addressed, I will take over this issue. Please choose something else to work on :wink:
