### ISSUE TITLE
Jumping to a specific page through pagination component in changes page would clear the date filter

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#6898]
### Describe the issue

Entering number to jump to a specific page through pagination component in changes page would clear the date filter,  including starting date and ending date filter.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to changes page
2. Setting a date filter
3. Click on the pagination component
4. Enter a number than go
5. The date filter is cleared

### Expected behavior

The date filter wouldn't be cleared.

### Screenshots

![weblate_pagination1](https://user-images.githubusercontent.com/49396421/144435120-f0c08ac8-f614-43ab-97b1-bcd4f96897c1.gif)

### How do you run Weblate?

weblate.org service

**Comment by ejgonzalez17** [comment]
Hi, I would like to take this issue to start contributing to your project.

**Comment by nijel** [comment]
@ejgonzalez17 you are welcome

**Comment by Geeyun-JY3** [comment]
This bug seems fixed after https://github.com/WeblateOrg/weblate/commit/08a5c15c20d15a785b1bb67d070d8eece5e61c6b (?) implemented.

**Comment by nijel** [comment]
Indeed it was fixed.
