### ISSUE TITLE
After upgrade from 4.8.1 to 4.9.1 download file from api got 403

### ISSUE THREAD

**Issue by zslucky** [WeblateOrg/weblate#6904]
### Describe the issue

The download API `/download/{project}/{component}/{LANG}/` that return 403 after upgrade.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Just upgrade 4.8.1 to 4.9.1

### How do you run Weblate?

Docker container

**Comment by zslucky** [comment]
I added download file permission to every possible roles, it looks like worked. 

Do we really need force premission check here? Or provide a setting to bypass it?

**Comment by nijel** [comment]
Yes, see #6547 and 114f9c684825d05793944cdf070aaca8b0d9a2cf. But the permission should be included in all built-in roles by default after upgrading.

**Comment by zslucky** [comment]
@nijel , OK thanks.
