### ISSUE TITLE
4.9.1 zen mode will scroll to top after change status to approved

### ISSUE THREAD

**Issue by zslucky** [WeblateOrg/weblate#6906]
### Describe the issue

In the latest version, the zen mode will scroll to top after I change status to approved. 

When I have lot of strings to edit, it doesn't convenience at all.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Just create some strings
2. Change to Zen mode and scroll to bottom.
3. Click and change the string's status to Approved.

### How do you run Weblate?

Docker container

**Comment by comradekingu** [comment]
It just happens if you don't click exactly within the checkbox I think.

**Comment by zslucky** [comment]
I also get a strange thing, which I check the approved and it update status for wrong item...

**Comment by comradekingu** [comment]
@zslucky
I noticed the sequencing is broken when string ordering is changed.
Try sorting by "amount of words" and tab through something in Zen.

**Comment by zslucky** [comment]
@comradekingu looks like incorrect.
![screen-record](https://user-images.githubusercontent.com/15725589/145950701-f8982a72-7739-4dc8-8e8a-5dd06f143ec1.gif)

**Comment by nijel** [comment]
This should be the fix: https://github.com/django-crispy-forms/django-crispy-forms/pull/1199

We will include it in our templates as well, but it really comes  from crispy forms.
