### ISSUE TITLE
Cannot add a translation for a component in JASP project

### ISSUE THREAD

**Issue by boutinb** [WeblateOrg/weblate#6907]
### Describe the issue

In the JASP project, I have the jaspGraph component. When I try to add a language for this component (I have tried Chinese Simplified and French languages), then it just says 'The translation will be updated in the background'. But after some days I still don't see the translations for this component.
What strange is that for other JASP components, I can add a language without problem: it adds it directly without the message it will do that in the background.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to JASP project
2. Select the Languages menu
3. Choose 'Chinese Simplified'
4. Scroll down to the jaspGraph component
5. Click on the + icon to add the Chinese translation
6. This message is displayed: 'The translation will be updated in the background.'
7. The day after (even a week), this translation is still not added.

### Expected behavior

The Chinese Simplified language should be added to the jaspGraph component.

### How do you run Weblate?

weblate.org service

### Weblate versions

I run WebLate via the hosted version: https://hosted.weblate.org/

**Comment by nijel** [comment]
The problem here is that `po/R-JASPgraphs.pot` which is configured as a template for new languages no longer exists in the repository.

The issue on Weblate side is that it doesn't properly report this...

**Comment by nijel** [comment]
I've added alert to indicate this:

![image](https://user-images.githubusercontent.com/212189/144849676-1c19d020-d284-484a-be0a-27f47b283b24.png)

**Comment by boutinb** [comment]
Thanks!
