### ISSUE TITLE
Weblate not mapping xliff "needs-translation" to the “Needs edit” state.

### ISSUE THREAD

**Issue by mzeug** [WeblateOrg/weblate#6913]
### Describe the issue

I have an Angular application i wan't to translate via Weblate.
The initial translation worked without problems but now i'm totaly stucked.
I updated the xliff files using the XLIFF Sync VSCode plugin, comitted the changes
and updated the weblate repository.
But weblate doesn't recognize the changes and marks all elements as translated regardless of the target status.
But according to the docs they should be in the edit state. 
https://docs.weblate.org/en/weblate-4.8.1/formats.html?highlight=%22needs-translation%22#translation-states
Maybe someone can help me with this. What am i missing?

Example trans-unit:

```
      <trans-unit id="32da9f8593fd9618b3f5b4524da68f4c3669f20c" datatype="html">
        <source>Please translate me</source>
        <target state="needs-translation"/>
        <context-group purpose="location">
          <context context-type="sourcefile">somedir/somefile.html</context>
          <context context-type="linenumber">92,100</context>
        </context-group>
      </trans-unit>
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
In your example, the string is not translated (the target tag is blank), in this case the `state` attribute is ignored.
