### ISSUE TITLE
Add/adapt check for translated variables

### ISSUE THREAD

**Issue by hwansing** [WeblateOrg/weblate#6920]
### Describe the problem

I noticed that there's no check detecting, when translator has translated variables like {MINSIZE} or {PERCENT}. (I guess there is a similar check, but it does not catch these cases.)

### Describe the solution you'd like

Would be nice, if a check would point out this translation error.

### Screenshots

![Screenshot_20211208-070627_Firefox](https://user-images.githubusercontent.com/8604846/145159835-122db11f-2139-43e6-9434-3229dce2a378.png)

**Comment by nijel** [comment]
Not sure what is the actual syntax, maybe ECMAScript template literals could be used? See https://docs.weblate.org/en/latest/user/checks.html#ecmascript-template-literals

**Comment by hwansing** [comment]
Hi,

Michal Čihař ***@***.***> wrote (Sun, 12 Dec 2021 13:01:09 -0800):
> Not sure what is the actual syntax, maybe ECMAScript template literals could 
> be used? See https://docs.weblate.org/en/latest/user/checks.html#ecmascript-template-literals

Ok, I see. I was not aware of the existence of those checks. 
Sorry for the noise.

Will try that. 
Thanks

Feel free to close this issue then


Regards
Holger


-- 
Holger Wansing ***@***.***>
PGP-Fingerprint: 496A C6E8 1442 4B34 8508  3529 59F1 87CA 156E B076
