### ISSUE TITLE
Issue with the glossary in weblate version 4.6.1

### ISSUE THREAD

**Issue by gbacruz** [WeblateOrg/weblate#6931]
### Describe the issue

We try to create a new glossary in Weblate version 4.6.1 using the option **Upload translations files**
   and this glossary works for a few days but then, the glossary does not work for the option **Add new term**. Checking the logs we found that Weblate erase the local repository of the PO files from that component/glossary.  Logs for the application returns next message 
   
   `Dec  9 13:52:26 tst-weblate2 weblate[7218]: ERROR Failure while executing task#012Traceback (most recent call last):#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task#012    R = retval = fun(*args, **kwargs)#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__#012    return self.run(*args, **kwargs)#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner#012    reraise(*exc_info)#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-packages/sentry_sdk/_compat.py", line 54, in reraise#012    raise value#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner#012    return f(*args, **kwargs)#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-packages/celery/app/autoretry.py", line 35, in run#012    return task._orig_run(*args, **kwargs)#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-packages/weblate/trans/tasks.py", line 104, in perform_commit#012    component = Component.objects.get(pk=pk)#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method#012    return getattr(self.get_queryset(), name)(*args, **kwargs)#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-`

 ``

Checking the celery-log we found that this issue occurs between these hours and tasks: 

[2021-12-02 12:30:35,447: INFO/MainProcess] Received task: weblate.utils.tasks.heartbeat[d8550798-1ae0-42f9-b829-db6317f00f4d]  
[2021-12-02 12:31:03,504: INFO/Beat] Scheduler: Sending due task cleanup-stale-repos (weblate.trans.tasks.cleanup_stale_repos)
[2021-12-02 12:31:03,509: INFO/Beat] Scheduler: Sending due task cleanup-old-comments (weblate.trans.tasks.cleanup_old_comments)
[2021-12-02 12:31:03,513: INFO/Beat] Scheduler: Sending due task suggestions-cleanup (weblate.trans.tasks.cleanup_suggestions)
[2021-12-02 12:31:03,516: INFO/MainProcess] Received task: weblate.trans.tasks.cleanup_suggestions[36f39df9-00b9-4b30-bf76-11df5eae66d6]  
[2021-12-02 12:31:03,516: INFO/Beat] Scheduler: Sending due task component-alerts (weblate.trans.tasks.component_alerts)
[2021-12-02 12:31:03,520: INFO/Beat] Scheduler: Sending due task font-files-cleanup (weblate.fonts.tasks.cleanup_font_files)
[2021-12-02 12:31:03,523: INFO/Beat] Scheduler: Sending due task cleanup-old-suggestions (weblate.trans.tasks.cleanup_old_suggestions)
[2021-12-02 12:31:03,526: INFO/MainProcess] Received task: weblate.trans.tasks.component_alerts[23232a3b-588f-495e-a0df-03ef7a33d966]  
[2021-12-02 12:31:03,526: INFO/Beat] Scheduler: Sending due task daily-addons (weblate.addons.tasks.daily_addons)
[2021-12-02 12:31:03,530: INFO/Beat] Scheduler: Sending due task screenshot-files-cleanup (weblate.screenshots.tasks.cleanup_screenshot_files)

Following the celery log we try to inspect the code and found that maybe in this method the issue occurs ->

```
@app.task(trail=False)
def cleanup_stale_repos():
    prefix = data_dir("vcs")
    vcs_mask = os.path.join(prefix, "*", "*")

    yesterday = time() - 86400

    for path in glob(vcs_mask):
        if not os.path.isdir(path):
            continue

        # Skip recently modified paths
        if os.path.getmtime(path) > yesterday:
            continue

        # Parse path
        project, component = os.path.split(path[len(prefix) + 1 :])
        
        # Find matching components
        objects = Component.objects.with_repo().filter(
            slug=component, project__slug=project
        )

        # Remove stale dirs
        if not objects.exists():
            remove_tree(path)
```

 
We try recreating the component/Glossary using a version control option but the same issue appears after a few days to create it. could you help us with this, please? 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to 'create new component'
2. Click on Upload translations files
3. Select a translation zip 
4. Fill the forms
5. check the option Upload translations files
6. Use as a glossary
6. Create the component/Glossary

### Expected behavior

Add terms in the glossary

### Screenshots

![image](https://user-images.githubusercontent.com/58188256/145475198-f6a367fc-5290-4c4a-9255-d21e25bf04de.png)

### Exception traceback

```pytb
Dec  9 13:52:26 tst-weblate2 weblate[7218]: ERROR Failure while executing task#012Traceback (most recent call last):#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task#012    R = retval = fun(*args, **kwargs)#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__#012    return self.run(*args, **kwargs)#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner#012    reraise(*exc_info)#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-packages/sentry_sdk/_compat.py", line 54, in reraise#012    raise value#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner#012    return f(*args, **kwargs)#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-packages/celery/app/autoretry.py", line 35, in run#012    return task._orig_run(*args, **kwargs)#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-packages/weblate/trans/tasks.py", line 104, in perform_commit#012    component = Component.objects.get(pk=pk)#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method#012    return getattr(self.get_queryset(), name)(*args, **kwargs)#012  File "/opt/weblate/weblate-3.9.1/lib64/python3.6/site-
```

### How do you run Weblate?

PyPI module

### Weblate versions

4.6.1

### Weblate deploy checks

```shell
not related
```

### Additional context

Thanks

**Comment by nijel** [comment]
Most likely, this was fixed by 45d2e7f378e. Can you please upgrade?
