### ISSUE TITLE
Strange double sentence in the title of a widget

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#6934]
### Describe the issue

On page https://hosted.weblate.org/projects/weblate/application/en/#information ; look zt the title of the first widget displayed in the right column => strings on the left and strings on the right are quite the same ... which do not make sense (according to me).

Have you any idea of what it's meant to tell user with theses strings?

### Steps to reproduce the behavior

Go there https://hosted.weblate.org/projects/weblate/application/en/#information ; look to the title: 
- left and right are displaying quite the same sentence ...

### Screenshots

![image](https://user-images.githubusercontent.com/1452146/145644634-3f7258c1-fa21-4060-bc6f-6e5c8eb13b2a.png)

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 4.10-dev

**Comment by nijel** [comment]
Wrong translation, the strings are:

* "Trends of last 30 days" / https://hosted.weblate.org/translate/weblate/application/fr/?checksum=c70d1c441d369e19
* "and previous 30 days" / https://hosted.weblate.org/translate/weblate/application/fr/?checksum=9a1d8e5f530fd604

You are welcome to fix that ;-)

**Comment by ldmpub** [comment]
Fixed for french.

Thanks 👍
