### ISSUE TITLE
Instead of “Save/Save and stay”, have “Save and continue/Save”

### ISSUE THREAD

**Issue by fitojb** [WeblateOrg/weblate#6936]
### Describe the issue

I think this renaming will make the buttons’ behaviors more straightforward to understand. Also, it’s logical—if a button does two things (i.e., saving and advancing to the next string), they all should be mentioned.

Launchpad.net has this: 
![imatge](https://user-images.githubusercontent.com/554953/145662509-3e07dd40-07ce-4d8d-830e-7e8647075527.png)

A shorter alternative to the “Save and continue” suggested label is “Save and next”.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

weblate.org service

**Comment by baffclan** [comment]
Related to #6860?

**Comment by fitojb** [comment]
Closing as duplicate, thanks
