### ISSUE TITLE
How does automatic labeling work?

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#6966]
### Describe the issue

I have the latest version of weblate with the option to automatically label translated strings. I used automatic translation based on other components, can't see any label. Do you need to turn on the labeling functions somewhere?
#6774
### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1:
![Screenshot_31](https://user-images.githubusercontent.com/39633242/146521330-374fcaa2-1d7e-4820-a32c-8cb31d8eab7f.jpg)
2:
![Screenshot_32](https://user-images.githubusercontent.com/39633242/146521371-d3b6b751-8e9a-4128-b9ea-94f9789d628d.jpg)

### Expected behavior

After using automatic translation, all automatically translated strings have a label.

### How do you run Weblate?

Docker container

### Additional context

<html>
<body>

4.10.1-dev — 856e1a79fe2e852bec8f2b83f71638d478a1af53
--

</body>
</html>

**Comment by tomkolp** [comment]
You have to go to "bulk edit" and manually add a label. Then it is displayed correctly. I just thought the label would be added automatically.
![image](https://user-images.githubusercontent.com/39633242/146528966-249dbd78-525d-4807-b737-0e957f5138f3.png)

**Comment by alexislg2** [comment]
The "Automatically translated" label disappear randomly a few minutes after being assigned to the strings, it is pretty weird.

If i click on it :
![image](https://user-images.githubusercontent.com/7933080/155559329-3653062b-491c-4970-b768-983da15001ad.png)


I get this message : 
`No string matched your search!`

This is pretty weird.

**Comment by nijel** [comment]
Should be fixed by 26a3c85b61
