### ISSUE TITLE
safe-html flags <br> and <a>'s target/rel

### ISSUE THREAD

**Issue by TilmanJimenez** [WeblateOrg/weblate#6976]
### Describe the problem

`<br>` tags aswell as `<a target="_blank" rel="noreferrer">` get marked as unsafe html when using the safe-html flag

### Describe the solution you'd like

Add `<br/>` to the safe list. If possible add `target="_blank"` to the whitelist if `rel="noreferrer"` is present

**Comment by nijel** [comment]
The check should allow whatever is in the source string, there is currently no option to customize that.
