### ISSUE TITLE
Find untranslated strings

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#7008]
### Describe the issue

I can't find untranslated strings easily anymore.

The documentation says finding untranslated strings is possible in multiple languages at once
https://docs.weblate.org/en/latest/user/translating.html?highlight=number%20of%20strings#matrix-view
but it isn't possible to sort status:empty there, and the box to do it moves farther down as more strings are loaded, so not a solution for many strings.

https://hosted.weblate.org/matrix/andors-trail/game-content/?lang=nb_NO&lang=sv

I realize opening a multi-language editor with editable fields for a whole project (or instance) is resource heavy, but I can't figure out how to operate the basic functionality. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Finding missing translations is done by 
1. Clicking "[Project](https://hosted.weblate.org/projects/andors-trail/)" 
2. → [Languages](https://hosted.weblate.org/projects/andors-trail/#languages) 
3. → the number under "untranslated" to get to https://hosted.weblate.org/zen/andors-trail/-/nb_NO/?q=state:%3Ctranslated and then 
4. changing to "status:empty". https://hosted.weblate.org/zen/andors-trail/-/nb_NO/?offset=1&q=state%3Aempty&sort_by=-priority%2Cposition&checksum=

### Expected behavior

Clicking the number under what is correctly named "untranslated" in language view under https://hosted.weblate.org/projects/andors-trail/#languages like it used to be.

### Screenshots

![bilde](https://user-images.githubusercontent.com/13802408/147327525-3da6ba1a-db1b-4385-8497-17de96f2a682.png)

### How do you run Weblate?

weblate.org service

### Additional context

![bilde](https://user-images.githubusercontent.com/13802408/147327630-4f3f4a19-94a6-4cad-815b-8ce79cc1f6bf.png)

**Comment by nijel** [comment]
> I can't find untranslated strings easily anymore.

Nothing has changed in this recently, what is the difference?

>The documentation says finding untranslated strings is possible in multiple languages at once
https://docs.weblate.org/en/latest/user/translating.html?highlight=number%20of%20strings#matrix-view
but it isn't possible to sort status:empty there, and the box to do it moves farther down as more strings are loaded, so not a solution for many strings.

There is currently no filtering in the matrix mode.

> Clicking the number under what is correctly named "untranslated" in language view under https://hosted.weblate.org/projects/andors-trail/#languages like it used to be.

Are you referring to https://github.com/WeblateOrg/weblate/issues/5896?

**Comment by comradekingu** [comment]
@nijel 
Whatever my solutions or thoughts are, that is my problem.
Finding correct labels for what I think is broken functionality doesn't help me, so I won't.
I haven't been able to find untranslated strings easily on anything newer than where it changed.
Doing it per component is available through clicking into the categories.
Doing it per project needs the above workaround?

Whatever the case for having fewer categories in the progress-bar,  I thought maybe whoever
thought of it had a plan for how to find untranslated strings.
Maybe I am not finding it.

**Comment by nijel** [comment]
I think the root cause of the confusion here is the word "untranslated". Some people understand it as "string which has no translation" while others as "strings which translation is not completed".

So, the first thing to address is this, and I've tried that in https://github.com/WeblateOrg/weblate/pull/7016. We can then focus on adding easy filter for the blank strings.

**Comment by comradekingu** [comment]
@nijel "Untranslated" means _not translated_ though, and translations will too.

**Comment by nijel** [comment]
@comradekingu I understand perfectly what it means to you, but apparently this it not how everybody understands that...

**Comment by comradekingu** [comment]
My understanding is beside the point,
https://www.merriam-webster.com/dictionary/untranslated
https://www.dictionary.com/browse/untranslated
https://www.collinsdictionary.com/dictionary/english/untranslated
https://en.wikipedia.org/wiki/Untranslated_region
https://www.lexico.com/en/definition/untranslated
