### ISSUE TITLE
keywords auto translate everywhere

### ISSUE THREAD

**Issue by algazarra** [WeblateOrg/weblate#701]
it would be cool if weblate auto translated keywords in all strings automatically. For example, one of our app's features is "price hit". this is repeated in multiple strings. When translating in one, it would be cool to translate in all of them, for coherence sake.

I'm reviewing some translations submitted by others and I have to search manually to see how they translated "price hit" before.
##

**Comment by emmapeel2** [comment]
Yes, I miss this feature always along with the 'Inconsistent' check.
For example, when it is inconsistent, you should be asked:

Change it on all the other occurences as well?

**Comment by nijel** [comment]
That's on the bottom of the page (but that's offtopic here):

![debian_handbook_00b_foreword_-_indonesian_ _hosted_weblate_-_2017-02-13_13 39 38](https://cloud.githubusercontent.com/assets/212189/22883743/e49e566e-f1f1-11e6-904d-e3efbf3943a6.png)

**Comment by emmapeel2** [comment]
I have used the "Other translations" tab to get to the 'still untranslated' strings, but you need to go one by one to change them, you cannot decide the correct translation on all the components with one click and maybe a confirm (or at least I don't see the option)

**Comment by nijel** [comment]
You mean replace all in one component? This can be done by automatic translation, but indeed it's not easy to find. Anyway, we're really offtopic here.

**Comment by nijel** [comment]
Depending on the desired approach, there will be several options:

* Use translation propagation in case the strings are exactly same
* Use machinery to get suggestions from translation memory
* Use glossary and upcoming machinery and checks integration (https://github.com/WeblateOrg/weblate/issues/4905, https://github.com/WeblateOrg/weblate/issues/1297)
