### ISSUE TITLE
HTML Translation: Line Offsetting.

### ISSUE THREAD

**Issue by graebertshiva** [WeblateOrg/weblate#7024]
### Describe the issue

Hi @nijel 

I have seen if we add some new Lines in between in HTML Base Language i.e. English, then the lines are offsetting in Other corresponding Language Files like German. 

is there anything i am missed to add some check like that so that i will be able to resolve this line offsetting. or do i need to add anything in my files like id?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

Docker container

**Comment by graebertshiva** [comment]
![Screenshot from 2022-01-08 13-10-47](https://user-images.githubusercontent.com/54701590/148636272-ebe2de53-27f4-4dca-ac45-23b97fa71cea.png)

Line Offsetting: line alignment.

once we add some new Lines in existing html file in base file i.e English, in between lines. and then we add them back to weblate for translation again then the line alignment is different and existing translated file in German is not able to recognise the new text. it's showing new text lines corresponding to old line number weather it's already translated.

**Comment by nijel** [comment]
This is how currently the document translation is implemented. It is definitely not the best state as it exposes internals which are not really needed.
