### ISSUE TITLE
The “hyphen” symbol in visual keyboard

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#7060]
### Describe the problem

https://github.com/WeblateOrg/weblate/blob/dd3b49849926087ff35d0754f27b45588e7be0ce/weblate/trans/specialchars.py#L291
The “hyphen” symbol in visual keyboard is actually called “Hyphen-Minus” in Unicode (`-`, U+002D). 
There is another symbol actually called “hyphen”  in Unicode(`‐`, U+2010). 
People may use the “Hyphen-Minus” symbol more often since it can be directly input through the <kbd>-</kbd> key in most physical keyboard layout (and this is a historical issue related to typewriter).
It may confuse users.

### Describe the solution you'd like

Explicitly call it “Hyphen-Minus”. Or explain it in document.

Actually I am not sure if it is really necessary since it may be a little split hairs. People may not care about their difference.

**Comment by nijel** [comment]
I think it should really be U+2010 (see #406).
