### ISSUE TITLE
Plural form for monolingual po is lost in translation

### ISSUE THREAD

**Issue by xperseguers** [WeblateOrg/weblate#7061]
### Describe the issue

I created a source .po file like that:

```
# Group of attributes for member's details
msgid "Person.Group.Sponsors"
msgid_plural ""
msgstr[0] "Sponsor"
msgstr[1] "Sponsors"
```

This is thus a monolingual po file. It shows properly in Frontend:
![147947082-f2489692-da43-4af5-ac2a-bfa632c8b652](https://user-images.githubusercontent.com/646805/148078751-5e0f4836-1b1c-4b1b-aea4-27e702a08000.png)

However after translating those plurals, and committing to file system, the translated po files totally miss the plural definitions and store this instead:

```
msgid "Person.Group.Sponsors"
msgstr "Pate"
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Create a component whose file format is "gettext PO file (monolingual)"
2. Import/create the sample multilingual po file
3. Translate to another language (in the example German)
4. Commit
5. Check file system

### Expected behavior

The localized po file is expected to store this instead:

```
msgid "Person.Group.Sponsors"
msgid_plural ""
msgstr[0] "Pate"
msgstr[1] "Paten"
```

(for a 2-plural form language and naturally with more forms in case of Croatian or other language dealing with more than 2 forms for plural).

### How do you run Weblate?

PyPI module

### Weblate versions

 * Weblate: 4.10.1
 * Django: 4.0
 * siphashc: 2.1
 * translate-toolkit: 3.5.1
 * lxml: 4.7.1
 * Pillow: 8.4.0
 * bleach: 4.1.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.1.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.13.0
 * oauthlib: 3.1.1
 * django-compressor: 3.1
 * djangorestframework: 3.13.1
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.4.2
 * setuptools: 44.0.0
 * jellyfish: 0.8.9
 * openpyxl: 3.0.9
 * celery: 5.2.3
 * kombu: 5.2.3
 * translation-finder: 2.10
 * weblate-language-data: 2021.7
 * html2text: 2020.1.16
 * pycairo: 1.20.1
 * pygobject: 3.42.0
 * diff-match-patch: 20200713
 * requests: 2.26.0
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.5.1
 * Cython: 0.29.26
 * misaka: 2.1.1
 * GitPython: 3.1.24
 * borgbackup: 1.1.17
 * pyparsing: 3.0.6
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * Python: 3.8.10
 * Git: 2.25.1
 * psycopg2: 2.9.3
 * ruamel.yaml: 0.17.19
 * Redis server: 5.0.7
 * PostgreSQL server: 12.9
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: 10.0.1.10
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 5.4.0-91-generic (x86_64)

### Weblate deploy checks

```shell
n/a
```

### Additional context

First discussed here: https://github.com/WeblateOrg/weblate/discussions/7053

**Comment by nijel** [comment]
I can reproduce this in case the string existed before in the translated file as singular, can you please confirm that?

Before Weblate doing the changes, did the file contain following?

```
msgid "Person.Group.Sponsors"
msgstr ""
```

**Comment by xperseguers** [comment]
> I can reproduce this in case the string existed before in the translated file as singular, can you please confirm that?
> 
> Before Weblate doing the changes, did the file contain following?
> 
> ```
> msgid "Person.Group.Sponsors"
> msgstr ""
> ```

Yes, that's quite possible because some of those labels have indeed switched from singular to plural form.

Manually applied your commit #d71663c and checked, that works!

Thanks for having investigated and fixed it.
