### ISSUE TITLE
Project level backup and restore

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#7066]
### Describe the problem

It would be useful to support backup/restore of individual projects. Use cases:

* Individual backups from shared instance, such as Hosted Weblate
* Migration to different Weblate instance

### Describe the solution you'd like

Backup would generate a ZIP file with all project configuration and metadata. The actual format might be JSON as that's widely used, and we use it already for other exports.

Content:

* [x] Export metadata (version, timestamp, instance, ...)
* [x] Project configuration
* [x] Project labels
* [x] Translation memory as JSON

For each component:

* [x] Component configuration
* [x] Repository content as ZIP
* [x] All translations configuration
* [x] Unit metadata
  - contains flags, explanations, ignored checks, comments, suggestions, labels
* [x] Screenshots

The objects will be referenced by current primary ID inside the backup.

Restore will be a two phase with preview of content to confirm importing.

1. Create project
2. Import labels, translation memory
3. Unpack repository content
4. Create component without triggering sync
5. Create translations
6. Create units
7. Create screenshots
8. Trigger sync in the background

### Describe alternatives you've considered

Full server backup does not serve well for some use cases.

**Comment by orangesunny** [comment]
This is an exciting feature for many Weblate users, but @rhofer and @KadAnna are very much expecting it. I just want to let you know it should be coming in 4.13. You can also comment here if you would feel the scope’s missing anything.
