### ISSUE TITLE
Make button to add translations more prominent 

### ISSUE THREAD

**Issue by sonnyp** [WeblateOrg/weblate#7079]
### Describe the problem

Users are asking how to add translations, which seems to indicate the feature is not prominent enough

See https://github.com/sonnyp/Junction/issues/54

I think it's specially difficult to find coming from the engage page.

Here is the user path from a translator/contributor perspective

1. https://github.com/sonnyp/Commit/#translation
2. https://hosted.weblate.org/engage/commit/
3. Click "Translate"
4. Wonder what a component is and click on it
5. https://hosted.weblate.org/projects/commit/commit/
6. Scroll down to find "Start new translation"

### Describe the solution you'd like

Make the button "Start new translation" more prominent. Maybe move it from below the table to above the table?

Example https://hosted.weblate.org/projects/junction/junction/

---

Less important and tangent to the problem, if there is a single component – the user could be redirected to it directly instead of to the component list.

### Additional context

I had a great conversation with @orangesunny :pray:  and he invited me to report issues and contribute – so here I am.

If you like the suggestion to move the button above the list - I am happy to try and send a PR.

Cheers!

**Comment by nijel** [comment]
The desired state is that user has configured languages and those are offered for adding directly in the list:

![image](https://user-images.githubusercontent.com/212189/148643805-bf16d80c-df6c-48a2-b973-5610a0b8d7b4.png)

The question is how to make this available to new users easily.

**Comment by sonnyp** [comment]
That only works if

1. the user is registered
2. the user has configured languages.

It's not friendly to newcomers IMHO.

BTW it is also confusing to experienced users which aren't signed in see https://github.com/sonnyp/Commit/issues/51

**Comment by nijel** [comment]
I'm aware of that, I've mentioned it already in the previous post:

> The question is how to make this available to new users easily.

**Comment by nijel** [comment]
I've added autoconfiguration of user languages based the `Accept-Language` HTTP header in e148d58e250cf3b9c1e9b421cf9dc852c434be3d. That should work quite well for most users.
