### ISSUE TITLE
Avoid scrolling when adding screenshots

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#7085]
### Describe the problem

When adding/editing screenshots for the translators, the OCR doesn't have a chance to find all strings that should be associated with this screenshot. The most obvious ones are hint text for buttons which have only an icon and no caption. Sometimes also strings that contain accelerator keys like "Save &all" are not recognized properly, because they have an underscore "Save _all" under the letter (at least on Windows). 
This means that I have to add all relevant strings from memory and this also means that I probably will miss a lot.

**Edit**:  The actual issue is described in https://github.com/WeblateOrg/weblate/issues/7085#issuecomment-1009950253

### Describe the solution you'd like

At least the .po format contains a very valuable information, the location of the string. If the search function in the screenshot dialogue would allow me to search for the location of a string (either optional or always), it would be much easier to find all strings associated to a certain form.

### Screenshots

![grafik](https://user-images.githubusercontent.com/3872576/148743317-fd3eedc5-5fa0-4800-9619-406a8d5153c6.png)
The form is called "ModeTemplates.dfm". I know that one of the button hints contains the string "create" so I can add it by searching for "Create". It would be nice to be able to add all strings for this form by simply searching for "ModeTemplates.dfm"

**Comment by nijel** [comment]
The search is same as elsewhere, so use `location:search-term`. See https://docs.weblate.org/en/latest/user/search.html

**Comment by luebbe** [comment]
Thanks! That's cool. The idea didn't occur to me...

**Comment by luebbe** [comment]
That's true. Only while adding strings, the top list grows and pushes the bottom list and the items on which I may want to click next off screen.

**Comment by meel-hd** [comment]
@nijel  this issue is related to OCR. Where is the problem with scrolling? Wouldn't it be better to open a new issue and close this one as it seems resolved?

**Comment by nijel** [comment]
I think the remaining issue to address here is:

> while adding strings, the top list grows and pushes the bottom list and the items on which I may want to click next off screen.

So while adding, the viewport should not move because of strings added to the top list.
