### ISSUE TITLE
Turn off checks for pseudolocale-created translations

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#7091]
### Describe the problem

Some checks – like bad sentence ending – is useless when using pseudolocale add-on.

### Describe the solution you'd like

1. Turn these checks off for languages created by Pseudolocale add-on.

or

2. Make a setting to dismiss checks for a language.

### Screenshots

![checks](https://user-images.githubusercontent.com/23450011/148958800-3e11aca4-be6a-4a18-b965-deae4cf3da86.jpg)

### Additional context

I am not sure what is the right way to deal with the problem. Some users do use Pseudolocale for setting up a different locale of the same language, e.g. en –> en_UK. In this case, checks are useful.

Maybe turn off some checks only if the suffix is used and others – like a capital letter at the beginning – when the prefix is used.

**Comment by nijel** [comment]
I don't think it's a good idea to do that automatically. How to recognize pseudolocale? By a language code? By using in the pseudolocale generation add-on? Something like that should be a user decision. But right now, there is no way to configure checks per language in Weblate...

**Comment by KadAnna** [comment]
Hello, the problem arised when I used pseudolocale add-on and pseudolocale language provided for this purpose, I therefore expect not having these problems. Thanks!

**Comment by nijel** [comment]
The thing I was afraid of was misused for initial translation, but that should be properly handled by https://github.com/WeblateOrg/weblate/issues/5692 in 4.11.

Once this use case is gone, it makes sense for the pseudolocale add-on to flag the translation to run no checks.

Technically, this requires:

* implement a flag to disable all checks (we currently only have per check flags)
* add install/uninstall/configure hook to add-ons
* adjust pseudolocale add-on to change translation flags on install/uninstall/configure
