### ISSUE TITLE
The current translation does not equals with history last

### ISSUE THREAD

**Issue by wirthandras** [WeblateOrg/weblate#7098]
### Describe the issue

We encountered an issue, the actual text is an older text, it is not equals with the last element of history.

The manual export and git push produce the history last element.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Expected behavior

The actual translation and history last element are equal.

### Screenshots

![image](https://user-images.githubusercontent.com/12913003/149278093-1825b2df-627b-4ebf-8d0a-5c2669caa216.png)

### How do you run Weblate?

Docker container

### Weblate versions

4.8.1

### Additional context

The source text changed from 
Submit party order (<x id="INTERPOLATION" equiv-text="({{ submitTotalPrice | currency }"/>)
To
Submit party order (<x id="INTERPOLATION" equiv-text="({{ submitTotalPrice | localizedCurrency }"/>)

**Comment by nijel** [comment]
Maybe the translation was changed in git? Weblate currently does not track such changes, see https://github.com/WeblateOrg/weblate/issues/5726

**Comment by wirthandras** [comment]
@nijel thanks you are right, I exported to weblate to early (I should have to wait for new translation integration).
I close the issue
