### ISSUE TITLE
`dir=auto` for comments

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#7109]
### Describe the issue

When adding a comment in Hebrew (or Arabic, Farsi, Kurdish, etc.) for a string the comment is aligned according to LTR regardless of the script.

The comment editing dialog showing the text aligned to the left while the visual character is aligned right.
If the entire comment starts with an RTL script (it's a problem when I'm mentioning someone) all the text is aligned right.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to some term for translation
2. Switch to the comment section
3. Write the following comments (write the first one, then delete and write the second one):
'@nijel שלום לך'
'שלום לכולם'

### Expected behavior

Text should be aligned right when most of the text or at least the beginning is in RTL script.

### Screenshots

<img width="1035" alt="Screen Shot 2022-01-17 at 13 39 50" src="https://user-images.githubusercontent.com/406826/149763341-20c99482-d808-4844-b08d-54a5082e9e09.png">

### Exception traceback

```pytb
None
```

### How do you run Weblate?

weblate.org service

### Additional context

I truly like the way Weblate supports RTL languages, we should keep the momentum :)

**Comment by nijel** [comment]
There used to be `dir="auto"` but it was removed in 29b809138d03f06a710018e19246d436032ebb65 (probably unintentionally). However for me it makes no difference - it still renders as LTR when the text starts with LTR text (user mention). The only way to make it RTL is using `dir="rtl"`.

**Comment by yarons** [comment]
But it'll break English (LTR) comments in RTL interface :(

**Comment by nijel** [comment]
We can do this based on the language

**Comment by yarons** [comment]
Of the comments itself? That sounds good.

**Comment by nijel** [comment]
Of the language being commented, that usually matches the language of the comment.

**Comment by jermanuts** [comment]
Ideally we would something like word processors where you can force a text direction.

The current implementation messes up when comments are LTR (English) and the language the component is translated into is RTL.

**Comment by nijel** [comment]
@jermanuts I think this belongs to a separate issue. Please include examples that do not work well with the current approach, and we can look for another solution.
