### ISSUE TITLE
Missing newline on Android strings when not using \n

### ISSUE THREAD

**Issue by dllud** [WeblateOrg/weblate#711]
On an Android strings' file it is possible to [use a real EOL instead of an explicit `\n`](http://stackoverflow.com/a/17288710). This makes the strings' file easier to read.

However, on Weblate, a string separated just by real EOLs will appear as a single long line.
![weblate-long-line](https://cloud.githubusercontent.com/assets/1716156/7127225/df389466-e238-11e4-8fc2-537104f9527a.png)

Is this a translation-toolkit related issue? If so, should I open an issue there too?

Note: with a [`\n`at the end of every line](https://github.com/drpout/boilr/commit/62edfb8c515b97bf6f42ca4cf8153057c0085e94) things look as expected.
![weblate-separated-lines](https://cloud.githubusercontent.com/assets/1716156/7127266/8a553e30-e239-11e4-98cb-0afa8aa297ea.png)
##

**Comment by nijel** [comment]
Yes, it's translate-toolkit issue, Weblate does no mangling on the strings.

**Comment by nijel** [comment]
PS: There are quite some PRs open on translate-toolkit, so there is change this is already somewhere there, but they are currently really slow in integrating fixes...

**Comment by dllud** [comment]
I just gave a look to translate-toolkit issue tracker and could find no PR implementing this. Thus I opened an issue there: translate/translate#3262

**Comment by nijel** [comment]
This should be fixed since https://github.com/translate/translate/pull/3442.

**Comment by nijel** [comment]
It would be great if you could look at https://github.com/WeblateOrg/weblate/issues/1418#issuecomment-288031554 as there seems to be problem with current handling of newlines...
