### ISSUE TITLE
New user via invite gets a "page not found" error

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#7113]
### Describe the issue

1. Add a new user via the https://(weblate)/manage/users/ page and send the invite via mail
2. Add the user to one "(project)@translate" group
3. The user clicks on the link and receives a "Page not found" error. 

![grafik](https://user-images.githubusercontent.com/3872576/149774258-4a567aac-1449-4e1a-a885-07c63a08d5eb.png)

All our projects are private by default. Users can only see the projects to which they have been added.
The new user in question is already a member of the "Users", "Viewers" and "(project)@translate"
He can't log in, because he obviously hasn't been able to set a password yet.

The only ticket that sounds related is https://github.com/WeblateOrg/weblate/issues/3666

The docs: https://docs.weblate.org/en/latest/admin/access.html?highlight=invite%20user#new-user-invitation
mention the "forgot password" link. When is this link shown?

To me it looks a bit random, because the link is not there initially and only after 3-10 klicks on any of the "Login" links it shows up.

![grafik](https://user-images.githubusercontent.com/3872576/149775735-89ddd25a-df5f-4897-a5ee-559c4836ef51.png)
Initial view

![grafik](https://user-images.githubusercontent.com/3872576/149775819-590bf375-72af-4327-b249-fdc0624b4e8f.png)
After a random number of clicks on any of the two "Anmelden" links at the top left/right

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Docker container

### Weblate versions

Weblate 4.10.1 running in Docker.

**Comment by nijel** [comment]
This looks like you do not have enabled email authentication backend which is needed for password reset and invitations.

**Comment by luebbe** [comment]
Thanks, that was it. WEBLATE_NO_EMAIL_AUTH was set by our admin during the initial configuration, because according to his words: "The docs didn't explain that it makes sense to enable it".
If the security policy is to disable everything that isn't absolulely necessary, the information provided at: https://docs.weblate.org/en/latest/admin/install/docker.html?highlight=email%20authentication#other-authentication-settings is a bit sparse ;)
