### ISSUE TITLE
Weblate could not push changes to the upstream repository

### ISSUE THREAD

**Issue by ManeraKai** [WeblateOrg/weblate#7129]
### Describe the issue

It was working fine yesterday. It's now unable to push to my [Repo](https://github.com/ManeraKai/simplytranslate_mobile). I have authorization setup and everything working fine. The only think I may did in that time was resetting it in the Maintenance tab.

 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

I don't know how

### Expected behavior

To just push normally as yesterday.

### Screenshots

![image](https://user-images.githubusercontent.com/40805353/150337679-0a83b36e-3f08-4e29-96af-f3eb7c8b8f79.png)

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
The push to https without credentials could never work, so most likely some configuration was changed. Follow the hints in the alert to fix that.

**Comment by ManeraKai** [comment]
Thanks! For anyone who is still struggling:
Generate A [Personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token), give it the **repos** permission. Copy the token to use it in the next step.
![image](https://user-images.githubusercontent.com/40805353/150352379-9baf28f2-8014-4328-86c2-1f76575891c5.png)

In the Settings for a component in Weblate, use this **Repository push URL**:
`https://username:tokenxxxxxxxxxx@github.com/username/repo.git`

Ex: `https://ManeraKai:tokenxxxxxxxxxx@github.com/ManeraKai/simplytranslate_mobile.git`
![image](https://user-images.githubusercontent.com/40805353/150352639-dbc19403-0b4a-4694-b4c1-dac89c7413be.png)

Hopefully it works for you.

**Comment by ManeraKai** [comment]
Problem with this now is doesn't make a  pull request, it just pushes them directly to the Repo.

**Comment by nijel** [comment]
That is expected with "Git" as version control, you need "GitHub" for that. See https://docs.weblate.org/en/latest/admin/continuous.html#pushing-changes-from-weblate

**Comment by ManeraKai** [comment]
So there is no need for credentials if I selected `GitHub` in Vesion Control. Yeah, I'm so smart to not notice that!
