### ISSUE TITLE
weblate compilemessages CommandError: Can't find msgfmt. Make sure you have GNU gettext tools 0.15 or newer installed.

### ISSUE THREAD

**Issue by pgy866** [WeblateOrg/weblate#7136]
### Describe the issue

Run command `weblate compilemessages`
`CommandError: Can't find msgfmt. Make sure you have GNU gettext tools 0.15 or newer installed.`

In Debian/deepin/Ubuntu:
`sudo apt-get install gettext`

应该加入依赖列表吗？
Should I add to the dependency list?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Screenshots

![截图_选择区域_20220122095652](https://user-images.githubusercontent.com/28694676/150620402-ed61707f-f750-475f-a834-9f600708a6e8.png)

### How do you run Weblate?

Git checkout

**Comment by nijel** [comment]
Running `compilemessages` on installed system is typically not needed (the files are compiled when installed using pip). I will adjust the instructions to not mention this step at all.
