### ISSUE TITLE
Change Github PR title format

### ISSUE THREAD

**Issue by jooola** [WeblateOrg/weblate#7141]
### Describe the issue

Our project is following the conventional commit format and we would like to have the PR title opened by weblate to follow this convention. I searched how I could change this but it seems this is not possible when using hosted.weblate.org ?

We edited the message configuration in our project configuration panel on hosted.weblate.org, but didn't found any field helping in that direction.

I found that this settings seem only available the admin ? https://docs.weblate.org/en/latest/admin/config.html?highlight=pull%20request#default-pull-message

Our project:
- https://github.com/LibreTime/libretime/issues/1530 
- https://hosted.weblate.org/projects/libretime/
- https://github.com/LibreTime/libretime/pull/1531#event-5930737213

Our CI is only checking for the PR title to follow the conventional commit format, and this is making it fail.

I am unsure what are the good practices: Should we rebase or squash the commits coming from Weblate ?

How can we make this work ?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

See links to our project for examples.

### Expected behavior

We expect the PR title to follow our commit message format.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
The pull request message could be configurable at component level, same as the commit message is.

**Comment by jooola** [comment]
Thank you @nijel !
