### ISSUE TITLE
Remove the redundant leading space in username hyperlink text beside the avatar

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#7157]
### Describe the problem

There is a redudant leading space in username hyperlink text beside the avatar.

### Describe the solution you'd like

Remove this space.

### Screenshots

![weblate avatar redundant space](https://user-images.githubusercontent.com/49396421/151102864-dedf875a-6c2f-4c5b-b86f-4adf85fd27ff.gif)

![image](https://user-images.githubusercontent.com/49396421/150990748-bd488779-1d00-4351-bb50-1a2d08db1702.png)

**Comment by nijel** [comment]
The space there is intentional:

![obrazek](https://user-images.githubusercontent.com/212189/151174153-4c464f65-b75f-4e23-b8bb-3630e1d7369f.png)

**Comment by Geeyun-JY3** [comment]
I don't think using space for alignment is a good idea. The Chromium-based browser I am using provide a “copy link text” option in hyperlink context menu.
![image](https://user-images.githubusercontent.com/49396421/151178410-7a2305d4-ac1e-4cb3-a209-49ad8f51c009.png)
Therefore, I would get the text with a redundant leading space and it causes inconvenience. That’s why I open this issue. Sincerely hope that there could be a better workaround.

**Comment by nijel** [comment]
It can be probably solved by css and extra classes, but using space to separate image (user avatar) and text is the most obvious way and makes the code more readable and works out of the box for RTL. I won't refuse patches to address this, but I don't consider this to be a issue.
