### ISSUE TITLE
Automatically add word/translation to other components with same languages

### ISSUE THREAD

**Issue by GabriFila** [WeblateOrg/weblate#7158]
### Describe the issue

Hello, I have a question regarding managing of multiple translation targets

I need to provide translations for 3 frontends:
- iOS
- Android
- web

For each of them I need 3 languages (it,fr,en) the base one is English

Looking around the documentation and GH issues, I found the _translation propagation_ feature.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Expected behavior

I noticed that translations get only propagated across components when a key already exists in the same language of another component. I would like that when I add a new key to a language in a component, the key would automatically transfers to other components.

Is it possible? How?

Thank you very much

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
The propagation works only while translating. For other cases you can use automatic translation. Either manually or via add-on.

**Comment by GabriFila** [comment]
Thank you for the fast response, can you please tell me how to set the behaviour I described above using `automatic translation add-on` or point somewhere to find out how?

Thank you again

**Comment by nijel** [comment]
Enable the add-on to translate untranslated strings and taking strings from other components.

**Comment by GabriFila** [comment]
I have the following configuration (image) set in each component, but when I add a translastion from the UI on english language on one component I do not see the updated data on english languages of other components.
Am i missing something?

Thank you

![weblateAddonCOnfig](https://user-images.githubusercontent.com/32385294/151204628-938d73e6-133d-4c26-84af-2d5fbdd07e8f.png)

**Comment by nijel** [comment]
I think it does not happen immediately, it runs nightly

**Comment by GabriFila** [comment]
Hello, I waited the night but nothing has happened, I will check maybe later (24 hours from the update).

But also the docs say the the add-on is triggered:
> - When new strings appear in a component.
> - Once in a month for every component, this can be configured using BACKGROUND_TASKS.

So I guess it should be triggered right after a new string is added. is this a bug? How can i solve it?

Thank you

**Comment by nijel** [comment]
Yes, it's a bug, I've just fixed it in 30e2477.

**Comment by GabriFila** [comment]
Thank you!
How can I get the new version? Do I need to wait for the official release or I can specify to get a commit-specific image? In the case of the former, when will it be released?

**Comment by nijel** [comment]
If you installed using pip, you can install from Git right now. The Docker images are built nightly.
