### ISSUE TITLE
Github.com PR creation fails due to missing API token

### ISSUE THREAD

**Issue by aparcar** [WeblateOrg/weblate#7161]
### Describe the issue

<img width="768" alt="image" src="https://user-images.githubusercontent.com/16000931/151323315-dc50ad48-83fb-442a-bca4-30d09aaf673c.png">

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to Manage > Repository Maintenance
2. Click `push`
3. See error message

### Expected behavior

I'd except the commits to be pushed to GitHub.

### Screenshots

<img width="768" alt="image" src="https://user-images.githubusercontent.com/16000931/151323567-ac52f393-9770-44e9-971c-420090a30d73.png">

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
I've tightened the configuration yesterday, but apparently too much. Fixed.
