### ISSUE TITLE
Redirection of the invalid permalink

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#7170]
### Describe the problem

If I don’t get it wrong, the permalink of a string (de facto the checksum I guess?) would be changed after the source string is changed. (I only test in Weblate project on Hosted Weblate. Or it is de facto considered as a new string by Weblate? And it seems that this is a `.po` file specific bug. I have opened a discussion for this: #7168.) In addition, the permalink would be invalid if the string is removed in source code.

Currently, after the string is changed or removed in source code, the permalink would be redirected to the first string of corresponding component.
This may lead the users to mistakenly believe that the permalink is corresponding to the shown string which is the first string of corresponding component in fact.

### Describe the solution you'd like

Redirect to translation page (e.g. https://hosted.weblate.org/projects/weblate/application/zh_Hans/) instead of the first string of corresponding component, as well as showing a notice bar telling user that the string is changed (for example, read: `Error in parameter: Invalid checksum specified!`?) or removed in source code.

**Comment by nijel** [comment]
For bilingual translations, the checksum is based on source string and context (if present), for monolingual by the key. This matches how the framework then identifies the string.

**Comment by Geeyun-JY3** [comment]
BTW, is it possible to redirect the invalid permalink to the corresponding string translate page for the changed strings in bilingual translation file?
