### ISSUE TITLE
weblate sees messages using msgctxt as ambiguous

### ISSUE THREAD

**Issue by JohnRDOrazio** [WeblateOrg/weblate#7177]
### Describe the problem

When using gettext, we have the possibility of distinguishing one same word or phrase to be translated by context, so that it can be translated differently according to the context it's in. So the source word or phrase might be the same, but the translation will be different:

https://www.gnu.org/software/gettext/manual/html_node/Contexts.html

Even though PHP doesn't have native support for `pgettext`, I found that it is easy enough to implement with this function:

```php
if (!function_exists('pgettext')) {
    function pgettext($context, $msgid) {
       $contextString = "{$context}\004{$msgid}";
       $translation = dcgettext('litcal', $contextString, LC_MESSAGES);
       if ($translation == $contextString)  return $msgid;
       else  return $translation;
    }
}
```

Tested and working, when I generate the pot file like this:

```bash
xgettext --from-code=UTF-8 --add-comments='translators:' --keyword="pgettext:1c,2"  ...
```

Weblate is picking up on `msgctxt` because I can see **CONTEXT** both in the string information box, and in the translation box (see screenshot below).

However, weblate is complaining that the translation is **_inconsistent_**, I'm guessing simply because there are different translations of the same source string? It's like weblate is ignoring the Context, which should distinguish between multiple source strings with the same `msgid`.

### Describe the solution you'd like

Weblate should take `msgctxt` into account when doing consistency checks.

### Screenshots

For example, I have a project where I am translating the single possessive preposition "of" into various other languages, since it is needed by the program to build a phrase. However in English there will not always be a definite article that follows, whereas in other languages there will be, and the translation should therefore include the definite article which, in other languages, will most often have gender and number. So we have to distinguish between at least four contexts:

* masculine singular
* masculine plural
* feminine singular
* feminine plural

![screenshot weblate msgctxt](https://user-images.githubusercontent.com/231298/151666797-15063c05-e572-472f-96c6-dd6634439a10.jpg)

From the above screenshot, we can see that weblate is trying to get me to apply the translation from one context to another context, simply because the `msgid` is the same. It does not take into account `msgctxt` when raising inconsistency flags and generating suggested translations.

### Additional context

Weblate: 4.10.1

**Comment by JohnRDOrazio** [comment]
When looking at the **Other occurrences** tab, I see that Weblate does distinguish between the situation where the source and the context are the same, or the other situation where the source is the same but the context is different. If it knows the underlying difference, it should take that into account before raising an inconsistency flag:
![screenshot weblate msgctxt 2](https://user-images.githubusercontent.com/231298/151667467-ac438ef6-b4df-44a7-9d45-5c92e8a4aa2a.jpg)

**Comment by nijel** [comment]
The check is raised on the suggestion, what really doesn't make sense. It should be skipped there...
