### ISSUE TITLE
Group creation and editing from the weblate interface.

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#7182]
### Describe the problem

It is not possible to create a group and edit it from the level of the weblate interface.

### Describe the solution you'd like

Possibility to create a group and edit it from the weblate interface.

**Comment by nijel** [comment]
Project level groups are already manageable from Weblate in current git, it will be included in the 4.11 release.

**Comment by nijel** [comment]
Rest is covered by https://github.com/WeblateOrg/weblate/issues/2363, https://github.com/WeblateOrg/weblate/issues/2127, https://github.com/WeblateOrg/weblate/issues/2126, https://github.com/WeblateOrg/weblate/issues/2493

**Comment by tomkolp** [comment]
I have version 4.11dev https://github.com/WeblateOrg/weblate/commits/25a4f11d6dd13ee2bbf6d59f20a94d9b68b62daf , I haven't found creating or editing a group anywhere.  There is only the "teams" tab.  Are there any group options in today's bleeding docker images?  The most important functionality for me is: assigning individual components and component lists to a group.

**Comment by nijel** [comment]
Teams are what groups at project level are called. But these do not allow creating per component teams for now (only per language ones).
