### ISSUE TITLE
Missing android support for Chinese (Traditional, Hong Kong)

### ISSUE THREAD

**Issue by nekohasekai** [WeblateOrg/weblate#7186]
### Describe the issue

https://github.com/WeblateOrg/weblate/blob/f0b4c8146b7c0663003ab04233c09f3cb8457119/weblate/formats/base.py#L37-L43

Add:
```
"zh_Hant_HK": "zh-rHK",
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Screenshots

![](https://user-images.githubusercontent.com/42300169/151682085-7c5f530d-ea49-4ed1-8611-25a1ea5a3830.png)

### How do you run Weblate?

weblate.org service

### Additional context

https://github.com/SagerNet/SagerNet/issues/358

**Comment by nekohasekai** [comment]
Weblate still submits wrong filename, what do I need to do?

**Comment by nijel** [comment]
That fix is not yet deployed. Still you can create or rename the file in git and it should work just fine.
