### ISSUE TITLE
Empty objects are filled with incorrect data

### ISSUE THREAD

**Issue by sr258** [WeblateOrg/weblate#7201]
### Describe the issue

I've installed the new 'Prefill translation with source' addon by installing the bleeding version of Weblate. I'm now experiencing an issue with the translation files generated by Weblate that hasn'T happened before. It might either be an issue with the addon or something introduced somewhere else.

The JSON source file has this structure:

```json
"field": {
    "fields": [
      {
        "label": "Score Range"
      },
      {},
      {
        "label": "Feedback for defined score range",
        "placeholder": "Fill in the feedback"
      }
    ]
  }
```

The file generated by Weblate for a translation (cs.json) in this case is this:

```json
"field": {
    "fields": [
      {
        "label": "Score Range"
      },
      {
        "label": "Feedback for defined score range",
        "placeholder": "Fill in the feedback"
      },
      {
        "label": "Feedback for defined score range",
        "placeholder": "Fill in the feedback"
      }
    ]
  }
```

As you can see the empty object with index 1 is filled with data from the next object.

Weblate doesn't have an entry for the object in the middle:
![image](https://user-images.githubusercontent.com/15268740/152490697-13eadc8a-ec52-4536-96d4-4bcda2580ce1.png)

I believe that Weblate for some reason doesn't deal with empty objects as well as it used to. I'm pretty sure this worked in the past.### 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

- Add this repository to Weblate: https://github.com/otacke/h5p-crossword/ (nested JSON, language/*.json as file pattern, language/.en.json as base file)
- Download the cs.json file (Czech). It won't show the properties in index 1
- Activate the 'Prefill translation with source'.
- Download the cs.json file (Czech). There will be the invalid entry in index 1. (see https://github.com/otacke/h5p-crossword/blob/1f910a657c0ade0a79bfff52c4302ff2a4759f78/language/cs.json#L74-L84)

### Expected behavior

The object at index 1 should be empty.

### How do you run Weblate?

Docker container

### Weblate versions

* Weblate: 4.11-1d04a36066
 * Django: 4.0.2
 * siphashc: 2.1
 * translate-toolkit: 3.5.3
 * lxml: 4.7.1
 * Pillow: 9.0.1
 * bleach: 4.1.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.2.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.13.0
 * oauthlib: 3.2.0
 * django-compressor: 3.1
 * djangorestframework: 3.13.1
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.4.2
 * jellyfish: 0.8.9
 * openpyxl: 3.0.9
 * celery: 5.2.3
 * kombu: 5.2.3
 * translation-finder: 2.11
 * weblate-language-data: 2022.1
 * html2text: 2020.1.16
 * pycairo: 1.20.1
 * pygobject: 3.42.0
 * diff-match-patch: 20200713
 * requests: 2.27.1
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.5.4
 * Cython: 0.29.27
 * misaka: 2.1.1
 * GitPython: 3.1.26
 * borgbackup: 1.1.17
 * pyparsing: 3.0.7
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * Python: 3.10.2
 * Git: 2.30.2
 * psycopg2: 2.9.3
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.17.20
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.20.48
 * zeep: 4.1.0
 * aeidon: 1.10.1
 * iniparse: 0.5
 * mysqlclient: 2.1.0
 * Mercurial: 6.0.2
 * git-svn: 2.30.2
 * git-review: 2.2.0
 * Redis server: 4.0.14
 * PostgreSQL server: 14.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.strato.de
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.15.0-166-generic (x86_64)

**Comment by nijel** [comment]
Handling JSON files with non translatable content is not really supported. Upon string change, the translate toolkit (library we use for handling translation files) updates matching element, but it doesn't copy content which is not shown in Weblate, such as empty objects.

**Comment by sr258** [comment]
But I believe this used to work in the past. The H5P files have these empty objects in several places and it hasn't been an issue before. In the past I had to use a patched version of translate toolkit to fix this problem, but for some time (at least a year or so) the empty objects in arrays used to work.

**Comment by nijel** [comment]
It really depends on what is being changed, but the code is not designed to handle such cases.
