### ISSUE TITLE
Glossary - Explanation disappears as soon as new term is added

### ISSUE THREAD

**Issue by RobbWatershed** [WeblateOrg/weblate#7210]
### Describe the issue

Whenever a new term is added to the glossary, explanation of previously added terms disappear

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Context : Multilingual project with english as its base language

1. Go to the Glossary
2. Go to English (base language)
3. Use "Add new glossary term" button
4. Type key and English translation (both are the same)
5. Click "Add"
6. Type an explanation in the Explanation field
7. Click "Save and continue"
8. Go back to Glossary / English, click on "All strings" and on the entry you just created
9. Make sure its explanation is still there
10. Go back to Glossary / English
11. Repeat steps 3 to 7
12. Go back to Glossary / English, click on "All strings" and on the entry you just created
13. Make sure its explanation is still there
14. Go back to Glossary / English, click on "All strings" and on the entry you created at step 7
15. Its explanation is now gone !

### Expected behavior

At step 15, the explanation of the 1st created entry should still be there

### Exception traceback

```pytb
N/A - No error nor crash displayed
```

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 4.11-dev, according to the footer

### Additional context

https://hosted.weblate.org/translate/hentoid/glossary/en/

**Comment by nijel** [comment]
It should be now deployed to https://hosted.weblate.org/.

**Comment by RobbWatershed** [comment]
Can confirm it works now. Thanks again @nijel 😄
