### ISSUE TITLE
Add check to ensure translated string never modifies variables

### ISSUE THREAD

**Issue by shasheene** [WeblateOrg/weblate#7211]
### Describe the problem

My open-source [project](https://github.com/rescuezilla/rescuezilla) receives a large number of translations thanks to Weblate.

The problem is my source strings contain variables using Python's format string syntax (enclosed by braces characters `{` and `}`), and even experienced translators sometimes accidentally translate the variable name.

Here's an example:
```
msgid "Successfully restored image partition {image} to {destination_partition}"
msgstr "Ripristinata con successo l'immagine della partizione {image} su {destinazione_partition}"
```
The `destination_partition` variable should not have been translated. The variable name needs to remain the same as the source string, otherwise in they'll be an error that may only be discovered at runtime when that variable is substituted:
```
>>> print("This is a {name}".format(name="test"))
This is a test

>>> print("This is a {name_wrong}".format(name="test"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'name_wrong'
````

Until now I have been discovering these errors by manually examining the source code everytime I merge a new translation.

### Describe the solution you'd like

Weblate should ideally have a "linter" to detect the mismatch based on some understanding of the variable delimiters.

The example I showed above is Python-specific, but other languages may suffer the same issue.

### Describe alternatives you've considered

I have considered running a "linter" to try and detect this error in my build system. A cursory search reveals a linter [that also doesn't detect this situation](https://github.com/ziima/polint/issues/9). As with most projects, my build system already runs `msgfmt` locally to "compile" the gettext source files into the .MO binary files. But the `msgfmt` "compilation" won't detect this error.

But I feel it's better to have this detection happen in Weblate itself, because then the translator can be informed of the error and fix it themselves.

**Comment by nijel** [comment]
There are already dozen of such checks, doesn't one of them fit your needs? https://docs.weblate.org/en/latest/user/checks.html#formatted-strings

**Comment by shasheene** [comment]
Oh wow thanks! That should definitely be enough for what I need!!

I see now that another user was also unaware of the flag a few months ago: https://github.com/WeblateOrg/weblate/issues/6920

**Comment by nijel** [comment]
With PO files and `xgettext`, these flags should be set automatically:

https://github.com/WeblateOrg/weblate/blob/4c6a09b861f1c7f839658dfcca5d532240ae4c9e/weblate/locale/cs/LC_MESSAGES/django.po#L311-L314

Maybe there is something wrong in the way you generate the PO files?
