### ISSUE TITLE
Extend search with comment_status field

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#7227]
### Describe the problem

Search allows translators to include the `comment:TEXT` field. When user notification is used, this field can be used as `comment:@Username` what results in a reduced list for which the user with `Username` has been explicitely mentioned. Currently, the result does not distinguish between *resolved* and *unresolved* comments. This makes it difficult for users to focus on comments which are still open / untreated.

### Describe the solution you'd like

Introduce a search field `comment_status:{resolved|unresolved}`.

A user can focus on unresolved comments with explicite mentioning by querying

- Custom search: `comment:@Username AND comment_status:unresolved`

**Comment by nijel** [comment]
I think it makes more sense to search for unresolved comments by default. This is consistent that we have `check:` and `dismissed_check:` qualifiers.

**Comment by rhofer** [comment]
Good idea. Many thanks for that quick implementation.
