### ISSUE TITLE
Creating a component from uploaded document ends with error

### ISSUE THREAD

**Issue by felixvd** [WeblateOrg/weblate#7233]
### Describe the issue

The `Translate Document` procedure either ends with an error before creating the component, or no translations can be created in the component (until a source repo is linked and a template added, presumably).

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to 'create/component/?project=1#doc'
2. Upload an .xlf file
3. Click "Continue" until you encounter this error:

![Screenshot from 2022-02-10 18-19-13](https://user-images.githubusercontent.com/4535737/153377213-db6beb87-de87-4ce2-9825-b69edff02e90.png)

5. You can work around this error by choosing "Disable adding new translations", but that just creates the component without any languages to translate to, which appears to be another dead end.

### Expected behavior

No template should be required to add new translations. The documentation should explain this use case better.

I expected [this documentation entry](https://docs.weblate.org/en/weblate-4.6.2/admin/projects.html#component-new-base) to be more helpful, but it does not seem to apply to my situation. How can I supply this file if I only upload the document? Should it not be a blank file by default? What does the template even look like?

### Screenshots

See above

### How do you run Weblate?

Other

### Weblate versions

We are running Weblate 4.6.2

### Weblate deploy checks

```shell
-
```

### Additional context

I am trying to set up a workflow for project managers who want do one-off translations of files, like [Matecat](https://www.matecat.com/). Is Weblate just not a good fit for this use?

**Comment by nijel** [comment]
> We are running Weblate 4.6.2

Have you tried upgrading?

Also what is rest of the component configuration, can you please share that as well?
