### ISSUE TITLE
Checkboxes display issue

### ISSUE THREAD

**Issue by NathanBnm** [WeblateOrg/weblate#7234]
### Describe the issue

I noticed a checkbox display issue while translating on hosted.weblate.org (version 4.11-dev). Checkboxes are now too big and centered relative to their parent.

It happens on the "Needs editing" option and in the "Add term to glossary" modal while translating as shown in the attached screenshots.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Screenshots

![Capture d’écran 2022-02-10 à 11 18 33](https://user-images.githubusercontent.com/45366162/153387979-ee1b9b26-5c34-4fc8-bdde-3b6539d8052f.png)
![Capture d’écran 2022-02-10 à 11 18 37](https://user-images.githubusercontent.com/45366162/153387983-15576610-ebd3-44c2-a9f9-b888a7f2706e.png)
![Capture d’écran 2022-02-10 à 11 23 04](https://user-images.githubusercontent.com/45366162/153387985-ad9818e5-02fd-4b4d-9352-7b6f77bb21df.png)

### How do you run Weblate?

weblate.org service

**Comment by Geeyun-JY3** [comment]
Still can reproduce in progress page on mobile Android System WebView 101.0.4951.41 (495104103).
![pic](https://user-images.githubusercontent.com/49396421/170646766-dcb445e0-03dc-4a2e-9c3e-1140d5abb0aa.jpg)

**Comment by nijel** [comment]
@Geeyun-JY3 Have you run `weblate collectstatic` after upgrading Weblate? This could be as well outcome of outdated CSS files.

**Comment by Geeyun-JY3** [comment]
I just reproduce this on Hosted Weblate.

**Comment by nijel** [comment]
Should be fixed in 86d4fb308c

**Comment by Geeyun-JY3** [comment]
Should be https://github.com/WeblateOrg/weblate/commit/d91dbe2668421ef588a10c106132f5d9d2c820c9. You copied the wrong URL 😂.
