### ISSUE TITLE
No more check when the same user changes twice a key

### ISSUE THREAD

**Issue by NicolasLeboeuf** [WeblateOrg/weblate#7239]
### Describe the problem

I often need to change twice in a row the same key (because I misstyped something for instance).

But the mechanism preventing simultaneous changes on the same key applies when the same user changes the same key in a short period of time.

Edit: regarding the error message. I can't "check my changes" as they are overridden by the error.

### Describe the solution you'd like

I'd like this doesn't happen in this case, and be able to change a key as many times as I want in a few seconds.

### Describe alternatives you've considered

At least it could keep the lastest translation, so I don't have to retranslate again the key.

### Screenshots

![image](https://user-images.githubusercontent.com/62602652/153568885-9c41ede8-8ee4-411d-9877-f533377f60f0.png)

**Comment by ritasandra** [comment]
Hello

**Comment by comradekingu** [comment]
@NicolasLeboeuf Can you provide an example of when what you describe happens? Preferably with links.

In the Zen editor the only uneditable state is if you change the source string without refreshing the page you attempt to make a translation in.

**Comment by NicolasLeboeuf** [comment]
Here an example on a new key.

I translate the key in english "Add". Then I want, a few seconds later, to change it to "New"
![2022-03-28 09_10_43-CTM-BACK_messages — English @ Weblate_ Add](https://user-images.githubusercontent.com/62602652/160345204-3356c9ba-c8f4-4a4e-a7b3-6f2537d304c1.png)

And I get the error. It doesn't save "New", tells me "please check", but displays the old translation, then I can't check (when the key is a long sentence and the change just one character it can be complicated to figure out where was the change).

This mechanism makes sense when you have several people working on the translations, but here the same user did the changes, then there is a minimal risk of error.
