### ISSUE TITLE
Zen mode doesn't just save once per change but constantly tries to save same change again and again

### ISSUE THREAD

**Issue by AwesomeStickz** [WeblateOrg/weblate#7243]
### Describe the issue

When typing in zen mode, it saves automatically, I guess it's supposed to save just once (per change) but it constantly tries to save the same thing again and again (even when you have made no changes after once) with a lot of POST requests which seems never ending in an infinite loop

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to zen mode
2. Type anything
3. Check your console, it'll be spamming POST requests trying to save it again and again

Not sure if it's 100% reproducible but for me, it is, my project is a new one with about 700 strings and a few languages, if that helps

### Expected behavior

Should just save it once

### Screenshots

![weblate](https://user-images.githubusercontent.com/38146668/153688066-365ffb42-7b6b-43b4-b495-bd3dd1ccf630.gif)

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.10.1
 * Django: 4.0
 * siphashc: 2.1
 * translate-toolkit: 3.5.1
 * lxml: 4.7.1
 * Pillow: 8.4.0
 * bleach: 4.1.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.1.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.13.0
 * oauthlib: 3.1.1
 * django-compressor: 3.1
 * djangorestframework: 3.13.1
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.4.0
 * setuptools: 60.0.4
 * jellyfish: 0.8.9
 * openpyxl: 3.0.9
 * celery: 5.2.1
 * kombu: 5.2.2
 * translation-finder: 2.10
 * weblate-language-data: 2021.7
 * html2text: 2020.1.16
 * pycairo: 1.20.1
 * pygobject: 3.42.0
 * diff-match-patch: 20200713
 * requests: 2.26.0
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.5.1
 * Cython: 0.29.26
 * misaka: 2.1.1
 * GitPython: 3.1.24
 * borgbackup: 1.1.17
 * pyparsing: 3.0.6
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * Python: 3.10.1
 * Git: 2.30.2
 * psycopg2: 2.9.2
 * psycopg2-binary: 2.9.2
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.17.17
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.20.26
 * zeep: 4.1.0
 * aeidon: 1.10.1
 * iniparse: 0.5
 * mysqlclient: 2.1.0
 * Mercurial: 6.0
 * git-svn: 2.30.2
 * git-review: 2.2.0
 * Redis server: 6.2.6
 * PostgreSQL server: 13.5
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.giveawayboat.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.4.0-89-generic (x86_64)

**Comment by nijel** [comment]
What browser do you use?

**Comment by AwesomeStickz** [comment]
Google Chrome, Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by nijel** [comment]
The saving is supposed to happen on the [change event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event), which should happen only when the textarea loses focus. Maybe you have some browser extension that causes this event to trigger more often?

**Comment by AwesomeStickz** [comment]
Though this is now fixed and closed, wanted to say this:

I don't think it's cuz of any extension I use. I tried the same in Mozilla Firefox which I barely use and I have no extensions in it so it's pretty much like a newly added browser but anyway, I tried there and I have the same problem there too so I don't think this could be cuz of any extension and might be cuz of something else
