### ISSUE TITLE
Weblate outputs empty Android string entities

### ISSUE THREAD

**Issue by arkon** [WeblateOrg/weblate#7248]
### Describe the issue

We were notified in https://github.com/tachiyomiorg/tachiyomi/pull/6607 (c.f. the PR diff) that the strings sometimes contain invalid empty string entities, e.g.,

```xml
<string name="foo" />
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Unsure, seems to be the existing Weblate behavior

### Expected behavior

- Entities are not included in the XML file if there's not translations.
- Weblate enforces all plurals items if needed

### How do you run Weblate?

weblate.org service

### Additional context

The related project: https://hosted.weblate.org/projects/tachiyomi/strings/

**Comment by arkon** [comment]
This still needs to be triaged.

**Comment by nijel** [comment]
This happens in case the string translation is being removed in Weblate. In case you don't want such entries to be present, you can use [Remove blank strings add-on](https://docs.weblate.org/en/latest/admin/addons.html#remove-blank-strings). If this is generally desired for this file format, it should be probably addressed in the translate-toolkit.

**Comment by arkon** [comment]
Thanks, the add-on works. 

https://github.com/translate/translate/issues/3281 seems to partially address the plurals issue, but it may be possible for Weblate to enforce validation on their end to require all quantities.

**Comment by nijel** [comment]
Not writing some strings to the files by Weblate should be covered by https://github.com/WeblateOrg/weblate/issues/3745.

Back to the original topic - is this general with the Android strings, or is this behavior specific to your use case?
