### ISSUE TITLE
Option to disable automatic repository scanning

### ISSUE THREAD

**Issue by pontaoski** [WeblateOrg/weblate#7251]
### Describe the problem

Weblate takes forever to scan huge repositories (~150k files), in order to autogenerate a config (I think). I already know what config I want to put in for the repo, so I don't need Weblate to waste its time autogenerating one that I'm going to throw out.

### Describe the solution you'd like

An explicit toggle for Weblate to autoscan or not.

**Comment by nijel** [comment]
It should be pretty easy to add a checkbox to skip the discover stage while creating a component:

https://github.com/WeblateOrg/weblate/blob/d598eb99180e98a15fc274207c921788e6693cee/weblate/trans/views/create.py#L286-L292

**Comment by nijel** [comment]
Meanwhile, I've made a lot of performance improvements to the scanning, so maybe this won't be needed in the end.

**Comment by nijel** [comment]
Closing for now, as I believe performance of Weblate 4.11 with translation-finder 2.12 should be acceptable in this case.
