### ISSUE TITLE
"Copy and Save" button from the Automatic Suggestions marks the strings as "Needs editing"

### ISSUE THREAD

**Issue by alexislg2** [WeblateOrg/weblate#7288]
### Describe the issue

When a translator selects an automatic translation that he finds OK and clicks "Copy and save", the string is copied and saved but with the "needs editing" mark.

It does not make sense. If a translator considers that the suggested translation is OK, he clicks on "copy and save". There's no reason why the string should need a further edit because a human translator considered it as correct.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to the Automatic Suggestion tab, select one of the suggested translations (from memory or auto translation)
1. Select one of the suggestions that is correct and click "copy and save"

### Expected behavior

1. The translation should be copied and saved but the string should not be marked as "needs editing" because a human translator considered it as correct.

### Screenshots

<img width="954" alt="image" src="https://user-images.githubusercontent.com/7933080/154997428-c4d7fd89-fb34-4734-9ad7-8d13e1571c62.png">

### How do you run Weblate?

Docker container

### Weblate versions

* Weblate: 4.10.1
 * Django: 4.0
 * siphashc: 2.1
 * translate-toolkit: 3.5.1
 * lxml: 4.7.1
 * Pillow: 8.4.0
 * bleach: 4.1.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.1.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.13.0
 * oauthlib: 3.1.1
 * django-compressor: 3.1
 * djangorestframework: 3.13.1
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.4.0
 * setuptools: 60.0.4
 * jellyfish: 0.8.9
 * openpyxl: 3.0.9
 * celery: 5.2.1
 * kombu: 5.2.2
 * translation-finder: 2.10
 * weblate-language-data: 2021.7
 * html2text: 2020.1.16
 * pycairo: 1.20.1
 * pygobject: 3.42.0
 * diff-match-patch: 20200713
 * requests: 2.26.0
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.5.1
 * Cython: 0.29.26
 * misaka: 2.1.1
 * GitPython: 3.1.24
 * borgbackup: 1.1.17
 * pyparsing: 3.0.6
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * Python: 3.10.1
 * Git: 2.30.2
 * psycopg2: 2.9.2
 * psycopg2-binary: 2.9.2
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.17.17
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.20.26
 * zeep: 4.1.0
 * aeidon: 1.10.1
 * iniparse: 0.5
 * mysqlclient: 2.1.0
 * Mercurial: 6.0
 * git-svn: 2.30.2
 * git-review: 2.2.0
 * Redis server: 6.2.6
 * PostgreSQL server: 13.6
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: email-smtp.eu-west-1.amazonaws.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.4.0-99-generic (x86_64)

**Comment by nijel** [comment]
What browser do you use?

**Comment by alexislg2** [comment]
@nijel  I use Chrome latest version but I also have this with other browsers
I think I found the cause: https://github.com/WeblateOrg/weblate/blob/eec50fb50357029fd8fa6f4a6cfe5b7a6602e71c/weblate/static/editor/full.js#L29

The "Copy and Save" button has the CSS class `.js-copy-save-machinery` BUT is inside a `<TR>`element that has the class `.js-copy-machinery`. So when you click on "Click and Save", both `this.$editor.on("click", ".js-copy-save-machinery")` and `this.$editor.on("click", ".js-copy-machinery")` are executed
