### ISSUE TITLE
JSON - Support trailing commans

### ISSUE THREAD

**Issue by Belorus** [WeblateOrg/weblate#7298]
### Describe the problem

We have flow where delopers commit changes to git, and via webhook weblate gets fresh translations.

Sometimes devs leave trailing comma after last translation, and weblate shows error

### Describe the solution you'd like

Support trailing commas in JSON

### Additional context

Weblate 4.10.1
Monolingual mode

**Comment by nijel** [comment]
Sorry, but there is no trailing comma in the JSON specification. We use standard Python parser here.

**Comment by Belorus** [comment]
@nijel Yep, and official parsers usually support that comma "mode" in addition to // comments (that are also not part of standard) to make usability higher. 

I'm a .net guy and we have following - https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-invalid-json?pivots=dotnet-6-0#allow-comments-and-trailing-commas

I fully understand your willingness to only stick to standards but usability is sometimes more important than purity, do you agree? In this situation it won't break any behavior / usecases

**Comment by nijel** [comment]
I looked for comment supporting parsers some time ago, and I was not really happy with available options. There is issue for that, so the options could be discussed there. I think it was about web extension JSON format...
