### ISSUE TITLE
Feature request: allow subscription at sub-project level

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#730]
Recently OsmAnd has created a new "sub-project" for iOs which I don't want to translate.
Yet there is no way to keep my subscription to OsmAnd but without the iOs branch.

Currently subscription is managed at project level, I need to manage my subscription on "branches" in a project.

regards,
##

**Comment by ldmpub** [comment]
Hi,

I would appreciate if this new feature can be implemented.

"Too many mails kills mail"... quote from Albert Einstein ;-))))

**Comment by nijel** [comment]
I'd like to see all features implement, but somehow they don't get implemented magically ;-).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
