### ISSUE TITLE
Slowness while saving after a Suggestion's 'Accept and Edit' command

### ISSUE THREAD

**Issue by valtermura** [WeblateOrg/weblate#7300]
### Describe the issue

While reviewing a suggestion, after having clicked the 'Accept and Edit' button, and edited the translation, when you click on the 'Save' button, the program takes a long time to save, up to 30 seconds and more.
It only happens with this particular type of action, the other actions seems to be ok.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to 'a suggestion'
2. Click on 'accept and edit button'
3. Modify the translation
4. Click on the 'Save' button
5. Wait for the completion of the action

### Expected behavior

The action should take one or two seconds (and not up to 30 secs, as experimented).

### How do you run Weblate?

Other

### Weblate versions

Weblate 4.8.1 running on (https://translations.documentfoundation.org/) 
https://translations.documentfoundation.org/about/

### Additional context

Other infos:
LibreOffice translation project
Italian Team project

**Comment by nijel** [comment]
Can you check server logs what happened in that time? Is there chance to upgrade?

**Comment by valtermura** [comment]
> Can you check server logs what happened in that time? Is there chance to upgrade?

I cannot. As translators part of a team, we are simple users and not administrators. We do not have access to the server log.
In any case, we will ask to the administrators of the server and check with them.

**Comment by nijel** [comment]
You can also ask them for upgrade, it might address some issues as well ;-). There were several performance improvements to labels or variants in case you happen to use these.
