### ISSUE TITLE
Changes to settigns blocked by Weblate due to error in unmodified "file mask" setting

### ISSUE THREAD

**Issue by TobiGr** [WeblateOrg/weblate#7312]
### Describe the issue

I tried to modify a few entries in the "Files" settings in [NewPipe/Strings](https://hosted.weblate.org/settings/newpipe/strings/). However, Weblate rejects the changes to whatever setting I modify and displays this message although **it was not modified** below the "File mask" entry:

> There is more than one file for Chinese (Simplified) language, please adjust the file mask and use components for translating different resources.
>
> Path of files to translate relative to repository root, use * instead of language code, for example: po/*.po or locale/*/LC_MESSAGES/django.po.

This error **blocks me from changing any setting**, although the "File mask" setting was not touched at all.

The content of the "file mask" setting is `app/src/main/res/values-*/strings.xml` which is the standard format for Android resource strings.  The following Chinese resource directories are in our repository.

> values-zh-rCN   [Chinese (Simplefied)]
> values-zh-rHK   [Chinese (Honkong)]
> values-zh-rTW   [Chinese (Traditional)]

All three are correctly identified by Weblate and translatable via the web app.
I do not know what to change to be able to modify other settings.
As a side note: It might be better to not block all changes when there is an error with another setting.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

That's the way the problem occoured in NewPipe:

1. Create a traanslation component for Android resource strings (file mask like `res/values-*/strings.xml`)
2. Add threse three languages (I cannot say whether they were added manually or via the web interface) 
   values-zh-rCN   [Chinese (Simplefied)]
   values-zh-rHK   [Chinese (Honkong)]
   values-zh-rTW   [Chinese (Traditional)]
3. go to the component's settings > files and try to modify any setting.

### Expected behavior

a) Weblate recognises that the file mask field has not been modified and thus allows me to make changes to other settings
b) Weblate does not throw an error at all

### Screenshots

![grafik](https://user-images.githubusercontent.com/17365767/155751529-eaaf62ee-481e-4b9b-9d8f-37c2c6297bb0.png)

### How do you run Weblate?

weblate.org service

### Weblate versions

[Hosted weblate](https://hosted.weblate.org) is used at version 4.11.1-dev

### Weblate deploy checks

```shell
cannot obtain, because https://hosted.weblate.org/ is used
```

**Comment by nijel** [comment]
There is most likely additional file in the repository....

**Comment by Geeyun-JY3** [comment]
Actually there are two files for Chinese (Simplified) in NewPipe repository, as I reported in https://github.com/TeamNewPipe/NewPipe/issues/6469:
1. https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-b%2Bzh%2BHANS%2BCN/strings.xml
2. https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-zh-rCN/strings.xml

And BTW, the Chinese (Simplified) from Weblate would only push to the first file now.

Not sure if it is related.

**Comment by nijel** [comment]
See https://hosted.weblate.org/projects/newpipe/strings/#alerts

**Comment by mhmdanas** [comment]
> And BTW, the Chinese (Simplified) translation from Weblate would only push to the first file now.

Is there any way to force Weblate to push changes to zh-rCN instead of b+zh+HANS+CN? See https://github.com/TeamNewPipe/NewPipe/issues/6469 and https://github.com/TeamNewPipe/NewPipe/pull/8549#issuecomment-1166228298.

**Comment by nijel** [comment]
Weblate does not rename files, it keeps whatever you have in the repository. The only time when Weblate logic comes into play is when creating new translations.
