### ISSUE TITLE
Multiple Module in one Git repository

### ISSUE THREAD

**Issue by Heshmatkhah** [WeblateOrg/weblate#7317]
### Describe the issue

Hi
I have a repository for a web application containing multiple modules written in python (more than 300 modules).
Each module has its i18n file.

Here is a demonstration of repository structure:
```
repo
 +-- core
 |    +-- some_python_files.py
 |    +-- i18n
 |         +-- en.po
 |         +-- core.pot
 +-- module_1
 |    +-- some_python_files.py
 |    +-- i18n
 |         +-- en.po
 |         +-- module_1.pot
 +-- module_2
 |    +-- some_python_files.py
 |    +-- i18n
 |         +-- en.po
 |         +-- module_2.pot
....
```

How can I add this repository to Weblate that Weblate detected each module as a spread translation component?

for Transifex, I add a `.tx/config` file like this:
```
[main]
host = https://www.transifex.com
type = PO

[project.core]
file_filter = core/i18n/<lang>.po
source_file = core/i18n/core.pot
source_lang = en

[project.module_1]
file_filter = module_1/i18n/<lang>.po
source_file = module_1/i18n/module_1.pot
source_lang = en

[project.module_2]
file_filter = module_2/i18n/<lang>.po
source_file = module_2/i18n/module_2.pot
source_lang = en

....
```
Then Transifex will automatically detect modules, translation templates, and existing translations. Also, it allows me to add new phrases.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Exception traceback

```pytb
I want to add a config file to the repository for automatically detecting translation files.
Or any guide for how to manually configure Weblate for this repository structure.
```

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.11
 * Django: 4.0.2
 * siphashc: 2.1
 * translate-toolkit: 3.6.0
 * lxml: 4.7.1
 * Pillow: 9.0.1
 * bleach: 4.1.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.2.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.0
 * django-compressor: 3.1
 * djangorestframework: 3.13.1
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.6.0
 * jellyfish: 0.9.0
 * openpyxl: 3.0.9
 * celery: 5.2.3
 * kombu: 5.2.3
 * translation-finder: 2.12
 * weblate-language-data: 2022.2
 * html2text: 2020.1.16
 * pycairo: 1.20.1
 * pygobject: 3.42.0
 * diff-match-patch: 20200713
 * requests: 2.27.1
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.5.6
 * Cython: 0.29.28
 * misaka: 2.1.1
 * GitPython: 3.1.27
 * borgbackup: 1.2.0
 * pyparsing: 3.0.7
 * pyahocorasick: 1.4.4
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.0.12
 * Python: 3.10.2
 * Git: 2.30.2
 * psycopg2: 2.9.3
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.21.8
 * zeep: 4.1.0
 * aeidon: 1.10.1
 * iniparse: 0.5
 * mysqlclient: 2.1.0
 * Mercurial: 6.0.3
 * git-svn: 2.30.2
 * git-review: 2.2.0
 * Redis server: 6.2.6
 * PostgreSQL server: 13.6
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.scarfbank.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.4.0-26-generic (x86_64)

### Weblate deploy checks

```shell
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail ((535, b'Incorrect authentication data')), please check EMAIL_* settings.
	HINT: https://docs.weblate.org/en/weblate-4.11/admin/install.html#out-mail

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.11/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.11/admin/backup.html

System check identified 7 issues (1 silenced).
ERROR: 1
```

**Comment by nijel** [comment]
There is currently no configuration file used by Weblate. You can use [Component discovery add-on](https://docs.weblate.org/en/latest/admin/addons.html#component-discovery) to create more components from a single repository.
