### ISSUE TITLE
File-upload defaults to replacing all strings

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#7322]
### Describe the problem

https://hosted.weblate.org/projects/projectname/component/language_code/#upload
has ~"all" (update translated and approved strings) selected by default (in the bottommost dropdown),
instead of "untranslated only".

### Describe the solution you'd like

Me getting more clever with the buttons, (getting there).
"Untranslated only" by default

### Additional context

This would avoid overwriting good translations.
The other one also has "import as translated" by default.

**Comment by nijel** [comment]
The form recalls whatever you've used last time. The actual default is to replace translated strings only (as that is what people typically want when uploading):

https://github.com/WeblateOrg/weblate/blob/35bafce010ef47a9bea3521c9c36636fbddadd4c/weblate/trans/forms.py#L653
