### ISSUE TITLE
JSON i18next changed the format json file - weblate 3.9.1

### ISSUE THREAD

**Issue by gb-ccartagena** [WeblateOrg/weblate#7331]
### Describe the issue

I have a component with the file format: "i18next JSON file" when an update of the translation is made from the weblate interface and the commit is made, it changes the content of the file and where there is a dot (.) it changes it to a nested text ({})

So where my common.json used to look like this:
```
{
"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.":""
}
```

it got transformed into this:
```
{
"Lorem Ipsum is simply dummy text of the printing and typesetting industry": {
    " Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book": {
        "": ""
        }
   }
}
```

These changes are made to all strings that have a dot, even if it hasn't been updated.

What can I do so that the dots do not change?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Screenshots

![Screenshot from 2022-03-01 17-50-43](https://user-images.githubusercontent.com/100703541/156262435-928e3578-ce74-43e0-ab1b-d95f2de5de28.png)

### How do you run Weblate?

PyPI module

### Weblate versions

 * Weblate 3.9.1

**Comment by nijel** [comment]
Is this really i18next? Maybe using plain JSON format would be more appropriate?

Anyway, Weblate should not change existing strings, so there is something broken in the version you are using. Handling of JSON files have been heavily improved since then, so the first thing you should try is upgrading to the current release.
