### ISSUE TITLE
"Prefill translation with source" addon pushes on translation file creation

### ISSUE THREAD

**Issue by sr258** [WeblateOrg/weblate#7334]
### Describe the issue

If you enable the new "Prefill translation with source" addon and create a new translation file, it automatically creates a push to the repository with the prefilled translation.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Expected behavior

The translation is prefilled, but it is not pushed to the version control system.

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.11-1d04a36066
 * Django: 4.0.2
 * siphashc: 2.1
 * translate-toolkit: 3.5.3
 * lxml: 4.7.1
 * Pillow: 9.0.1
 * bleach: 4.1.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.2.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.13.0
 * oauthlib: 3.2.0
 * django-compressor: 3.1
 * djangorestframework: 3.13.1
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.4.2
 * jellyfish: 0.8.9
 * openpyxl: 3.0.9
 * celery: 5.2.3
 * kombu: 5.2.3
 * translation-finder: 2.11
 * weblate-language-data: 2022.1
 * html2text: 2020.1.16
 * pycairo: 1.20.1
 * pygobject: 3.42.0
 * diff-match-patch: 20200713
 * requests: 2.27.1
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.5.4
 * Cython: 0.29.27
 * misaka: 2.1.1
 * GitPython: 3.1.26
 * borgbackup: 1.1.17
 * pyparsing: 3.0.7
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * Python: 3.10.2
 * Git: 2.30.2
 * psycopg2: 2.9.3
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.17.20
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.20.48
 * zeep: 4.1.0
 * aeidon: 1.10.1
 * iniparse: 0.5
 * mysqlclient: 2.1.0
 * Mercurial: 6.0.2
 * git-svn: 2.30.2
 * git-review: 2.2.0
 * Redis server: 4.0.14
 * PostgreSQL server: 14.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.strato.de
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.15.0-169-generic (x86_64)

**Comment by nijel** [comment]
It is intentionally that way to ensure that the blank file is not kept in the repository. Also, any translation of the file would trigger committing anyway.
