### ISSUE TITLE
Development docker does not work

### ISSUE THREAD

**Issue by qwerty287** [WeblateOrg/weblate#7336]
### Describe the issue

Requested to open a new issue: https://github.com/WeblateOrg/weblate/pull/7326#pullrequestreview-897184491

Sorry for the bad issue title.
I have some issues with working with the development docker image:
1. If I just run it, it seems that the nginx or the server running there can't access the cache folders and browsers can't access static CSS and JS files. This can be solved by using `docker exec`  and then running a `chmod` command inside the container, but it have to be done everytime I restart the container.
2. It does not apply changes I do in my local code. Maybe I'm doing or understanding something wrong, but restarting the container (using `./rundev.sh` and `./rundev.sh stop`) should actually use my changes done in the code? I don't know why, there aren't any errors in the logs, but it's just not working.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

I don't know - these issues are probably only affecting me, so I can't give you a good proposal.

### How do you run Weblate?

Git checkout

### Weblate versions

(Almost) latest commit from `main` branch

**Comment by nijel** [comment]
Can you please share the exact error message and chmod you are executing?

**Comment by qwerty287** [comment]
chmod was always just a simple chmod and I gave 777 perms to make it simple for me (`chmod -R 777 <path, I don't know which one it was, will look it up>`) - for the error msg I'll look again later.

**Comment by qwerty287** [comment]
After trying to get the error, the static chmod thing is working now. Will check if it's also working that it runs my "own" code.

**Comment by qwerty287** [comment]
It has been working once, now it stopped working. Error is e.g.
`nginx stderr | 2022/03/02 18:55:52 [error] 232#232: *1 open() "/app/cache/static/vendor/bootstrap/css/bootstrap-datepicker3.css" failed (13: Permission denied), client: 172.20.0.1, server: , request: "GET /static/vendor/bootstrap/css/bootstrap-datepicker3.css?v=4.11-c2b01df5bd HTTP/1.1", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/"`
