### ISSUE TITLE
Add Libravatar support

### ISSUE THREAD

**Issue by Wuzzy2** [WeblateOrg/weblate#7342]
### Describe the problem

The only way to get an avatar is gravatar.com, a proprietary avatar service. But it would be better if Weblate supports the FOSS community.

### Describe the solution you'd like

Add support for Libravatar (https://www.libravatar.org).

### Describe alternatives you've considered

Just let users upload the avatar directly instead of relying on any 3rd-party service.

**Comment by nijel** [comment]
You can use [AVATAR_URL_PREFIX](https://docs.weblate.org/en/latest/admin/config.html#avatar-url-prefix) (see https://github.com/WeblateOrg/weblate/issues/2155 and https://github.com/WeblateOrg/weblate/issues/2109).

The user uploaded avatars are also on the roadmap, see https://github.com/WeblateOrg/weblate/issues/3564
