### ISSUE TITLE
Translation Memory Maintenance - Global delete and recreate

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#7347]
### Describe the problem

Situation, goal and problem is described in https://github.com/WeblateOrg/weblate/issues/7346

### Describe the solution you'd like

- Today, TM handling allows upload, download and delete
- Extend handling with recreate / renew TM: flush all old entries and freshly create from active component/project
  - Most likely feasible for project TM
  - For personal TM it may makes no sense. Upload, download and delete might be sufficient
  - For shared TM, the renew option would possibly point at project TM

![TM-refresh-buttons](https://user-images.githubusercontent.com/8058166/156714547-3d5d12ed-edc8-4658-9a6d-473d146fa028.png)

Assuming that translations on components are managed carefully (and review states are applied properly), such a "global" clean-up in sense of recreating from current component state, would be very helpful in order to get rid of old, invalid strings and would reduce TM pollution by carriyng out this actions from time to time.

Excluded:

- Manually uploaded TMs either on project level or personal level shall not be affected. This still shall work as-is.

Affects:
- shared TM
- project TM
- personal TM

Pros
- Impoved TM handling. Allows TM intervention if needed / on event.
- Management actions on TM are selective.

Cons
- Requires manual interaction
- Requires awareness of translators (if awareness is not given, TM will still grow and pollute)
  - Our translators are not working daily with Weblate, hence, they are even not aware of what maintenance features are available. We assume, they would not use manual TM management, what leads to polluted TMs again.

**Comment by rhofer** [comment]
@nijel Many thanks for this feature. Is there any indication how long it takes to rebuild a TM? How long will it take after triggering rebuild until the TM is visible again in `Project / Translation memory` ?

**Comment by nijel** [comment]
There is currently no indication for that. I've added at least logging of components being updated in 4fe4f9a3405516b14cf191b54b9107b6cea7199d.
