### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by bouhlal** [WeblateOrg/weblate#7358]
### Describe the issue

when I try to install Weblate I got the error bellow,
please tell me how can I fix it ?
I'm using windows subLinux ubuntu

`:~$ sudo pip install "Weblate[all]"
Collecting Weblate[all]
  Using cached Weblate-4.11.2-py3-none-any.whl (26.6 MB)
Collecting borgbackup<1.3,>=1.1.11
  Downloading borgbackup-1.2.0.tar.gz (4.0 MB)
     |████████████████████████████████| 4.0 MB 230 kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fjwxp1j_/borgbackup/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fjwxp1j_/borgbackup/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-fjwxp1j_/borgbackup/pip-egg-info
         cwd: /tmp/pip-install-fjwxp1j_/borgbackup/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fjwxp1j_/borgbackup/setup.py", line 185, in <module>
        setup_crypto.crypto_ext_kwargs(pc, system_prefix_openssl),
      File "/tmp/pip-install-fjwxp1j_/borgbackup/setup_crypto.py", line 32, in crypto_ext_kwargs
        raise Exception('Could not find OpenSSL lib/headers, please set BORG_OPENSSL_PREFIX')
    Exception: Could not find OpenSSL lib/headers, please set BORG_OPENSSL_PREFIX
    Warning: can not import pkgconfig python package.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

PyPI module

**Comment by nijel** [comment]
Seems like borgbackup 1.2 is missing some build time dependencies. Try installing pkgconfig before: `pip install pkgconfig`

**Comment by KuSh** [comment]
On macos this is because pkgconfig doesn't found the openssl version provided by homebrew :
Adding `/usr/local/opt/openssl@3/lib/pkgconfig` to PKG_CONFIG_PATH environment variable fixes the problem
