### ISSUE TITLE
Burmese punctuation not detected

### ISSUE THREAD

**Issue by alanazar** [WeblateOrg/weblate#7375]
### Describe the issue

Hello,
While contributing to this project to solve outstanding errors I realized the Burmese punctuation is not being detected properly.
I tried researching but not sure how to fix it
https://translate.jellyfin.org/checks/end_stop/jellyfin/
https://translate.jellyfin.org/checks/end_question/jellyfin/

The Burmese full stop is this:
။

and the question mark is this:
း။

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Other

**Comment by nijel** [comment]
The full stop is supported in Weblate 4.11: 8e3a19f48fc8052d5a3de2b3c3eedc4bae62bb2e

**Comment by alanazar** [comment]
Hello,

This is still not working even though Weblate has been updated to version 4.13.1

**Comment by nijel** [comment]
The upgrade will not trigger running checks, in the [default configuration](https://docs.weblate.org/en/latest/admin/config.html#background-tasks) the checks are update once in a month. You can trigger this manually using [updatechecks](https://docs.weblate.org/en/latest/admin/management.html#updatechecks) management command.

**Comment by alanazar** [comment]
Thank you!

**Comment by alanazar** [comment]
> The upgrade will not trigger running checks, in the [default configuration](https://docs.weblate.org/en/latest/admin/config.html#background-tasks) the checks are updated once in a month. You can trigger this manually using [updatechecks](https://docs.weblate.org/en/latest/admin/management.html#updatechecks) management command.

Hello,
Can you please check these errors?
https://translate.jellyfin.org/translate/jellyfin/jellyfin-web/my/?q=check:end_stop%20OR%20dismissed_check:end_stop

It seems Weblate is still picking up these as a full-stop error
။ – signifies a full stop, or the end of a sentence;
း။ – signifies a question mark;

The problem is weblate is picking up the last 2 lines as a misplaced fullstop even though the source is a question

**Comment by nijel** [comment]
I've fixed these now. It turns out that copy-pasting the composed question mark didn't work correctly and caused some issues.

**Comment by alanazar** [comment]
> I've fixed these now. It turns out that copy-pasting the composed question mark didn't work correctly and caused some issues.

Thank you! :)
