### ISSUE TITLE
Pseudolocale add-on respects the length of text being localized

### ISSUE THREAD

**Issue by KadAnna** [WeblateOrg/weblate#7381]
### Describe the problem

I want to use the pseudolocale add-on for testing if it fits withing the fixed dialog size. The texts and dialog windows are of various size - from a heading in a table to full sentences. At the moment. I can add only a fixed number of charactets, which does not really respect the variability of text that is being localized.

### Describe the solution you'd like

I would like to choose flexible number of characters of suffixes, depending on the length of a string. Let us say for a string with less then 10 characers, between 10-30 characters and more then 30 characters, I would choose a suffix of the text's lentgh of  130 %, 120 % and 110% respectively.
We have good experience with using @ as a prefix, and [appropriate number of underscores]@ as suffix.

e.g.
`@this is a middle long text__@`

**Comment by nijel** [comment]
This is how it will look like:

![image](https://user-images.githubusercontent.com/212189/158602116-051dea5d-40bb-4c9a-9639-963eaba9dddc.png)

Feedback is welcome.

**Comment by KadAnna** [comment]
Thank you for the nice feature! works perfectly.
