### ISSUE TITLE
Cannot resolve keyword 'expires' into field

### ISSUE THREAD

**Issue by stefanopallicca-imagicle** [WeblateOrg/weblate#7385]
### Describe the issue

Version 4.11.2 (docker)

Using Sentry.io, I receive lots of these errors:
```
Cannot resolve keyword 'expires' into field. Choices are: auditlog, auth_token, author_set, change, comment, contributoragreement, date_expires, date_joined, email, font, full_name, groups, id, is_active, is_bot, is_superuser, last_login, logentry, memory, password, profile, screenshot, social_auth, subscription, suggestion, user_votes, userblock, username, vote
```

django/db/models/sql/query.py in names_to_path at line 1640
![image](https://user-images.githubusercontent.com/81425747/158331224-4760cdb8-5956-48fd-9be8-1ab0d192e68e.png)

I' don't know what kind of impact this may have on my current installation.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.11.2
 * Django: 4.0.3
 * siphashc: 2.1
 * translate-toolkit: 3.6.0
 * lxml: 4.7.1
 * Pillow: 9.0.1
 * bleach: 4.1.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.2.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.0
 * django-compressor: 3.1
 * djangorestframework: 3.13.1
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.6.0
 * jellyfish: 0.9.0
 * openpyxl: 3.0.9
 * celery: 5.2.3
 * kombu: 5.2.3
 * translation-finder: 2.12
 * weblate-language-data: 2022.2
 * html2text: 2020.1.16
 * pycairo: 1.20.1
 * pygobject: 3.42.0
 * diff-match-patch: 20200713
 * requests: 2.27.1
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.5.6
 * Cython: 0.29.28
 * misaka: 2.1.1
 * GitPython: 3.1.27
 * borgbackup: 1.2.0
 * pyparsing: 3.0.7
 * pyahocorasick: 1.4.4
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.0.12
 * Python: 3.10.2
 * Git: 2.30.2
 * psycopg2: 2.9.3
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.21.12
 * zeep: 4.1.0
 * aeidon: 1.10.1
 * iniparse: 0.5
 * mysqlclient: 2.1.0
 * Mercurial: 6.1
 * git-svn: 2.30.2
 * git-review: 2.2.0
 * Redis server: 6.2.6
 * PostgreSQL server: 13.6
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: outlook.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.11.0-1017-aws (x86_64)

### Weblate deploy checks

```shell
System check identified no issues (1 silenced).
```

**Comment by nijel** [comment]
Already fixed by 7f68307dc3535561420c55728f7eff679f797735.
