### ISSUE TITLE
Weblate changes indentation for all lines in WebExtension files

### ISSUE THREAD

**Issue by hbinkle** [WeblateOrg/weblate#7393]
### Describe the issue

After weblate changed the file the original indentation is changed and so all lines in the file occur as changed in VCS (git)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Expected behavior

The indentation should be kept like in the original file or at least I should be able to adjust it somewhere to match developer settings.

### Screenshots

![image](https://user-images.githubusercontent.com/51942180/158751171-2e6fd14f-3bd2-4fe3-81ba-2b903ebf399c.png)

### How do you run Weblate?

Docker container

### Weblate versions

4.10.1

**Comment by nijel** [comment]
The indentation can be customized by [Customize JSON output add-on](https://docs.weblate.org/en/latest/admin/addons.html#customize-json-output).

**Comment by hbinkle** [comment]
[Customize JSON output add-on](https://docs.weblate.org/en/latest/admin/addons.html#customize-json-output) solved the problem.
