### ISSUE TITLE
After the migration from CentOS 7 to AlmaLinux 8.5 getting 504 on /manage/performance 

### ISSUE THREAD

**Issue by pavel-hladik** [WeblateOrg/weblate#7400]
### Describe the issue

Hi,

I'm on Weblate 4.10.1 and after the migration of OS from CentOS 7 to AlmaLinux 8.5 I'm getting 504 on /manage/performance. I see no errors on uwsgi or celery workers logs. Probably the /manage/performance is running the command `weblate check --deploy`, which is not working neither.

When I do:
```
[root@weblate ~]# su - weblate
[weblate@weblate ~]$ source "/opt/weblate/weblate-env/bin/activate"
(weblate-env) [weblate@weblate ~]$ weblate check --deploy
```
I can wait for couple of hours for progress but it is just in stuck. When I cancel the command with ctrl+c I see:
```
^CTraceback (most recent call last):
  File "/opt/weblate/weblate-env/bin/weblate", line 8, in <module>
    sys.exit(main())
  File "/opt/weblate/weblate-env/lib/python3.6/site-packages/weblate/runner.py", line 34, in main
    utility.execute()
  File "/opt/weblate/weblate-env/lib/python3.6/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/weblate/weblate-env/lib/python3.6/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/weblate/weblate-env/lib/python3.6/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/weblate/weblate-env/lib/python3.6/site-packages/django/core/management/commands/check.py", line 69, in handle
    databases=options['databases'],
  File "/opt/weblate/weblate-env/lib/python3.6/site-packages/django/core/management/base.py", line 423, in check
    databases=databases,
  File "/opt/weblate/weblate-env/lib/python3.6/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/weblate/weblate-env/lib/python3.6/site-packages/weblate/utils/checks.py", line 131, in check_mail_connection
    connection.open()
  File "/opt/weblate/weblate-env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 62, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/lib64/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python3.6/smtplib.py", line 338, in connect
    (code, msg) = self.getreply()
  File "/usr/lib64/python3.6/smtplib.py", line 387, in getreply
    line = self.file.readline(_MAXLINE + 1)
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```
I can say all other components working correctly and I see just this issue.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

I tried to migrate CentOS 7 to AlmaLinux 8.5, there are plenty of steps, it is hard to document it. But I want to see at least some error to know what I need to focus on.

### Expected behavior

Some output from command.

### How do you run Weblate?

Other

### Weblate versions

 * Weblate: 4.10.1
 * Django: 3.2.11
 * siphashc: 1.3
 * translate-toolkit: 3.5.3
 * lxml: 4.7.0
 * Pillow: 7.0.0
 * bleach: 3.1.1
 * python-dateutil: 2.8.1
 * social-auth-core: 4.1.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-filter: 2.4.0
 * django-appconf: 1.0.3
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 45.2.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.3
 * celery: 5.1.2
 * kombu: 5.1.0
 * translation-finder: 2.7
 * weblate-language-data: 2022.1
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.34.0
 * diff-match-patch: 20200713
 * requests: 2.22.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.1
 * Cython: 0.29.15
 * misaka: 2.1.1
 * GitPython: 3.0.8
 * borgbackup: 1.1.10
 * pyparsing: 3.0.7
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * Python: 3.6.8
 * Git: 2.27.0
 * psycopg2-binary: 2.8.4
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.0
 * boto3: 1.20.46
 * zeep: 3.4.0
 * aeidon: 1.10.1
 * iniparse: 0.5
 * Mercurial: 6.0.1
 * git-svn: 2.27.0
 * git-review: 2.2.0
 * Redis server: 6.0.9
 * PostgreSQL server: 12.9
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.18.0-348.20.1.el8_5.x86_64 (x86_64)

**Comment by nijel** [comment]
Is your celery worker running?

**Comment by pavel-hladik** [comment]
Yes it is, I tried to clear all the celery worker logs, restart them and see if I can catch some error during running the cmd `weblate check --deploy`, but no luck, there are no errors. We verified basic functionality and everything seems to work, except this one cmd.

**Comment by nijel** [comment]
Ah, looking again at the error, it fails to connect to SMTP server. Not sure why some timeout is not applied here...

**Comment by pavel-hladik** [comment]
Thank you! That was it.
