### ISSUE TITLE
You do not have permission to perform this action

### ISSUE THREAD

**Issue by tjazwinski** [WeblateOrg/weblate#7418]
### Describe the issue

I'm trying to add explanation to unit:
PATCH /api/units/70697/
"{"explanation":"test"}"
I'm working on admin user
I added:
Authorization: Token wlu_lwHnIcqM3y********************************

And I receive such message:
{"detail":"You do not have permission to perform this action."}

User admin has also asigned all groups

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

Docker container

### Weblate versions

4.10.1

**Comment by burner1024** [comment]
> Explanation can only be changed on the source strings (it is displayed on all languages).

@nijel is it the same for extra_flags? Getting the same error for those.
