### ISSUE TITLE
API returns maximum of 20 records at a time

### ISSUE THREAD

**Issue by cwarnermm** [WeblateOrg/weblate#7438]
### Describe the issue

I'm using the APIs to generate a list of translation contributors over a given period of time. The APIs appear to return only 20 records at a time which results in the generated list taking considerable time to finish. Is there a way to return more records at a time? I couldn't find something like this documented in the API docs.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Screenshots

![image](https://user-images.githubusercontent.com/74422101/160430968-16a728c9-75c5-4346-824a-487a13c88521.png)

### How do you run Weblate?

Other

**Comment by nijel** [comment]
The pagination is currently defined in `REST_FRAMEWORK` in `settings.py`. You can change the page size by changing `PAGE_SIZE`.
