### ISSUE TITLE
Pullrequests have title 'None'

### ISSUE THREAD

**Issue by MAGICCC** [WeblateOrg/weblate#7451]
### Describe the issue

Somehow when I push the changes from Weblate to GitHub it will create a PR where the title is 'None' and without content.
I am not sure why it causes it.
See https://github.com/mailcow/mailcow-dockerized/pull/4529, I edited the title manually and added the normal content as comment

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Add changes to weblate
2. Push to GH
3. It will create a PR with title 'None' and no content in the comment

### Expected behavior

Have the 'normal' PR content.

### Screenshots

Below the screenshot that I edited the comment.
![edit_comment](https://user-images.githubusercontent.com/3279213/161132097-da6ace16-7191-4d5e-a131-8c4df1caf5e8.png)

### How do you run Weblate?

Docker container

### Weblate versions

```
 * Weblate: 4.11.2
 * Django: 4.0.3
 * siphashc: 2.1
 * translate-toolkit: 3.6.0
 * lxml: 4.7.1
 * Pillow: 9.0.1
 * bleach: 4.1.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.2.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.0
 * django-compressor: 3.1
 * djangorestframework: 3.13.1
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.6.0
 * jellyfish: 0.9.0
 * openpyxl: 3.0.9
 * celery: 5.2.3
 * kombu: 5.2.3
 * translation-finder: 2.12
 * weblate-language-data: 2022.2
 * html2text: 2020.1.16
 * pycairo: 1.20.1
 * pygobject: 3.42.0
 * diff-match-patch: 20200713
 * requests: 2.27.1
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.5.6
 * Cython: 0.29.28
 * misaka: 2.1.1
 * GitPython: 3.1.27
 * borgbackup: 1.2.0
 * pyparsing: 3.0.7
 * pyahocorasick: 1.4.4
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.0.12
 * Python: 3.10.2
 * Git: 2.30.2
 * psycopg2: 2.9.3
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.21.12
 * zeep: 4.1.0
 * aeidon: 1.10.1
 * iniparse: 0.5
 * mysqlclient: 2.1.0
 * Mercurial: 6.1
 * git-svn: 2.30.2
 * git-review: 2.2.0
 * Redis server: 6.2.6
 * PostgreSQL server: 13.6
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: hosted.mailcow.de
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.4.0-104-generic (x86_64)
```

### Weblate deploy checks

```shell
System check identified some issues:

WARNINGS:
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.11.2/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.11.2/admin/backup.html

System check identified 3 issues (1 silenced).
```

### Additional context

I updated to Weblate: 4.11.2 some days after release. Since we dont have so many translations I didnt see the issue immediately

**Comment by nijel** [comment]
It should be the first line of DEFAULT_PULL_MESSAGE, what do you have configured there?

**Comment by MAGICCC** [comment]
I never set a env varible in my docker-compose.override.yml for this so its empty

**Comment by connyduck** [comment]
This happens to us as well, e.g. here https://github.com/tuskyapp/Tusky/pull/2421
