### ISSUE TITLE
Ability to hide language or source File Translation

### ISSUE THREAD

**Issue by jolessops** [WeblateOrg/weblate#7469]
### Describe the problem

We recently upgraded from Weblate 3.7 to the latest version. In the past, the source file was not showing inside the project. Now on the latest release, this file is showing in the project.

We don't want users to be able to change this source file language. Since all our source files use the same language I have removed the right to change this language. We will also create the newer component with the Edit base File option Uncheck.

We would like the option to completely hide the source file or a complete language from a user group.

### Describe the solution you'd like

We would like to either have the option to hide a language from a user group or the option to hide the source file when we create a new component.

### Additional context

Weblate 4.11.2 with docker installation
All projects are private and we use some custom groups for security

I have made the feature request because I didn't find any way to do this. If there is already an option you can let me know.

**Comment by nijel** [comment]
The older versions had a dedicated source strings view for this, and now it's consolidated to the same UI as translations.

Currently, there is no option to hide a language. Even if the source language is not editable, it is useful to browse for problematic strings with quality checks.
