### ISSUE TITLE
Hosted weblate fails to create pull request on gitlab.com with error 403 Forbidden (-1)

### ISSUE THREAD

**Issue by 1u** [WeblateOrg/weblate#7477]
### Describe the issue

Automatic and manual pushes lead to error 405
"Failed to create pull request: 403 Forbidden (-1)"

We have some memories that it happened before and disappeared again just like this.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to https://hosted.weblate.org/projects/openki/openki/#repository 
2. Go to  "2 Outgoing commits in the Weblate repository"
3. Click on push
4. See error above and underneath

### Expected behavior

Creating a pull request on https://gitlab.com/Openki/Openki/ branch dev

### Screenshots

![image](https://user-images.githubusercontent.com/4281072/162272502-4c2f6700-325f-4084-9f8d-3a826b82f30a.png)

### Exception traceback

```pytb
Error above: "Could not push to remote branch on Openki/Openki."
Underneath: "Failed to create pull request: 403 Forbidden (-1)"
```

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Most likely, it's caused by the Openki Gitlab repository configuration. I don't see the "New merge request" button at https://gitlab.com/Openki/Openki/-/merge_requests as I see it on other projects ....

**Comment by 1u** [comment]
Hi thx for answering! And looking into it a bit. 

So no other gitlab.com repositories that are affected by the same problem...

I checked a lot of settings in the repository on GitLab before opening this issue. I didn't find any settings that would forbid to make a merge request. And we don't remember having changed something there. I'm now in contact with GitLabs support. I'll keep you updated here.

**Comment by 1u** [comment]
@nijel yes exactly, thx for the screenshots. Sorry I didn't confirm this before: I saw the exact same behavior...

I didn't get a helping response from gitlab support yet. I now just added gitlab user "weblate" as role "reporter" to the openki repository and pushed manually [here](https://hosted.weblate.org/projects/openki/openki/#repository). And it worked. No idea what's going wrong. I'll keep you updated here if I find out more.

**Comment by 1u** [comment]
Removed Weblate as role "reporter" from the repo -> Pushing didn't work again.   
Added as "Guest" -> Pushing worked again.

**Comment by 1u** [comment]
Update: Gitlab support is looking into it further. Pointed me to https://gitlab.com/gitlab-org/gitlab/-/issues/358665

**Comment by comradekingu** [comment]
@1u Got fixed in GitLab upstream. Works now?

**Comment by 1u** [comment]
Nice! Yes.   

I just removed user @weblate as guest from our repo and pushed it manually in the hosted.weblate UI and it worked again. :tada:
