### ISSUE TITLE
Improve names for Chinese variants

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#7488]
### Describe the problem

Options for interface language are untranslatable.

https://github.com/WeblateOrg/weblate/blob/ab1de3cd5fdf05da0bc2db3ece0e08fa2cd6b689/weblate/settings_example.py#L98-L142
(same in https://github.com/WeblateOrg/weblate/blob/main/weblate/settings_docker.py, https://github.com/WeblateOrg/website/blob/main/weblate_web/settings.py)

They are not consistent with the native name of each language in [Weblate/Language data](https://hosted.weblate.org/projects/weblate/languages/) (translated by translators of each language)

BTW, options for [interface language in Weblate itself](https://hosted.weblate.org/accounts/profile/#languages) is weird. They start with (up to down)
```
한국어
---------
```

### Describe the solution you'd like

Make options for interface language translatable.

Now that translators of each language would translate their own language’s English name into their language (that is language’s native name) in Weblate/Language data, why not make use of them and make these options translatable.

### Describe alternatives you've considered

TBH, I prefer the Twitter-style language option: starting with the language’s name in the current language, ending with its native name, connecting the above-mentioned two languages’ names using ` - `.
![image](https://user-images.githubusercontent.com/49396421/162624444-200aff56-46a9-420c-a86c-278165b6bad7.png)

But if you want to reuse the code everywhere and there is not enough space in the language chooser of the Weblate website, I am OK with the current style — only using the native name.

### Screenshots

![image](https://user-images.githubusercontent.com/49396421/162601605-376cb76f-34ec-4e0a-9614-8f265f901db5.png)

**Comment by nijel** [comment]
There is definitely not enough space on the weblate.org language chooser. Also, I think the native name is the most important because that's what a person speaking in that language will always understand.

**Comment by Geeyun-JY3** [comment]
OK. How about making these language names translatable by their translators?

**Comment by nijel** [comment]
I definitely need more opinions here - I don't see many benefits in this, and it is code to write and maintain :-).

**Comment by Geeyun-JY3** [comment]
The current native name of Chinese including Simplified Chinese and Traditional Chinese are not accurate. That is why I open this issue. (BTW, where did you get these languages’ native names?)

Strictly speaking, neither `简体字` nor `正體字`  refers to a language. Either of them refers to a type of Chinese character.
`简体字` refers to the Chinese characters that have undergone simplifications of character "structure" or "body".
`简体字` means Simplified Chinese characters, while `正體字` means Traditional Chinese characters.
I would suggest changing `简体字` to `简体中文` (correspond to `Simplified Chinese` in English), `正體字` to `正體中文`(correspond to `Traditional Chinese` in English).

See also:
- https://en.wikipedia.org/wiki/Simplified_Chinese_characters
- https://en.wikipedia.org/wiki/Traditional_Chinese_characters

If making options for interface language translatable is still undecided, what about changing the native name of Chinese and fixing the [order bug](https://user-images.githubusercontent.com/49396421/162601605-376cb76f-34ec-4e0a-9614-8f265f901db5.png) I mentioned above first?

**Comment by Geeyun-JY3** [comment]
Do not forget to change them in https://github.com/WeblateOrg/website/blob/main/weblate_web/settings.py

**Comment by Geeyun-JY3** [comment]
So is options for [interface language in Weblate itself](https://hosted.weblate.org/accounts/profile/#languages) starting with (up to down)
```
한국어
---------
```
a bug?
![image](https://user-images.githubusercontent.com/49396421/162601605-376cb76f-34ec-4e0a-9614-8f265f901db5.png)

**Comment by Geeyun-JY3** [comment]
Still can reproduce this [bug](https://github.com/WeblateOrg/weblate/issues/7488#issuecomment-1103771358) on Hosted Weblate for now. 
How do I know if a commit in this repo has been deployed on Hosted Weblate?

**Comment by nijel** [comment]
You can see the revision at https://hosted.weblate.org/about/.

The fix was deployed, but it was incomplete. I've made a followup fix now, to be deployed later this week.

**Comment by Geeyun-JY3** [comment]
Any relationship between a commit hash and the revision at https://hosted.weblate.org/about/? I search `g1f88791995` but get nothing.

**Comment by nijel** [comment]
Remove leading `g` 😀

**Comment by Geeyun-JY3** [comment]
Got it (why there is a leading `g`🤔)

**Comment by Geeyun-JY3** [comment]
One last question, why the language sequence of [options for interface language](https://hosted.weblate.org/accounts/profile/#languages) is not completely the same as the source code? For example, Korean is at the top of options.
Is it a bug too? Or intended?

**Comment by nijel** [comment]
It is ordered according to [Unicode Collation Algorithm](https://unicode.org/reports/tr10/).

**Comment by Geeyun-JY3** [comment]
> It is ordered according to [Unicode Collation Algorithm](https://unicode.org/reports/tr10/).

Got it.
