### ISSUE TITLE
"Automatically translated" label got applied to source language strings after running automatic translations for another language

### ISSUE THREAD

**Issue by WofWca** [WeblateOrg/weblate#7504]
### Describe the issue

5 days ago I used [Automatic translation](https://docs.weblate.org/en/latest/user/translating.html?highlight=automatic#automatic-translation) with "Add as translation" for, IIRC, unfinished strings in another language and later noticed that the "Automatically translated" label also got applied to the source (English) language strings, which seems wrong to me.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Did not try again, but apparently:

1. Go to a non-source language that has unfinished strings
2. Tools -> Automatic translation
3. Select "Add as needing edit", "Unfinished strings", "Machine translation".
4. DeepL, Google Translate, LibreTranslate, Microsoft Translator, Weblate Translation Memory
5. "Apply", then wait for it to finish.
6. Go to the source language and see that the "Automatically translated" label got applied to some strings.

### Expected behavior

"Automatically translated" label got applied only to the strings in the language that I used automatic translation for.

### Screenshots

"Automatically translated" label got applied to the strings in the language that I used automatic translation for __and__ to the corresponding strings of the source language.

### How do you run Weblate?

weblate.org service

### Weblate versions

The one that was deployed on hosted.weblate.org 5 days ago.

**Comment by burner1024** [comment]
As I learned the hard way, labels are a property of source strings. Same with explanations.

**Comment by WofWca** [comment]
Oh. That explains it. I guess then we need to ask for per-language labels first? Is #5447 the one?

**Comment by burner1024** [comment]
I don't think that's the one.
All I can say is that seeing "auto translated" label in other languages sure is misleading, and it would be nice to be able to mark translation units individually.

**Comment by nijel** [comment]
This label is applied to the translation only, see for example https://hosted.weblate.org/translate/weblate/documentation/cs/?checksum=c344c14b63623663 and https://hosted.weblate.org/translate/weblate/documentation/en/?checksum=c344c14b63623663.

**Comment by burner1024** [comment]
So labels can be set on translation units without setting them on source units? Certainly doesn't work that way for me.

**Comment by nijel** [comment]
This is currently used only for Automatically translated labels. User labels can be set only for source string.

**Comment by WofWca** [comment]
Then I must have edited the labels after. Should we close then? Or edit? Or close and create a new one?

**Comment by nijel** [comment]
Having a link to the affected strings could help in diagnosing this next time...
