### ISSUE TITLE
Can't delete source units

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#7508]
### Describe the issue

When deleting a source unit, it appears to be successful, but the unit stays.
Same through API and UI.
Here I send two DELETE requests to the same unit, and both responses are 204 = "object was deleted successfully".

```bash
$ time curl -v -H "Authorization: Token X" -X DELETE "http://127.0.0.1:8080/api/units/1576704/"
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> DELETE /api/units/1576704/ HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.68.0
> Accept: */*
> Authorization: Token X
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< Server: nginx
< Date: Mon, 18 Apr 2022 04:55:04 GMT
< Connection: keep-alive
< Vary: Accept, Cookie
< Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
< X-RateLimit-Limit: 5000
< X-RateLimit-Remaining: 4156
< X-RateLimit-Reset: 11
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Referrer-Policy: same-origin
< 
* Connection #0 to host 127.0.0.1 left intact

real	0m6.189s
user	0m0.012s
sys	0m0.000s
$ time curl -v -H "Authorization: Token X" -X DELETE "http://127.0.0.1:8080/api/units/1576704/"
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> DELETE /api/units/1576704/ HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.68.0
> Accept: */*
> Authorization: Token X
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< Server: nginx
< Date: Mon, 18 Apr 2022 05:04:41 GMT
< Connection: keep-alive
< Vary: Accept, Cookie
< Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
< X-RateLimit-Limit: 5000
< X-RateLimit-Remaining: 4591
< X-RateLimit-Reset: 22
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< Referrer-Policy: same-origin
< Cross-Origin-Opener-Policy: same-origin
< 
* Connection #0 to host 127.0.0.1 left intact

```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Send a DELETE request.
2. Send it again.

### Expected behavior

Unit deleted.

### Exception traceback

```pytb
No exceptions in logs, just this

gunicorn stderr | [2022-04-18 05:04:34,070: INFO/306] fallout/rp: skipped push: push on commit disabled
gunicorn stderr | [2022-04-18 05:04:37,580: INFO/306] fallout/rp: checking data/text/po/english.pot (en) [1/10]
gunicorn stderr | [2022-04-18 05:04:40,632: INFO/306] fallout/rp: checking data/text/po/czech.po (czech) [2/10]
gunicorn stderr | [2022-04-18 05:04:40,669: INFO/306] fallout/rp: checking data/text/po/french.po (french) [3/10]
gunicorn stderr | [2022-04-18 05:04:40,704: INFO/306] fallout/rp: checking data/text/po/german.po (german) [4/10]
gunicorn stderr | [2022-04-18 05:04:40,748: INFO/306] fallout/rp: checking data/text/po/hungarian.po (hungarian) [5/10]
gunicorn stderr | [2022-04-18 05:04:40,782: INFO/306] fallout/rp: checking data/text/po/italian.po (italian) [6/10]
gunicorn stderr | [2022-04-18 05:04:40,816: INFO/306] fallout/rp: checking data/text/po/polish.po (polish) [7/10]
gunicorn stderr | [2022-04-18 05:04:40,848: INFO/306] fallout/rp: checking data/text/po/portuguese.po (portuguese) [8/10]
gunicorn stderr | [2022-04-18 05:04:40,875: INFO/306] fallout/rp: checking data/text/po/russian.po (russian) [9/10]
gunicorn stderr | [2022-04-18 05:04:40,914: INFO/306] fallout/rp: checking data/text/po/spanish.po (spanish) [10/10]
gunicorn stderr | [2022-04-18 05:04:40,947: INFO/306] fallout/rp: checking triggered alerts
gunicorn stderr | [2022-04-18 05:04:41,011: INFO/306] fallout/rp: updating completed
gunicorn stderr | [2022-04-18 05:04:41,016: INFO/306] fallout/rp: updating stats caches
celery-celery stderr | [2022-04-18 05:04:41,076: INFO/MainProcess] Task weblate.trans.tasks.update_component_stats[87442d3e-8575-4afd-8389-36a59b92ca3d] received
```

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.10.1
 * Django: 4.0
 * siphashc: 2.1
 * translate-toolkit: 3.5.1
 * lxml: 4.7.1
 * Pillow: 8.4.0
 * bleach: 4.1.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.1.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.13.0
 * oauthlib: 3.1.1
 * django-compressor: 3.1
 * djangorestframework: 3.13.1
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.4.0
 * setuptools: 60.0.4
 * jellyfish: 0.8.9
 * openpyxl: 3.0.9
 * celery: 5.2.1
 * kombu: 5.2.2
 * translation-finder: 2.10
 * weblate-language-data: 2021.7
 * html2text: 2020.1.16
 * pycairo: 1.20.1
 * pygobject: 3.42.0
 * diff-match-patch: 20200713
 * requests: 2.26.0
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.5.1
 * Cython: 0.29.26
 * misaka: 2.1.1
 * GitPython: 3.1.24
 * borgbackup: 1.1.17
 * pyparsing: 3.0.6
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * Python: 3.10.1
 * Git: 2.30.2
 * psycopg2: 2.9.2
 * psycopg2-binary: 2.9.2
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.17.17
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.20.26
 * zeep: 4.1.0
 * aeidon: 1.10.1
 * iniparse: 0.5
 * mysqlclient: 2.1.0
 * Mercurial: 6.0
 * git-svn: 2.30.2
 * git-review: 2.2.0
 * Redis server: 6.2.4
 * PostgreSQL server: 13.3
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: 127.0.0.1
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.13.0-39-generic (x86_64)

**Comment by nijel** [comment]
What is your component configuration? Is the removed string removed from the files?

**Comment by burner1024** [comment]
I have tried this again and it worked properly. Maybe some weird caching issue. I'll add more details if I find a reproducible use case.
