### ISSUE TITLE
Fluent messages aren't being detected

### ISSUE THREAD

**Issue by benjaminwinger** [WeblateOrg/weblate#7510]
### Describe the issue

I'm attempting to set a up a weblate project (https://hosted.weblate.org/projects/portmod/portmod/) which uses Fluent and BCP-style language codes, and it appears to be finding the source localisation file (it can be downloaded through weblate's interface), however no messages are detected and there is an alert saying that the file mask (`l10n/*/main.ftl`) does not match any files.

I also get an Internal Server Error message if I attempt to add new translation languages.

> Server Error
> 
> The server had serious problems serving your request, and this error has been recorded as 71e056ac7f524bd6afabad1b3fce99af. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Expected behavior

I was expecting that upon setting up the project component it would detect all the messages in the base language file and also detect the two existing partial translations.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Translate-toolkit part of the fix: https://github.com/translate/translate/pull/4611

**Comment by benjaminwinger** [comment]
Despite hosted.weblate.org being updated to 4.12 with the fix, I'm still not seeing any change. I'm guessing that there are probably multiple issues.

I've tried deleting and recreating the component, but the situation still appears to be the same as before: there aren't any messages showing up and trying to add a new language produces an error.

**Comment by nijel** [comment]
Yes, there is also syntax issue in your file and the parser breaks on that: https://gitlab.com/portmod/portmod/-/blob/master/l10n/en-GB/main.ftl#L120

Unfortunately, the syntax errors are not well handled in translate-toolkit for Fluent, see https://github.com/translate/translate/issues/4615

**Comment by benjaminwinger** [comment]
Brilliant, it's working now. Thank you very much!
