### ISSUE TITLE
How to change SSH key?

### ISSUE THREAD

**Issue by pavelpikatamcs** [WeblateOrg/weblate#7513]
### Describe the issue

Hi,

Is it possible to rotate/change SSH key displayed in Weblate?
We are using `weblate/weblate:4.8.1-3` docker image

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Docker container

### Weblate versions

weblate/weblate:4.8.1-3

**Comment by nijel** [comment]
There is no UI for this, but it is stored in `data/ssh`. You can remove it and generate new one in the UI - https://docs.weblate.org/en/latest/vcs.html#weblate-ssh-key
