### ISSUE TITLE
Another bot problem

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#7514]
### Describe the issue

Queries suck two CPU cores (200% CPU). I would like to completely block robots from accessing my projects (no indexing needed). How can I edit the robots.txt file?

```
nginx stdout | 172.21.0.4 - - [19/Apr/2022:11:51:46 +0200] "GET /changes/?component=3952276&project=eso-spolszczenie&start_date=2020-12-01&end_date=2020-12-31 HTTP/1.0" 200 16033 "-" "Mozilla/5.0 (compatible; BLEXBot/1.0; +http://webmeup-crawler.com/)"
nginx stdout | 172.21.0.4 - - [19/Apr/2022:11:51:50 +0200] "GET /changes/?component=3952276&project=eso-spolszczenie&start_date=2021-01-01&end_date=2021-01-31 HTTP/1.0" 200 79082 "-" "Mozilla/5.0 (compatible; BLEXBot/1.0; +http://webmeup-crawler.com/)"
nginx stdout | 172.21.0.4 - - [19/Apr/2022:11:51:54 +0200] "GET /changes/?component=3952276&project=eso-spolszczenie&start_date=2021-02-01&end_date=2021-02-28 HTTP/1.0" 200 84605 "-" "Mozilla/5.0 (compatible; BLEXBot/1.0; +http://webmeup-crawler.com/)"
nginx stdout | 172.21.0.4 - - [19/Apr/2022:11:51:58 +0200] "GET /changes/?component=3952276&project=eso-spolszczenie&start_date=2021-03-01&end_date=2021-03-31 HTTP/1.0" 200 79798 "-" "Mozilla/5.0 (compatible; BLEXBot/1.0; +http://webmeup-crawler.com/)"
nginx stdout | 172.21.0.4 - - [19/Apr/2022:11:52:03 +0200] "GET /changes/?component=3952276&project=eso-spolszczenie&start_date=2021-04-01&end_date=2021-04-30 HTTP/1.0" 200 80495 "-" "Mozilla/5.0 (compatible; BLEXBot/1.0; +http://webmeup-crawler.com/)"
nginx stdout | 172.21.0.4 - - [19/Apr/2022:11:52:08 +0200] "GET /changes/?component=3952276&project=eso-spolszczenie&start_date=2021-05-01&end_date=2021-05-31 HTTP/1.0" 200 78260 "-" "Mozilla/5.0 (compatible; BLEXBot/1.0; +http://webmeup-crawler.com/)"
nginx stdout | 172.21.0.4 - - [19/Apr/2022:11:52:12 +0200] "GET /changes/?component=3952276&project=eso-spolszczenie&start_date=2021-06-01&end_date=2021-06-30 HTTP/1.0" 200 80506 "-" "Mozilla/5.0 (compatible; BLEXBot/1.0; +http://webmeup-crawler.com/)"
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Additional context

Docker

**Comment by tomkolp** [comment]
This is not a malicious bot and should apply to your robots. How can I edit the roobots.txt file in docker myself?

**Comment by nijel** [comment]
Create custom `/app/data/python/customize/templates/robots.txt`, see https://docs.weblate.org/en/latest/admin/install/docker.html#further-configuration-customization

**Comment by tomkolp** [comment]
> 

I temporarily blocked all bots.
Before the blockade, eg "SiteCheckerBotCrawler / 1.0 (+ http: //sitechecker.pro)" read /changes/
After being banned, it read robots.txt and stopped reading /changes/

**Comment by tomkolp** [comment]
Weird that robots obey the "block User-agent" entry, not "block /changes/".

Noticed that robots read also /static/, should it be like that?

`nginx stdout | 172.21.0.2 - - [20/Apr/2022:08:27:58 +0200] "GET /static/CACHE/css/output.d784a4e73944.css HTTP/1.0" 200 151125 "https://site.eu/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36 SeoSiteCheckup (https://seositecheckup.com)"
nginx stdout | 172.21.0.2 - - [20/Apr/2022:08:27:58 +0200] "GET /static/state/alert.svg HTTP/1.0" 200 266 "site.eu/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36 SeoSiteCheckup (https://seositecheckup.com)"
nginx stdout | 172.21.0.2 - - [20/Apr/2022:08:27:58 +0200] "GET /static/CACHE/js/output.91ba9ed0a400.js HTTP/1.0" 200 357236 "site.eu/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36 SeoSiteCheckup (https://seositecheckup.com)"
nginx stdout | 172.21.0.2 - - [20/Apr/2022:08:27:58 +0200] "GET /css/custom.css?a075fb12203a9a2 HTTP/1.0" 200 5443 "site.eu/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36 SeoSiteCheckup (https://seositecheckup.com)"
nginx stdout | 172.21.0.2 - - [20/Apr/2022:08:27:58 +0200] "GET /js/i18n/ HTTP/1.0" 200 3343 "site.eu/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36 SeoSiteCheckup (https://seositecheckup.com)"`

**Comment by nijel** [comment]
> It would be nice to have a real ip so I could block it on the firewall.

That should be done since https://github.com/WeblateOrg/docker/issues/1306

> Noticed that robots read also /static/, /matrix/, should it be like that?

Static files are okay, matrix is disallowed since b255385c1c39f21fd11a7a9f0ee61ecc63ab0b45

**Comment by tomkolp** [comment]
For me, the topic has been completed, I created my roobots.txt file and blocked all User-Agents (no search engine indexation). When real IP in the future appears in the future, the default robots.txt restores. As the logs will be real IP check if the IP belongs to a real bot or malicious. At the moment, some bots do not apply to robots.txt and continue to read prohibited folders. After complete prohibiting visits, the user-agent stops visiting folders.

**Comment by tomkolp** [comment]
All bots that do not respect the robots.txt file are malicious. Now, when you can see the ip, they can be easily tracked and blocked.
