### ISSUE TITLE
Component discovery in multimodule android project setup

### ISSUE THREAD

**Issue by warting** [WeblateOrg/weblate#7524]
### Describe the problem

In our project we have lots of modules and new modules is beeing added quickly. 
the original base string resorses is placed in different modules, around the mono repo and we would like to auto discover those base languages automatically.

In the same repo we could have example: 
app/src/main/res/values/strings.xml
app/src/main/res/values/strings_login.xml
libs/map/src/main/res/values/strings_map.xml
libs/settings/configuration/src/main/res/values/strings_configuration.xml
libs/settings/usersettings/src/main/res/values/strings_usersettings.xml
libs/shared/utils/whatever/depth/src/main/res/values/strings_any_path.xml

I dont want to add a dummy translation file in order to make the current component discovery to pick up the string resource.

### Describe the solution you'd like

I would like to have a component discovery so that you could match base language instead of the translated files.

I would like to find all base language files with the patterns with one of the following:
*values/strings*.xml
strings*.xml

(or have a android gradle plugin)

### Describe alternatives you've considered

most other translation tools have some sort of android gradle plugin that discovers all string resourse xml files and syncs them to the translation system

https://github.com/crowdin/github-action
https://github.com/marketplace/actions/onesky-file-uploader
https://github.com/brainly/onesky-gradle-plugin

**Comment by nijel** [comment]
It should be doable with two discovery add-ons installed, each having a different match:

* `(?P<component>.*)/main/res/values-(?P<language>[^/]*)/strings.xml`
* `(?P<component>.*)/main/res/values-(?P<language>[^/]*)/strings-(?P<submodule>.*).xml` and component name `{{ component|title }}: {{ submodule }}`
