### ISSUE TITLE
Branch is pushed but Pull Request ist not created

### ISSUE THREAD

**Issue by raphaelguye** [WeblateOrg/weblate#7539]
### Describe the issue

I have configured Weblate to create Pull Request on my GitHub project.

When I commit / push a change from the weblate interface, the expected branch `weblate-integrate` is well created and pushed on Github, but the PR is **not** automatically created. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Configure weblate with Git and a Push branch

### Expected behavior

The Pull Request is automatically created

### Screenshots

<img width="635" alt="weblate-config" src="https://user-images.githubusercontent.com/1267845/165105226-25c58c52-1510-4691-abdf-9072e6aff1b9.png">

### How do you run Weblate?

weblate.org service

**Comment by comradekingu** [comment]
Did you select pull request for method, and set up a webhook?
Maybe "Age of changes to commit" set to "0" does something to that effect?

**Comment by raphaelguye** [comment]
What do you mean by 
> Did you select pull request for method [...] ?

In the [documentation](https://docs.weblate.org/no/latest/admin/continuous.html#pushing-changes-from-weblate) it says (in the table) to put the **Repository URL** and the **Branch name**.

**Comment by nijel** [comment]
Did you choose [GitHub pull requests](https://docs.weblate.org/no/latest/vcs.html#vcs-github) as VCS integration?

**Comment by raphaelguye** [comment]
> Did you choose [GitHub pull requests](https://docs.weblate.org/no/latest/vcs.html#vcs-github) as VCS integration?

You mean the API credentials (GITHUB_CREDENTIALS) ?
If yes, how to update the `settings.py` on a hosted service ?

**Comment by nijel** [comment]
This:

![image](https://user-images.githubusercontent.com/212189/165291056-b9f383f9-6a3c-40dd-b4bc-225c8e9aa8ba.png)

**Comment by raphaelguye** [comment]
@nijel :
What's the content of your settings.py to have this `GitHub pull request` entry ?

**Comment by nijel** [comment]
We have configured https://docs.weblate.org/no/latest/admin/config.html#std-setting-GITHUB_CREDENTIALS. For Docker it's exposed in environment as well: https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_GITHUB_USERNAME

**Comment by raphaelguye** [comment]
Fixed by configuring [WEBLATE_GITHUB_USERNAME](https://docs.weblate.org/no/latest/admin/install/docker.html#envvar-WEBLATE_GITHUB_USERNAME) and WEBLATE_GITHUB_TOKEN in our settings.py config file (docker instance)
