### ISSUE TITLE
Alternative translations

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#7546]
### Describe the problem

In some situations, it is useful to have multiple translations per string. 

For example, when translating a database of terms, some might have multiple translations into the target language.

We ran this with a medical application:

```csv
Stomach ache (finding), douleur à l'estomac
Stomach ache (finding), douleur gastrique
```

### Describe the solution you'd like

* Support limited to CSV file format
* The translate-toolkit needs to be adjust as well

**Comment by burner1024** [comment]
isn't that what variants are for?

**Comment by nijel** [comment]
Variants are at the source string level, while this is for translations - single source string can have multiple translations.

**Comment by burner1024** [comment]
Still, when using the resulting translation in the app, you have to pick one or another translation in one or other usage instance, which means some kind of context. Which is what "manage strings"/context/variants provide.

(I'm just kind of afraid that if variants don't get much usage, they might get deprecated in future, and that'd be very unpleasant for us)

**Comment by nijel** [comment]
Don't worry about depreciating variants, that's not something we consider.

But this is really different, the use case is translating databases which are used for looking up IDs by the name. In this case, all translations are equal (unlike in variants where there is some differentiating factor).

Example of such database can be SNOMED, see https://browser.ihtsdotools.org/?perspective=full&conceptId1=22298006&edition=MAIN/2022-04-30&release=&languages=en
