### ISSUE TITLE
Unable to add term to second glossary while editing translations for a component.

### ISSUE THREAD

**Issue by Oblomov** [WeblateOrg/weblate#7549]
### Describe the issue

Hello,

I have been working on the translations for the [«Game: NodeCore» module in the MineTest project](https://hosted.weblate.org/projects/minetest/nodecore/it/). The project has two glossary modules: a project-wide «MineTest Glossary», and a module-specific «NodeCore Glossary». The latter was added recently, manually, is configured to be editable and I can contribute to it directly adding terms while working on the glossary-nodecore module itself.

The issue happens when I try to use the 'Add term to glossary' feature while working on a different component: in this case, if I try to add a term to the glossary on the fly, the only option offered from the drop-down menu to select the glossary to contribute to is the MineTest glossary.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Steps to reproduce (thanks also @comradekingu that helped me pinpoint the issue on IRC):

1. visit https://hosted.weblate.org/translate/minetest/nodecore/it/?offset=1&q=mattock&sort_by=-priority%2Cposition&checksum=
2. observe that the "Glossary" window in the top-right corner of the interface shows suggestions from the NodeCore Glossary component (including the possibility to edit them).
3. click on the «⊕ Add term to glossary» green link in the Glossary window
4. in the pop-up window titled “Add term to glossary”, open the pull-down “Glossary” menu.
5. only MineTest Glossary is available as option.

### Expected behavior

The “NodeCore Glossary” should be among the options for pull-down “Glossary” menu, but it is not, despite this second glossary being otherwise as accessible and editable as the primary one.

### How do you run Weblate?

weblate.org service

**Comment by comradekingu** [comment]
The use-case for this is if a word is specific to only one component,
or differs between components.

**Comment by nijel** [comment]
This is caused by the glossary component configuration - it is configured as monolingual, what makes it impossible to add strings to individual languages.

**Comment by Oblomov** [comment]
Interesting, thanks. I thought it would allow adding a string to the original language (with the given language-specific translation). We've recreated the glossary without the monolingual flag and it seems to be working.
