### ISSUE TITLE
Protected branch on Github for SSH repositories

### ISSUE THREAD

**Issue by raphaelguye** [WeblateOrg/weblate#7561]
### Describe the issue

We have a protected branch on our Github repository where we try to push changes from Weblate.

The authorisation from Github have been configured using [SSH](https://docs.weblate.org/no/latest/vcs.html#ssh-repositories). It's working when I try to push on a branch not protected.

I also tried to add the [GitHub Weblate App](https://github.com/apps/weblate) by allowing only the repository weblate need. Not sure this step is mandatory.

On the branch protection rules page of Github, I'm not able to add the weblate user into the people who can dismiss pull request reviews, following the [official documentation](https://docs.weblate.org/no/latest/admin/continuous.html#protected-branches):
<img width="400" alt="image" src="https://user-images.githubusercontent.com/1267845/165906640-2ab9675d-1ba2-458a-9a9b-eff0c632e901.png">

Probably because there is no "weblate users" added to the team members.

So my question is: how should I configure the protected branch to allow push from weblate ?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Add the weblate ssh public key into your Github configuration
2. Configure the Weblate Github App
3. Configure Weblate VCS
4. On Github, protect your target branch to require pull requests
5. Try to allow the weblate user to by pass the pull requests

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
You probably need to create dedicated user for pushing in this case (this is what we do with our hosted service, there is @weblate user for that).

**Comment by raphaelguye** [comment]
Thanks @nijel  for your proposal, effectively it's working if I create a dedicated user.

But it means I have to use [https authentication](https://docs.weblate.org/en/weblate-4.10.1/vcs.html#https-repositories) rather than ssh. There is no way to make it work with ssh, right ?

**Comment by raphaelguye** [comment]
Another problem, we have configured in GitHub several status checks:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/1267845/165947398-8a6380e1-d5b3-425c-8990-60b1abd89db4.png">

Do you know if there is a way to bypass it?
For the moment I get the error message
```
remote: error: GH006: Protected branch update failed for refs/heads/develop.        
remote: error: 3 of 3 required status checks are expected.  
```

**Comment by raphaelguye** [comment]
After more tests, it seems that it doesn't work 🤷‍♂️

So I would say that : **On Github, branches protected by a pull request restriction can't be bypass when you increase your restrictions with some status checks**.

I have created a [Pull Request](https://github.com/github/docs/pull/17535#issuecomment-1114585431) to update the official Github documentation.

**Comment by nijel** [comment]
Maybe it would be better to push to a fork and create a merge request. Merging will then happen once all CI passes... This is what we do on this repo, merging of the translation requests is automated by https://kodiakhq.com/ (maybe it's possible natively by GitHub now, this workflow was created before auto-merge was available).
