### ISSUE TITLE
Weblate registered default user permissions

### ISSUE THREAD

**Issue by VygantasVoltasIT** [WeblateOrg/weblate#7566]
### Describe the issue

Is there a way how can we restrict newly registered user to disallow to delete other users translation suggestions? After a good 5 hours of research, I haven't found anything in the internet nor documentation how to solve this issue.
I've enabled suggestions and suggestions voting, but I can't seem to find which user can do what. Maybe there is some kind of a default registered users roles configuration?

I am running Weblate version 4.12.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Docker container

### Weblate versions

4.12

**Comment by nijel** [comment]
Each user is by default member of the "Users" group. To change the privileges, either change the group (see https://docs.weblate.org/en/latest/admin/access.html#site-wide-permission-management) or change the automatic assignment rules (see https://docs.weblate.org/en/latest/admin/access.html#automatic-group-assignments).

**Comment by burner1024** [comment]
@nijel what do you mean by "change the group"?
As far as I can see, there's no option to change anything, Weblate's built-in groups and roles are set in stone.
![Captura de pantalla de 2022-05-05 23-53-36](https://user-images.githubusercontent.com/1279852/166973847-1bc13de7-74c6-4ebd-b72c-81cb7f981204.png)
![Captura de pantalla de 2022-05-05 23-53-43](https://user-images.githubusercontent.com/1279852/166973855-42243002-4158-457c-a064-b2ddf4130d29.png)

**Comment by VygantasVoltasIT** [comment]
@burner1024 I've figured it out. If you want to change the default functionality, you will need to create a custom role and group and in the group edit page in Django interface there will be an option called "Automatic group assignments"

<img width="313" alt="image" src="https://user-images.githubusercontent.com/104633180/167078902-78ef5100-0ce7-4a3a-9c82-08dd2d1bf15b.png">

The default, built-in groups and roles cannot be changed through Django interface, but you can remove those directly through the database although it is not recommended according to the Weblate documentation. What you might want to change - Automatic group assignments. There are two default groups assigned to every new user - Viewers and Users. The Viewers group doesn't contain any roles, but I can speculate that they have it hardcoded in to the code. The other group - Users contains single role - Power User. It gives users a little much out of the box so you can remove the role through the database.

**Comment by mig5** [comment]
@VygantasVoltasIT you might be interested to know that in Weblate 4.14.1, there's a new 'Groups' management interface in the Weblate (not Django) admin area. You are able to modify which roles are attached to the default 'Users' and 'Viewers' group, and you can also modify or delete the Automatic Assignments from that group. No more hacking around in the db!

See https://github.com/WeblateOrg/weblate/issues/7602 and the commit https://github.com/WeblateOrg/weblate/commit/8226de5b58f984750de845dab875ee65ce906f0b
