### ISSUE TITLE
Language naming (display name) became inconsistent

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#7577]
### Describe the issue

With weblate 4.11 we are observing inconsistent language naming. Especially, for italian it has been discovered that `it` and `it_CH` leads to the same display name "Italian" what is puzzling the translators, since the displayname does not indicate anymore what language is meant. (still, the URL does encode `it` or `it_ch` in it).

![image](https://user-images.githubusercontent.com/8058166/166205285-d95866ec-4f47-46da-9fd9-bbd119b381ea.png)

Regarding italian, this is a specific problem.

Furthermore, there are other inconsistencies as shown in the screen shot.

E.g. German
- German (de_DE)
- Swiss High German

Why not to name it according same pattern as e.g. German (de_DE), German (de_CH), etc.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Expected behavior

Clearly distinguish `it` and `it_CH` (may also apply to other languages) in its display name.

### Screenshots

see above

### Exception traceback

```pytb
none
```

### How do you run Weblate?

Docker container

### Weblate versions

official image from https://hub.docker.com/layers/weblate/weblate/weblate/4.11.2-1/images/sha256-4666c5d4cb191bad25fd22e1a78ecc5118d87f47eb2dca4bad6a992edb34f11d?context=explore

### Weblate deploy checks

```shell
n/a
```

### Additional context

n/a

**Comment by nijel** [comment]
This language has proper long name since https://github.com/WeblateOrg/language-data/commit/75e61eb836e1141948e41469a5e79062461bdea6:

https://github.com/WeblateOrg/language-data/blob/afbbecf1274db3715a45d5f315b2607002aadd6a/languages.csv#L265

The question is why it is not applied in your case. Do you have `UPDATE_LANGUAGES` disabled? In that case, the language definitions will get out of sync with the code, and it will not include the language code in name of the language which has verbose name in Weblate.

**Comment by rhofer** [comment]
Just checked: `WEBLATE_UPDATE_LANGUAGES` is not set. Hence, default should apply (`true`).

I will do Weblate 4.12 upgrade this evening. Let's see, wheter it is still there.

Could it help to provoke the command `weblate setuplang` ?

**Comment by rhofer** [comment]
@nijel I just updated on staging from 4.11 to 4.12. The problem still was there. But after executing `weblate setuplang` manually on console, the problem was solved.

Could it be, that during upgrade in the migration job(s) the `... setuplang` is not or not properly executed?

**Comment by nijel** [comment]
Just looked into that: It is executed, but with a flag prohibiting updating existing languages (same as `setuplang --no-update`). This was intentionally to avoid overwriting user changes on languages. On the other side, this breaks in situations like this one...

**Comment by rhofer** [comment]
Thanks, got it. Then it might be better to add a flag to the languages itself stating whether it is customized or not. This would allow to update with `setuplang --exclude-customized` , or something like this ... just my thoughts :-)

**Comment by nijel** [comment]
On the other side, this logic was introduced prior to `UPDATE_LANGUAGES` setting existed. With that, it might be better to simply update all languages unless `UPDATE_LANGUAGES` is disabled....

**Comment by rhofer** [comment]
Yes, agree. Especially if you want to stick to this "black or white" decision. ... or `UPDATE_LANGUAGES` to become multistate:
- none
- standard only
- all
... but it makes it definitely more complicated.

I'd leave it to your risk assessment :-) .
