### ISSUE TITLE
Add tests for `<link rel="(next|prev)`

### ISSUE THREAD

**Issue by WofWca** [WeblateOrg/weblate#7584]
### Describe the problem

There are no tests for #7558, #7573.

### Describe the solution you'd like

Add tests for this. But I'm not sure where to put them. Can you give an advice?

**Comment by nijel** [comment]
The translation editor is tested in `weblate/trans/tests/test_edit.py`. For #7573 probabl in the tests for individual views where link should be visible.

**Comment by enrique9318** [comment]
Hi, can I help on this? is there any additional info that I might need before starting?

**Comment by WofWca** [comment]
Oh. That `<link>` is actually gone now 🦀🦀
