### ISSUE TITLE
Pull github error 504

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#7590]
### Describe the issue

I'm getting "504 error" while fetching changes from github repository. The download of changes is aborted. Reusing "pull" does not detect changes. Only after I made a change to the repository, the download of changes was resumed.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

Docker container

### Weblate versions

Docker
<html>
<body>

4.12-dev — 28bf9caeec324d8d9cb3437aa1586e18992f45a9
--

</body>
</html>4.12-dev — [28bf9caeec324d8d9cb3437aa1586e18992f45a9](https://github.com/WeblateOrg/weblate/commits/28bf9caeec324d8d9cb3437aa1586e18992f45a9)

[sentry link](https://sentry.io/share/issue/4105455a42f344bd8fe86d742e7177f1/)

**Comment by nijel** [comment]
That's an error from GitHub, i doubt it has anything to do with Weblate

**Comment by tomkolp** [comment]
This is my first time since I have used a weblate. If it's githube's fault, I close the topic.
