### ISSUE TITLE
ImportError: cannot import name

### ISSUE THREAD

**Issue by Justman10000** [WeblateOrg/weblate#7592]
### Describe the issue

Hi, I wanted to set up Weblate again, but now this comes up:

> ImportError: cannot import name 'add_breadcrumb' from partially initialized module 'weblate.utils.errors' (most likely due to a circular import) (/usr/local/lib/python3.9/dist-packages/weblate/utils/errors.py)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Git checkout

**Comment by nijel** [comment]
There is most likely additional error before this one which will be the root cause.

**Comment by Justman10000** [comment]
> There is most likely additional error before this one which will be the root cause.

Yes, [here](https://pastebin.com/8K3Wcnt9) is the full...

**Comment by nijel** [comment]
You didn't create settings, see https://docs.weblate.org/en/latest/admin/install.html#adjusting-configuration

**Comment by Justman10000** [comment]
> You didn't create settings, see https://docs.weblate.org/en/latest/admin/install.html#adjusting-configuration

Yes, I did... That's why

**Comment by Justman10000** [comment]
> You didn't create settings, see https://docs.weblate.org/en/latest/admin/install.html#adjusting-configuration

Ah, when I ran it in the env it worked! However, now I have this problem:
![grafik](https://user-images.githubusercontent.com/49990629/168379668-4b84b414-1aa7-46f9-897b-0164be64b50c.png)

**Comment by Justman10000** [comment]
@nijel

**Comment by nijel** [comment]
Maybe the wsgi process is not running? Check the logs (and describe how you run Weblate).
