### ISSUE TITLE
Not all URLs in release information are clickable

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#7597]
### Describe the issue

Just a minor issue and it doesn't affect Weblate itself:

Some of the URLs in the release information are not converted into proper links and thus must be copy&pasted into the browser
e.g. to look up the closed milestones for a release.

See Screenshot for the 4.11. release, since it contains two examples:
![grafik](https://user-images.githubusercontent.com/3872576/166921894-e98751e0-e275-4926-b833-251a48767b68.png)
Probably because there is `code and maybe other __markup__ around the <http://somewhere.net>` URL

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

**Comment by nijel** [comment]
Where do you see that? It is correct at https://docs.weblate.org/en/latest/changes.html

**Comment by luebbe** [comment]
Here: https://github.com/WeblateOrg/weblate/releases
