### ISSUE TITLE
Translation unit disappearing if it was edited before first push

### ISSUE THREAD

**Issue by antonkomarev** [WeblateOrg/weblate#7606]
### Describe the issue

If you are creating new translation unit and modifying it before the pushing to the repo, then after push it will disappear and will re-appear only after maintenance reset will be performed. This may lead to create duplicated keys.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

This behavior only reproduce if you are using external Git repository for translations.

1. Open page https://weblate.example/projects/project/component/en/#new
2. Create translation unit `test_key` with value `test_key`
3. Open page with translation unit editing https://weblate.example/translate/project/component/en/
4. Edit translation of key to `test_key2` and click `Save and continue` or `Save and stay`
5. Open repository maintenance page: https://weblate.example/projects/project/component/en/#repository
6. Click Commit & Push changes
7. Open page with translation unit editing again https://weblate.example/translate/project/component/en/
    7.1. Translation unit is missing
8. Open repository maintenance page again: https://weblate.example/projects/project/component/en/#repository
9. Click Maintenance > Reset
10. Open page with translation unit editing again https://weblate.example/translate/project/component/en/
    10.1. Translation unit is present

### Expected behavior

Translation unit is present

### Screenshots

https://user-images.githubusercontent.com/1849174/167115497-c636c932-f471-4559-bd34-b296a38ee168.mov

### How do you run Weblate?

Docker container

### Weblate versions

Weblate 4.11.2

### Additional context

There is no issue if you push changes before the editing translation value.

**Comment by nijel** [comment]
This might be related to https://github.com/WeblateOrg/weblate/issues/4953 - the string is added with different key than what Weblate expects.
