### ISSUE TITLE
docs: "Installing from sources" duplicated steps

### ISSUE THREAD

**Issue by WofWca** [WeblateOrg/weblate#7607]
### Describe the issue

https://docs.weblate.org/en/latest/admin/install/source.html#installing-from-sources

It says

> Please follow the installation instructions for your system first:

but on the linked pages it looks like it lists the full instructions and not some intermediate steps, which makes it look like you have to set up two instances of Weblate, because you have to follow https://docs.weblate.org/en/latest/admin/install/source.html#installing-from-sources after following OS-specific instructions.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Expected behavior

Perhaps the OS-specific links are supposed to just show how to install dependencies and `virtualenv`?

### How do you run Weblate?

Git checkout

**Comment by nijel** [comment]
The intention is that you first install Weblate from a package and then upgrade it to the Git checkout in the next step. The prior Weblate installation using pip is harmless, as it's upgraded later.
