### ISSUE TITLE
Extended file mask definition feature and Placeholders support

### ISSUE THREAD

**Issue by silopolis** [WeblateOrg/weblate#7614]
### Describe the problem

The only field and '*' for language code available for defining po files mask is a little limited.
To give our example, for the [LinuxCNC project](https://github.com/linuxcnc/LinuxCNC) we are migrating to po4a and WebLate, and are getting less comfortable handling 200k lines pot/po files. We manage both  *NIX man pages and documentation in AsciiDoc format, and are considering splitting our translation files at directory or even file level. For this we would better be able to put the pot/po files in similar hierarchies under a common folder. Something like `docs/po/$LANG/**/$SRC_FILENAME.po`.

For other projects, less structured, being able to define an arbitrary number of paths/masks should certainly be helpful.

### Describe the solution you'd like

It'd be nice to have extended  wildcard (with globstar - **) and pattern matching support, as well as being able to create many masks.

Best would be to also support placeholders like those found in Crowdin:

* %language% | Language name (e.g. Ukrainian)
* %two_letters_code% | Language code ISO 639-1 (i.e. uk)
* %three_letters_code% | Language code ISO 639-2/T (i.e. ukr)
* %locale% | Locale (like uk-UA)
* %locale_with_underscore% | Locale (i.e. uk_UA)
* %android_code% | Android Locale identifier used to name "values-" directories
* %osx_code% | OS X Locale identifier used to name ".lproj" directories
* %osx_locale% | OS X Locale used to name translated resources (i.e. uk, zh-Hans, zh_HK)
* %original_file_name% | Original file name
* %file_name% | File name without extension
* %file_extension% | Original file extension
* %original_path% | Use parent folders' names in your project to build the file path in the resulting archive

But maybe that last one is for another request

**Comment by nijel** [comment]
One component in Weblate has a single translation file, so the file mask is correct. You will need multiple components for multiple files. This can be automated by https://docs.weblate.org/en/latest/admin/addons.html#component-discovery
