### ISSUE TITLE
Removal of stale source strings, leftovers

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#7619]
### Describe the issue

[Ref](https://github.com/WeblateOrg/weblate/discussions/7511). Doesn't look like it works properly.
I have a singleton variant now: [here](https://hive.bgforge.net/search/?offset=1&q=has%3Avariant+AND+language%3Aen&sort_by=-priority%2Cposition&checksum=), first string.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Follow the link.

### Expected behavior

Variants cleaned up after deletion.

### How do you run Weblate?

Docker container

### Weblate versions

Standard 4.12.1

### Weblate deploy checks

```shell
all good
```

**Comment by nijel** [comment]
All strings listed in the search have at least one translation, so I don't see an issue there...

**Comment by burner1024** [comment]
Sorry, what does it have to do with translation?
Here's the [string](https://hive.bgforge.net/translate/fallout/fo2tweaks/en/?checksum=667458f42c986262&q=has%3Avariant+AND+language%3Aen&sort_by=-priority%2Cposition). It shows up in `has:variant` search. Where is its variant?
