### ISSUE TITLE
Colour blind theme

### ISSUE THREAD

**Issue by sanketgarade** [WeblateOrg/weblate#7623]
### Describe the problem

I am partially colour blind with red-green colours. So I find it difficult to gauge the completeness of a project based on the thin and long red-green band that is used for the same.

### Describe the solution you'd like

Just want to suggest, if possible, to develop a colour-blind friendly theme as an option for users like me. 

### Additional context

I am creating this feature request on GitHub as guided by your customer care whom I had initially contacted.

**Comment by nijel** [comment]
Would something like this work for you?

![obrazek](https://user-images.githubusercontent.com/212189/168016537-bb8873ec-0085-4f7d-96ef-a13fe356a2ae.png)

I'm open to other suggestions how to improve this.

**Comment by sanketgarade** [comment]
Yes looks ok. Another thing that i think can be improved is by putting a distinctly identifiable element (like a thick line or something) on the border where the red and green colours meet.
