### ISSUE TITLE
Automatic translation not working (Machine translation)

### ISSUE THREAD

**Issue by borisBelloc** [WeblateOrg/weblate#7631]
### Describe the issue

Hello, 👋

We host a Weblate to manage our translations (Weblate 4.4.2).

I'm trying to do automatic translation via [machine translation](https://docs.weblate.org/no/latest/admin/machine.html#machine-translation) but nothing happens.

-------------------

I made a test components set with English and French language.
English is main language and English is 100% completed.

My component got 4 strings (1 manually translated to french and 3 needing translation).

Objective : I try to use automatic translation for the French language.

On our project we got 2 activated machines translation :
- Weblate
- Weblate translation memory

Tool > Automatic translation
Traduction mode : Add as to check 
Filter : String not translated

I then select Weblate and/or Weblate translation memory (screen1)
Progress bar.... then green message (screen2) :  **Machine translation finished, no strings have been modified**

What am I doing wrong ?
Thanks for help 

### Screenshots

Screen1 : 
![image](https://user-images.githubusercontent.com/37147299/168083627-79dabe2e-e74e-4021-afba-39e44edf6a4f.png)

Screen2 : 
![image](https://user-images.githubusercontent.com/37147299/168084716-746fa342-a25a-4531-9cdb-a7c6d27917d0.png)

### Weblate versions

Weblate 4.4.2

![image](https://user-images.githubusercontent.com/37147299/168085549-91839a24-40b4-46f0-b8d6-9ed62b489897.png)

**Comment by nijel** [comment]
These translate based on existing strings in Weblate. See https://docs.weblate.org/en/latest/admin/machine.html#weblate

**Comment by borisBelloc** [comment]
Hi,
Thank for the link, I did read it before but there is not much information : 
```
Weblate can be the source of machine translations as well. It is based on the Woosh fulltext engine, and provides both exact and inexact matches.

```
I thought "machine translation" mean "automatic translation" as when you go to translate.google and automaticaly translate a text from one language to another

is it impossible to use "automatic translation" within weblate or is it possible but not with "weblate" and "Weblate translation memory" ?

**Comment by nijel** [comment]
I will clarify the docs to better explain this.
