### ISSUE TITLE
"Prefill translation with source" addon does not work

### ISSUE THREAD

**Issue by antonkomarev** [WeblateOrg/weblate#7633]
### Describe the issue

I think I've tried all possible ways, addon seems to be broken... or I'm missing something?

> All untranslated strings in the component will be filled with the source string, and marked as needing edit. Use this when you can not have empty strings in the translation files.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Enable addon:
<img width="786" alt="Screenshot 2022-05-12 at 22 50 33" src="https://user-images.githubusercontent.com/1849174/168156890-73bc2caa-93ba-4cd3-91fd-a43c61dbcd6b.png">

2. Try to add English (origin) translation
- There is no way to add new translation strings without filling translation (textarea is required):
<img width="786" alt="Screenshot 2022-05-12 at 22 51 31" src="https://user-images.githubusercontent.com/1849174/168156999-76c12e2b-b5e6-472a-a2f2-700c0643b207.png">
 
4. Try to create translation string with any not empty value and erase it later (update translation stirng with empty value)
- Nothing happens (string is empty, no "Needs editing" flag set)

6. Try to add new translation key from the API
- You cannot add translation string without `value` (400 error)
- You cannot add translation string with `value = null` (400 error)
- You cannot add translation string with `value = ''` (400 error)
- Translation string with empty array `value = []` just adds new translation with empty value, but without "Needs editing" flag and empty translation.

### Expected behavior

After enabling addon I can add translation strings with empty value. Translation will be added with `value = key` and with flag "Needs editing".

### How do you run Weblate?

Docker container

### Weblate versions

Weblate 4.11.2

**Comment by antonkomarev** [comment]
It looks like I've misunderstood this feature.
I thought that you can create only key `example.key` in English and value will be automatically same `example.key`. And it will be marked with "Needs editing" flag. Like this:
<img width="786" alt="Screenshot 2022-05-13 at 08 16 13" src="https://user-images.githubusercontent.com/1849174/168215818-71606ebe-7db8-486f-b551-e6059b877aca.png">

But it creates keys + values from source language in all secondary languages and adds "Needs editing" flags in them.

**Comment by nijel** [comment]
It fills translation with the source string, not the source string with context/key, so it works as intended.
