### ISSUE TITLE
UnicodeEncodeError: Weblate tries to encode in MAC Latin-2 instead of UTF-8

### ISSUE THREAD

**Issue by endervad** [WeblateOrg/weblate#7641]
### Describe the issue

When trying to commit, push, or download certain translation file, Weblate throws an `UnicodeEncodeError` error. The translation file itself is in UTF-8. According to the error message Weblate tries to encode it as MAC Latin-2.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

* Commit or push when there are changes in this file.
or
* Download this translation

### Expected behavior

* Commit/push is successful
or
* Translation file is successfully downloaded

### Exception traceback

```pytb
UnicodeEncodeError at /download/ffxiv-translation/quest-005-manfst206_00509/
'charmap' codec can't encode characters in position 247-252: character maps to <undefined>
Request Method:	GET
Request URL:	https://host6450.hnt.ru/download/ffxiv-translation/quest-005-manfst206_00509/?format=zip
Django Version:	4.0.4
Exception Type:	UnicodeEncodeError
Exception Value:	
'charmap' codec can't encode characters in position 247-252: character maps to <undefined>
Exception Location:	/usr/local/lib/python3.10/encodings/mac_latin2.py, line 17, in encode
Python Executable:	/usr/local/bin/python
Python Version:	3.10.4
Python Path:	
['/',
 '/usr/local/lib/python3.10/site-packages/git/ext/gitdb',
 '/',
 '/usr/local/bin',
 '/usr/local/lib/python310.zip',
 '/usr/local/lib/python3.10',
 '/usr/local/lib/python3.10/lib-dynload',
 '/usr/local/lib/python3.10/site-packages',
 '/app/data/python',
 '/usr/local/lib/python3.10/site-packages/gitdb/ext/smmap']
Server time:	Sat, 14 May 2022 16:09:58 +0300
Unicode error hint
The string that could not be encoded/decoded was: <tab>Момоди гото

Full exception e-mail is in "Additional context" since it's very large.
```

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.12.1
 * Django: 4.0.4
 * siphashc: 2.1
 * translate-toolkit: 3.6.1
 * lxml: 4.7.1
 * Pillow: 9.1.0
 * bleach: 5.0.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.2.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.0
 * django-compressor: 4.0
 * djangorestframework: 3.13.1
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.6.0
 * jellyfish: 0.9.0
 * openpyxl: 3.0.9
 * celery: 5.2.6
 * kombu: 5.2.4
 * translation-finder: 2.12
 * weblate-language-data: 2022.2
 * html2text: 2020.1.16
 * pycairo: 1.21.0
 * pygobject: 3.42.1
 * diff-match-patch: 20200713
 * requests: 2.27.1
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.5.10
 * Cython: 0.29.28
 * misaka: 2.1.1
 * GitPython: 3.1.27
 * borgbackup: 1.2.0
 * pyparsing: 3.0.8
 * pyahocorasick: 1.4.4
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.0.12
 * Python: 3.10.4
 * Git: 2.30.2
 * psycopg2: 2.9.3
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.22.3
 * zeep: 4.1.0
 * aeidon: 1.11
 * iniparse: 0.5
 * mysqlclient: 2.1.0
 * Mercurial: 6.1.1
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 6.2.7
 * PostgreSQL server: 13.6
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.gmail.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.10.102.1-microsoft-standard-WSL2 (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.12.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.12.1/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 4.12.2.
        HINT: https://docs.weblate.org/en/weblate-4.12.1/admin/upgrade.html

System check identified 3 issues (1 silenced).
```

### Additional context

Full exception e-mail:
[[Weblate] ERROR (EXTERNAL IP)_ Internal Server Error_ _download_ffxiv-translation_quest-005-manfst206_00509_.zip](https://github.com/WeblateOrg/weblate/files/8693062/Weblate.ERROR.EXTERNAL.IP._.Internal.Server.Error_._download_ffxiv-translation_quest-005-manfst206_00509_.zip)

I would've pulled the problematic file directly from the container but since I couldn't find from the location of edited file, I've crafted one myself. Error occurs on `ru.csv` file:
[quest-005-manfst206_00509.zip](https://github.com/WeblateOrg/weblate/files/8693040/quest-005-manfst206_00509.zip)

Also I see that a new version of Weblate is available, however it's not up for Docker yet.
```
> docker pull weblate/weblate
Using default tag: latest
latest: Pulling from weblate/weblate
Digest: sha256:fd350991806cdac22dd41732916a4bdd72c9c8d6404f5691ed8f8e6113cad146
Status: Image is up to date for weblate/weblate:latest
docker.io/weblate/weblate:latest
```

**Comment by endervad** [comment]
This issue did not reproduce when I:
* deleted RU translation on Weblate
* recreated it back (this way it's empty and doesn't contain non-ASCII characters anymore)
* uploaded my crafted `ru.csv` file with "Replace existing translation file" option
I couldn't upload and replace the file without deleting translation first since I've been getting encoding error again.

**Comment by nijel** [comment]
Might be another incarnation of https://github.com/Ousret/charset_normalizer/issues/174

**Comment by nijel** [comment]
I could not reproduce this with your file. The problem would be in the existing file in Weblate, not in the one you are uploading.

PS: Newer Docker image is being built now (we had some issues in our CI). You can also use `weblate/weblate:edge` meanwhile. But I don't think there are any changes which might address this.

**Comment by endervad** [comment]
That's what I figured too since this file worked fine when I uploaded it to Weblate. How can I take the file from Weblate then if downloading doesn't work?

**Comment by nijel** [comment]
You can copy it from the data volume (for example, in `/var/lib/docker/volumes/weblate_weblate-data/_data/vcs/<PROJECT>/<COMPONENT>/...`).

**Comment by endervad** [comment]
That's what I've tried but the file was unedited there, identical to the one on remote VCS.

**Comment by nijel** [comment]
Anyway, I'm going to address this by option to avoid autodetection.

Still, if you can share the original file, we might investigate that and fix it in the charset_normalizer.

**Comment by endervad** [comment]
> The file should exist upon creating language in Weblate (either it should be present in both repository and Weblate or in neither of them). Are you sure you are looking at the correct location?

If there are no other places other than `vcs` folder then yes, I'm sure. Maybe it's because I've disabled push on commit? I can post component config if necessary.
