### ISSUE TITLE
Export file *.properties as unicode ?

### ISSUE THREAD

**Issue by borisBelloc** [WeblateOrg/weblate#7654]
### Describe the issue

Hello,

Is it possible to make weblate automaticaly transform specials characters to unicode when you "download translation file as zip" ?
(exemple : \u05E7\u05D5\u05D1\u05E5 ) 

When I download my files, I have text in hebrew and I would like to have only unicode : 
(I have the left screen and I would like to have the right screen)

![image](https://user-images.githubusercontent.com/37147299/168793941-20187888-dacd-43e4-aa5c-6890a9ac24c2.png)

My project settings are :

File format : Properties Java (UTF-8)
![image](https://user-images.githubusercontent.com/37147299/168794217-dd32f01a-03cc-43e0-8c0f-cbc7747a100e.png)

I tried to search on the doc and found no information 🤔
thanks for your time

### Weblate versions

Weblate 4.4.2

**Comment by nijel** [comment]
Weblate should save it this way.

- Were strings edited in Weblate or the file existed before?
- Can you try upgrading Weblate? This may have been fixed meanwhile.

**Comment by borisBelloc** [comment]
Hello, thank you for your help.

> Were strings edited in Weblate or the file existed before?

The file was obtained by export from an other weblate project.
Some key were then removed with a JAVA Script then the file was used to create a "new project" inside weblate

![image](https://user-images.githubusercontent.com/37147299/168980584-d82c1fd6-de63-4a06-a45f-0ccf9b7dc55b.png)


> Can you try upgrading Weblate? This may have been fixed meanwhile.

I will see if this is possible

**Comment by borisBelloc** [comment]
hi

> Can you try upgrading Weblate?

We installed weblate 4.5 and when doing the migration we got this error message : 

![image](https://user-images.githubusercontent.com/37147299/168997954-e7c44760-9107-44b3-8fa1-1d5218460e34.png)

When we tried 4.4.2 to 4.6, we also got an error message when trying to migrate : 

![image](https://user-images.githubusercontent.com/37147299/168998107-fa9f6b15-cf6e-47ec-b511-9e860d3e8458.png)


🤔

**Comment by nijel** [comment]
You apparently did something with migrations on top of what is provided by Weblate. The best approach would be to migrate back to what was shipped with Weblate and then upgrade.

**Comment by borisBelloc** [comment]
ok thanks, we will try to fix it, 
no idea what may have been modified, we will search.

**Comment by borisBelloc** [comment]
> Were strings edited in Weblate or the file existed before?

I wanted to see if there is the the same problem when everything is 100% from weblate (no import).

I made a new project inside weblate. (start from 0)

* File format : Properties Java (UTF-8)
![image](https://user-images.githubusercontent.com/37147299/169299881-14114696-833e-41cb-b4b7-f9ceaf3ebe22.png)
* manualy added a key inside English with it's translation 
![image](https://user-images.githubusercontent.com/37147299/169298343-e353c238-3afa-48fa-8ecb-1ed021eee7fa.png)
* added Hebrew language
* manualy added translation
![image](https://user-images.githubusercontent.com/37147299/169298457-18b14fb4-aa83-4461-b05d-953d15734791.png)

When I download file, it's writen in hebrew and not _escaped ascii/unicode_
![image](https://user-images.githubusercontent.com/37147299/169300157-0af01d10-487b-4002-8406-814750e55b85.png)
