### ISSUE TITLE
Add Alibaba Translate machine translate service

### ISSUE THREAD

**Issue by Aikatsui** [WeblateOrg/weblate#7659]
### Basic details

Provider: Alibaba Translate

**Description**

1. This provider offer free quota, 1 million characters per month
2. they've several services that collaborate with real translators for many languages so ofcourse MT quality might be better (or in future) than to other popular providers that get developed using public people's inputs etc.

https://www.alibabacloud.com/help/en/machine-translation
https://www.alibabacloud.com/help/en/machine-translation/latest/product-pricing-introduction

- _https://translate.alibaba.com/ (note: to avoid confuse, if you click API access on this site, it will redirect to the local alibaba translate; aliyun site, but you can use above alibabacloud (en site) for easy)_
- _https://alynx.alifanyi.com/ https://alynx.alifanyi.com/pay.html
(also it has a free plan and part of alibaba translate)_
- _https://www.zuodao.com/crowdsourcing/homePage.html
(part of alibaba translate)_

**Comment by nijel** [comment]
Is this related? https://docs.weblate.org/en/latest/admin/machine.html#youdao-zhiyun-api-machine-translation

**Comment by Aikatsui** [comment]
No. it's netease company. something like gitlab, gitea

**Comment by nijel** [comment]
Okay, I got confused by zoudao and youdao :-)

**Comment by Aikatsui** [comment]
Update: Details for documentation 
https://docs.weblate.org/en/latest/admin/machine.html#

https://www.alibabacloud.com/help/en/machine-translation
https://www.alibabacloud.com/help/en/basics-for-beginners/latest/obtain-an-accesskey-pair

**Comment by hussainshaikh12** [comment]
Hey can you assign this issue to me.

**Comment by nijel** [comment]
@hussainshaikh12  You're welcome!

**Comment by Aikatsui** [comment]
Beta version released: https://store.crowdin.com/alibaba
meanwhile weblate 😴

ping @hussainshaikh12

**Comment by hussainshaikh12** [comment]
Hey @nijel sorry for not responding earlier. I was stuck and was not able to even do the setup locally as i did not have the proper resources to do so back then. And apart from that the alibaba cloud account setup for me was also a difficult thing to do as it was not allowing me to add my card to get access to the free trial(Had to connect to the support team multiple times). I just had one suggestion that it would be great if we could have something like a discord or similar to easily connect to others for simple setup issues and doubts.

**Comment by Aikatsui** [comment]
@hussainshaikh12 Thank you. :blush: You can find his email on the github profile. If you want something like discord, i would recommend using mattermost, zulip etc.
