### ISSUE TITLE
Is there is a way to create pluralized translations from the UI?

### ISSUE THREAD

**Issue by antonkomarev** [WeblateOrg/weblate#7663]
### Describe the issue

I cannot find how to create pluralized strings from the UI. There is a way to create them from file upload, by VCS import or by API, but I cannot find anything related to it in UI. If string already support pluralization you have multiple textarea fields to fill each plural form.

How can we add new translation string with multiple plural forms from the UI?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Add new translation string

### Expected behavior

1. Choose `Plural` radio button on "Add new translation string" page
2. Add new translation string with multiple plural forms

### Screenshots

<img width="590" alt="Screenshot 2022-05-18 at 13 58 29" src="https://user-images.githubusercontent.com/1849174/169024383-39829082-7e9a-42c4-86a2-16cf65acdde2.png">

### How do you run Weblate?

Docker container

### Weblate versions

Weblate 4.12.2

**Comment by nijel** [comment]
Currently, there is no UI for this, it is possible to that via API, though.

**Comment by AkhilrajNambiar** [comment]
There is no update to this so far. Weblate identifies plurals, but there is no way to separately add the singular and plural translations

**Comment by jasonlessenich** [comment]
What's the state on this?

**Comment by nijel** [comment]
@harriebird Can you take a look at this? The backend has all the features as it is used in the API. The `NewUnitBaseForm` and subclasses need to be modified to support this (returning list of strings as `source` from the `as_kwargs` method) and it will need UI changes to choose between singular and plural.

**Comment by harriebird** [comment]
Hi guys, check my PR #11756 for this issue.
