### ISSUE TITLE
Why Variant relate on source string instead of key (id)?

### ISSUE THREAD

**Issue by antonkomarev** [WeblateOrg/weblate#7664]
### Describe the issue

Why variants uses mutable source string value as relation identifier instead of immutable Translation key (XLIFF `id` attribute)? Is it bug or made intentionally?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Create translation string with `key = example` and translation `This is example`
2. Create variant of the string `example` with `key = example_one` and translation `This is example One`
3. Create variant of the string `example` with `key = example_two` and translation `This is example Two`
4. Export XLIFF file
5. Look on `weblate-flags` attribute

```xliff
<trans-unit xml:space="preserve" approved="yes" id="example">
  <source>This is example</source>
  <target state="translated">This is example</target>
</trans-unit>

<trans-unit xml:space="preserve" approved="yes" id="example_one" weblate-flags="variant:&quot;This is example&quot;">
  <source>This is example One</source>
  <target state="translated">This is example One</target>
</trans-unit>

<trans-unit xml:space="preserve" approved="yes" id="example_two" weblate-flags="variant:&quot;This is example&quot;">
  <source>This is example Two</source>
  <target state="translated">This is example Two</target>
</trans-unit>
```

### Expected behavior

```xliff
<trans-unit xml:space="preserve" approved="yes" id="example">
  <source>This is example</source>
  <target state="translated">This is example</target>
</trans-unit>

<trans-unit xml:space="preserve" approved="yes" id="example_one" weblate-flags="variant:example">
  <source>This is example One</source>
  <target state="translated">This is example One</target>
</trans-unit>

<trans-unit xml:space="preserve" approved="yes" id="example_two" weblate-flags="variant:example">
  <source>This is example Two</source>
  <target state="translated">This is example Two</target>
</trans-unit>
```

### How do you run Weblate?

Docker container

### Weblate versions

Weblate 4.12.2

**Comment by burner1024** [comment]
There's no ids in PO format, for example.
Although I did expect variants to be linked by unit ids or something. Right now, with every source string update, I guess variants have to be re-linked, and given that it scales pretty [badly](https://github.com/WeblateOrg/weblate/issues/7661), this could be a major issue in setups that use lots of variants.

**Comment by antonkomarev** [comment]
> When using keys, it might be better to use [automated variants](https://docs.weblate.org/en/latest/devel/translations.html#automated-key-based-variants).

Then variants flagged as variant in UI but not does not flagged in exported XLIFF file in any way. Is that correct behavior?

```xliff
<trans-unit xml:space="preserve" approved="yes" id="example">
  <source>This is example</source>
  <target state="translated">This is example</target>
</trans-unit>

<trans-unit xml:space="preserve" approved="yes" id="example_one">
  <source>This is example One</source>
  <target state="translated">This is example One</target>
</trans-unit>

<trans-unit xml:space="preserve" approved="yes" id="example_two">
  <source>This is example Two</source>
  <target state="translated">This is example Two</target>
</trans-unit>
```

**Comment by nijel** [comment]
Yes, that's correct.
