### ISSUE TITLE
Allow Social Auth to bind to existing accounts

### ISSUE THREAD

**Issue by OdyX** [WeblateOrg/weblate#7666]
### Describe the problem

Currently, if moving from Google OAuth2 to KeyCloak OpenID, a user will not be allowed to "bind" their new authentication to their existing user. The only way for individual users to get that to work is to first login with an existing authentication mechanism, associate the account with KeyCloak.

### Describe the solution you'd like

 There could be a way to allow-list some authentication mechanisms to allow "automatic binding".

It seems that the culprit is `weblate.accounts.pipeline.ensure_valid`, https://github.com/WeblateOrg/weblate/blob/da00376324ed64d66c3e99effdf76263cb3ac09a/weblate/accounts/pipeline.py#L362-L364

### Describe alternatives you've considered

There doesn't seem to be an available way to configure this.

**Comment by nijel** [comment]
It's not a good idea by default (see https://github.com/WeblateOrg/weblate/issues/7588#issuecomment-1122400274), but it might be a reasonable to have a configuration option for migration between authentication providers.

**Comment by reloxx13** [comment]
i removed the raising error and it works for now. the account will also be linked after entering the existing password.       
i hope we can get this supported somehow as ill have to do this after every update now.     
thank you.
