### ISSUE TITLE
Weblate - Setup failed

### ISSUE THREAD

**Issue by Justman10000** [WeblateOrg/weblate#7677]
### Describe the issue

Hi, I was able to set up Weblate, but now i have this problem:

![grafik](https://user-images.githubusercontent.com/49990629/169602483-3695ec7b-1cde-4827-92a7-32e961bc4542.png)

As you can see, no CSS

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Install weblate from source
2. Compile it
3. Use [Apache2 Config](https://docs.weblate.org/en/latest/admin/install.html#sample-configuration-for-apache)

### Expected behavior

Complete weblate output

### How do you run Weblate?

Git checkout

### Weblate versions

 * Weblate: 4.12.2
 * Django: 4.0.4
 * siphashc: 2.1
 * translate-toolkit: 3.6.2
 * lxml: 4.6.5
 * Pillow: 9.1.1
 * bleach: 5.0.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.2.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.0
 * django-compressor: 4.0
 * djangorestframework: 3.13.1
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.6.0
 * jellyfish: 0.9.0
 * openpyxl: 3.0.10
 * celery: 5.2.6
 * kombu: 5.2.4
 * translation-finder: 2.13
 * weblate-language-data: 2022.3
 * html2text: 2020.1.16
 * pycairo: 1.21.0
 * pygobject: 3.42.1
 * diff-match-patch: 20200713
 * requests: 2.27.1
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.5.12
 * Cython: 0.29.30
 * misaka: 2.1.1
 * GitPython: 3.1.27
 * borgbackup: 1.1.17
 * pyparsing: 3.0.9
 * pyahocorasick: 1.4.4
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.0.12
 * Python: 3.9.2
 * Git: 2.30.2
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * boto3: 1.22.13
 * zeep: 4.1.0
 * aeidon: 1.11
 * iniparse: 0.5
 * Mercurial: 6.1.2
 * git-review: 2.3.1
 * Redis server: 7.0.0
 * PostgreSQL server: 13.5
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 5.10.0-14-amd64 (x86_64)

### Weblate deploy checks

```shell
?: (weblate.W033.Subversion) Failure in loading VCS module for Subversion: git: 'svn' is not a git command. See 'git --help'.

The most similar commands are
        fsck
        mv
        show
 (1)
        HINT: https://docs.weblate.org/en/weblate-4.12.2/vcs.html

INFOS:
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.12.2/admin/backup.html
```

### Additional context

I don't know what to do with the backups...

**Comment by Justman10000** [comment]
Hinzu kommt noch dies:

> System check identified 1 issue (1 silenced).
Mai 20, 2022 - 20:21:22
Django version 4.0.4, using settings 'weblate.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

But port 8000 cannot be reached, even though the machine is running locally and the port is open! It seems Weblate isn't even listening on port 8000!

**Comment by Justman10000** [comment]
OK, done! Now that I know what to do, which is quite different from the documentation, I won't do a PR until tomorrow at the earliest to update the documentation...

**Comment by Justman10000** [comment]
Cheered too soon, here comes this:

![grafik](https://user-images.githubusercontent.com/49990629/169656964-e93a0ee4-6ea6-479b-83e8-611cf82f6de4.png)

**Comment by Justman10000** [comment]
@nijel

**Comment by nijel** [comment]
Sorry I have no clue how your setup looks like. Are you using Apache (https://github.com/WeblateOrg/weblate/issues/7677#issue-1243569250) or built-in server (https://github.com/WeblateOrg/weblate/issues/7677#issuecomment-1133329084)?

**Comment by Justman10000** [comment]
> > Sorry, I have no clue how your setup looks like. Are you using Apache ([#7677 (comment)](https://github.com/WeblateOrg/weblate/issues/7677#issue-1243569250)) or built-in server ([#7677 (comment)](https://github.com/WeblateOrg/weblate/issues/7677#issuecomment-1133329084))?
> 
> It's been dealt with! The documentation is just extremely confusing! I fix it...

@nijel 

Have now pushed the promised update! (#7740)
