### ISSUE TITLE
Multi files

### ISSUE THREAD

**Issue by Justman10000** [WeblateOrg/weblate#7680]
### Describe the problem

Only one language file can be used in translation components!

### Describe the solution you'd like

A system based on Crowdin, you have a view with all files!

### Screenshots

As an an example:

![grafik](https://user-images.githubusercontent.com/49990629/169669074-117210ac-bcaa-4afd-acc1-8c29fbb73daa.png)

### Additional context

I hope that this will be adopted as soon as possible, I'm sure others will too!

**Comment by nijel** [comment]
You need more components, see https://docs.weblate.org/en/latest/admin/projects.html. You can use [Component discovery](https://docs.weblate.org/en/latest/admin/addons.html#component-discovery) to automate creating of them.

**Comment by Justman10000** [comment]
> Yes, but each translation file has a name as well...

That's clear, but if I have a component called Website, for example, but it uses multiple JSON files for translation, what do I name the other components? Because website (1), website (2) and website (3), as an example, just looks stupid!

**Comment by nijel** [comment]
Are you files storing translations called website-1.json, website-2.json and website-3.json?

**Comment by Justman10000** [comment]
> Are you files storing translations called website-1.json, website-2.json and website-3.json?

As? For example, you have admin.php, messages.php, etc

**Comment by nijel** [comment]
And the components can be named same way....

**Comment by Justman10000** [comment]
> And the components can be named same way....

Yes, it also looks stupid if you suddenly have 3 websites there instead of just programming it like Crowdin has it...
