### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by mehdichaouch** [WeblateOrg/weblate#7689]
### Describe the issue

Hello,

After adding a translation key, we observe that this key as missing to translate in:
- German
- Dutch
- Flemish
- French (Belgium)

For exemple, I can go to:
https://weblate.xyz.com/translate/xyz-m2/magento2-master/en/?checksum=7c1bec936c52446c
but not in:
https://weblate.xyz.com/translate/xyz-m2/magento2-master/de/?checksum=7c1bec936c52446c

For a test translation key I just added, I can see:
![image](https://user-images.githubusercontent.com/861701/170006937-5b1e3d05-25c9-4280-864a-39f4658eeebe.png)
but for the one in trouble I have _Timing emotions_:
![image](https://user-images.githubusercontent.com/861701/170006533-1953b588-21f5-4f3c-9f72-7ae67f5ce699.png)

How it's possible to do not have the same amount of language?
How can I have all keys available to all language?
Is there a setting that cause this trouble?
Is there a command to link key to all languages?
And if there is a maintenance command that should be run by infra let me know.

PS: I check the documentation, and found nothing to solve my bug.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Git checkout

### Weblate versions

Weblate 4.9

**Comment by nijel** [comment]
It might be caused by your component configuration (for example, in case you are using bilingual setup). It might also be a bug in Weblate version you are using, can you try upgrading?

**Comment by mehdichaouch** [comment]
@nijel thanks for your answer.
I'll try to update and see if it fix the bug.

**Comment by nijel** [comment]
Upgrading is documented here: https://docs.weblate.org/en/latest/admin/upgrade.html
