### ISSUE TITLE
Change translation file name

### ISSUE THREAD

**Issue by EmmanuelBlanchet** [WeblateOrg/weblate#7691]
### Describe the issue

Hi, how would I go about manually changing the file name for an existing language?
For example, when I add Armenian as a new language, the file name is set to be ``hy.json``, but I'd like it to be hy_am.json. Or Romanian as ``ro_ro.json`` instead of ``ro.json``. (Specifically, I need them to be in the Minecraft format)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Docker container

### Weblate versions

Weblate: 4.12.2
    Django: 4.0.4
    siphashc: 2.1
    translate-toolkit: 3.6.2
    lxml: 4.6.5
    Pillow: 9.1.0
    bleach: 5.0.0
    python-dateutil: 2.8.2
    social-auth-core: 4.2.0
    social-auth-app-django: 5.0.0
    django-crispy-forms: 1.14.0
    oauthlib: 3.2.0
    django-compressor: 4.0
    djangorestframework: 3.13.1
    django-filter: 21.1
    django-appconf: 1.0.5
    user-agents: 2.2.0
    filelock: 3.6.0
    jellyfish: 0.9.0
    openpyxl: 3.0.9
    celery: 5.2.6
    kombu: 5.2.4
    translation-finder: 2.12
    weblate-language-data: 2022.2
    html2text: 2020.1.16
    pycairo: 1.21.0
    pygobject: 3.42.1
    diff-match-patch: 20200713
    requests: 2.27.1
    django-redis: 5.2.0
    hiredis: 2.0.0
    sentry_sdk: 1.5.12
    Cython: 0.29.29
    misaka: 2.1.1
    GitPython: 3.1.27
    borgbackup: 1.2.0
    pyparsing: 3.0.9
    pyahocorasick: 1.4.4
    python-redis-lock: 3.7.0
    charset-normalizer: 2.0.12
    Python: 3.10.4
    Git: 2.30.2
    psycopg2: 2.9.3
    psycopg2-binary: 2.9.3
    phply: 1.2.5
    ruamel.yaml: 0.17.21
    tesserocr: 2.5.2
    akismet: 1.1
    boto3: 1.22.13
    zeep: 4.1.0
    aeidon: 1.11
    iniparse: 0.5
    mysqlclient: 2.1.0
    Mercurial: 6.1.2
    git-svn: 2.30.2
    git-review: 2.3.1
    Redis server: 6.2.7
    PostgreSQL server: 14.3
    Database backends: django.db.backends.postgresql
    Cache backends: default:RedisCache, avatar:FileBasedCache
    Email setup: django.core.mail.backends.dummy.EmailBackend: 127.0.0.1
    OS encoding: filesystem=utf-8, default=utf-8
    Celery: redis://cache:6379/1, redis://cache:6379/1, regular
    Platform: Linux 5.10.0-14-cloud-amd64 (x86_64)

**Comment by nijel** [comment]
Rename it in the Git and push changes, Weblate should handle that without problems. You might want to customize language code format to better fit your use case.

**Comment by EmmanuelBlanchet** [comment]
> You might want to customize language code format to better fit your use case.

How would I go about that?

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/languages.html#adding-new-translations (not sure if there is something that fits you 100%, maybe another style would be needed).
