### ISSUE TITLE
Rewrite unsafe (XSS-prone) code in a safer way

### ISSUE THREAD

**Issue by WofWca** [WeblateOrg/weblate#7699]
### Describe the problem

There is some code that is hard to check whether is safe or not. Namely:

* [x] Remaining `mark_safe` usage (e.g. https://github.com/WeblateOrg/weblate/blob/f0b4c8146b7c0663003ab04233c09f3cb8457119/weblate/accounts/templatetags/site_url.py#L32-L49, https://github.com/WeblateOrg/weblate/blob/6e28638d2a251aec65b84beb097cf00eac911af7/weblate/trans/forms.py#L275-L277, looks like rewriting `translations.py` is gonna be a pain: https://github.com/WeblateOrg/weblate/blob/6e28638d2a251aec65b84beb097cf00eac911af7/weblate/trans/templatetags/translations.py#L252)
* [x] `|safe` usage in templates (e.g. https://github.com/WeblateOrg/weblate/blob/5821a776ab0c9a527187db37cd4597142ec34583/weblate/templates/bootstrap3/field.html#L17)
* [x] Direct `HttpResponse` usage (e.g. https://github.com/WeblateOrg/weblate/blob/22d577b1f1e88665a88b4569380148030e0f8389/weblate/trans/views/reports.py#L125)
* [x] Maybe there's something in JavaScript. I saw `innerHTML`, for example. And a lot of `$('...`.
* [x] Wherever there is `escape(`, it likely means that the code can be rewritten with `format_html`.
* [x] Try searching for `[A-Z]\.format\(` - most of occurrences need to be rewritten with `format_html`.
* [x] Considering how big the translation files are, maybe it's time to make a wrapper for `gettext`, `trans` and `blocktrans` which will escape the text by default.

And I might have missed something.

### Describe the solution you'd like

Gradually make the code easier to assess for security, by removing `|safe`, `mark_safe(`, `.innerHTML =` and utilizing `format_html`, `format_html_join`, `conditional_escape`, etc.

### Additional context

These fall under this: #7676, #7683, #7696.

**Comment by nijel** [comment]
> Direct HttpResponse usage 

This one is for generated text/plain, not sure if there is a better alternative.

> [weblate/weblate/templates/bootstrap3/field.html](https://github.com/WeblateOrg/weblate/blob/5821a776ab0c9a527187db37cd4597142ec34583/weblate/templates/bootstrap3/field.html#L17)

This one is based on django-crispy-forms, we have to follow what they do.

> [weblate/weblate/accounts/templatetags/site_url.py](https://github.com/WeblateOrg/weblate/blob/f0b4c8146b7c0663003ab04233c09f3cb8457119/weblate/accounts/templatetags/site_url.py#L32-L49)

This one does post-processing of HTML, I don't see a better alternative.

>  , looks like rewriting translations.py is gonna be a pain:

It is basically merging a list with HTML tags and list with text. I'd be a bit worried about the performance if this is migrated to `format_html_join`.
