### ISSUE TITLE
When trying to add a suggestion that is == current translation, it says "suggestion already exists", even if there are actually none

### ISSUE THREAD

**Issue by WofWca** [WeblateOrg/weblate#7705]
### Describe the issue

Sounds nitpicky, but it confused me when is was editing glossary since there's an "Explanation" text area which is in place of where the translation text area usually is on non-glossary items. Maybe this also needs to be changed.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

weblate.org service

### Additional context

Code:

https://github.com/WeblateOrg/weblate/blob/4b2e079b80103364292464b585186943b7172890/weblate/trans/views/edit.py#L288-L297

https://github.com/WeblateOrg/weblate/blob/d92daadd0e3cd8d150cb1386e9a7b3ed541f37c3/weblate/trans/models/suggestion.py#L47-L48

**Comment by Sugarlust** [comment]
hey I'm new to opensource and would like to work on it can you please tell what needs to be done?

**Comment by WofWca** [comment]
What is it that you don't understand? There are links to the responsible code in the issue description.

**Comment by Sugarlust** [comment]
I did check out the code what i meant to ask is do you have any idea on what should be changed and what should it rather say?

**Comment by nijel** [comment]
The problem is that there is same error message used for case where suggestion matches existing suggestion (where it correct) and when it matches existing translation (where the message is confusing).
