### ISSUE TITLE
Make 404 more useful when possible

### ISSUE THREAD

**Issue by WofWca** [WeblateOrg/weblate#7711]
### Describe the problem

For example, if you try go to a non-existent language of a component, the page will only suggest to go home or to all projects, while it would be better if it linked to the component, or suggested adding a language that you tried to visit. Example: https://hosted.weblate.org/projects/keepassxc/keepassxc-browser-dev/fil/

![image](https://user-images.githubusercontent.com/39462442/170858920-68e686b2-649b-40ce-8d04-c9f5de9b24fb.png)

### Describe the solution you'd like

Add useful suggestions depending on the context.

### Additional context

https://github.com/WeblateOrg/weblate/blob/1804a951c8ae9199d23099a8ec322134ee5b45bc/weblate/urls.py#L136-L140

https://github.com/WeblateOrg/weblate/blob/329dabf59991ed2ee1b44f331929da41d8031c98/weblate/templates/404.html

**Comment by nijel** [comment]
There is already a middleware dealing with this:

https://github.com/WeblateOrg/weblate/blob/12e59a7f1e6a381b46f186680fe192f49ad791d7/weblate/middleware.py#L75-L191

**Comment by ParthS007** [comment]
@nijel Can you please add more context what is expected here?

**Comment by ParthS007** [comment]
@nijel Can you please add more context what is expected here?

**Comment by nijel** [comment]
When you enter a URL to an existing component, but not an existing language, it should redirect to the component and telling user to add that language.

For example, https://hosted.weblate.org/projects/weblate/application/ace/ should redirect to https://hosted.weblate.org/projects/weblate/application/ and tell user that Acehnese translation is currently not existing, but can be added.
