### ISSUE TITLE
On the `/engage` page, reduce the amount of clicks required to actually start translating

### ISSUE THREAD

**Issue by WofWca** [WeblateOrg/weblate#7715]
### Describe the problem

Now I'd say it really takes a lot to get to business from the engage page. You have to:
1. Click "Translate".
2. Select language (even if the language is specified in the URL (`/engage/<project>/<lang>`)
3. Select a component.
4. Find the "Translate" button, or select an option from a myriad of them.
Then you can finally check out what the translation process looks like. And I omitted creating an account here.
Considering this I'd say it currently makes sense to consider sending users to `/translate/<project>/<component>/<lang>/?q=state:%3Ctranslated` instead of the engage page.

### Describe the solution you'd like

* Would be cool to display the most appropriate option on the engage page. If the user doesn't like it, they can select another one (like now we have "View project languages"). Or they can simply follow the suggestion, and later navigate wherever they need using breadcrumbs.
    * The language can be made the same as current display language (inferred from geo-IP and stuff). As far as I know something like this is done for registered users: e148d58e250cf3b9c1e9b421cf9dc852c434be3d. At least put it at the top of the list of the languages.
    * the component can be the one with the highest priority. Or add an option called "default component"
    * the string filter can be the same as for the "Translate button" on the `/projects/<project>/<component>/<lang>/` page (from step 4).
* About step 3 above: the Glossary component can be confusing, especially considering that by default it has the same name as the project. Perhaps it needs to be named "Glossary" by default? I know there is a badge saying that next to it, but still. Separate issue?
* Uhh also both "Translate" and "View project languages" buttons lead to the same URL. Remove either?
    https://github.com/WeblateOrg/weblate/blob/4a696e34a1bcdbc5423a2769d893c2aaa9426c12/weblate/templates/engage.html#L63-L64

### Additional context

Related: #7715, #7079, e148d58e250cf3b9c1e9b421cf9dc852c434be3d

**Comment by luzpaz** [comment]
What's left to do here?

**Comment by nijel** [comment]
I'm not sure, seems like most of the points have been addressed. Closing.
