### ISSUE TITLE
Weblate can't extract the attributes within the messages inside a Fluent translation file

### ISSUE THREAD

**Issue by pan93412** [WeblateOrg/weblate#7742]
### Describe the problem

When importing [the string file of rustc](https://github.com/rust-lang/rust/blob/4322a785cc99ea5fc81dd7f5fc8ba7f7a64b08ef/compiler/rustc_error_messages/locales/en-US/parser.ftl), I found that Weblate can't extract the attributes inside messages.

[As it is listed in the official Fluent specification](https://projectfluent.org/fluent/guide/attributes.html), I wish it can be supported! 😄

### Describe the solution you'd like

Weblate can treat the attributes in the messages as a translatable string.

### Screenshots

![Weblate can correctly extract the messages but not the attributes inside messages](https://user-images.githubusercontent.com/28441561/172054157-c3021a14-ab72-4eaa-9120-d0a090a0ecae.png)

Take this image as example: I hope the strings in `.suggestion` and `.help` can be extracted and translated as a normal string.

**Comment by nijel** [comment]
Currently, the attributes are not exposed as translatable strings by translate-toolkit.

**Comment by pan93412** [comment]
> Currently, the attributes are not exposed as translatable strings by translate-toolkit.

Create an issue with a link to here in https://github.com/translate/translate/issues/4649. Not really sure how to report it correctly since there is no `ftl2po`.

**Comment by nijel** [comment]
This is correct, there are no convertors for fluent, but only a storage class there.

**Comment by juliancoffee** [comment]
Still an issue even after https://github.com/translate/translate/issues/4649?
