### ISSUE TITLE
NotSupportedError when trying to "Search and replace" with filter

### ISSUE THREAD

**Issue by endervad** [WeblateOrg/weblate#7754]
### Describe the issue

"Search and replace" feature doesn't work and produces an error if used with filtering. I caught the following example:
Filter: `source:r"^Blizzard$" language:ru`
String to change: `Лёд`
String to replace: `Метель`
This error occurs both inside the language, and outside out of language (component-wide). I also unsuccessfully tried other filter queries, like `source:r"^Blizzard$"` or `language:ru`
This error does not occur if you remove the filter query.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to any component (optionally you can go to any language of the component)
2. Tools > Search and replace: Input any filter query (e.g. language:XX) and fill other fields
3. "Search and replace" will show the changes. If you press "Replace" you'll get an error

### Expected behavior

Search and Replace should work.

### Exception traceback

```pytb
Got an email, attached it to 'Additional context' section.
```

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.12.2
 * Django: 4.0.4
 * siphashc: 2.1
 * translate-toolkit: 3.6.2
 * lxml: 4.6.5
 * Pillow: 9.1.0
 * bleach: 5.0.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.2.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.0
 * django-compressor: 4.0
 * djangorestframework: 3.13.1
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.6.0
 * jellyfish: 0.9.0
 * openpyxl: 3.0.9
 * celery: 5.2.6
 * kombu: 5.2.4
 * translation-finder: 2.12
 * weblate-language-data: 2022.2
 * html2text: 2020.1.16
 * pycairo: 1.21.0
 * pygobject: 3.42.1
 * diff-match-patch: 20200713
 * requests: 2.27.1
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.5.12
 * Cython: 0.29.29
 * misaka: 2.1.1
 * GitPython: 3.1.27
 * borgbackup: 1.2.0
 * pyparsing: 3.0.9
 * pyahocorasick: 1.4.4
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.0.12
 * Python: 3.10.4
 * Git: 2.30.2
 * psycopg2: 2.9.3
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.22.13
 * zeep: 4.1.0
 * aeidon: 1.11
 * iniparse: 0.5
 * mysqlclient: 2.1.0
 * Mercurial: 6.1.2
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 6.2.7
 * PostgreSQL server: 13.7
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.gmail.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.10.102.1-microsoft-standard-WSL2 (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.12.2/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.12.2/admin/backup.html

System check identified 2 issues (1 silenced).
```

### Additional context

[[Weblate] ERROR (EXTERNAL IP)_ Internal Server Error_ _replace_ffxiv-translation_action_ru_.zip](https://github.com/WeblateOrg/weblate/files/8862128/Weblate.ERROR.EXTERNAL.IP._.Internal.Server.Error_._replace_ffxiv-translation_action_ru_.zip)

**Comment by nijel** [comment]
Should be already fixed by 431b723228f7bd315987f15e8bd489495bacb03c.
