### ISSUE TITLE
"Broken project website URL" sends too much alert email

### ISSUE THREAD

**Issue by alvinhochun** [WeblateOrg/weblate#7758]
### Describe the issue

The "project website" is a per-project setting, yet the "broken project website URL" alert triggers an alert email **per component**. In our case we have 295 components in a project. The project website appeared to be temporarily offline to our Weblate instance, and Weblate proceeded to send us 295 emails each.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Create a project with a lot of components
2. Make Weblate fail to connect to the project website URL

### Expected behavior

At most one alert email per user shall be sent.

### How do you run Weblate?

Docker container

### Weblate versions

Weblate 4.12.2

### Additional context

cc @pan93412

**Comment by pan93412** [comment]
Some screenshots about this issue:

![telegram-cloud-photo-size-5-6127302771309916232-x](https://user-images.githubusercontent.com/28441561/172893022-a14068e9-cca8-4290-aee0-b144f7231f5c.jpg)

![telegram-cloud-photo-size-1-4974771477366811160-x](https://user-images.githubusercontent.com/28441561/172893033-d4037b2c-4cbf-4257-bfdc-fb1daabb4005.jpg)

![image](https://user-images.githubusercontent.com/28441561/172893121-35c6f235-addb-450a-ad41-efe02deec94a.png)

![image](https://user-images.githubusercontent.com/28441561/172893153-6905f273-669e-4242-8972-cbdc63c6c170.png)

![image](https://user-images.githubusercontent.com/28441561/172893183-a381a636-c6c8-47ae-9447-3782e7ecfccf.png)
