### ISSUE TITLE
Test mode: weblate in gibberish

### ISSUE THREAD

**Issue by emyoulation** [WeblateOrg/weblate#7774]
### Describe the problem

Could a full automatic Weblate complete glossary dummy translation be programmatically generated for test purposes?

It is sometimes difficult to perceive when strings have been overlooked for translation. (That includes when a typo or a whitespace oddity prevents a translation.)

### Describe the solution you'd like

Perhaps Weblate could auto-generate a "Gibberish language" (or maybe a dead language that has a Unicode block, like Sumerian/Akkadian cuneiform) translation file so that a developer could switch their OS to that pseudo language and verify nothing was overlooked. It might use an unusual subset of the Unicode range... like random characters from the Mahjong Tiles block. (It could be extra fancy and separate words with face down tile, alternating suit with each word and use random special tiles for punctuation.)

This would also need a too to regenerate locally on demand. Otherwise, iterative tests would have to wait for a batch regeneration.

### Describe alternatives you've considered

Originally, the thought was to merely prefix the translated strings with an Unicode symbol. 

But our language discrimination is trained to spot words with meaning. Untranslated words word stand-out prominently whereas prefixed words would have to be carefully read.

**Comment by nijel** [comment]
There is already pseudolocale add-on, it adds prefix and suffix to all strings, what serves well for testing - you see which strings are translatable, and you also see what string is that.
