### ISSUE TITLE
ACL : Allow everyone to suggest but only some ppl to approve

### ISSUE THREAD

**Issue by ebanDev** [WeblateOrg/weblate#7776]
### Describe the issue

It's an ACL issue, I want the following
- Everyone logged in can suggest a translation
- Only users of the "Reviewers" team can approve translation and then they are commited and pushed to the repo
- 
I can't find where to manage permissions for "everyone" role :/

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

PyPI module

### Weblate versions

4.13

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/access.html#site-wide-permission-management - everybody is by default member of the "Users" group.
