### ISSUE TITLE
Component without strings shows up 100% progress instead of checkmark

### ISSUE THREAD

**Issue by qwerty287** [WeblateOrg/weblate#7778]
### Describe the issue

A component without strings (a glossary) shows up as 100%, but there isn't the checkmark.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Create an empty component
2. Look at the overview.

### Expected behavior

Show a checkmark.

### Screenshots

![](https://user-images.githubusercontent.com/80460567/174327914-e6fb751e-4f58-4ee3-acdb-9e9f4ed09758.png)

### How do you run Weblate?

weblate.org service

### Additional context

I refer to https://hosted.weblate.org/projects/auxio/glossary/.

**Comment by ParthS007** [comment]
@nijel Can you please add more info about the checkmark (where I can find it in the code) and where I can find the instructions to make an empty component. Thanks
