### ISSUE TITLE
Authorized translators

### ISSUE THREAD

**Issue by GreenLunar** [WeblateOrg/weblate#779]
Is it possible to restrict access to a Weblate project for selected translators?

See issue MaartenBaert/ssr/issues/351
##

**Comment by nijel** [comment]
Currently this feature is available only for commercial (non public) translations. This might change once #516 is implemented.

**Comment by nijel** [comment]
On the other side, none of hosted projects complained on the openness so far, so I believe it works fine for them.

**Comment by GreenLunar** [comment]
Maybe it is a coincidence.

Linux applications (mostly, software written GTK+) in Hebrew used to be high quality until 2005; since 2004/2005 to this day, there are/were some people who started to "translate" GTK+ software with their special language such as translating Cut/Copy/Paste (i.e. verb) into Cutting/Copying/Pasting (i.e. adverb) in Hebrew, and other weird things.

Xfce desktop environment was translated into a VERY LOW QUALITY in Hebrew until 2014, when an Israeli GNU contributor, who is not a bored person (i.e. a person who have a job and a family), was bothered in this concern, and that respected GNU contributor was bothered with over 200 (two hundred) disturbing emails since 2011.  Xfce also used to be available in high quality by its 3 first translators.

The damages of having free-for-all access are extremely severe.

While I am participating in Weblate, I will not recommend it until this problem is fixed.

**Comment by nijel** [comment]
I've seen poor quality translations in both open and closed translator communities. It's just matter of review the translation gets - more people looking and taking care the translation usually leads to better results. For closed ones it actually tends to be worse once bad translator gets in (what's hard to decide if you do not know the language).

Still it's choice of every project which way it prefers. For projects with big community of translators, it's reasonable choice to stick with closed model as they have enough translators to keep the translations running even with high barrier to contribute. For projects with small or non existing community, the closed model will usually not bring enough attention to get the translations done due to high barrier to enter.

Weblate supports both models, but the closed one is really closed right now - there is no visibility of closed projects and this offering is currently available only for commercial customers on Hosted Weblate.

**Comment by GreenLunar** [comment]
> I've seen poor quality translations in both open and closed translator communities. It's just matter of review the translation gets - more people looking and taking care the translation usually leads to better results. For closed ones it actually tends to be worse once bad translator gets in (what's hard to decide if you do not know the language).

I agree. In concern to open source translations, managed by volunteers, usually, once you get a bad translator in a project (e.g. GNOME and Xfce) it is difficult to boot him out, because earlier translators who are being asked to assist in de-legitimizing a vandal translator, they may ignore you, either because they do not care or they have no available frame of time to handle it, because they have families, need to pay the rent etc.

**Comment by GreenLunar** [comment]
I have bothered to translate https://hosted.weblate.org/projects/weblate/master/he/ and this 455h01e https://hosted.weblate.org/user/Yaron/ (link will be deleted) has vandalized my work!!!

**Comment by GreenLunar** [comment]
I meant https://hosted.weblate.org/projects/weblate/javascript/he/

**Comment by GreenLunar** [comment]
He did not even ask me!
```
https://github.com/nijel/weblate/commit/d3fcc55b34c01358cc52df11b854eaac1bf99c58
```
Please ban that systematic vandal!

**Comment by GreenLunar** [comment]
This is the person who was booted out from Xfce

He just submit several short string (even with typing errors) just to dump his name all over.

He is a sit-at-home jobless person.

**Comment by GreenLunar** [comment]
@nijel is it possible to delete comments that I have deleted here from https://www.bountysource.com/issues/24318081-authorized-translators ?

**Comment by yarons** [comment]
What vandal @GreenLunar?

**Comment by GreenLunar** [comment]
I am the translator of F-Droid in Hebrew.
I request you to stop changing my original strings.
You did not even request my opinion before you did (and still do) so.
https://hosted.weblate.org/projects/f-droid/f-droid/he/#history

**Comment by yarons** [comment]
@GreenLunar 

Your translation is inconsistent and incomprehensible, please refrain from gender biased translation, your translations are discriminating women. 

Thanks.

**Comment by GreenLunar** [comment]
I am also the translation coordinator for Psi.  Unfortunately, we do not use Weblate to due to the lack of Authorized Translators feature.  I also request you not to intervene with the Psi translation.  Your changes will not be committed to the Psi repository.

**Comment by GreenLunar** [comment]
> Your translation is inconsistent and incomprehensible, please refrain from gender biased translation, your translations are discriminating women.

Are you ok? Did you ask me for my permission?

**Comment by GreenLunar** [comment]
LOL, @nijel, he has [locked](https://hosted.weblate.org/projects/f-droid/f-droid/he/#locking) the translation. Take into consideration that if you won't do something in this concern, Weblate will not succeed.

**Comment by yarons** [comment]
Did you ask for my permission when you took over my translations? 

Your lawyer oriented translations are not natural to the users, I've got many complaints about you. 

At should stop doing this and meet.

**Comment by GreenLunar** [comment]
You are the person who was kicked out from Xfce Hebrew. When you were "in charge" you locked out new comers with 30%, and when you were booted out, Xfce Hebrew went to 100% and high quality.

Please stop it.

**Comment by yarons** [comment]
@GreenLunar your Xfce translation is a disgrace, Google translate is doing a better work than you. 

I'm keeping on high standards and good translators requires training. 

The language used in court is far different from the native language, your usage and misunderstanding of plural rules is shameful, do yourself a favor and try and understand what you're doing, otherwise the users are abandoning the open source software, you are actually making people stop using open source.

**Comment by GreenLunar** [comment]
I am not the translator of Xfce.
Again, do not even bother to intervene with Psi IM or Psi+ projects. We will not accept your changes, especially since you do not use any of them, you will not get further responds from me.

@nijel do we really have to fall into this sad state of affairs?
@yarons yo, bro, it was nice chatting with you, but I have a __job__ and so I need to leave.

**Comment by yarons** [comment]
@GreenLunar yeah, ruining peoples lives an a mediocre lawyer, please leave before more users will, you are doing a very low quality work and causing a lot of damage just like you do in court, peace.

**Comment by nijel** [comment]
@GreenLunar: Anybody locks the translation while he is working on that, this is to avoid two translators working on one translation at same time.

Sorry guys, but this is really not the right place to deciding who of you does better translation to Hebrew as I certainly can not judge this.

Anyway this feature is technically available in Weblate code right now, it's just not exposed in the UI (there is https://github.com/WeblateOrg/weblate/issues/1434 for it). Another question is whether it will be ever available in the free hosting plan.
