### ISSUE TITLE
java: `String.format()` checks wrongly applied to `java-format`

### ISSUE THREAD

**Issue by ptoscano** [WeblateOrg/weblate#7798]
### Describe the issue

It seems that weblate tries to apply the checks for a printf-like version of Java format strings (i.e. the ones for `String.format()` for messages with the `java-format` format. From what I can see, this does not match the behaviour of GNU gettext:
https://www.gnu.org/software/gettext/manual/html_node/java_002dformat.html

This can be easily checked:
```java
class Test
{
    public static void main(String args[])
    {
        System.out.println(String.format(tr("Hello, %s!"), "format"));
    }
}
```
and extracting it:
```bash
$ xgettext -o - -ktr test-format.java
```
gives the following (header removed):
```pot
#: test-format.java:5
#, java-printf-format
msgid "Hello, %s!"
msgstr ""
```

I checked the code of weblate at commit f2f333fd2750c67d0d933e3dccd3ca123bb7d58e:
https://github.com/WeblateOrg/weblate/blob/f2f333fd2750c67d0d933e3dccd3ca123bb7d58e/weblate/checks/format.py#L260

IMHO the above ought to be `java-printf-format` rather than `java-format`.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Other

**Comment by nijel** [comment]
When we implemented `java-format`, Gettext didn't have `java-printf-format`...
