### ISSUE TITLE
java: `MessageFormat` messages are not properly checked

### ISSUE THREAD

**Issue by ptoscano** [WeblateOrg/weblate#7799]
### Describe the issue

Weblate somehow knows about `MessageFormat`-style messages in Java code, with a check for that kind of messages. I see this was introduced by #2290.

The problem is that that check is not applied by default to the messages that really need it, i.e. those marked as `java-format`:
https://www.gnu.org/software/gettext/manual/html_node/java_002dformat.html

This can be easily checked:
```java
import java.text.MessageFormat;

class Test
{
    public static void main(String args[])
    {
        MessageFormat form = new MessageFormat(tr("Hello, \"{0}\"!"));
        Object[] formatArgs = {new String("MessageFormat")};
        System.out.println(form.format(formatArgs));
    }
}
```
and extracting it:
```bash
$ xgettext -o - -ktr test-messageformat.java
```
gives the following (header removed):
```gettext
#: test-messageformat.java:7
#, java-format
msgid "Hello, \"{0}\"!"
msgstr ""
```

A blocker issue for this is that weblate currently applies a wrong check to `java-format` messages -- see #7798.

Because of this, `MessageFormat` messages (marked with `java-format`) are not checked as they ought to be; in particular:
- the handling of the placeholders: they are completely ignored
- the escaping done with `'` (apostrophe) is not checked

this results in weblate happily accepting wrong translations without any warning, whereas GNU gettext will reject such translations. At least, this was recently noticed in the Fedora Weblate instance, i.e. https://translate.fedoraproject.org/ which currently runs 4.13.

I checked the code of weblate at commit f2f333fd2750c67d0d933e3dccd3ca123bb7d58e, and it seems the issue is still there.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Other

**Comment by nijel** [comment]
It is toggled by `java-messageformat`, see https://docs.weblate.org/en/latest/user/checks.html#check-java-messageformat. Seems like we have the flags different than Gettext.

**Comment by ptoscano** [comment]
Hi @nijel,

first of all, thanks for the changes for this!

One question related to #7920: from what I can see, it still does not implement a proper format check in weblate/checks/format.py for the "java-format" flag? In particular, checks for `MessageFormat` are not applied while editing? Or am I missing something?

**Comment by nijel** [comment]
They are - the checks were existing, they were just applied on different flags.
