### ISSUE TITLE
Machine translation with deepl adds spurious semi-colon to quoted parts

### ISSUE THREAD

**Issue by jnavila** [WeblateOrg/weblate#7803]
### Describe the issue

On hosted.weblate.org, when a word is quoted (with a large variety of quoting types)  in the original text, they appear followed by a semi-colon in the translated text. I don't know whether this is specific to French:

The same string inserted in the web page of DeepL site does not include the semi-colons 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to https://hosted.weblate.org/translate/git-manpages/translations/fr/?q=state:%3Ctranslated
2. Select "Automatic translation"
3. Click on next until a string with quotes appears in the source
4. See error in translated part for DeepL

### Expected behavior

The quoted parts are translated but not decorated with trailing semi-colon.

### Screenshots

![image](https://user-images.githubusercontent.com/156172/175783930-ff918961-0aea-4ab9-8597-c3ddbbc0ea77.png)

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Might be related to https://github.com/WeblateOrg/weblate/issues/6529...

**Comment by jnavila** [comment]
Thank you!
