### ISSUE TITLE
Weblate uses the wrong format when creating new Java properties files

### ISSUE THREAD

**Issue by derkoe** [WeblateOrg/weblate#7826]
### Describe the issue

Java Properties use the following format for language / country: {filename}_{language}_{COUNTRY}.properties. For example: `messages_de_AT.properties` (or without country `messages_de.properties`).

Weblate creates new properties files with a dash "-" instead of an underscore between language and country.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Create a component with type "Java Properties" (it does not matter which encoding)
2. Add a new language "English (United Kingdom)"
4. Check the created file name - it is `{filename}_en-GB.properties`

### Expected behavior

The file should be created as `{filename}_en_GB.properties`

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.13
 * Django: 4.0.5
 * siphashc: 2.1
 * translate-toolkit: 3.7.0
 * lxml: 4.6.5
 * Pillow: 9.1.1
 * bleach: 5.0.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.0
 * django-compressor: 4.0
 * djangorestframework: 3.13.1
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.7.1
 * jellyfish: 0.9.0
 * openpyxl: 3.0.10
 * celery: 5.2.7
 * kombu: 5.2.4
 * translation-finder: 2.13
 * weblate-language-data: 2022.5
 * html2text: 2020.1.16
 * pycairo: 1.21.0
 * pygobject: 3.42.1
 * diff-match-patch: 20200713
 * requests: 2.28.0
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.5.12
 * Cython: 0.29.30
 * misaka: 2.1.1
 * GitPython: 3.1.27
 * borgbackup: 1.2.0
 * pyparsing: 3.0.9
 * pyahocorasick: 1.4.4
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.0.12
 * Python: 3.10.5
 * Git: 2.30.2
 * psycopg2: 2.9.3
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * boto3: 1.24.11
 * zeep: 4.1.0
 * aeidon: 1.11
 * iniparse: 0.5
 * mysqlclient: 2.1.0
 * Mercurial: 6.1.4
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 6.2.7
 * PostgreSQL server: 13.7
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mailz.porsche.co.at
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379/1, redis://localhost:6379/1, regular
 * Platform: Linux 3.10.0-1160.25.1.el7.x86_64 (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/latest/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/latest/admin/backup.html

System check identified 2 issues (1 silenced).
```

**Comment by derkoe** [comment]
This could fix it: https://github.com/WeblateOrg/weblate/compare/main...derkoe:fix/java-file-format

Should I create a PR?

**Comment by nijel** [comment]
It works intentionally this way, see https://github.com/WeblateOrg/weblate/issues/2980. Also, the Java documentation seems to disagree with you: https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html

**Comment by derkoe** [comment]
Java internally represents languages in the Locale class - the language tag mentioned in this docs is actually never used in loading translations. 

The properties are loaded in Java via resource bundles which use underscores for separation - see the docs here: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/ResourceBundle.html#getBundle(java.lang.String,java.util.Locale,java.lang.ClassLoader)

See also:
- https://www.oreilly.com/library/view/learning-java-4th/9781449372477/ch10s03.html
- Translations of the most used Java web server Tomcat: https://github.com/apache/tomcat/blob/main/java/jakarta/el/LocalStrings_pt_BR.properties

**Comment by nijel** [comment]
Looking at Hosted Weblate most indeed use underscore. There are some with dash, though. This makes me wonder why nobody complained about this - it is behaving this way for three years...

**Comment by nijel** [comment]
Anyway, as a workaround, you can set language code style to Linux in your component configuration.

The proper fix needs to be more complex than what you've proposed:

- the default language code style for Java Properties can be changed to "linux", tests need to be adjusted
- existing "java" language code style should be renamed, but should be kept as an option, this needs migration of existing component configurations
- the documentation needs to be adjusted as well

**Comment by derkoe** [comment]
I have now changed the style to default and adapted the tests: https://github.com/WeblateOrg/weblate/compare/main...derkoe:fix/java-file-format

But I'm not sure how to deal with the "Java style" option under "Language code style"
