### ISSUE TITLE
Sort button should indicate the current sorting order (ascending or descending)

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#7830]
### Describe the issue

The sort button is always the same (sort-ascending) after the page is loaded.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to any page with the sort button
2. Click the sort button
3. See that the order is changed but the sort button wouldn't change to another(sort-descending to sort-descending or verse vice) after the page is loaded

### Expected behavior

The sort button should indicate the current sorting order (ascending or descending).

### Screenshots

![weblate sort button](https://user-images.githubusercontent.com/49396421/176859448-0060b35d-222c-41c5-9b70-a6f10620081c.gif)

### How do you run Weblate?

weblate.org service

**Comment by ParthS007** [comment]
@nijel Can you please point me to code of the desired sort button or you can also point me to instructions to find this in UI. Thanks

**Comment by nijel** [comment]
I think the issue is not only about missing tooltip, but that the button looks same regardless sorting order.

**Comment by nijel** [comment]
The order is implied in the order string - for example '-priority' and 'priority'. That is the logic implemented here:

https://github.com/WeblateOrg/weblate/blob/531881d360faa842cdd1601a84bc56e1701e4c3c/weblate/static/loader-bootstrap.js#L934-L955

Maybe it's just not working properly or is not triggered, I think this used to work in the past.
