### ISSUE TITLE
Translations are not available for (The translation of the string has changed   meanwhile . Please check your changes . )

### ISSUE THREAD

**Issue by yangyangdaji** [WeblateOrg/weblate#7838]
### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Bug
![Screenshot_20220702_203336_com android chrome](https://user-images.githubusercontent.com/108261729/177002077-6b86f8f7-df10-456d-8c7f-600a1f23303b.jpg)
### Translated
![Screenshot_20220702_203831_com android chrome](https://user-images.githubusercontent.com/108261729/177002080-7c4714f2-28de-4523-b813-5ccdbb0cf032.jpg)
### The interface language is Chinese
![Screenshot_20220702_210858_com android chrome](https://user-images.githubusercontent.com/108261729/177002250-b4e083c7-ff42-47ce-b5a6-d5ad639ec0a8.jpg)

### weblate.org service

**Comment by yangyangdaji** [comment]
@nijel

**Comment by Geeyun-JY3** [comment]
All you need to do is waiting for the deployment of the corresponding commit.： https://github.com/WeblateOrg/weblate/issues/7644#issuecomment-1128479272

**Comment by yangyangdaji** [comment]
OK I will wait for the update

**Comment by yangyangdaji** [comment]
I will convert it to resolve when the string is sync

**Comment by nijel** [comment]
Now deployed on Hosted Weblate.
