### ISSUE TITLE
Addition formatting of a space in diff is missing

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#7849]
### Describe the issue

The addition formatting of space in the diff is missing while it is the leading space of a double space after this addition.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Add a space (U+0020) before a space (U+0020)
2. Switch to the `History` tab
3. See the diff

### Expected behavior

The space should be formatted as an addition besides the double space highlight.

### Screenshots

Example: https://hosted.weblate.org/translate/weblate/documentation/zh_Hans/?checksum=2b52d9f718405ca2
![image](https://user-images.githubusercontent.com/49396421/177369429-46db9ac7-edc2-4174-8f18-c92ae739d316.png)

### How do you run Weblate?

weblate.org service

**Comment by Geeyun-JY3** [comment]
@nijel

**Comment by nijel** [comment]
df0627b34bbe0ac8153520bd09e57ffc6a759f6a should fix it for good.
