### ISSUE TITLE
Weblate WebApp: Translation string but not used (part of the string still in english)

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#7855]
### Describe the issue

When using Weblate translation tool and wanting to add a Comment, help is the only string displayed in English, see:

![Capture 2](https://user-images.githubusercontent.com/1452146/177878396-8f1bb1f8-c7dc-4c9d-b23b-c3abf9b46c6a.png)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to Any string with a "french user"
2. Go to the Comment part
3. Read the Help displayed below the dropdown list (help indicates to pay attention ti the scope of the comment).

### Expected behavior

The string seems to be translated in french, please use it, see https://hosted.weblate.org/translate/weblate/application/fr/?checksum=d66ec268f1b8bd8b.

### Screenshots

See above.

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 4.13.1-dev

### Additional context

No clear if this bug affects all languages or only french?

**Comment by nijel** [comment]
As you can see in the history, the string was translated 6 days ago: https://hosted.weblate.org/translate/weblate/application/fr/?checksum=d66ec268f1b8bd8b#history

The translation is just not yet deployed...

**Comment by ldmpub** [comment]
Thanks 😇
