### ISSUE TITLE
Default (infer) "Repository browser" link template from "Source code repository"

### ISSUE THREAD

**Issue by WofWca** [WeblateOrg/weblate#7865]
### Describe the problem

Unless you explicitly specify "Repository browser" link template, repository browser links will never be generated (they'll remain as text). But we can infer them (at least for popular services like GitHub, GitLab, Bitbucket).

### Describe the solution you'd like

Either fill the "Repository browser" field automatically, or default here: https://github.com/WeblateOrg/weblate/blob/5bfcb775baf855ab89dc373a4901d20dfbe0fb1f/weblate/trans/models/component.py#L1155

### Screenshots

![image](https://user-images.githubusercontent.com/39462442/178154398-ebfe2783-a2b6-4000-96e8-bac6e32a5b87.png)

### Additional context

Inspired by this comment https://github.com/WeblateOrg/weblate/issues/7738#issuecomment-1146638364

**Comment by nijel** [comment]
Currently, these are configured separately, so it's up to the admin to configure it or not. In case it will be automatically generated from VCS location, it should honor the `vcs.view` permission when rendering - to avoid exposing VCS location when not desired. I think it's safe to guard existing repository browser links with this permission.

**Comment by ParthS007** [comment]
@nijel Can you please add some implementation details here. Thanks 👍

**Comment by nijel** [comment]
The following code needs to be expanded to fall back to repo URL-based template if repoweb is not set:

https://github.com/WeblateOrg/weblate/blob/5bfcb775baf855ab89dc373a4901d20dfbe0fb1f/weblate/trans/models/component.py#L1155

* The get_repoweb_link needs to take `User` parameter to check `vcs.view` permission, all callers have to be adjusted to pass it
* The template will be generated for known services based on the repository URL
* If VCS is using merge requests integration (GitHub/GitLab/...) it should get the service type from that
* Otherwise detection should be based on repository URL

**Comment by ParthS007** [comment]
I started working it and I have following findings:

- I am assuming the `repo URL-based template` refers to link of the file in vcs on github/gitlab/.. etc!

- I went through `vcs/git.py` to look for merge requests integration check but I couldn't find any relevant code, where I can see if a VCS is using merge requests integration?
 
- For now, I created a draft on 1 assumption and returning template as path to the repo url + branch.

**Comment by nijel** [comment]
The integration is selected by the `vcs` attribute, I'd probably go with something generic like this:

```python
   methodname = f"generate_{self.vcs}_repoweb_template"
   template = getattr(self, methodname, self.get_git_repoweb_template)

def get_git_repoweb_template(self):
   # Do a repo URL based detection here
   if self.repo looks like GitHub:
        return self.get_github_repoweb_template()
   ...
   return None

def get_github_repoweb_template(self):
   # Extract domain, owner and slug from the repo URL
   return f"https://{domain}/{owner}/{slug}/blob/{{branch}}/{{filename}}#L{{line}}"
```

For parsing the URLs and detecting the services, you might utilize URL detection in the hooks (though that one is for the opposite direction):

https://github.com/WeblateOrg/weblate/blob/b56a360873b9afe851f2909ebb9db42877a6296f/weblate/trans/views/hooks.py#L42-L80

**Comment by ParthS007** [comment]
I added the url detection for services, I was not sure on how the URL will look like for services other than github, so kept them as to do for now. Please let me know if it is the right direction and how can I test the functionality. I went through the tests, i am assuming now I have to test something like this? https://github.com/WeblateOrg/weblate/blob/main/weblate/trans/tests/test_templatetags.py#L129-L149
