### ISSUE TITLE
Missing Fedora messages when a new source string is added to translation

### ISSUE THREAD

**Issue by jojurajan** [WeblateOrg/weblate#7880]
### Describe the issue

Earlier, our consumer for Fedora messages was receiving messages whenever we were adding new source strings to Weblate. With version 4.13, we are no longer seeing those messages being sent out.
The messages that we see right now are for "Translation changed" events.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to the source translation of a component.
2. Add a new translation string.
3. Check the celery-notify logs to verify that a `weblate_fedora_messaging.tasks.fedora_messaging_change` task has been received.
4. You will see no tasks being generated for this change. (Error)
5. Now edit the translation string added in the 2nd step.
6. You will see a `weblate_fedora_messaging.tasks.fedora_messaging_change` task being generated for this change.

### Expected behavior

We should be seeing `weblate_fedora_messaging.tasks.fedora_messaging_change` tasks being received when we add new source strings for translation, either individually or via file upload.

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.13
 * Django: 4.0.5
 * siphashc: 2.1
 * translate-toolkit: 3.7.0
 * lxml: 4.6.5
 * Pillow: 9.1.1
 * bleach: 5.0.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.0
 * django-compressor: 4.0
 * djangorestframework: 3.13.1
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.7.1
 * jellyfish: 0.9.0
 * openpyxl: 3.0.10
 * celery: 5.2.7
 * kombu: 5.2.4
 * translation-finder: 2.13
 * weblate-language-data: 2022.5
 * html2text: 2020.1.16
 * pycairo: 1.21.0
 * pygobject: 3.42.1
 * diff-match-patch: 20200713
 * requests: 2.28.0
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.5.12
 * Cython: 0.29.30
 * misaka: 2.1.1
 * GitPython: 3.1.27
 * borgbackup: 1.2.0
 * pyparsing: 3.0.9
 * pyahocorasick: 1.4.4
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.0.12
 * Python: 3.10.5
 * Git: 2.30.2
 * psycopg2: 2.9.3
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * boto3: 1.24.11
 * zeep: 4.1.0
 * aeidon: 1.11
 * iniparse: 0.5
 * mysqlclient: 2.1.0
 * Mercurial: 6.1.4
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 5.0.7
 * PostgreSQL server: 10.12
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: [REDACTED]
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: amqp://[REDACTED]:[REDACTED]:5672/[REDACTED], redis://:[REDACTED]:6379/3, regular
 * Platform: Linux 5.4.0-77-generic (x86_64)

### Weblate deploy checks

```shell
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E034) The Celery process is outdated or misconfigured. Following items differ: vcs
	HINT: https://docs.weblate.org/en/weblate-4.13/admin/install.html#celery

WARNINGS:
?: (security.W019) You have 'django.middleware.clickjacking.XFrameOptionsMiddleware' in your MIDDLEWARE, but X_FRAME_OPTIONS is not set to 'DENY'. Unless there is a good reason for your site to serve other parts of itself in a frame, you should change it to 'DENY'.

INFOS:
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.13/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 4.13.1.
	HINT: https://docs.weblate.org/en/weblate-4.13/admin/upgrade.html
```

**Comment by jojurajan** [comment]
This is also happening during deletion of source strings. There are no messages being sent via notify or fedora_messaging_change tasks for this action/change.

**Comment by nijel** [comment]
Can you please clarify some details?

- How the new source string is being added?
- What was the exact event you were receiving before?
- Do you get a different event now, or none?

**Comment by jojurajan** [comment]
> Can you please clarify some details?
> 
> * How the new source string is being added?
We are adding the source string via the translations.upload method.

> * What was the exact event you were receiving before?
From our logs, I could gather only a few details:
Topic name -> weblate.new_string_added.dragoman.quad-de.de_AT
```
"component": "quad-de",
"action": "New string added"

```
> * Do you get a different event now, or none?
We are not getting any event right now

**Comment by nijel** [comment]
> This is also happening during deletion of source strings. There are no messages being sent via notify or fedora_messaging_change tasks for this action/change.

I think there was never an event for string removal. Or did it work before?

> We are adding the source string via the translations.upload method.

I've just reproduced this for bilingual translation files and replace method. Is that what you are using?

**Comment by jojurajan** [comment]
Our components are setup for mono-lingual translations. Could that be the issue with missing events during string creation?

**Comment by jojurajan** [comment]
> > This is also happening during deletion of source strings. There are no messages being sent via notify or fedora_messaging_change tasks for this action/change.
> 
> I think there was never an event for string removal. Or did it work before?

I feel the same because we haven't used the deletion messages until now. Would it be fine to create a feature request to push messages when strings are being deleted?

> 
> > We are adding the source string via the translations.upload method.
> 
> I've just reproduced this for bilingual translation files and replace method. Is that what you are using?

Our components are setup for monolingual translations. Could it be that this bug only affects monolingual ones?

**Comment by nijel** [comment]
I've discovered another case where the event is not triggered - when using add method while uploading.

For the delete event, please open a separate feature request.

**Comment by jojurajan** [comment]
@nijel Do we have an update on the fix for the issue with monolingual components? I didn't see any commit being tagged with this ticket.

**Comment by nijel** [comment]
See above:

> [nijel](https://github.com/nijel) closed this as [completed](https://github.com/WeblateOrg/weblate/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/WeblateOrg/weblate/commit/0cc905d6873c922f876e214578f52210092a7b34 [10 days ago](https://github.com/WeblateOrg/weblate/issues/7880#event-6999476128)

It will be included in the 4.14 release

**Comment by jojurajan** [comment]
Just to be clear, this fixes issue with the missing messages for both monolingual and bilingual components.

**Comment by nijel** [comment]
Yes.
