### ISSUE TITLE
Some history activities in Weblate are missing after manually updating the translation file in the repository and pushing the changes to Weblate

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#7882]
### Describe the issue

After manually updating the translation file in the repository and pushing the changes to Weblate, some former changes (history activities) made in Weblate which have already been committed to the repository are missing in Weblate History.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Example: [Languages, components, or the projects they are in, can be removed (deleted from Weblate and remote repository if used) from the menu :guilabel:`Manage` ↓ :guilabel:`Removal` of each project, component, or language.](https://hosted.weblate.org/translate/weblate/documentation/zh_Hans/?checksum=d866ae872df95f0a#history)

After [manually updating the translation file in the repository](https://github.com/WeblateOrg/weblate/commit/7103a74ca6d39992324c9d890cdb0aab35d2aa68#diff-cbff8615c3f4fa9c9984977d26b756367df232a1dd8a3654c522af11ba314abb) and pushing the changes to Weblate, changes (history activities) made by [@yangyangdaji](https://hosted.weblate.org/user/yangyangdaji/) in Weblate which have already been [committed to the repository](https://github.com/WeblateOrg/weblate/commit/df0ab5f66a38b6445f04b9da0f7e4b894da49d76#diff-cbff8615c3f4fa9c9984977d26b756367df232a1dd8a3654c522af11ba314abbL32689-R32687) are [missing in Weblate History](https://hosted.weblate.org/changes/?user=yangyangdaji&component=documentation&project=weblate&lang=zh_Hans&action=27&user=yangyangdaji&start_date=&end_date=2022-07-03). The corresponding changes now becomes a “String updated in the repository” type history activity by “None”, while some history activities whose corresponding changes are in the same commit still can be found in Weblate History, such as [Rebases Weblate commits on top of upstream repository on update. This provides clean history without extra merge commits.](https://hosted.weblate.org/translate/weblate/documentation/zh_Hans/?checksum=87e822f46a7ab778#history) (in [history](https://hosted.weblate.org/changes/?user=yangyangdaji&component=documentation&project=weblate&lang=zh_Hans&action=27&user=yangyangdaji&start_date=&end_date=2022-07-03)).

### Expected behavior

The original history would not be lost after manually updating the translation file in the repository.

### Screenshots

![image](https://user-images.githubusercontent.com/49396421/178683346-432641b7-fac0-4a4c-a60d-4fdabd37b8a9.png)

### How do you run Weblate?

weblate.org service

**Comment by Geeyun-JY3** [comment]
Why is there a “Resource update” action ([The "`docs/locales/zh_Hans/LC_MESSAGES/docs.po`" file was changed.”](https://hosted.weblate.org/changes/?page=5&limit=20&component=documentation&project=weblate&action=0&end_date=2022-07-14)) which only happened to the Simplified Chinese translation of [Document component](https://hosted.weblate.org/projects/weblate/documentation/zh_Hans/) before the [translation file really changed in the repository](https://github.com/WeblateOrg/weblate/commit/cddd2d536290a20996b904365f6b80dc33a4d0e2)?
![image](https://user-images.githubusercontent.com/49396421/179130508-cdcbf08b-66b3-4061-97c0-b004c2b21baa.png)

What happened to the [Weblate project](https://hosted.weblate.org/projects/weblate/) on Hosted Weblate? Is it related to the configuration changed about #7887 (Right after the https://github.com/WeblateOrg/weblate/issues/7887#issuecomment-1184367521)?

**Comment by Geeyun-JY3** [comment]
> The history for a string is deleted only in case the string is removed. So, there seems to be some issue with the update which is causing removing the strings and later adding them back...

Actually, when I reported https://github.com/WeblateOrg/weblate/issues/7882#issue-1303060325, that example string was not removed as you can see that the previous “New translation” action by [@Yangyulin](https://hosted.weblate.org/user/Yangyulin/) in the screenshot.

But https://github.com/WeblateOrg/weblate/issues/7882#issuecomment-1184557576 really removed the strings and later added them back…

**Comment by Geeyun-JY3** [comment]
I think this issue should keep open until really fixed.

**Comment by Geeyun-JY3** [comment]
@nijel

**Comment by nijel** [comment]
https://github.com/WeblateOrg/weblate/pull/7894 might have fixed that, so I'd keep this closed until we see another occurrence. Alow, we now have better logging in place, that should make diagnosing the issue possible.
