### ISSUE TITLE
There is no translator credit in the file header of the PO file of the Weblate document

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#7887]
### Describe the issue

There is no translator credit in the file header of the PO file of the Weblate document (https://github.com/WeblateOrg/weblate/tree/main/docs/locales).

Is it intended? Or a bug?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Example:

- https://github.com/WeblateOrg/weblate/commit/eb5d83991e48f9fadfa4ae5f59c5707557f9eb17
- https://github.com/WeblateOrg/weblate/commit/fb1c3de8ab24a6148cbeaa4fd58f3402e94617f1

### Expected behavior

Credit all translators of the Weblate document

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Not intended, Weblate was just not configured to do so. I've just changed that.

**Comment by Geeyun-JY3** [comment]
@nijel Why are most of the strings in the Simplified Chinese translation of [Document](https://hosted.weblate.org/projects/weblate/documentation/zh_Hans/) component lost😨?
![image](https://user-images.githubusercontent.com/49396421/178983598-c8ed451e-cd10-429a-89fb-c9bba168f6f6.png)

**Comment by nijel** [comment]
Let's deal with that in #7882.
