### ISSUE TITLE
Restrict access for review group by language

### ISSUE THREAD

**Issue by rsr-cs** [WeblateOrg/weblate#7893]
### Describe the problem

We want to give access rights for reviewers for a specific language and project wise. I like the idea to have a review group to assign users to. I created an additional group for the language but it is not combined with the review group of the project. 

### Describe the solution you'd like

I would like to have an option to restrict access to specific languages for review groups of the project. 

### Describe alternatives you've considered

See above. I thought to assign two groups, the review group of the project and a group with language option. But the acess rights of the review group supersede the language group.

### Screenshots

![Screenshot 2022-07-14 191853](https://user-images.githubusercontent.com/84009557/179044585-9b414964-ff3e-4900-82ea-4948f0146e19.png)
This is the only option for the group Reviewer HU
![grafik](https://user-images.githubusercontent.com/84009557/179044927-d8b2abcc-d9cf-4c64-9347-84773fcf14d8.png)

**Comment by nijel** [comment]
The user permissions are union of all permissions he gets from groups. So if you want to exclude Hungarian from the "Review" group, you need to adjust language selection for it to exclude it as well.
