### ISSUE TITLE
Send notify/fedora messages when a source or translation unit is being deleted. 

### ISSUE THREAD

**Issue by jojurajan** [WeblateOrg/weblate#7899]
### Describe the problem

We use Fedora consumer for propagating changes from Weblate back to our legacy translation systems. Currently, we don't have a way to know when a translation/source string is being deleted from Weblate other than fetching data via API and comparing them.

### Describe the solution you'd like

To keep the translations in sync, we would like to get Fedora/notify messages when someone deletes a source/translation unit from Weblate.

**Comment by sandratoo** [comment]
Hi, can I try this out?

**Comment by nijel** [comment]
Yes! What needs to be done:

* Add new event to the `Change` model to track these (ACTION_STRING_REMOVE)
* Adjust delete endpoints to generate change entry

Once this is done, it will automatically end up in notifications.
