### ISSUE TITLE
[IME][Mac] Hitting Enter fires searching even while in text edit mode

### ISSUE THREAD

**Issue by 2rara** [WeblateOrg/weblate#7905]
### Describe the issue

When you use a CJK IME such as the default Japanese IME on Mac, hittting Enter fires searching even when you're in text edit mode. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to any of your translation projects.
2. Go to the search tab.
3. Focus the search box for target strings and translated texts.
4. Enable the Hiragana input mode of Mac's default Japanese IME (choose the Romaji input mode).
5. Press A and Enter.

### Expected behavior

It prints out the letter あ without firing searching.

### Screenshots

<img width="428" alt="スクリーンショット 2022-07-19 19 53 37" src="https://user-images.githubusercontent.com/27809401/179817143-ac71a6fb-011d-4782-afc8-316272616ab6.png">

### How do you run Weblate?

Other

### Weblate versions

Weblate 4.4 (I also checked with 4.13 on https://translate.fedoraproject.org/projects/authselect/#search, and the issue reproduced.)

### Weblate deploy checks

```shell
(I'm not the sysadmin of this Weblate instance.)
```

### Additional context

Hitting Enter is commonly used to just confirm an input text in Japanese. Hitting Enter against a confirmed text should fire searching, but not when the text is still unconfirmed.

**Comment by nijel** [comment]
AFAIK we don't do any special handling here - it's a regular input in a form, browser does the submission...

**Comment by 2rara** [comment]
@nijel Thank you for checking. I also just tried more browsers, and the issue reproduces on Safari 15.5, Vivaldi 5.3 and Chrome 103, but not on Firefox 102. It could be an issue on the Webkit/Blink browser engine side.
I will report this to those projects if they aren't their known issues, and write an update here.

**Comment by 2rara** [comment]
The Chromiuem team says the issue won't be fixed. Their comment might help the Weblate team find a potential issue in the platform.

> This is working as intended. The webpage hooks a mousedown callback on input#id_q that fires search on "Enter" key down. It seems that this page is not designed with IME input in mind. I suggest you to contact the website owner. 
Closing, but please reopen if you think that this is wrong.

https://bugs.chromium.org/p/chromium/issues/detail?id=1349328#c4

**Comment by nijel** [comment]
Okay, so I was wrong here, I thought we're relying on the browser in this...
