### ISSUE TITLE
Possibility of incorrect data usage, Awaiting translation suggestions

### ISSUE THREAD

**Issue by manifesttim** [WeblateOrg/weblate#7924]
### Describe the issue

Hello,

I am facing some confusion. I created an account on translate.getmonero.org using my own choice's username and password, and today I happened to bump upon a file downloaded on my phone called translate / grk, containing a username and a password that have been given to me in order to perhaps register with them. Now, the problem I assume is if those were the required data I had to make an account would I have to proceed in creating this as I've read in the file? Would it not be possible to transfer my already done translations from one account to another if I were to switch accounts? Also, another thing I would like to point out is that I have completed quite a few translations of oth Greek and Korean for Monero and most of them remain only suggested. I was told if I were to complete a number of them I would not have to contiunue for much longer and follow the next step in submitting a CSS proposal. Could yo u let me know if I have to keep going until a certain number to be qualified for a continue?

Thank you,

Panagiota Zarra

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Screenshots

![screenshot1](https://user-images.githubusercontent.com/108767820/180856832-eb67dc71-29b1-4efe-92a9-200fdb0bf67d.png)
![screenshot2](https://user-images.githubusercontent.com/108767820/180856876-4d60d7c6-6cf8-4610-a576-7b7ed6f28d23.png)
![screenshot3](https://user-images.githubusercontent.com/108767820/180856920-ffc685e8-79df-4de6-a67b-e82e94578bfc.png)

### How do you run Weblate?

Git checkout

**Comment by nijel** [comment]
We're not operating https://translate.getmonero.org/, please use support contacts on that website.

**Comment by Ze-oZ** [comment]
> ### Describe the issue
> Hello,
> 
> I am facing some confusion. I created an account on translate.getmonero.org using my own choice's username and password, and today I happened to bump upon a file downloaded on my phone called translate / grk, containing a username and a password that have been given to me in order to perhaps register with them. Now, the problem I assume is if those were the required data I had to make an account would I have to proceed in creating this as I've read in the file? Would it not be possible to transfer my already done translations from one account to another if I were to switch accounts? Also, another thing I would like to point out is that I have completed quite a few translations of oth Greek and Korean for Monero and most of them remain only suggested. I was told if I were to complete a number of them I would not have to contiunue for much longer and follow the next step in submitting a CSS proposal. Could yo u let me know if I have to keep going until a certain number to be qualified for a continue?
> 
> Thank you,
> 
> Panagiota Zarra
> 
> ### I already tried
> * [x]  I've read and searched [the documentation](https://docs.weblate.org/).
> * [x]  I've searched for similar issues in this repository.
> 
> ### Steps to reproduce the behavior
> 1. Go to '...'
> 2. Scroll down to '...'
> 3. Click on '...'
> 4. See error
> 
> ### Expected behavior
> _No response_
> 
> ### Screenshots
> ![screenshot1](https://user-images.githubusercontent.com/108767820/180856832-eb67dc71-29b1-4efe-92a9-200fdb0bf67d.png) ![screenshot2](https://user-images.githubusercontent.com/108767820/180856876-4d60d7c6-6cf8-4610-a576-7b7ed6f28d23.png) ![screenshot3](https://user-images.githubusercontent.com/108767820/180856920-ffc685e8-79df-4de6-a67b-e82e94578bfc.png)
> 
> ### Exception traceback
> _No response_
> 
> ### How do you run Weblate?
> Git checkout
> 
> ### Weblate versions
> _No response_
> 
> ### Weblate deploy checks
> _No response_
> 
> ### Additional context
> _No response_



> ### Describe the issue
> Hello,
> 
> I am facing some confusion. I created an account on translate.getmonero.org using my own choice's username and password, and today I happened to bump upon a file downloaded on my phone called translate / grk, containing a username and a password that have been given to me in order to perhaps register with them. Now, the problem I assume is if those were the required data I had to make an account would I have to proceed in creating this as I've read in the file? Would it not be possible to transfer my already done translations from one account to another if I were to switch accounts? Also, another thing I would like to point out is that I have completed quite a few translations of oth Greek and Korean for Monero and most of them remain only suggested. I was told if I were to complete a number of them I would not have to contiunue for much longer and follow the next step in submitting a CSS proposal. Could yo u let me know if I have to keep going until a certain number to be qualified for a continue?
> 
> Thank you,
> 
> Panagiota Zarra
> 
> ### I already tried
> * [x]  I've read and searched [the documentation](https://docs.weblate.org/).
> * [x]  I've searched for similar issues in this repository.
> 
> ### Steps to reproduce the behavior
> 1. Go to '...'
> 2. Scroll down to '...'
> 3. Click on '...'
> 4. See error
> 
> ### Expected behavior
> _No response_
> 
> ### Screenshots
> ![screenshot1](https://user-images.githubusercontent.com/108767820/180856832-eb67dc71-29b1-4efe-92a9-200fdb0bf67d.png) ![screenshot2](https://user-images.githubusercontent.com/108767820/180856876-4d60d7c6-6cf8-4610-a576-7b7ed6f28d23.png) ![screenshot3](https://user-images.githubusercontent.com/108767820/180856920-ffc685e8-79df-4de6-a67b-e82e94578bfc.png)
> 
> ### Exception traceback
> _No response_
> 
> ### How do you run Weblate?
> Git checkout
> 
> ### Weblate versions
> _No response_
> 
> ### Weblate deploy checks
> _No response_
> 
> ### Additional context
> _No response_



> ### Describe the issue
> Hello,
> 
> I am facing some confusion. I created an account on translate.getmonero.org using my own choice's username and password, and today I happened to bump upon a file downloaded on my phone called translate / grk, containing a username and a password that have been given to me in order to perhaps register with them. Now, the problem I assume is if those were the required data I had to make an account would I have to proceed in creating this as I've read in the file? Would it not be possible to transfer my already done translations from one account to another if I were to switch accounts? Also, another thing I would like to point out is that I have completed quite a few translations of oth Greek and Korean for Monero and most of them remain only suggested. I was told if I were to complete a number of them I would not have to contiunue for much longer and follow the next step in submitting a CSS proposal. Could yo u let me know if I have to keep going until a certain number to be qualified for a continue?
> 
> Thank you,
> 
> Panagiota Zarra
> 
> ### I already tried
> * [x]  I've read and searched [the documentation](https://docs.weblate.org/).
> * [x]  I've searched for similar issues in this repository.
> 
> ### Steps to reproduce the behavior
> 1. Go to '...'
> 2. Scroll down to '...'
> 3. Click on '...'
> 4. See error
> 
> ### Expected behavior
> _No response_
> 
> ### Screenshots
> ![screenshot1](https://user-images.githubusercontent.com/108767820/180856832-eb67dc71-29b1-4efe-92a9-200fdb0bf67d.png) ![screenshot2](https://user-images.githubusercontent.com/108767820/180856876-4d60d7c6-6cf8-4610-a576-7b7ed6f28d23.png) ![screenshot3](https://user-images.githubusercontent.com/108767820/180856920-ffc685e8-79df-4de6-a67b-e82e94578bfc.png)
> 
> ### Exception traceback
> _No response_
> 
> ### How do you run Weblate?
> Git checkout
> 
> ### Weblate versions
> _No response_
> 
> ### Weblate deploy checks
> _No response_
> 
> ### Additional context
> _No response_

**Comment by Ze-oZ** [comment]
Γεια σού Παναγιώτα, δυστυχώς δεν υπάρχει κανένας άλλος που να μεταφράζει στα Ελληνικά αυτό το διάστημα, έχω εγκρίνει σχεδόν όλες τις μεταφράσεις σου, αν θες μπορείς να μου στειλεις ενα μαιλ για συνεργασία /συντονισμό  για την υπόλοιπη μετάφραση ... βέβαια μόνο εαν ενδιαφερεσαι ακόμα :)

zeoz_olikis@proton.me
