### ISSUE TITLE
Marking glossary term as read-only doesn't add the flag properly. Also adding untranslatable strings. 

### ISSUE THREAD

**Issue by mimkorn** [WeblateOrg/weblate#7940]
### Describe the issue

When I create a glossary term and mark it as untranslatable it doesn't add read-only properly to other languages and still wants me to translate the term. I have to go to a translation and add read-only by writing it. Clicking the button Mark as Read-only doesn't work properly. Please observe the gif: https://share.cleanshot.com/f1dmhT

Sorry for not adding much additional details, I can live without this being fixed, but wanted to share my finding just in case you'd want to do something about it anyway. Didn't have much more time filling out the other fields.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Observe the gif. https://share.cleanshot.com/f1dmhT

Create a glossary term as untranslatable and part of terminology.

### Expected behavior

Would not require me

### Screenshots

https://share.cleanshot.com/f1dmhT

### How do you run Weblate?

Docker container

### Weblate versions

4.13

**Comment by nijel** [comment]
I'm unsure right now, but maybe the updating happens in the background. Have you tried reloading the page again once doing the change?

Still, such behavior would be a bug...

**Comment by mimkorn** [comment]
Yeah, it didn't work correctly even with a refresh. Actually, I found
multiple unrelated bugs (around 5) with the glossary (which renders it
unusable for us for the moment). Seems like you're a Czech Native. I also
live in Czech. I'm a Slovak native. If you're interested, we could do a
quick call together, and I'd share my findings with you via a short screen
share session. It would be probably more efficient, you'd be able to ask
things live and do quick checks like "could you refresh page" ad hoc. So
far, we've evaluated Glossary functionality as not usable for the moment,
so it's not a pressing matter for us, but we'd surely try using it again if
we'd find that the bugs are not there anymore.

Let me know what you think.

Šimon
