### ISSUE TITLE
question about q parameter - filtered downloaded strings - on REST API GET /api/translations/(string:project)/(string:component)/(string:language)/file/ 

### ISSUE THREAD

**Issue by hwblts1** [WeblateOrg/weblate#7941]
### Describe the issue

We have a question regarding Weblate REST API 

`GET /api/translations/(string:project)/(string:component)/(string:language)/file/ `

and `q parameter` - filter downloaded strings

In the documentation for Weblate's REST API it is mentioned that downloading all the translation files in a .zip file there is support for query:
https://docs.weblate.org/en/latest/api.html#get--api-components-(string-project)-(string-component)-file-
https://docs.weblate.org/en/latest/user/search.html
https://docs.weblate.org/en/latest/user/search.html#search-operators

However in the documentation for downloading a translation file for a specific language this is not mentioned:
https://docs.weblate.org/en/latest/api.html#get--api-translations-(string-project)-(string-component)-(string-language)-file-

In postman this URL seems to return filtered results:
<host>/api/translations/(string:project)/(string:component)/(string:language)/file/?format=json&q=state:>=translated

Was this (accidentally) omitted from documentation? Or is this deprecated (or getting deprecated)?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

In postman this URL seems to return filtered results:
<host>/api/translations/(string:project)/(string:component)/(string:language)/file/?format=json&q=state:>=transl

### Expected behavior

describe in Weblate documentation 

https://docs.weblate.org/en/latest/api.html#get--api-translations-(string-project)-(string-component)-(string-language)-file-

if there is support for query

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
The `q` parameter is documented at wrong endpoint, the one for ZIP download doesn't support this.
