### ISSUE TITLE
Unable to create translation from "Upload Document" - Monolingual base language file (file does not exist)

### ISSUE THREAD

**Issue by Kentoseth** [WeblateOrg/weblate#7943]
### Describe the issue

So firstly I would like to say that I commend and thank you for making this wonderful software and allowing people to use it gratis for Libre projects.

However, in order to translate non-dev translations (like a book or document) is needlessly complex and has resulted in what I think is a bug:

I was trying to upload a new component in my Project via the "upload document" option.

[matn-mod.txt](https://github.com/WeblateOrg/weblate/files/9214454/matn-mod.txt)

(attached document is a .txt file)

The first page allows me to upload the document but the next step forces me to "Specify configuration manually", without being able to proceed without choosing this:

![box_1](https://user-images.githubusercontent.com/2989402/181644485-f7697501-5f54-4834-a4f0-d3dc2daffc3a.png)

Now I proceed to the bug below.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to 'create new translation component'
2. upload matn-txt file
3. choose manual configuration option
4. in manual configuration, fill in necessary details
5. for "filemask" I used: *.txt
6. for "Monolingual base language file" I used: matn-mod.txt
7. Error: "File does not exist."

### Expected behavior

I expected that the file would be found as I uploaded it. I thought maybe the '-' is an issue, so I also tried "matnmod.txt" as an uploaded file and then added in "Monolingual base language file" as "matnmod.txt" with the same error.

### Screenshots

![details_1](https://user-images.githubusercontent.com/2989402/181645257-e61fb2aa-e3bb-4d27-9fc7-f55815e0cbb9.png)

----------------

![details_2](https://user-images.githubusercontent.com/2989402/181645267-ab60969d-25ec-4d61-895d-783e3af1e13f.png)

### Exception traceback

```pytb
None. This is on hosted weblate.
```

### How do you run Weblate?

weblate.org service

### Additional context

I would suggest simplifying the Document translate option. It is too complex for non-technical users and they would likely give up when attempting to fill in the manual config details.

**Comment by Kentoseth** [comment]
Thanks for the quick response.

Is there another (text) document format I can use instead of .txt that might resolve this?

**Comment by nijel** [comment]
The issue is not in the txt formats, but rather in the setup - you need to manually guess the filemask - it is `<component_slug>/*.txt`, monolingual base file should be `<component_slug>/<source_language_code>.txt`.

**Comment by razor313** [comment]
I have the same issue but with Android format!

<img width="984" alt="Screenshot 2023-06-13 at 15 14 09" src="https://github.com/WeblateOrg/weblate/assets/26047366/ec4d8e1c-4475-4f56-b1c9-e65c3d73f1ea">

I uploaded documents stored in the internal repository `(local:)`
