### ISSUE TITLE
REST API - Searching in other scopes

### ISSUE THREAD

**Issue by endervad** [WeblateOrg/weblate#7951]
### Describe the problem

According to the REST API documentation, it seems like currently it's only possible to search inside a single language file of a component in a project using `q` parameter: https://docs.weblate.org/en/latest/api.html#get--api-translations-(string-project)-(string-component)-(string-language)-units-
I'd like to request making it possible to search globally through API, same as how in web `https://<url>/search/?q=` works. It would probably make sense to introduce similar search methods to other scopes, like project or component (not in a single language file).

### Describe the solution you'd like

`GET /api/translations/(string:project)/(string:component)/units/?q=`
`GET /api/translations/(string:project)/units/?q=`
`GET /api/translations/units/?q=` or maybe `GET /api/units/?q=`

Response JSON Object:
* results (array) – array of component objects ( `GET /api/units/(int:id)/` )

**Comment by nijel** [comment]
I'd stick with `/api/units/?q=`. It is an existing endpoint, it just needs to implement searching. And you can search for project/component/language via the search query to achieve additional filtering.
