### ISSUE TITLE
env setting ENABLE_SHARING not working

### ISSUE THREAD

**Issue by wilcopots** [WeblateOrg/weblate#7976]
### Describe the issue

We are running Weblate in a **docker environment,** and one of the custom setting we would like is to disable the share menu both on the project page as on the component page. 

I have set the ENABLE_SHARING to false, but it does not seem to have effect on this menu. 

Documentation I followed for this setting:
https://docs.weblate.org/no/latest/admin/config.html#enable-sharing

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

In our docker.yml we are setting 
environment: 
WEBLATE_ENABLE_SHARING: false

### Expected behavior

When ENABLE_SHARING is false, I expect there is no share menu with items ( Share on Facebook / Tweet this translation! / Engage page / Status widgets ) visible.

### How do you run Weblate?

Docker container

### Weblate versions

Using the docker image: 
weblate/weblate:4.13.1-2

**Comment by nijel** [comment]
This setting is currently not exposed via environment for the Docker container, see https://docs.weblate.org/no/latest/admin/install/docker.html for list of supported settings.
