### ISSUE TITLE
Confirmation on user deletion

### ISSUE THREAD

**Issue by wilcopots** [WeblateOrg/weblate#7977]
### Describe the problem

On the user detail page (/user/[username]/#edit), on the bottom of the page there is an option to delete the user, via button 'Delete'. 
This button is right next to the 'Save' button. 

If for any reason you miss-click on 'Save', and thereby click on 'Delete'. The user is deleted immediately and not able to restore. 

### Describe the solution you'd like

It would be ideally if there is a confirmation page after request for deletion, likewise the same as there is for deleting a component or project. In that case you won't accidentally irreversible delete the user.  

### Screenshots

<img width="301" alt="Screenshot 2022-08-05 at 15 54 37" src="https://user-images.githubusercontent.com/17179724/183092301-71006ad0-8fce-418e-8637-a5dc6cafdafe.png">

### Additional context

Using Weblate 4.13.1

**Comment by shashwatpandeyvns** [comment]
Hi,
I would like contribute to the project. How can start this journey? Please, Enlighten me.

**Comment by nijel** [comment]
You're welcome to contribute!

The current delete button is here:

https://github.com/WeblateOrg/weblate/blob/c8f507972102558803f29abb0f1cfacd048c3a96/weblate/templates/accounts/user.html#L291-L296

It needs to include a confirmation popup like it is done here for removing a user from a project:

https://github.com/WeblateOrg/weblate/blob/c8f507972102558803f29abb0f1cfacd048c3a96/weblate/templates/trans/project-access-row.html#L44-L59

**Comment by shashwatpandeyvns** [comment]
I was trying to install Weblate on wsl for testing purposes, but it failed every time with - ERROR: Could not build wheels for borgbackup which use PEP 517 and cannot be installed directly. Any Idea what's going on here?

**Comment by nijel** [comment]
Maybe you're missing some of the system dependencies, please check corresponding distro guide at https://docs.weblate.org/en/latest/admin/install.html

**Comment by DiegoCaraballo** [comment]
Hello @nijel how are you?
I would like to contribute.
Can I start with this?
Regards!

**Comment by nijel** [comment]
@DiegoCaraballo Yes, contributions are always welcome!

**Comment by prakhar1144** [comment]
Hey all,
I have started working on this issue.

**Comment by alexjensen2002** [comment]
Oh, my apologies @prakhar1144 I forgot to say I started working on this earlier. I'm pretty much done with it, though I'm not entirely clear on how or whether I need to do unit tests/etc for this, since it's just an HTML change.

@nijel how would I go about making a pull request and/or getting feedback on if my code is ready to merge?

**Comment by alexjensen2002** [comment]
Oh, oops, I didn't see the compare across forks button before so I thought that I couldn't make a PR for some reason haha.

I wasn't sure how to do unit tests or squash commits, so for now this is just a draft PR. 
I'm using WSL and Docker for my setup, by the way, so if you have any way to help me there that would be appreciated. When I try to use rundev.sh to test it doesn't find any tests, so I assume I'm missing some sort of setup.
