### ISSUE TITLE
Clarify two different lookups related to “state”

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#7980]
### Describe the problem

There are two different lookups related to “state”: `state:TEXT` and `is:TEXT`.
It is confusing.

### Describe the solution you'd like

Clarify these two different lookups in the documentation.

**Comment by nijel** [comment]
`state` looks only at state, while `is` can handle additional lookups.

For example:

* `is:translated` is same as `state:>=translated`
* `is:untranslated` is same as `state:<translated`
* `is:pending` is not looking at string state at all

**Comment by Geeyun-JY3** [comment]
https://docs.weblate.org/en/latest/user/search.html#fields

> `state:TEXT`
> State search (`approved`, `translated`, `needs-editing`, `empty`, `read-only`), supports [Field operators](https://docs.weblate.org/en/latest/user/search.html#search-operators).

> is:TEXT
> Search for string states (pending, translated, untranslated).

The description of these two fields in the documentation are quite simple and similar.
More detailed explanation is needed.

**Comment by QuocNguyen2412** [comment]
Hi, I would like to work on this.

**Comment by nijel** [comment]
Any contributors are welcome!

**Comment by Geeyun-JY3** [comment]
I still have questions about the `is:TEXT` lookup.

According to the source code: https://github.com/WeblateOrg/weblate/blob/bda83e3c28f135e88af5b122770bbb146c690059/weblate/utils/search.py#L192-L202

- `is:read-only` is same as `state:read-only`
- `is:approved` is same as `state:approved`
- `is:needs-editing` is same as `state:needs-editing`
- `is:translated` is same as `state:>=translated`
- `is:untranslated` is same as `state:<translated`

I still wonder why the logic of `is:read-only`, `is:approved` and `is:needs-editing` is different from `is:translated` and `is:untranslated`.

And why the `is:TEXT` was created as a lookup different from the `state:TEXT` in the begining.

**Comment by nijel** [comment]
It provides additional queries. It's not uncommon to build a query language with more ways to query the same thing – it makes it easier for a user to write the query. For example, GitHub has this as well: https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-open-or-closed-state

**Comment by Geeyun-JY3** [comment]
I still think it is necessary to detail the function of every available `is:TEXT` lookup in the documentation. Since the logic of the `is:TEXT` lookup is currently inconsistent (as [listed above](https://github.com/WeblateOrg/weblate/issues/7980#issuecomment-1294387083)).
https://github.com/WeblateOrg/weblate/commit/59961d62189378ecbc0d809c4a091432f6d09ead#diff-3eb290919f61bddd29299720477d0001574593aa098ddaf1e41011adb8ebfc3aR50 is not enough and the documentation is still unclear.

**Comment by nijel** [comment]
Okay reopening.
