### ISSUE TITLE
Repository maintenance page does not load when using weblate:// repository

### ISSUE THREAD

**Issue by Derkades** [WeblateOrg/weblate#7982]
### Describe the issue

When a component uses a `weblate://` path for Settings > Version control > Source code repository, going to Manage > Repository maintenance produces the following message:
 
> Error while loading page: error (0): undefined

Most settings can be managed from the component that "owns" the repository, like pulling/pushing. However, the lock button only affects the one component, not any other components sharing the repository. This makes it impossible to lock a component using a `weblate://` repository.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Create component A with Git repository (not sure about other VCS)
2. Create component B that shares the repository from component A, using `weblate://`
3. Try to lock component B by visiting Manage > Repository Maintenance

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.13.1
 * Django: 4.0.6
 * siphashc: 2.1
 * translate-toolkit: 3.7.1
 * lxml: 4.6.5
 * Pillow: 9.2.0
 * bleach: 5.0.1
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.0
 * django-compressor: 4.0
 * djangorestframework: 3.13.1
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.7.1
 * jellyfish: 0.9.0
 * openpyxl: 3.0.10
 * celery: 5.2.7
 * kombu: 5.2.4
 * translation-finder: 2.13
 * weblate-language-data: 2022.5
 * html2text: 2020.1.16
 * pycairo: 1.21.0
 * pygobject: 3.42.1
 * diff-match-patch: 20200713
 * requests: 2.28.1
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.6.0
 * Cython: 0.29.30
 * misaka: 2.1.1
 * GitPython: 3.1.27
 * borgbackup: 1.2.1
 * pyparsing: 3.0.9
 * pyahocorasick: 1.4.4
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.1.0
 * Python: 3.10.5
 * Git: 2.30.2
 * psycopg2: 2.9.3
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * boto3: 1.24.23
 * zeep: 4.1.0
 * aeidon: 1.11
 * iniparse: 0.5
 * mysqlclient: 2.1.1
 * Mercurial: 6.1.4
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 6.2.7
 * PostgreSQL server: 13.7
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: [removed]
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.15.0-40-generic (x86_64)

**Comment by nijel** [comment]
It should work. Are there any errors in the server logs? Sent to admins e-mail?

**Comment by Derkades** [comment]
Apologies for the noise, turns out this is not a weblate issue. The component happened to have the URL "cookie-consent", which was being blocked by one of the cookie popup filters in uBlock origin...
