### ISSUE TITLE
Download also populated translations for offline translation

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#7983]
### Describe the problem

In https://hosted.weblate.org/projects/readyou/android-strings/nb_NO/#download
I can't download anything that doesn't strip out the original strings.

### Describe the solution you'd like

A "Prefill translation with source"
Fills in translation strings with source string.  (which it is called in the plugins)

### Describe alternatives you've considered

Going to the  source (English) equivalent, download the file from there, and then change the name before uploading.

### Screenshots

(The choices available now)
![image](https://user-images.githubusercontent.com/13802408/183506398-a8cfdd11-b83d-4fef-ae09-9f7bf417dff7.png)

(From the plugins)
![image](https://user-images.githubusercontent.com/13802408/183507024-cff81409-4970-4054-84c3-7fe97628c952.png)

### Additional context

It says "Suitable for offline translation", but having only the keys to go by gets difficult quickly.
Not sure if this concerns only Android strings, or all mono files.

**Comment by nijel** [comment]
That's why there are bilingual formats to download as well (CSV/XLIFF/gettext/XLSX).
