### ISSUE TITLE
You do not have permission to perform this action.

### ISSUE THREAD

**Issue by S-lear** [WeblateOrg/weblate#7992]
### Describe the issue

I am the admin account and upload the translation json file through restful api (POST /api/translations/(string:project)/(string:component)/(string:language)/file/).
Some components report: You do not have permission to perform this action.
Some are successful.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Maybe the method you are using is not applicable to the translation? See https://docs.weblate.org/en/latest/user/files.html#import-methods
