### ISSUE TITLE
Add "auto-complete suggestions" to "Add a user" feature in user management for any given project

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#7998]
### Describe the problem

With many users helping us with translations, it can be quite tricky to add the right user to a project. You need to know the user name you want to add.

### Describe the solution you'd like

Perhaps it is possible to enhance the **User to add** text box with the same auto-lookup which you have when entering a **Comment** using markdown "@".

 
![image](https://user-images.githubusercontent.com/26718215/184297463-f3e5de09-9a3f-48e1-88d3-656a9aa020da.png)

### Additional context

Thanks so much for considering this. ;-)

**Comment by andhikalfariz** [comment]
helo sir, may I try to fix this isse?

**Comment by Ravina-Deogadkar** [comment]
Can I take this issue?

**Comment by nijel** [comment]
Yes, anybody is welcome to contribute!

**Comment by andhikalfariz** [comment]
Okay thank you sir! May I get assigned for this issue?

**Comment by nijel** [comment]
Okay, I've just assigned you!

**Comment by Ravina-Deogadkar** [comment]
Is there anything else I can work on?

**Comment by nijel** [comment]
@Ravina-Deogadkar There are a lot of issues to start with: https://github.com/WeblateOrg/weblate/labels/good%20first%20issue
