### ISSUE TITLE
The search result doesn't exist when clicked

### ISSUE THREAD

**Issue by yangyangdaji** [WeblateOrg/weblate#8003]
# The search result doesn't exist when clicked
@Geeyun-JY3:
> 
> 1. Open the [browse view of Flathub/flathub.org — Chinese (Simplified)](https://hosted.weblate.org/browse/flathub/frontend/zh_Hans/).
> 2. Search `帐户`  browse view.
> 3. Change all `帐` to `账`.
> 4. Reload the browse view page (searching `帐户`).
> 5. All the matching results in 2 are still shown in 1 while using the same browser, though their target strings no longer contain `帐` after the changes done in 3.

### [search results](https://hosted.weblate.org/browse/flathub/frontend/zh_Hans/?offset=1&q=%E5%B8%90%E6%88%B7&sort_by=-priority%2Cposition&checksum=)

![Videoframe_20220815_121936_com huawei himovie](https://user-images.githubusercontent.com/108261729/184576434-d390970e-a749-4462-8c1b-cbbdaa295cd8.jpg)
![Videoframe_20220815_115912_com huawei himovie](https://user-images.githubusercontent.com/108261729/184576442-7a1b5718-f6ee-4c5c-9ac8-731715c37a97.jpg)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Weblate 4.14-dev

**Comment by nijel** [comment]
Does the error persist? There is server-side caching of the search results, which could cause this in some corner cases.

**Comment by yangyangdaji** [comment]
> Does the error persist? There is server-side caching of the search results, which could cause this in some corner cases.

Yes ,see https://hosted.weblate.org/browse/flathub/frontend/zh_Hans/?offset=1&q=%E5%B8%90%E6%88%B7&sort_by=-priority%2Cposition&checksum=

**Comment by yangyangdaji** [comment]
Changed browser problem solved

**Comment by yangyangdaji** [comment]
By the way ,The original browser I deleted cache
![Screenshot_20220815_145009_com android chrome](https://user-images.githubusercontent.com/108261729/184589760-b844c8fd-0cdf-4072-b48f-7105deacc665.jpg)

The problem remains

**Comment by yangyangdaji** [comment]
@nijel

**Comment by nijel** [comment]
The link you've sent ends up with "No strings found!"

**Comment by yangyangdaji** [comment]
I re-installed browser

![ok](https://foruda.gitee.com/images/1660554569924759467/screenshot_20220815_170611.jpeg "Screenshot_20220815_170611.jpg")
Problem solved

**Comment by Geeyun-JY3** [comment]
@nijel Actually, it is easy to reproduce this in the browse view. I have reproduced this several times before. I think some fixes are needed. 

This is an issue with the browse view.
When searching something that is only contained by target strings in the browse view, then changing the matching results’ translation, which makes them no longer contain the searching keyword, the changed results would be still shown in the browse view with the same keyword after the changes, while using the same browser.

Let’s take https://github.com/WeblateOrg/weblate/issues/8003#issue-1338520378 for example. If I don't get it wrong, it should be: 

1. Open the [browse view of Flathub/flathub.org — Chinese (Simplified)](https://hosted.weblate.org/browse/flathub/frontend/zh_Hans/).
2. Search `帐户`  browse view.
3. Change all `帐` to `账`.
4. Reload the browse view page (searching `帐户`).
5. All the matching results in 2 are still shown in 1 while using the same browser, though their target strings no longer contain `帐` after the changes done in 3.

**Comment by yangyangdaji** [comment]
yes



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 23, 2022 13:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [WeblateOrg/weblate] The search result doesn't exist when clicked(Issue #8003)




 
@nijel Actually, it is easy to reproduce this in the browse view. I have reproduced this several times before. I think some fixes are needed.
 
This is an issue with the browse view.
 When searching something that is only contained by target strings in the browse view, then changing the matching results’ translation, which makes them no longer contain the searching keyword, the changed results would be still shown in the browse view with the same keyword after the changes, while using the same browser.
 
Let’s take #8003 (comment) for example. If I don't get it wrong, it should be:
  
Open the browse view of Flathub/flathub.org — Chinese (Simplified).
 
Search 帐户  browse view.
 
Change all 帐 to 账.
 
Reload the browse view page (searching 帐户).
 
All the matching results in 2 are still shown in 1 while using the same browser, though their target strings no longer contain 帐 after the changes done in 3.
