### ISSUE TITLE
Isn't showing new keys for iOS localization strings after update from remote repo

### ISSUE THREAD

**Issue by madlax19** [WeblateOrg/weblate#8012]
### Describe the issue

After update from remote repo if iOS Localizable.strings file contains duplicate keys, new keys are not displayed in UI and can't be localized. But downloaded localizable.strings file from UI it contains these missed keys.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Update remote repo with iOS localizable.strings files by adding new strings with same key like this :
```
"some_new_key_1" = "Some new value 1";
"some_new_key_duplicate" = "Some new duplicate value";
"some_new_key_duplicate" = "Some new duplicate value";
"some_new_key_2" = "Some new value 2";
"some_new_key_3" = "Some new value 3";
```
2. Into component  **Manage** go to **Repository maintenance** and update component from remote repo by pressing **Update** button
3. Go to languages list and select Language what has been updated
4. Try to search for new keys

### Expected behavior

User interface should displays the new keys even they are duplicated in remote source file

### How do you run Weblate?

Docker container

### Weblate versions

4.13.1

**Comment by nijel** [comment]
Weblate 4.13 doesn't properly report duplicate keys and fails to update in that case.

This is already fixed by 309b09a45ff873c49bae923394b553ae0d725353.
