### ISSUE TITLE
Can't download any translation files. 404 error

### ISSUE THREAD

**Issue by yumithecat** [WeblateOrg/weblate#8015]
### Describe the issue

Hi, I'm currently using weblate to translate my mobile app. Since today morning, when I tried to download all translations it just didn't work. And trying to download a single one leads me to an 404 error page.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to your project
2. Click on 'files'
3. Click on 'Download translation files as ZIP file'
4. error
Or
1. Go to your project
2. Select a language
3. Click on 'Download translation'
4. 404 error

### Expected behavior

I would expect it not do display an 404 error, and also not to download an empty folder

### Screenshots

![Screenshot_20220819-070125_Chrome](https://user-images.githubusercontent.com/89903745/185547684-9db6d3d7-0b5c-4e92-a923-2c29a8295891.jpg)
![Screenshot_20220819-070550_Chrome](https://user-images.githubusercontent.com/89903745/185547646-ad36f1a3-d5ab-4f8b-ad30-55baad8031cb.jpg)
![Screenshot_20220819-070136_Chrome](https://user-images.githubusercontent.com/89903745/185547673-4d18bbf1-69e7-4030-aca8-96af804aaec5.jpg)

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
You can not download files which were removed from the repository...

**Comment by yumithecat** [comment]
> You can not download files which were removed from the repository...

The thing is, as I said: yesterday evening it worked completely fine. I removed nothing. And today it didn't work anymore. Is there maybe a place where I can put the file back?

(I'll look at the support plans and I'll decide later on.)

**Comment by yumithecat** [comment]
> You can not download files which were removed from the repository...

The thing is, as I said: yesterday evening it worked completely fine. I removed nothing. And today it didn't work anymore. Is there maybe a place where I can put the file back?

(I'll look at the support plans and I'll decide later on.)

**Comment by yumithecat** [comment]
My server host loaded a backup and it's fine now, so I'll just close this issue then. Thanks for taking your time to answer me tho.

**Comment by nijel** [comment]
> The thing is, as I said: yesterday evening it worked completely fine. I removed nothing. And today it didn't work anymore. Is there maybe a place where I can put the file back?

If your translations are stored in the Git repository, maybe somebody else did (re)moved them and pushed that change?

Anyway the files were missing, Weblate correctly reported that, so I don't see any issue on the Weblate side.
