### ISSUE TITLE
Key is parsed for Glossary matches.

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#8016]
### Describe the issue

Apparently the "key" is also parsed for Glossary matches and not only the "value".

![image](https://user-images.githubusercontent.com/26718215/185565787-ba6f725c-ee14-4233-ba38-b47cdf873c2c.png)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Expected behavior

Only the text in "value" should be parsed, not the "key".

### Screenshots

![image](https://user-images.githubusercontent.com/26718215/185565805-4ea40784-3ed4-44ac-8846-675189db052a.png)

### How do you run Weblate?

Docker container

### Weblate versions

4.13

**Comment by nijel** [comment]
It was intentionally implemented this way in 06934dd0133. Unfortunately, I didn't write any reasoning for that back then. And I don't see a reason for doing that now...
