### ISSUE TITLE
Automatic component discovery

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#802]
With some projects, it might be usable to have automatic component discovery. Let's say we will have one repository holding many translation files and whenever new one is added, it should be automatically visible in Weblate.

Right now this is possible to do manually from command line:

```
./manage.py import_project \
    --name-template 'Infographics %s' \
    --file-format xliff \
    project weblate://project/infographics master \
    'path/infographics/ig-**.*.xlf'
```

But this should be possible to do automatically on git update.

This should probably go to separate model which will be tracking these patters (as there might be more of them for single project), which needs to hold at least:
- component with git repository to track
- match pattern
- used file format
- naming template
- component for base of other settings (new language, licensing, ...)
##

**Comment by alexei38** [comment]
if possible, I would like to use an exclude for components

**Comment by nijel** [comment]
IMHO this really should be really implemented as an addon once we have them (see https://github.com/WeblateOrg/weblate/issues/1353).

**Comment by nijel** [comment]
The WIP pull request is here: https://github.com/WeblateOrg/weblate/pull/1953

It should be fully functional, it just needs documentation and rewriting import_project to use new code.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
