### ISSUE TITLE
How to setup WEBLATE_BASIC_LANGUAGES and list environment target ?

### ISSUE THREAD

**Issue by NicolasBFR** [WeblateOrg/weblate#8021]
### Describe the issue

I tried to run the Docker instalation of Weblate with restriction to the EU languages like this in docker-compose.yml like this:
` WEBLATE_BASIC_LANGUAGES ["de","en","bg","hr","da","es","et","fi","fr","el","hu","ga","it","lv","lt","mt","nl","pl","pt","ro","sk","sl","sv","cs"]`

but when I do `docker-compose up` docker returns:
`services.weblate.environment.WEBLATE_BASIC_LANGUAGES must be a string, number, boolean or null`.
How to configure a list varenv ?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Exception traceback

`services.weblate.environment.WEBLATE_BASIC_LANGUAGES must be a string, number, boolean or null`

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.13.1
 * Django: 4.0.6
 * siphashc: 2.1
 * translate-toolkit: 3.7.1
 * lxml: 4.6.5
 * Pillow: 9.2.0
 * bleach: 5.0.1
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.0
 * django-compressor: 4.0
 * djangorestframework: 3.13.1
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.7.1
 * jellyfish: 0.9.0
 * openpyxl: 3.0.10
 * celery: 5.2.7
 * kombu: 5.2.4
 * translation-finder: 2.13
 * weblate-language-data: 2022.5
 * html2text: 2020.1.16
 * pycairo: 1.21.0
 * pygobject: 3.42.1
 * diff-match-patch: 20200713
 * requests: 2.28.1
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.6.0
 * Cython: 0.29.30
 * misaka: 2.1.1
 * GitPython: 3.1.27
 * borgbackup: 1.2.1
 * pyparsing: 3.0.9
 * pyahocorasick: 1.4.4
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.1.0
 * Python: 3.10.5
 * Git: 2.30.2
 * psycopg2: 2.9.3
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * boto3: 1.24.23
 * zeep: 4.1.0
 * aeidon: 1.11
 * iniparse: 0.5
 * mysqlclient: 2.1.1
 * Mercurial: 6.1.4
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 6.2.7
 * PostgreSQL server: 14.5
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: 127.0.0.1
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.10.124-1-MANJARO (x86_64)

### Weblate deploy checks

```shell
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail ([Errno 111] Connection refused), please check EMAIL_* settings.
        HINT: https://docs.weblate.org/en/weblate-4.13.1/admin/install.html#out-mail
?: (weblate.E012) The server e-mail address should be changed from its default value
        HINT: https://docs.weblate.org/en/weblate-4.13.1/admin/install.html#production-email
?: (weblate.E013) The "From" e-mail address should be changed from its default value
        HINT: https://docs.weblate.org/en/weblate-4.13.1/admin/install.html#production-email

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.13.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.13.1/admin/backup.html

System check identified 9 issues (1 silenced).
```

**Comment by NicolasBFR** [comment]
I replaced the line with `WEBLATE_BASIC_LANGUAGES: de,en,bg,hr,da,es,et,fi,fr,el,hu,ga,it,lv,lt,mt,nl,pl,pt,ro,sk,sl,sv,cs`.
This time it is compiling, but the languages are not limited

**Comment by nijel** [comment]
String with comma separated values

**Comment by NicolasBFR** [comment]
With this : `WEBLATE_BASIC_LANGUAGES: "de","en","bg","hr","da","es","et","fi","fr","el","hu","ga","it","lv","lt","mt","nl","pl","pt","ro","sk","sl","sv","cs"`
or this `WEBLATE_BASIC_LANGUAGES: 'de','en','bg','hr','da','es','et','fi','fr','el','hu','ga','it','lv','lt','mt','nl','pl','pt','ro','sk','sl','sv','cs'`

docker-compose up gives me : `yaml: line 26: did not find expected key`

**Comment by NicolasBFR** [comment]
Oh, ok you meant this:

` WEBLATE_BASIC_LANGUAGES: "de,en,bg,hr,da,es,et,fi,fr,el,hu,ga,it,lv,lt,mt,nl,pl,pt,ro,sk,sl,sv,cs"`
The problem now is that the language list when starting new translation to a project still contains all languages:
![image](https://user-images.githubusercontent.com/55790631/185691725-ac29b357-b16e-4320-8ed4-74e65e76856a.png)

**Comment by nijel** [comment]
> This only limits non privileged users to add unwanted languages. The project admins are still presented with full selection of languages defined in Weblate.

See https://docs.weblate.org/en/latest/admin/config.html#std-setting-BASIC_LANGUAGES

**Comment by NicolasBFR** [comment]
Oh ok thanks
