### ISSUE TITLE
crediting xmr

### ISSUE THREAD

**Issue by Gaberred** [WeblateOrg/weblate#8031]
### Describe the issue

I made 3 transfers to 2 of my wallets a day ago and xmr did not come. 
Txid:
bd76aca071dd80256cc13baa65ec26f85923205fffcad03ec35e994a082ddb32
Txid:
7963b170bc2997af22a5031191386dc0eea2368dde86a078a653b66134728715
Address:
48VvuMcMwZregWANEEATDvb1yRd4mjkNf2A8SgnWD1rP4nigoS43xBn5M2mZYpK7d7bDvqLicFPfmaJRm3sDMx1P9smtnDb
Address: 45R4JxgJCZRRKhErjSYHhmMtAN8DsPgop2Mau3poKzAHb2wvEgUF7p3b1Lj4EYHkTPZEZ4ZSUp94tD3TaLraHsCfDcDLedH

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

Git checkout

**Comment by nijel** [comment]
Weblate is localization platform, not a xmr wallet...
