### ISSUE TITLE
Source changes are not synced as fuzzy in the monolingual po

### ISSUE THREAD

**Issue by nedsociety** [WeblateOrg/weblate#8036]
### Describe the issue

Our project recently had some changes in the source strings. As it uses monolingual po, Weblate recognized the changes and flagged them as Needs Editing as described [here](https://docs.weblate.org/no/latest/faq.html#can-weblate-highlight-changes-in-a-fuzzy-string).

After that I tried to make the po files reflect the changes which Weblate had automatically made, by using the Force synchronization command. However after the push it seems the command does nothing to those entries, even if they're marked as `Needs Editing`.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

The repo is located in https://github.com/ftl-mv-translation/ftl-mv-translation.

1. Fork the repo, make a branch at commitid 39fd34cbb7b1f5d4d6039e26763d8ef428b8c2b7.
2. Create a Weblate component for `locale/data/events_lightspeed.xml/*.po` on the aforementioned branch.
3. Fast-forward the branch to commitid dcf5b36c19059ab87574158480ed996806ee4e84.
4. After the Update command Weblate grabs the source string changes.
5. Issue Force synchronization and Push.

### Expected behavior

From https://github.com/WeblateOrg/weblate/blob/main/docs/workflows.rst:

> ### Needs editing
>    Translation needs editing, this is usually the result of a source string change, fuzzy matching or translator action.
>    The translation is stored in the file, depending on the file format it might
>    be marked as needing edit (for example as it gets a ``fuzzy`` flag in the Gettext file).

After Force synchronization such entries should have been marked as `#, fuzzy`, as they're marked as `Needs Editing` in Weblate.

### Screenshots

![image](https://user-images.githubusercontent.com/11943013/185889878-e1f7dff0-d008-44d7-8b4b-c6e7c5f85d63.png)

After `Force synchronization`, the entry is dumped as:

```po
#: src-en/data/events_lightspeed.xml:637
msgid ""
"data/events_lightspeed.xml$//event[@name=\"ATLAS_MENU_NOEQUIPMENT\"]/choice[@req=\"SEC"
" SECTOR_DUSKBRINGER_UNIQUE\"]/text"
msgstr "더스크브링어 주도로 나아간다."
```

Notice that there's no `#, fuzzy` though `Needs Editing` is checked by Weblate.

### How do you run Weblate?

Docker container

### Additional context

Checks are not available as I have no access on them. The site says the version is 4.12.1.

**Comment by nijel** [comment]
For me, the fuzzy flag is written to the file on the force synchronization:

```po
#: src-en/data/events_lightspeed.xml:384
#, fuzzy
msgid ""
"data/events_lightspeed.xml$//event[@name=\"ATLAS_MENU\"]/choice[@req=\"SEC "
"SECTOR_DUSKBRINGER_UNIQUE\"]/text"
msgstr "Zum Duskbringer Capitol weiterreisen."

```

What is intentional is that this state is not written to the file directly - most of the monolingual files do not support his, and thus Weblate doesn't attempt to write the states caused by source string change.

**Comment by nedsociety** [comment]
Weird, [here's](https://weblate.hyperq.be/projects/ftl-multiverse/dataevents_lightspeedxml/ko/) our environment. Files -> Download translation will have that entry marked without fuzzy:

```
#: src-en/data/events_lightspeed.xml:384
msgid ""
"data/events_lightspeed.xml$//event[@name=\"ATLAS_MENU\"]/choice[@req=\"SEC "
"SECTOR_DUSKBRINGER_UNIQUE\"]/text"
msgstr "Zum Duskbringer Capitol weiterreisen."
```

I'm curious that which made the difference here.

> What is intentional is that this state is not written to the file directly - most of the monolingual files do not support his, and thus Weblate doesn't attempt to write the states caused by source string change.

Could you elaborate more? If that's the case then we would have never witnessed them being marked as fuzzy. But I've got it in my small-scale test (not that repo though), and you've got it on this test run as well. Is there a specific condition whether it's enabled or not? Or is there a documentation on this behavior?

**Comment by nijel** [comment]
There is no condition - the needs editing state triggered by source string change is never marked for writing out to the file. The state is kept in Weblate database only. This is because most monolingual formats do not support storing string states.

**Comment by nedsociety** [comment]
Well that's a bit confusing, contradicting both the documentation and my test results.

Anyway is there a way that we may query the state programmatically?

**Comment by nijel** [comment]
The states changed by Weblate are indeed not covered by the docs at all. Maybe the current behavior is wrong as well, I'm just describing how it currently behaves.

Note that I'm testing on 4.14, so it might behave slightly differently than you observe.

You can get the state using API: https://docs.weblate.org/en/latest/api.html#get--api-translations-(string-project)-(string-component)-(string-language)-units-

**Comment by nedsociety** [comment]
Got it, thanks. I'll try that API as a workaround for now.

**Comment by nijel** [comment]
Let's try if we can easily address this, I've drafted https://github.com/WeblateOrg/weblate/pull/8047 which should make Weblate commit these flags to the PO files.
