### ISSUE TITLE
source strings <Improved performance and memory usage of translation memory lookups> not found 

### ISSUE THREAD

**Issue by yangyangdaji** [WeblateOrg/weblate#8041]
### Describe the issue

source strings <Improved performance and memory usage of translation memory lookups> not found

[search results](https://hosted.weblate.org/search/weblate/documentation/?offset=&q=Improved+performance+and+memory+usage+of+translation+memory+lookups&sort_by=-priority%2Cposition&checksum=) 
![Screenshot_20220822_230041_edit_2449066849105](https://user-images.githubusercontent.com/108261729/186031502-7905e365-4aae-46a0-86a8-c77a9684c86d.jpg)

[translated document](https://docs.weblate.org/zh_CN/latest/changes.html#weblate-4-14) 

![Screenshot_20220822_230128_com android chrome_edit_2379268109532](https://user-images.githubusercontent.com/108261729/186031548-4a0b95d9-4cae-4312-9d7a-a12e11b4752e.jpg)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Weblate 4.14-dev

**Comment by Geeyun-JY3** [comment]
All you need to do is wait for the updates of PO files (corresponding commit message: i18n: Update PO files).

**Comment by yangyangdaji** [comment]
(https://github.com/WeblateOrg/weblate/commit/35a71476bfb58cf8e961d83578de44ecb35ece9b) i18n: Update PO files It is not included in the subcommit

**Comment by Geeyun-JY3** [comment]
Because it is added after https://github.com/WeblateOrg/weblate/commit/35a71476bfb58cf8e961d83578de44ecb35ece9b: https://github.com/WeblateOrg/weblate/commit/2c0f0861570fe72e8cf852179063451290b32acc#diff-13939719fa5d88ab31dfc99a49861551b8e157a0ead47125cbe28a2ab72a122d

You need to wait for the next updates of PO files.

**Comment by yangyangdaji** [comment]
> 因为它是在[35a7147](https://github.com/WeblateOrg/weblate/commit/35a71476bfb58cf8e961d83578de44ecb35ece9b)之后添加的：[2c0f086 #diff-13939719fa5d88ab31dfc99a49861551b8e157a0ead47125cbe28a2ab72a122d](https://github.com/WeblateOrg/weblate/commit/2c0f0861570fe72e8cf852179063451290b32acc#diff-13939719fa5d88ab31dfc99a49861551b8e157a0ead47125cbe28a2ab72a122d)
> 
> 您需要等待 PO 文件的下一次更新。

ok
