### ISSUE TITLE
Problem with component creation for Mac due to duplicate EN language in the filemask

### ISSUE THREAD

**Issue by jzahradn** [WeblateOrg/weblate#8065]
### Describe the issue

Hi,

it is not clear to me why I am getting error during a component creation:
"There is more than one file for English language, please adjust the filemask and use components for translating different resources."
when I configure filemask this way:
"apps/desktop-client/smart-job-manager/SmartJobManager.Mac/Resources/*.lproj/Localizable.strings".

I don't see any other English language in the path. The files list is on the screenshot.

Best Regards

Jan

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Screenshots

<img width="488" alt="image" src="https://user-images.githubusercontent.com/55885376/187181124-fc123b9c-af45-4b7e-a5cd-428dcd8a25f4.png">

### How do you run Weblate?

Git checkout

### Weblate versions

* Weblate: weblate-4.5
 * Django: 3.1.7
 * siphashc: 2.1
 * translate-toolkit: 3.3.2
 * lxml: 4.6.2
 * Pillow: 8.1.0
 * bleach: 3.3.0
 * python-dateutil: 2.8.1
 * social-auth-core: 4.0.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.11.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.2
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 53.0.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.6
 * celery: 5.0.5
 * kombu: 5.0.2
 * translation-finder: 2.9
 * weblate-language-data: 2021.3
 * html2text: 2020.1.16
 * pycairo: 1.20.0
 * pygobject: 3.38.0
 * diff-match-patch: 20200713
 * requests: 2.25.1
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.20.3
 * Cython: 0.29.22
 * misaka: 2.1.1
 * GitPython: 3.1.13
 * borgbackup: 1.1.15
 * pyparsing: 2.4.7
 * Python: 3.6.9
 * Git: 2.17.1
 * psycopg2: 2.7.4
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.4.0
 * akismet: 1.0.1
 * boto3: 1.16.39
 * zeep: 3.4.0
 * aeidon: 1.2.1
 * Mercurial: 4.5.3
 * git-review: 1.28.0
 * Redis server: 4.0.9
 * PostgreSQL server: 9.5.13
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtpinternal.myq.cz
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.15.0-191-generic (x86_64)

### Weblate deploy checks

```shell
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E027) The path /var/www/weblate/data/cache/fonts/14d784bc3113819c63ec09bcd1e0dcb4-le64.cache-7 is owned by a different user, check your DATA_DIR settings.
	HINT: https://docs.weblate.org/en/weblate-4.5/admin/install.html#file-permissions
?: (weblate.E027) The path /var/www/weblate/data/cache/fonts/b5e909958a2fcc4071e7f0142376ee37-le64.cache-7 is owned by a different user, check your DATA_DIR settings.
	HINT: https://docs.weblate.org/en/weblate-4.5/admin/install.html#file-permissions
?: (weblate.E027) The path /var/www/weblate/data/cache/fonts/be68cefafcae4573dbe0c72153107a55-le64.cache-7 is owned by a different user, check your DATA_DIR settings.
	HINT: https://docs.weblate.org/en/weblate-4.5/admin/install.html#file-permissions
?: (weblate.E027) The path /var/www/weblate/data/cache/fonts/d7cac2f5cee47ca036f3b6ae92bfbdcc-le64.cache-7 is owned by a different user, check your DATA_DIR settings.
	HINT: https://docs.weblate.org/en/weblate-4.5/admin/install.html#file-permissions

WARNINGS:
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (weblate.W025.ini) Failure in loading handler for ini file format: Missing iniparse library.
	HINT: https://docs.weblate.org/en/weblate-4.5/admin/install.html#optional-deps
?: (weblate.W025.islu) Failure in loading handler for islu file format: Missing iniparse library.
	HINT: https://docs.weblate.org/en/weblate-4.5/admin/install.html#optional-deps
?: (weblate.W033.Subversion) Failure in loading VCS module for Subversion: git: 'svn' is not a git command. See 'git --help'.

The most similar commands are
	fsck
	mv
	show
 (1)
	HINT: https://docs.weblate.org/en/weblate-4.5/vcs.html

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.5/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.5/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 4.14.
	HINT: https://docs.weblate.org/en/weblate-4.5/admin/upgrade.html

System check identified 12 issues (2 silenced).
```

**Comment by jzahradn** [comment]
<img width="970" alt="image" src="https://user-images.githubusercontent.com/55885376/187185630-fc4b800b-52c5-4c52-a4c7-2f484e897e64.png">

**Comment by nijel** [comment]
The base file is in English (this can be configured in the component) and there is also en file.

**Comment by jzahradn** [comment]
OK, thank you for clarification. If I keep only one Localizable.strings file the component can be created indeed.
However, it is strange because in most of our components we have both base and en files and we had never such problems during creating components.
We can close this issue.

**Comment by nijel** [comment]
Maybe you have a different language configured as source? This alert is there for quote some time...

**Comment by jzahradn** [comment]
English (en.lproj) set as both base and template while base.lproj exists in the same path and contains the same strings. More in screenshots.
<img width="984" alt="Snímek obrazovky 2022-09-08 v 17 56 39" src="https://user-images.githubusercontent.com/55885376/189169852-7ac6fd52-6ce1-4a3b-a8cb-00152da3d68d.png">
<img width="985" alt="Snímek obrazovky 2022-09-08 v 17 57 02" src="https://user-images.githubusercontent.com/55885376/189169866-8838e2e3-aa4e-4522-8a47-9e66c86400aa.png">
<img width="1015" alt="Snímek obrazovky 2022-09-08 v 17 58 20" src="https://user-images.githubusercontent.com/55885376/189169880-59957a6c-c078-4d4d-a246-0efb25ededad.png">

**Comment by nijel** [comment]
It doesn't matter which of these you choose as base. Your Weblate is configured to parse `*.lproj` what matches both `Base.lproj` and `en.lproj`. See https://docs.weblate.org/en/latest/faq.html#what-does-mean-there-are-more-files-for-the-single-language-en
