### ISSUE TITLE
Internal Server Error when trying commit Weblate changes or synchronise Weblate repository

### ISSUE THREAD

**Issue by ashutoshgngwr** [WeblateOrg/weblate#8072]
### Describe the issue

When I click commit, I get Internal Server Error. The latest recorded id of the error is `15f25aa168e146179a91ee3e60e3428d`. I get the same error when trying to Update/Pull/Rebase the repository. Its latest recorded id is `b743b90716c24126bfdb8c2ec2d5011c`. I am not sure what is going on.

Before this started, I attempted to fix fatal crashes in my Android app caused by plurals in cs/fr/lt locales. I simply duplicated the `many` as the `other` key. So plurals for these locales now look like the following.

```xml
<plurals name="time_minutes">
    <item quantity="one">%1$d minutė</item>
    <item quantity="few">%1$d minutės</item>
    <item quantity="many">%1$d minučių</item>
    <item quantity="other">%1$d minučių</item>
</plurals>
```

I also tried to manually merge the Weblate repository into upstream, but it didn't help.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to the 'Repository Maintenance' tab
2. Click on 'Commit' or 'Update'
3. See the error

### Screenshots

![image](https://user-images.githubusercontent.com/7106123/187889611-de98b223-3f09-45c7-9c8d-61c4605d60e2.png)
![image](https://user-images.githubusercontent.com/7106123/187889672-98c9751f-e001-4da5-8948-83df5cdc6a59.png)

### How do you run Weblate?

weblate.org service

### Additional context

Weblate Project: https://hosted.weblate.org/projects/noice/
Android App Source: https://github.com/trynoice/android-app
Possibly related to: #7520

**Comment by nijel** [comment]
Does it still happen? I've fixed similar issue tonight.

**Comment by ashutoshgngwr** [comment]
@nijel I just tried it, and it is still happening.

**Comment by nijel** [comment]
Ah, I fixed that, but didn't deploy the fix. It is working now.

For the record, the fix is https://github.com/translate/translate/pull/4713

**Comment by ashutoshgngwr** [comment]
@nijel Thank you for the quick resolution! Everything is working as expected now.
