### ISSUE TITLE
Strings set as read-only should be displayed as translated AND validated

### ISSUE THREAD

**Issue by KadAnna** [WeblateOrg/weblate#8096]
### Describe the problem

At the moment, strings set as for review are displayed green, as they need to be reviewed. This is confusing both for users, so for translators.

### Describe the solution you'd like

When string is set as read-only, would you please have it considered as approved. 

### Describe alternatives you've considered

Enable the workflow for review to read-ony strings. Although set up at the project setting, this feature is turned off for read-only strings.

### Additional context

Same issue is with source language - the same way, show strings in green, although there is now way to make them green / validated.

**Comment by Geeyun-JY3** [comment]
@nijel Currently, the read-only strings are still indicated as green in the `Strings status` section of the `Overview` tab of a translation.

https://hosted.weblate.org/projects/f-droid/website-pages/zh_Hans/
![image](https://user-images.githubusercontent.com/49396421/197140735-10fcf0af-f335-4061-8a1f-585b3446194b.png)

https://hosted.weblate.org/projects/f-droid/website-pages/en/
![image](https://user-images.githubusercontent.com/49396421/197140936-5fa87b3d-af71-4155-a465-8601cd4ccdbb.png)
