### ISSUE TITLE
Plurals not generated properly in 4.14

### ISSUE THREAD

**Issue by alipovatyi** [WeblateOrg/weblate#8097]
### Describe the issue

Before the 4.14 version of Weblate strings were generated correctly but now they are broken for some languages (ES, IT and FR in this case). If you try to download the files for Spanish (ES) or Italian (IT), you will find an empty `other` tag and a new `many` which is not applicable to these languages (the correct ones are described in the _Expected behavior_ section but in short it should be `other` instead of `many`). 

**Italian:**
```xml
<plurals name="points">
    <item quantity="one">%1$d point</item>
    <item quantity="many">%1$d points</item>
    <item quantity="other"></item>
</plurals>
```

**Spanish:**
```xml
<plurals name="points">
    <item quantity="one">%1$d point</item>
    <item quantity="many">%1$d points</item>
    <item quantity="other"></item>
</plurals>
```

Another problem has appeared with French (FR) translations when it generates `many` (which is required by Android, see _Screenshots_ sections) correctly but `other` remains empty which is required by the specification. 

**French:**
```xml
<plurals name="points">
    <item quantity="one">%1$d point</item>
    <item quantity="many">%1$d points</item>
    <item quantity="other"></item>
</plurals>
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Add a new plural glossary term (eg. `points`)
2. Download translations in XML (for Android) using `/api/translations/(string:project)/(string:component)/(string:language)/file/?format=aresource` for ES (Spanish), IT (Italian), and FR (French) languages
3. Check the downloaded files

### Expected behavior

Expected to have correctly generated strings (see below) for all languages.

**Italian:**
```xml
<plurals name="points">
    <item quantity="one">%1$d point</item>
    <item quantity="other">%1$d points</item>
</plurals>
```

**Spanish:**
```xml
<plurals name="points">
    <item quantity="one">%1$d point</item>
    <item quantity="other">%1$d points</item>
</plurals>
```

**French:**
```xml
<plurals name="points">
    <item quantity="one">%1$d point</item>
    <item quantity="many">%1$d points</item>
    <item quantity="other">%1$d points</item>
</plurals>
```

### Screenshots

<img src=https://user-images.githubusercontent.com/23189039/189114110-a0cd53cb-6654-4e4c-a795-47e8f262f8bc.png width=500 />
<img src=https://user-images.githubusercontent.com/23189039/189113975-c12aa8ef-ea35-4ae7-b732-33b1e9c52e7e.png width=500 />
<img src=https://user-images.githubusercontent.com/23189039/189113838-57125859-b7bf-41a5-b1e2-9082d8f0d4c3.png width=500 />

### How do you run Weblate?

Other

### Weblate versions

4.14

### Additional context

This has been tested for _EN, DA, DE, ES, FI, FR, IT, NL, nb_NO, PL & SV_ languages, and XML format. The problem may occur for other platforms and/or languages too.

**Comment by nijel** [comment]
This is desired, see https://github.com/WeblateOrg/weblate/issues/7888

**Comment by alipovatyi** [comment]
@nijel is it desired to generate empty tags even for languages that do not have such tags?

**Comment by radzio** [comment]
@nijel  are you sure that this is intended behavior? What about the empty tags?
