### ISSUE TITLE
White on white text when cloning translation

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#8100]
### Describe the issue

Cloning text gets me very unreadable text with FF 102.2.0esr (and Chromium 104.0.5112.101)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Go to either
https://hosted.weblate.org/zen/finamp/finamp/nb_NO/?offset=2&q=state%3A%3Ctranslated
or
https://hosted.weblate.org/translate/finamp/finamp/nb_NO/?q=state%3A%3Ctranslated

Click "Clone to translation"

### Expected behavior

Black text on white background

### Screenshots

![image](https://user-images.githubusercontent.com/13802408/189207064-2ffb84dd-db57-4996-a261-9e1322b3f3a4.png)

### How do you run Weblate?

weblate.org service

### Weblate versions

4.14.1-dev

### Additional context

The main component is mistakenly added as a glossary, and there is only one component.
However, it also happens in regular projects when cloning the source and a translation exists.

**Comment by yangyangdaji** [comment]
@nijel the problem still exists
![Screenshot_20220913_093054_com android chrome](https://user-images.githubusercontent.com/108261729/189788342-26553615-625f-4a2c-a3a9-726f1715e462.jpg)

**Comment by comradekingu** [comment]
@yangyangdaji 
Hosted Weblate is still on version 4.14.1-dev.
Once the new version is rolled out the fix will be included. :)

**Comment by nijel** [comment]
I'm deploying the fix right now...
