### ISSUE TITLE
New translation strings inserted at the end of file

### ISSUE THREAD

**Issue by QazPolma** [WeblateOrg/weblate#8102]
### Describe the issue

New translation strings inserted at the end of their files instead of maintaining the position of the source file.
At the same time, the weblate UI maintains the position of the source string.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1.Insert a new string into source file(outside of weblate UI).
2.Translate the string and commit the changes.

Result:
Newly translated string is inserted at the end of translation. 

### Expected behavior

The translated string would appear in the same position as the source string in all translation files.

### How do you run Weblate?

Docker container

### Weblate versions

* Weblate: 4.14
 * Django: 4.1
 * siphashc: 2.1
 * translate-toolkit: 3.7.2
 * lxml: 4.9.1
 * Pillow: 9.2.0
 * bleach: 5.0.1
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.0
 * django-compressor: 4.1
 * djangorestframework: 3.13.1
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.8.0
 * rapidfuzz: 2.6.0
 * openpyxl: 3.0.10
 * celery: 5.2.7
 * kombu: 5.2.4
 * translation-finder: 2.14
 * weblate-language-data: 2022.7
 * html2text: 2020.1.16
 * pycairo: 1.21.0
 * pygobject: 3.42.2
 * diff-match-patch: 20200713
 * requests: 2.28.1
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.9.5
 * Cython: 0.29.32
 * misaka: 2.1.1
 * GitPython: 3.1.27
 * borgbackup: 1.2.2
 * pyparsing: 3.0.9
 * pyahocorasick: 1.4.4
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.1.1
 * Python: 3.10.6
 * Git: 2.30.2
 * psycopg2: 2.9.3
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * boto3: 1.24.57
 * zeep: 4.1.0
 * aeidon: 1.11
 * iniparse: 0.5
 * mysqlclient: 2.1.1
 * Mercurial: 6.2.1
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 6.2.7
 * PostgreSQL server: 13.8
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mgt-dtu.vlan13
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 3.10.0-1160.76.1.el7.x86_64 (x86_64)

### Weblate deploy checks

```shell
CRITICALS:
?: (weblate.E018) Failed to download avatar: HTTPSConnectionPool(host='www.gravatar.com', port=443): Max retries exceeded with url: /avatar/77a4accfa1d1d8fcae8e2f3fd42eb1de?d=identicon&s=32 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f03629cfb50>, 'Connection to www.gravatar.com timed out. (connect timeout=1.0)'))
	HINT: https://docs.weblate.org/en/weblate-4.14/admin/optionals.html#avatars

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.14/admin/install.html#collecting-errors
```

### Additional context

Tested with iOS strings file.

**Comment by nijel** [comment]
Yes, the ordering is based on the monolingual base, ordering in the translation files is not maintained. If you want to sort the strings there is https://docs.weblate.org/en/latest/admin/addons.html#format-the-java-properties-file
