### ISSUE TITLE
Untranslated number increased ; Things to check : Has been translated

### ISSUE THREAD

**Issue by borisBelloc** [WeblateOrg/weblate#8115]
### Describe the issue

Hello,

The number of "Untranslated" has increased on our projet, I wanted to see why.
![image](https://user-images.githubusercontent.com/37147299/190165266-9292d55d-49bd-428b-bc4e-9f488c99ac69.png)

When I click to check why the number increased, I see that most untranslated string are tagged with : `Things to check :
 Has been translated`

Why is it happening ? 
"**Fix string**" button do nothing and the "last translation" is exaclty the same as the current translation : 
![image](https://user-images.githubusercontent.com/37147299/190165603-930b85e9-d15c-401f-9a3a-c3c7edee2ad4.png)

Why is this warning activated if the translation was the same as the current one ? is it useful ?
Did the warning appear because the boolean "Needs editing" has been activated ?

thank you

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Self-hosted

### Weblate versions

Weblate 4.4.2

**Comment by nijel** [comment]
There was a bug that triggered this check for strings which have translation, but were marked as "needs editing". I don't recall where it got fixed, but you're using an outdated version which might be affected by this.

**Comment by borisBelloc** [comment]
thanks for the fast answer 😀

**Comment by comradekingu** [comment]
@borisBelloc You can close the issue :)
https://docs.weblate.org/en/latest/admin/upgrade.html
