### ISSUE TITLE
API unit creation is not available if "Manage strings" is disabled

### ISSUE THREAD

**Issue by antonkomarev** [WeblateOrg/weblate#8116]
### Describe the problem

I want to disable adding new units creation from UI, but keep this functionality for the API call:
```
POST /api/translations/{project}/{component}/en/units/
```

There is [Manage strings](https://docs.weblate.org/en/weblate-4.12.2/admin/projects.html#component-manage-units) feature, but it disables API creation too 😢 

### Describe the solution you'd like

I want to be able to create units from API from this endpoint even if "Manage strings" option is disabled, or have separate one (if this endpoint is used in the UI).

**Comment by nijel** [comment]
The API is intentionally consistent with the UI

**Comment by nijel** [comment]
There is separate permission for this (Add new string), using that might be better way to go if you want to restrict usage in some cases.

**Comment by antonkomarev** [comment]
So I need only one user account which can do that functionality, let's say bot user. And other teams can't add keys, right?

**Comment by nijel** [comment]
Yes.
