### ISSUE TITLE
Package libjpeg62-turbo-dev is not available on Ubuntu

### ISSUE THREAD

**Issue by wilkis3** [WeblateOrg/weblate#8124]
### Describe the issue

The package libjpeg62-turbo-dev is not available on all Ubuntu versions only on Debian.

```
$ apt install libjpeg62-turbo-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libjpeg62-turbo-dev
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Update apt
2. Try to install libjpeg62-turbo-dev

### Expected behavior

libjpeg62-turbo-dev is available on Ubuntu

### How do you run Weblate?

Other

**Comment by nijel** [comment]
It seems to be https://packages.ubuntu.com/jammy/libjpeg-turbo8-dev there.
