### ISSUE TITLE
Please disable Glosbe automatic translation service by default

### ISSUE THREAD

**Issue by dleidert** [WeblateOrg/weblate#8129]
### Describe the issue

Glosbe is enabled by default, but as pointed out in #5598 the service has been shut down. IMHO the Glosbe automatic translation service should either be removed or disabled by default then. Otherwise, it will still produce error messages by default.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Use a fresh installation of weblate using docker and automatic suggestions will produce a 404 error for Glosbe.

### Expected behavior

Glosbe must be turned on explicitely or it should not be available at all.

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.14
 * Django: 4.1
 * siphashc: 2.1
 * translate-toolkit: 3.7.2
 * lxml: 4.9.1
 * Pillow: 9.2.0
 * bleach: 5.0.1
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.0
 * django-compressor: 4.1
 * djangorestframework: 3.13.1
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.8.0
 * rapidfuzz: 2.6.0
 * openpyxl: 3.0.10
 * celery: 5.2.7
 * kombu: 5.2.4
 * translation-finder: 2.14
 * weblate-language-data: 2022.7
 * html2text: 2020.1.16
 * pycairo: 1.21.0
 * pygobject: 3.42.2
 * diff-match-patch: 20200713
 * requests: 2.28.1
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.9.5
 * Cython: 0.29.32
 * misaka: 2.1.1
 * GitPython: 3.1.27
 * borgbackup: 1.2.2
 * pyparsing: 3.0.9
 * pyahocorasick: 1.4.4
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.1.1
 * Python: 3.10.6
 * Git: 2.30.2
 * psycopg2: 2.9.3
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * boto3: 1.24.57
 * zeep: 4.1.0
 * aeidon: 1.11
 * iniparse: 0.5
 * mysqlclient: 2.1.1
 * Mercurial: 6.2.1
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 6.2.7
 * PostgreSQL server: 14.5
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.wgdd.de
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.10.0-14-amd64 (x86_64)

**Comment by nijel** [comment]
It is not enabled automatically, the only automatically enabled ones are built-in:

https://github.com/WeblateOrg/weblate/blob/3a8c199025a7e19a93fb74adaa51d0d672a1435d/weblate/machinery/models.py#L103-L106

**Comment by dleidert** [comment]
I did never enable it, still it was enabled (and I also somehow remember to read in the docs that it is enabled by default). I'll try with a clean container to see if I can reproduce it, and let you know of my results.

**Comment by nijel** [comment]
In the Docker container, it will be enabled if `WEBLATE_MT_GLOSBE_ENABLED` environment is sent (this is legacy feature, it is there only for migration from older releases, current configuration is in the database only).
