### ISSUE TITLE
docker: Enable WEBLATE_GITLAB_CREDENTIALS environment variable

### ISSUE THREAD

**Issue by calbasi** [WeblateOrg/weblate#8132]
### Describe the problem

Right now it seems I can use gitlab_username and gitlab_token variables. But when I try to use gitlab_credentials:

>       WEBLATE_GITLAB_CREDENTIALS: "git.duniter.org": {username: weblate,token: XXXXXXXXXXXXXXX}

I get this error:

> ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
>   in "./docker-compose.override.yml", line 17, column 52

### Describe the solution you'd like

Add weblate_gitlab_credentials support

**Comment by jatinmark** [comment]
I would like to work on this. Can you please assign this to me?

**Comment by nijel** [comment]
@jatinmark Yes, you're welcome.

**Comment by nijel** [comment]
You can now configure WEBLATE_GITLAB_CREDENTIALS for a single host by setting WEBLATE_GITLAB_HOST, WEBLATE_GITLAB_USERNAME and WEBLATE_GITLAB_TOKEN, see https://github.com/WeblateOrg/weblate/commit/b299b88af9dd20c6c8bef68ef1d5125def0de471. Multiple host configuration is still not supported via environment variables.

**Comment by Dbhardwaj99** [comment]
Has Jatin closed this issue or Is it still open? I can work on this

**Comment by jatinmark** [comment]
Yes , you can work on this issue .

**Comment by Dbhardwaj99** [comment]
Hello,

I would like to enable the WEBLATE_GITLAB_CREDENTIALS environment variable in the docker-compose.yml file. Currently, the file is not able to parse the value of this variable.

To fix the issue, I propose modifying the syntax of the WEBLATE_GITLAB_CREDENTIALS variable as follows:

environment:

      DJANGO_SETTINGS_MODULE: weblate.settings_docker

      WEBLATE_SITE_DOMAIN: ${WEBLATE_HOST}

      # Enable the WEBLATE_GITLAB_CREDENTIALS variable here:

      WEBLATE_GITLAB_CREDENTIALS: '"git.duniter.org": {username: $USERNAME,token: $TOKEN}'

**Comment by nijel** [comment]
Just to clarify it: There is currently no support for `WEBLATE_GITLAB_CREDENTIALS` in Docker. This issue is about adding it.

If you are configuring a single Gitlab instance, use WEBLATE_GITLAB_HOST, WEBLATE_GITLAB_USERNAME and WEBLATE_GITLAB_TOKEN.
