### ISSUE TITLE
[Android Strings] Weblate tries to translate "reference" strings like `@string/label`

### ISSUE THREAD

**Issue by OxygenCobalt** [WeblateOrg/weblate#8134]
### Describe the issue

I use reference strings in my Android app to reduce the amount of redundant strings that have the same content while still providing a better label for them in some contexts. These are usually formatted as `@string/label`. Recently, I have noticed that Weblate actively tries to translate these reference strings. 

This usually ends up with them being "translated" by users and written to the `strings.xml` as "\@strings/label`. Unlike the prior, these will not reference the strings I am intending in the app and cause UX issues.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Make a `strings.xml` with the following:
```xml
<string name="foo">Foo</string>
<string name="foobar">@string/foo</string>
```
3. Configure weblate to use Android Strings
4. Find that "foobar" is listed with a value of "@string/foo"
5. Translate "foobar", which results in this:

```xml
<string name="foobar">\@string/foo</string>
```

### Expected behavior

Weblate should not display these reference strings, or, better, show the actual value of these reference strings so they can be translated individually.

In the case shown above, "foobar" would either not be shown or be shown with a value of "Foo".

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
You can avoid showing these for translation by:

```xml
<string name="foobar" translatable="false">@string/foo</string>
```

I'm not sure what is the best approach here:

- expanding the value will just add not needed effort to translate same strings multiple times
- escaping is there to allow actual translations starting with `@`

**Comment by OxygenCobalt** [comment]
Oh, the translatable trick should work fine. Thanks.
