### ISSUE TITLE
external redis reconnect with nslookup

### ISSUE THREAD

**Issue by tolikkk** [WeblateOrg/weblate#8138]
### Describe the issue

Hello.

We use kubernetes weblate version 4.4.2-1 with external redis host. In our environment redis - is a cluster service with 2 nodes (master + slave). Master host is always known by a cluster DNS A-record, pointing to IP of current active RW redis node.

The problem we have - when redis host changes role master -> slave, weblate does no reconnect to new redis master. It seems weblate resolve REDIS_HOST IP while starting and use it's address further. Restarting weblate fix the problem - it resolves new redis host IP and works fine.

Errors in weblate logs:
`uwsgi stderr | django_redis.exceptions.ConnectionInterrupted: Redis ReadOnlyError: You can't write against a read only replica.`

Do you have any appropriate configuration option in weblate to reconnect + nslookup to redis if request fail? Or may be force doing lookup at any request?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. start weblate with external redis (REDIS_HOST = redis.example.com). redis.example.com = 192.168.0.2
2. switch redis roles master <-> slave. redis.example.com = 192.168.0.3
3. got weblate error "Redis ReadOnlyError: You can't write against a read only replica"

### Expected behavior

weblate reconnect to new redis master host using the same REDIS_HOST = redis.example.com

### How do you run Weblate?

Docker container

### Weblate versions

4.4.2-1

**Comment by nijel** [comment]
It should be doable via Redis connection pool configuration, but I have no experience with that: https://github.com/jazzband/django-redis#connection-pools
