### ISSUE TITLE
Language deletion does not persist

### ISSUE THREAD

**Issue by arkon** [WeblateOrg/weblate#8151]
### Describe the issue

Attempting to delete a language results in it continually returning.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Delete a language. This can either be done via the Weblate UI (e.g. https://hosted.weblate.org/projects/tachiyomi/strings/tl/#delete) or via a commit deleting the translation file.
2. After some time, the language comes back.

- [Example commit deleting Tagalog translations](https://github.com/tachiyomiorg/tachiyomi/commit/750f90614dde4b05cb4cfb718c7489f3f3a0e7e1)
- [Later Weblate PR](https://github.com/tachiyomiorg/tachiyomi/pull/8070) where it returns

### Expected behavior

The language should be permanently deleted.

### How do you run Weblate?

weblate.org service

### Additional context

I wasn't sure if a user was adding it back. However, I have also changed the "Adding new translation" setting at https://hosted.weblate.org/settings/tachiyomi/strings/#files to "Contact maintainers". No notification was sent, so the system seems to be adding the language back by itself.

**Comment by nijel** [comment]
You have installed [Add missing languages add-on](https://docs.weblate.org/en/weblate-4.14.1/admin/addons.html#addon-weblate-consistency-languages) which does that.

**Comment by arkon** [comment]
Ah, that'd make sense. I wonder if there'd be a more intuitive way of deleting languages across components in that case.
