### ISSUE TITLE
Create pull request instead of force push

### ISSUE THREAD

**Issue by anuj-scanova** [WeblateOrg/weblate#8155]
### Describe the issue

I have the following repository set up
<img width="717" alt="Screen Shot 2022-09-26 at 4 25 23 PM" src="https://user-images.githubusercontent.com/105233146/192259479-ed3ebb6a-41ac-4b18-ab50-5e31d7dfd0fd.png">

Basically what I want is,
1. Every time a code is pushed to the `qa` branch, changes should be updated in Weblate for translation.
2. When the translation is done, it should create a pull request to the `master` branch.
3. The pull request will be reviewed by a reviewer and merged on approval.

Now when I hit this **Push** button in the **Repository maintenance**
<img width="1675" alt="Screen Shot 2022-09-26 at 4 27 44 PM" src="https://user-images.githubusercontent.com/105233146/192259950-3731be11-ae13-43f4-b154-a0e81619c8b3.png">

It hard pushes the changes to the `master` branch and then creates a pull request to the `qa` branch (Repository branch)
<img width="878" alt="Screen Shot 2022-09-26 at 4 29 48 PM" src="https://user-images.githubusercontent.com/105233146/192260190-4c7212f0-221c-410b-9931-780a0cdb01e8.png">

Whereas I'm expecting this to only create a pull request to `master`.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Expected behavior

Pull request should be created to the specified branch, ie., `master`.

### How do you run Weblate?

Docker container

### Weblate versions

* Weblate: 4.13.1
 * Django: 4.0.5
 * siphashc: 2.1
 * translate-toolkit: 3.7.1
 * lxml: 4.6.5
 * Pillow: 9.1.1
 * bleach: 5.0.1
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.0
 * django-compressor: 4.0
 * djangorestframework: 3.13.1
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.7.1
 * jellyfish: 0.9.0
 * openpyxl: 3.0.10
 * celery: 5.2.7
 * kombu: 5.2.4
 * translation-finder: 2.13
 * weblate-language-data: 2022.5
 * html2text: 2020.1.16
 * pycairo: 1.21.0
 * pygobject: 3.42.1
 * diff-match-patch: 20200713
 * requests: 2.28.1
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.6.0
 * Cython: 0.29.30
 * misaka: 2.1.1
 * GitPython: 3.1.27
 * borgbackup: 1.2.1
 * pyparsing: 3.0.9
 * pyahocorasick: 1.4.4
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.1.0
 * Python: 3.10.5
 * Git: 2.30.2
 * psycopg2: 2.9.3
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * boto3: 1.24.21
 * zeep: 4.1.0
 * aeidon: 1.11
 * iniparse: 0.5
 * mysqlclient: 2.1.1
 * Mercurial: 6.1.4
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 6.2.7
 * PostgreSQL server: 14.4
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: email-smtp.ap-south-1.amazonaws.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.15.0-1019-aws (aarch64)

**Comment by nijel** [comment]
It behaves as intended and documented: https://docs.weblate.org/en/latest/admin/continuous.html#pushing-changes-from-weblate
