### ISSUE TITLE
The save button is not active

### ISSUE THREAD

**Issue by danial-shirali-1380** [WeblateOrg/weblate#8157]
### Describe the issue

When translating texts, the save button is not active for me

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Screenshots

<img width="1081" alt="Screenshot 1401-07-05 at 02 28 29" src="https://user-images.githubusercontent.com/111172921/192395204-b833773d-0b81-4c2d-835a-9ff29d4d8f79.png">

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
There can be several reasons, the tooltip on the button will tell you that.

**Comment by comradekingu** [comment]
@danial-shirali-1380
Are you logged in?
