### ISSUE TITLE
Add user to the component

### ISSUE THREAD

**Issue by anuj-scanova** [WeblateOrg/weblate#8192]
### Describe the issue

Mine is a private project and have created multiple components for the project
<img width="1669" alt="Screen Shot 2022-10-07 at 11 35 40 AM" src="https://user-images.githubusercontent.com/105233146/194478956-e6d22219-f400-4ea7-9d6e-3dbe10af8726.png">

```
Project
  - Frontend component
  - Backend component
```

Each component is a restricted component
<img width="568" alt="Screen Shot 2022-10-07 at 11 36 12 AM" src="https://user-images.githubusercontent.com/105233146/194479048-8d97f513-382a-428c-b199-7032053afdda.png">

I have hired an external translator agency to provide the translation, hence want to share access to a specific component **Frontend component** with disabled **Automatic suggestion**. For that created a Team **Translator External**
<img width="589" alt="Screen Shot 2022-10-07 at 11 35 05 AM" src="https://user-images.githubusercontent.com/105233146/194478873-a1fbdd5f-d40a-4d0f-9e12-d8d737aa0475.png">

and added the user to the group.

But the user is only able to see the Glossary. Can't find how to grant permission to the restricted component.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Expected behavior

I should be able to grant permission to the specific components while hiding other components in the project from external translators.

### How do you run Weblate?

Docker container

### Weblate versions

Powered by [Weblate 4.14](https://weblate.org/)

**Comment by nijel** [comment]
This can currently be configured at /admin/, adding to teams UI should not be hard.

**Comment by Richard7111** [comment]
Hi, can you assign this issue to me? Would like to work on it.

**Comment by prakhar1144** [comment]
Hi, @nijel  I would like to work on this issue. Please assign this to me.

**Comment by nijel** [comment]
@prakhar1144 Thanks, I've just assigned you this issue.

**Comment by nijel** [comment]
@Danfro as mentioned before – this is possible using Django admin, Weblate UI is currently missing here.

**Comment by Danfro** [comment]
@nijel yes, I saw that. The missing weblate UI part I primarily meant, that would be great to have.

And may I add, it looks like when using hosted weblate, only an admin for https://hosted.weblate.org/admin/ can enter those settings unless I am missing something. At least for our project, adding "/admin/" at the end does result in a "page not known error".

**Comment by nijel** [comment]
Okay, let's implement this because I've already spent enough time explaining it here...

**Comment by Danfro** [comment]
Just tried it for the first time. Works great. Thank you very much @nijel !
