### ISSUE TITLE
Borg 1.2.x update

### ISSUE THREAD

**Issue by reloxx13** [WeblateOrg/weblate#8195]
### Describe the issue

Heya,     

are there any known problems with borgbackup 1.2.0 ?   
I want to use the new import-tar command introduced in 1.2.0 because I'm moving to a new server.    
`export-tar` worked fine, but I cannot find a good explanation about how to import the archive.tar back now.    
Current version is `borg 1.1.18`

https://github.com/WeblateOrg/weblate/blob/af3e55ffe1b7f0e4cb30aa52011fe98a36cdae26/requirements.txt#L2

https://www.borgbackup.org/releases/borg-1.2.html
> import-tar: New complement to export-tar. Import existing tar files or (together with export-tar) move archives from one borg repo to another. Please note that currently export-tar + import-tar is a lossy conversion as it does not support all metadata that borg create/extract supports (like ACLs, xattrs, flags).   

https://docs.weblate.org/en/latest/admin/backup.html    

Another question: is there a way to merge two Weblate instances? Do you have any hints for me for doing this?    
Users, history and memory, etc. doesn't matter, I just want the projects into one.    

The project settings are in the database with a persistent ID, I would have projects with the same ID, resulting in conflicts.    
My current approach is to choose the smaller Weblate instance and backup every project one by one and restore it in the other one. Or do you have another, better idea?       
Edit: i also found this now where the project export/import is suggested: https://docs.weblate.org/en/latest/admin/backup.html#project-level-backups

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Git checkout

**Comment by reloxx13** [comment]
borg >= 1.2.0 need python 3.8 😵‍💫

**Comment by nijel** [comment]
Yes, but you don't need `> 1.2.0` to run Weblate:

https://github.com/WeblateOrg/weblate/blob/3bc177503db7107c87cd83c241ad7c26244be3a5/requirements.txt#L1

For now, Weblate supports Python 3.7, and it will stay as long as we have it in our infra (see https://github.com/WeblateOrg/weblate/pull/8637).
