### ISSUE TITLE
Failed to fetch translations from Weblate Translation Memory

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#8197]
### Describe the issue

After entering "automatic suggestions" you will get an error and nothing will be displayed.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to automatic suggestions

### Screenshots

![unknown](https://user-images.githubusercontent.com/39633242/194710632-3d43294a-06fb-4582-af70-fa7e1d658d12.png)

### How do you run Weblate?

Docker container

### Weblate versions

4.15-dev — 219d7505aae6fcfa87f36a46d184979c19ff52d5

### Additional context

https://sentry.io/share/issue/0bb7d61b0a274c3c956fba4f81f159ac/

**Comment by DagomiFermax** [comment]
I have the same issue with the same version, Ticket#206711
![Captura de Pantalla 2022-10-17 a las 13 39 34](https://user-images.githubusercontent.com/84782477/196612028-d701d291-fd43-4fe4-b276-49b94e051712.png)

**Comment by DagomiFermax** [comment]
Thanks.

But I need to know when are deployed in the hosted service.
