### ISSUE TITLE
 add Pop-up warning for review:"Approval translation" 

### ISSUE THREAD

**Issue by yangyangdaji** [WeblateOrg/weblate#8198]
Superseded https://github.com/WeblateOrg/weblate/issues/8196

# Describe the problem
As proposed at GradienceTeam/Gradience#616 (comment)

The name "Approved Translation" can be misunderstood by project maintainers/reviewers.
Not known to cause read-only

So need to add Pop-up warning when clicking on the approve button for the maintainers/reviewers. After approval Contributors cannot change ,asking if it wants to continue.

# Describe the solution you'd like
add Pop-up warning for review:"Approval translation" asking if it wants to continue

**Comment by yangyangdaji** [comment]
ping @nijel

**Comment by Geeyun-JY3** [comment]
TBH I do not see why the prompt box for approved translation is necessary.
Can you explain why “misunderstood by project maintainers” then need to “inform contributors”?

The dimmed `Save and continue` button and missing `Save and stay` button already indicate that the current translation is approved.

I would suggest adding a state badge just like the `read-only` badge.

**Comment by yangyangdaji** [comment]
@Geeyun-JY3
add a Prompt Box to warn the maintainers. Contributors cannot change it after approval.

**Comment by Geeyun-JY3** [comment]
> The name "Approved Translation" can be misunderstood by project maintainers. Not known to cause read-only
> 
> add a Prompt Box to warn the maintainers. After approval Contributors cannot changes.

Please detail where you want to add such a prompt box. [Project Setting UI](https://docs.weblate.org/en/latest/workflows.html#turning-on-reviews) or somewhere else?
There is no such a `Approved Translation` string in Weblate UI.

**Comment by yangyangdaji** [comment]
add a Pop-up warning for "Approve Translation.

**Comment by comradekingu** [comment]
How about just changing the name to what it actually does?
Do you mean "reviewed"? (I didn't know that caused locking.)

**Comment by yangyangdaji** [comment]
> How about just changing the name to what it actually does? Do you mean "reviewed"? (I didn't know that caused locking.)

LGTM :)

**Comment by Geeyun-JY3** [comment]
I got you.
But obviously this should be a warning for reviewers instead of maintainers. 

And I think this is unnecessary.
The button itself already indicates its effect. I do not see why a reviewer would be misunderstood by these buttons.
A extra pop-up warning just makes the whole workflow less efficient.

**Comment by Geeyun-JY3** [comment]
> How about just changing the name to what it actually does?
> Do you mean "reviewed"? (I didn't know that caused locking.)

Please detail the string you want to change.

**Comment by comradekingu** [comment]
@Geeyun-JY3 You are saying it is called "Approval translation", and I don't know where that is used.
Secondarily, for some sort of reviewed string to also lock the translation should be expressed, when it isn't currently.
Personally I don't like locked strings at all.

**Comment by Geeyun-JY3** [comment]
> You are saying it is called "Approval translation", and I don't know where that is used.

@comradekingu It is not me. It is @yangyangdaji who [mentioned "Approval translation".](https://github.com/WeblateOrg/weblate/issues/8198#issuecomment-1274059369)

I just [said](https://github.com/WeblateOrg/weblate/issues/8198#issuecomment-1274101706):
> There is no such a `Approved Translation` string in Weblate UI.

***

> Secondarily, for some sort of reviewed string to also lock the translation should be expressed, when it isn't currently.

TBH I do not really understand this sentence.

> Personally I don't like these types of locked strings at all. It has been tried thoroughly on TX and Crowdin, where it doesn't work.

Like it or not, approving strings to make it uneditable just a part of the workflow.🤷🏻‍♂️ It depends on the project maintainers. 
I think the problem of https://github.com/GradienceTeam/Gradience/pull/616#issuecomment-1272144043 is just the project maintainer making some configurations about the review workflow (seems using the [Bulk edit add-on](https://docs.weblate.org/en/weblate-4.14.1/admin/addons.html#bulk-edit) to set the state automatically).

**Comment by yangyangdaji** [comment]
@Geeyun-JY3 
![Screenshot_20221012_110649](https://user-images.githubusercontent.com/108261729/195240766-f60b6d3e-f439-4f5a-8551-b869205bf0fd.jpg)

**Comment by Geeyun-JY3** [comment]
> ![Screenshot_20221012_110649](https://user-images.githubusercontent.com/108261729/195240766-f60b6d3e-f439-4f5a-8551-b869205bf0fd.jpg)

I know this and it is useless. We still do not what configurations are set.

**Comment by comradekingu** [comment]
https://docs.weblate.org/en/latest/workflows.html#translation-states

The question is _why_ it locks strings to reviewers. To be used right before a release?

**Comment by yangyangdaji** [comment]
It looks to me like they should be using some kind of script. Implementing automatic approval

**Comment by yangyangdaji** [comment]
That's why https://github.com/WeblateOrg/weblate/issues/8196 was proposed

**Comment by comradekingu** [comment]
The real question is _why_ reviewing stuff locks it for anyone besides other reviewers.
Is it to be used just prior to release? What happens when it is switched on and off?

https://docs.weblate.org/en/latest/workflows.html is in a sorry state.

@Geeyun-JY3 I see you are added as a reviewer for https://github.com/WeblateOrg/weblate/pull/7505/files#commit-suggestions
Tried to brush it up just now. That would help out greatly for a first pass.

**Comment by Geeyun-JY3** [comment]
> https://docs.weblate.org/en/latest/workflows.html#translation-states
> 
> The question is _why_ it locks strings to reviewers. To be used right before a release?

Locking strings to reviewers is what the approved state is for. That is the function. I think the [documentation you mentioned](https://docs.weblate.org/en/weblate-4.14.1/workflows.html#translation-states) has already clarified this.
If you are asking why strings are approved in some projects, you should ask the project maintainers. There are many reasons for them to choose to enable review workflow and approve strings at some time.

**Comment by yangyangdaji** [comment]
I will use the Issues for discussion

**Comment by Geeyun-JY3** [comment]
What a mess…

**Comment by yangyangdaji** [comment]
Replaced by #8208
