### ISSUE TITLE
expose SOCIAL_AUTH_GITEA config options for docker deployment

### ISSUE THREAD

**Issue by Bubu** [WeblateOrg/weblate#8205]
### Describe the problem

We'd like to configure gitea oauth for a docker deployment. This currently requires using `settings-override.py`, it would be nice if it instead can be exposed like all the other oauth settings via `WEBLATE_*` env vars.

### Describe the solution you'd like

see above

**Comment by Revortni** [comment]
@nijel hey I'd like to give this a try

**Comment by nijel** [comment]
@Revortni you're welcome!

**Comment by Revortni** [comment]
ok so i looked into the social core documentation for gitea and it seems only the below code would suffice.
`SOCIAL_AUTH_GITEA_KEY = os.environ.get("WEBLATE_SOCIAL_AUTH_GITEA_KEY", "") `
` SOCIAL_AUTH_GITEA_SECRET = os.environ.get( 
    "WEBLATE_SOCIAL_AUTH_GITEA_SECRET", "" 
)`

**Comment by Revortni** [comment]
@nijel hey there. any comments on this?

**Comment by nijel** [comment]
The URL is most likely needed as well to specify the gitea server URL.

**Comment by Revortni** [comment]
> You also need to add the backend to AUTHENTICATION_BACKENDS (see the above example).
as you can see below the documentation does not specify any authentication backend for Gitea. 
![image](https://user-images.githubusercontent.com/19191940/196636393-52abdc08-0c5c-4eb4-a912-f8d74043b433.png)

**Comment by Revortni** [comment]
> The URL is most likely needed as well to specify the gitea server URL.

Ok will add a config for this too

**Comment by Revortni** [comment]
@nijel I've mentioned my findings about the authentication backend above

**Comment by nijel** [comment]
It's generic way of enabling backends. Just look at the BitBucket example I've posted in https://github.com/WeblateOrg/weblate/issues/8205#issuecomment-1280522985. Also, it would be great if you could actually test that the integration works...
