### ISSUE TITLE
(review: "Strings waiting for review") Feature Suggestions

### ISSUE THREAD

**Issue by yangyangdaji** [WeblateOrg/weblate#8208]
Superseded https://github.com/WeblateOrg/weblate/issues/8198

# Describe the problem
###  Chinese
不是所有人都会看文档。大部分人只会理解表面意思「批准翻译」而不知道实际效果
这就是为什么我提出https://github.com/WeblateOrg/weblate/issues/8198 和 #8196 的原因

### English

1. Click "Save" Weblate will change the translation directly to create the illusion that approval is not required
![Screenshot_20221013_095158](https://user-images.githubusercontent.com/108261729/195484066-6a0d7e42-badd-4154-aac1-2572c40456aa.jpg)

2. (Strings waiting for review) indicates that these translations are Suggest
Needs reviewers approval

3. or Approval is not required to change the translation

## Let's make a hypothesis

 Strings waiting for review
Contributors cannot change translation  
but can Suggest
Awaiting approval from reviewers

### Just like in Crowdin:
![Screenshot_20221013_075639_com android chrome_edit_8797792181469](https://user-images.githubusercontent.com/108261729/195477667-19415b0a-5bca-4736-9061-16d3882af707.jpg)

Only one button

# 2. No translation approval required
Contributors can change the translation
### Just like in Weblate:
![Screenshot_20221013_081023_edit_4297130263927](https://user-images.githubusercontent.com/108261729/195470284-87101185-868a-4aba-908c-97179d782f5a.jpg)
# Describe the solution you'd like

1. Click "Save" Weblate will change the translation directly to create the illusion that approval is not required
![Screenshot_20221013_095158](https://user-images.githubusercontent.com/108261729/195484066-6a0d7e42-badd-4154-aac1-2572c40456aa.jpg)

2. (Strings waiting for review) indicates that these translations are Suggest
Needs reviewers approval
So Keep one a "Suggest button"
and treat the changes as Suggest

3. or not as "String waiting for review"
 Approval is not required to change the translation treat the changes as Suggest

**Comment by nijel** [comment]
The name is based on XLIFF (http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#approved)

**Comment by yangyangdaji** [comment]
I know, but I think if the translation needs to be approved, then he can't translate the string directly but only suggest that if he changes the translation string, it means don't review it

**Comment by Geeyun-JY3** [comment]
> I know, but I think if the translation needs to be approved, then he can't translate the string directly but only suggest that if he changes the translation string, it means don't review it

(TBH, this sentence is quite hard to understand. Please organize your words)

I think you just do not understand what “review” means in l10n and Weblate. Just try to figure it out and get used to it. “Review” is a commonly used term in l10n.

**Comment by yangyangdaji** [comment]
@Geeyun-JY3 Let's make a hypothesis

# 1. Strings waiting for review
Contributors cannot change translation  
but can Suggest
Awaiting approval from reviewers

### Just like in Crowdin:
![Screenshot_20221013_075639_com android chrome_edit_3462296721346](https://user-images.githubusercontent.com/108261729/195468919-42febca9-3146-4c40-8ac2-82b9427c474d.jpg)

# 2. Translated strings
Contributors can change the translation

**Comment by Geeyun-JY3** [comment]
So, what is wrong with the Weblate UI?

**Comment by yangyangdaji** [comment]
@Geeyun-JY3 

1. Click "Save" Weblate will change the translation directly to create the illusion that approval is not required
![Screenshot_20221013_095158](https://user-images.githubusercontent.com/108261729/195484066-6a0d7e42-badd-4154-aac1-2572c40456aa.jpg)

2. (Strings waiting for review) indicates that these translations are Suggest
Needs reviewers approval
So Keep one a Suggest button
and treat the changes as Suggest

**Comment by Geeyun-JY3** [comment]
要不你还是写中文吧，你这英文也太烂了，真心看不懂。

**Comment by yangyangdaji** [comment]
@Geeyun-JY3 我的意思是 Crowdin 那样，既然是带审核的翻译。那么那么就不要让贡献者直接更改字符串，应该和建议一样等待他的审查者审核 同意之后在更改字符串。

**Comment by yangyangdaji** [comment]
或者就不需要说成等待审查，直接视为已翻译

**Comment by yangyangdaji** [comment]
问题就这么简单仅此而已，我觉得不说英文更快点 
我还用了 Grammarly 😂

**Comment by Geeyun-JY3** [comment]
> 我的意思是 Crowdin 那样，既然是待审核的翻译。那么那么就不要让贡献者直接更改字符串，应该和建议一样等待他的审查者审核 同意之后在更改字符串。

0. 不要把 Crowdin 的翻译流程（workflow）套在 Weblate 上，本来就是不一样的设计和逻辑。
1. Crowdin 的模式是：平行展示曾经提交过的译文作为候选项，在译文（translation）未被 approve 时，采用最高票译文，如平票则采用最新提交的译文，一样会更改 VCS 里的译文，和 Weblate 这种直接更改本质上是类似的，并不是说译文被 approve 了才会被推送到 VCS（根据我的观察 crowdin.com 上的大部分项目都是这样，没研究过 Crowdin 有没有提供其他可改变翻译流程的相关设置项，猜测应该是有的，只是我暂时还没碰到过这样的项目）。
2. Weblate 的模式是：无论项目是否启用审校（Enable reviews），只采用最新提交的译文，在字符串未被 approve 前，不同的译文想要竞争，实践中更建议通过提交建议（suggestion）然后讨论协商；当然 Weblate 这种流程是有可能发生编辑战的。
Transifex 其实也是类似 Weblate 这种流程。

流程中包含审校不代表呈现方式只能像 Crowdin 那样，更何况 Weblate 里建议可实现类似的平行展示多个译文候选项。
上述两种流程最终 approve 的译文其实很大程度上还是取决于 proofreader/reviewer，我觉得这两种流程各有优劣。本来就是两种模式，为何要强求统一呢？

3. 更何况，光看文档，我感觉利用好 Weblate 的 [权限控制、群组、角色](https://docs.weblate.org/en/weblate-4.14.1/admin/access.html#users-roles-groups-and-permissions) 等是能搞出你想要的这种译者无法直接改，只能提建议，然后等审校员（reviewer）来 approve 才能使译文真正被更改的翻译流程。
觉得 Weblate 默认的这种流程不行，想优化，可以让项目维护者尝试去自定义（设置项应该是有的，不过不太清楚 Hosted Weblate 上能自定义到什么程度）。
没实践过不多猜测，不做保证。参见：<https://docs.weblate.org/en/weblate-4.14.1/workflows.html>。

> 或者就不需要说成等待审查，直接视为已翻译。不是谁都会看文档的

在 Weblate 中，可翻译的字符串有以下几个状态（state）：`approved`、`translated`、`needs-editing`、`empty`，其中只有项目启用审校的流程时才会有 `approved` 这个状态。
所以 Weblate 语境下，**待审校**（_Waiting for review_）这个字符串只会在项目启用审校的流程时出现，表示字符串目前已翻译（`translated`）但没核准（`approved`），你可以去看看启用了审校流程的项目的某个部件的翻译的概览 tab（如：<https://hosted.weblate.org/projects/f-droid/fdroiddata/zh_Hans/#overview>），其中字符串状态（Strings status）一栏里的 `待审校的字符串`（Strings waiting for review）的 URL 就是以 `?q=state:translated` 结尾，其指的就是状态为 `translated` 的字符串。

> 大部分人只会理解表面意思「批准翻译」而不知道实际效果，这就是为什么我提出 https://github.com/WeblateOrg/weblate/issues/8198 和 https://github.com/WeblateOrg/weblate/issues/8196 的原因

你横跨几个 issue 说半天的「批准翻译」（Approval translation）到底在哪？Weblate 的 UI 根本就没有这个字符串，谈何用户怎么理解？

***

> 问题就这么简单仅此而已，我觉得不说英文，快多了
我还用了 Grammarly 😂

让你写中文是因为你英文写得实在是一塌糊涂，根本看不懂（属实是 Grammarly 也救不了😅），方便仅在这个 issue 下进行的暂时的交流而已。
待会还是要给其他人解释的。
这么**简单**的问题你还得开了两三个 issue，来回十几条评论，题目评论删删改改十几次，最后还得写中文才让人理解得了，很担心在其他项目你和别人协作时会如何，尤其是在对面看不懂中文的时候😅。

***

> 这就是为什么我提出 #8198 和 #8196 的原因

顺带一提，这是一个病句。

**Comment by Geeyun-JY3** [comment]
> 我的意思是 Crowdin 那样，既然是待审核的翻译。那么那么就不要让贡献者直接更改字符串，应该和建议一样等待他的审查者审核 同意之后在更改字符串。

0. 不要把 Crowdin 的翻译流程（workflow）套在 Weblate 上，本来就是不一样的设计和逻辑。
1. Crowdin 的模式是：平行展示曾经提交过的译文作为候选项，在译文（translation）未被 approve 时，采用最高票译文，如平票则采用最新提交的译文，一样会更改 VCS 里的译文，和 Weblate 这种直接更改本质上是类似的，并不是说译文被 approve 了才会被推送到 VCS（根据我的观察 crowdin.com 上的大部分项目都是这样，没研究过 Crowdin 有没有提供其他可改变翻译流程的相关设置项，猜测应该是有的，只是我暂时还没碰到过这样的项目）。
2. Weblate 的模式是：无论项目是否启用审校（Enable reviews），只采用最新提交的译文，在字符串未被 approve 前，不同的译文想要竞争，实践中更建议通过提交建议（suggestion）然后讨论协商；当然 Weblate 这种流程是有可能发生编辑战的。
Transifex 其实也是类似 Weblate 这种流程。

流程中包含审校不代表呈现方式只能像 Crowdin 那样，更何况 Weblate 里建议可实现类似的平行展示多个译文候选项。
上述两种流程最终 approve 的译文其实很大程度上还是取决于 proofreader/reviewer，我觉得这两种流程各有优劣。本来就是两种模式，为何要强求统一呢？

3. 更何况，光看文档，我感觉利用好 Weblate 的 [权限控制、群组、角色](https://docs.weblate.org/en/weblate-4.14.1/admin/access.html#users-roles-groups-and-permissions) 等是能搞出你想要的这种译者无法直接改，只能提建议，然后等审校员（reviewer）来 approve 才能使译文真正被更改的翻译流程。
觉得 Weblate 默认的这种流程不行，想优化，可以让项目维护者尝试去自定义（设置项应该是有的，不过不太清楚 Hosted Weblate 上能自定义到什么程度）。
没实践过不多猜测，不做保证。参见：<https://docs.weblate.org/en/weblate-4.14.1/workflows.html>。

> 或者就不需要说成等待审查，直接视为已翻译。不是谁都会看文档的

在 Weblate 中，可翻译的字符串有以下几个状态（state）：`approved`、`translated`、`needs-editing`、`empty`，其中只有项目启用审校的流程时才会有 `approved` 这个状态。
所以 Weblate 语境下，**待审校**（_Waiting for review_）这个字符串只会在项目启用审校的流程时出现，表示字符串目前已翻译（`translated`）但没核准（`approved`），你可以去看看启用了审校流程的项目的某个部件的翻译的概览 tab（如：<https://hosted.weblate.org/projects/f-droid/fdroiddata/zh_Hans/#overview>），其中字符串状态（Strings status）一栏里的 `待审校的字符串`（Strings waiting for review）的 URL 就是以 `?q=state:translated` 结尾，其指的就是状态为 `translated` 的字符串。

> 大部分人只会理解表面意思「批准翻译」而不知道实际效果，这就是为什么我提出 https://github.com/WeblateOrg/weblate/issues/8198 和 https://github.com/WeblateOrg/weblate/issues/8196 的原因

你横跨几个 issue 说半天的「批准翻译」（Approval translation）到底在哪？Weblate 的 UI 根本就没有这个字符串，谈何用户怎么理解？

***

> 问题就这么简单仅此而已，我觉得不说英文，快多了
我还用了 Grammarly 😂

让你写中文是因为你英文写得实在是一塌糊涂，根本看不懂（属实是 Grammarly 也救不了😅），方便仅在这个 issue 下进行的暂时的交流而已。
待会还是要给其他人解释的。
这么**简单**的问题你还得开了两三个 issue，来回十几条评论，题目评论删删改改十几次，最后还得写中文才让人理解得了，很担心在其他项目你和别人协作时会如何，尤其是在对面看不懂中文的时候😅。

***

> 这就是为什么我提出 #8198 和 #8196 的原因

顺带一提，这是一个病句。

**Comment by yangyangdaji** [comment]
impossible

**Comment by Geeyun-JY3** [comment]
[Translation approved](https://hosted.weblate.org/translate/weblate/application/en/?checksum=d29a1f12e0564633) 这字符串有啥不好理解的地方😳？

**Comment by yangyangdaji** [comment]
我觉得他应该选择选项才会达到这种效果，我想把类似的改成 [批准并设为不可编辑]



---Original---
From: ***@***.***&gt;
Date: Thu, Oct 13, 2022 18:12 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [WeblateOrg/weblate] (review: "Strings waiting for review")Feature Suggestions (Issue #8208)




 
Translation approved 这字符串有啥不好理解的地方😳？

**Comment by yangyangdaji** [comment]
@Geeyun-JY3 谢谢耐心的替我解答

**Comment by Geeyun-JY3** [comment]
`approved` 这个状态就是让无权限的人不能编辑，叫什么「不可编辑」显然也会误导。

Crowdin、OneSky 用的也都是「Approved」，就是习惯一下的事，这本就是个在 l10n 里很常见的单词。

**Comment by yangyangdaji** [comment]
懂了



---Original---
From: ***@***.***&gt;
Date: Thu, Oct 13, 2022 19:06 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [WeblateOrg/weblate] (review: "Strings waiting for review")Feature Suggestions (Issue #8208)




 
approved 这个状态就是让无权限的人不能编辑，叫什么「不可编辑」显然也会误导。
 
Crowdin、OneSky 用的也都是「Approved」，就是习惯一下的事，这本就是个在 l10n 里很常见的单词。
