### ISSUE TITLE
expose AVATAR_URL_PREFIX config option for docker deployment

### ISSUE THREAD

**Issue by Bubu** [WeblateOrg/weblate#8210]
### Describe the problem

I'd like to set the AVATAR_URL_PREFIX option via environment variable. It's currently only possible via `settings-override.py`

### Describe the solution you'd like

see above

**Comment by nijel** [comment]
@dankrzeminski32 Yes, you're welcome!

**Comment by nijel** [comment]
The Docker configuration is here: 
https://github.com/WeblateOrg/weblate/blob/e9ac4d5f1b553e02fd32a93f6822997ca2c036b1/weblate/settings_docker.py#L1363

**Comment by dankrzeminski32** [comment]
@nijel Hi, I have added the changes to the docker settings file, I am looking to update the documentation on this now... 

Do I put 4.14.2 for the 'versionadded'?

```rst
.. envvar:: WEBLATE_AVATAR_URL_PREFIX

   .. versionadded:: 4.14.2

   Configures :setting:`AVATAR_URL_PREFIX`.
```
