### ISSUE TITLE
Desintalación

### ISSUE THREAD

**Issue by GustavoGirardelli** [WeblateOrg/weblate#8219]
### Describe the issue

[a](https://docs.weblate.org/es/latest/admin/install/venv-debian.html)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

weblate.org service

**Comment by GustavoGirardelli** [comment]
I sent it to support

**Comment by GustavoGirardelli** [comment]
Yo lo mandé a soporte

**Comment by GustavoGirardelli** [comment]
They still don't help me
Aún no me ayudan

**Comment by nijel** [comment]
Please write in English here and describe your problem. Posting a single link to the documentation is not really a problem description...
