### ISSUE TITLE
Use appconf for settings handling

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#822]
Weblate currently comes with own handling of configuration defaults, it might be good idea to replace it with http://django-appconf.readthedocs.org/en/latest/
##

**Comment by kryskool** [comment]
Hi @nijel 

I use a similar module to manage apps, django-configurations. I didn't check all differences from django-appconf, but it seem more complete.

http://django-configurations.readthedocs.io/en/stable/

regards,

**Comment by nijel** [comment]
That indeed sounds like an option.

**Comment by nijel** [comment]
Done in 3363d8b9664f7f0b3a862dce8e9b8434caf1e192
