### ISSUE TITLE
Eliminar registro

### ISSUE THREAD

**Issue by GustavoGirardelli** [WeblateOrg/weblate#8220]
borrar cuenta de  Weblate

delete weblate account

Delete weblate record

Eliminar registro Weblate

**Comment by GustavoGirardelli** [comment]
Ooooooooo......

**Comment by GustavoGirardelli** [comment]
Oooo...


*      Lic. Gustavo A. Girardelli    .*

*.*

**Comment by nijel** [comment]
Duplicate of #8219
