### ISSUE TITLE
Python SIGSEGV on RHEL-9 (python-3.9)

### ISSUE THREAD

**Issue by assen-totin** [WeblateOrg/weblate#8222]
### Describe the issue

Database migration results in core dump.
All Celery workers core dump at startup.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

I have a Weblate 4.10.1 system running fine on RHEL-8 (python 3.6). As Weblate 4.11 requries Python 3.7, I decided to move the system to the latest RedHat version, which is RHEL-9 (GA from May 2022, updated with all patches as of today). Weblate is installed with PIP, the web runs under Apache web server, Celery runs under systemd.

I installed the same Weblate version, 4.10.1 on RHEL-9, copied the config file, connected to the original Postgres and stared the web - all worked OK.

I then started all Celery workers (via system) and each of them ended immediately with segfault. 

Hoping that the issue may have been resolved between December 2021 (when 4.10.1 was released) an the current 4.14.1 version, I upgraded to this latest Weblate version - sadly, to no avail. Python still crashes when starting a Celery worker, even when doing a migration or even when collecting some info from the weblate system. Outside Weblate python works fine.

### Expected behavior

- Celery workers start normally
- Database migration completes fine.

### Exception traceback

```pytb
Here is the complete backtrace from the core file - albeit the first few lines are perhaps the interesting ones.

Reading symbols from /usr/bin/python...
Reading symbols from .gnu_debugdata for /usr/bin/python3.9...
(No debugging symbols found in .gnu_debugdata for /usr/bin/python3.9)
[New LWP 4159]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/var/www/weblate/bin/python /var/www/weblate/bin/weblate migrate --noinput'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f8667b4ceb3 in pango_shape_with_flags () from /lib64/libpango-1.0.so.0
Missing separate debuginfos, use: dnf debuginfo-install python-unversioned-command-3.9.10-2.el9.noarch
(gdb) bt
#0  0x00007f8667b4ceb3 in pango_shape_with_flags () at /lib64/libpango-1.0.so.0
#1  0x00007f8667b3ddbe in shape_run () at /lib64/libpango-1.0.so.0
#2  0x00007f8667b3eeec in process_item.lto_priv () at /lib64/libpango-1.0.so.0
#3  0x00007f8667b4479c in pango_layout_check_lines.part.0.lto_priv () at /lib64/libpango-1.0.so.0
#4  0x00007f8667b38a02 in pango_layout_get_line_count () at /lib64/libpango-1.0.so.0
#5  0x00007f8668a448b6 in ffi_call_unix64 () at /lib64/libffi.so.8
#6  0x00007f8668a41556 in ffi_call_int.lto_priv () at /lib64/libffi.so.8
#7  0x00007f8668af1be5 in pygi_invoke_c_callable
    (function_cache=0x558e0a7e7970, state=<optimized out>, py_args=<optimized out>, py_kwargs=<optimized out>) at gi/pygi-invoke.c:684
#8  0x00007f8668ae8cdc in pygi_function_cache_invoke
    (function_cache=<optimized out>, py_args=py_args@entry=0x7f8663f92400, py_kwargs=py_kwargs@entry=0x0) at gi/pygi-cache.c:862
#9  0x00007f8668af2349 in pygi_callable_info_invoke (user_data=0x0, cache=<optimized out>, kwargs=0x0, py_args=0x7f8663f92400, info=<optimized out>)
    at gi/pygi-invoke.c:727
#10 0x00007f8668aed04d in _callable_info_call (self=0x7f866376af30, args=0x7f866c87a040, kwargs=0x0) at gi/pygi-info.c:548
#11 0x00007f866cd12744 in _PyObject_MakeTpCall () at /lib64/libpython3.9.so.1.0
#12 0x00007f866cd0f6ae in _PyEval_EvalFrameDefault () at /lib64/libpython3.9.so.1.0
#13 0x00007f866cd090dd in _PyEval_EvalCode () at /lib64/libpython3.9.so.1.0
#14 0x00007f866cd16c8e in _PyFunction_Vectorcall () at /lib64/libpython3.9.so.1.0
#15 0x00007f866cdbdb5a in bounded_lru_cache_wrapper () at /lib64/libpython3.9.so.1.0
#16 0x00007f866cd12744 in _PyObject_MakeTpCall () at /lib64/libpython3.9.so.1.0
#17 0x00007f866cd0f1de in _PyEval_EvalFrameDefault () at /lib64/libpython3.9.so.1.0
#18 0x00007f866cd090dd in _PyEval_EvalCode () at /lib64/libpython3.9.so.1.0
#19 0x00007f866cd16c8e in _PyFunction_Vectorcall () at /lib64/libpython3.9.so.1.0
#20 0x00007f866cd0b41c in _PyEval_EvalFrameDefault () at /lib64/libpython3.9.so.1.0
#21 0x00007f866cd090dd in _PyEval_EvalCode () at /lib64/libpython3.9.so.1.0
#22 0x00007f866cd16c8e in _PyFunction_Vectorcall () at /lib64/libpython3.9.so.1.0
#23 0x00007f866cd1f261 in method_vectorcall () at /lib64/libpython3.9.so.1.0
#24 0x00007f866cd0b41c in _PyEval_EvalFrameDefault () at /lib64/libpython3.9.so.1.0
#25 0x00007f866cd090dd in _PyEval_EvalCode () at /lib64/libpython3.9.so.1.0
#26 0x00007f866cd16c8e in _PyFunction_Vectorcall () at /lib64/libpython3.9.so.1.0
#27 0x00007f866cd1f261 in method_vectorcall () at /lib64/libpython3.9.so.1.0
#28 0x00007f866cd0b41c in _PyEval_EvalFrameDefault () at /lib64/libpython3.9.so.1.0
#29 0x00007f866cd090dd in _PyEval_EvalCode () at /lib64/libpython3.9.so.1.0
#30 0x00007f866cd16c8e in _PyFunction_Vectorcall () at /lib64/libpython3.9.so.1.0
#31 0x00007f866cd1f745 in PyVectorcall_Call () at /lib64/libpython3.9.so.1.0
#32 0x00007f866cd0d30a in _PyEval_EvalFrameDefault () at /lib64/libpython3.9.so.1.0
#33 0x00007f866cd090dd in _PyEval_EvalCode () at /lib64/libpython3.9.so.1.0
#34 0x00007f866cd16c8e in _PyFunction_Vectorcall () at /lib64/libpython3.9.so.1.0
#35 0x00007f866cd1f261 in method_vectorcall () at /lib64/libpython3.9.so.1.0
#36 0x00007f866cd1f745 in PyVectorcall_Call () at /lib64/libpython3.9.so.1.0
--Type <RET> for more, q to quit, c to continue without paging--
#37 0x00007f866cd0d30a in _PyEval_EvalFrameDefault () at /lib64/libpython3.9.so.1.0
#38 0x00007f866cd090dd in _PyEval_EvalCode () at /lib64/libpython3.9.so.1.0
#39 0x00007f866cd16c8e in _PyFunction_Vectorcall () at /lib64/libpython3.9.so.1.0
#40 0x00007f866cd1f261 in method_vectorcall () at /lib64/libpython3.9.so.1.0
#41 0x00007f866cd1f745 in PyVectorcall_Call () at /lib64/libpython3.9.so.1.0
#42 0x00007f866cd0d30a in _PyEval_EvalFrameDefault () at /lib64/libpython3.9.so.1.0
#43 0x00007f866cd16f33 in function_code_fastcall () at /lib64/libpython3.9.so.1.0
#44 0x00007f866cd0a6bd in _PyEval_EvalFrameDefault () at /lib64/libpython3.9.so.1.0
#45 0x00007f866cd16f33 in function_code_fastcall () at /lib64/libpython3.9.so.1.0
#46 0x00007f866cd0a6bd in _PyEval_EvalFrameDefault () at /lib64/libpython3.9.so.1.0
#47 0x00007f866cd16f33 in function_code_fastcall () at /lib64/libpython3.9.so.1.0
#48 0x00007f866cd0a45b in _PyEval_EvalFrameDefault () at /lib64/libpython3.9.so.1.0
#49 0x00007f866cd090dd in _PyEval_EvalCode () at /lib64/libpython3.9.so.1.0
#50 0x00007f866cd864c5 in _PyEval_EvalCodeWithName () at /lib64/libpython3.9.so.1.0
#51 0x00007f866cd8645d in PyEval_EvalCodeEx () at /lib64/libpython3.9.so.1.0
#52 0x00007f866cd8640f in PyEval_EvalCode () at /lib64/libpython3.9.so.1.0
#53 0x00007f866cdb5644 in run_eval_code_obj () at /lib64/libpython3.9.so.1.0
#54 0x00007f866cdb14f6 in run_mod () at /lib64/libpython3.9.so.1.0
#55 0x00007f866cc84ea0 in pyrun_file.cold () at /lib64/libpython3.9.so.1.0
#56 0x00007f866cdab423 in PyRun_SimpleFileExFlags () at /lib64/libpython3.9.so.1.0
#57 0x00007f866cda8688 in Py_RunMain () at /lib64/libpython3.9.so.1.0
#58 0x00007f866cd78f0d in Py_BytesMain () at /lib64/libpython3.9.so.1.0
#59 0x00007f866ca34e50 in __libc_start_call_main () at /lib64/libc.so.6
#60 0x00007f866ca34efc in __libc_start_main_impl () at /lib64/libc.so.6
#61 0x0000558e08609095 in _start ()
```

### How do you run Weblate?

PyPI module

### Weblate versions

(weblate) [root@cgdcweblate weblate]# weblate list_versions
 * Weblate: 4.14.1
 * Django: 4.0.8
 * siphashc: 2.1
 * translate-toolkit: 3.7.3
 * lxml: 4.9.1
 * Pillow: 9.2.0
 * bleach: 4.1.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.13.0
 * oauthlib: 3.2.1
 * django-compressor: 3.1
 * djangorestframework: 3.13.1
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.8.0
 * rapidfuzz: 2.11.1
 * openpyxl: 3.0.10
 * celery: 5.2.7
 * kombu: 5.2.4
 * translation-finder: 2.14
 * weblate-language-data: 2022.7
 * html2text: 2020.1.16
 * pycairo: 1.21.0
 * pygobject: 3.42.2
 * diff-match-patch: 20200713
 * requests: 2.26.0
 * django-redis: 5.1.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.9.10
 * Cython: 0.29.32
 * misaka: 2.1.1
 * GitPython: 3.1.29
 * borgbackup: 1.1.18
 * pyparsing: 3.0.9
 * pyahocorasick: 1.4.4
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.0.12
 * Python: 3.9.10
 * Git: 2.31.1
 * psycopg2-binary: 2.9.4
 * ruamel.yaml: 0.17.21
 * Redis server: 6.2.6
 * PostgreSQL server: 14.5
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp-out.curaden-hosting.ch
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: sentinel://172.16.70.61:26379/1;sentinel://172.16.70.62:26379/1;sentinel://172.16.70.63:26379/1, sentinel://172.16.70.61:26379/1;sentinel://172.16.70.62:26379/1;sentinel://172.16.70.63:26379/1, regular
 * Platform: Linux 5.14.0-70.26.1.el9_0.x86_64 (x86_64)

### Weblate deploy checks

```shell
(weblate) [root@cgdcweblate weblate]# weblate check --deploy
Segmentation fault
```

### Additional context

(weblate) [root@cgdcweblate weblate]# rpm -q pango
pango-1.48.7-2.el9.x86_64
(weblate) [root@cgdcweblate weblate]# rpm -q cairo
cairo-1.17.4-7.el9.x86_64

On the working RHEL-8 system, pango is 1.42.

On its own, Python works on the system (a lot of RHEL CLI/TUI tools are written in Python and none has produced a segfault so far; we also run other Python code on RHEL-9 without similar issues).

As I get it form the backtrace, we leave pure python for gi/pygi-info, then we go into FFI and then into Pango.

What I really don't understand is why a command-line operation like a database migration needs to load fonts?

Has anybody seen anything similar before?

**Comment by nijel** [comment]
As the crash is happening in libpango, try rebuilding pycairo (`pip install --force-reinstall --no-binary :all: pycairo`) or checking that your gobject introspection packages match the libraries versions (it seems to be `gobject-introspection-devel` and `gobject-introspection` packages on RHEL).

**Comment by assen-totin** [comment]
Thank you, but this did not help.

I already had pycairo-1.21.0 - and nothing had changed or were upgraded to justify rebuild it. Yet I did, and, as expected, to no avail - still SIGSEGV in Python.

As of the gobject-introspection, they do match - YUM normally tracks there and it i snot that easy to break your system.

(weblate) [root@cgdcweblate weblate]# rpm -qa | grep gobject-introspection*
gobject-introspection-1.68.0-10.el9.x86_64
gobject-introspection-devel-1.68.0-10.el9.x86_64

**Comment by assen-totin** [comment]
Hello,

We eventually found the reason for the crash: the static assets have not been collected (which prevents the stack from finding a font it is looking for, which absence it fails to identify, which then leads to null pointer defer in Pango).
