### ISSUE TITLE
Changes made in tabs from former session skip history

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#8235]
### Describe the issue

It is possible to make changes that skip the history.

[Access denied](https://hosted.weblate.org/) 

CSRF-verifification failed. Request cancelled.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Open many WL tabs from Hosted (in FF 102.3.0esr (64-bit))
Get logged out after a while
Log in at one tab
Make changes in another (where the user always was seemingly logged in)

>[Access denied](https://hosted.weblate.org/) 

CSRF-verification failed. Request cancelled.

### How do you run Weblate?

weblate.org service

### Additional context

I did this in https://hosted.weblate.org/translate/debian-handbook/90_derivative-distributions/nb_NO/?checksum=1bd415abc9ee2e3b

Ubuntu har nådd et bredt publikum (my change)
Ubuntu har nådd _ut_ til et bredt publikum (former version)

The change doesn't show up in https://hosted.weblate.org/languages/nb_NO/debian-handbook/#history either.

Edit: It may that I just opened some tabs after being logged in, and then logged in at another tab.
In any event, using the tabs that are not refreshed to make changes is what leads to the issue.

**Comment by nijel** [comment]
In case you got CSRF denied, the form was definitely not saved. The string there sill contains "ut til":

![obrazek](https://user-images.githubusercontent.com/212189/196159684-b2a2d10e-6f6a-4448-a19a-b58e23e9fd60.png)
