### ISSUE TITLE
User profile loading slowly

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#8236]
### Describe the problem

Slow loading of the profile occurs in users who contribute to a huge number of components (over 2000).
https://weblate.examples/user/user_examples/

### Describe the solution you'd like

You can enter pagination.

### Screenshots

![image](https://user-images.githubusercontent.com/39633242/196168101-d5e9c661-e8d6-475a-b720-ffa507c805d6.png)

**Comment by gernathlub** [comment]
Hi I would like to start working on this issue if its still a valid one

**Comment by nijel** [comment]
Yes, the question is whether pagination is the best approach here. Maybe listing first few (50?) projects and adding a link to browse rest of them - elsewhere and paginated.

**Comment by tomkolp** [comment]
Yes, displaying the first 50, and then loading the rest after pressing the "see more" button.  Ideally, the rest of the pages are loaded on the same page, there may be a new page in the end.

**Comment by Geeyun-JY3** [comment]
If implemented, the same logic should be applied to the `Watched projects` and `Managed projects` tabs too.

**Comment by nijel** [comment]
Yes, all projects listing should be affected. I'd prefer to do a complete listing on /projects/ page, it just needs to add support for filtering the projects this way.

**Comment by comradekingu** [comment]
Would it be a bit faster if /#changes was used as a landing for user profiles? It doesn't list as much, and then has the button to view more.
