### ISSUE TITLE
Missing translations from a language

### ISSUE THREAD

**Issue by tsabi** [WeblateOrg/weblate#8237]
### Describe the issue

I have this in my `component.pot` file and also in the `hu.po` file:
```
#. module: website
#. openerp-web
#: code:addons/website/static/src/xml/website.cookies_bar.xml:0
#, python-format
msgid "We use cookies to provide you a better user experience on this website."
msgstr ""
```

When i search in the component for `location:website.cookies_bar` in the english language i got the result, but in the hungarian language there is no result.

How can this happen and how can i fix it?
The most interesting thing is that this text is exists phisically in  the hu.po file, but when i search in weblate it dont find it.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

I really don't know how i made this.

### How do you run Weblate?

PyPI module

### Weblate versions

 * Weblate: 4.14.1
 * Django: 3.2.4
 * siphashc: 2.1
 * translate-toolkit: 3.7.3
 * lxml: 4.9.1
 * Pillow: 9.1.0
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.1
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.7.1
 * rapidfuzz: 2.10.0
 * openpyxl: 3.0.5
 * celery: 5.1.2
 * kombu: 5.1.0
 * translation-finder: 2.14
 * weblate-language-data: 2022.7
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.38.0
 * diff-match-patch: 20200713
 * requests: 2.27.1
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 1.9.2
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.8
 * borgbackup: 1.1.13
 * pyparsing: 3.0.9
 * pyahocorasick: 1.4.1
 * python-redis-lock: 3.6.0
 * charset-normalizer: 2.0.12
 * Python: 3.8.10
 * Git: 2.25.1
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.20.37
 * zeep: 3.4.0
 * aeidon: 1.10.1
 * iniparse: 0.5
 * Mercurial: 6.0.1
 * git-svn: 2.25.1
 * git-review: 1.28.0
 * Redis server: 5.0.7
 * PostgreSQL server: 13.8
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 5.15.39-1-pve (x86_64)

### Weblate deploy checks

```shell
System check identified no issues (1 silenced).
```

**Comment by tsabi** [comment]
I just noticed that in the English language information tab it says that there are 2193 source texts, while in Hungarian there are only 941.

**Comment by nijel** [comment]
Any errors in the server logs? Maybe there is parse error is some of the other files and Weblate will stop processing at that point.
