### ISSUE TITLE
Track comment removal/resolving in history

### ISSUE THREAD

**Issue by maboroshin** [WeblateOrg/weblate#8253]
### Describe the issue

Comments by two people (A and B) in the "History" tab. Comments by two people (A and C) into the "Comments" tab, One person is replaced by another.

e.g. [Sample divided comments](https://hosted.weblate.org/translate/free-tube/translations/ja/?checksum=078a8b1bbc0a0340#history).

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. See a string history tab with multiple comments.
2. See Comments tab.
3. Compare Speakers.

### Expected behavior

In the comments tab, everyone's comments. History tab includes everyone's updates and comments

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
The history tab can show deleted comments as well, those won't be visible on the comments tab. Maybe that's what you observe?

**Comment by maboroshin** [comment]
@nijel No. Kyotaro's comment (comment C) is not in the Comments tab. Not all comments are displayed in the Comments tab. Is this not a bug? 

The following is correct. And, Hence my comments will disappear from the History tab. (Upper limit 10 logs: https://github.com/WeblateOrg/weblate/issues/8254)
* maboroshin's comment (comment B)  in the Comments tab is 2 years old. (2020-10-12)
* Kyotaro's comments (comment C)  on the History tab are newer than this. (2020-10-26)

**Comment by Geeyun-JY3** [comment]
I would suggest that Weblate should track the comments deletion (“Comment deleted”) and resolution (“Comment resolved”) in history.

If this would make the `History`  of translation editor full of comment related activities, a filter for the `History` tab to show all comment related activities or not maybe needed.
Just like GitLab(?):
![image](https://user-images.githubusercontent.com/49396421/186398404-0b65f478-b3c1-44f5-9175-52ec44b2dc18.png)
