### ISSUE TITLE
Add view for all string level changes

### ISSUE THREAD

**Issue by maboroshin** [WeblateOrg/weblate#8254]
### Describe the problem

I can't see each whole history, Assumed to be about 2 pages. But we can only see 10 change logs. It is shown at the bottom of the change history: <code>Browse all component changes</code>. Press this to see all history for this project. It's over 100 pages. e.g. [Sample string](https://hosted.weblate.org/translate/free-tube/translations/ja/?checksum=11e5157a289519d4)

### Describe the solution you'd like

Increase the upper limit from 10 change logs. This seems easy. Simply displaying 30 logs would solve much of the problem.

### Describe alternatives you've considered

Ideally, All history and comments for that string are displayed in the History tab.

**Comment by nijel** [comment]
There should be a link in the bottom of the list to show all string changes instead of the component ones.

**Comment by comradekingu** [comment]
@maboroshin Do you want to see all string changes for the entire project, or
do you want to see all string changes for an individual string (without resorting to finding it in the general history)?

**Comment by maboroshin** [comment]
@comradekingu : The entire history is already displayed.

What needs to be improved. If you open an individual string, there are only 10 logs.
