### ISSUE TITLE
(show differences) The text is highlighted incorrectly

### ISSUE THREAD

**Issue by yangyangdaji** [WeblateOrg/weblate#8257]
### 1. The added text is not highlighted

![Screenshot_20221022_221721_edit_53780273445439](https://user-images.githubusercontent.com/108261729/197344140-bbf0e42f-64a3-4df4-b90c-78fdf4562302.jpg)

### 2. Strikethrough color inconsistency

![Screenshot_20221022_173610_edit_37724510066118](https://user-images.githubusercontent.com/108261729/197332687-f125affa-5ee2-4e00-a120-3008133bc39e.jpg)

### 1
https://hosted.weblate.org/translate/jamulus/windows-installer/zh_Hans/?checksum=9f211635d90572e3

### 2
https://hosted.weblate.org/projects/jamulus/windows-installer/zh_Hans/#history
### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 4.14.2-dev

**Comment by Geeyun-JY3** [comment]
@nijel Still can reproduce the strikethrough color issue in suggestion-related events
Example: https://hosted.weblate.org/translate/debian-handbook/14_security/zh_Hans/?checksum=5f15c91d08b7638d#history

**Comment by nijel** [comment]
That should be fixed in cbde36b3b6
