### ISSUE TITLE
Update an existing string's translators explanation from a translators-comment from its source POT-file

### ISSUE THREAD

**Issue by SantosSi** [WeblateOrg/weblate#8260]
### Describe the issue

When adding a comment for translators in the source POT file as described in the [PO file docu](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html), that comment is not used for that string's translator explanation.
POT files are configured and used, as they are successfully read when adding a language.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Add a translators-comment (line starts with a `# `) for a string in the source POT file
2. Commit to the repo
3. Make sure the file change was detected by Weblate
4. Check the explanation for the same string in Weblate

### Expected behavior

The translators-comment appears as a string explanation in Weblate.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
The explanation is only stored and managed in Weblate. Comments from the file are displayed as "Source string description", see https://hosted.weblate.org/translate/weblate/application/cs/?checksum=39b3998dcfe68cbf for this:

https://github.com/WeblateOrg/weblate/blob/7d5801294b186e81dbf062c1cfe3b10dabae7781/weblate/locale/cs/LC_MESSAGES/django.po#L123-L126

**Comment by SantosSi** [comment]
Thanks, Michal, for the explanation. That was mainly my misunderstanding: I mistook the translator-comments as comments FOR translators.
Additionally, the source Markdown files do not have comments, I am afraid the next run of the command md2po overwrites those manually added extracted-comments (untested).
FYI, your suggestion worked like a charm, thanks again: https://hosted.weblate.org/translate/ospo-zone-ggi/52_activity_22/pt/?checksum=141056b27c966a18

**Comment by SantosSi** [comment]
Running into an incompatibility with md2po, which does not keep `#.` comments intact, as it regards only `#` comments as comments FOR the translator (like I did above). The dilemma of this incompatibility between Weblate and mdpo is that 
- either comments for the translator are in `#`: Weblate does not show them to the translator, but kept intact by md2po runs
- or comments for the translator are in `.#`: Weblate shows them to the translator, but are removed by md2po runs.
See my [issue comment there](https://github.com/mondeja/mdpo/issues/107#issuecomment-1306791017).
I would love to see you communicate directly, making both tools compatible.

**Comment by nijel** [comment]
See https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html:

* `#.` is comment extracted from the source intended for translators, Weblate displays those
* `#` is comment provided by translators, Weblate ignores those

The `md2po` behavior is somewhat expected. I assume it creates POT file from Markdown (which contains no comments) and then calls `msgmerge` to update PO file. It keeps the translator comments, but overrides the extracted comments based on the POT file.
