### ISSUE TITLE
Apply for Gitlab OSS program?

### ISSUE THREAD

**Issue by maxking** [WeblateOrg/weblate#8261]
### Describe the issue

We just got a [Merge Request on Gitlab](https://gitlab.com/mailman/postorius/-/merge_requests/733) from Weblate and realized that it doesn't run the CI anymore due to missing CI minutes on Gitlab Shared Runners.

I don't know if there is a way to run the jobs as a part of destination project's CI, but Gitlab has a OSS program that bumps the total number of allowed CI minutes to much higher limit: https://about.gitlab.com/solutions/open-source/join/ 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Weblate is definitely not eligible there:

> Not seek profit: Your organization can accept donations to sustain its work, but it can’t seek to make a profit by selling services, by charging for enhancements or add-ons, or by other means.

The proper solution to this is not to use a user for this, but have proper integration via app. https://github.com/WeblateOrg/weblate/issues/1688 is related.
