### ISSUE TITLE
Weblate Github Webhooks

### ISSUE THREAD

**Issue by sismithk3** [WeblateOrg/weblate#8269]
### Describe the issue

Hi, We have our setup integrated with Github and making use of the continuous integration with webhooks. However we noticed the changes were not being reflected in weblate, checking the webhook delivery it states a 202 response with the message `{"status": "failure", "message": "No matching repositories found!", "match_status": {"repository_matches": 0, "branch_matches": 0, "enabled_hook_matches": 0}}`
Is there any configuration we need to do to get this to work or how should it match. All components were added through weblate UI with the version control set to use Github, we have the github username and password set in the docker-compose file and can push and pull through the UI without issue.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Docker container

### Weblate versions

* Weblate: 4.3.2
 * Django: 3.1.3
 * siphashc: 2.1
 * Whoosh: 2.7.4
 * translate-toolkit: 3.2.0
 * lxml: 4.6.1
 * Pillow: 8.0.1
 * bleach: 3.2.1
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.1
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.5
 * weblate-language-data: 2020.11
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.19.2
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.11
 * borgbackup: 1.1.14
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.6
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.16.12
 * zeep: 4.0.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.1
 * Mercurial: 5.6
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * Redis server: 4.0.14
 * PostgreSQL server: 11.10
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.sendgrid.net
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.15.0-1098-azure (x86_64)

**Comment by nijel** [comment]
The matching is based on repository URL, more details are available in the log. Maybe not in the version you use, though...

What is the repository URL configured in Weblate? What is sent in the webhook?

**Comment by sismithk3** [comment]
The repository URL is https:///username:access_token@github.com/K3Imagine/TestReqs
In the webhook it sends  `"url": "https://github.com/k3imagine/TestReqs"`
The log shows 
```gunicorn stderr | [2022-10-26 08:00:58,526: INFO/408] received GitHub notification on repository k3imagine/TestReqs.git, URL https://github.com/k3imagine/TestReqs, branch development, 0 matching components, 0 to process, 0 linked
```

**Comment by sismithk3** [comment]
I see a fix has been put in place for this, can i ask how quick we can expect this to be released (specifically in the docker build)

**Comment by nijel** [comment]
Most likely next week.
