### ISSUE TITLE
Update Translation Memory documentation about rebuild, etc.

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#8288]
### Describe the problem

Translation memory management has evolved in recent versions, and the documentation is not reflecting that.

### Describe the solution you'd like

Describe all features of translation memory management within UI, including on the project level. Like the rebuild button!
Introduced via **https://github.com/WeblateOrg/weblate/issues/7347**

**Comment by orangesunny** [comment]
@comradekingu, would you be interested in this?

**Comment by comradekingu** [comment]
I will have a go later. https://docs.weblate.org/en/latest/admin/memory.html#translation-memory
You can assign me to the issue.

**Comment by orangesunny** [comment]
Thank you!

**Comment by comradekingu** [comment]
@orangesunny 
 #8290
