### ISSUE TITLE
Newline symbols (similar to `⤶`) are shifted everywhere

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#8321]
### Describe the issue

Newline symbols (similar to `⤶`) are shifted everywhere.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to a sting whose source contains newline(s)
  Example: https://hosted.weblate.org/translate/weblate/hosted/zh_Hans/?checksum=dea54fc3bc2d2f88#history

### Expected behavior

No offset

### Screenshots

![image](https://user-images.githubusercontent.com/49396421/200509181-432e1689-c9d8-4b38-8101-ab155d0b6871.png)

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 4.14.2

**Comment by nijel** [comment]
Works fine in Firefox, I could reproduce this in Chrome.
