### ISSUE TITLE
Automatic translation from other components breaks on plurals

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#8322]
My experience is as follows: when I automatically translate a component based on my other components, the plural form and singular form are concatenated and saved as the singular form.

![image](https://user-images.githubusercontent.com/521449/200510963-c65b509c-347b-4190-bca4-e38b91d30d36.png)

_Originally posted by @jorrit in https://github.com/WeblateOrg/weblate/issues/8062#issuecomment-1306803594_

**Comment by jorrit** [comment]
Thank you @nijel !
