### ISSUE TITLE
Sorting Glossary Entries - give prio to glossaries from "own" project

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#8332]
### Describe the problem

When using multiple (shared, from other projects) glossaries in a project, it would be nice if those matches from the "original Glossary component belonging to the current project were shown at the top rather than the bottom of somewhere in the middle.

Glossary entries within the project are always better matches and more important than those from other (reference) projects.
 

### Describe the solution you'd like

Move glossary entry matches retrieved from current project Glossary component to top. 
I.e section (1) above section (2) on the screenshot below

### Screenshots

![image](https://user-images.githubusercontent.com/26718215/201089996-b29e5b0d-24ae-47d0-946b-96fec63ad039.png)

**Comment by nijel** [comment]
I'm not really convinced that this would be better in all cases – alphabetic sorting has advantages as well…

**Comment by ilocit** [comment]
The alphabetic sorting should be kept, within each Glossary component.
With glossaries with many entries, this gets really messy and there needs to be a way to prioritize. And the "core glossary component within the project should always prevail above shared ones.
All other matches can be sorted in whatever way (mixed, alphabetically), but the matches from the "core" glossary need to be shown at the top. Really.

**Comment by KadAnna** [comment]
We use a "common" glossary that tries to unify terms across projects and that one I want to give a priority over the project's glossary... so cannot agree with the original suggestion.

**Comment by ilocit** [comment]
Well, @KadAnna, normally Terms on a project level are more specific to the project than any general shared glossaries.
You only add terms to a project glossary when you want to set a different translation for that particular project compared to "general" (for good reason).
Anyhow, what we see here, the use cases are very different, so maybe a general "switch" or "setting" is needed for (shared) Glossaries to prioritize them.

**Comment by nijel** [comment]
But we do have existing solution to order components – https://docs.weblate.org/en/latest/admin/projects.html#priority. It just should be applied to the glossary terms as well.

**Comment by ilocit** [comment]
> But we do have existing solution to order components – https://docs.weblate.org/en/latest/admin/projects.html#priority. It just should be applied to the glossary terms as well.

Sorry, @nijel the suggested solution does not work.
I added two Glossaries to a project, one as Medium one as Very High.
This has no effect on the order in which the entries are being displayed in the Glossary section.

**Comment by nijel** [comment]
It will work in 4.15...

**Comment by ilocit** [comment]
> It will work in 4.15...

Thanks!
