### ISSUE TITLE
po files are not update in time

### ISSUE THREAD

**Issue by yangyangdaji** [WeblateOrg/weblate#8339]
### not found (Browse all string changes) string

> @Geeyun-JY3:Why can’t you just wait for the updates of PO files?
> 

> @yangyangdaji: How often is the PO file update?

> @Geeyun-JY3: It is irregular. It is triggered by @nijel manually

> @yangyangdaji: I get it

po files are not update in time

[search results](https://hosted.weblate.org/search/weblate/?offset=1&q=Browse+all+string+changes&sort_by=-priority%2Cposition&checksum=)

![Screenshot_20221113_191002](https://user-images.githubusercontent.com/108261729/201519168-a2dede44-6f77-4093-851f-989350ae0803.jpg)
![Screenshot_20221113_190354](https://user-images.githubusercontent.com/108261729/201519171-7488941b-aeb0-4446-832f-316ef3de37bd.jpg)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 4.15-dev

# Describe the solution you'd like
maybe use github Actions to auto generate or update po files

**Comment by Geeyun-JY3** [comment]
Why can’t you just wait for the updates of PO files?

This is not the first time you open issue for this similar situation: #8041

**Comment by yangyangdaji** [comment]
@Geeyun-JY3  So when was the string added?

**Comment by yangyangdaji** [comment]
git commit https://github.com/WeblateOrg/weblate/commit/1490d6f79d19653dd608e985e20129e92999c19f

7 days ago

**Comment by yangyangdaji** [comment]
How often is the PO file updated

**Comment by Geeyun-JY3** [comment]
> How often is the PO file update?

It is irregular. It is done by @nijel manually.

**Comment by yangyangdaji** [comment]
> > How often is the PO file update?
> 
> It is irregular. It is done by @nijel manually.

I get it

**Comment by yangyangdaji** [comment]
Maybe use github Actions to auto generate/update po files

**Comment by nijel** [comment]
> But maybe use github Actions to auto generate or update po files

Yes, it would be possible, but that would generate too many changes. There is no need to push every string immediately to translation.

I've done the update now in e960bfba32.
