### ISSUE TITLE
Whitespace placeholder (middle dot) for space is not centered

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#8348]
### Describe the issue

The whitespace placeholder for space (middle dot) is not centered.

IIRC, they are centered before.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to the full editor
2. See the source / second language / diff field

### Expected behavior

Whitespace placeholder (middle dot) for spaces is centered

### Screenshots

Example:
- single space: https://hosted.weblate.org/translate/weblate/documentation/zh_Hans/?checksum=37a744c38a91650e#history
![image](https://user-images.githubusercontent.com/49396421/201823914-495896a5-e478-4fc9-aad4-e93ba0b6a23c.png)
- leading space: https://hosted.weblate.org/translate/po4a/po4a-doc/zh_Hans/?checksum=e01dd695735cf15d
![image](https://user-images.githubusercontent.com/49396421/201824048-69bc3753-9bf7-40ff-ac24-fce9e6350e8b.png)
- ending space: https://hosted.weblate.org/translate/newpipe/glossary/zh_Hans/?checksum=2fb8f253fe55e20e
![image](https://user-images.githubusercontent.com/49396421/201824167-60249823-71f7-4d19-82ab-d03e1928e17f.png)

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 4.15-dev (weblate-4.14.2-81-gd5a83bc217)

**Comment by nijel** [comment]
Might be outcome of df0627b34bbe0ac8153520bd09e57ffc6a759f6a.
