### ISSUE TITLE
Show the source text of the source string as the content of the `New source string` event in the history

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#8350]
### Describe the problem

The content of the `New source string` event in the history is the same as the name of the event.
It can be more useful.

### Describe the solution you'd like

Directly show the source text of the source string as the content of the `New source string` event in the history.

(Just like the `Removed string` event though not all `Removed string` events would show the text of the corresponding string. Another bug?)

### Screenshots

![image](https://user-images.githubusercontent.com/49396421/201832830-e5529648-56aa-4f15-b917-a6e20f1fde80.png)

**Comment by nijel** [comment]
The event is already attached to a string, so it should be pretty easy to add the displaying.

**Comment by d29107d** [comment]
@Geeyun-JY3 
I want to finish this issue.
I am a newbie to weblate.
Can you tell me how to produce the `New source string` event?

**Comment by Geeyun-JY3** [comment]
> I want to finish this issue.
> I am a newbie to weblate.
> Can you tell me how to produce the `New source string` event?

I am not a developer :)
You should @nijel

**Comment by d29107d** [comment]
@Geeyun-JY3 
Actually, I don't know how to produce the `New source string`  history via the website.
What you want to do is directly show the source text of the source string instead of show `New source string`, right?

**Comment by Geeyun-JY3** [comment]
> Actually, I don't know how to produce the `New source string` history via the website. What you want to do is directly show the source text of the source string instead of show `New source string`, right?

Oh I got you.

Go to the changes page at any level. Then choose the `New source string` in the **Action** section of the bottom **Search** filter menu.
Here is an example: https://hosted.weblate.org/changes/?project=&lang=zh_Hans&action=13&user=&start_date=&end_date=

**Comment by d29107d** [comment]
@nijel 
I don't have `New source string` in my local environment, do you know how to produce a `New source string` data?

**Comment by nijel** [comment]
It is generated here:

https://github.com/WeblateOrg/weblate/blob/6ee22e1b19c9a0b9553affce7e41df524134bca2/weblate/trans/models/component.py#L1045-L1047

As mentioned, it already has a unit attached, so this is just a matter of displaying that.
