### ISSUE TITLE
Java MessageFormat check returns a lot of false positives for French

### ISSUE THREAD

**Issue by KadAnna** [WeblateOrg/weblate#8355]
### Describe the issue

French language returns a lot of false positives "Java MessageFormat " Could this be limited? all the French apostrophes are reported as a bug, ... and French uses them a lot.. :) Thanks!

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
Single quotes have to be written as `''`, otherwise they are treated as start of quoting, please see https://docs.oracle.com/javase/7/docs/api/java/text/MessageFormat.html

I've clarified the docs in 3c028a7a2a.
