### ISSUE TITLE
Quick action in suggestion box hide text in RTL languages

### ISSUE THREAD

**Issue by sr258** [WeblateOrg/weblate#8356]
### Describe the issue

If there are suggestion in a RTL language, the quick action ("accept", "accept and edit", "delete", ...) hide the text in the suggestion box: 
![grafik](https://user-images.githubusercontent.com/15268740/202223933-5f935ab6-40b4-4574-8152-27e9431f2e1f.png)

It's not possible to read what's below the actions.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
https://github.com/WeblateOrg/weblate/issues/8259 is somewhat related (it also questions placement of these buttons).
