### ISSUE TITLE
Can the string imported for the first time be set to an incomplete state by default

### ISSUE THREAD

**Issue by GYariza** [WeblateOrg/weblate#8374]
### Describe the issue

Can the string imported for the first time be set to an incomplete state by default？
Because developers will translate some strings themselves, but they are not professional translators, so they need to be reviewed by translators again.
However, when the project is imported for the first time, the strings (translated by developers) are displayed in "Translated strings".

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
Yes, there is an add-on for that: https://docs.weblate.org/en/latest/admin/addons.html#flag-new-translations-as-needs-editing
