### ISSUE TITLE
How to increase REST_FRAMEWORK PAGE_SIZE on Hosted Weblate

### ISSUE THREAD

**Issue by neflyte** [WeblateOrg/weblate#8377]
### Describe the issue

I'm working with a hosted Weblate instance and would like to change the REST_FRAMEWORK PAGE_SIZE setting from 20 to a higher number. Can this change be made in hosted Weblate? If so, how can the chage be made?

I couldn't find any reference to this outside of a settings file that isn't exposed for hosted Weblate instances.

Any assistance is appreciated!

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Use the Weblate API to retrieve a list of data; only 20 records get returned at a time.

### Expected behavior

A way to adjust the PAGE_SIZE setting is available for hosted Weblate instances.

### How do you run Weblate?

weblate.org service

### Weblate versions

Didn't see a way to do this for hosted Weblate.

### Weblate deploy checks

```shell
Using hosted Weblate.
```

**Comment by nijel** [comment]
No, this can be only changed in the configuration file. What is issue in paginating the results?
