### ISSUE TITLE
False postives in checks while source has plural forms

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#8382]
### Describe the issue

It seems that checks are currently applied between each plural form of translation and the first plural form of the source.
It produces many false positives.

Only tested in projects whose source language is English.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to a string whose source has plural forms
2. Enable some checks
3. See the false positive checks

### Expected behavior

There is no false positive on string whose source has plural forms.

I think checks should be applied between each plural form of translation and the corresponding plural form of the source if available.
Not sure if the matching of plural form between source and target language would be complicated.

### Screenshots

Example 1:

- Source language (English): https://hosted.weblate.org/translate/koreader/koreader/en/?checksum=3a041d774ef3f333#translations
  ![image](https://user-images.githubusercontent.com/49396421/203926605-c3de2de0-b57d-4d83-b04b-d4e0b364c097.png)
- Target language 1 (Chinese (Simplified)): https://hosted.weblate.org/translate/koreader/koreader/zh_Hans/?checksum=3a041d774ef3f333#translations
  ![image](https://user-images.githubusercontent.com/49396421/203927107-3ab73aea-e5c7-40b8-bc39-af1cd865ebee.png)
- Target language 2 (Hungarian): https://hosted.weblate.org/translate/koreader/koreader/hu/?checksum=3a041d774ef3f333#translations
  ![image](https://user-images.githubusercontent.com/49396421/203940350-fc94f667-3832-4db3-a538-cba80775a6a3.png)
- Target language 3 (Moldavian): https://hosted.weblate.org/translate/koreader/koreader/ro_MD/?checksum=3a041d774ef3f333#translations
  ![image](https://user-images.githubusercontent.com/49396421/203936872-85013948-6ce4-4a7b-8110-e08ab0a5c677.png)

Example 2:

- Source language (English): https://hosted.weblate.org/translate/liberapay/core/en/?checksum=a947b1502cd1e4d6#translations
  ![image](https://user-images.githubusercontent.com/49396421/203938274-7a98414d-efff-418b-b183-6f7385114ba0.png)
- Target language 1 (Chinese (Simplified)): https://hosted.weblate.org/translate/liberapay/core/zh_Hans/?checksum=a947b1502cd1e4d6#translations
  ![image](https://user-images.githubusercontent.com/49396421/203938758-0a47d9e3-38f0-4375-b6d3-e6044f72cbb1.png)
- For comparison (The check seems to work fine here)
  Target language 2 (French): https://hosted.weblate.org/translate/liberapay/core/fr/?checksum=a947b1502cd1e4d6#translations
  ![image](https://user-images.githubusercontent.com/49396421/203941547-fff47c51-5e39-45be-9296-74d31917bb21.png)

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 4.15-dev (weblate-4.14.2-141-gc035e6ec60)

**Comment by Geeyun-JY3** [comment]
@nijel Is this bug really fixed? https://github.com/WeblateOrg/weblate/commit/883b13a61a45e3274f4ba0845ce48893e4d68471 and https://github.com/WeblateOrg/weblate/commit/6a6f7356369d3ff6c001feb3de04754f589a781f do not seem to fix it.

Examples mentioned in https://github.com/WeblateOrg/weblate/issues/8382#issue-1464241221 still can produce false positives in checks.

Example 1:

The description of the “Things to check” panel is just changed from [“Following format strings are extra: %1”](https://hosted.weblate.org/translate/weblate/application/en/?checksum=635e886cae5aa766) to “[Translation is missing some placeholders](https://hosted.weblate.org/translate/weblate/application/en/?checksum=bd7daf7bf671ec15)”. 
Target language 1, 2 and 3 are the same:

- Target language 1 [Chinese (Simplified)]: https://hosted.weblate.org/translate/koreader/koreader/zh_Hans/?checksum=3a041d774ef3f333#translations
  ![image](https://user-images.githubusercontent.com/49396421/206852600-45c3ba61-857b-4183-9d86-f54d942fe676.png)
- Target language 2 (Hungarian): https://hosted.weblate.org/translate/koreader/koreader/hu/?checksum=3a041d774ef3f333#translations
  ![image](https://user-images.githubusercontent.com/49396421/206852631-a7ce079b-48e6-4f96-929b-f7c12385a054.png)
- Target language 3 (Moldavian): https://hosted.weblate.org/translate/koreader/koreader/ro_MD/?checksum=3a041d774ef3f333#translations
  ![image](https://user-images.githubusercontent.com/49396421/206852534-023f92b6-0fad-4455-b0cb-25e055aa6e35.png)

Example 2: still the same

Target language 1 [Chinese (Simplified)]: https://hosted.weblate.org/translate/liberapay/core/zh_Hans/?checksum=a947b1502cd1e4d6#translations
![image](https://user-images.githubusercontent.com/49396421/206852697-821aebb2-3954-4685-b0e8-8c9a27179af8.png)

***

Weblate versions: Weblate 4.15-dev (weblate-4.14.2-339-g01c5f4c9b7)

**Comment by nijel** [comment]
I don't think these fixes are already deployed, but I will check later...

**Comment by nijel** [comment]
Okay, it is deployed. Existing checks are updated once in a month, so it will take some time until they disappear. I've manually triggered update on https://hosted.weblate.org/translate/koreader/koreader/zh_Hans/?checksum=3a041d774ef3f333#translations and the check disappeared as expected.

**Comment by Geeyun-JY3** [comment]
@nijel Example 2 is still reproducible. It is been several months. Are the existing checks really updated once a month?

**Comment by nijel** [comment]
https://hosted.weblate.org/translate/liberapay/core/zh_Hans/?checksum=a947b1502cd1e4d6 is different – it is caused by "<unused singular (hash=875d02423fb659ec81c96c1ca550c608)>" being the singular. It should be addressed by 462597af6e.

**Comment by Geeyun-JY3** [comment]
The fix works for the Chinese. 
But it produces false positive in checks for some languages which has the same plural forms (plural formula: `n != 1`) as English, while the singular target field is already the same as the source and the plural target field ends with a full stop
All of them have these two failing checks: 

- Mismatched full stop
- XML syntax

Examples:

- https://hosted.weblate.org/translate/liberapay/core/eo/?checksum=a947b1502cd1e4d6
  ![image](https://user-images.githubusercontent.com/49396421/232232848-d1e1a302-8dbf-49cb-b951-46c90bb32a1f.png)
- https://hosted.weblate.org/translate/liberapay/core/de/?checksum=a947b1502cd1e4d6
  ![image](https://user-images.githubusercontent.com/49396421/232232822-e215e617-108f-40d7-b17e-221c2c4e64ba.png)

**Comment by nijel** [comment]
Honestly, all this `<unused singular` thing is hacky. It is a non-standard solution used by liberapay only. Everybody else puts the singular there just for the consistency, even if it unlikely it is being used.

I've fixed the XML check in b36a716bb48379877766d8be248ee67f432b5bb6 because it is not supposed to trigger in such cases (where all source plurals are not valid XML).

Other checks will continue to trigger. Pull request addressing that cleanly (not touching individual checks code) and not hurting performance will be considered.

**Comment by Geeyun-JY3** [comment]
Yeah that `<unused singular` thing is hacky. I just hope that Weblate can properly handle the correspondence of plural forms.

My focus is on the “Mismatched full stop” check while I report https://github.com/WeblateOrg/weblate/issues/8382#issuecomment-1509867059.
So another PR is needed to fix the false positive in the “Mismatched full stop” check?

**Comment by nijel** [comment]
Any check can trigger on this, the solution would have to be generic and implemented in the base class.
