### ISSUE TITLE
Cannot add a language on component

### ISSUE THREAD

**Issue by gasperthegracner** [WeblateOrg/weblate#8395]
### Describe the issue

We cannot add new language to a component.

We are running Weblate via Bitnami image

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to 'Project -> Component'
2. Click on 'Start new translation'
3. Select language
4. confirm

### Expected behavior

"Start new translation" should add new translation to the list

### How do you run Weblate?

Other

### Weblate versions

Weblate-4.14.2-py3.7

**Comment by nijel** [comment]
What happens depends on the configuration: https://docs.weblate.org/en/latest/admin/projects.html#adding-new-translation

**Comment by gasperthegracner** [comment]
> What happens depends on the configuration: https://docs.weblate.org/en/latest/admin/projects.html#adding-new-translation
> 
> In case adding is configured, but does not happen, something useful might be in the logs.

@nijel 
we checked the logs, `en.json` was missing in `/opt/bitnami/weblate/data/vcs/{project}/{component}`, after adding it and setting the right permissions, we manage to solve the issue.

**Comment by nijel** [comment]
I've improved the error reporting for 4.15 in 9255b14e4f7d08273792db514690fabcba8e4f06.
