### ISSUE TITLE
Matching of Java translations with component discovery addons

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#8407]
### Describe the issue

I'm trying to configure the component discovery addons to match Java translations that are using `ApplicationResources.properties` files. I think I entered the right regular expression but Weblate seems to not find any component with it, even if I have quite a lot of them in my repository. 

Here's an example of the source translation file I'm trying to match: https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties
Translations are using ApplicationResources_{{ language }}.properties such as: https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources_fr.properties

I'm using the following regex for matching translations files: 
```
(?P<component>[^/]*)/src/main/resources/ApplicationResources_(?P<language>[^/.]*).properties
```

and using this for the monolingual base filename:
```
{{ component }}/src/main/resources/ApplicationResources.properties
```

I put those information when configuring the discovery addons in https://l10n.xwiki.org/projects/xwiki-platform/xwiki-core-resources/ (see screenshot for configuration of this component), so I'm expecting that it would find at least the original component, but it keeps saying that no component is found. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Screenshots

![image](https://user-images.githubusercontent.com/1478232/205017080-4db47151-ac61-40bd-b83d-1c76d78090e2.png)

### How do you run Weblate?

PyPI module

### Weblate versions

```
* Weblate: 4.12.1
 * Django: 3.2.4
 * siphashc: 1.3
 * translate-toolkit: 3.6.1
 * lxml: 4.6.3
 * Pillow: 9.1.0
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 4.2.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.1
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.6.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 5.1.0
 * kombu: 5.1.0
 * translation-finder: 2.7
 * weblate-language-data: 2021.5
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.38.0
 * diff-match-patch: 20200713
 * requests: 2.27.1
 * django-redis: 4.12.1
 * hiredis: 1.0.1
 * sentry_sdk: 0.15.1
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.8
 * borgbackup: 1.1.13
 * pyparsing: 3.0.8
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.0.12
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.5.2
 * boto3: 1.22.10
 * zeep: 4.1.0
 * aeidon: 1.11
 * iniparse: 0.5
 * Mercurial: 6.1.2
 * git-review: 2.3.1
 * Redis server: 5.0.14
 * PostgreSQL server: 11.14
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.19.0-20-amd64 (x86_64)
```

**Comment by nijel** [comment]
You're trying to match `xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources_fr.properties` with `(?P<component>[^/]*)/src/main/resources/ApplicationResources_(?P<language>[^/.]*).properties`.

That can't work because the component part excludes `/` and it actually is `xwiki-platform-core/xwiki-platform-oldcore`. So either include the prefix in the regexp (in case it is fixed}) or allow `/` there: `(?P<component>.*)/src/main/resources/ApplicationResources_(?P<language>[^/.]*).properties`

**Comment by surli** [comment]
Thanks for the quick answer! 

So actually it's a bit more complex than that: in my case we have a Maven multi-module repository and I want to detect also translations in nested module such as `xwiki-platform-core/parent/child/subchild/module-with-translation` and I want `module-with-translation` to be the name of the my component. 
I did tried to use `.*/(?P<component>[^/]*)/src/main/resources/ApplicationResources_(?P<language>[^/.]*).properties` but I wasn't working. 
At the end I figured that I needed to also capture the whole hierarchy of module for the monolingual base filename, so I ended up with this solution which is finally working: 

Matching regex:
`(?P<originalHierarchy>.+/)(?P<component>[^/]*)/src/main/resources/ApplicationResources_(?P<language>[^/.]*).properties`

Monolingual base filename:
`{{ originalHierarchy }}{{ component }}/src/main/resources/ApplicationResources.properties`
