### ISSUE TITLE
ICU MessageFormat does not recognize placeholders wrapped in `''`

### ISSUE THREAD

**Issue by rob006** [WeblateOrg/weblate#8408]
### Describe the issue

Example: https://weblate.rob006.net/translate/flarum/flarum-tags/es/?checksum=6b8b99fada9d3171

Check complains about missing `title` placeholder, while it is available in translation, just wrapped between `''`.

![5a392495](https://user-images.githubusercontent.com/5972388/205052070-d6f1d7db-b2ef-4926-be2d-bf7a2527c2bf.png)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Git checkout

### Weblate versions

 * Weblate: weblate-4.14.1
 * Django: 4.1.1
 * siphashc: 2.1
 * translate-toolkit: 3.7.3
 * lxml: 4.9.1
 * Pillow: 9.2.0
 * bleach: 5.0.1
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.1.0
 * django-compressor: 4.1
 * djangorestframework: 3.13.1
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.8.0
 * rapidfuzz: 2.10.3
 * openpyxl: 2.6.4
 * celery: 5.2.7
 * kombu: 5.2.3
 * translation-finder: 2.14
 * weblate-language-data: 2022.7
 * html2text: 2020.1.16
 * pycairo: 1.21.0
 * pygobject: 3.42.2
 * diff-match-patch: 20200713
 * requests: 2.28.1
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.9.9
 * Cython: 0.29.32
 * misaka: 2.1.1
 * GitPython: 3.1.27
 * borgbackup: 1.2.2
 * pyparsing: 3.0.9
 * pyahocorasick: 1.4.4
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.1.1
 * Python: 3.8.10
 * Git: 2.25.1
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.24.84
 * zeep: 4.1.0
 * aeidon: 1.11
 * iniparse: 0.5
 * mysqlclient: 2.1.1
 * Redis server: 5.0.7
 * MySQL sever: 8.0.31
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379/0, redis://localhost:6379/0, regular
 * Platform: Linux 5.4.0-132-generic (x86_64)

**Comment by nijel** [comment]
The wrapping in single quote makes it a string literal and not used as placeholder...
