### ISSUE TITLE
Discovery addons proposes to create already existing components

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#8413]
### Describe the issue

I recently configured properly discovery addons for creating components related to Java properties and it's working properly. 
Now in the same repository I have other translation file formats and I'm trying to configure another instance of discovery addons for those, so my first question is:
it is possible to have two different configurations of discovery addons in the same project? It sounds like the UI doesn't prevent me to do it if I try to add the addons from another component, but I don't know if it will work properly afterwards. 

Now I'm opening this ticket because I again don't manage to properly configure the addons: it matches properly the files I want to find, but apparently it matches them as "Components to be created" (see first screenshot) while some of the proposed components to be created definitely already exists (see second screenshot). 

I suspect it to be related to my regular expression for matching, I'm using this expression:
```
(?P<originalHierarchy>.+/)(?P<component>[^/]*)/src/main/resources/(?P<package>([^/]+/)*)(?P<baseFileName>[^/.]*Translations[^/.]*).(?P<language>[^/._]*).xml
```
and the following monolingual filename:
```
{{ originalHierarchy }}{{ component }}/src/main/resources/{{ package }}{{ baseFileName }}.xml
```

as you might notice I have to capture the actual filename because the rule here is that it always contains `Translations` but it can be a suffix or a prefix, or even independent, but it's not a fixed filename. For example, we have a `LikeTranslations.xml` (see related screenshots). So maybe Weblate doesn't properly find the existing components because I'm using an expression here and not a fixed filename? is that possible?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Screenshots

![image](https://user-images.githubusercontent.com/1478232/205250494-5fd7a5ee-8a59-4372-a6ee-5c33d507730c.png)

![image](https://user-images.githubusercontent.com/1478232/205250656-e324cf19-4f85-4738-85b2-9dd2d7d7b0e6.png)

### How do you run Weblate?

PyPI module

### Weblate versions

 * Weblate: 4.12.1
 * Django: 3.2.4
 * siphashc: 1.3
 * translate-toolkit: 3.6.1
 * lxml: 4.6.3
 * Pillow: 9.1.0
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 4.2.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.1
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.6.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 5.1.0
 * kombu: 5.1.0
 * translation-finder: 2.7
 * weblate-language-data: 2021.5
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.38.0
 * diff-match-patch: 20200713
 * requests: 2.27.1
 * django-redis: 4.12.1
 * hiredis: 1.0.1
 * sentry_sdk: 0.15.1
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.8
 * borgbackup: 1.1.13
 * pyparsing: 3.0.8
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.0.12
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.5.2
 * boto3: 1.22.10
 * zeep: 4.1.0
 * aeidon: 1.11
 * iniparse: 0.5
 * Mercurial: 6.1.2
 * git-review: 2.3.1
 * Redis server: 5.0.14
 * PostgreSQL server: 11.14
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.19.0-20-amd64 (x86_64)

**Comment by surli** [comment]
> The matching is based on file mask. You seem to have that one wrong as it does not include {{ originalHierarchy }} (or at least you didn't mention that).

Hmm it does include it, in the addons configuration I put that for the monolingual base filename:
```
{{ originalHierarchy }}{{ component }}/src/main/resources/{{ package }}{{ baseFileName }}.xml
```

and in my already existing Like UI component the corresponding original hierarchy is: `xwiki-platform-core/xwiki-platform-like/` (full path of the mask being `xwiki-platform-core/xwiki-platform-like/xwiki-platform-like-ui/src/main/resources/XWiki/Like/LikeTranslations.*.xml`)

**Comment by nijel** [comment]
Not in the monolingual name, but in the file mask.

**Comment by surli** [comment]
> Not in the monolingual name, but in the file mask.

Sorry I don't follow you. On the addons configuration I have this: 
![image](https://user-images.githubusercontent.com/1478232/205310823-4791ef26-4c0d-4885-8aa2-705e1afe06b1.png)

So you can see that `originalHierarchy` is included in the regular expression of the mask. 
And as I said in my previous answer, in case of the Like UI component example I gave the mask is
`xwiki-platform-core/xwiki-platform-like/xwiki-platform-like-ui/src/main/resources/XWiki/Like/LikeTranslations.*.xml`

So this `originalHierarchy` part of the pattern matches `xwiki-platform-core/xwiki-platform-like/` of this mask.

**Comment by surli** [comment]
> Maybe the other component is using real repository?

Not it's also a component with sharing repository: 
![image](https://user-images.githubusercontent.com/1478232/205315015-d7fbd03c-0a92-48fd-a797-47509e523941.png)

**Comment by nijel** [comment]
Can you please try it with following regexp? (It adds `\` before `.`):

`(?P<originalHierarchy>.+/)(?P<component>[^/]*)/src/main/resources/(?P<package>([^/]+/)*)(?P<baseFileName>[^/.]*Translations[^/.]*)\.(?P<language>[^/._]*).xml`

**Comment by surli** [comment]
Just checked and I'm getting same result. I also tried putting `\` before `.xml` to also escape that one but same result.

**Comment by nijel** [comment]
Your repo is public, right? Can you please share that and configuration of the main component? I will try to reproduce this in my environment.

**Comment by surli** [comment]
Sure, the repo is https://github.com/xwiki/xwiki-platform 
What info do you need / How do you want me to share config of the main component? Here's some screenshot, let me know if it's enough or not for you:
![image](https://user-images.githubusercontent.com/1478232/205330045-19555840-4f7d-4e9c-a90a-7846a0f4ccee.png)
![image](https://user-images.githubusercontent.com/1478232/205330064-d1e17e61-22d0-498c-994e-e78aa2a8d088.png)

Also note that I'm a bit late for upgrading, current version of Weblate we use is 4.12.1

**Comment by nijel** [comment]
Thanks, I will look into that. Meanwhile I've added display of file mask to the preview, so that it is easier to see when it is wrong: d8ac3fb79b5298728f0578f48d2a0962af80e871

**Comment by nijel** [comment]
It works as expected for me.

Maybe the repository linking didn't work well for some reason? Can you try running following?

```
weblate shell -c 'from weblate.trans.models import Component; c = Component.objects.get(slug="like-ui"); print(c.linked_component)'
```

**Comment by nijel** [comment]
Thanks, that looks correct.

**Comment by surli** [comment]
Note that in my case I already have a configured discovery addons (for java properties), I don't know if you took that into account when trying to reproduce, but maybe it has no impact.

**Comment by nijel** [comment]
It should not have any impact.

**Comment by surli** [comment]
I'd like to reopen this issue as I still reproduce the problem after an upgrade to Weblate 4.15.1.

**Comment by nijel** [comment]
The only change is that discovery now lists the component configuration as well. Please verify that whether template and file mask match the existing component.
