### ISSUE TITLE
Change mechanism of finding and showing occurrences

### ISSUE THREAD

**Issue by petrenkonikita112263** [WeblateOrg/weblate#8425]
### Describe the problem

Currently, the mechanism's work is based on the result of the comparison. If there's the exact string or word, then the named section's other occurrences will be displayed with all coincidences in translations.
However, there're some words, "add, delete, edit" & "Add, Delete, Edit" and others that are the same words(and strings), but on the platform, they're not. 

### Describe the solution you'd like

That's why it will be a great simplification if the mechanism of comparing strings is based on capitalized comparisons or lowercase.

**Comment by nijel** [comment]
I'm sorry, but I have no clue what feature you are talking about. Can you please clarify?

**Comment by petrenkonikita112263** [comment]
Let's say you have the word "Add," and you need to translate it into any other language. Somehow you've also had the word "add" which needs to be translated. However, you won't see the word "add" as an occurrence when you're translating the word "Add" only will be words starting with the capital "A". The same works with string, for instance, "welcome to your page" won't be an occurrence for "Welcome to your page".

**Comment by nijel** [comment]
You mean on "Other occurrences" tab? (https://hosted.weblate.org/translate/weblate/application/cs/?checksum=1302f55c88f998e2#others) That one is supposed to show exactly same strings only.

**Comment by petrenkonikita112263** [comment]
Yes, but the current comparison is a disadvantage.

**Comment by nijel** [comment]
If you want close matches, "Automatic suggestions" is the place to find them. "Other occurences" is only shown when there are same strings in the projects.

**Comment by petrenkonikita112263** [comment]
Again, why can an exact string be the string with the same letters but in upper, lower, or capital cases?
