### ISSUE TITLE
Deleting old suggestions after their modifications

### ISSUE THREAD

**Issue by petrenkonikita112263** [WeblateOrg/weblate#8426]
### Describe the issue

At the moment, if the users make some suggestions and decide to edit their suggestion,  it will overwrite the old one

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to any word or string you've planned to translate
2. Translate it and save translations as a suggestion's to this string
3. Click on the pencil icon to update the created suggestions
4. Make any modifications and save it (press Suggest button)
5. It will override the old suggestions and automatically apply translation to the string

### Expected behavior

Instead of overriding the old suggestion, it will create a new one. The first one will still exist. No suggestions won't be applied to the string

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 4.12.1

**Comment by nijel** [comment]
The pencil button is called "Accept and edit", so it does something different than you expect :-).

**Comment by petrenkonikita112263** [comment]
Then what's the purpose of editing suggestions? If it will accept.

**Comment by nijel** [comment]
There was no change in this – there is “accept”, and “accept and edit”. They both accept the suggestion, the first one moves to the next string, the second one stays on the current one for additional edits.

**Comment by nijel** [comment]
Maybe we should reconsider UI style here - the icon like buttons doesn't give enough place to explain the behavior. It has also another issues, see https://github.com/WeblateOrg/weblate/issues/8259
