### ISSUE TITLE
Add notification or section for updated text

### ISSUE THREAD

**Issue by petrenkonikita112263** [WeblateOrg/weblate#8442]
### Describe the problem

There might be situations in which the initial string will be updated. Then if the primary state was translated, the translation would be outdated after modification. Due to that, the translations might need to be clarified. 

### Describe the solution you'd like

As I see it can be done in one of two options:

1. Adding a new section on "String status" for instance, "Updated strings" which will display strings with the updated original text
2. Create a history tab (window) with further notification about the changed strings

**Comment by nijel** [comment]
The strings will be marked as “Needs editing” by Weblate, the change will be visible both in the history and as source string change. You can filter for such changes in the history.

You can see the example here: https://hosted.weblate.org/translate/f-droid/f-droid-metadata/eo/?checksum=502bfece59e1216b#history (this is first thing I've found, and make be hard to read as there are whitespace changes only).

**Comment by petrenkonikita112263** [comment]
@nijel Appreciate your help and clarification. Indeed, starting from the newer version (I don't know from which), the status is "Needs editing" for strings with updated text.
