### ISSUE TITLE
Change the place of the “Commit e-mail” option in Settings

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#8492]
### Describe the problem

**Commit e-mail** is not something about the (public) profile. It would not be shown on the user profile page publicly like the other fields of the `Profile` tab.
This may mislead users and some users may not find this option quickly. The current place of this option is kind of weird.

### Describe the solution you'd like

Considering there is a hint below the **E-mail** form which is placed under the `Account` tab, saying “[Your name and e-mail will appear as commit authorship.](https://hosted.weblate.org/translate/weblate/application/en/?checksum=2218344cf3266b9f)”, I would suggest moving the **Commit e-mail** option from `Profile` tab to `Account` tab.

### Screenshots

![image](https://user-images.githubusercontent.com/49396421/208087036-2983830a-7bf2-49e6-84ea-1f1f4c939517.png)
![image](https://user-images.githubusercontent.com/49396421/208086941-eaf920f0-00a9-465d-b9e9-69e69e4c8509.png)

**Comment by nijel** [comment]
It was placed to public profile as that is publicly shown, but you're right that Account fits better in this case.
