### ISSUE TITLE
Cannot add LinkedIn profile name

### ISSUE THREAD

**Issue by Bushido1** [WeblateOrg/weblate#8498]
### Describe the issue

Hi!

After filling "LinkedIn profile name" at https://translations.documentfoundation.org/accounts/profile/#profile with https://www.linkedin.com/in/olav-m%C3%A4gi-80208b5, I get an error "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.".

Is it because my profile name includes "ä" i.e. "%C3%A4"?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to https://translations.documentfoundation.org/accounts/profile/#profile
2. Scroll down to LinkedIn profile name
3. Fill it with https://www.linkedin.com/in/olav-m%C3%A4gi-80208b58
4. Click on 'Save'
5. See error "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens."

### Expected behavior

No such error

### Screenshots

![pilt](https://user-images.githubusercontent.com/11409601/208196711-39e37884-ae6d-49b2-8ad5-0d6aae065fa6.png)

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Yes, the assumption was that the service allows only ASCII characters there.

**Comment by Kaushik-Iyer** [comment]
Can someone explain what is to be changed where? I want to try to work on this

**Comment by nijel** [comment]
The type of the field probably needs to be changed to something more generic, but some validation will be still needed there:

https://github.com/WeblateOrg/weblate/blob/5498a1ed5597b3308944501a7823115c179a8498/weblate/accounts/models.py#L551-L556

**Comment by Kaushik-Iyer** [comment]
I think I will have to use CharField instead of SlugField, but it has a max character limit of 255 characters

**Comment by nijel** [comment]
Yes, that could do the trick as well.

**Comment by nijel** [comment]
Fixed by https://github.com/WeblateOrg/weblate/pull/8619, thanks!
