### ISSUE TITLE
Automatic translation add-on adds an unnecessary character

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#8501]
### Describe the issue

I have an add-on set up that automatically adds suggestions.  For about 8 days, suggestions added have the following format: ['sample text'] The translation memory contains only text without any extra characters at the beginning and end.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Expected behavior

Suggestions without extra characters.

### Screenshots

![image](https://user-images.githubusercontent.com/39633242/208233371-597226c3-09a4-47b3-94ab-f6acea23251b.png)
![image](https://user-images.githubusercontent.com/39633242/208233381-b0b39940-90ce-48ae-b5c3-74404c9a3fbb.png)

### How do you run Weblate?

Docker container

### Additional context

4.15-dev — a128a915eaec95d96aa9d51b6a32ed36af678514

**Comment by nijel** [comment]
What service do you use for the automatic suggestions?
