### ISSUE TITLE
"other occurrences" incorrect context display

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#8502]
### Describe the issue

Context is displayed incorrectly in the "other occurrences tab".

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to other occurrences tab
2. See error

### Expected behavior

Correct context display (as before).

### Screenshots

![image](https://user-images.githubusercontent.com/39633242/208233899-2dbdee08-9871-49b5-a648-286d0d91e8be.png)

### How do you run Weblate?

Docker container

### Additional context

4.15-dev — a128a915eaec95d96aa9d51b6a32ed36af678514

**Comment by nijel** [comment]
What is wrong on that? There used to be no context display here before.

**Comment by tomkolp** [comment]
the context is vertical

**Comment by nijel** [comment]
Because the screen is too small for that. The text is vertical as well.

**Comment by tomkolp** [comment]
Unfortunately I don't have a screenshot.  The context was horizontal.  I guess you could scroll the screen to the right if something didn't fit.

**Comment by nijel** [comment]
The context was not displayed here before, it was added in 2144cf224044205772ef522ec350427a8d43e2aa.

**Comment by tomkolp** [comment]
That's why I couldn't find screenshots.  Is it possible to better adjust the display of context?  If not, you can close the application.

**Comment by nijel** [comment]
With removed wrapping, the text will need horizontal scrolling:

![image](https://user-images.githubusercontent.com/212189/208399645-46e6852a-eb16-4e52-9f28-2e70aa09e2c4.png)

I have no clue what is better, but we definitely need to be able to wrap context when it's too long.

**Comment by tomkolp** [comment]
Now you have to scroll right anyway.
![image](https://user-images.githubusercontent.com/39633242/208416319-c27cbf49-f918-45f4-b18c-9c1e068b3c69.png)

![image](https://user-images.githubusercontent.com/39633242/208416372-67dfc69e-7cef-4329-bbfd-bc6ab612ae26.png)
