### ISSUE TITLE
healthz route fails in user matching

### ISSUE THREAD

**Issue by nebulade** [WeblateOrg/weblate#8510]
### Describe the issue

When calling the /healthz GET api, it returns 500 with:
```
[2022-12-20 17:01:30,103: ERROR/208] Internal Server Error: /healthz/
Traceback (most recent call last):
  File "/app/code/weblate-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/app/code/weblate-env/lib/python3.10/site-packages/weblate/accounts/middleware.py", line 57, in __call__
    request.user = user = get_user(request)
  File "/app/code/weblate-env/lib/python3.10/site-packages/weblate/accounts/middleware.py", line 42, in get_user
    user = get_anonymous()
  File "/app/code/weblate-env/lib/python3.10/site-packages/weblate/auth/models.py", line 260, in get_anonymous
    return User.objects.select_related("profile").get(
  File "/app/code/weblate-env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
weblate.auth.models.User.DoesNotExist: User matching query does not exist.
[pid: 208|app: 0|req: 2/93] 172.18.0.1 () {34 vars in 440 bytes} [Tue Dec 20 17:01:30 2022] GET /healthz/ => generated 31 bytes in 101 msecs (HTTP/1.1 500) 5 headers in 188 bytes (1 switches on core 0)
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Expected behavior

Return 200 as of https://github.com/WeblateOrg/weblate/blob/main/weblate/trans/views/basic.py#L461

### Exception traceback

```pytb
Internal Server Error: /healthz/
Traceback (most recent call last):
  File "/app/code/weblate-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/app/code/weblate-env/lib/python3.10/site-packages/weblate/accounts/middleware.py", line 57, in __call__
    request.user = user = get_user(request)
  File "/app/code/weblate-env/lib/python3.10/site-packages/weblate/accounts/middleware.py", line 42, in get_user
    user = get_anonymous()
  File "/app/code/weblate-env/lib/python3.10/site-packages/weblate/auth/models.py", line 260, in get_anonymous
    return User.objects.select_related("profile").get(
  File "/app/code/weblate-env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
weblate.auth.models.User.DoesNotExist: User matching query does not exist.
```

### How do you run Weblate?

Other

### Weblate versions

 * Weblate: 4.15
 * Django: 4.1.4
 * siphashc: 2.1
 * translate-toolkit: 3.8.0
 * lxml: 4.9.2
 * Pillow: 9.3.0
 * bleach: 5.0.1
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.2
 * django-compressor: 4.1
 * djangorestframework: 3.14.0
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.8.2
 * rapidfuzz: 2.13.6
 * openpyxl: 3.0.10
 * celery: 5.2.7
 * kombu: 5.2.4
 * translation-finder: 2.14
 * weblate-language-data: 2022.9
 * html2text: 2020.1.16
 * pycairo: 1.23.0
 * pygobject: 3.42.2
 * diff-match-patch: 20200713
 * requests: 2.28.1
 * django-redis: 5.2.0
 * hiredis: 2.1.0
 * sentry_sdk: 1.12.0
 * Cython: 0.29.32
 * misaka: 2.1.1
 * GitPython: 3.1.29
 * borgbackup: 1.2.2
 * pyparsing: 3.0.9
 * pyahocorasick: 1.4.4
 * python-redis-lock: 4.0.0
 * charset-normalizer: 2.1.1
 * Python: 3.10.6
 * Git: 2.34.1
 * psycopg2-binary: 2.9.5
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * boto3: 1.26.31
 * zeep: 4.2.1
 * aeidon: 1.11
 * iniparse: 0.5
 * Mercurial: 6.3.1
 * git-svn: 2.34.1
 * git-review: 2.3.1
 * Redis server: 5.0.7
 * PostgreSQL server: 12.12
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.15.0-197-generic (x86_64)

### Additional context

This is for the Cloudron package.

**Comment by nijel** [comment]
Did you manually remove anonymous user? It will be recreated when running database migrations or via `weblate  setupgroups`.

**Comment by nebulade** [comment]
Thanks for the fast feedback, this is actually for the Cloudron app package and our e2e tests failed on that. Looks like we overlooked adding that init command in the start script. 

I wonder if there are other missing steps by now, our current one looks like https://git.cloudron.io/cloudron/weblate-app/-/blob/master/start.sh 

Is it safe to call `weblate setupgroups` on every restart similar to the db migrate to ensure those groups?

**Comment by nijel** [comment]
There should be no need to call it separately, it is triggered inside `weblate migrate` as well.

**Comment by nebulade** [comment]
Oh actually after taking a closer look now, the initial `weblate migrate` fails midway due to `btree_gin` extension not being whitelisted for non-superusers in Cloudron's postgres server instance. Will try to add that extension for Cloudron apps and report back, but most likely this was the root cause.
