### ISSUE TITLE
weblate loaddata,meet problem.

### ISSUE THREAD

**Issue by yueshanzhang** [WeblateOrg/weblate#8522]
### Describe the issue

https://docs.weblate.org/en/latest/admin/install.html

# Export current data
weblate dumpdata > /tmp/weblate.dump
# Import dump
weblate loaddata /tmp/weblate.dump 

weblate@e3cceeb109e6:/$ weblate loaddata /tmp/weblate.dump 
**CommandError: Problem installing fixture '/tmp/weblate': dump is not a known serialization format.**
weblate@e3cceeb109e6:/$ weblate version
4.1.4

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

Docker container

### Weblate versions

weblate version
4.1.4

**Comment by yueshanzhang** [comment]
![image](https://user-images.githubusercontent.com/116559966/209290142-c5825196-f559-4a87-9c86-60b516e7f8e7.png)

**Comment by nijel** [comment]
What is content of the file?

**Comment by yueshanzhang** [comment]
> 

weblate dumpdata > /tmp/weblate.dump

**Comment by yueshanzhang** [comment]
> What is content of the file?

I am testing full backup and recovery, or full backup and migration.

Data from 'weblate dumpdata > /tmp/weblate.dump' at docker.

[root@lenovo ~]# docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
e3cceeb109e6 weblate/weblate "/app/bin/start runs…" 47 hours ago Up 47 hours (healthy) 0.0.0.0:8008->8080/tcp, :::8008->8080/tcp 05weblate_weblate_1
5e5ef8114a54 redis:6-alpine "docker-entrypoint.s…" 47 hours ago Up 47 hours 6379/tcp 05weblate_cache_1
42f3b6da1f76 postgres:15-alpine "docker-entrypoint.s…" 47 hours ago Up 47 hours 5432/tcp 05weblate_database_1

[root@lenovo ~]# docker exec -it 05weblate_weblate_1 bash
weblate@e3cceeb109e6:/$ weblate dumpdata > /tmp/weblate.dump

**Comment by yueshanzhang** [comment]
Hello Sir.

I am testing full backup and recovery .

Data from command 'weblate dumpdata > /tmp/weblate.dump' at docker.

***@***.*** ~]# docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
e3cceeb109e6 weblate/weblate "/app/bin/start runs…" 05weblate_weblate_1
5e5ef8114a54 redis:6-alpine "docker-entrypoint.s…" 05weblate_cache_1
42f3b6da1f76 postgres:15-alpine "docker-entrypoint.s…" 05weblate_database_1

***@***.*** ~]# docker exec -it 05weblate_weblate_1 bash
***@***.***:/$ weblate dumpdata > /tmp/weblate.dump


在 12/23/22 15:40, Michal Čihař 写道:

**Comment by yueshanzhang** [comment]
> What is content of the file?

 [{"model": "addons.addon", "pk": 136, "fields": {"component": 40, "name": "weblate.cleanup.blank", "configuration": "{}", "state": "{}", "project_scope": false, "repo_scope": false}}, {"model": "addons.addon", "pk": 137, "fields": {"component": 40, "name": "weblate.generate.prefill", "configuration": "{}", "state": "{}", "project_scope": false, "repo_scope": false}}, {"model": "addons.addon", "pk": 138, "fields": {"component": 40, "name": "weblate.discovery.discovery", "configuration": "{\"match\": \"(?P<component>.*)/src/main/res/values[-]*(?P<language>[^/]*)/strings.xml\", \"file_format\": \"aresource\", \"name_template\": \"Android-git: {{ component }}\", \"base_file_template\": \"{{ component }}/src/main/res/values/strings.xml\", \"new_base_template\": \"\", \"intermediate_template\": \"\", \"language_regex\": \"^(.*)$\", \"copy_addons\": true, \"remove\": false, \"confirm\": true, \"preview\": true}", "state": "{}", "project_scope": false, "repo_scope": true}}, {"model": "addons.addon", "pk": 140, "fields": {"component": 43, "name": "weblate.cleanup.blank", "configuration": "{}", "state": "{}", "project_scope": false, "repo_scope": false}}, {"model": "addons.addon", "pk": 141, "fields": {"component": 43, "name": "weblate.generate.prefill", "configuration": "{}", "state": "{}", "project_scope": false, "repo_scope": false}}, {"model": "addons.addon", "pk": 143, "fields": {"component": 41, "name": "weblate.cleanup.blank", "configuration": "{}", "state": "{}", "project_scope": false, "repo_scope": false}}, {"model": "addons.addon", "pk": 144, "fields": {"component": 44, "name": "weblate.cleanup.blank", "configuration": "{}", "state": "{}", "project_scope": false, "repo_scope": false}}, {"model": "addons.addon", "pk": 145, "fields": {"component": 46, "name": "weblate.cleanup.blank", "configuration": "{}", "state": "{}", "project_scope": false, "repo_scope": false}}, {"model": "addons.addon", "pk": 146, "fields": {"component": 41, "name": "weblate.generate.prefill", "configuration": "{}", "state": "{}", "project_scope": false, "repo_scope": false}}, {"model": "addons.addon", "pk": 147, "fields": {"component": 45, "name": "weblate.cleanup.blank", "configuration": "{}", "state": "{}", "project_scope": false, "repo_scope": false}}, {"model": "addons.addon", "pk": 148, "fields": {"component": 44, "name": "weblate.generate.prefill", "configuration": "{}", "state": "{}", "project_scope": false, "repo_scope": false}}, {"model": "addons.addon", "pk": 149, "fields": {"component": 47, "name": "weblate.cleanup.blank", "configuration": "{}", "state": "{}", "project_scope": false, "repo_scope": false}}, {"model": "addons.addon", "pk": 150, "fields": {"component": 45, "name": "weblate.generate.prefill", "configuration": "{}", "state": "{}", "project_scope": false, "repo_scope": false}}, {"model": "addons.addon", "pk": 151, "fields": {"component": 48, "name": "weblate.cleanup.blank", "configuration": "{}", "state": "{}", "project_scope": false, "repo_scope": false}}, {"model": "addons.addon", "pk": 152, "fields": {"component": 46, "name": "weblate.generate.prefill", "configuration": "{}", "state": "{}", "project_scope": false, "repo_scope": false}}, {"model": "addons.addon", "pk": 153, "fields": {"component": 47, "name": "weblate.generate.prefill", "configuration": "{}", "state": "{}", "project_scope": false, "repo_scope": false}}, {"model": "addons.addon", "pk": 154, "fields": {"component": 48, "name": "weblate.generate.prefill", "configuration": "{}", "state": "{}", "project_scope": false, "repo_scope": false}}, {"model": "addons.addon", "pk": 155, "fields": {"component": 49, "name": "weblate.cleanup.blank", "configuration": "{}", "state": "{}", "project_scope": false, "....
 
 Sir, Can you help me?

**Comment by yueshanzhang** [comment]
solved

**Comment by nijel** [comment]
Maybe you could share what was the issue? That would be helpful in case somebody else runs into the same issue...
