### ISSUE TITLE
Android strings show "&" character incorrectly

### ISSUE THREAD

**Issue by epoberezkin** [WeblateOrg/weblate#8525]
### Describe the issue

Android strings should include & character as "&amp;" - weblate UI shows it incorrectly.

A related issue is https://github.com/WeblateOrg/weblate/issues/6490, but for some reason it was "put aside" as narrow - & character is quite common.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Expected behavior

"&amp;" is supported in Android source/target strings.

### How do you run Weblate?

weblate.org service

**Comment by comradekingu** [comment]
Where is "&" shown incorrectly? Can you post a link to an instance of it happening?
