### ISSUE TITLE
Cleanup translation files addon doesn't cleanup everything in one go

### ISSUE THREAD

**Issue by MAGICCC** [WeblateOrg/weblate#8534]
### Describe the issue

Our 'Cleanup translation files' addon recently cleaned the other language files to remove obsolete strings and I saw that it doesn't clean everything in one go. Instead I had to push to GitHub, merge and then the addon would continue

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Let the addon clean the language files
2. Merge and the addon will continue

### Expected behavior

Addon would remove everything in one go.

### Screenshots

https://github.com/mailcow/mailcow-dockerized/commit/55d57c552df09b63095138c6bb7f894070a935f3
https://github.com/mailcow/mailcow-dockerized/commit/24acd4258945fcc5412d372275a886aaba1119b8

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.15
 * Django: 4.1.4
 * siphashc: 2.1
 * translate-toolkit: 3.8.0
 * lxml: 4.9.2
 * Pillow: 9.3.0
 * bleach: 5.0.1
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.2
 * django-compressor: 4.1
 * djangorestframework: 3.14.0
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.8.2
 * rapidfuzz: 2.13.6
 * openpyxl: 3.0.10
 * celery: 5.2.7
 * kombu: 5.2.4
 * translation-finder: 2.14
 * weblate-language-data: 2022.9
 * html2text: 2020.1.16
 * pycairo: 1.23.0
 * pygobject: 3.42.2
 * diff-match-patch: 20200713
 * requests: 2.28.1
 * django-redis: 5.2.0
 * hiredis: 2.1.0
 * sentry_sdk: 1.12.0
 * Cython: 0.29.32
 * misaka: 2.1.1
 * GitPython: 3.1.29
 * borgbackup: 1.2.2
 * pyparsing: 3.0.9
 * pyahocorasick: 1.4.4
 * python-redis-lock: 4.0.0
 * charset-normalizer: 2.1.1
 * Python: 3.11.1
 * Git: 2.30.2
 * psycopg2: 2.9.5
 * psycopg2-binary: 2.9.5
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * boto3: 1.26.31
 * zeep: 4.2.1
 * aeidon: 1.11
 * iniparse: 0.5
 * mysqlclient: 2.1.1
 * Mercurial: 6.3.1
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 6.2.8
 * PostgreSQL server: 13.9
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: hosted.mailcow.de
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.15.0-56-generic (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

WARNINGS:
?: (security.W018) You should not have DEBUG set to True in deployment.
?: (weblate.W040.github) github uses deprecated configuration, please switch to GITHUB_CREDENTIALS
        HINT: https://docs.weblate.org/en/weblate-4.15/vcs.html

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.15/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.15/admin/backup.html

System check identified 4 issues (1 silenced).
```

**Comment by nijel** [comment]
It is supposed to do a full cleanup. What is your component configuration? Any additional add-ons installed?

**Comment by MAGICCC** [comment]
See below for component configuration and additional installed add-ons:
![image](https://user-images.githubusercontent.com/3279213/211150666-1ce838af-19c2-403e-847a-467e2333fa81.png)
![image](https://user-images.githubusercontent.com/3279213/211150682-a3070487-655d-4832-96be-2fc660c9c38c.png)
![image](https://user-images.githubusercontent.com/3279213/211150692-499d85f4-e3bc-4bd4-a546-07c030b51ce3.png)





![image](https://user-images.githubusercontent.com/3279213/211150449-63bb42d7-afa5-4322-acc5-b35f6333263b.png)

**Comment by nijel** [comment]
Hmm, I don't see anything related. And I cannot reproduce the issue locally. Was the setup the same back then when the issue happened? Did you see the issue happenning again?

**Comment by MAGICCC** [comment]
>Was the setup the same back then when the issue happened?
Yes same setup

>Did you see the issue happenning again?
No not yet, and I can't say when it will happen again since deleting source strings are rare. Sorry
