### ISSUE TITLE
Pop-up button text suggestions

### ISSUE THREAD

**Issue by 13663316223** [WeblateOrg/weblate#8542]
### Describe the issue

It is recommended to distinguish "connecte" and "connected" in the pop-up panel, otherwise people will mistakenly think that the button is disabled

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Can you please clarify which pop-up are you talking about?

**Comment by comradekingu** [comment]
@13663316223 
I don't think it says "connecte" anywhere.
https://hosted.weblate.org/languages/en/weblate/search/?offset=1&q=connecte&sort_by=-priority%2Cposition&checksum=

Can you post a screenshot?
