### ISSUE TITLE
'str' object has no attribute 'get' error when updating units via API

### ISSUE THREAD

**Issue by violarulan** [WeblateOrg/weblate#8544]
### Describe the issue

version: 4.15 (docker)

When I try to update a specific unit using the API, it throws the following error:

```
'str' object has no attribute 'get'
/usr/local/lib/python3.11/site-packages/weblate/api/serializers.py, line 1039, in to_internal_value
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

The endpoint is `PATCH /api/units/<my unit id>/` and the payload is `{"state": 10, "target": ["\u52a0\u8fbe\u91cc\u5de5\u4f1a\u65e5"]}`. I use Python requests to send it.

```
    headers = {'Authorization': f"Token {mytoken}", 'Accept': 'application/json'}
    payload = json.dumps({"state": 10, "target": [translation]})
    print(f"--> {payload}")
    update = requests.patch(f"{WEBLATE_API_BASE}units/{unit_id}/", headers=headers, json=payload).json()
    print(f"<-- {update}")
```

The output:

```
--> {"state": 10, "target": ["\u52a0\u8fbe\u91cc\u5de5\u4f1a\u65e5"]}
<-- {'error': 'Server Error (500)'}
```

When I checked the Local Vars part in the Django error output, I noticed the `data` variable is still a `string` rather than dictionary at the very bottom of the traceback.

<html><body>

Variable | Value
-- | --
data | '{"state": 10, "target": ["\\u52a0\\u8fbe\\u91cc\\u5de5\\u4f1a\\u65e5"]}'
is_empty_value | False
self | UnitWriteSerializer(<Unit: [628506] Caldari Union Day>, context={'request': <rest_framework.request.Request: PATCH '/api/units/529344/'>, 'format': None, 'view': <weblate.api.views.UnitViewSet object>}, data='{"state": 10, "target": ["\\u52a0\\u8fbe\\u91cc\\u5de5\\u4f1a\\u65e5"]}', partial=True):     target = PluralField()     state = ChoiceField(choices=((0, 'Empty'), (10, 'Needs editing'), (20, 'Translated'), (30, 'Approved'), (100, 'Read only')), required=False, validators=[<django.core.validators.MinValueValidator object>, <django.core.validators.MaxValueValidator object>])     explanation = CharField(allow_blank=True, help_text='Additional explanation to clarify meaning or usage of the string.', required=False, style={'base_template': 'textarea.html'})     extra_flags = CharField(allow_blank=True, help_text='Additional comma-separated flags to influence Weblate behavior.', label='Translation flags', required=False, style={'base_template': 'textarea.html'}, validators=[<function validate_check_flags>])     labels = LabelsSerializer(many=True)

</body>
</html>

I think that should be problem. 

### How do you run Weblate?

Docker container

### Weblate versions

4.15 (docker)

### Weblate deploy checks

```shell
> docker-compose exec --user weblate weblate weblate check --deploy
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.15/admin/install.html#collecting-errors

System check identified 1 issue (1 silenced).
```

**Comment by nijel** [comment]
> I noticed the data variable is still a string rather than dictionary at the very bottom of the traceback.

Yes, because you are double encoding the payload as JSON. The requests `json` parameter encodes it as JSON. Either do `.patch(json={})` or `.patch(data=json.dumps({})`.

Still Weblate should not crash and report the issue correctly.
