### ISSUE TITLE
Gettext syntax checker

### ISSUE THREAD

**Issue by AnnaArchivist** [WeblateOrg/weblate#8546]
### Describe the problem

In gettext, percentage signs are used for variables, and stray percentage signs can cause errors at runtime. They should be escaped as double percentage signs (`%%`). It's easy to make this mistake. For example, we've seen it in these cases so far:

* Actually want to use a percentage sign, e.g. "5%"
* Percentage sign in URL, e.g. `<a href=\"https://zh.wikipedia.org/wiki/%E5%BD%B1%E5%AD%90%E5%9C%96%E6%9B%B8%E9%A4%A8\">`

In both these cases it crashed our application, and in both these cases double percentage signs should be used.

Additionally, this might be a separate issue, so feel free to split it out and link it, but it feels related: when forgetting to specify a variable type in gettext, it can also cause runtime crashes. E.g. `%(mystring)` instead of `%(mystring)s`.

### Describe the solution you'd like

It would be nice to have a check for invalid gettext syntax, including unescaped percentage signs, and invalid/missing variable types.

Thanks for an amazing tool!

**Comment by AnnaArchivist** [comment]
Oops, I believe this is already implemented in `weblate.checks.format.PythonFormatCheck`? My bad, sorry! Feel free to reopen if it's missing.

**Comment by nijel** [comment]
Yes, with xgettext the strings even get proper flag and everything works automatically:

https://github.com/WeblateOrg/weblate/blob/268436dd60c4719c1e0d4da37efdb3d56478254c/weblate/locale/cs/LC_MESSAGES/django.po#L75-L78
