### ISSUE TITLE
tests fail in 2038

### ISSUE THREAD

**Issue by bmwiedemann** [WeblateOrg/weblate#8556]
### Describe the issue

While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds), I found that
our `weblate` package failed to build in 2038, because a test failed:

```
ERROR: test_upstream_changes_rename (weblate.vcs.tests.test_vcs.VCSHgTest)
weblate.vcs.base.RepositoryException: hg: parse error: date exceeds 32 bits: 2180462939
```

Background:
As part of my work on reproducible builds for openSUSE, I check that software still gives identical build results in the future.
The usual offset is +16 years, because that is how long I expect some software will be used in some places.
This showed up failing tests in our package build.
See https://reproducible-builds.org/ for why this matters.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. on Debian or openSUSE do
2. `osc co openSUSE:Factory/weblate && cd $_`
3. `osc build --vm-type=kvm --noservice --clean --build-opt=--vm-custom-opt="-rtc base=2038-09-04T00:00:00" standard`

### Expected behavior

tests should keep passing in future

### Exception traceback

```pytb
ERROR: test_upstream_changes_rename (weblate.vcs.tests.test_vcs.VCSHgTest)
weblate.vcs.base.RepositoryException: hg: parse error: date exceeds 32 bits: 2180462939
```

### How do you run Weblate?

Other

**Comment by nijel** [comment]
This is an issue in Mercurial: https://www.mercurial-scm.org/repo/hg/file/tip/mercurial/utils/dateutil.py#l300

**Comment by bmwiedemann** [comment]
Thanks for the pointer. I filed https://bz.mercurial-scm.org/show_bug.cgi?id=6778
