### ISSUE TITLE
Add gettext add-on to linked components 

### ISSUE THREAD

**Issue by rsr-cs** [WeblateOrg/weblate#8564]
### Describe the issue

It seems the gettext add-on needs to be installed manualy for each component in a project. For projects with component discovery active it would be very helpful to have the plugin also active for the linked components to e.g. prevent line wrapping in all PO-files of a project.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Install component discovery add-on in a project
2. Install gettext add-on with no line wrapping option on the master component

-> The gettext add-on is only active for the master component 

### Expected behavior

The gettext add-on should be installed for all linked components

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
If you create the components manually, you have to manually install the add-ons as well. For the component discovery there is an option to clone add-ons from the base component.

**Comment by nijel** [comment]
Also, if you want the Gettext add-on configured in all cases, this might be for you: https://docs.weblate.org/en/latest/admin/config.html#default-addons

**Comment by rsr-cs** [comment]
> Also, if you want the Gettext add-on configured in all cases, this might be for you: https://docs.weblate.org/en/latest/admin/config.html#default-addons

This would only apply to newly created components. Is there a chance to add it to exisiting ones? We have a lot of them :-)

**Comment by nijel** [comment]
https://docs.weblate.org/en/latest/api.html#post--api-components-(string-project)-(string-component)-addons- or  https://docs.weblate.org/en/latest/admin/management.html#django-admin-install_addon?
