### ISSUE TITLE
Quick navigation to category totals for components

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#8565]
### Describe the problem

Having to navigate to the language in question, or using the search to get (for example) all unfinished strings for all components in a projects.

### Describe the solution you'd like

Links from the category headers

### Describe alternatives you've considered

A separate entry of totals, but that just gets confusing if there aren't as many, and it uses space.

### Screenshots

From https://hosted.weblate.org/languages/nb_NO/lomiri/
![bilde](https://user-images.githubusercontent.com/13802408/210920222-f5ae0513-6340-48e6-a8ea-84eaaaa713fa.png)

In https://hosted.weblate.org/projects/lomiri/#languages
![bilde](https://user-images.githubusercontent.com/13802408/210920706-b714cd6f-1786-401a-adf7-a97374baac21.png)

https://hosted.weblate.org/zen/lomiri/-/nb_NO/?q=state:%3Ctranslated gives all untranslated and so on.

### Additional context

I suppose the same could be done for all components of all languages in the language view (?).
However, that isn't the problem I am having other than when fixing errors, and it seems resource-intensive to produce such views.

**Comment by nijel** [comment]
These headers are already used for sorting...

**Comment by comradekingu** [comment]
I was thinking:
1. [Clickable link] ▾ as two distinct functions,  (with the ↓)
but that isn't as nice for mobile-users.

It is a loss for sorting to have it be a dropdown menu.

2.  Total number following category, i.e. `Translated` and then 0–999, 1–999 k, or 1–999 m
This is 6 extra chars for each, so no more friendly for mobile-users.

3. A new row underneath the categories to do sorting.
It is sort of there already, but populating it with a ▾  is maybe uglier.
In my head clicking a number opening all instances of said category, means clicking the actual category does the same.

Possible fail is people clicking the category thinking it will do sorting, but I think that is easy enough to learn if so. (?)

**Comment by nijel** [comment]
I don't think it's a good idea to make the table headers links, as that would collide with sorting and that is a common UI pattern.
