### ISSUE TITLE
Allow strings in JSON format to use one JSON key as the ID and another as the translation

### ISSUE THREAD

**Issue by SamWhited** [WeblateOrg/weblate#8576]
### Describe the problem

The JSON formats currently supported by weblate all assume that the JSON looks something like this:

```
{
  "translation key": "translated string"
}
```

However, my JSON looks something like this:

```
{
  "lang": "en-US",
  "messages": [
    {
      "id": "translation key",
      "translation": "translated string"
    }
  ]
}
```

I can mark the `"lang"` key as read only, so there's no trouble there, but each field in messages shows up as a translatable string, ie. `messages[0].id` and `messages[0].translation`. This isn't the end of the world, except that to a non-technical translator it looks as if they should translate "id". If I mark the ID field as read-only it does not get copied into the JSON from the source strings file, so we end up with a broken entry that contains the translation but no ID.

### Describe the solution you'd like

It would be nice if you could specify a field where its value would act as the ID instead of assuming the field name is the ID. Alternatively, Go's `gotext` format from https://pkg.go.dev/golang.org/x/text/cmd/gotext could be supported directly (though it's not widely used and not very well documented, so it may not be ready for native support yet and this could probably be implemented in a generic way anyways).

### Describe alternatives you've considered

Right now I'm just allowing the `id` keys to be translated and requiring review for all translations so that I can tell people not to translate that key.

### Screenshots

![A screenshot of the translation interface, the string in question that has been selected for translation is an "id" that should not be translatable](https://user-images.githubusercontent.com/512573/211174261-e209a41c-e85d-48d9-99f7-786df8354855.png)

**Comment by nijel** [comment]
How is this related to https://docs.weblate.org/en/latest/formats.html#go-i18n-json-files?

**Comment by SamWhited** [comment]
@nijel it's not related, that's a totally different 3rd party thing that's already supported.

**Comment by nijel** [comment]
I'm asking because it has similar layout of the JSON file (with `id` being a hash item as well).

Anyway, the best approach is to add support for this particular format.

**Comment by SamWhited** [comment]
I see, thank you! I don't see an example of that file format, but I was under the impression it just used a flat one. I'll take a look though and file an issue upstream as indicated, thanks again!

**Comment by SamWhited** [comment]
Oops, found translate/translate#4450 so it looks like this issue has already been filed!
