### ISSUE TITLE
locales/en-US.json: invalid literal for int() with base 10: '^'

### ISSUE THREAD

**Issue by SamantazFox** [WeblateOrg/weblate#8618]
### Describe the issue

Since yesterday, we're getting this error every hour.
It's spamming our inboxes (~40 mails every hour) as well as our translation history (see screenshot below)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

I honnestly don't know what triggered this.
We recently added a few translations in the primary file (`en-US.json`) but I don't think this is related, as the character mentionned in the error message is not part of the changes. I tried to manually merge the pending changes then doing a force resync, as well as a reset, but the problem remains.

<details>
<summary><b>Diff file, for reference</b></summary>

```diff
diff --git a/locales/en-US.json b/locales/en-US.json
index 5554b928..12955665 100644
--- a/locales/en-US.json
+++ b/locales/en-US.json
@@ -404,9 +404,7 @@
     "`x` marked it with a ❤": "`x` marked it with a ❤",
     "Audio mode": "Audio mode",
     "Video mode": "Video mode",
-    "Videos": "Videos",
     "Playlists": "Playlists",
-    "Community": "Community",
     "search_filters_title": "Filters",
     "search_filters_date_label": "Upload date",
     "search_filters_date_option_none": "Any date",
@@ -472,5 +470,11 @@
     "crash_page_read_the_faq": "read the <a href=\"`x`\">Frequently Asked Questions (FAQ)</a>",
     "crash_page_search_issue": "searched for <a href=\"`x`\">existing issues on GitHub</a>",
     "crash_page_report_issue": "If none of the above helped, please <a href=\"`x`\">open a new issue on GitHub</a> (preferably in English) and include the following text in your message (do NOT translate that text):",
-    "error_video_not_in_playlist": "The requested video doesn't exist in this playlist. <a href=\"`x`\">Click here for the playlist home page.</a>"
+    "error_video_not_in_playlist": "The requested video doesn't exist in this playlist. <a href=\"`x`\">Click here for the playlist home page.</a>",
+    "channel_tab_videos_label": "Videos",
+    "channel_tab_shorts_label": "Shorts",
+    "channel_tab_streams_label": "Livestreams",
+    "channel_tab_playlists_label": "Playlists",
+    "channel_tab_community_label": "Community",
+    "channel_tab_channels_label": "Channels"
 }
```
</details>

### Expected behavior

Weblate works normally

### Screenshots

![image](https://user-images.githubusercontent.com/52980486/212780082-56eb0177-5539-4327-949b-8fb569d9e624.png)

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 4.15.1-dev

### Additional context

https://hosted.weblate.org/changes/?page=3&limit=20&component=translations&project=invidious

**Comment by nijel** [comment]
Should be fixed by https://github.com/translate/translate/pull/4806

**Comment by TheFrenchGhosty** [comment]
(I'm in the Invidious team, like @SamantazFox )


Just so that you are aware @nijel in the last 48 hours each member of the team received around 2000 e-mails of this error from noreply@weblate.org 


I genuinely feel like you're downplaying this issue, since I'm sure we weren't the only one getting it, and there's a strong possibility that weblate.org is now blacklisted.

**Comment by nijel** [comment]
Can you please clarify how I am downplaying the issue? It has been fixed yesterday, and released and deployed today.

**Comment by TheFrenchGhosty** [comment]
@nijel Yes the bug is fixed (thanks for that) but you didn't mentioned anything about the thousands of e-mails that were sent. Though... I guess this doesn't concern us, as users?

**Comment by nijel** [comment]
Yes, this was a bug that caused sending about 2000 e-mails to five e-mail addresses. I do apologize for that, but unfortunately bugs do happen.

You are really overestimating the impact – you were the only project affected, and the e-mail volume from Hosted Weblate is not really different from the other days.
