### ISSUE TITLE
Broken plurals in i18next v3 files

### ISSUE THREAD

**Issue by SamantazFox** [WeblateOrg/weblate#8625]
### Describe the issue

Weblate tries to push various unexpected changes to i18next v3 files.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Create a project with the following json files

`i18n/en.json`:
```json
{
    "generic_count_years": "{{count}} year",
    "generic_count_years_plural": "{{count}} years",
    "generic_count_months": "{{count}} month",
    "generic_count_months_plural": "{{count}} months"
}
```

`i18n/fa.json`:
```json
{
    "generic_count_years_0": "{{count}} سال",
    "generic_count_months_0": "{{count}} ماه"
}
```

`i18n/id.json`:
```json
{
    "generic_count_years_0": "{{count}} tahun",
    "generic_count_months_0": "{{count}} bulan"
}
```

`i18n/he.json`:
```json
{
}
```

2. Setup a translation project, with file format set to "i18next JSON file v3"

3. Enable "Remove blank strings" add-on
4. Enable "Cleanup translation files" add-on

5. Weblate proposes the following diff:
```diff
diff --git a/i18n/fa.json b/i18n/fa.json
index 0a77c02a..8799acca 100644
--- a/i18n/fa.json
+++ b/i18n/fa.json
@@ -1,4 +1,6 @@
 {
-    "generic_count_years_0": "{{count}} سال",
-    "generic_count_months_0": "{{count}} ماه"
+    "generic_count_years": "{{count}} سال",
+    "generic_count_years_plural": "",
+    "generic_count_months": "{{count}} ماه",
+    "generic_count_months_plural": ""
 }
diff --git a/i18n/id.json b/i18n/id.json
index 72752fd8..2218b10f 100644
--- a/i18n/id.json
+++ b/i18n/id.json
@@ -1,4 +1,4 @@
 {
-    "generic_count_years_0": "{{count}} tahun",
-    "generic_count_months_0": "{{count}} bulan"
+    "generic_count_years": "{{count}} tahun",
+    "generic_count_months": "{{count}} bulan"
 }
diff --git a/i18n/he.json b/i18n/he.json
index 2c63c085..d0a7562a 100644
--- a/i18n/he.json
+++ b/i18n/he.json
@@ -1,2 +1,10 @@
 {
+    "generic_count_years_0": "",
+    "generic_count_years_1": "",
+    "generic_count_years_2": "",
+    "generic_count_years_3": "",
+    "generic_count_months_0": "",
+    "generic_count_months_1": "",
+    "generic_count_months_2": "",
+    "generic_count_months_3": ""
 }
```

### Expected behavior

As per:
https://github.com/i18next/i18next/blob/v22.4.9/src/PluralResolver.js#L15-L16
https://github.com/i18next/i18next/blob/v22.4.9/src/PluralResolver.js#L44

the plural forms in Persian (fa) and Indonesian (id) should always be `<key>_0`.

In addition, the translation file cleaning add-ons should prevent the extra entries from being created in `he.json`.

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 4.15.1-dev

### Additional context

Weblate has worked flawlessly for years, but since we encountered https://github.com/WeblateOrg/weblate/issues/8618 the other, it seems that all of our project decided to break.

I've tried hard resetting / force resync of Weblate, as well as disabling and re-enabling the cleaning add-ons, but none of those actions have impacted the Weblate PR (https://github.com/iv-org/invidious/pull/3575)

**Comment by nijel** [comment]
There are two issues in this:

- the missing `_0` suffix, translate-toolkit omits it in this case, what seems wrong looking at the code, this should be addressed by https://github.com/translate/translate/pull/4811
- different plural counts for some languages - I've created issue for you at https://github.com/translate/translate/issues/4812, once that is fixed, similar fix needs to be done in Weblate

**Comment by nijel** [comment]
After looking deeper, I think the latter is a bug in i18next, please report it there. See https://github.com/translate/translate/issues/4812 for more info.

**Comment by SamantazFox** [comment]
Should I open a new issue regarding the cleanup add-on not cleaning the translation files?

**Comment by nijel** [comment]
Cleanup add-on should remove strings not present in the template. Under some conditions it seems that more runs are needed, see https://github.com/WeblateOrg/weblate/issues/8534

Maybe you're looking for https://docs.weblate.org/en/latest/admin/addons.html#remove-blank-strings instead?

**Comment by SamantazFox** [comment]
> Maybe you're looking for https://docs.weblate.org/en/latest/admin/addons.html#remove-blank-strings instead?

I have both add-ons enabled ("Remove blank strings" and "Cleanup translation files"), but some blank translations remains in various translation files.

**Comment by nijel** [comment]
c28d4983e79891e0f7e46219afd2d6935d442950 should improve that.

**Comment by SamantazFox** [comment]
@nijel Yes, it's working now ^^
