### ISSUE TITLE
enhanced length check

### ISSUE THREAD

**Issue by asoliverez** [WeblateOrg/weblate#864]
we need to add a check for maximum length based on the style used, ie check the length for a specific font and size.
In order to do that, we would add the font, size, and max length as metadata in the source code, and it should be able to calculate if the translated string is the right length.
##

**Comment by nijel** [comment]
What file format do you use? (I ask to see possible options for passing metadata.)

**Comment by asoliverez** [comment]
The source code is mostly C code.
For the style, we use CSS style formatting.
This is GTK+ code, with CSS stylesheets.

I'll check

**Comment by nijel** [comment]
I meant what file format do you use for translations :-).

**Comment by asoliverez** [comment]
Sorry :)
We use gettext .po files

**Comment by asoliverez** [comment]
Do you think this feature is worth implementing? Do you see it as useful for other projects?
Of course I'm open to award a bounty on it, if you think it's upstream-worthy

**Comment by nijel** [comment]
I'm not really sure with font width calculation. It's really hard to do, especially for non latin fonts. Also to make it work Weblate would need the font locally.

Having text lenght limitation would be much easier to implement.

**Comment by asoliverez** [comment]
We could start with text length check while I figure out a way for the font width calculation

El 15 de octubre de 2015 8:09:23 PM GMT+01:00, "Michal Čihař" <notifications@github.com> escribió:
>I'm not really sure with font width calculation. It's really hard to
>do, especially for non latin fonts. Also to make it work Weblate would
>need the font locally.
>
>Having text lenght limitation would be much easier to implement.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/nijel/weblate/issues/864#issuecomment-148491118

-- 
Sent from my mobile device. Please excuse my brevity.

**Comment by asoliverez** [comment]
We do have a way to check font width length, but it's not cross-platform, and as you said, the server should have that font installed.
I'd split this into 3 tasks:
- add the metadata for styles (upstream worthy?)
- add the char length check (upstream worthy)
- add font width length check, based on previous check, we would add a call to a font renderer, and check for actual rendered length. In our case, it would be Pango on a Gnome-based system. This work is probably not worth upstreaming.

I can get someone to work on this next week, but would need some guidance to modify in the right places.

**Comment by nijel** [comment]
As for metadata it should be stored as flag. Currently they are stored [per Unit][0] (as extracted by [get_flags][1] from source file), [Source][2] (can be edited in the source strings UI) or per [Component][3] (defined component wide). There is shared [validate_check_flags][4] to validate  the value in user editable fields. I think in this particular case, it should be something like ``max_length:100``.

For the beginning I'd not care about implementing of parsing this from the source file, it can be added later.

Once you have defined the flag, you can base quality check on it...


[0]:https://github.com/nijel/weblate/blob/master/weblate/trans/models/unit.py#L322
[1]:https://github.com/nijel/weblate/blob/master/weblate/trans/formats.py#L132
[2]:https://github.com/nijel/weblate/blob/master/weblate/trans/models/source.py#L42
[3]:https://github.com/nijel/weblate/blob/master/weblate/trans/models/subproject.py#L330
[4]:https://github.com/nijel/weblate/blob/master/weblate/trans/validators.py#L97

**Comment by nijel** [comment]
Revising this after some time: Do you think it's worth implementing the length based on font rendering?

The current ``max_length:N`` is used quite widely, but I'm not sure about adding another which includes font rendering...

**Comment by nijel** [comment]
Closing as I don't think trying to mimic rendering is going to work properly in general.
