### ISSUE TITLE
Unable to configure Microsoft Translator "Name or service not known"

### ISSUE THREAD

**Issue by alikleit-ns** [WeblateOrg/weblate#8644]
### Describe the issue

I'm getting the following error when setting up Microsoft Translator:

`Failed to fetch supported languages: HTTPSConnectionPool(host='germanywestcentral.https', port=443): Max retries exceeded with url: //api.cognitive.microsofttranslator.com//sts/v1.0/issueToken?Subscription-Key=<my-api-key> (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd05ae7e690>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

I tried the following urls (non-regional):
https://api.cognitive.microsofttranslator.com
https://api.cognitive.microsofttranslator.com/translate?api-version=3.0

and same with the europe region url:
api-eur.cognitive.microsofttranslator.com

region: germanywestcentral

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
Is DNS working correctly on your server? Because `api.cognitive.microsofttranslator.com` resolves just fine for me...

**Comment by alikleit-ns** [comment]
The api resolves perfectly on the test-code that they provide (same credentials), though when we use weblate interface we get that error. However, this is my azure network setup, I tried both locally and on a secure ec2 instance, kept getting the same exception.

** Application Networks
![image](https://user-images.githubusercontent.com/122785904/214539108-21086856-c5c8-4b34-9d43-ddb0598c207f.png)

** Weblate Interface - Exception
![image](https://user-images.githubusercontent.com/122785904/214539503-70555036-576d-40cd-8e4f-e6502b93b60e.png)

**Comment by alikleit-ns** [comment]
I tried with the code sample that they provide, same credential work for me in a C# console application. However, I also tried on Weblate locally and a secure ec2 instance. and getting this exception:

![image](https://user-images.githubusercontent.com/122785904/214540225-d4dbb67d-6383-423c-a74b-c3340ef487e5.png)

All networks are allowed in Azure:
![image](https://user-images.githubusercontent.com/122785904/214540336-f2ecde3a-0396-4def-86f5-804a2f6a79ea.png)

I'm using the latest version of Weblate

**Comment by nijel** [comment]
Looking at their docs and you need to use `api.cognitive.microsoft.com` instead of `api.cognitive.microsofttranslator.com` when using region. Try omitting region, that should work for now.

**Comment by alikleit-ns** [comment]
Thanks! that worked :) though the link in the documentation that they provide is ``

**Comment by nijel** [comment]
Okay, I got confused myself as well `api.cognitive.microsofttranslator.com` is for translating, while `api.cognitive.microsoft.com` is for issuing keys. So, the change I made is wrong and needs to be reverted.

**Comment by nijel** [comment]
I've reworked the form, hopefully it will be less confusing now.
