### ISSUE TITLE
Badge has bad kerning

### ISSUE THREAD

**Issue by bt90** [WeblateOrg/weblate#8651]
### Describe the issue

STRIN GS LAN GUAGES TRAN SLATED

![287x66-grey](https://user-images.githubusercontent.com/1926175/213864471-38692b54-9d54-4c83-b214-6d9f40a65e86.png)

Source: https://hosted.weblate.org/widgets/syncthing/-/287x66-grey.png

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

weblate.org service

**Comment by Geeyun-JY3** [comment]
The kerning is still bad I think.
![image](https://user-images.githubusercontent.com/49396421/232263081-94d51b79-47ef-4031-a116-b02c85eb6c45.png)
Source: https://hosted.weblate.org/widgets/syncthing/-/287x66-grey.png

**Comment by bt90** [comment]
It's much better but there's still room for improvement.
