### ISSUE TITLE
Apple App Store metadata language code style doesn't handle fr-FR code

### ISSUE THREAD

**Issue by rtsisyk** [WeblateOrg/weblate#8652]
### Describe the issue

I use "App store metadata files" format with "Apple App Store metadata style".  My repo has both `fr-FR` and `fr-CA` folders for French (France) and French (Canada), respectively.  

Weblate complains that repo has two folders for French language:

<ul>
        <li>Avoid having translation files for both the plain language 
code and its equivalent territory designation (for example de and 
de_DE).</li>
        </ul>

<p>The following occurrences were found:</p>

Language | Language codes | File names
-- | -- | --
French | fr-FR, fr | iphone/metadata/fr-FR, iphone/metadata/fr

https://hosted.weblate.org/settings/organicmaps/apple-appstore-metadata/

I can see that "Apple App Store metadata style" has correct `fr-FR` code:

https://github.com/WeblateOrg/weblate/blob/1a6108f4cfc1c6e710a1b154154e2a2453590ca5/weblate/formats/base.py#L37

I have tried to delete and re-add French again, but it always adds with `fr` instead of `fr-FR`.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
This is really coming from a way Git handles (or does not handle) directories. "Maintenance"/"Cleanup" in https://hosted.weblate.org/projects/organicmaps/apple-appstore-metadata/#repository will remove those, but it's hard to figure out as these stale directories are not shown on the status...

**Comment by nijel** [comment]
There is currently no way for that (and that could lead to consistency issues, as the force-push could do anything with the files).
