### ISSUE TITLE
Flag to disable "Following fixups were applied to translation: Trailing and leading whitespace"

### ISSUE THREAD

**Issue by Ralim** [WeblateOrg/weblate#8663]
### Describe the problem

For my application a blank line carries meaning; and so blank lines need to be kept in the translations.
To work around this at the moment text has to be awkwardly spread across two lines; or manually patched in git after.

### Describe the solution you'd like

Flag to disable this fixup from occuring; or even better a way to disable it project wide.

### Describe alternatives you've considered

Currently doing workaround of adding padding or a fullstop on a line by itself which looks terrible

**Comment by nijel** [comment]
Ah, there already is a flag for this: https://docs.weblate.org/en/latest/user/checks.html#trailing-and-leading-whitespace-fixer. The documentation was added recently, though: b83bfa53829ba07132d474c3df7b6b30a6add9e6
