### ISSUE TITLE
Hitting the Enter on Android browser won’t jump to the search result listing page

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#8671]
### Describe the issue

Hitting the <kbd>Enter</kbd> on the Android browser won’t jump to the search result listing page. 

Not sure if it is a universal bug on the mobile browsers. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to the `Search` tab at any level
2. Type anything on the top text input bar
3. Hit the <kbd>Enter</kbd>
4. The focus moves to the text input bar of the Advanced query builder

### Expected behavior

Hitting the <kbd>Enter</kbd> then would jump to the search result listing page. It should be consistent with the behavior on the desktop browser.

### Screenshots

https://user-images.githubusercontent.com/49396421/214488644-273eda44-f61e-47e3-9fb2-b3bebfe6aa5d.mp4

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 4.16-dev (weblate-4.15.1-61-gdd9b713455)

### Additional context

Tested with

- Browser: Chrome 109.0.5414.86
- IME: Gboard 12.6.02.491625702-release-arm64-v8a (102451622)

**Comment by Geeyun-JY3** [comment]
I cannot reproduce this now. Tested with Chrome 121.0.6167.164. Is it fixed by Weblate or just a Chrome (Chromium) bug?

**Comment by nijel** [comment]
Most likely it was fixed by changing the input to the textarea and handling Enter manually since 07a737d5ea98a608680bd1bbcd89a3d43389d948.
