### ISSUE TITLE
add support for branch disconnection and branch privileges

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#868]
Weblate currently supports only two modes of operation on branches: connected and separate.

Release management requires to add third mode of operation: Partially connected.

Most of the time, work happens on all branches. But once the branch project enters RC stage, automatic update should be discontinued. Since that moment, person with branch management privileges should have 100% control over incoming strings in the particular branch. Each string that would normally immediately propagate from the master to the branch, will now require review and approval. Until that, the old instance of the string will be kept in the frozen branch.
##

**Comment by stanislav-brabec** [comment]
To be more exact:

It is expected, that in the moment of such freeze, important languages are probably 100% translated.

=> It would be good to fine tune this feature: add string (e. g. to unsupported language) can be done without review, string change in supported language needs review (see also 
https://github.com/nijel/weblate/issues/867).

**Comment by shanewims** [comment]
I would like to add to this: for SLE translation done by our translation vendor, we usually do this in a number of cycles. At a fixed date, we take a snapshot of pot/po files and translate that content for ~16 languages. We know exactly how many words need to be translated, we know the wordcount statistics for each language. Once the translation is complete we submit the translated files. It would not be good for us if the English files were continually updating during a translation cycle. We should to be able to freeze the source strings until a translation cycle is complete.

**Comment by opensuse-i18n** [comment]
shanewims: Code freeze has nothing to do with Weblate. Programmers should be aware of it, and don't add new strings to the frozen repository. If they break string freeze, Weblate can do nothing about it. It just pulls the new string as soon as possible.

Weblate should just support reverse direction freeze: Stop automatic synchronization with master branch at point of the freeze. Since this moment, strings from master branch should become just a suggestion for the frozen branch, and only maintainers of the branch can accept them.

**Comment by shanewims** [comment]
Before code freeze, we need a way to prevent source file updates during a translation cycle, otherwise translators could become confused/frustrated with constantly updating files, and it becomes difficult to track words translated for billing purposes.

**Comment by stanislav-brabec** [comment]
shanewims: It is a big against the spirit of Weblate and it may result in a merge conflict.

But it could be possible with a small code modification:

- To prevent conflicts, developers will be asked to NOT update pot file regularly, just on request. It is easily possible, and standard tools support this work-flow: strings are merged only by "make dist" and "make update-po".

- Small code changes in Weblate would be needed:
  - Being able to disable update hooks for particular sub-project.
  - And optionally being able to disable sending on change per sub-project, not only per-project. It makes sense for multi-lingual batch updates: All translations will be sent in one commit.

**Comment by nijel** [comment]
I think it everything needed is already there:

* You can disable "Allow translation propagation" for components which are "frozen", this way they won't get updates from others (and also will not push updates to others)
* The permissions should be done using Group ACL
