### ISSUE TITLE
Download converted files at component level

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#8680]
Shame you can't export a zip of (for example) CSV files at the component level.  That would be useful.
l.
_Originally posted by @neilbingham in https://github.com/WeblateOrg/weblate/discussions/8666#discussioncomment-4766546_

**Comment by emmapeel2** [comment]
OMG @nijel! I was about to open a ticket for something similar: the possibility of downloading only approved translations for a component with the API. I see they can be downloaded one by one at [projects/{project}/{component}/{language}/#download](https://hosted.weblate.org/projects/tor/tb-torlauncherproperties/es/#download), but I don't find a way to do with a script.

Could you include the customized downloads on this ticket? If not, I can open another ticket.

**Comment by nijel** [comment]
You can do the same using API (per translation) - https://docs.weblate.org/en/latest/api.html#get--api-translations-(string-project)-(string-component)-(string-language)-file-
