### ISSUE TITLE
component.py does not set timeout in WeblateLock

### ISSUE THREAD

**Issue by jorrit** [WeblateOrg/weblate#8682]
### Describe the issue

I'm getting irregular errors like these when I stress the API a little bit on a slightly overloaded system:

The API call is `POST` `translations/project/component/language/file/`.
The response is:
`{"file":"Lock could not be acquired in 1"}`

Should the lock timeout really be the default 1 here? All other calls to the constructor of `WeblateLock` use a timeout of 120.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
The timeout really needs to be way shorter here, but maybe it could be longer than the default 1 second.

But looking at the code I think the locking is no longer needed for the regular upload as it now uses standard translate API and that one does not need locking.

**Comment by jorrit** [comment]
Thanks you for your quick response and changes!
