### ISSUE TITLE
docker: Is it necessary make WEBLATE_SOCIAL_AUTH_GITLAB_SCOPE and WEBLATE_AUTHENTICATION_BACKENDS available as Docker environment variable?

### ISSUE THREAD

**Issue by calbasi** [WeblateOrg/weblate#8689]
### Describe the issue

To enable Gitlab OAuth2 weblate use 5 environment variables:

https://docs.weblate.org/en/latest/admin/auth.html#gitlab-oauth-2

but only 3 of them are available at Docker:

https://docs.weblate.org/en/latest/admin/install/docker.html#gitlab

So I wonder if, like #8132 we need to add the missing 2 as docker environment variables.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.11.2

**Comment by nijel** [comment]
Setting key and secret is all you need in Docker, rest is done automatically:

https://github.com/WeblateOrg/weblate/blob/a249d75fcbf8a2e05ef71284022808e14060077f/weblate/settings_docker.py#L319-L327
