### ISSUE TITLE
WEBLATE LOGIN ISSUE IN LOCALHOST SERVER

### ISSUE THREAD

**Issue by GopiKrishnaPancheti** [WeblateOrg/weblate#8690]
### Describe the issue

We tried to register a user using an email address but the website says we will send an activation link but we didn't got any activation link  in the mail we checked in spam folder also 

This issue is in localhost Weblate server in ubuntu OS

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Try to register user in localhost WEBLATE server. The Activation mail is not coming.

### Expected behavior

Activation mail to be sent to the given email 

### Screenshots

![Screenshot_20230127_112909](https://user-images.githubusercontent.com/123734181/215070475-21963af8-0aea-4d9f-b85c-f529818e50ee.png)

### How do you run Weblate?

PyPI module

**Comment by nijel** [comment]
Is sending mails working on the server? See https://docs.weblate.org/en/latest/admin/install.html#out-mail
