### ISSUE TITLE
Extra commit with wrong author after changing source string

### ISSUE THREAD

**Issue by WofWca** [WeblateOrg/weblate#8691]
### Describe the issue

git history says that I added a string translation, but it wasn't me. I only recently changed the source string.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Make someone else add a translation of several strings.
2. Change the source string (English) of one of the strings translated in step 1.
3. Go to "repository maintenance" and commit pending changes to the Weblate repo.
4. There are now 3 commits (recent-to-older order):
  * A commit authored by me, where I supposedly add the translation of the string from step 2 (e.g. https://github.com/WofWca/jumpcutter/commit/00d381d6cf6f4d2fd592f3555564a1fc3a1edf5c).
  * A commit authored by the person from step 1, which adds the strings from step 1, except the string from step 2 (e.g. https://github.com/WofWca/jumpcutter/commit/9cc03d220c50c0a01542355c17107919e4efb139).
  * A commit authored by me where I change the source string (e.g. https://github.com/WofWca/jumpcutter/commit/53089cc6d06be7415df332ef492cedeea2d74213)

<details><summary>`git log` output</summary>

```diff
00d381d Translated using Weblate (Polish)
diff --git a/pl/messages.json b/pl/messages.json
index 4b3a88b..ec9343e 100644
--- a/pl/messages.json
+++ b/pl/messages.json
@@ -34,5 +34,8 @@
        },
        "openLocalFile": {
                "message": "otwórz lokalny plik"
+       },
+       "soundedSpeed": {
+               "message": "Prędkość dźwięku"
        }
 }
9cc03d2 Translated using Weblate (Polish)
diff --git a/pl/messages.json b/pl/messages.json
index 314d29c..4b3a88b 100644
--- a/pl/messages.json
+++ b/pl/messages.json
@@ -4,5 +4,35 @@
        },
        "extensionDescription": {
                "message": "Oglądaj wykłady ~1,5x szybciej dzięki szybkiemu przewijaniu długich przerw miedzy zdaniami"
+       },
+       "enable": {
+               "message": "Włacz"
+       },
+       "resetToDefaults": {
+               "message": "Przywróć domyślne ustawienia"
+       },
+       "noSuitableElement": {
+               "message": "Nie znaleziono odpowiedniego elementu multimedialnego na stronie"
+       },
+       "silenceSpeed": {
+               "message": "Prędkość ciszy"
+       },
+       "relativeToSounded": {
+               "message": "w odniesieniu do prędkości dźwięku"
+       },
+       "absolute": {
+               "message": "bezwzględna"
+       },
+       "fileInputLabel": {
+               "message": "Przeciągnij plik / pliki\nalbo naciśnij tutaj aby wybrać"
+       },
+       "useExperimentalAlgorithm": {
+               "message": "Użyj eksperymentalnego algorytmu"
+       },
+       "contentScriptFail": {
+               "message": "Nie udało się uruchomić skryptu na tej stronie"
+       },
+       "openLocalFile": {
+               "message": "otwórz lokalny plik"
        }
 }
53089cc Translated using Weblate (English)
diff --git a/en/messages.json b/en/messages.json
index c9e5ba4..42da6c0 100644
--- a/en/messages.json
+++ b/en/messages.json
@@ -138,7 +138,7 @@
                "message": "When the current audio volume is below this value, speed up.\nOn the chart, this is the red 🟥 horizontal line. The blue 🟦 line is the current volume, so when the blue line is below the red,   it is considered to  silence."
        },
        "soundedSpeed": {
-               "message": "Sounded speed"
+               "message": "Regular speed"
        },
        "soundedSpeedTooltip": {
                "message": "The speed at which we play the video when it's currently NOT silent, the \"normal\" speed.\nOn the chart, the parts that were played at this speed have green 🟩 background."
8b6359c Translated using Weblate (Russian)
```

</details>

### Expected behavior

There's no that latest commit, and its change is squashed in the previous one.

### Screenshots

History of the string:

![image](https://user-images.githubusercontent.com/39462442/215265118-075155a2-21a1-4b72-acc9-cf5ee135d768.png)

### How do you run Weblate?

weblate.org service

### Weblate versions

weblate-4.15.2-111-g42190855d3

**Comment by nijel** [comment]
Commit pending is missing on translations when changing the source string, should be fixed.
