### ISSUE TITLE
Inconsistent "copy" "clone" button naming

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#8708]
### Describe the issue

Go to "Automatic/machine translations" in regular mode
https://l10n.elementary.io/translate/website/press/nb/?q=state%3A%3Ctranslated#machinery

Pressing "Copy and save" there (regular view) does what "Clone" does in Zen mode.
(Pressing "Copy" in Zen mode just copies text, and "Clone" makes it the current translation)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Click "Copy" from the regular view for automatic translations and Zen editor.
Notice different results.

### Expected behavior

Icons from Zen used, with the colours as they are now. (Not sure what the colours do though).

Just "Copy"  and "Save", (as that is what is used for the regular mode)?

I think calling it "Clone" both places (or using the icon) makes sense.
If OTOH "Copy" should copy it over, "Clone to translation" should have a different name?

The button-colours in the regular mode are great. Maybe they could be re-used for Zen?
![bilde](https://user-images.githubusercontent.com/13802408/215893644-a54604d5-8cbb-43b5-92d0-2ebd53b29c5b.png)

There are icons for "Suggest" and "Skip" in the regular editor, but nothing for "Save and continue" and "Save and stay".

There were some complaints that this is long and cumbersome. In my head just "Save" should be the button before "Save and continue".

The kingu solution is to just use fixed width buttons with the icons and no text, and then have the text in a mouseover,
and a new button for suggest and continue.)

💾 | 💾⏩  |🯄 | 🯄⏩ | ⏩ |
(Save | save and continue | suggest | Suggest and continue | Continue )

The compromise is to just have "Save" "Save and continue", etc. where everything has icons. (save some, and use a bit more for the icons).

### Screenshots

![bilde](https://user-images.githubusercontent.com/13802408/215894028-c2615298-0ea3-4c2a-b793-e91dc66bb200.png)

### How do you run Weblate?

weblate.org service

### Weblate versions

4.14.2

### Additional context

Curiously, "Copy and save" (in the regular mode/automatic translation view) doesn't actually do any copying to the clipboard.

**Comment by nijel** [comment]
“Copy” should be used for copying to the clipboard. I am uncertain whether “Clone” is the right word to use in automatic suggestions. Maybe “Apply” is better?
