### ISSUE TITLE
Ability to override inherited max-length flag

### ISSUE THREAD

**Issue by rtsisyk** [WeblateOrg/weblate#8712]
### Describe the problem

I use "App store metadata files" format to translate [F-Droid metadata](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/).

F-Droid supports up to 50 characters in `title.txt` while Google Play supports just 30. Currently the format implicitly adds `max-length:30` to `title.txt` flags. I added explicitly `max-length:50` to flags, but it looks like that implicitly inherited flags have higher priority. 

<img width="631" alt="image" src="https://user-images.githubusercontent.com/1799054/215974375-ebecd626-631e-4fae-91e9-43df48aebd60.png">

<img width="465" alt="image" src="https://user-images.githubusercontent.com/1799054/215975918-182c4ddc-1d97-47a7-9d99-75e9725e810e.png">

<img width="107" alt="image" src="https://user-images.githubusercontent.com/1799054/215975958-0a116568-ebff-4104-94f7-cedb078f8e3b.png">

### Describe the solution you'd like

Explicilty-configured flags should have higher priority.

### Additional context

https://hosted.weblate.org/translate/organicmaps/fdroid-metadata

**Comment by nijel** [comment]
No, it's not deployed yet.
