### ISSUE TITLE
Performing the `has:plural` lookup is quite slow

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#8719]
### Describe the issue

It takes quite a long time to perform the `has:plural` lookup at the language of a project level.
I cannot even load the page while performing the `has:plural` lookup at the project level and the language of an instance level.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to search tab of a language of a project / a project / a language of an instance 
2. Enter `has:plural`
3. Click on the `Search` button
4. Cannot load the page

### Expected behavior

Everyone can open the corresponding page.

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 4.16-dev (weblate-4.15.2-209-gde41682274)

### Additional context

Example:

- It takes a long time to open https://hosted.weblate.org/languages/zh_Hans/weblate/search/?offset=1&q=has%3Aplural&sort_by=num_words&checksum=
- I cannot open https://hosted.weblate.org/search/weblate/?offset=&q=has%3Aplural&sort_by=-priority%2Cposition&checksum= and https://hosted.weblate.org/languages/zh_Hans/-/search/?offset=&q=+has%3Aplural&sort_by=-priority%2Cposition&checksum=

**Comment by nijel** [comment]
Confirmed on my test instance as well. Most likely this was caused by 50c5258dcac380db4d773edbfd6f138cb4bb05ff - the pg_trgm is great for text search, but performs poorly on whitespace search (what `has:plural` translates to) as it has to recheck every string. We need to have a fallback operator for whitespace only searches here...

**Comment by Geeyun-JY3** [comment]
@nijel Performing a `source:r"(^|\W)ID(\W|$)"` lookup in the same level is quite slow too. Is it a similar bug?

**Comment by nijel** [comment]
Probably yes, though this one should not be that bad...

**Comment by Geeyun-JY3** [comment]
My primary use case is searching at the language of a project level. It still takes me several minutes to load the results listing page. I think this is unacceptable. 
While using this regular expression, it seems that if the specific word I want to search is less than three letters, performing this lookup would be quite slow. 
Should I open an issue for it?

**Comment by nijel** [comment]
Yes, the string length is the key here (or actually the length of the alphanumeric part of the string). Unfortunately, getting that info from regular expression is not that straightforward, but I will look into options…

Weblate uses PostgreSQL trigram index to optimize these. They work great for 3+ alphanumeric chars, but horribly for shorter ones. Unfortunately, the PostgreSQL optimizer doesn't deal with this, and we work around this in Weblate for the strings by adding string concatenation to the field when the string is too short and would perform badly. Adding operation on the field stops PostgreSQL from using index, and resorts to full table scan, which is faster in this case.

**Comment by nijel** [comment]
https://github.com/WeblateOrg/weblate/pull/8840 should address this.
