### ISSUE TITLE
Show all plural forms of the source string in the source field of the editor, regardless of the plural forms of the target language

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#8722]
### Describe the problem

Not all plural forms of source language will be shown in the editor. It depends on the plural forms of the target language. Sometimes the hidden plural form(s) may have some extra information for translators.

### Describe the solution you'd like

Show all plural forms of the source string in the source field of the editor, regardless of the plural forms of the target language

### Screenshots

Example: while the source language is English and the target language is Chinese (Simplified), the singular form of the source string would not be shown.
![image](https://user-images.githubusercontent.com/49396421/216081178-942233bb-105d-414f-aff4-cfbd2ab1d294.png)

### Additional context

Crowdin would show all plural forms of the source string:
![image](https://user-images.githubusercontent.com/49396421/216079890-e1945223-7a4b-43d3-824a-536f76095e9a.png)

Transifex too, but in a different way which translators need to toggle the plural forms manually:
![image](https://user-images.githubusercontent.com/49396421/216079672-e1581639-8831-4a3f-bcfe-073953240de8.png)

**Comment by nijel** [comment]
It was intentionally changed this way in a2124648a7314c23ee886fc962018dd8b048737c, see #680

**Comment by Geeyun-JY3** [comment]
Sometimes the source text is not good enough, which would may make the translation wrong in some corner cases. And

Maybe Weblate can add an option letting users decide whether to show all plural forms of the source string?
Or adding a button to toggle the appearance of all hidden plural form(s) of the source string (inspired by Transifex)? Users can temporarily see all plural forms of the source string.

**Comment by Geeyun-JY3** [comment]
I think it is necessary to show directly which plural form(s) need to be translated for the current target language, and the fact that the source string has multiple plural forms while translators of the current target language do not need to translate some of them.
