### ISSUE TITLE
Perform project backup upon removal

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#8723]
### Describe the problem

When billing trial expires or is not paid, the project is removed. It would be useful to have a project backup in place so that it can be recovered.

### Describe the solution you'd like

Create project backup before the project is removed.

**Comment by comradekingu** [comment]
(If considering UI options).
Similarly, **for accidentally nuked projects** the "purge local repo" option in #repository could have an entry under "source code status" -saying  "deleted" from where it can be recovered within 14 days.
https://hosted.weblate.org/projects/remmina/remmina/nb_NO/#repository as an example.
Then a "Yes I really want to not be able to recover this" option, if the idea is to reclaim storage space or get rid of the data before 14 days.

**For lapsed Libre projects**, an e-mail saying "You have to recover your translation if you want to use it, and then fix issues or get a different plan." for the first one, and then a grayed out option and "send a message" for the second overshot deadline.

**For lapsed invoices**,
functionally I think "recover" could be grayed out, with a link to the invoice page. https://hosted.weblate.org/billing/

**Comment by nijel** [comment]
I'm not considering UI options right now. Requests to recover projects are rare. So far, these were only connected to automated removal from trial or not paid billings, so simple project backup done at removal time will cover this without extra effort UI would need.
