### ISSUE TITLE
Machine translation is not working

### ISSUE THREAD

**Issue by buddha2042** [WeblateOrg/weblate#8724]
### Describe the issue

I have setup multiple languages using weblate v3.7.1 integration which is working fine. However, I cannot setup automatic translation for any words or langauge. According to docs, third party services like google translate need to be setup for this purpose. But, I couldn't find those options in weblate setting.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

This is just help for my settings in my account. I don't think think it's a bug. Any immidiate help would be much appreciated.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Please read the documentation for instructions how to configure machine translation services: https://docs.weblate.org/en/weblate-3.7.1/admin/machine.html

This has been recently changed to use UI, so upgrading will make it easier for you.

**Comment by nijel** [comment]
It should be commented out in the example configuration, but you can add it if it's not there...

**Comment by nijel** [comment]
https://docs.weblate.org/en/weblate-3.7.1/admin/sample.html

**Comment by nijel** [comment]
Just upgrade to recent version where you can do this in the user interface. Please see https://weblate.org/support/ for professional support options.
