### ISSUE TITLE
[question] Is it possible to prevent translated/approved XML tags appearing in XLIFF translations?

### ISSUE THREAD

**Issue by epoberezkin** [WeblateOrg/weblate#8731]
### Describe the issue

We are using export/import localisations in iOS apps, so that the translated files are XLIFF - these tags create additional diff on export (Xcode removes them).

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Simply commit any iOS translations

### Expected behavior

Some setting to avoid adding translated/approved tags to XLIFF files

### How do you run Weblate?

weblate.org service

**Comment by epoberezkin** [comment]
right, so can we somehow prevent weblate from tracking these strings as exporting XLIFFs from Xcode overrides them... Not sure, maybe a better solution is to translate "Localised" files directly, without XLIFF import/export?

**Comment by epoberezkin** [comment]
How would weblate track strings state if Localized  files are used?

**Comment by nijel** [comment]
Many formats do not store state at all, in that case it is stored in the Weblate database only. But for formats which do support it, it is exposed.
