### ISSUE TITLE
"Has been translated" and "Long untranslated" checks failing for approved source strings

### ISSUE THREAD

**Issue by WofWca** [WeblateOrg/weblate#8739]
### Describe the issue

"Has been translated": for some of the strings (like [this](https://hosted.weblate.org/translate/jump-cutter/extension-ui/en/?checksum=e358533698b9954c)) the check is failing for all the languages to which it has never been translated.
"Long untranslated": the check appeared for [this string](https://hosted.weblate.org/translate/jump-cutter/extension-ui/en/?checksum=828acfb279cd2675) after I changed it, then later approved.

Affects 6 out of 130 strings.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Not sure yet, probably has to do with the fact that the approval is enabled for the source language.

### Expected behavior

The strings don't have such warnings.

### Screenshots

![image](https://user-images.githubusercontent.com/39462442/216658894-14a9e97b-0f88-4d63-b863-5955cdb1413b.png)
![image](https://user-images.githubusercontent.com/39462442/216659189-9f6976b1-ad1d-4942-ae56-c19885ad3871.png)

![image](https://user-images.githubusercontent.com/39462442/216659312-b79d2df2-9d65-422f-b2ee-b32d4ab09eaf.png)

### How do you run Weblate?

weblate.org service

### Weblate versions

weblate-4.15.2-243-gf190eef292

### Additional context

Related: #5107

**Comment by nijel** [comment]
https://hosted.weblate.org/translate/jump-cutter/extension-ui/cs/?checksum=e358533698b9954c#history seems like a bug, probably some history entries are misdetected, I will take a look at that.

Long untranslated seems valid for https://hosted.weblate.org/translate/jump-cutter/extension-ui/en/?checksum=828acfb279cd2675#translations, it might be just a coincidence that it was triggered after you edited it.
