### ISSUE TITLE
merge conflict that cannot be locally reproduced

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#8755]
### Describe the issue

In https://hosted.weblate.org/projects/f-droid/website/, it says there is a merge conflict.  I cannot reproduce it locally.  I do:

```bash
git fetch weblate
git checkout -b w weblate/master
git rebase master
```

And it rebases fine every time.  I also tried including the commits that Weblate say conflict, e.g. `11e2219ed`.  But it still says there is a merge conflict.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. https://hosted.weblate.org/projects/f-droid/website/#repository
2. click on Update -> Rebase
3. Wait for it to finish
4. See merge conflict

```
error: could not apply 11e2219ed... Translated using Weblate: Hebrew (he) by Yaron Shahrabani <sh.yaron@gmail.com>
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 11e2219ed... Translated using Weblate: Hebrew (he) by Yaron Shahrabani <sh.yaron@gmail.com>
Auto-merging po/_posts.he.po
CONFLICT (content): Merge conflict in po/_posts.he.po
```

### Expected behavior

If there is no merge conflict locally, I can't see why there is one in Weblate.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
I can still reproduce this on the server. Do you have some git configuration (`~/.gitconfig`) which might affect this?

For some reason, git doesn't recognize d7fca0ded34e60836b51c84479d2774ec73249bd (which is already in upstream repo) to be a cherry-pick of 11e2219ed7fcc519f3086640926bd7b1043c5529, and stops on that, even though there is actual conflict.

I've just manually fixed that in the Weblate repo...

**Comment by eighthave** [comment]
I don't think my git config should affect it.  Here's my _~/.gitconfig_:

```toml
[pull]
	ff = only
[transfer]
	fsckObjects = true
[advice]
	skippedCherryPicks = false
```

And the relevant bits in the repo's _.git/config_:

```toml
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
```

**Comment by eighthave** [comment]
I'm using _git_ v2.39.1 from Debian/bookworm.

**Comment by nijel** [comment]
We're on git 2.30.2, that might cause some differences... Will try to play with this more later.

**Comment by nijel** [comment]
It turns out that the Weblate git configuration is guilty here – the merge driver for PO files didn't gracefully handle this.

**Comment by nijel** [comment]
@rtsisyk That's not related to this issue. Moreover, I think Weblate behaves correctly – you ask it to not wrap lines, and it does not wrap them.
