### ISSUE TITLE
Inconsistency between views for stated license

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#8789]
### Describe the issue

https://hosted.weblate.org/projects/ultrasonic/#information has a little graphic saying `GPL-3.0`
as does
https://hosted.weblate.org/projects/ultrasonic/#components and
https://hosted.weblate.org/projects/ultrasonic/app/

but not
https://hosted.weblate.org/projects/ultrasonic/app/#information or
https://hosted.weblate.org/projects/ultrasonic/app/nb_NO/#information
where it is written out in full `GNU General Public License v3.0 or later`

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to the different links above
2. Expect the same way to display the license between all of them
3. Find it is not the case

### Expected behavior

Expected it to be the little textbox graphic everywere.

### Screenshots

![bilde](https://user-images.githubusercontent.com/13802408/218358037-d0fee034-735b-465e-9b1a-e88c717f07b8.png)
vs
![bilde](https://user-images.githubusercontent.com/13802408/218357919-166c9764-7b8b-4839-928d-3016f9e13b38.png)

### How do you run Weblate?

weblate.org service

### Additional context

The field is gray in
https://hosted.weblate.org/projects/ultrasonic/#information
vs white in
https://hosted.weblate.org/projects/ultrasonic/app/#information

and it is field number 3 vs nr 4.

It would be nice if all fields were white, and the license field was always nr. 3.

**Comment by nijel** [comment]
The badges at project level are intentionally simplified:

https://github.com/WeblateOrg/weblate/blob/bc9b6d1d33606a884855288ec7f5aac32e415a85/weblate/trans/models/component.py#L3360-L3363

**Comment by nijel** [comment]
The bot closed the issue because nobody bothered to respond. That's exactly it's purpose. There is no point in keeping open issues where nobody is interested in them.

The problem here is that UI space is limited and we want to give users glance at used license. This is really not a legal document to involve lawyers. In that case it might be just better to remove this badge from listing.

**Comment by nijel** [comment]
> Then make your statement about the issue and close it on your own. Using a bot indicates that even the maintainers not interested in anything. It gives the expression the project is unhealthy which itself drive potential new contributors away. If you are not able to handle issue closing on your own then why would be able to mentoring new contributors?!

We have better things to do than monitoring which issues got stale. The bot is way better in this than we would be. There are quite some issues where people come, we ask for clarification, and they never come back. And there is no point in keeping such issues open. If you are willing to go through open issues where clarification is needed and nobody bothered to answer and handle them manually, I can “kill that bot”.

But back to the issue. Let's reopen this and look into the options we have. I've just also noticed that the licenses summary discussed in the initial post on the project page is no longer shown, as 32f7489e81de1e28acb0c940371ab275a55ecbf6 unintentionally dropped passing list of licenses to the template.

**Comment by nijel** [comment]
This is really off-topic here, let's discuss this at https://github.com/WeblateOrg/weblate/discussions/12848.

**Comment by comradekingu** [comment]
Back to report having the licenses on the project serves the purpose of knowing everything is good at a glance (with the mouseover). Especially for projects with many components, not having to click into each one to look at respective info tabs makes sense.

I know it is in https://hosted.weblate.org/accounts/profile/#licenses too, but that isn't a very obvious place to look.

Doing this sort of compliance work manually becomes more-so important when the initial issue arises from GPLv*-_only_ being too easy to select by mistake.
I know the code looks sleek, but in practice there is just the wrong license selected all the time.
Also no warning for selecting a license that isn't in use on the instance altogether.

Top 10 licenses used selectable from a short list above the rest?
Warning for "only".
Consistent use of icons, never spelled out, and with the "or later/only".

Would really cut down on problems.

Ideally just auto-select the license in the repo pointed to, and go with "or later" if nothing else is known.
