### ISSUE TITLE
The pagination component in the changes page is abnormal

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#8799]
### Describe the issue

The pagination component in the changes page is abnormal.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to the changes page
2. Scroll down to the bottom
3. Click on the pagination component
4. See the error

### Expected behavior

The pagination component works fine in the changes page.

### Screenshots

![image](https://user-images.githubusercontent.com/49396421/218607137-6307010f-ac66-4fe4-adc0-dd6ef039a0dc.png)

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 4.16-dev (weblate-4.15.2-401-gc1c1531596)

**Comment by Geeyun-JY3** [comment]
Still reproducible in Weblate 4.16-rc (weblate-4.15.2-685-g68a0661f58)
![(8KI_4%_48HCY(`$BHIJHHQ](https://user-images.githubusercontent.com/49396421/221908632-f0adccc8-c93e-41af-83ee-278f4c22687d.png)

**Comment by nijel** [comment]
Looks like I've messed up the deploy, it works fine now.
