### ISSUE TITLE
Support FormatJS (aka React-Intl) with descriptions

### ISSUE THREAD

**Issue by graue** [WeblateOrg/weblate#8802]
### Describe the problem

I initially thought that Weblate supported FormatJS, aka React-Intl, based on issue #3286 and based on the documentation [saying that](https://docs.weblate.org/en/latest/formats.html#formats) Weblate supports "Simple key / value files, used for example by vue-i18n or react-intl."

After much confusion, I've realized that Weblate only supports FormatJS if I throw away all the string descriptions and provide strings with no context, and doesn't support FormatJS's [default format](https://formatjs.io/docs/getting-started/message-extraction), which looks like this:

```.json
{
  "some-message-id": {
    "defaultMessage": "Control Panel",
    "description": "title of control panel section"
  }
}
```

### Describe the solution you'd like

Ideally, Weblate would support the format I gave an example of above, where there is a JSON dictionary that maps each message ID to a hash of `defaultMessage` and possibly `description` strings.

### Describe alternatives you've considered

I have worked around this by writing a custom formatter on the FormatJS side for the WebExtension JSON format, and this appears to work OK so far.

However, that's not one of the [builtin formatters in FormatJS](https://formatjs.io/docs/getting-started/message-extraction), none of which Weblate appears to support.

### Additional context

I submitted a Hosted Weblate support request a week ago about this, and haven't heard back. At that time, I didn't realize the feature was unsupported, and thought it was just a configuration problem. I'm trying to translate my project [BikeHopper](https://github.com/bikehopper/bikehopper-ui).

**Comment by nijel** [comment]
Using "Crowdin Chrome JSON" formatter should work fine with Weblate https://docs.weblate.org/en/latest/formats.html#webextension-json. 

Adding native support for FormatJS should not be hard, it looks quite similar to other JSON formats. We recently got https://github.com/translate/translate/pull/4798 to add one of these.

**Comment by graue** [comment]
Thanks! Well spotted that the "Crowdin" and "WebExtension" formats are mutually compatible, despite different names.

I've filed an issue on the translate toolkit here: https://github.com/translate/translate/issues/4838

Do you want to keep this issue open as well to track? If not, feel free to close this.

**Comment by idoodler** [comment]
Would very much appreciate that 👍

**Comment by graue** [comment]
This doesn't seem to be working on hosted Weblate. When I change the format in my project settings to Format.JS, I get this error:

> Could not parse translation base file: module 'translate.storage.jsonl10n' has no attribute 'FormatJSJsonFile'

![image](https://github.com/WeblateOrg/weblate/assets/1730853/530da7d8-287a-49f0-a2de-4c7b945a7206)

**Comment by nijel** [comment]
Hmm, probably I should finally release the translate-toolkit with the backend support.

**Comment by nijel** [comment]
Here it comes: https://github.com/translate/translate/pull/5178

**Comment by graue** [comment]
Great, thank you! Although our project using Weblate is a small open source project with no budget, I made a small donation to express appreciation. 🙏
