### ISSUE TITLE
Language-specific explanations in glossary

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#8810]
### Describe the problem

The "Explanation" field in glossary entries currently seems to apply to all langages, that is, by adding an explanation a you add it to all languages' glossaries.

While I suppose this kind of "global" explanations can be useful too, it would be good to also have explanations or comments that are specific to one language. For example, if I include in the explanation a link to a Finnish article, that's useful for Finnish translators but not so much for translators of other languages.

### Describe the solution you'd like

Weblate allows creating language-specific explanations or comments in the glossary.

### Describe alternatives you've considered

If language-specific explanations are not possible, the UI and the documentation should at least communicate that the explanations as they are are global and should probably be written in the source language.

**Comment by timothyqiu** [comment]
I figured out that there could be three "Explanation" fields:

1. Read only version of 2
2. Global explanation shown for all languages
3. Language specific

![image](https://user-images.githubusercontent.com/372476/222109640-682acc6c-87ae-400f-9bbf-d2275a957e5c.png)

When both 2 and 3 exists, both will be shown in the Glossary box.

The problem is, if you click the "Add term to glossary" button in the Glossary box, the "Explanation" field is for the global explanation. But regular users can't edit global explanation.

**Comment by Geeyun-JY3** [comment]
Here are some examples of what @timothyqiu mentioned:

- https://hosted.weblate.org/translate/f-droid/glossary-f-droid/zh_Hans/?checksum=7d73c9f5ce198cc3
![image](https://user-images.githubusercontent.com/49396421/222131680-ab8e43d4-45f0-450a-bfe4-fef4d795d208.png)
- https://hosted.weblate.org/translate/f-droid/glossary-f-droid/zh_Hans/?checksum=6cf7cc0ddb514b1b
![image](https://user-images.githubusercontent.com/49396421/222132687-d15a28dd-faed-4fa9-b1c2-c037d05215cf.png)

TBH how Weblate handles the explanation of glossary entry looks quite strange.
Seems related: #6701

**Comment by Geeyun-JY3** [comment]
I am still confused about the [explanation](https://docs.weblate.org/en/latest/admin/translating.html#explanation) in Weblate. 
AFAIK, the explanation is not language-specific and it should not. And [the explanation is only stored and managed in Weblate](https://github.com/WeblateOrg/weblate/issues/8260#issuecomment-1288606944).

Is it possible for Weblate to be compatible with the standard TBX (TermBase eXchange) Version 3 to improve the glossary feature? Crowdin supports it and provides so many fields for glossary entry: https://crowdin.com/blog/2022/10/03/what-is-new-at-crowdin-september-2022#tbx-v3-support-and-advanced-glossary
I am not quite familiar with the TBX Version 3 standard. Is there a field that functions like a language-specific explanation?
Crowdin provides a field (description) like this: https://support.crowdin.com/glossary/#adding-glossary-concepts-and-terms.

**Comment by nijel** [comment]
You can have language-specific explanation. If you edit it at https://hosted.weblate.org/translate/weblate/glossary/cs/?checksum=6524385c7f47f79e it is for Czech, if at https://hosted.weblate.org/translate/weblate/glossary/en/?checksum=6524385c7f47f79e then it is for the source term and is shown for all languages.

**Comment by timothyqiu** [comment]
@nijel Is it intended that the explanation field inside this dialog is not language specific?

![ksnip_20230312-102128](https://user-images.githubusercontent.com/372476/224520624-b4808022-81d4-4e51-9c5f-1488c4008a3c.png)

I see many cases that translators mistake it as language specific, adding explanation in their own language. 

The admin has to:

1. Identify which language the explanation is written in.
2. Move the explanation to that language's glossary.
3. Clear the explanation in English glossary.
