### ISSUE TITLE
French plural Translations are not imported as in previous versions. 

### ISSUE THREAD

**Issue by ali-avci** [WeblateOrg/weblate#8823]
### Describe the issue

Had encountered that the French language has 3 kind of plurals defined in the new installation of weblate (v 4.15.2). Asked our french guys who made the translation and they told me that they are not aware of the kinds of plurals. 

Changed the language definition in such a case that the language has only two plural forms, with the formula n > 1. Defined it as it was in Weblate 3.6.1. 

But after importing the french resource bundles the "other" part of the plurals are still empty. 

Do I have to make somewhere else also a change. 

below are the English and French Resource Bundles. 

`<?xml version="1.0" encoding="UTF-8"?>
<resources>
    <plurals name="cod_header_info_text">
        <item quantity="one">%d order with cash on delivery</item>
        <item quantity="other">%d orders with cash on delivery</item>
    </plurals>
`

`<resources>
    <plurals name="cod_header_info_text">
        <item quantity="one">1 ordre avec contre remboursement</item>
        <item quantity="other">%d ordres avec contre-remboursement</item>
    </plurals>`

In the database the content of the units is as following.
`%d order with cash on delivery%d orders with cash on delivery
`

`
1 ordre avec contre remboursement
`

I assume that this is caused by the weblate-language-data package that has the 3 kind plural form in code for the french language.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Expected behavior

Expected that the "other" term in french resource bundle should appear in the UI and also in the database.

### How do you run Weblate?

PyPI module

### Weblate versions

 * Weblate: 4.15.2
 * Django: 4.1.6
 * siphashc: 2.1
 * translate-toolkit: 3.8.4
 * lxml: 4.9.2
 * Pillow: 9.4.0
 * bleach: 5.0.1
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.2
 * django-compressor: 4.3.1
 * djangorestframework: 3.14.0
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.9.0
 * rapidfuzz: 2.13.7
 * openpyxl: 3.0.10
 * celery: 5.2.7
 * kombu: 5.2.4
 * translation-finder: 2.15
 * weblate-language-data: 2023.1
 * html2text: 2020.1.16
 * pycairo: 1.23.0
 * pygobject: 3.42.2
 * diff-match-patch: 20200713
 * requests: 2.28.2
 * django-redis: 5.2.0
 * hiredis: 2.1.1
 * sentry_sdk: 1.15.0
 * Cython: 0.29.33
 * misaka: 2.1.1
 * GitPython: 3.1.30
 * borgbackup: 1.2.3
 * pyparsing: 3.0.9
 * pyahocorasick: 2.0.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.0.1
 * Python: 3.8.10
 * Git: 2.25.1
 * psycopg2: 2.9.5
 * ruamel.yaml: 0.17.21
 * mysqlclient: 2.1.1
 * Redis server: 5.0.7
 * MariaDB sever: 5.5.5
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 5.15.0-1030-aws (x86_64)

**Comment by nijel** [comment]
French is supposed to have three plurals since CLDR 38, see https://github.com/WeblateOrg/weblate/issues/7888.
