### ISSUE TITLE
Automatic translation is terribly slow

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#8832]
### Describe the issue

After one of the recent updates, automatic translation slows down a lot. Previously, the translation time for a file of 300 strings was 5-20 seconds, now it is 30-80 seconds. You have to wait a long time for the progress bar to start at all. Once it starts it runs normally.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Docker container

### Weblate versions

4.16-dev — [cd604cd0baa6bd7b9c4a370e1f7e6b8f9802cf9d](https://github.com/WeblateOrg/weblate/commits/cd604cd0baa6bd7b9c4a370e1f7e6b8f9802cf9d)

**Comment by tomkolp** [comment]
The log contains hundreds of such entries:
```
nginx stdout | 11.22.33.44 - - [23/Feb/2023:11:45:11 +0100] "GET /api/tasks/658b3dac-d60d-4d9b-810f-5ce1519f37f5/ HTTP/1.0" 200 197 "https://weblate.eso-spolszczenie.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50"
nginx stdout | 11.22.33.44 - - [23/Feb/2023:11:45:12 +0100] "GET /api/tasks/658b3dac-d60d-4d9b-810f-5ce1519f37f5/ HTTP/1.0" 200 197 "https://weblate.eso-spolszczenie.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50"
nginx stdout | 11.22.33.44 - - [23/Feb/2023:11:45:13 +0100] "GET /api/tasks/658b3dac-d60d-4d9b-810f-5ce1519f37f5/ HTTP/1.0" 200 197 "https://weblate.eso-spolszczenie.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50"
nginx stdout | 11.22.33.44 - - [23/Feb/2023:11:45:14 +0100] "GET /api/tasks/658b3dac-d60d-4d9b-810f-5ce1519f37f5/ HTTP/1.0" 200 197 "https://weblate.eso-spolszczenie.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50"
nginx stdout | 11.22.33.44 - - [23/Feb/2023:11:45:14 +0100] "GET /api/tasks/658b3dac-d60d-4d9b-810f-5ce1519f37f5/ HTTP/1.0" 200 197 "https://weblate.eso-spolszczenie.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50"
nginx stdout | 11.22.33.44 - - [23/Feb/2023:11:45:16 +0100] "GET /api/tasks/658b3dac-d60d-4d9b-810f-5ce1519f37f5/ HTTP/1.0" 200 197 "https://weblate.eso-spolszczenie.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50"
```

**Comment by nijel** [comment]
Polling for the progress is expected.

Do you know when it started to happen?

**Comment by tomkolp** [comment]
All I can say is that the bleeding version from early January worked fine. I haven't used automatic translation since then.

**Comment by nijel** [comment]
There was no code change since that time in the translation memory. Maybe the celery queue is just too long for some reason? Too many background tasks?

**Comment by tomkolp** [comment]
There is no queue.  The cpu usage is between 1-3, so nothing is done in the background.  Has anyone noticed similar slow performance?

**Comment by nijel** [comment]
What source do you use for automatic translation?

**Comment by tomkolp** [comment]
> What source do you use for automatic translation?

Other translation components (2700 components)

**Comment by tomkolp** [comment]
Does anyone else have this problem or are you supposed to look for a problem in the server configuration?  
Yesterday I ran automatic translation for a file with 8000 strings.  25 minutes nothing happened, then the progress bar started and the translation finished in 2 minutes.  For 25 minutes, the cpu smelled from 3 to 5%, disk usage max 15mb write / read.  
The only thing that has changed in the weblate configuration is: 1) about 5% of the strings have arrived and sql has been upgraded with two versions to the current one.

**Comment by nijel** [comment]
Try tuning up PostgreSQL configuration using https://pgtune.leopard.in.ua/. Giving it more memory might also help.

A good starting point might also be to figure out which SQL query is problematic, this can be seen in [pg_stat_activity view](https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-PG-STAT-ACTIVITY-VIEW).

**Comment by tomkolp** [comment]
> Try tuning up PostgreSQL configuration using https://pgtune.leopard.in.ua/. Giving it more memory might also help.
> 
> A good starting point might also be to figure out which SQL query is problematic, this can be seen in [pg_stat_activity view](https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-PG-STAT-ACTIVITY-VIEW).

Maybe the PostgreSQL update cleared my settings. I'll check again, thanks for the helpful advice.

**Comment by tomkolp** [comment]
After today's update [https://github.com/WeblateOrg/weblate/commits/dbde9ad2492ff987198089f8c520044682f7f93f](url) everything works as before and even better. When translating 18,000 strings, the wait for progress to start is now 16 seconds. @nijel are you able to confirm which fix might have helped?

**Comment by tomkolp** [comment]
@nijel 
I've identified two problems with the automatic translation: 
1) you have to commit the changes and send to the repo.  When there are any uncommitted changes, automatic translation will not start.  
2) The progress bar often hangs.  The translations are already finished and the progress bar never ends.

**Comment by nijel** [comment]
> After today's [update](https://github.com/WeblateOrg/weblate/commits/dbde9ad2492ff987198089f8c520044682f7f93f) everything works as before and even better. When translating 18,000 strings, the wait for progress to start is now 16 seconds. @nijel are you able to confirm which fix might have helped?

I'm not aware of any change which could improve the performance here.

> * you have to commit the changes and send to the repo.  When there are any uncommitted changes, automatic translation will not start.

Is there any error in the log? If so, please open an issue for that.
 
> * The progress bar often hangs.  The translations are already finished and the progress bar never ends.

Please open a separate issue for that. Including status response from the browser (networking from the developer tools will show that) would be really helpful.

**Comment by tomkolp** [comment]
Unfortunately, the problem returns.  I added one big file from github repository, waited about an hour.  Docker logs and cpu load do not indicate that anything else is being done in the queue after adding the file.  After turning on automatic translation, the progress bar stands still, nothing happens for several minutes.  Automatic translation using other components.  There are no errors in the browser console.
![Screenshot_20230418_221909_Edge](https://user-images.githubusercontent.com/39633242/232895850-b02c430b-ef36-49a2-ab1e-1088f7fc054f.jpg)
![Screenshot_20230418_222001_Edge](https://user-images.githubusercontent.com/39633242/232895882-43350fa7-77da-4a14-ac33-d3d59a1a15e7.jpg)

**Comment by tomkolp** [comment]
@nijel Automatic translation stopped working completely. Please advise what else I can check.
`weblate=# SELECT * FROM pg_stat_activity WHERE state <> 'idle' AND clock_timestamp() - query_start > interval '5 minutes';
 datid | datname |  pid   | leader_pid | usesysid | usename | application_name | client_addr | client_hostname | client_port |         backend_start         |          xact_start           |          query_start          |         state_change          | wait_event_type | wait_event | state  | backend_xid | backend_xmin | query_id |                                                                                                                                                                                                                                                                                                                  query                                                                                                                                                                                                                                                                                                                  |  backend_type
-------+---------+--------+------------+----------+---------+------------------+-------------+-----------------+-------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-----------------+------------+--------+-------------+--------------+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------
 18558 | weblate | 105105 |            |       10 | weblate |                  | 172.18.0.4  |                 |       59138 | 2023-04-19 05:22:24.344646+00 | 2023-04-19 05:22:24.423307+00 | 2023-04-19 05:22:24.435368+00 | 2023-04-19 05:22:24.435372+00 |                 |            | active |             |      1135902 |          | SELECT "trans_unit"."source", "trans_unit"."state", "trans_unit"."target" FROM "trans_unit" INNER JOIN "trans_translation" ON ("trans_unit"."translation_id" = "trans_translation"."id") INNER JOIN "trans_component" ON ("trans_translation"."component_id" = "trans_component"."id") WHERE ("trans_unit"."state" >= 20 AND "trans_component"."project_id" = 5 AND "trans_component"."source_language_id" = 131 AND "trans_translation"."plural_id" = 401 AND NOT ("trans_unit"."translation_id" = 9651) AND "trans_unit"."source" IN (SELECT U0."source" FROM "trans_unit" U0 WHERE (U0."translation_id" = 9651 AND U0."state" = 0))) | client backend
 18558 | weblate | 103758 |            |       10 | weblate |                  | 172.18.0.4  |                 |       52596 | 2023-04-19 04:39:55.599275+00 | 2023-04-19 04:39:55.633469+00 | 2023-04-19 04:39:55.642853+00 | 2023-04-19 04:39:55.642855+00 |                 |            | active |             |      1135763 |          | SELECT "trans_unit"."source", "trans_unit"."state", "trans_unit"."target" FROM "trans_unit" INNER JOIN "trans_translation" ON ("trans_unit"."translation_id" = "trans_translation"."id") WHERE ("trans_unit"."state" >= 20 AND "trans_translation"."component_id" = 2550 AND "trans_translation"."plural_id" = 401 AND "trans_unit"."source" IN (SELECT U0."source" FROM "trans_unit" U0 LEFT OUTER JOIN "trans_suggestion" U2 ON (U0."id" = U2."unit_id") WHERE (U0."translation_id" = 5427 AND U2."id" IS NULL AND U0."state" = 0)))                                                                                                  | client backend
(2 rows)
`
