### ISSUE TITLE
Leave search field when no search results

### ISSUE THREAD

**Issue by maboroshin** [WeblateOrg/weblate#8833]
### Describe the problem

The "Search" function searches for strings. If there are no results, it returns to "Overview" tab and displays "```No strings found!```". The search field disappears. Search terms have also disappeared.

### Describe the solution you'd like

Leave search field when no search results. Do the same as when search results exist.

If the search field remains, typo can be easily modified.

### Screenshots

If there are no search results: The search field disappears.
![image](https://user-images.githubusercontent.com/41102508/221171991-a8e1ca88-a873-4d85-b565-22f5cd7ff3b2.png)

----

If search results exist: There is a search field.
![image](https://user-images.githubusercontent.com/41102508/221172219-e02eff3c-106f-4539-8b3d-ceb2853f2922.png)

**Comment by maboroshin** [comment]
![ok](https://foruda.gitee.com/images/1660554569924759467/screenshot_20220815_170611.jpeg)

_Originally posted by @yangyangdaji in https://github.com/WeblateOrg/weblate/issues/8003#issuecomment-1214787796_

The images in this comment seem to work as expected.

* Search URI on this comments: https://hosted.weblate.org/browse/flathub/frontend/zh_Hans/?offset=1&q=%E5%B8%90%E6%88%B7&sort_by=-priority%2Cposition&checksum=
* URL I opened from the search tab on this project: https://hosted.weblate.org/zen/flathub/frontend/zh_Hans/?offset=1&q=%E5%B8%90%E6%88%B7&sort_by=-priority%2Cposition&checksum=

**Comment by shindodkar** [comment]
This is my first open source contribution and I am so excited to make it done. But I have only basic idea about it. 

Your guidance will be so helpful to start on this project.

**Comment by maboroshin** [comment]
@shindodkar 
I am a bug reporter and don't know the details of the program. However, the following string is present in the URL

browse / translate / zen

Weblate would call three different functions for this. The "browse" is working as expected. So you simply copy this behavior into the other two functions.

When you have completed your code changes, please submit a pull request to GitHub.

**Comment by nijel** [comment]
The error handling is here:

https://github.com/WeblateOrg/weblate/blob/43a3a7fbdb6049fe083082b2b28ad5158eddf4aa/weblate/trans/views/edit.py#L265-L268

What IMHO would be the best approach is to add `?q=<QUERY>#search` to the redirect URL and make the parent page load the URL parameter to the form and display it.

**Comment by Harish-2403** [comment]
> The error handling is here:
> 
> https://github.com/WeblateOrg/weblate/blob/43a3a7fbdb6049fe083082b2b28ad5158eddf4aa/weblate/trans/views/edit.py#L265-L268
> 
> What IMHO would be the best approach is to add `?q=<QUERY>#search` to the redirect URL and make the parent page load the URL parameter to the form and display it.

Hi nijel . I made the following change in the code you mentioned:
`if not unit_ids and not blank:
    search_query = cleaned_data.get("q", "")
    redirect_url = f"{base}?q={search_query}#search"
    return redirect(redirect_url)`
But I am unable to find the parent page to change it. Can you help me find it

**Comment by nijel** [comment]
That's basically all show_* views in weblate/trans/views/basic.py. Look where `SearchForm` is instantiated.

**Comment by maboroshin** [comment]
This issue has now been resolved.

However, The design shows the input field below the original input field. It's not an intuitive understanding.

If there are no search candidates:

![image](https://github.com/WeblateOrg/weblate/assets/41102508/40be6db0-99d5-4967-b5f4-c78348483398)

----

If search candidates exist:

![image](https://github.com/WeblateOrg/weblate/assets/41102508/edc141c7-2551-4631-bff5-be764bea089e)

**Comment by nijel** [comment]
Indeed, this was addressed in 35a540d8d234f1eb6f67e12740f4b084eeef3c3a. The view is different, but the search input is now preserved.
