### ISSUE TITLE
Save button disabled unexpectedly

### ISSUE THREAD

**Issue by timothyqiu** [WeblateOrg/weblate#8864]
### Describe the issue

I'm an admin of the [Godot Engine](https://hosted.weblate.org/projects/godot-engine/) project.

Starting from last night, the "Save and continue" buttons is disabled for me, with the tooltip

> Insufficient privileges for saving translations.

* I am still able to upload translations.
* The button is only enabled in the glossary component, and disabled in other components.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Go to a translation page.

### Expected behavior

The "Save and continue" buttons is enabled.

### Screenshots

![image](https://user-images.githubusercontent.com/372476/222104504-1399f243-580d-4e62-bf9d-ccd0f93264e0.png)

### How do you run Weblate?

weblate.org service

### Additional context

I think it's probably related to this commit yesterday: https://github.com/WeblateOrg/weblate/commit/6468f6630fa61a96e715e38028ec674bb47c2f5b

The `elif` condition seems wrong according to logic described in the commit message.

> When user can edit flags, **but can not save translations**, the Save button
is needed only for glossaries

https://github.com/WeblateOrg/weblate/blob/3d17243adff83e1c562314e94c0f8cc901d1e14b/weblate/templates/translate.html#L219-L222

**Comment by PascalRepond** [comment]
We have the same problem in our project https://hosted.weblate.org/translate/rero_plus/
