### ISSUE TITLE
broken link in Community localization checklist to Configure repository hooks for automated flow

### ISSUE THREAD

**Issue by zisuu** [WeblateOrg/weblate#8877]
### Describe the issue

In weblate version 4.16.1 this links to a borken url:
![image](https://user-images.githubusercontent.com/11134301/222706141-d28d7d05-7295-416c-abdb-8f763b959144.png)

URL: https://docs.weblate.org/en/weblate-4.16.1/admin/continuous.html#update-vcs

shows:
![image](https://user-images.githubusercontent.com/11134301/222706264-13d69d24-bb00-4d9e-9183-7bbf1b892cb9.png)

If i change to URL to version 4.16 the link seem to work:
https://docs.weblate.org/en/weblate-4.16/admin/continuous.html#update-vcs

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to 'Community localization checklist'
2. On Version control integration -> Configure repository hooks for automated flow of updates to Weblate -> Click 'Configure'

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.16.1
 * Django: 4.1.7
 * siphashc: 2.1
 * translate-toolkit: 3.8.4
 * lxml: 4.9.2
 * Pillow: 9.4.0
 * nh3: 0.2.8
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 2.0
 * oauthlib: 3.2.2
 * django-compressor: 4.3.1
 * djangorestframework: 3.14.0
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.9.0
 * rapidfuzz: 2.13.7
 * openpyxl: 3.1.1
 * celery: 5.2.7
 * django-celery-beat: 2.4.0
 * kombu: 5.2.4
 * translation-finder: 2.15
 * weblate-language-data: 2023.3
 * html2text: 2020.1.16
 * pycairo: 1.23.0
 * pygobject: 3.42.2
 * diff-match-patch: 20200713
 * requests: 2.28.2
 * django-redis: 5.2.0
 * hiredis: 2.2.2
 * sentry_sdk: 1.16.0
 * Cython: 0.29.33
 * misaka: 2.1.1
 * GitPython: 3.1.31
 * borgbackup: 1.2.3
 * pyparsing: 3.0.9
 * pyahocorasick: 2.0.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.0.1
 * Python: 3.11.2
 * Git: 2.30.2
 * psycopg2: 2.9.5
 * psycopg2-binary: 2.9.5
 * phply: 1.2.6
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * boto3: 1.26.81
 * zeep: 4.2.1
 * aeidon: 1.12
 * iniparse: 0.5
 * mysqlclient: 2.1.1
 * Mercurial: 6.3.2
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 7.0.7
 * PostgreSQL server: 15.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtpauth.pnet.ch
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache_community_test:6379/1, redis://cache_community_test:6379/1, regular
 * Platform: Linux 4.18.0-372.26.1.el8_6.x86_64 (x86_64)

**Comment by nijel** [comment]
Seems like manual trigger to build that is failing as well, created https://github.com/readthedocs/readthedocs.org/issues/10101 to discuss this with readthedocs.org.

**Comment by nijel** [comment]
The docs is now built.
