### ISSUE TITLE
Concordance Search in Translation Memory returns error message

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#8878]
### Describe the issue

When you search for a term or phrase in the translation memory, now result is returned, but this error message:
![image](https://user-images.githubusercontent.com/26718215/222762366-1228d228-b6b7-448b-bd89-b77b44be0e1a.png)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Switch to tab "Automatic Translation"
2. Search for a term or phrase in the Search field.

### Expected behavior

I would expect a search result like this on the previous version:
![image](https://user-images.githubusercontent.com/26718215/222763357-411584b7-e6d2-4714-9189-d835872b4720.png)

### Screenshots

![image](https://user-images.githubusercontent.com/26718215/222762748-d3e37c86-36d4-46d8-9bf0-3b4248dc4fc8.png)

### How do you run Weblate?

Docker container

### Weblate versions

4.16.1

**Comment by nijel** [comment]
This is already fixed in git for 4.16.2

**Comment by nijel** [comment]
Fixes in de87bf928c11891e33ea653cdbbd6bcc58468bc9
