### ISSUE TITLE
Add permalink to zen mode

### ISSUE THREAD

**Issue by maboroshin** [WeblateOrg/weblate#8882]
### Describe the issue

In Zen mode, "Open in full editor" refers to a string in the following hash:

```?q=state%3A<translated&offset=5```

The offset appears to be the ordered number of search results. It points to a different string, perhaps because the cache changes over time. Probably.

This method changes the link to a different string. No one would expect a different string to open. Another problem is that giving the address to others may later refer to a different string.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Open some language in some project somewhere.
2. Open "Unfinished strings" (This string is translated in the language you chose.)
3. From the top right, enable Zen mode.
4. Copy any string and the URL for "Open in full editor".
5. Start translation.
6. Open the copied URL a few hours later.
7. A different string appears.

### Expected behavior

"Open in full editor." refers to a unique string. See hash of ```checksum```, not ```offset```.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
That's why there is a permalink icon on top of the editor. If you share a link to untranslated strings, you should get a list of currently untranslated strings…

**Comment by maboroshin** [comment]
In Zen mode, there are only offset links.

Sample URL:
https://hosted.weblate.org/zen/yattee/localizable-strings/ja/?q=state:%3Ctranslated

**Comment by maboroshin** [comment]
The editor's link is still referenced by '''offset'''. So now I need to do the following for each string. (1) Copy URL. (2) Open a new window. (3) Copy to address.

Comments and history can't be viewed from Weblate's list mode (ZEN mode). To improve the quality of the translation, it is necessarily necessary to open the editor URL. So, ```offset``` shifts are often encountered.
