### ISSUE TITLE
Enabling Deepl not working - Failed to fetch translation: DeepLTranslation.download_translations()

### ISSUE THREAD

**Issue by cbreit** [WeblateOrg/weblate#8886]
### Describe the issue

When trying to enable Deepl for auto-translation the following error occurs:
`Failed to fetch translation: DeepLTranslation.download_translations() takes from 6 to 7 positional arguments but 8 were given`

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Setup latest Weblate accorind to: https://github.com/WeblateOrg/docker-compose
2. Setup a free DeepL account; get API key
3. Got to: <weblate_utl>/manage/machinery/deepl/
4. Enter API-URL for free service(https://api-free.deepl.com/v2/) and enter API key.
5. Press 'Save'

### Expected behavior

Plugin gets enabled.

### Screenshots

![image](https://user-images.githubusercontent.com/9445373/223096014-8a628703-c854-4bc8-b5a8-4be4a8dc5b1b.png)

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.16.1
 * Django: 4.1.7
 * siphashc: 2.1
 * translate-toolkit: 3.8.4
 * lxml: 4.9.2
 * Pillow: 9.4.0
 * nh3: 0.2.8
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 2.0
 * oauthlib: 3.2.2
 * django-compressor: 4.3.1
 * djangorestframework: 3.14.0
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.9.0
 * rapidfuzz: 2.13.7
 * openpyxl: 3.1.1
 * celery: 5.2.7
 * django-celery-beat: 2.4.0
 * kombu: 5.2.4
 * translation-finder: 2.15
 * weblate-language-data: 2023.3
 * html2text: 2020.1.16
 * pycairo: 1.23.0
 * pygobject: 3.42.2
 * diff-match-patch: 20200713
 * requests: 2.28.2
 * django-redis: 5.2.0
 * hiredis: 2.2.2
 * sentry_sdk: 1.16.0
 * Cython: 0.29.33
 * misaka: 2.1.1
 * GitPython: 3.1.31
 * borgbackup: 1.2.3
 * pyparsing: 3.0.9
 * pyahocorasick: 2.0.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.0.1
 * Python: 3.11.2
 * Git: 2.30.2
 * psycopg2: 2.9.5
 * psycopg2-binary: 2.9.5
 * phply: 1.2.6
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * boto3: 1.26.81
 * zeep: 4.2.1
 * aeidon: 1.12
 * iniparse: 0.5
 * mysqlclient: 2.1.1
 * Mercurial: 6.3.2
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 7.0.9
 * PostgreSQL server: 15.2
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: w01c1b5e.kasserver.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 6.1.0-3-amd64 (x86_64)

### Additional context

API key is working -- following curl returns the correct translation:
`curl -X POST 'https://api-free.deepl.com/v2/translate' -H 'Authorization: DeepL-Auth-Key xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:fx' -d 'text=Hello%2C%20world!' -d 'target_lang=DE'`

**Comment by nijel** [comment]
Already fixed in 8b1ec22d991e299e1e1f274038418d3712cb53ed via #8880
