### ISSUE TITLE
Variables stripped with XLIFF format

### ISSUE THREAD

**Issue by isametal88** [WeblateOrg/weblate#8891]
### Describe the issue

Hello,
we are facing a problem using Weblate to handle the translation of our Angular application.
I think we are missing something, but we're not able to figure out what.
The source strings are extracted in XLIFF (1.2) format using the standard Angular tools, but when the source messages are uploaded to weblate for translation, every variable used in the strings is stripped. We don't know if we need to write these variables in a certain way to make them work.

Source string example:
`<trans-unit id="2085829909901977917" datatype="html">
        <source>rinnovabile <x id="PH" equiv-text="getYearFromDate(this.coupon.fixed_license_expire)"/></source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/_shared/components/coupon-modal-accountant/coupon-display/coupon-description/coupon-description.component.ts</context>
          <context context-type="linenumber">17</context>
        </context-group>
      </trans-unit>`

Spanish version created from weblate
`<trans-unit id="2085829909901977917" datatype="html" xml:space="preserve" approved="no">
        <source>rinnovabile</source>
        <target state="translated">renovable</target>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/_shared/components/coupon-modal-accountant/coupon-modal-accountant.component.ts</context>
          <context context-type="linenumber">112,111</context>
        </context-group>
      </trans-unit>`

Of course the result is the correct string in the base language, and only "rinnovabile" in spanish.
Thank you for your support

Isaia

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
You should choose XLIFF with placeables support, see https://docs.weblate.org/en/latest/formats.html#xliff

**Comment by isametal88** [comment]
Hello Nijel,

this is the format Angular uses with XLIFF:

`<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="it" datatype="plaintext" original="ng2.template">
    <body> ...`

Using placeables I generate units like this: 
`<trans-unit id="4666442495607243569" datatype="html">
        <source>Data di riferimento <x id="refDate" equiv-text="item.reference_date"/></source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/sections/communications/components/side/edit/edit.config.ts</context>
          <context context-type="linenumber">42</context>
        </context-group>
      </trans-unit>`

but looking at the string in weblate, it's only 'Data di riferimento ', so the variable is lost in the translation.

Also, i'm not able to use placeables using i18n tags but only with localize (but this is more a Angular problem, I think)

Thank you very much

Isaia
