### ISSUE TITLE
Backup does not restore

### ISSUE THREAD

**Issue by fynngodau** [WeblateOrg/weblate#8905]
### Describe the issue

I am trying to import a backup from a project exported on another Weblate instance. This is not successful and yields the following cryptic error message:

>Failed to load project backup: '' is too short Failed validating 'minLength' in schema['items']['properties']['source']: {'$id': '#/items/properties/source', 'default': '', 'examples': ['Hello'], 'minLength': 1, 'title': 'The Source String', 'type': 'string'} On instance[81]['source']: ''

Unfortunately I do not understand what this means and failed to find and fix the problem in my backup ZIP manually.

Both instances are running the same weblate version. Two other projects have successfully exported and imported in this combination of instances.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

- Add new translation project → Import backup
- Upload my project backup as exported from https://weblate.bubu1.eu/projects/librariesdirect/librariesdirect/: [1678372565.zip](https://github.com/WeblateOrg/weblate/files/10932734/1678372565.zip)

### Expected behavior

The backup should import successfully.

### How do you run Weblate?

Docker

### Weblate versions

Both instances run 4.16.2

**Comment by nijel** [comment]
The problem is that there is an empty string in the translation memory (inside `weblate-memory.json`):

```json
  {
    "source": "",
    "target": " ",
    "source_language": "en",
    "target_language": "pt_BR",
    "origin": "librariesdirect/librariesdirect",
    "category": 10000003
  }
```

Removing it should fix the import. 

Still, Weblate should handle this gracefully.

**Comment by fynngodau** [comment]
Thanks, I've removed the faulty entry from my JSON file and the import was now successful.
