### ISSUE TITLE
XML text is not always detected

### ISSUE THREAD

**Issue by roptat** [WeblateOrg/weblate#8915]
### Describe the issue

I have a translation for a docbook document (using po4a, so each file is a single po file). The XML markup is detected and clickable during translation in most strings, but sometimes it's not. It seems to be related to unknown entities somehow, as strings with no entities or only `&nbsp;` have clickable markup, but not strings with custom markup such as `&gcc-version;`.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

You can find the XML markup detected on https://translate.linuxfromscratch.org/translate/linux-from-scratch/chapter02_hostreqs/fr/?checksum=26d0af51767838e6&sort_by=-priority,position (where you can click on XML markup), but  not on the very next string, which has the same structure and the same context in the po file on https://translate.linuxfromscratch.org/translate/linux-from-scratch/chapter02_hostreqs/fr/?sort_by=-priority%2Cposition&offset=8

### How do you run Weblate?

PyPI module

### Weblate versions

 * Weblate: 4.16.2
 * Django: 4.1.7
 * siphashc: 2.1
 * translate-toolkit: 3.8.5
 * lxml: 4.9.2
 * Pillow: 9.4.0
 * nh3: 0.2.8
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 2.0
 * oauthlib: 3.2.2
 * django-compressor: 4.3.1
 * djangorestframework: 3.14.0
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.9.0
 * rapidfuzz: 2.13.7
 * openpyxl: 3.1.1
 * celery: 5.2.7
 * django-celery-beat: 2.4.0
 * kombu: 5.2.4
 * translation-finder: 2.15
 * weblate-language-data: 2023.3
 * html2text: 2020.1.16
 * pycairo: 1.23.0
 * pygobject: 3.42.2
 * diff-match-patch: 20200713
 * requests: 2.28.2
 * django-redis: 5.2.0
 * hiredis: 2.2.2
 * sentry_sdk: 1.16.0
 * Cython: 0.29.33
 * misaka: 2.1.1
 * GitPython: 3.1.31
 * borgbackup: 1.2.3
 * pyparsing: 3.0.9
 * pyahocorasick: 2.0.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.0.1
 * Python: 3.10.6
 * Git: 2.34.1
 * psycopg2: 2.9.5
 * phply: 1.2.6
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * boto3: 1.26.83
 * zeep: 4.2.1
 * aeidon: 1.12
 * iniparse: 0.5
 * Mercurial: 6.3.3
 * git-svn: 2.34.1
 * git-review: 2.3.1
 * Redis server: 6.0.16
 * PostgreSQL server: 14.7
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 5.15.0-1030-oracle (aarch64)

### Weblate deploy checks

```shell
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.16.2/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.16.2/admin/backup.html

System check identified 2 issues (1 silenced).
```

**Comment by nijel** [comment]
Add `xml-text` flag to these strings. Otherwise, there is some detection in place which does not deal with some situations. See https://docs.weblate.org/en/latest/admin/checks.html#customizing-behavior-using-flags and https://docs.weblate.org/en/latest/user/checks.html#xml-markup.
