### ISSUE TITLE
Preferred language when not logged in

### ISSUE THREAD

**Issue by maboroshin** [WeblateOrg/weblate#8937]
### Describe the problem

Preferred target language not detected when not logged in.
* List of languages for each component https://hosted.weblate.org/projects/weblate/application/
* Project Languages Tab https://hosted.weblate.org/projects/weblate/#languages

### Describe the solution you'd like

Display the browser's display language at the beginning of the language list. Same as when login.

### Additional context

"日本語 (Japanese)" is displayed at the bottom of the list due to the rules of Japanese. They have to scroll to the bottom every time. The languages at the bottom in Unicode order have the same problem.

**Comment by nijel** [comment]
The logic is here:

https://github.com/WeblateOrg/weblate/blob/a58b7f350220b6a5760ff9230ac042efbcd63620/weblate/accounts/models.py#L691-L700

Adding the current interface language is the easiest path, but that would limit it to only languages in which Weblate is translated. Building on top of `Language.objects.get_request_language` is probably a more generic approach.

**Comment by dankrzeminski32** [comment]
Hey @nijel,

I'm starting work on this. What do you mean by "Adding the current interface language"?

If extending on `Language.objects.get_request_language`, do we catch `Language.DoesNotExist` and create a new language?

**Comment by maboroshin** [comment]
Perhaps the language of the system is detected.

**Comment by nijel** [comment]
`get_request_language` already catches `DoesNotExist`. Creating new languages there is not useful – we would rather not pollute the database with random stuff the user sends in an HTTP header.

**Comment by dankrzeminski32** [comment]
So if the user is not logged in,

1.) Get language from header using `get_request_language` and match it to our db record
2.) Prioritize this above all other languages in  get_translation_order 

Let me know if that sounds right.

**Comment by nijel** [comment]
Yes, `get_translation_order` will need to receive `request` as well to be able to get that information.
