### ISSUE TITLE
unable to parse gotext json

### ISSUE THREAD

**Issue by cherepanov** [WeblateOrg/weblate#8938]
### Describe the issue

Fresh install via official docker compose ver 4.16.2
Create translation component as described in docs and use official gotext examples as source

https://docs.weblate.org/en/latest/formats.html#gotext-json

https://github.com/golang/text

Import fails with
```
Could not parse translation base file: 'str' object has no attribute 'get'
```

The same message in console

```
weblate_1   | gunicorn stderr | [2023-03-16 09:39:54,825: WARNING/384] Template parse error: AttributeError: 'str' object has no attribute 'get'
```

Related: #4844 #4323

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Expected behavior

Successful import our meaningful error message

### Screenshots

![image](https://user-images.githubusercontent.com/876145/225576193-f9ccabc1-f807-4960-9ee2-915f2bcb18f1.png)

### How do you run Weblate?

Docker container

### Weblate versions

4.16.2

**Comment by cherepanov** [comment]
> Can you share the problematic file?

I setup to use golang/text as source repo, so file is here

https://github.com/golang/text/blob/master/cmd/gotext/examples/extract/locales/en-US/messages.gotext.json

**Comment by nijel** [comment]
I've discovered two issues while parsing these files:

* https://github.com/translate/translate/issues/4868
* https://github.com/translate/translate/issues/4867

I don't see any issue within Weblate, so I'm closing this issue in favor of these two.
