### ISSUE TITLE
Failing checks notification and disabling is not intuitive

### ISSUE THREAD

**Issue by scarabeusiv** [WeblateOrg/weblate#894]
When translating strings that have failing checks like "source same as target" it is not obvious that one has to unitck the warning notification in the coner to make it go away. Maybe if there was popup when clicking on save that would make it disappear it would save me, and others of course, quite few minutes of wondering :)
##

**Comment by nijel** [comment]
I guess #949 will make it easier to understand.

**Comment by nijel** [comment]
We really need more detailed view for the check and visible actions:

- improve naming (see https://github.com/WeblateOrg/weblate/issues/2956)
- make the ignore button more visible
- possibly adding button to ignore for all languages (seems quite common use case for non translatable strings)
- maybe include even the description or suggestion how to fix

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
