### ISSUE TITLE
Make read-only strings blue

### ISSUE THREAD

**Issue by throwaway-d** [WeblateOrg/weblate#8949]
### Describe the problem

https://github.com/Darkempire78/OpenCalc/issues/197

It would be easy to differ with editable strings.

### Describe the solution you'd like

Just read the title

### Screenshots

![image](https://user-images.githubusercontent.com/121148372/226152889-076a51f6-f1d1-4623-abaa-18e1972ae7c9.png)
![image](https://user-images.githubusercontent.com/121148372/226152919-3b580fbd-2435-4a38-9f4a-3a0ea54b9f68.png)

### Additional context

I'm very newbie to reporting issues on this project. This project looks very big and complex. I hope the issue description is good enough.

**Comment by throwaway-d** [comment]
@@github-actions I don’t like you.

**Comment by Geeyun-JY3** [comment]
The reason why the read-only strings of [F-Droid](https://hosted.weblate.org/projects/f-droid/) are blue is this project enables review. 
Both approved strings and read-only strings are blue currently.
Example: https://hosted.weblate.org/projects/f-droid/f-droid/zh_Hans/
![image](https://user-images.githubusercontent.com/49396421/229668317-61692456-61b1-45ed-b0d1-ad566077af1d.png)

***

@nijel Now that read-only is a state different from approved, I would suggest using a different color to indicate this state.

**Comment by throwaway-d** [comment]
> Now that read-only is a state different from approved, I would suggest using a different color to indicate this state, such as black, blown, or something else.

Thank you a lot for the information! I agree with you! :D
We also need to make sure that the colors are differentiable for colorblind peope.

**Comment by throwaway-d** [comment]
> a different color that works for colorblind

Actually, the current red/green is the worst colors for colorblind people.

**Comment by throwaway-d** [comment]
About accessibility, we should have many different color schemes for users to choose and users should be able to customize their own themes. This should be discussed on a different, separate issue. 

This issue should be focused only on adding a new color for the **_default_** theme.

Funny thing is that Weblate still yet doesn’t have a default dark theme.

**Comment by Geeyun-JY3** [comment]
Dark mode is another long story: #2969

**Comment by nijel** [comment]
Yes, funny thing is that nobody contributed working dark theme so far.

**Comment by comradekingu** [comment]
As an aside, blue already doesn't work for the colour-blind if there is no green in the middle(?)

"All strings" is gray, so black?

**Comment by throwaway-d** [comment]
> As an aside, blue already doesn't work for the colour-blind if there is no green in the middle(?)

If you mean to replace the color of translated strings from green to blue. It does work. See https://www.color-blindness.com/coblis-color-blindness-simulator/

**1. Normal**
![colorblindtest](https://user-images.githubusercontent.com/121148372/230067450-c6f5f281-e39b-406a-b117-321e5e8c5acc.png)

**2. Red-Weak/Protanomaly**
![image](https://user-images.githubusercontent.com/121148372/230068248-a9967b18-103a-463e-ac75-32160c8eb80c.png)

**3. Green-Weak/Deuteranomaly**
![image](https://user-images.githubusercontent.com/121148372/230068344-613ce200-d8f8-4f86-a6e4-b1beb5d24a00.png)

**4. Blue-Weak/Tritanomaly**
![image](https://user-images.githubusercontent.com/121148372/230068438-f6584704-fd90-446a-a761-f3160f383f32.png)

**5. Red-Blind/Protanopia**
![image](https://user-images.githubusercontent.com/121148372/230068651-d2856e4d-3167-4ea1-8d8c-b3a0d55b4329.png)

**6. Green-Blind/Deuteranopia**
![image](https://user-images.githubusercontent.com/121148372/230068926-14fd3367-ca42-4783-8e6d-87b127db1049.png)

**7. Blue-Blind/Tritanopia**
![image](https://user-images.githubusercontent.com/121148372/230068962-c526f96c-b729-4756-a10c-31c7771485b3.png)

**8. Monochromacy/Achromatopsia**
![image](https://user-images.githubusercontent.com/121148372/230069222-366dcfc0-6e58-41b6-a167-faa37741a5a0.png)

**9. Blue Cone Monochromacy**
![image](https://user-images.githubusercontent.com/121148372/230069358-af90fe9d-120b-465a-a242-75b1f29cdc82.png)

**Comment by nijel** [comment]
After a lot of discussion, we settled on a simplified color scheme in https://github.com/WeblateOrg/weblate/pull/9794. The progress bar indicates strings which do not need any action, and including read-only in that pack makes perfect sense.
