### ISSUE TITLE
Chinese Traditional Hong Kong Translation BUG

### ISSUE THREAD

**Issue by 66li** [WeblateOrg/weblate#8970]
### Describe the issue

I want to access from Chinese to Chinese traditional Hong Kong, I use google-v3-api, and I encounter the following error.

celery-translate stderr | During handling of the above exception, another exception occurred:
celery-translate stderr |
celery-translate stderr | Traceback (most recent call last):
celery-translate stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
celery-translate stderr |     R = retval = fun(*args, **kwargs)
celery-translate stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
celery-translate stderr |     return self.run(*args, **kwargs)
celery-translate stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/autoretry.py", line 34, in run
celery-translate stderr |     return task._orig_run(*args, **kwargs)
celery-translate stderr |   File "/usr/local/lib/python3.10/site-packages/weblate/trans/tasks.py", line 400, in auto_translate
celery-translate stderr |     auto.process_mt(engines, threshold)
celery-translate stderr |   File "/usr/local/lib/python3.10/site-packages/weblate/trans/autotranslate.py", line 182, in process_mt
celery-translate stderr |     translations = self.fetch_mt(engines, int(threshold))
celery-translate stderr |   File "/usr/local/lib/python3.10/site-packages/weblate/trans/autotranslate.py", line 167, in fetch_mt
celery-translate stderr |     translation_service.batch_translate(
celery-translate stderr |   File "/usr/local/lib/python3.10/site-packages/weblate/machinery/base.py", line 415, in batch_translate
celery-translate stderr |     self._batch_translate(source, language, units, user=user, threshold=threshold)
celery-translate stderr |   File "/usr/local/lib/python3.10/site-packages/weblate/machinery/base.py", line 422, in _batch_translate
celery-translate stderr |     for item in self._translate(
celery-translate stderr |   File "/usr/local/lib/python3.10/site-packages/weblate/machinery/base.py", line 388, in _translate
celery-translate stderr |     raise MachineTranslationError(self.get_error_message(exc))
celery-translate stderr | weblate.machinery.base.MachineTranslationError: InvalidArgument: 400 Target language can't be equal to source language. [field_violations {
celery-translate stderr |   field: "source_language_code"
celery-translate stderr |   description: "Source language: zh-CN"
celery-translate stderr | }
celery-translate stderr | field_violations {
celery-translate stderr |   field: "target_language_code"
celery-translate stderr |   description: "Target language: zh"
celery-translate stderr | }
celery-translate stderr | ]

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

Docker container

### Weblate versions

/weblate:4.12.2-2

**Comment by nijel** [comment]
Google doesn't support this combination, but Weblate should gracefully handle this.

**Comment by 66li** [comment]
It should be translated from zh-CN to zh-HK, but the parameters passed to the Google translation API are zh-CN to zh

**Comment by nijel** [comment]
What languages does this translation have in Weblate? Google does support zh-CN and zh-TW, so maybe some mapping does not happen in the best way (probably HK variant is mapped to `zh`).

**Comment by 66li** [comment]
When I use weblate to translate zh-CN to zh-HK, ideally the translation api to google should be zh-CN to zh-HK, but actually the translation api to google is zh-CN to zh

**Comment by nijel** [comment]
The problem is that there is no zh-HK in Google :-). So Weblate ended up using zh instead. It will now use zh-TW instead as that is using the same script.

**Comment by 66li** [comment]
I use zh-HK , Google-V3-api works fine
