### ISSUE TITLE
Ability to specify ranges when uploading and downloading files

### ISSUE THREAD

**Issue by Rindbee** [WeblateOrg/weblate#8971]
### Describe the problem

Recently, I often translate, proofread, and check the effect locally. Then upload the file to https://hosted.weblate.org/.

As an example, I downloaded the latest translation files from this website. 
Then, I translated the entries between the 100th and 200th locally in order.
When uploading and processing conflicts, I hope that only the entries between 100-200 will be affected, this prevents overwriting work done by other users during this period.

### Describe the solution you'd like

Would like to be able to specify the range covered when uploading.

### Screenshots

![0](https://user-images.githubusercontent.com/30386067/227113083-9ea735ab-0f91-494b-a1dd-b2ebd423eb16.png)

**Comment by nijel** [comment]
You can already do filtering in download. On upload I'm not sure how useful it would be (there are tricky cases like obsolete strings, which might be counted by some editors and skipped by others).

**Comment by Rindbee** [comment]
> You can already do filtering in download. 

I also didn't find the desired option in the download filter options. Because not only to translate but also to **proofread**.
So I want to get all entries between `100 - 200`, variously annotated, translated and untranslated. If it's not in that range, and it keeps old translations, it might overwrite another user's work on the range `300 - 400` when uploading.

> On upload I'm not sure how useful it would be (there are tricky cases like obsolete strings, which might be counted by some editors and skipped by others).

I don't think there is a need for an exact range, a range like` 90 - 220` is also suitable. Of course, you can also specify a narrower range such as `110 -190`. If necessary, manually check the index on the site to get the closest possible range.

**Comment by nijel** [comment]
Ah, I thought it was there. I've added position based filtering int 29a601a8a8a70b3fab0d36bb1914e8b84fd5d170.
