### ISSUE TITLE
Allow to select language(s) when creating Announcement

### ISSUE THREAD

**Issue by keunes** [WeblateOrg/weblate#8973]
### Describe the problem

For AntennaPod we're looking for translators of certain languages that are active in our project, to engage them in a special 'assignment'. To do this, we'd like to send a message only to those users involved in our languages.

### Describe the solution you'd like

When creating an announcement, be able to multi-select languages (list contains those languages active in the project). Then the message/announcement only goes to the translators that are active for/following our project.

### Screenshots

![afbeelding](https://user-images.githubusercontent.com/11229646/227131771-82491b8f-0a98-4d30-a3c9-527b17aa7828.png)

### Additional context

The 'Post announcement' functionality is available under Manage > Post announcement:
https://hosted.weblate.org/projects/antennapod/#announcement

In Django (admin interface) it is already possible to select languages: https://docs.weblate.org/en/latest/admin/announcements.html

**Comment by nijel** [comment]
#11003 seems like a better approach to me.

**Comment by nijel** [comment]
Closing in favor of (already implemented) https://github.com/WeblateOrg/weblate/issues/11003
