### ISSUE TITLE
Keys in similar keys part are not similar at all.

### ISSUE THREAD

**Issue by AgnesWuYulun** [WeblateOrg/weblate#8976]
### Describe the issue

We use the Weblate 4.15.1
When I translate, there is a function named "similar keys" below. But those keys are not similar to the key that is being translated.
We feel confused about this problem and don't know how to fix it.

Would you please let me know why this problem occurs and how to solve it? Thank you!

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Screenshots

![similar keys](https://user-images.githubusercontent.com/128686188/227149803-732d8c46-ce66-4e8a-a172-7441025bc57a.png)

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
It is a list of strings alphabetically ordered by key.

**Comment by AgnesWuYulun** [comment]
> 

Hi, thank you! But why it's called similar keys and they're just listed alphabetically? It's a tricky title. So "similar keys" is not used as a translation memory tool? Would you please let me know?

**Comment by nijel** [comment]
The translation memory is shown in "Automatic suggestions".
