### ISSUE TITLE
Automatic translation add-on mess string statuses

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#8979]
### Describe the issue

AT add-on applies the status of the source string to the translation instead of applying the one chosen when installing.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Install automatic translation add-on
2. Set it to "add as Needs editing"
3. Let it do its magic
4. See that strings translated by it have the status of the source string (Approved) instead of Needs editing.

### How do you run Weblate?

Other

### Weblate versions

4.14.1

**Comment by KadAnna** [comment]
would it be possible to also add the status "for review"?

**Comment by nijel** [comment]
That is currently the only option, you cannot add strings as approved. Please open a separate issue if you want that as well.

**Comment by KadAnna** [comment]
see https://github.com/WeblateOrg/weblate/issues/9048
