### ISSUE TITLE
GitLab merge request API access for gitlab.com is not configured

### ISSUE THREAD

**Issue by madi-nuralin** [WeblateOrg/weblate#8986]
### Describe the issue

I try to setup a Push Request on GitLab.
The steps that I've completed:
1. Add `@weblate` user as a collaborator to gitlab project.
2. Create access token on gitlab.
3. In `weblate-docker` modify docker env as below:
```
WEBLATE_GITLAB_USERNAME=weblate
WEBLATE_GITLAB_HOST=https://gitlab.com
WEBLATE_GITLAB_TOKEN=**token**
```
4. `docker-compose up`
5. Put Generated SSH key from Weblate into GitLab.
6. Appropriately configure VCS setup for project component.

Finally, I made some translation and as a result push command returned:
 `[2023-03-24 10:17:49,424: WARNING/370] Could not push the repo: RepositoryException: GitLab merge request API access for gitlab.com is not configured`.

Could someone tell me what I did incorrect?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Docker container

### Weblate versions

Weblate: 4.16.4

**Comment by nijel** [comment]
It should be `WEBLATE_GITLAB_HOST=gitlab.com`.

**Comment by madi-nuralin** [comment]
Thank you @nijel, it helped!
appreciate your help)
