### ISSUE TITLE
POST /file API endpoint does not work

### ISSUE THREAD

**Issue by Sil3ntStorm** [WeblateOrg/weblate#8988]
### Describe the issue

Using python requests to upload a new translation file to weblate leads to the following error:
```
{
    'conflicts': ['"conflicts" is not a valid choice.'],
    'fuzzy': ['"fuzzy" is not a valid choice.'],
    'method': ['"method" is not a valid choice.'],
}
```
When removing the parameters it complains about, the request succeeds but does not actually change anything or make any of the new strings available in the Web UI.

The function used:
```py
import requests
from pprint import pformat

def upload_translation_data(api_key: str, endpoint: str, project: str, component: str, file_path: str):
    url = f'{endpoint}/api/translations/{project}/{component}/en/file/'
    hdr = {'Authorization': f'Token {api_key}'}
    data = { 'email': 'some@email.address', 'author': 'Some Name', 'method': 'fuzzy', 'fuzzy': 'process', 'conflicts': 'replace-translated' }

    with open(file_path, 'rb') as f:
        resp = requests.post(url, headers = hdr, files = { **data, 'file': ('application/json', f)})
        print(f'Request finished with status {resp.status_code} reply: {pformat(resp.json())}')
        return resp.status_code == 200
    return False
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Run the function with a plain JSON file and observe the error.

### Expected behavior

The request is successful and strings that changed in the source file are updated in Weblate and new strings from the file are present ready to be translated.

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
`files = { **data` looks wrong, can you enable logging to see what it actually does produce?

Using `json=data, files={` instead should be correct way to perform the request.

**Comment by Sil3ntStorm** [comment]
It produces 
```
{'email': 'some@email.address', 'author': 'Some Name', 'method': 'fuzzy', 'fuzzy': 'process', 'conflicts': 'replace-translated', 'file': ('application/json', <_io.BufferedReader name='en.json'>)}
```
which seems fine to me.
Regardless doing it that other way at least seems to make Weblate understand the request and reply with a 200 code.

**However** it does not change anything. No new translations from the file (that are not present in Weblate yet) are added, nor are existing ones (removed from the file) removed. None of the changed ones are updated either. Basically it accepts the request but opts to not do anything it seems like.

So I guess the question then becomes "How do you update the source of the translations using the API, in a way that removes or marks as deprecated deleted strings across all languages for a specified component, while simultaneously adding any new strings to all languages for said component by doing a single API call?"

**Comment by nijel** [comment]
This is not what I meant. I was asking how the actual request looks like. So I did it for you:

```
--0eb868755c626e539b032398ad9aac55
Content-Disposition: form-data; name="email"; filename="email"

some@email.address
--0eb868755c626e539b032398ad9aac55
Content-Disposition: form-data; name="author"; filename="author"

Some Name
--0eb868755c626e539b032398ad9aac55
Content-Disposition: form-data; name="method"; filename="method"

fuzzy
--0eb868755c626e539b032398ad9aac55
Content-Disposition: form-data; name="fuzzy"; filename="fuzzy"

process
--0eb868755c626e539b032398ad9aac55
Content-Disposition: form-data; name="conflicts"; filename="conflicts"

replace-translated
```

As you can see, the variables are sent as files with content you've passed.

The correct way of passing the data is:

```python
        resp = requests.post(url, headers = hdr, data=data, files = {'file': ('application/json', f)})
```

Please read requests documentation to understand this better.
