### ISSUE TITLE
OpenAI GPT-4 MT

### ISSUE THREAD

**Issue by AsmoKoskinen** [WeblateOrg/weblate#9009]
### Describe the problem

Many automatic machine translation services are available on Weblate.

### Describe the solution you'd like

How about to open a machine translation service for OpenAI GPT-4?

https://openai.com/waitlist/gpt-4-api

### Additional context

I have this API in use for GPT-4. GPT-4 translates very well, I use it to translate from English to Finnish.

**Comment by ilocit** [comment]
I'd be interested in exploring this too, @AsmoKoskinen 

I already created a little Python script to help me check out the possibilities.
![image](https://user-images.githubusercontent.com/26718215/228507126-296dba52-3efa-4c99-87be-115ac8ed0702.png)

Maybe we can build a team and spec out the desired features,the  UI and work on the implementation.

**Comment by AsmoKoskinen** [comment]
@ilocit Well, I am no developer at all, just using (quite heavy) Weblate (private docker site). Weblate 4.16 added support for IBM Watson Language Translator. Just like to see GPT-4 for Weblate, too.

**Comment by nijel** [comment]
Adding support for another MT is simple, see how it was done for IBM Watson: https://github.com/WeblateOrg/weblate/pull/8594

**Comment by ilocit** [comment]
Thanks for pointing to the IBM Watson implementation as reference, @nijel .
But the implementation of ChatGPT, if we want to put it into full use to benefit from the possibilities which go beyond "yet another MT engine", is a bit more complex and would require some brainstorming about a possible UI for this service with settings and prompt enhancements.

If there is anybody interested in making this happen, I'd be happy to participate.
I will also give a simple implementation a shot. As a first draft.

**Comment by nijel** [comment]
More options can be added later, the form can be customized, and the MT can be installed per project, so that each project can have different settings.

**Comment by AsmoKoskinen** [comment]
Well, after reading about IBM Watson MT, reading about OpenAI API and chatting with GPT-3.5/4 I managed figure out something that works on Weblate 4.16.4 (Mac OS). Hopefully someone will pick this up and do it the right way.

![Näyttökuva 2023-4-9 kello 17 29 39](https://user-images.githubusercontent.com/28524781/230778962-9f2b1b91-b4e0-4eee-8ef4-a71878538763.jpg)

I touched models.py, test.py and openai.py.

models.py

[...]
"weblate.machinery.ibm.IBMTranslation",
"weblate.machinery.openai.OpenAITranslation", 
[...]

tests.py

[...]
from weblate.machinery.ibm import IBMTranslation
from weblate.machinery.openai import OpenAITranslation
[...]

openai.py as a attachment.
[openai.py.zip](https://github.com/WeblateOrg/weblate/files/11185687/openai.py.zip)

**Comment by AsmoKoskinen** [comment]
Here is a working try with model "gpt-4", openai.py as a attachment.
[openai.py.zip](https://github.com/WeblateOrg/weblate/files/11193282/openai.py.zip)

**Comment by AsmoKoskinen** [comment]
I try PR for this issue.

**Comment by AsmoKoskinen** [comment]
I encountered this error (machinery failed: not supported language pair: en - fi).

This seems to fix it:

![Näyttökuva 2023-4-14 kello 9 08 42](https://user-images.githubusercontent.com/28524781/231955634-f49fbd5d-65f4-421e-84e0-63dbf6cbfcec.jpg)

```
    def map_code_code(self, code):
        return code.replace("_", "-").split("-")[0].lower()

    def is_supported(self, source, language):
        return True
```

Now it works again.

But I can't do a proper PR the right way.

However, here are the four files that I have changed.
[machine.rst.zip](https://github.com/WeblateOrg/weblate/files/11229259/machine.rst.zip)
[tests.py.zip](https://github.com/WeblateOrg/weblate/files/11229300/tests.py.zip)
[models.py.zip](https://github.com/WeblateOrg/weblate/files/11229302/models.py.zip)
[openai.py.zip](https://github.com/WeblateOrg/weblate/files/11229303/openai.py.zip)

**Comment by nijel** [comment]
More complex persona will be needed to make this work reliably. Otherwise, it ends up including remarks about some strings not fully translatable between languages, transliteration and other content. So far, I ended up with:

> You are a highly skilled translation assistant, adept at translating text between languages with precision and nuance. You always reply with translated string only. You do not include transliteration.

**Comment by ilocit** [comment]
The real advantage of GPT over other nMT engines is the customization via e.g. **personas** and **instructions**.
So, I think it would be important to have this as a customizable UI field.

Like this perhaps (this is how [CustomMT ](https://console.custom.mt/) has built it!):

![image](https://user-images.githubusercontent.com/26718215/232735137-954fa399-e288-4ac1-b400-0612325a726f.png)

Definitely (1) and (2), the option to inject a project **glossary** would be super cool, of course! (3)

**Comment by Grigler** [comment]
Is this something that is still being worked on? We're hoping to introduce this to our flow for rapid deployments, with human validation following it

**Comment by Grigler** [comment]
It's true that we could technically get by with nMT, however we think that with being able to supply context to GPT on small strings (a common case in our game) we'd end up with a higher quality initial set of translations

**Comment by nijel** [comment]
As a quick and dirty solution, you can try what has been posted in https://github.com/WeblateOrg/weblate/issues/9009#issuecomment-1507972610. For full integration, I'd like to have this included in the 5.0 release in August, but the feature has not yet been fixed on the roadmap.

**Comment by ilocit** [comment]
@Grigler 
> It's true that we could technically get by with nMT, however we think that with being able to supply context to GPT on small strings (a common case in our game) we'd end up with a higher quality initial set of translations

And that is precisely the challenge and why the above mentioned "quick and dirty" integration won't bring you much benefit.
We would need to look at how to build the "context". 
Is is the 5,10,15 strings before and/or after the current one?
Is it developer comments that are added and made usable in Weblate and the prompt?
Is it a dialog with prompt details for Role, Target Audience, Style, Temperature....
or totally different.

In a game you might want to include the character to add specific tone and slang of that particular character of the game.

Lot's of options. ;-)

**Comment by ilocit** [comment]
FYI, I reached out to @jspricke whom you tagged here, @nijel too. Let's see if and what we can manage until July.

**Comment by nijel** [comment]
@ilocit No, he will most likely start working in July :-).

**Comment by dxdx123** [comment]
May I ask if there has been any progress on this issue?

**Comment by nijel** [comment]
AFAIK, nobody is working on this issue. I'm still stuck in the API waitlist…

**Comment by Grigler** [comment]
Locally in our organisations fork, we have integrated the 3.5-Turbo API call though the results are relatively poor initially as we haven't spent enough time toying with the setup 'System' string given to the AI. Thankfully the model is the only difference in the API usage, so work could begin while we also sit stuck on the waitlist.

In our current usage, we are using the "Explanation" field of the source string as a Context input but I expect we'll be iterating on this for a long time before we get satisfactory results.

**Comment by tipa** [comment]
Based on the work here https://github.com/WeblateOrg/weblate/issues/9009#issuecomment-1507972610 I have fixed and adapted the integration for my needs:
- Removed unneeded URL form in configuration
- Added checkbox in configuration to switch between `gpt-4 `and `gpt-3.5-turbo` (as the latter is **significantly** [cheaper](https://openai.com/pricing) but might be sufficient for certain use-cases)
- Adjusted the prompt:
```
messages = [
    {"role": "system", "content": f"You are a highly skilled translation assistant, adept at translating text to language '{language}' with precision and nuance. You always reply with translated string only. You do not include transliteration."},
    {"role": "user", "content": text}
]
```

[openai.zip](https://github.com/WeblateOrg/weblate/files/13178025/openai.zip)

(Installation hint for noobs like me: Copy `openai.py` file to `/weblate/machinery/` folder and add this line to the `WEBLATE_MACHINERY` list in the `models.py` file in the same directory: `"weblate.machinery.openai.OpenAITranslation",
`

**Comment by jeremi** [comment]
What would be interesting is to use embedding to integrate the glossary and/or other similar translations

**Comment by tipa** [comment]
OpenAI recently released [GTP4-Turbo](https://help.openai.com/en/articles/8555510-gpt-4-turbo) and the Python library was [updated to v1.3.5](https://github.com/openai/openai-python) with some breaking changes to the API, so I updated the openai.py file for Weblate:

[openai.zip](https://github.com/WeblateOrg/weblate/files/13444967/openai.zip)

**Comment by nijel** [comment]
@tipa Can you please share changes you've done to `forms.py` as well? I will create a PR for that if you are not interested in that.

**Comment by nijel** [comment]
WIP integration is here: https://github.com/WeblateOrg/weblate/pull/10479

**Comment by tipa** [comment]
@nijel I will add my `forms.py` changes to the linked PR
