### ISSUE TITLE
Lithuanian lokalization projects may use both 3 and 4 plural forms

### ISSUE THREAD

**Issue by embar-** [WeblateOrg/weblate#901]
Some localization projects of Lithuanian use 3 plural forms, while others use 4 forms (e.g. KDE, openSUSE team)

Reasons:
- Historically Lithuanian in software localization had 3 plural forms:
  - 1, 21, 31, 41, 51...
  - 22, 23, 24... 29, 32... 39, 42...49, 52... 59...
  - 11, 12, 13... 19, 29, 30, 40, 50, 60...
- Arises problem while translating really single 1, because in Lithuanian the same ruler apllay for "1 atnaujinimas" ("1 update") and "21 atnaujinimas" ("21 updates") (and its OK, if there is number "%d atnaujinimas", where %d = 1 or 21 ), but there is error to say "update" for 1 and "update" for 21 (both in Lithuanian, and in English). So some localization teams decided to switch to 4 plural forms to make distinction between 1 and x1 (21, 31...)

Lithuanian KDE team switched in 2009 (if you could read in Lithuanian...):
https://mail.kde.org/pipermail/kde-i18n-lt/2009-September/000324.html
http://kde.akl.lt/?p=148

For openSUSE project transition from 3 to 4 plurals was done in 2010 (in English message):
http://lists.opensuse.org/opensuse-translation/2010-08/msg00001.html

See some discussion in English: https://bugs.launchpad.net/ubuntu/+source/language-pack-kde-lt/+bug/565294

The similar situation was with other languages, like Serbian, Hebrew...

So Webplate should be compatible to both variants of Lithuanian language, at first it should respect plural forms determined in header of PO file.
##

**Comment by stanislav-brabec** [comment]
Related bug: https://github.com/nijel/weblate/issues/900

**Comment by stanislav-brabec** [comment]
Well, Weblate could help to migrate to a new plural form by a definition of plural matrix.
e. g.:
map old 0 to new 0 and 1
map old 1 to new 2
map old 2 to new 3
and mark the result as "needs review" or "fuzzy"

By the way, the plural form set for Lithuanian by Weblate looks very suspicious. It never returns 1.

**Comment by embar-** [comment]
OK!

The correct header for 4 plural forms. Check this.

"Plural-Forms: nplurals=4; plural=(n==1 ? 0 : n%10>=2 && (n%100<10 || n"
"%100>=20) ? 1 : n%10==0 || (n%100>10 && n%100<20) ? 2 : 3);\n"

**Comment by stanislav-brabec** [comment]
The bad plural form appeared here
https://github.com/openSUSE/libstorage/blob/9bc21cacaa729462e060b075b8161f466444ad28/po/lt.po (which was imported from openSUSE LCN SVN trunk, r93031.

So it is definitely not a Weblate fault.

Still, if importing 3-forms lt.po file, it needs either to keep 3-forms plurals, or apply an import matrix mentioned above (it is Lithuanian 3-to-4 migration specific).

It looks that Weblate 2.4 downgraded back to 3-forms Lithuanian plurals:
https://github.com/nijel/weblate/blob/2762e7bb5b1ff3ba2a7da4539c115147792da331/weblate/lang/plurals.txt#L86

**Comment by embar-** [comment]
I will fix in SVN

**Comment by embar-** [comment]
I would be best, if Webplate don't change header at all – accept as it is, like other editors – e.g. Lokalize

**Comment by embar-** [comment]
Hm... 

Something interesting, KDE Plasma 5 and KDE4 translations have this ruler:
"Plural-Forms: nplurals=4; plural=(n==1 ? 0 : n%10>=2 && (n%100<10 || n"
"%100>=20) ? 1 : n%10==0 || (n%100>10 && n%100<20) ? 2 : 3);\n"
(as from https://websvn.kde.org/*checkout*/branches/stable/l10n-kde4/lt/messages/kdelibs/kdelibs4.po and http://websvn.kde.org/*checkout*/branches/stable/l10n-kf5/lt/messages/kde-workspace/kaccess.po )

**Comment by embar-** [comment]
For Leap please use this header:

"Plural-Forms: nplurals=4; plural=(n==1 ? 0 : n%10==1 && n%100!=11 ? 1 : n%"
"10>=2 && (n%100<10 || n%100>=20) ? 2 : 3);\n"

Then all translations of Leap will go into separate branch, I would like to change ruler to (its too late for Leap)

"Plural-Forms: nplurals=4; plural=(n==1 ? 0 : n%10>=2 && (n%100<10 || n"
"%100>=20) ? 1 : n%10==0 || (n%100>10 && n%100<20) ? 2 : 3);\n"

And again: I would be best, if Webplate don't change header at all – respect, accept, and use as it is, like other editors – e.g. Lokalize. But if there is no header, It would be best to use: 

"Plural-Forms: nplurals=4; plural=(n==1 ? 0 : n%10>=2 && (n%100<10 || n"
"%100>=20) ? 1 : n%10==0 || (n%100>10 && n%100<20) ? 2 : 3);\n"

**Comment by embar-** [comment]
I still can not start to translate, because of this bug.
E.g. 
https://github.com/openSUSE/zypper/blob/master/po/lt.po have 4 plural forms,
but while editing, it proposes only 3 plural forms!
And if I try to download https://l10n.opensuse.org/download/zypper/master/lt/ – I see 3 plural forms in header, but 4 plural forms in text! 
And in https://l10n.opensuse.org/projects/zypper/master/lt/ I see warning „C format string does not match source“ for 61 messages!

**Comment by embar-** [comment]
The above https://github.com/WeblateOrg/weblate/issues/901#issuecomment-239606807 is still valid and I can not translate zypper.

**Comment by stanislav-brabec** [comment]
IMHO Weblate still does not support multiple plural forms for a single language.

But the newer version supports admin-level editing of the plural form. So we can force 4-form for all translations, and then convert all po files to a 4-form. (I am not sure, whether a tool exists for it, but it should not be complicated to write it.)

**Comment by embar-** [comment]
Yes, please, force all Lithuanian translation headers in https://l10n.opensuse.org to use:

"Plural-Forms: nplurals=4; plural=(n==1 ? 0 : n%10>=2 && (n%100<10 || n"
"%100>=20) ? 1 : n%10==0 || (n%100>10 && n%100<20) ? 2 : 3);\n"

**Comment by stanislav-brabec** [comment]
Changed in the [openSUSE Weblate](https://l10n.opensuse.org/) admin interface. Change in the code defaults needs to be done by @nijel .

**Comment by nijel** [comment]
Weblate is using whatever is defined in translate-toolkit (well in most cases). So this should be preferably addressed there: https://github.com/translate/translate/blob/master/translate/lang/data.py#L118
