### ISSUE TITLE
Potential O(N^2) problem in spawning celery cleanup_project tasks

### ISSUE THREAD

**Issue by xyzz** [WeblateOrg/weblate#9031]
### Describe the issue

I have a project with a lot of components, around 5 thousand. After doing some maintenance on the git repo, changing/deleting many translation units from many projects, I noticed that celery is severely backlogged.

It looks like when a component changes sufficiently (e.g. lines are deleted), here https://github.com/WeblateOrg/weblate/blob/b847ad3b9f5c08b6d0e7005d2421ee06ea228109/weblate/trans/models/component.py#L2312 it spawns a cleanup_project() task.

However, cleanup_project here https://github.com/WeblateOrg/weblate/blob/b847ad3b9f5c08b6d0e7005d2421ee06ea228109/weblate/trans/tasks.py#L153 does pretty much what it says on the tin i.e. it goes through every component in the project and cleans it up.

So it seems this is now a O(N^2) problem where I have 5k spawned tasks, and every task goes through 5k components (even tho it only needs to do that once?), and there could probably be severe lock contention as well?

In any case I'm wondering if it's possible to change the task to cleanup a specific component, or somehow make it not spawn duplicate tasks when a lot of components get changed.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Git checkout

**Comment by nijel** [comment]
It used to be really project scoped before (4c6e9c80a25e114eb988dead8695f37a2107bf13), but these days it is merely a component scoped. I think it should be actually changed to component scope.
