### ISSUE TITLE
Support for Source String Descriptions in YAML files

### ISSUE THREAD

**Issue by niccokunzmann** [WeblateOrg/weblate#9039]
### Describe the issue

I have a yaml file like this:

```
# Title of the page
# https://mywebsite/page.html#title
page-title: "Main Page"
```

I added these comments in order to allow the users to check out the place where the translations are on the page.

I had a look at https://docs.weblate.org/en/latest/formats.html - yaml section and the table.

Format | Linguality [1] | Plurals [2] | Descriptions [3] | Context [4] | Location [5] | Flags [8] | Additional states [6]
-- | -- | -- | -- | -- | -- | -- | --
YAML files | mono | no | yes | no | no | no

Descriptions are allowed but I do not know how to add these to the file.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Expected behavior

I would expect the comments to turn up here: 
![image](https://user-images.githubusercontent.com/564768/229650427-7088841e-8942-4bc9-a58c-e5c05694a923.png)
But the explanations are empty.

How do I add descriptions/explanations from the yaml file?

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
"Explanation" is provided in Weblate, the comments from the file are shown as "Source string description". See for example https://hosted.weblate.org/translate/weblate/application/cs/?checksum=39b3998dcfe68cbf

**Comment by niccokunzmann** [comment]
Hm. Interesting. It seems like the comments have different meanings depending on how they are made:

```
#. Translators: Shown on wrong answer to the mathematics-based CAPTCHA
#: weblate/accounts/forms.py:513
```

`#.` is a "Source string description"
`#:` is a link to the file. I will see and try out a bit.

I think, I would have liked that explained or linked below the table of what supports description strings.

**Comment by niccokunzmann** [comment]
I wonder where this would be implemented. I think, since PO files can do that already and we have different types of input files, there is probably a modular structure for that that can be kind-of replicated.

**Comment by nijel** [comment]
This syntax is specific to PO files, see https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

Looking at YAML handler, it doesn't seem to parse comments at all: https://github.com/translate/translate/blob/master/translate/storage/yaml.py, so it needs to be implemented there. Weblate will then display comments properly.

**Comment by niccokunzmann** [comment]
I opened https://github.com/translate/translate/issues/4883 so that the implementation part is done here. From my perspective this issue is not resolved now but a documentation issue:

> The documentation claims that yaml files support Descriptions . However there is no documentation about how to add descriptions. This discussion seems to suggest that descriptions are not possible.

To close this issue:
- [ ]  Either remove the `yes` for yaml in the description column of [the table](https://docs.weblate.org/en/latest/formats.html) or add an example of how to add a description in the yaml Section.

Thanks for helping so far. What are your thoughts on this?

**Comment by nijel** [comment]
Correct, I've removed that in 0bc286ed8e68a155223ad266efff2b6fd075f06a.
