### ISSUE TITLE
Context/key is not highlighted in Zen mode:

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#9044]
Context/key is still not highlighted in Zen mode:
![image](https://user-images.githubusercontent.com/49396421/229287852-96bd83eb-454b-4f8b-b8e3-9b6c411b29fd.png)

_Originally posted by @Geeyun-JY3 in https://github.com/WeblateOrg/weblate/issues/8769#issuecomment-1492953905_

**Comment by gtrplair** [comment]
Hi, I would like to contribute to this project and take on this issue.

**Comment by nijel** [comment]
You're welcome.

Zen mode is rendered here: https://github.com/WeblateOrg/weblate/blob/main/weblate/templates/zen-units.html

It should use format_translation template tag to render context.

**Comment by kurabemono** [comment]
Hi, it seems this issue is unassigned. I would ike to take on this issue.

**Comment by nijel** [comment]
@kurabemono You're welcome!

**Comment by kurabemono** [comment]
Hi @nijel,

What is the standard for writing tests for this kind of modification? I looked at the solution to issue #8769 for reference and didn't find a test. Is a visual confirmation (+passing automated tests) okay, or should I write a test in weblate/trans/tests?

Also, apologies if this is the wrong place to ask.
