### ISSUE TITLE
Alerts send on non-existing problems

### ISSUE THREAD

**Issue by isametal88** [WeblateOrg/weblate#9051]
### Describe the issue

Hello,

we are facing something that is probably a configuration issue, but we're not able to figure it out.

We are using Weblate to manage the translation of both our web app and our mobile app, but every single day we receive at least two alerts:

- the web project sends : Repository outdated.
The VCS repository is not up to date with the upstream one. Please merge changes manually or set up hooks to automate this. (of course the hooks are configured, everything is working properly, we never sync the updates manually)

- the mobile project: Parse error
Error message
No such file or directory
Failing file
src/localizations/it.json
(of course also this is wrong: the file exists and it's the source of our translation, which is working)

We have no idea on what to do with this alerts, could somebody help us out?

Thank you very much

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Docker container

**Comment by isametal88** [comment]
Hello Nijel,

no, the updates from our repo is pushed directly. Most of the e-mails show a conflict, but it's not true (we tried also to reset the weblate repo to have a clean state, but nothing has changed).
And the "no such file or directory" is impossible because it's the same localization json weblate uses to read the strings that are being translated :-(

Isaia

**Comment by nijel** [comment]
Maybe two Weblate processes are running with a different configuration?

**Comment by isametal88** [comment]
Hello,

I'll investigate about this, but I don't think that's the case.

Isaia
