### ISSUE TITLE
[RestAPI] How to add translation to already created key?

### ISSUE THREAD

**Issue by infureal** [WeblateOrg/weblate#9073]
### Describe the issue

In documentation I find `/api/translations/(string:project)/(string:component)/(string:language)/units/` endpoit that create a new unit. For example with `ru` language code. Next I try to create translation to this key by using same endpoint but another language code `kk`. But I got `403 Forbidden` message: 
```json
{
    "detail": "Can not add unit"
}
```

Question: **How can I add transation to created unit via RestAPI.**

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Add translation to key for language via `/api/translations/(string:project)/(string:component)/(string:language)/units/` 
2. ...

### Expected behavior

To create translation for existing unit

### How do you run Weblate?

PyPI module

**Comment by Dmytro9999** [comment]
I had the same problem today
```
{
  "detail": "Can not add unit"
}
Status: 403 Forbidden
```
I want to create a new unit for the existing language
