### ISSUE TITLE
Add file format examples to the documentation

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#9078]
### Describe the problem

Some documentation of file formats include examples, but most not. It should be improved.

### Describe the solution you'd like

Almost each file format page should include **Example files** section showing an example of such file (the exception here probably will be binary formats like Excel or IDML).

### Additional context

https://docs.weblate.org/en/latest/formats/json.html already does include this.

For many of formats, the example files can be found in the test suite, so it can be included like in JSON docs: https://github.com/WeblateOrg/weblate/blob/main/docs/formats/json.rst

**Comment by pernelkanic** [comment]
can i take up this issue?

**Comment by nijel** [comment]
Yes, any contribution is welcome.

**Comment by pernelkanic** [comment]
Can I get a brief on what must be done?
