### ISSUE TITLE
Clickable comments in project view

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#9089]
### Describe the issue

Can't click comments here
https://hosted.weblate.org/projects/lomiri/

Can click comments here
https://hosted.weblate.org/projects/lomiri/lomiri-camera-app/ 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Try to click comments from https://hosted.weblate.org/projects/lomiri/

### Expected behavior

Opening all comments for the respective component.
https://hosted.weblate.org/search/lomiri/lomiri-camera-app/?q=has%3Acomment&sort_by=-priority%2Cposition&checksum= , but in the actual editor (so the comments can be read).

### Screenshots

UBPorts/Lomiri
![bilde](https://user-images.githubusercontent.com/13802408/232194191-60911c1c-78f5-4acf-b62e-384725a87e26.png)
UBPorts/Lomiri/CameraApp
![bilde](https://user-images.githubusercontent.com/13802408/232194157-f28ae863-5c48-4b01-a35e-b531e88112dc.png)

### How do you run Weblate?

weblate.org service

### Additional context

Would be nice with (unsolved) comments for the entire project
https://hosted.weblate.org/search/lomiri/?q=has%3Acomment&sort_by=-priority%2Cposition&checksum=
by clicking the top field.
, or language (without any projects selected).

I don't think people are awere comments are language-specific.

**Comment by themohammadsa** [comment]
Hey @comradekingu, I would like to pick this issue up. 

Issue #1:
Unable to click the comment on 'untranslated' links ie. the red ones.

Have a doubt though, Is the above the only issue?

**Comment by nijel** [comment]
@ashishnagar19 You're welcome. Don't hesitate to ask if something is unclear.

**Comment by ashishnagar19** [comment]
sir could you explain additional context more clearly.

**Comment by ashishnagar19** [comment]
i did some changes how to run your website locally so i can see changes

**Comment by ashishnagar19** [comment]
<a href="{{ translate_url }}{{ object.component.project.name }}?q=has:comment#comments" class="btn btn-link" alt="{% trans "Comments" %}">{% icon "pencil.svg" %}
     {% trans "Comments" %}
  </a>
          is this the correct way, i have make changes in list-objecst.html.

**Comment by ashishnagar19** [comment]
I am trying to install the weblate on my system, but in configuration part where i have to copy settings_examples.py to settings.py but settings.py is already there  and it is different from settings_example.py. So tell me how to configure it.

**Comment by comradekingu** [comment]
At a guess you copy the content you want from settings_example.py into settings.py?

**Comment by luzpaz** [comment]
@ashishnagar19 any progress?

**Comment by BC46** [comment]
May I please work on this issue?

**Comment by nijel** [comment]
@BC46 Yes, you're welcome.

**Comment by BC46** [comment]
I have a question. In the source code I can see that the `list-objects-number.html` view component is responsible for determining whether the numbers inside the table should be clickable. Ensuring the `translate_url` is defined on the components page would not only make the comments clickable, but also all other table numbers because those make use of `list-objects-number.html` too. Moreover, this approach would change the folder icon next to each table row into a pencil icon, as specified in `list-objects.html`. So I am wondering, what would be the preferred approach to only make the comments clickable while not making other visual changes? I am open to any suggestions.
