### ISSUE TITLE
Cleanup translation files addon removes keys that exist in the base file

### ISSUE THREAD

**Issue by aotrzonsek** [WeblateOrg/weblate#9102]
### Describe the issue

For some reason the "Cleanup translation files" addon removed a lot of translation keys from properties files (different languages) in one component although the keys were defined in the base file. 

This happened after one developer commited changes to the base file unintentionally changing the file encoding. Weblate marked this component with an error icon, saying that it was unable to determine the encoding of the file. After manually fixing the encoding in the base file in git, Weblate, after synchronising with the git repo two minutes later, removed a large part of the translation keys in various languages.

Weblate version was 4.14.1
The affected component uses one more addon: "Component discovery"

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Can you somehow identify which strings got removed? Did they have anything in common? For example, were they missing from some language files?
