### ISSUE TITLE
Emojis aren't pushed to translations correctly

### ISSUE THREAD

**Issue by ThatOneCalculator** [WeblateOrg/weblate#9115]
### Describe the issue

![image](https://user-images.githubusercontent.com/44733677/232878841-e4d8c1eb-f9fa-458d-8f42-1f3c28cd099d.png)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Translate string with emoji
2. Observe it being turned to unicode code without emoji

### Expected behavior

Emoji gets added

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
What file format do you use? This looks correct for ISO-8859-1 encoded files, you probably want to use UTF-8 instead.

**Comment by ThatOneCalculator** [comment]
The file formal is `.yaml`, it's saved text with  emojis fine before Weblate, but `file -bi en-US.yml` does show `text/plain; charset=us-ascii`

**Comment by nijel** [comment]
It is an issue in the library we're using, I've created it for you: https://sourceforge.net/p/ruamel-yaml/tickets/454/
