### ISSUE TITLE
Typos in /locale/ru/LC_MESSAGES/django.po

### ISSUE THREAD

**Issue by Gadicuz** [WeblateOrg/weblate#9119]
### Describe the issue

There are typos in translation messages /locale/ru/LC_MESSAGES/django.po

https://github.com/WeblateOrg/weblate/blob/main/weblate/locale/ru/LC_MESSAGES/django.po#L9844
```
msgstr[0] "Этот компонент не получал новых переводов в течении %(count)s дня."
msgstr[1] "Этот компонент не получал новых переводов в течении %(count)s дней."
msgstr[2] "Этот компонент не получал новых переводов в течении %(count)s дней."
```
The right spelling is
```
msgstr[0] "Этот компонент не получал новых переводов в течение %(count)s дня."
msgstr[1] "Этот компонент не получал новых переводов в течение %(count)s дней."
msgstr[2] "Этот компонент не получал новых переводов в течение %(count)s дней."
```

https://github.com/WeblateOrg/weblate/blob/main/weblate/locale/ru/LC_MESSAGES/django.po#L10490
```
msgstr[0] "У следующей строки тот же самый контекст и источник."
msgstr[1] "У следующих строк тот же самый контекст и источник."
msgstr[2] "У следующих строк тот же самый контекст и источник."
```
The right spelling is
```
msgstr[0] "У следующей строки те же самые контекст и источник."
msgstr[1] "У следующих строк те же самые контекст и источник."
msgstr[2] "У следующих строк те же самые контекст и источник."
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Other

**Comment by nijel** [comment]
Thanks, I've fixed the first one as that looks more like a typo. 

You can fix also it yourself here:

* https://hosted.weblate.org/translate/weblate/application/ru/?checksum=244ed78cac98e5db
* https://hosted.weblate.org/translate/weblate/application/ru/?checksum=d815ce5ce5b24771
