### ISSUE TITLE
All ''s in the translation result are replaced by &#39

### ISSUE THREAD

**Issue by 66li** [WeblateOrg/weblate#9124]
### Describe the issue

All ''s in the translation result are replaced by &#39

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

weblate.org service

**Comment by 66li** [comment]
my version 4.12.2-2

**Comment by 66li** [comment]
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/37136076/233308732-f7edcd75-abc9-4a1b-a4ce-582574fe73dd.png">

**Comment by 66li** [comment]
i use Google Translate API v3

**Comment by 66li** [comment]
&#39 is the ASCII code for '

**Comment by 66li** [comment]
Can I fix him by modifying a piece of code?

**Comment by 66li** [comment]
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/37136076/233310744-9482b43e-499c-4847-8f0e-17d2bc0ec4b1.png">

**Comment by nijel** [comment]
What did you do when this happened? What file format do you use?

**Comment by 66li** [comment]
How to query file format

**Comment by 66li** [comment]
I solved the problem using this modification

**Comment by 66li** [comment]
https://github.com/WeblateOrg/weblate/pull/9125
