### ISSUE TITLE
Require user’s confirmation of invitation for being added to a project

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#9131]
### Describe the problem

Currently, once a user is added to the project, it can happen without their intention. A wrong setup can result in notification-spam.

### Describe the solution you'd like

- require user’s confirmation in the e-mail invitation to be added as a participant
- let instance admins to turn this off server-wide
- `nice to have` see pending invitations in https://`weblate`/accounts/profile/

**Comment by nijel** [comment]
https://github.com/WeblateOrg/weblate/issues/9261 might make sense to implement together with this.
