### ISSUE TITLE
Disabling xml-invalid for the project

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#9168]
### Describe the issue

How to disable xml-invalid quality checks for an entire project in docker. It was recently automatically added to the entire project. How can you do it the fastest? The whole operation will probably take several days.

I've been reading the documentation but only found information about QA exclusions that apply to a standard weblate installation, not in containers.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1 Go to string translation
2 See new quality checks, completely redundant throughout the project

### Screenshots

![image](https://user-images.githubusercontent.com/39633242/234497002-3b1ceccb-8d68-4a85-a04c-3b51993b56b1.png)

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
Add `ignore-xml-invalid` to component flags.
See https://docs.weblate.org/en/latest/user/checks.html#xml-syntax and https://docs.weblate.org/en/latest/admin/projects.html#translation-flags

**Comment by tomkolp** [comment]
> Add `ignore-xml-invalid` to component flags. See https://docs.weblate.org/en/latest/user/checks.html#xml-syntax and https://docs.weblate.org/en/latest/admin/projects.html#translation-flags

I know about the flag, but how do I add it to 3000 components at once?

**Comment by tomkolp** [comment]
![image](https://user-images.githubusercontent.com/39633242/234555412-42eae1b6-f322-4d6f-9f2a-0b14debd92cf.png)
We've always used <<player{text/text}>> , this check came out a few weeks ago for the first time.

**Comment by tomkolp** [comment]
I added to docker-compose:
WEBLATE_REMOVE_CHECK: weblate.checks.markup.XMLValidityCheck
I restarted the containers.
The name of this check in the list of all changed its name from Polish to English. When I click on xml-invalid I get the page not found message.
The following lines have a check only now in English.
Do I still need to force the rechecking somehow or is this some kind of bug?
If I have to force it, how can I do it for all components?
![image](https://user-images.githubusercontent.com/39633242/234558137-3b25ebf6-6409-439d-bc1b-7efc1143d46f.png)
![image](https://user-images.githubusercontent.com/39633242/234558564-fa24985d-2300-4e36-b256-a33bc1a13a94.png)
![image](https://user-images.githubusercontent.com/39633242/234558682-722edc94-2e3c-45c5-a517-301b78dc9724.png)

**Comment by tomkolp** [comment]
> I added to docker-compose: WEBLATE_REMOVE_CHECK: weblate.checks.markup.XMLValidityCheck I restarted the containers. The name of this check in the list of all changed its name from Polish to English. When I click on xml-invalid I get the page not found message. The following component have a check only now in English. Do I still need to force the rechecking somehow or is this some kind of bug? If I have to force it, how can I do it for all components? ![image](https://user-images.githubusercontent.com/39633242/234558137-3b25ebf6-6409-439d-bc1b-7efc1143d46f.png) ![image](https://user-images.githubusercontent.com/39633242/234558564-fa24985d-2300-4e36-b256-a33bc1a13a94.png) ![image](https://user-images.githubusercontent.com/39633242/234558682-722edc94-2e3c-45c5-a517-301b78dc9724.png)

**Comment by nijel** [comment]
You can force updating checks manually using https://docs.weblate.org/en/latest/admin/management.html#updatechecks, without that, the checks are updated once in a month (see https://docs.weblate.org/en/latest/admin/config.html#background-tasks).

**Comment by tomkolp** [comment]
I just wasn't sure if this behavior (message page cannot be displayed) is normal behavior after excluding checks.
I have enabled check recalculation for all components. Initially, I see that "xml-invalid" is disappearing. Seeing the speed of the operation, it will be completed in a few days.

Thanks for leading me to a solution.

**Comment by nijel** [comment]
This turned out to be a bug in the XML check, I've just fixed that in 32220fc58819369df772aa1a4476821c9a7c78e0
