### ISSUE TITLE
UI: Rename maintaince "Push" button based on project/component settings

### ISSUE THREAD

**Issue by buhtz** [WeblateOrg/weblate#9176]
### Describe the issue

In the maintaince section there is a button labeld "Push". This doesn't make sense when the component is setup to do PullRequests to the upstream repo.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Setup "PullRequest" and look into maintaince section.

### Expected behavior

Name the button "Push" when the component is setup with push behavior.
Name it "Create PullRequest" when PR behavior is setup.

Or just name it "Sync with upstream repo" in all cases.

### Screenshots

![image](https://user-images.githubusercontent.com/11861496/235092610-970551f7-b961-4972-acee-d218354a7f9d.png)

### How do you run Weblate?

Other

**Comment by buhtz** [comment]
https://github.com/WeblateOrg/weblate/discussions/8535

**Comment by nijel** [comment]
Well, it does both push (to a fork/branch) *and* create a pull/merge request in that case. But it makes sense to have a more verbose text here (I've already rewritten some of that page in 9c8dfd0d3a283804ccd07c7cbff0b19af0d55c6e).

**Comment by buhtz** [comment]
> Well, it does both push (to a fork/branch) _and_ create a pull/merge request in that case.

From a UI designers perspective it doesn't matter what "it does" but what the "users understand what happens".
On a shell I can do `git push`. That is a "Push".
On a code hoster I can create a PullRequest (or MergeRequest on GitLab). That is a "PullRequest".
Two totally different things from a users perspective.

A good UI should reflect the users perspective and/or guide him gently around it there is a need to.

**Comment by nijel** [comment]
I'm not saying that the current look is good, but that it only describes part of the operation :-).

**Comment by nijel** [comment]
Revamped repository maintenance: 

![image](https://user-images.githubusercontent.com/212189/235113663-4fe32e05-498d-4cb1-85ab-142752b398e2.png)

**Comment by buhtz** [comment]
What changed? I still see the "Push" button here.

**Comment by nijel** [comment]
There is a service specific description next to it, for Gitea it is defined here:

https://github.com/WeblateOrg/weblate/blob/20f06c4638ab442376e592155fecfaa963def62d/weblate/vcs/git.py#L1117

The button is still called "Push" as I don't see a better short naming here. Suggestions are welcome.
