### ISSUE TITLE
Add protocol configuration to VCS credentials

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#9179]
### Describe the problem

Rigt now VCS configuration such as [GITLAB_CREDENTIALS](https://docs.weblate.org/en/latest/admin/config.html#gitlab-credentials) assume user is using `https`. While this is true in most cases, user might be using `http`.

### Describe the solution you'd like

Add `protocol` field to all `CREDENTIALS` settings and use that to generate service URL instead of hardcoded `https`.

### Describe alternatives you've considered

Forcing users to `https` is safer approach and does not require code changes.

### Additional context

https://github.com/WeblateOrg/weblate/discussions/9161

**Comment by nijel** [comment]
Your description is correct. The only thing missing is that `protocol` setting should default to `https` if not specified.

**Comment by DavidNguyen2002** [comment]
Sounds great. I'll start working on this now.
