### ISSUE TITLE
Sort strings by "last updated"

### ISSUE THREAD

**Issue by buhtz** [WeblateOrg/weblate#9215]
### Describe the problem

The background is I would like to see the latest actievis in a language. Based on the last commits I can see that someone did translations in a specific language but I'm not able to see what was translated.

### Describe the solution you'd like

When looking into the list of strings I would like to sort them by updated or modified date.

The background is I would like to see the latest actievis in a language. Based on the last commits I can see that someone did translations in a specific language but I'm not able to see what was translated.

### Additional context

#9212

**Comment by nijel** [comment]
The problem is that the last update timestamp is not stored separately. It is the recent change in a separate table, what makes it unsuitable for ordering right now.

**Comment by Geeyun-JY3** [comment]
If implemented, I suggest showing the “Last updated” date and time in the “String information” panel of the editor as well.

**Comment by comradekingu** [comment]
https://hosted.weblate.org/projects/remmina/remmina/nb_NO/#history
or
https://hosted.weblate.org/zen/remmina/remmina/nb_NO/?offset=&q=&sort_by=-timestamp&checksum=
is probably the closest for now.

@Geeyun-JY3 
Maybe it only makes sense to show that it has been edited if there are more than the one entry in the translation history?

**Comment by Geeyun-JY3** [comment]
> Maybe it only makes sense to show that it has been edited if there are more than the one entry in the translation history?

I think it is unnecessary.

**Comment by comradekingu** [comment]
I think if the current editing history is presented in better fashion it can be combined and alert users to the fact once
any subsequent editing has been done. Colouring could work.

Presents only valid and useful information, as opposed to burdening the user.
