### ISSUE TITLE
COMPRESS_OFFLINE = True might be quirky/broken on 4.17

### ISSUE THREAD

**Issue by BhaaLseN** [WeblateOrg/weblate#9218]
### Describe the issue

I just installed a new VM with weblate 4.15 (because I had existing configuration files I wanted to go from), and once that worked I jumped to 4.17.

But the first thing that popped in my face was missing CSS files, despite running `weblate compress` after performing the described update steps.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Set `COMPRESS_OFFLINE = True` in `settings.py`
2. Run `weblate compress` to make sure JS and CSS are prepared correctly
3. Reload the webserver (in my case: `apache2ctl restart`) and Celery (in my case: `service celery-weblate restart`)
4. Open the main page in a web browser

Step 4 unfortunately fails to load some CSS, which is missing.

### Expected behavior

Main page (and all other pages) load correctly

### How do you run Weblate?

Git checkout

### Weblate versions

```
$ weblate list_versions
 * Weblate: weblate-4.17
 * Django: 4.2.1
 * siphashc: 2.1
 * translate-toolkit: 3.8.6
 * lxml: 4.9.2
 * Pillow: 9.5.0
 * nh3: 0.2.11
 * python-dateutil: 2.8.2
 * social-auth-core: 4.4.2
 * social-auth-app-django: 5.2.0
 * django-crispy-forms: 2.0
 * oauthlib: 3.2.2
 * django-compressor: 4.3.1
 * djangorestframework: 3.14.0
 * django-filter: 23.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.11.0
 * rapidfuzz: 3.0.0
 * openpyxl: 3.1.2
 * celery: 5.2.7
 * django-celery-beat: 2.5.0
 * kombu: 5.2.4
 * translation-finder: 2.15
 * weblate-language-data: 2023.4
 * html2text: 2020.1.16
 * pycairo: 1.23.0
 * pygobject: 3.44.1
 * diff-match-patch: 20200713
 * requests: 2.28.2
 * django-redis: 5.2.0
 * hiredis: 2.2.3
 * sentry_sdk: 1.22.2
 * Cython: 0.29.34
 * misaka: 2.1.1
 * GitPython: 3.1.31
 * borgbackup: 1.2.4
 * pyparsing: 3.0.9
 * pyahocorasick: 2.0.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.1.0
 * Python: 3.9.16
 * Git: 2.30.2
 * psycopg2-binary: 2.9.6
 * ruamel.yaml: 0.17.24
 * Redis server: 6.0.16
 * PostgreSQL server: 13.10
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache
 * Email setup: django.core.mail.backends.dummy.EmailBackend:
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 5.10.0-22-amd64 (x86_64)
```

### Additional context

Setting `COMPRESS_OFFLINE = False` fixes this, but it worked fine before (up until at least 4.15). I did _not_ try 4.16 so I cannot say if it was an issue there or not. 

The request that fails is this one (which is referenced from the main page generated thru `wsgi.py`):
```
GET /static/CACHE/css/output.2cde8abaeada.css HTTP/1.1
Host: weblate
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Accept: text/css,*/*;q=0.1
Accept-Language: en-US,en;q=0.8,de-DE;q=0.5,de;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://weblate/
Connection: keep-alive
Cookie: translate-tab=#translations; sessionid=wu5azqvdophzcql4i5ugmedrd04m8dig; django_language=en
Sec-Fetch-Dest: style
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
Pragma: no-cache
Cache-Control: no-cache
-----
HTTP/1.1 404 Not Found
Date: Tue, 09 May 2023 13:29:28 GMT
Server: Apache/2.4.56 (Debian)
Content-Length: 270
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1
```

There is no file named `output.2cde8abaeada.css` in the configured cache folder; and `manifest.json` doesn't list it either.
```
$ ls -l /home/weblate/data/static/CACHE/css/
total 320
-rw-r--r-- 1 weblate weblate 151350 May  9 15:28 output.e98aff4ced4c.css
-rw-r--r-- 1 weblate weblate 176043 May  9 15:28 output.ece24c888a44.css
```
In fact, this file doesn't exist anywhere in `/home/weblate`. Other files (like the JS used) work as expected.

Running `weblate compile` again does nothing noticable, its output is always the same:
```
$ weblate compress
Compressing... done
Compressed 6 block(s) from 244 template(s) for 2 context(s).
$ weblate compress
Compressing... done
Compressed 6 block(s) from 244 template(s) for 2 context(s).
```

`weblate collectstatic` at least prints that it didn't have to do anything:
```
$ weblate collectstatic --noinput

0 static files copied to '/home/weblate/data/static', 390 unmodified.
```

Note that I reverted from `STATIC_ROOT = os.path.join(CACHE_DIR, "static")` back to `STATIC_ROOT = os.path.join(DATA_DIR, "static")` because I thought that was the issue; but it turned out this wasn't related. I'm still running it in the `DATA_DIR` at this point, which is why the paths might seem off.

**Comment by BhaaLseN** [comment]
Thats on `mod_wsgi`. And I restarted both Apache2 and the Celery service, multiple times.

**Comment by BhaaLseN** [comment]
I finally got around to try this again, and so far it _is_ working. Not sure what changed since last time, except for a machine reboot.

🤷

**Comment by BhaaLseN** [comment]
Reopening this after updating and _again_ seeing this issue (current config can be seen in #11029, except for `weblate check --deploy` because thats currently broken for me.) I'm now on 5.4, with the following configuration; but I also tested this on the intermediate upgrade step to 5.0.2, with the same results (yet different file names/hashes from the minification):
```py
# (hopefully) relevant sections from settings.py
# None of those settings should be different from settings_example.py at this point.
DATA_DIR = "/home/weblate/data"
CACHE_DIR = f"{DATA_DIR}/cache"

STATIC_ROOT = os.path.join(CACHE_DIR, "static")

COMPRESS_OFFLINE = True
```

Opening any page (in my case, I default to the management page to look at the Performance report, Alerts and Repository checks immediately after an upgrade) shows broken styles due to CSS and JS files not being found:
```
GET /static/CACHE/css/output.a64decb4f431.css HTTP/1.1
Host: weblate
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0
Accept: text/css,*/*;q=0.1
Accept-Language: en-US,en;q=0.8,de-DE;q=0.5,de;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://weblate/
Connection: keep-alive
Cookie: translate-tab=#translations; django_language=en; sessionid=7m2nxnnch636no0q1265afdyd50vonro
Sec-Fetch-Dest: style
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
Pragma: no-cache
Cache-Control: no-cache
-----
HTTP/1.1 404 Not Found
Date: Fri, 16 Feb 2024 11:23:48 GMT
Server: Apache/2.4.57 (Debian)
Content-Length: 270
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1
```

```
GET /static/CACHE/css/output.b2cdc5489794.css HTTP/1.1
Host: weblate
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0
Accept: text/css,*/*;q=0.1
Accept-Language: en-US,en;q=0.8,de-DE;q=0.5,de;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://weblate/
Connection: keep-alive
Cookie: translate-tab=#translations; django_language=en; sessionid=7m2nxnnch636no0q1265afdyd50vonro
Sec-Fetch-Dest: style
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
Pragma: no-cache
Cache-Control: no-cache
-----
HTTP/1.1 404 Not Found
Date: Fri, 16 Feb 2024 11:23:48 GMT
Server: Apache/2.4.57 (Debian)
Content-Length: 270
Keep-Alive: timeout=5, max=98
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1
```

Those are just two examples that simply won't load. Apache 2 (with `mod_wsgi`) was restarted multiple times just to make sure, same for the `weblate-celery` service (which _shouldn't_ have any effect on this); and I re-ran `weblate collectstatic --noinput --clear` followed by `weblate compress` multiple times to confirm.

Locally, the situation looks like this:
```
weblate@weblate:~/data$ pwd
/home/weblate/data
weblate@weblate:~/data$ find . -name output.a64decb4f431.css
./cache/static/CACHE/css/output.a64decb4f431.css
weblate@weblate:~/data$ find . -name output.b2cdc5489794.css
./cache/static/CACHE/css/output.b2cdc5489794.css
```

As far as I can tell there, that seems to be correct. It is using the configured `STATIC_ROOT` directory when running `weblate compress`.

However, _unless_ I copy them to the configured `DATA_DIR` (appending `"static"`) the page stays broken:
```
weblate@weblate:~/data$ cp -r cache/static/CACHE/ static/
```

Somewhere there seems to be a disconnect between the configured `STATIC_ROOT` directory (which is effectively at `/home/weblate/data/cache/static`, yielding the existing file path `/home/weblate/data/cache/static/CACHE/css/output.a64decb4f431.css`) and what the website attempts to load from something below `DATA_DIR` (while apparently ignoring `CACHE_DIR`; which is effectively at `/home/weblate/data/static` without the `cache/` in between, yielding the supposed file path `/home/weblate/data/static/CACHE/css/output.a64decb4f431.css` that makes things work when I move the `CACHE` folder over.)

Note that older versions (pre-4.17, which was when I originally raised this issue) did not have `CACHE_DIR` and my workaround back when was to redefine `STATIC_ROOT` back to the old behavior:
```py
STATIC_ROOT = os.path.join(DATA_DIR, "static")
```
Maybe this hints at a location somewhere internally that still uses the old approach or so; at least I couldn't find any config files (Apache 2, Celery service/config, `settings.py` itself) that would do that either intentionally or unintentionally because I put it there.

Anything _else_ that I could check on my end? The working copy is clean, no extra files or anything (other than a `.python-version` file from `pyenv`) that would affect this to be best of my knowledge.

**Comment by nijel** [comment]
What is served as `/static/` is configured in Apache, so maybe your configuration is wrong there? Seem like it is pointing to a different folder.

Moreover, did you configure `COMPRESS_OFFLINE_CONTEXT` and `COMPRESS_CSS_HASHING_METHOD`?
 
https://github.com/WeblateOrg/weblate/blob/149fb8c3062f672c09203bb2d56c133a3c2ad7e1/weblate/settings_example.py#L805-L808

**Comment by BhaaLseN** [comment]
> What is served as `/static/` is configured in Apache, so maybe your configuration is wrong there? Seem like it is pointing to a different folder.

Yep, looks like that was the problem here. I compared my config with `weblate/examples/apache.conf`, and kinda stopped reading after line 19: https://github.com/WeblateOrg/weblate/blob/777d8d2c2a36af753b3d5facfd0ba6101c8faa5a/weblate/examples/apache.conf#L19

After taking another closer look, the _comment_ is outdated (and should probably be `CACHE_DIR/static` rather than `DATA_DIR/static`) but the _directives_ are recent/correct. My config was _consistent_ but just _wrong_ in the end.

I just updated this in my config and things are now working as they should:
```diff
-    # DATA_DIR/static/
+    # CACHE_DIR/static/
-    Alias /static/ /home/weblate/data/static/
+    Alias /static/ /home/weblate/data/cache/static/
-    <Directory /home/weblate/data/static/>
+    <Directory /home/weblate/data/cache/static/>
         Require all granted
     </Directory>
```
There's just too many moving parts to keep everything in mind; and perhaps one of the reasons why Docker is so much more attractive these days.

Thanks a ton 👍 

> Moreover, did you configure `COMPRESS_OFFLINE_CONTEXT` and `COMPRESS_CSS_HASHING_METHOD`?

Nothing other than the defaults (with the exception of `COMPRESS_OFFLINE`:
```
weblate@weblate:~$ grep -i -n compress weblate/weblate/settings.py
176-# List of finder classes that know how to find static files in
177-# various locations.
178-STATICFILES_FINDERS = (
181:    "compressor.finders.CompressorFinder",
410-# Django and Weblate apps
411-INSTALLED_APPS = [
448:    "compressor",
939:# Django compressor offline mode
940:COMPRESS_OFFLINE = True
941:COMPRESS_OFFLINE_CONTEXT = "weblate.utils.compress.offline_context"
942:COMPRESS_CSS_HASHING_METHOD = "content"
```

...but I guess this is obviously irrelevant now that I found my apache issue.

**Comment by nijel** [comment]
I've updated the examples in a697f36e90.
