### ISSUE TITLE
Label description and tooltip

### ISSUE THREAD

**Issue by ZiYueCommentary** [WeblateOrg/weblate#9227]
### Describe the problem

Sometimes a label name cannot describe detail.

I have a label called "Menu bar item", and I want to tell translators that they can add the access key to their translations.

### Describe the solution you'd like

Adding `title` to the html element.

### Screenshots

![2023-05-13 202857](https://github.com/WeblateOrg/weblate/assets/63241389/4d209210-2805-40ce-8846-ba57fd11958e)
![Snipaste_2023-05-13_20-37-00](https://github.com/WeblateOrg/weblate/assets/63241389/50d13cfe-9189-4f1c-8d8c-61fb8b831876)
![Snipaste_2023-05-13_20-38-21](https://github.com/WeblateOrg/weblate/assets/63241389/94bbdbf3-1b93-490a-84d5-a76d0d437a29)

**Comment by harriebird** [comment]
Hi guys, check my PR #11907 for this issue.
