### ISSUE TITLE
Invitations without email login

### ISSUE THREAD

**Issue by Bubu** [WeblateOrg/weblate#9261]
### Describe the problem

Our weblate installation at https://translate.codeberg.org/ has all user accounts backed by the gitea installation at codeberg.org.  

`AUTHENTICATION_BACKENDS = ("social_core.backends.gitea.GiteaOAuth2", "weblate.accounts.auth.WeblateUserBackend",)`

This makes the invite functionality not work at all and confusing to users and their invited contributors that try to use them.

### Describe the solution you'd like

I don't really see a way to make invites work if the user account that needs to be created is on a seperate platform, so I'd instead like to just disable this functionality in the UI completely.

### Additional context

Report from a user at codeberg: https://codeberg.org/Codeberg/Community/issues/1027

**Comment by nijel** [comment]
Actually, it makes sense to have invitations even without e-mail authentication:

* To add people to projects
* To invite people to start using Weblate

The invitations can still work:

* User receives e-mail
* Signs in using a third-party platform
* The created account is linked with the invitation

This really needs https://github.com/WeblateOrg/weblate/issues/9131 as well.
