### ISSUE TITLE
Broken link to privacy policy when accepting new terms of service

### ISSUE THREAD

**Issue by yvanzo** [WeblateOrg/weblate#9272]
### Describe the issue

When logging into a Weblate instance where the legal terms have been changed, the user is appropriately redirected to the form `/legal/confirm/` which includes the new Terms of Service in a pre-scrollable div.

In this context, the (new) link to the privacy policy from the section 5 of the ToS is not working: It resolves to `None`. It seems that the template `{{ privacy_url }}` doesn’t resolve correctly in this context.

In other contexts, this link works fine:

* From `/legal/terms/`, it resolves to `/legal/privacy/`.
* From the all-in-one `/en/terms/`, it resolves to `#privacy`.

Template for the link: https://github.com/WeblateOrg/wllegal/blob/2023.3/wllegal/templates/legal/documents/tos.html#LL101C211-L101C235

I’m reporting this bug to `wllegal` as it occurs since its latest version `2023.3`.
However I don’t know if it has to be addressed in `wllegal` and/or `weblate`.
I’ve searched for similar issues in both repositories.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to `/legal/confirm/`?… (with an account having accepted old legal terms only, or using a new account?)
2. Scroll to the section 5 about personal data
3. Click on the link to the privacy policy
4. Get page not found from `/legal/confirm/None`

### Expected behavior

4. Get `/legal/privacy/`, possibly in a new tab.

**Comment by nijel** [comment]
Fixed in 45ddceedb66b256f75f491c2fe42ee4bd5b10980
