### ISSUE TITLE
Gettext without headers: all translations marked fuzzy

### ISSUE THREAD

**Issue by rix0rrr** [WeblateOrg/weblate#9290]
### Describe the issue

We are using Hosted Weblate. 

Because we're noticing that when we are running gettext update commands locally (using `pybabel`, in case that matters), there are frequent merge conflicts in the time stamps that are in the `.po` file headers.

So I thought I would be clever and run `pybabel` with `--omit-header`, so it doesn't emit the magic `msgid ""` entry that has the metadata headers attached.

It looks like in response, Weblate has marked all my translations `fuzzy`, completely reordered all translations in the file, and has replaced them with the original English versions. I had to do some git trickery to get back to a workable state.

This was a surprise to me. Is this expected? 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Have a number of `.po` files translated via Weblate.

Then run:

```
pybabel extract -F babel.cfg -o messages.pot . --no-location --sort-output --omit-header
pybabel update -i messages.pot -d translations -N  --no-wrap --omit-header
```

Specifically, you can see the change I made in this PR: https://github.com/hedyorg/hedy/pull/4304

### Expected behavior

I expected fewer conflicts. Instead I got more :).

### How do you run Weblate?

weblate.org service

**Comment by rix0rrr** [comment]
Here is the commit where Weblate starts marking a bunch of translations as fuzzy: https://github.com/hedyorg/hedy/pull/4297/commits/93f65c11d3a27296c9fdf0b929cb614c8497773d


Which follows right on the heels of https://github.com/hedyorg/hedy/pull/4297/commits/27f41d86a0bbf6bc38bcfbb178684c8adb3ced0a where I remove all the headers from po files.

![2023-05-23 at 19 09](https://github.com/WeblateOrg/weblate/assets/524162/09d47f50-211b-43c4-b62c-df4be9c83a63)

**Comment by nijel** [comment]
It is not changing existing translations to be fuzzy, it adds missing strings as fuzzy. This is done by add-on, which you have installed. See https://docs.weblate.org/en/latest/admin/addons.html#prefill-translation-with-source
