### ISSUE TITLE
Differentiate translations created by Prefill add-on

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#9294]
### Describe the problem

It’s hard to monitor changes in translations and not lose some strings when using the `Prefill translation with source` add-on. Controlling the target status should be an option.

### Describe the solution you'd like

EDIT: https://github.com/WeblateOrg/weblate/issues/9294#issuecomment-1564017068

~Let the user set the target status of the strings pre-filled by this add-on like it is possible with `mode` in `Automatic translation`.~

~`Untranslated` and `Needs editing` statuses are desired.~

**Comment by ashishnagar19** [comment]
do we need to customize the translations part with editing option.

**Comment by nijel** [comment]
@ashishnagar19 Can you please clarify what you mean?

**Comment by ashishnagar19** [comment]
I am trying to say if strings does'nt get translated or there is some error in target, do we need to give users a option to edit further.

**Comment by orangesunny** [comment]
> I am trying to say if strings does'nt get translated or there is some error in target, do we need to give users a option to edit further.

This issue is about letting the user adjust what status will be used for the translations pre-filled by this add-on: https://docs.weblate.org/en/latest/admin/addons.html#prefill-translation-with-source

The default (current) status is `Needs editing`.


After consultations, we defined a better way to implement this and solve problems that led to this issue. Strings pre-filled by this add-on will have label `Prefilled with source`

**Comment by orangesunny** [comment]
All translations created by this add-on will be labeled automatically with `Prefilled with source`

**Comment by nijel** [comment]
Thinking more about this, adding label is not the right approach here. The proper solution really is splitting "Needs editing" into substates, as described in #2240.
