### ISSUE TITLE
Easily remove project/component-specific notifications setting

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#9302]
### Describe the problem

Once the project or component has customized notifications setting applied, there is no comfortable way to remove the project/component form the list of tabs and make it watched/unwatched.

### Describe the solution you'd like

A cross next to the name of the notifications setting tab that removes the item-specific notifications settings. UI notification is shown as a confirmation.

Messages:
- When the project or component is not in `Watched projects` as well:
_Item-specific notifications settings removed._

- When the project is part of the user’s `Watched projects` as well:
_Project-specific notifications settings removed. Settings for the Watched projects are used now._

**Comment by Johnson591144** [comment]
Are you people adding symbols or additional prefix to my phone number? My device was working awesome yesterday. Now it's acting up again. Certain calls going to voicemail
