### ISSUE TITLE
Different components in same language update all componants files

### ISSUE THREAD

**Issue by polter05** [WeblateOrg/weblate#9308]
### Describe the issue

Hi,

We have gettext translations. In each language, one or more domains are set (one or more translations).
![image](https://github.com/WeblateOrg/weblate/assets/68990960/ba62d508-86aa-4276-be25-5fd54a9c752f)

For general
![image](https://github.com/WeblateOrg/weblate/assets/68990960/ac9f3d7b-8088-4c44-8da4-6cf8b36e9858)

For specifique1 in nld
![image](https://github.com/WeblateOrg/weblate/assets/68990960/4d03ae65-9c61-42ce-af40-26ab67958f3a)

The same things for specifique2

The problem is when I update a translation for general, the translation of specifique1 or specifique2 are update too. When I update translation of specifique1, the others domain (general and specifique2) are also updated.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Update the gerenal nld translation
2. Commit the udpate
3. Push the update
4. In the gitlab MR, all the po file of the language are udpate

### Expected behavior

Juste the po file of the componant must be updated

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/68990960/76e23c41-c712-4311-a3bb-8949056493ca)

### How do you run Weblate?

Docker container

### Weblate deploy checks

```shell
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail ([Errno -2] Name or service not known), please check EMAIL_* settings.
	HINT: https://docs.weblate.org/en/weblate-4.17/admin/install.html#out-mail
?: (weblate.E012) The server e-mail address should be changed from its default value
	HINT: https://docs.weblate.org/en/weblate-4.17/admin/install.html#production-email
?: (weblate.E013) The "From" e-mail address should be changed from its default value
	HINT: https://docs.weblate.org/en/weblate-4.17/admin/install.html#production-email

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.17/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.17/admin/backup.html

System check identified 8 issues (1 silenced).
```

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/projects.html#allow-translation-propagation

**Comment by polter05** [comment]
> See https://docs.weblate.org/en/latest/admin/projects.html#allow-translation-propagation

Tks !!!!!! 👍
