### ISSUE TITLE
Fix narrow columns

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#9319]
### Describe the issue

Columns in the editor tabs (history, other occurrences, suggestions...) are now rendered entirely by browser, which leads to some of them being narrow and unusable.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. open a long string/defined by a long key in the editor
2. open Automatic suggestions or Nearby strings tabs
3. see the mess

### Expected behavior

Use wrapping or line-breaking, probably together with a mouseover tooltip. Don’t leave the behavior to the browser.

### Screenshots

<img width="583" alt="image001" src="https://github.com/WeblateOrg/weblate/assets/23450011/519eca88-9f81-45e2-866f-efbe03985d36">

from Safari Safari 16.3 on macOS, but it’s similar everywhere.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Does it still happen? This was supposed to be fixed in 27f75bad5a3b341b655ffe7dde43764bf6af8649, see #8502.
