### ISSUE TITLE
Status widgets ask for help even when translated 100%

### ISSUE THREAD

**Issue by Wuzzy2** [WeblateOrg/weblate#932]
Some status widgets (and the Weblate webpage) still ask people for help translating when is is done  100%.

Namely, the banners of size 287×66 and the “landing page”/“engage page” (whatever it is called) you get on when you follow the link on the image.
The banner of size “286×66” says something like “100% complete, help us”.
The “engage page” has a lengthy text about helping but it is pointless with a 100% complete translation.
Maybe some different text should be displayed in the case of 100%.

How to reproduce: Just surf a little bit on Hosted Weblate (https://hosted.weblate.org/) and choose a project where any language is 100% done, then choose that language, and then select “Widgets” from the “Tools” fake drop-down menu.
##

**Comment by nijel** [comment]
The help can be with review or fixing typos, so it's not really pointless. But having nicer wording could help.

**Comment by nijel** [comment]
The widgets now do not include the text at all:

![287x66-white](https://user-images.githubusercontent.com/212189/59684958-60d5cb00-91db-11e9-9c62-4b2d6670bc97.png)

The landing page is also simplified: https://hosted.weblate.org/engage/weblate/

So I think it's time to close this :-).
