### ISSUE TITLE
Zen mode does not work for anonymous users, throws JSON error

### ISSUE THREAD

**Issue by emmapeel2** [WeblateOrg/weblate#9331]
### Describe the issue

When users without login try to make changes in Zen mode, they get a JSON error.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

- If you are logged in from hosted.weblate you need to log out.
- Go to https://hosted.weblate.org/zen/tor/tor-browser-user-manual/ach/?offset=1&q=state%3A%3Ctranslated
- Make a change and move to the following string

There is a red message from weblate:

`SyntaxError: JSON.parse: unexpected character at line 7 column 1 of the JSON data`

And the changes are not saved.

### Expected behavior

The changes should be saved, even if as suggestions.

### Screenshots

![error-zen cleaned](https://github.com/WeblateOrg/weblate/assets/11485015/84e32024-09e8-44ca-93aa-85daa669c497)

### How do you run Weblate?

weblate.org service

**Comment by emmapeel2** [comment]
Nice!

It is better now with the message 'Forbidden', but it would be even better if the edits of non-logged users could suggest terms in Zen, is that not possible?

I would like that feature because I want to have an ' Improve translation'  button on our website, and send the people that clicks this button to a Zen interface with the strings of that page in particular (using the string location value to search). But I am afraid people will submit translations that are going to be lost.

Anonymous users can suggest on the normal view, is it not possible to allow them to suggest in Zen view?

**Comment by nijel** [comment]
I don't think it's a good idea. When automatically making suggestions here, it would behave different for authenticated and unauthenticated users. So, when user doesn't notice he got signed out, he would be suddenly making suggestions without really noticing.
