### ISSUE TITLE
"Reused Translation" is not working properly

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#9336]
### Describe the issue

I have marked a string as "Reused Translation" how do I display all related strings?
Recheck has been triggered in 2% of components and there are already about 5000 results. Ultimately, this check will have tens of thousands of results to manually search for results using a search engine.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Open string with "Reused Translation" check
2. What next? Search for identically translated ones in the search engine using the translation?

### Expected behavior

Weblate displays links to strings related to the string where the error occurs.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/39633242/3ffd7e5e-2187-4165-b231-d7f7d7397685)
![image](https://github.com/WeblateOrg/weblate/assets/39633242/45b6a802-d7ba-42eb-a167-57ff86325c75)
EDIT:
I used the search engine to find all the strings with the translation "X" . All found strings have the same source text. What is meant by "source" in this check? Is it the text "source" or the context+ "source"?
![image](https://github.com/WeblateOrg/weblate/assets/39633242/25a29b3c-2760-4724-a731-130b19b72042)

### How do you run Weblate?

weblate.org service

### Weblate versions

<html>
<body>

4.18-dev — 9a73f791e9cccced6f4b6fef4c473eb54174fd16
--

</body>
</html>4.18-dev — [9a73f791e9cccced6f4b6fef4c473eb54174fd16](https://github.com/WeblateOrg/weblate/commits/9a73f791e9cccced6f4b6fef4c473eb54174fd16)

**Comment by tomkolp** [comment]
4.18-dev — ee09ac24373b69ee2a62e63ee16b281fc58386ac 
I upgraded weblate, forced recheck.  After a few hours I have over 270 000 "reused translations".  Strings with the same source and translation, but a different context, are still marked.
You can check how it looks like https://weblate.eso-spolszenie.eu
@nijel

**Comment by nijel** [comment]
Should be better since b1e290f9736fa674a77b15bdfd186a95d60a28ac

**Comment by tomkolp** [comment]
https://weblate.eso-spolszczenie.eu/search/?q=Porozmawiaj+z+Darienem+Gautierem&sort_by=-priority%2Cposition&checksum=

**Comment by nijel** [comment]
It can't look for a substring (it used MD5 for the lookup). I've added display of the other source strings in b18a2fabb52e8e59f04fd0ea755f7b36e127181b to make it easier to find such strings. They will also be shown on the other “Other occurrences” tab since f188963030d1fc5f772099120799c5ba90877182.
