### ISSUE TITLE
recurring task for linked components

### ISSUE THREAD

**Issue by Heshmatkhah** [WeblateOrg/weblate#9352]
### Describe the issue

I have a repository containing 656 modules
each module has an i18n directory that contains po and pot files.
here is my repository root:
```
app-1/
├─ module-1/
│  ├─ i18n/
│  │  ├─ en.po
│  │  ├─ module-1.pot
├─ module-2/
│  ├─ i18n/
│  │  ├─ en.po
│  │  ├─ module-2.pot
├─ module-3/
│  ├─ i18n/
│  │  ├─ en.po
│  │  ├─ module-3.pot
app-2/
├─ module-4/
│  ├─ i18n/
│  │  ├─ en.po
│  │  ├─ module-4.pot
├─ module-5/
│  ├─ i18n/
│  │  ├─ en.po
│  │  ├─ module-5.pot

```
I have created a project for each app and a component with a git repository for my first component (assume `module-1`)
then all other 655 modules are using the internal weblate repository `weblate://app-1/module-1` in their own projects

I also shared the glossary of `app-1` with all other apps.

Whenever I do anything in my modules, it triggers a task `updating linked project` then it checks all components and these updated projects cause triggering the same task again and which makes my instance unusable, and it's not able to commit/ push changes to my repository.

I don't know how many times the task is triggered, but it never ends running this and I should stop the service and run it again.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. create a component with git repository
2. create a couple of other components with the internal repository to the first one
3. try to change something, it will trigger `updating linked project` multiple times

### Expected behavior

check if the task is already triggered, don't trigger it again.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/10222466/ef66f72c-ad1d-41ff-bcff-e1a8c7d7d3ae)

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.17
 * Django: 4.2
 * siphashc: 2.1
 * translate-toolkit: 3.8.6
 * lxml: 4.9.2
 * Pillow: 9.5.0
 * nh3: 0.2.11
 * python-dateutil: 2.8.2
 * social-auth-core: 4.4.2
 * social-auth-app-django: 5.2.0
 * django-crispy-forms: 2.0
 * oauthlib: 3.2.2
 * django-compressor: 4.3.1
 * djangorestframework: 3.14.0
 * django-filter: 23.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.11.0
 * rapidfuzz: 3.0.0
 * openpyxl: 3.1.2
 * celery: 5.2.7
 * django-celery-beat: 2.5.0
 * kombu: 5.2.4
 * translation-finder: 2.15
 * weblate-language-data: 2023.4
 * html2text: 2020.1.16
 * pycairo: 1.23.0
 * pygobject: 3.44.1
 * diff-match-patch: 20200713
 * requests: 2.28.2
 * django-redis: 5.2.0
 * hiredis: 2.2.2
 * sentry_sdk: 1.21.1
 * Cython: 0.29.34
 * misaka: 2.1.1
 * GitPython: 3.1.31
 * borgbackup: 1.2.4
 * pyparsing: 3.0.9
 * pyahocorasick: 2.0.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.1.0
 * Python: 3.11.3
 * Git: 2.30.2
 * psycopg2: 2.9.6
 * psycopg2-binary: 2.9.6
 * phply: 1.2.6
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.6.0
 * boto3: 1.26.124
 * zeep: 4.2.1
 * aeidon: 1.12
 * iniparse: 0.5
 * mysqlclient: 2.1.1
 * Mercurial: 6.4.2
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 7.0.11
 * PostgreSQL server: 15.3
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.scarfbank.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.18.0-425.19.2.el8_7.x86_64 (x86_64)

### Weblate deploy checks

```shell
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail ((535, b'Incorrect authentication data')), please check EMAIL_* settings.
	HINT: https://docs.weblate.org/en/weblate-4.17/admin/install.html#out-mail

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.17/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.17/admin/backup.html

System check identified 6 issues (1 silenced).
```

**Comment by nijel** [comment]
If you're using Git squash add-on, it was most likely addressed by ad0dcae3ac.

**Comment by nijel** [comment]
Ah, there is also an issue with DEFAULT_ADDONS and repo-scoped add-ons - it installs them on every component, instead of being there just once. You can uninstall them on all but the main component and the situation should improve.

**Comment by nijel** [comment]
Should be fixed by a012ffab55d6db9c98f767ca2e569a747e4d3bd0

**Comment by Heshmatkhah** [comment]
Thank you a lot, Is there any way to use these changes right now till they appear in the next release?

**Comment by nijel** [comment]
You can install from git or use `bleeding` tag of the Docker container to get the latest changes.
