### ISSUE TITLE
Restrict contact form to signed in users

### ISSUE THREAD

**Issue by eloquence** [WeblateOrg/weblate#9353]
### Describe the problem

The "contact your admin" form on our Weblate instance is starting to attract spam from crawlers.

### Describe the solution you'd like

It would be good to restrict it to signed in users to mitigate spam.

### Describe alternatives you've considered

CAPTCHA is already enabled but CAPTCHAs are increasingly useless.

**Comment by nijel** [comment]
If you are using LOGIN_REQUIRED, you can remove the contact URL from LOGIN_REQUIRED_URLS_EXCEPTIONS.

**Comment by nijel** [comment]
The contact form is open intentionally – it is linked from the page in case the user has trouble registering. There should be some way such user can get in touch...

**Comment by nijel** [comment]
You need to include other URLs from the default settings, so that at least login page works.

**Comment by perrfect** [comment]
> You need to include other URLs from the default settings, so that at least login page works.

I want to disable Weblate contact form in general.
I'm using `WEBLATE_REQUIRE_LOGIN=1` and don't have any other options.
I don't understand which other URLs from default settings I should include.
Could you please write some examples?

**Comment by perrfect** [comment]
> I've added example to the documentation: [b5ca320](https://github.com/WeblateOrg/weblate/commit/b5ca3200df81643afbdb17dee85a8e04b31d3f63)

Thank you.
