### ISSUE TITLE
Some languages have no suggestion from ModernMT

### ISSUE THREAD

**Issue by urbalazs** [WeblateOrg/weblate#9357]
### Describe the issue

I have a self hosted Weblate and a ModernMT subscription. Some languages get suggestions from ModernMT, others don't.

Works: ar_SA, bg, ca, cs, da, de, et, fi, fr_CA, fr, gl, he, hi, hr, hu, id, it, ja, lt, lv, mk, ms, nb_NO, nl, pl, ro, ru, sk, sl, sv, sw, th, uk, vi

Does not work: el, en_CA, en_GB, es, es_CO, es_MX, fa, ko, pt, pt_BR, sr_Cyrl, tr, zh_Hans, zh_Hant

When I call the API from command line, I get translation.

```
curl -X POST \
    -H "X-HTTP-Method-Override: GET" \
    -H "Content-Type: application/json" \
    -H "MMT-ApiKey: $MY_API_KEY" \
    --data '{"source": "en", "target":"el", "q":["Deploy ACLs"]}' \
    --no-progress-meter \
    --compressed \
    "https://api.modernmt.com/translate" |\
    jq
```

```
{
  "status": 200,
  "data": [
    {
      "translation": "Ανάπτυξη ACL",
      "billedCharacters": 11,
      "characters": 11,
      "billed": true
    }
  ]
}
```

```
curl -X POST \
    -H "X-HTTP-Method-Override: GET" \
    -H "Content-Type: application/json" \
    -H "MMT-ApiKey: $MY_API_KEY" \
    --data '{"source": "en", "target":"sr_Cyrl", "q":["Deploy ACLs"]}' \
    --no-progress-meter \
    --compressed \
    "https://api.modernmt.com/translate" |\
    jq
```

```
{
  "status": 200,
  "data": [
    {
      "translation": "Распореди АЦЛ-ове",
      "billedCharacters": 11,
      "characters": 11,
      "billed": true
    }
  ]
}
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Add you ModernMT API key to Weblate.
2. Ask a translation for language `de` (German). This works fine.
3. Ask a translation for language `el` (Greek). The is no translation suggestion.

### Expected behavior

All languages should get translation suggestion from ModernMT.

### How do you run Weblate?

Docker container

### Weblate versions

4.16.4

**Comment by urbalazs** [comment]
I found that Persian language code (`fa` in Weblate) can be replaced by `pes` based on the [language list of ModernMT](https://www.modernmt.com/api/#languages).

@nijel can you please add this mapping to [language_map](https://github.com/WeblateOrg/weblate/blob/main/weblate/machinery/modernmt.py#L22-L26) of ModernMT?

```diff
    language_map = {
+       "fa": "pes",
        "sr_Cyrl": "sr",
        "zh_Hant": "zh-TW",
        "zh_Hans": "zh-CN",
    }
```

**Comment by nijel** [comment]
Done, thanks for suggestion.
