### ISSUE TITLE
User doesn't see button for manage.

### ISSUE THREAD

**Issue by dolgovas** [WeblateOrg/weblate#9370]
### Describe the issue

User with management access doesn't see button with wrench, but he can access there via link /manage/

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Create custom role admins with permissions to manage users and user management interface
2. Create custom team with admins role
3. Try to manage users

### Expected behavior

I want to user button instead uri to access to management interface

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/43605609/387a450a-a476-4747-a32b-5d9a8cb0db0d)
![image](https://github.com/WeblateOrg/weblate/assets/43605609/6ae5fcfc-a66b-439d-bf59-3a3209fa97cc)

### How do you run Weblate?

Docker container

### Weblate versions

#  docker compose exec --user weblate weblate weblate list_versions
 * Weblate: 4.17
 * Django: 4.2.1
 * siphashc: 2.1
 * translate-toolkit: 3.8.6
 * lxml: 4.9.2
 * Pillow: 9.5.0
 * nh3: 0.2.12
 * python-dateutil: 2.8.2
 * social-auth-core: 4.4.2
 * social-auth-app-django: 5.2.0
 * django-crispy-forms: 2.0
 * oauthlib: 3.2.2
 * django-compressor: 4.3.1
 * djangorestframework: 3.14.0
 * django-filter: 23.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.11.0
 * rapidfuzz: 3.0.0
 * openpyxl: 3.1.2
 * celery: 5.2.7
 * django-celery-beat: 2.5.0
 * kombu: 5.3.0
 * translation-finder: 2.15
 * weblate-language-data: 2023.4
 * html2text: 2020.1.16
 * pycairo: 1.23.0
 * pygobject: 3.44.1
 * diff-match-patch: 20200713
 * requests: 2.28.2
 * django-redis: 5.2.0
 * hiredis: 2.2.3
 * sentry_sdk: 1.25.0
 * Cython: 0.29.35
 * misaka: 2.1.1
 * GitPython: 3.1.31
 * borgbackup: 1.2.4
 * pyparsing: 3.0.9
 * pyahocorasick: 2.0.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.1.0
 * Python: 3.11.3
 * Git: 2.30.2
 * psycopg2: 2.9.6
 * psycopg2-binary: 2.9.6
 * phply: 1.2.6
 * ruamel.yaml: 0.17.31
 * tesserocr: 2.6.0
 * boto3: 1.26.146
 * zeep: 4.2.1
 * aeidon: 1.12
 * iniparse: 0.5
 * mysqlclient: 2.1.1
 * Mercurial: 6.4.3
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 7.0.11
 * PostgreSQL server: 15.3
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: inbound.mail.bcsvm.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://:PWD@cache:6379/1, redis://:PWD@cache:6379/1, regular
 * Platform: Linux 5.15.0-71-generic (x86_64)

### Weblate deploy checks

```shell
#  docker compose exec --user weblate weblate weblate check --deploy
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.17/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.17/admin/backup.html

System check identified 2 issues (1 silenced).
```

**Comment by nijel** [comment]
There are definitely some rough edges in site-wide permissions, developing those is not yet fully complete. Related to https://github.com/WeblateOrg/weblate/issues/2363
