### ISSUE TITLE
Don't use variable from ENV

### ISSUE THREAD

**Issue by dolgovas** [WeblateOrg/weblate#9371]
### Describe the issue

Hi! I want to change some setting in saml config, but it doesn't work like in example. Why?
from https://github.com/WeblateOrg/weblate/blob/main/weblate/settings_docker.py
```
            "attr_name": os.environ.get("WEBLATE_SAML_ID_ATTR_NAME", "full_name"),
            "attr_username": os.environ.get(
                "WEBLATE_SAML_ID_ATTR_USERNAME", "username"
            ),
            "attr_email": os.environ.get("WEBLATE_SAML_ID_ATTR_EMAIL", "email"),
```
but weblate steel use default settings...
```
'attr_name': 'full_name', 'attr_username': 'username', 'attr_email': 'email'
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Run official docker-compose

**Comment by nijel** [comment]
Are you actually running a container which supports these? The attribute overrides were added in 170fb50f395, which is currently only in the `bleeding` tag. I guess we should add documentation here...
