### ISSUE TITLE
Define custom code block detection and checks

### ISSUE THREAD

**Issue by Heshmatkhah** [WeblateOrg/weblate#9385]
### Describe the issue

Hi
I run Google API v3 auto-translation on my project, which has some errors.
I have some special strings that I have to translate:

- `<i class="fa fa-align-justify fa-4x" role="img" aria-label="Multiple lines" title="Multiple Lines"/>`
   The `Multiple lines` should be translated, but it's part of the tag. Can I tell this to the weblate?
    ![Screen Shot 2023-06-12 at 11 13 05 AM](https://github.com/WeblateOrg/weblate/assets/10222466/0802590b-38b8-4e38-8eae-29dfb7298c7b)

- Can I define a custom check for weblate that check, "if there is an escaped test in target string that doesn't exist on the source, give me a warning?" 
  - `'%s' is not a valid period. Supported formats are "21/12/2022", "Q1/2022", "12/2022", and "2022".`: the check should be failed, because all of those `&quot;`
     ![Screen Shot 2023-06-12 at 11 32 41 AM](https://github.com/WeblateOrg/weblate/assets/10222466/8e5b5b32-5172-416e-afc7-271b23e3b0ea)
  - `&lt;?xml version="1.0" encoding="utf-8"?&gt;`: the check should be filled because the source contains `&gt;` and `&lt;` but the target contains `&quot;`
    ![Screen Shot 2023-06-12 at 11 40 32 AM](https://github.com/WeblateOrg/weblate/assets/10222466/161b699e-df0c-433d-9940-1d291d8531fe)

- `{{ object.company_id.name }}: Your intervention is scheduled {{ 'from the ' + format_datetime(object.planned_date_begin, tz=object.partner_id.tz, lang_code=object.partner_id.lang) + ' to the ' + format_datetime(object.planned_date_end, tz=object.partner_id.tz, lang_code=object.partner_id.lang) if object.planned_date_begin and object.planned_date_end else '' }}`
   this is a Python format string that will be passed twice through the format function (`{{` -> `{` -> formatted), or a Jinja template. this is because of the template system that the codebase uses.
   **can I define custom code tag detection for weblate so it detects `{ ..... }` and `{{ ..... }}` as code?**
    (selected part is the translation of the last `else`)
    also previously mentioned check should failed for this because of `&#39;`
    ![Screen Shot 2023-06-12 at 12 06 35 PM](https://github.com/WeblateOrg/weblate/assets/10222466/35556acc-8e55-4007-adac-9eb71fa29465)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

- It's not an issue

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
You can write own checks, see https://docs.weblate.org/en/latest/admin/checks.html#writing-own-checks.

Instead of that, I'd suggest making the strings less complex. This will make them easier to replace and less likely to break in different ways. Especially, the code does not belong to the translations.

For example, the last string could be:

```
{{ object.company_id.name }}: Your intervention is scheduled from the {{ planned_date_begin }} to the {{ planned_date_end }}
```
