### ISSUE TITLE
Login loop

### ISSUE THREAD

**Issue by Puoh** [WeblateOrg/weblate#9387]
### Describe the issue

Hello,

Everytime a new user tries to access our weblate page it just instantly reloads and sends you back to the login screen. The screen that redirects says "New registrations are turned off". According to sign-in logs in our azure ad, the attempts to sign in to weblate are successful.

Users who have had access since before can still access it without issues.

Not sure this is the place to ask, but I've just been assigned to getting it fixed, and we have no documentation for this.

![msedge_rt9gEsfYnX](https://github.com/WeblateOrg/weblate/assets/101170738/69f0a86d-0a94-4162-97ae-7044f73f38ab)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Go to https://translate.lime.tech

attempt to log in with our azure ad account

it successfully logs in, then redirects back to login page.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/101170738/b4456b00-8945-4cfb-b597-ffa1a4217fce)

### How do you run Weblate?

Other

**Comment by nijel** [comment]
As you have paid support for this, the better place to ask is care@weblate.org :-). Anyway, I've just fixed that.

PS: It was needed to turn on https://docs.weblate.org/en/latest/admin/config.html#std-setting-REGISTRATION_OPEN
