### ISSUE TITLE
Coloring isuue of the mobile navigation bar’s hamburger button (☰)

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#9391]
### Describe the problem

The color of the mobile navigation bar’s hamburger button (☰) should not be black in the dark theme. It is almost invisible on Hosted Weblate. 

### Describe the solution you'd like

The color of the mobile navigation bar’s hamburger button should be consistent in both light and dark themes.
Considering the color of the navigation bar is customizable, I suggest that the color of the mobile navigation bar’s hamburger button should also be customizable.

BTW, I think the border of the hamburger button can be removed, or make it consistent with the color of the hamburger button. Current color scheme looks strange while the instance customizes the color of the navigation bar, such as  [Codeberg Translate](https://translate.codeberg.org/) 

### Screenshots

:  
![Screenshot_20230613103626](https://github.com/WeblateOrg/weblate/assets/49396421/e8d04940-6cd9-4319-aeae-e65d679043ae)
[Codeberg Translate](https://translate.codeberg.org/): 
![Screenshot_20230613132951](https://github.com/WeblateOrg/weblate/assets/49396421/3a8ceffe-9a2d-4ec0-abc7-8637f6478345)

**Comment by Geeyun-JY3** [comment]
The hamburger button is still black in the dark theme: 
![Screenshot_20230615091752.jpg](https://github.com/WeblateOrg/weblate/assets/49396421/d9d05971-5ce3-4566-b1a8-fbec2f41ee73)

**Comment by nijel** [comment]
What browser do you use? It works correctly for me in Firefox and Chrome.

**Comment by Geeyun-JY3** [comment]
Chrome on Android

**Comment by nijel** [comment]
Ah, probably a caching issue, as the dark theme CSS is not collected with others. Try reloading the page.

**Comment by nijel** [comment]
I've just deployed fix for that...

**Comment by Geeyun-JY3** [comment]
Why I cannot enter Hosted Weblate with my account signed in? It is been several hours.

**Comment by nijel** [comment]
Because I made a typo which breaks Weblate with the dark theme. It should be fixed now.
