### ISSUE TITLE
'format': 'File format not supported'

### ISSUE THREAD

**Issue by razor313** [WeblateOrg/weblate#9392]
### Describe the issue

I've created a new project by importing translated files but once I want to download as the `aresource` (Android strings files) via `wlc` I face this error: `Error: HTTP error 400: Bad Request {'format': 'File format not supported'}`

Seems I have to change the project settings but I don't know how!

Please guide me on this matter, thanks in advance.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

I've tried downloading it with other formats such iOS but it didn't work!

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
Omit `format` parameter to skip the conversion, see https://docs.weblate.org/en/latest/api.html#get--api-translations-(string-project)-(string-component)-(string-language)-file-

**Comment by razor313** [comment]
@nijel Thank you for replying but It doesn't work properly, the output file isn't XML file since it doesn't have this 
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name" translatable="false">APP_NAME</string>
</resources>
```
I need to convert it into `XML` file since the files are in `XLIFF` format on the weblate. I've tried the following commands to convert/download them as XML format but none of them have worked.

`wlc download PROJECT_NAME/COMPONENT_NAME/en -c strings -o en-strings.xml`

`wlc download PROJECT_NAME/COMPONENT_NAME/en -c aresource -o en-strings.xml`


Meanwhile, could you please take a look at #7943?

**Comment by razor313** [comment]
I changed to `XLIFF Translation File` but I am still not able to set Monolingual base language file.

<img width="971" alt="Screenshot 2023-06-13 at 16 31 27" src="https://github.com/WeblateOrg/weblate/assets/26047366/872c97ad-1f7c-44c5-9e66-124c071af88d">
<img width="1031" alt="Screenshot 2023-06-13 at 16 31 38" src="https://github.com/WeblateOrg/weblate/assets/26047366/06923455-fe4f-4c6d-902b-7f4f3feda363">


also, I get this `Error: HTTP error 400: Bad Request {'format': 'File format not supported'}` once try to download/convert it to android format (xml/aresource)
