### ISSUE TITLE
Complaints from users after upgrade from version 3.9

### ISSUE THREAD

**Issue by MatjazSega** [WeblateOrg/weblate#9395]
### Describe the problem

Hello,

We've been using Weblate 3.9 for a long time before upgrading to the latest version a few weeks ago. As an administrator, I am very happy with the new version, as it is faster and more reliable. Users, on the other hand, have had a few complaints, saying that translation process was faster in older version.

There are 2 main issues:

1. When searching translations, you select translated strings subset and enter source string. If you then choose to search amongst untranslated strings via dropdown, search string is wiped.
![image](https://github.com/WeblateOrg/weblate/assets/54701245/5ee69afc-3bc8-4b42-bb7f-db625e9cb69e)
![image](https://github.com/WeblateOrg/weblate/assets/54701245/2021678e-34c3-4c52-a999-dc8263c23024)

In 3.9, when you opened search window and changed the translations subset, it retained the rest of the search string:
![image](https://github.com/WeblateOrg/weblate/assets/54701245/a9674c80-b5c0-47e4-bf3c-0cd45fe60f76)

2. Applying existing translations requires more work than it did in 3.9. In 3.9, under tab "Other occurences", there was a button "Use this translation":
![image](https://github.com/WeblateOrg/weblate/assets/54701245/b4e61c27-e53c-4480-b5b4-7dae8cb51b65)

In newest version, you need to select a radio button of the translation you want to use, then scroll all the way down (there can be a lot of equal translations), and then click "Apply selected translation to all propagated strings" button:
![image](https://github.com/WeblateOrg/weblate/assets/54701245/77b17396-ef3d-472e-a136-7986ef3b294f)

### Describe the solution you'd like

Regarding problem number 1, we would expect that changing the subset of translations you want to search in would only change the "translated:=XX" part of the search string instead of wiping it.

Regarding problem number 2, users would like to have one-click option of applying existing translation, like in 3.9

**Comment by nijel** [comment]
1. The dropdown contains predefined queries, it intentionally overrides the selection. More comfortable UI is covered in https://github.com/WeblateOrg/weblate/issues/3063
2. The button did something else than most people have expected, please see https://github.com/WeblateOrg/weblate/issues/3715

**Comment by MatjazSega** [comment]
Hey. Sorry, I just didn't find time to come to this sooner.

1. I read through the issue you mentioned. I did not understand all that you were discussing, but I agree that search needed to be change and that current implementation is generally better.
I still think that dropdown behavior is a bit weird though. Having a dropdown in front of the search filter leads user to believe that it functions alongside the search filter (like "Sort by"), while in fact it wipes search filter and adds "state" parameter. This way, It actually works much the same as the rest of the parameters helpers below, with addition of wiping the text.
In my opinion, more consistent design would be to have state dropdown parameter helper below the search filter, with the rest of the parameter helpers, much in the same way as "has" parameter helper. For resetting the search filter, "Reset filter" button would be added to the right of "Sort by" dropdown.
That said, it is definitely not a huge issue and users will get used to it. It just seemed appropriate to state our users' opinion and my developer view on it.
2. I read through the issue you mentioned and I am not sure what most users thought the button does, as it did exactly the thing we expected it to do - use the selected string as target on current translation. Maybe other users have different translation processed and had trouble with the wording of "Use this translations" button, but i think that could be solved some other way. The only good reason for moving the button below I can think of is lack of space in line for a "Use this translation" button, but that could be solved by smaller textless button.
Again, not a deal-breaking issue, but you can understand that it's hard to "sell" new version of a tool to users, when it changes often used one-click operation to click-scroll-scroll-...-scroll-click operation.

**Comment by nijel** [comment]
>  use the selected string as target on current translation. 

No, it used it on all propagated translations. The behavior is still the same, it is just the UI being more verbose to clarify what it does. I think it's the propagation what confuses it, but that's another complex topic (see https://github.com/WeblateOrg/weblate/issues/3166).
