### ISSUE TITLE
No highlighting of delimiters in placeholders

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#9406]
### Describe the issue

https://l10n.elementary.io/translate/files/files/es/?checksum=158eab1af1b7f04b#comments

Here `'` is used as a flag character which allows us to show the , delimiter depending on the number, e.g. 1,000,000 items. From $ man printf.3:

   Flag characters
       The character % is followed by zero or more of the following flags:
       ……

       '      For  decimal  conversion (i, d, u, f, F, g, G) the output is to be grouped with thousands' grouping characters if the locale information indicates any.  (See setlocale(3).)  Note that many versions of gcc(1) cannot parse
              this option and will issue a warning.  (SUSv2 did not include %'F, but SUSv3 added it.)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Add delimiter
2. Have it be part of the highlighting
3. Trick translators into believing it needs to be included

### Expected behavior

`%`'`d` instead of `%'d` would be expected(?)

### How do you run Weblate?

weblate.org service

### Weblate versions

Using Weblate 4.17

### Additional context

Maybe it could include something in "info" by default to explain the delimiters used in various languages,
or use the defaults for any given language?

**Comment by nijel** [comment]
`%'d` is highlighted in both source and translation, that looks correct. Note that `'` flag uses locale specific separator, so if it is used in the source string, it should be IMHO used in the translation as well.

**Comment by comradekingu** [comment]
OK, that seems fine.
