### ISSUE TITLE
Unclear documentation about screenshot discovery feature

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#9413]
### Describe the issue

Hi,

I'm excited about the new feature for discovering automatically screenshots in a repo in 4.18 (thanks for that!) but the doc about it (in https://docs.weblate.org/en/latest/admin/projects.html#screenshot-file-mask) is not quite clear and we have a disagreement when talking about it.

So I just want to confirm: this is configured per component and the mask aims at matching a translation key, right? 
For example if I have a component `foo` with a translation key `my.translation.key` and a mask  `/foo/translations/screenshots/*.png` then it will search for `/foo/translations/screenshots/my.translation.key.png`. Is that correct? 

I'll improve the doc with an example if it's right.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Read the documentation and discuss it.

### How do you run Weblate?

PyPI module

**Comment by nijel** [comment]
@surli Can you please review https://github.com/WeblateOrg/weblate/pull/9434?
