### ISSUE TITLE
Request for Customizable Machine Translation Engines through WEBLATE_MACHINERY  

### ISSUE THREAD

**Issue by dxdx123** [WeblateOrg/weblate#9415]
### Describe the problem

When I add the following configuration in settings-override.py, it doesn't work:
WEBLATE_MACHINERY += ('weblate_chatgpt.chatgpt.ChatGPTTranslation',)"

Therefore, I can only add a Python script under weblate/machinery/, but this approach is quite inelegant. I hope to add it as an additional component instead

### Describe the solution you'd like

I am writing to request a feature that could enhance the flexibility of this project. I would like to suggest a new method to add custom machine translation engines, which could be realized via a mechanism similar to CHECK_LIST += [...].

It would be beneficial if WEBLATE_MACHINERY  could be made more customizable, allowing us to integrate our own machine translation engines easily. This could increase the versatility of the service and adapt to more diverse usage scenarios.

Could you please consider this enhancement for a future release? I believe that this feature would be a great addition to the project.

Looking forward to your feedback.

### Describe alternatives you've considered

in settings-override.py file，I want to add a customize plugin，like this：
WEBLATE_MACHINERY += ('weblate_chatgpt.chatgpt.ChatGPTTranslation',)

**Comment by nijel** [comment]
The settings needs to be expanded in settings_docker.py, same as we do with checks. Then you would be also able to use https://docs.weblate.org/en/latest/admin/install/docker.html#changing-enabled-apps-checks-add-ons-or-autofixes

**Comment by dxdx123** [comment]
Could I kindly inquire whether I should extend WEBLATE_MACHINERY in settings_docker.py? Would there be a need for additional code modifications, by any chance?

**Comment by nijel** [comment]
Just include WEBLATE_MACHINERY with all built-in engines and add  `modify_env_list(WEBLATE_MACHINERY, "MACHINERY")` to allow modifying it from the environment.
