### ISSUE TITLE
Allow GenerateMoAddon to export fuzzy strings

### ISSUE THREAD

**Issue by jorrit** [WeblateOrg/weblate#9418]
### Describe the problem

We use the 'fuzzy' marking to mark texts that need to be reviewed by our translators. However, we would like to use those texts in our application as soon as possible.

Right now, the addon `GenerateMoAddon` is programmed such that only units with a state greater than or equal to `STATE_TRANSLATED` are exported. 

### Describe the solution you'd like

It would be great for us if a configuration item could be added that allows us to export units with state `STATE_FUZZY` or greater.

### Describe alternatives you've considered

I could investigate using the review workflow, but this is a project-wide settings and I would like to use this on a component level.

**Comment by nijel** [comment]
It should be easy to add this as an option, it used to include all strings due to a bug until 899a7421b2ad388a24b9b328eba5d7230722ba22.

**Comment by jorrit** [comment]
I'd think it would just be a checkbox 'Add fuzzy strings' that changes `STATE_TRANSLATED` to `STATE_FUZZY` in the implementation.

**Comment by YashTote** [comment]
I have come up with a solution. Just wanted to check wether its working. Are there any sample repositories or translation files so that I could test the solution? I was unable to find any that has fuzzy strings.

**Comment by jorrit** [comment]
I don't see the field, I think this is because it wasn't added to `self.helper.layout`.

**Comment by nijel** [comment]
Good catch, added it in 40161dfa2e.

**Comment by jorrit** [comment]
Thanks so much, again!
