### ISSUE TITLE
Is v.4.18.1 available in docker?

### ISSUE THREAD

**Issue by pedrocerejo-truphone** [WeblateOrg/weblate#9433]
### Describe the issue

I would like to use v4.18.1 but I don't know if the tag 4.18 is that version.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Go to [dockerhub](https://hub.docker.com/r/weblate/weblate/tags)
Find the tag 4.18.

I don't know if it correspondes to 4.18.1

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
I've just pushed the tag for it, it will be published in hours. But the most important bugfix of 4.18.1 (dark theme CSS handling) was already included in the 4.18.0.1 container as a backported patch.

**Comment by pedrocerejo-truphone** [comment]
Thank you very much!
