### ISSUE TITLE
Nginx returns "Bad Request - Error parsing headers" for headers larger than 8k

### ISSUE THREAD

**Issue by roboptics** [WeblateOrg/weblate#9437]
### Describe the issue

If a request is sent with a header larger than 8k, the error "400 error - Request Header Or Cookie Too Large" is shown by nginx. This is a common situation for the cookies header when weblate is hosted under the same domain as other applications.
This can be fixed by setting:

```
large_client_header_buffers 8 32k;
```

in nginx configuration, for instance in /etc/nginx/sites-enabled/weblate.

After adding the setting aboce to the nginx configuration, the error on the title in shown "Bad Request - Error parsing headers: 'limit request headers fields size'".
I tried to set additional settings to nginx, but nothing works. Probably this is beeing thrown by some other component.
Did not find any information on the documentation or posted on how to increase the maximum header size for weblate.

Any help is appreciated.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Add a header to the domain where weblate is hosted that is larger than 8k.
2. Try to access weblate

### Expected behavior

The errors in the description are shown

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/17877466/9c95a6e5-ee57-4c70-9f14-d33ab8ebc978)

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
> ### How do you run Weblate?
> 
> weblate.org service

Most likely not as you are changing the nginx configuration.

The error message is coming from gunicorn (https://github.com/benoitc/gunicorn/blob/add8a4c951f02a67ca1f81264e5c107fa68e6496/gunicorn/http/message.py#L103), adjust its configuration.
