### ISSUE TITLE
Move "Start new translation" button to the top

### ISSUE THREAD

**Issue by buhtz** [WeblateOrg/weblate#9441]
### Describe the problem

Some [projects do have a long list of languages](https://translate.codeberg.org/projects/backintime/common/).

The button "Start new translations" at the end of that list disappear somehow because of that. The problem is that the users don't understand and know that they are able themselves to add new languages.

### Describe the solution you'd like

Just move that button to the top of that list.

**Comment by nijel** [comment]
User languages are shown as one-click items on top of the list, so it is straightforward to add languages the user translates to:

![image](https://github.com/WeblateOrg/weblate/assets/212189/18c85cff-5190-42a7-9c66-8f8083d52bf8)

**Comment by buhtz** [comment]
Thanks for your reply. I've never saw something like this.

Not sure what I see there. It seems that it is an admin-view where the admin can decide to add a language some user has created and worked on?

That is not the step I'm talking about. I mean the user. The user want to add a new langauge. The button for this is at the end of the list.

![image](https://github.com/WeblateOrg/weblate/assets/11861496/fca5162d-4fb3-466c-98aa-2375d207e3ea)

**Comment by comradekingu** [comment]
Move to top and don't leave the page to do it?

**Comment by nijel** [comment]
I don't see a reason to move a rarely used button to a prominent place. Users will have configured their languages and those are shown on top. So, these can easily add their language already.

Such change would focus on admins, and those already have other add buttons at the bottom of the list (for example adding new component).

On the other side, I think it makes sense to add this to the top + dropdown.

**Comment by buhtz** [comment]
> I don't see a reason to move a rarely used button to a prominent place. Users will have configured their languages and those are shown on top. So, these can easily add their language already.
> 
> Such change would focus on admins, and those already have other add buttons at the bottom of the list (for example adding new component).
> 
> On the other side, I think it makes sense to add this to the top + dropdown.

I assume we do misunderstand each other.
You say in the beginning "I don't see a reason to move..." and in the end the opposite "...I think it makes sense to add this to the top". And which "dropdown" do you mean? We never talked about a dropdown.

**Comment by nijel** [comment]
I've rearranged the UI for adding in dcdd417ed354cd22733c356e3c3065a78a77163a. There is now a plus icon in the list header to add a new language/component/translation.
