### ISSUE TITLE
Correct way to use "%" as a printable character in a python string

### ISSUE THREAD

**Issue by buhtz** [WeblateOrg/weblate#9449]
### Describe the issue

Simple example:

    val = '15'
    print(_('Trying to keep min {perc}% free inodes').format(perc=val))

Asking several linter that seems to be PEP conform and valid Python code.

But Weblate (4.17) gives me a check error about this:

    Following format strings are missing: % f

I can understand why this happens. But I'm not sure who is "wrong" here.
Isn't my code valid? Or is the Weblate check not correct at this point?

To my knowledge `%` as printable character don't need to be escaped in Python if you don't use the `%f` type of format strings anymore. But I don't have a PEP about that.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Try this

    val = '15'
    print(_('Trying to keep min {perc}% free inodes').format(perc=val))

### Expected behavior

No check error.

### How do you run Weblate?

Other

### Weblate versions

4.17 on translate.coderberg.org

### Weblate deploy checks

```shell
Don't know the answer.
```

### Additional context

No additional context

**Comment by buhtz** [comment]
Please also see [PEP3101](https://peps.python.org/pep-3101) which don't talk about escaping `%`.

**Comment by nijel** [comment]
I think this is actually a xgettext bug, it creates the PO file indicating that *both* `python-format` and `python-brace-format` are being applied to this string:

```po
#: test.py:2
#, python-format, python-brace-format
msgid "Trying to keep min {perc}% free inodes"
msgstr ""
```

Weblate then just follows these flags. You can add the `ignore-python-format` flag in Weblate to override this.

**Comment by buhtz** [comment]
> I think this is actually a xgettext bug

Thanks for analyzing. I'll see if I open a ticket at xgettext.

> Weblate then just follows these flags. You can add the `ignore-python-format` flag in Weblate to override this.

Where can I do this? I only find "enforced checks" in the Translation settings. btw: This opinions makes no sense to me because all checks are done. So why should I "enforce" something that is even done?

**Comment by nijel** [comment]
Add the flag to the affected string only, see https://docs.weblate.org/en/latest/admin/translating.html#additional-info-on-source-strings

**Comment by buhtz** [comment]
> Add the flag to the affected string only, see https://docs.weblate.org/en/latest/admin/translating.html#additional-info-on-source-strings

I assume this flag will get lost when I reset the weblate repo?

This is how I "update" it with my upstream repo because my weblate instance is not allowed to commit/merge/PR into Microsoft GitHub accounts (for very good reasons).

**Comment by nijel** [comment]
It should stay there as long as the string is there.
