### ISSUE TITLE
Plurals in json files - import & export

### ISSUE THREAD

**Issue by bezysoftware** [WeblateOrg/weblate#9458]
### Describe the problem

Currently exporting plural strings (imported via Android strings file e.g.) skips them. It would be nice if they were exported too, e.g. in this format (as nested objects):
```json
 "cars": {
  "one": "%s car",
  "few": "%s cars",
  "many": "%s cars"
 }
```

Same thing for importing such files - they can be imported but each quantity as tracked as a separate string with composite key, e.g.
"cars.one" and "cars.few". Not terrible but could be better

### Describe the solution you'd like

Import / export plural strings in json format:
```json
 "cars": {
  "one": "%s car",
  "few": "%s cars",
  "many": "%s cars"
 }
```

**Comment by nijel** [comment]
There is no plurals support in plain JSON format, see https://docs.weblate.org/en/latest/formats.html#translation-types-capabilities

**Comment by bezysoftware** [comment]
Does some "extended" json format exist? 
Our use case is we have localization files coming from Android (primary app) but we want to reuse these in our Angular app. Right now we have to manually construct the json file manually from raw strings, being able to export them directly into json would help a lot

**Comment by nijel** [comment]
Yes, see links to JSON formats at https://docs.weblate.org/en/latest/formats/json.html
