### ISSUE TITLE
Duplicate notifications

### ISSUE THREAD

**Issue by ib** [WeblateOrg/weblate#9464]
### Describe the issue

When a change is made to an already translated string, two notifications are sent, one for the user's "Translated string" notification setting and one for the "Changed string" setting. Both (virtually identical) emails read: "Changed translation" (subject) and "Translation change" (body). (There is only one "Translation changed" entry in the history, but there are two notification emails).

Shouldn't "Translated string" only take effect if the string is newly translated, i.e. was previously untranslated? If not, how to distinguish between a new (i.e. first-time) and a changed translation (notification-wise)?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to user's Settings > Notification.
2. Enable notification for "Changed string" and "Translated string".
3. Wait until someone changes a translation.

### Expected behavior

When a change is made to an already translated string, only one "Changed string" notification should be sent.

### How do you run Weblate?

weblate.org service

### Weblate versions

[Weblate 4.18.1](https://hosted.weblate.org/)

**Comment by ib** [comment]
I suppose this is a regression.

The notification reads:
```## Source string

Get the Aurora Store source code from Aurora OSS on GitLab.

## Translation

Aurora Store-Quellcode von Aurora OSS bei GitLab herunterladen.

## Translation change

Aurora Store-Quellcode von Aurora OSS bei GitLab herunterladen.
```

Please note that (old) "Translation" and (new) "Translation change" are identical. However, a period has been added at the end of the sentence which can be seen in the history:

![history](https://github.com/WeblateOrg/weblate/assets/123327/79580356-ea60-412f-ae22-a12b684c8cd6)

The new "skip" mechanism for duplicate notifications seems to come too late for the old state of the translation.

**Comment by nijel** [comment]
@ib It's unrelated. The only reason is that the plain text version cannot show the diff.
