### ISSUE TITLE
Automatic fixup for punctuation spacing

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#9470]
### Describe the problem

The [Punctuation spacing check](https://docs.weblate.org/en/latest/user/checks.html#punctuation-spacing) accepts breakable space, while the proper solution is to use non-breakable one.

### Describe the solution you'd like

Add an automatic fixup which would turn `<space><punctuation>` in French and Breton to `<nb-space><punctuation>`.

### Describe alternatives you've considered

Make the check more strict and keep this up to the translator.

**Comment by HarmfulBreeze** [comment]
Hello,

Some guides like the _Lexique des règles typographiques en usage à l'Imprimerie nationale_, often used as a reference in France, specify that there should be a regular non-breaking space before the colon character, but not for other "two-part" characters where a NNBSP should be used instead. Some organizations and media however prefer to use NNBSP with colons.

Are there plans to add a toggle (of sorts) to allow the use of NBSP with colons?

Thanks!
Pierre

**Comment by nijel** [comment]
Currently, there is no such plan. Please open a separate issue to discuss this.
