### ISSUE TITLE
After upgrading Ubuntu to 22.04 the weblate docker image no longer runs

### ISSUE THREAD

**Issue by sdn3rd** [WeblateOrg/weblate#9471]
### Describe the issue

I am getting the following error in the docker-compose logs:
weblate_1   | django_redis.exceptions.ConnectionInterrupted: Redis TimeoutError: Timeout connecting to server
weblate_1   | 
weblate_1   | During handling of the above exception, another exception occurred:
weblate_1   | 
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/bin/weblate", line 8, in <module>
weblate_1   |     sys.exit(main())
weblate_1   |              ^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/weblate/runner.py", line 19, in main
weblate_1   |     utility.execute()
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
weblate_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
weblate_1   |     self.execute(*args, **cmd_options)
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
weblate_1   |     output = self.handle(*args, **options)
weblate_1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/shell.py", line 117, in handle
weblate_1   |     exec(options["command"], globals())
weblate_1   |   File "<string>", line 1, in <module>
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 36, in _decorator
weblate_1   |     raise e.__cause__
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django_redis/client/default.py", line 668, in has_key
weblate_1   |     return client.exists(key) == 1
weblate_1   |            ^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 1708, in exists
weblate_1   |     return self.execute_command("EXISTS", *names)
weblate_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1266, in execute_command
weblate_1   |     conn = self.connection or pool.get_connection(command_name, **options)
weblate_1   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 1457, in get_connection
weblate_1   |     connection.connect()
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 703, in connect
weblate_1   |     raise TimeoutError("Timeout connecting to server")
weblate_1   | redis.exceptions.TimeoutError: Timeout connecting to server
weblate_1   | redis at cache is unavailable - retrying 29

I am unsure what is causing this, but it is the docker image and I did a git pull to update it as well, still the same thing.  Any pointers in the right direction are greatly appreciated.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

cd weblate-docker
docker-compose start
docker-compose logs

### Expected behavior

It was working prior to upgrading ubtunu from 20 to 22 lts

### How do you run Weblate?

Docker container

### Weblate versions

originally a git clone, went in and did a git pull, was previously 4.16 when it worked.

**Comment by sdn3rd** [comment]
docker-compose ps
          Name                         Command                   State                                    Ports                            
-------------------------------------------------------------------------------------------------------------------------------------------
weblate-docker_cache_1      docker-entrypoint.sh redis ...   Up               6379/tcp                                                     
weblate-docker_database_1   docker-entrypoint.sh postgres    Up               5432/tcp                                                     
weblate-docker_weblate_1    /app/bin/start runserver         Up (unhealthy)   0.0.0.0:443->4443/tcp,:::443->4443/tcp,                      
                                                                              0.0.0.0:80->8080/tcp,:::80->8080/tcp

**Comment by sdn3rd** [comment]
I am in worse shape now, I issued a docker-compose pull and now get:
 docker-compose start
Starting database ... failed
Starting cache    ... failed
Starting weblate  ... failed
ERROR: No containers to start
ERROR: 1

**Comment by nijel** [comment]
Try `docker compose down` and `docker compose up -d`, that will rebuild all compose containers and network.

**Comment by sdn3rd** [comment]
Now the output is different not sure if it's a bug:

weblate_1   | Starting...
weblate_1   | [2023-06-30 03:19:28,942: WARNING/11] Handled exception: BusyLoadingError: Redis is loading the dataset in memory
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 29, in _decorator
weblate_1   |     return method(self, *args, **kwargs)
weblate_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 138, in has_key
weblate_1   |     return self.client.has_key(*args, **kwargs)
weblate_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django_redis/client/default.py", line 670, in has_key
weblate_1   |     raise ConnectionInterrupted(connection=client) from e
weblate_1   | django_redis.exceptions.ConnectionInterrupted: Redis BusyLoadingError: Redis is loading the dataset in memory
weblate_1   | 
weblate_1   | During handling of the above exception, another exception occurred:
weblate_1   | 
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/bin/weblate", line 8, in <module>
weblate_1   |     sys.exit(main())
weblate_1   |              ^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/weblate/runner.py", line 19, in main
weblate_1   |     utility.execute()
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
weblate_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
weblate_1   |     self.execute(*args, **cmd_options)
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
weblate_1   |     output = self.handle(*args, **options)
weblate_1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/shell.py", line 117, in handle
weblate_1   |     exec(options["command"], globals())
weblate_1   |   File "<string>", line 1, in <module>
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 36, in _decorator
weblate_1   |     raise e.__cause__
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django_redis/client/default.py", line 668, in has_key
weblate_1   |     return client.exists(key) == 1
weblate_1   |            ^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 1708, in exists
weblate_1   |     return self.execute_command("EXISTS", *names)
weblate_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1269, in execute_command
weblate_1   |     return conn.retry.call_with_retry(
weblate_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 49, in call_with_retry
weblate_1   |     fail(error)
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1273, in <lambda>
weblate_1   |     lambda error: self._disconnect_raise(conn, error),
weblate_1   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1259, in _disconnect_raise
weblate_1   |     raise error
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
weblate_1   |     return do()
weblate_1   |            ^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1270, in <lambda>
weblate_1   |     lambda: self._send_command_parse_response(
weblate_1   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1246, in _send_command_parse_response
weblate_1   |     return self.parse_response(conn, command_name, **options)
weblate_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1286, in parse_response
weblate_1   |     response = connection.read_response()
weblate_1   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 874, in read_response
weblate_1   |     response = self._parser.read_response(disable_decoding=disable_decoding)
weblate_1   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 502, in read_response
weblate_1   |     raise response
weblate_1   | redis.exceptions.BusyLoadingError: Redis is loading the dataset in memory
weblate_1   | redis at cache is unavailable - retrying 30
weblate_1   | [2023-06-30 03:19:32,185: WARNING/31] Handled exception: BusyLoadingError: Redis is loading the dataset in memory
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 29, in _decorator
weblate_1   |     return method(self, *args, **kwargs)
weblate_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 138, in has_key
weblate_1   |     return self.client.has_key(*args, **kwargs)
weblate_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django_redis/client/default.py", line 670, in has_key
weblate_1   |     raise ConnectionInterrupted(connection=client) from e
weblate_1   | django_redis.exceptions.ConnectionInterrupted: Redis BusyLoadingError: Redis is loading the dataset in memory
weblate_1   | 
weblate_1   | During handling of the above exception, another exception occurred:
weblate_1   | 
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/bin/weblate", line 8, in <module>
weblate_1   |     sys.exit(main())
weblate_1   |              ^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/weblate/runner.py", line 19, in main
weblate_1   |     utility.execute()
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
weblate_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
weblate_1   |     self.execute(*args, **cmd_options)
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
weblate_1   |     output = self.handle(*args, **options)
weblate_1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/shell.py", line 117, in handle
weblate_1   |     exec(options["command"], globals())
weblate_1   |   File "<string>", line 1, in <module>
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 36, in _decorator
weblate_1   |     raise e.__cause__
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django_redis/client/default.py", line 668, in has_key
weblate_1   |     return client.exists(key) == 1
weblate_1   |            ^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 1708, in exists
weblate_1   |     return self.execute_command("EXISTS", *names)
weblate_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1269, in execute_command
weblate_1   |     return conn.retry.call_with_retry(
weblate_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 49, in call_with_retry
weblate_1   |     fail(error)
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1273, in <lambda>
weblate_1   |     lambda error: self._disconnect_raise(conn, error),
weblate_1   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1259, in _disconnect_raise
weblate_1   |     raise error
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
weblate_1   |     return do()
weblate_1   |            ^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1270, in <lambda>
weblate_1   |     lambda: self._send_command_parse_response(
weblate_1   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1246, in _send_command_parse_response
weblate_1   |     return self.parse_response(conn, command_name, **options)
weblate_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1286, in parse_response
weblate_1   |     response = connection.read_response()
weblate_1   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 874, in read_response
weblate_1   |     response = self._parser.read_response(disable_decoding=disable_decoding)
weblate_1   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 502, in read_response
weblate_1   |     raise response
weblate_1   | redis.exceptions.BusyLoadingError: Redis is loading the dataset in memory
weblate_1   | redis at cache is unavailable - retrying 29
weblate_1   | [2023-06-30 03:19:35,943: WARNING/51] Handled exception: BusyLoadingError: Redis is loading the dataset in memory
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 29, in _decorator
weblate_1   |     return method(self, *args, **kwargs)
weblate_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 138, in has_key
weblate_1   |     return self.client.has_key(*args, **kwargs)
weblate_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django_redis/client/default.py", line 670, in has_key
weblate_1   |     raise ConnectionInterrupted(connection=client) from e
weblate_1   | django_redis.exceptions.ConnectionInterrupted: Redis BusyLoadingError: Redis is loading the dataset in memory
weblate_1   | 
weblate_1   | During handling of the above exception, another exception occurred:
weblate_1   | 
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/bin/weblate", line 8, in <module>
weblate_1   |     sys.exit(main())
weblate_1   |              ^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/weblate/runner.py", line 19, in main
weblate_1   |     utility.execute()
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
weblate_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
weblate_1   |     self.execute(*args, **cmd_options)
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
weblate_1   |     output = self.handle(*args, **options)
weblate_1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/shell.py", line 117, in handle
weblate_1   |     exec(options["command"], globals())
weblate_1   |   File "<string>", line 1, in <module>
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 36, in _decorator
weblate_1   |     raise e.__cause__
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django_redis/client/default.py", line 668, in has_key
weblate_1   |     return client.exists(key) == 1
weblate_1   |            ^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 1708, in exists
weblate_1   |     return self.execute_command("EXISTS", *names)
weblate_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1269, in execute_command
weblate_1   |     return conn.retry.call_with_retry(
weblate_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 49, in call_with_retry
weblate_1   |     fail(error)
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1273, in <lambda>
weblate_1   |     lambda error: self._disconnect_raise(conn, error),
weblate_1   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1259, in _disconnect_raise
weblate_1   |     raise error
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
weblate_1   |     return do()
weblate_1   |            ^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1270, in <lambda>
weblate_1   |     lambda: self._send_command_parse_response(
weblate_1   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1246, in _send_command_parse_response
weblate_1   |     return self.parse_response(conn, command_name, **options)
weblate_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1286, in parse_response
weblate_1   |     response = connection.read_response()
weblate_1   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 874, in read_response
weblate_1   |     response = self._parser.read_response(disable_decoding=disable_decoding)
weblate_1   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 502, in read_response
weblate_1   |     raise response
weblate_1   | redis.exceptions.BusyLoadingError: Redis is loading the dataset in memory
weblate_1   | redis at cache is unavailable - retrying 28


Different error now it seems?

**Comment by sdn3rd** [comment]
I read through the documentation and I have to say, it's super unclear how to use redis while using a docker container and the part about updating django cache?   Is that even related to using a docker image, it has a link.

I guess the real issue is fundamentally the documentation while decent enough is not very clear and the level of knowledge to even use it has to be relatively high.  

I would love to see it updated to be more clear and I appreciate the point in the right direction, which did not really help me set the environment variable to the IP of the host and bind redis-server to it.  All of this is completely unclear and i guess it's assumed since it's not part of weblate, why explain it?  I am unsure but it's exceedingly confusing documentation.

**Comment by nijel** [comment]
Can you please link to unclear documentation? Or even better, suggest improvements to it?

When using Docker, redis is one of the containers started by docker compose.
