### ISSUE TITLE
Glossary translation explanation mapping is broken

### ISSUE THREAD

**Issue by pavelhoral** [WeblateOrg/weblate#9476]
### Describe the issue

We are using TBX glossary and there is a bug when the TBX gets updated and Weblate pulls changes from the repo.

When we add new glossary entry in Weblate, the explanation is written as `<descrip>` for source unit explanation and as `<note from="translator">` for target unit explanation.

However when we modify TBX in the VCS and pull the changes, everything from the TBX file gets mapped to `note` column in the database. So we end up with duplicate explanations that can not be deleted via UI.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Create new translation project
2. Create glossary component
3. Add new glossary entry with source string explanation
4. Push to repository
5. Make new commit in the repository by changing glossary translation
6. Pull changes to Weblate (update from repo)
7. Observe duplicate explanation that can no longer be edited

### Expected behavior

Source string explanation and translation explanation should be mapped to `explanation` only and `note` should no longer be used.

### Screenshots

![obrazek](https://github.com/WeblateOrg/weblate/assets/2012726/c21dee92-78d6-48bd-ad82-3dd42a68b614)

### How do you run Weblate?

Docker container

### Weblate versions

4.18.1

**Comment by nijel** [comment]
Ah, translate-toolkit sets the `from` attribute `note` when saving this, but does no filtering when reading. Needs to be fixed there.

**Comment by pavelhoral** [comment]
> Ah, translate-toolkit sets the `from` attribute `note` when saving this, but does no filtering when reading. Needs to be fixed there.

Should I create the issue there? I am not sure I understand the cause you've described.

**Comment by nijel** [comment]
Should be fixed by https://github.com/translate/translate/pull/4955 and https://github.com/WeblateOrg/weblate/pull/9485
