### ISSUE TITLE
How disable contact form?

### ISSUE THREAD

**Issue by perrfect** [WeblateOrg/weblate#9479]
### Describe the issue

I'm using Weblate in docker-compose.
How can disable contact form to restrict access via the Internet?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

I tried to use `WEBLATE_CONTACT_FORM=0`, but the form is still working.

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
Duplicate of #9353
