### ISSUE TITLE
How can use /api without login.

### ISSUE THREAD

**Issue by perrfect** [WeblateOrg/weblate#9480]
### Describe the issue

Hello.
I'm using Weblate in docker-compose and have added `WEBLATE_REQUIRE_LOGIN=1`, because my Weblate is accessible via the Internet.
But I need access to `https://translations.example.com/api/` without login only with a token. And in this case I'm getting:

```
HTTP 401 Unauthorized
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
WWW-Authenticate: Token

{
    "detail": "Authentication credentials were not provided."
}
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

In a environment file add the parameter:
`WEBLATE_REQUIRE_LOGIN=1`
And try to use the URL: `https://translations.example.com/api`

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
It should work with a token. How are you passing it? Any reverse proxy in front of Weblate which might discard it?

Furthermore, didn't you change WEBLATE_LOGIN_REQUIRED_URLS_EXCEPTIONS? The default one excludes API.

**Comment by perrfect** [comment]
> It should work with a token. How are you passing it? Any reverse proxy in front of Weblate which might discard it?
> 
> Furthermore, didn't you change WEBLATE_LOGIN_REQUIRED_URLS_EXCEPTIONS? The default one excludes API.

Hello. Thank you for your reply.
My Weblate is behind nginx revers proxy.
And my environment file I don't have `WEBLATE_LOGIN_REQUIRED_URLS_EXCEPTIONS` parameter.
