### ISSUE TITLE
Add _FILE support for all (sensitive) variables

### ISSUE THREAD

**Issue by jorrit** [WeblateOrg/weblate#9482]
### Describe the problem

I'd like to connect my Weblate installation to Azure AD. Weblate runs in Docker. Right now, this requires that I specify `WEBLATE_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_SECRET` as an environment variable.
I would like to use Docker secrets to pass the secret to Weblate.

Right now, only a limited number of environment variables support reading from a file.

### Describe the solution you'd like

I would like to propose that a wrapper function for `os.environ.get()` is added to `settings_docker.py` such that all environment variables that could be sensitive can be read from a file if `${VARNAME}_FILE` exists. This would also remove the need for a manual list of variables in the start script.

**Comment by nijel** [comment]
There are already similar environment wrappers in https://github.com/WeblateOrg/weblate/blob/main/weblate/utils/environment.py, adding another one should be easy.

**Comment by YashTote** [comment]
The secrets have to be declared in docker-compose.yml to be available in the container. But doing these changes in the docker-compose file seems a little odd. Can you suggest me where should that be declared ?

**Comment by nijel** [comment]
There are two things:

* First, the container needs to support this. That's what I've refrenced in the previous comment.
* Then you can configure these in `docker-compose.yml`, see https://docs.docker.com/compose/use-secrets/

**Comment by YashTote** [comment]
The secrets requires you to define the password or the passkey before hand. How do I handle this? Or what is the usual way?

**Comment by nijel** [comment]
Sorry, but this is out of scope here.

**Comment by jorrit** [comment]
@nijel: thanks!
