### ISSUE TITLE
Notifications issue

### ISSUE THREAD

**Issue by ib** [WeblateOrg/weblate#9486]
### Describe the issue

@nijel This is a addition to #9464.

I still don't understand why the "Translated string" notification is nothing but a subset of "Changed string".

The usual translation workflow is: (1) "New strings to translate" → (2) "New translation" or "Suggestion accepted" → (possibly later) (3) "Translation changed".

There are options to be notified separately for (1) and (3), but not for (2).

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Select "Translated string" and "Changed string" in the user settings.

### Expected behavior

I would expect there to be a notification option that informs on first-time, new translations only.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
"Translated string" is indeed subset of "Changed string". It covers only changes done by translator in Weblate. It excludes changes done in the repository, automatic translation, or state changes, so it is less noisy. Similarly there is "Approved string" notifications, which is subset of "Changed string", but only triggered on strings approval with the review workflow.

**Comment by ib** [comment]
My point is that there is no notification setting for (2).

**Comment by nijel** [comment]
“Translated string” is actually triggered on both “Translation changed” and “New translation”. There is indeed no separate notification for accepting suggestions.

**Comment by ib** [comment]
(2) isn't about "Suggestion accepted".

What I miss is a notification for a previously untranslated string that got translated for the first time, which can happen either by a manual translation or an accepted suggestion. This is what I have labeled (2).

I thought that "Translated string" meant exactly this (but I was wrong).

You can close this issue if you feel that workflow steps (1), (2) and (3) do not require separate notifications.

**Comment by nijel** [comment]
I think it makes sense to include suggestion accepted action in the translated string notification. I'd rather not introduce another notification choice.

**Comment by Geeyun-JY3** [comment]
> I think it makes sense to include suggestion accepted action in the translated string notification. I'd rather not introduce another notification choice.

If implemented, I think a more specific name for the “Translated string” notification is needed.

**Comment by ib** [comment]
@nijel Thank you, I appreciate your efforts and can understand not introducing a new notification choice.

However, I think that the current notification labels might be confusing to users.

"Translated string" should rather read something like "New or changed translation of string" or so and "Changed string" should rather read something like "Any change to string" or so to express that it is some kind of _superset_. Otherwise it is hard to understand what the difference between "Translated" and "Changed" is supposed to be. 

Just my opinion, though.

**Comment by nijel** [comment]
Naming is indeed not good. The intention here was to have one notification for user triggered changes and the other for all changes (including automatic translation, updates from the repository, bulk edits, ...). I've renamed first to "Edited string", hopefully it's a better name.
