### ISSUE TITLE
Italian language not showing up in the menu

### ISSUE THREAD

**Issue by Pho573** [WeblateOrg/weblate#9493]
### Describe the issue

In the project I'm translating there are 4 components, I already translated 2 components to italian, but I can't do the same to the other 2 because in the drop down menu italian doesn't show up.

![bla](https://github.com/WeblateOrg/weblate/assets/138355128/23b7e256-fa51-4769-b7b7-69abc9466fc9)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Try to add the same language multiple times across multiple components, that's what I did.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Maybe Italian is already added there?

**Comment by Pho573** [comment]
I was wrong, it seems like the problem is just an option selected by the project manager.
No need to respond to my issue anymore.

**Comment by Pho573** [comment]
I was wrong, it seems like the problem is just an option selected by the project manager.
No need to respond to my issue anymore.
