### ISSUE TITLE
How correctly use all emails from a domain in google auth?

### ISSUE THREAD

**Issue by perrfect** [WeblateOrg/weblate#9499]
### Describe the issue

I'm using Weblate in docker-compose. And also using google auth for login.
Google auth works correctly, but only if I set one email address in `WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_EMAILS=test@example.com`
How can I set all emails from the domain in `WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_EMAILS`.
I tried to use:
```
WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_EMAILS=*@example.com
WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_EMAILS=^.*@example.com$
```
But it doesn't work.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

A docker-compose with the next setting:
```
WEBLATE_REGISTRATION_OPEN=0
WEBLATE_REGISTRATION_ALLOW_BACKENDS=google-oauth2
WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS=example.com
WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY="test.apps.google.com"
WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET="qwerty"
WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_EMAILS=*@example.com
```

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
How about just `WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS=example.com`?

**Comment by perrfect** [comment]
> How about just `WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS=example.com`?

Hello. Thank you for your reply. Everything is ok. Thank you.
