### ISSUE TITLE
When accessing a self-hosted Weblate site anonymously, you can see the list of translated languages. 

### ISSUE THREAD

**Issue by dxdx123** [WeblateOrg/weblate#9507]
### Describe the issue

When accessing a self-hosted Weblate site anonymously, you can see the list of translated languages. Not only can you see the language options, but you can also view various language translation data. I believe this may be a bug and I hope it will be fixed in future versions.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1.To open the Weblate homepage,
2. click on the "Language" option, 
3. and then click on "Browse All Languages".

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/14290268/b94dd278-7163-4421-b7bc-065db4ce7a55)
![image](https://github.com/WeblateOrg/weblate/assets/14290268/5056e9c7-9c28-46d5-85ec-352be79e5e1d)

### How do you run Weblate?

Docker container

### Weblate versions

4.18.1

**Comment by nijel** [comment]
This is documented at https://docs.weblate.org/en/latest/admin/access.html#per-project-access-control. You can also lock down all access, see https://docs.weblate.org/en/latest/admin/access.html#additional-access-restrictions.
