### ISSUE TITLE
How correctly backup Weblate?

### ISSUE THREAD

**Issue by perrfect** [WeblateOrg/weblate#9508]
### Describe the issue

Hello.
I'm using Weblate in a docker-compose.
How should I correctly backup my Weblate if something happens?
Should I backup only the postgresql database or the data in a `redis-data` and a `weblate-cache `volumes is also important?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Also is it enough using this command in cron when container is running?
`docker-compose --project-directory /opt/weblate exec database pg_dumpall -U weblate > backup.sql`
Or should I need to stop the container before running the `pg_dumpall` command?

And also in documentation i see the `WEBLATE_DATABASE_BACKUP` options, but don't fully understand how correctly use it?
Where will the backup be stored?
How often will the backup be performed?
The value of these options should be in 0 or 1, or  "plain",  "compressed", "none"?

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
https://docs.weblate.org/en/latest/admin/backup.html
