### ISSUE TITLE
Widget missing glyphs for Chinese

### ISSUE THREAD

**Issue by ZiYueCommentary** [WeblateOrg/weblate#9514]
### Describe the issue

The badges and panel in Chinese didn't display texts properly.

This is kinda like https://github.com/WeblateOrg/weblate/issues/6838 , but it didn't happen in Weblate 4.17

![image](https://github.com/WeblateOrg/weblate/assets/63241389/9bd4c677-ca6d-457d-98f1-0840afd44655)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Open status widgets.
2. Specific the language as Simplified Chinese or Traditional Chinese.

### Expected behavior

https://hosted.weblate.org/widgets/3d-slicer/?lang=zh_Hans&component=#open

### Screenshots

Examples of this issue:

1. https://translate.mattermost.com/widgets/calls/?lang=zh_Hans&component=#open
1. https://translate.cloudron.io/widgets/cloudron/?lang=zh_Hans&component=#open
1. https://weblate.ziyuesinicization.site/widgets/scpcb-ue/?lang=zh_Hans&component=local-ini#open

... and this is not happening in Weblate 4.17:

1. https://weblate.rob006.net/widgets/flarum/?lang=zh_Hans&component=#open

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.18.2
 * Django: 4.2.2
 * siphashc: 2.1
 * translate-toolkit: 3.9.2
 * lxml: 4.9.2
 * Pillow: 9.5.0
 * nh3: 0.2.13
 * python-dateutil: 2.8.2
 * social-auth-core: 4.4.2
 * social-auth-app-django: 5.2.0
 * django-crispy-forms: 2.0
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.2
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.12.2
 * rapidfuzz: 3.1.1
 * openpyxl: 3.1.2
 * celery: 5.3.1
 * django-celery-beat: 2.5.0
 * kombu: 5.3.1
 * translation-finder: 2.15
 * weblate-language-data: 2023.5
 * html2text: 2020.1.16
 * pycairo: 1.24.0
 * PyGObject: 3.44.1
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.3.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.26.0
 * Cython: 0.29.35
 * misaka: 2.1.1
 * GitPython: 3.1.31
 * borgbackup: 1.2.4
 * pyparsing: 3.0.9
 * pyahocorasick: 2.0.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.1.0
 * Python: 3.11.4
 * Git: 2.30.2
 * psycopg2: 2.9.6
 * phply: 1.2.6
 * ruamel.yaml: 0.17.32
 * tesserocr: 2.6.0
 * boto3: 1.26.164
 * zeep: 4.2.1
 * aeidon: 1.12
 * iniparse: 0.5
 * mysqlclient: 2.2.0
 * Mercurial: 6.4.5
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 7.0.11
 * PostgreSQL server: 15.3
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp-mail.outlook.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.4.119-20.0009.20 (x86_64)

**Comment by nijel** [comment]
Probably caused by 1e18926f0ed2843a6dadb526ead8a92d344c63ce, see #9145.
