### ISSUE TITLE
Automatic translation add-on keeps running after uninstalled

### ISSUE THREAD

**Issue by kylecorry31** [WeblateOrg/weblate#9516]
### Describe the issue

I discovered the automatic translation add-on today and enabled it on my repo, but I didn't like the quality of some of the translations so I attempted to stop it by changing the action it took (add as suggestion instead) and then uninstalling, but it keeps making changes. My assumption is that it is going to keep running until all translations are generated, and because I've reset the repo a few times it hasn't got there yet - my hope is that once it finishes translating what's there, it will stop and I can just discard the changes.

File format: Android String Resource

URL: https://hosted.weblate.org/projects/trail-sense/trail-sense-android

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Enable automatic translation add-on on untranslated strings, add as translation, libretranslate
2. Committed changes after a little bit and pushed to my upstream repo to see if I could easily clean up some of the translations (it was having issue with format arguments %s was being translated as seemingly random strings)
3. Switched it to add as suggestion, libretranslate + weblate translation memory
4. At this point, it was still adding translations instead of suggestions, so I uninstalled the extension
5. On settings, I reset the repo multiple times and also tried cleanup and synchronize
6. Translations are still being added (I've locked the repo so it will be easier to clear out when it's done)

### Expected behavior

When I uninstall the automatic translation add-on, automatic translations stop being added.

When I switch automatic translations from adding the translation to adding a suggestion, it will stop adding new translations.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
There is currently no way to stop a running operation. It won't be executed again.

**Comment by kylecorry31** [comment]
@nijel thank you for the clarification

**Comment by kylecorry31** [comment]
After running overnight, I reset the repo and automatic translations have stopped. That lines up with the operation only being executed once and running until completion.

I'm all set, feel free to close this issue or repurpose it as needed, thanks!
