### ISSUE TITLE
Webhook security

### ISSUE THREAD

**Issue by siepkes** [WeblateOrg/weblate#9518]
### Describe the issue

I can't find information on how to enable webhook authentication. GitHub themselves seem to recommend to use their HMAC functionality (with shared secret) they provide (see GitHub's [Securing your webhooks](https://docs.github.com/en/webhooks-and-events/webhooks/securing-your-webhooks)). In the Weblate documentation for the [GitHub Webhook](https://docs.weblate.org/en/latest/admin/continuous.html#github-setup) integration I don't see any way to authenticate the requests are actually coming from GitHub. I also don't see an option in `settings.py` to for example specify a shared secret.

Am I missing something here?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

.

### How do you run Weblate?

Git checkout

**Comment by nijel** [comment]
There is currently no support for webhooks authentication. Weblate uses only repository URL and branch to detect which component to update.
