### ISSUE TITLE
Hide Personal API key per default

### ISSUE THREAD

**Issue by derkoe** [WeblateOrg/weblate#9520]
### Describe the problem

When you go to https://hosted.weblate.org/access/{project}/#api while screen sharing everybody will see you personal API key. 

The same is true for https://hosted.weblate.org/accounts/profile/#api but I guess this does not happen that much.

### Describe the solution you'd like

Hide the API key per default and only display it on some interaction ("Reveal key").

**Comment by derkoe** [comment]
This would be a simple implementation for that: https://github.com/WeblateOrg/weblate/compare/main...derkoe:feat/hide-api-key. Should I create a PR for that?

**Comment by nijel** [comment]
Yes, pull requests are welcome.
