### ISSUE TITLE
QA checks should highlight problems found in string

### ISSUE THREAD

**Issue by shanewims** [WeblateOrg/weblate#953]
When the QA checks find an error in the selected segment a message is displayed but it would be very helpful if the issue was highlighted in the strings (particularly for spacing and formatting issues).

(Feedback from translation vendor)
##

**Comment by nijel** [comment]
There is already PR implementing this: #949

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has been fixed. Most of the fix has been done in past, recently the checks also indicate the actual problem more verbosely.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
