### ISSUE TITLE
How to use the WEBLATE_BORG_EXTRA_ARGS variable?

### ISSUE THREAD

**Issue by foundryvtthub** [WeblateOrg/weblate#9530]
### Describe the issue

Hello,

I'm struggling to find how to properly use the WEBLATE_BORG_EXTRA_ARGS.

The Weblate documentation says to use it like this:

```BORG_EXTRA_ARGS = ["--exclude", "vcs/"]```

I tried multiple format to do the same in the Docker Compose file but I didn't find the right one.

Could you help me please?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Add WEBLATE_BORG_EXTRA_ARGS
Add values like `WEBLATE_BORG_EXTRA_ARGS: --exclude vcs/`

**Comment by nijel** [comment]
Use following:

```yaml
WEBLATE_BORG_EXTRA_ARGS: --exclude,vcs/
```

I will update the documentation to cover this.
