### ISSUE TITLE
Admin password step during setup is easy to miss.

### ISSUE THREAD

**Issue by yilmazdurmaz** [WeblateOrg/weblate#9531]
### Describe the problem

I was trying to have a local instance to work on local for a project.

This is the first time I try Weblate on local.

Most steps are clear, but this one is crucial and this line is very easy to misinterpret as I did and spent the next few hours where to find the admin password:
>Create an account for the administrator user and copy its password to the clipboard, and also save it for later use:
> `weblate createadmin`

### Describe the solution you'd like

This expression should emphasize the "copy the password" part, something like this:

__Create an account for the administrator user. This command will generate an admin password for the first use. Copy it to the clipboard, and also save it for later use: __

In addition, this would make it much better if you include this:

__ If you previously missed/lost the admin password, renew it with this command__
`weblate createadmin --update`

### Describe alternatives you've considered

The alternative was to check lots of places to see if there is a default password somewhere while spending a lot of time (few hours) just for this simple solution:
`weblate createadmin --update`

**Comment by swrp-j** [comment]
Could you please assign this issue to me?
