### ISSUE TITLE
Using on-screen keyboard shifts focus to first entry in Zen

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#9533]
### Describe the issue

https://hosted.weblate.org/translate/f-droid/f-droid-metadata/nb_NO/?checksum=8c43dc476c04f616

If adding enough secondary languages to where the total string spans beyond available viewing area, the focus will shift to the beginning of the string if anything is clicked on the on-screen keyboard.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Open https://hosted.weblate.org/translate/f-droid/f-droid-metadata/nb_NO/?checksum=8c43dc476c04f616
Go to "Zen"
![image](https://github.com/WeblateOrg/weblate/assets/13802408/db318cdd-6fc4-452d-bef2-bb675471ca38)
Scroll down to the editing field (which should arguably be in focus right away)
![image](https://github.com/WeblateOrg/weblate/assets/13802408/42369be8-9ed0-4c01-8f56-a26c16968ff7)
Click anything on the on-screen keyboard,
![image](https://github.com/WeblateOrg/weblate/assets/13802408/7e76ac17-f6a9-45a7-9d91-fa10548bdfab)
and we are back to the top again
![image](https://github.com/WeblateOrg/weblate/assets/13802408/a7c52cc5-fbea-423e-bb6c-d8939f00a3c2)
Scroll down again.
Noticed the clicked character is there
![image](https://github.com/WeblateOrg/weblate/assets/13802408/e4b51f77-5ce3-4ed8-a98f-f444f8d91203)

### Expected behavior

Didn't expect on-screen keyboard input to mean leaving the editing field at all.

### How do you run Weblate?

weblate.org service

**Comment by meel-hd** [comment]
working on it :)

**Comment by meel-hd** [comment]
This issue is not relevant anymore after the implementation of #12981 (the selected editor now is insured to be visible).
