### ISSUE TITLE
Machine Translation gives suggestions but they cannot be accepted or cloned (hosted.weblate.org)

### ISSUE THREAD

**Issue by yilmazdurmaz** [WeblateOrg/weblate#9538]
### Describe the issue

This happens at least on hosted.weblate.org

I am translating this project for the Turkish language: https://hosted.weblate.org/translate/learn-gdscript-from-zero

Automatic suggestions down the page works pretty nice and gives me suggestions.

The problem is, I cannot "accept" them, nor "clone to translation"

the latter simply toggles "needs editing" box, and nothing else. This should at least copy the translation that is already seen in the translation table.

pressing the "accept" button seemingly tries to use it as it browses to the next translation. but browsing back to supposedly-auto-translated string show no trace of such activity.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. go to [hosted.weblate.org](https://hosted.weblate.org/translate/learn-gdscript-from-zero)
2. find any Turkish translation string, maybe copy it to the clipboard, and delete it. (or maybe even clone to a temporary project)
3. try to delete that translation and use the "clone to translation" button. It should have no effect.
4. now first "save and stay" to clear the translation, then use the "accept" button for any machine translation. it will browse to next string.
5. browse back to the string you were trying to "machine translate" and see it is still empty.

6. use the history and browse back to the last translation of the string and save it.

### Expected behavior

-  "clone to translation" should copy the translated string into the editing area
- "accept" should save that entire machine translation into the string.

### Exception traceback

```pytb
sometime, there comes an error message on the top, but it takes only about a second and I cannot even read what is the problem, let alone try to copy it.
```

### How do you run Weblate?

weblate.org service

**Comment by yilmazdurmaz** [comment]
Hi @nijel,

your commit message sounds a bit off: "js: Fix storing first plural form from automatic suggestions".  storing plural forms?

Tell me if I am wrong, but I think there is a misunderstanding. The problem here is not about plural forms.

Anyways, when can I see & test it on the "hosted.weblate.org" to see if it solves the issue?

**Comment by nijel** [comment]
The problem was in handling plural forms (even if, in your case, the string had none).

**Comment by yilmazdurmaz** [comment]
That is an interesting bug.

The fix is now in effect on the site, and both buttons are doing their jobs.

Thanks for the fix ;)
