### ISSUE TITLE
Track origin of automatic translations

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#9545]
### Describe the problem

Currently, all automatic translations are recorded as “Automatic translation” in history, giving no clue what service did generate the translation.

### Describe the solution you'd like

Store the origin information in the history so that it can be displayed to the user.

**Comment by Rish-P** [comment]
Hi I'm a newbie to Open source and would like to contribute
can I take this up?

**Comment by nijel** [comment]
Implemented in a7c352ed0db.
