### ISSUE TITLE
Documentation missing for support GIF screenshots

### ISSUE THREAD

**Issue by buhtz** [WeblateOrg/weblate#9580]
### Describe the problem

Screenshots are good to provide the context of a string to the users.
Sometimes the context is not clear from an one-frame image. Sometimes there is a need of a short GIF animation.
See example below.

### Describe the solution you'd like

Support animated GIFs as upload option to screenshots section.

### Screenshots

Here you see one tooltip. The content of that tooltip is modified depending on context.

![bit_fileview_tooltips](https://github.com/WeblateOrg/weblate/assets/11861496/b8457944-5dca-4a64-9b60-1b966cdcdf17)

**Comment by nijel** [comment]
It is actually supported since 8fa4153b539, see #2924. It's just not properly documented.

**Comment by buhtz** [comment]
> It is actually supported since [8fa4153](https://github.com/WeblateOrg/weblate/commit/8fa4153b539bd6981ecfffb5bfe7cebd4484f4a6), see #2924. It's just not properly documented.

More user friendly answer for future readers: It is supported in latest dev version but not released yet.

Thanks in advance.

**Comment by nijel** [comment]
It is supported since the 3.8 release, as you can see from the linked issue.

BTW: I kept the issue open until the documentation update in https://github.com/WeblateOrg/weblate/pull/9582 is merged…

**Comment by buhtz** [comment]
Why making it so complex. I can not see it in the Issue. Yes there is the 3.8 milestone and it is closed. But a milestone is not a release. It should but often is not.

The commit you linked has a change.rst in it and there it is an unreleased feature.

I can read myself but you have to offer the information, for example an up to date CHANGELOG.

To know which one is up-to-date I tried to find out which one is your development branch reflecting the latest state of development. I don't have the answer. I realized that you don't describe or name your branching model in your CONTRIBUTING.md or the website linked behind it. Basic information for potential contributors are missing in your project.

**Comment by buhtz** [comment]
And you really have to learn to communicate. This would save my time and yours.

Just tell me that the feature is there but it is not documented. Short sentence would have saved a lot of time. 😡

**Comment by nijel** [comment]
> And you really have to learn to communicate. This would save my time and yours.

When talking about saving time: Have you considered using search before filing this issue? https://github.com/WeblateOrg/weblate/issues?q=is%3Aissue++gif

> Just tell me that the feature is there but it is not documented. Short sentence would have saved a lot of time. rage

That's what I did in https://github.com/WeblateOrg/weblate/issues/9580#issuecomment-1637560690. Clicking on both issue or commit would tell you the actual release.
