### ISSUE TITLE
doc: inconsistent path for serving static files 

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#9601]
### Describe the issue

There is an inconsistency in the documentation regarding serving the static files.
In `settings_example.py` there is since 4.16:
`STATIC_ROOT = os.path.join(CACHE_DIR, "static")`

Before 4.16 this value was:
`STATIC_ROOT = os.path.join(DATA_DIR, "static")`

The impact of this change is that all documentation talking about serving static file should point out that those files are coming from the CACHE_DIR, e.g. in https://docs.weblate.org/en/latest/admin/install.html#serving-static-files and in particular in https://docs.weblate.org/en/latest/admin/install.html#sample-configuration-for-nginx-and-uwsgi where the paths are now wrong. 

I just had the issue when performing an upgrade: suddenly my static files were not properly served anymore. I had to change my nginx configuration to fix the problem. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Upgrade weblate from 4.15 to 4.16 and apply the changes in settings_example.py

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Should be addressed by https://github.com/WeblateOrg/weblate/pull/9605, review is welcome.
