### ISSUE TITLE
Indicate diff in plain text e-mails

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#9619]
### Describe the problem

The notification reads:
```## Source string

Get the Aurora Store source code from Aurora OSS on GitLab.

## Translation

Aurora Store-Quellcode von Aurora OSS bei GitLab herunterladen.

## Translation change

Aurora Store-Quellcode von Aurora OSS bei GitLab herunterladen.
```

Please note that (old) "Translation" and (new) "Translation change" are identical. However, a period has been added at the end of the sentence which can be seen in the history:

![history](https://github.com/WeblateOrg/weblate/assets/123327/79580356-ea60-412f-ae22-a12b684c8cd6)

The new "skip" mechanism for duplicate notifications seems to come too late for the old state of the translation.

### Describe the solution you'd like

The diff should be visible in the text variant of e-mail.

I think using syntax as git `--word-diff` would be a viable approach:

```
[-REMOVED BLOCK-]{+ADDED BLOCK+}
```

It should be possible to subclass HTML2Text and use `tag_callback` to handle `ins` and `div` tags this way:

https://github.com/Alir3z4/html2text/blob/a3ed67b69160746b03a5861bf5c1b7a5ba76a4e1/html2text/__init__.py#L305-L307

### Additional context

Originally spotted by @ib at https://github.com/WeblateOrg/weblate/issues/9464#issuecomment-1644283050

**Comment by Rish-P** [comment]
can I pickup this issue? I'm a newbie and could try to come up with a workaround

**Comment by nijel** [comment]
@Rish-P Yes, you're welcome!

**Comment by nijel** [comment]
The proposed solution is described in the initial post. HTML2Text is called here: https://github.com/WeblateOrg/weblate/blob/c4c3a71cb25fb2424990ee1f6267433639c28c79/weblate/accounts/tasks.py#L133
