### ISSUE TITLE
Get Call for finished translations

### ISSUE THREAD

**Issue by ecxod** [WeblateOrg/weblate#9635]
### Describe the problem

Question : Is there already an Api-call with which you can easily query the status of the translation? 

### Describe the solution you'd like

It would be enough example : 
```
    https://weblate.example.org/projects/example/status
```
and then you get a list of Koma separated languages. e.g. 
``` 
    en,zh,fi
```
no login required

**Comment by nijel** [comment]
Maybe https://docs.weblate.org/en/latest/api.html#get--api-components-(string-project)-(string-component)-statistics-

**Comment by ecxod** [comment]
It can use it. Thank you.
