### ISSUE TITLE
doesn't add new strings to PHP

### ISSUE THREAD

**Issue by svbeon** [WeblateOrg/weblate#965]
well so we just installed weblate and our source file en.php looks like this

``` php
$loc['one'] = 'stuff';
$loc['two'] = 'is';
```

and i test translated 21 strings for sv.php. the problem was that if the strings didn't already exist in sv.php they weren't added to sv.php either. but if the string were there it was modified with the new value.
##

**Comment by nijel** [comment]
What version do you use? For 2.5 there are quite some improvements in this area (they fixed similar issues for different file formats).

**Comment by 00svbeon** [comment]
@nijel Weblate 2.5-dev

**Comment by nijel** [comment]
This is due to poor support for PHP files in translate-toolkit. I've added this to documentation: https://docs.weblate.org/en/latest/formats.html#php-strings

**Comment by nijel** [comment]
Should be fixed for real in https://github.com/translate/translate/pull/3697
