### ISSUE TITLE
Credit terminology entries to adding user

### ISSUE THREAD

**Issue by yilmazdurmaz** [WeblateOrg/weblate#9661]
### Describe the issue

The name is "None" and without any profile.. Since the name does not ring anything for a real person, I take it as some kind of AI-like system user.

And it has gone rogue for quite some time. It adds new items to the glossary no one asked for, sometimes acceptable, but mostly lots of nonsense duplicates.

Below are new addition made by it; most are parts of scripting codes (underscores) and 3 are exact duplicates.

https://hosted.weblate.org/browse/learn-gdscript-from-zero/glossary/tr/?q=state:%3Ctranslated

![new glossary item](https://github.com/WeblateOrg/weblate/assets/1812105/8190164a-78c5-4c50-8afb-0008526240ff)

https://hosted.weblate.org/translate/learn-gdscript-from-zero/glossary/tr/?checksum=8ed571e7e2730eb8&q=state%3A%3Ctranslated

![added by None system user](https://github.com/WeblateOrg/weblate/assets/1812105/9f68f93f-dcf9-4a66-aa7d-b6b964bc4dee)

I reported a similar issue before that if I try to delete duplicates, this None would revive them. I haven't heard about that from you yet, so you may take this as a complimentary issue and treat them both equal in fixing the None user.

https://github.com/WeblateOrg/weblate/issues/9593

Please fix the behaviour of this system user asap.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Just wait because there is no timer for this behavior
   - and then the None will add new items sooner or later, then you will be notified in the daily digest if set.

### Expected behavior

The None user should either not
 - add new items into the glossary
 - or have the mind not to add duplicate words, and/or code parts

### Screenshots

related screenshots are given under their respective links above

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
There is no AI in this, it's just operations which can't be accounted to any user. See also https://github.com/WeblateOrg/weblate/issues/3009.

In this particular case, the term was added upon commit to the language because of the `terminology` flag. And it is there four times because somebody added it there four times: https://hosted.weblate.org/translate/learn-gdscript-from-zero/glossary/en/?checksum=241ff434c9eab98e#others

**Comment by yilmazdurmaz** [comment]
Alright then, one mystery is solved. So, these nonsense additions are actually made by some real user but directly into the main language, here English.

I will try to delete these nonsense/duplicate strings from there and see what happens.

**Comment by yilmazdurmaz** [comment]
I am now traversing the English glossary and I can see there are items I added for my language, Turkish.

I thought adding new items to the glossary will only go to my selected/current language's glossary.

But now it is clear it goes back to the main language, and then propagates to other languages.

@nijel , do you know if there is/was any work about separating these two behaviors? not to propagate to other languages?

**Comment by nijel** [comment]
If you don't mark the string as terminology it will be in your language only, see https://docs.weblate.org/en/latest/user/glossary.html#terminology.

But I think the terminology entries should be credited to the adding user. I will change that.
