### ISSUE TITLE
Don't use the misleading name "One" for a singular form used for numbers other than 1

### ISSUE THREAD

**Issue by danpla** [WeblateOrg/weblate#9675]
### Describe the problem

Consider the following English source string with plural form (from a PO file):
```
msgid "One apple"
msgid_plural "{count} apples"
```
As you see, msgid uses "One apple" instead of "{count} apple", which is acceptable in English.

In other languages, however, the singular form may be used not only for 1. For example, in Russian, Ukrainian, Belarusian, Serbian, and Croatian the singular form is also used for numbers ending with 1. The problem with Webalte is that although it shows the right hint when you hover over the circled "i", the entry name literally says "One", which is simply not true for the mentioned languages:
![Untitled](https://github.com/WeblateOrg/weblate/assets/10910745/0ce5fc4b-942c-4e81-afcb-22059380fed4)

Naturally, this misguides translators: they think that the message will be used for exactly 1 item, and create a translation that doesn't work with 21, 31, 41, etc. - that is, in the example source string above, they will use the analog of "One apple" instead of "{count} apple". After all, if the entry clearly says "one", why would anyone check the hint button?

### Describe the solution you'd like

The entry label should probably not say "One", but instead include the example text currently hidden in (i).

**Comment by nijel** [comment]
These are names defined by CLDR (see https://www.unicode.org/cldr/charts/40/supplemental/language_plural_rules.html#hr) and Weblate uses them for consistency with other tooling. Showing the examples more prominently might make it more clear, though.

PS: There are languages where the same applies to “Two”, see https://www.unicode.org/cldr/charts/40/supplemental/language_plural_rules.html#dsb

**Comment by nishitiwari22** [comment]
Is this issue still open? I am looking to contribute to it. I am newbie.

**Comment by nijel** [comment]
Many professional translators are used to these names, that's why I think the category names should stay visible. 

The specific rules are language dependent (and vary between file formats or framework versions), so I don't think it's reasonable to have a verbose description for each of them.

So my original intention here was just to show the numbers directly, not only in a tooltip. This is what I've just implemented in https://github.com/WeblateOrg/weblate/pull/10136

**Comment by t-cordonnier** [comment]
I understand but

> Many professional translators are used to these names, 

The fact that somebody (not me) opened such a ticket shows us that this is not the case for everybody. 

> The specific rules are language dependent [...]  So my original intention here was just to show the numbers directly,

As the rule can depend from the number, you may have exactly same problem to display the correct number. For example what if some languages make agreement for 21 as singular and some as genitive plural like 25?

**Comment by nijel** [comment]
I'm not saying that everybody understands these, but it's an industry standard. Omitting that would be confusing for many users. We definitely need to clarify this for users not familiar with CLDR categories.
