### ISSUE TITLE
Backup must ignore "lost+found"

### ISSUE THREAD

**Issue by eltorio** [WeblateOrg/weblate#9681]
### Describe the issue

Backup fail with error:
/app/data/lost+found: dir_open: [Errno 13] Permission denied: 'lost+found'

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Deploy Weblate with helm chart and tag edge
Setup borg with a remote repository
launch a backup

### Expected behavior

lost+found must be ignored (weblate run as weblate user not root)

### How do you run Weblate?

Docker container

### Weblate versions

* Weblate: 4.18.2
 * Django: 4.2.4
 * siphashc: 2.1
 * translate-toolkit: 3.9.2
 * lxml: 4.9.3
 * Pillow: 9.5.0
 * nh3: 0.2.14
 * python-dateutil: 2.8.2
 * social-auth-core: 4.4.2
 * social-auth-app-django: 5.2.0
 * django-crispy-forms: 2.0
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.2
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.12.2
 * rapidfuzz: 3.1.2
 * openpyxl: 3.1.2
 * celery: 5.3.1
 * django-celery-beat: 2.5.0
 * kombu: 5.3.1
 * translation-finder: 2.15
 * weblate-language-data: 2023.5
 * html2text: 2020.1.16
 * pycairo: 1.24.0
 * PyGObject: 3.44.1
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.3.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.29.2
 * Cython: 0.29.36
 * misaka: 2.1.1
 * GitPython: 3.1.32
 * borgbackup: 1.2.4
 * pyparsing: 3.0.9
 * pyahocorasick: 2.0.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.2.0
 * Python: 3.11.4
 * Git: 2.30.2
 * psycopg2: 2.9.6
 * phply: 1.2.6
 * ruamel.yaml: 0.17.32
 * tesserocr: 2.6.0
 * boto3: 1.26.165
 * zeep: 4.2.1
 * aeidon: 1.12
 * iniparse: 0.5
 * mysqlclient: 2.2.0
 * Mercurial: 6.5
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 7.0.11
 * PostgreSQL server: 15.3
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: ****************
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://:weblate@weblate-redis-master:6379/1, redis://:weblate@weblate-redis-master:6379/1, regular
 * Platform: Linux 5.15.0-1042-azure (aarch64)

### Weblate deploy checks

```shell
weblate@weblate-787f889456-kcf64:/$ weblate check --deploy
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.C030) The Celery beat scheduler is not executing periodic tasks in a timely manner.
        HINT: https://docs.weblate.org/en/weblate-4.18.2/admin/install.html#celery
?: (weblate.C038) The database seems slow, the query took 138 milliseconds
        HINT: https://docs.weblate.org/en/weblate-4.18.2/admin/install.html#production-database

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.18.2/admin/install.html#collecting-errors

System check identified 7 issues (1 silenced).
```

**Comment by nijel** [comment]
You can use BORG_EXTRA_ARGS to exclude it, but it makes sense to add it to the default list.
