### ISSUE TITLE
Python format check not applied to some plural forms

### ISSUE THREAD

**Issue by VladimirSlavik** [WeblateOrg/weblate#9682]
### Describe the issue

Hello, I have a source string which is a plural using python format (the percent kind). In weblate, I have turned on "python format" as a mandatory check. Somebody just translated the string, and did not use the percent format. There is nothing shown on the string page indicating this is a problem, and this translation is pushed into the repository.

Detailed information below.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to https://translate.fedoraproject.org/translate/anaconda/rhel-9/ar/?q=%25d+_storage+device+selected&sort_by=-priority%2Cposition&checksum=
2. Observe `Flags: python-format`, lack of %d in some of the translation plurals, but no related warning or error.

### Expected behavior

There should be some indication that the check failed.

### How do you run Weblate?

Other

### Weblate versions

@yurchor can you please fill in the missing parts?

### Additional context

Detailed information:

- I am using the weblate instance at https://translate.fedoraproject.org, which runs version 4.18.2.
- The string is in Arabic, project `anaconda`, component `rhel-9`: singular ` %d _storage device selected`, plural ` %d _storage devices selected`
- Weblate correctly shows `python-format` in flags, and highlights the `%d`.
- The Arabic translation has these:
  ```
  لا جهازَ تخزينٍ مُحدَّدٌ
  جهازُ تخزينٍ واحدٍ مُحدَّدٌ
  جهازا تخزينٍ اثنان مُحددان
  %d‏ جهاز تخزين محدد
  %d‏ جهاز تخزين محدد
  %d‏ جهاز تخزين محدد
  ```
- When I run `msgfmt -c`, it detects correctly that this particular string's translation is wrong.
- The same string has been a problem already in a different component, the scenario was the same.

**Comment by yurchor** [comment]
Actually, I do not know what can be added here. It is hard to tackle with languages with many plural forms. It is allowed to skip %d for singular but I do not know how to treat this for dual and other forms in Arabic. It should be inspected by Weblate developers.

**Comment by VladimirSlavik** [comment]
Sorry, I meant the things it asks about deployment. But maybe that does not matter?

**Comment by nijel** [comment]
Weblate allows omitting the format string when there is only a single value for the plural form. So for Arabic, it is okay to have six plurals as:

* None storage device selected 
* One storage device selected 
* Two storage devices selected 
* %d storage devices selected 
* %d storage devices selected 
* %d storage devices selected

This is inconsistent with `msgfmt -c`, but allows nicer translations, and most frameworks support this behavior.

**Comment by VladimirSlavik** [comment]
Thank you, that answers why this happens.

I suppose there is no way to adjust this on a component level?

Is this check done by something that I can swap with using msgfmt? I found `PythonFormatCheck` in https://github.com/WeblateOrg/weblate/blob/main/weblate/checks/format.py, which does not appear to be easy to isolate, so the answer there is again no?

**Comment by nijel** [comment]
I've just implemented flag to enforce such format strings in https://github.com/WeblateOrg/weblate/pull/9695

The Weblate checks are not easy to isolate because they depend on the database. You can use enforced checks in Weblate to make sure that no broken strings are committed as translations, see https://docs.weblate.org/en/latest/admin/projects.html#enforced-checks

**Comment by VladimirSlavik** [comment]
Thank you! That was unexpected...

I was looking at msgfmt instead, trying to see if I could make the relaxed mode for plurals an option there. Perhaps that would be a more reasonable thing in context of the whole ecosystem - as you say, many other parts allow this, and for some format kinds it's technically sound to omit things.
