### ISSUE TITLE
Change password not working

### ISSUE THREAD

**Issue by theking2** [WeblateOrg/weblate#9688]
### Describe the issue

First I store my passwords in Keepass so I cannot forget passwords as I never know them in the first place.

After a couple of months of non usages my username/password combo was not accepted. I reset the password but also the new password is not accepted. 

It seems there is a vulnerability in your username/password implementation. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. attempt logon (fails as username/password combo seems wrong
2. reset password and
3. set a new password with the link provided
4. attempt to logon with the new password

Logon fails __Deze combinatie van gebruikersnaam/wachtwoord werd niet gevonden. Probeer het opnieuw. __

### Expected behavior

Weblate not forgetting passwords

### How do you run Weblate?

weblate.org service

**Comment by theking2** [comment]
after change  CSRF error is reported. So I assume the password was never changed. Which leads to the question how do I succesfully change the password?

**Comment by theking2** [comment]
logon attempts result in  Content-Security-Policy: De instellingen van de pagina blokkeerden het laden van een bron op inline (‘script-src’). [preload.js:136:52](moz-extension://01bafd90-71c5-4b13-82a5-3a42b7b522b1/lib/content-script/preload.js)

**Comment by nijel** [comment]
Have you tried disabling browser extensions? We definitely do not use inline Javascript...
