### ISSUE TITLE
PHP format is not aligned to sprintf

### ISSUE THREAD

**Issue by matzeeable** [WeblateOrg/weblate#9698]
### Describe the issue

When using the `php-format` check, it does not work with e.g. escaping.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

The current regular expression does not work with escaped percent characters or spaces: https://regex101.com/r/kbxtub/1

https://github.com/WeblateOrg/weblate/blob/fcd725b4abd8ceb6c3f67ff6596131edaa50175d/weblate/checks/format.py#L51-L64

### Expected behavior

`%%` and `% f` should not be found as `sprintf` placeholder.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/1008534/107dce1d-d14a-4483-a761-a38781fb949c)

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
The check is correct because the ordering of the format strings have changed. Whatever was supposed to be printed as `%d` will be printed as `%s` with your translation.

**Comment by matzeeable** [comment]
Thanks for the prompt response. Changing to `%1$s` and `%2$s` seems to resolve the issue. But why is `%%` marked as variable? `%%` is an escaped `%`.

**Comment by nijel** [comment]
Because it is token processed by printf. Weblate will not complain if that is the only missing/extra one.
