### ISSUE TITLE
Check vue_format fails for formatting modifiers

### ISSUE THREAD

**Issue by Sil3ntStorm** [WeblateOrg/weblate#9709]
### Describe the issue

When a locale reference is used `@.lower:message` https://kazupon.github.io/vue-i18n/guide/messages.html#linked-locale-messages and a translation decides it does not need the value to be lower cased and hence removes the `.lower` specifier, Weblate will complain about the format string missing and an extra format string being present of the same name just without the .lower specifier.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Have a source translation that includes a reference with .lower
Have another language translate it without the .lower specifier.

### Expected behavior

No issue is raised, as long as the main reference is the same.
Translating `@.lower:message` with `@:message` would **not** raise an error.
Translating `@:message` with `@.lower:message` would **not** raise an error.
Translating `@.lower:message` with `@:mesage` **would raise** an error since the main reference is different.

### How do you run Weblate?

Docker container

### Weblate versions

4.16.4

**Comment by nijel** [comment]
IMHO it's valid to raise the check in this case. This is definitely something that should be reviewed, and the translator can still dismiss the check in such case.
