### ISSUE TITLE
Syntax highlighting of search input

### ISSUE THREAD

**Issue by maBarabas** [WeblateOrg/weblate#9728]
### Describe the issue

1. Go to a screenshot
2. Enter "not found" as the search term
3. A lot of strings appear as search results, most of them not containing anything related to "not found"

If I enter "not" or "found" then fewer results are found compared to "not found".

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to a screenshot
2. Enter "not found" as the search term
3. A lot of strings appear as search results, most of them not containing anything related to "not found"

### Expected behavior

Search only lists strings containing "not found"

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/69897582/5dcbab51-0de7-4fd8-b454-eb44a08d528e)

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Use "not found" in this case. Search supports boolean operators, so you search for all strings not containing string found. See https://docs.weblate.org/en/latest/user/search.html#boolean-operators

**Comment by maBarabas** [comment]
I see, I'll keep the issue open as a UI bug, as this is obvious.

Maybe there should be an English representation of what I have searched for, for example: Strings not containing "found", or a mention of the search syntax next to the text box, or a graphical representation of how my query was parsed.

Just looking at the box, I think most users would assume it's a plain text search.

**Comment by nijel** [comment]
I don't think English representation would be useful for possibly long queries. Instead, doing syntax highlighting on the search input would show how it is interpreted.

What I'd like to see:

* Uppercase logical operators upon typing/pasting, so this query would become `NOT found`
* Highlight syntax using PrismJS (which we already use)

**Comment by buhtz** [comment]
IMHO the current search behavior is a bug because it do not fit the users expectations (#10793). Keep in mind the "the user" especially in translation context is (for me) a non technical person knowing nearly nothing about computers.
But having syntax enlightening is a good workaround to be more explicit about the fact that the search might behave different then the user expect.
