### ISSUE TITLE
Assign translators to a single translation.

### ISSUE THREAD

**Issue by Roheryn** [WeblateOrg/weblate#974]
I would like to be able to assign translators to a certain, single translation; without being able to edit the other translations. This would make things easier for translating into a lot of different languages. Could this somehow be made possible?
##

**Comment by nijel** [comment]
This should be possible once https://github.com/nijel/weblate/pull/963 is merged.

**Comment by nijel** [comment]
...and that was merged years ago without closing this issue, closing now.
