### ISSUE TITLE
Adding a terminology glossary also carries translation into other languages

### ISSUE THREAD

**Issue by timothyqiu** [WeblateOrg/weblate#9777]
### Describe the issue

I added this terminology glossary in Simplified Chinese:

https://hosted.weblate.org/translate/godot-engine/glossary/zh_Hans/?checksum=22a41abe0be82d9c

* Expected: This glossary is added to other languages, but untranslated
* Actual: This glossary is added to other languages, but also uses my translation for Simplified Chinese

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Click "Add term to glossary" when translating a regular string.
2. Fill in the form
   * English: `stride`
   * Chinese (Simplified): `步幅`
   * Explanation: `Offset between two lines of data, greater than or equal to the size of each line of data.`
   * Check "Terminology"
3. Click Save

Wait and see the glossary added to other languages, but they also use `步幅` as translation in these languages.

### Expected behavior

The glossary is added to other languages since it's marked as terminology, but it should not carry my translation for Simplified Chinese to other languages.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Regression from 9203c06ed97fb5454e1e19e3939681c0db7363d2 / #9661
