### ISSUE TITLE
Replace misaka with mistletoe

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#9786]
### Describe the problem

mistletoe is used for parsing Markdown in translate-toolkit so it is requirement we can not avoid. misaka is used internally by Weblate. So there are now two Markdown parsers required to run Weblate.

### Describe the solution you'd like

Replace usage of misaka with mistletoe. It should not be hard, our customization is pretty minimal: https://github.com/WeblateOrg/weblate/blob/main/weblate/utils/markdown.py

### Additional context

https://github.com/FSX/misaka:

> Misaka is not being maintained anymore. I've not been able to find time to to properly maintain this project

**Comment by itlallou** [comment]
Hello!I'd like to contribute to this

**Comment by nijel** [comment]
@itlallou You're welcome!

**Comment by subhajit20** [comment]
@nijel Hey this has been open for 3 weeks.
So I am taking this and coming up with a PR.

**Comment by nijel** [comment]
You are welcome!

**Comment by subhajit20** [comment]
@nijel Made a pr.
Can you check and let me know for further corrections needed?

**Comment by nijel** [comment]
Look at https://github.com/miyuchina/mistletoe documentation and reimplement existing behavior using it.

**Comment by Maddy0027** [comment]
@nijel if @subhajit20 is not working on this issue i would like to work on it

**Comment by JanMalte** [comment]
> @nijel if @subhajit20 is not working on this issue i would like to work on it

You are welcome to make a new PR by yourself. Just mention this issue in the description, so it will get linked here.
