### ISSUE TITLE
Translating is slow

### ISSUE THREAD

**Issue by tbodt** [WeblateOrg/weblate#9791]
### Describe the issue

Every page load takes about 2 seconds. This doesn't sound like a lot but waiting 2 seconds just to see the next message after every 2 seconds spent editing or reading a message means everything takes twice as long and it drives me crazy. The only way to reasonably get anything done is zen mode. This is a problem in every weblate instance I've used, it's not specific to a single instance's setup.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Click almost any button or link on the tool that loads a new page

### Expected behavior

Page should load in less than a second

### How do you run Weblate?

Other

**Comment by tbodt** [comment]
I attempted to reproduce this locally and my local environment ended up being actually pretty fast. Wat

**Comment by tomkolp** [comment]
The larger the design and translation memory, the slower it runs.
- In a project with 252,282,960 characters, reading the next string in normal mode takes about 5 seconds.
- In small projects loading is less than a second.

Have you restored the entire project and translation memory locally?

**Comment by nijel** [comment]
*Automatic suggestions* and *Other languages* are loaded on demand. Others are loaded directly because they are typically cheap to fetch. You can enable performance monitoring via Sentry and inspect what is causing the slowness.

**Comment by tomkolp** [comment]
> _Automatic suggestions_ and _Other languages_ are loaded on demand. Others are loaded directly because they are typically cheap to fetch. You can enable performance monitoring via Sentry and inspect what is causing the slowness.

I have performance checking enabled in sentry. Unfortunately, the free plan only allows me to sign up for 2-3 days. I have records from a few days ago, is this an inquiry we are interested in?
![image](https://github.com/WeblateOrg/weblate/assets/39633242/ac98f59f-b248-4bd1-8723-26563bc19eb9)

**Comment by nijel** [comment]
Yes, just scroll down to see what takes most of these 5 seconds.

**Comment by tomkolp** [comment]
![image](https://github.com/WeblateOrg/weblate/assets/39633242/4af02b3a-c146-47fd-9881-a482bfdf5cf2)
------------------------------------------------------------------------------------------------------------------------
![image](https://github.com/WeblateOrg/weblate/assets/39633242/1779b2a7-e8d6-4605-9f06-9e98b2bf4c9a)
------------------------------------------------------------------------------------------------------------------------
![image](https://github.com/WeblateOrg/weblate/assets/39633242/499bd610-2faa-4cee-a3da-418cc9870fc5)
------------------------------------------------------------------------------------------------------------------------
![image](https://github.com/WeblateOrg/weblate/assets/39633242/5670621d-ca3a-4f78-a634-aac3f34feff9)
------------------------------------------------------------------------------------------------------------------------
![image](https://github.com/WeblateOrg/weblate/assets/39633242/f6bca047-7525-44d3-bd0c-d443c93cf3d1)
------------------------------------------------------------------------------------------------------------------------
![image](https://github.com/WeblateOrg/weblate/assets/39633242/6535f23c-220c-4f67-8069-4e3a961e2069)

**Comment by tbodt** [comment]
>   Have you restored the entire project and translation memory locally?
I haven't tried this - i'm not sure how to export the entire state like this of a weblate instance I don't own.

Looks like most of the time is spent on sql queries - good to know!

**Comment by tomkolp** [comment]
> @tomkolp
> 
> * There are nearly 2 seconds spent on the "Other translations" tab, this is not something we see on our servers. I guess that's on one of the huge projects you have.
> * Is there anything outstanding in the permissions span? This one is double compared to what I typically see.

in the "Other translations" tab there are from 2 to 200 items, but most are 2-5 items.  

What other information can I provide?  

Personally, I don't do translations and I didn't know it was so slow now.

**Comment by tomkolp** [comment]
Alternatively, I can send sentry login details to email.  I only use Sentry to debug weblate.  I think that the errors collected there will be more useful to you, I can't do anything with this knowledge.  I don't report all bugs, only the critical ones.

**Comment by tomkolp** [comment]
> The trans_label query performance should be improved with [36c779b](https://github.com/WeblateOrg/weblate/commit/36c779b976ddbfbbcfd6b8d9c6103bedf79cf3d1). The original query shows a lot of variance (1ms - 2s), while the new one seems pretty stable around 1ms in my test environment.

I uploaded weblate updates, unfortunately I don't see any improvement in loading speed.

**Comment by nijel** [comment]
Thanks, I've looked at some performance events and did fixes in e692544506e08604ac94b961bee385bef6cb0458 and 47178b51f3d7fb35f05f3bf9307654f5522f9982.

**Comment by tomkolp** [comment]
> Thanks, I've looked at some performance events and did fixes in [e692544](https://github.com/WeblateOrg/weblate/commit/e692544506e08604ac94b961bee385bef6cb0458) and [47178b5](https://github.com/WeblateOrg/weblate/commit/47178b51f3d7fb35f05f3bf9307654f5522f9982).

I have uploaded the patches. The loading for the logged in user is unchanged, while the anonymous user improved the loading speed to about 3s. Previously it was 5s for logged in and anonymous.

**Comment by nijel** [comment]
@tomkolp Looking at current metrics in Sentry (thanks for providing that!), nearly all /translate/ requests are now below 10 seconds. I've done some performance improvements today as well, so I think we should get somewhere under 5 seconds. This is still far from being perfect, but it's progress.

Two outstanding issues would be `get_other_units` and glossary lookups performance. 

@tbodt Can you please share where did you observe the slowness so that we can investigate that as well?

**Comment by tomkolp** [comment]
> @tomkolp Looking at current metrics in Sentry (thanks for providing that!), nearly all /translate/ requests are now below 10 seconds. I've done some performance improvements today as well, so I think we should get somewhere under 5 seconds. This is still far from being perfect, but it's progress.
> 
> Two outstanding issues would be `get_other_units` and glossary lookups performance.
> 
> @tbodt Can you please share where did you observe the slowness so that we can investigate that as well?

@nijel I applied the fixes. Previously, the average string loading was 8s, now it is 4.55s.

**Comment by tbodt** [comment]
An example of the kind of page that I'm having problems with is https://hosted.weblate.org/translate/weblate/application/tok/ (just a translation page). It feels like it loads faster today, but there's still room for improvement, I'd hope for a page like that to load in under a second.

**Comment by nijel** [comment]
This one should get better once 75486c6634b5f418dd3ba0f2b24ae4ee70965afb is deployed (currently scheduled for next weekend together with https://github.com/weblate-status-bot/status/issues/570).

**Comment by nijel** [comment]
Just to provide some insight, this is how /translate/ performance was improved over the past 30 days:

![image](https://github.com/WeblateOrg/weblate/assets/212189/d4eef525-5662-4c79-a23d-a9f2169cc6a9)

I'll close this as resolved for 5.0.1. The only remaining issue is the performance of “Other units”, let's address this in https://github.com/WeblateOrg/weblate/issues/9903.

**Comment by tomkolp** [comment]
> > @tomkolp Looking at current metrics in Sentry (thanks for providing that!), nearly all /translate/ requests are now below 10 seconds. I've done some performance improvements today as well, so I think we should get somewhere under 5 seconds. This is still far from being perfect, but it's progress.
> > Two outstanding issues would be `get_other_units` and glossary lookups performance.
> > @tbodt Can you please share where did you observe the slowness so that we can investigate that as well?
> 
> @nijel I applied the fixes. Previously, the average string loading was 8s, now it is 4.55s.

After moving weblate from SAS drives to nvme, I managed to get down to 3.25s per string.

**Comment by tbodt** [comment]
Thanks for working on this!
