### ISSUE TITLE
Line number doesn’t match source string in link to translation file

### ISSUE THREAD

**Issue by yvanzo** [WeblateOrg/weblate#9792]
### Describe the issue

When translating any string, in the panel “String information”, the last item “Translation file” has a link to the source translation file (most often with `.pot` name extension). This link has a fragment with a line number always set to 1.

I would expect this line number to match the source string definition instead, otherwise to not have any fragment in this link.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to https://hosted.weblate.org/translate/weblate/application/en/?checksum=f5351ff85ab23173
2. In the column on the right side,
   in the panel “String information”,
   in the last item “Translation file”,
   in the link named “weblate/locale/django.pot”,
   in the target `https://github.com/WeblateOrg/weblate/blob/main/weblate/locale/django.pot#L1`,
   the fragment [L1](https://github.com/WeblateOrg/weblate/blob/main/weblate/locale/django.pot#L1) doesn’t match the source string in that remote page.

### Expected behavior

The fragment should probably be something like [L104-108](https://github.com/WeblateOrg/weblate/blob/main/weblate/locale/django.pot#L104-L108) that matches the whole definition, or at least one its lines such as [L107](https://github.com/WeblateOrg/weblate/blob/main/weblate/locale/django.pot#L107).

### How do you run Weblate?

weblate.org service

**Comment by Geeyun-JY3** [comment]
See #7738
