### ISSUE TITLE
Save button does not work for Users team

### ISSUE THREAD

**Issue by urbalazs** [WeblateOrg/weblate#9800]
### Describe the issue

I have exactly the same issue as described [here](https://github.com/WeblateOrg/weblate/issues/7602#issuecomment-1634346378). The Save button does nothing for Users team.

I have 4.18.2.1 as docker image. In the mentioned issue you said, it was fixed in 4.15.1 but I have newer version with the same issue.

Additional information:

I updated the docker container from 4.18.2.1 to 4.18.2.2 and now I have two Users team: the original one (with ID = 3) and a completely new one (with ID = 126). I cannot change the original one because the Save button doesn't work, but I can change the new one.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to /manage/teams/
2. Modify any team but Users --> it works
3. Try to modify the Users team --> Save button doesn't work

### How do you run Weblate?

Docker container

### Weblate versions

4.18.2.1
4.18.2.2

**Comment by nijel** [comment]
What browser do you use? Do you have any browser extensions which might be causing this? Any errors in the browser console?

I've just tested this on Firefox and Chrome, and it works just fine.

**Comment by nijel** [comment]
…ah now I see it: It seems to happen only in groups with enough users to trigger pagination.
