### ISSUE TITLE
Translator header entries (comments) of Weblate’s own translation files seem to be removed in every `i18n: Update PO files` commit

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#9817]
### Describe the issue

The translator header entries (comments) of Weblate’s own translation files (`.po`) seem to be removed in every [`i18n: Update PO files` commit](https://github.com/search?q=repo%3AWeblateOrg%2Fweblate+%E2%80%8Bi18n%3A%C2%A0Update%C2%A0PO%C2%A0files&type=commits) lately.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Example: https://github.com/WeblateOrg/weblate/commit/a7b41644b0d77aec8cef1f143a1e0cd0d68bcb4a#diff-4a196213cd83aa9e10648491dcaa556e18eb176f6894348a106d1c2180c2e91dL4-L5
Corresponding translation file snapshot before this commit: https://github.com/WeblateOrg/weblate/blob/8c0e6eb7cc3654677259584cd8027273d6956fde/docs/locales/ar/LC_MESSAGES/docs.po#L3-L7
Corresponding translation file snapshot after this commit: https://github.com/WeblateOrg/weblate/blob/a7b41644b0d77aec8cef1f143a1e0cd0d68bcb4a/docs/locales/ar/LC_MESSAGES/docs.po#L3-L6

### Expected behavior

The translator header entries (comments) of translation files (`.po`) are not removed in every `i18n: Update PO files` commit.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/49396421/b5965f3b-8e0f-475c-a550-fa5aa9d0fdab)

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 5.0 (weblate-5.0-41-gbe542d3c9b)

**Comment by nijel** [comment]
Caused by using `reuse annotate` inside the script, not sure if there is a way around. What is the reason for keeping the translators in the file anyway?

**Comment by Geeyun-JY3** [comment]
> What is the reason for keeping the translators in the file anyway?

I just think it is strange that the translators comment lines were recently removed from the translation file after being kept for years.
So these comments are added by gettext and it is not optional? Is it a convention of the PO files?

As for the reason for keeping the translators comment lines in the file, I think it is necessary to credit the translators and the PO file file is a good place to do this. I would prefer to keep these comments if this is a convention and it can be done by gettext automatically.

One more thing: Is it possible to bring the removed translators comments back?

**Comment by nijel** [comment]
These comments are added by Weblate add-on (https://docs.weblate.org/en/latest/admin/addons.html#contributors-in-comment). It is a convention, not a gettext standard (that only covers `Last-Translator` header).

While it is useful to credit translators, I'm uncertain if this is the best way to do this as only a few people will look inside these files.

Anyway, if somebody wants to bring these back, here is a list of commits that could have removed them:

* 1c51d58f5e i18n: Update PO files
* a7b41644b0 i18n: Update PO files
* c9cbe50a92 i18n: Update PO files
* f4b17ca916 i18n: Update PO files
