### ISSUE TITLE
Diff in history events does not show the real changes

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#9821]
### Describe the issue

The history events do not show the real diff.
Are there some history events missing or is it a diff rendering bug?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

https://hosted.weblate.org/translate/weblate/application/zh_Hans/?checksum=97a6aaa4a3cf7d34#history

### Expected behavior

The actual translation text change is

```diff
---由 {username} 邀请至 {site_title}。
+++由 {username} 邀请至 {project} 项目。
```

The addition (green part) should cover `project} 项目` instead of only `project}`. Currently ` 项目` is not covered as green in this example.
But the amount of edited characters is right🤔.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/49396421/5ecd0bc6-ab06-4ed1-9af4-a5d1d7bebadf)
![image](https://github.com/WeblateOrg/weblate/assets/49396421/08f7206f-f407-43ab-af75-536575c666eb)

### How do you run Weblate?

weblate.org service

### Weblate versions

Weblate 5.0.1-dev (weblate-5.0-208-ge6843a560e)

**Comment by yangyangdaji** [comment]
@Geeyun-JY3 

It's a rendering bug, as I pointed out on https://github.com/WeblateOrg/weblate/issues/9832

> In this [example](https://hosted.weblate.org/translate/flathub/frontend/pl/?checksum=2df913c5b01b45f4), the diff view only highlights `{{appName}}` does not highlight other characters.
> 
> ![Screenshot_2023-08-30-16-33-57-547_com lemurbrowser exts-edit](https://user-images.githubusercontent.com/108261729/264295071-f0cd2180-d615-4cb2-9562-df684fc1ef1b.jpg)

**Comment by Geeyun-JY3** [comment]
Seems related to the placeables🤔.

**Comment by Geeyun-JY3** [comment]
It seems to be related to theplaceables.
