### ISSUE TITLE
Broken repository browser URL

### ISSUE THREAD

**Issue by anuj-scanova** [WeblateOrg/weblate#9823]
### Describe the issue

I have a private repository with the file structure
```
/src/admin_log/models.py
```
and using the `qa` branch of the repository.

In the **Repository Browser**, provided the following path (added `src` to the path)
```
https://github.com/org/repository/blob/{{branch}}/src/{{filename}}#L{{line}}
```

However, It gives error
```
This component is set up incorrectly.

The repository browser URL points to non-existing locations:

https://github.com/org/repository/blob/qa/src/admin_log/models.py#L18 (404 Client Error: Not Found for url: https://github.com/org/repository/blob/qa/src/admin_log/models.py#L18)
This can happen if the path within the translation files contains references to a parent directory, or is absolute.

Appeared 7 hours ago, last seen 6 minutes ago
```

However, clicking the URL takes you to the right file and line number in Github.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Configure **Repository Browser** to a private repository

### Expected behavior

The URL should be working without giving any error.

### Screenshots

<img width="1660" alt="Screenshot 2023-08-29 at 8 17 41 AM" src="https://github.com/WeblateOrg/weblate/assets/105233146/42399bc1-4712-49aa-979c-6056092c9a03">

### How do you run Weblate?

Docker container

### Weblate versions

[Weblate 4.14.1](https://weblate.org/)

**Comment by nijel** [comment]
Perhaps the GitHub repo is not public and because of that Weblate gets 404?
