### ISSUE TITLE
Inconsistent history event names

### ISSUE THREAD

**Issue by urbalazs** [WeblateOrg/weblate#9824]
### Describe the issue

The name of history events are inconsistent, see [this section](https://github.com/WeblateOrg/weblate/blob/main/weblate/trans/models/change.py#L284-L422). Some examples:

- Resource update: noun + verb
- Translation completed: noun + verb past
- New translation: no verb
- Removed comment: verb past + noun

They should be consistent like "Something happened" (noun + verb past):

- Resource updated
- Translation completed
- Translation added 
- Comment removed

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Open [this section](https://github.com/WeblateOrg/weblate/blob/main/weblate/trans/models/change.py#L284-L422)

or

Open `/changes/browse/PROJECT/COMPONENT/` to see all events in the GUI.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
https://github.com/WeblateOrg/weblate/pull/10135 tries to consolidate this, reviews welcome.

**Comment by Geeyun-JY3** [comment]
I have been confused by these inconsistent event names for a long time while translating. 
Currently, some of the Simplified Chinese translations of these event names actually imply that it was _someone_ who did these events, which is in the active voice. These event names shown below the user’s avatar in the UI also make the active voice look reasonable: this layout implies that someone (the avatar) did something (the event shown below).

If #10135 is implemented (changing all these event names to noun + verb past participle, that is passive voice), is it still necessary to imply that was _someone_ who did these events in translations?

**Comment by nijel** [comment]
Typically there is someone who did the action. But there are also automated events (automatic translation) or actors outside Weblate (changes in the repository).
