### ISSUE TITLE
Info icon redirects to 404 page

### ISSUE THREAD

**Issue by eschumacher-99** [WeblateOrg/weblate#9830]
### Describe the issue

The info icon redirects to the corresponding page in the Docs. However, if the page does not exist in the set interface language, the user lands on a 404 page. I would expect that it would then redirect to the English page instead. So, unfortunately, most translators have no way to get the relevant info.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Set the user interface language to German
2. Go to a project
3. Select a Component
4. Select a language
5. Scroll to string status
6. Click the info icon on the right
7. Redirects to [https://docs.weblate.org/de/weblate-4.13.1/user/translating.html#strings-to-check](https://docs.weblate.org/de/weblate-4.13.1/user/translating.html#strings-to-check)

### Expected behavior

Opens the corresponding page in the Docs in German or if not available in the default language.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/77051325/14991e6a-7857-4848-abca-b736e586cfea)
![image](https://github.com/WeblateOrg/weblate/assets/77051325/8af9cdf8-93ef-4896-99b2-80b6b44c2d2a)

### How do you run Weblate?

PyPI module

### Weblate versions

4.13.1

**Comment by nijel** [comment]
For some reason this version of documentation was not built, I've just triggered it manually.
