### ISSUE TITLE
Automatic translation suggestion origin

### ISSUE THREAD

**Issue by FrostKiwi** [WeblateOrg/weblate#9842]
### Describe the problem

Expanding on https://github.com/WeblateOrg/weblate/issues/9545, it would be excellent if we could see which service an automatic translation comes from, since when letting AI do suggestions, it simply says suggestion by "anonymous".

### Describe the solution you'd like

It would give some more context to the translator, if the suggestion came not from anonymous, but from the Weblate default account with appended (Automatic translation - DeepL), to indicate that it was an AI translation and which service was used.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/60887273/b36f6648-c798-4b80-8624-72f3f37f9bdd)

**Comment by nijel** [comment]
Related to https://github.com/WeblateOrg/weblate/issues/9545

**Comment by nijel** [comment]
Implemented in a7c352ed0db.

**Comment by FrostKiwi** [comment]
ヽ(*・ω・)ﾉ Many thanks
