### ISSUE TITLE
Repeated and missing entries in license list

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#9848]
### Describe the issue

https://hosted.weblate.org/accounts/profile/#licenses
has a lot of repeated components for me, and it seems to only
list stuff I have contributed to more recently, as opposed to contributed to in the past.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to https://hosted.weblate.org/accounts/profile/#licenses
2. Notice stuff is repeated
3. Search for "skytube" or similar without finding it.
4. Translate some strings in https://hosted.weblate.org/projects/skytube/strings/nb_NO/ and now it is there.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/13802408/6a8e8cba-01e8-4ace-8506-324382c0b188)

### Exception traceback

```pytb
I would want it to only list each project contributed to once.
```

### How do you run Weblate?

weblate.org service

### Additional context

Not if entries are repeated if there are contributions in multiple languages.
Edit: Turns out they are
![image](https://github.com/WeblateOrg/weblate/assets/13802408/4d646880-c3a8-4f43-a5dc-d72768df089a)

**Comment by nijel** [comment]
It intentionally lists only licenses from recent contributions (in 90 days) for performance reasons.
