### ISSUE TITLE
Repeated entries in list of failing checks

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#9853]
### Describe the issue

All failing checks are shown twice in two separate lists.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to failing checks
2. Scroll down
3. Get the same list twice

### Expected behavior

Expected just the one list

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/13802408/730ab7e0-4269-4d39-b3c2-57b5dd096d16)
…

![image](https://github.com/WeblateOrg/weblate/assets/13802408/2230a008-aaed-43f0-8b5a-1d412a53fca0)

### How do you run Weblate?

weblate.org service

### Additional context

Possibly related to https://github.com/WeblateOrg/weblate/issues/9848 ?

**Comment by nijel** [comment]
Once it is for a whole project and once for each user language in a project.  It has been like this for years...
