### ISSUE TITLE
Add Approved Percentage as a Column in the Object List

### ISSUE THREAD

**Issue by michael-smt** [WeblateOrg/weblate#9855]
### Describe the problem

Currently in the object list (for projects, components & languages) there is no percentage shown that represents the blue bar.

It is cumbersome to collect a overview on the approval percentage over multiple languages or components.

### Describe the solution you'd like

Similar to the "Translated" column there would also be a "Approved" column with the same behaviour (percentage/green checkmark).

### Describe alternatives you've considered

Re-use the existing "Translated" column and rename it to "Translated/Approved". When approval is applicable, replace the values in the "Translated" column with the approval percentage. Or show two percentage values. While this saves space, readability suffers and can become confusing.

Making the columns customizeable seem like much too much effort. There is still enough horizontal space left in desktop mode that a additional column would fit.

### Screenshots

![Screenshot](https://github.com/WeblateOrg/weblate/assets/139211597/211a8227-1d2c-43a3-ae8a-e9dd3bcbd788)

### Additional context

In our translation projects we use the precentage of approved strings as a quality gateway for two things:
- When using a intermediate language file, the main translation work shall only start when the monolingual base file's approval is over a certain percentage
- A language shall only be intergrated into the software when it's approval is over a certain percentage (similar to #3436).

**Comment by emmapeel2** [comment]
Yes please, we also need this on our project.
