### ISSUE TITLE
Newlines not handled properly in CSV

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#987]
It seems that something on the way just strips `\` from the string keeping only `n` there:

``` diff
-"til: \n{0} ({1})\n\n"
+"til: n{0} ({1})nn"
```
##

**Comment by nijel** [comment]
See also https://github.com/translate/translate/issues/3246

**Comment by Cussa** [comment]
Hi, there is some new position about this bug? I know that it's on the library, but is there any idea if it will be fixed?

I'm having a lot of problems because of it now.

**Comment by nijel** [comment]
AFAIK nobody is working on this right now. The original translate-toolkit maintainers are now pretty much doing only pull requests review and merging, most of the recent new code there has come from me...

**Comment by nijel** [comment]
Proposed fix is here: https://github.com/translate/translate/pull/3880

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has been fixed in translate-toolkit by accepting https://github.com/translate/translate/pull/3880.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
