### ISSUE TITLE
Add glossary support for ModernMT

### ISSUE THREAD

**Issue by urbalazs** [WeblateOrg/weblate#9881]
### Describe the problem

ModernMT has `glossaries` [request parameter](https://www.modernmt.com/api/#translate-text) to use glossaries for the translation of the input texts. It works fine if I call the API directly from command line, but Weblate doesn't honor this parameter. It would be nice to add an optional support for it.

### Describe the solution you'd like

- Extend the ModernMT [setting form](https://github.com/WeblateOrg/weblate/blob/main/weblate/machinery/forms.py#L208-L212) with a new field where the glossary IDs and context vestors can be added as comma separated string since more than one glossary can be use at the same time.
- Extend the [request](https://github.com/WeblateOrg/weblate/blob/main/weblate/machinery/modernmt.py#L74) with the `glossaries` paramter.

### Additional context

From the ModernMT [documentation](https://www.modernmt.com/api/#context-vector):

> Glossaries
> This parameter is a string, consisting of a list of memory ids separated by a comma, that denotes the glossaries to be used during the translation. Therefore, when included, it indicates that the glossary entries contained in the specified memories are to be used. If a non-existent memory is provided, it will be ignored.

> Context vector
> The context vector is the object which leverages ModernMT adaptation during the translation. It consists of a list of memories, each one with a corresponding weight. The higher the weight is, the more the memory content will influence the translation result.
> This is an example of a context vector: `37787:0.457,37784:0.2`. It contains the memory `37787` with a weight of `0.457`, and the memory `37784` with a weight of `0.2`.

**Comment by nijel** [comment]
Related to https://github.com/WeblateOrg/weblate/issues/7086

**Comment by gersona** [comment]
for the sake of clarity,
You want to have a field where we can provide context vectors or glossary IDs that will be included in ALL translation requests ?

**Comment by nijel** [comment]
I understand it that way, I'd avoid doing something more complex for now.
