### ISSUE TITLE
same word but different meaning in two different component, but they are coupled somehow and cannot be edited separately

### ISSUE THREAD

**Issue by yilmazdurmaz** [WeblateOrg/weblate#9889]
### Describe the issue

check this glossary item: 
https://hosted.weblate.org/translate/godot-engine/glossary/tr/?checksum=ed92a0a67abbe9d3&q=switch&sort_by=-priority%2Cposition

You will see two other occurrences in two different components. though words are the same, their meanings are different.
- the one in documentation component uses as is for programming construct "switch" so it must keep the word as is.
- the other has the meaning of swicthing which can be translated.

but they are somehow now linked and changes made on one affects the other.

I already knew that adding an item into glossary distributes it into "empty" translations. that is kinda nice, but must be handled with care.

but this is different. these are not in the glossary and they should be editable completely separately. otherwise there is no meaning to write context for them.

If need be, these translation can be added as "suggestions" to other strings, but they shouldn't be coupled. and If this is something system wide, please change this behaviour.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

I don't know, for the moment, if there are other strings with this problem.

1- start with this item: https://hosted.weblate.org/translate/godot-engine/glossary/tr/?checksum=ed92a0a67abbe9d3&q=switch&sort_by=-priority%2Cposition
2- see "other occurences"
3- check both occurences; you will see I tried to edit them, and they are coupled

### Expected behavior

only glossary should distribute translations to other components, and components should not affect each other as their contexts might differ causing different translation meanings.

### How do you run Weblate?

weblate.org service

**Comment by linsui** [comment]
I thought I encountered the same problem. I tested the markdown support for a component which was coverted to .po. When the strings in the new markdown component are edit, the same strings in the .po file is also changed.

**Comment by nijel** [comment]
You should disable translation propagation in such cases, see https://docs.weblate.org/en/latest/admin/projects.html#allow-translation-propagation and https://github.com/WeblateOrg/weblate/issues/3166

**Comment by linsui** [comment]
Thanks!

**Comment by yilmazdurmaz** [comment]
Seems I used wrong words while searching, and I did not think it would be under discussion this long.

I need to grasp this new info first, but just a "disable" does not feel the right word/thing for the moment.

"propagating as suggestions"; I need to first check if you have already discussed this solution or have a setting for it.
