### ISSUE TITLE
MR to gitlab error due to parse vcs url wrong

### ISSUE THREAD

**Issue by Yoshino-s** [WeblateOrg/weblate#9890]
### Describe the issue

When using Gitlab MR as vcs with custom port in vsc url like

```
ssh://git@gitlab.company:222/aaa/bbb.git
```

An error will be reported when push change

```
Failed to create pull request: 404 Project Not Found (-1)
```

And I use sentry to track error and i found weblate request to this url

```
https://gitlab.company/api/v4/projects/222%2Faaa%2Fbbb/merge_requests
```

Which parse 222 as part of repo name.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Set the vcs to gitlab
2. Set the vcs url to `git@gitlab.company:222/aaa/bbb.git`
3. make translate
4. push change to Gitlab MR
5. trigger an error

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.18.2
 * Django: 4.2.2
 * siphashc: 2.1
 * translate-toolkit: 3.9.2
 * lxml: 4.9.2
 * Pillow: 9.5.0
 * nh3: 0.2.13
 * python-dateutil: 2.8.2
 * social-auth-core: 4.4.2
 * social-auth-app-django: 5.2.0
 * django-crispy-forms: 2.0
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.2
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.12.2
 * rapidfuzz: 3.1.1
 * openpyxl: 3.1.2
 * celery: 5.3.1
 * django-celery-beat: 2.5.0
 * kombu: 5.3.1
 * translation-finder: 2.15
 * weblate-language-data: 2023.5
 * html2text: 2020.1.16
 * pycairo: 1.24.0
 * PyGObject: 3.44.1
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.3.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.26.0
 * Cython: 0.29.35
 * misaka: 2.1.1
 * GitPython: 3.1.31
 * borgbackup: 1.2.4
 * pyparsing: 3.0.9
 * pyahocorasick: 2.0.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.1.0
 * Python: 3.11.4
 * Git: 2.30.2
 * psycopg2: 2.9.6
 * phply: 1.2.6
 * ruamel.yaml: 0.17.32
 * tesserocr: 2.6.0
 * boto3: 1.26.164
 * zeep: 4.2.1
 * aeidon: 1.12
 * iniparse: 0.5
 * mysqlclient: 2.2.0
 * Mercurial: 6.4.5
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 7.2.0
 * PostgreSQL server: 15.4
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.126.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://:JhCUG84N7w@redis-master.storage:6379/1, redis://:JhCUG84N7w@redis-master.storage:6379/1, regular
 * Platform: Linux 4.18.0-477.15.1.el8_8.x86_64 (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

WARNINGS:
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.18.2/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 5.0.
        HINT: https://docs.weblate.org/en/weblate-4.18.2/admin/upgrade.html

System check identified 3 issues (1 silenced).
```

### Additional context

[sentry.json.zip](https://github.com/WeblateOrg/weblate/files/12555631/sentry.json.zip)

**Comment by nijel** [comment]
`ssh://git@gitlab.company:222/aaa/bbb.git` seems to work just fine, it is only `git@gitlab.company:222/aaa/bbb.git` which causes such issue.

**Comment by nijel** [comment]
…what is correct, as that matches what Git itself does:

* `ssh://git@gitlab.company:222/aaa/bbb.git` is interpreted as `/aaa/bbb.git` repo on `gitlab.company` server on port 222. 
* `git@gitlab.company:222/aaa/bbb.git` is interpreted as `222/aaa/bbb.git` repo on `gitlab.company` server (and default SSH port)

**Comment by nijel** [comment]
And there are two pieces of code dealing with this in Weblate, where one is correct (as described above) and the second one is broken (as you observe).
