### ISSUE TITLE
Ability to perform a translation using the API

### ISSUE THREAD

**Issue by Exifers** [WeblateOrg/weblate#9896]
### Describe the problem

As far as I understand, the API allows only to create source units, but not to add translated content.

### Describe the solution you'd like

I would like to be able to translate some units using the API.

### Describe alternatives you've considered

Submitting a post on the form url used by the frontend, but this requires a csrf token (which I can't get from an API key), and the form seems to use some computed hashes.

### Additional context

This would be a great feature. I need this for a script that detects added keys in a pre-commit hook and asks for translations in languages that the developer knows.

**Comment by nijel** [comment]
You can change units here: https://docs.weblate.org/en/latest/api.html#patch--api-units-(int-id)-
