### ISSUE TITLE
Github release notes contain markup leftovers

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#9910]
### Describe the issue

Not a big deal, but since the 5.0 release there are fragments of markup left in the release notes. Just take a look at:
https://github.com/WeblateOrg/weblate/releases/tag/weblate-5.0.1 and 5.0
There are `{.xxx "..."}` all over the place.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

https://github.com/WeblateOrg/weblate/releases/tag/weblate-5.0.1

### How do you run Weblate?

Other

**Comment by Geeyun-JY3** [comment]
The [Weblate 5.0 release note on GitHub](https://github.com/WeblateOrg/weblate/releases/tag/weblate-5.0) is still not fixed.

**Comment by nijel** [comment]
Fixed that manually now, but there is really no intention to fix all the past release notes.
