### ISSUE TITLE
Utilize expression index for auth

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#9973]
### Describe the problem

Weblate does manually create index using `CREATE UNIQUE INDEX` during the `weblate.auth` model migration.

### Describe the solution you'd like

This should be changed to use Django standard expression index `UniqueConstraint(...Upper(...))` instead for better readability and portability.

### Additional context

Need Django 4.0+ (Weblate already requires 4.2).

See also https://stackoverflow.com/a/69752763/225718 and https://stackoverflow.com/a/66966391/225718

**Comment by mohebmithani** [comment]
Hi @nijel I would like to take this one for my first hacktoberfest contribution

**Comment by nijel** [comment]
You're welcome

**Comment by nishitiwari22** [comment]
Is this still open? I am looking to contribute to it I am newbie as well.

**Comment by mohebmithani** [comment]
@nishitiwari22 i'm working on it. Apologies.

**Comment by mohebmithani** [comment]
@nijel i've sent the PR. Let me know if it needs some changes
