### ISSUE TITLE
Browse mode for power users: add keyboard arrows for going forward, and back while browsing

### ISSUE THREAD

**Issue by alltheseas** [WeblateOrg/weblate#9979]
### Describe the problem

_what happens_

When "browsing" all strings for a particular language, in an application translated in Weblate, I don't have a quick way to go to the next page of strings. When I browse to the bottom of the page, I cannot easily proceed to the next page. I have to 
1) scroll back to the top of the page, and
2) click on the right arrow icon

### Describe the solution you'd like

_what I suggest should happen_

When browsing all strings of translations with multiple pages of strings, I should be able to use the arrows on my keyboard to move forward to the next page (right arrow), and move back to the previous page (left arrow). 

This will save me time, and reduce friction while browsing all strings for a particular language.

### Describe alternatives you've considered

Keep suffering

**Comment by varunTarone** [comment]
Hey @alltheseas!

This is my first time contributing to open-source and also participating in **Hacktoberfest**.
My tech stack is : HTML, CSS, JS & React (intermediate). 

Can you assign me this issue?

Also, pls guide me during the process of fixing this issue.

**Comment by alltheseas** [comment]
Welcome to FOSS @varunTarone !

I do not have permissions for this repository - consider yourself assigned!

Lmk if you have questions

**Comment by varunTarone** [comment]
Awesome! 
So meanwhile, I was searching through the codebase, but I was unable to find the exact code where the feature needs to be implemented. Can u also share your slack so that we can discuss how should I step by step solve this issue and what change need to be done in the code 😃 
Plus should I use this installation method for contribution: https://docs.weblate.org/en/latest/admin/install/source.html#installing-from-sources
or simply Docker.

Also I will tag @nijel so that he can assign me this issue and provide some help regarding it. 

Thank You 👋

**Comment by alltheseas** [comment]
> searching through the codebase (still searching), but I was unable to find the exact code where the feature needs to be implemented. 

Did you find where the front and back arrows for navigating forward and back are? 

> slack

I'm a new contributor here - try tagging the owners of this repo

**Comment by alltheseas** [comment]
> Live chat about Weblate is available at Libera.Chat IRC network. The channel name is #weblate. This can be accessed by, for example, https://web.libera.chat/#weblate or an IRC client installed on your computer.

**Comment by varunTarone** [comment]
> > searching through the codebase (still searching), but I was unable to find the exact code where the feature needs to be implemented. 
> 
> Did you find where the front and back arrows for navigating forward and back are? 
> 
> > slack
> 
> I'm a new contributor here - try tagging the owners of this repo 

Oh ok 👍 am on it.
And also, sorry for distributing you again 🙏 
And thank you for the help.

**Comment by nijel** [comment]
Weblate currently uses Mousetrap to bind keyboard shortcuts:

https://github.com/WeblateOrg/weblate/blob/1576de13c4faef59286279c9e493a116d722bafb/weblate/static/editor/full.js#L85-L88

A similar script needs to be implemented for the [browse](https://github.com/WeblateOrg/weblate/blob/main/weblate/templates/browse.html) page and documented: https://docs.weblate.org/en/latest/user/translating.html#keyboard-shortcuts

Having https://github.com/WeblateOrg/weblate/issues/5064 implemented as well would be nice to show users what keyboard shortcuts are available on the current page.

**Comment by nijel** [comment]
Great to see somebody picking this! I'd recommend leaving out https://github.com/WeblateOrg/weblate/issues/5064 as a separate pull request as it is a separate issue and changes will be then easier to review.
