### ISSUE TITLE
Xliff format being returned as v1.1

### ISSUE THREAD

**Issue by nicemandan** [WeblateOrg/weblate#9996]
### Describe the issue

I'm writing a Unity plugin for Weblate and Unity only supports Xliff 1.2

We're using a self-hosted instance of Weblate 4.18.2  and calling the following api with the format set to xliff:
/api/translations/(string: project)/(string: component)/(string: language)/file/?format=xliff

This will return an xliff string in 1.1 format which is incompatible with Unity e.g. :
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.1" version="1.1">

This is also the version if downloaded from the Weblate Dashboard.

The 4.18.2 documentation hints at the use of v1.2, but it's more explicitly described in the 5.1 documentation
https://docs.weblate.org/en/weblate-4.18.2/formats/xliff.html
https://docs.weblate.org/en/latest/formats/xliff.html

Also, the source format for the translations is from xliff 1.2 files stored in Github, exported from Unity (note that omitting the format in the api call will just directly serve the 1.2 xliff files from the VCS)

Is this just a case of needing to upgrade or is this a bug in the api?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Call the translations api using the ?format=xliff query string: 
/api/translations/(string: project)/(string: component)/(string: language)/file/?format=xliff
2. Observe the xliff version in the response is 1.1

### Expected behavior

Expecting to see v1.2 in the xliff response e.g.
<xliff xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">

### How do you run Weblate?

weblate.org service

### Weblate versions

4.18.2

**Comment by nijel** [comment]
Weblate should preserve XLIFF version used in the file. If you use conversion during download, it will always generate XLIFF 1.1, see https://docs.weblate.org/en/latest/user/files.html#download

**Comment by nijel** [comment]
The file will be update with same xliff version, it's only the download conversion which always generates xliff 1.1. Remove `?format=xliff` from the download URL to avoid the conversion.
