### ISSUE TITLE
Mobile website width issues

### ISSUE THREAD

**Issue by Daviteusz** [WeblateOrg/weblate#9998]
### Describe the issue

The scroll bar for tables is missing making the page not fit the screen

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Open Chrome, Firefox or similar browser
2. Go to project information or history tab
3. Zoom out

### Expected behavior

The site should fit the width of the screen in every possible place.

### Screenshots

<img src=https://github.com/WeblateOrg/weblate/assets/11527277/12392233-78f8-45df-aa63-3342a3d4a27d width=30%>
<img src=https://github.com/WeblateOrg/weblate/assets/11527277/c4818cfa-f720-42d3-b951-902aa473d45d width=30%>

### How do you run Weblate?

weblate.org service

**Comment by Maddy0027** [comment]
@nijel i like to work on this issue but i am new to this so i would like if you help me with this my tech stack are HTML CSS javascript c++ and python

**Comment by Maddy0027** [comment]
@nijel do you want to adjust overflow that is cause due reduce in screen size when we shift form desktop to mobile or tab version

**Comment by nijel** [comment]
There are more issues on the page, for start just pick one of them to address.

Quickly I've identified two of them:

* Strings stats table, that probably needs horizontal scrollbar
* Activity chart should probably use narrower bars on smaller screens

**Comment by Maddy0027** [comment]
is there is discord or slack channel where i can get in touch with you

**Comment by nijel** [comment]
Sorry, I'm not anywhere like that currently.
